SUMO - Simulation of Urban MObility: NIImporter_ITSUMO::Handler Class Reference
NIImporter_ITSUMO::Handler Class Reference
Data Structures
struct Lane
struct LaneSet
struct Section
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
Handler (NBNetBuilder &toFill)
Contructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~Handler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
Private Member Functions
Handler (const Handler &s)
invalidated copy constructor
Handler & operator= (const Handler &s)
invalidated assignment operator
Private Attributes
std::vector< Lane > myCurrentLanes
std::vector< LaneSet * > myCurrentLaneSets
std::map< std::string, LaneSet * > myLaneSets
NBNetBuilder & myNetBuilder
The container to fill.
std::map< std::string, std::string > myParameter
A temporary parameter map.
std::vector< Section * > mySections
Detailed Description
Definition at line 81 of file NIImporter_ITSUMO.h.
Constructor & Destructor Documentation
Handler() [1/2]
NIImporter_ITSUMO::Handler::Handler (NBNetBuilder & toFill)
Contructor.
Parameters
[in] toFill The container to fill
Definition at line 140 of file NIImporter_ITSUMO.cpp.
~Handler()
NIImporter_ITSUMO::Handler::~Handler ()
Destructor.
Definition at line 145 of file NIImporter_ITSUMO.cpp.
Handler() [2/2]
NIImporter_ITSUMO::Handler::Handler (const Handler & s) private
invalidated copy constructor
Member Function Documentation
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
myCharacters()
void NIImporter_ITSUMO::Handler::myCharacters (int element, const std::string & chars) protected virtual
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented from GenericSAXHandler.
Definition at line 164 of file NIImporter_ITSUMO.cpp.
References NIImporter_ITSUMO::ITSUMO_TAG_END_NODE, NIImporter_ITSUMO::ITSUMO_TAG_LANE_ID, NIImporter_ITSUMO::ITSUMO_TAG_LANE_POSITION, NIImporter_ITSUMO::ITSUMO_TAG_LANESET_ID, NIImporter_ITSUMO::ITSUMO_TAG_LANESET_POSITION, NIImporter_ITSUMO::ITSUMO_TAG_MAXIMUM_SPEED, NIImporter_ITSUMO::ITSUMO_TAG_NODE_ID, NIImporter_ITSUMO::ITSUMO_TAG_NODE_NAME, NIImporter_ITSUMO::ITSUMO_TAG_SECTION_ID, NIImporter_ITSUMO::ITSUMO_TAG_START_NODE, NIImporter_ITSUMO::ITSUMO_TAG_X_COORD, NIImporter_ITSUMO::ITSUMO_TAG_Y_COORD, myParameter, and StringUtils::prune().
myEndElement()
void NIImporter_ITSUMO::Handler::myEndElement (int element) protected virtual
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented from GenericSAXHandler.
Definition at line 214 of file NIImporter_ITSUMO.cpp.
References TplConvert::_2double(), TplConvert::_2int(), NIImporter_ITSUMO::Handler::LaneSet::from, NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), NIImporter_ITSUMO::Handler::LaneSet::id, NBNodeCont::insert(), NBEdgeCont::insert(), NIImporter_ITSUMO::ITSUMO_TAG_LANE, NIImporter_ITSUMO::ITSUMO_TAG_LANESET, NIImporter_ITSUMO::ITSUMO_TAG_NODE, NIImporter_ITSUMO::ITSUMO_TAG_SECTION, NIImporter_ITSUMO::ITSUMO_TAG_SIMULATION, NIImporter_ITSUMO::Handler::LaneSet::lanes, myCurrentLanes, myCurrentLaneSets, myLaneSets, myNetBuilder, myParameter, mySections, NBNodeCont::retrieve(), NIImporter_ITSUMO::Handler::LaneSet::to, NBNetBuilder::transformCoordinate(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, NIImporter_ITSUMO::Handler::LaneSet::v, and WRITE_ERROR.
myStartElement()
void NIImporter_ITSUMO::Handler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 149 of file NIImporter_ITSUMO.cpp.
References NIImporter_ITSUMO::ITSUMO_TAG_LANESET, NIImporter_ITSUMO::ITSUMO_TAG_NODE, and myParameter.
operator=()
Handler& NIImporter_ITSUMO::Handler::operator= (const Handler & s) private
invalidated assignment operator
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myCurrentLanes
std::vector<Lane> NIImporter_ITSUMO::Handler::myCurrentLanes private
Definition at line 145 of file NIImporter_ITSUMO.h.
Referenced by myEndElement().
myCurrentLaneSets
std::vector<LaneSet*> NIImporter_ITSUMO::Handler::myCurrentLaneSets private
Definition at line 160 of file NIImporter_ITSUMO.h.
Referenced by myEndElement().
myLaneSets
std::map<std::string, LaneSet*> NIImporter_ITSUMO::Handler::myLaneSets private
Definition at line 159 of file NIImporter_ITSUMO.h.
Referenced by myEndElement().
myNetBuilder
NBNetBuilder& NIImporter_ITSUMO::Handler::myNetBuilder private
The container to fill.
Definition at line 130 of file NIImporter_ITSUMO.h.
Referenced by myEndElement().
myParameter
std::map<std::string, std::string> NIImporter_ITSUMO::Handler::myParameter private
A temporary parameter map.
Definition at line 133 of file NIImporter_ITSUMO.h.
Referenced by myCharacters(), myEndElement(), and myStartElement().
mySections
std::vector<Section*> NIImporter_ITSUMO::Handler::mySections private
Definition at line 170 of file NIImporter_ITSUMO.h.
Referenced by myEndElement().
The documentation for this class was generated from the following files:
NIImporter_ITSUMO.h
NIImporter_ITSUMO.cpp