SUMO - Simulation of Urban MObility: GUIShapeContainer Class Reference
GUIShapeContainer Class Reference
Storage for geometrical objects extended by mutexes.
#include <GUIShapeContainer.h>
Public Types
typedef NamedObjectCont< PointOfInterest * > POIs
typedef NamedObjectCont< SUMOPolygon * > Polygons
containers
Public Member Functions
virtual bool addPOI (const std::string &id, const std::string &type, const RGBColor &color, const Position &pos, bool geo, const std::string &lane, double posOverLane, double posLat, double layer, double angle, const std::string &imgFile, double width, double height, bool ignorePruning=false)
Builds a POI using the given values and adds it to the container.
virtual bool addPolygon (const std::string &id, const std::string &type, const RGBColor &color, double layer, double angle, const std::string &imgFile, const PositionVector &shape, bool geo, bool fill, bool ignorePruning=false)
Builds a polygon using the given values and adds it to the container.
std::vector< GUIGlID > getPOIIds () const
Returns the gl-ids of all pois.
const POIs & getPOIs () const
Returns all pois.
std::vector< GUIGlID > getPolygonIDs () const
Returns the gl-ids of all polygons.
const Polygons & getPolygons () const
Returns all polygons.
GUIShapeContainer (SUMORTree &vis)
Constructor.
virtual void movePOI (const std::string &id, const Position &pos)
Assigns a new position to the named PoI.
virtual bool removePOI (const std::string &id)
Removes a PoI from the container.
virtual bool removePolygon (const std::string &id)
Removes a polygon from the container.
virtual void reshapePolygon (const std::string &id, const PositionVector &shape)
Assigns a shape to the named polygon.
virtual ~GUIShapeContainer ()
Destructor.
Protected Member Functions
virtual bool add (SUMOPolygon *poly, bool ignorePruning=false)
add polygon
virtual bool add (PointOfInterest *poi, bool ignorePruning=false)
add poi
Protected Attributes
POIs myPOIs
stored POIs
Polygons myPolygons
stored Polygons
Private Attributes
MFXMutex myLock
The mutex for adding/removing operations.
SUMORTree & myVis
The RTree structure to add and remove visualization elements.
Detailed Description
Storage for geometrical objects extended by mutexes.
See also
ShapeContainer
Definition at line 54 of file GUIShapeContainer.h.
Member Typedef Documentation
POIs
typedef NamedObjectCont<PointOfInterest*> ShapeContainer::POIs inherited
Definition at line 52 of file ShapeContainer.h.
Polygons
typedef NamedObjectCont<SUMOPolygon*> ShapeContainer::Polygons inherited
containers
Definition at line 51 of file ShapeContainer.h.
Constructor & Destructor Documentation
GUIShapeContainer()
GUIShapeContainer::GUIShapeContainer (SUMORTree & vis)
Constructor.
Definition at line 41 of file GUIShapeContainer.cpp.
~GUIShapeContainer()
GUIShapeContainer::~GUIShapeContainer () virtual
Destructor.
Definition at line 45 of file GUIShapeContainer.cpp.
Member Function Documentation
add() [1/2]
bool ShapeContainer::add (SUMOPolygon * poly, bool ignorePruning = false) protected virtual inherited
add polygon
Reimplemented in PCPolyContainer.
Definition at line 102 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and ShapeContainer::myPolygons.
Referenced by PCPolyContainer::add(), ShapeContainer::addPOI(), ShapeContainer::addPolygon(), and ShapeContainer::getPOIs().
add() [2/2]
bool ShapeContainer::add (PointOfInterest * poi, bool ignorePruning = false) protected virtual inherited
add poi
Reimplemented in PCPolyContainer.
Definition at line 112 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and ShapeContainer::myPOIs.
addPOI()
bool GUIShapeContainer::addPOI (const std::string & id, const std::string & type, const RGBColor & color, const Position & pos, bool geo, const std::string & lane, double posOverLane, double posLat, double layer, double angle, const std::string & imgFile, double width, double height, bool ignorePruning = false) virtual
Builds a POI using the given values and adds it to the container.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] pos The position of the POI
Reimplemented from ShapeContainer.
Definition at line 49 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::add(), SUMORTree::addAdditionalGLObject(), myLock, ShapeContainer::myPOIs, and myVis.
addPolygon()
bool GUIShapeContainer::addPolygon (const std::string & id, const std::string & type, const RGBColor & color, double layer, double angle, const std::string & imgFile, const PositionVector & shape, bool geo, bool fill, bool ignorePruning = false) virtual
Builds a polygon using the given values and adds it to the container.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] geo specify if shape was loaded as GEO coordinate
[in] fill Whether the polygon shall be filled
Returns
whether the polygon could be added
Reimplemented from ShapeContainer.
Definition at line 65 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::add(), SUMORTree::addAdditionalGLObject(), myLock, ShapeContainer::myPolygons, and myVis.
getPOIIds()
std::vector< GUIGlID > GUIShapeContainer::getPOIIds () const
Returns the gl-ids of all pois.
Definition at line 131 of file GUIShapeContainer.cpp.
References ShapeContainer::getPOIs(), and myLock.
getPOIs()
const POIs& ShapeContainer::getPOIs () const inline inherited
Returns all pois.
Definition at line 128 of file ShapeContainer.h.
References ShapeContainer::add(), and ShapeContainer::myPOIs.
Referenced by ShapeHandler::addPOI(), libsumo::POI::getIDList(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), getPOIIds(), libsumo::POI::getTree(), GNESelectorFrame::onCmdInvert(), and GNENet::retrieveShapes().
getPolygonIDs()
std::vector< GUIGlID > GUIShapeContainer::getPolygonIDs () const
Returns the gl-ids of all polygons.
Definition at line 142 of file GUIShapeContainer.cpp.
References ShapeContainer::getPolygons(), and myLock.
getPolygons()
const Polygons& ShapeContainer::getPolygons () const inline inherited
Returns all polygons.
Definition at line 123 of file ShapeContainer.h.
References ShapeContainer::myPolygons.
Referenced by ShapeHandler::addPoly(), libsumo::Polygon::getIDList(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), getPolygonIDs(), libsumo::Polygon::getTree(), PCLoaderDlrNavteq::loadPolyFile(), GNESelectorFrame::onCmdInvert(), and GNENet::retrieveShapes().
movePOI()
void GUIShapeContainer::movePOI (const std::string & id, const Position & pos) virtual
Assigns a new position to the named PoI.
Parameters
[in] id The id of the PoI to move
[in] pos The PoI's new position
Reimplemented from ShapeContainer.
Definition at line 106 of file GUIShapeContainer.cpp.
References SUMORTree::addAdditionalGLObject(), NamedObjectCont< T >::get(), myLock, ShapeContainer::myPOIs, myVis, and SUMORTree::removeAdditionalGLObject().
removePOI()
bool GUIShapeContainer::removePOI (const std::string & id) virtual
Removes a PoI from the container.
Parameters
[in] id The id of the PoI
Returns
Whether the poi could be removed
Reimplemented from ShapeContainer.
Definition at line 94 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::get(), myLock, ShapeContainer::myPOIs, myVis, NamedObjectCont< T >::remove(), and SUMORTree::removeAdditionalGLObject().
removePolygon()
bool GUIShapeContainer::removePolygon (const std::string & id) virtual
Removes a polygon from the container.
Parameters
[in] id The id of the polygon
Returns
Whether the polygon could be removed
Reimplemented from ShapeContainer.
Definition at line 82 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::get(), myLock, ShapeContainer::myPolygons, myVis, NamedObjectCont< T >::remove(), and SUMORTree::removeAdditionalGLObject().
reshapePolygon()
void GUIShapeContainer::reshapePolygon (const std::string & id, const PositionVector & shape) virtual
Assigns a shape to the named polygon.
Parameters
[in] id The id of the polygon to reshape
[in] shape The polygon's new shape
Reimplemented from ShapeContainer.
Definition at line 118 of file GUIShapeContainer.cpp.
References SUMORTree::addAdditionalGLObject(), NamedObjectCont< T >::get(), myLock, ShapeContainer::myPolygons, myVis, SUMORTree::removeAdditionalGLObject(), and GUIPolygon::setShape().
Field Documentation
myLock
MFXMutex GUIShapeContainer::myLock mutable private
The mutex for adding/removing operations.
Definition at line 140 of file GUIShapeContainer.h.
Referenced by addPOI(), addPolygon(), getPOIIds(), getPolygonIDs(), movePOI(), removePOI(), removePolygon(), and reshapePolygon().
myPOIs
POIs ShapeContainer::myPOIs protected inherited
stored POIs
Definition at line 144 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), addPOI(), GNENet::addPOI(), GNENet::changeShapeID(), GNENet::computeAndUpdate(), GNENet::generateShapeID(), GNENet::getGlIDs(), GNENet::getNumberOfShapes(), ShapeContainer::getPOIs(), GNENet::insertShape(), ShapeContainer::movePOI(), movePOI(), ShapeContainer::removePOI(), removePOI(), GNENet::removeShape(), GNENet::retrievePOI(), GNENet::retrievePOILane(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), GNENet::saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and PCPolyContainer::~PCPolyContainer().
myPolygons
Polygons ShapeContainer::myPolygons protected inherited
stored Polygons
Definition at line 141 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), addPolygon(), GNENet::addPolygon(), GNENet::changeShapeID(), GNENet::computeAndUpdate(), GNENet::generateShapeID(), GNENet::getGlIDs(), GNENet::getNumberOfShapes(), ShapeContainer::getPolygons(), GNENet::insertShape(), ShapeContainer::removePolygon(), removePolygon(), GNENet::removeShape(), ShapeContainer::reshapePolygon(), reshapePolygon(), GNENet::retrievePolygon(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), GNENet::saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and PCPolyContainer::~PCPolyContainer().
myVis
SUMORTree& GUIShapeContainer::myVis private
The RTree structure to add and remove visualization elements.
Definition at line 143 of file GUIShapeContainer.h.
Referenced by addPOI(), addPolygon(), movePOI(), removePOI(), removePolygon(), and reshapePolygon().
The documentation for this class was generated from the following files:
GUIShapeContainer.h
GUIShapeContainer.cpp