SUMO - Simulation of Urban MObility: tcpip::SocketException Class Reference
tcpip::SocketException Class Reference
#include <socket.h>
Public Member Functions
SocketException (std::string what) throw ()
virtual const char * what () const throw ()
~SocketException () throw ()
Private Attributes
std::string what_
Detailed Description
Definition at line 59 of file socket.h.
Constructor & Destructor Documentation
SocketException()
tcpip::SocketException::SocketException (std::string what) throw () inline
Definition at line 64 of file socket.h.
~SocketException()
tcpip::SocketException::~SocketException () throw () inline
Definition at line 75 of file socket.h.
Member Function Documentation
what()
virtual const char* tcpip::SocketException::what () const throw () inline virtual
Definition at line 70 of file socket.h.
Referenced by TraCIServer::cleanup(), TraCITestClient::commandClose(), TraCITestClient::commandGetVariable(), TraCITestClient::commandSetOrder(), TraCITestClient::commandSetValue(), TraCITestClient::commandSimulationStep(), TraCITestClient::commandSubscribeContextVariable(), TraCITestClient::commandSubscribeObjectVariable(), main(), OutputDevice_Network::OutputDevice_Network(), OutputDevice_Network::postWriteHook(), TraCIServer::processCommandsUntilSimStep(), TraCITestClient::run(), and TraCIServer::TraCIServer().
Field Documentation
what_
std::string tcpip::SocketException::what_ private
Definition at line 62 of file socket.h.
The documentation for this class was generated from the following file:
socket.h