SUMO - Simulation of Urban MObility: MSBatteryExport Class Reference
MSBatteryExport Class Reference
Realises dumping Battery Data.
#include <MSBatteryExport.h>
Static Public Member Functions
static void write (OutputDevice &of, SUMOTime timestep, int precision)
Writes the complete network state of the given edges into the given device.
Private Member Functions
MSBatteryExport (const MSBatteryExport &)
Invalidated copy constructor.
MSBatteryExport & operator= (const MSBatteryExport &)
Invalidated assignment operator.
Detailed Description
Realises dumping Battery Data.
The class offers a static method, which writes all available Battery factors of each vehicles of the network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 55 of file MSBatteryExport.h.
Constructor & Destructor Documentation
MSBatteryExport()
MSBatteryExport::MSBatteryExport (const MSBatteryExport &) private
Invalidated copy constructor.
Member Function Documentation
operator=()
MSBatteryExport& MSBatteryExport::operator= (const MSBatteryExport &) private
Invalidated assignment operator.
write()
void MSBatteryExport::write (OutputDevice & of, SUMOTime timestep, int precision) static
Writes the complete network state of the given edges into the given device.
Opens the current time step and export the Battery factors of all availabel vehicles
Parameters
[in] of The output device to use
[in] timestep The current time step
[in] precision The output precision
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 48 of file MSBatteryExport.cpp.
References OutputDevice::closeTag(), MSVehicle::getAcceleration(), MSDevice_Battery::getActualBatteryCapacity(), MSDevice_Battery::getChargingStationID(), MSDevice_Battery::getConsum(), MSBaseVehicle::getDevice(), MSDevice_Battery::getEnergyCharged(), Named::getID(), MSBaseVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSDevice_Battery::getMaximumBatteryCapacity(), MSVehicle::getPosition(), MSVehicle::getPositionOnLane(), MSLane::getShape(), MSVehicle::getSpeed(), MSNet::getVehicleControl(), MSDevice_Battery::getVehicleStopped(), MSBaseVehicle::getVehicleType(), MSDevice_Battery::isChargingInTransit(), MSDevice_Battery::isChargingStopped(), MSVehicle::isOnRoad(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), OutputDevice::openTag(), PositionVector::positionAtOffset(), OutputDevice::setPrecision(), SUMO_ATTR_ACCELERATION, SUMO_ATTR_ACTUALBATTERYCAPACITY, SUMO_ATTR_CHARGINGSTATIONID, SUMO_ATTR_ENERGYCHARGED, SUMO_ATTR_ENERGYCHARGEDINTRANSIT, SUMO_ATTR_ENERGYCHARGEDSTOPPED, SUMO_ATTR_ENERGYCONSUMED, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, SUMO_ATTR_POSONLANE, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TIMESTOPPED, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_TIMESTEP, SUMO_TAG_VEHICLE, time2string(), OutputDevice::writeAttr(), Position::x(), and Position::y().
Referenced by MSNet::writeOutput().
The documentation for this class was generated from the following files:
MSBatteryExport.h
MSBatteryExport.cpp