SUMO - Simulation of Urban MObility: SUMORouteLoaderControl Class Reference
SUMORouteLoaderControl Class Reference
#include <SUMORouteLoaderControl.h>
Public Member Functions
void add (SUMORouteLoader *loader)
add another loader
SUMOTime getFirstLoadTime () const
returns the timestamp of the first loaded vehicle or flow
bool haveAllLoaded () const
returns whether loading is completed
void loadNext (SUMOTime step)
loads the next routes up to and including the given time step
SUMORouteLoaderControl (SUMOTime inAdvanceStepNo)
constructor
~SUMORouteLoaderControl ()
destructor
Private Member Functions
SUMORouteLoaderControl & operator= (const SUMORouteLoaderControl &src)
Invalidated assignment operator.
SUMORouteLoaderControl (const SUMORouteLoaderControl &src)
Invalidated copy constructor.
Private Attributes
bool myAllLoaded
SUMOTime myCurrentLoadTime
the time step up to which vehicles were loaded
SUMOTime myFirstLoadTime
the first time step for which vehicles were loaded
const SUMOTime myInAdvanceStepNo
the number of routes to read in forward
bool myLoadAll
std::vector< SUMORouteLoader * > myRouteLoaders
the list of route loaders
Detailed Description
SUMORouteLoaderControl This controls is initialised with the list of route loaders and uses them to load routes step wise. The parameter myInAdvanceStepNo holds the number of time steps to read the routes in forward. If it is 0 (default), all routes will be read at once.
Definition at line 56 of file SUMORouteLoaderControl.h.
Constructor & Destructor Documentation
SUMORouteLoaderControl() [1/2]
SUMORouteLoaderControl::SUMORouteLoaderControl (SUMOTime inAdvanceStepNo)
constructor
Definition at line 41 of file SUMORouteLoaderControl.cpp.
~SUMORouteLoaderControl()
SUMORouteLoaderControl::~SUMORouteLoaderControl ()
destructor
Definition at line 51 of file SUMORouteLoaderControl.cpp.
References myRouteLoaders.
SUMORouteLoaderControl() [2/2]
SUMORouteLoaderControl::SUMORouteLoaderControl (const SUMORouteLoaderControl & src) private
Invalidated copy constructor.
Member Function Documentation
add()
void SUMORouteLoaderControl::add (SUMORouteLoader * loader)
add another loader
Definition at line 60 of file SUMORouteLoaderControl.cpp.
References myRouteLoaders.
Referenced by NLBuilder::buildRouteLoaderControl(), and ROLoader::openTypedRoutes().
getFirstLoadTime()
SUMOTime SUMORouteLoaderControl::getFirstLoadTime () const inline
returns the timestamp of the first loaded vehicle or flow
Definition at line 71 of file SUMORouteLoaderControl.h.
References myFirstLoadTime.
Referenced by ROLoader::openRoutes(), and ROLoader::processRoutes().
haveAllLoaded()
bool SUMORouteLoaderControl::haveAllLoaded () const inline
returns whether loading is completed
Definition at line 76 of file SUMORouteLoaderControl.h.
References myAllLoaded.
Referenced by ROLoader::processRoutes().
loadNext()
void SUMORouteLoaderControl::loadNext (SUMOTime step)
loads the next routes up to and including the given time step
Definition at line 66 of file SUMORouteLoaderControl.cpp.
References MAX2(), MIN2(), myAllLoaded, myCurrentLoadTime, myFirstLoadTime, myInAdvanceStepNo, myLoadAll, myRouteLoaders, and SUMOTime_MAX.
Referenced by MSNet::loadRoutes(), ROLoader::openRoutes(), and ROLoader::processRoutes().
operator=()
SUMORouteLoaderControl& SUMORouteLoaderControl::operator= (const SUMORouteLoaderControl & src) private
Invalidated assignment operator.
Field Documentation
myAllLoaded
bool SUMORouteLoaderControl::myAllLoaded private
Definition at line 95 of file SUMORouteLoaderControl.h.
Referenced by haveAllLoaded(), and loadNext().
myCurrentLoadTime
SUMOTime SUMORouteLoaderControl::myCurrentLoadTime private
the time step up to which vehicles were loaded
Definition at line 85 of file SUMORouteLoaderControl.h.
Referenced by loadNext().
myFirstLoadTime
SUMOTime SUMORouteLoaderControl::myFirstLoadTime private
the first time step for which vehicles were loaded
Definition at line 82 of file SUMORouteLoaderControl.h.
Referenced by getFirstLoadTime(), and loadNext().
myInAdvanceStepNo
const SUMOTime SUMORouteLoaderControl::myInAdvanceStepNo private
the number of routes to read in forward
Definition at line 88 of file SUMORouteLoaderControl.h.
Referenced by loadNext().
myLoadAll
bool SUMORouteLoaderControl::myLoadAll private
information whether all routes shall be loaded and whether they were loaded
Definition at line 95 of file SUMORouteLoaderControl.h.
Referenced by loadNext().
myRouteLoaders
std::vector<SUMORouteLoader*> SUMORouteLoaderControl::myRouteLoaders private
the list of route loaders
Definition at line 91 of file SUMORouteLoaderControl.h.
Referenced by add(), loadNext(), and ~SUMORouteLoaderControl().
The documentation for this class was generated from the following files:
SUMORouteLoaderControl.h
SUMORouteLoaderControl.cpp