SUMO - Simulation of Urban MObility: PedestrianRouter< E, L, N, V, INTERNALROUTER > Class Template Reference
PedestrianRouter< E, L, N, V, INTERNALROUTER > Class Template Reference
#include <PedestrianRouter.h>
Public Types
typedef IntermodalEdge< E, L, N, V > _IntermodalEdge
typedef IntermodalNetwork< E, L, N, V > _IntermodalNetwork
typedef IntermodalTrip< E, N, V > _IntermodalTrip
typedef double(* Operation) (const E *const, const IntermodalTrip< E, N, V > *const, double)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter< E, _IntermodalTrip > * clone ()
double compute (const E *from, const E *to, double departPos, double arrivalPos, double speed, SUMOTime msTime, const N *onlyNode, std::vector< const E *> &into, bool allEdges=false)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
bool compute (const E *, const E *, const _IntermodalTrip *const, SUMOTime, std::vector< const E *> &)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
double getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, double t) const
PedestrianRouter ()
Constructor.
PedestrianRouter (_IntermodalNetwork *net)
void prohibit (const std::vector< E *> &toProhibit)
double recomputeCosts (const std::vector< const E *> &, const _IntermodalTrip *const, SUMOTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~PedestrianRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Member Functions
PedestrianRouter & operator= (const PedestrianRouter &s)
Invalidated assignment operator.
Private Attributes
const bool myAmClone
INTERNALROUTER * myInternalRouter
_IntermodalNetwork * myPedNet
Detailed Description
template<class E, class L, class N, class V, class INTERNALROUTER>
class PedestrianRouter< E, L, N, V, INTERNALROUTER >
The router for pedestrians (on a bidirectional network of sidewalks and crossings)
Definition at line 54 of file PedestrianRouter.h.
Member Typedef Documentation
_IntermodalEdge
template<class E, class L, class N, class V, class INTERNALROUTER> typedef IntermodalEdge<E, L, N, V> PedestrianRouter< E, L, N, V, INTERNALROUTER >::_IntermodalEdge
Definition at line 57 of file PedestrianRouter.h.
_IntermodalNetwork
template<class E, class L, class N, class V, class INTERNALROUTER> typedef IntermodalNetwork<E, L, N, V> PedestrianRouter< E, L, N, V, INTERNALROUTER >::_IntermodalNetwork
Definition at line 58 of file PedestrianRouter.h.
_IntermodalTrip
template<class E, class L, class N, class V, class INTERNALROUTER> typedef IntermodalTrip<E, N, V> PedestrianRouter< E, L, N, V, INTERNALROUTER >::_IntermodalTrip
Definition at line 59 of file PedestrianRouter.h.
Operation
typedef double(* SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::Operation) (const E *const, const IntermodalTrip< E, N, V > *const, double) inherited
Type of the function that is used to retrieve the edge effort.
Definition at line 55 of file SUMOAbstractRouter.h.
Constructor & Destructor Documentation
PedestrianRouter() [1/2]
template<class E, class L, class N, class V, class INTERNALROUTER> PedestrianRouter< E, L, N, V, INTERNALROUTER >::PedestrianRouter () inline
Constructor.
Definition at line 62 of file PedestrianRouter.h.
PedestrianRouter() [2/2]
template<class E, class L, class N, class V, class INTERNALROUTER> PedestrianRouter< E, L, N, V, INTERNALROUTER >::PedestrianRouter (_IntermodalNetwork * net) inline
Definition at line 68 of file PedestrianRouter.h.
~PedestrianRouter()
template<class E, class L, class N, class V, class INTERNALROUTER> virtual PedestrianRouter< E, L, N, V, INTERNALROUTER >::~PedestrianRouter () inline virtual
Destructor.
Definition at line 75 of file PedestrianRouter.h.
Member Function Documentation
clone()
template<class E, class L, class N, class V, class INTERNALROUTER> virtual SUMOAbstractRouter<E, _IntermodalTrip>* PedestrianRouter< E, L, N, V, INTERNALROUTER >::clone () inline virtual
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 82 of file PedestrianRouter.h.
compute() [1/2]
template<class E, class L, class N, class V, class INTERNALROUTER> double PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute (const E * from, const E * to, double departPos, double arrivalPos, double speed, SUMOTime msTime, const N * onlyNode, std::vector< const E *> & into, bool allEdges = false) inline
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Definition at line 88 of file PedestrianRouter.h.
Referenced by MSRouteHandler::addPersonTrip(), libsumo::Simulation::findIntermodalRoute(), MSPModel_Striping::getNextLane(), MSPModel_Striping::PState::PState(), and libsumo::Person::rerouteTraveltime().
compute() [2/2]
template<class E, class L, class N, class V, class INTERNALROUTER> bool PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute (const E * , const E * , const _IntermodalTrip * const, SUMOTime , std::vector< const E *> &) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 127 of file PedestrianRouter.h.
endQuery()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myQueryStartTime, SUMOAbstractRouter< E, V >::myQueryTimeSum, and SUMOAbstractRouter< E, V >::myQueryVisits.
getEffort()
double SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myOperation.
operator=()
template<class E, class L, class N, class V, class INTERNALROUTER> PedestrianRouter& PedestrianRouter< E, L, N, V, INTERNALROUTER >::operator= (const PedestrianRouter< E, L, N, V, INTERNALROUTER > & s) private
Invalidated assignment operator.
prohibit()
template<class E, class L, class N, class V, class INTERNALROUTER> void PedestrianRouter< E, L, N, V, INTERNALROUTER >::prohibit (const std::vector< E *> & toProhibit) inline
Definition at line 136 of file PedestrianRouter.h.
Referenced by MSNet::getPedestrianRouter().
recomputeCosts()
template<class E, class L, class N, class V, class INTERNALROUTER> double PedestrianRouter< E, L, N, V, INTERNALROUTER >::recomputeCosts (const std::vector< const E *> & , const _IntermodalTrip * const, SUMOTime) const inline virtual
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 132 of file PedestrianRouter.h.
setBulkMode()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myBulkMode.
startQuery()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myNumQueries, and SUMOAbstractRouter< E, V >::myQueryStartTime.
Field Documentation
myAmClone
template<class E, class L, class N, class V, class INTERNALROUTER> const bool PedestrianRouter< E, L, N, V, INTERNALROUTER >::myAmClone private
Definition at line 146 of file PedestrianRouter.h.
Referenced by PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::~PedestrianRouter().
myBulkMode
bool SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
myInternalRouter
template<class E, class L, class N, class V, class INTERNALROUTER> INTERNALROUTER* PedestrianRouter< E, L, N, V, INTERNALROUTER >::myInternalRouter private
Definition at line 147 of file PedestrianRouter.h.
Referenced by PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::PedestrianRouter(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::prohibit(), and PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::~PedestrianRouter().
myOperation
Operation SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
myPedNet
template<class E, class L, class N, class V, class INTERNALROUTER> _IntermodalNetwork* PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet private
Definition at line 148 of file PedestrianRouter.h.
Referenced by PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::clone(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::PedestrianRouter(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::prohibit(), and PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::~PedestrianRouter().
The documentation for this class was generated from the following file:
PedestrianRouter.h