SUMO - Simulation of Urban MObility: NLHandler Class Reference
NLHandler Class Reference
The XML-Handler for network loading.
#include <NLHandler.h>
Public Types
typedef std::vector< MSLane * > LaneVector
Definition of a lane vector.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime getLastDepart () const
Returns the last loaded depart time.
bool haveSeenAdditionalSpeedRestrictions () const
bool haveSeenInternalEdge () const
bool haveSeenNeighs () const
bool lefthand () const
double networkVersion () const
NLHandler (const std::string &file, MSNet &net, NLDetectorBuilder &detBuilder, NLTriggerBuilder &triggerBuilder, NLEdgeControlBuilder &edgeBuilder, NLJunctionControlBuilder &junctionBuilder)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~NLHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (double &startPos, double &endPos, const double laneLength, const double minLength, const bool friendlyPos)
check start and end position of a stop
static std::mt19937 * getParsingRNG ()
Protected Types
typedef std::map< std::string, std::pair< std::string, std::string > > JunctionGraph
temporary data for building the junction graph after network parsing is finished
Protected Member Functions
virtual void addE1Detector (const SUMOSAXAttributes &attrs)
Builds an e1 detector using the given specification.
virtual void addE2Detector (const SUMOSAXAttributes &attrs)
Builds an e2 detector using the given specification.
void addE3Entry (const SUMOSAXAttributes &attrs)
Adds an entry to the currently processed e3 detector.
void addE3Exit (const SUMOSAXAttributes &attrs)
Adds an exit to the currently processed e3 detector.
virtual void addEdgeLaneMeanData (const SUMOSAXAttributes &attrs, int objecttype)
Builds edge or lane base mean data collector using the given specification.
virtual void addInstantE1Detector (const SUMOSAXAttributes &attrs)
Builds an e1 detector using the given specification.
void addParam (const SUMOSAXAttributes &attrs)
void addPersonTrip (const SUMOSAXAttributes &attrs)
add a routing request for a walking or intermodal person
virtual void addRouteProbeDetector (const SUMOSAXAttributes &attrs)
Builds a routeProbe-detector using the given specification.
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
virtual void addVTypeProbeDetector (const SUMOSAXAttributes &attrs)
Builds a vtype-detector using the given specification.
void addWalk (const SUMOSAXAttributes &attrs)
add a fully specified walk
void beginE3Detector (const SUMOSAXAttributes &attrs)
Starts building of an e3 detector using the given specification.
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
void closeContainer ()
Ends the processing of a container.
virtual void closeEdge ()
Closes the process of building an edge.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
virtual void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void endE3Detector ()
Builds of an e3 detector using collected values.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
void parseWalkPositions (const SUMOSAXAttributes &attrs, const std::string &personID, const MSEdge *fromEdge, const MSEdge *&toEdge, double &departPos, double &arrivalPos, MSStoppingPlace *&bs, const MSTransportable::Stage *const lastStage, bool &ok)
@ brief parse depart- and arrival positions of a walk
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called when a closing tag occurs.
Protected Attributes
NLDiscreteEventBuilder myActionBuilder
A builder for object actions.
MSTransportable::MSTransportablePlan * myActiveContainerPlan
The plan of the current container.
MSTransportable::MSTransportablePlan * myActivePlan
The plan of the current person.
ConstMSEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
double myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
bool myAmLoadingState
whether a state file is being loaded
bool myAmParsingTLLogicOrJunction
internal information whether a tls-logic is currently read
SUMOTime myBeginDefault
The default value for flow begins.
Boundary myConvBoundary
double myCurrentCosts
The currently parsed route costs.
std::string myCurrentDistrictID
The id of the current district.
bool myCurrentIsBroken
bool myCurrentIsInternalToSkip
Information whether the currently parsed edge is internal and not wished, here.
RandomDistributor< const MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route)
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
std::string myCurrentTypeID
The id of the currently processed edge type.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
std::string myCurrentWAUTID
The id of the currently processed WAUT.
SumoXMLTag myDefaultCFModel
the default car following model
NLDetectorBuilder & myDetectorBuilder
The detector builder to use.
NLEdgeControlBuilder & myEdgeControlBuilder
The edge builder to use.
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
bool myHaveSeenAdditionalSpeedRestrictions
whether additional files contained type-specific speed limits
bool myHaveSeenInternalEdge
whether the loaded network contains internal lanes
bool myHaveSeenNeighs
whether the loaded network contains explicit neighbor lanes
bool myHaveWarnedAboutDeprecatedLanes
IDSupplier myIdSupplier
generates numerical ids
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
NLJunctionControlBuilder & myJunctionControlBuilder
The junction builder to use.
JunctionGraph myJunctionGraph
SUMOTime myLastDepart
The insertion time of the vehicle read last.
Parameterised * myLastParameterised
bool myLefthand
whether the loaded network was built for left hand traffic
MSNet & myNet
The net to fill (preinitialised)
bool myNetIsLoaded
whether the location element was already loadee
Position myNetworkOffset
The network offset.
double myNetworkVersion
the loaded network version
Boundary myOrigBoundary
The network's boundaries.
NLTriggerBuilder & myTriggerBuilder
The trigger builder to use.
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
Static Protected Attributes
static std::mt19937 myParsingRNG
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Private Member Functions
void addConnection (const SUMOSAXAttributes &attrs)
adds a connection
void addDistrict (const SUMOSAXAttributes &attrs)
void addDistrictEdge (const SUMOSAXAttributes &attrs, bool isSource)
void addLane (const SUMOSAXAttributes &attrs)
adds a lane to the previously opened edge
void addPhase (const SUMOSAXAttributes &attrs)
adds a phase to the traffic lights logic currently build
void addPOI (const SUMOSAXAttributes &attrs)
adds a polygon
void addPoly (const SUMOSAXAttributes &attrs)
adds a polygon
void addRequest (const SUMOSAXAttributes &attrs)
adds a request item to the current junction logic
void addRoundabout (const SUMOSAXAttributes &attrs)
void addWAUTJunction (const SUMOSAXAttributes &attrs)
void addWAUTSwitch (const SUMOSAXAttributes &attrs)
void beginEdgeParsing (const SUMOSAXAttributes &attrs)
begins the processing of an edge
void closeWAUT ()
void initJunctionLogic (const SUMOSAXAttributes &attrs)
begins the reading of a junction row logic
void initTrafficLightLogic (const SUMOSAXAttributes &attrs)
begins the reading of a traffic lights logic
NLHandler (const NLHandler &s)
virtual void openJunction (const SUMOSAXAttributes &attrs)
opens a junction for processing
virtual void openWAUT (const SUMOSAXAttributes &attrs)
NLHandler & operator= (const NLHandler &s)
void parseLanes (const std::string &junctionID, const std::string &def, std::vector< MSLane *> &into, bool &ok)
LinkDirection parseLinkDir (const std::string &dir)
Parses the given character into an enumeration typed link direction.
LinkState parseLinkState (const std::string &state)
Parses the given character into an enumeration typed link state.
void setLocation (const SUMOSAXAttributes &attrs)
Parses network location description.
Detailed Description
The XML-Handler for network loading.
The SAX2-handler responsible for parsing networks and routes to load. This is an extension of the MSRouteHandler as routes and vehicles may also be loaded from network descriptions.
Definition at line 87 of file NLHandler.h.
Member Typedef Documentation
JunctionGraph
typedef std::map<std::string, std::pair<std::string, std::string> > NLHandler::JunctionGraph protected
temporary data for building the junction graph after network parsing is finished
Definition at line 362 of file NLHandler.h.
LaneVector
typedef std::vector<MSLane*> NLHandler::LaneVector
Definition of a lane vector.
Definition at line 90 of file NLHandler.h.
Constructor & Destructor Documentation
NLHandler() [1/2]
NLHandler::NLHandler (const std::string & file, MSNet & net, NLDetectorBuilder & detBuilder, NLTriggerBuilder & triggerBuilder, NLEdgeControlBuilder & edgeBuilder, NLJunctionControlBuilder & junctionBuilder)
Constructor.
Parameters
[in] file Name of the parsed file
[in,out] net The network to fill
[in] detBuilder The detector builder to use
[in] triggerBuilder The trigger builder to use
[in] edgeBuilder The builder of edges to use
[in] junctionBuilder The builder of junctions to use
Definition at line 63 of file NLHandler.cpp.
~NLHandler()
NLHandler::~NLHandler () virtual
Destructor.
Definition at line 85 of file NLHandler.cpp.
NLHandler() [2/2]
NLHandler::NLHandler (const NLHandler & s) private
invalid copy constructor
Member Function Documentation
addConnection()
void NLHandler::addConnection (const SUMOSAXAttributes & attrs) private
adds a connection
Definition at line 1139 of file NLHandler.cpp.
References MSLane::addApproachingLane(), MSLane::addIncomingLane(), MSTLLogicControl::TLSLogicVariants::addLink(), MSLane::addLink(), MSLane::dictionary(), MSEdge::dictionary(), SUMOSAXAttributes::get(), MSTLLogicControl::TLSLogicVariants::getActive(), Named::getID(), MSEdge::getLanes(), MSLane::getLength(), SUMOSAXAttributes::getOpt(), MSLane::getShape(), NLJunctionControlBuilder::getTLLogic(), MSGlobals::gUsingInternalLanes, myJunctionControlBuilder, myNetworkVersion, parseLinkDir(), parseLinkState(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMO_ATTR_VISIBILITY_DISTANCE, toString(), and WRITE_ERROR.
Referenced by myStartElement().
addDistrict()
void NLHandler::addDistrict (const SUMOSAXAttributes & attrs) private
Parses a district and creates a pseudo edge for it
Called on the occurence of a "district" element, this method retrieves the id of the district and creates a district type edge with this id.
Parameters
[in] attrs The attributes (of the "district"-element) to parse
Exceptions
ProcessError If an edge given in district is not known
Definition at line 1280 of file NLHandler.cpp.
References ShapeContainer::addPolygon(), MSEdge::addSuccessor(), NLEdgeControlBuilder::buildEdge(), MSEdge::dictionary(), EDGEFUNC_CONNECTOR, SUMOSAXAttributes::get(), MSNet::getShapeContainer(), SUMOSAXAttributes::getStringVector(), SUMOSAXAttributes::hasAttribute(), MSEdge::initialize(), myCurrentDistrictID, myCurrentIsBroken, myEdgeControlBuilder, myNet, RGBColor::parseColor(), SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_SHAPE, WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
addDistrictEdge()
void NLHandler::addDistrictEdge (const SUMOSAXAttributes & attrs, bool isSource) private
Parses a district edge and connects it to the district
Called on the occurence of a "dsource" or "dsink" element, this method retrieves the id of the approachable edge. If this edge is known and valid, the approaching edge is informed about it.
Parameters
[in] attrs The attributes to parse
[in] isSource whether a "dsource or a "dsink" was given
Todo:
No exception?
Definition at line 1330 of file NLHandler.cpp.
References MSEdge::dictionary(), SUMOSAXAttributes::get(), myCurrentDistrictID, myCurrentIsBroken, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
addE1Detector()
void NLHandler::addE1Detector (const SUMOSAXAttributes & attrs) protected virtual
Builds an e1 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 770 of file NLHandler.cpp.
References NLDetectorBuilder::buildInductLoop(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_VTYPES, and WRITE_ERROR.
Referenced by myStartElement().
addE2Detector()
void NLHandler::addE2Detector (const SUMOSAXAttributes & attrs) protected virtual
Builds an e2 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 869 of file NLHandler.cpp.
References NLDetectorBuilder::buildE2Detector(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), MSTLLogicControl::TLSLogicVariants::getActive(), GenericSAXHandler::getFileName(), NLDetectorBuilder::getLaneChecking(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogic(), StringTokenizer::hasNext(), myDetectorBuilder, myJunctionControlBuilder, StringTokenizer::next(), NUMERICAL_EPS, SUMO_ATTR_CONT, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMO_ATTR_VTYPES, SUMO_TAG_E2DETECTOR, TIME2STEPS, WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
addE3Entry()
void NLHandler::addE3Entry (const SUMOSAXAttributes & attrs) protected
Adds an entry to the currently processed e3 detector.
Parameters
[in] attrs The attributes that define the entry
Definition at line 1078 of file NLHandler.cpp.
References NLDetectorBuilder::addE3Entry(), SUMOSAXAttributes::get(), NLDetectorBuilder::getCurrentE3ID(), SUMOSAXAttributes::getOpt(), myDetectorBuilder, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, and SUMO_ATTR_POSITION.
Referenced by myStartElement().
addE3Exit()
void NLHandler::addE3Exit (const SUMOSAXAttributes & attrs) protected
Adds an exit to the currently processed e3 detector.
Parameters
[in] attrs The attributes that define the exit
Definition at line 1091 of file NLHandler.cpp.
References NLDetectorBuilder::addE3Exit(), SUMOSAXAttributes::get(), NLDetectorBuilder::getCurrentE3ID(), SUMOSAXAttributes::getOpt(), myDetectorBuilder, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, and SUMO_ATTR_POSITION.
Referenced by myStartElement().
addEdgeLaneMeanData()
void NLHandler::addEdgeLaneMeanData (const SUMOSAXAttributes & attrs, int objecttype) protected virtual
Builds edge or lane base mean data collector using the given specification.
Parameters
[in] attrs The attributes that define the detector
[in] objecttype The type (lane/edge) of the parsed mean data definition
Definition at line 1104 of file NLHandler.cpp.
References FileHelpers::checkForRelativity(), NLDetectorBuilder::createEdgeLaneMeanData(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::getOptSUMOTimeReporting(), myDetectorBuilder, POSITION_EPS, string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_EXCLUDE_EMPTY, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_MAX_TRAVELTIME, SUMO_ATTR_MIN_SAMPLES, SUMO_ATTR_TRACK_VEHICLES, SUMO_ATTR_TYPE, SUMO_ATTR_VTYPES, SUMO_ATTR_WITH_INTERNAL, SUMO_TAG_MEANDATA_LANE, and WRITE_ERROR.
Referenced by myStartElement().
addInstantE1Detector()
void NLHandler::addInstantE1Detector (const SUMOSAXAttributes & attrs) protected virtual
Builds an e1 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 799 of file NLHandler.cpp.
References NLDetectorBuilder::buildInstantInductLoop(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_VTYPES, and WRITE_ERROR.
Referenced by myStartElement().
addLane()
void NLHandler::addLane (const SUMOSAXAttributes & attrs) private
adds a lane to the previously opened edge
Definition at line 401 of file NLHandler.cpp.
References NLEdgeControlBuilder::addLane(), MSLane::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, myLastParameterised, myNet, parseVehicleClasses(), MSNet::setPermissionsFound(), SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LENGTH, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, SUMO_const_laneWidth, SVCAll, and WRITE_ERROR.
Referenced by myStartElement().
addParam()
void NLHandler::addParam (const SUMOSAXAttributes & attrs) protected
Definition at line 521 of file NLHandler.cpp.
References NLJunctionControlBuilder::addParam(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), myAmParsingTLLogicOrJunction, myJunctionControlBuilder, myLastParameterised, Parameterised::setParameter(), SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by myStartElement().
addPersonTrip()
void MSRouteHandler::addPersonTrip (const SUMOSAXAttributes & attrs) protected virtual inherited
add a routing request for a walking or intermodal person
Implements SUMORouteHandler.
Definition at line 1033 of file MSRouteHandler.cpp.
References MSVehicleControl::addVehicle(), MSVehicleControl::buildVehicle(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_POS_RANDOM, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSEdge::dictionary(), GenericSAXHandler::error(), MSGlobals::gCheckRoutes, MSStoppingPlace::getAccessPos(), OptionsCont::getFloat(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::getOptSUMOTimeReporting(), MSNet::getPedestrianRouter(), MSNet::getStoppingPlace(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSRouteHandler::parseWalkPositions(), RandHelper::rand(), SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DURATION, SUMO_ATTR_FROM, SUMO_ATTR_MODES, SUMO_ATTR_SPEED, SUMO_ATTR_TO, SUMO_ATTR_VTYPES, SUMO_ATTR_WALKFACTOR, SUMO_TAG_BUS_STOP, SVC_BICYCLE, SVC_BUS, SVC_IGNORING, SVC_PASSENGER, toString(), VEHPARS_VTYPE_SET, SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
addPhase()
void NLHandler::addPhase (const SUMOSAXAttributes & attrs) private
adds a phase to the traffic lights logic currently build
Todo:
: the following should be moved to StringTok
Definition at line 679 of file NLHandler.cpp.
References NLJunctionControlBuilder::addPhase(), SUMOSAXAttributes::get(), NLJunctionControlBuilder::getActiveKey(), NLJunctionControlBuilder::getActiveSubKey(), MsgHandler::getErrorInstance(), NLJunctionControlBuilder::getNumberOfLoadedPhases(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::getSUMOTimeReporting(), MsgHandler::getWarningInstance(), SUMOSAXAttributes::hasAttribute(), MsgHandler::inform(), myJunctionControlBuilder, SUMO_ATTR_DURATION, SUMO_ATTR_MAXDURATION, SUMO_ATTR_MINDURATION, SUMO_ATTR_STATE, SUMO_ATTR_TARGETLANE, SUMO_ATTR_TYPE, toString(), and WRITE_ERROR.
Referenced by myStartElement().
addPOI()
void NLHandler::addPOI (const SUMOSAXAttributes & attrs) private
adds a polygon
addPoly()
void NLHandler::addPoly (const SUMOSAXAttributes & attrs) private
adds a polygon
addRequest()
void NLHandler::addRequest (const SUMOSAXAttributes & attrs) private
adds a request item to the current junction logic
Definition at line 606 of file NLHandler.cpp.
References NLJunctionControlBuilder::addLogicItem(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_CONT, SUMO_ATTR_FOES, SUMO_ATTR_INDEX, SUMO_ATTR_RESPONSE, and WRITE_ERROR.
Referenced by myStartElement().
addRoundabout()
void NLHandler::addRoundabout (const SUMOSAXAttributes & attrs) private
Parses a roundabout and sets flags for the edges
Parameters
[in] attrs The attributes to parse
Definition at line 1352 of file NLHandler.cpp.
References MSEdge::dictionary(), SUMOSAXAttributes::getStringVector(), SUMOSAXAttributes::hasAttribute(), MSEdge::markAsRoundabout(), SUMO_ATTR_EDGES, and WRITE_ERROR.
Referenced by myStartElement().
addRouteProbeDetector()
void NLHandler::addRouteProbeDetector (const SUMOSAXAttributes & attrs) protected virtual
Builds a routeProbe-detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 845 of file NLHandler.cpp.
References NLDetectorBuilder::buildRouteProbe(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_VTYPES, and WRITE_ERROR.
Referenced by myStartElement().
addStop()
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual inherited
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 826 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MsgHandler::getErrorInstance(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLanes(), SUMOSAXAttributes::getOpt(), MSNet::getStoppingPlace(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::lane, MAX2(), MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::Stop::parkingarea, SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ACTTYPE, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_PARKING_AREA, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
addVTypeProbeDetector()
void NLHandler::addVTypeProbeDetector (const SUMOSAXAttributes & attrs) protected virtual
Builds a vtype-detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 825 of file NLHandler.cpp.
References NLDetectorBuilder::buildVTypeProbe(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_TYPE, and WRITE_ERROR.
Referenced by myStartElement().
addWalk()
void MSRouteHandler::addWalk (const SUMOSAXAttributes & attrs) protected virtual inherited
add a fully specified walk
Implements SUMORouteHandler.
Definition at line 1175 of file MSRouteHandler.cpp.
References MSRouteHandler::deleteActivePlans(), SUMOVehicleParameter::depart, DEPART_POS_RANDOM, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), MSRouteHandler::parseWalkPositions(), RandHelper::rand(), SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_ROUTE, and SUMO_ATTR_SPEED.
Referenced by MSRouteHandler::getParsingRNG().
addWAUTJunction()
void NLHandler::addWAUTJunction (const SUMOSAXAttributes & attrs) private
Definition at line 585 of file NLHandler.cpp.
References MSTLLogicControl::addWAUTJunction(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_JUNCTION_ID, SUMO_ATTR_PROCEDURE, SUMO_ATTR_SYNCHRON, SUMO_ATTR_WAUT_ID, and WRITE_ERROR.
Referenced by myStartElement().
addWAUTSwitch()
void NLHandler::addWAUTSwitch (const SUMOSAXAttributes & attrs) private
Definition at line 566 of file NLHandler.cpp.
References MSTLLogicControl::addWAUTSwitch(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, SUMO_ATTR_TIME, SUMO_ATTR_TO, and WRITE_ERROR.
Referenced by myStartElement().
beginE3Detector()
void NLHandler::beginE3Detector (const SUMOSAXAttributes & attrs) protected
Starts building of an e3 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 1054 of file NLHandler.cpp.
References NLDetectorBuilder::beginE3Detector(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_VTYPES, TIME2STEPS, and WRITE_ERROR.
Referenced by myStartElement().
beginEdgeParsing()
void NLHandler::beginEdgeParsing (const SUMOSAXAttributes & attrs) private
begins the processing of an edge
Definition at line 316 of file NLHandler.cpp.
References NLEdgeControlBuilder::addCrossingEdges(), NLEdgeControlBuilder::beginEdgeParsing(), EDGEFUNC_CROSSING, SUMOSAXAttributes::get(), SUMOSAXAttributes::getEdgeFunc(), SUMOXMLDefinitions::getJunctionIDFromInternalEdge(), SUMOSAXAttributes::getOpt(), MSGlobals::gUsingInternalLanes, StringTokenizer::hasNext(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, myHaveSeenInternalEdge, myJunctionGraph, StringTokenizer::next(), SUMO_ATTR_CROSSING_EDGES, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_NAME, SUMO_ATTR_PRIORITY, SUMO_ATTR_TO, SUMO_ATTR_TYPE, and WRITE_ERROR.
Referenced by myStartElement().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
checkLastDepart()
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 75 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
checkStopPos()
bool SUMORouteHandler::checkStopPos (double & startPos, double & endPos, const double laneLength, const double minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 219 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), RORouteHandler::addStop(), RONetHandler::parseAccess(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
closeContainer()
void MSRouteHandler::closeContainer () protected virtual inherited
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 752 of file MSRouteHandler.cpp.
References MSTransportableControl::buildContainer(), SUMORouteHandler::checkLastDepart(), GenericSAXHandler::error(), MSNet::getContainerControl(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closeEdge()
void NLHandler::closeEdge () protected virtual
Closes the process of building an edge.
Definition at line 385 of file NLHandler.cpp.
References NLEdgeControlBuilder::closeEdge(), MSEdge::dictionary(), Named::getID(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, and WRITE_ERROR.
Referenced by myEndElement().
closeFlow()
void MSRouteHandler::closeFlow () protected virtual inherited
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 780 of file MSRouteHandler.cpp.
References SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeRoute(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::parametersSet, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, string2time(), VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closePerson()
void MSRouteHandler::closePerson () protected virtual inherited
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 720 of file MSRouteHandler.cpp.
References MSTransportableControl::buildPerson(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::deleteActivePlans(), SUMOVehicleParameter::depart, GenericSAXHandler::error(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myAmLoadingState, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closeRoute()
void MSRouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual inherited
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 469 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), MSNet::getInstance(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, and MSRoute::setCosts().
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
closeRouteDistribution()
void MSRouteHandler::closeRouteDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 586 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::getParsingRNG().
closeVehicle()
void MSRouteHandler::closeVehicle () protected virtual inherited
Ends the processing of a vehicle.
Implements SUMORouteHandler.
Reimplemented in MSStateHandler.
Definition at line 608 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::buildVehicle(), SUMORouteHandler::checkLastDepart(), DEFAULT_VTYPE_ID, MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSVehicleType::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getQuota(), MSVehicleControl::getVehicle(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myAmLoadingState, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), SVC_PEDESTRIAN, toString(), VEHPARS_ROUTE_SET, SUMOVehicleParameter::vtypeid, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSStateHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
closeVehicleTypeDistribution()
void MSRouteHandler::closeVehicleTypeDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 370 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentVTypeDistribution, and MSRouteHandler::myCurrentVTypeDistributionID.
Referenced by MSRouteHandler::getParsingRNG().
closeWAUT()
void NLHandler::closeWAUT () private
Definition at line 1381 of file NLHandler.cpp.
References MSTLLogicControl::closeWAUT(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, and WRITE_ERROR.
Referenced by myEndElement().
endE3Detector()
void NLHandler::endE3Detector () protected virtual
Builds of an e3 detector using collected values.
Definition at line 1371 of file NLHandler.cpp.
References NLDetectorBuilder::endE3Detector(), myDetectorBuilder, and WRITE_ERROR.
Referenced by myEndElement().
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by addE1Detector(), addE2Detector(), addEdgeLaneMeanData(), addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), addRouteProbeDetector(), addVTypeProbeDetector(), beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
getFirstDepart()
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 73 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addPersonTrip(), SUMORouteHandler::addStop(), SUMORouteHandler::addWalk(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
getLastDepart()
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 69 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
getParsingRNG()
static std::mt19937* MSRouteHandler::getParsingRNG () inline static inherited
Definition at line 69 of file MSRouteHandler.h.
References MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), MSRouteHandler::myParsingRNG, MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseFromViaTo(), and MSRouteHandler::parseWalkPositions().
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::computeRandomDepartOffset(), MSInsertionControl::determineCandidates(), NLBuilder::init(), and GUILoadThread::run().
haveSeenAdditionalSpeedRestrictions()
bool NLHandler::haveSeenAdditionalSpeedRestrictions () const inline
Definition at line 119 of file NLHandler.h.
Referenced by NLBuilder::build().
haveSeenInternalEdge()
bool NLHandler::haveSeenInternalEdge () const inline
Definition at line 111 of file NLHandler.h.
Referenced by NLBuilder::build(), and NLBuilder::buildNet().
haveSeenNeighs()
bool NLHandler::haveSeenNeighs () const inline
Definition at line 115 of file NLHandler.h.
Referenced by NLBuilder::build(), and NLBuilder::buildNet().
initJunctionLogic()
void NLHandler::initJunctionLogic (const SUMOSAXAttributes & attrs) private
begins the reading of a junction row logic
Definition at line 631 of file NLHandler.cpp.
References SUMOSAXAttributes::get(), NLJunctionControlBuilder::initJunctionLogic(), myAmParsingTLLogicOrJunction, myCurrentIsBroken, myJunctionControlBuilder, and SUMO_ATTR_ID.
Referenced by myStartElement().
initTrafficLightLogic()
void NLHandler::initTrafficLightLogic (const SUMOSAXAttributes & attrs) private
begins the reading of a traffic lights logic
Definition at line 646 of file NLHandler.cpp.
References SUMOSAXAttributes::get(), StringBijection< T >::get(), MSTLLogicControl::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), NLJunctionControlBuilder::initTrafficLightLogic(), myAmParsingTLLogicOrJunction, myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_ID, SUMO_ATTR_OFFSET, SUMO_ATTR_PROGRAMID, SUMO_ATTR_TYPE, TLTYPE_STATIC, SUMOXMLDefinitions::TrafficLightTypes, and WRITE_ERROR.
Referenced by myStartElement().
lefthand()
bool NLHandler::lefthand () const inline
Definition at line 123 of file NLHandler.h.
Referenced by NLBuilder::buildNet().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void NLHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Todo:
Refactor/describe
Reimplemented from MSRouteHandler.
Definition at line 245 of file NLHandler.cpp.
References MSJunction::addIncoming(), MSJunction::addOutgoing(), closeEdge(), NLJunctionControlBuilder::closeJunction(), NLJunctionControlBuilder::closeJunctionLogic(), NLJunctionControlBuilder::closeTrafficLightLogic(), closeWAUT(), MSEdge::dictionary(), endE3Detector(), NLTriggerBuilder::endParkingArea(), GenericSAXHandler::getFileName(), myAmParsingTLLogicOrJunction, myCurrentIsBroken, MSRouteHandler::myEndElement(), myJunctionControlBuilder, myJunctionGraph, myLastParameterised, myNetIsLoaded, myTriggerBuilder, NLJunctionControlBuilder::retrieve(), MSEdge::setJunctions(), SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_JUNCTION, SUMO_TAG_NET, SUMO_TAG_PARAM, SUMO_TAG_PARKING_AREA, SUMO_TAG_TLLOGIC, SUMO_TAG_WAUT, and WRITE_ERROR.
myStartElement()
void NLHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Todo:
Refactor/describe
Reimplemented from MSRouteHandler.
Definition at line 89 of file NLHandler.cpp.
References NLTriggerBuilder::addAccess(), NLDiscreteEventBuilder::addAction(), addConnection(), addDistrict(), addDistrictEdge(), addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addEdgeLaneMeanData(), addInstantE1Detector(), addLane(), NLEdgeControlBuilder::addNeigh(), addParam(), addPhase(), addRequest(), MSNet::addRestriction(), addRoundabout(), addRouteProbeDetector(), addVTypeProbeDetector(), addWAUTJunction(), addWAUTSwitch(), beginE3Detector(), beginEdgeParsing(), NLTriggerBuilder::buildVaporizer(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getString(), getVehicleClassID(), initJunctionLogic(), initTrafficLightLogic(), myActionBuilder, myCurrentIsBroken, myCurrentTypeID, myEdgeControlBuilder, myHaveSeenAdditionalSpeedRestrictions, myHaveSeenNeighs, myLefthand, myNet, myNetIsLoaded, myNetworkVersion, MSRouteHandler::myStartElement(), myTriggerBuilder, openJunction(), openWAUT(), NLTriggerBuilder::parseAndAddLotEntry(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLTriggerBuilder::parseAndBuildRerouter(), NLTriggerBuilder::parseAndBuildStoppingPlace(), setLocation(), SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LEFTHAND, SUMO_ATTR_SPEED, SUMO_ATTR_VCLASS, SUMO_ATTR_VERSION, SUMO_TAG_ACCESS, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_INDUCTION_LOOP, SUMO_TAG_INSTANT_INDUCTION_LOOP, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANE_AREA_DETECTOR, SUMO_TAG_LOCATION, SUMO_TAG_MEANDATA_EDGE, SUMO_TAG_MEANDATA_LANE, SUMO_TAG_NEIGH, SUMO_TAG_NET, SUMO_TAG_PARAM, SUMO_TAG_PARKING_AREA, SUMO_TAG_PARKING_SPACE, SUMO_TAG_PHASE, SUMO_TAG_REQUEST, SUMO_TAG_REROUTER, SUMO_TAG_RESTRICTION, SUMO_TAG_ROUNDABOUT, SUMO_TAG_ROUTEPROBE, SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, SUMO_TAG_TAZSOURCE, SUMO_TAG_TIMEDEVENT, SUMO_TAG_TLLOGIC, SUMO_TAG_TRAIN_STOP, SUMO_TAG_TYPE, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPEPROBE, SUMO_TAG_WAUT, SUMO_TAG_WAUT_JUNCTION, SUMO_TAG_WAUT_SWITCH, and WRITE_ERROR.
networkVersion()
double NLHandler::networkVersion () const inline
Definition at line 127 of file NLHandler.h.
References ShapeHandler::myEndElement(), and ShapeHandler::myStartElement().
Referenced by NLBuilder::buildNet().
openJunction()
void NLHandler::openJunction (const SUMOSAXAttributes & attrs) private virtual
opens a junction for processing
Definition at line 452 of file NLHandler.cpp.
References PositionVector::closePolygon(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getNodeType(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getStringSecure(), MSGlobals::gUsingInternalLanes, SUMOSAXAttributes::hasAttribute(), myCurrentIsBroken, myJunctionControlBuilder, NLJunctionControlBuilder::openJunction(), parseLanes(), SUMO_ATTR_ID, SUMO_ATTR_INCLANES, SUMO_ATTR_INTLANES, SUMO_ATTR_KEY, SUMO_ATTR_SHAPE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_Z, and WRITE_ERROR.
Referenced by myStartElement().
openRoute()
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route for reading
Implements SUMORouteHandler.
Definition at line 390 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
openRouteDistribution()
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 539 of file MSRouteHandler.cpp.
References TplConvert::_2doubleSec(), RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
openVehicleTypeDistribution()
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 348 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, MSRouteHandler::myParsingRNG, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
Referenced by MSRouteHandler::getParsingRNG().
openWAUT()
void NLHandler::openWAUT (const SUMOSAXAttributes & attrs) private virtual
Definition at line 539 of file NLHandler.cpp.
References MSTLLogicControl::addWAUT(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOptSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, SUMO_ATTR_ID, SUMO_ATTR_REF_TIME, SUMO_ATTR_START_PROG, and WRITE_ERROR.
Referenced by myStartElement().
operator=()
NLHandler& NLHandler::operator= (const NLHandler & s) private
invalid assignment operator
parseFromViaTo()
void MSRouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected inherited
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 110 of file MSRouteHandler.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_ROUTE, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
parseLanes()
void NLHandler::parseLanes (const std::string & junctionID, const std::string & def, std::vector< MSLane *> & into, bool & ok) private
Definition at line 501 of file NLHandler.cpp.
References MSLane::dictionary(), MSGlobals::gUsingInternalLanes, StringTokenizer::hasNext(), StringTokenizer::next(), and WRITE_ERROR.
Referenced by openJunction().
parseLinkDir()
LinkDirection NLHandler::parseLinkDir (const std::string & dir) private
Parses the given character into an enumeration typed link direction.
Definition at line 1233 of file NLHandler.cpp.
References StringBijection< T >::get(), and SUMOXMLDefinitions::LinkDirections.
Referenced by addConnection().
parseLinkState()
LinkState NLHandler::parseLinkState (const std::string & state) private
Parses the given character into an enumeration typed link state.
Definition at line 1243 of file NLHandler.cpp.
References StringBijection< T >::get(), LINKSTATE_TL_OFF_BLINKING, and SUMOXMLDefinitions::LinkStates.
Referenced by addConnection().
parseStop()
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 271 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parametersSet, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, SUMOSAXAttributes::parseStringSet(), STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_PARKING_AREA, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), and SUMORouteHandler::getFirstDepart().
parseWalkPositions()
void MSRouteHandler::parseWalkPositions (const SUMOSAXAttributes & attrs, const std::string & personID, const MSEdge * fromEdge, const MSEdge *& toEdge, double & departPos, double & arrivalPos, MSStoppingPlace *& bs, const MSTransportable::Stage *const lastStage, bool & ok) protected inherited
@ brief parse depart- and arrival positions of a walk
Definition at line 978 of file MSRouteHandler.cpp.
References SUMOSAXAttributes::get(), MSStoppingPlace::getAccessPos(), MSTransportable::Stage::getArrivalPos(), MSStoppingPlace::getBeginLanePosition(), MSTransportable::Stage::getDestination(), MSTransportable::Stage::getDestinationStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLength(), SUMOSAXAttributes::getOpt(), MSNet::getStoppingPlace(), MSEdge::getToJunction(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myParsingRNG, SUMOVehicleParserHelper::parseWalkPos(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMO_TAG_BUS_STOP, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addWalk(), and MSRouteHandler::getParsingRNG().
registerLastDepart()
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 87 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
setLocation()
void NLHandler::setLocation (const SUMOSAXAttributes & attrs) private
Parses network location description.
Definition at line 1259 of file NLHandler.cpp.
References SUMOSAXAttributes::get(), GeoConvHelper::getFinal(), OptionsCont::getOptions(), GeoConvHelper::init(), myNetIsLoaded, SUMO_ATTR_CONV_BOUNDARY, SUMO_ATTR_NET_OFFSET, SUMO_ATTR_ORIG_BOUNDARY, SUMO_ATTR_ORIG_PROJ, and WRITE_WARNING.
Referenced by myStartElement().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myActionBuilder
NLDiscreteEventBuilder NLHandler::myActionBuilder protected
A builder for object actions.
Definition at line 301 of file NLHandler.h.
Referenced by myStartElement().
myActiveContainerPlan
MSTransportable::MSTransportablePlan* MSRouteHandler::myActiveContainerPlan protected inherited
The plan of the current container.
Definition at line 165 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
myActivePlan
MSTransportable::MSTransportablePlan* MSRouteHandler::myActivePlan protected inherited
The plan of the current person.
Definition at line 162 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closePerson(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
myActiveRoute
ConstMSEdgeVector MSRouteHandler::myActiveRoute protected inherited
The current route.
Definition at line 159 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeRoute(), MSRouteHandler::MSRouteHandler(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), and MSRouteHandler::parseFromViaTo().
myActiveRouteColor
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 174 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteID
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 165 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
myActiveRouteProbability
double SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 171 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteRefID
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 168 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteStops
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 180 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeRoute(), and RORouteHandler::closeRoute().
myAddVehiclesDirectly
bool MSRouteHandler::myAddVehiclesDirectly protected inherited
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 168 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), and MSRouteHandler::closeVehicle().
myAmLoadingState
bool MSRouteHandler::myAmLoadingState protected inherited
whether a state file is being loaded
Definition at line 183 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and MSStateHandler::MSStateHandler().
myAmParsingTLLogicOrJunction
bool NLHandler::myAmParsingTLLogicOrJunction protected
internal information whether a tls-logic is currently read
Definition at line 323 of file NLHandler.h.
Referenced by addParam(), initJunctionLogic(), initTrafficLightLogic(), and myEndElement().
myBeginDefault
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 189 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
myConvBoundary
Boundary NLHandler::myConvBoundary protected
Definition at line 335 of file NLHandler.h.
myCurrentCosts
double SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 177 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myCurrentDistrictID
std::string NLHandler::myCurrentDistrictID protected
The id of the current district.
Definition at line 320 of file NLHandler.h.
Referenced by addDistrict(), and addDistrictEdge().
myCurrentIsBroken
bool NLHandler::myCurrentIsBroken protected
Definition at line 337 of file NLHandler.h.
Referenced by addDistrict(), addDistrictEdge(), addLane(), addRequest(), addWAUTJunction(), addWAUTSwitch(), beginEdgeParsing(), closeEdge(), closeWAUT(), initJunctionLogic(), initTrafficLightLogic(), myEndElement(), myStartElement(), openJunction(), and openWAUT().
myCurrentIsInternalToSkip
bool NLHandler::myCurrentIsInternalToSkip protected
Information whether the currently parsed edge is internal and not wished, here.
Definition at line 304 of file NLHandler.h.
Referenced by addLane(), beginEdgeParsing(), and closeEdge().
myCurrentRouteDistribution
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution protected inherited
The currently parsed distribution of routes (probability->route)
Definition at line 177 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
myCurrentRouteDistributionID
std::string MSRouteHandler::myCurrentRouteDistributionID protected inherited
The id of the currently parsed route distribution.
Definition at line 180 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
myCurrentTypeID
std::string NLHandler::myCurrentTypeID protected
The id of the currently processed edge type.
Definition at line 329 of file NLHandler.h.
Referenced by myStartElement().
myCurrentVType
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 183 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSStateHandler::myEndElement(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
myCurrentVTypeDistribution
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution protected inherited
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 171 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
myCurrentVTypeDistributionID
std::string MSRouteHandler::myCurrentVTypeDistributionID protected inherited
The id of the currently parsed vehicle type distribution.
Definition at line 174 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), and MSRouteHandler::openVehicleTypeDistribution().
myCurrentWAUTID
std::string NLHandler::myCurrentWAUTID protected
The id of the currently processed WAUT.
Definition at line 326 of file NLHandler.h.
Referenced by addWAUTSwitch(), closeWAUT(), and openWAUT().
myDefaultCFModel
SumoXMLTag SUMORouteHandler::myDefaultCFModel protected inherited
the default car following model
Definition at line 201 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::MSRouteHandler(), and SUMORouteHandler::myStartElement().
myDetectorBuilder
NLDetectorBuilder& NLHandler::myDetectorBuilder protected
The detector builder to use.
Definition at line 308 of file NLHandler.h.
Referenced by addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addEdgeLaneMeanData(), addInstantE1Detector(), addRouteProbeDetector(), addVTypeProbeDetector(), beginE3Detector(), and endE3Detector().
myEdgeControlBuilder
NLEdgeControlBuilder& NLHandler::myEdgeControlBuilder protected
The edge builder to use.
Definition at line 314 of file NLHandler.h.
Referenced by addDistrict(), addLane(), beginEdgeParsing(), closeEdge(), and myStartElement().
myEndDefault
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 192 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
myFirstDepart
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 195 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
myHaveSeenAdditionalSpeedRestrictions
bool NLHandler::myHaveSeenAdditionalSpeedRestrictions protected
whether additional files contained type-specific speed limits
Definition at line 350 of file NLHandler.h.
Referenced by myStartElement().
myHaveSeenInternalEdge
bool NLHandler::myHaveSeenInternalEdge protected
whether the loaded network contains internal lanes
Definition at line 344 of file NLHandler.h.
Referenced by beginEdgeParsing().
myHaveSeenNeighs
bool NLHandler::myHaveSeenNeighs protected
whether the loaded network contains explicit neighbor lanes
Definition at line 347 of file NLHandler.h.
Referenced by myStartElement().
myHaveWarnedAboutDeprecatedLanes
bool NLHandler::myHaveWarnedAboutDeprecatedLanes protected
Definition at line 339 of file NLHandler.h.
myIdSupplier
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 186 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
myInsertStopEdgesAt
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 198 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
myJunctionControlBuilder
NLJunctionControlBuilder& NLHandler::myJunctionControlBuilder protected
The junction builder to use.
Definition at line 317 of file NLHandler.h.
Referenced by addConnection(), addE2Detector(), addParam(), addPhase(), addRequest(), addWAUTJunction(), addWAUTSwitch(), closeWAUT(), initJunctionLogic(), initTrafficLightLogic(), myEndElement(), openJunction(), and openWAUT().
myJunctionGraph
JunctionGraph NLHandler::myJunctionGraph protected
Definition at line 363 of file NLHandler.h.
Referenced by beginEdgeParsing(), and myEndElement().
myLastDepart
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 162 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
myLastParameterised
Parameterised* NLHandler::myLastParameterised protected
Definition at line 341 of file NLHandler.h.
Referenced by addLane(), addParam(), and myEndElement().
myLefthand
bool NLHandler::myLefthand protected
whether the loaded network was built for left hand traffic
Definition at line 353 of file NLHandler.h.
Referenced by myStartElement().
myNet
MSNet& NLHandler::myNet protected
The net to fill (preinitialised)
Definition at line 216 of file NLHandler.h.
Referenced by addDistrict(), addLane(), and myStartElement().
myNetIsLoaded
bool NLHandler::myNetIsLoaded protected
whether the location element was already loadee
Definition at line 359 of file NLHandler.h.
Referenced by myEndElement(), myStartElement(), and setLocation().
myNetworkOffset
Position NLHandler::myNetworkOffset protected
The network offset.
Definition at line 332 of file NLHandler.h.
myNetworkVersion
double NLHandler::myNetworkVersion protected
the loaded network version
Definition at line 356 of file NLHandler.h.
Referenced by addConnection(), and myStartElement().
myOrigBoundary
Boundary NLHandler::myOrigBoundary protected
The network's boundaries.
Definition at line 335 of file NLHandler.h.
myParsingRNG
std::mt19937 MSRouteHandler::myParsingRNG static protected inherited
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Definition at line 186 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addWalk(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), and MSRouteHandler::parseWalkPositions().
myTriggerBuilder
NLTriggerBuilder& NLHandler::myTriggerBuilder protected
The trigger builder to use.
Definition at line 311 of file NLHandler.h.
Referenced by myEndElement(), and myStartElement().
myVehicleParameter
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 159 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSRouteHandler::addPersonTrip(), RORouteHandler::addPersonTrip(), MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::addWalk(), RORouteHandler::addWalk(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSStateHandler::myEndElement(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
The documentation for this class was generated from the following files:
NLHandler.h
NLHandler.cpp