SUMO - Simulation of Urban MObility: NIVissimVehTypeClass Class Reference
NIVissimVehTypeClass Class Reference
#include <NIVissimVehTypeClass.h>
Public Member Functions
double meanSpeed () const
NIVissimVehTypeClass (int id, const std::string &name, const RGBColor &color, std::vector< int > &types)
~NIVissimVehTypeClass ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int id, const std::string &name, const RGBColor &color, std::vector< int > &types)
static bool dictionary (int id, NIVissimVehTypeClass *o)
static NIVissimVehTypeClass * dictionary (int name)
Private Types
typedef std::map< int, NIVissimVehTypeClass * > DictType
Private Attributes
RGBColor myColor
int myID
std::string myName
std::vector< int > myTypes
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 44 of file NIVissimVehTypeClass.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimVehTypeClass*> NIVissimVehTypeClass::DictType private
Definition at line 61 of file NIVissimVehTypeClass.h.
Constructor & Destructor Documentation
NIVissimVehTypeClass()
NIVissimVehTypeClass::NIVissimVehTypeClass (int id, const std::string & name, const RGBColor & color, std::vector< int > & types)
Definition at line 39 of file NIVissimVehTypeClass.cpp.
Referenced by dictionary().
~NIVissimVehTypeClass()
NIVissimVehTypeClass::~NIVissimVehTypeClass ()
Definition at line 45 of file NIVissimVehTypeClass.cpp.
Member Function Documentation
clearDict()
void NIVissimVehTypeClass::clearDict () static
Definition at line 85 of file NIVissimVehTypeClass.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/3]
bool NIVissimVehTypeClass::dictionary (int id, const std::string & name, const RGBColor & color, std::vector< int > & types) static
Definition at line 49 of file NIVissimVehTypeClass.cpp.
References NIVissimVehTypeClass().
Referenced by NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition::myEndElement(), and NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse().
dictionary() [2/3]
bool NIVissimVehTypeClass::dictionary (int id, NIVissimVehTypeClass * o) static
Definition at line 64 of file NIVissimVehTypeClass.cpp.
References myDict.
dictionary() [3/3]
NIVissimVehTypeClass * NIVissimVehTypeClass::dictionary (int name) static
Definition at line 75 of file NIVissimVehTypeClass.cpp.
References myDict.
meanSpeed()
double NIVissimVehTypeClass::meanSpeed () const
Field Documentation
myColor
RGBColor NIVissimVehTypeClass::myColor private
Definition at line 58 of file NIVissimVehTypeClass.h.
myDict
NIVissimVehTypeClass::DictType NIVissimVehTypeClass::myDict static private
Definition at line 62 of file NIVissimVehTypeClass.h.
Referenced by clearDict(), and dictionary().
myID
int NIVissimVehTypeClass::myID private
Definition at line 56 of file NIVissimVehTypeClass.h.
myName
std::string NIVissimVehTypeClass::myName private
Definition at line 57 of file NIVissimVehTypeClass.h.
myTypes
std::vector<int> NIVissimVehTypeClass::myTypes private
Definition at line 59 of file NIVissimVehTypeClass.h.
The documentation for this class was generated from the following files:
NIVissimVehTypeClass.h
NIVissimVehTypeClass.cpp