SUMO - Simulation of Urban MObility: NIVissimNodeCluster Class Reference
NIVissimNodeCluster Class Reference
#include <NIVissimNodeCluster.h>
Public Member Functions
void buildNBNode (NBNodeCont &nc)
int getID () const
NBNode * getNBNode () const
std::string getNodeName () const
Position getPos () const
NIVissimNodeCluster (int id, int nodeid, int tlid, const std::vector< int > &connectors, const std::vector< int > &disturbances, bool amEdgeSplitOnly)
bool recheckEdgeChanges ()
~NIVissimNodeCluster ()
Static Public Member Functions
static void _debugOut (std::ostream &into)
static void assignToEdges ()
static void buildNBNodes (NBNodeCont &nc)
static void clearDict ()
static int contSize ()
static void dict_addDisturbances (NBDistrictCont &dc, NBNodeCont &nc, NBEdgeCont &ec)
static void dict_recheckEdgeChanges ()
static bool dictionary (int id, NIVissimNodeCluster *o)
static int dictionary (int nodeid, int tlid, const std::vector< int > &connectors, const std::vector< int > &disturbances, bool amEdgeSplitOnly)
static NIVissimNodeCluster * dictionary (int id)
static int getFromNode (int edgeid)
static int getToNode (int edgeid)
static void setCurrentVirtID (int id)
Private Types
typedef std::map< int, NIVissimNodeCluster * > DictType
Private Attributes
bool myAmEdgeSplit
std::vector< int > myConnectors
std::vector< int > myDisturbances
int myID
NBNode * myNBNode
int myNodeID
Position myPosition
int myTLID
Static Private Attributes
static int myCurrentID = 1
static DictType myDict
Detailed Description
Definition at line 52 of file NIVissimNodeCluster.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimNodeCluster*> NIVissimNodeCluster::DictType private
Definition at line 95 of file NIVissimNodeCluster.h.
Constructor & Destructor Documentation
NIVissimNodeCluster()
NIVissimNodeCluster::NIVissimNodeCluster (int id, int nodeid, int tlid, const std::vector< int > & connectors, const std::vector< int > & disturbances, bool amEdgeSplitOnly)
Definition at line 57 of file NIVissimNodeCluster.cpp.
Referenced by dictionary().
~NIVissimNodeCluster()
NIVissimNodeCluster::~NIVissimNodeCluster ()
Definition at line 66 of file NIVissimNodeCluster.cpp.
Member Function Documentation
_debugOut()
void NIVissimNodeCluster::_debugOut (std::ostream & into) static
Definition at line 248 of file NIVissimNodeCluster.cpp.
References myConnectors, myDict, and myID.
Referenced by getID().
assignToEdges()
static void NIVissimNodeCluster::assignToEdges () static
Referenced by getID().
buildNBNode()
void NIVissimNodeCluster::buildNBNode (NBNodeCont & nc)
Definition at line 128 of file NIVissimNodeCluster.cpp.
References NIVissimAbstractEdge::buildGeom(), NIVissimAbstractEdge::crossesEdge(), NIVissimAbstractEdge::crossesEdgeAtPoint(), NIVissimAbstractEdge::dictionary(), NIVissimConnection::dictionary(), NIVissimConnection::getFromGeomPosition(), getNodeName(), PositionVector::getPolygonCenter(), NIVissimConnection::getToGeomPosition(), NBNodeCont::insert(), myAmEdgeSplit, myConnectors, myNBNode, NODETYPE_PRIORITY, and PositionVector::push_back_noDoublePos().
Referenced by getID().
buildNBNodes()
void NIVissimNodeCluster::buildNBNodes (NBNodeCont & nc) static
Definition at line 188 of file NIVissimNodeCluster.cpp.
References myDict.
Referenced by getID(), and NIImporter_Vissim::postLoadBuild().
clearDict()
void NIVissimNodeCluster::clearDict () static
Definition at line 292 of file NIVissimNodeCluster.cpp.
References myDict.
Referenced by getID(), and NIImporter_Vissim::~NIImporter_Vissim().
contSize()
int NIVissimNodeCluster::contSize () static
Definition at line 111 of file NIVissimNodeCluster.cpp.
References myDict.
Referenced by getID().
dict_addDisturbances()
void NIVissimNodeCluster::dict_addDisturbances (NBDistrictCont & dc, NBNodeCont & nc, NBEdgeCont & ec) static
Definition at line 277 of file NIVissimNodeCluster.cpp.
References NIVissimDisturbance::addToNode(), NIVissimDisturbance::dictionary(), myDict, NIVissimDisturbance::reportRefused(), and NBNodeCont::retrieve().
Referenced by getID(), and NIImporter_Vissim::postLoadBuild().
dict_recheckEdgeChanges()
void NIVissimNodeCluster::dict_recheckEdgeChanges () static
Definition at line 197 of file NIVissimNodeCluster.cpp.
Referenced by getID().
dictionary() [1/3]
bool NIVissimNodeCluster::dictionary (int id, NIVissimNodeCluster * o) static
Definition at line 72 of file NIVissimNodeCluster.cpp.
References myDict.
Referenced by NIVissimConnectionCluster::buildNodeClusters(), NIVissimConnection::buildNodeClusters(), dictionary(), getID(), and NIVissimConnectionCluster::getNBNode().
dictionary() [2/3]
int NIVissimNodeCluster::dictionary (int nodeid, int tlid, const std::vector< int > & connectors, const std::vector< int > & disturbances, bool amEdgeSplitOnly) static
Definition at line 84 of file NIVissimNodeCluster.cpp.
References dictionary(), myCurrentID, and NIVissimNodeCluster().
dictionary() [3/3]
NIVissimNodeCluster * NIVissimNodeCluster::dictionary (int id) static
Definition at line 100 of file NIVissimNodeCluster.cpp.
References myDict.
getFromNode()
int NIVissimNodeCluster::getFromNode (int edgeid) static
Definition at line 203 of file NIVissimNodeCluster.cpp.
References NIVissimConnection::dictionary(), NIVissimConnection::getToEdgeID(), myConnectors, and myDict.
Referenced by getID().
getID()
int NIVissimNodeCluster::getID () const inline
Definition at line 59 of file NIVissimNodeCluster.h.
References _debugOut(), assignToEdges(), buildNBNode(), buildNBNodes(), clearDict(), contSize(), dict_addDisturbances(), dict_recheckEdgeChanges(), dictionary(), getFromNode(), getNBNode(), getNodeName(), getPos(), getToNode(), myID, recheckEdgeChanges(), and setCurrentVirtID().
getNBNode()
NBNode * NIVissimNodeCluster::getNBNode () const
Definition at line 265 of file NIVissimNodeCluster.cpp.
References myNBNode.
Referenced by getID().
getNodeName()
std::string NIVissimNodeCluster::getNodeName () const
Definition at line 118 of file NIVissimNodeCluster.cpp.
References myID, and myTLID.
Referenced by buildNBNode(), and getID().
getPos()
Position NIVissimNodeCluster::getPos () const
Definition at line 271 of file NIVissimNodeCluster.cpp.
References myPosition.
Referenced by getID().
getToNode()
int NIVissimNodeCluster::getToNode (int edgeid) static
Definition at line 225 of file NIVissimNodeCluster.cpp.
References NIVissimConnection::dictionary(), NIVissimConnection::getFromEdgeID(), myConnectors, and myDict.
Referenced by getID().
recheckEdgeChanges()
bool NIVissimNodeCluster::recheckEdgeChanges ()
Referenced by getID().
setCurrentVirtID()
void NIVissimNodeCluster::setCurrentVirtID (int id) static
Definition at line 301 of file NIVissimNodeCluster.cpp.
References myCurrentID.
Referenced by getID(), and NIImporter_Vissim::postLoadBuild().
Field Documentation
myAmEdgeSplit
bool NIVissimNodeCluster::myAmEdgeSplit private
Definition at line 99 of file NIVissimNodeCluster.h.
Referenced by buildNBNode().
myConnectors
std::vector<int> NIVissimNodeCluster::myConnectors private
Definition at line 92 of file NIVissimNodeCluster.h.
Referenced by _debugOut(), buildNBNode(), getFromNode(), and getToNode().
myCurrentID
int NIVissimNodeCluster::myCurrentID = 1 static private
Definition at line 97 of file NIVissimNodeCluster.h.
Referenced by dictionary(), and setCurrentVirtID().
myDict
NIVissimNodeCluster::DictType NIVissimNodeCluster::myDict static private
Definition at line 96 of file NIVissimNodeCluster.h.
Referenced by _debugOut(), buildNBNodes(), clearDict(), contSize(), dict_addDisturbances(), dictionary(), getFromNode(), and getToNode().
myDisturbances
std::vector<int> NIVissimNodeCluster::myDisturbances private
Definition at line 93 of file NIVissimNodeCluster.h.
myID
int NIVissimNodeCluster::myID private
Definition at line 89 of file NIVissimNodeCluster.h.
Referenced by _debugOut(), getID(), and getNodeName().
myNBNode
NBNode* NIVissimNodeCluster::myNBNode private
Definition at line 98 of file NIVissimNodeCluster.h.
Referenced by buildNBNode(), and getNBNode().
myNodeID
int NIVissimNodeCluster::myNodeID private
Definition at line 90 of file NIVissimNodeCluster.h.
myPosition
Position NIVissimNodeCluster::myPosition private
Definition at line 94 of file NIVissimNodeCluster.h.
Referenced by getPos().
myTLID
int NIVissimNodeCluster::myTLID private
Definition at line 91 of file NIVissimNodeCluster.h.
Referenced by getNodeName().
The documentation for this class was generated from the following files:
NIVissimNodeCluster.h
NIVissimNodeCluster.cpp