SUMO - Simulation of Urban MObility: GawronCalculator< R, E, V > Class Template Reference
GawronCalculator< R, E, V > Class Template Reference
Cost calculation with Gawron's method.
#include <GawronCalculator.h>
Public Member Functions
void calculateProbabilities (std::vector< R *> alternatives, const V *const, const SUMOTime)
calculate the probabilities
GawronCalculator (const double beta, const double a)
Constructor.
int getMaxRouteNumber () const
bool keepRoutes () const
void setCosts (R *route, const double costs, const bool isActive=false) const
bool skipRouteCalculation () const
virtual ~GawronCalculator ()
Destructor.
Static Public Member Functions
static void cleanup ()
static RouteCostCalculator< R, E, V > & getCalculator ()
Private Member Functions
double gawronF (const double pdr, const double pds, const double x) const
Performs the gawron - f() function From "Dynamic User Equilibria...".
double gawronG (const double a, const double x) const
Performs the gawron - g() function From "Dynamic User Equilibria...".
GawronCalculator & operator= (const GawronCalculator &s)
invalidated assignment operator
Private Attributes
const double myA
gawron a - value
const double myBeta
gawron beta - value
Detailed Description
template<class R, class E, class V>
class GawronCalculator< R, E, V >
Cost calculation with Gawron's method.
Definition at line 46 of file GawronCalculator.h.
Constructor & Destructor Documentation
GawronCalculator()
template<class R, class E, class V> GawronCalculator< R, E, V >::GawronCalculator (const double beta, const double a) inline
Constructor.
Definition at line 49 of file GawronCalculator.h.
~GawronCalculator()
template<class R, class E, class V> virtual GawronCalculator< R, E, V >::~GawronCalculator () inline virtual
Destructor.
Definition at line 52 of file GawronCalculator.h.
Member Function Documentation
calculateProbabilities()
template<class R, class E, class V> void GawronCalculator< R, E, V >::calculateProbabilities (std::vector< R *> alternatives, const V * const, const SUMOTime) inline virtual
calculate the probabilities
Implements RouteCostCalculator< R, E, V >.
Definition at line 63 of file GawronCalculator.h.
References GawronCalculator< R, E, V >::gawronF(), ISNAN(), MAX2(), and MIN2().
cleanup()
template<class R, class E, class V> static void RouteCostCalculator< R, E, V >::cleanup () inline static inherited
Definition at line 54 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::calculateProbabilities(), RouteCostCalculator< R, E, V >::myInstance, and RouteCostCalculator< R, E, V >::setCosts().
Referenced by RONet::cleanup().
gawronF()
template<class R, class E, class V> double GawronCalculator< R, E, V >::gawronF (const double pdr, const double pds, const double x) const inline private
Performs the gawron - f() function From "Dynamic User Equilibria...".
Definition at line 92 of file GawronCalculator.h.
References GawronCalculator< R, E, V >::gawronG(), and GawronCalculator< R, E, V >::myA.
Referenced by GawronCalculator< R, E, V >::calculateProbabilities().
gawronG()
template<class R, class E, class V> double GawronCalculator< R, E, V >::gawronG (const double a, const double x) const inline private
Performs the gawron - g() function From "Dynamic User Equilibria...".
Definition at line 102 of file GawronCalculator.h.
Referenced by GawronCalculator< R, E, V >::gawronF().
getCalculator()
template<class R , class E , class V > RouteCostCalculator< R, E, V > & RouteCostCalculator< R, E, V >::getCalculator () static inherited
Definition at line 114 of file RouteCostCalculator.h.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and RouteCostCalculator< R, E, V >::myInstance.
Referenced by RORouteDef::addAlternative(), and ROMAAssignments::sue().
getMaxRouteNumber()
template<class R, class E, class V> int RouteCostCalculator< R, E, V >::getMaxRouteNumber () const inline inherited
Definition at line 64 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myMaxRouteNumber.
keepRoutes()
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::keepRoutes () const inline inherited
Definition at line 68 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myKeepRoutes.
Referenced by RORouteDef::addAlternative().
operator=()
template<class R, class E, class V> GawronCalculator& GawronCalculator< R, E, V >::operator= (const GawronCalculator< R, E, V > & s) private
invalidated assignment operator
setCosts()
template<class R, class E, class V> void GawronCalculator< R, E, V >::setCosts (R * route, const double costs, const bool isActive = false) const inline virtual
Implements RouteCostCalculator< R, E, V >.
Definition at line 54 of file GawronCalculator.h.
References GawronCalculator< R, E, V >::myBeta.
skipRouteCalculation()
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::skipRouteCalculation () const inline inherited
Definition at line 72 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::mySkipRouteCalculation.
Field Documentation
myA
template<class R, class E, class V> const double GawronCalculator< R, E, V >::myA private
gawron a - value
Definition at line 114 of file GawronCalculator.h.
Referenced by GawronCalculator< R, E, V >::gawronF().
myBeta
template<class R, class E, class V> const double GawronCalculator< R, E, V >::myBeta private
gawron beta - value
Definition at line 111 of file GawronCalculator.h.
Referenced by GawronCalculator< R, E, V >::setCosts().
The documentation for this class was generated from the following file:
GawronCalculator.h