SUMO - Simulation of Urban MObility: AGActivityGenHandler Class Reference
AGActivityGenHandler Class Reference
#include <AGActivityGenHandler.h>
Public Member Functions
AGActivityGenHandler (AGCity &city, RONet *net)
Constructor.
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~AGActivityGenHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
called from myStartElement
AGCity & myCity
The city to store the information into.
std::string myCurrentObject
The name of the object that is currently processed.
AGBusLine * currentBusLine
bool isRevStation
indicator whether the current station (in bus line context) is a reverse station or not.
RONet * net
The loaded network.
bool myProcess
An indicator whether the next edge shall be read (internal edges are not read by now)
void parseGeneralCityInfo (const SUMOSAXAttributes &attrs)
void parseParameters (const SUMOSAXAttributes &attrs)
void parseStreets (const SUMOSAXAttributes &attrs)
void parseCityGates (const SUMOSAXAttributes &attrs)
void parseWorkHours ()
void parseOpeningHour (const SUMOSAXAttributes &attrs)
void parseClosingHour (const SUMOSAXAttributes &attrs)
void parseSchools ()
void parseSchool (const SUMOSAXAttributes &attrs)
void parseBusStation (const SUMOSAXAttributes &attrs)
void parseBusLine (const SUMOSAXAttributes &attrs)
void parseStations ()
void parseRevStations ()
void parseStation (const SUMOSAXAttributes &attrs)
void parseFrequency (const SUMOSAXAttributes &attrs)
void parsePopulation ()
void parseBracket (const SUMOSAXAttributes &attrs)
AGActivityGenHandler (const AGActivityGenHandler &src)
Invalidated copy constructor.
AGActivityGenHandler & operator= (const AGActivityGenHandler &src)
Invalidated assignment operator.
Detailed Description
Definition at line 53 of file AGActivityGenHandler.h.
Constructor & Destructor Documentation
AGActivityGenHandler() [1/2]
AGActivityGenHandler::AGActivityGenHandler (AGCity & city, RONet * net)
Constructor.
Parameters
[in] net The City instance to fill
Definition at line 57 of file AGActivityGenHandler.cpp.
~AGActivityGenHandler()
AGActivityGenHandler::~AGActivityGenHandler () virtual
Destructor.
Definition at line 62 of file AGActivityGenHandler.cpp.
AGActivityGenHandler() [2/2]
AGActivityGenHandler::AGActivityGenHandler (const AGActivityGenHandler & src) private
Invalidated copy constructor.
Member Function Documentation
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, PCLoaderOSM::EdgesHandler, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, MSCalibrator, NIXMLEdgesHandler, NIXMLNodesHandler, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, ShapeHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, and ROMARouteHandler.
Definition at line 226 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), and SUMOSAXReader::parseNext().
myStartElement()
void AGActivityGenHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 66 of file AGActivityGenHandler.cpp.
References AGEN_TAG_BRACKET, AGEN_TAG_BUSLINE, AGEN_TAG_BUSSTATION, AGEN_TAG_CLOSING, AGEN_TAG_ENTRANCE, AGEN_TAG_FREQUENCY, AGEN_TAG_GENERAL, AGEN_TAG_OPENING, AGEN_TAG_PARAM, AGEN_TAG_POPULATION, AGEN_TAG_REV_STATIONS, AGEN_TAG_SCHOOL, AGEN_TAG_SCHOOLS, AGEN_TAG_STATION, AGEN_TAG_STATIONS, AGEN_TAG_STREET, AGEN_TAG_WORKHOURS, parseBracket(), parseBusLine(), parseBusStation(), parseCityGates(), parseClosingHour(), parseFrequency(), parseGeneralCityInfo(), parseOpeningHour(), parseParameters(), parsePopulation(), parseRevStations(), parseSchool(), parseSchools(), parseStation(), parseStations(), parseStreets(), and parseWorkHours().
operator=()
AGActivityGenHandler& AGActivityGenHandler::operator= (const AGActivityGenHandler & src) private
Invalidated assignment operator.
parseBracket()
void AGActivityGenHandler::parseBracket (const SUMOSAXAttributes & attrs) protected
Definition at line 376 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_ENDAGE, AGEN_ATTR_PEOPLENBR, AGEN_TAG_BRACKET, SUMOSAXAttributes::getInt(), myCity, myCurrentObject, AGDataAndStatistics::population, AGCity::statData, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseBusLine()
void AGActivityGenHandler::parseBusLine (const SUMOSAXAttributes & attrs) protected
Definition at line 298 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_MAX_TRIP_DURATION, AGEN_TAG_BUSLINE, AGCity::busLines, currentBusLine, SUMOSAXAttributes::getInt(), SUMOSAXAttributes::getString(), myCity, myCurrentObject, AGBusLine::setMaxTripTime(), SUMO_ATTR_ID, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseBusStation()
void AGActivityGenHandler::parseBusStation (const SUMOSAXAttributes & attrs) protected
Bus stations and Bus extraction an additional computation have to be done to create buses' names and buses in the return way
Definition at line 281 of file AGActivityGenHandler.cpp.
References AGEN_TAG_BUSSTATION, AGDataAndStatistics::busStations, SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getInt(), AGCity::getStreet(), SUMOSAXAttributes::getString(), myCity, AGCity::statData, SUMO_ATTR_EDGE, SUMO_ATTR_ID, SUMO_ATTR_POSITION, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseCityGates()
void AGActivityGenHandler::parseCityGates (const SUMOSAXAttributes & attrs) protected
parse city entrances: the gates of the city, used for incoming and outgoing traffic
Definition at line 201 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_INCOMING, AGEN_ATTR_OUTGOING, AGEN_TAG_CITYGATES, AGCity::cityGates, SUMOSAXAttributes::getFloat(), AGCity::getStreet(), SUMOSAXAttributes::getString(), AGDataAndStatistics::incoming, myCity, AGDataAndStatistics::outgoing, AGCity::statData, SUMO_ATTR_EDGE, SUMO_ATTR_POSITION, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseClosingHour()
void AGActivityGenHandler::parseClosingHour (const SUMOSAXAttributes & attrs) protected
Definition at line 239 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_HOUR, AGEN_ATTR_PROP, AGEN_TAG_CLOSING, AGDataAndStatistics::endWorkHours, SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getInt(), myCity, myCurrentObject, AGCity::statData, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseFrequency()
void AGActivityGenHandler::parseFrequency (const SUMOSAXAttributes & attrs) protected
Definition at line 351 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_RATE, AGEN_TAG_FREQUENCY, currentBusLine, AGBusLine::generateBuses(), SUMOSAXAttributes::getInt(), myCurrentObject, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseGeneralCityInfo()
void AGActivityGenHandler::parseGeneralCityInfo (const SUMOSAXAttributes & attrs) protected
Parses attributes from an "general"-element in city file.
Definition at line 133 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_CARS, AGEN_ATTR_CHILDREN, AGEN_ATTR_HOUSEHOLDS, AGEN_ATTR_IN_TRAFFIC, AGEN_ATTR_INHABITANTS, AGEN_ATTR_LABORDEMAND, AGEN_ATTR_MAX_FOOT_DIST, AGEN_ATTR_OUT_TRAFFIC, AGEN_ATTR_RETIREMENT, AGEN_ATTR_UNEMPLOYEMENT, AGEN_TAG_GENERAL, AGDataAndStatistics::carRate, SUMOSAXAttributes::getInt(), SUMOSAXAttributes::getOpt(), AGDataAndStatistics::households, AGDataAndStatistics::incomingTraffic, AGDataAndStatistics::inhabitants, AGDataAndStatistics::laborDemand, AGDataAndStatistics::limitAgeChildren, AGDataAndStatistics::limitAgeRetirement, AGDataAndStatistics::maxFootDistance, myCity, AGDataAndStatistics::outgoingTraffic, AGCity::statData, SUMOXMLDefinitions::Tags, AGDataAndStatistics::unemployement, and WRITE_ERROR.
Referenced by myStartElement().
parseOpeningHour()
void AGActivityGenHandler::parseOpeningHour (const SUMOSAXAttributes & attrs) protected
Definition at line 224 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_HOUR, AGEN_ATTR_PROP, AGEN_TAG_OPENING, AGDataAndStatistics::beginWorkHours, SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getInt(), myCity, myCurrentObject, AGCity::statData, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseParameters()
void AGActivityGenHandler::parseParameters (const SUMOSAXAttributes & attrs) protected
parse parameters, all are optional, default values are given.
Definition at line 155 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_CARPREF, AGEN_ATTR_CITYSPEED, AGEN_ATTR_DEP_VARIATION, AGEN_ATTR_FREETIMERATE, AGEN_ATTR_UNI_RAND_TRAFFIC, AGEN_TAG_PARAM, AGDataAndStatistics::carPreference, AGDataAndStatistics::departureVariation, AGDataAndStatistics::freeTimeActivityRate, SUMOSAXAttributes::getOpt(), myCity, AGDataAndStatistics::speedTimePerKm, AGCity::statData, SUMOXMLDefinitions::Tags, AGDataAndStatistics::uniformRandomTrafficRate, and WRITE_ERROR.
Referenced by myStartElement().
parsePopulation()
void AGActivityGenHandler::parsePopulation () protected
population and children accompaniment bracket extraction then households and all population data will be computable
Definition at line 371 of file AGActivityGenHandler.cpp.
References myCurrentObject.
Referenced by myStartElement().
parseRevStations()
void AGActivityGenHandler::parseRevStations () protected
Definition at line 320 of file AGActivityGenHandler.cpp.
References isRevStation.
Referenced by myStartElement().
parseSchool()
void AGActivityGenHandler::parseSchool (const SUMOSAXAttributes & attrs) protected
Definition at line 259 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_BEGINAGE, AGEN_ATTR_CAPACITY, AGEN_ATTR_CLOSING, AGEN_ATTR_ENDAGE, AGEN_ATTR_OPENING, AGEN_TAG_SCHOOL, SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getInt(), AGCity::getStreet(), SUMOSAXAttributes::getString(), myCity, AGCity::schools, SUMO_ATTR_EDGE, SUMO_ATTR_POSITION, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseSchools()
void AGActivityGenHandler::parseSchools () protected
School extraction
Definition at line 254 of file AGActivityGenHandler.cpp.
References myCurrentObject.
Referenced by myStartElement().
parseStation()
void AGActivityGenHandler::parseStation (const SUMOSAXAttributes & attrs) protected
Definition at line 325 of file AGActivityGenHandler.cpp.
References AGEN_TAG_STATION, AGDataAndStatistics::busStations, currentBusLine, SUMOSAXAttributes::get(), isRevStation, AGBusLine::locateRevStation(), AGBusLine::locateStation(), myCity, myCurrentObject, AGCity::statData, SUMO_ATTR_REFID, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseStations()
void AGActivityGenHandler::parseStations () protected
Definition at line 315 of file AGActivityGenHandler.cpp.
References isRevStation.
Referenced by myStartElement().
parseStreets()
void AGActivityGenHandler::parseStreets (const SUMOSAXAttributes & attrs) protected
streets are extracted: it fills the streets list of the City object an additional computation is needed to normalize the number of inhabitants (and workpositions) in each street
Definition at line 172 of file AGActivityGenHandler.cpp.
References AGEN_ATTR_OUT_WORKPOSITION, AGEN_ATTR_POPULATION, AGEN_TAG_STREET, RONet::getEdge(), SUMOSAXAttributes::getFloat(), ROEdge::getLength(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), myCity, net, AGStreet::setPopulation(), AGStreet::setWorkplaceNumber(), AGCity::streets, SUMO_ATTR_EDGE, SUMOXMLDefinitions::Tags, and WRITE_ERROR.
Referenced by myStartElement().
parseWorkHours()
void AGActivityGenHandler::parseWorkHours () protected
extraction of work opening and closing hours
Definition at line 219 of file AGActivityGenHandler.cpp.
References myCurrentObject.
Referenced by myStartElement().
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
currentBusLine
AGBusLine* AGActivityGenHandler::currentBusLine protected
Definition at line 154 of file AGActivityGenHandler.h.
Referenced by parseBusLine(), parseFrequency(), and parseStation().
isRevStation
bool AGActivityGenHandler::isRevStation protected
indicator whether the current station (in bus line context) is a reverse station or not.
Definition at line 157 of file AGActivityGenHandler.h.
Referenced by parseRevStations(), parseStation(), and parseStations().
myCity
AGCity& AGActivityGenHandler::myCity protected
The city to store the information into.
Definition at line 150 of file AGActivityGenHandler.h.
Referenced by parseBracket(), parseBusLine(), parseBusStation(), parseCityGates(), parseClosingHour(), parseGeneralCityInfo(), parseOpeningHour(), parseParameters(), parseSchool(), parseStation(), and parseStreets().
myCurrentObject
std::string AGActivityGenHandler::myCurrentObject protected
The name of the object that is currently processed.
Definition at line 153 of file AGActivityGenHandler.h.
Referenced by parseBracket(), parseBusLine(), parseClosingHour(), parseFrequency(), parseOpeningHour(), parsePopulation(), parseSchools(), parseStation(), and parseWorkHours().
myProcess
bool AGActivityGenHandler::myProcess protected
An indicator whether the next edge shall be read (internal edges are not read by now)
Definition at line 163 of file AGActivityGenHandler.h.
net
RONet* AGActivityGenHandler::net protected
The loaded network.
Definition at line 160 of file AGActivityGenHandler.h.
Referenced by parseStreets().
The documentation for this class was generated from the following files:
AGActivityGenHandler.h
AGActivityGenHandler.cpp