SUMO - Simulation of Urban MObility: GUISelectedStorage Class Reference
GUISelectedStorage Class Reference
Storage for "selected" objects.
#include <GUISelectedStorage.h>
Data Structures
class SingleTypeSelections
A container for ids of selected objects of a certain type.
class UpdateTarget
Public Member Functions
void add2Update (UpdateTarget *updateTarget)
Adds a dialog to be updated.
void clear ()
Clears the list of selected objects.
void deselect (GUIGlID id)
Deselects the object with the given id.
const std::set< GUIGlID > & getSelected () const
Returns the set of ids of all selected objects.
const std::set< GUIGlID > & getSelected (GUIGlObjectType type)
Returns the set of ids of all selected objects' of a certain type.
GUISelectedStorage ()
Constructor.
bool isSelected (GUIGlObjectType type, GUIGlID id)
Returns the information whether the object with the given type and id is selected.
std::string load (const std::string &filename, GUIGlObjectType type=GLO_MAX)
Loads a selection list (optionally with restricted type)
std::set< GUIGlID > loadIDs (const std::string &filename, std::string &msgOut, GUIGlObjectType type=GLO_MAX, int maxErrors=16)
Loads a selection list (optionally with restricted type) and returns the ids of all active objects.
void remove2Update ()
Removes the dialog to be updated.
void save (GUIGlObjectType type, const std::string &filename)
Saves a selection list.
void save (const std::string &filename) const
Saves the combined selection of all types.
void select (GUIGlID id, bool update=true)
Adds the object with the given id.
void toggleSelection (GUIGlID id)
Toggles selection of an object.
~GUISelectedStorage ()
Destructor.
Private Member Functions
std::string load (GUIGlObjectType type, const std::string &filename, bool restrictType, std::set< GUIGlID > &into)
load items into the given set, optionally restricting to type
Static Private Member Functions
static void save (const std::string &filename, const std::set< GUIGlID > &ids)
saves items from the given set
Private Attributes
std::set< GUIGlID > myAllSelected
List of selected objects.
std::map< GUIGlObjectType, SingleTypeSelections > mySelections
map with the selections
UpdateTarget * myUpdateTarget
The dialog to be updated.
Friends
class SingleTypeSelections
set SingleTypeSelections as friend class
Detailed Description
Storage for "selected" objects.
Object selection is done by storing the "gl-ids" of selectable objects (GUIGlObjects) within internal containers of this class. Each id is stored twice - in a global container and within one of the type-aware containers.
This class allows adding and removing objects (their ids) from the lists of selected objects, saving the lists into a file, and obtaining the lists of selected objects (both all and type-aware).
Most of the adding/removing methods do not require a GUIGlObjectType as parameter, but an integer. This is done to perform the action on objects with a yet unknown type - in this case, the type is obtained internally.
Besides this, the class forces an active view of selected items to refresh its contents if an item is added/removed. For this, an FXWindow has to make itself visible to GUISelectedStorage.
See also
GUIGlObject
GUIGlObjectType
GUIDialog_GLChosenEditor
Definition at line 76 of file GUISelectedStorage.h.
Constructor & Destructor Documentation
GUISelectedStorage()
GUISelectedStorage::GUISelectedStorage ()
Constructor.
Definition at line 94 of file GUISelectedStorage.cpp.
Referenced by GUISelectedStorage::UpdateTarget::~UpdateTarget().
~GUISelectedStorage()
GUISelectedStorage::~GUISelectedStorage ()
Destructor.
Definition at line 97 of file GUISelectedStorage.cpp.
Referenced by GUISelectedStorage::UpdateTarget::~UpdateTarget().
Member Function Documentation
add2Update()
void GUISelectedStorage::add2Update (UpdateTarget * updateTarget)
Adds a dialog to be updated.
Parameters
[in] updateTarget the callback for selection changes
Definition at line 260 of file GUISelectedStorage.cpp.
References myUpdateTarget.
Referenced by GNESelectorFrame::show(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
clear()
void GUISelectedStorage::clear ()
Clears the list of selected objects.
Clears the global container and all sub-containers via SingleTypeSelections::clear.
The optionally listening UpdateTarget is informed about the change.
Definition at line 177 of file GUISelectedStorage.cpp.
References myAllSelected, mySelections, myUpdateTarget, and GUISelectedStorage::UpdateTarget::selectionUpdated().
Referenced by GNEViewNet::abortOperation(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GUIDialog_GLChosenEditor::onCmdClear(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
deselect()
void GUISelectedStorage::deselect (GUIGlID id)
Deselects the object with the given id.
The id of the object is removed from the sub-container that is responsible for objects of the determined type using SingleTypeSelections::deselect and from the global list of chosen items if it is there.
The optionally listening UpdateTarget is informed about the change.
Parameters
[in] id The id of the object
Exceptions
ProcessError If the object is not known or the type is not covered by a sub-container
See also
GUIGlObject
GUIGlObjectType
SingleTypeSelections::deselect
GUIDialog_GLChosenEditor
Definition at line 131 of file GUISelectedStorage.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, myAllSelected, mySelections, myUpdateTarget, GUISelectedStorage::UpdateTarget::selectionUpdated(), toString(), and GUIGlObjectStorage::unblockObject().
Referenced by GNEEdge::addConnection(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIDialog_GLChosenEditor::onCmdDeselect(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEChange_Selection::redo(), GNEChange_Selection::undo(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
getSelected() [1/2]
const std::set< GUIGlID > & GUISelectedStorage::getSelected () const
Returns the set of ids of all selected objects.
Definition at line 165 of file GUISelectedStorage.cpp.
References myAllSelected.
Referenced by GNENet::addReversedEdge(), GNESelectorFrame::handleIDs(), GNEDialog_FixAdditionalPositions::onCmdAccept(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNESelectorFrame::onCmdInvert(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEViewNet::onLeftBtnPress(), GUIDialog_GLChosenEditor::rebuildList(), GNESelectorFrame::selectionUpdated(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
getSelected() [2/2]
const std::set< GUIGlID > & GUISelectedStorage::getSelected (GUIGlObjectType type)
Returns the set of ids of all selected objects' of a certain type.
Parameters
[in] type The type of the object
Returns
A set containing the ids of all selected objects of the given type
See also
SingleTypeSelections::getSelected
Definition at line 171 of file GUISelectedStorage.cpp.
References mySelections.
isSelected()
bool GUISelectedStorage::isSelected (GUIGlObjectType type, GUIGlID id)
Returns the information whether the object with the given type and id is selected.
If the type is ==-1, it is determined, first. If it could not be obtained, or if the type is not covered by any selection container, a ProcessError is thrown.
Otherwise, the container holding objects of the determined type is asked whether the given id is stored using SingleTypeSelections::isSelected().
Parameters
[in] type The type of the object (GUIGlObjectType or -1)
[in] id The id of the object
Returns
Whether the object is selected
Exceptions
ProcessError If the object is not known or the type is not covered by a sub-container
See also
GUIGlObject
GUIGlObjectType
SingleTypeSelections::isSelected
Definition at line 101 of file GUISelectedStorage.cpp.
References GLO_ADDITIONAL, GLO_DETECTOR, GLO_NETWORK, GLO_TRIGGER, GUISelectedStorage::SingleTypeSelections::isSelected(), and mySelections.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNEViewNet::deleteSelectedConnections(), GNEViewNet::deleteSelectedCrossings(), GNENet::deleteShape(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIPolygon::drawGL(), GNELane::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEPoly::drawGL(), GNEEdge::drawGL(), GUILane::drawGL(), GNEShape::drawLockIcon(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNELane::getPopUpMenu(), GUIEdge::getScaleValue(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GNEViewNet::onCmdClearConnections(), GNEViewNet::onCmdDuplicateLane(), GNESelectorFrame::onCmdInvert(), GNEViewNet::onCmdResetConnections(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GNENet::replaceIncomingEdge(), GNENet::retrieveAdditionals(), GNENet::retrieveEdges(), GNENet::retrieveJunctions(), GNENet::retrieveLanes(), GNENet::retrieveShapes(), GNEJunction::setColor(), GNELane::setLaneColor(), GNECrossingFrame::crossingParameters::useSelectedEdges(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
load() [1/2]
std::string GUISelectedStorage::load (const std::string & filename, GUIGlObjectType type = GLO_MAX)
Loads a selection list (optionally with restricted type)
Parameters
[in] filename The name of the file to load the list of selected objects from
[in] type The type of the objects to load if changed from default
Returns
error messages if errors occured or the empty string
Definition at line 234 of file GUISelectedStorage.cpp.
References loadIDs(), myUpdateTarget, GUISelectedStorage::SingleTypeSelections::select(), and GUISelectedStorage::UpdateTarget::selectionUpdated().
Referenced by GUIDialog_GLChosenEditor::onCmdLoad(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
load() [2/2]
std::string GUISelectedStorage::load (GUIGlObjectType type, const std::string & filename, bool restrictType, std::set< GUIGlID > & into) private
load items into the given set, optionally restricting to type
loadIDs()
std::set< GUIGlID > GUISelectedStorage::loadIDs (const std::string & filename, std::string & msgOut, GUIGlObjectType type = GLO_MAX, int maxErrors = 16)
Loads a selection list (optionally with restricted type) and returns the ids of all active objects.
Parameters
[in] filename The name of the file to load the list of selected objects from
[out] msg Any error messages while loading or the empty string
[in] type The type of the objects to load if changed from default
[in] maxErrors The maximum Number of errors to return
Returns
the set of loaded ids
Definition at line 189 of file GUISelectedStorage.cpp.
References GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_MAX, and toString().
Referenced by load(), GNESelectorFrame::onCmdLoad(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
remove2Update()
void GUISelectedStorage::remove2Update ()
Removes the dialog to be updated.
Definition at line 266 of file GUISelectedStorage.cpp.
References myUpdateTarget.
Referenced by GNESelectorFrame::hide(), GNEAdditionalFrame::~GNEAdditionalFrame(), GNECrossingFrame::~GNECrossingFrame(), GNEPolygonFrame::~GNEPolygonFrame(), GNESelectorFrame::~GNESelectorFrame(), GUIDialog_GLChosenEditor::~GUIDialog_GLChosenEditor(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
save() [1/3]
void GUISelectedStorage::save (GUIGlObjectType type, const std::string & filename)
Saves a selection list.
Parameters
[in] type The type of the objects to save
[in] filename The name of the file to save the list of selected objects into
Definition at line 248 of file GUISelectedStorage.cpp.
References mySelections.
Referenced by GNESelectorFrame::onCmdSave(), GUIDialog_GLChosenEditor::onCmdSave(), GUISelectedStorage::SingleTypeSelections::save(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
save() [2/3]
void GUISelectedStorage::save (const std::string & filename) const
Saves the combined selection of all types.
Parameters
[in] filename The name of the file to save the list of selected objects into
Definition at line 254 of file GUISelectedStorage.cpp.
References myAllSelected, and GUISelectedStorage::SingleTypeSelections::save().
save() [3/3]
void GUISelectedStorage::save (const std::string & filename, const std::set< GUIGlID > & ids) static private
saves items from the given set
Definition at line 272 of file GUISelectedStorage.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), GUIGlObject::getFullName(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, and GUIGlObjectStorage::unblockObject().
select()
void GUISelectedStorage::select (GUIGlID id, bool update = true)
Adds the object with the given id.
The id of the object is added to the sub-container that is responsible for objects of the determined type using SingleTypeSelections::select and to the global list of chosen items if it is not already there.
The optionally listening window is informed about the change.
Parameters
[in] id The id of the object
Exceptions
ProcessError If the object is not known or the type is not covered by a sub-container
See also
GUIGlObject
GUIGlObjectType
SingleTypeSelections::select
GUIDialog_GLChosenEditor
Definition at line 114 of file GUISelectedStorage.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, myAllSelected, mySelections, myUpdateTarget, GUISelectedStorage::UpdateTarget::selectionUpdated(), toString(), and GUIGlObjectStorage::unblockObject().
Referenced by GNENet::joinSelectedJunctions(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIApplicationWindow::onCmdEditChosen(), GNEChange_Selection::redo(), GNEChange_Crossing::redo(), GUIVehicle::selectBlockingFoes(), GNEChange_Selection::undo(), GNEChange_Crossing::undo(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
toggleSelection()
void GUISelectedStorage::toggleSelection (GUIGlID id)
Toggles selection of an object.
If the object can not be obtained a ProcessError is thrown.
Otherwise, it is determined whether the object is already selected or not. If so, it is deselected by calling "deselect", otherwise it is selected via "select".
Parameters
[in] id The id of the object
Exceptions
ProcessError If the object is not known or the type is not covered by a sub-container
See also
GUIGlObject
deselect
select
Definition at line 148 of file GUISelectedStorage.cpp.
References GUISelectedStorage::SingleTypeSelections::deselect(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GUISelectedStorage::SingleTypeSelections::isSelected(), GUISelectedStorage::SingleTypeSelections::select(), toString(), and GUIGlObjectStorage::unblockObject().
Referenced by GUIDialog_GLObjChooser::onCmdToggleSelection(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnPress(), GUIMessageWindow::setCursorPos(), and GUISelectedStorage::UpdateTarget::~UpdateTarget().
Friends And Related Function Documentation
SingleTypeSelections
friend class SingleTypeSelections friend
set SingleTypeSelections as friend class
Definition at line 273 of file GUISelectedStorage.h.
Field Documentation
myAllSelected
std::set<GUIGlID> GUISelectedStorage::myAllSelected private
List of selected objects.
Definition at line 281 of file GUISelectedStorage.h.
Referenced by clear(), deselect(), getSelected(), save(), and select().
mySelections
std::map<GUIGlObjectType, SingleTypeSelections> GUISelectedStorage::mySelections private
map with the selections
Definition at line 278 of file GUISelectedStorage.h.
Referenced by clear(), deselect(), getSelected(), isSelected(), save(), and select().
myUpdateTarget
UpdateTarget* GUISelectedStorage::myUpdateTarget private
The dialog to be updated.
Definition at line 284 of file GUISelectedStorage.h.
Referenced by add2Update(), clear(), deselect(), load(), remove2Update(), and select().
The documentation for this class was generated from the following files:
GUISelectedStorage.h
GUISelectedStorage.cpp