SUMO - Simulation of Urban MObility: StdDefs.h File Reference
StdDefs.h File Reference
#include <config.h>
#include <string>
#include <cmath>
#include <limits>
Macros
#define SUMO_MAX_CONNECTIONS 256
the maximum number of connections across an intersection
#define UNUSED_PARAMETER(x) ((void)(x))
Functions
template<typename T >
T ISNAN (T a)
template<typename T >
T MAX2 (T a, T b)
template<typename T >
T MAX3 (T a, T b, T c)
template<typename T >
T MAX4 (T a, T b, T c, T d)
template<typename T >
T MIN2 (T a, T b)
template<typename T >
T MIN3 (T a, T b, T c)
template<typename T >
T MIN4 (T a, T b, T c, T d)
double roundBits (double x, int fractionBits)
round to the given number of mantissa bits beyond the given number
double truncate (double x, int fractionBits)
discrds mantissa bits beyond the given number
Variables
bool gDebugFlag1
global utility flags for debugging
bool gDebugFlag2
bool gDebugFlag3
bool gDebugFlag4
int gPrecision
the precision for floating point outputs
int gPrecisionGeo
const double INVALID_DOUBLE = std::numeric_limits<double>::max()
const double SUMO_const_halfLaneAndOffset = (double)(3.2 / 2. + .1)
const double SUMO_const_halfLaneWidth = (double) 1.6
const double SUMO_const_haltingSpeed = (double) 0.1
the speed threshold at which vehicles are considered as halting
const double SUMO_const_laneOffset = (double) .1
const double SUMO_const_laneWidth = (double) 3.2
const double SUMO_const_laneWidthAndOffset = (double) 3.3
const double SUMO_const_quarterLaneWidth = (double) 0.8
Detailed Description
Author
Daniel Krajzewicz
Laura Bieker
Michael Behrisch
Jakob Erdmann
Date
Fri, 29.04.2005
Version
$Id$
Definition in file StdDefs.h.
Macro Definition Documentation
SUMO_MAX_CONNECTIONS
#define SUMO_MAX_CONNECTIONS 256
the maximum number of connections across an intersection
Definition at line 42 of file StdDefs.h.
Referenced by NLJunctionControlBuilder::addLogicItem(), NBNode::computeLogic(), and MSRailCrossing::MSRailCrossing().
UNUSED_PARAMETER
#define UNUSED_PARAMETER (x) ((void)(x))
Definition at line 39 of file StdDefs.h.
Referenced by MSLeaderDistanceInfo::addLeader(), MSCriticalFollowerDistanceInfo::addLeader(), MSPModel::blockedAtDist(), MSRailCrossing::changeStepAndDuration(), MSOffTrafficLightLogic::changeStepAndDuration(), MSRailSignal::changeStepAndDuration(), combCallback(), combineCallback(), HelpersHBEFA::compute(), HelpersHBEFA3::compute(), RODFNet::computeRoutesFor(), MSAbstractLaneChangeModel::computeSpeedLat(), MSAbstractLaneChangeModel::decideDirection(), GNEReferenceCounter::decRef(), MSDetectorFileOutput::detectorUpdate(), GUIVehicle::drawAction_drawLinkItems(), GUIBaseVehicle::drawAction_drawVehicleBrakeLight(), GUITriggeredRerouter::drawGL(), GUIGlObject::drawGLAdditional(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSCFModel::estimateArrivalTime(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), NIImporter_OpenDrive::findWidthSplit(), FXSingleEventThread::FXSingleEventThread(), FXEX::FXThreadEvent::FXThreadEvent(), NIImporter_OpenDrive::geomFromArc(), NIImporter_OpenDrive::geomFromLine(), NIImporter_OpenDrive::geomFromParamPoly(), NIImporter_OpenDrive::geomFromPoly(), NIImporter_OpenDrive::geomFromSpiral(), RODFDetectorCon::getAggFlowFor(), PollutantsInterface::Helper::getAmitranVehicleClass(), PollutantsInterface::Helper::getClass(), PollutantsInterface::Helper::getClassByName(), PollutantsInterface::Helper::getEuroClass(), MSInternalJunction::getFoeInternalLanes(), MSInternalJunction::getFoeLinks(), MSJunctionLogic::getFoesFor(), PollutantsInterface::Helper::getFuel(), MSJunctionLogic::getIsCont(), PHEMCEP::GetMaxAccel(), PollutantsInterface::Helper::getModifiedAccel(), MSJunctionLogic::getResponseFor(), GUIGlObject::getTypeParameterWindow(), PollutantsInterface::Helper::getWeight(), NBHeightMapper::getZ(), MSPModel::hasPedestrians(), GNEReferenceCounter::incRef(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSCFModel_Wiedemann::interactionGap(), MEVehicle::isStoppedInRange(), PedestrianState::moveToXY(), MSPModel_Striping::PState::moveToXY(), MSPModel_NonInteracting::MSPModel_NonInteracting(), NBLoadedSUMOTLDef::myCompute(), NIImporter_DlrNavteq::NamesHandler::NamesHandler(), MSPModel::nextBlocking(), NIImporter_ArcView::NIImporter_ArcView(), NIImporter_Vissim::NIImporter_Vissim(), NIImporter_DlrNavteq::NodesHandler::NodesHandler(), MSMeanData::MeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMoveReminder::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSDevice_SSM::notifyEnter(), MSMoveReminder::notifyLeave(), MSDevice_SSM::notifyLeave(), MSMoveReminder::notifyMove(), MSDevice_SSM::notifyMove(), MSMoveReminder::notifyMoveInternal(), FXSingleEventThread::onThreadSignal(), FXEX::FXThreadEvent::onThreadSignal(), NBNode::edge_by_direction_sorter::operator()(), RGBColor::parseColorReporting(), MSLaneSpeedTrigger::processCommand(), libsumo::Vehicle::remove(), GNEDeleteFrame::removeAttributeCarrier(), NBTrafficLightDefinition::removeConnection(), GNENet::replaceIncomingEdge(), MEVehicle::replaceRoute(), MSMeanData::resetOnly(), MSAbstractLaneChangeModel::saveBlockerLength(), GUIViewTraffic::saveFrame(), GUISUMOAbstractView::saveFrame(), GUIMainWindow::sendBlockingEvent(), libsumo::Vehicle::setEmissionClass(), MSCFModel::setImperfection(), MSDevice::setParameter(), MSAbstractLaneChangeModel::setParameter(), libsumo::Vehicle::setSpeed(), GUIDialog_EditViewport::setValues(), libsumo::Vehicle::setVia(), NBTrafficLightDefinition::shiftTLConnectionLaneIndex(), FXSingleEventThread::signal(), FXEX::FXThreadEvent::signal(), MSAbstractLaneChangeModel::sublaneChangeCompleted(), toString(), toString< LaneChangeAction >(), toString< LaneChangeModel >(), toString< LaneSpreadFunction >(), toString< LateralAlignment >(), toString< LinkDirection >(), toString< LinkState >(), toString< SUMOVehicleClass >(), toString< SumoXMLAttr >(), toString< SumoXMLEdgeFunc >(), toString< SumoXMLNodeType >(), toString< SumoXMLTag >(), toString< TrafficLightType >(), NIImporter_DlrNavteq::TrafficlightsHandler::TrafficlightsHandler(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::updateSafeLatDist(), MSLCM_DK2008::wantsChange(), MSAbstractLaneChangeModel::wantsChange(), MSAbstractLaneChangeModel::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSInstantInductLoop::writeXMLOutput().
Function Documentation
ISNAN()
template<typename T > T ISNAN (T a) inline
Definition at line 108 of file StdDefs.h.
References gDebugFlag1, gDebugFlag2, gDebugFlag3, gDebugFlag4, gPrecision, gPrecisionGeo, roundBits(), and truncate().
Referenced by bezier(), GawronCalculator< R, E, V >::calculateProbabilities(), and MSCFModel::maximumSafeFollowSpeed().
MAX2()
template<typename T > T MAX2 (T a, T b) inline
Definition at line 73 of file StdDefs.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSPModel_Striping::addCrossingVehs(), MSRouteHandler::addStop(), MSStoppingPlace::addTransportable(), MSE2Collector::aggregateOutputValues(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::AStarRouter(), IDSupplier::avoid(), NBNode::bezierControlPoints(), NIVisumTL::build(), GUIViewTraffic::buildColorRainbow(), GNEViewNet::buildColorRainbow(), RODFNet::buildEdgeFlowMap(), GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), GawronCalculator< R, E, V >::calculateProbabilities(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), RGBColor::changedBrightness(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MELoop::checkCar(), MSLaneChanger::checkChange(), MSDevice_SSM::checkConflictEntryAndExit(), NBEdgeCont::checkGrade(), MSVehicle::checkLinkLeader(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), NBLoadedSUMOTLDef::cleanupStates(), MSVehicle::collisionStopTime(), MSLCM_SL2015::commitManoeuvre(), NBNodeShapeComputer::compute(), Bresenham::compute(), HelpersHBEFA::compute(), HelpersHBEFA3::compute(), HelpersPHEMlight::compute(), NBNetBuilder::compute(), NBTrafficLightDefinition::computeBrakingTime(), MSVehicleType::computeChosenSpeedDeviation(), MSLCM_SL2015::computeGapFactor(), NBNode::computeLanes2Lanes(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), MSLCM_SL2015::computeSpeedLat(), CState::computeTranshipTime(), MSPModel_NonInteracting::PState::computeWalkingTime(), NBPTStop::computExtent(), MSSOTLTrafficLightLogic::countVehicles(), MSCFModel_Daniel1::dawdle(), MSCFModel_SmartSK::dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_Krauss::dawdle2(), MSCFModel_KraussX::dawdleX(), MSDevice_SSM::determineTTCandDRAC(), MSCFModel::distAfterTime(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawBestLanes(), GUIPolygon::drawGL(), GUILane::drawGL(), GUITLLogicPhasesTrackerWindow::drawValues(), MSCFModel::estimateSpeedAfterDistance(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVehicle::executeMove(), NBEdge::expandableBy(), NBEdge::extendGeometryAtNode(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel_Rail::freeSpeed(), MSCFModel::freeSpeed(), MSCFModel::gapExtrapolation(), NBEdgeCont::generateStreetSigns(), NBNode::geometryLike(), GUIMessageWindow::getActiveStringObject(), GUIPerson::getCenteringBoundary(), MEVehicle::getConservativeSpeed(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentOccupancy(), MSEdge::getCurrentTravelTime(), MSVehicle::getDeltaPos(), ROVehicle::getDepartureTime(), MSDevice_Routing::getEffort(), GUIVisualizationSizeSettings::getExaggeration(), NBEdge::getFinalLength(), MSLane::getFollowersOnConsecutive(), GNEAttributeCarrier::getHigherNumberOfAttributes(), MSBaseVehicle::getImpatience(), MSPModel_Striping::PState::getImpatience(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLeaveTime(), ROEdge::getLengthGeometryFactor(), PositionVector::getMaxGrade(), MESegment::getMaxPenaltySeconds(), MSCFModel::getMinimalArrivalTime(), NIImporter_OpenStreetMap::getNeighboringNodes(), MESegment::getNextInsertionTime(), MSLane::getOppositePos(), PositionVector::getOverlapWith(), GUIVehicle::getRightSublaneOnEdge(), MSVehicle::getSafeFollowSpeed(), MSCFModel::getSecureGap(), MSCFModel::getSpeedAfterMaxDecel(), MSLeaderInfo::getSubLanes(), PublicTransportEdge< E, L, N, V >::getTravelTime(), PedestrianEdge< E, L, N, V >::getTravelTime(), ROEdge::getTravelTime(), MEVehicle::getWaitingTime(), MSLink::getZipperSpeed(), GUIDialog_ViewSettings::GUIDialog_ViewSettings(), GUIJunctionWrapper::GUIJunctionWrapper(), MSLane::handleCollisionBetween(), MSVehicle::Influencer::influenceSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSActuatedTrafficLightLogic::init(), MSLCM_SL2015::initDerivedParameters(), MSLCM_LC2013::initDerivedParameters(), MSTrafficLightLogic::initMesoTLSPenalties(), NIImporter_OpenStreetMap::insertEdge(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), NBEdgeCont::joinSameNodeConnectingEdges(), MSLCM_SL2015::keepLatGap(), LandmarkLookupTable< E, V >::LandmarkLookupTable(), SUMORouteLoaderControl::loadNext(), LandmarkLookupTable< E, V >::lowerBound(), MSE2Collector::makeMoveNotification(), MAX3(), MAX4(), MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeedBallistic(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::minNextSpeed(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Helper::moveToXYMap(), libsumo::Helper::moveToXYMap_matchingRoutePosition(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIImporter_OpenDrive::myStartElement(), MESegment::newArrival(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), GNETLSEditorFrame::onCmdPhaseCreate(), GNETLSEditorFrame::onCmdPhaseDelete(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::straightness_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), MSPModel_Striping::PState::otherStripe(), MSLCM_LC2013::overtakeDistance(), MSCFModel::passingTime(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMoveInternal(), MESegment::prepareDetectorForWriting(), MSLCM_SL2015::prepareStep(), SUMOVehicleParserHelper::processActionStepLength(), MSE2Collector::processJams(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MSDelayBasedTrafficLightLogic::proposeProlongation(), GUIDialog_ViewSettings::rebuildList(), MSEdge::recalcCache(), MESegment::receive(), MESegment::recomputeJamThreshold(), NIImporter_OpenDrive::recomputeWidths(), NIImporter_OpenStreetMap::reconstructLayerElevation(), MSCalibrator::remainingVehicleCapacity(), MESegment::removeCar(), NIImporter_DlrNavteq::TimeRestrictionsHandler::report(), NBEdgeCont::retrievePossiblySplit(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSE2Collector::selectLanes(), MESegment::send(), GNELane::setMultiColor(), GUILane::setMultiColor(), MSLCM_SL2015::setOwnState(), MESegment::setSpeedForQueue(), GUIMainWindow::setWindowSizeAndPos(), GNEEdge::smoothShape(), NBEdgeCont::splitAt(), MSCFModel_PWag2009::stopSpeed(), MSCFModel_SmartSK::stopSpeed(), MSCFModel_Wiedemann::stopSpeed(), MSPModel_Striping::PState::stripe(), MSDelayBasedTrafficLightLogic::trySwitch(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), AGFreeTime::typeFromHomeNight(), MSVehicle::updateBestLanes(), MSRailCrossing::updateCurrentPhase(), MSLCM_SL2015::updateGaps(), GNEJunction::updateGeometry(), CHBuilder< E, V >::CHInfo::updateLevel(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSVehicle::updateState(), MSVehicleControl::vehicleDeparted(), MSPModel_Striping::PState::walk(), MSPerson::MSPersonStage_Walking::walkDistance(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSVehicle::workOnMoveReminders(), MSMeanData_Net::MSLaneMeanDataValues::write(), ODMatrix::write(), RODFDetectorCon::writeEmitters(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_OpenDrive::writeGeomSmooth(), NWWriter_OpenDrive::writeInternalEdge(), NWWriter_SUMO::writeInternalEdges(), MSQueueExport::writeLane(), NWWriter_OpenDrive::writeNormalEdge(), RODFDetector::writeSingleSpeedTrigger(), MSInductLoop::writeXMLOutput(), and MSE2Collector::writeXMLOutput().
MAX3()
template<typename T > T MAX3 (T a, T b, T c) inline
Definition at line 87 of file StdDefs.h.
References MAX2().
Referenced by MELoop::checkCar(), MSActuatedTrafficLightLogic::duration(), NBRampsComputer::fulfillsRampConstraints(), MSCFModel::getMinimalArrivalTime(), MESegment::getNextInsertionTime(), MSTransportable::Stage_Waiting::proceed(), MSDelayBasedTrafficLightLogic::trySwitch(), and MSLCM_SL2015::updateGaps().
MAX4()
template<typename T > T MAX4 (T a, T b, T c, T d) inline
Definition at line 101 of file StdDefs.h.
References MAX2().
MIN2()
template<typename T > T MIN2 (T a, T b) inline
Definition at line 67 of file StdDefs.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::DriveProcessItem::adaptLeaveSpeed(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSPModel_Striping::addCrossingVehs(), MSVehicle::addStop(), NBEdge::addStraightConnections(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSLane::basePos(), NBNode::bezierControlPoints(), GUIViewTraffic::buildColorRainbow(), GNEViewNet::buildColorRainbow(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MSBaseVehicle::calculateArrivalParams(), GawronCalculator< R, E, V >::calculateProbabilities(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), RGBColor::changedBrightness(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MELoop::checkCar(), MSLaneChanger::checkChange(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSE2Collector::checkPositioning(), MSLCM_SL2015::commitFollowSpeed(), Bresenham::compute(), NBNetBuilder::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), NBEdge::computeAngle(), MSDevice_SSM::computeDRAC(), NBNode::computeLanes2Lanes(), NBOwnTLDef::computeLogicAndConts(), computeRoutes(), MSLCM_SL2015::computeSpeedGain(), MSLCM_SL2015::computeSpeedLat(), NBPTStop::computExtent(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSDevice_SSM::determineTTCandDRAC(), GLHelper::drawBoxLines(), GUILane::drawDirectionIndicators(), GNELane::drawDirectionIndicators(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUILane::drawMarkings(), GNELane::drawMarkings(), GUIBaseVehicle::drawOnPos(), MSActuatedTrafficLightLogic::duration(), MSDevice_SSM::estimateConflictTimes(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSCFModel::estimateSpeedAfterDistance(), NBEdge::extendGeometryAtNode(), NBEdge::firstIntersection(), MSCFModel_Kerner::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_Daniel1::followSpeed(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_Krauss::followSpeed(), MSLane::freeInsertion(), MSCFModel_Wiedemann::fullspeed(), MSActuatedTrafficLightLogic::gapControl(), MSCFModel::gapExtrapolation(), MSLane::getBruttoOccupancy(), MSInductLoop::getCurrentOccupancy(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSTransportable::Stage_Driving::getEdgePos(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), MSE2Collector::getEstimateQueueLength(), MSBaseVehicle::getImpatience(), MSPModel_Striping::PState::getImpatience(), MSLink::getLeaderInfo(), MSLane::getLeadersOnConsecutive(), libsumo::Lane::getLinks(), GeomHelper::getMinAngleDiff(), MSActuatedTrafficLightLogic::getMinimumMinDuration(), ROEdge::getMinimumTravelTime(), NBNodesEdgesSorter::crossing_by_junction_angle_sorter::getMinRank(), HelpersPHEMlight::getModifiedAccel(), NIImporter_OpenStreetMap::getNeighboringNodes(), MSLane::getNettoOccupancy(), ROEdge::getNoiseEffort(), CState::getPosition(), GUIBaseVehicle::getSeatPosition(), NBEdge::getShapeEndAngle(), NBEdge::getShapeStartAngle(), MSLeaderInfo::getSublaneBorders(), MSLeaderInfo::getSubLanes(), PublicTransportEdge< E, L, N, V >::getTravelTime(), ROEdge::getTravelTime(), MSLane::getVehicleMaxSpeed(), MSLink::getZipperSpeed(), GUIDialog_ViewSettings::GUIDialog_ViewSettings(), MSLane::handleCollisionBetween(), MSVehicle::Influencer::influenceSpeed(), MSLCM_LC2013::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSPModel_Striping::initWalkingAreaPaths(), MSCFModel::insertionStopSpeed(), MSCFModel::interactionGap(), NBNodeCont::joinJunctions(), MSLCM_SL2015::keepLatGap(), MSLane::lastInsertion(), SUMORouteLoaderControl::loadNext(), MESegment::loadState(), MSE2Collector::makeMoveNotification(), MSCFModel::maximumSafeStopSpeedEuler(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MIN3(), MIN4(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), libsumo::Helper::moveToXYMap_matchingRoutePosition(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBEdge::NBEdge(), MESegment::newArrival(), TraCIServer::nextTargetTime(), MSMeanData::MeanDataValues::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), NBContHelper::straightness_sorter::operator()(), operator>>(), MSPModel_Striping::PState::otherStripe(), MSCFModel::passingTime(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSDevice_SSM::processEncounters(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), MSVehicle::processLinkAproaches(), ROLoader::processRoutes(), MSEdge::recalcCache(), MESegment::receive(), NBEdge::reinit(), NIImporter_DlrNavteq::TimeRestrictionsHandler::report(), ROMAAssignments::resetFlows(), MSLane::safeInsertionSpeed(), RONet::saveAndRemoveRoutesUntil(), MSLCM_SL2015::setOwnState(), MSLink::setRequestInformation(), GUIMainWindow::setWindowSizeAndPos(), NBEdge::shiftPositionAtNode(), NBEdge::shortenGeometryAtNode(), PositionVector::smoothedZFront(), GNEEdge::smoothShape(), NBEdgeCont::splitAt(), NBEdge::startShapeAt(), MSCFModel_Krauss::stopSpeed(), MSCFModel_Rail::stopSpeed(), MSCFModel_Kerner::stopSpeed(), MSCFModel_PWag2009::stopSpeed(), MSCFModel_Daniel1::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), MSCFModel_SmartSK::stopSpeed(), MSCFModel_Wiedemann::stopSpeed(), MSPModel_Striping::PState::stripe(), MSDelayBasedTrafficLightLogic::trySwitch(), AGFreeTime::typeFromHomeNight(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSVehicleControl::vehicleDeparted(), MSCFModel_KraussOrig1::vsafe(), MSPModel_Striping::PState::walk(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Net::MSLaneMeanDataValues::write(), NWWriter_OpenDrive::writeGeomSmooth(), MSInductLoop::writeXMLOutput(), MSE3Collector::writeXMLOutput(), and MSMeanData::writeXMLOutput().
MIN3()
template<typename T > T MIN3 (T a, T b, T c) inline
Definition at line 80 of file StdDefs.h.
References MIN2().
Referenced by MSCFModel_Kerner::_v(), NBNodeShapeComputer::badIntersection(), MSLCM_SL2015::commitManoeuvre(), MSTrafficLightLogic::init(), MSCFModel_Rail::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel::moveHelper(), MSLCM_SL2015::updateGaps(), and MSPModel_Striping::PState::walk().
MIN4()
template<typename T > T MIN4 (T a, T b, T c, T d) inline
Definition at line 94 of file StdDefs.h.
References MIN2().
Referenced by MSCFModel_Kerner::_v(), GLHelper::drawBoxLines(), and MSMeanData::MeanDataValues::notifyMove().
roundBits()
double roundBits (double x, int fractionBits)
round to the given number of mantissa bits beyond the given number
Definition at line 41 of file StdDefs.cpp.
Referenced by ISNAN().
truncate()
double truncate (double x, int fractionBits)
discrds mantissa bits beyond the given number
Definition at line 37 of file StdDefs.cpp.
Referenced by ISNAN().
Variable Documentation
gDebugFlag1
bool gDebugFlag1
global utility flags for debugging
Definition at line 32 of file StdDefs.cpp.
Referenced by MSLink::blockedAtTime(), MSLink::blockedByFoe(), NBNode::buildCrossings(), NIImporter_OpenDrive::OpenDriveLaneSection::buildSpeedChanges(), NBNode::buildWalkingAreas(), NBNode::checkCrossing(), MSVehicle::executeMove(), NIImporter_OpenDrive::findWidthSplit(), NBEdge::getCrossingAngle(), NBNode::getEdgesSortedByAngleAtNodeCenter(), MSLane::getLastVehicleInformation(), MSLink::getLeaderInfo(), NBNode::guessCrossings(), ISNAN(), MSPModel_Striping::PState::mergeObstacles(), MSPModel_Striping::moveInDirectionOnLane(), MSLink::opened(), MSVehicle::processLinkAproaches(), NIImporter_OpenDrive::recomputeWidths(), NIImporter_OpenDrive::revisitLaneSections(), NBEdge::setNodeBorder(), and NIImporter_OpenDrive::splitMinWidths().
gDebugFlag2
bool gDebugFlag2
Definition at line 33 of file StdDefs.cpp.
Referenced by MSLCM_SL2015::_patchSpeed(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::checkTraCICommands(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::commitManoeuvre(), MSCFModel::followSpeedTransient(), MSLCM_SL2015::inform(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), ISNAN(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::patchSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateGaps(), and MSLCM_SL2015::wantsChangeSublane().
gDebugFlag3
bool gDebugFlag3
Definition at line 34 of file StdDefs.cpp.
Referenced by ISNAN().
gDebugFlag4
bool gDebugFlag4
Definition at line 35 of file StdDefs.cpp.
Referenced by ISNAN().
gPrecision
int gPrecision
the precision for floating point outputs
Definition at line 29 of file StdDefs.cpp.
Referenced by SystemFrame::checkOptions(), ISNAN(), NIImporter_OpenDrive::myStartElement(), MSNet::postSimStepOutput(), MSDevice_Tripinfo::printStatistics(), time2string(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSEmissionExport::write(), MSXMLRawOut::write(), NWWriter_OpenDrive::writeInternalEdge(), NWWriter_OpenDrive::writeNormalEdge(), and MSDevice_SSM::writeOutConflict().
gPrecisionGeo
int gPrecisionGeo
Definition at line 30 of file StdDefs.cpp.
Referenced by SystemFrame::checkOptions(), MSVTypeProbe::execute(), ISNAN(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PCPolyContainer::save(), GUISUMOAbstractView::updatePositionInformation(), MSFCDExport::write(), NWWriter_XML::writeEdgesAndConnections(), GeoConvHelper::writeLocation(), NWWriter_XML::writeNodes(), MSDevice_SSM::writeOutConflict(), and MSFCDExport::writeTransportable().
INVALID_DOUBLE
const double INVALID_DOUBLE = std::numeric_limits<double>::max()
Definition at line 59 of file StdDefs.h.
Referenced by MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSCFModel::estimateArrivalTime(), MSLink::getLengthBeforeCrossing(), MSLink::getLengthsBeforeCrossing(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::reset().
SUMO_const_halfLaneAndOffset
const double SUMO_const_halfLaneAndOffset = (double)(3.2 / 2. + .1)
Definition at line 54 of file StdDefs.h.
Referenced by NIXMLEdgesHandler::myEndElement().
SUMO_const_halfLaneWidth
const double SUMO_const_halfLaneWidth = (double) 1.6
Definition at line 50 of file StdDefs.h.
SUMO_const_haltingSpeed
const double SUMO_const_haltingSpeed = (double) 0.1
the speed threshold at which vehicles are considered as halting
Definition at line 57 of file StdDefs.h.
Referenced by MSLCM_LC2013::_wantsChange(), GUIApplicationWindow::checkGamingEvents(), MSVehicle::checkLinkLeader(), MSLCM_SL2015::checkStrategicChange(), MSNet::getHaltingVehicleNumber(), libsumo::Lane::getLastStepHaltingNumber(), MSCFModel::getMinimalArrivalTime(), MSVehicle::getSpaceTillLastStanding(), libsumo::Edge::getVehicleHaltingNumber(), MSLane::isInsertionSuccess(), MSDevice_Tripinfo::notifyMove(), MSVehicle::processNextStop(), MSVehicle::setBrakingSignals(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateCFRelated(), MSVehicle::updateWaitingTime(), MSPModel_Striping::PState::walk(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
SUMO_const_laneOffset
const double SUMO_const_laneOffset = (double) .1
Definition at line 52 of file StdDefs.h.
Referenced by NBEdge::computeLaneShapes(), GUILane::drawBikeMarkings(), GUILane::drawMarkings(), GNELane::drawMarkings(), NIImporter_SUMO::reconstructEdgeShape(), and NBEdge::shiftPositionAtNode().
SUMO_const_laneWidth
const double SUMO_const_laneWidth = (double) 3.2
Definition at line 49 of file StdDefs.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), NLHandler::addLane(), NBNode::buildCrossings(), NBNode::buildWalkingAreas(), MSLCM_SL2015::checkStrategicChange(), NBEdge::computeLaneShapes(), NBNodeShapeComputer::computeNodeShapeDefault(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), GUILane::drawArrows(), GUIBusStop::getCenteringBoundary(), NBEdge::getLaneWidth(), MSVehicle::getPosition(), NIImporter_OpenStreetMap::insertEdge(), GUISUMOAbstractView::makeSnapshot(), NBRampsComputer::moveRampRight(), libsumo::Helper::moveToXYMap(), MSParkingArea::MSParkingArea(), and NIImporter_SUMO::reconstructEdgeShape().
SUMO_const_laneWidthAndOffset
const double SUMO_const_laneWidthAndOffset = (double) 3.3
Definition at line 53 of file StdDefs.h.
Referenced by NBEdge::getMaxLaneOffset(), and NIXMLEdgesHandler::myEndElement().
SUMO_const_quarterLaneWidth
const double SUMO_const_quarterLaneWidth = (double) 0.8
Definition at line 51 of file StdDefs.h.