SUMO - Simulation of Urban MObility: MSEventControl Class Reference
MSEventControl Class Reference
Stores time-dependant events and executes them at the proper time.
#include <MSEventControl.h>
Data Structures
class EventSortCrit
Sort-criterion for events.
Public Types
typedef std::pair< Command *, SUMOTime > Event
Combination of an event and the time it shall be executed at.
Public Member Functions
virtual void addEvent (Command *operation, SUMOTime execTimeStep=-1)
Adds an Event.
virtual void execute (SUMOTime time)
Executes time-dependant commands.
bool isEmpty ()
Returns whether events are in the que.
MSEventControl ()
Default constructor.
void setCurrentTimeStep (SUMOTime time)
Set the current Time.
virtual ~MSEventControl ()
Destructor.
Private Types
typedef std::priority_queue< Event, std::vector< Event >, EventSortCrit > EventCont
Container for time-dependant events, e.g. traffic-light-change.
Private Member Functions
SUMOTime getCurrentTimeStep ()
get the Current TimeStep used in addEvent.
MSEventControl (const MSEventControl &)
invalid copy constructor.
MSEventControl & operator= (const MSEventControl &)
invalid assignment operator.
Private Attributes
SUMOTime currentTimeStep
The current TimeStep.
EventCont myEvents
Event-container, holds executable events.
Detailed Description
Stores time-dependant events and executes them at the proper time.
Definition at line 56 of file MSEventControl.h.
Member Typedef Documentation
Event
typedef std::pair< Command*, SUMOTime > MSEventControl::Event
Combination of an event and the time it shall be executed at.
Definition at line 59 of file MSEventControl.h.
EventCont
typedef std::priority_queue< Event, std::vector< Event >, EventSortCrit > MSEventControl::EventCont private
Container for time-dependant events, e.g. traffic-light-change.
Definition at line 132 of file MSEventControl.h.
Constructor & Destructor Documentation
MSEventControl() [1/2]
MSEventControl::MSEventControl ()
Default constructor.
Definition at line 44 of file MSEventControl.cpp.
~MSEventControl()
MSEventControl::~MSEventControl () virtual
Destructor.
Definition at line 48 of file MSEventControl.cpp.
References myEvents.
MSEventControl() [2/2]
MSEventControl::MSEventControl (const MSEventControl &) private
invalid copy constructor.
Member Function Documentation
addEvent()
void MSEventControl::addEvent (Command * operation, SUMOTime execTimeStep = -1) virtual
Adds an Event.
Parameters
[in] operation The event to add
[in] execTimeStep The time the event shall be executed at (-1 means at sim start)
See also
Command
Reimplemented in GUIEventControl.
Definition at line 59 of file MSEventControl.cpp.
References myEvents.
Referenced by MSPModel_NonInteracting::add(), MSCModel_NonInteracting::add(), GUIEventControl::addEvent(), MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), NLTriggerBuilder::buildVaporizer(), MSDevice_Routing::buildVehicleDevices(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTLLogicControl::closeWAUT(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), MSLaneSpeedTrigger::init(), MSCalibrator::init(), MSDevice_Routing::MSDevice_Routing(), MSPModel_Striping::MSPModel_Striping(), MSTrafficLightLogic::MSTrafficLightLogic(), MSVTypeProbe::MSVTypeProbe(), MSTriggeredRerouter::myEndElement(), MSDevice_Routing::notifyEnter(), and MSTriggeredRerouter::setPermissions().
execute()
void MSEventControl::execute (SUMOTime time) virtual
Executes time-dependant commands.
Loops over all stored events, continuing until the first event which execution time lies beyond the given time + deltaT. If the event had to be executed before the given time, a warning is generated and the event deleted. Otherwise (the event is valid), the event is executed.
Each executed event must return the time that has to pass until it shall be executed again. If the returned time is 0, the event is deleted. Otherwise it is readded, after the new execution time (returned + current) is computed.
ProcessErrors thrown by executed commands are rethrown.
Parameters
[in] time The current simulation time
Exceptions
ProcessError From an executed Command
Reimplemented in GUIEventControl.
Definition at line 65 of file MSEventControl.cpp.
References DELTA_T, Command::execute(), myEvents, and WRITE_WARNING.
Referenced by GUIEventControl::execute(), and MSNet::simulationStep().
getCurrentTimeStep()
SUMOTime MSEventControl::getCurrentTimeStep () private
get the Current TimeStep used in addEvent.
Definition at line 112 of file MSEventControl.cpp.
References currentTimeStep, MSNet::getCurrentTimeStep(), and MSNet::getInstance().
isEmpty()
bool MSEventControl::isEmpty ()
Returns whether events are in the que.
Returns
whether events are in the que
Definition at line 102 of file MSEventControl.cpp.
References myEvents.
Referenced by MSNet::simulationState().
operator=()
MSEventControl& MSEventControl::operator= (const MSEventControl &) private
invalid assignment operator.
setCurrentTimeStep()
void MSEventControl::setCurrentTimeStep (SUMOTime time)
Set the current Time.
This method is only for Unit Testing. Set the current TimeStep used in addEvent. Normally the time is set automatically from an instance of MSNet.
Definition at line 107 of file MSEventControl.cpp.
References currentTimeStep.
Field Documentation
currentTimeStep
SUMOTime MSEventControl::currentTimeStep private
The current TimeStep.
Definition at line 135 of file MSEventControl.h.
Referenced by getCurrentTimeStep(), and setCurrentTimeStep().
myEvents
EventCont MSEventControl::myEvents private
Event-container, holds executable events.
Definition at line 138 of file MSEventControl.h.
Referenced by addEvent(), execute(), isEmpty(), and ~MSEventControl().
The documentation for this class was generated from the following files:
MSEventControl.h
MSEventControl.cpp