SUMO - Simulation of Urban MObility: RODUAFrame Class Reference
RODUAFrame Class Reference
Sets and checks options for dua-routing.
#include <RODUAFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid for usage within duarouter.
static void fillOptions ()
Inserts options used by duarouter into the OptionsCont-singleton.
Static Protected Member Functions
static void addDUAOptions ()
Inserts dua options used by duarouter into the OptionsCont-singleton.
static void addImportOptions ()
Inserts import options used by duarouter into the OptionsCont-singleton.
Detailed Description
Sets and checks options for dua-routing.
Definition at line 41 of file RODUAFrame.h.
Member Function Documentation
addDUAOptions()
void RODUAFrame::addDUAOptions () static protected
Inserts dua options used by duarouter into the OptionsCont-singleton.
Definition at line 127 of file RODUAFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by fillOptions().
addImportOptions()
void RODUAFrame::addImportOptions () static protected
Inserts import options used by duarouter into the OptionsCont-singleton.
Definition at line 76 of file RODUAFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by fillOptions().
checkOptions()
bool RODUAFrame::checkOptions () static
Checks set options from the OptionsCont-singleton for being valid for usage within duarouter.
Currently, this is done via a call to "ROFrame::checkOptions".
Returns
Whether all needed options are set
Todo:
probably, more things should be checked...
Definition at line 178 of file RODUAFrame.cpp.
References SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, ROFrame::checkOptions(), SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, OptionsCont::getBool(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isDefault(), OptionsCont::isSet(), SUMOVehicleParameter::parseArrivalLane(), SUMOVehicleParameter::parseArrivalPos(), SUMOVehicleParameter::parseArrivalSpeed(), SUMOVehicleParameter::parseDepartLane(), SUMOVehicleParameter::parseDepartPos(), SUMOVehicleParameter::parseDepartSpeed(), OptionsCont::set(), WRITE_ERROR, and WRITE_WARNING.
Referenced by main().
fillOptions()
void RODUAFrame::fillOptions () static
Inserts options used by duarouter into the OptionsCont-singleton.
As duarouter shares several options with other routing appplications, the insertion of these is done via a call to ROFrame::fillOptions.
duarouter-specific options are added afterwards via calls to "addImportOptions" and "addDUAOptions".
Definition at line 51 of file RODUAFrame.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), addDUAOptions(), addImportOptions(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), ROFrame::fillOptions(), OptionsCont::getOptions(), and RandHelper::insertRandOptions().
Referenced by main().
The documentation for this class was generated from the following files:
RODUAFrame.h
RODUAFrame.cpp