SUMO - Simulation of Urban MObility: MSFullExport Class Reference
MSFullExport Class Reference
Dumping a hugh List of Parameters available in the Simulation.
#include <MSFullExport.h>
Static Public Member Functions
static void write (OutputDevice &of, SUMOTime timestep)
Dumping a hugh List of Parameters available in the Simulation.
Private Member Functions
MSFullExport (const MSFullExport &)
Invalidated copy constructor.
MSFullExport & operator= (const MSFullExport &)
Invalidated assignment operator.
Static Private Member Functions
static void writeEdge (OutputDevice &of)
Writes the XML Nodes for the edges (e.g. traveltime)
static void writeLane (OutputDevice &of, const MSLane &lane)
Writes the XML Nodes for the lanes (e.g. emissions, occupancy)
static void writeTLS (OutputDevice &of, SUMOTime timestep)
Writes the XML Nodes for the traffic lights (e.g. actual state)
static void writeVehicles (OutputDevice &of)
Writes the XML Nodes for the vehicles (e.g. speed, position, emissions)
Detailed Description
Dumping a hugh List of Parameters available in the Simulation.
The class offers a static method, which writes a hugh List of Parameters available in the Simulation into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 56 of file MSFullExport.h.
Constructor & Destructor Documentation
MSFullExport()
MSFullExport::MSFullExport (const MSFullExport &) private
Invalidated copy constructor.
Member Function Documentation
operator=()
MSFullExport& MSFullExport::operator= (const MSFullExport &) private
Invalidated assignment operator.
write()
void MSFullExport::write (OutputDevice & of, SUMOTime timestep) static
Dumping a hugh List of Parameters available in the Simulation.
The class offers a static method, which writes a hugh List of Parameters available in the Simulation into the given OutputDevice.
Parameters
[in] of The output device to use
[in] timestep The current time step
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 51 of file MSFullExport.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), time2string(), writeEdge(), writeTLS(), and writeVehicles().
Referenced by MSNet::writeOutput().
writeEdge()
void MSFullExport::writeEdge (OutputDevice & of) static private
Writes the XML Nodes for the edges (e.g. traveltime)
Definition at line 92 of file MSFullExport.cpp.
References OutputDevice::closeTag(), MSEdge::getCurrentTravelTime(), MSNet::getEdgeControl(), MSEdgeControl::getEdges(), Named::getID(), MSNet::getInstance(), MSEdge::getLanes(), OutputDevice::openTag(), OutputDevice::writeAttr(), and writeLane().
Referenced by write().
writeLane()
void MSFullExport::writeLane (OutputDevice & of, const MSLane & lane) static private
Writes the XML Nodes for the lanes (e.g. emissions, occupancy)
Definition at line 110 of file MSFullExport.cpp.
References OutputDevice::closeTag(), MSLane::getCO2Emissions(), MSLane::getCOEmissions(), MSLane::getElectricityConsumption(), MSLane::getFuelConsumption(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHCEmissions(), Named::getID(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getNOxEmissions(), MSLane::getPMxEmissions(), MSLane::getSpeedLimit(), MSLane::getVehicleNumber(), OutputDevice::openTag(), and OutputDevice::writeAttr().
Referenced by writeEdge().
writeTLS()
void MSFullExport::writeTLS (OutputDevice & of, SUMOTime timestep) static private
Writes the XML Nodes for the traffic lights (e.g. actual state)
Definition at line 122 of file MSFullExport.cpp.
References OutputDevice::closeTag(), MSTLLogicControl::get(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTLLogicControl::getAllTLIds(), MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getInstance(), MSTrafficLightLogic::getLaneVectors(), MSPhaseDefinition::getState(), MSNet::getTLSControl(), OutputDevice::openTag(), and OutputDevice::writeAttr().
Referenced by write().
writeVehicles()
void MSFullExport::writeVehicles (OutputDevice & of) static private
Writes the XML Nodes for the vehicles (e.g. speed, position, emissions)
Definition at line 64 of file MSFullExport.cpp.
References OutputDevice::closeTag(), PollutantsInterface::Emissions::CO, PollutantsInterface::Emissions::CO2, PollutantsInterface::computeAll(), HelpersHarmonoise::computeNoise(), PollutantsInterface::Emissions::electricity, PollutantsInterface::Emissions::fuel, SUMOVehicle::getAcceleration(), SUMOVehicle::getAngle(), MSVehicleType::getEmissionClass(), Named::getID(), SUMOVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicle::getLane(), PollutantsInterface::getName(), SUMOVehicle::getPosition(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getRoute(), SUMOVehicle::getSlope(), SUMOVehicle::getSpeed(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), PollutantsInterface::Emissions::HC, SUMOVehicle::isOnRoad(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), GeomHelper::naviDegree(), PollutantsInterface::Emissions::NOx, OutputDevice::openTag(), PollutantsInterface::Emissions::PMx, OutputDevice::writeAttr(), Position::x(), and Position::y().
Referenced by write().
The documentation for this class was generated from the following files:
MSFullExport.h
MSFullExport.cpp