SUMO - Simulation of Urban MObility: NWWriter_XML Class Reference
NWWriter_XML Class Reference
Exporter writing networks using XML (native input) format.
#include <NWWriter_XML.h>
Static Public Member Functions
static void writeJoinedJunctions (const OptionsCont &oc, NBNodeCont &nc)
Writes the joined-juncionts to file.
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into XML-files (nodes, edges, connections, traffic lights)
static void writeStreetSigns (const OptionsCont &oc, NBEdgeCont &ec)
Writes street signs as POIs to file.
Static Private Member Functions
static void writeEdgesAndConnections (const OptionsCont &oc, NBNodeCont &nc, NBEdgeCont &ec)
Writes the edges and connections files.
static void writeNodes (const OptionsCont &oc, NBNodeCont &nc)
Writes the nodes file.
static void writeParkingAreas (const OptionsCont &cont, NBParkingCont &pc, NBEdgeCont &ec)
writes imported parking areas to file
static void writePTLines (const OptionsCont &cont, NBPTLineCont &lc, NBEdgeCont &ec)
static void writePTStops (const OptionsCont &oc, NBPTStopCont &ec)
Writes the pt stops file.
static void writeTrafficLights (const OptionsCont &oc, NBTrafficLightLogicCont &tc, NBEdgeCont &ec)
Writes the traffic lights file.
static void writeTypes (const OptionsCont &oc, NBTypeCont &tc)
Writes the types file.
Detailed Description
Exporter writing networks using XML (native input) format.
Definition at line 64 of file NWWriter_XML.h.
Member Function Documentation
writeEdgesAndConnections()
void NWWriter_XML::writeEdgesAndConnections (const OptionsCont & oc, NBNodeCont & nc, NBEdgeCont & ec) static private
Writes the edges and connections files.
Parameters
[in] oc The options to use
[in] nb The network build from which to read data
Definition at line 174 of file NWWriter_XML.cpp.
References NBEdge::Lane::accelRamp, NBNodeCont::begin(), NBEdgeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), OutputDevice::closeTag(), NBEdge::Lane::customShape, NBNodeCont::end(), NBEdgeCont::end(), NBEdge::Lane::endOffset, StringUtils::escapeXML(), OptionsCont::exists(), OptionsCont::getBool(), NBEdge::getConnections(), OutputDevice::getDevice(), NBEdge::getEndOffset(), GeoConvHelper::getFinal(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLanes(), NBEdge::getLaneSpreadFunction(), NBEdge::getLaneWidth(), NBEdge::getLoadedLength(), NBEdge::getNumLanes(), NBNode::getOutgoingEdges(), NBEdge::getPermissions(), NBEdge::getPriority(), NBEdgeCont::getRoundabouts(), NBEdge::getSpeed(), NBEdge::getStreetName(), OptionsCont::getString(), NBEdge::getToNode(), NBEdge::getTypeID(), gPrecisionGeo, NBEdge::hasDefaultGeometry(), NBEdge::hasLaneSpecificEndOffset(), NBEdge::hasLaneSpecificPermissions(), NBEdge::hasLaneSpecificSpeed(), NBEdge::hasLaneSpecificWidth(), NBEdge::hasLoadedLength(), LANESPREAD_RIGHT, OutputDevice::lf(), NWFrame::MAJOR_VERSION, NBEdge::needsLaneSpecificOutput(), OutputDevice::openTag(), NBEdge::Lane::oppositeID, NBEdge::Lane::permissions, NWWriter_SUMO::PLAIN, NBEdge::Lane::preferred, OutputDevice::setPrecision(), NBEdge::Lane::speed, SUMO_ATTR_ACCELERATION, SUMO_ATTR_EDGES, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LANE, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NODE, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_VERSION, SUMO_ATTR_WIDTH, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_LANE, SUMO_TAG_NEIGH, SVC_PEDESTRIAN, toString(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, GeoConvHelper::usingInverseGeoProjection(), NBEdge::Lane::width, OutputDevice::writeAttr(), NWWriter_SUMO::writeConnection(), Parameterised::writeParams(), writePermissions(), writePreferences(), NWWriter_SUMO::writeProhibitions(), NWWriter_SUMO::writeRoundabouts(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writeJoinedJunctions()
void NWWriter_XML::writeJoinedJunctions (const OptionsCont & oc, NBNodeCont & nc) static
Writes the joined-juncionts to file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 360 of file NWWriter_XML.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), OutputDevice::getDevice(), NBNodeCont::getJoinedClusters(), OptionsCont::getString(), NWFrame::MAJOR_VERSION, OutputDevice::openTag(), SUMO_ATTR_NODES, SUMO_ATTR_VERSION, SUMO_TAG_JOIN, OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by GNENet::saveJoined(), and writeNetwork().
writeNetwork()
void NWWriter_XML::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into XML-files (nodes, edges, connections, traffic lights)
Parameters
[in] oc The options to use
[in] nb The network builder from which to read data
Definition at line 58 of file NWWriter_XML.cpp.
References OptionsCont::exists(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), NBNetBuilder::getParkingCont(), NBNetBuilder::getPTLineCont(), NBNetBuilder::getPTStopCont(), NBNetBuilder::getTLLogicCont(), NBNetBuilder::getTypeCont(), OptionsCont::isSet(), NBTypeCont::size(), writeEdgesAndConnections(), writeJoinedJunctions(), writeNodes(), writeParkingAreas(), writePTLines(), writePTStops(), writeStreetSigns(), writeTrafficLights(), and writeTypes().
Referenced by GNENet::savePlain(), and NWFrame::writeNetwork().
writeNodes()
void NWWriter_XML::writeNodes (const OptionsCont & oc, NBNodeCont & nc) static private
Writes the nodes file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 88 of file NWWriter_XML.cpp.
References NBNodeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), OutputDevice::closeTag(), NBNodeCont::end(), OptionsCont::exists(), OptionsCont::getBool(), NBNode::getControllingTLS(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), Named::getID(), NBNode::getKeepClear(), NBNode::getPosition(), NBNode::getRadius(), NBNode::getShape(), OptionsCont::getString(), NBNode::getType(), gPrecisionGeo, NBNode::hasCustomShape(), NBNode::isTLControlled(), joinToString(), NWFrame::MAJOR_VERSION, OutputDevice::openTag(), OutputDevice::setPrecision(), SUMO_ATTR_CONTROLLED_INNER, SUMO_ATTR_ID, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TLID, SUMO_ATTR_TYPE, SUMO_ATTR_VERSION, SUMO_TAG_NODE, toString(), NBNode::UNSPECIFIED_RADIUS, GeoConvHelper::usingGeoProjection(), GeoConvHelper::usingInverseGeoProjection(), WRITE_WARNING, OutputDevice::writeAttr(), GeoConvHelper::writeLocation(), Parameterised::writeParams(), NWFrame::writePositionLong(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writeParkingAreas()
void NWWriter_XML::writeParkingAreas (const OptionsCont & cont, NBParkingCont & pc, NBEdgeCont & ec) static private
writes imported parking areas to file
Definition at line 414 of file NWWriter_XML.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), OptionsCont::getString(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writePTLines()
void NWWriter_XML::writePTLines (const OptionsCont & cont, NBPTLineCont & lc, NBEdgeCont & ec) static private
Definition at line 405 of file NWWriter_XML.cpp.
References NBPTLineCont::begin(), OutputDevice::close(), NBPTLineCont::end(), OutputDevice::getDevice(), OptionsCont::getString(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writePTStops()
void NWWriter_XML::writePTStops (const OptionsCont & oc, NBPTStopCont & ec) static private
Writes the pt stops file.
Parameters
[in] oc The options to use
[in] nc The pt stop container from which to read data
Definition at line 397 of file NWWriter_XML.cpp.
References NBPTStopCont::begin(), OutputDevice::close(), NBPTStopCont::end(), OutputDevice::getDevice(), OptionsCont::getString(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writeStreetSigns()
void NWWriter_XML::writeStreetSigns (const OptionsCont & oc, NBEdgeCont & ec) static
Writes street signs as POIs to file.
Parameters
[in] oc The options to use
[in] ec The edge-container from which to read data
Definition at line 384 of file NWWriter_XML.cpp.
References NBEdgeCont::begin(), OutputDevice::close(), NBEdgeCont::end(), OutputDevice::getDevice(), NBEdge::getSigns(), OptionsCont::getString(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writeTrafficLights()
void NWWriter_XML::writeTrafficLights (const OptionsCont & oc, NBTrafficLightLogicCont & tc, NBEdgeCont & ec) static private
Writes the traffic lights file.
Parameters
[in] oc The options to use
[in] tc The tll-container from which to read data
[in] ec The edge-container from which to read data
Definition at line 337 of file NWWriter_XML.cpp.
References NBEdgeCont::begin(), OutputDevice::close(), NBEdgeCont::end(), NBEdge::getConnections(), OutputDevice::getDevice(), OptionsCont::getString(), NWFrame::MAJOR_VERSION, SUMO_ATTR_VERSION, NWWriter_SUMO::TLL, NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeTrafficLights(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
writeTypes()
void NWWriter_XML::writeTypes (const OptionsCont & oc, NBTypeCont & tc) static private
Writes the types file.
Parameters
[in] oc The options to use
[in] nc The type-container from which to read data
Definition at line 163 of file NWWriter_XML.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), OptionsCont::getString(), NWFrame::MAJOR_VERSION, SUMO_ATTR_VERSION, NBTypeCont::writeTypes(), and OutputDevice::writeXMLHeader().
Referenced by writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_XML.h
NWWriter_XML.cpp