SUMO - Simulation of Urban MObility: libsumo::Vehicle Class Reference
libsumo::Vehicle Class Reference
#include <Vehicle.h>
Static Public Member Functions
Value retrieval
static std::vector< std::string > getIDList ()
static int getIDCount ()
static double getSpeed (const std::string &vehicleID)
static double getSpeedWithoutTraCI (const std::string &vehicleID)
static TraCIPosition getPosition (const std::string &vehicleID)
static TraCIPosition getPosition3D (const std::string &vehicleID)
static double getAngle (const std::string &vehicleID)
static double getSlope (const std::string &vehicleID)
static std::string getRoadID (const std::string &vehicleID)
static std::string getLaneID (const std::string &vehicleID)
static int getLaneIndex (const std::string &vehicleID)
static std::string getTypeID (const std::string &vehicleID)
static std::string getRouteID (const std::string &vehicleID)
static int getRouteIndex (const std::string &vehicleID)
static TraCIColor getColor (const std::string &vehicleID)
static double getLanePosition (const std::string &vehicleID)
static double getLateralLanePosition (const std::string &vehicleID)
static double getCO2Emission (const std::string &vehicleID)
static double getCOEmission (const std::string &vehicleID)
static double getHCEmission (const std::string &vehicleID)
static double getPMxEmission (const std::string &vehicleID)
static double getNOxEmission (const std::string &vehicleID)
static double getFuelConsumption (const std::string &vehicleID)
static double getNoiseEmission (const std::string &vehicleID)
static double getElectricityConsumption (const std::string &vehicleID)
static int getPersonNumber (const std::string &vehicleID)
static std::pair< std::string, double > getLeader (const std::string &vehicleID, double dist)
static double getWaitingTime (const std::string &vehicleID)
static double getAccumulatedWaitingTime (const std::string &vehicleID)
static double getAdaptedTraveltime (const std::string &vehicleID, const std::string &edgeID, int time)
static double getEffort (const std::string &vehicleID, const std::string &edgeID, int time)
static bool isRouteValid (const std::string &vehicleID)
static std::vector< std::string > getEdges (const std::string &vehicleID)
static int getSignalStates (const std::string &vehicleID)
static std::vector< TraCIBestLanesData > getBestLanes (const std::string &vehicleID)
static std::vector< TraCINextTLSData > getNextTLS (const std::string &vehicleID)
static int getStopState (const std::string &vehicleID)
static double getDistance (const std::string &vehicleID)
static double getDrivingDistance (const std::string &vehicleID, const std::string &edgeID, double position, int laneIndex)
static double getDrivingDistance2D (const std::string &vehicleID, double x, double y)
static double getAllowedSpeed (const std::string &vehicleID)
static double getSpeedFactor (const std::string &vehicleID)
static int getSpeedMode (const std::string &vehicleID)
static int getLanechangeMode (const std::string &vehicleID)
static int getRoutingMode (const std::string &vehicleID)
static std::string getLine (const std::string &vehicleID)
static std::vector< std::string > getVia (const std::string &vehicleID)
static std::pair< int, int > getLaneChangeState (const std::string &vehicleID, int direction)
static std::string getParameter (const std::string &vehicleID, const std::string &key)
static const MSVehicleType & getVehicleType (const std::string &vehicleID)
vehicle type value retrieval shortcuts
static std::string getEmissionClass (const std::string &vehicleID)
static std::string getShapeClass (const std::string &vehicleID)
static std::string getVClass (const std::string &vehicleID)
static double getLength (const std::string &vehicleID)
static double getAccel (const std::string &vehicleID)
static double getDecel (const std::string &vehicleID)
static double getEmergencyDecel (const std::string &vehicleID)
static double getApparentDecel (const std::string &vehicleID)
static double getActionStepLength (const std::string &vehicleID)
static double getLastActionTime (const std::string &vehicleID)
static double getTau (const std::string &vehicleID)
static double getImperfection (const std::string &vehicleID)
static double getSpeedDeviation (const std::string &vehicleID)
static double getMinGap (const std::string &vehicleID)
static double getMaxSpeed (const std::string &vehicleID)
static double getWidth (const std::string &vehicleID)
State Changing
static void setStop (const std::string &vehicleID, const std::string &edgeID, double endPos=1., int laneIndex=0, SUMOTime duration=4294967295u, int flags=STOP_DEFAULT, double startPos=INVALID_DOUBLE_VALUE, SUMOTime until=-1)
static void resume (const std::string &vehicleID)
static void add (const std::string &vehicleID, const std::string &routeID, const std::string &typeID="DEFAULT_VEHTYPE", int depart=DEPARTFLAG_NOW, int departLane=DEPARTFLAG_LANE_FIRST_ALLOWED, double departPos=DEPARTFLAG_POS_BASE, double departSpeed=0, int arrivalLane=ARRIVALFLAG_LANE_CURRENT, double arrivalPos=ARRIVALFLAG_POS_MAX, double arrivalSpeed=ARRIVALFLAG_SPEED_CURRENT, const std::string &fromTaz="", const std::string &toTaz="", const std::string &line="", int personCapacity=4, int personNumber=0)
static void changeTarget (const std::string &vehicleID, const std::string &edgeID)
static void changeLane (const std::string &vehicleID, int laneIndex, SUMOTime duration)
static void changeSublane (const std::string &vehicleID, double latDist)
static void slowDown (const std::string &vehicleID, double speed, SUMOTime duration)
static void setSpeed (const std::string &vehicleID, double speed)
static void setType (const std::string &vehicleID, const std::string &typeID)
static void setRouteID (const std::string &vehicleID, const std::string &routeID)
static void setRoute (const std::string &vehicleID, const std::vector< std::string > &edgeIDs)
static void setAdaptedTraveltime (const std::string &vehicleID, const std::string &edgeID, double time=INVALID_DOUBLE_VALUE, double begSeconds=0, double endSeconds=std::numeric_limits< double >::max())
static void setEffort (const std::string &vehicleID, const std::string &edgeID, double effort=INVALID_DOUBLE_VALUE, double begSeconds=0, double endSeconds=std::numeric_limits< double >::max())
static void rerouteTraveltime (const std::string &vehicleID)
static void rerouteEffort (const std::string &vehicleID)
static void setSignals (const std::string &vehicleID, int signals)
static void moveTo (const std::string &vehicleID, const std::string &laneID, double position)
static void moveToXY (const std::string &vehicleID, const std::string &edgeID, const int laneIndex, const double x, const double y, double angle, const int keepRouteFlag)
static void setMaxSpeed (const std::string &vehicleID, double speed)
static void setActionStepLength (const std::string &vehicleID, double actionStepLength, bool resetActionOffset=true)
static void remove (const std::string &vehicleID, char reason=REMOVE_VAPORIZED)
static void setColor (const std::string &vehicleID, const TraCIColor &col)
static void setLine (const std::string &vehicleID, const std::string &line)
static void setVia (const std::string &vehicleID, const std::vector< std::string > &via)
static void setShapeClass (const std::string &vehicleID, const std::string &clazz)
static void setEmissionClass (const std::string &vehicleID, const std::string &clazz)
static void setParameter (const std::string &vehicleID, const std::string &key, const std::string &value)
Private Member Functions
Vehicle & operator= (const Vehicle &src)
invalidated assignment operator
Vehicle ()
invalidated standard constructor
Vehicle (const Vehicle &src)
invalidated copy constructor
Static Private Member Functions
static MSVehicle * getVehicle (const std::string &id)
static bool isOnInit (const std::string &vehicleID)
static bool isVisible (const MSVehicle *veh)
Detailed Description
Definition at line 53 of file Vehicle.h.
Constructor & Destructor Documentation
Vehicle() [1/2]
libsumo::Vehicle::Vehicle () private
invalidated standard constructor
Vehicle() [2/2]
libsumo::Vehicle::Vehicle (const Vehicle & src) private
invalidated copy constructor
Member Function Documentation
add()
void Vehicle::add (const std::string & vehicleID, const std::string & routeID, const std::string & typeID = "DEFAULT_VEHTYPE", int depart = DEPARTFLAG_NOW, int departLane = DEPARTFLAG_LANE_FIRST_ALLOWED, double departPos = DEPARTFLAG_POS_BASE, double departSpeed = 0, int arrivalLane = ARRIVALFLAG_LANE_CURRENT, double arrivalPos = ARRIVALFLAG_POS_MAX, double arrivalSpeed = ARRIVALFLAG_SPEED_CURRENT, const std::string & fromTaz = "", const std::string & toTaz = "", const std::string & line = "", int personCapacity = 4, int personNumber = 0) static
Definition at line 753 of file Vehicle.cpp.
References MSInsertionControl::add(), MSVehicleControl::addVehicle(), MSVehicleControl::buildVehicle(), SUMOVehicleParameter::depart, DEPART_DEF_MAX, DEPART_LANE_DEF_MAX, DEPART_LANE_GIVEN, DEPART_POS_DEF_MAX, DEPART_POS_GIVEN, DEPART_SPEED_DEF_MAX, DEPART_SPEED_GIVEN, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSRoute::dictionary(), MSNet::getCurrentTimeStep(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, NUMERICAL_EPS, and WRITE_WARNING.
Referenced by TraCIServerAPI_Vehicle::processSet().
changeLane()
void Vehicle::changeLane (const std::string & vehicleID, int laneIndex, SUMOTime duration) static
Definition at line 738 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), MSNet::getInstance(), getVehicle(), and MSVehicle::Influencer::setLaneTimeLine().
Referenced by TraCIServerAPI_Vehicle::processSet().
changeSublane()
void Vehicle::changeSublane (const std::string & vehicleID, double latDist) static
Definition at line 747 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), getVehicle(), and MSVehicle::Influencer::setSublaneChange().
Referenced by TraCIServerAPI_Vehicle::processSet().
changeTarget()
void Vehicle::changeTarget (const std::string & vehicleID, const std::string & edgeID) static
Definition at line 712 of file Vehicle.cpp.
References SUMOAbstractRouter< E, V >::compute(), MSEdge::dictionary(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getRerouteOrigin(), MSNet::getRouterTT(), getVehicle(), isOnInit(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
Referenced by TraCIServerAPI_Vehicle::processSet().
getAccel()
double Vehicle::getAccel (const std::string & vehicleID) static
Definition at line 563 of file Vehicle.cpp.
References MSVehicleType::getLength(), and getVehicleType().
getAccumulatedWaitingTime()
double Vehicle::getAccumulatedWaitingTime (const std::string & vehicleID) static
Definition at line 270 of file Vehicle.cpp.
References MSVehicle::getAccumulatedWaitingSeconds(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getActionStepLength()
double Vehicle::getActionStepLength (const std::string & vehicleID) static
Definition at line 580 of file Vehicle.cpp.
References MSVehicleType::getActionStepLengthSecs(), and getVehicleType().
getAdaptedTraveltime()
double Vehicle::getAdaptedTraveltime (const std::string & vehicleID, const std::string & edgeID, int time) static
Definition at line 276 of file Vehicle.cpp.
References libsumo::Helper::getEdge(), getVehicle(), MSVehicle::getWeightsStorage(), INVALID_DOUBLE_VALUE, and MSEdgeWeightsStorage::retrieveExistingTravelTime().
Referenced by TraCIServerAPI_Vehicle::processGet().
getAllowedSpeed()
double Vehicle::getAllowedSpeed (const std::string & vehicleID) static
Definition at line 455 of file Vehicle.cpp.
References MSVehicle::getLane(), getVehicle(), MSLane::getVehicleMaxSpeed(), INVALID_DOUBLE_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getAngle()
double Vehicle::getAngle (const std::string & vehicleID) static
Definition at line 129 of file Vehicle.cpp.
References MSVehicle::getAngle(), getVehicle(), INVALID_DOUBLE_VALUE, isVisible(), and GeomHelper::naviDegree().
Referenced by TraCIServerAPI_Vehicle::processGet().
getApparentDecel()
double Vehicle::getApparentDecel (const std::string & vehicleID) static
Definition at line 577 of file Vehicle.cpp.
References MSCFModel::getApparentDecel(), MSVehicleType::getCarFollowModel(), and getVehicleType().
getBestLanes()
std::vector< TraCIBestLanesData > Vehicle::getBestLanes (const std::string & vehicleID) static
Definition at line 319 of file Vehicle.cpp.
References libsumo::TraCIBestLanesData::allowsContinuation, MSVehicle::LaneQ::allowsContinuation, MSVehicle::LaneQ::bestContinuations, libsumo::TraCIBestLanesData::bestLaneOffset, MSVehicle::LaneQ::bestLaneOffset, libsumo::TraCIBestLanesData::continuationLanes, MSVehicle::getBestLanes(), Named::getID(), getVehicle(), MSVehicle::isOnRoad(), MSVehicle::LaneQ::lane, libsumo::TraCIBestLanesData::laneID, libsumo::TraCIBestLanesData::length, MSVehicle::LaneQ::length, MSVehicle::LaneQ::nextOccupation, and libsumo::TraCIBestLanesData::occupation.
Referenced by TraCIServerAPI_Vehicle::processGet().
getCO2Emission()
double Vehicle::getCO2Emission (const std::string & vehicleID) static
Definition at line 196 of file Vehicle.cpp.
References MSVehicle::getCO2Emissions(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getCOEmission()
double Vehicle::getCOEmission (const std::string & vehicleID) static
Definition at line 202 of file Vehicle.cpp.
References MSVehicle::getCOEmissions(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getColor()
TraCIColor Vehicle::getColor (const std::string & vehicleID) static
Definition at line 179 of file Vehicle.cpp.
References getParameter(), getVehicle(), and libsumo::Helper::makeTraCIColor().
Referenced by TraCIServerAPI_Vehicle::processGet().
getDecel()
double Vehicle::getDecel (const std::string & vehicleID) static
Definition at line 569 of file Vehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getMaxDecel(), and getVehicleType().
getDistance()
double Vehicle::getDistance (const std::string & vehicleID) static
Definition at line 394 of file Vehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::getCurrentRouteEdge(), MSBaseVehicle::getDepartPos(), MSRoute::getDistanceBetween(), MSLane::getEdge(), MSVehicle::getLane(), getLength(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), getVehicle(), INVALID_DOUBLE_VALUE, MSLane::isInternal(), and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getDrivingDistance()
double Vehicle::getDrivingDistance (const std::string & vehicleID, const std::string & edgeID, double position, int laneIndex) static
Definition at line 421 of file Vehicle.cpp.
References MSRoute::getDistanceBetween(), libsumo::Helper::getEdge(), MSLane::getEdge(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), getVehicle(), INVALID_DOUBLE_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getDrivingDistance2D()
double Vehicle::getDrivingDistance2D (const std::string & vehicleID, double x, double y) static
Definition at line 437 of file Vehicle.cpp.
References libsumo::Helper::convertCartesianToRoadMap(), MSRoute::getDistanceBetween(), MSBaseVehicle::getEdge(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), getVehicle(), INVALID_DOUBLE_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getEdges()
std::vector< std::string > Vehicle::getEdges (const std::string & vehicleID) static
Definition at line 302 of file Vehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSBaseVehicle::getRoute(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getEffort()
double Vehicle::getEffort (const std::string & vehicleID, const std::string & edgeID, int time) static
Definition at line 286 of file Vehicle.cpp.
References libsumo::Helper::getEdge(), getVehicle(), MSVehicle::getWeightsStorage(), INVALID_DOUBLE_VALUE, and MSEdgeWeightsStorage::retrieveExistingEffort().
Referenced by TraCIServerAPI_Vehicle::processGet().
getElectricityConsumption()
double Vehicle::getElectricityConsumption (const std::string & vehicleID) static
Definition at line 238 of file Vehicle.cpp.
References MSVehicle::getElectricityConsumption(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getEmergencyDecel()
double Vehicle::getEmergencyDecel (const std::string & vehicleID) static
Definition at line 574 of file Vehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getEmergencyDecel(), and getVehicleType().
getEmissionClass()
std::string Vehicle::getEmissionClass (const std::string & vehicleID) static
Definition at line 546 of file Vehicle.cpp.
References PollutantsInterface::getName(), and getVehicleType().
getFuelConsumption()
double Vehicle::getFuelConsumption (const std::string & vehicleID) static
Definition at line 226 of file Vehicle.cpp.
References MSVehicle::getFuelConsumption(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getHCEmission()
double Vehicle::getHCEmission (const std::string & vehicleID) static
Definition at line 208 of file Vehicle.cpp.
References MSVehicle::getHCEmissions(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getIDCount()
int Vehicle::getIDCount () static
Definition at line 95 of file Vehicle.cpp.
References getIDList().
Referenced by TraCIServerAPI_Vehicle::processGet().
getIDList()
std::vector< std::string > Vehicle::getIDList () static
Definition at line 83 of file Vehicle.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::loadedVehBegin(), and MSVehicleControl::loadedVehEnd().
Referenced by getIDCount(), and TraCIServerAPI_Vehicle::processGet().
getImperfection()
double Vehicle::getImperfection (const std::string & vehicleID) static
Definition at line 594 of file Vehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getImperfection(), and getVehicleType().
getLanechangeMode()
int Vehicle::getLanechangeMode (const std::string & vehicleID) static
Definition at line 476 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), MSVehicle::Influencer::getLanechangeMode(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getLaneChangeState()
std::pair< int, int > Vehicle::getLaneChangeState (const std::string & vehicleID, int direction) static
Definition at line 497 of file Vehicle.cpp.
References MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getSavedState(), getVehicle(), MSVehicle::isOnRoad(), and LCA_UNKNOWN.
Referenced by TraCIServerAPI_Vehicle::processGet().
getLaneID()
std::string Vehicle::getLaneID (const std::string & vehicleID) static
Definition at line 150 of file Vehicle.cpp.
References Named::getID(), MSVehicle::getLane(), getVehicle(), and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getLaneIndex()
int Vehicle::getLaneIndex (const std::string & vehicleID) static
Definition at line 157 of file Vehicle.cpp.
References MSLane::getIndex(), MSVehicle::getLane(), getVehicle(), INVALID_INT_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getLanePosition()
double Vehicle::getLanePosition (const std::string & vehicleID) static
Definition at line 184 of file Vehicle.cpp.
References MSVehicle::getPositionOnLane(), getVehicle(), INVALID_DOUBLE_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getLastActionTime()
double Vehicle::getLastActionTime (const std::string & vehicleID) static
Definition at line 583 of file Vehicle.cpp.
References getVehicle(), and STEPS2TIME.
Referenced by TraCIServerAPI_Vehicle::processGet().
getLateralLanePosition()
double Vehicle::getLateralLanePosition (const std::string & vehicleID) static
Definition at line 190 of file Vehicle.cpp.
References MSVehicle::getLateralPositionOnLane(), getVehicle(), INVALID_DOUBLE_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getLeader()
std::pair< std::string, double > Vehicle::getLeader (const std::string & vehicleID, double dist) static
Definition at line 250 of file Vehicle.cpp.
References MSVehicle::getLeader(), getVehicle(), and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getLength()
double Vehicle::getLength (const std::string & vehicleID) static
Definition at line 557 of file Vehicle.cpp.
References MSVehicleType::getLength(), and getVehicleType().
Referenced by getDistance().
getLine()
std::string Vehicle::getLine (const std::string & vehicleID) static
Definition at line 486 of file Vehicle.cpp.
References MSBaseVehicle::getParameter(), getVehicle(), and SUMOVehicleParameter::line.
Referenced by TraCIServerAPI_Vehicle::processGet().
getMaxSpeed()
double Vehicle::getMaxSpeed (const std::string & vehicleID) static
Definition at line 618 of file Vehicle.cpp.
References MSVehicleType::getMaxSpeed(), and getVehicleType().
getMinGap()
double Vehicle::getMinGap (const std::string & vehicleID) static
Definition at line 612 of file Vehicle.cpp.
References MSVehicleType::getMinGap(), and getVehicleType().
getNextTLS()
std::vector< TraCINextTLSData > Vehicle::getNextTLS (const std::string & vehicleID) static
Definition at line 345 of file Vehicle.cpp.
References libsumo::TraCINextTLSData::dist, MSVehicle::getBestLanesContinuation(), MSLane::getEdge(), MSVehicle::getLane(), MSLane::getLength(), MSVehicle::getPositionOnLane(), getVehicle(), libsumo::TraCINextTLSData::id, MSEdge::isInternal(), MSLane::isLinkEnd(), MSVehicle::isOnRoad(), libsumo::TraCINextTLSData::state, MSLane::succLinkSec(), and libsumo::TraCINextTLSData::tlIndex.
Referenced by TraCIServerAPI_Vehicle::processGet().
getNoiseEmission()
double Vehicle::getNoiseEmission (const std::string & vehicleID) static
Definition at line 232 of file Vehicle.cpp.
References MSVehicle::getHarmonoise_NoiseEmissions(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getNOxEmission()
double Vehicle::getNOxEmission (const std::string & vehicleID) static
Definition at line 220 of file Vehicle.cpp.
References MSVehicle::getNOxEmissions(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getParameter()
std::string Vehicle::getParameter (const std::string & vehicleID, const std::string & key) static
Definition at line 508 of file Vehicle.cpp.
References StringUtils::endsWith(), StringTokenizer::get(), MSBaseVehicle::getDeviceParameter(), MSVehicle::getLaneChangeModel(), MSBaseVehicle::getParameter(), Parameterised::getParameter(), MSAbstractLaneChangeModel::getParameter(), getVehicle(), MSBaseVehicle::hasDevice(), StringTokenizer::size(), and StringUtils::startsWith().
Referenced by getColor(), and TraCIServerAPI_Vehicle::processGet().
getPersonNumber()
int Vehicle::getPersonNumber (const std::string & vehicleID) static
Definition at line 244 of file Vehicle.cpp.
References MSVehicle::getPersonNumber(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getPMxEmission()
double Vehicle::getPMxEmission (const std::string & vehicleID) static
Definition at line 214 of file Vehicle.cpp.
References MSVehicle::getPMxEmissions(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getPosition()
TraCIPosition Vehicle::getPosition (const std::string & vehicleID) static
Definition at line 114 of file Vehicle.cpp.
References MSVehicle::getPosition(), getVehicle(), INVALID_DOUBLE_VALUE, isVisible(), libsumo::Helper::makeTraCIPosition(), libsumo::TraCIPosition::x, libsumo::TraCIPosition::y, and libsumo::TraCIPosition::z.
Referenced by TraCIServerAPI_Vehicle::processGet().
getPosition3D()
static TraCIPosition libsumo::Vehicle::getPosition3D (const std::string & vehicleID) static
getRoadID()
std::string Vehicle::getRoadID (const std::string & vehicleID) static
Definition at line 143 of file Vehicle.cpp.
References MSLane::getEdge(), Named::getID(), MSVehicle::getLane(), getVehicle(), and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getRouteID()
std::string Vehicle::getRouteID (const std::string & vehicleID) static
Definition at line 168 of file Vehicle.cpp.
References Named::getID(), MSBaseVehicle::getRoute(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getRouteIndex()
int Vehicle::getRouteIndex (const std::string & vehicleID) static
Definition at line 173 of file Vehicle.cpp.
References MSVehicle::getRoutePosition(), getVehicle(), MSBaseVehicle::hasDeparted(), and INVALID_INT_VALUE.
Referenced by TraCIServerAPI_Vehicle::processGet().
getRoutingMode()
int Vehicle::getRoutingMode (const std::string & vehicleID) static
Definition at line 481 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), MSVehicle::Influencer::getRoutingMode(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getShapeClass()
std::string Vehicle::getShapeClass (const std::string & vehicleID) static
Definition at line 551 of file Vehicle.cpp.
References getVehicleShapeName(), and getVehicleType().
getSignalStates()
int Vehicle::getSignalStates (const std::string & vehicleID) static
Definition at line 314 of file Vehicle.cpp.
References MSVehicle::getSignals(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getSlope()
double Vehicle::getSlope (const std::string & vehicleID) static
Definition at line 136 of file Vehicle.cpp.
References MSVehicle::getSlope(), getVehicle(), INVALID_DOUBLE_VALUE, and MSVehicle::isOnRoad().
Referenced by TraCIServerAPI_Vehicle::processGet().
getSpeed()
double Vehicle::getSpeed (const std::string & vehicleID) static
Definition at line 100 of file Vehicle.cpp.
References MSVehicle::getSpeed(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getSpeedDeviation()
double Vehicle::getSpeedDeviation (const std::string & vehicleID) static
Definition at line 600 of file Vehicle.cpp.
References Distribution_Parameterized::getParameter(), MSVehicleType::getSpeedFactor(), and getVehicleType().
getSpeedFactor()
double Vehicle::getSpeedFactor (const std::string & vehicleID) static
Definition at line 465 of file Vehicle.cpp.
References MSBaseVehicle::getChosenSpeedFactor(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getSpeedMode()
int Vehicle::getSpeedMode (const std::string & vehicleID) static
Definition at line 471 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), MSVehicle::Influencer::getSpeedMode(), and getVehicle().
Referenced by TraCIServerAPI_Vehicle::processGet().
getSpeedWithoutTraCI()
double Vehicle::getSpeedWithoutTraCI (const std::string & vehicleID) static
Definition at line 107 of file Vehicle.cpp.
References MSVehicle::getSpeedWithoutTraciInfluence(), getVehicle(), INVALID_DOUBLE_VALUE, and isVisible().
Referenced by TraCIServerAPI_Vehicle::processGet().
getStopState()
int Vehicle::getStopState (const std::string & vehicleID) static
Definition at line 377 of file Vehicle.cpp.
References MSVehicle::Stop::busstop, MSVehicle::Stop::chargingStation, MSVehicle::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, MSVehicle::getNextStop(), getVehicle(), MSVehicle::isStopped(), SUMOVehicleParameter::Stop::parking, MSVehicle::Stop::parkingarea, MSVehicle::Stop::pars, and SUMOVehicleParameter::Stop::triggered.
Referenced by TraCIServerAPI_Vehicle::processGet().
getTau()
double Vehicle::getTau (const std::string & vehicleID) static
Definition at line 588 of file Vehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getHeadwayTime(), and getVehicleType().
getTypeID()
std::string Vehicle::getTypeID (const std::string & vehicleID) static
Definition at line 163 of file Vehicle.cpp.
References MSVehicleType::getID(), getVehicle(), and MSBaseVehicle::getVehicleType().
Referenced by TraCIServerAPI_Vehicle::processGet().
getVClass()
std::string Vehicle::getVClass (const std::string & vehicleID) static
Definition at line 606 of file Vehicle.cpp.
References getVehicleType(), and toString().
getVehicle()
MSVehicle * Vehicle::getVehicle (const std::string & id) static private
Definition at line 57 of file Vehicle.cpp.
References MSNet::getInstance(), MSVehicleControl::getVehicle(), and MSNet::getVehicleControl().
Referenced by changeLane(), changeSublane(), changeTarget(), getAccumulatedWaitingTime(), getAdaptedTraveltime(), getAllowedSpeed(), getAngle(), getBestLanes(), getCO2Emission(), getCOEmission(), getColor(), getDistance(), getDrivingDistance(), getDrivingDistance2D(), getEdges(), getEffort(), getElectricityConsumption(), getFuelConsumption(), getHCEmission(), getLanechangeMode(), getLaneChangeState(), getLaneID(), getLaneIndex(), getLanePosition(), getLastActionTime(), getLateralLanePosition(), getLeader(), getLine(), getNextTLS(), getNoiseEmission(), getNOxEmission(), getParameter(), getPersonNumber(), getPMxEmission(), getPosition(), getRoadID(), getRouteID(), getRouteIndex(), getRoutingMode(), getSignalStates(), getSlope(), getSpeed(), getSpeedFactor(), getSpeedMode(), getSpeedWithoutTraCI(), getStopState(), getTypeID(), getVehicleType(), getVia(), getWaitingTime(), isRouteValid(), moveTo(), moveToXY(), remove(), rerouteEffort(), rerouteTraveltime(), resume(), setActionStepLength(), setAdaptedTraveltime(), setColor(), setEffort(), setEmissionClass(), setLine(), setMaxSpeed(), setParameter(), setRoute(), setRouteID(), setShapeClass(), setSignals(), setSpeed(), setStop(), setType(), setVia(), and slowDown().
getVehicleType()
const MSVehicleType & Vehicle::getVehicleType (const std::string & vehicleID) static
Definition at line 540 of file Vehicle.cpp.
References getVehicle(), and MSBaseVehicle::getVehicleType().
Referenced by getAccel(), getActionStepLength(), getApparentDecel(), getDecel(), getEmergencyDecel(), getEmissionClass(), getImperfection(), getLength(), getMaxSpeed(), getMinGap(), getShapeClass(), getSpeedDeviation(), getTau(), getVClass(), getWidth(), and TraCIServerAPI_Vehicle::processGet().
getVia()
std::vector< std::string > Vehicle::getVia (const std::string & vehicleID) static
Definition at line 491 of file Vehicle.cpp.
References MSBaseVehicle::getParameter(), getVehicle(), and SUMOVehicleParameter::via.
Referenced by TraCIServerAPI_Vehicle::processGet().
getWaitingTime()
double Vehicle::getWaitingTime (const std::string & vehicleID) static
Definition at line 264 of file Vehicle.cpp.
References getVehicle(), and MSVehicle::getWaitingSeconds().
Referenced by TraCIServerAPI_Vehicle::processGet().
getWidth()
double Vehicle::getWidth (const std::string & vehicleID) static
Definition at line 624 of file Vehicle.cpp.
References getVehicleType(), and MSVehicleType::getWidth().
isOnInit()
bool Vehicle::isOnInit (const std::string & vehicleID) static private
Definition at line 77 of file Vehicle.cpp.
References MSNet::getInstance(), SUMOVehicle::getLane(), MSVehicleControl::getVehicle(), and MSNet::getVehicleControl().
Referenced by changeTarget(), rerouteEffort(), and rerouteTraveltime().
isRouteValid()
bool Vehicle::isRouteValid (const std::string & vehicleID) static
Definition at line 296 of file Vehicle.cpp.
References getVehicle(), and MSBaseVehicle::hasValidRoute().
Referenced by TraCIServerAPI_Vehicle::processGet().
isVisible()
bool Vehicle::isVisible (const MSVehicle * veh) static private
Definition at line 71 of file Vehicle.cpp.
References MSVehicle::isOnRoad(), MSVehicle::isParking(), and MSVehicle::wasRemoteControlled().
Referenced by getAngle(), getCO2Emission(), getCOEmission(), getElectricityConsumption(), getFuelConsumption(), getHCEmission(), getNoiseEmission(), getNOxEmission(), getPMxEmission(), getPosition(), getRoadID(), getSpeed(), and getSpeedWithoutTraCI().
moveTo()
void Vehicle::moveTo (const std::string & vehicleID, const std::string & laneID, double position) static
Definition at line 1084 of file Vehicle.cpp.
References MSInsertionControl::alreadyDeparted(), MSLane::dictionary(), MSVehicle::enterLaneAtMove(), MSLane::forceVehicleInsertion(), MSBaseVehicle::getEdge(), MSLane::getEdge(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicle::getLane(), MSEdge::getLanes(), getVehicle(), MSNet::getVehicleControl(), MSBaseVehicle::hasDeparted(), MSVehicle::isOnRoad(), MSMoveReminder::NOTIFICATION_DEPARTED, MSMoveReminder::NOTIFICATION_TELEPORT, MSVehicle::onRemovalFromNet(), MSLane::removeVehicle(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicle::setTentativeLaneAndPosition(), MSBaseVehicle::succEdge(), and MSVehicle::willPass().
Referenced by TraCIServerAPI_Vehicle::processSet().
moveToXY()
void Vehicle::moveToXY (const std::string & vehicleID, const std::string & edgeID, const int laneIndex, const double x, const double y, double angle, const int keepRouteFlag) static
Definition at line 843 of file Vehicle.cpp.
References MSInsertionControl::alreadyDeparted(), Position::angleTo2D(), MSRoute::begin(), PositionVector::distance2D(), Position::distanceTo2D(), MSLane::geometryPositionAtOffset(), MSBaseVehicle::getCurrentRouteEdge(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPosition(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), MSVehicle::getRoutePosition(), MSLane::getShape(), getVehicle(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSGlobals::gLateralResolution, INVALID_DOUBLE_VALUE, GeomHelper::INVALID_OFFSET, MSVehicle::isOnRoad(), MIN2(), PositionVector::move2side(), libsumo::Helper::moveToXYMap(), libsumo::Helper::moveToXYMap_matchingRoutePosition(), GeomHelper::naviDegree(), PositionVector::rotationAtOffset(), libsumo::Helper::setRemoteControlled(), toString(), and WRITE_WARNING.
Referenced by TraCIServerAPI_Vehicle::processSet().
operator=()
Vehicle& libsumo::Vehicle::operator= (const Vehicle & src) private
invalidated assignment operator
remove()
void Vehicle::remove (const std::string & vehicleID, char reason = REMOVE_VAPORIZED) static
Definition at line 1144 of file Vehicle.cpp.
References getVehicle(), and UNUSED_PARAMETER.
rerouteEffort()
void Vehicle::rerouteEffort (const std::string & vehicleID) static
Definition at line 1064 of file Vehicle.cpp.
References MSNet::getInstance(), getVehicle(), isOnInit(), and MSBaseVehicle::reroute().
Referenced by TraCIServerAPI_Vehicle::processSet().
rerouteTraveltime()
void Vehicle::rerouteTraveltime (const std::string & vehicleID) static
Definition at line 1057 of file Vehicle.cpp.
References MSNet::getInstance(), getVehicle(), isOnInit(), and MSBaseVehicle::reroute().
Referenced by TraCIServerAPI_Vehicle::processSet().
resume()
void Vehicle::resume (const std::string & vehicleID) static
Definition at line 693 of file Vehicle.cpp.
References MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSBaseVehicle::getID(), MSVehicle::getNextStop(), getVehicle(), MSVehicle::hasStops(), MSVehicle::Stop::pars, MSVehicle::Stop::reached, MSVehicle::resumeFromStopping(), and SUMOVehicleParameter::Stop::startPos.
Referenced by TraCIServerAPI_Vehicle::processSet().
setActionStepLength()
void Vehicle::setActionStepLength (const std::string & vehicleID, double actionStepLength, bool resetActionOffset = true) static
Definition at line 1123 of file Vehicle.cpp.
References MSVehicle::getActionStepLength(), MSBaseVehicle::getSingularType(), getVehicle(), SUMOVehicleParserHelper::processActionStepLength(), MSVehicle::resetActionOffset(), MSVehicleType::setActionStepLength(), MSVehicle::updateActionOffset(), and WRITE_ERROR.
Referenced by TraCIServerAPI_Vehicle::processSet().
setAdaptedTraveltime()
void Vehicle::setAdaptedTraveltime (const std::string & vehicleID, const std::string & edgeID, double time = INVALID_DOUBLE_VALUE, double begSeconds = 0, double endSeconds = std::numeric_limits<double>::max()) static
Definition at line 1005 of file Vehicle.cpp.
References MSEdgeWeightsStorage::addTravelTime(), MSEdge::dictionary(), getVehicle(), MSVehicle::getWeightsStorage(), INVALID_DOUBLE_VALUE, MSEdgeWeightsStorage::knowsTravelTime(), and MSEdgeWeightsStorage::removeTravelTime().
Referenced by TraCIServerAPI_Vehicle::processSet().
setColor()
void Vehicle::setColor (const std::string & vehicleID, const TraCIColor & col) static
Definition at line 1151 of file Vehicle.cpp.
References libsumo::TraCIColor::a, libsumo::TraCIColor::b, SUMOVehicleParameter::color, libsumo::TraCIColor::g, MSBaseVehicle::getParameter(), getVehicle(), SUMOVehicleParameter::parametersSet, libsumo::TraCIColor::r, RGBColor::set(), and VEHPARS_COLOR_SET.
setEffort()
void Vehicle::setEffort (const std::string & vehicleID, const std::string & edgeID, double effort = INVALID_DOUBLE_VALUE, double begSeconds = 0, double endSeconds = std::numeric_limits<double>::max()) static
Definition at line 1031 of file Vehicle.cpp.
References MSEdgeWeightsStorage::addEffort(), MSEdge::dictionary(), getVehicle(), MSVehicle::getWeightsStorage(), INVALID_DOUBLE_VALUE, MSEdgeWeightsStorage::knowsEffort(), and MSEdgeWeightsStorage::removeEffort().
Referenced by TraCIServerAPI_Vehicle::processSet().
setEmissionClass()
void Vehicle::setEmissionClass (const std::string & vehicleID, const std::string & clazz) static
Definition at line 1175 of file Vehicle.cpp.
References getVehicle(), and UNUSED_PARAMETER.
setLine()
void Vehicle::setLine (const std::string & vehicleID, const std::string & line) static
Definition at line 1159 of file Vehicle.cpp.
References MSBaseVehicle::getParameter(), getVehicle(), and SUMOVehicleParameter::line.
setMaxSpeed()
void Vehicle::setMaxSpeed (const std::string & vehicleID, double speed) static
Definition at line 1118 of file Vehicle.cpp.
References MSBaseVehicle::getSingularType(), getVehicle(), and MSVehicleType::setMaxSpeed().
setParameter()
void Vehicle::setParameter (const std::string & vehicleID, const std::string & key, const std::string & value) static
Definition at line 1182 of file Vehicle.cpp.
References TplConvert::_2bool(), MSBaseVehicle::createDevice(), StringUtils::endsWith(), StringTokenizer::get(), MSVehicle::getLaneChangeModel(), MSBaseVehicle::getParameter(), getVehicle(), MSBaseVehicle::setDeviceParameter(), MSAbstractLaneChangeModel::setParameter(), StringTokenizer::size(), and StringUtils::startsWith().
Referenced by TraCIServerAPI_Vehicle::processSet().
setRoute()
void Vehicle::setRoute (const std::string & vehicleID, const std::vector< std::string > & edgeIDs) static
Definition at line 991 of file Vehicle.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLane(), getVehicle(), MSEdge::parseEdgesList(), and MSBaseVehicle::replaceRouteEdges().
Referenced by TraCIServerAPI_Vehicle::processSet().
setRouteID()
void Vehicle::setRouteID (const std::string & vehicleID, const std::string & routeID) static
Definition at line 970 of file Vehicle.cpp.
References MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSBaseVehicle::getID(), MSVehicle::getLane(), getVehicle(), MSBaseVehicle::hasValidRoute(), MSVehicle::replaceRoute(), and WRITE_WARNING.
Referenced by TraCIServerAPI_Vehicle::processSet().
setShapeClass()
void Vehicle::setShapeClass (const std::string & vehicleID, const std::string & clazz) static
Definition at line 1170 of file Vehicle.cpp.
References MSBaseVehicle::getSingularType(), getVehicle(), getVehicleShapeID(), and MSVehicleType::setShape().
setSignals()
void Vehicle::setSignals (const std::string & vehicleID, int signals) static
Definition at line 1071 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), getVehicle(), MSVehicle::Influencer::setSignals(), MSVehicle::switchOffSignal(), and MSVehicle::switchOnSignal().
Referenced by TraCIServerAPI_Vehicle::processSet().
setSpeed()
void Vehicle::setSpeed (const std::string & vehicleID, double speed) static
Definition at line 955 of file Vehicle.cpp.
References getVehicle(), and UNUSED_PARAMETER.
setStop()
void Vehicle::setStop (const std::string & vehicleID, const std::string & edgeID, double endPos = 1., int laneIndex = 0, SUMOTime duration = 4294967295u, int flags = STOP_DEFAULT, double startPos = INVALID_DOUBLE_VALUE, SUMOTime until = -1) static
Definition at line 630 of file Vehicle.cpp.
References MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSEdge::dictionary(), MSEdge::getLanes(), getVehicle(), SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_NOTHING, SUMO_TAG_PARKING_AREA, and toString().
Referenced by TraCIServerAPI_Vehicle::processSet().
setType()
void Vehicle::setType (const std::string & vehicleID, const std::string & typeID) static
Definition at line 961 of file Vehicle.cpp.
References MSNet::getInstance(), getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), and MSBaseVehicle::replaceVehicleType().
Referenced by TraCIServerAPI_Vehicle::processSet().
setVia()
void Vehicle::setVia (const std::string & vehicleID, const std::vector< std::string > & via) static
Definition at line 1164 of file Vehicle.cpp.
References getVehicle(), and UNUSED_PARAMETER.
slowDown()
void Vehicle::slowDown (const std::string & vehicleID, double speed, SUMOTime duration) static
Definition at line 946 of file Vehicle.cpp.
References MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getSpeed(), getVehicle(), and MSVehicle::Influencer::setSpeedTimeLine().
Referenced by TraCIServerAPI_Vehicle::processSet().
The documentation for this class was generated from the following files:
Vehicle.h
Vehicle.cpp