SUMO - Simulation of Urban MObility: MSPerson::Influencer Class Reference
MSPerson::Influencer Class Reference
Changes the wished person speed and position.
#include <MSPerson.h>
Public Member Functions
SUMOTime getLastAccessTimeStep () const
Influencer ()
Constructor.
bool isRemoteAffected (SUMOTime t) const
bool isRemoteControlled () const
void postProcessRemoteControl (MSPerson *p)
void setRemoteControlled (Position xyPos, MSLane *l, double pos, double posLat, double angle, int edgeOffset, const ConstMSEdgeVector &route, SUMOTime t)
~Influencer ()
Destructor.
Private Attributes
SUMOTime myLastRemoteAccess
double myRemoteAngle
int myRemoteEdgeOffset
MSLane * myRemoteLane
double myRemotePos
double myRemotePosLat
ConstMSEdgeVector myRemoteRoute
Position myRemoteXYPos
Detailed Description
Changes the wished person speed and position.
The class is used for passing velocities or positions obtained via TraCI to the person.
Definition at line 316 of file MSPerson.h.
Constructor & Destructor Documentation
Influencer()
MSPerson::Influencer::Influencer ()
Constructor.
Definition at line 532 of file MSPerson.cpp.
~Influencer()
MSPerson::Influencer::~Influencer ()
Destructor.
Definition at line 535 of file MSPerson.cpp.
Member Function Documentation
getLastAccessTimeStep()
SUMOTime MSPerson::Influencer::getLastAccessTimeStep () const inline
Definition at line 328 of file MSPerson.h.
isRemoteAffected()
bool MSPerson::Influencer::isRemoteAffected (SUMOTime t) const
Definition at line 558 of file MSPerson.cpp.
References TIME2STEPS.
isRemoteControlled()
bool MSPerson::Influencer::isRemoteControlled () const
Definition at line 552 of file MSPerson.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
postProcessRemoteControl()
void MSPerson::Influencer::postProcessRemoteControl (MSPerson * p)
Definition at line 564 of file MSPerson.cpp.
References MSTransportable::getCurrentStage(), MSNet::getInstance(), MSPerson::MSPersonStage_Walking::getPedestrianState(), MSTransportable::getStageType(), PedestrianState::moveToXY(), and MSTransportable::MOVING_WITHOUT_VEHICLE.
setRemoteControlled()
void MSPerson::Influencer::setRemoteControlled (Position xyPos, MSLane * l, double pos, double posLat, double angle, int edgeOffset, const ConstMSEdgeVector & route, SUMOTime t)
Definition at line 539 of file MSPerson.cpp.
Referenced by libsumo::Helper::setRemoteControlled().
Field Documentation
myLastRemoteAccess
SUMOTime MSPerson::Influencer::myLastRemoteAccess private
Definition at line 346 of file MSPerson.h.
myRemoteAngle
double MSPerson::Influencer::myRemoteAngle private
Definition at line 343 of file MSPerson.h.
myRemoteEdgeOffset
int MSPerson::Influencer::myRemoteEdgeOffset private
Definition at line 344 of file MSPerson.h.
myRemoteLane
MSLane* MSPerson::Influencer::myRemoteLane private
Definition at line 340 of file MSPerson.h.
myRemotePos
double MSPerson::Influencer::myRemotePos private
Definition at line 341 of file MSPerson.h.
myRemotePosLat
double MSPerson::Influencer::myRemotePosLat private
Definition at line 342 of file MSPerson.h.
myRemoteRoute
ConstMSEdgeVector MSPerson::Influencer::myRemoteRoute private
Definition at line 345 of file MSPerson.h.
myRemoteXYPos
Position MSPerson::Influencer::myRemoteXYPos private
Definition at line 339 of file MSPerson.h.
The documentation for this class was generated from the following files:
MSPerson.h
MSPerson.cpp