SUMO - Simulation of Urban MObility: MSPedestrianPushButton Class Reference
MSPedestrianPushButton Class Reference
#include <MSPushButton.h>
Public Member Functions
MSPedestrianPushButton (const MSEdge *walkingEdge, const MSEdge *crossingEdge)
virtual ~MSPedestrianPushButton ()
bool isActivated () const
abstract methods inherited from PedestrianState
Static Public Member Functions
static bool isActiveForEdge (const MSEdge *walkingEdge, const MSEdge *crossing)
Static method with the same behavior of isActivated.
static bool isActiveOnAnySideOfTheRoad (const MSEdge *crossing)
Static method to check if the push button is active on both side of the road.
static std::vector< MSPushButton * > loadPushButtons (const MSPhaseDefinition *)
Loads all the pushbuttons for all the controlled lanes of a stage.
Static Private Member Functions
static bool anyActive (const std::vector< MSPushButton *> &)
Checks if any pushbutton in the vector is active.
static void loadCrossingEdgeMap ()
Private Attributes
const MSEdge * m_crossingEdge
const MSEdge * m_edge
Static Private Attributes
static std::map< std::string, std::vector< std::string > > m_crossingEdgeMap
static bool m_crossingEdgeMapLoaded = false
Detailed Description
Pedestrian push button
Definition at line 62 of file MSPushButton.h.
Constructor & Destructor Documentation
MSPedestrianPushButton()
MSPedestrianPushButton::MSPedestrianPushButton (const MSEdge * walkingEdge, const MSEdge * crossingEdge)
MSPedestrianPushButton constructor
Parameters
[in] edge the edge where the push button is located. Must be a walking area.
[in] crossingEdge the crossing controlled by the push button. Must be a crossing.
Definition at line 50 of file MSPushButton.cpp.
References MSEdge::getPermissions(), MSEdge::isCrossing(), MSEdge::isWalkingArea(), and SVC_PEDESTRIAN.
Referenced by loadPushButtons().
~MSPedestrianPushButton()
virtual MSPedestrianPushButton::~MSPedestrianPushButton () inline virtual
Definition at line 70 of file MSPushButton.h.
References MSPushButton::isActivated().
Member Function Documentation
anyActive()
bool MSPushButton::anyActive (const std::vector< MSPushButton *> & pushButtons) static inherited
Checks if any pushbutton in the vector is active.
Returns
True if at least one pushbutton is active, false otherwise
Definition at line 38 of file MSPushButton.cpp.
References m_crossingEdgeMap, and m_crossingEdgeMapLoaded.
Referenced by MSSOTLTrafficLightLogic::isPushButtonPressed().
isActivated()
bool MSPedestrianPushButton::isActivated () const virtual
abstract methods inherited from PedestrianState
Implements MSPushButton.
Definition at line 56 of file MSPushButton.cpp.
References isActiveForEdge(), MSPushButton::m_crossingEdge, and MSPushButton::m_edge.
isActiveForEdge()
bool MSPedestrianPushButton::isActiveForEdge (const MSEdge * walkingEdge, const MSEdge * crossing) static
Static method with the same behavior of isActivated.
Checks if the the pushbutton has been pressed for a particular crossing from a edge.
Returns
true if pressed, false otherwise
TODO keep using >= 1 or switch to ==1. Should change return value from always active to active only when pressed? TODO If changed the swarm logic must be changed since it relies on this behavior that keeps it active
Definition at line 60 of file MSPushButton.cpp.
References DBG, Named::getID(), MSBaseVehicle::getID(), MSTransportable::getID(), MSEdge::getLanes(), MSPerson::getNextEdgePtr(), MSEdge::getPersons(), MSEdge::getPredecessors(), MSEdge::getSuccessors(), MSBaseVehicle::getVClass(), MSLane::getVehiclesSecure(), MSTransportable::getWaitingSeconds(), MSVehicle::getWaitingSeconds(), MSLane::releaseVehicles(), MSBaseVehicle::succEdge(), SVC_PEDESTRIAN, and WRITE_MESSAGE.
Referenced by isActivated(), and isActiveOnAnySideOfTheRoad().
isActiveOnAnySideOfTheRoad()
bool MSPedestrianPushButton::isActiveOnAnySideOfTheRoad (const MSEdge * crossing) static
Static method to check if the push button is active on both side of the road.
Parameters
[in] A crossing edge
Returns
true if pressed, false otherwise
Definition at line 139 of file MSPushButton.cpp.
References DBG, Named::getID(), getWalkingAreas(), isActiveForEdge(), and WRITE_MESSAGE.
loadCrossingEdgeMap()
void MSPedestrianPushButton::loadCrossingEdgeMap () static private
Definition at line 184 of file MSPushButton.cpp.
References MSEdge::getAllEdges(), MSEdge::getCrossingEdges(), Named::getID(), MSEdge::isCrossing(), m_crossingEdgeMap, and m_crossingEdgeMapLoaded.
Referenced by loadPushButtons().
loadPushButtons()
std::vector< MSPushButton * > MSPedestrianPushButton::loadPushButtons (const MSPhaseDefinition * phase) static
Loads all the pushbuttons for all the controlled lanes of a stage.
Parameters
[in] A phase definition
Returns
A list of pushbuttons
Definition at line 151 of file MSPushButton.cpp.
References DBG, MSLane::dictionary(), MSEdge::dictionary(), MSLane::getEdge(), Named::getID(), MSPhaseDefinition::getState(), MSPhaseDefinition::getTargetLaneSet(), getWalkingAreas(), loadCrossingEdgeMap(), m_crossingEdgeMap, MSPedestrianPushButton(), and WRITE_MESSAGE.
Referenced by MSSOTLTrafficLightLogic::isPushButtonPressed().
Field Documentation
m_crossingEdge
const MSEdge* MSPushButton::m_crossingEdge protected inherited
Definition at line 56 of file MSPushButton.h.
Referenced by isActivated(), and MSPushButton::MSPushButton().
m_crossingEdgeMap
std::map< std::string, std::vector< std::string > > MSPedestrianPushButton::m_crossingEdgeMap static private
Definition at line 100 of file MSPushButton.h.
Referenced by MSPushButton::anyActive(), loadCrossingEdgeMap(), and loadPushButtons().
m_crossingEdgeMapLoaded
bool MSPedestrianPushButton::m_crossingEdgeMapLoaded = false static private
Definition at line 101 of file MSPushButton.h.
Referenced by MSPushButton::anyActive(), and loadCrossingEdgeMap().
m_edge
const MSEdge* MSPushButton::m_edge protected inherited
Definition at line 55 of file MSPushButton.h.
Referenced by isActivated(), and MSPushButton::MSPushButton().
The documentation for this class was generated from the following files:
MSPushButton.h
MSPushButton.cpp