SUMO - Simulation of Urban MObility: Command Class Reference
Command Class Reference abstract
Base (microsim) event class.
#include <Command.h>
Public Member Functions
Command ()
Constructor.
virtual SUMOTime execute (SUMOTime currentTime)=0
Executes the command.
virtual ~Command ()
Destructor.
Detailed Description
Base (microsim) event class.
Classes derived from Command may be added to MSEventControl instances in order to be executed at a certain time step.
As soon as the simulation reaches the desired time step, the command (event) is executed by calling "execute" with the current time step. The method must return either 0, if the event shall not be executed again or a positive value (in simulation seconds) that described when it shall be executed again. The method must not return a value below zero, the behaviour is undefined in this case.
Warning
The EventControl the Command is added to gets responsible for this command's deletion.
See also
Design Patterns, Gamma et al.
WrappingCommand
MSEventControl
Definition at line 60 of file Command.h.
Constructor & Destructor Documentation
Command()
Command::Command () inline
Constructor.
Definition at line 63 of file Command.h.
~Command()
virtual Command::~Command () inline virtual
Destructor.
Definition at line 67 of file Command.h.
References execute().
Member Function Documentation
execute()
virtual SUMOTime Command::execute (SUMOTime currentTime) pure virtual
Executes the command.
The implementations should return 0 if the command shall not be repeated, or a value larger than 0 that describe the time after which the command shall be executed again. Values below 0 must not be returned.
Parameters
[in] currentTime The current simulation time
Returns
The time after which the command shall be executed again, 0 if this command shall be descheduled.
Exceptions
ProcessError Derived actions may throw this exception
Implemented in MSTLLogicControl::SwitchInitCommand, MSTrafficLightLogic::SwitchCommand, MSPModel_Striping::MovePedestrians, MSDevice_BTreceiver::BTreceiverUpdate, WrappingCommand< T >, WrappingCommand< MSDevice_Routing >, StaticCommand< T >, MSVTypeProbe, MSCalibrator::CalibratorCommand, Command_SaveTLSSwitches, MSLaneSpeedTrigger, Command_SaveTLSSwitchStates, MSCModel_NonInteracting::MoveToNextEdge, Command_SaveTLSState, MSPModel_NonInteracting::MoveToNextEdge, MSCalibrator, and METriggeredCalibrator.
Referenced by MSEventControl::execute(), and ~Command().
The documentation for this class was generated from the following file:
Command.h