SUMO - Simulation of Urban MObility: CHBuilder< E, V > Class Template Reference
CHBuilder< E, V > Class Template Reference
#include <CHBuilder.h>
Data Structures
class CHConnection
Forward/backward connection with associated FORWARD cost.
class CHInfo
class CHInfoComparator
class Connection
Forward/backward connection with associated forward/backward cost.
struct Hierarchy
struct Shortcut
Public Types
typedef std::pair< const E *, const E * > ConstEdgePair
typedef std::map< ConstEdgePair, const E * > ShortcutVia
Public Member Functions
const Hierarchy * buildContractionHierarchy (SUMOTime time, const V *const vehicle, const SUMOAbstractRouter< E, V > *effortProvider)
CHBuilder (const std::vector< E *> &edges, bool unbuildIsWarning, const SUMOVehicleClass svc, bool validatePermissions)
Constructor.
virtual ~CHBuilder ()
Destructor.
Private Types
typedef std::pair< const CHConnection *, const CHConnection * > CHConnectionPair
typedef std::vector< CHConnectionPair > CHConnectionPairs
typedef std::vector< CHConnection > CHConnections
Private Member Functions
void debugPrintQueue (std::vector< CHInfo *> &queue)
void disconnect (CHConnections &connections, CHInfo *other)
remove all connections to/from the given edge (assume it exists only once)
CHInfo * getCHInfo (const E *const edge)
CHBuilder & operator= (const CHBuilder &s)
Invalidated assignment operator.
void synchronize (CHInfo &info, double time, const V *const vehicle, const SUMOAbstractRouter< E, V > *effortProvider)
copy connections from the original net (modified destructively during contraction)
bool tryUpdateFront (std::vector< CHInfo *> &queue)
tries to update the priority of the first edge
Private Attributes
std::vector< CHInfo > myCHInfos
static vector for lookup
CHInfoComparator myCmp
Comparator for contraction priority.
const std::vector< E * > & myEdges
all edges with numerical ids
MsgHandler *const myErrorMsgHandler
the handler for routing errors
SPTree< CHInfo, CHConnection > * mySPTree
the shortest path tree to use when searching for shortcuts
const SUMOVehicleClass mySVC
the permissions for which the hierarchy was constructed
int myUpdateCount
counters for performance logging
Detailed Description
template<class E, class V>
class CHBuilder< E, V >
Definition at line 71 of file CHBuilder.h.
Member Typedef Documentation
CHConnectionPair
template<class E, class V> typedef std::pair<const CHConnection*, const CHConnection*> CHBuilder< E, V >::CHConnectionPair private
Definition at line 230 of file CHBuilder.h.
CHConnectionPairs
template<class E, class V> typedef std::vector<CHConnectionPair> CHBuilder< E, V >::CHConnectionPairs private
Definition at line 231 of file CHBuilder.h.
CHConnections
template<class E, class V> typedef std::vector<CHConnection> CHBuilder< E, V >::CHConnections private
Definition at line 229 of file CHBuilder.h.
ConstEdgePair
template<class E, class V> typedef std::pair<const E*, const E*> CHBuilder< E, V >::ConstEdgePair
Definition at line 85 of file CHBuilder.h.
ShortcutVia
template<class E, class V> typedef std::map<ConstEdgePair, const E*> CHBuilder< E, V >::ShortcutVia
Definition at line 86 of file CHBuilder.h.
Constructor & Destructor Documentation
CHBuilder()
template<class E, class V> CHBuilder< E, V >::CHBuilder (const std::vector< E *> & edges, bool unbuildIsWarning, const SUMOVehicleClass svc, bool validatePermissions) inline
Constructor.
Parameters
[in] validatePermissions Whether a multi-permission hierarchy shall be built If set to false, the net is pruned in synchronize() and the hierarchy is tailored to the svc
Definition at line 98 of file CHBuilder.h.
References CHBuilder< E, V >::myCHInfos.
~CHBuilder()
template<class E, class V> virtual CHBuilder< E, V >::~CHBuilder () inline virtual
Destructor.
Definition at line 112 of file CHBuilder.h.
References CHBuilder< E, V >::mySPTree.
Member Function Documentation
buildContractionHierarchy()
template<class E, class V> const Hierarchy* CHBuilder< E, V >::buildContractionHierarchy (SUMOTime time, const V *const vehicle, const SUMOAbstractRouter< E, V > * effortProvider) inline
Definition at line 117 of file CHBuilder.h.
References CHBuilder< E, V >::CHInfo::approaching, CHBuilder< E, V >::Hierarchy::backwardUplinks, CHBuilder< E, V >::Connection::Connection(), CHBuilder< E, V >::CHConnection::cost, CHBuilder< E, V >::disconnect(), CHBuilder< E, V >::CHInfo::edge, MsgHandler::endProcessMsg(), CHBuilder< E, V >::CHInfo::followers, CHBuilder< E, V >::Hierarchy::forwardUplinks, CHBuilder< E, V >::getCHInfo(), SysUtils::getCurrentMillis(), MsgHandler::getMessageInstance(), CHBuilder< E, V >::myCHInfos, CHBuilder< E, V >::myCmp, CHBuilder< E, V >::mySPTree, CHBuilder< E, V >::mySVC, CHBuilder< E, V >::myUpdateCount, CHBuilder< E, V >::CHConnection::permissions, CHBuilder< E, V >::CHInfo::permissions, CHBuilder< E, V >::CHInfo::priority, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, CHBuilder< E, V >::CHInfo::rank, CHBuilder< E, V >::Hierarchy::shortcuts, CHBuilder< E, V >::CHInfo::shortcuts, STEPS2TIME, SumoVehicleClassStrings, CHBuilder< E, V >::synchronize(), CHBuilder< E, V >::CHConnection::target, time2string(), toString(), CHBuilder< E, V >::tryUpdateFront(), CHBuilder< E, V >::CHInfo::updatePriority(), and WRITE_MESSAGE.
debugPrintQueue()
template<class E, class V> void CHBuilder< E, V >::debugPrintQueue (std::vector< CHInfo *> & queue) inline private
Definition at line 488 of file CHBuilder.h.
References CHBuilder< E, V >::CHInfo::edge, and CHBuilder< E, V >::CHInfo::priority.
Referenced by CHBuilder< E, V >::tryUpdateFront().
disconnect()
template<class E, class V> void CHBuilder< E, V >::disconnect (CHConnections & connections, CHInfo * other) inline private
remove all connections to/from the given edge (assume it exists only once)
Definition at line 458 of file CHBuilder.h.
Referenced by CHBuilder< E, V >::buildContractionHierarchy().
getCHInfo()
template<class E, class V> CHInfo* CHBuilder< E, V >::getCHInfo (const E *const edge) inline private
Definition at line 423 of file CHBuilder.h.
References CHBuilder< E, V >::myCHInfos.
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), and CHBuilder< E, V >::synchronize().
operator=()
template<class E, class V> CHBuilder& CHBuilder< E, V >::operator= (const CHBuilder< E, V > & s) private
Invalidated assignment operator.
synchronize()
template<class E, class V> void CHBuilder< E, V >::synchronize (CHInfo & info, double time, const V *const vehicle, const SUMOAbstractRouter< E, V > * effortProvider) inline private
copy connections from the original net (modified destructively during contraction)
Definition at line 429 of file CHBuilder.h.
References CHBuilder< E, V >::CHInfo::approaching, CHBuilder< E, V >::Connection::cost, CHBuilder< E, V >::CHInfo::edge, CHBuilder< E, V >::CHInfo::followers, CHBuilder< E, V >::getCHInfo(), SUMOAbstractRouter< E, V >::getEffort(), CHBuilder< E, V >::mySPTree, CHBuilder< E, V >::mySVC, and CHBuilder< E, V >::Connection::permissions.
Referenced by CHBuilder< E, V >::buildContractionHierarchy().
tryUpdateFront()
template<class E, class V> bool CHBuilder< E, V >::tryUpdateFront (std::vector< CHInfo *> & queue) inline private
tries to update the priority of the first edge
Returns
wether updating changed the first edge
Definition at line 471 of file CHBuilder.h.
References CHBuilder< E, V >::debugPrintQueue(), CHBuilder< E, V >::CHInfo::edge, CHBuilder< E, V >::myCmp, CHBuilder< E, V >::mySPTree, CHBuilder< E, V >::myUpdateCount, and CHBuilder< E, V >::CHInfo::updatePriority().
Referenced by CHBuilder< E, V >::buildContractionHierarchy().
Field Documentation
myCHInfos
template<class E, class V> std::vector<CHInfo> CHBuilder< E, V >::myCHInfos private
static vector for lookup
Definition at line 504 of file CHBuilder.h.
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), CHBuilder< E, V >::CHBuilder(), and CHBuilder< E, V >::getCHInfo().
myCmp
template<class E, class V> CHInfoComparator CHBuilder< E, V >::myCmp private
Comparator for contraction priority.
Definition at line 507 of file CHBuilder.h.
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), and CHBuilder< E, V >::tryUpdateFront().
myEdges
template<class E, class V> const std::vector<E*>& CHBuilder< E, V >::myEdges private
all edges with numerical ids
Definition at line 498 of file CHBuilder.h.
myErrorMsgHandler
template<class E, class V> MsgHandler* const CHBuilder< E, V >::myErrorMsgHandler private
the handler for routing errors
Definition at line 501 of file CHBuilder.h.
mySPTree
template<class E, class V> SPTree<CHInfo, CHConnection>* CHBuilder< E, V >::mySPTree private
the shortest path tree to use when searching for shortcuts
Definition at line 510 of file CHBuilder.h.
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), CHBuilder< E, V >::synchronize(), CHBuilder< E, V >::tryUpdateFront(), and CHBuilder< E, V >::~CHBuilder().
mySVC
template<class E, class V> const SUMOVehicleClass CHBuilder< E, V >::mySVC private
the permissions for which the hierarchy was constructed
Definition at line 513 of file CHBuilder.h.
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), and CHBuilder< E, V >::synchronize().
myUpdateCount
template<class E, class V> int CHBuilder< E, V >::myUpdateCount private
counters for performance logging
Definition at line 516 of file CHBuilder.h.
Referenced by CHBuilder< E, V >::buildContractionHierarchy(), and CHBuilder< E, V >::tryUpdateFront().
The documentation for this class was generated from the following file:
CHBuilder.h