SUMO - Simulation of Urban MObility: GUIUserIO Class Reference
GUIUserIO Class Reference
Some OS-dependant functions to ease cliboard manipulation.
#include <GUIUserIO.h>
Static Public Member Functions
static void copyToClipboard (const FXApp &app, const std::string &text)
Copies the given text to clipboard.
Static Public Attributes
static std::string clipped = ""
Detailed Description
Some OS-dependant functions to ease cliboard manipulation.
This helper contains only one function by now. It is used to store a text snipplet permanently within Windows-clipboard. This method is necessary, because FOX only implements the Linux/UNIX-text copying scheme where a marked text is copied. This does not work as soon as the widget with the marked text is destroyed or when the selection is lost. Because this scheme differs very much from the way the clipboard is handled in windows, is is implemented "from scratch" herein.
Definition at line 52 of file GUIUserIO.h.
Member Function Documentation
copyToClipboard()
void GUIUserIO::copyToClipboard (const FXApp & app, const std::string & text) static
Copies the given text to clipboard.
This method is only implemented for MS Windows.
Parameters
[in] app The application to use
[in] text The text to copy
Definition at line 44 of file GUIUserIO.cpp.
References clipped.
Referenced by GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), and GUIGLObjectPopupMenu::onCmdCopyTypedName().
Field Documentation
clipped
std::string GUIUserIO::clipped = "" static
Definition at line 63 of file GUIUserIO.h.
Referenced by copyToClipboard(), GNEApplicationWindow::onClipboardRequest(), and GUIApplicationWindow::onClipboardRequest().
The documentation for this class was generated from the following files:
GUIUserIO.h
GUIUserIO.cpp