SUMO - Simulation of Urban MObility: MSPhaseDefinition Class Reference
MSPhaseDefinition Class Reference
The definition of a single phase of a tls logic.
#include <MSPhaseDefinition.h>
Public Types
typedef std::vector< std::string > LaneIdVector
typedef std::bitset< 4 > PhaseType
Public Member Functions
LinkState getSignalState (int pos) const
Returns the state of the tls signal at the given position.
const std::string & getState () const
Returns the state within this phase.
const LaneIdVector & getTargetLaneSet () const throw ()
bool isCommit () const throw ()
bool isDecisional () const throw ()
bool isGreenPhase () const
Returns whether this phase is a pure "green" phase.
bool isTarget () const throw ()
bool isTransient () const throw ()
bool isUndefined () const throw ()
MSPhaseDefinition (SUMOTime durationArg, const std::string &stateArg)
Constructor.
MSPhaseDefinition (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string &stateArg) throw ()
Constructor In this phase the duration is constrained between min and max duration.
MSPhaseDefinition (SUMOTime durationArg, const std::string &stateArg, bool transient_notdecisional, bool commit, LaneIdVector &targetLaneSetArg) throw ()
MSPhaseDefinition (SUMOTime durationArg, const std::string &stateArg, bool transient_notdecisional, bool commit) throw ()
MSPhaseDefinition (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string &stateArg, bool transient_notdecisional, bool commit, LaneIdVector &targetLaneSetArg) throw ()
MSPhaseDefinition (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string &stateArg, bool transient_notdecisional, bool commit) throw ()
bool operator!= (const MSPhaseDefinition &pd)
Comparison operator.
virtual ~MSPhaseDefinition ()
Destructor.
Data Fields
SUMOTime duration
The duration of the phase.
SUMOTime lastDuration
The previous duration of the phase.
SUMOTime maxDuration
The maximum duration of the phase.
SUMOTime minDuration
The minimum duration of the phase.
SUMOTime myLastSwitch
Stores the timestep of the last on-switched of the phase.
Private Member Functions
void init (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string &stateArg)
void init (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string &stateArg, LaneIdVector &targetLaneSetArg)
Private Attributes
PhaseType phaseType
std::string state
The phase definition.
LaneIdVector targetLaneSet
Detailed Description
The definition of a single phase of a tls logic.
Definition at line 58 of file MSPhaseDefinition.h.
Member Typedef Documentation
LaneIdVector
typedef std::vector<std::string> MSPhaseDefinition::LaneIdVector
Definition at line 73 of file MSPhaseDefinition.h.
PhaseType
typedef std::bitset<4> MSPhaseDefinition::PhaseType
Definition at line 71 of file MSPhaseDefinition.h.
Constructor & Destructor Documentation
MSPhaseDefinition() [1/6]
MSPhaseDefinition::MSPhaseDefinition (SUMOTime durationArg, const std::string & stateArg) inline
Constructor.
minDuration and maxDuration are set to duration.
Parameters
[in] durationArg The duration of the phase
[in] stateArg The state in the phase
Definition at line 136 of file MSPhaseDefinition.h.
References COMMIT_BIT, init(), TARGET_BIT, TRANSIENT_NOTDECISIONAL_BIT, and UNDEFINED_BIT.
MSPhaseDefinition() [2/6]
MSPhaseDefinition::MSPhaseDefinition (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string & stateArg) throw () inline
Constructor In this phase the duration is constrained between min and max duration.
Parameters
[in] durationArg The duration of the phase
[in] minDurationArg The minimum duration of the phase
[in] maxDurationArg The maximum duration of the phase
[in] stateArg The state in the phase
Definition at line 154 of file MSPhaseDefinition.h.
References COMMIT_BIT, init(), TARGET_BIT, TRANSIENT_NOTDECISIONAL_BIT, and UNDEFINED_BIT.
MSPhaseDefinition() [3/6]
MSPhaseDefinition::MSPhaseDefinition (SUMOTime durationArg, const std::string & stateArg, bool transient_notdecisional, bool commit, LaneIdVector & targetLaneSetArg) throw () inline
Definition at line 172 of file MSPhaseDefinition.h.
References COMMIT_BIT, MsgHandler::getErrorInstance(), MsgHandler::inform(), init(), TARGET_BIT, TRANSIENT_NOTDECISIONAL_BIT, and UNDEFINED_BIT.
MSPhaseDefinition() [4/6]
MSPhaseDefinition::MSPhaseDefinition (SUMOTime durationArg, const std::string & stateArg, bool transient_notdecisional, bool commit) throw () inline
Definition at line 190 of file MSPhaseDefinition.h.
References COMMIT_BIT, init(), TARGET_BIT, TRANSIENT_NOTDECISIONAL_BIT, and UNDEFINED_BIT.
MSPhaseDefinition() [5/6]
MSPhaseDefinition::MSPhaseDefinition (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string & stateArg, bool transient_notdecisional, bool commit, LaneIdVector & targetLaneSetArg) throw () inline
Definition at line 208 of file MSPhaseDefinition.h.
References COMMIT_BIT, MsgHandler::getErrorInstance(), MsgHandler::inform(), init(), TARGET_BIT, TRANSIENT_NOTDECISIONAL_BIT, and UNDEFINED_BIT.
MSPhaseDefinition() [6/6]
MSPhaseDefinition::MSPhaseDefinition (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string & stateArg, bool transient_notdecisional, bool commit) throw () inline
Definition at line 228 of file MSPhaseDefinition.h.
References COMMIT_BIT, init(), TARGET_BIT, TRANSIENT_NOTDECISIONAL_BIT, and UNDEFINED_BIT.
~MSPhaseDefinition()
virtual MSPhaseDefinition::~MSPhaseDefinition () inline virtual
Destructor.
Definition at line 241 of file MSPhaseDefinition.h.
Member Function Documentation
getSignalState()
LinkState MSPhaseDefinition::getSignalState (int pos) const inline
Returns the state of the tls signal at the given position.
Parameters
[in] pos The position of the signal to return the state for
Returns
The state of the signal at the given position
Definition at line 277 of file MSPhaseDefinition.h.
getState()
const std::string& MSPhaseDefinition::getState () const inline
Returns the state within this phase.
Returns
The state in this phase
Definition at line 247 of file MSPhaseDefinition.h.
References state.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), GUITrafficLightLogicWrapper::drawGL(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSActuatedTrafficLightLogic::gapControl(), libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(), MSSwarmTrafficLightLogic::getLaneLightState(), libsumo::TrafficLight::getRedYellowGreenState(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSPedestrianPushButton::loadPushButtons(), TraCIServerAPI_TrafficLight::processGet(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSTrafficLightLogic::setTrafficLightSignals(), MSSOTLTrafficLightLogic::trySwitch(), and MSFullExport::writeTLS().
getTargetLaneSet()
const LaneIdVector& MSPhaseDefinition::getTargetLaneSet () const throw () inline
Definition at line 251 of file MSPhaseDefinition.h.
References targetLaneSet.
Referenced by MSSOTLTrafficLightLogic::countVehicles(), MSSwarmTrafficLightLogic::decideNextPhase(), and MSPedestrianPushButton::loadPushButtons().
init() [1/2]
void MSPhaseDefinition::init (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string & stateArg) inline private
Definition at line 110 of file MSPhaseDefinition.h.
References OptionsCont::getOptions(), and string2time().
Referenced by init(), and MSPhaseDefinition().
init() [2/2]
void MSPhaseDefinition::init (SUMOTime durationArg, SUMOTime minDurationArg, SUMOTime maxDurationArg, const std::string & stateArg, LaneIdVector & targetLaneSetArg) inline private
Definition at line 121 of file MSPhaseDefinition.h.
References init().
isCommit()
bool MSPhaseDefinition::isCommit () const throw () inline
Definition at line 324 of file MSPhaseDefinition.h.
References COMMIT_BIT.
Referenced by MSSOTLCongestionPolicy::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicy::decideNextPhase(), MSSOTLTrafficLightLogic::decideNextPhase(), and MSSwarmTrafficLightLogic::decideNextPhase().
isDecisional()
bool MSPhaseDefinition::isDecisional () const throw () inline
Definition at line 317 of file MSPhaseDefinition.h.
References TRANSIENT_NOTDECISIONAL_BIT.
Referenced by MSSOTLCongestionPolicy::decideNextPhase(), MSSOTLPolicy::decideNextPhase(), and MSSOTLTrafficLightLogic::decideNextPhase().
isGreenPhase()
bool MSPhaseDefinition::isGreenPhase () const inline
Returns whether this phase is a pure "green" phase.
"pure green" means in this case that at least one stream has green and no stream has yellow. Such phases are meant to be candidates for being stretched by actuated or agentbased traffic light logics.
Returns
Whether this phase is a "pure green" phase
Definition at line 262 of file MSPhaseDefinition.h.
Referenced by MSDelayBasedTrafficLightLogic::trySwitch().
isTarget()
bool MSPhaseDefinition::isTarget () const throw () inline
Definition at line 303 of file MSPhaseDefinition.h.
References TARGET_BIT.
Referenced by MSSOTLTrafficLightLogic::countVehicles(), MSSwarmTrafficLightLogic::decideNextPhase(), MSSOTLTrafficLightLogic::setToATargetPhase(), MSSOTLTrafficLightLogic::setupCTS(), and MSSOTLTrafficLightLogic::trySwitch().
isTransient()
bool MSPhaseDefinition::isTransient () const throw () inline
Definition at line 310 of file MSPhaseDefinition.h.
References TRANSIENT_NOTDECISIONAL_BIT.
Referenced by MSSOTLCongestionPolicy::decideNextPhase(), MSSOTLPolicy::decideNextPhase(), and MSSOTLTrafficLightLogic::decideNextPhase().
isUndefined()
bool MSPhaseDefinition::isUndefined () const throw () inline
Definition at line 296 of file MSPhaseDefinition.h.
References UNDEFINED_BIT.
Referenced by MSSOTLTrafficLightLogic::checkPhases().
operator!=()
bool MSPhaseDefinition::operator!= (const MSPhaseDefinition & pd) inline
Comparison operator.
Note that only the state must differ, not the duration!
Parameters
[in] pd The phase definition to compare against
Returns
Whether the given phase definition differs
Definition at line 288 of file MSPhaseDefinition.h.
References state.
Field Documentation
duration
SUMOTime MSPhaseDefinition::duration
The duration of the phase.
Definition at line 77 of file MSPhaseDefinition.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSSOTLMarchingPolicy::canRelease(), MSSOTLTrafficLightLogic::computeReturnTime(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(), MSPhasedTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSPhasedTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), libsumo::TrafficLight::getPhaseDuration(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSTrafficLightLogic::getSpentDuration(), MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), GUIViewTraffic::onGamingClick(), PushButtonLogic::pushButtonLogic(), libsumo::TrafficLight::setPhase(), SigmoidLogic::sigmoidLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and MSTLLogicControl::WAUTSwitchProcedure::switchToPos().
lastDuration
SUMOTime MSPhaseDefinition::lastDuration
The previous duration of the phase.
Definition at line 80 of file MSPhaseDefinition.h.
Referenced by MSSOTLWaveTrafficLightLogic::canRelease().
maxDuration
SUMOTime MSPhaseDefinition::maxDuration
The maximum duration of the phase.
Definition at line 86 of file MSPhaseDefinition.h.
Referenced by MSSOTLPlatoonPolicy::canRelease(), libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(), MSDelayBasedTrafficLightLogic::proposeProlongation(), and MSDelayBasedTrafficLightLogic::trySwitch().
minDuration
SUMOTime MSPhaseDefinition::minDuration
The minimum duration of the phase.
Definition at line 83 of file MSPhaseDefinition.h.
Referenced by MSSOTLPhasePolicy::canRelease(), MSSOTLMarchingPolicy::canRelease(), MSSOTLPlatoonPolicy::canRelease(), MSSOTLCongestionPolicy::canRelease(), MSActuatedTrafficLightLogic::duration(), libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(), MSDelayBasedTrafficLightLogic::trySwitch(), and MSActuatedTrafficLightLogic::trySwitch().
myLastSwitch
SUMOTime MSPhaseDefinition::myLastSwitch
Stores the timestep of the last on-switched of the phase.
Definition at line 89 of file MSPhaseDefinition.h.
Referenced by MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), MSPhasedTrafficLightLogic::getPhaseIndexAtTime(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSDelayBasedTrafficLightLogic::trySwitch(), and MSSOTLTrafficLightLogic::trySwitch().
phaseType
PhaseType MSPhaseDefinition::phaseType private
Definition at line 98 of file MSPhaseDefinition.h.
state
std::string MSPhaseDefinition::state private
The phase definition.
Definition at line 93 of file MSPhaseDefinition.h.
Referenced by getState(), and operator!=().
targetLaneSet
LaneIdVector MSPhaseDefinition::targetLaneSet private
Definition at line 108 of file MSPhaseDefinition.h.
Referenced by getTargetLaneSet().
The documentation for this class was generated from the following file:
MSPhaseDefinition.h