SUMO - Simulation of Urban MObility: Position Class Reference
Position Class Reference
A point in 2D or 3D with translation and scaling methods.
#include <Position.h>
Public Member Functions
void add (const Position &pos)
Adds the given position to this one.
void add (double dx, double dy)
Adds the given position to this one.
void add (double dx, double dy, double dz)
Adds the given position to this one.
bool almostSame (const Position &p2, double maxDiv=POSITION_EPS) const
checki if two position is almost the sme as other
double angleTo2D (const Position &other) const
returns the angle in the plane of the vector pointing from here to the other position
Position crossProduct (const Position &pos)
returns the cross product between this point and the second one
double distanceSquaredTo (const Position &p2) const
returns the square of the distance to another position
double distanceSquaredTo2D (const Position &p2) const
returns the square of the distance to another position (Only using x and y positions)
double distanceTo (const Position &p2) const
returns the euclidean distance in 3 dimension
double distanceTo2D (const Position &p2) const
returns the euclidean distance in the x-y-plane
double dotProduct (const Position &pos)
returns the dot product (scalar product) between this point and the second one
void mul (double val)
Multiplies both positions with the given value.
void mul (double mx, double my)
Multiplies position with the given values.
void mul (double mx, double my, double mz)
Multiplies position with the given values.
void norm2d ()
bool operator!= (const Position &p2) const
difference operator
Position operator* (double scalar) const
keep the direction but modify the length of the (location) vector to length * scalar
Position operator+ (const Position &p2) const
add operator
Position operator+ (double offset) const
keep the direction but modify the length of the (location) vector to length + scalar
Position operator- (const Position &p2) const
sub operator
bool operator< (const Position &p2) const
lexicographical sorting for use in maps and sets
bool operator== (const Position &p2) const
comparation operator
Position ()
default constructor
Position (double x, double y)
parametrised constructor
Position (double x, double y, double z)
parametrised constructor
void set (double x, double y)
set positions x and y
void set (double x, double y, double z)
set positions x, y and z
void set (const Position &pos)
set position with another position
void setx (double x)
set position x
void sety (double y)
set position y
void setz (double z)
set position z
void sub (double dx, double dy)
Substracts the given position from this one.
void sub (double dx, double dy, double dz)
Substracts the given position from this one.
void sub (const Position &pos)
Substracts the given position from this one.
double x () const
Returns the x-position.
double y () const
Returns the y-position.
double z () const
Returns the z-position.
~Position ()
Destructor.
Static Public Member Functions
static const Position & invalidPosition ()
reference to invalid position (needed if INVALID is taken by macro-definition)
Static Public Attributes
static const Position INVALID
used to indicate that a position is valid
Private Attributes
double myX
The x-position.
double myY
The y-position.
double myZ
The z-position.
Friends
std::ostream & operator<< (std::ostream &os, const Position &p)
output operator
Detailed Description
A point in 2D or 3D with translation and scaling methods.
Definition at line 45 of file Position.h.
Constructor & Destructor Documentation
Position() [1/3]
Position::Position () inline
default constructor
Definition at line 48 of file Position.h.
Referenced by crossProduct(), GUIPointOfInterest::drawGL(), GNEPOI::drawGL(), GNEPOILane::drawGL(), GNEPOILane::getPositionInView(), operator*(), operator+(), and operator-().
Position() [2/3]
Position::Position (double x, double y) inline
parametrised constructor
Definition at line 51 of file Position.h.
Position() [3/3]
Position::Position (double x, double y, double z) inline
parametrised constructor
Definition at line 55 of file Position.h.
~Position()
Position::~Position () inline
Destructor.
Definition at line 59 of file Position.h.
Member Function Documentation
add() [1/3]
void Position::add (const Position & pos) inline
Adds the given position to this one.
Definition at line 132 of file Position.h.
References myX, myY, and myZ.
Referenced by NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeNodeShapeDefault(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GUIEdge::drawGL(), GNEEdge::drawGL(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), GeoConvHelper::moveConvertedBy(), GNEDetectorE3::moveGeometry(), GNEPOI::moveGeometry(), GNEDetector::moveGeometry(), GNEPOILane::moveGeometry(), GNEStoppingPlace::moveGeometry(), GNEVariableSpeedSign::moveGeometry(), GNERerouter::moveGeometry(), GNEJunction::moveGeometry(), NBDistrict::reshiftPosition(), NBNode::reshiftPosition(), NBPTStop::reshiftPostion(), GUISUMOAbstractView::showToolTipFor(), and GeoConvHelper::x2cartesian_const().
add() [2/3]
void Position::add (double dx, double dy) inline
Adds the given position to this one.
Definition at line 139 of file Position.h.
References myX, and myY.
add() [3/3]
void Position::add (double dx, double dy, double dz) inline
Adds the given position to this one.
Definition at line 145 of file Position.h.
References myX, myY, and myZ.
almostSame()
bool Position::almostSame (const Position & p2, double maxDiv = POSITION_EPS) const inline
checki if two position is almost the sme as other
Definition at line 234 of file Position.h.
References distanceTo().
Referenced by GNEViewNet::begingMoveSelection(), PositionVector::insert_noDoublePos(), AGPosition::operator==(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
angleTo2D()
double Position::angleTo2D (const Position & other) const inline
returns the angle in the plane of the vector pointing from here to the other position
Definition at line 259 of file Position.h.
References myX, and myY.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), NBEdge::computeAngle(), GUIBusStop::drawGL(), GLHelper::drawTriangleAtEnd(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), PositionVector::rotationAtOffset(), and NWWriter_OpenDrive::writeGeomSmooth().
crossProduct()
Position Position::crossProduct (const Position & pos) inline
returns the cross product between this point and the second one
Definition at line 264 of file Position.h.
References myX, myY, myZ, and Position().
Referenced by NBHeightMapper::Triangle::normalVector().
distanceSquaredTo()
double Position::distanceSquaredTo (const Position & p2) const inline
returns the square of the distance to another position
Definition at line 244 of file Position.h.
References myX, myY, and myZ.
Referenced by distanceTo().
distanceSquaredTo2D()
double Position::distanceSquaredTo2D (const Position & p2) const inline
returns the square of the distance to another position (Only using x and y positions)
Definition at line 254 of file Position.h.
References myX, and myY.
Referenced by distanceTo2D(), and NBPTStopCont::getClosestPlatformToPTStopPosition().
distanceTo()
double Position::distanceTo (const Position & p2) const inline
returns the euclidean distance in 3 dimension
Definition at line 239 of file Position.h.
References distanceSquaredTo().
Referenced by almostSame(), GNEViewNet::begingMoveSelection(), TraCIServerAPI_Simulation::commandDistanceRequest(), NBHelpers::distance(), AGPosition::distanceTo(), GLHelper::drawBoxLines(), GLHelper::drawTriangleAtEnd(), PositionVector::extrapolate(), ROEdge::getLengthGeometryFactor(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), PositionVector::indexOfClosest(), NBEdge::init(), GUIE2Collector::MyWrapper::MyWrapper(), MSDevice_Bluelight::notifyMove(), GNEViewNet::onCmdTransformPOI(), GUIViewTraffic::onGamingClick(), operator+(), PositionVector::positionAtOffset(), NIVissimEdge::remapOneOfNodes(), PositionVector::rotationAtOffset(), GUIBaseVehicle::setFunctionalColor(), GNEStoppingPlace::setStoppingPlaceGeometry(), PositionVector::slopeDegreeAtOffset(), GUILane::splitAtSegments(), GNEDetectorE2::updateGeometry(), and MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility().
distanceTo2D()
double Position::distanceTo2D (const Position & p2) const inline
returns the euclidean distance in the x-y-plane
Definition at line 249 of file Position.h.
References distanceSquaredTo2D().
Referenced by NBNode::bezierControlPoints(), NBNode::buildWalkingAreas(), NGRandomNetBuilder::canConnect(), NBNode::checkCrossing(), GUIVehicle::computeSeats(), NIImporter_OpenDrive::computeShapes(), PositionVector::distance2D(), GUIVehicle::drawAction_drawRailCarriages(), GUIBusStop::drawGL(), PositionVector::extrapolate2D(), ROEdge::getDistanceTo(), MSEdge::getDistanceTo(), MSLink::getLeaderInfo(), PositionVector::getMaxGrade(), CState::getPosition(), GNEInternalLane::GNEInternalLane(), GUILane::GUILane(), MSVehicle::Influencer::implicitDeltaPosRemote(), MSVehicle::Influencer::implicitSpeedRemote(), MSPModel_Striping::initWalkingAreaPaths(), PositionVector::insertAtClosest(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::move2side(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), GeomHelper::nearest_offset_on_line_to_point2D(), PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), PositionVector::removeClosest(), GNEEdge::resetEndpoint(), GNEEdge::setEndpoint(), PositionVector::sideOffset(), PositionVector::simplified(), PositionVector::slopeDegreeAtOffset(), PositionVector::smoothedZFront(), PositionVector::transformToVectorCoordinates(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNELane::updateGeometry(), MSPerson::MSPersonStage_Walking::walkDistance(), NWWriter_OpenDrive::writeGeomLines(), and NWWriter_OpenDrive::writeGeomSmooth().
dotProduct()
double Position::dotProduct (const Position & pos) inline
returns the dot product (scalar product) between this point and the second one
Definition at line 272 of file Position.h.
References myX, myY, and myZ.
Referenced by NBHeightMapper::Triangle::getZ().
invalidPosition()
static const Position& Position::invalidPosition () inline static
reference to invalid position (needed if INVALID is taken by macro-definition)
Definition at line 280 of file Position.h.
References INVALID.
mul() [1/3]
void Position::mul (double val) inline
Multiplies both positions with the given value.
Definition at line 112 of file Position.h.
References myX, myY, and myZ.
Referenced by NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), GeoConvHelper::computeFinal(), NBNodeShapeComputer::computeNodeShapeDefault(), GUIEdge::drawGL(), GNEEdge::drawGL(), NBNode::getEmptyDir(), NBDistrict::mirrorX(), NBNode::mirrorX(), PCPolyContainer::saveDlrTDP(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
mul() [2/3]
void Position::mul (double mx, double my) inline
Multiplies position with the given values.
Definition at line 119 of file Position.h.
References myX, and myY.
mul() [3/3]
void Position::mul (double mx, double my, double mz) inline
Multiplies position with the given values.
Definition at line 125 of file Position.h.
References myX, myY, and myZ.
norm2d()
void Position::norm2d () inline
Definition at line 172 of file Position.h.
References myX, and myY.
Referenced by NBNode::getEmptyDir().
operator!=()
bool Position::operator!= (const Position & p2) const inline
difference operator
Definition at line 218 of file Position.h.
References myX, myY, and myZ.
operator*()
Position Position::operator* (double scalar) const inline
keep the direction but modify the length of the (location) vector to length * scalar
Definition at line 198 of file Position.h.
References myX, myY, myZ, and Position().
operator+() [1/2]
Position Position::operator+ (const Position & p2) const inline
add operator
Definition at line 188 of file Position.h.
References myX, myY, myZ, and Position().
operator+() [2/2]
Position Position::operator+ (double offset) const inline
keep the direction but modify the length of the (location) vector to length + scalar
Definition at line 203 of file Position.h.
References distanceTo(), myX, myY, myZ, and Position().
operator-()
Position Position::operator- (const Position & p2) const inline
sub operator
Definition at line 193 of file Position.h.
References myX, myY, myZ, and Position().
operator<()
bool Position::operator< (const Position & p2) const inline
lexicographical sorting for use in maps and sets
Definition at line 223 of file Position.h.
References myX, myY, and myZ.
operator==()
bool Position::operator== (const Position & p2) const inline
comparation operator
Definition at line 213 of file Position.h.
References myX, myY, and myZ.
set() [1/3]
void Position::set (double x, double y) inline
set positions x and y
Definition at line 92 of file Position.h.
References myX, myY, x(), and y().
Referenced by NIXMLNodesHandler::addNode(), ShapeHandler::addPOI(), NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeSmall(), GUISUMOAbstractView::destroyPopup(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUICompleteSchemeStorage::init(), NBHeightMapper::loadTiff(), libsumo::Helper::makePosition(), GUISettingsHandler::myStartElement(), NLJunctionControlBuilder::openJunction(), operator>>(), TraCIServerAPI_GUI::processSet(), GUICompleteSchemeStorage::saveViewport(), libsumo::POI::setPosition(), NGNode::setX(), NGNode::setY(), GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
set() [2/3]
void Position::set (double x, double y, double z) inline
set positions x, y and z
Definition at line 98 of file Position.h.
References myX, myY, myZ, x(), y(), and z().
set() [3/3]
void Position::set (const Position & pos) inline
set position with another position
Definition at line 105 of file Position.h.
References myX, myY, and myZ.
setx()
void Position::setx (double x) inline
set position x
Definition at line 77 of file Position.h.
References myX, and x().
Referenced by GNENet::joinSelectedJunctions(), GNEDetectorE3::setAttribute(), and GUISUMOAbstractView::snapToActiveGrid().
sety()
void Position::sety (double y) inline
set position y
Definition at line 82 of file Position.h.
References myY, and y().
Referenced by GNENet::joinSelectedJunctions(), GNEDetectorE3::setAttribute(), and GUISUMOAbstractView::snapToActiveGrid().
setz()
void Position::setz (double z) inline
set position z
Definition at line 87 of file Position.h.
References myZ, and z().
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), and NBEdge::startShapeAt().
sub() [1/3]
void Position::sub (double dx, double dy) inline
Substracts the given position from this one.
Definition at line 152 of file Position.h.
References myX, and myY.
Referenced by NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), AGPosition::compute2dPosition(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), and NBHeightMapper::Triangle::getZ().
sub() [2/3]
void Position::sub (double dx, double dy, double dz) inline
Substracts the given position from this one.
Definition at line 158 of file Position.h.
References myX, myY, and myZ.
sub() [3/3]
void Position::sub (const Position & pos) inline
Substracts the given position from this one.
Definition at line 165 of file Position.h.
References myX, myY, and myZ.
x()
double Position::x () const inline
Returns the x-position.
Definition at line 62 of file Position.h.
References myX.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), GNEDetectorE3::commitGeometryMoving(), NBPTStopCont::computeCrossProductEdgePosition(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), Boundary::distanceTo2D(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GUISUMOAbstractView::drawDecals(), GLHelper::drawFilledPoly(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEPoly::drawGL(), GNEEdge::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEShape::drawLockIcon(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextAtEnd(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), NBPTStopCont::findAccessEdgesForRailStops(), GeomHelper::findLineCircleIntersections(), GNEDetectorE3::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), PositionVector::getPolygonCenter(), libsumo::Person::getPosition(), libsumo::POI::getPosition(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), GNEPOILane::getPositionInView(), MSVTKExport::getPositions(), libsumo::InductionLoop::getTree(), GUIDanielPerspectiveChanger::getXPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), NBNodeCont::insert(), PositionVector::intersects(), PositionVector::isLeft(), GNENet::joinSelectedJunctions(), NBHeightMapper::loadTiff(), libsumo::Helper::makeTraCIPosition(), MSPModel_Striping::moveInDirection(), MSParkingArea::MSParkingArea(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE2Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), PCPolyContainer::saveDlrTDP(), set(), GUIBaseVehicle::setFunctionalColor(), GNEStoppingPlace::setStoppingPlaceGeometry(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), setx(), NGNode::setY(), PositionVector::sideOffset(), PositionVector::simplified(), GUISUMOAbstractView::snapToActiveGrid(), NBNetBuilder::transformCoordinate(), GNEAdditional::updateChildConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEDetectorE2::updateGeometry(), GNELane::updateGeometry(), GNEJunction::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), GNEDetectorE3::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
y()
double Position::y () const inline
Returns the y-position.
Definition at line 67 of file Position.h.
References myY.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), GNEDetectorE3::commitGeometryMoving(), NBPTStopCont::computeCrossProductEdgePosition(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), Boundary::distanceTo2D(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GUISUMOAbstractView::drawDecals(), GLHelper::drawFilledPoly(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEPoly::drawGL(), GNEEdge::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEShape::drawLockIcon(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextAtEnd(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), NBPTStopCont::findAccessEdgesForRailStops(), GeomHelper::findLineCircleIntersections(), GNEDetectorE3::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), libsumo::Person::getPosition(), libsumo::POI::getPosition(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), GNEPOILane::getPositionInView(), MSVTKExport::getPositions(), libsumo::InductionLoop::getTree(), GUIDanielPerspectiveChanger::getYPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), NBNodeCont::insert(), PositionVector::intersects(), PositionVector::isLeft(), GNENet::joinSelectedJunctions(), NBHeightMapper::loadTiff(), libsumo::Helper::makeTraCIPosition(), MSPModel_Striping::moveInDirection(), MSParkingArea::MSParkingArea(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE2Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), PCPolyContainer::saveDlrTDP(), set(), GUIBaseVehicle::setFunctionalColor(), GNEStoppingPlace::setStoppingPlaceGeometry(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setX(), sety(), PositionVector::sideOffset(), PositionVector::simplified(), GUISUMOAbstractView::snapToActiveGrid(), NBNetBuilder::transformCoordinate(), GNEAdditional::updateChildConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEDetectorE2::updateGeometry(), GNELane::updateGeometry(), GNEJunction::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), GNEDetectorE3::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
z()
double Position::z () const inline
Returns the z-position.
Definition at line 72 of file Position.h.
References myZ.
Referenced by Boundary::add(), PositionVector::add(), GUISettingsHandler::applyViewport(), Boundary::around(), bezier(), NBNode::bezierControlPoints(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBEdge::cutAtIntersection(), MSVTypeProbe::execute(), GUIJunctionWrapper::getColorValue(), GNEJunction::getColorValue(), PositionVector::getMaxGrade(), PositionVector::getOverlapWith(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), libsumo::POI::getPosition(), libsumo::Person::getPosition(), MSVTKExport::getPositions(), libsumo::Helper::makeTraCIPosition(), PositionVector::move2side(), GUISettingsHandler::myStartElement(), GNENet::registerJunction(), set(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), setz(), PositionVector::slopeDegreeAtOffset(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), NBEdge::startShapeAt(), GNEEdge::straightenElevation(), MSFCDExport::write(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), and MSFCDExport::writeTransportable().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Position & p) friend
output operator
Definition at line 179 of file Position.h.
Field Documentation
INVALID
const Position Position::INVALID static
used to indicate that a position is valid
Definition at line 277 of file Position.h.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), NLShapeHandler::getLanePos(), PCLoaderXML::getLanePos(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), MSPModel_Striping::PState::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSVehicle::getPosition(), MSVehicle::getPositionAlongBestLanes(), MSParkingArea::getVehiclePosition(), PositionVector::intersectionPosition2D(), invalidPosition(), PositionVector::move2side(), MSPModel_Striping::moveInDirection(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), PositionVector::positionAtOffset(), PositionVector::positionAtOffset2D(), MSPerson::MSPersonStage_Driving::proceed(), GUISUMOAbstractView::showViewportEditor(), MSLaneChangerSublane::startChangeSublane(), PositionVector::transformToVectorCoordinates(), MSVehicle::updateState(), and MSVehicle::validatePosition().
myX
double Position::myX private
The x-position.
Definition at line 286 of file Position.h.
Referenced by add(), angleTo2D(), crossProduct(), distanceSquaredTo(), distanceSquaredTo2D(), dotProduct(), mul(), norm2d(), operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), set(), setx(), sub(), and x().
myY
double Position::myY private
The y-position.
Definition at line 289 of file Position.h.
Referenced by add(), angleTo2D(), crossProduct(), distanceSquaredTo(), distanceSquaredTo2D(), dotProduct(), mul(), norm2d(), operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), set(), sety(), sub(), and y().
myZ
double Position::myZ private
The z-position.
Definition at line 292 of file Position.h.
Referenced by add(), crossProduct(), distanceSquaredTo(), dotProduct(), mul(), operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), set(), setz(), sub(), and z().
The documentation for this class was generated from the following files:
Position.h
Position.cpp