SUMO - Simulation of Urban MObility: NIVissimConnectionCluster::NodeSubCluster Class Reference
NIVissimConnectionCluster::NodeSubCluster Class Reference
Public Types
typedef std::vector< NIVissimConnection * > ConnectionCont
Public Member Functions
void add (NIVissimConnection *c)
void add (const NodeSubCluster &c)
std::vector< int > getConnectionIDs () const
NodeSubCluster (NIVissimConnection *c)
bool overlapsWith (const NodeSubCluster &c, double offset=0)
int size () const
~NodeSubCluster ()
Data Fields
Boundary myBoundary
ConnectionCont myConnections
Friends
class NIVissimConnectionCluster
Detailed Description
Definition at line 114 of file NIVissimConnectionCluster.h.
Member Typedef Documentation
ConnectionCont
typedef std::vector<NIVissimConnection*> NIVissimConnectionCluster::NodeSubCluster::ConnectionCont
Definition at line 126 of file NIVissimConnectionCluster.h.
Constructor & Destructor Documentation
NodeSubCluster()
NIVissimConnectionCluster::NodeSubCluster::NodeSubCluster (NIVissimConnection * c)
Definition at line 65 of file NIVissimConnectionCluster.cpp.
References add().
~NodeSubCluster()
NIVissimConnectionCluster::NodeSubCluster::~NodeSubCluster ()
Definition at line 70 of file NIVissimConnectionCluster.cpp.
Member Function Documentation
add() [1/2]
void NIVissimConnectionCluster::NodeSubCluster::add (NIVissimConnection * c)
Definition at line 74 of file NIVissimConnectionCluster.cpp.
References Boundary::add(), NIVissimConnection::getBoundingBox(), myBoundary, and myConnections.
Referenced by add(), NodeSubCluster(), and NIVissimConnectionCluster::same_direction_sorter::operator()().
add() [2/2]
void NIVissimConnectionCluster::NodeSubCluster::add (const NodeSubCluster & c)
Definition at line 81 of file NIVissimConnectionCluster.cpp.
References add(), and myConnections.
getConnectionIDs()
std::vector< int > NIVissimConnectionCluster::NodeSubCluster::getConnectionIDs () const
Definition at line 95 of file NIVissimConnectionCluster.cpp.
References NIVissimConnectionCluster::getNextFreeNodeID(), and myConnections.
overlapsWith()
bool NIVissimConnectionCluster::NodeSubCluster::overlapsWith (const NodeSubCluster & c, double offset = 0)
Definition at line 107 of file NIVissimConnectionCluster.cpp.
References myBoundary, Boundary::overlapsWith(), Boundary::xmax(), and Boundary::xmin().
size()
int NIVissimConnectionCluster::NodeSubCluster::size () const
Definition at line 89 of file NIVissimConnectionCluster.cpp.
References myConnections.
Friends And Related Function Documentation
NIVissimConnectionCluster
friend class NIVissimConnectionCluster friend
Definition at line 123 of file NIVissimConnectionCluster.h.
Field Documentation
myBoundary
Boundary NIVissimConnectionCluster::NodeSubCluster::myBoundary
Definition at line 125 of file NIVissimConnectionCluster.h.
Referenced by add(), and overlapsWith().
myConnections
ConnectionCont NIVissimConnectionCluster::NodeSubCluster::myConnections
Definition at line 127 of file NIVissimConnectionCluster.h.
Referenced by add(), getConnectionIDs(), NIVissimConnectionCluster::removeConnections(), and size().
The documentation for this class was generated from the following files:
NIVissimConnectionCluster.h
NIVissimConnectionCluster.cpp