SUMO - Simulation of Urban MObility: GNECalibratorDialog Class Reference
GNECalibratorDialog Class Reference
Dialog for edit calibrators.
#include <GNECalibratorDialog.h>
Public Member Functions
GNECalibrator * getEditedCalibrator () const
get edited calibrator
GNECalibratorDialog (GNECalibrator *editedCalibrator)
FOX-declaration.
~GNECalibratorDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdAddRoute (FXObject *, FXSelector, void *)
add new route
long onCmdClickedRoute (FXObject *, FXSelector, void *)
remove or edit route
long onCmdAddFlow (FXObject *, FXSelector, void *)
add new flow
long onCmdClickedFlow (FXObject *, FXSelector, void *)
remove or edit flow
long onCmdAddVehicleType (FXObject *, FXSelector, void *)
add new vehicle type
long onCmdClickedVehicleType (FXObject *, FXSelector, void *)
remove or edit vehicle type
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNECalibratorDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
Protected Attributes
FXVerticalFrame * myContentFrame
frame for contents
Private Member Functions
GNECalibratorDialog (const GNECalibratorDialog &)=delete
Invalidated copy constructor.
GNECalibratorDialog & operator= (const GNECalibratorDialog &)=delete
Invalidated assignment operator.
void updateFlowAndLabelButton ()
update flow and label button
void updateFlowTable ()
update data table with flows
void updateRouteTable ()
update data table with routes
void updateVehicleTypeTable ()
update data table with vehicle types
Private Attributes
FXButton * myAddFlow
button for add new flow
FXButton * myAddRoute
button for add new route
FXButton * myAddVehicleType
button for add new vehicle type
GNECalibrator * myEditedCalibrator
pointer to edited calibrator
FXTable * myFlowList
list with flows
FXLabel * myLabelFlow
label for flows
FXTable * myRouteList
list with routes
FXTable * myVehicleTypeList
list with vehicle types
Detailed Description
Dialog for edit calibrators.
Definition at line 52 of file GNECalibratorDialog.h.
Constructor & Destructor Documentation
GNECalibratorDialog() [1/3]
GNECalibratorDialog::GNECalibratorDialog (GNECalibrator * editedCalibrator)
FOX-declaration.
Constructor
Definition at line 70 of file GNECalibratorDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelThick, GUIDesignTableAdditionals, GUIDesignUniformHorizontalFrame, ICON_ADD, MID_GNE_CALIBRATORDIALOG_ADD_FLOW, MID_GNE_CALIBRATORDIALOG_ADD_ROUTE, MID_GNE_CALIBRATORDIALOG_ADD_VEHICLETYPE, MID_GNE_CALIBRATORDIALOG_TABLE_FLOW, MID_GNE_CALIBRATORDIALOG_TABLE_ROUTE, MID_GNE_CALIBRATORDIALOG_TABLE_VEHICLETYPE, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_VTYPE, and toString().
~GNECalibratorDialog()
GNECalibratorDialog::~GNECalibratorDialog ()
destructor
Definition at line 125 of file GNECalibratorDialog.cpp.
GNECalibratorDialog() [2/3]
GNECalibratorDialog::GNECalibratorDialog () inline protected
FOX needs this.
Definition at line 98 of file GNECalibratorDialog.h.
GNECalibratorDialog() [3/3]
GNECalibratorDialog::GNECalibratorDialog (const GNECalibratorDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterDialog::onCmdAccept(), onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), GNERerouterDialog::onCmdCancel(), onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
getEditedCalibrator()
GNECalibrator * GNECalibratorDialog::getEditedCalibrator () const
get edited calibrator
Definition at line 129 of file GNECalibratorDialog.cpp.
References myEditedCalibrator.
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNECalibratorDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 135 of file GNECalibratorDialog.cpp.
References GNEAdditionalDialog::acceptChanges().
onCmdAddFlow()
long GNECalibratorDialog::onCmdAddFlow (FXObject * , FXSelector , void *)
add new flow
Definition at line 245 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorRoutes(), GNECalibrator::getCalibratorVehicleTypes(), myEditedCalibrator, and updateFlowTable().
onCmdAddRoute()
long GNECalibratorDialog::onCmdAddRoute (FXObject * , FXSelector , void *)
add new route
Definition at line 167 of file GNECalibratorDialog.cpp.
References updateRouteTable().
onCmdAddVehicleType()
long GNECalibratorDialog::onCmdAddVehicleType (FXObject * , FXSelector , void *)
add new vehicle type
Definition at line 283 of file GNECalibratorDialog.cpp.
References updateVehicleTypeTable().
onCmdCancel()
long GNECalibratorDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 145 of file GNECalibratorDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdClickedFlow()
long GNECalibratorDialog::onCmdClickedFlow (FXObject * , FXSelector , void *)
remove or edit flow
Definition at line 260 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedCalibrator, myFlowList, and updateFlowTable().
onCmdClickedRoute()
long GNECalibratorDialog::onCmdClickedRoute (FXObject * , FXSelector , void *)
remove or edit route
Definition at line 177 of file GNECalibratorDialog.cpp.
References OptionsCont::getBool(), GNECalibrator::getCalibratorFlows(), GNECalibrator::getCalibratorRoutes(), OptionsCont::getOptions(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedCalibrator, myRouteList, SUMO_ATTR_ROUTE, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, toString(), updateFlowTable(), updateRouteTable(), and WRITE_WARNING.
onCmdClickedVehicleType()
long GNECalibratorDialog::onCmdClickedVehicleType (FXObject * , FXSelector , void *)
remove or edit vehicle type
Definition at line 293 of file GNECalibratorDialog.cpp.
References OptionsCont::getBool(), GNECalibrator::getCalibratorFlows(), GNECalibrator::getCalibratorVehicleTypes(), OptionsCont::getOptions(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedCalibrator, myRouteList, myVehicleTypeList, SUMO_ATTR_TYPE, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, toString(), updateFlowTable(), updateVehicleTypeTable(), and WRITE_WARNING.
onCmdReset()
long GNECalibratorDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 155 of file GNECalibratorDialog.cpp.
References GNEAdditionalDialog::resetChanges(), updateFlowTable(), updateRouteTable(), and updateVehicleTypeTable().
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNECalibratorDialog& GNECalibratorDialog::operator= (const GNECalibratorDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), GNERerouterDialog::onCmdReset(), onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
updateFlowAndLabelButton()
void GNECalibratorDialog::updateFlowAndLabelButton () private
update flow and label button
Definition at line 477 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorRoutes(), GNECalibrator::getCalibratorVehicleTypes(), myAddFlow, myEditedCalibrator, myFlowList, myLabelFlow, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_VTYPE, and toString().
Referenced by updateFlowTable(), updateRouteTable(), and updateVehicleTypeTable().
updateFlowTable()
void GNECalibratorDialog::updateFlowTable () private
update data table with flows
Definition at line 395 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorFlows(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myEditedCalibrator, myFlowList, SUMO_ATTR_ID, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VCLASS, toString(), and updateFlowAndLabelButton().
Referenced by onCmdAddFlow(), onCmdClickedFlow(), onCmdClickedRoute(), onCmdClickedVehicleType(), and onCmdReset().
updateRouteTable()
void GNECalibratorDialog::updateRouteTable () private
update data table with routes
Definition at line 356 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorRoutes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myEditedCalibrator, myRouteList, SUMO_ATTR_EDGES, SUMO_ATTR_ID, toString(), and updateFlowAndLabelButton().
Referenced by onCmdAddRoute(), onCmdClickedRoute(), and onCmdReset().
updateVehicleTypeTable()
void GNECalibratorDialog::updateVehicleTypeTable () private
update data table with vehicle types
Definition at line 439 of file GNECalibratorDialog.cpp.
References GNECalibrator::getCalibratorVehicleTypes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_REMOVE, myEditedCalibrator, myVehicleTypeList, SUMO_ATTR_ID, SUMO_ATTR_VCLASS, toString(), and updateFlowAndLabelButton().
Referenced by onCmdAddVehicleType(), onCmdClickedVehicleType(), and onCmdReset().
Field Documentation
myAddFlow
FXButton* GNECalibratorDialog::myAddFlow private
button for add new flow
Definition at line 114 of file GNECalibratorDialog.h.
Referenced by updateFlowAndLabelButton().
myAddRoute
FXButton* GNECalibratorDialog::myAddRoute private
button for add new route
Definition at line 105 of file GNECalibratorDialog.h.
myAddVehicleType
FXButton* GNECalibratorDialog::myAddVehicleType private
button for add new vehicle type
Definition at line 120 of file GNECalibratorDialog.h.
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myEditedCalibrator
GNECalibrator* GNECalibratorDialog::myEditedCalibrator private
pointer to edited calibrator
Definition at line 102 of file GNECalibratorDialog.h.
Referenced by getEditedCalibrator(), onCmdAddFlow(), onCmdClickedFlow(), onCmdClickedRoute(), onCmdClickedVehicleType(), updateFlowAndLabelButton(), updateFlowTable(), updateRouteTable(), and updateVehicleTypeTable().
myFlowList
FXTable* GNECalibratorDialog::myFlowList private
list with flows
Definition at line 117 of file GNECalibratorDialog.h.
Referenced by onCmdClickedFlow(), updateFlowAndLabelButton(), and updateFlowTable().
myLabelFlow
FXLabel* GNECalibratorDialog::myLabelFlow private
label for flows
Definition at line 111 of file GNECalibratorDialog.h.
Referenced by updateFlowAndLabelButton().
myRouteList
FXTable* GNECalibratorDialog::myRouteList private
list with routes
Definition at line 108 of file GNECalibratorDialog.h.
Referenced by onCmdClickedRoute(), onCmdClickedVehicleType(), and updateRouteTable().
myVehicleTypeList
FXTable* GNECalibratorDialog::myVehicleTypeList private
list with vehicle types
Definition at line 123 of file GNECalibratorDialog.h.
Referenced by onCmdClickedVehicleType(), and updateVehicleTypeTable().
The documentation for this class was generated from the following files:
GNECalibratorDialog.h
GNECalibratorDialog.cpp