SUMO - Simulation of Urban MObility: RODFDetectorFlows Class Reference
RODFDetectorFlows Class Reference
A container for flows.
#include <RODFDetectorFlow.h>
Public Member Functions
void addFlow (const std::string &detector_id, SUMOTime timestamp, const FlowDef &fd)
const std::vector< FlowDef > & getFlowDefs (const std::string &id) const
double getFlowSumSecure (const std::string &id) const
double getMaxDetectorFlow () const
bool knows (const std::string &det_id) const
void mesoJoin (const std::string &nid, const std::vector< std::string > &oldids)
void printAbsolute () const
void removeFlow (const std::string &detector_id)
RODFDetectorFlows (SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
void setFlows (const std::string &detector_id, std::vector< FlowDef > &)
~RODFDetectorFlows ()
Protected Attributes
SUMOTime myBeginTime
SUMOTime myEndTime
std::map< std::string, std::vector< FlowDef > > myFastAccessFlows
double myMaxDetectorFlow
SUMOTime myStepOffset
Private Member Functions
RODFDetectorFlows & operator= (const RODFDetectorFlows &src)
Invalidated assignment operator.
RODFDetectorFlows (const RODFDetectorFlows &src)
Invalidated copy constructor.
Detailed Description
A container for flows.
Definition at line 74 of file RODFDetectorFlow.h.
Constructor & Destructor Documentation
RODFDetectorFlows() [1/2]
RODFDetectorFlows::RODFDetectorFlows (SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 41 of file RODFDetectorFlow.cpp.
~RODFDetectorFlows()
RODFDetectorFlows::~RODFDetectorFlows ()
Definition at line 47 of file RODFDetectorFlow.cpp.
RODFDetectorFlows() [2/2]
RODFDetectorFlows::RODFDetectorFlows (const RODFDetectorFlows & src) private
Invalidated copy constructor.
Member Function Documentation
addFlow()
void RODFDetectorFlows::addFlow (const std::string & detector_id, SUMOTime timestamp, const FlowDef & fd)
!! mean value?
!! mean value?
Definition at line 51 of file RODFDetectorFlow.cpp.
References fd, FlowDef::firstSet, FlowDef::fLKW, FlowDef::isLKW, myBeginTime, myEndTime, myFastAccessFlows, myStepOffset, FlowDef::qLKW, FlowDef::qPKW, FlowDef::vLKW, and FlowDef::vPKW.
Referenced by mesoJoin(), and RODFDetFlowLoader::read().
getFlowDefs()
const std::vector< FlowDef > & RODFDetectorFlows::getFlowDefs (const std::string & id) const
Definition at line 118 of file RODFDetectorFlow.cpp.
References myFastAccessFlows.
Referenced by RODFNet::buildEdgeFlowMap(), getFlowSumSecure(), RODFNet::revalidateFlows(), RODFDetector::writeEmitterDefinition(), and RODFDetector::writeSingleSpeedTrigger().
getFlowSumSecure()
double RODFDetectorFlows::getFlowSumSecure (const std::string & id) const
Definition at line 126 of file RODFDetectorFlow.cpp.
References getFlowDefs(), and knows().
Referenced by RODFDetectorCon::writeEmitterPOIs().
getMaxDetectorFlow()
double RODFDetectorFlows::getMaxDetectorFlow () const
Definition at line 140 of file RODFDetectorFlow.cpp.
References myFastAccessFlows, and myMaxDetectorFlow.
Referenced by RODFDetectorCon::writeEmitterPOIs().
knows()
bool RODFDetectorFlows::knows (const std::string & det_id) const
Definition at line 112 of file RODFDetectorFlow.cpp.
References myFastAccessFlows.
Referenced by RODFNet::buildEdgeFlowMap(), getFlowSumSecure(), RODFDetectorCon::guessEmptyFlows(), mesoJoin(), RODFNet::removeEmptyDetectors(), RODFNet::reportEmptyDetectors(), RODFNet::revalidateFlows(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
mesoJoin()
void RODFDetectorFlows::mesoJoin (const std::string & nid, const std::vector< std::string > & oldids)
Definition at line 162 of file RODFDetectorFlow.cpp.
References addFlow(), knows(), myBeginTime, myEndTime, myFastAccessFlows, and myStepOffset.
Referenced by RODFNet::mesoJoin().
operator=()
RODFDetectorFlows& RODFDetectorFlows::operator= (const RODFDetectorFlows & src) private
Invalidated assignment operator.
printAbsolute()
void RODFDetectorFlows::printAbsolute () const
Definition at line 179 of file RODFDetectorFlow.cpp.
References myFastAccessFlows.
Referenced by startComputation().
removeFlow()
void RODFDetectorFlows::removeFlow (const std::string & detector_id)
Definition at line 106 of file RODFDetectorFlow.cpp.
References myFastAccessFlows.
Referenced by RODFNet::removeEmptyDetectors().
setFlows()
void RODFDetectorFlows::setFlows (const std::string & detector_id, std::vector< FlowDef > & flows)
Definition at line 91 of file RODFDetectorFlow.cpp.
References FlowDef::fLKW, myFastAccessFlows, FlowDef::qLKW, and FlowDef::qPKW.
Referenced by RODFNet::revalidateFlows().
Field Documentation
myBeginTime
SUMOTime RODFDetectorFlows::myBeginTime protected
Definition at line 94 of file RODFDetectorFlow.h.
Referenced by addFlow(), and mesoJoin().
myEndTime
SUMOTime RODFDetectorFlows::myEndTime protected
Definition at line 94 of file RODFDetectorFlow.h.
Referenced by addFlow(), and mesoJoin().
myFastAccessFlows
std::map<std::string, std::vector<FlowDef> > RODFDetectorFlows::myFastAccessFlows protected
Definition at line 93 of file RODFDetectorFlow.h.
Referenced by addFlow(), getFlowDefs(), getMaxDetectorFlow(), knows(), mesoJoin(), printAbsolute(), removeFlow(), and setFlows().
myMaxDetectorFlow
double RODFDetectorFlows::myMaxDetectorFlow mutable protected
Definition at line 95 of file RODFDetectorFlow.h.
Referenced by getMaxDetectorFlow().
myStepOffset
SUMOTime RODFDetectorFlows::myStepOffset protected
Definition at line 94 of file RODFDetectorFlow.h.
Referenced by addFlow(), and mesoJoin().
The documentation for this class was generated from the following files:
RODFDetectorFlow.h
RODFDetectorFlow.cpp