SUMO - Simulation of Urban MObility: IntermodalRouter< E, L, N, V, INTERNALROUTER > Class Template Reference
IntermodalRouter< E, L, N, V, INTERNALROUTER > Class Template Reference
#include <IntermodalRouter.h>
Data Structures
struct TripItem
Public Types
enum ModeChangeOptions { PARKING_AREAS = 1, PT_STOPS = 2, ALL_JUNCTIONS = 4 }
where mode changes are possible
typedef double(* Operation) (const E *const, const IntermodalTrip< E, N, V > *const, double)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
void addAccess (const std::string &stopId, const E *stopEdge, const double pos, const SumoXMLTag category)
Adds access edges for stopping places to the intermodal network.
void addSchedule (const SUMOVehicleParameter &pars, const std::vector< SUMOVehicleParameter::Stop > *addStops=0)
SUMOAbstractRouter< E, _IntermodalTrip > * clone ()
bool compute (const E *from, const E *to, double departPos, double arrivalPos, double speed, const V *const vehicle, const SVCPermissions modeSet, SUMOTime msTime, std::vector< TripItem > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
bool compute (const E *, const E *, const _IntermodalTrip *const, SUMOTime, std::vector< const E *> &)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
double getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, double t) const
bool hasNet () const
IntermodalRouter (CreateNetCallback callback, int carWalkTransfer)
Constructor.
void prohibit (const std::vector< E *> &toProhibit)
double recomputeCosts (const std::vector< const E *> &, const _IntermodalTrip *const, SUMOTime) const
void setBulkMode (const bool mode)
void startQuery ()
void writeNetwork (OutputDevice &dev)
void writeWeights (OutputDevice &dev)
virtual ~IntermodalRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Types
typedef AccessEdge< E, L, N, V > _AccessEdge
typedef IntermodalEdge< E, L, N, V > _IntermodalEdge
typedef IntermodalNetwork< E, L, N, V > _IntermodalNetwork
typedef IntermodalTrip< E, N, V > _IntermodalTrip
typedef PublicTransportEdge< E, L, N, V > _PTEdge
typedef void(* CreateNetCallback) (IntermodalRouter< E, L, N, V, INTERNALROUTER > &)
Private Member Functions
void addCarEdges (const std::vector< E *> &edges)
void createNet ()
_IntermodalEdge * getCarEdge (const E *e) const
Returns the associated car edge.
IntermodalRouter (_IntermodalNetwork *net)
IntermodalRouter & operator= (const IntermodalRouter &s)
Invalidated assignment operator.
int splitEdge (_IntermodalEdge *const toSplit, _IntermodalEdge *afterSplit, const double pos, _IntermodalEdge *const stopConn, const bool forward=true, const bool addExit=true)
Splits an edge (if necessary) and connects it to a stopping edge.
Private Attributes
std::map< _IntermodalEdge *, std::vector< _IntermodalEdge * > > myAccessSplits
retrieve the splitted edges for the given "original"
const bool myAmClone
CreateNetCallback myCallback
std::map< const E *, _IntermodalEdge * > myCarLookup
retrieve the car edge for the given input edge E
const int myCarWalkTransfer
_IntermodalNetwork * myIntermodalNet
INTERNALROUTER * myInternalRouter
int myNumericalID
std::map< std::string, std::vector< _PTEdge * > > myPTLines
retrieve the public transport edges for the given line
std::map< std::string, _IntermodalEdge * > myStopConnections
retrieve the connecting edges for the given "bus" stop
Detailed Description
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >>
class IntermodalRouter< E, L, N, V, INTERNALROUTER >
The router for pedestrians (on a bidirectional network of sidewalks and crossings)
Definition at line 59 of file IntermodalRouter.h.
Member Typedef Documentation
_AccessEdge
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> typedef AccessEdge<E, L, N, V> IntermodalRouter< E, L, N, V, INTERNALROUTER >::_AccessEdge private
Definition at line 64 of file IntermodalRouter.h.
_IntermodalEdge
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> typedef IntermodalEdge<E, L, N, V> IntermodalRouter< E, L, N, V, INTERNALROUTER >::_IntermodalEdge private
Definition at line 62 of file IntermodalRouter.h.
_IntermodalNetwork
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> typedef IntermodalNetwork<E, L, N, V> IntermodalRouter< E, L, N, V, INTERNALROUTER >::_IntermodalNetwork private
Definition at line 65 of file IntermodalRouter.h.
_IntermodalTrip
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> typedef IntermodalTrip<E, N, V> IntermodalRouter< E, L, N, V, INTERNALROUTER >::_IntermodalTrip private
Definition at line 66 of file IntermodalRouter.h.
_PTEdge
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> typedef PublicTransportEdge<E, L, N, V> IntermodalRouter< E, L, N, V, INTERNALROUTER >::_PTEdge private
Definition at line 63 of file IntermodalRouter.h.
CreateNetCallback
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> typedef void(* IntermodalRouter< E, L, N, V, INTERNALROUTER >::CreateNetCallback) (IntermodalRouter< E, L, N, V, INTERNALROUTER > &) private
Definition at line 61 of file IntermodalRouter.h.
Operation
typedef double(* SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::Operation) (const E *const, const IntermodalTrip< E, N, V > *const, double) inherited
Type of the function that is used to retrieve the edge effort.
Definition at line 55 of file SUMOAbstractRouter.h.
Member Enumeration Documentation
ModeChangeOptions
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> enum IntermodalRouter::ModeChangeOptions
where mode changes are possible
Enumerator
PARKING_AREAS
parking areas
PT_STOPS
public transport stops and access
ALL_JUNCTIONS
junctions with edges allowing the additional mode
Definition at line 79 of file IntermodalRouter.h.
Constructor & Destructor Documentation
IntermodalRouter() [1/2]
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> IntermodalRouter< E, L, N, V, INTERNALROUTER >::IntermodalRouter (CreateNetCallback callback, int carWalkTransfer) inline
Constructor.
Definition at line 89 of file IntermodalRouter.h.
~IntermodalRouter()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> virtual IntermodalRouter< E, L, N, V, INTERNALROUTER >::~IntermodalRouter () inline virtual
Destructor.
Definition at line 96 of file IntermodalRouter.h.
IntermodalRouter() [2/2]
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> IntermodalRouter< E, L, N, V, INTERNALROUTER >::IntermodalRouter (_IntermodalNetwork * net) inline private
Definition at line 379 of file IntermodalRouter.h.
Member Function Documentation
addAccess()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::addAccess (const std::string & stopId, const E * stopEdge, const double pos, const SumoXMLTag category) inline
Adds access edges for stopping places to the intermodal network.
This method creates an intermodal stop edge to represent the stoppping place (if not present yet) and determines the edges which need to be splitted (usually the forward and the backward pedestrian edges and the car edge) and calls splitEdge for the actual split and the connection of the stop edge with access edges. After that it adds and adapts the depart and arrival connectors to the new edge(s).
Parameters
[in] stopId The id of the stop to add
[in] stopEdge The edge on which the stop is located
[in] pos The relative position on the edge where the stop is located
[in] category The type of stop
Definition at line 125 of file IntermodalRouter.h.
Referenced by RONet::adaptIntermodalRouter(), and MSNet::adaptIntermodalRouter().
addCarEdges()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::addCarEdges (const std::vector< E *> & edges) inline private
Definition at line 449 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::createNet().
addSchedule()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::addSchedule (const SUMOVehicleParameter & pars, const std::vector< SUMOVehicleParameter::Stop > * addStops = 0) inline
Definition at line 195 of file IntermodalRouter.h.
Referenced by MSInsertionControl::adaptIntermodalRouter(), RONet::adaptIntermodalRouter(), and MSVehicleControl::adaptIntermodalRouter().
clone()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> SUMOAbstractRouter<E, _IntermodalTrip>* IntermodalRouter< E, L, N, V, INTERNALROUTER >::clone () inline virtual
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 103 of file IntermodalRouter.h.
compute() [1/2]
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> bool IntermodalRouter< E, L, N, V, INTERNALROUTER >::compute (const E * from, const E * to, double departPos, double arrivalPos, double speed, const V *const vehicle, const SVCPermissions modeSet, SUMOTime msTime, std::vector< TripItem > & into) inline
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Definition at line 270 of file IntermodalRouter.h.
Referenced by ROPerson::computeIntermodal().
compute() [2/2]
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> bool IntermodalRouter< E, L, N, V, INTERNALROUTER >::compute (const E * , const E * , const _IntermodalTrip * const, SUMOTime , std::vector< const E *> &) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 332 of file IntermodalRouter.h.
createNet()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::createNet () inline private
Definition at line 487 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::clone(), IntermodalRouter< E, L, N, V >::compute(), IntermodalRouter< E, L, N, V >::prohibit(), IntermodalRouter< E, L, N, V >::writeNetwork(), and IntermodalRouter< E, L, N, V >::writeWeights().
endQuery()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myQueryStartTime, SUMOAbstractRouter< E, V >::myQueryTimeSum, and SUMOAbstractRouter< E, V >::myQueryVisits.
getCarEdge()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> _IntermodalEdge* IntermodalRouter< E, L, N, V, INTERNALROUTER >::getCarEdge (const E * e) const inline private
Returns the associated car edge.
Definition at line 498 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addCarEdges(), and IntermodalRouter< E, L, N, V >::prohibit().
getEffort()
double SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myOperation.
hasNet()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> bool IntermodalRouter< E, L, N, V, INTERNALROUTER >::hasNet () const inline
Definition at line 108 of file IntermodalRouter.h.
Referenced by RONet::saveAndRemoveRoutesUntil().
operator=()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> IntermodalRouter& IntermodalRouter< E, L, N, V, INTERNALROUTER >::operator= (const IntermodalRouter< E, L, N, V, INTERNALROUTER > & s) private
Invalidated assignment operator.
prohibit()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::prohibit (const std::vector< E *> & toProhibit) inline
Definition at line 341 of file IntermodalRouter.h.
Referenced by MSNet::getIntermodalRouter().
recomputeCosts()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> double IntermodalRouter< E, L, N, V, INTERNALROUTER >::recomputeCosts (const std::vector< const E *> & , const _IntermodalTrip * const, SUMOTime) const inline virtual
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 337 of file IntermodalRouter.h.
setBulkMode()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myBulkMode.
splitEdge()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> int IntermodalRouter< E, L, N, V, INTERNALROUTER >::splitEdge (_IntermodalEdge *const toSplit, _IntermodalEdge * afterSplit, const double pos, _IntermodalEdge *const stopConn, const bool forward = true, const bool addExit = true) inline private
Splits an edge (if necessary) and connects it to a stopping edge.
This method determines whether an edge needs to be split at the given position (if there is not already a split nearby) and connects the stop edge via new access edges.
Parameters
[in] toSplit The first edge in the split list
[in] afterSplit The edge to add if a split is performed
[in] pos The relative position on the edge where the stop is located
[in] stopConn The stop edge to connect to
[in] forward whether we are aplitting a forward edge (backward edges get different names)
[in] addExit whether we can just enter the stop or exit as well (cars should not exit yet)
Returns
the index in the split list where the new edge has been added (if there was already a split near the position -1)
Definition at line 397 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess().
startQuery()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myNumQueries, and SUMOAbstractRouter< E, V >::myQueryStartTime.
writeNetwork()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::writeNetwork (OutputDevice & dev) inline
Definition at line 352 of file IntermodalRouter.h.
Referenced by RONet::writeIntermodal().
writeWeights()
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> void IntermodalRouter< E, L, N, V, INTERNALROUTER >::writeWeights (OutputDevice & dev) inline
Definition at line 367 of file IntermodalRouter.h.
Referenced by RONet::writeIntermodal().
Field Documentation
myAccessSplits
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> std::map<_IntermodalEdge*, std::vector<_IntermodalEdge*> > IntermodalRouter< E, L, N, V, INTERNALROUTER >::myAccessSplits private
retrieve the splitted edges for the given "original"
Definition at line 524 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), and IntermodalRouter< E, L, N, V >::splitEdge().
myAmClone
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> const bool IntermodalRouter< E, L, N, V, INTERNALROUTER >::myAmClone private
Definition at line 507 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::~IntermodalRouter().
myBulkMode
bool SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
myCallback
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> CreateNetCallback IntermodalRouter< E, L, N, V, INTERNALROUTER >::myCallback private
Definition at line 511 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::createNet().
myCarLookup
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> std::map<const E*, _IntermodalEdge*> IntermodalRouter< E, L, N, V, INTERNALROUTER >::myCarLookup private
retrieve the car edge for the given input edge E
Definition at line 515 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), and IntermodalRouter< E, L, N, V >::getCarEdge().
myCarWalkTransfer
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> const int IntermodalRouter< E, L, N, V, INTERNALROUTER >::myCarWalkTransfer private
Definition at line 512 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), and IntermodalRouter< E, L, N, V >::addCarEdges().
myIntermodalNet
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> _IntermodalNetwork* IntermodalRouter< E, L, N, V, INTERNALROUTER >::myIntermodalNet private
Definition at line 509 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), IntermodalRouter< E, L, N, V >::addSchedule(), IntermodalRouter< E, L, N, V >::clone(), IntermodalRouter< E, L, N, V >::compute(), IntermodalRouter< E, L, N, V >::createNet(), IntermodalRouter< E, L, N, V >::hasNet(), IntermodalRouter< E, L, N, V >::prohibit(), IntermodalRouter< E, L, N, V >::splitEdge(), IntermodalRouter< E, L, N, V >::writeNetwork(), IntermodalRouter< E, L, N, V >::writeWeights(), and IntermodalRouter< E, L, N, V >::~IntermodalRouter().
myInternalRouter
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> INTERNALROUTER* IntermodalRouter< E, L, N, V, INTERNALROUTER >::myInternalRouter private
Definition at line 508 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::compute(), IntermodalRouter< E, L, N, V >::createNet(), IntermodalRouter< E, L, N, V >::prohibit(), and IntermodalRouter< E, L, N, V >::~IntermodalRouter().
myNumericalID
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> int IntermodalRouter< E, L, N, V, INTERNALROUTER >::myNumericalID private
Definition at line 510 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), IntermodalRouter< E, L, N, V >::addSchedule(), IntermodalRouter< E, L, N, V >::createNet(), and IntermodalRouter< E, L, N, V >::splitEdge().
myOperation
Operation SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
myPTLines
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> std::map<std::string, std::vector<_PTEdge*> > IntermodalRouter< E, L, N, V, INTERNALROUTER >::myPTLines private
retrieve the public transport edges for the given line
Definition at line 518 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addSchedule().
myStopConnections
template<class E, class L, class N, class V, class INTERNALROUTER = DijkstraRouter<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V>, prohibited_withPermissions<IntermodalEdge<E, L, N, V>, IntermodalTrip<E, N, V> > >> std::map<std::string, _IntermodalEdge*> IntermodalRouter< E, L, N, V, INTERNALROUTER >::myStopConnections private
retrieve the connecting edges for the given "bus" stop
Definition at line 521 of file IntermodalRouter.h.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), and IntermodalRouter< E, L, N, V >::addSchedule().
The documentation for this class was generated from the following file:
IntermodalRouter.h