SUMO - Simulation of Urban MObility: ShapeContainer Class Reference
ShapeContainer Class Reference
Storage for geometrical objects.
#include <ShapeContainer.h>
Public Types
typedef NamedObjectCont< PointOfInterest * > POIs
typedef NamedObjectCont< SUMOPolygon * > Polygons
containers
Public Member Functions
virtual bool addPOI (const std::string &id, const std::string &type, const RGBColor &color, const Position &pos, bool geo, const std::string &lane, double posOverLane, double posLat, double layer, double angle, const std::string &imgFile, double width, double height, bool ignorePruning=false)
Builds a POI using the given values and adds it to the container.
virtual bool addPolygon (const std::string &id, const std::string &type, const RGBColor &color, double layer, double angle, const std::string &imgFile, const PositionVector &shape, bool geo, bool fill, bool ignorePruning=false)
Builds a polygon using the given values and adds it to the container.
const POIs & getPOIs () const
Returns all pois.
const Polygons & getPolygons () const
Returns all polygons.
virtual void movePOI (const std::string &id, const Position &pos)
Assigns a new position to the named PoI.
virtual bool removePOI (const std::string &id)
Removes a PoI from the container.
virtual bool removePolygon (const std::string &id)
Removes a polygon from the container.
virtual void reshapePolygon (const std::string &id, const PositionVector &shape)
Assigns a shape to the named polygon.
ShapeContainer ()
Constructor.
virtual ~ShapeContainer ()
Destructor.
Protected Member Functions
virtual bool add (SUMOPolygon *poly, bool ignorePruning=false)
add polygon
virtual bool add (PointOfInterest *poi, bool ignorePruning=false)
add poi
Protected Attributes
POIs myPOIs
stored POIs
Polygons myPolygons
stored Polygons
Detailed Description
Storage for geometrical objects.
Definition at line 47 of file ShapeContainer.h.
Member Typedef Documentation
POIs
typedef NamedObjectCont<PointOfInterest*> ShapeContainer::POIs
Definition at line 52 of file ShapeContainer.h.
Polygons
typedef NamedObjectCont<SUMOPolygon*> ShapeContainer::Polygons
containers
Definition at line 51 of file ShapeContainer.h.
Constructor & Destructor Documentation
ShapeContainer()
ShapeContainer::ShapeContainer ()
Constructor.
Definition at line 50 of file ShapeContainer.cpp.
~ShapeContainer()
ShapeContainer::~ShapeContainer () virtual
Destructor.
Definition at line 52 of file ShapeContainer.cpp.
Member Function Documentation
add() [1/2]
bool ShapeContainer::add (SUMOPolygon * poly, bool ignorePruning = false) protected virtual
add polygon
Reimplemented in PCPolyContainer.
Definition at line 102 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and myPolygons.
Referenced by PCPolyContainer::add(), addPOI(), addPolygon(), and getPOIs().
add() [2/2]
bool ShapeContainer::add (PointOfInterest * poi, bool ignorePruning = false) protected virtual
add poi
Reimplemented in PCPolyContainer.
Definition at line 112 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and myPOIs.
addPOI()
bool ShapeContainer::addPOI (const std::string & id, const std::string & type, const RGBColor & color, const Position & pos, bool geo, const std::string & lane, double posOverLane, double posLat, double layer, double angle, const std::string & imgFile, double width, double height, bool ignorePruning = false) virtual
Builds a POI using the given values and adds it to the container.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] pos The position of the POI
Reimplemented in GNENet, and GUIShapeContainer.
Definition at line 64 of file ShapeContainer.cpp.
References add().
Referenced by libsumo::POI::add(), and ShapeHandler::addPOI().
addPolygon()
bool ShapeContainer::addPolygon (const std::string & id, const std::string & type, const RGBColor & color, double layer, double angle, const std::string & imgFile, const PositionVector & shape, bool geo, bool fill, bool ignorePruning = false) virtual
Builds a polygon using the given values and adds it to the container.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] geo specify if shape was loaded as GEO coordinate
[in] fill Whether the polygon shall be filled
Returns
whether the polygon could be added
Reimplemented in GNENet, and GUIShapeContainer.
Definition at line 55 of file ShapeContainer.cpp.
References add().
Referenced by libsumo::Polygon::add(), NLHandler::addDistrict(), and ShapeHandler::addPoly().
getPOIs()
const POIs& ShapeContainer::getPOIs () const inline
Returns all pois.
Definition at line 128 of file ShapeContainer.h.
References add(), and myPOIs.
Referenced by ShapeHandler::addPOI(), libsumo::POI::getIDList(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), GUIShapeContainer::getPOIIds(), libsumo::POI::getTree(), GNESelectorFrame::onCmdInvert(), and GNENet::retrieveShapes().
getPolygons()
const Polygons& ShapeContainer::getPolygons () const inline
Returns all polygons.
Definition at line 123 of file ShapeContainer.h.
References myPolygons.
Referenced by ShapeHandler::addPoly(), libsumo::Polygon::getIDList(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), GUIShapeContainer::getPolygonIDs(), libsumo::Polygon::getTree(), PCLoaderDlrNavteq::loadPolyFile(), GNESelectorFrame::onCmdInvert(), and GNENet::retrieveShapes().
movePOI()
void ShapeContainer::movePOI (const std::string & id, const Position & pos) virtual
Assigns a new position to the named PoI.
Parameters
[in] id The id of the PoI to move
[in] pos The PoI's new position
Reimplemented in GUIShapeContainer.
Definition at line 84 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), and myPOIs.
removePOI()
bool ShapeContainer::removePOI (const std::string & id) virtual
Removes a PoI from the container.
Parameters
[in] id The id of the PoI
Returns
Whether the poi could be removed
Reimplemented in GUIShapeContainer.
Definition at line 78 of file ShapeContainer.cpp.
References myPOIs, and NamedObjectCont< T >::remove().
Referenced by libsumo::POI::remove(), and GNEChange_Attribute::~GNEChange_Attribute().
removePolygon()
bool ShapeContainer::removePolygon (const std::string & id) virtual
Removes a polygon from the container.
Parameters
[in] id The id of the polygon
Returns
Whether the polygon could be removed
Reimplemented in GUIShapeContainer.
Definition at line 72 of file ShapeContainer.cpp.
References myPolygons, and NamedObjectCont< T >::remove().
Referenced by libsumo::Polygon::remove(), and GNEChange_Attribute::~GNEChange_Attribute().
reshapePolygon()
void ShapeContainer::reshapePolygon (const std::string & id, const PositionVector & shape) virtual
Assigns a shape to the named polygon.
Parameters
[in] id The id of the polygon to reshape
[in] shape The polygon's new shape
Reimplemented in GUIShapeContainer.
Definition at line 93 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), myPolygons, and SUMOPolygon::setShape().
Referenced by libsumo::Polygon::setShape().
Field Documentation
myPOIs
POIs ShapeContainer::myPOIs protected
stored POIs
Definition at line 144 of file ShapeContainer.h.
Referenced by add(), GUIShapeContainer::addPOI(), GNENet::addPOI(), GNENet::changeShapeID(), GNENet::computeAndUpdate(), GNENet::generateShapeID(), GNENet::getGlIDs(), GNENet::getNumberOfShapes(), getPOIs(), GNENet::insertShape(), movePOI(), GUIShapeContainer::movePOI(), removePOI(), GUIShapeContainer::removePOI(), GNENet::removeShape(), GNENet::retrievePOI(), GNENet::retrievePOILane(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), GNENet::saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and PCPolyContainer::~PCPolyContainer().
myPolygons
Polygons ShapeContainer::myPolygons protected
stored Polygons
Definition at line 141 of file ShapeContainer.h.
Referenced by add(), GUIShapeContainer::addPolygon(), GNENet::addPolygon(), GNENet::changeShapeID(), GNENet::computeAndUpdate(), GNENet::generateShapeID(), GNENet::getGlIDs(), GNENet::getNumberOfShapes(), getPolygons(), GNENet::insertShape(), removePolygon(), GUIShapeContainer::removePolygon(), GNENet::removeShape(), reshapePolygon(), GUIShapeContainer::reshapePolygon(), GNENet::retrievePolygon(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), GNENet::saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and PCPolyContainer::~PCPolyContainer().
The documentation for this class was generated from the following files:
ShapeContainer.h
ShapeContainer.cpp