SUMO - Simulation of Urban MObility: TraCIServerAPI_TrafficLight Class Reference
TraCIServerAPI_TrafficLight Class Reference
APIs for getting/setting traffic light values via TraCI.
#include <TraCIServerAPI_TrafficLight.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa2: Get Traffic Lights Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc2: Change Traffic Lights State)
Private Member Functions
TraCIServerAPI_TrafficLight & operator= (const TraCIServerAPI_TrafficLight &s)
invalidated assignment operator
TraCIServerAPI_TrafficLight (const TraCIServerAPI_TrafficLight &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting traffic light values via TraCI.
Definition at line 46 of file TraCIServerAPI_TrafficLight.h.
Constructor & Destructor Documentation
TraCIServerAPI_TrafficLight()
TraCIServerAPI_TrafficLight::TraCIServerAPI_TrafficLight (const TraCIServerAPI_TrafficLight & s) private
invalidated copy constructor
Member Function Documentation
operator=()
TraCIServerAPI_TrafficLight& TraCIServerAPI_TrafficLight::operator= (const TraCIServerAPI_TrafficLight & s) private
invalidated assignment operator
processGet()
bool TraCIServerAPI_TrafficLight::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa2: Get Traffic Lights Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 48 of file TraCIServerAPI_TrafficLight.cpp.
References CMD_GET_TL_VARIABLE, libsumo::TraCIPhase::duration, libsumo::TraCIPhase::duration1, libsumo::TraCIPhase::duration2, MSTLLogicControl::get(), MSTLLogicControl::TLSLogicVariants::getActive(), libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(), libsumo::TrafficLight::getControlledJunctions(), libsumo::TrafficLight::getControlledLanes(), libsumo::TrafficLight::getControlledLinks(), MSTrafficLightLogic::getCurrentPhaseDef(), libsumo::TrafficLight::getIDCount(), libsumo::TrafficLight::getIDList(), MSNet::getInstance(), MSTrafficLightLogic::getLaneVectors(), Parameterised::getMap(), libsumo::TrafficLight::getNextSwitch(), libsumo::TrafficLight::getParameter(), libsumo::TrafficLight::getPhase(), libsumo::TrafficLight::getPhaseDuration(), libsumo::TrafficLight::getProgram(), libsumo::TrafficLight::getRedYellowGreenState(), MSPhaseDefinition::getState(), MSNet::getTLSControl(), ID_COUNT, ID_LIST, libsumo::TraCIPhase::phase, tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_TL_VARIABLE, RTYPE_OK, TL_COMPLETE_DEFINITION_RYG, TL_CONTROLLED_JUNCTIONS, TL_CONTROLLED_LANES, TL_CONTROLLED_LINKS, TL_CURRENT_PHASE, TL_CURRENT_PROGRAM, TL_EXTERNAL_STATE, TL_NEXT_SWITCH, TL_PHASE_DURATION, TL_RED_YELLOW_GREEN_STATE, toHex(), TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, TYPE_UBYTE, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
processSet()
bool TraCIServerAPI_TrafficLight::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xc2: Change Traffic Lights State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 256 of file TraCIServerAPI_TrafficLight.cpp.
References CMD_SET_TL_VARIABLE, libsumo::TraCILogic::currentPhaseIndex, libsumo::TraCILogic::phases, tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, libsumo::TrafficLight::setCompleteRedYellowGreenDefinition(), libsumo::TrafficLight::setParameter(), libsumo::TrafficLight::setPhase(), libsumo::TrafficLight::setPhaseDuration(), libsumo::TrafficLight::setProgram(), libsumo::TrafficLight::setRedYellowGreenState(), libsumo::TraCILogic::subID, TL_COMPLETE_PROGRAM_RYG, TL_PHASE_DURATION, TL_PHASE_INDEX, TL_PROGRAM, TL_RED_YELLOW_GREEN_STATE, toHex(), libsumo::TraCILogic::type, TYPE_COMPOUND, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_TrafficLight.h
TraCIServerAPI_TrafficLight.cpp