SUMO - Simulation of Urban MObility: GUIPerspectiveChanger Class Reference
GUIPerspectiveChanger Class Reference abstract
#include <GUIPerspectiveChanger.h>
Public Types
enum MouseState { MOUSEBTN_NONE = 0, MOUSEBTN_LEFT = 1, MOUSEBTN_RIGHT = 2, MOUSEBTN_MIDDLE = 4 }
mouse states
Public Member Functions
virtual void centerTo (const Position &pos, double radius, bool applyZoom=true)=0
Centers the view to the given position, setting it to a size that covers the radius. Used for: Centering of vehicles and junctions */.
virtual void changeCanvasSizeLeft (int change)=0
FXint getMouseXPosition () const
Returns the last mouse x-position an event occured at.
FXint getMouseYPosition () const
Returns the last mouse y-position an event occured at.
virtual double getRotation () const =0
Returns the rotation of the canvas stored in this changer.
Boundary getViewport (bool fixRatio=true)
get viewport
virtual double getXPos () const =0
Returns the x-offset of the field to show stored in this changer.
virtual double getYPos () const =0
Returns the y-offset of the field to show stored in this changer.
virtual double getZoom () const =0
Returns the zoom factor computed stored in this changer.
virtual double getZPos () const =0
Returns the camera height corresponding to the current zoom factor.
GUIPerspectiveChanger (GUISUMOAbstractView &callBack, const Boundary &viewPort)
Constructor.
virtual void setViewport (double zoom, double xPos, double yPos)=0
Sets the viewport Used for: Adapting a new viewport.
void setViewport (const Boundary &viewPort)
set viewport
virtual void setViewportFrom (double xPos, double yPos, double zPos)=0
Alternative method for setting the viewport.
virtual double zoom2ZPos (double zoom) const =0
Returns the camera height at which the given zoom level is reached.
virtual double zPos2Zoom (double zPos) const =0
Returns the zoom level that is achieved at a given camera height.
virtual ~GUIPerspectiveChanger ()
Destructor.
virtual void onLeftBtnPress (void *data)
mouse functions
virtual bool onLeftBtnRelease (void *data)
called when user releases left button
virtual void onRightBtnPress (void *data)
called when user press right button
virtual bool onRightBtnRelease (void *data)
called when user releases right button
virtual void onDoubleClicked (void *data)
called when user click two times
virtual void onMouseWheel (void *data)
called when user changes mouse wheel
virtual void onMouseMove (void *data)
called when user moves mouse
virtual long onKeyPress (void *data)
called when user press a key
virtual long onKeyRelease (void *data)
called when user releases a key
Protected Attributes
GUISUMOAbstractView & myCallback
The parent window (canvas to scale)
FXint myMouseXPosition
the current mouse position
FXint myMouseYPosition
Boundary myViewPort
the intended viewport
Private Member Functions
GUIPerspectiveChanger (const GUIPerspectiveChanger &)
Invalidated copy constructor.
GUIPerspectiveChanger & operator= (const GUIPerspectiveChanger &)
Invalidated assignment operator.
Boundary patchedViewPort ()
patched viewPort with the same aspect ratio as the canvas
Detailed Description
This is the interface for implementation of own classes that handle the interaction between the user and a display field. While most of our (IVF) interfaces allow zooming by choosing the rectangle to show, other types of interaction are possible and have been implemented. To differ between the behaviours, all types of interaction between the user and the canvas are send to this class: mouse moving, mouse button pressing and releasing.
Definition at line 59 of file GUIPerspectiveChanger.h.
Member Enumeration Documentation
MouseState
enum GUIPerspectiveChanger::MouseState
mouse states
Enumerator
MOUSEBTN_NONE
MOUSEBTN_LEFT
MOUSEBTN_RIGHT
MOUSEBTN_MIDDLE
Definition at line 62 of file GUIPerspectiveChanger.h.
Constructor & Destructor Documentation
GUIPerspectiveChanger() [1/2]
GUIPerspectiveChanger::GUIPerspectiveChanger (GUISUMOAbstractView & callBack, const Boundary & viewPort)
Constructor.
Definition at line 39 of file GUIPerspectiveChanger.cpp.
~GUIPerspectiveChanger()
GUIPerspectiveChanger::~GUIPerspectiveChanger () virtual
Destructor.
Definition at line 45 of file GUIPerspectiveChanger.cpp.
GUIPerspectiveChanger() [2/2]
GUIPerspectiveChanger::GUIPerspectiveChanger (const GUIPerspectiveChanger &) private
Invalidated copy constructor.
Member Function Documentation
centerTo()
virtual void GUIPerspectiveChanger::centerTo (const Position & pos, double radius, bool applyZoom = true) pure virtual
Centers the view to the given position, setting it to a size that covers the radius. Used for: Centering of vehicles and junctions */.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::centerTo().
changeCanvasSizeLeft()
virtual void GUIPerspectiveChanger::changeCanvasSizeLeft (int change) pure virtual
Implemented in GUIDanielPerspectiveChanger.
getMouseXPosition()
FXint GUIPerspectiveChanger::getMouseXPosition () const
Returns the last mouse x-position an event occured at.
Definition at line 98 of file GUIPerspectiveChanger.cpp.
References myMouseXPosition.
getMouseYPosition()
FXint GUIPerspectiveChanger::getMouseYPosition () const
Returns the last mouse y-position an event occured at.
Definition at line 104 of file GUIPerspectiveChanger.cpp.
References myMouseYPosition.
getRotation()
virtual double GUIPerspectiveChanger::getRotation () const pure virtual
Returns the rotation of the canvas stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
getViewport()
Boundary GUIPerspectiveChanger::getViewport (bool fixRatio = true)
get viewport
Definition at line 110 of file GUIPerspectiveChanger.cpp.
References myViewPort, and patchedViewPort().
Referenced by GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getVisibleBoundary(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::p2m(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::paintGLGrid(), and GUISUMOAbstractView::screenPos2NetPos().
getXPos()
virtual double GUIPerspectiveChanger::getXPos () const pure virtual
Returns the x-offset of the field to show stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::copyViewportTo(), GUISUMOAbstractView::getViewportEditor(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), GUISUMOAbstractView::onMouseMove(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
getYPos()
virtual double GUIPerspectiveChanger::getYPos () const pure virtual
Returns the y-offset of the field to show stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::copyViewportTo(), GUISUMOAbstractView::getViewportEditor(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), GUISUMOAbstractView::onMouseMove(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
getZoom()
virtual double GUIPerspectiveChanger::getZoom () const pure virtual
Returns the zoom factor computed stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::getViewportEditor(), GUIDialog_EditViewport::onCmdLoad(), GUISUMOAbstractView::onMouseMove(), and TraCIServerAPI_GUI::processGet().
getZPos()
virtual double GUIPerspectiveChanger::getZPos () const pure virtual
Returns the camera height corresponding to the current zoom factor.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::copyViewportTo(), GUIApplicationWindow::onCmdNetedit(), TraCIServerAPI_GUI::processSet(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
onDoubleClicked()
void GUIPerspectiveChanger::onDoubleClicked (void * data) virtual
called when user click two times
Definition at line 71 of file GUIPerspectiveChanger.cpp.
onKeyPress()
long GUIPerspectiveChanger::onKeyPress (void * data) virtual
called when user press a key
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 86 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onKeyPress().
onKeyRelease()
long GUIPerspectiveChanger::onKeyRelease (void * data) virtual
called when user releases a key
Definition at line 92 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onKeyRelease().
onLeftBtnPress()
void GUIPerspectiveChanger::onLeftBtnPress (void * data) virtual
mouse functions
called when user press left button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 50 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onLeftBtnPress(), and GNEViewNet::processClick().
onLeftBtnRelease()
bool GUIPerspectiveChanger::onLeftBtnRelease (void * data) virtual
called when user releases left button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 55 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onLeftBtnRelease().
onMouseMove()
void GUIPerspectiveChanger::onMouseMove (void * data) virtual
called when user moves mouse
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 81 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onMouseMove().
onMouseWheel()
void GUIPerspectiveChanger::onMouseWheel (void * data) virtual
called when user changes mouse wheel
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 76 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onMouseWheel().
onRightBtnPress()
void GUIPerspectiveChanger::onRightBtnPress (void * data) virtual
called when user press right button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 61 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onRightBtnPress().
onRightBtnRelease()
bool GUIPerspectiveChanger::onRightBtnRelease (void * data) virtual
called when user releases right button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 66 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onRightBtnRelease(), and GUISUMOAbstractView::openObjectDialog().
operator=()
GUIPerspectiveChanger& GUIPerspectiveChanger::operator= (const GUIPerspectiveChanger &) private
Invalidated assignment operator.
patchedViewPort()
Boundary GUIPerspectiveChanger::patchedViewPort () private
patched viewPort with the same aspect ratio as the canvas
Definition at line 126 of file GUIPerspectiveChanger.cpp.
References Boundary::getHeight(), Boundary::getWidth(), Boundary::growHeight(), Boundary::growWidth(), myCallback, and myViewPort.
Referenced by getViewport().
setViewport() [1/2]
virtual void GUIPerspectiveChanger::setViewport (double zoom, double xPos, double yPos) pure virtual
Sets the viewport Used for: Adapting a new viewport.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::getObjectsInBoundary(), and GUISUMOAbstractView::recenterView().
setViewport() [2/2]
void GUIPerspectiveChanger::setViewport (const Boundary & viewPort)
set viewport
Definition at line 120 of file GUIPerspectiveChanger.cpp.
References myViewPort.
setViewportFrom()
virtual void GUIPerspectiveChanger::setViewportFrom (double xPos, double yPos, double zPos) pure virtual
Alternative method for setting the viewport.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::setViewportFromTo().
zoom2ZPos()
virtual double GUIPerspectiveChanger::zoom2ZPos (double zoom) const pure virtual
Returns the camera height at which the given zoom level is reached.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISettingsHandler::applyViewport(), GUIDialog_EditViewport::onCmdChanged(), TraCIServerAPI_GUI::processSet(), and GUIDialog_EditViewport::setValues().
zPos2Zoom()
virtual double GUIPerspectiveChanger::zPos2Zoom (double zPos) const pure virtual
Returns the zoom level that is achieved at a given camera height.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUIDialog_EditViewport::onCmdChanged(), and GUIDialog_EditViewport::setValues().
Field Documentation
myCallback
GUISUMOAbstractView& GUIPerspectiveChanger::myCallback protected
The parent window (canvas to scale)
Definition at line 157 of file GUIPerspectiveChanger.h.
Referenced by GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), GUIDanielPerspectiveChanger::move(), GUIDanielPerspectiveChanger::onKeyPress(), GUIDanielPerspectiveChanger::onMouseMove(), GUIDanielPerspectiveChanger::onMouseWheel(), GUIDanielPerspectiveChanger::onRightBtnPress(), patchedViewPort(), GUIDanielPerspectiveChanger::setViewport(), and GUIDanielPerspectiveChanger::zoom().
myMouseXPosition
FXint GUIPerspectiveChanger::myMouseXPosition protected
the current mouse position
Definition at line 160 of file GUIPerspectiveChanger.h.
Referenced by getMouseXPosition(), GUIDanielPerspectiveChanger::onLeftBtnPress(), GUIDanielPerspectiveChanger::onLeftBtnRelease(), GUIDanielPerspectiveChanger::onMouseMove(), GUIDanielPerspectiveChanger::onRightBtnPress(), and GUIDanielPerspectiveChanger::onRightBtnRelease().
myMouseYPosition
FXint GUIPerspectiveChanger::myMouseYPosition protected
Definition at line 160 of file GUIPerspectiveChanger.h.
Referenced by getMouseYPosition(), GUIDanielPerspectiveChanger::onLeftBtnPress(), GUIDanielPerspectiveChanger::onLeftBtnRelease(), GUIDanielPerspectiveChanger::onMouseMove(), GUIDanielPerspectiveChanger::onRightBtnPress(), and GUIDanielPerspectiveChanger::onRightBtnRelease().
myViewPort
Boundary GUIPerspectiveChanger::myViewPort protected
the intended viewport
Definition at line 163 of file GUIPerspectiveChanger.h.
Referenced by GUIDanielPerspectiveChanger::centerTo(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), getViewport(), GUIDanielPerspectiveChanger::getXPos(), GUIDanielPerspectiveChanger::getYPos(), GUIDanielPerspectiveChanger::getZoom(), GUIDanielPerspectiveChanger::getZPos(), GUIDanielPerspectiveChanger::move(), GUIDanielPerspectiveChanger::onKeyPress(), patchedViewPort(), GUIDanielPerspectiveChanger::setViewport(), setViewport(), and GUIDanielPerspectiveChanger::zoom().
The documentation for this class was generated from the following files:
GUIPerspectiveChanger.h
GUIPerspectiveChanger.cpp