SUMO - Simulation of Urban MObility: MSSOTLMarchingPolicy Class Reference
MSSOTLMarchingPolicy Class Reference
Class for low-level marching policy.
#include <MSSOTLMarchingPolicy.h>
Public Member Functions
bool canRelease (SUMOTime elapsed, bool thresholdPassed, bool pushButtonPressed, const MSPhaseDefinition *stage, int vehicleCount)
void clearParameter ()
Clears the parameter map.
double computeDesirability (double vehInMeasure, double vehOutMeasure, double vehInDispersionMeasure, double vehOutDispersionMeasure)
Computes the desirability of this policy, necessary when used in combination with an high level policy.
double computeDesirability (double vehInMeasure, double vehOutMeasure)
virtual int decideNextPhase (SUMOTime elapsed, const MSPhaseDefinition *stage, int currentPhaseIndex, int phaseMaxCTS, bool thresholdPassed, bool pushButtonPressed, int vehicleCount)
MSSOTLPolicyDesirability * getDesirabilityAlgorithm ()
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
std::string getName ()
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
virtual double getThetaSensitivity ()
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSSOTLMarchingPolicy (const std::map< std::string, std::string > &parameters)
MSSOTLMarchingPolicy (MSSOTLPolicyDesirability *desirabilityAlgorithm)
MSSOTLMarchingPolicy (MSSOTLPolicyDesirability *desirabilityAlgorithm, const std::map< std::string, std::string > &parameters)
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
virtual void setThetaSensitivity (double val)
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Protected Member Functions
void init (std::string prefix, const Parameterised *parameterised)
void init ()
bool pushButtonLogic (SUMOTime elapsed, bool pushButtonPressed, const MSPhaseDefinition *stage)
Protected Attributes
std::string m_prefix
double m_pushButtonScaleFactor
Detailed Description
Class for low-level marching policy.
Definition at line 40 of file MSSOTLMarchingPolicy.h.
Constructor & Destructor Documentation
MSSOTLMarchingPolicy() [1/3]
MSSOTLMarchingPolicy::MSSOTLMarchingPolicy (const std::map< std::string, std::string > & parameters)
Definition at line 24 of file MSSOTLMarchingPolicy.cpp.
References init().
MSSOTLMarchingPolicy() [2/3]
MSSOTLMarchingPolicy::MSSOTLMarchingPolicy (MSSOTLPolicyDesirability * desirabilityAlgorithm)
Definition at line 30 of file MSSOTLMarchingPolicy.cpp.
References MSSOTLPolicy::getDesirabilityAlgorithm(), init(), and MSSOTLPolicyDesirability::setKeyPrefix().
MSSOTLMarchingPolicy() [3/3]
MSSOTLMarchingPolicy::MSSOTLMarchingPolicy (MSSOTLPolicyDesirability * desirabilityAlgorithm, const std::map< std::string, std::string > & parameters)
Definition at line 37 of file MSSOTLMarchingPolicy.cpp.
References MSSOTLPolicy::getDesirabilityAlgorithm(), init(), and MSSOTLPolicyDesirability::setKeyPrefix().
Member Function Documentation
canRelease()
bool MSSOTLMarchingPolicy::canRelease (SUMOTime elapsed, bool thresholdPassed, bool pushButtonPressed, const MSPhaseDefinition * stage, int vehicleCount) virtual
Implements MSSOTLPolicy.
Definition at line 45 of file MSSOTLMarchingPolicy.cpp.
References MSPhaseDefinition::duration, MSPhaseDefinition::minDuration, and PushButtonLogic::pushButtonLogic().
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
computeDesirability() [1/2]
double MSSOTLPolicy::computeDesirability (double vehInMeasure, double vehOutMeasure, double vehInDispersionMeasure, double vehOutDispersionMeasure) inherited
Computes the desirability of this policy, necessary when used in combination with an high level policy.
Definition at line 105 of file MSSOTLPolicy.cpp.
References MSSOTLPolicyDesirability::computeDesirability(), DBG, MSSOTLPolicy::getName(), MSSOTLPolicy::myDesirabilityAlgorithm, and WRITE_MESSAGE.
computeDesirability() [2/2]
double MSSOTLPolicy::computeDesirability (double vehInMeasure, double vehOutMeasure) inherited
Definition at line 114 of file MSSOTLPolicy.cpp.
References MSSOTLPolicyDesirability::computeDesirability(), DBG, MSSOTLPolicy::getName(), MSSOTLPolicy::myDesirabilityAlgorithm, and WRITE_MESSAGE.
decideNextPhase()
int MSSOTLPolicy::decideNextPhase (SUMOTime elapsed, const MSPhaseDefinition * stage, int currentPhaseIndex, int phaseMaxCTS, bool thresholdPassed, bool pushButtonPressed, int vehicleCount) virtual inherited
Reimplemented in MSSOTLCongestionPolicy.
Definition at line 123 of file MSSOTLPolicy.cpp.
References MSSOTLPolicy::canRelease(), DBG, MSPhaseDefinition::isCommit(), MSPhaseDefinition::isDecisional(), MSPhaseDefinition::isTransient(), time2string(), and WRITE_MESSAGE.
Referenced by MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), and MSSwarmTrafficLightLogic::decideNextPhase().
getDesirabilityAlgorithm()
MSSOTLPolicyDesirability* MSSOTLPolicy::getDesirabilityAlgorithm () inline inherited
Definition at line 127 of file MSSOTLPolicy.h.
Referenced by MSSOTLCongestionPolicy::MSSOTLCongestionPolicy(), MSSOTLMarchingPolicy(), MSSOTLPhasePolicy::MSSOTLPhasePolicy(), MSSOTLPlatoonPolicy::MSSOTLPlatoonPolicy(), MSSOTLRequestPolicy::MSSOTLRequestPolicy(), and MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getName()
std::string MSSOTLPolicy::getName () inline inherited
Definition at line 124 of file MSSOTLPolicy.h.
Referenced by MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicy::computeDesirability(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), and MSSwarmTrafficLightLogic::updateSensitivities().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getThetaSensitivity()
virtual double MSSOTLPolicy::getThetaSensitivity () inline virtual inherited
Definition at line 118 of file MSSOTLPolicy.h.
Referenced by MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), and MSSwarmTrafficLightLogic::updateSensitivities().
init() [1/2]
void PushButtonLogic::init (std::string prefix, const Parameterised * parameterised) protected inherited
Definition at line 27 of file MSSOTLPolicy.cpp.
References TplConvert::_2double(), Parameterised::getParameter(), PushButtonLogic::m_prefix, PushButtonLogic::m_pushButtonScaleFactor, and WRITE_MESSAGE.
Referenced by MSSOTLPhasePolicy::init(), init(), and MSSOTLPlatoonPolicy::init().
init() [2/2]
void MSSOTLMarchingPolicy::init () protected virtual
Reimplemented from MSSOTLPolicy.
Definition at line 53 of file MSSOTLMarchingPolicy.cpp.
References PushButtonLogic::init().
Referenced by MSSOTLMarchingPolicy().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
pushButtonLogic()
bool PushButtonLogic::pushButtonLogic (SUMOTime elapsed, bool pushButtonPressed, const MSPhaseDefinition * stage) protected inherited
Definition at line 33 of file MSSOTLPolicy.cpp.
References MSPhaseDefinition::duration, PushButtonLogic::m_prefix, PushButtonLogic::m_pushButtonScaleFactor, and WRITE_MESSAGE.
Referenced by MSSOTLPhasePolicy::canRelease(), canRelease(), and MSSOTLPlatoonPolicy::canRelease().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setThetaSensitivity()
virtual void MSSOTLPolicy::setThetaSensitivity (double val) inline virtual inherited
Definition at line 121 of file MSSOTLPolicy.h.
Referenced by MSSwarmTrafficLightLogic::updateSensitivities().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
m_prefix
std::string PushButtonLogic::m_prefix protected inherited
Definition at line 52 of file MSSOTLPolicy.h.
Referenced by PushButtonLogic::init(), SigmoidLogic::init(), PushButtonLogic::pushButtonLogic(), and SigmoidLogic::sigmoidLogic().
m_pushButtonScaleFactor
double PushButtonLogic::m_pushButtonScaleFactor protected inherited
Definition at line 51 of file MSSOTLPolicy.h.
Referenced by PushButtonLogic::init(), and PushButtonLogic::pushButtonLogic().
The documentation for this class was generated from the following files:
MSSOTLMarchingPolicy.h
MSSOTLMarchingPolicy.cpp