SUMO - Simulation of Urban MObility: NBSign Class Reference
NBSign Class Reference
A class representing a single street sign.
#include <NBSign.h>
Public Types
enum SignType {
SIGN_TYPE_SPEED, SIGN_TYPE_YIELD, SIGN_TYPE_STOP, SIGN_TYPE_ALLWAY_STOP,
SIGN_TYPE_ON_RAMP, SIGN_TYPE_PRIORITY, SIGN_TYPE_RIGHT_BEFORE_LEFT, SIGN_TYPE_ROUNDABOUT,
SIGN_TYPE_RAIL_CROSSING, SIGN_TYPE_SLOPE, SIGN_TYPE_CITY, SIGN_TYPE_INFO
}
Public Member Functions
NBSign (SignType type, double offset, const std::string label="")
Constructor with id, and position.
void writeAsPOI (OutputDevice &into, const NBEdge *edge) const
write into device as POI positioned relative to the given edge
~NBSign ()
Destructor.
Private Attributes
std::string myLabel
The (optional) label (for SPEED, SLOPE etc)
double myOffset
The offset of the sign from the start of its edge.
SignType myType
the type of the sign
Static Private Attributes
static StringBijection< SignType > SignTypeColors
static StringBijection< SignType > SignTypeStrings
Detailed Description
A class representing a single street sign.
Definition at line 50 of file NBSign.h.
Member Enumeration Documentation
SignType
enum NBSign::SignType
Enumerator
SIGN_TYPE_SPEED
SIGN_TYPE_YIELD
SIGN_TYPE_STOP
SIGN_TYPE_ALLWAY_STOP
SIGN_TYPE_ON_RAMP
SIGN_TYPE_PRIORITY
SIGN_TYPE_RIGHT_BEFORE_LEFT
SIGN_TYPE_ROUNDABOUT
SIGN_TYPE_RAIL_CROSSING
SIGN_TYPE_SLOPE
SIGN_TYPE_CITY
SIGN_TYPE_INFO
Definition at line 53 of file NBSign.h.
Constructor & Destructor Documentation
NBSign()
NBSign::NBSign (SignType type, double offset, const std::string label = "")
Constructor with id, and position.
Parameters
[in] type The type of the sign
[in] offset The offset of the sign from the start of its edge
[in] label The (optional) label (for SPEED, SLOPE etc)
Definition at line 66 of file NBSign.cpp.
~NBSign()
NBSign::~NBSign ()
Destructor.
Definition at line 73 of file NBSign.cpp.
Member Function Documentation
writeAsPOI()
void NBSign::writeAsPOI (OutputDevice & into, const NBEdge * edge) const
write into device as POI positioned relative to the given edge
XXX
Todo:
add default colors
Definition at line 77 of file NBSign.cpp.
References RGBColor::BLUE, OutputDevice::closeTag(), Named::getID(), NBEdge::getLanes(), StringBijection< T >::getString(), RGBColor::GREY, PositionVector::move2side(), myOffset, myType, OutputDevice::openTag(), PositionVector::positionAtOffset(), RGBColor::RED, SIGN_TYPE_ALLWAY_STOP, SIGN_TYPE_CITY, SIGN_TYPE_INFO, SIGN_TYPE_ON_RAMP, SIGN_TYPE_PRIORITY, SIGN_TYPE_RAIL_CROSSING, SIGN_TYPE_RIGHT_BEFORE_LEFT, SIGN_TYPE_ROUNDABOUT, SIGN_TYPE_SLOPE, SIGN_TYPE_SPEED, SIGN_TYPE_STOP, SIGN_TYPE_YIELD, SignTypeStrings, SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_ID, SUMO_ATTR_TYPE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_POI, toString(), OutputDevice::writeAttr(), Position::x(), Position::y(), and RGBColor::YELLOW.
Field Documentation
myLabel
std::string NBSign::myLabel private
The (optional) label (for SPEED, SLOPE etc)
Definition at line 92 of file NBSign.h.
myOffset
double NBSign::myOffset private
The offset of the sign from the start of its edge.
Definition at line 89 of file NBSign.h.
Referenced by writeAsPOI().
myType
SignType NBSign::myType private
the type of the sign
Definition at line 86 of file NBSign.h.
Referenced by writeAsPOI().
SignTypeColors
StringBijection<SignType> NBSign::SignTypeColors static private
Definition at line 95 of file NBSign.h.
SignTypeStrings
StringBijection< NBSign::SignType > NBSign::SignTypeStrings static private
Definition at line 94 of file NBSign.h.
Referenced by writeAsPOI().
The documentation for this class was generated from the following files:
NBSign.h
NBSign.cpp