SUMO - Simulation of Urban MObility: PHEMlightdll::CEPHandler Class Reference
PHEMlightdll::CEPHandler Class Reference
#include <CEPHandler.h>
Public Member Functions
CEPHandler ()
bool GetCEP (const std::vector< std::string > &DataPath, Helpers *Helper)
const std::map< std::string, CEP * > & getCEPS () const
Private Member Functions
bool Load (const std::vector< std::string > &DataPath, Helpers *Helper)
bool ReadEmissionData (bool readFC, const std::vector< std::string > &DataPath, const std::string &emissionClass, Helpers *Helper, std::vector< std::string > &header, std::vector< std::vector< double > > &matrix, std::vector< double > &idlingValues)
std::string ReadLine (std::ifstream &s)
bool ReadVehicleFile (const std::vector< std::string > &DataPath, const std::string &emissionClass, Helpers *Helper, double &vehicleMass, double &vehicleLoading, double &vehicleMassRot, double &crossArea, double &cWValue, double &f0, double &f1, double &f2, double &f3, double &f4, double &axleRatio, double &auxPower, double &ratedPower, double &engineIdlingSpeed, double &engineRatedSpeed, double &effectiveWheelDiameter, std::vector< double > &transmissionGearRatios, std::string &vehicleMassType, std::string &vehicleFuelType, double &pNormV0, double &pNormP0, double &pNormV1, double &pNormP1, std::vector< std::vector< double > > &matrixSpeedInertiaTable, std::vector< std::vector< double > > &normedDragTable)
std::vector< std::string > split (const std::string &s, char delim)
double todouble (const std::string &s)
std::vector< double > todoubleList (const std::vector< std::string > &s)
Private Attributes
std::map< std::string, CEP * > _ceps
Detailed Description
Definition at line 38 of file CEPHandler.h.
Constructor & Destructor Documentation
CEPHandler()
PHEMlightdll::CEPHandler::CEPHandler ()
Definition at line 34 of file CEPHandler.cpp.
References _ceps.
Member Function Documentation
GetCEP()
bool PHEMlightdll::CEPHandler::GetCEP (const std::vector< std::string > & DataPath, Helpers * Helper)
Definition at line 42 of file CEPHandler.cpp.
References getCEPS(), PHEMlightdll::Helpers::getgClass(), and Load().
Referenced by HelpersPHEMlight::getClassByName().
getCEPS()
const std::map< std::string, CEP * > & PHEMlightdll::CEPHandler::getCEPS () const
Definition at line 38 of file CEPHandler.cpp.
References _ceps.
Referenced by GetCEP(), and HelpersPHEMlight::getClassByName().
Load()
bool PHEMlightdll::CEPHandler::Load (const std::vector< std::string > & DataPath, Helpers * Helper) private
Definition at line 51 of file CEPHandler.cpp.
References _ceps, PHEMlightdll::Helpers::getgClass(), PHEMlightdll::Constants::HeavyVehicle, ReadEmissionData(), and ReadVehicleFile().
Referenced by GetCEP().
ReadEmissionData()
bool PHEMlightdll::CEPHandler::ReadEmissionData (bool readFC, const std::vector< std::string > & DataPath, const std::string & emissionClass, Helpers * Helper, std::vector< std::string > & header, std::vector< std::vector< double > > & matrix, std::vector< double > & idlingValues) private
Definition at line 298 of file CEPHandler.cpp.
References ReadLine(), PHEMlightdll::Helpers::setErrMsg(), split(), and todoubleList().
Referenced by Load().
ReadLine()
std::string PHEMlightdll::CEPHandler::ReadLine (std::ifstream & s) private
Definition at line 376 of file CEPHandler.cpp.
Referenced by ReadEmissionData(), and ReadVehicleFile().
ReadVehicleFile()
bool PHEMlightdll::CEPHandler::ReadVehicleFile (const std::vector< std::string > & DataPath, const std::string & emissionClass, Helpers * Helper, double & vehicleMass, double & vehicleLoading, double & vehicleMassRot, double & crossArea, double & cWValue, double & f0, double & f1, double & f2, double & f3, double & f4, double & axleRatio, double & auxPower, double & ratedPower, double & engineIdlingSpeed, double & engineRatedSpeed, double & effectiveWheelDiameter, std::vector< double > & transmissionGearRatios, std::string & vehicleMassType, std::string & vehicleFuelType, double & pNormV0, double & pNormP0, double & pNormV1, double & pNormP1, std::vector< std::vector< double > > & matrixSpeedInertiaTable, std::vector< std::vector< double > > & normedDragTable) private
Definition at line 108 of file CEPHandler.cpp.
References PHEMlightdll::Helpers::getCommentPrefix(), ReadLine(), PHEMlightdll::Helpers::setErrMsg(), split(), todouble(), and todoubleList().
Referenced by Load().
split()
std::vector< std::string > PHEMlightdll::CEPHandler::split (const std::string & s, char delim) private
Definition at line 351 of file CEPHandler.cpp.
Referenced by ReadEmissionData(), and ReadVehicleFile().
todouble()
double PHEMlightdll::CEPHandler::todouble (const std::string & s) private
Definition at line 361 of file CEPHandler.cpp.
Referenced by ReadVehicleFile(), and todoubleList().
todoubleList()
std::vector< double > PHEMlightdll::CEPHandler::todoubleList (const std::vector< std::string > & s) private
Definition at line 368 of file CEPHandler.cpp.
References todouble().
Referenced by ReadEmissionData(), and ReadVehicleFile().
Field Documentation
_ceps
std::map<std::string, CEP*> PHEMlightdll::CEPHandler::_ceps private
Definition at line 51 of file CEPHandler.h.
Referenced by CEPHandler(), getCEPS(), and Load().
The documentation for this class was generated from the following files:
CEPHandler.h
CEPHandler.cpp