SUMO - Simulation of Urban MObility: NIImporter_SUMO::EdgeAttrs Struct Reference
NIImporter_SUMO::EdgeAttrs Struct Reference
Describes the values found in an edge's definition and this edge's lanes.
Public Member Functions
void clearParameter ()
Clears the parameter map.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Data Fields
NBEdge * builtEdge
The built edge.
std::string fromNode
The node this edge starts at.
SumoXMLEdgeFunc func
This edge's function.
std::string id
This edge's id.
std::vector< LaneAttrs * > lanes
This edge's lanes.
double length
The length of the edge if set explicitly.
LaneSpreadFunction lsf
The lane spread function.
double maxSpeed
The maximum velocity allowed on this edge (!!!)
int priority
This edge's priority.
PositionVector shape
This edges's shape.
std::string streetName
This edge's street name.
std::string toNode
The node this edge ends at.
std::string type
This edge's type.
Detailed Description
Describes the values found in an edge's definition and this edge's lanes.
Definition at line 235 of file NIImporter_SUMO.h.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
builtEdge
NBEdge* NIImporter_SUMO::EdgeAttrs::builtEdge
The built edge.
Definition at line 259 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
fromNode
std::string NIImporter_SUMO::EdgeAttrs::fromNode
The node this edge starts at.
Definition at line 245 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
func
SumoXMLEdgeFunc NIImporter_SUMO::EdgeAttrs::func
This edge's function.
Definition at line 243 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addConnection(), NIImporter_SUMO::addEdge(), and NIImporter_SUMO::addLane().
id
std::string NIImporter_SUMO::EdgeAttrs::id
This edge's id.
Definition at line 237 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addEdge(), NIImporter_SUMO::addLane(), NIImporter_SUMO::getLaneAttrsFromID(), NIImporter_SUMO::myEndElement(), and NIImporter_SUMO::reconstructEdgeShape().
lanes
std::vector<LaneAttrs*> NIImporter_SUMO::EdgeAttrs::lanes
This edge's lanes.
Definition at line 257 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addConnection(), NIImporter_SUMO::getLaneAttrsFromID(), NIImporter_SUMO::myEndElement(), NIImporter_SUMO::reconstructEdgeShape(), and NIImporter_SUMO::~NIImporter_SUMO().
length
double NIImporter_SUMO::EdgeAttrs::length
The length of the edge if set explicitly.
Definition at line 251 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
lsf
LaneSpreadFunction NIImporter_SUMO::EdgeAttrs::lsf
The lane spread function.
Definition at line 261 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addEdge(), and NIImporter_SUMO::reconstructEdgeShape().
maxSpeed
double NIImporter_SUMO::EdgeAttrs::maxSpeed
The maximum velocity allowed on this edge (!!!)
Definition at line 255 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addEdge(), and NIImporter_SUMO::myEndElement().
priority
int NIImporter_SUMO::EdgeAttrs::priority
This edge's priority.
Definition at line 253 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
shape
PositionVector NIImporter_SUMO::EdgeAttrs::shape
This edges's shape.
Definition at line 249 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
streetName
std::string NIImporter_SUMO::EdgeAttrs::streetName
This edge's street name.
Definition at line 239 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
toNode
std::string NIImporter_SUMO::EdgeAttrs::toNode
The node this edge ends at.
Definition at line 247 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
type
std::string NIImporter_SUMO::EdgeAttrs::type
This edge's type.
Definition at line 241 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addEdge().
The documentation for this struct was generated from the following file:
NIImporter_SUMO.h