SUMO - Simulation of Urban MObility: GNESelectorFrame Class Reference
GNESelectorFrame Class Reference
#include <GNESelectorFrame.h>
Data Structures
struct ObjectTypeEntry
Public Types
enum SetOperation {
SET_ADD = 1, SET_SUB = 2, SET_RESTRICT = 3, SET_REPLACE = 4,
SET_DEFAULT = 5
}
FOX-declaration.
Public Member Functions
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNESelectorFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
void handleIDs (std::vector< GUIGlID > ids, bool selectEdgesEnabled, SetOperation setop=SET_DEFAULT)
apply list of ids to the current selection according to SetOperation,
void hide ()
hide Frame
bool locked (GUIGlObjectType type)
void selectionUpdated ()
called if currently registered for updates for changes of global selection
void setFrameWidth (int newWidth)
set width of GNEFrame
void show ()
show Frame
~GNESelectorFrame ()
Destructor.
FOX-callbacks
called when user change type of selction operation
long onCmdSelectOperation (FXObject *, FXSelector, void *)
long onCmdSubset (FXObject *, FXSelector, void *)
Called when the user change the type of element to search (netElement or Additional)
long onCmdLoad (FXObject *, FXSelector, void *)
Called when the user presses the Load-button.
long onCmdSave (FXObject *, FXSelector, void *)
Called when the user presses the Save-button.
long onCmdClear (FXObject *, FXSelector, void *)
Called when the user presses the Clear-button.
long onCmdInvert (FXObject *, FXSelector, void *)
Called when the user presses the Invert-button.
long onCmdSelMBTag (FXObject *, FXSelector, void *)
Called when the user selectes a tag in the match box.
long onCmdSelMBAttribute (FXObject *, FXSelector, void *)
Called when the user selectes a tag in the match box.
long onCmdSelMBString (FXObject *, FXSelector, void *)
Called when the user enters a new selection expression.
long onCmdHelp (FXObject *, FXSelector, void *)
Called when the user clicks the help button.
long onCmdScaleSelection (FXObject *, FXSelector, void *)
Called when the user changes visual scaling.
Protected Member Functions
GNESelectorFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Member Functions
std::vector< GUIGlID > getMatches (SumoXMLTag ACTag, SumoXMLAttr ACAttr, char compOp, double val, const std::string &expr)
return objects of the given type with matching attrs
Private Attributes
FXRadioButton * myAddRadioButton
add radio button
SumoXMLAttr myCurrentAttribute
current SumoXMLTag Attribute
SumoXMLTag myCurrentTag
current SumoXMLTag tag
FXRadioButton * myKeepRadioButton
keep button
FXComboBox * myMatchAttrComboBox
attributes of the match box
FXTextField * myMatchString
string of the match
FXComboBox * myMatchTagComboBox
tag of the match box
FXRadioButton * myRemoveRadioButton
remove radio button
FXRadioButton * myReplaceRadioButton
replace radio button
FXRealSpinDial * mySelectionScaling
selection scaling
FXComboBox * mySetComboBox
tag of the sets of elements
SetOperation mySetOperation
how to modify selection
std::map< GUIGlObjectType, ObjectTypeEntry > myTypeEntries
check boxes for type-based selection locking and selected object counts
Detailed Description
The Widget for modifying selections of network-elements
Definition at line 46 of file GNESelectorFrame.h.
Member Enumeration Documentation
SetOperation
enum GNESelectorFrame::SetOperation
FOX-declaration.
operations of selector
Enumerator
SET_ADD
SET_SUB
SET_RESTRICT
SET_REPLACE
SET_DEFAULT
Definition at line 52 of file GNESelectorFrame.h.
Constructor & Destructor Documentation
GNESelectorFrame() [1/2]
GNESelectorFrame::GNESelectorFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 87 of file GNESelectorFrame.cpp.
References GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, GUIDesignButton, GUIDesignButtonRectangular, GUIDesignComboBox, GUIDesignComboBoxNCol, GUIDesignGroupBoxFrame, GUIDesignLabelFrameInformation, GUIDesignRadioButton, GUIDesignSpinDial, GUIDesignTextField, GUIDesignTextFieldNCol, MID_CHOOSEN_CLEAR, MID_CHOOSEN_ELEMENTS, MID_CHOOSEN_INVERT, MID_CHOOSEN_LOAD, MID_CHOOSEN_OPERATION, MID_CHOOSEN_SAVE, MID_GNE_SELECTORFRAME_PROCESSSTRING, MID_GNE_SELECTORFRAME_SELECTATTRIBUTE, MID_GNE_SELECTORFRAME_SELECTSCALE, MID_GNE_SELECTORFRAME_SELECTTAG, MID_HELP, myAddRadioButton, GNEFrame::myContentFrame, myCurrentAttribute, myCurrentTag, myKeepRadioButton, myMatchAttrComboBox, myMatchString, myMatchTagComboBox, myRemoveRadioButton, myReplaceRadioButton, mySelectionScaling, mySetComboBox, myTypeEntries, onCmdSubset(), FX::FXRealSpinDial::setHelpText(), FX::FXRealSpinDial::setIncrements(), FX::FXRealSpinDial::setNumberFormat(), FX::FXRealSpinDial::setRange(), FX::FXRealSpinDial::setValue(), SUMO_ATTR_SPEED, and SUMO_TAG_EDGE.
~GNESelectorFrame()
GNESelectorFrame::~GNESelectorFrame ()
Destructor.
Definition at line 168 of file GNESelectorFrame.cpp.
References gSelected, and GUISelectedStorage::remove2Update().
GNESelectorFrame() [2/2]
GNESelectorFrame::GNESelectorFrame () inline protected
FOX needs this.
Definition at line 143 of file GNESelectorFrame.h.
Member Function Documentation
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getMatches()
std::vector< GUIGlID > GNESelectorFrame::getMatches (SumoXMLTag ACTag, SumoXMLAttr ACAttr, char compOp, double val, const std::string & expr) private
return objects of the given type with matching attrs
Parameters
[in] ACTag XML Tag of AttributeCarrier
[in] ACAttr XML Attribute of AttributeCarrier
[in] compOp One of {<,>,=} for matching against val or '@' for matching against expr
Definition at line 687 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::getAttribute(), GNEAttributeCarrier::getAttributeForSelection(), GNENet::getGlIDs(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GUIGlObjectStorage::gIDStorage, GNEAttributeCarrier::isNumerical(), GNEFrame::myViewNet, GNENet::retrieveAttributeCarrier(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdSelMBString().
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
handleIDs()
void GNESelectorFrame::handleIDs (std::vector< GUIGlID > ids, bool selectEdgesEnabled, SetOperation setop = SET_DEFAULT)
apply list of ids to the current selection according to SetOperation,
Note
if setop==SET_DEFAULT than the currently set mode (mySetOperation) is used
Definition at line 613 of file GNESelectorFrame.cpp.
References GNEViewNet::autoSelectNodes(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEViewNet::getNet(), GUIGlObjectStorage::getObjectBlocking(), GUISelectedStorage::getSelected(), GUIGlObject::getType(), GNEViewNet::getUndoList(), GUIGlObjectStorage::gIDStorage, GLO_EDGE, GLO_LANE, gSelected, locked(), mySetOperation, myTypeEntries, GNEFrame::myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), SET_ADD, SET_DEFAULT, SET_REPLACE, SET_RESTRICT, SET_SUB, and GUIGlObjectStorage::unblockObject().
Referenced by locked(), onCmdLoad(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), onCmdSelMBString(), and GNEViewNet::onLeftBtnRelease().
hide()
void GNESelectorFrame::hide () virtual
hide Frame
Reimplemented from GNEFrame.
Definition at line 576 of file GNESelectorFrame.cpp.
References gSelected, GNEFrame::hide(), and GUISelectedStorage::remove2Update().
locked()
bool GNESelectorFrame::locked (GUIGlObjectType type) inline
Definition at line 129 of file GNESelectorFrame.h.
References handleIDs(), myTypeEntries, selectionUpdated(), and SET_DEFAULT.
Referenced by handleIDs(), and GNEViewNet::onLeftBtnPress().
onCmdClear()
long GNESelectorFrame::onCmdClear (FXObject * , FXSelector , void *)
Called when the user presses the Clear-button.
Note
Clear the internal list and calls GUISelectedStorage::clear and repaints itself
Definition at line 327 of file GNESelectorFrame.cpp.
References GNEViewNet::getNet(), GUISelectedStorage::getSelected(), GNEViewNet::getUndoList(), gSelected, GNEFrame::myViewNet, GNEUndoList::p_begin(), and GNEUndoList::p_end().
onCmdHelp()
long GNESelectorFrame::onCmdHelp (FXObject * , FXSelector , void *)
Called when the user clicks the help button.
Note
pop up help window
Definition at line 524 of file GNESelectorFrame.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonOK, GUIDesignDialogBox, GUIDesignLabelFrameInformation, and ICON_ACCEPT.
onCmdInvert()
long GNESelectorFrame::onCmdInvert (FXObject * , FXSelector , void *)
Called when the user presses the Invert-button.
Note
invert the selection and repaints itself
Definition at line 337 of file GNESelectorFrame.cpp.
References GNEPOI::getGlID(), GNEPoly::getGlID(), GNENet::getGlIDs(), GNEViewNet::getNet(), ShapeContainer::getPOIs(), ShapeContainer::getPolygons(), GUISelectedStorage::getSelected(), GNEViewNet::getUndoList(), GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, gSelected, GUISelectedStorage::isSelected(), GNEFrame::myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), and GNEViewNet::selectEdges().
onCmdLoad()
long GNESelectorFrame::onCmdLoad (FXObject * , FXSelector , void *)
Called when the user presses the Load-button.
Note
Opens a file dialog and forces the parent to load the list of selected objects when a file was chosen. Rebuilds the list, then, and redraws itself.
Definition at line 267 of file GNESelectorFrame.cpp.
References gCurrentFolder, OptionsCont::getBool(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), gSelected, handleIDs(), ICON_EMPTY, GUISelectedStorage::loadIDs(), GNEFrame::myViewNet, and WRITE_WARNING.
onCmdSave()
long GNESelectorFrame::onCmdSave (FXObject * , FXSelector , void *)
Called when the user presses the Save-button.
Note
Opens a file dialog and forces the selection container to save the list of selected objects when a file was chosen. If the saveing failed, a message window is shown.
Definition at line 302 of file GNESelectorFrame.cpp.
References gCurrentFolder, OptionsCont::getBool(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), gSelected, ICON_EMPTY, GUISelectedStorage::save(), and WRITE_WARNING.
onCmdScaleSelection()
long GNESelectorFrame::onCmdScaleSelection (FXObject * , FXSelector , void *)
Called when the user changes visual scaling.
Definition at line 558 of file GNESelectorFrame.cpp.
References FX::FXRealSpinDial::getValue(), mySelectionScaling, GNEFrame::myViewNet, and GNEViewNet::setSelectionScaling().
onCmdSelectOperation()
long GNESelectorFrame::onCmdSelectOperation (FXObject * obj, FXSelector , void *)
Definition at line 174 of file GNESelectorFrame.cpp.
References myAddRadioButton, myKeepRadioButton, myRemoveRadioButton, myReplaceRadioButton, mySetOperation, SET_ADD, SET_REPLACE, SET_RESTRICT, and SET_SUB.
onCmdSelMBAttribute()
long GNESelectorFrame::onCmdSelMBAttribute (FXObject * , FXSelector , void *)
Called when the user selectes a tag in the match box.
Note
updates the attr listbox and repaints itself
Definition at line 453 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::allowedAttributes(), myCurrentAttribute, myCurrentTag, myMatchAttrComboBox, myMatchString, SUMO_ATTR_NOTHING, and toString().
Referenced by onCmdSelMBTag().
onCmdSelMBString()
long GNESelectorFrame::onCmdSelMBString (FXObject * , FXSelector , void *)
Called when the user enters a new selection expression.
Note
validates expression and modifies current selection
Definition at line 473 of file GNESelectorFrame.cpp.
References getMatches(), handleIDs(), GNEAttributeCarrier::isNumerical(), myCurrentAttribute, myCurrentTag, and myMatchString.
onCmdSelMBTag()
long GNESelectorFrame::onCmdSelMBTag (FXObject * , FXSelector , void *)
Called when the user selectes a tag in the match box.
Note
updates the attr listbox and repaints itself
Definition at line 403 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedNetElementsTags(), GNEAttributeCarrier::allowedShapeTags(), myCurrentTag, myMatchAttrComboBox, myMatchString, myMatchTagComboBox, mySetComboBox, onCmdSelMBAttribute(), SUMO_TAG_NOTHING, and toString().
Referenced by onCmdSubset().
onCmdSubset()
long GNESelectorFrame::onCmdSubset (FXObject * , FXSelector , void *)
Called when the user change the type of element to search (netElement or Additional)
Definition at line 210 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedNetElementsTags(), GNEAttributeCarrier::allowedShapeTags(), myMatchAttrComboBox, myMatchString, myMatchTagComboBox, mySetComboBox, onCmdSelMBTag(), and toString().
Referenced by GNESelectorFrame().
selectionUpdated()
void GNESelectorFrame::selectionUpdated () virtual
called if currently registered for updates for changes of global selection
Implements GUISelectedStorage::UpdateTarget.
Definition at line 585 of file GNESelectorFrame.cpp.
References OptionsCont::getOptions(), GUISelectedStorage::getSelected(), GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, gSelected, myTypeEntries, toString(), and WRITE_WARNING.
Referenced by locked(), and show().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
show()
void GNESelectorFrame::show () virtual
show Frame
Reimplemented from GNEFrame.
Definition at line 566 of file GNESelectorFrame.cpp.
References GUISelectedStorage::add2Update(), gSelected, selectionUpdated(), and GNEFrame::show().
Referenced by GNEViewNet::updateModeSpecificControls().
Field Documentation
myAddRadioButton
FXRadioButton* GNESelectorFrame::myAddRadioButton private
add radio button
Definition at line 150 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), and onCmdSelectOperation().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myCurrentAttribute
SumoXMLAttr GNESelectorFrame::myCurrentAttribute private
current SumoXMLTag Attribute
Definition at line 180 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), onCmdSelMBAttribute(), and onCmdSelMBString().
myCurrentTag
SumoXMLTag GNESelectorFrame::myCurrentTag private
current SumoXMLTag tag
Definition at line 177 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), onCmdSelMBAttribute(), onCmdSelMBString(), and onCmdSelMBTag().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myKeepRadioButton
FXRadioButton* GNESelectorFrame::myKeepRadioButton private
keep button
Definition at line 156 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), and onCmdSelectOperation().
myMatchAttrComboBox
FXComboBox* GNESelectorFrame::myMatchAttrComboBox private
attributes of the match box
Definition at line 168 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), onCmdSelMBAttribute(), onCmdSelMBTag(), and onCmdSubset().
myMatchString
FXTextField* GNESelectorFrame::myMatchString private
string of the match
Definition at line 171 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), onCmdSelMBAttribute(), onCmdSelMBString(), onCmdSelMBTag(), and onCmdSubset().
myMatchTagComboBox
FXComboBox* GNESelectorFrame::myMatchTagComboBox private
tag of the match box
Definition at line 165 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), onCmdSelMBTag(), and onCmdSubset().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myRemoveRadioButton
FXRadioButton* GNESelectorFrame::myRemoveRadioButton private
remove radio button
Definition at line 153 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), and onCmdSelectOperation().
myReplaceRadioButton
FXRadioButton* GNESelectorFrame::myReplaceRadioButton private
replace radio button
Definition at line 159 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), and onCmdSelectOperation().
mySelectionScaling
FXRealSpinDial* GNESelectorFrame::mySelectionScaling private
selection scaling
Definition at line 174 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), and onCmdScaleSelection().
mySetComboBox
FXComboBox* GNESelectorFrame::mySetComboBox private
tag of the sets of elements
Definition at line 162 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), onCmdSelMBTag(), and onCmdSubset().
mySetOperation
SetOperation GNESelectorFrame::mySetOperation private
how to modify selection
Definition at line 147 of file GNESelectorFrame.h.
Referenced by handleIDs(), and onCmdSelectOperation().
myTypeEntries
std::map<GUIGlObjectType, ObjectTypeEntry> GNESelectorFrame::myTypeEntries private
check boxes for type-based selection locking and selected object counts
Definition at line 191 of file GNESelectorFrame.h.
Referenced by GNESelectorFrame(), handleIDs(), locked(), and selectionUpdated().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), onCmdInvert(), onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNESelectorFrame.h
GNESelectorFrame.cpp