SUMO - Simulation of Urban MObility: MSFrame Class Reference
MSFrame Class Reference
Sets and checks options for microsim; inits global outputs and settings.
#include <MSFrame.h>
Static Public Member Functions
static void buildStreams ()
Builds the streams used possibly by the simulation.
static bool checkOptions ()
Checks the set options.
static void fillOptions ()
Inserts options used by the simulation into the OptionsCont-singleton.
static void setMSGlobals (OptionsCont &oc)
Sets the global microsim-options.
Detailed Description
Sets and checks options for microsim; inits global outputs and settings.
In addition to setting and checking options, this frame also sets global values via "setMSGlobals". They are stored in MSGlobals.
Also, global output streams are initialised within "buildStreams".
See also
MSGlobals
Definition at line 56 of file MSFrame.h.
Member Function Documentation
buildStreams()
void MSFrame::buildStreams () static
Builds the streams used possibly by the simulation.
Definition at line 484 of file MSFrame.cpp.
References OutputDevice::createDeviceByOption(), DELTA_T, MSStopOut::init(), MSDevice_Vehroutes::init(), STEPS2MS, and toString().
Referenced by NLBuilder::buildNet().
checkOptions()
bool MSFrame::checkOptions () static
Checks the set options.
The following constraints must be valid:
the network-file was specified (otherwise no simulation is existing)
the begin and the end of the simulation must be given
The default lane change model must be known If one is not, false is returned.
Returns
Whether the settings are valid
Todo:
Rechek usage of the lane change model
probably, more things should be checked...
Definition at line 515 of file MSFrame.cpp.
References SUMOXMLDefinitions::CarFollowModels, SystemFrame::checkOptions(), MSDevice::checkOptions(), OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getInt(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isDefault(), OptionsCont::isSet(), OptionsCont::isUsableFileList(), OptionsCont::set(), string2time(), toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by NLBuilder::init(), and GUILoadThread::run().
fillOptions()
void MSFrame::fillOptions () static
Inserts options used by the simulation into the OptionsCont-singleton.
Device-options are inserted by calling the device's "insertOptions" -methods.
!! check, describe
!! check, describe
Definition at line 66 of file MSFrame.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::addXMLDefault(), OptionsCont::doRegister(), OptionsCont::getOptions(), MSDevice::insertOptions(), and RandHelper::insertRandOptions().
Referenced by NLBuilder::init(), main(), and GUILoadThread::run().
setMSGlobals()
void MSFrame::setMSGlobals (OptionsCont & oc) static
Sets the global microsim-options.
Parameters
[in] oc The options container to get the values from
See also
MSGlobals
Definition at line 615 of file MSFrame.cpp.
References DELTA_T, MSGlobals::gActionStepLength, MSGlobals::gCheck4Accidents, MSGlobals::gCheckRoutes, OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getString(), MSGlobals::gIgnoreJunctionBlocker, MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, MSGlobals::gMesoLimitedJunctionControl, MSGlobals::gMesoMinorPenalty, MSGlobals::gMesoOvertaking, MSGlobals::gMesoTLSPenalty, MSGlobals::gOmitEmptyEdgesOnDump, MSGlobals::gSemiImplicitEulerUpdate, MSGlobals::gStateLoaded, MSGlobals::gTimeToGridlock, MSGlobals::gTimeToGridlockHighways, MSGlobals::gTimeToImpatience, MSGlobals::gUseMesoSim, MSGlobals::gUsingInternalLanes, MSGlobals::gWaitingTimeMemory, MSLane::initCollisionOptions(), MSAbstractLaneChangeModel::initGlobalOptions(), OptionsCont::isDefault(), OptionsCont::isSet(), SUMOVehicleParserHelper::processActionStepLength(), string2time(), and WRITE_MESSAGE.
Referenced by NLBuilder::init(), and GUILoadThread::run().
The documentation for this class was generated from the following files:
MSFrame.h
MSFrame.cpp