SUMO - Simulation of Urban MObility: PlainXMLFormatter Class Reference
PlainXMLFormatter Class Reference
Output formatter for plain XML output.
#include <PlainXMLFormatter.h>
Public Member Functions
bool closeTag (std::ostream &into)
Closes the most recently opened tag.
void openTag (std::ostream &into, const std::string &xmlElement)
Opens an XML tag.
void openTag (std::ostream &into, const SumoXMLTag &xmlElement)
Opens an XML tag.
PlainXMLFormatter (const int defaultIndentation=0)
Constructor.
bool writeHeader (std::ostream &into, const SumoXMLTag &rootElement)
Writes an XML header with optional configuration.
void writePreformattedTag (std::ostream &into, const std::string &val)
writes a preformatted tag to the device but ensures that any pending tags are closed
bool writeXMLHeader (std::ostream &into, const std::string &rootElement, const std::map< SumoXMLAttr, std::string > &attrs)
Writes an XML header with optional configuration.
virtual ~PlainXMLFormatter ()
Destructor.
Static Public Member Functions
template<class T >
static void writeAttr (std::ostream &into, const std::string &attr, const T &val)
writes an arbitrary attribute
template<class T >
static void writeAttr (std::ostream &into, const SumoXMLAttr attr, const T &val)
writes a named attribute
Private Attributes
int myDefaultIndentation
The initial indentation level.
bool myHavePendingOpener
whether a closing ">" might be missing
std::vector< std::string > myXMLStack
The stack of begun xml elements.
Detailed Description
Output formatter for plain XML output.
PlainXMLFormatter format XML like output into the output stream.
Definition at line 45 of file PlainXMLFormatter.h.
Constructor & Destructor Documentation
PlainXMLFormatter()
PlainXMLFormatter::PlainXMLFormatter (const int defaultIndentation = 0)
Constructor.
Definition at line 39 of file PlainXMLFormatter.cpp.
~PlainXMLFormatter()
virtual PlainXMLFormatter::~PlainXMLFormatter () inline virtual
Destructor.
Definition at line 52 of file PlainXMLFormatter.h.
References closeTag(), openTag(), writeHeader(), writePreformattedTag(), and writeXMLHeader().
Member Function Documentation
closeTag()
bool PlainXMLFormatter::closeTag (std::ostream & into) virtual
Closes the most recently opened tag.
Parameters
[in] into The output stream to use
Returns
Whether a further element existed in the stack and could be closed
Todo:
it is not verified that the topmost element was closed
Implements OutputFormatter.
Definition at line 90 of file PlainXMLFormatter.cpp.
References myDefaultIndentation, myHavePendingOpener, and myXMLStack.
Referenced by ~PlainXMLFormatter().
openTag() [1/2]
void PlainXMLFormatter::openTag (std::ostream & into, const std::string & xmlElement) virtual
Opens an XML tag.
An indentation, depending on the current xml-element-stack size, is written followed by the given xml element ("<" + xmlElement) The xml element is added to the stack, then.
Parameters
[in] into The output stream to use
[in] xmlElement Name of element to open
Returns
The OutputDevice for further processing
Implements OutputFormatter.
Definition at line 73 of file PlainXMLFormatter.cpp.
References myDefaultIndentation, myHavePendingOpener, and myXMLStack.
Referenced by openTag(), writeHeader(), writeXMLHeader(), and ~PlainXMLFormatter().
openTag() [2/2]
void PlainXMLFormatter::openTag (std::ostream & into, const SumoXMLTag & xmlElement) virtual
Opens an XML tag.
Helper method which finds the correct string before calling openTag.
Parameters
[in] into The output stream to use
[in] xmlElement Id of the element to open
Implements OutputFormatter.
Definition at line 84 of file PlainXMLFormatter.cpp.
References openTag(), and toString().
writeAttr() [1/2]
template<class T > static void PlainXMLFormatter::writeAttr (std::ostream & into, const std::string & attr, const T & val) inline static
writes an arbitrary attribute
Parameters
[in] into The output stream to use
[in] attr The attribute (name)
[in] val The attribute value
Definition at line 127 of file PlainXMLFormatter.h.
References toString().
Referenced by OutputDevice::writeAttr(), and writeXMLHeader().
writeAttr() [2/2]
template<class T > static void PlainXMLFormatter::writeAttr (std::ostream & into, const SumoXMLAttr attr, const T & val) inline static
writes a named attribute
Parameters
[in] into The output stream to use
[in] attr The attribute (name)
[in] val The attribute value
Definition at line 139 of file PlainXMLFormatter.h.
References toString().
writeHeader()
bool PlainXMLFormatter::writeHeader (std::ostream & into, const SumoXMLTag & rootElement)
Writes an XML header with optional configuration.
If something has been written (myXMLStack is not empty), nothing is written and false returned.
Parameters
[in] into The output stream to use
[in] rootElement The root element to use
Definition at line 45 of file PlainXMLFormatter.cpp.
References OptionsCont::getOptions(), myXMLStack, openTag(), and OptionsCont::writeXMLHeader().
Referenced by ~PlainXMLFormatter().
writePreformattedTag()
void PlainXMLFormatter::writePreformattedTag (std::ostream & into, const std::string & val) virtual
writes a preformatted tag to the device but ensures that any pending tags are closed
Parameters
[in] into The output stream to use
[in] val The preformatted data
Implements OutputFormatter.
Definition at line 107 of file PlainXMLFormatter.cpp.
References myHavePendingOpener.
Referenced by ~PlainXMLFormatter().
writeXMLHeader()
bool PlainXMLFormatter::writeXMLHeader (std::ostream & into, const std::string & rootElement, const std::map< SumoXMLAttr, std::string > & attrs) virtual
Writes an XML header with optional configuration.
If something has been written (myXMLStack is not empty), nothing is written and false returned.
Parameters
[in] into The output stream to use
[in] rootElement The root element to use
[in] attrs Additional attributes to save within the rootElement
Todo:
Describe what is saved
Implements OutputFormatter.
Definition at line 56 of file PlainXMLFormatter.cpp.
References OptionsCont::getOptions(), myHavePendingOpener, myXMLStack, openTag(), writeAttr(), and OptionsCont::writeXMLHeader().
Referenced by ~PlainXMLFormatter().
Field Documentation
myDefaultIndentation
int PlainXMLFormatter::myDefaultIndentation private
The initial indentation level.
Definition at line 149 of file PlainXMLFormatter.h.
Referenced by closeTag(), and openTag().
myHavePendingOpener
bool PlainXMLFormatter::myHavePendingOpener private
whether a closing ">" might be missing
Definition at line 152 of file PlainXMLFormatter.h.
Referenced by closeTag(), openTag(), writePreformattedTag(), and writeXMLHeader().
myXMLStack
std::vector<std::string> PlainXMLFormatter::myXMLStack private
The stack of begun xml elements.
Definition at line 146 of file PlainXMLFormatter.h.
Referenced by closeTag(), openTag(), writeHeader(), and writeXMLHeader().
The documentation for this class was generated from the following files:
PlainXMLFormatter.h
PlainXMLFormatter.cpp