SUMO - Simulation of Urban MObility: SysUtils Class Reference
SysUtils Class Reference
A few system-specific functions.
#include <SysUtils.h>
Static Public Member Functions
static long getCurrentMillis ()
Returns the current time in milliseconds.
static unsigned long runHiddenCommand (const std::string &cmd)
run a shell command without popping up any windows (particuarly on win32)
Detailed Description
A few system-specific functions.
Definition at line 40 of file SysUtils.h.
Member Function Documentation
getCurrentMillis()
long SysUtils::getCurrentMillis () static
Returns the current time in milliseconds.
Returns
Current time
Definition at line 45 of file SysUtils.cpp.
Referenced by NLBuilder::build(), CHBuilder< E, V >::buildContractionHierarchy(), MSNet::closeBuilding(), MSNet::closeSimulation(), NBNetBuilder::compute(), SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery(), NLBuilder::load(), NBNetBuilder::moveToOrigin(), GUIRunThread::run(), MSNet::simulationStep(), SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery(), and NWFrame::writeNetwork().
runHiddenCommand()
unsigned long SysUtils::runHiddenCommand (const std::string & cmd) static
run a shell command without popping up any windows (particuarly on win32)
Definition at line 70 of file SysUtils.cpp.
References INFINITE.
Referenced by GUIApplicationWindow::checkGamingEvents(), and GUIApplicationWindow::onCmdNetedit().
The documentation for this class was generated from the following files:
SysUtils.h
SysUtils.cpp