SUMO - Simulation of Urban MObility: GUIMEVehicle Class Reference
GUIMEVehicle Class Reference
A MSVehicle extended by some values for usage within the gui.
#include <GUIMEVehicle.h>
Public Types
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
virtual void activateReminders (const MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
"Activates" all current move reminder
virtual void addContainer (MSTransportable *container)
Adds a container to this vehicle.
virtual void addPerson (MSTransportable *person)
Adds a person to this vehicle.
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0, bool collision=false, MSRouteIterator *searchStart=0)
Adds a stop.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
void createDevice (const std::string &deviceName)
create device of the given type
bool drawAction_drawCarriageClass (const GUIVisualizationSettings &s, SUMOVehicleShape guiShape, bool asImage) const
draws the given guiShape if it has distinc carriages/modules and eturns true if so
virtual void drawAction_drawLinkItems (const GUIVisualizationSettings &) const
virtual void drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &) const
virtual void drawAction_drawVehicleBlinker (double) const
virtual void drawAction_drawVehicleBlueLight () const
virtual void drawAction_drawVehicleBrakeLight (double length, bool onlyOne=false) const
virtual void drawBestLanes () const
Draws the vehicle's best lanes.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
void drawRouteHelper (const GUIVisualizationSettings &s, const MSRoute &r) const
Draws the route.
double estimateLeaveSpeed (const MSLink *link) const
Returns the vehicle's estimated speed after driving accross the link.
virtual double getAcceleration () const
Returns the vehicle's acceleration.
SUMOTime getAccumulatedWaitingTime () const
Returns the duration for which the vehicle was blocked.
double getAngle () const
Return current angle.
virtual double getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
double getAverageSpeed () const
Returns the vehicle's estimated average speed on the segment assuming no further delays.
double getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
SUMOTime getBlockTime () const
Returns the time at which the vehicle was blocked.
double getBlockTimeSeconds () const
Returns the time at which the vehicle was blocked on the current segment.
double getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
double getColorValue (int activeScheme) const
gets the color value according to the current scheme index
double getConservativeSpeed (SUMOTime &earliestArrival) const
Returns the vehicle's estimated speed taking into account delays.
double getCurrentLinkPenaltySeconds () const
Returns the delay that is accrued due to option –meso-tls-penalty or –meso-minor-penalty.
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
SUMOTime getDepartDelay () const
Returns the depart delay.
double getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
std::string getDeviceParameter (const std::string &deviceName, const std::string &key) const
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
SUMOTime getEventTime () const
Returns the (planned) time at which the vehicle leaves his current cell.
double getEventTimeSeconds () const
Returns the earliest leave time for the current segment.
const std::string & getID () const
Returns the name of the vehicle.
double getImpatience () const
Returns this vehicles impatience.
MSLane * getLane () const
Returns the lane the vehicle is on.
SUMOTime getLastEntryTime () const
Returns the time the vehicle entered the current segment.
double getLastEntryTimeSeconds () const
Returns the entry time for the current segment.
double getLastLaneChangeOffset () const
Returns the time since the last lane change in seconds.
virtual double getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
double getLength () const
Returns the vehicle's length.
double getMaxSpeed () const
Returns the maximum speed.
double getNaviDegree () const
return the current angle in navigational degrees
MSParkingArea * getNextParkingArea ()
get the current parking area stop
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Position getPosition (const double offset=0) const
Return current position (x/y, cartesian)
double getPositionOnLane () const
Get the vehicle's position along the lane.
double getPreviousSpeed () const
Returns the vehicle's previous speed.
int getQueIndex () const
Returns the index of the que the vehicle is in.
virtual const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
const MSRoute & getRoute () const
Returns the current route.
MESegment * getSegment () const
Returns the current segment the vehicle is on.
MSVehicleType & getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
double getSlope () const
Returns the slope of the road at vehicle's position.
double getSpeed () const
Returns the vehicle's estimated speed assuming no delays.
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
std::string getStopInfo () const
retrieve information about the current stop state
SUMOTime getStoptime (const MESegment *const seg) const
Returns how long to stop at the given segment.
GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
double getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
SUMOTime getWaitingTime () const
Returns the duration for which the vehicle was blocked.
double getWidth () const
Returns the vehicle's width.
GUIMEVehicle (SUMOVehicleParameter *pars, const MSRoute *route, MSVehicleType *type, const double speedFactor)
Constructor.
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasDevice (const std::string &deviceName) const
check whether the vehicle is equiped with a device of the given type
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
virtual bool isFrontOnLane (const MSLane *) const
Returns the information whether the front of the vehhicle is on the given lane.
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isParking () const
Returns whether the vehicle is parking.
virtual bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
virtual bool isSelected () const
whether this vehicle is selected in the GUI
bool isStopped () const
Returns whether the vehicle is at a stop.
bool isStoppedInRange (double pos) const
return whether the given position is within range of the current stop
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool mayProceed () const
Returns whether the vehicle is allowed to pass the next junction.
bool moveRoutePointer ()
Update when the vehicle enters a new edge in the move step.
void onDepart ()
Called when the vehicle is inserted into the network.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceParkingArea (MSParkingArea *, std::string &)
replace the current parking area stop with a new stop with merge duration
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0, bool addStops=true, bool removeStops=true)
Replaces the current route by the given one.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false, bool removeStops=true)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
void selectBlockingFoes () const
adds the blocking foes to the current selection
virtual void setArrivalPos (double arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setBlockTime (const SUMOTime t)
Sets the time at which the vehicle was blocked.
void setChosenSpeedFactor (const double factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setDeviceParameter (const std::string &deviceName, const std::string &key, const std::string &value)
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
void setEventTime (SUMOTime t, bool hasDelay=true)
Sets the (planned) time at which the vehicle leaves his current cell.
void setLastEntryTime (SUMOTime t)
Sets the entry time for the current segment.
virtual void setSegment (MESegment *s, int idx=0)
Sets the current segment the vehicle is at together with its que.
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
void updateDetectorForWriting (MSMoveReminder *rem, SUMOTime currentTime, SUMOTime exitTime)
Updates a single vehicle detector if present.
void updateDetectors (SUMOTime currentTime, const bool isLeave, const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_JUNCTION)
Updates all vehicle detectors.
~GUIMEVehicle ()
destructor
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawOnPos (const GUIVisualizationSettings &s, const Position &pos, const double angle) const
Draws the object on the specified position with the specified angle.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static bool setFunctionalColor (int activeScheme, const MSBaseVehicle *veh)
sets the color according to the current scheme index and some vehicle function
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
const Position & getSeatPosition (int personIndex) const
returns the seat position for the person with the given index
const MSVehicleType & getVType () const
A shortcut to myVehicle.myType.
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Member Functions
static void drawLinkItem (const Position &pos, SUMOTime arrivalTime, SUMOTime leaveTime, double exagerate)
Protected Attributes
int myArrivalLane
The destination lane where the vehicle stops.
double myArrivalPos
The position on the destination lane where the vehicle stops.
SUMOTime myBlockTime
The time at which the vehicle was blocked on its current segment.
double myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
double myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
SUMOTime myEventTime
The (planned) time of leaving the segment (cell)
SUMOTime myLastEntryTime
The time the vehicle entered its current segment.
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This vehicle's parameter.
int myQueIndex
Index of the que the vehicle is in (important for multiqueue extension)
const MSRoute * myRoute
This vehicle's route.
PositionVector mySeatPositions
positions of seats in the vehicle (updated at every drawing step)
MESegment * mySegment
The segment the vehicle is at.
std::map< const MESegment *const, SUMOTime > myStops
where to stop
MSVehicleType * myType
This vehicle's type.
Static Protected Attributes
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Additional visualisations
bool hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
void addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void drawRoute (const GUIVisualizationSettings &s, int routeNo, double darken) const
Chooses the route to draw and draws it, darkening it as given.
enum VisualisationFeatures {
VO_SHOW_BEST_LANES = 1, VO_SHOW_ROUTE = 2, VO_SHOW_ALL_ROUTES = 4, VO_SHOW_LFLINKITEMS = 8,
VO_DRAW_OUTSIDE_NETWORK = 16
}
Additional visualisation feature ids.
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
drawing helper methods
void drawAction_drawVehicleAsBoxPlus () const
void drawAction_drawVehicleAsTrianglePlus () const
bool drawAction_drawVehicleAsPoly (const GUIVisualizationSettings &s) const
bool drawAction_drawVehicleAsImage (const GUIVisualizationSettings &s, double length=-1) const
static void drawPoly (double *poses, double offset)
Move reminder structures
MoveReminderCont myMoveReminders
Currently relevant move reminders.
typedef std::vector< std::pair< MSMoveReminder *, double > > MoveReminderCont
Definition of a move reminder container.
Detailed Description
A MSVehicle extended by some values for usage within the gui.
A visualisable MSVehicle. Extended by the possibility to retrieve names of all available vehicles (static) and the possibility to retrieve the color of the vehicle which is available in different forms allowing an easier recognition of done actions such as lane changing.
Definition at line 61 of file GUIMEVehicle.h.
Member Typedef Documentation
ComparatorIdLess
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 79 of file SUMOVehicle.h.
MoveReminderCont
typedef std::vector< std::pair<MSMoveReminder*, double> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 468 of file MSBaseVehicle.h.
Member Enumeration Documentation
VisualisationFeatures
enum GUIBaseVehicle::VisualisationFeatures inherited
Additional visualisation feature ids.
Enumerator
VO_SHOW_BEST_LANES
show vehicle's best lanes
VO_SHOW_ROUTE
show vehicle's current route
VO_SHOW_ALL_ROUTES
show all vehicle's routes
VO_SHOW_LFLINKITEMS
LFLinkItems.
VO_DRAW_OUTSIDE_NETWORK
draw vehicle outside the road network
Definition at line 287 of file GUIBaseVehicle.h.
Constructor & Destructor Documentation
GUIMEVehicle()
GUIMEVehicle::GUIMEVehicle (SUMOVehicleParameter * pars, const MSRoute * route, MSVehicleType * type, const double speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 51 of file GUIMEVehicle.cpp.
~GUIMEVehicle()
GUIMEVehicle::~GUIMEVehicle ()
destructor
Definition at line 61 of file GUIMEVehicle.cpp.
Member Function Documentation
activateReminders()
void MSBaseVehicle::activateReminders (const MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual inherited
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
[in] enteredLane The lane, which is entered (if applicable)
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented in MSVehicle.
Definition at line 376 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices(), MESegment::receive(), and MELoop::teleportVehicle().
addActiveAddVisualisation()
void GUIBaseVehicle::addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::addAdditionalGLVisualisation
Definition at line 1174 of file GUIBaseVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), and GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems().
addContainer()
void MSBaseVehicle::addContainer (MSTransportable * container) virtual inherited
Adds a container to this vehicle.
The default implementation does nothing since containers are not supported by default
Parameters
[in] container The container to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 316 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getID(), and MSTransportable::getID().
Referenced by MSBaseVehicle::getDevices().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
addPerson()
void MSBaseVehicle::addPerson (MSTransportable * person) virtual inherited
Adds a person to this vehicle.
The default implementation does nothing since persons are not supported by default
Parameters
[in] person The person to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 311 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getID(), and MSTransportable::getID().
Referenced by MSBaseVehicle::getDevices().
addReminder()
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 349 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MESegment::addReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSBaseVehicle::getDevices(), and MSVehicle::processNextStop().
addStop()
bool MEVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0, bool collision = false, MSRouteIterator * searchStart = 0) virtual inherited
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 223 of file MEVehicle.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MELoop::getSegmentForEdge(), MSGlobals::gMesoNet, SUMOVehicleParameter::Stop::lane, and MEVehicle::myStops.
Referenced by MEVehicle::getLane().
addStops()
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 473 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), SUMOVehicleParameter::depart, MSRoute::getStops(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::stops, and WRITE_WARNING.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MEVehicle::getBlockTimeSeconds(), MSVehicle::replaceRoute(), and MSBaseVehicle::setChosenSpeedFactor().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
calculateArrivalParams()
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 398 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MSEdge::isTazConnector(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::isSelected(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), and MSBaseVehicle::reroute().
createDevice()
void MSBaseVehicle::createDevice (const std::string & deviceName) inherited
create device of the given type
Definition at line 508 of file MSBaseVehicle.cpp.
References MSDevice_Routing::buildVehicleDevices(), MSBaseVehicle::getDevice(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::hasDevice(), MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, MSMoveReminder::NOTIFICATION_DEPARTED, and MSDevice_Routing::notifyEnter().
Referenced by libsumo::Vehicle::setParameter().
drawAction_drawCarriageClass()
bool GUIMEVehicle::drawAction_drawCarriageClass (const GUIVisualizationSettings & s, SUMOVehicleShape guiShape, bool asImage) const virtual
draws the given guiShape if it has distinc carriages/modules and eturns true if so
Implements GUIBaseVehicle.
Definition at line 162 of file GUIMEVehicle.cpp.
References GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus().
Referenced by getAngle().
drawAction_drawLinkItems()
virtual void GUIBaseVehicle::drawAction_drawLinkItems (const GUIVisualizationSettings &) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 141 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawGLAdditional().
drawAction_drawPersonsAndContainers()
virtual void GUIBaseVehicle::drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 142 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsBoxPlus()
void GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus () const protected inherited
Definition at line 336 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::getVType().
Referenced by drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), and GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsImage()
bool GUIBaseVehicle::drawAction_drawVehicleAsImage (const GUIVisualizationSettings & s, double length = -1) const protected inherited
Definition at line 848 of file GUIBaseVehicle.cpp.
References GUITexturesHelper::drawTexturedBox(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), GUIBaseVehicle::getVType(), MSVehicleType::getWidth(), and GUIVisualizationSettings::vehicleSize.
Referenced by GUIVehicle::drawAction_drawRailCarriages(), and GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsPoly()
bool GUIBaseVehicle::drawAction_drawVehicleAsPoly (const GUIVisualizationSettings & s) const protected inherited
Definition at line 385 of file GUIBaseVehicle.cpp.
References RGBColor::changedBrightness(), GUIBaseVehicle::drawAction_drawCarriageClass(), GLHelper::drawBoxLine(), GLHelper::drawFilledCircle(), GUIBaseVehicle::drawPoly(), GLHelper::getColor(), MSVehicleType::getGuiShape(), MSVehicleType::getLength(), GUIBaseVehicle::getVType(), MSVehicleType::getWidth(), RGBColor::GREY, GLHelper::setColor(), SVS_ANT, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_BUS_FLEXIBLE, SVS_BUS_TROLLEY, SVS_DELIVERY, SVS_E_VEHICLE, SVS_EMERGENCY, SVS_FIREBRIGADE, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, SVS_PASSENGER_WAGON, SVS_PEDESTRIAN, SVS_POLICE, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_1TRAILER, SVS_TRUCK_SEMITRAILER, SVS_UNKNOWN, and vehiclePoly_PassengerCarBody.
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsTrianglePlus()
void GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus () const protected inherited
Definition at line 351 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), MSVehicleType::getLength(), and GUIBaseVehicle::getVType().
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleBlinker()
virtual void GUIBaseVehicle::drawAction_drawVehicleBlinker (double) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 136 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleBlueLight()
virtual void GUIBaseVehicle::drawAction_drawVehicleBlueLight () const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 145 of file GUIBaseVehicle.h.
References GUIBaseVehicle::addActiveAddVisualisation(), GUIBaseVehicle::drawGL(), GUIBaseVehicle::drawGLAdditional(), GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getCenteringBoundary(), GUIBaseVehicle::getPopUpMenu(), GUIBaseVehicle::hasActiveAddVisualisation(), and GUIBaseVehicle::removeActiveAddVisualisation().
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleBrakeLight()
virtual void GUIBaseVehicle::drawAction_drawVehicleBrakeLight (double length, bool onlyOne = false) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 137 of file GUIBaseVehicle.h.
References UNUSED_PARAMETER.
Referenced by GUIBaseVehicle::drawOnPos().
drawBestLanes()
virtual void GUIBaseVehicle::drawBestLanes () const inline virtual inherited
Draws the vehicle's best lanes.
Reimplemented in GUIVehicle.
Definition at line 144 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawGLAdditional().
drawGL()
void GUIBaseVehicle::drawGL (const GUIVisualizationSettings & s) const virtual inherited
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 1030 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getAngle(), and GUIBaseVehicle::getPosition().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIParkingArea::drawGL(), GUILane::drawGL(), and GUIBaseVehicle::drawGLAdditional().
drawGLAdditional()
void GUIBaseVehicle::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 1036 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawLinkItems(), GUIBaseVehicle::drawBestLanes(), GUIBaseVehicle::drawGL(), GUIBaseVehicle::drawRoute(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), GUIGlObject::getType(), GUIBaseVehicle::hasActiveAddVisualisation(), MSBaseVehicle::isOnRoad(), GUIBaseVehicle::myVehicle, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
drawLinkItem()
void GUIBaseVehicle::drawLinkItem (const Position & pos, SUMOTime arrivalTime, SUMOTime leaveTime, double exagerate) static protected inherited
Definition at line 1069 of file GUIBaseVehicle.cpp.
References GLHelper::drawFilledCircle(), GLHelper::drawText(), RGBColor::GREEN, STEPS2TIME, toString(), Position::x(), and Position::y().
Referenced by GUIVehicle::drawAction_drawLinkItems().
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GNERouteProbe::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
drawOnPos()
void GUIBaseVehicle::drawOnPos (const GUIVisualizationSettings & s, const Position & pos, const double angle) const inherited
Draws the object on the specified position with the specified angle.
Parameters
[in] s The settings for the current view (may influence drawing)
[in] pos The position to draw the vehicle on
[in] angle The drawing angle of the vehicle
Definition at line 867 of file GUIBaseVehicle.cpp.
References GUIVisualizationTextSettings::color, GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawPersonsAndContainers(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), GUIBaseVehicle::drawAction_drawVehicleBlinker(), GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawAction_drawVehicleBrakeLight(), GUIVisualizationSettings::drawLaneChangePreference, GUIVisualizationSettings::drawMinGap, GUIGlObject::drawName(), GLHelper::drawOutlineCircle(), GLHelper::drawText(), MSBaseVehicle::getDevice(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), SUMOVehicle::getLane(), MSVehicleType::getMinGap(), MSBaseVehicle::getParameter(), SUMOVehicle::getPosition(), MSDevice_BTreceiver::getRange(), GUIGlObject::getType(), GUIBaseVehicle::getVType(), GLO_MAX, SUMOVehicleParameter::line, M_PI, MIN2(), GUIBaseVehicle::mySeatPositions, GUIBaseVehicle::myVehicle, GUIVisualizationSettings::personName, RAD2DEG, GUIVisualizationSettings::scale, GUIBaseVehicle::setColor(), GUIVisualizationTextSettings::show, GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationTextSettings::size, SVS_ANT, SVS_BICYCLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGL(), and GUIEdge::drawMesoVehicles().
drawPoly()
void GUIBaseVehicle::drawPoly (double * poses, double offset) static protected inherited
Definition at line 369 of file GUIBaseVehicle.cpp.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly().
drawRoute()
void GUIBaseVehicle::drawRoute (const GUIVisualizationSettings & s, int routeNo, double darken) const inherited
Chooses the route to draw and draws it, darkening it as given.
Parameters
[in] s The visualisation settings, needed to determine the vehicle's color
[in] routeNo The route to show (0: the current, >0: prior)
[in] darken The amount to darken the route by
Definition at line 1191 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawRouteHelper(), MSBaseVehicle::getRoute(), MSDevice_Vehroutes::getRoute(), GUIBaseVehicle::myRoutes, GUIBaseVehicle::myVehicle, and GUIBaseVehicle::setColor().
Referenced by GUIBaseVehicle::drawGLAdditional().
drawRouteHelper()
void GUIMEVehicle::drawRouteHelper (const GUIVisualizationSettings & s, const MSRoute & r) const virtual
Draws the route.
Parameters
[in] r The route to draw
Implements GUIBaseVehicle.
Definition at line 215 of file GUIMEVehicle.cpp.
References MSRoute::begin(), GLHelper::drawBoxLines(), MSRoute::end(), GUIVisualizationSizeSettings::getExaggeration(), GUILane::getShape(), GUILane::getShapeLengths(), GUILane::getShapeRotations(), and GUIVisualizationSettings::vehicleSize.
Referenced by getAngle().
estimateLeaveSpeed()
double MEVehicle::estimateLeaveSpeed (const MSLink * link) const inherited
Returns the vehicle's estimated speed after driving accross the link.
See also
MSVehicle.cpp::estimateLeaveSpeed
Definition at line 125 of file MEVehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), MEVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), and MIN2().
Referenced by MEVehicle::getLane(), and MESegment::isOpen().
getAcceleration()
double MSBaseVehicle::getAcceleration () const virtual inherited
Returns the vehicle's acceleration.
This default implementation returns always 0.
Returns
The acceleration
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 280 of file MSBaseVehicle.cpp.
Referenced by MSBaseVehicle::getCurrentRouteEdge().
getAccumulatedWaitingTime()
SUMOTime MEVehicle::getAccumulatedWaitingTime () const inline virtual inherited
Returns the duration for which the vehicle was blocked.
Implements SUMOVehicle.
Definition at line 281 of file MEVehicle.h.
References MEVehicle::getWaitingTime().
getAngle()
double GUIMEVehicle::getAngle () const inline virtual
Return current angle.
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 90 of file GUIMEVehicle.h.
References drawAction_drawCarriageClass(), drawRouteHelper(), MEVehicle::getAngle(), getColorValue(), getLastLaneChangeOffset(), getParameterWindow(), getStopInfo(), getTypeParameterWindow(), and selectBlockingFoes().
getArrivalPos()
virtual double MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 269 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
getAverageSpeed()
double MEVehicle::getAverageSpeed () const inherited
Returns the vehicle's estimated average speed on the segment assuming no further delays.
Returns
The vehicle's estimated average speed
Note
This is only an upper bound. The speed will be lower if the preceeding vehicle is delayed
Definition at line 119 of file MEVehicle.cpp.
References MESegment::getLength(), MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MEVehicle::mySegment, and STEPS2TIME.
Referenced by MEVehicle::getLane(), and MEVehicle::getSpeed().
getBackPositionOnLane()
double MEVehicle::getBackPositionOnLane (const MSLane * lane) const virtual inherited
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Implements SUMOVehicle.
Definition at line 74 of file MEVehicle.cpp.
References MSVehicleType::getLength(), MEVehicle::getPositionOnLane(), and MSBaseVehicle::getVehicleType().
getBlockTime()
SUMOTime MEVehicle::getBlockTime () const inline inherited
Returns the time at which the vehicle was blocked.
Returns
The blocking time
Definition at line 270 of file MEVehicle.h.
References MEVehicle::myBlockTime.
Referenced by MELoop::checkCar(), and MEVehicle::getBlockTimeSeconds().
getBlockTimeSeconds()
double MEVehicle::getBlockTimeSeconds () const inline inherited
Returns the time at which the vehicle was blocked on the current segment.
Definition at line 308 of file MEVehicle.h.
References MSBaseVehicle::addStops(), MEVehicle::getBlockTime(), MEVehicle::getCurrentLinkPenaltySeconds(), MEVehicle::loadState(), MEVehicle::mayProceed(), MSMoveReminder::NOTIFICATION_JUNCTION, MEVehicle::replaceRoute(), MEVehicle::saveState(), STEPS2TIME, MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
Referenced by getParameterWindow().
getCenteringBoundary()
Boundary GUIBaseVehicle::getCenteringBoundary () const virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 327 of file GUIBaseVehicle.cpp.
References Boundary::add(), MSVehicleType::getLength(), GUIBaseVehicle::getPosition(), MSBaseVehicle::getVehicleType(), Boundary::grow(), and GUIBaseVehicle::myVehicle.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
getChosenSpeedFactor()
double MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 377 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by getParameterWindow(), GUIVehicle::getParameterWindow(), and libsumo::Vehicle::getSpeedFactor().
getColorValue()
double GUIMEVehicle::getColorValue (int activeScheme) const virtual
gets the color value according to the current scheme index
Implements GUIBaseVehicle.
Definition at line 169 of file GUIMEVehicle.cpp.
References MSBaseVehicle::getDepartDelay(), MESegment::getEdge(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), MEVehicle::getSegment(), MEVehicle::getSpeed(), MSEdge::getVehicleMaxSpeed(), MEVehicle::getWaitingSeconds(), GLO_VEHICLE, gSelected, GUISelectedStorage::isSelected(), and STEPS2TIME.
Referenced by getAngle().
getConservativeSpeed()
double MEVehicle::getConservativeSpeed (SUMOTime & earliestArrival) const inherited
Returns the vehicle's estimated speed taking into account delays.
Returns
The vehicle's estimated speed
Parameters
[in,out] earliestArrival A lower bound on leaveTime, modified to contain new lower bound on leave Time
Note
This is only an upper bound. The speed may be even lower if there are further delays downstream
Definition at line 134 of file MEVehicle.cpp.
References DELTA_T, MESegment::getLength(), MAX2(), MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MEVehicle::mySegment, and STEPS2TIME.
Referenced by MEVehicle::getLane().
getCurrentLinkPenaltySeconds()
double MEVehicle::getCurrentLinkPenaltySeconds () const inherited
Returns the delay that is accrued due to option –meso-tls-penalty or –meso-minor-penalty.
Definition at line 278 of file MEVehicle.cpp.
References MESegment::getLinkPenalty(), MEVehicle::mySegment, and STEPS2TIME.
Referenced by MEVehicle::getBlockTimeSeconds(), and getParameterWindow().
getCurrentRouteEdge()
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 192 of file MSBaseVehicle.h.
References MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
Referenced by MSDevice_SSM::findSurroundingVehicles(), libsumo::Vehicle::getDistance(), and libsumo::Vehicle::moveToXY().
getDepartDelay()
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 253 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by getColorValue(), GUIVehicle::getColorValue(), getParameterWindow(), and GUIVehicle::getParameterWindow().
getDepartPos()
double MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 261 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by libsumo::Vehicle::getDistance().
getDeparture()
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 248 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay(), and MSVehicle::Influencer::postProcessRemoteControl().
getDevice()
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 447 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), GUIBaseVehicle::drawOnPos(), MSVehicle::resumeFromStopping(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
getDeviceParameter()
std::string MSBaseVehicle::getDeviceParameter (const std::string & deviceName, const std::string & key) const inherited
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 527 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by libsumo::Vehicle::getParameter().
getDevices()
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 302 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
getEdge()
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 149 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), libsumo::Vehicle::getDrivingDistance2D(), MSVehicle::getLatOffset(), getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), MSBaseVehicle::getVClass(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MELoop::teleportVehicle().
getEventTime()
SUMOTime MEVehicle::getEventTime () const inline inherited
Returns the (planned) time at which the vehicle leaves his current cell.
Returns
The time the vehicle thinks he leaves his cell at
Definition at line 211 of file MEVehicle.h.
References MEVehicle::myEventTime.
Referenced by MELoop::addLeaderCar(), MELoop::checkCar(), MEVehicle::getEventTimeSeconds(), MESegment::isOpen(), MESegment::receive(), MELoop::removeLeaderCar(), MESegment::send(), MELoop::setApproaching(), MESegment::setSpeedForQueue(), MELoop::teleportVehicle(), and MEVehicle::updateDetectors().
getEventTimeSeconds()
double MEVehicle::getEventTimeSeconds () const inline inherited
Returns the earliest leave time for the current segment.
Definition at line 298 of file MEVehicle.h.
References MEVehicle::getEventTime(), and STEPS2TIME.
Referenced by getParameterWindow().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getID()
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 121 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChangerSublane::abortLCManeuver(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), MSBaseVehicle::addContainer(), MSPModel_Striping::addCrossingVehs(), MSLCM_SL2015::addLCSpeedAdvice(), MSBaseVehicle::addPerson(), MSVehicle::addTraciStopAtStoppingPlace(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), libsumo::Vehicle::changeTarget(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSVehicle::computeAngle(), MSLCM_SL2015::computeSpeedLat(), MSDevice_SSM::computeSSMs(), MSLaneChanger::continueChange(), MSLaneChangerSublane::continueChangeSublane(), MSLCM_SL2015::decideDirection(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSDevice_SSM::Encounter::Encounter(), MSCalibrator::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLaneChanger::findCandidate(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSAbstractLaneChangeModel::getShadowLane(), MSBaseVehicle::getSingularType(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSVehicle::ignoreRed(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::lateralDistanceToLane(), MSVehicle::leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSVehicle::onRemovalFromNet(), MSLaneChangerSublane::outputLCStarted(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLCM_SL2015::prepareStep(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::removePassedDriveItems(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), libsumo::Vehicle::resume(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), MSCalibrator::scheduleRemoval(), GUIVehicle::selectBlockingFoes(), MSVehicle::setAngle(), MSAbstractLaneChangeModel::setManeuverDist(), MSLane::setManeuverReservation(), MSLCM_SL2015::setOwnState(), MSLane::setPartialOccupation(), libsumo::Helper::setRemoteControlled(), libsumo::Vehicle::setRoute(), libsumo::Vehicle::setRouteID(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSVehicle::updateBestLanes(), MSVehicle::updateDriveItems(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicle::updateState(), MSAbstractLaneChangeModel::updateTargetLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), and MSXMLRawOut::writeVehicle().
getImpatience()
double MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 440 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToImpatience, MAX2(), and MIN2().
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), GUIVehicle::getParameterWindow(), MSLCM_LC2013::informFollower(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::processLinkAproaches(), and GUIVehicle::selectBlockingFoes().
getLane()
MSLane* MEVehicle::getLane () const inline virtual inherited
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 90 of file MEVehicle.h.
References MEVehicle::addStop(), MEVehicle::estimateLeaveSpeed(), MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getPosition(), MEVehicle::getSpeed(), MEVehicle::getStopEdges(), MEVehicle::getStoptime(), MEVehicle::hasArrived(), MEVehicle::isOnRoad(), MEVehicle::isParking(), MEVehicle::isStopped(), MEVehicle::isStoppedInRange(), MEVehicle::isStoppedTriggered(), and MEVehicle::moveRoutePointer().
getLastEntryTime()
SUMOTime MEVehicle::getLastEntryTime () const inline inherited
Returns the time the vehicle entered the current segment.
Returns
The entry time
Definition at line 253 of file MEVehicle.h.
References MEVehicle::myLastEntryTime.
Referenced by MEVehicle::getLastEntryTimeSeconds(), MESegment::newArrival(), MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
getLastEntryTimeSeconds()
double MEVehicle::getLastEntryTimeSeconds () const inline inherited
Returns the entry time for the current segment.
Definition at line 303 of file MEVehicle.h.
References MEVehicle::getLastEntryTime(), and STEPS2TIME.
Referenced by getParameterWindow().
getLastLaneChangeOffset()
double GUIMEVehicle::getLastLaneChangeOffset () const virtual
Returns the time since the last lane change in seconds.
See also
MSVehicle::myLastLaneChangeOffset
Returns
The time since the last lane change in seconds
Implements GUIBaseVehicle.
Definition at line 227 of file GUIMEVehicle.cpp.
Referenced by getAngle().
getLateralPositionOnLane()
virtual double MSBaseVehicle::getLateralPositionOnLane () const inline virtual inherited
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 175 of file MSBaseVehicle.h.
getLength()
double MSBaseVehicle::getLength () const inline inherited
Returns the vehicle's length.
Returns
vehicle's length
Definition at line 361 of file MSBaseVehicle.h.
References MSVehicleType::getLength(), and MSBaseVehicle::myType.
Referenced by MSVehicle::addStop(), MSDevice_SSM::checkConflictEntryAndExit(), MSDevice_SSM::classifyEncounter(), MSDevice_SSM::determineConflictPoint(), MSDevice_SSM::determineTTCandDRAC(), MSVehicle::enterLaneAtInsertion(), MSDevice_SSM::findSurroundingVehicles(), MSLink::getLeaderInfo(), MSDevice_SSM::getUpstreamVehicles(), MSVehicle::updateFurtherLanes(), MSDevice_SSM::updatePassedEncounter(), and MSVehicle::validatePosition().
getMaxSpeed()
double MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosRemote(), and MSVehicle::Influencer::implicitSpeedRemote().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNEPoly::getParentName(), GNERerouter::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNaviDegree()
double GUIBaseVehicle::getNaviDegree () const inline inherited
return the current angle in navigational degrees
Definition at line 92 of file GUIBaseVehicle.h.
References GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawRouteHelper(), GUIBaseVehicle::getAngle(), GUIBaseVehicle::getColorValue(), GUIBaseVehicle::getLastLaneChangeOffset(), GUIBaseVehicle::getParameterWindow(), GUIBaseVehicle::getStopInfo(), GUIBaseVehicle::getTypeParameterWindow(), GeomHelper::naviDegree(), and GUIBaseVehicle::selectBlockingFoes().
Referenced by getParameterWindow(), and GUIVehicle::getParameterWindow().
getNextParkingArea()
MSParkingArea* MEVehicle::getNextParkingArea () inline virtual inherited
get the current parking area stop
Implements SUMOVehicle.
Definition at line 192 of file MEVehicle.h.
getNumberReroutes()
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 291 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), and MSBaseVehicle::myNumberReroutes.
Referenced by GUIBaseVehicle::drawGLAdditional(), getColorValue(), GUIVehicle::getColorValue(), and MSBaseVehicle::replaceRouteEdges().
getParameter()
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 127 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getDepartSpeed(), libsumo::Vehicle::getLine(), libsumo::Vehicle::getParameter(), getParameterWindow(), GUIVehicle::getParameterWindow(), libsumo::Vehicle::getVia(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setColor(), GUIBaseVehicle::setFunctionalColor(), libsumo::Vehicle::setLine(), libsumo::Vehicle::setParameter(), and METriggeredCalibrator::tryEmit().
getParameterWindow()
GUIParameterTableWindow * GUIMEVehicle::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIBaseVehicle.
Definition at line 65 of file GUIMEVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MEVehicle::getBlockTimeSeconds(), MSBaseVehicle::getChosenSpeedFactor(), MEVehicle::getCurrentLinkPenaltySeconds(), MSBaseVehicle::getDepartDelay(), MSBaseVehicle::getEdge(), MEVehicle::getEventTimeSeconds(), MSBaseVehicle::getID(), MEVehicle::getLastEntryTimeSeconds(), GUIBaseVehicle::getNaviDegree(), MSBaseVehicle::getParameter(), MEVehicle::getPositionOnLane(), MEVehicle::getSegment(), MEVehicle::getSpeed(), MEVehicle::getWaitingSeconds(), SUMOVehicleParameter::line, GUIParameterTableWindow::mkItem(), MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, and time2string().
Referenced by getAngle().
getParentName()
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEPoly, GNERerouter, GNEPOILane, GNEVariableSpeedSign, GNENetElement, GNEPOI, GNERouteProbe, GNEStoppingPlace, GNEDetector, GUILane, GNEDetectorE3, GNEVaporizer, and GNELane.
Definition at line 114 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
getPopUpMenu()
GUIGLObjectPopupMenu * GUIBaseVehicle::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 281 of file GUIBaseVehicle.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUIBaseVehicle::hasActiveAddVisualisation(), MID_HIDE_ALLROUTES, MID_HIDE_BEST_LANES, MID_HIDE_CURRENTROUTE, MID_HIDE_LFLINKITEMS, MID_SHOW_ALLROUTES, MID_SHOW_BEST_LANES, MID_SHOW_CURRENTROUTE, MID_SHOW_FOES, MID_SHOW_LFLINKITEMS, MID_START_TRACK, MID_STOP_TRACK, GUIBaseVehicle::myAdditionalVisualizations, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
getPosition()
Position GUIMEVehicle::getPosition (const double offset = 0) const inline virtual
Return current position (x/y, cartesian)
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 82 of file GUIMEVehicle.h.
References MEVehicle::getPosition().
getPositionOnLane()
double MEVehicle::getPositionOnLane () const virtual inherited
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 80 of file MEVehicle.cpp.
References MESegment::getIndex(), MESegment::getLength(), and MEVehicle::mySegment.
Referenced by MEVehicle::getAngle(), MEVehicle::getBackPositionOnLane(), getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), and MEVehicle::hasArrived().
getPreviousSpeed()
double MSBaseVehicle::getPreviousSpeed () const virtual inherited
Returns the vehicle's previous speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 64 of file MSBaseVehicle.cpp.
getQueIndex()
int MEVehicle::getQueIndex () const inline inherited
Returns the index of the que the vehicle is in.
Returns
The que index
Definition at line 237 of file MEVehicle.h.
References MEVehicle::myQueIndex.
Referenced by MESegment::getLink(), MESegment::removeCar(), MEVehicle::saveState(), and MESegment::send().
getRerouteOrigin()
virtual const MSEdge* MSBaseVehicle::getRerouteOrigin () const inline virtual inherited
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge
Returns
The rerouting start point
Reimplemented in MSVehicle.
Definition at line 184 of file MSBaseVehicle.h.
References MSBaseVehicle::myCurrEdge.
Referenced by MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
getRoute()
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 107 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), libsumo::Vehicle::getDistance(), libsumo::Vehicle::getDrivingDistance(), libsumo::Vehicle::getDrivingDistance2D(), libsumo::Vehicle::getEdges(), libsumo::Vehicle::getRouteID(), MSLane::isInsertionSuccess(), libsumo::Vehicle::moveToXY(), MSVehicle::Influencer::postProcessRemoteControl(), and GUIBaseVehicle::setFunctionalColor().
getSeatPosition()
const Position & GUIBaseVehicle::getSeatPosition (int personIndex) const protected inherited
returns the seat position for the person with the given index
if there are not enough seats in the vehicle people have to squeeze onto the last seat
Definition at line 1225 of file GUIBaseVehicle.cpp.
References MIN2(), and GUIBaseVehicle::mySeatPositions.
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers().
getSegment()
MESegment* MEVehicle::getSegment () const inline inherited
Returns the current segment the vehicle is on.
Returns
The segment the vehicle is on
Definition at line 229 of file MEVehicle.h.
References MEVehicle::mySegment.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), getColorValue(), getParameterWindow(), MEVehicle::isOnRoad(), MESegment::loadState(), MELoop::setApproaching(), and MELoop::teleportVehicle().
getSingularType()
MSVehicleType & MSBaseVehicle::getSingularType () inherited
Replaces the current vehicle type with a new one used by this vehicle only.
If the currently used vehicle type is already marked as being used by this vehicle only, no new type is created.
Returns
The new modifiable vehicle type
See also
MSBaseVehicle::myType
Definition at line 559 of file MSBaseVehicle.cpp.
References MSVehicleType::buildSingularType(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSVehicleType::isVehicleSpecific(), MSBaseVehicle::myType, OutputDevice::openTag(), MSBaseVehicle::replaceVehicleType(), STEPS2TIME, SUMO_ATTR_ID, SUMO_ATTR_TIME, toString(), and OutputDevice::writeAttr().
Referenced by TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setActionStepLength(), MSBaseVehicle::setChosenSpeedFactor(), libsumo::Vehicle::setMaxSpeed(), and libsumo::Vehicle::setShapeClass().
getSlope()
double MEVehicle::getSlope () const virtual inherited
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 95 of file MEVehicle.cpp.
References MSBaseVehicle::getEdge(), MSEdge::getLanes(), MEVehicle::getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::slopeDegreeAtOffset().
getSpeed()
double MEVehicle::getSpeed () const virtual inherited
Returns the vehicle's estimated speed assuming no delays.
Returns
The vehicle's estimated speed
Note
This is only an upper bound. The speed will be lower if the preceeding vehicle is delayed
Implements SUMOVehicle.
Definition at line 109 of file MEVehicle.cpp.
References MEVehicle::getAverageSpeed(), and MEVehicle::getWaitingTime().
Referenced by MEVehicle::estimateLeaveSpeed(), getColorValue(), MEVehicle::getLane(), getParameterWindow(), MESegment::isOpen(), MESegment::newArrival(), MESegment::receive(), and MELoop::setApproaching().
getStopEdges()
const ConstMSEdgeVector MEVehicle::getStopEdges () const virtual inherited
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 262 of file MEVehicle.cpp.
References MEVehicle::myStops.
Referenced by MEVehicle::getLane().
getStopInfo()
std::string GUIMEVehicle::getStopInfo () const virtual
retrieve information about the current stop state
Implements GUIBaseVehicle.
Definition at line 234 of file GUIMEVehicle.cpp.
References MEVehicle::isParking(), and MEVehicle::isStopped().
Referenced by getAngle().
getStoptime()
SUMOTime MEVehicle::getStoptime (const MESegment *const seg) const inherited
Returns how long to stop at the given segment.
Parameters
[in] seg The segment in question
Returns
stop time for the segment
Definition at line 253 of file MEVehicle.cpp.
References MEVehicle::myStops.
Referenced by MEVehicle::getLane(), and MESegment::receive().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIMEVehicle::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Implements GUIBaseVehicle.
Definition at line 137 of file GUIMEVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicleType::getContainerCapacity(), MSVehicleType::getEmissionClass(), MSVehicleType::getID(), MSVehicleType::getLength(), Parameterised::getMap(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getMinGap(), PollutantsInterface::getName(), MSVehicleType::getParameter(), MSVehicleType::getPersonCapacity(), MSVehicleType::getVehicleClass(), GUIParameterTableWindow::mkItem(), MSBaseVehicle::myType, and SumoVehicleClassStrings.
Referenced by getAngle().
getVClass()
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), and SUMOVTypeParameter::vehicleClass.
Referenced by GUIVehicle::drawRouteHelper(), MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
getVehicleType()
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 115 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeaders(), MSPModel_Striping::addCrossingVehs(), MSVehicle::addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MSLCM_SL2015::computeSpeedLat(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSDevice_SSM::estimateConflictTimes(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), MSVehicle::getLateralOverlap(), MSLane::getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), GUIVehicle::getLeftSideOnEdge(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), MSVehicle::getTimeGapOnLane(), MESegment::getTimeHeadway(), libsumo::Vehicle::getTypeID(), libsumo::Vehicle::getVehicleType(), GUIBaseVehicle::getVType(), MSLCM_SL2015::getWidth(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MESegment::hasSpaceFor(), MSVehicle::ignoreRed(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::keepClear(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), MSCFModel_Krauss::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSVehicle::overlap(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MESegment::receive(), MSLaneChanger::ChangeElem::registerHop(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), GUIVehicle::selectBlockingFoes(), MSVehicleType::setActionStepLength(), MSAbstractLaneChangeModel::setFollowerGaps(), GUIBaseVehicle::setFunctionalColor(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSVehicle::setTentativeLaneAndPosition(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
getVType()
const MSVehicleType& GUIBaseVehicle::getVType () const inline protected inherited
A shortcut to myVehicle.myType.
Definition at line 342 of file GUIBaseVehicle.h.
References MSBaseVehicle::getVehicleType(), and GUIBaseVehicle::myVehicle.
Referenced by GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), and GUIBaseVehicle::drawOnPos().
getWaitingSeconds()
double MEVehicle::getWaitingSeconds () const inline inherited
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 292 of file MEVehicle.h.
References MEVehicle::getWaitingTime(), and STEPS2TIME.
Referenced by getColorValue(), and getParameterWindow().
getWaitingTime()
SUMOTime MEVehicle::getWaitingTime () const inline virtual inherited
Returns the duration for which the vehicle was blocked.
Implements SUMOVehicle.
Definition at line 276 of file MEVehicle.h.
References MAX2(), MEVehicle::myBlockTime, and MEVehicle::myEventTime.
Referenced by MELoop::checkCar(), MEVehicle::getAccumulatedWaitingTime(), MEVehicle::getSpeed(), MEVehicle::getWaitingSeconds(), MESegment::isOpen(), and MELoop::setApproaching().
getWidth()
double MSBaseVehicle::getWidth () const inline inherited
Returns the vehicle's width.
Returns
vehicle's width
Definition at line 369 of file MSBaseVehicle.h.
References MSVehicleType::getWidth(), and MSBaseVehicle::myType.
Referenced by MSDevice_SSM::classifyEncounter(), MSAbstractLaneChangeModel::determineTargetLane(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), MSVehicle::getLateralOverlap(), MSVehicle::lateralDistanceToLane(), MSVehicle::planMoveInternal(), MSLaneChangerSublane::startChangeSublane(), and MSDevice_SSM::updatePassedEncounter().
hasActiveAddVisualisation()
bool GUIBaseVehicle::hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const inherited
Returns whether the named feature is enabled in the given view.
Parameters
[in] parent The view for which the feature may be enabled
[in] which The visualisation feature
Returns
see comment
Definition at line 1168 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGLAdditional(), and GUIBaseVehicle::getPopUpMenu().
hasArrived()
bool MEVehicle::hasArrived () const virtual inherited
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 159 of file MEVehicle.cpp.
References MSRoute::end(), MEVehicle::getPositionOnLane(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MEVehicle::myEventTime, MSBaseVehicle::myRoute, MEVehicle::mySegment, POSITION_EPS, and SUMOTime_MIN.
Referenced by MEVehicle::getLane(), MEVehicle::moveRoutePointer(), and MESegment::receive().
hasDeparted()
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 300 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by MSVehicle::addStop(), MSBaseVehicle::createDevice(), MSLane::forceVehicleInsertion(), libsumo::Vehicle::getRouteIndex(), MEVehicle::loadState(), MSVehicle::loadState(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::saveState(), and MSBaseVehicle::setArrivalPos().
hasDevice()
bool MSBaseVehicle::hasDevice (const std::string & deviceName) const inherited
check whether the vehicle is equiped with a device of the given type
Definition at line 497 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), and libsumo::Vehicle::getParameter().
hasValidRoute()
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 321 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), libsumo::Vehicle::isRouteValid(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::replaceRouteEdges(), and libsumo::Vehicle::setRouteID().
isFrontOnLane()
virtual bool MSBaseVehicle::isFrontOnLane (const MSLane *) const inline virtual inherited
Returns the information whether the front of the vehhicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 167 of file MSBaseVehicle.h.
isOnRoad()
bool MEVehicle::isOnRoad () const virtual inherited
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 168 of file MEVehicle.cpp.
References MEVehicle::getSegment().
Referenced by MEVehicle::getLane().
isParking()
bool MEVehicle::isParking () const virtual inherited
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 174 of file MEVehicle.cpp.
Referenced by MEVehicle::getLane(), and getStopInfo().
isRemoteControlled()
virtual bool MSBaseVehicle::isRemoteControlled () const inline virtual inherited
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 160 of file MSBaseVehicle.h.
isSelected()
virtual bool MSBaseVehicle::isSelected () const inline virtual inherited
whether this vehicle is selected in the GUI
Implements SUMOVehicle.
Reimplemented in GUIVehicle.
Definition at line 430 of file MSBaseVehicle.h.
References MSBaseVehicle::calculateArrivalParams(), and MSBaseVehicle::getStopEdges().
isStopped()
bool MEVehicle::isStopped () const virtual inherited
Returns whether the vehicle is at a stop.
Returns
Whether it has stopped
Implements SUMOVehicle.
Definition at line 234 of file MEVehicle.cpp.
References MEVehicle::mySegment, and MEVehicle::myStops.
Referenced by MELoop::checkCar(), MEVehicle::getLane(), getStopInfo(), and MEVehicle::isStoppedInRange().
isStoppedInRange()
bool MEVehicle::isStoppedInRange (double pos) const virtual inherited
return whether the given position is within range of the current stop
Implements SUMOVehicle.
Definition at line 246 of file MEVehicle.cpp.
References MEVehicle::isStopped(), and UNUSED_PARAMETER.
Referenced by MEVehicle::getLane().
isStoppedTriggered()
bool MEVehicle::isStoppedTriggered () const virtual inherited
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 240 of file MEVehicle.cpp.
Referenced by MEVehicle::getLane().
loadState()
void MEVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual inherited
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 369 of file MEVehicle.cpp.
References MELoop::addLeaderCar(), MESegment::getIndex(), MESegment::getNextSegment(), MELoop::getSegmentForEdge(), SUMOSAXAttributes::getString(), MSGlobals::gMesoNet, SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), MEVehicle::myBlockTime, MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MEVehicle::setSegment(), SUMO_ATTR_POSITION, SUMO_ATTR_STATE, SUMOTime_MAX, and SUMOTime_MIN.
Referenced by MEVehicle::getBlockTimeSeconds().
mayProceed()
bool MEVehicle::mayProceed () const inherited
Returns whether the vehicle is allowed to pass the next junction.
Returns
true iff the vehicle may drive over the next junction
Definition at line 272 of file MEVehicle.cpp.
References MESegment::isOpen(), and MEVehicle::mySegment.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), and MEVehicle::getBlockTimeSeconds().
moveRoutePointer()
bool MEVehicle::moveRoutePointer () inherited
Update when the vehicle enters a new edge in the move step.
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 141 of file MEVehicle.cpp.
References MSRoute::end(), MEVehicle::hasArrived(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, and SUMOVehicleParameter::via.
Referenced by METriggeredCalibrator::execute(), MEVehicle::getLane(), MESegment::receive(), and MELoop::teleportVehicle().
onDepart()
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 292 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), and MESegment::receive().
removeActiveAddVisualisation()
void GUIBaseVehicle::removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::removeAdditionalGLVisualisation
Definition at line 1184 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations, and GUISUMOAbstractView::removeAdditionalGLVisualisation().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
removeReminder()
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 360 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
replaceParkingArea()
bool MEVehicle::replaceParkingArea (MSParkingArea * , std::string &) inline virtual inherited
replace the current parking area stop with a new stop with merge duration
Implements SUMOVehicle.
Definition at line 186 of file MEVehicle.h.
replaceRoute()
bool MEVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0, bool addStops = true, bool removeStops = true) virtual inherited
Replaces the current route by the given one.
Implements SUMOVehicle.
Definition at line 180 of file MEVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSRoute::getEdges(), MSNet::getInstance(), MESegment::getLink(), MSNet::informVehicleStateListener(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, MEVehicle::mySegment, MSRoute::release(), MSLink::removeApproaching(), MELoop::setApproaching(), UNUSED_PARAMETER, and MSNet::VEHICLE_STATE_NEWROUTE.
Referenced by MEVehicle::getBlockTimeSeconds().
replaceRouteEdges()
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false, bool removeStops = true) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
[in] removeStops Whether stops should be removed if they do not fit onto the new route
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 227 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), toString(), and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), MSBaseVehicle::reroute(), and libsumo::Vehicle::setRoute().
replaceVehicleType()
void MSBaseVehicle::replaceVehicleType (MSVehicleType * type) inherited
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSBaseVehicle::myType
Definition at line 550 of file MSBaseVehicle.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleType::isVehicleSpecific(), MSBaseVehicle::myType, and MSVehicleControl::removeVType().
Referenced by MSBaseVehicle::getSingularType(), MSBaseVehicle::setChosenSpeedFactor(), and libsumo::Vehicle::setType().
reroute()
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 155 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), MSBaseVehicle::calculateArrivalParams(), SUMOAbstractRouter< E, V >::compute(), MSInsertionControl::descheduleDeparture(), MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, MSGlobals::gCheckRoutes, Named::getID(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSEdge::isTazConnector(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, SUMOVehicleParameter::via, and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), MSBaseVehicle::getCurrentRouteEdge(), libsumo::Vehicle::rerouteEffort(), and libsumo::Vehicle::rerouteTraveltime().
saveState()
void MEVehicle::saveState (OutputDevice & out) virtual inherited
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 340 of file MEVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MESegment::getEdge(), MESegment::getIndex(), MEVehicle::getQueIndex(), MEVehicle::myBlockTime, MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MSBaseVehicle::myDevices, MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MEVehicle::mySegment, MEVehicle::myStops, OutputDevice::openTag(), MSBaseVehicle::saveState(), STEPS2TIME, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_LANE, SUMO_ATTR_STATE, SUMO_TAG_STOP, toString(), OutputDevice::writeAttr(), and Parameterised::writeParams().
Referenced by MEVehicle::getBlockTimeSeconds().
selectBlockingFoes()
void GUIMEVehicle::selectBlockingFoes () const virtual
adds the blocking foes to the current selection
Implements GUIBaseVehicle.
Definition at line 248 of file GUIMEVehicle.cpp.
Referenced by getAngle().
setArrivalPos()
virtual void MSBaseVehicle::setArrivalPos (double arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 275 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
setBlockTime()
void MEVehicle::setBlockTime (const SUMOTime t) inline inherited
Sets the time at which the vehicle was blocked.
Parameters
[in] t The blocking time
Definition at line 261 of file MEVehicle.h.
References MEVehicle::myBlockTime, and MEVehicle::myLastEntryTime.
Referenced by MELoop::checkCar(), and MESegment::receive().
setChosenSpeedFactor()
void MSBaseVehicle::setChosenSpeedFactor (const double factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 384 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::getDevice(), MSBaseVehicle::getSingularType(), MSBaseVehicle::myChosenSpeedFactor, MSBaseVehicle::replaceVehicleType(), and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
setColor()
void GUIBaseVehicle::setColor (const GUIVisualizationSettings & s) const protected inherited
sets the color according to the currente settings
Definition at line 1079 of file GUIBaseVehicle.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIBaseVehicle::getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIBaseVehicle::myVehicle, GLHelper::setColor(), GUIBaseVehicle::setFunctionalColor(), and GUIVisualizationSettings::vehicleColorer.
Referenced by GUIBaseVehicle::drawOnPos(), and GUIBaseVehicle::drawRoute().
setDeviceParameter()
void MSBaseVehicle::setDeviceParameter (const std::string & deviceName, const std::string & key, const std::string & value) inherited
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 538 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by libsumo::Vehicle::setParameter().
setEventTime()
void MEVehicle::setEventTime (SUMOTime t, bool hasDelay = true) inline inherited
Sets the (planned) time at which the vehicle leaves his current cell.
Parameters
[in] t The leaving time
Definition at line 199 of file MEVehicle.h.
References MESegment::getEdge(), MSEdge::markDelayed(), MEVehicle::myEventTime, MEVehicle::myLastEntryTime, and MEVehicle::mySegment.
Referenced by MELoop::checkCar(), METriggeredCalibrator::execute(), MESegment::receive(), MESegment::send(), MESegment::setSpeedForQueue(), and MELoop::teleportVehicle().
setFunctionalColor()
bool GUIBaseVehicle::setFunctionalColor (int activeScheme, const MSBaseVehicle * veh) static inherited
sets the color according to the current scheme index and some vehicle function
Definition at line 1088 of file GUIBaseVehicle.cpp.
References SUMOVehicleParameter::color, RGBColor::DEFAULT_COLOR, Position::distanceTo(), RGBColor::fromHSV(), Boundary::getCenter(), MSRoute::getColor(), MSVehicleType::getColor(), MSRoute::getEdges(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSBaseVehicle::getRoute(), MSBaseVehicle::getVehicleType(), M_PI, GLHelper::setColor(), VEHPARS_COLOR_SET, VTYPEPARS_COLOR_SET, MSVehicleType::wasSet(), SUMOVehicleParameter::wasSet(), Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIBaseVehicle::setColor().
setLastEntryTime()
void MEVehicle::setLastEntryTime (SUMOTime t) inline inherited
Sets the entry time for the current segment.
Parameters
[in] t The entry time
Definition at line 245 of file MEVehicle.h.
References MEVehicle::myLastEntryTime.
Referenced by MESegment::receive().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setSegment()
virtual void MEVehicle::setSegment (MESegment * s, int idx = 0) inline virtual inherited
Sets the current segment the vehicle is at together with its que.
Parameters
[in] s The current segment
[in] q The current que
Definition at line 220 of file MEVehicle.h.
References MEVehicle::myQueIndex, and MEVehicle::mySegment.
Referenced by MELoop::changeSegment(), METriggeredCalibrator::execute(), MEVehicle::loadState(), MESegment::receive(), and MELoop::teleportVehicle().
succEdge()
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), libsumo::Vehicle::moveTo(), MELoop::nextSegment(), and MESegment::receive().
updateDetectorForWriting()
void MEVehicle::updateDetectorForWriting (MSMoveReminder * rem, SUMOTime currentTime, SUMOTime exitTime) inherited
Updates a single vehicle detector if present.
Definition at line 288 of file MEVehicle.cpp.
References MESegment::getIndex(), MEVehicle::getLastEntryTime(), MESegment::getLength(), MSBaseVehicle::myMoveReminders, MEVehicle::mySegment, and MSMoveReminder::updateDetector().
Referenced by MEVehicle::getBlockTimeSeconds().
updateDetectors()
void MEVehicle::updateDetectors (SUMOTime currentTime, const bool isLeave, const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_JUNCTION) inherited
Updates all vehicle detectors.
Definition at line 306 of file MEVehicle.cpp.
References MEVehicle::getEventTime(), MESegment::getIndex(), MEVehicle::getLastEntryTime(), MESegment::getLength(), MSBaseVehicle::myMoveReminders, MEVehicle::mySegment, and MSMoveReminder::NOTIFICATION_SEGMENT.
Referenced by MEVehicle::getBlockTimeSeconds(), MESegment::setSpeedForQueue(), and MESegment::updateDetectorsOnLeave().
Field Documentation
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
myAdditionalVisualizations
std::map<GUISUMOAbstractView*, int> GUIBaseVehicle::myAdditionalVisualizations inherited
Enabled visualisations, per view.
Definition at line 301 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), GUIVehicle::drawOutsideNetwork(), GUIBaseVehicle::getPopUpMenu(), GUIBaseVehicle::hasActiveAddVisualisation(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::~GUIBaseVehicle().
myArrivalLane
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 487 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and MSVehicle::updateBestLanes().
myArrivalPos
double MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 484 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and MSVehicle::updateBestLanes().
myBlockTime
SUMOTime MEVehicle::myBlockTime protected inherited
The time at which the vehicle was blocked on its current segment.
Definition at line 359 of file MEVehicle.h.
Referenced by MEVehicle::getBlockTime(), MEVehicle::getWaitingTime(), MEVehicle::loadState(), MEVehicle::saveState(), and MEVehicle::setBlockTime().
myChosenSpeedFactor
double MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 457 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
myCurrEdge
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 454 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::enterLaneAtMove(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), MSVehicle::getRerouteOrigin(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MSVehicle::leaveLane(), MEVehicle::loadState(), MSVehicle::loadState(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLaneAdvances(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), and MSVehicle::willPass().
myDepartPos
double MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 481 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), and MSVehicle::saveState().
myDeparture
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 478 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), MEVehicle::loadState(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), MEVehicle::saveState(), and MSVehicle::saveState().
myDevices
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 475 of file MSBaseVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::createDevice(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDeviceParameter(), MSBaseVehicle::getDevices(), getParameterWindow(), GUIVehicle::getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::hasDevice(), MSBaseVehicle::MSBaseVehicle(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::setDeviceParameter(), and MSBaseVehicle::~MSBaseVehicle().
myEventTime
SUMOTime MEVehicle::myEventTime protected inherited
The (planned) time of leaving the segment (cell)
Definition at line 353 of file MEVehicle.h.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getEventTime(), MEVehicle::getWaitingTime(), MEVehicle::hasArrived(), MEVehicle::loadState(), MEVehicle::saveState(), and MEVehicle::setEventTime().
myLastEntryTime
SUMOTime MEVehicle::myLastEntryTime protected inherited
The time the vehicle entered its current segment.
Definition at line 356 of file MEVehicle.h.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getLastEntryTime(), MEVehicle::loadState(), MEVehicle::saveState(), MEVehicle::setBlockTime(), MEVehicle::setEventTime(), and MEVehicle::setLastEntryTime().
myLock
MFXMutex GUIBaseVehicle::myLock mutable protected inherited
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 349 of file GUIBaseVehicle.h.
Referenced by GUIVehicle::drawBestLanes(), and GUIBaseVehicle::~GUIBaseVehicle().
myMoveReminders
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Currently relevant move reminders.
Definition at line 471 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), MSVehicle::leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and MSVehicle::workOnMoveReminders().
myNumberReroutes
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 490 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), MSVehicle::replaceRoute(), and MEVehicle::replaceRoute().
myParameter
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This vehicle's parameter.
Definition at line 445 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSVehicle::addTraciStop(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::createDevice(), MSVehicle::enterLaneAtMove(), MSVehicle::getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), getParameterWindow(), GUIVehicle::getParameterWindow(), MSVehicle::getPersonNumber(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::replaceParkingArea(), MSBaseVehicle::reroute(), MEVehicle::saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSVehicle::updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
myQueIndex
int MEVehicle::myQueIndex protected inherited
Index of the que the vehicle is in (important for multiqueue extension)
Definition at line 350 of file MEVehicle.h.
Referenced by MEVehicle::getQueIndex(), and MEVehicle::setSegment().
myRoute
const MSRoute* MSBaseVehicle::myRoute protected inherited
This vehicle's route.
Definition at line 448 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), GUIVehicle::drawRouteHelper(), MSVehicle::getDistanceToPosition(), MSVehicle::getRerouteOrigin(), MSBaseVehicle::getRoute(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and MSBaseVehicle::~MSBaseVehicle().
mySeatPositions
PositionVector GUIBaseVehicle::mySeatPositions mutable protected inherited
positions of seats in the vehicle (updated at every drawing step)
Definition at line 352 of file GUIBaseVehicle.h.
Referenced by GUIVehicle::computeSeats(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getSeatPosition(), and GUIBaseVehicle::GUIBaseVehicle().
mySegment
MESegment* MEVehicle::mySegment protected inherited
The segment the vehicle is at.
Definition at line 347 of file MEVehicle.h.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getCurrentLinkPenaltySeconds(), MEVehicle::getPositionOnLane(), MEVehicle::getSegment(), MEVehicle::hasArrived(), MEVehicle::isStopped(), MEVehicle::mayProceed(), MEVehicle::replaceRoute(), MEVehicle::saveState(), MEVehicle::setEventTime(), MEVehicle::setSegment(), MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
myStops
std::map<const MESegment* const, SUMOTime> MEVehicle::myStops protected inherited
where to stop
Definition at line 362 of file MEVehicle.h.
Referenced by MEVehicle::addStop(), MEVehicle::getStopEdges(), MEVehicle::getStoptime(), MEVehicle::isStopped(), and MEVehicle::saveState().
myType
MSVehicleType* MSBaseVehicle::myType protected inherited
This vehicle's type.
Definition at line 451 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getActionStepLength(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getCarFollowModel(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSBaseVehicle::getLength(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getMaxSpeedOnLane(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getSingularType(), getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MSBaseVehicle::hasValidRoute(), MSVehicle::processNextStop(), MSBaseVehicle::replaceVehicleType(), MSVehicle::updateBestLanes(), and MSVehicle::~MSVehicle().
NOT_YET_DEPARTED
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 495 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::hasDeparted(), and MSVehicle::Influencer::postProcessRemoteControl().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIMEVehicle.h
GUIMEVehicle.cpp