SUMO - Simulation of Urban MObility: NWWriter_SUMO Class Reference
NWWriter_SUMO Class Reference
Exporter writing networks using the SUMO format.
#include <NWWriter_SUMO.h>
Public Types
enum ConnectionStyle { SUMONET, PLAIN, TLL }
Static Public Member Functions
static void writeConnection (OutputDevice &into, const NBEdge &from, const NBEdge::Connection &c, bool includeInternal, ConnectionStyle style=SUMONET)
Writes connections outgoing from the given edge (also used in NWWriter_XML)
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a SUMO-file.
static void writeProhibitions (OutputDevice &into, const NBConnectionProhibits &prohibitions)
writes the given prohibitions
static void writeRoundabouts (OutputDevice &into, const std::set< EdgeSet > &roundabouts, const NBEdgeCont &ec)
Writes roundabouts.
static void writeTrafficLights (OutputDevice &into, const NBTrafficLightLogicCont &tllCont)
writes the traffic light logics to the given device
Static Private Member Functions
Methods for writing network parts
static bool writeInternalEdges (OutputDevice &into, const NBEdgeCont &ec, const NBNode &n)
Writes internal edges (<edge ... with id[0]==':') of the given node.
static void writeEdge (OutputDevice &into, const NBEdge &e, bool noNames)
Writes an edge (<edge ...)
static void writeLane (OutputDevice &into, const std::string &lID, double speed, SVCPermissions permissions, SVCPermissions preferred, double endOffset, double width, PositionVector shape, const Parameterised *params, double length, int index, const std::string &oppositeID, bool accelRamp=false, bool customShape=false)
Writes a lane (<lane ...) of an edge.
static void writeJunction (OutputDevice &into, const NBNode &n, const bool checkLaneFoes)
Writes a junction (<junction ...)
static bool writeInternalNodes (OutputDevice &into, const NBNode &n)
Writes internal junctions (<junction with id[0]==':' ...) of the given node.
static bool writeInternalConnections (OutputDevice &into, const NBNode &n)
Writes inner connections within the node.
static void writeDistrict (OutputDevice &into, const NBDistrict &d)
Writes a district.
static void writeInternalConnection (OutputDevice &into, const std::string &from, const std::string &to, int fromLane, int toLane, const std::string &via, LinkDirection dir=LINKDIR_STRAIGHT)
Writes a single internal connection.
static std::string writeSUMOTime (SUMOTime time)
writes a SUMOTime as int if possible, otherwise as a float
static std::string prohibitionConnection (const NBConnection &c)
the attribute value for a prohibition
static void writeRoundabout (OutputDevice &into, const std::vector< std::string > &r, const NBEdgeCont &ec)
Writes a roundabout.
static std::string getOppositeInternalID (const NBEdgeCont &ec, const NBEdge *from, const NBEdge::Connection &con)
retrieve the id of the opposite direction internal lane if it exists
Detailed Description
Exporter writing networks using the SUMO format.
Definition at line 62 of file NWWriter_SUMO.h.
Member Enumeration Documentation
ConnectionStyle
enum NWWriter_SUMO::ConnectionStyle
Enumerator
SUMONET
PLAIN
TLL
Definition at line 65 of file NWWriter_SUMO.h.
Member Function Documentation
getOppositeInternalID()
std::string NWWriter_SUMO::getOppositeInternalID (const NBEdgeCont & ec, const NBEdge * from, const NBEdge::Connection & con) static private
retrieve the id of the opposite direction internal lane if it exists
Definition at line 231 of file NWWriter_SUMO.cpp.
References NBEdge::Connection::fromLane, NBEdge::getConnections(), NBEdge::Connection::getInternalLaneID(), NBEdge::getLaneID(), NBEdge::getLanes(), PositionVector::length(), NBEdge::Lane::oppositeID, NBEdgeCont::retrieve(), NBEdge::Connection::shape, NBEdge::Connection::toEdge, and NBEdge::Connection::toLane.
Referenced by writeInternalEdges().
prohibitionConnection()
std::string NWWriter_SUMO::prohibitionConnection (const NBConnection & c) static private
the attribute value for a prohibition
Definition at line 783 of file NWWriter_SUMO.cpp.
References NBConnection::getFrom(), Named::getID(), and NBConnection::getTo().
Referenced by writeProhibitions().
writeConnection()
void NWWriter_SUMO::writeConnection (OutputDevice & into, const NBEdge & from, const NBEdge::Connection & c, bool includeInternal, ConnectionStyle style = SUMONET) static
Writes connections outgoing from the given edge (also used in NWWriter_XML)
Parameters
[in] into The device to write the edge into
[in] from The edge to write connections for
[in] c The connection to write
[in] includeInternal Whether information about inner-lanes used to cross the intersection shall be written
[in] plain Whether only plain-xml output should be written (omit some attributes)
Definition at line 574 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBEdge::Connection::contPos, NBEdge::Connection::customShape, NBEdge::Connection::fromLane, OptionsCont::getBool(), NBNode::getDirection(), Named::getID(), NBEdge::Connection::getInternalLaneID(), NBNode::getKeepClear(), NBNode::getLinkState(), OptionsCont::getOptions(), NBEdge::getToNode(), NBEdge::Connection::keepClear, LINKDIR_NODIR, NBEdge::Connection::mayDefinitelyPass, OutputDevice::openTag(), PLAIN, NBEdge::Connection::speed, SUMO_ATTR_CONTPOS, SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_PASS, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_TAG_CONNECTION, SUMONET, NBEdge::Connection::tlID, TLL, NBEdge::Connection::tlLinkNo, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, toString(), NBEdge::UNSPECIFIED_CONTPOS, NBEdge::UNSPECIFIED_SPEED, NBEdge::UNSPECIFIED_VISIBILITY_DISTANCE, NBEdge::Connection::visibility, and OutputDevice::writeAttr().
Referenced by NWWriter_XML::writeEdgesAndConnections(), writeNetwork(), and NWWriter_XML::writeTrafficLights().
writeDistrict()
void NWWriter_SUMO::writeDistrict (OutputDevice & into, const NBDistrict & d) static private
Writes a district.
Parameters
[in] into The device to write the edge into
[in] d The district
Definition at line 726 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), Named::getID(), NBDistrict::getShape(), NBDistrict::getSinkEdges(), NBDistrict::getSinkWeights(), NBDistrict::getSourceEdges(), NBDistrict::getSourceWeights(), VectorHelper< T >::normaliseSum(), OutputDevice::openTag(), SUMO_ATTR_ID, SUMO_ATTR_SHAPE, SUMO_ATTR_WEIGHT, SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, SUMO_TAG_TAZSOURCE, and OutputDevice::writeAttr().
Referenced by writeNetwork().
writeEdge()
void NWWriter_SUMO::writeEdge (OutputDevice & into, const NBEdge & e, bool noNames) static private
Writes an edge (<edge ...)
Parameters
[in] into The device to write the edge into
[in] e The edge to write
[in] noNames Whether names shall be ignored
See also
writeLane()
Definition at line 356 of file NWWriter_SUMO.cpp.
References NBEdge::Lane::accelRamp, OutputDevice::closeTag(), NBEdge::Lane::customShape, EDGEFUNC_CONNECTOR, NBEdge::Lane::endOffset, StringUtils::escapeXML(), NBEdge::getFinalLength(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLanes(), NBEdge::getLaneSpreadFunction(), NBEdge::getLoadedLength(), NBEdge::getPriority(), NBEdge::getStreetName(), NBEdge::getToNode(), NBEdge::getTypeID(), NBEdge::hasDefaultGeometry(), NBEdge::hasLoadedLength(), NBEdge::isMacroscopicConnector(), LANESPREAD_RIGHT, OutputDevice::openTag(), NBEdge::Lane::oppositeID, NBEdge::Lane::permissions, NBEdge::Lane::preferred, NBEdge::Lane::shape, NBEdge::Lane::speed, SUMO_ATTR_FROM, SUMO_ATTR_FUNCTION, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_TAG_EDGE, NBEdge::Lane::width, OutputDevice::writeAttr(), writeLane(), and Parameterised::writeParams().
Referenced by writeNetwork().
writeInternalConnection()
void NWWriter_SUMO::writeInternalConnection (OutputDevice & into, const std::string & from, const std::string & to, int fromLane, int toLane, const std::string & via, LinkDirection dir = LINKDIR_STRAIGHT) static private
Writes a single internal connection.
Parameters
[in] from The id of the from-edge
[in] to The id of the to-edge
[in] toLane The indexd of the to-lane
[in] via The (optional) via edge
Definition at line 652 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_STATE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMO_TAG_CONNECTION, and OutputDevice::writeAttr().
Referenced by writeInternalConnections(), and writeNetwork().
writeInternalConnections()
bool NWWriter_SUMO::writeInternalConnections (OutputDevice & into, const NBNode & n) static private
Writes inner connections within the node.
Parameters
[in] into The device to write the edge into
[in] n The node to write inner links for
Definition at line 625 of file NWWriter_SUMO.cpp.
References OptionsCont::getBool(), NBEdge::getConnections(), NBNode::getDirection(), Named::getID(), NBNode::getIncomingEdges(), OptionsCont::getOptions(), NBEdge::Connection::haveVia, NBEdge::Connection::id, NBEdge::Connection::internalLaneIndex, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, NBEdge::Connection::viaID, and writeInternalConnection().
Referenced by writeNetwork().
writeInternalEdges()
bool NWWriter_SUMO::writeInternalEdges (OutputDevice & into, const NBEdgeCont & ec, const NBNode & n) static private
Writes internal edges (<edge ... with id[0]==':') of the given node.
Parameters
[in] into The device to write the edges into
[in] n The node to write the edges of
Returns
Whether an internal edge was written
Definition at line 260 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), EDGEFUNC_CROSSING, EDGEFUNC_INTERNAL, EDGEFUNC_WALKINGAREA, NBNode::getCrossings(), NBNode::getIncomingEdges(), getOppositeInternalID(), NBNode::getWalkingAreas(), NBNode::WalkingArea::hasCustomShape, NBNode::WalkingArea::id, NBNode::WalkingArea::length, MAX2(), OutputDevice::openTag(), NBEdge::Lane::permissions, POSITION_EPS, NBEdge::Lane::preferred, NBNode::WalkingArea::shape, SUMO_ATTR_CROSSING_EDGES, SUMO_ATTR_FUNCTION, SUMO_ATTR_ID, SUMO_TAG_EDGE, SVC_PEDESTRIAN, SVCAll, NBEdge::UNSPECIFIED_OFFSET, NBEdge::Lane::width, NBNode::WalkingArea::width, OutputDevice::writeAttr(), and writeLane().
Referenced by writeNetwork().
writeInternalNodes()
bool NWWriter_SUMO::writeInternalNodes (OutputDevice & into, const NBNode & n) static private
Writes internal junctions (<junction with id[0]==':' ...) of the given node.
Parameters
[in] into The device to write the edge into
[in] n The junction/node to write internal nodes for
Definition at line 527 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBNode::getCrossings(), NBNode::getIncomingEdges(), joinToString(), NODETYPE_INTERNAL, OutputDevice::openTag(), SUMO_ATTR_ID, SUMO_ATTR_INCLANES, SUMO_ATTR_INTLANES, SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, OutputDevice::writeAttr(), and NWFrame::writePositionLong().
Referenced by writeNetwork().
writeJunction()
void NWWriter_SUMO::writeJunction (OutputDevice & into, const NBNode & n, const bool checkLaneFoes) static private
Writes a junction (<junction ...)
Parameters
[in] into The device to write the edge into
[in] n The junction/node to write
[in] checkLaneFoes Whether laneConflicts shall be checked at this junction
Definition at line 452 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBNode::getCrossings(), Named::getID(), NBNode::getIncomingEdges(), OptionsCont::getOptions(), NBNode::getPosition(), NBNode::getRadius(), NBNode::getShape(), NBNode::getType(), NBNode::hasCustomShape(), NODETYPE_DEAD_END, NODETYPE_NOJUNCTION, OutputDevice::openTag(), PositionVector::simplified(), SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_ID, SUMO_ATTR_INCLANES, SUMO_ATTR_INTLANES, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, NBNode::UNSPECIFIED_RADIUS, OutputDevice::writeAttr(), NBNode::writeLogic(), Parameterised::writeParams(), and NWFrame::writePositionLong().
Referenced by writeNetwork().
writeLane()
void NWWriter_SUMO::writeLane (OutputDevice & into, const std::string & lID, double speed, SVCPermissions permissions, SVCPermissions preferred, double endOffset, double width, PositionVector shape, const Parameterised * params, double length, int index, const std::string & oppositeID, bool accelRamp = false, bool customShape = false) static private
Writes a lane (<lane ...) of an edge.
Parameters
[in] into The device to write the edge into
[in] lID The ID of the lane
[in] origID The original ID of the edge in the input
[in] length Lane's length
[in] index The index of the lane within the edge
[in] oppositeID The ID of the opposite lane for overtaking
[in] accelRamp whether this lane is an acceleration lane
[in] customShape whether this lane has a custom shape
Definition at line 398 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), PositionVector::getSubpart(), PositionVector::length(), OutputDevice::openTag(), SUMO_ATTR_ACCELERATION, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LANE, SUMO_ATTR_LENGTH, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, SUMO_TAG_LANE, SUMO_TAG_NEIGH, SVC_UNSPECIFIED, toString(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, WRITE_WARNING, OutputDevice::writeAttr(), Parameterised::writeParams(), writePermissions(), and writePreferences().
Referenced by writeEdge(), and writeInternalEdges().
writeNetwork()
void NWWriter_SUMO::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into a SUMO-file.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 60 of file NWWriter_SUMO.cpp.
References NBDistrictCont::begin(), NBNodeCont::begin(), NBEdgeCont::begin(), OutputDevice::close(), OutputDevice::closeTag(), NBDistrictCont::end(), NBNodeCont::end(), NBEdgeCont::end(), OptionsCont::getBool(), NBEdge::getConnections(), NBNode::getCrossing(), NBNode::getCrossings(), OutputDevice::getDevice(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), OptionsCont::getInt(), NBNetBuilder::getNodeCont(), NBEdgeCont::getRoundabouts(), OptionsCont::getString(), NBNetBuilder::getTLLogicCont(), NBNetBuilder::getTypeCont(), NBNode::getWalkingAreas(), NBHelpers::interpretLaneID(), OptionsCont::isDefault(), OptionsCont::isSet(), OutputDevice::lf(), LINKDIR_STRAIGHT, LINKSTATE_MAJOR, LINKSTATE_MINOR, NWFrame::MAJOR_VERSION, OutputDevice::openTag(), NBNode::Crossing::priority, NBDistrictCont::size(), SUMO_ATTR_CORNERDETAIL, SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_LEFTHAND, SUMO_ATTR_LINKDETAIL, SUMO_ATTR_RECTANGULAR_LANE_CUT, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VERSION, SUMO_ATTR_WALKINGAREAS, SUMO_TAG_CONNECTION, NBNode::Crossing::tlID, NBNode::Crossing::tlLinkNo, toString(), OutputDevice::writeAttr(), writeConnection(), writeDistrict(), writeEdge(), writeInternalConnection(), writeInternalConnections(), writeInternalEdges(), writeInternalNodes(), writeJunction(), GeoConvHelper::writeLocation(), writeProhibitions(), writeRoundabouts(), writeTrafficLights(), NBTypeCont::writeTypes(), and OutputDevice::writeXMLHeader().
Referenced by NWFrame::writeNetwork().
writeProhibitions()
void NWWriter_SUMO::writeProhibitions (OutputDevice & into, const NBConnectionProhibits & prohibitions) static
writes the given prohibitions
Definition at line 767 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), prohibitionConnection(), SUMO_ATTR_PROHIBITED, SUMO_ATTR_PROHIBITOR, SUMO_TAG_PROHIBITION, and OutputDevice::writeAttr().
Referenced by NWWriter_XML::writeEdgesAndConnections(), and writeNetwork().
writeRoundabout()
void NWWriter_SUMO::writeRoundabout (OutputDevice & into, const std::vector< std::string > & r, const NBEdgeCont & ec) static private
Writes a roundabout.
Parameters
[in] into The device to write the edge into
[in] r The roundabout to write
[in] ec The edge control to retrieve named edges from
Definition at line 697 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), Named::getID(), NBEdge::getToNode(), joinToString(), OutputDevice::openTag(), NBEdgeCont::retrieve(), SUMO_ATTR_EDGES, SUMO_ATTR_NODES, SUMO_TAG_ROUNDABOUT, WRITE_WARNING, and OutputDevice::writeAttr().
Referenced by writeRoundabouts().
writeRoundabouts()
void NWWriter_SUMO::writeRoundabouts (OutputDevice & into, const std::set< EdgeSet > & roundabouts, const NBEdgeCont & ec) static
Writes roundabouts.
Parameters
[in] into The device to write the edge into
[in] roundaboutes The roundabouts to write
[in] ec The edge control to retrieve named edges from
Definition at line 671 of file NWWriter_SUMO.cpp.
References OutputDevice::lf(), and writeRoundabout().
Referenced by NWWriter_XML::writeEdgesAndConnections(), and writeNetwork().
writeSUMOTime()
std::string NWWriter_SUMO::writeSUMOTime (SUMOTime time) static private
writes a SUMOTime as int if possible, otherwise as a float
Definition at line 756 of file NWWriter_SUMO.cpp.
References STEPS2TIME, and toString().
Referenced by writeTrafficLights().
writeTrafficLights()
void NWWriter_SUMO::writeTrafficLights (OutputDevice & into, const NBTrafficLightLogicCont & tllCont) static
writes the traffic light logics to the given device
Definition at line 789 of file NWWriter_SUMO.cpp.
References OutputDevice::closeTag(), NBTrafficLightLogicCont::getComputed(), OutputDevice::lf(), OutputDevice::openTag(), SUMO_ATTR_DURATION, SUMO_ATTR_ID, SUMO_ATTR_MAXDURATION, SUMO_ATTR_MINDURATION, SUMO_ATTR_OFFSET, SUMO_ATTR_PROGRAMID, SUMO_ATTR_STATE, SUMO_ATTR_TYPE, SUMO_TAG_PHASE, SUMO_TAG_TLLOGIC, TLTYPE_STATIC, NBTrafficLightDefinition::UNSPECIFIED_DURATION, OutputDevice::writeAttr(), and writeSUMOTime().
Referenced by writeNetwork(), and NWWriter_XML::writeTrafficLights().
The documentation for this class was generated from the following files:
NWWriter_SUMO.h
NWWriter_SUMO.cpp