SUMO - Simulation of Urban MObility: libsumo::POI Class Reference
libsumo::POI Class Reference
#include <POI.h>
Static Public Member Functions
static bool add (const std::string &poiID, const TraCIPosition &pos, const TraCIColor &c, const std::string &type, int layer)
static TraCIColor getColor (const std::string &poiID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::string getParameter (const std::string &poiID, const std::string &param)
static TraCIPosition getPosition (const std::string &poiID)
static NamedRTree * getTree ()
Returns a tree filled with PoI instances.
static std::string getType (const std::string &poiID)
static bool remove (const std::string &poiID, int layer=0)
static void setColor (const std::string &poiID, const TraCIColor &c)
static void setParameter (const std::string &poiID, const std::string &param, const std::string &value)
static void setPosition (const std::string &poiID, const TraCIPosition &pos)
static void setType (const std::string &poiID, const std::string &setType)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
POI & operator= (const POI &src)
invalidated assignment operator
POI ()
invalidated standard constructor
POI (const POI &src)
invalidated copy constructor
Static Private Member Functions
static PointOfInterest * getPoI (const std::string &id)
Detailed Description
Definition at line 53 of file POI.h.
Constructor & Destructor Documentation
POI() [1/2]
libsumo::POI::POI () private
invalidated standard constructor
POI() [2/2]
libsumo::POI::POI (const POI & src) private
invalidated copy constructor
Member Function Documentation
add()
bool POI::add (const std::string & poiID, const TraCIPosition & pos, const TraCIColor & c, const std::string & type, int layer) static
Definition at line 107 of file POI.cpp.
References ShapeContainer::addPOI(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, MSNet::getInstance(), MSNet::getShapeContainer(), libsumo::Helper::makePosition(), and libsumo::Helper::makeRGBColor().
Referenced by TraCIServerAPI_POI::processSet().
getColor()
TraCIColor POI::getColor (const std::string & poiID) static
Definition at line 66 of file POI.cpp.
References Shape::getColor(), getPoI(), and libsumo::Helper::makeTraCIColor().
Referenced by TraCIServerAPI_POI::processGet().
getIDCount()
int POI::getIDCount () static
Definition at line 56 of file POI.cpp.
References getIDList().
Referenced by TraCIServerAPI_POI::processGet().
getIDList()
std::vector< std::string > POI::getIDList () static
Definition at line 48 of file POI.cpp.
References MSNet::getInstance(), ShapeContainer::getPOIs(), MSNet::getShapeContainer(), and NamedObjectCont< T >::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_POI::processGet().
getParameter()
std::string POI::getParameter (const std::string & poiID, const std::string & param) static
Definition at line 83 of file POI.cpp.
References Parameterised::getParameter(), and getPoI().
Referenced by TraCIServerAPI_POI::processGet().
getPoI()
PointOfInterest * POI::getPoI (const std::string & id) static private
Definition at line 130 of file POI.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), ShapeContainer::getPOIs(), and MSNet::getShapeContainer().
Referenced by getColor(), getParameter(), getPosition(), getType(), setColor(), setParameter(), setPosition(), and setType().
getPosition()
TraCIPosition POI::getPosition (const std::string & poiID) static
Definition at line 73 of file POI.cpp.
References getPoI(), Position::x(), libsumo::TraCIPosition::x, Position::y(), libsumo::TraCIPosition::y, Position::z(), and libsumo::TraCIPosition::z.
Referenced by TraCIServerAPI_POI::processGet().
getTree()
NamedRTree * POI::getTree () static
Returns a tree filled with PoI instances.
Returns
The rtree of PoIs
Definition at line 140 of file POI.cpp.
References MSNet::getInstance(), ShapeContainer::getPOIs(), MSNet::getShapeContainer(), and NamedRTree::Insert().
getType()
std::string POI::getType (const std::string & poiID) static
Definition at line 61 of file POI.cpp.
References getPoI(), and Shape::getType().
Referenced by TraCIServerAPI_POI::processGet().
operator=()
POI& libsumo::POI::operator= (const POI & src) private
invalidated assignment operator
remove()
bool POI::remove (const std::string & poiID, int layer = 0) static
Definition at line 117 of file POI.cpp.
References MSNet::getInstance(), MSNet::getShapeContainer(), and ShapeContainer::removePOI().
Referenced by TraCIServerAPI_POI::processSet().
setColor()
void POI::setColor (const std::string & poiID, const TraCIColor & c) static
Definition at line 101 of file POI.cpp.
References getPoI(), libsumo::Helper::makeRGBColor(), and Shape::setColor().
Referenced by TraCIServerAPI_POI::processSet().
setParameter()
void POI::setParameter (const std::string & poiID, const std::string & param, const std::string & value) static
Definition at line 123 of file POI.cpp.
References getPoI(), and Parameterised::setParameter().
Referenced by TraCIServerAPI_POI::processSet().
setPosition()
void POI::setPosition (const std::string & poiID, const TraCIPosition & pos) static
Definition at line 95 of file POI.cpp.
References getPoI(), libsumo::Helper::makePosition(), and Position::set().
Referenced by TraCIServerAPI_POI::processSet().
setType()
void POI::setType (const std::string & poiID, const std::string & setType) static
Definition at line 89 of file POI.cpp.
References getPoI(), and Shape::setType().
Referenced by TraCIServerAPI_POI::processSet().
subscribe()
static void libsumo::POI::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
subscribeContext()
static void libsumo::POI::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
POI.h
POI.cpp