SUMO - Simulation of Urban MObility: NBEdge::MainDirections Class Reference
NBEdge::MainDirections Class Reference
Holds (- relative to the edge it is build from -!!!) the list of main directions a vehicle that drives on this street may take on the junction the edge ends in The back direction is not regarded.
Public Types
enum Direction { DIR_RIGHTMOST, DIR_LEFTMOST, DIR_FORWARD }
enum of possible directions
Public Member Functions
bool empty () const
returns the information whether no following street has a higher priority
bool includes (Direction d) const
returns the information whether the street in the given direction has a higher priority
MainDirections (const EdgeVector &outgoing, NBEdge *parent, NBNode *to, int indexOfStraightest)
constructor
~MainDirections ()
destructor
Data Fields
std::vector< Direction > myDirs
list of the main direction within the following junction relative to the edge
Private Member Functions
MainDirections (const MainDirections &)
Invalidated copy constructor.
MainDirections & operator= (const MainDirections &)
Invalidated assignment operator.
Detailed Description
Holds (- relative to the edge it is build from -!!!) the list of main directions a vehicle that drives on this street may take on the junction the edge ends in The back direction is not regarded.
Definition at line 1264 of file NBEdge.h.
Member Enumeration Documentation
Direction
enum NBEdge::MainDirections::Direction
enum of possible directions
Enumerator
DIR_RIGHTMOST
DIR_LEFTMOST
DIR_FORWARD
Definition at line 1267 of file NBEdge.h.
Constructor & Destructor Documentation
MainDirections() [1/2]
NBEdge::MainDirections::MainDirections (const EdgeVector & outgoing, NBEdge * parent, NBNode * to, int indexOfStraightest)
constructor
Definition at line 173 of file NBEdge.cpp.
References DEBUGCOND2, DIR_FORWARD, DIR_LEFTMOST, DIR_RIGHTMOST, NBNode::getDirection(), Named::getID(), NBEdge::getJunctionPriority(), NBNode::getType(), NBNode::isTrafficLight(), LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_STRAIGHT, and toString().
~MainDirections()
NBEdge::MainDirections::~MainDirections ()
destructor
Definition at line 221 of file NBEdge.cpp.
MainDirections() [2/2]
NBEdge::MainDirections::MainDirections (const MainDirections &) private
Invalidated copy constructor.
Member Function Documentation
empty()
bool NBEdge::MainDirections::empty () const
returns the information whether no following street has a higher priority
Definition at line 225 of file NBEdge.cpp.
Referenced by NBEdge::prepareEdgePriorities().
includes()
bool NBEdge::MainDirections::includes (Direction d) const
returns the information whether the street in the given direction has a higher priority
Definition at line 231 of file NBEdge.cpp.
Referenced by NBEdge::prepareEdgePriorities().
operator=()
MainDirections& NBEdge::MainDirections::operator= (const MainDirections &) private
Invalidated assignment operator.
Field Documentation
myDirs
std::vector<Direction> NBEdge::MainDirections::myDirs
list of the main direction within the following junction relative to the edge
Definition at line 1270 of file NBEdge.h.
Referenced by NBEdge::prepareEdgePriorities().
The documentation for this class was generated from the following files:
NBEdge.h
NBEdge.cpp