SUMO - Simulation of Urban MObility: OptionsLoader Class Reference
OptionsLoader Class Reference
A SAX-Handler for loading options.
#include <OptionsLoader.h>
Public Member Functions
bool errorOccured () const
Returns the information whether an error occured.
const std::string & getItem () const
Returns the last item read.
OptionsLoader (const bool routeOnly=false)
Constructor.
~OptionsLoader ()
Handlers for the SAX DocumentHandler interface
virtual void startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList &attributes)
Called on the occurence of the beginning of a tag.
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
Called on the occurence of character data.
void endElement (const XMLCh *const name)
Called on the end of an element.
Handlers for the SAX ErrorHandler interface
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Called on an XML-warning.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Called on an XML-error.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Called on an XML-fatal error.
Private Member Functions
OptionsLoader & operator= (const OptionsLoader &s)
OptionsLoader (const OptionsLoader &s)
bool setSecure (const std::string &name, const std::string &value) const
Tries to set the named option to the given value.
void setValue (const std::string &key, std::string &value)
Tries to set the named option to the given value.
Private Attributes
bool myError
The information whether an error occured.
std::string myItem
The name of the currently parsed option.
OptionsCont & myOptions
The options to fill.
bool myRootOnly
The information whether only the root element should be parsed.
std::string myValue
The currently read characters string.
Detailed Description
A SAX-Handler for loading options.
Definition at line 53 of file OptionsLoader.h.
Constructor & Destructor Documentation
OptionsLoader() [1/2]
OptionsLoader::OptionsLoader (const bool routeOnly = false)
Constructor.
Definition at line 52 of file OptionsLoader.cpp.
Referenced by getItem().
~OptionsLoader()
OptionsLoader::~OptionsLoader ()
destructor
Definition at line 56 of file OptionsLoader.cpp.
OptionsLoader() [2/2]
OptionsLoader::OptionsLoader (const OptionsLoader & s) private
invalid copy constructor
Member Function Documentation
characters()
void OptionsLoader::characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
Called on the occurence of character data.
If this occurs inside a single tag it sets the option named by the tag to the value given by the character data. This is considered deprecated in favor of attributes.
Todo:
Describe better
Definition at line 92 of file OptionsLoader.cpp.
References TplConvert::_2str(), and myValue.
endElement()
void OptionsLoader::endElement (const XMLCh *const name)
Called on the end of an element.
Resets the element name
Definition at line 110 of file OptionsLoader.cpp.
References myItem, myValue, and setValue().
error()
void OptionsLoader::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception)
Called on an XML-error.
The warning is reported to the the error-instance of MsgHandler
Definition at line 134 of file OptionsLoader.cpp.
References TplConvert::_2str(), myError, toString(), and WRITE_ERROR.
errorOccured()
bool OptionsLoader::errorOccured () const
Returns the information whether an error occured.
Definition at line 158 of file OptionsLoader.cpp.
References myError.
Referenced by OptionsIO::getRoot(), and OptionsIO::loadConfiguration().
fatalError()
void OptionsLoader::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception)
Called on an XML-fatal error.
The warning is reported to the the error-instance of MsgHandler
Definition at line 146 of file OptionsLoader.cpp.
References TplConvert::_2str(), myError, toString(), and WRITE_ERROR.
getItem()
const std::string& OptionsLoader::getItem () const inline
Returns the last item read.
Definition at line 127 of file OptionsLoader.h.
References myItem, operator=(), OptionsLoader(), setSecure(), and setValue().
Referenced by OptionsIO::getRoot().
operator=()
OptionsLoader& OptionsLoader::operator= (const OptionsLoader & s) private
invalid assignment operator
Referenced by getItem().
setSecure()
bool OptionsLoader::setSecure (const std::string & name, const std::string & value) const private
Tries to set the named option to the given value.
Checks the item whether it was default before setting it. Returns the information whether the item was set before (was not a default value)
Parameters
[in] name The name of the option to set
[in] value The new value for the option
Returns
Whether the option could be set
Definition at line 99 of file OptionsLoader.cpp.
References OptionsCont::isWriteable(), myOptions, and OptionsCont::set().
Referenced by getItem(), and setValue().
setValue()
void OptionsLoader::setValue (const std::string & key, std::string & value) private
Tries to set the named option to the given value.
Also evaluates whether it is a boolean or a filename option and does the relevant checks / modifications.
Parameters
[in] key The name of the option to set
[in] value The new value for the option
Definition at line 76 of file OptionsLoader.cpp.
References myError, setSecure(), and WRITE_ERROR.
Referenced by endElement(), getItem(), and startElement().
startElement()
void OptionsLoader::startElement (const XMLCh *const name, XERCES_CPP_NAMESPACE::AttributeList & attributes) virtual
Called on the occurence of the beginning of a tag.
Sets the name of the last item
Definition at line 59 of file OptionsLoader.cpp.
References TplConvert::_2str(), myItem, myRootOnly, myValue, and setValue().
warning()
void OptionsLoader::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception)
Called on an XML-warning.
The warning is reported to the the warning-instance of MsgHandler
Definition at line 124 of file OptionsLoader.cpp.
References TplConvert::_2str(), myError, toString(), and WRITE_WARNING.
Field Documentation
myError
bool OptionsLoader::myError private
The information whether an error occured.
Definition at line 170 of file OptionsLoader.h.
Referenced by error(), errorOccured(), fatalError(), setValue(), and warning().
myItem
std::string OptionsLoader::myItem private
The name of the currently parsed option.
Definition at line 176 of file OptionsLoader.h.
Referenced by endElement(), getItem(), and startElement().
myOptions
OptionsCont& OptionsLoader::myOptions private
The options to fill.
Definition at line 173 of file OptionsLoader.h.
Referenced by setSecure().
myRootOnly
bool OptionsLoader::myRootOnly private
The information whether only the root element should be parsed.
Definition at line 167 of file OptionsLoader.h.
Referenced by startElement().
myValue
std::string OptionsLoader::myValue private
The currently read characters string.
Definition at line 179 of file OptionsLoader.h.
Referenced by characters(), endElement(), and startElement().
The documentation for this class was generated from the following files:
OptionsLoader.h
OptionsLoader.cpp