SUMO - Simulation of Urban MObility: LineReader Class Reference
LineReader Class Reference
Retrieves a file linewise and reports the lines to a handler.
#include <LineReader.h>
Public Member Functions
void close ()
Closes the reading.
std::string getFileName () const
Returns the name of the used file.
unsigned long getPosition ()
Returns the current position within the file.
bool good () const
Returns the information whether the stream is readable.
bool hasMore () const
Returns whether another line may be read (the file was not read completely)
LineReader ()
Constructor.
LineReader (const std::string &file)
Constructor.
void readAll (LineHandler &lh)
Reads the whole file linewise, reporting every line to the given LineHandler.
bool readLine (LineHandler &lh)
Reads a single (the next) line from the file and reports it to the given LineHandler.
std::string readLine ()
Reads a single (the next) line from the file and returns it.
void reinit ()
Reinitialises the reading (of the previous file)
bool setFile (const std::string &file)
Reinitialises the reader for reading from the given file.
void setPos (unsigned long pos)
Sets the current position within the file to the given value.
~LineReader ()
Destructor.
Private Attributes
int myAvailable
Information how many bytes are available within the used file.
char myBuffer [1024]
To override MSVC++-bugs, we use an own getline which uses this buffer.
std::string myFileName
the name of the file to read the contents from
int myRead
Information about how many characters were supplied to the LineHandler.
int myRread
Information how many bytes were read by the reader from the file.
std::string myStrBuffer
a string-buffer
std::ifstream myStrm
the stream used
Detailed Description
Retrieves a file linewise and reports the lines to a handler.
This class reads the contents from a file line by line and report them to a LineHandler-derivate.
See also
LineHandler
Todo:
No checks are done so far during reading/setting position etc.
Should not IOError be thrown if something fails?
Definition at line 57 of file LineReader.h.
Constructor & Destructor Documentation
LineReader() [1/2]
LineReader::LineReader ()
Constructor.
Definition at line 45 of file LineReader.cpp.
LineReader() [2/2]
LineReader::LineReader (const std::string & file)
Constructor.
Initialises reading from the file with the given name using setFile.
Parameters
[in] file The name of the file to open
See also
setFile
Definition at line 48 of file LineReader.cpp.
References reinit().
~LineReader()
LineReader::~LineReader ()
Destructor.
Definition at line 55 of file LineReader.cpp.
Member Function Documentation
close()
void LineReader::close ()
Closes the reading.
getFileName()
std::string LineReader::getFileName () const
Returns the name of the used file.
Returns
The name of the opened file
Definition at line 178 of file LineReader.cpp.
References myFileName.
Referenced by ODMatrix::getNextNonCommentLine(), RODFDetFlowLoader::read(), ODMatrix::readO(), and ODMatrix::readV().
getPosition()
unsigned long LineReader::getPosition ()
Returns the current position within the file.
Returns
The current position within the opened file
Definition at line 192 of file LineReader.cpp.
References myRread.
Referenced by NIImporter_VISUM::load().
good()
bool LineReader::good () const
Returns the information whether the stream is readable.
Returns
Whether the file is usable (good())
Definition at line 224 of file LineReader.cpp.
References myStrm.
Referenced by ODMatrix::getNextNonCommentLine(), and ODMatrix::loadMatrix().
hasMore()
bool LineReader::hasMore () const
Returns whether another line may be read (the file was not read completely)
Returns
Whether further reading is possible
Definition at line 59 of file LineReader.cpp.
References myAvailable, and myRread.
Referenced by ODMatrix::getNextNonCommentLine(), PCLoaderVisum::load(), NIImporter_VISUM::load(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), RODFDetFlowLoader::read(), ODMatrix::readO(), and ODMatrix::readV().
readAll()
void LineReader::readAll (LineHandler & lh)
Reads the whole file linewise, reporting every line to the given LineHandler.
When the LineHandler returns false, the reading will be aborted
Parameters
[in] lh The LineHandler to report read lines to
Definition at line 65 of file LineReader.cpp.
References myAvailable, myRread, and readLine().
Referenced by NIImporter_DlrNavteq::loadNetwork().
readLine() [1/2]
bool LineReader::readLine (LineHandler & lh)
Reads a single (the next) line from the file and reports it to the given LineHandler.
When the LineHandler returns false, the reading will be aborted
Parameters
[in] lh The LineHandler to report read lines to
Returns
Whether a further line exists
Definition at line 75 of file LineReader.cpp.
References myAvailable, myBuffer, myRead, myRread, myStrBuffer, myStrm, and LineHandler::report().
Referenced by ODMatrix::getNextNonCommentLine(), PCLoaderVisum::load(), NIImporter_VISUM::load(), ODMatrix::loadMatrix(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), main(), and RODFDetFlowLoader::read().
readLine() [2/2]
std::string LineReader::readLine ()
Reads a single (the next) line from the file and returns it.
Returns
The next line in the file
Definition at line 127 of file LineReader.cpp.
References myAvailable, myBuffer, myRead, myRread, myStrBuffer, and myStrm.
Referenced by readAll().
reinit()
void LineReader::reinit ()
Reinitialises the reading (of the previous file)
Definition at line 198 of file LineReader.cpp.
References myAvailable, myFileName, myRead, myRread, myStrBuffer, and myStrm.
Referenced by LineReader(), PCLoaderVisum::load(), NIImporter_VISUM::load(), and setFile().
setFile()
bool LineReader::setFile (const std::string & file)
Reinitialises the reader for reading from the given file.
Returns false when the file is not readable
Parameters
[in] file The name of the file to open
Returns
Whether the file could be opened
Definition at line 184 of file LineReader.cpp.
References myFileName, myStrm, and reinit().
Referenced by NIImporter_VISUM::load(), and NIImporter_DlrNavteq::loadNetwork().
setPos()
void LineReader::setPos (unsigned long pos)
Sets the current position within the file to the given value.
Parameters
[in] pos The new position within the file
Definition at line 215 of file LineReader.cpp.
References myRead, myRread, myStrBuffer, and myStrm.
Referenced by NIImporter_VISUM::load().
Field Documentation
myAvailable
int LineReader::myAvailable private
Information how many bytes are available within the used file.
Definition at line 169 of file LineReader.h.
Referenced by hasMore(), readAll(), readLine(), and reinit().
myBuffer
char LineReader::myBuffer[1024] private
To override MSVC++-bugs, we use an own getline which uses this buffer.
Definition at line 160 of file LineReader.h.
Referenced by readLine().
myFileName
std::string LineReader::myFileName private
the name of the file to read the contents from
Definition at line 154 of file LineReader.h.
Referenced by getFileName(), reinit(), and setFile().
myRead
int LineReader::myRead private
Information about how many characters were supplied to the LineHandler.
Definition at line 166 of file LineReader.h.
Referenced by readLine(), reinit(), and setPos().
myRread
int LineReader::myRread private
Information how many bytes were read by the reader from the file.
Definition at line 172 of file LineReader.h.
Referenced by getPosition(), hasMore(), readAll(), readLine(), reinit(), and setPos().
myStrBuffer
std::string LineReader::myStrBuffer private
a string-buffer
Definition at line 163 of file LineReader.h.
Referenced by readLine(), reinit(), and setPos().
myStrm
std::ifstream LineReader::myStrm private
the stream used
Definition at line 157 of file LineReader.h.
Referenced by good(), readLine(), reinit(), setFile(), and setPos().
The documentation for this class was generated from the following files:
LineReader.h
LineReader.cpp