SUMO - Simulation of Urban MObility: BinaryInputDevice.cpp File Reference
BinaryInputDevice.cpp File Reference
#include <config.h>
#include <string>
#include <utils/common/StdDefs.h>
#include <utils/geom/Position.h>
#include "BinaryFormatter.h"
#include "BinaryInputDevice.h"
Macros
#define BUF_MAX 10000
Functions
BinaryInputDevice & operator>> (BinaryInputDevice &os, char &c)
BinaryInputDevice & operator>> (BinaryInputDevice &os, unsigned char &c)
BinaryInputDevice & operator>> (BinaryInputDevice &os, int &i)
BinaryInputDevice & operator>> (BinaryInputDevice &os, double &f)
BinaryInputDevice & operator>> (BinaryInputDevice &os, bool &b)
BinaryInputDevice & operator>> (BinaryInputDevice &os, std::string &s)
BinaryInputDevice & operator>> (BinaryInputDevice &os, std::vector< std::string > &v)
BinaryInputDevice & operator>> (BinaryInputDevice &os, std::vector< int > &v)
BinaryInputDevice & operator>> (BinaryInputDevice &os, std::vector< std::vector< int > > &v)
BinaryInputDevice & operator>> (BinaryInputDevice &os, Position &p)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
2005-09-15
Version
$Id$
Definition in file BinaryInputDevice.cpp.
Macro Definition Documentation
BUF_MAX
#define BUF_MAX 10000
Definition at line 40 of file BinaryInputDevice.cpp.
Referenced by operator>>().
Function Documentation
operator>>() [1/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, char & c)
Parameters
[in,out] os The BinaryInputDevice to read the char from
[in] c The char to store the read value into
Returns
The used BinaryInputDevice for further processing
Definition at line 95 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_BYTE, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [2/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, unsigned char & c)
Parameters
[in,out] os The BinaryInputDevice to read the char from
[in] c The char to store the read value into
Returns
The used BinaryInputDevice for further processing
Definition at line 103 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_BYTE, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [3/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, int & i)
Parameters
[in,out] os The BinaryInputDevice to read the int from
[in] i The int to store the read value into
Returns
The used BinaryInputDevice for further processing
Definition at line 111 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_INTEGER, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [4/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, double & f)
Parameters
[in,out] os The BinaryInputDevice to read the double from
[in] i The double to store the read value into
Returns
The used BinaryInputDevice for further processing
Definition at line 119 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_FLOAT, BinaryFormatter::BF_SCALED2INT, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [5/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, bool & b)
Parameters
[in,out] os The BinaryInputDevice to read the bool from
[in] i The bool to store the read value into
Returns
The used BinaryInputDevice for further processing
Definition at line 133 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_BYTE, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [6/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, std::string & s)
Reads the length of the string as an int, first. Reads then the specified number of chars into "myBuffer". Please note that the buffer has a fixed size - longer strings will cause an error.
Parameters
[in,out] os The BinaryInputDevice to read the string from
[in] s The string to store the read value into
Returns
The used BinaryInputDevice for further processing
Todo:
Use either a buffer with a flexible size or report an error if the buffer is too small!
Definition at line 142 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_STRING, BUF_MAX, BinaryInputDevice::checkType(), MIN2(), BinaryInputDevice::myBuffer, and BinaryInputDevice::myStream.
operator>>() [7/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, std::vector< std::string > & v)
Reads the length of the vector as an int, first. Reads then the specified number of strings using the string input operator. Please note that the buffer has a fixed size - longer strings will cause an error.
Parameters
[in,out] os The BinaryInputDevice to read the string from
[in] v The string vector to store the read value into
Returns
The used BinaryInputDevice for further processing
Todo:
Use either a buffer with a flexible size or report an error if the buffer is too small!
Definition at line 159 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_LIST, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [8/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, std::vector< int > & v)
Reads the length of the vector as an int, first. Reads then the specified number of strings using the string input operator. Please note that the buffer has a fixed size - longer strings will cause an error.
Parameters
[in,out] os The BinaryInputDevice to read the string from
[in] v The string vector to store the read value into
Returns
The used BinaryInputDevice for further processing
Todo:
Use either a buffer with a flexible size or report an error if the buffer is too small!
Definition at line 174 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_LIST, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [9/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, std::vector< std::vector< int > > & v)
Reads the length of the vector as an int, first. Reads then the specified number of strings using the string input operator. Please note that the buffer has a fixed size - longer strings will cause an error.
Parameters
[in,out] os The BinaryInputDevice to read the string from
[in] v The string vector to store the read value into
Returns
The used BinaryInputDevice for further processing
Todo:
Use either a buffer with a flexible size or report an error if the buffer is too small!
Definition at line 189 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_LIST, BinaryInputDevice::checkType(), and BinaryInputDevice::myStream.
operator>>() [10/10]
BinaryInputDevice& operator>> (BinaryInputDevice & os, Position & p)
Parameters
[in,out] os The BinaryInputDevice to read the Position from
[in] p The Position to store the read value into
Returns
The used BinaryInputDevice for further processing
Definition at line 204 of file BinaryInputDevice.cpp.
References BinaryFormatter::BF_POSITION_2D, BinaryFormatter::BF_POSITION_3D, BinaryFormatter::BF_SCALED2INT_POSITION_2D, BinaryFormatter::BF_SCALED2INT_POSITION_3D, BinaryInputDevice::checkType(), BinaryInputDevice::myStream, and Position::set().