SUMO - Simulation of Urban MObility: NIVisumTL::TimePeriod Class Reference
NIVisumTL::TimePeriod Class Reference
A time period with a start and an end time.
#include <NIVisumTL.h>
Public Member Functions
SUMOTime getEndTime ()
Returns the stored end time.
SUMOTime getStartTime ()
Returns the stored start time.
SUMOTime getYellowTime ()
Returns the stored yellow time.
TimePeriod (SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
Constructor.
~TimePeriod ()
Destructor.
Private Attributes
SUMOTime myEndTime
End time.
SUMOTime myStartTime
Start time.
SUMOTime myYellowTime
Yellow time.
Detailed Description
A time period with a start and an end time.
Definition at line 55 of file NIVisumTL.h.
Constructor & Destructor Documentation
TimePeriod()
NIVisumTL::TimePeriod::TimePeriod (SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime) inline
Constructor.
Definition at line 58 of file NIVisumTL.h.
~TimePeriod()
NIVisumTL::TimePeriod::~TimePeriod () inline
Destructor.
Definition at line 62 of file NIVisumTL.h.
Member Function Documentation
getEndTime()
SUMOTime NIVisumTL::TimePeriod::getEndTime () inline
Returns the stored end time.
Definition at line 70 of file NIVisumTL.h.
References myEndTime.
Referenced by NIVisumTL::build().
getStartTime()
SUMOTime NIVisumTL::TimePeriod::getStartTime () inline
Returns the stored start time.
Definition at line 65 of file NIVisumTL.h.
References myStartTime.
Referenced by NIVisumTL::build().
getYellowTime()
SUMOTime NIVisumTL::TimePeriod::getYellowTime () inline
Returns the stored yellow time.
Definition at line 75 of file NIVisumTL.h.
References myYellowTime.
Referenced by NIVisumTL::build().
Field Documentation
myEndTime
SUMOTime NIVisumTL::TimePeriod::myEndTime private
End time.
Definition at line 83 of file NIVisumTL.h.
Referenced by getEndTime().
myStartTime
SUMOTime NIVisumTL::TimePeriod::myStartTime private
Start time.
Definition at line 81 of file NIVisumTL.h.
Referenced by getStartTime().
myYellowTime
SUMOTime NIVisumTL::TimePeriod::myYellowTime private
Yellow time.
Definition at line 85 of file NIVisumTL.h.
Referenced by getYellowTime().
The documentation for this class was generated from the following file:
NIVisumTL.h