SUMO - Simulation of Urban MObility: LaneStoringVisitor Class Reference
LaneStoringVisitor Class Reference
#include <Helper.h>
Public Member Functions
void add (const MSLane *const l) const
Adds the given object to the container.
LaneStoringVisitor (std::set< std::string > &ids, const PositionVector &shape, const double range, const int domain)
Constructor.
~LaneStoringVisitor ()
Destructor.
Data Fields
const int myDomain
std::set< std::string > & myIDs
The container.
const double myRange
const PositionVector & myShape
Private Member Functions
LaneStoringVisitor (const LaneStoringVisitor &src)
invalidated copy constructor
LaneStoringVisitor & operator= (const LaneStoringVisitor &src)
invalidated assignment operator
Detailed Description
Definition at line 51 of file Helper.h.
Constructor & Destructor Documentation
LaneStoringVisitor() [1/2]
LaneStoringVisitor::LaneStoringVisitor (std::set< std::string > & ids, const PositionVector & shape, const double range, const int domain) inline
Constructor.
Definition at line 54 of file Helper.h.
~LaneStoringVisitor()
LaneStoringVisitor::~LaneStoringVisitor () inline
Destructor.
Definition at line 59 of file Helper.h.
References add().
LaneStoringVisitor() [2/2]
LaneStoringVisitor::LaneStoringVisitor (const LaneStoringVisitor & src) private
invalidated copy constructor
Member Function Documentation
add()
void LaneStoringVisitor::add (const MSLane *const l) const
Adds the given object to the container.
Definition at line 56 of file Helper.cpp.
References CMD_GET_EDGE_VARIABLE, CMD_GET_LANE_VARIABLE, CMD_GET_PERSON_VARIABLE, CMD_GET_VEHICLE_VARIABLE, PositionVector::distance2D(), MSLane::getEdge(), Named::getID(), MSNet::getInstance(), MSLane::getShape(), MSEdge::getSortedPersons(), MSLane::getVehiclesSecure(), LANE_RTREE_QUAL, myDomain, myIDs, myRange, myShape, and MSLane::releaseVehicles().
Referenced by MSLane::visit(), and ~LaneStoringVisitor().
operator=()
LaneStoringVisitor& LaneStoringVisitor::operator= (const LaneStoringVisitor & src) private
invalidated assignment operator
Field Documentation
myDomain
const int LaneStoringVisitor::myDomain
Definition at line 68 of file Helper.h.
Referenced by add().
myIDs
std::set<std::string>& LaneStoringVisitor::myIDs
The container.
Definition at line 65 of file Helper.h.
Referenced by add().
myRange
const double LaneStoringVisitor::myRange
Definition at line 67 of file Helper.h.
Referenced by add().
myShape
const PositionVector& LaneStoringVisitor::myShape
Definition at line 66 of file Helper.h.
Referenced by add().
The documentation for this class was generated from the following files:
Helper.h
Helper.cpp