SUMO - Simulation of Urban MObility: ROPerson::PersonTrip Class Reference
ROPerson::PersonTrip Class Reference
A planItem can be a Trip which contains multiple tripItems.
#include <ROPerson.h>
Public Member Functions
virtual void addTripItem (TripItem *tripIt)
void addVehicle (ROVehicle *veh)
double getArrivalPos (bool replaceDefault=true) const
double getDepartPos (bool replaceDefault=true) const
const ROEdge * getDestination () const
SVCPermissions getModes () const
const ROEdge * getOrigin () const
std::vector< ROVehicle * > & getVehicles ()
double getWalkFactor () const
bool hasBusStopDest () const
virtual bool isStop () const
virtual bool needsRouting () const
PersonTrip ()
PersonTrip (const ROEdge *const from, const ROEdge *const to, const SVCPermissions modeSet, const double departPos, const double arrivalPos, const std::string &busStop, double _walkFactor)
void saveAsXML (OutputDevice &os, const bool extended) const
void saveVehicles (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const
virtual ~PersonTrip ()
Destructor.
Private Member Functions
PersonTrip & operator= (const PersonTrip &src)
Invalidated assignment operator.
Private Attributes
const double arr
const std::string busStop
const double dep
const ROEdge * from
const SVCPermissions modes
std::vector< TripItem * > myTripItems
the fully specified trips
std::vector< ROVehicle * > myVehicles
the vehicles which may be used for routing
const ROEdge * to
double walkFactor
walking speed factor
Detailed Description
A planItem can be a Trip which contains multiple tripItems.
Definition at line 223 of file ROPerson.h.
Constructor & Destructor Documentation
PersonTrip() [1/2]
ROPerson::PersonTrip::PersonTrip () inline
Definition at line 225 of file ROPerson.h.
PersonTrip() [2/2]
ROPerson::PersonTrip::PersonTrip (const ROEdge *const from, const ROEdge *const to, const SVCPermissions modeSet, const double departPos, const double arrivalPos, const std::string & busStop, double _walkFactor) inline
Definition at line 227 of file ROPerson.h.
~PersonTrip()
virtual ROPerson::PersonTrip::~PersonTrip () inline virtual
Destructor.
Definition at line 231 of file ROPerson.h.
Member Function Documentation
addTripItem()
virtual void ROPerson::PersonTrip::addTripItem (TripItem * tripIt) inline virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 241 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
addVehicle()
void ROPerson::PersonTrip::addVehicle (ROVehicle * veh) inline
Definition at line 244 of file ROPerson.h.
Referenced by ROPerson::addTrip().
getArrivalPos()
double ROPerson::PersonTrip::getArrivalPos (bool replaceDefault = true) const inline
Definition at line 259 of file ROPerson.h.
References POSITION_EPS.
Referenced by ROPerson::computeIntermodal().
getDepartPos()
double ROPerson::PersonTrip::getDepartPos (bool replaceDefault = true) const inline
Definition at line 256 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
getDestination()
const ROEdge* ROPerson::PersonTrip::getDestination () const inline virtual
Implements ROPerson::PlanItem.
Definition at line 253 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
getModes()
SVCPermissions ROPerson::PersonTrip::getModes () const inline
Definition at line 262 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
getOrigin()
const ROEdge* ROPerson::PersonTrip::getOrigin () const inline virtual
Implements ROPerson::PlanItem.
Definition at line 250 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
getVehicles()
std::vector<ROVehicle*>& ROPerson::PersonTrip::getVehicles () inline
Definition at line 247 of file ROPerson.h.
Referenced by ROPerson::addTrip(), and ROPerson::computeRoute().
getWalkFactor()
double ROPerson::PersonTrip::getWalkFactor () const inline
Definition at line 277 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
hasBusStopDest()
bool ROPerson::PersonTrip::hasBusStopDest () const inline
Definition at line 265 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
isStop()
virtual bool ROPerson::PlanItem::isStop () const inline virtual inherited
Reimplemented in ROPerson::Stop.
Definition at line 98 of file ROPerson.h.
needsRouting()
virtual bool ROPerson::PersonTrip::needsRouting () const inline virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 268 of file ROPerson.h.
References ROPerson::PlanItem::saveVehicles().
operator=()
PersonTrip& ROPerson::PersonTrip::operator= (const PersonTrip & src) private
Invalidated assignment operator.
saveAsXML()
void ROPerson::PersonTrip::saveAsXML (OutputDevice & os, const bool extended) const inline virtual
Implements ROPerson::PlanItem.
Definition at line 272 of file ROPerson.h.
saveVehicles()
void ROPerson::PersonTrip::saveVehicles (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 163 of file ROPerson.cpp.
Field Documentation
arr
const double ROPerson::PersonTrip::arr private
Definition at line 285 of file ROPerson.h.
busStop
const std::string ROPerson::PersonTrip::busStop private
Definition at line 286 of file ROPerson.h.
dep
const double ROPerson::PersonTrip::dep private
Definition at line 285 of file ROPerson.h.
from
const ROEdge* ROPerson::PersonTrip::from private
Definition at line 282 of file ROPerson.h.
modes
const SVCPermissions ROPerson::PersonTrip::modes private
Definition at line 284 of file ROPerson.h.
myTripItems
std::vector<TripItem*> ROPerson::PersonTrip::myTripItems private
the fully specified trips
Definition at line 288 of file ROPerson.h.
myVehicles
std::vector<ROVehicle*> ROPerson::PersonTrip::myVehicles private
the vehicles which may be used for routing
Definition at line 290 of file ROPerson.h.
to
const ROEdge* ROPerson::PersonTrip::to private
Definition at line 283 of file ROPerson.h.
walkFactor
double ROPerson::PersonTrip::walkFactor private
walking speed factor
Definition at line 292 of file ROPerson.h.
The documentation for this class was generated from the following files:
ROPerson.h
ROPerson.cpp