SUMO - Simulation of Urban MObility: libsumo::Person Class Reference
libsumo::Person Class Reference
#include <Person.h>
Static Public Member Functions
static void add (const std::string &personID, const std::string &edgeID, double pos, double depart=DEPARTFLAG_NOW, const std::string typeID="DEFAULT_PEDTYPE")
static void appendDrivingStage (const std::string &personID, const std::string &toEdge, const std::string &lines, const std::string &stopID="")
static void appendWaitingStage (const std::string &personID, double duration, const std::string &description="waiting", const std::string &stopID="")
static void appendWalkingStage (const std::string &personID, const std::vector< std::string > &edgeIDs, double arrivalPos, double duration=-1, double speed=-1, const std::string &stopID="")
static double getAngle (const std::string &personID)
static TraCIColor getColor (const std::string &personID)
static std::vector< std::string > getEdges (const std::string &personID, int nextStageIndex=0)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static double getLanePosition (const std::string &personID)
static std::string getNextEdge (const std::string &personID)
static std::string getParameter (const std::string &routeID, const std::string &param)
static TraCIPosition getPosition (const std::string &personID)
static int getRemainingStages (const std::string &personID)
static std::string getRoadID (const std::string &personID)
static double getSpeed (const std::string &personID)
static int getStage (const std::string &personID, int nextStageIndex=0)
static std::string getTypeID (const std::string &personID)
static std::string getVehicle (const std::string &personID)
static double getWaitingTime (const std::string &personID)
static void moveTo (const std::string &personID, const std::string &edgeID, double position)
static void moveToXY (const std::string &personID, const std::string &edgeID, const double x, const double y, double angle, const int keepRouteFlag)
static void removeStage (const std::string &personID, int nextStageIndex)
static void removeStages (const std::string &personID)
static void rerouteTraveltime (const std::string &personID)
static void setColor (const std::string &personID, const TraCIColor &c)
static void setHeight (const std::string &personID, double height)
static void setLength (const std::string &personID, double length)
static void setMinGap (const std::string &personID, double minGap)
static void setParameter (const std::string &personID, const std::string &key, const std::string &value)
static void setSpeed (const std::string &personID, double speed)
static void setType (const std::string &personID, const std::string &typeID)
static void setWidth (const std::string &personID, double width)
Private Member Functions
Person & operator= (const Person &src)
invalidated assignment operator
Person ()
invalidated standard constructor
Person (const Person &src)
invalidated copy constructor
Static Private Member Functions
static MSPerson * getPerson (const std::string &id)
static std::string getSingularVType (const std::string &personID)
Friends
bool TraCIServerAPI_Person::processSet (TraCIServer &, tcpip::Storage &, tcpip::Storage &)
Detailed Description
Definition at line 50 of file Person.h.
Constructor & Destructor Documentation
Person() [1/2]
libsumo::Person::Person () private
invalidated standard constructor
Person() [2/2]
libsumo::Person::Person (const Person & src) private
invalidated copy constructor
Member Function Documentation
add()
void libsumo::Person::add (const std::string & personID, const std::string & edgeID, double pos, double depart = DEPARTFLAG_NOW, const std::string typeID = "DEFAULT_PEDTYPE") static
Definition at line 205 of file Person.cpp.
References MSTransportableControl::add(), MSTransportableControl::buildPerson(), SUMOVehicleParameter::depart, DEPART_DEF_MAX, DEPART_POS_GIVEN, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departProcedure, MSEdge::dictionary(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSEdge::getLength(), getPerson(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, TIME2STEPS, time2string(), toString(), and WRITE_WARNING.
Referenced by TraCIServerAPI_Person::processSet().
appendDrivingStage()
void libsumo::Person::appendDrivingStage (const std::string & personID, const std::string & toEdge, const std::string & lines, const std::string & stopID = "") static
Definition at line 271 of file Person.cpp.
References MSTransportable::appendStage(), MSEdge::dictionary(), MSNet::getInstance(), getPerson(), MSNet::getStoppingPlace(), NUMERICAL_EPS, and SUMO_TAG_BUS_STOP.
Referenced by TraCIServerAPI_Person::processSet().
appendWaitingStage()
void libsumo::Person::appendWaitingStage (const std::string & personID, double duration, const std::string & description = "waiting", const std::string & stopID = "") static
Definition at line 292 of file Person.cpp.
References MSTransportable::appendStage(), MSTransportable::getArrivalEdge(), MSTransportable::getArrivalPos(), MSNet::getInstance(), getPerson(), MSNet::getStoppingPlace(), SUMO_TAG_BUS_STOP, and TIME2STEPS.
Referenced by TraCIServerAPI_Person::processSet().
appendWalkingStage()
void libsumo::Person::appendWalkingStage (const std::string & personID, const std::vector< std::string > & edgeIDs, double arrivalPos, double duration = -1, double speed = -1, const std::string & stopID = "") static
Definition at line 309 of file Person.cpp.
References MSTransportable::appendStage(), MSTransportable::getArrivalPos(), MSTransportable::getID(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), getPerson(), MSNet::getStoppingPlace(), MSTransportable::getVehicleType(), MSEdge::parseEdgesList(), SUMO_TAG_BUS_STOP, and TIME2STEPS.
Referenced by TraCIServerAPI_Person::processSet().
getAngle()
double libsumo::Person::getAngle (const std::string & personID) static
Definition at line 80 of file Person.cpp.
References getPerson(), and GeomHelper::naviDegree().
Referenced by TraCIServerAPI_Person::processGet().
getColor()
TraCIColor libsumo::Person::getColor (const std::string & personID) static
Definition at line 104 of file Person.cpp.
References libsumo::TraCIColor::a, RGBColor::alpha(), libsumo::TraCIColor::b, RGBColor::blue(), SUMOVehicleParameter::color, libsumo::TraCIColor::g, MSTransportable::getParameter(), getPerson(), RGBColor::green(), libsumo::TraCIColor::r, and RGBColor::red().
Referenced by TraCIServerAPI_Person::processGet().
getEdges()
std::vector< std::string > libsumo::Person::getEdges (const std::string & personID, int nextStageIndex = 0) static
Definition at line 134 of file Person.cpp.
References MSTransportable::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), and getPerson().
Referenced by TraCIServerAPI_Person::processGet().
getIDCount()
int libsumo::Person::getIDCount () static
Definition at line 63 of file Person.cpp.
References MSNet::getInstance(), MSNet::getPersonControl(), and MSTransportableControl::size().
Referenced by TraCIServerAPI_Person::processGet().
getIDList()
std::vector< std::string > libsumo::Person::getIDList () static
Definition at line 50 of file Person.cpp.
References MSNet::getInstance(), MSNet::getPersonControl(), MSTransportableControl::loadedBegin(), MSTransportableControl::loadedEnd(), and MSTransportable::WAITING_FOR_DEPART.
Referenced by TraCIServerAPI_Person::processGet().
getLanePosition()
double libsumo::Person::getLanePosition (const std::string & personID) static
Definition at line 98 of file Person.cpp.
References MSTransportable::getEdgePos(), and getPerson().
Referenced by TraCIServerAPI_Person::processGet().
getNextEdge()
std::string libsumo::Person::getNextEdge (const std::string & personID) static
Definition at line 128 of file Person.cpp.
References MSPerson::getNextEdge(), and getPerson().
Referenced by TraCIServerAPI_Person::processGet().
getParameter()
std::string libsumo::Person::getParameter (const std::string & routeID, const std::string & param) static
Definition at line 181 of file Person.cpp.
References Parameterised::getParameter(), MSTransportable::getParameter(), and getPerson().
Referenced by TraCIServerAPI_Person::processGet().
getPerson()
MSPerson * libsumo::Person::getPerson (const std::string & id) static private
Definition at line 564 of file Person.cpp.
References MSTransportableControl::get(), MSNet::getInstance(), and MSNet::getPersonControl().
Referenced by add(), appendDrivingStage(), appendWaitingStage(), appendWalkingStage(), getAngle(), getColor(), getEdges(), getLanePosition(), getNextEdge(), getParameter(), getPosition(), getRemainingStages(), getRoadID(), getSingularVType(), getSpeed(), getStage(), getTypeID(), getVehicle(), getWaitingTime(), moveTo(), moveToXY(), removeStage(), rerouteTraveltime(), setParameter(), setSpeed(), and setType().
getPosition()
TraCIPosition libsumo::Person::getPosition (const std::string & personID) static
Definition at line 69 of file Person.cpp.
References getPerson(), MSTransportable::getPosition(), Position::x(), libsumo::TraCIPosition::x, Position::y(), libsumo::TraCIPosition::y, Position::z(), and libsumo::TraCIPosition::z.
Referenced by TraCIServerAPI_Person::processGet().
getRemainingStages()
int libsumo::Person::getRemainingStages (const std::string & personID) static
Definition at line 164 of file Person.cpp.
References MSTransportable::getNumRemainingStages(), and getPerson().
Referenced by TraCIServerAPI_Person::processGet().
getRoadID()
std::string libsumo::Person::getRoadID (const std::string & personID) static
Definition at line 92 of file Person.cpp.
References MSTransportable::getEdge(), Named::getID(), and getPerson().
Referenced by TraCIServerAPI_Person::processGet().
getSingularVType()
std::string libsumo::Person::getSingularVType (const std::string & personID) static private
Definition at line 574 of file Person.cpp.
References MSVehicleType::getID(), getPerson(), and MSTransportable::getSingularType().
Referenced by TraCIServerAPI_Person::processSet(), setColor(), setHeight(), setLength(), setMinGap(), and setWidth().
getSpeed()
double libsumo::Person::getSpeed (const std::string & personID) static
Definition at line 86 of file Person.cpp.
References getPerson(), and MSTransportable::getSpeed().
Referenced by TraCIServerAPI_Person::processGet().
getStage()
int libsumo::Person::getStage (const std::string & personID, int nextStageIndex = 0) static
Definition at line 151 of file Person.cpp.
References MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), getPerson(), and MSTransportable::getStageType().
Referenced by TraCIServerAPI_Person::processGet().
getTypeID()
std::string libsumo::Person::getTypeID (const std::string & personID) static
Definition at line 116 of file Person.cpp.
References MSVehicleType::getID(), getPerson(), and MSTransportable::getVehicleType().
Referenced by TraCIServerAPI_Person::processGet().
getVehicle()
std::string libsumo::Person::getVehicle (const std::string & personID) static
Definition at line 170 of file Person.cpp.
References SUMOVehicle::getID(), getPerson(), and MSTransportable::getVehicle().
Referenced by TraCIServerAPI_Person::processGet().
getWaitingTime()
double libsumo::Person::getWaitingTime (const std::string & personID) static
Definition at line 122 of file Person.cpp.
References getPerson(), and MSTransportable::getWaitingSeconds().
Referenced by TraCIServerAPI_Person::processGet().
moveTo()
void libsumo::Person::moveTo (const std::string & personID, const std::string & edgeID, double position) static
Definition at line 386 of file Person.cpp.
References MSEdge::dictionary(), MSTransportable::getCurrentStageDescription(), and getPerson().
moveToXY()
void libsumo::Person::moveToXY (const std::string & personID, const std::string & edgeID, const double x, const double y, double angle, const int keepRouteFlag) static
Definition at line 411 of file Person.cpp.
References Position::angleTo2D(), PositionVector::distance2D(), Position::distanceTo2D(), MSLane::geometryPositionAtOffset(), MSTransportable::getCurrentStage(), MSTransportable::getCurrentStageDescription(), MSTransportable::getEdge(), MSTransportable::getEdgePos(), MSPerson::MSPersonStage_Walking::getEdges(), Named::getID(), MSTransportable::getID(), Named::getIDSecure(), MSNet::getInstance(), getPerson(), MSTransportable::getPosition(), MSPerson::MSPersonStage_Walking::getRoute(), MSPerson::MSPersonStage_Walking::getRouteStep(), MSLane::getShape(), MSTransportable::getStageType(), MSTransportable::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSGlobals::gLateralResolution, INVALID_DOUBLE_VALUE, GeomHelper::INVALID_OFFSET, MIN2(), PositionVector::move2side(), libsumo::Helper::moveToXYMap(), libsumo::Helper::moveToXYMap_matchingRoutePosition(), MSTransportable::MOVING_WITHOUT_VEHICLE, GeomHelper::naviDegree(), PositionVector::rotationAtOffset(), libsumo::Helper::setRemoteControlled(), toString(), and WRITE_WARNING.
Referenced by TraCIServerAPI_Person::processSet().
operator=()
Person& libsumo::Person::operator= (const Person & src) private
invalidated assignment operator
removeStage()
void libsumo::Person::removeStage (const std::string & personID, int nextStageIndex) static
Definition at line 341 of file Person.cpp.
References MSTransportable::getNumRemainingStages(), getPerson(), and MSTransportable::removeStage().
Referenced by TraCIServerAPI_Person::processSet().
removeStages()
static void libsumo::Person::removeStages (const std::string & personID) static
rerouteTraveltime()
void libsumo::Person::rerouteTraveltime (const std::string & personID) static
Definition at line 354 of file Person.cpp.
References PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), EDGEFUNC_NORMAL, MSTransportable::getArrivalEdge(), MSTransportable::getArrivalPos(), MSTransportable::getCurrentStageType(), MSTransportable::getEdge(), MSTransportable::getEdgePos(), MSTransportable::getEdges(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), MSTransportable::getNumRemainingStages(), MSNet::getPedestrianRouter(), getPerson(), MSTransportable::getVehicleType(), MSTransportable::MOVING_WITHOUT_VEHICLE, and MSPerson::reroute().
Referenced by TraCIServerAPI_Person::processSet().
setColor()
void libsumo::Person::setColor (const std::string & personID, const TraCIColor & c) static
Definition at line 555 of file Person.cpp.
References libsumo::TraCIColor::a, libsumo::TraCIColor::b, libsumo::TraCIColor::g, getSingularVType(), libsumo::VehicleType::getVType(), libsumo::TraCIColor::r, and MSVehicleType::setColor().
setHeight()
void libsumo::Person::setHeight (const std::string & personID, double height) static
Definition at line 545 of file Person.cpp.
References getSingularVType(), libsumo::VehicleType::getVType(), and MSVehicleType::setHeight().
setLength()
void libsumo::Person::setLength (const std::string & personID, double length) static
Definition at line 535 of file Person.cpp.
References getSingularVType(), libsumo::VehicleType::getVType(), and MSVehicleType::setLength().
setMinGap()
void libsumo::Person::setMinGap (const std::string & personID, double minGap) static
Definition at line 550 of file Person.cpp.
References getSingularVType(), libsumo::VehicleType::getVType(), and MSVehicleType::setMinGap().
setParameter()
void libsumo::Person::setParameter (const std::string & personID, const std::string & key, const std::string & value) static
untested setter functions which alter the person's vtype
Definition at line 529 of file Person.cpp.
References MSTransportable::getParameter(), and getPerson().
Referenced by TraCIServerAPI_Person::processSet().
setSpeed()
void libsumo::Person::setSpeed (const std::string & personID, double speed) static
Definition at line 189 of file Person.cpp.
References getPerson(), and MSTransportable::setSpeed().
Referenced by TraCIServerAPI_Person::processSet().
setType()
void libsumo::Person::setType (const std::string & personID, const std::string & typeID) static
Definition at line 195 of file Person.cpp.
References MSNet::getInstance(), getPerson(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), and MSTransportable::replaceVehicleType().
Referenced by TraCIServerAPI_Person::processSet().
setWidth()
void libsumo::Person::setWidth (const std::string & personID, double width) static
Definition at line 540 of file Person.cpp.
References getSingularVType(), libsumo::VehicleType::getVType(), and MSVehicleType::setWidth().
Friends And Related Function Documentation
TraCIServerAPI_Person::processSet
bool TraCIServerAPI_Person::processSet (TraCIServer & , tcpip::Storage & , tcpip::Storage &) friend
The documentation for this class was generated from the following files:
Person.h
Person.cpp