SUMO - Simulation of Urban MObility: NBPTPlatform Class Reference
NBPTPlatform Class Reference
#include <NBPTPlatform.h>
Public Member Functions
double getMyLength () const
Position * getMyPos ()
NBPTPlatform (Position position, double d)
Private Attributes
double myLength
Position myPos
Detailed Description
Definition at line 25 of file NBPTPlatform.h.
Constructor & Destructor Documentation
NBPTPlatform()
NBPTPlatform::NBPTPlatform (Position position, double d)
Definition at line 20 of file NBPTPlatform.cpp.
Member Function Documentation
getMyLength()
double NBPTPlatform::getMyLength () const
Definition at line 26 of file NBPTPlatform.cpp.
References myLength.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), and NBPTStopCont::assignPTStopToEdgeOfClosestPlatform().
getMyPos()
Position * NBPTPlatform::getMyPos ()
Definition at line 23 of file NBPTPlatform.cpp.
References myPos.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), and NBPTStopCont::getClosestPlatformToPTStopPosition().
Field Documentation
myLength
double NBPTPlatform::myLength private
Definition at line 35 of file NBPTPlatform.h.
Referenced by getMyLength().
myPos
Position NBPTPlatform::myPos private
Definition at line 30 of file NBPTPlatform.h.
Referenced by getMyPos().
The documentation for this class was generated from the following files:
NBPTPlatform.h
NBPTPlatform.cpp