SUMO - Simulation of Urban MObility: GUIDanielPerspectiveChanger Class Reference
GUIDanielPerspectiveChanger Class Reference
#include <GUIDanielPerspectiveChanger.h>
Public Types
enum MouseState { MOUSEBTN_NONE = 0, MOUSEBTN_LEFT = 1, MOUSEBTN_RIGHT = 2, MOUSEBTN_MIDDLE = 4 }
mouse states
Public Member Functions
void centerTo (const Position &pos, double radius, bool applyZoom=true)
Centers the view to the given position, setting it to a size that covers the radius.
void changeCanvasSizeLeft (int change)
FXint getMouseXPosition () const
Returns the last mouse x-position an event occured at.
FXint getMouseYPosition () const
Returns the last mouse y-position an event occured at.
virtual double getRotation () const
Returns the rotation of the canvas stored in this changer.
Boundary getViewport (bool fixRatio=true)
get viewport
virtual double getXPos () const
Returns the x-offset of the field to show stored in this changer.
virtual double getYPos () const
Returns the y-offset of the field to show stored in this changer.
virtual double getZoom () const
Returns the zoom factor computed stored in this changer.
virtual double getZPos () const
Returns the camera height corresponding to the current zoom factor.
GUIDanielPerspectiveChanger (GUISUMOAbstractView &callBack, const Boundary &viewPort)
long onKeyPress (void *data)
called when user press a key
void onLeftBtnPress (void *data)
mouse functions
bool onLeftBtnRelease (void *data)
called when user releases left button
void onMouseMove (void *data)
called when user moves mouse
void onMouseWheel (void *data)
called when user changes mouse wheel
void onRightBtnPress (void *data)
called when user press right button
bool onRightBtnRelease (void *data)
called when user releases right button
void setDragDelay (FXTime delay)
void setViewport (double zoom, double xPos, double yPos)
Sets the viewport.
void setViewport (const Boundary &viewPort)
set viewport
void setViewportFrom (double xPos, double yPos, double zPos)
Alternative method for setting the viewport.
virtual double zoom2ZPos (double zoom) const
Returns the camera height at which the given zoom level is reached.
virtual double zPos2Zoom (double zPos) const
Returns the zoom level that is achieved at a given camera height.
~GUIDanielPerspectiveChanger ()
Destructor.
virtual void onDoubleClicked (void *data)
called when user click two times
virtual long onKeyRelease (void *data)
called when user releases a key
Protected Attributes
GUISUMOAbstractView & myCallback
The parent window (canvas to scale)
FXint myMouseXPosition
the current mouse position
FXint myMouseYPosition
Boundary myViewPort
the intended viewport
Private Member Functions
GUIDanielPerspectiveChanger (const GUIDanielPerspectiveChanger &)
Invalidated copy constructor.
void move (int xdiff, int ydiff)
GUIDanielPerspectiveChanger & operator= (const GUIDanielPerspectiveChanger &)
Invalidated assignment operator.
void rotate (int diff)
Performs the rotation of the view.
void zoom (double factor)
Performs the zooming of the view.
Private Attributes
FXTime myDragDelay
avoid flicker
int myMouseButtonState
the current mouse state
FXlong myMouseDownTime
bool myMoveOnClick
Information whether the user has moved the cursor while pressing a mouse button.
double myOrigHeight
double myOrigWidth
the original viewport dimensions in m which serve as the reference point for 100% zoom
double myRotation
the current rotation
Position myZoomBase
the network location on which to zoom using right click+drag
Detailed Description
This changer has the following behaviour:
zooming by pressing the right mouse button and moving the mouse vertically
rotation by pressing the right mouse button and moving the mouse horizontally
network movement by pressing the left mouse button and moving the mouse
Definition at line 57 of file GUIDanielPerspectiveChanger.h.
Member Enumeration Documentation
MouseState
enum GUIPerspectiveChanger::MouseState inherited
mouse states
Enumerator
MOUSEBTN_NONE
MOUSEBTN_LEFT
MOUSEBTN_RIGHT
MOUSEBTN_MIDDLE
Definition at line 62 of file GUIPerspectiveChanger.h.
Constructor & Destructor Documentation
GUIDanielPerspectiveChanger() [1/2]
GUIDanielPerspectiveChanger::GUIDanielPerspectiveChanger (GUISUMOAbstractView & callBack, const Boundary & viewPort)
Definition at line 43 of file GUIDanielPerspectiveChanger.cpp.
~GUIDanielPerspectiveChanger()
GUIDanielPerspectiveChanger::~GUIDanielPerspectiveChanger ()
Destructor.
Definition at line 56 of file GUIDanielPerspectiveChanger.cpp.
GUIDanielPerspectiveChanger() [2/2]
GUIDanielPerspectiveChanger::GUIDanielPerspectiveChanger (const GUIDanielPerspectiveChanger &) private
Invalidated copy constructor.
Member Function Documentation
centerTo()
void GUIDanielPerspectiveChanger::centerTo (const Position & pos, double radius, bool applyZoom = true) virtual
Centers the view to the given position, setting it to a size that covers the radius.
Implements GUIPerspectiveChanger.
Definition at line 136 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::add(), getXPos(), getYPos(), Boundary::grow(), Boundary::moveby(), GUIPerspectiveChanger::myViewPort, Position::x(), and Position::y().
changeCanvasSizeLeft()
void GUIDanielPerspectiveChanger::changeCanvasSizeLeft (int change) virtual
Implements GUIPerspectiveChanger.
Definition at line 276 of file GUIDanielPerspectiveChanger.cpp.
References GUIPerspectiveChanger::myCallback, GUIPerspectiveChanger::myViewPort, GUISUMOAbstractView::p2m(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
getMouseXPosition()
FXint GUIPerspectiveChanger::getMouseXPosition () const inherited
Returns the last mouse x-position an event occured at.
Definition at line 98 of file GUIPerspectiveChanger.cpp.
References GUIPerspectiveChanger::myMouseXPosition.
getMouseYPosition()
FXint GUIPerspectiveChanger::getMouseYPosition () const inherited
Returns the last mouse y-position an event occured at.
Definition at line 104 of file GUIPerspectiveChanger.cpp.
References GUIPerspectiveChanger::myMouseYPosition.
getRotation()
double GUIDanielPerspectiveChanger::getRotation () const virtual
Returns the rotation of the canvas stored in this changer.
Implements GUIPerspectiveChanger.
Definition at line 94 of file GUIDanielPerspectiveChanger.cpp.
References myRotation.
getViewport()
Boundary GUIPerspectiveChanger::getViewport (bool fixRatio = true) inherited
get viewport
Definition at line 110 of file GUIPerspectiveChanger.cpp.
References GUIPerspectiveChanger::myViewPort, and GUIPerspectiveChanger::patchedViewPort().
Referenced by GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getVisibleBoundary(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::p2m(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::paintGLGrid(), and GUISUMOAbstractView::screenPos2NetPos().
getXPos()
double GUIDanielPerspectiveChanger::getXPos () const virtual
Returns the x-offset of the field to show stored in this changer.
Implements GUIPerspectiveChanger.
Definition at line 100 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::getCenter(), GUIPerspectiveChanger::myViewPort, and Position::x().
Referenced by centerTo().
getYPos()
double GUIDanielPerspectiveChanger::getYPos () const virtual
Returns the y-offset of the field to show stored in this changer.
Implements GUIPerspectiveChanger.
Definition at line 106 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::getCenter(), GUIPerspectiveChanger::myViewPort, and Position::y().
Referenced by centerTo().
getZoom()
double GUIDanielPerspectiveChanger::getZoom () const virtual
Returns the zoom factor computed stored in this changer.
Implements GUIPerspectiveChanger.
Definition at line 112 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::getWidth(), myOrigWidth, and GUIPerspectiveChanger::myViewPort.
getZPos()
double GUIDanielPerspectiveChanger::getZPos () const virtual
Returns the camera height corresponding to the current zoom factor.
Implements GUIPerspectiveChanger.
Definition at line 118 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::getWidth(), and GUIPerspectiveChanger::myViewPort.
move()
void GUIDanielPerspectiveChanger::move (int xdiff, int ydiff) private
Definition at line 60 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::moveby(), GUIPerspectiveChanger::myCallback, GUIPerspectiveChanger::myViewPort, and GUISUMOAbstractView::p2m().
Referenced by onMouseMove(), and setDragDelay().
onDoubleClicked()
void GUIPerspectiveChanger::onDoubleClicked (void * data) virtual inherited
called when user click two times
Definition at line 71 of file GUIPerspectiveChanger.cpp.
onKeyPress()
long GUIDanielPerspectiveChanger::onKeyPress (void * data) virtual
called when user press a key
Reimplemented from GUIPerspectiveChanger.
Definition at line 286 of file GUIDanielPerspectiveChanger.cpp.
References GUIVisualizationSettings::gaming, GUICompleteSchemeStorage::getDefault(), Boundary::getHeight(), GUISUMOAbstractView::getPositionInformation(), Boundary::getWidth(), gSchemeStorage, Boundary::moveby(), GUIPerspectiveChanger::myCallback, GUIPerspectiveChanger::myViewPort, myZoomBase, GUISUMOAbstractView::recenterView(), GUISUMOAbstractView::showViewschemeEditor(), GUISUMOAbstractView::updateToolTip(), and zoom().
onKeyRelease()
long GUIPerspectiveChanger::onKeyRelease (void * data) virtual inherited
called when user releases a key
Definition at line 92 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onKeyRelease().
onLeftBtnPress()
void GUIDanielPerspectiveChanger::onLeftBtnPress (void * data) virtual
mouse functions
called when user press left button
Reimplemented from GUIPerspectiveChanger.
Definition at line 149 of file GUIDanielPerspectiveChanger.cpp.
References GUIPerspectiveChanger::MOUSEBTN_LEFT, myMouseButtonState, myMouseDownTime, GUIPerspectiveChanger::myMouseXPosition, GUIPerspectiveChanger::myMouseYPosition, and myMoveOnClick.
onLeftBtnRelease()
bool GUIDanielPerspectiveChanger::onLeftBtnRelease (void * data) virtual
called when user releases left button
Reimplemented from GUIPerspectiveChanger.
Definition at line 160 of file GUIDanielPerspectiveChanger.cpp.
References GUIPerspectiveChanger::MOUSEBTN_LEFT, myMouseButtonState, GUIPerspectiveChanger::myMouseXPosition, GUIPerspectiveChanger::myMouseYPosition, and myMoveOnClick.
onMouseMove()
void GUIDanielPerspectiveChanger::onMouseMove (void * data) virtual
called when user moves mouse
Reimplemented from GUIPerspectiveChanger.
Definition at line 221 of file GUIDanielPerspectiveChanger.cpp.
References GUIVisualizationSettings::gaming, GUICompleteSchemeStorage::getDefault(), gSchemeStorage, GUIPerspectiveChanger::MOUSEBTN_LEFT, GUIPerspectiveChanger::MOUSEBTN_RIGHT, move(), GUIPerspectiveChanger::myCallback, myDragDelay, myMouseButtonState, myMouseDownTime, GUIPerspectiveChanger::myMouseXPosition, GUIPerspectiveChanger::myMouseYPosition, myMoveOnClick, rotate(), GUISUMOAbstractView::setWindowCursorPosition(), GUISUMOAbstractView::updateToolTip(), and zoom().
onMouseWheel()
void GUIDanielPerspectiveChanger::onMouseWheel (void * data) virtual
called when user changes mouse wheel
Reimplemented from GUIPerspectiveChanger.
Definition at line 194 of file GUIDanielPerspectiveChanger.cpp.
References GUISUMOAbstractView::getPositionInformation(), GUIPerspectiveChanger::myCallback, myZoomBase, GUISUMOAbstractView::updateToolTip(), and zoom().
onRightBtnPress()
void GUIDanielPerspectiveChanger::onRightBtnPress (void * data) virtual
called when user press right button
Reimplemented from GUIPerspectiveChanger.
Definition at line 170 of file GUIDanielPerspectiveChanger.cpp.
References GUISUMOAbstractView::getPositionInformation(), GUIPerspectiveChanger::MOUSEBTN_RIGHT, GUIPerspectiveChanger::myCallback, myMouseButtonState, myMouseDownTime, GUIPerspectiveChanger::myMouseXPosition, GUIPerspectiveChanger::myMouseYPosition, myMoveOnClick, and myZoomBase.
onRightBtnRelease()
bool GUIDanielPerspectiveChanger::onRightBtnRelease (void * data) virtual
called when user releases right button
Reimplemented from GUIPerspectiveChanger.
Definition at line 182 of file GUIDanielPerspectiveChanger.cpp.
References GUIPerspectiveChanger::MOUSEBTN_RIGHT, myMouseButtonState, GUIPerspectiveChanger::myMouseXPosition, GUIPerspectiveChanger::myMouseYPosition, and myMoveOnClick.
operator=()
GUIDanielPerspectiveChanger& GUIDanielPerspectiveChanger::operator= (const GUIDanielPerspectiveChanger &) private
Invalidated assignment operator.
rotate()
void GUIDanielPerspectiveChanger::rotate (int diff) private
Performs the rotation of the view.
Definition at line 83 of file GUIDanielPerspectiveChanger.cpp.
Referenced by onMouseMove(), and setDragDelay().
setDragDelay()
void GUIDanielPerspectiveChanger::setDragDelay (FXTime delay) inline
Definition at line 117 of file GUIDanielPerspectiveChanger.h.
References move(), myDragDelay, rotate(), and zoom().
setViewport() [1/2]
void GUIDanielPerspectiveChanger::setViewport (double zoom, double xPos, double yPos) virtual
Sets the viewport.
Implements GUIPerspectiveChanger.
Definition at line 258 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::add(), Boundary::growHeight(), Boundary::growWidth(), GUIPerspectiveChanger::myCallback, myOrigHeight, myOrigWidth, and GUIPerspectiveChanger::myViewPort.
Referenced by setViewportFrom().
setViewport() [2/2]
void GUIPerspectiveChanger::setViewport (const Boundary & viewPort) inherited
set viewport
Definition at line 120 of file GUIPerspectiveChanger.cpp.
References GUIPerspectiveChanger::myViewPort.
setViewportFrom()
void GUIDanielPerspectiveChanger::setViewportFrom (double xPos, double yPos, double zPos) virtual
Alternative method for setting the viewport.
Implements GUIPerspectiveChanger.
Definition at line 270 of file GUIDanielPerspectiveChanger.cpp.
References setViewport(), and zPos2Zoom().
zoom()
void GUIDanielPerspectiveChanger::zoom (double factor) private
Performs the zooming of the view.
Definition at line 67 of file GUIDanielPerspectiveChanger.cpp.
References Boundary::getCenter(), GUIPerspectiveChanger::myCallback, GUIPerspectiveChanger::myViewPort, myZoomBase, Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by onKeyPress(), onMouseMove(), onMouseWheel(), and setDragDelay().
zoom2ZPos()
double GUIDanielPerspectiveChanger::zoom2ZPos (double zoom) const virtual
Returns the camera height at which the given zoom level is reached.
Implements GUIPerspectiveChanger.
Definition at line 124 of file GUIDanielPerspectiveChanger.cpp.
References myOrigWidth.
zPos2Zoom()
double GUIDanielPerspectiveChanger::zPos2Zoom (double zPos) const virtual
Returns the zoom level that is achieved at a given camera height.
Implements GUIPerspectiveChanger.
Definition at line 130 of file GUIDanielPerspectiveChanger.cpp.
References myOrigWidth.
Referenced by setViewportFrom().
Field Documentation
myCallback
GUISUMOAbstractView& GUIPerspectiveChanger::myCallback protected inherited
The parent window (canvas to scale)
Definition at line 157 of file GUIPerspectiveChanger.h.
Referenced by changeCanvasSizeLeft(), move(), onKeyPress(), onMouseMove(), onMouseWheel(), onRightBtnPress(), GUIPerspectiveChanger::patchedViewPort(), setViewport(), and zoom().
myDragDelay
FXTime GUIDanielPerspectiveChanger::myDragDelay private
avoid flicker
Definition at line 151 of file GUIDanielPerspectiveChanger.h.
Referenced by onMouseMove(), and setDragDelay().
myMouseButtonState
int GUIDanielPerspectiveChanger::myMouseButtonState private
the current mouse state
Definition at line 142 of file GUIDanielPerspectiveChanger.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onRightBtnPress(), and onRightBtnRelease().
myMouseDownTime
FXlong GUIDanielPerspectiveChanger::myMouseDownTime private
Definition at line 152 of file GUIDanielPerspectiveChanger.h.
Referenced by onLeftBtnPress(), onMouseMove(), and onRightBtnPress().
myMouseXPosition
FXint GUIPerspectiveChanger::myMouseXPosition protected inherited
the current mouse position
Definition at line 160 of file GUIPerspectiveChanger.h.
Referenced by GUIPerspectiveChanger::getMouseXPosition(), onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onRightBtnPress(), and onRightBtnRelease().
myMouseYPosition
FXint GUIPerspectiveChanger::myMouseYPosition protected inherited
Definition at line 160 of file GUIPerspectiveChanger.h.
Referenced by GUIPerspectiveChanger::getMouseYPosition(), onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onRightBtnPress(), and onRightBtnRelease().
myMoveOnClick
bool GUIDanielPerspectiveChanger::myMoveOnClick private
Information whether the user has moved the cursor while pressing a mouse button.
Definition at line 145 of file GUIDanielPerspectiveChanger.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onRightBtnPress(), and onRightBtnRelease().
myOrigHeight
double GUIDanielPerspectiveChanger::myOrigHeight private
Definition at line 136 of file GUIDanielPerspectiveChanger.h.
Referenced by setViewport().
myOrigWidth
double GUIDanielPerspectiveChanger::myOrigWidth private
the original viewport dimensions in m which serve as the reference point for 100% zoom
Definition at line 136 of file GUIDanielPerspectiveChanger.h.
Referenced by getZoom(), setViewport(), zoom2ZPos(), and zPos2Zoom().
myRotation
double GUIDanielPerspectiveChanger::myRotation private
the current rotation
Definition at line 139 of file GUIDanielPerspectiveChanger.h.
Referenced by getRotation().
myViewPort
Boundary GUIPerspectiveChanger::myViewPort protected inherited
the intended viewport
Definition at line 163 of file GUIPerspectiveChanger.h.
Referenced by centerTo(), changeCanvasSizeLeft(), GUIPerspectiveChanger::getViewport(), getXPos(), getYPos(), getZoom(), getZPos(), move(), onKeyPress(), GUIPerspectiveChanger::patchedViewPort(), setViewport(), GUIPerspectiveChanger::setViewport(), and zoom().
myZoomBase
Position GUIDanielPerspectiveChanger::myZoomBase private
the network location on which to zoom using right click+drag
Definition at line 148 of file GUIDanielPerspectiveChanger.h.
Referenced by onKeyPress(), onMouseWheel(), onRightBtnPress(), and zoom().
The documentation for this class was generated from the following files:
GUIDanielPerspectiveChanger.h
GUIDanielPerspectiveChanger.cpp