SUMO - Simulation of Urban MObility: MSContainer::MSContainerStage_Tranship Class Reference
MSContainer::MSContainerStage_Tranship Class Reference
#include <MSContainer.h>
Public Member Functions
virtual void abort (MSTransportable *)
abort this stage (TraCI)
virtual void beginEventOutput (const MSTransportable &c, SUMOTime t, OutputDevice &os) const
Called for writing the events output.
virtual void endEventOutput (const MSTransportable &c, SUMOTime t, OutputDevice &os) const
Called for writing the events output (end of an action)
double getAngle (SUMOTime now) const
Returns the angle of the container.
double getArrivalPos () const
CState * getContainerState () const
double getDepartPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
const MSEdge * getEdge () const
Returns the current edge.
double getEdgeAngle (const MSEdge *e, double at) const
get angle of the edge at a certain position
double getEdgePos (SUMOTime now) const
Returns the offset from the start of the current edge measured in its natural direction.
Position getEdgePosition (const MSEdge *e, double at, double offset) const
get position on edge e at length at with orthogonal offset
ConstMSEdgeVector getEdges () const
the edges of the current stage
const MSEdge * getFromEdge () const
Returns first edge of the containers route.
Position getLanePosition (const MSLane *lane, double at, double offset) const
get position on lane at length at with orthogonal offset
double getMaxSpeed () const
accessors to be used by MSCModel_NonInteracting
const MSEdge * getNextRouteEdge () const
Position getPosition (SUMOTime now) const
Returns the position of the container.
double getSpeed () const
Returns the speed of the container.
std::string getStageDescription () const
Returns the current stage description as a string.
StageType getStageType () const
const MSEdge * getToEdge () const
Returns last edge of the containers route.
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
SUMOTime getWaitingTime (SUMOTime now) const
Returns the time the container spent waiting.
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
bool moveToNextEdge (MSTransportable *container, SUMOTime currentTime, MSEdge *nextInternal=0)
move forward and return whether the container arrived
MSContainerStage_Tranship (const std::vector< const MSEdge *> &route, MSStoppingPlace *toStop, double speed, double departPos, double arrivalPos)
constructor
virtual void proceed (MSNet *net, MSTransportable *container, SUMOTime now, Stage *previous)
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
virtual void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void setSpeed (double)
sets the walking speed (ignored in other stages)
virtual void tripInfoOutput (OutputDevice &os, MSTransportable *transportable) const
Called on writing tripinfo output.
~MSContainerStage_Tranship ()
destructor
Protected Attributes
double myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
MSContainerStage_Tranship (const MSContainerStage_Tranship &)
Invalidated copy constructor.
MSContainerStage_Tranship & operator= (const MSContainerStage_Tranship &)
Invalidated assignment operator.
Private Attributes
CState * myContainerState
state that is to be manipulated by MSCModel
MSEdge * myCurrentInternalEdge
The current internal edge this container is on or 0.
double myDepartPos
the depart position
std::vector< const MSEdge * > myRoute
The route of the container.
std::vector< const MSEdge * >::iterator myRouteStep
current step
double mySpeed
the speed of the container
Friends
class MSCModel_NonInteracting
Detailed Description
A "real" stage performing the tranship of a container A container is in this stage if it gets transhipred between two stops that are assumed to be connected.
Definition at line 111 of file MSContainer.h.
Constructor & Destructor Documentation
MSContainerStage_Tranship() [1/2]
MSContainer::MSContainerStage_Tranship::MSContainerStage_Tranship (const std::vector< const MSEdge *> & route, MSStoppingPlace * toStop, double speed, double departPos, double arrivalPos)
constructor
Definition at line 121 of file MSContainer.cpp.
References SUMOVehicleParameter::interpretEdgePos(), myDepartPos, myRoute, and SUMO_ATTR_DEPARTPOS.
~MSContainerStage_Tranship()
MSContainer::MSContainerStage_Tranship::~MSContainerStage_Tranship ()
destructor
Definition at line 132 of file MSContainer.cpp.
MSContainerStage_Tranship() [2/2]
MSContainer::MSContainerStage_Tranship::MSContainerStage_Tranship (const MSContainerStage_Tranship &) private
Invalidated copy constructor.
Member Function Documentation
abort()
virtual void MSTransportable::Stage::abort (MSTransportable *) inline virtual inherited
abort this stage (TraCI)
Reimplemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, and MSPerson::MSPersonStage_Walking.
Definition at line 118 of file MSTransportable.h.
beginEventOutput()
void MSContainer::MSContainerStage_Tranship::beginEventOutput (const MSTransportable & c, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 221 of file MSContainer.cpp.
References MSTransportable::getID(), myRoute, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
endEventOutput()
void MSContainer::MSContainerStage_Tranship::endEventOutput (const MSTransportable & c, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 228 of file MSContainer.cpp.
References MSTransportable::getID(), myRoute, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
getAngle()
double MSContainer::MSContainerStage_Tranship::getAngle (SUMOTime now) const virtual
Returns the angle of the container.
Implements MSTransportable::Stage.
Definition at line 174 of file MSContainer.cpp.
References CState::getAngle(), and myContainerState.
getArrivalPos()
double MSContainer::MSContainerStage_Tranship::getArrivalPos () const inline
Definition at line 193 of file MSContainer.h.
References MSTransportable::Stage::myArrivalPos.
Referenced by CState::computeTranshipTime().
getContainerState()
CState* MSContainer::MSContainerStage_Tranship::getContainerState () const inline
Definition at line 201 of file MSContainer.h.
getDepartPos()
double MSContainer::MSContainerStage_Tranship::getDepartPos () const inline
Definition at line 189 of file MSContainer.h.
Referenced by CState::computeTranshipTime().
getDestination()
const MSEdge & MSTransportable::Stage::getDestination () const inherited
returns the destination edge
Definition at line 60 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by MSTransportable::Stage_Waiting::getEdges(), MSTransportable::Stage_Driving::getEdges(), MSPModel_Striping::moveInDirectionOnLane(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), and MSTransportable::Stage_Waiting::routeOutput().
getDestinationStop()
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline inherited
returns the destination stop (if any)
Definition at line 87 of file MSTransportable.h.
References MSTransportable::Stage::myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
getEdge()
const MSEdge * MSContainer::MSContainerStage_Tranship::getEdge () const virtual
Returns the current edge.
Implements MSTransportable::Stage.
Definition at line 145 of file MSContainer.cpp.
References myCurrentInternalEdge, and myRouteStep.
Referenced by CState::getAngle(), and moveToNextEdge().
getEdgeAngle()
double MSTransportable::Stage::getEdgeAngle (const MSEdge * e, double at) const inherited
get angle of the edge at a certain position
Definition at line 93 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), and MSTransportable::Stage::getVehicle().
getEdgePos()
double MSContainer::MSContainerStage_Tranship::getEdgePos (SUMOTime now) const virtual
Returns the offset from the start of the current edge measured in its natural direction.
Implements MSTransportable::Stage.
Definition at line 164 of file MSContainer.cpp.
References CState::getEdgePos(), and myContainerState.
getEdgePosition()
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, double at, double offset) const inherited
get position on edge e at length at with orthogonal offset
Definition at line 83 of file MSTransportable.cpp.
References MSTransportable::Stage::getLanePosition(), and MSEdge::getLanes().
Referenced by MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), and MSTransportable::Stage::getVehicle().
getEdges()
ConstMSEdgeVector MSContainer::MSContainerStage_Tranship::getEdges () const virtual
the edges of the current stage
Implements MSTransportable::Stage.
Definition at line 190 of file MSContainer.cpp.
References myRoute.
getFromEdge()
const MSEdge * MSContainer::MSContainerStage_Tranship::getFromEdge () const virtual
Returns first edge of the containers route.
Implements MSTransportable::Stage.
Definition at line 154 of file MSContainer.cpp.
References myRoute.
Referenced by CState::computeTranshipTime().
getLanePosition()
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, double at, double offset) const inherited
get position on lane at length at with orthogonal offset
Definition at line 88 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::positionAtOffset().
Referenced by CState::computeTranshipTime(), MSTransportable::Stage::getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and MSTransportable::Stage::getVehicle().
getMaxSpeed()
double MSContainer::MSContainerStage_Tranship::getMaxSpeed () const inline
accessors to be used by MSCModel_NonInteracting
Definition at line 185 of file MSContainer.h.
Referenced by CState::computeTranshipTime(), CState::getPosition(), and CState::getSpeed().
getNextRouteEdge()
const MSEdge* MSContainer::MSContainerStage_Tranship::getNextRouteEdge () const inline
Definition at line 197 of file MSContainer.h.
getPosition()
Position MSContainer::MSContainerStage_Tranship::getPosition (SUMOTime now) const virtual
Returns the position of the container.
Implements MSTransportable::Stage.
Definition at line 169 of file MSContainer.cpp.
References CState::getPosition(), and myContainerState.
getSpeed()
double MSContainer::MSContainerStage_Tranship::getSpeed () const virtual
Returns the speed of the container.
Implements MSTransportable::Stage.
Definition at line 184 of file MSContainer.cpp.
References CState::getSpeed(), and myContainerState.
getStageDescription()
std::string MSContainer::MSContainerStage_Tranship::getStageDescription () const inline virtual
Returns the current stage description as a string.
Implements MSTransportable::Stage.
Definition at line 152 of file MSContainer.h.
References MSTransportable::Stage_Driving::beginEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSContainer::MSContainerStage_Driving::routeOutput(), and MSContainer::MSContainerStage_Driving::tripInfoOutput().
getStageType()
StageType MSTransportable::Stage::getStageType () const inline inherited
Definition at line 107 of file MSTransportable.h.
References MSTransportable::Stage::getStageDescription(), MSTransportable::Stage::myType, and MSTransportable::Stage::proceed().
Referenced by MSTransportable::getStageType().
getToEdge()
const MSEdge * MSContainer::MSContainerStage_Tranship::getToEdge () const
Returns last edge of the containers route.
Definition at line 159 of file MSContainer.cpp.
References myRoute.
Referenced by CState::computeTranshipTime().
getVehicle()
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 138 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), MSTransportable::Stage::endEventOutput(), MSTransportable::Stage::getEdgeAngle(), MSTransportable::Stage::getEdgePosition(), MSTransportable::Stage::getEdges(), MSTransportable::Stage::getLanePosition(), MSTransportable::Stage::getSpeed(), MSTransportable::Stage::getWaitingTime(), MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
getWaitingTime()
SUMOTime MSContainer::MSContainerStage_Tranship::getWaitingTime (SUMOTime now) const virtual
Returns the time the container spent waiting.
Implements MSTransportable::Stage.
Definition at line 179 of file MSContainer.cpp.
isWaiting4Vehicle()
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 133 of file MSTransportable.h.
isWaitingFor()
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual inherited
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 78 of file MSTransportable.cpp.
Referenced by MSTransportable::Stage::setSpeed().
moveToNextEdge()
bool MSContainer::MSContainerStage_Tranship::moveToNextEdge (MSTransportable * container, SUMOTime currentTime, MSEdge * nextInternal = 0)
move forward and return whether the container arrived
Definition at line 234 of file MSContainer.cpp.
References MSStoppingPlace::addTransportable(), MSTransportableControl::erase(), MSNet::getContainerControl(), getEdge(), MSNet::getInstance(), myCurrentInternalEdge, MSTransportable::Stage::myDestinationStop, myRoute, myRouteStep, and MSTransportable::proceed().
operator=()
MSContainerStage_Tranship& MSContainer::MSContainerStage_Tranship::operator= (const MSContainerStage_Tranship &) private
Invalidated assignment operator.
proceed()
void MSContainer::MSContainerStage_Tranship::proceed (MSNet * net, MSTransportable * container, SUMOTime now, Stage * previous) virtual
proceeds to the next step
Implements MSTransportable::Stage.
Definition at line 136 of file MSContainer.cpp.
References MSCModel_NonInteracting::add(), MSTransportable::Stage::getEdgePos(), MSCModel_NonInteracting::getModel(), myContainerState, MSTransportable::Stage::myDeparted, myDepartPos, myRoute, and myRouteStep.
routeOutput()
void MSContainer::MSContainerStage_Tranship::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 213 of file MSContainer.cpp.
References OutputDevice::closeTag(), myRoute, mySpeed, OutputDevice::openTag(), SUMO_ATTR_EDGES, SUMO_ATTR_SPEED, and OutputDevice::writeAttr().
setArrived()
void MSTransportable::Stage::setArrived (SUMOTime now) virtual inherited
logs end of the step
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 73 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrived.
Referenced by MSTransportable::Stage_Driving::getVehicle(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::Stage_Driving::setArrived(), and MSTransportable::Stage::setSpeed().
setDeparted()
void MSTransportable::Stage::setDeparted (SUMOTime now) inherited
logs end of the step
Definition at line 66 of file MSTransportable.cpp.
References MSTransportable::Stage::myDeparted.
Referenced by MSTransportable::getVehicleType(), and MSTransportable::Stage::setSpeed().
setSpeed()
virtual void MSTransportable::Stage::setSpeed (double) inline virtual inherited
sets the walking speed (ignored in other stages)
Reimplemented in MSPerson::MSPersonStage_Walking.
Definition at line 121 of file MSTransportable.h.
References MSTransportable::Stage::isWaitingFor(), MSTransportable::Stage::setArrived(), and MSTransportable::Stage::setDeparted().
Referenced by MSTransportable::getVehicle().
tripInfoOutput()
void MSContainer::MSContainerStage_Tranship::tripInfoOutput (OutputDevice & os, MSTransportable * transportable) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 196 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::myArrivalPos, MSTransportable::Stage::myArrived, MSTransportable::Stage::myDeparted, myDepartPos, mySpeed, OutputDevice::openTag(), STEPS2TIME, time2string(), and OutputDevice::writeAttr().
Friends And Related Function Documentation
MSCModel_NonInteracting
friend class MSCModel_NonInteracting friend
Definition at line 112 of file MSContainer.h.
Field Documentation
myArrivalPos
double MSTransportable::Stage::myArrivalPos protected inherited
the position at which we want to arrive
Definition at line 192 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage::getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), getArrivalPos(), MSTransportable::Stage_Waiting::getEdgePos(), MSTransportable::Stage_Waiting::getPosition(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Walking::walkDistance().
myArrived
SUMOTime MSTransportable::Stage::myArrived protected inherited
the time at which this stage ended
Definition at line 198 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
myContainerState
CState* MSContainer::MSContainerStage_Tranship::myContainerState private
state that is to be manipulated by MSCModel
Definition at line 219 of file MSContainer.h.
Referenced by getAngle(), getEdgePos(), getPosition(), getSpeed(), and proceed().
myCurrentInternalEdge
MSEdge* MSContainer::MSContainerStage_Tranship::myCurrentInternalEdge private
The current internal edge this container is on or 0.
Definition at line 222 of file MSContainer.h.
Referenced by getEdge(), and moveToNextEdge().
myDeparted
SUMOTime MSTransportable::Stage::myDeparted protected inherited
the time at which this stage started
Definition at line 195 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getWaitingTime(), MSTransportable::Stage_Driving::getWaitingTime(), MSPerson::MSPersonStage_Walking::proceed(), proceed(), MSTransportable::Stage_Waiting::proceed(), MSTransportable::Stage::setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
myDepartPos
double MSContainer::MSContainerStage_Tranship::myDepartPos private
the depart position
Definition at line 213 of file MSContainer.h.
Referenced by MSContainerStage_Tranship(), proceed(), and tripInfoOutput().
myDestination
const MSEdge& MSTransportable::Stage::myDestination protected inherited
the next edge to reach by getting transported
Definition at line 186 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage::getDestination(), MSTransportable::Stage_Waiting::getEdge(), MSTransportable::Stage_Waiting::getFromEdge(), and MSTransportable::Stage_Waiting::getPosition().
myDestinationStop
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected inherited
the stop to reach by getting transported (if any)
Definition at line 189 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getDestinationStop(), MSTransportable::Stage_Driving::getWaitingDescription(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), moveToNextEdge(), MSPerson::MSPersonStage_Walking::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
myRoute
std::vector<const MSEdge*> MSContainer::MSContainerStage_Tranship::myRoute private
The route of the container.
Definition at line 207 of file MSContainer.h.
Referenced by beginEventOutput(), endEventOutput(), getEdges(), getFromEdge(), getToEdge(), moveToNextEdge(), MSContainerStage_Tranship(), proceed(), and routeOutput().
myRouteStep
std::vector<const MSEdge*>::iterator MSContainer::MSContainerStage_Tranship::myRouteStep private
current step
Definition at line 210 of file MSContainer.h.
Referenced by getEdge(), moveToNextEdge(), and proceed().
mySpeed
double MSContainer::MSContainerStage_Tranship::mySpeed private
the speed of the container
Definition at line 216 of file MSContainer.h.
Referenced by routeOutput(), and tripInfoOutput().
myType
StageType MSTransportable::Stage::myType protected inherited
The type of this stage.
Definition at line 201 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getStageType(), MSTransportable::Stage_Waiting::routeOutput(), and MSTransportable::Stage_Waiting::tripInfoOutput().
The documentation for this class was generated from the following files:
MSContainer.h
MSContainer.cpp