SUMO - Simulation of Urban MObility: FXLinkLabel Class Reference
FXLinkLabel Class Reference
#include <FXLinkLabel.h>
Public Types
enum { ID_FIRST = FXLabel::ID_LAST, ID_TIMER, ID_LAST }
Public Member Functions
FXLinkLabel (FXComposite *p, const FXString &text, FXIcon *ic=0, FXuint opts=LABEL_NORMAL, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
Constructor.
long onLeftBtnPress (FXObject *, FXSelector, void *)
long onTimer (FXObject *, FXSelector, void *)
virtual ~FXLinkLabel ()
Destructor.
Static Public Member Functions
static FXint fxexecute (FXString link)
Protected Member Functions
FXLinkLabel ()
Detailed Description
A label which points to a link. This class behaves very much like the FXLabel class but it points to some link which is started when clicked.
Definition at line 40 of file FXLinkLabel.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_FIRST
ID_TIMER
ID_LAST
Definition at line 53 of file FXLinkLabel.h.
Constructor & Destructor Documentation
FXLinkLabel() [1/2]
FXLinkLabel::FXLinkLabel () inline protected
Definition at line 44 of file FXLinkLabel.h.
References ~FXLinkLabel().
FXLinkLabel() [2/2]
FXLinkLabel::FXLinkLabel (FXComposite * p, const FXString & text, FXIcon * ic = 0, FXuint opts = LABEL_NORMAL, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD)
Constructor.
Definition at line 86 of file FXLinkLabel.cpp.
~FXLinkLabel()
FXLinkLabel::~FXLinkLabel () virtual
Destructor.
Definition at line 91 of file FXLinkLabel.cpp.
References ID_TIMER.
Referenced by FXLinkLabel().
Member Function Documentation
fxexecute()
FXint FXLinkLabel::fxexecute (FXString link) static
Definition at line 41 of file FXLinkLabel.cpp.
References FXDEFMAP(), ID_TIMER, onLeftBtnPress(), and onTimer().
Referenced by GUIApplicationWindow::onCmdHelp(), GNEApplicationWindow::onCmdHelp(), and onLeftBtnPress().
onLeftBtnPress()
long FXLinkLabel::onLeftBtnPress (FXObject * , FXSelector , void *)
Definition at line 95 of file FXLinkLabel.cpp.
References fxexecute(), and ID_TIMER.
Referenced by fxexecute().
onTimer()
long FXLinkLabel::onTimer (FXObject * , FXSelector , void *)
Definition at line 109 of file FXLinkLabel.cpp.
Referenced by fxexecute().
The documentation for this class was generated from the following files:
FXLinkLabel.h
FXLinkLabel.cpp