SUMO - Simulation of Urban MObility: RODFDetectorCon Class Reference
RODFDetectorCon Class Reference
A container for RODFDetectors.
#include <RODFDetector.h>
Public Member Functions
bool addDetector (RODFDetector *dfd)
bool detectorsHaveCompleteTypes () const
bool detectorsHaveRoutes () const
int getAggFlowFor (const ROEdge *edge, SUMOTime time, SUMOTime period, const RODFDetectorFlows &flows) const
const RODFDetector & getAnyDetectorForEdge (const RODFEdge *const edge) const
const RODFDetector & getDetector (const std::string &id) const
const std::vector< RODFDetector * > & getDetectors () const
RODFDetector & getModifiableDetector (const std::string &id) const
void guessEmptyFlows (RODFDetectorFlows &flows)
bool knows (const std::string &id) const
void mesoJoin (const std::string &nid, const std::vector< std::string > &oldids)
void removeDetector (const std::string &id)
RODFDetectorCon ()
void save (const std::string &file) const
void saveAsPOIs (const std::string &file) const
void saveRoutes (const std::string &file) const
void setSpeedFactorAndDev (SUMOVTypeParameter &type, double maxFactor, double avgFactor, double dev, bool forceDev)
void writeEmitterPOIs (const std::string &file, const RODFDetectorFlows &flows)
void writeEmitters (const std::string &file, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, const RODFNet &net, bool writeCalibrators, bool includeUnusedRoutes, double scale, bool insertionsOnly)
void writeEndRerouterDetectors (const std::string &file)
void writeSpeedTrigger (const RODFNet *const net, const std::string &file, const RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
void writeValidationDetectors (const std::string &file, bool includeSources, bool singleFile, bool friendly)
~RODFDetectorCon ()
Protected Member Functions
void clearDists (std::map< SUMOTime, RandomDistributor< int > * > &dists) const
Clears the given distributions map, deleting the timed distributions.
Protected Attributes
std::map< std::string, std::vector< RODFDetector * > > myDetectorEdgeMap
std::map< std::string, RODFDetector * > myDetectorMap
std::vector< RODFDetector * > myDetectors
Private Member Functions
RODFDetectorCon & operator= (const RODFDetectorCon &src)
Invalidated assignment operator.
RODFDetectorCon (const RODFDetectorCon &src)
Invalidated copy constructor.
Detailed Description
A container for RODFDetectors.
Definition at line 227 of file RODFDetector.h.
Constructor & Destructor Documentation
RODFDetectorCon() [1/2]
RODFDetectorCon::RODFDetectorCon ()
Definition at line 476 of file RODFDetector.cpp.
~RODFDetectorCon()
RODFDetectorCon::~RODFDetectorCon ()
Definition at line 479 of file RODFDetector.cpp.
RODFDetectorCon() [2/2]
RODFDetectorCon::RODFDetectorCon (const RODFDetectorCon & src) private
Invalidated copy constructor.
Member Function Documentation
addDetector()
bool RODFDetectorCon::addDetector (RODFDetector * dfd)
Definition at line 487 of file RODFDetector.cpp.
References Named::getID(), and RODFDetector::getLaneID().
Referenced by RODFDetectorHandler::myStartElement().
clearDists()
void RODFDetectorCon::clearDists (std::map< SUMOTime, RandomDistributor< int > * > & dists) const protected
Clears the given distributions map, deleting the timed distributions.
Parameters
[in] dists The distribution map to clear
Definition at line 955 of file RODFDetector.cpp.
detectorsHaveCompleteTypes()
bool RODFDetectorCon::detectorsHaveCompleteTypes () const
Definition at line 503 of file RODFDetector.cpp.
References TYPE_NOT_DEFINED.
Referenced by startComputation().
detectorsHaveRoutes()
bool RODFDetectorCon::detectorsHaveRoutes () const
Definition at line 514 of file RODFDetector.cpp.
Referenced by startComputation().
getAggFlowFor()
int RODFDetectorCon::getAggFlowFor (const ROEdge * edge, SUMOTime time, SUMOTime period, const RODFDetectorFlows & flows) const
Definition at line 759 of file RODFDetector.cpp.
References Named::getID(), FlowDef::qLKW, FlowDef::qPKW, and UNUSED_PARAMETER.
Referenced by RODFDetector::computeSplitProbabilities().
getAnyDetectorForEdge()
const RODFDetector & RODFDetectorCon::getAnyDetectorForEdge (const RODFEdge *const edge) const
Definition at line 944 of file RODFDetector.cpp.
References Named::getID().
Referenced by RODFDetector::buildDestinationDistribution().
getDetector()
const RODFDetector & RODFDetectorCon::getDetector (const std::string & id) const
Definition at line 609 of file RODFDetector.cpp.
Referenced by RODFNet::buildDetectorDependencies(), RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), RODFNet::hasInBetweenDetectorsOnly(), RODFNet::hasSourceDetector(), RODFNet::isDestination(), RODFNet::isFalseSource(), RODFNet::isSource(), and RODFNet::mesoJoin().
getDetectors()
const std::vector< RODFDetector * > & RODFDetectorCon::getDetectors () const
Definition at line 525 of file RODFDetector.cpp.
Referenced by RODFNet::buildDetectorEdgeDependencies(), RODFNet::buildRoutes(), RODFNet::computeTypes(), readDetectors(), RODFNet::removeEmptyDetectors(), RODFNet::reportEmptyDetectors(), RODFNet::revalidateFlows(), and startComputation().
getModifiableDetector()
RODFDetector & RODFDetectorCon::getModifiableDetector (const std::string & id) const
Definition at line 615 of file RODFDetector.cpp.
Referenced by RODFNet::buildDetectorDependencies().
guessEmptyFlows()
void RODFDetectorCon::guessEmptyFlows (RODFDetectorFlows & flows)
Definition at line 899 of file RODFDetector.cpp.
References RODFDetector::getFollowerDetectors(), Named::getID(), RODFDetector::getPriorDetectors(), and RODFDetectorFlows::knows().
Referenced by startComputation().
knows()
bool RODFDetectorCon::knows (const std::string & id) const
Definition at line 621 of file RODFDetector.cpp.
Referenced by RODFDetFlowLoader::read().
mesoJoin()
void RODFDetectorCon::mesoJoin (const std::string & nid, const std::vector< std::string > & oldids)
Definition at line 963 of file RODFDetector.cpp.
References RODFDetector::RODFDetector().
Referenced by RODFNet::mesoJoin().
operator=()
RODFDetectorCon& RODFDetectorCon::operator= (const RODFDetectorCon & src) private
Invalidated assignment operator.
removeDetector()
void RODFDetectorCon::removeDetector (const std::string & id)
Definition at line 872 of file RODFDetector.cpp.
Referenced by RODFNet::removeEmptyDetectors().
save()
void RODFDetectorCon::save (const std::string & file) const
Definition at line 531 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, OutputDevice::close(), OutputDevice::closeTag(), DISCARDED_DETECTOR, StringUtils::escapeXML(), OutputDevice::getDevice(), OutputDevice::openTag(), SINK_DETECTOR, SOURCE_DETECTOR, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_TAG_DETECTOR_DEFINITION, OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
saveAsPOIs()
void RODFDetectorCon::saveAsPOIs (const std::string & file) const
Definition at line 559 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, RGBColor::BLUE, OutputDevice::close(), DISCARDED_DETECTOR, StringUtils::escapeXML(), OutputDevice::getDevice(), RGBColor::GREEN, OutputDevice::openTag(), RGBColor::RED, SINK_DETECTOR, SOURCE_DETECTOR, SUMO_ATTR_COLOR, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_TAG_POI, OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
saveRoutes()
void RODFDetectorCon::saveRoutes (const std::string & file) const
Definition at line 587 of file RODFDetector.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), SOURCE_DETECTOR, and OutputDevice::writeXMLHeader().
Referenced by startComputation().
setSpeedFactorAndDev()
void RODFDetectorCon::setSpeedFactorAndDev (SUMOVTypeParameter & type, double maxFactor, double avgFactor, double dev, bool forceDev)
Definition at line 710 of file RODFDetector.cpp.
References Distribution_Parameterized::getParameter(), NUMERICAL_EPS, SUMOVTypeParameter::parametersSet, SUMOVTypeParameter::speedFactor, and VTYPEPARS_SPEEDFACTOR_SET.
writeEmitterPOIs()
void RODFDetectorCon::writeEmitterPOIs (const std::string & file, const RODFDetectorFlows & flows)
Definition at line 727 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, OutputDevice::close(), DISCARDED_DETECTOR, StringUtils::escapeXML(), OutputDevice::getDevice(), RODFDetectorFlows::getFlowSumSecure(), Named::getID(), RODFDetectorFlows::getMaxDetectorFlow(), OutputDevice::openTag(), SINK_DETECTOR, SOURCE_DETECTOR, SUMO_ATTR_COLOR, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_TAG_POI, toString(), OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
writeEmitters()
void RODFDetectorCon::writeEmitters (const std::string & file, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset, const RODFNet & net, bool writeCalibrators, bool includeUnusedRoutes, double scale, bool insertionsOnly)
Definition at line 627 of file RODFDetector.cpp.
References BETWEEN_DETECTOR, RODFDetector::buildDestinationDistribution(), OutputDevice::close(), OutputDevice::closeTag(), DEFAULT_VTYPE_ID, StringUtils::escapeXML(), RODFNet::getAvgSpeedFactorLKW(), RODFNet::getAvgSpeedFactorPKW(), OutputDevice::getDevice(), RONet::getEdge(), RODFDetector::getEdgeID(), FileHelpers::getFilePath(), OptionsCont::getFloat(), Named::getID(), RODFDetector::getLaneID(), RODFNet::getMaxSpeedFactorLKW(), RODFNet::getMaxSpeedFactorPKW(), OptionsCont::getOptions(), RODFDetector::getPos(), OptionsCont::getString(), RODFDetector::getType(), OptionsCont::isDefault(), RODFDetectorFlows::knows(), MAX2(), OutputDevice::openTag(), SUMOVTypeParameter::parametersSet, SOURCE_DETECTOR, SUMO_ATTR_FILE, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_TAG_CALIBRATOR, SVC_PASSENGER, SVC_TRUCK, VTYPEPARS_VEHICLECLASS_SET, SUMOVTypeParameter::write(), OutputDevice::writeAttr(), RODFDetector::writeEmitterDefinition(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
writeEndRerouterDetectors()
void RODFDetectorCon::writeEndRerouterDetectors (const std::string & file)
Definition at line 825 of file RODFDetector.cpp.
References OutputDevice::close(), StringUtils::escapeXML(), OutputDevice::getDevice(), Named::getID(), RODFDetector::getLaneID(), RODFDetector::getType(), OutputDevice::openTag(), SINK_DETECTOR, SUMO_ATTR_EDGES, SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_POSITION, SUMO_TAG_REROUTER, OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
writeSpeedTrigger()
void RODFDetectorCon::writeSpeedTrigger (const RODFNet *const net, const std::string & file, const RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 803 of file RODFDetector.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), StringUtils::escapeXML(), OutputDevice::getDevice(), RONet::getEdge(), RODFDetector::getEdgeID(), FileHelpers::getFilePath(), Named::getID(), RODFDetector::getLaneID(), RODFDetector::getType(), RODFDetectorFlows::knows(), OutputDevice::openTag(), SINK_DETECTOR, SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_LANES, SUMO_TAG_VSS, OutputDevice::writeAttr(), RODFDetector::writeSingleSpeedTrigger(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
writeValidationDetectors()
void RODFDetectorCon::writeValidationDetectors (const std::string & file, bool includeSources, bool singleFile, bool friendly)
Definition at line 841 of file RODFDetector.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), StringUtils::escapeXML(), OutputDevice::getDevice(), Named::getID(), RODFDetector::getLaneID(), RODFDetector::getPos(), RODFDetector::getType(), OutputDevice::openTag(), SOURCE_DETECTOR, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_TAG_E1DETECTOR, OutputDevice::writeAttr(), and OutputDevice::writeXMLHeader().
Referenced by startComputation().
Field Documentation
myDetectorEdgeMap
std::map<std::string, std::vector<RODFDetector*> > RODFDetectorCon::myDetectorEdgeMap protected
Definition at line 283 of file RODFDetector.h.
myDetectorMap
std::map<std::string, RODFDetector*> RODFDetectorCon::myDetectorMap protected
Definition at line 282 of file RODFDetector.h.
myDetectors
std::vector<RODFDetector*> RODFDetectorCon::myDetectors protected
Definition at line 281 of file RODFDetector.h.
The documentation for this class was generated from the following files:
RODFDetector.h
RODFDetector.cpp