SUMO - Simulation of Urban MObility: MSMeanData_Amitran::MSLaneMeanDataValues Class Reference
MSMeanData_Amitran::MSLaneMeanDataValues Class Reference
Data structure for mean (aggregated) edge/lane values.
#include <MSMeanData_Amitran.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
void addTo (MSMeanData::MeanDataValues &val) const
Add the values of this to the given one and store them there.
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
virtual double getSamples () const
Returns the number of collected sample seconds.
double getTravelledDistance () const
Returns the total travelled distance.
bool isEmpty () const
Returns whether any data was collected.
MSLaneMeanDataValues (MSLane *const lane, const double length, const bool doAdd, const MSMeanData_Amitran *parent)
Constructor.
virtual bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Called if the vehicle leaves the reminder's lane.
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
void reset (bool afterWrite=false)
Resets values so they may be used for the next interval.
void setDescription (const std::string &description)
virtual void update ()
Called if a per timestep update is needed. Default does nothing.
void write (OutputDevice &dev, const SUMOTime period, const double numLanes, const double defaultTravelTime, const int numVehicles=-1) const
Writes output values into the given stream.
virtual ~MSLaneMeanDataValues ()
Destructor.
Methods inherited from MSMoveReminder
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Computes current values and adds them to their sums.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void notifyMoveInternal (const SUMOVehicle &veh, const double, const double timeOnLane, const double, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double)
Internal notification about the vehicle moves.
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
const double myLaneLength
The length of the lane / edge the data collector is on.
const MSMeanData *const myParent
The meandata parent.
Collected values
The number of sampled vehicle movements (in s)
double sampleSeconds
double travelledDistance
The sum of the distances the vehicles travelled.
Private Attributes
Collected values
The number of vehicles that entered this lane within the sample interval
int amount
std::map< const MSVehicleType *, int > typedAmount
The number of vehicles that entered this lane within the sample interval by type.
std::map< const MSVehicleType *, double > typedSamples
The number of sampled vehicle movements by type (in s)
std::map< const MSVehicleType *, double > typedTravelDistance
The sum of the distances the vehicles travelled by type.
Detailed Description
Data structure for mean (aggregated) edge/lane values.
Structure holding values that describe the flow and other physical properties aggregated over some seconds.
Definition at line 72 of file MSMeanData_Amitran.h.
Member Enumeration Documentation
Notification
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSLaneMeanDataValues()
MSMeanData_Amitran::MSLaneMeanDataValues::MSLaneMeanDataValues (MSLane *const lane, const double length, const bool doAdd, const MSMeanData_Amitran * parent)
Constructor.
Parameters
[in] length The length of the object for which the data gets collected
Definition at line 48 of file MSMeanData_Amitran.cpp.
~MSLaneMeanDataValues()
MSMeanData_Amitran::MSLaneMeanDataValues::~MSLaneMeanDataValues () virtual
Destructor.
Definition at line 55 of file MSMeanData_Amitran.cpp.
Member Function Documentation
addTo()
void MSMeanData_Amitran::MSLaneMeanDataValues::addTo (MSMeanData::MeanDataValues & val) const virtual
Add the values of this to the given one and store them there.
Parameters
[in] val The meandata to add to
Implements MSMeanData::MeanDataValues.
Definition at line 69 of file MSMeanData_Amitran.cpp.
References amount, MSMeanData::MeanDataValues::sampleSeconds, MSMeanData::MeanDataValues::travelledDistance, typedAmount, typedSamples, and typedTravelDistance.
getDescription()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 234 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::getSingularType(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::write().
getLane()
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), libsumo::InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
getSamples()
double MSMeanData::MeanDataValues::getSamples () const virtual inherited
Returns the number of collected sample seconds.
Returns
the number of collected sample seconds
Reimplemented in MSMeanData::MeanDataValueTracker.
Definition at line 281 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::sampleSeconds.
Referenced by MSCalibrator::currentSpeed(), MSMeanData::writePrefix(), MEInductLoop::writeXMLOutput(), and MSCalibrator::writeXMLOutput().
getTravelledDistance()
double MSMeanData::MeanDataValues::getTravelledDistance () const inline inherited
Returns the total travelled distance.
Returns
the total travelled distance
Definition at line 165 of file MSMeanData.h.
References MSMeanData::MeanDataValues::travelledDistance.
Referenced by MSCalibrator::currentSpeed(), and MSCalibrator::writeXMLOutput().
isEmpty()
bool MSMeanData_Amitran::MSLaneMeanDataValues::isEmpty () const virtual
Returns whether any data was collected.
Returns
whether no data was collected
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 111 of file MSMeanData_Amitran.cpp.
References amount, and MSMeanData::MeanDataValues::sampleSeconds.
notifyEnter()
bool MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Computes current values and adds them to their sums.
The fraction of time the vehicle is on the lane is computed and used as a weight for the vehicle's current values. The "emitted" field is incremented, additionally.
Parameters
[in] veh The vehicle that enters the lane
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
Always true
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 96 of file MSMeanData_Amitran.cpp.
References amount, MSMoveReminder::getLane(), SUMOVehicle::getVehicleType(), MSMeanData::MeanDataValues::myParent, MSMoveReminder::NOTIFICATION_DEPARTED, MSMoveReminder::NOTIFICATION_JUNCTION, typedAmount, and MSDetectorFileOutput::vehicleApplies().
notifyLeave()
bool MSMeanData::MeanDataValues::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual inherited
Called if the vehicle leaves the reminder's lane.
Parameters
veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Reimplemented in MSMeanData::MeanDataValueTracker, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 261 of file MSMeanData.cpp.
References MSGlobals::gUseMesoSim, and MSMoveReminder::NOTIFICATION_JUNCTION.
notifyMove()
bool MSMeanData::MeanDataValues::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual inherited
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented from MSMoveReminder.
Definition at line 91 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), MSMoveReminder::getLane(), MSVehicleType::getLength(), SUMOVehicle::getPreviousSpeed(), SUMOVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, SUMOVehicle::hasArrived(), MAX2(), MIN2(), MIN4(), MSMoveReminder::myLane, MSMeanData::MeanDataValues::myLaneLength, MSMoveReminder::notifyMoveInternal(), NUMERICAL_EPS, MSCFModel::passingTime(), MSCFModel::speedAfterTime(), TS, and WRITE_ERROR.
notifyMoveInternal()
void MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal (const SUMOVehicle & veh, const double , const double timeOnLane, const double , const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double) protected virtual
Internal notification about the vehicle moves.
See also
MSMoveReminder::notifyMoveInternal()
Reimplemented from MSMoveReminder.
Definition at line 87 of file MSMeanData_Amitran.cpp.
References SUMOVehicle::getVehicleType(), MSMeanData::MeanDataValues::sampleSeconds, MSMeanData::MeanDataValues::travelledDistance, typedSamples, and typedTravelDistance.
removeFromVehicleUpdateValues()
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 93 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
reset()
void MSMeanData_Amitran::MSLaneMeanDataValues::reset (bool afterWrite = false) virtual
Resets values so they may be used for the next interval.
Implements MSMeanData::MeanDataValues.
Definition at line 60 of file MSMeanData_Amitran.cpp.
References amount, typedAmount, typedSamples, and typedTravelDistance.
setDescription()
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 230 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
update()
void MSMeanData::MeanDataValues::update () virtual inherited
Called if a per timestep update is needed. Default does nothing.
Reimplemented in MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 276 of file MSMeanData.cpp.
updateDetector()
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 50 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
write()
void MSMeanData_Amitran::MSLaneMeanDataValues::write (OutputDevice & dev, const SUMOTime period, const double numLanes, const double defaultTravelTime, const int numVehicles = -1) const virtual
Writes output values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] period Length of the period the data were gathered
[in] numLanes The total number of lanes for which the data was collected
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSMeanData::MeanDataValues.
Definition at line 117 of file MSMeanData_Amitran.cpp.
References amount, OutputDevice::closeTag(), MSDetectorFileOutput::isTyped(), MSMeanData::MeanDataValues::myLaneLength, MSMeanData::MeanDataValues::myParent, OutputDevice::openTag(), MSMeanData::MeanDataValues::sampleSeconds, SUMO_ATTR_ID, MSMeanData::MeanDataValues::travelledDistance, typedAmount, typedSamples, typedTravelDistance, and OutputDevice::writeAttr().
Field Documentation
amount
int MSMeanData_Amitran::MSLaneMeanDataValues::amount private
Definition at line 135 of file MSMeanData_Amitran.h.
Referenced by addTo(), isEmpty(), notifyEnter(), reset(), and write().
myDescription
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 246 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
myLane
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 244 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), and MSMeanData::MeanDataValueTracker::reset().
myLaneLength
const double MSMeanData::MeanDataValues::myLaneLength protected inherited
The length of the lane / edge the data collector is on.
Definition at line 174 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyMove(), MSMeanData::MeanDataValueTracker::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
myParent
const MSMeanData* const MSMeanData::MeanDataValues::myParent protected inherited
The meandata parent.
Definition at line 171 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyEnter(), notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyLeave(), MSMeanData::MeanDataValueTracker::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), and write().
sampleSeconds
double MSMeanData::MeanDataValues::sampleSeconds protected inherited
Definition at line 179 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData::MeanDataValues::getSamples(), isEmpty(), MSMeanData_Net::MSLaneMeanDataValues::isEmpty(), MSMeanData::MeanDataValues::isEmpty(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
travelledDistance
double MSMeanData::MeanDataValues::travelledDistance protected inherited
The sum of the distances the vehicles travelled.
Definition at line 182 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData::MeanDataValues::getTravelledDistance(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
typedAmount
std::map<const MSVehicleType*, int> MSMeanData_Amitran::MSLaneMeanDataValues::typedAmount private
The number of vehicles that entered this lane within the sample interval by type.
Definition at line 138 of file MSMeanData_Amitran.h.
Referenced by addTo(), notifyEnter(), reset(), and write().
typedSamples
std::map<const MSVehicleType*, double> MSMeanData_Amitran::MSLaneMeanDataValues::typedSamples private
The number of sampled vehicle movements by type (in s)
Definition at line 141 of file MSMeanData_Amitran.h.
Referenced by addTo(), notifyMoveInternal(), reset(), and write().
typedTravelDistance
std::map<const MSVehicleType*, double> MSMeanData_Amitran::MSLaneMeanDataValues::typedTravelDistance private
The sum of the distances the vehicles travelled by type.
Definition at line 144 of file MSMeanData_Amitran.h.
Referenced by addTo(), notifyMoveInternal(), reset(), and write().
The documentation for this class was generated from the following files:
MSMeanData_Amitran.h
MSMeanData_Amitran.cpp