SUMO - Simulation of Urban MObility: GNENet Class Reference
GNENet Class Reference
A NBNetBuilder extended by visualisation and editing capabilities.
#include <GNENet.h>
Data Structures
class GNEChange_ReplaceEdgeInTLS
class for GNEChange_ReplaceEdgeInTLS
Public Types
typedef NamedObjectCont< PointOfInterest * > POIs
typedef NamedObjectCont< SUMOPolygon * > Polygons
containers
Public Member Functions
void addExplicitTurnaround (std::string id)
add edge id to the list of explicit turnarounds
GNEEdge * addReversedEdge (GNEEdge *edge, GNEUndoList *undoList)
add reversed edge
bool addSRestrictedLane (SUMOVehicleClass vclass, GNEEdge &edge, GNEUndoList *undoList)
add restricted lane to edge
void changeEdgeEndpoints (GNEEdge *edge, const std::string &newSourceID, const std::string &newDestID)
modifies endpoins of the given edge
bool cleanInvalidCrossings (GNEUndoList *undoList)
clear invalid crossings
void clearJunctionConnections (GNEJunction *junction, GNEUndoList *undoList)
clear junction's connections
void computeAndUpdate (OptionsCont &oc, bool volatileOptions)
recompute the network and update lane geometries
void computeEverything (GNEApplicationWindow *window, bool force=false, bool volatileOptions=false, std::string additionalPath="", std::string shapePath="")
trigger full netbuild computation param[in] window The window to inform about delay param[in] force Whether to force recomputation even if not needed param[in] volatileOptions enable or disable volatile options param[in] additionalPath path in wich additionals were saved before recomputing with volatile options param[in] shapePath path in wich shapes were saved before recomputing with volatile options
void computeJunction (GNEJunction *junction)
trigger recomputation of junction shape and logic param[in] window The window to inform about delay
GNEEdge * createEdge (GNEJunction *src, GNEJunction *dest, GNEEdge *tpl, GNEUndoList *undoList, const std::string &suggestedName="", bool wasSplit=false, bool allowDuplicateGeom=false)
creates a new edge (unless an edge with the same geometry already exists)
GNEJunction * createJunction (const Position &pos, GNEUndoList *undoList)
creates a new junction
void deleteConnection (GNEConnection *connection, GNEUndoList *undoList)
remove connection
void deleteCrossing (GNECrossing *crossing, GNEUndoList *undoList)
remove crossing
void deleteEdge (GNEEdge *edge, GNEUndoList *undoList)
removes edge
void deleteJunction (GNEJunction *junction, GNEUndoList *undoList)
removes junction and all incident edges
void deleteLane (GNELane *lane, GNEUndoList *undoList)
removes lane
void deleteShape (GNEShape *shape, GNEUndoList *undoList)
remove shape
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
void duplicateLane (GNELane *lane, GNEUndoList *undoList)
duplicates lane
std::string generateVaporizerID () const
generate an ID for vaporizers
FXApp * getApp ()
get pointer to the main App
const Boundary & getBoundary () const
returns the bounder of the network
std::set< GUIGlID > getGlIDs (GUIGlObjectType type=GLO_MAX)
get ids of currently active objects
NBNetBuilder * getNetBuilder () const
get net builder
const POIs & getPOIs () const
Returns all pois.
const Polygons & getPolygons () const
Returns all polygons.
NBTrafficLightLogicCont & getTLLogicCont ()
returns the tllcont of the underlying netbuilder
GNEViewNet * getViewNet () const
get view net
SUMORTree & getVisualisationSpeedUp ()
Returns the RTree used for visualisation speed-up.
const SUMORTree & getVisualisationSpeedUp () const
Returns the RTree used for visualisation speed-up.
GNENet (NBNetBuilder *netBuilder)
Constructor.
void initGNEConnections ()
initialize GNEConnections
bool joinSelectedJunctions (GNEUndoList *undoList)
join selected junctions
void mergeJunctions (GNEJunction *moved, GNEJunction *target, GNEUndoList *undoList)
merge the given junctions edges between the given junctions will be deleted
virtual void movePOI (const std::string &id, const Position &pos)
Assigns a new position to the named PoI.
bool netHasGNECrossings () const
check if net has GNECrossings
void refreshElement (GUIGlObject *o)
refreshes boundary information for o and update
void removeExplicitTurnaround (std::string id)
remove edge id from the list of explicit turnarounds
virtual bool removePOI (const std::string &id)
Removes a PoI from the container.
virtual bool removePolygon (const std::string &id)
Removes a polygon from the container.
bool removeRestrictedLane (SUMOVehicleClass vclass, GNEEdge &edge, GNEUndoList *undoList)
remove restricted lane
void removeSolitaryJunctions (GNEUndoList *undoList)
removes junctions that have no edges
void renameEdge (GNEEdge *edge, const std::string &newID)
updates the map and reserves new id
void renameJunction (GNEJunction *junction, const std::string &newID)
updates the map and reserves new id
void replaceIncomingEdge (GNEEdge *which, GNEEdge *by, GNEUndoList *undoList)
replaces edge
void replaceJunctionByGeometry (GNEJunction *junction, GNEUndoList *undoList)
replace the selected junction by geometry node(s) and merge the edges
void requireRecompute ()
inform the net about the need for recomputation
void resetJunctionConnections (GNEJunction *junction, GNEUndoList *undoList)
reset junction's connections
virtual void reshapePolygon (const std::string &id, const PositionVector &shape)
Assigns a shape to the named polygon.
bool restrictLane (SUMOVehicleClass vclass, GNELane *lane, GNEUndoList *undoList)
transform lane to restricted lane
GNEAttributeCarrier * retrieveAttributeCarrier (const GUIGlID id, bool failHard=true)
get a single attribute carrier based on a GLID
std::vector< GNEAttributeCarrier * > retrieveAttributeCarriers (const std::set< GUIGlID > &ids, GUIGlObjectType type)
get the attribute carriers based on GlIDs
GNEEdge * retrieveEdge (const std::string &id, bool failHard=true)
get edge by id
GNEEdge * retrieveEdge (GNEJunction *from, GNEJunction *to, bool failHard=true)
get edge by from and to GNEJunction
std::vector< GNEEdge * > retrieveEdges (bool onlySelected=false)
return all edges
GNEJunction * retrieveJunction (const std::string &id, bool failHard=true)
get junction by id
std::vector< GNEJunction * > retrieveJunctions (bool onlySelected=false)
return all junctions
GNELane * retrieveLane (const std::string &id, bool failHard=true, bool checkVolatileChange=false)
get lane by id
std::vector< GNELane * > retrieveLanes (bool onlySelected=false)
return all lanes
GNEPOI * retrievePOI (const std::string &id, bool failHard=true) const
get POI by id
GNEPOILane * retrievePOILane (const std::string &id, bool failHard=true) const
get POILane by id
GNEPoly * retrievePolygon (const std::string &id, bool failHard=true) const
get Polygon by id
std::vector< GNEShape * > retrieveShapes (SumoXMLTag shapeTag=SUMO_TAG_NOTHING, bool onlySelected=false)
return all shapes
void reverseEdge (GNEEdge *edge, GNEUndoList *undoList)
reverse edge
void save (OptionsCont &oc)
save the network
void saveJoined (OptionsCont &oc)
save log of joined junctions (and nothing else)
void savePlain (OptionsCont &oc)
save plain xml representation of the network (and nothing else)
void setViewNet (GNEViewNet *viewNet)
Set the viewNet to be notified of network changes.
GNEJunction * splitEdge (GNEEdge *edge, const Position &pos, GNEUndoList *undoList, GNEJunction *newJunction=0)
split edge at position by inserting a new junction
void splitEdgesBidi (const std::set< GNEEdge *> &edges, const Position &pos, GNEUndoList *undoList)
split all edges at position by inserting one new junction
~GNENet ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
const Boundary & getZBoundary () const
Returns the Z boundary (stored in the x() coordinate) values of 0 do not affect the boundary.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from ShapeHandler
bool addPolygon (const std::string &id, const std::string &type, const RGBColor &color, double layer, double angle, const std::string &imgFile, const PositionVector &shape, bool fill, bool geo, bool ignorePruning=false)
Builds a polygon using the given values and adds it to the container.
bool addPOI (const std::string &id, const std::string &type, const RGBColor &color, const Position &pos, bool geo, const std::string &lane, double posOverLane, double posLat, double layer, double angle, const std::string &imgFile, double width, double height, bool ignorePruning=false)
Builds a POI using the given values and adds it to the container.
Functions related to Additional Items
GNEAdditional * retrieveAdditional (const std::string &id, bool hardFail=true) const
Returns the named additional.
std::vector< GNEAdditional * > retrieveAdditionals (bool onlySelected=false)
return all additionals
GNEAdditional * getAdditional (SumoXMLTag type, const std::string &id) const
Returns the named additional.
std::vector< GNEAdditional * > getAdditionals (SumoXMLTag type=SUMO_TAG_NOTHING) const
get vector with additionals
GNERerouterInterval * getRerouterInterval (const std::string &rerouterIntervalID) const
int getNumberOfAdditionals (SumoXMLTag type=SUMO_TAG_NOTHING) const
Returns the number of additionals of the net.
void updateAdditionalID (const std::string &oldID, GNEAdditional *additional)
update additional ID in container
void requiereSaveAdditionals ()
inform that additionals has to be saved
void saveAdditionals (const std::string &filename)
save additional elements of the network
Functions related to Calibrator Items
Note
all three duplicates functions will be unified using GNERoute class
GNECalibratorRoute * retrieveCalibratorRoute (const std::string &id, bool hardFail=true) const
Returns the named calibrator route.
GNECalibratorVehicleType * retrieveCalibratorVehicleType (const std::string &id, bool hardFail=true) const
Returns the named calibrator vehicle type.
GNECalibratorFlow * retrieveCalibratorFlow (const std::string &id, bool hardFail=true) const
Returns the named calibrator flow.
std::string generateCalibratorRouteID () const
generate a new Calibrator Route ID
std::string generateCalibratorVehicleTypeID () const
generate a new Calibrator Vehicle Type ID
std::string generateCalibratorFlowID () const
generate a new Calibrator Flow ID
void changeCalibratorRouteID (GNECalibratorRoute *route, const std::string &oldID)
change Calibrator Route ID
void changeCalibratorVehicleTypeID (GNECalibratorVehicleType *vehicleType, const std::string &oldID)
change Calibrator Vehicle Type ID
void changeCalibratorFlowID (GNECalibratorFlow *flow, const std::string &oldID)
change Calibrator Flow ID
Functions related to Shapes
GNEPoly * addPolygonForEditShapes (GNENetElement *netElement, const PositionVector &shape, bool fill)
Builds a special polygon used for edit Junctions's shapes.
void removePolygonForEditShapes (GNEPoly *polygon)
remove Polygon for edit shapes
std::string generateShapeID (SumoXMLTag shapeTag) const
generate Shape ID
void changeShapeID (GNEShape *s, const std::string &OldID)
change Shape ID
void requiereSaveShapes ()
inform that shapes has to be saved
void saveShapes (const std::string &filename)
save shapes elements of the network
int getNumberOfShapes () const
get number of shapes
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
color of selected objects
color of selection
static const RGBColor selectionColor
static const RGBColor selectedLaneColor
color of selected lane
static const RGBColor selectedConnectionColor
color of selected connection
static const RGBColor selectedAdditionalColor
color of selected additionals
Protected Member Functions
virtual bool add (SUMOPolygon *poly, bool ignorePruning=false)
add polygon
virtual bool add (PointOfInterest *poi, bool ignorePruning=false)
add poi
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
Insertion and erasing of GNEAdditionals items
void insertAdditional (GNEAdditional *additional)
Insert a additional element int GNENet container.
void deleteAdditional (GNEAdditional *additional)
delete additional element of GNENet container
Insertion and erasing of GNECalibrator items
void insertCalibratorRoute (GNECalibratorRoute *route)
insert Calibrator Route in net
void deleteCalibratorRoute (GNECalibratorRoute *route)
delete Calibrator Route in net
void insertCalibratorFlow (GNECalibratorFlow *flow)
insert Calibrator Flow in net
void deleteCalibratorFlow (GNECalibratorFlow *flow)
delete Calibrator Flow in net
void insertCalibratorVehicleType (GNECalibratorVehicleType *vehicleType)
insert Calibrator VehicleType in net
void deleteCalibratorVehicleType (GNECalibratorVehicleType *vehicleType)
delete Calibrator VehicleType in net
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
std::map< std::pair< std::string, SumoXMLTag >, GNEAdditional * > myAdditionals
map with the name and pointer to additional elements of net
bool myAdditionalsSaved
Flag to check if additionals has to be saved.
std::map< std::string, GNECalibratorFlow * > myCalibratorFlows
map with the name and pointer to Calibrator Flows of net
std::map< std::string, GNECalibratorRoute * > myCalibratorRoutes
map with the name and pointer to Calibrator Routes of net
std::map< std::string, GNECalibratorVehicleType * > myCalibratorVehicleTypes
map with the name and pointer to Calibrator Vehicle Types of net
std::map< std::string, GNEEdge * > myEdges
map with the name and pointer to edges of net
std::set< std::string > myExplicitTurnarounds
list of edge ids for which turn-arounds must be added explicitly
SUMORTree myGrid
the rtree which contains all GUIGlObjects (so named for historical reasons)
std::map< std::string, GNEJunction * > myJunctions
map with the name and pointer to junctions of net
bool myNeedRecompute
whether the net needs recomputation
NBNetBuilder * myNetBuilder
The internal netbuilder.
POIs myPOIs
stored POIs
Polygons myPolygons
stored Polygons
bool myShapesSaved
Flag to check if shapes hast o be saved.
GNEViewNet * myViewNet
The viewNet to be notofied of about changes.
ID Suppliers for newly created edges and junctions
IDSupplier myEdgeIDSupplier
IDSupplier myJunctionIDSupplier
Private Member Functions
bool checkJunctionPosition (const Position &pos)
return true if there are already a Junction in the given position, false in other case
void deleteSingleEdge (GNEEdge *edge)
deletes a single edge
void deleteSingleJunction (GNEJunction *junction)
deletes a single junction
void initJunctionsAndEdges ()
Init Junctions and edges.
void insertEdge (GNEEdge *edge)
inserts a single edge into the net and into the underlying netbuild-container
void insertJunction (GNEJunction *junction)
inserts a single junction into the net and into the underlying netbuild-container
void insertShape (GNEShape *shape)
insert shape
GNEEdge * registerEdge (GNEEdge *edge)
registers an edge with GNENet containers
GNEJunction * registerJunction (GNEJunction *junction)
registers a junction with GNENet containers
void remapEdge (GNEEdge *oldEdge, GNEJunction *from, GNEJunction *to, GNEUndoList *undoList, bool preserveShapeStart, bool preserveShapeEnd)
void removeShape (GNEShape *shape)
remove created shape (but NOT delete)
void reserveEdgeID (const std::string &id)
reserve edge ID (To avoid duplicates)
void reserveJunctionID (const std::string &id)
reserve junction ID (To avoid duplicates)
void update ()
notify myViewNet
Static Private Member Functions
static void replaceInListAttribute (GNEAttributeCarrier *ac, SumoXMLAttr key, const std::string &which, const std::string &by, GNEUndoList *undoList)
Private Attributes
std::map< std::string, int > myEdgesAndNumberOfLanes
map with the Edges and their number of lanes
Boundary myZBoundary
the z boundary (stored in the x-coordinate), values of 0 are ignored
Static Private Attributes
static const double Z_INITIALIZED = 1
marker for whether the z-boundary is initialized
Friends
class GNEAdditionalHandler
declare friend class
class GNEChange_Additional
class GNEChange_CalibratorItem
class GNEChange_Connection
class GNEChange_Edge
class GNEChange_Junction
class GNEChange_Lane
class GNEChange_Shape
Detailed Description
A NBNetBuilder extended by visualisation and editing capabilities.
Definition at line 91 of file GNENet.h.
Member Typedef Documentation
POIs
typedef NamedObjectCont<PointOfInterest*> ShapeContainer::POIs inherited
Definition at line 52 of file ShapeContainer.h.
Polygons
typedef NamedObjectCont<SUMOPolygon*> ShapeContainer::Polygons inherited
containers
Definition at line 51 of file ShapeContainer.h.
Constructor & Destructor Documentation
GNENet()
GNENet::GNENet (NBNetBuilder * netBuilder)
Constructor.
Parameters
[in] netbuilder the netbuilder which may already have been filled GNENet becomes responsible for cleaning this up
Definition at line 117 of file GNENet.cpp.
References GUIGlObjectStorage::gIDStorage, and GUIGlObjectStorage::setNetObject().
~GNENet()
GNENet::~GNENet ()
Destructor.
Definition at line 142 of file GNENet.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), myAdditionals, myCalibratorFlows, myCalibratorRoutes, myCalibratorVehicleTypes, myEdges, myJunctions, myNetBuilder, toString(), and WRITE_WARNING.
Member Function Documentation
add() [1/2]
bool ShapeContainer::add (SUMOPolygon * poly, bool ignorePruning = false) protected virtual inherited
add polygon
Reimplemented in PCPolyContainer.
Definition at line 102 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and ShapeContainer::myPolygons.
Referenced by PCPolyContainer::add(), ShapeContainer::addPOI(), ShapeContainer::addPolygon(), and ShapeContainer::getPOIs().
add() [2/2]
bool ShapeContainer::add (PointOfInterest * poi, bool ignorePruning = false) protected virtual inherited
add poi
Reimplemented in PCPolyContainer.
Definition at line 112 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and ShapeContainer::myPOIs.
addExplicitTurnaround()
void GNENet::addExplicitTurnaround (std::string id)
add edge id to the list of explicit turnarounds
Definition at line 1628 of file GNENet.cpp.
References myExplicitTurnarounds.
Referenced by GNEJunction::setLogicValid().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
addPOI()
bool GNENet::addPOI (const std::string & id, const std::string & type, const RGBColor & color, const Position & pos, bool geo, const std::string & lane, double posOverLane, double posLat, double layer, double angle, const std::string & imgFile, double width, double height, bool ignorePruning = false) virtual
Builds a POI using the given values and adds it to the container.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] pos The position of the POI
Reimplemented from ShapeContainer.
Definition at line 251 of file GNENet.cpp.
References NamedObjectCont< T >::add(), NamedObjectCont< T >::get(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEChange_Shape, ShapeContainer::myPOIs, myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), retrieveLane(), and toString().
Referenced by GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), and GNEViewNet::onCmdTransformPOI().
addPolygon()
bool GNENet::addPolygon (const std::string & id, const std::string & type, const RGBColor & color, double layer, double angle, const std::string & imgFile, const PositionVector & shape, bool fill, bool geo, bool ignorePruning = false) virtual
Builds a polygon using the given values and adds it to the container.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] geo specify if shape was loaded as GEO coordinate
[in] fill Whether the polygon shall be filled
Returns
whether the polygon could be added
Reimplemented from ShapeContainer.
Definition at line 234 of file GNENet.cpp.
References NamedObjectCont< T >::get(), GNEViewNet::getUndoList(), GNEChange_Shape, ShapeContainer::myPolygons, myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_POLY, and toString().
Referenced by GNEPolygonFrame::addPolygon().
addPolygonForEditShapes()
GNEPoly * GNENet::addPolygonForEditShapes (GNENetElement * netElement, const PositionVector & shape, bool fill)
Builds a special polygon used for edit Junctions's shapes.
Parameters
[in] netElement GNENetElement to be edited
[in] shape shape to be edited
[in] fill enable or disable fill polygon
Exceptions
processError if shape is empty
Returns
created GNEPoly
Definition at line 1911 of file GNENet.cpp.
References SUMORTree::addAdditionalGLObject(), GLO_POLYGON, RGBColor::GREEN, myGrid, myViewNet, SUMOPolygon::setFill(), GUIPolygon::setLineWidth(), and GNEPoly::setShapeEditedElement().
Referenced by GNEViewNet::startEditCustomShape().
addReversedEdge()
GNEEdge * GNENet::addReversedEdge (GNEEdge * edge, GNEUndoList * undoList)
add reversed edge
Parameters
[in] edge The edge of which to add the reverse
Returns
Return the new edge or 0
Definition at line 765 of file GNENet.cpp.
References createEdge(), createJunction(), NBEdge::getGeometry(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEAttributeCarrier::getID(), NBEdge::getInnerGeometry(), NBEdge::getLaneSpreadFunction(), GNEEdge::getNBEdge(), NBEdge::getPermissions(), GUISelectedStorage::getSelected(), NBEdge::getTotalWidth(), gSelected, isRailway(), LANESPREAD_RIGHT, PositionVector::move2side(), GNEUndoList::p_begin(), GNEUndoList::p_end(), PositionVector::reverse(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, and toString().
Referenced by GNEViewNet::onCmdAddReversedEdge().
addSRestrictedLane()
bool GNENet::addSRestrictedLane (SUMOVehicleClass vclass, GNEEdge & edge, GNEUndoList * undoList)
add restricted lane to edge
Parameters
[in] vclass vehicle class to restrict
[in] edge The edge in which insert restricted lane
[in] undoList The undolist in which to mark changes
Definition at line 662 of file GNENet.cpp.
References duplicateLane(), GNEEdge::getLanes(), and restrictLane().
Referenced by GNEViewNet::addRestrictedLane().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
changeCalibratorFlowID()
void GNENet::changeCalibratorFlowID (GNECalibratorFlow * flow, const std::string & oldID)
change Calibrator Flow ID
Definition at line 1900 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorFlows.
Referenced by GNECalibratorFlow::setAttribute().
changeCalibratorRouteID()
void GNENet::changeCalibratorRouteID (GNECalibratorRoute * route, const std::string & oldID)
change Calibrator Route ID
Definition at line 1878 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorRoutes.
Referenced by GNECalibratorRoute::setAttribute().
changeCalibratorVehicleTypeID()
void GNENet::changeCalibratorVehicleTypeID (GNECalibratorVehicleType * vehicleType, const std::string & oldID)
change Calibrator Vehicle Type ID
Definition at line 1889 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorVehicleTypes.
Referenced by GNECalibratorVehicleType::setAttribute().
changeEdgeEndpoints()
void GNENet::changeEdgeEndpoints (GNEEdge * edge, const std::string & newSourceID, const std::string & newDestID)
modifies endpoins of the given edge
Definition at line 1597 of file GNENet.cpp.
References GNEEdge::getNBEdge(), GNEJunction::getNBNode(), NBEdge::reinitNodes(), requireRecompute(), retrieveJunction(), and update().
Referenced by GNEEdge::setAttribute().
changeShapeID()
void GNENet::changeShapeID (GNEShape * s, const std::string & OldID)
change Shape ID
Definition at line 1964 of file GNENet.cpp.
References NamedObjectCont< T >::changeID(), NamedObjectCont< T >::get(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), ShapeContainer::myPOIs, ShapeContainer::myPolygons, and SUMO_TAG_POLY.
Referenced by GNEPOI::setAttribute(), GNEPOILane::setAttribute(), and GNEPoly::setAttribute().
checkJunctionPosition()
bool GNENet::checkJunctionPosition (const Position & pos) private
return true if there are already a Junction in the given position, false in other case
Definition at line 846 of file GNENet.cpp.
References myJunctions.
Referenced by joinSelectedJunctions().
cleanInvalidCrossings()
bool GNENet::cleanInvalidCrossings (GNEUndoList * undoList)
clear invalid crossings
Definition at line 1444 of file GNENet.cpp.
References deleteCrossing(), getApp(), OptionsCont::getBool(), OptionsCont::getOptions(), myJunctions, GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CROSSING, toString(), and WRITE_WARNING.
Referenced by GNEApplicationWindow::onCmdCleanInvalidCrossings().
clearJunctionConnections()
void GNENet::clearJunctionConnections (GNEJunction * junction, GNEUndoList * undoList)
clear junction's connections
Definition at line 1561 of file GNENet.cpp.
References deleteConnection(), GNEJunction::getGNEConnections(), GNEUndoList::p_begin(), and GNEUndoList::p_end().
Referenced by GNEViewNet::onCmdClearConnections(), replaceJunctionByGeometry(), and resetJunctionConnections().
computeAndUpdate()
void GNENet::computeAndUpdate (OptionsCont & oc, bool volatileOptions)
recompute the network and update lane geometries
Definition at line 2302 of file GNENet.cpp.
References Boundary::add(), NBNetBuilder::compute(), OptionsCont::getBool(), GeoConvHelper::getFinal(), GNEViewNet::getUndoList(), initGNEConnections(), initJunctionsAndEdges(), OptionsCont::isSet(), myAdditionals, myEdges, myExplicitTurnarounds, myGrid, myJunctions, myNeedRecompute, myNetBuilder, ShapeContainer::myPOIs, ShapeContainer::myPolygons, myViewNet, refreshElement(), SUMORTree::removeAdditionalGLObject(), and Boundary::reset().
Referenced by computeEverything(), GNELoadThread::run(), save(), saveJoined(), and savePlain().
computeEverything()
void GNENet::computeEverything (GNEApplicationWindow * window, bool force = false, bool volatileOptions = false, std::string additionalPath = "", std::string shapePath = "")
trigger full netbuild computation param[in] window The window to inform about delay param[in] force Whether to force recomputation even if not needed param[in] volatileOptions enable or disable volatile options param[in] additionalPath path in wich additionals were saved before recomputing with volatile options param[in] shapePath path in wich shapes were saved before recomputing with volatile options
Definition at line 1235 of file GNENet.cpp.
References computeAndUpdate(), OptionsCont::getOptions(), myEdges, myEdgesAndNumberOfLanes, myNeedRecompute, myViewNet, XMLSubSys::runParser(), GNEApplicationWindow::setStatusBarText(), update(), and WRITE_MESSAGE.
Referenced by GNEApplicationWindow::onCmdComputeJunctions(), GNEApplicationWindow::onCmdComputeJunctionsVolatile(), and GNEViewNet::setEditMode().
computeJunction()
void GNENet::computeJunction (GNEJunction * junction)
trigger recomputation of junction shape and logic param[in] window The window to inform about delay
Definition at line 1292 of file GNENet.cpp.
References NBTrafficLightLogicCont::computeSingleLogic(), NBNode::getControllingTLS(), GNEJunction::getNBNode(), OptionsCont::getOptions(), and getTLLogicCont().
Referenced by GNETLSEditorFrame::onCmdDefSwitch().
createEdge()
GNEEdge * GNENet::createEdge (GNEJunction * src, GNEJunction * dest, GNEEdge * tpl, GNEUndoList * undoList, const std::string & suggestedName = "", bool wasSplit = false, bool allowDuplicateGeom = false)
creates a new edge (unless an edge with the same geometry already exists)
Parameters
[in] src The starting junction
[in] dest The ending junction
[in] tpl The template edge from which to copy attributes (including lane attrs)
[in] undoList The undoList in which to mark changes
[in] suggestedName
[in] wasSplit Whether the edge was created from a split
[in] allowDuplicateGeom Whether to create the edge even though another edge with the same geometry exists
Returns
The newly created edge or 0 if no edge was created
Definition at line 323 of file GNENet.cpp.
References GNEEdge::getNBEdge(), GNEJunction::getNBNode(), IDSupplier::getNext(), NBNode::getOutgoingEdges(), GNEChange_Edge, myEdgeIDSupplier, myEdges, GNEUndoList::p_begin(), GNEUndoList::p_end(), requireRecompute(), reserveEdgeID(), retrieveEdge(), GNEJunction::setLogicValid(), SUMO_TAG_EDGE, toString(), NBEdge::UNSPECIFIED_OFFSET, and NBEdge::UNSPECIFIED_WIDTH.
Referenced by addReversedEdge(), GNEViewNet::onLeftBtnPress(), remapEdge(), reverseEdge(), and splitEdge().
createJunction()
GNEJunction * GNENet::createJunction (const Position & pos, GNEUndoList * undoList)
creates a new junction
Parameters
[in] position The position of the new junction
[in] undoList The undolist in which to mark changes
Returns
the new junction
Definition at line 312 of file GNENet.cpp.
References IDSupplier::getNext(), GNEChange_Junction, myJunctionIDSupplier, and myJunctions.
Referenced by addReversedEdge(), joinSelectedJunctions(), GNEViewNet::onLeftBtnPress(), and splitEdge().
deleteAdditional()
void GNENet::deleteAdditional (GNEAdditional * additional) protected
delete additional element of GNENet container
Exceptions
processError if additional wasn't previously inserted
Definition at line 2036 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, myGrid, SUMORTree::removeAdditionalGLObject(), requiereSaveAdditionals(), toString(), and update().
Referenced by GNEChange_Additional::redo(), GNEChange_Lane::redo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), and GNEChange_Additional::~GNEChange_Additional().
deleteCalibratorFlow()
void GNENet::deleteCalibratorFlow (GNECalibratorFlow * flow) protected
delete Calibrator Flow in net
Exceptions
processError if flow wasn't previously inserted
Definition at line 2084 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorFlows.
Referenced by GNEChange_CalibratorItem::redo(), GNEChange_CalibratorItem::undo(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
deleteCalibratorRoute()
void GNENet::deleteCalibratorRoute (GNECalibratorRoute * route) protected
delete Calibrator Route in net
Exceptions
processError if route wasn't previously inserted
Definition at line 2063 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorRoutes.
Referenced by GNEChange_CalibratorItem::redo(), GNEChange_CalibratorItem::undo(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
deleteCalibratorVehicleType()
void GNENet::deleteCalibratorVehicleType (GNECalibratorVehicleType * vehicleType) protected
delete Calibrator VehicleType in net
Exceptions
processError if vehicleType wasn't previously inserted
Definition at line 2105 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorVehicleTypes.
Referenced by GNEChange_CalibratorItem::redo(), GNEChange_CalibratorItem::undo(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
deleteConnection()
void GNENet::deleteConnection (GNEConnection * connection, GNEUndoList * undoList)
remove connection
Parameters
[in] connection The connection to be removed
[in] undoList The undolist in which to mark changes
Definition at line 570 of file GNENet.cpp.
References GUISelectedStorage::deselect(), GNEConnection::getEdgeFrom(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEConnection::getNBConnection(), GNEConnection::getNBEdgeConnection(), GNEViewNet::getUndoList(), GLO_CONNECTION, GNEChange_Connection, gSelected, GNEJunction::invalidateTLS(), GUISelectedStorage::isSelected(), GNEJunction::markAsModified(), myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), requireRecompute(), SUMO_TAG_CONNECTION, and toString().
Referenced by clearJunctionConnections(), GNEViewNet::deleteSelectedConnections(), GNEConnectorFrame::handleLaneClick(), and GNEDeleteFrame::removeAttributeCarrier().
deleteCrossing()
void GNENet::deleteCrossing (GNECrossing * crossing, GNEUndoList * undoList)
remove crossing
Parameters
[in] crossing The crossing to be removed
[in] undoList The undolist in which to mark changes
Definition at line 590 of file GNENet.cpp.
References NBNode::Crossing::customShape, NBNode::Crossing::customTLIndex, GUISelectedStorage::deselect(), NBNode::Crossing::edges, GUIGlObject::getGlID(), GNECrossing::getNBCrossing(), GNECrossing::getParentJunction(), GLO_CROSSING, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_begin(), GNEUndoList::p_end(), NBNode::Crossing::priority, requireRecompute(), and NBNode::Crossing::width.
Referenced by cleanInvalidCrossings(), deleteJunction(), GNEViewNet::deleteSelectedCrossings(), joinSelectedJunctions(), remapEdge(), GNEDeleteFrame::removeAttributeCarrier(), GNEJunction::removeEdgeFromCrossings(), and GNEEdge::removeEdgeFromCrossings().
deleteEdge()
void GNENet::deleteEdge (GNEEdge * edge, GNEUndoList * undoList)
removes edge
Parameters
[in] edge The edge to be removed
[in] undoList The undolist in which to mark changes
Definition at line 430 of file GNENet.cpp.
References GNENetElement::getAdditionalChilds(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEEdge::getLanes(), GLO_EDGE, GNEChange_Additional, GNEChange_Edge, GNEChange_Shape, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::removeEdgeFromCrossings(), GNEEdge::removeEdgeOfAdditionalParents(), requireRecompute(), GNEJunction::setLogicValid(), SUMO_TAG_EDGE, and toString().
Referenced by deleteJunction(), deleteLane(), GNEViewNet::deleteSelectedEdges(), remapEdge(), GNEDeleteFrame::removeAttributeCarrier(), reverseEdge(), and splitEdge().
deleteJunction()
void GNENet::deleteJunction (GNEJunction * junction, GNEUndoList * undoList)
removes junction and all incident edges
Parameters
[in] junction The junction to be removed
[in] undoList The undolist in which to mark changes
Definition at line 378 of file GNENet.cpp.
References deleteCrossing(), deleteEdge(), NBNode::getEdges(), GUIGlObject::getGlID(), GNEJunction::getGNECrossings(), GNEJunction::getGNEEdges(), GNEJunction::getJunctionNeighbours(), GNEJunction::getNBNode(), GLO_JUNCTION, GNEChange_Junction, gSelected, GUISelectedStorage::isSelected(), myEdges, NODETYPE_PRIORITY, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::setAttribute(), SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, and toString().
Referenced by GNEViewNet::deleteSelectedJunctions(), joinSelectedJunctions(), mergeJunctions(), GNEDeleteFrame::removeAttributeCarrier(), removeSolitaryJunctions(), and replaceJunctionByGeometry().
deleteLane()
void GNENet::deleteLane (GNELane * lane, GNEUndoList * undoList)
removes lane
Parameters
[in] lane The lane to be removed
[in] undoList The undolist in which to mark changes
Definition at line 528 of file GNENet.cpp.
References deleteEdge(), GNENetElement::getAdditionalChilds(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNELane::getIndex(), NBEdge::getLaneStruct(), GNEEdge::getNBEdge(), NBEdge::getNumLanes(), GNELane::getParentEdge(), GNELane::getShapeChilds(), GLO_EDGE, GLO_LANE, GNEChange_Additional, GNEChange_Lane, GNEChange_Shape, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNELane::removeLaneOfAdditionalParents(), requireRecompute(), GNEJunction::setLogicValid(), SUMO_TAG_LANE, and toString().
Referenced by GNEViewNet::deleteSelectedLanes(), GNEDeleteFrame::removeAttributeCarrier(), and removeRestrictedLane().
deleteShape()
void GNENet::deleteShape (GNEShape * shape, GNEUndoList * undoList)
remove shape
Parameters
[in] shape The Shape to be removed
[in] undoList The undolist in which to mark changes
Definition at line 608 of file GNENet.cpp.
References GNEShape::getGlID(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GLO_POLYGON, GNEChange_Shape, gSelected, GUISelectedStorage::isSelected(), myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by GNEViewNet::deleteSelectedShapes(), GNEViewNet::onCmdTransformPOI(), and GNEDeleteFrame::removeAttributeCarrier().
deleteSingleEdge()
void GNENet::deleteSingleEdge (GNEEdge * edge) private
deletes a single edge
Definition at line 2214 of file GNENet.cpp.
References GNEReferenceCounter::decRef(), GUISelectedStorage::deselect(), NBEdgeCont::extract(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), GUIGlObject::getGlID(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), gSelected, myEdges, myGrid, myNetBuilder, SUMORTree::removeAdditionalGLObject(), GNEJunction::removeIncomingGNEEdge(), GNEJunction::removeOutgoingGNEEdge(), GNEEdge::setResponsible(), and update().
Referenced by GNEChange_Edge::redo(), and GNEChange_Edge::undo().
deleteSingleJunction()
void GNENet::deleteSingleJunction (GNEJunction * junction) private
deletes a single junction
Definition at line 2201 of file GNENet.cpp.
References GNEReferenceCounter::decRef(), GUISelectedStorage::deselect(), NBNodeCont::extract(), GUIGlObject::getGlID(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), NBNetBuilder::getNodeCont(), gSelected, myGrid, myJunctions, myNetBuilder, SUMORTree::removeAdditionalGLObject(), GNEJunction::setResponsible(), and update().
Referenced by GNEChange_Junction::redo(), and GNEChange_Junction::undo().
drawGL()
void GNENet::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 229 of file GNENet.cpp.
drawGLAdditional()
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 153 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GNERouteProbe::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
duplicateLane()
void GNENet::duplicateLane (GNELane * lane, GNEUndoList * undoList)
duplicates lane
Parameters
[in] lane The lane to be duplicated
[in] undoList The undolist in which to mark changes
Definition at line 623 of file GNENet.cpp.
References GNELane::getIndex(), NBEdge::getLaneStruct(), GNEEdge::getNBEdge(), GNELane::getParentEdge(), GNEChange_Lane, GNEUndoList::p_begin(), GNEUndoList::p_end(), requireRecompute(), SUMO_TAG_LANE, and toString().
Referenced by addSRestrictedLane(), and GNEViewNet::onCmdDuplicateLane().
generateCalibratorFlowID()
std::string GNENet::generateCalibratorFlowID () const
generate a new Calibrator Flow ID
Definition at line 1868 of file GNENet.cpp.
References myCalibratorFlows, SUMO_TAG_FLOW, and toString().
generateCalibratorRouteID()
std::string GNENet::generateCalibratorRouteID () const
generate a new Calibrator Route ID
Definition at line 1848 of file GNENet.cpp.
References myCalibratorRoutes, SUMO_TAG_ROUTE, and toString().
generateCalibratorVehicleTypeID()
std::string GNENet::generateCalibratorVehicleTypeID () const
generate a new Calibrator Vehicle Type ID
Definition at line 1858 of file GNENet.cpp.
References myCalibratorVehicleTypes, SUMO_TAG_VTYPE, and toString().
generateShapeID()
std::string GNENet::generateShapeID (SumoXMLTag shapeTag) const
generate Shape ID
Definition at line 1939 of file GNENet.cpp.
References NamedObjectCont< T >::get(), ShapeContainer::myPOIs, ShapeContainer::myPolygons, SUMO_TAG_POLY, and toString().
Referenced by GNEPolygonFrame::buildPoly(), and GNEPolygonFrame::processClick().
generateVaporizerID()
std::string GNENet::generateVaporizerID () const
generate an ID for vaporizers
Definition at line 1090 of file GNENet.cpp.
References myAdditionals, SUMO_TAG_VAPORIZER, and toString().
getAdditional()
GNEAdditional * GNENet::getAdditional (SumoXMLTag type, const std::string & id) const
Returns the named additional.
Parameters
[in] type tag with the type of additional
[in] id The id of the additional to return.
Returns
The named additional, or 0 if don't exists
Definition at line 1667 of file GNENet.cpp.
References myAdditionals.
Referenced by GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEAdditional::changeAdditionalID(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEDetectorExit::isValid(), GNEDetectorEntry::isValid(), GNECalibrator::isValid(), GNEAdditional::isValidAdditionalID(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEAdditionalHandler::parseAndBuildDetectorE1(), GNEAdditionalHandler::parseAndBuildDetectorE2(), GNEAdditionalHandler::parseAndBuildDetectorE3(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAdditionalHandler::parseAndBuildRouteProbe(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), and GNECalibrator::setAttribute().
getAdditionals()
std::vector< GNEAdditional * > GNENet::getAdditionals (SumoXMLTag type = SUMO_TAG_NOTHING) const
get vector with additionals
Parameters
[in] type type of additional to get. SUMO_TAG_NOTHING will get all additionals
Returns
vector with pointers to additionals.
Definition at line 1679 of file GNENet.cpp.
References myAdditionals, and SUMO_TAG_NOTHING.
Referenced by GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals().
getApp()
FXApp * GNENet::getApp ()
get pointer to the main App
Definition at line 1325 of file GNENet.cpp.
References myViewNet.
Referenced by cleanInvalidCrossings(), and joinSelectedJunctions().
getBoundary()
const Boundary & GNENet::getBoundary () const
returns the bounder of the network
Definition at line 202 of file GNENet.cpp.
References myGrid.
Referenced by getCenteringBoundary().
getCenteringBoundary()
Boundary GNENet::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 288 of file GNENet.cpp.
References getBoundary().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), deleteConnection(), deleteCrossing(), deleteEdge(), deleteJunction(), deleteLane(), deleteSingleEdge(), deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getGlIDs()
std::set< GUIGlID > GNENet::getGlIDs (GUIGlObjectType type = GLO_MAX)
get ids of currently active objects
Parameters
[in] type If type != GLO_MAX, get active ids of that type, otherwise get all active ids
Definition at line 1138 of file GNENet.cpp.
References GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_MAX, GLO_POI, GLO_POLYGON, GLO_TLLOGIC, myAdditionals, myEdges, myJunctions, ShapeContainer::myPOIs, and ShapeContainer::myPolygons.
Referenced by GNESelectorFrame::getMatches(), GNESelectorFrame::onCmdInvert(), and GNEViewParent::onCmdLocate().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), deleteSingleEdge(), deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNEPoly::getParentName(), GNERerouter::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), registerEdge(), registerJunction(), remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNetBuilder()
NBNetBuilder * GNENet::getNetBuilder () const
get net builder
Definition at line 1331 of file GNENet.cpp.
References myNetBuilder.
Referenced by GNEJunction::rebuildGNECrossings(), GNEChange_Crossing::redo(), and GNEChange_Crossing::undo().
getNumberOfAdditionals()
int GNENet::getNumberOfAdditionals (SumoXMLTag type = SUMO_TAG_NOTHING) const
Returns the number of additionals of the net.
Parameters
[in] type type of additional to count. SUMO_TAG_NOTHING will count all additionals
Returns
Number of additionals of the net
Definition at line 1709 of file GNENet.cpp.
References myAdditionals, and SUMO_TAG_NOTHING.
Referenced by GNEAdditionalFrame::generateID(), and GNEApplicationWindow::onCmdComputeJunctionsVolatile().
getNumberOfShapes()
int GNENet::getNumberOfShapes () const
get number of shapes
Definition at line 2014 of file GNENet.cpp.
References ShapeContainer::myPOIs, ShapeContainer::myPolygons, and NamedObjectCont< T >::size().
Referenced by GNEApplicationWindow::onCmdComputeJunctionsVolatile().
getParameterWindow()
GUIParameterTableWindow * GNENet::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 219 of file GNENet.cpp.
References GUIParameterTableWindow::closeBuilding().
getParentName()
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEPoly, GNERerouter, GNEPOILane, GNEVariableSpeedSign, GNENetElement, GNEPOI, GNERouteProbe, GNEStoppingPlace, GNEDetector, GUILane, GNEDetectorE3, GNEVaporizer, and GNELane.
Definition at line 114 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
getPOIs()
const POIs& ShapeContainer::getPOIs () const inline inherited
Returns all pois.
Definition at line 128 of file ShapeContainer.h.
References ShapeContainer::add(), and ShapeContainer::myPOIs.
Referenced by ShapeHandler::addPOI(), libsumo::POI::getIDList(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), GUIShapeContainer::getPOIIds(), libsumo::POI::getTree(), GNESelectorFrame::onCmdInvert(), and retrieveShapes().
getPolygons()
const Polygons& ShapeContainer::getPolygons () const inline inherited
Returns all polygons.
Definition at line 123 of file ShapeContainer.h.
References ShapeContainer::myPolygons.
Referenced by ShapeHandler::addPoly(), libsumo::Polygon::getIDList(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), GUIShapeContainer::getPolygonIDs(), libsumo::Polygon::getTree(), PCLoaderDlrNavteq::loadPolyFile(), GNESelectorFrame::onCmdInvert(), and retrieveShapes().
getPopUpMenu()
GUIGLObjectPopupMenu * GNENet::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 209 of file GNENet.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildPopupHeader(), and GUIGlObject::buildPositionCopyEntry().
getRerouterInterval()
GNERerouterInterval * GNENet::getRerouterInterval (const std::string & rerouterIntervalID) const
Definition at line 1691 of file GNENet.cpp.
References GNERerouter::getRerouterIntervals(), myAdditionals, and SUMO_TAG_REROUTER.
Referenced by GNEAdditionalHandler::parseAndBuildRerouterClosingLaneReroute().
getTLLogicCont()
NBTrafficLightLogicCont & GNENet::getTLLogicCont ()
returns the tllcont of the underlying netbuilder
Definition at line 1613 of file GNENet.cpp.
References NBNetBuilder::getTLLogicCont(), and myNetBuilder.
Referenced by GNEJunction::addTrafficLight(), computeJunction(), GNETLSEditorFrame::onCmdDefSwitch(), GNEJunction::removeTrafficLight(), replaceIncomingEdge(), and GNEJunction::setAttribute().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, GUIPerson, and GUIContainer.
Definition at line 126 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
getViewNet()
GNEViewNet * GNENet::getViewNet () const
get view net
Definition at line 1607 of file GNENet.cpp.
References myViewNet.
Referenced by GNEPoly::changeFirstGeometryPoint(), GNEPoly::closePolygon(), GNEEdge::commitShapeChange(), GNEEdge::deleteGeometryPoint(), GNEPoly::deleteGeometryPoint(), GNEJunction::drawGL(), GNEConnection::drawGL(), GNEPoly::drawGL(), GNEShape::drawLockIcon(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNEConnection::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GNEApplicationWindow::onCmdComputeJunctionsVolatile(), GNEApplicationWindow::onCmdOpenAdditionals(), GNEPoly::openPolygon(), GNEChange_Selection::redo(), GNEChange_Crossing::redo(), GNEConnection::setAttribute(), GNELane::setAttribute(), GNEPoly::simplifyShape(), GNEChange_Selection::undo(), GNEChange_Crossing::undo(), GNELane::updateGeometry(), and GNEJunction::updateShapesAndGeometries().
getVisualisationSpeedUp() [1/2]
SUMORTree & GNENet::getVisualisationSpeedUp ()
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 300 of file GNENet.cpp.
References myGrid.
Referenced by GNETLSEditorFrame::buildIinternalLanes().
getVisualisationSpeedUp() [2/2]
const SUMORTree & GNENet::getVisualisationSpeedUp () const
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 306 of file GNENet.cpp.
References myGrid.
getZBoundary()
const Boundary & GNENet::getZBoundary () const
Returns the Z boundary (stored in the x() coordinate) values of 0 do not affect the boundary.
Definition at line 294 of file GNENet.cpp.
References myZBoundary.
initGNEConnections()
void GNENet::initGNEConnections ()
initialize GNEConnections
Definition at line 2291 of file GNENet.cpp.
References myEdges.
Referenced by computeAndUpdate(), and GNEViewNet::onCmdToogleShowConnection().
initJunctionsAndEdges()
void GNENet::initJunctionsAndEdges () private
Init Junctions and edges.
Definition at line 2119 of file GNENet.cpp.
References Boundary::add(), NBNodeCont::getAllNames(), NBEdgeCont::getAllNames(), NBNetBuilder::getEdgeCont(), Boundary::getHeight(), NBNetBuilder::getNodeCont(), Boundary::getWidth(), myEdges, myGrid, myNetBuilder, registerEdge(), registerJunction(), NBNodeCont::retrieve(), NBEdgeCont::retrieve(), and NBNodesEdgesSorter::sortNodesEdges().
Referenced by computeAndUpdate().
insertAdditional()
void GNENet::insertAdditional (GNEAdditional * additional) protected
Insert a additional element int GNENet container.
Exceptions
processError if route was already inserted
Definition at line 2020 of file GNENet.cpp.
References SUMORTree::addAdditionalGLObject(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, myGrid, requiereSaveAdditionals(), toString(), and GNEAdditional::updateGeometry().
Referenced by GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Lane::undo(), and GNEChange_Additional::undo().
insertCalibratorFlow()
void GNENet::insertCalibratorFlow (GNECalibratorFlow * flow) protected
insert Calibrator Flow in net
Exceptions
processError if flow was already inserted
Definition at line 2074 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorFlows.
Referenced by GNEAdditionalHandler::buildCalibratorFlow(), GNEChange_CalibratorItem::redo(), and GNEChange_CalibratorItem::undo().
insertCalibratorRoute()
void GNENet::insertCalibratorRoute (GNECalibratorRoute * route) protected
insert Calibrator Route in net
Exceptions
processError if route was already inserted
Definition at line 2053 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorRoutes.
Referenced by GNEAdditionalHandler::buildCalibratorRoute(), GNEChange_CalibratorItem::redo(), and GNEChange_CalibratorItem::undo().
insertCalibratorVehicleType()
void GNENet::insertCalibratorVehicleType (GNECalibratorVehicleType * vehicleType) protected
insert Calibrator VehicleType in net
Exceptions
processError if vehicleType was already inserted
Definition at line 2095 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myCalibratorVehicleTypes.
Referenced by GNEAdditionalHandler::buildCalibratorVehicleType(), GNEChange_CalibratorItem::redo(), and GNEChange_CalibratorItem::undo().
insertEdge()
void GNENet::insertEdge (GNEEdge * edge) private
inserts a single edge into the net and into the underlying netbuild-container
Definition at line 2155 of file GNENet.cpp.
References NBNode::addIncomingEdge(), NBNode::addOutgoingEdge(), NBNetBuilder::getEdgeCont(), NBEdge::getFromNode(), GNEEdge::getNBEdge(), NBEdge::getToNode(), NBEdgeCont::insert(), myNetBuilder, and registerEdge().
Referenced by GNEChange_Edge::redo(), and GNEChange_Edge::undo().
insertJunction()
void GNENet::insertJunction (GNEJunction * junction) private
inserts a single junction into the net and into the underlying netbuild-container
Definition at line 2148 of file GNENet.cpp.
References GNEJunction::getNBNode(), NBNetBuilder::getNodeCont(), NBNodeCont::insert(), myNetBuilder, and registerJunction().
Referenced by GNEChange_Junction::redo(), and GNEChange_Junction::undo().
insertShape()
void GNENet::insertShape (GNEShape * shape) private
insert shape
Definition at line 2233 of file GNENet.cpp.
References NamedObjectCont< T >::add(), SUMORTree::addAdditionalGLObject(), GNEShape::getAttribute(), GNEAttributeCarrier::getGUIGLObject(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myGrid, ShapeContainer::myPOIs, ShapeContainer::myPolygons, requiereSaveShapes(), retrieveLane(), SUMO_ATTR_LANE, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEChange_Shape::redo(), and GNEChange_Shape::undo().
joinSelectedJunctions()
bool GNENet::joinSelectedJunctions (GNEUndoList * undoList)
join selected junctions
Note
difference to mergeJunctions:
can join more than 2
connected edges will keep their geometry (big junction shape is created)
no hirarchy: if any junction has a traffic light than the resuling junction will
Definition at line 1337 of file GNENet.cpp.
References NBNodeCont::analyzeCluster(), checkJunctionPosition(), createJunction(), deleteCrossing(), deleteJunction(), getApp(), OptionsCont::getBool(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), NBNetBuilder::getNodeCont(), OptionsCont::getOptions(), gSelected, myEdges, myJunctions, myNetBuilder, NODETYPE_TRAFFIC_LIGHT, GNEUndoList::p_begin(), GNEUndoList::p_end(), NBNodeCont::registerJoinedCluster(), remapEdge(), retrieveJunctions(), GUISelectedStorage::select(), GNEJunction::setAttribute(), Position::setx(), Position::sety(), SUMO_ATTR_ID, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_TAG_JUNCTION, toString(), WRITE_WARNING, Position::x(), and Position::y().
Referenced by GNEApplicationWindow::onCmdJoinJunctions().
mergeJunctions()
void GNENet::mergeJunctions (GNEJunction * moved, GNEJunction * target, GNEUndoList * undoList)
merge the given junctions edges between the given junctions will be deleted
Parameters
[in] moved The junction that will be eliminated
[in] target The junction that will be enlarged
[in] undoList The undo list with which to register changes
Definition at line 799 of file GNENet.cpp.
References deleteJunction(), GNEJunction::getAttribute(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), NBNode::getIncomingEdges(), GNEJunction::getNBNode(), NBNode::getOutgoingEdges(), myEdges, GNEUndoList::p_begin(), GNEUndoList::p_end(), remapEdge(), GNEJunction::setAttribute(), SUMO_ATTR_POSITION, SUMO_TAG_JUNCTION, and toString().
Referenced by GNEViewNet::mergeJunctions().
movePOI()
void ShapeContainer::movePOI (const std::string & id, const Position & pos) virtual inherited
Assigns a new position to the named PoI.
Parameters
[in] id The id of the PoI to move
[in] pos The PoI's new position
Reimplemented in GUIShapeContainer.
Definition at line 84 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), and ShapeContainer::myPOIs.
netHasGNECrossings()
bool GNENet::netHasGNECrossings () const
check if net has GNECrossings
Definition at line 1314 of file GNENet.cpp.
References myJunctions.
Referenced by GNEChange_Crossing::redo(), and GNEChange_Crossing::undo().
refreshElement()
void GNENet::refreshElement (GUIGlObject * o)
refreshes boundary information for o and update
Definition at line 1082 of file GNENet.cpp.
References SUMORTree::addAdditionalGLObject(), myGrid, SUMORTree::removeAdditionalGLObject(), and update().
Referenced by GNEEdge::addConnection(), computeAndUpdate(), GNEEdge::moveEntireShape(), GNEPOI::moveGeometry(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNECrossing::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEVaporizer::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEEdge::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEPOI::updateGeometry(), GNERouteProbe::updateGeometry(), GNEPOILane::updateGeometry(), GNEPoly::updateGeometry(), GNEVariableSpeedSign::updateGeometry(), GNEChargingStation::updateGeometry(), GNERerouter::updateGeometry(), and GNECalibrator::updateGeometry().
registerEdge()
GNEEdge * GNENet::registerEdge (GNEEdge * edge) private
registers an edge with GNENet containers
Definition at line 2183 of file GNENet.cpp.
References Boundary::add(), SUMORTree::addAdditionalGLObject(), GNEJunction::addIncomingGNEEdge(), GNEJunction::addOutgoingGNEEdge(), GNEEdge::getBoundary(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GUIGlObject::getMicrosimID(), GNEReferenceCounter::incRef(), myEdges, myGrid, GNEEdge::setResponsible(), and update().
Referenced by initJunctionsAndEdges(), and insertEdge().
registerJunction()
GNEJunction * GNENet::registerJunction (GNEJunction * junction) private
registers a junction with GNENet containers
Definition at line 2166 of file GNENet.cpp.
References Boundary::add(), SUMORTree::addAdditionalGLObject(), GNEJunction::getBoundary(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), NBNode::getPosition(), GNEReferenceCounter::incRef(), myGrid, myJunctions, myZBoundary, GNEJunction::setResponsible(), update(), Position::z(), and Z_INITIALIZED.
Referenced by initJunctionsAndEdges(), and insertJunction().
remapEdge()
void GNENet::remapEdge (GNEEdge * oldEdge, GNEJunction * from, GNEJunction * to, GNEUndoList * undoList, bool preserveShapeStart, bool preserveShapeEnd) private
Definition at line 822 of file GNENet.cpp.
References createEdge(), deleteCrossing(), deleteEdge(), GNEEdge::getAttribute(), NBEdge::getGeometry(), GNEEdge::getGNECrossings(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, and toString().
Referenced by joinSelectedJunctions(), and mergeJunctions().
removeExplicitTurnaround()
void GNENet::removeExplicitTurnaround (std::string id)
remove edge id from the list of explicit turnarounds
Definition at line 1634 of file GNENet.cpp.
References myExplicitTurnarounds.
Referenced by GNEEdge::removeConnection().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
removePOI()
bool ShapeContainer::removePOI (const std::string & id) virtual inherited
Removes a PoI from the container.
Parameters
[in] id The id of the PoI
Returns
Whether the poi could be removed
Reimplemented in GUIShapeContainer.
Definition at line 78 of file ShapeContainer.cpp.
References ShapeContainer::myPOIs, and NamedObjectCont< T >::remove().
Referenced by libsumo::POI::remove(), and GNEChange_Attribute::~GNEChange_Attribute().
removePolygon()
bool ShapeContainer::removePolygon (const std::string & id) virtual inherited
Removes a polygon from the container.
Parameters
[in] id The id of the polygon
Returns
Whether the polygon could be removed
Reimplemented in GUIShapeContainer.
Definition at line 72 of file ShapeContainer.cpp.
References ShapeContainer::myPolygons, and NamedObjectCont< T >::remove().
Referenced by libsumo::Polygon::remove(), and GNEChange_Attribute::~GNEChange_Attribute().
removePolygonForEditShapes()
void GNENet::removePolygonForEditShapes (GNEPoly * polygon)
remove Polygon for edit shapes
Definition at line 1928 of file GNENet.cpp.
References GNEAttributeCarrier::getGUIGLObject(), myGrid, myViewNet, and SUMORTree::removeAdditionalGLObject().
Referenced by GNEViewNet::stopEditCustomShape().
removeRestrictedLane()
bool GNENet::removeRestrictedLane (SUMOVehicleClass vclass, GNEEdge & edge, GNEUndoList * undoList)
remove restricted lane
Parameters
[in] vclass vehicle class to restrict
[in] edge the edge in which remove sidewalk
[in] undoList The undolist in which to mark changes
Definition at line 677 of file GNENet.cpp.
References deleteLane(), and GNEEdge::getLanes().
Referenced by GNEViewNet::removeRestrictedLane().
removeShape()
void GNENet::removeShape (GNEShape * shape) private
remove created shape (but NOT delete)
Definition at line 2252 of file GNENet.cpp.
References GNEShape::getAttribute(), GNEAttributeCarrier::getGUIGLObject(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myGrid, ShapeContainer::myPOIs, ShapeContainer::myPolygons, NamedObjectCont< T >::remove(), SUMORTree::removeAdditionalGLObject(), requiereSaveShapes(), retrieveLane(), SUMO_ATTR_LANE, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEChange_Shape::redo(), GNEChange_Lane::redo(), GNEChange_Shape::undo(), and GNEChange_Lane::undo().
removeSolitaryJunctions()
void GNENet::removeSolitaryJunctions (GNEUndoList * undoList)
removes junctions that have no edges
Definition at line 1500 of file GNENet.cpp.
References deleteJunction(), NBNode::getEdges(), GNEJunction::getNBNode(), myJunctions, GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_JUNCTION, and toString().
Referenced by GNEApplicationWindow::onCmdCleanJunctions().
renameEdge()
void GNENet::renameEdge (GNEEdge * edge, const std::string & newID)
updates the map and reserves new id
Definition at line 1584 of file GNENet.cpp.
References NBNetBuilder::getEdgeCont(), Named::getID(), GNEEdge::getLanes(), GNEEdge::getNBEdge(), myEdges, myNetBuilder, NBEdgeCont::rename(), and GNEEdge::setMicrosimID().
Referenced by GNEEdge::setAttribute().
renameJunction()
void GNENet::renameJunction (GNEJunction * junction, const std::string & newID)
updates the map and reserves new id
Definition at line 1619 of file GNENet.cpp.
References Named::getID(), GNEJunction::getNBNode(), NBNetBuilder::getNodeCont(), myJunctions, myNetBuilder, NBNodeCont::rename(), and GUIGlObject::setMicrosimID().
Referenced by GNEJunction::setAttribute().
replaceIncomingEdge()
void GNENet::replaceIncomingEdge (GNEEdge * which, GNEEdge * by, GNEUndoList * undoList)
replaces edge
Parameters
[in] which The edge to be replaced
[in] by The replacement edge
[in] undoList The undolist in which to mark changes
Definition at line 475 of file GNENet.cpp.
References GNENetElement::getAdditionalChilds(), GNENetElement::getAdditionalParents(), GNEEdge::getAttribute(), NBEdge::getConnections(), GUIGlObject::getGlID(), GNEJunction::getGNECrossings(), GNEEdge::getGNEJunctionDestiny(), GNEAttributeCarrier::getID(), NBEdge::getLaneID(), GNEEdge::getLanes(), GNEEdge::getNBEdge(), getTLLogicCont(), GLO_EDGE, GNEChange_Connection, GNEChange_Edge, gSelected, GUISelectedStorage::isSelected(), GNEUndoList::p_add(), GNEUndoList::p_begin(), GNEUndoList::p_end(), replaceInListAttribute(), SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_LANE, SUMO_ATTR_TO, SUMO_TAG_EDGE, toString(), and UNUSED_PARAMETER.
Referenced by replaceJunctionByGeometry().
replaceInListAttribute()
void GNENet::replaceInListAttribute (GNEAttributeCarrier * ac, SumoXMLAttr key, const std::string & which, const std::string & by, GNEUndoList * undoList) static private
Definition at line 2393 of file GNENet.cpp.
References GNEAttributeCarrier::getAttribute(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::setAttribute(), and toString().
Referenced by replaceIncomingEdge().
replaceJunctionByGeometry()
void GNENet::replaceJunctionByGeometry (GNEJunction * junction, GNEUndoList * undoList)
replace the selected junction by geometry node(s) and merge the edges
Definition at line 1517 of file GNENet.cpp.
References PositionVector::append(), NBNode::checkIsRemovable(), clearJunctionConnections(), deleteJunction(), GNEEdge::getAttribute(), NBEdge::getConnections(), NBNode::getEdgesToJoin(), NBEdge::getGeometry(), NBEdge::getInnerGeometry(), GNEEdge::getNBEdge(), GNEJunction::getNBNode(), NBNode::getPosition(), NBEdge::getToNode(), GNE_ATTR_SHAPE_END, GNEChange_Connection, NBEdge::hasDefaultGeometryEndpointAtNode(), myEdges, GNEUndoList::p_begin(), GNEUndoList::p_end(), PositionVector::push_back_noDoublePos(), replaceIncomingEdge(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, and toString().
Referenced by GNEViewNet::onCmdReplaceJunction().
requiereSaveAdditionals()
void GNENet::requiereSaveAdditionals ()
inform that additionals has to be saved
Definition at line 1736 of file GNENet.cpp.
References GNEApplicationWindow::enableSaveAdditionalsMenu(), GNEViewParent::getGNEAppWindows(), OptionsCont::getOptions(), GNEViewNet::getViewParent(), myAdditionalsSaved, myViewNet, and WRITE_WARNING.
Referenced by deleteAdditional(), insertAdditional(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Additional::redo(), GNEChange_Attribute::redo(), GNEChange_CalibratorItem::redo(), GNEChange_RerouterItem::redo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Additional::undo(), GNEChange_Attribute::undo(), GNEChange_CalibratorItem::undo(), GNEChange_RerouterItem::undo(), and updateAdditionalID().
requiereSaveShapes()
void GNENet::requiereSaveShapes ()
inform that shapes has to be saved
Definition at line 1982 of file GNENet.cpp.
References GNEApplicationWindow::enableSaveShapesMenu(), GNEViewParent::getGNEAppWindows(), OptionsCont::getOptions(), GNEViewNet::getViewParent(), myShapesSaved, myViewNet, and WRITE_WARNING.
Referenced by insertShape(), GNEChange_Attribute::redo(), removeShape(), and GNEChange_Attribute::undo().
requireRecompute()
void GNENet::requireRecompute ()
inform the net about the need for recomputation
Definition at line 1308 of file GNENet.cpp.
References myNeedRecompute.
Referenced by changeEdgeEndpoints(), createEdge(), deleteConnection(), deleteCrossing(), deleteEdge(), deleteLane(), duplicateLane(), GNEJunction::invalidateShape(), and GNEViewNet::onCmdToogleShowConnection().
reserveEdgeID()
void GNENet::reserveEdgeID (const std::string & id) private
reserve edge ID (To avoid duplicates)
Definition at line 2279 of file GNENet.cpp.
References IDSupplier::avoid(), and myEdgeIDSupplier.
Referenced by createEdge().
reserveJunctionID()
void GNENet::reserveJunctionID (const std::string & id) private
reserve junction ID (To avoid duplicates)
Definition at line 2285 of file GNENet.cpp.
References IDSupplier::avoid(), and myJunctionIDSupplier.
resetJunctionConnections()
void GNENet::resetJunctionConnections (GNEJunction * junction, GNEUndoList * undoList)
reset junction's connections
Definition at line 1573 of file GNENet.cpp.
References clearJunctionConnections(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and GNEJunction::setLogicValid().
Referenced by GNEViewNet::onCmdResetConnections().
reshapePolygon()
void ShapeContainer::reshapePolygon (const std::string & id, const PositionVector & shape) virtual inherited
Assigns a shape to the named polygon.
Parameters
[in] id The id of the polygon to reshape
[in] shape The polygon's new shape
Reimplemented in GUIShapeContainer.
Definition at line 93 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), ShapeContainer::myPolygons, and SUMOPolygon::setShape().
Referenced by libsumo::Polygon::setShape().
restrictLane()
bool GNENet::restrictLane (SUMOVehicleClass vclass, GNELane * lane, GNEUndoList * undoList)
transform lane to restricted lane
Parameters
[in] vclass vehicle class to restrict
[in] lane The lane to be transformed
[in] undoList The undolist in which to mark changes
Definition at line 635 of file GNENet.cpp.
References GNEEdge::getLanes(), GNEEdge::getNBEdge(), OptionsCont::getOptions(), GNELane::getParentEdge(), NBEdge::getPermissions(), getVehicleClassNames(), GNELane::setAttribute(), SUMO_ATTR_ALLOW, SUMO_ATTR_WIDTH, SVC_PEDESTRIAN, and toString().
Referenced by addSRestrictedLane(), and GNEViewNet::restrictLane().
retrieveAdditional()
GNEAdditional * GNENet::retrieveAdditional (const std::string & id, bool hardFail = true) const
Returns the named additional.
Parameters
[in] id The id of the additional to return.
[in] failHard Whether attempts to retrieve a nonexisting additional should result in an exception
Definition at line 1640 of file GNENet.cpp.
References myAdditionals.
Referenced by GNEAdditionalHandler::buildAdditional(), GNEAdditional::changeAdditionalParent(), GNEAdditionalHandler::parseAndBuildCalibratorFlow(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildCalibratorVehicleType(), GNEAdditionalHandler::parseAndBuildDetectorEntry(), GNEAdditionalHandler::parseAndBuildDetectorExit(), GNEAdditionalHandler::parseAndBuildRerouterClosingReroute(), GNEAdditionalHandler::parseAndBuildRerouterDestProbReroute(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEAdditionalHandler::parseAndBuildRerouterRouteProbReroute(), GNEAdditionalHandler::parseAndBuildVariableSpeedSignStep(), and GNEChange_Additional::~GNEChange_Additional().
retrieveAdditionals()
std::vector< GNEAdditional * > GNENet::retrieveAdditionals (bool onlySelected = false)
return all additionals
Parameters
[in] onlySelected Whether to return only selected additionals
Definition at line 1655 of file GNENet.cpp.
References GLO_ADDITIONAL, gSelected, GUISelectedStorage::isSelected(), and myAdditionals.
Referenced by GNEViewNet::deleteSelectedAdditionals().
retrieveAttributeCarrier()
GNEAttributeCarrier * GNENet::retrieveAttributeCarrier (const GUIGlID id, bool failHard = true)
get a single attribute carrier based on a GLID
Parameters
[in] ids the GL IDs for which to retrive the AC
[in] failHard Whether attempts to retrieve a nonexisting AttributeCarrier should result in an exception
Exceptions
InvalidArgument if GL ID doesn't have a associated Attribute Carrier
Definition at line 1100 of file GNENet.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, and GUIGlObjectStorage::unblockObject().
Referenced by GNESelectorFrame::getMatches(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onMouseMove(), and retrieveAttributeCarriers().
retrieveAttributeCarriers()
std::vector< GNEAttributeCarrier * > GNENet::retrieveAttributeCarriers (const std::set< GUIGlID > & ids, GUIGlObjectType type)
get the attribute carriers based on GlIDs
Parameters
[in] ids The set of ids for which to retrive the ACs
[in] type The GUI-type of the objects with the given ids.
Exceptions
InvalidArgument if any given id does not match the declared type
Definition at line 1123 of file GNENet.cpp.
References GNEAttributeCarrier::getGUIGLObject(), GUIGlObject::getType(), and retrieveAttributeCarrier().
Referenced by GNEViewNet::onLeftBtnPress().
retrieveCalibratorFlow()
GNECalibratorFlow * GNENet::retrieveCalibratorFlow (const std::string & id, bool hardFail = true) const
Returns the named calibrator flow.
Parameters
[in] id The id of the calibrator flow to return.
[in] failHard Whether attempts to retrieve a nonexisting calibrator flow should result in an exception
Definition at line 1832 of file GNENet.cpp.
References myCalibratorFlows.
Referenced by GNEAdditionalHandler::buildCalibratorFlow(), GNECalibratorFlow::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorFlow(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
retrieveCalibratorRoute()
GNECalibratorRoute * GNENet::retrieveCalibratorRoute (const std::string & id, bool hardFail = true) const
Returns the named calibrator route.
Parameters
[in] id The id of the calibrator route to return.
[in] failHard Whether attempts to retrieve a nonexisting calibrator route should result in an exception
Definition at line 1800 of file GNENet.cpp.
References myCalibratorRoutes.
Referenced by GNEAdditionalHandler::buildCalibratorRoute(), GNECalibratorRoute::isValid(), GNECalibratorFlow::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorFlow(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNECalibratorFlow::setAttribute(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
retrieveCalibratorVehicleType()
GNECalibratorVehicleType * GNENet::retrieveCalibratorVehicleType (const std::string & id, bool hardFail = true) const
Returns the named calibrator vehicle type.
Parameters
[in] id The id of the calibrator vehicle type to return.
[in] failHard Whether attempts to retrieve a nonexisting calibrator vehicle type should result in an exception
Definition at line 1816 of file GNENet.cpp.
References myCalibratorVehicleTypes.
Referenced by GNEAdditionalHandler::buildCalibratorVehicleType(), GNECalibratorVehicleType::isValid(), GNECalibratorFlow::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorFlow(), GNEAdditionalHandler::parseAndBuildCalibratorVehicleType(), GNECalibratorFlow::setAttribute(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
retrieveEdge() [1/2]
GNEEdge * GNENet::retrieveEdge (const std::string & id, bool failHard = true)
get edge by id
Parameters
[in] id The id of the desired edge
[in] failHard Whether attempts to retrieve a nonexisting edge should result in an exception
Exceptions
UnknownElement
Definition at line 902 of file GNENet.cpp.
References myEdges.
Referenced by GNEViewNet::addRestrictedLane(), GNEAdditionalHandler::buildAdditional(), GNEAdditional::changeEdge(), GNEAttributeCarrier::checkGNEEdgesValid(), createEdge(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), GNEEdge::getOppositeEdge(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), GNEConnectorFrame::initTargets(), GNEDestProbReroute::isValid(), GNEClosingReroute::isValid(), GNEVaporizer::isValid(), GNERouteProbe::isValid(), GNECalibrator::isValid(), GNEEdge::isValid(), GNEJunction::markAsModified(), GNEJunction::moveJunctionGeometry(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildRerouterClosingReroute(), GNEAdditionalHandler::parseAndBuildRerouterDestProbReroute(), GNEAdditionalHandler::parseAndBuildRouteProbe(), GNEAdditionalHandler::parseAndBuildVaporizer(), GNEAttributeCarrier::parseGNEEdges(), GNEViewNet::removeRestrictedLane(), GNEViewNet::restrictLane(), GNEEdge::retrieveGNEConnection(), retrieveLane(), GNEDestProbReroute::setAttribute(), GNEClosingReroute::setAttribute(), and GNEJunction::setLogicValid().
retrieveEdge() [2/2]
GNEEdge * GNENet::retrieveEdge (GNEJunction * from, GNEJunction * to, bool failHard = true)
get edge by from and to GNEJunction
Parameters
[in] id The id of the desired edge
[in] failHard Whether attempts to retrieve a nonexisting edge should result in an exception
Exceptions
UnknownElement
Definition at line 917 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), and myEdges.
retrieveEdges()
std::vector< GNEEdge * > GNENet::retrieveEdges (bool onlySelected = false)
return all edges
Parameters
[in] onlySelected Whether to return only selected edges
Definition at line 974 of file GNENet.cpp.
References GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), and myEdges.
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::addRestrictedLane(), GNEViewNet::begingMoveSelection(), GNEViewNet::deleteSelectedConnections(), GNEViewNet::deleteSelectedEdges(), GNELane::getPopUpMenu(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::removeRestrictedLane(), GNEAdditionalFrame::SelectorParentEdges::showList(), and GNEAdditionalFrame::SelectorParentEdges::updateUseSelectedEdges().
retrieveJunction()
GNEJunction * GNENet::retrieveJunction (const std::string & id, bool failHard = true)
get junction by id
Parameters
[in] id The id of the desired junction
[in] failHard Whether attempts to retrieve a nonexisting junction should result in an exception
Exceptions
UnknownElement
Definition at line 889 of file GNENet.cpp.
References myJunctions.
Referenced by changeEdgeEndpoints(), GNEJunction::invalidateTLS(), GNEJunction::isValid(), GNEEdge::isValid(), GNETLSEditorFrame::onCmdOK(), GNEConnection::setAttribute(), GNEJunction::setAttribute(), and GNEEdge::setAttribute().
retrieveJunctions()
std::vector< GNEJunction * > GNENet::retrieveJunctions (bool onlySelected = false)
return all junctions
Parameters
[in] onlySelected Whether to return only selected junctions
Definition at line 1033 of file GNENet.cpp.
References GLO_JUNCTION, gSelected, GUISelectedStorage::isSelected(), and myJunctions.
Referenced by GNEViewNet::begingMoveSelection(), GNEViewNet::buildColorRainbow(), GNEViewNet::deleteSelectedCrossings(), GNEViewNet::deleteSelectedJunctions(), joinSelectedJunctions(), GNEViewNet::onCmdClearConnections(), GNEViewNet::onCmdResetConnections(), and GNEConnectorFrame::onCmdSelectDeadStarts().
retrieveLane()
GNELane * GNENet::retrieveLane (const std::string & id, bool failHard = true, bool checkVolatileChange = false)
get lane by id
Parameters
[in] id The id of the desired lane
[in] failHard Whether attempts to retrieve a nonexisting lane should result in an exception
[in] checkVolatileChange Used by additionals after recomputing with volatile options.
Exceptions
UnknownElement
Definition at line 1000 of file GNENet.cpp.
References SUMOXMLDefinitions::getEdgeIDFromLane(), GNELane::getIndex(), GNEEdge::getLanes(), myEdgesAndNumberOfLanes, retrieveEdge(), SUMO_TAG_EDGE, SUMO_TAG_LANE, and toString().
Referenced by addPOI(), GNEPolygonFrame::addPOILane(), GNEAdditionalHandler::buildAdditional(), GNEAdditional::changeLane(), GNEAttributeCarrier::checkGNELanesValid(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), insertShape(), GNEClosingLaneReroute::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), GNECalibratorFlow::isValid(), GNEChargingStation::isValid(), GNEPOILane::isValid(), GNECalibrator::isValid(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEAdditionalHandler::parseAndBuildDetectorE1(), GNEAdditionalHandler::parseAndBuildDetectorE2(), GNEAdditionalHandler::parseAndBuildDetectorEntry(), GNEAdditionalHandler::parseAndBuildDetectorExit(), GNEAdditionalHandler::parseAndBuildRerouterClosingLaneReroute(), GNEAttributeCarrier::parseGNELanes(), removeShape(), GNEClosingLaneReroute::setAttribute(), and GNEPOILane::setAttribute().
retrieveLanes()
std::vector< GNELane * > GNENet::retrieveLanes (bool onlySelected = false)
return all lanes
Parameters
[in] onlySelected Whether to return only selected lanes
Definition at line 986 of file GNENet.cpp.
References GLO_LANE, gSelected, GUISelectedStorage::isSelected(), and myEdges.
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::addRestrictedLane(), GNEViewNet::buildColorRainbow(), GNEViewNet::deleteSelectedLanes(), GNELane::getPopUpMenu(), GNETLSEditorFrame::handleMultiChange(), GNEViewNet::onCmdDuplicateLane(), GNEViewNet::removeRestrictedLane(), GNEViewNet::restrictLane(), GNEAdditionalFrame::SelectorParentLanes::showList(), and GNEAdditionalFrame::SelectorParentLanes::updateUseSelectedLanes().
retrievePOI()
GNEPOI * GNENet::retrievePOI (const std::string & id, bool failHard = true) const
get POI by id
Parameters
[in] id The id of the desired POI
[in] failHard Whether attempts to retrieve a nonexisting POI should result in an exception
Exceptions
UnknownElement
Definition at line 948 of file GNENet.cpp.
References NamedObjectCont< T >::get(), and ShapeContainer::myPOIs.
Referenced by GNEPolygonFrame::addPOI(), GNEPOI::isValid(), and GNEPOILane::isValid().
retrievePOILane()
GNEPOILane * GNENet::retrievePOILane (const std::string & id, bool failHard = true) const
get POILane by id
Parameters
[in] id The id of the desired POILane
[in] failHard Whether attempts to retrieve a nonexisting POILane should result in an exception
Exceptions
UnknownElement
Definition at line 961 of file GNENet.cpp.
References NamedObjectCont< T >::get(), and ShapeContainer::myPOIs.
Referenced by GNEPolygonFrame::addPOILane().
retrievePolygon()
GNEPoly * GNENet::retrievePolygon (const std::string & id, bool failHard = true) const
get Polygon by id
Parameters
[in] id The id of the desired polygon
[in] failHard Whether attempts to retrieve a nonexisting polygon should result in an exception
Exceptions
UnknownElement
Definition at line 935 of file GNENet.cpp.
References NamedObjectCont< T >::get(), and ShapeContainer::myPolygons.
Referenced by GNEPolygonFrame::addPolygon(), and GNEPoly::isValid().
retrieveShapes()
std::vector< GNEShape * > GNENet::retrieveShapes (SumoXMLTag shapeTag = SUMO_TAG_NOTHING, bool onlySelected = false)
return all shapes
Parameters
[in] shapeTag Type of shape. SUMO_TAG_NOTHING returns all shapes
[in] onlySelected Whether to return only selected junctions
Definition at line 1045 of file GNENet.cpp.
References GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), ShapeContainer::getPOIs(), ShapeContainer::getPolygons(), GLO_POI, GLO_POLYGON, gSelected, GUISelectedStorage::isSelected(), SUMO_TAG_NOTHING, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEViewNet::deleteSelectedShapes().
reverseEdge()
void GNENet::reverseEdge (GNEEdge * edge, GNEUndoList * undoList)
reverse edge
Parameters
[in] edge The edge to be reversed
Definition at line 754 of file GNENet.cpp.
References createEdge(), deleteEdge(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEAttributeCarrier::getID(), NBEdge::getInnerGeometry(), GNEEdge::getNBEdge(), GNEUndoList::p_begin(), PositionVector::reverse(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, and toString().
Referenced by GNEViewNet::onCmdReverseEdge().
save()
void GNENet::save (OptionsCont & oc)
save the network
Parameters
[in] oc The OptionsCont which knows how and where to save
Definition at line 858 of file GNENet.cpp.
References computeAndUpdate(), myNetBuilder, and NWFrame::writeNetwork().
Referenced by GNEApplicationWindow::onCmdSaveNetwork().
saveAdditionals()
void GNENet::saveAdditionals (const std::string & filename)
save additional elements of the network
Parameters
[in] filename name of the file in wich save additionals
Definition at line 1746 of file GNENet.cpp.
References GNEStoppingPlace::areStoppingPlacesPositionsFixed(), OutputDevice::close(), OutputDevice::getDevice(), OptionsCont::getOptions(), GNEDetector::isDetectorPositionFixed(), myAdditionals, myAdditionalsSaved, myViewNet, OutputDevice::openTag(), and WRITE_WARNING.
Referenced by GNEApplicationWindow::onCmdComputeJunctionsVolatile(), and GNEApplicationWindow::onCmdSaveAdditionals().
saveJoined()
void GNENet::saveJoined (OptionsCont & oc)
save log of joined junctions (and nothing else)
Parameters
[in] oc The OptionsCont which knows how and where to save
Definition at line 875 of file GNENet.cpp.
References computeAndUpdate(), NBNetBuilder::getNodeCont(), myNetBuilder, and NWWriter_XML::writeJoinedJunctions().
Referenced by GNEApplicationWindow::onCmdSaveJoined().
savePlain()
void GNENet::savePlain (OptionsCont & oc)
save plain xml representation of the network (and nothing else)
Parameters
[in] oc The OptionsCont which knows how and where to save
Definition at line 867 of file GNENet.cpp.
References computeAndUpdate(), myNetBuilder, and NWWriter_XML::writeNetwork().
Referenced by GNEApplicationWindow::onCmdSaveAsPlainXML().
saveShapes()
void GNENet::saveShapes (const std::string & filename)
save shapes elements of the network
Parameters
[in] filename name of the file in wich save shapes
Definition at line 1991 of file GNENet.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), OptionsCont::getOptions(), ShapeContainer::myPOIs, ShapeContainer::myPolygons, myShapesSaved, OutputDevice::openTag(), and WRITE_WARNING.
Referenced by GNEApplicationWindow::onCmdComputeJunctionsVolatile(), and GNEApplicationWindow::onCmdSaveShapes().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setViewNet()
void GNENet::setViewNet (GNEViewNet * viewNet)
Set the viewNet to be notified of network changes.
Definition at line 883 of file GNENet.cpp.
References myViewNet.
splitEdge()
GNEJunction * GNENet::splitEdge (GNEEdge * edge, const Position & pos, GNEUndoList * undoList, GNEJunction * newJunction = 0)
split edge at position by inserting a new junction
Parameters
[in] edge The edge to be split
[in] pos The position on which to insert the new junction
Returns
The new junction
Definition at line 691 of file GNENet.cpp.
References createEdge(), createJunction(), deleteEdge(), NBEdge::getGeometry(), GNEEdge::getGNEJunctionSource(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEChange_Connection, PositionVector::nearest_offset_to_point2D(), GNEUndoList::p_begin(), GNEEdge::setAttribute(), PositionVector::splitAt(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, toString(), and GNEEdge::wasSplit().
Referenced by GNEViewNet::onCmdSplitEdge(), and splitEdgesBidi().
splitEdgesBidi()
void GNENet::splitEdgesBidi (const std::set< GNEEdge *> & edges, const Position & pos, GNEUndoList * undoList)
split all edges at position by inserting one new junction
Parameters
[in] edges The edges to be split
[in] pos The position on which to insert the new junction
Definition at line 743 of file GNENet.cpp.
References GNEUndoList::p_begin(), GNEUndoList::p_end(), splitEdge(), SUMO_TAG_EDGE, and toString().
Referenced by GNEViewNet::onCmdSplitEdgeBidi().
update()
void GNENet::update () private
notify myViewNet
Definition at line 2271 of file GNENet.cpp.
References myViewNet.
Referenced by changeEdgeEndpoints(), computeEverything(), deleteAdditional(), deleteSingleEdge(), deleteSingleJunction(), refreshElement(), registerEdge(), and registerJunction().
updateAdditionalID()
void GNENet::updateAdditionalID (const std::string & oldID, GNEAdditional * additional)
update additional ID in container
Note
this function is automatically called when user changes the ID of an additional
Definition at line 1721 of file GNENet.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myAdditionals, requiereSaveAdditionals(), and toString().
Referenced by GNEAdditional::changeAdditionalID().
Friends And Related Function Documentation
GNEAdditionalHandler
friend class GNEAdditionalHandler friend
declare friend class
Definition at line 94 of file GNENet.h.
GNEChange_Additional
friend class GNEChange_Additional friend
Definition at line 101 of file GNENet.h.
Referenced by deleteEdge(), and deleteLane().
GNEChange_CalibratorItem
friend class GNEChange_CalibratorItem friend
Definition at line 100 of file GNENet.h.
GNEChange_Connection
friend class GNEChange_Connection friend
Definition at line 98 of file GNENet.h.
Referenced by deleteConnection(), replaceIncomingEdge(), replaceJunctionByGeometry(), and splitEdge().
GNEChange_Edge
friend class GNEChange_Edge friend
Definition at line 96 of file GNENet.h.
Referenced by createEdge(), deleteEdge(), and replaceIncomingEdge().
GNEChange_Junction
friend class GNEChange_Junction friend
Definition at line 95 of file GNENet.h.
Referenced by createJunction(), and deleteJunction().
GNEChange_Lane
friend class GNEChange_Lane friend
Definition at line 97 of file GNENet.h.
Referenced by deleteLane(), and duplicateLane().
GNEChange_Shape
friend class GNEChange_Shape friend
Definition at line 99 of file GNENet.h.
Referenced by addPOI(), addPolygon(), deleteEdge(), deleteLane(), and deleteShape().
Field Documentation
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
myAdditionals
std::map<std::pair<std::string, SumoXMLTag>, GNEAdditional*> GNENet::myAdditionals protected
map with the name and pointer to additional elements of net
Definition at line 677 of file GNENet.h.
Referenced by computeAndUpdate(), deleteAdditional(), generateVaporizerID(), getAdditional(), getAdditionals(), getGlIDs(), getNumberOfAdditionals(), getRerouterInterval(), insertAdditional(), retrieveAdditional(), retrieveAdditionals(), saveAdditionals(), updateAdditionalID(), and ~GNENet().
myAdditionalsSaved
bool GNENet::myAdditionalsSaved protected
Flag to check if additionals has to be saved.
Definition at line 701 of file GNENet.h.
Referenced by requiereSaveAdditionals(), and saveAdditionals().
myCalibratorFlows
std::map<std::string, GNECalibratorFlow*> GNENet::myCalibratorFlows protected
map with the name and pointer to Calibrator Flows of net
Definition at line 686 of file GNENet.h.
Referenced by changeCalibratorFlowID(), deleteCalibratorFlow(), generateCalibratorFlowID(), insertCalibratorFlow(), retrieveCalibratorFlow(), and ~GNENet().
myCalibratorRoutes
std::map<std::string, GNECalibratorRoute*> GNENet::myCalibratorRoutes protected
map with the name and pointer to Calibrator Routes of net
Definition at line 680 of file GNENet.h.
Referenced by changeCalibratorRouteID(), deleteCalibratorRoute(), generateCalibratorRouteID(), insertCalibratorRoute(), retrieveCalibratorRoute(), and ~GNENet().
myCalibratorVehicleTypes
std::map<std::string, GNECalibratorVehicleType*> GNENet::myCalibratorVehicleTypes protected
map with the name and pointer to Calibrator Vehicle Types of net
Definition at line 683 of file GNENet.h.
Referenced by changeCalibratorVehicleTypeID(), deleteCalibratorVehicleType(), generateCalibratorVehicleTypeID(), insertCalibratorVehicleType(), retrieveCalibratorVehicleType(), and ~GNENet().
myEdgeIDSupplier
IDSupplier GNENet::myEdgeIDSupplier protected
Definition at line 690 of file GNENet.h.
Referenced by createEdge(), and reserveEdgeID().
myEdges
std::map<std::string, GNEEdge*> GNENet::myEdges protected
map with the name and pointer to edges of net
Definition at line 674 of file GNENet.h.
Referenced by computeAndUpdate(), computeEverything(), createEdge(), deleteJunction(), deleteSingleEdge(), getGlIDs(), initGNEConnections(), initJunctionsAndEdges(), joinSelectedJunctions(), mergeJunctions(), registerEdge(), renameEdge(), replaceJunctionByGeometry(), retrieveEdge(), retrieveEdges(), retrieveLanes(), and ~GNENet().
myEdgesAndNumberOfLanes
std::map<std::string, int> GNENet::myEdgesAndNumberOfLanes private
map with the Edges and their number of lanes
Definition at line 810 of file GNENet.h.
Referenced by computeEverything(), and retrieveLane().
myExplicitTurnarounds
std::set<std::string> GNENet::myExplicitTurnarounds protected
list of edge ids for which turn-arounds must be added explicitly
Definition at line 695 of file GNENet.h.
Referenced by addExplicitTurnaround(), computeAndUpdate(), and removeExplicitTurnaround().
myGrid
SUMORTree GNENet::myGrid protected
the rtree which contains all GUIGlObjects (so named for historical reasons)
Definition at line 662 of file GNENet.h.
Referenced by addPolygonForEditShapes(), computeAndUpdate(), deleteAdditional(), deleteSingleEdge(), deleteSingleJunction(), getBoundary(), getVisualisationSpeedUp(), initJunctionsAndEdges(), insertAdditional(), insertShape(), refreshElement(), registerEdge(), registerJunction(), removePolygonForEditShapes(), and removeShape().
myJunctionIDSupplier
IDSupplier GNENet::myJunctionIDSupplier protected
Definition at line 691 of file GNENet.h.
Referenced by createJunction(), and reserveJunctionID().
myJunctions
std::map<std::string, GNEJunction*> GNENet::myJunctions protected
map with the name and pointer to junctions of net
Definition at line 671 of file GNENet.h.
Referenced by checkJunctionPosition(), cleanInvalidCrossings(), computeAndUpdate(), createJunction(), deleteSingleJunction(), getGlIDs(), joinSelectedJunctions(), netHasGNECrossings(), registerJunction(), removeSolitaryJunctions(), renameJunction(), retrieveJunction(), retrieveJunctions(), and ~GNENet().
myNeedRecompute
bool GNENet::myNeedRecompute protected
whether the net needs recomputation
Definition at line 698 of file GNENet.h.
Referenced by computeAndUpdate(), computeEverything(), and requireRecompute().
myNetBuilder
NBNetBuilder* GNENet::myNetBuilder protected
The internal netbuilder.
Definition at line 668 of file GNENet.h.
Referenced by computeAndUpdate(), deleteSingleEdge(), deleteSingleJunction(), getNetBuilder(), getTLLogicCont(), initJunctionsAndEdges(), insertEdge(), insertJunction(), joinSelectedJunctions(), renameEdge(), renameJunction(), save(), saveJoined(), savePlain(), and ~GNENet().
myPOIs
POIs ShapeContainer::myPOIs protected inherited
stored POIs
Definition at line 144 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), GUIShapeContainer::addPOI(), addPOI(), changeShapeID(), computeAndUpdate(), generateShapeID(), getGlIDs(), getNumberOfShapes(), ShapeContainer::getPOIs(), insertShape(), ShapeContainer::movePOI(), GUIShapeContainer::movePOI(), ShapeContainer::removePOI(), GUIShapeContainer::removePOI(), removeShape(), retrievePOI(), retrievePOILane(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and PCPolyContainer::~PCPolyContainer().
myPolygons
Polygons ShapeContainer::myPolygons protected inherited
stored Polygons
Definition at line 141 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), GUIShapeContainer::addPolygon(), addPolygon(), changeShapeID(), computeAndUpdate(), generateShapeID(), getGlIDs(), getNumberOfShapes(), ShapeContainer::getPolygons(), insertShape(), ShapeContainer::removePolygon(), GUIShapeContainer::removePolygon(), removeShape(), ShapeContainer::reshapePolygon(), GUIShapeContainer::reshapePolygon(), retrievePolygon(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and PCPolyContainer::~PCPolyContainer().
myShapesSaved
bool GNENet::myShapesSaved protected
Flag to check if shapes hast o be saved.
Definition at line 704 of file GNENet.h.
Referenced by requiereSaveShapes(), and saveShapes().
myViewNet
GNEViewNet* GNENet::myViewNet protected
The viewNet to be notofied of about changes.
Definition at line 665 of file GNENet.h.
Referenced by addPOI(), addPolygon(), addPolygonForEditShapes(), computeAndUpdate(), computeEverything(), deleteConnection(), deleteShape(), getApp(), getViewNet(), removePolygonForEditShapes(), requiereSaveAdditionals(), requiereSaveShapes(), saveAdditionals(), setViewNet(), and update().
myZBoundary
Boundary GNENet::myZBoundary private
the z boundary (stored in the x-coordinate), values of 0 are ignored
Definition at line 804 of file GNENet.h.
Referenced by getZBoundary(), and registerJunction().
selectedAdditionalColor
const RGBColor GNENet::selectedAdditionalColor static
color of selected additionals
Definition at line 116 of file GNENet.h.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNERouteProbe::drawGL(), GNEChargingStation::drawGL(), and GNECalibrator::drawGL().
selectedConnectionColor
const RGBColor GNENet::selectedConnectionColor static
color of selected connection
Definition at line 113 of file GNENet.h.
Referenced by GNEConnection::drawGL().
selectedLaneColor
const RGBColor GNENet::selectedLaneColor static
color of selected lane
Definition at line 110 of file GNENet.h.
Referenced by GNEPoly::drawGL(), and GNELane::setLaneColor().
selectionColor
const RGBColor GNENet::selectionColor static
Definition at line 107 of file GNENet.h.
Referenced by GNEViewNet::doPaintGL(), GNEDetectorE1::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNERouteProbe::drawGL(), GNEChargingStation::drawGL(), GNEPoly::drawGL(), GNEEdge::drawGL(), GNECalibrator::drawGL(), GNELane::drawMarkings(), GNEJunction::setColor(), and GNELane::setLaneColor().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
Z_INITIALIZED
const double GNENet::Z_INITIALIZED = 1 static private
marker for whether the z-boundary is initialized
Definition at line 807 of file GNENet.h.
Referenced by registerJunction().
The documentation for this class was generated from the following files:
GNENet.h
GNENet.cpp