SUMO - Simulation of Urban MObility: MSBaseVehicle Class Reference
MSBaseVehicle Class Reference abstract
The base class for microscopic and mesoscopic vehicles.
#include <MSBaseVehicle.h>
Public Types
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
virtual void activateReminders (const MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
"Activates" all current move reminder
virtual void addContainer (MSTransportable *container)
Adds a container to this vehicle.
virtual void addPerson (MSTransportable *person)
Adds a person to this vehicle.
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
virtual bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0, bool collision=false, ConstMSEdgeVector::const_iterator *searchStart=0)=0
Adds a stop.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
void createDevice (const std::string &deviceName)
create device of the given type
virtual double getAcceleration () const
Returns the vehicle's acceleration.
virtual SUMOTime getAccumulatedWaitingTime () const =0
virtual double getAngle () const =0
Get the vehicle's angle.
virtual double getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
virtual double getBackPositionOnLane (const MSLane *lane) const =0
Get the vehicle's back position along the given lane.
double getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
SUMOTime getDepartDelay () const
Returns the depart delay.
double getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
std::string getDeviceParameter (const std::string &deviceName, const std::string &key) const
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
const std::string & getID () const
Returns the name of the vehicle.
double getImpatience () const
Returns this vehicles impatience.
virtual MSLane * getLane () const =0
Returns the lane the vehicle is on.
virtual double getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
double getLength () const
Returns the vehicle's length.
double getMaxSpeed () const
Returns the maximum speed.
virtual MSParkingArea * getNextParkingArea ()=0
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
virtual Position getPosition (const double offset=0) const =0
Return current position (x/y, cartesian)
virtual double getPositionOnLane () const =0
Get the vehicle's position along the lane.
double getPreviousSpeed () const
Returns the vehicle's previous speed.
virtual const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
const MSRoute & getRoute () const
Returns the current route.
MSVehicleType & getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
virtual double getSlope () const
Returns the slope of the road at vehicle's position.
virtual double getSpeed () const =0
Returns the vehicle's current speed.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
virtual SUMOTime getWaitingTime () const =0
double getWidth () const
Returns the vehicle's width.
virtual bool hasArrived () const
Returns whether this vehicle has already arived (by default this is true if the vehicle has reached its final edge)
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasDevice (const std::string &deviceName) const
check whether the vehicle is equiped with a device of the given type
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
virtual bool isFrontOnLane (const MSLane *) const
Returns the information whether the front of the vehhicle is on the given lane.
virtual bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
virtual bool isParking () const =0
Returns the information whether the vehicle is parked.
virtual bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
virtual bool isSelected () const
whether this vehicle is selected in the GUI
virtual bool isStopped () const =0
Returns whether the vehicle is at a stop.
virtual bool isStoppedInRange (double pos) const =0
Returns whether the vehicle is stoped in range of the given position.
virtual bool isStoppedTriggered () const =0
Returns whether the vehicle is at a stop and waiting for a person or container to continue.
MSBaseVehicle (SUMOVehicleParameter *pars, const MSRoute *route, MSVehicleType *type, const double speedFactor)
Constructor.
void onDepart ()
Called when the vehicle is inserted into the network.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
virtual bool replaceParkingArea (MSParkingArea *parkingArea, std::string &errorMsg)=0
Replaces a stop.
virtual bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0, bool addStops=true, bool removeStops=true)=0
Replaces the current route by the given one.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false, bool removeStops=true)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
virtual void setArrivalPos (double arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setChosenSpeedFactor (const double factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setDeviceParameter (const std::string &deviceName, const std::string &key, const std::string &value)
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
virtual ~MSBaseVehicle ()
Destructor.
state io
virtual void saveState (OutputDevice &out)
Saves the (common) state of a vehicle.
state io
virtual void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)=0
Loads the state of this vehicle from the given description.
Protected Member Functions
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
virtual const ConstMSEdgeVector getStopEdges () const =0
Returns the list of still pending stop edges.
Protected Attributes
int myArrivalLane
The destination lane where the vehicle stops.
double myArrivalPos
The position on the destination lane where the vehicle stops.
double myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
double myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This vehicle's parameter.
const MSRoute * myRoute
This vehicle's route.
MSVehicleType * myType
This vehicle's type.
Static Protected Attributes
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Private Member Functions
MSBaseVehicle & operator= (const MSBaseVehicle &s)
invalidated assignment operator
Friends
class GUIBaseVehicle
Move reminder structures
typedef std::vector< std::pair< MSMoveReminder *, double > > MoveReminderCont
Definition of a move reminder container.
MoveReminderCont myMoveReminders
Currently relevant move reminders.
Detailed Description
The base class for microscopic and mesoscopic vehicles.
Definition at line 55 of file MSBaseVehicle.h.
Member Typedef Documentation
ComparatorIdLess
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 79 of file SUMOVehicle.h.
MoveReminderCont
typedef std::vector< std::pair<MSMoveReminder*, double> > MSBaseVehicle::MoveReminderCont protected
Definition of a move reminder container.
Definition at line 468 of file MSBaseVehicle.h.
Constructor & Destructor Documentation
MSBaseVehicle()
MSBaseVehicle::MSBaseVehicle (SUMOVehicleParameter * pars, const MSRoute * route, MSVehicleType * type, const double speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 69 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSDevice::buildVehicleDevices(), calculateArrivalParams(), MSGlobals::gCheckRoutes, MSRoute::getLastEdge(), hasValidRoute(), SUMOVehicleParameter::id, MSEdge::isTazConnector(), myDevices, myMoveReminders, myRoute, SUMOVehicleParameter::parametersSet, VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::wasSet().
~MSBaseVehicle()
MSBaseVehicle::~MSBaseVehicle () virtual
Destructor.
Definition at line 108 of file MSBaseVehicle.cpp.
References MSRoute::checkDist(), myDevices, myParameter, myRoute, MSRoute::release(), SUMOVehicleParameter::repetitionNumber, and SUMOVehicleParameter::routeid.
Member Function Documentation
activateReminders()
void MSBaseVehicle::activateReminders (const MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
[in] enteredLane The lane, which is entered (if applicable)
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented in MSVehicle.
Definition at line 376 of file MSBaseVehicle.cpp.
References myMoveReminders.
Referenced by getDevices(), MESegment::receive(), and MELoop::teleportVehicle().
addContainer()
void MSBaseVehicle::addContainer (MSTransportable * container) virtual
Adds a container to this vehicle.
The default implementation does nothing since containers are not supported by default
Parameters
[in] container The container to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 316 of file MSBaseVehicle.cpp.
References getID(), and MSTransportable::getID().
Referenced by getDevices().
addPerson()
void MSBaseVehicle::addPerson (MSTransportable * person) virtual
Adds a person to this vehicle.
The default implementation does nothing since persons are not supported by default
Parameters
[in] person The person to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 311 of file MSBaseVehicle.cpp.
References getID(), and MSTransportable::getID().
Referenced by getDevices().
addReminder()
void MSBaseVehicle::addReminder (MSMoveReminder * rem)
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 349 of file MSBaseVehicle.cpp.
References myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MESegment::addReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), getDevices(), and MSVehicle::processNextStop().
addStop()
virtual bool SUMOVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0, bool collision = false, ConstMSEdgeVector::const_iterator * searchStart = 0) pure virtual inherited
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implemented in MSVehicle, and MEVehicle.
Referenced by addStops(), and SUMOVehicle::~SUMOVehicle().
addStops()
void MSBaseVehicle::addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 473 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), SUMOVehicleParameter::depart, MSRoute::getStops(), myParameter, myRoute, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::stops, and WRITE_WARNING.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MEVehicle::getBlockTimeSeconds(), MSVehicle::replaceRoute(), and setChosenSpeedFactor().
calculateArrivalParams()
void MSBaseVehicle::calculateArrivalParams () protected
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 398 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MSEdge::isTazConnector(), MAX2(), MIN2(), myArrivalLane, myArrivalPos, myParameter, myRoute, myType, RandHelper::rand(), toString(), and WRITE_WARNING.
Referenced by isSelected(), MSBaseVehicle(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), and reroute().
createDevice()
void MSBaseVehicle::createDevice (const std::string & deviceName)
create device of the given type
Definition at line 508 of file MSBaseVehicle.cpp.
References MSDevice_Routing::buildVehicleDevices(), getDevice(), hasDeparted(), hasDevice(), myDevices, myParameter, MSMoveReminder::NOTIFICATION_DEPARTED, and MSDevice_Routing::notifyEnter().
Referenced by libsumo::Vehicle::setParameter().
getAcceleration()
double MSBaseVehicle::getAcceleration () const virtual
Returns the vehicle's acceleration.
This default implementation returns always 0.
Returns
The acceleration
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 280 of file MSBaseVehicle.cpp.
Referenced by getCurrentRouteEdge().
getAccumulatedWaitingTime()
virtual SUMOTime SUMOVehicle::getAccumulatedWaitingTime () const pure virtual inherited
Implemented in MSVehicle, and MEVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), and SUMOVehicle::~SUMOVehicle().
getAngle()
virtual double SUMOVehicle::getAngle () const pure virtual inherited
Get the vehicle's angle.
Returns
The angle of the vehicle (in degree)
Implemented in MSVehicle, GUIMEVehicle, GUIVehicle, and MEVehicle.
Referenced by MSDevice_Battery::notifyMove(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::writeVehicles(), and SUMOVehicle::~SUMOVehicle().
getArrivalPos()
virtual double MSBaseVehicle::getArrivalPos () const inline virtual
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 269 of file MSBaseVehicle.h.
References myArrivalPos.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
getBackPositionOnLane()
virtual double SUMOVehicle::getBackPositionOnLane (const MSLane * lane) const pure virtual inherited
Get the vehicle's back position along the given lane.
Returns
The position of the vehicle (in m from the given lane's begin)
Implemented in MSVehicle, and MEVehicle.
Referenced by MSInductLoop::notifyEnter(), and SUMOVehicle::~SUMOVehicle().
getChosenSpeedFactor()
double MSBaseVehicle::getChosenSpeedFactor () const inline virtual
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 377 of file MSBaseVehicle.h.
References myChosenSpeedFactor.
Referenced by GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), and libsumo::Vehicle::getSpeedFactor().
getCurrentRouteEdge()
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 192 of file MSBaseVehicle.h.
References getAcceleration(), getSlope(), myCurrEdge, onDepart(), replaceRouteEdges(), and reroute().
Referenced by MSDevice_SSM::findSurroundingVehicles(), libsumo::Vehicle::getDistance(), and libsumo::Vehicle::moveToXY().
getDepartDelay()
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 253 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, getDeparture(), and getParameter().
Referenced by GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIMEVehicle::getParameterWindow(), and GUIVehicle::getParameterWindow().
getDepartPos()
double MSBaseVehicle::getDepartPos () const inline virtual
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 261 of file MSBaseVehicle.h.
References myDepartPos.
Referenced by libsumo::Vehicle::getDistance().
getDeparture()
SUMOTime MSBaseVehicle::getDeparture () const inline virtual
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 248 of file MSBaseVehicle.h.
References myDeparture.
Referenced by getDepartDelay(), and MSVehicle::Influencer::postProcessRemoteControl().
getDevice()
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 447 of file MSBaseVehicle.cpp.
References myDevices.
Referenced by createDevice(), GUIBaseVehicle::drawOnPos(), MSVehicle::resumeFromStopping(), setChosenSpeedFactor(), and MSBatteryExport::write().
getDeviceParameter()
std::string MSBaseVehicle::getDeviceParameter (const std::string & deviceName, const std::string & key) const
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 527 of file MSBaseVehicle.cpp.
References myDevices.
Referenced by libsumo::Vehicle::getParameter().
getDevices()
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 302 of file MSBaseVehicle.h.
References activateReminders(), addContainer(), addPerson(), addReminder(), hasValidRoute(), myDevices, and removeReminder().
getEdge()
const MSEdge * MSBaseVehicle::getEdge () const virtual
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 149 of file MSBaseVehicle.cpp.
References myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), libsumo::Vehicle::getDrivingDistance2D(), MSVehicle::getLatOffset(), GUIMEVehicle::getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), getVClass(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MELoop::teleportVehicle().
getID()
const std::string & MSBaseVehicle::getID () const virtual
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 121 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and myParameter.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChangerSublane::abortLCManeuver(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), addContainer(), MSPModel_Striping::addCrossingVehs(), MSLCM_SL2015::addLCSpeedAdvice(), addPerson(), MSVehicle::addTraciStopAtStoppingPlace(), calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), libsumo::Vehicle::changeTarget(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSVehicle::computeAngle(), MSLCM_SL2015::computeSpeedLat(), MSDevice_SSM::computeSSMs(), MSLaneChanger::continueChange(), MSLaneChangerSublane::continueChangeSublane(), MSLCM_SL2015::decideDirection(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSDevice_SSM::Encounter::Encounter(), MSCalibrator::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLaneChanger::findCandidate(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSAbstractLaneChangeModel::getShadowLane(), getSingularType(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSVehicle::ignoreRed(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::lateralDistanceToLane(), MSVehicle::leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSVehicle::onRemovalFromNet(), MSLaneChangerSublane::outputLCStarted(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLCM_SL2015::prepareStep(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::removePassedDriveItems(), replaceRouteEdges(), reroute(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), libsumo::Vehicle::resume(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), saveState(), MSCalibrator::scheduleRemoval(), GUIVehicle::selectBlockingFoes(), MSVehicle::setAngle(), MSAbstractLaneChangeModel::setManeuverDist(), MSLane::setManeuverReservation(), MSLCM_SL2015::setOwnState(), MSLane::setPartialOccupation(), libsumo::Helper::setRemoteControlled(), libsumo::Vehicle::setRoute(), libsumo::Vehicle::setRouteID(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSVehicle::updateBestLanes(), MSVehicle::updateDriveItems(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicle::updateState(), MSAbstractLaneChangeModel::updateTargetLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), and MSXMLRawOut::writeVehicle().
getImpatience()
double MSBaseVehicle::getImpatience () const virtual
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 440 of file MSBaseVehicle.cpp.
References getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToImpatience, MAX2(), and MIN2().
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), getNumberReroutes(), GUIVehicle::getParameterWindow(), MSLCM_LC2013::informFollower(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::processLinkAproaches(), and GUIVehicle::selectBlockingFoes().
getLane()
virtual MSLane* SUMOVehicle::getLane () const pure virtual inherited
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implemented in MSVehicle, and MEVehicle.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), GUIBaseVehicle::drawOnPos(), MSTransportable::Stage_Driving::getEdge(), libsumo::Vehicle::isOnInit(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_SSM::notifyLeave(), MSDevice_Battery::notifyMove(), MSDevice_Bluelight::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and SUMOVehicle::~SUMOVehicle().
getLateralPositionOnLane()
virtual double MSBaseVehicle::getLateralPositionOnLane () const inline virtual
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 175 of file MSBaseVehicle.h.
getLength()
double MSBaseVehicle::getLength () const inline
Returns the vehicle's length.
Returns
vehicle's length
Definition at line 361 of file MSBaseVehicle.h.
References MSVehicleType::getLength(), and myType.
Referenced by MSVehicle::addStop(), MSDevice_SSM::checkConflictEntryAndExit(), MSDevice_SSM::classifyEncounter(), MSDevice_SSM::determineConflictPoint(), MSDevice_SSM::determineTTCandDRAC(), MSVehicle::enterLaneAtInsertion(), MSDevice_SSM::findSurroundingVehicles(), MSLink::getLeaderInfo(), MSDevice_SSM::getUpstreamVehicles(), MSVehicle::updateFurtherLanes(), MSDevice_SSM::updatePassedEncounter(), and MSVehicle::validatePosition().
getMaxSpeed()
double MSBaseVehicle::getMaxSpeed () const virtual
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), getVClass(), MSVehicle::Influencer::implicitDeltaPosRemote(), and MSVehicle::Influencer::implicitSpeedRemote().
getNextParkingArea()
virtual MSParkingArea* SUMOVehicle::getNextParkingArea () pure virtual inherited
returns the next imminent stop in the stop queue
Returns
the upcoming stop
Implemented in MSVehicle, and MEVehicle.
Referenced by MSTriggeredRerouter::rerouteParkingArea(), and SUMOVehicle::~SUMOVehicle().
getNumberReroutes()
int MSBaseVehicle::getNumberReroutes () const inline virtual
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 291 of file MSBaseVehicle.h.
References getImpatience(), and myNumberReroutes.
Referenced by GUIBaseVehicle::drawGLAdditional(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), and replaceRouteEdges().
getParameter()
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 127 of file MSBaseVehicle.cpp.
References myParameter.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), getDepartDelay(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getDepartSpeed(), libsumo::Vehicle::getLine(), libsumo::Vehicle::getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), libsumo::Vehicle::getVia(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setColor(), GUIBaseVehicle::setFunctionalColor(), libsumo::Vehicle::setLine(), libsumo::Vehicle::setParameter(), and METriggeredCalibrator::tryEmit().
getPosition()
virtual Position SUMOVehicle::getPosition (const double offset = 0) const pure virtual inherited
Return current position (x/y, cartesian)
If the vehicle is not in the net, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See also
myLane
Implemented in MSVehicle, MEVehicle, GUIMEVehicle, and GUIVehicle.
Referenced by GUIBaseVehicle::drawOnPos(), MSVTypeProbe::execute(), MSTransportable::Stage_Driving::getPosition(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Bluelight::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::writeVehicles(), and SUMOVehicle::~SUMOVehicle().
getPositionOnLane()
virtual double SUMOVehicle::getPositionOnLane () const pure virtual inherited
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implemented in MSVehicle, and MEVehicle.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSVTypeProbe::execute(), MSTransportable::Stage_Driving::getEdgePos(), MSE2Collector::makeVehicleInfo(), MSDevice_Vehroutes::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSInductLoop::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Battery::notifyMove(), onDepart(), MSTransportable::Stage_Driving::setArrived(), MSTransportable::Stage_Driving::setVehicle(), MSStopOut::stopEnded(), MSEmissionExport::write(), MSFCDExport::write(), MSXMLRawOut::writeVehicle(), MSFullExport::writeVehicles(), and SUMOVehicle::~SUMOVehicle().
getPreviousSpeed()
double MSBaseVehicle::getPreviousSpeed () const virtual
Returns the vehicle's previous speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 64 of file MSBaseVehicle.cpp.
getRerouteOrigin()
virtual const MSEdge* MSBaseVehicle::getRerouteOrigin () const inline virtual
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge
Returns
The rerouting start point
Reimplemented in MSVehicle.
Definition at line 184 of file MSBaseVehicle.h.
References myCurrEdge.
Referenced by replaceRouteEdges(), and reroute().
getRoute()
const MSRoute& MSBaseVehicle::getRoute () const inline virtual
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 107 of file MSBaseVehicle.h.
References myRoute.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), libsumo::Vehicle::getDistance(), libsumo::Vehicle::getDrivingDistance(), libsumo::Vehicle::getDrivingDistance2D(), libsumo::Vehicle::getEdges(), libsumo::Vehicle::getRouteID(), MSLane::isInsertionSuccess(), libsumo::Vehicle::moveToXY(), MSVehicle::Influencer::postProcessRemoteControl(), and GUIBaseVehicle::setFunctionalColor().
getSingularType()
MSVehicleType & MSBaseVehicle::getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
If the currently used vehicle type is already marked as being used by this vehicle only, no new type is created.
Returns
The new modifiable vehicle type
See also
MSBaseVehicle::myType
Definition at line 559 of file MSBaseVehicle.cpp.
References MSVehicleType::buildSingularType(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), getID(), MSVehicleType::getID(), MSNet::getInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSVehicleType::isVehicleSpecific(), myType, OutputDevice::openTag(), replaceVehicleType(), STEPS2TIME, SUMO_ATTR_ID, SUMO_ATTR_TIME, toString(), and OutputDevice::writeAttr().
Referenced by TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setActionStepLength(), setChosenSpeedFactor(), libsumo::Vehicle::setMaxSpeed(), and libsumo::Vehicle::setShapeClass().
getSlope()
double MSBaseVehicle::getSlope () const virtual
Returns the slope of the road at vehicle's position.
This default implementation returns always 0.
Returns
The slope
Implements SUMOVehicle.
Reimplemented in MSVehicle, and MEVehicle.
Definition at line 286 of file MSBaseVehicle.cpp.
Referenced by getCurrentRouteEdge().
getSpeed()
virtual double SUMOVehicle::getSpeed () const pure virtual inherited
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implemented in MSVehicle, and MEVehicle.
Referenced by MSChargingStation::addChargeValueForOutput(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSInductLoop::collectVehiclesOnDet(), MSE3Collector::detectorUpdate(), MSE3Collector::enter(), MSVTypeProbe::execute(), MSNet::getHaltingVehicleNumber(), MSTransportable::Stage_Driving::getSpeed(), MSNet::getVehicleMeanSpeeds(), MSE3Collector::leave(), MSDevice_Vehroutes::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSInstantInductLoop::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Battery::notifyMove(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::writeVehicle(), MSXMLRawOut::writeVehicle(), MSFullExport::writeVehicles(), and SUMOVehicle::~SUMOVehicle().
getStopEdges()
virtual const ConstMSEdgeVector MSBaseVehicle::getStopEdges () const protected pure virtual
Returns the list of still pending stop edges.
Implemented in MSVehicle, and MEVehicle.
Referenced by isSelected(), and reroute().
getVClass()
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.h.
References getEdge(), getMaxSpeed(), MSVehicleType::getParameter(), myType, succEdge(), and SUMOVTypeParameter::vehicleClass.
Referenced by GUIVehicle::drawRouteHelper(), MSPedestrianPushButton::isActiveForEdge(), and reroute().
getVehicleType()
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 115 of file MSBaseVehicle.h.
References myType.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeaders(), MSPModel_Striping::addCrossingVehs(), MSVehicle::addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MSLCM_SL2015::computeSpeedLat(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSDevice_SSM::estimateConflictTimes(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), getImpatience(), MSVehicle::getLateralOverlap(), MSLane::getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), GUIVehicle::getLeftSideOnEdge(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), MSVehicle::getTimeGapOnLane(), MESegment::getTimeHeadway(), libsumo::Vehicle::getTypeID(), libsumo::Vehicle::getVehicleType(), GUIBaseVehicle::getVType(), MSLCM_SL2015::getWidth(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MESegment::hasSpaceFor(), MSVehicle::ignoreRed(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::keepClear(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), MSCFModel_Krauss::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSVehicle::overlap(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MESegment::receive(), MSLaneChanger::ChangeElem::registerHop(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), saveState(), GUIVehicle::selectBlockingFoes(), MSVehicleType::setActionStepLength(), MSAbstractLaneChangeModel::setFollowerGaps(), GUIBaseVehicle::setFunctionalColor(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSVehicle::setTentativeLaneAndPosition(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
getWaitingTime()
virtual SUMOTime SUMOVehicle::getWaitingTime () const pure virtual inherited
Implemented in MSVehicle, and MEVehicle.
Referenced by getImpatience(), MSTriggeredRerouter::notifyEnter(), MSDevice_Tripinfo::notifyMoveInternal(), and SUMOVehicle::~SUMOVehicle().
getWidth()
double MSBaseVehicle::getWidth () const inline
Returns the vehicle's width.
Returns
vehicle's width
Definition at line 369 of file MSBaseVehicle.h.
References MSVehicleType::getWidth(), and myType.
Referenced by MSDevice_SSM::classifyEncounter(), MSAbstractLaneChangeModel::determineTargetLane(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), MSVehicle::getLateralOverlap(), MSVehicle::lateralDistanceToLane(), MSVehicle::planMoveInternal(), MSLaneChangerSublane::startChangeSublane(), and MSDevice_SSM::updatePassedEncounter().
hasArrived()
bool MSBaseVehicle::hasArrived () const virtual
Returns whether this vehicle has already arived (by default this is true if the vehicle has reached its final edge)
Implements SUMOVehicle.
Reimplemented in MSVehicle, and MEVehicle.
Definition at line 306 of file MSBaseVehicle.cpp.
References succEdge().
Referenced by setArrivalPos().
hasDeparted()
bool MSBaseVehicle::hasDeparted () const virtual
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 300 of file MSBaseVehicle.cpp.
References myDeparture, and NOT_YET_DEPARTED.
Referenced by MSVehicle::addStop(), createDevice(), MSLane::forceVehicleInsertion(), libsumo::Vehicle::getRouteIndex(), MEVehicle::loadState(), MSVehicle::loadState(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), saveState(), and setArrivalPos().
hasDevice()
bool MSBaseVehicle::hasDevice (const std::string & deviceName) const
check whether the vehicle is equiped with a device of the given type
Definition at line 497 of file MSBaseVehicle.cpp.
References myDevices.
Referenced by createDevice(), and libsumo::Vehicle::getParameter().
hasValidRoute()
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 321 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), myCurrEdge, myRoute, and myType.
Referenced by getDevices(), MESegment::initialise(), libsumo::Vehicle::isRouteValid(), MSBaseVehicle(), replaceRouteEdges(), and libsumo::Vehicle::setRouteID().
isFrontOnLane()
virtual bool MSBaseVehicle::isFrontOnLane (const MSLane *) const inline virtual
Returns the information whether the front of the vehhicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 167 of file MSBaseVehicle.h.
isOnRoad()
virtual bool MSBaseVehicle::isOnRoad () const inline virtual
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Implements SUMOVehicle.
Reimplemented in MSVehicle, and MEVehicle.
Definition at line 152 of file MSBaseVehicle.h.
Referenced by GUIBaseVehicle::drawGLAdditional(), and MSXMLRawOut::writeVehicle().
isParking()
virtual bool SUMOVehicle::isParking () const pure virtual inherited
Returns the information whether the vehicle is parked.
Returns
Whether the vehicle is parked
Implemented in MSVehicle, and MEVehicle.
Referenced by GUIVehicleControl::insertVehicleIDs(), MSFCDExport::write(), and SUMOVehicle::~SUMOVehicle().
isRemoteControlled()
virtual bool MSBaseVehicle::isRemoteControlled () const inline virtual
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 160 of file MSBaseVehicle.h.
isSelected()
virtual bool MSBaseVehicle::isSelected () const inline virtual
whether this vehicle is selected in the GUI
Implements SUMOVehicle.
Reimplemented in GUIVehicle.
Definition at line 430 of file MSBaseVehicle.h.
References calculateArrivalParams(), and getStopEdges().
isStopped()
virtual bool SUMOVehicle::isStopped () const pure virtual inherited
Returns whether the vehicle is at a stop.
Returns
Whether the has stopped
Implemented in MSVehicle, and MEVehicle.
Referenced by MSNet::getVehicleMeanSpeeds(), MSDevice_Transportable::notifyMove(), MSDevice_Tripinfo::notifyMove(), MSDevice_Transportable::removeTransportable(), and SUMOVehicle::~SUMOVehicle().
isStoppedInRange()
virtual bool SUMOVehicle::isStoppedInRange (double pos) const pure virtual inherited
Returns whether the vehicle is stoped in range of the given position.
Implemented in MSVehicle, and MEVehicle.
Referenced by SUMOVehicle::~SUMOVehicle().
isStoppedTriggered()
virtual bool SUMOVehicle::isStoppedTriggered () const pure virtual inherited
Returns whether the vehicle is at a stop and waiting for a person or container to continue.
Implemented in MSVehicle, and MEVehicle.
Referenced by SUMOVehicle::~SUMOVehicle().
loadState()
virtual void SUMOVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) pure virtual inherited
Loads the state of this vehicle from the given description.
Implemented in MSVehicle, and MEVehicle.
Referenced by MSStateHandler::closeVehicle(), and SUMOVehicle::~SUMOVehicle().
onDepart()
void MSBaseVehicle::onDepart () virtual
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 292 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), myDepartPos, myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by MSVehicle::enterLaneAtInsertion(), getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), and MESegment::receive().
operator=()
MSBaseVehicle& MSBaseVehicle::operator= (const MSBaseVehicle & s) private
invalidated assignment operator
removeReminder()
void MSBaseVehicle::removeReminder (MSMoveReminder * rem)
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 360 of file MSBaseVehicle.cpp.
References myMoveReminders.
Referenced by getDevices().
replaceParkingArea()
virtual bool SUMOVehicle::replaceParkingArea (MSParkingArea * parkingArea, std::string & errorMsg) pure virtual inherited
Replaces a stop.
The stop replace the next stop into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implemented in MSVehicle, and MEVehicle.
Referenced by SUMOVehicle::~SUMOVehicle().
replaceRoute()
virtual bool SUMOVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0, bool addStops = true, bool removeStops = true) pure virtual inherited
Replaces the current route by the given one.
Implemented in MEVehicle, and MSVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), replaceRouteEdges(), and SUMOVehicle::~SUMOVehicle().
replaceRouteEdges()
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false, bool removeStops = true) virtual
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
[in] removeStops Whether stops should be removed if they do not fit onto the new route
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 227 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), getID(), getNumberReroutes(), getRerouteOrigin(), hasValidRoute(), myCurrEdge, myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), toString(), and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), reroute(), and libsumo::Vehicle::setRoute().
replaceVehicleType()
void MSBaseVehicle::replaceVehicleType (MSVehicleType * type)
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSBaseVehicle::myType
Definition at line 550 of file MSBaseVehicle.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleType::isVehicleSpecific(), myType, and MSVehicleControl::removeVType().
Referenced by getSingularType(), setChosenSpeedFactor(), and libsumo::Vehicle::setType().
reroute()
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 155 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), calculateArrivalParams(), SUMOAbstractRouter< E, V >::compute(), MSInsertionControl::descheduleDeparture(), MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, MSGlobals::gCheckRoutes, Named::getID(), getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSRoute::getLastEdge(), getRerouteOrigin(), getStopEdges(), getVClass(), MSEdge::isTazConnector(), myParameter, myRoute, replaceRouteEdges(), SUMOVehicleParameter::toTaz, SUMOVehicleParameter::via, and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), getCurrentRouteEdge(), libsumo::Vehicle::rerouteEffort(), and libsumo::Vehicle::rerouteTraveltime().
saveState()
void MSBaseVehicle::saveState (OutputDevice & out) virtual
Saves the (common) state of a vehicle.
Implements SUMOVehicle.
Reimplemented in MSVehicle, and MEVehicle.
Definition at line 458 of file MSBaseVehicle.cpp.
References Named::getID(), getID(), OptionsCont::getOptions(), getVehicleType(), hasDeparted(), myParameter, myRoute, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_TAG_VEHICLE, VEHPARS_FORCE_REROUTE, SUMOVehicleParameter::wasSet(), SUMOVehicleParameter::write(), and OutputDevice::writeAttr().
Referenced by MEVehicle::saveState(), MSVehicle::saveState(), and setChosenSpeedFactor().
setArrivalPos()
virtual void MSBaseVehicle::setArrivalPos (double arrivalPos) inline virtual
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 275 of file MSBaseVehicle.h.
References hasArrived(), hasDeparted(), and myArrivalPos.
setChosenSpeedFactor()
void MSBaseVehicle::setChosenSpeedFactor (const double factor) inline virtual
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 384 of file MSBaseVehicle.h.
References addStops(), getDevice(), getSingularType(), myChosenSpeedFactor, replaceVehicleType(), and saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
setDeviceParameter()
void MSBaseVehicle::setDeviceParameter (const std::string & deviceName, const std::string & key, const std::string & value)
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 538 of file MSBaseVehicle.cpp.
References myDevices.
Referenced by libsumo::Vehicle::setParameter().
succEdge()
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSRoute::begin(), myCurrEdge, and myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), getVClass(), hasArrived(), MSPedestrianPushButton::isActiveForEdge(), libsumo::Vehicle::moveTo(), MELoop::nextSegment(), and MESegment::receive().
Friends And Related Function Documentation
GUIBaseVehicle
friend class GUIBaseVehicle friend
Definition at line 66 of file MSBaseVehicle.h.
Field Documentation
myArrivalLane
int MSBaseVehicle::myArrivalLane protected
The destination lane where the vehicle stops.
Definition at line 487 of file MSBaseVehicle.h.
Referenced by calculateArrivalParams(), and MSVehicle::updateBestLanes().
myArrivalPos
double MSBaseVehicle::myArrivalPos protected
The position on the destination lane where the vehicle stops.
Definition at line 484 of file MSBaseVehicle.h.
Referenced by calculateArrivalParams(), getArrivalPos(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), setArrivalPos(), and MSVehicle::updateBestLanes().
myChosenSpeedFactor
double MSBaseVehicle::myChosenSpeedFactor protected
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 457 of file MSBaseVehicle.h.
Referenced by getChosenSpeedFactor(), and setChosenSpeedFactor().
myCurrEdge
MSRouteIterator MSBaseVehicle::myCurrEdge protected
Iterator to current route-edge.
Definition at line 454 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::enterLaneAtMove(), getCurrentRouteEdge(), MSVehicle::getDistanceToPosition(), getEdge(), getRerouteOrigin(), MSVehicle::getRerouteOrigin(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), hasValidRoute(), MSVehicle::leaveLane(), MEVehicle::loadState(), MSVehicle::loadState(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLaneAdvances(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), replaceRouteEdges(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSVehicle::saveState(), succEdge(), MSVehicle::updateBestLanes(), and MSVehicle::willPass().
myDepartPos
double MSBaseVehicle::myDepartPos protected
The real depart position.
Definition at line 481 of file MSBaseVehicle.h.
Referenced by getDepartPos(), MSVehicle::loadState(), onDepart(), and MSVehicle::saveState().
myDeparture
SUMOTime MSBaseVehicle::myDeparture protected
The real departure time.
Definition at line 478 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), getDeparture(), hasDeparted(), MEVehicle::loadState(), MSVehicle::loadState(), onDepart(), MEVehicle::saveState(), and MSVehicle::saveState().
myDevices
std::vector<MSDevice*> MSBaseVehicle::myDevices protected
The devices this vehicle has.
Definition at line 475 of file MSBaseVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), createDevice(), getDevice(), getDeviceParameter(), getDevices(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), hasDevice(), MSBaseVehicle(), MEVehicle::saveState(), MSVehicle::saveState(), setDeviceParameter(), and ~MSBaseVehicle().
myMoveReminders
MoveReminderCont MSBaseVehicle::myMoveReminders protected
Currently relevant move reminders.
Definition at line 471 of file MSBaseVehicle.h.
Referenced by activateReminders(), MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addContainer(), MSVehicle::addPerson(), addReminder(), GUIBaseVehicle::GUIBaseVehicle(), MSVehicle::leaveLane(), MSBaseVehicle(), removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and MSVehicle::workOnMoveReminders().
myNumberReroutes
int MSBaseVehicle::myNumberReroutes protected
The number of reroutings.
Definition at line 490 of file MSBaseVehicle.h.
Referenced by getNumberReroutes(), MSVehicle::replaceRoute(), and MEVehicle::replaceRoute().
myParameter
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected
This vehicle's parameter.
Definition at line 445 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), addStops(), MSVehicle::addTraciStop(), calculateArrivalParams(), createDevice(), MSVehicle::enterLaneAtMove(), MSVehicle::getContainerNumber(), getID(), getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSVehicle::getPersonNumber(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::replaceParkingArea(), reroute(), MEVehicle::saveState(), saveState(), MSVehicle::saveState(), MSVehicle::updateBestLanes(), and ~MSBaseVehicle().
myRoute
const MSRoute* MSBaseVehicle::myRoute protected
This vehicle's route.
Definition at line 448 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), addStops(), calculateArrivalParams(), GUIVehicle::drawRouteHelper(), MSVehicle::getDistanceToPosition(), MSVehicle::getRerouteOrigin(), getRoute(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), replaceRouteEdges(), reroute(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), saveState(), MSVehicle::saveState(), succEdge(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and ~MSBaseVehicle().
myType
MSVehicleType* MSBaseVehicle::myType protected
This vehicle's type.
Definition at line 451 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), calculateArrivalParams(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getActionStepLength(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getCarFollowModel(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), getLength(), getMaxSpeed(), MSVehicle::getMaxSpeedOnLane(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), getSingularType(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), getVClass(), getVehicleType(), getWidth(), hasValidRoute(), MSVehicle::processNextStop(), replaceVehicleType(), MSVehicle::updateBestLanes(), and MSVehicle::~MSVehicle().
NOT_YET_DEPARTED
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected
Definition at line 495 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), hasDeparted(), and MSVehicle::Influencer::postProcessRemoteControl().
The documentation for this class was generated from the following files:
MSBaseVehicle.h
MSBaseVehicle.cpp