SUMO - Simulation of Urban MObility: GNERerouterIntervalDialog Class Reference
GNERerouterIntervalDialog Class Reference
Dialog for edit rerouter intervals.
#include <GNERerouterIntervalDialog.h>
Public Member Functions
GNERerouterInterval * getEditedRerouterInterval () const
get edited Rerouter Interval
GNERerouterIntervalDialog (GNERerouterInterval *rerouterInterval, bool updatingElement)
FOX-declaration.
~GNERerouterIntervalDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdAddClosingLaneReroute (FXObject *, FXSelector, void *)
add closing lane reroute
long onCmdAddClosingReroute (FXObject *, FXSelector, void *)
add closing reroute
long onCmdAddDestProbReroute (FXObject *, FXSelector, void *)
add dest prob reroute
long onCmdAddRouteProbReroute (FXObject *, FXSelector, void *)
add route prob reroute
long onCmdClickedClosingLaneReroute (FXObject *, FXSelector, void *)
remove closing lane reroute
long onCmdClickedClosingReroute (FXObject *, FXSelector, void *)
remove closing reroute
long onCmdClickedDestProbReroute (FXObject *, FXSelector, void *)
remove dest prob reroute
long onCmdClickedRouteProbReroute (FXObject *, FXSelector, void *)
remove route prob reroute
long onCmdEditClosingLaneReroute (FXObject *, FXSelector, void *)
/edit closing lane reroute
long onCmdEditClosingReroute (FXObject *, FXSelector, void *)
/edit closing reroute
long onCmdEditDestProbReroute (FXObject *, FXSelector, void *)
/edit dest prob reroute
long onCmdEditRouteProbReroute (FXObject *, FXSelector, void *)
/edit route prob reroute
long onCmdChangeBeginEnd (FXObject *, FXSelector, void *)
called when begin or endis changed
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNERerouterIntervalDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
Protected Attributes
FXButton * myAddClosingLaneReroutes
button for add new closing lane reroutes
FXButton * myAddClosingReroutes
button for add new closing reroutes
FXButton * myAddDestProbReroutes
button for add new destiny probability reroutes
FXButton * myAddRouteProbReroute
button for add new route probability reroutes
bool myBeginEndValid
flag to check if begin an end are valid
FXTextField * myBeginTextField
begin time text field
FXLabel * myCheckLabel
begin/end time check label
bool myClosingLaneReroutesValid
flag to check if closing lane reroutes are valid
FXTable * myClosingLaneRerouteTable
list with closing lane reroutes
bool myClosingReroutesValid
flag to check if closing reroutes are valid
FXTable * myClosingRerouteTable
list with closing reroutes
FXVerticalFrame * myContentFrame
frame for contents
bool myDestProbReroutesValid
flag to check if Destiny probability reroutes are valid
FXTable * myDestProbRerouteTable
list with destiny probability reroutes
GNERerouterInterval * myEditedRerouterInterval
pointer to rerouter interval
FXTextField * myEndTextField
end time text field
bool myRouteProbReroutesValid
flag to check if route prob reroutes are valid
FXTable * myRouteProbRerouteTable
list with route probability reroute
bool myUpdatingElement
flag to indicate if rerouter interval is being created or modified
Private Member Functions
GNERerouterIntervalDialog (const GNERerouterIntervalDialog &)=delete
Invalidated copy constructor.
GNERerouterIntervalDialog & operator= (const GNERerouterIntervalDialog &)=delete
Invalidated assignment operator.
void updateClosingLaneReroutesTable ()
update data of closing lane reroute table
void updateClosingReroutesTable ()
update data of closing reroute table
void updateDestProbReroutesTable ()
update data of destiny probabilitry reroute table
void updateRouteProbReroutesTable ()
update data of probabilitry reroutes table
Detailed Description
Dialog for edit rerouter intervals.
Definition at line 56 of file GNERerouterIntervalDialog.h.
Constructor & Destructor Documentation
GNERerouterIntervalDialog() [1/3]
GNERerouterIntervalDialog::GNERerouterIntervalDialog (GNERerouterInterval * rerouterInterval, bool updatingElement)
FOX-declaration.
constructor
Definition at line 91 of file GNERerouterIntervalDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelIcon32x32Thicked, GUIDesignLabelLeftThick, GUIDesignLabelThick, GUIDesignTableAdditionals, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, GUIDesignUniformHorizontalFrame, ICON_ADD, ICON_CORRECT, MID_GNE_REROUTEDIALOG_ADD_CLOSINGLANEREROUTE, MID_GNE_REROUTEDIALOG_ADD_CLOSINGREROUTE, MID_GNE_REROUTEDIALOG_ADD_DESTPROBREROUTE, MID_GNE_REROUTEDIALOG_ADD_ROUTEPROBREROUTE, MID_GNE_REROUTEDIALOG_EDIT_INTERVAL, MID_GNE_REROUTEDIALOG_TABLE_CLOSINGLANEREROUTE, MID_GNE_REROUTEDIALOG_TABLE_CLOSINGREROUTE, MID_GNE_REROUTEDIALOG_TABLE_DESTPROBREROUTE, MID_GNE_REROUTEDIALOG_TABLE_ROUTEPROBREROUTE, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, and toString().
~GNERerouterIntervalDialog()
GNERerouterIntervalDialog::~GNERerouterIntervalDialog ()
destructor
Definition at line 169 of file GNERerouterIntervalDialog.cpp.
GNERerouterIntervalDialog() [2/3]
GNERerouterIntervalDialog::GNERerouterIntervalDialog () inline protected
FOX needs this.
Definition at line 124 of file GNERerouterIntervalDialog.h.
GNERerouterIntervalDialog() [3/3]
GNERerouterIntervalDialog::GNERerouterIntervalDialog (const GNERerouterIntervalDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNECalibratorDialog::onCmdAccept(), onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), GNERerouterDialog::onCmdCancel(), GNECalibratorDialog::onCmdCancel(), onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
getEditedRerouterInterval()
GNERerouterInterval * GNERerouterIntervalDialog::getEditedRerouterInterval () const
get edited Rerouter Interval
Definition at line 173 of file GNERerouterIntervalDialog.cpp.
References myEditedRerouterInterval.
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNERerouterIntervalDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 179 of file GNERerouterIntervalDialog.cpp.
References GNEAdditionalDialog::acceptChanges(), OptionsCont::getBool(), GNERerouterInterval::getClosingLaneReroutes(), GNERerouterInterval::getClosingReroutes(), GNERerouterInterval::getDestProbReroutes(), OptionsCont::getOptions(), GNERerouterInterval::getRerouterParent(), GNERerouterInterval::getRouteProbReroutes(), GNEAttributeCarrier::getTag(), myBeginEndValid, myClosingLaneReroutesValid, myClosingReroutesValid, myDestProbReroutesValid, myEditedRerouterInterval, myRouteProbReroutesValid, myUpdatingElement, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, toString(), and WRITE_WARNING.
onCmdAddClosingLaneReroute()
long GNERerouterIntervalDialog::onCmdAddClosingLaneReroute (FXObject * , FXSelector , void *)
add closing lane reroute
Definition at line 292 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedRerouterInterval, and updateClosingLaneReroutesTable().
onCmdAddClosingReroute()
long GNERerouterIntervalDialog::onCmdAddClosingReroute (FXObject * , FXSelector , void *)
add closing reroute
Definition at line 303 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedRerouterInterval, and updateClosingReroutesTable().
onCmdAddDestProbReroute()
long GNERerouterIntervalDialog::onCmdAddDestProbReroute (FXObject * , FXSelector , void *)
add dest prob reroute
Definition at line 314 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedRerouterInterval, and updateDestProbReroutesTable().
onCmdAddRouteProbReroute()
long GNERerouterIntervalDialog::onCmdAddRouteProbReroute (FXObject * , FXSelector , void *)
add route prob reroute
Definition at line 325 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedRerouterInterval, and updateRouteProbReroutesTable().
onCmdCancel()
long GNERerouterIntervalDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 269 of file GNERerouterIntervalDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdChangeBeginEnd()
long GNERerouterIntervalDialog::onCmdChangeBeginEnd (FXObject * , FXSelector , void *)
called when begin or endis changed
Definition at line 508 of file GNERerouterIntervalDialog.cpp.
References GUIIconSubSys::getIcon(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), ICON_CORRECT, ICON_ERROR, GNERerouterInterval::isValid(), myBeginEndValid, myBeginTextField, myCheckLabel, myEditedRerouterInterval, myEndTextField, GNERerouterInterval::setAttribute(), GNERerouter::sortIntervals(), SUMO_ATTR_BEGIN, and SUMO_ATTR_END.
onCmdClickedClosingLaneReroute()
long GNERerouterIntervalDialog::onCmdClickedClosingLaneReroute (FXObject * , FXSelector , void *)
remove closing lane reroute
Definition at line 336 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getClosingLaneReroutes(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myClosingLaneRerouteTable, myEditedRerouterInterval, and updateClosingLaneReroutesTable().
onCmdClickedClosingReroute()
long GNERerouterIntervalDialog::onCmdClickedClosingReroute (FXObject * , FXSelector , void *)
remove closing reroute
Definition at line 351 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getClosingReroutes(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myClosingRerouteTable, myEditedRerouterInterval, and updateClosingReroutesTable().
onCmdClickedDestProbReroute()
long GNERerouterIntervalDialog::onCmdClickedDestProbReroute (FXObject * , FXSelector , void *)
remove dest prob reroute
Definition at line 366 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getDestProbReroutes(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myDestProbRerouteTable, myEditedRerouterInterval, and updateDestProbReroutesTable().
onCmdClickedRouteProbReroute()
long GNERerouterIntervalDialog::onCmdClickedRouteProbReroute (FXObject * , FXSelector , void *)
remove route prob reroute
Definition at line 381 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getRerouterParent(), GNERerouterInterval::getRouteProbReroutes(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedRerouterInterval, myRouteProbRerouteTable, and updateRouteProbReroutesTable().
onCmdEditClosingLaneReroute()
long GNERerouterIntervalDialog::onCmdEditClosingLaneReroute (FXObject * , FXSelector , void *)
/edit closing lane reroute
Definition at line 396 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getClosingLaneReroutes(), GUIIconSubSys::getIcon(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), ICON_CORRECT, ICON_ERROR, GNEClosingLaneReroute::isValid(), myClosingLaneReroutesValid, myClosingLaneRerouteTable, myEditedRerouterInterval, GNEClosingLaneReroute::setAttribute(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, and SUMO_ATTR_ID.
onCmdEditClosingReroute()
long GNERerouterIntervalDialog::onCmdEditClosingReroute (FXObject * , FXSelector , void *)
/edit closing reroute
Definition at line 426 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getClosingReroutes(), GUIIconSubSys::getIcon(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), ICON_CORRECT, ICON_ERROR, GNEClosingReroute::isValid(), myClosingReroutesValid, myClosingRerouteTable, myEditedRerouterInterval, GNEClosingReroute::setAttribute(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, and SUMO_ATTR_ID.
onCmdEditDestProbReroute()
long GNERerouterIntervalDialog::onCmdEditDestProbReroute (FXObject * , FXSelector , void *)
/edit dest prob reroute
Definition at line 456 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getDestProbReroutes(), GUIIconSubSys::getIcon(), GNERerouterInterval::getRerouterParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), ICON_CORRECT, ICON_ERROR, GNEDestProbReroute::isValid(), myDestProbReroutesValid, myDestProbRerouteTable, myEditedRerouterInterval, GNEDestProbReroute::setAttribute(), SUMO_ATTR_ID, and SUMO_ATTR_PROB.
onCmdEditRouteProbReroute()
long GNERerouterIntervalDialog::onCmdEditRouteProbReroute (FXObject * , FXSelector , void *)
/edit route prob reroute
Definition at line 482 of file GNERerouterIntervalDialog.cpp.
References GUIIconSubSys::getIcon(), GNERerouterInterval::getRerouterParent(), GNERerouterInterval::getRouteProbReroutes(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), ICON_CORRECT, ICON_ERROR, GNERouteProbReroute::isValid(), myEditedRerouterInterval, myRouteProbReroutesValid, myRouteProbRerouteTable, GNERouteProbReroute::setAttribute(), SUMO_ATTR_ID, and SUMO_ATTR_PROB.
onCmdReset()
long GNERerouterIntervalDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 279 of file GNERerouterIntervalDialog.cpp.
References GNEAdditionalDialog::resetChanges(), updateClosingLaneReroutesTable(), updateClosingReroutesTable(), updateDestProbReroutesTable(), and updateRouteProbReroutesTable().
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNERerouterIntervalDialog& GNERerouterIntervalDialog::operator= (const GNERerouterIntervalDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), GNERerouterDialog::onCmdReset(), GNECalibratorDialog::onCmdReset(), onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
updateClosingLaneReroutesTable()
void GNERerouterIntervalDialog::updateClosingLaneReroutesTable () private
update data of closing lane reroute table
Definition at line 528 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getClosingLaneReroutes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_CORRECT, ICON_REMOVE, myClosingLaneRerouteTable, myEditedRerouterInterval, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_ATTR_LANE, and toString().
Referenced by onCmdAddClosingLaneReroute(), onCmdClickedClosingLaneReroute(), and onCmdReset().
updateClosingReroutesTable()
void GNERerouterIntervalDialog::updateClosingReroutesTable () private
update data of closing reroute table
Definition at line 575 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getClosingReroutes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_CORRECT, ICON_REMOVE, myClosingRerouteTable, myEditedRerouterInterval, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_ID, and toString().
Referenced by onCmdAddClosingReroute(), onCmdClickedClosingReroute(), and onCmdReset().
updateDestProbReroutesTable()
void GNERerouterIntervalDialog::updateDestProbReroutesTable () private
update data of destiny probabilitry reroute table
Definition at line 622 of file GNERerouterIntervalDialog.cpp.
References GNERerouterInterval::getDestProbReroutes(), GUIIconSubSys::getIcon(), GUIDesignTableIconCellWidth, ICON_CORRECT, ICON_REMOVE, myDestProbRerouteTable, myEditedRerouterInterval, SUMO_ATTR_EDGE, SUMO_ATTR_ID, SUMO_ATTR_PROB, and toString().
Referenced by onCmdAddDestProbReroute(), onCmdClickedDestProbReroute(), and onCmdReset().
updateRouteProbReroutesTable()
void GNERerouterIntervalDialog::updateRouteProbReroutesTable () private
update data of probabilitry reroutes table
Definition at line 664 of file GNERerouterIntervalDialog.cpp.
References GUIIconSubSys::getIcon(), GNERerouterInterval::getRouteProbReroutes(), GUIDesignTableIconCellWidth, ICON_CORRECT, ICON_REMOVE, myEditedRerouterInterval, myRouteProbRerouteTable, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_ROUTE, and toString().
Referenced by onCmdAddRouteProbReroute(), onCmdClickedRouteProbReroute(), and onCmdReset().
Field Documentation
myAddClosingLaneReroutes
FXButton* GNERerouterIntervalDialog::myAddClosingLaneReroutes protected
button for add new closing lane reroutes
Definition at line 142 of file GNERerouterIntervalDialog.h.
myAddClosingReroutes
FXButton* GNERerouterIntervalDialog::myAddClosingReroutes protected
button for add new closing reroutes
Definition at line 145 of file GNERerouterIntervalDialog.h.
myAddDestProbReroutes
FXButton* GNERerouterIntervalDialog::myAddDestProbReroutes protected
button for add new destiny probability reroutes
Definition at line 148 of file GNERerouterIntervalDialog.h.
myAddRouteProbReroute
FXButton* GNERerouterIntervalDialog::myAddRouteProbReroute protected
button for add new route probability reroutes
Definition at line 151 of file GNERerouterIntervalDialog.h.
myBeginEndValid
bool GNERerouterIntervalDialog::myBeginEndValid protected
flag to check if begin an end are valid
Definition at line 166 of file GNERerouterIntervalDialog.h.
Referenced by onCmdAccept(), and onCmdChangeBeginEnd().
myBeginTextField
FXTextField* GNERerouterIntervalDialog::myBeginTextField protected
begin time text field
Definition at line 133 of file GNERerouterIntervalDialog.h.
Referenced by onCmdChangeBeginEnd().
myCheckLabel
FXLabel* GNERerouterIntervalDialog::myCheckLabel protected
begin/end time check label
Definition at line 139 of file GNERerouterIntervalDialog.h.
Referenced by onCmdChangeBeginEnd().
myClosingLaneReroutesValid
bool GNERerouterIntervalDialog::myClosingLaneReroutesValid protected
flag to check if closing lane reroutes are valid
Definition at line 169 of file GNERerouterIntervalDialog.h.
Referenced by onCmdAccept(), and onCmdEditClosingLaneReroute().
myClosingLaneRerouteTable
FXTable* GNERerouterIntervalDialog::myClosingLaneRerouteTable protected
list with closing lane reroutes
Definition at line 154 of file GNERerouterIntervalDialog.h.
Referenced by onCmdClickedClosingLaneReroute(), onCmdEditClosingLaneReroute(), and updateClosingLaneReroutesTable().
myClosingReroutesValid
bool GNERerouterIntervalDialog::myClosingReroutesValid protected
flag to check if closing reroutes are valid
Definition at line 172 of file GNERerouterIntervalDialog.h.
Referenced by onCmdAccept(), and onCmdEditClosingReroute().
myClosingRerouteTable
FXTable* GNERerouterIntervalDialog::myClosingRerouteTable protected
list with closing reroutes
Definition at line 157 of file GNERerouterIntervalDialog.h.
Referenced by onCmdClickedClosingReroute(), onCmdEditClosingReroute(), and updateClosingReroutesTable().
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myDestProbReroutesValid
bool GNERerouterIntervalDialog::myDestProbReroutesValid protected
flag to check if Destiny probability reroutes are valid
Definition at line 175 of file GNERerouterIntervalDialog.h.
Referenced by onCmdAccept(), and onCmdEditDestProbReroute().
myDestProbRerouteTable
FXTable* GNERerouterIntervalDialog::myDestProbRerouteTable protected
list with destiny probability reroutes
Definition at line 160 of file GNERerouterIntervalDialog.h.
Referenced by onCmdClickedDestProbReroute(), onCmdEditDestProbReroute(), and updateDestProbReroutesTable().
myEditedRerouterInterval
GNERerouterInterval* GNERerouterIntervalDialog::myEditedRerouterInterval protected
pointer to rerouter interval
Definition at line 127 of file GNERerouterIntervalDialog.h.
Referenced by getEditedRerouterInterval(), onCmdAccept(), onCmdAddClosingLaneReroute(), onCmdAddClosingReroute(), onCmdAddDestProbReroute(), onCmdAddRouteProbReroute(), onCmdChangeBeginEnd(), onCmdClickedClosingLaneReroute(), onCmdClickedClosingReroute(), onCmdClickedDestProbReroute(), onCmdClickedRouteProbReroute(), onCmdEditClosingLaneReroute(), onCmdEditClosingReroute(), onCmdEditDestProbReroute(), onCmdEditRouteProbReroute(), updateClosingLaneReroutesTable(), updateClosingReroutesTable(), updateDestProbReroutesTable(), and updateRouteProbReroutesTable().
myEndTextField
FXTextField* GNERerouterIntervalDialog::myEndTextField protected
end time text field
Definition at line 136 of file GNERerouterIntervalDialog.h.
Referenced by onCmdChangeBeginEnd().
myRouteProbReroutesValid
bool GNERerouterIntervalDialog::myRouteProbReroutesValid protected
flag to check if route prob reroutes are valid
Definition at line 178 of file GNERerouterIntervalDialog.h.
Referenced by onCmdAccept(), and onCmdEditRouteProbReroute().
myRouteProbRerouteTable
FXTable* GNERerouterIntervalDialog::myRouteProbRerouteTable protected
list with route probability reroute
Definition at line 163 of file GNERerouterIntervalDialog.h.
Referenced by onCmdClickedRouteProbReroute(), onCmdEditRouteProbReroute(), and updateRouteProbReroutesTable().
myUpdatingElement
bool GNERerouterIntervalDialog::myUpdatingElement protected
flag to indicate if rerouter interval is being created or modified
Definition at line 130 of file GNERerouterIntervalDialog.h.
Referenced by onCmdAccept().
The documentation for this class was generated from the following files:
GNERerouterIntervalDialog.h
GNERerouterIntervalDialog.cpp