SUMO - Simulation of Urban MObility: TraCIAPI::POIScope Class Reference
TraCIAPI::POIScope Class Reference
Scope for interaction with POIs.
#include <TraCIAPI.h>
Public Member Functions
void add (const std::string &poiID, double x, double y, const libsumo::TraCIColor &c, const std::string &type, int layer) const
libsumo::TraCIColor getColor (const std::string &poiID) const
std::vector< std::string > getIDList () const
libsumo::TraCIPosition getPosition (const std::string &poiID) const
std::string getType (const std::string &poiID) const
POIScope (TraCIAPI &parent)
void remove (const std::string &poiID, int layer=0) const
void setColor (const std::string &poiID, const libsumo::TraCIColor &c) const
void setPosition (const std::string &poiID, double x, double y) const
void setType (const std::string &poiID, const std::string &setType) const
virtual ~POIScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
POIScope & operator= (const POIScope &src)
invalidated assignment operator
POIScope (const POIScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with POIs.
Definition at line 382 of file TraCIAPI.h.
Constructor & Destructor Documentation
POIScope() [1/2]
TraCIAPI::POIScope::POIScope (TraCIAPI & parent) inline
Definition at line 384 of file TraCIAPI.h.
~POIScope()
virtual TraCIAPI::POIScope::~POIScope () inline virtual
Definition at line 385 of file TraCIAPI.h.
References TraCIAPI::getColor(), TraCIAPI::getPosition(), and TraCIAPI::TraCIScopeWrapper::operator=().
POIScope() [2/2]
TraCIAPI::POIScope::POIScope (const POIScope & src) private
invalidated copy constructor
Member Function Documentation
add()
void TraCIAPI::POIScope::add (const std::string & poiID, double x, double y, const libsumo::TraCIColor & c, const std::string & type, int layer) const
Definition at line 1323 of file TraCIAPI.cpp.
References libsumo::TraCIColor::a, ADD, libsumo::TraCIColor::b, CMD_SET_POI_VARIABLE, libsumo::TraCIColor::g, POSITION_2D, libsumo::TraCIColor::r, TYPE_COLOR, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
getColor()
TraCIColor TraCIAPI::POIScope::getColor (const std::string & poiID) const
Definition at line 1283 of file TraCIAPI.cpp.
References CMD_GET_POI_VARIABLE, and VAR_COLOR.
getIDList()
std::vector< std::string > TraCIAPI::POIScope::getIDList () const
Definition at line 1268 of file TraCIAPI.cpp.
References CMD_GET_POI_VARIABLE, and ID_LIST.
getPosition()
TraCIPosition TraCIAPI::POIScope::getPosition (const std::string & poiID) const
Definition at line 1278 of file TraCIAPI.cpp.
References CMD_GET_POI_VARIABLE, and VAR_POSITION.
getType()
std::string TraCIAPI::POIScope::getType (const std::string & poiID) const
Definition at line 1273 of file TraCIAPI.cpp.
References CMD_GET_POI_VARIABLE, and VAR_TYPE.
operator=()
POIScope& TraCIAPI::POIScope::operator= (const POIScope & src) private
invalidated assignment operator
remove()
void TraCIAPI::POIScope::remove (const std::string & poiID, int layer = 0) const
Definition at line 1345 of file TraCIAPI.cpp.
References CMD_SET_POI_VARIABLE, REMOVE, TYPE_INTEGER, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
setColor()
void TraCIAPI::POIScope::setColor (const std::string & poiID, const libsumo::TraCIColor & c) const
Definition at line 1310 of file TraCIAPI.cpp.
References libsumo::TraCIColor::a, libsumo::TraCIColor::b, CMD_SET_POI_VARIABLE, libsumo::TraCIColor::g, libsumo::TraCIColor::r, TYPE_COLOR, VAR_COLOR, and tcpip::Storage::writeUnsignedByte().
setPosition()
void TraCIAPI::POIScope::setPosition (const std::string & poiID, double x, double y) const
Definition at line 1299 of file TraCIAPI.cpp.
References CMD_SET_POI_VARIABLE, POSITION_2D, VAR_POSITION, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
setType()
void TraCIAPI::POIScope::setType (const std::string & poiID, const std::string & setType) const
Definition at line 1289 of file TraCIAPI.cpp.
References CMD_SET_POI_VARIABLE, TYPE_STRING, VAR_TYPE, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp