SUMO - Simulation of Urban MObility: GUIEvent_Screenshot Class Reference
GUIEvent_Screenshot Class Reference
#include <GUIEvent_Screenshot.h>
Public Member Functions
GUIEventType getOwnType () const
returns the event type
GUIEvent_Screenshot (GUISUMOAbstractView *view, const std::string &file)
constructor
~GUIEvent_Screenshot ()
destructor
Data Fields
const std::string myFile
the name of the file to save to
GUISUMOAbstractView *const myView
the view to save
Protected Attributes
GUIEventType myType
the type of the event
Private Member Functions
GUIEvent_Screenshot & operator= (const GUIEvent_Screenshot &s)
Invalidated assignment operator.
Detailed Description
Throw to GUIApplicationWindow from GUIRunThread to trigger a screenshot
Definition at line 51 of file GUIEvent_Screenshot.h.
Constructor & Destructor Documentation
GUIEvent_Screenshot()
GUIEvent_Screenshot::GUIEvent_Screenshot (GUISUMOAbstractView * view, const std::string & file) inline
constructor
Definition at line 54 of file GUIEvent_Screenshot.h.
~GUIEvent_Screenshot()
GUIEvent_Screenshot::~GUIEvent_Screenshot () inline
destructor
Definition at line 61 of file GUIEvent_Screenshot.h.
Member Function Documentation
getOwnType()
GUIEventType GUIEvent::getOwnType () const inline inherited
returns the event type
Definition at line 83 of file GUIEvent.h.
References GUIEvent::myType.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
operator=()
GUIEvent_Screenshot& GUIEvent_Screenshot::operator= (const GUIEvent_Screenshot & s) private
Invalidated assignment operator.
Field Documentation
myFile
const std::string GUIEvent_Screenshot::myFile
the name of the file to save to
Definition at line 68 of file GUIEvent_Screenshot.h.
Referenced by GUIApplicationWindow::handleEvent_Screenshot().
myType
GUIEventType GUIEvent::myType protected inherited
the type of the event
Definition at line 98 of file GUIEvent.h.
Referenced by GUIEvent::getOwnType(), and GUIEvent_Message::GUIEvent_Message().
myView
GUISUMOAbstractView* const GUIEvent_Screenshot::myView
the view to save
Definition at line 65 of file GUIEvent_Screenshot.h.
Referenced by GUIApplicationWindow::handleEvent_Screenshot().
The documentation for this class was generated from the following file:
GUIEvent_Screenshot.h