SUMO - Simulation of Urban MObility: MSTrafficLightLogic::SwitchCommand Class Reference
MSTrafficLightLogic::SwitchCommand Class Reference
Class realising the switch between the traffic light phases.
#include <MSTrafficLightLogic.h>
Public Member Functions
void deschedule (MSTrafficLightLogic *tlLogic)
Marks this swicth as invalid (if the phase duration has changed, f.e.)
SUMOTime execute (SUMOTime currentTime)
Executes the regarded junction's "trySwitch"- method.
SUMOTime getNextSwitchTime () const
Returns the assumed next switch time.
SwitchCommand (MSTLLogicControl &tlcontrol, MSTrafficLightLogic *tlLogic, SUMOTime nextSwitch)
Constructor.
~SwitchCommand ()
Destructor.
Private Member Functions
SwitchCommand & operator= (const SwitchCommand &)
Invalidated assignment operator.
SwitchCommand (const SwitchCommand &)
Invalidated copy constructor.
Private Attributes
bool myAmValid
Information whether this switch command is still valid.
SUMOTime myAssumedNextSwitch
Assumed switch time (may change in case of adaptive traffic lights)
MSTLLogicControl & myTLControl
The responsible traffic lights control.
MSTrafficLightLogic * myTLLogic
The logic to be executed on a switch.
Detailed Description
Class realising the switch between the traffic light phases.
Definition at line 345 of file MSTrafficLightLogic.h.
Constructor & Destructor Documentation
SwitchCommand() [1/2]
MSTrafficLightLogic::SwitchCommand::SwitchCommand (MSTLLogicControl & tlcontrol, MSTrafficLightLogic * tlLogic, SUMOTime nextSwitch)
Constructor.
Parameters
[in] tlcontrol The responsible traffic lights control
[in] tlLogic The controlled tls logic
[in] duration Duration till next switch
Definition at line 59 of file MSTrafficLightLogic.cpp.
~SwitchCommand()
MSTrafficLightLogic::SwitchCommand::~SwitchCommand ()
Destructor.
Definition at line 65 of file MSTrafficLightLogic.cpp.
SwitchCommand() [2/2]
MSTrafficLightLogic::SwitchCommand::SwitchCommand (const SwitchCommand &) private
Invalidated copy constructor.
Member Function Documentation
deschedule()
void MSTrafficLightLogic::SwitchCommand::deschedule (MSTrafficLightLogic * tlLogic)
Marks this swicth as invalid (if the phase duration has changed, f.e.)
Parameters
[in] tlLogic The controlled tls logic
Definition at line 96 of file MSTrafficLightLogic.cpp.
References myAmValid, myAssumedNextSwitch, and myTLLogic.
Referenced by MSPhasedTrafficLightLogic::changeStepAndDuration(), and MSSimpleTrafficLightLogic::changeStepAndDuration().
execute()
SUMOTime MSTrafficLightLogic::SwitchCommand::execute (SUMOTime currentTime) virtual
Executes the regarded junction's "trySwitch"- method.
Parameters
[in] currentTime The current simulation time
Returns
The time after which the command shall be executed again (the time of next switch)
Implements Command.
Definition at line 70 of file MSTrafficLightLogic.cpp.
References MSTLLogicControl::TLSLogicVariants::executeOnSwitchActions(), MSTLLogicControl::get(), MSTrafficLightLogic::getCurrentPhaseIndex(), Named::getID(), MSTLLogicControl::isActive(), myAmValid, myAssumedNextSwitch, myTLControl, myTLLogic, MSTrafficLightLogic::setTrafficLightSignals(), and MSTrafficLightLogic::trySwitch().
getNextSwitchTime()
SUMOTime MSTrafficLightLogic::SwitchCommand::getNextSwitchTime () const inline
Returns the assumed next switch time.
Returns
The assumed next switch time
Definition at line 375 of file MSTrafficLightLogic.h.
References myAssumedNextSwitch.
Referenced by MSTrafficLightLogic::getNextSwitchTime().
operator=()
SwitchCommand& MSTrafficLightLogic::SwitchCommand::operator= (const SwitchCommand &) private
Invalidated assignment operator.
Field Documentation
myAmValid
bool MSTrafficLightLogic::SwitchCommand::myAmValid private
Information whether this switch command is still valid.
Definition at line 391 of file MSTrafficLightLogic.h.
Referenced by deschedule(), and execute().
myAssumedNextSwitch
SUMOTime MSTrafficLightLogic::SwitchCommand::myAssumedNextSwitch private
Assumed switch time (may change in case of adaptive traffic lights)
Definition at line 388 of file MSTrafficLightLogic.h.
Referenced by deschedule(), execute(), and getNextSwitchTime().
myTLControl
MSTLLogicControl& MSTrafficLightLogic::SwitchCommand::myTLControl private
The responsible traffic lights control.
Definition at line 382 of file MSTrafficLightLogic.h.
Referenced by execute().
myTLLogic
MSTrafficLightLogic* MSTrafficLightLogic::SwitchCommand::myTLLogic private
The logic to be executed on a switch.
Definition at line 385 of file MSTrafficLightLogic.h.
Referenced by deschedule(), and execute().
The documentation for this class was generated from the following files:
MSTrafficLightLogic.h
MSTrafficLightLogic.cpp