SUMO - Simulation of Urban MObility: AGActivities Class Reference
AGActivities Class Reference
#include <AGActivities.h>
Public Member Functions
void addTrip (AGTrip t, std::list< AGTrip > *tripSet)
void addTrips (std::list< AGTrip > t, std::list< AGTrip > *tripSet)
AGActivities (AGCity *city, int days)
void generateActivityTrips ()
Data Fields
std::list< AGTrip > trips
Private Member Functions
bool generateBusTraffic (AGBusLine bl)
bool generateInOutTraffic ()
std::string generateName (int i, std::string prefix)
bool generateRandomTraffic ()
bool generateTrips (AGHousehold &hh)
Private Attributes
AGCity * myCity
int nbrDays
Detailed Description
Definition at line 47 of file AGActivities.h.
Constructor & Destructor Documentation
AGActivities()
AGActivities::AGActivities (AGCity * city, int days) inline
Definition at line 49 of file AGActivities.h.
References addTrip(), addTrips(), and generateActivityTrips().
Member Function Documentation
addTrip()
void AGActivities::addTrip (AGTrip t, std::list< AGTrip > * tripSet)
Definition at line 50 of file AGActivities.cpp.
Referenced by AGActivities().
addTrips()
void AGActivities::addTrips (std::list< AGTrip > t, std::list< AGTrip > * tripSet)
Definition at line 55 of file AGActivities.cpp.
Referenced by AGActivities(), and generateTrips().
generateActivityTrips()
void AGActivities::generateActivityTrips ()
trips due to public transportation
trips due to activities in the city : includes people working in work positions out of the city
trips due to incoming and outgoing traffic : the outgoing traffic is already done: households in which someone works on a work position that is out of the city.
random traffic trips : this includes uniform and proportional random traffic
Definition at line 63 of file AGActivities.cpp.
References AGCity::busLines, generateBusTraffic(), generateInOutTraffic(), generateRandomTraffic(), generateTrips(), AGCity::households, myCity, and trips.
Referenced by AGActivities(), and AGActivityGen::makeActivityTrips().
generateBusTraffic()
bool AGActivities::generateBusTraffic (AGBusLine bl) private
Buses in the first direction
Buses in the return direction
Definition at line 160 of file AGActivities.cpp.
References AGTrip::addLayOver(), AGBusLine::buses, AGBusLine::revBuses, AGBusLine::revStations, AGBusLine::stations, and trips.
Referenced by generateActivityTrips().
generateInOutTraffic()
bool AGActivities::generateInOutTraffic () private
outgoing traffic already done by generateTrips(): people who work out of the city. Here are people from outside the city coming to work.
Definition at line 203 of file AGActivities.cpp.
References AGCity::cityGates, generateName(), AGDataAndStatistics::getRandomCityGateByIncoming(), myCity, AGCity::peopleIncoming, AGTrip::setDepTime(), AGDataAndStatistics::speedTimePerKm, AGCity::statData, and trips.
Referenced by generateActivityTrips().
generateName()
std::string AGActivities::generateName (int i, std::string prefix) private
generates car names, given the unique (number, prefix)
Definition at line 233 of file AGActivities.cpp.
Referenced by generateInOutTraffic(), and generateRandomTraffic().
generateRandomTraffic()
bool AGActivities::generateRandomTraffic () private
Definition at line 240 of file AGActivities.cpp.
References generateName(), AGCity::getRandomStreet(), myCity, nbrDays, RandHelper::rand(), AGTrip::setType(), AGCity::statData, trips, and AGDataAndStatistics::uniformRandomTrafficRate.
Referenced by generateActivityTrips().
generateTrips()
bool AGActivities::generateTrips (AGHousehold & hh) private
Definition at line 125 of file AGActivities.cpp.
References addTrips(), AGWorkAndSchool::generateTrips(), AGActivity::getPartialActivityTrips(), myCity, nbrDays, REBUILD_ITERATION_LIMIT, AGHousehold::regenerate(), AGCity::statData, and trips.
Referenced by generateActivityTrips().
Field Documentation
myCity
AGCity* AGActivities::myCity private
Definition at line 75 of file AGActivities.h.
Referenced by generateActivityTrips(), generateInOutTraffic(), generateRandomTraffic(), and generateTrips().
nbrDays
int AGActivities::nbrDays private
Definition at line 77 of file AGActivities.h.
Referenced by generateRandomTraffic(), and generateTrips().
trips
std::list<AGTrip> AGActivities::trips
trips contains trips as well for one day as for every day, these trips will be regenerated with small variations by ActivityGen at the end of the simulation before generating the trip file
Definition at line 62 of file AGActivities.h.
Referenced by generateActivityTrips(), generateBusTraffic(), generateInOutTraffic(), generateRandomTraffic(), generateTrips(), and AGActivityGen::makeActivityTrips().
The documentation for this class was generated from the following files:
AGActivities.h
AGActivities.cpp