SUMO - Simulation of Urban MObility: GUIDialog_EditViewport Class Reference
GUIDialog_EditViewport Class Reference
A dialog to change the viewport.
#include <GUIDialog_EditViewport.h>
Public Types
enum {
MID_CHANGED = FXDialogBox::ID_LAST, MID_OK, MID_CANCEL, MID_LOAD,
MID_SAVE
}
FOX-callback enumerations.
Public Member Functions
GUIDialog_EditViewport (GUISUMOAbstractView *parent, const char *name, int x, int y)
Constructor.
bool haveGrabbed () const
Returns the information whether one of the spin dialers is grabbed.
void setOldValues (const Position &lookFrom, const Position &lookAt)
Resets old values.
void setValues (double zoom, double xoff, double yoff)
Sets the given values into the dialog.
void setValues (const Position &lookFrom, const Position &lookAt)
Sets the given values into the dialog.
void show ()
overload show function to focus always in OK Button
void writeXML (OutputDevice &dev)
write the settings to the given device
~GUIDialog_EditViewport ()
Destructor.
FOX-callbacks
long onCmdChanged (FXObject *, FXSelector, void *)
Called when the user changes the viewport.
long onCmdOk (FXObject *, FXSelector, void *)
Called when the user wants to keep the viewport.
long onCmdCancel (FXObject *, FXSelector, void *)
Called when the user wants to restore the viewport.
long onCmdLoad (FXObject *, FXSelector, void *)
Called when the user wants to load a viewport.
long onCmdSave (FXObject *, FXSelector, void *)
Called when the user wants to save a viewport.
Protected Member Functions
GUIDialog_EditViewport ()
FOX needs this.
Protected Attributes
FXButton * buttonOk
OK button.
Position myOldLookAt
Position myOldLookFrom
The old viewport.
GUISUMOAbstractView * myParent
The calling view.
FXRealSpinDial * myXOff
FXRealSpinDial * myYOff
FXRealSpinDial * myZOff
FXRealSpinDial * myZoom
The spin dialers used to change the view.
Detailed Description
A dialog to change the viewport.
Definition at line 50 of file GUIDialog_EditViewport.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
FOX-callback enumerations.
Enumerator
MID_CHANGED
MID_OK
MID_CANCEL
MID_LOAD
MID_SAVE
Definition at line 55 of file GUIDialog_EditViewport.h.
Constructor & Destructor Documentation
GUIDialog_EditViewport() [1/2]
GUIDialog_EditViewport::GUIDialog_EditViewport (GUISUMOAbstractView * parent, const char * name, int x, int y)
Constructor.
Parameters
[in] parent The view to change
[in] name This dialog's caption
[in] x x-position to show the dialog at
[in] y y-position to show the dialog at
Definition at line 67 of file GUIDialog_EditViewport.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonCancel, GUIDesignButtonOK, GUIDesignButtonToolbarWithText, GUIDesignContentsFrame, GUIDesignHorizontalFrameIcons, GUIDesignHorizontalSeparator, GUIDesignLabelLeftThick, GUIDesignSpinDial, ICON_ACCEPT, ICON_CANCEL, ICON_EDITVIEWPORT, ICON_OPEN_CONFIG, ICON_SAVE, MID_CANCEL, MID_LOAD, MID_OK, MID_SAVE, FX::SPINDIAL_NOMAX, and FX::SPINDIAL_NOMIN.
~GUIDialog_EditViewport()
GUIDialog_EditViewport::~GUIDialog_EditViewport ()
Destructor.
Definition at line 121 of file GUIDialog_EditViewport.cpp.
GUIDialog_EditViewport() [2/2]
GUIDialog_EditViewport::GUIDialog_EditViewport () inline protected
FOX needs this.
Definition at line 146 of file GUIDialog_EditViewport.h.
Member Function Documentation
haveGrabbed()
bool GUIDialog_EditViewport::haveGrabbed () const
Returns the information whether one of the spin dialers is grabbed.
Returns
Whether the spin dialers are currently used
Definition at line 267 of file GUIDialog_EditViewport.cpp.
References myXOff, myYOff, and myZoom.
Referenced by GUISUMOAbstractView::onMouseMove().
onCmdCancel()
long GUIDialog_EditViewport::onCmdCancel (FXObject * , FXSelector , void *)
Called when the user wants to restore the viewport.
Definition at line 156 of file GUIDialog_EditViewport.cpp.
References myOldLookAt, myOldLookFrom, myParent, and GUISUMOAbstractView::setViewportFromTo().
onCmdChanged()
long GUIDialog_EditViewport::onCmdChanged (FXObject * o, FXSelector , void *)
Called when the user changes the viewport.
Definition at line 164 of file GUIDialog_EditViewport.cpp.
References GUISUMOAbstractView::getChanger(), Position::INVALID, myParent, myXOff, myYOff, myZOff, myZoom, GUISUMOAbstractView::setViewportFromTo(), GUIPerspectiveChanger::zoom2ZPos(), and GUIPerspectiveChanger::zPos2Zoom().
onCmdLoad()
long GUIDialog_EditViewport::onCmdLoad (FXObject * , FXSelector , void *)
Called when the user wants to load a viewport.
Definition at line 182 of file GUIDialog_EditViewport.cpp.
References GUISettingsHandler::applyViewport(), gCurrentFolder, GUISUMOAbstractView::getChanger(), GUIIconSubSys::getIcon(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), ICON_EMPTY, myParent, and setValues().
onCmdOk()
long GUIDialog_EditViewport::onCmdOk (FXObject * , FXSelector , void *)
Called when the user wants to keep the viewport.
Definition at line 137 of file GUIDialog_EditViewport.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), Position::INVALID, myParent, myXOff, myYOff, myZOff, myZoom, GUISUMOAbstractView::setViewportFromTo(), toString(), and WRITE_WARNING.
onCmdSave()
long GUIDialog_EditViewport::onCmdSave (FXObject * , FXSelector , void *)
Called when the user wants to save a viewport.
Definition at line 201 of file GUIDialog_EditViewport.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), gCurrentFolder, OutputDevice::getDevice(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), ICON_EMPTY, OutputDevice::openTag(), SUMO_TAG_VIEWSETTINGS, and writeXML().
setOldValues()
void GUIDialog_EditViewport::setOldValues (const Position & lookFrom, const Position & lookAt)
Resets old values.
Parameters
[in] lookFrom Current viewport's from
[in] lookAt Current viewport's at
Definition at line 259 of file GUIDialog_EditViewport.cpp.
References myOldLookAt, myOldLookFrom, and setValues().
Referenced by GUISUMOAbstractView::showViewportEditor().
setValues() [1/2]
void GUIDialog_EditViewport::setValues (double zoom, double xoff, double yoff)
Sets the given values into the dialog.
Parameters
[in] zoom Current view's zoom
[in] xoff Current view's x-offset
[in] yoff Current view's y-offset
Definition at line 234 of file GUIDialog_EditViewport.cpp.
References GUISUMOAbstractView::getChanger(), myParent, myXOff, myYOff, myZOff, myZoom, and GUIPerspectiveChanger::zoom2ZPos().
Referenced by GUISUMOAbstractView::getViewportEditor(), onCmdLoad(), GUISUMOAbstractView::onMouseMove(), and setOldValues().
setValues() [2/2]
void GUIDialog_EditViewport::setValues (const Position & lookFrom, const Position & lookAt)
Sets the given values into the dialog.
Parameters
[in] lookFrom Current viewport's from
[in] lookAt Current viewport's at
Definition at line 243 of file GUIDialog_EditViewport.cpp.
References GUISUMOAbstractView::getChanger(), myParent, myXOff, myYOff, myZOff, myZoom, UNUSED_PARAMETER, Position::x(), Position::y(), Position::z(), and GUIPerspectiveChanger::zPos2Zoom().
show()
void GUIDialog_EditViewport::show ()
overload show function to focus always in OK Button
Definition at line 125 of file GUIDialog_EditViewport.cpp.
References buttonOk, OptionsCont::getOptions(), and myZOff.
Referenced by GUISUMOAbstractView::showViewportEditor().
writeXML()
void GUIDialog_EditViewport::writeXML (OutputDevice & dev)
write the settings to the given device
Definition at line 220 of file GUIDialog_EditViewport.cpp.
References OutputDevice::closeTag(), myXOff, myYOff, myZoom, OutputDevice::openTag(), SUMO_ATTR_CENTER_X, SUMO_ATTR_CENTER_Y, SUMO_ATTR_CENTER_Z, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_ZOOM, SUMO_TAG_VIEWPORT, and OutputDevice::writeAttr().
Referenced by GUIDialog_ViewSettings::onCmdExportSetting(), and onCmdSave().
Field Documentation
buttonOk
FXButton* GUIDialog_EditViewport::buttonOk protected
OK button.
Definition at line 136 of file GUIDialog_EditViewport.h.
Referenced by show().
myOldLookAt
Position GUIDialog_EditViewport::myOldLookAt protected
Definition at line 130 of file GUIDialog_EditViewport.h.
Referenced by onCmdCancel(), and setOldValues().
myOldLookFrom
Position GUIDialog_EditViewport::myOldLookFrom protected
The old viewport.
Definition at line 130 of file GUIDialog_EditViewport.h.
Referenced by onCmdCancel(), and setOldValues().
myParent
GUISUMOAbstractView* GUIDialog_EditViewport::myParent protected
The calling view.
Definition at line 127 of file GUIDialog_EditViewport.h.
Referenced by onCmdCancel(), onCmdChanged(), onCmdLoad(), onCmdOk(), and setValues().
myXOff
FXRealSpinDial * GUIDialog_EditViewport::myXOff protected
Definition at line 133 of file GUIDialog_EditViewport.h.
Referenced by haveGrabbed(), onCmdChanged(), onCmdOk(), setValues(), and writeXML().
myYOff
FXRealSpinDial * GUIDialog_EditViewport::myYOff protected
Definition at line 133 of file GUIDialog_EditViewport.h.
Referenced by haveGrabbed(), onCmdChanged(), onCmdOk(), setValues(), and writeXML().
myZOff
FXRealSpinDial * GUIDialog_EditViewport::myZOff protected
Definition at line 133 of file GUIDialog_EditViewport.h.
Referenced by onCmdChanged(), onCmdOk(), setValues(), and show().
myZoom
FXRealSpinDial* GUIDialog_EditViewport::myZoom protected
The spin dialers used to change the view.
Definition at line 133 of file GUIDialog_EditViewport.h.
Referenced by haveGrabbed(), onCmdChanged(), onCmdOk(), setValues(), and writeXML().
The documentation for this class was generated from the following files:
GUIDialog_EditViewport.h
GUIDialog_EditViewport.cpp