SUMO - Simulation of Urban MObility: libsumo::Polygon Class Reference
libsumo::Polygon Class Reference
#include <Polygon.h>
Static Public Member Functions
static void add (const std::string &polygonID, const TraCIPositionVector &shape, const TraCIColor &c, bool fill, const std::string &type, int layer)
static TraCIColor getColor (const std::string &polygonID)
static bool getFilled (const std::string &polygonID)
static std::vector< std::string > getIDList ()
static std::string getParameter (const std::string &polygonID, const std::string &paramName)
static TraCIPositionVector getShape (const std::string &polygonID)
static NamedRTree * getTree ()
Returns a tree filled with polygon instances.
static std::string getType (const std::string &polygonID)
static void remove (const std::string &polygonID, int layer=0)
static void setColor (const std::string &polygonID, const TraCIColor &c)
static void setFilled (std::string polygonID, bool filled)
static void setParameter (std::string &name, std::string &value, std::string &string)
static void setShape (const std::string &polygonID, const TraCIPositionVector &shape)
static void setType (const std::string &polygonID, const std::string &setType)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
Polygon & operator= (const Polygon &src)
invalidated assignment operator
Polygon ()
invalidated standard constructor
Polygon (const Polygon &src)
invalidated copy constructor
Static Private Member Functions
static SUMOPolygon * getPolygon (const std::string &id)
Detailed Description
Definition at line 47 of file Polygon.h.
Constructor & Destructor Documentation
Polygon() [1/2]
libsumo::Polygon::Polygon () private
invalidated standard constructor
Polygon() [2/2]
libsumo::Polygon::Polygon (const Polygon & src) private
invalidated copy constructor
Member Function Documentation
add()
void Polygon::add (const std::string & polygonID, const TraCIPositionVector & shape, const TraCIColor & c, bool fill, const std::string & type, int layer) static
Definition at line 91 of file Polygon.cpp.
References ShapeContainer::addPolygon(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, MSNet::getInstance(), MSNet::getShapeContainer(), libsumo::Helper::makePositionVector(), and libsumo::Helper::makeRGBColor().
Referenced by TraCIServerAPI_Polygon::processSet().
getColor()
TraCIColor Polygon::getColor (const std::string & polygonID) static
Definition at line 60 of file Polygon.cpp.
References Shape::getColor(), getPolygon(), and libsumo::Helper::makeTraCIColor().
Referenced by TraCIServerAPI_Polygon::processGet().
getFilled()
bool Polygon::getFilled (const std::string & polygonID) static
Definition at line 55 of file Polygon.cpp.
References SUMOPolygon::getFill(), and getPolygon().
Referenced by TraCIServerAPI_Polygon::processGet().
getIDList()
std::vector< std::string > Polygon::getIDList () static
Definition at line 36 of file Polygon.cpp.
References MSNet::getInstance(), ShapeContainer::getPolygons(), MSNet::getShapeContainer(), and NamedObjectCont< T >::insertIDs().
Referenced by TraCIServerAPI_Polygon::processGet().
getParameter()
std::string Polygon::getParameter (const std::string & polygonID, const std::string & paramName) static
Definition at line 66 of file Polygon.cpp.
References Parameterised::getParameter(), and getPolygon().
Referenced by TraCIServerAPI_Polygon::processGet().
getPolygon()
SUMOPolygon * Polygon::getPolygon (const std::string & id) static private
Definition at line 118 of file Polygon.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), ShapeContainer::getPolygons(), and MSNet::getShapeContainer().
Referenced by getColor(), getFilled(), getParameter(), getShape(), getType(), setColor(), setFilled(), setParameter(), setShape(), and setType().
getShape()
TraCIPositionVector Polygon::getShape (const std::string & polygonID) static
Definition at line 49 of file Polygon.cpp.
References getPolygon(), SUMOPolygon::getShape(), and libsumo::Helper::makeTraCIPositionVector().
Referenced by TraCIServerAPI_Polygon::processGet().
getTree()
NamedRTree * Polygon::getTree () static
Returns a tree filled with polygon instances.
Returns
The rtree of polygons
Definition at line 134 of file Polygon.cpp.
References MSNet::getInstance(), ShapeContainer::getPolygons(), MSNet::getShapeContainer(), NamedRTree::Insert(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
getType()
std::string Polygon::getType (const std::string & polygonID) static
Definition at line 44 of file Polygon.cpp.
References getPolygon(), and Shape::getType().
Referenced by TraCIServerAPI_Polygon::processGet().
operator=()
Polygon& libsumo::Polygon::operator= (const Polygon & src) private
invalidated assignment operator
remove()
void Polygon::remove (const std::string & polygonID, int layer = 0) static
Definition at line 101 of file Polygon.cpp.
References MSNet::getInstance(), MSNet::getShapeContainer(), and ShapeContainer::removePolygon().
Referenced by TraCIServerAPI_Polygon::processSet().
setColor()
void Polygon::setColor (const std::string & polygonID, const TraCIColor & c) static
Definition at line 85 of file Polygon.cpp.
References getPolygon(), libsumo::Helper::makeRGBColor(), and Shape::setColor().
Referenced by TraCIServerAPI_Polygon::processSet().
setFilled()
void Polygon::setFilled (std::string polygonID, bool filled) static
Definition at line 111 of file Polygon.cpp.
References getPolygon(), and SUMOPolygon::setFill().
Referenced by TraCIServerAPI_Polygon::processSet().
setParameter()
void Polygon::setParameter (std::string & name, std::string & value, std::string & string) static
Definition at line 128 of file Polygon.cpp.
References getPolygon(), and Parameterised::setParameter().
Referenced by TraCIServerAPI_Polygon::processSet().
setShape()
void Polygon::setShape (const std::string & polygonID, const TraCIPositionVector & shape) static
Definition at line 77 of file Polygon.cpp.
References MSNet::getInstance(), getPolygon(), MSNet::getShapeContainer(), libsumo::Helper::makePositionVector(), and ShapeContainer::reshapePolygon().
Referenced by TraCIServerAPI_Polygon::processSet().
setType()
void Polygon::setType (const std::string & polygonID, const std::string & setType) static
Definition at line 71 of file Polygon.cpp.
References getPolygon(), and Shape::setType().
Referenced by TraCIServerAPI_Polygon::processSet().
subscribe()
static void libsumo::Polygon::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
subscribeContext()
static void libsumo::Polygon::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
Polygon.h
Polygon.cpp