SUMO - Simulation of Urban MObility: GNERerouterDialog Class Reference
GNERerouterDialog Class Reference
Dialog for edit rerouters.
#include <GNERerouterDialog.h>
Public Member Functions
GNERerouter * getEditedRerouter () const
get edited rerouter
GNERerouterDialog (GNERerouter *rerouterParent)
FOX-declaration.
~GNERerouterDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdAddInterval (FXObject *, FXSelector, void *)
add new interval
long onCmdClickedInterval (FXObject *, FXSelector, void *)
remove or edit interval
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNERerouterDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
Protected Attributes
FXButton * myAddInterval
button for add new interval
FXVerticalFrame * myContentFrame
frame for contents
GNERerouter * myEditedRerouter
pointer to edited rerouter
FXTable * myIntervalTable
list with intervals
Private Member Functions
GNERerouterDialog (const GNERerouterDialog &)=delete
Invalidated copy constructor.
GNERerouterDialog & operator= (const GNERerouterDialog &)=delete
Invalidated assignment operator.
void updateIntervalTable ()
update data table
Detailed Description
Dialog for edit rerouters.
Definition at line 51 of file GNERerouterDialog.h.
Constructor & Destructor Documentation
GNERerouterDialog() [1/3]
GNERerouterDialog::GNERerouterDialog (GNERerouter * rerouterParent)
FOX-declaration.
Constructor
Definition at line 62 of file GNERerouterDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelThick, GUIDesignTableAdditionals, ICON_ADD, MID_GNE_REROUTEDIALOG_ADD_INTERVAL, MID_GNE_REROUTEDIALOG_TABLE_INTERVAL, SUMO_TAG_INTERVAL, and toString().
~GNERerouterDialog()
GNERerouterDialog::~GNERerouterDialog ()
destructor
Definition at line 88 of file GNERerouterDialog.cpp.
GNERerouterDialog() [2/3]
GNERerouterDialog::GNERerouterDialog () inline protected
FOX needs this.
Definition at line 85 of file GNERerouterDialog.h.
GNERerouterDialog() [3/3]
GNERerouterDialog::GNERerouterDialog (const GNERerouterDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), onCmdAccept(), GNECalibratorDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), onCmdCancel(), GNECalibratorDialog::onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
getEditedRerouter()
GNERerouter * GNERerouterDialog::getEditedRerouter () const
get edited rerouter
Definition at line 92 of file GNERerouterDialog.cpp.
References myEditedRerouter.
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNERerouterDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 98 of file GNERerouterDialog.cpp.
References GNEAdditionalDialog::acceptChanges(), OptionsCont::getBool(), GNEAttributeCarrier::getID(), GNERerouter::getNumberOfOverlappedIntervals(), OptionsCont::getOptions(), myEditedRerouter, toString(), and WRITE_WARNING.
onCmdAddInterval()
long GNERerouterDialog::onCmdAddInterval (FXObject * , FXSelector , void *)
add new interval
Definition at line 146 of file GNERerouterDialog.cpp.
References updateIntervalTable().
onCmdCancel()
long GNERerouterDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 126 of file GNERerouterDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdClickedInterval()
long GNERerouterDialog::onCmdClickedInterval (FXObject * , FXSelector , void *)
remove or edit interval
Definition at line 156 of file GNERerouterDialog.cpp.
References GNERerouterInterval::getClosingLaneReroutes(), GNERerouterInterval::getClosingReroutes(), GNERerouterInterval::getDestProbReroutes(), GNERerouter::getRerouterIntervals(), GNERerouterInterval::getRouteProbReroutes(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedRerouter, myIntervalTable, and updateIntervalTable().
onCmdReset()
long GNERerouterDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 136 of file GNERerouterDialog.cpp.
References GNEAdditionalDialog::resetChanges(), and updateIntervalTable().
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNERerouterDialog& GNERerouterDialog::operator= (const GNERerouterDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), onCmdReset(), GNECalibratorDialog::onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
updateIntervalTable()
void GNERerouterDialog::updateIntervalTable () private
update data table
Definition at line 201 of file GNERerouterDialog.cpp.
References GUIIconSubSys::getIcon(), GNERerouter::getRerouterIntervals(), GUIDesignTableIconCellWidth, ICON_REMOVE, myEditedRerouter, myIntervalTable, SUMO_ATTR_BEGIN, SUMO_ATTR_END, and toString().
Referenced by onCmdAddInterval(), onCmdClickedInterval(), and onCmdReset().
Field Documentation
myAddInterval
FXButton* GNERerouterDialog::myAddInterval protected
button for add new interval
Definition at line 91 of file GNERerouterDialog.h.
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myEditedRerouter
GNERerouter* GNERerouterDialog::myEditedRerouter protected
pointer to edited rerouter
Definition at line 88 of file GNERerouterDialog.h.
Referenced by getEditedRerouter(), onCmdAccept(), onCmdClickedInterval(), and updateIntervalTable().
myIntervalTable
FXTable* GNERerouterDialog::myIntervalTable protected
list with intervals
Definition at line 94 of file GNERerouterDialog.h.
Referenced by onCmdClickedInterval(), and updateIntervalTable().
The documentation for this class was generated from the following files:
GNERerouterDialog.h
GNERerouterDialog.cpp