SUMO - Simulation of Urban MObility: Option_Bool Class Reference
Option_Bool Class Reference
#include <Option.h>
Public Member Functions
bool getBool () const
Returns the stored boolean value.
const std::string & getDescription () const
Returns the description of what this option does.
virtual double getFloat () const
Returns the stored double value.
virtual int getInt () const
Returns the stored integer value.
virtual const IntVector & getIntVector () const
Returns the stored integer vector.
virtual std::string getString () const
Returns the stored string value.
virtual const std::string & getTypeName () const
Returns the mml-type name of this option.
std::string getValueString () const
Returns the string-representation of the value.
bool isBool () const
Returns true, the information whether the option is a bool option.
virtual bool isDefault () const
Returns the information whether the option holds the default value.
virtual bool isFileName () const
Returns the information whether this option is a file name.
bool isSet () const
returns the information whether this options holds a valid value
bool isWriteable () const
Returns the information whether the option may be set a further time.
Option_Bool & operator= (const Option_Bool &s)
Assignment operator.
Option_Bool (bool value)
Constructor for an option with a default value.
Option_Bool (const Option_Bool &s)
Copy constructor.
void resetDefault ()
Resets the option to be on its default value.
void resetWritable ()
Resets the option to be writeable.
bool set (const std::string &v)
void setDescription (const std::string &desc)
Sets the description of what this option does.
void unSet ()
marks this option as unset
~Option_Bool ()
Destructor.
Protected Member Functions
bool markSet ()
Marks the information as set.
Protected Attributes
std::string myTypeName
A type name for this option (has presets, but may be overwritten)
Private Attributes
bool myValue
Detailed Description
Definition at line 519 of file Option.h.
Constructor & Destructor Documentation
Option_Bool() [1/2]
Option_Bool::Option_Bool (bool value)
Constructor for an option with a default value.
Calls Option(true)
Parameters
[in] value This option's default value
Definition at line 352 of file Option.cpp.
References Option::myTypeName.
Option_Bool() [2/2]
Option_Bool::Option_Bool (const Option_Bool & s)
Copy constructor.
Definition at line 361 of file Option.cpp.
References myValue.
~Option_Bool()
Option_Bool::~Option_Bool ()
Destructor.
Definition at line 358 of file Option.cpp.
Member Function Documentation
getBool()
bool Option_Bool::getBool () const virtual
Returns the stored boolean value.
See also
bool Option::getBool()
Returns
Returns the stored boolean
Reimplemented from Option.
Definition at line 379 of file Option.cpp.
References myValue.
getDescription()
const std::string & Option::getDescription () const inherited
Returns the description of what this option does.
The description stored in myDescription is returned.
Returns
The description of this option's purpose
Definition at line 164 of file Option.cpp.
References Option::myDescription.
Referenced by OptionsCont::printHelp(), and OptionsCont::writeConfiguration().
getFloat()
double Option::getFloat () const virtual inherited
Returns the stored double value.
Option_Float returns the stored real number in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored real number if being an instance of Option_Float
Exceptions
InvalidArgument If the class is not an instance of Option_Float
Reimplemented in Option_Float.
Definition at line 81 of file Option.cpp.
Referenced by OptionsCont::getFloat().
getInt()
int Option::getInt () const virtual inherited
Returns the stored integer value.
Option_Integer returns the stored integer number in this method's reimplementation. All other option classesdo not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored integer number if being an instance of Option_Integer
Exceptions
InvalidArgument If the class is not an instance of Option_Integer
Reimplemented in Option_Integer.
Definition at line 87 of file Option.cpp.
Referenced by OptionsCont::getInt().
getIntVector()
const IntVector & Option::getIntVector () const virtual inherited
Returns the stored integer vector.
Option_IntVector returns the stored integer vector in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored integer vector if being an instance of Option_IntVector
Exceptions
InvalidArgument If the class is not an instance of Option_IntVector
Reimplemented in Option_IntVector.
Definition at line 105 of file Option.cpp.
Referenced by OptionsCont::getIntVector().
getString()
std::string Option::getString () const virtual inherited
Returns the stored string value.
Option_String and Option_FileName return the stored string in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored string if being an instance of Option_String
Exceptions
InvalidArgument If the class is not an instance of Option_String
Reimplemented in Option_String.
Definition at line 93 of file Option.cpp.
Referenced by OptionsCont::getString(), and OptionsCont::getStringVector().
getTypeName()
const std::string & Option::getTypeName () const virtual inherited
Returns the mml-type name of this option.
The type name stored in myTypeName is returned.
Returns
The man-readable type name
Definition at line 176 of file Option.cpp.
References Option::myTypeName.
Referenced by OptionsCont::getTypeName(), OptionsCont::printHelp(), OptionsCont::writeConfiguration(), and OptionsCont::writeSchema().
getValueString()
std::string Option_Bool::getValueString () const virtual
Returns the string-representation of the value.
If myValue is true, "true" is returned, "false" otherwise.
See also
std::string Option::getValueString()
Returns
The stored value encoded into a string
Implements Option.
Definition at line 396 of file Option.cpp.
References myValue.
isBool()
bool Option_Bool::isBool () const virtual
Returns true, the information whether the option is a bool option.
Returns true.
See also
bool Option::isBool()
Returns
true
Reimplemented from Option.
Definition at line 405 of file Option.cpp.
isDefault()
bool Option::isDefault () const virtual inherited
Returns the information whether the option holds the default value.
Returns
true if the option was not set from command line / configuration, false otherwise
Definition at line 134 of file Option.cpp.
References Option::myHaveTheDefaultValue.
Referenced by OptionsCont::writeConfiguration().
isFileName()
bool Option::isFileName () const virtual inherited
Returns the information whether this option is a file name.
Returns false. Only Option_FileName overrides this method returning true.
Returns
true if the Option is an Option_FileName, false otherwise
Reimplemented in Option_FileName.
Definition at line 140 of file Option.cpp.
isSet()
bool Option::isSet () const inherited
returns the information whether this options holds a valid value
Returns
Whether a value has been set
Definition at line 75 of file Option.cpp.
References Option::myAmSet.
Referenced by OptionsCont::checkDependingSuboptions(), OptionsCont::isUsableFileList(), and OptionsCont::writeConfiguration().
isWriteable()
bool Option::isWriteable () const inherited
Returns the information whether the option may be set a further time.
This method returns whether the option was not already set using command line options / configuration. This is done by returning the value of myAmWritable.
Returns
Whether the option may be set from the command line / configuration
Definition at line 146 of file Option.cpp.
References Option::myAmWritable.
Referenced by OptionsCont::isWriteable(), and OptionsCont::set().
markSet()
bool Option::markSet () protected inherited
Marks the information as set.
Sets the "myAmSet" - information. Returns whether the option was writeable before.
Returns
Whether the option was not set before.
Definition at line 111 of file Option.cpp.
References Option::myAmSet, Option::myAmWritable, and Option::myHaveTheDefaultValue.
Referenced by Option_Integer::set(), Option_String::set(), Option_Float::set(), set(), and Option_IntVector::set().
operator=()
Option_Bool & Option_Bool::operator= (const Option_Bool & s)
Assignment operator.
Definition at line 368 of file Option.cpp.
References myValue, and Option::operator=().
resetDefault()
void Option::resetDefault () inherited
Resets the option to be on its default value.
An option is on its default after initialisation with a value, but as soon as it gets set, it is no longer. This method resets the default-flag.
Definition at line 158 of file Option.cpp.
References Option::myHaveTheDefaultValue.
Referenced by OptionsCont::setDefault().
resetWritable()
void Option::resetWritable () inherited
Resets the option to be writeable.
An option is writable after initialisation, but as soon as it gets set, it is no longer writeable. This method resets the writable-flag.
Definition at line 152 of file Option.cpp.
References Option::myAmWritable.
set()
bool Option_Bool::set (const std::string & v) virtual
sets the given value (converts it to bool)
Implements Option.
Definition at line 385 of file Option.cpp.
References TplConvert::_2bool(), Option::markSet(), and myValue.
setDescription()
void Option::setDescription (const std::string & desc) inherited
Sets the description of what this option does.
The description stored in myDescription is returned.
Returns
The description of this option's purpose
Definition at line 170 of file Option.cpp.
References Option::myDescription.
Referenced by OptionsCont::addDescription().
unSet()
void Option::unSet () inherited
marks this option as unset
Definition at line 121 of file Option.cpp.
References Option::myAmSet, and Option::myAmWritable.
Field Documentation
myTypeName
std::string Option::myTypeName protected inherited
A type name for this option (has presets, but may be overwritten)
Definition at line 286 of file Option.h.
Referenced by Option::getTypeName(), Option_Bool(), Option_FileName::Option_FileName(), Option_Float::Option_Float(), Option_Integer::Option_Integer(), Option_IntVector::Option_IntVector(), and Option_String::Option_String().
myValue
bool Option_Bool::myValue private
the value, valid only when the base-classes "myAmSet"-member is true
Definition at line 574 of file Option.h.
Referenced by getBool(), getValueString(), operator=(), Option_Bool(), and set().
The documentation for this class was generated from the following files:
Option.h
Option.cpp