SUMO - Simulation of Urban MObility: VectorHelper< T > Class Template Reference
VectorHelper< T > Class Template Reference
#include <VectorHelper.h>
Static Public Member Functions
static void add2All (std::vector< T > &v, T what)
static void div (std::vector< T > &v, T by)
static T maxValue (const std::vector< T > &v)
static T minValue (const std::vector< T > &v)
static void normaliseSum (std::vector< T > &v, T msum=1.0)
static void remove_larger_than (std::vector< T > &v, T swell)
static void remove_smaller_than (std::vector< T > &v, T swell)
static void removeDouble (std::vector< T > &v)
static void set (std::vector< T > &v, T to)
static bool subSetExists (const std::vector< T > &v1, const std::vector< T > &v2)
Returns the information whether at least one element is within both vectors.
static T sum (const std::vector< T > &v)
Detailed Description
template<class T>
class VectorHelper< T >
Definition at line 47 of file VectorHelper.h.
Member Function Documentation
add2All()
template<class T > static void VectorHelper< T >::add2All (std::vector< T > & v, T what) inline static
Definition at line 137 of file VectorHelper.h.
div()
template<class T > static void VectorHelper< T >::div (std::vector< T > & v, T by) inline static
Definition at line 70 of file VectorHelper.h.
Referenced by VectorHelper< T >::normaliseSum().
maxValue()
template<class T > static T VectorHelper< T >::maxValue (const std::vector< T > & v) inline static
Definition at line 97 of file VectorHelper.h.
Referenced by NBNodeShapeComputer::badIntersection(), NBEdgeCont::guessOpposites(), NBEdge::isNearEnough2BeJoined2(), and NBEdge::startShapeAt().
minValue()
template<class T > static T VectorHelper< T >::minValue (const std::vector< T > & v) inline static
Definition at line 107 of file VectorHelper.h.
Referenced by NBNodeShapeComputer::badIntersection().
normaliseSum()
template<class T > static void VectorHelper< T >::normaliseSum (std::vector< T > & v, T msum = 1.0) inline static
Definition at line 57 of file VectorHelper.h.
References VectorHelper< T >::div(), and VectorHelper< T >::sum().
Referenced by NWWriter_SUMO::writeDistrict().
remove_larger_than()
template<class T > static void VectorHelper< T >::remove_larger_than (std::vector< T > & v, T swell) inline static
Definition at line 127 of file VectorHelper.h.
remove_smaller_than()
template<class T > static void VectorHelper< T >::remove_smaller_than (std::vector< T > & v, T swell) inline static
Definition at line 117 of file VectorHelper.h.
removeDouble()
template<class T > static void VectorHelper< T >::removeDouble (std::vector< T > & v) inline static
Definition at line 76 of file VectorHelper.h.
Referenced by NIVissimConnectionCluster::add(), NIVissimEdge::buildConnectionClusters(), and NIVissimConnectionCluster::NIVissimConnectionCluster().
set()
template<class T > static void VectorHelper< T >::set (std::vector< T > & v, T to) inline static
Definition at line 91 of file VectorHelper.h.
subSetExists()
template<class T > static bool VectorHelper< T >::subSetExists (const std::vector< T > & v1, const std::vector< T > & v2) inline static
Returns the information whether at least one element is within both vectors.
Definition at line 144 of file VectorHelper.h.
sum()
template<class T > static T VectorHelper< T >::sum (const std::vector< T > & v) inline static
Definition at line 49 of file VectorHelper.h.
Referenced by VectorHelper< T >::normaliseSum().
The documentation for this class was generated from the following file:
VectorHelper.h