SUMO - Simulation of Urban MObility: TraCIAPI::PolygonScope Class Reference
TraCIAPI::PolygonScope Class Reference
Scope for interaction with polygons.
#include <TraCIAPI.h>
Public Member Functions
void add (const std::string &polygonID, const libsumo::TraCIPositionVector &shape, const libsumo::TraCIColor &c, bool fill, const std::string &type, int layer) const
libsumo::TraCIColor getColor (const std::string &polygonID) const
std::vector< std::string > getIDList () const
libsumo::TraCIPositionVector getShape (const std::string &polygonID) const
std::string getType (const std::string &polygonID) const
PolygonScope (TraCIAPI &parent)
void remove (const std::string &polygonID, int layer=0) const
void setColor (const std::string &polygonID, const libsumo::TraCIColor &c) const
void setShape (const std::string &polygonID, const libsumo::TraCIPositionVector &shape) const
void setType (const std::string &polygonID, const std::string &setType) const
virtual ~PolygonScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
PolygonScope & operator= (const PolygonScope &src)
invalidated assignment operator
PolygonScope (const PolygonScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with polygons.
Definition at line 414 of file TraCIAPI.h.
Constructor & Destructor Documentation
PolygonScope() [1/2]
TraCIAPI::PolygonScope::PolygonScope (TraCIAPI & parent) inline
Definition at line 416 of file TraCIAPI.h.
~PolygonScope()
virtual TraCIAPI::PolygonScope::~PolygonScope () inline virtual
Definition at line 417 of file TraCIAPI.h.
References TraCIAPI::getColor(), and TraCIAPI::TraCIScopeWrapper::operator=().
PolygonScope() [2/2]
TraCIAPI::PolygonScope::PolygonScope (const PolygonScope & src) private
invalidated copy constructor
Member Function Documentation
add()
void TraCIAPI::PolygonScope::add (const std::string & polygonID, const libsumo::TraCIPositionVector & shape, const libsumo::TraCIColor & c, bool fill, const std::string & type, int layer) const
Definition at line 1418 of file TraCIAPI.cpp.
References libsumo::TraCIColor::a, ADD, libsumo::TraCIColor::b, CMD_SET_POLYGON_VARIABLE, libsumo::TraCIColor::g, libsumo::TraCIColor::r, TYPE_COLOR, TYPE_COMPOUND, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_UBYTE, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
getColor()
TraCIColor TraCIAPI::PolygonScope::getColor (const std::string & polygonID) const
Definition at line 1375 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and VAR_COLOR.
getIDList()
std::vector< std::string > TraCIAPI::PolygonScope::getIDList () const
Definition at line 1360 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and ID_LIST.
getShape()
TraCIPositionVector TraCIAPI::PolygonScope::getShape (const std::string & polygonID) const
Definition at line 1370 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and VAR_SHAPE.
getType()
std::string TraCIAPI::PolygonScope::getType (const std::string & polygonID) const
Definition at line 1365 of file TraCIAPI.cpp.
References CMD_GET_POLYGON_VARIABLE, and VAR_TYPE.
operator=()
PolygonScope& TraCIAPI::PolygonScope::operator= (const PolygonScope & src) private
invalidated assignment operator
remove()
void TraCIAPI::PolygonScope::remove (const std::string & polygonID, int layer = 0) const
Definition at line 1446 of file TraCIAPI.cpp.
References CMD_SET_POLYGON_VARIABLE, REMOVE, TYPE_INTEGER, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
setColor()
void TraCIAPI::PolygonScope::setColor (const std::string & polygonID, const libsumo::TraCIColor & c) const
Definition at line 1405 of file TraCIAPI.cpp.
References libsumo::TraCIColor::a, libsumo::TraCIColor::b, CMD_SET_POLYGON_VARIABLE, libsumo::TraCIColor::g, libsumo::TraCIColor::r, TYPE_COLOR, VAR_COLOR, and tcpip::Storage::writeUnsignedByte().
setShape()
void TraCIAPI::PolygonScope::setShape (const std::string & polygonID, const libsumo::TraCIPositionVector & shape) const
Definition at line 1391 of file TraCIAPI.cpp.
References CMD_SET_POLYGON_VARIABLE, TYPE_POLYGON, VAR_POSITION, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
setType()
void TraCIAPI::PolygonScope::setType (const std::string & polygonID, const std::string & setType) const
Definition at line 1381 of file TraCIAPI.cpp.
References CMD_SET_POLYGON_VARIABLE, TYPE_STRING, VAR_TYPE, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp