SUMO - Simulation of Urban MObility: ROPerson::Ride Class Reference
ROPerson::Ride Class Reference
A ride is part of a trip, e.g., go from here to here by car or bus.
#include <ROPerson.h>
Public Member Functions
const ROEdge * getDestination () const
const ROEdge * getOrigin () const
Ride (const ROEdge *const _from, const ROEdge *const _to, const std::string &_lines, const double _cost, const std::string &_destStop="")
void saveAsXML (OutputDevice &os, const bool extended) const
Protected Attributes
double cost
Private Member Functions
Ride & operator= (const Ride &src)
Invalidated assignment operator.
Private Attributes
const std::string destStop
const ROEdge *const from
const std::string lines
const ROEdge *const to
Detailed Description
A ride is part of a trip, e.g., go from here to here by car or bus.
Definition at line 160 of file ROPerson.h.
Constructor & Destructor Documentation
Ride()
ROPerson::Ride::Ride (const ROEdge *const _from, const ROEdge *const _to, const std::string & _lines, const double _cost, const std::string & _destStop = "") inline
Definition at line 162 of file ROPerson.h.
Member Function Documentation
getDestination()
const ROEdge* ROPerson::Ride::getDestination () const inline virtual
Implements ROPerson::TripItem.
Definition at line 169 of file ROPerson.h.
References ROPerson::PlanItem::saveAsXML().
getOrigin()
const ROEdge* ROPerson::Ride::getOrigin () const inline virtual
Implements ROPerson::TripItem.
Definition at line 166 of file ROPerson.h.
operator=()
Ride& ROPerson::Ride::operator= (const Ride & src) private
Invalidated assignment operator.
saveAsXML()
void ROPerson::Ride::saveAsXML (OutputDevice & os, const bool extended) const virtual
Implements ROPerson::TripItem.
Definition at line 117 of file ROPerson.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), SUMO_ATTR_BUS_STOP, SUMO_ATTR_COST, SUMO_ATTR_FROM, SUMO_ATTR_LINES, SUMO_ATTR_TO, SUMO_TAG_RIDE, and OutputDevice::writeAttr().
Field Documentation
cost
double ROPerson::TripItem::cost protected inherited
Definition at line 153 of file ROPerson.h.
destStop
const std::string ROPerson::Ride::destStop private
Definition at line 178 of file ROPerson.h.
from
const ROEdge* const ROPerson::Ride::from private
Definition at line 175 of file ROPerson.h.
lines
const std::string ROPerson::Ride::lines private
Definition at line 177 of file ROPerson.h.
to
const ROEdge* const ROPerson::Ride::to private
Definition at line 176 of file ROPerson.h.
The documentation for this class was generated from the following files:
ROPerson.h
ROPerson.cpp