SUMO - Simulation of Urban MObility: NBEdgeCont Class Reference
NBEdgeCont Class Reference
Storage for edges, including some functionality operating on multiple edges.
#include <NBEdgeCont.h>
Data Structures
struct PostProcessConnection
A structure representing a connection between two lanes.
Public Member Functions
void addRoundabout (const EdgeSet &roundabout)
add user specified roundabout
void applyOptions (OptionsCont &oc)
Initialises the storage by applying given options.
void checkGrade (double threshold) const
check whether edges are to steep
void checkOverlap (double threshold, double zThreshold) const
check whether edges overlap
void clear ()
Deletes all edges.
void generateStreetSigns ()
assigns street signs to edges based on toNode types
NBEdge * getByID (const std::string &edgeID) const
Returns the edge with id if it exists.
EdgeVector getGeneratedFrom (const std::string &id) const
Returns the edges which have been built by splitting the edge of the given id.
NBEdge * getOppositeByID (const std::string &edgeID) const
Returns the edge with negated id if it exists.
const std::set< EdgeSet > getRoundabouts () const
Returns the determined roundabouts.
int guessRoundabouts ()
Determines which edges belong to roundabouts and increases their priority.
int guessSidewalks (double width, double minSpeed, double maxSpeed, bool fromPermissions)
add sidwalks to edges within the given limits or permissions and return the number of edges affected
void ignore (std::string id)
mark the given edge id as ignored
bool ignoreFilterMatch (NBEdge *edge)
Returns true if this edge matches one of the removal criteria.
void markRoundabouts ()
mark edge priorities and prohibit turn-arounds for all roundabout edges
NBEdgeCont (NBTypeCont &tc)
Constructor.
void patchRoundabouts (NBEdge *orig, NBEdge *part1, NBEdge *part2, std::set< EdgeSet > &roundabouts)
fix roundabout information after splitting an edge
int remapIDs (bool numericaIDs, bool reservedIDs)
remap node IDs accoring to options –numerical-ids and –reserved-ids
void rename (NBEdge *edge, const std::string &newID)
Renames the edge. Throws exception if newID already exists.
bool wasIgnored (std::string id) const
Returns whether the edge with the id was ignored during parsing.
bool wasRemoved (std::string id) const
Returns whether the edge with the id was deleted explicitly.
~NBEdgeCont ()
Destructor.
edge access methods
bool insert (NBEdge *edge, bool ignorePrunning=false)
Adds an edge to the dictionary.
NBEdge * retrieve (const std::string &id, bool retrieveExtracted=false) const
Returns the edge that has the given id.
NBEdge * retrievePossiblySplit (const std::string &id, bool downstream) const
Tries to retrieve an edge, even if it is splitted.
NBEdge * retrievePossiblySplit (const std::string &id, const std::string &hint, bool incoming) const
Tries to retrieve an edge, even if it is splitted.
NBEdge * retrievePossiblySplit (const std::string &id, double pos) const
Tries to retrieve an edge, even if it is splitted.
void erase (NBDistrictCont &dc, NBEdge *edge)
Removes the given edge from the container (deleting it)
void extract (NBDistrictCont &dc, NBEdge *edge, bool remember=false)
Removes the given edge from the container like erase but does not delete it.
std::map< std::string, NBEdge * >::const_iterator begin () const
Returns the pointer to the begin of the stored edges.
std::map< std::string, NBEdge * >::const_iterator end () const
Returns the pointer to the end of the stored edges.
explicit edge manipulation methods
bool splitAt (NBDistrictCont &dc, NBEdge *edge, NBNode *node)
Splits the edge at the position nearest to the given node.
bool splitAt (NBDistrictCont &dc, NBEdge *edge, NBNode *node, const std::string &firstEdgeName, const std::string &secondEdgeName, int noLanesFirstEdge, int noLanesSecondEdge, const double speed=-1., const int changedLeft=0)
Splits the edge at the position nearest to the given node using the given modifications.
bool splitAt (NBDistrictCont &dc, NBEdge *edge, double edgepos, NBNode *node, const std::string &firstEdgeName, const std::string &secondEdgeName, int noLanesFirstEdge, int noLanesSecondEdge, const double speed=-1., const int changedLeft=0)
Splits the edge at the position nearest to the given node using the given modifications.
container access methods
int size () const
Returns the number of edges.
std::vector< std::string > getAllNames () const
Returns all ids of known edges.
int getNoEdgeSplits () const
Returns the number of edge splits.
Adapting the input
void removeUnwishedEdges (NBDistrictCont &dc)
Removes unwished edges (not in keep-edges)
void splitGeometry (NBNodeCont &nc)
Splits edges into multiple if they have a complex geometry.
void reduceGeometries (const double minDist)
void checkGeometries (const double maxAngle, const double minRadius, bool fix)
processing methods
void sortOutgoingLanesConnections ()
Sorts all lanes of all edges within the container by their direction.
void computeEdge2Edges (bool noLeftMovers)
Computes for each edge the approached edges.
void computeLanes2Edges ()
Computes for each edge which lanes approach the next edges.
void recheckLanes ()
Rechecks whether all lanes have a successor for each of the stored edges.
void appendTurnarounds (bool noTLSControlled)
Appends turnarounds to all edges stored in the container.
void appendTurnarounds (const std::set< std::string > &ids, bool noTLSControlled)
Appends turnarounds to all edges stored in the container Calls "NBEdge::appendTurnaround" for edges with the given ids.
void computeEdgeShapes ()
Computes the shapes of all edges stored in the container.
void computeLaneShapes ()
Computes the shapes of all lanes of all edges stored in the container.
void clearControllingTLInformation () const
Clears information about controlling traffic lights for all connenections of all edges.
void joinSameNodeConnectingEdges (NBDistrictCont &dc, NBTrafficLightLogicCont &tlc, EdgeVector edges)
Joins the given edges because they connect the same nodes.
void guessOpposites ()
Sets opposite lane information for geometrically close edges.
void recheckLaneSpread ()
Rechecks whether the lane spread is proper.
Connections handling
void addPostProcessConnection (const std::string &from, int fromLane, const std::string &to, int toLane, bool mayDefinitelyPass, bool keepClear, double contPos, double visibility, double speed, const PositionVector &customShape, bool warnOnly=false)
Adds a connection which could not be set during loading.
void recheckPostProcessConnections ()
Try to set any stored connections.
Private Types
typedef std::map< std::string, NBEdge * > EdgeCont
The type of the dictionary where an edge may be found by its id.
Private Member Functions
NBEdgeCont (const NBEdgeCont &s)
invalidated copy constructor
NBEdgeCont & operator= (const NBEdgeCont &s)
invalidated assignment operator
Static Private Member Functions
static double formFactor (const EdgeVector &loopEdges)
compute the form factor for a loop of edges
Private Attributes
std::vector< PostProcessConnection > myConnections
The list of connections to recheck.
EdgeCont myEdges
The instance of the dictionary (id->edge)
int myEdgesSplit
the number of splits of edges during the building
EdgeCont myExtractedEdges
The extracted nodes which are kept for reference.
std::set< EdgeSet > myGuessedRoundabouts
Edges marked as belonging to a roundabout after guessing.
std::set< std::string > myIgnoredEdges
The ids of ignored edges.
std::set< EdgeSet > myRoundabouts
Edges marked as belonging to a roundabout by the user (each EdgeVector is a roundabout)
NBTypeCont & myTypeCont
The network builder; used to obtain type information.
Settings for accepting/dismissing edges
double myEdgesMinSpeed
The minimum speed an edge may have in order to be kept (default: -1)
bool myRemoveEdgesAfterJoining
Whether edges shall be joined first, then removed.
std::set< std::string > myEdges2Keep
Set of ids of edges which shall explicitly be kept.
std::set< std::string > myEdges2Remove
Set of ids of edges which shall explicitly be removed.
SVCPermissions myVehicleClasses2Keep
Set of vehicle types which must be allowed on edges in order to keep them.
SVCPermissions myVehicleClasses2Remove
Set of vehicle types which need not be supported (edges which allow ONLY these are removed)
std::set< std::string > myTypes2Keep
Set of edges types which shall be kept.
std::set< std::string > myTypes2Remove
Set of edges types which shall be removed.
PositionVector myPruningBoundary
Boundary within which an edge must be located in order to be kept.
bool myNeedGeoTransformedPruningBoundary
whether a geo transform has been applied to the pruning boundary
Detailed Description
Storage for edges, including some functionality operating on multiple edges.
Definition at line 66 of file NBEdgeCont.h.
Member Typedef Documentation
EdgeCont
typedef std::map<std::string, NBEdge*> NBEdgeCont::EdgeCont private
The type of the dictionary where an edge may be found by its id.
Definition at line 623 of file NBEdgeCont.h.
Constructor & Destructor Documentation
NBEdgeCont() [1/2]
NBEdgeCont::NBEdgeCont (NBTypeCont & tc)
Constructor.
Parameters
[in] tc The net builded; used to obtain types
Definition at line 62 of file NBEdgeCont.cpp.
~NBEdgeCont()
NBEdgeCont::~NBEdgeCont ()
Destructor.
Definition at line 71 of file NBEdgeCont.cpp.
References clear().
NBEdgeCont() [2/2]
NBEdgeCont::NBEdgeCont (const NBEdgeCont & s) private
invalidated copy constructor
Member Function Documentation
addPostProcessConnection()
void NBEdgeCont::addPostProcessConnection (const std::string & from, int fromLane, const std::string & to, int toLane, bool mayDefinitelyPass, bool keepClear, double contPos, double visibility, double speed, const PositionVector & customShape, bool warnOnly = false)
Adds a connection which could not be set during loading.
Parameters
[in] from The id of the edge the connection starts at
[in] fromLane The number of the lane the connection starts at
[in] to The id of the edge the connection ends at
[in] toLane The number of the lane the connection ends at
[in] mayDefinitelyPass Whether the connection may be passed without braking
[in] keepClear Whether the connection must check to keep the junction clear
[in] contPos Custom position for internal junction
[in] visibility Custom foe visiblity connection
[in] speed Custom speed
[in] customShape Custom shape
[in] warnOnly Whether a failure to set this connection should only result in a warning
Definition at line 857 of file NBEdgeCont.cpp.
References myConnections.
Referenced by NIXMLConnectionsHandler::parseLaneBound(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), and wasRemoved().
addRoundabout()
void NBEdgeCont::addRoundabout (const EdgeSet & roundabout)
add user specified roundabout
Definition at line 1058 of file NBEdgeCont.cpp.
References myRoundabouts, toString(), and WRITE_WARNING.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLEdgesHandler::addRoundabout(), and wasRemoved().
appendTurnarounds() [1/2]
void NBEdgeCont::appendTurnarounds (bool noTLSControlled)
Appends turnarounds to all edges stored in the container.
Calls "NBEdge::appendTurnaround" for all edges within the container.
Parameters
[in] noTLSControlled Whether the turnaround shall not be connected if the edge is controlled by a tls
Todo:
Recheck whether a visitor-pattern should be used herefor
See also
NBEdge::appendTurnaround
Definition at line 680 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
appendTurnarounds() [2/2]
void NBEdgeCont::appendTurnarounds (const std::set< std::string > & ids, bool noTLSControlled)
Appends turnarounds to all edges stored in the container Calls "NBEdge::appendTurnaround" for edges with the given ids.
Parameters
[in] ids The list of ids for which to append a turnaround
[in] noTLSControlled Whether the turnaround shall not be connected if the edge is controlled by a tls
See also
NBEdge::appendTurnaround
Definition at line 688 of file NBEdgeCont.cpp.
References myEdges.
applyOptions()
void NBEdgeCont::applyOptions (OptionsCont & oc)
Initialises the storage by applying given options.
Options, mainly steering the acceptance of edges, are parsed and the according internal variables are set.
Parameters
[in] oc The options container to read options from
Todo:
Recheck exceptions
Definition at line 77 of file NBEdgeCont.cpp.
References TplConvert::_2double(), OptionsCont::exists(), OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getString(), OptionsCont::getStringVector(), OptionsCont::isSet(), NBHelpers::loadEdgesFromFile(), myEdges2Keep, myEdges2Remove, myEdgesMinSpeed, myNeedGeoTransformedPruningBoundary, myPruningBoundary, myRemoveEdgesAfterJoining, myTypes2Keep, myTypes2Remove, myVehicleClasses2Keep, myVehicleClasses2Remove, and parseVehicleClasses().
Referenced by NBNetBuilder::applyOptions().
begin()
std::map<std::string, NBEdge*>::const_iterator NBEdgeCont::begin () const inline
Returns the pointer to the begin of the stored edges.
Returns
The iterator to the beginning of stored edges
Definition at line 190 of file NBEdgeCont.h.
References myEdges.
Referenced by NBNetBuilder::compute(), NBNetBuilder::mirrorX(), NBNetBuilder::moveToOrigin(), NBNodeCont::removeComponents(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_SUMO::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_XML::writeStreetSigns(), and NWWriter_XML::writeTrafficLights().
checkGeometries()
void NBEdgeCont::checkGeometries (const double maxAngle, const double minRadius, bool fix)
Parameters
[in] maxAngle The maximum geometry angle allowed
[in] minRadius The minimum turning radius allowed at the start and end
[in] fix Whether to prune geometry points to avoid sharp turns at start and end
See also
NBEdge::checkGeometry
Definition at line 597 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
checkGrade()
void NBEdgeCont::checkGrade (double threshold) const
check whether edges are to steep
Definition at line 1227 of file NBEdgeCont.cpp.
References NBEdge::getConnections(), NBEdge::Connection::getDescription(), Named::getID(), NBEdge::getLaneShape(), PositionVector::getMaxGrade(), NBEdge::getNumLanes(), MAX2(), myEdges, NBEdge::Connection::shape, toString(), NBEdge::Connection::viaShape, and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and wasRemoved().
checkOverlap()
void NBEdgeCont::checkOverlap (double threshold, double zThreshold) const
check whether edges overlap
Definition at line 1198 of file NBEdgeCont.cpp.
References PositionVector::append(), PositionVector::getBoxBoundary(), NBEdge::getCCWBoundaryLine(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), PositionVector::getOverlapWith(), NBEdge::getToNode(), NBEdge::getTotalWidth(), Boundary::grow(), myEdges, Boundary::overlapsWith(), toString(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and wasRemoved().
clear()
void NBEdgeCont::clear ()
Deletes all edges.
Definition at line 142 of file NBEdgeCont.cpp.
References myEdges, and myExtractedEdges.
Referenced by ~NBEdgeCont().
clearControllingTLInformation()
void NBEdgeCont::clearControllingTLInformation () const
Clears information about controlling traffic lights for all connenections of all edges.
Definition at line 608 of file NBEdgeCont.cpp.
References myEdges.
Referenced by getNoEdgeSplits(), and NBTrafficLightLogicCont::setTLControllingInformation().
computeEdge2Edges()
void NBEdgeCont::computeEdge2Edges (bool noLeftMovers)
Computes for each edge the approached edges.
Calls "NBEdge::computeEdge2Edges" for all edges within the container.
Parameters
[in] noLeftMovers Whether left-moving connections shall be omitted
Todo:
Recheck whether a visitor-pattern should be used herefor
See also
NBEdge::computeEdge2Edges
Definition at line 624 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
computeEdgeShapes()
void NBEdgeCont::computeEdgeShapes ()
Computes the shapes of all edges stored in the container.
Calls "NBEdge::computeEdgeShape" for all edges within the container.
Todo:
Recheck whether a visitor-pattern should be used herefor
Recheck usage
See also
NBEdge::computeEdgeShape
Definition at line 696 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
computeLanes2Edges()
void NBEdgeCont::computeLanes2Edges ()
Computes for each edge which lanes approach the next edges.
Calls "NBEdge::computeLanes2Edges" for all edges within the container.
Todo:
Recheck whether a visitor-pattern should be used herefor
See also
NBEdge::computeLanes2Edges
Definition at line 632 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
computeLaneShapes()
void NBEdgeCont::computeLaneShapes ()
Computes the shapes of all lanes of all edges stored in the container.
Calls "NBEdge::computeLaneShapes" for all edges within the container.
Todo:
Recheck whether a visitor-pattern should be used herefor
Recheck usage
See also
NBEdge::computeLaneShapes
Definition at line 704 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
end()
std::map<std::string, NBEdge*>::const_iterator NBEdgeCont::end () const inline
Returns the pointer to the end of the stored edges.
Returns
The iterator to the end of stored edges
Definition at line 198 of file NBEdgeCont.h.
References myEdges, and splitAt().
Referenced by NBNetBuilder::compute(), NBNetBuilder::mirrorX(), NBNetBuilder::moveToOrigin(), NBNodeCont::removeComponents(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_SUMO::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_XML::writeStreetSigns(), and NWWriter_XML::writeTrafficLights().
erase()
void NBEdgeCont::erase (NBDistrictCont & dc, NBEdge * edge)
Removes the given edge from the container (deleting it)
Parameters
[in] dc The district container, in order to remove the edge from sources/sinks
[in] edge The edge to remove
Todo:
Recheck whether the district cont is needed - if districts are processed using an external tool
Definition at line 384 of file NBEdgeCont.cpp.
References extract().
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLEdgesHandler::addEdge(), NBNodeCont::removeComponents(), NBNodeCont::removeIsolatedRoads(), NBNode::removeSelfLoops(), removeUnwishedEdges(), and splitAt().
extract()
void NBEdgeCont::extract (NBDistrictCont & dc, NBEdge * edge, bool remember = false)
Removes the given edge from the container like erase but does not delete it.
Parameters
[in] dc The district container, in order to remove the edge from sources/sinks
[in] edge The edge to remove
[in] remember Whether to keep this edge for future reference
Todo:
Recheck whether the district cont is needed - if districts are processed using an external tool
Recheck whether this is used at all and why
Definition at line 391 of file NBEdgeCont.cpp.
References Named::getID(), myEdges, myExtractedEdges, NBEdge::myFrom, NBEdge::myTo, NBNode::removeEdge(), and NBDistrictCont::removeFromSinksAndSources().
Referenced by NIXMLEdgesHandler::deleteEdge(), GNENet::deleteSingleEdge(), erase(), NBNodeCont::joinNodeClusters(), joinSameNodeConnectingEdges(), NBNodeCont::removeUnwishedNodes(), and NIImporter_DlrNavteq::TimeRestrictionsHandler::report().
formFactor()
double NBEdgeCont::formFactor (const EdgeVector & loopEdges) static private
compute the form factor for a loop of edges
Definition at line 1039 of file NBEdgeCont.cpp.
References PositionVector::append(), PositionVector::area(), PositionVector::length2D(), and M_PI.
Referenced by guessRoundabouts(), and wasRemoved().
generateStreetSigns()
void NBEdgeCont::generateStreetSigns ()
assigns street signs to edges based on toNode types
Definition at line 1097 of file NBEdgeCont.cpp.
References NBEdge::addSign(), NBEdge::getJunctionPriority(), NBEdge::getLength(), NBEdge::getToNode(), NBNode::getType(), NBNode::isSimpleContinuation(), MAX2(), myEdges, NODETYPE_ALLWAY_STOP, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RIGHT_BEFORE_LEFT, NBSign::SIGN_TYPE_ALLWAY_STOP, NBSign::SIGN_TYPE_PRIORITY, NBSign::SIGN_TYPE_RIGHT_BEFORE_LEFT, NBSign::SIGN_TYPE_STOP, and NBSign::SIGN_TYPE_YIELD.
Referenced by NBNetBuilder::compute(), and wasRemoved().
getAllNames()
std::vector< std::string > NBEdgeCont::getAllNames () const
Returns all ids of known edges.
Returns
All ids of known edges
Todo:
Recheck usage, probably, filling a given vector would be better...
Definition at line 550 of file NBEdgeCont.cpp.
References myEdges.
Referenced by GNENet::initJunctionsAndEdges(), remapIDs(), NBNodeCont::removeIsolatedRoads(), size(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeProhibitedManoeuvres().
getByID()
NBEdge * NBEdgeCont::getByID (const std::string & edgeID) const
Returns the edge with id if it exists.
Definition at line 850 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), NBPTStop::findLaneAndComputeBusStopExtend(), getNoEdgeSplits(), NBPTStopCont::getReverseStop(), NBPTStopCont::reviseStops(), and NBPTLineCont::reviseStops().
getGeneratedFrom()
EdgeVector NBEdgeCont::getGeneratedFrom (const std::string & id) const
Returns the edges which have been built by splitting the edge of the given id.
Parameters
[in] id The id of the original edge
Returns
List of all edges which have been built by splitting the original edge
Todo:
Recheck usage
Definition at line 901 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBPTStopCont::assignLanes(), retrievePossiblySplit(), and wasRemoved().
getNoEdgeSplits()
int NBEdgeCont::getNoEdgeSplits () const inline
Returns the number of edge splits.
Returns
How often an edge was split
Definition at line 297 of file NBEdgeCont.h.
References appendTurnarounds(), checkGeometries(), clearControllingTLInformation(), computeEdge2Edges(), computeEdgeShapes(), computeLanes2Edges(), computeLaneShapes(), getByID(), getOppositeByID(), guessOpposites(), guessRoundabouts(), joinSameNodeConnectingEdges(), myEdgesSplit, recheckLanes(), recheckLaneSpread(), reduceGeometries(), removeUnwishedEdges(), sortOutgoingLanesConnections(), and splitGeometry().
Referenced by NILoader::load().
getOppositeByID()
NBEdge * NBEdgeCont::getOppositeByID (const std::string & edgeID) const
Returns the edge with negated id if it exists.
Definition at line 843 of file NBEdgeCont.cpp.
References myEdges.
Referenced by getNoEdgeSplits(), recheckLaneSpread(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
getRoundabouts()
const std::set< EdgeSet > NBEdgeCont::getRoundabouts () const
Returns the determined roundabouts.
Returns
The list of roundabout edges
Definition at line 1050 of file NBEdgeCont.cpp.
References myGuessedRoundabouts, and myRoundabouts.
Referenced by NBNetBuilder::compute(), NBRampsComputer::computeRamps(), markRoundabouts(), wasRemoved(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_Amitran::writeNetwork(), and NWWriter_SUMO::writeNetwork().
guessOpposites()
void NBEdgeCont::guessOpposites ()
Sets opposite lane information for geometrically close edges.
Definition at line 799 of file NBEdgeCont.cpp.
References PositionVector::distances(), NBEdge::getFromNode(), NBEdge::getLaneID(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), NBNode::getOutgoingEdges(), NBEdge::getToNode(), VectorHelper< T >::maxValue(), myEdges, NBEdge::Lane::oppositeID, and NBEdge::Lane::shape.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
guessRoundabouts()
int NBEdgeCont::guessRoundabouts ()
Determines which edges belong to roundabouts and increases their priority.
Parameters
[out] marked Edges which belong to a roundabout are stored here
Returns
The number of guessed roundabouts
Definition at line 943 of file NBEdgeCont.cpp.
References formFactor(), NBEdge::getAngleAtNode(), NBNode::getConnectionTo(), NBNode::getEdges(), NBEdge::getFromNode(), NBEdge::getToNode(), NBEdge::getTurnDestination(), myEdges, myGuessedRoundabouts, myRoundabouts, NBContHelper::nextCW(), and NBHelpers::relAngle().
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
guessSidewalks()
int NBEdgeCont::guessSidewalks (double width, double minSpeed, double maxSpeed, bool fromPermissions)
add sidwalks to edges within the given limits or permissions and return the number of edges affected
Definition at line 1137 of file NBEdgeCont.cpp.
References NBEdge::addSidewalk(), Named::getID(), OptionsCont::getOptions(), NBEdge::getPermissions(), NBEdge::getSpeed(), OptionsCont::getStringVector(), myEdges, and SVC_PEDESTRIAN.
Referenced by NBNetBuilder::compute(), and wasRemoved().
ignore()
void NBEdgeCont::ignore (std::string id) inline
mark the given edge id as ignored
Definition at line 479 of file NBEdgeCont.h.
References myIgnoredEdges.
Referenced by NIImporter_SUMO::_loadNetwork().
ignoreFilterMatch()
bool NBEdgeCont::ignoreFilterMatch (NBEdge * edge)
Returns true if this edge matches one of the removal criteria.
Definition at line 178 of file NBEdgeCont.cpp.
References PositionVector::getBoxBoundary(), NBEdge::getGeometry(), Named::getID(), GeoConvHelper::getLoaded(), NBEdge::getPermissions(), GeoConvHelper::getProcessing(), NBTypeCont::getShallBeDiscarded(), NBEdge::getSpeed(), NBEdge::getTypeID(), Boundary::grow(), NBTypeCont::knows(), myEdges2Keep, myEdges2Remove, myEdgesMinSpeed, myNeedGeoTransformedPruningBoundary, myPruningBoundary, myRemoveEdgesAfterJoining, myTypeCont, myTypes2Keep, myTypes2Remove, myVehicleClasses2Keep, myVehicleClasses2Remove, Boundary::overlapsWith(), POSITION_EPS, NBNetBuilder::transformCoordinates(), GeoConvHelper::usingGeoProjection(), WRITE_ERROR, and GeoConvHelper::x2cartesian_const().
Referenced by NIImporter_SUMO::_loadNetwork(), insert(), and wasRemoved().
insert()
bool NBEdgeCont::insert (NBEdge * edge, bool ignorePrunning = false)
Adds an edge to the dictionary.
First, it is determined whether the edge shall not be discarded due to any reasons (being outside a boundary, or not in the optional list of edges to import, etc.). If so, the edge is deleted and "true" is returned. "true" is also returned if the edge is accepted - no edge with the same name exists within this container. If another edge with the same name exists, false is returned.
Parameters
[in] edge The edge to add
[in] ignorePrunning Whether this edge must not be prunned
Returns
Whether the edge was valid (no edge with the same id is already known)
Definition at line 157 of file NBEdgeCont.cpp.
References NBEdge::dismissVehicleClassInformation(), OptionsCont::exists(), OptionsCont::getBool(), NBEdge::getFromNode(), Named::getID(), OptionsCont::getOptions(), NBEdge::getToNode(), ignoreFilterMatch(), myEdges, myIgnoredEdges, and NBNode::removeEdge().
Referenced by NIImporter_SUMO::_loadNetwork(), NIVissimEdge::buildNBEdge(), NIVissimDistrictConnection::dict_BuildDistricts(), NIImporter_OpenStreetMap::insertEdge(), GNENet::insertEdge(), joinSameNodeConnectingEdges(), NIImporter_ArcView::load(), NIImporter_RobocupRescue::loadEdges(), NIImporter_OpenDrive::loadNetwork(), NIXMLEdgesHandler::myEndElement(), NIImporter_ITSUMO::Handler::myEndElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_Edges(), NIImporter_DlrNavteq::EdgesHandler::report(), splitAt(), NBEdge::splitGeometry(), and NGNet::toNB().
joinSameNodeConnectingEdges()
void NBEdgeCont::joinSameNodeConnectingEdges (NBDistrictCont & dc, NBTrafficLightLogicCont & tlc, EdgeVector edges)
Joins the given edges because they connect the same nodes.
Parameters
[in] dc The district container needed to remove edges
[in] tlc The tls container needed to remove edges
[in] edges The edges to join
Todo:
Recheck and describe usage
Definition at line 712 of file NBEdgeCont.cpp.
References NBEdge::addEdge2EdgeConnection(), extract(), Named::getID(), NBEdge::getLanes(), insert(), MAX2(), NBEdge::moveOutgoingConnectionsFrom(), NBNode::replaceIncoming(), NBNode::replaceOutgoing(), NBTrafficLightLogicCont::replaceRemoved(), NBEdge::setEndOffset(), NBEdge::setLaneWidth(), NBEdge::setPermissions(), NBEdge::UNSPECIFIED_OFFSET, and NBEdge::UNSPECIFIED_WIDTH.
Referenced by getNoEdgeSplits(), and NBNodeCont::joinSimilarEdges().
markRoundabouts()
void NBEdgeCont::markRoundabouts ()
mark edge priorities and prohibit turn-arounds for all roundabout edges
Definition at line 1070 of file NBEdgeCont.cpp.
References NBNode::getIncomingEdges(), getRoundabouts(), NBEdge::getTurnDestination(), NBEdge::LANES2LANES_USER, NBEdge::removeFromConnections(), NBEdge::ROUNDABOUT, and NBNode::setRoundabout().
Referenced by NBNetBuilder::compute(), and wasRemoved().
operator=()
NBEdgeCont& NBEdgeCont::operator= (const NBEdgeCont & s) private
invalidated assignment operator
patchRoundabouts()
void NBEdgeCont::patchRoundabouts (NBEdge * orig, NBEdge * part1, NBEdge * part2, std::set< EdgeSet > & roundabouts)
fix roundabout information after splitting an edge
Definition at line 532 of file NBEdgeCont.cpp.
Referenced by splitAt(), and wasRemoved().
recheckLanes()
void NBEdgeCont::recheckLanes ()
Rechecks whether all lanes have a successor for each of the stored edges.
Calls "NBEdge::recheckLanes" for all edges within the container.
Todo:
Recheck whether a visitor-pattern should be used herefor
See also
NBEdge::recheckLanes
Definition at line 640 of file NBEdgeCont.cpp.
References OptionsCont::getBool(), NBEdge::getFinalLength(), NBEdge::getFromNode(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLanes(), NBEdge::getLaneStruct(), NBEdge::getLoadedLength(), NBEdge::getNumLanes(), OptionsCont::getOptions(), NBEdge::getToNode(), myEdges, POSITION_EPS, NBEdge::recheckLanes(), retrieve(), NBEdge::setLoadedLength(), toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
recheckLaneSpread()
void NBEdgeCont::recheckLaneSpread ()
Rechecks whether the lane spread is proper.
Todo:
Recheck usage; check whether this is really needed and whether it works at all
Definition at line 829 of file NBEdgeCont.cpp.
References getOppositeByID(), LANESPREAD_CENTER, LANESPREAD_RIGHT, myEdges, and NBEdge::setLaneSpreadFunction().
Referenced by getNoEdgeSplits(), and NIImporter_DlrNavteq::loadNetwork().
recheckPostProcessConnections()
void NBEdgeCont::recheckPostProcessConnections ()
Try to set any stored connections.
Definition at line 865 of file NBEdgeCont.cpp.
References NBEdge::addLane2LaneConnection(), OptionsCont::exists(), OptionsCont::getBool(), NBEdge::getConnections(), NBEdge::getFromNode(), Named::getID(), OptionsCont::getOptions(), NBEdge::getToNode(), NBEdge::L2L_USER, myConnections, myEdges, NBEdge::removeFromConnections(), retrievePossiblySplit(), NBEdge::Connection::toEdge, WRITE_ERROR, and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and wasRemoved().
reduceGeometries()
void NBEdgeCont::reduceGeometries (const double minDist)
Parameters
[in] nc The node container needed to build (geometry) nodes
See also
NBEdge::reduceGeometry
Definition at line 589 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
remapIDs()
int NBEdgeCont::remapIDs (bool numericaIDs, bool reservedIDs)
remap node IDs accoring to options –numerical-ids and –reserved-ids
Definition at line 1162 of file NBEdgeCont.cpp.
References TplConvert::_str2long(), getAllNames(), OptionsCont::getBool(), Named::getID(), IDSupplier::getNext(), OptionsCont::getOptions(), NBHelpers::loadPrefixedIDsFomFile(), myEdges, Named::setID(), and NBEdge::setOrigID().
Referenced by NBNetBuilder::compute(), and wasRemoved().
removeUnwishedEdges()
void NBEdgeCont::removeUnwishedEdges (NBDistrictCont & dc)
Removes unwished edges (not in keep-edges)
Parameters
Definition at line 561 of file NBEdgeCont.cpp.
References erase(), NBEdge::getFromNode(), Named::getID(), NBEdge::getToNode(), myEdges, myEdges2Keep, and NBNode::removeEdge().
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
rename()
void NBEdgeCont::rename (NBEdge * edge, const std::string & newID)
Renames the edge. Throws exception if newID already exists.
Definition at line 403 of file NBEdgeCont.cpp.
References Named::getID(), myEdges, and Named::setID().
Referenced by GNENet::renameEdge(), and wasRemoved().
retrieve()
NBEdge * NBEdgeCont::retrieve (const std::string & id, bool retrieveExtracted = false) const
Returns the edge that has the given id.
If no edge that has the given id is known, 0 is returned.
Parameters
[in] id The id of the edge to retrieve
[in] bool Whether extracted edges shall be retrieved as well
Returns
The edge with the given id, 0 if no such edge exists
Definition at line 250 of file NBEdgeCont.cpp.
References myEdges, and myExtractedEdges.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLConnectionsHandler::addCrossing(), NIXMLEdgesHandler::addEdge(), NIXMLEdgesHandler::addRoundabout(), NIVissimDisturbance::addToNode(), NIXMLConnectionsHandler::addWalkingArea(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NBConnection::checkFrom(), NBConnection::checkTo(), NBRampsComputer::computeRamps(), NBPTLineCont::constructRoute(), NIXMLEdgesHandler::deleteEdge(), NIVissimDistrictConnection::dict_BuildDistricts(), NIImporter_VISUM::getNamedEdge(), NIImporter_VISUM::getNamedEdgeContinuating(), NWWriter_SUMO::getOppositeInternalID(), NIImporter_VISUM::getReversedContinuating(), GNENet::initJunctionsAndEdges(), NBNodeCont::joinJunctions(), NIImporter_ArcView::load(), NIImporter_OpenDrive::loadNetwork(), NIXMLEdgesHandler::myEndElement(), NIXMLConnectionsHandler::myStartElement(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_Edges(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseConnection(), recheckLanes(), NBNodeCont::removeIsolatedRoads(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::TimeRestrictionsHandler::report(), NIImporter_DlrNavteq::ProhibitionHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), NIXMLTrafficLightsHandler::retrieveEdge(), retrievePossiblySplit(), NBPTLine::write(), NBParking::write(), and NWWriter_SUMO::writeRoundabout().
retrievePossiblySplit() [1/3]
NBEdge * NBEdgeCont::retrievePossiblySplit (const std::string & id, bool downstream) const
Tries to retrieve an edge, even if it is splitted.
The edge given with the id should exist and is followed downstream or upstream, depending on the parameter to the last edge still starting with the id.
Parameters
[in] id The id of the edge to retrieve
[in] downstream search direction
Returns
The searched edge
Todo:
Recheck usage
Definition at line 286 of file NBEdgeCont.cpp.
References retrieve().
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), NIVissimDisturbance::addToNode(), NIVissimConnection::buildEdgeConnections(), NBConnection::checkFrom(), NBConnection::checkTo(), NIVissimDistrictConnection::dict_BuildDistricts(), recheckPostProcessConnections(), and NIVissimConflictArea::setPriorityRegulation().
retrievePossiblySplit() [2/3]
NBEdge * NBEdgeCont::retrievePossiblySplit (const std::string & id, const std::string & hint, bool incoming) const
Tries to retrieve an edge, even if it is splitted.
To describe which part of the edge shall be returned, the id of a second edge, participating at the node and the information whether to return the outgoing or the incoming is needed.
Parameters
[in] id The id of the edge to retrieve
[in] hint An additional information which helps to retrieve the correct edge
[in] incoming Whether the edge to find is an incoming edge at the node "hint" participates
Returns
The searched edge
Todo:
Recheck usage
Definition at line 305 of file NBEdgeCont.cpp.
References getGeneratedFrom(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), NBEdge::myFrom, NBEdge::myTo, and retrieve().
retrievePossiblySplit() [3/3]
NBEdge * NBEdgeCont::retrievePossiblySplit (const std::string & id, double pos) const
Tries to retrieve an edge, even if it is splitted.
To describe which part of the edge shall be returned, a position hint is supplied.
Parameters
[in] id The id of the edge to retrieve
[in] pos An additional about the position of the basic edge's subpart
Returns
The searched edge
Todo:
Recheck usage
Definition at line 339 of file NBEdgeCont.cpp.
References NBEdge::getLength(), MAX2(), myEdges, and retrieve().
size()
int NBEdgeCont::size () const inline
Returns the number of edges.
Returns
The number of edges stored in this container
Definition at line 282 of file NBEdgeCont.h.
References getAllNames(), and myEdges.
Referenced by NILoader::load(), and main().
sortOutgoingLanesConnections()
void NBEdgeCont::sortOutgoingLanesConnections ()
Sorts all lanes of all edges within the container by their direction.
Calls "NBEdge::sortOutgoingLanesConnections" for all edges within the container.
Todo:
Recheck whether a visitor-pattern should be used herefor
See also
NBEdge::sortOutgoingLanesConnections
Definition at line 616 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
splitAt() [1/3]
bool NBEdgeCont::splitAt (NBDistrictCont & dc, NBEdge * edge, NBNode * node)
Splits the edge at the position nearest to the given node.
Uses "splitAt(NBDistrictCont &, NBEdge *, NBNode *, const std::string &, const std::string &, int , int)" to perform the split; the edge names are built by appending "[0]" and "[1]", respectively. Both edges will have the same number of lanes.
Parameters
[in] dc The district container, in order to remove/add the edge from/to sources/sinks
[in] edge The edge to split
[in] node The node to split the edge at
Returns
Whether the edge could be split
Exceptions
ProcessError If connections between the edges can not be built
See also
NBEdge::splitAt(NBDistrictCont &, NBEdge *, NBNode *, const std::string &, const std::string &, int , int)
Definition at line 415 of file NBEdgeCont.cpp.
References Named::getID(), and NBEdge::myLanes.
Referenced by NIVissimDisturbance::addToNode(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), end(), NIXMLEdgesHandler::myEndElement(), NIImporter_VISUM::parse_Lanes(), and splitAt().
splitAt() [2/3]
bool NBEdgeCont::splitAt (NBDistrictCont & dc, NBEdge * edge, NBNode * node, const std::string & firstEdgeName, const std::string & secondEdgeName, int noLanesFirstEdge, int noLanesSecondEdge, const double speed = -1., const int changedLeft = 0)
Splits the edge at the position nearest to the given node using the given modifications.
Determines the position of the split by finding the nearest position on the edge to the given node. If this position is too near to the edges begin/end, false is returned.
Otherwise, "splitAt(NBDistrictCont &, NBEdge *, double, NBNode *, const std::string &, const std::string &, int , int)" is used to perform the split.
Parameters
[in] dc The district container, in order to remove/add the edge from/to sources/sinks
[in] edge The edge to split
[in] node The node to split the edge at
[in] firstEdgeName The id the first part of the split edge shall have
[in] secondEdgeName The id the second part of the split edge shall have
[in] noLanesFirstEdge The number of lanes the second part of the split edge shall have
[in] noLanesSecondEdge The number of lanes the second part of the split edge shall have
[in] speed The speed for the edge after the split
[in] changedLeft The number of lanes that is added or removed on the left side of the edge (By default all added/removed lanes are assumed to be on the right when computing connections)
Returns
Whether the edge could be split
Exceptions
ProcessError If connections between the edges can not be built
See also
NBEdge::splitAt(NBDistrictCont &, NBEdge *, double, NBNode *, const std::string &, const std::string &, int , int)
Definition at line 422 of file NBEdgeCont.cpp.
References NBEdge::getGeometry(), NBNode::getPosition(), PositionVector::length(), NBEdge::myFrom, NBEdge::myTo, GeomHelper::nearest_offset_on_line_to_point2D(), PositionVector::nearest_offset_to_point2D(), and splitAt().
splitAt() [3/3]
bool NBEdgeCont::splitAt (NBDistrictCont & dc, NBEdge * edge, double edgepos, NBNode * node, const std::string & firstEdgeName, const std::string & secondEdgeName, int noLanesFirstEdge, int noLanesSecondEdge, const double speed = -1., const int changedLeft = 0)
Splits the edge at the position nearest to the given node using the given modifications.
Parameters
[in] dc The district container, in order to remove/add the edge from/to sources/sinks
[in] edge The edge to split
[in] node The node to split the edge at
[in] firstEdgeName The id the first part of the split edge shall have
[in] secondEdgeName The id the second part of the split edge shall have
[in] noLanesFirstEdge The number of lanes the second part of the split edge shall have
[in] noLanesSecondEdge The number of lanes the second part of the split edge shall have
[in] speed The speed for the edge after the split
[in] changedLeft The number of lanes that is added or removed on the left side of the edge (By default all added/removed lanes are assumed to be on the right when computing connections)
Returns
Whether the edge could be split
Exceptions
ProcessError If connections between the edges can not be built
Definition at line 444 of file NBEdgeCont.cpp.
References NBEdge::addLane2LaneConnection(), NBEdge::copyConnectionsFrom(), erase(), NBNode::getControllingTLS(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), OptionsCont::getOptions(), Parameterised::getParameter(), NBNode::getPosition(), insert(), NBEdge::L2L_COMPUTED, MAX2(), MIN2(), myEdges2Keep, myEdges2Remove, myEdgesSplit, NBEdge::myFrom, myGuessedRoundabouts, myRemoveEdgesAfterJoining, myRoundabouts, NBEdge::myTo, patchRoundabouts(), NBNode::removeDoubleEdges(), NBNode::replaceIncoming(), NBNode::replaceOutgoing(), NBEdge::setOrigID(), NBEdge::setSpeed(), PositionVector::splitAt(), and SUMO_PARAM_ORIGID.
splitGeometry()
void NBEdgeCont::splitGeometry (NBNodeCont & nc)
Splits edges into multiple if they have a complex geometry.
Calls "NBEdge::splitGeometry" for all edges within the container which have more than three positions in their geometry.
Parameters
[in] nc The node container needed to build (geometry) nodes
See also
NBEdge::splitGeometry
Definition at line 578 of file NBEdgeCont.cpp.
References myEdges.
Referenced by NBNetBuilder::compute(), and getNoEdgeSplits().
wasIgnored()
bool NBEdgeCont::wasIgnored (std::string id) const inline
Returns whether the edge with the id was ignored during parsing.
Returns
Whether the edge with the id was ignored during parsing
Definition at line 474 of file NBEdgeCont.h.
References myIgnoredEdges.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLEdgesHandler::addRoundabout(), NIImporter_OpenDrive::loadNetwork(), and NIXMLConnectionsHandler::myStartElement().
wasRemoved()
bool NBEdgeCont::wasRemoved (std::string id) const inline
Returns whether the edge with the id was deleted explicitly.
Definition at line 485 of file NBEdgeCont.h.
References addPostProcessConnection(), addRoundabout(), checkGrade(), checkOverlap(), formFactor(), generateStreetSigns(), getGeneratedFrom(), getRoundabouts(), guessSidewalks(), ignoreFilterMatch(), markRoundabouts(), myExtractedEdges, patchRoundabouts(), recheckPostProcessConnections(), remapIDs(), and rename().
Referenced by NIXMLConnectionsHandler::myStartElement().
Field Documentation
myConnections
std::vector<PostProcessConnection> NBEdgeCont::myConnections private
The list of connections to recheck.
Definition at line 619 of file NBEdgeCont.h.
Referenced by addPostProcessConnection(), and recheckPostProcessConnections().
myEdges
EdgeCont NBEdgeCont::myEdges private
The instance of the dictionary (id->edge)
Definition at line 626 of file NBEdgeCont.h.
Referenced by appendTurnarounds(), begin(), checkGeometries(), checkGrade(), checkOverlap(), clear(), clearControllingTLInformation(), computeEdge2Edges(), computeEdgeShapes(), computeLanes2Edges(), computeLaneShapes(), end(), extract(), generateStreetSigns(), getAllNames(), getByID(), getGeneratedFrom(), getOppositeByID(), guessOpposites(), guessRoundabouts(), guessSidewalks(), insert(), recheckLanes(), recheckLaneSpread(), recheckPostProcessConnections(), reduceGeometries(), remapIDs(), removeUnwishedEdges(), rename(), retrieve(), retrievePossiblySplit(), size(), sortOutgoingLanesConnections(), and splitGeometry().
myEdges2Keep
std::set<std::string> NBEdgeCont::myEdges2Keep private
Set of ids of edges which shall explicitly be kept.
Definition at line 647 of file NBEdgeCont.h.
Referenced by applyOptions(), ignoreFilterMatch(), removeUnwishedEdges(), and splitAt().
myEdges2Remove
std::set<std::string> NBEdgeCont::myEdges2Remove private
Set of ids of edges which shall explicitly be removed.
Definition at line 650 of file NBEdgeCont.h.
Referenced by applyOptions(), ignoreFilterMatch(), and splitAt().
myEdgesMinSpeed
double NBEdgeCont::myEdgesMinSpeed private
The minimum speed an edge may have in order to be kept (default: -1)
Definition at line 641 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
myEdgesSplit
int NBEdgeCont::myEdgesSplit private
the number of splits of edges during the building
Definition at line 635 of file NBEdgeCont.h.
Referenced by getNoEdgeSplits(), and splitAt().
myExtractedEdges
EdgeCont NBEdgeCont::myExtractedEdges private
The extracted nodes which are kept for reference.
Definition at line 629 of file NBEdgeCont.h.
Referenced by clear(), extract(), retrieve(), and wasRemoved().
myGuessedRoundabouts
std::set<EdgeSet> NBEdgeCont::myGuessedRoundabouts private
Edges marked as belonging to a roundabout after guessing.
Definition at line 674 of file NBEdgeCont.h.
Referenced by getRoundabouts(), guessRoundabouts(), and splitAt().
myIgnoredEdges
std::set<std::string> NBEdgeCont::myIgnoredEdges private
The ids of ignored edges.
Definition at line 632 of file NBEdgeCont.h.
Referenced by ignore(), insert(), and wasIgnored().
myNeedGeoTransformedPruningBoundary
bool NBEdgeCont::myNeedGeoTransformedPruningBoundary private
whether a geo transform has been applied to the pruning boundary
Definition at line 668 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
myPruningBoundary
PositionVector NBEdgeCont::myPruningBoundary private
Boundary within which an edge must be located in order to be kept.
Definition at line 665 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
myRemoveEdgesAfterJoining
bool NBEdgeCont::myRemoveEdgesAfterJoining private
Whether edges shall be joined first, then removed.
Definition at line 644 of file NBEdgeCont.h.
Referenced by applyOptions(), ignoreFilterMatch(), and splitAt().
myRoundabouts
std::set<EdgeSet> NBEdgeCont::myRoundabouts private
Edges marked as belonging to a roundabout by the user (each EdgeVector is a roundabout)
Definition at line 672 of file NBEdgeCont.h.
Referenced by addRoundabout(), getRoundabouts(), guessRoundabouts(), and splitAt().
myTypeCont
NBTypeCont& NBEdgeCont::myTypeCont private
The network builder; used to obtain type information.
Definition at line 570 of file NBEdgeCont.h.
Referenced by ignoreFilterMatch().
myTypes2Keep
std::set<std::string> NBEdgeCont::myTypes2Keep private
Set of edges types which shall be kept.
Definition at line 659 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
myTypes2Remove
std::set<std::string> NBEdgeCont::myTypes2Remove private
Set of edges types which shall be removed.
Definition at line 662 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
myVehicleClasses2Keep
SVCPermissions NBEdgeCont::myVehicleClasses2Keep private
Set of vehicle types which must be allowed on edges in order to keep them.
Definition at line 653 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
myVehicleClasses2Remove
SVCPermissions NBEdgeCont::myVehicleClasses2Remove private
Set of vehicle types which need not be supported (edges which allow ONLY these are removed)
Definition at line 656 of file NBEdgeCont.h.
Referenced by applyOptions(), and ignoreFilterMatch().
The documentation for this class was generated from the following files:
NBEdgeCont.h
NBEdgeCont.cpp