SUMO - Simulation of Urban MObility: SUMORouteLoader Class Reference
SUMORouteLoader Class Reference
#include <SUMORouteLoader.h>
Public Member Functions
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime loadUntil (SUMOTime time)
bool moreAvailable () const
returns the information whether new data is available
SUMORouteLoader (SUMORouteHandler *handler)
constructor
~SUMORouteLoader ()
destructor
Private Attributes
SUMORouteHandler * myHandler
the used Handler
bool myMoreAvailable
information whether more vehicles should be available
SUMOSAXReader * myParser
the used SAXReader
Detailed Description
Definition at line 49 of file SUMORouteLoader.h.
Constructor & Destructor Documentation
SUMORouteLoader()
SUMORouteLoader::SUMORouteLoader (SUMORouteHandler * handler)
constructor
Definition at line 39 of file SUMORouteLoader.cpp.
References GenericSAXHandler::getFileName(), XMLSubSys::getSAXReader(), myHandler, myParser, and SUMOSAXReader::parseFirst().
~SUMORouteLoader()
SUMORouteLoader::~SUMORouteLoader ()
destructor
Definition at line 48 of file SUMORouteLoader.cpp.
References myHandler, and myParser.
Member Function Documentation
getFirstDepart()
SUMOTime SUMORouteLoader::getFirstDepart () const
returns the first departure time that was ever read
Definition at line 82 of file SUMORouteLoader.cpp.
References SUMORouteHandler::getFirstDepart(), and myHandler.
loadUntil()
SUMOTime SUMORouteLoader::loadUntil (SUMOTime time)
loads vehicles until a vehicle is read that starts after the specified time
Definition at line 55 of file SUMORouteLoader.cpp.
References SUMORouteHandler::getLastDepart(), myHandler, myMoreAvailable, myParser, SUMOSAXReader::parseNext(), and SUMOTime_MAX.
moreAvailable()
bool SUMORouteLoader::moreAvailable () const
returns the information whether new data is available
Definition at line 76 of file SUMORouteLoader.cpp.
References myMoreAvailable.
Field Documentation
myHandler
SUMORouteHandler* SUMORouteLoader::myHandler private
the used Handler
Definition at line 75 of file SUMORouteLoader.h.
Referenced by getFirstDepart(), loadUntil(), SUMORouteLoader(), and ~SUMORouteLoader().
myMoreAvailable
bool SUMORouteLoader::myMoreAvailable private
information whether more vehicles should be available
Definition at line 72 of file SUMORouteLoader.h.
Referenced by loadUntil(), and moreAvailable().
myParser
SUMOSAXReader* SUMORouteLoader::myParser private
the used SAXReader
Definition at line 69 of file SUMORouteLoader.h.
Referenced by loadUntil(), SUMORouteLoader(), and ~SUMORouteLoader().
The documentation for this class was generated from the following files:
SUMORouteLoader.h
SUMORouteLoader.cpp