SUMO - Simulation of Urban MObility: ToString.h File Reference
ToString.h File Reference
#include <config.h>
#include <sstream>
#include <string>
#include <iomanip>
#include <algorithm>
#include <list>
#include <utils/xml/SUMOXMLDefinitions.h>
#include <utils/common/SUMOVehicleClass.h>
#include <utils/common/Named.h>
#include <utils/distribution/Distribution_Parameterized.h>
#include "StdDefs.h"
Functions
template<typename T , typename T_BETWEEN >
std::string joinToString (const std::vector< T > &v, const T_BETWEEN &between, std::streamsize accuracy=gPrecision)
template<typename T , typename T_BETWEEN >
std::string joinToString (const std::set< T > &s, const T_BETWEEN &between, std::streamsize accuracy=gPrecision)
template<typename KEY , typename VAL , typename T_BETWEEN , typename T_BETWEEN_KEYVAL >
std::string joinToString (const std::map< KEY, VAL > &s, const T_BETWEEN &between, const T_BETWEEN_KEYVAL &between_keyval, std::streamsize accuracy=gPrecision)
template<typename T , typename T_BETWEEN >
std::string joinToStringSorting (const std::vector< T > &v, const T_BETWEEN &between, std::streamsize accuracy=gPrecision)
template<typename T >
std::string toHex (const T i, std::streamsize numDigits=0)
template<class T >
std::string toString (const T &t, std::streamsize accuracy=gPrecision)
std::string toString (const Named *obj, std::streamsize accuracy)
template<typename V >
std::string toString (const std::vector< V *> &v, std::streamsize accuracy=gPrecision)
template<typename V >
std::string toString (const typename std::vector< V *>::const_iterator &b, const typename std::vector< V *>::const_iterator &e, std::streamsize accuracy=gPrecision)
template<typename V >
std::string toString (const std::list< V *> &v, std::streamsize accuracy=gPrecision)
template<typename V >
std::string toString (const typename std::list< V *>::const_iterator &b, const typename std::list< V *>::const_iterator &e, std::streamsize accuracy=gPrecision)
template<typename V >
std::string toString (const std::set< V *> &v, std::streamsize accuracy=gPrecision)
template<>
std::string toString (const std::vector< int > &v, std::streamsize accuracy)
template<>
std::string toString (const std::vector< long long int > &v, std::streamsize accuracy)
template<>
std::string toString (const std::vector< double > &v, std::streamsize accuracy)
template<>
std::string toString (const std::vector< std::string > &v, std::streamsize)
template<>
std::string toString (const std::set< std::string > &v, std::streamsize)
template<>
std::string toString (const std::map< std::string, std::string > &v, std::streamsize)
template<>
std::string toString< Distribution_Parameterized > (const Distribution_Parameterized &dist, std::streamsize accuracy)
template<>
std::string toString< LaneChangeAction > (const LaneChangeAction &action, std::streamsize accuracy)
template<>
std::string toString< LaneChangeModel > (const LaneChangeModel &model, std::streamsize accuracy)
template<>
std::string toString< LaneSpreadFunction > (const LaneSpreadFunction &lsf, std::streamsize accuracy)
template<>
std::string toString< LateralAlignment > (const LateralAlignment &latA, std::streamsize accuracy)
template<>
std::string toString< LinkDirection > (const LinkDirection &linkDir, std::streamsize accuracy)
template<>
std::string toString< LinkState > (const LinkState &linkState, std::streamsize accuracy)
template<>
std::string toString< SUMOVehicleClass > (const SUMOVehicleClass &vClass, std::streamsize accuracy)
template<>
std::string toString< SumoXMLAttr > (const SumoXMLAttr &attr, std::streamsize accuracy)
template<>
std::string toString< SumoXMLEdgeFunc > (const SumoXMLEdgeFunc &edgeFunc, std::streamsize accuracy)
template<>
std::string toString< SumoXMLNodeType > (const SumoXMLNodeType &nodeType, std::streamsize accuracy)
template<>
std::string toString< SumoXMLTag > (const SumoXMLTag &tag, std::streamsize accuracy)
template<>
std::string toString< TrafficLightType > (const TrafficLightType &type, std::streamsize accuracy)
Detailed Description
Author
Christian Roessel
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Wed, 23 Sep 2002
Version
$Id$
Definition in file ToString.h.
Function Documentation
joinToString() [1/3]
template<typename T , typename T_BETWEEN > std::string joinToString (const std::vector< T > & v, const T_BETWEEN & between, std::streamsize accuracy = gPrecision) inline
Definition at line 236 of file ToString.h.
References toString().
Referenced by GNEAdditionalFrame::addAdditional(), NBEdge::buildInnerEdges(), NIImporter_OpenDrive::OpenDriveLaneSection::buildLaneMapping(), NIImporter_OpenDrive::OpenDriveLaneSection::buildSpeedChanges(), GUISUMOAbstractView::checkSnapshots(), MSNet::closeSimulation(), GNEBusStop::getAttribute(), GNEContainerStop::getAttribute(), MSContainer::MSContainerStage_Driving::getStageDescription(), MSPerson::MSPersonStage_Driving::getStageDescription(), Option_IntVector::getValueString(), getVehicleClassNames(), MSTransportable::Stage_Driving::getWaitingDescription(), NIImporter_OpenStreetMap::insertEdge(), GNECrossingFrame::crossingParameters::invertEdges(), joinToStringSorting(), GNECrossingFrame::crossingParameters::markEdge(), MSDevice_SSM::MSDevice_SSM(), GNEDialog_AllowDisallow::onCmdAccept(), GNEAttributeCarrier::parseGNEEdges(), GNEAttributeCarrier::parseGNELanes(), GNEJunction::removeEdgeFromCrossings(), MSTriggeredRerouter::rerouteParkingArea(), NIImporter_OpenDrive::setEdgeLinks2(), TraCITestClient::testAPI(), Distribution_Parameterized::toStr(), toString(), GNECrossingFrame::crossingParameters::useSelectedEdges(), MSVehicle::Stop::write(), NWWriter_SUMO::writeInternalNodes(), NWWriter_XML::writeNodes(), and NWWriter_SUMO::writeRoundabout().
joinToString() [2/3]
template<typename T , typename T_BETWEEN > std::string joinToString (const std::set< T > & s, const T_BETWEEN & between, std::streamsize accuracy = gPrecision) inline
Definition at line 289 of file ToString.h.
References toString().
joinToString() [3/3]
template<typename KEY , typename VAL , typename T_BETWEEN , typename T_BETWEEN_KEYVAL > std::string joinToString (const std::map< KEY, VAL > & s, const T_BETWEEN & between, const T_BETWEEN_KEYVAL & between_keyval, std::streamsize accuracy = gPrecision) inline
Definition at line 317 of file ToString.h.
References toString().
joinToStringSorting()
template<typename T , typename T_BETWEEN > std::string joinToStringSorting (const std::vector< T > & v, const T_BETWEEN & between, std::streamsize accuracy = gPrecision) inline
Definition at line 252 of file ToString.h.
References joinToString().
Referenced by NBNodeCont::joinJunctions(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and toString().
toHex()
template<typename T > std::string toHex (const T i, std::streamsize numDigits = 0) inline
Definition at line 65 of file ToString.h.
Referenced by TraCIServerAPI_Edge::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServerAPI_VehicleType::processSet(), and TraCIServer::writeStatusCmd().
toString() [1/13]
template<class T > std::string toString (const T & t, std::streamsize accuracy = gPrecision) inline
Template for conversions from origin format to string representation (when supplied by c++/the stl)
Definition at line 55 of file ToString.h.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), libsumo::Person::add(), MSDetectorControl::add(), ODMatrix::add(), MSDevice_SSM::Encounter::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), GNEAdditionalFrame::addAdditional(), GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), NBLoadedSUMOTLDef::addConnection(), NIImporter_SUMO::addConnection(), NLHandler::addConnection(), NIImporter_SUMO::addEdge(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), NIXMLEdgesHandler::addLane(), GNEAdditional::addLaneChild(), NLJunctionControlBuilder::addLogicItem(), GNEJunction::addOutgoingGNEEdge(), MSRouteHandler::addPersonTrip(), NLHandler::addPhase(), ShapeHandler::addPOI(), PCLoaderOSM::addPOI(), GNENet::addPOI(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), PCLoaderOSM::addPolygon(), GNENet::addPolygon(), GNEPolygonFrame::addPolygon(), GNEViewNet::addRestrictedLane(), NBEdge::addRestrictedLane(), GNENet::addReversedEdge(), NBEdgeCont::addRoundabout(), GNELane::addShapeChild(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), RONet::addStoppingPlace(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimTL::NIVissimTLSignal::addTo(), MSVehicle::addTraciStopAtStoppingPlace(), ROPerson::addTrip(), NBPTLine::addWayNode(), GNEAttributeCarrier::allowedAttributes(), NBNodeCont::analyzeCluster(), MSTransportable::appendStage(), NIImporter_OpenStreetMap::RelationHandler::applyRestriction(), NLEdgeControlBuilder::build(), MSAbstractLaneChangeModel::build(), GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildClosingLaneReroute(), GNEAdditionalHandler::buildClosingReroute(), NIImporter_OpenDrive::buildConnectionsToOuter(), GNEAdditionalHandler::buildContainerStop(), CHBuilder< E, V >::buildContractionHierarchy(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEViewNet::buildEditModeControls(), GNEAdditionalHandler::builDestProbReroute(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NIVissimEdge::buildNBEdge(), GNEPolygonFrame::buildPoly(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRerouterInterval(), NLDetectorBuilder::buildRouteProbe(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildRouteProbReroute(), MELoop::buildSegmentsFor(), GUITriggerBuilder::buildStoppingPlace(), NLTriggerBuilder::buildStoppingPlace(), MSFrame::buildStreams(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEAdditionalHandler::buildVariableSpeedSignStep(), MSDevice_Battery::buildVehicleDevices(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEPoly::changeFirstGeometryPoint(), GNEAdditional::changeLane(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), NBNode::checkCrossing(), NIImporter_OpenStreetMap::RelationHandler::checkEdgeRef(), RONet::checkFlows(), NBEdge::checkGeometry(), GNEAttributeCarrier::checkGNEEdgesValid(), GNEAttributeCarrier::checkGNELanesValid(), NBEdgeCont::checkGrade(), NWWriter_OpenDrive::checkLaneGeometries(), NGFrame::checkOptions(), MSFrame::checkOptions(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSSOTLTrafficLightLogic::checkPhases(), MSE2Collector::checkPositioning(), NLDetectorBuilder::checkSampleInterval(), GUISUMOAbstractView::checkSnapshots(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), GNENet::cleanInvalidCrossings(), GNEEdge::clearGNEConnections(), SUMOSAXAttributesImpl_Binary::clone(), MSNet::closeSimulation(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSRouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdgeVectors(), GNEDetectorE3::commitGeometryMoving(), GNEPOI::commitGeometryMoving(), GNEDetector::commitGeometryMoving(), GNEPOILane::commitGeometryMoving(), GNEStoppingPlace::commitGeometryMoving(), GNEVariableSpeedSign::commitGeometryMoving(), GNERerouter::commitGeometryMoving(), GNEJunction::commitGeometryMoving(), GNEPoly::commitShapeChange(), GNEEdge::commitShapeChange(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute(), NBNetBuilder::compute(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), IntermodalRouter< E, L, N, V >::compute(), CHRouter< E, V, PF >::compute(), ODMatrix::computeDeparts(), MSDevice_SSM::computeDRAC(), NBNode::computeLogic(), NBNode::computeNodeShape(), computeRoutes(), NIImporter_OpenDrive::computeShapes(), MSAbstractLaneChangeModel::computeSpeedLat(), MSDevice_SSM::computeSSMs(), RODFNet::computeTypes(), NBPTLineCont::constructRoute(), NGNet::createChequerBoard(), GNENet::createEdge(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNECrossingFrame::crossingParameters::crossingParameters(), GLHelper::debugVertices(), MSLCM_SL2015::decideDirection(), MSAbstractLaneChangeModel::decideDirection(), GNEReferenceCounter::decRef(), GNENet::deleteAdditional(), GNENet::deleteConnection(), GNENet::deleteEdge(), NIXMLEdgesHandler::deleteEdge(), GNEEdge::deleteGeometryPoint(), GNEPoly::deleteGeometryPoint(), GNENet::deleteJunction(), GNENet::deleteLane(), NIXMLNodesHandler::deleteNode(), NBTrafficLightLogic::deletePhase(), GNEViewNet::deleteSelectedConnections(), GNEViewNet::deleteSelectedCrossings(), GNEViewNet::deleteSelectedEdges(), GNEViewNet::deleteSelectedJunctions(), GNEViewNet::deleteSelectedLanes(), GNEViewNet::deleteSelectedShapes(), GNENet::deleteShape(), GUISelectedStorage::deselect(), MSLane::detectCollisions(), MSInsertionControl::determineCandidates(), MSDevice_SSM::determineTTCandDRAC(), GNEAttributeCarrier::discreteChoices(), TraCIServer::dispatchCommand(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUIBaseVehicle::drawLinkItem(), GNELane::drawLinkNo(), GUILane::drawLinkNo(), GUIVehicle::drawRouteHelper(), GNELane::drawTLSLinkNo(), GUILane::drawTLSLinkNo(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), GNENet::duplicateLane(), GNECrossingFrame::edgesSelector::edgesSelector(), NLDetectorBuilder::endE3Detector(), MSE3Collector::enter(), MSVehicle::enterLaneAtLaneChange(), OptionsLoader::error(), MSDevice_SSM::estimateConflictTimes(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVehicle::executeMove(), NBEdge::expandableBy(), OptionsLoader::fatalError(), NIImporter_OpenStreetMap::RelationHandler::findEdgeRef(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), GNENet::generateCalibratorFlowID(), GNENet::generateCalibratorRouteID(), GNENet::generateCalibratorVehicleTypeID(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), MSDevice_Example::generateOutput(), MSDevice_Bluelight::generateOutput(), GNENet::generateShapeID(), GNENet::generateVaporizerID(), NIImporter_OpenDrive::geomFromSpiral(), GNERouteProbReroute::getAttribute(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNEVariableSpeedSignStep::getAttribute(), GNECalibratorRoute::getAttribute(), GNECalibratorVehicleType::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE2::getAttribute(), GNECalibratorFlow::getAttribute(), GNEVaporizer::getAttribute(), GNECrossing::getAttribute(), GNEDetectorE3::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), GNECalibrator::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNEAttributeCarrier::getAttributeType(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), NIImporter_DlrNavteq::EdgesHandler::getColumn(), NBEdge::getConnection(), NBEdge::getConnectionRef(), GNEAttributeCarrier::getDefaultValue(), NBEdge::Connection::getDescription(), MSVehicle::Stop::getDescription(), NLDetectorBuilder::getEdgeChecking(), MSMeanData_Amitran::getEdgeID(), NBNode::getEdgesSortedByAngleAtNodeCenter(), MSDevice_SSM::getExtraTime(), NBEdge::Connection::getInternalLaneID(), ROMAAssignments::getKPaths(), NLDetectorBuilder::getLaneChecking(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), NLShapeHandler::getLanePos(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), libsumo::VehicleType::getLateralAlignment(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), NIVissimDistrictConnection::getMeanSpeed(), MSPModel_Striping::getNextLane(), GUISUMOAbstractView::getObjectsInBoundary(), libsumo::Simulation::getParameter(), MSDevice_Battery::getParameter(), MSDevice_Transportable::getParameter(), MSLCM_LC2013::getParameter(), MSDevice_Bluelight::getParameter(), MSDevice_Example::getParameter(), MSLCM_SL2015::getParameter(), MSDevice_Routing::getParameter(), MSAbstractLaneChangeModel::getParameter(), GUIPolygon::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GNENetElement::getParameterWindow(), GUINet::getParameterWindow(), GNEAdditional::getParameterWindow(), MSLane::getPartialBehind(), NBEdge::getPermissionVariants(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPOI::getPopUpMenu(), GNEPOILane::getPopUpMenu(), GUILane::getPopUpMenu(), GNEAdditional::getPopUpMenu(), MSBaseVehicle::getSingularType(), ROEdge::getStoredEffort(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), GUIPropertyScheme< T >::getTagName(), ROMAAssignments::getTravelTime(), ROEdge::getTravelTime(), GNEAdditionalHandler::getTypeOfFlowDistribution(), GUIVehicle::getTypeParameterWindow(), libsumo::Vehicle::getVClass(), libsumo::VehicleType::getVehicleClass(), MSVehicleControl::getWaitingVehicle(), NBHeightMapper::getZ(), GNEAdditionalFrame::GNEAdditionalFrame(), GNECalibratorDialog::GNECalibratorDialog(), GNECalibratorFlowDialog::GNECalibratorFlowDialog(), GNECalibratorRouteDialog::GNECalibratorRouteDialog(), GNECalibratorVehicleTypeDialog::GNECalibratorVehicleTypeDialog(), GNEChange_Attribute::GNEChange_Attribute(), GNEDialog_AllowDisallow::GNEDialog_AllowDisallow(), GNEDialog_FixAdditionalPositions::GNEDialog_FixAdditionalPositions(), GNEPolygonFrame::GNEPolygonFrame(), GNERerouterDialog::GNERerouterDialog(), GNERerouterIntervalDialog::GNERerouterIntervalDialog(), GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog(), GNEViewNet::GNEViewNet(), NBNode::guessCrossings(), NBNodeCont::guessTLs(), MSLane::handleCollisionBetween(), GUIApplicationWindow::handleEvent_SimulationStep(), GNEConnectorFrame::handleLaneClick(), GNEAttributeCarrier::hasDefaultValue(), HelpersHBEFA::HelpersHBEFA(), GNEViewNet::hotkeyEnter(), MSVehicle::ignoreRed(), GNEReferenceCounter::incRef(), ROMAAssignments::incremental(), MSVehicle::Influencer::influenceChangeDecision(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), GUICompleteSchemeStorage::init(), GNETLSEditorFrame::initPhaseTable(), GNEDialog_Wizard::InputFloat::InputFloat(), GNEDialog_Wizard::InputInt::InputInt(), GNENet::insertAdditional(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::insertNodeChecking(), MSDevice_SSM::insertOptions(), MSEdge::insertVehicle(), GNEInspectorFrame::inspectMultisection(), MSLane::integrateNewVehicle(), SUMOVehicleParameter::interpretEdgePos(), MSLane::isInsertionSuccess(), GNEAdditional::isRouteValid(), GNERouteProbReroute::isValid(), GNEDestProbReroute::isValid(), GNEClosingLaneReroute::isValid(), GNEClosingReroute::isValid(), GNEVariableSpeedSignStep::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNERerouterInterval::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), GNECalibratorFlow::isValid(), GNEVaporizer::isValid(), GNECrossing::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNEConnection::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNELane::isValid(), GNEJunction::isValid(), GNEEdge::isValid(), NBNodeCont::joinJunctions(), GNENet::joinSelectedJunctions(), NBNodeCont::joinTLS(), joinToString(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), NILoader::load(), PCLoaderVisum::load(), PCLoaderArcView::load(), NIImporter_ArcView::load(), NIImporter_OpenStreetMap::load(), NIImporter_RobocupRescue::loadEdges(), GUISelectedStorage::loadIDs(), PCLoaderOSM::loadIfSet(), NBHeightMapper::loadIfSet(), MFXImageHelper::loadImage(), loadNet(), ROLoader::loadNet(), NIImporter_OpenDrive::loadNetwork(), NIImporter_RobocupRescue::loadNodes(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), NILoader::loadXML(), main(), NBEdge::MainDirections::MainDirections(), MSDevice_SSM::makeStringWithNAs(), GNEDeleteFrame::markAttributeCarrier(), GNENet::mergeJunctions(), GNEViewNet::mergeJunctions(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NIXMLEdgesHandler::myEndElement(), NIImporter_OpenStreetMap::RelationHandler::myEndElement(), GUISettingsHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), ODAmitranHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), PCLoaderOSM::RelationsHandler::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::RelationHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), GNEAdditionalFrame::NeteditAttributes::NeteditAttributes(), NIVissimAbstractEdge::NIVissimAbstractEdge(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNEDialog_FixAdditionalPositions::onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNEVariableSpeedSignDialog::onCmdAccept(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNECalibratorDialog::onCmdClickedRoute(), GNECalibratorDialog::onCmdClickedVehicleType(), GUIDialog_ViewSettings::onCmdColorChange(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNEViewNet::onCmdDuplicateLane(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GUIDialog_EditViewport::onCmdOk(), GNETLSEditorFrame::onCmdPhaseEdit(), GNEAdditionalFrame::onCmdSelectAdditional(), GNEPolygonFrame::onCmdSelectShape(), GNESelectorFrame::onCmdSelMBAttribute(), GNESelectorFrame::onCmdSelMBTag(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetColorAttribute(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNESelectorFrame::onCmdSubset(), GNEViewNet::onCmdTransformPOI(), GNEViewNet::onLeftBtnPress(), MSVehicle::onRemovalFromNet(), GNEAdditional::openAdditionalDialog(), GUIApplicationWindow::openNewView(), GNEApplicationWindow::openNewView(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), PlainXMLFormatter::openTag(), OutputDevice_Network::OutputDevice_Network(), MSLaneChangerSublane::outputLCStarted(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_Point(), RONetHandler::parseAccess(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildCalibratorFlow(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildCalibratorVehicleType(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEAdditionalHandler::parseAndBuildDetectorE1(), GNEAdditionalHandler::parseAndBuildDetectorE2(), GNEAdditionalHandler::parseAndBuildDetectorE3(), GNEAdditionalHandler::parseAndBuildDetectorEntry(), GNEAdditionalHandler::parseAndBuildDetectorExit(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAdditionalHandler::parseAndBuildRerouterClosingLaneReroute(), GNEAdditionalHandler::parseAndBuildRerouterClosingReroute(), GNEAdditionalHandler::parseAndBuildRerouterDestProbReroute(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEAdditionalHandler::parseAndBuildRerouterRouteProbReroute(), GNEAdditionalHandler::parseAndBuildRouteProbe(), NLTriggerBuilder::parseAndBuildStoppingPlace(), GNEAdditionalHandler::parseAndBuildVaporizer(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAdditionalHandler::parseAndBuildVariableSpeedSignStep(), GNEAttributeCarrier::parseAttributeFromXML(), RONetHandler::parseConnection(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), RONetHandler::parseLane(), NIXMLConnectionsHandler::parseLaneBound(), SUMOSAXReader::parseNext(), GUISettingsHandler::parseSizeSettings(), RONetHandler::parseStoppingPlace(), GUISettingsHandler::parseTextSettings(), ODMatrix::parseTimeLine(), SUMOVehicleParserHelper::parseVTypeEmbedded(), SUMOVehicleParserHelper::parseWalkPos(), MSRouteHandler::parseWalkPositions(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), OutputDevice_Network::postWriteHook(), NBEdge::prepareEdgePriorities(), MSLCM_SL2015::prepareStep(), NBNodeCont::printBuiltNodesStatistics(), GNEPolygonFrame::processClick(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), MSPModel_Striping::PState::PState(), ODMatrix::readO(), NIImporter_DlrNavteq::readVersion(), GNEJunction::rebuildGNECrossings(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NIImporter_OpenStreetMap::reconstructLayerElevation(), GNEChange_Shape::redo(), GNEChange_Junction::redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_Additional::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_Junction::redoName(), GNEChange_Shape::redoName(), GNEChange_VariableSpeedSignItem::redoName(), GNEChange_TLS::redoName(), GNEChange_Lane::redoName(), GNEChange_Connection::redoName(), GNEChange_Additional::redoName(), GNEChange_Edge::redoName(), GNEChange_Attribute::redoName(), GNEChange_Crossing::redoName(), GNEChange_CalibratorItem::redoName(), GNEChange_RerouterItem::redoName(), GNEEdge::remakeGNEConnections(), GNENet::remapEdge(), GNEAdditionalFrame::removeAdditional(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), GNEEdge::removeEdgeOfAdditionalParents(), GNEJunction::removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), GNELane::removeLaneOfAdditionalParents(), GNEJunction::removeOutgoingGNEEdge(), GNEViewNet::removeRestrictedLane(), NBNodeCont::removeSelfLoops(), GNELane::removeShapeChild(), GNENet::removeSolitaryJunctions(), GNENet::replaceIncomingEdge(), GNENet::replaceInListAttribute(), GNENet::replaceJunctionByGeometry(), MSBaseVehicle::replaceRouteEdges(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), NBRequest::reportWarnings(), GNEEdge::resetEndpoint(), NBEdge::restoreRestrictedLane(), GNENet::restrictLane(), GNEViewNet::restrictLane(), GNEEdge::retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNENet::retrieveLane(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), GNENet::reverseEdge(), NIImporter_OpenDrive::revisitLaneSections(), RONet::saveAndRemoveRoutesUntil(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSDevice_Vehroutes::saveState(), MSDevice_Tripinfo::saveState(), MEVehicle::saveState(), MSVehicle::saveState(), GUISelectedStorage::select(), GNESelectorFrame::selectionUpdated(), GNEAdditionalFrame::SelectorParentEdges::SelectorParentEdges(), GNEAdditionalFrame::SelectorParentLanes::SelectorParentLanes(), GNERouteProbReroute::setAttribute(), GNEDestProbReroute::setAttribute(), GNEClosingReroute::setAttribute(), GNEClosingLaneReroute::setAttribute(), GNEVariableSpeedSignStep::setAttribute(), GNECalibratorRoute::setAttribute(), GNECalibratorVehicleType::setAttribute(), GNERerouterInterval::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNECalibratorFlow::setAttribute(), GNEVaporizer::setAttribute(), GNECrossing::setAttribute(), GNEDetectorE3::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNEConnection::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERerouter::setAttribute(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), GNECalibrator::setAttribute(), GNELane::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSChargingStation::setEfficency(), GNEEdge::setEndpoint(), RODFRouteCont::setID(), MFXAddEditTypedTable::setItemFromControl(), MFXAddEditTypedTable::setItemFromControl_NoRelease(), GeoConvHelper::setLoaded(), MSDevice_Battery::setMaximumBatteryCapacity(), GNEEdge::setNumLanes(), GNETLSEditorFrame::TLSAttributes::setOffset(), MSLCM_SL2015::setOwnState(), MSDevice_Battery::setParameter(), MSLCM_LC2013::setParameter(), MSLCM_SL2015::setParameter(), MSAbstractLaneChangeModel::setParameter(), libsumo::TrafficLight::setPhase(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), libsumo::Vehicle::setStop(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), GNECalibratorVehicleTypeDialog::setVClassLabelImage(), GNEInspectorFrame::NeteditParameters::show(), GNEInspectorFrame::AttributeInput::showAttribute(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEFrame::GEOAttributes::showGEOAttributes(), GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeList::showListParameter(), GNEAdditionalFrame::AdditionalAttributeSingle::showParameter(), GNEPolygonFrame::ShapeAttributeSingle::showParameter(), GNEPolygonFrame::ShapeAttributes::showWarningMessage(), GNEAdditionalFrame::AdditionalAttributes::showWarningMessage(), GNEPoly::simplifyShape(), GNEEdge::smooth(), GNEEdge::smoothElevation(), PositionVector::splitAt(), GNENet::splitEdge(), GNENet::splitEdgesBidi(), NBEdge::splitGeometry(), NIImporter_OpenDrive::splitMinWidths(), GNEEdge::straightenElevation(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSAbstractLaneChangeModel::sublaneChangeCompleted(), ROMAAssignments::sue(), MELoop::teleportVehicle(), GUISelectedStorage::toggleSelection(), Distribution_Parameterized::toStr(), TraCIServer::TraCIServer(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), NIXMLEdgesHandler::tryGetLaneSpread(), SAXWeightsHandler::tryParse(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), GNEChange_Additional::undo(), GNEChange_Lane::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_Junction::undoName(), GNEChange_Shape::undoName(), GNEChange_VariableSpeedSignItem::undoName(), GNEChange_TLS::undoName(), GNEChange_Lane::undoName(), GNEChange_Connection::undoName(), GNEChange_Additional::undoName(), GNEChange_Edge::undoName(), GNEChange_Attribute::undoName(), GNEChange_Crossing::undoName(), GNEChange_CalibratorItem::undoName(), GNEChange_RerouterItem::undoName(), GNENet::updateAdditionalID(), MSVehicle::updateBestLanes(), GNERerouterIntervalDialog::updateClosingLaneReroutesTable(), GNERerouterIntervalDialog::updateClosingReroutesTable(), GNEDeleteFrame::updateCurrentLabel(), GNETLSEditorFrame::updateCycleDuration(), GNEConnectorFrame::updateDescription(), GNERerouterIntervalDialog::updateDestProbReroutesTable(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), GNECalibratorDialog::updateFlowAndLabelButton(), GNECalibratorDialog::updateFlowTable(), MSVehicle::updateFurtherLanes(), GNERerouterDialog::updateIntervalTable(), GUISUMOAbstractView::updatePositionInformation(), GNERerouterIntervalDialog::updateRouteProbReroutesTable(), GNECalibratorDialog::updateRouteTable(), MSAbstractLaneChangeModel::updateShadowLane(), CHBuilder< E, V >::CHInfo::updateShortcuts(), MSAbstractLaneChangeModel::updateTargetLane(), GNECalibratorDialog::updateVehicleTypeTable(), GNETLSEditorFrame::varDurString(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSAbstractLaneChangeModel::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSAbstractLaneChangeModel::wantsChangeSublane(), OptionsLoader::warning(), NBPTLine::write(), MSFCDExport::write(), SUMOVTypeParameter::write(), MSInstantInductLoop::write(), SUMOVehicleParameter::write(), GNEDetectorE3::writeAdditional(), MSLink::writeApproaching(), NBSign::writeAsPOI(), PlainXMLFormatter::writeAttr(), BinaryFormatter::writeAttr(), NWWriter_SUMO::writeConnection(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), ODMatrix::writeFlows(), NWWriter_OpenDrive::writeGeomSmooth(), NWWriter_SUMO::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), MSDevice_SSM::writeOutConflict(), GUICompleteSchemeStorage::writeSettings(), ROLoader::writeStats(), NWWriter_SUMO::writeSUMOTime(), MSAmitranTrajectories::writeVehicle(), RORoute::writeXMLDefinition(), MSRouteProbe::writeXMLOutput(), MSCalibrator::writeXMLOutput(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEEdge::~GNEEdge(), GNEJunction::~GNEJunction(), GNENet::~GNENet(), GNEReferenceCounter::~GNEReferenceCounter(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
toString() [2/13]
std::string toString (const Named * obj, std::streamsize accuracy) inline
Definition at line 73 of file ToString.h.
References Named::getIDSecure(), and UNUSED_PARAMETER.
toString() [3/13]
template<typename V > std::string toString (const std::vector< V *> & v, std::streamsize accuracy = gPrecision) inline
Definition at line 178 of file ToString.h.
toString() [4/13]
template<typename V > std::string toString (const typename std::vector< V *>::const_iterator & b, const typename std::vector< V *>::const_iterator & e, std::streamsize accuracy = gPrecision) inline
Definition at line 183 of file ToString.h.
References Named::getIDSecure(), and UNUSED_PARAMETER.
toString() [5/13]
template<typename V > std::string toString (const std::list< V *> & v, std::streamsize accuracy = gPrecision) inline
Definition at line 196 of file ToString.h.
toString() [6/13]
template<typename V > std::string toString (const typename std::list< V *>::const_iterator & b, const typename std::list< V *>::const_iterator & e, std::streamsize accuracy = gPrecision) inline
Definition at line 201 of file ToString.h.
References Named::getIDSecure(), and UNUSED_PARAMETER.
toString() [7/13]
template<typename V > std::string toString (const std::set< V *> & v, std::streamsize accuracy = gPrecision) inline
Definition at line 260 of file ToString.h.
References joinToStringSorting(), and UNUSED_PARAMETER.
toString() [8/13]
template<> std::string toString (const std::vector< int > & v, std::streamsize accuracy) inline
Definition at line 271 of file ToString.h.
References joinToString().
toString() [9/13]
template<> std::string toString (const std::vector< long long int > & v, std::streamsize accuracy) inline
Definition at line 277 of file ToString.h.
References joinToString().
toString() [10/13]
template<> std::string toString (const std::vector< double > & v, std::streamsize accuracy) inline
Definition at line 283 of file ToString.h.
References joinToString().
toString() [11/13]
template<> std::string toString (const std::vector< std::string > & v, std::streamsize) inline
Definition at line 305 of file ToString.h.
References joinToString().
toString() [12/13]
template<> std::string toString (const std::set< std::string > & v, std::streamsize) inline
Definition at line 311 of file ToString.h.
References joinToString().
toString() [13/13]
template<> std::string toString (const std::map< std::string, std::string > & v, std::streamsize) inline
Definition at line 333 of file ToString.h.
References joinToString().
toString< Distribution_Parameterized >()
template<> std::string toString< Distribution_Parameterized > (const Distribution_Parameterized & dist, std::streamsize accuracy) inline
Definition at line 173 of file ToString.h.
toString< LaneChangeAction >()
template<> std::string toString< LaneChangeAction > (const LaneChangeAction & action, std::streamsize accuracy) inline
Definition at line 154 of file ToString.h.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneChangeActions, and UNUSED_PARAMETER.
toString< LaneChangeModel >()
template<> std::string toString< LaneChangeModel > (const LaneChangeModel & model, std::streamsize accuracy) inline
Definition at line 142 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LaneChangeModels, and UNUSED_PARAMETER.
toString< LaneSpreadFunction >()
template<> std::string toString< LaneSpreadFunction > (const LaneSpreadFunction & lsf, std::streamsize accuracy) inline
Definition at line 114 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LaneSpreadFunctions, and UNUSED_PARAMETER.
toString< LateralAlignment >()
template<> std::string toString< LateralAlignment > (const LateralAlignment & latA, std::streamsize accuracy) inline
Definition at line 148 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LateralAlignments, and UNUSED_PARAMETER.
toString< LinkDirection >()
template<> std::string toString< LinkDirection > (const LinkDirection & linkDir, std::streamsize accuracy) inline
Definition at line 128 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LinkDirections, and UNUSED_PARAMETER.
toString< LinkState >()
template<> std::string toString< LinkState > (const LinkState & linkState, std::streamsize accuracy) inline
Definition at line 121 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::LinkStates, and UNUSED_PARAMETER.
toString< SUMOVehicleClass >()
template<> std::string toString< SUMOVehicleClass > (const SUMOVehicleClass & vClass, std::streamsize accuracy) inline
Definition at line 107 of file ToString.h.
References SumoVehicleClassStrings, and UNUSED_PARAMETER.
toString< SumoXMLAttr >()
template<> std::string toString< SumoXMLAttr > (const SumoXMLAttr & attr, std::streamsize accuracy) inline
Definition at line 86 of file ToString.h.
References SUMOXMLDefinitions::Attrs, StringBijection< T >::getString(), and UNUSED_PARAMETER.
toString< SumoXMLEdgeFunc >()
template<> std::string toString< SumoXMLEdgeFunc > (const SumoXMLEdgeFunc & edgeFunc, std::streamsize accuracy) inline
Definition at line 100 of file ToString.h.
References SUMOXMLDefinitions::EdgeFunctions, StringBijection< T >::getString(), and UNUSED_PARAMETER.
toString< SumoXMLNodeType >()
template<> std::string toString< SumoXMLNodeType > (const SumoXMLNodeType & nodeType, std::streamsize accuracy) inline
Definition at line 93 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::NodeTypes, and UNUSED_PARAMETER.
toString< SumoXMLTag >()
template<> std::string toString< SumoXMLTag > (const SumoXMLTag & tag, std::streamsize accuracy) inline
Definition at line 79 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::Tags, and UNUSED_PARAMETER.
toString< TrafficLightType >()
template<> std::string toString< TrafficLightType > (const TrafficLightType & type, std::streamsize accuracy) inline
Definition at line 135 of file ToString.h.
References StringBijection< T >::getString(), SUMOXMLDefinitions::TrafficLightTypes, and UNUSED_PARAMETER.