SUMO - Simulation of Urban MObility: NIImporter_OpenDrive Class Reference
NIImporter_OpenDrive Class Reference
Importer for networks stored in openDrive format.
#include <NIImporter_OpenDrive.h>
Data Structures
struct Connection
A connection between two roads.
struct OpenDriveEdge
Representation of an openDrive "link".
struct OpenDriveGeometry
Representation of an OpenDrive geometry part.
struct OpenDriveLane
Representation of a lane.
struct OpenDriveLaneSection
Representation of a lane section.
struct OpenDriveLink
Representation of an OpenDrive link.
struct OpenDriveSignal
Representation of a signal.
struct Poly3
class same_position_finder
class sections_by_s_sorter
A class for sorting lane sections by their s-value.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given SUMO file.
Protected Types
enum ContactPoint { OPENDRIVE_CP_UNKNOWN, OPENDRIVE_CP_START, OPENDRIVE_CP_END }
OpenDrive contact type enumeration.
enum ElementType { OPENDRIVE_ET_UNKNOWN, OPENDRIVE_ET_ROAD, OPENDRIVE_ET_JUNCTION }
OpenDrive element type enumeration.
enum GeometryType {
OPENDRIVE_GT_UNKNOWN, OPENDRIVE_GT_LINE, OPENDRIVE_GT_SPIRAL, OPENDRIVE_GT_ARC,
OPENDRIVE_GT_POLY3, OPENDRIVE_GT_PARAMPOLY3
}
OpenDrive geometry type enumeration.
enum LinkType { OPENDRIVE_LT_SUCCESSOR, OPENDRIVE_LT_PREDECESSOR }
OpenDrive link type enumeration.
typedef Poly3 OpenDriveElevation
LaneOffset has the same fields as Elevation.
typedef Poly3 OpenDriveLaneOffset
typedef Poly3 OpenDriveWidth
enum OpenDriveXMLAttr {
OPENDRIVE_ATTR_NOTHING, OPENDRIVE_ATTR_REVMAJOR, OPENDRIVE_ATTR_REVMINOR, OPENDRIVE_ATTR_ID,
OPENDRIVE_ATTR_LENGTH, OPENDRIVE_ATTR_JUNCTION, OPENDRIVE_ATTR_ELEMENTTYPE, OPENDRIVE_ATTR_ELEMENTID,
OPENDRIVE_ATTR_CONTACTPOINT, OPENDRIVE_ATTR_S, OPENDRIVE_ATTR_X, OPENDRIVE_ATTR_Y,
OPENDRIVE_ATTR_HDG, OPENDRIVE_ATTR_CURVSTART, OPENDRIVE_ATTR_CURVEND, OPENDRIVE_ATTR_CURVATURE,
OPENDRIVE_ATTR_A, OPENDRIVE_ATTR_B, OPENDRIVE_ATTR_C, OPENDRIVE_ATTR_D,
OPENDRIVE_ATTR_AU, OPENDRIVE_ATTR_BU, OPENDRIVE_ATTR_CU, OPENDRIVE_ATTR_DU,
OPENDRIVE_ATTR_AV, OPENDRIVE_ATTR_BV, OPENDRIVE_ATTR_CV, OPENDRIVE_ATTR_DV,
OPENDRIVE_ATTR_PRANGE, OPENDRIVE_ATTR_TYPE, OPENDRIVE_ATTR_LEVEL, OPENDRIVE_ATTR_ORIENTATION,
OPENDRIVE_ATTR_DYNAMIC, OPENDRIVE_ATTR_INCOMINGROAD, OPENDRIVE_ATTR_CONNECTINGROAD, OPENDRIVE_ATTR_FROM,
OPENDRIVE_ATTR_TO, OPENDRIVE_ATTR_MAX, OPENDRIVE_ATTR_SOFFSET, OPENDRIVE_ATTR_NAME,
OPENDRIVE_ATTR_UNIT
}
Numbers representing openDrive-XML - attributes.
enum OpenDriveXMLTag {
OPENDRIVE_TAG_NOTHING, OPENDRIVE_TAG_HEADER, OPENDRIVE_TAG_ROAD, OPENDRIVE_TAG_PREDECESSOR,
OPENDRIVE_TAG_SUCCESSOR, OPENDRIVE_TAG_GEOMETRY, OPENDRIVE_TAG_LINE, OPENDRIVE_TAG_SPIRAL,
OPENDRIVE_TAG_ARC, OPENDRIVE_TAG_POLY3, OPENDRIVE_TAG_PARAMPOLY3, OPENDRIVE_TAG_LANESECTION,
OPENDRIVE_TAG_LANEOFFSET, OPENDRIVE_TAG_LEFT, OPENDRIVE_TAG_CENTER, OPENDRIVE_TAG_RIGHT,
OPENDRIVE_TAG_LANE, OPENDRIVE_TAG_SIGNAL, OPENDRIVE_TAG_JUNCTION, OPENDRIVE_TAG_CONNECTION,
OPENDRIVE_TAG_LANELINK, OPENDRIVE_TAG_WIDTH, OPENDRIVE_TAG_SPEED, OPENDRIVE_TAG_ELEVATION
}
Numbers representing openDrive-XML - element names.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
NIImporter_OpenDrive (const NBTypeCont &tc, std::map< std::string, OpenDriveEdge *> &edges)
Constructor.
~NIImporter_OpenDrive ()
Destructor.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int element)
Called when a closing tag occurs.
Static Protected Member Functions
static void calcPointOnCurve (double *ad_x, double *ad_y, double ad_centerX, double ad_centerY, double ad_r, double ad_length)
static void calculateCurveCenter (double *ad_x, double *ad_y, double ad_radius, double ad_hdg)
static Position calculateStraightEndPoint (double hdg, double length, const Position &start)
static void computeShapes (std::map< std::string, OpenDriveEdge *> &edges)
Computes a polygon representation of each edge's geometry.
static void findWidthSplit (const NBTypeCont &tc, std::vector< OpenDriveLane > &lanes, int section, double sectionStart, double sectionEnd, std::vector< double > &splitPositions)
static PositionVector geomFromArc (const OpenDriveEdge &e, const OpenDriveGeometry &g, double resolution)
static PositionVector geomFromLine (const OpenDriveEdge &e, const OpenDriveGeometry &g)
static PositionVector geomFromParamPoly (const OpenDriveEdge &e, const OpenDriveGeometry &g, double resolution)
static PositionVector geomFromPoly (const OpenDriveEdge &e, const OpenDriveGeometry &g, double resolution)
static PositionVector geomFromSpiral (const OpenDriveEdge &e, const OpenDriveGeometry &g, double resolution)
static NBNode * getOrBuildNode (const std::string &id, const Position &pos, NBNodeCont &nc)
Builds a node or returns the already built.
static void recomputeWidths (OpenDriveLaneSection &sec, double start, double end, double sectionStart, double sectionEnd)
static void recomputeWidths (std::vector< OpenDriveLane > &lanes, double start, double end, double sectionStart, double sectionEnd)
static void revisitLaneSections (const NBTypeCont &tc, std::map< std::string, OpenDriveEdge *> &edges)
Rechecks lane sections of the given edges.
static void setNodeSecure (NBNodeCont &nc, OpenDriveEdge &e, const std::string &nodeID, NIImporter_OpenDrive::LinkType lt)
static void setStraightConnections (std::vector< OpenDriveLane > &lanes)
static void splitMinWidths (OpenDriveEdge *e, const NBTypeCont &tc, double minDist)
Static Protected Attributes
static StringBijection< int >::Entry openDriveAttrs []
The names of openDrive-XML attributes (for passing to GenericSAXHandler)
static StringBijection< int >::Entry openDriveTags []
The names of openDrive-XML elements (for passing to GenericSAXHandler)
Private Member Functions
void addGeometryShape (GeometryType type, const std::vector< double > &vals)
void addLink (LinkType lt, const std::string &elementType, const std::string &elementID, const std::string &contactPoint)
Static Private Member Functions
static void buildConnectionsToOuter (const Connection &c, const std::map< std::string, OpenDriveEdge *> &innerEdges, std::vector< Connection > &into, std::set< Connection > &seen)
static std::string revertID (const std::string &id)
static void setEdgeLinks2 (OpenDriveEdge &e, const std::map< std::string, OpenDriveEdge *> &edges)
Private Attributes
bool myConnectionWasEmpty
std::string myCurrentConnectingRoad
ContactPoint myCurrentContactPoint
OpenDriveEdge myCurrentEdge
std::string myCurrentIncomingRoad
std::string myCurrentJunctionID
OpenDriveXMLTag myCurrentLaneDirection
std::map< std::string, OpenDriveEdge * > & myEdges
std::vector< int > myElementStack
const NBTypeCont & myTypeContainer
Static Private Attributes
static bool myImportAllTypes
static bool myImportWidths
static double myMinWidth
Friends
bool operator< (const Connection &c1, const Connection &c2)
Detailed Description
Importer for networks stored in openDrive format.
Definition at line 60 of file NIImporter_OpenDrive.h.
Member Typedef Documentation
OpenDriveElevation
typedef Poly3 NIImporter_OpenDrive::OpenDriveElevation protected
LaneOffset has the same fields as Elevation.
Definition at line 278 of file NIImporter_OpenDrive.h.
OpenDriveLaneOffset
typedef Poly3 NIImporter_OpenDrive::OpenDriveLaneOffset protected
Definition at line 279 of file NIImporter_OpenDrive.h.
OpenDriveWidth
typedef Poly3 NIImporter_OpenDrive::OpenDriveWidth protected
Definition at line 280 of file NIImporter_OpenDrive.h.
Member Enumeration Documentation
ContactPoint
enum NIImporter_OpenDrive::ContactPoint protected
OpenDrive contact type enumeration.
Enumerator
OPENDRIVE_CP_UNKNOWN
OPENDRIVE_CP_START
OPENDRIVE_CP_END
Definition at line 186 of file NIImporter_OpenDrive.h.
ElementType
enum NIImporter_OpenDrive::ElementType protected
OpenDrive element type enumeration.
Enumerator
OPENDRIVE_ET_UNKNOWN
OPENDRIVE_ET_ROAD
OPENDRIVE_ET_JUNCTION
Definition at line 177 of file NIImporter_OpenDrive.h.
GeometryType
enum NIImporter_OpenDrive::GeometryType protected
OpenDrive geometry type enumeration.
Enumerator
OPENDRIVE_GT_UNKNOWN
OPENDRIVE_GT_LINE
OPENDRIVE_GT_SPIRAL
OPENDRIVE_GT_ARC
OPENDRIVE_GT_POLY3
OPENDRIVE_GT_PARAMPOLY3
Definition at line 194 of file NIImporter_OpenDrive.h.
LinkType
enum NIImporter_OpenDrive::LinkType protected
OpenDrive link type enumeration.
Enumerator
OPENDRIVE_LT_SUCCESSOR
OPENDRIVE_LT_PREDECESSOR
Definition at line 169 of file NIImporter_OpenDrive.h.
OpenDriveXMLAttr
enum NIImporter_OpenDrive::OpenDriveXMLAttr protected
Numbers representing openDrive-XML - attributes.
See also
GenericSAXHandler
Enumerator
OPENDRIVE_ATTR_NOTHING
OPENDRIVE_ATTR_REVMAJOR
OPENDRIVE_ATTR_REVMINOR
OPENDRIVE_ATTR_ID
OPENDRIVE_ATTR_LENGTH
OPENDRIVE_ATTR_JUNCTION
OPENDRIVE_ATTR_ELEMENTTYPE
OPENDRIVE_ATTR_ELEMENTID
OPENDRIVE_ATTR_CONTACTPOINT
OPENDRIVE_ATTR_S
OPENDRIVE_ATTR_X
OPENDRIVE_ATTR_Y
OPENDRIVE_ATTR_HDG
OPENDRIVE_ATTR_CURVSTART
OPENDRIVE_ATTR_CURVEND
OPENDRIVE_ATTR_CURVATURE
OPENDRIVE_ATTR_A
OPENDRIVE_ATTR_B
OPENDRIVE_ATTR_C
OPENDRIVE_ATTR_D
OPENDRIVE_ATTR_AU
OPENDRIVE_ATTR_BU
OPENDRIVE_ATTR_CU
OPENDRIVE_ATTR_DU
OPENDRIVE_ATTR_AV
OPENDRIVE_ATTR_BV
OPENDRIVE_ATTR_CV
OPENDRIVE_ATTR_DV
OPENDRIVE_ATTR_PRANGE
OPENDRIVE_ATTR_TYPE
OPENDRIVE_ATTR_LEVEL
OPENDRIVE_ATTR_ORIENTATION
OPENDRIVE_ATTR_DYNAMIC
OPENDRIVE_ATTR_INCOMINGROAD
OPENDRIVE_ATTR_CONNECTINGROAD
OPENDRIVE_ATTR_FROM
OPENDRIVE_ATTR_TO
OPENDRIVE_ATTR_MAX
OPENDRIVE_ATTR_SOFFSET
OPENDRIVE_ATTR_NAME
OPENDRIVE_ATTR_UNIT
Definition at line 122 of file NIImporter_OpenDrive.h.
OpenDriveXMLTag
enum NIImporter_OpenDrive::OpenDriveXMLTag protected
Numbers representing openDrive-XML - element names.
See also
GenericSAXHandler
Enumerator
OPENDRIVE_TAG_NOTHING
OPENDRIVE_TAG_HEADER
OPENDRIVE_TAG_ROAD
OPENDRIVE_TAG_PREDECESSOR
OPENDRIVE_TAG_SUCCESSOR
OPENDRIVE_TAG_GEOMETRY
Todo:
OPENDRIVE_TAG_NEIGHBOR,
OPENDRIVE_TAG_TYPE,
OPENDRIVE_TAG_LINE
OPENDRIVE_TAG_SPIRAL
OPENDRIVE_TAG_ARC
OPENDRIVE_TAG_POLY3
OPENDRIVE_TAG_PARAMPOLY3
OPENDRIVE_TAG_LANESECTION
OPENDRIVE_TAG_LANEOFFSET
OPENDRIVE_TAG_LEFT
OPENDRIVE_TAG_CENTER
OPENDRIVE_TAG_RIGHT
OPENDRIVE_TAG_LANE
OPENDRIVE_TAG_SIGNAL
OPENDRIVE_TAG_JUNCTION
OPENDRIVE_TAG_CONNECTION
OPENDRIVE_TAG_LANELINK
OPENDRIVE_TAG_WIDTH
OPENDRIVE_TAG_SPEED
OPENDRIVE_TAG_ELEVATION
Definition at line 87 of file NIImporter_OpenDrive.h.
Constructor & Destructor Documentation
NIImporter_OpenDrive()
NIImporter_OpenDrive::NIImporter_OpenDrive (const NBTypeCont & tc, std::map< std::string, OpenDriveEdge *> & edges) protected
Constructor.
Parameters
[in] tc The type container used to determine whether a lane shall kept
[in] nc The edge map to fill
Definition at line 1503 of file NIImporter_OpenDrive.cpp.
~NIImporter_OpenDrive()
NIImporter_OpenDrive::~NIImporter_OpenDrive () protected
Destructor.
Definition at line 1509 of file NIImporter_OpenDrive.cpp.
Member Function Documentation
addGeometryShape()
void NIImporter_OpenDrive::addGeometryShape (GeometryType type, const std::vector< double > & vals) private
Definition at line 1829 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::OpenDriveEdge::geometries, NIImporter_OpenDrive::OpenDriveEdge::id, myCurrentEdge, OPENDRIVE_GT_UNKNOWN, NIImporter_OpenDrive::OpenDriveGeometry::params, and NIImporter_OpenDrive::OpenDriveGeometry::type.
Referenced by myStartElement().
addLink()
void NIImporter_OpenDrive::addLink (LinkType lt, const std::string & elementType, const std::string & elementID, const std::string & contactPoint) private
Definition at line 1807 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::OpenDriveLink::contactPoint, NIImporter_OpenDrive::OpenDriveLink::elementType, NIImporter_OpenDrive::OpenDriveEdge::links, myCurrentEdge, OPENDRIVE_CP_END, OPENDRIVE_CP_START, OPENDRIVE_ET_JUNCTION, and OPENDRIVE_ET_ROAD.
Referenced by myStartElement().
buildConnectionsToOuter()
void NIImporter_OpenDrive::buildConnectionsToOuter (const Connection & c, const std::map< std::string, OpenDriveEdge *> & innerEdges, std::vector< Connection > & into, std::set< Connection > & seen) static private
!!! should not, look in all?
Definition at line 713 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::Connection::all, cn, NIImporter_OpenDrive::OpenDriveEdge::connections, NIImporter_OpenDrive::Connection::fromCP, NIImporter_OpenDrive::Connection::fromEdge, NIImporter_OpenDrive::Connection::fromLane, NIImporter_OpenDrive::Connection::origID, NIImporter_OpenDrive::Connection::origLane, NIImporter_OpenDrive::Connection::toEdge, NIImporter_OpenDrive::Connection::toLane, toString(), and WRITE_WARNING.
Referenced by loadNetwork().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
calcPointOnCurve()
void NIImporter_OpenDrive::calcPointOnCurve (double * ad_x, double * ad_y, double ad_centerX, double ad_centerY, double ad_r, double ad_length) static protected
Definition at line 1279 of file NIImporter_OpenDrive.cpp.
Referenced by geomFromArc().
calculateCurveCenter()
void NIImporter_OpenDrive::calculateCurveCenter (double * ad_x, double * ad_y, double ad_radius, double ad_hdg) static protected
Definition at line 1251 of file NIImporter_OpenDrive.cpp.
Referenced by geomFromArc().
calculateStraightEndPoint()
Position NIImporter_OpenDrive::calculateStraightEndPoint (double hdg, double length, const Position & start) static protected
Definition at line 1239 of file NIImporter_OpenDrive.cpp.
References Position::x(), and Position::y().
Referenced by geomFromLine().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
computeShapes()
void NIImporter_OpenDrive::computeShapes (std::map< std::string, OpenDriveEdge *> & edges) static protected
Computes a polygon representation of each edge's geometry.
Parameters
[in] edges The edges which geometries shall be converted
Definition at line 901 of file NIImporter_OpenDrive.cpp.
References PositionVector::add(), NIImporter_OpenDrive::Poly3::computeAt(), Position::distanceTo2D(), NIImporter_OpenDrive::OpenDriveEdge::elevations, OptionsCont::exists(), NIImporter_OpenDrive::OpenDriveEdge::geom, NIImporter_OpenDrive::OpenDriveEdge::geometries, geomFromArc(), geomFromLine(), geomFromParamPoly(), geomFromPoly(), geomFromSpiral(), OptionsCont::getFloat(), OptionsCont::getOptions(), NIImporter_OpenDrive::OpenDriveEdge::id, PositionVector::indexOfClosest(), PositionVector::insertAtClosest(), OptionsCont::isDefault(), PositionVector::move2side(), NIImporter_OpenDrive::OpenDriveEdge::offsets, OPENDRIVE_GT_ARC, OPENDRIVE_GT_LINE, OPENDRIVE_GT_PARAMPOLY3, OPENDRIVE_GT_POLY3, OPENDRIVE_GT_SPIRAL, OPENDRIVE_GT_UNKNOWN, POSITION_EPS, PositionVector::positionAtOffset2D(), PositionVector::push_back_noDoublePos(), PositionVector::removeDoublePoints(), NIImporter_OpenDrive::Poly3::s, toString(), NBNetBuilder::transformCoordinates(), NIImporter_OpenDrive::OpenDriveGeometry::type, WRITE_ERROR, and WRITE_WARNING.
Referenced by loadNetwork().
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
findWidthSplit()
void NIImporter_OpenDrive::findWidthSplit (const NBTypeCont & tc, std::vector< OpenDriveLane > & lanes, int section, double sectionStart, double sectionEnd, std::vector< double > & splitPositions) static protected
Definition at line 1953 of file NIImporter_OpenDrive.cpp.
References gDebugFlag1, NBTypeCont::getPermissions(), NBTypeCont::getShallBeDiscarded(), NIImporter_OpenDrive::OpenDriveLane::id, NBTypeCont::knows(), myMinWidth, POSITION_EPS, SVC_BICYCLE, SVC_PEDESTRIAN, NIImporter_OpenDrive::OpenDriveLane::type, UNUSED_PARAMETER, and NIImporter_OpenDrive::OpenDriveLane::widthData.
Referenced by splitMinWidths().
geomFromArc()
PositionVector NIImporter_OpenDrive::geomFromArc (const OpenDriveEdge & e, const OpenDriveGeometry & g, double resolution) static protected
Definition at line 1158 of file NIImporter_OpenDrive.cpp.
References calcPointOnCurve(), calculateCurveCenter(), PositionVector::getSubpart2D(), NIImporter_OpenDrive::OpenDriveGeometry::hdg, NIImporter_OpenDrive::OpenDriveGeometry::length, NIImporter_OpenDrive::OpenDriveGeometry::params, NIImporter_OpenDrive::OpenDriveGeometry::s, UNUSED_PARAMETER, NIImporter_OpenDrive::OpenDriveGeometry::x, and NIImporter_OpenDrive::OpenDriveGeometry::y.
Referenced by computeShapes().
geomFromLine()
PositionVector NIImporter_OpenDrive::geomFromLine (const OpenDriveEdge & e, const OpenDriveGeometry & g) static protected
Definition at line 1084 of file NIImporter_OpenDrive.cpp.
References calculateStraightEndPoint(), NIImporter_OpenDrive::OpenDriveGeometry::hdg, NIImporter_OpenDrive::OpenDriveGeometry::length, UNUSED_PARAMETER, NIImporter_OpenDrive::OpenDriveGeometry::x, and NIImporter_OpenDrive::OpenDriveGeometry::y.
Referenced by computeShapes().
geomFromParamPoly()
PositionVector NIImporter_OpenDrive::geomFromParamPoly (const OpenDriveEdge & e, const OpenDriveGeometry & g, double resolution) static protected
Definition at line 1220 of file NIImporter_OpenDrive.cpp.
References PositionVector::getSubpart2D(), NIImporter_OpenDrive::OpenDriveGeometry::hdg, NIImporter_OpenDrive::OpenDriveGeometry::length, NIImporter_OpenDrive::OpenDriveGeometry::params, UNUSED_PARAMETER, NIImporter_OpenDrive::OpenDriveGeometry::x, and NIImporter_OpenDrive::OpenDriveGeometry::y.
Referenced by computeShapes().
geomFromPoly()
PositionVector NIImporter_OpenDrive::geomFromPoly (const OpenDriveEdge & e, const OpenDriveGeometry & g, double resolution) static protected
Definition at line 1203 of file NIImporter_OpenDrive.cpp.
References PositionVector::getSubpart2D(), NIImporter_OpenDrive::OpenDriveGeometry::hdg, NIImporter_OpenDrive::OpenDriveGeometry::length, NIImporter_OpenDrive::OpenDriveGeometry::params, UNUSED_PARAMETER, NIImporter_OpenDrive::OpenDriveGeometry::x, and NIImporter_OpenDrive::OpenDriveGeometry::y.
Referenced by computeShapes().
geomFromSpiral()
PositionVector NIImporter_OpenDrive::geomFromSpiral (const OpenDriveEdge & e, const OpenDriveGeometry & g, double resolution) static protected
Definition at line 1094 of file NIImporter_OpenDrive.cpp.
References PositionVector::add(), GenericSAXHandler::error(), PositionVector::getSubpart2D(), NIImporter_OpenDrive::OpenDriveGeometry::hdg, NIImporter_OpenDrive::OpenDriveEdge::id, NIImporter_OpenDrive::OpenDriveGeometry::length, GeomHelper::naviDegree(), odrSpiral(), NIImporter_OpenDrive::OpenDriveGeometry::params, PositionVector::rotate2D(), NIImporter_OpenDrive::OpenDriveGeometry::s, toString(), UNUSED_PARAMETER, WRITE_WARNING, NIImporter_OpenDrive::OpenDriveGeometry::x, and NIImporter_OpenDrive::OpenDriveGeometry::y.
Referenced by computeShapes().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
getOrBuildNode()
NBNode * NIImporter_OpenDrive::getOrBuildNode (const std::string & id, const Position & pos, NBNodeCont & nc) static protected
Builds a node or returns the already built.
If the node is already known, it is returned. Otherwise, the node is built. If the newly built node can not be added to the container, a ProcessError is thrown. Otherwise this node is returned.
Parameters
[in] id The id of the node to build/get
Definition at line 866 of file NIImporter_OpenDrive.cpp.
References NBNodeCont::insert(), and NBNodeCont::retrieve().
Referenced by loadNetwork().
loadNetwork()
void NIImporter_OpenDrive::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads content of the optionally given SUMO file.
If the option "opendrive-files" is set, the file stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "opendrive-files" is not set, this method simply returns.
The loading is done by parsing the network definition as an XML file using the SAXinterface and handling the incoming data via this class' methods.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Todo:
: One could think of determining whether lane sections may be joined when being equal in SUMO's sense Their naming would have to be updated, too, also in TraCI
Todo:
: probably, the lane offsets to the center are not right
Definition at line 162 of file NIImporter_OpenDrive.cpp.
References NBEdge::addLane2LaneConnection(), NBNode::addTrafficLight(), buildConnectionsToOuter(), computeShapes(), NIImporter_OpenDrive::OpenDriveLink::contactPoint, DEBUG_COND, DEBUG_COND2, NIImporter_OpenDrive::OpenDriveLink::elementID, NIImporter_OpenDrive::OpenDriveLink::elementType, NIImporter_OpenDrive::OpenDriveEdge::from, NIImporter_OpenDrive::OpenDriveEdge::geom, StringBijection< T >::get(), OptionsCont::getBool(), PositionVector::getBoxBoundary(), NBEdge::getConnections(), NBNode::getControllingTLS(), NBNetBuilder::getEdgeCont(), OptionsCont::getFloat(), Named::getID(), NBEdge::getLaneStruct(), NBNetBuilder::getNodeCont(), OptionsCont::getOptions(), getOrBuildNode(), NBTypeCont::getPermissions(), NIImporter_OpenDrive::OpenDriveEdge::getPriority(), NBTypeCont::getSpeed(), OptionsCont::getStringVector(), PositionVector::getSubpart2D(), NBNetBuilder::getTLLogicCont(), NBEdge::getToNode(), NBNetBuilder::getTypeCont(), NBTypeCont::getWidth(), NIImporter_OpenDrive::OpenDriveEdge::id, NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), FileHelpers::isReadable(), NBNode::isTLControlled(), OptionsCont::isUsableFileList(), NIImporter_OpenDrive::OpenDriveEdge::junction, NBEdge::L2L_USER, NBEdge::L2L_VALIDATED, NIImporter_OpenDrive::OpenDriveEdge::laneSections, LANESPREAD_RIGHT, NIImporter_OpenDrive::OpenDriveEdge::length, PositionVector::length2D(), NIImporter_OpenDrive::OpenDriveEdge::links, NIImporter_OpenDrive::OpenDriveLink::linkType, myImportAllTypes, myImportWidths, myMinWidth, OPENDRIVE_CP_END, OPENDRIVE_CP_START, OPENDRIVE_ET_ROAD, OPENDRIVE_LT_PREDECESSOR, OPENDRIVE_LT_SUCCESSOR, OPENDRIVE_TAG_LEFT, OPENDRIVE_TAG_RIGHT, NBEdge::Lane::permissions, PositionVector::positionAtOffset(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, NBNodeCont::retrieve(), NBEdgeCont::retrieve(), PositionVector::reverse(), revertID(), revisitLaneSections(), XMLSubSys::runParser(), NIImporter_OpenDrive::OpenDriveLaneSection::s, setEdgeLinks2(), setNodeSecure(), Parameterised::setParameter(), NIImporter_OpenDrive::OpenDriveEdge::signals, NBEdge::Lane::speed, NIImporter_OpenDrive::OpenDriveLane::speed, splitMinWidths(), NIImporter_OpenDrive::OpenDriveEdge::streetName, SUMO_PARAM_ORIGID, SVC_AUTHORITY, SVC_BICYCLE, SVC_EMERGENCY, SVC_PEDESTRIAN, NIImporter_OpenDrive::OpenDriveEdge::to, toString(), SUMOXMLDefinitions::TrafficLightTypes, NIImporter_OpenDrive::OpenDriveLane::type, UNSET_CONNECTION, NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, NBEdgeCont::wasIgnored(), NBEdge::Lane::width, NIImporter_OpenDrive::OpenDriveLane::width, WRITE_ERROR, and WRITE_WARNING.
Referenced by NILoader::load().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void NIImporter_OpenDrive::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 1771 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::Connection::all, NIImporter_OpenDrive::OpenDriveEdge::connections, NIImporter_OpenDrive::Connection::fromCP, NIImporter_OpenDrive::Connection::fromEdge, NIImporter_OpenDrive::Connection::fromLane, NIImporter_OpenDrive::OpenDriveEdge::id, NIImporter_OpenDrive::OpenDriveEdge::laneSections, myConnectionWasEmpty, myCurrentConnectingRoad, myCurrentContactPoint, myCurrentEdge, myCurrentIncomingRoad, myEdges, myElementStack, myTypeContainer, OPENDRIVE_CP_END, OPENDRIVE_TAG_CONNECTION, OPENDRIVE_TAG_LANESECTION, OPENDRIVE_TAG_ROAD, NIImporter_OpenDrive::Connection::toCP, NIImporter_OpenDrive::Connection::toEdge, NIImporter_OpenDrive::Connection::toLane, and WRITE_ERROR.
myStartElement()
void NIImporter_OpenDrive::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
In dependence to the obtained type, an appropriate parsing method is called ("addEdge" if an edge encounters, f.e.).
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 1514 of file NIImporter_OpenDrive.cpp.
References addGeometryShape(), addLink(), NIImporter_OpenDrive::OpenDriveEdge::connections, DEBUG_COND, NIImporter_OpenDrive::OpenDriveEdge::elevations, NIImporter_OpenDrive::Connection::fromEdge, NIImporter_OpenDrive::OpenDriveEdge::geometries, SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), gPrecision, SUMOSAXAttributes::hasAttribute(), NIImporter_OpenDrive::OpenDriveEdge::id, NIImporter_OpenDrive::OpenDriveEdge::junction, NIImporter_OpenDrive::OpenDriveEdge::laneSections, MAX2(), myConnectionWasEmpty, myCurrentConnectingRoad, myCurrentContactPoint, myCurrentEdge, myCurrentIncomingRoad, myCurrentJunctionID, myCurrentLaneDirection, myEdges, myElementStack, NIImporter_OpenDrive::OpenDriveEdge::offsets, OPENDRIVE_ATTR_A, OPENDRIVE_ATTR_AU, OPENDRIVE_ATTR_AV, OPENDRIVE_ATTR_B, OPENDRIVE_ATTR_BU, OPENDRIVE_ATTR_BV, OPENDRIVE_ATTR_C, OPENDRIVE_ATTR_CONNECTINGROAD, OPENDRIVE_ATTR_CONTACTPOINT, OPENDRIVE_ATTR_CU, OPENDRIVE_ATTR_CURVATURE, OPENDRIVE_ATTR_CURVEND, OPENDRIVE_ATTR_CURVSTART, OPENDRIVE_ATTR_CV, OPENDRIVE_ATTR_D, OPENDRIVE_ATTR_DU, OPENDRIVE_ATTR_DV, OPENDRIVE_ATTR_DYNAMIC, OPENDRIVE_ATTR_ELEMENTID, OPENDRIVE_ATTR_ELEMENTTYPE, OPENDRIVE_ATTR_FROM, OPENDRIVE_ATTR_HDG, OPENDRIVE_ATTR_ID, OPENDRIVE_ATTR_INCOMINGROAD, OPENDRIVE_ATTR_JUNCTION, OPENDRIVE_ATTR_LENGTH, OPENDRIVE_ATTR_LEVEL, OPENDRIVE_ATTR_MAX, OPENDRIVE_ATTR_NAME, OPENDRIVE_ATTR_ORIENTATION, OPENDRIVE_ATTR_PRANGE, OPENDRIVE_ATTR_REVMAJOR, OPENDRIVE_ATTR_REVMINOR, OPENDRIVE_ATTR_S, OPENDRIVE_ATTR_SOFFSET, OPENDRIVE_ATTR_TO, OPENDRIVE_ATTR_TYPE, OPENDRIVE_ATTR_UNIT, OPENDRIVE_ATTR_X, OPENDRIVE_ATTR_Y, OPENDRIVE_CP_END, OPENDRIVE_CP_START, OPENDRIVE_GT_ARC, OPENDRIVE_GT_LINE, OPENDRIVE_GT_PARAMPOLY3, OPENDRIVE_GT_POLY3, OPENDRIVE_GT_SPIRAL, OPENDRIVE_LT_PREDECESSOR, OPENDRIVE_LT_SUCCESSOR, OPENDRIVE_TAG_ARC, OPENDRIVE_TAG_CENTER, OPENDRIVE_TAG_CONNECTION, OPENDRIVE_TAG_ELEVATION, OPENDRIVE_TAG_GEOMETRY, OPENDRIVE_TAG_HEADER, OPENDRIVE_TAG_JUNCTION, OPENDRIVE_TAG_LANE, OPENDRIVE_TAG_LANELINK, OPENDRIVE_TAG_LANEOFFSET, OPENDRIVE_TAG_LANESECTION, OPENDRIVE_TAG_LEFT, OPENDRIVE_TAG_LINE, OPENDRIVE_TAG_PARAMPOLY3, OPENDRIVE_TAG_POLY3, OPENDRIVE_TAG_PREDECESSOR, OPENDRIVE_TAG_RIGHT, OPENDRIVE_TAG_ROAD, OPENDRIVE_TAG_SIGNAL, OPENDRIVE_TAG_SPEED, OPENDRIVE_TAG_SPIRAL, OPENDRIVE_TAG_SUCCESSOR, OPENDRIVE_TAG_WIDTH, NIImporter_OpenDrive::OpenDriveEdge::signals, toString(), WRITE_ERROR, and WRITE_WARNING.
recomputeWidths() [1/2]
void NIImporter_OpenDrive::recomputeWidths (OpenDriveLaneSection & sec, double start, double end, double sectionStart, double sectionEnd) static protected
Definition at line 2043 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::OpenDriveLaneSection::lanesByDir, NIImporter_OpenDrive::OpenDriveLaneSection::leftLaneNumber, OPENDRIVE_TAG_LEFT, OPENDRIVE_TAG_RIGHT, and NIImporter_OpenDrive::OpenDriveLaneSection::rightLaneNumber.
Referenced by splitMinWidths().
recomputeWidths() [2/2]
void NIImporter_OpenDrive::recomputeWidths (std::vector< OpenDriveLane > & lanes, double start, double end, double sectionStart, double sectionEnd) static protected
Definition at line 2054 of file NIImporter_OpenDrive.cpp.
References gDebugFlag1, NIImporter_OpenDrive::OpenDriveLane::id, MAX2(), NIImporter_OpenDrive::OpenDriveLane::type, NIImporter_OpenDrive::OpenDriveLane::width, and NIImporter_OpenDrive::OpenDriveLane::widthData.
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
revertID()
std::string NIImporter_OpenDrive::revertID (const std::string & id) static private
Definition at line 857 of file NIImporter_OpenDrive.cpp.
Referenced by loadNetwork().
revisitLaneSections()
void NIImporter_OpenDrive::revisitLaneSections (const NBTypeCont & tc, std::map< std::string, OpenDriveEdge *> & edges) static protected
Rechecks lane sections of the given edges.
Parameters
[in] edges The edges which lane sections shall be reviewed
Definition at line 1026 of file NIImporter_OpenDrive.cpp.
References DEBUG_COND, gDebugFlag1, NIImporter_OpenDrive::OpenDriveEdge::id, NIImporter_OpenDrive::OpenDriveEdge::laneSections, POSITION_EPS, toString(), and WRITE_WARNING.
Referenced by loadNetwork().
setEdgeLinks2()
void NIImporter_OpenDrive::setEdgeLinks2 (OpenDriveEdge & e, const std::map< std::string, OpenDriveEdge *> & edges) static private
Definition at line 772 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::Connection::all, NIImporter_OpenDrive::OpenDriveEdge::connections, NIImporter_OpenDrive::OpenDriveLink::contactPoint, DEBUG_COND, DEBUG_COND2, NIImporter_OpenDrive::OpenDriveLink::elementID, NIImporter_OpenDrive::OpenDriveLink::elementType, NIImporter_OpenDrive::Connection::fromCP, NIImporter_OpenDrive::Connection::fromEdge, NIImporter_OpenDrive::Connection::fromLane, NIImporter_OpenDrive::OpenDriveEdge::id, joinToString(), NIImporter_OpenDrive::OpenDriveLaneSection::laneMap, NIImporter_OpenDrive::OpenDriveLaneSection::lanesByDir, NIImporter_OpenDrive::OpenDriveEdge::laneSections, NIImporter_OpenDrive::OpenDriveEdge::links, NIImporter_OpenDrive::OpenDriveLink::linkType, myImportAllTypes, OPENDRIVE_CP_END, OPENDRIVE_ET_ROAD, OPENDRIVE_LT_SUCCESSOR, OPENDRIVE_TAG_LEFT, OPENDRIVE_TAG_RIGHT, NIImporter_OpenDrive::OpenDriveLaneSection::s, NIImporter_OpenDrive::Connection::toCP, NIImporter_OpenDrive::Connection::toEdge, NIImporter_OpenDrive::Connection::toLane, and WRITE_ERROR.
Referenced by loadNetwork().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
setNodeSecure()
void NIImporter_OpenDrive::setNodeSecure (NBNodeCont & nc, OpenDriveEdge & e, const std::string & nodeID, NIImporter_OpenDrive::LinkType lt) static protected
Definition at line 880 of file NIImporter_OpenDrive.cpp.
References NIImporter_OpenDrive::OpenDriveEdge::from, NIImporter_OpenDrive::OpenDriveEdge::id, OPENDRIVE_LT_SUCCESSOR, NBNodeCont::retrieve(), and NIImporter_OpenDrive::OpenDriveEdge::to.
Referenced by loadNetwork().
setStraightConnections()
void NIImporter_OpenDrive::setStraightConnections (std::vector< OpenDriveLane > & lanes) static protected
Definition at line 2035 of file NIImporter_OpenDrive.cpp.
Referenced by splitMinWidths().
splitMinWidths()
void NIImporter_OpenDrive::splitMinWidths (OpenDriveEdge * e, const NBTypeCont & tc, double minDist) static protected
Definition at line 1860 of file NIImporter_OpenDrive.cpp.
References DEBUG_COND, findWidthSplit(), gDebugFlag1, NIImporter_OpenDrive::OpenDriveEdge::id, NIImporter_OpenDrive::OpenDriveLaneSection::lanesByDir, NIImporter_OpenDrive::OpenDriveEdge::laneSections, NIImporter_OpenDrive::OpenDriveLaneSection::leftLaneNumber, NIImporter_OpenDrive::OpenDriveEdge::length, OPENDRIVE_TAG_LEFT, OPENDRIVE_TAG_RIGHT, recomputeWidths(), NIImporter_OpenDrive::OpenDriveLaneSection::rightLaneNumber, NIImporter_OpenDrive::OpenDriveLaneSection::s, setStraightConnections(), NIImporter_OpenDrive::OpenDriveLaneSection::sOrig, and toString().
Referenced by loadNetwork().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Friends And Related Function Documentation
operator<
bool operator< (const Connection & c1, const Connection & c2) friend
Definition at line 1845 of file NIImporter_OpenDrive.cpp.
Field Documentation
myConnectionWasEmpty
bool NIImporter_OpenDrive::myConnectionWasEmpty private
Definition at line 537 of file NIImporter_OpenDrive.h.
Referenced by myEndElement(), and myStartElement().
myCurrentConnectingRoad
std::string NIImporter_OpenDrive::myCurrentConnectingRoad private
Definition at line 535 of file NIImporter_OpenDrive.h.
Referenced by myEndElement(), and myStartElement().
myCurrentContactPoint
ContactPoint NIImporter_OpenDrive::myCurrentContactPoint private
Definition at line 536 of file NIImporter_OpenDrive.h.
Referenced by myEndElement(), and myStartElement().
myCurrentEdge
OpenDriveEdge NIImporter_OpenDrive::myCurrentEdge private
Definition at line 528 of file NIImporter_OpenDrive.h.
Referenced by addGeometryShape(), addLink(), myEndElement(), and myStartElement().
myCurrentIncomingRoad
std::string NIImporter_OpenDrive::myCurrentIncomingRoad private
Definition at line 534 of file NIImporter_OpenDrive.h.
Referenced by myEndElement(), and myStartElement().
myCurrentJunctionID
std::string NIImporter_OpenDrive::myCurrentJunctionID private
Definition at line 533 of file NIImporter_OpenDrive.h.
Referenced by myStartElement().
myCurrentLaneDirection
OpenDriveXMLTag NIImporter_OpenDrive::myCurrentLaneDirection private
Definition at line 532 of file NIImporter_OpenDrive.h.
Referenced by myStartElement().
myEdges
std::map<std::string, OpenDriveEdge*>& NIImporter_OpenDrive::myEdges private
Definition at line 530 of file NIImporter_OpenDrive.h.
Referenced by myEndElement(), and myStartElement().
myElementStack
std::vector<int> NIImporter_OpenDrive::myElementStack private
Definition at line 531 of file NIImporter_OpenDrive.h.
Referenced by myEndElement(), and myStartElement().
myImportAllTypes
bool NIImporter_OpenDrive::myImportAllTypes static private
Definition at line 539 of file NIImporter_OpenDrive.h.
Referenced by NIImporter_OpenDrive::OpenDriveLaneSection::buildLaneMapping(), loadNetwork(), and setEdgeLinks2().
myImportWidths
bool NIImporter_OpenDrive::myImportWidths static private
Definition at line 540 of file NIImporter_OpenDrive.h.
Referenced by loadNetwork().
myMinWidth
double NIImporter_OpenDrive::myMinWidth static private
Definition at line 541 of file NIImporter_OpenDrive.h.
Referenced by findWidthSplit(), and loadNetwork().
myTypeContainer
const NBTypeCont& NIImporter_OpenDrive::myTypeContainer private
Definition at line 527 of file NIImporter_OpenDrive.h.
Referenced by myEndElement().
openDriveAttrs
StringBijection< int >::Entry NIImporter_OpenDrive::openDriveAttrs static protected
The names of openDrive-XML attributes (for passing to GenericSAXHandler)
Definition at line 602 of file NIImporter_OpenDrive.h.
openDriveTags
StringBijection< int >::Entry NIImporter_OpenDrive::openDriveTags static protected
Initial value:
= {
    { "header",           NIImporter_OpenDrive::OPENDRIVE_TAG_HEADER },
    { "road",             NIImporter_OpenDrive::OPENDRIVE_TAG_ROAD },
    { "predecessor",      NIImporter_OpenDrive::OPENDRIVE_TAG_PREDECESSOR },
    { "successor",        NIImporter_OpenDrive::OPENDRIVE_TAG_SUCCESSOR },
    { "geometry",         NIImporter_OpenDrive::OPENDRIVE_TAG_GEOMETRY },
    { "line",             NIImporter_OpenDrive::OPENDRIVE_TAG_LINE },
    { "spiral",           NIImporter_OpenDrive::OPENDRIVE_TAG_SPIRAL },
    { "arc",              NIImporter_OpenDrive::OPENDRIVE_TAG_ARC },
    { "poly3",            NIImporter_OpenDrive::OPENDRIVE_TAG_POLY3 },
    { "paramPoly3",       NIImporter_OpenDrive::OPENDRIVE_TAG_PARAMPOLY3 },
    { "laneSection",      NIImporter_OpenDrive::OPENDRIVE_TAG_LANESECTION },
    { "laneOffset",       NIImporter_OpenDrive::OPENDRIVE_TAG_LANEOFFSET },
    { "left",             NIImporter_OpenDrive::OPENDRIVE_TAG_LEFT },
    { "center",           NIImporter_OpenDrive::OPENDRIVE_TAG_CENTER },
    { "right",            NIImporter_OpenDrive::OPENDRIVE_TAG_RIGHT },
    { "lane",             NIImporter_OpenDrive::OPENDRIVE_TAG_LANE },
    { "signal",           NIImporter_OpenDrive::OPENDRIVE_TAG_SIGNAL },
    { "junction",         NIImporter_OpenDrive::OPENDRIVE_TAG_JUNCTION },
    { "connection",       NIImporter_OpenDrive::OPENDRIVE_TAG_CONNECTION },
    { "laneLink",         NIImporter_OpenDrive::OPENDRIVE_TAG_LANELINK },
    { "width",            NIImporter_OpenDrive::OPENDRIVE_TAG_WIDTH },
    { "speed",            NIImporter_OpenDrive::OPENDRIVE_TAG_SPEED },
    { "elevation",        NIImporter_OpenDrive::OPENDRIVE_TAG_ELEVATION },
    { "",                 NIImporter_OpenDrive::OPENDRIVE_TAG_NOTHING }
}
The names of openDrive-XML elements (for passing to GenericSAXHandler)
Definition at line 599 of file NIImporter_OpenDrive.h.
The documentation for this class was generated from the following files:
NIImporter_OpenDrive.h
NIImporter_OpenDrive.cpp