SUMO - Simulation of Urban MObility: GNEFrame::NeteditAttributes Class Reference
GNEFrame::NeteditAttributes Class Reference
#include <GNEFrame.h>
Public Member Functions
void hideNeteditAttributes ()
hide NeteditAttributes
bool isBlockMovementEnabled () const
check if block movement is enabled
bool isBlockShapeEnabled () const
check if block shape is enabled
bool isCloseShapeEnabled () const
check if clse shape is enabled
NeteditAttributes (GNEFrame *frameParent)
FOX-declaration.
void showNeteditAttributes (bool shapeEditing)
show NeteditAttributes
~NeteditAttributes ()
destructor
FOX-callbacks
Called when user changes the checkbox "set blocking movement"
long onCmdSetBlockMovement (FXObject *, FXSelector, void *)
long onCmdSetBlockShape (FXObject *, FXSelector, void *)
Called when user changes the checkbox "set blocking shape".
long onCmdsetClosingShape (FXObject *, FXSelector, void *)
Called when the user change checkbox for open/closed polygon.
Protected Member Functions
NeteditAttributes ()
FOX needs this.
Private Attributes
FXCheckButton * myBlockMovementCheckButton
checkBox for block movement
FXLabel * myBlockMovementLabel
Label for block movement.
FXCheckButton * myBlockShapeCheckButton
checkBox for block shape
FXHorizontalFrame * myBlockShapeFrame
frame for Block shape
FXLabel * myBlockShapeLabel
Label for block shape.
FXCheckButton * myClosePolygonCheckButton
checkbox to enable/disable closing polygon
FXHorizontalFrame * myClosePolygonFrame
Frame for open/close polygon.
FXLabel * myClosePolygonLabel
Label for open/close polygon.
GNEFrame * myFrameParent
GNEFrame parent.
Detailed Description
Definition at line 62 of file GNEFrame.h.
Constructor & Destructor Documentation
NeteditAttributes() [1/2]
GNEFrame::NeteditAttributes::NeteditAttributes (GNEFrame * frameParent)
FOX-declaration.
constructor
Definition at line 84 of file GNEFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignCheckButtonAttribute, GUIDesignLabelAttribute, MID_GNE_ADDITIONALFRAME_BLOCKMOVEMENT, MID_GNE_POLYGONFRAME_CLOSE, and MID_GNE_SET_BLOCKING_SHAPE.
~NeteditAttributes()
GNEFrame::NeteditAttributes::~NeteditAttributes ()
destructor
Definition at line 104 of file GNEFrame.cpp.
NeteditAttributes() [2/2]
GNEFrame::NeteditAttributes::NeteditAttributes () inline protected
FOX needs this.
Definition at line 102 of file GNEFrame.h.
Member Function Documentation
hideNeteditAttributes()
void GNEFrame::NeteditAttributes::hideNeteditAttributes ()
hide NeteditAttributes
Definition at line 122 of file GNEFrame.cpp.
Referenced by GNEPolygonFrame::onCmdSelectShape().
isBlockMovementEnabled()
bool GNEFrame::NeteditAttributes::isBlockMovementEnabled () const
check if block movement is enabled
Definition at line 128 of file GNEFrame.cpp.
References myBlockMovementCheckButton.
Referenced by GNEPolygonFrame::buildPoly(), and GNEPolygonFrame::processClick().
isBlockShapeEnabled()
bool GNEFrame::NeteditAttributes::isBlockShapeEnabled () const
check if block shape is enabled
Definition at line 134 of file GNEFrame.cpp.
References myBlockShapeCheckButton.
Referenced by GNEPolygonFrame::buildPoly().
isCloseShapeEnabled()
bool GNEFrame::NeteditAttributes::isCloseShapeEnabled () const
check if clse shape is enabled
Definition at line 140 of file GNEFrame.cpp.
References myClosePolygonCheckButton.
Referenced by GNEFrame::DrawingMode::stopDrawing().
onCmdSetBlockMovement()
long GNEFrame::NeteditAttributes::onCmdSetBlockMovement (FXObject * , FXSelector , void *)
Definition at line 146 of file GNEFrame.cpp.
References myBlockMovementCheckButton.
onCmdSetBlockShape()
long GNEFrame::NeteditAttributes::onCmdSetBlockShape (FXObject * , FXSelector , void *)
Called when user changes the checkbox "set blocking shape".
Definition at line 157 of file GNEFrame.cpp.
References myBlockShapeCheckButton.
onCmdsetClosingShape()
long GNEFrame::NeteditAttributes::onCmdsetClosingShape (FXObject * , FXSelector , void *)
Called when the user change checkbox for open/closed polygon.
Definition at line 168 of file GNEFrame.cpp.
References myClosePolygonCheckButton.
showNeteditAttributes()
void GNEFrame::NeteditAttributes::showNeteditAttributes (bool shapeEditing)
show NeteditAttributes
Definition at line 108 of file GNEFrame.cpp.
References myBlockShapeFrame, and myClosePolygonFrame.
Referenced by GNEPolygonFrame::onCmdSelectShape().
Field Documentation
myBlockMovementCheckButton
FXCheckButton* GNEFrame::NeteditAttributes::myBlockMovementCheckButton private
checkBox for block movement
Definition at line 112 of file GNEFrame.h.
Referenced by isBlockMovementEnabled(), and onCmdSetBlockMovement().
myBlockMovementLabel
FXLabel* GNEFrame::NeteditAttributes::myBlockMovementLabel private
Label for block movement.
Definition at line 109 of file GNEFrame.h.
myBlockShapeCheckButton
FXCheckButton* GNEFrame::NeteditAttributes::myBlockShapeCheckButton private
checkBox for block shape
Definition at line 121 of file GNEFrame.h.
Referenced by isBlockShapeEnabled(), and onCmdSetBlockShape().
myBlockShapeFrame
FXHorizontalFrame* GNEFrame::NeteditAttributes::myBlockShapeFrame private
frame for Block shape
Definition at line 115 of file GNEFrame.h.
Referenced by showNeteditAttributes().
myBlockShapeLabel
FXLabel* GNEFrame::NeteditAttributes::myBlockShapeLabel private
Label for block shape.
Definition at line 118 of file GNEFrame.h.
myClosePolygonCheckButton
FXCheckButton* GNEFrame::NeteditAttributes::myClosePolygonCheckButton private
checkbox to enable/disable closing polygon
Definition at line 130 of file GNEFrame.h.
Referenced by isCloseShapeEnabled(), and onCmdsetClosingShape().
myClosePolygonFrame
FXHorizontalFrame* GNEFrame::NeteditAttributes::myClosePolygonFrame private
Frame for open/close polygon.
Definition at line 124 of file GNEFrame.h.
Referenced by showNeteditAttributes().
myClosePolygonLabel
FXLabel* GNEFrame::NeteditAttributes::myClosePolygonLabel private
Label for open/close polygon.
Definition at line 127 of file GNEFrame.h.
myFrameParent
GNEFrame* GNEFrame::NeteditAttributes::myFrameParent private
GNEFrame parent.
Definition at line 106 of file GNEFrame.h.
The documentation for this class was generated from the following files:
GNEFrame.h
GNEFrame.cpp