SUMO - Simulation of Urban MObility: NIVisumTL Class Reference
NIVisumTL Class Reference
Intermediate class for storing visum traffic lights during their import.
#include <NIVisumTL.h>
Data Structures
class Phase
A phase.
class SignalGroup
A signal group can be defined either by a time period or by phases.
class TimePeriod
A time period with a start and an end time.
Public Member Functions
void addNode (NBNode *n)
Adds a node to control.
void addPhase (const std::string &name, SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
Adds a phase.
void addSignalGroup (const std::string &name, SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
Adds a signal group.
void build (NBEdgeCont &ec, NBTrafficLightLogicCont &tlc)
build the traffic light and add it to the given container
std::map< std::string, Phase * > & getPhases ()
Returns the map of named phases.
SignalGroup & getSignalGroup (const std::string &name)
Returns the named signal group.
NIVisumTL (const std::string &name, SUMOTime cycleTime, SUMOTime offset, SUMOTime intermediateTime, bool phaseDefined)
Constructor.
~NIVisumTL ()
Destructor.
Private Attributes
SUMOTime myCycleTime
The cycle time of traffic light in seconds.
SUMOTime myIntermediateTime
The all-red time (unused here)
std::string myName
The name of traffic light.
std::vector< NBNode * > myNodes
Vector of nodes belonging to this traffic light.
SUMOTime myOffset
The offset in the plan.
bool myPhaseDefined
Toogles the usage either of phases or of time periods in signal groups.
std::map< std::string, Phase * > myPhases
Map of used phases if phases defined.
std::map< std::string, SignalGroup * > mySignalGroups
Map of used signal groups.
Detailed Description
Intermediate class for storing visum traffic lights during their import.
Definition at line 50 of file NIVisumTL.h.
Constructor & Destructor Documentation
NIVisumTL()
NIVisumTL::NIVisumTL (const std::string & name, SUMOTime cycleTime, SUMOTime offset, SUMOTime intermediateTime, bool phaseDefined)
Constructor.
Parameters
[in] name The name of the TLS
[in] cycleTime The cycle time of the TLS
[in] offset Seconds to skip
[in] intermediateTime The name of the TLS
[in] phaseDefined Whether phases are defined
Definition at line 43 of file NIVisumTL.cpp.
~NIVisumTL()
NIVisumTL::~NIVisumTL ()
Destructor.
Definition at line 50 of file NIVisumTL.cpp.
References myPhases, and mySignalGroups.
Member Function Documentation
addNode()
void NIVisumTL::addNode (NBNode * n) inline
Adds a node to control.
Definition at line 153 of file NIVisumTL.h.
References addPhase(), addSignalGroup(), and myNodes.
addPhase()
void NIVisumTL::addPhase (const std::string & name, SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
Adds a phase.
Definition at line 67 of file NIVisumTL.cpp.
References myPhases.
Referenced by addNode().
addSignalGroup()
void NIVisumTL::addSignalGroup (const std::string & name, SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
Adds a signal group.
Definition at line 61 of file NIVisumTL.cpp.
References mySignalGroups.
Referenced by addNode().
build()
void NIVisumTL::build (NBEdgeCont & ec, NBTrafficLightLogicCont & tlc)
build the traffic light and add it to the given container
Definition at line 79 of file NIVisumTL.cpp.
References NBLoadedTLDef::addSignalGroup(), NBLoadedTLDef::addSignalGroupPhaseBegin(), NBLoadedTLDef::addToSignalGroup(), NIVisumTL::SignalGroup::connections(), StringBijection< T >::get(), NIVisumTL::TimePeriod::getEndTime(), Named::getID(), OptionsCont::getOptions(), NIVisumTL::TimePeriod::getStartTime(), NIVisumTL::TimePeriod::getYellowTime(), NBTrafficLightLogicCont::insert(), MAX2(), myCycleTime, myIntermediateTime, myNodes, myOffset, myPhaseDefined, mySignalGroups, NIVisumTL::SignalGroup::phases(), NBLoadedTLDef::setCycleDuration(), NBLoadedTLDef::setSignalYellowTimes(), NBTrafficLightDefinition::TLCOLOR_GREEN, NBTrafficLightDefinition::TLCOLOR_RED, and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by getPhases().
getPhases()
std::map<std::string, Phase*>& NIVisumTL::getPhases () inline
Returns the map of named phases.
Definition at line 164 of file NIVisumTL.h.
References build(), getSignalGroup(), and myPhases.
getSignalGroup()
NIVisumTL::SignalGroup & NIVisumTL::getSignalGroup (const std::string & name)
Returns the named signal group.
Definition at line 73 of file NIVisumTL.cpp.
References mySignalGroups.
Referenced by getPhases().
Field Documentation
myCycleTime
SUMOTime NIVisumTL::myCycleTime private
The cycle time of traffic light in seconds.
Definition at line 179 of file NIVisumTL.h.
Referenced by build().
myIntermediateTime
SUMOTime NIVisumTL::myIntermediateTime private
The all-red time (unused here)
Definition at line 185 of file NIVisumTL.h.
Referenced by build().
myName
std::string NIVisumTL::myName private
The name of traffic light.
Definition at line 176 of file NIVisumTL.h.
myNodes
std::vector<NBNode*> NIVisumTL::myNodes private
Vector of nodes belonging to this traffic light.
Definition at line 191 of file NIVisumTL.h.
Referenced by addNode(), and build().
myOffset
SUMOTime NIVisumTL::myOffset private
The offset in the plan.
Definition at line 182 of file NIVisumTL.h.
Referenced by build().
myPhaseDefined
bool NIVisumTL::myPhaseDefined private
Toogles the usage either of phases or of time periods in signal groups.
Definition at line 188 of file NIVisumTL.h.
Referenced by build().
myPhases
std::map<std::string, Phase*> NIVisumTL::myPhases private
Map of used phases if phases defined.
Definition at line 194 of file NIVisumTL.h.
Referenced by addPhase(), getPhases(), NIVisumTL::SignalGroup::phases(), and ~NIVisumTL().
mySignalGroups
std::map<std::string, SignalGroup*> NIVisumTL::mySignalGroups private
Map of used signal groups.
Definition at line 197 of file NIVisumTL.h.
Referenced by addSignalGroup(), build(), getSignalGroup(), and ~NIVisumTL().
The documentation for this class was generated from the following files:
NIVisumTL.h
NIVisumTL.cpp