SUMO - Simulation of Urban MObility: CHRouterWrapper< E, V, PF > Class Template Reference
CHRouterWrapper< E, V, PF > Class Template Reference
Computes the shortest path through a contracted network.
#include <CHRouterWrapper.h>
Public Types
typedef double(* Operation) (const E *const, const V *const, double)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
CHRouterWrapper (const std::vector< E *> &edges, const bool ignoreErrors, Operation operation, const SUMOTime begin, const SUMOTime end, const SUMOTime weightPeriod, const int numThreads)
Constructor.
virtual SUMOAbstractRouter< E, V > * clone ()
bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
double getEffort (const E *const e, const V *const v, double t) const
double recomputeCosts (const std::vector< const E *> &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
~CHRouterWrapper ()
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Types
typedef CHRouter< E, V, noProhibitions< E, V > > CHRouterType
typedef std::map< std::pair< const SUMOVehicleClass, const double >, std::vector< CHRouterType * > > RouterMap
Private Attributes
const SUMOTime myBegin
const std::vector< E * > & myEdges
all edges with numerical ids
const SUMOTime myEnd
const bool myIgnoreErrors
const int myMaxNumInstances
RouterMap myRouters
const SUMOTime myWeightPeriod
Detailed Description
template<class E, class V, class PF>
class CHRouterWrapper< E, V, PF >
Computes the shortest path through a contracted network.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 71 of file CHRouterWrapper.h.
Member Typedef Documentation
CHRouterType
template<class E, class V, class PF> typedef CHRouter<E, V, noProhibitions<E, V> > CHRouterWrapper< E, V, PF >::CHRouterType private
Definition at line 167 of file CHRouterWrapper.h.
Operation
template<class E, class V, class PF> typedef double(* CHRouterWrapper< E, V, PF >::Operation) (const E *const, const V *const, double)
Type of the function that is used to retrieve the edge effort.
Definition at line 75 of file CHRouterWrapper.h.
RouterMap
template<class E, class V, class PF> typedef std::map<std::pair<const SUMOVehicleClass, const double>, std::vector<CHRouterType*> > CHRouterWrapper< E, V, PF >::RouterMap private
Definition at line 194 of file CHRouterWrapper.h.
Constructor & Destructor Documentation
CHRouterWrapper()
template<class E, class V, class PF> CHRouterWrapper< E, V, PF >::CHRouterWrapper (const std::vector< E *> & edges, const bool ignoreErrors, Operation operation, const SUMOTime begin, const SUMOTime end, const SUMOTime weightPeriod, const int numThreads) inline
Constructor.
Definition at line 79 of file CHRouterWrapper.h.
~CHRouterWrapper()
template<class E, class V, class PF> CHRouterWrapper< E, V, PF >::~CHRouterWrapper () inline
Definition at line 90 of file CHRouterWrapper.h.
References CHRouterWrapper< E, V, PF >::myRouters.
Member Function Documentation
clone()
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* CHRouterWrapper< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 99 of file CHRouterWrapper.h.
References CHRouterWrapper< E, V, PF >::myBegin, CHRouterWrapper< E, V, PF >::myEdges, CHRouterWrapper< E, V, PF >::myEnd, CHRouterWrapper< E, V, PF >::myIgnoreErrors, CHRouterWrapper< E, V, PF >::myMaxNumInstances, SUMOAbstractRouter< E, V >::myOperation, CHRouterWrapper< E, V, PF >::myRouters, and CHRouterWrapper< E, V, PF >::myWeightPeriod.
compute()
template<class E, class V, class PF> bool CHRouterWrapper< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 110 of file CHRouterWrapper.h.
References CHRouterWrapper< E, V, PF >::myBegin, CHRouterWrapper< E, V, PF >::myEdges, CHRouterWrapper< E, V, PF >::myEnd, CHRouterWrapper< E, V, PF >::myIgnoreErrors, CHRouterWrapper< E, V, PF >::myMaxNumInstances, CHRouterWrapper< E, V, PF >::myRouters, and CHRouterWrapper< E, V, PF >::myWeightPeriod.
endQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
getEffort()
template<class E, class V> double SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHBuilder< E, V >::synchronize().
recomputeCosts()
template<class E, class V, class PF> double CHRouterWrapper< E, V, PF >::recomputeCosts (const std::vector< const E *> & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 151 of file CHRouterWrapper.h.
References SUMOAbstractRouter< E, V >::getEffort(), STEPS2TIME, and WRITE_WARNING.
setBulkMode()
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
startQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
myBegin
template<class E, class V, class PF> const SUMOTime CHRouterWrapper< E, V, PF >::myBegin private
Definition at line 203 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
myBulkMode
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
myEdges
template<class E, class V, class PF> const std::vector<E*>& CHRouterWrapper< E, V, PF >::myEdges private
all edges with numerical ids
Definition at line 199 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
myEnd
template<class E, class V, class PF> const SUMOTime CHRouterWrapper< E, V, PF >::myEnd private
Definition at line 204 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
myIgnoreErrors
template<class E, class V, class PF> const bool CHRouterWrapper< E, V, PF >::myIgnoreErrors private
Definition at line 201 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
myMaxNumInstances
template<class E, class V, class PF> const int CHRouterWrapper< E, V, PF >::myMaxNumInstances private
Definition at line 206 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
myOperation
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
myRouters
template<class E, class V, class PF> RouterMap CHRouterWrapper< E, V, PF >::myRouters private
Definition at line 196 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), CHRouterWrapper< E, V, PF >::compute(), and CHRouterWrapper< E, V, PF >::~CHRouterWrapper().
myWeightPeriod
template<class E, class V, class PF> const SUMOTime CHRouterWrapper< E, V, PF >::myWeightPeriod private
Definition at line 205 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
The documentation for this class was generated from the following file:
CHRouterWrapper.h