SUMO - Simulation of Urban MObility: NIVissimSource Class Reference
NIVissimSource Class Reference
#include <NIVissimSource.h>
Public Member Functions
NIVissimSource (const std::string &id, const std::string &name, const std::string &edgeid)
~NIVissimSource ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (const std::string &id, const std::string &name, const std::string &edgeid)
static bool dictionary (const std::string &id, NIVissimSource *o)
static NIVissimSource * dictionary (const std::string &id)
Private Types
typedef std::map< std::string, NIVissimSource * > DictType
Private Attributes
std::string myEdgeID
std::string myID
std::string myName
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 42 of file NIVissimSource.h.
Member Typedef Documentation
DictType
typedef std::map<std::string, NIVissimSource*> NIVissimSource::DictType private
Definition at line 58 of file NIVissimSource.h.
Constructor & Destructor Documentation
NIVissimSource()
NIVissimSource::NIVissimSource (const std::string & id, const std::string & name, const std::string & edgeid)
Definition at line 37 of file NIVissimSource.cpp.
Referenced by dictionary().
~NIVissimSource()
NIVissimSource::~NIVissimSource ()
Definition at line 42 of file NIVissimSource.cpp.
Member Function Documentation
clearDict()
void NIVissimSource::clearDict () static
Definition at line 79 of file NIVissimSource.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/3]
bool NIVissimSource::dictionary (const std::string & id, const std::string & name, const std::string & edgeid) static
Definition at line 46 of file NIVissimSource.cpp.
References NIVissimSource().
Referenced by NIImporter_Vissim::NIVissimXMLHandler_Zuflussdefinition::myStartElement(), and NIVissimSingleTypeParser_Zuflussdefinition::parse().
dictionary() [2/3]
bool NIVissimSource::dictionary (const std::string & id, NIVissimSource * o) static
Definition at line 58 of file NIVissimSource.cpp.
References myDict.
dictionary() [3/3]
NIVissimSource * NIVissimSource::dictionary (const std::string & id) static
Definition at line 69 of file NIVissimSource.cpp.
References myDict.
Field Documentation
myDict
NIVissimSource::DictType NIVissimSource::myDict static private
Definition at line 59 of file NIVissimSource.h.
Referenced by clearDict(), and dictionary().
myEdgeID
std::string NIVissimSource::myEdgeID private
Definition at line 55 of file NIVissimSource.h.
myID
std::string NIVissimSource::myID private
Definition at line 53 of file NIVissimSource.h.
myName
std::string NIVissimSource::myName private
Definition at line 54 of file NIVissimSource.h.
The documentation for this class was generated from the following files:
NIVissimSource.h
NIVissimSource.cpp