SUMO - Simulation of Urban MObility: NIVissimClosures Class Reference
NIVissimClosures Class Reference
#include <NIVissimClosures.h>
Public Member Functions
NIVissimClosures (const std::string &id, int from_node, int to_node, std::vector< int > &overEdges)
~NIVissimClosures ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (const std::string &id, int from_node, int to_node, std::vector< int > &overEdges)
static bool dictionary (const std::string &name, NIVissimClosures *o)
static NIVissimClosures * dictionary (const std::string &name)
Private Types
typedef std::map< std::string, NIVissimClosures * > DictType
Private Member Functions
NIVissimClosures (const NIVissimClosures &s)
invalidated copy constructor
NIVissimClosures & operator= (const NIVissimClosures &s)
invalidated assignment operator
Private Attributes
int myFromNode
const std::string myID
std::vector< int > myOverEdges
int myToNode
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 43 of file NIVissimClosures.h.
Member Typedef Documentation
DictType
typedef std::map<std::string, NIVissimClosures*> NIVissimClosures::DictType private
Definition at line 55 of file NIVissimClosures.h.
Constructor & Destructor Documentation
NIVissimClosures() [1/2]
NIVissimClosures::NIVissimClosures (const std::string & id, int from_node, int to_node, std::vector< int > & overEdges)
Definition at line 38 of file NIVissimClosures.cpp.
Referenced by dictionary().
~NIVissimClosures()
NIVissimClosures::~NIVissimClosures ()
Definition at line 45 of file NIVissimClosures.cpp.
NIVissimClosures() [2/2]
NIVissimClosures::NIVissimClosures (const NIVissimClosures & s) private
invalidated copy constructor
Member Function Documentation
clearDict()
void NIVissimClosures::clearDict () static
Definition at line 85 of file NIVissimClosures.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/3]
bool NIVissimClosures::dictionary (const std::string & id, int from_node, int to_node, std::vector< int > & overEdges) static
Definition at line 49 of file NIVissimClosures.cpp.
References NIVissimClosures().
Referenced by NIVissimSingleTypeParser_Kantensperrung::parse().
dictionary() [2/3]
bool NIVissimClosures::dictionary (const std::string & name, NIVissimClosures * o) static
Definition at line 63 of file NIVissimClosures.cpp.
References myDict.
dictionary() [3/3]
NIVissimClosures * NIVissimClosures::dictionary (const std::string & name) static
Definition at line 74 of file NIVissimClosures.cpp.
References myDict.
operator=()
NIVissimClosures& NIVissimClosures::operator= (const NIVissimClosures & s) private
invalidated assignment operator
Field Documentation
myDict
NIVissimClosures::DictType NIVissimClosures::myDict static private
Definition at line 56 of file NIVissimClosures.h.
Referenced by clearDict(), and dictionary().
myFromNode
int NIVissimClosures::myFromNode private
Definition at line 58 of file NIVissimClosures.h.
myID
const std::string NIVissimClosures::myID private
Definition at line 57 of file NIVissimClosures.h.
myOverEdges
std::vector<int> NIVissimClosures::myOverEdges private
Definition at line 59 of file NIVissimClosures.h.
myToNode
int NIVissimClosures::myToNode private
Definition at line 58 of file NIVissimClosures.h.
The documentation for this class was generated from the following files:
NIVissimClosures.h
NIVissimClosures.cpp