SUMO - Simulation of Urban MObility: LandmarkLookupTable< E, V > Class Template Reference
LandmarkLookupTable< E, V > Class Template Reference
Computes the shortest path through a network using the A* algorithm.
#include <AStarLookupTable.h>
Public Member Functions
bool consistent () const
whether the heuristic ist consistent (found nodes are always visited on the shortest path the first time)
LandmarkLookupTable (const std::string &filename, const std::vector< E *> &edges, SUMOAbstractRouter< E, V > *router, const V *defaultVehicle, const std::string &outfile, const int maxNumThreads)
double lowerBound (const E *from, const E *to, double speed, double speedFactor, double fromEffort, double toEffort) const
provide a lower bound on the distance between from and to (excluding traveltime of both edges)
Private Member Functions
std::string getLandmark (int i) const
Private Attributes
int myFirstNonInternal
std::vector< std::vector< double > > myFromLandmarkDists
std::map< std::string, int > myLandmarks
std::vector< std::vector< double > > myToLandmarkDists
Detailed Description
template<class E, class V>
class LandmarkLookupTable< E, V >
Computes the shortest path through a network using the A* algorithm.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
EC The class to retrieve the effort for an edge from
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 104 of file AStarLookupTable.h.
Constructor & Destructor Documentation
LandmarkLookupTable()
template<class E , class V > LandmarkLookupTable< E, V >::LandmarkLookupTable (const std::string & filename, const std::vector< E *> & edges, SUMOAbstractRouter< E, V > * router, const V * defaultVehicle, const std::string & outfile, const int maxNumThreads) inline
Definition at line 106 of file AStarLookupTable.h.
References TplConvert::_2double(), FXWorkerThread::Pool::add(), SUMOAbstractRouter< E, V >::clone(), SUMOAbstractRouter< E, V >::compute(), StringTokenizer::get(), MAX2(), SUMOAbstractRouter< E, V >::recomputeCosts(), StringTokenizer::size(), FXWorkerThread::Pool::size(), FXWorkerThread::Pool::waitAll(), and WRITE_WARNING.
Member Function Documentation
consistent()
template<class E , class V > bool LandmarkLookupTable< E, V >::consistent () const inline virtual
whether the heuristic ist consistent (found nodes are always visited on the shortest path the first time)
Implements AbstractLookupTable< E, V >.
Definition at line 331 of file AStarLookupTable.h.
getLandmark()
template<class E , class V > std::string LandmarkLookupTable< E, V >::getLandmark (int i) const inline private
Definition at line 389 of file AStarLookupTable.h.
lowerBound()
template<class E , class V > double LandmarkLookupTable< E, V >::lowerBound (const E * from, const E * to, double speed, double speedFactor, double fromEffort, double toEffort) const inline virtual
provide a lower bound on the distance between from and to (excluding traveltime of both edges)
Implements AbstractLookupTable< E, V >.
Definition at line 283 of file AStarLookupTable.h.
References MAX2(), and UNREACHABLE.
Field Documentation
myFirstNonInternal
template<class E , class V > int LandmarkLookupTable< E, V >::myFirstNonInternal private
Definition at line 339 of file AStarLookupTable.h.
myFromLandmarkDists
template<class E , class V > std::vector<std::vector<double> > LandmarkLookupTable< E, V >::myFromLandmarkDists private
Definition at line 337 of file AStarLookupTable.h.
myLandmarks
template<class E , class V > std::map<std::string, int> LandmarkLookupTable< E, V >::myLandmarks private
Definition at line 336 of file AStarLookupTable.h.
myToLandmarkDists
template<class E , class V > std::vector<std::vector<double> > LandmarkLookupTable< E, V >::myToLandmarkDists private
Definition at line 338 of file AStarLookupTable.h.
The documentation for this class was generated from the following file:
AStarLookupTable.h