SUMO - Simulation of Urban MObility: MSPModel_NonInteracting::PState Class Reference
MSPModel_NonInteracting::PState Class Reference
abstract base class for managing callbacks to retrieve various state information from the model
Public Member Functions
SUMOTime computeWalkingTime (const MSEdge *prev, const MSPerson::MSPersonStage_Walking &stage, SUMOTime currentTime)
compute walking time on edge and update state members
MoveToNextEdge * getCommand ()
virtual void moveToXY (MSPerson *p, Position pos, MSLane *lane, double lanePos, double lanePosLat, double angle, int routeOffset, const ConstMSEdgeVector &edges, SUMOTime t)
try to move person to the given position
PState (MoveToNextEdge *cmd)
double getEdgePos (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
abstract methods inherited from PedestrianState
Position getPosition (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the network coordinate of the person
double getAngle (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the direction in which the person faces in degrees
SUMOTime getWaitingTime (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the time the person spent standing
double getSpeed (const MSPerson::MSPersonStage_Walking &stage) const
return the current speed of the person
const MSEdge * getNextEdge (const MSPerson::MSPersonStage_Walking &stage) const
return the list of internal edges if the pedestrian is on an intersection
Private Attributes
MoveToNextEdge * myCommand
double myCurrentBeginPos
SUMOTime myCurrentDuration
double myCurrentEndPos
SUMOTime myLastEntryTime
Detailed Description
abstract base class for managing callbacks to retrieve various state information from the model
Definition at line 96 of file MSPModel_NonInteracting.h.
Constructor & Destructor Documentation
PState()
MSPModel_NonInteracting::PState::PState (MoveToNextEdge * cmd) inline
Definition at line 98 of file MSPModel_NonInteracting.h.
Member Function Documentation
computeWalkingTime()
SUMOTime MSPModel_NonInteracting::PState::computeWalkingTime (const MSEdge * prev, const MSPerson::MSPersonStage_Walking & stage, SUMOTime currentTime)
compute walking time on edge and update state members
Definition at line 114 of file MSPModel_NonInteracting.cpp.
References MSPModel::BACKWARD, DELTA_T, MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getArrivalPos(), MSPerson::MSPersonStage_Walking::getDepartPos(), MSPerson::MSPersonStage_Walking::getEdge(), MSEdge::getFromJunction(), MSEdge::getLength(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSPerson::MSPersonStage_Walking::getNextRouteEdge(), MSEdge::getToJunction(), MAX2(), TIME2STEPS, and MSPModel::UNDEFINED_DIRECTION.
Referenced by MSPModel_NonInteracting::add(), and MSPModel_NonInteracting::MoveToNextEdge::execute().
getAngle()
double MSPModel_NonInteracting::PState::getAngle (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the direction in which the person faces in degrees
Implements PedestrianState.
Definition at line 172 of file MSPModel_NonInteracting.cpp.
References MSPerson::MSPersonStage_Walking::getEdge(), MSTransportable::Stage::getEdgeAngle(), and M_PI.
getCommand()
MoveToNextEdge* MSPModel_NonInteracting::PState::getCommand () inline
Definition at line 112 of file MSPModel_NonInteracting.h.
getEdgePos()
double MSPModel_NonInteracting::PState::getEdgePos (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
abstract methods inherited from PedestrianState
Implements PedestrianState.
Definition at line 148 of file MSPModel_NonInteracting.cpp.
getNextEdge()
const MSEdge * MSPModel_NonInteracting::PState::getNextEdge (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the list of internal edges if the pedestrian is on an intersection
Implements PedestrianState.
Definition at line 195 of file MSPModel_NonInteracting.cpp.
References MSPerson::MSPersonStage_Walking::getNextRouteEdge().
getPosition()
Position MSPModel_NonInteracting::PState::getPosition (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the network coordinate of the person
Implements PedestrianState.
Definition at line 155 of file MSPModel_NonInteracting.cpp.
References MSLane::allowsVehicleClass(), MSPerson::MSPersonStage_Walking::getEdge(), MSNet::getInstance(), MSTransportable::Stage::getLanePosition(), MSEdge::getLanes(), MSNet::lefthand(), MSPModel::SIDEWALK_OFFSET, and SVC_PEDESTRIAN.
getSpeed()
double MSPModel_NonInteracting::PState::getSpeed (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the current speed of the person
Implements PedestrianState.
Definition at line 189 of file MSPModel_NonInteracting.cpp.
References MSPerson::MSPersonStage_Walking::getMaxSpeed().
getWaitingTime()
SUMOTime MSPModel_NonInteracting::PState::getWaitingTime (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the time the person spent standing
Implements PedestrianState.
Definition at line 183 of file MSPModel_NonInteracting.cpp.
moveToXY()
virtual void PedestrianState::moveToXY (MSPerson * p, Position pos, MSLane * lane, double lanePos, double lanePosLat, double angle, int routeOffset, const ConstMSEdgeVector & edges, SUMOTime t) inline virtual inherited
try to move person to the given position
Reimplemented in MSPModel_Striping::PState.
Definition at line 154 of file MSPModel.h.
References UNUSED_PARAMETER.
Referenced by MSPerson::Influencer::postProcessRemoteControl().
Field Documentation
myCommand
MoveToNextEdge* MSPModel_NonInteracting::PState::myCommand private
Definition at line 121 of file MSPModel_NonInteracting.h.
myCurrentBeginPos
double MSPModel_NonInteracting::PState::myCurrentBeginPos private
Definition at line 119 of file MSPModel_NonInteracting.h.
myCurrentDuration
SUMOTime MSPModel_NonInteracting::PState::myCurrentDuration private
Definition at line 118 of file MSPModel_NonInteracting.h.
myCurrentEndPos
double MSPModel_NonInteracting::PState::myCurrentEndPos private
Definition at line 120 of file MSPModel_NonInteracting.h.
myLastEntryTime
SUMOTime MSPModel_NonInteracting::PState::myLastEntryTime private
Definition at line 117 of file MSPModel_NonInteracting.h.
The documentation for this class was generated from the following files:
MSPModel_NonInteracting.h
MSPModel_NonInteracting.cpp