SUMO - Simulation of Urban MObility: GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger Class Reference
GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger Class Reference
#include <GUILaneSpeedTrigger.h>
Public Types
enum {
MID_USER_DEF = FXDialogBox::ID_LAST, MID_PRE_DEF, MID_OPTION, MID_CLOSE,
ID_LAST
}
Public Member Functions
GUIManip_LaneSpeedTrigger (GUIMainWindow &app, const std::string &name, GUILaneSpeedTrigger &o, int xpos, int ypos)
Constructor.
long onCmdChangeOption (FXObject *, FXSelector, void *)
long onCmdClose (FXObject *, FXSelector, void *)
long onCmdOverride (FXObject *, FXSelector, void *)
long onCmdPreDef (FXObject *, FXSelector, void *)
long onCmdUserDef (FXObject *, FXSelector, void *)
long onUpdPreDef (FXObject *, FXSelector, void *)
long onUpdUserDef (FXObject *, FXSelector, void *)
virtual ~GUIManip_LaneSpeedTrigger ()
Destructor.
Protected Member Functions
GUIManip_LaneSpeedTrigger ()
Private Attributes
FXDataTarget myChosenTarget
FXint myChosenValue
GUILaneSpeedTrigger * myObject
GUIMainWindow * myParent
FXComboBox * myPredefinedValues
double mySpeed
FXDataTarget mySpeedTarget
FXRealSpinDial * myUserDefinedSpeed
Detailed Description
Definition at line 135 of file GUILaneSpeedTrigger.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MID_USER_DEF
MID_PRE_DEF
MID_OPTION
MID_CLOSE
ID_LAST
Definition at line 138 of file GUILaneSpeedTrigger.h.
Constructor & Destructor Documentation
GUIManip_LaneSpeedTrigger() [1/2]
GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::GUIManip_LaneSpeedTrigger (GUIMainWindow & app, const std::string & name, GUILaneSpeedTrigger & o, int xpos, int ypos)
Constructor.
Definition at line 92 of file GUILaneSpeedTrigger.cpp.
References MID_CLOSE.
~GUIManip_LaneSpeedTrigger()
GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::~GUIManip_LaneSpeedTrigger () virtual
Destructor.
Definition at line 167 of file GUILaneSpeedTrigger.cpp.
GUIManip_LaneSpeedTrigger() [2/2]
GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::GUIManip_LaneSpeedTrigger () inline protected
Definition at line 179 of file GUILaneSpeedTrigger.h.
Member Function Documentation
onCmdChangeOption()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdChangeOption (FXObject * , FXSelector , void *)
Definition at line 216 of file GUILaneSpeedTrigger.cpp.
References FX::FXRealSpinDial::getValue(), myChosenValue, myObject, myParent, myPredefinedValues, mySpeed, myUserDefinedSpeed, MSLaneSpeedTrigger::setOverriding(), MSLaneSpeedTrigger::setOverridingValue(), and GUIMainWindow::updateChildren().
onCmdClose()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdClose (FXObject * , FXSelector , void *)
Definition at line 171 of file GUILaneSpeedTrigger.cpp.
onCmdOverride()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdOverride (FXObject * , FXSelector , void *)
onCmdPreDef()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdPreDef (FXObject * , FXSelector , void *)
Definition at line 197 of file GUILaneSpeedTrigger.cpp.
References myObject, myParent, myPredefinedValues, mySpeed, MSLaneSpeedTrigger::setOverridingValue(), and GUIMainWindow::updateChildren().
onCmdUserDef()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdUserDef (FXObject * , FXSelector , void *)
Definition at line 178 of file GUILaneSpeedTrigger.cpp.
References FX::FXRealSpinDial::getValue(), myObject, myParent, mySpeed, myUserDefinedSpeed, MSLaneSpeedTrigger::setOverridingValue(), and GUIMainWindow::updateChildren().
onUpdPreDef()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdPreDef (FXObject * sender, FXSelector , void * ptr)
Definition at line 206 of file GUILaneSpeedTrigger.cpp.
References myChosenValue, myParent, and GUIMainWindow::updateChildren().
onUpdUserDef()
long GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdUserDef (FXObject * sender, FXSelector , void * ptr)
Definition at line 187 of file GUILaneSpeedTrigger.cpp.
References myChosenValue, myParent, and GUIMainWindow::updateChildren().
Field Documentation
myChosenTarget
FXDataTarget GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::myChosenTarget private
Definition at line 166 of file GUILaneSpeedTrigger.h.
myChosenValue
FXint GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::myChosenValue private
Definition at line 164 of file GUILaneSpeedTrigger.h.
Referenced by onCmdChangeOption(), onUpdPreDef(), and onUpdUserDef().
myObject
GUILaneSpeedTrigger* GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::myObject private
Definition at line 176 of file GUILaneSpeedTrigger.h.
Referenced by onCmdChangeOption(), onCmdPreDef(), and onCmdUserDef().
myParent
GUIMainWindow* GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::myParent private
Definition at line 162 of file GUILaneSpeedTrigger.h.
Referenced by onCmdChangeOption(), onCmdPreDef(), onCmdUserDef(), onUpdPreDef(), and onUpdUserDef().
myPredefinedValues
FXComboBox* GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::myPredefinedValues private
Definition at line 174 of file GUILaneSpeedTrigger.h.
Referenced by onCmdChangeOption(), and onCmdPreDef().
mySpeed
double GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::mySpeed private
Definition at line 168 of file GUILaneSpeedTrigger.h.
Referenced by onCmdChangeOption(), onCmdPreDef(), and onCmdUserDef().
mySpeedTarget
FXDataTarget GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::mySpeedTarget private
Definition at line 170 of file GUILaneSpeedTrigger.h.
myUserDefinedSpeed
FXRealSpinDial* GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::myUserDefinedSpeed private
Definition at line 172 of file GUILaneSpeedTrigger.h.
Referenced by onCmdChangeOption(), and onCmdUserDef().
The documentation for this class was generated from the following files:
GUILaneSpeedTrigger.h
GUILaneSpeedTrigger.cpp