SUMO - Simulation of Urban MObility: ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime Class Reference
ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime Class Reference
Obtains edge travel times from a weights handler and stores them within the edges.
#include <ROLoader.h>
Public Member Functions
void addEdgeWeight (const std::string &id, double val, double beg, double end) const
Adds a travel time for a given edge and time period.
EdgeFloatTimeLineRetriever_EdgeTravelTime (RONet &net)
Constructor.
~EdgeFloatTimeLineRetriever_EdgeTravelTime ()
Destructor.
Private Attributes
RONet & myNet
The network edges shall be obtained from.
Detailed Description
Obtains edge travel times from a weights handler and stores them within the edges.
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever
Definition at line 151 of file ROLoader.h.
Constructor & Destructor Documentation
EdgeFloatTimeLineRetriever_EdgeTravelTime()
ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::EdgeFloatTimeLineRetriever_EdgeTravelTime (RONet & net) inline
Constructor.
Definition at line 154 of file ROLoader.h.
~EdgeFloatTimeLineRetriever_EdgeTravelTime()
ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::~EdgeFloatTimeLineRetriever_EdgeTravelTime () inline
Destructor.
Definition at line 157 of file ROLoader.h.
References ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight().
Member Function Documentation
addEdgeWeight()
void ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight (const std::string & id, double val, double beg, double end) const virtual
Adds a travel time for a given edge and time period.
Parameters
[in] id The id of the object to add a weight for
[in] val The travel time
[in] beg The begin of the interval the weight is valid for
[in] end The end of the interval the weight is valid for
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever::addEdgeWeight
Implements SAXWeightsHandler::EdgeFloatTimeLineRetriever.
Definition at line 65 of file ROLoader.cpp.
References ROEdge::addTravelTime(), RONet::getEdge(), OptionsCont::getOptions(), myNet, WRITE_ERROR, and WRITE_WARNING.
Field Documentation
myNet
RONet& ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::myNet private
The network edges shall be obtained from.
Definition at line 172 of file ROLoader.h.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), and addEdgeWeight().
The documentation for this class was generated from the following files:
ROLoader.h
ROLoader.cpp