SUMO - Simulation of Urban MObility: libsumo::TrafficLight Class Reference
libsumo::TrafficLight Class Reference
#include <TrafficLight.h>
Static Public Member Functions
static std::vector< TraCILogic > getCompleteRedYellowGreenDefinition (const std::string &tlsID)
static std::vector< std::string > getControlledJunctions (const std::string &tlsID)
static std::vector< std::string > getControlledLanes (const std::string &tlsID)
static std::vector< std::vector< TraCILink > > getControlledLinks (const std::string &tlsID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static SUMOTime getNextSwitch (const std::string &tlsID)
static std::string getParameter (const std::string &tlsID, const std::string &paramName)
static int getPhase (const std::string &tlsID)
static SUMOTime getPhaseDuration (const std::string &tlsID)
static std::string getProgram (const std::string &tlsID)
static std::string getRedYellowGreenState (const std::string &tlsID)
static void setCompleteRedYellowGreenDefinition (const std::string &tlsID, const TraCILogic &logic)
static void setParameter (const std::string &tlsID, const std::string &paramName, const std::string &value)
static void setPhase (const std::string &tlsID, const int index)
static void setPhaseDuration (const std::string &tlsID, const SUMOTime phaseDuration)
static void setProgram (const std::string &tlsID, const std::string &programID)
static void setRedYellowGreenState (const std::string &tlsID, const std::string &state)
Private Member Functions
TrafficLight & operator= (const TrafficLight &src)
invalidated assignment operator
TrafficLight ()
invalidated standard constructor
TrafficLight (const TrafficLight &src)
invalidated copy constructor
Static Private Member Functions
static MSTLLogicControl::TLSLogicVariants & getTLS (const std::string &id)
Detailed Description
Definition at line 51 of file TrafficLight.h.
Constructor & Destructor Documentation
TrafficLight() [1/2]
libsumo::TrafficLight::TrafficLight () private
invalidated standard constructor
TrafficLight() [2/2]
libsumo::TrafficLight::TrafficLight (const TrafficLight & src) private
invalidated copy constructor
Member Function Documentation
getCompleteRedYellowGreenDefinition()
std::vector< TraCILogic > TrafficLight::getCompleteRedYellowGreenDefinition (const std::string & tlsID) static
Definition at line 63 of file TrafficLight.cpp.
References MSPhaseDefinition::duration, MSTLLogicControl::TLSLogicVariants::getAllLogics(), MSPhaseDefinition::getState(), getTLS(), MSPhaseDefinition::maxDuration, MSPhaseDefinition::minDuration, and libsumo::TraCILogic::subParameter.
Referenced by TraCIServerAPI_TrafficLight::processGet().
getControlledJunctions()
std::vector< std::string > TrafficLight::getControlledJunctions (const std::string & tlsID) static
Definition at line 80 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getLinks(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getControlledLanes()
std::vector< std::string > TrafficLight::getControlledLanes (const std::string & tlsID) static
Definition at line 93 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getLaneVectors(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getControlledLinks()
std::vector< std::vector< TraCILink > > TrafficLight::getControlledLinks (const std::string & tlsID) static
Definition at line 106 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), Named::getID(), MSLink::getLane(), MSTrafficLightLogic::getLaneVectors(), MSTrafficLightLogic::getLinks(), getTLS(), and MSLink::getViaLane().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getIDCount()
int TrafficLight::getIDCount () static
Definition at line 51 of file TrafficLight.cpp.
References getIDList().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getIDList()
std::vector< std::string > TrafficLight::getIDList () static
Definition at line 45 of file TrafficLight.cpp.
References MSTLLogicControl::getAllTLIds(), MSNet::getInstance(), and MSNet::getTLSControl().
Referenced by getIDCount(), and TraCIServerAPI_TrafficLight::processGet().
getNextSwitch()
SUMOTime TrafficLight::getNextSwitch (const std::string & tlsID) static
Definition at line 148 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getNextSwitchTime(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getParameter()
std::string TrafficLight::getParameter (const std::string & tlsID, const std::string & paramName) static
Definition at line 154 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), Parameterised::getParameter(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getPhase()
int TrafficLight::getPhase (const std::string & tlsID) static
Definition at line 136 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseIndex(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getPhaseDuration()
SUMOTime TrafficLight::getPhaseDuration (const std::string & tlsID) static
Definition at line 142 of file TrafficLight.cpp.
References MSPhaseDefinition::duration, MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseDef(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getProgram()
std::string TrafficLight::getProgram (const std::string & tlsID) static
Definition at line 130 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getProgramID(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getRedYellowGreenState()
std::string TrafficLight::getRedYellowGreenState (const std::string & tlsID) static
Definition at line 57 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseDef(), MSPhaseDefinition::getState(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processGet().
getTLS()
MSTLLogicControl::TLSLogicVariants & TrafficLight::getTLS (const std::string & id) static private
Definition at line 224 of file TrafficLight.cpp.
References MSTLLogicControl::get(), MSNet::getInstance(), and MSNet::getTLSControl().
Referenced by getCompleteRedYellowGreenDefinition(), getControlledJunctions(), getControlledLanes(), getControlledLinks(), getNextSwitch(), getParameter(), getPhase(), getPhaseDuration(), getProgram(), getRedYellowGreenState(), setCompleteRedYellowGreenDefinition(), setParameter(), setPhase(), setPhaseDuration(), setProgram(), and setRedYellowGreenState().
operator=()
TrafficLight& libsumo::TrafficLight::operator= (const TrafficLight & src) private
invalidated assignment operator
setCompleteRedYellowGreenDefinition()
void TrafficLight::setCompleteRedYellowGreenDefinition (const std::string & tlsID, const TraCILogic & logic) static
Definition at line 198 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::addLogic(), libsumo::TraCILogic::currentPhaseIndex, libsumo::TraCIPhase::duration, libsumo::TraCIPhase::duration1, libsumo::TraCIPhase::duration2, MSNet::getInstance(), MSTLLogicControl::TLSLogicVariants::getLogic(), getTLS(), libsumo::TraCIPhase::phase, libsumo::TraCILogic::phases, libsumo::TraCILogic::subID, and libsumo::TraCILogic::subParameter.
Referenced by TraCIServerAPI_TrafficLight::processSet().
setParameter()
void TrafficLight::setParameter (const std::string & tlsID, const std::string & paramName, const std::string & value) static
Definition at line 218 of file TrafficLight.cpp.
References MSTLLogicControl::TLSLogicVariants::getActive(), getTLS(), and Parameterised::setParameter().
Referenced by TraCIServerAPI_TrafficLight::processSet().
setPhase()
void TrafficLight::setPhase (const std::string & tlsID, const int index) static
Definition at line 166 of file TrafficLight.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), MSPhaseDefinition::duration, MSTLLogicControl::TLSLogicVariants::getActive(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), getTLS(), and toString().
Referenced by TraCIServerAPI_TrafficLight::processSet().
setPhaseDuration()
void TrafficLight::setPhaseDuration (const std::string & tlsID, const SUMOTime phaseDuration) static
Definition at line 189 of file TrafficLight.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), and getTLS().
Referenced by TraCIServerAPI_TrafficLight::processSet().
setProgram()
void TrafficLight::setProgram (const std::string & tlsID, const std::string & programID) static
Definition at line 179 of file TrafficLight.cpp.
References MSNet::getInstance(), getTLS(), and MSTLLogicControl::TLSLogicVariants::switchTo().
Referenced by TraCIServerAPI_TrafficLight::processSet().
setRedYellowGreenState()
void TrafficLight::setRedYellowGreenState (const std::string & tlsID, const std::string & state) static
Definition at line 160 of file TrafficLight.cpp.
References MSNet::getInstance(), getTLS(), and MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline().
Referenced by TraCIServerAPI_TrafficLight::processSet().
The documentation for this class was generated from the following files:
TrafficLight.h
TrafficLight.cpp