SUMO - Simulation of Urban MObility: StringBijection< T > Class Template Reference
StringBijection< T > Class Template Reference
#include <StringBijection.h>
Data Structures
struct Entry
Public Member Functions
void addAlias (const std::string str, const T key)
void addKeysInto (std::vector< T > &list) const
T get (const std::string &str) const
const std::string & getString (const T key) const
std::vector< std::string > getStrings () const
bool has (const T key) const
bool hasString (const std::string &str) const
void insert (const std::string str, const T key, bool checkDuplicates=true)
void remove (const std::string str, const T key)
int size () const
StringBijection ()
StringBijection (Entry entries[], T terminatorKey, bool checkDuplicates=true)
Private Attributes
std::map< std::string, T > myString2T
std::map< T, std::string > myT2String
Detailed Description
template<class T>
class StringBijection< T >
Template container for maintaining a bidirectional map between strings and something else It is not always a bijection since it allows for duplicate entries on both sides if either checkDuplicates is set to false in the constructor or the insert function or if the addAlias function is used.
Definition at line 51 of file StringBijection.h.
Constructor & Destructor Documentation
StringBijection() [1/2]
template<class T> StringBijection< T >::StringBijection () inline
Definition at line 68 of file StringBijection.h.
StringBijection() [2/2]
template<class T> StringBijection< T >::StringBijection (Entry entries[], T terminatorKey, bool checkDuplicates = true) inline
Definition at line 71 of file StringBijection.h.
Member Function Documentation
addAlias()
template<class T> void StringBijection< T >::addAlias (const std::string str, const T key) inline
Definition at line 94 of file StringBijection.h.
Referenced by HelpersPHEMlight::getClassByName(), HelpersHBEFA::HelpersHBEFA(), and HelpersHBEFA3::HelpersHBEFA3().
addKeysInto()
template<class T> void StringBijection< T >::addKeysInto (std::vector< T > & list) const inline
Definition at line 149 of file StringBijection.h.
get()
template<class T> T StringBijection< T >::get (const std::string & str) const inline
Definition at line 105 of file StringBijection.h.
Referenced by NIImporter_SUMO::addConnection(), NIImporter_SUMO::addEdge(), NBNodeCont::analyzeCluster(), SUMOVehicleParserHelper::beginVTypeParsing(), NIVisumTL::build(), NGNode::buildNBNode(), NBNetBuilder::compute(), HelpersHBEFA3::getClass(), HelpersPHEMlight::getClass(), HelpersPHEMlight::getClassByName(), SUMOSAXAttributesImpl_Cached::getEdgeFunc(), SUMOSAXAttributesImpl_Xerces::getEdgeFunc(), PHEMCEP::GetEmission(), NWWriter_OpenDrive::getID(), SUMOSAXAttributesImpl_Cached::getNodeType(), SUMOSAXAttributesImpl_Xerces::getNodeType(), GNEInternalLane::getPopUpMenu(), GNELane::getPopUpMenu(), getVehicleClassCompoundID(), getVehicleClassID(), getVehicleClassNamesList(), getVehicleShapeID(), NBNodeCont::guessTLs(), HelpersHBEFA::HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NLHandler::initTrafficLightLogic(), NIImporter_OpenStreetMap::insertNodeChecking(), NIImporter_OpenDrive::loadNetwork(), MSRouteHandler::MSRouteHandler(), NLHandler::parseLinkDir(), NLHandler::parseLinkState(), NIXMLNodesHandler::processNodeType(), NIXMLNodesHandler::processTrafficLightDefinitions(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), GNEJunction::setAttribute(), and NIXMLEdgesHandler::tryGetLaneSpread().
getString()
template<class T> const std::string& StringBijection< T >::getString (const T key) const inline
Definition at line 114 of file StringBijection.h.
Referenced by HelpersHBEFA3::getAmitranVehicleClass(), HelpersPHEMlight::getAmitranVehicleClass(), HelpersHBEFA3::getEuroClass(), HelpersPHEMlight::getEuroClass(), HelpersHBEFA3::getFuel(), HelpersPHEMlight::getFuel(), libsumo::Lane::getLinks(), getVehicleShapeName(), HelpersPHEMlight::getWeight(), parseVehicleClasses(), toString< LaneChangeModel >(), toString< LaneSpreadFunction >(), toString< LateralAlignment >(), toString< LinkDirection >(), toString< LinkState >(), toString< SumoXMLAttr >(), toString< SumoXMLEdgeFunc >(), toString< SumoXMLNodeType >(), toString< SumoXMLTag >(), toString< TrafficLightType >(), and NBSign::writeAsPOI().
getStrings()
template<class T> std::vector<std::string> StringBijection< T >::getStrings () const inline
Definition at line 139 of file StringBijection.h.
Referenced by GNEAttributeCarrier::discreteChoices(), GNEInternalLane::getPopUpMenu(), GNELane::getPopUpMenu(), getVehicleClassCompoundID(), getVehicleClassNamesList(), and toString< LaneChangeAction >().
has()
template<class T> bool StringBijection< T >::has (const T key) const inline
Definition at line 129 of file StringBijection.h.
Referenced by StringBijection< FXuint >::getString(), and StringBijection< FXuint >::insert().
hasString()
template<class T> bool StringBijection< T >::hasString (const std::string & str) const inline
Definition at line 124 of file StringBijection.h.
Referenced by canParseVehicleClasses(), canParseVehicleShape(), StringBijection< FXuint >::get(), HelpersHBEFA3::getClass(), HelpersPHEMlight::getClass(), HelpersPHEMlight::getClassByName(), PHEMCEP::GetEmission(), NWWriter_OpenDrive::getID(), getVehicleClassID(), getVehicleShapeID(), StringBijection< FXuint >::insert(), GNEJunction::isValid(), GNEEdge::isValid(), and parseVehicleClasses().
insert()
template<class T> void StringBijection< T >::insert (const std::string str, const T key, bool checkDuplicates = true) inline
Definition at line 79 of file StringBijection.h.
Referenced by GNEViewNet::buildEditModeControls(), HelpersPHEMlight::getClassByName(), NWWriter_OpenDrive::getID(), HelpersEnergy::HelpersEnergy(), HelpersHBEFA::HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), HelpersPHEMlight::HelpersPHEMlight(), PHEMCEP::PHEMCEP(), and StringBijection< FXuint >::StringBijection().
remove()
template<class T> void StringBijection< T >::remove (const std::string str, const T key) inline
Definition at line 99 of file StringBijection.h.
Referenced by HelpersPHEMlight::getClassByName().
size()
template<class T> int StringBijection< T >::size () const inline
Definition at line 134 of file StringBijection.h.
Referenced by SUMOSAXAttributesImpl_Binary::getEdgeFunc(), SUMOSAXAttributesImpl_Binary::getNodeType(), and writePermissions().
Field Documentation
myString2T
template<class T> std::map<std::string, T> StringBijection< T >::myString2T private
Definition at line 158 of file StringBijection.h.
Referenced by StringBijection< FXuint >::addAlias(), StringBijection< FXuint >::get(), StringBijection< FXuint >::hasString(), StringBijection< FXuint >::insert(), StringBijection< FXuint >::remove(), and StringBijection< FXuint >::size().
myT2String
template<class T> std::map<T, std::string> StringBijection< T >::myT2String private
Definition at line 159 of file StringBijection.h.
Referenced by StringBijection< FXuint >::addKeysInto(), StringBijection< FXuint >::getString(), StringBijection< FXuint >::getStrings(), StringBijection< FXuint >::has(), StringBijection< FXuint >::insert(), and StringBijection< FXuint >::remove().
The documentation for this class was generated from the following file:
StringBijection.h