SUMO - Simulation of Urban MObility: NIImporter_OpenStreetMap::RelationHandler Class Reference
NIImporter_OpenStreetMap::RelationHandler Class Reference
A class which extracts relevant relation information from a parsed OSM-file.
#include <NIImporter_OpenStreetMap.h>
Data Structures
struct NIIPTPlatform
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RelationHandler (const std::map< long long int, NIOSMNode *> &osmNodes, const std::map< long long int, Edge *> &osmEdges, NBPTStopCont *nbptStopCont, const std::map< long long int, Edge *> &platfromShapes, NBPTLineCont *nbptLineCont, const OptionsCont &oc)
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~RelationHandler () override
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs) override
Called on the opening of a tag;.
void myEndElement (int element) override
Called when a closing tag occurs.
Private Types
enum RestrictionType { RESTRICTION_ONLY, RESTRICTION_NO, RESTRICTION_UNKNOWN }
whether the only allowed or the only forbidden connection is defined
Private Member Functions
bool applyRestriction () const
try to apply the parsed restriction and return whether successful
bool checkEdgeRef (long long int ref) const
check whether a referenced way has a corresponding edge
NBEdge * findEdgeRef (long long int wayRef, const std::vector< NBEdge *> &candidates) const
try to find the way segment among candidates
RelationHandler & operator= (const RelationHandler &s)
invalidated assignment operator
RelationHandler (const RelationHandler &s)
invalidated copy constructor
void resetValues ()
reset members to their defaults for parsing a new relation
Private Attributes
long long int myCurrentRelation
The currently parsed relation.
long long int myFromWay
the origination way for the current restriction
bool myIsRestriction
whether the currently parsed relation is a restriction
bool myIsRoute
indicates whether current relation is a route
bool myIsStopArea
indicates whether current relation is a pt stop area
std::string myName
name of the relation
NBPTLineCont * myNBPTLineCont
PT Line container to be filled.
NBPTStopCont * myNBPTStopCont
The previously filled pt stop container.
const OptionsCont & myOptionsCont
the options cont
const std::map< long long int, Edge * > & myOSMEdges
The previously parsed edges.
const std::map< long long int, NIOSMNode * > & myOSMNodes
The previously parsed nodes.
std::vector< int > myParentElements
The element stack.
std::vector< NIIPTPlatform > myPlatforms
bus stop platforms
const std::map< long long int, Edge * > & myPlatformShapes
The previously parsed platform shapes.
std::string myPTRouteType
indicates whether current relation is a pt route
std::string myRef
ref of the pt line
RestrictionType myRestrictionType
std::vector< long long int > myStops
bus stop references
long long int myToWay
the destination way for the current restriction
long long int myViaNode
the via node/way for the current restriction
long long int myViaWay
std::vector< long long int > myWays
ways in pt line references
Detailed Description
A class which extracts relevant relation information from a parsed OSM-file.
turn restrictions
Definition at line 439 of file NIImporter_OpenStreetMap.h.
Member Enumeration Documentation
RestrictionType
enum NIImporter_OpenStreetMap::RelationHandler::RestrictionType private
whether the only allowed or the only forbidden connection is defined
Enumerator
RESTRICTION_ONLY
The only valid connection is declared.
RESTRICTION_NO
The only invalid connection is declared.
RESTRICTION_UNKNOWN
The relation tag was missing.
Definition at line 522 of file NIImporter_OpenStreetMap.h.
Constructor & Destructor Documentation
RelationHandler() [1/2]
NIImporter_OpenStreetMap::RelationHandler::RelationHandler (const std::map< long long int, NIOSMNode *> & osmNodes, const std::map< long long int, Edge *> & osmEdges, NBPTStopCont * nbptStopCont, const std::map< long long int, Edge *> & platfromShapes, NBPTLineCont * nbptLineCont, const OptionsCont & oc)
Constructor.
Parameters
[in] osmNodes The previously parsed OSM-nodes
[in] osmEdges The previously parse OSM-edges
Definition at line 1056 of file NIImporter_OpenStreetMap.cpp.
References resetValues(), and ~RelationHandler().
~RelationHandler()
NIImporter_OpenStreetMap::RelationHandler::~RelationHandler () override default
Destructor.
Referenced by RelationHandler().
RelationHandler() [2/2]
NIImporter_OpenStreetMap::RelationHandler::RelationHandler (const RelationHandler & s) private
invalidated copy constructor
Member Function Documentation
applyRestriction()
bool NIImporter_OpenStreetMap::RelationHandler::applyRestriction () const private
try to apply the parsed restriction and return whether successful
Definition at line 1387 of file NIImporter_OpenStreetMap.cpp.
References NBEdge::addEdge2EdgeConnection(), findEdgeRef(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), NIImporter_OpenStreetMap::INVALID_ID, myFromWay, myOSMNodes, myRestrictionType, myToWay, myViaNode, NBEdge::removeFromConnections(), RESTRICTION_ONLY, toString(), and WRITE_WARNING.
Referenced by myEndElement().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
checkEdgeRef()
bool NIImporter_OpenStreetMap::RelationHandler::checkEdgeRef (long long int ref) const private
check whether a referenced way has a corresponding edge
Definition at line 1218 of file NIImporter_OpenStreetMap.cpp.
References myCurrentRelation, myOSMEdges, toString(), and WRITE_WARNING.
Referenced by myStartElement().
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
findEdgeRef()
NBEdge * NIImporter_OpenStreetMap::RelationHandler::findEdgeRef (long long int wayRef, const std::vector< NBEdge *> & candidates) const private
try to find the way segment among candidates
Definition at line 1419 of file NIImporter_OpenStreetMap.cpp.
References toString(), and WRITE_WARNING.
Referenced by applyRestriction().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void NIImporter_OpenStreetMap::RelationHandler::myEndElement (int element) override protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 1230 of file NIImporter_OpenStreetMap.cpp.
References NBPTStop::addPlatformCand(), NBPTLine::addPTStop(), NBPTLine::addWayNode(), applyRestriction(), NIImporter_OpenStreetMap::NIOSMNode::ele, NBPTStopCont::get(), OptionsCont::getFloat(), OptionsCont::getOptions(), NBPTLine::getStops(), NIImporter_OpenStreetMap::NIOSMNode::id, NBPTLineCont::insert(), NIImporter_OpenStreetMap::INVALID_ID, OptionsCont::isSet(), NIImporter_OpenStreetMap::NIOSMNode::lat, PositionVector::length(), NIImporter_OpenStreetMap::NIOSMNode::lon, NIImporter_OpenStreetMap::Edge::myCurrentNodes, myCurrentRelation, myFromWay, myIsRestriction, myIsRoute, myIsStopArea, myName, myNBPTLineCont, myNBPTStopCont, myOptionsCont, myOSMEdges, myOSMNodes, myParentElements, myPlatforms, myPlatformShapes, myPTRouteType, myRef, myRestrictionType, myStops, myToWay, myViaNode, myViaWay, myWays, resetValues(), RESTRICTION_UNKNOWN, NBPTStop::setIsMultipleStopPositions(), NBPTLine::setMyNumOfStops(), NBPTLine::setRef(), SUMO_TAG_RELATION, toString(), NBNetBuilder::transformCoordinate(), WRITE_ERROR, and WRITE_WARNING.
myStartElement()
void NIImporter_OpenStreetMap::RelationHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) override protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 1093 of file NIImporter_OpenStreetMap.cpp.
References checkEdgeRef(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::hasAttribute(), NIImporter_OpenStreetMap::INVALID_ID, NIImporter_OpenStreetMap::RelationHandler::NIIPTPlatform::isWay, myCurrentRelation, myFromWay, myIsRestriction, myIsRoute, myIsStopArea, myName, myOSMNodes, myParentElements, myPlatforms, myPlatformShapes, myPTRouteType, myRef, myRestrictionType, myStops, myToWay, myViaNode, myViaWay, myWays, NIImporter_OpenStreetMap::RelationHandler::NIIPTPlatform::ref, RESTRICTION_NO, RESTRICTION_ONLY, SUMO_ATTR_ID, SUMO_ATTR_K, SUMO_ATTR_REF, SUMO_ATTR_TYPE, SUMO_ATTR_V, SUMO_TAG_MEMBER, SUMO_TAG_RELATION, SUMO_TAG_TAG, toString(), and WRITE_WARNING.
operator=()
RelationHandler& NIImporter_OpenStreetMap::RelationHandler::operator= (const RelationHandler & s) private
invalidated assignment operator
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
resetValues()
void NIImporter_OpenStreetMap::RelationHandler::resetValues () private
reset members to their defaults for parsing a new relation
Definition at line 1076 of file NIImporter_OpenStreetMap.cpp.
References NIImporter_OpenStreetMap::INVALID_ID, myCurrentRelation, myFromWay, myIsRestriction, myIsRoute, myIsStopArea, myPlatforms, myPTRouteType, myRestrictionType, myStops, myToWay, myViaNode, myViaWay, myWays, and RESTRICTION_UNKNOWN.
Referenced by myEndElement(), and RelationHandler().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myCurrentRelation
long long int NIImporter_OpenStreetMap::RelationHandler::myCurrentRelation private
The currently parsed relation.
Definition at line 497 of file NIImporter_OpenStreetMap.h.
Referenced by checkEdgeRef(), myEndElement(), myStartElement(), and resetValues().
myFromWay
long long int NIImporter_OpenStreetMap::RelationHandler::myFromWay private
the origination way for the current restriction
Definition at line 506 of file NIImporter_OpenStreetMap.h.
Referenced by applyRestriction(), myEndElement(), myStartElement(), and resetValues().
myIsRestriction
bool NIImporter_OpenStreetMap::RelationHandler::myIsRestriction private
whether the currently parsed relation is a restriction
Definition at line 503 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myIsRoute
bool NIImporter_OpenStreetMap::RelationHandler::myIsRoute private
indicates whether current relation is a route
Definition at line 570 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myIsStopArea
bool NIImporter_OpenStreetMap::RelationHandler::myIsStopArea private
indicates whether current relation is a pt stop area
Definition at line 567 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myName
std::string NIImporter_OpenStreetMap::RelationHandler::myName private
name of the relation
Definition at line 576 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), and myStartElement().
myNBPTLineCont
NBPTLineCont* NIImporter_OpenStreetMap::RelationHandler::myNBPTLineCont private
PT Line container to be filled.
Definition at line 494 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement().
myNBPTStopCont
NBPTStopCont* NIImporter_OpenStreetMap::RelationHandler::myNBPTStopCont private
The previously filled pt stop container.
Definition at line 491 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement().
myOptionsCont
const OptionsCont& NIImporter_OpenStreetMap::RelationHandler::myOptionsCont private
the options cont
Definition at line 517 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement().
myOSMEdges
const std::map<long long int, Edge*>& NIImporter_OpenStreetMap::RelationHandler::myOSMEdges private
The previously parsed edges.
Definition at line 485 of file NIImporter_OpenStreetMap.h.
Referenced by checkEdgeRef(), and myEndElement().
myOSMNodes
const std::map<long long int, NIOSMNode*>& NIImporter_OpenStreetMap::RelationHandler::myOSMNodes private
The previously parsed nodes.
Definition at line 482 of file NIImporter_OpenStreetMap.h.
Referenced by applyRestriction(), myEndElement(), and myStartElement().
myParentElements
std::vector<int> NIImporter_OpenStreetMap::RelationHandler::myParentElements private
The element stack.
Definition at line 500 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), and myStartElement().
myPlatforms
std::vector<NIIPTPlatform> NIImporter_OpenStreetMap::RelationHandler::myPlatforms private
bus stop platforms
Definition at line 561 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myPlatformShapes
const std::map<long long int, Edge*>& NIImporter_OpenStreetMap::RelationHandler::myPlatformShapes private
The previously parsed platform shapes.
Definition at line 488 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), and myStartElement().
myPTRouteType
std::string NIImporter_OpenStreetMap::RelationHandler::myPTRouteType private
indicates whether current relation is a pt route
Definition at line 573 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myRef
std::string NIImporter_OpenStreetMap::RelationHandler::myRef private
ref of the pt line
Definition at line 579 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), and myStartElement().
myRestrictionType
RestrictionType NIImporter_OpenStreetMap::RelationHandler::myRestrictionType private
Definition at line 530 of file NIImporter_OpenStreetMap.h.
Referenced by applyRestriction(), myEndElement(), myStartElement(), and resetValues().
myStops
std::vector<long long int> NIImporter_OpenStreetMap::RelationHandler::myStops private
bus stop references
Definition at line 552 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myToWay
long long int NIImporter_OpenStreetMap::RelationHandler::myToWay private
the destination way for the current restriction
Definition at line 509 of file NIImporter_OpenStreetMap.h.
Referenced by applyRestriction(), myEndElement(), myStartElement(), and resetValues().
myViaNode
long long int NIImporter_OpenStreetMap::RelationHandler::myViaNode private
the via node/way for the current restriction
Definition at line 512 of file NIImporter_OpenStreetMap.h.
Referenced by applyRestriction(), myEndElement(), myStartElement(), and resetValues().
myViaWay
long long int NIImporter_OpenStreetMap::RelationHandler::myViaWay private
Definition at line 513 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
myWays
std::vector<long long int> NIImporter_OpenStreetMap::RelationHandler::myWays private
ways in pt line references
Definition at line 564 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), myStartElement(), and resetValues().
The documentation for this class was generated from the following files:
NIImporter_OpenStreetMap.h
NIImporter_OpenStreetMap.cpp