SUMO - Simulation of Urban MObility: PHEMCEP Class Reference
PHEMCEP Class Reference
Data Handler for a single CEP emission data set.
#include <PHEMCEP.h>
Public Member Functions
double CalcPower (double v, double a, double slope, double vehicleLoading=0) const
Returns the power of used for a vehicle at state v,a, slope and loading.
double GetCdValue () const
Getter function to recieve vehicle data from CEP.
double GetCrossSectionalArea () const
Getter function to recieve vehicle data from CEP.
double GetDecelCoast (double speed, double acc, double gradient, double vehicleLoading) const
double GetEmission (const std::string &pollutantIdentifier, double power, double speed, bool normalized=false) const
Returns a emission measure for power[kW] level.
SUMOEmissionClass GetEmissionClass () const
Getter function to recieve vehicle data from CEP.
double GetMassRot () const
Getter function to recieve vehicle data from CEP.
double GetMassVehicle () const
Getter function to recieve vehicle data from CEP.
double GetMaxAccel (double v, double a, double gradient, double vehicleLoading=0) const
Returns the maximum accelaration for a vehicle at state v,a, slope and loading.
double GetRatedPower () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF0 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF1 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF2 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF3 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF4 () const
Getter function to recieve vehicle data from CEP.
const std::string & GetVehicleFuelType () const
Getter function to recieve vehicle data from CEP.
double GetVehicleLoading () const
Getter function to recieve vehicle data from CEP.
PHEMCEP (bool heavyVehicel, SUMOEmissionClass emissionClass, const std::string &emissionClassIdentifier, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cdValue, double f0, double f1, double f2, double f3, double f4, double ratedPower, double pNormV0, double pNormP0, double pNormV1, double pNormP1, double axleRatio, double engineIdlingSpeed, double engineRatedSpeed, double effectiveWheelDiameter, double idlingFC, const std::string &vehicleFuelType, const std::vector< std::vector< double > > &matrixFC, const std::vector< std::string > &headerLinePollutants, const std::vector< std::vector< double > > &matrixPollutants, const std::vector< std::vector< double > > &matrixSpeedRotational, const std::vector< std::vector< double > > &normedDragTable, const std::vector< double > &idlingValuesPollutants)
~PHEMCEP ()
Destructor.
Private Member Functions
void FindLowerUpperInPattern (int &lowerIndex, int &upperIndex, const std::vector< double > &pattern, double value) const
Finds bounding upper and lower index in pattern for value.
double GetDragCoeffecient (double nNorm) const
double GetGearCoeffecient (double speed) const
double GetPMaxNorm (double speed) const
Calculates maximum available rated power for speed.
double GetRotationalCoeffecient (double speed) const
Calculates rotational index for speed.
double Interpolate (double px, double p1, double p2, double e1, double e2) const
Interpolates emission linearly between two known power-emission pairs.
Private Attributes
double _axleRatio
double _cdValue
Cw value.
std::vector< double > _cepCurveFC
StringBijection< std::vector< double > > _cepCurvePollutants
double _crossSectionalArea
crosssectional area of vehicle
std::vector< double > _dragNormTable
double _drivingPower
double _effictiveWheelDiameter
SUMOEmissionClass _emissionClass
PHEM emission class of vehicle.
double _engineIdlingSpeed
double _engineRatedSpeed
std::vector< double > _gearTransmissionCurve
bool _heavyVehicle
double _idlingFC
StringBijection< double > _idlingValuesPollutants
double _massRot
rotational mass of vehicle
double _massVehicle
vehicle mass
std::vector< double > _nNormTable
std::vector< double > _normailzedPowerPatternPollutants
StringBijection< std::vector< double > > _normalizedCepCurvePollutants
std::vector< double > _normalizedPowerPatternFC
double _normalizingPower
NormalizingType _normalizingType
std::vector< double > _normedCepCurveFC
double _pNormP0
Step functions parameter for maximum rated power.
double _pNormP1
Step functions parameter for maximum rated power.
double _pNormV0
Step functions parameter for maximum rated power.
double _pNormV1
Step functions parameter for maximum rated power.
std::vector< double > _powerPatternFC
std::vector< double > _powerPatternPollutants
double _ratedPower
rated power of vehicle
double _resistanceF0
Rolling resistance f0.
double _resistanceF1
Rolling resistance f1.
double _resistanceF2
Rolling resistance f2.
double _resistanceF3
Rolling resistance f3.
double _resistanceF4
Rolling resistance f4.
int _sizeOfPatternFC
int _sizeOfPatternPollutants
std::vector< double > _speedCurveRotational
std::vector< double > _speedPatternRotational
std::string _vehicleFuelType
double _vehicleLoading
vehicle loading
Detailed Description
Data Handler for a single CEP emission data set.
Definition at line 58 of file PHEMCEP.h.
Constructor & Destructor Documentation
PHEMCEP()
PHEMCEP::PHEMCEP (bool heavyVehicel, SUMOEmissionClass emissionClass, const std::string & emissionClassIdentifier, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cdValue, double f0, double f1, double f2, double f3, double f4, double ratedPower, double pNormV0, double pNormP0, double pNormV1, double pNormP1, double axleRatio, double engineIdlingSpeed, double engineRatedSpeed, double effectiveWheelDiameter, double idlingFC, const std::string & vehicleFuelType, const std::vector< std::vector< double > > & matrixFC, const std::vector< std::string > & headerLinePollutants, const std::vector< std::vector< double > > & matrixPollutants, const std::vector< std::vector< double > > & matrixSpeedRotational, const std::vector< std::vector< double > > & normedDragTable, const std::vector< double > & idlingValuesPollutants)
Definition at line 44 of file PHEMCEP.cpp.
References _axleRatio, _cdValue, _cepCurveFC, _cepCurvePollutants, _crossSectionalArea, _dragNormTable, _drivingPower, _effictiveWheelDiameter, _emissionClass, _engineIdlingSpeed, _engineRatedSpeed, _gearTransmissionCurve, _heavyVehicle, _idlingFC, _idlingValuesPollutants, _massRot, _massVehicle, _nNormTable, _normailzedPowerPatternPollutants, _normalizedCepCurvePollutants, _normalizedPowerPatternFC, _normalizingPower, _normalizingType, _normedCepCurveFC, _pNormP0, _pNormP1, _pNormV0, _pNormV1, _powerPatternFC, _powerPatternPollutants, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _sizeOfPatternFC, _sizeOfPatternPollutants, _speedCurveRotational, _speedPatternRotational, _vehicleFuelType, _vehicleLoading, CalcPower(), DrivingPower, StringBijection< T >::insert(), NORMALIZING_ACCELARATION, NORMALIZING_SPEED, and RatedPower.
~PHEMCEP()
PHEMCEP::~PHEMCEP ()
Destructor.
Definition at line 192 of file PHEMCEP.cpp.
References _cepCurveFC, _powerPatternFC, _powerPatternPollutants, _speedCurveRotational, and _speedPatternRotational.
Member Function Documentation
CalcPower()
double PHEMCEP::CalcPower (double v, double a, double slope, double vehicleLoading = 0) const
Returns the power of used for a vehicle at state v,a, slope and loading.
Parameters
[in] v The vehicle's average velocity
[in] a The vehicle's average acceleration
[in] slope The road's slope at vehicle's position [deg]
Definition at line 406 of file PHEMCEP.cpp.
References _cdValue, _crossSectionalArea, _massRot, _massVehicle, _resistanceF0, _resistanceF1, _resistanceF4, _vehicleLoading, AIR_DENSITY_CONST, GetRotationalCoeffecient(), and GRAVITY_CONST.
Referenced by HelpersPHEMlight::compute(), GetMaxAccel(), and PHEMCEP().
FindLowerUpperInPattern()
void PHEMCEP::FindLowerUpperInPattern (int & lowerIndex, int & upperIndex, const std::vector< double > & pattern, double value) const private
Finds bounding upper and lower index in pattern for value.
Parameters
[out] lowerIndex out variable for lower index
[out] upperIndex out variable for lower index
[in] pattern to search
[in] value to search
Definition at line 364 of file PHEMCEP.cpp.
Referenced by GetDecelCoast(), GetDragCoeffecient(), GetEmission(), GetGearCoeffecient(), GetRotationalCoeffecient(), and GetVehicleFuelType().
GetCdValue()
double PHEMCEP::GetCdValue () const inline
Getter function to recieve vehicle data from CEP.
Returns
Cw value
Todo:
: Why is it named "cdValue", here?
Definition at line 184 of file PHEMCEP.h.
References _cdValue.
GetCrossSectionalArea()
double PHEMCEP::GetCrossSectionalArea () const inline
Getter function to recieve vehicle data from CEP.
Returns
crosssectional area of vehicle
Definition at line 191 of file PHEMCEP.h.
References _crossSectionalArea.
GetDecelCoast()
double PHEMCEP::GetDecelCoast (double speed, double acc, double gradient, double vehicleLoading) const
Definition at line 285 of file PHEMCEP.cpp.
References _axleRatio, _cdValue, _crossSectionalArea, _effictiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _massVehicle, _nNormTable, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _vehicleLoading, FindLowerUpperInPattern(), GetDragCoeffecient(), GetGearCoeffecient(), GetRotationalCoeffecient(), GRAVITY_CONST, M_PI2, and SPEED_DCEL_MIN.
GetDragCoeffecient()
double PHEMCEP::GetDragCoeffecient (double nNorm) const private
Definition at line 351 of file PHEMCEP.cpp.
References _dragNormTable, _nNormTable, FindLowerUpperInPattern(), and Interpolate().
Referenced by GetDecelCoast(), and GetVehicleFuelType().
GetEmission()
double PHEMCEP::GetEmission (const std::string & pollutantIdentifier, double power, double speed, bool normalized = false) const
Returns a emission measure for power[kW] level.
Parameters
[in] pollutantIdentifier Desired pollutant, e.g. NOx
[in] power in [kW]
Returns
emission in [g/h]
Definition at line 203 of file PHEMCEP.cpp.
References _cepCurveFC, _cepCurvePollutants, _idlingFC, _idlingValuesPollutants, _normailzedPowerPatternPollutants, _normalizedCepCurvePollutants, _normalizedPowerPatternFC, _normedCepCurveFC, _powerPatternFC, _powerPatternPollutants, FindLowerUpperInPattern(), StringBijection< T >::get(), StringBijection< T >::hasString(), Interpolate(), and ZERO_SPEED_ACCURACY.
Referenced by HelpersPHEMlight::getEmission().
GetEmissionClass()
SUMOEmissionClass PHEMCEP::GetEmissionClass () const inline
Getter function to recieve vehicle data from CEP.
Returns
PHEM emission class of vehicle
Definition at line 135 of file PHEMCEP.h.
References _emissionClass.
GetGearCoeffecient()
double PHEMCEP::GetGearCoeffecient (double speed) const private
Definition at line 338 of file PHEMCEP.cpp.
References _gearTransmissionCurve, _speedPatternRotational, FindLowerUpperInPattern(), and Interpolate().
Referenced by GetDecelCoast(), and GetVehicleFuelType().
GetMassRot()
double PHEMCEP::GetMassRot () const inline
Getter function to recieve vehicle data from CEP.
Returns
rotational mass of vehicle
Definition at line 214 of file PHEMCEP.h.
References _massRot.
GetMassVehicle()
double PHEMCEP::GetMassVehicle () const inline
Getter function to recieve vehicle data from CEP.
Returns
vehicle mass
Definition at line 199 of file PHEMCEP.h.
References _massVehicle.
GetMaxAccel()
double PHEMCEP::GetMaxAccel (double v, double a, double gradient, double vehicleLoading = 0) const
Returns the maximum accelaration for a vehicle at state v,a, slope and loading.
Parameters
[in] v The vehicle's average velocity
[in] a The vehicle's average acceleration
[in] slope The road's slope at vehicle's position [deg]
Definition at line 417 of file PHEMCEP.cpp.
References _massRot, _massVehicle, _ratedPower, _vehicleLoading, CalcPower(), GetPMaxNorm(), GetRotationalCoeffecient(), and UNUSED_PARAMETER.
GetPMaxNorm()
double PHEMCEP::GetPMaxNorm (double speed) const private
Calculates maximum available rated power for speed.
Parameters
[in] speed desired speed
Definition at line 426 of file PHEMCEP.cpp.
References _pNormP0, _pNormP1, _pNormV0, _pNormV1, and Interpolate().
Referenced by GetMaxAccel(), and GetVehicleFuelType().
GetRatedPower()
double PHEMCEP::GetRatedPower () const inline
Getter function to recieve vehicle data from CEP.
Returns
rated power of vehicle
Definition at line 222 of file PHEMCEP.h.
References _ratedPower.
GetResistanceF0()
double PHEMCEP::GetResistanceF0 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f0
Definition at line 143 of file PHEMCEP.h.
References _resistanceF0.
GetResistanceF1()
double PHEMCEP::GetResistanceF1 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f1
Definition at line 151 of file PHEMCEP.h.
References _resistanceF1.
GetResistanceF2()
double PHEMCEP::GetResistanceF2 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f2
Definition at line 159 of file PHEMCEP.h.
References _resistanceF2.
GetResistanceF3()
double PHEMCEP::GetResistanceF3 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f3
Definition at line 167 of file PHEMCEP.h.
References _resistanceF3.
GetResistanceF4()
double PHEMCEP::GetResistanceF4 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f4
Definition at line 175 of file PHEMCEP.h.
References _resistanceF4.
GetRotationalCoeffecient()
double PHEMCEP::GetRotationalCoeffecient (double speed) const private
Calculates rotational index for speed.
Parameters
[in] speed desired speed
Definition at line 325 of file PHEMCEP.cpp.
References _speedCurveRotational, _speedPatternRotational, FindLowerUpperInPattern(), and Interpolate().
Referenced by CalcPower(), GetDecelCoast(), GetMaxAccel(), and GetVehicleFuelType().
GetVehicleFuelType()
const std::string& PHEMCEP::GetVehicleFuelType () const inline
Getter function to recieve vehicle data from CEP.
Returns
fuel type of vehicle
Definition at line 229 of file PHEMCEP.h.
References _vehicleFuelType, FindLowerUpperInPattern(), GetDragCoeffecient(), GetGearCoeffecient(), GetPMaxNorm(), GetRotationalCoeffecient(), and Interpolate().
Referenced by HelpersPHEMlight::compute().
GetVehicleLoading()
double PHEMCEP::GetVehicleLoading () const inline
Getter function to recieve vehicle data from CEP.
Returns
vehicle loading
Definition at line 206 of file PHEMCEP.h.
References _vehicleLoading.
Interpolate()
double PHEMCEP::Interpolate (double px, double p1, double p2, double e1, double e2) const private
Interpolates emission linearly between two known power-emission pairs.
Parameters
[in] px power-value to interpolate
[in] p1 first known power value
[in] p2 second known power value
[in] e1 emission value for p1
[in] e2 emission value for p2
Returns
emission value for px
Definition at line 277 of file PHEMCEP.cpp.
Referenced by GetDragCoeffecient(), GetEmission(), GetGearCoeffecient(), GetPMaxNorm(), GetRotationalCoeffecient(), and GetVehicleFuelType().
Field Documentation
_axleRatio
double PHEMCEP::_axleRatio private
Definition at line 298 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
_cdValue
double PHEMCEP::_cdValue private
Cw value.
Definition at line 279 of file PHEMCEP.h.
Referenced by CalcPower(), GetCdValue(), GetDecelCoast(), and PHEMCEP().
_cepCurveFC
std::vector<double> PHEMCEP::_cepCurveFC private
Todo:
describe
Definition at line 318 of file PHEMCEP.h.
Referenced by GetEmission(), PHEMCEP(), and ~PHEMCEP().
_cepCurvePollutants
StringBijection< std::vector<double> > PHEMCEP::_cepCurvePollutants private
Definition at line 325 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_crossSectionalArea
double PHEMCEP::_crossSectionalArea private
crosssectional area of vehicle
Definition at line 281 of file PHEMCEP.h.
Referenced by CalcPower(), GetCrossSectionalArea(), GetDecelCoast(), and PHEMCEP().
_dragNormTable
std::vector<double> PHEMCEP::_dragNormTable private
Definition at line 324 of file PHEMCEP.h.
Referenced by GetDragCoeffecient(), and PHEMCEP().
_drivingPower
double PHEMCEP::_drivingPower private
Definition at line 308 of file PHEMCEP.h.
Referenced by PHEMCEP().
_effictiveWheelDiameter
double PHEMCEP::_effictiveWheelDiameter private
Definition at line 301 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
_emissionClass
SUMOEmissionClass PHEMCEP::_emissionClass private
PHEM emission class of vehicle.
Definition at line 266 of file PHEMCEP.h.
Referenced by GetEmissionClass(), and PHEMCEP().
_engineIdlingSpeed
double PHEMCEP::_engineIdlingSpeed private
Definition at line 299 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
_engineRatedSpeed
double PHEMCEP::_engineRatedSpeed private
Definition at line 300 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
_gearTransmissionCurve
std::vector<double> PHEMCEP::_gearTransmissionCurve private
Definition at line 322 of file PHEMCEP.h.
Referenced by GetGearCoeffecient(), and PHEMCEP().
_heavyVehicle
bool PHEMCEP::_heavyVehicle private
Definition at line 309 of file PHEMCEP.h.
Referenced by PHEMCEP().
_idlingFC
double PHEMCEP::_idlingFC private
Definition at line 302 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_idlingValuesPollutants
StringBijection<double> PHEMCEP::_idlingValuesPollutants private
Definition at line 327 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_massRot
double PHEMCEP::_massRot private
rotational mass of vehicle
Definition at line 287 of file PHEMCEP.h.
Referenced by CalcPower(), GetMassRot(), GetMaxAccel(), and PHEMCEP().
_massVehicle
double PHEMCEP::_massVehicle private
vehicle mass
Definition at line 283 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetMassVehicle(), GetMaxAccel(), and PHEMCEP().
_nNormTable
std::vector<double> PHEMCEP::_nNormTable private
Definition at line 323 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetDragCoeffecient(), and PHEMCEP().
_normailzedPowerPatternPollutants
std::vector<double> PHEMCEP::_normailzedPowerPatternPollutants private
Definition at line 316 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_normalizedCepCurvePollutants
StringBijection<std::vector<double> > PHEMCEP::_normalizedCepCurvePollutants private
Definition at line 326 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_normalizedPowerPatternFC
std::vector<double> PHEMCEP::_normalizedPowerPatternFC private
Definition at line 315 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_normalizingPower
double PHEMCEP::_normalizingPower private
Definition at line 307 of file PHEMCEP.h.
Referenced by PHEMCEP().
_normalizingType
NormalizingType PHEMCEP::_normalizingType private
Definition at line 267 of file PHEMCEP.h.
Referenced by PHEMCEP().
_normedCepCurveFC
std::vector<double> PHEMCEP::_normedCepCurveFC private
Todo:
describe
Definition at line 320 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
_pNormP0
double PHEMCEP::_pNormP0 private
Step functions parameter for maximum rated power.
Definition at line 293 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
_pNormP1
double PHEMCEP::_pNormP1 private
Step functions parameter for maximum rated power.
Definition at line 297 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
_pNormV0
double PHEMCEP::_pNormV0 private
Step functions parameter for maximum rated power.
Definition at line 291 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
_pNormV1
double PHEMCEP::_pNormV1 private
Step functions parameter for maximum rated power.
Definition at line 295 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
_powerPatternFC
std::vector<double> PHEMCEP::_powerPatternFC private
Todo:
describe
Definition at line 312 of file PHEMCEP.h.
Referenced by GetEmission(), PHEMCEP(), and ~PHEMCEP().
_powerPatternPollutants
std::vector<double> PHEMCEP::_powerPatternPollutants private
Todo:
describe
Definition at line 314 of file PHEMCEP.h.
Referenced by GetEmission(), PHEMCEP(), and ~PHEMCEP().
_ratedPower
double PHEMCEP::_ratedPower private
rated power of vehicle
Definition at line 289 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetMaxAccel(), GetRatedPower(), and PHEMCEP().
_resistanceF0
double PHEMCEP::_resistanceF0 private
Rolling resistance f0.
Definition at line 269 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetResistanceF0(), and PHEMCEP().
_resistanceF1
double PHEMCEP::_resistanceF1 private
Rolling resistance f1.
Definition at line 271 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetResistanceF1(), and PHEMCEP().
_resistanceF2
double PHEMCEP::_resistanceF2 private
Rolling resistance f2.
Definition at line 273 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetResistanceF2(), and PHEMCEP().
_resistanceF3
double PHEMCEP::_resistanceF3 private
Rolling resistance f3.
Definition at line 275 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetResistanceF3(), and PHEMCEP().
_resistanceF4
double PHEMCEP::_resistanceF4 private
Rolling resistance f4.
Definition at line 277 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetResistanceF4(), and PHEMCEP().
_sizeOfPatternFC
int PHEMCEP::_sizeOfPatternFC private
Definition at line 304 of file PHEMCEP.h.
Referenced by PHEMCEP().
_sizeOfPatternPollutants
int PHEMCEP::_sizeOfPatternPollutants private
Todo:
describe
Definition at line 306 of file PHEMCEP.h.
Referenced by PHEMCEP().
_speedCurveRotational
std::vector<double> PHEMCEP::_speedCurveRotational private
Definition at line 321 of file PHEMCEP.h.
Referenced by GetRotationalCoeffecient(), PHEMCEP(), and ~PHEMCEP().
_speedPatternRotational
std::vector<double> PHEMCEP::_speedPatternRotational private
Definition at line 310 of file PHEMCEP.h.
Referenced by GetGearCoeffecient(), GetRotationalCoeffecient(), PHEMCEP(), and ~PHEMCEP().
_vehicleFuelType
std::string PHEMCEP::_vehicleFuelType private
Definition at line 303 of file PHEMCEP.h.
Referenced by GetVehicleFuelType(), and PHEMCEP().
_vehicleLoading
double PHEMCEP::_vehicleLoading private
vehicle loading
Definition at line 285 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetMaxAccel(), GetVehicleLoading(), and PHEMCEP().
The documentation for this class was generated from the following files:
PHEMCEP.h
PHEMCEP.cpp