SUMO - Simulation of Urban MObility: ROAbstractEdgeBuilder Class Reference
ROAbstractEdgeBuilder Class Reference abstract
Interface for building instances of router-edges.
#include <ROAbstractEdgeBuilder.h>
Public Member Functions
ROAbstractEdgeBuilder ()
Constructor.
virtual ~ROAbstractEdgeBuilder ()
Destructor.
Methods to be implemented
virtual ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to, const int priority)=0
Builds an edge with the given name.
Protected Member Functions
int getNextIndex ()
Returns the index of the edge to built.
Private Member Functions
ROAbstractEdgeBuilder & operator= (const ROAbstractEdgeBuilder &src)
Invalidated assignment operator.
ROAbstractEdgeBuilder (const ROAbstractEdgeBuilder &src)
Invalidated copy constructor.
Private Attributes
int myCurrentIndex
The next edge's index.
Detailed Description
Interface for building instances of router-edges.
As the different routing algorithms may need certain types of edges, edges are build via a factory object derived from this class.
The only method to be implemented is "buildEdge" which builds an edge of the needed ROEdge-subtype.
The built edges are numbered in the order they are built, the current number (index) is stored in "myCurrentIndex" and the next to use may be obtained via "getNextIndex".
Definition at line 60 of file ROAbstractEdgeBuilder.h.
Constructor & Destructor Documentation
ROAbstractEdgeBuilder() [1/2]
ROAbstractEdgeBuilder::ROAbstractEdgeBuilder () inline
Constructor.
Definition at line 63 of file ROAbstractEdgeBuilder.h.
~ROAbstractEdgeBuilder()
virtual ROAbstractEdgeBuilder::~ROAbstractEdgeBuilder () inline virtual
Destructor.
Definition at line 67 of file ROAbstractEdgeBuilder.h.
References buildEdge().
ROAbstractEdgeBuilder() [2/2]
ROAbstractEdgeBuilder::ROAbstractEdgeBuilder (const ROAbstractEdgeBuilder & src) private
Invalidated copy constructor.
Member Function Documentation
buildEdge()
virtual ROEdge* ROAbstractEdgeBuilder::buildEdge (const std::string & name, RONode * from, RONode * to, const int priority) pure virtual
Builds an edge with the given name.
Parameters
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] priority The edge priority (road class)
Returns
A proper instance of the named edge
Implemented in RODUAEdgeBuilder, ROMAEdgeBuilder, RODFEdgeBuilder, ROJTREdgeBuilder, and AGStreet::Builder.
Referenced by RONetHandler::parseDistrict(), RONetHandler::parseEdge(), and ~ROAbstractEdgeBuilder().
getNextIndex()
int ROAbstractEdgeBuilder::getNextIndex () inline protected
Returns the index of the edge to built.
Returns
Next valid edge index
Definition at line 89 of file ROAbstractEdgeBuilder.h.
References myCurrentIndex.
Referenced by AGStreet::Builder::buildEdge(), ROJTREdgeBuilder::buildEdge(), RODFEdgeBuilder::buildEdge(), ROMAEdgeBuilder::buildEdge(), and RODUAEdgeBuilder::buildEdge().
operator=()
ROAbstractEdgeBuilder& ROAbstractEdgeBuilder::operator= (const ROAbstractEdgeBuilder & src) private
Invalidated assignment operator.
Field Documentation
myCurrentIndex
int ROAbstractEdgeBuilder::myCurrentIndex private
The next edge's index.
Definition at line 96 of file ROAbstractEdgeBuilder.h.
Referenced by getNextIndex().
The documentation for this class was generated from the following file:
ROAbstractEdgeBuilder.h