SUMO - Simulation of Urban MObility: ROPerson::Stop Class Reference
ROPerson::Stop Class Reference
A planItem can be a Stop.
#include <ROPerson.h>
Public Member Functions
virtual void addTripItem (TripItem *)
const ROEdge * getDestination () const
const ROEdge * getOrigin () const
bool isStop () const
virtual bool needsRouting () const
void saveAsXML (OutputDevice &os, const bool) const
virtual void saveVehicles (OutputDevice &, OutputDevice *const, bool, OptionsCont &) const
Stop (const SUMOVehicleParameter::Stop &stop, const ROEdge *const stopEdge)
Private Member Functions
Stop & operator= (const Stop &src)
Invalidated assignment operator.
Private Attributes
const ROEdge *const edge
SUMOVehicleParameter::Stop stopDesc
Detailed Description
A planItem can be a Stop.
Definition at line 110 of file ROPerson.h.
Constructor & Destructor Documentation
Stop()
ROPerson::Stop::Stop (const SUMOVehicleParameter::Stop & stop, const ROEdge *const stopEdge) inline
Definition at line 112 of file ROPerson.h.
Member Function Documentation
addTripItem()
virtual void ROPerson::PlanItem::addTripItem (TripItem *) inline virtual inherited
Reimplemented in ROPerson::PersonTrip.
Definition at line 91 of file ROPerson.h.
References ROPerson::PlanItem::getDestination(), and ROPerson::PlanItem::getOrigin().
getDestination()
const ROEdge* ROPerson::Stop::getDestination () const inline virtual
Implements ROPerson::PlanItem.
Definition at line 117 of file ROPerson.h.
getOrigin()
const ROEdge* ROPerson::Stop::getOrigin () const inline virtual
Implements ROPerson::PlanItem.
Definition at line 114 of file ROPerson.h.
isStop()
bool ROPerson::Stop::isStop () const inline virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 123 of file ROPerson.h.
needsRouting()
virtual bool ROPerson::PlanItem::needsRouting () const inline virtual inherited
Reimplemented in ROPerson::PersonTrip.
Definition at line 101 of file ROPerson.h.
operator=()
Stop& ROPerson::Stop::operator= (const Stop & src) private
Invalidated assignment operator.
saveAsXML()
void ROPerson::Stop::saveAsXML (OutputDevice & os, const bool) const inline virtual
Implements ROPerson::PlanItem.
Definition at line 120 of file ROPerson.h.
saveVehicles()
virtual void ROPerson::PlanItem::saveVehicles (OutputDevice & , OutputDevice * const, bool , OptionsCont &) const inline virtual inherited
Reimplemented in ROPerson::PersonTrip.
Definition at line 96 of file ROPerson.h.
References ROPerson::PlanItem::saveAsXML().
Referenced by ROPerson::PersonTrip::needsRouting().
Field Documentation
edge
const ROEdge* const ROPerson::Stop::edge private
Definition at line 129 of file ROPerson.h.
stopDesc
SUMOVehicleParameter::Stop ROPerson::Stop::stopDesc private
Definition at line 128 of file ROPerson.h.
The documentation for this class was generated from the following file:
ROPerson.h