SUMO - Simulation of Urban MObility: GNEDialog_Wizard::InputInt Class Reference
GNEDialog_Wizard::InputInt Class Reference
#include <GNEDialog_Wizard.h>
Public Member Functions
InputInt (FXComposite *parent, const std::string &name)
FOX-declaration.
long onCmdSetOption (FXObject *, FXSelector, void *)
try to set new attribute value
Protected Member Functions
InputInt ()
FOX needs this.
Private Attributes
std::string myName
name
FXTextField * myTextField
text field
Detailed Description
Definition at line 105 of file GNEDialog_Wizard.h.
Constructor & Destructor Documentation
InputInt() [1/2]
GNEDialog_Wizard::InputInt::InputInt (FXComposite * parent, const std::string & name)
FOX-declaration.
Definition at line 144 of file GNEDialog_Wizard.cpp.
References OptionsCont::getInt(), OptionsCont::getOptions(), MID_GNE_SET_ATTRIBUTE, myTextField, and toString().
InputInt() [2/2]
GNEDialog_Wizard::InputInt::InputInt () inline protected
FOX needs this.
Definition at line 118 of file GNEDialog_Wizard.h.
Member Function Documentation
onCmdSetOption()
long GNEDialog_Wizard::InputInt::onCmdSetOption (FXObject * , FXSelector , void *)
try to set new attribute value
Definition at line 155 of file GNEDialog_Wizard.cpp.
References OptionsCont::getOptions(), myName, myTextField, OptionsCont::resetWritable(), and OptionsCont::set().
Field Documentation
myName
std::string GNEDialog_Wizard::InputInt::myName private
name
Definition at line 122 of file GNEDialog_Wizard.h.
Referenced by onCmdSetOption().
myTextField
FXTextField* GNEDialog_Wizard::InputInt::myTextField private
text field
Definition at line 125 of file GNEDialog_Wizard.h.
Referenced by InputInt(), and onCmdSetOption().
The documentation for this class was generated from the following files:
GNEDialog_Wizard.h
GNEDialog_Wizard.cpp