SUMO - Simulation of Urban MObility: MSVehicleType Class Reference
MSVehicleType Class Reference
The car-following model and parameter.
#include <MSVehicleType.h>
Public Member Functions
void check ()
Checks whether vehicle type parameters may be problematic (Currently, only the value for the action step length is compared with the value for the desired headway time.)
const SUMOVTypeParameter & getParameter () const
bool isVehicleSpecific () const
Returns whether this type belongs to a single vehicle only (was modified)
MSVehicleType (const SUMOVTypeParameter &parameter)
Constructor.
bool wasSet (int what) const
Returns whether the given parameter was set.
virtual ~MSVehicleType ()
Destructor.
Atomar getter for simulation
const std::string & getID () const
Returns the name of the vehicle type.
int getNumericalID () const
Returns the running index of the vehicle type.
double getLength () const
Get vehicle's length [m].
double getLengthWithGap () const
Get vehicle's length including the minimum gap [m].
double getMinGap () const
Get the free space in front of vehicles of this class.
double getMinGapLat () const
Get the minimum lateral gap that vehicles of this type maintain.
const MSCFModel & getCarFollowModel () const
Returns the vehicle type's car following model definition (const version)
MSCFModel & getCarFollowModel ()
Returns the vehicle type's car following model definition (non-const version)
LaneChangeModel getLaneChangeModel () const
double getMaxSpeed () const
Get vehicle's maximum speed [m/s].
double computeChosenSpeedDeviation (std::mt19937 *rng, const double minDev=-1.) const
Computes and returns the speed deviation.
double getDefaultProbability () const
Get the default probability of this vehicle type.
SUMOVehicleClass getVehicleClass () const
Get this vehicle type's vehicle class.
SUMOEmissionClass getEmissionClass () const
Get this vehicle type's emission class.
const RGBColor & getColor () const
Returns this type's color.
const Distribution_Parameterized & getSpeedFactor () const
Returns this type's speed factor.
SUMOTime getActionStepLength () const
Returns this type's default action step length.
double getActionStepLengthSecs () const
Returns this type's default action step length in seconds.
double getImpatience () const
Returns this type's impatience.
Atomar getter for visualization
double getWidth () const
Get the width which vehicles of this class shall have when being drawn.
double getHeight () const
Get the height which vehicles of this class shall have when being drawn.
SUMOVehicleShape getGuiShape () const
Get this vehicle type's shape.
std::string getOSGFile () const
Get this vehicle type's 3D model file name.
std::string getImgFile () const
Get this vehicle type's raster model file name.
int getPersonCapacity () const
Get this vehicle type's person capacity.
int getContainerCapacity () const
Get this vehicle type's container capacity.
SUMOTime getBoardingDuration () const
Get this vehicle type's boarding duration.
SUMOTime getLoadingDuration () const
Get this vehicle type's loading duration.
double getMaxSpeedLat () const
Get vehicle's maximum lateral speed [m/s].
LateralAlignment getPreferredLateralAlignment () const
Get vehicle's preferred lateral alignment.
Setter methods
void setLength (const double &length)
Set a new value for this type's length.
void setHeight (const double &height)
Set a new value for this type's height.
void setMinGap (const double &minGap)
Set a new value for this type's minimum gap.
void setMinGapLat (const double &minGapLat)
Set a new value for this type's minimum lataral gap.
void setMaxSpeed (const double &maxSpeed)
Set a new value for this type's maximum speed.
void setMaxSpeedLat (const double &maxSpeedLat)
Set a new value for this type's maximum lateral speed.
void setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
void setDefaultProbability (const double &prob)
Set a new value for this type's default probability.
void setSpeedFactor (const double &factor)
Set a new value for this type's speed factor.
void setSpeedDeviation (const double &dev)
Set a new value for this type's speed deviation.
void setActionStepLength (const SUMOTime actionStepLength, bool resetActionOffset)
Set a new value for this type's action step length.
void setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
void setColor (const RGBColor &color)
Set a new value for this type's color.
void setWidth (const double &width)
Set a new value for this type's width.
void setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
void setImpatience (const double impatience)
Set a new value for this type's impatience.
void setPreferredLateralAlignment (LateralAlignment latAlignment)
Set vehicle's preferred lateral alignment.
Private Member Functions
MSVehicleType (const MSVehicleType &)
Invalidated copy constructor.
MSVehicleType & operator= (const MSVehicleType &)
Invalidated assignment operator.
Private Attributes
double myCachedActionStepLengthSecs
the vtypes actionsStepLength in seconds (cached because needed very often)
MSCFModel * myCarFollowModel
instance of the car following model.
const int myIndex
the running index
const MSVehicleType * myOriginalType
The original type.
SUMOVTypeParameter myParameter
the parameter container
bool myWarnedActionStepLengthTauOnce
Indicator whether the user was already warned once about an action step length larger than the desired time headway.
Static Private Attributes
static int myNextIndex = 0
next value for the running index
methods for building vehicle types
MSVehicleType * buildSingularType (const std::string &id) const
Duplicates the microsim vehicle type giving the newly created type the given id, marking it as vehicle specific.
MSVehicleType * duplicateType (const std::string &id, bool persistent) const
Duplicates the microsim vehicle type giving the newly created type the given id.
static MSVehicleType * build (SUMOVTypeParameter &from)
Builds the microsim vehicle type described by the given parameter.
Detailed Description
The car-following model and parameter.
MSVehicleType stores the parameter of a single vehicle type and methods that use these for computing the vehicle's car-following behavior
It is assumed that within the simulation many vehicles are using the same vehicle type, quite common is using only one vehicle type for all vehicles.
You can think of it like of having a vehicle type for each VW Golf or Ford Mustang in your simulation while the car instances just refer to it.
Definition at line 72 of file MSVehicleType.h.
Constructor & Destructor Documentation
MSVehicleType() [1/2]
MSVehicleType::MSVehicleType (const SUMOVTypeParameter & parameter)
Constructor.
Parameters
[in] parameter The vehicle type's parameter
Definition at line 64 of file MSVehicleType.cpp.
References SUMOVTypeParameter::actionStepLength, MSGlobals::gActionStepLength, getLength(), getMaxSpeed(), myCachedActionStepLengthSecs, myParameter, STEPS2TIME, VTYPEPARS_ACTIONSTEPLENGTH_SET, and SUMOVTypeParameter::wasSet().
Referenced by build(), and duplicateType().
~MSVehicleType()
MSVehicleType::~MSVehicleType () virtual
Destructor.
Definition at line 77 of file MSVehicleType.cpp.
References myCarFollowModel.
MSVehicleType() [2/2]
MSVehicleType::MSVehicleType (const MSVehicleType &) private
Invalidated copy constructor.
Member Function Documentation
build()
MSVehicleType * MSVehicleType::build (SUMOVTypeParameter & from) static
Builds the microsim vehicle type described by the given parameter.
Parameters
[in] from The vehicle type description
Returns
The built vehicle type
Exceptions
ProcessError on false values (not et used)
Definition at line 282 of file MSVehicleType.cpp.
References SUMOVTypeParameter::cfModel, check(), SUMOVTypeParameter::getCFParam(), SUMOVTypeParameter::getCFParamString(), SUMOVTypeParameter::getDefaultAccel(), SUMOVTypeParameter::getDefaultDecel(), SUMOVTypeParameter::getDefaultImperfection(), SUMOVTypeParameter::id, MSVehicleType(), myCarFollowModel, SUMO_ATTR_ACCEL, SUMO_ATTR_APPARENTDECEL, SUMO_ATTR_CF_IDM_DELTA, SUMO_ATTR_CF_IDM_STEPPING, SUMO_ATTR_CF_IDMM_ADAPT_FACTOR, SUMO_ATTR_CF_IDMM_ADAPT_TIME, SUMO_ATTR_CF_KERNER_PHI, SUMO_ATTR_CF_PWAGNER2009_APPROB, SUMO_ATTR_CF_PWAGNER2009_TAULAST, SUMO_ATTR_CF_WIEDEMANN_ESTIMATION, SUMO_ATTR_CF_WIEDEMANN_SECURITY, SUMO_ATTR_DECEL, SUMO_ATTR_EMERGENCYDECEL, SUMO_ATTR_K, SUMO_ATTR_SIGMA, SUMO_ATTR_TAU, SUMO_ATTR_TMP1, SUMO_ATTR_TMP2, SUMO_ATTR_TMP3, SUMO_ATTR_TMP4, SUMO_ATTR_TMP5, SUMO_ATTR_TRAIN_TYPE, SUMO_TAG_CF_BKERNER, SUMO_TAG_CF_DANIEL1, SUMO_TAG_CF_IDM, SUMO_TAG_CF_IDMM, SUMO_TAG_CF_KRAUSS, SUMO_TAG_CF_KRAUSS_ORIG1, SUMO_TAG_CF_KRAUSS_PLUS_SLOPE, SUMO_TAG_CF_KRAUSSX, SUMO_TAG_CF_PWAGNER2009, SUMO_TAG_CF_RAIL, SUMO_TAG_CF_SMART_SK, SUMO_TAG_CF_WIEDEMANN, SUMOVTypeParameter::vehicleClass, and WRITE_WARNING.
Referenced by getPreferredLateralAlignment(), MSVehicleControl::MSVehicleControl(), and MSRouteHandler::myEndElement().
buildSingularType()
MSVehicleType * MSVehicleType::buildSingularType (const std::string & id) const
Duplicates the microsim vehicle type giving the newly created type the given id, marking it as vehicle specific.
Parameters
[in] id The new id of the type
Returns
The built vehicle type
Note
This method is used in case that a vType is meant to be used only for a specific vehicle The created vType will be removed with the vehicle or if it is assigned a new type.
Definition at line 370 of file MSVehicleType.cpp.
References duplicateType().
Referenced by getPreferredLateralAlignment(), MSBaseVehicle::getSingularType(), and MSTransportable::getSingularType().
check()
void MSVehicleType::check ()
Checks whether vehicle type parameters may be problematic (Currently, only the value for the action step length is compared with the value for the desired headway time.)
Definition at line 391 of file MSVehicleType.cpp.
References SUMOVTypeParameter::actionStepLength, getCarFollowModel(), MSCFModel::getHeadwayTime(), getID(), myParameter, myWarnedActionStepLengthTauOnce, STEPS2TIME, VTYPEPARS_ACTIONSTEPLENGTH_SET, SUMOVTypeParameter::wasSet(), and WRITE_WARNING.
Referenced by build(), getParameter(), and setActionStepLength().
computeChosenSpeedDeviation()
double MSVehicleType::computeChosenSpeedDeviation (std::mt19937 * rng, const double minDev = -1.) const
Computes and returns the speed deviation.
Returns
A new, random speed deviation
Definition at line 83 of file MSVehicleType.cpp.
References MAX2(), myParameter, Distribution_Parameterized::sample(), and SUMOVTypeParameter::speedFactor.
Referenced by GUITransportableControl::buildPerson(), MSTransportableControl::buildPerson(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), getMaxSpeed(), and MSEdge::insertVehicle().
duplicateType()
MSVehicleType * MSVehicleType::duplicateType (const std::string & id, bool persistent) const
Duplicates the microsim vehicle type giving the newly created type the given id.
Parameters
[in] id The new id of the type
[in] persistent If true the created vType will be persistent and can be used by several vehicles, otherwise it may be removed before simulation end,
See also
buildSingularType()
Returns
The built vehicle type
Definition at line 376 of file MSVehicleType.cpp.
References MSCFModel::duplicate(), getID(), MSNet::getInstance(), SUMOVTypeParameter::id, MSVehicleType(), myCarFollowModel, myOriginalType, and myParameter.
Referenced by buildSingularType(), libsumo::VehicleType::copy(), and getPreferredLateralAlignment().
getActionStepLength()
SUMOTime MSVehicleType::getActionStepLength () const inline
Returns this type's default action step length.
Returns
The default action step length of this type (in ms.)
Definition at line 224 of file MSVehicleType.h.
References SUMOVTypeParameter::actionStepLength, and myParameter.
Referenced by MSVehicle::getActionStepLength().
getActionStepLengthSecs()
double MSVehicleType::getActionStepLengthSecs () const inline
Returns this type's default action step length in seconds.
Returns
The default action step length of this type (in s.)
Definition at line 232 of file MSVehicleType.h.
References myCachedActionStepLengthSecs.
Referenced by libsumo::VehicleType::getActionStepLength(), libsumo::Vehicle::getActionStepLength(), and MSVehicle::getActionStepLengthSecs().
getBoardingDuration()
SUMOTime MSVehicleType::getBoardingDuration () const inline
Get this vehicle type's boarding duration.
Returns
The time a person needs to board a vehicle of this type
Definition at line 306 of file MSVehicleType.h.
References SUMOVTypeParameter::boardingDuration, and myParameter.
Referenced by MSTransportableControl::boardAnyWaiting(), and GUIVehicle::getTypeParameterWindow().
getCarFollowModel() [1/2]
const MSCFModel& MSVehicleType::getCarFollowModel () const inline
Returns the vehicle type's car following model definition (const version)
Returns
The vehicle type's car following model definition
Definition at line 147 of file MSVehicleType.h.
References myCarFollowModel.
Referenced by MSLink::blockedByFoe(), check(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), libsumo::VehicleType::getAccel(), libsumo::VehicleType::getApparentDecel(), libsumo::Vehicle::getApparentDecel(), MSVehicle::getCarFollowModel(), libsumo::VehicleType::getDecel(), libsumo::Vehicle::getDecel(), libsumo::VehicleType::getEmergencyDecel(), libsumo::Vehicle::getEmergencyDecel(), libsumo::VehicleType::getImperfection(), libsumo::Vehicle::getImperfection(), libsumo::VehicleType::getTau(), libsumo::Vehicle::getTau(), MESegment::isOpen(), MSVehicle::MSVehicle(), MSVehicle::processTraCISpeedControl(), MSCalibrator::remainingVehicleCapacity(), libsumo::VehicleType::setAccel(), libsumo::VehicleType::setApparentDecel(), libsumo::VehicleType::setDecel(), libsumo::VehicleType::setEmergencyDecel(), libsumo::VehicleType::setImperfection(), libsumo::VehicleType::setTau(), MSVehicleControl::vehicleDeparted(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
getCarFollowModel() [2/2]
MSCFModel& MSVehicleType::getCarFollowModel () inline
Returns the vehicle type's car following model definition (non-const version)
Returns
The vehicle type's car following model definition
Definition at line 155 of file MSVehicleType.h.
References myCarFollowModel.
getColor()
const RGBColor& MSVehicleType::getColor () const inline
Returns this type's color.
Returns
The color of this type
Definition at line 208 of file MSVehicleType.h.
References SUMOVTypeParameter::color, and myParameter.
Referenced by libsumo::VehicleType::getColor(), and GUIBaseVehicle::setFunctionalColor().
getContainerCapacity()
int MSVehicleType::getContainerCapacity () const inline
Get this vehicle type's container capacity.
Returns
The container capacity of this vehicle type
Definition at line 299 of file MSVehicleType.h.
References SUMOVTypeParameter::containerCapacity, and myParameter.
Referenced by GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), and MSTransportableControl::loadAnyWaiting().
getDefaultProbability()
double MSVehicleType::getDefaultProbability () const inline
Get the default probability of this vehicle type.
Returns
The probability to use this type
Definition at line 182 of file MSVehicleType.h.
References SUMOVTypeParameter::defaultProbability, and myParameter.
Referenced by MSRouteHandler::myEndElement(), MSRouteHandler::openVehicleTypeDistribution(), and setDefaultProbability().
getEmissionClass()
SUMOEmissionClass MSVehicleType::getEmissionClass () const inline
Get this vehicle type's emission class.
Returns
The emission class of this vehicle type
See also
SUMOEmissionClass
Definition at line 200 of file MSVehicleType.h.
References SUMOVTypeParameter::emissionClass, and myParameter.
Referenced by MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), libsumo::VehicleType::getEmissionClass(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
getGuiShape()
SUMOVehicleShape MSVehicleType::getGuiShape () const inline
Get this vehicle type's shape.
Returns
The shape of this vehicle type
See also
SUMOVehicleShape
Definition at line 268 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::shape.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly(), MSVehicle::getBoundingPoly(), and libsumo::VehicleType::getShapeClass().
getHeight()
double MSVehicleType::getHeight () const inline
Get the height which vehicles of this class shall have when being drawn.
Returns
The height of this type's vehicles
Definition at line 260 of file MSVehicleType.h.
References SUMOVTypeParameter::height, and myParameter.
Referenced by libsumo::VehicleType::getHeight(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), and setHeight().
getID()
const std::string& MSVehicleType::getID () const inline
Returns the name of the vehicle type.
Returns
This type's id
Definition at line 100 of file MSVehicleType.h.
References SUMOVTypeParameter::id, and myParameter.
Referenced by MSChargingStation::addChargeValueForOutput(), MSRouteHandler::addPersonTrip(), MSVehicleControl::addVType(), check(), MSRouteHandler::closeVehicle(), MSInductLoop::collectVehiclesOnDet(), duplicateType(), MSVTypeProbe::execute(), libsumo::Simulation::findIntermodalRoute(), MSDevice_Tripinfo::generateOutput(), MSBaseVehicle::getSingularType(), MSTransportable::getSingularType(), libsumo::Person::getSingularVType(), libsumo::Person::getTypeID(), libsumo::Vehicle::getTypeID(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSAbstractLaneChangeModel::laneChangeOutput(), MSInductLoop::leaveDetectorByMove(), MSE2Collector::makeVehicleInfo(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSRouteHandler::myEndElement(), MSDevice_Bluelight::notifyMove(), TraCIServerAPI_Vehicle::processSet(), MSVehicleControl::removeVType(), MSPerson::routeOutput(), MSStopOut::stopEnded(), MSDetectorFileOutput::vehicleApplies(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSDevice_Vehroutes::writeOutput(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
getImgFile()
std::string MSVehicleType::getImgFile () const inline
Get this vehicle type's raster model file name.
Returns
The raster file name of this vehicle type
Definition at line 283 of file MSVehicleType.h.
References SUMOVTypeParameter::imgFile, and myParameter.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), and GUIBaseVehicle::drawAction_drawVehicleAsImage().
getImpatience()
double MSVehicleType::getImpatience () const inline
Returns this type's impatience.
Returns
The impatience of this type
Definition at line 240 of file MSVehicleType.h.
References SUMOVTypeParameter::impatience, and myParameter.
Referenced by MSPModel_Striping::PState::getImpatience(), and setImpatience().
getLaneChangeModel()
LaneChangeModel MSVehicleType::getLaneChangeModel () const inline
Definition at line 160 of file MSVehicleType.h.
References SUMOVTypeParameter::lcModel, and myParameter.
Referenced by MSVehicle::MSVehicle().
getLength()
double MSVehicleType::getLength () const inline
Get vehicle's length [m].
Returns
The length vehicles of this type have in m
Definition at line 116 of file MSVehicleType.h.
References SUMOVTypeParameter::length, and myParameter.
Referenced by MSCFModel_Wiedemann::_v(), MSPModel_Striping::addCrossingVehs(), MSVehicle::addStop(), MSStoppingPlace::addTransportable(), MSLane::basePos(), MSLane::checkForPedestrians(), MSVehicle::checkRewindLinkLanes(), MSInductLoop::collectVehiclesOnDet(), MSLaneChanger::computeOvertakingTime(), MSLane::detectCollisions(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSDevice_SSM::estimateConflictTimes(), MSLane::executeMovements(), MSLane::freeInsertion(), libsumo::Vehicle::getAccel(), MSVehicle::getBackPosition(), MEVehicle::getBackPositionOnLane(), MSVehicle::getBackPositionOnLane(), MSTransportable::getBoundingBox(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartPosBound(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), libsumo::VehicleType::getLength(), libsumo::Vehicle::getLength(), MSPModel_Striping::PState::getLength(), MSBaseVehicle::getLength(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSVehicle::getPositionOnLane(), MSLaneChanger::getRealFollower(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MSLCM_SL2015::keepLatGap(), MSInductLoop::leaveDetectorByMove(), MSLane::leftByLaneChange(), MSE2Collector::makeVehicleInfo(), MSPModel_Striping::moveInDirectionOnLane(), MSVehicleType(), MSPModel_Striping::nextBlocking(), MSInstantInductLoop::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), MSE3Collector::MSE3LeaveReminder::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSLCM_LC2013::overtakeDistance(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSStoppingPlace::removeTransportable(), MSLane::removeVehicle(), GUIVehicle::selectBlockingFoes(), MSLink::setApproaching(), setLength(), MSVehicle::setTentativeLaneAndPosition(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSInstantInductLoop::write(), and MSQueueExport::writeLane().
getLengthWithGap()
double MSVehicleType::getLengthWithGap () const inline
Get vehicle's length including the minimum gap [m].
Returns
The length vehicles of this type have (including the minimum gap in m
Definition at line 124 of file MSVehicleType.h.
References SUMOVTypeParameter::length, SUMOVTypeParameter::minGap, and myParameter.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeToNewLane(), MSLane::checkForPedestrians(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSLane::executeMovements(), MESegment::getTimeHeadway(), MESegment::hasSpaceFor(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), MESegment::isOpen(), MSLane::leftByLaneChange(), MESegment::loadState(), MSVehicle::overlap(), MSLCM_LC2013::overtakeDistance(), MESegment::receive(), MSLaneChanger::ChangeElem::registerHop(), MSLaneChanger::registerUnchanged(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MESegment::removeCar(), MSLane::removeVehicle(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
getLoadingDuration()
SUMOTime MSVehicleType::getLoadingDuration () const inline
Get this vehicle type's loading duration.
Returns
The time a container needs to get laoded on a vehicle of this type
Definition at line 313 of file MSVehicleType.h.
References SUMOVTypeParameter::loadingDuration, and myParameter.
Referenced by GUIVehicle::getTypeParameterWindow(), and MSTransportableControl::loadAnyWaiting().
getMaxSpeed()
double MSVehicleType::getMaxSpeed () const inline
Get vehicle's maximum speed [m/s].
Returns
The maximum speed (in m/s) of vehicles of this class
Definition at line 168 of file MSVehicleType.h.
References computeChosenSpeedDeviation(), SUMOVTypeParameter::maxSpeed, and myParameter.
Referenced by MSRouteHandler::addPersonTrip(), libsumo::Person::appendWalkingStage(), GUIApplicationWindow::checkGamingEvents(), MSCFModel::estimateSpeedAfterDistance(), libsumo::Simulation::findIntermodalRoute(), libsumo::VehicleType::getMaxSpeed(), libsumo::Vehicle::getMaxSpeed(), MSBaseVehicle::getMaxSpeed(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSVehicle::getMaxSpeedOnLane(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), MSCFModel::insertionStopSpeed(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSVehicleType(), MSRouteHandler::myStartElement(), MSPModel_Striping::nextBlocking(), MSPerson::reroute(), libsumo::Person::rerouteTraveltime(), setMaxSpeed(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
getMaxSpeedLat()
double MSVehicleType::getMaxSpeedLat () const inline
Get vehicle's maximum lateral speed [m/s].
Returns
The maximum lateral speed (in m/s) of vehicles of this class
Definition at line 320 of file MSVehicleType.h.
References SUMOVTypeParameter::maxSpeedLat, and myParameter.
Referenced by MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::commitManoeuvre(), MSLCM_SL2015::computeSpeedLat(), libsumo::VehicleType::getMaxSpeedLat(), MSLeaderInfo::getSubLanes(), GUIVehicle::getTypeParameterWindow(), and setMaxSpeedLat().
getMinGap()
double MSVehicleType::getMinGap () const inline
Get the free space in front of vehicles of this class.
Returns
The place before the vehicle
Definition at line 132 of file MSVehicleType.h.
References SUMOVTypeParameter::minGap, and myParameter.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_IDM::_v(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeaders(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLane::detectCollisionBetween(), GUIBaseVehicle::drawOnPos(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getFollowersOnConsecutive(), MSStoppingPlace::getLastFreePos(), MSLane::getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), libsumo::VehicleType::getMinGap(), libsumo::Vehicle::getMinGap(), MSPModel_Striping::PState::getMinGap(), MSLane::getOppositeLeader(), MSLaneChanger::getRealLeader(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSLink::getZipperSpeed(), MSLCM_SL2015::informLeaders(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSE2Collector::makeVehicleInfo(), MSLCM_DK2008::patchSpeed(), MSVehicle::processNextStop(), MSLane::safeInsertionSpeed(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), setMinGap(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
getMinGapLat()
double MSVehicleType::getMinGapLat () const inline
Get the minimum lateral gap that vehicles of this type maintain.
Returns
The place before the vehicle
Definition at line 139 of file MSVehicleType.h.
References SUMOVTypeParameter::minGapLat, and myParameter.
Referenced by libsumo::VehicleType::getMinGapLat(), GUIVehicle::getTypeParameterWindow(), setMinGapLat(), and MSLCM_SL2015::updateGaps().
getNumericalID()
int MSVehicleType::getNumericalID () const inline
Returns the running index of the vehicle type.
Returns
This type's numerical id
Definition at line 108 of file MSVehicleType.h.
References myIndex.
Referenced by MSAmitranTrajectories::writeVehicle().
getOSGFile()
std::string MSVehicleType::getOSGFile () const inline
Get this vehicle type's 3D model file name.
Returns
The model file name of this vehicle type
Definition at line 275 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::osgFile.
getParameter()
const SUMOVTypeParameter& MSVehicleType::getParameter () const inline
Definition at line 524 of file MSVehicleType.h.
References check(), and myParameter.
Referenced by MSLink::blockedAtTime(), MSLink::blockedByFoe(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSLink::getLeaderInfo(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), libsumo::VehicleType::getParameter(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSTriggeredRerouter::getWeight(), MSPModel_Striping::PState::ignoreRed(), MSVehicle::ignoreRed(), MSVehicle::keepClear(), MSCFModel_Krauss::moveHelper(), MSDevice_SSM::requestsTrajectories(), libsumo::VehicleType::setParameter(), and MSDevice_SSM::useGeoCoords().
getPersonCapacity()
int MSVehicleType::getPersonCapacity () const inline
Get this vehicle type's person capacity.
Returns
The person capacity of this vehicle type
Definition at line 291 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::personCapacity.
Referenced by MSTransportableControl::boardAnyWaiting(), GUIMEVehicle::getTypeParameterWindow(), and GUIVehicle::getTypeParameterWindow().
getPreferredLateralAlignment()
LateralAlignment MSVehicleType::getPreferredLateralAlignment () const inline
Get vehicle's preferred lateral alignment.
Returns
The vehicle's preferred lateral alignment
Definition at line 327 of file MSVehicleType.h.
References build(), buildSingularType(), duplicateType(), SUMOVTypeParameter::latAlignment, myParameter, setActionStepLength(), setColor(), setDefaultProbability(), setEmissionClass(), setHeight(), setImpatience(), setLength(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), setMinGapLat(), setPreferredLateralAlignment(), setShape(), setSpeedDeviation(), setSpeedFactor(), setVClass(), and setWidth().
Referenced by MSLCM_SL2015::_wantsChangeSublane(), libsumo::VehicleType::getLateralAlignment(), and GUIVehicle::getTypeParameterWindow().
getSpeedFactor()
const Distribution_Parameterized& MSVehicleType::getSpeedFactor () const inline
Returns this type's speed factor.
Returns
The speed factor of this type
Definition at line 216 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::speedFactor.
Referenced by libsumo::VehicleType::getSpeedDeviation(), libsumo::Vehicle::getSpeedDeviation(), libsumo::VehicleType::getSpeedFactor(), and MSEdge::insertVehicle().
getVehicleClass()
SUMOVehicleClass MSVehicleType::getVehicleClass () const inline
Get this vehicle type's vehicle class.
Returns
The class of this vehicle type
See also
SUMOVehicleClass
Definition at line 191 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::vehicleClass.
Referenced by MSLCM_LC2013::_wantsChange(), MSRouteHandler::addPersonTrip(), MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), MSRouteHandler::closeVehicle(), MSVehicle::executeMove(), libsumo::Simulation::findIntermodalRoute(), MSEdge::getDepartLane(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), libsumo::VehicleType::getVehicleClass(), MSBaseVehicle::hasValidRoute(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSLane::succLinkSec(), MSVehicle::updateBestLanes(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
getWidth()
double MSVehicleType::getWidth () const inline
Get the width which vehicles of this class shall have when being drawn.
Returns
The width of this type's vehicles
Definition at line 253 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::width.
Referenced by MSLCM_LC2013::adaptSpeedToPedestrians(), MSPModel_Striping::addCrossingVehs(), MSLane::checkForPedestrians(), MSDevice_SSM::classifyEncounter(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSLane::getDepartPosLat(), MSLink::getLeaderInfo(), GUIVehicle::getLeftSideOnEdge(), MSPModel_Striping::getNextLaneObstacles(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), libsumo::VehicleType::getWidth(), libsumo::Vehicle::getWidth(), MSLCM_SL2015::getWidth(), MSBaseVehicle::getWidth(), MSLane::insertVehicle(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::PState::otherStripe(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), setWidth(), and MSLCM_SL2015::updateCFRelated().
isVehicleSpecific()
bool MSVehicleType::isVehicleSpecific () const inline
Returns whether this type belongs to a single vehicle only (was modified)
Returns
Whether this vehicle type is based on a different one, and belongs to one vehicle only
Definition at line 519 of file MSVehicleType.h.
References myOriginalType.
Referenced by MSBaseVehicle::getSingularType(), MSTransportable::getSingularType(), MSBaseVehicle::replaceVehicleType(), MSTransportable::replaceVehicleType(), setActionStepLength(), MSTransportable::~MSTransportable(), and MSVehicle::~MSVehicle().
operator=()
MSVehicleType& MSVehicleType::operator= (const MSVehicleType &) private
Invalidated assignment operator.
setActionStepLength()
void MSVehicleType::setActionStepLength (const SUMOTime actionStepLength, bool resetActionOffset)
Set a new value for this type's action step length.
Parameters
[in] actionStepLength The new action step length of this type (in ms.)
[in] resetActionOffset If True (default), the next action point is scheduled immediately. if If resetActionOffset == False, the interval between the last and the next action point is updated to match the given value for all vehicles of this type, or if the latter is smaller than the time since the last action point, the next action follows immediately.
Note
: Singular vtypes do not update the state of the corresponding vehicle, because the global lookup would be too expensive. The caller is responsible to perform the actionOffsetReset operation at caller context, where the vehicle is known.
Definition at line 202 of file MSVehicleType.cpp.
References SUMOVTypeParameter::actionStepLength, check(), MSNet::getInstance(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), isVehicleSpecific(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), myCachedActionStepLengthSecs, myParameter, SUMOVTypeParameter::parametersSet, MSVehicle::resetActionOffset(), STEPS2TIME, MSVehicle::updateActionOffset(), and VTYPEPARS_ACTIONSTEPLENGTH_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setActionStepLength(), and libsumo::Vehicle::setActionStepLength().
setColor()
void MSVehicleType::setColor (const RGBColor & color)
Set a new value for this type's color.
Parameters
[in] color The new color of this type
Definition at line 245 of file MSVehicleType.cpp.
References SUMOVTypeParameter::color, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_COLOR_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setColor(), and libsumo::Person::setColor().
setDefaultProbability()
void MSVehicleType::setDefaultProbability (const double & prob)
Set a new value for this type's default probability.
If the given value<0 then the one from the original type will be used.
Parameters
[in] prob The new default probability of this type
Definition at line 169 of file MSVehicleType.cpp.
References SUMOVTypeParameter::defaultProbability, getDefaultProbability(), myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_PROBABILITY_SET.
Referenced by getPreferredLateralAlignment().
setEmissionClass()
void MSVehicleType::setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
Parameters
[in] eclass The new emission class of this type
Definition at line 238 of file MSVehicleType.cpp.
References SUMOVTypeParameter::emissionClass, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_EMISSIONCLASS_SET.
Referenced by getPreferredLateralAlignment(), and libsumo::VehicleType::setEmissionClass().
setHeight()
void MSVehicleType::setHeight (const double & height)
Set a new value for this type's height.
If the given value<0 then the one from the original type will be used.
Parameters
[in] height The new height of this type
Definition at line 101 of file MSVehicleType.cpp.
References getHeight(), SUMOVTypeParameter::height, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_HEIGHT_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setHeight(), and libsumo::Person::setHeight().
setImpatience()
void MSVehicleType::setImpatience (const double impatience)
Set a new value for this type's impatience.
Parameters
[in] impatience The new impatience of this type
Definition at line 262 of file MSVehicleType.cpp.
References getImpatience(), SUMOVTypeParameter::impatience, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_IMPATIENCE_SET.
Referenced by getPreferredLateralAlignment().
setLength()
void MSVehicleType::setLength (const double & length)
Set a new value for this type's length.
If the given value<0 then the one from the original type will be used.
Parameters
[in] length The new length of this type
Definition at line 90 of file MSVehicleType.cpp.
References getLength(), SUMOVTypeParameter::length, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_LENGTH_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setLength(), and libsumo::Person::setLength().
setMaxSpeed()
void MSVehicleType::setMaxSpeed (const double & maxSpeed)
Set a new value for this type's maximum speed.
If the given value<0 then the one from the original type will be used.
Parameters
[in] maxSpeed The new maximum speed of this type
Definition at line 134 of file MSVehicleType.cpp.
References getMaxSpeed(), SUMOVTypeParameter::maxSpeed, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_MAXSPEED_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setMaxSpeed(), and libsumo::Vehicle::setMaxSpeed().
setMaxSpeedLat()
void MSVehicleType::setMaxSpeedLat (const double & maxSpeedLat)
Set a new value for this type's maximum lateral speed.
If the given value<0 then the one from the original type will be used.
Parameters
[in] maxSpeedLat The new maximum lateral speed of this type
Definition at line 145 of file MSVehicleType.cpp.
References getMaxSpeedLat(), SUMOVTypeParameter::maxSpeedLat, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_MAXSPEED_LAT_SET.
Referenced by getPreferredLateralAlignment(), and libsumo::VehicleType::setMaxSpeedLat().
setMinGap()
void MSVehicleType::setMinGap (const double & minGap)
Set a new value for this type's minimum gap.
If the given value<0 then the one from the original type will be used.
Parameters
[in] minGap The new minimum gap of this type
Definition at line 112 of file MSVehicleType.cpp.
References getMinGap(), SUMOVTypeParameter::minGap, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_MINGAP_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setMinGap(), and libsumo::Person::setMinGap().
setMinGapLat()
void MSVehicleType::setMinGapLat (const double & minGapLat)
Set a new value for this type's minimum lataral gap.
If the given value<0 then the one from the original type will be used.
Parameters
[in] minGapLat The new minimum lateral gap of this type
Definition at line 123 of file MSVehicleType.cpp.
References getMinGapLat(), SUMOVTypeParameter::minGapLat, myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_MINGAP_LAT_SET.
Referenced by getPreferredLateralAlignment(), and libsumo::VehicleType::setMinGapLat().
setPreferredLateralAlignment()
void MSVehicleType::setPreferredLateralAlignment (LateralAlignment latAlignment)
Set vehicle's preferred lateral alignment.
Definition at line 162 of file MSVehicleType.cpp.
References SUMOVTypeParameter::latAlignment, myParameter, SUMOVTypeParameter::parametersSet, and VTYPEPARS_LATALIGNMENT_SET.
Referenced by getPreferredLateralAlignment(), MSDevice_Bluelight::notifyMove(), and libsumo::VehicleType::setLateralAlignment().
setShape()
void MSVehicleType::setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
Parameters
[in] shape The new shape of this type
Definition at line 273 of file MSVehicleType.cpp.
References myParameter, SUMOVTypeParameter::parametersSet, SUMOVTypeParameter::shape, and VTYPEPARS_SHAPE_SET.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setShapeClass(), and libsumo::Vehicle::setShapeClass().
setSpeedDeviation()
void MSVehicleType::setSpeedDeviation (const double & dev)
Set a new value for this type's speed deviation.
If the given value<0 then the one from the original type will be used.
Parameters
[in] dev The new speed deviation of this type
Definition at line 191 of file MSVehicleType.cpp.
References Distribution_Parameterized::getParameter(), myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, SUMOVTypeParameter::speedFactor, and VTYPEPARS_SPEEDFACTOR_SET.
Referenced by getPreferredLateralAlignment(), and libsumo::VehicleType::setSpeedDeviation().
setSpeedFactor()
void MSVehicleType::setSpeedFactor (const double & factor)
Set a new value for this type's speed factor.
If the given value<0 then the one from the original type will be used.
Parameters
[in] factor The new speed factor of this type
Definition at line 180 of file MSVehicleType.cpp.
References Distribution_Parameterized::getParameter(), myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, SUMOVTypeParameter::speedFactor, and VTYPEPARS_SPEEDFACTOR_SET.
Referenced by getPreferredLateralAlignment(), and libsumo::VehicleType::setSpeedFactor().
setVClass()
void MSVehicleType::setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
Parameters
[in] vclass The new vehicle class of this type
Definition at line 156 of file MSVehicleType.cpp.
References myParameter, SUMOVTypeParameter::parametersSet, SUMOVTypeParameter::vehicleClass, and VTYPEPARS_VEHICLECLASS_SET.
Referenced by getPreferredLateralAlignment(), and libsumo::VehicleType::setVehicleClass().
setWidth()
void MSVehicleType::setWidth (const double & width)
Set a new value for this type's width.
If the given value<0 then the one from the original type will be used.
Parameters
[in] width The new width of this type
Definition at line 252 of file MSVehicleType.cpp.
References getWidth(), myOriginalType, myParameter, SUMOVTypeParameter::parametersSet, VTYPEPARS_WIDTH_SET, and SUMOVTypeParameter::width.
Referenced by getPreferredLateralAlignment(), libsumo::VehicleType::setWidth(), and libsumo::Person::setWidth().
wasSet()
bool MSVehicleType::wasSet (int what) const inline
Returns whether the given parameter was set.
Parameters
[in] what The parameter which one asks for
Returns
Whether the given parameter was set
Definition at line 89 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::parametersSet.
Referenced by MSRouteHandler::myStartElement(), and GUIBaseVehicle::setFunctionalColor().
Field Documentation
myCachedActionStepLengthSecs
double MSVehicleType::myCachedActionStepLengthSecs private
the vtypes actionsStepLength in seconds (cached because needed very often)
Definition at line 539 of file MSVehicleType.h.
Referenced by getActionStepLengthSecs(), MSVehicleType(), and setActionStepLength().
myCarFollowModel
MSCFModel* MSVehicleType::myCarFollowModel private
instance of the car following model.
Definition at line 549 of file MSVehicleType.h.
Referenced by build(), duplicateType(), getCarFollowModel(), and ~MSVehicleType().
myIndex
const int MSVehicleType::myIndex private
the running index
Definition at line 546 of file MSVehicleType.h.
Referenced by getNumericalID().
myNextIndex
int MSVehicleType::myNextIndex = 0 static private
next value for the running index
Definition at line 555 of file MSVehicleType.h.
myOriginalType
const MSVehicleType* MSVehicleType::myOriginalType private
The original type.
Definition at line 552 of file MSVehicleType.h.
Referenced by duplicateType(), isVehicleSpecific(), setDefaultProbability(), setHeight(), setImpatience(), setLength(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), setMinGapLat(), setSpeedDeviation(), setSpeedFactor(), and setWidth().
myParameter
SUMOVTypeParameter MSVehicleType::myParameter private
the parameter container
Definition at line 536 of file MSVehicleType.h.
Referenced by check(), computeChosenSpeedDeviation(), duplicateType(), getActionStepLength(), getBoardingDuration(), getColor(), getContainerCapacity(), getDefaultProbability(), getEmissionClass(), getGuiShape(), getHeight(), getID(), getImgFile(), getImpatience(), getLaneChangeModel(), getLength(), getLengthWithGap(), getLoadingDuration(), getMaxSpeed(), getMaxSpeedLat(), getMinGap(), getMinGapLat(), getOSGFile(), getParameter(), getPersonCapacity(), getPreferredLateralAlignment(), getSpeedFactor(), getVehicleClass(), getWidth(), MSVehicleType(), setActionStepLength(), setColor(), setDefaultProbability(), setEmissionClass(), setHeight(), setImpatience(), setLength(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), setMinGapLat(), setPreferredLateralAlignment(), setShape(), setSpeedDeviation(), setSpeedFactor(), setVClass(), setWidth(), and wasSet().
myWarnedActionStepLengthTauOnce
bool MSVehicleType::myWarnedActionStepLengthTauOnce private
Indicator whether the user was already warned once about an action step length larger than the desired time headway.
Definition at line 543 of file MSVehicleType.h.
Referenced by check().
The documentation for this class was generated from the following files:
MSVehicleType.h
MSVehicleType.cpp