SUMO - Simulation of Urban MObility: MSChargingStation Class Reference
MSChargingStation Class Reference
#include <MSChargingStation.h>
Data Structures
struct charge
struct to save information for the cahrgingStation output
Public Member Functions
virtual void addAccess (MSLane *lane, const double pos)
adds an access point to this stop
void addChargeValueForOutput (double WCharged, MSDevice_Battery *battery)
add charge value for output
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void addTransportable (MSTransportable *p)
adds a transportable to this stop
void enter (SUMOVehicle *what, double beg, double end)
Called if a vehicle enters this stop.
double getAccessPos (const MSEdge *edge) const
the position on the given edge which is connected to this stop, -1 on failure
const std::multimap< MSLane *, double > & getAllAccessPos () const
lanes and positions connected to this stop
double getBeginLanePosition () const
Returns the begin position of this stop.
double getChargeDelay () const
Get Charge Delay.
bool getChargeInTransit () const
Get chargeInTransit.
double getChargingPower () const
Get charging station's charging power.
double getEfficency () const
Get efficiency of the charging station.
double getEndLanePosition () const
Returns the end position of this stop.
const std::string & getID () const
Returns the id.
const MSLane & getLane () const
Returns the lane this stop is located at.
double getLastFreePos (const SUMOVehicle &forVehicle) const
Returns the last free position on this stop.
const std::string & getMyName () const
double getStoppingPosition (const SUMOVehicle *veh) const
For vehicles at the stop this gives the the actual stopping position of the vehicle. For all others the last free stopping position.
double getTotalCharged () const
int getTransportableNumber () const
Returns the number of transportables waiting on this stop.
double getWaitingPositionOnLane () const
Returns the lane position corresponding to getWaitPosition()
Position getWaitPosition () const
Returns the next free waiting place for pedestrians / containers.
bool hasAccess (const MSEdge *edge) const
checks whether this stop provides access to the given edge
bool isCharging () const
Return true if in the current time step charging station is charging a vehicle.
void leaveFrom (SUMOVehicle *what)
Called if a vehicle leaves this stop.
MSChargingStation (const std::string &chargingStationID, MSLane &lane, double startPos, double endPos, double chargingPower, double efficency, bool chargeInTransit, double chargeDelay)
constructor
void removeTransportable (MSTransportable *p)
Removes a transportable from this stop.
void setChargeDelay (double chargeDelay)
Set charge delay of the charging station.
void setChargeInTransit (bool chargeInTransit)
Set charge in transit of the charging station.
void setChargingPower (double chargingPower)
Set charging station's charging power.
void setChargingVehicle (bool value)
enable or disable charging vehicle
void setEfficency (double efficency)
Set efficiency of the charging station.
void setID (const std::string &newID)
resets the id
bool vehicleIsInside (const double position) const
Check if a vehicle is inside in the Charge Station.
void writeChargingStationOutput (OutputDevice &output)
write charging station values
~MSChargingStation ()
destructor
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
void computeLastFreePos ()
Computes the last free position on this stop.
Protected Attributes
std::multimap< MSLane *, double > myAccessPos
lanes and positions connected to this stop
const double myBegPos
The begin position this bus stop is located at.
double myChargeDelay
Charge Delay.
bool myChargeInTransit
Allow charge in transit.
std::vector< charge > myChargeValues
vector with the charges of this charging station
double myChargingPower
Charging station's charging power.
bool myChargingVehicle
Check if in the current TimeStep chargingStation is charging a vehicle.
double myEfficiency
Efficiency of the charging station.
const double myEndPos
The end position this bus stop is located at.
std::map< const SUMOVehicle *, std::pair< double, double > > myEndPositions
A map from objects (vehicles) to the areas they acquire after entering the stop.
std::string myID
The name of the object.
const MSLane & myLane
The lane this bus stop is located at.
double myLastFreePos
The last free position at this stop (variable)
std::vector< std::string > myLines
The list of lines that are assigned to this stop.
const std::string myName
The name of the stopping place.
double myTotalCharge
total energy charged by this charging station
double myWaitingPos
The next free position for persons / containers.
std::vector< MSTransportable * > myWaitingTransportables
Persons waiting at this stop.
Private Member Functions
MSChargingStation (const MSChargingStation &)
Invalidated copy constructor.
MSChargingStation & operator= (const MSChargingStation &)
Invalidated assignment operator.
Detailed Description
Definition at line 57 of file MSChargingStation.h.
Constructor & Destructor Documentation
MSChargingStation() [1/2]
MSChargingStation::MSChargingStation (const std::string & chargingStationID, MSLane & lane, double startPos, double endPos, double chargingPower, double efficency, bool chargeInTransit, double chargeDelay)
constructor
Definition at line 47 of file MSChargingStation.cpp.
References MSStoppingPlace::getBeginLanePosition(), getChargingPower(), getEfficency(), MSStoppingPlace::getEndLanePosition(), Named::getID(), myChargeDelay, myChargingPower, myEfficiency, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_EFFICIENCY, SUMO_TAG_CHARGING_STATION, toString(), and WRITE_WARNING.
~MSChargingStation()
MSChargingStation::~MSChargingStation ()
destructor
Definition at line 80 of file MSChargingStation.cpp.
MSChargingStation() [2/2]
MSChargingStation::MSChargingStation (const MSChargingStation &) private
Invalidated copy constructor.
Member Function Documentation
addAccess()
virtual void MSStoppingPlace::addAccess (MSLane * lane, const double pos) inline virtual inherited
adds an access point to this stop
Reimplemented in GUIBusStop.
Definition at line 173 of file MSStoppingPlace.h.
References MSStoppingPlace::myAccessPos.
Referenced by GUIBusStop::addAccess(), and NLTriggerBuilder::addAccess().
addChargeValueForOutput()
void MSChargingStation::addChargeValueForOutput (double WCharged, MSDevice_Battery * battery)
add charge value for output
Definition at line 167 of file MSChargingStation.cpp.
References MSDevice_Battery::getActualBatteryCapacity(), MSDevice_Battery::getChargingStartTime(), MSDevice::getHolder(), SUMOVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSDevice_Battery::getMaximumBatteryCapacity(), SUMOVehicle::getSpeed(), MSDevice_Battery::getStoppingTreshold(), SUMOVehicle::getVehicleType(), myChargeDelay, myChargeInTransit, myChargeValues, myChargingPower, myEfficiency, and myTotalCharge.
Referenced by getTotalCharged(), and MSDevice_Battery::notifyMove().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
addTransportable()
void MSStoppingPlace::addTransportable (MSTransportable * p) inherited
adds a transportable to this stop
Definition at line 108 of file MSStoppingPlace.cpp.
References MSVehicleType::getLength(), MSTransportable::getVehicleType(), MAX2(), MSStoppingPlace::myBegPos, MSStoppingPlace::myWaitingPos, and MSStoppingPlace::myWaitingTransportables.
Referenced by MSStoppingPlace::getTransportableNumber(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
computeLastFreePos()
void MSStoppingPlace::computeLastFreePos () protected inherited
Computes the last free position on this stop.
The last free position is the one, the last vehicle ends at. It is stored in myLastFreePos. If no vehicle halts, the last free position gets the value of myEndPos.
Definition at line 139 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myEndPos, MSStoppingPlace::myEndPositions, and MSStoppingPlace::myLastFreePos.
Referenced by MSStoppingPlace::enter(), MSStoppingPlace::getAllAccessPos(), MSStoppingPlace::leaveFrom(), and MSStoppingPlace::MSStoppingPlace().
enter()
void MSStoppingPlace::enter (SUMOVehicle * what, double beg, double end) inherited
Called if a vehicle enters this stop.
Stores the position of the entering vehicle in myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that enters the bus stop
[in] beg The begin halting position of the vehicle
[in] what The end halting position of the vehicle
See also
computeLastFreePos
Definition at line 76 of file MSStoppingPlace.cpp.
References MSStoppingPlace::computeLastFreePos(), and MSStoppingPlace::myEndPositions.
Referenced by MSVehicle::processNextStop().
getAccessPos()
double MSStoppingPlace::getAccessPos (const MSEdge * edge) const inherited
the position on the given edge which is connected to this stop, -1 on failure
Definition at line 151 of file MSStoppingPlace.cpp.
References MSLane::getEdge(), MSStoppingPlace::myAccessPos, MSStoppingPlace::myBegPos, MSStoppingPlace::myEndPos, and MSStoppingPlace::myLane.
Referenced by MSRouteHandler::addPersonTrip(), MSStoppingPlace::getAllAccessPos(), and MSRouteHandler::parseWalkPositions().
getAllAccessPos()
const std::multimap<MSLane*, double>& MSStoppingPlace::getAllAccessPos () const inline inherited
lanes and positions connected to this stop
Definition at line 178 of file MSStoppingPlace.h.
References MSStoppingPlace::computeLastFreePos(), MSStoppingPlace::getAccessPos(), MSStoppingPlace::hasAccess(), and MSStoppingPlace::myAccessPos.
getBeginLanePosition()
double MSStoppingPlace::getBeginLanePosition () const inherited
Returns the begin position of this stop.
Returns
The position the stop begins at
Definition at line 64 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myBegPos.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getStoppingPlaceID(), MSChargingStation(), MSRouteHandler::parseWalkPositions(), MSVehicle::processNextStop(), MSVehicle::replaceParkingArea(), MSTriggeredRerouter::rerouteParkingArea(), and vehicleIsInside().
getChargeDelay()
double MSChargingStation::getChargeDelay () const
Get Charge Delay.
Definition at line 103 of file MSChargingStation.cpp.
References myChargeDelay.
Referenced by MSDevice_Battery::notifyMove().
getChargeInTransit()
bool MSChargingStation::getChargeInTransit () const
Get chargeInTransit.
Definition at line 97 of file MSChargingStation.cpp.
References myChargeInTransit.
Referenced by MSDevice_Battery::notifyMove().
getChargingPower()
double MSChargingStation::getChargingPower () const
Get charging station's charging power.
Definition at line 85 of file MSChargingStation.cpp.
References myChargingPower.
Referenced by MSChargingStation(), and MSDevice_Battery::notifyMove().
getEfficency()
double MSChargingStation::getEfficency () const
Get efficiency of the charging station.
Definition at line 91 of file MSChargingStation.cpp.
References myEfficiency.
Referenced by MSChargingStation(), and MSDevice_Battery::notifyMove().
getEndLanePosition()
double MSStoppingPlace::getEndLanePosition () const inherited
Returns the end position of this stop.
Returns
The position the stop ends at
Definition at line 70 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myEndPos.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getStoppingPlaceID(), MSChargingStation(), MSTriggeredRerouter::notifyEnter(), MSRouteHandler::parseWalkPositions(), MSVehicle::processNextStop(), MSStoppingPlace::removeTransportable(), MSVehicle::replaceParkingArea(), MSTriggeredRerouter::rerouteParkingArea(), and vehicleIsInside().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), setChargeDelay(), setChargingPower(), NBEdge::setControllingTLInformation(), setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getLane()
const MSLane & MSStoppingPlace::getLane () const inherited
Returns the lane this stop is located at.
Returns
Reference to the lane the stop is located at
Definition at line 58 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myLane.
Referenced by MSRouteHandler::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSNet::getStoppingPlaceID(), MSTriggeredRerouter::notifyEnter(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::replaceParkingArea(), and MSTriggeredRerouter::rerouteParkingArea().
getLastFreePos()
double MSStoppingPlace::getLastFreePos (const SUMOVehicle & forVehicle) const inherited
Returns the last free position on this stop.
Returns
The last free position of this bus stop
Definition at line 83 of file MSStoppingPlace.cpp.
References MSVehicleType::getMinGap(), SUMOVehicle::getVehicleType(), MSStoppingPlace::myEndPos, and MSStoppingPlace::myLastFreePos.
Referenced by MSStoppingPlace::getStoppingPosition(), and MSVehicle::processNextStop().
getMyName()
const std::string & MSStoppingPlace::getMyName () const inherited
Definition at line 179 of file MSStoppingPlace.cpp.
References MSStoppingPlace::myName.
Referenced by GUIBusStop::drawGL(), and GUIBusStop::getParameterWindow().
getStoppingPosition()
double MSStoppingPlace::getStoppingPosition (const SUMOVehicle * veh) const inherited
For vehicles at the stop this gives the the actual stopping position of the vehicle. For all others the last free stopping position.
Definition at line 98 of file MSStoppingPlace.cpp.
References MSStoppingPlace::getLastFreePos(), and MSStoppingPlace::myEndPositions.
Referenced by MSStoppingPlace::getWaitingPositionOnLane().
getTotalCharged()
double MSChargingStation::getTotalCharged () const inline
Definition at line 103 of file MSChargingStation.h.
References addChargeValueForOutput(), myTotalCharge, and writeChargingStationOutput().
Referenced by libsumo::Simulation::getParameter().
getTransportableNumber()
int MSStoppingPlace::getTransportableNumber () const inline inherited
Returns the number of transportables waiting on this stop.
Definition at line 162 of file MSStoppingPlace.h.
References MSStoppingPlace::addTransportable(), MSStoppingPlace::myWaitingTransportables, and MSStoppingPlace::removeTransportable().
Referenced by GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), and TraCIServerAPI_Simulation::processGet().
getWaitingPositionOnLane()
double MSStoppingPlace::getWaitingPositionOnLane () const inline inherited
Returns the lane position corresponding to getWaitPosition()
Returns
The waiting position along the stop lane
Definition at line 149 of file MSStoppingPlace.h.
References MSStoppingPlace::getStoppingPosition(), and MSStoppingPlace::myWaitingPos.
Referenced by MSPerson::MSPersonStage_Driving::proceed().
getWaitPosition()
Position MSStoppingPlace::getWaitPosition () const inherited
Returns the next free waiting place for pedestrians / containers.
Returns
The next free waiting place for pedestrians / containers
Definition at line 92 of file MSStoppingPlace.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSStoppingPlace::myLane, MSStoppingPlace::myWaitingPos, and PositionVector::positionAtOffset().
Referenced by MSPerson::MSPersonStage_Driving::proceed().
hasAccess()
bool MSStoppingPlace::hasAccess (const MSEdge * edge) const inherited
checks whether this stop provides access to the given edge
Definition at line 165 of file MSStoppingPlace.cpp.
References MSLane::getEdge(), MSStoppingPlace::myAccessPos, and MSStoppingPlace::myLane.
Referenced by MSStoppingPlace::getAllAccessPos().
isCharging()
bool MSChargingStation::isCharging () const
Return true if in the current time step charging station is charging a vehicle.
Definition at line 161 of file MSChargingStation.cpp.
References myChargingVehicle.
leaveFrom()
void MSStoppingPlace::leaveFrom (SUMOVehicle * what) inherited
Called if a vehicle leaves this stop.
Removes the position of the vehicle from myEndPositions.
Recomputes the free space using "computeLastFreePos" then.
Parameters
[in] what The vehicle that leaves the bus stop
See also
computeLastFreePos
Definition at line 131 of file MSStoppingPlace.cpp.
References MSStoppingPlace::computeLastFreePos(), and MSStoppingPlace::myEndPositions.
operator=()
MSChargingStation& MSChargingStation::operator= (const MSChargingStation &) private
Invalidated assignment operator.
removeTransportable()
void MSStoppingPlace::removeTransportable (MSTransportable * p) inherited
Removes a transportable from this stop.
Definition at line 116 of file MSStoppingPlace.cpp.
References MSStoppingPlace::getEndLanePosition(), MSVehicleType::getLength(), MSTransportable::getVehicleType(), MSStoppingPlace::myWaitingPos, and MSStoppingPlace::myWaitingTransportables.
Referenced by MSStoppingPlace::getTransportableNumber(), and MSVehicle::processNextStop().
setChargeDelay()
void MSChargingStation::setChargeDelay (double chargeDelay)
Set charge delay of the charging station.
Definition at line 135 of file MSChargingStation.cpp.
References Named::getID(), myChargeDelay, SUMO_ATTR_CHARGEDELAY, SUMO_TAG_CHARGING_STATION, toString(), and WRITE_WARNING.
setChargeInTransit()
void MSChargingStation::setChargeInTransit (bool chargeInTransit)
Set charge in transit of the charging station.
Definition at line 129 of file MSChargingStation.cpp.
References myChargeInTransit.
setChargingPower()
void MSChargingStation::setChargingPower (double chargingPower)
Set charging station's charging power.
Definition at line 109 of file MSChargingStation.cpp.
References Named::getID(), myChargingPower, SUMO_ATTR_CHARGINGPOWER, SUMO_TAG_CHARGING_STATION, toString(), and WRITE_WARNING.
setChargingVehicle()
void MSChargingStation::setChargingVehicle (bool value)
enable or disable charging vehicle
Definition at line 145 of file MSChargingStation.cpp.
References myChargingVehicle.
Referenced by MSDevice_Battery::notifyMove().
setEfficency()
void MSChargingStation::setEfficency (double efficency)
Set efficiency of the charging station.
Definition at line 119 of file MSChargingStation.cpp.
References Named::getID(), myEfficiency, SUMO_ATTR_EFFICIENCY, SUMO_TAG_CHARGING_STATION, toString(), and WRITE_WARNING.
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
vehicleIsInside()
bool MSChargingStation::vehicleIsInside (const double position) const
Check if a vehicle is inside in the Charge Station.
Parameters
[in] position Position of vehicle in the LANE
Returns
true if is between StartPostion and EndPostion
Definition at line 151 of file MSChargingStation.cpp.
References MSStoppingPlace::getBeginLanePosition(), and MSStoppingPlace::getEndLanePosition().
writeChargingStationOutput()
void MSChargingStation::writeChargingStationOutput (OutputDevice & output)
write charging station values
Definition at line 197 of file MSChargingStation.cpp.
References OutputDevice::closeTag(), myChargeValues, Named::myID, myTotalCharge, OutputDevice::openTag(), SUMO_ATTR_ACTUALBATTERYCAPACITY, SUMO_ATTR_CHARGING_STATUS, SUMO_ATTR_CHARGINGBEGIN, SUMO_ATTR_CHARGINGEND, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CHARGINGSTEPS, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENERGYCHARGED, SUMO_ATTR_ID, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, SUMO_ATTR_PARTIALCHARGE, SUMO_ATTR_TIME, SUMO_ATTR_TOTALENERGYCHARGED, SUMO_ATTR_TOTALENERGYCHARGED_VEHICLE, SUMO_ATTR_TYPE, SUMO_TAG_CHARGING_STATION, SUMO_TAG_STEP, SUMO_TAG_VEHICLE, time2string(), and OutputDevice::writeAttr().
Referenced by getTotalCharged().
Field Documentation
myAccessPos
std::multimap<MSLane*, double> MSStoppingPlace::myAccessPos protected inherited
lanes and positions connected to this stop
Definition at line 230 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addAccess(), MSStoppingPlace::getAccessPos(), MSStoppingPlace::getAllAccessPos(), and MSStoppingPlace::hasAccess().
myBegPos
const double MSStoppingPlace::myBegPos protected inherited
The begin position this bus stop is located at.
Definition at line 209 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), MSParkingArea::computeLastFreePos(), MSStoppingPlace::getAccessPos(), MSStoppingPlace::getBeginLanePosition(), GUIContainerStop::getParameterWindow(), GUIChargingStation::getParameterWindow(), GUIBusStop::getParameterWindow(), GUIParkingArea::getParameterWindow(), MSParkingArea::getSpaceDim(), and MSParkingArea::MSParkingArea().
myChargeDelay
double MSChargingStation::myChargeDelay protected
Charge Delay.
Definition at line 164 of file MSChargingStation.h.
Referenced by addChargeValueForOutput(), getChargeDelay(), GUIChargingStation::getParameterWindow(), MSChargingStation(), and setChargeDelay().
myChargeInTransit
bool MSChargingStation::myChargeInTransit protected
Allow charge in transit.
Definition at line 161 of file MSChargingStation.h.
Referenced by addChargeValueForOutput(), getChargeInTransit(), GUIChargingStation::getParameterWindow(), and setChargeInTransit().
myChargeValues
std::vector<charge> MSChargingStation::myChargeValues protected
vector with the charges of this charging station
Definition at line 173 of file MSChargingStation.h.
Referenced by addChargeValueForOutput(), and writeChargingStationOutput().
myChargingPower
double MSChargingStation::myChargingPower protected
Charging station's charging power.
Definition at line 155 of file MSChargingStation.h.
Referenced by addChargeValueForOutput(), GUIChargingStation::drawGL(), getChargingPower(), GUIChargingStation::getParameterWindow(), MSChargingStation(), and setChargingPower().
myChargingVehicle
bool MSChargingStation::myChargingVehicle protected
Check if in the current TimeStep chargingStation is charging a vehicle.
Definition at line 167 of file MSChargingStation.h.
Referenced by GUIChargingStation::drawGL(), isCharging(), and setChargingVehicle().
myEfficiency
double MSChargingStation::myEfficiency protected
Efficiency of the charging station.
Definition at line 158 of file MSChargingStation.h.
Referenced by addChargeValueForOutput(), getEfficency(), GUIChargingStation::getParameterWindow(), MSChargingStation(), and setEfficency().
myEndPos
const double MSStoppingPlace::myEndPos protected inherited
The end position this bus stop is located at.
Definition at line 212 of file MSStoppingPlace.h.
Referenced by MSParkingArea::addLotEntry(), MSStoppingPlace::computeLastFreePos(), MSStoppingPlace::getAccessPos(), MSStoppingPlace::getEndLanePosition(), MSStoppingPlace::getLastFreePos(), GUIChargingStation::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), GUIParkingArea::getParameterWindow(), and MSParkingArea::getSpaceDim().
myEndPositions
std::map<const SUMOVehicle*, std::pair<double, double> > MSStoppingPlace::myEndPositions protected inherited
A map from objects (vehicles) to the areas they acquire after entering the stop.
Definition at line 203 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::computeLastFreePos(), MSParkingArea::enter(), MSStoppingPlace::enter(), MSParkingArea::getOccupancy(), MSStoppingPlace::getStoppingPosition(), MSParkingArea::leaveFrom(), and MSStoppingPlace::leaveFrom().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myLane
const MSLane& MSStoppingPlace::myLane protected inherited
The lane this bus stop is located at.
Definition at line 206 of file MSStoppingPlace.h.
Referenced by GUIParkingArea::drawGL(), MSStoppingPlace::getAccessPos(), MSStoppingPlace::getLane(), MSParkingArea::getSpaceDim(), MSStoppingPlace::getWaitPosition(), and MSStoppingPlace::hasAccess().
myLastFreePos
double MSStoppingPlace::myLastFreePos protected inherited
The last free position at this stop (variable)
Definition at line 215 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::computeLastFreePos(), MSParkingArea::computeLastFreePos(), MSParkingArea::getLastFreePos(), and MSStoppingPlace::getLastFreePos().
myLines
std::vector<std::string> MSStoppingPlace::myLines protected inherited
The list of lines that are assigned to this stop.
Definition at line 200 of file MSStoppingPlace.h.
Referenced by GUIContainerStop::drawGL(), GUIBusStop::drawGL(), and GUIParkingArea::drawGL().
myName
const std::string MSStoppingPlace::myName protected inherited
The name of the stopping place.
Definition at line 221 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::getMyName().
myTotalCharge
double MSChargingStation::myTotalCharge protected
total energy charged by this charging station
Definition at line 170 of file MSChargingStation.h.
Referenced by addChargeValueForOutput(), getTotalCharged(), and writeChargingStationOutput().
myWaitingPos
double MSStoppingPlace::myWaitingPos protected inherited
The next free position for persons / containers.
Definition at line 218 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), MSStoppingPlace::getWaitingPositionOnLane(), MSStoppingPlace::getWaitPosition(), and MSStoppingPlace::removeTransportable().
myWaitingTransportables
std::vector<MSTransportable*> MSStoppingPlace::myWaitingTransportables protected inherited
Persons waiting at this stop.
Definition at line 227 of file MSStoppingPlace.h.
Referenced by MSStoppingPlace::addTransportable(), GUIContainerStop::drawGL(), GUIParkingArea::drawGL(), MSStoppingPlace::getTransportableNumber(), and MSStoppingPlace::removeTransportable().
The documentation for this class was generated from the following files:
MSChargingStation.h
MSChargingStation.cpp