SUMO - Simulation of Urban MObility: CState Class Reference
CState Class Reference
#include <MSCModel_NonInteracting.h>
Public Member Functions
SUMOTime computeTranshipTime (const MSEdge *prev, const MSContainer::MSContainerStage_Tranship &stage, SUMOTime currentTime)
compute tranship time on edge and update state members
CState ()
double getAngle (const MSContainer::MSContainerStage_Tranship &stage, SUMOTime now) const
return the direction in which the container heading to
double getEdgePos (const MSContainer::MSContainerStage_Tranship &stage, SUMOTime now) const
return the offset from the start of the current edge measured in its natural direction
Position getPosition (const MSContainer::MSContainerStage_Tranship &stage, SUMOTime now) const
return the network coordinate of the container
double getSpeed (const MSContainer::MSContainerStage_Tranship &stage) const
return the current speed of the container
~CState ()
Static Public Attributes
static const int BACKWARD
static const int FORWARD
static const double LATERAL_OFFSET
the offset for computing container positions when being transhiped
static const int UNDEFINED_DIRECTION
Private Attributes
double myCurrentBeginPos
Position myCurrentBeginPosition
SUMOTime myCurrentDuration
double myCurrentEndPos
Position myCurrentEndPosition
SUMOTime myLastEntryTime
Detailed Description
Definition at line 98 of file MSCModel_NonInteracting.h.
Constructor & Destructor Documentation
CState()
CState::CState () inline
Definition at line 100 of file MSCModel_NonInteracting.h.
~CState()
CState::~CState () inline
Definition at line 102 of file MSCModel_NonInteracting.h.
Member Function Documentation
computeTranshipTime()
SUMOTime CState::computeTranshipTime (const MSEdge * prev, const MSContainer::MSContainerStage_Tranship & stage, SUMOTime currentTime)
compute tranship time on edge and update state members
Definition at line 140 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getDepartPos(), MSContainer::MSContainerStage_Tranship::getFromEdge(), MSTransportable::Stage::getLanePosition(), MSEdge::getLanes(), MSContainer::MSContainerStage_Tranship::getMaxSpeed(), MSContainer::MSContainerStage_Tranship::getToEdge(), MAX2(), and TIME2STEPS.
Referenced by MSCModel_NonInteracting::add(), and MSCModel_NonInteracting::MoveToNextEdge::execute().
getAngle()
double CState::getAngle (const MSContainer::MSContainerStage_Tranship & stage, SUMOTime now) const
return the direction in which the container heading to
Definition at line 124 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getEdge(), MSTransportable::Stage::getEdgeAngle(), and M_PI.
Referenced by MSContainer::MSContainerStage_Tranship::getAngle().
getEdgePos()
double CState::getEdgePos (const MSContainer::MSContainerStage_Tranship & stage, SUMOTime now) const
return the offset from the start of the current edge measured in its natural direction
Definition at line 110 of file MSCModel_NonInteracting.cpp.
Referenced by MSContainer::MSContainerStage_Tranship::getEdgePos().
getPosition()
Position CState::getPosition (const MSContainer::MSContainerStage_Tranship & stage, SUMOTime now) const
return the network coordinate of the container
Definition at line 116 of file MSCModel_NonInteracting.cpp.
References Position::distanceTo2D(), MSContainer::MSContainerStage_Tranship::getMaxSpeed(), MIN2(), PositionVector::positionAtOffset2D(), and STEPS2TIME.
Referenced by MSContainer::MSContainerStage_Tranship::getPosition().
getSpeed()
double CState::getSpeed (const MSContainer::MSContainerStage_Tranship & stage) const
return the current speed of the container
Definition at line 134 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getMaxSpeed().
Referenced by MSContainer::MSContainerStage_Tranship::getSpeed().
Field Documentation
BACKWARD
const int CState::BACKWARD static
Definition at line 106 of file MSCModel_NonInteracting.h.
FORWARD
const int CState::FORWARD static
Definition at line 102 of file MSCModel_NonInteracting.h.
LATERAL_OFFSET
const double CState::LATERAL_OFFSET static
the offset for computing container positions when being transhiped
Definition at line 110 of file MSCModel_NonInteracting.h.
myCurrentBeginPos
double CState::myCurrentBeginPos private
Definition at line 127 of file MSCModel_NonInteracting.h.
myCurrentBeginPosition
Position CState::myCurrentBeginPosition private
Definition at line 129 of file MSCModel_NonInteracting.h.
myCurrentDuration
SUMOTime CState::myCurrentDuration private
Definition at line 126 of file MSCModel_NonInteracting.h.
myCurrentEndPos
double CState::myCurrentEndPos private
Definition at line 128 of file MSCModel_NonInteracting.h.
myCurrentEndPosition
Position CState::myCurrentEndPosition private
Definition at line 130 of file MSCModel_NonInteracting.h.
myLastEntryTime
SUMOTime CState::myLastEntryTime private
Definition at line 125 of file MSCModel_NonInteracting.h.
UNDEFINED_DIRECTION
const int CState::UNDEFINED_DIRECTION static
Definition at line 107 of file MSCModel_NonInteracting.h.
The documentation for this class was generated from the following files:
MSCModel_NonInteracting.h
MSCModel_NonInteracting.cpp