SUMO - Simulation of Urban MObility: bezier.cpp File Reference
bezier.cpp File Reference
#include <config.h>
#include <cmath>
#include <iostream>
#include <utils/common/StdDefs.h>
#include "PositionVector.h"
Functions
double Basis (int n, int i, double t)
void bezier (int npts, double b[], int cpts, double p[])
PositionVector bezier (const PositionVector &init, int numPoints)
double factrl (int n)
double Ni (int n, int i)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
2003-11-19
Version
$Id$
Definition in file bezier.cpp.
Function Documentation
Basis()
double Basis (int n, int i, double t)
Definition at line 87 of file bezier.cpp.
References Ni().
Referenced by bezier().
bezier() [1/2]
void bezier (int npts, double b[], int cpts, double p[])
Definition at line 96 of file bezier.cpp.
References Basis().
Referenced by bezier(), NBNode::computeSmoothShape(), GNEEdge::smoothShape(), NWWriter_OpenDrive::writeGeomSmooth(), and NWWriter_OpenDrive::writeInternalEdge().
bezier() [2/2]
PositionVector bezier (const PositionVector & init, int numPoints)
Definition at line 133 of file bezier.cpp.
References bezier(), ISNAN(), Position::x(), Position::y(), and Position::z().
factrl()
double factrl (int n)
Definition at line 57 of file bezier.cpp.
Referenced by Ni().
Ni()
double Ni (int n, int i)
Definition at line 81 of file bezier.cpp.
References factrl().
Referenced by Basis().