SUMO - Simulation of Urban MObility: NINavTeqHelper Class Reference
NINavTeqHelper Class Reference
Some parser methods shared around several formats containing NavTeq-Nets.
#include <NINavTeqHelper.h>
Static Public Member Functions
static void addVehicleClasses (NBEdge &e, const std::string &classS)
Adds vehicle classes parsing the given list of allowed vehicles.
static void addVehicleClassesV6 (NBEdge &e, const std::string &classS)
same as addVehicleClasses but for version 6+
static int getLaneNumber (const std::string &id, const std::string &laneNoS, double speed)
Returns the lane number evaluating the given Navteq-description.
static double getSpeed (const std::string &id, const std::string &speedClassS)
Returns the speed evaluating the given Navteq-description.
Detailed Description
Some parser methods shared around several formats containing NavTeq-Nets.
Networks from NavTeq ofte use categories for speed limits and the number of lanes. This class parses such categories and converts them into proper values.
Definition at line 56 of file NINavTeqHelper.h.
Member Function Documentation
addVehicleClasses()
void NINavTeqHelper::addVehicleClasses (NBEdge & e, const std::string & classS) static
Adds vehicle classes parsing the given list of allowed vehicles.
Parses the given class-string and sets all set (allowed) vehicle types into the given edge using "addVehicleClass".
Parameters
[in] e The edge to set the parsed vehicle classes into
[in] classS The string that contains the information whether a vehicle class is allowed
See also
addVehicleClass
Definition at line 106 of file NINavTeqHelper.cpp.
References NBEdge::allowVehicleClass(), NBEdge::setPermissions(), SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_DELIVERY, SVC_EMERGENCY, SVC_HOV, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_TAXI, SVC_TRAILER, SVC_TRUCK, and SVCAll.
Referenced by NIImporter_DlrNavteq::EdgesHandler::report().
addVehicleClassesV6()
void NINavTeqHelper::addVehicleClassesV6 (NBEdge & e, const std::string & classS) static
same as addVehicleClasses but for version 6+
Definition at line 159 of file NINavTeqHelper.cpp.
References NBEdge::allowVehicleClass(), NBEdge::setPermissions(), SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_DELIVERY, SVC_EMERGENCY, SVC_HOV, SVC_MOTORCYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_TAXI, SVC_TRAILER, SVC_TRUCK, and SVCAll.
Referenced by NIImporter_DlrNavteq::EdgesHandler::report().
getLaneNumber()
int NINavTeqHelper::getLaneNumber (const std::string & id, const std::string & laneNoS, double speed) static
Returns the lane number evaluating the given Navteq-description.
Parameters
[in] id The id of the edge (for debug-output)
[in] laneNoS The string that describes the number of lanes
[in] speed An additional hint for guessing the proper lane number
Returns
The converted lane number
Exceptions
ProcessError If the given lane number definition is not a number or if it is not known
Definition at line 76 of file NINavTeqHelper.cpp.
References TplConvert::_2int().
Referenced by NIImporter_ArcView::load(), and NIImporter_DlrNavteq::EdgesHandler::report().
getSpeed()
double NINavTeqHelper::getSpeed (const std::string & id, const std::string & speedClassS) static
Returns the speed evaluating the given Navteq-description.
This method tries to parse the speed category into its int-representation and to determine the speed that is assigned to the category. If either of both steps can not be perfored, a ProcessError is thrown.
Parameters
[in] id The id of the edge (for debug-output)
[in] speedClassS The string that describes the speed class
Returns
The converted speed (in m/s)
Exceptions
ProcessError If the given speed class definition is not a number or if it is not known
Definition at line 44 of file NINavTeqHelper.cpp.
References TplConvert::_2int().
Referenced by NIImporter_ArcView::load(), and NIImporter_DlrNavteq::EdgesHandler::report().
The documentation for this class was generated from the following files:
NINavTeqHelper.h
NINavTeqHelper.cpp