SUMO - Simulation of Urban MObility: NIImporter_OpenStreetMap::EdgesHandler Class Reference
NIImporter_OpenStreetMap::EdgesHandler Class Reference
A class which extracts OSM-edges from a parsed OSM-file.
#include <NIImporter_OpenStreetMap.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
EdgesHandler (const std::map< long long int, NIOSMNode *> &osmNodes, std::map< long long int, Edge *> &toFill, std::map< long long int, Edge *> &platformShapes)
Constructor.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~EdgesHandler () override
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs) override
Called on the opening of a tag;.
void myEndElement (int element) override
Called when a closing tag occurs.
Private Member Functions
EdgesHandler (const EdgesHandler &s)
invalidated copy constructor
EdgesHandler & operator= (const EdgesHandler &s)
invalidated assignment operator
Private Attributes
Edge * myCurrentEdge
The currently built edge.
std::map< long long int, Edge * > & myEdgeMap
A map of built edges.
const std::map< long long int, NIOSMNode * > & myOSMNodes
The previously parsed nodes.
std::vector< int > myParentElements
The element stack.
std::map< long long int, Edge * > & myPlatformShapesMap
A map of built edges.
std::map< std::string, double > mySpeedMap
A map of non-numeric speed descriptions to their numeric values.
Detailed Description
A class which extracts OSM-edges from a parsed OSM-file.
Definition at line 367 of file NIImporter_OpenStreetMap.h.
Constructor & Destructor Documentation
EdgesHandler() [1/2]
NIImporter_OpenStreetMap::EdgesHandler::EdgesHandler (const std::map< long long int, NIOSMNode *> & osmNodes, std::map< long long int, Edge *> & toFill, std::map< long long int, Edge *> & platformShapes)
Constructor.
Parameters
[in] osmNodes The previously parsed (osm-)nodes
[in,out] toFill The edges container to fill with read edges
Definition at line 777 of file NIImporter_OpenStreetMap.cpp.
References NIImporter_OpenStreetMap::MAXSPEED_UNGIVEN, mySpeedMap, and ~EdgesHandler().
~EdgesHandler()
NIImporter_OpenStreetMap::EdgesHandler::~EdgesHandler () override default
Destructor.
Referenced by EdgesHandler().
EdgesHandler() [2/2]
NIImporter_OpenStreetMap::EdgesHandler::EdgesHandler (const EdgesHandler & s) private
invalidated copy constructor
Member Function Documentation
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void NIImporter_OpenStreetMap::EdgesHandler::myEndElement (int element) override protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 1035 of file NIImporter_OpenStreetMap.cpp.
References NIImporter_OpenStreetMap::Edge::id, myCurrentEdge, NIImporter_OpenStreetMap::Edge::myCurrentIsPlatform, NIImporter_OpenStreetMap::Edge::myCurrentIsRoad, myEdgeMap, myParentElements, myPlatformShapesMap, and SUMO_TAG_WAY.
myStartElement()
void NIImporter_OpenStreetMap::EdgesHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) override protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 798 of file NIImporter_OpenStreetMap.cpp.
References TplConvert::_2double(), TplConvert::_2int(), NIImporter_OpenStreetMap::compoundTypeSeparator, StringUtils::endsWith(), SUMOSAXAttributes::get(), OptionsCont::getBool(), OptionsCont::getOptions(), SUMOSAXAttributes::getStringSecure(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), NIImporter_OpenStreetMap::Edge::id, joinToStringSorting(), MIN2(), NIImporter_OpenStreetMap::Edge::myBuswayType, myCurrentEdge, NIImporter_OpenStreetMap::Edge::myCurrentIsPlatform, NIImporter_OpenStreetMap::Edge::myCurrentIsRoad, NIImporter_OpenStreetMap::Edge::myCurrentNodes, NIImporter_OpenStreetMap::Edge::myCyclewayType, NIImporter_OpenStreetMap::Edge::myHighWayType, NIImporter_OpenStreetMap::Edge::myIsOneWay, NIImporter_OpenStreetMap::Edge::myLayer, NIImporter_OpenStreetMap::Edge::myMaxSpeed, NIImporter_OpenStreetMap::Edge::myNoLanes, NIImporter_OpenStreetMap::Edge::myNoLanesForward, myOSMNodes, myParentElements, NIImporter_OpenStreetMap::Edge::myParkingType, mySpeedMap, NIImporter_OpenStreetMap::PARKING_BOTH, NIImporter_OpenStreetMap::PARKING_LEFT, NIImporter_OpenStreetMap::PARKING_RIGHT, StringUtils::prune(), Parameterised::setParameter(), StringUtils::startsWith(), NIImporter_OpenStreetMap::Edge::streetName, SUMO_ATTR_ID, SUMO_ATTR_K, SUMO_ATTR_REF, SUMO_ATTR_V, SUMO_TAG_ND, SUMO_TAG_TAG, SUMO_TAG_WAY, StringUtils::to_lower_case(), toString(), NIImporter_OpenStreetMap::WAY_BACKWARD, NIImporter_OpenStreetMap::WAY_BOTH, NIImporter_OpenStreetMap::WAY_FORWARD, NIImporter_OpenStreetMap::WAY_UNKNOWN, and WRITE_WARNING.
operator=()
EdgesHandler& NIImporter_OpenStreetMap::EdgesHandler::operator= (const EdgesHandler & s) private
invalidated assignment operator
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myCurrentEdge
Edge* NIImporter_OpenStreetMap::EdgesHandler::myCurrentEdge private
The currently built edge.
Definition at line 417 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), and myStartElement().
myEdgeMap
std::map<long long int, Edge*>& NIImporter_OpenStreetMap::EdgesHandler::myEdgeMap private
A map of built edges.
Definition at line 411 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement().
myOSMNodes
const std::map<long long int, NIOSMNode*>& NIImporter_OpenStreetMap::EdgesHandler::myOSMNodes private
The previously parsed nodes.
Definition at line 408 of file NIImporter_OpenStreetMap.h.
Referenced by myStartElement().
myParentElements
std::vector<int> NIImporter_OpenStreetMap::EdgesHandler::myParentElements private
The element stack.
Definition at line 420 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement(), and myStartElement().
myPlatformShapesMap
std::map<long long int, Edge*>& NIImporter_OpenStreetMap::EdgesHandler::myPlatformShapesMap private
A map of built edges.
Definition at line 414 of file NIImporter_OpenStreetMap.h.
Referenced by myEndElement().
mySpeedMap
std::map<std::string, double> NIImporter_OpenStreetMap::EdgesHandler::mySpeedMap private
A map of non-numeric speed descriptions to their numeric values.
Definition at line 423 of file NIImporter_OpenStreetMap.h.
Referenced by EdgesHandler(), and myStartElement().
The documentation for this class was generated from the following files:
NIImporter_OpenStreetMap.h
NIImporter_OpenStreetMap.cpp