SUMO - Simulation of Urban MObility: NBOwnTLDef::edge_by_incoming_priority_sorter Class Reference
NBOwnTLDef::edge_by_incoming_priority_sorter Class Reference
Sorts edges by their priority within the node they end at.
#include <NBOwnTLDef.h>
Public Member Functions
int operator() (const NBEdge *const e1, const NBEdge *const e2) const
comparing operator
Detailed Description
Sorts edges by their priority within the node they end at.
Definition at line 244 of file NBOwnTLDef.h.
Member Function Documentation
operator()()
int NBOwnTLDef::edge_by_incoming_priority_sorter::operator() (const NBEdge *const e1, const NBEdge *const e2) const inline
comparing operator
Parameters
[in] e1 an edge
[in] e2 an edge
Definition at line 250 of file NBOwnTLDef.h.
References Named::getID(), NBEdge::getJunctionPriority(), and NBEdge::getToNode().
The documentation for this class was generated from the following file:
NBOwnTLDef.h