SUMO - Simulation of Urban MObility: PedestrianRouterDijkstra< E, L, N, V > Class Template Reference
PedestrianRouterDijkstra< E, L, N, V > Class Template Reference
#include <PedestrianRouter.h>
Public Types
typedef IntermodalEdge< E, L, N, V > _IntermodalEdge
typedef IntermodalNetwork< E, L, N, V > _IntermodalNetwork
typedef IntermodalTrip< E, N, V > _IntermodalTrip
typedef double(* Operation) (const E *const, const IntermodalTrip< E, N, V > *const, double)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter< E, _IntermodalTrip > * clone ()
double compute (const E *from, const E *to, double departPos, double arrivalPos, double speed, SUMOTime msTime, const N *onlyNode, std::vector< const E * > &into, bool allEdges=false)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
bool compute (const E *, const E *, const _IntermodalTrip *const, SUMOTime, std::vector< const E * > &)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
double getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, double t) const
void prohibit (const std::vector< E * > &toProhibit)
double recomputeCosts (const std::vector< const E * > &, const _IntermodalTrip *const, SUMOTime) const
void setBulkMode (const bool mode)
void startQuery ()
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Detailed Description
template<class E, class L, class N, class V>
class PedestrianRouterDijkstra< E, L, N, V >
Definition at line 159 of file PedestrianRouter.h.
Member Typedef Documentation
_IntermodalEdge
typedef IntermodalEdge<E, L, N, V> PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::_IntermodalEdge inherited
Definition at line 57 of file PedestrianRouter.h.
_IntermodalNetwork
typedef IntermodalNetwork<E, L, N, V> PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::_IntermodalNetwork inherited
Definition at line 58 of file PedestrianRouter.h.
_IntermodalTrip
typedef IntermodalTrip<E, N, V> PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::_IntermodalTrip inherited
Definition at line 59 of file PedestrianRouter.h.
Operation
typedef double(* SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::Operation) (const E *const, const IntermodalTrip< E, N, V > *const, double) inherited
Type of the function that is used to retrieve the edge effort.
Definition at line 55 of file SUMOAbstractRouter.h.
Member Function Documentation
clone()
virtual SUMOAbstractRouter<E, _IntermodalTrip>* PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::clone () inline virtual inherited
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 82 of file PedestrianRouter.h.
References PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet.
compute() [1/2]
double PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute (const E * from, const E * to, double departPos, double arrivalPos, double speed, SUMOTime msTime, const N * onlyNode, std::vector< const E *> & into, bool allEdges = false) inline inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Definition at line 88 of file PedestrianRouter.h.
References IntermodalNetwork< E, L, N, V >::getArrivalConnector(), IntermodalNetwork< E, L, N, V >::getDepartConnector(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::myInternalRouter, PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet, TIME2STEPS, toString(), and WRITE_WARNING.
compute() [2/2]
bool PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute (const E * , const E * , const _IntermodalTrip * const, SUMOTime , std::vector< const E *> &) inline virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 127 of file PedestrianRouter.h.
endQuery()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myQueryStartTime, SUMOAbstractRouter< E, V >::myQueryTimeSum, and SUMOAbstractRouter< E, V >::myQueryVisits.
getEffort()
double SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myOperation.
prohibit()
void PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::prohibit (const std::vector< E *> & toProhibit) inline inherited
Definition at line 136 of file PedestrianRouter.h.
References IntermodalNetwork< E, L, N, V >::getBothDirections(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::myInternalRouter, and PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet.
recomputeCosts()
double PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::recomputeCosts (const std::vector< const E *> & , const _IntermodalTrip * const, SUMOTime) const inline virtual inherited
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 132 of file PedestrianRouter.h.
setBulkMode()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myBulkMode.
startQuery()
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myNumQueries, and SUMOAbstractRouter< E, V >::myQueryStartTime.
Field Documentation
myBulkMode
bool SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
myOperation
Operation SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
The documentation for this class was generated from the following file:
PedestrianRouter.h