SUMO - Simulation of Urban MObility: TraCIAPI::PersonScope Class Reference
TraCIAPI::PersonScope Class Reference
Scope for interaction with vehicles.
#include <TraCIAPI.h>
Public Member Functions
void add (const std::string &personID, const std::string &edgeID, double pos, double depart=DEPARTFLAG_NOW, const std::string typeID="DEFAULT_PEDTYPE")
void appendDrivingStage (const std::string &personID, const std::string &toEdge, const std::string &lines, const std::string &stopID="")
void appendWaitingStage (const std::string &personID, double duration, const std::string &description="waiting", const std::string &stopID="")
void appendWalkingStage (const std::string &personID, const std::vector< std::string > &edges, double arrivalPos, double duration=-1, double speed=-1, const std::string &stopID="")
std::vector< std::string > getEdges (const std::string &personID, int nextStageIndex=0) const
int getIDCount () const
std::vector< std::string > getIDList () const
std::string getNextEdge (const std::string &personID) const
libsumo::TraCIPosition getPosition (const std::string &personID) const
int getRemainingStages (const std::string &personID) const
std::string getRoadID (const std::string &personID) const
double getSpeed (const std::string &personID) const
int getStage (const std::string &personID, int nextStageIndex=0) const
std::string getTypeID (const std::string &personID) const
std::string getVehicle (const std::string &personID) const
double getWaitingTime (const std::string &personID) const
PersonScope (TraCIAPI &parent)
void removeStage (const std::string &personID, int nextStageIndex) const
void removeStages (const std::string &personID) const
void rerouteTraveltime (const std::string &personID) const
void setColor (const std::string &personID, const libsumo::TraCIColor &c) const
void setHeight (const std::string &personID, double height) const
void setLength (const std::string &personID, double length) const
void setMinGap (const std::string &personID, double minGap) const
void setSpeed (const std::string &personID, double speed) const
void setType (const std::string &personID, const std::string &typeID) const
void setWidth (const std::string &personID, double width) const
virtual ~PersonScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
PersonScope & operator= (const PersonScope &src)
invalidated assignment operator
PersonScope (const PersonScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with vehicles.
Definition at line 748 of file TraCIAPI.h.
Constructor & Destructor Documentation
PersonScope() [1/2]
TraCIAPI::PersonScope::PersonScope (TraCIAPI & parent) inline
Definition at line 750 of file TraCIAPI.h.
~PersonScope()
virtual TraCIAPI::PersonScope::~PersonScope () inline virtual
Definition at line 751 of file TraCIAPI.h.
References DEPARTFLAG_NOW, TraCIAPI::getPosition(), and TraCIAPI::TraCIScopeWrapper::operator=().
PersonScope() [2/2]
TraCIAPI::PersonScope::PersonScope (const PersonScope & src) private
invalidated copy constructor
Member Function Documentation
add()
void TraCIAPI::PersonScope::add (const std::string & personID, const std::string & edgeID, double pos, double depart = DEPARTFLAG_NOW, const std::string typeID = "DEFAULT_PEDTYPE")
Definition at line 2821 of file TraCIAPI.cpp.
References ADD, CMD_SET_PERSON_VARIABLE, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
appendDrivingStage()
void TraCIAPI::PersonScope::appendDrivingStage (const std::string & personID, const std::string & toEdge, const std::string & lines, const std::string & stopID = "")
Definition at line 2886 of file TraCIAPI.cpp.
References APPEND_STAGE, CMD_SET_PERSON_VARIABLE, STAGE_DRIVING, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
appendWaitingStage()
void TraCIAPI::PersonScope::appendWaitingStage (const std::string & personID, double duration, const std::string & description = "waiting", const std::string & stopID = "")
Definition at line 2842 of file TraCIAPI.cpp.
References APPEND_STAGE, CMD_SET_PERSON_VARIABLE, STAGE_WAITING, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRING, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
appendWalkingStage()
void TraCIAPI::PersonScope::appendWalkingStage (const std::string & personID, const std::vector< std::string > & edges, double arrivalPos, double duration = -1, double speed = -1, const std::string & stopID = "")
Definition at line 2861 of file TraCIAPI.cpp.
References APPEND_STAGE, CMD_SET_PERSON_VARIABLE, STAGE_WALKING, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
getEdges()
std::vector< std::string > TraCIAPI::PersonScope::getEdges (const std::string & personID, int nextStageIndex = 0) const
Definition at line 2793 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, TYPE_INTEGER, VAR_EDGES, tcpip::Storage::writeByte(), and tcpip::Storage::writeInt().
Referenced by TraCITestClient::testAPI().
getIDCount()
int TraCIAPI::PersonScope::getIDCount () const
Definition at line 2739 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and ID_COUNT.
getIDList()
std::vector< std::string > TraCIAPI::PersonScope::getIDList () const
Definition at line 2734 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and ID_LIST.
Referenced by TraCITestClient::testAPI().
getNextEdge()
std::string TraCIAPI::PersonScope::getNextEdge (const std::string & personID) const
Definition at line 2769 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_NEXT_EDGE.
Referenced by TraCITestClient::testAPI().
getPosition()
TraCIPosition TraCIAPI::PersonScope::getPosition (const std::string & personID) const
Definition at line 2749 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_POSITION.
getRemainingStages()
int TraCIAPI::PersonScope::getRemainingStages (const std::string & personID) const
Definition at line 2780 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_STAGES_REMAINING.
Referenced by TraCITestClient::testAPI().
getRoadID()
std::string TraCIAPI::PersonScope::getRoadID (const std::string & personID) const
Definition at line 2754 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_ROAD_ID.
Referenced by TraCITestClient::testAPI().
getSpeed()
double TraCIAPI::PersonScope::getSpeed (const std::string & personID) const
Definition at line 2744 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_SPEED.
Referenced by TraCITestClient::testAPI().
getStage()
int TraCIAPI::PersonScope::getStage (const std::string & personID, int nextStageIndex = 0) const
Definition at line 2785 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, TYPE_INTEGER, VAR_STAGE, tcpip::Storage::writeByte(), and tcpip::Storage::writeInt().
Referenced by TraCITestClient::testAPI().
getTypeID()
std::string TraCIAPI::PersonScope::getTypeID (const std::string & personID) const
Definition at line 2759 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_TYPE.
Referenced by TraCITestClient::testAPI().
getVehicle()
std::string TraCIAPI::PersonScope::getVehicle (const std::string & personID) const
Definition at line 2775 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_VEHICLE.
Referenced by TraCITestClient::testAPI().
getWaitingTime()
double TraCIAPI::PersonScope::getWaitingTime (const std::string & personID) const
Definition at line 2764 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_WAITING_TIME.
Referenced by TraCITestClient::testAPI().
operator=()
PersonScope& TraCIAPI::PersonScope::operator= (const PersonScope & src) private
invalidated assignment operator
removeStage()
void TraCIAPI::PersonScope::removeStage (const std::string & personID, int nextStageIndex) const
Definition at line 2904 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, REMOVE_STAGE, TYPE_INTEGER, tcpip::Storage::writeByte(), and tcpip::Storage::writeInt().
Referenced by TraCITestClient::testAPI().
removeStages()
void TraCIAPI::PersonScope::removeStages (const std::string & personID) const
Definition at line 2801 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
rerouteTraveltime()
void TraCIAPI::PersonScope::rerouteTraveltime (const std::string & personID) const
Definition at line 2811 of file TraCIAPI.cpp.
References CMD_REROUTE_TRAVELTIME, CMD_SET_PERSON_VARIABLE, TYPE_COMPOUND, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setColor()
void TraCIAPI::PersonScope::setColor (const std::string & personID, const libsumo::TraCIColor & c) const
Definition at line 2978 of file TraCIAPI.cpp.
References libsumo::TraCIColor::a, libsumo::TraCIColor::b, CMD_SET_PERSON_VARIABLE, libsumo::TraCIColor::g, libsumo::TraCIColor::r, TYPE_COLOR, VAR_COLOR, and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setHeight()
void TraCIAPI::PersonScope::setHeight (const std::string & personID, double height) const
Definition at line 2957 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, TYPE_DOUBLE, VAR_HEIGHT, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setLength()
void TraCIAPI::PersonScope::setLength (const std::string & personID, double length) const
Definition at line 2936 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, TYPE_DOUBLE, VAR_LENGTH, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setMinGap()
void TraCIAPI::PersonScope::setMinGap (const std::string & personID, double minGap) const
Definition at line 2967 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, TYPE_DOUBLE, VAR_MINGAP, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setSpeed()
void TraCIAPI::PersonScope::setSpeed (const std::string & personID, double speed) const
Definition at line 2915 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, TYPE_DOUBLE, VAR_SPEED, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setType()
void TraCIAPI::PersonScope::setType (const std::string & personID, const std::string & typeID) const
Definition at line 2926 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, TYPE_STRING, VAR_TYPE, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setWidth()
void TraCIAPI::PersonScope::setWidth (const std::string & personID, double width) const
Definition at line 2947 of file TraCIAPI.cpp.
References CMD_SET_PERSON_VARIABLE, TYPE_DOUBLE, VAR_WIDTH, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp