SUMO - Simulation of Urban MObility: MEVehicle Class Reference
MEVehicle Class Reference
A vehicle from the mesoscopic point of view.
#include <MEVehicle.h>
Public Types
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
virtual void activateReminders (const MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
"Activates" all current move reminder
virtual void addContainer (MSTransportable *container)
Adds a container to this vehicle.
virtual void addPerson (MSTransportable *person)
Adds a person to this vehicle.
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0, bool collision=false, MSRouteIterator *searchStart=0)
Adds a stop.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
void createDevice (const std::string &deviceName)
create device of the given type
double estimateLeaveSpeed (const MSLink *link) const
Returns the vehicle's estimated speed after driving accross the link.
virtual double getAcceleration () const
Returns the vehicle's acceleration.
SUMOTime getAccumulatedWaitingTime () const
Returns the duration for which the vehicle was blocked.
double getAngle () const
Returns the vehicle's direction in degrees.
virtual double getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
double getAverageSpeed () const
Returns the vehicle's estimated average speed on the segment assuming no further delays.
double getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
SUMOTime getBlockTime () const
Returns the time at which the vehicle was blocked.
double getBlockTimeSeconds () const
Returns the time at which the vehicle was blocked on the current segment.
double getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
double getConservativeSpeed (SUMOTime &earliestArrival) const
Returns the vehicle's estimated speed taking into account delays.
double getCurrentLinkPenaltySeconds () const
Returns the delay that is accrued due to option –meso-tls-penalty or –meso-minor-penalty.
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
SUMOTime getDepartDelay () const
Returns the depart delay.
double getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
std::string getDeviceParameter (const std::string &deviceName, const std::string &key) const
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
SUMOTime getEventTime () const
Returns the (planned) time at which the vehicle leaves his current cell.
double getEventTimeSeconds () const
Returns the earliest leave time for the current segment.
const std::string & getID () const
Returns the name of the vehicle.
double getImpatience () const
Returns this vehicles impatience.
MSLane * getLane () const
Returns the lane the vehicle is on.
SUMOTime getLastEntryTime () const
Returns the time the vehicle entered the current segment.
double getLastEntryTimeSeconds () const
Returns the entry time for the current segment.
virtual double getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
double getLength () const
Returns the vehicle's length.
double getMaxSpeed () const
Returns the maximum speed.
MSParkingArea * getNextParkingArea ()
get the current parking area stop
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
Position getPosition (const double offset=0) const
Return current position (x/y, cartesian)
double getPositionOnLane () const
Get the vehicle's position along the lane.
double getPreviousSpeed () const
Returns the vehicle's previous speed.
int getQueIndex () const
Returns the index of the que the vehicle is in.
virtual const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
const MSRoute & getRoute () const
Returns the current route.
MESegment * getSegment () const
Returns the current segment the vehicle is on.
MSVehicleType & getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
double getSlope () const
Returns the slope of the road at vehicle's position.
double getSpeed () const
Returns the vehicle's estimated speed assuming no delays.
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
SUMOTime getStoptime (const MESegment *const seg) const
Returns how long to stop at the given segment.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
double getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
SUMOTime getWaitingTime () const
Returns the duration for which the vehicle was blocked.
double getWidth () const
Returns the vehicle's width.
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasDevice (const std::string &deviceName) const
check whether the vehicle is equiped with a device of the given type
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
virtual bool isFrontOnLane (const MSLane *) const
Returns the information whether the front of the vehhicle is on the given lane.
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isParking () const
Returns whether the vehicle is parking.
virtual bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
virtual bool isSelected () const
whether this vehicle is selected in the GUI
bool isStopped () const
Returns whether the vehicle is at a stop.
bool isStoppedInRange (double pos) const
return whether the given position is within range of the current stop
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool mayProceed () const
Returns whether the vehicle is allowed to pass the next junction.
MEVehicle (SUMOVehicleParameter *pars, const MSRoute *route, MSVehicleType *type, const double speedFactor)
Constructor.
bool moveRoutePointer ()
Update when the vehicle enters a new edge in the move step.
void onDepart ()
Called when the vehicle is inserted into the network.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceParkingArea (MSParkingArea *, std::string &)
replace the current parking area stop with a new stop with merge duration
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0, bool addStops=true, bool removeStops=true)
Replaces the current route by the given one.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false, bool removeStops=true)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
virtual void setArrivalPos (double arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setBlockTime (const SUMOTime t)
Sets the time at which the vehicle was blocked.
void setChosenSpeedFactor (const double factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setDeviceParameter (const std::string &deviceName, const std::string &key, const std::string &value)
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
void setEventTime (SUMOTime t, bool hasDelay=true)
Sets the (planned) time at which the vehicle leaves his current cell.
void setLastEntryTime (SUMOTime t)
Sets the entry time for the current segment.
virtual void setSegment (MESegment *s, int idx=0)
Sets the current segment the vehicle is at together with its que.
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
void updateDetectorForWriting (MSMoveReminder *rem, SUMOTime currentTime, SUMOTime exitTime)
Updates a single vehicle detector if present.
void updateDetectors (SUMOTime currentTime, const bool isLeave, const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_JUNCTION)
Updates all vehicle detectors.
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
Protected Member Functions
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
Protected Attributes
int myArrivalLane
The destination lane where the vehicle stops.
double myArrivalPos
The position on the destination lane where the vehicle stops.
SUMOTime myBlockTime
The time at which the vehicle was blocked on its current segment.
double myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
double myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
SUMOTime myEventTime
The (planned) time of leaving the segment (cell)
SUMOTime myLastEntryTime
The time the vehicle entered its current segment.
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This vehicle's parameter.
int myQueIndex
Index of the que the vehicle is in (important for multiqueue extension)
const MSRoute * myRoute
This vehicle's route.
MESegment * mySegment
The segment the vehicle is at.
std::map< const MESegment *const, SUMOTime > myStops
where to stop
MSVehicleType * myType
This vehicle's type.
Static Protected Attributes
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Move reminder structures
MoveReminderCont myMoveReminders
Currently relevant move reminders.
typedef std::vector< std::pair< MSMoveReminder *, double > > MoveReminderCont
Definition of a move reminder container.
Detailed Description
A vehicle from the mesoscopic point of view.
Definition at line 51 of file MEVehicle.h.
Member Typedef Documentation
ComparatorIdLess
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 79 of file SUMOVehicle.h.
MoveReminderCont
typedef std::vector< std::pair<MSMoveReminder*, double> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 468 of file MSBaseVehicle.h.
Constructor & Destructor Documentation
MEVehicle()
MEVehicle::MEVehicle (SUMOVehicleParameter * pars, const MSRoute * route, MSVehicleType * type, const double speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 53 of file MEVehicle.cpp.
References DEPART_SPEED_GIVEN, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSVehicleType::getID(), MSVehicleType::getMaxSpeed(), MSVehicleType::getVehicleClass(), and SUMOVehicleParameter::id.
Member Function Documentation
activateReminders()
void MSBaseVehicle::activateReminders (const MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual inherited
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
[in] enteredLane The lane, which is entered (if applicable)
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented in MSVehicle.
Definition at line 376 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices(), MESegment::receive(), and MELoop::teleportVehicle().
addContainer()
void MSBaseVehicle::addContainer (MSTransportable * container) virtual inherited
Adds a container to this vehicle.
The default implementation does nothing since containers are not supported by default
Parameters
[in] container The container to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 316 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getID(), and MSTransportable::getID().
Referenced by MSBaseVehicle::getDevices().
addPerson()
void MSBaseVehicle::addPerson (MSTransportable * person) virtual inherited
Adds a person to this vehicle.
The default implementation does nothing since persons are not supported by default
Parameters
[in] person The person to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 311 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getID(), and MSTransportable::getID().
Referenced by MSBaseVehicle::getDevices().
addReminder()
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 349 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MESegment::addReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSBaseVehicle::getDevices(), and MSVehicle::processNextStop().
addStop()
bool MEVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0, bool collision = false, MSRouteIterator * searchStart = 0) virtual
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 223 of file MEVehicle.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MELoop::getSegmentForEdge(), MSGlobals::gMesoNet, SUMOVehicleParameter::Stop::lane, and myStops.
Referenced by getLane().
addStops()
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 473 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), SUMOVehicleParameter::depart, MSRoute::getStops(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::stops, and WRITE_WARNING.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), getBlockTimeSeconds(), MSVehicle::replaceRoute(), and MSBaseVehicle::setChosenSpeedFactor().
calculateArrivalParams()
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 398 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MSEdge::isTazConnector(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::isSelected(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::replaceRoute(), replaceRoute(), and MSBaseVehicle::reroute().
createDevice()
void MSBaseVehicle::createDevice (const std::string & deviceName) inherited
create device of the given type
Definition at line 508 of file MSBaseVehicle.cpp.
References MSDevice_Routing::buildVehicleDevices(), MSBaseVehicle::getDevice(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::hasDevice(), MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, MSMoveReminder::NOTIFICATION_DEPARTED, and MSDevice_Routing::notifyEnter().
Referenced by libsumo::Vehicle::setParameter().
estimateLeaveSpeed()
double MEVehicle::estimateLeaveSpeed (const MSLink * link) const
Returns the vehicle's estimated speed after driving accross the link.
See also
MSVehicle.cpp::estimateLeaveSpeed
Definition at line 125 of file MEVehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), and MIN2().
Referenced by getLane(), and MESegment::isOpen().
getAcceleration()
double MSBaseVehicle::getAcceleration () const virtual inherited
Returns the vehicle's acceleration.
This default implementation returns always 0.
Returns
The acceleration
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 280 of file MSBaseVehicle.cpp.
Referenced by MSBaseVehicle::getCurrentRouteEdge().
getAccumulatedWaitingTime()
SUMOTime MEVehicle::getAccumulatedWaitingTime () const inline virtual
Returns the duration for which the vehicle was blocked.
Implements SUMOVehicle.
Definition at line 281 of file MEVehicle.h.
References getWaitingTime().
getAngle()
double MEVehicle::getAngle () const virtual
Returns the vehicle's direction in degrees.
Returns
The vehicle's current angle
Implements SUMOVehicle.
Definition at line 88 of file MEVehicle.cpp.
References MSBaseVehicle::getEdge(), MSEdge::getLanes(), getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::rotationAtOffset().
Referenced by GUIMEVehicle::getAngle().
getArrivalPos()
virtual double MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 269 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
getAverageSpeed()
double MEVehicle::getAverageSpeed () const
Returns the vehicle's estimated average speed on the segment assuming no further delays.
Returns
The vehicle's estimated average speed
Note
This is only an upper bound. The speed will be lower if the preceeding vehicle is delayed
Definition at line 119 of file MEVehicle.cpp.
References MESegment::getLength(), myEventTime, myLastEntryTime, mySegment, and STEPS2TIME.
Referenced by getLane(), and getSpeed().
getBackPositionOnLane()
double MEVehicle::getBackPositionOnLane (const MSLane * lane) const virtual
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Implements SUMOVehicle.
Definition at line 74 of file MEVehicle.cpp.
References MSVehicleType::getLength(), getPositionOnLane(), and MSBaseVehicle::getVehicleType().
getBlockTime()
SUMOTime MEVehicle::getBlockTime () const inline
Returns the time at which the vehicle was blocked.
Returns
The blocking time
Definition at line 270 of file MEVehicle.h.
References myBlockTime.
Referenced by MELoop::checkCar(), and getBlockTimeSeconds().
getBlockTimeSeconds()
double MEVehicle::getBlockTimeSeconds () const inline
Returns the time at which the vehicle was blocked on the current segment.
Definition at line 308 of file MEVehicle.h.
References MSBaseVehicle::addStops(), getBlockTime(), getCurrentLinkPenaltySeconds(), loadState(), mayProceed(), MSMoveReminder::NOTIFICATION_JUNCTION, replaceRoute(), saveState(), STEPS2TIME, updateDetectorForWriting(), and updateDetectors().
Referenced by GUIMEVehicle::getParameterWindow().
getChosenSpeedFactor()
double MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 377 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), and libsumo::Vehicle::getSpeedFactor().
getConservativeSpeed()
double MEVehicle::getConservativeSpeed (SUMOTime & earliestArrival) const
Returns the vehicle's estimated speed taking into account delays.
Returns
The vehicle's estimated speed
Parameters
[in,out] earliestArrival A lower bound on leaveTime, modified to contain new lower bound on leave Time
Note
This is only an upper bound. The speed may be even lower if there are further delays downstream
Definition at line 134 of file MEVehicle.cpp.
References DELTA_T, MESegment::getLength(), MAX2(), myEventTime, myLastEntryTime, mySegment, and STEPS2TIME.
Referenced by getLane().
getCurrentLinkPenaltySeconds()
double MEVehicle::getCurrentLinkPenaltySeconds () const
Returns the delay that is accrued due to option –meso-tls-penalty or –meso-minor-penalty.
Definition at line 278 of file MEVehicle.cpp.
References MESegment::getLinkPenalty(), mySegment, and STEPS2TIME.
Referenced by getBlockTimeSeconds(), and GUIMEVehicle::getParameterWindow().
getCurrentRouteEdge()
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 192 of file MSBaseVehicle.h.
References MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
Referenced by MSDevice_SSM::findSurroundingVehicles(), libsumo::Vehicle::getDistance(), and libsumo::Vehicle::moveToXY().
getDepartDelay()
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 253 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIMEVehicle::getParameterWindow(), and GUIVehicle::getParameterWindow().
getDepartPos()
double MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 261 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by libsumo::Vehicle::getDistance().
getDeparture()
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 248 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay(), and MSVehicle::Influencer::postProcessRemoteControl().
getDevice()
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 447 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), GUIBaseVehicle::drawOnPos(), MSVehicle::resumeFromStopping(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
getDeviceParameter()
std::string MSBaseVehicle::getDeviceParameter (const std::string & deviceName, const std::string & key) const inherited
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 527 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by libsumo::Vehicle::getParameter().
getDevices()
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 302 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
getEdge()
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 149 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::enterLaneAtLaneChange(), METriggeredCalibrator::execute(), getAngle(), libsumo::Vehicle::getDrivingDistance2D(), MSVehicle::getLatOffset(), GUIMEVehicle::getParameterWindow(), getPosition(), getSlope(), MSBaseVehicle::getVClass(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MELoop::teleportVehicle().
getEventTime()
SUMOTime MEVehicle::getEventTime () const inline
Returns the (planned) time at which the vehicle leaves his current cell.
Returns
The time the vehicle thinks he leaves his cell at
Definition at line 211 of file MEVehicle.h.
References myEventTime.
Referenced by MELoop::addLeaderCar(), MELoop::checkCar(), getEventTimeSeconds(), MESegment::isOpen(), MESegment::receive(), MELoop::removeLeaderCar(), MESegment::send(), MELoop::setApproaching(), MESegment::setSpeedForQueue(), MELoop::teleportVehicle(), and updateDetectors().
getEventTimeSeconds()
double MEVehicle::getEventTimeSeconds () const inline
Returns the earliest leave time for the current segment.
Definition at line 298 of file MEVehicle.h.
References getEventTime(), and STEPS2TIME.
Referenced by GUIMEVehicle::getParameterWindow().
getID()
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 121 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChangerSublane::abortLCManeuver(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), MSBaseVehicle::addContainer(), MSPModel_Striping::addCrossingVehs(), MSLCM_SL2015::addLCSpeedAdvice(), MSBaseVehicle::addPerson(), MSVehicle::addTraciStopAtStoppingPlace(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), libsumo::Vehicle::changeTarget(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSVehicle::computeAngle(), MSLCM_SL2015::computeSpeedLat(), MSDevice_SSM::computeSSMs(), MSLaneChanger::continueChange(), MSLaneChangerSublane::continueChangeSublane(), MSLCM_SL2015::decideDirection(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSDevice_SSM::Encounter::Encounter(), MSCalibrator::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLaneChanger::findCandidate(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSAbstractLaneChangeModel::getShadowLane(), MSBaseVehicle::getSingularType(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSVehicle::ignoreRed(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::lateralDistanceToLane(), MSVehicle::leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSVehicle::onRemovalFromNet(), MSLaneChangerSublane::outputLCStarted(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLCM_SL2015::prepareStep(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::removePassedDriveItems(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), libsumo::Vehicle::resume(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), MSCalibrator::scheduleRemoval(), GUIVehicle::selectBlockingFoes(), MSVehicle::setAngle(), MSAbstractLaneChangeModel::setManeuverDist(), MSLane::setManeuverReservation(), MSLCM_SL2015::setOwnState(), MSLane::setPartialOccupation(), libsumo::Helper::setRemoteControlled(), libsumo::Vehicle::setRoute(), libsumo::Vehicle::setRouteID(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSVehicle::updateBestLanes(), MSVehicle::updateDriveItems(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicle::updateState(), MSAbstractLaneChangeModel::updateTargetLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), and MSXMLRawOut::writeVehicle().
getImpatience()
double MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 440 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToImpatience, MAX2(), and MIN2().
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), GUIVehicle::getParameterWindow(), MSLCM_LC2013::informFollower(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::processLinkAproaches(), and GUIVehicle::selectBlockingFoes().
getLane()
MSLane* MEVehicle::getLane () const inline virtual
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 90 of file MEVehicle.h.
References addStop(), estimateLeaveSpeed(), getAverageSpeed(), getConservativeSpeed(), getPosition(), getSpeed(), getStopEdges(), getStoptime(), hasArrived(), isOnRoad(), isParking(), isStopped(), isStoppedInRange(), isStoppedTriggered(), and moveRoutePointer().
getLastEntryTime()
SUMOTime MEVehicle::getLastEntryTime () const inline
Returns the time the vehicle entered the current segment.
Returns
The entry time
Definition at line 253 of file MEVehicle.h.
References myLastEntryTime.
Referenced by getLastEntryTimeSeconds(), MESegment::newArrival(), updateDetectorForWriting(), and updateDetectors().
getLastEntryTimeSeconds()
double MEVehicle::getLastEntryTimeSeconds () const inline
Returns the entry time for the current segment.
Definition at line 303 of file MEVehicle.h.
References getLastEntryTime(), and STEPS2TIME.
Referenced by GUIMEVehicle::getParameterWindow().
getLateralPositionOnLane()
virtual double MSBaseVehicle::getLateralPositionOnLane () const inline virtual inherited
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 175 of file MSBaseVehicle.h.
getLength()
double MSBaseVehicle::getLength () const inline inherited
Returns the vehicle's length.
Returns
vehicle's length
Definition at line 361 of file MSBaseVehicle.h.
References MSVehicleType::getLength(), and MSBaseVehicle::myType.
Referenced by MSVehicle::addStop(), MSDevice_SSM::checkConflictEntryAndExit(), MSDevice_SSM::classifyEncounter(), MSDevice_SSM::determineConflictPoint(), MSDevice_SSM::determineTTCandDRAC(), MSVehicle::enterLaneAtInsertion(), MSDevice_SSM::findSurroundingVehicles(), MSLink::getLeaderInfo(), MSDevice_SSM::getUpstreamVehicles(), MSVehicle::updateFurtherLanes(), MSDevice_SSM::updatePassedEncounter(), and MSVehicle::validatePosition().
getMaxSpeed()
double MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosRemote(), and MSVehicle::Influencer::implicitSpeedRemote().
getNextParkingArea()
MSParkingArea* MEVehicle::getNextParkingArea () inline virtual
get the current parking area stop
Implements SUMOVehicle.
Definition at line 192 of file MEVehicle.h.
getNumberReroutes()
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 291 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), and MSBaseVehicle::myNumberReroutes.
Referenced by GUIBaseVehicle::drawGLAdditional(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), and MSBaseVehicle::replaceRouteEdges().
getParameter()
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 127 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getDepartSpeed(), libsumo::Vehicle::getLine(), libsumo::Vehicle::getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), libsumo::Vehicle::getVia(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setColor(), GUIBaseVehicle::setFunctionalColor(), libsumo::Vehicle::setLine(), libsumo::Vehicle::setParameter(), and METriggeredCalibrator::tryEmit().
getPosition()
Position MEVehicle::getPosition (const double offset = 0) const virtual
Return current position (x/y, cartesian)
If the vehicle's myLane is 0, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See also
myLane
Implements SUMOVehicle.
Definition at line 102 of file MEVehicle.cpp.
References MSLane::geometryPositionAtOffset(), MSBaseVehicle::getEdge(), MSEdge::getLanes(), and getPositionOnLane().
Referenced by getLane(), and GUIMEVehicle::getPosition().
getPositionOnLane()
double MEVehicle::getPositionOnLane () const virtual
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 80 of file MEVehicle.cpp.
References MESegment::getIndex(), MESegment::getLength(), and mySegment.
Referenced by getAngle(), getBackPositionOnLane(), GUIMEVehicle::getParameterWindow(), getPosition(), getSlope(), and hasArrived().
getPreviousSpeed()
double MSBaseVehicle::getPreviousSpeed () const virtual inherited
Returns the vehicle's previous speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 64 of file MSBaseVehicle.cpp.
getQueIndex()
int MEVehicle::getQueIndex () const inline
Returns the index of the que the vehicle is in.
Returns
The que index
Definition at line 237 of file MEVehicle.h.
References myQueIndex.
Referenced by MESegment::getLink(), MESegment::removeCar(), saveState(), and MESegment::send().
getRerouteOrigin()
virtual const MSEdge* MSBaseVehicle::getRerouteOrigin () const inline virtual inherited
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge
Returns
The rerouting start point
Reimplemented in MSVehicle.
Definition at line 184 of file MSBaseVehicle.h.
References MSBaseVehicle::myCurrEdge.
Referenced by MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
getRoute()
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 107 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), libsumo::Vehicle::getDistance(), libsumo::Vehicle::getDrivingDistance(), libsumo::Vehicle::getDrivingDistance2D(), libsumo::Vehicle::getEdges(), libsumo::Vehicle::getRouteID(), MSLane::isInsertionSuccess(), libsumo::Vehicle::moveToXY(), MSVehicle::Influencer::postProcessRemoteControl(), and GUIBaseVehicle::setFunctionalColor().
getSegment()
MESegment* MEVehicle::getSegment () const inline
Returns the current segment the vehicle is on.
Returns
The segment the vehicle is on
Definition at line 229 of file MEVehicle.h.
References mySegment.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), GUIMEVehicle::getColorValue(), GUIMEVehicle::getParameterWindow(), isOnRoad(), MESegment::loadState(), MELoop::setApproaching(), and MELoop::teleportVehicle().
getSingularType()
MSVehicleType & MSBaseVehicle::getSingularType () inherited
Replaces the current vehicle type with a new one used by this vehicle only.
If the currently used vehicle type is already marked as being used by this vehicle only, no new type is created.
Returns
The new modifiable vehicle type
See also
MSBaseVehicle::myType
Definition at line 559 of file MSBaseVehicle.cpp.
References MSVehicleType::buildSingularType(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSVehicleType::isVehicleSpecific(), MSBaseVehicle::myType, OutputDevice::openTag(), MSBaseVehicle::replaceVehicleType(), STEPS2TIME, SUMO_ATTR_ID, SUMO_ATTR_TIME, toString(), and OutputDevice::writeAttr().
Referenced by TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setActionStepLength(), MSBaseVehicle::setChosenSpeedFactor(), libsumo::Vehicle::setMaxSpeed(), and libsumo::Vehicle::setShapeClass().
getSlope()
double MEVehicle::getSlope () const virtual
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 95 of file MEVehicle.cpp.
References MSBaseVehicle::getEdge(), MSEdge::getLanes(), getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::slopeDegreeAtOffset().
getSpeed()
double MEVehicle::getSpeed () const virtual
Returns the vehicle's estimated speed assuming no delays.
Returns
The vehicle's estimated speed
Note
This is only an upper bound. The speed will be lower if the preceeding vehicle is delayed
Implements SUMOVehicle.
Definition at line 109 of file MEVehicle.cpp.
References getAverageSpeed(), and getWaitingTime().
Referenced by estimateLeaveSpeed(), GUIMEVehicle::getColorValue(), getLane(), GUIMEVehicle::getParameterWindow(), MESegment::isOpen(), MESegment::newArrival(), MESegment::receive(), and MELoop::setApproaching().
getStopEdges()
const ConstMSEdgeVector MEVehicle::getStopEdges () const virtual
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 262 of file MEVehicle.cpp.
References myStops.
Referenced by getLane().
getStoptime()
SUMOTime MEVehicle::getStoptime (const MESegment *const seg) const
Returns how long to stop at the given segment.
Parameters
[in] seg The segment in question
Returns
stop time for the segment
Definition at line 253 of file MEVehicle.cpp.
References myStops.
Referenced by getLane(), and MESegment::receive().
getVClass()
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), and SUMOVTypeParameter::vehicleClass.
Referenced by GUIVehicle::drawRouteHelper(), MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
getVehicleType()
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 115 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeaders(), MSPModel_Striping::addCrossingVehs(), MSVehicle::addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MSLCM_SL2015::computeSpeedLat(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSDevice_SSM::estimateConflictTimes(), estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSLane::executeMovements(), MSLane::freeInsertion(), getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), MSVehicle::getLateralOverlap(), MSLane::getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), GUIVehicle::getLeftSideOnEdge(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), MSVehicle::getTimeGapOnLane(), MESegment::getTimeHeadway(), libsumo::Vehicle::getTypeID(), libsumo::Vehicle::getVehicleType(), GUIBaseVehicle::getVType(), MSLCM_SL2015::getWidth(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MESegment::hasSpaceFor(), MSVehicle::ignoreRed(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::keepClear(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), MSCFModel_Krauss::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSVehicle::overlap(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MESegment::receive(), MSLaneChanger::ChangeElem::registerHop(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), GUIVehicle::selectBlockingFoes(), MSVehicleType::setActionStepLength(), MSAbstractLaneChangeModel::setFollowerGaps(), GUIBaseVehicle::setFunctionalColor(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSVehicle::setTentativeLaneAndPosition(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
getWaitingSeconds()
double MEVehicle::getWaitingSeconds () const inline
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 292 of file MEVehicle.h.
References getWaitingTime(), and STEPS2TIME.
Referenced by GUIMEVehicle::getColorValue(), and GUIMEVehicle::getParameterWindow().
getWaitingTime()
SUMOTime MEVehicle::getWaitingTime () const inline virtual
Returns the duration for which the vehicle was blocked.
Implements SUMOVehicle.
Definition at line 276 of file MEVehicle.h.
References MAX2(), myBlockTime, and myEventTime.
Referenced by MELoop::checkCar(), getAccumulatedWaitingTime(), getSpeed(), getWaitingSeconds(), MESegment::isOpen(), and MELoop::setApproaching().
getWidth()
double MSBaseVehicle::getWidth () const inline inherited
Returns the vehicle's width.
Returns
vehicle's width
Definition at line 369 of file MSBaseVehicle.h.
References MSVehicleType::getWidth(), and MSBaseVehicle::myType.
Referenced by MSDevice_SSM::classifyEncounter(), MSAbstractLaneChangeModel::determineTargetLane(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), MSVehicle::getLateralOverlap(), MSVehicle::lateralDistanceToLane(), MSVehicle::planMoveInternal(), MSLaneChangerSublane::startChangeSublane(), and MSDevice_SSM::updatePassedEncounter().
hasArrived()
bool MEVehicle::hasArrived () const virtual
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 159 of file MEVehicle.cpp.
References MSRoute::end(), getPositionOnLane(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, myEventTime, MSBaseVehicle::myRoute, mySegment, POSITION_EPS, and SUMOTime_MIN.
Referenced by getLane(), moveRoutePointer(), and MESegment::receive().
hasDeparted()
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 300 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by MSVehicle::addStop(), MSBaseVehicle::createDevice(), MSLane::forceVehicleInsertion(), libsumo::Vehicle::getRouteIndex(), loadState(), MSVehicle::loadState(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::saveState(), and MSBaseVehicle::setArrivalPos().
hasDevice()
bool MSBaseVehicle::hasDevice (const std::string & deviceName) const inherited
check whether the vehicle is equiped with a device of the given type
Definition at line 497 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), and libsumo::Vehicle::getParameter().
hasValidRoute()
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 321 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), libsumo::Vehicle::isRouteValid(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::replaceRouteEdges(), and libsumo::Vehicle::setRouteID().
isFrontOnLane()
virtual bool MSBaseVehicle::isFrontOnLane (const MSLane *) const inline virtual inherited
Returns the information whether the front of the vehhicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 167 of file MSBaseVehicle.h.
isOnRoad()
bool MEVehicle::isOnRoad () const virtual
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 168 of file MEVehicle.cpp.
References getSegment().
Referenced by getLane().
isParking()
bool MEVehicle::isParking () const virtual
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 174 of file MEVehicle.cpp.
Referenced by getLane(), and GUIMEVehicle::getStopInfo().
isRemoteControlled()
virtual bool MSBaseVehicle::isRemoteControlled () const inline virtual inherited
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 160 of file MSBaseVehicle.h.
isSelected()
virtual bool MSBaseVehicle::isSelected () const inline virtual inherited
whether this vehicle is selected in the GUI
Implements SUMOVehicle.
Reimplemented in GUIVehicle.
Definition at line 430 of file MSBaseVehicle.h.
References MSBaseVehicle::calculateArrivalParams(), and MSBaseVehicle::getStopEdges().
isStopped()
bool MEVehicle::isStopped () const virtual
Returns whether the vehicle is at a stop.
Returns
Whether it has stopped
Implements SUMOVehicle.
Definition at line 234 of file MEVehicle.cpp.
References mySegment, and myStops.
Referenced by MELoop::checkCar(), getLane(), GUIMEVehicle::getStopInfo(), and isStoppedInRange().
isStoppedInRange()
bool MEVehicle::isStoppedInRange (double pos) const virtual
return whether the given position is within range of the current stop
Implements SUMOVehicle.
Definition at line 246 of file MEVehicle.cpp.
References isStopped(), and UNUSED_PARAMETER.
Referenced by getLane().
isStoppedTriggered()
bool MEVehicle::isStoppedTriggered () const virtual
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 240 of file MEVehicle.cpp.
Referenced by getLane().
loadState()
void MEVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 369 of file MEVehicle.cpp.
References MELoop::addLeaderCar(), MESegment::getIndex(), MESegment::getNextSegment(), MELoop::getSegmentForEdge(), SUMOSAXAttributes::getString(), MSGlobals::gMesoNet, SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), myBlockTime, MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, myEventTime, myLastEntryTime, setSegment(), SUMO_ATTR_POSITION, SUMO_ATTR_STATE, SUMOTime_MAX, and SUMOTime_MIN.
Referenced by getBlockTimeSeconds().
mayProceed()
bool MEVehicle::mayProceed () const
Returns whether the vehicle is allowed to pass the next junction.
Returns
true iff the vehicle may drive over the next junction
Definition at line 272 of file MEVehicle.cpp.
References MESegment::isOpen(), and mySegment.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), and getBlockTimeSeconds().
moveRoutePointer()
bool MEVehicle::moveRoutePointer ()
Update when the vehicle enters a new edge in the move step.
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 141 of file MEVehicle.cpp.
References MSRoute::end(), hasArrived(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, and SUMOVehicleParameter::via.
Referenced by METriggeredCalibrator::execute(), getLane(), MESegment::receive(), and MELoop::teleportVehicle().
onDepart()
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 292 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), and MESegment::receive().
removeReminder()
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 360 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
replaceParkingArea()
bool MEVehicle::replaceParkingArea (MSParkingArea * , std::string &) inline virtual
replace the current parking area stop with a new stop with merge duration
Implements SUMOVehicle.
Definition at line 186 of file MEVehicle.h.
replaceRoute()
bool MEVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0, bool addStops = true, bool removeStops = true) virtual
Replaces the current route by the given one.
Implements SUMOVehicle.
Definition at line 180 of file MEVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSRoute::getEdges(), MSNet::getInstance(), MESegment::getLink(), MSNet::informVehicleStateListener(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, mySegment, MSRoute::release(), MSLink::removeApproaching(), MELoop::setApproaching(), UNUSED_PARAMETER, and MSNet::VEHICLE_STATE_NEWROUTE.
Referenced by getBlockTimeSeconds().
replaceRouteEdges()
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false, bool removeStops = true) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
[in] removeStops Whether stops should be removed if they do not fit onto the new route
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 227 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), toString(), and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), MSBaseVehicle::reroute(), and libsumo::Vehicle::setRoute().
replaceVehicleType()
void MSBaseVehicle::replaceVehicleType (MSVehicleType * type) inherited
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSBaseVehicle::myType
Definition at line 550 of file MSBaseVehicle.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleType::isVehicleSpecific(), MSBaseVehicle::myType, and MSVehicleControl::removeVType().
Referenced by MSBaseVehicle::getSingularType(), MSBaseVehicle::setChosenSpeedFactor(), and libsumo::Vehicle::setType().
reroute()
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 155 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), MSBaseVehicle::calculateArrivalParams(), SUMOAbstractRouter< E, V >::compute(), MSInsertionControl::descheduleDeparture(), MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, MSGlobals::gCheckRoutes, Named::getID(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSEdge::isTazConnector(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, SUMOVehicleParameter::via, and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), MSBaseVehicle::getCurrentRouteEdge(), libsumo::Vehicle::rerouteEffort(), and libsumo::Vehicle::rerouteTraveltime().
saveState()
void MEVehicle::saveState (OutputDevice & out) virtual
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 340 of file MEVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MESegment::getEdge(), MESegment::getIndex(), getQueIndex(), myBlockTime, MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MSBaseVehicle::myDevices, myEventTime, myLastEntryTime, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, mySegment, myStops, OutputDevice::openTag(), MSBaseVehicle::saveState(), STEPS2TIME, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_LANE, SUMO_ATTR_STATE, SUMO_TAG_STOP, toString(), OutputDevice::writeAttr(), and Parameterised::writeParams().
Referenced by getBlockTimeSeconds().
setArrivalPos()
virtual void MSBaseVehicle::setArrivalPos (double arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 275 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
setBlockTime()
void MEVehicle::setBlockTime (const SUMOTime t) inline
Sets the time at which the vehicle was blocked.
Parameters
[in] t The blocking time
Definition at line 261 of file MEVehicle.h.
References myBlockTime, and myLastEntryTime.
Referenced by MELoop::checkCar(), and MESegment::receive().
setChosenSpeedFactor()
void MSBaseVehicle::setChosenSpeedFactor (const double factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 384 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::getDevice(), MSBaseVehicle::getSingularType(), MSBaseVehicle::myChosenSpeedFactor, MSBaseVehicle::replaceVehicleType(), and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
setDeviceParameter()
void MSBaseVehicle::setDeviceParameter (const std::string & deviceName, const std::string & key, const std::string & value) inherited
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 538 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by libsumo::Vehicle::setParameter().
setEventTime()
void MEVehicle::setEventTime (SUMOTime t, bool hasDelay = true) inline
Sets the (planned) time at which the vehicle leaves his current cell.
Parameters
[in] t The leaving time
Definition at line 199 of file MEVehicle.h.
References MESegment::getEdge(), MSEdge::markDelayed(), myEventTime, myLastEntryTime, and mySegment.
Referenced by MELoop::checkCar(), METriggeredCalibrator::execute(), MESegment::receive(), MESegment::send(), MESegment::setSpeedForQueue(), and MELoop::teleportVehicle().
setLastEntryTime()
void MEVehicle::setLastEntryTime (SUMOTime t) inline
Sets the entry time for the current segment.
Parameters
[in] t The entry time
Definition at line 245 of file MEVehicle.h.
References myLastEntryTime.
Referenced by MESegment::receive().
setSegment()
virtual void MEVehicle::setSegment (MESegment * s, int idx = 0) inline virtual
Sets the current segment the vehicle is at together with its que.
Parameters
[in] s The current segment
[in] q The current que
Definition at line 220 of file MEVehicle.h.
References myQueIndex, and mySegment.
Referenced by MELoop::changeSegment(), METriggeredCalibrator::execute(), loadState(), MESegment::receive(), and MELoop::teleportVehicle().
succEdge()
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), libsumo::Vehicle::moveTo(), MELoop::nextSegment(), and MESegment::receive().
updateDetectorForWriting()
void MEVehicle::updateDetectorForWriting (MSMoveReminder * rem, SUMOTime currentTime, SUMOTime exitTime)
Updates a single vehicle detector if present.
Definition at line 288 of file MEVehicle.cpp.
References MESegment::getIndex(), getLastEntryTime(), MESegment::getLength(), MSBaseVehicle::myMoveReminders, mySegment, and MSMoveReminder::updateDetector().
Referenced by getBlockTimeSeconds().
updateDetectors()
void MEVehicle::updateDetectors (SUMOTime currentTime, const bool isLeave, const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_JUNCTION)
Updates all vehicle detectors.
Definition at line 306 of file MEVehicle.cpp.
References getEventTime(), MESegment::getIndex(), getLastEntryTime(), MESegment::getLength(), MSBaseVehicle::myMoveReminders, mySegment, and MSMoveReminder::NOTIFICATION_SEGMENT.
Referenced by getBlockTimeSeconds(), MESegment::setSpeedForQueue(), and MESegment::updateDetectorsOnLeave().
Field Documentation
myArrivalLane
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 487 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and MSVehicle::updateBestLanes().
myArrivalPos
double MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 484 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), hasArrived(), MSVehicle::hasArrived(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and MSVehicle::updateBestLanes().
myBlockTime
SUMOTime MEVehicle::myBlockTime protected
The time at which the vehicle was blocked on its current segment.
Definition at line 359 of file MEVehicle.h.
Referenced by getBlockTime(), getWaitingTime(), loadState(), saveState(), and setBlockTime().
myChosenSpeedFactor
double MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 457 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
myCurrEdge
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 454 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::enterLaneAtMove(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), MSVehicle::getRerouteOrigin(), MSVehicle::getRoutePosition(), hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MSVehicle::leaveLane(), loadState(), MSVehicle::loadState(), moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLaneAdvances(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::resetRoutePosition(), saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), and MSVehicle::willPass().
myDepartPos
double MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 481 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), and MSVehicle::saveState().
myDeparture
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 478 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), loadState(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), saveState(), and MSVehicle::saveState().
myDevices
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 475 of file MSBaseVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::createDevice(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDeviceParameter(), MSBaseVehicle::getDevices(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::hasDevice(), MSBaseVehicle::MSBaseVehicle(), saveState(), MSVehicle::saveState(), MSBaseVehicle::setDeviceParameter(), and MSBaseVehicle::~MSBaseVehicle().
myEventTime
SUMOTime MEVehicle::myEventTime protected
The (planned) time of leaving the segment (cell)
Definition at line 353 of file MEVehicle.h.
Referenced by getAverageSpeed(), getConservativeSpeed(), getEventTime(), getWaitingTime(), hasArrived(), loadState(), saveState(), and setEventTime().
myLastEntryTime
SUMOTime MEVehicle::myLastEntryTime protected
The time the vehicle entered its current segment.
Definition at line 356 of file MEVehicle.h.
Referenced by getAverageSpeed(), getConservativeSpeed(), getLastEntryTime(), loadState(), saveState(), setBlockTime(), setEventTime(), and setLastEntryTime().
myMoveReminders
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Currently relevant move reminders.
Definition at line 471 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), MSVehicle::leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), updateDetectorForWriting(), updateDetectors(), and MSVehicle::workOnMoveReminders().
myNumberReroutes
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 490 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), MSVehicle::replaceRoute(), and replaceRoute().
myParameter
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This vehicle's parameter.
Definition at line 445 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSVehicle::addTraciStop(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::createDevice(), MSVehicle::enterLaneAtMove(), MSVehicle::getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSVehicle::getPersonNumber(), moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::replaceParkingArea(), MSBaseVehicle::reroute(), saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSVehicle::updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
myQueIndex
int MEVehicle::myQueIndex protected
Index of the que the vehicle is in (important for multiqueue extension)
Definition at line 350 of file MEVehicle.h.
Referenced by getQueIndex(), and setSegment().
myRoute
const MSRoute* MSBaseVehicle::myRoute protected inherited
This vehicle's route.
Definition at line 448 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), GUIVehicle::drawRouteHelper(), MSVehicle::getDistanceToPosition(), MSVehicle::getRerouteOrigin(), MSBaseVehicle::getRoute(), MSVehicle::getRoutePosition(), hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::replaceRoute(), replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSVehicle::resetRoutePosition(), saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and MSBaseVehicle::~MSBaseVehicle().
mySegment
MESegment* MEVehicle::mySegment protected
The segment the vehicle is at.
Definition at line 347 of file MEVehicle.h.
Referenced by getAverageSpeed(), getConservativeSpeed(), getCurrentLinkPenaltySeconds(), getPositionOnLane(), getSegment(), hasArrived(), isStopped(), mayProceed(), replaceRoute(), saveState(), setEventTime(), setSegment(), updateDetectorForWriting(), and updateDetectors().
myStops
std::map<const MESegment* const, SUMOTime> MEVehicle::myStops protected
where to stop
Definition at line 362 of file MEVehicle.h.
Referenced by addStop(), getStopEdges(), getStoptime(), isStopped(), and saveState().
myType
MSVehicleType* MSBaseVehicle::myType protected inherited
This vehicle's type.
Definition at line 451 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getActionStepLength(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getCarFollowModel(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSBaseVehicle::getLength(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getMaxSpeedOnLane(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getSingularType(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MSBaseVehicle::hasValidRoute(), MSVehicle::processNextStop(), MSBaseVehicle::replaceVehicleType(), MSVehicle::updateBestLanes(), and MSVehicle::~MSVehicle().
NOT_YET_DEPARTED
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 495 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::hasDeparted(), and MSVehicle::Influencer::postProcessRemoteControl().
The documentation for this class was generated from the following files:
MEVehicle.h
MEVehicle.cpp