SUMO - Simulation of Urban MObility: GNEApplicationWindow Class Reference
GNEApplicationWindow Class Reference
The main window of the Netedit.
#include <GNEApplicationWindow.h>
Data Structures
class GNEShapeHandler
FOX-declaration.
Public Member Functions
void addChild (FXMDIChild *child, bool updateOnSimStep=true)
Adds a further child window to the list.
void addChild (FXMainWindow *child, bool updateOnSimStep=true)
virtual void create ()
Creates the main window (required by FOX)
void dependentBuild ()
build dependent
virtual void detach ()
detaches the tool/menu bar
void enableSaveAdditionalsMenu ()
enable save additionals
void enableSaveShapesMenu ()
enable save shapes
GUISUMOAbstractView * getActiveView () const
get the active view or 0
FXFont * getBoldFont ()
FXGLCanvas * getBuildGLCanvas () const
get build OpenGL Canvas
FXLabel & getCartesianLabel ()
SUMOTime getCurrentSimTime () const
get current simulation time (pure virtual but we don't need it)
FXCursor * getDefaultCursor ()
get default cursor
virtual double getDelay () const
Returns the delay (should be overwritten by subclasses if applicable)
FXLabel & getGeoLabel ()
FXGLVisual * getGLVisual () const
double getTrackerInterval () const
get current tracker interval (pure virtual but we don't need it)
GNEUndoList * getUndoList ()
get pointer to undoList
FXMDIChild * getViewByID (const std::string &id) const
std::vector< std::string > getViewIDs () const
GNEApplicationWindow (FXApp *a, const std::string &configPattern)
Constructor.
bool isGaming () const
return whether the gui is in gaming mode
bool listInternal () const
return whether to list internal structures
bool listParking () const
return whether to list parking vehicles
bool listTeleporting () const
return whether to list teleporting vehicles
void loadOptionOnStartup ()
load net on startup
void removeChild (FXMDIChild *child)
removes the given child window from the list
void removeChild (FXMainWindow *child)
virtual void sendBlockingEvent (GUIEvent *event)
Sends an event from the application thread to the GUI and waits until it is handled.
void setAdditionalsFile (const std::string &additionalsFile)
set additionals file
virtual void setDelay (double)
Sets the delay of the parent application.
void setShapesFile (const std::string &shapesFile)
set shapes file
void setStatusBarText (const std::string &statusBarText)
set text of the statusBar
void updateChildren ()
void updateControls ()
update control contents after undo/redo or recompute
virtual ~GNEApplicationWindow ()
Destructor.
Inter-thread event handling
called when an event occured
virtual void eventOccured ()
void handleEvent_NetworkLoaded (GUIEvent *e)
handle event of type Network loaded
void handleEvent_Message (GUIEvent *e)
hanlde event of type message
FOX-callbacks
called when the command/FXCall new network is executed
long onCmdNewNetwork (FXObject *, FXSelector, void *)
long onCmdOpenConfiguration (FXObject *, FXSelector, void *)
called when the command/FXCall open configuration is executed
long onCmdOpenNetwork (FXObject *, FXSelector, void *)
called when the command/FXCall open network is executed
long onCmdOpenForeign (FXObject *, FXSelector, void *)
called when the command/FXCall open foreign is executed
long onCmdOpenShapes (FXObject *, FXSelector, void *)
called when the command/FXCall open shapes is executed
long onCmdOpenAdditionals (FXObject *, FXSelector, void *)
called when the command/FXCall open additionals is executed
long onCmdReload (FXObject *, FXSelector, void *)
called when the command/FXCall reload is executed
long onCmdOpenRecent (FXObject *, FXSelector, void *)
called when the command/FXCall open recent is executed
long onCmdClose (FXObject *, FXSelector, void *)
called when the command/FXCall close is executed
long onCmdLocate (FXObject *, FXSelector, void *)
called when the command/FXCall locate is executed
long onCmdSaveNetwork (FXObject *, FXSelector, void *)
called when the command/FXCall save network is executed
long onCmdSaveAdditionals (FXObject *, FXSelector, void *)
called when the command/FXCall save additionals is executed
long onCmdSaveAdditionalsAs (FXObject *, FXSelector, void *)
called when the command/FXCall save additionals as is executed
long onUpdSaveNetwork (FXObject *, FXSelector, void *)
called when the update/FXCall save network is executed
long onCmdSaveAsNetwork (FXObject *, FXSelector, void *)
called when the command/FXCall save network as is executed
long onUpdNeedsNetwork (FXObject *, FXSelector, void *)
called when the upadte/FXCall needs network is executed
long onUpdReload (FXObject *, FXSelector, void *)
called when the update/FXCall reload is executed
long onCmdSaveAsPlainXML (FXObject *, FXSelector, void *)
called when the command/FXCall save as plain xml is executed
long onCmdSaveJoined (FXObject *, FXSelector, void *)
called when the command/FXCall save joined is executed
long onCmdSaveShapes (FXObject *, FXSelector, void *)
called when the command/FXCall save shapes is executed
long onCmdSaveShapesAs (FXObject *, FXSelector, void *)
called when the command/FXCall save shapes as is executed
long onKeyPress (FXObject *o, FXSelector sel, void *data)
called when a key is pressed
long onKeyRelease (FXObject *o, FXSelector sel, void *data)
called when a key is released
long onCmdQuit (FXObject *, FXSelector, void *)
Called by FOX if the application shall be closed.
long onCmdEditChosen (FXObject *, FXSelector, void *)
called when the command/FXCall edit chosen is executed
long onCmdAppSettings (FXObject *, FXSelector, void *)
Opens the application settings menu.
long onCmdGaming (FXObject *, FXSelector, void *)
called when the command/FXCall toogle gaming mode is executed
long onCmdAbout (FXObject *, FXSelector, void *)
called when the command/FXCall show about dialog is executed
long onCmdNewView (FXObject *, FXSelector, void *)
called when the command/FXCall new view is executed
long onUpdOpen (FXObject *, FXSelector, void *)
called when the command/FXCall on update open executed
long onCmdClearMsgWindow (FXObject *, FXSelector, void *)
called when the command/FXCall clear message windows is executed
long onLoadThreadEvent (FXObject *, FXSelector, void *)
called when the command/FXCall load thread is executed
long onClipboardRequest (FXObject *sender, FXSelector sel, void *ptr)
called when the command/FXCall clipboard request is executed
long onCmdSetMode (FXObject *sender, FXSelector sel, void *ptr)
called if the user hits an edit-mode hotkey
long onCmdAbort (FXObject *sender, FXSelector sel, void *ptr)
called if the user hits esc
long onCmdDel (FXObject *sender, FXSelector sel, void *ptr)
called if the user hits del
long onCmdEnter (FXObject *sender, FXSelector sel, void *ptr)
called if the user hits enter
long onCmdFocusFrame (FXObject *sender, FXSelector sel, void *ptr)
called if the user hits f
long onCmdEditViewport (FXObject *, FXSelector, void *)
called if the user press key v to open zoom editor
long onCmdHelp (FXObject *sender, FXSelector sel, void *ptr)
called if the user selects help->Documentation
long onCmdComputeJunctions (FXObject *, FXSelector, void *)
called if the user selects Processing->compute junctions
long onCmdComputeJunctionsVolatile (FXObject *, FXSelector, void *)
called if the user selects Processing->compute junctions with volatile options
long onCmdCleanJunctions (FXObject *, FXSelector, void *)
called if the user selects Processing->clean junctions
long onCmdJoinJunctions (FXObject *, FXSelector, void *)
called if the user selects Processing->join junctions
long onCmdCleanInvalidCrossings (FXObject *, FXSelector, void *)
called if the user selects Processing->clear invalid crossings
long onCmdOptions (FXObject *, FXSelector, void *)
called if the user selects Processing->Configure Options
Static Public Member Functions
static GUIMainWindow * getInstance ()
Protected Member Functions
virtual void fillMenuBar ()
Builds the menu bar.
GNEApplicationWindow ()
FOX needs this for static members.
void setWindowSizeAndPos ()
perform initial window positioning and sizing according to user options / previous call
Protected Attributes
bool hadDependentBuild
check if had dependent build
std::string myAdditionalsFile
filename for load/save additionals
bool myAmGaming
information whether the gui is currently in gaming mode
bool myAmLoading
information whether the gui is currently loading and the load-options shall be greyed out
FXFont * myBoldFont
Font used for popup-menu titles.
FXDockSite * myBottomDock
FXLabel * myCartesianCoordinate
Labels for the current cartesian and geo-coordinate.
FXHorizontalFrame * myCartesianFrame
std::string myConfigPattern
Input file pattern.
FXMenuPane * myEditMenu
MFXEventQue< GUIEvent * > myEvents
List of got requests.
FXMenuPane * myFileMenu
the submenus
FXLabel * myGeoCoordinate
FXHorizontalFrame * myGeoFrame
FXGLVisual * myGLVisual
The gl-visual used.
FXMenuPane * myHelpMenu
FXDockSite * myLeftDock
bool myListInternal
information whether the locator should list internal structures
bool myListParking
information whether the locator should list parking vehicles
bool myListTeleporting
information whether the locator should list teleporting vehicles
GNELoadThread * myLoadThread
the thread that loads the network
FXEX::FXThreadEvent myLoadThreadEvent
io-event with the load-thread
FXMenuPane * myLocatorMenu
FXSplitter * myMainSplitter
The splitter that divides the main window into view and the log window.
FXMDIClient * myMDIClient
The multi view panel.
FXMDIMenu * myMDIMenu
The menu used for the MDI-windows.
FXMenuBar * myMenuBar
The application menu bar.
FXToolBarShell * myMenuBarDrag
GUIMessageWindow * myMessageWindow
A window to display messages, warnings and error in.
std::string myName
the name of the simulation
GNENet * myNet
we are responsible for the net
FXMenuPane * myProcessingMenu
FXRecentFiles myRecentConfigs
List of recent config files.
FXRecentFiles myRecentNets
List of recent nets.
FXDockSite * myRightDock
std::string myShapesFile
filename for load/save shapes
FXStatusBar * myStatusbar
The status bar.
std::vector< FXMDIChild * > mySubWindows
const FXString myTitlePrefix
the prefix for the window title
FXToolBar * myToolBar1
The application tool bar.
FXToolBar * myToolBar2
FXToolBar * myToolBar3
FXToolBar * myToolBar4
FXToolBar * myToolBar5
FXToolBarShell * myToolBarDrag1
for some menu detaching fun
FXToolBarShell * myToolBarDrag2
FXToolBarShell * myToolBarDrag3
FXToolBarShell * myToolBarDrag4
FXToolBarShell * myToolBarDrag5
FXDockSite * myTopDock
MFXMutex myTrackerLock
A lock to make the removal and addition of trackers secure.
std::vector< FXMainWindow * > myTrackerWindows
GNEUndoList * myUndoList
the one and only undo list
int myViewNumber
The current view number.
FXMenuPane * myWindowsMenu
Static Protected Attributes
static GUIMainWindow * myInstance = 0
the singleton window instance
Private Member Functions
void closeAllWindows ()
this method closes all windows and deletes the current simulation */
bool continueWithUnsavedAdditionalChanges ()
warns about unsaved changes in additionals and gives the user the option to abort
bool continueWithUnsavedChanges ()
warns about unsaved changes and gives the user the option to abort
bool continueWithUnsavedShapeChanges ()
warns about unsaved changes in shapes and gives the user the option to abort
GNEViewNet * getView ()
convenience method
void loadConfigOrNet (const std::string file, bool isNet, bool isReload=false, bool useStartupOptions=false, bool newNet=false)
starts to load a netimport configuration or a network */
GUISUMOAbstractView * openNewView ()
opens a new simulation display
Private Attributes
FXMenuCommand * mySaveAdditionalsMenuCommand
FXMenuCommand for enable or disable save additionals.
FXMenuCommand * mySaveShapesMenuCommand
FXMenuCommand for enable or disable save shapes.
Detailed Description
The main window of the Netedit.
Contains the file opening support and a canvas to display the network in.
Beside views on the simulation, shown within a MDI-window, the main window may also have some further views (children) assigned which are stored within a separate list.
Definition at line 69 of file GNEApplicationWindow.h.
Constructor & Destructor Documentation
GNEApplicationWindow() [1/2]
GNEApplicationWindow::GNEApplicationWindow (FXApp * a, const std::string & configPattern)
Constructor.
Parameters
[in] a The FOX application
[in] configPattern The pattern used for loading configurations
Definition at line 205 of file GNEApplicationWindow.cpp.
References GUIIconSubSys::initIcons(), and GUITextureSubSys::initTextures().
~GNEApplicationWindow()
GNEApplicationWindow::~GNEApplicationWindow () virtual
Destructor.
Definition at line 323 of file GNEApplicationWindow.cpp.
References GUIIconSubSys::close(), GUITextureSubSys::close(), closeAllWindows(), MFXEventQue< T >::empty(), myEditMenu, myEvents, myFileMenu, GUIMainWindow::myGLVisual, myHelpMenu, myLoadThread, myLocatorMenu, myProcessingMenu, myUndoList, myWindowsMenu, MFXEventQue< T >::pop(), and MFXEventQue< T >::top().
GNEApplicationWindow() [2/2]
GNEApplicationWindow::GNEApplicationWindow () inline protected
FOX needs this for static members.
Definition at line 314 of file GNEApplicationWindow.h.
References fillMenuBar().
Member Function Documentation
addChild() [1/2]
void GUIMainWindow::addChild (FXMDIChild * child, bool updateOnSimStep = true) inherited
Adds a further child window to the list.
Definition at line 99 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by GUIParameterTableWindow::closeBuilding(), and GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow().
addChild() [2/2]
void GUIMainWindow::addChild (FXMainWindow * child, bool updateOnSimStep = true) inherited
Definition at line 114 of file GUIMainWindow.cpp.
References MFXMutex::lock(), GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, and MFXMutex::unlock().
closeAllWindows()
void GNEApplicationWindow::closeAllWindows () private
this method closes all windows and deletes the current simulation */
Definition at line 1052 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUISelectedStorage::clear(), gSelected, MFXMutex::lock(), GUIMainWindow::myCartesianCoordinate, GUIMainWindow::myGeoCoordinate, myMessageWindow, myNet, GUIMainWindow::mySubWindows, myTitlePrefix, GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, myUndoList, GNEUndoList::p_clear(), GLHelper::resetFont(), GeoConvHelper::resetLoaded(), GUITextureSubSys::resetTextures(), MFXMutex::unlock(), and GUIMessageWindow::unregisterMsgHandlers().
Referenced by loadConfigOrNet(), onCmdClose(), and ~GNEApplicationWindow().
continueWithUnsavedAdditionalChanges()
bool GNEApplicationWindow::continueWithUnsavedAdditionalChanges () private
warns about unsaved changes in additionals and gives the user the option to abort
Definition at line 1794 of file GNEApplicationWindow.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), getView(), mySaveAdditionalsMenuCommand, onCmdSaveAdditionals(), and WRITE_WARNING.
Referenced by continueWithUnsavedChanges().
continueWithUnsavedChanges()
bool GNEApplicationWindow::continueWithUnsavedChanges () private
warns about unsaved changes and gives the user the option to abort
Definition at line 1730 of file GNEApplicationWindow.cpp.
References continueWithUnsavedAdditionalChanges(), continueWithUnsavedShapeChanges(), OptionsCont::getBool(), OptionsCont::getOptions(), getView(), myUndoList, onCmdSaveNetwork(), GNEUndoList::p_clear(), and WRITE_WARNING.
Referenced by loadConfigOrNet(), onCmdClose(), onCmdNewNetwork(), onCmdOpenForeign(), and onCmdQuit().
continueWithUnsavedShapeChanges()
bool GNEApplicationWindow::continueWithUnsavedShapeChanges () private
warns about unsaved changes in shapes and gives the user the option to abort
Definition at line 1843 of file GNEApplicationWindow.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), getView(), mySaveShapesMenuCommand, onCmdSaveShapes(), and WRITE_WARNING.
Referenced by continueWithUnsavedChanges().
create()
void GNEApplicationWindow::create () virtual
Creates the main window (required by FOX)
Definition at line 298 of file GNEApplicationWindow.cpp.
References gCurrentFolder, OptionsCont::getOptions(), GUIMainWindow::myCartesianFrame, myEditMenu, myFileMenu, GUIMainWindow::myGeoFrame, myHelpMenu, myMenuBarDrag, myWindowsMenu, and GUIMainWindow::setWindowSizeAndPos().
dependentBuild()
void GNEApplicationWindow::dependentBuild ()
build dependent
Definition at line 226 of file GNEApplicationWindow.cpp.
References fillMenuBar(), GUIIconSubSys::getIcon(), GUIDesignBar, GUIDesignHorizontalFrameStatusBar, GUIDesignSplitter, GUIDesignSplitterMDI, GUIDesignStatusBar, GUIDesignToolBarGrip, GUIDesignToolBarShell3, hadDependentBuild, ICON_NETEDIT, ID_LOADTHREAD_EVENT, MID_EDITVIEWPORT, MID_GNE_HOTKEY_DEL, MID_GNE_HOTKEY_ENTER, MID_GNE_HOTKEY_ESC, MID_GNE_HOTKEY_FOCUSFRAME, MID_GNE_SETMODE_ADDITIONAL, MID_GNE_SETMODE_CONNECT, MID_GNE_SETMODE_CREATE_EDGE, MID_GNE_SETMODE_CROSSING, MID_GNE_SETMODE_DELETE, MID_GNE_SETMODE_INSPECT, MID_GNE_SETMODE_MOVE, MID_GNE_SETMODE_POLYGON, MID_GNE_SETMODE_SELECT, MID_GNE_SETMODE_TLS, MID_WINDOW, GUIMainWindow::myCartesianCoordinate, GUIMainWindow::myCartesianFrame, myEvents, GUIMainWindow::myGeoCoordinate, GUIMainWindow::myGeoFrame, myLoadThread, myLoadThreadEvent, myMainSplitter, GUIMainWindow::myMDIClient, myMDIMenu, myMenuBar, myMenuBarDrag, myMessageWindow, GUIMainWindow::myStatusbar, myTitlePrefix, GUIMainWindow::myTopDock, FXEX::FXBaseObject::setSelector(), FXEX::FXBaseObject::setTarget(), and WRITE_ERROR.
Referenced by main().
detach()
void GNEApplicationWindow::detach () virtual
detaches the tool/menu bar
Definition at line 352 of file GNEApplicationWindow.cpp.
References myMenuBarDrag.
enableSaveAdditionalsMenu()
void GNEApplicationWindow::enableSaveAdditionalsMenu ()
enable save additionals
Definition at line 1126 of file GNEApplicationWindow.cpp.
References mySaveAdditionalsMenuCommand.
Referenced by GNENet::requiereSaveAdditionals().
enableSaveShapesMenu()
void GNEApplicationWindow::enableSaveShapesMenu ()
enable save shapes
Definition at line 1132 of file GNEApplicationWindow.cpp.
References mySaveShapesMenuCommand.
Referenced by GNENet::requiereSaveShapes().
eventOccured()
void GNEApplicationWindow::eventOccured () virtual
Implements MFXInterThreadEventClient.
Definition at line 882 of file GNEApplicationWindow.cpp.
References MFXEventQue< T >::empty(), EVENT_ERROR_OCCURED, EVENT_MESSAGE_OCCURED, EVENT_SIMULATION_LOADED, EVENT_WARNING_OCCURED, GUIEvent::getOwnType(), handleEvent_Message(), handleEvent_NetworkLoaded(), myEvents, MFXEventQue< T >::pop(), and MFXEventQue< T >::top().
Referenced by onLoadThreadEvent().
fillMenuBar()
void GNEApplicationWindow::fillMenuBar () protected virtual
Builds the menu bar.
Definition at line 359 of file GNEApplicationWindow.cpp.
References GUIIconSubSys::getIcon(), ICON_CLEANJUNCTIONS, ICON_CLOSE, ICON_COMPUTEJUNCTIONS, ICON_JOINJUNCTIONS, ICON_LOCATEADD, ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATEPOI, ICON_LOCATEPOLY, ICON_LOCATETLS, ICON_MODEADDITIONAL, ICON_MODECONNECTION, ICON_MODECREATEEDGE, ICON_MODECROSSING, ICON_MODEDELETE, ICON_MODEINSPECT, ICON_MODEMOVE, ICON_MODEPOLYGON, ICON_MODESELECT, ICON_MODETLS, ICON_OPEN_ADDITIONALS, ICON_OPEN_CONFIG, ICON_OPEN_NET, ICON_OPEN_SHAPES, ICON_OPTIONS, ICON_REDO, ICON_RELOAD, ICON_SAVE, ICON_UNDO, MID_ABOUT, MID_CLEARMESSAGEWINDOW, MID_CLOSE, MID_GNE_PROCESSING_CLEANINVALIDCROSSINGS, MID_GNE_PROCESSING_CLEANJUNCTIONS, MID_GNE_PROCESSING_COMPUTEJUNCTIONS, MID_GNE_PROCESSING_COMPUTEJUNCTIONS_VOLATILE, MID_GNE_PROCESSING_JOINJUNCTIONS, MID_GNE_PROCESSING_OPTIONS, MID_GNE_SETMODE_ADDITIONAL, MID_GNE_SETMODE_CONNECT, MID_GNE_SETMODE_CREATE_EDGE, MID_GNE_SETMODE_CROSSING, MID_GNE_SETMODE_DELETE, MID_GNE_SETMODE_INSPECT, MID_GNE_SETMODE_MOVE, MID_GNE_SETMODE_POLYGON, MID_GNE_SETMODE_SELECT, MID_GNE_SETMODE_TLS, MID_GNE_TOOLBARFILE_NEWNETWORK, MID_GNE_TOOLBARFILE_OPENFOREIGN, MID_GNE_TOOLBARFILE_SAVEADDITIONALS, MID_GNE_TOOLBARFILE_SAVEADDITIONALS_AS, MID_GNE_TOOLBARFILE_SAVEJOINED, MID_GNE_TOOLBARFILE_SAVENETWORK, MID_GNE_TOOLBARFILE_SAVENETWORK_AS, MID_GNE_TOOLBARFILE_SAVEPLAINXML, MID_GNE_TOOLBARFILE_SAVESHAPES, MID_GNE_TOOLBARFILE_SAVESHAPES_AS, MID_HELP, MID_LOCATEADD, MID_LOCATEEDGE, MID_LOCATEJUNCTION, MID_LOCATEPOI, MID_LOCATEPOLY, MID_LOCATETLS, MID_OPEN_ADDITIONALS, MID_OPEN_CONFIG, MID_OPEN_NETWORK, MID_OPEN_SHAPES, MID_QUIT, MID_RECENTFILE, MID_RELOAD, myEditMenu, myFileMenu, myHelpMenu, myLocatorMenu, myMenuBar, myMessageWindow, myProcessingMenu, myRecentConfigs, myRecentNets, mySaveAdditionalsMenuCommand, mySaveShapesMenuCommand, GUIMainWindow::myStatusbar, myUndoList, and myWindowsMenu.
Referenced by dependentBuild(), and GNEApplicationWindow().
getActiveView()
GUISUMOAbstractView * GUIMainWindow::getActiveView () const inherited
get the active view or 0
Definition at line 198 of file GUIMainWindow.cpp.
References GUIGlChildWindow::getView(), and GUIMainWindow::myMDIClient.
Referenced by GUIVehicle::drawOutsideNetwork(), and GUIMainWindow::sendBlockingEvent().
getBoldFont()
FXFont * GUIMainWindow::getBoldFont () inherited
Definition at line 152 of file GUIMainWindow.cpp.
References GUIMainWindow::myBoldFont.
Referenced by GUIGlObject::buildPopupHeader(), GNEDeleteFrame::createPopUpMenu(), and GNEInspectorFrame::createPopUpMenu().
getBuildGLCanvas()
FXGLCanvas * GNEApplicationWindow::getBuildGLCanvas () const virtual
get build OpenGL Canvas
Implements GUIMainWindow.
Definition at line 1023 of file GNEApplicationWindow.cpp.
References GUIGlChildWindow::getBuildGLCanvas(), and GUIMainWindow::myMDIClient.
Referenced by openNewView().
getCartesianLabel()
FXLabel & GUIMainWindow::getCartesianLabel () inherited
Definition at line 177 of file GUIMainWindow.cpp.
References GUIMainWindow::myCartesianCoordinate.
Referenced by GUIMainWindow::setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
getCurrentSimTime()
SUMOTime GNEApplicationWindow::getCurrentSimTime () const virtual
get current simulation time (pure virtual but we don't need it)
Implements GUIMainWindow.
Definition at line 1034 of file GNEApplicationWindow.cpp.
getDefaultCursor()
FXCursor * GNEApplicationWindow::getDefaultCursor ()
get default cursor
Definition at line 1094 of file GNEApplicationWindow.cpp.
getDelay()
virtual double GUIMainWindow::getDelay () const inline virtual inherited
Returns the delay (should be overwritten by subclasses if applicable)
Returns
parsed delay in milliseconds
Reimplemented in GUIApplicationWindow.
Definition at line 110 of file GUIMainWindow.h.
Referenced by GUISUMOAbstractView::getDelay(), and GUIViewTraffic::saveFrame().
getGeoLabel()
FXLabel & GUIMainWindow::getGeoLabel () inherited
Definition at line 183 of file GUIMainWindow.cpp.
References GUIMainWindow::myGeoCoordinate.
Referenced by GUIMainWindow::setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
getGLVisual()
FXGLVisual * GUIMainWindow::getGLVisual () const inherited
Definition at line 171 of file GUIMainWindow.cpp.
References GUIMainWindow::myGLVisual.
Referenced by GUISUMOViewParent::init().
getInstance()
GUIMainWindow * GUIMainWindow::getInstance (void) static inherited
Definition at line 189 of file GUIMainWindow.cpp.
References GUIMainWindow::myInstance.
Referenced by GUIVehicle::drawOutsideNetwork(), TraCIServerAPI_GUI::getNamedView(), GUITexturesHelper::getTextureID(), GUIMainWindow::listTeleporting(), TraCIServerAPI_GUI::processGet(), and GUIMessageWindow::setCursorPos().
getTrackerInterval()
double GNEApplicationWindow::getTrackerInterval () const virtual
get current tracker interval (pure virtual but we don't need it)
Implements GUIMainWindow.
Definition at line 1040 of file GNEApplicationWindow.cpp.
getUndoList()
GNEUndoList * GNEApplicationWindow::getUndoList ()
get pointer to undoList
Definition at line 1046 of file GNEApplicationWindow.cpp.
References myUndoList.
getView()
GNEViewNet * GNEApplicationWindow::getView () private
convenience method
Definition at line 1720 of file GNEApplicationWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by continueWithUnsavedAdditionalChanges(), continueWithUnsavedChanges(), continueWithUnsavedShapeChanges(), handleEvent_NetworkLoaded(), onCmdAbort(), onCmdDel(), onCmdEditViewport(), onCmdEnter(), onCmdFocusFrame(), onCmdSetMode(), and updateControls().
getViewByID()
FXMDIChild * GUIMainWindow::getViewByID (const std::string & id) const inherited
Definition at line 141 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by TraCIServerAPI_GUI::getNamedView(), and GUIMessageWindow::setCursorPos().
getViewIDs()
std::vector< std::string > GUIMainWindow::getViewIDs () const inherited
Definition at line 131 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by TraCIServerAPI_GUI::processGet(), and GUIMessageWindow::setCursorPos().
handleEvent_Message()
void GNEApplicationWindow::handleEvent_Message (GUIEvent * e)
hanlde event of type message
Definition at line 978 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::appendMsg(), GUIEvent_Message::getMsg(), GUIEvent::getOwnType(), and myMessageWindow.
Referenced by eventOccured().
handleEvent_NetworkLoaded()
void GNEApplicationWindow::handleEvent_NetworkLoaded (GUIEvent * e)
handle event of type Network loaded
Definition at line 906 of file GNEApplicationWindow.cpp.
References GUISUMOAbstractView::addDecals(), GUISettingsHandler::addSettings(), GUISettingsHandler::applyViewport(), GUISettingsHandler::getDecals(), OptionsCont::getOptions(), OptionsCont::getString(), MFXUtils::getTitleText(), getView(), GNENet::getViewNet(), gSchemeStorage, MID_GNE_SETMODE_INSPECT, myAdditionalsFile, myAmLoading, GNEEvent_NetworkLoaded::myFile, myMessageWindow, GNEEvent_NetworkLoaded::myNet, myNet, GNEEvent_NetworkLoaded::mySettingsFile, myShapesFile, myTitlePrefix, myUndoList, myViewNumber, GNEEvent_NetworkLoaded::myViewportFromRegistry, openNewView(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GUIMessageWindow::registerMsgHandlers(), XMLSubSys::runParser(), Position::set(), GNEViewNet::setEditModeFromHotkey(), GUISettingsHandler::setSnapshots(), setStatusBarText(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), GUIMainWindow::setWindowSizeAndPos(), WRITE_ERROR, and WRITE_MESSAGE.
Referenced by eventOccured().
isGaming()
bool GUIMainWindow::isGaming () const inline inherited
return whether the gui is in gaming mode
Definition at line 86 of file GUIMainWindow.h.
References GUIMainWindow::myAmGaming.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded(), GUISUMOViewParent::init(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnRelease(), and GUIViewTraffic::setColorScheme().
listInternal()
bool GUIMainWindow::listInternal () const inline inherited
return whether to list internal structures
Definition at line 91 of file GUIMainWindow.h.
References GUIMainWindow::myListInternal.
Referenced by GUISUMOViewParent::onCmdLocate().
listParking()
bool GUIMainWindow::listParking () const inline inherited
return whether to list parking vehicles
Definition at line 96 of file GUIMainWindow.h.
References GUIMainWindow::myListParking.
Referenced by GUIApplicationWindow::fillMenuBar(), and GUISUMOViewParent::onCmdLocate().
listTeleporting()
bool GUIMainWindow::listTeleporting () const inline inherited
return whether to list teleporting vehicles
Definition at line 101 of file GUIMainWindow.h.
References GUIMainWindow::getInstance(), and GUIMainWindow::myListTeleporting.
Referenced by GUISUMOViewParent::onCmdLocate().
loadConfigOrNet()
void GNEApplicationWindow::loadConfigOrNet (const std::string file, bool isNet, bool isReload = false, bool useStartupOptions = false, bool newNet = false) private
starts to load a netimport configuration or a network */
Definition at line 985 of file GNEApplicationWindow.cpp.
References closeAllWindows(), continueWithUnsavedChanges(), gSchemeStorage, GNELoadThread::loadConfigOrNet(), myAmLoading, myLoadThread, GUICompleteSchemeStorage::saveViewport(), and setStatusBarText().
Referenced by loadOptionOnStartup(), onCmdNewNetwork(), onCmdOpenConfiguration(), onCmdOpenForeign(), onCmdOpenNetwork(), onCmdOpenRecent(), and onCmdReload().
loadOptionOnStartup()
void GNEApplicationWindow::loadOptionOnStartup ()
load net on startup
Definition at line 1100 of file GNEApplicationWindow.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), and loadConfigOrNet().
Referenced by main().
onClipboardRequest()
long GNEApplicationWindow::onClipboardRequest (FXObject * sender, FXSelector sel, void * ptr)
called when the command/FXCall clipboard request is executed
Definition at line 866 of file GNEApplicationWindow.cpp.
References GUIUserIO::clipped.
onCmdAbort()
long GNEApplicationWindow::onCmdAbort (FXObject * sender, FXSelector sel, void * ptr)
called if the user hits esc
Definition at line 1147 of file GNEApplicationWindow.cpp.
References GNEViewNet::abortOperation(), OptionsCont::getOptions(), getView(), and WRITE_WARNING.
onCmdAbout()
long GNEApplicationWindow::onCmdAbout (FXObject * , FXSelector , void *)
called when the command/FXCall show about dialog is executed
Definition at line 849 of file GNEApplicationWindow.cpp.
References GNEDialog_About::create(), OptionsCont::getOptions(), and WRITE_WARNING.
onCmdAppSettings()
long GNEApplicationWindow::onCmdAppSettings (FXObject * , FXSelector , void *)
Opens the application settings menu.
onCmdCleanInvalidCrossings()
long GNEApplicationWindow::onCmdCleanInvalidCrossings (FXObject * , FXSelector , void *)
called if the user selects Processing->clear invalid crossings
Definition at line 1400 of file GNEApplicationWindow.cpp.
References GNENet::cleanInvalidCrossings(), OptionsCont::getOptions(), myNet, myUndoList, and WRITE_WARNING.
onCmdCleanJunctions()
long GNEApplicationWindow::onCmdCleanJunctions (FXObject * , FXSelector , void *)
called if the user selects Processing->clean junctions
Definition at line 1378 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), myNet, myUndoList, GNENet::removeSolitaryJunctions(), and WRITE_WARNING.
onCmdClearMsgWindow()
long GNEApplicationWindow::onCmdClearMsgWindow (FXObject * , FXSelector , void *)
called when the command/FXCall clear message windows is executed
Definition at line 842 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::clear(), and myMessageWindow.
onCmdClose()
long GNEApplicationWindow::onCmdClose (FXObject * , FXSelector , void *)
called when the command/FXCall close is executed
Definition at line 812 of file GNEApplicationWindow.cpp.
References closeAllWindows(), continueWithUnsavedChanges(), mySaveAdditionalsMenuCommand, and mySaveShapesMenuCommand.
onCmdComputeJunctions()
long GNEApplicationWindow::onCmdComputeJunctions (FXObject * , FXSelector , void *)
called if the user selects Processing->compute junctions
Definition at line 1213 of file GNEApplicationWindow.cpp.
References GNENet::computeEverything(), OptionsCont::getOptions(), myNet, updateControls(), and WRITE_WARNING.
onCmdComputeJunctionsVolatile()
long GNEApplicationWindow::onCmdComputeJunctionsVolatile (FXObject * , FXSelector , void *)
called if the user selects Processing->compute junctions with volatile options
Definition at line 1225 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GNENet::computeEverything(), gCurrentFolder, OptionsCont::getBool(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), GNENet::getNumberOfAdditionals(), GNENet::getNumberOfShapes(), OptionsCont::getOptions(), GNENet::getViewNet(), ICON_EMPTY, myAdditionalsFile, myMessageWindow, myNet, myShapesFile, GNENet::saveAdditionals(), GNENet::saveShapes(), updateControls(), and WRITE_WARNING.
onCmdDel()
long GNEApplicationWindow::onCmdDel (FXObject * sender, FXSelector sel, void * ptr)
called if the user hits del
Definition at line 1162 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), getView(), GNEViewNet::hotkeyDel(), and WRITE_WARNING.
onCmdEditChosen()
long GNEApplicationWindow::onCmdEditChosen (FXObject * , FXSelector , void *)
called when the command/FXCall edit chosen is executed
Definition at line 625 of file GNEApplicationWindow.cpp.
References gSelected.
onCmdEditViewport()
long GNEApplicationWindow::onCmdEditViewport (FXObject * , FXSelector , void *)
called if the user press key v to open zoom editor
Definition at line 1197 of file GNEApplicationWindow.cpp.
References getView(), and GUISUMOAbstractView::showViewportEditor().
onCmdEnter()
long GNEApplicationWindow::onCmdEnter (FXObject * sender, FXSelector sel, void * ptr)
called if the user hits enter
Definition at line 1175 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), getView(), GNEViewNet::hotkeyEnter(), and WRITE_WARNING.
onCmdFocusFrame()
long GNEApplicationWindow::onCmdFocusFrame (FXObject * sender, FXSelector sel, void * ptr)
called if the user hits f
Definition at line 1188 of file GNEApplicationWindow.cpp.
References getView(), and GNEViewNet::hotkeyFocusFrame().
onCmdGaming()
long GNEApplicationWindow::onCmdGaming (FXObject * , FXSelector , void *)
called when the command/FXCall toogle gaming mode is executed
onCmdHelp()
long GNEApplicationWindow::onCmdHelp (FXObject * sender, FXSelector sel, void * ptr)
called if the user selects help->Documentation
Definition at line 1206 of file GNEApplicationWindow.cpp.
References FXLinkLabel::fxexecute().
onCmdJoinJunctions()
long GNEApplicationWindow::onCmdJoinJunctions (FXObject * , FXSelector , void *)
called if the user selects Processing->join junctions
Definition at line 1389 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), GNENet::joinSelectedJunctions(), myNet, myUndoList, and WRITE_WARNING.
onCmdLocate()
long GNEApplicationWindow::onCmdLocate (FXObject * , FXSelector sel, void *)
called when the command/FXCall locate is executed
Definition at line 824 of file GNEApplicationWindow.cpp.
References GUIMainWindow::myMDIClient, and GNEViewParent::onCmdLocate().
onCmdNewNetwork()
long GNEApplicationWindow::onCmdNewNetwork (FXObject * , FXSelector , void *)
Definition at line 635 of file GNEApplicationWindow.cpp.
References continueWithUnsavedChanges(), GNELoadThread::fillOptions(), OptionsCont::getOptions(), loadConfigOrNet(), and GNELoadThread::setDefaultOptions().
onCmdNewView()
long GNEApplicationWindow::onCmdNewView (FXObject * , FXSelector , void *)
called when the command/FXCall new view is executed
onCmdOpenAdditionals()
long GNEApplicationWindow::onCmdOpenAdditionals (FXObject * , FXSelector , void *)
called when the command/FXCall open additionals is executed
Definition at line 758 of file GNEApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), GNENet::getViewNet(), ICON_EMPTY, myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), XMLSubSys::runParser(), and WRITE_MESSAGE.
onCmdOpenConfiguration()
long GNEApplicationWindow::onCmdOpenConfiguration (FXObject * , FXSelector , void *)
called when the command/FXCall open configuration is executed
Definition at line 649 of file GNEApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, loadConfigOrNet(), myConfigPattern, and myRecentConfigs.
onCmdOpenForeign()
long GNEApplicationWindow::onCmdOpenForeign (FXObject * , FXSelector , void *)
called when the command/FXCall open foreign is executed
Definition at line 692 of file GNEApplicationWindow.cpp.
References NIFrame::checkOptions(), continueWithUnsavedChanges(), GNELoadThread::fillOptions(), gCurrentFolder, GUIIconSubSys::getIcon(), OptionsCont::getOptions(), ICON_EMPTY, loadConfigOrNet(), and OptionsCont::set().
onCmdOpenNetwork()
long GNEApplicationWindow::onCmdOpenNetwork (FXObject * , FXSelector , void *)
called when the command/FXCall open network is executed
Definition at line 669 of file GNEApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, loadConfigOrNet(), myRecentNets, mySaveAdditionalsMenuCommand, and mySaveShapesMenuCommand.
onCmdOpenRecent()
long GNEApplicationWindow::onCmdOpenRecent (FXObject * sender, FXSelector , void * fileData)
called when the command/FXCall open recent is executed
Definition at line 792 of file GNEApplicationWindow.cpp.
References loadConfigOrNet(), myAmLoading, myRecentNets, and GUIMainWindow::myStatusbar.
onCmdOpenShapes()
long GNEApplicationWindow::onCmdOpenShapes (FXObject * , FXSelector , void *)
called when the command/FXCall open shapes is executed
Definition at line 733 of file GNEApplicationWindow.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), XMLSubSys::runParser(), and WRITE_MESSAGE.
onCmdOptions()
long GNEApplicationWindow::onCmdOptions (FXObject * , FXSelector , void *)
called if the user selects Processing->Configure Options
Definition at line 1411 of file GNEApplicationWindow.cpp.
References NIFrame::checkOptions(), NWFrame::checkOptions(), NBFrame::checkOptions(), and SystemFrame::checkOptions().
onCmdQuit()
long GNEApplicationWindow::onCmdQuit (FXObject * , FXSelector , void *)
Called by FOX if the application shall be closed.
Note
Called either by FileMenu->Quit, the normal close-menu or SIGINT
Definition at line 606 of file GNEApplicationWindow.cpp.
References continueWithUnsavedChanges(), and gCurrentFolder.
onCmdReload()
long GNEApplicationWindow::onCmdReload (FXObject * , FXSelector , void *)
called when the command/FXCall reload is executed
Definition at line 804 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), and loadConfigOrNet().
onCmdSaveAdditionals()
long GNEApplicationWindow::onCmdSaveAdditionals (FXObject * , FXSelector , void *)
called when the command/FXCall save additionals is executed
Definition at line 1645 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUIMessageWindow::appendMsg(), EVENT_MESSAGE_OCCURED, gCurrentFolder, OptionsCont::getBool(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), ICON_EMPTY, myAdditionalsFile, myMessageWindow, myNet, mySaveAdditionalsMenuCommand, GNENet::saveAdditionals(), and WRITE_WARNING.
Referenced by continueWithUnsavedAdditionalChanges(), and onCmdSaveAdditionalsAs().
onCmdSaveAdditionalsAs()
long GNEApplicationWindow::onCmdSaveAdditionalsAs (FXObject * , FXSelector , void *)
called when the command/FXCall save additionals as is executed
Definition at line 1689 of file GNEApplicationWindow.cpp.
References gCurrentFolder, MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), ICON_EMPTY, myAdditionalsFile, and onCmdSaveAdditionals().
onCmdSaveAsNetwork()
long GNEApplicationWindow::onCmdSaveAsNetwork (FXObject * , FXSelector , void *)
called when the command/FXCall save network as is executed
Definition at line 1426 of file GNEApplicationWindow.cpp.
References gCurrentFolder, MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), MFXUtils::getTitleText(), ICON_EMPTY, myTitlePrefix, onCmdSaveNetwork(), OptionsCont::resetWritable(), and OptionsCont::set().
Referenced by onCmdSaveNetwork().
onCmdSaveAsPlainXML()
long GNEApplicationWindow::onCmdSaveAsPlainXML (FXObject * , FXSelector , void *)
called when the command/FXCall save as plain xml is executed
Definition at line 1444 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUIMessageWindow::appendMsg(), StringUtils::endsWith(), EVENT_MESSAGE_OCCURED, gCurrentFolder, OptionsCont::getBool(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), OptionsCont::getString(), ICON_EMPTY, OptionsCont::isSet(), myMessageWindow, myNet, myUndoList, OptionsCont::resetWritable(), GNENet::savePlain(), OptionsCont::set(), OptionsCont::unSet(), and WRITE_WARNING.
onCmdSaveJoined()
long GNEApplicationWindow::onCmdSaveJoined (FXObject * , FXSelector , void *)
called when the command/FXCall save joined is executed
Definition at line 1496 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUIMessageWindow::appendMsg(), EVENT_MESSAGE_OCCURED, gCurrentFolder, OptionsCont::getBool(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), OptionsCont::getString(), ICON_EMPTY, OptionsCont::isSet(), myMessageWindow, myNet, OptionsCont::resetWritable(), GNENet::saveJoined(), OptionsCont::set(), OptionsCont::unSet(), and WRITE_WARNING.
onCmdSaveNetwork()
long GNEApplicationWindow::onCmdSaveNetwork (FXObject * , FXSelector , void *)
called when the command/FXCall save network is executed
Definition at line 1613 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUIMessageWindow::appendMsg(), EVENT_MESSAGE_OCCURED, OptionsCont::getBool(), OptionsCont::getOptions(), OptionsCont::getString(), myMessageWindow, myNet, myUndoList, onCmdSaveAsNetwork(), GNENet::save(), and WRITE_WARNING.
Referenced by continueWithUnsavedChanges(), and onCmdSaveAsNetwork().
onCmdSaveShapes()
long GNEApplicationWindow::onCmdSaveShapes (FXObject * , FXSelector , void *)
called when the command/FXCall save shapes is executed
Definition at line 1539 of file GNEApplicationWindow.cpp.
References GUIMessageWindow::addSeparator(), GUIMessageWindow::appendMsg(), EVENT_MESSAGE_OCCURED, gCurrentFolder, OptionsCont::getBool(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), ICON_EMPTY, myMessageWindow, myNet, mySaveShapesMenuCommand, myShapesFile, GNENet::saveShapes(), and WRITE_WARNING.
Referenced by continueWithUnsavedShapeChanges(), and onCmdSaveShapesAs().
onCmdSaveShapesAs()
long GNEApplicationWindow::onCmdSaveShapesAs (FXObject * , FXSelector , void *)
called when the command/FXCall save shapes as is executed
Definition at line 1581 of file GNEApplicationWindow.cpp.
References gCurrentFolder, MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), ICON_EMPTY, myShapesFile, and onCmdSaveShapes().
onCmdSetMode()
long GNEApplicationWindow::onCmdSetMode (FXObject * sender, FXSelector sel, void * ptr)
called if the user hits an edit-mode hotkey
Definition at line 1138 of file GNEApplicationWindow.cpp.
References getView(), and GNEViewNet::setEditModeFromHotkey().
onKeyPress()
long GNEApplicationWindow::onKeyPress (FXObject * o, FXSelector sel, void * data)
called when a key is pressed
Definition at line 1900 of file GNEApplicationWindow.cpp.
References GUIMainWindow::myMDIClient, and GNEViewParent::onKeyPress().
onKeyRelease()
long GNEApplicationWindow::onKeyRelease (FXObject * o, FXSelector sel, void * data)
called when a key is released
Definition at line 1913 of file GNEApplicationWindow.cpp.
References GUIMainWindow::myMDIClient, and GNEViewParent::onKeyRelease().
onLoadThreadEvent()
long GNEApplicationWindow::onLoadThreadEvent (FXObject * , FXSelector , void *)
called when the command/FXCall load thread is executed
Definition at line 875 of file GNEApplicationWindow.cpp.
References eventOccured().
onUpdNeedsNetwork()
long GNEApplicationWindow::onUpdNeedsNetwork (FXObject * sender, FXSelector , void *)
called when the upadte/FXCall needs network is executed
Definition at line 1599 of file GNEApplicationWindow.cpp.
References myNet.
onUpdOpen()
long GNEApplicationWindow::onUpdOpen (FXObject * sender, FXSelector , void *)
called when the command/FXCall on update open executed
Definition at line 835 of file GNEApplicationWindow.cpp.
References myAmLoading.
onUpdReload()
long GNEApplicationWindow::onUpdReload (FXObject * sender, FXSelector , void *)
called when the update/FXCall reload is executed
Definition at line 1606 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), and myNet.
onUpdSaveNetwork()
long GNEApplicationWindow::onUpdSaveNetwork (FXObject * sender, FXSelector , void *)
called when the update/FXCall save network is executed
Definition at line 1707 of file GNEApplicationWindow.cpp.
References OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), and myNet.
openNewView()
GUISUMOAbstractView * GNEApplicationWindow::openNewView () private
opens a new simulation display
Definition at line 1006 of file GNEApplicationWindow.cpp.
References getBuildGLCanvas(), GUIGlChildWindow::getView(), GUIMainWindow::myMDIClient, myMDIMenu, myNet, myUndoList, myViewNumber, and toString().
Referenced by handleEvent_NetworkLoaded().
removeChild() [1/2]
void GUIMainWindow::removeChild (FXMDIChild * child) inherited
removes the given child window from the list
Definition at line 105 of file GUIMainWindow.cpp.
References GUIMainWindow::mySubWindows.
Referenced by GNEViewParent::~GNEViewParent(), GUIDialog_Breakpoints::~GUIDialog_Breakpoints(), GUIDialog_GLChosenEditor::~GUIDialog_GLChosenEditor(), GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser(), GUIParameterTableWindow::~GUIParameterTableWindow(), GUIParameterTracker::~GUIParameterTracker(), GUISUMOViewParent::~GUISUMOViewParent(), and GUITLLogicPhasesTrackerWindow::~GUITLLogicPhasesTrackerWindow().
removeChild() [2/2]
void GUIMainWindow::removeChild (FXMainWindow * child) inherited
Definition at line 122 of file GUIMainWindow.cpp.
References MFXMutex::lock(), GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, and MFXMutex::unlock().
sendBlockingEvent()
virtual void GUIMainWindow::sendBlockingEvent (GUIEvent * event) inline virtual inherited
Sends an event from the application thread to the GUI and waits until it is handled.
Parameters
event the event to send
Reimplemented in GUIApplicationWindow.
Definition at line 121 of file GUIMainWindow.h.
References GUIMainWindow::getActiveView(), and UNUSED_PARAMETER.
setAdditionalsFile()
void GNEApplicationWindow::setAdditionalsFile (const std::string & additionalsFile)
set additionals file
Definition at line 1114 of file GNEApplicationWindow.cpp.
References myAdditionalsFile.
setDelay()
virtual void GUIMainWindow::setDelay (double) inline virtual inherited
Sets the delay of the parent application.
Reimplemented in GUIApplicationWindow.
Definition at line 116 of file GUIMainWindow.h.
Referenced by GUISUMOAbstractView::setDelay().
setShapesFile()
void GNEApplicationWindow::setShapesFile (const std::string & shapesFile)
set shapes file
Definition at line 1120 of file GNEApplicationWindow.cpp.
References myShapesFile.
setStatusBarText()
void GNEApplicationWindow::setStatusBarText (const std::string & statusBarText) virtual
set text of the statusBar
Reimplemented from GUIMainWindow.
Definition at line 1107 of file GNEApplicationWindow.cpp.
References GUIMainWindow::myStatusbar.
Referenced by GNENet::computeEverything(), handleEvent_NetworkLoaded(), and loadConfigOrNet().
setWindowSizeAndPos()
void GUIMainWindow::setWindowSizeAndPos () protected inherited
perform initial window positioning and sizing according to user options / previous call
Definition at line 207 of file GUIMainWindow.cpp.
References TplCheck::_str2int(), TplConvert::_str2int(), OptionsCont::getOptions(), OptionsCont::getStringVector(), OptionsCont::isSet(), MAX2(), MIN2(), and WRITE_ERROR.
Referenced by GUIApplicationWindow::create(), create(), GUIMainWindow::GUIMainWindow(), handleEvent_NetworkLoaded(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
updateChildren()
void GUIMainWindow::updateChildren () inherited
Definition at line 158 of file GUIMainWindow.cpp.
References MFXMutex::lock(), MID_SIMSTEP, GUIMainWindow::myMDIClient, GUIMainWindow::myTrackerLock, GUIMainWindow::myTrackerWindows, and MFXMutex::unlock().
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdChangeOption(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption(), GUIDialog_GLChosenEditor::onCmdClear(), GUIDialog_GLChosenEditor::onCmdDeselect(), GUIApplicationWindow::onCmdEditChosen(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdUserDef(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdPreDef(), GUICalibrator::GUIManip_Calibrator::onUpdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdUserDef(), GUICalibrator::GUIManip_Calibrator::onUpdUserDef(), and GUITriggeredRerouter::GUIManip_TriggeredRerouter::onUpdUserDef().
updateControls()
void GNEApplicationWindow::updateControls ()
update control contents after undo/redo or recompute
Definition at line 1891 of file GNEApplicationWindow.cpp.
References getView(), and GNEViewNet::updateControls().
Referenced by onCmdComputeJunctions(), onCmdComputeJunctionsVolatile(), GNEUndoList::redo(), and GNEUndoList::undo().
Field Documentation
hadDependentBuild
bool GNEApplicationWindow::hadDependentBuild protected
check if had dependent build
Definition at line 375 of file GNEApplicationWindow.h.
Referenced by dependentBuild().
myAdditionalsFile
std::string GNEApplicationWindow::myAdditionalsFile protected
filename for load/save additionals
Definition at line 387 of file GNEApplicationWindow.h.
Referenced by handleEvent_NetworkLoaded(), onCmdComputeJunctionsVolatile(), onCmdSaveAdditionals(), onCmdSaveAdditionalsAs(), and setAdditionalsFile().
myAmGaming
bool GUIMainWindow::myAmGaming protected inherited
information whether the gui is currently in gaming mode
Definition at line 153 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), GUIMainWindow::isGaming(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), and GUIApplicationWindow::updateTimeLCD().
myAmLoading
bool GNEApplicationWindow::myAmLoading protected
information whether the gui is currently loading and the load-options shall be greyed out
Definition at line 329 of file GNEApplicationWindow.h.
Referenced by handleEvent_NetworkLoaded(), loadConfigOrNet(), onCmdOpenRecent(), and onUpdOpen().
myBoldFont
FXFont* GUIMainWindow::myBoldFont protected inherited
Font used for popup-menu titles.
Definition at line 135 of file GUIMainWindow.h.
Referenced by GUIMainWindow::getBoldFont(), GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
myBottomDock
FXDockSite * GUIMainWindow::myBottomDock protected inherited
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
myCartesianCoordinate
FXLabel* GUIMainWindow::myCartesianCoordinate protected inherited
Labels for the current cartesian and geo-coordinate.
Definition at line 144 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::closeAllWindows(), closeAllWindows(), GUIApplicationWindow::dependentBuild(), dependentBuild(), and GUIMainWindow::getCartesianLabel().
myCartesianFrame
FXHorizontalFrame* GUIMainWindow::myCartesianFrame protected inherited
Definition at line 145 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::create(), create(), GUIApplicationWindow::dependentBuild(), and dependentBuild().
myConfigPattern
std::string GNEApplicationWindow::myConfigPattern protected
Input file pattern.
Definition at line 372 of file GNEApplicationWindow.h.
Referenced by onCmdOpenConfiguration().
myEditMenu
FXMenuPane * GNEApplicationWindow::myEditMenu protected
Definition at line 332 of file GNEApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GNEApplicationWindow().
myEvents
MFXEventQue<GUIEvent*> GNEApplicationWindow::myEvents protected
List of got requests.
Definition at line 351 of file GNEApplicationWindow.h.
Referenced by dependentBuild(), eventOccured(), and ~GNEApplicationWindow().
myFileMenu
FXMenuPane* GNEApplicationWindow::myFileMenu protected
the submenus
Definition at line 332 of file GNEApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GNEApplicationWindow().
myGeoCoordinate
FXLabel * GUIMainWindow::myGeoCoordinate protected inherited
Definition at line 144 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::closeAllWindows(), closeAllWindows(), GUIApplicationWindow::dependentBuild(), dependentBuild(), and GUIMainWindow::getGeoLabel().
myGeoFrame
FXHorizontalFrame * GUIMainWindow::myGeoFrame protected inherited
Definition at line 145 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::create(), create(), GUIApplicationWindow::dependentBuild(), and dependentBuild().
myGLVisual
FXGLVisual* GUIMainWindow::myGLVisual protected inherited
The gl-visual used.
Definition at line 148 of file GUIMainWindow.h.
Referenced by GUIMainWindow::getGLVisual(), ~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
myHelpMenu
FXMenuPane * GNEApplicationWindow::myHelpMenu protected
Definition at line 332 of file GNEApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GNEApplicationWindow().
myInstance
GUIMainWindow * GUIMainWindow::myInstance = 0 static protected inherited
the singleton window instance
Definition at line 165 of file GUIMainWindow.h.
Referenced by GUIMainWindow::getInstance(), and GUIMainWindow::GUIMainWindow().
myLeftDock
FXDockSite * GUIMainWindow::myLeftDock protected inherited
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
myListInternal
bool GUIMainWindow::myListInternal protected inherited
information whether the locator should list internal structures
Definition at line 156 of file GUIMainWindow.h.
Referenced by GUIMainWindow::listInternal(), and GUIApplicationWindow::onCmdListInternal().
myListParking
bool GUIMainWindow::myListParking protected inherited
information whether the locator should list parking vehicles
Definition at line 159 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::fillMenuBar(), GUIMainWindow::listParking(), and GUIApplicationWindow::onCmdListParking().
myListTeleporting
bool GUIMainWindow::myListTeleporting protected inherited
information whether the locator should list teleporting vehicles
Definition at line 162 of file GUIMainWindow.h.
Referenced by GUIMainWindow::listTeleporting(), and GUIApplicationWindow::onCmdListTeleporting().
myLoadThread
GNELoadThread* GNEApplicationWindow::myLoadThread protected
the thread that loads the network
Definition at line 323 of file GNEApplicationWindow.h.
Referenced by dependentBuild(), loadConfigOrNet(), and ~GNEApplicationWindow().
myLoadThreadEvent
FXEX::FXThreadEvent GNEApplicationWindow::myLoadThreadEvent protected
io-event with the load-thread
Definition at line 363 of file GNEApplicationWindow.h.
Referenced by dependentBuild().
myLocatorMenu
FXMenuPane * GNEApplicationWindow::myLocatorMenu protected
Definition at line 332 of file GNEApplicationWindow.h.
Referenced by fillMenuBar(), and ~GNEApplicationWindow().
myMainSplitter
FXSplitter* GNEApplicationWindow::myMainSplitter protected
The splitter that divides the main window into view and the log window.
Definition at line 343 of file GNEApplicationWindow.h.
Referenced by dependentBuild().
myMDIClient
FXMDIClient* GUIMainWindow::myMDIClient protected inherited
The multi view panel.
Definition at line 138 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::dependentBuild(), dependentBuild(), GUIApplicationWindow::fillMenuBar(), GUIMainWindow::getActiveView(), GUIApplicationWindow::getBuildGLCanvas(), getBuildGLCanvas(), GUIApplicationWindow::onCmdEditChosen(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), onCmdLocate(), GUIApplicationWindow::onCmdLocate(), GUIApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdShowStats(), onKeyPress(), GUIApplicationWindow::onKeyPress(), onKeyRelease(), GUIApplicationWindow::onKeyRelease(), GUIApplicationWindow::openNewView(), openNewView(), and GUIMainWindow::updateChildren().
myMDIMenu
FXMDIMenu* GNEApplicationWindow::myMDIMenu protected
The menu used for the MDI-windows.
Definition at line 354 of file GNEApplicationWindow.h.
Referenced by dependentBuild(), and openNewView().
myMenuBar
FXMenuBar* GNEApplicationWindow::myMenuBar protected
The application menu bar.
Definition at line 357 of file GNEApplicationWindow.h.
Referenced by dependentBuild(), and fillMenuBar().
myMenuBarDrag
FXToolBarShell * GNEApplicationWindow::myMenuBarDrag protected
Definition at line 346 of file GNEApplicationWindow.h.
Referenced by create(), dependentBuild(), and detach().
myMessageWindow
GUIMessageWindow* GNEApplicationWindow::myMessageWindow protected
A window to display messages, warnings and error in.
Definition at line 340 of file GNEApplicationWindow.h.
Referenced by closeAllWindows(), dependentBuild(), fillMenuBar(), handleEvent_Message(), handleEvent_NetworkLoaded(), onCmdClearMsgWindow(), onCmdComputeJunctionsVolatile(), onCmdSaveAdditionals(), onCmdSaveAsPlainXML(), onCmdSaveJoined(), onCmdSaveNetwork(), and onCmdSaveShapes().
myName
std::string GNEApplicationWindow::myName protected
the name of the simulation
Definition at line 320 of file GNEApplicationWindow.h.
myNet
GNENet* GNEApplicationWindow::myNet protected
we are responsible for the net
Definition at line 378 of file GNEApplicationWindow.h.
Referenced by closeAllWindows(), handleEvent_NetworkLoaded(), onCmdCleanInvalidCrossings(), onCmdCleanJunctions(), onCmdComputeJunctions(), onCmdComputeJunctionsVolatile(), onCmdJoinJunctions(), onCmdOpenAdditionals(), onCmdOpenShapes(), onCmdSaveAdditionals(), onCmdSaveAsPlainXML(), onCmdSaveJoined(), onCmdSaveNetwork(), onCmdSaveShapes(), onUpdNeedsNetwork(), onUpdReload(), onUpdSaveNetwork(), and openNewView().
myProcessingMenu
FXMenuPane * GNEApplicationWindow::myProcessingMenu protected
Definition at line 332 of file GNEApplicationWindow.h.
Referenced by fillMenuBar(), and ~GNEApplicationWindow().
myRecentConfigs
FXRecentFiles GNEApplicationWindow::myRecentConfigs protected
List of recent config files.
Definition at line 366 of file GNEApplicationWindow.h.
Referenced by fillMenuBar(), and onCmdOpenConfiguration().
myRecentNets
FXRecentFiles GNEApplicationWindow::myRecentNets protected
List of recent nets.
Definition at line 369 of file GNEApplicationWindow.h.
Referenced by fillMenuBar(), onCmdOpenNetwork(), and onCmdOpenRecent().
myRightDock
FXDockSite * GUIMainWindow::myRightDock protected inherited
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
mySaveAdditionalsMenuCommand
FXMenuCommand* GNEApplicationWindow::mySaveAdditionalsMenuCommand private
FXMenuCommand for enable or disable save additionals.
Definition at line 394 of file GNEApplicationWindow.h.
Referenced by continueWithUnsavedAdditionalChanges(), enableSaveAdditionalsMenu(), fillMenuBar(), onCmdClose(), onCmdOpenNetwork(), and onCmdSaveAdditionals().
mySaveShapesMenuCommand
FXMenuCommand* GNEApplicationWindow::mySaveShapesMenuCommand private
FXMenuCommand for enable or disable save shapes.
Definition at line 397 of file GNEApplicationWindow.h.
Referenced by continueWithUnsavedShapeChanges(), enableSaveShapesMenu(), fillMenuBar(), onCmdClose(), onCmdOpenNetwork(), and onCmdSaveShapes().
myShapesFile
std::string GNEApplicationWindow::myShapesFile protected
filename for load/save shapes
Definition at line 390 of file GNEApplicationWindow.h.
Referenced by handleEvent_NetworkLoaded(), onCmdComputeJunctionsVolatile(), onCmdSaveShapes(), onCmdSaveShapesAs(), and setShapesFile().
myStatusbar
FXStatusBar* GUIMainWindow::myStatusbar protected inherited
The status bar.
Definition at line 141 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::dependentBuild(), dependentBuild(), GUIApplicationWindow::fillMenuBar(), fillMenuBar(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), GUIApplicationWindow::onCmdOpenRecent(), onCmdOpenRecent(), GUIApplicationWindow::onCmdStart(), GUIApplicationWindow::onCmdStep(), GUIApplicationWindow::openNewView(), GUIApplicationWindow::setStatusBarText(), and setStatusBarText().
mySubWindows
std::vector<FXMDIChild*> GUIMainWindow::mySubWindows protected inherited
Definition at line 129 of file GUIMainWindow.h.
Referenced by GUIMainWindow::addChild(), GUIApplicationWindow::closeAllWindows(), closeAllWindows(), getView(), GUIMainWindow::getViewByID(), GUIMainWindow::getViewIDs(), GUIApplicationWindow::onCmdNetedit(), and GUIMainWindow::removeChild().
myTitlePrefix
const FXString GNEApplicationWindow::myTitlePrefix protected
the prefix for the window title
Definition at line 384 of file GNEApplicationWindow.h.
Referenced by closeAllWindows(), dependentBuild(), handleEvent_NetworkLoaded(), and onCmdSaveAsNetwork().
myToolBar1
FXToolBar* GNEApplicationWindow::myToolBar1 protected
The application tool bar.
Definition at line 360 of file GNEApplicationWindow.h.
myToolBar2
FXToolBar * GNEApplicationWindow::myToolBar2 protected
Definition at line 360 of file GNEApplicationWindow.h.
myToolBar3
FXToolBar * GNEApplicationWindow::myToolBar3 protected
Definition at line 360 of file GNEApplicationWindow.h.
myToolBar4
FXToolBar * GNEApplicationWindow::myToolBar4 protected
Definition at line 360 of file GNEApplicationWindow.h.
myToolBar5
FXToolBar * GNEApplicationWindow::myToolBar5 protected
Definition at line 360 of file GNEApplicationWindow.h.
myToolBarDrag1
FXToolBarShell* GNEApplicationWindow::myToolBarDrag1 protected
for some menu detaching fun
Definition at line 346 of file GNEApplicationWindow.h.
myToolBarDrag2
FXToolBarShell * GNEApplicationWindow::myToolBarDrag2 protected
Definition at line 346 of file GNEApplicationWindow.h.
myToolBarDrag3
FXToolBarShell * GNEApplicationWindow::myToolBarDrag3 protected
Definition at line 346 of file GNEApplicationWindow.h.
myToolBarDrag4
FXToolBarShell * GNEApplicationWindow::myToolBarDrag4 protected
Definition at line 346 of file GNEApplicationWindow.h.
myToolBarDrag5
FXToolBarShell * GNEApplicationWindow::myToolBarDrag5 protected
Definition at line 346 of file GNEApplicationWindow.h.
myTopDock
FXDockSite* GUIMainWindow::myTopDock protected inherited
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::buildToolBars(), GUIApplicationWindow::dependentBuild(), dependentBuild(), GUIMainWindow::GUIMainWindow(), and GUIMainWindow::~GUIMainWindow().
myTrackerLock
MFXMutex GUIMainWindow::myTrackerLock protected inherited
A lock to make the removal and addition of trackers secure.
Definition at line 132 of file GUIMainWindow.h.
Referenced by GUIMainWindow::addChild(), GUIApplicationWindow::closeAllWindows(), closeAllWindows(), GUIMainWindow::removeChild(), and GUIMainWindow::updateChildren().
myTrackerWindows
std::vector<FXMainWindow*> GUIMainWindow::myTrackerWindows protected inherited
Definition at line 130 of file GUIMainWindow.h.
Referenced by GUIMainWindow::addChild(), GUIApplicationWindow::closeAllWindows(), closeAllWindows(), GUIMainWindow::removeChild(), and GUIMainWindow::updateChildren().
myUndoList
GNEUndoList* GNEApplicationWindow::myUndoList protected
the one and only undo list
Definition at line 381 of file GNEApplicationWindow.h.
Referenced by closeAllWindows(), continueWithUnsavedChanges(), fillMenuBar(), getUndoList(), handleEvent_NetworkLoaded(), onCmdCleanInvalidCrossings(), onCmdCleanJunctions(), onCmdJoinJunctions(), onCmdOpenAdditionals(), onCmdOpenShapes(), onCmdSaveAsPlainXML(), onCmdSaveNetwork(), openNewView(), and ~GNEApplicationWindow().
myViewNumber
int GNEApplicationWindow::myViewNumber protected
The current view number.
Definition at line 326 of file GNEApplicationWindow.h.
Referenced by handleEvent_NetworkLoaded(), and openNewView().
myWindowsMenu
FXMenuPane * GNEApplicationWindow::myWindowsMenu protected
Definition at line 332 of file GNEApplicationWindow.h.
Referenced by create(), fillMenuBar(), and ~GNEApplicationWindow().
The documentation for this class was generated from the following files:
GNEApplicationWindow.h
GNEApplicationWindow.cpp