SUMO - Simulation of Urban MObility: TraCIAPI::TraCIScopeWrapper Class Reference
TraCIAPI::TraCIScopeWrapper Class Reference
An abstract interface for accessing type-dependent values.
#include <TraCIAPI.h>
Public Member Functions
TraCIScopeWrapper (TraCIAPI &parent)
Constructor.
virtual ~TraCIScopeWrapper ()
Destructor.
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
TraCIScopeWrapper & operator= (const TraCIScopeWrapper &src)
invalidated assignment operator
TraCIScopeWrapper (const TraCIScopeWrapper &src)
invalidated copy constructor
Detailed Description
An abstract interface for accessing type-dependent values.
Must be derived by interfaces which implement access methods to certain object types
Definition at line 116 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIScopeWrapper() [1/2]
TraCIAPI::TraCIScopeWrapper::TraCIScopeWrapper (TraCIAPI & parent) inline
Constructor.
Parameters
[in] parent The parent TraCI client which offers the connection
Definition at line 121 of file TraCIAPI.h.
~TraCIScopeWrapper()
virtual TraCIAPI::TraCIScopeWrapper::~TraCIScopeWrapper () inline virtual
Destructor.
Definition at line 124 of file TraCIAPI.h.
TraCIScopeWrapper() [2/2]
TraCIAPI::TraCIScopeWrapper::TraCIScopeWrapper (const TraCIScopeWrapper & src) private
invalidated copy constructor
Member Function Documentation
operator=()
TraCIScopeWrapper& TraCIAPI::TraCIScopeWrapper::operator= (const TraCIScopeWrapper & src) private
invalidated assignment operator
Referenced by TraCIAPI::EdgeScope::~EdgeScope(), TraCIAPI::GUIScope::~GUIScope(), TraCIAPI::InductionLoopScope::~InductionLoopScope(), TraCIAPI::JunctionScope::~JunctionScope(), TraCIAPI::LaneAreaScope::~LaneAreaScope(), TraCIAPI::LaneScope::~LaneScope(), TraCIAPI::MeMeScope::~MeMeScope(), TraCIAPI::PersonScope::~PersonScope(), TraCIAPI::POIScope::~POIScope(), TraCIAPI::PolygonScope::~PolygonScope(), TraCIAPI::RouteScope::~RouteScope(), TraCIAPI::SimulationScope::~SimulationScope(), TraCIAPI::TrafficLightScope::~TrafficLightScope(), and TraCIAPI::VehicleTypeScope::~VehicleTypeScope().
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following file:
TraCIAPI.h