SUMO - Simulation of Urban MObility: NIVissimTL::NIVissimTLSignal Class Reference
NIVissimTL::NIVissimTLSignal Class Reference
#include <NIVissimTL.h>
Public Member Functions
bool addTo (NBEdgeCont &ec, NBLoadedTLDef *node) const
Position getPosition () const
bool isWithin (const PositionVector &poly) const
NIVissimTLSignal (int id, const std::string &name, const std::vector< int > &groupids, int edgeid, int laneno, double position, const std::vector< int > &assignedVehicleTypes)
~NIVissimTLSignal ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int lsaid, int id, NIVissimTLSignal *o)
static NIVissimTLSignal * dictionary (int lsaid, int id)
static SSignalDictType getSignalsFor (int tlid)
Protected Attributes
int myEdgeID
std::vector< int > myGroupIDs
int myID
int myLane
std::string myName
double myPosition
std::vector< int > myVehicleTypes
Static Protected Attributes
static SignalDictType myDict
Detailed Description
Definition at line 86 of file NIVissimTL.h.
Constructor & Destructor Documentation
NIVissimTLSignal()
NIVissimTL::NIVissimTLSignal::NIVissimTLSignal (int id, const std::string & name, const std::vector< int > & groupids, int edgeid, int laneno, double position, const std::vector< int > & assignedVehicleTypes)
Definition at line 60 of file NIVissimTL.cpp.
~NIVissimTLSignal()
NIVissimTL::NIVissimTLSignal::~NIVissimTLSignal ()
Definition at line 72 of file NIVissimTL.cpp.
Member Function Documentation
addTo()
bool NIVissimTL::NIVissimTLSignal::addTo (NBEdgeCont & ec, NBLoadedTLDef * node) const
Definition at line 139 of file NIVissimTL.cpp.
References NBLoadedTLDef::addToSignalGroup(), NIVissimConnection::dictionary(), NBEdge::getConnectionsFromLane(), NIVissimConnection::getFromEdgeID(), NBEdge::getNumLanes(), NIVissimConnection::getToEdgeID(), NBEdge::lanesWereAssigned(), NIVissimTL::NIVissimTLSignalGroup::myDict, myEdgeID, myGroupIDs, myLane, myPosition, NBEdgeCont::retrievePossiblySplit(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, toString(), and WRITE_WARNING.
clearDict()
void NIVissimTL::NIVissimTLSignal::clearDict () static
Definition at line 118 of file NIVissimTL.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/2]
bool NIVissimTL::NIVissimTLSignal::dictionary (int lsaid, int id, NIVissimTL::NIVissimTLSignal * o) static
Definition at line 87 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimSingleTypeParser_Signalgeberdefinition::parse().
dictionary() [2/2]
NIVissimTL::NIVissimTLSignal * NIVissimTL::NIVissimTLSignal::dictionary (int lsaid, int id) static
Definition at line 104 of file NIVissimTL.cpp.
References myDict.
getPosition()
Position NIVissimTL::NIVissimTLSignal::getPosition () const
Definition at line 81 of file NIVissimTL.cpp.
References NIVissimAbstractEdge::dictionary(), myEdgeID, and myPosition.
Referenced by isWithin().
getSignalsFor()
NIVissimTL::SSignalDictType NIVissimTL::NIVissimTLSignal::getSignalsFor (int tlid) static
Definition at line 129 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimTL::dict_SetSignals().
isWithin()
bool NIVissimTL::NIVissimTLSignal::isWithin (const PositionVector & poly) const
Definition at line 75 of file NIVissimTL.cpp.
References PositionVector::around(), and getPosition().
Field Documentation
myDict
NIVissimTL::SignalDictType NIVissimTL::NIVissimTLSignal::myDict static protected
Definition at line 110 of file NIVissimTL.h.
Referenced by clearDict(), dictionary(), and getSignalsFor().
myEdgeID
int NIVissimTL::NIVissimTLSignal::myEdgeID protected
Definition at line 106 of file NIVissimTL.h.
Referenced by addTo(), and getPosition().
myGroupIDs
std::vector<int> NIVissimTL::NIVissimTLSignal::myGroupIDs protected
Definition at line 105 of file NIVissimTL.h.
Referenced by addTo().
myID
int NIVissimTL::NIVissimTLSignal::myID protected
Definition at line 103 of file NIVissimTL.h.
myLane
int NIVissimTL::NIVissimTLSignal::myLane protected
Definition at line 107 of file NIVissimTL.h.
Referenced by addTo().
myName
std::string NIVissimTL::NIVissimTLSignal::myName protected
Definition at line 104 of file NIVissimTL.h.
myPosition
double NIVissimTL::NIVissimTLSignal::myPosition protected
Definition at line 108 of file NIVissimTL.h.
Referenced by addTo(), and getPosition().
myVehicleTypes
std::vector<int> NIVissimTL::NIVissimTLSignal::myVehicleTypes protected
Definition at line 109 of file NIVissimTL.h.
The documentation for this class was generated from the following files:
NIVissimTL.h
NIVissimTL.cpp