SUMO - Simulation of Urban MObility: CircularBuffer< T > Class Template Reference
CircularBuffer< T > Class Template Reference
#include <MSSwarmTrafficLightLogic.h>
Public Member Functions
bool addValue (const T newValue, T &replacedValue)
T at (const int index) const
T back () const
CircularBuffer (int size)
void clear ()
T front () const
void push_front (const T value)
int size () const
virtual ~CircularBuffer ()
Private Member Functions
void insert (const T &value)
Private Attributes
T * m_buffer
int m_currentIndex
bool m_firstTime
int m_size
Detailed Description
template<class T>
class CircularBuffer< T >
Definition at line 43 of file MSSwarmTrafficLightLogic.h.
Constructor & Destructor Documentation
CircularBuffer()
template<class T > CircularBuffer< T >::CircularBuffer (int size) inline
Definition at line 45 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::m_buffer, and CircularBuffer< T >::m_size.
~CircularBuffer()
template<class T > virtual CircularBuffer< T >::~CircularBuffer () inline virtual
Definition at line 50 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::m_buffer.
Member Function Documentation
addValue()
template<class T > bool CircularBuffer< T >::addValue (const T newValue, T & replacedValue) inline
Definition at line 54 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::insert(), CircularBuffer< T >::m_buffer, CircularBuffer< T >::m_currentIndex, and CircularBuffer< T >::m_firstTime.
at()
template<class T > T CircularBuffer< T >::at (const int index) const inline
Definition at line 67 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::m_buffer, CircularBuffer< T >::m_currentIndex, and CircularBuffer< T >::m_size.
Referenced by CircularBuffer< T >::back(), and CircularBuffer< T >::front().
back()
template<class T > T CircularBuffer< T >::back () const inline
Definition at line 76 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::at(), and CircularBuffer< T >::size().
clear()
template<class T > void CircularBuffer< T >::clear () inline
Definition at line 87 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::m_currentIndex, and CircularBuffer< T >::m_firstTime.
front()
template<class T > T CircularBuffer< T >::front () const inline
Definition at line 72 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::at().
insert()
template<class T > void CircularBuffer< T >::insert (const T & value) inline private
Definition at line 98 of file MSSwarmTrafficLightLogic.h.
Referenced by CircularBuffer< T >::addValue(), and CircularBuffer< T >::push_front().
push_front()
template<class T > void CircularBuffer< T >::push_front (const T value) inline
Definition at line 63 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::insert().
size()
template<class T > int CircularBuffer< T >::size () const inline
Definition at line 80 of file MSSwarmTrafficLightLogic.h.
References CircularBuffer< T >::m_currentIndex, CircularBuffer< T >::m_firstTime, and CircularBuffer< T >::m_size.
Referenced by CircularBuffer< T >::back().
Field Documentation
m_buffer
template<class T > T* CircularBuffer< T >::m_buffer private
Definition at line 93 of file MSSwarmTrafficLightLogic.h.
Referenced by CircularBuffer< T >::addValue(), CircularBuffer< T >::at(), CircularBuffer< T >::CircularBuffer(), and CircularBuffer< T >::~CircularBuffer().
m_currentIndex
template<class T > int CircularBuffer< T >::m_currentIndex private
Definition at line 95 of file MSSwarmTrafficLightLogic.h.
Referenced by CircularBuffer< T >::addValue(), CircularBuffer< T >::at(), CircularBuffer< T >::clear(), and CircularBuffer< T >::size().
m_firstTime
template<class T > bool CircularBuffer< T >::m_firstTime private
Definition at line 96 of file MSSwarmTrafficLightLogic.h.
Referenced by CircularBuffer< T >::addValue(), CircularBuffer< T >::clear(), and CircularBuffer< T >::size().
m_size
template<class T > int CircularBuffer< T >::m_size private
Definition at line 94 of file MSSwarmTrafficLightLogic.h.
Referenced by CircularBuffer< T >::at(), CircularBuffer< T >::CircularBuffer(), and CircularBuffer< T >::size().
The documentation for this class was generated from the following file:
MSSwarmTrafficLightLogic.h