SUMO - Simulation of Urban MObility: MSDetectorControl Class Reference
MSDetectorControl Class Reference
Detectors container; responsible for string and output generation.
#include <MSDetectorControl.h>
Data Structures
struct detectorEquals
Returns true if detectors are equal.
Public Member Functions
void add (SumoXMLTag type, MSDetectorFileOutput *d, const std::string &device, SUMOTime splInterval, SUMOTime begin=-1)
Adds a detector/output combination into the containers.
void add (SumoXMLTag type, MSDetectorFileOutput *d)
Adds only the detector into the containers.
void add (MSMeanData *mn, const std::string &device, SUMOTime frequency, SUMOTime begin)
Adds a mean data object.
void addDetectorAndInterval (MSDetectorFileOutput *det, OutputDevice *device, SUMOTime interval, SUMOTime begin=-1)
Adds one of the detectors as a new MSDetectorFileOutput.
void close (SUMOTime step)
Closes the detector outputs.
const std::vector< SumoXMLTag > getAvailableTypes () const
Returns the list of available detector types.
const NamedObjectCont< MSDetectorFileOutput * > & getTypedDetectors (SumoXMLTag type) const
Returns the list of detectors of the given type.
MSDetectorControl ()
Constructor.
void updateDetectors (const SUMOTime step)
Computes detector values.
void writeOutput (SUMOTime step, bool closing)
Writes the output to be generated within the given time step.
~MSDetectorControl ()
Destructor.
Protected Types
Structures needed for assigning detectors to intervals
typedef std::pair< MSDetectorFileOutput *, OutputDevice *> DetectorFilePair
A pair of a Detector with it's associated file-stream.
typedef std::vector< DetectorFilePair > DetectorFileVec
Container holding DetectorFilePair (with the same interval).
typedef std::pair< SUMOTime, SUMOTime > IntervalsKey
Definition of the interval key.
typedef std::map< IntervalsKey, DetectorFileVec > Intervals
Association of intervals to DetectorFilePair containers.
Protected Attributes
std::map< SumoXMLTag, NamedObjectCont< MSDetectorFileOutput * > > myDetectors
The detectors map, first by detector type, then using NamedObjectCont (.
NamedObjectCont< MSDetectorFileOutput * > myEmptyContainer
An empty container to return in getTypedDetectors() if no detectors of the asked type exist.
Intervals myIntervals
Map that hold DetectorFileVec for given intervals.
std::map< IntervalsKey, SUMOTime > myLastCalls
The map that holds the last call for each sample interval.
std::vector< MSMeanData * > myMeanData
List of harmonoise detectors.
Private Member Functions
MSDetectorControl (const MSDetectorControl &)
Invalidated copy constructor.
MSDetectorControl & operator= (const MSDetectorControl &)
Invalidated assignment operator.
Detailed Description
Detectors container; responsible for string and output generation.
Definition at line 59 of file MSDetectorControl.h.
Member Typedef Documentation
DetectorFilePair
typedef std::pair< MSDetectorFileOutput*, OutputDevice* > MSDetectorControl::DetectorFilePair protected
A pair of a Detector with it's associated file-stream.
Definition at line 192 of file MSDetectorControl.h.
DetectorFileVec
typedef std::vector< DetectorFilePair > MSDetectorControl::DetectorFileVec protected
Container holding DetectorFilePair (with the same interval).
Definition at line 195 of file MSDetectorControl.h.
Intervals
typedef std::map< IntervalsKey, DetectorFileVec > MSDetectorControl::Intervals protected
Association of intervals to DetectorFilePair containers.
Definition at line 201 of file MSDetectorControl.h.
IntervalsKey
typedef std::pair<SUMOTime, SUMOTime> MSDetectorControl::IntervalsKey protected
Definition of the interval key.
Definition at line 198 of file MSDetectorControl.h.
Constructor & Destructor Documentation
MSDetectorControl() [1/2]
MSDetectorControl::MSDetectorControl ()
Constructor.
Definition at line 46 of file MSDetectorControl.cpp.
~MSDetectorControl()
MSDetectorControl::~MSDetectorControl ()
Destructor.
Deletes all stored detectors.
Definition at line 50 of file MSDetectorControl.cpp.
References myDetectors, and myMeanData.
MSDetectorControl() [2/2]
MSDetectorControl::MSDetectorControl (const MSDetectorControl &) private
Invalidated copy constructor.
Member Function Documentation
add() [1/3]
void MSDetectorControl::add (SumoXMLTag type, MSDetectorFileOutput * d, const std::string & device, SUMOTime splInterval, SUMOTime begin = -1)
Adds a detector/output combination into the containers.
The detector is tried to be added into "myDetectors". If the detector is already known (the id was already used for a similar detector), a ProcessError is thrown.
Otherwise, the Detector2File-mechanism is instantiated for the detector.
Please note, that the detector control gets responsible for the detector.
Parameters
[in] type The type of the detector
[in] d The detector to add
[in] device The device the detector uses
[in] splInterval The sample interval of the detector
Exceptions
ProcessError If the detector is already known
Definition at line 70 of file MSDetectorControl.cpp.
References addDetectorAndInterval(), OutputDevice::getDevice(), Named::getID(), myDetectors, and toString().
Referenced by add(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::buildRouteProbe(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NLDetectorBuilder::createEdgeLaneMeanData(), NLDetectorBuilder::endE3Detector(), MSDelayBasedTrafficLightLogic::init(), and MSActuatedTrafficLightLogic::init().
add() [2/3]
void MSDetectorControl::add (SumoXMLTag type, MSDetectorFileOutput * d)
Adds only the detector into the containers.
The detector is tried to be added into "myDetectors". If the detector is already known (the id was already used for a similar detector), a ProcessError is thrown.
Please note, that the detector control gets responsible for the detector.
Parameters
[in] type The type of the detector
[in] d The detector to add
Exceptions
ProcessError If the detector is already known
Definition at line 80 of file MSDetectorControl.cpp.
References add(), Named::getID(), myDetectors, and toString().
add() [3/3]
void MSDetectorControl::add (MSMeanData * mn, const std::string & device, SUMOTime frequency, SUMOTime begin)
Adds a mean data object.
The detector is pushed into the internal list.
Please note, that the detector control gets responsible for the detector.
Parameters
[in] mn The mean data to add
[in] device The output device to use
[in] frequency The frequency for output generation
[in] begin The begin of the first interval
Definition at line 89 of file MSDetectorControl.cpp.
References addDetectorAndInterval(), OutputDevice::getDevice(), OptionsCont::getOptions(), MSMeanData::init(), myMeanData, and string2time().
addDetectorAndInterval()
void MSDetectorControl::addDetectorAndInterval (MSDetectorFileOutput * det, OutputDevice * device, SUMOTime interval, SUMOTime begin = -1)
Adds one of the detectors as a new MSDetectorFileOutput.
Parameters
[in] det The generator to add
[in] device The device to use
[in] interval The sample interval to use
[in] begin The start of the first sample interval to use
Definition at line 150 of file MSDetectorControl.cpp.
References OptionsCont::getOptions(), myIntervals, myLastCalls, string2time(), WRITE_WARNING, and MSDetectorFileOutput::writeXMLDetectorProlog().
Referenced by add().
close()
void MSDetectorControl::close (SUMOTime step)
Closes the detector outputs.
Goes through the intervals to write and writes the last step using the current simulation time as end.
Parameters
[in] step The time step (the simulation has ended at)
Definition at line 61 of file MSDetectorControl.cpp.
References myIntervals, and writeOutput().
Referenced by MSNet::closeSimulation().
getAvailableTypes()
const std::vector< SumoXMLTag > MSDetectorControl::getAvailableTypes () const
Returns the list of available detector types.
Returns
The list of types
Definition at line 100 of file MSDetectorControl.cpp.
References myDetectors.
Referenced by GUINet::initGUIStructures().
getTypedDetectors()
const NamedObjectCont< MSDetectorFileOutput * > & MSDetectorControl::getTypedDetectors (SumoXMLTag type) const
Returns the list of detectors of the given type.
Parameters
[in] type The type of detectors to be retrieved
Returns
The container of detectors
Definition at line 110 of file MSDetectorControl.cpp.
References myDetectors, and myEmptyContainer.
Referenced by libsumo::MultiEntryExit::getDetector(), libsumo::LaneArea::getDetector(), libsumo::InductionLoop::getDetector(), libsumo::MultiEntryExit::getIDCount(), libsumo::LaneArea::getIDCount(), libsumo::InductionLoop::getIDCount(), libsumo::MultiEntryExit::getIDList(), libsumo::LaneArea::getIDList(), libsumo::InductionLoop::getIDList(), TraCIServerAPI_InductionLoop::getPosition(), GUINet::initGUIStructures(), NLTriggerBuilder::parseAndBuildCalibrator(), and updateDetectors().
operator=()
MSDetectorControl& MSDetectorControl::operator= (const MSDetectorControl &) private
Invalidated assignment operator.
updateDetectors()
void MSDetectorControl::updateDetectors (const SUMOTime step)
Computes detector values.
Some detectors need to be touched each time step in order to compute values from the vehicles stored in their containers. This method goes through all of these detectors and forces a recomputation of the values.
Parameters
[in] step The current time step
Definition at line 119 of file MSDetectorControl.cpp.
References getTypedDetectors(), myDetectors, and myMeanData.
Referenced by MSNet::writeOutput().
writeOutput()
void MSDetectorControl::writeOutput (SUMOTime step, bool closing)
Writes the output to be generated within the given time step.
Goes through the list of intervals. If one interval has ended within the given step or if the closing-flag is set and the output was not written in this step already, the writeXMLOutput method is called for all MSDetectorFileOutputs within this interval.
Parameters
[in] step The current time step
[in] closing Whether the device is closed
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 132 of file MSDetectorControl.cpp.
References myIntervals, myLastCalls, and MSDetectorFileOutput::writeXMLOutput().
Referenced by close(), and MSNet::writeOutput().
Field Documentation
myDetectors
std::map<SumoXMLTag, NamedObjectCont< MSDetectorFileOutput*> > MSDetectorControl::myDetectors protected
The detectors map, first by detector type, then using NamedObjectCont (.
See also
NamedObjectCont)
Definition at line 224 of file MSDetectorControl.h.
Referenced by add(), getAvailableTypes(), getTypedDetectors(), updateDetectors(), and ~MSDetectorControl().
myEmptyContainer
NamedObjectCont< MSDetectorFileOutput*> MSDetectorControl::myEmptyContainer protected
An empty container to return in getTypedDetectors() if no detectors of the asked type exist.
Definition at line 237 of file MSDetectorControl.h.
Referenced by getTypedDetectors().
myIntervals
Intervals MSDetectorControl::myIntervals protected
Map that hold DetectorFileVec for given intervals.
Definition at line 228 of file MSDetectorControl.h.
Referenced by addDetectorAndInterval(), close(), and writeOutput().
myLastCalls
std::map<IntervalsKey, SUMOTime> MSDetectorControl::myLastCalls protected
The map that holds the last call for each sample interval.
Definition at line 231 of file MSDetectorControl.h.
Referenced by addDetectorAndInterval(), and writeOutput().
myMeanData
std::vector<MSMeanData*> MSDetectorControl::myMeanData protected
List of harmonoise detectors.
Definition at line 234 of file MSDetectorControl.h.
Referenced by add(), updateDetectors(), and ~MSDetectorControl().
The documentation for this class was generated from the following files:
MSDetectorControl.h
MSDetectorControl.cpp