SUMO - Simulation of Urban MObility: MSLane::by_connections_to_sorter Class Reference
MSLane::by_connections_to_sorter Class Reference
Sorts edges by their angle relative to the given edge (straight comes first)
Public Member Functions
by_connections_to_sorter (const MSEdge *const e)
constructor
int operator() (const MSEdge *const e1, const MSEdge *const e2) const
comparing operator
Private Member Functions
by_connections_to_sorter & operator= (const by_connections_to_sorter &)
Private Attributes
const MSEdge *const myEdge
double myLaneDir
Detailed Description
Sorts edges by their angle relative to the given edge (straight comes first)
Definition at line 1332 of file MSLane.h.
Constructor & Destructor Documentation
by_connections_to_sorter()
MSLane::by_connections_to_sorter::by_connections_to_sorter (const MSEdge *const e) explicit
constructor
Definition at line 2564 of file MSLane.cpp.
Member Function Documentation
operator()()
int MSLane::by_connections_to_sorter::operator() (const MSEdge *const e1, const MSEdge *const e2) const
comparing operator
Definition at line 2571 of file MSLane.cpp.
References MSEdge::allowedLanes(), GeomHelper::angleDiff(), MSLane::getShape(), M_PI, myEdge, and myLaneDir.
operator=()
by_connections_to_sorter& MSLane::by_connections_to_sorter::operator= (const by_connections_to_sorter &) private
Field Documentation
myEdge
const MSEdge* const MSLane::by_connections_to_sorter::myEdge private
Definition at line 1343 of file MSLane.h.
Referenced by operator()().
myLaneDir
double MSLane::by_connections_to_sorter::myLaneDir private
Definition at line 1344 of file MSLane.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
MSLane.h
MSLane.cpp