SUMO - Simulation of Urban MObility: NBNodeCont Class Reference
NBNodeCont Class Reference
Container for nodes during the netbuilding process.
#include <NBNodeCont.h>
Public Member Functions
void analyzeCluster (std::set< NBNode *> cluster, std::string &id, Position &pos, bool &hasTLS, TrafficLightType &type)
void clear ()
deletes all nodes
void computeLanes2Lanes ()
divides the incoming lanes on outgoing lanes
void computeLogics (const NBEdgeCont &ec, OptionsCont &oc)
build the list of outgoing edges and lanes
void computeNodeShapes (double mismatchThreshold=-1)
Compute the junction shape for this node.
void discardTrafficLights (NBTrafficLightLogicCont &tlc, bool geometryLike, bool guessSignals)
std::vector< std::string > getAllNames () const
get all node names
std::string getFreeID ()
generates a new node ID
const std::vector< std::set< std::string > > & getJoinedClusters () const
gets all joined clusters (see doc for myClusters2Join)
void markAsSplit (const NBNode *node)
mark a node as being created form a split
NBNodeCont ()
Constructor.
void printBuiltNodesStatistics () const
Prints statistics about built nodes.
void registerJoinedCluster (const std::set< NBNode *> &cluster)
gets all joined clusters (see doc for myClusters2Join)
int remapIDs (bool numericaIDs, bool reservedIDs)
remap node IDs accoring to options –numerical-ids and –reserved-ids
void rename (NBNode *node, const std::string &newID)
Renames the node. Throws exception if newID already exists.
int size () const
Returns the number of nodes stored in this container.
~NBNodeCont ()
Destructor.
Insertion/removal/retrieval of nodes
bool insert (const std::string &id, const Position &position, NBDistrict *district=0)
Inserts a node into the map.
bool insert (NBNode *node)
Inserts a node into the map.
bool erase (NBNode *node)
Removes the given node, deleting it.
bool extract (NBNode *node, bool remember=false)
Removes the given node but does not delete it.
NBNode * retrieve (const std::string &id) const
Returns the node with the given name.
NBNode * retrieve (const Position &position, const double offset=0.) const
Returns the node with the given coordinates.
std::map< std::string, NBNode * >::const_iterator begin () const
Returns the pointer to the begin of the stored nodes.
std::map< std::string, NBNode * >::const_iterator end () const
Returns the pointer to the end of the stored nodes.
Methods for for joining nodes
void addJoinExclusion (const std::vector< std::string > &ids, bool check=false)
void addCluster2Join (std::set< std::string > cluster)
add ids of nodes which shall be joined into a single node
int joinLoadedClusters (NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tlc)
Joins loaded junction clusters (see NIXMLNodesHandler)
int joinJunctions (double maxDist, NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tlc, NBPTStopCont &sc)
Joins junctions that are very close together.
Adapting the input
void removeSelfLoops (NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tc)
Removes self-loop edges (edges where the source and the destination node are the same)
void joinSimilarEdges (NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tlc)
Joins edges connecting the same nodes.
void avoidOverlap ()
fix overlap
void removeIsolatedRoads (NBDistrictCont &dc, NBEdgeCont &ec)
Removes sequences of edges that are not connected with a junction. Simple roads without junctions sometimes remain when converting from OpenStreetMap, but they make no sense. Remaining empty nodes are also deleted.
void removeComponents (NBDistrictCont &dc, NBEdgeCont &ec, const int numKeep)
Checks the network for weak connectivity and removes all but the largest components. The connectivity check is done regardless of edge direction and vclass.
int removeUnwishedNodes (NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tlc, NBPTStopCont &sc, NBPTLineCont &lc, NBParkingCont &pc, bool removeGeometryNodes)
Removes "unwished" nodes.
Methods for guessing/computing traffic lights
void guessTLs (OptionsCont &oc, NBTrafficLightLogicCont &tlc)
Guesses which junctions or junction clusters shall be controlled by tls.
void joinTLS (NBTrafficLightLogicCont &tlc, double maxdist)
Builds clusters of tls-controlled junctions and joins the control if possible.
void setAsTLControlled (NBNode *node, NBTrafficLightLogicCont &tlc, TrafficLightType type, std::string id="")
Sets the given node as being controlled by a tls.
Private Types
typedef std::pair< NBNode *, double > NodeAndDist
typedef std::vector< std::set< NBNode * > > NodeClusters
Definition of a node cluster container.
typedef std::map< std::string, NBNode * > NodeCont
Definition of the map of names to nodes.
Private Member Functions
NBNodeCont (const NBNodeCont &s)
invalidated copy constructor
NBNodeCont & operator= (const NBNodeCont &s)
invalidated assignment operator
Helper methods for for joining nodes
void generateNodeClusters (double maxDist, NodeClusters &into) const
Builds node clusters.
void joinNodeClusters (NodeClusters clusters, NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tlc)
joins the given node clusters
Helper methods for guessing/computing traffic lights
bool shouldBeTLSControlled (const std::set< NBNode *> &c) const
Returns whethe the given node cluster should be controlled by a tls.
Private Attributes
std::vector< std::set< std::string > > myClusters2Join
loaded sets of node ids to join (cleared after use)
std::set< NBNode * > myExtractedNodes
The extracted nodes which are kept for reference.
int myInternalID
The running internal id.
std::set< std::string > myJoined
ids found in loaded join clusters used for error checking
std::vector< std::set< std::string > > myJoinedClusters
sets of node ids which were joined
std::set< std::string > myJoinExclusions
set of node ids which should not be joined
NodeCont myNodes
The map of names to nodes.
NamedRTree myRTree
node positions for faster lookup
std::set< const NBNode * > mySplit
nodes that were created when splitting an edge
Detailed Description
Container for nodes during the netbuilding process.
Definition at line 66 of file NBNodeCont.h.
Member Typedef Documentation
NodeAndDist
typedef std::pair<NBNode*, double> NBNodeCont::NodeAndDist private
Definition at line 301 of file NBNodeCont.h.
NodeClusters
typedef std::vector<std::set<NBNode*> > NBNodeCont::NodeClusters private
Definition of a node cluster container.
Definition at line 300 of file NBNodeCont.h.
NodeCont
typedef std::map<std::string, NBNode*> NBNodeCont::NodeCont private
Definition of the map of names to nodes.
Definition at line 334 of file NBNodeCont.h.
Constructor & Destructor Documentation
NBNodeCont() [1/2]
NBNodeCont::NBNodeCont ()
Constructor.
Definition at line 67 of file NBNodeCont.cpp.
~NBNodeCont()
NBNodeCont::~NBNodeCont ()
Destructor.
Definition at line 72 of file NBNodeCont.cpp.
References clear().
NBNodeCont() [2/2]
NBNodeCont::NBNodeCont (const NBNodeCont & s) private
invalidated copy constructor
Member Function Documentation
addCluster2Join()
void NBNodeCont::addCluster2Join (std::set< std::string > cluster)
add ids of nodes which shall be joined into a single node
Parameters
[in] cluster The cluster to add
Definition at line 519 of file NBNodeCont.cpp.
References myClusters2Join, myJoined, myJoinExclusions, and WRITE_WARNING.
Referenced by NIXMLNodesHandler::addJoinCluster(), and end().
addJoinExclusion()
void NBNodeCont::addJoinExclusion (const std::vector< std::string > & ids, bool check = false)
Definition at line 503 of file NBNodeCont.cpp.
References myJoined, myJoinExclusions, retrieve(), and WRITE_WARNING.
Referenced by NIXMLNodesHandler::addJoinExclusion(), NBNetBuilder::compute(), and end().
analyzeCluster()
void NBNodeCont::analyzeCluster (std::set< NBNode *> cluster, std::string & id, Position & pos, bool & hasTLS, TrafficLightType & type)
Definition at line 847 of file NBNodeCont.cpp.
References Position::add(), StringBijection< T >::get(), OptionsCont::getOptions(), Position::mul(), toString(), SUMOXMLDefinitions::TrafficLightTypes, and WRITE_WARNING.
Referenced by joinNodeClusters(), GNENet::joinSelectedJunctions(), joinTLS(), and size().
avoidOverlap()
void NBNodeCont::avoidOverlap ()
fix overlap
Definition at line 443 of file NBNodeCont.cpp.
References myNodes.
Referenced by NBNetBuilder::compute(), and end().
begin()
std::map<std::string, NBNode*>::const_iterator NBNodeCont::begin () const inline
Returns the pointer to the begin of the stored nodes.
Definition at line 117 of file NBNodeCont.h.
References myNodes.
Referenced by NBNetBuilder::compute(), NBEdgePriorityComputer::computeEdgePriorities(), NBNodeTypeComputer::computeNodeTypes(), NBRampsComputer::computeRamps(), NBTurningDirectionsComputer::computeTurnDirections(), NBNetBuilder::mirrorX(), NBNetBuilder::moveToOrigin(), removeUnwishedNodes(), NBTrafficLightLogicCont::setTLControllingInformation(), NBNodesEdgesSorter::sortNodesEdges(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), and NWWriter_DlrNavteq::writeTrafficSignals().
clear()
void NBNodeCont::clear ()
deletes all nodes
Definition at line 1155 of file NBNodeCont.cpp.
References myExtractedNodes, and myNodes.
Referenced by size(), and ~NBNodeCont().
computeLanes2Lanes()
void NBNodeCont::computeLanes2Lanes ()
divides the incoming lanes on outgoing lanes
Definition at line 1138 of file NBNodeCont.cpp.
References myNodes.
Referenced by NBNetBuilder::compute(), and end().
computeLogics()
void NBNodeCont::computeLogics (const NBEdgeCont & ec, OptionsCont & oc)
build the list of outgoing edges and lanes
Definition at line 1147 of file NBNodeCont.cpp.
References myNodes.
Referenced by NBNetBuilder::compute(), and end().
computeNodeShapes()
void NBNodeCont::computeNodeShapes (double mismatchThreshold = -1)
Compute the junction shape for this node.
Parameters
[in] mismatchThreshold The threshold for warning about shapes which are away from myPosition
Definition at line 1182 of file NBNodeCont.cpp.
References myNodes.
Referenced by NBNetBuilder::compute(), and size().
discardTrafficLights()
void NBNodeCont::discardTrafficLights (NBTrafficLightLogicCont & tlc, bool geometryLike, bool guessSignals)
Definition at line 1276 of file NBNodeCont.cpp.
References NBTrafficLightLogicCont::extract(), NBNode::geometryLike(), NBNode::getControllingTLS(), NBNode::getOutgoingEdges(), NBNode::getPosition(), NBNode::isTLControlled(), myNodes, NODETYPE_UNKNOWN, NBNode::reinit(), and NBNode::removeTrafficLight().
Referenced by getJoinedClusters(), and NILoader::load().
end()
std::map<std::string, NBNode*>::const_iterator NBNodeCont::end () const inline
Returns the pointer to the end of the stored nodes.
Definition at line 122 of file NBNodeCont.h.
References addCluster2Join(), addJoinExclusion(), avoidOverlap(), computeLanes2Lanes(), computeLogics(), guessTLs(), joinJunctions(), joinLoadedClusters(), joinSimilarEdges(), joinTLS(), myNodes, removeComponents(), removeIsolatedRoads(), removeSelfLoops(), removeUnwishedNodes(), rename(), and setAsTLControlled().
Referenced by NBNetBuilder::compute(), NBEdgePriorityComputer::computeEdgePriorities(), NBNodeTypeComputer::computeNodeTypes(), NBRampsComputer::computeRamps(), NBTurningDirectionsComputer::computeTurnDirections(), NBNetBuilder::mirrorX(), NBNetBuilder::moveToOrigin(), NBTrafficLightLogicCont::setTLControllingInformation(), NBNodesEdgesSorter::sortNodesEdges(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), and NWWriter_DlrNavteq::writeTrafficSignals().
erase()
bool NBNodeCont::erase (NBNode * node)
Removes the given node, deleting it.
Parameters
[in] node The node to delete and remove
Returns
Whether the node could be removed (existed)
Definition at line 138 of file NBNodeCont.cpp.
References extract().
Referenced by joinNodeClusters(), NIVissimEdge::remapOneOfNodes(), removeComponents(), and removeIsolatedRoads().
extract()
bool NBNodeCont::extract (NBNode * node, bool remember = false)
Removes the given node but does not delete it.
Parameters
[in] node The node to delete and remove
[in] remember Whether to keep the node for future reference
Returns
Whether the node could be removed (existed)
Definition at line 149 of file NBNodeCont.cpp.
References Named::getID(), NBNode::getPosition(), myExtractedNodes, myNodes, myRTree, NamedRTree::Remove(), NBNode::removeTrafficLights(), Position::x(), and Position::y().
Referenced by NIXMLNodesHandler::deleteNode(), GNENet::deleteSingleJunction(), erase(), and removeUnwishedNodes().
generateNodeClusters()
void NBNodeCont::generateNodeClusters (double maxDist, NodeClusters & into) const private
Builds node clusters.
A node cluster is made up from nodes which are near by (distance<maxDist) and connected.
Parameters
[in] maxDist The maximum distance between two nodes for clustering
Definition at line 451 of file NBNodeCont.cpp.
References NBNode::geometryLike(), NBNode::getEdges(), NBEdge::getFromNode(), NBEdge::getLoadedLength(), NBEdge::getPermissions(), NBEdge::getToNode(), NBNode::hasIncoming(), myNodes, and SVC_PEDESTRIAN.
Referenced by guessTLs(), joinJunctions(), and joinTLS().
getAllNames()
std::vector< std::string > NBNodeCont::getAllNames () const
get all node names
Definition at line 1255 of file NBNodeCont.cpp.
References myNodes.
Referenced by GNENet::initJunctionsAndEdges(), remapIDs(), size(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
getFreeID()
std::string NBNodeCont::getFreeID ()
generates a new node ID
Definition at line 1168 of file NBNodeCont.cpp.
References retrieve().
Referenced by size().
getJoinedClusters()
const std::vector<std::set<std::string> >& NBNodeCont::getJoinedClusters () const inline
gets all joined clusters (see doc for myClusters2Join)
Definition at line 281 of file NBNodeCont.h.
References discardTrafficLights(), and myJoinedClusters.
Referenced by NWWriter_XML::writeJoinedJunctions().
guessTLs()
void NBNodeCont::guessTLs (OptionsCont & oc, NBTrafficLightLogicCont & tlc)
Guesses which junctions or junction clusters shall be controlled by tls.
Parameters
[in] oc The options that steer the guessing process
Definition at line 910 of file NBNodeCont.cpp.
References OptionsCont::exists(), generateNodeClusters(), NBNode::geometryLike(), StringBijection< T >::get(), OptionsCont::getBool(), NBNode::getControllingTLS(), OptionsCont::getFloat(), NBEdge::getFromNode(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::getLength(), OptionsCont::getOptions(), NBNode::getOutgoingEdges(), NBEdge::getSignalOffset(), OptionsCont::getStringVector(), NBEdge::getToNode(), NBTrafficLightLogicCont::insert(), NBNode::isNearDistrict(), OptionsCont::isSet(), NBNode::isTLControlled(), myNodes, NODETYPE_PRIORITY, NBTrafficLightLogicCont::removeFully(), NBNode::removeTrafficLights(), retrieve(), setAsTLControlled(), shouldBeTLSControlled(), TLTYPE_STATIC, toString(), SUMOXMLDefinitions::TrafficLightTypes, NBEdge::UNSPECIFIED_SIGNAL_OFFSET, and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
insert() [1/2]
bool NBNodeCont::insert (const std::string & id, const Position & position, NBDistrict * district = 0)
Inserts a node into the map.
Parameters
[in] id The node's id
[in] position The node's position
[in] A district assigned to the node
Returns
Whether the node could be added (no other with the same id or position is stored)
Definition at line 79 of file NBNodeCont.cpp.
References NamedRTree::Insert(), myNodes, myRTree, Position::x(), and Position::y().
Referenced by NIImporter_SUMO::addJunction(), NIImporter_VISUM::buildDistrictNode(), NIVissimEdge::buildNBEdge(), NIVissimNodeCluster::buildNBNode(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), NIVissimEdge::getFromNode(), NIImporter_OpenDrive::getOrBuildNode(), NIVissimEdge::getToNode(), GNENet::insertJunction(), NIImporter_OpenStreetMap::insertNodeChecking(), joinNodeClusters(), NIImporter_ArcView::load(), NIImporter_OpenDrive::loadNetwork(), NIImporter_RobocupRescue::loadNodes(), NIXMLEdgesHandler::myEndElement(), NIImporter_ITSUMO::Handler::myEndElement(), NIImporter_MATSim::NodesHandler::myStartElement(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_Nodes(), NIXMLNodesHandler::processNodeType(), NIVissimEdge::remapOneOfNodes(), NIImporter_DlrNavteq::NodesHandler::report(), NIVissimEdge::resolveSameNode(), NBEdge::splitGeometry(), and NGNet::toNB().
insert() [2/2]
bool NBNodeCont::insert (NBNode * node)
Inserts a node into the map.
Parameters
[in] node The node to insert
Returns
Whether the node could be added (no other with the same id or position is stored)
Definition at line 94 of file NBNodeCont.cpp.
References Named::getID(), NBNode::getPosition(), NamedRTree::Insert(), myNodes, myRTree, Position::x(), and Position::y().
joinJunctions()
int NBNodeCont::joinJunctions (double maxDist, NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tlc, NBPTStopCont & sc)
Joins junctions that are very close together.
Definition at line 561 of file NBNodeCont.cpp.
References NBPTStopCont::begin(), NBPTStopCont::end(), generateNodeClusters(), NBEdge::getAngleAtNode(), NBNode::getConnectionTo(), NBEdge::getFromNode(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::getLoadedLength(), OptionsCont::getOptions(), NBNode::getOutgoingEdges(), NBEdge::getPermissions(), NBEdge::getToNode(), joinNodeClusters(), joinToStringSorting(), MIN2(), myJoinExclusions, NBEdgeCont::retrieve(), SVC_PEDESTRIAN, toString(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
joinLoadedClusters()
int NBNodeCont::joinLoadedClusters (NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tlc)
Joins loaded junction clusters (see NIXMLNodesHandler)
Definition at line 537 of file NBNodeCont.cpp.
References joinNodeClusters(), myClusters2Join, retrieve(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
joinNodeClusters()
void NBNodeCont::joinNodeClusters (NodeClusters clusters, NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tlc) private
joins the given node clusters
Definition at line 760 of file NBNodeCont.cpp.
References NBEdge::addLane2LaneConnection(), analyzeCluster(), NBEdge::Lane::connectionsDone, NBEdge::declareConnectionsAsLoaded(), erase(), NBEdgeCont::extract(), NBEdge::getConnections(), NBEdge::getFromNode(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), NBEdge::getToNode(), NBEdge::INIT, insert(), NBTrafficLightLogicCont::insert(), NBEdge::L2L_USER, registerJoinedCluster(), NBEdge::reinitNodes(), retrieve(), and WRITE_WARNING.
Referenced by joinJunctions(), and joinLoadedClusters().
joinSimilarEdges()
void NBNodeCont::joinSimilarEdges (NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tlc)
Joins edges connecting the same nodes.
Parameters
Definition at line 179 of file NBNodeCont.cpp.
References NBEdge::getLoadedLength(), NBEdge::getPermissions(), NBEdge::getSpeed(), NBEdge::isNearEnough2BeJoined2(), NBEdgeCont::joinSameNodeConnectingEdges(), and myNodes.
Referenced by NBNetBuilder::compute(), and end().
joinTLS()
void NBNodeCont::joinTLS (NBTrafficLightLogicCont & tlc, double maxdist)
Builds clusters of tls-controlled junctions and joins the control if possible.
Parameters
Definition at line 1075 of file NBNodeCont.cpp.
References analyzeCluster(), generateNodeClusters(), NBTrafficLightLogicCont::insert(), NBTrafficLightLogicCont::removeFully(), toString(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
markAsSplit()
void NBNodeCont::markAsSplit (const NBNode * node) inline
mark a node as being created form a split
Definition at line 291 of file NBNodeCont.h.
References mySplit, and remapIDs().
Referenced by NIXMLEdgesHandler::myEndElement().
operator=()
NBNodeCont& NBNodeCont::operator= (const NBNodeCont & s) private
invalidated assignment operator
printBuiltNodesStatistics()
void NBNodeCont::printBuiltNodesStatistics () const
Prints statistics about built nodes.
Goes through stored nodes, computes the numbers of unregulated, priority and right-before-left junctions and prints them.
Definition at line 1190 of file NBNodeCont.cpp.
References myNodes, NODETYPE_ALLWAY_STOP, NODETYPE_DEAD_END, NODETYPE_DISTRICT, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED, NODETYPE_UNKNOWN, NODETYPE_ZIPPER, toString(), and WRITE_MESSAGE.
Referenced by NBNetBuilder::compute(), and size().
registerJoinedCluster()
void NBNodeCont::registerJoinedCluster (const std::set< NBNode *> & cluster)
gets all joined clusters (see doc for myClusters2Join)
Definition at line 837 of file NBNodeCont.cpp.
References myJoinedClusters.
Referenced by joinNodeClusters(), GNENet::joinSelectedJunctions(), and size().
remapIDs()
int NBNodeCont::remapIDs (bool numericaIDs, bool reservedIDs)
remap node IDs accoring to options –numerical-ids and –reserved-ids
Definition at line 1301 of file NBNodeCont.cpp.
References TplConvert::_str2long(), getAllNames(), OptionsCont::getBool(), Named::getID(), IDSupplier::getNext(), OptionsCont::getOptions(), NBHelpers::loadPrefixedIDsFomFile(), myNodes, Named::setID(), Parameterised::setParameter(), and SUMO_PARAM_ORIGID.
Referenced by NBNetBuilder::compute(), and markAsSplit().
removeComponents()
void NBNodeCont::removeComponents (NBDistrictCont & dc, NBEdgeCont & ec, const int numKeep)
Checks the network for weak connectivity and removes all but the largest components. The connectivity check is done regardless of edge direction and vclass.
Parameters
Definition at line 312 of file NBNodeCont.cpp.
References NBEdgeCont::begin(), NBEdgeCont::end(), erase(), NBEdgeCont::erase(), NBEdge::getFromNode(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), and NBEdge::getToNode().
Referenced by NBNetBuilder::compute(), and end().
removeIsolatedRoads()
void NBNodeCont::removeIsolatedRoads (NBDistrictCont & dc, NBEdgeCont & ec)
Removes sequences of edges that are not connected with a junction. Simple roads without junctions sometimes remain when converting from OpenStreetMap, but they make no sense. Remaining empty nodes are also deleted.
Parameters
Definition at line 224 of file NBNodeCont.cpp.
References erase(), NBEdgeCont::erase(), NBEdgeCont::getAllNames(), NBEdge::getFromNode(), Named::getID(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), NBEdge::getToNode(), NBEdgeCont::retrieve(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
removeSelfLoops()
void NBNodeCont::removeSelfLoops (NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tc)
Removes self-loop edges (edges where the source and the destination node are the same)
Parameters
Definition at line 167 of file NBNodeCont.cpp.
References myNodes, toString(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
removeUnwishedNodes()
int NBNodeCont::removeUnwishedNodes (NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tlc, NBPTStopCont & sc, NBPTLineCont & lc, NBParkingCont & pc, bool removeGeometryNodes)
Removes "unwished" nodes.
Removes nodes if a) no incoming/outgoing edges exist or b) if the node is a "geometry" node. In the second case, edges that participate at the node will be joined. Whether the node is a geometry node or not, is determined by a call to NBNode::checkIsRemovable. The node is removed from the list of tls-controlled nodes.
Parameters
Definition at line 369 of file NBNodeCont.cpp.
References NBPTLineCont::addEdges2Keep(), NBParkingCont::addEdges2Keep(), NBPTStopCont::addEdges2Keep(), NBEdge::append(), begin(), NBNode::checkIsRemovable(), extract(), NBEdgeCont::extract(), NBNode::getEdges(), NBNode::getEdgesToJoin(), NBNode::getIncomingEdges(), OptionsCont::getOptions(), NBNode::getOutgoingEdges(), OptionsCont::getString(), OptionsCont::getStringVector(), NBEdge::getToNode(), OptionsCont::isSet(), NBHelpers::loadEdgesFromFile(), myNodes, mySplit, NBNode::replaceIncoming(), and NBTrafficLightLogicCont::replaceRemoved().
Referenced by NBNetBuilder::compute(), and end().
rename()
void NBNodeCont::rename (NBNode * node, const std::string & newID)
Renames the node. Throws exception if newID already exists.
Definition at line 1265 of file NBNodeCont.cpp.
References Named::getID(), myNodes, and Named::setID().
Referenced by end(), and GNENet::renameJunction().
retrieve() [1/2]
NBNode * NBNodeCont::retrieve (const std::string & id) const
Returns the node with the given name.
Parameters
[in] id The id of the node to retrieve
Returns
The node with the given id, or 0 if no such node exists
Definition at line 108 of file NBNodeCont.cpp.
References myNodes.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLConnectionsHandler::addCrossing(), addJoinExclusion(), NIXMLNodesHandler::addNode(), NIXMLEdgesHandler::addSplit(), NIVissimDisturbance::addToNode(), NIImporter_VISUM::buildDistrictNode(), NGEdge::buildNBEdge(), NBNetBuilder::compute(), NIXMLNodesHandler::deleteNode(), NIVissimNodeCluster::dict_addDisturbances(), NIVissimDistrictConnection::dict_BuildDistricts(), getFreeID(), NIImporter_VISUM::getNamedNode(), NIImporter_OpenDrive::getOrBuildNode(), guessTLs(), GNENet::initJunctionsAndEdges(), NIImporter_OpenStreetMap::insertNodeChecking(), joinLoadedClusters(), joinNodeClusters(), NIImporter_ArcView::load(), NIImporter_RobocupRescue::loadEdges(), NIImporter_OpenDrive::loadNetwork(), NIImporter_ITSUMO::Handler::myEndElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_VISUM::parse_NodesToTrafficLights(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NIImporter_DlrNavteq::EdgesHandler::report(), NIVissimEdge::resolveSameNode(), NIXMLEdgesHandler::setNodes(), NIImporter_OpenDrive::setNodeSecure(), NBEdge::splitGeometry(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
retrieve() [2/2]
NBNode * NBNodeCont::retrieve (const Position & position, const double offset = 0.) const
Returns the node with the given coordinates.
Parameters
[in] position The position at which the node to retrieve lies
[in] offset An offset which can be applied in the case positions are blurred
Returns
The node at the given position, or 0 if no such node exists
Definition at line 118 of file NBNodeCont.cpp.
References NBNode::getPosition(), myNodes, myRTree, POSITION_EPS, NamedRTree::Search(), Position::x(), and Position::y().
setAsTLControlled()
void NBNodeCont::setAsTLControlled (NBNode * node, NBTrafficLightLogicCont & tlc, TrafficLightType type, std::string id = "")
Sets the given node as being controlled by a tls.
Parameters
[in] node The node that shall be controlled by a tls
[in] tlc The traffic lights control into which the new traffic light definition shall be stored
[in] type The type of the new tls
[in] id The id of the tls to add
Todo:
Recheck exception handling
Definition at line 1121 of file NBNodeCont.cpp.
References Named::getID(), NBTrafficLightLogicCont::insert(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), end(), and guessTLs().
shouldBeTLSControlled()
bool NBNodeCont::shouldBeTLSControlled (const std::set< NBNode *> & c) const private
Returns whethe the given node cluster should be controlled by a tls.
Parameters
[in] c The node cluster
Returns
Whether this node cluster shall be controlled by a tls
Definition at line 882 of file NBNodeCont.cpp.
Referenced by guessTLs().
size()
int NBNodeCont::size () const inline
Returns the number of nodes stored in this container.
Definition at line 243 of file NBNodeCont.h.
References analyzeCluster(), clear(), computeNodeShapes(), getAllNames(), getFreeID(), myNodes, printBuiltNodesStatistics(), and registerJoinedCluster().
Referenced by NILoader::load(), main(), NIImporter_DlrNavteq::NodesHandler::report(), NWWriter_OpenDrive::writeNetwork(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
Field Documentation
myClusters2Join
std::vector<std::set<std::string> > NBNodeCont::myClusters2Join private
loaded sets of node ids to join (cleared after use)
Definition at line 346 of file NBNodeCont.h.
Referenced by addCluster2Join(), and joinLoadedClusters().
myExtractedNodes
std::set<NBNode*> NBNodeCont::myExtractedNodes private
The extracted nodes which are kept for reference.
Definition at line 340 of file NBNodeCont.h.
Referenced by clear(), and extract().
myInternalID
int NBNodeCont::myInternalID private
The running internal id.
Definition at line 331 of file NBNodeCont.h.
myJoined
std::set<std::string> NBNodeCont::myJoined private
ids found in loaded join clusters used for error checking
Definition at line 352 of file NBNodeCont.h.
Referenced by addCluster2Join(), and addJoinExclusion().
myJoinedClusters
std::vector<std::set<std::string> > NBNodeCont::myJoinedClusters private
sets of node ids which were joined
Definition at line 349 of file NBNodeCont.h.
Referenced by getJoinedClusters(), and registerJoinedCluster().
myJoinExclusions
std::set<std::string> NBNodeCont::myJoinExclusions private
set of node ids which should not be joined
Definition at line 343 of file NBNodeCont.h.
Referenced by addCluster2Join(), addJoinExclusion(), and joinJunctions().
myNodes
NodeCont NBNodeCont::myNodes private
The map of names to nodes.
Definition at line 337 of file NBNodeCont.h.
Referenced by avoidOverlap(), begin(), clear(), computeLanes2Lanes(), computeLogics(), computeNodeShapes(), discardTrafficLights(), end(), extract(), generateNodeClusters(), getAllNames(), guessTLs(), insert(), joinSimilarEdges(), printBuiltNodesStatistics(), remapIDs(), removeSelfLoops(), removeUnwishedNodes(), rename(), retrieve(), and size().
myRTree
NamedRTree NBNodeCont::myRTree private
node positions for faster lookup
Definition at line 358 of file NBNodeCont.h.
Referenced by extract(), insert(), and retrieve().
mySplit
std::set<const NBNode*> NBNodeCont::mySplit private
nodes that were created when splitting an edge
Definition at line 355 of file NBNodeCont.h.
Referenced by markAsSplit(), and removeUnwishedNodes().
The documentation for this class was generated from the following files:
NBNodeCont.h
NBNodeCont.cpp