SUMO - Simulation of Urban MObility: ODMatrix Class Reference
ODMatrix Class Reference
An O/D (origin/destination) matrix.
#include <ODMatrix.h>
Data Structures
class cell_by_begin_comparator
Used for sorting the cells by the begin time they describe.
class descending_departure_comperator
Used for sorting vehicles by their departure (latest first)
struct ODVehicle
An internal representation of a single vehicle.
Public Member Functions
bool add (double vehicleNumber, SUMOTime begin, SUMOTime end, const std::string &origin, const std::string &destination, const std::string &vehicleType)
Builds a single cell from the given values, verifying them.
bool add (const std::string &id, const SUMOTime depart, const std::pair< const std::string, const std::string > &od, const std::string &vehicleType)
Adds a single vehicle with departure time.
void applyCurve (const Distribution_Points &ps)
Splits the stored cells dividing them on the given time line.
const std::vector< ODCell * > & getCells ()
double getNumDiscarded () const
Returns the number of discarded vehicles.
double getNumLoaded () const
Returns the number of loaded vehicles.
double getNumWritten () const
Returns the number of written vehicles.
void loadMatrix (OptionsCont &oc)
read a matrix in one of several formats
void loadRoutes (OptionsCont &oc, SUMOSAXHandler &handler)
read SUMO routes
ODMatrix (const ODDistrictCont &dc)
Constructor.
Distribution_Points parseTimeLine (const std::vector< std::string > &def, bool timelineDayInHours)
split the given timeline
void readO (LineReader &lr, double scale, std::string vehType, bool matrixHasVehType)
read a VISUM-matrix with the O Format
void readV (LineReader &lr, double scale, std::string vehType, bool matrixHasVehType)
read a VISUM-matrix with the V Format
void sortByBeginTime ()
void write (SUMOTime begin, const SUMOTime end, OutputDevice &dev, const bool uniform, const bool differSourceSink, const bool noVtype, const std::string &prefix, const bool stepLog, bool pedestrians, bool persontrips)
Writes the vehicles stored in the matrix assigning the sources and sinks.
void writeDefaultAttrs (OutputDevice &dev, const bool noVtype, const ODCell *const cell)
Helper function for flow and trip output writing the depart and arrival attributes.
void writeFlows (const SUMOTime begin, const SUMOTime end, OutputDevice &dev, const bool noVtype, const std::string &prefix, bool asProbability=false)
Writes the flows stored in the matrix.
~ODMatrix ()
Destructor.
Protected Member Functions
void applyCurve (const Distribution_Points &ps, ODCell *cell, std::vector< ODCell *> &newCells)
Splits the given cell dividing it on the given time line and storing the results in the given container.
double computeDeparts (ODCell *cell, int &vehName, std::vector< ODVehicle > &into, const bool uniform, const bool differSourceSink, const std::string &prefix)
Computes the vehicle departs stored in the given cell and saves them in "into".
Private Member Functions
std::string getNextNonCommentLine (LineReader &lr)
ODMatrix (const ODMatrix &s)
invalid copy constructor
ODMatrix & operator= (const ODMatrix &s)
invalid assignment operator
SUMOTime parseSingleTime (const std::string &time)
double readFactor (LineReader &lr, double scale)
std::pair< SUMOTime, SUMOTime > readTime (LineReader &lr)
Private Attributes
std::vector< ODCell * > myContainer
The loaded cells.
const ODDistrictCont & myDistricts
The districts to retrieve sources/sinks from.
std::set< std::string > myMissingDistricts
The missing districts already warned about.
double myNumDiscarded
Number of discarded vehicles.
double myNumLoaded
Number of loaded vehicles.
double myNumWritten
Number of written vehicles.
std::map< const std::pair< const std::string, const std::string >, std::vector< ODCell * > > myShortCut
The loaded cells indexed by origin and destination.
Detailed Description
An O/D (origin/destination) matrix.
This class is the internal representation of a loaded O/D-matrix. Beside being the storage for ODCells, the matrix also contains information about the numbers of loaded, discarded, and written vehicles.
The matrix has a reference to the container of districts stored. This allows to validate added cell descriptions in means that using existing origins/ destinations only is assured.
In addition of being a storage, the matrix is also responsible for writing the results and contains methods for splitting the entries over time.
Definition at line 75 of file ODMatrix.h.
Constructor & Destructor Documentation
ODMatrix() [1/2]
ODMatrix::ODMatrix (const ODDistrictCont & dc)
Constructor.
Parameters
[in] dc The district container to obtain referenced districts from
Definition at line 57 of file ODMatrix.cpp.
Referenced by ODMatrix::descending_departure_comperator::operator()().
~ODMatrix()
ODMatrix::~ODMatrix ()
Destructor.
Definition at line 61 of file ODMatrix.cpp.
References myContainer.
ODMatrix() [2/2]
ODMatrix::ODMatrix (const ODMatrix & s) private
invalid copy constructor
Member Function Documentation
add() [1/2]
bool ODMatrix::add (double vehicleNumber, SUMOTime begin, SUMOTime end, const std::string & origin, const std::string & destination, const std::string & vehicleType)
Builds a single cell from the given values, verifying them.
At first, the number of loaded vehicles (myNoLoaded) is incremented by vehicleNumber.
It is checked whether both the origin and the destination exist within the assigned district container (myDistricts). If one of them is missing, an error is generated, if both, a warning, because in the later case the described flow may lay completely beside the processed area. In both cases the given number of vehicles (vehicleNumber) is added to myNoDiscarded.
If the origin/destination districts are known, a cell is built using the given values. This cell is added to the list of known cells (myContainer).
Parameters
[in] vehicleNumber The number of vehicles to store within the cell
[in] begin The begin of the interval the cell is valid for
[in] end The end of the interval the cell is valid for
[in] origin The origin district to use for the cell's flows
[in] destination The destination district to use for the cell's flows
[in] vehicleType The vehicle type to use for the cell's flows
Returns
whether the cell could be added
Definition at line 70 of file ODMatrix.cpp.
References ODCell::begin, ODCell::destination, ODCell::end, NamedObjectCont< T >::get(), myContainer, myDistricts, myMissingDistricts, myNumDiscarded, myNumLoaded, ODCell::origin, ODDistrict::sinkNumber(), ODDistrict::sourceNumber(), toString(), ODCell::vehicleNumber, ODCell::vehicleType, WRITE_ERROR, and WRITE_WARNING.
Referenced by add(), ROMARouteHandler::myEndElement(), ODAmitranHandler::myStartElement(), readO(), and readV().
add() [2/2]
bool ODMatrix::add (const std::string & id, const SUMOTime depart, const std::pair< const std::string, const std::string > & od, const std::string & vehicleType)
Adds a single vehicle with departure time.
If there is no existing ODCell for the given parameters one is generated using add(...)
Parameters
[in] id The id of the vehicle
[in] depart The departure time of the vehicle
[in] od The origin and destination district to use for the cell's flows
[in] vehicleType The vehicle type to use for the cell's flows
Returns
whether the vehicle could be added
Definition at line 112 of file ODMatrix.cpp.
References add(), ODCell::departures, OptionsCont::getOptions(), myContainer, myMissingDistricts, myNumDiscarded, myNumLoaded, myShortCut, string2time(), and ODCell::vehicleNumber.
applyCurve() [1/2]
void ODMatrix::applyCurve (const Distribution_Points & ps)
Splits the stored cells dividing them on the given time line.
Todo:
Describe
Definition at line 547 of file ODMatrix.cpp.
References myContainer.
Referenced by computeRoutes(), and main().
applyCurve() [2/2]
void ODMatrix::applyCurve (const Distribution_Points & ps, ODCell * cell, std::vector< ODCell *> & newCells) protected
Splits the given cell dividing it on the given time line and storing the results in the given container.
For the given cell, a list of clones is generated. The number of these is equal to the number of "areas" within the given distribution description (time line in this case) and each clone's vehicleNumber is equal to the given cell's vehicle number multiplied with the area's probability. The clones are stored in the given cell vector.
See also
Distribution_Points
Parameters
[in] ps The time line to apply
[in] cell The cell to split
[out] newCells The storage to put generated cells into
Todo:
describe better!!!
Definition at line 531 of file ODMatrix.cpp.
References ODCell::begin, ODCell::destination, ODCell::end, RandomDistributor< T >::getOverallProb(), RandomDistributor< T >::getProbs(), RandomDistributor< T >::getVals(), ODCell::origin, TIME2STEPS, ODCell::vehicleNumber, and ODCell::vehicleType.
computeDeparts()
double ODMatrix::computeDeparts (ODCell * cell, int & vehName, std::vector< ODVehicle > & into, const bool uniform, const bool differSourceSink, const std::string & prefix) protected
Computes the vehicle departs stored in the given cell and saves them in "into".
At first, the number of vehicles to insert is computed using the integer value of the vehicleNumber information from the given cell. In the case vehicleNumber has a fraction, an additional vehicle may be added in the case a chosen random number is lower than this fraction.
If uniform is true, the departure times of the generated vehicles are spread uniformly, otherwise the departure time are chosen randomly from the interval.
The vehicle names are generated by putting the value of vehName after the given prefix. The value of vehName is incremented with each generated vehicle.
The number of left vehicles (the fraction if no additional vehicle was generated) is returned.
Parameters
[in] cell The cell to use
[in,out] vehName An incremented index of the generated vehicle
[out] into The storage to put generated vehicles into
[in] uniform Information whether departure times shallbe uniformly spread or random
[in] differSourceSink whether source and sink shall be different edges
[in] prefix A prefix for the vehicle names
Returns
The number of left vehicles to insert
Definition at line 148 of file ODMatrix.cpp.
References ODCell::begin, ODMatrix::ODVehicle::cell, ODMatrix::ODVehicle::depart, ODCell::destination, ODCell::end, ODMatrix::ODVehicle::from, NamedObjectCont< T >::get(), ODDistrictCont::getRandomSinkFromDistrict(), ODDistrictCont::getRandomSourceFromDistrict(), ODMatrix::ODVehicle::id, myDistricts, ODCell::origin, RandHelper::rand(), ODDistrict::sinkNumber(), ODDistrict::sourceNumber(), ODMatrix::ODVehicle::to, toString(), ODCell::vehicleNumber, and WRITE_WARNING.
Referenced by write().
getCells()
const std::vector<ODCell*>& ODMatrix::getCells () inline
Definition at line 246 of file ODMatrix.h.
References myContainer, and sortByBeginTime().
Referenced by computeRoutes(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), ROMAAssignments::resetFlows(), and ROMAAssignments::sue().
getNextNonCommentLine()
std::string ODMatrix::getNextNonCommentLine (LineReader & lr) private
in the functions readV and readO
Todo:
Describe
Definition at line 342 of file ODMatrix.cpp.
References LineReader::getFileName(), LineReader::good(), LineReader::hasMore(), StringUtils::prune(), and LineReader::readLine().
Referenced by readFactor(), readO(), readTime(), and readV().
getNumDiscarded()
double ODMatrix::getNumDiscarded () const
Returns the number of discarded vehicles.
Returns the value of myNoDiscarded
Returns
The number of discarded vehicles
Definition at line 525 of file ODMatrix.cpp.
References myNumDiscarded.
Referenced by main().
getNumLoaded()
double ODMatrix::getNumLoaded () const
Returns the number of loaded vehicles.
Returns the value of myNoLoaded
Returns
The number of loaded vehicles
Definition at line 513 of file ODMatrix.cpp.
References myNumLoaded.
Referenced by main().
getNumWritten()
double ODMatrix::getNumWritten () const
Returns the number of written vehicles.
Returns the value of myNoWritten
Returns
The number of written vehicles
Definition at line 519 of file ODMatrix.cpp.
References myNumWritten.
Referenced by main().
loadMatrix()
void ODMatrix::loadMatrix (OptionsCont & oc)
read a matrix in one of several formats
Todo:
Describe
Definition at line 560 of file ODMatrix.cpp.
References OptionsCont::getFloat(), OptionsCont::getString(), OptionsCont::getStringVector(), LineReader::good(), FileHelpers::isReadable(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, LineReader::readLine(), readO(), readV(), and XMLSubSys::runParser().
Referenced by main().
loadRoutes()
void ODMatrix::loadRoutes (OptionsCont & oc, SUMOSAXHandler & handler)
read SUMO routes
Todo:
Describe
Definition at line 606 of file ODMatrix.cpp.
References OptionsCont::getStringVector(), FileHelpers::isReadable(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, and XMLSubSys::runParser().
Referenced by main().
operator=()
ODMatrix& ODMatrix::operator= (const ODMatrix & s) private
invalid assignment operator
Referenced by ODMatrix::descending_departure_comperator::operator()().
parseSingleTime()
SUMOTime ODMatrix::parseSingleTime (const std::string & time) private
in the functions readV and readO
Todo:
Describe
Definition at line 354 of file ODMatrix.cpp.
References TplConvert::_2int(), and TIME2STEPS.
Referenced by readTime().
parseTimeLine()
Distribution_Points ODMatrix::parseTimeLine (const std::vector< std::string > & def, bool timelineDayInHours)
split the given timeline
Todo:
Describe
Definition at line 623 of file ODMatrix.cpp.
References TplConvert::_2double(), RandomDistributor< T >::add(), StringTokenizer::next(), StringTokenizer::size(), and toString().
Referenced by computeRoutes(), and main().
readFactor()
double ODMatrix::readFactor (LineReader & lr, double scale) private
in the functions readV and readO
Todo:
Describe
Definition at line 383 of file ODMatrix.cpp.
References TplConvert::_2double(), and getNextNonCommentLine().
Referenced by readO(), and readV().
readO()
void ODMatrix::readO (LineReader & lr, double scale, std::string vehType, bool matrixHasVehType)
read a VISUM-matrix with the O Format
Todo:
Describe
Definition at line 463 of file ODMatrix.cpp.
References TplConvert::_2double(), TplConvert::_2int(), add(), LineReader::getFileName(), getNextNonCommentLine(), LineReader::hasMore(), StringTokenizer::next(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, StringUtils::prune(), readFactor(), readTime(), StringTokenizer::size(), toString(), and StringTokenizer::WHITECHARS.
Referenced by loadMatrix().
readTime()
std::pair< SUMOTime, SUMOTime > ODMatrix::readTime (LineReader & lr) private
in the functions readV and readO
Todo:
Describe
Definition at line 365 of file ODMatrix.cpp.
References getNextNonCommentLine(), StringTokenizer::next(), parseSingleTime(), and StringTokenizer::WHITECHARS.
Referenced by readO(), and readV().
readV()
void ODMatrix::readV (LineReader & lr, double scale, std::string vehType, bool matrixHasVehType)
read a VISUM-matrix with the V Format
Todo:
Describe
Definition at line 395 of file ODMatrix.cpp.
References TplConvert::_2double(), TplConvert::_2int(), add(), LineReader::getFileName(), getNextNonCommentLine(), LineReader::hasMore(), StringTokenizer::hasNext(), StringTokenizer::next(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, StringUtils::prune(), readFactor(), readTime(), and StringTokenizer::WHITECHARS.
Referenced by loadMatrix().
sortByBeginTime()
void ODMatrix::sortByBeginTime ()
Definition at line 648 of file ODMatrix.cpp.
References myContainer.
Referenced by computeRoutes(), getCells(), write(), and writeFlows().
write()
void ODMatrix::write (SUMOTime begin, const SUMOTime end, OutputDevice & dev, const bool uniform, const bool differSourceSink, const bool noVtype, const std::string & prefix, const bool stepLog, bool pedestrians, bool persontrips)
Writes the vehicles stored in the matrix assigning the sources and sinks.
The cells stored in myContainer are sorted, first. Then, for each time step to generate vehicles for, it is checked whether the topmost cell is valid for this time step. If so, vehicles are generated from this cell's description using "computeDeparts" and stored in an internal vector. The pointer is moved and the check is repeated until the current cell is not valid for the current time or no further cells exist.
Then, for the current time step, the internal list of vehicles is sorted and all vehicles that start within this time step are written.
The left fraction of vehicles to insert is saved for each O/D-dependency over time and the number of vehicles to generate is increased as soon as this value is larger than 1, decrementing it.
Parameters
[in] begin The begin time to generate vehicles for
[in] end The end time to generate vehicles for
[in] dev The stream to write the generated vehicle trips to
[in] uniform Information whether departure times shallbe uniformly spread or random
[in] differSourceSink whether source and sink shall be different edges
[in] noVtype Whether vtype information shall not be written
[in] prefix A prefix for the vehicle names
[in] stepLog Whether processed time shall be written
Definition at line 216 of file ODMatrix.cpp.
References OutputDevice::closeTag(), computeDeparts(), DELTA_T, MAX2(), myContainer, myNumWritten, OutputDevice::openTag(), sortByBeginTime(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_DEPART, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_TO, SUMO_TAG_PERSON, SUMO_TAG_PERSONTRIP, SUMO_TAG_TRIP, SUMO_TAG_WALK, time2string(), OutputDevice::writeAttr(), and writeDefaultAttrs().
Referenced by main().
writeDefaultAttrs()
void ODMatrix::writeDefaultAttrs (OutputDevice & dev, const bool noVtype, const ODCell *const cell)
Helper function for flow and trip output writing the depart and arrival attributes.
Parameters
[in] dev The stream to write the generated vehicle trips to
[in] noVtype Whether vtype information shall not be written
[in] cell The OD cell containing the vtype
Definition at line 187 of file ODMatrix.cpp.
References ODCell::destination, OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), ODCell::origin, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_TO_TAZ, SUMO_ATTR_TYPE, ODCell::vehicleType, and OutputDevice::writeAttr().
Referenced by write(), and writeFlows().
writeFlows()
void ODMatrix::writeFlows (const SUMOTime begin, const SUMOTime end, OutputDevice & dev, const bool noVtype, const std::string & prefix, bool asProbability = false)
Writes the flows stored in the matrix.
Parameters
[in] begin The begin time to generate vehicles for
[in] end The end time to generate vehicles for
[in] dev The stream to write the generated vehicle trips to
[in] noVtype Whether vtype information shall not be written
[in] prefix A prefix for the flow names
[in] asProbability Write probability to spawn per second instead of number of vehicles
Definition at line 305 of file ODMatrix.cpp.
References ODCell::begin, OutputDevice::closeTag(), ODCell::end, myContainer, OutputDevice::openTag(), OutputDevice::setPrecision(), sortByBeginTime(), STEPS2TIME, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_NUMBER, SUMO_ATTR_PROB, SUMO_TAG_FLOW, time2string(), toString(), ODCell::vehicleNumber, WRITE_WARNING, OutputDevice::writeAttr(), and writeDefaultAttrs().
Referenced by main().
Field Documentation
myContainer
std::vector<ODCell*> ODMatrix::myContainer private
The loaded cells.
Definition at line 346 of file ODMatrix.h.
Referenced by add(), applyCurve(), getCells(), sortByBeginTime(), write(), writeFlows(), and ~ODMatrix().
myDistricts
const ODDistrictCont& ODMatrix::myDistricts private
The districts to retrieve sources/sinks from.
Definition at line 352 of file ODMatrix.h.
Referenced by add(), and computeDeparts().
myMissingDistricts
std::set<std::string> ODMatrix::myMissingDistricts private
The missing districts already warned about.
Definition at line 355 of file ODMatrix.h.
Referenced by add().
myNumDiscarded
double ODMatrix::myNumDiscarded private
Number of discarded vehicles.
Definition at line 364 of file ODMatrix.h.
Referenced by add(), and getNumDiscarded().
myNumLoaded
double ODMatrix::myNumLoaded private
Number of loaded vehicles.
Definition at line 358 of file ODMatrix.h.
Referenced by add(), and getNumLoaded().
myNumWritten
double ODMatrix::myNumWritten private
Number of written vehicles.
Definition at line 361 of file ODMatrix.h.
Referenced by getNumWritten(), and write().
myShortCut
std::map<const std::pair<const std::string, const std::string>, std::vector<ODCell*> > ODMatrix::myShortCut private
The loaded cells indexed by origin and destination.
Definition at line 349 of file ODMatrix.h.
Referenced by add().
The documentation for this class was generated from the following files:
ODMatrix.h
ODMatrix.cpp