SUMO - Simulation of Urban MObility: GNEPolygonFrame Class Reference
GNEPolygonFrame Class Reference
#include <GNEPolygonFrame.h>
Data Structures
class ShapeAttributes
class ShapeAttributeSingle
Public Types
enum AddShapeResult { ADDSHAPE_SUCCESS, ADDSHAPE_NEWPOINT, ADDSHAPE_INVALID, ADDSHAPE_NOTHING }
FOX-declaration.
Public Member Functions
bool buildPoly (const PositionVector &drawedShape)
build Polygon using values of Fields and drawed shape return true if was sucesfully created
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNEPolygonFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
virtual void hide ()
hide Frame
AddShapeResult processClick (const Position &clickedPosition, GNELane *lane)
process click over Viewnet
void setFrameWidth (int newWidth)
set width of GNEFrame
void show ()
show shape frame and update use selected edges/lanes
~GNEPolygonFrame ()
Destructor.
FOX-callbacks
Called when the user select another shape Type
long onCmdSelectShape (FXObject *, FXSelector, void *)
Static Public Member Functions
static std::string getIdsSelected (const FXList *list)
get list of selecte id's in string format
Protected Member Functions
bool addPOI (const std::map< SumoXMLAttr, std::string > &POIValues)
add POI
bool addPOILane (const std::map< SumoXMLAttr, std::string > &POIValues)
add POILane
bool addPolygon (const std::map< SumoXMLAttr, std::string > &POIValues)
add Polygon
GNEPolygonFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Member Functions
void setParametersOfShape (SumoXMLTag actualShapeType)
set parameters depending of the new shapeType
Private Attributes
SumoXMLTag myActualShapeType
actual shape type selected in the match Box
FXGroupBox * myGroupBoxForMyShapeMatchBox
groupBox for Match Box of shapes
GNEPolygonFrame::ShapeAttributes * myShapeAttributes
shape internal attributes
FXComboBox * myShapeMatchBox
combo box with the list of shape elements
Detailed Description
The Widget for setting internal attributes of shape elements
Definition at line 48 of file GNEPolygonFrame.h.
Member Enumeration Documentation
AddShapeResult
enum GNEPolygonFrame::AddShapeResult
FOX-declaration.
enum with all possible values after try to create an shape using frame
Enumerator
ADDSHAPE_SUCCESS
ADDSHAPE_NEWPOINT
ADDSHAPE_INVALID
ADDSHAPE_NOTHING
Definition at line 55 of file GNEPolygonFrame.h.
Constructor & Destructor Documentation
GNEPolygonFrame() [1/2]
GNEPolygonFrame::GNEPolygonFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 82 of file GNEPolygonFrame.cpp.
References GNEAttributeCarrier::allowedShapeTags(), GUIDesignComboBox, GUIDesignComboBoxNCol, GUIDesignGroupBoxFrame, MID_GNE_ADDITIONALFRAME_SELECTADDITIONALTYPE, SUMO_TAG_POLY, and toString().
~GNEPolygonFrame()
GNEPolygonFrame::~GNEPolygonFrame ()
Destructor.
Definition at line 124 of file GNEPolygonFrame.cpp.
References gSelected, and GUISelectedStorage::remove2Update().
GNEPolygonFrame() [2/2]
GNEPolygonFrame::GNEPolygonFrame () inline protected
FOX needs this.
Definition at line 264 of file GNEPolygonFrame.h.
References addPOI(), addPOILane(), addPolygon(), and setParametersOfShape().
Member Function Documentation
addPOI()
bool GNEPolygonFrame::addPOI (const std::map< SumoXMLAttr, std::string > & POIValues) protected
add POI
Definition at line 331 of file GNEPolygonFrame.cpp.
References GNENet::addPOI(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNE_ATTR_BLOCK_MOVEMENT, GNEFrame::myViewNet, GNEUndoList::p_abort(), GNEUndoList::p_begin(), GNEUndoList::p_end(), RGBColor::parseColor(), GeomConvHelper::parseShapeReporting(), GNENet::retrievePOI(), GNEPOI::setAttribute(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SUMO_TAG_POI, and toString().
Referenced by GNEPolygonFrame(), and processClick().
addPOILane()
bool GNEPolygonFrame::addPOILane (const std::map< SumoXMLAttr, std::string > & POIValues) protected
add POILane
Definition at line 361 of file GNEPolygonFrame.cpp.
References GNENet::addPOI(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNE_ATTR_BLOCK_MOVEMENT, GNEFrame::myViewNet, GNEUndoList::p_abort(), GNEUndoList::p_begin(), GNEUndoList::p_end(), RGBColor::parseColor(), GNENet::retrieveLane(), GNENet::retrievePOILane(), GNEPOILane::setAttribute(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SUMO_TAG_POILANE, and toString().
Referenced by GNEPolygonFrame(), and processClick().
addPolygon()
bool GNEPolygonFrame::addPolygon (const std::map< SumoXMLAttr, std::string > & POIValues) protected
add Polygon
Definition at line 301 of file GNEPolygonFrame.cpp.
References GNENet::addPolygon(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNE_ATTR_BLOCK_MOVEMENT, GNE_ATTR_BLOCK_SHAPE, GNEFrame::myViewNet, GNEUndoList::p_abort(), GNEUndoList::p_begin(), GNEUndoList::p_end(), RGBColor::parseColor(), GeomConvHelper::parseShapeReporting(), GNENet::retrievePolygon(), GNEPoly::setAttribute(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_FILL, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LAYER, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, SUMO_TAG_POLY, and toString().
Referenced by buildPoly(), and GNEPolygonFrame().
buildPoly()
bool GNEPolygonFrame::buildPoly (const PositionVector & drawedShape)
build Polygon using values of Fields and drawed shape return true if was sucesfully created
Note
called when user stop drawing polygon
Definition at line 193 of file GNEPolygonFrame.cpp.
References addPolygon(), GNEPolygonFrame::ShapeAttributes::areValuesValid(), GNENet::generateShapeID(), GNEPolygonFrame::ShapeAttributes::getAttributesAndValues(), GNEViewNet::getNet(), GNE_ATTR_BLOCK_MOVEMENT, GNE_ATTR_BLOCK_SHAPE, GNEFrame::NeteditAttributes::isBlockMovementEnabled(), GNEFrame::NeteditAttributes::isBlockShapeEnabled(), GNEFrame::myNeteditAttributes, myShapeAttributes, GNEFrame::myViewNet, GNEPolygonFrame::ShapeAttributes::showWarningMessage(), SUMO_ATTR_GEO, SUMO_ATTR_ID, SUMO_ATTR_SHAPE, SUMO_TAG_POLY, and toString().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getIdsSelected()
std::string GNEPolygonFrame::getIdsSelected (const FXList * list) static
get list of selecte id's in string format
Definition at line 264 of file GNEPolygonFrame.cpp.
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
hide()
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), and GNEDeleteFrame::removeAttributeCarrier().
onCmdSelectShape()
long GNEPolygonFrame::onCmdSelectShape (FXObject * , FXSelector , void *)
Definition at line 224 of file GNEPolygonFrame.cpp.
References GNEAttributeCarrier::allowedShapeTags(), GNEFrame::DrawingMode::hideDrawingMode(), GNEFrame::NeteditAttributes::hideNeteditAttributes(), myActualShapeType, GNEFrame::myDrawingMode, GNEFrame::myNeteditAttributes, myShapeAttributes, myShapeMatchBox, setParametersOfShape(), GNEFrame::DrawingMode::showDrawingMode(), GNEFrame::NeteditAttributes::showNeteditAttributes(), SUMO_TAG_NOTHING, SUMO_TAG_POLY, and toString().
processClick()
GNEPolygonFrame::AddShapeResult GNEPolygonFrame::processClick (const Position & clickedPosition, GNELane * lane)
process click over Viewnet
Parameters
[in] clickedPosition clicked position over ViewNet
[in] lane clicked lane
Returns
AddShapeStatus with the result of operation
Definition at line 130 of file GNEPolygonFrame.cpp.
References GNEFrame::DrawingMode::addNewPoint(), addPOI(), addPOILane(), ADDSHAPE_INVALID, ADDSHAPE_NEWPOINT, ADDSHAPE_NOTHING, ADDSHAPE_SUCCESS, GNEPolygonFrame::ShapeAttributes::areValuesValid(), GNENet::generateShapeID(), GNEPolygonFrame::ShapeAttributes::getAttributesAndValues(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), GNELane::getShape(), GNE_ATTR_BLOCK_MOVEMENT, GNEFrame::NeteditAttributes::isBlockMovementEnabled(), GNEFrame::DrawingMode::isDrawing(), myActualShapeType, GNEFrame::myDrawingMode, GNEFrame::myNeteditAttributes, myShapeAttributes, GNEFrame::myViewNet, PositionVector::nearest_offset_to_point2D(), GNEViewNet::setStatusBarText(), GNEPolygonFrame::ShapeAttributes::showWarningMessage(), SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, toString(), and WRITE_WARNING.
Referenced by GNEViewNet::onLeftBtnPress().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
setParametersOfShape()
void GNEPolygonFrame::setParametersOfShape (SumoXMLTag actualShapeType) private
set parameters depending of the new shapeType
Definition at line 280 of file GNEPolygonFrame.cpp.
References GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAttributeCarrier::allowedAttributes(), GNEPolygonFrame::ShapeAttributes::clearAttributes(), GNEPolygonFrame::ShapeAttributes::getNumberOfAddedAttributes(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEAttributeCarrier::isUnique(), myActualShapeType, myShapeAttributes, and GNEPolygonFrame::ShapeAttributes::showShapeParameters().
Referenced by GNEPolygonFrame(), and onCmdSelectShape().
show()
void GNEPolygonFrame::show () virtual
show shape frame and update use selected edges/lanes
Reimplemented from GNEFrame.
Definition at line 257 of file GNEPolygonFrame.cpp.
References GNEFrame::show().
Referenced by GNEPolygonFrame::ShapeAttributeSingle::showParameter(), GNEPolygonFrame::ShapeAttributes::showShapeParameters(), and GNEViewNet::updateModeSpecificControls().
Field Documentation
myActualShapeType
SumoXMLTag GNEPolygonFrame::myActualShapeType private
actual shape type selected in the match Box
Definition at line 289 of file GNEPolygonFrame.h.
Referenced by onCmdSelectShape(), processClick(), and setParametersOfShape().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), onCmdSelectShape(), and processClick().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxForMyShapeMatchBox
FXGroupBox* GNEPolygonFrame::myGroupBoxForMyShapeMatchBox private
groupBox for Match Box of shapes
Definition at line 280 of file GNEPolygonFrame.h.
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by buildPoly(), GNEFrame::getNeteditAttributes(), onCmdSelectShape(), and processClick().
myShapeAttributes
GNEPolygonFrame::ShapeAttributes* GNEPolygonFrame::myShapeAttributes private
shape internal attributes
Definition at line 286 of file GNEPolygonFrame.h.
Referenced by buildPoly(), onCmdSelectShape(), processClick(), and setParametersOfShape().
myShapeMatchBox
FXComboBox* GNEPolygonFrame::myShapeMatchBox private
combo box with the list of shape elements
Definition at line 283 of file GNEPolygonFrame.h.
Referenced by onCmdSelectShape().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), addPOI(), addPOILane(), addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNEPolygonFrame.h
GNEPolygonFrame.cpp