SUMO - Simulation of Urban MObility: GUIBaseVehicle::GUIBaseVehiclePopupMenu Class Reference
GUIBaseVehicle::GUIBaseVehiclePopupMenu Class Reference
#include <GUIBaseVehicle.h>
Public Member Functions
GUISUMOAbstractView * getParentView ()
return the real owner of this popup
GUIBaseVehiclePopupMenu (GUIMainWindow &app, GUISUMOAbstractView &parent, GUIGlObject &o, std::map< GUISUMOAbstractView *, int > &additionalVisualizations)
Constructor.
void insertMenuPaneChild (FXMenuPane *child)
Insert a sub-menu pane in this GUIGLObjectPopupMenu.
long onCmdHideAllRoutes (FXObject *, FXSelector, void *)
Called if all routes of the vehicle shall be hidden.
long onCmdHideBestLanes (FXObject *, FXSelector, void *)
Called if the vehicle's best lanes shall be hidden.
long onCmdHideCurrentRoute (FXObject *, FXSelector, void *)
Called if the current route of the vehicle shall be hidden.
long onCmdHideLFLinkItems (FXObject *, FXSelector, void *)
Called if all routes of the vehicle shall be hidden.
long onCmdShowAllRoutes (FXObject *, FXSelector, void *)
Called if all routes of the vehicle shall be shown.
long onCmdShowBestLanes (FXObject *, FXSelector, void *)
Called if the vehicle's best lanes shall be shown.
long onCmdShowCurrentRoute (FXObject *, FXSelector, void *)
Called if the current route of the vehicle shall be shown.
long onCmdShowFoes (FXObject *, FXSelector, void *)
Called when show a vehicles foes.
long onCmdShowLFLinkItems (FXObject *, FXSelector, void *)
Called if all routes of the vehicle shall be shown.
long onCmdStartTrack (FXObject *, FXSelector, void *)
Called if the vehicle shall be tracked.
long onCmdStopTrack (FXObject *, FXSelector, void *)
Called if the current shall not be tracked any longer.
~GUIBaseVehiclePopupMenu ()
Destructor.
FX Calls
Called if the assigned objects shall be centered
long onCmdCenter (FXObject *, FXSelector, void *)
long onCmdCopyName (FXObject *, FXSelector, void *)
Called if the name shall be copied to clipboard.
long onCmdCopyTypedName (FXObject *, FXSelector, void *)
Called if the typed name shall be copied to clipboard.
long onCmdCopyEdgeName (FXObject *, FXSelector, void *)
Called if the edge name shall be copied to clipboard (for lanes only)
long onCmdCopyCursorPosition (FXObject *, FXSelector, void *)
Called if the cursor position shall be copied to clipboard.
long onCmdCopyCursorGeoPosition (FXObject *, FXSelector, void *)
Called if the cursor geo-position shall be copied to clipboard.
long onCmdShowPars (FXObject *, FXSelector, void *)
Called if the parameter of this object shall be shown.
long onCmdShowTypePars (FXObject *, FXSelector, void *)
Called if the type parameter of this object shall be shown.
long onCmdAddSelected (FXObject *, FXSelector, void *)
Called if the object shall be added to the list of selected objects.
long onCmdRemoveSelected (FXObject *, FXSelector, void *)
Called if the object shall be removed from the list of selected objects.
Protected Member Functions
GUIBaseVehiclePopupMenu ()
default constructor needed by FOX
Protected Attributes
std::map< GUISUMOAbstractView *, int > dummy
Needed for parameterless instantiation.
GUIMainWindow * myApplication
The main application.
std::vector< FXMenuPane * > myMenuPanes
vector mit Sub-MenuPanes
Position myNetworkPosition
The position within the network the cursor was above when instanting the popup.
GUIGlObject * myObject
The object that belongs to this popup-menu.
GUISUMOAbstractView * myParent
The parent window.
std::map< GUISUMOAbstractView *, int > & myVehiclesAdditionalVisualizations
Information which additional visualisations are enabled (per view)
Detailed Description
A popup-menu for vehicles. In comparison to the normal popup-menu, this one also allows to trigger further visualisations and to track the vehicle.
Definition at line 231 of file GUIBaseVehicle.h.
Constructor & Destructor Documentation
GUIBaseVehiclePopupMenu() [1/2]
GUIBaseVehicle::GUIBaseVehiclePopupMenu::GUIBaseVehiclePopupMenu (GUIMainWindow & app, GUISUMOAbstractView & parent, GUIGlObject & o, std::map< GUISUMOAbstractView *, int > & additionalVisualizations)
Constructor.
Parameters
[in] app The main window for instantiation of other windows
[in] parent The parent view for changing it
[in] o The object of interest
[in,out] additionalVisualizations Information which additional visualisations are enabled (per view)
Definition at line 149 of file GUIBaseVehicle.cpp.
~GUIBaseVehiclePopupMenu()
GUIBaseVehicle::GUIBaseVehiclePopupMenu::~GUIBaseVehiclePopupMenu ()
Destructor.
Definition at line 156 of file GUIBaseVehicle.cpp.
GUIBaseVehiclePopupMenu() [2/2]
GUIBaseVehicle::GUIBaseVehiclePopupMenu::GUIBaseVehiclePopupMenu () inline protected
default constructor needed by FOX
Definition at line 277 of file GUIBaseVehicle.h.
Member Function Documentation
getParentView()
GUISUMOAbstractView* GUIGLObjectPopupMenu::getParentView () inline inherited
return the real owner of this popup
Definition at line 73 of file GUIGLObjectPopupMenu.h.
References GUIGLObjectPopupMenu::myParent, GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIGLObjectPopupMenu::onCmdShowPars(), and GUIGLObjectPopupMenu::onCmdShowTypePars().
Referenced by GNEInternalLane::onDefault().
insertMenuPaneChild()
void GUIGLObjectPopupMenu::insertMenuPaneChild (FXMenuPane * child) inherited
Insert a sub-menu pane in this GUIGLObjectPopupMenu.
Definition at line 86 of file GUIGLObjectPopupMenu.cpp.
References GUIGLObjectPopupMenu::myMenuPanes.
Referenced by GNELane::getPopUpMenu().
onCmdAddSelected()
long GUIGLObjectPopupMenu::onCmdAddSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be added to the list of selected objects.
Definition at line 166 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISelectedStorage::select().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCenter()
long GUIGLObjectPopupMenu::onCmdCenter (FXObject * , FXSelector , void *) inherited
Definition at line 103 of file GUIGLObjectPopupMenu.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyCursorGeoPosition()
long GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor geo-position shall be copied to clipboard.
Definition at line 140 of file GUIGLObjectPopupMenu.cpp.
References GeoConvHelper::cartesian2geo(), GUIUserIO::copyToClipboard(), GeoConvHelper::getFinal(), gPrecisionGeo, GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, toString(), Position::x(), and Position::y().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyCursorPosition()
long GUIGLObjectPopupMenu::onCmdCopyCursorPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor position shall be copied to clipboard.
Definition at line 133 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, and toString().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyEdgeName()
long GUIGLObjectPopupMenu::onCmdCopyEdgeName (FXObject * , FXSelector , void *) inherited
Called if the edge name shall be copied to clipboard (for lanes only)
Definition at line 125 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getParentName(), GUIGlObject::getType(), GLO_LANE, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyName()
long GUIGLObjectPopupMenu::onCmdCopyName (FXObject * , FXSelector , void *) inherited
Called if the name shall be copied to clipboard.
Definition at line 111 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getMicrosimID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyTypedName()
long GUIGLObjectPopupMenu::onCmdCopyTypedName (FXObject * , FXSelector , void *) inherited
Called if the typed name shall be copied to clipboard.
Definition at line 118 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getFullName(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdHideAllRoutes()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes (FXObject * , FXSelector , void *)
Called if all routes of the vehicle shall be hidden.
Definition at line 169 of file GUIBaseVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::VO_SHOW_ALL_ROUTES.
onCmdHideBestLanes()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes (FXObject * , FXSelector , void *)
Called if the vehicle's best lanes shall be hidden.
Definition at line 203 of file GUIBaseVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::VO_SHOW_BEST_LANES.
onCmdHideCurrentRoute()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute (FXObject * , FXSelector , void *)
Called if the current route of the vehicle shall be hidden.
Definition at line 186 of file GUIBaseVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::VO_SHOW_ROUTE.
onCmdHideLFLinkItems()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems (FXObject * , FXSelector , void *)
Called if all routes of the vehicle shall be hidden.
Definition at line 237 of file GUIBaseVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::VO_SHOW_LFLINKITEMS.
onCmdRemoveSelected()
long GUIGLObjectPopupMenu::onCmdRemoveSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be removed from the list of selected objects.
Definition at line 174 of file GUIGLObjectPopupMenu.cpp.
References GUISelectedStorage::deselect(), GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowAllRoutes()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes (FXObject * , FXSelector , void *)
Called if all routes of the vehicle shall be shown.
Definition at line 160 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIBaseVehicle::VO_SHOW_ALL_ROUTES.
onCmdShowBestLanes()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes (FXObject * , FXSelector , void *)
Called if the vehicle's best lanes shall be shown.
Definition at line 194 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIBaseVehicle::VO_SHOW_BEST_LANES.
onCmdShowCurrentRoute()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute (FXObject * , FXSelector , void *)
Called if the current route of the vehicle shall be shown.
Definition at line 177 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIBaseVehicle::VO_SHOW_ROUTE.
onCmdShowFoes()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes (FXObject * , FXSelector , void *)
Called when show a vehicles foes.
Definition at line 244 of file GUIBaseVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIBaseVehicle::selectBlockingFoes().
onCmdShowLFLinkItems()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems (FXObject * , FXSelector , void *)
Called if all routes of the vehicle shall be shown.
Definition at line 228 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIBaseVehicle::VO_SHOW_LFLINKITEMS.
onCmdShowPars()
long GUIGLObjectPopupMenu::onCmdShowPars (FXObject * , FXSelector , void *) inherited
Called if the parameter of this object shall be shown.
Definition at line 151 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowTypePars()
long GUIGLObjectPopupMenu::onCmdShowTypePars (FXObject * , FXSelector , void *) inherited
Called if the type parameter of this object shall be shown.
Definition at line 159 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getTypeParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdStartTrack()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack (FXObject * , FXSelector , void *)
Called if the vehicle shall be tracked.
Definition at line 211 of file GUIBaseVehicle.cpp.
References GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISUMOAbstractView::startTrack().
onCmdStopTrack()
long GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack (FXObject * , FXSelector , void *)
Called if the current shall not be tracked any longer.
Definition at line 220 of file GUIBaseVehicle.cpp.
References GUIGlObject::getType(), GLO_VEHICLE, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISUMOAbstractView::stopTrack().
Field Documentation
dummy
std::map<GUISUMOAbstractView*, int> GUIBaseVehicle::GUIBaseVehiclePopupMenu::dummy protected
Needed for parameterless instantiation.
Definition at line 273 of file GUIBaseVehicle.h.
myApplication
GUIMainWindow* GUIGLObjectPopupMenu::myApplication protected inherited
The main application.
Definition at line 122 of file GUIGLObjectPopupMenu.h.
Referenced by GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdShowPars(), and GUIGLObjectPopupMenu::onCmdShowTypePars().
myMenuPanes
std::vector<FXMenuPane*> GUIGLObjectPopupMenu::myMenuPanes protected inherited
vector mit Sub-MenuPanes
Definition at line 128 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::insertMenuPaneChild(), and GUIGLObjectPopupMenu::~GUIGLObjectPopupMenu().
myNetworkPosition
Position GUIGLObjectPopupMenu::myNetworkPosition protected inherited
The position within the network the cursor was above when instanting the popup.
Definition at line 125 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), and GUIGLObjectPopupMenu::onCmdCopyCursorPosition().
myObject
GUIGlObject* GUIGLObjectPopupMenu::myObject protected inherited
The object that belongs to this popup-menu.
Definition at line 119 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdAddSelected(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), onCmdHideAllRoutes(), onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), onCmdHideCurrentRoute(), onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), onCmdShowAllRoutes(), onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), onCmdShowCurrentRoute(), onCmdShowFoes(), onCmdShowLFLinkItems(), GUIGLObjectPopupMenu::onCmdShowPars(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIGLObjectPopupMenu::onCmdShowTypePars(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), and GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic().
myParent
GUISUMOAbstractView* GUIGLObjectPopupMenu::myParent protected inherited
The parent window.
Definition at line 116 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::getParentView(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), onCmdHideAllRoutes(), onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), onCmdHideCurrentRoute(), onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), onCmdShowAllRoutes(), onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), onCmdShowCurrentRoute(), onCmdShowFoes(), onCmdShowLFLinkItems(), GUIGLObjectPopupMenu::onCmdShowPars(), GUIGLObjectPopupMenu::onCmdShowTypePars(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), and onCmdStopTrack().
myVehiclesAdditionalVisualizations
std::map<GUISUMOAbstractView*, int>& GUIBaseVehicle::GUIBaseVehiclePopupMenu::myVehiclesAdditionalVisualizations protected
Information which additional visualisations are enabled (per view)
Definition at line 271 of file GUIBaseVehicle.h.
The documentation for this class was generated from the following files:
GUIBaseVehicle.h
GUIBaseVehicle.cpp