SUMO - Simulation of Urban MObility: TraCIServerAPI_MultiEntryExit Class Reference
TraCIServerAPI_MultiEntryExit Class Reference
APIs for getting/setting multi-entry/multi-exit detector values via TraCI.
#include <TraCIServerAPI_MultiEntryExit.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa1: Get MeMeDetector Variable)
Private Member Functions
TraCIServerAPI_MultiEntryExit & operator= (const TraCIServerAPI_MultiEntryExit &s)
invalidated assignment operator
TraCIServerAPI_MultiEntryExit (const TraCIServerAPI_MultiEntryExit &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting multi-entry/multi-exit detector values via TraCI.
Definition at line 46 of file TraCIServerAPI_MultiEntryExit.h.
Constructor & Destructor Documentation
TraCIServerAPI_MultiEntryExit()
TraCIServerAPI_MultiEntryExit::TraCIServerAPI_MultiEntryExit (const TraCIServerAPI_MultiEntryExit & s) private
invalidated copy constructor
Member Function Documentation
operator=()
TraCIServerAPI_MultiEntryExit& TraCIServerAPI_MultiEntryExit::operator= (const TraCIServerAPI_MultiEntryExit & s) private
invalidated assignment operator
processGet()
bool TraCIServerAPI_MultiEntryExit::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa1: Get MeMeDetector Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 43 of file TraCIServerAPI_MultiEntryExit.cpp.
References CMD_GET_MULTIENTRYEXIT_VARIABLE, libsumo::MultiEntryExit::getIDCount(), libsumo::MultiEntryExit::getIDList(), libsumo::MultiEntryExit::getLastStepHaltingNumber(), libsumo::MultiEntryExit::getLastStepMeanSpeed(), libsumo::MultiEntryExit::getLastStepVehicleIDs(), libsumo::MultiEntryExit::getLastStepVehicleNumber(), ID_COUNT, ID_LIST, LAST_STEP_MEAN_SPEED, LAST_STEP_VEHICLE_HALTING_NUMBER, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_MULTIENTRYEXIT_VARIABLE, RTYPE_OK, toHex(), TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRINGLIST, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_MultiEntryExit.h
TraCIServerAPI_MultiEntryExit.cpp