SUMO - Simulation of Urban MObility: MFXEditableTable Class Reference
MFXEditableTable Class Reference
#include <MFXEditableTable.h>
Public Types
enum {
ID_LABELEDIT = FXTable::ID_LAST, ID_EDITEND, ID_NEXTLINE, ID_EDITOR,
ID_TEXT_CHANGED, ID_LAST
}
Public Member Functions
virtual void editCancel ()
virtual void editEnd ()
virtual void editItem (FXTableItem *item, FXint how)
MFXEditableTable (FXComposite *p, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=0, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_MARGIN, FXint pr=DEFAULT_MARGIN, FXint pt=DEFAULT_MARGIN, FXint pb=DEFAULT_MARGIN)
long onAutoScroll (FXObject *o, FXSelector s, void *d)
long onClipboardGained (FXObject *o, FXSelector s, void *d)
long onClipboardLost (FXObject *o, FXSelector s, void *d)
long onClipboardRequest (FXObject *o, FXSelector s, void *d)
long onCmdDeleteColumn (FXObject *o, FXSelector s, void *d)
long onCmdDeleteRow (FXObject *o, FXSelector s, void *d)
long onCmdDeselectAll (FXObject *o, FXSelector s, void *d)
long onCmdExtend (FXObject *o, FXSelector s, void *d)
long onCmdHorzGrid (FXObject *o, FXSelector s, void *d)
long onCmdInsertColumn (FXObject *o, FXSelector s, void *d)
long onCmdInsertRow (FXObject *o, FXSelector s, void *d)
long onCmdMark (FXObject *o, FXSelector s, void *d)
long onCmdMoveBottom (FXObject *o, FXSelector s, void *d)
long onCmdMoveDown (FXObject *o, FXSelector s, void *d)
long onCmdMoveEnd (FXObject *o, FXSelector s, void *d)
long onCmdMoveHome (FXObject *o, FXSelector s, void *d)
long onCmdMoveLeft (FXObject *o, FXSelector s, void *d)
long onCmdMovePageDown (FXObject *o, FXSelector s, void *d)
long onCmdMovePageUp (FXObject *o, FXSelector s, void *d)
long onCmdMoveRight (FXObject *o, FXSelector s, void *d)
long onCmdMoveTop (FXObject *o, FXSelector s, void *d)
long onCmdMoveUp (FXObject *o, FXSelector s, void *d)
long onCmdSelectAll (FXObject *o, FXSelector s, void *d)
long onCmdSelectCell (FXObject *o, FXSelector s, void *d)
long onCmdSelectColumn (FXObject *o, FXSelector s, void *d)
long onCmdSelectColumnIndex (FXObject *o, FXSelector s, void *d)
long onCmdSelectRow (FXObject *o, FXSelector s, void *d)
long onCmdSelectRowIndex (FXObject *o, FXSelector s, void *d)
long onCmdVertGrid (FXObject *o, FXSelector s, void *d)
long onCommand (FXObject *o, FXSelector s, void *d)
long onDoubleClicked (FXObject *o, FXSelector s, void *d)
long onEditEnd (FXObject *, FXSelector, void *)
long onEditFocusOut (FXObject *, FXSelector, void *)
long onEditKeyPress (FXObject *, FXSelector, void *ptr)
long onFocusIn (FXObject *o, FXSelector s, void *d)
long onFocusOut (FXObject *o, FXSelector s, void *d)
long onHScrollerChanged (FXObject *o, FXSelector s, void *d)
long onHScrollerDragged (FXObject *o, FXSelector s, void *d)
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
long onLeftBtnClicked (FXObject *sender, FXSelector sel, void *ptr)
long onLeftBtnPress (FXObject *sender, FXSelector sel, void *ptr)
long onLeftBtnRelease (FXObject *sender, FXSelector sel, void *ptr)
long onRightBtnPress (FXObject *o, FXSelector s, void *d)
long onRightBtnRelease (FXObject *sender, FXSelector sel, void *ptr)
long onSelectionGained (FXObject *o, FXSelector s, void *d)
long onSelectionLost (FXObject *o, FXSelector s, void *d)
long onSelectionRequest (FXObject *o, FXSelector s, void *d)
long onTabKeyPress (FXObject *o, FXSelector s, void *d)
long onTabKeyRelease (FXObject *o, FXSelector s, void *d)
long onTripleClicked (FXObject *o, FXSelector s, void *d)
long onUngrabbed (FXObject *o, FXSelector s, void *d)
long onUpdDeleteColumn (FXObject *o, FXSelector s, void *d)
long onUpdDeleteRow (FXObject *o, FXSelector s, void *d)
long onUpdHorzGrid (FXObject *o, FXSelector s, void *d)
long onUpdVertGrid (FXObject *o, FXSelector s, void *d)
long onVScrollerChanged (FXObject *o, FXSelector s, void *d)
long onVScrollerDragged (FXObject *o, FXSelector s, void *d)
void writeProtectCol (int col, bool val=true)
~MFXEditableTable ()
Protected Member Functions
MFXEditableTable ()
Protected Attributes
FXint myEditedCol
FXTableItem * myEditedItem
FXint myEditedRow
FXTextField * myEditor
FXString myPreviousText
std::set< int > myWriteProtectedCols
Detailed Description
Definition at line 47 of file MFXEditableTable.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_LABELEDIT
ID_EDITEND
ID_NEXTLINE
ID_EDITOR
ID_TEXT_CHANGED
ID_LAST
Definition at line 50 of file MFXEditableTable.h.
Constructor & Destructor Documentation
MFXEditableTable() [1/2]
MFXEditableTable::MFXEditableTable (FXComposite * p, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = 0, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_MARGIN, FXint pr = DEFAULT_MARGIN, FXint pt = DEFAULT_MARGIN, FXint pb = DEFAULT_MARGIN)
Definition at line 108 of file MFXEditableTable.cpp.
~MFXEditableTable()
MFXEditableTable::~MFXEditableTable ()
Definition at line 122 of file MFXEditableTable.cpp.
MFXEditableTable() [2/2]
MFXEditableTable::MFXEditableTable () inline protected
Definition at line 142 of file MFXEditableTable.h.
Member Function Documentation
editCancel()
void MFXEditableTable::editCancel () virtual
Definition at line 250 of file MFXEditableTable.cpp.
References myEditedItem, and myEditor.
Referenced by onEditKeyPress().
editEnd()
void MFXEditableTable::editEnd () virtual
Definition at line 211 of file MFXEditableTable.cpp.
References MFXEditedTableItem::col, ID_EDITEND, ID_TEXT_CHANGED, MFXEditedTableItem::item, myEditedCol, myEditedItem, myEditedRow, myEditor, myPreviousText, and MFXEditedTableItem::row.
Referenced by editItem(), onAutoScroll(), onClipboardGained(), onClipboardLost(), onClipboardRequest(), onCmdDeleteColumn(), onCmdDeleteRow(), onCmdDeselectAll(), onCmdExtend(), onCmdHorzGrid(), onCmdInsertColumn(), onCmdInsertRow(), onCmdMark(), onCmdMoveBottom(), onCmdMoveDown(), onCmdMoveEnd(), onCmdMoveHome(), onCmdMoveLeft(), onCmdMovePageDown(), onCmdMovePageUp(), onCmdMoveRight(), onCmdMoveTop(), onCmdMoveUp(), onCmdSelectAll(), onCmdSelectColumn(), onCmdSelectColumnIndex(), onCmdSelectRow(), onCmdSelectRowIndex(), onCmdVertGrid(), onCommand(), onDoubleClicked(), onEditFocusOut(), onEditKeyPress(), onHScrollerChanged(), onHScrollerDragged(), onLeftBtnClicked(), onLeftBtnPress(), onRightBtnPress(), onTabKeyPress(), onTabKeyRelease(), onTripleClicked(), onUngrabbed(), onUpdDeleteColumn(), onUpdDeleteRow(), onUpdHorzGrid(), onUpdVertGrid(), onVScrollerChanged(), and onVScrollerDragged().
editItem()
void MFXEditableTable::editItem (FXTableItem * item, FXint how) virtual
Definition at line 167 of file MFXEditableTable.cpp.
References editEnd(), myEditedCol, myEditedItem, myEditedRow, myEditor, myPreviousText, and myWriteProtectedCols.
Referenced by onLeftBtnClicked().
onAutoScroll()
long MFXEditableTable::onAutoScroll (FXObject * o, FXSelector s, void * d)
Definition at line 353 of file MFXEditableTable.cpp.
References editEnd().
onClipboardGained()
long MFXEditableTable::onClipboardGained (FXObject * o, FXSelector s, void * d)
Definition at line 430 of file MFXEditableTable.cpp.
References editEnd().
onClipboardLost()
long MFXEditableTable::onClipboardLost (FXObject * o, FXSelector s, void * d)
Definition at line 423 of file MFXEditableTable.cpp.
References editEnd().
onClipboardRequest()
long MFXEditableTable::onClipboardRequest (FXObject * o, FXSelector s, void * d)
Definition at line 437 of file MFXEditableTable.cpp.
References editEnd().
onCmdDeleteColumn()
long MFXEditableTable::onCmdDeleteColumn (FXObject * o, FXSelector s, void * d)
Definition at line 495 of file MFXEditableTable.cpp.
References editEnd().
onCmdDeleteRow()
long MFXEditableTable::onCmdDeleteRow (FXObject * o, FXSelector s, void * d)
Definition at line 511 of file MFXEditableTable.cpp.
References editEnd().
onCmdDeselectAll()
long MFXEditableTable::onCmdDeselectAll (FXObject * o, FXSelector s, void * d)
Definition at line 661 of file MFXEditableTable.cpp.
References editEnd().
onCmdExtend()
long MFXEditableTable::onCmdExtend (FXObject * o, FXSelector s, void * d)
Definition at line 676 of file MFXEditableTable.cpp.
References editEnd().
onCmdHorzGrid()
long MFXEditableTable::onCmdHorzGrid (FXObject * o, FXSelector s, void * d)
Definition at line 481 of file MFXEditableTable.cpp.
References editEnd().
onCmdInsertColumn()
long MFXEditableTable::onCmdInsertColumn (FXObject * o, FXSelector s, void * d)
Definition at line 527 of file MFXEditableTable.cpp.
References editEnd().
onCmdInsertRow()
long MFXEditableTable::onCmdInsertRow (FXObject * o, FXSelector s, void * d)
Definition at line 535 of file MFXEditableTable.cpp.
References editEnd().
onCmdMark()
long MFXEditableTable::onCmdMark (FXObject * o, FXSelector s, void * d)
Definition at line 669 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveBottom()
long MFXEditableTable::onCmdMoveBottom (FXObject * o, FXSelector s, void * d)
Definition at line 593 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveDown()
long MFXEditableTable::onCmdMoveDown (FXObject * o, FXSelector s, void * d)
Definition at line 565 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveEnd()
long MFXEditableTable::onCmdMoveEnd (FXObject * o, FXSelector s, void * d)
Definition at line 579 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveHome()
long MFXEditableTable::onCmdMoveHome (FXObject * o, FXSelector s, void * d)
Definition at line 572 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveLeft()
long MFXEditableTable::onCmdMoveLeft (FXObject * o, FXSelector s, void * d)
Definition at line 544 of file MFXEditableTable.cpp.
References editEnd().
onCmdMovePageDown()
long MFXEditableTable::onCmdMovePageDown (FXObject * o, FXSelector s, void * d)
Definition at line 600 of file MFXEditableTable.cpp.
References editEnd().
onCmdMovePageUp()
long MFXEditableTable::onCmdMovePageUp (FXObject * o, FXSelector s, void * d)
Definition at line 607 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveRight()
long MFXEditableTable::onCmdMoveRight (FXObject * o, FXSelector s, void * d)
Definition at line 551 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveTop()
long MFXEditableTable::onCmdMoveTop (FXObject * o, FXSelector s, void * d)
Definition at line 586 of file MFXEditableTable.cpp.
References editEnd().
onCmdMoveUp()
long MFXEditableTable::onCmdMoveUp (FXObject * o, FXSelector s, void * d)
Definition at line 558 of file MFXEditableTable.cpp.
References editEnd().
onCmdSelectAll()
long MFXEditableTable::onCmdSelectAll (FXObject * o, FXSelector s, void * d)
Definition at line 653 of file MFXEditableTable.cpp.
References editEnd().
onCmdSelectCell()
long MFXEditableTable::onCmdSelectCell (FXObject * o, FXSelector s, void * d)
Definition at line 645 of file MFXEditableTable.cpp.
onCmdSelectColumn()
long MFXEditableTable::onCmdSelectColumn (FXObject * o, FXSelector s, void * d)
Definition at line 630 of file MFXEditableTable.cpp.
References editEnd().
onCmdSelectColumnIndex()
long MFXEditableTable::onCmdSelectColumnIndex (FXObject * o, FXSelector s, void * d)
Definition at line 622 of file MFXEditableTable.cpp.
References editEnd().
onCmdSelectRow()
long MFXEditableTable::onCmdSelectRow (FXObject * o, FXSelector s, void * d)
Definition at line 638 of file MFXEditableTable.cpp.
References editEnd().
onCmdSelectRowIndex()
long MFXEditableTable::onCmdSelectRowIndex (FXObject * o, FXSelector s, void * d)
Definition at line 615 of file MFXEditableTable.cpp.
References editEnd().
onCmdVertGrid()
long MFXEditableTable::onCmdVertGrid (FXObject * o, FXSelector s, void * d)
Definition at line 488 of file MFXEditableTable.cpp.
References editEnd().
onCommand()
long MFXEditableTable::onCommand (FXObject * o, FXSelector s, void * d)
Definition at line 460 of file MFXEditableTable.cpp.
References editEnd().
onDoubleClicked()
long MFXEditableTable::onDoubleClicked (FXObject * o, FXSelector s, void * d)
Definition at line 444 of file MFXEditableTable.cpp.
References editEnd().
onEditEnd()
long MFXEditableTable::onEditEnd (FXObject * , FXSelector , void *)
Definition at line 242 of file MFXEditableTable.cpp.
References myEditedItem.
onEditFocusOut()
long MFXEditableTable::onEditFocusOut (FXObject * , FXSelector , void *)
Definition at line 297 of file MFXEditableTable.cpp.
References editEnd().
onEditKeyPress()
long MFXEditableTable::onEditKeyPress (FXObject * , FXSelector , void * ptr)
Definition at line 262 of file MFXEditableTable.cpp.
References editCancel(), and editEnd().
onFocusIn()
long MFXEditableTable::onFocusIn (FXObject * o, FXSelector s, void * d)
Definition at line 388 of file MFXEditableTable.cpp.
onFocusOut()
long MFXEditableTable::onFocusOut (FXObject * o, FXSelector s, void * d)
Definition at line 395 of file MFXEditableTable.cpp.
onHScrollerChanged()
long MFXEditableTable::onHScrollerChanged (FXObject * o, FXSelector s, void * d)
Definition at line 325 of file MFXEditableTable.cpp.
References editEnd().
onHScrollerDragged()
long MFXEditableTable::onHScrollerDragged (FXObject * o, FXSelector s, void * d)
Definition at line 339 of file MFXEditableTable.cpp.
References editEnd().
onKeyRelease()
long MFXEditableTable::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 285 of file MFXEditableTable.cpp.
onLeftBtnClicked()
long MFXEditableTable::onLeftBtnClicked (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 134 of file MFXEditableTable.cpp.
References editEnd(), editItem(), myEditedCol, myEditedItem, and myEditedRow.
onLeftBtnPress()
long MFXEditableTable::onLeftBtnPress (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 126 of file MFXEditableTable.cpp.
References editEnd().
onLeftBtnRelease()
long MFXEditableTable::onLeftBtnRelease (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 155 of file MFXEditableTable.cpp.
onRightBtnPress()
long MFXEditableTable::onRightBtnPress (FXObject * o, FXSelector s, void * d)
Definition at line 367 of file MFXEditableTable.cpp.
References editEnd().
onRightBtnRelease()
long MFXEditableTable::onRightBtnRelease (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 312 of file MFXEditableTable.cpp.
onSelectionGained()
long MFXEditableTable::onSelectionGained (FXObject * o, FXSelector s, void * d)
Definition at line 409 of file MFXEditableTable.cpp.
onSelectionLost()
long MFXEditableTable::onSelectionLost (FXObject * o, FXSelector s, void * d)
Definition at line 402 of file MFXEditableTable.cpp.
onSelectionRequest()
long MFXEditableTable::onSelectionRequest (FXObject * o, FXSelector s, void * d)
Definition at line 416 of file MFXEditableTable.cpp.
onTabKeyPress()
long MFXEditableTable::onTabKeyPress (FXObject * o, FXSelector s, void * d)
Definition at line 374 of file MFXEditableTable.cpp.
References editEnd().
onTabKeyRelease()
long MFXEditableTable::onTabKeyRelease (FXObject * o, FXSelector s, void * d)
Definition at line 381 of file MFXEditableTable.cpp.
References editEnd().
onTripleClicked()
long MFXEditableTable::onTripleClicked (FXObject * o, FXSelector s, void * d)
Definition at line 452 of file MFXEditableTable.cpp.
References editEnd().
onUngrabbed()
long MFXEditableTable::onUngrabbed (FXObject * o, FXSelector s, void * d)
Definition at line 360 of file MFXEditableTable.cpp.
References editEnd().
onUpdDeleteColumn()
long MFXEditableTable::onUpdDeleteColumn (FXObject * o, FXSelector s, void * d)
Definition at line 503 of file MFXEditableTable.cpp.
References editEnd().
onUpdDeleteRow()
long MFXEditableTable::onUpdDeleteRow (FXObject * o, FXSelector s, void * d)
Definition at line 519 of file MFXEditableTable.cpp.
References editEnd().
onUpdHorzGrid()
long MFXEditableTable::onUpdHorzGrid (FXObject * o, FXSelector s, void * d)
Definition at line 467 of file MFXEditableTable.cpp.
References editEnd().
onUpdVertGrid()
long MFXEditableTable::onUpdVertGrid (FXObject * o, FXSelector s, void * d)
Definition at line 474 of file MFXEditableTable.cpp.
References editEnd().
onVScrollerChanged()
long MFXEditableTable::onVScrollerChanged (FXObject * o, FXSelector s, void * d)
Definition at line 332 of file MFXEditableTable.cpp.
References editEnd().
onVScrollerDragged()
long MFXEditableTable::onVScrollerDragged (FXObject * o, FXSelector s, void * d)
Definition at line 346 of file MFXEditableTable.cpp.
References editEnd().
writeProtectCol()
void MFXEditableTable::writeProtectCol (int col, bool val = true)
Definition at line 683 of file MFXEditableTable.cpp.
References myWriteProtectedCols.
Field Documentation
myEditedCol
FXint MFXEditableTable::myEditedCol protected
Definition at line 137 of file MFXEditableTable.h.
Referenced by editEnd(), editItem(), and onLeftBtnClicked().
myEditedItem
FXTableItem* MFXEditableTable::myEditedItem protected
Definition at line 136 of file MFXEditableTable.h.
Referenced by editCancel(), editEnd(), editItem(), onEditEnd(), and onLeftBtnClicked().
myEditedRow
FXint MFXEditableTable::myEditedRow protected
Definition at line 137 of file MFXEditableTable.h.
Referenced by editEnd(), editItem(), and onLeftBtnClicked().
myEditor
FXTextField* MFXEditableTable::myEditor protected
Definition at line 135 of file MFXEditableTable.h.
Referenced by editCancel(), editEnd(), and editItem().
myPreviousText
FXString MFXEditableTable::myPreviousText protected
Definition at line 139 of file MFXEditableTable.h.
Referenced by editEnd(), and editItem().
myWriteProtectedCols
std::set<int> MFXEditableTable::myWriteProtectedCols protected
Definition at line 138 of file MFXEditableTable.h.
Referenced by editItem(), and writeProtectCol().
The documentation for this class was generated from the following files:
MFXEditableTable.h
MFXEditableTable.cpp