SUMO - Simulation of Urban MObility: AGBus Class Reference
AGBus Class Reference
#include <AGBus.h>
Public Member Functions
AGBus (std::string name, int depTime)
AGBus (int depTime)
int getDeparture ()
std::string getName ()
void print () const
void setName (std::string name)
Private Attributes
int departureTime
std::string name
Detailed Description
Definition at line 42 of file AGBus.h.
Constructor & Destructor Documentation
AGBus() [1/2]
AGBus::AGBus (std::string name, int depTime) inline
Definition at line 44 of file AGBus.h.
AGBus() [2/2]
AGBus::AGBus (int depTime) inline
Definition at line 47 of file AGBus.h.
References getDeparture(), getName(), name, print(), and setName().
Member Function Documentation
getDeparture()
int AGBus::getDeparture ()
Definition at line 47 of file AGBus.cpp.
References departureTime.
Referenced by AGBus().
getName()
std::string AGBus::getName ()
Definition at line 52 of file AGBus.cpp.
References name.
Referenced by AGBus().
print()
void AGBus::print () const
Definition at line 57 of file AGBus.cpp.
References departureTime, and name.
Referenced by AGBus().
setName()
void AGBus::setName (std::string name)
Definition at line 42 of file AGBus.cpp.
References name.
Referenced by AGBus().
Field Documentation
departureTime
int AGBus::departureTime private
Definition at line 56 of file AGBus.h.
Referenced by getDeparture(), and print().
name
std::string AGBus::name private
Definition at line 55 of file AGBus.h.
Referenced by AGBus(), getName(), print(), and setName().
The documentation for this class was generated from the following files:
AGBus.h
AGBus.cpp