SUMO - Simulation of Urban MObility: MSStateHandler Class Reference
MSStateHandler Class Reference
Parser and output filter for routes and vehicles state saving and loading.
#include <MSStateHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime getLastDepart () const
Returns the last loaded depart time.
SUMOTime getTime () const
MSStateHandler (const std::string &file, const SUMOTime offset)
standard constructor
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~MSStateHandler ()
standard destructor
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (double &startPos, double &endPos, const double laneLength, const double minLength, const bool friendlyPos)
check start and end position of a stop
static std::mt19937 * getParsingRNG ()
static void saveState (const std::string &file, SUMOTime step)
Saves the current state.
Protected Member Functions
void addParam (const SUMOSAXAttributes &attrs)
assign arbitrary vehicle parameters
void addPersonTrip (const SUMOSAXAttributes &attrs)
add a routing request for a walking or intermodal person
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
void addWalk (const SUMOSAXAttributes &attrs)
add a fully specified walk
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
void closeContainer ()
Ends the processing of a container.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
void parseWalkPositions (const SUMOSAXAttributes &attrs, const std::string &personID, const MSEdge *fromEdge, const MSEdge *&toEdge, double &departPos, double &arrivalPos, MSStoppingPlace *&bs, const MSTransportable::Stage *const lastStage, bool &ok)
@ brief parse depart- and arrival positions of a walk
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int element)
Called when a closing tag occurs.
Protected Attributes
MSTransportable::MSTransportablePlan * myActiveContainerPlan
The plan of the current container.
MSTransportable::MSTransportablePlan * myActivePlan
The plan of the current person.
ConstMSEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
double myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
bool myAmLoadingState
whether a state file is being loaded
SUMOTime myBeginDefault
The default value for flow begins.
double myCurrentCosts
The currently parsed route costs.
RandomDistributor< const MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route)
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
SumoXMLTag myDefaultCFModel
the default car following model
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
IDSupplier myIdSupplier
generates numerical ids
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
SUMOTime myLastDepart
The insertion time of the vehicle read last.
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
Static Protected Attributes
static std::mt19937 myParsingRNG
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Private Member Functions
MSStateHandler (const MSStateHandler &s)
Invalidated copy constructor.
MSStateHandler & operator= (const MSStateHandler &s)
Invalidated assignment operator.
Private Attributes
SUMOSAXAttributes * myAttrs
cached attrs (used when loading vehicles)
std::vector< SUMOSAXAttributes * > myDeviceAttrs
cached device attrs (used when loading vehicles)
std::pair< int, int > myEdgeAndLane
Parameterised * myLastParameterised
the last object that potentially carries parameters
const SUMOTime myOffset
int myQueIndex
MESegment * mySegment
SUMOTime myTime
std::set< std::string > myVehiclesToRemove
vehicles that shall be removed when loading state
Detailed Description
Parser and output filter for routes and vehicles state saving and loading.
Definition at line 51 of file MSStateHandler.h.
Constructor & Destructor Documentation
MSStateHandler() [1/2]
MSStateHandler::MSStateHandler (const std::string & file, const SUMOTime offset)
standard constructor
Definition at line 60 of file MSStateHandler.cpp.
References OptionsCont::getOptions(), OptionsCont::getStringVector(), MSRouteHandler::myAmLoadingState, and myVehiclesToRemove.
~MSStateHandler()
MSStateHandler::~MSStateHandler () virtual
standard destructor
Definition at line 73 of file MSStateHandler.cpp.
MSStateHandler() [2/2]
MSStateHandler::MSStateHandler (const MSStateHandler & s) private
Invalidated copy constructor.
Member Function Documentation
addParam()
void SUMORouteHandler::addParam (const SUMOSAXAttributes & attrs) protected inherited
assign arbitrary vehicle parameters
Definition at line 257 of file SUMORouteHandler.cpp.
References SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), SUMORouteHandler::myCurrentVType, SUMORouteHandler::myVehicleParameter, Parameterised::setParameter(), SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::myStartElement().
addPersonTrip()
void MSRouteHandler::addPersonTrip (const SUMOSAXAttributes & attrs) protected virtual inherited
add a routing request for a walking or intermodal person
Implements SUMORouteHandler.
Definition at line 1033 of file MSRouteHandler.cpp.
References MSVehicleControl::addVehicle(), MSVehicleControl::buildVehicle(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_POS_RANDOM, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSEdge::dictionary(), GenericSAXHandler::error(), MSGlobals::gCheckRoutes, MSStoppingPlace::getAccessPos(), OptionsCont::getFloat(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::getOptSUMOTimeReporting(), MSNet::getPedestrianRouter(), MSNet::getStoppingPlace(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSRouteHandler::parseWalkPositions(), RandHelper::rand(), SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DURATION, SUMO_ATTR_FROM, SUMO_ATTR_MODES, SUMO_ATTR_SPEED, SUMO_ATTR_TO, SUMO_ATTR_VTYPES, SUMO_ATTR_WALKFACTOR, SUMO_TAG_BUS_STOP, SVC_BICYCLE, SVC_BUS, SVC_IGNORING, SVC_PASSENGER, toString(), VEHPARS_VTYPE_SET, SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
addStop()
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual inherited
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 826 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MsgHandler::getErrorInstance(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLanes(), SUMOSAXAttributes::getOpt(), MSNet::getStoppingPlace(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::lane, MAX2(), MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::Stop::parkingarea, SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ACTTYPE, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_PARKING_AREA, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
addWalk()
void MSRouteHandler::addWalk (const SUMOSAXAttributes & attrs) protected virtual inherited
add a fully specified walk
Implements SUMORouteHandler.
Definition at line 1175 of file MSRouteHandler.cpp.
References MSRouteHandler::deleteActivePlans(), SUMOVehicleParameter::depart, DEPART_POS_RANDOM, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), MSRouteHandler::parseWalkPositions(), RandHelper::rand(), SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_ROUTE, and SUMO_ATTR_SPEED.
Referenced by MSRouteHandler::getParsingRNG().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
checkLastDepart()
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 75 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
checkStopPos()
bool SUMORouteHandler::checkStopPos (double & startPos, double & endPos, const double laneLength, const double minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 219 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), RORouteHandler::addStop(), RONetHandler::parseAccess(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
closeContainer()
void MSRouteHandler::closeContainer () protected virtual inherited
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 752 of file MSRouteHandler.cpp.
References MSTransportableControl::buildContainer(), SUMORouteHandler::checkLastDepart(), GenericSAXHandler::error(), MSNet::getContainerControl(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closeFlow()
void MSRouteHandler::closeFlow () protected virtual inherited
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 780 of file MSRouteHandler.cpp.
References SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeRoute(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::parametersSet, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, string2time(), VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closePerson()
void MSRouteHandler::closePerson () protected virtual inherited
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 720 of file MSRouteHandler.cpp.
References MSTransportableControl::buildPerson(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::deleteActivePlans(), SUMOVehicleParameter::depart, GenericSAXHandler::error(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myAmLoadingState, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closeRoute()
void MSRouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual inherited
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 469 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), MSNet::getInstance(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, and MSRoute::setCosts().
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
closeRouteDistribution()
void MSRouteHandler::closeRouteDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 586 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::getParsingRNG().
closeVehicle()
void MSStateHandler::closeVehicle () protected virtual
Ends the processing of a vehicle.
Reimplemented from MSRouteHandler.
Definition at line 199 of file MSStateHandler.cpp.
References MSInsertionControl::alreadyDeparted(), MSRouteHandler::closeVehicle(), SUMOVehicleParameter::depart, MSVehicleControl::discountStateLoaded(), SUMOVehicle::getDevice(), SUMOVehicle::getDevices(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), SUMOVehicle::hasDeparted(), SUMOVehicleParameter::id, SUMOVehicle::loadState(), myAttrs, myDeviceAttrs, myOffset, SUMORouteHandler::myVehicleParameter, myVehiclesToRemove, MSMoveReminder::NOTIFICATION_DEPARTED, MSDevice_Routing::notifyEnter(), and SUMO_ATTR_ID.
Referenced by getTime().
closeVehicleTypeDistribution()
void MSRouteHandler::closeVehicleTypeDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 370 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentVTypeDistribution, and MSRouteHandler::myCurrentVTypeDistributionID.
Referenced by MSRouteHandler::getParsingRNG().
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
getFirstDepart()
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 73 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addPersonTrip(), SUMORouteHandler::addStop(), SUMORouteHandler::addWalk(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
getLastDepart()
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 69 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
getParsingRNG()
static std::mt19937* MSRouteHandler::getParsingRNG () inline static inherited
Definition at line 69 of file MSRouteHandler.h.
References MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), MSRouteHandler::myParsingRNG, MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseFromViaTo(), and MSRouteHandler::parseWalkPositions().
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::computeRandomDepartOffset(), MSInsertionControl::determineCandidates(), NLBuilder::init(), and GUILoadThread::run().
getTime()
SUMOTime MSStateHandler::getTime () const inline
Definition at line 65 of file MSStateHandler.h.
References closeVehicle(), myEndElement(), myStartElement(), and myTime.
Referenced by NLBuilder::build().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void MSStateHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from MSRouteHandler.
Definition at line 190 of file MSStateHandler.cpp.
References SUMORouteHandler::myCurrentVType, MSRouteHandler::myEndElement(), myLastParameterised, SUMORouteHandler::myVehicleParameter, and SUMO_TAG_PARAM.
Referenced by getTime().
myStartElement()
void MSStateHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from MSRouteHandler.
Definition at line 105 of file MSStateHandler.cpp.
References TplConvert::_2long(), SUMOSAXAttributes::clone(), SUMOSAXAttributes::get(), MSEdge::getAllEdges(), MESegment::getEdge(), SUMOSAXAttributes::getFloat(), MSNet::getInstance(), MSVehicleTransfer::getInstance(), SUMOSAXAttributes::getInt(), MESegment::getNextSegment(), MSEdge::getNumericalID(), MELoop::getSegmentForEdge(), SUMOSAXAttributes::getString(), MSNet::getVehicleControl(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, SUMOSAXAttributes::hasAttribute(), MSVehicleTransfer::loadState(), MESegment::loadState(), myAttrs, SUMORouteHandler::myCurrentVType, myDeviceAttrs, myEdgeAndLane, myLastParameterised, myOffset, myQueIndex, mySegment, MSRouteHandler::myStartElement(), myTime, SUMORouteHandler::myVehicleParameter, SUMOSAXAttributes::parseStringVector(), Parameterised::setParameter(), MSVehicleControl::setState(), string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_DEPART, SUMO_ATTR_END, SUMO_ATTR_KEY, SUMO_ATTR_NUMBER, SUMO_ATTR_TIME, SUMO_ATTR_VALUE, SUMO_ATTR_VERSION, SUMO_TAG_DELAY, SUMO_TAG_DEVICE, SUMO_TAG_LANE, SUMO_TAG_PARAM, SUMO_TAG_SEGMENT, SUMO_TAG_SNAPSHOT, SUMO_TAG_VEHICLE, SUMO_TAG_VEHICLETRANSFER, SUMO_TAG_VIEWSETTINGS_VEHICLES, SUMO_TAG_VTYPE, VERSION_STRING, and WRITE_WARNING.
Referenced by getTime().
openRoute()
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route for reading
Implements SUMORouteHandler.
Definition at line 390 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
openRouteDistribution()
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 539 of file MSRouteHandler.cpp.
References TplConvert::_2doubleSec(), RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
openVehicleTypeDistribution()
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 348 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, MSRouteHandler::myParsingRNG, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
Referenced by MSRouteHandler::getParsingRNG().
operator=()
MSStateHandler& MSStateHandler::operator= (const MSStateHandler & s) private
Invalidated assignment operator.
parseFromViaTo()
void MSRouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected inherited
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 110 of file MSRouteHandler.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_ROUTE, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
parseStop()
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 271 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parametersSet, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, SUMOSAXAttributes::parseStringSet(), STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_PARKING_AREA, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), and SUMORouteHandler::getFirstDepart().
parseWalkPositions()
void MSRouteHandler::parseWalkPositions (const SUMOSAXAttributes & attrs, const std::string & personID, const MSEdge * fromEdge, const MSEdge *& toEdge, double & departPos, double & arrivalPos, MSStoppingPlace *& bs, const MSTransportable::Stage *const lastStage, bool & ok) protected inherited
@ brief parse depart- and arrival positions of a walk
Definition at line 978 of file MSRouteHandler.cpp.
References SUMOSAXAttributes::get(), MSStoppingPlace::getAccessPos(), MSTransportable::Stage::getArrivalPos(), MSStoppingPlace::getBeginLanePosition(), MSTransportable::Stage::getDestination(), MSTransportable::Stage::getDestinationStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLength(), SUMOSAXAttributes::getOpt(), MSNet::getStoppingPlace(), MSEdge::getToJunction(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myParsingRNG, SUMOVehicleParserHelper::parseWalkPos(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMO_TAG_BUS_STOP, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addWalk(), and MSRouteHandler::getParsingRNG().
registerLastDepart()
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 87 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
saveState()
void MSStateHandler::saveState (const std::string & file, SUMOTime step) static
Saves the current state.
Parameters
[in] file The file to write the state into
Definition at line 78 of file MSStateHandler.cpp.
References OutputDevice::close(), MSRoute::dict_saveState(), MSEdge::dictSize(), MSEdge::getAllEdges(), OutputDevice::getDevice(), MSNet::getInstance(), MSVehicleTransfer::getInstance(), MSNet::getVehicleControl(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, MSVehicleTransfer::saveState(), MSVehicleControl::saveState(), SUMO_ATTR_TIME, SUMO_ATTR_VERSION, SUMO_TAG_SNAPSHOT, time2string(), VERSION_STRING, OutputDevice::writeAttr(), and OutputDevice::writeHeader().
Referenced by TraCIServerAPI_Simulation::processSet(), and MSNet::simulationStep().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myActiveContainerPlan
MSTransportable::MSTransportablePlan* MSRouteHandler::myActiveContainerPlan protected inherited
The plan of the current container.
Definition at line 165 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
myActivePlan
MSTransportable::MSTransportablePlan* MSRouteHandler::myActivePlan protected inherited
The plan of the current person.
Definition at line 162 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closePerson(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
myActiveRoute
ConstMSEdgeVector MSRouteHandler::myActiveRoute protected inherited
The current route.
Definition at line 159 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeRoute(), MSRouteHandler::MSRouteHandler(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), and MSRouteHandler::parseFromViaTo().
myActiveRouteColor
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 174 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteID
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 165 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
myActiveRouteProbability
double SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 171 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteRefID
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 168 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteStops
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 180 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeRoute(), and RORouteHandler::closeRoute().
myAddVehiclesDirectly
bool MSRouteHandler::myAddVehiclesDirectly protected inherited
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 168 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), and MSRouteHandler::closeVehicle().
myAmLoadingState
bool MSRouteHandler::myAmLoadingState protected inherited
whether a state file is being loaded
Definition at line 183 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and MSStateHandler().
myAttrs
SUMOSAXAttributes* MSStateHandler::myAttrs private
cached attrs (used when loading vehicles)
Definition at line 104 of file MSStateHandler.h.
Referenced by closeVehicle(), and myStartElement().
myBeginDefault
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 189 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
myCurrentCosts
double SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 177 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myCurrentRouteDistribution
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution protected inherited
The currently parsed distribution of routes (probability->route)
Definition at line 177 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
myCurrentRouteDistributionID
std::string MSRouteHandler::myCurrentRouteDistributionID protected inherited
The id of the currently parsed route distribution.
Definition at line 180 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
myCurrentVType
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 183 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), myEndElement(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
myCurrentVTypeDistribution
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution protected inherited
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 171 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
myCurrentVTypeDistributionID
std::string MSRouteHandler::myCurrentVTypeDistributionID protected inherited
The id of the currently parsed vehicle type distribution.
Definition at line 174 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), and MSRouteHandler::openVehicleTypeDistribution().
myDefaultCFModel
SumoXMLTag SUMORouteHandler::myDefaultCFModel protected inherited
the default car following model
Definition at line 201 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::MSRouteHandler(), and SUMORouteHandler::myStartElement().
myDeviceAttrs
std::vector<SUMOSAXAttributes*> MSStateHandler::myDeviceAttrs private
cached device attrs (used when loading vehicles)
Definition at line 107 of file MSStateHandler.h.
Referenced by closeVehicle(), and myStartElement().
myEdgeAndLane
std::pair<int, int> MSStateHandler::myEdgeAndLane private
Definition at line 100 of file MSStateHandler.h.
Referenced by myStartElement().
myEndDefault
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 192 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
myFirstDepart
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 195 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
myIdSupplier
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 186 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
myInsertStopEdgesAt
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 198 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
myLastDepart
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 162 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
myLastParameterised
Parameterised* MSStateHandler::myLastParameterised private
the last object that potentially carries parameters
Definition at line 110 of file MSStateHandler.h.
Referenced by myEndElement(), and myStartElement().
myOffset
const SUMOTime MSStateHandler::myOffset private
Definition at line 97 of file MSStateHandler.h.
Referenced by closeVehicle(), and myStartElement().
myParsingRNG
std::mt19937 MSRouteHandler::myParsingRNG static protected inherited
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Definition at line 186 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addWalk(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), and MSRouteHandler::parseWalkPositions().
myQueIndex
int MSStateHandler::myQueIndex private
Definition at line 101 of file MSStateHandler.h.
Referenced by myStartElement().
mySegment
MESegment* MSStateHandler::mySegment private
Definition at line 99 of file MSStateHandler.h.
Referenced by myStartElement().
myTime
SUMOTime MSStateHandler::myTime private
Definition at line 98 of file MSStateHandler.h.
Referenced by getTime(), and myStartElement().
myVehicleParameter
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 159 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSRouteHandler::addPersonTrip(), RORouteHandler::addPersonTrip(), MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::addWalk(), RORouteHandler::addWalk(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), closeVehicle(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), myEndElement(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), myStartElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
myVehiclesToRemove
std::set<std::string> MSStateHandler::myVehiclesToRemove private
vehicles that shall be removed when loading state
Definition at line 113 of file MSStateHandler.h.
Referenced by closeVehicle(), and MSStateHandler().
The documentation for this class was generated from the following files:
MSStateHandler.h
MSStateHandler.cpp