SUMO - Simulation of Urban MObility: GNEEvent_NetworkLoaded Class Reference
GNEEvent_NetworkLoaded Class Reference
#include <GNEEvent_NetworkLoaded.h>
Public Member Functions
GUIEventType getOwnType () const
returns the event type
GNEEvent_NetworkLoaded (GNENet *net, const std::string &file, const std::string &settingsFile, const bool viewportFromRegistry)
constructor
~GNEEvent_NetworkLoaded ()
destructor
Data Fields
std::string myFile
the name of the loaded file
GNENet * myNet
the loaded net
std::string mySettingsFile
the name of the settings file to load
bool myViewportFromRegistry
whether loading viewport from registry
Protected Attributes
GUIEventType myType
the type of the event
Detailed Description
Throw to GUIApplicationWindow from GUILoadThread after a simulation has been loaded or the loading process failed
Definition at line 53 of file GNEEvent_NetworkLoaded.h.
Constructor & Destructor Documentation
GNEEvent_NetworkLoaded()
GNEEvent_NetworkLoaded::GNEEvent_NetworkLoaded (GNENet * net, const std::string & file, const std::string & settingsFile, const bool viewportFromRegistry) inline
constructor
Definition at line 56 of file GNEEvent_NetworkLoaded.h.
~GNEEvent_NetworkLoaded()
GNEEvent_NetworkLoaded::~GNEEvent_NetworkLoaded () inline
destructor
Definition at line 64 of file GNEEvent_NetworkLoaded.h.
Member Function Documentation
getOwnType()
GUIEventType GUIEvent::getOwnType () const inline inherited
returns the event type
Definition at line 83 of file GUIEvent.h.
References GUIEvent::myType.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
Field Documentation
myFile
std::string GNEEvent_NetworkLoaded::myFile
the name of the loaded file
Definition at line 71 of file GNEEvent_NetworkLoaded.h.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded().
myNet
GNENet* GNEEvent_NetworkLoaded::myNet
the loaded net
Definition at line 68 of file GNEEvent_NetworkLoaded.h.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded().
mySettingsFile
std::string GNEEvent_NetworkLoaded::mySettingsFile
the name of the settings file to load
Definition at line 74 of file GNEEvent_NetworkLoaded.h.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded().
myType
GUIEventType GUIEvent::myType protected inherited
the type of the event
Definition at line 98 of file GUIEvent.h.
Referenced by GUIEvent::getOwnType(), and GUIEvent_Message::GUIEvent_Message().
myViewportFromRegistry
bool GNEEvent_NetworkLoaded::myViewportFromRegistry
whether loading viewport from registry
Definition at line 77 of file GNEEvent_NetworkLoaded.h.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded().
The documentation for this class was generated from the following file:
GNEEvent_NetworkLoaded.h