SUMO - Simulation of Urban MObility: NIVissimTL Class Reference
NIVissimTL Class Reference
#include <NIVissimTL.h>
Data Structures
class NIVissimTLSignal
class NIVissimTLSignalGroup
Public Types
typedef std::map< int, SGroupDictType > GroupDictType
typedef std::map< int, NIVissimTLSignalGroup * > SGroupDictType
typedef std::map< int, SSignalDictType > SignalDictType
typedef std::map< int, NIVissimTLSignal * > SSignalDictType
Public Member Functions
int getID () const
std::string getType () const
NIVissimTL (int id, const std::string &type, const std::string &name, SUMOTime absdur, SUMOTime offset)
~NIVissimTL ()
Static Public Member Functions
static void clearDict ()
static bool dict_SetSignals (NBTrafficLightLogicCont &tlc, NBEdgeCont &ec)
static bool dictionary (int id, const std::string &type, const std::string &name, SUMOTime absdur, SUMOTime offset)
static bool dictionary (int id, NIVissimTL *o)
static NIVissimTL * dictionary (int id)
Protected Attributes
SUMOTime myAbsDuration
NIVissimTLSignalGroup * myCurrentGroup
int myID
std::string myName
SUMOTime myOffset
std::string myType
Private Types
typedef std::map< int, NIVissimTL * > DictType
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 56 of file NIVissimTL.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimTL*> NIVissimTL::DictType private
Definition at line 143 of file NIVissimTL.h.
GroupDictType
typedef std::map<int, SGroupDictType> NIVissimTL::GroupDictType
Definition at line 81 of file NIVissimTL.h.
SGroupDictType
typedef std::map<int, NIVissimTLSignalGroup*> NIVissimTL::SGroupDictType
Definition at line 79 of file NIVissimTL.h.
SignalDictType
typedef std::map<int, SSignalDictType> NIVissimTL::SignalDictType
Definition at line 80 of file NIVissimTL.h.
SSignalDictType
typedef std::map<int, NIVissimTLSignal*> NIVissimTL::SSignalDictType
Definition at line 77 of file NIVissimTL.h.
Constructor & Destructor Documentation
NIVissimTL()
NIVissimTL::NIVissimTL (int id, const std::string & type, const std::string & name, SUMOTime absdur, SUMOTime offset)
Definition at line 311 of file NIVissimTL.cpp.
Referenced by dictionary().
~NIVissimTL()
NIVissimTL::~NIVissimTL ()
Definition at line 320 of file NIVissimTL.cpp.
Member Function Documentation
clearDict()
void NIVissimTL::clearDict () static
Definition at line 360 of file NIVissimTL.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dict_SetSignals()
bool NIVissimTL::dict_SetSignals (NBTrafficLightLogicCont & tlc, NBEdgeCont & ec) static
Definition at line 372 of file NIVissimTL.cpp.
References NIVissimTL::NIVissimTLSignalGroup::getGroupsFor(), getID(), NIVissimTL::NIVissimTLSignal::getSignalsFor(), getType(), NBTrafficLightLogicCont::insert(), myAbsDuration, myDict, myID, NBLoadedTLDef::setCycleDuration(), TLTYPE_ACTUATED, TLTYPE_STATIC, WRITE_ERROR, and WRITE_WARNING.
Referenced by NIImporter_Vissim::postLoadBuild().
dictionary() [1/3]
bool NIVissimTL::dictionary (int id, const std::string & type, const std::string & name, SUMOTime absdur, SUMOTime offset) static
Definition at line 327 of file NIVissimTL.cpp.
References NIVissimTL().
Referenced by NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseFixedTime(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), and NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseVAS().
dictionary() [2/3]
bool NIVissimTL::dictionary (int id, NIVissimTL * o) static
Definition at line 339 of file NIVissimTL.cpp.
References myDict.
dictionary() [3/3]
NIVissimTL * NIVissimTL::dictionary (int id) static
Definition at line 350 of file NIVissimTL.cpp.
References myDict.
getID()
int NIVissimTL::getID () const
Definition at line 436 of file NIVissimTL.cpp.
References myID.
Referenced by dict_SetSignals().
getType()
std::string NIVissimTL::getType () const
Definition at line 430 of file NIVissimTL.cpp.
References myType.
Referenced by dict_SetSignals(), and NIVissimSingleTypeParser_Signalgruppendefinition::parse().
Field Documentation
myAbsDuration
SUMOTime NIVissimTL::myAbsDuration protected
Definition at line 138 of file NIVissimTL.h.
Referenced by dict_SetSignals().
myCurrentGroup
NIVissimTLSignalGroup* NIVissimTL::myCurrentGroup protected
Definition at line 140 of file NIVissimTL.h.
myDict
NIVissimTL::DictType NIVissimTL::myDict static private
Definition at line 144 of file NIVissimTL.h.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), clearDict(), dict_SetSignals(), and dictionary().
myID
int NIVissimTL::myID protected
Definition at line 136 of file NIVissimTL.h.
Referenced by dict_SetSignals(), and getID().
myName
std::string NIVissimTL::myName protected
Definition at line 137 of file NIVissimTL.h.
myOffset
SUMOTime NIVissimTL::myOffset protected
Definition at line 139 of file NIVissimTL.h.
myType
std::string NIVissimTL::myType protected
Definition at line 141 of file NIVissimTL.h.
Referenced by getType().
The documentation for this class was generated from the following files:
NIVissimTL.h
NIVissimTL.cpp