SUMO - Simulation of Urban MObility: NIImporter_SUMO::Connection Struct Reference
NIImporter_SUMO::Connection Struct Reference
A connection description.
Public Member Functions
void clearParameter ()
Clears the parameter map.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Data Fields
double contPos
custom position for internal junction on this connection
PositionVector customShape
custom shape connection
bool keepClear
Whether the junction must be kept clear coming from this connection.
bool mayDefinitelyPass
Information about being definitely free to drive (on-ramps)
double speed
custom speed for connection
std::string tlID
The id of the traffic light that controls this connection.
int tlLinkNo
The index of this connection within the controlling traffic light.
std::string toEdgeID
The id of the target edge.
int toLaneIdx
The index of the target lane.
double visibility
custom foe visibility for connection
Detailed Description
A connection description.
Definition at line 181 of file NIImporter_SUMO.h.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
contPos
double NIImporter_SUMO::Connection::contPos
custom position for internal junction on this connection
Definition at line 195 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
customShape
PositionVector NIImporter_SUMO::Connection::customShape
custom shape connection
Definition at line 201 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
keepClear
bool NIImporter_SUMO::Connection::keepClear
Whether the junction must be kept clear coming from this connection.
Definition at line 193 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
mayDefinitelyPass
bool NIImporter_SUMO::Connection::mayDefinitelyPass
Information about being definitely free to drive (on-ramps)
Definition at line 191 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
speed
double NIImporter_SUMO::Connection::speed
custom speed for connection
Definition at line 199 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
tlID
std::string NIImporter_SUMO::Connection::tlID
The id of the traffic light that controls this connection.
Definition at line 187 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
tlLinkNo
int NIImporter_SUMO::Connection::tlLinkNo
The index of this connection within the controlling traffic light.
Definition at line 189 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
toEdgeID
std::string NIImporter_SUMO::Connection::toEdgeID
The id of the target edge.
Definition at line 183 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
toLaneIdx
int NIImporter_SUMO::Connection::toLaneIdx
The index of the target lane.
Definition at line 185 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
visibility
double NIImporter_SUMO::Connection::visibility
custom foe visibility for connection
Definition at line 197 of file NIImporter_SUMO.h.
Referenced by NIImporter_SUMO::_loadNetwork(), and NIImporter_SUMO::addConnection().
The documentation for this struct was generated from the following file:
NIImporter_SUMO.h