SUMO - Simulation of Urban MObility: GUIPolygon.cpp File Reference
GUIPolygon.cpp File Reference
#include <config.h>
#include <string>
#include "GUIPolygon.h"
#include <utils/gui/images/GUITexturesHelper.h>
#include <utils/gui/globjects/GUIGlObject.h>
#include <utils/gui/div/GUIParameterTableWindow.h>
#include <utils/gui/globjects/GUIGLObjectPopupMenu.h>
#include <utils/gui/settings/GUIVisualizationSettings.h>
#include <utils/gui/div/GUIGlobalSelection.h>
#include <utils/gui/div/GLHelper.h>
Functions
void APIENTRY beginCallback (GLenum which)
void APIENTRY combineCallback (GLdouble coords[3], GLdouble *vertex_data[4], GLfloat weight[4], GLdouble **dataOut)
void APIENTRY endCallback (void)
void APIENTRY errorCallback (GLenum errorCode)
void APIENTRY vertexCallback (GLvoid *vertex)
Variables
GLfloat INV_POLY_TEX_DIM = 1.0 / 256.0
GLfloat xPlane [] = {INV_POLY_TEX_DIM, 0.0, 0.0, 0.0}
GLfloat yPlane [] = {0.0, INV_POLY_TEX_DIM, 0.0, 0.0}
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Laura Bieker
Date
June 2006
Version
$Id$
Definition in file GUIPolygon.cpp.
Function Documentation
beginCallback()
void APIENTRY beginCallback (GLenum which)
Definition at line 101 of file GUIPolygon.cpp.
Referenced by GUIPolygon::performTesselation().
combineCallback()
void APIENTRY combineCallback (GLdouble coords[3], GLdouble * vertex_data[4], GLfloat weight[4], GLdouble ** dataOut)
Definition at line 121 of file GUIPolygon.cpp.
References UNUSED_PARAMETER.
Referenced by GUIPolygon::performTesselation().
endCallback()
void APIENTRY endCallback (void)
Definition at line 113 of file GUIPolygon.cpp.
Referenced by GUIPolygon::performTesselation().
errorCallback()
void APIENTRY errorCallback (GLenum errorCode)
Definition at line 105 of file GUIPolygon.cpp.
vertexCallback()
void APIENTRY vertexCallback (GLvoid * vertex)
Definition at line 117 of file GUIPolygon.cpp.
Variable Documentation
INV_POLY_TEX_DIM
GLfloat INV_POLY_TEX_DIM = 1.0 / 256.0
Definition at line 137 of file GUIPolygon.cpp.
xPlane
GLfloat xPlane[] = {INV_POLY_TEX_DIM, 0.0, 0.0, 0.0}
Definition at line 138 of file GUIPolygon.cpp.
Referenced by GUIPolygon::drawGL().
yPlane
GLfloat yPlane[] = {0.0, INV_POLY_TEX_DIM, 0.0, 0.0}
Definition at line 139 of file GUIPolygon.cpp.
Referenced by GUIPolygon::drawGL().