SUMO - Simulation of Urban MObility: NIVissimConnection Class Reference
NIVissimConnection Class Reference
#include <NIVissimConnection.h>
Public Member Functions
void addDisturbance (int disturbance)
int buildEdgeConnections (NBEdgeCont &ec)
void buildGeom ()
bool clustered () const
void computeBounding ()
bool crosses (const AbstractPoly &poly, double offset=0) const
bool crossesEdge (NIVissimAbstractEdge *c) const
Position crossesEdgeAtPoint (NIVissimAbstractEdge *c) const
const Boundary & getBoundary () const
const Boundary & getBoundingBox () const
const std::vector< int > & getDisturbances () const
int getFromEdgeID () const
Position getFromGeomPosition () const
const std::vector< int > & getFromLanes () const
double getFromPosition () const
const PositionVector & getGeometry () const
Position getGeomPosition (double pos) const
int getID () const
int getToEdgeID () const
Position getToGeomPosition () const
const std::vector< int > & getToLanes () const
double getToPosition () const
bool hasNodeCluster () const
void inCluster (int id)
NIVissimConnection (int id, const std::string &name, const NIVissimExtendedEdgePoint &from_def, const NIVissimExtendedEdgePoint &to_def, const PositionVector &geom, const std::vector< int > &assignedVehicles, const NIVissimClosedLanesVector &clv)
bool overlapsWith (const AbstractPoly &p, double offset=0.0) const
void recheckLanes (const NBEdge *const fromEdge, const NBEdge *const toEdge)
Resets lane numbers if all lanes shall be used.
void setNodeCluster (int nodeid)
void splitAssigning ()
virtual ~NIVissimConnection ()
Static Public Member Functions
static void buildNodeClusters ()
static void clearDict ()
static void closeLoading ()
static void dict_assignToEdges ()
static void dict_buildNBEdgeConnections (NBEdgeCont &ec)
static bool dictionary (int id, NIVissimAbstractEdge *e)
static bool dictionary (int id, NIVissimConnection *o)
static NIVissimConnection * dictionary (int id)
static std::vector< int > getForEdge (int edgeid, bool omitNodeAssigned=true)
static int getMaxID ()
static std::vector< int > getWithin (const AbstractPoly &p, double offset=0.0)
static std::vector< int > getWithin (const AbstractPoly &poly)
static void splitAndAssignToNodes ()
Protected Types
typedef std::set< NIVissimBoundedClusterObject * > ContType
Protected Attributes
Boundary * myBoundary
int myClusterID
std::vector< int > myDisturbances
PositionVector myGeom
int myID
int myNode
Private Types
typedef std::map< int, NIVissimConnection * > DictType
Private Attributes
std::vector< int > myAssignedVehicles
NIVissimClosedLanesVector myClosedLanes
NIVissimExtendedEdgePoint myFromDef
std::string myName
NIVissimExtendedEdgePoint myToDef
Static Private Attributes
static DictType myDict
static int myMaxID
Detailed Description
Definition at line 52 of file NIVissimConnection.h.
Member Typedef Documentation
ContType
typedef std::set<NIVissimBoundedClusterObject*> NIVissimBoundedClusterObject::ContType protected inherited
Definition at line 59 of file NIVissimBoundedClusterObject.h.
DictType
typedef std::map<int, NIVissimConnection*> NIVissimConnection::DictType private
Definition at line 115 of file NIVissimConnection.h.
Constructor & Destructor Documentation
NIVissimConnection()
NIVissimConnection::NIVissimConnection (int id, const std::string & name, const NIVissimExtendedEdgePoint & from_def, const NIVissimExtendedEdgePoint & to_def, const PositionVector & geom, const std::vector< int > & assignedVehicles, const NIVissimClosedLanesVector & clv)
Definition at line 65 of file NIVissimConnection.cpp.
~NIVissimConnection()
NIVissimConnection::~NIVissimConnection () virtual
Definition at line 75 of file NIVissimConnection.cpp.
References myClosedLanes.
Member Function Documentation
addDisturbance()
void NIVissimAbstractEdge::addDisturbance (int disturbance) inherited
Definition at line 174 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDisturbances.
buildEdgeConnections()
int NIVissimConnection::buildEdgeConnections (NBEdgeCont & ec)
Definition at line 217 of file NIVissimConnection.cpp.
References NBEdge::addLane2LaneConnection(), NIVissimEdge::dictionary(), NIVissimEdge::getBestIncoming(), NIVissimEdge::getBestOutgoing(), getFromEdgeID(), getFromLanes(), NIVissimAbstractEdge::getID(), Named::getID(), NBEdge::getNumLanes(), getToEdgeID(), getToLanes(), NBEdge::L2L_VALIDATED, recheckLanes(), NBEdgeCont::retrievePossiblySplit(), toString(), NIVissimEdge::wasWithinAJunction(), and WRITE_WARNING.
buildGeom()
void NIVissimConnection::buildGeom () virtual
Implements NIVissimAbstractEdge.
Definition at line 207 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getGeomPosition(), myFromDef, NIVissimAbstractEdge::myGeom, and myToDef.
buildNodeClusters()
void NIVissimConnection::buildNodeClusters () static
Definition at line 106 of file NIVissimConnection.cpp.
References NIVissimBoundedClusterObject::clustered(), NIVissimNodeCluster::dictionary(), getWithin(), NIVissimBoundedClusterObject::myBoundary, myDict, Boundary::xmax(), and Boundary::xmin().
clearDict()
void NIVissimAbstractEdge::clearDict () static inherited
Definition at line 159 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
closeLoading()
void NIVissimBoundedClusterObject::closeLoading () static inherited
Definition at line 69 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
clustered()
bool NIVissimBoundedClusterObject::clustered () const inherited
Definition at line 63 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myClusterID.
Referenced by buildNodeClusters().
computeBounding()
void NIVissimConnection::computeBounding () virtual
Implements NIVissimBoundedClusterObject.
Definition at line 136 of file NIVissimConnection.cpp.
References Boundary::add(), NIVissimExtendedEdgePoint::getGeomPosition(), NIVissimBoundedClusterObject::myBoundary, myFromDef, and myToDef.
crosses()
bool NIVissimBoundedClusterObject::crosses (const AbstractPoly & poly, double offset = 0) const inherited
Definition at line 49 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myBoundary, Boundary::overlapsWith(), Boundary::xmax(), and Boundary::xmin().
crossesEdge()
bool NIVissimAbstractEdge::crossesEdge (NIVissimAbstractEdge * c) const inherited
Definition at line 117 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersects(), and NIVissimAbstractEdge::myGeom.
Referenced by NIVissimNodeCluster::buildNBNode().
crossesEdgeAtPoint()
Position NIVissimAbstractEdge::crossesEdgeAtPoint (NIVissimAbstractEdge * c) const inherited
Definition at line 123 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersectionPosition2D(), and NIVissimAbstractEdge::myGeom.
Referenced by NIVissimDisturbance::addToNode(), and NIVissimNodeCluster::buildNBNode().
dict_assignToEdges()
void NIVissimConnection::dict_assignToEdges () static
Definition at line 312 of file NIVissimConnection.cpp.
References NIVissimEdge::dictionary(), getFromEdgeID(), getToEdgeID(), and myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
dict_buildNBEdgeConnections()
void NIVissimConnection::dict_buildNBEdgeConnections (NBEdgeCont & ec) static
Definition at line 273 of file NIVissimConnection.cpp.
References myDict, and WRITE_WARNING.
Referenced by NIImporter_Vissim::postLoadBuild().
dictionary() [1/3]
bool NIVissimAbstractEdge::dictionary (int id, NIVissimAbstractEdge * e) static inherited
Definition at line 65 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict.
Referenced by NIVissimNodeCluster::buildNBNode(), NIVissimDisturbance::computeBounding(), NIVissimDisturbance::dict_SetDisturbances(), NIVissimExtendedEdgePoint::getGeomPosition(), NIVissimTL::NIVissimTLSignal::getPosition(), and NIVissimAbstractEdge::NIVissimAbstractEdge().
dictionary() [2/3]
bool NIVissimConnection::dictionary (int id, NIVissimConnection * o) static
Definition at line 84 of file NIVissimConnection.cpp.
References myDict.
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), NIVissimDisturbance::addToNode(), NIVissimEdge::buildConnectionClusters(), NIVissimNodeCluster::buildNBNode(), NIVissimEdge::getBestIncoming(), NIVissimEdge::getBestOutgoing(), NIVissimDisturbance::getConnection(), NIVissimEdge::getConnectionTo(), NIVissimConnectionCluster::getDisturbanceParticipators(), NIVissimNodeCluster::getFromNode(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimEdge::getOutgoingConnected(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), NIVissimConnectionCluster::getPositionForEdge(), NIVissimNodeCluster::getToNode(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition::myEndElement(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimEdge::connection_position_sorter::operator()(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), and NIVissimConflictArea::setPriorityRegulation().
dictionary() [3/3]
NIVissimConnection * NIVissimConnection::dictionary (int id) static
Definition at line 96 of file NIVissimConnection.cpp.
References myDict.
getBoundary()
const Boundary & NIVissimBoundedClusterObject::getBoundary () const inherited
Definition at line 77 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myBoundary.
Referenced by NIVissimConnectionCluster::liesOnSameEdgesEnd().
getBoundingBox()
const Boundary & NIVissimConnection::getBoundingBox () const
Definition at line 305 of file NIVissimConnection.cpp.
References NIVissimBoundedClusterObject::myBoundary, Boundary::xmax(), and Boundary::xmin().
Referenced by NIVissimConnectionCluster::NodeSubCluster::add().
getDisturbances()
const std::vector< int > & NIVissimAbstractEdge::getDisturbances () const inherited
Definition at line 180 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDisturbances.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
getForEdge()
std::vector< int > NIVissimConnection::getForEdge (int edgeid, bool omitNodeAssigned = true) static
Definition at line 146 of file NIVissimConnection.cpp.
References myDict.
getFromEdgeID()
int NIVissimConnection::getFromEdgeID () const
Definition at line 163 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getEdgeID(), and myFromDef.
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), NIVissimDisturbance::addToNode(), buildEdgeConnections(), dict_assignToEdges(), NIVissimEdge::dict_checkEdges2Join(), NIVissimDisturbance::getConnection(), NIVissimEdge::getConnectionTo(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getPositionForEdge(), NIVissimNodeCluster::getToNode(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimEdge::connection_position_sorter::operator()(), NIVissimConnectionCluster::recheckEdges(), and NIVissimConflictArea::setPriorityRegulation().
getFromGeomPosition()
Position NIVissimConnection::getFromGeomPosition () const
Definition at line 187 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getGeomPosition(), and myFromDef.
Referenced by NIVissimNodeCluster::buildNBNode(), NIVissimConnectionCluster::recheckEdges(), and NIVissimConnectionCluster::recomputeBoundary().
getFromLanes()
const std::vector< int > & NIVissimConnection::getFromLanes () const
Definition at line 286 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getLanes(), and myFromDef.
Referenced by buildEdgeConnections(), and NIVissimEdge::getOutgoingConnected().
getFromPosition()
double NIVissimConnection::getFromPosition () const
Definition at line 175 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getPosition(), and myFromDef.
Referenced by NIVissimEdge::dict_checkEdges2Join(), NIVissimConnectionCluster::getPositionForEdge(), and NIVissimEdge::connection_position_sorter::operator()().
getGeometry()
const PositionVector & NIVissimAbstractEdge::getGeometry () const inherited
Definition at line 168 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myGeom.
Referenced by NIVissimEdge::dict_checkEdges2Join(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::same_direction_sorter::operator()(), and NIVissimConnectionCluster::recomputeBoundary().
getGeomPosition()
Position NIVissimAbstractEdge::getGeomPosition (double pos) const inherited
Definition at line 87 of file NIVissimAbstractEdge.cpp.
References PositionVector::extrapolate(), PositionVector::length(), NIVissimAbstractEdge::myGeom, and PositionVector::positionAtOffset().
Referenced by NIVissimDistrictConnection::geomPosition().
getID()
int NIVissimAbstractEdge::getID () const inherited
Definition at line 154 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myID.
Referenced by NIVissimDisturbance::addToNode(), buildEdgeConnections(), NIVissimEdge::dict_checkEdges2Join(), NIVissimEdge::getConnectionTo(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), and NIVissimConnectionCluster::removeConnections().
getMaxID()
int NIVissimConnection::getMaxID () static
Definition at line 322 of file NIVissimConnection.cpp.
References myMaxID.
getToEdgeID()
int NIVissimConnection::getToEdgeID () const
Definition at line 169 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getEdgeID(), and myToDef.
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), NIVissimDisturbance::addToNode(), buildEdgeConnections(), NIVissimEdge::checkUnconnectedLaneSpeeds(), dict_assignToEdges(), NIVissimDisturbance::getConnection(), NIVissimEdge::getConnectionTo(), NIVissimNodeCluster::getFromNode(), NIVissimEdge::getOutgoingConnected(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), NIVissimConnectionCluster::getPositionForEdge(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimEdge::propagateOwn(), NIVissimEdge::propagateSpeed(), NIVissimConnectionCluster::recheckEdges(), NIVissimEdge::setDistrictSpeed(), and NIVissimConflictArea::setPriorityRegulation().
getToGeomPosition()
Position NIVissimConnection::getToGeomPosition () const
Definition at line 194 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getGeomPosition(), and myToDef.
Referenced by NIVissimNodeCluster::buildNBNode(), NIVissimConnectionCluster::recheckEdges(), and NIVissimConnectionCluster::recomputeBoundary().
getToLanes()
const std::vector< int > & NIVissimConnection::getToLanes () const
Definition at line 292 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getLanes(), and myToDef.
Referenced by buildEdgeConnections(), NIVissimEdge::checkUnconnectedLaneSpeeds(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimEdge::propagateOwn(), NIVissimEdge::propagateSpeed(), and NIVissimEdge::setDistrictSpeed().
getToPosition()
double NIVissimConnection::getToPosition () const
Definition at line 181 of file NIVissimConnection.cpp.
References NIVissimExtendedEdgePoint::getPosition(), and myToDef.
Referenced by NIVissimConnectionCluster::getPositionForEdge(), and NIVissimEdge::connection_position_sorter::operator()().
getWithin() [1/2]
std::vector< int > NIVissimAbstractEdge::getWithin (const AbstractPoly & p, double offset = 0.0) static inherited
Definition at line 129 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict, NIVissimAbstractEdge::myID, and NIVissimAbstractEdge::overlapsWith().
getWithin() [2/2]
std::vector< int > NIVissimConnection::getWithin (const AbstractPoly & poly) static
Definition at line 124 of file NIVissimConnection.cpp.
References myDict.
Referenced by buildNodeClusters().
hasNodeCluster()
bool NIVissimAbstractEdge::hasNodeCluster () const inherited
Definition at line 148 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myNode.
inCluster()
void NIVissimBoundedClusterObject::inCluster (int id) inherited
Definition at line 57 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myClusterID.
overlapsWith()
bool NIVissimAbstractEdge::overlapsWith (const AbstractPoly & p, double offset = 0.0) const inherited
Definition at line 142 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myGeom, and PositionVector::overlapsWith().
Referenced by NIVissimAbstractEdge::getWithin().
recheckLanes()
void NIVissimConnection::recheckLanes (const NBEdge *const fromEdge, const NBEdge *const toEdge)
Resets lane numbers if all lanes shall be used.
Calls "NIVissimExtendedEdgePoint::recheckLanes" for both used edges.
Parameters
[in] The built from-edge
[in] The built to-edge
Definition at line 298 of file NIVissimConnection.cpp.
References myFromDef, myToDef, and NIVissimExtendedEdgePoint::recheckLanes().
Referenced by buildEdgeConnections().
setNodeCluster()
void NIVissimConnection::setNodeCluster (int nodeid) virtual
Implements NIVissimAbstractEdge.
Definition at line 200 of file NIVissimConnection.cpp.
References NIVissimAbstractEdge::myNode.
splitAndAssignToNodes()
void NIVissimAbstractEdge::splitAndAssignToNodes () static inherited
Definition at line 102 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict, and NIVissimAbstractEdge::splitAssigning().
splitAssigning()
void NIVissimAbstractEdge::splitAssigning () inherited
Definition at line 110 of file NIVissimAbstractEdge.cpp.
Referenced by NIVissimAbstractEdge::splitAndAssignToNodes().
Field Documentation
myAssignedVehicles
std::vector<int> NIVissimConnection::myAssignedVehicles private
Definition at line 112 of file NIVissimConnection.h.
myBoundary
Boundary* NIVissimBoundedClusterObject::myBoundary protected inherited
Definition at line 61 of file NIVissimBoundedClusterObject.h.
Referenced by buildNodeClusters(), NIVissimDisturbance::computeBounding(), computeBounding(), NIVissimBoundedClusterObject::crosses(), NIVissimBoundedClusterObject::getBoundary(), getBoundingBox(), and NIVissimBoundedClusterObject::~NIVissimBoundedClusterObject().
myClosedLanes
NIVissimClosedLanesVector NIVissimConnection::myClosedLanes private
Definition at line 113 of file NIVissimConnection.h.
Referenced by ~NIVissimConnection().
myClusterID
int NIVissimBoundedClusterObject::myClusterID protected inherited
Definition at line 62 of file NIVissimBoundedClusterObject.h.
Referenced by NIVissimBoundedClusterObject::clustered(), and NIVissimBoundedClusterObject::inCluster().
myDict
NIVissimConnection::DictType NIVissimConnection::myDict static private
Definition at line 116 of file NIVissimConnection.h.
Referenced by buildNodeClusters(), dict_assignToEdges(), dict_buildNBEdgeConnections(), dictionary(), getForEdge(), and getWithin().
myDisturbances
std::vector<int> NIVissimAbstractEdge::myDisturbances protected inherited
Definition at line 74 of file NIVissimAbstractEdge.h.
Referenced by NIVissimAbstractEdge::addDisturbance(), and NIVissimAbstractEdge::getDisturbances().
myFromDef
NIVissimExtendedEdgePoint NIVissimConnection::myFromDef private
Definition at line 111 of file NIVissimConnection.h.
Referenced by buildGeom(), computeBounding(), getFromEdgeID(), getFromGeomPosition(), getFromLanes(), getFromPosition(), and recheckLanes().
myGeom
PositionVector NIVissimAbstractEdge::myGeom protected inherited
Definition at line 73 of file NIVissimAbstractEdge.h.
Referenced by buildGeom(), NIVissimEdge::buildNBEdge(), NIVissimAbstractEdge::crossesEdge(), NIVissimAbstractEdge::crossesEdgeAtPoint(), NIVissimEdge::getBegin2D(), NIVissimEdge::getEnd2D(), NIVissimEdge::getFromNode(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getGeomPosition(), NIVissimEdge::getLength(), NIVissimEdge::getToNode(), NIVissimAbstractEdge::NIVissimAbstractEdge(), NIVissimAbstractEdge::overlapsWith(), and NIVissimEdge::resolveSameNode().
myID
int NIVissimAbstractEdge::myID protected inherited
Definition at line 72 of file NIVissimAbstractEdge.h.
Referenced by NIVissimEdge::buildNBEdge(), NIVissimEdge::getFromNode(), NIVissimAbstractEdge::getID(), NIVissimEdge::getToNode(), NIVissimAbstractEdge::getWithin(), NIVissimEdge::NIVissimEdge(), NIVissimEdge::resolveSameNode(), and NIVissimEdge::setDistrictSpeed().
myMaxID
int NIVissimConnection::myMaxID static private
Definition at line 117 of file NIVissimConnection.h.
Referenced by getMaxID().
myName
std::string NIVissimConnection::myName private
Definition at line 110 of file NIVissimConnection.h.
myNode
int NIVissimAbstractEdge::myNode protected inherited
Definition at line 75 of file NIVissimAbstractEdge.h.
Referenced by NIVissimAbstractEdge::hasNodeCluster(), NIVissimEdge::setNodeCluster(), and setNodeCluster().
myToDef
NIVissimExtendedEdgePoint NIVissimConnection::myToDef private
Definition at line 111 of file NIVissimConnection.h.
Referenced by buildGeom(), computeBounding(), getToEdgeID(), getToGeomPosition(), getToLanes(), getToPosition(), and recheckLanes().
The documentation for this class was generated from the following files:
NIVissimConnection.h
NIVissimConnection.cpp