SUMO - Simulation of Urban MObility: GUIEvent_Message Class Reference
GUIEvent_Message Class Reference
#include <GUIEvent_Message.h>
Public Member Functions
const std::string & getMsg () const
Returns the message.
GUIEventType getOwnType () const
returns the event type
GUIEvent_Message (const std::string &msg)
constructor
GUIEvent_Message (MsgHandler::MsgType type, const std::string &msg)
constructor
~GUIEvent_Message ()
destructor
Protected Attributes
std::string myMsg
The message.
GUIEventType myType
the type of the event
Detailed Description
GUIEvent_Message Throw from GUIRunThread to GUIApplicationWindow and then further to all displays after a step has been performed
Definition at line 45 of file GUIEvent_Message.h.
Constructor & Destructor Documentation
GUIEvent_Message() [1/2]
GUIEvent_Message::GUIEvent_Message (const std::string & msg) inline
constructor
Definition at line 48 of file GUIEvent_Message.h.
GUIEvent_Message() [2/2]
GUIEvent_Message::GUIEvent_Message (MsgHandler::MsgType type, const std::string & msg) inline
constructor
Definition at line 53 of file GUIEvent_Message.h.
References EVENT_ERROR_OCCURED, EVENT_MESSAGE_OCCURED, EVENT_WARNING_OCCURED, MsgHandler::MT_ERROR, MsgHandler::MT_MESSAGE, MsgHandler::MT_WARNING, and GUIEvent::myType.
~GUIEvent_Message()
GUIEvent_Message::~GUIEvent_Message () inline
destructor
Definition at line 71 of file GUIEvent_Message.h.
Member Function Documentation
getMsg()
const std::string& GUIEvent_Message::getMsg () const inline
Returns the message.
Definition at line 74 of file GUIEvent_Message.h.
References myMsg.
Referenced by GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
getOwnType()
GUIEventType GUIEvent::getOwnType () const inline inherited
returns the event type
Definition at line 83 of file GUIEvent.h.
References GUIEvent::myType.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
Field Documentation
myMsg
std::string GUIEvent_Message::myMsg protected
The message.
Definition at line 81 of file GUIEvent_Message.h.
Referenced by getMsg().
myType
GUIEventType GUIEvent::myType protected inherited
the type of the event
Definition at line 98 of file GUIEvent.h.
Referenced by GUIEvent::getOwnType(), and GUIEvent_Message().
The documentation for this class was generated from the following file:
GUIEvent_Message.h