SUMO - Simulation of Urban MObility: NIVissimConnectionCluster Class Reference
NIVissimConnectionCluster Class Reference
#include <NIVissimConnectionCluster.h>
Data Structures
class NodeSubCluster
class same_direction_sorter
Public Member Functions
bool around (const Position &p, double offset=0) const
const std::vector< int > & getConnections () const
NIVissimConnection * getIncomingContinuation (NIVissimEdge *e) const
PositionVector getIncomingContinuationGeometry (NIVissimEdge *e) const
NBNode * getNBNode () const
NIVissimConnection * getOutgoingContinuation (NIVissimEdge *e) const
PositionVector getOutgoingContinuationGeometry (NIVissimEdge *e) const
double getPositionForEdge (int edgeid) const
bool hasNodeCluster () const
NIVissimConnectionCluster (const std::vector< int > &connections, int nodeCluster, int edgeid)
Constructor Build the boundary; The boundary includes both incoming and outgoing nodes.
NIVissimConnectionCluster (const std::vector< int > &connections, const Boundary &boundary, int nodeCluster, const std::vector< int > &edges)
bool overlapsWith (NIVissimConnectionCluster *c, double offset=0) const
Returns the information whether the given cluster overlaps the current.
~NIVissimConnectionCluster ()
Destructor.
Static Public Member Functions
static void _debugOut (std::ostream &into)
static void buildNodeClusters ()
static void clearDict ()
static int dictSize ()
static int getNextFreeNodeID ()
static void joinByDisturbances (double offset)
static void joinBySameEdges (double offset)
Tries to joind clusters participating within a node This is done by joining clusters which overlap.
Private Types
typedef std::vector< NIVissimConnectionCluster * > ContType
Private Member Functions
void add (NIVissimConnectionCluster *c)
Adds the second cluster.
std::vector< int > extendByToTreatAsSame (const std::vector< int > &iv1, const std::vector< int > &iv2) const
std::vector< int > getDisturbanceParticipators ()
bool isWeakDistrictConnRealisation (NIVissimConnectionCluster *c2)
bool joinable (NIVissimConnectionCluster *c2, double offset)
bool liesOnSameEdgesEnd (NIVissimConnectionCluster *cc2)
void recheckEdges ()
void recomputeBoundary ()
void removeConnections (const NodeSubCluster &c)
Private Attributes
int myBlaID
Boundary myBoundary
The boundary of the cluster.
std::vector< int > myConnections
List of connection-ids which participate within this cluster.
std::vector< int > myEdges
std::vector< int > myIncomingEdges
int myNodeCluster
The node the cluster is assigned to.
std::vector< int > myNodes
std::vector< int > myOutgoingEdges
std::vector< int > myTLs
Static Private Attributes
static ContType myClusters
static int myFirstFreeID = 100000
static int myStaticBlaID = 0
Friends
class NIVissimEdge
Detailed Description
This class holds a list of connections either all outgoing or all incoming within an edge, which do lies close together. This shall be the connections which belong to a single node. It still are not all of the node's connections, as other edges may participate to this node, too.
Definition at line 59 of file NIVissimConnectionCluster.h.
Member Typedef Documentation
ContType
typedef std::vector<NIVissimConnectionCluster*> NIVissimConnectionCluster::ContType private
Definition at line 194 of file NIVissimConnectionCluster.h.
Constructor & Destructor Documentation
NIVissimConnectionCluster() [1/2]
NIVissimConnectionCluster::NIVissimConnectionCluster (const std::vector< int > & connections, int nodeCluster, int edgeid)
Constructor Build the boundary; The boundary includes both incoming and outgoing nodes.
Definition at line 120 of file NIVissimConnectionCluster.cpp.
References NIVissimConnection::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getToEdgeID(), myClusters, myEdges, myIncomingEdges, myOutgoingEdges, recomputeBoundary(), and VectorHelper< T >::removeDouble().
NIVissimConnectionCluster() [2/2]
NIVissimConnectionCluster::NIVissimConnectionCluster (const std::vector< int > & connections, const Boundary & boundary, int nodeCluster, const std::vector< int > & edges)
Definition at line 143 of file NIVissimConnectionCluster.cpp.
References NIVissimConnection::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getToEdgeID(), myBoundary, myClusters, myIncomingEdges, myOutgoingEdges, recomputeBoundary(), VectorHelper< T >::removeDouble(), Boundary::xmax(), and Boundary::xmin().
~NIVissimConnectionCluster()
NIVissimConnectionCluster::~NIVissimConnectionCluster ()
Destructor.
Definition at line 166 of file NIVissimConnectionCluster.cpp.
Member Function Documentation
_debugOut()
void NIVissimConnectionCluster::_debugOut (std::ostream & into) static
Definition at line 523 of file NIVissimConnectionCluster.cpp.
References myClusters.
Referenced by getConnections().
add()
void NIVissimConnectionCluster::add (NIVissimConnectionCluster * c) private
Adds the second cluster.
Definition at line 186 of file NIVissimConnectionCluster.cpp.
References Boundary::add(), NIVissimEdge::dictionary(), myBoundary, myConnections, myEdges, myIncomingEdges, myNodeCluster, myOutgoingEdges, VectorHelper< T >::removeDouble(), Boundary::xmax(), and Boundary::xmin().
around()
bool NIVissimConnectionCluster::around (const Position & p, double offset = 0) const
Definition at line 589 of file NIVissimConnectionCluster.cpp.
References Boundary::around(), myBoundary, Boundary::xmax(), and Boundary::xmin().
Referenced by NIVissimEdge::getFromNode(), and NIVissimEdge::resolveSameNode().
buildNodeClusters()
void NIVissimConnectionCluster::buildNodeClusters () static
Definition at line 492 of file NIVissimConnectionCluster.cpp.
References NIVissimNodeCluster::dictionary(), NIVissimDisturbance::getWithin(), myClusters, and WRITE_WARNING.
Referenced by getConnections(), and NIImporter_Vissim::postLoadBuild().
clearDict()
void NIVissimConnectionCluster::clearDict () static
Definition at line 695 of file NIVissimConnectionCluster.cpp.
References myClusters, and myFirstFreeID.
Referenced by getConnections(), and NIImporter_Vissim::~NIImporter_Vissim().
dictSize()
int NIVissimConnectionCluster::dictSize () static
Definition at line 546 of file NIVissimConnectionCluster.cpp.
References myClusters.
Referenced by getConnections().
extendByToTreatAsSame()
std::vector< int > NIVissimConnectionCluster::extendByToTreatAsSame (const std::vector< int > & iv1, const std::vector< int > & iv2) const private
Definition at line 460 of file NIVissimConnectionCluster.cpp.
References NIVissimEdge::dictionary(), and NIVissimEdge::getToTreatAsSame().
Referenced by joinable(), and NIVissimConnectionCluster::same_direction_sorter::operator()().
getConnections()
const std::vector<int>& NIVissimConnectionCluster::getConnections () const inline
Definition at line 85 of file NIVissimConnectionCluster.h.
References _debugOut(), buildNodeClusters(), clearDict(), dictSize(), getIncomingContinuation(), getIncomingContinuationGeometry(), getNextFreeNodeID(), getOutgoingContinuation(), getOutgoingContinuationGeometry(), joinByDisturbances(), joinBySameEdges(), and myConnections.
getDisturbanceParticipators()
std::vector< int > NIVissimConnectionCluster::getDisturbanceParticipators () private
Definition at line 476 of file NIVissimConnectionCluster.cpp.
References NIVissimDisturbance::dictionary(), NIVissimConnection::dictionary(), NIVissimDisturbance::getDisturbanceID(), NIVissimAbstractEdge::getDisturbances(), NIVissimDisturbance::getEdgeID(), and myConnections.
Referenced by joinable(), and NIVissimConnectionCluster::same_direction_sorter::operator()().
getIncomingContinuation()
NIVissimConnection * NIVissimConnectionCluster::getIncomingContinuation (NIVissimEdge * e) const
Definition at line 728 of file NIVissimConnectionCluster.cpp.
References PositionVector::beginEndAngle(), NIVissimConnection::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getID(), and myConnections.
Referenced by getConnections().
getIncomingContinuationGeometry()
PositionVector NIVissimConnectionCluster::getIncomingContinuationGeometry (NIVissimEdge * e) const
Definition at line 705 of file NIVissimConnectionCluster.cpp.
References PositionVector::beginEndAngle(), NIVissimConnection::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getID(), and myConnections.
Referenced by getConnections().
getNBNode()
NBNode * NIVissimConnectionCluster::getNBNode () const
Definition at line 583 of file NIVissimConnectionCluster.cpp.
References NIVissimNodeCluster::dictionary(), and myNodeCluster.
Referenced by NIVissimEdge::getFromNode().
getNextFreeNodeID()
int NIVissimConnectionCluster::getNextFreeNodeID () static
Definition at line 171 of file NIVissimConnectionCluster.cpp.
References myFirstFreeID.
Referenced by NIVissimConnectionCluster::NodeSubCluster::getConnectionIDs(), and getConnections().
getOutgoingContinuation()
NIVissimConnection * NIVissimConnectionCluster::getOutgoingContinuation (NIVissimEdge * e) const
Definition at line 772 of file NIVissimConnectionCluster.cpp.
References PositionVector::beginEndAngle(), NIVissimConnection::dictionary(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getID(), NIVissimConnection::getToEdgeID(), and myConnections.
Referenced by getConnections().
getOutgoingContinuationGeometry()
PositionVector NIVissimConnectionCluster::getOutgoingContinuationGeometry (NIVissimEdge * e) const
Definition at line 750 of file NIVissimConnectionCluster.cpp.
References PositionVector::beginEndAngle(), NIVissimConnection::dictionary(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getID(), NIVissimConnection::getToEdgeID(), and myConnections.
Referenced by getConnections().
getPositionForEdge()
double NIVissimConnectionCluster::getPositionForEdge (int edgeid) const
Definition at line 628 of file NIVissimConnectionCluster.cpp.
References GeomHelper::crossPoint(), NIVissimNodeDef::dictionary(), NIVissimConnection::dictionary(), NIVissimEdge::dictionary(), NIVissimNodeDef::getEdgePosition(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getFromPosition(), NIVissimConnection::getToEdgeID(), NIVissimConnection::getToPosition(), myBoundary, myConnections, myEdges, myNodeCluster, GeomHelper::nearest_offset_on_line_to_point2D(), WRITE_WARNING, Boundary::xmax(), and Boundary::xmin().
Referenced by NIVissimEdge::connection_cluster_position_sorter::operator()().
hasNodeCluster()
bool NIVissimConnectionCluster::hasNodeCluster () const
Definition at line 540 of file NIVissimConnectionCluster.cpp.
References myNodeCluster.
Referenced by joinable().
isWeakDistrictConnRealisation()
bool NIVissimConnectionCluster::isWeakDistrictConnRealisation (NIVissimConnectionCluster * c2) private
Definition at line 382 of file NIVissimConnectionCluster.cpp.
References GeomHelper::angleDiff(), PositionVector::beginEndAngle(), DEG2RAD, NIVissimConnection::dictionary(), NIVissimEdge::dictionary(), NIVissimAbstractEdge::getGeometry(), PositionVector::intersects(), isWeakDistrictConnRealisation(), myConnections, myIncomingEdges, and myOutgoingEdges.
Referenced by isWeakDistrictConnRealisation(), and NIVissimConnectionCluster::same_direction_sorter::operator()().
joinable()
bool NIVissimConnectionCluster::joinable (NIVissimConnectionCluster * c2, double offset) private
Definition at line 325 of file NIVissimConnectionCluster.cpp.
References extendByToTreatAsSame(), getDisturbanceParticipators(), hasNodeCluster(), myConnections, myIncomingEdges, myOutgoingEdges, and overlapsWith().
Referenced by NIVissimConnectionCluster::same_direction_sorter::operator()().
joinByDisturbances()
static void NIVissimConnectionCluster::joinByDisturbances (double offset) static
Referenced by getConnections().
joinBySameEdges()
void NIVissimConnectionCluster::joinBySameEdges (double offset) static
Tries to joind clusters participating within a node This is done by joining clusters which overlap.
Definition at line 216 of file NIVissimConnectionCluster.cpp.
References myClusters.
Referenced by getConnections(), and NIImporter_Vissim::postLoadBuild().
liesOnSameEdgesEnd()
bool NIVissimConnectionCluster::liesOnSameEdgesEnd (NIVissimConnectionCluster * cc2) private
Definition at line 425 of file NIVissimConnectionCluster.cpp.
References NIVissimConnection::dictionary(), NIVissimEdge::dictionary(), NIVissimBoundedClusterObject::getBoundary(), Boundary::getCenter(), NIVissimConnection::getFromEdgeID(), NIVissimAbstractEdge::getGeometry(), NIVissimConnection::getToEdgeID(), myConnections, and GeomHelper::nearest_offset_on_line_to_point2D().
Referenced by NIVissimConnectionCluster::same_direction_sorter::operator()().
overlapsWith()
bool NIVissimConnectionCluster::overlapsWith (NIVissimConnectionCluster * c, double offset = 0) const
Returns the information whether the given cluster overlaps the current.
Definition at line 177 of file NIVissimConnectionCluster.cpp.
References myBoundary, Boundary::overlapsWith(), Boundary::xmax(), and Boundary::xmin().
Referenced by joinable().
recheckEdges()
void NIVissimConnectionCluster::recheckEdges () private
Definition at line 597 of file NIVissimConnectionCluster.cpp.
References NIVissimEdge::addToConnectionCluster(), Boundary::around(), NIVissimConnection::dictionary(), NIVissimEdge::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getFromGeomPosition(), NIVissimConnection::getToEdgeID(), NIVissimConnection::getToGeomPosition(), myBoundary, myConnections, myEdges, NIVissimEdge::removeFromConnectionCluster(), Boundary::xmax(), and Boundary::xmin().
Referenced by NIVissimConnectionCluster::same_direction_sorter::operator()().
recomputeBoundary()
void NIVissimConnectionCluster::recomputeBoundary () private
Definition at line 566 of file NIVissimConnectionCluster.cpp.
References Boundary::add(), NIVissimConnection::dictionary(), PositionVector::getBoxBoundary(), NIVissimConnection::getFromGeomPosition(), NIVissimAbstractEdge::getGeometry(), NIVissimConnection::getToGeomPosition(), myBoundary, myConnections, Boundary::xmax(), and Boundary::xmin().
Referenced by NIVissimConnectionCluster(), NIVissimConnectionCluster::same_direction_sorter::operator()(), and removeConnections().
removeConnections()
void NIVissimConnectionCluster::removeConnections (const NodeSubCluster & c) private
Definition at line 552 of file NIVissimConnectionCluster.cpp.
References NIVissimAbstractEdge::getID(), NIVissimConnectionCluster::NodeSubCluster::myConnections, myConnections, and recomputeBoundary().
Referenced by NIVissimConnectionCluster::same_direction_sorter::operator()().
Friends And Related Function Documentation
NIVissimEdge
friend class NIVissimEdge friend
Definition at line 83 of file NIVissimConnectionCluster.h.
Field Documentation
myBlaID
int NIVissimConnectionCluster::myBlaID private
Definition at line 198 of file NIVissimConnectionCluster.h.
myBoundary
Boundary NIVissimConnectionCluster::myBoundary private
The boundary of the cluster.
Definition at line 179 of file NIVissimConnectionCluster.h.
Referenced by add(), around(), getPositionForEdge(), NIVissimConnectionCluster(), overlapsWith(), recheckEdges(), and recomputeBoundary().
myClusters
NIVissimConnectionCluster::ContType NIVissimConnectionCluster::myClusters static private
Definition at line 195 of file NIVissimConnectionCluster.h.
Referenced by _debugOut(), buildNodeClusters(), clearDict(), dictSize(), joinBySameEdges(), and NIVissimConnectionCluster().
myConnections
std::vector<int> NIVissimConnectionCluster::myConnections private
List of connection-ids which participate within this cluster.
Definition at line 176 of file NIVissimConnectionCluster.h.
Referenced by add(), getConnections(), getDisturbanceParticipators(), getIncomingContinuation(), getIncomingContinuationGeometry(), getOutgoingContinuation(), getOutgoingContinuationGeometry(), getPositionForEdge(), isWeakDistrictConnRealisation(), joinable(), liesOnSameEdgesEnd(), recheckEdges(), recomputeBoundary(), and removeConnections().
myEdges
std::vector<int> NIVissimConnectionCluster::myEdges private
Definition at line 185 of file NIVissimConnectionCluster.h.
Referenced by add(), getPositionForEdge(), NIVissimConnectionCluster(), and recheckEdges().
myFirstFreeID
int NIVissimConnectionCluster::myFirstFreeID = 100000 static private
Definition at line 196 of file NIVissimConnectionCluster.h.
Referenced by clearDict(), and getNextFreeNodeID().
myIncomingEdges
std::vector<int> NIVissimConnectionCluster::myIncomingEdges private
Definition at line 191 of file NIVissimConnectionCluster.h.
Referenced by add(), isWeakDistrictConnRealisation(), joinable(), and NIVissimConnectionCluster().
myNodeCluster
int NIVissimConnectionCluster::myNodeCluster private
The node the cluster is assigned to.
Definition at line 182 of file NIVissimConnectionCluster.h.
Referenced by add(), getNBNode(), getPositionForEdge(), and hasNodeCluster().
myNodes
std::vector<int> NIVissimConnectionCluster::myNodes private
Definition at line 187 of file NIVissimConnectionCluster.h.
myOutgoingEdges
std::vector<int> NIVissimConnectionCluster::myOutgoingEdges private
Definition at line 191 of file NIVissimConnectionCluster.h.
Referenced by add(), isWeakDistrictConnRealisation(), joinable(), and NIVissimConnectionCluster().
myStaticBlaID
int NIVissimConnectionCluster::myStaticBlaID = 0 static private
Definition at line 197 of file NIVissimConnectionCluster.h.
myTLs
std::vector<int> NIVissimConnectionCluster::myTLs private
Definition at line 189 of file NIVissimConnectionCluster.h.
The documentation for this class was generated from the following files:
NIVissimConnectionCluster.h
NIVissimConnectionCluster.cpp