SUMO - Simulation of Urban MObility: NIVissimTL::NIVissimTLSignalGroup Class Reference
NIVissimTL::NIVissimTLSignalGroup Class Reference
#include <NIVissimTL.h>
Public Member Functions
bool addTo (NBLoadedTLDef *node) const
NIVissimTLSignalGroup (int id, const std::string &name, bool isGreenBegin, const std::vector< double > &times, SUMOTime tredyellow, SUMOTime tyellow)
~NIVissimTLSignalGroup ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int lsaid, int id, NIVissimTLSignalGroup *o)
static NIVissimTLSignalGroup * dictionary (int lsaid, int id)
static SGroupDictType getGroupsFor (int tlid)
Private Attributes
bool myFirstIsRed
int myID
std::string myName
std::vector< double > myTimes
SUMOTime myTRedYellow
SUMOTime myTYellow
Static Private Attributes
static GroupDictType myDict
Detailed Description
Definition at line 113 of file NIVissimTL.h.
Constructor & Destructor Documentation
NIVissimTLSignalGroup()
NIVissimTL::NIVissimTLSignalGroup::NIVissimTLSignalGroup (int id, const std::string & name, bool isGreenBegin, const std::vector< double > & times, SUMOTime tredyellow, SUMOTime tyellow)
Definition at line 207 of file NIVissimTL.cpp.
~NIVissimTLSignalGroup()
NIVissimTL::NIVissimTLSignalGroup::~NIVissimTLSignalGroup ()
Definition at line 217 of file NIVissimTL.cpp.
Member Function Documentation
addTo()
bool NIVissimTL::NIVissimTLSignalGroup::addTo (NBLoadedTLDef * node) const
Definition at line 280 of file NIVissimTL.cpp.
References NBLoadedTLDef::addSignalGroup(), NBLoadedTLDef::addSignalGroupPhaseBegin(), NIVissimTL::myDict, myFirstIsRed, myID, myTimes, myTRedYellow, myTYellow, NBLoadedTLDef::setSignalYellowTimes(), NBTrafficLightDefinition::TLCOLOR_GREEN, and NBTrafficLightDefinition::TLCOLOR_RED.
clearDict()
void NIVissimTL::NIVissimTLSignalGroup::clearDict () static
Definition at line 259 of file NIVissimTL.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/2]
bool NIVissimTL::NIVissimTLSignalGroup::dictionary (int lsaid, int id, NIVissimTL::NIVissimTLSignalGroup * o) static
Definition at line 221 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimSingleTypeParser_Signalgruppendefinition::parseFixedTime().
dictionary() [2/2]
NIVissimTL::NIVissimTLSignalGroup * NIVissimTL::NIVissimTLSignalGroup::dictionary (int lsaid, int id) static
Definition at line 246 of file NIVissimTL.cpp.
References myDict.
getGroupsFor()
NIVissimTL::SGroupDictType NIVissimTL::NIVissimTLSignalGroup::getGroupsFor (int tlid) static
Definition at line 270 of file NIVissimTL.cpp.
References myDict.
Referenced by NIVissimTL::dict_SetSignals().
Field Documentation
myDict
NIVissimTL::GroupDictType NIVissimTL::NIVissimTLSignalGroup::myDict static private
Definition at line 132 of file NIVissimTL.h.
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), clearDict(), dictionary(), and getGroupsFor().
myFirstIsRed
bool NIVissimTL::NIVissimTLSignalGroup::myFirstIsRed private
Definition at line 130 of file NIVissimTL.h.
Referenced by addTo().
myID
int NIVissimTL::NIVissimTLSignalGroup::myID private
Definition at line 127 of file NIVissimTL.h.
Referenced by addTo().
myName
std::string NIVissimTL::NIVissimTLSignalGroup::myName private
Definition at line 128 of file NIVissimTL.h.
myTimes
std::vector<double> NIVissimTL::NIVissimTLSignalGroup::myTimes private
Definition at line 129 of file NIVissimTL.h.
Referenced by addTo().
myTRedYellow
SUMOTime NIVissimTL::NIVissimTLSignalGroup::myTRedYellow private
Definition at line 131 of file NIVissimTL.h.
Referenced by addTo().
myTYellow
SUMOTime NIVissimTL::NIVissimTLSignalGroup::myTYellow private
Definition at line 131 of file NIVissimTL.h.
Referenced by addTo().
The documentation for this class was generated from the following files:
NIVissimTL.h
NIVissimTL.cpp