SUMO - Simulation of Urban MObility: METriggeredCalibrator Class Reference
METriggeredCalibrator Class Reference
Calibrates the flow on a segment to a specified one.
#include <METriggeredCalibrator.h>
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
SUMOTime execute (SUMOTime currentTime)
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
const std::string & getID () const
Returns the id.
SUMOTime getLastDepart () const
Returns the last loaded depart time.
METriggeredCalibrator (const std::string &id, const MSEdge *const edge, const double pos, const std::string &aXMLFilename, const std::string &outputFilename, const SUMOTime freq, const double length, const MSRouteProbe *probe)
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void setID (const std::string &newID)
resets the id
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~METriggeredCalibrator ()
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (double &startPos, double &endPos, const double laneLength, const double minLength, const bool friendlyPos)
check start and end position of a stop
static void cleanup ()
cleanup remaining data structures
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static std::mt19937 * getParsingRNG ()
Protected Member Functions
void addParam (const SUMOSAXAttributes &attrs)
assign arbitrary vehicle parameters
void addPersonTrip (const SUMOSAXAttributes &attrs)
add a routing request for a walking or intermodal person
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
void addWalk (const SUMOSAXAttributes &attrs)
add a fully specified walk
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
int clearedInJam () const
void closeContainer ()
Ends the processing of a container.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
virtual void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
double currentFlow () const
flow in the current interval in veh/h
double currentSpeed () const
measured speed in the current interval
void init ()
int inserted () const
bool invalidJam () const
returns whether the segment is jammed although it should not be
bool invalidJam (int laneIndex) const
bool isActive () const
bool isCurrentStateActive (SUMOTime time)
int maximumInflow () const
returns the maximum number of vehicles that could enter from upstream until the calibrator is activated again
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
void parseWalkPositions (const SUMOSAXAttributes &attrs, const std::string &personID, const MSEdge *fromEdge, const MSEdge *&toEdge, double &departPos, double &arrivalPos, MSStoppingPlace *&bs, const MSTransportable::Stage *const lastStage, bool &ok)
@ brief parse depart- and arrival positions of a walk
int passed () const
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
int remainingVehicleCapacity () const
returns the number of vehicles (of the current type) that still fit onto the segment
int remainingVehicleCapacity (int laneIndex) const
int removed () const
bool removePending ()
remove any vehicles which are scheduled for removal. return true if removals took place
void reset ()
reset collected vehicle data
bool scheduleRemoval (MSVehicle *veh)
try to schedule the givne vehicle for removal. return true if it isn't already scheduled
int totalWished () const
number of vehicles expected to pass this interval
bool tryEmit (MESegment *s, MEVehicle *vehicle)
bool tryEmit (MSLane *lane, MSVehicle *vehicle)
void updateMeanData ()
do nothing
void writeXMLOutput ()
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called on the closing of a tag;.
Protected Attributes
MSTransportable::MSTransportablePlan * myActiveContainerPlan
The plan of the current container.
MSTransportable::MSTransportablePlan * myActivePlan
The plan of the current person.
ConstMSEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
double myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
bool myAmActive
whether the calibrator was active when last checking
bool myAmLoadingState
whether a state file is being loaded
SUMOTime myBeginDefault
The default value for flow begins.
int myClearedInJam
The number of vehicles that were removed when clearin a jam.
double myCurrentCosts
The currently parsed route costs.
RandomDistributor< const MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route)
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
std::vector< AspiredState >::const_iterator myCurrentStateInterval
Iterator pointing to the current interval.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
SumoXMLTag myDefaultCFModel
the default car following model
double myDefaultSpeed
The default (maximum) speed on the segment.
bool myDidInit
The information whether init was called.
bool myDidSpeedAdaption
The information whether speed was adapted in the current interval.
const MSEdge *const myEdge
the edge on which this calibrator lies
MSMeanData_Net::MSLaneMeanDataValues myEdgeMeanData
accumlated data for the whole edge
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
SUMOTime myFrequency
The frequeny with which to check for calibration.
bool myHaveWarnedAboutClearingJam
The default (maximum) speed on the segment.
std::string myID
The name of the object.
IDSupplier myIdSupplier
generates numerical ids
int myInserted
The number of vehicles that were inserted in the current interval.
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
std::vector< AspiredState > myIntervals
List of adaptation intervals.
MSLane *const myLane
the lane on which this calibrator lies (0 if the whole edge is covered at once)
std::vector< MSMeanData_Net::MSLaneMeanDataValues * > myLaneMeanData
data collector for the calibrator
SUMOTime myLastDepart
The insertion time of the vehicle read last.
OutputDevice * myOutput
The device for xml statistics.
const double myPos
the position on the edge where this calibrator lies
const MSRouteProbe *const myProbe
the route probe to retrieve routes from
int myRemoved
The number of vehicles that were removed in the current interval.
bool mySpeedIsDefault
The information whether the speed adaption has been reset.
std::set< std::string > myToRemove
set of vehicle ids to remove
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
std::vector< VehicleRemover * > myVehicleRemovers
Static Protected Attributes
static std::vector< MSMoveReminder * > LeftoverReminders
static std::vector< SUMOVehicleParameter * > LeftoverVehicleParameters
static std::mt19937 myParsingRNG
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Private Attributes
MESegment * mySegment
mesoscopic edge segment the calibrator lies on
Detailed Description
Calibrates the flow on a segment to a specified one.
Definition at line 45 of file METriggeredCalibrator.h.
Constructor & Destructor Documentation
METriggeredCalibrator()
METriggeredCalibrator::METriggeredCalibrator (const std::string & id, const MSEdge *const edge, const double pos, const std::string & aXMLFilename, const std::string & outputFilename, const SUMOTime freq, const double length, const MSRouteProbe * probe)
constructor
Definition at line 58 of file METriggeredCalibrator.cpp.
References MESegment::addDetector(), Named::getID(), MSCalibrator::myEdgeMeanData, mySegment, and MSMoveReminder::setDescription().
~METriggeredCalibrator()
METriggeredCalibrator::~METriggeredCalibrator () virtual
destructor
Definition at line 71 of file METriggeredCalibrator.cpp.
References MSCalibrator::myCurrentStateInterval, MSCalibrator::myEdgeMeanData, MSCalibrator::myIntervals, mySegment, MESegment::removeDetector(), and MSCalibrator::writeXMLOutput().
Member Function Documentation
addParam()
void SUMORouteHandler::addParam (const SUMOSAXAttributes & attrs) protected inherited
assign arbitrary vehicle parameters
Definition at line 257 of file SUMORouteHandler.cpp.
References SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), SUMORouteHandler::myCurrentVType, SUMORouteHandler::myVehicleParameter, Parameterised::setParameter(), SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::myStartElement().
addPersonTrip()
void MSRouteHandler::addPersonTrip (const SUMOSAXAttributes & attrs) protected virtual inherited
add a routing request for a walking or intermodal person
Implements SUMORouteHandler.
Definition at line 1033 of file MSRouteHandler.cpp.
References MSVehicleControl::addVehicle(), MSVehicleControl::buildVehicle(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_POS_RANDOM, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSEdge::dictionary(), GenericSAXHandler::error(), MSGlobals::gCheckRoutes, MSStoppingPlace::getAccessPos(), OptionsCont::getFloat(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::getOptSUMOTimeReporting(), MSNet::getPedestrianRouter(), MSNet::getStoppingPlace(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSRouteHandler::parseWalkPositions(), RandHelper::rand(), SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DURATION, SUMO_ATTR_FROM, SUMO_ATTR_MODES, SUMO_ATTR_SPEED, SUMO_ATTR_TO, SUMO_ATTR_VTYPES, SUMO_ATTR_WALKFACTOR, SUMO_TAG_BUS_STOP, SVC_BICYCLE, SVC_BUS, SVC_IGNORING, SVC_PASSENGER, toString(), VEHPARS_VTYPE_SET, SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
addStop()
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual inherited
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 826 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MsgHandler::getErrorInstance(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLanes(), SUMOSAXAttributes::getOpt(), MSNet::getStoppingPlace(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::lane, MAX2(), MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::Stop::parkingarea, SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ACTTYPE, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_PARKING_AREA, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
addWalk()
void MSRouteHandler::addWalk (const SUMOSAXAttributes & attrs) protected virtual inherited
add a fully specified walk
Implements SUMORouteHandler.
Definition at line 1175 of file MSRouteHandler.cpp.
References MSRouteHandler::deleteActivePlans(), SUMOVehicleParameter::depart, DEPART_POS_RANDOM, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), MSRouteHandler::parseWalkPositions(), RandHelper::rand(), SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_ROUTE, and SUMO_ATTR_SPEED.
Referenced by MSRouteHandler::getParsingRNG().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
checkLastDepart()
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 75 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
checkStopPos()
bool SUMORouteHandler::checkStopPos (double & startPos, double & endPos, const double laneLength, const double minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 219 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), RORouteHandler::addStop(), RONetHandler::parseAccess(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
cleanup()
void MSCalibrator::cleanup () static inherited
cleanup remaining data structures
Definition at line 504 of file MSCalibrator.cpp.
References MSCalibrator::LeftoverReminders, and MSCalibrator::LeftoverVehicleParameters.
Referenced by MSNet::clearAll().
clearedInJam()
int MSCalibrator::clearedInJam () const inline protected inherited
Definition at line 204 of file MSCalibrator.h.
References MSCalibrator::myClearedInJam, MSCalibrator::remainingVehicleCapacity(), MSCalibrator::reset(), and MSCalibrator::updateMeanData().
Referenced by GUICalibrator::getParameterWindow().
closeContainer()
void MSRouteHandler::closeContainer () protected virtual inherited
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 752 of file MSRouteHandler.cpp.
References MSTransportableControl::buildContainer(), SUMORouteHandler::checkLastDepart(), GenericSAXHandler::error(), MSNet::getContainerControl(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closeFlow()
void MSRouteHandler::closeFlow () protected virtual inherited
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 780 of file MSRouteHandler.cpp.
References SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeRoute(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::parametersSet, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, string2time(), VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closePerson()
void MSRouteHandler::closePerson () protected virtual inherited
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 720 of file MSRouteHandler.cpp.
References MSTransportableControl::buildPerson(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::deleteActivePlans(), SUMOVehicleParameter::depart, GenericSAXHandler::error(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myAmLoadingState, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
closeRoute()
void MSRouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual inherited
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 469 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), MSNet::getInstance(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, and MSRoute::setCosts().
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
closeRouteDistribution()
void MSRouteHandler::closeRouteDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 586 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::getParsingRNG().
closeVehicle()
void MSRouteHandler::closeVehicle () protected virtual inherited
Ends the processing of a vehicle.
Implements SUMORouteHandler.
Reimplemented in MSStateHandler.
Definition at line 608 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::buildVehicle(), SUMORouteHandler::checkLastDepart(), DEFAULT_VTYPE_ID, MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSVehicleType::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getQuota(), MSVehicleControl::getVehicle(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myAmLoadingState, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), SVC_PEDESTRIAN, toString(), VEHPARS_ROUTE_SET, SUMOVehicleParameter::vtypeid, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSStateHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
closeVehicleTypeDistribution()
void MSRouteHandler::closeVehicleTypeDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 370 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentVTypeDistribution, and MSRouteHandler::myCurrentVTypeDistributionID.
Referenced by MSRouteHandler::getParsingRNG().
currentFlow()
double MSCalibrator::currentFlow () const protected inherited
flow in the current interval in veh/h
Definition at line 270 of file MSCalibrator.cpp.
References MSNet::getInstance(), MSCalibrator::myCurrentStateInterval, MSCalibrator::passed(), and STEPS2TIME.
Referenced by GUICalibrator::getParameterWindow(), and MSCalibrator::passed().
currentSpeed()
double MSCalibrator::currentSpeed () const protected inherited
measured speed in the current interval
Definition at line 276 of file MSCalibrator.cpp.
References MSMeanData::MeanDataValues::getSamples(), MSMeanData::MeanDataValues::getTravelledDistance(), and MSCalibrator::myEdgeMeanData.
Referenced by GUICalibrator::getParameterWindow(), and MSCalibrator::passed().
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
execute()
SUMOTime METriggeredCalibrator::execute (SUMOTime currentTime) virtual
the implementation of the MSTrigger / Command interface. Calibrating takes place here.
Reimplemented from MSCalibrator.
Definition at line 95 of file METriggeredCalibrator.cpp.
References MSVehicleControl::buildVehicle(), MSRoute::contains(), MSVehicleControl::deleteVehicle(), DELTA_T, SUMOVehicleParameter::depart, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSBaseVehicle::getEdge(), MESegment::getEdge(), OptionsCont::getFloat(), Named::getID(), MSNet::getInstance(), MESegment::getNextInsertionTime(), MESegment::getNextSegment(), OptionsCont::getOptions(), MSRouteProbe::getRoute(), MELoop::getSegmentForEdge(), MSEdge::getSpeedLimit(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gMesoNet, SUMOVehicleParameter::id, invalidJam(), MSCalibrator::isCurrentStateActive(), MAX2(), maximumInflow(), MEVehicle::moveRoutePointer(), MSCalibrator::myClearedInJam, MSCalibrator::myCurrentStateInterval, MSCalibrator::myDefaultSpeed, MSCalibrator::myDidSpeedAdaption, MSCalibrator::myEdge, MSCalibrator::myEdgeMeanData, MSCalibrator::myFrequency, MSCalibrator::myHaveWarnedAboutClearingJam, Named::myID, MSCalibrator::myInserted, MSCalibrator::myIntervals, MSCalibrator::myProbe, MSCalibrator::myRemoved, mySegment, MSCalibrator::mySpeedIsDefault, passed(), MESegment::prepareDetectorForWriting(), remainingVehicleCapacity(), MSMeanData_Net::MSLaneMeanDataValues::reset(), SUMOVehicleParameter::routeid, MEVehicle::setEventTime(), MSEdge::setMaxSpeed(), MEVehicle::setSegment(), MESegment::setSpeed(), STEPS2TIME, TIME2STEPS, time2string(), toString(), tryEmit(), MESegment::vaporizeAnyCar(), SUMOVehicleParameter::vtypeid, WRITE_WARNING, and MSCalibrator::writeXMLOutput().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
getFirstDepart()
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 73 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addPersonTrip(), SUMORouteHandler::addStop(), SUMORouteHandler::addWalk(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice::saveState(), MSDevice_Vehroutes::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getLastDepart()
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 69 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
getParsingRNG()
static std::mt19937* MSRouteHandler::getParsingRNG () inline static inherited
Definition at line 69 of file MSRouteHandler.h.
References MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), MSRouteHandler::myParsingRNG, MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseFromViaTo(), and MSRouteHandler::parseWalkPositions().
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::computeRandomDepartOffset(), MSInsertionControl::determineCandidates(), NLBuilder::init(), and GUILoadThread::run().
init()
void MSCalibrator::init () protected inherited
Definition at line 116 of file MSCalibrator.cpp.
References MSEventControl::addEvent(), MSNet::getEndOfTimestepEvents(), MSNet::getInstance(), MSCalibrator::myDidInit, Named::myID, MSCalibrator::myIntervals, SUMOTime_MAX, and WRITE_WARNING.
Referenced by MSCalibrator::MSCalibrator(), and MSCalibrator::myEndElement().
inserted()
int MSCalibrator::inserted () const inline protected inherited
Definition at line 198 of file MSCalibrator.h.
References MSCalibrator::myInserted.
Referenced by GUICalibrator::getParameterWindow().
invalidJam() [1/2]
bool METriggeredCalibrator::invalidJam () const protected
returns whether the segment is jammed although it should not be
Definition at line 245 of file METriggeredCalibrator.cpp.
References MESegment::getBruttoOccupancy(), MESegment::getEdge(), MESegment::getMeanSpeed(), MSEdge::getSpeedLimit(), maximumInflow(), mySegment, and remainingVehicleCapacity().
Referenced by execute(), and passed().
invalidJam() [2/2]
bool MSCalibrator::invalidJam (int laneIndex) const protected inherited
Definition at line 456 of file MSCalibrator.cpp.
References MSEdge::getLanes(), MSEdge::getSpeedLimit(), MSCalibrator::myEdge, and MSCalibrator::remainingVehicleCapacity().
Referenced by MSCalibrator::execute(), and MSCalibrator::passed().
isActive()
bool MSCalibrator::isActive () const inline protected inherited
Definition at line 152 of file MSCalibrator.h.
References MSCalibrator::myAmActive.
Referenced by GUICalibrator::drawGL(), and GUICalibrator::getParameterWindow().
isCurrentStateActive()
bool MSCalibrator::isCurrentStateActive (SUMOTime time) protected inherited
Definition at line 249 of file MSCalibrator.cpp.
References MSCalibrator::myCurrentStateInterval, and MSCalibrator::myIntervals.
Referenced by execute(), and MSCalibrator::execute().
maximumInflow()
int METriggeredCalibrator::maximumInflow () const inline protected
returns the maximum number of vehicles that could enter from upstream until the calibrator is activated again
Definition at line 85 of file METriggeredCalibrator.h.
References MESegment::getMinimumHeadwayTime(), MSCalibrator::myFrequency, and mySegment.
Referenced by execute(), and invalidJam().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void MSCalibrator::myEndElement (int element) protected virtual inherited
Called on the closing of a tag;.
Parameters
[in] element ID of the currently closed element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from MSRouteHandler.
Definition at line 204 of file MSCalibrator.cpp.
References MSCalibrator::init(), MSCalibrator::myDidInit, MSRouteHandler::myEndElement(), SUMO_TAG_CALIBRATOR, and SUMO_TAG_FLOW.
myStartElement()
void MSCalibrator::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual inherited
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from MSRouteHandler.
Definition at line 141 of file MSCalibrator.cpp.
References MSCalibrator::AspiredState::begin, DEFAULT_VTYPE_ID, DEPART_LANE_ALLOWED_FREE, DEPART_LANE_DEFAULT, DEPART_LANE_GIVEN, DEPART_SPEED_DEFAULT, DEPART_SPEED_MAX, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departSpeedProcedure, MSCalibrator::AspiredState::end, Named::getID(), MSLane::getIndex(), MSNet::getInstance(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSCalibrator::LeftoverVehicleParameters, MSCalibrator::myCurrentStateInterval, Named::myID, MSCalibrator::myIntervals, MSCalibrator::myLane, MSRouteHandler::myStartElement(), SUMOVehicleParserHelper::parseVehicleAttributes(), MSCalibrator::AspiredState::q, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_SPEED, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_FLOW, MSCalibrator::AspiredState::v, MSCalibrator::AspiredState::vehicleParameter, SUMOVehicleParameter::vtypeid, WRITE_ERROR, and WRITE_WARNING.
openRoute()
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route for reading
Implements SUMORouteHandler.
Definition at line 390 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
openRouteDistribution()
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 539 of file MSRouteHandler.cpp.
References TplConvert::_2doubleSec(), RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
openVehicleTypeDistribution()
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 348 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, MSRouteHandler::myParsingRNG, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
Referenced by MSRouteHandler::getParsingRNG().
parseFromViaTo()
void MSRouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected inherited
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 110 of file MSRouteHandler.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_ROUTE, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
parseStop()
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 271 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parametersSet, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, SUMOSAXAttributes::parseStringSet(), STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_PARKING_AREA, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), and SUMORouteHandler::getFirstDepart().
parseWalkPositions()
void MSRouteHandler::parseWalkPositions (const SUMOSAXAttributes & attrs, const std::string & personID, const MSEdge * fromEdge, const MSEdge *& toEdge, double & departPos, double & arrivalPos, MSStoppingPlace *& bs, const MSTransportable::Stage *const lastStage, bool & ok) protected inherited
@ brief parse depart- and arrival positions of a walk
Definition at line 978 of file MSRouteHandler.cpp.
References SUMOSAXAttributes::get(), MSStoppingPlace::getAccessPos(), MSTransportable::Stage::getArrivalPos(), MSStoppingPlace::getBeginLanePosition(), MSTransportable::Stage::getDestination(), MSTransportable::Stage::getDestinationStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLength(), SUMOSAXAttributes::getOpt(), MSNet::getStoppingPlace(), MSEdge::getToJunction(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myParsingRNG, SUMOVehicleParserHelper::parseWalkPos(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMO_TAG_BUS_STOP, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addWalk(), and MSRouteHandler::getParsingRNG().
passed()
int METriggeredCalibrator::passed () const inline protected virtual
Reimplemented from MSCalibrator.
Definition at line 67 of file METriggeredCalibrator.h.
References invalidJam(), MSCalibrator::myEdgeMeanData, MSMeanData_Net::MSLaneMeanDataValues::nVehDeparted, MSMeanData_Net::MSLaneMeanDataValues::nVehEntered, MSMeanData_Net::MSLaneMeanDataValues::nVehVaporized, remainingVehicleCapacity(), and reset().
Referenced by execute().
registerLastDepart()
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 87 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
remainingVehicleCapacity() [1/2]
int METriggeredCalibrator::remainingVehicleCapacity () const protected
returns the number of vehicles (of the current type) that still fit onto the segment
Definition at line 256 of file METriggeredCalibrator.cpp.
References MSNet::getInstance(), MSVehicleType::getLengthWithGap(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSCalibrator::myCurrentStateInterval, mySegment, MESegment::remainingVehicleCapacity(), and SUMOVehicleParameter::vtypeid.
Referenced by execute(), invalidJam(), and passed().
remainingVehicleCapacity() [2/2]
int MSCalibrator::remainingVehicleCapacity (int laneIndex) const protected inherited
Definition at line 479 of file MSCalibrator.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getHeadwayTime(), MSNet::getInstance(), MSEdge::getLanes(), MSEdge::getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSEdge::getSpeedLimit(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MAX2(), MSCalibrator::myCurrentStateInterval, MSCalibrator::myEdge, and SUMOVehicleParameter::vtypeid.
Referenced by MSCalibrator::clearedInJam(), and MSCalibrator::invalidJam().
removed()
int MSCalibrator::removed () const inline protected inherited
Definition at line 201 of file MSCalibrator.h.
References MSCalibrator::myRemoved.
Referenced by GUICalibrator::getParameterWindow().
removePending()
bool MSCalibrator::removePending () protected inherited
remove any vehicles which are scheduled for removal. return true if removals took place
Definition at line 286 of file MSCalibrator.cpp.
References Named::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSCalibrator::myToRemove, MSMoveReminder::NOTIFICATION_VAPORIZED, MSVehicle::onRemovalFromNet(), MSLane::removeVehicle(), MSVehicleControl::scheduleVehicleRemoval(), and WRITE_WARNING.
Referenced by MSCalibrator::execute(), and MSCalibrator::scheduleRemoval().
reset()
void METriggeredCalibrator::reset () protected virtual
reset collected vehicle data
Reimplemented from MSCalibrator.
Definition at line 264 of file METriggeredCalibrator.cpp.
References MSCalibrator::myEdgeMeanData, and MSMeanData_Net::MSLaneMeanDataValues::reset().
Referenced by passed().
scheduleRemoval()
bool MSCalibrator::scheduleRemoval (MSVehicle * veh) inline protected inherited
try to schedule the givne vehicle for removal. return true if it isn't already scheduled
Definition at line 222 of file MSCalibrator.h.
References MSBaseVehicle::getID(), MSCalibrator::myToRemove, and MSCalibrator::removePending().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
totalWished()
int MSCalibrator::totalWished () const protected inherited
number of vehicles expected to pass this interval
Definition at line 259 of file MSCalibrator.cpp.
References MSCalibrator::myCurrentStateInterval, MSCalibrator::myIntervals, and STEPS2TIME.
Referenced by MSCalibrator::execute(), GUICalibrator::getParameterWindow(), and MSCalibrator::passed().
tryEmit() [1/2]
bool METriggeredCalibrator::tryEmit (MESegment * s, MEVehicle * vehicle) protected
Definition at line 83 of file METriggeredCalibrator.cpp.
References MSVehicleControl::addVehicle(), SUMOVehicleParameter::depart, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSNet::getVehicleControl(), and MESegment::initialise().
Referenced by execute().
tryEmit() [2/2]
bool MSCalibrator::tryEmit (MSLane * lane, MSVehicle * vehicle) protected inherited
updateMeanData()
void METriggeredCalibrator::updateMeanData () inline protected virtual
do nothing
Reimplemented from MSCalibrator.
Definition at line 82 of file METriggeredCalibrator.h.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
writeXMLOutput()
void MSCalibrator::writeXMLOutput () protected inherited
Definition at line 216 of file MSCalibrator.cpp.
References MSMeanData::MeanDataValues::getSamples(), MSMeanData::MeanDataValues::getTravelledDistance(), MSCalibrator::myClearedInJam, MSCalibrator::myCurrentStateInterval, MSCalibrator::myDidSpeedAdaption, MSCalibrator::myEdgeMeanData, MSCalibrator::myHaveWarnedAboutClearingJam, Named::myID, MSCalibrator::myInserted, MSCalibrator::myOutput, MSCalibrator::myRemoved, MSMeanData_Net::MSLaneMeanDataValues::nVehDeparted, MSMeanData_Net::MSLaneMeanDataValues::nVehEntered, MSMeanData_Net::MSLaneMeanDataValues::nVehVaporized, MSCalibrator::passed(), MSCalibrator::reset(), STEPS2TIME, time2string(), toString(), and MSCalibrator::updateMeanData().
Referenced by execute(), MSCalibrator::execute(), ~METriggeredCalibrator(), and MSCalibrator::~MSCalibrator().
Field Documentation
LeftoverReminders
std::vector< MSMoveReminder * > MSCalibrator::LeftoverReminders static protected inherited
Definition at line 284 of file MSCalibrator.h.
Referenced by MSCalibrator::cleanup(), and MSCalibrator::MSCalibrator().
LeftoverVehicleParameters
std::vector< SUMOVehicleParameter * > MSCalibrator::LeftoverVehicleParameters static protected inherited
Definition at line 285 of file MSCalibrator.h.
Referenced by MSCalibrator::cleanup(), and MSCalibrator::myStartElement().
myActiveContainerPlan
MSTransportable::MSTransportablePlan* MSRouteHandler::myActiveContainerPlan protected inherited
The plan of the current container.
Definition at line 165 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
myActivePlan
MSTransportable::MSTransportablePlan* MSRouteHandler::myActivePlan protected inherited
The plan of the current person.
Definition at line 162 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closePerson(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
myActiveRoute
ConstMSEdgeVector MSRouteHandler::myActiveRoute protected inherited
The current route.
Definition at line 159 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeRoute(), MSRouteHandler::MSRouteHandler(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), and MSRouteHandler::parseFromViaTo().
myActiveRouteColor
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 174 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteID
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 165 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::addWalk(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
myActiveRouteProbability
double SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 171 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteRefID
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 168 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myActiveRouteStops
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 180 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeRoute(), and RORouteHandler::closeRoute().
myAddVehiclesDirectly
bool MSRouteHandler::myAddVehiclesDirectly protected inherited
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 168 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), and MSRouteHandler::closeVehicle().
myAmActive
bool MSCalibrator::myAmActive protected inherited
whether the calibrator was active when last checking
Definition at line 280 of file MSCalibrator.h.
Referenced by MSCalibrator::execute(), and MSCalibrator::isActive().
myAmLoadingState
bool MSRouteHandler::myAmLoadingState protected inherited
whether a state file is being loaded
Definition at line 183 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and MSStateHandler::MSStateHandler().
myBeginDefault
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 189 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
myClearedInJam
int MSCalibrator::myClearedInJam protected inherited
The number of vehicles that were removed when clearin a jam.
Definition at line 267 of file MSCalibrator.h.
Referenced by MSCalibrator::clearedInJam(), execute(), MSCalibrator::execute(), MSCalibrator::passed(), and MSCalibrator::writeXMLOutput().
myCurrentCosts
double SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 177 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
myCurrentRouteDistribution
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution protected inherited
The currently parsed distribution of routes (probability->route)
Definition at line 177 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
myCurrentRouteDistributionID
std::string MSRouteHandler::myCurrentRouteDistributionID protected inherited
The id of the currently parsed route distribution.
Definition at line 180 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
myCurrentStateInterval
std::vector<AspiredState>::const_iterator MSCalibrator::myCurrentStateInterval protected inherited
Iterator pointing to the current interval.
Definition at line 247 of file MSCalibrator.h.
Referenced by MSCalibrator::currentFlow(), GUICalibrator::drawGL(), execute(), MSCalibrator::execute(), GUICalibrator::getParameterWindow(), MSCalibrator::isCurrentStateActive(), MSCalibrator::myStartElement(), remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MSCalibrator::totalWished(), MSCalibrator::writeXMLOutput(), ~METriggeredCalibrator(), and MSCalibrator::~MSCalibrator().
myCurrentVType
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 183 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSStateHandler::myEndElement(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
myCurrentVTypeDistribution
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution protected inherited
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 171 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
myCurrentVTypeDistributionID
std::string MSRouteHandler::myCurrentVTypeDistributionID protected inherited
The id of the currently parsed vehicle type distribution.
Definition at line 174 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), and MSRouteHandler::openVehicleTypeDistribution().
myDefaultCFModel
SumoXMLTag SUMORouteHandler::myDefaultCFModel protected inherited
the default car following model
Definition at line 201 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::MSRouteHandler(), and SUMORouteHandler::myStartElement().
myDefaultSpeed
double MSCalibrator::myDefaultSpeed protected inherited
The default (maximum) speed on the segment.
Definition at line 275 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), and GUICalibrator::getParameterWindow().
myDidInit
bool MSCalibrator::myDidInit protected inherited
The information whether init was called.
Definition at line 273 of file MSCalibrator.h.
Referenced by MSCalibrator::init(), MSCalibrator::MSCalibrator(), and MSCalibrator::myEndElement().
myDidSpeedAdaption
bool MSCalibrator::myDidSpeedAdaption protected inherited
The information whether speed was adapted in the current interval.
Definition at line 271 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), and MSCalibrator::writeXMLOutput().
myEdge
const MSEdge* const MSCalibrator::myEdge protected inherited
the edge on which this calibrator lies
Definition at line 233 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), MSCalibrator::invalidJam(), MSCalibrator::MSCalibrator(), and MSCalibrator::remainingVehicleCapacity().
myEdgeMeanData
MSMeanData_Net::MSLaneMeanDataValues MSCalibrator::myEdgeMeanData protected inherited
accumlated data for the whole edge
Definition at line 243 of file MSCalibrator.h.
Referenced by MSCalibrator::currentSpeed(), execute(), MSCalibrator::execute(), METriggeredCalibrator(), passed(), MSCalibrator::passed(), reset(), MSCalibrator::reset(), MSCalibrator::updateMeanData(), MSCalibrator::writeXMLOutput(), and ~METriggeredCalibrator().
myEndDefault
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 192 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
myFirstDepart
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 195 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
myFrequency
SUMOTime MSCalibrator::myFrequency protected inherited
The frequeny with which to check for calibration.
Definition at line 261 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), and maximumInflow().
myHaveWarnedAboutClearingJam
bool MSCalibrator::myHaveWarnedAboutClearingJam protected inherited
The default (maximum) speed on the segment.
Definition at line 277 of file MSCalibrator.h.
Referenced by execute(), and MSCalibrator::writeXMLOutput().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myIdSupplier
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 186 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
myInserted
int MSCalibrator::myInserted protected inherited
The number of vehicles that were inserted in the current interval.
Definition at line 265 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), MSCalibrator::inserted(), and MSCalibrator::writeXMLOutput().
myInsertStopEdgesAt
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 198 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
myIntervals
std::vector<AspiredState> MSCalibrator::myIntervals protected inherited
List of adaptation intervals.
Definition at line 245 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), GUICalibrator::getParameterWindow(), MSCalibrator::init(), MSCalibrator::isCurrentStateActive(), MSCalibrator::myStartElement(), MSCalibrator::totalWished(), ~METriggeredCalibrator(), and MSCalibrator::~MSCalibrator().
myLane
MSLane* const MSCalibrator::myLane protected inherited
the lane on which this calibrator lies (0 if the whole edge is covered at once)
Definition at line 235 of file MSCalibrator.h.
Referenced by MSCalibrator::execute(), MSCalibrator::MSCalibrator(), and MSCalibrator::myStartElement().
myLaneMeanData
std::vector<MSMeanData_Net::MSLaneMeanDataValues*> MSCalibrator::myLaneMeanData protected inherited
data collector for the calibrator
Definition at line 241 of file MSCalibrator.h.
Referenced by MSCalibrator::MSCalibrator(), MSCalibrator::reset(), and MSCalibrator::updateMeanData().
myLastDepart
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 162 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
myOutput
OutputDevice* MSCalibrator::myOutput protected inherited
The device for xml statistics.
Definition at line 258 of file MSCalibrator.h.
Referenced by MSCalibrator::MSCalibrator(), and MSCalibrator::writeXMLOutput().
myParsingRNG
std::mt19937 MSRouteHandler::myParsingRNG static protected inherited
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Definition at line 186 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addWalk(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), and MSRouteHandler::parseWalkPositions().
myPos
const double MSCalibrator::myPos protected inherited
the position on the edge where this calibrator lies
Definition at line 237 of file MSCalibrator.h.
myProbe
const MSRouteProbe* const MSCalibrator::myProbe protected inherited
the route probe to retrieve routes from
Definition at line 239 of file MSCalibrator.h.
Referenced by execute(), and MSCalibrator::execute().
myRemoved
int MSCalibrator::myRemoved protected inherited
The number of vehicles that were removed in the current interval.
Definition at line 263 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::passed(), MSCalibrator::removed(), and MSCalibrator::writeXMLOutput().
mySegment
MESegment* METriggeredCalibrator::mySegment private
mesoscopic edge segment the calibrator lies on
Definition at line 91 of file METriggeredCalibrator.h.
Referenced by execute(), invalidJam(), maximumInflow(), METriggeredCalibrator(), remainingVehicleCapacity(), and ~METriggeredCalibrator().
mySpeedIsDefault
bool MSCalibrator::mySpeedIsDefault protected inherited
The information whether the speed adaption has been reset.
Definition at line 269 of file MSCalibrator.h.
Referenced by execute(), and MSCalibrator::execute().
myToRemove
std::set<std::string> MSCalibrator::myToRemove protected inherited
set of vehicle ids to remove
Note
: we avoid keeping vehicle points because someone else might invalidate it before look at it again (i.e. another calibrator)
Definition at line 255 of file MSCalibrator.h.
Referenced by MSCalibrator::removePending(), and MSCalibrator::scheduleRemoval().
myVehicleParameter
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 159 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSRouteHandler::addPersonTrip(), RORouteHandler::addPersonTrip(), MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::addWalk(), RORouteHandler::addWalk(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSStateHandler::myEndElement(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
myVehicleRemovers
std::vector<VehicleRemover*> MSCalibrator::myVehicleRemovers protected inherited
Definition at line 249 of file MSCalibrator.h.
Referenced by MSCalibrator::MSCalibrator(), and MSCalibrator::~MSCalibrator().
The documentation for this class was generated from the following files:
METriggeredCalibrator.h
METriggeredCalibrator.cpp