SUMO - Simulation of Urban MObility: GUINet Class Reference
GUINet Class Reference
A MSNet extended by some values for usage within the gui.
#include <GUINet.h>
Public Types
typedef IntermodalRouter< MSEdge, MSLane, MSJunction, SUMOVehicle > MSIntermodalRouter
typedef PedestrianRouterDijkstra< MSEdge, MSLane, MSJunction, MSVehicle > MSPedestrianRouterDijkstra
enum SimulationState {
SIMSTATE_LOADING, SIMSTATE_RUNNING, SIMSTATE_END_STEP_REACHED, SIMSTATE_NO_FURTHER_VEHICLES,
SIMSTATE_CONNECTION_CLOSED, SIMSTATE_ERROR_IN_SIM, SIMSTATE_TOO_MANY_TELEPORTS
}
Possible states of a simulation - running or stopped with different reasons.
Public Member Functions
void addRestriction (const std::string &id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
void closeBuilding (const OptionsCont &oc, MSEdgeControl *edges, MSJunctionControl *junctions, SUMORouteLoaderControl *routeLoaders, MSTLLogicControl *tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles, bool hasInternalLinks, bool hasNeighs, bool lefthand, double version)
Closes the network's building process.
void closeSimulation (SUMOTime start)
Closes the simulation (all files, connections, etc.)
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
const Boundary & getBoundary () const
returns the bounder of the network
SUMOTime getCurrentTimeStep () const
Returns the current simulation step.
GUIMEVehicleControl * getGUIMEVehicleControl ()
Returns the vehicle control.
GUIVehicleControl * getGUIVehicleControl ()
Returns the vehicle control.
MSIntermodalRouter & getIntermodalRouter (const MSEdgeVector &prohibited=MSEdgeVector()) const
Position getJunctionPosition (const std::string &name) const
returns the position of a junction
const NamedRTree & getLanesRTree () const
Returns an RTree that contains lane IDs.
MSPedestrianRouterDijkstra & getPedestrianRouter (const MSEdgeVector &prohibited=MSEdgeVector()) const
const std::map< SUMOVehicleClass, double > * getRestrictions (const std::string &id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterEffort (const MSEdgeVector &prohibited=MSEdgeVector()) const
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterTT (const MSEdgeVector &prohibited=MSEdgeVector()) const
SUMORTree & getVisualisationSpeedUp ()
Returns the RTree used for visualisation speed-up.
const SUMORTree & getVisualisationSpeedUp () const
Returns the RTree used for visualisation speed-up.
GUINet (MSVehicleControl *vc, MSEventControl *beginOfTimestepEvents, MSEventControl *endOfTimestepEvents, MSEventControl *insertionEvents)
Constructor.
void guiSimulationStep ()
Some further steps needed for gui processing.
bool hasElevation () const
return whether the network contains elevation data
bool hasInternalLinks () const
return whether the network contains internal links
bool hasPermissions () const
Returns whether the network has specific vehicle class permissions.
void initGUIStructures ()
Initialises gui wrappers.
bool lefthand () const
return whether the network was built for lefthand traffic
void loadRoutes ()
loads routes for the next few steps
void lock ()
grant exclusive access to the simulation state
bool logSimulationDuration () const
Returns whether duration shall be logged.
void setCurrentTimeStep (const SUMOTime step)
Sets the current simulation step (used by state loading)
void setPermissionsFound ()
Labels the network to contain vehicle class permissions.
SimulationState simulate (SUMOTime start, SUMOTime stop)
Simulates from timestep start to stop.
SimulationState simulationState (SUMOTime stopTime) const
Called after a simulation step, this method returns the current simulation state.
void simulationStep ()
Performs a single simulation step (locking the simulation)
void unlock ()
release exclusive access to the simulation state
bool vehicleExists (const std::string &name) const
returns the information whether the vehicle still exists
double version () const
return the network version
void writeChargingStationOutput () const
write charging station output
void writeOutput ()
Write netstate, summary and detector output.
~GUINet ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
functions for performance measurements
int getWholeDuration () const
Returns the duration of the last step (sim+visualisation+idle) (in ms)
int getSimDuration () const
Returns the duration of the last step's simulation part (in ms)
double getRTFactor () const
Returns the simulation speed as a factor to real time.
double getUPS () const
Returns the update per seconds rate.
double getMeanRTFactor (int duration) const
Returns the simulation speed as a factor to real time.
double getMeanUPS () const
Returns the update per seconds rate.
int getIdleDuration () const
Returns the duration of the last step's idle part (in ms)
void setSimDuration (int val)
Sets the duration of the last step's simulation part.
void setIdleDuration (int val)
Sets the duration of the last step's idle part.
double getAvgRouteLength () const
double getAvgDuration () const
double getAvgWaitingTime () const
double getAvgTimeLoss () const
double getAvgDepartDelay () const
double getAvgTripSpeed () const
double getAvgWalkRouteLength () const
double getAvgWalkDuration () const
double getAvgWalkTimeLoss () const
MSTransportableControl & getPersonControl ()
Returns the person control.
MSTransportableControl & getContainerControl ()
Returns the container control.
int getLinkTLID (MSLink *link) const
int getLinkTLIndex (MSLink *link) const
locator-methods
std::vector< GUIGlID > getJunctionIDs (bool includeInternal) const
std::vector< GUIGlID > getTLSIDs () const
Returns the gl-ids of all traffic light logics within the net.
Output during the simulation
void preSimStepOutput () const
Prints the current step number.
void postSimStepOutput () const
Prints the statistics of the step at its end.
Retrieval of references to substructures
MSVehicleControl & getVehicleControl ()
Returns the vehicle control.
bool hasPersons () const
Returns whether persons are simulated.
bool hasContainers () const
Returns whether containers are simulated.
MSEdgeControl & getEdgeControl ()
Returns the edge control.
MSInsertionControl & getInsertionControl ()
Returns the insertion control.
MSDetectorControl & getDetectorControl ()
Returns the detector control.
MSTLLogicControl & getTLSControl ()
Returns the tls logics control.
MSJunctionControl & getJunctionControl ()
Returns the junctions control.
MSEventControl * getBeginOfTimestepEvents ()
Returns the event control for events executed at the begin of a time step.
MSEventControl * getEndOfTimestepEvents ()
Returns the event control for events executed at the end of a time step.
MSEventControl * getInsertionEvents ()
Returns the event control for insertion events.
ShapeContainer & getShapeContainer ()
Returns the shapes container.
MSEdgeWeightsStorage & getWeightsStorage ()
Returns the net's internal edge travel times/efforts container.
Insertion and retrieval of stopping places
bool addStoppingPlace (const SumoXMLTag category, MSStoppingPlace *stop)
Adds a stopping place.
MSStoppingPlace * getStoppingPlace (const std::string &id, const SumoXMLTag category) const
Returns the named stopping place of the given category.
std::string getStoppingPlaceID (const MSLane *lane, const double pos, const SumoXMLTag category) const
Returns the stop of the given category close to the given position.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void adaptIntermodalRouter (MSIntermodalRouter &router)
static void clearAll ()
Clears all dictionaries.
static double getEffort (const MSEdge *const e, const SUMOVehicle *const v, double t)
Returns the effort to pass an edge.
static GUINet * getGUIInstance ()
Returns the pointer to the unique instance of GUINet (singleton).
static MSNet * getInstance ()
Returns the pointer to the unique instance of MSNet (singleton).
static std::string getStateMessage (SimulationState state)
Returns the message to show if a certain state occurs.
static double getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, double t)
Returns the travel time to pass an edge.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::map< MSLink *, std::string > Links2LogicMap
Definition of a link-to-logic-id map.
typedef std::map< MSTrafficLightLogic *, GUITrafficLightLogicWrapper * > Logics2WrapperMap
Definition of a traffic light-to-wrapper map.
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
bool checkElevation ()
check all lanes for elevation data
int getHaltingVehicleNumber () const
count number of standing vehicles in the network
double getVehicleMeanSpeed () const
double getVehicleMeanSpeedRelative () const
std::pair< double, double > getVehicleMeanSpeeds () const
get current absolute and relative mean vehicle speed in the network
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
Boundary myBoundary
The networks boundary.
std::vector< GUIDetectorWrapper * > myDetectorWrapper
A detector dictionary.
std::vector< GUIEdge * > myEdgeWrapper
Wrapped MS-edges.
LayeredRTree myGrid
The visualization speed-up.
bool myHasElevation
Whether the network contains elevation data.
bool myHasInternalLinks
Whether the network contains internal links/lanes/edges.
bool myHavePermissions
Whether the network contains edges which not all vehicles may pass.
MSIntermodalRouter * myIntermodalRouter
std::vector< GUIJunctionWrapper * > myJunctionWrapper
Wrapped MS-junctions.
std::pair< bool, NamedRTree > myLanesRTree
An RTree structure holding lane IDs.
int myLastIdleDuration
int myLastSimDuration
The step durations (simulation, /*visualisation, */idle)
long myLastVehicleMovementCount
bool myLefthand
Whether the network was built for left-hand traffic.
Links2LogicMap myLinks2Logic
The link-to-logic-id map.
Logics2WrapperMap myLogics2Wrapper
The traffic light-to-wrapper map.
int myMaxTeleports
Maximum number of teleports.
long myOverallSimDuration
long myOverallVehicleCount
MSPedestrianRouterDijkstra * myPedestrianRouter
std::map< std::string, std::map< SUMOVehicleClass, double > > myRestrictions
The vehicle class specific speed restrictions.
SUMORouteLoaderControl * myRouteLoaders
Route loader for dynamic loading of routes.
SUMOAbstractRouter< MSEdge, SUMOVehicle > * myRouterEffort
SUMOAbstractRouter< MSEdge, SUMOVehicle > * myRouterTT
SUMOTime myStep
Current time step.
std::map< SumoXMLTag, NamedObjectCont< MSStoppingPlace * > > myStoppingPlaces
Dictionary of bus / container stops.
std::vector< MSTrafficLightLogic * > myTLLogicWrapper
Wrapped TL-Logics.
std::vector< VehicleStateListener * > myVehicleStateListeners
Container for vehicle state listener.
double myVersion
the network version
Substructures
MSVehicleControl * myVehicleControl
Controls vehicle building and deletion;.
MSTransportableControl * myPersonControl
Controls person building and deletion;.
MSTransportableControl * myContainerControl
Controls container building and deletion;.
MSEdgeControl * myEdges
Controls edges, performs vehicle movement;.
MSJunctionControl * myJunctions
Controls junctions, realizes right-of-way rules;.
MSTLLogicControl * myLogics
Controls tls logics, realizes waiting on tls rules;.
MSInsertionControl * myInserter
Controls vehicle insertion;.
MSDetectorControl * myDetectorControl
Controls detectors;.
MSEventControl * myBeginOfTimestepEvents
Controls events executed at the begin of a time step;.
MSEventControl * myEndOfTimestepEvents
Controls events executed at the end of a time step;.
MSEventControl * myInsertionEvents
Controls insertion events;.
ShapeContainer * myShapeContainer
A container for geometrical shapes;.
MSEdgeWeightsStorage * myEdgeWeights
The net's knowledge about edge efforts/travel times;.
data needed for computing performance values
bool myLogExecutionTime
Information whether the simulation duration shall be logged.
bool myLogStepNumber
Information whether the number of the simulation step shall be logged.
long myTraCIStepDuration
The last simulation step duration.
long mySimStepDuration
long mySimBeginMillis
The overall simulation duration.
long long int myVehiclesMoved
The overall number of vehicle movements.
State output variables
std::vector< SUMOTime > myStateDumpTimes
Times at which a state shall be written.
std::vector< std::string > myStateDumpFiles
The names for the state files.
SUMOTime myStateDumpPeriod
The period for writing state.
std::string myStateDumpPrefix
name components for periodic state
std::string myStateDumpSuffix
Static Protected Attributes
static MSNet * myInstance = 0
Unique instance of MSNet.
static const std::string STAGE_EVENTS
string constants for simstep stages
static const std::string STAGE_INSERTIONS
static const std::string STAGE_LANECHANGE
static const std::string STAGE_MOVEMENTS
Private Member Functions
GUIGlID createTLWrapper (MSTrafficLightLogic *tll)
creates a wrapper for the given logic and returns the GlID
void initTLMap ()
Initialises the tl-logic map and wrappers.
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
Friends
class GUIOSGBuilder
class GUITrafficLightLogicWrapper
Notification about vehicle state changes
void addVehicleStateListener (VehicleStateListener *listener)
Adds a vehicle states listener.
void removeVehicleStateListener (VehicleStateListener *listener)
Removes a vehicle states listener.
void informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to)
Informs all added listeners about a vehicle's state change.
enum VehicleState {
VEHICLE_STATE_BUILT, VEHICLE_STATE_DEPARTED, VEHICLE_STATE_STARTING_TELEPORT, VEHICLE_STATE_ENDING_TELEPORT,
VEHICLE_STATE_ARRIVED, VEHICLE_STATE_NEWROUTE, VEHICLE_STATE_STARTING_PARKING, VEHICLE_STATE_ENDING_PARKING,
VEHICLE_STATE_STARTING_STOP, VEHICLE_STATE_ENDING_STOP
}
Definition of a vehicle state.
Detailed Description
A MSNet extended by some values for usage within the gui.
This gui version of the network allows the retrieval of some more information than the normal network version does. Due to this, not only these retrieval, but also some further initialisation methods must have been implemented. Nonethenless, this class has almost the same functions as the MSNet-class.
Some microsimulation items are wrapped in certain classes to allow their drawing and their enumerated access. This enumeration is realised by inserting the wrapped items into vectors and is needed to fasten the network's drawing as only visible items are being drawn.
Definition at line 88 of file GUINet.h.
Member Typedef Documentation
Links2LogicMap
typedef std::map<MSLink*, std::string> GUINet::Links2LogicMap protected
Definition of a link-to-logic-id map.
Definition at line 361 of file GUINet.h.
Logics2WrapperMap
typedef std::map<MSTrafficLightLogic*, GUITrafficLightLogicWrapper*> GUINet::Logics2WrapperMap protected
Definition of a traffic light-to-wrapper map.
Definition at line 367 of file GUINet.h.
MSIntermodalRouter
typedef IntermodalRouter<MSEdge, MSLane, MSJunction, SUMOVehicle> MSNet::MSIntermodalRouter inherited
Definition at line 114 of file MSNet.h.
MSPedestrianRouterDijkstra
typedef PedestrianRouterDijkstra<MSEdge, MSLane, MSJunction, MSVehicle> MSNet::MSPedestrianRouterDijkstra inherited
Definition at line 113 of file MSNet.h.
Member Enumeration Documentation
SimulationState
enum MSNet::SimulationState inherited
Possible states of a simulation - running or stopped with different reasons.
Enumerator
SIMSTATE_LOADING
The simulation is loading.
SIMSTATE_RUNNING
The simulation is running.
SIMSTATE_END_STEP_REACHED
The final simulation step has been performed.
SIMSTATE_NO_FURTHER_VEHICLES
The simulation does not contain further vehicles.
SIMSTATE_CONNECTION_CLOSED
The connection to a client was closed by the client.
SIMSTATE_ERROR_IN_SIM
An error occured during the simulation step.
SIMSTATE_TOO_MANY_TELEPORTS
The simulation had too many teleports.
Definition at line 95 of file MSNet.h.
VehicleState
enum MSNet::VehicleState inherited
Definition of a vehicle state.
Enumerator
VEHICLE_STATE_BUILT
The vehicle was built, but has not yet departed.
VEHICLE_STATE_DEPARTED
The vehicle has departed (was inserted into the network)
VEHICLE_STATE_STARTING_TELEPORT
The vehicle started to teleport.
VEHICLE_STATE_ENDING_TELEPORT
The vehicle ended being teleported.
VEHICLE_STATE_ARRIVED
The vehicle arrived at his destination (is deleted)
VEHICLE_STATE_NEWROUTE
The vehicle got a new route.
VEHICLE_STATE_STARTING_PARKING
The vehicles starts to park.
VEHICLE_STATE_ENDING_PARKING
The vehicle ends to park.
VEHICLE_STATE_STARTING_STOP
The vehicles starts to stop.
VEHICLE_STATE_ENDING_STOP
The vehicle ends to stop.
Definition at line 482 of file MSNet.h.
Constructor & Destructor Documentation
GUINet()
GUINet::GUINet (MSVehicleControl * vc, MSEventControl * beginOfTimestepEvents, MSEventControl * endOfTimestepEvents, MSEventControl * insertionEvents)
Constructor.
Parameters
[in] vc The vehicle control to use
[in] beginOfTimestepEvents The event control to use for simulation step begin events
[in] endOfTimestepEvents The event control to use for simulation step end events
[in] insertionEvents The event control to use for insertion events
Exceptions
ProcessError If a network was already constructed
Definition at line 80 of file GUINet.cpp.
References GUIGlObjectStorage::gIDStorage, and GUIGlObjectStorage::setNetObject().
~GUINet()
GUINet::~GUINet ()
Destructor.
Definition at line 90 of file GUINet.cpp.
References GUIGlObject_AbstractAdd::clearDictionary(), MFXMutex::locked(), myDetectorWrapper, myJunctionWrapper, myLock, myLogics2Wrapper, and MFXMutex::unlock().
Member Function Documentation
adaptIntermodalRouter()
void MSNet::adaptIntermodalRouter (MSIntermodalRouter & router) static inherited
Definition at line 958 of file MSNet.cpp.
References MSInsertionControl::adaptIntermodalRouter(), MSVehicleControl::adaptIntermodalRouter(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::addAccess(), MSNet::getInsertionControl(), MSNet::getVehicleControl(), MSNet::myInstance, MSNet::myStoppingPlaces, SUMO_TAG_BUS_STOP, and SUMO_TAG_PARKING_AREA.
Referenced by MSNet::getIntermodalRouter(), and MSNet::VehicleStateListener::~VehicleStateListener().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
addRestriction()
void MSNet::addRestriction (const std::string & id, const SUMOVehicleClass svc, const double speed) inherited
Adds a restriction for an edge type.
Parameters
[in] id The id of the type
[in] svc The vehicle class the restriction refers to
[in] speed The restricted speed
Definition at line 297 of file MSNet.cpp.
References MSNet::myRestrictions.
Referenced by NLHandler::myStartElement(), and MSNet::setPermissionsFound().
addStoppingPlace()
bool MSNet::addStoppingPlace (const SumoXMLTag category, MSStoppingPlace * stop) inherited
Adds a stopping place.
If another stop with the same id and category exists, false is returned. Otherwise, the stop is added to the internal stopping place container.
This control gets responsible for deletion of the added stop.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Definition at line 857 of file MSNet.cpp.
References Named::getID(), MSNet::myStoppingPlaces, SUMO_TAG_BUS_STOP, and SUMO_TAG_TRAIN_STOP.
Referenced by GUITriggerBuilder::beginParkingArea(), NLTriggerBuilder::beginParkingArea(), GUITriggerBuilder::buildChargingStation(), NLTriggerBuilder::buildChargingStation(), GUITriggerBuilder::buildStoppingPlace(), NLTriggerBuilder::buildStoppingPlace(), and MSNet::getShapeContainer().
addVehicleStateListener()
void MSNet::addVehicleStateListener (VehicleStateListener * listener) inherited
Adds a vehicle states listener.
Parameters
[in] listener The listener to add
Definition at line 832 of file MSNet.cpp.
References MSNet::myVehicleStateListeners.
Referenced by MSDevice_Vehroutes::init(), TraCIServer::openSocket(), and MSNet::VehicleStateListener::~VehicleStateListener().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
checkElevation()
bool MSNet::checkElevation () protected inherited
check all lanes for elevation data
Definition at line 986 of file MSNet.cpp.
References MSEdgeControl::getEdges(), and MSNet::myEdges.
Referenced by MSNet::closeBuilding(), and MSNet::version().
clearAll()
void MSNet::clearAll () static inherited
Clears all dictionaries.
Todo:
Try to move all this to the destructor
Definition at line 621 of file MSNet.cpp.
References MSTrigger::cleanup(), MSPModel::cleanup(), MSCModel_NonInteracting::cleanup(), MSDevice_BTsender::cleanup(), MSCalibrator::cleanup(), TraCIServer::cleanup(), libsumo::Helper::cleanup(), MSDevice_SSM::cleanup(), MSDevice::cleanupAll(), MSRoute::clear(), MSLane::clear(), MSEdge::clear(), TraCIServer::getInstance(), and MSVehicleTransfer::getInstance().
Referenced by GUILoadThread::run(), MSNet::setPermissionsFound(), and MSNet::~MSNet().
closeBuilding()
void MSNet::closeBuilding (const OptionsCont & oc, MSEdgeControl * edges, MSJunctionControl * junctions, SUMORouteLoaderControl * routeLoaders, MSTLLogicControl * tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles, bool hasInternalLinks, bool hasNeighs, bool lefthand, double version) inherited
Closes the network's building process.
Assigns the structures built while loading to this network.
Parameters
[in] oc The options to use
[in] edges The control of edges which belong to this network
[in] junctions The control of junctions which belong to this network
[in] routeLoaders The route loaders used
[in] tlc The control of traffic lights which belong to this network
[in] stateDumpTimes List of time steps at which state shall be written
[in] stateDumpFiles Filenames for states
[in] hasInternalLinks Whether the network actually contains internal links
[in] lefthand Whether the network was built for left-hand traffic
[in] version The network version
Todo:
Try to move all this to the constructor?
Definition at line 219 of file MSNet.cpp.
References MSNet::checkElevation(), SysUtils::getCurrentMillis(), OptionsCont::getString(), MSGlobals::gLateralResolution, MSNet::hasInternalLinks(), MSNet::lefthand(), MSNet::myEdges, MSNet::myHasElevation, MSNet::myHasInternalLinks, MSNet::myJunctions, MSNet::myLefthand, MSNet::myLogExecutionTime, MSNet::myLogics, MSNet::myRouteLoaders, MSNet::mySimBeginMillis, MSNet::myStateDumpFiles, MSNet::myStateDumpPeriod, MSNet::myStateDumpPrefix, MSNet::myStateDumpSuffix, MSNet::myStateDumpTimes, MSNet::myVersion, MSJunctionControl::postloadInitContainer(), string2time(), MSNet::version(), and WRITE_WARNING.
Referenced by NLBuilder::buildNet().
closeSimulation()
void MSNet::closeSimulation (SUMOTime start) inherited
Closes the simulation (all files, connections, etc.)
Writes also performance output
Parameters
[in] start The step the simulation was started with
Todo:
What exceptions may occure?
Definition at line 372 of file MSNet.cpp.
References MSDetectorControl::close(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSDevice_Vehroutes::generateOutputForUnfinished(), MSVehicleControl::getCollisionCount(), SysUtils::getCurrentMillis(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getEmergencyStops(), MSTransportableControl::getJammedNumber(), MSTransportableControl::getLoadedNumber(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSTransportableControl::getRunningNumber(), MSVehicleControl::getRunningVehicleNo(), MSVehicleControl::getTeleportCount(), MSVehicleControl::getTeleportsJam(), MSVehicleControl::getTeleportsWrongLane(), MSVehicleControl::getTeleportsYield(), MSInsertionControl::getWaitingVehicleNo(), joinToString(), MSNet::myDetectorControl, MSNet::myInserter, MSNet::myLogExecutionTime, MSNet::myPersonControl, MSNet::mySimBeginMillis, MSNet::myStep, MSNet::myVehicleControl, MSNet::myVehiclesMoved, MSDevice_Tripinfo::printStatistics(), STEPS2TIME, toString(), WRITE_MESSAGE, and MSNet::writeChargingStationOutput().
Referenced by GUIRunThread::deleteSim(), MSNet::setPermissionsFound(), and MSNet::simulate().
createTLWrapper()
GUIGlID GUINet::createTLWrapper (MSTrafficLightLogic * tll) private
creates a wrapper for the given logic and returns the GlID
Definition at line 150 of file GUINet.cpp.
References SUMORTree::addAdditionalGLObject(), GUIGlObject::getGlID(), Named::getID(), MSTrafficLightLogic::getLinks(), GUITrafficLightLogicWrapper, myGrid, myLinks2Logic, MSNet::myLogics, and myLogics2Wrapper.
Referenced by getVisualisationSpeedUp(), initTLMap(), and GUITrafficLightLogicWrapper::switchTLSLogic().
drawGL()
void GUINet::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 496 of file GUINet.cpp.
drawGLAdditional()
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 153 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
getAvgDepartDelay()
double GUINet::getAvgDepartDelay () const inline
Definition at line 221 of file GUINet.h.
References MSDevice_Tripinfo::getAvgDepartDelay().
Referenced by getParameterWindow().
getAvgDuration()
double GUINet::getAvgDuration () const inline
Definition at line 212 of file GUINet.h.
References MSDevice_Tripinfo::getAvgDuration().
Referenced by getParameterWindow().
getAvgRouteLength()
double GUINet::getAvgRouteLength () const inline
Definition at line 209 of file GUINet.h.
References MSDevice_Tripinfo::getAvgRouteLength().
Referenced by getParameterWindow().
getAvgTimeLoss()
double GUINet::getAvgTimeLoss () const inline
Definition at line 218 of file GUINet.h.
References MSDevice_Tripinfo::getAvgTimeLoss().
Referenced by getParameterWindow().
getAvgTripSpeed()
double GUINet::getAvgTripSpeed () const inline
Definition at line 224 of file GUINet.h.
References MSDevice_Tripinfo::getAvgDuration(), and MSDevice_Tripinfo::getAvgRouteLength().
Referenced by getParameterWindow().
getAvgWaitingTime()
double GUINet::getAvgWaitingTime () const inline
Definition at line 215 of file GUINet.h.
References MSDevice_Tripinfo::getAvgWaitingTime().
Referenced by getParameterWindow().
getAvgWalkDuration()
double GUINet::getAvgWalkDuration () const inline
Definition at line 230 of file GUINet.h.
References MSDevice_Tripinfo::getAvgWalkDuration().
Referenced by getParameterWindow().
getAvgWalkRouteLength()
double GUINet::getAvgWalkRouteLength () const inline
Definition at line 227 of file GUINet.h.
References MSDevice_Tripinfo::getAvgWalkRouteLength().
Referenced by getParameterWindow().
getAvgWalkTimeLoss()
double GUINet::getAvgWalkTimeLoss () const inline
Definition at line 233 of file GUINet.h.
References MSDevice_Tripinfo::getAvgWalkTimeLoss(), getContainerControl(), getJunctionIDs(), getLinkTLID(), getLinkTLIndex(), getPersonControl(), getTLSIDs(), and initGUIStructures().
Referenced by getParameterWindow().
getBeginOfTimestepEvents()
MSEventControl* MSNet::getBeginOfTimestepEvents () inline inherited
Returns the event control for events executed at the begin of a time step.
Returns
The control responsible for events that are executed at the begin of a time step
See also
MSEventControl
myBeginOfTimestepEvents
Definition at line 399 of file MSNet.h.
References MSNet::myBeginOfTimestepEvents.
Referenced by MSPModel_NonInteracting::add(), MSCModel_NonInteracting::add(), NLTriggerBuilder::buildVaporizer(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTLLogicControl::closeWAUT(), MSLaneSpeedTrigger::init(), MSPModel_Striping::MSPModel_Striping(), MSTrafficLightLogic::MSTrafficLightLogic(), MSTriggeredRerouter::myEndElement(), MSDevice_Routing::notifyEnter(), and MSTriggeredRerouter::setPermissions().
getBoundary()
const Boundary & GUINet::getBoundary () const
returns the bounder of the network
Definition at line 113 of file GUINet.cpp.
References myBoundary.
Referenced by getCenteringBoundary().
getCenteringBoundary()
Boundary GUINet::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 500 of file GUINet.cpp.
References getBoundary().
getContainerControl()
MSTransportableControl & GUINet::getContainerControl () virtual
Returns the container control.
If the container control does not exist, yet, it is created.
Returns
The container control
See also
MSContainerControl
myContainerControl
Reimplemented from MSNet.
Definition at line 128 of file GUINet.cpp.
References MSNet::myContainerControl.
Referenced by getAvgWalkTimeLoss(), and GUIApplicationWindow::handleEvent_SimulationStep().
getCurrentTimeStep()
SUMOTime MSNet::getCurrentTimeStep () const inline inherited
Returns the current simulation step.
Returns
the current simulation step
Definition at line 253 of file MSNet.h.
References MSNet::myStep.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), libsumo::Person::add(), libsumo::Vehicle::add(), GUIEdge::addRerouter(), MSDevice_Vehroutes::addRoute(), MSTLLogicControl::addWAUTJunction(), MSTransportableControl::boardAnyWaiting(), NLDetectorBuilder::buildE2Detector(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSTLLogicControl::closeWAUT(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), TraCIServer::dispatchCommand(), MSActuatedTrafficLightLogic::duration(), MSVehicle::enterLaneAtInsertion(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVehicle::executeMove(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), MSActuatedTrafficLightLogic::gapControl(), MSTransportable::getAngle(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentOccupancy(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), GUIApplicationWindow::getCurrentSimTime(), MSLaneSpeedTrigger::getCurrentSpeed(), libsumo::Simulation::getCurrentTime(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSTransportable::getEdgePos(), MSLane::getFirstVehicleInformation(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), libsumo::Lane::getLinks(), MESegment::getMeanSpeed(), MSInsertionControl::getPendingEmits(), MSTransportable::getPosition(), MSVehicle::getPosition(), MSTrafficLightLogic::getSpentDuration(), MSTransportable::getWaitingSeconds(), MSLink::getZipperSpeed(), GUIApplicationWindow::handleEvent_SimulationStep(), MSSwarmTrafficLightLogic::init(), MSLaneSpeedTrigger::init(), MSDevice_Routing::initEdgeWeights(), TraCIServer::initialiseSubscription(), MSTLLogicControl::initWautSwitch(), MSLane::isInsertionSuccess(), MSPerson::Influencer::isRemoteControlled(), MSVehicle::Influencer::isRemoteControlled(), MSTransportableControl::loadAnyWaiting(), GUIRunThread::makeStep(), MSPModel_Striping::MSPModel_Striping(), MSDevice_Vehroutes::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Transportable::notifyMove(), GUIApplicationWindow::onCmdTimeToggle(), MSBaseVehicle::onDepart(), TraCIServer::postProcessSimulationStep(), MESegment::prepareDetectorForWriting(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSTriggeredRerouter::rerouteParkingArea(), MSVehicle::resetActionOffset(), MSSOTLTrafficLightLogic::resetCTS(), MSTrafficLightLogic::resetLinkStates(), GUIRunThread::run(), TraCIServer::sendOutputToAll(), libsumo::TrafficLight::setPhase(), libsumo::TrafficLight::setPhaseDuration(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSPhasedTrafficLightLogic::setStep(), MSSOTLTrafficLightLogic::setupCTS(), MSNet::simulate(), MSSimpleTrafficLightLogic::trySwitch(), MSDelayBasedTrafficLightLogic::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateActionOffset(), MSSOTLTrafficLightLogic::updateCTS(), MSRailCrossing::updateCurrentPhase(), MSSwarmTrafficLightLogic::updateSensitivities(), and MSVehicle::wasRemoteControlled().
getDetectorControl()
MSDetectorControl& MSNet::getDetectorControl () inline inherited
Returns the detector control.
Returns
The detector control
See also
MSDetectorControl
myDetectorControl
Definition at line 369 of file MSNet.h.
References MSNet::myDetectorControl.
Referenced by MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::buildRouteProbe(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NLDetectorBuilder::createEdgeLaneMeanData(), NLDetectorBuilder::endE3Detector(), libsumo::MultiEntryExit::getDetector(), libsumo::LaneArea::getDetector(), libsumo::InductionLoop::getDetector(), libsumo::LaneArea::getIDCount(), libsumo::MultiEntryExit::getIDCount(), libsumo::InductionLoop::getIDCount(), libsumo::MultiEntryExit::getIDList(), libsumo::LaneArea::getIDList(), libsumo::InductionLoop::getIDList(), TraCIServerAPI_InductionLoop::getPosition(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), and NLTriggerBuilder::parseAndBuildCalibrator().
getEdgeControl()
MSEdgeControl& MSNet::getEdgeControl () inline inherited
Returns the edge control.
Returns
The edge control
See also
MSEdgeControl
myEdges
Definition at line 349 of file MSNet.h.
References MSNet::myEdges.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), NLBuilder::build(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), libsumo::Helper::convertCartesianToRoadMap(), MSLane::incorporateVehicle(), MSMeanData::init(), MSFCDExport::write(), MSQueueExport::writeEdge(), and MSFullExport::writeEdge().
getEffort()
double MSNet::getEffort (const MSEdge *const e, const SUMOVehicle *const v, double t) static inherited
Returns the effort to pass an edge.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the effort shall be returned [s]
Returns
The effort (abstract) for an edge
See also
DijkstraRouter_ByProxi
Definition at line 136 of file MSNet.cpp.
References MSNet::getInstance(), MSVehicle::getWeightsStorage(), MSNet::getWeightsStorage(), and MSEdgeWeightsStorage::retrieveExistingEffort().
Referenced by MSNet::getRouterEffort(), and MSNet::VehicleStateListener::~VehicleStateListener().
getEndOfTimestepEvents()
MSEventControl* MSNet::getEndOfTimestepEvents () inline inherited
Returns the event control for events executed at the end of a time step.
Returns
The control responsible for events that are executed at the end of a time step
See also
MSEventControl
myEndOfTimestepEvents
Definition at line 409 of file MSNet.h.
References MSNet::myEndOfTimestepEvents.
Referenced by MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), MSDevice_Routing::buildVehicleDevices(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), MSCalibrator::init(), and MSVTypeProbe::MSVTypeProbe().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getGUIInstance()
GUINet * GUINet::getGUIInstance () static
Returns the pointer to the unique instance of GUINet (singleton).
Returns
Pointer to the unique GUINet-instance
Exceptions
ProcessError If a network was not yet constructed
Definition at line 506 of file GUINet.cpp.
References MSNet::getInstance().
Referenced by GUIEdge::addRerouter(), GUIViewTraffic::doPaintGL(), GUIEdge::drawMesoVehicles(), getVisualisationSpeedUp(), GUIApplicationWindow::onCmdShowStats(), and GUITrafficLightLogicWrapper::switchTLSLogic().
getGUIMEVehicleControl()
GUIMEVehicleControl * GUINet::getGUIMEVehicleControl ()
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 533 of file GUINet.cpp.
References myEdgeWrapper, myJunctionWrapper, and MSNet::myVehicleControl.
Referenced by GUIEdge::drawMesoVehicles(), and getVisualisationSpeedUp().
getGUIVehicleControl()
GUIVehicleControl * GUINet::getGUIVehicleControl ()
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 516 of file GUINet.cpp.
References MSNet::myVehicleControl.
Referenced by getVisualisationSpeedUp().
getHaltingVehicleNumber()
int MSNet::getHaltingVehicleNumber () const protected inherited
count number of standing vehicles in the network
Definition at line 1000 of file MSNet.cpp.
References SUMOVehicle::getSpeed(), SUMOVehicle::isOnRoad(), SUMOVehicle::isRemoteControlled(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), MSNet::myVehicleControl, and SUMO_const_haltingSpeed.
Referenced by getParameterWindow(), MSNet::version(), and MSNet::writeOutput().
getIdleDuration()
int GUINet::getIdleDuration () const
Returns the duration of the last step's idle part (in ms)
Definition at line 376 of file GUINet.cpp.
References myLastIdleDuration.
Referenced by getParameterWindow().
getInsertionControl()
MSInsertionControl& MSNet::getInsertionControl () inline inherited
Returns the insertion control.
Returns
The insertion control
See also
MSInsertionControl
myInserter
Definition at line 359 of file MSNet.h.
References MSNet::myInserter.
Referenced by MSNet::adaptIntermodalRouter(), libsumo::Vehicle::add(), MSLane::checkFailure(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), GUIEdge::getColorValue(), GUILane::getColorValue(), libsumo::Simulation::getMinExpectedNumber(), getParameterWindow(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GUIApplicationWindow::handleEvent_SimulationStep(), MSLane::isInsertionSuccess(), MSVehicleTransfer::loadState(), libsumo::Vehicle::moveTo(), libsumo::Vehicle::moveToXY(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), and MSBaseVehicle::reroute().
getInsertionEvents()
MSEventControl* MSNet::getInsertionEvents () inline inherited
Returns the event control for insertion events.
Returns
The control responsible for insertion events
See also
MSEventControl
myInsertionEvents
Definition at line 419 of file MSNet.h.
References MSNet::myInsertionEvents.
Referenced by MSDevice_Routing::MSDevice_Routing().
getInstance()
MSNet * MSNet::getInstance (void) static inherited
Returns the pointer to the unique instance of MSNet (singleton).
Returns
Pointer to the unique MSNet-instance
Exceptions
ProcessError If a network was not yet constructed
Definition at line 167 of file MSNet.cpp.
References MSNet::myInstance.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSTransportable::Stage_Waiting::abort(), MSTransportableControl::abortWaitingForVehicle(), MSDevice_Routing::adaptEdgeEfforts(), libsumo::Polygon::add(), LaneStoringVisitor::add(), libsumo::POI::add(), MSPModel_Striping::add(), libsumo::Person::add(), MSVehicleTransfer::add(), libsumo::Vehicle::add(), MSChargingStation::addChargeValueForOutput(), libsumo::Edge::addEffort(), MSTrafficLightLogic::addLink(), MSTLLogicControl::TLSLogicVariants::addLogic(), MSRouteHandler::addPersonTrip(), GUIEdge::addRerouter(), MSDevice_Vehroutes::addRoute(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), libsumo::Edge::addTravelTime(), MSTLLogicControl::addWAUTJunction(), libsumo::Person::appendDrivingStage(), libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportableControl::boardAnyWaiting(), MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NLTriggerBuilder::buildVaporizer(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSDevice_Routing::buildVehicleDevices(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), libsumo::Vehicle::changeLane(), MELoop::changeSegment(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), libsumo::Vehicle::changeTarget(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSTLLogicControl::closeWAUT(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), libsumo::Helper::convertCartesianToRoadMap(), NLDetectorBuilder::createEdgeLaneMeanData(), MSCalibrator::currentFlow(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSInsertionControl::determineCandidates(), TraCIServer::dispatchCommand(), GUITrafficLightLogicWrapper::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawMarkings(), GUILane::drawTLSLinkNo(), MSVehicleType::duplicateType(), MSActuatedTrafficLightLogic::duration(), GUITriggerBuilder::endParkingArea(), MSVehicle::enterLaneAtInsertion(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), MSActuatedTrafficLightLogic::gapControl(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), MSTransportable::getAngle(), MSVehicle::getBackPositionOnLane(), GUIEdge::getColorValue(), GUILane::getColorValue(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), MSLaneSpeedTrigger::getCurrentSpeed(), MSInductLoop::getCurrentSpeed(), libsumo::Simulation::getCurrentTime(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSInductLoop::getCurrentVehicleIDs(), libsumo::MultiEntryExit::getDetector(), libsumo::LaneArea::getDetector(), libsumo::InductionLoop::getDetector(), MSTransportable::getEdgePos(), MSNet::getEffort(), MSLane::getFirstVehicleInformation(), getGUIInstance(), libsumo::MultiEntryExit::getIDCount(), libsumo::LaneArea::getIDCount(), libsumo::InductionLoop::getIDCount(), libsumo::Person::getIDCount(), libsumo::VehicleType::getIDList(), libsumo::Polygon::getIDList(), libsumo::LaneArea::getIDList(), libsumo::MultiEntryExit::getIDList(), libsumo::TrafficLight::getIDList(), libsumo::InductionLoop::getIDList(), libsumo::Person::getIDList(), libsumo::POI::getIDList(), libsumo::Junction::getIDList(), libsumo::Vehicle::getIDList(), libsumo::Junction::getJunction(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), libsumo::Lane::getLinks(), GUILane::getLoadedEdgeWeight(), MSLane::getMaximumBrakeDist(), MESegment::getMeanSpeed(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), libsumo::Simulation::getMinExpectedNumber(), MSPModel::getModel(), MSCModel_NonInteracting::getModel(), MSPModel_Striping::getNextLane(), libsumo::Simulation::getParameter(), MSInsertionControl::getPendingEmits(), libsumo::Person::getPerson(), libsumo::Edge::getPersonIDs(), MSTLLogicControl::getPhaseDef(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_Vehicle::getPosition(), TraCIServerAPI_Person::getPosition(), MSPModel_NonInteracting::PState::getPosition(), MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSTransportable::getPosition(), MSVehicle::getPosition(), MSVTKExport::getPositions(), MSVehicle::Influencer::getRouterTT(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), MSBaseVehicle::getSingularType(), MSVTKExport::getSpeed(), MSTrafficLightLogic::getSpentDuration(), GUILane::getStoredEdgeTravelTime(), MSEdge::getSuccessors(), libsumo::TrafficLight::getTLS(), MSNet::getTravelTime(), MSEdge::getTravelTimeStatic(), libsumo::InductionLoop::getTree(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), libsumo::POI::getTree(), libsumo::Vehicle::getVehicle(), libsumo::InductionLoop::getVehicleData(), libsumo::VehicleType::getVType(), MSTransportable::getWaitingSeconds(), MSLink::getZipperSpeed(), GUIBusStop::GUIBusStop(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), MSLane::handleCollisionBetween(), MSPModel_Striping::PState::ignoreRed(), MSVehicle::ignoreRed(), MSLane::incorporateVehicle(), MSVehicle::influenceChangeDecision(), MSRailCrossing::init(), MSDevice_Vehroutes::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSLaneSpeedTrigger::init(), MSCalibrator::init(), MSMeanData::init(), MSDevice_Routing::initEdgeWeights(), TraCIServer::initialiseSubscription(), MSLane::initRestrictions(), MSTLLogicControl::initWautSwitch(), MSEdge::insertVehicle(), MSLane::isInsertionSuccess(), libsumo::Vehicle::isOnInit(), MSPerson::Influencer::isRemoteControlled(), MSVehicle::Influencer::isRemoteControlled(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::leaveLane(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSTransportableControl::loadAnyWaiting(), MSVehicleTransfer::loadState(), libsumo::Vehicle::moveTo(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), MSDevice_Routing::MSDevice_Routing(), MSParkingArea::MSParkingArea(), MSTrafficLightLogic::MSTrafficLightLogic(), MSVTypeProbe::MSVTypeProbe(), GUITriggeredRerouter::myEndElement(), MSRouteHandler::myEndElement(), MSTriggeredRerouter::myEndElement(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSTriggeredRerouter::myStartElement(), MSDevice_Transportable::notifyEnter(), MSDevice_Vehroutes::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Routing::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Transportable::notifyMove(), MSDevice_Battery::notifyMove(), MSDevice_Bluelight::notifyMove(), MSE3Collector::MSE3EntryReminder::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), GUIViewTraffic::onGamingClick(), TraCIServer::openSocket(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseWalkPositions(), MSVehicle::planMoveInternal(), libsumo::Helper::postProcessRemoteControl(), MSPerson::Influencer::postProcessRemoteControl(), TraCIServer::postProcessSimulationStep(), MESegment::prepareDetectorForWriting(), MSPerson::MSPersonStage_Walking::proceed(), TraCIServer::processCommandsUntilSimStep(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_Simulation::processGet(), MSVehicle::processLaneAdvances(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), MSVehicle::processTraCISpeedControl(), MSPModel_Striping::PState::PState(), MESegment::receive(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), libsumo::Polygon::remove(), libsumo::POI::remove(), MSCalibrator::removePending(), MSTransportable::removeStage(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceVehicleType(), MSTransportable::replaceVehicleType(), MSDevice_Routing::reroute(), MSBaseVehicle::reroute(), libsumo::Vehicle::rerouteEffort(), MSTriggeredRerouter::rerouteParkingArea(), libsumo::Person::rerouteTraveltime(), libsumo::Vehicle::rerouteTraveltime(), MSVehicle::resetActionOffset(), MSSOTLTrafficLightLogic::resetCTS(), MSTrafficLightLogic::resetLinkStates(), MSVehicle::resumeFromStopping(), libsumo::Edge::retrieveExistingEffort(), libsumo::Edge::retrieveExistingTravelTime(), MSContainer::routeOutput(), MSPerson::routeOutput(), MSStateHandler::saveState(), MSVehicleControl::scheduleVehicleRemoval(), TraCIServer::sendOutputToAll(), MSVehicleType::setActionStepLength(), libsumo::TrafficLight::setCompleteRedYellowGreenDefinition(), GUIBaseVehicle::setFunctionalColor(), MSLaneSpeedTrigger::setOverriding(), MSLaneSpeedTrigger::setOverridingValue(), MSTriggeredRerouter::setPermissions(), libsumo::TrafficLight::setPhase(), libsumo::TrafficLight::setPhaseDuration(), libsumo::TrafficLight::setProgram(), libsumo::TrafficLight::setRedYellowGreenState(), libsumo::Polygon::setShape(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSPhasedTrafficLightLogic::setStep(), libsumo::Person::setType(), libsumo::Vehicle::setType(), MSSOTLTrafficLightLogic::setupCTS(), libsumo::Simulation::simulationStep(), libsumo::Vehicle::slowDown(), MSStopOut::stopEnded(), MSStopOut::stopStarted(), MSLane::succLinkSec(), MSTLLogicControl::TLSLogicVariants::switchTo(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSInsertionControl::tryInsert(), MSSimpleTrafficLightLogic::trySwitch(), MSDelayBasedTrafficLightLogic::trySwitch(), MSRailCrossing::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSRailSignal::trySwitch(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateActionOffset(), MSSOTLTrafficLightLogic::updateCTS(), MSRailCrossing::updateCurrentPhase(), MSSOTLTrafficLightLogic::updateDecayThreshold(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateShadowLane(), MSPModel_Striping::usingInternalLanes(), MSVehicleControl::vehicleDeparted(), MSPModel_Striping::PState::walk(), MSVehicle::wasRemoteControlled(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), MSDevice_Vehroutes::writeOutput(), MSNet::writeOutput(), MSFullExport::writeTLS(), MSFullExport::writeVehicles(), MSDevice_BTreceiver::BTreceiverUpdate::~BTreceiverUpdate(), MSDevice_Routing::~MSDevice_Routing(), MSTransportable::~MSTransportable(), and MSVehicle::~MSVehicle().
getIntermodalRouter()
MSNet::MSIntermodalRouter & MSNet::getIntermodalRouter (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 938 of file MSNet.cpp.
References MSNet::adaptIntermodalRouter(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::ALL_JUNCTIONS, OptionsCont::getOptions(), MSNet::myIntermodalRouter, IntermodalRouter< E, L, N, V, INTERNALROUTER >::PARKING_AREAS, IntermodalRouter< E, L, N, V, INTERNALROUTER >::prohibit(), and IntermodalRouter< E, L, N, V, INTERNALROUTER >::PT_STOPS.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
getJunctionControl()
MSJunctionControl& MSNet::getJunctionControl () inline inherited
Returns the junctions control.
Returns
The junctions control
See also
MSJunctionControl
myJunctions
Definition at line 389 of file MSNet.h.
References MSNet::myJunctions.
Referenced by libsumo::Junction::getIDList(), and libsumo::Junction::getJunction().
getJunctionIDs()
std::vector< GUIGlID > GUINet::getJunctionIDs (bool includeInternal) const
Definition at line 232 of file GUINet.cpp.
References myJunctionWrapper.
Referenced by getAvgWalkTimeLoss(), and getParameterWindow().
getJunctionPosition()
Position GUINet::getJunctionPosition (const std::string & name) const
returns the position of a junction
Definition at line 177 of file GUINet.cpp.
References NamedObjectCont< T >::get(), MSJunction::getPosition(), and MSNet::myJunctions.
getLanesRTree()
const NamedRTree & MSNet::getLanesRTree () const inherited
Returns an RTree that contains lane IDs.
Returns
An Rtree containing lane IDs
Definition at line 976 of file MSNet.cpp.
References MSLane::fill(), and MSNet::myLanesRTree.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
getLinkTLID()
int GUINet::getLinkTLID (MSLink * link) const
Returns the gl-id of the traffic light that controls the given link valid only if the link is controlled by a tls
Definition at line 190 of file GUINet.cpp.
References MSTLLogicControl::getActive(), myLinks2Logic, MSNet::myLogics, and myLogics2Wrapper.
Referenced by GUILane::drawLinkRule(), and getAvgWalkTimeLoss().
getLinkTLIndex()
int GUINet::getLinkTLIndex (MSLink * link) const
Returns the index of the link within the junction that controls the given link; Returns -1 if the link is not controlled by a tls
Definition at line 205 of file GUINet.cpp.
References MSTLLogicControl::getActive(), myLinks2Logic, MSNet::myLogics, and myLogics2Wrapper.
Referenced by GUILane::drawTLSLinkNo(), and getAvgWalkTimeLoss().
getMeanRTFactor()
double GUINet::getMeanRTFactor (int duration) const
Returns the simulation speed as a factor to real time.
Definition at line 358 of file GUINet.cpp.
References myOverallSimDuration.
getMeanUPS()
double GUINet::getMeanUPS () const
Returns the update per seconds rate.
Definition at line 367 of file GUINet.cpp.
References myOverallSimDuration, and MSNet::myVehiclesMoved.
Referenced by getParameterWindow().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNERerouter::getParentName(), GNEPoly::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getParameterWindow()
GUIParameterTableWindow * GUINet::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 416 of file GUINet.cpp.
References GUIParameterTableWindow::closeBuilding(), getAvgDepartDelay(), getAvgDuration(), getAvgRouteLength(), getAvgTimeLoss(), getAvgTripSpeed(), getAvgWaitingTime(), getAvgWalkDuration(), getAvgWalkRouteLength(), getAvgWalkTimeLoss(), MSVehicleControl::getCollisionCount(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getEndedVehicleNo(), MSNet::getHaltingVehicleNumber(), getIdleDuration(), GUIEdge::getIDs(), MSNet::getInsertionControl(), MSTransportableControl::getJammedNumber(), getJunctionIDs(), MSTransportableControl::getLoadedNumber(), MSVehicleControl::getLoadedVehicleNo(), getMeanUPS(), OptionsCont::getOptions(), getPersonControl(), getRTFactor(), MSTransportableControl::getRunningNumber(), MSVehicleControl::getRunningVehicleNo(), getSimDuration(), MSVehicleControl::getTeleportCount(), GUIEdge::getTotalLength(), getUPS(), MSNet::getVehicleControl(), MSNet::getVehicleMeanSpeed(), MSNet::getVehicleMeanSpeedRelative(), MSInsertionControl::getWaitingVehicleNo(), getWholeDuration(), MSNet::logSimulationDuration(), GUIParameterTableWindow::mkItem(), MSNet::myPersonControl, MSNet::myVersion, and toString().
Referenced by GUIApplicationWindow::onCmdShowStats().
getParentName()
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEPoly, GNERerouter, GNEPOILane, GNEVariableSpeedSign, GNENetElement, GNEPOI, GNERouteProbe, GNEStoppingPlace, GNEDetector, GUILane, GNEDetectorE3, GNEVaporizer, and GNELane.
Definition at line 114 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
getPedestrianRouter()
MSNet::MSPedestrianRouterDijkstra & MSNet::getPedestrianRouter (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 928 of file MSNet.cpp.
References MSNet::myPedestrianRouter, and PedestrianRouter< E, L, N, V, INTERNALROUTER >::prohibit().
Referenced by MSRouteHandler::addPersonTrip(), libsumo::Simulation::findIntermodalRoute(), MSPModel_Striping::getNextLane(), MSPModel_Striping::PState::PState(), libsumo::Person::rerouteTraveltime(), and MSNet::VehicleStateListener::~VehicleStateListener().
getPersonControl()
MSTransportableControl & GUINet::getPersonControl () virtual
Returns the person control.
If the person control does not exist, yet, it is created.
Returns
The person control
See also
MSPersonControl
myPersonControl
Reimplemented from MSNet.
Definition at line 119 of file GUINet.cpp.
References MSNet::myPersonControl.
Referenced by getAvgWalkTimeLoss(), getParameterWindow(), and GUIApplicationWindow::handleEvent_SimulationStep().
getPopUpMenu()
GUIGLObjectPopupMenu * GUINet::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 404 of file GUINet.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), and GUIGlObject::buildShowParamsPopupEntry().
getRestrictions()
const std::map< SUMOVehicleClass, double > * MSNet::getRestrictions (const std::string & id) const inherited
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
Parameters
[in] id The id of the type
Returns
The mapping of vehicle classes to maximum speeds
Definition at line 303 of file MSNet.cpp.
References MSNet::myRestrictions.
Referenced by MSLane::initRestrictions(), and MSNet::setPermissionsFound().
getRouterEffort()
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterEffort (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 917 of file MSNet.cpp.
References MSEdge::getAllEdges(), MSNet::getEffort(), MSNet::getTravelTime(), and MSNet::myRouterEffort.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
getRouterTT()
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterTT (const MSEdgeVector & prohibited = MSEdgeVector()) const inherited
Definition at line 897 of file MSNet.cpp.
References MSEdge::getAllEdges(), OptionsCont::getOptions(), OptionsCont::getString(), MSNet::getTravelTime(), MSNet::myRouterTT, and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), TraCIServerAPI_Simulation::commandDistanceRequest(), libsumo::Simulation::findRoute(), MSVehicle::Influencer::getRouterTT(), MSTriggeredRerouter::notifyEnter(), MSTriggeredRerouter::rerouteParkingArea(), and MSNet::VehicleStateListener::~VehicleStateListener().
getRTFactor()
double GUINet::getRTFactor () const
Returns the simulation speed as a factor to real time.
Definition at line 340 of file GUINet.cpp.
References DELTA_T, and myLastSimDuration.
Referenced by getParameterWindow().
getShapeContainer()
ShapeContainer& MSNet::getShapeContainer () inline inherited
Returns the shapes container.
Returns
The shapes container
See also
ShapeContainer
myShapeContainer
Definition at line 429 of file MSNet.h.
References MSNet::addStoppingPlace(), MSNet::getStoppingPlace(), MSNet::getStoppingPlaceID(), MSNet::getWeightsStorage(), MSNet::myShapeContainer, and MSNet::writeChargingStationOutput().
Referenced by libsumo::Polygon::add(), libsumo::POI::add(), NLHandler::addDistrict(), NLBuilder::build(), libsumo::Polygon::getIDList(), libsumo::POI::getIDList(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), libsumo::Polygon::getTree(), libsumo::POI::getTree(), GUISUMOViewParent::onCmdLocate(), GUIApplicationWindow::onCmdOpenShapes(), libsumo::Polygon::remove(), libsumo::POI::remove(), and libsumo::Polygon::setShape().
getSimDuration()
int GUINet::getSimDuration () const
Returns the duration of the last step's simulation part (in ms)
Returns
How long it took to compute the last step
Definition at line 326 of file GUINet.cpp.
References myLastSimDuration.
Referenced by getParameterWindow().
getStateMessage()
std::string MSNet::getStateMessage (MSNet::SimulationState state) static inherited
Returns the message to show if a certain state occurs.
Returns
Readable description of the state
Definition at line 598 of file MSNet.cpp.
References MSNet::SIMSTATE_CONNECTION_CLOSED, MSNet::SIMSTATE_END_STEP_REACHED, MSNet::SIMSTATE_ERROR_IN_SIM, MSNet::SIMSTATE_LOADING, MSNet::SIMSTATE_NO_FURTHER_VEHICLES, MSNet::SIMSTATE_RUNNING, and MSNet::SIMSTATE_TOO_MANY_TELEPORTS.
Referenced by GUIApplicationWindow::handleEvent_SimulationEnded(), GUIRunThread::makeStep(), MSNet::setPermissionsFound(), and MSNet::simulate().
getStoppingPlace()
MSStoppingPlace * MSNet::getStoppingPlace (const std::string & id, const SumoXMLTag category) const inherited
Returns the named stopping place of the given category.
Parameters
[in] id The id of the stop to return.
[in] category The type of stop
Returns
The named stop, or 0 if no such stop exists
Definition at line 863 of file MSNet.cpp.
References MSNet::myStoppingPlaces.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), libsumo::Person::appendDrivingStage(), libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), libsumo::Simulation::getParameter(), MSNet::getShapeContainer(), MSRouteHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSDevice_Battery::notifyMove(), MSRouteHandler::parseWalkPositions(), and TraCIServerAPI_Simulation::processGet().
getStoppingPlaceID()
std::string MSNet::getStoppingPlaceID (const MSLane * lane, const double pos, const SumoXMLTag category) const inherited
Returns the stop of the given category close to the given position.
Parameters
[in] lane the lane of the stop to return.
[in] pos the position of the stop to return.
[in] category The type of stop
Returns
The stop id on the location, or "" if no such stop exists
Definition at line 872 of file MSNet.cpp.
References MSStoppingPlace::getBeginLanePosition(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), and MSNet::myStoppingPlaces.
Referenced by MSNet::getShapeContainer(), and MSDevice_Battery::notifyMove().
getTLSControl()
MSTLLogicControl& MSNet::getTLSControl () inline inherited
Returns the tls logics control.
Returns
The tls logics control
See also
MSTLLogicControl
myLogics
Definition at line 379 of file MSNet.h.
References MSNet::myLogics.
Referenced by NLBuilder::build(), NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), libsumo::TrafficLight::getIDList(), NLJunctionControlBuilder::getTLLogicControlToUse(), libsumo::TrafficLight::getTLS(), initTLMap(), GUIViewTraffic::onGamingClick(), TraCIServerAPI_TrafficLight::processGet(), and MSFullExport::writeTLS().
getTLSIDs()
std::vector< GUIGlID > GUINet::getTLSIDs () const
Returns the gl-ids of all traffic light logics within the net.
Definition at line 244 of file GUINet.cpp.
References myLogics2Wrapper.
Referenced by getAvgWalkTimeLoss().
getTravelTime()
double MSNet::getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, double t) static inherited
Returns the travel time to pass an edge.
Parameters
[in] e The edge for which the travel time to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the travel time shall be returned [s]
Returns
The travel time for an edge
See also
DijkstraRouter_ByProxi
Definition at line 150 of file MSNet.cpp.
References MSNet::getInstance(), MSEdge::getMinimumTravelTime(), MSVehicle::getWeightsStorage(), MSNet::getWeightsStorage(), and MSEdgeWeightsStorage::retrieveExistingTravelTime().
Referenced by MSNet::getRouterEffort(), MSNet::getRouterTT(), MSEdge::getTravelTimeStatic(), MSDevice_Routing::initEdgeWeights(), MSDevice_Routing::reroute(), and MSNet::VehicleStateListener::~VehicleStateListener().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, GUIPerson, and GUIContainer.
Definition at line 126 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
getUPS()
double GUINet::getUPS () const
Returns the update per seconds rate.
Definition at line 349 of file GUINet.cpp.
References myLastSimDuration, and myLastVehicleMovementCount.
Referenced by getParameterWindow().
getVehicleControl()
MSVehicleControl& MSNet::getVehicleControl () inline inherited
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 306 of file MSNet.h.
References MSNet::getPersonControl(), and MSNet::myVehicleControl.
Referenced by MSNet::adaptIntermodalRouter(), libsumo::Person::add(), MSVehicleTransfer::add(), libsumo::Vehicle::add(), MSRouteHandler::addPersonTrip(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), libsumo::VehicleType::getIDList(), libsumo::Vehicle::getIDList(), MSLane::getMaximumBrakeDist(), libsumo::Simulation::getMinExpectedNumber(), getParameterWindow(), TraCIServerAPI_Vehicle::getPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), libsumo::Vehicle::getVehicle(), libsumo::VehicleType::getVType(), MSLane::handleCollisionBetween(), GUIApplicationWindow::handleEvent_SimulationStep(), libsumo::Vehicle::isOnInit(), libsumo::Vehicle::moveTo(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSDevice_Bluelight::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), MSRouteHandler::openVehicleTypeDistribution(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSDevice_SSM::processEncounters(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), MESegment::receive(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MSCalibrator::removePending(), MSBaseVehicle::replaceVehicleType(), MSTransportable::replaceVehicleType(), MSVehicle::resumeFromStopping(), MSStateHandler::saveState(), MSVehicleType::setActionStepLength(), setSimDuration(), libsumo::Person::setType(), libsumo::Vehicle::setType(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSNet::writeOutput(), MSFullExport::writeVehicles(), MSTransportable::~MSTransportable(), and MSVehicle::~MSVehicle().
getVehicleMeanSpeed()
double MSNet::getVehicleMeanSpeed () const inline protected inherited
Definition at line 615 of file MSNet.h.
References MSNet::getVehicleMeanSpeeds().
Referenced by getParameterWindow().
getVehicleMeanSpeedRelative()
double MSNet::getVehicleMeanSpeedRelative () const inline protected inherited
Definition at line 618 of file MSNet.h.
References MSNet::getVehicleMeanSpeeds().
Referenced by getParameterWindow().
getVehicleMeanSpeeds()
std::pair< double, double > MSNet::getVehicleMeanSpeeds () const protected inherited
get current absolute and relative mean vehicle speed in the network
Definition at line 1013 of file MSNet.cpp.
References SUMOVehicle::getEdge(), SUMOVehicle::getSpeed(), MSEdge::getSpeedLimit(), SUMOVehicle::isOnRoad(), SUMOVehicle::isRemoteControlled(), SUMOVehicle::isStopped(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), and MSNet::myVehicleControl.
Referenced by MSNet::getVehicleMeanSpeed(), MSNet::getVehicleMeanSpeedRelative(), MSNet::version(), and MSNet::writeOutput().
getVisualisationSpeedUp() [1/2]
SUMORTree& GUINet::getVisualisationSpeedUp () inline
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 288 of file GUINet.h.
References myGrid.
getVisualisationSpeedUp() [2/2]
const SUMORTree& GUINet::getVisualisationSpeedUp () const inline
Returns the RTree used for visualisation speed-up.
Returns
The visualisation speed-up
Definition at line 296 of file GUINet.h.
References createTLWrapper(), getGUIInstance(), getGUIMEVehicleControl(), getGUIVehicleControl(), initTLMap(), lock(), myGrid, and unlock().
getWeightsStorage()
MSEdgeWeightsStorage & MSNet::getWeightsStorage () inherited
Returns the net's internal edge travel times/efforts container.
If the net does not have such a container, it is built.
Returns
The net's knowledge about edge weights
Definition at line 785 of file MSNet.cpp.
References MSNet::myEdgeWeights.
Referenced by NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), libsumo::Edge::addEffort(), libsumo::Edge::addTravelTime(), GUILane::getColorValue(), MSNet::getEffort(), GUILane::getLoadedEdgeWeight(), GUILane::getScaleValue(), MSNet::getShapeContainer(), GUILane::getStoredEdgeTravelTime(), and MSNet::getTravelTime().
getWholeDuration()
int GUINet::getWholeDuration () const
Returns the duration of the last step (sim+visualisation+idle) (in ms)
Returns
How long it took to compute and display the last step
Definition at line 320 of file GUINet.cpp.
References myLastIdleDuration, and myLastSimDuration.
Referenced by getParameterWindow().
guiSimulationStep()
void GUINet::guiSimulationStep ()
Some further steps needed for gui processing.
Definition at line 218 of file GUINet.cpp.
References GLObjectValuePassConnector< T >::updateAll().
Referenced by GUIRunThread::makeStep().
hasContainers()
bool MSNet::hasContainers () const inline inherited
Returns whether containers are simulated.
Definition at line 339 of file MSNet.h.
References MSNet::myContainerControl.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), and MSVehicle::processNextStop().
hasElevation()
bool MSNet::hasElevation () const inline inherited
return whether the network contains elevation data
Definition at line 592 of file MSNet.h.
References MSNet::myHasElevation.
Referenced by MSVTypeProbe::execute().
hasInternalLinks()
bool MSNet::hasInternalLinks () const inline inherited
return whether the network contains internal links
Definition at line 587 of file MSNet.h.
References MSNet::myHasInternalLinks.
Referenced by MSNet::closeBuilding(), MSDevice_Tripinfo::computeLengthAndDuration(), MSTriggeredRerouter::rerouteParkingArea(), MSPModel_Striping::usingInternalLanes(), and MSDevice_Vehroutes::writeOutput().
hasPermissions()
bool MSNet::hasPermissions () const inline inherited
Returns whether the network has specific vehicle class permissions.
Returns
whether permissions are present
Definition at line 173 of file MSNet.h.
References MSNet::myHavePermissions.
Referenced by MSDevice_Routing::reroute().
hasPersons()
bool MSNet::hasPersons () const inline inherited
Returns whether persons are simulated.
Definition at line 323 of file MSNet.h.
References MSNet::getContainerControl(), and MSNet::myPersonControl.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), and MSVehicle::processNextStop().
informVehicleStateListener()
void MSNet::informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to) inherited
Informs all added listeners about a vehicle's state change.
Parameters
[in] vehicle The vehicle which changed its state
[in] to The state the vehicle has changed to
See also
VehicleStateListener:vehicleStateChanged
Definition at line 849 of file MSNet.cpp.
References MSNet::myVehicleStateListeners.
Referenced by MSVehicleTransfer::add(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleTransfer::checkInsertions(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicleControl::vehicleDeparted(), and MSNet::VehicleStateListener::~VehicleStateListener().
initGUIStructures()
void GUINet::initGUIStructures ()
Initialises gui wrappers.
Definition at line 259 of file GUINet.cpp.
References Boundary::add(), SUMORTree::addAdditionalGLObject(), MSEdge::getAllEdges(), MSDetectorControl::getAvailableTypes(), GUIJunctionWrapper::getBoundary(), Boundary::getHeight(), MSEdge::getLanes(), MSDetectorControl::getTypedDetectors(), Boundary::getWidth(), Boundary::grow(), initTLMap(), LayeredRTree::Insert(), myBoundary, MSNet::myDetectorControl, myDetectorWrapper, myEdgeWrapper, myGrid, MSNet::myJunctions, myJunctionWrapper, MSPModel::SIDEWALK_OFFSET, NamedObjectCont< T >::size(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by getAvgWalkTimeLoss(), and GUILoadThread::run().
initTLMap()
void GUINet::initTLMap () private
Initialises the tl-logic map and wrappers.
Definition at line 137 of file GUINet.cpp.
References createTLWrapper(), MSTLLogicControl::getAllLogics(), MSNet::getTLSControl(), and myTLLogicWrapper.
Referenced by getVisualisationSpeedUp(), and initGUIStructures().
lefthand()
bool MSNet::lefthand () const inline inherited
return whether the network was built for lefthand traffic
Definition at line 597 of file MSNet.h.
References MSNet::myLefthand.
Referenced by MSNet::closeBuilding(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawMarkings(), GUILane::drawTLSLinkNo(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), MSPModel_NonInteracting::PState::getPosition(), GUIBusStop::GUIBusStop(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), and MSParkingArea::MSParkingArea().
loadRoutes()
void MSNet::loadRoutes () inherited
loads routes for the next few steps
Definition at line 366 of file MSNet.cpp.
References SUMORouteLoaderControl::loadNext(), MSNet::myRouteLoaders, and MSNet::myStep.
Referenced by GUIRunThread::init(), NLBuilder::init(), MSNet::setPermissionsFound(), and MSNet::simulationStep().
lock()
void GUINet::lock ()
grant exclusive access to the simulation state
Definition at line 522 of file GUINet.cpp.
References MFXMutex::lock(), and myLock.
Referenced by GUIViewTraffic::doPaintGL(), and getVisualisationSpeedUp().
logSimulationDuration()
bool MSNet::logSimulationDuration () const inherited
Returns whether duration shall be logged.
Returns
Whether duration shall be logged
Definition at line 762 of file MSNet.cpp.
References MSNet::myLogExecutionTime.
Referenced by getParameterWindow(), and MSNet::setCurrentTimeStep().
postSimStepOutput()
void MSNet::postSimStepOutput () const inherited
Prints the statistics of the step at its end.
Called on the end of a simulation step
Definition at line 800 of file MSNet.cpp.
References DELTA_T, MSVehicleControl::getDepartedVehicleNo(), TraCIServer::getInstance(), MSVehicleControl::getRunningVehicleNo(), MSInsertionControl::getWaitingVehicleNo(), gPrecision, MSNet::myInserter, MSNet::myLogExecutionTime, MSNet::mySimStepDuration, MSNet::myStep, MSNet::myTraCIStepDuration, MSNet::myVehicleControl, time2string(), and TS.
Referenced by MSNet::setCurrentTimeStep(), and MSNet::simulate().
preSimStepOutput()
void MSNet::preSimStepOutput () const inherited
Prints the current step number.
Called on the begin of a simulation step
Definition at line 794 of file MSNet.cpp.
References MSNet::myStep, and time2string().
Referenced by MSNet::setCurrentTimeStep(), and MSNet::simulate().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
removeVehicleStateListener()
void MSNet::removeVehicleStateListener (VehicleStateListener * listener) inherited
Removes a vehicle states listener.
Parameters
[in] listener The listener to remove
Definition at line 840 of file MSNet.cpp.
References MSNet::myVehicleStateListeners.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
setCurrentTimeStep()
void MSNet::setCurrentTimeStep (const SUMOTime step) inline inherited
Sets the current simulation step (used by state loading)
Parameters
step the current simulation step
Definition at line 261 of file MSNet.h.
References MSNet::logSimulationDuration(), MSNet::myStep, MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), and MSNet::writeOutput().
Referenced by GUIRunThread::init().
setIdleDuration()
void GUINet::setIdleDuration (int val)
Sets the duration of the last step's idle part.
Definition at line 398 of file GUINet.cpp.
References myLastIdleDuration.
Referenced by GUIRunThread::run().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPermissionsFound()
void MSNet::setPermissionsFound () inline inherited
Labels the network to contain vehicle class permissions.
Definition at line 179 of file MSNet.h.
References MSNet::addRestriction(), MSNet::clearAll(), MSNet::closeSimulation(), MSNet::getRestrictions(), MSNet::getStateMessage(), MSNet::loadRoutes(), MSNet::myHavePermissions, MSNet::simulate(), MSNet::simulationState(), and MSNet::simulationStep().
Referenced by NLHandler::addLane().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setSimDuration()
void GUINet::setSimDuration (int val)
Sets the duration of the last step's simulation part.
Definition at line 382 of file GUINet.cpp.
References MSVehicleControl::getRunningVehicleNo(), MSNet::getVehicleControl(), myLastSimDuration, myLastVehicleMovementCount, myOverallSimDuration, and myOverallVehicleCount.
Referenced by GUIRunThread::run().
simulate()
MSNet::SimulationState MSNet::simulate (SUMOTime start, SUMOTime stop) inherited
Simulates from timestep start to stop.
Parameters
[in] start The begin time step of the simulation
[in] stop The end time step of the simulation
Returns
Returns always 0
Todo:
Recheck return value
What exceptions may occure?
Definition at line 313 of file MSNet.cpp.
References MSNet::closeSimulation(), MSNet::getCurrentTimeStep(), TraCIServer::getInstance(), TraCIServer::getLoadArgs(), OptionsCont::getOptions(), MSNet::getStateMessage(), MSNet::myLogStepNumber, MSNet::myStep, MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), OptionsIO::setArgs(), MSNet::SIMSTATE_LOADING, MSNet::SIMSTATE_RUNNING, SIMTIME, MSNet::simulationState(), MSNet::simulationStep(), time2string(), TraCIServer::wasClosed(), and WRITE_MESSAGE.
Referenced by main(), and MSNet::setPermissionsFound().
simulationState()
MSNet::SimulationState MSNet::simulationState (SUMOTime stopTime) const inherited
Called after a simulation step, this method returns the current simulation state.
Parameters
[in] stopTime The time the simulation shall stop at
Returns
The current simulation state
See also
SimulationState
Definition at line 560 of file MSNet.cpp.
References MSVehicleControl::abortWaiting(), MSTransportableControl::abortWaitingForVehicle(), MSVehicleControl::getActiveVehicleCount(), TraCIServer::getInstance(), MSInsertionControl::getPendingFlowCount(), MSVehicleControl::getTeleportCount(), MSTransportableControl::hasNonWaiting(), MSEventControl::isEmpty(), MSNet::myContainerControl, MSNet::myInserter, MSNet::myInsertionEvents, MSNet::myMaxTeleports, MSNet::myPersonControl, MSNet::myStep, MSNet::myVehicleControl, MSNet::SIMSTATE_CONNECTION_CLOSED, MSNet::SIMSTATE_END_STEP_REACHED, MSNet::SIMSTATE_LOADING, MSNet::SIMSTATE_NO_FURTHER_VEHICLES, MSNet::SIMSTATE_RUNNING, MSNet::SIMSTATE_TOO_MANY_TELEPORTS, and TraCIServer::wasClosed().
Referenced by GUIRunThread::makeStep(), MSNet::setPermissionsFound(), and MSNet::simulate().
simulationStep()
void GUINet::simulationStep ()
Performs a single simulation step (locking the simulation)
Definition at line 225 of file GUINet.cpp.
References myLock, and MSNet::simulationStep().
Referenced by GUIRunThread::makeStep().
unlock()
void GUINet::unlock ()
release exclusive access to the simulation state
Definition at line 528 of file GUINet.cpp.
References myLock, and MFXMutex::unlock().
Referenced by GUIViewTraffic::doPaintGL(), and getVisualisationSpeedUp().
vehicleExists()
bool GUINet::vehicleExists (const std::string & name) const
returns the information whether the vehicle still exists
Definition at line 184 of file GUINet.cpp.
References MSVehicleControl::getVehicle(), and MSNet::myVehicleControl.
version()
double MSNet::version () const inline inherited
return the network version
Definition at line 602 of file MSNet.h.
References MSNet::checkElevation(), MSNet::getHaltingVehicleNumber(), MSNet::getVehicleMeanSpeeds(), and MSNet::myVersion.
Referenced by MSNet::closeBuilding().
writeChargingStationOutput()
void MSNet::writeChargingStationOutput () const inherited
write charging station output
Definition at line 886 of file MSNet.cpp.
References OutputDevice::getDeviceByOption(), MSNet::myStoppingPlaces, and SUMO_TAG_CHARGING_STATION.
Referenced by MSNet::closeSimulation(), and MSNet::getShapeContainer().
writeOutput()
void MSNet::writeOutput () inherited
Write netstate, summary and detector output.
Todo:
Which exceptions may occur?
Definition at line 645 of file MSNet.cpp.
References OutputDevice::closeTag(), DELTA_T, MSVehicleControl::getDepartedVehicleNo(), OutputDevice::getDeviceByOption(), MSEdgeControl::getEdges(), MSVehicleControl::getEndedVehicleNo(), MSNet::getHaltingVehicleNumber(), MSNet::getInstance(), MSDevice_SSM::getInstances(), OptionsCont::getInt(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSVehicleControl::getRunningVehicleNo(), OptionsCont::getString(), MSVehicleControl::getTotalDepartureDelay(), MSVehicleControl::getTotalTravelTime(), MSNet::getVehicleControl(), MSNet::getVehicleMeanSpeeds(), MSInsertionControl::getWaitingVehicleNo(), OptionsCont::isSet(), MSNet::myDetectorControl, MSNet::myEdges, MSNet::myHasElevation, MSNet::myInserter, MSNet::myLogExecutionTime, MSNet::mySimStepDuration, MSNet::myStep, MSNet::myVehicleControl, OutputDevice::openTag(), STEPS2TIME, SUMO_ATTR_ID, time2string(), MSDevice_SSM::updateAndWriteOutput(), MSDetectorControl::updateDetectors(), MSVTKExport::write(), MSEmissionExport::write(), MSQueueExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSFullExport::write(), MSAmitranTrajectories::write(), MSXMLRawOut::write(), OutputDevice::writeAttr(), and MSDetectorControl::writeOutput().
Referenced by MSNet::setCurrentTimeStep(), and MSNet::simulationStep().
Friends And Related Function Documentation
GUIOSGBuilder
friend class GUIOSGBuilder friend
Definition at line 338 of file GUINet.h.
GUITrafficLightLogicWrapper
friend class GUITrafficLightLogicWrapper friend
Definition at line 90 of file GUINet.h.
Referenced by createTLWrapper().
Field Documentation
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
myBeginOfTimestepEvents
MSEventControl* MSNet::myBeginOfTimestepEvents protected inherited
Controls events executed at the begin of a time step;.
See also
MSEventControl
Definition at line 657 of file MSNet.h.
Referenced by MSNet::getBeginOfTimestepEvents(), MSNet::MSNet(), MSNet::simulationStep(), and MSNet::~MSNet().
myBoundary
Boundary GUINet::myBoundary protected
The networks boundary.
Definition at line 345 of file GUINet.h.
Referenced by getBoundary(), and initGUIStructures().
myContainerControl
MSTransportableControl* MSNet::myContainerControl protected inherited
Controls container building and deletion;.
See also
MSTransportableControl
Definition at line 645 of file MSNet.h.
Referenced by getContainerControl(), MSNet::getContainerControl(), MSNet::hasContainers(), MSNet::MSNet(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::~MSNet().
myDetectorControl
MSDetectorControl* MSNet::myDetectorControl protected inherited
Controls detectors;.
See also
MSDetectorControl
Definition at line 655 of file MSNet.h.
Referenced by MSNet::closeSimulation(), MSNet::getDetectorControl(), initGUIStructures(), MSNet::MSNet(), MSNet::writeOutput(), and MSNet::~MSNet().
myDetectorWrapper
std::vector<GUIDetectorWrapper*> GUINet::myDetectorWrapper protected
A detector dictionary.
Definition at line 357 of file GUINet.h.
Referenced by initGUIStructures(), and ~GUINet().
myEdges
MSEdgeControl* MSNet::myEdges protected inherited
Controls edges, performs vehicle movement;.
See also
MSEdgeControl
Definition at line 647 of file MSNet.h.
Referenced by MSNet::checkElevation(), MSNet::closeBuilding(), MSNet::getEdgeControl(), MSNet::MSNet(), MSNet::simulationStep(), MSNet::writeOutput(), and MSNet::~MSNet().
myEdgeWeights
MSEdgeWeightsStorage* MSNet::myEdgeWeights protected inherited
The net's knowledge about edge efforts/travel times;.
See also
MSEdgeWeightsStorage
Definition at line 665 of file MSNet.h.
Referenced by MSNet::getWeightsStorage(), MSNet::MSNet(), and MSNet::~MSNet().
myEdgeWrapper
std::vector<GUIEdge*> GUINet::myEdgeWrapper protected
Wrapped MS-edges.
Definition at line 348 of file GUINet.h.
Referenced by getGUIMEVehicleControl(), and initGUIStructures().
myEndOfTimestepEvents
MSEventControl* MSNet::myEndOfTimestepEvents protected inherited
Controls events executed at the end of a time step;.
See also
MSEventControl
Definition at line 659 of file MSNet.h.
Referenced by MSNet::getEndOfTimestepEvents(), MSNet::MSNet(), MSNet::simulationStep(), and MSNet::~MSNet().
myGrid
LayeredRTree GUINet::myGrid protected
The visualization speed-up.
Definition at line 342 of file GUINet.h.
Referenced by createTLWrapper(), getVisualisationSpeedUp(), and initGUIStructures().
myHasElevation
bool MSNet::myHasElevation protected inherited
Whether the network contains elevation data.
Definition at line 717 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::hasElevation(), and MSNet::writeOutput().
myHasInternalLinks
bool MSNet::myHasInternalLinks protected inherited
Whether the network contains internal links/lanes/edges.
Definition at line 714 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::hasInternalLinks().
myHavePermissions
bool MSNet::myHavePermissions protected inherited
Whether the network contains edges which not all vehicles may pass.
Definition at line 708 of file MSNet.h.
Referenced by MSNet::hasPermissions(), and MSNet::setPermissionsFound().
myInserter
MSInsertionControl* MSNet::myInserter protected inherited
Controls vehicle insertion;.
See also
MSInsertionControl
Definition at line 653 of file MSNet.h.
Referenced by MSNet::closeSimulation(), MSNet::getInsertionControl(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::simulationState(), MSNet::simulationStep(), MSNet::writeOutput(), and MSNet::~MSNet().
myInsertionEvents
MSEventControl* MSNet::myInsertionEvents protected inherited
Controls insertion events;.
See also
MSEventControl
Definition at line 661 of file MSNet.h.
Referenced by MSNet::getInsertionEvents(), MSNet::MSNet(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::~MSNet().
myInstance
MSNet * MSNet::myInstance = 0 static protected inherited
Unique instance of MSNet.
Definition at line 624 of file MSNet.h.
Referenced by MSNet::adaptIntermodalRouter(), MSNet::getInstance(), MSNet::MSNet(), and MSNet::~MSNet().
myIntermodalRouter
MSIntermodalRouter* MSNet::myIntermodalRouter mutable protected inherited
Definition at line 739 of file MSNet.h.
Referenced by MSNet::getIntermodalRouter().
myJunctions
MSJunctionControl* MSNet::myJunctions protected inherited
Controls junctions, realizes right-of-way rules;.
See also
MSJunctionControl
Definition at line 649 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::getJunctionControl(), getJunctionPosition(), initGUIStructures(), MSNet::MSNet(), and MSNet::~MSNet().
myJunctionWrapper
std::vector<GUIJunctionWrapper*> GUINet::myJunctionWrapper protected
Wrapped MS-junctions.
Definition at line 351 of file GUINet.h.
Referenced by getGUIMEVehicleControl(), getJunctionIDs(), initGUIStructures(), and ~GUINet().
myLanesRTree
std::pair<bool, NamedRTree> MSNet::myLanesRTree mutable protected inherited
An RTree structure holding lane IDs.
Definition at line 743 of file MSNet.h.
Referenced by MSNet::getLanesRTree(), MSNet::MSNet(), and MSNet::~MSNet().
myLastIdleDuration
int GUINet::myLastIdleDuration protected
Definition at line 373 of file GUINet.h.
Referenced by getIdleDuration(), getWholeDuration(), and setIdleDuration().
myLastSimDuration
int GUINet::myLastSimDuration protected
The step durations (simulation, /*visualisation, */idle)
Definition at line 373 of file GUINet.h.
Referenced by getRTFactor(), getSimDuration(), getUPS(), getWholeDuration(), and setSimDuration().
myLastVehicleMovementCount
long GUINet::myLastVehicleMovementCount protected
Definition at line 375 of file GUINet.h.
Referenced by getUPS(), and setSimDuration().
myLefthand
bool MSNet::myLefthand protected inherited
Whether the network was built for left-hand traffic.
Definition at line 720 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::lefthand().
myLinks2Logic
Links2LogicMap GUINet::myLinks2Logic protected
The link-to-logic-id map.
Definition at line 363 of file GUINet.h.
Referenced by createTLWrapper(), getLinkTLID(), and getLinkTLIndex().
myLock
MFXMutex GUINet::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 380 of file GUINet.h.
Referenced by lock(), simulationStep(), unlock(), and ~GUINet().
myLogExecutionTime
bool MSNet::myLogExecutionTime protected inherited
Information whether the simulation duration shall be logged.
Definition at line 674 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::closeSimulation(), MSNet::logSimulationDuration(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::simulationStep(), and MSNet::writeOutput().
myLogics
MSTLLogicControl* MSNet::myLogics protected inherited
Controls tls logics, realizes waiting on tls rules;.
See also
MSJunctionControl
Definition at line 651 of file MSNet.h.
Referenced by MSNet::closeBuilding(), createTLWrapper(), getLinkTLID(), getLinkTLIndex(), MSNet::getTLSControl(), MSNet::MSNet(), MSNet::simulationStep(), and MSNet::~MSNet().
myLogics2Wrapper
Logics2WrapperMap GUINet::myLogics2Wrapper protected
The traffic light-to-wrapper map.
Definition at line 369 of file GUINet.h.
Referenced by createTLWrapper(), getLinkTLID(), getLinkTLIndex(), getTLSIDs(), and ~GUINet().
myLogStepNumber
bool MSNet::myLogStepNumber protected inherited
Information whether the number of the simulation step shall be logged.
Definition at line 677 of file MSNet.h.
Referenced by MSNet::MSNet(), and MSNet::simulate().
myMaxTeleports
int MSNet::myMaxTeleports protected inherited
Maximum number of teleports.
Definition at line 633 of file MSNet.h.
Referenced by MSNet::MSNet(), and MSNet::simulationState().
myOverallSimDuration
long GUINet::myOverallSimDuration protected
Definition at line 376 of file GUINet.h.
Referenced by getMeanRTFactor(), getMeanUPS(), and setSimDuration().
myOverallVehicleCount
long GUINet::myOverallVehicleCount protected
Definition at line 375 of file GUINet.h.
Referenced by setSimDuration().
myPedestrianRouter
MSPedestrianRouterDijkstra* MSNet::myPedestrianRouter mutable protected inherited
Definition at line 738 of file MSNet.h.
Referenced by MSNet::getPedestrianRouter(), and MSNet::~MSNet().
myPersonControl
MSTransportableControl* MSNet::myPersonControl protected inherited
Controls person building and deletion;.
See also
MSTransportableControl
Definition at line 643 of file MSNet.h.
Referenced by MSNet::closeSimulation(), getParameterWindow(), getPersonControl(), MSNet::getPersonControl(), MSNet::hasPersons(), MSNet::MSNet(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::~MSNet().
myRestrictions
std::map<std::string, std::map<SUMOVehicleClass, double> > MSNet::myRestrictions protected inherited
The vehicle class specific speed restrictions.
Definition at line 711 of file MSNet.h.
Referenced by MSNet::addRestriction(), and MSNet::getRestrictions().
myRouteLoaders
SUMORouteLoaderControl* MSNet::myRouteLoaders protected inherited
Route loader for dynamic loading of routes.
Definition at line 627 of file MSNet.h.
Referenced by MSNet::closeBuilding(), MSNet::loadRoutes(), MSNet::MSNet(), and MSNet::~MSNet().
myRouterEffort
SUMOAbstractRouter<MSEdge, SUMOVehicle>* MSNet::myRouterEffort mutable protected inherited
Definition at line 737 of file MSNet.h.
Referenced by MSNet::getRouterEffort(), and MSNet::~MSNet().
myRouterTT
SUMOAbstractRouter<MSEdge, SUMOVehicle>* MSNet::myRouterTT mutable protected inherited
Definition at line 736 of file MSNet.h.
Referenced by MSNet::getRouterTT(), and MSNet::~MSNet().
myShapeContainer
ShapeContainer* MSNet::myShapeContainer protected inherited
A container for geometrical shapes;.
See also
ShapeContainer
Definition at line 663 of file MSNet.h.
Referenced by MSNet::getShapeContainer(), MSNet::MSNet(), and MSNet::~MSNet().
mySimBeginMillis
long MSNet::mySimBeginMillis protected inherited
The overall simulation duration.
Definition at line 683 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::closeSimulation().
mySimStepDuration
long MSNet::mySimStepDuration protected inherited
Definition at line 680 of file MSNet.h.
Referenced by MSNet::postSimStepOutput(), MSNet::simulationStep(), and MSNet::writeOutput().
myStateDumpFiles
std::vector<std::string> MSNet::myStateDumpFiles protected inherited
The names for the state files.
Definition at line 697 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
myStateDumpPeriod
SUMOTime MSNet::myStateDumpPeriod protected inherited
The period for writing state.
Definition at line 699 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
myStateDumpPrefix
std::string MSNet::myStateDumpPrefix protected inherited
name components for periodic state
Definition at line 701 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
myStateDumpSuffix
std::string MSNet::myStateDumpSuffix protected inherited
Definition at line 702 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
myStateDumpTimes
std::vector<SUMOTime> MSNet::myStateDumpTimes protected inherited
Times at which a state shall be written.
Definition at line 695 of file MSNet.h.
Referenced by MSNet::closeBuilding(), and MSNet::simulationStep().
myStep
SUMOTime MSNet::myStep protected inherited
Current time step.
Definition at line 630 of file MSNet.h.
Referenced by MSNet::closeSimulation(), MSNet::getCurrentTimeStep(), MSNet::loadRoutes(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), MSNet::setCurrentTimeStep(), MSNet::simulate(), MSNet::simulationState(), MSNet::simulationStep(), and MSNet::writeOutput().
myStoppingPlaces
std::map<SumoXMLTag, NamedObjectCont<MSStoppingPlace*> > MSNet::myStoppingPlaces protected inherited
Dictionary of bus / container stops.
Definition at line 726 of file MSNet.h.
Referenced by MSNet::adaptIntermodalRouter(), MSNet::addStoppingPlace(), MSNet::getStoppingPlace(), MSNet::getStoppingPlaceID(), and MSNet::writeChargingStationOutput().
myTLLogicWrapper
std::vector<MSTrafficLightLogic*> GUINet::myTLLogicWrapper protected
Wrapped TL-Logics.
Definition at line 354 of file GUINet.h.
Referenced by initTLMap().
myTraCIStepDuration
long MSNet::myTraCIStepDuration protected inherited
The last simulation step duration.
Definition at line 680 of file MSNet.h.
Referenced by MSNet::postSimStepOutput(), and MSNet::simulationStep().
myVehicleControl
MSVehicleControl* MSNet::myVehicleControl protected inherited
Controls vehicle building and deletion;.
See also
MSVehicleControl
Definition at line 641 of file MSNet.h.
Referenced by MSNet::closeSimulation(), getGUIMEVehicleControl(), getGUIVehicleControl(), MSNet::getHaltingVehicleNumber(), MSNet::getVehicleControl(), MSNet::getVehicleMeanSpeeds(), MSNet::MSNet(), MSNet::postSimStepOutput(), MSNet::simulationState(), MSNet::simulationStep(), vehicleExists(), MSNet::writeOutput(), and MSNet::~MSNet().
myVehiclesMoved
long long int MSNet::myVehiclesMoved protected inherited
The overall number of vehicle movements.
Definition at line 686 of file MSNet.h.
Referenced by MSNet::closeSimulation(), getMeanUPS(), and MSNet::simulationStep().
myVehicleStateListeners
std::vector<VehicleStateListener*> MSNet::myVehicleStateListeners protected inherited
Container for vehicle state listener.
Definition at line 729 of file MSNet.h.
Referenced by MSNet::addVehicleStateListener(), MSNet::informVehicleStateListener(), and MSNet::removeVehicleStateListener().
myVersion
double MSNet::myVersion protected inherited
the network version
Definition at line 723 of file MSNet.h.
Referenced by MSNet::closeBuilding(), getParameterWindow(), and MSNet::version().
STAGE_EVENTS
const std::string MSNet::STAGE_EVENTS static protected inherited
string constants for simstep stages
Definition at line 747 of file MSNet.h.
Referenced by MSNet::simulationStep().
STAGE_INSERTIONS
const std::string MSNet::STAGE_INSERTIONS static protected inherited
Definition at line 750 of file MSNet.h.
Referenced by MSNet::simulationStep().
STAGE_LANECHANGE
const std::string MSNet::STAGE_LANECHANGE static protected inherited
Definition at line 749 of file MSNet.h.
Referenced by MSNet::simulationStep().
STAGE_MOVEMENTS
const std::string MSNet::STAGE_MOVEMENTS static protected inherited
Definition at line 748 of file MSNet.h.
Referenced by MSNet::simulationStep().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUINet.h
GUINet.cpp