SUMO - Simulation of Urban MObility: MSEmissionExport Class Reference
MSEmissionExport Class Reference
Realises dumping Emission Data.
#include <MSEmissionExport.h>
Static Public Member Functions
static void write (OutputDevice &of, SUMOTime timestep, int precision)
Writes the complete network state of the given edges into the given device.
Private Member Functions
MSEmissionExport (const MSEmissionExport &)
Invalidated copy constructor.
MSEmissionExport & operator= (const MSEmissionExport &)
Invalidated assignment operator.
Detailed Description
Realises dumping Emission Data.
The class offers a static method, which writes all available emission factors of each vehicles of the network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 56 of file MSEmissionExport.h.
Constructor & Destructor Documentation
MSEmissionExport()
MSEmissionExport::MSEmissionExport (const MSEmissionExport &) private
Invalidated copy constructor.
Member Function Documentation
operator=()
MSEmissionExport& MSEmissionExport::operator= (const MSEmissionExport &) private
Invalidated assignment operator.
write()
void MSEmissionExport::write (OutputDevice & of, SUMOTime timestep, int precision) static
Writes the complete network state of the given edges into the given device.
Opens the current time step and export the emission factors of all availabel vehicles
Parameters
[in] of The output device to use
[in] timestep The current time step
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 47 of file MSEmissionExport.cpp.
References OutputDevice::closeTag(), PollutantsInterface::Emissions::CO, PollutantsInterface::Emissions::CO2, PollutantsInterface::computeAll(), HelpersHarmonoise::computeNoise(), PollutantsInterface::Emissions::electricity, PollutantsInterface::Emissions::fuel, SUMOVehicle::getAcceleration(), SUMOVehicle::getAngle(), MSVehicleType::getEmissionClass(), Named::getID(), SUMOVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicle::getLane(), PollutantsInterface::getName(), SUMOVehicle::getPosition(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getRoute(), SUMOVehicle::getSlope(), SUMOVehicle::getSpeed(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), gPrecision, PollutantsInterface::Emissions::HC, SUMOVehicle::isOnRoad(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), GeomHelper::naviDegree(), PollutantsInterface::Emissions::NOx, OutputDevice::openTag(), PollutantsInterface::Emissions::PMx, OutputDevice::setPrecision(), time2string(), OutputDevice::writeAttr(), Position::x(), and Position::y().
Referenced by MSNet::writeOutput().
The documentation for this class was generated from the following files:
MSEmissionExport.h
MSEmissionExport.cpp