SUMO - Simulation of Urban MObility: MSNet Class Reference
MSNet Class Reference
The simulated network and simulation perfomer.
#include <MSNet.h>
Data Structures
class VehicleStateListener
Interface for objects listening to vehicle state changes.
Public Types
typedef IntermodalRouter< MSEdge, MSLane, MSJunction, SUMOVehicle > MSIntermodalRouter
typedef PedestrianRouterDijkstra< MSEdge, MSLane, MSJunction, MSVehicle > MSPedestrianRouterDijkstra
enum SimulationState {
SIMSTATE_LOADING, SIMSTATE_RUNNING, SIMSTATE_END_STEP_REACHED, SIMSTATE_NO_FURTHER_VEHICLES,
SIMSTATE_CONNECTION_CLOSED, SIMSTATE_ERROR_IN_SIM, SIMSTATE_TOO_MANY_TELEPORTS
}
Possible states of a simulation - running or stopped with different reasons.
Public Member Functions
void addRestriction (const std::string &id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
void closeBuilding (const OptionsCont &oc, MSEdgeControl *edges, MSJunctionControl *junctions, SUMORouteLoaderControl *routeLoaders, MSTLLogicControl *tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles, bool hasInternalLinks, bool hasNeighs, bool lefthand, double version)
Closes the network's building process.
void closeSimulation (SUMOTime start)
Closes the simulation (all files, connections, etc.)
SUMOTime getCurrentTimeStep () const
Returns the current simulation step.
MSIntermodalRouter & getIntermodalRouter (const MSEdgeVector &prohibited=MSEdgeVector()) const
const NamedRTree & getLanesRTree () const
Returns an RTree that contains lane IDs.
MSPedestrianRouterDijkstra & getPedestrianRouter (const MSEdgeVector &prohibited=MSEdgeVector()) const
const std::map< SUMOVehicleClass, double > * getRestrictions (const std::string &id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterEffort (const MSEdgeVector &prohibited=MSEdgeVector()) const
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterTT (const MSEdgeVector &prohibited=MSEdgeVector()) const
bool hasElevation () const
return whether the network contains elevation data
bool hasInternalLinks () const
return whether the network contains internal links
bool hasPermissions () const
Returns whether the network has specific vehicle class permissions.
bool lefthand () const
return whether the network was built for lefthand traffic
void loadRoutes ()
loads routes for the next few steps
bool logSimulationDuration () const
Returns whether duration shall be logged.
MSNet (MSVehicleControl *vc, MSEventControl *beginOfTimestepEvents, MSEventControl *endOfTimestepEvents, MSEventControl *insertionEvents, ShapeContainer *shapeCont=0)
Constructor.
void setCurrentTimeStep (const SUMOTime step)
Sets the current simulation step (used by state loading)
void setPermissionsFound ()
Labels the network to contain vehicle class permissions.
SimulationState simulate (SUMOTime start, SUMOTime stop)
Simulates from timestep start to stop.
SimulationState simulationState (SUMOTime stopTime) const
Called after a simulation step, this method returns the current simulation state.
void simulationStep ()
Performs a single simulation step.
double version () const
return the network version
void writeChargingStationOutput () const
write charging station output
void writeOutput ()
Write netstate, summary and detector output.
virtual ~MSNet ()
Destructor.
Output during the simulation
void preSimStepOutput () const
Prints the current step number.
void postSimStepOutput () const
Prints the statistics of the step at its end.
Retrieval of references to substructures
MSVehicleControl & getVehicleControl ()
Returns the vehicle control.
virtual MSTransportableControl & getPersonControl ()
Returns the person control.
bool hasPersons () const
Returns whether persons are simulated.
virtual MSTransportableControl & getContainerControl ()
Returns the container control.
bool hasContainers () const
Returns whether containers are simulated.
MSEdgeControl & getEdgeControl ()
Returns the edge control.
MSInsertionControl & getInsertionControl ()
Returns the insertion control.
MSDetectorControl & getDetectorControl ()
Returns the detector control.
MSTLLogicControl & getTLSControl ()
Returns the tls logics control.
MSJunctionControl & getJunctionControl ()
Returns the junctions control.
MSEventControl * getBeginOfTimestepEvents ()
Returns the event control for events executed at the begin of a time step.
MSEventControl * getEndOfTimestepEvents ()
Returns the event control for events executed at the end of a time step.
MSEventControl * getInsertionEvents ()
Returns the event control for insertion events.
ShapeContainer & getShapeContainer ()
Returns the shapes container.
MSEdgeWeightsStorage & getWeightsStorage ()
Returns the net's internal edge travel times/efforts container.
Insertion and retrieval of stopping places
bool addStoppingPlace (const SumoXMLTag category, MSStoppingPlace *stop)
Adds a stopping place.
MSStoppingPlace * getStoppingPlace (const std::string &id, const SumoXMLTag category) const
Returns the named stopping place of the given category.
std::string getStoppingPlaceID (const MSLane *lane, const double pos, const SumoXMLTag category) const
Returns the stop of the given category close to the given position.
Static Public Member Functions
static void adaptIntermodalRouter (MSIntermodalRouter &router)
static void clearAll ()
Clears all dictionaries.
static double getEffort (const MSEdge *const e, const SUMOVehicle *const v, double t)
Returns the effort to pass an edge.
static MSNet * getInstance ()
Returns the pointer to the unique instance of MSNet (singleton).
static std::string getStateMessage (SimulationState state)
Returns the message to show if a certain state occurs.
static double getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, double t)
Returns the travel time to pass an edge.
Protected Member Functions
bool checkElevation ()
check all lanes for elevation data
int getHaltingVehicleNumber () const
count number of standing vehicles in the network
double getVehicleMeanSpeed () const
double getVehicleMeanSpeedRelative () const
std::pair< double, double > getVehicleMeanSpeeds () const
get current absolute and relative mean vehicle speed in the network
Protected Attributes
bool myHasElevation
Whether the network contains elevation data.
bool myHasInternalLinks
Whether the network contains internal links/lanes/edges.
bool myHavePermissions
Whether the network contains edges which not all vehicles may pass.
MSIntermodalRouter * myIntermodalRouter
std::pair< bool, NamedRTree > myLanesRTree
An RTree structure holding lane IDs.
bool myLefthand
Whether the network was built for left-hand traffic.
int myMaxTeleports
Maximum number of teleports.
MSPedestrianRouterDijkstra * myPedestrianRouter
std::map< std::string, std::map< SUMOVehicleClass, double > > myRestrictions
The vehicle class specific speed restrictions.
SUMORouteLoaderControl * myRouteLoaders
Route loader for dynamic loading of routes.
SUMOAbstractRouter< MSEdge, SUMOVehicle > * myRouterEffort
SUMOAbstractRouter< MSEdge, SUMOVehicle > * myRouterTT
SUMOTime myStep
Current time step.
std::map< SumoXMLTag, NamedObjectCont< MSStoppingPlace * > > myStoppingPlaces
Dictionary of bus / container stops.
std::vector< VehicleStateListener * > myVehicleStateListeners
Container for vehicle state listener.
double myVersion
the network version
Substructures
MSVehicleControl * myVehicleControl
Controls vehicle building and deletion;.
MSTransportableControl * myPersonControl
Controls person building and deletion;.
MSTransportableControl * myContainerControl
Controls container building and deletion;.
MSEdgeControl * myEdges
Controls edges, performs vehicle movement;.
MSJunctionControl * myJunctions
Controls junctions, realizes right-of-way rules;.
MSTLLogicControl * myLogics
Controls tls logics, realizes waiting on tls rules;.
MSInsertionControl * myInserter
Controls vehicle insertion;.
MSDetectorControl * myDetectorControl
Controls detectors;.
MSEventControl * myBeginOfTimestepEvents
Controls events executed at the begin of a time step;.
MSEventControl * myEndOfTimestepEvents
Controls events executed at the end of a time step;.
MSEventControl * myInsertionEvents
Controls insertion events;.
ShapeContainer * myShapeContainer
A container for geometrical shapes;.
MSEdgeWeightsStorage * myEdgeWeights
The net's knowledge about edge efforts/travel times;.
data needed for computing performance values
bool myLogExecutionTime
Information whether the simulation duration shall be logged.
bool myLogStepNumber
Information whether the number of the simulation step shall be logged.
long myTraCIStepDuration
The last simulation step duration.
long mySimStepDuration
long mySimBeginMillis
The overall simulation duration.
long long int myVehiclesMoved
The overall number of vehicle movements.
State output variables
std::vector< SUMOTime > myStateDumpTimes
Times at which a state shall be written.
std::vector< std::string > myStateDumpFiles
The names for the state files.
SUMOTime myStateDumpPeriod
The period for writing state.
std::string myStateDumpPrefix
name components for periodic state
std::string myStateDumpSuffix
Static Protected Attributes
static MSNet * myInstance = 0
Unique instance of MSNet.
static const std::string STAGE_EVENTS
string constants for simstep stages
static const std::string STAGE_INSERTIONS
static const std::string STAGE_LANECHANGE
static const std::string STAGE_MOVEMENTS
Private Member Functions
MSNet (const MSNet &)
Invalidated copy constructor.
MSNet & operator= (const MSNet &)
Invalidated assignment operator.
Notification about vehicle state changes
enum VehicleState {
VEHICLE_STATE_BUILT, VEHICLE_STATE_DEPARTED, VEHICLE_STATE_STARTING_TELEPORT, VEHICLE_STATE_ENDING_TELEPORT,
VEHICLE_STATE_ARRIVED, VEHICLE_STATE_NEWROUTE, VEHICLE_STATE_STARTING_PARKING, VEHICLE_STATE_ENDING_PARKING,
VEHICLE_STATE_STARTING_STOP, VEHICLE_STATE_ENDING_STOP
}
Definition of a vehicle state.
void addVehicleStateListener (VehicleStateListener *listener)
Adds a vehicle states listener.
void removeVehicleStateListener (VehicleStateListener *listener)
Removes a vehicle states listener.
void informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to)
Informs all added listeners about a vehicle's state change.
Detailed Description
The simulated network and simulation perfomer.
Definition at line 90 of file MSNet.h.
Member Typedef Documentation
MSIntermodalRouter
typedef IntermodalRouter<MSEdge, MSLane, MSJunction, SUMOVehicle> MSNet::MSIntermodalRouter
Definition at line 114 of file MSNet.h.
MSPedestrianRouterDijkstra
typedef PedestrianRouterDijkstra<MSEdge, MSLane, MSJunction, MSVehicle> MSNet::MSPedestrianRouterDijkstra
Definition at line 113 of file MSNet.h.
Member Enumeration Documentation
SimulationState
enum MSNet::SimulationState
Possible states of a simulation - running or stopped with different reasons.
Enumerator
SIMSTATE_LOADING
The simulation is loading.
SIMSTATE_RUNNING
The simulation is running.
SIMSTATE_END_STEP_REACHED
The final simulation step has been performed.
SIMSTATE_NO_FURTHER_VEHICLES
The simulation does not contain further vehicles.
SIMSTATE_CONNECTION_CLOSED
The connection to a client was closed by the client.
SIMSTATE_ERROR_IN_SIM
An error occured during the simulation step.
SIMSTATE_TOO_MANY_TELEPORTS
The simulation had too many teleports.
Definition at line 95 of file MSNet.h.
VehicleState
enum MSNet::VehicleState
Definition of a vehicle state.
Enumerator
VEHICLE_STATE_BUILT
The vehicle was built, but has not yet departed.
VEHICLE_STATE_DEPARTED
The vehicle has departed (was inserted into the network)
VEHICLE_STATE_STARTING_TELEPORT
The vehicle started to teleport.
VEHICLE_STATE_ENDING_TELEPORT
The vehicle ended being teleported.
VEHICLE_STATE_ARRIVED
The vehicle arrived at his destination (is deleted)
VEHICLE_STATE_NEWROUTE
The vehicle got a new route.
VEHICLE_STATE_STARTING_PARKING
The vehicles starts to park.
VEHICLE_STATE_ENDING_PARKING
The vehicle ends to park.
VEHICLE_STATE_STARTING_STOP
The vehicles starts to stop.
VEHICLE_STATE_ENDING_STOP
The vehicle ends to stop.
Definition at line 482 of file MSNet.h.
Constructor & Destructor Documentation
MSNet() [1/2]
MSNet::MSNet (MSVehicleControl * vc, MSEventControl * beginOfTimestepEvents, MSEventControl * endOfTimestepEvents, MSEventControl * insertionEvents, ShapeContainer * shapeCont = 0)
Constructor.
This constructor builds a net of which only some basic structures are initialised. It prepares the network for being filled while loading. As soon as all edge/junction/traffic lights and other containers are build, they must be initialised using "closeBuilding".
Parameters
[in] vc The vehicle control to use
[in] beginOfTimestepEvents The event control to use for simulation step begin events
[in] endOfTimestepEvents The event control to use for simulation step end events
[in] insertionEvents The event control to use for insertion events
[in] shapeCont The shape container to use
Exceptions
ProcessError If a network was already constructed
See also
closeBuilding
Definition at line 175 of file MSNet.cpp.
References OptionsCont::getBool(), OptionsCont::getInt(), OptionsCont::getOptions(), OptionsCont::getString(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, myBeginOfTimestepEvents, myContainerControl, myDetectorControl, myEdges, myEdgeWeights, myEndOfTimestepEvents, myInserter, myInsertionEvents, myInstance, myJunctions, myLanesRTree, myLogExecutionTime, myLogics, myLogStepNumber, myMaxTeleports, myPersonControl, myRouteLoaders, myShapeContainer, myStep, myVehicleControl, and string2time().
~MSNet()
MSNet::~MSNet () virtual
Destructor.
Definition at line 256 of file MSNet.cpp.
References clearAll(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, myBeginOfTimestepEvents, myContainerControl, myDetectorControl, myEdges, myEdgeWeights, myEndOfTimestepEvents, myInserter, myInsertionEvents, myInstance, myJunctions, myLanesRTree, myLogics, myPedestrianRouter, myPersonControl, myRouteLoaders, myRouterEffort, myRouterTT, myShapeContainer, and myVehicleControl.
MSNet() [2/2]
MSNet::MSNet (const MSNet &) private
Invalidated copy constructor.
Member Function Documentation
adaptIntermodalRouter()
void MSNet::adaptIntermodalRouter (MSIntermodalRouter & router) static
Definition at line 958 of file MSNet.cpp.
References MSInsertionControl::adaptIntermodalRouter(), MSVehicleControl::adaptIntermodalRouter(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::addAccess(), getInsertionControl(), getVehicleControl(), myInstance, myStoppingPlaces, SUMO_TAG_BUS_STOP, and SUMO_TAG_PARKING_AREA.
Referenced by getIntermodalRouter(), and MSNet::VehicleStateListener::~VehicleStateListener().
addRestriction()
void MSNet::addRestriction (const std::string & id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
Parameters
[in] id The id of the type
[in] svc The vehicle class the restriction refers to
[in] speed The restricted speed
Definition at line 297 of file MSNet.cpp.
References myRestrictions.
Referenced by NLHandler::myStartElement(), and setPermissionsFound().
addStoppingPlace()
bool MSNet::addStoppingPlace (const SumoXMLTag category, MSStoppingPlace * stop)
Adds a stopping place.
If another stop with the same id and category exists, false is returned. Otherwise, the stop is added to the internal stopping place container.
This control gets responsible for deletion of the added stop.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Definition at line 857 of file MSNet.cpp.
References Named::getID(), myStoppingPlaces, SUMO_TAG_BUS_STOP, and SUMO_TAG_TRAIN_STOP.
Referenced by GUITriggerBuilder::beginParkingArea(), NLTriggerBuilder::beginParkingArea(), GUITriggerBuilder::buildChargingStation(), NLTriggerBuilder::buildChargingStation(), GUITriggerBuilder::buildStoppingPlace(), NLTriggerBuilder::buildStoppingPlace(), and getShapeContainer().
addVehicleStateListener()
void MSNet::addVehicleStateListener (VehicleStateListener * listener)
Adds a vehicle states listener.
Parameters
[in] listener The listener to add
Definition at line 832 of file MSNet.cpp.
References myVehicleStateListeners.
Referenced by MSDevice_Vehroutes::init(), TraCIServer::openSocket(), and MSNet::VehicleStateListener::~VehicleStateListener().
checkElevation()
bool MSNet::checkElevation () protected
check all lanes for elevation data
Definition at line 986 of file MSNet.cpp.
References MSEdgeControl::getEdges(), and myEdges.
Referenced by closeBuilding(), and version().
clearAll()
void MSNet::clearAll () static
Clears all dictionaries.
Todo:
Try to move all this to the destructor
Definition at line 621 of file MSNet.cpp.
References MSTrigger::cleanup(), MSPModel::cleanup(), MSCModel_NonInteracting::cleanup(), MSDevice_BTsender::cleanup(), MSCalibrator::cleanup(), TraCIServer::cleanup(), libsumo::Helper::cleanup(), MSDevice_SSM::cleanup(), MSDevice::cleanupAll(), MSRoute::clear(), MSLane::clear(), MSEdge::clear(), TraCIServer::getInstance(), and MSVehicleTransfer::getInstance().
Referenced by GUILoadThread::run(), setPermissionsFound(), and ~MSNet().
closeBuilding()
void MSNet::closeBuilding (const OptionsCont & oc, MSEdgeControl * edges, MSJunctionControl * junctions, SUMORouteLoaderControl * routeLoaders, MSTLLogicControl * tlc, std::vector< SUMOTime > stateDumpTimes, std::vector< std::string > stateDumpFiles, bool hasInternalLinks, bool hasNeighs, bool lefthand, double version)
Closes the network's building process.
Assigns the structures built while loading to this network.
Parameters
[in] oc The options to use
[in] edges The control of edges which belong to this network
[in] junctions The control of junctions which belong to this network
[in] routeLoaders The route loaders used
[in] tlc The control of traffic lights which belong to this network
[in] stateDumpTimes List of time steps at which state shall be written
[in] stateDumpFiles Filenames for states
[in] hasInternalLinks Whether the network actually contains internal links
[in] lefthand Whether the network was built for left-hand traffic
[in] version The network version
Todo:
Try to move all this to the constructor?
Definition at line 219 of file MSNet.cpp.
References checkElevation(), SysUtils::getCurrentMillis(), OptionsCont::getString(), MSGlobals::gLateralResolution, hasInternalLinks(), lefthand(), myEdges, myHasElevation, myHasInternalLinks, myJunctions, myLefthand, myLogExecutionTime, myLogics, myRouteLoaders, mySimBeginMillis, myStateDumpFiles, myStateDumpPeriod, myStateDumpPrefix, myStateDumpSuffix, myStateDumpTimes, myVersion, MSJunctionControl::postloadInitContainer(), string2time(), version(), and WRITE_WARNING.
Referenced by NLBuilder::buildNet().
closeSimulation()
void MSNet::closeSimulation (SUMOTime start)
Closes the simulation (all files, connections, etc.)
Writes also performance output
Parameters
[in] start The step the simulation was started with
Todo:
What exceptions may occure?
Definition at line 372 of file MSNet.cpp.
References MSDetectorControl::close(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSDevice_Vehroutes::generateOutputForUnfinished(), MSVehicleControl::getCollisionCount(), SysUtils::getCurrentMillis(), MSVehicleControl::getDepartedVehicleNo(), MSVehicleControl::getEmergencyStops(), MSTransportableControl::getJammedNumber(), MSTransportableControl::getLoadedNumber(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSTransportableControl::getRunningNumber(), MSVehicleControl::getRunningVehicleNo(), MSVehicleControl::getTeleportCount(), MSVehicleControl::getTeleportsJam(), MSVehicleControl::getTeleportsWrongLane(), MSVehicleControl::getTeleportsYield(), MSInsertionControl::getWaitingVehicleNo(), joinToString(), myDetectorControl, myInserter, myLogExecutionTime, myPersonControl, mySimBeginMillis, myStep, myVehicleControl, myVehiclesMoved, MSDevice_Tripinfo::printStatistics(), STEPS2TIME, toString(), WRITE_MESSAGE, and writeChargingStationOutput().
Referenced by GUIRunThread::deleteSim(), setPermissionsFound(), and simulate().
getBeginOfTimestepEvents()
MSEventControl* MSNet::getBeginOfTimestepEvents () inline
Returns the event control for events executed at the begin of a time step.
Returns
The control responsible for events that are executed at the begin of a time step
See also
MSEventControl
myBeginOfTimestepEvents
Definition at line 399 of file MSNet.h.
References myBeginOfTimestepEvents.
Referenced by MSPModel_NonInteracting::add(), MSCModel_NonInteracting::add(), NLTriggerBuilder::buildVaporizer(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTLLogicControl::closeWAUT(), MSLaneSpeedTrigger::init(), MSPModel_Striping::MSPModel_Striping(), MSTrafficLightLogic::MSTrafficLightLogic(), MSTriggeredRerouter::myEndElement(), MSDevice_Routing::notifyEnter(), and MSTriggeredRerouter::setPermissions().
getContainerControl()
MSTransportableControl & MSNet::getContainerControl () virtual
Returns the container control.
If the container control does not exist, yet, it is created.
Returns
The container control
See also
MSContainerControl
myContainerControl
Reimplemented in GUINet.
Definition at line 776 of file MSNet.cpp.
References myContainerControl.
Referenced by MSTransportable::Stage_Waiting::abort(), MSRouteHandler::closeContainer(), hasPersons(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSDevice_Transportable::notifyLeave(), MSDevice_Transportable::notifyMove(), MSContainer::MSContainerStage_Driving::proceed(), MSTransportable::Stage_Waiting::proceed(), and MSVehicle::processNextStop().
getCurrentTimeStep()
SUMOTime MSNet::getCurrentTimeStep () const inline
Returns the current simulation step.
Returns
the current simulation step
Definition at line 253 of file MSNet.h.
References myStep.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), libsumo::Person::add(), libsumo::Vehicle::add(), GUIEdge::addRerouter(), MSDevice_Vehroutes::addRoute(), MSTLLogicControl::addWAUTJunction(), MSTransportableControl::boardAnyWaiting(), NLDetectorBuilder::buildE2Detector(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSTLLogicControl::closeWAUT(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), TraCIServer::dispatchCommand(), MSActuatedTrafficLightLogic::duration(), MSVehicle::enterLaneAtInsertion(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVehicle::executeMove(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), MSActuatedTrafficLightLogic::gapControl(), MSTransportable::getAngle(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentOccupancy(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), GUIApplicationWindow::getCurrentSimTime(), MSLaneSpeedTrigger::getCurrentSpeed(), libsumo::Simulation::getCurrentTime(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSTransportable::getEdgePos(), MSLane::getFirstVehicleInformation(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), libsumo::Lane::getLinks(), MESegment::getMeanSpeed(), MSInsertionControl::getPendingEmits(), MSTransportable::getPosition(), MSVehicle::getPosition(), MSTrafficLightLogic::getSpentDuration(), MSTransportable::getWaitingSeconds(), MSLink::getZipperSpeed(), GUIApplicationWindow::handleEvent_SimulationStep(), MSSwarmTrafficLightLogic::init(), MSLaneSpeedTrigger::init(), MSDevice_Routing::initEdgeWeights(), TraCIServer::initialiseSubscription(), MSTLLogicControl::initWautSwitch(), MSLane::isInsertionSuccess(), MSPerson::Influencer::isRemoteControlled(), MSVehicle::Influencer::isRemoteControlled(), MSTransportableControl::loadAnyWaiting(), GUIRunThread::makeStep(), MSPModel_Striping::MSPModel_Striping(), MSDevice_Vehroutes::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Transportable::notifyMove(), GUIApplicationWindow::onCmdTimeToggle(), MSBaseVehicle::onDepart(), TraCIServer::postProcessSimulationStep(), MESegment::prepareDetectorForWriting(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSTriggeredRerouter::rerouteParkingArea(), MSVehicle::resetActionOffset(), MSSOTLTrafficLightLogic::resetCTS(), MSTrafficLightLogic::resetLinkStates(), GUIRunThread::run(), TraCIServer::sendOutputToAll(), libsumo::TrafficLight::setPhase(), libsumo::TrafficLight::setPhaseDuration(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSPhasedTrafficLightLogic::setStep(), MSSOTLTrafficLightLogic::setupCTS(), simulate(), MSSimpleTrafficLightLogic::trySwitch(), MSDelayBasedTrafficLightLogic::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateActionOffset(), MSSOTLTrafficLightLogic::updateCTS(), MSRailCrossing::updateCurrentPhase(), MSSwarmTrafficLightLogic::updateSensitivities(), and MSVehicle::wasRemoteControlled().
getDetectorControl()
MSDetectorControl& MSNet::getDetectorControl () inline
Returns the detector control.
Returns
The detector control
See also
MSDetectorControl
myDetectorControl
Definition at line 369 of file MSNet.h.
References myDetectorControl.
Referenced by MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::buildRouteProbe(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NLDetectorBuilder::createEdgeLaneMeanData(), NLDetectorBuilder::endE3Detector(), libsumo::MultiEntryExit::getDetector(), libsumo::LaneArea::getDetector(), libsumo::InductionLoop::getDetector(), libsumo::LaneArea::getIDCount(), libsumo::MultiEntryExit::getIDCount(), libsumo::InductionLoop::getIDCount(), libsumo::MultiEntryExit::getIDList(), libsumo::LaneArea::getIDList(), libsumo::InductionLoop::getIDList(), TraCIServerAPI_InductionLoop::getPosition(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), and NLTriggerBuilder::parseAndBuildCalibrator().
getEdgeControl()
MSEdgeControl& MSNet::getEdgeControl () inline
Returns the edge control.
Returns
The edge control
See also
MSEdgeControl
myEdges
Definition at line 349 of file MSNet.h.
References myEdges.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), NLBuilder::build(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), libsumo::Helper::convertCartesianToRoadMap(), MSLane::incorporateVehicle(), MSMeanData::init(), MSFCDExport::write(), MSQueueExport::writeEdge(), and MSFullExport::writeEdge().
getEffort()
double MSNet::getEffort (const MSEdge *const e, const SUMOVehicle *const v, double t) static
Returns the effort to pass an edge.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the effort shall be returned [s]
Returns
The effort (abstract) for an edge
See also
DijkstraRouter_ByProxi
Definition at line 136 of file MSNet.cpp.
References getInstance(), MSVehicle::getWeightsStorage(), getWeightsStorage(), and MSEdgeWeightsStorage::retrieveExistingEffort().
Referenced by getRouterEffort(), and MSNet::VehicleStateListener::~VehicleStateListener().
getEndOfTimestepEvents()
MSEventControl* MSNet::getEndOfTimestepEvents () inline
Returns the event control for events executed at the end of a time step.
Returns
The control responsible for events that are executed at the end of a time step
See also
MSEventControl
myEndOfTimestepEvents
Definition at line 409 of file MSNet.h.
References myEndOfTimestepEvents.
Referenced by MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), MSDevice_Routing::buildVehicleDevices(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), MSCalibrator::init(), and MSVTypeProbe::MSVTypeProbe().
getHaltingVehicleNumber()
int MSNet::getHaltingVehicleNumber () const protected
count number of standing vehicles in the network
Definition at line 1000 of file MSNet.cpp.
References SUMOVehicle::getSpeed(), SUMOVehicle::isOnRoad(), SUMOVehicle::isRemoteControlled(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), myVehicleControl, and SUMO_const_haltingSpeed.
Referenced by GUINet::getParameterWindow(), version(), and writeOutput().
getInsertionControl()
MSInsertionControl& MSNet::getInsertionControl () inline
Returns the insertion control.
Returns
The insertion control
See also
MSInsertionControl
myInserter
Definition at line 359 of file MSNet.h.
References myInserter.
Referenced by adaptIntermodalRouter(), libsumo::Vehicle::add(), MSLane::checkFailure(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), GUIEdge::getColorValue(), GUILane::getColorValue(), libsumo::Simulation::getMinExpectedNumber(), GUINet::getParameterWindow(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GUIApplicationWindow::handleEvent_SimulationStep(), MSLane::isInsertionSuccess(), MSVehicleTransfer::loadState(), libsumo::Vehicle::moveTo(), libsumo::Vehicle::moveToXY(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), and MSBaseVehicle::reroute().
getInsertionEvents()
MSEventControl* MSNet::getInsertionEvents () inline
Returns the event control for insertion events.
Returns
The control responsible for insertion events
See also
MSEventControl
myInsertionEvents
Definition at line 419 of file MSNet.h.
References myInsertionEvents.
Referenced by MSDevice_Routing::MSDevice_Routing().
getInstance()
MSNet * MSNet::getInstance (void) static
Returns the pointer to the unique instance of MSNet (singleton).
Returns
Pointer to the unique MSNet-instance
Exceptions
ProcessError If a network was not yet constructed
Definition at line 167 of file MSNet.cpp.
References myInstance.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSTransportable::Stage_Waiting::abort(), MSTransportableControl::abortWaitingForVehicle(), MSDevice_Routing::adaptEdgeEfforts(), libsumo::Polygon::add(), LaneStoringVisitor::add(), libsumo::POI::add(), MSPModel_Striping::add(), libsumo::Person::add(), MSVehicleTransfer::add(), libsumo::Vehicle::add(), MSChargingStation::addChargeValueForOutput(), libsumo::Edge::addEffort(), MSTrafficLightLogic::addLink(), MSTLLogicControl::TLSLogicVariants::addLogic(), MSRouteHandler::addPersonTrip(), GUIEdge::addRerouter(), MSDevice_Vehroutes::addRoute(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), libsumo::Edge::addTravelTime(), MSTLLogicControl::addWAUTJunction(), libsumo::Person::appendDrivingStage(), libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportableControl::boardAnyWaiting(), MSDevice_BTreceiver::BTreceiverUpdate::BTreceiverUpdate(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NLTriggerBuilder::buildVaporizer(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSDevice_Routing::buildVehicleDevices(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), libsumo::Vehicle::changeLane(), MELoop::changeSegment(), MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), libsumo::Vehicle::changeTarget(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSTLLogicControl::closeWAUT(), Command_SaveTLSState::Command_SaveTLSState(), Command_SaveTLSSwitches::Command_SaveTLSSwitches(), Command_SaveTLSSwitchStates::Command_SaveTLSSwitchStates(), TraCIServerAPI_Simulation::commandDistanceRequest(), MSDevice_Tripinfo::computeLengthAndDuration(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), libsumo::Helper::convertCartesianToRoadMap(), NLDetectorBuilder::createEdgeLaneMeanData(), MSCalibrator::currentFlow(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSInsertionControl::determineCandidates(), TraCIServer::dispatchCommand(), GUITrafficLightLogicWrapper::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawMarkings(), GUILane::drawTLSLinkNo(), MSVehicleType::duplicateType(), MSActuatedTrafficLightLogic::duration(), GUITriggerBuilder::endParkingArea(), MSVehicle::enterLaneAtInsertion(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLCoupledLaneDet::execute(), Command_SaveTLCoupledDet::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), MSActuatedTrafficLightLogic::gapControl(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), MSTransportable::getAngle(), MSVehicle::getBackPositionOnLane(), GUIEdge::getColorValue(), GUILane::getColorValue(), MSLane::getCriticalLeader(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), MSLaneSpeedTrigger::getCurrentSpeed(), MSInductLoop::getCurrentSpeed(), libsumo::Simulation::getCurrentTime(), GUIViewTraffic::getCurrentTimeStep(), MSEventControl::getCurrentTimeStep(), MSInductLoop::getCurrentVehicleIDs(), libsumo::MultiEntryExit::getDetector(), libsumo::LaneArea::getDetector(), libsumo::InductionLoop::getDetector(), MSTransportable::getEdgePos(), getEffort(), MSLane::getFirstVehicleInformation(), GUINet::getGUIInstance(), libsumo::LaneArea::getIDCount(), libsumo::MultiEntryExit::getIDCount(), libsumo::InductionLoop::getIDCount(), libsumo::Person::getIDCount(), libsumo::VehicleType::getIDList(), libsumo::Polygon::getIDList(), libsumo::LaneArea::getIDList(), libsumo::MultiEntryExit::getIDList(), libsumo::TrafficLight::getIDList(), libsumo::InductionLoop::getIDList(), libsumo::Person::getIDList(), libsumo::POI::getIDList(), libsumo::Junction::getIDList(), libsumo::Vehicle::getIDList(), libsumo::Junction::getJunction(), MSLane::getLastVehicleInformation(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), libsumo::Lane::getLinks(), GUILane::getLoadedEdgeWeight(), MSLane::getMaximumBrakeDist(), MESegment::getMeanSpeed(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), libsumo::Simulation::getMinExpectedNumber(), MSPModel::getModel(), MSCModel_NonInteracting::getModel(), MSPModel_Striping::getNextLane(), libsumo::Simulation::getParameter(), MSInsertionControl::getPendingEmits(), libsumo::Person::getPerson(), libsumo::Edge::getPersonIDs(), MSTLLogicControl::getPhaseDef(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_Vehicle::getPosition(), TraCIServerAPI_Person::getPosition(), MSPModel_NonInteracting::PState::getPosition(), MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSTransportable::getPosition(), MSVehicle::getPosition(), MSVTKExport::getPositions(), MSVehicle::Influencer::getRouterTT(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), MSBaseVehicle::getSingularType(), MSVTKExport::getSpeed(), MSTrafficLightLogic::getSpentDuration(), GUILane::getStoredEdgeTravelTime(), MSEdge::getSuccessors(), libsumo::TrafficLight::getTLS(), getTravelTime(), MSEdge::getTravelTimeStatic(), libsumo::InductionLoop::getTree(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), libsumo::POI::getTree(), libsumo::Vehicle::getVehicle(), libsumo::InductionLoop::getVehicleData(), libsumo::VehicleType::getVType(), MSTransportable::getWaitingSeconds(), MSLink::getZipperSpeed(), GUIBusStop::GUIBusStop(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), MSLane::handleCollisionBetween(), MSPModel_Striping::PState::ignoreRed(), MSVehicle::ignoreRed(), MSLane::incorporateVehicle(), MSVehicle::influenceChangeDecision(), MSRailCrossing::init(), MSDevice_Vehroutes::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSLaneSpeedTrigger::init(), MSCalibrator::init(), MSMeanData::init(), MSDevice_Routing::initEdgeWeights(), TraCIServer::initialiseSubscription(), MSLane::initRestrictions(), MSTLLogicControl::initWautSwitch(), MSEdge::insertVehicle(), MSLane::isInsertionSuccess(), libsumo::Vehicle::isOnInit(), MSPerson::Influencer::isRemoteControlled(), MSVehicle::Influencer::isRemoteControlled(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::leaveLane(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSTransportableControl::loadAnyWaiting(), MSVehicleTransfer::loadState(), libsumo::Vehicle::moveTo(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), MSDevice_Routing::MSDevice_Routing(), MSParkingArea::MSParkingArea(), MSTrafficLightLogic::MSTrafficLightLogic(), MSVTypeProbe::MSVTypeProbe(), GUITriggeredRerouter::myEndElement(), MSRouteHandler::myEndElement(), MSTriggeredRerouter::myEndElement(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSTriggeredRerouter::myStartElement(), MSDevice_Transportable::notifyEnter(), MSDevice_Vehroutes::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), MSDevice_Routing::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Transportable::notifyMove(), MSDevice_Battery::notifyMove(), MSDevice_Bluelight::notifyMove(), MSE3Collector::MSE3EntryReminder::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), GUIViewTraffic::onGamingClick(), TraCIServer::openSocket(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseWalkPositions(), MSVehicle::planMoveInternal(), libsumo::Helper::postProcessRemoteControl(), MSPerson::Influencer::postProcessRemoteControl(), TraCIServer::postProcessSimulationStep(), MESegment::prepareDetectorForWriting(), MSPerson::MSPersonStage_Walking::proceed(), TraCIServer::processCommandsUntilSimStep(), MSDevice_SSM::processEncounters(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_Simulation::processGet(), MSVehicle::processLaneAdvances(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_Person::processSet(), MSVehicle::processTraCISpeedControl(), MSPModel_Striping::PState::PState(), MESegment::receive(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), libsumo::Polygon::remove(), libsumo::POI::remove(), MSCalibrator::removePending(), MSTransportable::removeStage(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceVehicleType(), MSTransportable::replaceVehicleType(), MSDevice_Routing::reroute(), MSBaseVehicle::reroute(), libsumo::Vehicle::rerouteEffort(), MSTriggeredRerouter::rerouteParkingArea(), libsumo::Person::rerouteTraveltime(), libsumo::Vehicle::rerouteTraveltime(), MSVehicle::resetActionOffset(), MSSOTLTrafficLightLogic::resetCTS(), MSTrafficLightLogic::resetLinkStates(), MSVehicle::resumeFromStopping(), libsumo::Edge::retrieveExistingEffort(), libsumo::Edge::retrieveExistingTravelTime(), MSContainer::routeOutput(), MSPerson::routeOutput(), MSStateHandler::saveState(), MSVehicleControl::scheduleVehicleRemoval(), TraCIServer::sendOutputToAll(), MSVehicleType::setActionStepLength(), libsumo::TrafficLight::setCompleteRedYellowGreenDefinition(), GUIBaseVehicle::setFunctionalColor(), MSLaneSpeedTrigger::setOverriding(), MSLaneSpeedTrigger::setOverridingValue(), MSTriggeredRerouter::setPermissions(), libsumo::TrafficLight::setPhase(), libsumo::TrafficLight::setPhaseDuration(), libsumo::TrafficLight::setProgram(), libsumo::TrafficLight::setRedYellowGreenState(), libsumo::Polygon::setShape(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSPhasedTrafficLightLogic::setStep(), libsumo::Person::setType(), libsumo::Vehicle::setType(), MSSOTLTrafficLightLogic::setupCTS(), libsumo::Simulation::simulationStep(), libsumo::Vehicle::slowDown(), MSStopOut::stopEnded(), MSStopOut::stopStarted(), MSLane::succLinkSec(), MSTLLogicControl::TLSLogicVariants::switchTo(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSInsertionControl::tryInsert(), MSSimpleTrafficLightLogic::trySwitch(), MSDelayBasedTrafficLightLogic::trySwitch(), MSRailCrossing::trySwitch(), MSActuatedTrafficLightLogic::trySwitch(), MSRailSignal::trySwitch(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateActionOffset(), MSSOTLTrafficLightLogic::updateCTS(), MSRailCrossing::updateCurrentPhase(), MSSOTLTrafficLightLogic::updateDecayThreshold(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateShadowLane(), MSPModel_Striping::usingInternalLanes(), MSVehicleControl::vehicleDeparted(), MSPModel_Striping::PState::walk(), MSVehicle::wasRemoteControlled(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), MSDevice_Vehroutes::writeOutput(), writeOutput(), MSFullExport::writeTLS(), MSFullExport::writeVehicles(), MSDevice_BTreceiver::BTreceiverUpdate::~BTreceiverUpdate(), MSDevice_Routing::~MSDevice_Routing(), MSTransportable::~MSTransportable(), and MSVehicle::~MSVehicle().
getIntermodalRouter()
MSNet::MSIntermodalRouter & MSNet::getIntermodalRouter (const MSEdgeVector & prohibited = MSEdgeVector()) const
Definition at line 938 of file MSNet.cpp.
References adaptIntermodalRouter(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::ALL_JUNCTIONS, OptionsCont::getOptions(), myIntermodalRouter, IntermodalRouter< E, L, N, V, INTERNALROUTER >::PARKING_AREAS, IntermodalRouter< E, L, N, V, INTERNALROUTER >::prohibit(), and IntermodalRouter< E, L, N, V, INTERNALROUTER >::PT_STOPS.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
getJunctionControl()
MSJunctionControl& MSNet::getJunctionControl () inline
Returns the junctions control.
Returns
The junctions control
See also
MSJunctionControl
myJunctions
Definition at line 389 of file MSNet.h.
References myJunctions.
Referenced by libsumo::Junction::getIDList(), and libsumo::Junction::getJunction().
getLanesRTree()
const NamedRTree & MSNet::getLanesRTree () const
Returns an RTree that contains lane IDs.
Returns
An Rtree containing lane IDs
Definition at line 976 of file MSNet.cpp.
References MSLane::fill(), and myLanesRTree.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
getPedestrianRouter()
MSNet::MSPedestrianRouterDijkstra & MSNet::getPedestrianRouter (const MSEdgeVector & prohibited = MSEdgeVector()) const
Definition at line 928 of file MSNet.cpp.
References myPedestrianRouter, and PedestrianRouter< E, L, N, V, INTERNALROUTER >::prohibit().
Referenced by MSRouteHandler::addPersonTrip(), libsumo::Simulation::findIntermodalRoute(), MSPModel_Striping::getNextLane(), MSPModel_Striping::PState::PState(), libsumo::Person::rerouteTraveltime(), and MSNet::VehicleStateListener::~VehicleStateListener().
getPersonControl()
MSTransportableControl & MSNet::getPersonControl () virtual
Returns the person control.
If the person control does not exist, yet, it is created.
Returns
The person control
See also
MSPersonControl
myPersonControl
Reimplemented in GUINet.
Definition at line 768 of file MSNet.cpp.
References myPersonControl.
Referenced by MSTransportable::Stage_Waiting::abort(), libsumo::Person::add(), MSRouteHandler::closePerson(), libsumo::Person::getIDCount(), libsumo::Person::getIDList(), libsumo::Person::getPerson(), TraCIServerAPI_Person::getPosition(), getVehicleControl(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSDevice_Transportable::notifyLeave(), MSDevice_Transportable::notifyMove(), GUISUMOViewParent::onCmdLocate(), TraCIServer::postProcessSimulationStep(), MSPerson::MSPersonStage_Walking::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSTransportable::Stage_Waiting::proceed(), MSVehicle::processNextStop(), TraCIServerAPI_Person::processSet(), MSPModel_Striping::PState::walk(), and MSFCDExport::write().
getRestrictions()
const std::map< SUMOVehicleClass, double > * MSNet::getRestrictions (const std::string & id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
Parameters
[in] id The id of the type
Returns
The mapping of vehicle classes to maximum speeds
Definition at line 303 of file MSNet.cpp.
References myRestrictions.
Referenced by MSLane::initRestrictions(), and setPermissionsFound().
getRouterEffort()
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterEffort (const MSEdgeVector & prohibited = MSEdgeVector()) const
Definition at line 917 of file MSNet.cpp.
References MSEdge::getAllEdges(), getEffort(), getTravelTime(), and myRouterEffort.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
getRouterTT()
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSNet::getRouterTT (const MSEdgeVector & prohibited = MSEdgeVector()) const
Definition at line 897 of file MSNet.cpp.
References MSEdge::getAllEdges(), OptionsCont::getOptions(), OptionsCont::getString(), getTravelTime(), myRouterTT, and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), TraCIServerAPI_Simulation::commandDistanceRequest(), libsumo::Simulation::findRoute(), MSVehicle::Influencer::getRouterTT(), MSTriggeredRerouter::notifyEnter(), MSTriggeredRerouter::rerouteParkingArea(), and MSNet::VehicleStateListener::~VehicleStateListener().
getShapeContainer()
ShapeContainer& MSNet::getShapeContainer () inline
Returns the shapes container.
Returns
The shapes container
See also
ShapeContainer
myShapeContainer
Definition at line 429 of file MSNet.h.
References addStoppingPlace(), getStoppingPlace(), getStoppingPlaceID(), getWeightsStorage(), myShapeContainer, and writeChargingStationOutput().
Referenced by libsumo::Polygon::add(), libsumo::POI::add(), NLHandler::addDistrict(), NLBuilder::build(), libsumo::Polygon::getIDList(), libsumo::POI::getIDList(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), libsumo::Polygon::getTree(), libsumo::POI::getTree(), GUISUMOViewParent::onCmdLocate(), GUIApplicationWindow::onCmdOpenShapes(), libsumo::Polygon::remove(), libsumo::POI::remove(), and libsumo::Polygon::setShape().
getStateMessage()
std::string MSNet::getStateMessage (MSNet::SimulationState state) static
Returns the message to show if a certain state occurs.
Returns
Readable description of the state
Definition at line 598 of file MSNet.cpp.
References SIMSTATE_CONNECTION_CLOSED, SIMSTATE_END_STEP_REACHED, SIMSTATE_ERROR_IN_SIM, SIMSTATE_LOADING, SIMSTATE_NO_FURTHER_VEHICLES, SIMSTATE_RUNNING, and SIMSTATE_TOO_MANY_TELEPORTS.
Referenced by GUIApplicationWindow::handleEvent_SimulationEnded(), GUIRunThread::makeStep(), setPermissionsFound(), and simulate().
getStoppingPlace()
MSStoppingPlace * MSNet::getStoppingPlace (const std::string & id, const SumoXMLTag category) const
Returns the named stopping place of the given category.
Parameters
[in] id The id of the stop to return.
[in] category The type of stop
Returns
The named stop, or 0 if no such stop exists
Definition at line 863 of file MSNet.cpp.
References myStoppingPlaces.
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicle::addTraciStopAtStoppingPlace(), libsumo::Person::appendDrivingStage(), libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), libsumo::Simulation::getParameter(), getShapeContainer(), MSRouteHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSDevice_Battery::notifyMove(), MSRouteHandler::parseWalkPositions(), and TraCIServerAPI_Simulation::processGet().
getStoppingPlaceID()
std::string MSNet::getStoppingPlaceID (const MSLane * lane, const double pos, const SumoXMLTag category) const
Returns the stop of the given category close to the given position.
Parameters
[in] lane the lane of the stop to return.
[in] pos the position of the stop to return.
[in] category The type of stop
Returns
The stop id on the location, or "" if no such stop exists
Definition at line 872 of file MSNet.cpp.
References MSStoppingPlace::getBeginLanePosition(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), and myStoppingPlaces.
Referenced by getShapeContainer(), and MSDevice_Battery::notifyMove().
getTLSControl()
MSTLLogicControl& MSNet::getTLSControl () inline
Returns the tls logics control.
Returns
The tls logics control
See also
MSTLLogicControl
myLogics
Definition at line 379 of file MSNet.h.
References myLogics.
Referenced by NLBuilder::build(), NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), libsumo::TrafficLight::getIDList(), NLJunctionControlBuilder::getTLLogicControlToUse(), libsumo::TrafficLight::getTLS(), GUINet::initTLMap(), GUIViewTraffic::onGamingClick(), TraCIServerAPI_TrafficLight::processGet(), and MSFullExport::writeTLS().
getTravelTime()
double MSNet::getTravelTime (const MSEdge *const e, const SUMOVehicle *const v, double t) static
Returns the travel time to pass an edge.
Parameters
[in] e The edge for which the travel time to be passed shall be returned
[in] v The vehicle that is rerouted
[in] t The time for which the travel time shall be returned [s]
Returns
The travel time for an edge
See also
DijkstraRouter_ByProxi
Definition at line 150 of file MSNet.cpp.
References getInstance(), MSEdge::getMinimumTravelTime(), MSVehicle::getWeightsStorage(), getWeightsStorage(), and MSEdgeWeightsStorage::retrieveExistingTravelTime().
Referenced by getRouterEffort(), getRouterTT(), MSEdge::getTravelTimeStatic(), MSDevice_Routing::initEdgeWeights(), MSDevice_Routing::reroute(), and MSNet::VehicleStateListener::~VehicleStateListener().
getVehicleControl()
MSVehicleControl& MSNet::getVehicleControl () inline
Returns the vehicle control.
Returns
The vehicle control
See also
MSVehicleControl
myVehicleControl
Definition at line 306 of file MSNet.h.
References getPersonControl(), and myVehicleControl.
Referenced by adaptIntermodalRouter(), libsumo::Person::add(), MSVehicleTransfer::add(), libsumo::Vehicle::add(), MSRouteHandler::addPersonTrip(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), libsumo::VehicleType::getIDList(), libsumo::Vehicle::getIDList(), MSLane::getMaximumBrakeDist(), libsumo::Simulation::getMinExpectedNumber(), GUINet::getParameterWindow(), TraCIServerAPI_Vehicle::getPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), libsumo::Vehicle::getVehicle(), libsumo::VehicleType::getVType(), MSLane::handleCollisionBetween(), GUIApplicationWindow::handleEvent_SimulationStep(), libsumo::Vehicle::isOnInit(), libsumo::Vehicle::moveTo(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSDevice_Bluelight::notifyMove(), GUISUMOViewParent::onCmdLocate(), MSBaseVehicle::onDepart(), MSRouteHandler::openVehicleTypeDistribution(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSDevice_SSM::processEncounters(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), MESegment::receive(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MSCalibrator::removePending(), MSBaseVehicle::replaceVehicleType(), MSTransportable::replaceVehicleType(), MSVehicle::resumeFromStopping(), MSStateHandler::saveState(), MSVehicleType::setActionStepLength(), GUINet::setSimDuration(), libsumo::Person::setType(), libsumo::Vehicle::setType(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), writeOutput(), MSFullExport::writeVehicles(), MSTransportable::~MSTransportable(), and MSVehicle::~MSVehicle().
getVehicleMeanSpeed()
double MSNet::getVehicleMeanSpeed () const inline protected
Definition at line 615 of file MSNet.h.
References getVehicleMeanSpeeds().
Referenced by GUINet::getParameterWindow().
getVehicleMeanSpeedRelative()
double MSNet::getVehicleMeanSpeedRelative () const inline protected
Definition at line 618 of file MSNet.h.
References getVehicleMeanSpeeds().
Referenced by GUINet::getParameterWindow().
getVehicleMeanSpeeds()
std::pair< double, double > MSNet::getVehicleMeanSpeeds () const protected
get current absolute and relative mean vehicle speed in the network
Definition at line 1013 of file MSNet.cpp.
References SUMOVehicle::getEdge(), SUMOVehicle::getSpeed(), MSEdge::getSpeedLimit(), SUMOVehicle::isOnRoad(), SUMOVehicle::isRemoteControlled(), SUMOVehicle::isStopped(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), and myVehicleControl.
Referenced by getVehicleMeanSpeed(), getVehicleMeanSpeedRelative(), version(), and writeOutput().
getWeightsStorage()
MSEdgeWeightsStorage & MSNet::getWeightsStorage ()
Returns the net's internal edge travel times/efforts container.
If the net does not have such a container, it is built.
Returns
The net's knowledge about edge weights
Definition at line 785 of file MSNet.cpp.
References myEdgeWeights.
Referenced by NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), libsumo::Edge::addEffort(), libsumo::Edge::addTravelTime(), GUILane::getColorValue(), getEffort(), GUILane::getLoadedEdgeWeight(), GUILane::getScaleValue(), getShapeContainer(), GUILane::getStoredEdgeTravelTime(), and getTravelTime().
hasContainers()
bool MSNet::hasContainers () const inline
Returns whether containers are simulated.
Definition at line 339 of file MSNet.h.
References myContainerControl.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), and MSVehicle::processNextStop().
hasElevation()
bool MSNet::hasElevation () const inline
return whether the network contains elevation data
Definition at line 592 of file MSNet.h.
References myHasElevation.
Referenced by MSVTypeProbe::execute().
hasInternalLinks()
bool MSNet::hasInternalLinks () const inline
return whether the network contains internal links
Definition at line 587 of file MSNet.h.
References myHasInternalLinks.
Referenced by closeBuilding(), MSDevice_Tripinfo::computeLengthAndDuration(), MSTriggeredRerouter::rerouteParkingArea(), MSPModel_Striping::usingInternalLanes(), and MSDevice_Vehroutes::writeOutput().
hasPermissions()
bool MSNet::hasPermissions () const inline
Returns whether the network has specific vehicle class permissions.
Returns
whether permissions are present
Definition at line 173 of file MSNet.h.
References myHavePermissions.
Referenced by MSDevice_Routing::reroute().
hasPersons()
bool MSNet::hasPersons () const inline
Returns whether persons are simulated.
Definition at line 323 of file MSNet.h.
References getContainerControl(), and myPersonControl.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), and MSVehicle::processNextStop().
informVehicleStateListener()
void MSNet::informVehicleStateListener (const SUMOVehicle *const vehicle, VehicleState to)
Informs all added listeners about a vehicle's state change.
Parameters
[in] vehicle The vehicle which changed its state
[in] to The state the vehicle has changed to
See also
VehicleStateListener:vehicleStateChanged
Definition at line 849 of file MSNet.cpp.
References myVehicleStateListeners.
Referenced by MSVehicleTransfer::add(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleTransfer::checkInsertions(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicleControl::vehicleDeparted(), and MSNet::VehicleStateListener::~VehicleStateListener().
lefthand()
bool MSNet::lefthand () const inline
return whether the network was built for lefthand traffic
Definition at line 597 of file MSNet.h.
References myLefthand.
Referenced by closeBuilding(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawMarkings(), GUILane::drawTLSLinkNo(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), MSPModel_NonInteracting::PState::getPosition(), GUIBusStop::GUIBusStop(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), and MSParkingArea::MSParkingArea().
loadRoutes()
void MSNet::loadRoutes ()
loads routes for the next few steps
Definition at line 366 of file MSNet.cpp.
References SUMORouteLoaderControl::loadNext(), myRouteLoaders, and myStep.
Referenced by GUIRunThread::init(), NLBuilder::init(), setPermissionsFound(), and simulationStep().
logSimulationDuration()
bool MSNet::logSimulationDuration () const
Returns whether duration shall be logged.
Returns
Whether duration shall be logged
Definition at line 762 of file MSNet.cpp.
References myLogExecutionTime.
Referenced by GUINet::getParameterWindow(), and setCurrentTimeStep().
operator=()
MSNet& MSNet::operator= (const MSNet &) private
Invalidated assignment operator.
postSimStepOutput()
void MSNet::postSimStepOutput () const
Prints the statistics of the step at its end.
Called on the end of a simulation step
Definition at line 800 of file MSNet.cpp.
References DELTA_T, MSVehicleControl::getDepartedVehicleNo(), TraCIServer::getInstance(), MSVehicleControl::getRunningVehicleNo(), MSInsertionControl::getWaitingVehicleNo(), gPrecision, myInserter, myLogExecutionTime, mySimStepDuration, myStep, myTraCIStepDuration, myVehicleControl, time2string(), and TS.
Referenced by setCurrentTimeStep(), and simulate().
preSimStepOutput()
void MSNet::preSimStepOutput () const
Prints the current step number.
Called on the begin of a simulation step
Definition at line 794 of file MSNet.cpp.
References myStep, and time2string().
Referenced by setCurrentTimeStep(), and simulate().
removeVehicleStateListener()
void MSNet::removeVehicleStateListener (VehicleStateListener * listener)
Removes a vehicle states listener.
Parameters
[in] listener The listener to remove
Definition at line 840 of file MSNet.cpp.
References myVehicleStateListeners.
Referenced by MSNet::VehicleStateListener::~VehicleStateListener().
setCurrentTimeStep()
void MSNet::setCurrentTimeStep (const SUMOTime step) inline
Sets the current simulation step (used by state loading)
Parameters
step the current simulation step
Definition at line 261 of file MSNet.h.
References logSimulationDuration(), myStep, postSimStepOutput(), preSimStepOutput(), and writeOutput().
Referenced by GUIRunThread::init().
setPermissionsFound()
void MSNet::setPermissionsFound () inline
Labels the network to contain vehicle class permissions.
Definition at line 179 of file MSNet.h.
References addRestriction(), clearAll(), closeSimulation(), getRestrictions(), getStateMessage(), loadRoutes(), myHavePermissions, simulate(), simulationState(), and simulationStep().
Referenced by NLHandler::addLane().
simulate()
MSNet::SimulationState MSNet::simulate (SUMOTime start, SUMOTime stop)
Simulates from timestep start to stop.
Parameters
[in] start The begin time step of the simulation
[in] stop The end time step of the simulation
Returns
Returns always 0
Todo:
Recheck return value
What exceptions may occure?
Definition at line 313 of file MSNet.cpp.
References closeSimulation(), getCurrentTimeStep(), TraCIServer::getInstance(), TraCIServer::getLoadArgs(), OptionsCont::getOptions(), getStateMessage(), myLogStepNumber, myStep, postSimStepOutput(), preSimStepOutput(), OptionsIO::setArgs(), SIMSTATE_LOADING, SIMSTATE_RUNNING, SIMTIME, simulationState(), simulationStep(), time2string(), TraCIServer::wasClosed(), and WRITE_MESSAGE.
Referenced by main(), and setPermissionsFound().
simulationState()
MSNet::SimulationState MSNet::simulationState (SUMOTime stopTime) const
Called after a simulation step, this method returns the current simulation state.
Parameters
[in] stopTime The time the simulation shall stop at
Returns
The current simulation state
See also
SimulationState
Definition at line 560 of file MSNet.cpp.
References MSVehicleControl::abortWaiting(), MSTransportableControl::abortWaitingForVehicle(), MSVehicleControl::getActiveVehicleCount(), TraCIServer::getInstance(), MSInsertionControl::getPendingFlowCount(), MSVehicleControl::getTeleportCount(), MSTransportableControl::hasNonWaiting(), MSEventControl::isEmpty(), myContainerControl, myInserter, myInsertionEvents, myMaxTeleports, myPersonControl, myStep, myVehicleControl, SIMSTATE_CONNECTION_CLOSED, SIMSTATE_END_STEP_REACHED, SIMSTATE_LOADING, SIMSTATE_NO_FURTHER_VEHICLES, SIMSTATE_RUNNING, SIMSTATE_TOO_MANY_TELEPORTS, and TraCIServer::wasClosed().
Referenced by GUIRunThread::makeStep(), setPermissionsFound(), and simulate().
simulationStep()
void MSNet::simulationStep ()
Performs a single simulation step.
Todo:
Which exceptions may occur?
Definition at line 439 of file MSNet.cpp.
References MSEdgeControl::changeLanes(), MSTLLogicControl::check2Switch(), MSVehicleTransfer::checkInsertions(), MSTransportableControl::checkWaiting(), DELTA_T, MSEdgeControl::detectCollisions(), MSInsertionControl::determineCandidates(), MSInsertionControl::emitVehicles(), MSEventControl::execute(), MSEdgeControl::executeMovements(), MSGlobals::gCheck4Accidents, SysUtils::getCurrentMillis(), TraCIServer::getInstance(), MSVehicleTransfer::getInstance(), MSVehicleControl::getRunningVehicleNo(), TraCIServer::getTargetTime(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, MSTransportableControl::hasTransportables(), TraCIServer::isEmbedded(), loadRoutes(), myBeginOfTimestepEvents, myContainerControl, myEdges, myEndOfTimestepEvents, myInserter, myInsertionEvents, myLogExecutionTime, myLogics, myPersonControl, mySimStepDuration, myStateDumpFiles, myStateDumpPeriod, myStateDumpPrefix, myStateDumpSuffix, myStateDumpTimes, myStep, myTraCIStepDuration, myVehicleControl, myVehiclesMoved, MSEdgeControl::patchActiveLanes(), MSEdgeControl::planMovements(), libsumo::Helper::postProcessRemoteControl(), TraCIServer::processCommandsUntilSimStep(), MSStateHandler::saveState(), SIMTIME, MELoop::simulate(), STAGE_EVENTS, STAGE_INSERTIONS, STAGE_LANECHANGE, STAGE_MOVEMENTS, time2string(), TraCIServer::wasClosed(), and writeOutput().
Referenced by TraCIServer::dispatchCommand(), setPermissionsFound(), simulate(), libsumo::Simulation::simulationStep(), and GUINet::simulationStep().
version()
double MSNet::version () const inline
return the network version
Definition at line 602 of file MSNet.h.
References checkElevation(), getHaltingVehicleNumber(), getVehicleMeanSpeeds(), and myVersion.
Referenced by closeBuilding().
writeChargingStationOutput()
void MSNet::writeChargingStationOutput () const
write charging station output
Definition at line 886 of file MSNet.cpp.
References OutputDevice::getDeviceByOption(), myStoppingPlaces, and SUMO_TAG_CHARGING_STATION.
Referenced by closeSimulation(), and getShapeContainer().
writeOutput()
void MSNet::writeOutput ()
Write netstate, summary and detector output.
Todo:
Which exceptions may occur?
Definition at line 645 of file MSNet.cpp.
References OutputDevice::closeTag(), DELTA_T, MSVehicleControl::getDepartedVehicleNo(), OutputDevice::getDeviceByOption(), MSEdgeControl::getEdges(), MSVehicleControl::getEndedVehicleNo(), getHaltingVehicleNumber(), getInstance(), MSDevice_SSM::getInstances(), OptionsCont::getInt(), MSVehicleControl::getLoadedVehicleNo(), OptionsCont::getOptions(), MSVehicleControl::getRunningVehicleNo(), OptionsCont::getString(), MSVehicleControl::getTotalDepartureDelay(), MSVehicleControl::getTotalTravelTime(), getVehicleControl(), getVehicleMeanSpeeds(), MSInsertionControl::getWaitingVehicleNo(), OptionsCont::isSet(), myDetectorControl, myEdges, myHasElevation, myInserter, myLogExecutionTime, mySimStepDuration, myStep, myVehicleControl, OutputDevice::openTag(), STEPS2TIME, SUMO_ATTR_ID, time2string(), MSDevice_SSM::updateAndWriteOutput(), MSDetectorControl::updateDetectors(), MSVTKExport::write(), MSQueueExport::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFullExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), MSXMLRawOut::write(), OutputDevice::writeAttr(), and MSDetectorControl::writeOutput().
Referenced by setCurrentTimeStep(), and simulationStep().
Field Documentation
myBeginOfTimestepEvents
MSEventControl* MSNet::myBeginOfTimestepEvents protected
Controls events executed at the begin of a time step;.
See also
MSEventControl
Definition at line 657 of file MSNet.h.
Referenced by getBeginOfTimestepEvents(), MSNet(), simulationStep(), and ~MSNet().
myContainerControl
MSTransportableControl* MSNet::myContainerControl protected
Controls container building and deletion;.
See also
MSTransportableControl
Definition at line 645 of file MSNet.h.
Referenced by GUINet::getContainerControl(), getContainerControl(), hasContainers(), MSNet(), simulationState(), simulationStep(), and ~MSNet().
myDetectorControl
MSDetectorControl* MSNet::myDetectorControl protected
Controls detectors;.
See also
MSDetectorControl
Definition at line 655 of file MSNet.h.
Referenced by closeSimulation(), getDetectorControl(), GUINet::initGUIStructures(), MSNet(), writeOutput(), and ~MSNet().
myEdges
MSEdgeControl* MSNet::myEdges protected
Controls edges, performs vehicle movement;.
See also
MSEdgeControl
Definition at line 647 of file MSNet.h.
Referenced by checkElevation(), closeBuilding(), getEdgeControl(), MSNet(), simulationStep(), writeOutput(), and ~MSNet().
myEdgeWeights
MSEdgeWeightsStorage* MSNet::myEdgeWeights protected
The net's knowledge about edge efforts/travel times;.
See also
MSEdgeWeightsStorage
Definition at line 665 of file MSNet.h.
Referenced by getWeightsStorage(), MSNet(), and ~MSNet().
myEndOfTimestepEvents
MSEventControl* MSNet::myEndOfTimestepEvents protected
Controls events executed at the end of a time step;.
See also
MSEventControl
Definition at line 659 of file MSNet.h.
Referenced by getEndOfTimestepEvents(), MSNet(), simulationStep(), and ~MSNet().
myHasElevation
bool MSNet::myHasElevation protected
Whether the network contains elevation data.
Definition at line 717 of file MSNet.h.
Referenced by closeBuilding(), hasElevation(), and writeOutput().
myHasInternalLinks
bool MSNet::myHasInternalLinks protected
Whether the network contains internal links/lanes/edges.
Definition at line 714 of file MSNet.h.
Referenced by closeBuilding(), and hasInternalLinks().
myHavePermissions
bool MSNet::myHavePermissions protected
Whether the network contains edges which not all vehicles may pass.
Definition at line 708 of file MSNet.h.
Referenced by hasPermissions(), and setPermissionsFound().
myInserter
MSInsertionControl* MSNet::myInserter protected
Controls vehicle insertion;.
See also
MSInsertionControl
Definition at line 653 of file MSNet.h.
Referenced by closeSimulation(), getInsertionControl(), MSNet(), postSimStepOutput(), simulationState(), simulationStep(), writeOutput(), and ~MSNet().
myInsertionEvents
MSEventControl* MSNet::myInsertionEvents protected
Controls insertion events;.
See also
MSEventControl
Definition at line 661 of file MSNet.h.
Referenced by getInsertionEvents(), MSNet(), simulationState(), simulationStep(), and ~MSNet().
myInstance
MSNet * MSNet::myInstance = 0 static protected
Unique instance of MSNet.
Definition at line 624 of file MSNet.h.
Referenced by adaptIntermodalRouter(), getInstance(), MSNet(), and ~MSNet().
myIntermodalRouter
MSIntermodalRouter* MSNet::myIntermodalRouter mutable protected
Definition at line 739 of file MSNet.h.
Referenced by getIntermodalRouter().
myJunctions
MSJunctionControl* MSNet::myJunctions protected
Controls junctions, realizes right-of-way rules;.
See also
MSJunctionControl
Definition at line 649 of file MSNet.h.
Referenced by closeBuilding(), getJunctionControl(), GUINet::getJunctionPosition(), GUINet::initGUIStructures(), MSNet(), and ~MSNet().
myLanesRTree
std::pair<bool, NamedRTree> MSNet::myLanesRTree mutable protected
An RTree structure holding lane IDs.
Definition at line 743 of file MSNet.h.
Referenced by getLanesRTree(), MSNet(), and ~MSNet().
myLefthand
bool MSNet::myLefthand protected
Whether the network was built for left-hand traffic.
Definition at line 720 of file MSNet.h.
Referenced by closeBuilding(), and lefthand().
myLogExecutionTime
bool MSNet::myLogExecutionTime protected
Information whether the simulation duration shall be logged.
Definition at line 674 of file MSNet.h.
Referenced by closeBuilding(), closeSimulation(), logSimulationDuration(), MSNet(), postSimStepOutput(), simulationStep(), and writeOutput().
myLogics
MSTLLogicControl* MSNet::myLogics protected
Controls tls logics, realizes waiting on tls rules;.
See also
MSJunctionControl
Definition at line 651 of file MSNet.h.
Referenced by closeBuilding(), GUINet::createTLWrapper(), GUINet::getLinkTLID(), GUINet::getLinkTLIndex(), getTLSControl(), MSNet(), simulationStep(), and ~MSNet().
myLogStepNumber
bool MSNet::myLogStepNumber protected
Information whether the number of the simulation step shall be logged.
Definition at line 677 of file MSNet.h.
Referenced by MSNet(), and simulate().
myMaxTeleports
int MSNet::myMaxTeleports protected
Maximum number of teleports.
Definition at line 633 of file MSNet.h.
Referenced by MSNet(), and simulationState().
myPedestrianRouter
MSPedestrianRouterDijkstra* MSNet::myPedestrianRouter mutable protected
Definition at line 738 of file MSNet.h.
Referenced by getPedestrianRouter(), and ~MSNet().
myPersonControl
MSTransportableControl* MSNet::myPersonControl protected
Controls person building and deletion;.
See also
MSTransportableControl
Definition at line 643 of file MSNet.h.
Referenced by closeSimulation(), GUINet::getParameterWindow(), GUINet::getPersonControl(), getPersonControl(), hasPersons(), MSNet(), simulationState(), simulationStep(), and ~MSNet().
myRestrictions
std::map<std::string, std::map<SUMOVehicleClass, double> > MSNet::myRestrictions protected
The vehicle class specific speed restrictions.
Definition at line 711 of file MSNet.h.
Referenced by addRestriction(), and getRestrictions().
myRouteLoaders
SUMORouteLoaderControl* MSNet::myRouteLoaders protected
Route loader for dynamic loading of routes.
Definition at line 627 of file MSNet.h.
Referenced by closeBuilding(), loadRoutes(), MSNet(), and ~MSNet().
myRouterEffort
SUMOAbstractRouter<MSEdge, SUMOVehicle>* MSNet::myRouterEffort mutable protected
Definition at line 737 of file MSNet.h.
Referenced by getRouterEffort(), and ~MSNet().
myRouterTT
SUMOAbstractRouter<MSEdge, SUMOVehicle>* MSNet::myRouterTT mutable protected
Definition at line 736 of file MSNet.h.
Referenced by getRouterTT(), and ~MSNet().
myShapeContainer
ShapeContainer* MSNet::myShapeContainer protected
A container for geometrical shapes;.
See also
ShapeContainer
Definition at line 663 of file MSNet.h.
Referenced by getShapeContainer(), MSNet(), and ~MSNet().
mySimBeginMillis
long MSNet::mySimBeginMillis protected
The overall simulation duration.
Definition at line 683 of file MSNet.h.
Referenced by closeBuilding(), and closeSimulation().
mySimStepDuration
long MSNet::mySimStepDuration protected
Definition at line 680 of file MSNet.h.
Referenced by postSimStepOutput(), simulationStep(), and writeOutput().
myStateDumpFiles
std::vector<std::string> MSNet::myStateDumpFiles protected
The names for the state files.
Definition at line 697 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
myStateDumpPeriod
SUMOTime MSNet::myStateDumpPeriod protected
The period for writing state.
Definition at line 699 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
myStateDumpPrefix
std::string MSNet::myStateDumpPrefix protected
name components for periodic state
Definition at line 701 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
myStateDumpSuffix
std::string MSNet::myStateDumpSuffix protected
Definition at line 702 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
myStateDumpTimes
std::vector<SUMOTime> MSNet::myStateDumpTimes protected
Times at which a state shall be written.
Definition at line 695 of file MSNet.h.
Referenced by closeBuilding(), and simulationStep().
myStep
SUMOTime MSNet::myStep protected
Current time step.
Definition at line 630 of file MSNet.h.
Referenced by closeSimulation(), getCurrentTimeStep(), loadRoutes(), MSNet(), postSimStepOutput(), preSimStepOutput(), setCurrentTimeStep(), simulate(), simulationState(), simulationStep(), and writeOutput().
myStoppingPlaces
std::map<SumoXMLTag, NamedObjectCont<MSStoppingPlace*> > MSNet::myStoppingPlaces protected
Dictionary of bus / container stops.
Definition at line 726 of file MSNet.h.
Referenced by adaptIntermodalRouter(), addStoppingPlace(), getStoppingPlace(), getStoppingPlaceID(), and writeChargingStationOutput().
myTraCIStepDuration
long MSNet::myTraCIStepDuration protected
The last simulation step duration.
Definition at line 680 of file MSNet.h.
Referenced by postSimStepOutput(), and simulationStep().
myVehicleControl
MSVehicleControl* MSNet::myVehicleControl protected
Controls vehicle building and deletion;.
See also
MSVehicleControl
Definition at line 641 of file MSNet.h.
Referenced by closeSimulation(), GUINet::getGUIMEVehicleControl(), GUINet::getGUIVehicleControl(), getHaltingVehicleNumber(), getVehicleControl(), getVehicleMeanSpeeds(), MSNet(), postSimStepOutput(), simulationState(), simulationStep(), GUINet::vehicleExists(), writeOutput(), and ~MSNet().
myVehiclesMoved
long long int MSNet::myVehiclesMoved protected
The overall number of vehicle movements.
Definition at line 686 of file MSNet.h.
Referenced by closeSimulation(), GUINet::getMeanUPS(), and simulationStep().
myVehicleStateListeners
std::vector<VehicleStateListener*> MSNet::myVehicleStateListeners protected
Container for vehicle state listener.
Definition at line 729 of file MSNet.h.
Referenced by addVehicleStateListener(), informVehicleStateListener(), and removeVehicleStateListener().
myVersion
double MSNet::myVersion protected
the network version
Definition at line 723 of file MSNet.h.
Referenced by closeBuilding(), GUINet::getParameterWindow(), and version().
STAGE_EVENTS
const std::string MSNet::STAGE_EVENTS static protected
string constants for simstep stages
Definition at line 747 of file MSNet.h.
Referenced by simulationStep().
STAGE_INSERTIONS
const std::string MSNet::STAGE_INSERTIONS static protected
Definition at line 750 of file MSNet.h.
Referenced by simulationStep().
STAGE_LANECHANGE
const std::string MSNet::STAGE_LANECHANGE static protected
Definition at line 749 of file MSNet.h.
Referenced by simulationStep().
STAGE_MOVEMENTS
const std::string MSNet::STAGE_MOVEMENTS static protected
Definition at line 748 of file MSNet.h.
Referenced by simulationStep().
The documentation for this class was generated from the following files:
MSNet.h
MSNet.cpp