SUMO - Simulation of Urban MObility: GNEAdditionalHandler Class Reference
GNEAdditionalHandler Class Reference
Builds trigger objects for GNENet (busStops, chargingStations, detectors, etc..)
#include <GNEAdditionalHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
GNEAdditionalHandler (const std::string &file, GNEViewNet *viewNet, bool undoAdditionals=true)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~GNEAdditionalHandler ()
Destructor.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
parsing methods
These methods parse the attributes for each of the described trigger and call the according methods to build the trigger
void parseAndBuildVaporizer (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Builds a vaporization.
void parseAndBuildVariableSpeedSign (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Variable Speed Signal (lane speed trigger)
void parseAndBuildVariableSpeedSignStep (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Variable Speed Signal Step.
void parseAndBuildRerouter (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a rerouter.
void parseAndBuildRerouterInterval (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Rerouter Interval.
void parseAndBuildRerouterClosingLaneReroute (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Closing Lane reroute.
void parseAndBuildRerouterClosingReroute (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Closing Reroute.
void parseAndBuildRerouterDestProbReroute (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Destiny Prob Reroute.
void parseAndBuildRerouterRouteProbReroute (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Route Prob Reroute.
void parseAndBuildBusStop (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a bus stop.
void parseAndBuildContainerStop (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a container stop.
void parseAndBuildChargingStation (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a charging station.
void parseAndBuildCalibrator (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a mesoscopic or microscopic calibrator.
void parseAndBuildDetectorE1 (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a induction loop detector (E1)
void parseAndBuildDetectorE2 (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a lane area detector (E2)
void parseAndBuildDetectorE3 (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a multi entry exit detector (E3)
void parseAndBuildDetectorEntry (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Entry detector.
void parseAndBuildDetectorExit (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds a Exit detector.
void parseAndBuildRouteProbe (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses his values and builds routeProbe.
void parseAndBuildCalibratorRoute (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses route values of Calibrators.
void parseAndBuildCalibratorVehicleType (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses vehicle type values of Calibrators.
void parseAndBuildCalibratorFlow (const SUMOSAXAttributes &attrs, const SumoXMLTag &tag)
Parses flow values of Calibrators.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
building methods
Called with parsed values, these methods build the trigger.
GNEViewNet * myViewNet
pointer to View's Net
bool myUndoAdditionals
flag to check if created additionals must be undo and redo
std::string myLastInsertedAdditionalParent
ID of last inserted Additional parent (needed for additionasl that own a child)
std::string getFileName (const SUMOSAXAttributes &attrs, const std::string &base, const bool allowEmpty=false)
Helper method to obtain the filename.
double getPosition (double pos, GNELane &lane, bool friendlyPos, const std::string &additionalID)
extracts the position, checks whether it shall be mirrored and checks whether it is within the lane.
static bool buildAdditional (GNEViewNet *viewNet, bool allowUndoRedo, SumoXMLTag tag, std::map< SumoXMLAttr, std::string > values)
Build additionals.
static bool buildBusStop (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNELane *lane, double startPos, double endPos, const std::string &name, const std::vector< std::string > &lines, bool friendlyPosition)
Builds a bus stop.
static bool buildContainerStop (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNELane *lane, double startPos, double endPos, const std::string &name, const std::vector< std::string > &lines, bool friendlyPosition)
Builds a container stop.
static bool buildChargingStation (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNELane *lane, double startPos, double endPos, const std::string &name, double chargingPower, double efficiency, bool chargeInTransit, double chargeDelay, bool friendlyPosition)
Builds a charging Station.
static bool buildDetectorE1 (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNELane *lane, double pos, double freq, const std::string &filename, const std::string &vehicleTypes, bool friendlyPos)
Builds a induction loop detector (E1)
static bool buildDetectorE2 (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNELane *lane, double pos, double length, double freq, const std::string &filename, bool cont, const double timeThreshold, double speedThreshold, double jamThreshold, bool friendlyPos)
Builds a lane Area Detector (E2)
static bool buildDetectorE3 (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, Position pos, double freq, const std::string &filename, const double timeThreshold, double speedThreshold)
Builds a multi entry exit detector (E3)
static bool buildDetectorEntry (GNEViewNet *viewNet, bool allowUndoRedo, GNEDetectorE3 *E3Parent, GNELane *lane, double pos, bool friendlyPos)
Builds a entry detector (E3)
static bool buildDetectorExit (GNEViewNet *viewNet, bool allowUndoRedo, GNEDetectorE3 *E3Parent, GNELane *lane, double pos, bool friendlyPos)
Builds a exit detector (E3)
static bool buildCalibrator (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNELane *lane, double pos, const std::string &outfile, double freq)
builds a microscopic calibrator over a lane
static bool buildCalibrator (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNEEdge *edge, double pos, const std::string &outfile, double freq)
builds a microscopic calibrator over an edge
static bool buildCalibratorRoute (GNEViewNet *viewNet, bool allowUndoRedo, GNECalibrator *calibratorParent, const std::string &routeID, const std::vector< GNEEdge *> &edges, const RGBColor &color)
static bool buildCalibratorVehicleType (GNEViewNet *viewNet, bool allowUndoRedo, GNECalibrator *calibratorParent, std::string vehicleTypeID, double accel, double decel, double sigma, double tau, double length, double minGap, double maxSpeed, double speedFactor, double speedDev, const RGBColor &color, SUMOVehicleClass vClass, const std::string &emissionClass, SUMOVehicleShape shape, double width, const std::string &filename, double impatience, const std::string &laneChangeModel, const std::string &carFollowModel, int personCapacity, int containerCapacity, double boardingDuration, double loadingDuration, const std::string &latAlignment, double minGapLat, double maxSpeedLat)
static bool buildCalibratorFlow (GNEViewNet *viewNet, bool allowUndoRedo, GNECalibrator *calibratorParent, const std::string &flowID, GNECalibratorRoute *route, GNECalibratorVehicleType *vtype, const RGBColor &color, const std::string &departLane, const std::string &departPos, const std::string &departSpeed, const std::string &arrivalLane, const std::string &arrivalPos, const std::string &arrivalSpeed, const std::string &line, int personNumber, int containerNumber, bool reroute, const std::string &departPosLat, const std::string &arrivalPosLat, double begin, double end, double vehsPerHour, double period, double probability, int number, int flowType)
static bool buildRerouter (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, Position pos, const std::vector< GNEEdge *> &edges, double prob, const std::string &file, bool off, double timeThreshold)
builds a rerouter
static bool buildRerouterInterval (GNEViewNet *viewNet, bool allowUndoRedo, GNERerouter *rerouterParent, double begin, double end)
builds a rerouter interval
static bool buildClosingLaneReroute (GNEViewNet *viewNet, bool allowUndoRedo, GNERerouterInterval *rerouterIntervalParent, GNELane *closedLane, SVCPermissions allowedVehicles, SVCPermissions disallowedVehicles)
static bool buildClosingReroute (GNEViewNet *viewNet, bool allowUndoRedo, GNERerouterInterval *rerouterIntervalParent, GNEEdge *closedEdge, SVCPermissions allowedVehicles, SVCPermissions disallowedVehicles)
static bool builDestProbReroute (GNEViewNet *viewNet, bool allowUndoRedo, GNERerouterInterval *rerouterIntervalParent, GNEEdge *newEdgeDestination, double probability)
static bool buildRouteProbReroute (GNEViewNet *viewNet, bool allowUndoRedo, GNERerouterInterval *rerouterIntervalParent, const std::string &newRouteId, double probability)
static bool buildRouteProbe (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, GNEEdge *edge, double freq, const std::string &file, double begin)
builds a Route probe
static bool buildVariableSpeedSign (GNEViewNet *viewNet, bool allowUndoRedo, const std::string &id, Position pos, const std::vector< GNELane *> &destLanes, const std::string &file)
Builds a VariableSpeedSign (lane speed trigger)
static bool buildVariableSpeedSignStep (GNEViewNet *viewNet, bool allowUndoRedo, GNEVariableSpeedSign *VSSParent, double time, double speed)
Builds a VariableSpeedSign Step.
static bool buildVaporizer (GNEViewNet *viewNet, bool allowUndoRedo, GNEEdge *edge, double startTime, double end)
Builds a vaporizer (lane speed trigger)
static bool fixStoppinPlacePosition (double &startPos, double &endPos, const double laneLength, const double minLength, const bool friendlyPos)
check if the position of an stoppingPlace over a lane is valid
static bool checkAndFixDetectorPositionPosition (double &pos, const double laneLength, const bool friendlyPos)
check if the position of a detector over a lane is valid
static bool fixE2DetectorPositionPosition (double &pos, double &length, const double laneLength, const bool friendlyPos)
check if the position of a detector over a lane is valid
int getTypeOfFlowDistribution (std::string flowID, double vehsPerHour, double period, double probability)
get a error message, if configuration of flow distribution is invalid
Detailed Description
Builds trigger objects for GNENet (busStops, chargingStations, detectors, etc..)
Definition at line 65 of file GNEAdditionalHandler.h.
Constructor & Destructor Documentation
GNEAdditionalHandler()
GNEAdditionalHandler::GNEAdditionalHandler (const std::string & file, GNEViewNet * viewNet, bool undoAdditionals = true)
Constructor.
Definition at line 69 of file GNEAdditionalHandler.cpp.
~GNEAdditionalHandler()
GNEAdditionalHandler::~GNEAdditionalHandler ()
Destructor.
Definition at line 76 of file GNEAdditionalHandler.cpp.
Member Function Documentation
buildAdditional()
bool GNEAdditionalHandler::buildAdditional (GNEViewNet * viewNet, bool allowUndoRedo, SumoXMLTag tag, std::map< SumoXMLAttr, std::string > values) static
Build additionals.
Parameters
[in] viewNet pointer to viewNet in wich additional will be created
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] tag tag of the additiona lto create
[in] values map with the attributes and values of the additional to create
Returns
true if was sucesfully created, false in other case
Definition at line 851 of file GNEAdditionalHandler.cpp.
References buildBusStop(), buildCalibrator(), buildChargingStation(), buildContainerStop(), buildDetectorE1(), buildDetectorE2(), buildDetectorE3(), buildDetectorEntry(), buildDetectorExit(), buildRerouter(), buildRouteProbe(), buildVaporizer(), buildVariableSpeedSign(), GNEViewNet::getNet(), GNE_ATTR_PARENT, GNEAttributeCarrier::parseGNEEdges(), GNEAttributeCarrier::parseGNELanes(), GeomConvHelper::parseShapeReporting(), GNENet::retrieveAdditional(), GNENet::retrieveEdge(), GNENet::retrieveLane(), SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONT, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_END, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, SUMO_ATTR_PROB, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_VTYPES, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::addAdditional().
buildBusStop()
bool GNEAdditionalHandler::buildBusStop (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNELane * lane, double startPos, double endPos, const std::string & name, const std::vector< std::string > & lines, bool friendlyPosition) static
Builds a bus stop.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the bus stop
[in] lane The lane the bus stop is placed on
[in] startPos Begin position of the bus stop on the lane
[in] endPos End position of the bus stop on the lane
[in] name Name of busStop
[in] lines Names of the bus lines that halt on this bus stop
[in] friendlyPos enable or disable friendly position
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the bus stop can not be added to the net (is duplicate)
Definition at line 1079 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_BUS_STOP, and toString().
Referenced by buildAdditional(), and parseAndBuildBusStop().
buildCalibrator() [1/2]
bool GNEAdditionalHandler::buildCalibrator (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNELane * lane, double pos, const std::string & outfile, double freq) static
builds a microscopic calibrator over a lane
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the calibrator
[in] lane The lane the calibrator is placed at
[in] pos The position on the edge the calibrator lies at
[in] outfile te file in which write results
Returns
true if was sucesfully created, false in other case
Todo:
Is the position correct/needed
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (is duplicate)
Definition at line 1239 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GUISUMOAbstractView::centerTo(), GNENet::getAdditional(), GUIGlObject::getGlID(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CALIBRATOR, and toString().
Referenced by buildAdditional(), and parseAndBuildCalibrator().
buildCalibrator() [2/2]
bool GNEAdditionalHandler::buildCalibrator (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNEEdge * edge, double pos, const std::string & outfile, double freq) static
builds a microscopic calibrator over an edge
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the calibrator
[in] edge The edge the calibrator is placed at
[in] pos The position on the edge the calibrator lies at
[in] outfile te file in which write results
Returns
true if was sucesfully created, false in other case
Todo:
Is the position correct/needed
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (is duplicate)
Definition at line 1260 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GUISUMOAbstractView::centerTo(), GNENet::getAdditional(), GUIGlObject::getGlID(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CALIBRATOR, and toString().
buildCalibratorFlow()
bool GNEAdditionalHandler::buildCalibratorFlow (GNEViewNet * viewNet, bool allowUndoRedo, GNECalibrator * calibratorParent, const std::string & flowID, GNECalibratorRoute * route, GNECalibratorVehicleType * vtype, const RGBColor & color, const std::string & departLane, const std::string & departPos, const std::string & departSpeed, const std::string & arrivalLane, const std::string & arrivalPos, const std::string & arrivalSpeed, const std::string & line, int personNumber, int containerNumber, bool reroute, const std::string & departPosLat, const std::string & arrivalPosLat, double begin, double end, double vehsPerHour, double period, double probability, int number, int flowType) static
DOCUMENTAR
Definition at line 1332 of file GNEAdditionalHandler.cpp.
References GNECalibrator::addCalibratorFlow(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNENet::insertCalibratorFlow(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveCalibratorFlow(), SUMO_TAG_FLOW, and toString().
Referenced by parseAndBuildCalibratorFlow().
buildCalibratorRoute()
bool GNEAdditionalHandler::buildCalibratorRoute (GNEViewNet * viewNet, bool allowUndoRedo, GNECalibrator * calibratorParent, const std::string & routeID, const std::vector< GNEEdge *> & edges, const RGBColor & color) static
DOCUMENTAR
Definition at line 1281 of file GNEAdditionalHandler.cpp.
References GNECalibrator::addCalibratorRoute(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNENet::insertCalibratorRoute(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveCalibratorRoute(), SUMO_TAG_ROUTE, and toString().
Referenced by parseAndBuildCalibratorRoute().
buildCalibratorVehicleType()
bool GNEAdditionalHandler::buildCalibratorVehicleType (GNEViewNet * viewNet, bool allowUndoRedo, GNECalibrator * calibratorParent, std::string vehicleTypeID, double accel, double decel, double sigma, double tau, double length, double minGap, double maxSpeed, double speedFactor, double speedDev, const RGBColor & color, SUMOVehicleClass vClass, const std::string & emissionClass, SUMOVehicleShape shape, double width, const std::string & filename, double impatience, const std::string & laneChangeModel, const std::string & carFollowModel, int personCapacity, int containerCapacity, double boardingDuration, double loadingDuration, const std::string & latAlignment, double minGapLat, double maxSpeedLat) static
DOCUMENTAR
Definition at line 1303 of file GNEAdditionalHandler.cpp.
References GNECalibrator::addCalibratorVehicleType(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNENet::insertCalibratorVehicleType(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveCalibratorVehicleType(), SUMO_TAG_VTYPE, and toString().
Referenced by parseAndBuildCalibratorVehicleType().
buildChargingStation()
bool GNEAdditionalHandler::buildChargingStation (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNELane * lane, double startPos, double endPos, const std::string & name, double chargingPower, double efficiency, bool chargeInTransit, double chargeDelay, bool friendlyPosition) static
Builds a charging Station.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the charging Station
[in] lane The lane the charging Station is placed on
[in] startPos Begin position of the charging Station on the lane
[in] endPos End position of the charging Station on the lane
[in] name Name of charging station
[in] chargingPower power charged in every timeStep
[in] efficiency efficiency of the charge
[in] chargeInTransit enable or disable charge in transit
[in] chargeDelay delay in the charge
[in] friendlyPos enable or disable friendly position
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the charging Station can not be added to the net (is duplicate)
Definition at line 1117 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CHARGING_STATION, and toString().
Referenced by buildAdditional(), and parseAndBuildChargingStation().
buildClosingLaneReroute()
bool GNEAdditionalHandler::buildClosingLaneReroute (GNEViewNet * viewNet, bool allowUndoRedo, GNERerouterInterval * rerouterIntervalParent, GNELane * closedLane, SVCPermissions allowedVehicles, SVCPermissions disallowedVehicles) static
DOCUMENTAR
Definition at line 1407 of file GNEAdditionalHandler.cpp.
References GNERerouterInterval::addClosingLaneReroute(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by parseAndBuildRerouterClosingLaneReroute().
buildClosingReroute()
bool GNEAdditionalHandler::buildClosingReroute (GNEViewNet * viewNet, bool allowUndoRedo, GNERerouterInterval * rerouterIntervalParent, GNEEdge * closedEdge, SVCPermissions allowedVehicles, SVCPermissions disallowedVehicles) static
DOCUMENTAR
Definition at line 1423 of file GNEAdditionalHandler.cpp.
References GNERerouterInterval::addClosingReroute(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by parseAndBuildRerouterClosingReroute().
buildContainerStop()
bool GNEAdditionalHandler::buildContainerStop (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNELane * lane, double startPos, double endPos, const std::string & name, const std::vector< std::string > & lines, bool friendlyPosition) static
Builds a container stop.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the container stop
[in] lane The lane the container stop is placed on
[in] startPos Begin position of the container stop on the lane
[in] endPos End position of the container stop on the lane
[in] name Name of container stop
[in] lines Names of the bus lines that halt on this container stop
[in] friendlyPos enable or disable friendly position
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the container stop can not be added to the net (is duplicate)
Definition at line 1098 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_CONTAINER_STOP, and toString().
Referenced by buildAdditional(), and parseAndBuildContainerStop().
buildDetectorE1()
bool GNEAdditionalHandler::buildDetectorE1 (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNELane * lane, double pos, double freq, const std::string & filename, const std::string & vehicleTypes, bool friendlyPos) static
Builds a induction loop detector (E1)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the detector
[in] lane The lane the detector is placed on
[in] pos position of the detector on the lane
[in] freq the aggregation period the values the detector collects shall be summed up.
[in] filename The path to the output file.
[in] splitByType If set, the collected values will be additionally reported on per-vehicle type base.
[in] friendlyPos enable or disable friendly position
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the detector can not be added to the net (is duplicate)
Definition at line 1136 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_E1DETECTOR, and toString().
Referenced by buildAdditional(), and parseAndBuildDetectorE1().
buildDetectorE2()
bool GNEAdditionalHandler::buildDetectorE2 (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNELane * lane, double pos, double length, double freq, const std::string & filename, bool cont, const double timeThreshold, double speedThreshold, double jamThreshold, bool friendlyPos) static
Builds a lane Area Detector (E2)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the detector
[in] lane The lane the detector is placed on
[in] pos position of the detector on the lane
Definition at line 1155 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_E2DETECTOR, and toString().
Referenced by buildAdditional(), and parseAndBuildDetectorE2().
buildDetectorE3()
bool GNEAdditionalHandler::buildDetectorE3 (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, Position pos, double freq, const std::string & filename, const double timeThreshold, double speedThreshold) static
Builds a multi entry exit detector (E3)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the detector
[in] pos position of the detector in the map
[in] freq the aggregation period the values the detector collects shall be summed up.
[in] filename The path to the output file.
[in] timeThreshold The time-based threshold that describes how much time has to pass until a vehicle is recognized as halting
[in] speedThreshold The speed-based threshold that describes how slow a vehicle has to be to be recognized as halting
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the detector can not be added to the net (is duplicate)
Definition at line 1175 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_E3DETECTOR, and toString().
Referenced by buildAdditional(), and parseAndBuildDetectorE3().
buildDetectorEntry()
bool GNEAdditionalHandler::buildDetectorEntry (GNEViewNet * viewNet, bool allowUndoRedo, GNEDetectorE3 * E3Parent, GNELane * lane, double pos, bool friendlyPos) static
Builds a entry detector (E3)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] E3Parent pointer to E3 detector parent
[in] lane The lane in which the entry detector is placed on
[in] pos position of the entry detector on the lane
[in] friendlyPos enable or disable friendly position
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the entry detector can not be added to the net (invalid parent or lane)
Definition at line 1193 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_DET_ENTRY, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANE, and toString().
Referenced by buildAdditional(), and parseAndBuildDetectorEntry().
buildDetectorExit()
bool GNEAdditionalHandler::buildDetectorExit (GNEViewNet * viewNet, bool allowUndoRedo, GNEDetectorE3 * E3Parent, GNELane * lane, double pos, bool friendlyPos) static
Builds a exit detector (E3)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] E3Parent pointer to E3 detector parent
[in] lane The lane in which the exit detector is placed on
[in] pos position of the exit detector on the lane
[in] friendlyPos enable or disable friendly position
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the exit detector can not be added to the net (invalid parent or lane
Definition at line 1216 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANE, and toString().
Referenced by buildAdditional(), and parseAndBuildDetectorExit().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
builDestProbReroute()
bool GNEAdditionalHandler::builDestProbReroute (GNEViewNet * viewNet, bool allowUndoRedo, GNERerouterInterval * rerouterIntervalParent, GNEEdge * newEdgeDestination, double probability) static
DOCUMENTAR
Definition at line 1439 of file GNEAdditionalHandler.cpp.
References GNERerouterInterval::addDestProbReroute(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by parseAndBuildRerouterDestProbReroute().
buildRerouter()
bool GNEAdditionalHandler::buildRerouter (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, Position pos, const std::vector< GNEEdge *> & edges, double prob, const std::string & file, bool off, double timeThreshold) static
builds a rerouter
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the rerouter
[in] pos position of the rerouter in the map
[in] edges The edges the rerouter is placed at
[in] prob The probability the rerouter reoutes vehicles with
[in] file The file to read the reroute definitions from
Returns
true if was sucesfully created, false in other case
Definition at line 1361 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_REROUTER, and toString().
Referenced by buildAdditional(), and parseAndBuildRerouter().
buildRerouterInterval()
bool GNEAdditionalHandler::buildRerouterInterval (GNEViewNet * viewNet, bool allowUndoRedo, GNERerouter * rerouterParent, double begin, double end) static
builds a rerouter interval
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] rerouterParent rerouter in which interval is placed
[in] begin begin of interval
[in] end end of interval
Returns
true if was sucesfully created, false in other case
Definition at line 1383 of file GNEAdditionalHandler.cpp.
References GNERerouter::addRerouterInterval(), GNEAttributeCarrier::getID(), GNERerouter::getNumberOfOverlappedIntervals(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNERerouter::removeRerouterInterval(), SUMO_TAG_INTERVAL, and toString().
Referenced by parseAndBuildRerouterInterval().
buildRouteProbe()
bool GNEAdditionalHandler::buildRouteProbe (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, GNEEdge * edge, double freq, const std::string & file, double begin) static
builds a Route probe
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the routeprobe
[in] edge The edges the routeprobe is placed at
[in] freq the aggregation period the values the routeprobe collects shall be summed up.
[in] file The file to read the routeprobe definitions from
[in] begin The time at which to start generating output
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the Route Probe can not be added to the net (is duplicate)
Definition at line 1471 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GUISUMOAbstractView::centerTo(), GNENet::getAdditional(), GUIGlObject::getGlID(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_ROUTEPROBE, and toString().
Referenced by buildAdditional(), and parseAndBuildRouteProbe().
buildRouteProbReroute()
bool GNEAdditionalHandler::buildRouteProbReroute (GNEViewNet * viewNet, bool allowUndoRedo, GNERerouterInterval * rerouterIntervalParent, const std::string & newRouteId, double probability) static
DOCUMENTAR
Definition at line 1455 of file GNEAdditionalHandler.cpp.
References GNERerouterInterval::addRouteProbReroute(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by parseAndBuildRerouterRouteProbReroute().
buildVaporizer()
bool GNEAdditionalHandler::buildVaporizer (GNEViewNet * viewNet, bool allowUndoRedo, GNEEdge * edge, double startTime, double end) static
Builds a vaporizer (lane speed trigger)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] edge edge in which tis vaporizer is placed
[in] startTime time in which this vaporizer start
[in] end time in which this vaporizer ends
Returns
true if was sucesfully created, false in other case
Exceptions
ProcessError If the XML definition file is errornous
Definition at line 1530 of file GNEAdditionalHandler.cpp.
References GNENetElement::addAdditionalChild(), GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_VAPORIZER, and toString().
Referenced by buildAdditional(), and parseAndBuildVaporizer().
buildVariableSpeedSign()
bool GNEAdditionalHandler::buildVariableSpeedSign (GNEViewNet * viewNet, bool allowUndoRedo, const std::string & id, Position pos, const std::vector< GNELane *> & destLanes, const std::string & file) static
Builds a VariableSpeedSign (lane speed trigger)
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] id The id of the lane speed trigger
[in] destLanes List of lanes affected by this speed trigger
[in] file Name of the file to read the speeds to set from
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the VariableSpeedSign can not be added to the net (is duplicate)
Definition at line 1492 of file GNEAdditionalHandler.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNENet::insertAdditional(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_TAG_VSS, and toString().
Referenced by buildAdditional(), and parseAndBuildVariableSpeedSign().
buildVariableSpeedSignStep()
bool GNEAdditionalHandler::buildVariableSpeedSignStep (GNEViewNet * viewNet, bool allowUndoRedo, GNEVariableSpeedSign * VSSParent, double time, double speed) static
Builds a VariableSpeedSign Step.
Parameters
[in] viewNet viewNet in which element will be inserted
[in] allowUndoRedo enable or disable remove created additional with ctrl + Z / ctrl + Y
[in] VSSParent Variable Speed Sign parent
[in] time step's time
[in] speed step's speed
Returns
true if was sucesfully created, false in other case
Exceptions
InvalidArgument If the Variable Speed Sign Step can not be added to the net (is duplicate)
Definition at line 1514 of file GNEAdditionalHandler.cpp.
References GNEVariableSpeedSign::addVariableSpeedSignStep(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by parseAndBuildVariableSpeedSignStep().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
checkAndFixDetectorPositionPosition()
bool GNEAdditionalHandler::checkAndFixDetectorPositionPosition (double & pos, const double laneLength, const bool friendlyPos) static
check if the position of a detector over a lane is valid
Parameters
[in] pos pos position of detector
[in] laneLength Length of the lane
[in] friendlyPos Attribute of detector
Returns
true if the detector position is valid, false in otherweise
Definition at line 1618 of file GNEAdditionalHandler.cpp.
Referenced by GNEDialog_FixAdditionalPositions::onCmdAccept(), parseAndBuildDetectorE1(), parseAndBuildDetectorEntry(), and parseAndBuildDetectorExit().
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
fixE2DetectorPositionPosition()
bool GNEAdditionalHandler::fixE2DetectorPositionPosition (double & pos, double & length, const double laneLength, const bool friendlyPos) static
check if the position of a detector over a lane is valid
Parameters
[in] startPos Start position of detector
[in] length length of detector
[in] laneLength Length of the lane
[in] friendlyPos Attribute of detector
Returns
true if the detector position is valid, false in otherweise
Definition at line 1660 of file GNEAdditionalHandler.cpp.
Referenced by GNEDialog_FixAdditionalPositions::onCmdAccept(), and parseAndBuildDetectorE2().
fixStoppinPlacePosition()
bool GNEAdditionalHandler::fixStoppinPlacePosition (double & startPos, double & endPos, const double laneLength, const double minLength, const bool friendlyPos) static
check if the position of an stoppingPlace over a lane is valid
Parameters
[in] startPos Start position of stoppingPlace
[in] endPos End position of stoppingPlace
[in] laneLength Length of the lane
[in] minLength Min length of the stoppingPlace
[in] friendlyPos Attribute of stoppingPlace
Returns
true if the stoppingPlace position is valid, false in otherweise
Definition at line 1582 of file GNEAdditionalHandler.cpp.
Referenced by GNEDialog_FixAdditionalPositions::onCmdAccept(), parseAndBuildBusStop(), parseAndBuildChargingStation(), and parseAndBuildContainerStop().
getFileName() [1/2]
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
getFileName() [2/2]
std::string GNEAdditionalHandler::getFileName (const SUMOSAXAttributes & attrs, const std::string & base, const bool allowEmpty = false)
Helper method to obtain the filename.
Parameters
[in] attrs The attributes to obtain the file name from
[in] base The base path (the path the loaded additional file lies in)
Returns
The (expanded) path to the named file
Todo:
Recheck usage of the helper class
Definition at line 1547 of file GNEAdditionalHandler.cpp.
References FileHelpers::getConfigurationRelative(), SUMOSAXAttributes::getOpt(), FileHelpers::isAbsolute(), SUMO_ATTR_FILE, and WRITE_WARNING.
getPosition()
double GNEAdditionalHandler::getPosition (double pos, GNELane & lane, bool friendlyPos, const std::string & additionalID)
extracts the position, checks whether it shall be mirrored and checks whether it is within the lane.
Parameters
[in] pos position of additional over lane
[in] lane The lane the position shall be valid for
[in] friendlyPos flag to indicate if friendlyPos is enabled
[in] additionalID ID of additional
Returns
The position on the lane
Definition at line 1566 of file GNEAdditionalHandler.cpp.
References GNEAttributeCarrier::getID(), GNELane::getLaneShapeLength(), and WRITE_WARNING.
getTypeOfFlowDistribution()
int GNEAdditionalHandler::getTypeOfFlowDistribution (std::string flowID, double vehsPerHour, double period, double probability) private
get a error message, if configuration of flow distribution is invalid
Definition at line 1633 of file GNEAdditionalHandler.cpp.
References GNECalibratorFlow::GNE_CALIBRATORFLOW_INVALID, GNECalibratorFlow::GNE_CALIBRATORFLOW_PERIOD, GNECalibratorFlow::GNE_CALIBRATORFLOW_PROBABILITY, GNECalibratorFlow::GNE_CALIBRATORFLOW_VEHSPERHOUR, SUMO_ATTR_PERIOD, SUMO_ATTR_PROB, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_FLOW, toString(), and WRITE_WARNING.
Referenced by parseAndBuildCalibratorFlow().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, PCLoaderOSM::EdgesHandler, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, MSCalibrator, NIXMLEdgesHandler, NIXMLNodesHandler, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, ShapeHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, and ROMARouteHandler.
Definition at line 226 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), and SUMOSAXReader::parseNext().
myStartElement()
void GNEAdditionalHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 80 of file GNEAdditionalHandler.cpp.
References parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildCalibratorFlow(), parseAndBuildCalibratorRoute(), parseAndBuildCalibratorVehicleType(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildRerouter(), parseAndBuildRerouterClosingLaneReroute(), parseAndBuildRerouterClosingReroute(), parseAndBuildRerouterDestProbReroute(), parseAndBuildRerouterInterval(), parseAndBuildRerouterRouteProbReroute(), parseAndBuildRouteProbe(), parseAndBuildVaporizer(), parseAndBuildVariableSpeedSign(), parseAndBuildVariableSpeedSignStep(), SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_INDUCTION_LOOP, SUMO_TAG_INTERVAL, SUMO_TAG_LANE_AREA_DETECTOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_TRAIN_STOP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
parseAndBuildBusStop()
void GNEAdditionalHandler::parseAndBuildBusStop (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a bus stop.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 540 of file GNEAdditionalHandler.cpp.
References buildBusStop(), fixStoppinPlacePosition(), GNENet::getAdditional(), GNELane::getLaneParametricLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, POSITION_EPS, GNENet::retrieveLane(), SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_STARTPOS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildCalibrator()
void GNEAdditionalHandler::parseAndBuildCalibrator (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a mesoscopic or microscopic calibrator.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 642 of file GNEAdditionalHandler.cpp.
References buildCalibrator(), GNENet::getAdditional(), GNEViewNet::getNet(), SUMOSAXAttributes::hasAttribute(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveEdge(), GNENet::retrieveLane(), SUMO_ATTR_EDGE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, SUMO_TAG_CALIBRATOR, SUMO_TAG_LANECALIBRATOR, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildCalibratorFlow()
void GNEAdditionalHandler::parseAndBuildCalibratorFlow (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses flow values of Calibrators.
Parameters
[in] attrs SAX-attributes which define the flows
[in] tag of the additional
Definition at line 295 of file GNEAdditionalHandler.cpp.
References buildCalibratorFlow(), GNEViewNet::getNet(), getTypeOfFlowDistribution(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveCalibratorFlow(), GNENet::retrieveCalibratorRoute(), GNENet::retrieveCalibratorVehicleType(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_CALIBRATOR, SUMO_TAG_FLOW, SUMO_TAG_ROUTE, SUMO_TAG_VTYPE, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildCalibratorRoute()
void GNEAdditionalHandler::parseAndBuildCalibratorRoute (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses route values of Calibrators.
Parameters
[in] attrs SAX-attributes which define the routes
[in] tag of the additional
Definition at line 217 of file GNEAdditionalHandler.cpp.
References buildCalibratorRoute(), GNEAttributeCarrier::checkGNEEdgesValid(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNEAttributeCarrier::parseGNEEdges(), GNENet::retrieveAdditional(), GNENet::retrieveCalibratorRoute(), SUMO_ATTR_COLOR, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_TAG_CALIBRATOR, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildCalibratorVehicleType()
void GNEAdditionalHandler::parseAndBuildCalibratorVehicleType (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses vehicle type values of Calibrators.
Parameters
[in] attrs SAX-attributes which define the vehicle types
[in] tag of the additional
Definition at line 246 of file GNEAdditionalHandler.cpp.
References buildCalibratorVehicleType(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveCalibratorVehicleType(), SUMO_ATTR_ACCEL, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_DECEL, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VCLASS, SUMO_ATTR_WIDTH, SUMO_TAG_CALIBRATOR, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildChargingStation()
void GNEAdditionalHandler::parseAndBuildChargingStation (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a charging station.
Parameters
[in] attrs SAXattributes which define the trigger
[in] tag of the additional
Definition at line 606 of file GNEAdditionalHandler.cpp.
References buildChargingStation(), fixStoppinPlacePosition(), GNENet::getAdditional(), GNELane::getLaneParametricLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, POSITION_EPS, GNENet::retrieveLane(), SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_NAME, SUMO_ATTR_STARTPOS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildContainerStop()
void GNEAdditionalHandler::parseAndBuildContainerStop (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a container stop.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 573 of file GNEAdditionalHandler.cpp.
References buildContainerStop(), fixStoppinPlacePosition(), GNENet::getAdditional(), GNELane::getLaneParametricLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, POSITION_EPS, GNENet::retrieveLane(), SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_STARTPOS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildDetectorE1()
void GNEAdditionalHandler::parseAndBuildDetectorE1 (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a induction loop detector (E1)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 705 of file GNEAdditionalHandler.cpp.
References buildDetectorE1(), checkAndFixDetectorPositionPosition(), GNENet::getAdditional(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_VTYPES, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildDetectorE2()
void GNEAdditionalHandler::parseAndBuildDetectorE2 (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a lane area detector (E2)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 737 of file GNEAdditionalHandler.cpp.
References buildDetectorE2(), fixE2DetectorPositionPosition(), GNENet::getAdditional(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_CONT, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LANE, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildDetectorE3()
void GNEAdditionalHandler::parseAndBuildDetectorE3 (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a multi entry exit detector (E3)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 773 of file GNEAdditionalHandler.cpp.
References buildDetectorE3(), GNENet::getAdditional(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_X, SUMO_ATTR_Y, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildDetectorEntry()
void GNEAdditionalHandler::parseAndBuildDetectorEntry (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Entry detector.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 799 of file GNEAdditionalHandler.cpp.
References buildDetectorEntry(), checkAndFixDetectorPositionPosition(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveLane(), SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_TAG_E3DETECTOR, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildDetectorExit()
void GNEAdditionalHandler::parseAndBuildDetectorExit (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Exit detector.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 825 of file GNEAdditionalHandler.cpp.
References buildDetectorExit(), checkAndFixDetectorPositionPosition(), GNELane::getLaneShapeLength(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveLane(), SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_TAG_E3DETECTOR, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRerouter()
void GNEAdditionalHandler::parseAndBuildRerouter (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a rerouter.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 396 of file GNEAdditionalHandler.cpp.
References buildRerouter(), GNEAttributeCarrier::checkGNEEdgesValid(), GNENet::getAdditional(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNEAttributeCarrier::parseGNEEdges(), SUMO_ATTR_EDGES, SUMO_ATTR_FILE, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_OFF, SUMO_ATTR_PROB, SUMO_ATTR_X, SUMO_ATTR_Y, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRerouterClosingLaneReroute()
void GNEAdditionalHandler::parseAndBuildRerouterClosingLaneReroute (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Closing Lane reroute.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 449 of file GNEAdditionalHandler.cpp.
References buildClosingLaneReroute(), GNEViewNet::getNet(), GNENet::getRerouterInterval(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveLane(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_TAG_INTERVAL, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRerouterClosingReroute()
void GNEAdditionalHandler::parseAndBuildRerouterClosingReroute (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Closing Reroute.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 473 of file GNEAdditionalHandler.cpp.
References buildClosingReroute(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveEdge(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_TAG_INTERVAL, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRerouterDestProbReroute()
void GNEAdditionalHandler::parseAndBuildRerouterDestProbReroute (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Destiny Prob Reroute.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 497 of file GNEAdditionalHandler.cpp.
References builDestProbReroute(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), GNENet::retrieveEdge(), SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_TAG_INTERVAL, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRerouterInterval()
void GNEAdditionalHandler::parseAndBuildRerouterInterval (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Rerouter Interval.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 428 of file GNEAdditionalHandler.cpp.
References buildRerouterInterval(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_TAG_REROUTER, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRerouterRouteProbReroute()
void GNEAdditionalHandler::parseAndBuildRerouterRouteProbReroute (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Route Prob Reroute.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 520 of file GNEAdditionalHandler.cpp.
References buildRouteProbReroute(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_TAG_INTERVAL, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildRouteProbe()
void GNEAdditionalHandler::parseAndBuildRouteProbe (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds routeProbe.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
Definition at line 189 of file GNEAdditionalHandler.cpp.
References buildRouteProbe(), GNENet::getAdditional(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveEdge(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildVaporizer()
void GNEAdditionalHandler::parseAndBuildVaporizer (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Builds a vaporization.
Parameters
[in] attrs SAX-attributes which define the vaporizer
[in] tag of the additional
Note
recheck throwing the exception
Definition at line 164 of file GNEAdditionalHandler.cpp.
References buildVaporizer(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNENet::retrieveEdge(), SUMO_ATTR_EDGE, SUMO_ATTR_END, SUMO_ATTR_STARTTIME, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildVariableSpeedSign()
void GNEAdditionalHandler::parseAndBuildVariableSpeedSign (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Variable Speed Signal (lane speed trigger)
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
See also
buildLaneSpeedTrigger
Definition at line 348 of file GNEAdditionalHandler.cpp.
References buildVariableSpeedSign(), GNEAttributeCarrier::checkGNELanesValid(), GNENet::getAdditional(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myUndoAdditionals, myViewNet, GNEAttributeCarrier::parseGNELanes(), SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_LANES, SUMO_ATTR_X, SUMO_ATTR_Y, toString(), and WRITE_WARNING.
Referenced by myStartElement().
parseAndBuildVariableSpeedSignStep()
void GNEAdditionalHandler::parseAndBuildVariableSpeedSignStep (const SUMOSAXAttributes & attrs, const SumoXMLTag & tag)
Parses his values and builds a Variable Speed Signal Step.
Parameters
[in] attrs SAX-attributes which define the trigger
[in] tag of the additional
See also
buildLaneSpeedTrigger
Definition at line 376 of file GNEAdditionalHandler.cpp.
References buildVariableSpeedSignStep(), GNEViewNet::getNet(), myLastInsertedAdditionalParent, myViewNet, GNENet::retrieveAdditional(), SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_TAG_VSS, toString(), and WRITE_WARNING.
Referenced by myStartElement().
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myLastInsertedAdditionalParent
std::string GNEAdditionalHandler::myLastInsertedAdditionalParent protected
ID of last inserted Additional parent (needed for additionasl that own a child)
Definition at line 552 of file GNEAdditionalHandler.h.
Referenced by parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildCalibratorFlow(), parseAndBuildCalibratorRoute(), parseAndBuildCalibratorVehicleType(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildRerouter(), parseAndBuildRerouterClosingLaneReroute(), parseAndBuildRerouterClosingReroute(), parseAndBuildRerouterDestProbReroute(), parseAndBuildRerouterInterval(), parseAndBuildRerouterRouteProbReroute(), parseAndBuildRouteProbe(), parseAndBuildVaporizer(), parseAndBuildVariableSpeedSign(), and parseAndBuildVariableSpeedSignStep().
myUndoAdditionals
bool GNEAdditionalHandler::myUndoAdditionals protected
flag to check if created additionals must be undo and redo
Definition at line 549 of file GNEAdditionalHandler.h.
Referenced by parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildCalibratorRoute(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildRerouter(), parseAndBuildRouteProbe(), parseAndBuildVaporizer(), and parseAndBuildVariableSpeedSign().
myViewNet
GNEViewNet* GNEAdditionalHandler::myViewNet protected
pointer to View's Net
Definition at line 546 of file GNEAdditionalHandler.h.
Referenced by parseAndBuildBusStop(), parseAndBuildCalibrator(), parseAndBuildCalibratorFlow(), parseAndBuildCalibratorRoute(), parseAndBuildCalibratorVehicleType(), parseAndBuildChargingStation(), parseAndBuildContainerStop(), parseAndBuildDetectorE1(), parseAndBuildDetectorE2(), parseAndBuildDetectorE3(), parseAndBuildDetectorEntry(), parseAndBuildDetectorExit(), parseAndBuildRerouter(), parseAndBuildRerouterClosingLaneReroute(), parseAndBuildRerouterClosingReroute(), parseAndBuildRerouterDestProbReroute(), parseAndBuildRerouterInterval(), parseAndBuildRerouterRouteProbReroute(), parseAndBuildRouteProbe(), parseAndBuildVaporizer(), parseAndBuildVariableSpeedSign(), and parseAndBuildVariableSpeedSignStep().
The documentation for this class was generated from the following files:
GNEAdditionalHandler.h
GNEAdditionalHandler.cpp