SUMO - Simulation of Urban MObility: GUISUMOAbstractView Class Reference
GUISUMOAbstractView Class Reference
#include <GUISUMOAbstractView.h>
Data Structures
struct Decal
A decal (an image) that can be shown.
Public Member Functions
void addDecals (const std::vector< Decal > &decals)
add decals
virtual void buildColorRainbow (GUIColorScheme &, int, GUIGlObjectType)
recalibrate color scheme according to the current value range
virtual void buildViewToolBars (GUIGlChildWindow &)
builds the view toolbars
virtual void centerTo (GUIGlID id, bool applyZoom, double zoomDist=20)
centers to the chosen artifact
void centerTo (const Boundary &bound)
centers to the chosen artifact
virtual void copyViewportTo (GUISUMOAbstractView *view)
copy the viewport to the given view
void destroyPopup ()
destoys the popup
GUIPerspectiveChanger & getChanger () const
get changer
FXComboBox & getColoringSchemesCombo ()
get coloring schemes combo
double getDelay () const
Returns the delay of the parent application.
double getGridHeight () const
get grid Height
double getGridWidth () const
get grid width
const Position & getPopupPosition () const
get position of current popup
Position getPositionInformation () const
Returns the cursor's x/y position within the network.
virtual GUIGlID getTrackedID () const
get tracked id
GUIDialog_EditViewport * getViewportEditor ()
get the viewport and create it on first access
Boundary getVisibleBoundary () const
get visible boundary
GUIVisualizationSettings * getVisualisationSettings () const
get visualitation settings
GUIVisualizationSettings * getVisualisationSettings ()
get visualisation settings
GUISUMOAbstractView (FXComposite *p, GUIMainWindow &app, GUIGlChildWindow *parent, const SUMORTree &grid, FXGLVisual *glVis, FXGLCanvas *share)
constructor
bool isInEditMode ()
returns true, if the edit button was pressed
double m2p (double meter) const
meter-to-pixels conversion method
FXbool makeCurrent ()
A reimplementation due to some internal reasons.
virtual void onGamingClick (Position)
on gaming click
virtual void openObjectDialog ()
double p2m (double pixel) const
pixels-to-meters conversion method
virtual void recenterView ()
recenters the view
void remove (GUIDialog_EditViewport *)
remove viewport
void remove (GUIDialog_ViewSettings *)
remove view settings
Position screenPos2NetPos (int x, int y) const
Translate screen position to network position.
void setApplicationSnapshots (std::set< SUMOTime > *snapshots, FXMutex *lock)
add snapshot synchronization
virtual bool setColorScheme (const std::string &)
set color scheme
void setDelay (double delay)
Sets the delay of the parent application.
virtual void setViewportFromTo (const Position &lookFrom, const Position &lookAt)
applies the given viewport settings
void setWindowCursorPosition (FXint x, FXint y)
Returns the information whether rotation is allowd.
void showToolTips (bool val)
show tool tips
virtual void showViewportEditor ()
show viewport editor
void showViewschemeEditor ()
show viewsscheme editor
Position snapToActiveGrid (const Position &pos) const
Returns a position that is mapped to the closest grid point if the grid is active.
virtual void startTrack (int)
star track
virtual void stopTrack ()
stop track
void updateToolTip ()
A method that updates the tooltip.
virtual ~GUISUMOAbstractView ()
destructor
virtual long onConfigure (FXObject *, FXSelector, void *)
mouse functions
virtual long onPaint (FXObject *, FXSelector, void *)
virtual long onLeftBtnPress (FXObject *, FXSelector, void *)
virtual long onLeftBtnRelease (FXObject *, FXSelector, void *)
virtual long onMiddleBtnPress (FXObject *, FXSelector, void *)
virtual long onMiddleBtnRelease (FXObject *, FXSelector, void *)
virtual long onRightBtnPress (FXObject *, FXSelector, void *)
virtual long onRightBtnRelease (FXObject *, FXSelector, void *)
virtual long onDoubleClicked (FXObject *, FXSelector, void *)
virtual long onMouseWheel (FXObject *, FXSelector, void *)
virtual long onMouseMove (FXObject *, FXSelector, void *)
virtual long onMouseLeft (FXObject *, FXSelector, void *)
virtual long onKeyPress (FXObject *o, FXSelector sel, void *data)
keyboard functions
virtual long onKeyRelease (FXObject *o, FXSelector sel, void *data)
Dealing with snapshots
void addSnapshot (SUMOTime time, const std::string &file)
Sets the snapshot time to file map.
std::string makeSnapshot (const std::string &destFile)
Takes a snapshots and writes it into the given file.
virtual void saveFrame (const std::string &destFile, FXColor *buf)
Adds a frame to a video snapshot which will be initialized if neccessary.
virtual void endSnapshot ()
Ends a video snapshot.
virtual void checkSnapshots ()
Checks whether it is time for a snapshot.
virtual SUMOTime getCurrentTimeStep () const
get the current simulation time
Additional visualisations
bool addAdditionalGLVisualisation (const GUIGlObject *const which)
Adds an object to call its additional visualisation method.
bool removeAdditionalGLVisualisation (const GUIGlObject *const which)
Removes an object from the list of objects that show additional things.
bool isAdditionalGLVisualisationEnabled (GUIGlObject *const which) const
Check if an object is added in the additional GL visualitation.
Protected Member Functions
void applyGLTransform (bool fixRatio=true)
applies gl-transformations to fit the Boundary given by myChanger onto the canvas. If fixRatio is true, this boundary will be enlarged to prevent anisotropic stretching. (this should be set to false when doing selections)
FXImage * checkGDALImage (Decal &d)
check whether we can read image data or position with gdal
void displayLegend ()
a line with ticks, and the length information.
virtual void doInit ()
doInit
virtual int doPaintGL (int, const Boundary &)
paint GL
void drawDecals ()
Draws the stored decals.
GUIGlID getObjectAtPosition (Position pos)
returns the id of the object at position using GL_SELECT
std::vector< GUIGlID > getObjectsAtPosition (Position pos, double radius)
returns the ids of the object at position within the given (rectangular) radius using GL_SELECT
std::vector< GUIGlID > getObjectsInBoundary (const Boundary &bound)
returns the ids of all objects in the given boundary
GUIGlID getObjectUnderCursor ()
returns the id of the object under the cursor using GL_SELECT
GUISUMOAbstractView ()
empty constructor
void paintGL ()
performs the painting of the simulation
void paintGLGrid ()
paints a grid
void showToolTipFor (const GUIGlID id)
invokes the tooltip for the given object
void updatePositionInformation () const
update position information
Protected Attributes
std::map< const GUIGlObject *, int > myAdditionallyDrawn
List of objects for which GUIGlObject::drawGLAdditional is called.
bool myAmInitialised
Internal information whether doInit() was called.
GUIMainWindow * myApp
The application.
std::set< SUMOTime > * myApplicationSnapshots
FXMutex * myApplicationSnapshotsLock
GUIPerspectiveChanger * myChanger
The perspective changer.
SUMORTree * myGrid
The visualization speed-up.
bool myInEditMode
Information whether too-tip informations shall be generated.
int myMouseHotspotX
Offset to the mouse-hotspot from the mouse position.
int myMouseHotspotY
GUIGlChildWindow * myParent
The parent window.
MFXMutex myPolyDrawLock
poly draw lock
GUIGLObjectPopupMenu * myPopup
The current popup-menu.
Position myPopupPosition
The current popup-menu position.
std::map< SUMOTime, std::vector< std::string > > mySnapshots
Snapshots.
MFXMutex mySnapshotsLock
The mutex to use before accessing the decals list in order to avoid thread conficts.
bool myUseToolTips
use tool tips
GUIDialog_EditViewport * myViewportChooser
viewport chooser
GUIDialog_ViewSettings * myVisualizationChanger
Visualization changer.
GUIVisualizationSettings * myVisualizationSettings
visualization settings
FXint myWindowCursorPositionX
Position of the cursor relative to the window.
FXint myWindowCursorPositionY
Optionally shown decals
The list of decals to show
std::vector< Decal > myDecals
MFXMutex myDecalsLock
The mutex to use before accessing the decals list in order to avoid thread conficts.
Detailed Description
This class is meant to be pure virtual later; It shall be the main class to inherit views of the simulation (micro- or macroscopic ones) from it.
Definition at line 80 of file GUISUMOAbstractView.h.
Constructor & Destructor Documentation
GUISUMOAbstractView() [1/2]
GUISUMOAbstractView::GUISUMOAbstractView (FXComposite * p, GUIMainWindow & app, GUIGlChildWindow * parent, const SUMORTree & grid, FXGLVisual * glVis, FXGLCanvas * share)
constructor
Definition at line 120 of file GUISUMOAbstractView.cpp.
References GUIVisualizationSettings::gaming, GUICompleteSchemeStorage::getDefault(), gSchemeStorage, and GUICompleteSchemeStorage::setViewport().
~GUISUMOAbstractView()
GUISUMOAbstractView::~GUISUMOAbstractView () virtual
destructor
Definition at line 150 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), gSchemeStorage, myChanger, myDecals, myPopup, myViewportChooser, myVisualizationChanger, myVisualizationSettings, GUIVisualizationSettings::name, GUICompleteSchemeStorage::saveViewport(), and GUICompleteSchemeStorage::setDefault().
GUISUMOAbstractView() [2/2]
GUISUMOAbstractView::GUISUMOAbstractView () inline protected
empty constructor
Definition at line 456 of file GUISUMOAbstractView.h.
Member Function Documentation
addAdditionalGLVisualisation()
bool GUISUMOAbstractView::addAdditionalGLVisualisation (const GUIGlObject *const which)
Adds an object to call its additional visualisation method.
Parameters
[in] which The object to add
Returns
Always true
See also
GUIGlObject::drawGLAdditional
Definition at line 1281 of file GUISUMOAbstractView.cpp.
References myAdditionallyDrawn.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), GUIPerson::addActiveAddVisualisation(), buildColorRainbow(), and GUIVehicle::drawOutsideNetwork().
addDecals()
void GUISUMOAbstractView::addDecals (const std::vector< Decal > & decals)
add decals
Definition at line 215 of file GUISUMOAbstractView.cpp.
References myDecals.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
addSnapshot()
void GUISUMOAbstractView::addSnapshot (SUMOTime time, const std::string & file)
Sets the snapshot time to file map.
Parameters
[in] snaps The snapshots to take at certain times
Definition at line 825 of file GUISUMOAbstractView.cpp.
References MFXMutex::lock(), myApplicationSnapshots, myApplicationSnapshotsLock, mySnapshots, mySnapshotsLock, and MFXMutex::unlock().
Referenced by buildViewToolBars(), TraCIServerAPI_GUI::processSet(), and GUISettingsHandler::setSnapshots().
applyGLTransform()
void GUISUMOAbstractView::applyGLTransform (bool fixRatio = true) protected
applies gl-transformations to fit the Boundary given by myChanger onto the canvas. If fixRatio is true, this boundary will be enlarged to prevent anisotropic stretching. (this should be set to false when doing selections)
Definition at line 1319 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), GLO_MAX, myChanger, Boundary::xmin(), and Boundary::ymin().
Referenced by getObjectsInBoundary(), makeSnapshot(), and paintGL().
buildColorRainbow()
virtual void GUISUMOAbstractView::buildColorRainbow (GUIColorScheme & , int , GUIGlObjectType) inline virtual
recalibrate color scheme according to the current value range
Reimplemented in GNEViewNet, and GUIViewTraffic.
Definition at line 213 of file GUISUMOAbstractView.h.
References addAdditionalGLVisualisation(), destroyPopup(), getGridHeight(), getGridWidth(), getPopupPosition(), getTrackedID(), isAdditionalGLVisualisationEnabled(), onGamingClick(), removeAdditionalGLVisualisation(), startTrack(), and stopTrack().
Referenced by GUIDialog_ViewSettings::onCmdColorChange().
buildViewToolBars()
virtual void GUISUMOAbstractView::buildViewToolBars (GUIGlChildWindow &) inline virtual
builds the view toolbars
Reimplemented in GNEViewNet, and GUIViewTraffic.
Definition at line 90 of file GUISUMOAbstractView.h.
References addSnapshot(), centerTo(), copyViewportTo(), getChanger(), getVisibleBoundary(), isInEditMode(), m2p(), makeCurrent(), makeSnapshot(), onConfigure(), onDoubleClicked(), onKeyPress(), onKeyRelease(), onLeftBtnPress(), onLeftBtnRelease(), onMiddleBtnPress(), onMiddleBtnRelease(), onMouseLeft(), onMouseMove(), onMouseWheel(), onPaint(), onRightBtnPress(), onRightBtnRelease(), openObjectDialog(), p2m(), recenterView(), saveFrame(), setViewportFromTo(), setWindowCursorPosition(), and updateToolTip().
Referenced by GUISUMOViewParent::init().
centerTo() [1/2]
void GUISUMOAbstractView::centerTo (GUIGlID id, bool applyZoom, double zoomDist = 20) virtual
centers to the chosen artifact
Parameters
[in] id The id of the artifact to center to
[in] applyZoom Whether to zoom in
[in] zoomDist The distance in m to use for the zoom, values < 0 means: use the centeringBoundary
Note
caller is responsible for calling update
Definition at line 560 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::centerTo(), Boundary::getCenter(), GUIGlObject::getCenteringBoundary(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, myChanger, GUIPerspectiveChanger::setViewport(), GUIGlObjectStorage::unblockObject(), and updatePositionInformation().
Referenced by GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), buildViewToolBars(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), paintGL(), TraCIServerAPI_GUI::processSet(), and GUIGlChildWindow::setView().
centerTo() [2/2]
void GUISUMOAbstractView::centerTo (const Boundary & bound)
centers to the chosen artifact
Definition at line 577 of file GUISUMOAbstractView.cpp.
References myChanger, and GUIPerspectiveChanger::setViewport().
checkGDALImage()
FXImage * GUISUMOAbstractView::checkGDALImage (Decal & d) protected
check whether we can read image data or position with gdal
Definition at line 1154 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::Decal::filename, getGridHeight(), getGridWidth(), GeoConvHelper::getProcessing(), GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::width, WRITE_MESSAGE, WRITE_WARNING, Position::x(), GeoConvHelper::x2cartesian(), and Position::y().
Referenced by drawDecals().
checkSnapshots()
void GUISUMOAbstractView::checkSnapshots () virtual
Checks whether it is time for a snapshot.
Reimplemented in GUIViewTraffic.
Definition at line 991 of file GUISUMOAbstractView.cpp.
References DELTA_T, getCurrentTimeStep(), joinToString(), MFXMutex::lock(), makeSnapshot(), myApplicationSnapshots, myApplicationSnapshotsLock, mySnapshots, mySnapshotsLock, toString(), MFXMutex::unlock(), and WRITE_WARNING.
Referenced by GUIViewTraffic::checkSnapshots(), endSnapshot(), onConfigure(), and GUISUMOViewParent::onSimStep().
copyViewportTo()
void GUISUMOAbstractView::copyViewportTo (GUISUMOAbstractView * view) virtual
copy the viewport to the given view
Definition at line 1077 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), myChanger, and setViewportFromTo().
Referenced by buildViewToolBars(), and GUIApplicationWindow::openNewView().
destroyPopup()
void GUISUMOAbstractView::destroyPopup ()
destoys the popup
Definition at line 641 of file GUISUMOAbstractView.cpp.
References myPopup, myPopupPosition, and Position::set().
Referenced by buildColorRainbow(), GNEViewNet::onCmdClearConnections(), GNEViewNet::onCmdEditConnectionShape(), GNEViewNet::onCmdEditCrossingShape(), GNEViewNet::onCmdEditJunctionShape(), GNEViewNet::onCmdReplaceJunction(), GNEViewNet::onCmdResetConnections(), GNEInternalLane::onDefault(), onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onRightBtnPress(), onRightBtnRelease(), and GNEViewNet::processClick().
displayLegend()
void GUISUMOAbstractView::displayLegend () protected
a line with ticks, and the length information.
Definition at line 479 of file GUISUMOAbstractView.cpp.
References RGBColor::BLACK, GLHelper::drawText(), FONS_ALIGN_LEFT, and m2p().
Referenced by makeSnapshot(), and paintGL().
doInit()
void GUISUMOAbstractView::doInit () protected virtual
doInit
Reimplemented in GNEViewNet.
Definition at line 248 of file GUISUMOAbstractView.cpp.
Referenced by onConfigure().
doPaintGL()
int GUISUMOAbstractView::doPaintGL (int , const Boundary &) protected virtual
paint GL
Reimplemented in GNEViewNet, and GUIViewTraffic.
Definition at line 242 of file GUISUMOAbstractView.cpp.
Referenced by getObjectsInBoundary(), makeSnapshot(), and paintGL().
drawDecals()
void GUISUMOAbstractView::drawDecals () protected
Draws the stored decals.
Definition at line 1233 of file GUISUMOAbstractView.cpp.
References GUITexturesHelper::add(), GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, checkGDALImage(), GUITexturesHelper::drawTexturedBox(), GUISUMOAbstractView::Decal::filename, GUITexturesHelper::getMaxTextureSize(), GUISUMOAbstractView::Decal::glID, GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::image, GUISUMOAbstractView::Decal::initialised, GUISUMOAbstractView::Decal::layer, MFXImageHelper::loadImage(), MFXMutex::lock(), myDecals, myDecalsLock, p2m(), GUISUMOAbstractView::Decal::rot, MFXImageHelper::scalePower2(), screenPos2NetPos(), GUISUMOAbstractView::Decal::screenRelative, GUISUMOAbstractView::Decal::skip2D, MFXMutex::unlock(), GUISUMOAbstractView::Decal::width, WRITE_ERROR, Position::x(), and Position::y().
Referenced by GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), and makeSnapshot().
endSnapshot()
virtual void GUISUMOAbstractView::endSnapshot () inline virtual
Ends a video snapshot.
Reimplemented in GUIViewTraffic.
Definition at line 185 of file GUISUMOAbstractView.h.
References checkSnapshots(), getCurrentTimeStep(), getViewportEditor(), getVisualisationSettings(), setColorScheme(), showToolTips(), showViewportEditor(), and showViewschemeEditor().
Referenced by GUISUMOViewParent::onCmdMakeSnapshot().
getChanger()
GUIPerspectiveChanger & GUISUMOAbstractView::getChanger () const
get changer
Definition at line 171 of file GUISUMOAbstractView.cpp.
References myChanger.
Referenced by GUISettingsHandler::applyViewport(), buildViewToolBars(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), and GUIDialog_EditViewport::setValues().
getColoringSchemesCombo()
FXComboBox & GUISUMOAbstractView::getColoringSchemesCombo ()
get coloring schemes combo
Definition at line 1148 of file GUISUMOAbstractView.cpp.
References GUIGlChildWindow::getColoringSchemesCombo(), and myParent.
Referenced by GUISettingsHandler::addSettings(), GUIDialog_ViewSettings::onCmdColorChange(), and GUIDialog_ViewSettings::onCmdSaveSetting().
getCurrentTimeStep()
SUMOTime GUISUMOAbstractView::getCurrentTimeStep () const virtual
get the current simulation time
Reimplemented in GUIViewTraffic.
Definition at line 1029 of file GUISUMOAbstractView.cpp.
Referenced by checkSnapshots(), and endSnapshot().
getDelay()
double GUISUMOAbstractView::getDelay () const
Returns the delay of the parent application.
Definition at line 1337 of file GUISUMOAbstractView.cpp.
References GUIMainWindow::getDelay(), and myApp.
Referenced by GUIDialog_ViewSettings::onCmdExportSetting().
getGridHeight()
double GUISUMOAbstractView::getGridHeight () const
get grid Height
Definition at line 1121 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), and myGrid.
Referenced by buildColorRainbow(), checkGDALImage(), and GUIDialog_ViewSettings::onCmdEditTable().
getGridWidth()
double GUISUMOAbstractView::getGridWidth () const
get grid width
Definition at line 1115 of file GUISUMOAbstractView.cpp.
References Boundary::getWidth(), and myGrid.
Referenced by buildColorRainbow(), checkGDALImage(), and GUIDialog_ViewSettings::onCmdEditTable().
getObjectAtPosition()
GUIGlID GUISUMOAbstractView::getObjectAtPosition (Position pos) protected
returns the id of the object at position using GL_SELECT
Definition at line 311 of file GUISUMOAbstractView.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), getObjectsInBoundary(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_LANE, GLO_POI, GLO_POLYGON, Boundary::grow(), GUIGlObjectStorage::unblockObject(), and GUIVisualizationSettings::UseMesoSim.
Referenced by GNEViewNet::getAdditionalAtPopupPosition(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), getObjectUnderCursor(), GNEViewNet::getPOIAtPopupPosition(), GNEViewNet::getPOILaneAtPopupPosition(), and GNEViewNet::getPolygonAtPopupPosition().
getObjectsAtPosition()
std::vector< GUIGlID > GUISUMOAbstractView::getObjectsAtPosition (Position pos, double radius) protected
returns the ids of the object at position within the given (rectangular) radius using GL_SELECT
Definition at line 356 of file GUISUMOAbstractView.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), getObjectsInBoundary(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, Boundary::grow(), and GUIGlObjectStorage::unblockObject().
Referenced by GNEViewNet::getEdgesAtPopupPosition().
getObjectsInBoundary()
std::vector< GUIGlID > GUISUMOAbstractView::getObjectsInBoundary (const Boundary & bound) protected
returns the ids of all objects in the given boundary
Definition at line 384 of file GUISUMOAbstractView.cpp.
References applyGLTransform(), doPaintGL(), GUIVisualizationSettings::drawForSelecting, GUIPerspectiveChanger::getViewport(), myApp, myChanger, myVisualizationSettings, GUIMainWindow::setStatusBarText(), GUIPerspectiveChanger::setViewport(), and toString().
Referenced by getObjectAtPosition(), getObjectsAtPosition(), GNEViewNet::mergeJunctions(), GNEViewNet::onCmdTransformPOI(), and GNEViewNet::onLeftBtnRelease().
getObjectUnderCursor()
GUIGlID GUISUMOAbstractView::getObjectUnderCursor () protected
returns the id of the object under the cursor using GL_SELECT
Definition at line 305 of file GUISUMOAbstractView.cpp.
References getObjectAtPosition(), and getPositionInformation().
Referenced by GUIViewTraffic::getLaneUnderCursor(), GNEViewNet::onLeftBtnPress(), onLeftBtnPress(), GNEViewNet::onMouseMove(), openObjectDialog(), and paintGL().
getPopupPosition()
const Position & GUISUMOAbstractView::getPopupPosition () const
get position of current popup
Definition at line 636 of file GUISUMOAbstractView.cpp.
References myPopupPosition.
Referenced by buildColorRainbow(), GNEViewNet::getAdditionalAtPopupPosition(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GNEViewNet::getPOIAtPopupPosition(), GNEViewNet::getPOILaneAtPopupPosition(), GNEViewNet::getPolygonAtPopupPosition(), GNEViewNet::onCmdDeleteGeometryPoint(), GNEViewNet::onCmdResetEdgeEndpoint(), GNEViewNet::onCmdSetEdgeEndpoint(), GNEViewNet::onCmdSetFirstGeometryPoint(), GNEViewNet::onCmdSplitEdge(), and GNEViewNet::onCmdSplitEdgeBidi().
getPositionInformation()
Position GUISUMOAbstractView::getPositionInformation () const
Returns the cursor's x/y position within the network.
Definition at line 186 of file GUISUMOAbstractView.cpp.
References myWindowCursorPositionX, myWindowCursorPositionY, and screenPos2NetPos().
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::doPaintGL(), GNEPoly::drawGL(), getObjectUnderCursor(), GUIEdge::getParameterWindow(), GNELane::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GUILane::getPopUpMenu(), GNEAdditional::getPopUpMenu(), GUIDanielPerspectiveChanger::onKeyPress(), GNEViewNet::onLeftBtnPress(), onLeftBtnRelease(), GNEViewNet::onMouseMove(), GUIDanielPerspectiveChanger::onMouseWheel(), GUIDanielPerspectiveChanger::onRightBtnPress(), openObjectDialog(), GNEDeleteFrame::removeAttributeCarrier(), showToolTipFor(), and updatePositionInformation().
getTrackedID()
GUIGlID GUISUMOAbstractView::getTrackedID () const virtual
get tracked id
Reimplemented in GUIViewTraffic.
Definition at line 1137 of file GUISUMOAbstractView.cpp.
References GUIGlObject::INVALID_ID.
Referenced by buildColorRainbow(), GUIPerson::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), paintGL(), and TraCIServerAPI_GUI::processSet().
getViewportEditor()
GUIDialog_EditViewport * GUISUMOAbstractView::getViewportEditor ()
get the viewport and create it on first access
Definition at line 1050 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), myChanger, myViewportChooser, and GUIDialog_EditViewport::setValues().
Referenced by endSnapshot(), GUIDialog_ViewSettings::onCmdExportSetting(), and showViewportEditor().
getVisibleBoundary()
Boundary GUISUMOAbstractView::getVisibleBoundary () const
get visible boundary
Definition at line 253 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), and myChanger.
Referenced by buildViewToolBars(), and TraCIServerAPI_GUI::processGet().
getVisualisationSettings() [1/2]
GUIVisualizationSettings * GUISUMOAbstractView::getVisualisationSettings () const
get visualitation settings
Definition at line 1097 of file GUISUMOAbstractView.cpp.
References myVisualizationSettings.
Referenced by GNEEdge::commitShapeChange(), endSnapshot(), GNELane::getPopUpMenu(), GUIApplicationWindow::onCmdEditChosen(), and TraCIServerAPI_GUI::processGet().
getVisualisationSettings() [2/2]
GUIVisualizationSettings * GUISUMOAbstractView::getVisualisationSettings ()
get visualisation settings
Definition at line 221 of file GUISUMOAbstractView.cpp.
References myVisualizationSettings.
isAdditionalGLVisualisationEnabled()
bool GUISUMOAbstractView::isAdditionalGLVisualisationEnabled (GUIGlObject *const which) const
Check if an object is added in the additional GL visualitation.
Parameters
[in] which The object to check
See also
GUIGlObject::drawGLAdditional
Definition at line 1309 of file GUISUMOAbstractView.cpp.
References myAdditionallyDrawn.
Referenced by buildColorRainbow().
isInEditMode()
bool GUISUMOAbstractView::isInEditMode ()
returns true, if the edit button was pressed
Definition at line 165 of file GUISUMOAbstractView.cpp.
References myInEditMode.
Referenced by buildViewToolBars().
m2p()
double GUISUMOAbstractView::m2p (double meter) const
meter-to-pixels conversion method
Definition at line 542 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), and myChanger.
Referenced by buildViewToolBars(), displayLegend(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), and makeSnapshot().
makeCurrent()
FXbool GUISUMOAbstractView::makeCurrent ()
A reimplementation due to some internal reasons.
Definition at line 598 of file GUISUMOAbstractView.cpp.
Referenced by buildViewToolBars(), GNEViewNet::getAdditionalAtPopupPosition(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUIViewTraffic::getLaneUnderCursor(), GNEViewNet::getPOIAtPopupPosition(), GNEViewNet::getPOILaneAtPopupPosition(), GNEViewNet::getPolygonAtPopupPosition(), makeSnapshot(), GNEViewNet::mergeJunctions(), onConfigure(), GNEViewNet::onLeftBtnPress(), onLeftBtnPress(), GNEViewNet::onLeftBtnRelease(), GNEViewNet::onMouseMove(), onPaint(), and openObjectDialog().
makeSnapshot()
std::string GUISUMOAbstractView::makeSnapshot (const std::string & destFile)
Takes a snapshots and writes it into the given file.
The format to use is determined from the extension. If compiled with ffmpeg and a video format is requested it will instantiate a video encoder.
Parameters
[in] destFile The name of the file to write the snapshot into
Returns
The error message, if an error occcured; "" otherwise
Definition at line 840 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), applyGLTransform(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), displayLegend(), GUIVisualizationSettings::dither, doPaintGL(), drawDecals(), GUIPerspectiveChanger::getViewport(), RGBColor::green(), m2p(), makeCurrent(), myChanger, myGrid, myUseToolTips, myVisualizationSettings, paintGLGrid(), RGBColor::red(), saveFrame(), MFXImageHelper::saveImage(), GUIVisualizationSettings::scale, SUMORTree::Search(), GUIVisualizationSettings::showGrid, GUIVisualizationSettings::showSizeLegend, FXSingleEventThread::sleep(), SUMO_const_laneWidth, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by buildViewToolBars(), GUIViewTraffic::checkSnapshots(), checkSnapshots(), GUIApplicationWindow::handleEvent_Screenshot(), GUISUMOViewParent::onCmdMakeSnapshot(), and GNEViewParent::onCmdMakeSnapshot().
onConfigure()
long GUISUMOAbstractView::onConfigure (FXObject * , FXSelector , void *) virtual
mouse functions
Definition at line 605 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), checkSnapshots(), doInit(), RGBColor::green(), makeCurrent(), myAmInitialised, myVisualizationSettings, and RGBColor::red().
Referenced by buildViewToolBars().
onDoubleClicked()
long GUISUMOAbstractView::onDoubleClicked (FXObject * , FXSelector , void *) virtual
Definition at line 727 of file GUISUMOAbstractView.cpp.
Referenced by buildViewToolBars().
onGamingClick()
void GUISUMOAbstractView::onGamingClick (Position) virtual
on gaming click
Reimplemented in GUIViewTraffic.
Definition at line 1143 of file GUISUMOAbstractView.cpp.
Referenced by buildColorRainbow(), and onLeftBtnRelease().
onKeyPress()
long GUISUMOAbstractView::onKeyPress (FXObject * o, FXSelector sel, void * data) virtual
keyboard functions
Reimplemented in GNEViewNet.
Definition at line 802 of file GUISUMOAbstractView.cpp.
References myChanger, myPopup, and GUIPerspectiveChanger::onKeyPress().
Referenced by buildViewToolBars(), GUISUMOViewParent::onKeyPress(), GNEViewNet::onKeyPress(), and GNEViewParent::onKeyPress().
onKeyRelease()
long GUISUMOAbstractView::onKeyRelease (FXObject * o, FXSelector sel, void * data) virtual
Reimplemented in GNEViewNet.
Definition at line 813 of file GUISUMOAbstractView.cpp.
References myChanger, myPopup, and GUIPerspectiveChanger::onKeyRelease().
Referenced by buildViewToolBars(), GUISUMOViewParent::onKeyRelease(), GNEViewNet::onKeyRelease(), and GNEViewParent::onKeyRelease().
onLeftBtnPress()
long GUISUMOAbstractView::onLeftBtnPress (FXObject * , FXSelector , void * data) virtual
Reimplemented in GNEViewNet.
Definition at line 651 of file GUISUMOAbstractView.cpp.
References destroyPopup(), getObjectUnderCursor(), gSelected, makeCurrent(), myChanger, GUIPerspectiveChanger::onLeftBtnPress(), and GUISelectedStorage::toggleSelection().
Referenced by buildViewToolBars().
onLeftBtnRelease()
long GUISUMOAbstractView::onLeftBtnRelease (FXObject * , FXSelector , void * data) virtual
Reimplemented in GNEViewNet.
Definition at line 682 of file GUISUMOAbstractView.cpp.
References destroyPopup(), getPositionInformation(), GUIMainWindow::isGaming(), myApp, myChanger, onGamingClick(), and GUIPerspectiveChanger::onLeftBtnRelease().
Referenced by buildViewToolBars(), and GNEViewNet::onLeftBtnRelease().
onMiddleBtnPress()
long GUISUMOAbstractView::onMiddleBtnPress (FXObject * , FXSelector , void *) virtual
Definition at line 694 of file GUISUMOAbstractView.cpp.
Referenced by buildViewToolBars().
onMiddleBtnRelease()
long GUISUMOAbstractView::onMiddleBtnRelease (FXObject * , FXSelector , void *) virtual
Definition at line 700 of file GUISUMOAbstractView.cpp.
Referenced by buildViewToolBars().
onMouseLeft()
long GUISUMOAbstractView::onMouseLeft (FXObject * , FXSelector , void *) virtual
Definition at line 762 of file GUISUMOAbstractView.cpp.
Referenced by buildViewToolBars().
onMouseMove()
long GUISUMOAbstractView::onMouseMove (FXObject * , FXSelector , void * data) virtual
Reimplemented in GNEViewNet.
Definition at line 743 of file GUISUMOAbstractView.cpp.
References destroyPopup(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), GUIDialog_EditViewport::haveGrabbed(), myChanger, myPopup, myViewportChooser, GUIPerspectiveChanger::onMouseMove(), GUIDialog_EditViewport::setValues(), and updatePositionInformation().
Referenced by buildViewToolBars(), GNEViewNet::onMouseMove(), and onRightBtnRelease().
onMouseWheel()
long GUISUMOAbstractView::onMouseWheel (FXObject * , FXSelector , void * data) virtual
Definition at line 733 of file GUISUMOAbstractView.cpp.
References GUIMainWindow::isGaming(), myApp, myChanger, GUIPerspectiveChanger::onMouseWheel(), and updatePositionInformation().
Referenced by buildViewToolBars().
onPaint()
long GUISUMOAbstractView::onPaint (FXObject * , FXSelector , void *) virtual
Definition at line 623 of file GUISUMOAbstractView.cpp.
References makeCurrent(), myAmInitialised, and paintGL().
Referenced by buildViewToolBars(), and GNEViewNet::updateModeSpecificControls().
onRightBtnPress()
long GUISUMOAbstractView::onRightBtnPress (FXObject * , FXSelector , void * data) virtual
Reimplemented in GNEViewNet.
Definition at line 706 of file GUISUMOAbstractView.cpp.
References destroyPopup(), myChanger, and GUIPerspectiveChanger::onRightBtnPress().
Referenced by buildViewToolBars(), and GNEViewNet::onRightBtnPress().
onRightBtnRelease()
long GUISUMOAbstractView::onRightBtnRelease (FXObject * o, FXSelector sel, void * data) virtual
Reimplemented in GNEViewNet.
Definition at line 715 of file GUISUMOAbstractView.cpp.
References destroyPopup(), GUIMainWindow::isGaming(), myApp, myChanger, onMouseMove(), GUIPerspectiveChanger::onRightBtnRelease(), and openObjectDialog().
Referenced by buildViewToolBars(), and GNEViewNet::onRightBtnRelease().
openObjectDialog()
void GUISUMOAbstractView::openObjectDialog () virtual
Definition at line 768 of file GUISUMOAbstractView.cpp.
References GUIGlObjectStorage::getNetObject(), GUIGlObjectStorage::getObjectBlocking(), getObjectUnderCursor(), GUIGlObject::getPopUpMenu(), getPositionInformation(), GUIGlObjectStorage::gIDStorage, makeCurrent(), myAmInitialised, myApp, myChanger, myPopup, myPopupPosition, GUIPerspectiveChanger::onRightBtnRelease(), and GUIGlObjectStorage::unblockObject().
Referenced by buildViewToolBars(), and onRightBtnRelease().
p2m()
double GUISUMOAbstractView::p2m (double pixel) const
pixels-to-meters conversion method
Definition at line 548 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), and myChanger.
Referenced by buildViewToolBars(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), GNEViewNet::doPaintGL(), drawDecals(), GUIDanielPerspectiveChanger::move(), and showToolTipFor().
paintGL()
void GUISUMOAbstractView::paintGL () protected
performs the painting of the simulation
Definition at line 259 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), applyGLTransform(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), centerTo(), displayLegend(), GUIVisualizationSettings::dither, doPaintGL(), getObjectUnderCursor(), getTrackedID(), GUIPerspectiveChanger::getViewport(), RGBColor::green(), GUIGlObject::INVALID_ID, myChanger, myUseToolTips, myVisualizationSettings, RGBColor::red(), GUIVisualizationSettings::showSizeLegend, and showToolTipFor().
Referenced by onPaint().
paintGLGrid()
void GUISUMOAbstractView::paintGLGrid () protected
paints a grid
Definition at line 437 of file GUISUMOAbstractView.cpp.
References GUIVisualizationSettings::addSize, GUIVisualizationSizeSettings::getExaggeration(), GUIPerspectiveChanger::getViewport(), GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, myChanger, myVisualizationSettings, GUIVisualizationSettings::scale, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), and makeSnapshot().
recenterView()
void GUISUMOAbstractView::recenterView () virtual
recenters the view
Definition at line 554 of file GUISUMOAbstractView.cpp.
References myChanger, myGrid, and GUIPerspectiveChanger::setViewport().
Referenced by buildViewToolBars(), GUIGlChildWindow::onCmdRecenterView(), GUIDanielPerspectiveChanger::onKeyPress(), and GUICompleteSchemeStorage::setViewport().
remove() [1/2]
void GUISUMOAbstractView::remove (GUIDialog_EditViewport *)
remove viewport
Definition at line 1103 of file GUISUMOAbstractView.cpp.
References myViewportChooser.
Referenced by GUIDialog_ViewSettings::~GUIDialog_ViewSettings().
remove() [2/2]
void GUISUMOAbstractView::remove (GUIDialog_ViewSettings *)
remove view settings
Definition at line 1109 of file GUISUMOAbstractView.cpp.
References myVisualizationChanger.
removeAdditionalGLVisualisation()
bool GUISUMOAbstractView::removeAdditionalGLVisualisation (const GUIGlObject *const which)
Removes an object from the list of objects that show additional things.
Parameters
[in] which The object to remoe
Returns
True if the object was known, false otherwise
See also
GUIGlObject::drawGLAdditional
Definition at line 1293 of file GUISUMOAbstractView.cpp.
References myAdditionallyDrawn.
Referenced by buildColorRainbow(), GUIVehicle::drawOutsideNetwork(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIPerson::removeActiveAddVisualisation().
saveFrame()
void GUISUMOAbstractView::saveFrame (const std::string & destFile, FXColor * buf) virtual
Adds a frame to a video snapshot which will be initialized if neccessary.
Reimplemented in GUIViewTraffic.
Definition at line 984 of file GUISUMOAbstractView.cpp.
References UNUSED_PARAMETER.
Referenced by buildViewToolBars(), and makeSnapshot().
screenPos2NetPos()
Position GUISUMOAbstractView::screenPos2NetPos (int x, int y) const
Translate screen position to network position.
Definition at line 205 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), myChanger, Boundary::xmin(), and Boundary::ymin().
Referenced by GNEViewNet::doPaintGL(), drawDecals(), and getPositionInformation().
setApplicationSnapshots()
void GUISUMOAbstractView::setApplicationSnapshots (std::set< SUMOTime > * snapshots, FXMutex * lock) inline
add snapshot synchronization
Definition at line 271 of file GUISUMOAbstractView.h.
References myApplicationSnapshots, and myApplicationSnapshotsLock.
Referenced by GUIApplicationWindow::openNewView().
setColorScheme()
bool GUISUMOAbstractView::setColorScheme (const std::string &) virtual
set color scheme
Reimplemented in GNEViewNet, and GUIViewTraffic.
Definition at line 1091 of file GUISUMOAbstractView.cpp.
Referenced by GUISettingsHandler::addSettings(), endSnapshot(), GUIGlChildWindow::onCmdChangeColorScheme(), GUIDialog_ViewSettings::onCmdColorChange(), GUIDialog_ViewSettings::onCmdNameChange(), GUIDialog_ViewSettings::onCmdSaveSetting(), and TraCIServerAPI_GUI::processSet().
setDelay()
void GUISUMOAbstractView::setDelay (double delay)
Sets the delay of the parent application.
Definition at line 1343 of file GUISUMOAbstractView.cpp.
References myApp, and GUIMainWindow::setDelay().
Referenced by GUIDialog_ViewSettings::loadSettings().
setViewportFromTo()
void GUISUMOAbstractView::setViewportFromTo (const Position & lookFrom, const Position & lookAt) virtual
applies the given viewport settings
Definition at line 1070 of file GUISUMOAbstractView.cpp.
References myChanger, GUIPerspectiveChanger::setViewportFrom(), Position::x(), Position::y(), and Position::z().
Referenced by GUISettingsHandler::applyViewport(), buildViewToolBars(), copyViewportTo(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIDialog_EditViewport::onCmdCancel(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), TraCIServerAPI_GUI::processSet(), and GUICompleteSchemeStorage::setViewport().
setWindowCursorPosition()
void GUISUMOAbstractView::setWindowCursorPosition (FXint x, FXint y)
Returns the information whether rotation is allowd.
Note
disabled Returns the gl-id of the object under the given coordinates
Definition at line 591 of file GUISUMOAbstractView.cpp.
References myMouseHotspotX, myMouseHotspotY, myWindowCursorPositionX, and myWindowCursorPositionY.
Referenced by buildViewToolBars(), and GUIDanielPerspectiveChanger::onMouseMove().
showToolTipFor()
void GUISUMOAbstractView::showToolTipFor (const GUIGlID id) protected
invokes the tooltip for the given object
Definition at line 423 of file GUISUMOAbstractView.cpp.
References Position::add(), RGBColor::BLACK, GLHelper::drawTextBox(), GUIGlObject::getFullName(), GUIGlObjectStorage::getObjectBlocking(), getPositionInformation(), GUIGlObjectStorage::gIDStorage, GLO_MAX, p2m(), and GUIGlObjectStorage::unblockObject().
Referenced by paintGL().
showToolTips()
void GUISUMOAbstractView::showToolTips (bool val)
show tool tips
Definition at line 1085 of file GUISUMOAbstractView.cpp.
References myUseToolTips.
Referenced by endSnapshot(), and GUIGlChildWindow::onCmdShowToolTips().
showViewportEditor()
void GUISUMOAbstractView::showViewportEditor () virtual
show viewport editor
Definition at line 1061 of file GUISUMOAbstractView.cpp.
References getViewportEditor(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), Position::INVALID, myChanger, myViewportChooser, GUIDialog_EditViewport::setOldValues(), and GUIDialog_EditViewport::show().
Referenced by endSnapshot(), GUIGlChildWindow::onCmdEditViewport(), and GNEApplicationWindow::onCmdEditViewport().
showViewschemeEditor()
void GUISUMOAbstractView::showViewschemeEditor ()
show viewsscheme editor
Definition at line 1035 of file GUISUMOAbstractView.cpp.
References myDecals, myDecalsLock, myVisualizationChanger, myVisualizationSettings, GUIDialog_ViewSettings::setCurrent(), and GUIDialog_ViewSettings::show().
Referenced by endSnapshot(), GUIGlChildWindow::onCmdEditViewScheme(), and GUIDanielPerspectiveChanger::onKeyPress().
snapToActiveGrid()
Position GUISUMOAbstractView::snapToActiveGrid (const Position & pos) const
Returns a position that is mapped to the closest grid point if the grid is active.
Definition at line 192 of file GUISUMOAbstractView.cpp.
References GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, myVisualizationSettings, Position::setx(), Position::sety(), GUIVisualizationSettings::showGrid, Position::x(), and Position::y().
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::doPaintGL(), GNEViewNet::onLeftBtnPress(), and GNEViewNet::onMouseMove().
startTrack()
void GUISUMOAbstractView::startTrack (int) virtual
star track
Reimplemented in GUIViewTraffic.
Definition at line 1127 of file GUISUMOAbstractView.cpp.
Referenced by buildColorRainbow(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), and TraCIServerAPI_GUI::processSet().
stopTrack()
void GUISUMOAbstractView::stopTrack () virtual
stop track
Reimplemented in GUIViewTraffic.
Definition at line 1132 of file GUISUMOAbstractView.cpp.
Referenced by buildColorRainbow(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), and TraCIServerAPI_GUI::processSet().
updatePositionInformation()
void GUISUMOAbstractView::updatePositionInformation () const protected
update position information
Definition at line 227 of file GUISUMOAbstractView.cpp.
References GeoConvHelper::cartesian2geo(), GUIMainWindow::getCartesianLabel(), GeoConvHelper::getFinal(), GUIMainWindow::getGeoLabel(), getPositionInformation(), gPrecisionGeo, myApp, toString(), Position::x(), and Position::y().
Referenced by centerTo(), onMouseMove(), and onMouseWheel().
updateToolTip()
void GUISUMOAbstractView::updateToolTip ()
A method that updates the tooltip.
Definition at line 177 of file GUISUMOAbstractView.cpp.
References myUseToolTips.
Referenced by buildViewToolBars(), GUIDanielPerspectiveChanger::onKeyPress(), GUIDanielPerspectiveChanger::onMouseMove(), and GUIDanielPerspectiveChanger::onMouseWheel().
Field Documentation
myAdditionallyDrawn
std::map<const GUIGlObject*, int> GUISUMOAbstractView::myAdditionallyDrawn protected
List of objects for which GUIGlObject::drawGLAdditional is called.
Definition at line 452 of file GUISUMOAbstractView.h.
Referenced by addAdditionalGLVisualisation(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), isAdditionalGLVisualisationEnabled(), and removeAdditionalGLVisualisation().
myAmInitialised
bool GUISUMOAbstractView::myAmInitialised protected
Internal information whether doInit() was called.
Definition at line 420 of file GUISUMOAbstractView.h.
Referenced by onConfigure(), onPaint(), and openObjectDialog().
myApp
GUIMainWindow* GUISUMOAbstractView::myApp protected
The application.
Definition at line 390 of file GUISUMOAbstractView.h.
Referenced by GNEViewNet::doPaintGL(), getDelay(), getObjectsInBoundary(), onLeftBtnRelease(), onMouseWheel(), onRightBtnRelease(), openObjectDialog(), GUIViewTraffic::saveFrame(), GUIViewTraffic::setColorScheme(), setDelay(), GNEViewNet::setEditMode(), GNEViewNet::setStatusBarText(), and updatePositionInformation().
myApplicationSnapshots
std::set<SUMOTime>* GUISUMOAbstractView::myApplicationSnapshots protected
Definition at line 442 of file GUISUMOAbstractView.h.
Referenced by addSnapshot(), checkSnapshots(), and setApplicationSnapshots().
myApplicationSnapshotsLock
FXMutex* GUISUMOAbstractView::myApplicationSnapshotsLock protected
Definition at line 446 of file GUISUMOAbstractView.h.
Referenced by addSnapshot(), checkSnapshots(), and setApplicationSnapshots().
myChanger
GUIPerspectiveChanger* GUISUMOAbstractView::myChanger protected
The perspective changer.
Definition at line 399 of file GUISUMOAbstractView.h.
Referenced by applyGLTransform(), centerTo(), copyViewportTo(), getChanger(), getObjectsInBoundary(), getViewportEditor(), getVisibleBoundary(), m2p(), makeSnapshot(), onKeyPress(), onKeyRelease(), onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onMouseWheel(), onRightBtnPress(), onRightBtnRelease(), openObjectDialog(), p2m(), paintGL(), paintGLGrid(), GNEViewNet::processClick(), recenterView(), screenPos2NetPos(), setViewportFromTo(), showViewportEditor(), and ~GUISUMOAbstractView().
myDecals
std::vector<Decal> GUISUMOAbstractView::myDecals protected
Definition at line 434 of file GUISUMOAbstractView.h.
Referenced by addDecals(), drawDecals(), showViewschemeEditor(), and ~GUISUMOAbstractView().
myDecalsLock
MFXMutex GUISUMOAbstractView::myDecalsLock protected
The mutex to use before accessing the decals list in order to avoid thread conficts.
Definition at line 437 of file GUISUMOAbstractView.h.
Referenced by drawDecals(), and showViewschemeEditor().
myGrid
SUMORTree* GUISUMOAbstractView::myGrid protected
The visualization speed-up.
Definition at line 396 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), getGridHeight(), getGridWidth(), makeSnapshot(), and recenterView().
myInEditMode
bool GUISUMOAbstractView::myInEditMode protected
Information whether too-tip informations shall be generated.
Definition at line 402 of file GUISUMOAbstractView.h.
Referenced by isInEditMode().
myMouseHotspotX
int GUISUMOAbstractView::myMouseHotspotX protected
Offset to the mouse-hotspot from the mouse position.
Definition at line 405 of file GUISUMOAbstractView.h.
Referenced by setWindowCursorPosition().
myMouseHotspotY
int GUISUMOAbstractView::myMouseHotspotY protected
Definition at line 405 of file GUISUMOAbstractView.h.
Referenced by setWindowCursorPosition().
myParent
GUIGlChildWindow* GUISUMOAbstractView::myParent protected
The parent window.
Definition at line 393 of file GUISUMOAbstractView.h.
Referenced by getColoringSchemesCombo().
myPolyDrawLock
MFXMutex GUISUMOAbstractView::myPolyDrawLock mutable protected
poly draw lock
Definition at line 449 of file GUISUMOAbstractView.h.
myPopup
GUIGLObjectPopupMenu* GUISUMOAbstractView::myPopup protected
The current popup-menu.
Definition at line 408 of file GUISUMOAbstractView.h.
Referenced by destroyPopup(), onKeyPress(), onKeyRelease(), onMouseMove(), openObjectDialog(), and ~GUISUMOAbstractView().
myPopupPosition
Position GUISUMOAbstractView::myPopupPosition protected
The current popup-menu position.
Definition at line 411 of file GUISUMOAbstractView.h.
Referenced by destroyPopup(), getPopupPosition(), and openObjectDialog().
mySnapshots
std::map<SUMOTime, std::vector<std::string> > GUISUMOAbstractView::mySnapshots protected
Snapshots.
Definition at line 441 of file GUISUMOAbstractView.h.
Referenced by addSnapshot(), and checkSnapshots().
mySnapshotsLock
MFXMutex GUISUMOAbstractView::mySnapshotsLock protected
The mutex to use before accessing the decals list in order to avoid thread conficts.
Definition at line 445 of file GUISUMOAbstractView.h.
Referenced by addSnapshot(), and checkSnapshots().
myUseToolTips
bool GUISUMOAbstractView::myUseToolTips protected
use tool tips
Definition at line 417 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), makeSnapshot(), paintGL(), showToolTips(), and updateToolTip().
myViewportChooser
GUIDialog_EditViewport* GUISUMOAbstractView::myViewportChooser protected
viewport chooser
Definition at line 423 of file GUISUMOAbstractView.h.
Referenced by getViewportEditor(), onMouseMove(), remove(), showViewportEditor(), and ~GUISUMOAbstractView().
myVisualizationChanger
GUIDialog_ViewSettings* GUISUMOAbstractView::myVisualizationChanger protected
Visualization changer.
Definition at line 429 of file GUISUMOAbstractView.h.
Referenced by remove(), GUIViewTraffic::setColorScheme(), GNEViewNet::setColorScheme(), showViewschemeEditor(), and ~GUISUMOAbstractView().
myVisualizationSettings
GUIVisualizationSettings* GUISUMOAbstractView::myVisualizationSettings protected
visualization settings
Definition at line 414 of file GUISUMOAbstractView.h.
Referenced by GNEViewNet::buildEditModeControls(), GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), getObjectsInBoundary(), getVisualisationSettings(), makeSnapshot(), GNEViewNet::onCmdShowGrid(), GNEViewNet::onCmdToogleShowConnection(), onConfigure(), GNEViewNet::onMouseMove(), paintGL(), paintGLGrid(), GUIViewTraffic::setColorScheme(), GNEViewNet::setColorScheme(), GNEViewNet::setSelectionScaling(), GNEViewNet::showConnections(), showViewschemeEditor(), snapToActiveGrid(), GNEViewNet::updateModeSpecificControls(), and ~GUISUMOAbstractView().
myWindowCursorPositionX
FXint GUISUMOAbstractView::myWindowCursorPositionX protected
Position of the cursor relative to the window.
Definition at line 426 of file GUISUMOAbstractView.h.
Referenced by getPositionInformation(), and setWindowCursorPosition().
myWindowCursorPositionY
FXint GUISUMOAbstractView::myWindowCursorPositionY protected
Definition at line 426 of file GUISUMOAbstractView.h.
Referenced by getPositionInformation(), and setWindowCursorPosition().
The documentation for this class was generated from the following files:
GUISUMOAbstractView.h
GUISUMOAbstractView.cpp