SUMO - Simulation of Urban MObility: NBLoadedTLDef Class Reference
NBLoadedTLDef Class Reference
A loaded (complete) traffic light logic.
#include <NBLoadedTLDef.h>
Data Structures
class SignalGroup
A single signal group, may control several connections.
Public Types
typedef std::map< std::string, SignalGroup * > SignalGroupCont
Definition of the container for signal groups.
enum TLColor {
TLCOLOR_RED, TLCOLOR_YELLOW, TLCOLOR_REDYELLOW, TLCOLOR_GREEN,
TLCOLOR_BLINK
}
An enumeration of possible tl-signal states.
Public Member Functions
void addControlledInnerEdges (const std::vector< std::string > &edges)
Adds the given ids into the list of inner edges controlled by the tls.
void addSignalGroup (const std::string &id)
Adds a signal group.
void addSignalGroupPhaseBegin (const std::string &groupid, SUMOTime time, TLColor color)
Sets the information about the begin of a phase.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool addToSignalGroup (const std::string &groupid, const NBConnection &connection)
Adds a connection to a signal group.
bool addToSignalGroup (const std::string &groupid, const NBConnectionVector &connections)
Adds a list of connections to a signal group.
void clearParameter ()
Clears the parameter map.
NBTrafficLightLogic * compute (OptionsCont &oc)
Computes the traffic light logic.
SignalGroup * findGroup (NBEdge *from, NBEdge *to) const
Returns the signal group which is responsible for the given connection.
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority, bool sameNodeOnly=false) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
std::vector< std::string > getControlledInnerEdges () const
Retrieve the ids of edges explicitly controlled by the tls.
const NBConnectionVector & getControlledLinks () const
returns the controlled links (depends on previous call to collectLinks)
NBConnectionVector & getControlledLinks ()
returns the controlled links (non const version)
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::string & getID () const
Returns the id.
const EdgeVector & getIncomingEdges () const
Returns the list of incoming edges (must be build first)
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
SUMOTime getOffset ()
Returns the offset.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
const std::string & getProgramID () const
Returns the ProgramID.
TrafficLightType getType () const
get the algorithm type (static etc..)
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
bool mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrake (const NBConnection &possProhibited, const NBConnection &possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
bool mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
NBLoadedTLDef (const NBEdgeCont &ec, const std::string &id, const std::vector< NBNode *> &junctions, SUMOTime offset, TrafficLightType type)
Constructor.
NBLoadedTLDef (const NBEdgeCont &ec, const std::string &id, NBNode *junction, SUMOTime offset, TrafficLightType type)
Constructor.
NBLoadedTLDef (const NBEdgeCont &ec, const std::string &id, SUMOTime offset, TrafficLightType type)
Constructor.
bool needsCont (const NBEdge *fromE, const NBEdge *toE, const NBEdge *otherFromE, const NBEdge *otherToE) const
virtual bool rightOnRedConflict (int index, int foeIndex) const
whether the given index must yield to the foeIndex while turing right on a red light
void setCycleDuration (int cycleDur)
Sets the duration of a cycle.
void setID (const std::string &newID)
resets the id
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void setProgramID (const std::string &programID)
Sets the programID.
void setSignalYellowTimes (const std::string &groupid, SUMOTime tRedYellow, SUMOTime tYellow)
Sets the times the light is yellow or red/yellow.
virtual void setType (TrafficLightType type)
set the algorithm type (static etc..)
virtual void shiftTLConnectionLaneIndex (NBEdge *edge, int offset)
patches (loaded) signal plans by modifying lane indices
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
~NBLoadedTLDef ()
Destructor.
Public methods from NBTrafficLightDefinition-interface
void setTLControllingInformation () const
Informs edges about being controlled by a tls.
void remapRemoved (NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
void initNeedsContRelation () const
Access to controlled nodes
virtual void addNode (NBNode *node)
Adds a node to the traffic light logic.
virtual void removeNode (NBNode *node)
Removes the given node from the list of controlled nodes.
virtual void removeConnection (const NBConnection &conn, bool reconstruct=true)
removes the given connection from the traffic light if recontruct=true, reconstructs the logic and informs the edges for immediate use in NETEDIT
const std::vector< NBNode * > & getNodes () const
Returns the list of controlled nodes.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Static Public Attributes
static const std::string DefaultProgramID = "0"
static const SUMOTime UNSPECIFIED_DURATION
Protected Types
typedef std::set< StreamPair > NeedsContRelation
typedef std::set< std::pair< int, int > > RightOnRedConflicts
Protected Member Functions
virtual bool amInvalid () const
void collectAllLinks ()
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
virtual void collectEdges ()
Build the list of participating edges.
int computeBrakingTime (double minDecel) const
Computes the time vehicles may need to brake.
Protected methods from NBTrafficLightDefinition-interface
NBTrafficLightLogic * myCompute (int brakingTimeSeconds)
Computes the traffic light logic finally in dependence to the type.
void setParticipantsInformation ()
Builds the list of participating nodes/edges/links.
void collectNodes ()
Collects the nodes participating in this traffic light.
void collectLinks ()
Collects the links participating in this traffic light.
bool mustBrake (const NBConnection &possProhibited, const std::string &state, int strmpos) const
Returns the information whether a connection must brake, given a phase.
void replaceRemoved (NBEdge *removed, int removedLane, NBEdge *by, int byLane)
Replaces a removed edge/lane.
Protected Attributes
std::set< std::string > myControlledInnerEdges
Set of inner edges that shall be controlled, though.
NBConnectionVector myControlledLinks
The list of controlled links.
std::vector< NBNode * > myControlledNodes
The container with participating nodes.
EdgeVector myEdgesWithin
The list of edges within the area controlled by the tls.
std::string myID
The name of the object.
EdgeVector myIncomingEdges
The list of incoming edges.
NeedsContRelation myNeedsContRelation
bool myNeedsContRelationReady
SUMOTime myOffset
The offset in the program.
RightOnRedConflicts myRightOnRedConflicts
bool myRightOnRedConflictsReady
std::string mySubID
The tls program's subid.
TrafficLightType myType
The algorithm type for the traffic light.
Static Protected Attributes
static const std::string DummyID = "dummy"
id for temporary definitions
Private Member Functions
std::string buildPhaseState (int time) const
Builds the phase for a given time.
Private Attributes
int myCycleDuration
The duration of a single cycle.
const NBEdgeCont * myEdgeCont
SignalGroupCont mySignalGroups
Controlled signal groups.
Detailed Description
A loaded (complete) traffic light logic.
Definition at line 48 of file NBLoadedTLDef.h.
Member Typedef Documentation
NeedsContRelation
typedef std::set<StreamPair> NBTrafficLightDefinition::NeedsContRelation protected inherited
Definition at line 450 of file NBTrafficLightDefinition.h.
RightOnRedConflicts
typedef std::set<std::pair<int, int> > NBTrafficLightDefinition::RightOnRedConflicts protected inherited
Definition at line 454 of file NBTrafficLightDefinition.h.
SignalGroupCont
typedef std::map<std::string, SignalGroup*> NBLoadedTLDef::SignalGroupCont
Definition of the container for signal groups.
Definition at line 204 of file NBLoadedTLDef.h.
Member Enumeration Documentation
TLColor
enum NBTrafficLightDefinition::TLColor inherited
An enumeration of possible tl-signal states.
Enumerator
TLCOLOR_RED
Signal shows red.
TLCOLOR_YELLOW
Signal shows yellow.
TLCOLOR_REDYELLOW
Signal shows red/yellow (unused)
TLCOLOR_GREEN
Signal shows green.
TLCOLOR_BLINK
Signal is blinking yellow.
Definition at line 84 of file NBTrafficLightDefinition.h.
Constructor & Destructor Documentation
NBLoadedTLDef() [1/3]
NBLoadedTLDef::NBLoadedTLDef (const NBEdgeCont & ec, const std::string & id, const std::vector< NBNode *> & junctions, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junctions Junctions controlled by this tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 263 of file NBLoadedTLDef.cpp.
NBLoadedTLDef() [2/3]
NBLoadedTLDef::NBLoadedTLDef (const NBEdgeCont & ec, const std::string & id, NBNode * junction, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junction The junction controlled by this tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 270 of file NBLoadedTLDef.cpp.
NBLoadedTLDef() [3/3]
NBLoadedTLDef::NBLoadedTLDef (const NBEdgeCont & ec, const std::string & id, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 276 of file NBLoadedTLDef.cpp.
~NBLoadedTLDef()
NBLoadedTLDef::~NBLoadedTLDef ()
Destructor.
Definition at line 282 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Member Function Documentation
addControlledInnerEdges()
void NBTrafficLightDefinition::addControlledInnerEdges (const std::vector< std::string > & edges) inherited
Adds the given ids into the list of inner edges controlled by the tls.
Parameters
[in] edges The list of edge ids which shall be controlled despite lying with the jointly controlled node cluster
Definition at line 437 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
Referenced by NBTrafficLightDefinition::getNodes(), and NIXMLTrafficLightsHandler::initTrafficLightLogic().
addNode()
void NBTrafficLightDefinition::addNode (NBNode * node) virtual inherited
Adds a node to the traffic light logic.
Parameters
[in] node A further node that shall be controlled by the tls
Definition at line 417 of file NBTrafficLightDefinition.cpp.
References NBNode::addTrafficLight(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBLoadedSUMOTLDef::addConnection(), addToSignalGroup(), GNEJunction::addTrafficLight(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBNode::invalidateTLS(), and NBTrafficLightDefinition::NBTrafficLightDefinition().
addSignalGroup()
void NBLoadedTLDef::addSignalGroup (const std::string & id)
Adds a signal group.
Parameters
[in] id The id of the signal group
Definition at line 601 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), and NIVisumTL::build().
addSignalGroupPhaseBegin()
void NBLoadedTLDef::addSignalGroupPhaseBegin (const std::string & groupid, SUMOTime time, TLColor color)
Sets the information about the begin of a phase.
Parameters
[in] groupid The id of the signal group to add the phase to
[in] time The time the phase starts at
[in] color The color of the signal during this phase
Definition at line 608 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), and NIVisumTL::build().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
addToSignalGroup() [1/2]
bool NBLoadedTLDef::addToSignalGroup (const std::string & groupid, const NBConnection & connection)
Adds a connection to a signal group.
Parameters
[in] groupid The id of the signal group to add the connection to
[in] connection The connection to add
Definition at line 569 of file NBLoadedTLDef.cpp.
References NBTrafficLightDefinition::addNode(), NBNode::addTrafficLight(), NBConnection::getFrom(), NBEdge::getFromNode(), NBConnection::getTo(), NBEdge::getToNode(), and mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), addToSignalGroup(), and NIVisumTL::build().
addToSignalGroup() [2/2]
bool NBLoadedTLDef::addToSignalGroup (const std::string & groupid, const NBConnectionVector & connections)
Adds a list of connections to a signal group.
Parameters
[in] groupid The id of the signal group to add the connections to
[in] connections The connections to add
Definition at line 590 of file NBLoadedTLDef.cpp.
References addToSignalGroup().
amInvalid()
bool NBTrafficLightDefinition::amInvalid () const protected virtual inherited
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 138 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by NBTrafficLightDefinition::compute(), and NBTrafficLightDefinition::initNeedsContRelation().
buildPhaseState()
std::string NBLoadedTLDef::buildPhaseState (int time) const private
Builds the phase for a given time.
Parameters
[in] ec The edge control to use
[in] time The time to build the phase for
Returns
The phase of this tls for the given time
Definition at line 387 of file NBLoadedTLDef.cpp.
References NBConnection::check(), NBLoadedTLDef::SignalGroup::getConnection(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBLoadedTLDef::SignalGroup::hasYellow(), NBLoadedTLDef::SignalGroup::mayDrive(), mustBrake(), myEdgeCont, and mySignalGroups.
Referenced by myCompute().
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
collectAllLinks()
void NBTrafficLightDefinition::collectAllLinks () protected inherited
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
Definition at line 455 of file NBTrafficLightDefinition.cpp.
References NBEdge::Connection::fromLane, NBEdge::getConnectionsFromLane(), Named::getID(), NBEdge::getNumLanes(), NBEdge::getPermissions(), NBEdge::getToNode(), NBNode::getType(), isRailway(), NBEdge::mayBeTLSControlled(), NBTrafficLightDefinition::myControlledLinks, NBTrafficLightDefinition::myIncomingEdges, NODETYPE_RAIL_CROSSING, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, toString(), and WRITE_WARNING.
Referenced by NBLoadedSUMOTLDef::collectLinks(), and NBOwnTLDef::collectLinks().
collectEdges()
void NBTrafficLightDefinition::collectEdges () protected virtual inherited
Build the list of participating edges.
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 188 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::collectReachable(), NBTrafficLightDefinition::DummyID, NBNode::FORWARD, OptionsCont::getBool(), NBEdge::getFirstNonPedestrianLaneIndex(), Named::getID(), OptionsCont::getOptions(), NBTrafficLightDefinition::myControlledInnerEdges, NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::myEdgesWithin, NBTrafficLightDefinition::myIncomingEdges, NBEdge::setIsInnerEdge(), and WRITE_WARNING.
Referenced by NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::setParticipantsInformation(), and setParticipantsInformation().
collectLinks()
void NBLoadedTLDef::collectLinks () protected virtual
Collects the links participating in this traffic light.
Exceptions
ProcessError If a link could not be found
See also
NBTrafficLightDefinition::collectLinks
Implements NBTrafficLightDefinition.
Definition at line 508 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::getConnection(), NBEdge::getConnectionsFromLane(), NBConnection::getFrom(), NBConnection::getFromLane(), Named::getID(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBEdge::getNumLanes(), NBConnection::getTLIndex(), NBConnection::getTo(), NBConnection::getToLane(), NBConnection::InvalidTlIndex, NBTrafficLightDefinition::myControlledLinks, myEdgeCont, NBTrafficLightDefinition::myIncomingEdges, mySignalGroups, NBConnection::setTLIndex(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, and WRITE_WARNING.
Referenced by setParticipantsInformation().
collectNodes()
void NBLoadedTLDef::collectNodes () protected
Collects the nodes participating in this traffic light.
See also
NBTrafficLightDefinition::collectNodes
Definition at line 490 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::getConnection(), NBConnection::getFrom(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBEdge::getToNode(), NBTrafficLightDefinition::myControlledNodes, and mySignalGroups.
Referenced by setParticipantsInformation().
compute()
NBTrafficLightLogic * NBTrafficLightDefinition::compute (OptionsCont & oc) inherited
Computes the traffic light logic.
Does some initialisation at first, then calls myCompute to finally build the tl-logic
Parameters
[in] oc The options container holding options needed during the building
Returns
The built logic (may be 0)
Definition at line 113 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::amInvalid(), NBTrafficLightDefinition::computeBrakingTime(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), Parameterised::getMap(), OptionsCont::isDefault(), NBTrafficLightDefinition::myCompute(), NBTrafficLightDefinition::myControlledNodes, Parameterised::updateParameter(), and WRITE_WARNING.
Referenced by NBTrafficLightLogicCont::computeSingleLogic(), GNEConnection::isValid(), and NBLoadedSUMOTLDef::reconstructLogic().
computeBrakingTime()
int NBTrafficLightDefinition::computeBrakingTime (double minDecel) const protected inherited
Computes the time vehicles may need to brake.
This time depends on the maximum speed allowed on incoming junctions. It is computed as max_speed_allowed / minimum_vehicle_decleration
Definition at line 144 of file NBTrafficLightDefinition.cpp.
References MAX2(), NBContHelper::maxSpeed(), and NBTrafficLightDefinition::myIncomingEdges.
Referenced by NBTrafficLightDefinition::compute().
findGroup()
NBLoadedTLDef::SignalGroup * NBLoadedTLDef::findGroup (NBEdge * from, NBEdge * to) const
Returns the signal group which is responsible for the given connection.
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
The signal group which controls the given connection
Definition at line 558 of file NBLoadedTLDef.cpp.
References mySignalGroups.
foes()
bool NBTrafficLightDefinition::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const inherited
Returns the information whether the given flows cross.
Parameters
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns
Whether both stream are foes (cross)
Definition at line 394 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBTrafficLightDefinition::getNodes(), and NBLoadedSUMOTLDef::initNeedsContRelation().
forbids()
bool NBTrafficLightDefinition::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority, bool sameNodeOnly = false) const inherited
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
[in] sameNodeOnly Whether the check shall only be performed if both edges are incoming to the same node
Returns
Whether the second flow prohibits the first one
See also
forbids
Definition at line 275 of file NBTrafficLightDefinition.cpp.
References DEBUGCOND, NBNode::foes(), NBNode::forbids(), NBEdge::getConnectedEdges(), NBNode::getDirection(), Named::getID(), LINKDIR_STRAIGHT, and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::computeUnblockedWeightedStreamNumber(), NBOwnTLDef::correctConflicting(), NBTrafficLightDefinition::getNodes(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), and myCompute().
getControlledInnerEdges()
std::vector< std::string > NBTrafficLightDefinition::getControlledInnerEdges () const inherited
Retrieve the ids of edges explicitly controlled by the tls.
Definition at line 443 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
Referenced by NBTrafficLightDefinition::getNodes(), and NIXMLTrafficLightsHandler::initTrafficLightLogic().
getControlledLinks() [1/2]
const NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () const inline inherited
returns the controlled links (depends on previous call to collectLinks)
Definition at line 300 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by GNETLSEditorFrame::buildIinternalLanes(), GNETLSEditorFrame::controlsEdge(), GNETLSEditorFrame::handleMultiChange(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), and NBLoadedSUMOTLDef::reconstructLogic().
getControlledLinks() [2/2]
NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () inline inherited
returns the controlled links (non const version)
Definition at line 306 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledLinks.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getIncomingEdges()
const EdgeVector & NBTrafficLightDefinition::getIncomingEdges () const inherited
Returns the list of incoming edges (must be build first)
Returns
The edges which are incoming into the tls
Definition at line 449 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myIncomingEdges.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBLoadedSUMOTLDef::reconstructLogic(), and NBTrafficLightDefinition::shiftTLConnectionLaneIndex().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getNodes()
const std::vector<NBNode*>& NBTrafficLightDefinition::getNodes () const inline inherited
Returns the list of controlled nodes.
Returns
Controlled nodes
Definition at line 179 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::addControlledInnerEdges(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), NBTrafficLightDefinition::getControlledInnerEdges(), NBTrafficLightDefinition::mustBrake(), NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::remapRemoved(), NBTrafficLightDefinition::replaceRemoved(), NBTrafficLightDefinition::setParticipantsInformation(), and NBTrafficLightDefinition::setTLControllingInformation().
Referenced by NBTrafficLightLogicCont::computeSingleLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), GNETLSEditorFrame::onCmdOK(), GNEJunction::removeTrafficLight(), and GNEJunction::setAttribute().
getOffset()
SUMOTime NBTrafficLightDefinition::getOffset () inline inherited
Returns the offset.
Returns
Offset
Definition at line 330 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myOffset.
Referenced by GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), and NBLoadedSUMOTLDef::reconstructLogic().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getProgramID()
const std::string& NBTrafficLightDefinition::getProgramID () const inline inherited
Returns the ProgramID.
Returns
The ID of the program (subID)
Definition at line 314 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NIImporter_SUMO::addPhase(), NBOwnTLDef::computeLogicAndConts(), NBTrafficLightLogicCont::computeSingleLogic(), NBTrafficLightLogicCont::extract(), NBTrafficLightLogicCont::insert(), GNEJunction::invalidateTLS(), myCompute(), NIImporter_SUMO::myEndElement(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedSUMOTLDef::reconstructLogic().
getType()
TrafficLightType NBTrafficLightDefinition::getType () const inline inherited
get the algorithm type (static etc..)
Definition at line 336 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myType.
Referenced by NBOwnTLDef::correctConflicting(), GNETLSEditorFrame::initPhaseTable(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), GNETLSEditorFrame::onCmdPhaseCreate(), GNETLSEditorFrame::onCmdPhaseEdit(), NIXMLNodesHandler::processTrafficLightDefinitions(), and NBLoadedSUMOTLDef::reconstructLogic().
initNeedsContRelation()
void NBLoadedTLDef::initNeedsContRelation () const virtual
Reimplemented from NBTrafficLightDefinition.
Definition at line 657 of file NBLoadedTLDef.cpp.
References NBTrafficLightDefinition::myNeedsContRelationReady.
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
mustBrake() [1/4]
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const from, const NBEdge *const to) const inherited
Returns the information whether the described flow must let any other flow pass.
If the from/to connection passes only one junction (from is incoming into same node as to outgoes from) the node is asked whether the flow must brake- Otherwise true is returned (recheck!) "from" must be an incoming edge into one of the participating nodes!
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 238 of file NBTrafficLightDefinition.cpp.
References NBNode::mustBrake(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBTrafficLightDefinition::getNodes(), and mustBrake().
mustBrake() [2/4]
bool NBTrafficLightDefinition::mustBrake (const NBConnection & possProhibited, const NBConnection & possProhibitor, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether the described flow must let the other flow pass.
Parameters
[in] possProhibited The maybe prohibited connection
[in] possProhibitor The maybe prohibiting connection
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See also
forbids
Definition at line 265 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids(), NBConnection::getFrom(), and NBConnection::getTo().
mustBrake() [3/4]
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether the described flow must let any other flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See also
forbids
Definition at line 253 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids().
mustBrake() [4/4]
bool NBLoadedTLDef::mustBrake (const NBConnection & possProhibited, const std::string & state, int strmpos) const protected
Returns the information whether a connection must brake, given a phase.
Parameters
[in] possProhibited The connection to investigate
[in] state The state
[in] strmpos The index of this connection within the masks
Returns
Whether the given connection must brake
Definition at line 441 of file NBLoadedTLDef.cpp.
References NBConnection::check(), NBLoadedTLDef::SignalGroup::getConnection(), NBConnection::getFrom(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBTrafficLightDefinition::mustBrake(), myEdgeCont, and mySignalGroups.
Referenced by buildPhaseState().
myCompute()
NBTrafficLightLogic * NBLoadedTLDef::myCompute (int brakingTimeSeconds) protected virtual
Computes the traffic light logic finally in dependence to the type.
Parameters
[in] brakingTime Duration a vehicle needs for braking in front of the tls in seconds
Returns
The computed logic
See also
NBTrafficLightDefinition::myCompute
Implements NBTrafficLightDefinition.
Definition at line 290 of file NBLoadedTLDef.cpp.
References NBTrafficLightLogic::addStep(), buildPhaseState(), MsgHandler::clear(), NBTrafficLightLogic::closeBuilding(), NBTrafficLightDefinition::forbids(), OptionsCont::getBool(), NBConnection::getFrom(), NBConnection::getFromLane(), Named::getID(), OptionsCont::getOptions(), NBTrafficLightLogic::getPhases(), NBTrafficLightDefinition::getProgramID(), NBLoadedTLDef::SignalGroup::getTimes(), NBConnection::getTLIndex(), NBConnection::getTo(), MsgHandler::getWarningInstance(), NBConnection::InvalidTlIndex, NBTrafficLightDefinition::myControlledLinks, myCycleDuration, NBTrafficLightDefinition::myNeedsContRelation, NBTrafficLightDefinition::myNeedsContRelationReady, NBTrafficLightDefinition::myOffset, mySignalGroups, NBTrafficLightDefinition::myType, NBLoadedTLDef::SignalGroup::patchTYellow(), NBNode::rightTurnConflict(), NBLoadedTLDef::SignalGroup::sortPhases(), TIME2STEPS, and WRITE_WARNING.
needsCont()
bool NBTrafficLightDefinition::needsCont (const NBEdge * fromE, const NBEdge * toE, const NBEdge * otherFromE, const NBEdge * otherToE) const inherited
Definition at line 486 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::initNeedsContRelation(), NBTrafficLightDefinition::myNeedsContRelation, and NBTrafficLightDefinition::myNeedsContRelationReady.
Referenced by NBTrafficLightDefinition::setType().
remapRemoved()
void NBLoadedTLDef::remapRemoved (NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) virtual
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
Parameters
[in] removed The removed edge
[in] incoming The edges to use instead if an incoming edge was removed
[in] outgoing The edges to use instead if an outgoing edge was removed
See also
NBTrafficLightDefinition::remapRemoved
Implements NBTrafficLightDefinition.
Definition at line 629 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::containsIncoming(), NBLoadedTLDef::SignalGroup::containsOutgoing(), mySignalGroups, NBLoadedTLDef::SignalGroup::remapIncoming(), and NBLoadedTLDef::SignalGroup::remapOutgoing().
removeConnection()
virtual void NBTrafficLightDefinition::removeConnection (const NBConnection & conn, bool reconstruct = true) inline virtual inherited
removes the given connection from the traffic light if recontruct=true, reconstructs the logic and informs the edges for immediate use in NETEDIT
Note
: tlIndex is not necessarily unique. we need the whole connection data here
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 171 of file NBTrafficLightDefinition.h.
References UNUSED_PARAMETER.
removeNode()
void NBTrafficLightDefinition::removeNode (NBNode * node) virtual inherited
Removes the given node from the list of controlled nodes.
Parameters
[in] node The node that shall not be controlled by the tls any more
Definition at line 427 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBNode::removeTrafficLight().
replaceRemoved()
void NBLoadedTLDef::replaceRemoved (NBEdge * removed, int removedLane, NBEdge * by, int byLane) protected virtual
Replaces a removed edge/lane.
Parameters
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
See also
NBTrafficLightDefinition::replaceRemoved
Implements NBTrafficLightDefinition.
Definition at line 645 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::containsIncoming(), NBLoadedTLDef::SignalGroup::containsOutgoing(), mySignalGroups, and NBLoadedTLDef::SignalGroup::remap().
rightOnRedConflict()
bool NBTrafficLightDefinition::rightOnRedConflict (int index, int foeIndex) const virtual inherited
whether the given index must yield to the foeIndex while turing right on a red light
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 511 of file NBTrafficLightDefinition.cpp.
References NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::DummyID, NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::myRightOnRedConflicts, NBTrafficLightDefinition::myRightOnRedConflictsReady, NBTrafficLightDefinition::setParticipantsInformation(), and TLTYPE_STATIC.
Referenced by NBTrafficLightDefinition::setType().
setCycleDuration()
void NBLoadedTLDef::setCycleDuration (int cycleDur)
Sets the duration of a cycle.
Parameters
[in] cycleDur The duration of the cycle
Definition at line 623 of file NBLoadedTLDef.cpp.
References myCycleDuration.
Referenced by NIVisumTL::build(), and NIVissimTL::dict_SetSignals().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setParticipantsInformation()
void NBLoadedTLDef::setParticipantsInformation () protected virtual
Builds the list of participating nodes/edges/links.
See also
NBTrafficLightDefinition::setParticipantsInformation
Reimplemented from NBTrafficLightDefinition.
Definition at line 481 of file NBLoadedTLDef.cpp.
References NBTrafficLightDefinition::collectEdges(), collectLinks(), and collectNodes().
setProgramID()
void NBTrafficLightDefinition::setProgramID (const std::string & programID) inline inherited
Sets the programID.
Parameters
[in] programID The new ID of the program (subID)
Definition at line 322 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NBTrafficLightLogicCont::insert(), GNEJunction::invalidateTLS(), and NBLoadedSUMOTLDef::reconstructLogic().
setSignalYellowTimes()
void NBLoadedTLDef::setSignalYellowTimes (const std::string & groupid, SUMOTime tRedYellow, SUMOTime tYellow)
Sets the times the light is yellow or red/yellow.
Parameters
[in] groupid The id of the signal group to add the phase to
[in] tRedYellow The duration of redyellow
[in] tYellow The duration of yellow
Definition at line 615 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), and NIVisumTL::build().
setTLControllingInformation()
void NBLoadedTLDef::setTLControllingInformation () const virtual
Informs edges about being controlled by a tls.
Parameters
[in] ec The container of edges
See also
NBTrafficLightDefinition::setTLControllingInformation
Implements NBTrafficLightDefinition.
Definition at line 375 of file NBLoadedTLDef.cpp.
References NBConnection::getFrom(), Named::getID(), NBConnection::getTLIndex(), NBConnection::InvalidTlIndex, NBTrafficLightDefinition::myControlledLinks, and NBEdge::setControllingTLInformation().
setType()
virtual void NBTrafficLightDefinition::setType (TrafficLightType type) inline virtual inherited
set the algorithm type (static etc..)
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 341 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::initNeedsContRelation(), NBTrafficLightDefinition::myType, NBTrafficLightDefinition::needsCont(), and NBTrafficLightDefinition::rightOnRedConflict().
shiftTLConnectionLaneIndex()
virtual void NBTrafficLightDefinition::shiftTLConnectionLaneIndex (NBEdge * edge, int offset) inline virtual inherited
patches (loaded) signal plans by modifying lane indices
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 288 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::getIncomingEdges(), and UNUSED_PARAMETER.
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
DefaultProgramID
const std::string NBTrafficLightDefinition::DefaultProgramID = "0" static inherited
Definition at line 78 of file NBTrafficLightDefinition.h.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
DummyID
const std::string NBTrafficLightDefinition::DummyID = "dummy" static protected inherited
id for temporary definitions
Definition at line 360 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), NBLoadedSUMOTLDef::reconstructLogic(), NBTrafficLightDefinition::rightOnRedConflict(), and NBLoadedSUMOTLDef::setTLControllingInformation().
myControlledInnerEdges
std::set<std::string> NBTrafficLightDefinition::myControlledInnerEdges protected inherited
Set of inner edges that shall be controlled, though.
Definition at line 408 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addControlledInnerEdges(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), and NBTrafficLightDefinition::getControlledInnerEdges().
myControlledLinks
NBConnectionVector NBTrafficLightDefinition::myControlledLinks protected inherited
The list of controlled links.
Definition at line 405 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedSUMOTLDef::amInvalid(), NBTrafficLightDefinition::amInvalid(), NBLoadedSUMOTLDef::cleanupStates(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedSUMOTLDef::collectLinks(), collectLinks(), NBTrafficLightDefinition::getControlledLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), myCompute(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::reconstructLogic(), NBLoadedSUMOTLDef::removeConnection(), NBLoadedSUMOTLDef::replaceRemoved(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), setTLControllingInformation(), and NBLoadedSUMOTLDef::shiftTLConnectionLaneIndex().
myControlledNodes
std::vector<NBNode*> NBTrafficLightDefinition::myControlledNodes protected inherited
The container with participating nodes.
Definition at line 396 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addNode(), NBLoadedSUMOTLDef::amInvalid(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectLinks(), collectNodes(), NBTrafficLightDefinition::compute(), NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), NBTrafficLightDefinition::getNodes(), NBOwnTLDef::initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBTrafficLightDefinition::NBTrafficLightDefinition(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::reconstructLogic(), NBTrafficLightDefinition::removeNode(), NBTrafficLightDefinition::rightOnRedConflict(), and NBLoadedSUMOTLDef::setTLControllingInformation().
myCycleDuration
int NBLoadedTLDef::myCycleDuration private
The duration of a single cycle.
Definition at line 388 of file NBLoadedTLDef.h.
Referenced by myCompute(), and setCycleDuration().
myEdgeCont
const NBEdgeCont* NBLoadedTLDef::myEdgeCont private
Definition at line 380 of file NBLoadedTLDef.h.
Referenced by buildPhaseState(), collectLinks(), and mustBrake().
myEdgesWithin
EdgeVector NBTrafficLightDefinition::myEdgesWithin protected inherited
The list of edges within the area controlled by the tls.
Definition at line 402 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::collectEdges(), and NBTrafficLightDefinition::collectEdges().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myIncomingEdges
EdgeVector NBTrafficLightDefinition::myIncomingEdges protected inherited
The list of incoming edges.
Definition at line 399 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::amInvalid(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), collectLinks(), NBTrafficLightDefinition::computeBrakingTime(), NBTrafficLightDefinition::getIncomingEdges(), and NBLoadedSUMOTLDef::reconstructLogic().
myNeedsContRelation
NeedsContRelation NBTrafficLightDefinition::myNeedsContRelation mutable protected inherited
Definition at line 451 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::correctConflicting(), NBOwnTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), myCompute(), and NBTrafficLightDefinition::needsCont().
myNeedsContRelationReady
bool NBTrafficLightDefinition::myNeedsContRelationReady mutable protected inherited
Definition at line 452 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::initNeedsContRelation(), initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), myCompute(), and NBTrafficLightDefinition::needsCont().
myOffset
SUMOTime NBTrafficLightDefinition::myOffset protected inherited
The offset in the program.
Definition at line 414 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::getOffset(), myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::reconstructLogic(), and NBLoadedSUMOTLDef::setOffset().
myRightOnRedConflicts
RightOnRedConflicts NBTrafficLightDefinition::myRightOnRedConflicts mutable protected inherited
Definition at line 455 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::correctConflicting(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::rightOnRedConflict(), and NBTrafficLightDefinition::rightOnRedConflict().
myRightOnRedConflictsReady
bool NBTrafficLightDefinition::myRightOnRedConflictsReady mutable protected inherited
Definition at line 456 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::rightOnRedConflict(), and NBTrafficLightDefinition::rightOnRedConflict().
mySignalGroups
SignalGroupCont NBLoadedTLDef::mySignalGroups private
Controlled signal groups.
Definition at line 385 of file NBLoadedTLDef.h.
Referenced by addSignalGroup(), addSignalGroupPhaseBegin(), addToSignalGroup(), buildPhaseState(), collectLinks(), collectNodes(), findGroup(), mustBrake(), myCompute(), remapRemoved(), replaceRemoved(), setSignalYellowTimes(), and ~NBLoadedTLDef().
mySubID
std::string NBTrafficLightDefinition::mySubID protected inherited
The tls program's subid.
Definition at line 411 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::getProgramID(), and NBTrafficLightDefinition::setProgramID().
myType
TrafficLightType NBTrafficLightDefinition::myType protected inherited
The algorithm type for the traffic light.
Definition at line 417 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::getType(), myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::reconstructLogic(), NBLoadedSUMOTLDef::setType(), and NBTrafficLightDefinition::setType().
UNSPECIFIED_DURATION
const SUMOTime NBTrafficLightDefinition::UNSPECIFIED_DURATION static inherited
Definition at line 77 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::addPedestrianScramble(), NIImporter_SUMO::addPhase(), NBTrafficLightLogic::addStep(), NBTrafficLightLogic::closeBuilding(), NBOwnTLDef::computeLogicAndConts(), GNETLSEditorFrame::onCmdPhaseEdit(), GNETLSEditorFrame::varDurString(), and NWWriter_SUMO::writeTrafficLights().
The documentation for this class was generated from the following files:
NBLoadedTLDef.h
NBLoadedTLDef.cpp