SUMO - Simulation of Urban MObility: RORoutable Class Reference
RORoutable Class Reference abstract
A routable thing such as a vehicle or person.
#include <RORoutable.h>
Public Member Functions
virtual void computeRoute (const RORouterProvider &provider, const bool removeLoops, MsgHandler *errorHandler)=0
SUMOTime getDepart () const
Returns the time the vehicle starts at, -1 for triggered vehicles.
virtual const ROEdge * getDepartEdge () const =0
const std::string & getID () const
Returns the id of the routable.
double getMaxSpeed () const
Returns the vehicle's maximum speed.
const SUMOVehicleParameter & getParameter () const
Returns the definition of the vehicle / person parameter.
bool getRoutingSuccess () const
const SUMOVTypeParameter * getType () const
Returns the type of the routable.
SUMOVehicleClass getVClass () const
bool isPartOfFlow () const
bool isPublicTransport () const
RORoutable (const SUMOVehicleParameter &pars, const SUMOVTypeParameter *type)
Constructor.
void write (OutputDevice &os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont &options) const
Saves the routable including the vehicle type (if it was not saved before).
virtual ~RORoutable ()
Destructor.
Protected Member Functions
virtual void saveAsXML (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const =0
Saves the complete routable description.
Protected Attributes
bool myRoutingSuccess
Whether the last routing was successful.
Private Member Functions
RORoutable & operator= (const RORoutable &src)
Invalidated assignment operator.
RORoutable (const RORoutable &src)
Invalidated copy constructor.
Private Attributes
SUMOVehicleParameter myParameter
The vehicle's parameter.
const SUMOVTypeParameter *const myType
The type of the vehicle.
Detailed Description
A routable thing such as a vehicle or person.
Definition at line 61 of file RORoutable.h.
Constructor & Destructor Documentation
RORoutable() [1/2]
RORoutable::RORoutable (const SUMOVehicleParameter & pars, const SUMOVTypeParameter * type) inline
Constructor.
Parameters
[in] pars Parameter of this routable
[in] type The type of the routable
Definition at line 68 of file RORoutable.h.
~RORoutable()
virtual RORoutable::~RORoutable () inline virtual
Destructor.
Definition at line 73 of file RORoutable.h.
RORoutable() [2/2]
RORoutable::RORoutable (const RORoutable & src) private
Invalidated copy constructor.
Member Function Documentation
computeRoute()
virtual void RORoutable::computeRoute (const RORouterProvider & provider, const bool removeLoops, MsgHandler * errorHandler) pure virtual
Implemented in ROPerson, and ROVehicle.
Referenced by RONet::createBulkRouteRequests(), isPartOfFlow(), and RONet::saveAndRemoveRoutesUntil().
getDepart()
SUMOTime RORoutable::getDepart () const inline
Returns the time the vehicle starts at, -1 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 109 of file RORoutable.h.
References SUMOVehicleParameter::depart, and myParameter.
Referenced by RONet::addPerson(), RONet::addVehicle(), and ROVehicleByDepartureComperator::operator()().
getDepartEdge()
virtual const ROEdge* RORoutable::getDepartEdge () const pure virtual
Implemented in ROPerson, and ROVehicle.
Referenced by RONet::createBulkRouteRequests(), and getMaxSpeed().
getID()
const std::string& RORoutable::getID () const inline
Returns the id of the routable.
Returns
The id of the routable
Definition at line 100 of file RORoutable.h.
References SUMOVehicleParameter::id, and myParameter.
Referenced by RORouteDef::addAlternative(), RONet::addPerson(), ROVehicle::addStop(), ROPerson::addTrip(), ROPerson::computeIntermodal(), ROVehicle::computeRoute(), RONet::createBulkRouteRequests(), ROVehicleByDepartureComperator::operator()(), RORouteDef::preComputeCurrentRoute(), and RORouteDef::repairCurrentRoute().
getMaxSpeed()
double RORoutable::getMaxSpeed () const inline
Returns the vehicle's maximum speed.
Definition at line 120 of file RORoutable.h.
References getDepartEdge(), SUMOVTypeParameter::maxSpeed, and myType.
Referenced by RONet::createBulkRouteRequests().
getParameter()
const SUMOVehicleParameter& RORoutable::getParameter () const inline
Returns the definition of the vehicle / person parameter.
Returns
The vehicle / person's parameter
Definition at line 80 of file RORoutable.h.
References myParameter.
Referenced by RONet::adaptIntermodalRouter(), ROVehicle::addStop(), ROPerson::computeIntermodal(), ROVehicle::getDepartureTime(), ROVehicle::ROVehicle(), ROVehicle::saveAsXML(), and ROPerson::saveAsXML().
getRoutingSuccess()
bool RORoutable::getRoutingSuccess () const inline
Definition at line 160 of file RORoutable.h.
References myRoutingSuccess, and saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
getType()
const SUMOVTypeParameter* RORoutable::getType () const inline
Returns the type of the routable.
Returns
The routable's type
Todo:
Why not return a reference?
Definition at line 91 of file RORoutable.h.
References myType.
Referenced by ROPerson::computeIntermodal(), ROVehicle::getChosenSpeedFactor(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), getVClass(), ROVehicle::saveAsXML(), and ROPerson::saveAsXML().
getVClass()
SUMOVehicleClass RORoutable::getVClass () const inline
Definition at line 114 of file RORoutable.h.
References getType(), SVC_IGNORING, and SUMOVTypeParameter::vehicleClass.
Referenced by RONet::createBulkRouteRequests(), ROEdge::isConnectedTo(), and ROEdge::prohibits().
isPartOfFlow()
bool RORoutable::isPartOfFlow () const inline
Definition at line 132 of file RORoutable.h.
References computeRoute(), myParameter, and SUMOVehicleParameter::repetitionNumber.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
isPublicTransport()
bool RORoutable::isPublicTransport () const inline
Definition at line 128 of file RORoutable.h.
References SUMOVehicleParameter::line, and myParameter.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
operator=()
RORoutable& RORoutable::operator= (const RORoutable & src) private
Invalidated assignment operator.
saveAsXML()
virtual void RORoutable::saveAsXML (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const protected pure virtual
Saves the complete routable description.
Saves the routable itself including the route and stops.
Parameters
[in] os The routes or alternatives output device to store the routable's description into
[in] typeos The types - output device to store additional types into
[in] asAlternatives Whether the route shall be saved as route alternatives
[in] options to find out about defaults and whether exit times for the edges shall be written
Exceptions
IOError If something fails (not yet implemented)
Implemented in ROPerson, and ROVehicle.
Referenced by getRoutingSuccess(), and write().
write()
void RORoutable::write (OutputDevice & os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont & options) const inline
Saves the routable including the vehicle type (if it was not saved before).
Parameters
[in] os The routes - output device to store the vehicle's description into
[in] altos The route alternatives - output device to store the vehicle's description into
[in] typeos The types - output device to store the vehicle types into
Exceptions
IOError If something fails (not yet implemented)
Definition at line 147 of file RORoutable.h.
References saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
Field Documentation
myParameter
SUMOVehicleParameter RORoutable::myParameter private
The vehicle's parameter.
Definition at line 181 of file RORoutable.h.
Referenced by getDepart(), getID(), getParameter(), isPartOfFlow(), and isPublicTransport().
myRoutingSuccess
bool RORoutable::myRoutingSuccess protected
Whether the last routing was successful.
Definition at line 188 of file RORoutable.h.
Referenced by ROPerson::computeIntermodal(), ROVehicle::computeRoute(), ROPerson::computeRoute(), and getRoutingSuccess().
myType
const SUMOVTypeParameter* const RORoutable::myType private
The type of the vehicle.
Definition at line 184 of file RORoutable.h.
Referenced by getMaxSpeed(), and getType().
The documentation for this class was generated from the following file:
RORoutable.h