SUMO - Simulation of Urban MObility: MSTLLogicControl Class Reference
MSTLLogicControl Class Reference
A class that stores and controls tls and switching of their programs.
#include <MSTLLogicControl.h>
Data Structures
class OnSwitchAction
Base class for things to execute if a tls switches to a new phase.
class SwitchInitCommand
This event-class is used to initialise a WAUT switch at a certain time.
class TLSLogicVariants
Storage for all programs of a single tls.
struct WAUT
A WAUT definition.
struct WAUTJunction
Storage for a junction assigned to a WAUT.
struct WAUTSwitch
Storage for a WAUTs switch point.
class WAUTSwitchProcedure
This is the abstract base class for switching from one tls program to another.
class WAUTSwitchProcedure_GSP
This class switches using the GSP algorithm.
class WAUTSwitchProcedure_JustSwitch
This class simply switches to the next program.
class WAUTSwitchProcedure_Stretch
This class switches using the Stretch algorithm.
struct WAUTSwitchProcess
An initialised switch process.
Public Member Functions
bool add (const std::string &id, const std::string &programID, MSTrafficLightLogic *logic, bool newDefault=true)
Adds a tls program to the container.
void check2Switch (SUMOTime step)
Checks whether any WAUT is trying to switch a tls into another program.
bool closeNetworkReading ()
Lets MSTLLogicControl know that the network has been loaded.
TLSLogicVariants & get (const std::string &id) const
Returns the variants of a named tls.
MSTrafficLightLogic * get (const std::string &id, const std::string &programID) const
Returns a single program (variant) defined by the tls id and the program programID.
MSTrafficLightLogic * getActive (const std::string &id) const
Returns the active program of a named tls.
std::vector< MSTrafficLightLogic * > getAllLogics () const
Returns a vector which contains all logics.
std::vector< std::string > getAllTLIds () const
std::pair< SUMOTime, MSPhaseDefinition > getPhaseDef (const std::string &tlid) const
return the complete phase definition for a named traffic lights logic
SUMOTime initWautSwitch (SwitchInitCommand &cmd)
Initialises switching a WAUT.
bool isActive (const MSTrafficLightLogic *tl) const
Returns whether the given tls program is the currently active for his tls.
bool knows (const std::string &id) const
Returns the information whether the named tls is stored.
MSTLLogicControl ()
Constructor.
void setTrafficLightSignals (SUMOTime t) const
Lets all running (current) tls programs apply their current signal states to links they control.
void switchOffAll ()
switch all logic variants to 'off'
void switchTo (const std::string &id, const std::string &programID)
Switches the named (id) tls to the named (programID) program.
~MSTLLogicControl ()
Destructor.
WAUT definition methods
void addWAUT (SUMOTime refTime, const std::string &id, const std::string &startProg)
Adds a WAUT definition.
void addWAUTSwitch (const std::string &wautid, SUMOTime when, const std::string &to)
Adds a WAUT switch step to a previously built WAUT.
void addWAUTJunction (const std::string &wautid, const std::string &tls, const std::string &proc, bool synchron)
Adds a tls to the list of tls to be switched by the named WAUT.
void closeWAUT (const std::string &wautid)
Closes loading of a WAUT.
Protected Attributes
std::vector< WAUTSwitchProcess > myCurrentlySwitched
A list of currently running switching procedures.
std::map< std::string, TLSLogicVariants * > myLogics
A map from ids to the corresponding variants.
bool myNetWasLoaded
Information whether the net was completely loaded.
std::map< std::string, WAUT * > myWAUTs
A map of ids to corresponding WAUTs.
Private Member Functions
MSTLLogicControl (const MSTLLogicControl &)
Invalidated copy constructor.
MSTLLogicControl & operator= (const MSTLLogicControl &)
Invalidated assignment operator.
Detailed Description
A class that stores and controls tls and switching of their programs.
This class holds all traffic light logics (programs) and their variants during the simulation. In addition, the schedule for switching between different tls programs are also stored.
When a WAUT is forced to switch, for each TLS, a switching procedure derived from WAUTSwitchProcedure is initialised and is asked repeatedly whether a switch could be done until it returns true.
Definition at line 66 of file MSTLLogicControl.h.
Constructor & Destructor Documentation
MSTLLogicControl() [1/2]
MSTLLogicControl::MSTLLogicControl ()
Constructor.
Definition at line 547 of file MSTLLogicControl.cpp.
~MSTLLogicControl()
MSTLLogicControl::~MSTLLogicControl ()
Destructor.
Definition at line 551 of file MSTLLogicControl.cpp.
References myLogics, and myWAUTs.
MSTLLogicControl() [2/2]
MSTLLogicControl::MSTLLogicControl (const MSTLLogicControl &) private
Invalidated copy constructor.
Member Function Documentation
add()
bool MSTLLogicControl::add (const std::string & id, const std::string & programID, MSTrafficLightLogic * logic, bool newDefault = true)
Adds a tls program to the container.
If a tls with the given id is not yet known, a TLSLogicVariants structure is built for this tls and added to the internal container and the tls program is used as the new default.
If the tls to add is loaded from an additional file (indicated by myNetWasLoaded, see closeNetworkReading), links from previously loaded tls are adapted to the logic. This may throw a ProcessError in the case no tls program was loaded for this tls before (was not defined in the network).
The parameter newDefault defines whether this program will be used as the new default program of this tls. This means that an existing tls program for this tls is replaced within the according TLSLogicVariants structure.
Parameters
[in] id The id of the tls (program) to add
[in] programID The program id of the tls (program) to add
[in] logic The tls logic to insert
Exceptions
ProcessError In the case an additional tls program is loaded and no one for the tls existed in the network
Returns
true if the tls program could be added, false otherwise
Definition at line 613 of file MSTLLogicControl.cpp.
References MSTLLogicControl::TLSLogicVariants::addLogic(), myLogics, and myNetWasLoaded.
addWAUT()
void MSTLLogicControl::addWAUT (SUMOTime refTime, const std::string & id, const std::string & startProg)
Adds a WAUT definition.
Throws an InvalidArgument if the given id is already in use.
Parameters
[in] refTime The reference time of the WAUT
[in] id The ID of the WAUT
[in] startProg The begin program of the WAUT
Exceptions
InvalidArgument If the id is already used by another WAUT
Definition at line 679 of file MSTLLogicControl.cpp.
References MSTLLogicControl::WAUT::id, myWAUTs, MSTLLogicControl::WAUT::refTime, and MSTLLogicControl::WAUT::startProg.
Referenced by NLHandler::openWAUT().
addWAUTJunction()
void MSTLLogicControl::addWAUTJunction (const std::string & wautid, const std::string & tls, const std::string & proc, bool synchron)
Adds a tls to the list of tls to be switched by the named WAUT.
Passes the values directly to the used tls control. This throws an InvalidArgument if the given WAUT id or the given junction id is not known.
Parameters
[in] wautid The ID of the WAUT
[in] tls The id of the tls to be switched
[in] proc The switching procedure to use
[in] synchron Whether the switching shall be done in synchron mode
Exceptions
InvalidArgument If the named WAUT or the named tls are not known
ProcessError If the initial switch fails
Definition at line 711 of file MSTLLogicControl.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSTLLogicControl::WAUTJunction::junction, myLogics, myWAUTs, MSTLLogicControl::WAUTJunction::procedure, switchTo(), and MSTLLogicControl::WAUTJunction::synchron.
Referenced by NLHandler::addWAUTJunction().
addWAUTSwitch()
void MSTLLogicControl::addWAUTSwitch (const std::string & wautid, SUMOTime when, const std::string & to)
Adds a WAUT switch step to a previously built WAUT.
Throws an InvalidArgument if the given WAUT id is not known.
Parameters
[in] wautid The ID of the WAUT
[in] when The switch procedure begin
[in] to The program the WAUT shall start to switch to at the given time
Exceptions
InvalidArgument If the named WAUT is not known
Definition at line 695 of file MSTLLogicControl.cpp.
References myWAUTs, MSTLLogicControl::WAUTSwitch::to, and MSTLLogicControl::WAUTSwitch::when.
Referenced by NLHandler::addWAUTSwitch().
check2Switch()
void MSTLLogicControl::check2Switch (SUMOTime step)
Checks whether any WAUT is trying to switch a tls into another program.
Called from MSNet::simulationStep
Definition at line 818 of file MSTLLogicControl.cpp.
References myCurrentlySwitched, MSTLLogicControl::WAUTSwitchProcess::proc, switchTo(), and MSTLLogicControl::WAUTSwitchProcedure::trySwitch().
Referenced by MSNet::simulationStep().
closeNetworkReading()
bool MSTLLogicControl::closeNetworkReading ()
Lets MSTLLogicControl know that the network has been loaded.
This method must be called after the network (including the initial tls definitions) was loaded.
The originally loaded traffic lights are also verified herein by calling TLSLogicVariants::checkOriginalTLS, first.
The MSTLLogicControl is informed in order to know that link information is known for the tls programs loaded afterwards so that it may be adapted from the previously loaded tls (a net may only contain one program per tls).
The states of the links controlled by tls are saved for their potential later usage (if the tls is switched to off-mode).
Returns
Whether the traffic lights could be initialised and are correct
Definition at line 635 of file MSTLLogicControl.cpp.
References myLogics, and myNetWasLoaded.
Referenced by NLJunctionControlBuilder::buildTLLogics().
closeWAUT()
void MSTLLogicControl::closeWAUT (const std::string & wautid)
Closes loading of a WAUT.
Instantiates the first switch ("SwitchInitCommand") for the WAUT into the network's simulation time step begin event control. Throws an InvalidArgument if the given WAUT id is not known.
Parameters
[in] wautid The ID of the WAUT
Exceptions
InvalidArgument If the named WAUT is not known
See also
SwitchInitCommand
Definition at line 749 of file MSTLLogicControl.cpp.
References MSEventControl::addEvent(), MSNet::getBeginOfTimestepEvents(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), myWAUTs, and MSTLLogicControl::WAUT::switches.
Referenced by NLHandler::closeWAUT().
get() [1/2]
MSTLLogicControl::TLSLogicVariants & MSTLLogicControl::get (const std::string & id) const
Returns the variants of a named tls.
Parameters
[in] id The id of the tls to get variants of
Returns
The variants of the named tls
Exceptions
InvalidArgument
Definition at line 583 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSTrafficLightLogic::SwitchCommand::execute(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLJunctionControlBuilder::getTLLogic(), libsumo::TrafficLight::getTLS(), NLHandler::initTrafficLightLogic(), GUIViewTraffic::onGamingClick(), TraCIServerAPI_TrafficLight::processGet(), GUITrafficLightLogicWrapper::switchTLSLogic(), and MSFullExport::writeTLS().
get() [2/2]
MSTrafficLightLogic * MSTLLogicControl::get (const std::string & id, const std::string & programID) const
Returns a single program (variant) defined by the tls id and the program programID.
Parameters
[in] id The id of the tls to get program of
[in] programID The program id of the tls program to get
Returns
The defined tls program if existing, 0 otherwise
Definition at line 593 of file MSTLLogicControl.cpp.
References myLogics.
getActive()
MSTrafficLightLogic * MSTLLogicControl::getActive (const std::string & id) const
Returns the active program of a named tls.
Parameters
[in] id The id of the tls to get the active program of
Returns
The current program of the defined tls if existing, 0 otherwise
Definition at line 657 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by GUINet::getLinkTLID(), GUINet::getLinkTLIndex(), getPhaseDef(), GUITrafficLightLogicWrapper::getPopUpMenu(), and GUITrafficLightLogicWrapper::switchTLSLogic().
getAllLogics()
std::vector< MSTrafficLightLogic * > MSTLLogicControl::getAllLogics () const
Returns a vector which contains all logics.
All logics are included, active (current) and non-active
Returns
A vector containing all loaded logics
Definition at line 572 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by GUINet::initTLMap(), and GUIViewTraffic::onGamingClick().
getAllTLIds()
std::vector< std::string > MSTLLogicControl::getAllTLIds () const
Returns the ids of all existing variants-structures, wich are the ids of their contained tls logics (not the logic's programm-ids)
Returns
the list of ids
Definition at line 603 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), libsumo::TrafficLight::getIDList(), and MSFullExport::writeTLS().
getPhaseDef()
std::pair< SUMOTime, MSPhaseDefinition > MSTLLogicControl::getPhaseDef (const std::string & tlid) const
return the complete phase definition for a named traffic lights logic
The phase definition will be the current of the currently active program of the named tls.
Parameters
[in] tlid The id of the tls to get the current phases of
Returns
A pair containing the current time and the current phases of the named tls
Definition at line 833 of file MSTLLogicControl.cpp.
References getActive(), MSTrafficLightLogic::getCurrentPhaseDef(), and MSNet::getInstance().
Referenced by GUITrafficLightLogicWrapper::begin2TrackPhases().
initWautSwitch()
SUMOTime MSTLLogicControl::initWautSwitch (MSTLLogicControl::SwitchInitCommand & cmd)
Initialises switching a WAUT.
This method is called from a previously built SwitchInitCommand
Parameters
[in] The command which initialises the switch
Returns
The time offset to next call
Definition at line 783 of file MSTLLogicControl.cpp.
References MSTLLogicControl::WAUTSwitchProcess::from, MSTLLogicControl::TLSLogicVariants::getActive(), MSNet::getCurrentTimeStep(), MSTLLogicControl::SwitchInitCommand::getIndex(), MSNet::getInstance(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSTLLogicControl::SwitchInitCommand::getWAUTID(), MSTLLogicControl::WAUTSwitchProcess::junction, myCurrentlySwitched, myLogics, myWAUTs, MSTLLogicControl::WAUTSwitchProcess::proc, MSTLLogicControl::WAUTSwitch::to, and MSTLLogicControl::WAUTSwitchProcess::to.
isActive()
bool MSTLLogicControl::isActive (const MSTrafficLightLogic * tl) const
Returns whether the given tls program is the currently active for his tls.
Parameters
[in] tl The tls to ask for
Returns
Whether the given tl is currently active (or a different program is used)
Definition at line 647 of file MSTLLogicControl.cpp.
References Named::getID(), and myLogics.
Referenced by MSTrafficLightLogic::SwitchCommand::execute(), and GUIViewTraffic::onGamingClick().
knows()
bool MSTLLogicControl::knows (const std::string & id) const
Returns the information whether the named tls is stored.
Parameters
[in] id The id of the tls to ask for
Returns
Whether a tls with the given id is known
Definition at line 625 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), and NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand().
operator=()
MSTLLogicControl& MSTLLogicControl::operator= (const MSTLLogicControl &) private
Invalidated assignment operator.
setTrafficLightSignals()
void MSTLLogicControl::setTrafficLightSignals (SUMOTime t) const
Lets all running (current) tls programs apply their current signal states to links they control.
Parameters
[in] t The current time
See also
MSTrafficLightLogic::setTrafficLightSignals
LinkState
MSLink::setTLState
Definition at line 564 of file MSTLLogicControl.cpp.
References myLogics.
switchOffAll()
void MSTLLogicControl::switchOffAll ()
switch all logic variants to 'off'
Definition at line 840 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by NLBuilder::build().
switchTo()
void MSTLLogicControl::switchTo (const std::string & id, const std::string & programID)
Switches the named (id) tls to the named (programID) program.
The program with the used programID must be previously added. If the tls itself or the program to switch to is not known, false is returned.
Parameters
[in] id The id of the tls to switch to
[in] programID The program id of the tls (program) to switch to
Exceptions
ProcessError If either the tls or the program to switch to is not known
Definition at line 667 of file MSTLLogicControl.cpp.
References myLogics.
Referenced by addWAUTJunction(), check2Switch(), GUIViewTraffic::onGamingClick(), and GUITrafficLightLogicWrapper::switchTLSLogic().
Field Documentation
myCurrentlySwitched
std::vector<WAUTSwitchProcess> MSTLLogicControl::myCurrentlySwitched protected
A list of currently running switching procedures.
Definition at line 815 of file MSTLLogicControl.h.
Referenced by check2Switch(), and initWautSwitch().
myLogics
std::map<std::string, TLSLogicVariants*> MSTLLogicControl::myLogics protected
A map from ids to the corresponding variants.
Definition at line 818 of file MSTLLogicControl.h.
Referenced by add(), addWAUTJunction(), closeNetworkReading(), get(), getActive(), getAllLogics(), getAllTLIds(), initWautSwitch(), isActive(), knows(), setTrafficLightSignals(), switchOffAll(), switchTo(), and ~MSTLLogicControl().
myNetWasLoaded
bool MSTLLogicControl::myNetWasLoaded protected
Information whether the net was completely loaded.
Definition at line 821 of file MSTLLogicControl.h.
Referenced by add(), and closeNetworkReading().
myWAUTs
std::map<std::string, WAUT*> MSTLLogicControl::myWAUTs protected
A map of ids to corresponding WAUTs.
Definition at line 812 of file MSTLLogicControl.h.
Referenced by addWAUT(), addWAUTJunction(), addWAUTSwitch(), closeWAUT(), initWautSwitch(), and ~MSTLLogicControl().
The documentation for this class was generated from the following files:
MSTLLogicControl.h
MSTLLogicControl.cpp