SUMO - Simulation of Urban MObility: NBTrafficLightLogic::PhaseDefinition Class Reference
NBTrafficLightLogic::PhaseDefinition Class Reference
The definition of a single phase of the logic.
#include <NBTrafficLightLogic.h>
Public Member Functions
bool operator!= (const PhaseDefinition &pd) const
Comparison operator.
PhaseDefinition (SUMOTime durationArg, const std::string &stateArg, SUMOTime minDurArg, SUMOTime maxDurArg)
Constructor.
~PhaseDefinition ()
Destructor.
Data Fields
SUMOTime duration
The duration of the phase in s.
SUMOTime maxDur
SUMOTime minDur
std::string state
The state definition.
Detailed Description
The definition of a single phase of the logic.
Definition at line 64 of file NBTrafficLightLogic.h.
Constructor & Destructor Documentation
PhaseDefinition()
NBTrafficLightLogic::PhaseDefinition::PhaseDefinition (SUMOTime durationArg, const std::string & stateArg, SUMOTime minDurArg, SUMOTime maxDurArg) inline
Constructor.
Parameters
[in] durationArg The duration of the phase
[in] stateArg Signals per link
Definition at line 78 of file NBTrafficLightLogic.h.
~PhaseDefinition()
NBTrafficLightLogic::PhaseDefinition::~PhaseDefinition () inline
Destructor.
Definition at line 85 of file NBTrafficLightLogic.h.
Member Function Documentation
operator!=()
bool NBTrafficLightLogic::PhaseDefinition::operator!= (const PhaseDefinition & pd) const inline
Comparison operator.
Parameters
[in] pd A second phase
Returns
Whether this and the given phases are same
Definition at line 91 of file NBTrafficLightLogic.h.
References NBTrafficLightLogic::addStep(), NBTrafficLightLogic::closeBuilding(), NBTrafficLightLogic::deletePhase(), duration, NBTrafficLightLogic::getDuration(), LINKSTATE_TL_RED, maxDur, minDur, NBTrafficLightLogic::NBTrafficLightLogic(), NBTrafficLightLogic::resetPhases(), NBTrafficLightLogic::setPhaseDuration(), NBTrafficLightLogic::setPhaseMaxDuration(), NBTrafficLightLogic::setPhaseMinDuration(), NBTrafficLightLogic::setPhaseState(), NBTrafficLightLogic::setStateLength(), state, TLTYPE_STATIC, and NBTrafficLightLogic::~NBTrafficLightLogic().
Field Documentation
duration
SUMOTime NBTrafficLightLogic::PhaseDefinition::duration
The duration of the phase in s.
Definition at line 67 of file NBTrafficLightLogic.h.
Referenced by operator!=().
maxDur
SUMOTime NBTrafficLightLogic::PhaseDefinition::maxDur
Definition at line 69 of file NBTrafficLightLogic.h.
Referenced by operator!=().
minDur
SUMOTime NBTrafficLightLogic::PhaseDefinition::minDur
Definition at line 68 of file NBTrafficLightLogic.h.
Referenced by operator!=().
state
std::string NBTrafficLightLogic::PhaseDefinition::state
The state definition.
Definition at line 72 of file NBTrafficLightLogic.h.
Referenced by GNETLSEditorFrame::onCmdPhaseSwitch(), and operator!=().
The documentation for this class was generated from the following file:
NBTrafficLightLogic.h