SUMO - Simulation of Urban MObility: MSLane::outgoing_lane_priority_sorter Class Reference
MSLane::outgoing_lane_priority_sorter Class Reference
Sorts lanes (their origin link) by the priority of their noninternal target edges or, if this doesn't yield an unambiguous result, wrt. the angle difference magnitude relative to the target lane's angle (straight comes first)
Public Member Functions
int operator() (const MSLink *link1, const MSLink *link2) const
comparing operator
outgoing_lane_priority_sorter (const MSLane *sourceLane)
constructor
Private Member Functions
outgoing_lane_priority_sorter & operator= (const outgoing_lane_priority_sorter &)
Private Attributes
const MSLane *const myLane
double myLaneDir
Detailed Description
Sorts lanes (their origin link) by the priority of their noninternal target edges or, if this doesn't yield an unambiguous result, wrt. the angle difference magnitude relative to the target lane's angle (straight comes first)
Definition at line 1373 of file MSLane.h.
Constructor & Destructor Documentation
outgoing_lane_priority_sorter()
MSLane::outgoing_lane_priority_sorter::outgoing_lane_priority_sorter (const MSLane * sourceLane) explicit
constructor
Definition at line 2683 of file MSLane.cpp.
Member Function Documentation
operator()()
int MSLane::outgoing_lane_priority_sorter::operator() (const MSLink * link1, const MSLink * link2) const
comparing operator
Definition at line 2688 of file MSLane.cpp.
References PositionVector::angleAt2D(), GeomHelper::angleDiff(), MSLane::getEdge(), Named::getID(), MSLink::getLane(), MSEdge::getPriority(), MSLane::getShape(), myLane, and myLaneDir.
operator=()
outgoing_lane_priority_sorter& MSLane::outgoing_lane_priority_sorter::operator= (const outgoing_lane_priority_sorter &) private
Field Documentation
myLane
const MSLane* const MSLane::outgoing_lane_priority_sorter::myLane private
Definition at line 1384 of file MSLane.h.
Referenced by operator()().
myLaneDir
double MSLane::outgoing_lane_priority_sorter::myLaneDir private
Definition at line 1385 of file MSLane.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
MSLane.h
MSLane.cpp