SUMO - Simulation of Urban MObility: MSLane Class Reference
MSLane Class Reference
Representation of a lane in the micro simulation.
#include <MSLane.h>
Data Structures
class AnyVehicleIterator
AnyVehicleIterator is a structure, which manages the iteration through all vehicles on the lane, that may be of importance for the car-following dynamics along that lane. The relevant types of vehicles are: 1) vehicles with their front on the lane (myVehicles), 2) vehicles intersecting the lane but with front on another lane (myPartialVehicles)
class by_connections_to_sorter
Sorts edges by their angle relative to the given edge (straight comes first)
class edge_finder
class incoming_lane_priority_sorter
Sorts lanes (IncomingLaneInfos) by their priority or, if this doesn't apply, wrt. the angle difference magnitude relative to the target lane's angle (straight comes first)
struct IncomingLaneInfo
class outgoing_lane_priority_sorter
Sorts lanes (their origin link) by the priority of their noninternal target edges or, if this doesn't yield an unambiguous result, wrt. the angle difference magnitude relative to the target lane's angle (straight comes first)
class vehicle_natural_position_sorter
class vehicle_position_sorter
Sorts vehicles by their position (descending)
struct VehPosition
Public Types
enum CollisionAction { COLLISION_ACTION_NONE, COLLISION_ACTION_WARN, COLLISION_ACTION_TELEPORT, COLLISION_ACTION_REMOVE }
typedef std::vector< MSVehicle * > VehCont
Container for vehicles.
Public Member Functions
void addApproachingLane (MSLane *lane, bool warnMultiCon)
void addIncomingLane (MSLane *lane, MSLink *viaLink)
void addParking (MSVehicle *veh)
add parking vehicle. This should only used during state loading
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool allowsVehicleClass (SUMOVehicleClass vclass) const
virtual bool appropriate (const MSVehicle *veh)
void clearParameter ()
Clears the parameter map.
virtual void detectCollisions (SUMOTime timestep, const std::string &stage)
Check if vehicles are too close.
bool empty () const
Returns true if there is not a single vehicle on the lane.
void enteredByLaneChange (MSVehicle *v)
MSLane * getCanonicalPredecessorLane () const
MSLane * getCanonicalSuccessorLane () const
double getCenterOnEdge () const
std::pair< MSVehicle *const, double > getCriticalLeader (double dist, double seen, double speed, const MSVehicle &veh) const
Returns the most dangerous leader and the distance to him.
int getCrossingIndex () const
return the index of the link to the next crossing if this is walkingArea, else -1
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
MSEdge & getEdge () const
Returns the lane's edge.
MSLink * getEntryLink () const
Returns the entry link if this is an internal lane, else 0.
MSVehicle * getFirstAnyVehicle () const
returns the first vehicle that is fully or partially on this lane
MSVehicle * getFirstFullVehicle () const
returns the first vehicle for which this lane is responsible or 0
const MSLane * getFirstInternalInConnection (double &offset) const
Returns 0 if the lane is not internal. Otherwise the first part of the connection (sequence of internal lanes along junction) corresponding to the lane is returned and the offset is set to the distance of the begin of this lane to the begin of the returned.
std::pair< MSVehicle *const, double > getFollower (const MSVehicle *ego, double egoPos, double dist, bool ignoreMinorLinks) const
Find follower vehicle for the given ego vehicle (which may be on the opposite direction lane)
MSLeaderDistanceInfo getFollowersOnConsecutive (const MSVehicle *ego, double backOffset, bool allSublanes, double searchDist=-1, bool ignoreMinorLinks=false) const
return the sublane followers with the largest missing rear gap among all predecessor lanes (within dist)
const std::string & getID () const
Returns the id.
const std::vector< IncomingLaneInfo > & getIncomingLanes () const
LinkState getIncomingLinkState () const
get the state of the link from the logical predecessor to this lane
MSVehicle * getLastAnyVehicle () const
returns the last vehicle that is fully or partially on this lane
MSVehicle * getLastFullVehicle () const
returns the last vehicle for which this lane is responsible or 0
std::pair< MSVehicle *const, double > getLeader (const MSVehicle *veh, const double vehPos, const std::vector< MSLane *> &bestLaneConts, double dist=-1, bool checkTmpVehicles=false) const
Returns the immediate leader of veh and the distance to veh starting on this lane.
std::pair< MSVehicle *const, double > getLeaderOnConsecutive (double dist, double seen, double speed, const MSVehicle &veh, const std::vector< MSLane *> &bestLaneConts) const
Returns the immediate leader and the distance to him.
void getLeadersOnConsecutive (double dist, double seen, double speed, const MSVehicle *ego, const std::vector< MSLane *> &bestLaneConts, MSLeaderDistanceInfo &result) const
Returns the immediate leaders and the distance to them (as getLeaderOnConsecutive but for the sublane case)
const MSLinkCont & getLinkCont () const
returns the container with all links !!!
MSLink * getLinkTo (const MSLane *) const
returns the link to the given lane or 0, if it is not connected
MSLane * getLogicalPredecessorLane () const
get the most likely precedecessor lane (sorted using by_connections_to_sorter). The result is cached in myLogicalPredecessorLane
MSLane * getLogicalPredecessorLane (const MSEdge &fromEdge) const
return the (first) predecessor lane from the given edge
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
double getMissingRearGap (const MSVehicle *leader, double backOffset, double leaderSpeed) const
return by how much further the leader must be inserted to avoid rear end collisions
const MSEdge * getNextNormal () const
Returns the lane's follower if it is an internal lane, the edge of the lane otherwise.
MSLane * getOpposite () const
return the opposite direction lane for lane changing or 0
std::pair< MSVehicle *const, double > getOppositeFollower (const MSVehicle *ego) const
std::pair< MSVehicle *const, double > getOppositeLeader (const MSVehicle *ego, double dist, bool oppositeDir) const
double getOppositePos (double pos) const
return the corresponding position on the opposite lane
std::vector< const MSLane * > getOutgoingLanes () const
get the list of outgoing lanes
MSLane * getParallelLane (int offset) const
Returns the lane with the given offset parallel to this one or 0 if it does not exist.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
const std::set< const MSVehicle * > & getParkingVehicles () const
retrieve the parking vehicles (see GUIParkingArea)
MSVehicle * getPartialBehind (const MSVehicle *ego) const
MSLeaderInfo getPartialBeyond () const
get all vehicles that are inlapping from consecutive edges
int getRightmostSublane () const
double getRightSideOnEdge () const
void initRestrictions ()
initialized vClass-specific speed limits
bool isApproachedFrom (MSEdge *const edge)
bool isApproachedFrom (MSEdge *const edge, MSLane *const lane)
bool isEmpty () const
bool isInternal () const
bool isLinkEnd (MSLinkCont::const_iterator &i) const
bool isLinkEnd (MSLinkCont::iterator &i)
virtual bool isSelected () const
whether this lane is selected in the GUI
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void leftByLaneChange (MSVehicle *v)
MSLane (const std::string &id, double maxSpeed, double length, MSEdge *const edge, int numericalID, const PositionVector &shape, double width, SVCPermissions permissions, int index, bool isRampAccel)
Constructor.
virtual void removeParking (MSVehicle *veh)
remove parking vehicle. This must be syncrhonized when running with GUI
virtual MSVehicle * removeVehicle (MSVehicle *remVehicle, MSMoveReminder::Notification notification, bool notify=true)
void resetPermissions (long transientID)
void setID (const std::string &newID)
resets the id
void setLength (double val)
Sets a new length for the lane (used by TraCI only)
void setMaxSpeed (double val)
Sets a new maximum speed for the lane (used by TraCI and MSCalibrator)
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void setPermissions (SVCPermissions permissions, long transientID)
Sets the permissions to the given value. If a transientID is given, the permissions are recored as temporary.
void setRightSideOnEdge (double value, int rightmostSublane)
void sortManeuverReservations ()
sorts myManeuverReservations
void sortPartialVehicles ()
sorts myPartialVehicles
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void visit (const LaneStoringVisitor &cont) const
Callback for visiting the lane when traversing an RTree.
void writeParams (OutputDevice &out) const
virtual ~MSLane ()
Destructor.
Additional initialisation
void addLink (MSLink *link)
Delayed initialization.
void addNeigh (const std::string &id)
Adds a neighbor to this lane.
interaction with MSMoveReminder
virtual void addMoveReminder (MSMoveReminder *rem)
Add a move-reminder to move-reminder container.
const std::vector< MSMoveReminder *> & getMoveReminders () const
Return the list of this lane's move reminders.
Vehicle insertion
bool insertVehicle (MSVehicle &v)
Tries to insert the given vehicle.
bool isInsertionSuccess (MSVehicle *vehicle, double speed, double pos, double posLat, bool recheckNextLanes, MSMoveReminder::Notification notification)
Tries to insert the given vehicle with the given state (speed and pos)
bool checkFailure (const MSVehicle *aVehicle, double &speed, double &dist, const double nspeed, const bool patchSpeed, const std::string errorMsg) const
bool lastInsertion (MSVehicle &veh, double mspeed, double posLat, bool patchSpeed)
inserts vehicle as close as possible to the last vehicle on this lane (or at the end of the lane if there is no leader)
bool freeInsertion (MSVehicle &veh, double speed, double posLat, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle on any place.
void forceVehicleInsertion (MSVehicle *veh, double pos, MSMoveReminder::Notification notification, double posLat=0)
Inserts the given vehicle at the given position.
Handling vehicles lapping into several lanes (-> partial occupation)
or which committed a maneuver that will lead them into another (sublane case -> maneuver reservations)
virtual double setPartialOccupation (MSVehicle *v)
Sets the information about a vehicle lapping into this lane.
virtual void resetPartialOccupation (MSVehicle *v)
Removes the information about a vehicle lapping into this lane.
virtual void setManeuverReservation (MSVehicle *v)
Registers the lane change intentions (towards this lane) for the given vehicle.
virtual void resetManeuverReservation (MSVehicle *v)
Unregisters a vehicle, which previously registered for maneuvering into this lane.
const MSLeaderInfo & getLastVehicleInformation (const MSVehicle *ego, double latOffset, double minPos=0, bool allowCached=true) const
Returns the last vehicles on the lane.
const MSLeaderInfo & getFirstVehicleInformation (const MSVehicle *ego, double latOffset, bool onlyFrontOnLane, double maxPos=std::numeric_limits< double >::max(), bool allowCached=true) const
analogue to getLastVehicleInformation but in the upstream direction
Access to vehicles
int getVehicleNumber () const
Returns the number of vehicles on this lane (for which this lane is responsible)
int getVehicleNumberWithPartials () const
Returns the number of vehicles on this lane (including partial occupators)
int getPartialVehicleNumber () const
Returns the number of vehicles partially on this lane (for which this lane is not responsible)
virtual const VehCont & getVehiclesSecure () const
Returns the vehicles container; locks it for microsimulation.
AnyVehicleIterator anyVehiclesBegin () const
begin iterator for iterating over all vehicles touching this lane in downstream direction
AnyVehicleIterator anyVehiclesEnd () const
end iterator for iterating over all vehicles touching this lane in downstream direction
AnyVehicleIterator anyVehiclesUpstreamBegin () const
begin iterator for iterating over all vehicles touching this lane in upstream direction
AnyVehicleIterator anyVehiclesUpstreamEnd () const
end iterator for iterating over all vehicles touching this lane in upstream direction
virtual void releaseVehicles () const
Allows to use the container for microsimulation again.
Atomar value getter
int getNumericalID () const
Returns this lane's numerical id.
const PositionVector & getShape () const
Returns this lane's shape.
double getLengthGeometryFactor () const
return shape.length() / myLength
bool isAccelLane () const
return whether this lane is an acceleration lane
double interpolateLanePosToGeometryPos (double lanePos) const
const Position geometryPositionAtOffset (double offset, double lateralOffset=0) const
double interpolateGeometryPosToLanePos (double geometryPos) const
double getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
double getSpeedLimit () const
Returns the lane's maximum allowed speed.
double getLength () const
Returns the lane's length.
SVCPermissions getPermissions () const
Returns the vehicle class permissions for this lane.
double getWidth () const
Returns the lane's width.
int getIndex () const
Returns the lane's index.
Vehicle movement (longitudinal)
virtual void planMovements (const SUMOTime t)
Compute safe velocities for all vehicles based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
void updateLeaderInfo (const MSVehicle *veh, VehCont::reverse_iterator &vehPart, VehCont::reverse_iterator &vehRes, MSLeaderInfo &ahead) const
This updates the MSLeaderInfo argument with respect to the given MSVehicle. All leader-vehicles on the same edge, which are relevant for the vehicle (i.e. with position > vehicle's position) and not already integrated into the LeaderInfo, are integrated. The given iterators vehPart and vehRes give access to these vehicles which are either partial occupators or have issued a maneuver reservation for the lane (the latter occurs only for the sublane model).
virtual bool executeMovements (SUMOTime t, std::vector< MSLane *> &lanesWithVehiclesToIntegrate)
Executes planned vehicle movements with regards to right-of-way.
virtual bool integrateNewVehicle (SUMOTime t)
Insert buffered vehicle into the real lane.
Current state retrieval
double getMeanSpeed () const
Returns the mean speed on this lane.
double getWaitingSeconds () const
Returns the overall waiting time on this lane.
double getBruttoOccupancy () const
Returns the brutto (including minGaps) occupancy of this lane during the last step.
double getNettoOccupancy () const
Returns the netto (excluding minGaps) occupancy of this lane during the last step (including minGaps)
double getBruttoVehLenSum () const
Returns the sum of lengths of vehicles, including their minGaps, which were on the lane during the last step.
double getCO2Emissions () const
Returns the sum of last step CO2 emissions.
double getCOEmissions () const
Returns the sum of last step CO emissions.
double getPMxEmissions () const
Returns the sum of last step PMx emissions.
double getNOxEmissions () const
Returns the sum of last step NOx emissions.
double getHCEmissions () const
Returns the sum of last step HC emissions.
double getFuelConsumption () const
Returns the sum of last step fuel consumption.
double getElectricityConsumption () const
Returns the sum of last step electricity consumption.
double getHarmonoise_NoiseEmissions () const
Returns the sum of last step noise emissions.
State saving/loading
void saveState (OutputDevice &out)
Saves the state of this lane into the given stream.
void loadState (std::vector< std::string > &vehIDs, MSVehicleControl &vc)
Loads the state of this segment with the given parameters.
Static Public Member Functions
static void clear ()
Clears the dictionary.
static bool dictionary (const std::string &id, MSLane *lane)
Static (sic!) container methods {.
static MSLane * dictionary (const std::string &id)
Returns the MSLane associated to the key id.
static int dictSize ()
Returns the number of stored lanes.
template<class RTREE >
static void fill (RTREE &into)
Fills the given RTree with lane instances.
static CollisionAction getCollisionAction ()
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void initCollisionOptions (const OptionsCont &oc)
static void insertIDs (std::vector< std::string > &into)
Adds the ids of all stored lanes into the given vector.
static MSLinkCont::const_iterator succLinkSec (const SUMOVehicle &veh, int nRouteSuccs, const MSLane &succLinkSource, const std::vector< MSLane *> &conts)
static bool teleportOnCollision ()
Static Public Attributes
static const long CHANGE_PERMISSIONS_GUI = 1
static const long CHANGE_PERMISSIONS_PERMANENT = 0
Protected Types
typedef std::map< std::string, MSLane *> DictType
definition of the static dictionary type
Protected Member Functions
double basePos (const MSVehicle &veh) const
departure position where the vehicle fits fully onto the lane (if possible)
bool checkForPedestrians (const MSVehicle *aVehicle, double &speed, double &dist, double pos, bool patchSpeed) const
check whether pedestrians on this lane interfere with vehicle insertion
bool detectCollisionBetween (SUMOTime timestep, const std::string &stage, MSVehicle *collider, MSVehicle *victim, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > &toRemove, std::set< const MSVehicle *> &toTeleport) const
detect whether there is a collision between the two vehicles
void detectPedestrianJunctionCollision (const MSVehicle *collider, const PositionVector &colliderBoundary, const MSLane *foeLane, SUMOTime timestep, const std::string &stage)
detect whether a vehicle collids with pedestrians on the junction
double getDepartPosLat (const MSVehicle &veh)
double getDepartSpeed (const MSVehicle &veh, bool &patchSpeed)
double getMaximumBrakeDist () const
compute maximum braking distance on this lane
void handleCollisionBetween (SUMOTime timestep, const std::string &stage, MSVehicle *collider, MSVehicle *victim, double gap, double latGap, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > &toRemove, std::set< const MSVehicle *> &toTeleport) const
take action upon collision
virtual void incorporateVehicle (MSVehicle *veh, double pos, double speed, double posLat, const MSLane::VehCont::iterator &at, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Inserts the vehicle into this lane, and informs it about entering the network.
double safeInsertionSpeed (const MSVehicle *veh, double seen, const MSLeaderInfo &leaders, double speed)
return the maximum safe speed for insertion behind leaders (a negative value indicates that safe insertion is impossible)
virtual void swapAfterLaneChange (SUMOTime t)
moves myTmpVehicles int myVehicles after a lane change procedure
Protected Attributes
std::map< MSEdge *, std::vector< MSLane * > > myApproachingLanes
All direct internal and direct (disregarding internal predecessors) non-internal predecessor lanes of this lane.
double myBruttoVehicleLengthSum
The current length of all vehicles on this lane, including their minGaps.
MSLane * myCanonicalPredecessorLane
Similar to LogicalPredecessorLane,.
MSLane * myCanonicalSuccessorLane
Main successor lane,.
MSEdge *const myEdge
The lane's edge, for routing only.
MSLeaderInfo myFollowerInfo
followers on all sublanes as seen by vehicles on consecutive lanes (cached)
SUMOTime myFollowerInfoTime
time step for which myFollowerInfo was last updated
std::string myID
The name of the object.
std::vector< IncomingLaneInfo > myIncomingLanes
All direct predecessor lanes.
int myIndex
The lane index.
const bool myIsRampAccel
whether this lane is an acceleration lane
MSLeaderInfo myLeaderInfo
leaders on all sublanes as seen by approaching vehicles (cached)
SUMOTime myLeaderInfoTime
time step for which myLeaderInfo was last updated
MSLeaderInfo myLeaderInfoTmp
double myLength
Lane length [m].
const double myLengthGeometryFactor
precomputed myShape.length / myLength
MSLinkCont myLinks
MSLane * myLogicalPredecessorLane
VehCont myManeuverReservations
The vehicles which registered maneuvering into the lane within their current action step. This is currently only relevant for sublane simulation, since continuous lanechanging uses the partial vehicle mechanism.
double myMaxSpeed
Lane-wide speedlimit [m/s].
std::vector< std::string > myNeighs
double myNettoVehicleLengthSum
The current length of all vehicles on this lane, excluding their minGaps.
int myNumericalID
Unique numerical ID (set on reading by netload)
SVCPermissions myOriginalPermissions
The original vClass permissions for this lane (before temporary modifications)
std::set< const MSVehicle * > myParkingVehicles
VehCont myPartialVehicles
The lane's partial vehicles. This container holds all vehicles that are partially on this lane but which are in myVehicles of another lane. Reasons for partial occupancies include the following.
std::map< long, SVCPermissions > myPermissionChanges
SVCPermissions myPermissions
The vClass permissions for this lane.
const std::map< SUMOVehicleClass, double > * myRestrictions
The vClass speed restrictions for this lane.
int myRightmostSublane
the index of the rightmost sublane of this lane on myEdge
double myRightSideOnEdge
the combined width of all lanes with lower index on myEdge
PositionVector myShape
The shape of the lane.
VehCont myTmpVehicles
Container for lane-changing vehicles. After completion of lane-change- process, the containers will be swapped with myVehicles.
VehCont myVehBuffer
Buffer for vehicles that moved from their previous lane onto this one. Integrated after all vehicles executed their moves.
VehCont myVehicles
The lane's vehicles. This container holds all vehicles that have their front (longitudinally) and their center (laterally) on this lane. These are the vehicles that this lane is 'responsibly' for (i.e. when executing movements)
const double myWidth
Lane width [m].
Static Protected Attributes
static DictType myDict
Static dictionary to associate string-ids with objects.
Private Member Functions
MSLane (const MSLane &)
invalidated copy constructor
MSLane & operator= (const MSLane &)
invalidated assignment operator
Private Attributes
std::vector< MSMoveReminder *> myMoveReminders
This lane's move reminder.
Static Private Attributes
static bool myCheckJunctionCollisions
static CollisionAction myCollisionAction
the action to take on collisions
static double myCollisionMinGapFactor
static SUMOTime myCollisionStopTime
Friends
class AnyVehicleIterator
class MSLaneChanger
needs access to myTmpVehicles (this maybe should be done via double-buffering!!!)
class MSLaneChangerSublane
class MSQueueExport
class MSXMLRawOut
Detailed Description
Representation of a lane in the micro simulation.
Class which represents a single lane. Somekind of the main class of the simulation. Allows moving vehicles.
Definition at line 77 of file MSLane.h.
Member Typedef Documentation
DictType
typedef std::map< std::string, MSLane* > MSLane::DictType protected
definition of the static dictionary type
Definition at line 1267 of file MSLane.h.
VehCont
typedef std::vector<MSVehicle*> MSLane::VehCont
Container for vehicles.
Definition at line 89 of file MSLane.h.
Member Enumeration Documentation
CollisionAction
enum MSLane::CollisionAction
Enumerator
COLLISION_ACTION_NONE
COLLISION_ACTION_WARN
COLLISION_ACTION_TELEPORT
COLLISION_ACTION_REMOVE
Definition at line 165 of file MSLane.h.
Constructor & Destructor Documentation
MSLane() [1/2]
MSLane::MSLane (const std::string & id, double maxSpeed, double length, MSEdge *const edge, int numericalID, const PositionVector & shape, double width, SVCPermissions permissions, int index, bool isRampAccel)
Constructor.
Parameters
[in] id The lane's id
[in] maxSpeed The speed allowed on this lane
[in] length The lane's length
[in] edge The edge this lane belongs to
[in] numericalID The numerical id of the lane
[in] shape The shape of the lane
[in] width The width of the lane
[in] permissions Encoding of the Vehicle classes that may drive on this lane
[in] index The index of this lane within its parent edge
[in] isRampAccel Whether this lane is an acceleratin lane
See also
SUMOVehicleClass
Definition at line 166 of file MSLane.cpp.
References initRestrictions().
~MSLane()
MSLane::~MSLane () virtual
Destructor.
Definition at line 192 of file MSLane.cpp.
References myLinks.
MSLane() [2/2]
MSLane::MSLane (const MSLane &) private
invalidated copy constructor
Member Function Documentation
addApproachingLane()
void MSLane::addApproachingLane (MSLane * lane, bool warnMultiCon)
Definition at line 1978 of file MSLane.cpp.
References getEdge(), Named::getID(), MSEdge::isInternal(), myApproachingLanes, and WRITE_WARNING.
Referenced by NLHandler::addConnection(), and getIncomingLanes().
addIncomingLane()
void MSLane::addIncomingLane (MSLane * lane, MSLink * viaLink)
Definition at line 1968 of file MSLane.cpp.
References getLength(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, myIncomingLanes, and MSLane::IncomingLaneInfo::viaLink.
Referenced by NLHandler::addConnection(), and allowsVehicleClass().
addLink()
void MSLane::addLink (MSLink * link)
Delayed initialization.
Not all lane-members are known at the time the lane is born, above all the pointers to other lanes, so we have to add them later.
Parameters
[in] link An outgoing link
Definition at line 206 of file MSLane.cpp.
References myLinks.
Referenced by NLHandler::addConnection().
addMoveReminder()
void MSLane::addMoveReminder (MSMoveReminder * rem) virtual
Add a move-reminder to move-reminder container.
The move reminder will not be deleted by the lane.
Parameters
[in] rem The move reminder to add
Definition at line 219 of file MSLane.cpp.
References myMoveReminders, and myVehicles.
Referenced by MSMoveReminder::MSMoveReminder().
addNeigh()
void MSLane::addNeigh (const std::string & id)
Adds a neighbor to this lane.
Parameters
[in] id The lane's id
Definition at line 212 of file MSLane.cpp.
References myNeighs.
addParking()
void MSLane::addParking (MSVehicle * veh)
add parking vehicle. This should only used during state loading
Definition at line 2723 of file MSLane.cpp.
References myParkingVehicles.
Referenced by getCenterOnEdge(), and MSVehicleTransfer::loadState().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
allowsVehicleClass()
bool MSLane::allowsVehicleClass (SUMOVehicleClass vclass) const inline
Definition at line 739 of file MSLane.h.
References addIncomingLane(), and myPermissions.
Referenced by MSVehicle::addStop(), MSEdge::allowedLanes(), MSPModel_NonInteracting::PState::getPosition(), MSVehicle::updateBestLanes(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
anyVehiclesBegin()
AnyVehicleIterator MSLane::anyVehiclesBegin () const inline
begin iterator for iterating over all vehicles touching this lane in downstream direction
Definition at line 398 of file MSLane.h.
References AnyVehicleIterator, myPartialVehicles, and myVehicles.
Referenced by detectCollisions(), getFollowersOnConsecutive(), getLastVehicleInformation(), getLeader(), MSLink::getLeaderInfo(), and MSPModel_Striping::moveInDirectionOnLane().
anyVehiclesEnd()
AnyVehicleIterator MSLane::anyVehiclesEnd () const inline
end iterator for iterating over all vehicles touching this lane in downstream direction
Definition at line 403 of file MSLane.h.
References AnyVehicleIterator, myPartialVehicles, and myVehicles.
Referenced by detectCollisions(), getFollowersOnConsecutive(), getLeader(), MSLink::getLeaderInfo(), and MSPModel_Striping::moveInDirectionOnLane().
anyVehiclesUpstreamBegin()
AnyVehicleIterator MSLane::anyVehiclesUpstreamBegin () const inline
begin iterator for iterating over all vehicles touching this lane in upstream direction
Definition at line 408 of file MSLane.h.
References AnyVehicleIterator, myPartialVehicles, and myVehicles.
Referenced by getFirstVehicleInformation(), getFollower(), and MSPModel_Striping::moveInDirectionOnLane().
anyVehiclesUpstreamEnd()
AnyVehicleIterator MSLane::anyVehiclesUpstreamEnd () const inline
end iterator for iterating over all vehicles touching this lane in upstream direction
Definition at line 413 of file MSLane.h.
References AnyVehicleIterator.
Referenced by getFollower(), and MSPModel_Striping::moveInDirectionOnLane().
appropriate()
bool MSLane::appropriate (const MSVehicle * veh) virtual
Returns the information whether this lane may be used to continue the current route
Definition at line 1697 of file MSLane.cpp.
References MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getLaneIndex(), MSEdge::isInternal(), myEdge, myLinks, MSBaseVehicle::succEdge(), and succLinkSec().
Referenced by executeMovements(), and getIndex().
basePos()
double MSLane::basePos (const MSVehicle & veh) const protected
departure position where the vehicle fits fully onto the lane (if possible)
Definition at line 559 of file MSLane.cpp.
References MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MIN2(), myLength, and POSITION_EPS.
Referenced by insertVehicle().
checkFailure()
bool MSLane::checkFailure (const MSVehicle * aVehicle, double & speed, double & dist, const double nspeed, const bool patchSpeed, const std::string errorMsg) const
Definition at line 564 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSInsertionControl::descheduleDeparture(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MIN2(), and WRITE_ERROR.
Referenced by checkForPedestrians(), getMoveReminders(), and isInsertionSuccess().
checkForPedestrians()
bool MSLane::checkForPedestrians (const MSVehicle * aVehicle, double & speed, double & dist, double pos, bool patchSpeed) const protected
check whether pedestrians on this lane interfere with vehicle insertion
Definition at line 3146 of file MSLane.cpp.
References checkFailure(), DEBUG_COND2, MSVehicle::getCarFollowModel(), getEdge(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSPModel::getModel(), MSVehicle::getRightSideOnLane(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSPModel::nextBlocking(), SIMTIME, and MSCFModel::stopSpeed().
Referenced by isInsertionSuccess().
clear()
void MSLane::clear () static
Clears the dictionary.
Definition at line 1662 of file MSLane.cpp.
References myDict.
Referenced by MSNet::clearAll(), and getEdge().
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
detectCollisionBetween()
bool MSLane::detectCollisionBetween (SUMOTime timestep, const std::string & stage, MSVehicle * collider, MSVehicle * victim, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > & toRemove, std::set< const MSVehicle *> & toTeleport) const protected
detect whether there is a collision between the two vehicles
Definition at line 1355 of file MSLane.cpp.
References COLLISION_ACTION_TELEPORT, DEBUG_COND, DEBUG_COND2, DELTA_T, MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getInfluencer(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, handleCollisionBetween(), MSVehicle::hasInfluencer(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::isOpposite(), MSVehicle::Influencer::isRemoteAffected(), myCollisionAction, myCollisionMinGapFactor, NUMERICAL_EPS, and SIMTIME.
Referenced by detectCollisions().
detectCollisions()
void MSLane::detectCollisions (SUMOTime timestep, const std::string & stage) virtual
Check if vehicles are too close.
Reimplemented in GUILane.
Definition at line 1157 of file MSLane.cpp.
References MSVehicleTransfer::add(), anyVehiclesBegin(), anyVehiclesEnd(), COLLISION_ACTION_NONE, DEBUG_COND, DEBUG_COND2, detectCollisionBetween(), detectPedestrianJunctionCollision(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicleTransfer::getInstance(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), getLastVehicleInformation(), MSVehicleType::getLength(), MSPModel::getModel(), MSEdge::getPersons(), MSVehicle::getPositionOnLane(), MSVehicle::getRightSideOnEdge(), getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, handleCollisionBetween(), MSPModel::hasPedestrians(), MSEdge::isInternal(), myCheckJunctionCollisions, myCollisionAction, myEdge, myLinks, myPartialVehicles, myVehicles, MSPModel::nextBlocking(), MSMoveReminder::NOTIFICATION_TELEPORT, MSMoveReminder::NOTIFICATION_VAPORIZED, MSLeaderInfo::numSublanes(), MSVehicle::onRemovalFromNet(), PositionVector::overlapsWith(), MSVehicleControl::registerCollision(), removeVehicle(), MSVehicleControl::scheduleVehicleRemoval(), SIMTIME, time2string(), toString(), and WRITE_WARNING.
Referenced by GUILane::detectCollisions(), and getIndex().
detectPedestrianJunctionCollision()
void MSLane::detectPedestrianJunctionCollision (const MSVehicle * collider, const PositionVector & colliderBoundary, const MSLane * foeLane, SUMOTime timestep, const std::string & stage) protected
detect whether a vehicle collids with pedestrians on the junction
Definition at line 1322 of file MSLane.cpp.
References DEBUG_COND, getEdge(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSPModel::getModel(), MSEdge::getPersons(), MSEdge::getSortedPersons(), MSNet::getVehicleControl(), MSPModel::hasPedestrians(), PositionVector::overlapsWith(), MSVehicleControl::registerCollision(), SIMTIME, time2string(), and WRITE_WARNING.
Referenced by detectCollisions().
dictionary() [1/2]
bool MSLane::dictionary (const std::string & id, MSLane * lane) static
Static (sic!) container methods {.
Inserts a MSLane into the static dictionary
Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Parameters
[in] id The id of the lane
[in] lane The lane itself
Returns
Whether the lane was added
Todo:
make non-static
why is the id given? The lane is named
Definition at line 1639 of file MSLane.cpp.
References myDict.
Referenced by NLHandler::addConnection(), NLHandler::addLane(), MSRouteHandler::addStop(), MSVehicle::addStop(), getEdge(), libsumo::Lane::getLane(), NLTriggerBuilder::getLane(), NLDetectorBuilder::getLaneChecking(), NLShapeHandler::getLanePos(), MSE2Collector::getLanes(), getOpposite(), TraCIServerAPI_Lane::getShape(), MSPedestrianPushButton::loadPushButtons(), MSVehicleTransfer::loadState(), libsumo::Vehicle::moveTo(), MSTriggeredRerouter::myStartElement(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLHandler::parseLanes(), TraCIServerAPI_Lane::processSet(), and MSE2Collector::recalculateDetectorLength().
dictionary() [2/2]
MSLane * MSLane::dictionary (const std::string & id) static
Returns the MSLane associated to the key id.
The lane is returned if exists, otherwise 0 is returned.
Parameters
[in] id The id of the lane
Returns
The lane
Definition at line 1651 of file MSLane.cpp.
References myDict.
dictSize()
static int MSLane::dictSize () inline static
Returns the number of stored lanes.
Returns
The number of stored lanes
Definition at line 658 of file MSLane.h.
References enteredByLaneChange(), fill(), getFirstAnyVehicle(), getFirstFullVehicle(), getLastAnyVehicle(), getLastFullVehicle(), getParallelLane(), insertIDs(), isEmpty(), isInternal(), isLinkEnd(), leftByLaneChange(), myDict, removeVehicle(), resetPermissions(), setPermissions(), and succLinkSec().
empty()
bool MSLane::empty () const inline
Returns true if there is not a single vehicle on the lane.
Definition at line 589 of file MSLane.h.
References myVehBuffer, myVehicles, setLength(), and setMaxSpeed().
Referenced by MSQueueExport::writeLane().
enteredByLaneChange()
void MSLane::enteredByLaneChange (MSVehicle * v)
Definition at line 2365 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), myBruttoVehicleLengthSum, and myNettoVehicleLengthSum.
Referenced by dictSize(), and MSAbstractLaneChangeModel::primaryLaneChanged().
executeMovements()
bool MSLane::executeMovements (SUMOTime t, std::vector< MSLane *> & lanesWithVehiclesToIntegrate) virtual
Executes planned vehicle movements with regards to right-of-way.
This method goes through all vehicles calling their executeMove method which causes vehicles to update their positions and speeds. Vehicles wich move to the next lane are stored in the targets lane buffer
Returns
Returns true, if all vehicles left the lane.
See also
MSVehicle::executeMove
Reimplemented in GUILane.
Definition at line 1507 of file MSLane.cpp.
References MSVehicleTransfer::add(), appropriate(), COLLISION_ACTION_REMOVE, COLLISION_ACTION_TELEPORT, MSVehicle::collisionStopTime(), DEBUG_COND2, MSVehicle::executeMove(), MSVehicle::getBestLanesContinuation(), getCollisionAction(), getEdge(), Named::getID(), MSBaseVehicle::getID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleType::getLength(), getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), getSpeedLimit(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingTime(), MSGlobals::gLateralResolution, MSGlobals::gTimeToGridlock, MSGlobals::gTimeToGridlockHighways, MSVehicle::hasArrived(), MSVehicle::isParking(), MSVehicle::isStopped(), MSEdge::isVaporizing(), myBruttoVehicleLengthSum, myLinks, myNettoVehicleLengthSum, myParkingVehicles, myVehBuffer, myVehicles, MSMoveReminder::NOTIFICATION_ARRIVED, MSMoveReminder::NOTIFICATION_VAPORIZED, MSVehicle::onRemovalFromNet(), MSVehicleControl::registerCollision(), MSVehicleControl::registerTeleportJam(), MSVehicleControl::registerTeleportWrongLane(), MSVehicleControl::registerTeleportYield(), MSVehicle::resumeFromStopping(), MSVehicleControl::scheduleVehicleRemoval(), SIMTIME, succLinkSec(), time2string(), and WRITE_WARNING.
Referenced by GUILane::executeMovements(), and getIndex().
fill()
template<class RTREE > template void MSLane::fill< LANE_RTREE_QUAL > (RTREE & into) static
Fills the given RTree with lane instances.
Parameters
Definition at line 1679 of file MSLane.cpp.
References PositionVector::getBoxBoundary(), getShape(), Boundary::grow(), LANE_RTREE_QUAL, myDict, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by libsumo::Helper::collectObjectsInRange(), dictSize(), and MSNet::getLanesRTree().
forceVehicleInsertion()
void MSLane::forceVehicleInsertion (MSVehicle * veh, double pos, MSMoveReminder::Notification notification, double posLat = 0)
Inserts the given vehicle at the given position.
No checks are done, vehicle insertion using this method may generate collisions (possibly delayed).
Parameters
[in] veh The vehicle to insert
[in] pos The position at which the vehicle shall be inserted
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
[in] posLat The lateral position at which the vehicle shall be inserted
Definition at line 940 of file MSLane.cpp.
References getDepartSpeed(), MSVehicle::getSpeed(), MSBaseVehicle::hasDeparted(), incorporateVehicle(), myVehicles, and MSVehicle::updateBestLanes().
Referenced by MSLaneChanger::changeOpposite(), getMoveReminders(), libsumo::Vehicle::moveTo(), and MSVehicle::Influencer::postProcessRemoteControl().
freeInsertion()
bool MSLane::freeInsertion (MSVehicle & veh, double speed, double posLat, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle on any place.
Parameters
[in] veh The vehicle to insert
[in] speed The maximum insertion speed
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns
Whether the vehicle could be inserted
Definition at line 345 of file MSLane.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), getFirstFullVehicle(), MSVehicleType::getLength(), getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), getMissingRearGap(), MSVehicle::getPositionOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), isInsertionSuccess(), MIN2(), myLength, myPartialVehicles, myVehicles, MSMoveReminder::NOTIFICATION_TELEPORT, POSITION_EPS, and MSVehicle::setTentativeLaneAndPosition().
Referenced by MSVehicleTransfer::checkInsertions(), getMoveReminders(), and insertVehicle().
geometryPositionAtOffset()
const Position MSLane::geometryPositionAtOffset (double offset, double lateralOffset = 0) const inline
Definition at line 461 of file MSLane.h.
References interpolateLanePosToGeometryPos(), myShape, and PositionVector::positionAtOffset().
Referenced by GUIE3Collector::MyWrapper::buildDefinition(), MSVehicle::computeAngle(), GUILane::debugDrawFoeIntersections(), GUIVehicle::drawAction_drawRailCarriages(), GUIEdge::drawMesoVehicles(), MSVehicle::getBackPosition(), NLShapeHandler::getLanePos(), MEVehicle::getPosition(), MSVehicle::getPosition(), MSVehicle::getPositionAlongBestLanes(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), and GUIInductLoop::MyWrapper::MyWrapper().
getBruttoOccupancy()
double MSLane::getBruttoOccupancy () const
Returns the brutto (including minGaps) occupancy of this lane during the last step.
Returns
The occupancy during the last step
Definition at line 2383 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MIN2(), myBruttoVehicleLengthSum, myLength, myPartialVehicles, myVehicles, and releaseVehicles().
Referenced by MSLCM_LC2013::_wantsChange(), GUILane::getColorValue(), getIncomingLanes(), GUILane::getParameterWindow(), GUILane::getScaleValue(), and MSEdge::insertVehicle().
getBruttoVehLenSum()
double MSLane::getBruttoVehLenSum () const inline
Returns the sum of lengths of vehicles, including their minGaps, which were on the lane during the last step.
Returns
The sum of vehicle lengths of vehicles in the last step
Definition at line 899 of file MSLane.h.
References getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getNOxEmissions(), getPMxEmissions(), and myBruttoVehicleLengthSum.
Referenced by MSVehicle::checkRewindLinkLanes().
getCanonicalPredecessorLane()
MSLane * MSLane::getCanonicalPredecessorLane () const
Return the main predecessor lane for the current. If there are several incoming lanes, the first attempt is to return the priorized. If this does not yield an unambiguous lane, the one with the least angle difference to the current is selected.
Definition at line 2295 of file MSLane.cpp.
References myCanonicalPredecessorLane, Named::myID, and myIncomingLanes.
Referenced by getEntryLink(), getFirstInternalInConnection(), getIncomingLanes(), MSRailSignal::init(), and MSE2Collector::selectLanes().
getCanonicalSuccessorLane()
MSLane * MSLane::getCanonicalSuccessorLane () const
Return the main successor lane for the current. If there are several outgoing lanes, the first attempt is to return the priorized. If this does not yield an unambiguous lane, the one with the least angle difference to the current is selected.
Definition at line 2315 of file MSLane.cpp.
References myCanonicalSuccessorLane, Named::myID, and myLinks.
Referenced by MSDevice_SSM::classifyEncounter(), getIncomingLanes(), and MSE2Collector::selectLanes().
getCenterOnEdge()
double MSLane::getCenterOnEdge () const inline
Definition at line 968 of file MSLane.h.
References addParking(), getFollower(), getOpposite(), getOppositeFollower(), getOppositeLeader(), getOppositePos(), myRightSideOnEdge, myWidth, removeParking(), sortManeuverReservations(), and sortPartialVehicles().
Referenced by MSVehicle::getCenterOnEdge(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
getCO2Emissions()
double MSLane::getCO2Emissions () const
Returns the sum of last step CO2 emissions.
Returns
CO2 emissions of vehicles on this lane during the last step
Definition at line 2442 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), libsumo::Lane::getCO2Emission(), GUILane::getColorValue(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getCOEmissions()
double MSLane::getCOEmissions () const
Returns the sum of last step CO emissions.
Returns
CO emissions of vehicles on this lane during the last step
Definition at line 2454 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), libsumo::Lane::getCOEmission(), GUILane::getColorValue(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getCollisionAction()
static CollisionAction MSLane::getCollisionAction () inline static
Definition at line 1069 of file MSLane.h.
References myCollisionAction.
Referenced by executeMovements(), and MSVehicle::resumeFromStopping().
getCriticalLeader()
std::pair< MSVehicle *const, double > MSLane::getCriticalLeader (double dist, double seen, double speed, const MSVehicle & veh) const
Returns the most dangerous leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the ego vehicle will pass it. If so, the subsequent lane is investigated. Check all lanes up to the stopping distance of ego. Return the leader vehicle (and the gap) which puts the biggest speed constraint on ego.
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Parameters
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The (ego) vehicle for which the information shall be computed
Returns
Definition at line 2193 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), getLastAnyVehicle(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpeed(), getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), isLinkEnd(), MAX2(), NUMERICAL_EPS, succLinkSec(), and TIME2STEPS.
Referenced by MSLaneChanger::checkChange(), and getIncomingLanes().
getCrossingIndex()
int MSLane::getCrossingIndex () const
return the index of the link to the next crossing if this is walkingArea, else -1
Definition at line 2372 of file MSLane.cpp.
References myLinks.
Referenced by getIndex().
getDepartPosLat()
double MSLane::getDepartPosLat (const MSVehicle & veh) protected
Definition at line 460 of file MSLane.cpp.
References DEPART_POS_DEFAULT, DEPART_POSLAT_CENTER, DEPART_POSLAT_GIVEN, DEPART_POSLAT_LEFT, DEPART_POSLAT_RANDOM, DEPART_POSLAT_RIGHT, SUMOVehicleParameter::departPosLat, SUMOVehicleParameter::departPosLatProcedure, MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), getWidth(), and RandHelper::rand().
Referenced by insertVehicle().
getDepartSpeed()
double MSLane::getDepartSpeed (const MSVehicle & veh, bool & patchSpeed) protected
Definition at line 433 of file MSLane.cpp.
References DEPART_SPEED_DEFAULT, DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSBaseVehicle::getParameter(), getVehicleMaxSpeed(), and RandHelper::rand().
Referenced by forceVehicleInsertion(), and insertVehicle().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getEdge()
MSEdge& MSLane::getEdge () const inline
Returns the lane's edge.
Returns
This lane's edge
Definition at line 607 of file MSLane.h.
References clear(), dictionary(), getFirstInternalInConnection(), getNextNormal(), and myEdge.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), LaneStoringVisitor::add(), addApproachingLane(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSEdge::allowedLanes(), MSSwarmTrafficLightLogic::allowLine(), MSSOTLE2Sensors::buildSensorForLane(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), checkForPedestrians(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSDevice_SSM::classifyEncounter(), MSEdge::closeBuilding(), GUILane::closeTraffic(), MSDevice_Tripinfo::computeLengthAndDuration(), MSLCM_SL2015::computeSpeedGain(), GUIDetectorBuilder::createInductLoop(), NLDetectorBuilder::createInductLoop(), detectPedestrianJunctionCollision(), MSLCM_LC2013::distanceAlongNextRoundabout(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSStoppingPlace::getAccessPos(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCenterOnEdge(), libsumo::Vehicle::getDistance(), MSVehicle::getDistanceToPosition(), libsumo::Vehicle::getDrivingDistance(), MSTransportable::Stage_Driving::getEdge(), libsumo::Lane::getEdgeID(), MSLinkContHelper::getInternalFollowingEdge(), MSEdge::getInternalFollowingEdge(), MSVehicle::getLaneIndex(), MSVehicle::getLatOffset(), MSLink::getLeaderInfo(), GUIVehicle::getLeftSublaneOnEdge(), getLogicalPredecessorLane(), MSPModel_Striping::PState::getNextEdge(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), libsumo::Vehicle::getNextTLS(), MSVehicle::getPosition(), GUIVehicle::getRightSublaneOnEdge(), libsumo::Vehicle::getRoadID(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSStoppingPlace::hasAccess(), MSVehicle::Influencer::implicitDeltaPosRemote(), MSVehicle::Influencer::implicitSpeedRemote(), MSVehicle::influenceChangeDecision(), MSRailSignal::init(), MSLink::isExitLink(), isInsertionSuccess(), MSJunction::isLeader(), MSLCM_SL2015::keepLatGap(), MSLink::lastWasContMajor(), MSVehicle::leaveLane(), MESegment::limitedControlOverride(), MSPedestrianPushButton::loadPushButtons(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveTo(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Helper::moveToXYMap(), MSTriggeredRerouter::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_SSM::notifyLeave(), GUIViewTraffic::onCmdAddRerouter(), GUIViewTraffic::onCmdCloseEdge(), MSLane::outgoing_lane_priority_sorter::operator()(), MSLane::edge_finder::operator()(), NLTriggerBuilder::parseAndBuildCalibrator(), MSRouteHandler::parseWalkPositions(), MSVehicle::passingMinor(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSInternalJunction::postloadInit(), MSLCM_SL2015::prepareStep(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSPModel_Striping::PState::PState(), MSVehicle::replaceRoute(), MSTriggeredRerouter::rerouteParkingArea(), MSVehicle::resumeFromStopping(), libsumo::Lane::setAllowed(), libsumo::Lane::setDisallowed(), MSLink::setRequestInformation(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSPModel_Striping::PState::walk(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSFCDExport::write().
getElectricityConsumption()
double MSLane::getElectricityConsumption () const
Returns the sum of last step electricity consumption.
Returns
electricity consumption of vehicles on this lane during the last step
Definition at line 2514 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), GUILane::getColorValue(), libsumo::Lane::getElectricityConsumption(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getEntryLink()
MSLink * MSLane::getEntryLink () const
Returns the entry link if this is an internal lane, else 0.
Definition at line 1902 of file MSLane.cpp.
References getCanonicalPredecessorLane(), getLinkTo(), and isInternal().
Referenced by MSDevice_SSM::classifyEncounter(), getIndex(), and MSLink::getLengthBeforeCrossing().
getFirstAnyVehicle()
MSVehicle * MSLane::getFirstAnyVehicle () const
returns the first vehicle that is fully or partially on this lane
Definition at line 1811 of file MSLane.cpp.
References MSVehicle::getPositionOnLane(), myPartialVehicles, and myVehicles.
Referenced by dictSize().
getFirstFullVehicle()
MSVehicle * MSLane::getFirstFullVehicle () const
returns the first vehicle for which this lane is responsible or 0
Definition at line 1788 of file MSLane.cpp.
References myVehicles.
Referenced by dictSize(), and freeInsertion().
getFirstInternalInConnection()
const MSLane * MSLane::getFirstInternalInConnection (double & offset) const
Returns 0 if the lane is not internal. Otherwise the first part of the connection (sequence of internal lanes along junction) corresponding to the lane is returned and the offset is set to the distance of the begin of this lane to the begin of the returned.
Definition at line 1621 of file MSLane.cpp.
References getCanonicalPredecessorLane(), getLength(), and isInternal().
Referenced by MSDevice_SSM::classifyEncounter(), and getEdge().
getFirstVehicleInformation()
const MSLeaderInfo & MSLane::getFirstVehicleInformation (const MSVehicle * ego, double latOffset, bool onlyFrontOnLane, double maxPos = std::numeric_limits<double>::max(), bool allowCached = true) const
analogue to getLastVehicleInformation but in the upstream direction
Definition at line 1021 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), anyVehiclesUpstreamBegin(), DEBUG_COND2, MSNet::getCurrentTimeStep(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLatOffset(), MSVehicle::getPositionOnLane(), MSVehicle::isFrontOnLane(), myFollowerInfo, myFollowerInfoTime, myLeaderInfoTmp, and myLength.
Referenced by getFollowersOnConsecutive(), and getMoveReminders().
getFollower()
std::pair< MSVehicle *const, double > MSLane::getFollower (const MSVehicle * ego, double egoPos, double dist, bool ignoreMinorLinks) const
Find follower vehicle for the given ego vehicle (which may be on the opposite direction lane)
Parameters
[in] ego The ego vehicle
[in] egoPos The ego position mapped to the current lane
[in] dist The look-back distance when looking at consecutive lanes
[in] ignoreMinorLinks Whether backward search should stop at minor links
Returns
the follower vehicle and it's gap to ego
Definition at line 3033 of file MSLane.cpp.
References anyVehiclesUpstreamBegin(), anyVehiclesUpstreamEnd(), DEBUG_COND2, getFollowersOnConsecutive(), Named::getID(), MSBaseVehicle::getID(), MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), and MSBaseVehicle::getVehicleType().
Referenced by getCenterOnEdge(), getOppositeFollower(), and getOppositeLeader().
getFollowersOnConsecutive()
MSLeaderDistanceInfo MSLane::getFollowersOnConsecutive (const MSVehicle * ego, double backOffset, bool allSublanes, double searchDist = -1, bool ignoreMinorLinks = false) const
return the sublane followers with the largest missing rear gap among all predecessor lanes (within dist)
XXX iterate in reverse and abort when there are no more freeSublanes
XXX dubious term. here for backwards compatibility
Definition at line 2759 of file MSLane.cpp.
References MSCriticalFollowerDistanceInfo::addFollower(), anyVehiclesBegin(), anyVehiclesEnd(), DEBUG_COND2, getFirstVehicleInformation(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), getIncomingLanes(), MSVehicle::getLane(), MSVehicle::getLatOffset(), MSVehicleType::getLength(), getLength(), getMaximumBrakeDist(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), getRightSideOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicle::isFrontOnLane(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, MAX2(), myIncomingLanes, MSLeaderInfo::numFreeSublanes(), SIMTIME, MSLeaderInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), and MSLane::IncomingLaneInfo::viaLink.
Referenced by getFollower(), getIncomingLanes(), getMissingRearGap(), and isInsertionSuccess().
getFuelConsumption()
double MSLane::getFuelConsumption () const
Returns the sum of last step fuel consumption.
Returns
fuel consumption of vehicles on this lane during the last step
Definition at line 2502 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), GUILane::getColorValue(), libsumo::Lane::getFuelConsumption(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getHarmonoise_NoiseEmissions()
double MSLane::getHarmonoise_NoiseEmissions () const
Returns the sum of last step noise emissions.
Returns
noise emissions of vehicles on this lane during the last step
Definition at line 2526 of file MSLane.cpp.
References getVehiclesSecure(), releaseVehicles(), and HelpersHarmonoise::sum().
Referenced by getBruttoVehLenSum(), GUILane::getColorValue(), libsumo::Lane::getNoiseEmission(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getHCEmissions()
double MSLane::getHCEmissions () const
Returns the sum of last step HC emissions.
Returns
HC emissions of vehicles on this lane during the last step
Definition at line 2490 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), GUILane::getColorValue(), libsumo::Lane::getHCEmission(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), detectCollisionBetween(), detectCollisions(), detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), getFollower(), getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), getLastVehicleInformation(), MSVehicle::getLatOffset(), getLeader(), MSLink::getLeaderInfo(), getLeaderOnConsecutive(), getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), getOppositeFollower(), getOppositeLeader(), getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), resetManeuverReservation(), resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice::saveState(), MSDevice_Vehroutes::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getIncomingLanes()
const std::vector<IncomingLaneInfo>& MSLane::getIncomingLanes () const inline
Definition at line 752 of file MSLane.h.
References addApproachingLane(), getBruttoOccupancy(), getCanonicalPredecessorLane(), getCanonicalSuccessorLane(), getCriticalLeader(), getFollowersOnConsecutive(), getIncomingLinkState(), getLeader(), getLeaderOnConsecutive(), getLeadersOnConsecutive(), getLogicalPredecessorLane(), getMeanSpeed(), getMissingRearGap(), getNettoOccupancy(), getOutgoingLanes(), getPartialBehind(), getPartialBeyond(), getWaitingSeconds(), isApproachedFrom(), and myIncomingLanes.
Referenced by getFollowersOnConsecutive(), MSLogicJunction::getInternalLanes(), MSNoLogicJunction::getInternalLanes(), MSLink::getInternalLengthsBefore(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), MSLane::incoming_lane_priority_sorter::operator()(), MSVehicle::passingMinor(), MSVehicle::planMoveInternal(), MSInternalJunction::postloadInit(), and MSLink::setRequestInformation().
getIncomingLinkState()
LinkState MSLane::getIncomingLinkState () const
get the state of the link from the logical predecessor to this lane
Definition at line 2336 of file MSLane.cpp.
References MSLinkContHelper::getConnectingLink(), getLogicalPredecessorLane(), MSLink::getState(), and LINKSTATE_DEADEND.
Referenced by getIncomingLanes().
getIndex()
int MSLane::getIndex () const inline
Returns the lane's index.
Returns
This lane's index
Definition at line 520 of file MSLane.h.
References appropriate(), detectCollisions(), executeMovements(), getCrossingIndex(), getEntryLink(), getLinkCont(), getLinkTo(), integrateNewVehicle(), myIndex, planMovements(), and updateLeaderInfo().
Referenced by MSLCM_SL2015::_wantsChangeSublane(), GUILane::drawLinkNo(), MSCalibrator::execute(), libsumo::Vehicle::getLaneIndex(), MSLink::getLeaderInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSLink::getZipperSpeed(), MSEdge::insertVehicle(), MSCalibrator::myStartElement(), MSDevice_Vehroutes::notifyEnter(), MSDevice_Bluelight::notifyMove(), MSLink::opened(), MSLaneChangerSublane::startChangeSublane(), and MSLaneChangerSublane::updateChanger().
getLastAnyVehicle()
MSVehicle * MSLane::getLastAnyVehicle () const
returns the last vehicle that is fully or partially on this lane
Definition at line 1797 of file MSLane.cpp.
References myPartialVehicles, and myVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), dictSize(), getCriticalLeader(), lastInsertion(), and MSLink::maybeOccupied().
getLastFullVehicle()
MSVehicle * MSLane::getLastFullVehicle () const
returns the last vehicle for which this lane is responsible or 0
Definition at line 1779 of file MSLane.cpp.
References myVehicles.
Referenced by dictSize().
getLastVehicleInformation()
const MSLeaderInfo & MSLane::getLastVehicleInformation (const MSVehicle * ego, double latOffset, double minPos = 0, bool allowCached = true) const
Returns the last vehicles on the lane.
The information about the last vehicles in this lanes in all sublanes occupied by ego are returned. Partial occupators are included
Parameters
[in] ego The vehicle for which to restrict the returned leaderInfo
[in] minPos The minimum position from which to start search for leaders
[in] allowCached Whether the cached value may be used
Returns
Information about the last vehicles
Definition at line 968 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), anyVehiclesBegin(), DEBUG_COND2, gDebugFlag1, MSNet::getCurrentTimeStep(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLatOffset(), MSVehicle::getPositionOnLane(), myLeaderInfo, myLeaderInfoTime, myLeaderInfoTmp, and MSLeaderInfo::toString().
Referenced by detectCollisions(), getLeadersOnConsecutive(), getMoveReminders(), isInsertionSuccess(), and MSVehicle::planMoveInternal().
getLeader()
std::pair< MSVehicle *const, double > MSLane::getLeader (const MSVehicle * veh, const double vehPos, const std::vector< MSLane *> & bestLaneConts, double dist = -1, bool checkTmpVehicles = false) const
Returns the immediate leader of veh and the distance to veh starting on this lane.
Iterates over the current lane to find a leader and then uses getLeaderOnConsecutive()
Parameters
[in] veh The vehicle for which the information shall be computed
[in] vehPos The vehicle position relative to this lane (may be negative)
[in] bestLaneConts The succeding lanes that shall be checked (if any)
[in] dist Optional distance to override default (ego stopDist)
[in] checkTmpVehicles Whether myTmpVehicles should be used instead of myVehicles
Returns
Definition at line 2042 of file MSLane.cpp.
References anyVehiclesBegin(), anyVehiclesEnd(), MSCFModel::brakeGap(), DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), Named::getID(), MSBaseVehicle::getID(), getLeaderOnConsecutive(), getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), myTmpVehicles, myVehicles, NUMERICAL_EPS, and toString().
Referenced by MSLaneChanger::checkChange(), getIncomingLanes(), getOppositeFollower(), getOppositeLeader(), and lastInsertion().
getLeaderOnConsecutive()
std::pair< MSVehicle *const, double > MSLane::getLeaderOnConsecutive (double dist, double seen, double speed, const MSVehicle & veh, const std::vector< MSLane *> & bestLaneConts) const
Returns the immediate leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the vehicle will pass it. If so, the subsequent lane is investigated. If a vehicle (leader) is found, it is returned, together with the length of the investigated lanes until this vehicle's end, including the already seen place (seen).
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Todo:
: There are some oddities:
what about crossing a link at red, or if a link is closed? Has a following vehicle to be regarded or not?
Parameters
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The vehicle for which the information shall be computed
[in] bestLaneConts The lanes the vehicle will use in future
Returns
Definition at line 2107 of file MSLane.cpp.
References MSCFModel::brakeGap(), DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MAX2(), myPartialVehicles, NUMERICAL_EPS, succLinkSec(), TIME2STEPS, and toString().
Referenced by getIncomingLanes(), getLeader(), and MSVehicle::getLeader().
getLeadersOnConsecutive()
void MSLane::getLeadersOnConsecutive (double dist, double seen, double speed, const MSVehicle * ego, const std::vector< MSLane *> & bestLaneConts, MSLeaderDistanceInfo & result) const
Returns the immediate leaders and the distance to them (as getLeaderOnConsecutive but for the sublane case)
Definition at line 2884 of file MSLane.cpp.
References MSLeaderDistanceInfo::addLeader(), MSCFModel::brakeGap(), DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), getLastVehicleInformation(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getLatOffset(), MSVehicleType::getLength(), getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::isFrontOnLane(), isLinkEnd(), MAX2(), MIN2(), myPartialVehicles, NUMERICAL_EPS, MSLeaderInfo::numFreeSublanes(), MSLeaderInfo::numSublanes(), SIMTIME, succLinkSec(), TIME2STEPS, MSLeaderInfo::toString(), and MSLink::LinkLeader::vehAndGap.
Referenced by getIncomingLanes().
getLength()
double MSLane::getLength () const inline
Returns the lane's length.
Returns
This lane's length
Definition at line 497 of file MSLane.h.
References myLength.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::adaptToLeaders(), NLTriggerBuilder::addAccess(), NLHandler::addConnection(), MSPModel_Striping::addCrossingVehs(), addIncomingLane(), MSVehicle::addStop(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NLDetectorBuilder::buildE2Detector(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), GUILane::debugDrawFoeIntersections(), MSLCM_LC2013::distanceAlongNextRoundabout(), MSPModel_Striping::PState::distToLaneEnd(), GUIVehicle::drawAction_drawRailCarriages(), GUIEdge::drawMesoVehicles(), MSVehicle::executeMove(), executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), freeInsertion(), GUILane::getColorValue(), getCriticalLeader(), MSVehicle::getDistanceToPosition(), MSE2Collector::getEstimateQueueLength(), getFirstInternalInConnection(), getFollowersOnConsecutive(), MSLink::getInternalLengthsAfter(), MSLink::getInternalLengthsBefore(), libsumo::Helper::getLaneChecking(), NLShapeHandler::getLanePos(), getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), getLeadersOnConsecutive(), libsumo::Lane::getLength(), MSLink::getLengthBeforeCrossing(), MSLink::getLengthsBeforeCrossing(), MSPModel_Striping::getNextLaneObstacles(), libsumo::Vehicle::getNextTLS(), getOppositePos(), NLTriggerBuilder::getPosition(), MSVehicle::getPositionAlongBestLanes(), NLDetectorBuilder::getPositionChecking(), MSLaneChanger::getRealLeader(), MSVehicle::getRerouteOrigin(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpaceTillLastStanding(), libsumo::Lane::getTraveltime(), handleCollisionBetween(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSE2Collector::initAuxiliaries(), MSPModel_Striping::initWalkingAreaPaths(), insertVehicle(), isInsertionSuccess(), lastInsertion(), MSLink::maybeOccupied(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSE2Collector::MSE2Collector(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildChargingStation(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSE2Collector::recalculateDetectorLength(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSVehicle::setBlinkerInformation(), MSLink::setRequestInformation(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateBestLanes(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData::writeEdge(), and MSQueueExport::writeLane().
getLengthGeometryFactor()
double MSLane::getLengthGeometryFactor () const inline
return shape.length() / myLength
Definition at line 444 of file MSLane.h.
References myLengthGeometryFactor.
getLinkCont()
const MSLinkCont & MSLane::getLinkCont () const
returns the container with all links !!!
Definition at line 1874 of file MSLane.cpp.
References myLinks.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSPModel_Striping::addCrossingVehs(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::computeSublaneShift(), GUILane::debugDrawFoeIntersections(), MSLCM_LC2013::distanceAlongNextRoundabout(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSVehicle::getBestLanesContinuation(), MSLinkContHelper::getConnectingLink(), MSLink::getCorrespondingExitLink(), getIndex(), libsumo::Lane::getInternalFoes(), MSLinkContHelper::getInternalFollowingEdge(), MSEdge::getInternalFollowingEdge(), MSLinkContHelper::getInternalFollowingLane(), MSLink::getInternalLengthsAfter(), MSLink::getLeaderInfo(), MSLink::getLengthsBeforeCrossing(), MESegment::getLink(), libsumo::Lane::getLinkNumber(), libsumo::Lane::getLinks(), MESegment::getMaxPenaltySeconds(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextWalkingArea(), MSVehicle::getPositionAlongBestLanes(), MSDevice_SSM::getVehiclesOnJunction(), MSRailSignal::init(), MSVehicle::planMoveInternal(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), MSEdge::recalcCache(), MSVehicle::setBlinkerInformation(), MSLink::setRequestInformation(), MSVehicle::updateBestLanes(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
getLinkTo()
MSLink * MSLane::getLinkTo (const MSLane * target) const
returns the link to the given lane or 0, if it is not connected
Definition at line 1881 of file MSLane.cpp.
References Named::getID(), isInternal(), and myLinks.
Referenced by MSDevice_SSM::findFoeConflictLane(), getEntryLink(), getIndex(), MSVehicle::getPositionAlongBestLanes(), MSRailSignal::init(), MSE2Collector::initAuxiliaries(), MSLane::incoming_lane_priority_sorter::operator()(), MSE2Collector::recalculateDetectorLength(), MSE2Collector::selectLanes(), and MSVehicle::updateDriveItems().
getLogicalPredecessorLane() [1/2]
MSLane * MSLane::getLogicalPredecessorLane () const
get the most likely precedecessor lane (sorted using by_connections_to_sorter). The result is cached in myLogicalPredecessorLane
Definition at line 2256 of file MSLane.cpp.
References getEdge(), MSEdge::getPredecessors(), myEdge, myIncomingLanes, and myLogicalPredecessorLane.
Referenced by MSEdge::allowsLaneChanging(), MSVehicle::checkLinkLeader(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), getIncomingLanes(), getIncomingLinkState(), MSLink::getLeaderInfo(), MSPModel_Striping::getNextLane(), MSLink::lastWasContMajor(), libsumo::Helper::moveToXYMap(), GUILane::setFunctionalColor(), MSLink::setRequestInformation(), and MSVehicle::updateBestLanes().
getLogicalPredecessorLane() [2/2]
MSLane * MSLane::getLogicalPredecessorLane (const MSEdge & fromEdge) const
return the (first) predecessor lane from the given edge
Definition at line 2284 of file MSLane.cpp.
References getEdge(), and myIncomingLanes.
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getMaximumBrakeDist()
double MSLane::getMaximumBrakeDist () const protected
compute maximum braking distance on this lane
Definition at line 2032 of file MSLane.cpp.
References MSNet::getInstance(), MSVehicleControl::getMaxSpeedFactor(), MSVehicleControl::getMinDeceleration(), getSpeedLimit(), and MSNet::getVehicleControl().
Referenced by getFollowersOnConsecutive().
getMeanSpeed()
double MSLane::getMeanSpeed () const
Returns the mean speed on this lane.
Returns
The average speed of vehicles during the last step; default speed if no vehicle was on this lane
Definition at line 2426 of file MSLane.cpp.
References getVehiclesSecure(), myMaxSpeed, myVehicles, and releaseVehicles().
Referenced by GUILane::getColorValue(), getIncomingLanes(), libsumo::Lane::getLastStepMeanSpeed(), GUILane::getScaleValue(), libsumo::Lane::getTraveltime(), and MSFullExport::writeLane().
getMissingRearGap()
double MSLane::getMissingRearGap (const MSVehicle * leader, double backOffset, double leaderSpeed) const
return by how much further the leader must be inserted to avoid rear end collisions
Definition at line 2016 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), getFollowersOnConsecutive(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), and MSVehicle::getSpeed().
Referenced by freeInsertion(), getIncomingLanes(), and isInsertionSuccess().
getMoveReminders()
const std::vector< MSMoveReminder* >& MSLane::getMoveReminders () const inline
Return the list of this lane's move reminders.
Returns
Previously added move reminder
Definition at line 232 of file MSLane.h.
References checkFailure(), forceVehicleInsertion(), freeInsertion(), getFirstVehicleInformation(), getLastVehicleInformation(), insertVehicle(), isInsertionSuccess(), lastInsertion(), myMoveReminders, MSMoveReminder::NOTIFICATION_DEPARTED, resetManeuverReservation(), resetPartialOccupation(), setManeuverReservation(), and setPartialOccupation().
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), and MSVehicle::processNextStop().
getNettoOccupancy()
double MSLane::getNettoOccupancy () const
Returns the netto (excluding minGaps) occupancy of this lane during the last step (including minGaps)
Returns
The occupancy during the last step
Definition at line 2398 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MIN2(), myLength, myNettoVehicleLengthSum, myPartialVehicles, myVehicles, and releaseVehicles().
Referenced by GUILane::getColorValue(), getIncomingLanes(), libsumo::Lane::getLastStepOccupancy(), GUILane::getParameterWindow(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getNextNormal()
const MSEdge * MSLane::getNextNormal () const
Returns the lane's follower if it is an internal lane, the edge of the lane otherwise.
Returns
This lane's follower
Definition at line 1611 of file MSLane.cpp.
References MSEdge::getSuccessors(), MSEdge::isInternal(), and myEdge.
Referenced by MSVehicle::addStop(), getEdge(), MSVehicle::getRerouteOrigin(), and MSVehicle::updateBestLanes().
getNOxEmissions()
double MSLane::getNOxEmissions () const
Returns the sum of last step NOx emissions.
Returns
NOx emissions of vehicles on this lane during the last step
Definition at line 2478 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), GUILane::getColorValue(), libsumo::Lane::getNOxEmission(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getNumericalID()
int MSLane::getNumericalID () const inline
Returns this lane's numerical id.
Returns
This lane's numerical id
Definition at line 431 of file MSLane.h.
References myNumericalID.
Referenced by MSPModel_Striping::lane_by_numid_sorter::operator()(), and MSPModel_Striping::walkingarea_path_sorter::operator()().
getOpposite()
MSLane * MSLane::getOpposite () const
return the opposite direction lane for lane changing or 0
Definition at line 3012 of file MSLane.cpp.
References dictionary(), and myNeighs.
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::executeMove(), getCenterOnEdge(), getOppositePos(), MSVehicle::planMoveInternal(), MSVehicle::updateBestLanes(), and MSVehicle::updateState().
getOppositeFollower()
std::pair< MSVehicle *const, double > MSLane::getOppositeFollower (const MSVehicle * ego) const
Definition at line 3075 of file MSLane.cpp.
References DEBUG_COND2, MSVehicle::getBackPositionOnLane(), getFollower(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), getLeader(), MSVehicleType::getLength(), getOppositePos(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::isOpposite(), and SIMTIME.
Referenced by MSLaneChanger::changeOpposite(), and getCenterOnEdge().
getOppositeLeader()
std::pair< MSVehicle *const, double > MSLane::getOppositeLeader (const MSVehicle * ego, double dist, bool oppositeDir) const
Definition at line 3052 of file MSLane.cpp.
References DEBUG_COND2, MSVehicle::getBestLanesContinuation(), getFollower(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), getLeader(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), getOppositePos(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::isOpposite(), and SIMTIME.
Referenced by MSLaneChanger::changeOpposite(), getCenterOnEdge(), and MSVehicle::planMoveInternal().
getOppositePos()
double MSLane::getOppositePos (double pos) const
return the corresponding position on the opposite lane
Definition at line 3021 of file MSLane.cpp.
References Named::getID(), getLength(), getOpposite(), and MAX2().
Referenced by MSLCM_LC2013::_wantsChange(), MSLaneChanger::changeOpposite(), MSVehicle::executeMove(), getCenterOnEdge(), getOppositeFollower(), getOppositeLeader(), and MSVehicle::updateState().
getOutgoingLanes()
std::vector< const MSLane * > MSLane::getOutgoingLanes () const
get the list of outgoing lanes
Definition at line 2347 of file MSLane.cpp.
References myLinks.
Referenced by getIncomingLanes(), MSRailSignal::init(), and MSVehicle::replaceRoute().
getParallelLane()
MSLane * MSLane::getParallelLane (int offset) const
Returns the lane with the given offset parallel to this one or 0 if it does not exist.
Parameters
[in] offset The offset of the result lane
Definition at line 1962 of file MSLane.cpp.
References myEdge, and MSEdge::parallelLane().
Referenced by MSLaneChanger::checkChange(), MSLink::computeParallelLink(), MSAbstractLaneChangeModel::determineTargetLane(), dictSize(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::lateralDistanceToLane(), MSVehicle::planMoveInternal(), and MSAbstractLaneChangeModel::updateTargetLane().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getParkingVehicles()
const std::set<const MSVehicle*>& MSLane::getParkingVehicles () const inline
retrieve the parking vehicles (see GUIParkingArea)
Definition at line 1016 of file MSLane.h.
References myParkingVehicles.
Referenced by GUIParkingArea::drawGL().
getPartialBehind()
MSVehicle * MSLane::getPartialBehind (const MSVehicle * ego) const
Definition at line 2974 of file MSLane.cpp.
References DEBUG_COND2, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getPositionOnLane(), MSVehicle::isFrontOnLane(), myPartialVehicles, SIMTIME, and toString().
Referenced by getIncomingLanes().
getPartialBeyond()
MSLeaderInfo MSLane::getPartialBeyond () const
get all vehicles that are inlapping from consecutive edges
Definition at line 2997 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), MSVehicle::getLatOffset(), MSVehicle::isFrontOnLane(), and myPartialVehicles.
Referenced by getIncomingLanes().
getPartialVehicleNumber()
int MSLane::getPartialVehicleNumber () const inline
Returns the number of vehicles partially on this lane (for which this lane is not responsible)
Returns
The number of vehicles touching this lane but with their front on another lane
Definition at line 381 of file MSLane.h.
References myPartialVehicles.
getPermissions()
SVCPermissions MSLane::getPermissions () const inline
Returns the vehicle class permissions for this lane.
Returns
This lane's allowed vehicle classes
Definition at line 505 of file MSLane.h.
References myPermissions.
Referenced by MSSwarmTrafficLightLogic::allowLine(), libsumo::Lane::getAllowed(), and GUIApplicationWindow::onCmdEditChosen().
getPMxEmissions()
double MSLane::getPMxEmissions () const
Returns the sum of last step PMx emissions.
Returns
PMx emissions of vehicles on this lane during the last step
Definition at line 2466 of file MSLane.cpp.
References getVehiclesSecure(), and releaseVehicles().
Referenced by getBruttoVehLenSum(), GUILane::getColorValue(), libsumo::Lane::getPMxEmission(), GUILane::getScaleValue(), and MSFullExport::writeLane().
getRightmostSublane()
int MSLane::getRightmostSublane () const inline
Definition at line 964 of file MSLane.h.
References myRightmostSublane.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
getRightSideOnEdge()
double MSLane::getRightSideOnEdge () const inline
Definition at line 960 of file MSLane.h.
References myRightSideOnEdge.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSLaneChangerSublane::checkChangeSublane(), MSVehicle::checkLinkLeader(), MSLCM_SL2015::commitManoeuvre(), detectCollisions(), MSVehicle::getCenterOnEdge(), getFollowersOnConsecutive(), MSVehicle::getLatOffset(), MSLCM_SL2015::keepLatGap(), MSVehicle::planMoveInternal(), MSLaneChangerSublane::startChangeSublane(), and MSLaneChangerSublane::updateChanger().
getShape()
const PositionVector& MSLane::getShape () const inline
Returns this lane's shape.
Returns
This lane's shape
Definition at line 439 of file MSLane.h.
References myShape.
Referenced by LaneStoringVisitor::add(), GUIBusStop::addAccess(), NLHandler::addConnection(), GUIE3Collector::MyWrapper::buildDefinition(), MSDevice_SSM::classifyEncounter(), TraCIServerAPI_Simulation::commandPositionConversion(), MSVehicle::computeAngle(), GUILane::debugDrawFoeIntersections(), GUIVehicle::drawAction_drawLinkItems(), GUILane::drawLane2LaneConnections(), fill(), libsumo::Helper::findCloserLane(), MEVehicle::getAngle(), MSPModel_Striping::PState::getAngle(), MSTransportable::Stage::getLanePosition(), MSPModel_Striping::getNextLaneObstacles(), TraCIServerAPI_InductionLoop::getPosition(), GUIContainer::getPosition(), libsumo::Lane::getShape(), TraCIServerAPI_Lane::getShape(), MEVehicle::getSlope(), MSVehicle::getSlope(), MSVTKExport::getSpeed(), libsumo::InductionLoop::getTree(), MSStoppingPlace::getWaitPosition(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), MSPModel_Striping::initWalkingAreaPaths(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSParkingArea::MSParkingArea(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSLane::by_connections_to_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), MSLink::setRequestInformation(), MSLaneChangerSublane::startChangeSublane(), MSPerson::MSPersonStage_Walking::walkDistance(), and MSBatteryExport::write().
getSpeedLimit()
double MSLane::getSpeedLimit () const inline
Returns the lane's maximum allowed speed.
Returns
This lane's maximum allowed speed
Definition at line 489 of file MSLane.h.
References myMaxSpeed.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::congested(), executeMovements(), GUILane::getColorValue(), MSE2Collector::getEstimatedCurrentVehicleNumber(), libsumo::Lane::getLinks(), getMaximumBrakeDist(), libsumo::Lane::getMaxSpeed(), GUILane::getParameterWindow(), GUILane::getScaleValue(), MSLCM_LC2013::informFollower(), MSActuatedTrafficLightLogic::init(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData::writeEdge(), and MSFullExport::writeLane().
getVehicleMaxSpeed()
double MSLane::getVehicleMaxSpeed (const SUMOVehicle *const veh) const inline
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
Parameters
[in] The vehicle to return the adapted speed limit for
Returns
This lane's resulting max. speed
Definition at line 475 of file MSLane.h.
References SUMOVehicle::getChosenSpeedFactor(), SUMOVehicle::getMaxSpeed(), SUMOVehicle::getVClass(), MIN2(), myMaxSpeed, and myRestrictions.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSCFModel_IDM::followSpeed(), libsumo::Vehicle::getAllowedSpeed(), GUIVehicle::getColorValue(), getCriticalLeader(), getDepartSpeed(), getLeadersOnConsecutive(), MSVehicle::getMaxSpeedOnLane(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), isInsertionSuccess(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_IDM::moveHelper(), MSVehicle::planMoveInternal(), MSVehicle::setBlinkerInformation(), MSCFModel_IDM::stopSpeed(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSVehicle::updateTimeLoss(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
getVehicleNumber()
int MSLane::getVehicleNumber () const inline
Returns the number of vehicles on this lane (for which this lane is responsible)
Returns
The number of vehicles with their front on this lane
Definition at line 365 of file MSLane.h.
References myVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), libsumo::Lane::getLastStepVehicleNumber(), MSVehicle::planMoveInternal(), MSFullExport::writeLane(), and MSXMLRawOut::writeLane().
getVehicleNumberWithPartials()
int MSLane::getVehicleNumberWithPartials () const inline
Returns the number of vehicles on this lane (including partial occupators)
Returns
The number of vehicles with intersecting this lane
Definition at line 373 of file MSLane.h.
References myPartialVehicles, and myVehicles.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), and MSPModel_Striping::PState::PState().
getVehiclesSecure()
virtual const VehCont& MSLane::getVehiclesSecure () const inline virtual
Returns the vehicles container; locks it for microsimulation.
Please note that it is necessary to release the vehicles container afterwards using "releaseVehicles".
Returns
The vehicles on this lane
Reimplemented in GUILane.
Definition at line 392 of file MSLane.h.
References myVehicles.
Referenced by LaneStoringVisitor::add(), GUIParkingArea::drawGL(), getBruttoOccupancy(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), libsumo::Lane::getLastStepHaltingNumber(), libsumo::Lane::getLastStepLength(), libsumo::Lane::getLastStepVehicleIDs(), MSVehicle::getLeader(), getMeanSpeed(), getNettoOccupancy(), getNOxEmissions(), getPMxEmissions(), MSVehicle::getSpaceTillLastStanding(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), and MSPedestrianPushButton::isActiveForEdge().
getWaitingSeconds()
double MSLane::getWaitingSeconds () const
Returns the overall waiting time on this lane.
Returns
The sum of the waiting time of all vehicles during the last step;
Definition at line 2413 of file MSLane.cpp.
References myVehicles.
Referenced by getIncomingLanes(), and libsumo::Lane::getWaitingTime().
getWidth()
double MSLane::getWidth () const inline
Returns the lane's width.
Returns
This lane's width
Definition at line 513 of file MSLane.h.
References myWidth.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSPModel_Striping::addCrossingVehs(), MSLaneChangerSublane::checkChangeToNewLane(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::computeSpeedGain(), MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::determineTargetLane(), GUILane::drawGL(), MSVehicle::getCenterOnEdge(), getDepartPosLat(), MSVehicle::getLateralOverlap(), MSVehicle::getLatOffset(), MSLink::getLeaderInfo(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::PState::getPosition(), MSVehicle::getRightSideOnLane(), MSLCM_SL2015::getSublaneWidth(), libsumo::Lane::getWidth(), GUIParkingArea::GUIParkingArea(), MSPModel_Striping::initWalkingAreaPaths(), insertVehicle(), MSLCM_SL2015::keepLatGap(), MSVehicle::lateralDistanceToLane(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), MSPModel_Striping::PState::moveToXY(), MSParkingArea::MSParkingArea(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::numStripes(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLinkAproaches(), GUIVehicle::selectBlockingFoes(), MSLink::setRequestInformation(), and MSLaneChangerSublane::startChangeSublane().
handleCollisionBetween()
void MSLane::handleCollisionBetween (SUMOTime timestep, const std::string & stage, MSVehicle * collider, MSVehicle * victim, double gap, double latGap, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > & toRemove, std::set< const MSVehicle *> & toTeleport) const protected
take action upon collision
Definition at line 1418 of file MSLane.cpp.
References MSVehicle::addStop(), MSCFModel::brakeGap(), SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, COLLISION_ACTION_REMOVE, COLLISION_ACTION_TELEPORT, COLLISION_ACTION_WARN, MSVehicle::collisionStopTime(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSVehicle::getCarFollowModel(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleType::getLength(), getLength(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSVehicle::hasInfluencer(), SUMOVehicleParameter::Stop::index, MSVehicle::Influencer::isRemoteAffected(), SUMOVehicleParameter::Stop::lane, MAX2(), MIN2(), myCollisionAction, myCollisionStopTime, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, MSVehicleControl::registerCollision(), SUMOVehicleParameter::Stop::startPos, time2string(), toString(), SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and WRITE_WARNING.
Referenced by detectCollisionBetween(), and detectCollisions().
incorporateVehicle()
void MSLane::incorporateVehicle (MSVehicle * veh, double pos, double speed, double posLat, const MSLane::VehCont::iterator & at, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) protected virtual
Inserts the vehicle into this lane, and informs it about entering the network.
Calls the vehicles enterLaneAtInsertion function, updates statistics and modifies the active state as needed
Parameters
[in] veh The vehicle to be incorporated
[in] pos The position of the vehicle
[in] speed The speed of the vehicle
[in] posLat The lateral position of the vehicle
[in] at
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Reimplemented in GUILane.
Definition at line 290 of file MSLane.cpp.
References MSVehicle::enterLaneAtInsertion(), MSNet::getEdgeControl(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSEdgeControl::gotActive(), MSEdge::markDelayed(), myBruttoVehicleLengthSum, myEdge, myLength, myNettoVehicleLengthSum, and myVehicles.
Referenced by forceVehicleInsertion(), GUILane::incorporateVehicle(), isInsertionSuccess(), and loadState().
initCollisionOptions()
void MSLane::initCollisionOptions (const OptionsCont & oc) static
Definition at line 3099 of file MSLane.cpp.
References COLLISION_ACTION_NONE, COLLISION_ACTION_REMOVE, COLLISION_ACTION_TELEPORT, COLLISION_ACTION_WARN, OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getString(), myCheckJunctionCollisions, myCollisionAction, myCollisionMinGapFactor, myCollisionStopTime, string2time(), and WRITE_ERROR.
Referenced by MSFrame::setMSGlobals(), and visit().
initRestrictions()
void MSLane::initRestrictions ()
initialized vClass-specific speed limits
Definition at line 200 of file MSLane.cpp.
References MSEdge::getEdgeType(), MSNet::getInstance(), MSNet::getRestrictions(), myEdge, and myRestrictions.
Referenced by MSLane(), and setRightSideOnEdge().
insertIDs()
void MSLane::insertIDs (std::vector< std::string > & into) static
Adds the ids of all stored lanes into the given vector.
Parameters
Definition at line 1671 of file MSLane.cpp.
References myDict.
Referenced by dictSize(), and libsumo::Lane::getIDList().
insertVehicle()
bool MSLane::insertVehicle (MSVehicle & v)
Tries to insert the given vehicle.
The insertion position and speed are determined in dependence to the vehicle's departure definition, first.
Then, the vehicle is tried to be inserted into the lane using these values by a call to "isInsertionSuccess". The result of "isInsertionSuccess" is returned.
Parameters
[in] v The vehicle to insert
Returns
Whether the vehicle could be inserted
See also
isInsertionSuccess
MSVehicle::getDepartureDefinition
MSVehicle::DepartArrivalDefinition
Definition at line 484 of file MSLane.cpp.
References basePos(), DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_LAST, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_POSLAT_FREE, DEPART_POSLAT_RANDOM_FREE, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosLatProcedure, SUMOVehicleParameter::departPosProcedure, freeInsertion(), getDepartPosLat(), getDepartSpeed(), getLength(), MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), getWidth(), MSGlobals::gLateralResolution, isInsertionSuccess(), lastInsertion(), myLength, MSMoveReminder::NOTIFICATION_DEPARTED, and RandHelper::rand().
Referenced by getMoveReminders(), and MSEdge::insertVehicle().
integrateNewVehicle()
bool MSLane::integrateNewVehicle (SUMOTime t) virtual
Insert buffered vehicle into the real lane.
Reimplemented in GUILane.
Definition at line 1715 of file MSLane.cpp.
References DEBUG_COND, Named::getID(), MSVehicle::getLane(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSGlobals::gLateralResolution, MSEdge::markDelayed(), myBruttoVehicleLengthSum, myEdge, myNeighs, myNettoVehicleLengthSum, myPartialVehicles, myVehBuffer, myVehicles, SIMTIME, sortPartialVehicles(), and toString().
Referenced by getIndex(), and GUILane::integrateNewVehicle().
interpolateGeometryPosToLanePos()
double MSLane::interpolateGeometryPosToLanePos (double geometryPos) const inline
Definition at line 467 of file MSLane.h.
References myLengthGeometryFactor.
Referenced by GUILane::getPopUpMenu(), and MSLink::setRequestInformation().
interpolateLanePosToGeometryPos()
double MSLane::interpolateLanePosToGeometryPos (double lanePos) const inline
Definition at line 455 of file MSLane.h.
References myLengthGeometryFactor.
Referenced by MSVehicle::computeAngle(), GUIEdge::drawMesoVehicles(), geometryPositionAtOffset(), MEVehicle::getAngle(), MSTransportable::Stage::getLanePosition(), MSVehicle::getPosition(), MEVehicle::getSlope(), MSVehicle::getSlope(), MSParkingArea::getSpaceDim(), MSStoppingPlace::getWaitPosition(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), MSParkingArea::MSParkingArea(), and MSLaneChangerSublane::startChangeSublane().
isAccelLane()
bool MSLane::isAccelLane () const inline
return whether this lane is an acceleration lane
Definition at line 449 of file MSLane.h.
References myIsRampAccel.
Referenced by MSLCM_LC2013::informFollower().
isApproachedFrom() [1/2]
bool MSLane::isApproachedFrom (MSEdge *const edge)
Definition at line 1992 of file MSLane.cpp.
References myApproachingLanes.
Referenced by getIncomingLanes().
isApproachedFrom() [2/2]
bool MSLane::isApproachedFrom (MSEdge *const edge, MSLane *const lane)
Definition at line 1998 of file MSLane.cpp.
References myApproachingLanes.
isEmpty()
bool MSLane::isEmpty () const
Returns the information whether the lane is has no vehicle and no partial occupation
Definition at line 1769 of file MSLane.cpp.
References myPartialVehicles, and myVehicles.
Referenced by dictSize().
isInsertionSuccess()
bool MSLane::isInsertionSuccess (MSVehicle * vehicle, double speed, double pos, double posLat, bool recheckNextLanes, MSMoveReminder::Notification notification)
Tries to insert the given vehicle with the given state (speed and pos)
Checks whether the vehicle can be inserted at the given position with the given speed so that no collisions with leader/follower occur and the speed does not cause unexpected behaviour on consecutive lanes. Returns false if the vehicle can not be inserted.
If the insertion can take place, incorporateVehicle() is called and true is returned.
Parameters
[in] vehicle The vehicle to insert
[in] speed The speed with which it shall be inserted
[in] pos The position at which it shall be inserted
[in] posLat The lateral position at which it shall be inserted
[in] recheckNextLanes Forces patching the speed for not being too fast on next lanes
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns
Whether the vehicle could be inserted
See also
MSVehicle::enterLaneAtInsertion
Definition at line 582 of file MSLane.cpp.
References ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, MSRoute::begin(), MSCFModel::brakeGap(), checkFailure(), checkForPedestrians(), DEBUG_COND2, MSInsertionControl::descheduleDeparture(), SUMOVehicleParameter::Stop::endPos, MSCFModel::freeSpeed(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), getEdge(), getFollowersOnConsecutive(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSBaseVehicle::getImpatience(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSRoute::getLastEdge(), getLastVehicleInformation(), MSVehicleType::getLength(), getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), getMissingRearGap(), MSVehicle::getNextStop(), MSBaseVehicle::getParameter(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getRoute(), MSCFModel::getSecureGap(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpeed(), getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::hasStops(), MSLeaderInfo::hasVehicles(), incorporateVehicle(), MSCFModel::insertionStopSpeed(), INVALID_SPEED, isLinkEnd(), MSVehicle::Stop::lane, LINKSTATE_ALLWAY_STOP, LINKSTATE_EQUAL, LINKSTATE_MINOR, LINKSTATE_STOP, MAX2(), Named::myID, myLength, myManeuverReservations, myPartialVehicles, myVehicles, NUMERICAL_EPS, MSLeaderInfo::numFreeSublanes(), MSLeaderInfo::numSublanes(), MSVehicle::Stop::pars, safeInsertionSpeed(), MSVehicle::setTentativeLaneAndPosition(), SIMTIME, MSCFModel::stopSpeed(), succLinkSec(), SUMO_const_haltingSpeed, TIME2STEPS, toString(), MSLeaderInfo::toString(), MSVehicle::updateBestLanes(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), freeInsertion(), getMoveReminders(), insertVehicle(), and lastInsertion().
isInternal()
bool MSLane::isInternal () const
Returns whether the lane pertains to an internal edge
Definition at line 1774 of file MSLane.cpp.
References MSEdge::isInternal(), and myEdge.
Referenced by MSDevice_SSM::classifyEncounter(), dictSize(), MSLCM_LC2013::distanceAlongNextRoundabout(), GUILane::drawGL(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), libsumo::Vehicle::getDistance(), getEntryLink(), getFirstInternalInConnection(), libsumo::Lane::getInternalFoes(), MSLink::getInternalLengthsAfter(), MSLink::getInternalLengthsBefore(), getLinkTo(), MSVehicle::getPositionAlongBestLanes(), MSE2Collector::initAuxiliaries(), MSLane::incoming_lane_priority_sorter::operator()(), succLinkSec(), MSVehicle::updateBestLanes(), and MSVehicle::updateDriveItems().
isLinkEnd() [1/2]
bool MSLane::isLinkEnd (MSLinkCont::const_iterator & i) const
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 1758 of file MSLane.cpp.
References myLinks.
Referenced by MSLaneChanger::checkChange(), dictSize(), getCriticalLeader(), getLeadersOnConsecutive(), libsumo::Vehicle::getNextTLS(), isInsertionSuccess(), MSVehicle::planMoveInternal(), and MSVehicle::unsafeLinkAhead().
isLinkEnd() [2/2]
bool MSLane::isLinkEnd (MSLinkCont::iterator & i)
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 1764 of file MSLane.cpp.
References myLinks.
isSelected()
virtual bool MSLane::isSelected () const inline virtual
whether this lane is selected in the GUI
Reimplemented in GUILane.
Definition at line 1021 of file MSLane.h.
References loadState(), and saveState().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
lastInsertion()
bool MSLane::lastInsertion (MSVehicle & veh, double mspeed, double posLat, bool patchSpeed)
inserts vehicle as close as possible to the last vehicle on this lane (or at the end of the lane if there is no leader)
look for a leaders on consecutive lanes
Definition at line 310 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), getLastAnyVehicle(), getLeader(), getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), isInsertionSuccess(), MIN2(), MSMoveReminder::NOTIFICATION_DEPARTED, POSITION_EPS, MSVehicle::setTentativeLaneAndPosition(), and MSVehicle::updateBestLanes().
Referenced by getMoveReminders(), and insertVehicle().
leftByLaneChange()
void MSLane::leftByLaneChange (MSVehicle * v)
Definition at line 2358 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), myBruttoVehicleLengthSum, and myNettoVehicleLengthSum.
Referenced by dictSize(), and MSAbstractLaneChangeModel::primaryLaneChanged().
loadState()
void MSLane::loadState (std::vector< std::string > & vehIDs, MSVehicleControl & vc)
Loads the state of this segment with the given parameters.
This method is called for every internal que the segment has. Every vehicle is retrieved from the given MSVehicleControl and added to this lane.
Parameters
[in] vehIDs The vehicle ids for the current que
[in] vc The vehicle control to retrieve references vehicles from
Todo:
What about throwing an IOError?
What about throwing an error if something else fails (a vehicle can not be referenced)?
Definition at line 2745 of file MSLane.cpp.
References MSVehicle::getLateralPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicleControl::getVehicle(), incorporateVehicle(), myVehicles, MSMoveReminder::NOTIFICATION_JUNCTION, MSVehicle::processNextStop(), and MSVehicle::updateBestLanes().
Referenced by isSelected().
operator=()
MSLane& MSLane::operator= (const MSLane &) private
invalidated assignment operator
Referenced by MSLane::edge_finder::operator()().
planMovements()
void MSLane::planMovements (const SUMOTime t) virtual
Compute safe velocities for all vehicles based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
This method goes through all vehicles calling their "planMove" method.
See also
MSVehicle::planMove
Reimplemented in GUILane.
Definition at line 1073 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), DEBUG_COND, Named::getID(), myManeuverReservations, myPartialVehicles, myVehicles, SIMTIME, toString(), MSLeaderInfo::toString(), and updateLeaderInfo().
Referenced by getIndex(), and GUILane::planMovements().
releaseVehicles()
virtual void MSLane::releaseVehicles () const inline virtual
Allows to use the container for microsimulation again.
Reimplemented in GUILane.
Definition at line 419 of file MSLane.h.
Referenced by LaneStoringVisitor::add(), GUIParkingArea::drawGL(), getBruttoOccupancy(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), libsumo::Lane::getLastStepHaltingNumber(), libsumo::Lane::getLastStepLength(), libsumo::Lane::getLastStepVehicleIDs(), MSVehicle::getLeader(), getMeanSpeed(), getNettoOccupancy(), getNOxEmissions(), getPMxEmissions(), MSVehicle::getSpaceTillLastStanding(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), and MSPedestrianPushButton::isActiveForEdge().
removeParking()
void MSLane::removeParking (MSVehicle * veh) virtual
remove parking vehicle. This must be syncrhonized when running with GUI
Reimplemented in GUILane.
Definition at line 2729 of file MSLane.cpp.
References myParkingVehicles.
Referenced by MSVehicleTransfer::checkInsertions(), getCenterOnEdge(), MSVehicleTransfer::remove(), and GUILane::removeParking().
removeVehicle()
MSVehicle * MSLane::removeVehicle (MSVehicle * remVehicle, MSMoveReminder::Notification notification, bool notify = true) virtual
Reimplemented in GUILane.
Definition at line 1944 of file MSLane.cpp.
References MSVehicle::getLane(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSVehicle::leaveLane(), myBruttoVehicleLengthSum, myNettoVehicleLengthSum, and myVehicles.
Referenced by detectCollisions(), dictSize(), libsumo::Vehicle::moveTo(), MSVehicle::Influencer::postProcessRemoteControl(), TraCIServerAPI_Vehicle::processSet(), MSCalibrator::removePending(), and GUILane::removeVehicle().
resetManeuverReservation()
void MSLane::resetManeuverReservation (MSVehicle * v) virtual
Unregisters a vehicle, which previously registered for maneuvering into this lane.
Parameters
[in] v The vehicle
Definition at line 272 of file MSLane.cpp.
References DEBUG_COND2, Named::getID(), MSBaseVehicle::getID(), myManeuverReservations, and SIMTIME.
Referenced by MSAbstractLaneChangeModel::cleanupTargetLane(), getMoveReminders(), and MSAbstractLaneChangeModel::updateTargetLane().
resetPartialOccupation()
void MSLane::resetPartialOccupation (MSVehicle * v) virtual
Removes the information about a vehicle lapping into this lane.
Parameters
[in] v The vehicle which laps into this lane
Reimplemented in GUILane.
Definition at line 242 of file MSLane.cpp.
References DEBUG_COND2, Named::getID(), MSBaseVehicle::getID(), myPartialVehicles, and SIMTIME.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), getMoveReminders(), GUILane::resetPartialOccupation(), and MSAbstractLaneChangeModel::updateShadowLane().
resetPermissions()
void MSLane::resetPermissions (long transientID)
Definition at line 3131 of file MSLane.cpp.
References myOriginalPermissions, myPermissionChanges, myPermissions, and SVCAll.
Referenced by GUILane::closeTraffic(), dictSize(), and setPermissions().
safeInsertionSpeed()
double MSLane::safeInsertionSpeed (const MSVehicle * veh, double seen, const MSLeaderInfo & leaders, double speed) protected
return the maximum safe speed for insertion behind leaders (a negative value indicates that safe insertion is impossible)
Definition at line 949 of file MSLane.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), INVALID_SPEED, MIN2(), and MSLeaderInfo::numSublanes().
Referenced by isInsertionSuccess().
saveState()
void MSLane::saveState (OutputDevice & out)
Saves the state of this lane into the given stream.
Basically, a list of vehicle ids
Parameters
Definition at line 2734 of file MSLane.cpp.
References OutputDevice::closeTag(), Named::getID(), myVehicles, OutputDevice::openTag(), SUMO_ATTR_VALUE, SUMO_TAG_LANE, SUMO_TAG_VIEWSETTINGS_VEHICLES, and OutputDevice::writeAttr().
Referenced by isSelected().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setLength()
void MSLane::setLength (double val)
Sets a new length for the lane (used by TraCI only)
Parameters
[in] val the new length in m
Definition at line 1926 of file MSLane.cpp.
References myEdge, myLength, and MSEdge::recalcCache().
Referenced by empty(), and libsumo::Lane::setLength().
setManeuverReservation()
void MSLane::setManeuverReservation (MSVehicle * v) virtual
Registers the lane change intentions (towards this lane) for the given vehicle.
Definition at line 261 of file MSLane.cpp.
References DEBUG_COND2, Named::getID(), MSBaseVehicle::getID(), myManeuverReservations, and SIMTIME.
Referenced by getMoveReminders(), and MSAbstractLaneChangeModel::updateTargetLane().
setMaxSpeed()
void MSLane::setMaxSpeed (double val)
Sets a new maximum speed for the lane (used by TraCI and MSCalibrator)
Parameters
[in] val the new speed in m/s
Definition at line 1919 of file MSLane.cpp.
References myEdge, myMaxSpeed, and MSEdge::recalcCache().
Referenced by empty(), MSCalibrator::execute(), and libsumo::Lane::setMaxSpeed().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setPartialOccupation()
double MSLane::setPartialOccupation (MSVehicle * v) virtual
Sets the information about a vehicle lapping into this lane.
This vehicle is added to myVehicles and may be distinguished from regular vehicles by the disparity between this lane and v->getLane()
Parameters
[in] v The vehicle which laps into this lane
Returns
This lane's length
Reimplemented in GUILane.
Definition at line 229 of file MSLane.cpp.
References DEBUG_COND2, Named::getID(), MSBaseVehicle::getID(), myLength, myPartialVehicles, and SIMTIME.
Referenced by getMoveReminders(), GUILane::setPartialOccupation(), and MSAbstractLaneChangeModel::updateShadowLane().
setPermissions()
void MSLane::setPermissions (SVCPermissions permissions, long transientID)
Sets the permissions to the given value. If a transientID is given, the permissions are recored as temporary.
Parameters
[in] permissions The new permissions
[in] transientID The id of the permission-modification or the special value PERMANENT
Definition at line 3119 of file MSLane.cpp.
References CHANGE_PERMISSIONS_PERMANENT, myOriginalPermissions, myPermissionChanges, myPermissions, and resetPermissions().
Referenced by GUILane::closeTraffic(), dictSize(), libsumo::Lane::setAllowed(), and libsumo::Lane::setDisallowed().
setRightSideOnEdge()
void MSLane::setRightSideOnEdge (double value, int rightmostSublane) inline
Definition at line 952 of file MSLane.h.
References initRestrictions(), myRightmostSublane, and myRightSideOnEdge.
sortManeuverReservations()
void MSLane::sortManeuverReservations ()
sorts myManeuverReservations
Definition at line 1750 of file MSLane.cpp.
References myManeuverReservations.
Referenced by getCenterOnEdge().
sortPartialVehicles()
void MSLane::sortPartialVehicles ()
sorts myPartialVehicles
Definition at line 1742 of file MSLane.cpp.
References myPartialVehicles.
Referenced by getCenterOnEdge(), integrateNewVehicle(), and swapAfterLaneChange().
succLinkSec()
MSLinkCont::const_iterator MSLane::succLinkSec (const SUMOVehicle & veh, int nRouteSuccs, const MSLane & succLinkSource, const std::vector< MSLane *> & conts) static
Same as succLink, but does not throw any assertions when the succeeding link could not be found; Returns the myLinks.end() instead; Further, the number of edges to look forward may be given
Definition at line 1825 of file MSLane.cpp.
References Named::getID(), SUMOVehicle::getID(), MSNet::getInstance(), MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), isInternal(), myLinks, SUMOVehicle::succEdge(), time2string(), and WRITE_WARNING.
Referenced by appropriate(), MSLaneChanger::checkChange(), dictSize(), executeMovements(), getCriticalLeader(), getLeaderOnConsecutive(), getLeadersOnConsecutive(), libsumo::Vehicle::getNextTLS(), isInsertionSuccess(), MSVehicle::planMoveInternal(), MSVehicle::setBlinkerInformation(), and MSVehicle::unsafeLinkAhead().
swapAfterLaneChange()
void MSLane::swapAfterLaneChange (SUMOTime t) protected virtual
moves myTmpVehicles int myVehicles after a lane change procedure
Reimplemented in GUILane.
Definition at line 1933 of file MSLane.cpp.
References myTmpVehicles, myVehicles, and sortPartialVehicles().
Referenced by GUILane::swapAfterLaneChange().
teleportOnCollision()
static bool MSLane::teleportOnCollision () inline static
Definition at line 1065 of file MSLane.h.
References COLLISION_ACTION_TELEPORT, and myCollisionAction.
Referenced by MSVehicleControl::getTeleportCount().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateLeaderInfo()
void MSLane::updateLeaderInfo (const MSVehicle * veh, VehCont::reverse_iterator & vehPart, VehCont::reverse_iterator & vehRes, MSLeaderInfo & ahead) const
This updates the MSLeaderInfo argument with respect to the given MSVehicle. All leader-vehicles on the same edge, which are relevant for the vehicle (i.e. with position > vehicle's position) and not already integrated into the LeaderInfo, are integrated. The given iterators vehPart and vehRes give access to these vehicles which are either partial occupators or have issued a maneuver reservation for the lane (the latter occurs only for the sublane model).
Definition at line 1107 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), DEBUG_COND, MSVehicle::getPositionOnLane(), myManeuverReservations, and myPartialVehicles.
Referenced by getIndex(), and planMovements().
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
visit()
void MSLane::visit (const LaneStoringVisitor & cont) const inline
Callback for visiting the lane when traversing an RTree.
This is used in the TraCIServerAPI_Lane for context subscriptions.
Parameters
[in] cont The context doing all the work
See also
libsumo::Helper::LaneStoringVisitor::add
Definition at line 1059 of file MSLane.h.
References LaneStoringVisitor::add(), and initCollisionOptions().
Referenced by libsumo::Helper::collectObjectsInRange().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Friends And Related Function Documentation
AnyVehicleIterator
friend class AnyVehicleIterator friend
Definition at line 86 of file MSLane.h.
Referenced by anyVehiclesBegin(), anyVehiclesEnd(), anyVehiclesUpstreamBegin(), and anyVehiclesUpstreamEnd().
MSLaneChanger
friend class MSLaneChanger friend
needs access to myTmpVehicles (this maybe should be done via double-buffering!!!)
Definition at line 80 of file MSLane.h.
MSLaneChangerSublane
friend class MSLaneChangerSublane friend
Definition at line 81 of file MSLane.h.
MSQueueExport
friend class MSQueueExport friend
Definition at line 85 of file MSLane.h.
MSXMLRawOut
friend class MSXMLRawOut friend
Definition at line 83 of file MSLane.h.
Field Documentation
CHANGE_PERMISSIONS_GUI
const long MSLane::CHANGE_PERMISSIONS_GUI = 1 static
Definition at line 1074 of file MSLane.h.
Referenced by GUILane::closeTraffic().
CHANGE_PERMISSIONS_PERMANENT
const long MSLane::CHANGE_PERMISSIONS_PERMANENT = 0 static
Definition at line 1073 of file MSLane.h.
Referenced by libsumo::Lane::setAllowed(), libsumo::Edge::setAllowedSVCPermissions(), libsumo::Lane::setDisallowed(), and setPermissions().
myApproachingLanes
std::map<MSEdge*, std::vector<MSLane*> > MSLane::myApproachingLanes protected
All direct internal and direct (disregarding internal predecessors) non-internal predecessor lanes of this lane.
Definition at line 1235 of file MSLane.h.
Referenced by addApproachingLane(), and isApproachedFrom().
myBruttoVehicleLengthSum
double MSLane::myBruttoVehicleLengthSum protected
The current length of all vehicles on this lane, including their minGaps.
Definition at line 1225 of file MSLane.h.
Referenced by enteredByLaneChange(), executeMovements(), getBruttoOccupancy(), getBruttoVehLenSum(), incorporateVehicle(), integrateNewVehicle(), leftByLaneChange(), and removeVehicle().
myCanonicalPredecessorLane
MSLane* MSLane::myCanonicalPredecessorLane mutable protected
Similar to LogicalPredecessorLane,.
See also
getCanonicalPredecessorLane()
Definition at line 1219 of file MSLane.h.
Referenced by getCanonicalPredecessorLane().
myCanonicalSuccessorLane
MSLane* MSLane::myCanonicalSuccessorLane mutable protected
Main successor lane,.
See also
getCanonicalSuccessorLane()
Definition at line 1222 of file MSLane.h.
Referenced by getCanonicalSuccessorLane().
myCheckJunctionCollisions
bool MSLane::myCheckJunctionCollisions static private
Definition at line 1278 of file MSLane.h.
Referenced by detectCollisions(), and initCollisionOptions().
myCollisionAction
MSLane::CollisionAction MSLane::myCollisionAction static private
the action to take on collisions
Definition at line 1277 of file MSLane.h.
Referenced by detectCollisionBetween(), detectCollisions(), getCollisionAction(), handleCollisionBetween(), initCollisionOptions(), and teleportOnCollision().
myCollisionMinGapFactor
double MSLane::myCollisionMinGapFactor static private
Definition at line 1280 of file MSLane.h.
Referenced by detectCollisionBetween(), and initCollisionOptions().
myCollisionStopTime
SUMOTime MSLane::myCollisionStopTime static private
Definition at line 1279 of file MSLane.h.
Referenced by handleCollisionBetween(), and initCollisionOptions().
myDict
MSLane::DictType MSLane::myDict static protected
Static dictionary to associate string-ids with objects.
Definition at line 1270 of file MSLane.h.
Referenced by clear(), dictionary(), dictSize(), fill(), and insertIDs().
myEdge
MSEdge* const MSLane::myEdge protected
The lane's edge, for routing only.
Definition at line 1198 of file MSLane.h.
Referenced by appropriate(), detectCollisions(), GUILane::drawGL(), GUILane::drawMarkings(), GUILane::getColorValue(), getEdge(), GUILane::getEdgeLaneNumber(), GUILane::getLoadedEdgeWeight(), getLogicalPredecessorLane(), getNextNormal(), getParallelLane(), GUILane::getParameterWindow(), GUILane::getScaleValue(), GUILane::getStoredEdgeTravelTime(), incorporateVehicle(), initRestrictions(), integrateNewVehicle(), isInternal(), GUILane::isLaneOrEdgeSelected(), GUILane::setColor(), GUILane::setFunctionalColor(), setLength(), and setMaxSpeed().
myFollowerInfo
MSLeaderInfo MSLane::myFollowerInfo mutable protected
followers on all sublanes as seen by vehicles on consecutive lanes (cached)
Definition at line 1240 of file MSLane.h.
Referenced by getFirstVehicleInformation().
myFollowerInfoTime
SUMOTime MSLane::myFollowerInfoTime mutable protected
time step for which myFollowerInfo was last updated
Definition at line 1247 of file MSLane.h.
Referenced by getFirstVehicleInformation().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), getCanonicalPredecessorLane(), getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myIncomingLanes
std::vector<IncomingLaneInfo> MSLane::myIncomingLanes protected
All direct predecessor lanes.
Definition at line 1213 of file MSLane.h.
Referenced by addIncomingLane(), getCanonicalPredecessorLane(), getFollowersOnConsecutive(), getIncomingLanes(), and getLogicalPredecessorLane().
myIndex
int MSLane::myIndex protected
The lane index.
Definition at line 1143 of file MSLane.h.
Referenced by GUILane::drawMarkings(), and getIndex().
myIsRampAccel
const bool MSLane::myIsRampAccel protected
whether this lane is an acceleration lane
Definition at line 1253 of file MSLane.h.
Referenced by isAccelLane().
myLeaderInfo
MSLeaderInfo MSLane::myLeaderInfo mutable protected
leaders on all sublanes as seen by approaching vehicles (cached)
Definition at line 1238 of file MSLane.h.
Referenced by getLastVehicleInformation().
myLeaderInfoTime
SUMOTime MSLane::myLeaderInfoTime mutable protected
time step for which myLeaderInfo was last updated
Definition at line 1245 of file MSLane.h.
Referenced by getLastVehicleInformation().
myLeaderInfoTmp
MSLeaderInfo MSLane::myLeaderInfoTmp mutable protected
Definition at line 1242 of file MSLane.h.
Referenced by getFirstVehicleInformation(), and getLastVehicleInformation().
myLength
double MSLane::myLength protected
Lane length [m].
Definition at line 1192 of file MSLane.h.
Referenced by basePos(), freeInsertion(), getBruttoOccupancy(), GUILane::getColorValue(), getFirstVehicleInformation(), getLength(), getNettoOccupancy(), GUILane::getParameterWindow(), GUILane::getScaleValue(), incorporateVehicle(), insertVehicle(), isInsertionSuccess(), setLength(), setPartialOccupation(), and GUILane::splitAtSegments().
myLengthGeometryFactor
const double MSLane::myLengthGeometryFactor protected
precomputed myShape.length / myLength
Definition at line 1250 of file MSLane.h.
Referenced by GUILane::getColorValue(), getLengthGeometryFactor(), GUILane::getScaleValue(), interpolateGeometryPosToLanePos(), and interpolateLanePosToGeometryPos().
myLinks
MSLinkCont MSLane::myLinks protected
The lane's Links to it's succeeding lanes and the default right-of-way rule, i.e. blocked or not blocked.
Definition at line 1232 of file MSLane.h.
Referenced by addLink(), appropriate(), detectCollisions(), GUILane::drawArrows(), GUILane::drawLane2LaneConnections(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), executeMovements(), getCanonicalSuccessorLane(), getCrossingIndex(), getLinkCont(), getLinkTo(), getOutgoingLanes(), isLinkEnd(), succLinkSec(), and ~MSLane().
myLogicalPredecessorLane
MSLane* MSLane::myLogicalPredecessorLane mutable protected
Definition at line 1216 of file MSLane.h.
Referenced by getLogicalPredecessorLane().
myManeuverReservations
VehCont MSLane::myManeuverReservations protected
The vehicles which registered maneuvering into the lane within their current action step. This is currently only relevant for sublane simulation, since continuous lanechanging uses the partial vehicle mechanism.
The entering vehicles are inserted at the front of this container and the leaving ones leave from the back.
Definition at line 1184 of file MSLane.h.
Referenced by isInsertionSuccess(), planMovements(), resetManeuverReservation(), setManeuverReservation(), sortManeuverReservations(), and updateLeaderInfo().
myMaxSpeed
double MSLane::myMaxSpeed protected
Lane-wide speedlimit [m/s].
Definition at line 1201 of file MSLane.h.
Referenced by GUILane::getColorValue(), getMeanSpeed(), GUILane::getScaleValue(), getSpeedLimit(), getVehicleMaxSpeed(), and setMaxSpeed().
myMoveReminders
std::vector< MSMoveReminder* > MSLane::myMoveReminders private
This lane's move reminder.
Definition at line 1274 of file MSLane.h.
Referenced by addMoveReminder(), and getMoveReminders().
myNeighs
std::vector<std::string> MSLane::myNeighs protected
Definition at line 1261 of file MSLane.h.
Referenced by addNeigh(), getOpposite(), and integrateNewVehicle().
myNettoVehicleLengthSum
double MSLane::myNettoVehicleLengthSum protected
The current length of all vehicles on this lane, excluding their minGaps.
Definition at line 1228 of file MSLane.h.
Referenced by enteredByLaneChange(), executeMovements(), getNettoOccupancy(), incorporateVehicle(), integrateNewVehicle(), leftByLaneChange(), and removeVehicle().
myNumericalID
int MSLane::myNumericalID protected
Unique numerical ID (set on reading by netload)
Definition at line 1137 of file MSLane.h.
Referenced by getNumericalID().
myOriginalPermissions
SVCPermissions MSLane::myOriginalPermissions protected
The original vClass permissions for this lane (before temporary modifications)
Definition at line 1207 of file MSLane.h.
Referenced by resetPermissions(), and setPermissions().
myParkingVehicles
std::set<const MSVehicle*> MSLane::myParkingVehicles protected
Definition at line 1189 of file MSLane.h.
Referenced by addParking(), GUILane::drawGL(), executeMovements(), getParkingVehicles(), and removeParking().
myPartialVehicles
VehCont MSLane::myPartialVehicles protected
The lane's partial vehicles. This container holds all vehicles that are partially on this lane but which are in myVehicles of another lane. Reasons for partial occupancies include the following.
the back is still on this lane during regular movement
the vehicle is performing a continuous lane-change maneuver
sub-lane simulation where vehicles can freely move laterally among the lanes of an edge
The entering vehicles are inserted at the front of this container and the leaving ones leave from the back.
Definition at line 1168 of file MSLane.h.
Referenced by anyVehiclesBegin(), anyVehiclesEnd(), anyVehiclesUpstreamBegin(), detectCollisions(), freeInsertion(), getBruttoOccupancy(), getFirstAnyVehicle(), getLastAnyVehicle(), getLeaderOnConsecutive(), getLeadersOnConsecutive(), getNettoOccupancy(), getPartialBehind(), getPartialBeyond(), getPartialVehicleNumber(), MSLaneChanger::getRealLeader(), getVehicleNumberWithPartials(), integrateNewVehicle(), isEmpty(), isInsertionSuccess(), MSLane::AnyVehicleIterator::nextIsMyVehicles(), MSLane::AnyVehicleIterator::operator*(), planMovements(), resetPartialOccupation(), setPartialOccupation(), sortPartialVehicles(), and updateLeaderInfo().
myPermissionChanges
std::map<long, SVCPermissions> MSLane::myPermissionChanges protected
Definition at line 1264 of file MSLane.h.
Referenced by GUILane::closeTraffic(), GUILane::getPopUpMenu(), resetPermissions(), and setPermissions().
myPermissions
SVCPermissions MSLane::myPermissions protected
The vClass permissions for this lane.
Definition at line 1204 of file MSLane.h.
Referenced by allowsVehicleClass(), GUILane::drawAsRailway(), GUILane::drawAsWaterway(), GUILane::drawGL(), GUILane::drawMarkings(), GUILane::getColorValue(), GUILane::getParameterWindow(), getPermissions(), resetPermissions(), and setPermissions().
myRestrictions
const std::map<SUMOVehicleClass, double>* MSLane::myRestrictions protected
The vClass speed restrictions for this lane.
Definition at line 1210 of file MSLane.h.
Referenced by getVehicleMaxSpeed(), and initRestrictions().
myRightmostSublane
int MSLane::myRightmostSublane protected
the index of the rightmost sublane of this lane on myEdge
Definition at line 1258 of file MSLane.h.
Referenced by getRightmostSublane(), and setRightSideOnEdge().
myRightSideOnEdge
double MSLane::myRightSideOnEdge protected
the combined width of all lanes with lower index on myEdge
Definition at line 1256 of file MSLane.h.
Referenced by getCenterOnEdge(), getRightSideOnEdge(), and setRightSideOnEdge().
myShape
PositionVector MSLane::myShape protected
The shape of the lane.
Definition at line 1140 of file MSLane.h.
Referenced by GUILane::drawGL(), geometryPositionAtOffset(), GUILane::getCenteringBoundary(), GUILane::getPopUpMenu(), GUILane::getShape(), getShape(), GUILane::GUILane(), GUILane::setFunctionalColor(), and GUILane::setMultiColor().
myTmpVehicles
VehCont MSLane::myTmpVehicles protected
Container for lane-changing vehicles. After completion of lane-change- process, the containers will be swapped with myVehicles.
Definition at line 1172 of file MSLane.h.
Referenced by getLeader(), MSLaneChanger::ChangeElem::registerHop(), and swapAfterLaneChange().
myVehBuffer
VehCont MSLane::myVehBuffer protected
Buffer for vehicles that moved from their previous lane onto this one. Integrated after all vehicles executed their moves.
Definition at line 1176 of file MSLane.h.
Referenced by empty(), executeMovements(), integrateNewVehicle(), and MSXMLRawOut::writeLane().
myVehicles
VehCont MSLane::myVehicles protected
The lane's vehicles. This container holds all vehicles that have their front (longitudinally) and their center (laterally) on this lane. These are the vehicles that this lane is 'responsibly' for (i.e. when executing movements)
The entering vehicles are inserted at the front of this container and the leaving ones leave from the back, e.g. the vehicle in front of the junction (often called first) is myVehicles.back() (if it exists). And if it is an iterator at a vehicle, ++it points to the vehicle in front. This is the interaction vehicle.
Definition at line 1156 of file MSLane.h.
Referenced by addMoveReminder(), anyVehiclesBegin(), anyVehiclesEnd(), anyVehiclesUpstreamBegin(), detectCollisions(), empty(), executeMovements(), GUILane::firstWaitingTime(), forceVehicleInsertion(), freeInsertion(), getBruttoOccupancy(), getFirstAnyVehicle(), getFirstFullVehicle(), getLastAnyVehicle(), getLastFullVehicle(), getLeader(), getMeanSpeed(), getNettoOccupancy(), getVehicleNumber(), getVehicleNumberWithPartials(), GUILane::getVehiclesSecure(), getVehiclesSecure(), getWaitingSeconds(), incorporateVehicle(), integrateNewVehicle(), isEmpty(), isInsertionSuccess(), loadState(), MSLane::AnyVehicleIterator::nextIsMyVehicles(), MSLane::AnyVehicleIterator::operator*(), planMovements(), removeVehicle(), saveState(), swapAfterLaneChange(), MSQueueExport::writeLane(), and MSXMLRawOut::writeLane().
myWidth
const double MSLane::myWidth protected
Lane width [m].
Definition at line 1195 of file MSLane.h.
Referenced by GUILane::drawArrows(), GUILane::drawDirectionIndicators(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), getCenterOnEdge(), GUILane::getParameterWindow(), getWidth(), and GUILane::GUILane().
The documentation for this class was generated from the following files:
MSLane.h
MSLane.cpp