SUMO - Simulation of Urban MObility: Bresenham::BresenhamCallBack Class Reference
Bresenham::BresenhamCallBack Class Reference abstract
#include <Bresenham.h>
Public Member Functions
BresenhamCallBack ()
virtual void execute (const int val1, const int val2)=0
virtual ~BresenhamCallBack ()
Detailed Description
BresenhamCallBack This class is the base interface-describing class for a callback class for the bresenham-function. Derived classes must implement the execute-method which is called on every bresenham-step
Definition at line 50 of file Bresenham.h.
Constructor & Destructor Documentation
BresenhamCallBack()
Bresenham::BresenhamCallBack::BresenhamCallBack () inline
constuctor
Definition at line 53 of file Bresenham.h.
~BresenhamCallBack()
virtual Bresenham::BresenhamCallBack::~BresenhamCallBack () inline virtual
destructor
Definition at line 56 of file Bresenham.h.
References Bresenham::compute(), and execute().
Member Function Documentation
execute()
virtual void Bresenham::BresenhamCallBack::execute (const int val1, const int val2) pure virtual
called when a bresenham step has been computed
Implemented in NBEdge::ToEdgeConnectionsAdder, and NBNode::ApproachingDivider.
Referenced by Bresenham::compute(), and ~BresenhamCallBack().
The documentation for this class was generated from the following file:
Bresenham.h