SUMO - Simulation of Urban MObility: libsumo::Route Class Reference
libsumo::Route Class Reference
#include <Route.h>
Static Public Member Functions
static void add (const std::string &routeID, const std::vector< std::string > &edgeIDs)
static std::vector< std::string > getEdges (const std::string &routeID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::string getParameter (const std::string &routeID, const std::string &param)
static const MSRoute * getRoute (const std::string &id)
static void setParameter (const std::string &routeID, const std::string &key, const std::string &value)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
Route & operator= (const Route &src)
invalidated assignment operator
Route ()
invalidated standard constructor
Route (const Route &src)
invalidated copy constructor
Detailed Description
Definition at line 51 of file Route.h.
Constructor & Destructor Documentation
Route() [1/2]
libsumo::Route::Route () private
invalidated standard constructor
Route() [2/2]
libsumo::Route::Route (const Route & src) private
invalidated copy constructor
Member Function Documentation
add()
void Route::add (const std::string & routeID, const std::vector< std::string > & edgeIDs) static
Definition at line 82 of file Route.cpp.
References MSRoute::dictionary(), and MSEdge::dictionary().
Referenced by TraCIServerAPI_Route::processSet().
getEdges()
std::vector< std::string > Route::getEdges (const std::string & routeID) static
Definition at line 52 of file Route.cpp.
References MSRoute::getEdges(), and getRoute().
Referenced by TraCIServerAPI_Route::processGet().
getIDCount()
int Route::getIDCount () static
Definition at line 63 of file Route.cpp.
References getIDList().
Referenced by TraCIServerAPI_Route::processGet().
getIDList()
std::vector< std::string > Route::getIDList () static
Definition at line 45 of file Route.cpp.
References MSRoute::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Route::processGet().
getParameter()
std::string Route::getParameter (const std::string & routeID, const std::string & param) static
Definition at line 69 of file Route.cpp.
References Parameterised::getParameter(), and getRoute().
Referenced by TraCIServerAPI_Route::processGet().
getRoute()
const MSRoute * Route::getRoute (const std::string & id) static
Definition at line 99 of file Route.cpp.
References MSRoute::dictionary().
Referenced by getEdges(), getParameter(), and setParameter().
operator=()
Route& libsumo::Route::operator= (const Route & src) private
invalidated assignment operator
setParameter()
void Route::setParameter (const std::string & routeID, const std::string & key, const std::string & value) static
Definition at line 75 of file Route.cpp.
References getRoute(), and Parameterised::setParameter().
Referenced by TraCIServerAPI_Route::processSet().
subscribe()
static void libsumo::Route::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
subscribeContext()
static void libsumo::Route::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
Route.h
Route.cpp