SUMO - Simulation of Urban MObility: marouter_main.cpp File Reference
marouter_main.cpp File Reference
#include <config.h>
#include <xercesc/sax/SAXException.hpp>
#include <xercesc/sax/SAXParseException.hpp>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <limits.h>
#include <ctime>
#include <vector>
#include <utils/common/MsgHandler.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/RandHelper.h>
#include <utils/common/ToString.h>
#include <utils/distribution/Distribution_Points.h>
#include <utils/iodevices/OutputDevice.h>
#include <utils/iodevices/OutputDevice_String.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/vehicle/RouteCostCalculator.h>
#include <utils/vehicle/DijkstraRouter.h>
#include <utils/vehicle/AStarRouter.h>
#include <utils/vehicle/CHRouter.h>
#include <utils/vehicle/CHRouterWrapper.h>
#include <utils/xml/XMLSubSys.h>
#include <od/ODCell.h>
#include <od/ODDistrict.h>
#include <od/ODDistrictCont.h>
#include <od/ODDistrictHandler.h>
#include <od/ODMatrix.h>
#include <router/ROEdge.h>
#include <router/ROLoader.h>
#include <router/RONet.h>
#include <router/RORoute.h>
#include <router/RORoutable.h>
#include "ROMAFrame.h"
#include "ROMAAssignments.h"
#include "ROMAEdgeBuilder.h"
#include "ROMARouteHandler.h"
#include "ROMAEdge.h"
Functions
void computeAllPairs (RONet &net, OptionsCont &oc)
void computeRoutes (RONet &net, OptionsCont &oc, ODMatrix &matrix)
double getTravelTime (const ROEdge *const edge, const ROVehicle *const, double)
void initNet (RONet &net, ROLoader &loader, OptionsCont &oc)
int main (int argc, char **argv)
void writeInterval (OutputDevice &dev, const SUMOTime begin, const SUMOTime end, const RONet &net, const ROVehicle *const veh)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Laura Bieker
Michael Behrisch
Date
Thu, 06 Jun 2002
Version
$Id$
Definition in file marouter_main.cpp.
Function Documentation
computeAllPairs()
void computeAllPairs (RONet & net, OptionsCont & oc)
Computes all pair shortest paths, saving them
Definition at line 122 of file marouter_main.cpp.
References ROEdge::getAllEdges(), OptionsCont::getBool(), RONet::getEdgeNumber(), RONet::getInternalEdgeNumber(), OptionsCont::getString(), getTravelTime(), and FileHelpers::writeFloat().
Referenced by main().
computeRoutes()
void computeRoutes (RONet & net, OptionsCont & oc, ODMatrix & matrix)
Computes the routes saving them
Definition at line 180 of file marouter_main.cpp.
References ODMatrix::applyCurve(), ODCell::begin, RONet::cleanup(), OutputDevice::closeTag(), OutputDevice::createDeviceByOption(), DEFAULT_VTYPE_ID, ODCell::departures, ODCell::destination, ODCell::end, ROEdge::getAllEdges(), OptionsCont::getBool(), ODMatrix::getCells(), OutputDevice::getDeviceByOption(), OptionsCont::getFloat(), OptionsCont::getInt(), ROEdge::getNoiseEffort(), OptionsCont::getOptions(), ROMAAssignments::getPenalizedEffort(), ROMAAssignments::getPenalizedTT(), RONet::getRouteOutput(), OptionsCont::getString(), OptionsCont::getStringVector(), ROMAAssignments::getTravelTime(), ROEdge::getTravelTimeStatic(), RONet::getVehicleTypeSecure(), RONet::hasPermissions(), OutputDevice::isBinary(), OptionsCont::isSet(), MIN2(), RONet::openOutput(), OutputDevice::openTag(), ODCell::origin, ODMatrix::parseTimeLine(), ODCell::pathsVector, SUMOAbstractRouter< E, V >::recomputeCosts(), ROMAAssignments::resetFlows(), ODMatrix::sortByBeginTime(), string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_DEPART, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_KEY, SUMO_ATTR_NUMBER, SUMO_ATTR_VALUE, SUMO_TAG_FLOW, SUMO_TAG_PARAM, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, SVC_IGNORING, time2string(), toString(), ODCell::vehicleNumber, OutputDevice::writeAttr(), writeInterval(), and OutputDevice::writePreformattedTag().
Referenced by main().
getTravelTime()
double getTravelTime (const ROEdge *const edge, const ROVehicle * const, double)
Definition at line 113 of file marouter_main.cpp.
References ROEdge::getLength(), and ROEdge::getSpeedLimit().
Referenced by computeAllPairs().
initNet()
void initNet (RONet & net, ROLoader & loader, OptionsCont & oc)
loads the net The net is in this meaning made up by the net itself and the dynamic weights which may be supplied in a separate file
Definition at line 92 of file marouter_main.cpp.
References OptionsCont::getBool(), OptionsCont::getString(), OptionsCont::isSet(), ROLoader::loadNet(), ROLoader::loadWeights(), and ROEdge::setGlobalOptions().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 417 of file marouter_main.cpp.
References TplConvert::_2str(), ROMAFrame::checkOptions(), MsgHandler::clear(), SystemFrame::close(), computeAllPairs(), computeRoutes(), ROMAFrame::fillOptions(), OptionsCont::getBool(), RONet::getDistricts(), MsgHandler::getErrorInstance(), ODMatrix::getNumLoaded(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), initNet(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), OptionsCont::isSet(), ODMatrix::loadMatrix(), ODMatrix::loadRoutes(), ODDistrictCont::makeDistricts(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), toString(), VERSION_STRING, WRITE_ERROR, and WRITE_MESSAGE.
writeInterval()
void writeInterval (OutputDevice & dev, const SUMOTime begin, const SUMOTime end, const RONet & net, const ROVehicle *const veh)
Writes the travel times for a single interval
Definition at line 157 of file marouter_main.cpp.
References NamedObjectCont< T >::begin(), OutputDevice::closeTag(), EDGEFUNC_NORMAL, NamedObjectCont< T >::end(), ROMAAssignments::getCapacity(), RONet::getEdgeMap(), ROMAEdge::getFlow(), ROEdge::getFunction(), Named::getID(), ROEdge::getLength(), ROEdge::getTravelTime(), OutputDevice::openTag(), STEPS2TIME, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_TAG_EDGE, SUMO_TAG_INTERVAL, time2string(), and OutputDevice::writeAttr().
Referenced by computeRoutes().