SUMO - Simulation of Urban MObility: RODFEdge Class Reference
RODFEdge Class Reference
#include <RODFEdge.h>
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
double getDistanceTo (const ROEdge *other) const
optimistic distance heuristic for use in routing
const std::vector< FlowDef > & getFlows () const
const RONode * getFromJunction () const
const std::string & getID () const
Returns the id.
const std::vector< ROLane * > & getLanes () const
Returns this edge's lanes.
int getPriority () const
get edge priority (road class)
const RONode * getToJunction () const
RODFEdge (const std::string &id, RONode *from, RONode *to, int index, const int priority)
Constructor.
void setFlows (const std::vector< FlowDef > &flows)
void setID (const std::string &newID)
resets the id
~RODFEdge ()
Destructor.
Set-up methods
virtual void addLane (ROLane *lane)
Adds a lane to the edge while loading.
virtual void addSuccessor (ROEdge *s, std::string dir="")
Adds information about a connected edge.
void setFunction (SumoXMLEdgeFunc func)
Sets the function of the edge.
void setSource (const bool isSource=true)
Sets whether the edge is a source.
void setSink (const bool isSink=true)
Sets whether the edge is a sink.
void setRestrictions (const std::map< SUMOVehicleClass, double > *restrictions)
Sets the vehicle class specific speed limits of the edge.
bool isInternal () const
return whether this edge is an internal edge
bool isCrossing () const
return whether this edge is a pedestrian crossing
bool isWalkingArea () const
return whether this edge is walking area
bool isTazConnector () const
void buildTimeLines (const std::string &measure, const bool boundariesOverride)
Builds the internal representation of the travel time/effort.
Getter methods
SumoXMLEdgeFunc getFunction () const
Returns the function of the edge.
bool isSink () const
Returns whether the edge acts as a sink.
double getLength () const
Returns the length of the edge.
int getNumericalID () const
Returns the index (numeric id) of the edge.
double getSpeedLimit () const
Returns the speed allowed on this edge.
double getLengthGeometryFactor () const
return a lower bound on shape.length() / myLength that is
double getVClassMaxSpeed (SUMOVehicleClass vclass) const
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
int getNumLanes () const
Returns the number of lanes this edge has.
bool isConnectedTo (const ROEdge *const e, const ROVehicle *const vehicle) const
returns the information whether this edge is directly connected to the given
bool prohibits (const ROVehicle *const vehicle) const
Returns whether this edge prohibits the given vehicle to pass it.
SVCPermissions getPermissions () const
bool allFollowersProhibit (const ROVehicle *const vehicle) const
Returns whether this edge succeeding edges prohibit the given vehicle to pass them.
Static Public Member Functions
static int dictSize ()
Returns the number of edges.
static const ROEdgeVector & getAllEdges ()
Returns all ROEdges.
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void setGlobalOptions (const bool interpolate)
Protected Member Functions
bool getStoredEffort (double time, double &ret) const
Retrieves the stored effort.
Protected Attributes
bool myAmSink
whether the edge is a source or a sink
bool myAmSource
ROEdgeVector myApproachingEdges
List of edges that approached this edge.
std::map< SUMOVehicleClass, ROEdgeVector > myClassesSuccessorMap
The successors available for a given vClass.
SVCPermissions myCombinedPermissions
The list of allowed vehicle classes combined across lanes.
ValueTimeLine< double > myEfforts
Container storing passing time varying over time for the edge.
ROEdgeVector myFollowingEdges
List of edges that may be approached from this edge.
RONode * myFromJunction
the junctions for this edge
SumoXMLEdgeFunc myFunction
The function of the edge.
std::string myID
The name of the object.
const int myIndex
The index (numeric id) of the edge.
std::vector< ROLane * > myLanes
This edge's lanes.
double myLength
The length of the edge.
const int myPriority
The edge priority (road class)
const std::map< SUMOVehicleClass, double > * myRestrictions
The vClass speed restrictions for this edge.
double mySpeed
The maximum speed allowed on this edge.
Boundary myTazBoundary
The bounding rectangle of incoming or outgoing edges for taz connectors.
RONode * myToJunction
ValueTimeLine< double > myTravelTimes
Container storing passing time varying over time for the edge.
bool myUsingETimeLine
Information whether the time line shall be used instead of the length value.
bool myUsingTTTimeLine
Information whether the time line shall be used instead of the length value.
Static Protected Attributes
static ROEdgeVector myEdges
static bool myHaveEWarned = false
Information whether the edge has reported missing weights.
static bool myHaveTTWarned = false
Information whether the edge has reported missing weights.
static bool myInterpolate = false
Information whether to interpolate at interval boundaries.
Private Member Functions
RODFEdge & operator= (const RODFEdge &src)
Invalidated assignment operator.
RODFEdge (const RODFEdge &src)
Invalidated copy constructor.
Private Attributes
std::vector< FlowDef > myFlows
Methods for getting/setting travel time and cost information
void addEffort (double value, double timeBegin, double timeEnd)
Adds a weight value.
void addTravelTime (double value, double timeBegin, double timeEnd)
Adds a travel time value.
int getNumSuccessors () const
Returns the number of edges this edge is connected to.
const ROEdgeVector & getSuccessors () const
Returns the following edges.
const ROEdgeVector & getSuccessors (SUMOVehicleClass vClass) const
Returns the following edges, restricted by vClass.
int getNumPredecessors () const
Returns the number of edges connected to this edge.
const ROEdgeVector & getPredecessors () const
Returns the edge at the given position from the list of incoming edges.
const ROEdge * getNormalBefore () const
if this edge is an internal edge, return its first normal predecessor, otherwise the edge itself
const ROEdge * getNormalAfter () const
if this edge is an internal edge, return its first normal successor, otherwise the edge itself
double getEffort (const ROVehicle *const veh, double time) const
Returns the effort for this edge.
bool hasLoadedTravelTime (double time) const
Returns whether a travel time for this edge was loaded.
double getTravelTime (const ROVehicle *const veh, double time) const
Returns the travel time for this edge.
double getMinimumTravelTime (const ROVehicle *const veh) const
Returns a lower bound for the travel time on this edge without using any stored timeLine.
static double getEffortStatic (const ROEdge *const edge, const ROVehicle *const veh, double time)
Returns the effort for the given edge.
static double getTravelTimeStatic (const ROEdge *const edge, const ROVehicle *const veh, double time)
Returns the travel time for the given edge.
template<PollutantsInterface::EmissionType ET>
static double getEmissionEffort (const ROEdge *const edge, const ROVehicle *const veh, double time)
static double getNoiseEffort (const ROEdge *const edge, const ROVehicle *const veh, double time)
Detailed Description
Definition at line 54 of file RODFEdge.h.
Constructor & Destructor Documentation
RODFEdge() [1/2]
RODFEdge::RODFEdge (const std::string & id, RONode * from, RONode * to, int index, const int priority)
Constructor.
Parameters
[in] id The id of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] index The numeric id of the edge
Definition at line 41 of file RODFEdge.cpp.
~RODFEdge()
RODFEdge::~RODFEdge ()
Destructor.
Definition at line 45 of file RODFEdge.cpp.
RODFEdge() [2/2]
RODFEdge::RODFEdge (const RODFEdge & src) private
Invalidated copy constructor.
Member Function Documentation
addEffort()
void ROEdge::addEffort (double value, double timeBegin, double timeEnd) inherited
Adds a weight value.
Parameters
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 129 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), ROEdge::myEfforts, and ROEdge::myUsingETimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), and ROEdge::getPermissions().
addLane()
void ROEdge::addLane (ROLane * lane) virtual inherited
Adds a lane to the edge while loading.
The lane's length is adapted. Additionally, the information about allowed/disallowed vehicle classes is patched using the information stored in the lane.
Parameters
[in] lane The lane to add
Todo:
What about vehicle-type aware connections?
Definition at line 93 of file ROEdge.cpp.
References ROLane::getLength(), ROLane::getPermissions(), ROLane::getSpeed(), ROEdge::myCombinedPermissions, ROEdge::myLanes, ROEdge::myLength, and ROEdge::mySpeed.
Referenced by RONetHandler::parseLane().
addSuccessor()
void ROEdge::addSuccessor (ROEdge * s, std::string dir = "") virtual inherited
Adds information about a connected edge.
The edge s is added to "myFollowingEdges" and this edge is added as predecessor to s.
Parameters
[in] s The edge to add
Todo:
What about vehicle-type aware connections?
Reimplemented in ROMAEdge, and ROJTREdge.
Definition at line 106 of file ROEdge.cpp.
References Boundary::add(), ROEdge::getFromJunction(), RONode::getPosition(), ROEdge::getToJunction(), ROEdge::isInternal(), ROEdge::isTazConnector(), ROEdge::myApproachingEdges, ROEdge::myFollowingEdges, and ROEdge::myTazBoundary.
Referenced by RONet::addDistrictEdge(), ROJTREdge::addSuccessor(), and ROMAEdge::addSuccessor().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
addTravelTime()
void ROEdge::addTravelTime (double value, double timeBegin, double timeEnd) inherited
Adds a travel time value.
Parameters
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 136 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), ROEdge::myTravelTimes, and ROEdge::myUsingTTTimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), ROEdge::getPermissions(), ROMAAssignments::incremental(), and ROMAAssignments::sue().
allFollowersProhibit()
bool ROEdge::allFollowersProhibit (const ROVehicle *const vehicle) const inherited
Returns whether this edge succeeding edges prohibit the given vehicle to pass them.
Parameters
[in] vehicle The vehicle for which the information has to be returned
Returns
Whether the vehicle may continue its route on any of the following edges
Definition at line 308 of file ROEdge.cpp.
References ROEdge::myFollowingEdges.
Referenced by ROJTREdge::chooseNext(), and ROEdge::getPermissions().
buildTimeLines()
void ROEdge::buildTimeLines (const std::string & measure, const bool boundariesOverride) inherited
Builds the internal representation of the travel time/effort.
Should be called after weights / travel times have been loaded.
In the case "weight-attribute" is one of "CO", "CO2", "HC", "NOx", "PMx", "fuel", or "electricity" the proper value (departs/s) is computed and multiplied with the travel time.
Parameters
[in] measure The name of the measure to use.
Definition at line 274 of file ROEdge.cpp.
References PollutantsInterface::CO, PollutantsInterface::CO2, PollutantsInterface::compute(), PollutantsInterface::ELEC, ValueTimeLine< T >::fillGaps(), PollutantsInterface::FUEL, PollutantsInterface::getClassByName(), PollutantsInterface::HC, ROEdge::myEfforts, ROEdge::myLength, ROEdge::mySpeed, ROEdge::myTravelTimes, ROEdge::myUsingETimeLine, ROEdge::myUsingTTTimeLine, PollutantsInterface::NO_X, and PollutantsInterface::PM_X.
Referenced by ROEdge::isTazConnector().
dictSize()
static int ROEdge::dictSize () inline static inherited
Returns the number of edges.
Definition at line 450 of file ROEdge.h.
References ROEdge::myEdges.
getAllEdges()
const ROEdgeVector & ROEdge::getAllEdges () static inherited
Returns all ROEdges.
Definition at line 319 of file ROEdge.cpp.
References ROEdge::myEdges.
Referenced by computeAllPairs(), computeRoutes(), and ROEdge::getEmissionEffort().
getDistanceTo()
double ROEdge::getDistanceTo (const ROEdge * other) const inherited
optimistic distance heuristic for use in routing
Definition at line 153 of file ROEdge.cpp.
References Boundary::distanceTo2D(), Position::distanceTo2D(), ROEdge::getFromJunction(), RONode::getPosition(), ROEdge::getToJunction(), ROEdge::isTazConnector(), and ROEdge::myTazBoundary.
Referenced by ROEdge::getEmissionEffort().
getEffort()
double ROEdge::getEffort (const ROVehicle *const veh, double time) const inherited
Returns the effort for this edge.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned [s]
Returns
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 143 of file ROEdge.cpp.
References ROEdge::getStoredEffort(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::myLength, and ROEdge::mySpeed.
Referenced by ROEdge::getEffortStatic(), ROMAAssignments::getPenalizedEffort(), and ROEdge::getPredecessors().
getEffortStatic()
static double ROEdge::getEffortStatic (const ROEdge *const edge, const ROVehicle *const veh, double time) inline static inherited
Returns the effort for the given edge.
Parameters
[in] edge The edge for which the effort shall be retrieved
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Returns
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 392 of file ROEdge.h.
References ROEdge::getEffort().
getEmissionEffort()
template<PollutantsInterface::EmissionType ET> static double ROEdge::getEmissionEffort (const ROEdge *const edge, const ROVehicle *const veh, double time) inline static inherited
Definition at line 426 of file ROEdge.h.
References PollutantsInterface::computeDefault(), SUMOVTypeParameter::emissionClass, ROEdge::getAllEdges(), SUMOVTypeParameter::getCFParam(), SUMOVTypeParameter::getDefaultAccel(), SUMOVTypeParameter::getDefaultImperfection(), ROEdge::getDistanceTo(), ROEdge::getNoiseEffort(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMO_ATTR_ACCEL, SUMO_ATTR_SIGMA, and SUMOVTypeParameter::vehicleClass.
getFlows()
const std::vector< FlowDef > & RODFEdge::getFlows () const
Definition at line 55 of file RODFEdge.cpp.
References myFlows.
Referenced by RODFNet::revalidateFlows().
getFromJunction()
const RONode* ROEdge::getFromJunction () const inline inherited
Definition at line 463 of file ROEdge.h.
References ROEdge::myFromJunction.
Referenced by ROEdge::addSuccessor(), RODFNet::buildApproachList(), AGPosition::compute2dPosition(), and ROEdge::getDistanceTo().
getFunction()
SumoXMLEdgeFunc ROEdge::getFunction () const inline inherited
Returns the function of the edge.
Returns
This edge's basic function
See also
SumoXMLEdgeFunc
Definition at line 188 of file ROEdge.h.
References ROEdge::myFunction.
Referenced by writeInterval().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getLanes()
const std::vector<ROLane*>& ROEdge::getLanes () const inline inherited
Returns this edge's lanes.
Returns
This edge's lanes
Definition at line 476 of file ROEdge.h.
References ROEdge::getStoredEffort(), and ROEdge::myLanes.
Referenced by RONetHandler::parseConnection().
getLength()
double ROEdge::getLength () const inline inherited
Returns the length of the edge.
Returns
This edge's length
Definition at line 204 of file ROEdge.h.
References ROEdge::myLength.
Referenced by RORouteHandler::addPersonTrip(), RORouteHandler::addStop(), RODFNet::buildRoutes(), ROMAAssignments::capacityConstraintFunction(), AGPosition::compute2dPosition(), RODFNet::getAbsPos(), getTravelTime(), RONetHandler::parseStoppingPlace(), AGActivityGenHandler::parseStreets(), AGStreet::print(), AGPosition::print(), AGPosition::randomPositionInStreet(), and writeInterval().
getLengthGeometryFactor()
double ROEdge::getLengthGeometryFactor () const inline inherited
return a lower bound on shape.length() / myLength that is
Definition at line 225 of file ROEdge.h.
References Position::distanceTo(), RONode::getPosition(), MAX2(), ROEdge::myFromJunction, ROEdge::myLength, and ROEdge::myToJunction.
getMinimumTravelTime()
double ROEdge::getMinimumTravelTime (const ROVehicle *const veh) const inline inherited
Returns a lower bound for the travel time on this edge without using any stored timeLine.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Definition at line 414 of file ROEdge.h.
References ROVehicle::getChosenSpeedFactor(), RORoutable::getType(), ROEdge::isTazConnector(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::myLength, and ROEdge::mySpeed.
Referenced by ROEdge::getTravelTime().
getNoiseEffort()
double ROEdge::getNoiseEffort (const ROEdge *const edge, const ROVehicle *const veh, double time) static inherited
Definition at line 198 of file ROEdge.cpp.
References HelpersHarmonoise::computeNoise(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), and ROEdge::mySpeed.
Referenced by computeRoutes(), and ROEdge::getEmissionEffort().
getNormalAfter()
const ROEdge * ROEdge::getNormalAfter () const inherited
if this edge is an internal edge, return its first normal successor, otherwise the edge itself
Definition at line 263 of file ROEdge.cpp.
References ROEdge::isInternal(), and ROEdge::myFollowingEdges.
Referenced by ROEdge::getPredecessors(), and RORouteDef::repairCurrentRoute().
getNormalBefore()
const ROEdge * ROEdge::getNormalBefore () const inherited
if this edge is an internal edge, return its first normal predecessor, otherwise the edge itself
Definition at line 252 of file ROEdge.cpp.
References ROEdge::isInternal(), and ROEdge::myApproachingEdges.
Referenced by RORouteHandler::addStop(), ROEdge::getPredecessors(), and RORouteDef::repairCurrentRoute().
getNumericalID()
int ROEdge::getNumericalID () const inline inherited
Returns the index (numeric id) of the edge.
Returns
This edge's numerical id
Definition at line 211 of file ROEdge.h.
References ROEdge::myIndex.
Referenced by RONet::createBulkRouteRequests().
getNumLanes()
int ROEdge::getNumLanes () const inline inherited
Returns the number of lanes this edge has.
Returns
This edge's number of lanes
Definition at line 251 of file ROEdge.h.
References ROEdge::isConnectedTo(), and ROEdge::myLanes.
Referenced by ROMAAssignments::capacityConstraintFunction(), ROMAAssignments::getCapacity(), and RODFDetectorHandler::myStartElement().
getNumPredecessors()
int ROEdge::getNumPredecessors () const inherited
Returns the number of edges connected to this edge.
If this edge's type is set to "source", 0 is returned, otherwise the number of edges stored in "myApproachingEdges".
Returns
The number of edges reaching into this edge
Definition at line 243 of file ROEdge.cpp.
References ROEdge::myAmSource, and ROEdge::myApproachingEdges.
Referenced by ROEdge::getSuccessors(), and RORouteHandler::parseFromViaTo().
getNumSuccessors()
int ROEdge::getNumSuccessors () const inherited
Returns the number of edges this edge is connected to.
If this edge's type is set to "sink", 0 is returned, otherwise the number of edges stored in "myFollowingEdges".
Returns
The number of edges following this edge
Definition at line 234 of file ROEdge.cpp.
References ROEdge::myAmSink, and ROEdge::myFollowingEdges.
Referenced by RODFDetector::computeSplitProbabilities(), ROEdge::getPermissions(), and RORouteHandler::parseFromViaTo().
getPermissions()
SVCPermissions ROEdge::getPermissions () const inline inherited
Definition at line 274 of file ROEdge.h.
References ROEdge::addEffort(), ROEdge::addTravelTime(), ROEdge::allFollowersProhibit(), ROEdge::getNumSuccessors(), and ROEdge::myCombinedPermissions.
Referenced by AGStreet::allows().
getPredecessors()
const ROEdgeVector& ROEdge::getPredecessors () const inline inherited
Returns the edge at the given position from the list of incoming edges.
Parameters
[in] pos The position of the list within the list of incoming
Returns
The incoming edge, stored at position pos
Definition at line 347 of file ROEdge.h.
References ROEdge::getEffort(), ROEdge::getNormalAfter(), ROEdge::getNormalBefore(), ROEdge::getTravelTime(), ROEdge::hasLoadedTravelTime(), and ROEdge::myApproachingEdges.
Referenced by RODFDetector::computeSplitProbabilities().
getPriority()
int ROEdge::getPriority () const inline inherited
get edge priority (road class)
Definition at line 459 of file ROEdge.h.
References ROEdge::myPriority.
Referenced by ROMAAssignments::capacityConstraintFunction(), and ROMAAssignments::getCapacity().
getSpeedLimit()
double ROEdge::getSpeedLimit () const inline inherited
Returns the speed allowed on this edge.
Returns
The speed allowed on this edge
Definition at line 219 of file ROEdge.h.
References ROEdge::mySpeed.
Referenced by RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), ROMAAssignments::capacityConstraintFunction(), RODFNet::computeRoutesFor(), ROMAAssignments::getCapacity(), getTravelTime(), RODFNet::isDestination(), RODFNet::isFalseSource(), and RODFNet::isSource().
getStoredEffort()
bool ROEdge::getStoredEffort (double time, double & ret) const protected inherited
Retrieves the stored effort.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned
Returns
Whether the effort is given
Definition at line 209 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getSplitTime(), ValueTimeLine< T >::getValue(), ROEdge::myEfforts, ROEdge::myHaveEWarned, Named::myID, ROEdge::myInterpolate, ROEdge::myTravelTimes, ROEdge::myUsingETimeLine, toString(), and WRITE_WARNING.
Referenced by ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getLanes(), and ROEdge::getNoiseEffort().
getSuccessors() [1/2]
const ROEdgeVector& ROEdge::getSuccessors () const inline inherited
Returns the following edges.
Definition at line 321 of file ROEdge.h.
References ROEdge::getNumPredecessors(), and ROEdge::myFollowingEdges.
Referenced by RODFNet::buildApproachList(), and ROEdge::isConnectedTo().
getSuccessors() [2/2]
const ROEdgeVector & ROEdge::getSuccessors (SUMOVehicleClass vClass) const inherited
Returns the following edges, restricted by vClass.
Parameters
[in] vClass The vClass for which to restrict the successors
Returns
The eligible following edges
Definition at line 325 of file ROEdge.cpp.
References ROLane::getEdge(), RONet::getInstance(), ROLane::getOutgoingLanes(), ROLane::getPermissions(), ROEdge::isTazConnector(), ROEdge::myClassesSuccessorMap, ROEdge::myFollowingEdges, ROEdge::myLanes, and SVC_IGNORING.
getToJunction()
const RONode* ROEdge::getToJunction () const inline inherited
Definition at line 467 of file ROEdge.h.
References ROEdge::myToJunction.
Referenced by ROEdge::addSuccessor(), RODFNet::buildApproachList(), AGPosition::compute2dPosition(), and ROEdge::getDistanceTo().
getTravelTime()
double ROEdge::getTravelTime (const ROVehicle *const veh, double time) const inherited
Returns the travel time for this edge.
Parameters
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The travel time needed by the given vehicle to pass the edge at the given time
Definition at line 174 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ROEdge::getMinimumTravelTime(), Distribution_Parameterized::getParameter(), ValueTimeLine< T >::getSplitTime(), RORoutable::getType(), ValueTimeLine< T >::getValue(), MAX2(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::myHaveTTWarned, Named::myID, ROEdge::myInterpolate, ROEdge::myLength, ROEdge::mySpeed, ROEdge::myTravelTimes, ROEdge::myUsingTTTimeLine, SUMOVTypeParameter::speedFactor, split(), toString(), and WRITE_WARNING.
Referenced by ROJTRRouter::compute(), ROEdge::getEmissionEffort(), ROMAAssignments::getPenalizedTT(), ROEdge::getPredecessors(), ROMAAssignments::getTravelTime(), ROEdge::getTravelTimeStatic(), ROMAAssignments::incremental(), and writeInterval().
getTravelTimeStatic()
static double ROEdge::getTravelTimeStatic (const ROEdge *const edge, const ROVehicle *const veh, double time) inline static inherited
Returns the travel time for the given edge.
Parameters
[in] edge The edge for which the travel time shall be retrieved
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The traveltime needed by the given vehicle to pass the edge at the given time
Definition at line 404 of file ROEdge.h.
References ROEdge::getTravelTime().
Referenced by computeRoutes().
getVClassMaxSpeed()
double ROEdge::getVClassMaxSpeed (SUMOVehicleClass vclass) const inline inherited
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
Parameters
[in] The vehicle to return the adapted speed limit for
Returns
This lane's resulting max. speed
Definition at line 237 of file ROEdge.h.
References ROEdge::myRestrictions, and ROEdge::mySpeed.
Referenced by RODFNet::buildEdgeFlowMap().
hasLoadedTravelTime()
bool ROEdge::hasLoadedTravelTime (double time) const inherited
Returns whether a travel time for this edge was loaded.
Parameters
[in] time The time for which the travel time shall be returned [s]
Returns
whether a value was loaded
Definition at line 168 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ROEdge::myTravelTimes, and ROEdge::myUsingTTTimeLine.
Referenced by ROEdge::getPredecessors(), and ROMAAssignments::incremental().
isConnectedTo()
bool ROEdge::isConnectedTo (const ROEdge *const e, const ROVehicle *const vehicle) const inherited
returns the information whether this edge is directly connected to the given
Parameters
[in] e The edge which may be connected
[in] vehicle The vehicle for which the connectivity is checked
Returns
Whether the given edge is a direct successor to this one
Definition at line 366 of file ROEdge.cpp.
References ROEdge::getSuccessors(), RORoutable::getVClass(), and SVC_IGNORING.
Referenced by ROEdge::getNumLanes().
isCrossing()
bool ROEdge::isCrossing () const inline inherited
return whether this edge is a pedestrian crossing
Definition at line 154 of file ROEdge.h.
References EDGEFUNC_CROSSING, and ROEdge::myFunction.
isInternal()
bool ROEdge::isInternal () const inline inherited
return whether this edge is an internal edge
Definition at line 149 of file ROEdge.h.
References EDGEFUNC_INTERNAL, and ROEdge::myFunction.
Referenced by RONet::addEdge(), RORouteHandler::addStop(), ROEdge::addSuccessor(), RODFNet::buildApproachList(), ROEdge::getNormalAfter(), and ROEdge::getNormalBefore().
isSink()
bool ROEdge::isSink () const inline inherited
Returns whether the edge acts as a sink.
Returns
whether the edge is a sink
Definition at line 196 of file ROEdge.h.
References ROEdge::myAmSink.
Referenced by ROJTRRouter::compute(), and ROEdge::setSink().
isTazConnector()
bool ROEdge::isTazConnector () const inline inherited
Definition at line 163 of file ROEdge.h.
References ROEdge::buildTimeLines(), EDGEFUNC_CONNECTOR, and ROEdge::myFunction.
Referenced by ROEdge::addSuccessor(), ROMAAssignments::capacityConstraintFunction(), ROMAAssignments::getCapacity(), ROEdge::getDistanceTo(), ROEdge::getMinimumTravelTime(), and ROEdge::getSuccessors().
isWalkingArea()
bool ROEdge::isWalkingArea () const inline inherited
return whether this edge is walking area
Definition at line 159 of file ROEdge.h.
References EDGEFUNC_WALKINGAREA, and ROEdge::myFunction.
operator=()
RODFEdge& RODFEdge::operator= (const RODFEdge & src) private
Invalidated assignment operator.
prohibits()
bool ROEdge::prohibits (const ROVehicle *const vehicle) const inline inherited
Returns whether this edge prohibits the given vehicle to pass it.
Parameters
[in] vehicle The vehicle for which the information has to be returned
Returns
Whether the vehicle must not enter this edge
Definition at line 269 of file ROEdge.h.
References RORoutable::getVClass(), and ROEdge::myCombinedPermissions.
Referenced by ROVehicle::addStop(), ROJTREdge::chooseNext(), and ROJTRRouter::compute().
setFlows()
void RODFEdge::setFlows (const std::vector< FlowDef > & flows)
Definition at line 49 of file RODFEdge.cpp.
References myFlows.
setFunction()
void ROEdge::setFunction (SumoXMLEdgeFunc func) inline inherited
Sets the function of the edge.
Parameters
[in] func The new function for the edge
Definition at line 119 of file ROEdge.h.
References ROEdge::myFunction.
Referenced by RONet::addDistrict(), and RONetHandler::parseEdge().
setGlobalOptions()
static void ROEdge::setGlobalOptions (const bool interpolate) inline static inherited
Definition at line 454 of file ROEdge.h.
References ROEdge::myInterpolate.
Referenced by initNet().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setRestrictions()
void ROEdge::setRestrictions (const std::map< SUMOVehicleClass, double > * restrictions) inline inherited
Sets the vehicle class specific speed limits of the edge.
Parameters
[in] restrictions The restrictions for the edge
Definition at line 143 of file ROEdge.h.
References ROEdge::myRestrictions.
Referenced by RONetHandler::parseEdge().
setSink()
void ROEdge::setSink (const bool isSink = true) inline inherited
Sets whether the edge is a sink.
Parameters
[in] func The new sink functionality for the edge
Definition at line 135 of file ROEdge.h.
References ROEdge::isSink(), and ROEdge::myAmSink.
Referenced by loadJTRDefinitions(), and ROJTRTurnDefLoader::myStartElement().
setSource()
void ROEdge::setSource (const bool isSource = true) inline inherited
Sets whether the edge is a source.
Parameters
[in] func The new source functionality for the edge
Definition at line 127 of file ROEdge.h.
References ROEdge::myAmSource.
Referenced by ROJTRTurnDefLoader::myStartElement().
Field Documentation
myAmSink
bool ROEdge::myAmSink protected inherited
whether the edge is a source or a sink
Definition at line 508 of file ROEdge.h.
Referenced by ROEdge::getNumSuccessors(), ROEdge::isSink(), and ROEdge::setSink().
myAmSource
bool ROEdge::myAmSource protected inherited
Definition at line 508 of file ROEdge.h.
Referenced by ROEdge::getNumPredecessors(), and ROEdge::setSource().
myApproachingEdges
ROEdgeVector ROEdge::myApproachingEdges protected inherited
List of edges that approached this edge.
Definition at line 531 of file ROEdge.h.
Referenced by ROEdge::addSuccessor(), ROEdge::getNormalBefore(), ROEdge::getNumPredecessors(), and ROEdge::getPredecessors().
myClassesSuccessorMap
std::map<SUMOVehicleClass, ROEdgeVector> ROEdge::myClassesSuccessorMap mutable protected inherited
The successors available for a given vClass.
Definition at line 552 of file ROEdge.h.
Referenced by ROEdge::getSuccessors().
myCombinedPermissions
SVCPermissions ROEdge::myCombinedPermissions protected inherited
The list of allowed vehicle classes combined across lanes.
Definition at line 543 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::getPermissions(), ROEdge::prohibits(), and ROEdge::ROEdge().
myEdges
ROEdgeVector ROEdge::myEdges static protected inherited
Definition at line 548 of file ROEdge.h.
Referenced by ROEdge::dictSize(), ROEdge::getAllEdges(), and ROEdge::ROEdge().
myEfforts
ValueTimeLine<double> ROEdge::myEfforts mutable protected inherited
Container storing passing time varying over time for the edge.
Definition at line 515 of file ROEdge.h.
Referenced by ROEdge::addEffort(), ROEdge::buildTimeLines(), and ROEdge::getStoredEffort().
myFlows
std::vector<FlowDef> RODFEdge::myFlows private
Definition at line 75 of file RODFEdge.h.
Referenced by getFlows(), and setFlows().
myFollowingEdges
ROEdgeVector ROEdge::myFollowingEdges protected inherited
List of edges that may be approached from this edge.
Definition at line 528 of file ROEdge.h.
Referenced by ROEdge::addSuccessor(), ROEdge::allFollowersProhibit(), ROJTREdge::chooseNext(), ROEdge::getNormalAfter(), ROEdge::getNumSuccessors(), ROEdge::getSuccessors(), and ROJTREdge::setTurnDefaults().
myFromJunction
RONode* ROEdge::myFromJunction protected inherited
the junctions for this edge
Definition at line 492 of file ROEdge.h.
Referenced by ROEdge::getFromJunction(), and ROEdge::getLengthGeometryFactor().
myFunction
SumoXMLEdgeFunc ROEdge::myFunction protected inherited
The function of the edge.
Definition at line 534 of file ROEdge.h.
Referenced by ROEdge::getFunction(), ROEdge::isCrossing(), ROEdge::isInternal(), ROEdge::isTazConnector(), ROEdge::isWalkingArea(), and ROEdge::setFunction().
myHaveEWarned
bool ROEdge::myHaveEWarned = false static protected inherited
Information whether the edge has reported missing weights.
Definition at line 523 of file ROEdge.h.
Referenced by ROEdge::getStoredEffort().
myHaveTTWarned
bool ROEdge::myHaveTTWarned = false static protected inherited
Information whether the edge has reported missing weights.
Definition at line 525 of file ROEdge.h.
Referenced by ROEdge::getTravelTime().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myIndex
const int ROEdge::myIndex protected inherited
The index (numeric id) of the edge.
Definition at line 496 of file ROEdge.h.
Referenced by ROEdge::getNumericalID().
myInterpolate
bool ROEdge::myInterpolate = false static protected inherited
Information whether to interpolate at interval boundaries.
Definition at line 520 of file ROEdge.h.
Referenced by ROEdge::getStoredEffort(), ROEdge::getTravelTime(), and ROEdge::setGlobalOptions().
myLanes
std::vector<ROLane*> ROEdge::myLanes protected inherited
This edge's lanes.
Definition at line 540 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::getLanes(), ROEdge::getNumLanes(), ROEdge::getSuccessors(), and ROEdge::~ROEdge().
myLength
double ROEdge::myLength protected inherited
The length of the edge.
Definition at line 505 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::buildTimeLines(), ROEdge::getEffort(), ROEdge::getLength(), ROEdge::getLengthGeometryFactor(), ROEdge::getMinimumTravelTime(), and ROEdge::getTravelTime().
myPriority
const int ROEdge::myPriority protected inherited
The edge priority (road class)
Definition at line 499 of file ROEdge.h.
Referenced by ROEdge::getPriority().
myRestrictions
const std::map<SUMOVehicleClass, double>* ROEdge::myRestrictions protected inherited
The vClass speed restrictions for this edge.
Definition at line 537 of file ROEdge.h.
Referenced by ROEdge::getVClassMaxSpeed(), and ROEdge::setRestrictions().
mySpeed
double ROEdge::mySpeed protected inherited
The maximum speed allowed on this edge.
Definition at line 502 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::buildTimeLines(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getSpeedLimit(), ROEdge::getTravelTime(), and ROEdge::getVClassMaxSpeed().
myTazBoundary
Boundary ROEdge::myTazBoundary protected inherited
The bounding rectangle of incoming or outgoing edges for taz connectors.
Definition at line 546 of file ROEdge.h.
Referenced by ROEdge::addSuccessor(), and ROEdge::getDistanceTo().
myToJunction
RONode* ROEdge::myToJunction protected inherited
Definition at line 493 of file ROEdge.h.
Referenced by ROEdge::getLengthGeometryFactor(), and ROEdge::getToJunction().
myTravelTimes
ValueTimeLine<double> ROEdge::myTravelTimes mutable protected inherited
Container storing passing time varying over time for the edge.
Definition at line 510 of file ROEdge.h.
Referenced by ROEdge::addTravelTime(), ROEdge::buildTimeLines(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), and ROEdge::hasLoadedTravelTime().
myUsingETimeLine
bool ROEdge::myUsingETimeLine protected inherited
Information whether the time line shall be used instead of the length value.
Definition at line 517 of file ROEdge.h.
Referenced by ROEdge::addEffort(), ROEdge::buildTimeLines(), and ROEdge::getStoredEffort().
myUsingTTTimeLine
bool ROEdge::myUsingTTTimeLine protected inherited
Information whether the time line shall be used instead of the length value.
Definition at line 512 of file ROEdge.h.
Referenced by ROEdge::addTravelTime(), ROEdge::buildTimeLines(), ROEdge::getTravelTime(), and ROEdge::hasLoadedTravelTime().
The documentation for this class was generated from the following files:
RODFEdge.h
RODFEdge.cpp