SUMO - Simulation of Urban MObility: GUIMainWindow Class Reference
GUIMainWindow Class Reference abstract
#include <GUIMainWindow.h>
Public Member Functions
void addChild (FXMDIChild *child, bool updateOnSimStep=true)
Adds a further child window to the list.
void addChild (FXMainWindow *child, bool updateOnSimStep=true)
GUISUMOAbstractView * getActiveView () const
get the active view or 0
FXFont * getBoldFont ()
virtual FXGLCanvas * getBuildGLCanvas () const =0
FXLabel & getCartesianLabel ()
virtual SUMOTime getCurrentSimTime () const =0
virtual double getDelay () const
Returns the delay (should be overwritten by subclasses if applicable)
FXLabel & getGeoLabel ()
FXGLVisual * getGLVisual () const
virtual double getTrackerInterval () const =0
FXMDIChild * getViewByID (const std::string &id) const
std::vector< std::string > getViewIDs () const
GUIMainWindow (FXApp *a)
bool isGaming () const
return whether the gui is in gaming mode
bool listInternal () const
return whether to list internal structures
bool listParking () const
return whether to list parking vehicles
bool listTeleporting () const
return whether to list teleporting vehicles
void removeChild (FXMDIChild *child)
removes the given child window from the list
void removeChild (FXMainWindow *child)
virtual void sendBlockingEvent (GUIEvent *event)
Sends an event from the application thread to the GUI and waits until it is handled.
virtual void setDelay (double)
Sets the delay of the parent application.
virtual void setStatusBarText (const std::string &)
void updateChildren ()
virtual ~GUIMainWindow ()
Static Public Member Functions
static GUIMainWindow * getInstance ()
Protected Member Functions
GUIMainWindow ()
void setWindowSizeAndPos ()
perform initial window positioning and sizing according to user options / previous call
Protected Attributes
bool myAmGaming
information whether the gui is currently in gaming mode
FXFont * myBoldFont
Font used for popup-menu titles.
FXDockSite * myBottomDock
FXLabel * myCartesianCoordinate
Labels for the current cartesian and geo-coordinate.
FXHorizontalFrame * myCartesianFrame
FXLabel * myGeoCoordinate
FXHorizontalFrame * myGeoFrame
FXGLVisual * myGLVisual
The gl-visual used.
FXDockSite * myLeftDock
bool myListInternal
information whether the locator should list internal structures
bool myListParking
information whether the locator should list parking vehicles
bool myListTeleporting
information whether the locator should list teleporting vehicles
FXMDIClient * myMDIClient
The multi view panel.
FXDockSite * myRightDock
FXStatusBar * myStatusbar
The status bar.
std::vector< FXMDIChild * > mySubWindows
FXDockSite * myTopDock
MFXMutex myTrackerLock
A lock to make the removal and addition of trackers secure.
std::vector< FXMainWindow * > myTrackerWindows
Static Protected Attributes
static GUIMainWindow * myInstance = 0
the singleton window instance
Detailed Description
Definition at line 53 of file GUIMainWindow.h.
Constructor & Destructor Documentation
GUIMainWindow() [1/2]
GUIMainWindow::GUIMainWindow (FXApp * a)
Definition at line 63 of file GUIMainWindow.cpp.
References myBoldFont, myBottomDock, myInstance, myLeftDock, myRightDock, and myTopDock.
~GUIMainWindow()
GUIMainWindow::~GUIMainWindow () virtual
Definition at line 88 of file GUIMainWindow.cpp.
References myBoldFont, myBottomDock, myLeftDock, myRightDock, and myTopDock.
GUIMainWindow() [2/2]
GUIMainWindow::GUIMainWindow () inline protected
Definition at line 168 of file GUIMainWindow.h.
References setWindowSizeAndPos().
Member Function Documentation
addChild() [1/2]
void GUIMainWindow::addChild (FXMDIChild * child, bool updateOnSimStep = true)
Adds a further child window to the list.
Definition at line 99 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by GUIParameterTableWindow::closeBuilding(), and GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow().
addChild() [2/2]
void GUIMainWindow::addChild (FXMainWindow * child, bool updateOnSimStep = true)
Definition at line 114 of file GUIMainWindow.cpp.
References MFXMutex::lock(), myTrackerLock, myTrackerWindows, and MFXMutex::unlock().
getActiveView()
GUISUMOAbstractView * GUIMainWindow::getActiveView () const
get the active view or 0
Definition at line 198 of file GUIMainWindow.cpp.
References GUIGlChildWindow::getView(), and myMDIClient.
Referenced by GUIVehicle::drawOutsideNetwork(), and sendBlockingEvent().
getBoldFont()
FXFont * GUIMainWindow::getBoldFont ()
Definition at line 152 of file GUIMainWindow.cpp.
References myBoldFont.
Referenced by GUIGlObject::buildPopupHeader(), GNEDeleteFrame::createPopUpMenu(), and GNEInspectorFrame::createPopUpMenu().
getBuildGLCanvas()
virtual FXGLCanvas* GUIMainWindow::getBuildGLCanvas () const pure virtual
Implemented in GNEApplicationWindow, and GUIApplicationWindow.
getCartesianLabel()
FXLabel & GUIMainWindow::getCartesianLabel ()
Definition at line 177 of file GUIMainWindow.cpp.
References myCartesianCoordinate.
Referenced by setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
getCurrentSimTime()
virtual SUMOTime GUIMainWindow::getCurrentSimTime () const pure virtual
Implemented in GNEApplicationWindow, and GUIApplicationWindow.
Referenced by GUIParam_PopupMenuInterface::onCmdOpenTracker().
getDelay()
virtual double GUIMainWindow::getDelay () const inline virtual
Returns the delay (should be overwritten by subclasses if applicable)
Returns
parsed delay in milliseconds
Reimplemented in GUIApplicationWindow.
Definition at line 110 of file GUIMainWindow.h.
Referenced by GUISUMOAbstractView::getDelay(), and GUIViewTraffic::saveFrame().
getGeoLabel()
FXLabel & GUIMainWindow::getGeoLabel ()
Definition at line 183 of file GUIMainWindow.cpp.
References myGeoCoordinate.
Referenced by setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
getGLVisual()
FXGLVisual * GUIMainWindow::getGLVisual () const
Definition at line 171 of file GUIMainWindow.cpp.
References myGLVisual.
Referenced by GUISUMOViewParent::init().
getInstance()
GUIMainWindow * GUIMainWindow::getInstance (void) static
Definition at line 189 of file GUIMainWindow.cpp.
References myInstance.
Referenced by GUIVehicle::drawOutsideNetwork(), TraCIServerAPI_GUI::getNamedView(), GUITexturesHelper::getTextureID(), listTeleporting(), TraCIServerAPI_GUI::processGet(), and GUIMessageWindow::setCursorPos().
getTrackerInterval()
virtual double GUIMainWindow::getTrackerInterval () const pure virtual
Implemented in GNEApplicationWindow, and GUIApplicationWindow.
Referenced by GUIParam_PopupMenuInterface::onCmdOpenTracker().
getViewByID()
FXMDIChild * GUIMainWindow::getViewByID (const std::string & id) const
Definition at line 141 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by TraCIServerAPI_GUI::getNamedView(), and GUIMessageWindow::setCursorPos().
getViewIDs()
std::vector< std::string > GUIMainWindow::getViewIDs () const
Definition at line 131 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by TraCIServerAPI_GUI::processGet(), and GUIMessageWindow::setCursorPos().
isGaming()
bool GUIMainWindow::isGaming () const inline
return whether the gui is in gaming mode
Definition at line 86 of file GUIMainWindow.h.
References myAmGaming.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded(), GUISUMOViewParent::init(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnRelease(), and GUIViewTraffic::setColorScheme().
listInternal()
bool GUIMainWindow::listInternal () const inline
return whether to list internal structures
Definition at line 91 of file GUIMainWindow.h.
References myListInternal.
Referenced by GUISUMOViewParent::onCmdLocate().
listParking()
bool GUIMainWindow::listParking () const inline
return whether to list parking vehicles
Definition at line 96 of file GUIMainWindow.h.
References myListParking.
Referenced by GUIApplicationWindow::fillMenuBar(), and GUISUMOViewParent::onCmdLocate().
listTeleporting()
bool GUIMainWindow::listTeleporting () const inline
return whether to list teleporting vehicles
Definition at line 101 of file GUIMainWindow.h.
References getInstance(), and myListTeleporting.
Referenced by GUISUMOViewParent::onCmdLocate().
removeChild() [1/2]
void GUIMainWindow::removeChild (FXMDIChild * child)
removes the given child window from the list
Definition at line 105 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by GNEViewParent::~GNEViewParent(), GUIDialog_Breakpoints::~GUIDialog_Breakpoints(), GUIDialog_GLChosenEditor::~GUIDialog_GLChosenEditor(), GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser(), GUIParameterTableWindow::~GUIParameterTableWindow(), GUIParameterTracker::~GUIParameterTracker(), GUISUMOViewParent::~GUISUMOViewParent(), and GUITLLogicPhasesTrackerWindow::~GUITLLogicPhasesTrackerWindow().
removeChild() [2/2]
void GUIMainWindow::removeChild (FXMainWindow * child)
Definition at line 122 of file GUIMainWindow.cpp.
References MFXMutex::lock(), myTrackerLock, myTrackerWindows, and MFXMutex::unlock().
sendBlockingEvent()
virtual void GUIMainWindow::sendBlockingEvent (GUIEvent * event) inline virtual
Sends an event from the application thread to the GUI and waits until it is handled.
Parameters
event the event to send
Reimplemented in GUIApplicationWindow.
Definition at line 121 of file GUIMainWindow.h.
References getActiveView(), and UNUSED_PARAMETER.
setDelay()
virtual void GUIMainWindow::setDelay (double) inline virtual
Sets the delay of the parent application.
Reimplemented in GUIApplicationWindow.
Definition at line 116 of file GUIMainWindow.h.
Referenced by GUISUMOAbstractView::setDelay().
setStatusBarText()
virtual void GUIMainWindow::setStatusBarText (const std::string &) inline virtual
Reimplemented in GNEApplicationWindow, and GUIApplicationWindow.
Definition at line 80 of file GUIMainWindow.h.
References getCartesianLabel(), and getGeoLabel().
Referenced by GUISUMOAbstractView::getObjectsInBoundary(), and GNEViewNet::setStatusBarText().
setWindowSizeAndPos()
void GUIMainWindow::setWindowSizeAndPos () protected
perform initial window positioning and sizing according to user options / previous call
Definition at line 207 of file GUIMainWindow.cpp.
References TplCheck::_str2int(), TplConvert::_str2int(), OptionsCont::getOptions(), OptionsCont::getStringVector(), OptionsCont::isSet(), MAX2(), MIN2(), and WRITE_ERROR.
Referenced by GUIApplicationWindow::create(), GNEApplicationWindow::create(), GUIMainWindow(), GNEApplicationWindow::handleEvent_NetworkLoaded(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
updateChildren()
void GUIMainWindow::updateChildren ()
Definition at line 158 of file GUIMainWindow.cpp.
References MFXMutex::lock(), MID_SIMSTEP, myMDIClient, myTrackerLock, myTrackerWindows, and MFXMutex::unlock().
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdChangeOption(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption(), GUIDialog_GLChosenEditor::onCmdClear(), GUIDialog_GLChosenEditor::onCmdDeselect(), GUIApplicationWindow::onCmdEditChosen(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdUserDef(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdPreDef(), GUICalibrator::GUIManip_Calibrator::onUpdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdUserDef(), GUICalibrator::GUIManip_Calibrator::onUpdUserDef(), and GUITriggeredRerouter::GUIManip_TriggeredRerouter::onUpdUserDef().
Field Documentation
myAmGaming
bool GUIMainWindow::myAmGaming protected
information whether the gui is currently in gaming mode
Definition at line 153 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), isGaming(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), and GUIApplicationWindow::updateTimeLCD().
myBoldFont
FXFont* GUIMainWindow::myBoldFont protected
Font used for popup-menu titles.
Definition at line 135 of file GUIMainWindow.h.
Referenced by getBoldFont(), GUIMainWindow(), and ~GUIMainWindow().
myBottomDock
FXDockSite * GUIMainWindow::myBottomDock protected
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIMainWindow(), and ~GUIMainWindow().
myCartesianCoordinate
FXLabel* GUIMainWindow::myCartesianCoordinate protected
Labels for the current cartesian and geo-coordinate.
Definition at line 144 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::dependentBuild(), and getCartesianLabel().
myCartesianFrame
FXHorizontalFrame* GUIMainWindow::myCartesianFrame protected
Definition at line 145 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::create(), GNEApplicationWindow::create(), GUIApplicationWindow::dependentBuild(), and GNEApplicationWindow::dependentBuild().
myGeoCoordinate
FXLabel * GUIMainWindow::myGeoCoordinate protected
Definition at line 144 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::dependentBuild(), and getGeoLabel().
myGeoFrame
FXHorizontalFrame * GUIMainWindow::myGeoFrame protected
Definition at line 145 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::create(), GNEApplicationWindow::create(), GUIApplicationWindow::dependentBuild(), and GNEApplicationWindow::dependentBuild().
myGLVisual
FXGLVisual* GUIMainWindow::myGLVisual protected
The gl-visual used.
Definition at line 148 of file GUIMainWindow.h.
Referenced by getGLVisual(), GNEApplicationWindow::~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
myInstance
GUIMainWindow * GUIMainWindow::myInstance = 0 static protected
the singleton window instance
Definition at line 165 of file GUIMainWindow.h.
Referenced by getInstance(), and GUIMainWindow().
myLeftDock
FXDockSite * GUIMainWindow::myLeftDock protected
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIMainWindow(), and ~GUIMainWindow().
myListInternal
bool GUIMainWindow::myListInternal protected
information whether the locator should list internal structures
Definition at line 156 of file GUIMainWindow.h.
Referenced by listInternal(), and GUIApplicationWindow::onCmdListInternal().
myListParking
bool GUIMainWindow::myListParking protected
information whether the locator should list parking vehicles
Definition at line 159 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::fillMenuBar(), listParking(), and GUIApplicationWindow::onCmdListParking().
myListTeleporting
bool GUIMainWindow::myListTeleporting protected
information whether the locator should list teleporting vehicles
Definition at line 162 of file GUIMainWindow.h.
Referenced by listTeleporting(), and GUIApplicationWindow::onCmdListTeleporting().
myMDIClient
FXMDIClient* GUIMainWindow::myMDIClient protected
The multi view panel.
Definition at line 138 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::fillMenuBar(), getActiveView(), GUIApplicationWindow::getBuildGLCanvas(), GNEApplicationWindow::getBuildGLCanvas(), GUIApplicationWindow::onCmdEditChosen(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), GNEApplicationWindow::onCmdLocate(), GUIApplicationWindow::onCmdLocate(), GUIApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdShowStats(), GNEApplicationWindow::onKeyPress(), GUIApplicationWindow::onKeyPress(), GNEApplicationWindow::onKeyRelease(), GUIApplicationWindow::onKeyRelease(), GUIApplicationWindow::openNewView(), GNEApplicationWindow::openNewView(), and updateChildren().
myRightDock
FXDockSite * GUIMainWindow::myRightDock protected
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIMainWindow(), and ~GUIMainWindow().
myStatusbar
FXStatusBar* GUIMainWindow::myStatusbar protected
The status bar.
Definition at line 141 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::fillMenuBar(), GNEApplicationWindow::fillMenuBar(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), GUIApplicationWindow::onCmdOpenRecent(), GNEApplicationWindow::onCmdOpenRecent(), GUIApplicationWindow::onCmdStart(), GUIApplicationWindow::onCmdStep(), GUIApplicationWindow::openNewView(), GUIApplicationWindow::setStatusBarText(), and GNEApplicationWindow::setStatusBarText().
mySubWindows
std::vector<FXMDIChild*> GUIMainWindow::mySubWindows protected
Definition at line 129 of file GUIMainWindow.h.
Referenced by addChild(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::getView(), getViewByID(), getViewIDs(), GUIApplicationWindow::onCmdNetedit(), and removeChild().
myTopDock
FXDockSite* GUIMainWindow::myTopDock protected
Definition at line 150 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::buildToolBars(), GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::dependentBuild(), GUIMainWindow(), and ~GUIMainWindow().
myTrackerLock
MFXMutex GUIMainWindow::myTrackerLock protected
A lock to make the removal and addition of trackers secure.
Definition at line 132 of file GUIMainWindow.h.
Referenced by addChild(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), removeChild(), and updateChildren().
myTrackerWindows
std::vector<FXMainWindow*> GUIMainWindow::myTrackerWindows protected
Definition at line 130 of file GUIMainWindow.h.
Referenced by addChild(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), removeChild(), and updateChildren().
The documentation for this class was generated from the following files:
GUIMainWindow.h
GUIMainWindow.cpp