SUMO - Simulation of Urban MObility: Command_SaveTLCoupledDet Class Reference
Command_SaveTLCoupledDet Class Reference
Writes e2 state on each tls switch.
#include <Command_SaveTLCoupledDet.h>
Public Member Functions
Command_SaveTLCoupledDet (MSTLLogicControl::TLSLogicVariants &tlls, MSDetectorFileOutput *dtf, SUMOTime begin, OutputDevice &device)
Constructor.
virtual void execute ()
Executes the command.
virtual ~Command_SaveTLCoupledDet ()
Destructor.
Protected Attributes
MSDetectorFileOutput * myDetector
The detector to use.
OutputDevice & myDevice
The file to write the output to.
const MSTLLogicControl::TLSLogicVariants & myLogics
The logic to use.
SUMOTime myStartTime
The last time the values were written.
Private Member Functions
Command_SaveTLCoupledDet (const Command_SaveTLCoupledDet &)
Invalidated copy constructor.
Command_SaveTLCoupledDet & operator= (const Command_SaveTLCoupledDet &)
Invalidated assignment operator.
Detailed Description
Writes e2 state on each tls switch.
Todo:
Problem: The detector may not save the last state (on simulation end)
Definition at line 55 of file Command_SaveTLCoupledDet.h.
Constructor & Destructor Documentation
Command_SaveTLCoupledDet() [1/2]
Command_SaveTLCoupledDet::Command_SaveTLCoupledDet (MSTLLogicControl::TLSLogicVariants & tlls, MSDetectorFileOutput * dtf, SUMOTime begin, OutputDevice & device)
Constructor.
Parameters
[in] tlls The logic to observe
[in] dtf The detector used to generate the values
[in] begin The begin simulation time
[in] device The output device to write the detector values into
Definition at line 44 of file Command_SaveTLCoupledDet.cpp.
References MSTLLogicControl::TLSLogicVariants::addSwitchCommand(), and MSDetectorFileOutput::writeXMLDetectorProlog().
~Command_SaveTLCoupledDet()
Command_SaveTLCoupledDet::~Command_SaveTLCoupledDet () virtual
Destructor.
Definition at line 53 of file Command_SaveTLCoupledDet.cpp.
Command_SaveTLCoupledDet() [2/2]
Command_SaveTLCoupledDet::Command_SaveTLCoupledDet (const Command_SaveTLCoupledDet &) private
Invalidated copy constructor.
Member Function Documentation
execute()
void Command_SaveTLCoupledDet::execute () virtual
Executes the command.
Called when an active tls program switches, this method calls "writeXMLOutput" of its detector (e2; the values are resetted there).
See also
MSDetectorFileOutput::writeXMLOutput
MSE2Collector::writeXMLOutput
Implements MSTLLogicControl::OnSwitchAction.
Reimplemented in Command_SaveTLCoupledLaneDet.
Definition at line 58 of file Command_SaveTLCoupledDet.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), myDetector, myDevice, myStartTime, and MSDetectorFileOutput::writeXMLOutput().
operator=()
Command_SaveTLCoupledDet& Command_SaveTLCoupledDet::operator= (const Command_SaveTLCoupledDet &) private
Invalidated assignment operator.
Field Documentation
myDetector
MSDetectorFileOutput* Command_SaveTLCoupledDet::myDetector protected
The detector to use.
Definition at line 91 of file Command_SaveTLCoupledDet.h.
Referenced by Command_SaveTLCoupledLaneDet::execute(), and execute().
myDevice
OutputDevice& Command_SaveTLCoupledDet::myDevice protected
The file to write the output to.
Definition at line 85 of file Command_SaveTLCoupledDet.h.
Referenced by Command_SaveTLCoupledLaneDet::execute(), and execute().
myLogics
const MSTLLogicControl::TLSLogicVariants& Command_SaveTLCoupledDet::myLogics protected
The logic to use.
Definition at line 88 of file Command_SaveTLCoupledDet.h.
myStartTime
SUMOTime Command_SaveTLCoupledDet::myStartTime protected
The last time the values were written.
Definition at line 94 of file Command_SaveTLCoupledDet.h.
Referenced by Command_SaveTLCoupledLaneDet::execute(), and execute().
The documentation for this class was generated from the following files:
Command_SaveTLCoupledDet.h
Command_SaveTLCoupledDet.cpp