SUMO - Simulation of Urban MObility: GUIParameterTracker Class Reference
GUIParameterTracker Class Reference
A window which displays the time line of one (or more) value(s)
#include <GUIParameterTracker.h>
Data Structures
class GUIParameterTrackerPanel
Public Types
enum { MID_AGGREGATIONINTERVAL = FXMainWindow::ID_LAST, MID_SAVE, ID_LAST }
callback-enumerations
Public Member Functions
void addTracked (GUIGlObject &o, ValueSource< double > *src, TrackerValueDesc *newTracked)
Adds a further time line to display.
void create ()
Creates the window.
GUIParameterTracker (GUIMainWindow &app, const std::string &name)
Constructor (the tracker is empty)
~GUIParameterTracker ()
Destructor.
FOX-callbacks
long onConfigure (FXObject *, FXSelector, void *)
Called on window resizing.
long onPaint (FXObject *, FXSelector, void *)
Called if the window shall be repainted.
long onSimStep (FXObject *, FXSelector, void *)
Called on a simulation step.
long onCmdChangeAggregation (FXObject *, FXSelector, void *)
Called when the aggregation interval (combo) has been changed.
long onCmdSave (FXObject *, FXSelector, void *)
Called when the data shall be saved.
Protected Member Functions
GUIParameterTracker ()
Fox needs this.
Protected Attributes
FXdouble myAggregationDelay
The simulation delay.
FXComboBox * myAggregationInterval
A combo box to select an aggregation interval.
GUIMainWindow * myApplication
The main application.
GUIParameterTrackerPanel * myPanel
The panel to display the values in.
FXToolBar * myToolBar
The tracker tool bar.
FXToolBarShell * myToolBarDrag
for some menu detaching fun
std::vector< TrackerValueDesc * > myTracked
The list of tracked values.
std::vector< GLObjectValuePassConnector< double > * > myValuePassers
The value sources.
Private Member Functions
void buildToolBar ()
Builds the tool bar.
Friends
class GUIParameterTrackerPanel
the panel may change some things
Detailed Description
A window which displays the time line of one (or more) value(s)
Definition at line 55 of file GUIParameterTracker.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
callback-enumerations
Enumerator
MID_AGGREGATIONINTERVAL
Change aggregation interval.
MID_SAVE
Save the current values.
ID_LAST
end-of-enum
Definition at line 59 of file GUIParameterTracker.h.
Constructor & Destructor Documentation
GUIParameterTracker() [1/2]
GUIParameterTracker::GUIParameterTracker (GUIMainWindow & app, const std::string & name)
Constructor (the tracker is empty)
Parameters
[in] app The main application window
[in] name The title of the tracker
Definition at line 70 of file GUIParameterTracker.cpp.
References GUIIconSubSys::getIcon(), and ICON_APP_TRACKER.
~GUIParameterTracker()
GUIParameterTracker::~GUIParameterTracker ()
Destructor.
Definition at line 83 of file GUIParameterTracker.cpp.
References myApplication, myToolBar, myToolBarDrag, myTracked, myValuePassers, and GUIMainWindow::removeChild().
GUIParameterTracker() [2/2]
GUIParameterTracker::GUIParameterTracker () inline protected
Fox needs this.
Definition at line 215 of file GUIParameterTracker.h.
Member Function Documentation
addTracked()
void GUIParameterTracker::addTracked (GUIGlObject & o, ValueSource< double > * src, TrackerValueDesc * newTracked)
Adds a further time line to display.
Parameters
[in] o The object to get values from
[in] src The value source of the object
[in] newTracked The description of the tracked value
Definition at line 127 of file GUIParameterTracker.cpp.
References myTracked, and myValuePassers.
Referenced by GUIParam_PopupMenuInterface::onCmdOpenTracker().
buildToolBar()
void GUIParameterTracker::buildToolBar () private
Builds the tool bar.
Definition at line 105 of file GUIParameterTracker.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignComboBoxStatic, GUIDesignToolBarGrip, GUIDesignToolBarShell3, ICON_SAVE, MID_AGGREGATIONINTERVAL, MID_SAVE, myAggregationInterval, myToolBar, and myToolBarDrag.
create()
void GUIParameterTracker::create ()
Creates the window.
Definition at line 98 of file GUIParameterTracker.cpp.
References myToolBarDrag.
Referenced by GUIParam_PopupMenuInterface::onCmdOpenTracker().
onCmdChangeAggregation()
long GUIParameterTracker::onCmdChangeAggregation (FXObject * , FXSelector , void *)
Called when the aggregation interval (combo) has been changed.
Definition at line 157 of file GUIParameterTracker.cpp.
References myAggregationInterval, myTracked, and TIME2STEPS.
onCmdSave()
long GUIParameterTracker::onCmdSave (FXObject * , FXSelector , void *)
Called when the data shall be saved.
Definition at line 191 of file GUIParameterTracker.cpp.
References OutputDevice::close(), FXDEFMAP(), gCurrentFolder, TrackerValueDesc::getAggregatedValues(), OutputDevice::getDevice(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), TrackerValueDesc::getName(), ICON_EMPTY, myTracked, GUIParameterTracker::GUIParameterTrackerPanel::onConfigure(), GUIParameterTracker::GUIParameterTrackerPanel::onPaint(), and TrackerValueDesc::unlockValues().
onConfigure()
long GUIParameterTracker::onConfigure (FXObject * sender, FXSelector sel, void * data)
Called on window resizing.
Definition at line 136 of file GUIParameterTracker.cpp.
References myPanel, and GUIParameterTracker::GUIParameterTrackerPanel::onConfigure().
onPaint()
long GUIParameterTracker::onPaint (FXObject * sender, FXSelector sel, void * data)
Called if the window shall be repainted.
Definition at line 143 of file GUIParameterTracker.cpp.
References myPanel, and GUIParameterTracker::GUIParameterTrackerPanel::onPaint().
onSimStep()
long GUIParameterTracker::onSimStep (FXObject * , FXSelector , void *)
Called on a simulation step.
Definition at line 150 of file GUIParameterTracker.cpp.
Friends And Related Function Documentation
GUIParameterTrackerPanel
friend class GUIParameterTrackerPanel friend
the panel may change some things
Definition at line 181 of file GUIParameterTracker.h.
Field Documentation
myAggregationDelay
FXdouble GUIParameterTracker::myAggregationDelay protected
The simulation delay.
Definition at line 208 of file GUIParameterTracker.h.
myAggregationInterval
FXComboBox* GUIParameterTracker::myAggregationInterval protected
A combo box to select an aggregation interval.
Definition at line 205 of file GUIParameterTracker.h.
Referenced by buildToolBar(), and onCmdChangeAggregation().
myApplication
GUIMainWindow* GUIParameterTracker::myApplication protected
The main application.
Definition at line 190 of file GUIParameterTracker.h.
Referenced by ~GUIParameterTracker().
myPanel
GUIParameterTrackerPanel* GUIParameterTracker::myPanel protected
The panel to display the values in.
Definition at line 196 of file GUIParameterTracker.h.
Referenced by onConfigure(), and onPaint().
myToolBar
FXToolBar* GUIParameterTracker::myToolBar protected
The tracker tool bar.
Definition at line 211 of file GUIParameterTracker.h.
Referenced by buildToolBar(), and ~GUIParameterTracker().
myToolBarDrag
FXToolBarShell* GUIParameterTracker::myToolBarDrag protected
for some menu detaching fun
Definition at line 202 of file GUIParameterTracker.h.
Referenced by buildToolBar(), create(), and ~GUIParameterTracker().
myTracked
std::vector<TrackerValueDesc*> GUIParameterTracker::myTracked protected
The list of tracked values.
Definition at line 193 of file GUIParameterTracker.h.
Referenced by addTracked(), onCmdChangeAggregation(), onCmdSave(), and ~GUIParameterTracker().
myValuePassers
std::vector<GLObjectValuePassConnector<double>*> GUIParameterTracker::myValuePassers protected
The value sources.
Definition at line 199 of file GUIParameterTracker.h.
Referenced by addTracked(), and ~GUIParameterTracker().
The documentation for this class was generated from the following files:
GUIParameterTracker.h
GUIParameterTracker.cpp