SUMO - Simulation of Urban MObility: NIVissimNodeDef_Edges Class Reference
NIVissimNodeDef_Edges Class Reference
#include <NIVissimNodeDef_Edges.h>
Data Structures
class id_matches
class lying_within_match
Public Member Functions
int buildNodeCluster ()
virtual double getEdgePosition (int edgeid) const
NIVissimNodeDef_Edges (int id, const std::string &name, const NIVissimNodeParticipatingEdgeVector &edges)
virtual ~NIVissimNodeDef_Edges ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int id, const std::string &name, const NIVissimNodeParticipatingEdgeVector &edges)
static bool dictionary (int id, NIVissimNodeDef *o)
static NIVissimNodeDef * dictionary (int id)
static int dictSize ()
static int getMaxID ()
Protected Attributes
NIVissimNodeParticipatingEdgeVector myEdges
int myID
std::string myName
Detailed Description
Definition at line 39 of file NIVissimNodeDef_Edges.h.
Constructor & Destructor Documentation
NIVissimNodeDef_Edges()
NIVissimNodeDef_Edges::NIVissimNodeDef_Edges (int id, const std::string & name, const NIVissimNodeParticipatingEdgeVector & edges)
Definition at line 49 of file NIVissimNodeDef_Edges.cpp.
Referenced by dictionary().
~NIVissimNodeDef_Edges()
NIVissimNodeDef_Edges::~NIVissimNodeDef_Edges () virtual
Definition at line 54 of file NIVissimNodeDef_Edges.cpp.
References myEdges.
Member Function Documentation
buildNodeCluster()
int NIVissimNodeDef::buildNodeCluster () inherited
clearDict()
void NIVissimNodeDef::clearDict () static inherited
Definition at line 132 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/3]
bool NIVissimNodeDef_Edges::dictionary (int id, const std::string & name, const NIVissimNodeParticipatingEdgeVector & edges) static
Definition at line 63 of file NIVissimNodeDef_Edges.cpp.
References NIVissimNodeDef::dictionary(), and NIVissimNodeDef_Edges().
Referenced by NIVissimSingleTypeParser_Knotendefinition::parse().
dictionary() [2/3]
bool NIVissimNodeDef::dictionary (int id, NIVissimNodeDef * o) static inherited
Definition at line 58 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict, and NIVissimNodeDef::myMaxID.
Referenced by dictionary(), NIVissimNodeDef_Poly::dictionary(), and NIVissimConnectionCluster::getPositionForEdge().
dictionary() [3/3]
NIVissimNodeDef * NIVissimNodeDef::dictionary (int id) static inherited
Definition at line 73 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
dictSize()
int NIVissimNodeDef::dictSize () static inherited
Definition at line 125 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myDict.
getEdgePosition()
double NIVissimNodeDef_Edges::getEdgePosition (int edgeid) const virtual
Implements NIVissimNodeDef.
Definition at line 109 of file NIVissimNodeDef_Edges.cpp.
References NIVissimNodeParticipatingEdge::getFromPos(), NIVissimNodeParticipatingEdge::getID(), NIVissimNodeParticipatingEdge::getToPos(), and myEdges.
getMaxID()
int NIVissimNodeDef::getMaxID () static inherited
Definition at line 141 of file NIVissimNodeDef.cpp.
References NIVissimNodeDef::myMaxID.
Referenced by NIImporter_Vissim::postLoadBuild().
Field Documentation
myEdges
NIVissimNodeParticipatingEdgeVector NIVissimNodeDef_Edges::myEdges protected
Definition at line 76 of file NIVissimNodeDef_Edges.h.
Referenced by getEdgePosition(), and ~NIVissimNodeDef_Edges().
myID
int NIVissimNodeDef::myID protected inherited
Definition at line 60 of file NIVissimNodeDef.h.
myName
std::string NIVissimNodeDef::myName protected inherited
Definition at line 61 of file NIVissimNodeDef.h.
The documentation for this class was generated from the following files:
NIVissimNodeDef_Edges.h
NIVissimNodeDef_Edges.cpp