SUMO - Simulation of Urban MObility: GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel Class Reference
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel Class Reference
The canvas for the visualisation of phases.
#include <GUITLLogicPhasesTrackerWindow.h>
Public Member Functions
GUITLLogicPhasesTrackerPanel (FXComposite *c, GUIMainWindow &app, GUITLLogicPhasesTrackerWindow &parent)
Constructor.
~GUITLLogicPhasesTrackerPanel ()
Destructor.
Friends
class GUITLLogicPhasesTrackerWindow
needed to update
FOX-callbacks
{
GUITLLogicPhasesTrackerWindow * myParent
}
long onConfigure (FXObject *, FXSelector, void *)
called on size change
long onPaint (FXObject *, FXSelector, void *)
called if the widget shall be repainted
GUITLLogicPhasesTrackerPanel ()
protected constructor for FOX
Detailed Description
The canvas for the visualisation of phases.
The drawing itself id done by the parent.
Definition at line 148 of file GUITLLogicPhasesTrackerWindow.h.
Constructor & Destructor Documentation
GUITLLogicPhasesTrackerPanel() [1/2]
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::GUITLLogicPhasesTrackerPanel (FXComposite * c, GUIMainWindow & app, GUITLLogicPhasesTrackerWindow & parent)
Constructor.
Parameters
[in] c The container for this panel
[in] app The main application window
[in] parent This panel's logial parent
Definition at line 70 of file GUITLLogicPhasesTrackerWindow.cpp.
~GUITLLogicPhasesTrackerPanel()
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::~GUITLLogicPhasesTrackerPanel ()
Destructor.
Definition at line 77 of file GUITLLogicPhasesTrackerWindow.cpp.
GUITLLogicPhasesTrackerPanel() [2/2]
GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::GUITLLogicPhasesTrackerPanel () inline protected
protected constructor for FOX
Definition at line 183 of file GUITLLogicPhasesTrackerWindow.h.
References GUITLLogicPhasesTrackerWindow::drawValues().
Referenced by GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow().
Member Function Documentation
onConfigure()
long GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::onConfigure (FXObject * , FXSelector , void *)
called on size change
Definition at line 81 of file GUITLLogicPhasesTrackerWindow.cpp.
Referenced by GUITLLogicPhasesTrackerWindow::onConfigure().
onPaint()
long GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::onPaint (FXObject * , FXSelector , void *)
called if the widget shall be repainted
Definition at line 104 of file GUITLLogicPhasesTrackerWindow.cpp.
References GUITLLogicPhasesTrackerWindow::drawValues(), FXDEFMAP(), MID_SIMSTEP, myParent, GUITLLogicPhasesTrackerWindow::onConfigure(), GUITLLogicPhasesTrackerWindow::onPaint(), and GUITLLogicPhasesTrackerWindow::onSimStep().
Referenced by GUITLLogicPhasesTrackerWindow::onPaint().
Friends And Related Function Documentation
GUITLLogicPhasesTrackerWindow
friend class GUITLLogicPhasesTrackerWindow friend
needed to update
Definition at line 163 of file GUITLLogicPhasesTrackerWindow.h.
Field Documentation
myParent
GUITLLogicPhasesTrackerWindow* GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerPanel::myParent private
}
The parent window
Definition at line 179 of file GUITLLogicPhasesTrackerWindow.h.
Referenced by onPaint().
The documentation for this class was generated from the following files:
GUITLLogicPhasesTrackerWindow.h
GUITLLogicPhasesTrackerWindow.cpp