SUMO - Simulation of Urban MObility: TraCIServerAPI_Edge Class Reference
TraCIServerAPI_Edge Class Reference
APIs for getting/setting edge values via TraCI.
#include <TraCIServerAPI_Edge.h>
Static Public Member Functions
static bool getShape (const std::string &id, PositionVector &shape)
Returns the named edge's shape.
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xaa: Get Edge Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xca: Change Edge State)
Private Member Functions
TraCIServerAPI_Edge & operator= (const TraCIServerAPI_Edge &s)
invalidated assignment operator
TraCIServerAPI_Edge (const TraCIServerAPI_Edge &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting edge values via TraCI.
Definition at line 45 of file TraCIServerAPI_Edge.h.
Constructor & Destructor Documentation
TraCIServerAPI_Edge()
TraCIServerAPI_Edge::TraCIServerAPI_Edge (const TraCIServerAPI_Edge & s) private
invalidated copy constructor
Member Function Documentation
getShape()
bool TraCIServerAPI_Edge::getShape (const std::string & id, PositionVector & shape) static
Returns the named edge's shape.
Parameters
[in] id The id of the searched edge
[out] shape The shape, if the edge is known
Returns
Whether the edge is known
Definition at line 396 of file TraCIServerAPI_Edge.cpp.
References libsumo::Edge::getShape(), and WRITE_WARNING.
Referenced by TraCIServer::findObjectShape().
operator=()
TraCIServerAPI_Edge& TraCIServerAPI_Edge::operator= (const TraCIServerAPI_Edge & s) private
invalidated assignment operator
processGet()
bool TraCIServerAPI_Edge::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xaa: Get Edge Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 56 of file TraCIServerAPI_Edge.cpp.
References CMD_GET_EDGE_VARIABLE, libsumo::Edge::getCO2Emissions(), libsumo::Edge::getCOEmissions(), libsumo::Edge::getCurrentTravelTime(), libsumo::Edge::getElectricityConsumption(), libsumo::Edge::getFuelConsumption(), libsumo::Edge::getHCEmissions(), libsumo::Edge::getIDCount(), libsumo::Edge::getIDList(), libsumo::Edge::getMeanSpeed(), libsumo::Edge::getNoiseEmissions(), libsumo::Edge::getNOxEmissions(), libsumo::Edge::getOccupancy(), libsumo::Edge::getParameter(), libsumo::Edge::getPersonIDs(), libsumo::Edge::getPMxEmissions(), libsumo::Edge::getVehicleAverageLength(), libsumo::Edge::getVehicleHaltingNumber(), libsumo::Edge::getVehicleIDs(), libsumo::Edge::getVehicleNumber(), libsumo::Edge::getWaitingSeconds(), ID_COUNT, ID_LIST, LAST_STEP_LENGTH, LAST_STEP_MEAN_SPEED, LAST_STEP_OCCUPANCY, LAST_STEP_PERSON_ID_LIST, LAST_STEP_VEHICLE_HALTING_NUMBER, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, tcpip::Storage::readString(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_EDGE_VARIABLE, libsumo::Edge::retrieveExistingEffort(), libsumo::Edge::retrieveExistingTravelTime(), RTYPE_OK, toHex(), TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, VAR_CO2EMISSION, VAR_COEMISSION, VAR_CURRENT_TRAVELTIME, VAR_EDGE_EFFORT, VAR_EDGE_TRAVELTIME, VAR_ELECTRICITYCONSUMPTION, VAR_FUELCONSUMPTION, VAR_HCEMISSION, VAR_NOISEEMISSION, VAR_NOXEMISSION, VAR_PARAMETER, VAR_PMXEMISSION, VAR_WAITING_TIME, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
processSet()
bool TraCIServerAPI_Edge::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xca: Change Edge State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 227 of file TraCIServerAPI_Edge.cpp.
References libsumo::Edge::addEffort(), libsumo::Edge::addTravelTime(), CMD_GET_EDGE_VARIABLE, CMD_SET_EDGE_VARIABLE, CMD_SET_VEHICLE_VARIABLE, LANE_ALLOWED, LANE_DISALLOWED, tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingDouble(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingString(), TraCIServer::readTypeCheckingStringList(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, libsumo::Edge::setAllowedVehicleClasses(), libsumo::Edge::setDisallowedVehicleClasses(), libsumo::Edge::setMaxSpeed(), libsumo::Edge::setParameter(), SUMOTime_MAX, toHex(), TYPE_COMPOUND, VAR_EDGE_EFFORT, VAR_EDGE_TRAVELTIME, VAR_MAXSPEED, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_Edge.h
TraCIServerAPI_Edge.cpp