SUMO - Simulation of Urban MObility: NLDiscreteEventBuilder Class Reference
NLDiscreteEventBuilder Class Reference
#include <NLDiscreteEventBuilder.h>
Public Types
enum ActionType { EV_SAVETLSTATE, EV_SAVETLSWITCHES, EV_SAVETLSWITCHSTATES }
Known action types.
Public Member Functions
void addAction (const SUMOSAXAttributes &attrs, const std::string &basePath)
Builds an action and saves it for further use.
NLDiscreteEventBuilder (MSNet &net)
Constructor.
~NLDiscreteEventBuilder ()
Destructor.
Protected Types
typedef std::map< std::string, ActionType > KnownActions
Definitions of a storage for build actions.
Protected Attributes
KnownActions myActions
Build actions that shall be executed during the simulation.
MSNet & myNet
Private Member Functions
void buildSaveTLStateCommand (const SUMOSAXAttributes &attrs, const std::string &basePath)
Builds an action which saves the state of a certain tls into a file.
void buildSaveTLSwitchesCommand (const SUMOSAXAttributes &attrs, const std::string &basePath)
Builds an action which saves the switch times of links into a file.
void buildSaveTLSwitchStatesCommand (const SUMOSAXAttributes &attrs, const std::string &basePath)
Builds an action which saves the switch times and states of tls into a file.
NLDiscreteEventBuilder & operator= (const NLDiscreteEventBuilder &)
Detailed Description
This class is responsible for building event-handling actions which the simulation shall execute.
Definition at line 53 of file NLDiscreteEventBuilder.h.
Member Typedef Documentation
KnownActions
typedef std::map<std::string, ActionType> NLDiscreteEventBuilder::KnownActions protected
Definitions of a storage for build actions.
Definition at line 89 of file NLDiscreteEventBuilder.h.
Member Enumeration Documentation
ActionType
enum NLDiscreteEventBuilder::ActionType
Known action types.
Enumerator
EV_SAVETLSTATE
"SaveTLSStates"
EV_SAVETLSWITCHES
"SaveTLSSwitchTimes"
EV_SAVETLSWITCHSTATES
"SaveTLSSwitchStates"
Definition at line 56 of file NLDiscreteEventBuilder.h.
Constructor & Destructor Documentation
NLDiscreteEventBuilder()
NLDiscreteEventBuilder::NLDiscreteEventBuilder (MSNet & net)
Constructor.
Definition at line 50 of file NLDiscreteEventBuilder.cpp.
References EV_SAVETLSTATE, EV_SAVETLSWITCHES, EV_SAVETLSWITCHSTATES, and myActions.
~NLDiscreteEventBuilder()
NLDiscreteEventBuilder::~NLDiscreteEventBuilder ()
Destructor.
Definition at line 58 of file NLDiscreteEventBuilder.cpp.
Member Function Documentation
addAction()
void NLDiscreteEventBuilder::addAction (const SUMOSAXAttributes & attrs, const std::string & basePath)
Builds an action and saves it for further use.
Definition at line 62 of file NLDiscreteEventBuilder.cpp.
References buildSaveTLStateCommand(), buildSaveTLSwitchesCommand(), buildSaveTLSwitchStatesCommand(), EV_SAVETLSTATE, EV_SAVETLSWITCHES, EV_SAVETLSWITCHSTATES, SUMOSAXAttributes::getOpt(), myActions, and SUMO_ATTR_TYPE.
Referenced by NLHandler::myStartElement().
buildSaveTLStateCommand()
void NLDiscreteEventBuilder::buildSaveTLStateCommand (const SUMOSAXAttributes & attrs, const std::string & basePath) private
Builds an action which saves the state of a certain tls into a file.
Definition at line 91 of file NLDiscreteEventBuilder.cpp.
References FileHelpers::checkForRelativity(), MSTLLogicControl::get(), MSTLLogicControl::getAllTLIds(), OutputDevice::getDevice(), SUMOSAXAttributes::getOpt(), MSNet::getTLSControl(), MSTLLogicControl::knows(), myNet, SUMO_ATTR_DEST, and SUMO_ATTR_SOURCE.
Referenced by addAction().
buildSaveTLSwitchesCommand()
void NLDiscreteEventBuilder::buildSaveTLSwitchesCommand (const SUMOSAXAttributes & attrs, const std::string & basePath) private
Builds an action which saves the switch times of links into a file.
Definition at line 119 of file NLDiscreteEventBuilder.cpp.
References FileHelpers::checkForRelativity(), MSTLLogicControl::get(), MSTLLogicControl::getAllTLIds(), OutputDevice::getDevice(), SUMOSAXAttributes::getOpt(), MSNet::getTLSControl(), MSTLLogicControl::knows(), myNet, SUMO_ATTR_DEST, and SUMO_ATTR_SOURCE.
Referenced by addAction().
buildSaveTLSwitchStatesCommand()
void NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand (const SUMOSAXAttributes & attrs, const std::string & basePath) private
Builds an action which saves the switch times and states of tls into a file.
Definition at line 147 of file NLDiscreteEventBuilder.cpp.
References FileHelpers::checkForRelativity(), MSTLLogicControl::get(), MSTLLogicControl::getAllTLIds(), OutputDevice::getDevice(), SUMOSAXAttributes::getOpt(), MSNet::getTLSControl(), MSTLLogicControl::knows(), myNet, SUMO_ATTR_DEST, and SUMO_ATTR_SOURCE.
Referenced by addAction().
operator=()
NLDiscreteEventBuilder& NLDiscreteEventBuilder::operator= (const NLDiscreteEventBuilder &) private
Field Documentation
myActions
KnownActions NLDiscreteEventBuilder::myActions protected
Build actions that shall be executed during the simulation.
Definition at line 92 of file NLDiscreteEventBuilder.h.
Referenced by addAction(), and NLDiscreteEventBuilder().
myNet
MSNet& NLDiscreteEventBuilder::myNet protected
Definition at line 94 of file NLDiscreteEventBuilder.h.
Referenced by buildSaveTLStateCommand(), buildSaveTLSwitchesCommand(), and buildSaveTLSwitchStatesCommand().
The documentation for this class was generated from the following files:
NLDiscreteEventBuilder.h
NLDiscreteEventBuilder.cpp