SUMO - Simulation of Urban MObility: MSSOTLRequestTrafficLightLogic Class Reference
MSSOTLRequestTrafficLightLogic Class Reference abstract
#include <MSSOTLRequestTrafficLightLogic.h>
Public Types
Structure definitions
typedef std::vector< MSPhaseDefinition * > Phases
Definition of a list of phases, being the junction logic.
typedef std::vector< MSLink * > LinkVector
Definition of the list of links that are subjected to this tls.
typedef std::vector< LinkVector > LinkVectorVector
Definition of a list that holds lists of links that do have the same attribute.
typedef std::vector< MSLane * > LaneVector
Definition of the list of arrival lanes subjected to this tls.
typedef std::vector< LaneVector > LaneVectorVector
Definition of a list that holds lists of lanes that do have the same attribute.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::string & getID () const
Returns the id.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
int getMinDecisionalPhaseDuration ()
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
void init (NLDetectorBuilder &nb) throw (ProcessError)
Initialises the tls with sensors on incoming and outgoing lanes Sensors are built in the simulation according to the type of sensor specified in the simulation parameter.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSSOTLRequestTrafficLightLogic (MSTLLogicControl &tlcontrol, const std::string &id, const std::string &subid, const Phases &phases, int step, SUMOTime delay, const std::map< std::string, std::string > &parameters) throw ()
Constructor without sensors passed.
MSSOTLRequestTrafficLightLogic (MSTLLogicControl &tlcontrol, const std::string &id, const std::string &subid, const Phases &phases, int step, SUMOTime delay, const std::map< std::string, std::string > &parameters, MSSOTLSensors *sensors) throw ()
Constructor with sensors passed.
void setID (const std::string &newID)
resets the id
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void setPhases (const Phases &phases, int index)
Replaces the phases and set the phase index.
SUMOTime trySwitch ()
Switches to the next phase.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Static Information Retrieval
Switches to the next phase
Parameters
[in] isActive Whether this program is the currently used one
Returns
The time of the next switch
See also
MSTrafficLightLogic::trySwitch
int getPhaseNumber () const
Returns the number of phases.
const Phases & getPhases () const
Returns the phases of this tls program.
const MSPhaseDefinition & getPhase (int givenstep) const
Returns the definition of the phase from the given position within the plan.
Dynamic Information Retrieval
int getCurrentPhaseIndex () const
Returns the current index within the program.
const MSPhaseDefinition & getCurrentPhaseDef () const
Returns the definition of the current phase.
Conversion between time and phase
SUMOTime getPhaseIndexAtTime (SUMOTime simStep) const
Returns the index of the logic at the given simulation step.
SUMOTime getOffsetFromIndex (int index) const
Returns the position (start of a phase during a cycle) from of a given step.
int getIndexFromOffset (SUMOTime offset) const
Returns the step (the phasenumber) of a given position of the cycle.
Changing phases and phase durations
void changeStepAndDuration (MSTLLogicControl &tlcontrol, SUMOTime simStep, int step, SUMOTime stepDuration)
Changes the current phase and her duration.
Handling of controlled links
virtual void addLink (MSLink *link, MSLane *lane, int pos)
Adds a link on building.
virtual void adaptLinkInformationFrom (const MSTrafficLightLogic &logic)
Applies information about controlled links and lanes from the given logic.
std::map< MSLink *, LinkState > collectLinkStates () const
Returns the (uncontrolled) states of the controlled links.
void resetLinkStates (const std::map< MSLink *, LinkState > &vals) const
Resets the states of controlled links.
Switching and setting current rows
bool setTrafficLightSignals (SUMOTime t) const
Applies the current signal states to controlled links.
Static Information Retrieval
const std::string & getProgramID () const
Returns this tl-logic's id.
const LaneVectorVector & getLaneVectors () const
Returns the list of lists of all lanes controlled by this tls.
const LaneVector & getLanesAt (int i) const
Returns the list of lanes that are controlled by the signals at the given position.
const LinkVectorVector & getLinks () const
Returns the list of lists of all affected links.
const LinkVector & getLinksAt (int i) const
Returns the list of links that are controlled by the signals at the given position.
int getLinkIndex (const MSLink *const link) const
Returns the index of the given link.
virtual const std::string getLogicType () const =0
Returns the type of the logic as a string.
Dynamic Information Retrieval
SUMOTime getDefaultCycleTime () const
Returns the cycle time (in ms)
SUMOTime getNextSwitchTime () const
Returns the assumed next switch time.
SUMOTime getSpentDuration () const
Returns the duration spent in the current phase.
Changing phases and phase durations
void addOverridingDuration (SUMOTime duration)
Changes the duration of the next phase.
void setCurrentDurationIncrement (SUMOTime delay)
Delays current phase by the given delay.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Types
typedef std::map< const std::string, std::vector< MSPushButton * > > PhasePushButtons
Protected Member Functions
bool canRelease () throw ()
virtual SUMOTime computeReturnTime ()
int countVehicles (MSPhaseDefinition phase)
virtual int decideNextPhase ()
MSSOTLE2Sensors * getCountSensors ()
Return the sensors that count the passage of vehicles in and out of the tl.
SUMOTime getCurrentPhaseElapsed ()
double getInputSensorsLength ()
double getOutputSensorsLength ()
int getPhaseIndexWithMaxCTS ()
MSSOTLSensors * getSensors ()
double getSpeedThreshold ()
int getThreshold ()
bool isPushButtonPressed ()
bool isThresholdPassed ()
void logStatus ()
void proceedToNextStep ()
Proceed to the next step.
void setStep (int step)
Forces a specific step.
Protected Attributes
PhasePushButtons m_pushButtons
SUMOTime myCurrentDurationIncrement
A value for enlarge the current duration.
SUMOTime myDefaultCycleTime
The cycle time (without changes)
std::string myID
The name of the object.
LaneVectorVector myLanes
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
LinkVectorVector myLinks
The list of LinkVectors; each vector contains the links that belong to the same link index.
std::vector< SUMOTime > myOverridingTimes
A list of duration overrides.
Phases myPhases
The list of phases this logic uses.
std::string myProgramID
The id of the logic.
int myStep
The current step.
SwitchCommand * mySwitchCommand
The current switch command.
Static Protected Attributes
static const LaneVector myEmptyLaneVector
An empty lane vector.
Detailed Description
Definition at line 34 of file MSSOTLRequestTrafficLightLogic.h.
Member Typedef Documentation
LaneVector
typedef std::vector<MSLane*> MSTrafficLightLogic::LaneVector inherited
Definition of the list of arrival lanes subjected to this tls.
Definition at line 77 of file MSTrafficLightLogic.h.
LaneVectorVector
typedef std::vector<LaneVector> MSTrafficLightLogic::LaneVectorVector inherited
Definition of a list that holds lists of lanes that do have the same attribute.
Definition at line 80 of file MSTrafficLightLogic.h.
LinkVector
typedef std::vector<MSLink*> MSTrafficLightLogic::LinkVector inherited
Definition of the list of links that are subjected to this tls.
Definition at line 71 of file MSTrafficLightLogic.h.
LinkVectorVector
typedef std::vector<LinkVector> MSTrafficLightLogic::LinkVectorVector inherited
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 74 of file MSTrafficLightLogic.h.
PhasePushButtons
typedef std::map<const std::string, std::vector<MSPushButton*> > MSSOTLTrafficLightLogic::PhasePushButtons protected inherited
Definition at line 121 of file MSSOTLTrafficLightLogic.h.
Phases
typedef std::vector<MSPhaseDefinition*> MSTrafficLightLogic::Phases inherited
Definition of a list of phases, being the junction logic.
Definition at line 68 of file MSTrafficLightLogic.h.
Constructor & Destructor Documentation
MSSOTLRequestTrafficLightLogic() [1/2]
MSSOTLRequestTrafficLightLogic::MSSOTLRequestTrafficLightLogic (MSTLLogicControl & tlcontrol, const std::string & id, const std::string & subid, const Phases & phases, int step, SUMOTime delay, const std::map< std::string, std::string > & parameters) throw ()
Constructor without sensors passed.
Parameters
[in] tlcontrol The tls control responsible for this tls
[in] id This tls' id
[in] subid This tls' sub-id (program id)
[in] phases Definitions of the phases
[in] step The initial phase index
[in] delay The time to wait before the first switch
Definition at line 23 of file MSSOTLRequestTrafficLightLogic.cpp.
References MsgHandler::getMessageInstance(), and MsgHandler::inform().
MSSOTLRequestTrafficLightLogic() [2/2]
MSSOTLRequestTrafficLightLogic::MSSOTLRequestTrafficLightLogic (MSTLLogicControl & tlcontrol, const std::string & id, const std::string & subid, const Phases & phases, int step, SUMOTime delay, const std::map< std::string, std::string > & parameters, MSSOTLSensors * sensors) throw ()
Constructor with sensors passed.
Parameters
[in] tlcontrol The tls control responsible for this tls
[in] id This tls' id
[in] subid This tls' sub-id (program id)
[in] phases Definitions of the phases
[in] step The initial phase index
[in] delay The time to wait before the first switch
Definition at line 34 of file MSSOTLRequestTrafficLightLogic.cpp.
References MsgHandler::getMessageInstance(), and MsgHandler::inform().
Member Function Documentation
adaptLinkInformationFrom()
void MSTrafficLightLogic::adaptLinkInformationFrom (const MSTrafficLightLogic & logic) virtual inherited
Applies information about controlled links and lanes from the given logic.
If we load a logic after the network has been loaded, we do not get the information about controlled links afterwards. We have to copy them from a previously loaded logic.
Parameters
[in] logic The logic to use the information about controlled links/lanes from
Reimplemented in MSRailSignal, MSRailCrossing, and MSOffTrafficLightLogic.
Definition at line 199 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLanes, and MSTrafficLightLogic::myLinks.
Referenced by MSOffTrafficLightLogic::adaptLinkInformationFrom(), MSRailCrossing::adaptLinkInformationFrom(), MSRailSignal::adaptLinkInformationFrom(), and MSTLLogicControl::TLSLogicVariants::addLogic().
addLink()
void MSTrafficLightLogic::addLink (MSLink * link, MSLane * lane, int pos) virtual inherited
Adds a link on building.
Parameters
[in] link The controlled link
[in] lane The lane this link starts at
[in] pos The link's index (signal group) within this program
Reimplemented in MSRailCrossing.
Definition at line 181 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getInstance(), MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myLinks, and MSLink::setTLState().
Referenced by MSRailCrossing::addLink().
addOverridingDuration()
void MSTrafficLightLogic::addOverridingDuration (SUMOTime duration) inherited
Changes the duration of the next phase.
Parameters
[in] duration The new duration
Definition at line 284 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myOverridingTimes.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTrafficLightLogic::getDefaultCycleTime(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
canRelease()
bool MSSOTLRequestTrafficLightLogic::canRelease () throw () protected virtual
Implements MSSOTLTrafficLightLogic.
Definition at line 46 of file MSSOTLRequestTrafficLightLogic.cpp.
References MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), getMinDecisionalPhaseDuration(), and MSSOTLTrafficLightLogic::isThresholdPassed().
Referenced by getMinDecisionalPhaseDuration().
changeStepAndDuration()
void MSPhasedTrafficLightLogic::changeStepAndDuration (MSTLLogicControl & tlcontrol, SUMOTime simStep, int step, SUMOTime stepDuration) virtual inherited
Changes the current phase and her duration.
Parameters
[in] tlcontrol The responsible traffic lights control
[in] simStep The current simulation step
[in] step Index of the phase to use
[in] stepDuration The left duration of the phase
See also
MSTrafficLightLogic::changeStepAndDuration
Implements MSTrafficLightLogic.
Definition at line 190 of file MSPhasedTrafficLightLogic.cpp.
References MSEventControl::addEvent(), MSTrafficLightLogic::SwitchCommand::deschedule(), MSNet::getBeginOfTimestepEvents(), MSNet::getInstance(), MSPhasedTrafficLightLogic::myStep, and MSTrafficLightLogic::mySwitchCommand.
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
collectLinkStates()
std::map< MSLink *, LinkState > MSTrafficLightLogic::collectLinkStates () const inherited
Returns the (uncontrolled) states of the controlled links.
Returns
The controlled link's states
Definition at line 206 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::saveInitialStates().
computeReturnTime()
virtual SUMOTime MSSOTLTrafficLightLogic::computeReturnTime () inline protected virtual inherited
Reimplemented in MSSwarmTrafficLightLogic.
Definition at line 193 of file MSSOTLTrafficLightLogic.h.
References DELTA_T, MSPhaseDefinition::duration, and MSPhasedTrafficLightLogic::getCurrentPhaseDef().
Referenced by MSSOTLTrafficLightLogic::trySwitch().
countVehicles()
int MSSOTLTrafficLightLogic::countVehicles (MSPhaseDefinition phase) protected inherited
Definition at line 265 of file MSSOTLTrafficLightLogic.cpp.
References MSSOTLSensors::countVehicles(), MSSOTLTrafficLightLogic::getMode(), MSPhaseDefinition::getTargetLaneSet(), MSPhaseDefinition::isTarget(), MAX2(), MSSOTLTrafficLightLogic::mySensors, and WRITE_ERROR.
Referenced by MSSOTLPlatoonTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), and MSSOTLTrafficLightLogic::updateCTS().
decideNextPhase()
int MSSOTLTrafficLightLogic::decideNextPhase () protected virtual inherited
Reimplemented in MSSwarmTrafficLightLogic, MSSOTLPolicyBasedTrafficLightLogic, and MSDeterministicHiLevelTrafficLightLogic.
Definition at line 427 of file MSSOTLTrafficLightLogic.cpp.
References MSSOTLTrafficLightLogic::canRelease(), MSPhasedTrafficLightLogic::getCurrentPhaseDef(), MSPhasedTrafficLightLogic::getCurrentPhaseIndex(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSPhaseDefinition::isCommit(), MSPhaseDefinition::isDecisional(), and MSPhaseDefinition::isTransient().
Referenced by MSSOTLTrafficLightLogic::trySwitch().
getCountSensors()
MSSOTLE2Sensors* MSSOTLTrafficLightLogic::getCountSensors () inline protected inherited
Return the sensors that count the passage of vehicles in and out of the tl.
Definition at line 187 of file MSSOTLTrafficLightLogic.h.
References MSSOTLTrafficLightLogic::myCountSensors.
Referenced by MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), and MSSwarmTrafficLightLogic::updatePheromoneLevels().
getCurrentPhaseDef()
const MSPhaseDefinition & MSPhasedTrafficLightLogic::getCurrentPhaseDef () const virtual inherited
Returns the definition of the current phase.
Returns
The current phase
See also
MSTrafficLightLogic::getCurrentPhaseDef
Implements MSTrafficLightLogic.
Definition at line 139 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::myPhases, and MSPhasedTrafficLightLogic::myStep.
Referenced by MSSOTLPhaseTrafficLightLogic::canRelease(), MSSOTLPlatoonTrafficLightLogic::canRelease(), MSSOTLWaveTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), MSSOTLTrafficLightLogic::computeReturnTime(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSOTLTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), MSSwarmTrafficLightLogic::getLaneLightState(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSSOTLTrafficLightLogic::trySwitch(), and MSSOTLTrafficLightLogic::updateDecayThreshold().
getCurrentPhaseElapsed()
SUMOTime MSSOTLTrafficLightLogic::getCurrentPhaseElapsed () protected inherited
Definition at line 359 of file MSSOTLTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSPhaseDefinition::myLastSwitch.
Referenced by MSSOTLPhaseTrafficLightLogic::canRelease(), MSSOTLPlatoonTrafficLightLogic::canRelease(), canRelease(), MSSOTLWaveTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), and MSSOTLTrafficLightLogic::trySwitch().
getCurrentPhaseIndex()
int MSPhasedTrafficLightLogic::getCurrentPhaseIndex () const virtual inherited
Returns the current index within the program.
Returns
The index of the current phase within the tls
See also
MSTrafficLightLogic::getCurrentPhaseIndex
Implements MSTrafficLightLogic.
Definition at line 133 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::myStep.
Referenced by MSSOTLWaveTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSOTLTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSSOTLTrafficLightLogic::init(), and MSSOTLTrafficLightLogic::trySwitch().
getDefaultCycleTime()
SUMOTime MSTrafficLightLogic::getDefaultCycleTime () const inline inherited
Returns the cycle time (in ms)
Returns
The (maybe changing) cycle time of this tls
Definition at line 266 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::addOverridingDuration(), MSTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getIndexFromOffset(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), MSTrafficLightLogic::getPhaseIndexAtTime(), MSTrafficLightLogic::getSpentDuration(), MSTrafficLightLogic::myDefaultCycleTime, and MSTrafficLightLogic::setCurrentDurationIncrement().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NLJunctionControlBuilder::closeTrafficLightLogic(), and MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice::saveState(), MSDevice_Vehroutes::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getIndexFromOffset()
int MSPhasedTrafficLightLogic::getIndexFromOffset (SUMOTime offset) const virtual inherited
Returns the step (the phasenumber) of a given position of the cycle.
Parameters
[in] offset The offset (time) for which the according phase shall be returned
Returns
The according phase
See also
MSTrafficLightLogic::getIndexFromOffset
Implements MSTrafficLightLogic.
Definition at line 167 of file MSPhasedTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSPhasedTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, and MSPhasedTrafficLightLogic::myPhases.
getInputSensorsLength()
double MSSOTLTrafficLightLogic::getInputSensorsLength () inline protected inherited
Definition at line 164 of file MSSOTLTrafficLightLogic.h.
References TplConvert::_2double(), and Parameterised::getParameter().
Referenced by MSSOTLTrafficLightLogic::init().
getLanesAt()
const LaneVector& MSTrafficLightLogic::getLanesAt (int i) const inline inherited
Returns the list of lanes that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The lanes controlled by the signal at the given index
Definition at line 189 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myEmptyLaneVector, and MSTrafficLightLogic::myLanes.
Referenced by GUITrafficLightLogicWrapper::drawGL(), Command_SaveTLSSwitches::execute(), MSActuatedTrafficLightLogic::gapControl(), GUIViewTraffic::onGamingClick(), and MSDelayBasedTrafficLightLogic::proposeProlongation().
getLaneVectors()
const LaneVectorVector& MSTrafficLightLogic::getLaneVectors () const inline inherited
Returns the list of lists of all lanes controlled by this tls.
Returns
All lanes controlled by this tls, sorted by the signal index
Definition at line 180 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLanes.
Referenced by MSSOTLWaveTrafficLightLogic::countVehicles(), GUITrafficLightLogicWrapper::getCenteringBoundary(), libsumo::TrafficLight::getControlledLanes(), libsumo::TrafficLight::getControlledLinks(), MSSOTLTrafficLightLogic::init(), TraCIServerAPI_TrafficLight::processGet(), and MSFullExport::writeTLS().
getLinkIndex()
int MSTrafficLightLogic::getLinkIndex (const MSLink *const link) const inherited
Returns the index of the given link.
Parameters
[in] link The link to retrieve the index for
Returns
The index of the given link (-1 if it is not controlled by this tls)
Definition at line 248 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by GUITrafficLightLogicWrapper::getLinkIndex(), and MSTrafficLightLogic::getLinksAt().
getLinks()
const LinkVectorVector& MSTrafficLightLogic::getLinks () const inline inherited
Returns the list of lists of all affected links.
Returns
All links controlled by this tls, sorted by the signal index
Definition at line 201 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), GUINet::createTLWrapper(), GUITLLogicPhasesTrackerWindow::drawValues(), Command_SaveTLSSwitches::execute(), libsumo::TrafficLight::getControlledJunctions(), libsumo::TrafficLight::getControlledLinks(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSDeterministicHiLevelTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), and MSOffTrafficLightLogic::rebuildPhase().
getLinksAt()
const LinkVector& MSTrafficLightLogic::getLinksAt (int i) const inline inherited
Returns the list of links that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The links controlled by the signal at the given index
Definition at line 210 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLogicType(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSTrafficLightLogic::getPhases(), and MSTrafficLightLogic::myLinks.
Referenced by MSDeterministicHiLevelTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), and MSSwarmTrafficLightLogic::init().
getLogicType()
virtual const std::string MSTrafficLightLogic::getLogicType () const pure virtual inherited
Returns the type of the logic as a string.
Returns
The type of the logic
Implemented in MSSwarmTrafficLightLogic, MSRailSignal, MSSimpleTrafficLightLogic, MSOffTrafficLightLogic, MSRailCrossing, MSSOTLPolicyBasedTrafficLightLogic, MSDeterministicHiLevelTrafficLightLogic, and MSSOTLWaveTrafficLightLogic.
Referenced by MSTrafficLightLogic::getLinksAt().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getMinDecisionalPhaseDuration()
int MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration () inline
Definition at line 65 of file MSSOTLRequestTrafficLightLogic.h.
References TplConvert::_2int(), canRelease(), and Parameterised::getParameter().
Referenced by canRelease().
getNextSwitchTime()
SUMOTime MSTrafficLightLogic::getNextSwitchTime () const inherited
Returns the assumed next switch time.
The time may change in case of adaptive/actuated traffic lights.
Returns
The assumed next switch time (simulation time)
Definition at line 265 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::SwitchCommand::getNextSwitchTime(), and MSTrafficLightLogic::mySwitchCommand.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTrafficLightLogic::getDefaultCycleTime(), libsumo::TrafficLight::getNextSwitch(), MSTrafficLightLogic::getSpentDuration(), and MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP().
getOffsetFromIndex()
SUMOTime MSPhasedTrafficLightLogic::getOffsetFromIndex (int index) const virtual inherited
Returns the position (start of a phase during a cycle) from of a given step.
Parameters
[in] index The index of the phase to return the begin of
Returns
The begin time of the phase
See also
MSTrafficLightLogic::getOffsetFromIndex
Implements MSTrafficLightLogic.
Definition at line 156 of file MSPhasedTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSPhasedTrafficLightLogic::getPhase(), and MSPhasedTrafficLightLogic::myPhases.
Referenced by MSPhasedTrafficLightLogic::getPhaseIndexAtTime().
getOutputSensorsLength()
double MSSOTLTrafficLightLogic::getOutputSensorsLength () inline protected inherited
Definition at line 168 of file MSSOTLTrafficLightLogic.h.
References TplConvert::_2double(), Parameterised::getParameter(), and MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS().
Referenced by MSSOTLTrafficLightLogic::init().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getPhase()
const MSPhaseDefinition & MSPhasedTrafficLightLogic::getPhase (int givenstep) const virtual inherited
Returns the definition of the phase from the given position within the plan.
Parameters
[in] givenstep The index of the phase within the plan
Returns
The definition of the phase at the given position
See also
MSTrafficLightLogic::getPhase
Implements MSTrafficLightLogic.
Definition at line 125 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::myPhases.
Referenced by MSSOTLTrafficLightLogic::checkPhases(), MSPhasedTrafficLightLogic::getIndexFromOffset(), MSPhasedTrafficLightLogic::getOffsetFromIndex(), MSPhasedTrafficLightLogic::getPhaseIndexAtTime(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSSOTLTrafficLightLogic::setToATargetPhase(), MSSOTLTrafficLightLogic::setupCTS(), MSSOTLTrafficLightLogic::trySwitch(), and MSSOTLTrafficLightLogic::updateCTS().
getPhaseIndexAtTime()
SUMOTime MSPhasedTrafficLightLogic::getPhaseIndexAtTime (SUMOTime simStep) const virtual inherited
Returns the index of the logic at the given simulation step.
Returns
The (estimated) index of the tls at the given simulation time step
See also
MSTrafficLightLogic::getPhaseIndexAtTime
Implements MSTrafficLightLogic.
Definition at line 146 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::getOffsetFromIndex(), MSPhasedTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, MSPhaseDefinition::myLastSwitch, and MSPhasedTrafficLightLogic::myStep.
getPhaseIndexWithMaxCTS()
int MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS () protected inherited
Definition at line 370 of file MSSOTLTrafficLightLogic.cpp.
References Named::getID(), RandHelper::getRandomFrom(), MSSOTLTrafficLightLogic::getTargetPhaseMaxLastSelection(), MSSOTLTrafficLightLogic::lastChain, MSSOTLTrafficLightLogic::targetPhasesCTS, MSSOTLTrafficLightLogic::targetPhasesLastSelection, and WRITE_MESSAGE.
Referenced by MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSOTLTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), and MSSOTLTrafficLightLogic::getOutputSensorsLength().
getPhaseNumber()
int MSPhasedTrafficLightLogic::getPhaseNumber () const virtual inherited
Returns the number of phases.
Returns
The number of this tls program's phases
See also
MSTrafficLightLogic::getPhaseNumber
Implements MSTrafficLightLogic.
Definition at line 114 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::myPhases.
getPhases()
const MSPhasedTrafficLightLogic::Phases & MSPhasedTrafficLightLogic::getPhases () const virtual inherited
Returns the phases of this tls program.
Returns
The phases of this tls program
See also
MSTrafficLightLogic::getPhases
Implements MSTrafficLightLogic.
Definition at line 120 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::myPhases.
Referenced by MSSOTLTrafficLightLogic::checkPhases(), MSSOTLTrafficLightLogic::init(), MSSOTLTrafficLightLogic::setToATargetPhase(), and MSSOTLTrafficLightLogic::setupCTS().
getProgramID()
const std::string& MSTrafficLightLogic::getProgramID () const inline inherited
Returns this tl-logic's id.
Returns
This program's id
Definition at line 172 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myProgramID.
Referenced by Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), GUITrafficLightLogicWrapper::getParameterWindow(), libsumo::TrafficLight::getProgram(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSTrafficLightLogic::init(), and GUIViewTraffic::onGamingClick().
getSensors()
MSSOTLSensors* MSSOTLTrafficLightLogic::getSensors () inline protected inherited
Definition at line 180 of file MSSOTLTrafficLightLogic.h.
References MSSOTLTrafficLightLogic::mySensors.
Referenced by MSSOTLWaveTrafficLightLogic::countVehicles(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), and MSSwarmTrafficLightLogic::updatePheromoneLevels().
getSpeedThreshold()
double MSSOTLTrafficLightLogic::getSpeedThreshold () inline protected inherited
Definition at line 160 of file MSSOTLTrafficLightLogic.h.
References TplConvert::_2double(), and Parameterised::getParameter().
Referenced by MSSOTLTrafficLightLogic::init().
getSpentDuration()
SUMOTime MSTrafficLightLogic::getSpentDuration () const inherited
Returns the duration spent in the current phase.
Returns
The time spent in the current phase
Definition at line 271 of file MSTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSTrafficLightLogic::getNextSwitchTime().
Referenced by MSTrafficLightLogic::getDefaultCycleTime().
getThreshold()
int MSSOTLTrafficLightLogic::getThreshold () inline protected inherited
Definition at line 156 of file MSSOTLTrafficLightLogic.h.
References TplConvert::_2int(), and Parameterised::getParameter().
Referenced by MSSOTLTrafficLightLogic::isThresholdPassed().
init()
void MSSOTLTrafficLightLogic::init (NLDetectorBuilder & nb) throw (ProcessError) virtual inherited
Initialises the tls with sensors on incoming and outgoing lanes Sensors are built in the simulation according to the type of sensor specified in the simulation parameter.
Parameters
[in] nb The detector builder
Exceptions
ProcessError If something fails on initialisation
Reimplemented from MSTrafficLightLogic.
Reimplemented in MSSwarmTrafficLightLogic.
Definition at line 122 of file MSSOTLTrafficLightLogic.cpp.
References MSSOTLE2Sensors::buildCountOutSensors(), MSSOTLE2Sensors::buildCountSensors(), MSSOTLE2Sensors::buildSensors(), DBG, MSSOTLTrafficLightLogic::decayThreshold, MSPhasedTrafficLightLogic::getCurrentPhaseIndex(), Named::getID(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSTrafficLightLogic::getLaneVectors(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getLinksAt(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), Parameterised::getParameter(), MSPhasedTrafficLightLogic::getPhases(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::myCountSensors, Named::myID, MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myLinks, MSSOTLTrafficLightLogic::mySensors, SENSORS_TYPE, SENSORS_TYPE_E1, SENSORS_TYPE_E2, MSSOTLTrafficLightLogic::sensorsSelfBuilt, MSSOTLSensors::stepChanged(), and WRITE_MESSAGE.
Referenced by MSSOTLHiLevelTrafficLightLogic::init().
isPushButtonPressed()
bool MSSOTLTrafficLightLogic::isPushButtonPressed () protected inherited
Checks the if the pushbutton was activated for the current stage
Returns
True if at least a push button was pressed
Definition at line 507 of file MSSOTLTrafficLightLogic.cpp.
References MSPushButton::anyActive(), MSPhasedTrafficLightLogic::getCurrentPhaseDef(), Parameterised::getParameter(), MSPhaseDefinition::getState(), MSPedestrianPushButton::loadPushButtons(), and MSSOTLTrafficLightLogic::m_pushButtons.
Referenced by MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), and MSSwarmTrafficLightLogic::decideNextPhase().
isThresholdPassed()
bool MSSOTLTrafficLightLogic::isThresholdPassed () protected inherited
Definition at line 306 of file MSSOTLTrafficLightLogic.cpp.
References DBG, MSSOTLTrafficLightLogic::decayThreshold, MSPhasedTrafficLightLogic::getCurrentPhaseDef(), Named::getID(), MSNet::getInstance(), MSPhasedTrafficLightLogic::getPhase(), MSPhaseDefinition::getState(), MSSOTLTrafficLightLogic::getThreshold(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::lastChain, RandHelper::rand(), MSSOTLTrafficLightLogic::targetPhasesCTS, time2string(), and WRITE_MESSAGE.
Referenced by MSSOTLPhaseTrafficLightLogic::canRelease(), MSSOTLPlatoonTrafficLightLogic::canRelease(), canRelease(), MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), and MSSwarmTrafficLightLogic::decideNextPhase().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
logStatus()
void MSSOTLTrafficLightLogic::logStatus () protected inherited
Definition at line 84 of file MSSOTLTrafficLightLogic.cpp.
proceedToNextStep()
void MSPhasedTrafficLightLogic::proceedToNextStep () protected inherited
Proceed to the next step.
MEMBER FACTORIZED TO PARENT CLASS (MSTrafficLightLogic)
Definition at line 99 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::myStep, and MSPhasedTrafficLightLogic::setStep().
resetLinkStates()
void MSTrafficLightLogic::resetLinkStates (const std::map< MSLink *, LinkState > & vals) const inherited
Resets the states of controlled links.
Parameters
[in] vals The state of controlled links to use
Definition at line 235 of file MSTrafficLightLogic.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSTrafficLightLogic::myLinks.
setCurrentDurationIncrement()
void MSTrafficLightLogic::setCurrentDurationIncrement (SUMOTime delay) inherited
Delays current phase by the given delay.
Parameters
[in] delay The time by which the current phase shall be delayed
Definition at line 290 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myCurrentDurationIncrement.
Referenced by MSTrafficLightLogic::getDefaultCycleTime().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setPhases()
void MSPhasedTrafficLightLogic::setPhases (const Phases & phases, int index) inherited
Replaces the phases and set the phase index.
Definition at line 203 of file MSPhasedTrafficLightLogic.cpp.
References MSPhasedTrafficLightLogic::deletePhases(), MSPhasedTrafficLightLogic::myPhases, and MSPhasedTrafficLightLogic::myStep.
setStep()
void MSPhasedTrafficLightLogic::setStep (int step) protected inherited
Forces a specific step.
Definition at line 104 of file MSPhasedTrafficLightLogic.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSPhasedTrafficLightLogic::myPhases, and MSPhasedTrafficLightLogic::myStep.
Referenced by MSPhasedTrafficLightLogic::proceedToNextStep(), MSSOTLTrafficLightLogic::setToATargetPhase(), and MSSOTLTrafficLightLogic::trySwitch().
setTrafficLightSignals()
bool MSTrafficLightLogic::setTrafficLightSignals (SUMOTime t) const inherited
Applies the current signal states to controlled links.
Parameters
[in] t The current time
Returns
Always true
See also
LinkState
MSLink::setTLState
Definition at line 219 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSPhaseDefinition::getState(), and MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::SwitchCommand::execute(), MSRailCrossing::init(), MSRailSignal::init(), MSTLLogicControl::TLSLogicVariants::switchTo(), MSRailCrossing::trySwitch(), and MSRailSignal::trySwitch().
trySwitch()
SUMOTime MSSOTLTrafficLightLogic::trySwitch () virtual inherited
Switches to the next phase.
Returns
The time of the next switch
Implements MSTrafficLightLogic.
Definition at line 453 of file MSSOTLTrafficLightLogic.cpp.
References ANALYSIS_DBG, MSSOTLTrafficLightLogic::computeReturnTime(), MSSOTLTrafficLightLogic::decayThreshold, MSSOTLTrafficLightLogic::decideNextPhase(), MSPhasedTrafficLightLogic::getCurrentPhaseDef(), MSSOTLTrafficLightLogic::getCurrentPhaseElapsed(), MSPhasedTrafficLightLogic::getCurrentPhaseIndex(), MSNet::getCurrentTimeStep(), Named::getID(), MSNet::getInstance(), MSPhasedTrafficLightLogic::getPhase(), MSPhaseDefinition::getState(), MSSOTLTrafficLightLogic::getTargetPhaseMaxLastSelection(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSPhaseDefinition::isTarget(), MSSOTLTrafficLightLogic::lastChain, MSPhaseDefinition::myLastSwitch, MSSOTLTrafficLightLogic::mySensors, MSSOTLTrafficLightLogic::resetCTS(), MSPhasedTrafficLightLogic::setStep(), MSSOTLSensors::stepChanged(), MSSOTLTrafficLightLogic::targetPhasesLastSelection, time2string(), MSSOTLTrafficLightLogic::updateCTS(), and WRITE_MESSAGE.
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
m_pushButtons
PhasePushButtons MSSOTLTrafficLightLogic::m_pushButtons protected inherited
Definition at line 122 of file MSSOTLTrafficLightLogic.h.
Referenced by MSSOTLTrafficLightLogic::isPushButtonPressed(), and MSSOTLTrafficLightLogic::~MSSOTLTrafficLightLogic().
myCurrentDurationIncrement
SUMOTime MSTrafficLightLogic::myCurrentDurationIncrement protected inherited
A value for enlarge the current duration.
Definition at line 417 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::setCurrentDurationIncrement(), and MSSimpleTrafficLightLogic::trySwitch().
myDefaultCycleTime
SUMOTime MSTrafficLightLogic::myDefaultCycleTime protected inherited
The cycle time (without changes)
Definition at line 423 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getDefaultCycleTime(), MSPhasedTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSPhasedTrafficLightLogic::getPhaseIndexAtTime(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSOffTrafficLightLogic::MSOffTrafficLightLogic(), MSPhasedTrafficLightLogic::MSPhasedTrafficLightLogic(), MSRailSignal::MSRailSignal(), and MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic().
myEmptyLaneVector
const MSTrafficLightLogic::LaneVector MSTrafficLightLogic::myEmptyLaneVector static protected inherited
An empty lane vector.
Definition at line 426 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getLanesAt().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myLanes
LaneVectorVector MSTrafficLightLogic::myLanes protected inherited
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
Definition at line 411 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSTrafficLightLogic::getLanesAt(), MSTrafficLightLogic::getLaneVectors(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), and MSSwarmTrafficLightLogic::resetLaneCheck().
myLinks
LinkVectorVector MSTrafficLightLogic::myLinks protected inherited
The list of LinkVectors; each vector contains the links that belong to the same link index.
Definition at line 408 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSTrafficLightLogic::collectLinkStates(), MSRailSignal::getAppropriateState(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getLinksAt(), MSRailCrossing::init(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSTrafficLightLogic::initMesoTLSPenalties(), MSSwarmTrafficLightLogic::resetLaneCheck(), MSTrafficLightLogic::resetLinkStates(), and MSTrafficLightLogic::setTrafficLightSignals().
myOverridingTimes
std::vector<SUMOTime> MSTrafficLightLogic::myOverridingTimes protected inherited
A list of duration overrides.
Definition at line 414 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::addOverridingDuration(), and MSSimpleTrafficLightLogic::trySwitch().
myPhases
Phases MSPhasedTrafficLightLogic::myPhases protected inherited
The list of phases this logic uses.
Definition at line 181 of file MSPhasedTrafficLightLogic.h.
Referenced by MSSOTLWaveTrafficLightLogic::canRelease(), MSPhasedTrafficLightLogic::deletePhases(), MSPhasedTrafficLightLogic::getCurrentPhaseDef(), MSPhasedTrafficLightLogic::getIndexFromOffset(), MSPhasedTrafficLightLogic::getOffsetFromIndex(), MSPhasedTrafficLightLogic::getPhase(), MSPhasedTrafficLightLogic::getPhaseNumber(), MSPhasedTrafficLightLogic::getPhases(), MSPhasedTrafficLightLogic::MSPhasedTrafficLightLogic(), MSPhasedTrafficLightLogic::setPhases(), MSPhasedTrafficLightLogic::setStep(), and MSSOTLTrafficLightLogic::~MSSOTLTrafficLightLogic().
myProgramID
std::string MSTrafficLightLogic::myProgramID protected inherited
The id of the logic.
Definition at line 405 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getProgramID(), MSDelayBasedTrafficLightLogic::init(), and MSActuatedTrafficLightLogic::init().
myStep
int MSPhasedTrafficLightLogic::myStep protected inherited
The current step.
Definition at line 197 of file MSPhasedTrafficLightLogic.h.
Referenced by MSPhasedTrafficLightLogic::changeStepAndDuration(), MSPhasedTrafficLightLogic::getCurrentPhaseDef(), MSPhasedTrafficLightLogic::getCurrentPhaseIndex(), MSPhasedTrafficLightLogic::getPhaseIndexAtTime(), MSPhasedTrafficLightLogic::proceedToNextStep(), MSPhasedTrafficLightLogic::setPhases(), and MSPhasedTrafficLightLogic::setStep().
mySwitchCommand
SwitchCommand* MSTrafficLightLogic::mySwitchCommand protected inherited
The current switch command.
Definition at line 420 of file MSTrafficLightLogic.h.
Referenced by MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getNextSwitchTime(), and MSTrafficLightLogic::MSTrafficLightLogic().
The documentation for this class was generated from the following files:
MSSOTLRequestTrafficLightLogic.h
MSSOTLRequestTrafficLightLogic.cpp