SUMO - Simulation of Urban MObility: MSLaneChangerSublane Class Reference
MSLaneChangerSublane Class Reference
Performs lane changing of vehicles.
#include <MSLaneChangerSublane.h>
Public Types
typedef std::vector< ChangeElem > Changer
The list of changers; For each lane, a ChangeElem is being build.
typedef Changer::iterator ChangerIt
the iterator moving over the ChangeElems
typedef Changer::const_iterator ConstChangerIt
the iterator moving over the ChangeElems
Public Member Functions
void laneChange (SUMOTime t)
Start lane-change-process for all vehicles on the edge'e lanes.
MSLaneChangerSublane (const std::vector< MSLane *> *lanes, bool allowChanging)
Constructor.
~MSLaneChangerSublane ()
Destructor.
Protected Types
typedef MSAbstractLaneChangeModel::StateAndDist StateAndDist
Protected Member Functions
void abortLCManeuver (MSVehicle *vehicle)
immediately stop lane-changing and register vehicle as unchanged
bool applyTraCICommands (MSVehicle *vehicle)
Execute TraCI LC-commands.
virtual bool change ()
virtual bool changeOpposite (std::pair< MSVehicle *, double > leader)
int checkChange (int laneOffset, const MSLane *targetLane, const std::pair< MSVehicle *const, double > &leader, const std::pair< MSVehicle *const, double > &neighLead, const std::pair< MSVehicle *const, double > &neighFollow, const std::vector< MSVehicle::LaneQ > &preb) const
StateAndDist checkChangeHelper (MSVehicle *vehicle, int laneOffset, LaneChangeAction alternatives)
helper function that calls checkChangeSublane and sets blocker information
int checkChangeSublane (int laneOffset, LaneChangeAction alternatives, const std::vector< MSVehicle::LaneQ > &preb, double &latDist, double &maneuverDist) const
check whether sub-lane changing in the given direction is desirable and possible
bool checkChangeToNewLane (MSVehicle *vehicle, const int direction, ChangerIt from, ChangerIt to)
check whether the given vehicle has entered the new lane 'to->lane' during a sublane LC-step
int checkChangeWithinEdge (int laneOffset, const std::pair< MSVehicle *const, double > &leader, const std::vector< MSVehicle::LaneQ > &preb) const
void checkTraCICommands (MSVehicle *vehicle)
Take into account traci LC-commands.
bool continueChange (MSVehicle *vehicle, ChangerIt &from)
continue a lane change maneuver and return whether the midpoint was passed in this step (used if gLaneChangeDuration > 0)
bool continueChangeSublane (MSVehicle *vehicle, ChangerIt &from)
Continue a sublane-lane change maneuver and return whether the midpoint was passed in this step.
ChangerIt findCandidate ()
Find current candidate. If there is none, myChanger.end() is returned.
MSLeaderDistanceInfo getLeaders (const ChangerIt &target, const MSVehicle *ego) const
get leaders for ego on the given lane
std::pair< MSVehicle *const, double > getRealFollower (const ChangerIt &target) const
std::pair< MSVehicle *const, double > getRealLeader (const ChangerIt &target) const
virtual void initChanger ()
Initialize the changer before looping over all vehicles.
bool mayChange (int direction) const
whether changing to the lane in the given direction should be considered
void outputLCEnded (MSVehicle *vehicle, ChangerIt &from, ChangerIt &to, int direction)
optional output for end of lane-change maneuvre
void outputLCStarted (MSVehicle *vehicle, ChangerIt &from, ChangerIt &to, int direction)
optional output for start of lane-change maneuvre
void registerUnchanged (MSVehicle *vehicle)
void startChange (MSVehicle *vehicle, ChangerIt &from, int direction)
start the lane change maneuver (and finish it instantly if gLaneChangeDuration == 0)
bool startChangeSublane (MSVehicle *vehicle, ChangerIt &from, double latDist)
change by the specified amount and return whether a new lane was entered
virtual void updateChanger (bool vehHasChanged)
void updateLanes (SUMOTime t)
MSVehicle * veh (ConstChangerIt ce) const
bool vehInChanger () const
Check if there is a single change-candidate in the changer. Returns true if there is one.
Static Protected Member Functions
static void computeOvertakingTime (const MSVehicle *vehicle, const MSVehicle *leader, double gap, double &timeToOvertake, double &spaceToOvertake)
Compute the time and space required for overtaking the given leader.
static MSVehicle * getCloserFollower (const double maxPos, MSVehicle *follow1, MSVehicle *follow2)
return the closer follower of ego
Protected Attributes
const bool myAllowsChanging
ChangerIt myCandi
Changer myChanger
Container for ChangeElemements, one for every lane in the edge.
const bool myChangeToOpposite
whether this edge allows changing to the opposite direction edge
Private Member Functions
MSLaneChangerSublane ()
Default constructor.
MSLaneChangerSublane (const MSLaneChangerSublane &)
Copy constructor.
MSLaneChangerSublane & operator= (const MSLaneChangerSublane &)
Assignment operator.
Detailed Description
Performs lane changing of vehicles.
Definition at line 49 of file MSLaneChangerSublane.h.
Member Typedef Documentation
Changer
typedef std::vector< ChangeElem > MSLaneChanger::Changer inherited
The list of changers; For each lane, a ChangeElem is being build.
Definition at line 112 of file MSLaneChanger.h.
ChangerIt
typedef Changer::iterator MSLaneChanger::ChangerIt inherited
the iterator moving over the ChangeElems
Definition at line 115 of file MSLaneChanger.h.
ConstChangerIt
typedef Changer::const_iterator MSLaneChanger::ConstChangerIt inherited
the iterator moving over the ChangeElems
Definition at line 118 of file MSLaneChanger.h.
StateAndDist
typedef MSAbstractLaneChangeModel::StateAndDist MSLaneChangerSublane::StateAndDist protected
Definition at line 100 of file MSLaneChangerSublane.h.
Constructor & Destructor Documentation
MSLaneChangerSublane() [1/3]
MSLaneChangerSublane::MSLaneChangerSublane (const std::vector< MSLane *> * lanes, bool allowChanging)
Constructor.
Definition at line 58 of file MSLaneChangerSublane.cpp.
References MSLaneChanger::myChanger.
~MSLaneChangerSublane()
MSLaneChangerSublane::~MSLaneChangerSublane ()
Destructor.
Definition at line 74 of file MSLaneChangerSublane.cpp.
MSLaneChangerSublane() [2/3]
MSLaneChangerSublane::MSLaneChangerSublane () private
Default constructor.
MSLaneChangerSublane() [3/3]
MSLaneChangerSublane::MSLaneChangerSublane (const MSLaneChangerSublane &) private
Copy constructor.
Member Function Documentation
abortLCManeuver()
void MSLaneChangerSublane::abortLCManeuver (MSVehicle * vehicle) protected
immediately stop lane-changing and register vehicle as unchanged
Definition at line 218 of file MSLaneChangerSublane.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSLaneChanger::registerUnchanged(), MSAbstractLaneChangeModel::setManeuverDist(), MSAbstractLaneChangeModel::setSpeedLat(), and SIMTIME.
Referenced by change(), and startChangeSublane().
applyTraCICommands()
bool MSLaneChanger::applyTraCICommands (MSVehicle * vehicle) protected inherited
Execute TraCI LC-commands.
Note
This is currently only used within non-actionsteps for the non-sublane model.
Returns
whether lane was changed
Definition at line 410 of file MSLaneChanger.cpp.
References MSLaneChanger::continueChange(), MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getOwnState(), LCA_BLOCKED, LCA_LEFT, LCA_RIGHT, MSLaneChanger::myCandi, and MSAbstractLaneChangeModel::startLaneChangeManeuver().
Referenced by MSLaneChanger::change(), and MSLaneChanger::veh().
change()
bool MSLaneChangerSublane::change () protected virtual
Find a new candidate and try to change it.
myAllowsChanging || vehicle->getLaneChangeModel().alreadyChanged() ||
Reimplemented from MSLaneChanger.
Definition at line 112 of file MSLaneChangerSublane.cpp.
References abortLCManeuver(), MSVehicle::adaptBestLanesOccupation(), checkChangeHelper(), MSLaneChanger::checkTraCICommands(), continueChangeSublane(), DEBUG_COND, MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::decideDirection(), MSAbstractLaneChangeModel::StateAndDist::dir, MSLaneChanger::findCandidate(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), getLeaders(), MSAbstractLaneChangeModel::getManeuverDist(), MSAbstractLaneChangeModel::getSpeedLat(), MSVehicle::isActive(), MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::isRemoteControlled(), MSVehicle::isStoppedOnLane(), MSAbstractLaneChangeModel::StateAndDist::latDist, LCA_BLOCKED, LCA_LEFT, LCA_NONE, LCA_RIGHT, LCA_URGENT, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::StateAndDist::maneuverDist, MSLaneChanger::mayChange(), MSLaneChanger::myCandi, MSLaneChanger::myChanger, MSLaneChanger::registerUnchanged(), MSAbstractLaneChangeModel::setManeuverDist(), MSAbstractLaneChangeModel::setOwnState(), SIMTIME, startChangeSublane(), MSAbstractLaneChangeModel::StateAndDist::state, toString(), MSVehicle::updateBestLanes(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), and MSLaneChanger::veh().
changeOpposite()
bool MSLaneChanger::changeOpposite (std::pair< MSVehicle *, double > leader) protected virtual inherited
try changing to the opposite direction edge.
XXX use a dedicated transformation function
XXX compute a better lateral position
Definition at line 950 of file MSLaneChanger.cpp.
References MSCFModel::brakeGap(), MSLaneChanger::checkChange(), MSLaneChanger::computeOvertakingTime(), DEBUG_COND, MSLaneChanger::findCandidate(), MSLane::forceVehicleInsertion(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLinkContHelper::getConnectingLink(), MSLink::getDirection(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getInfluencer(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSLane::getOpposite(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), MSVehicle::getPositionOnLane(), MSVehicle::Influencer::getRespectJunctionPriority(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLink::getState(), MSVehicleType::getVehicleClass(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSVehicle::hasInfluencer(), MSLink::havePriority(), MSLink::haveRed(), MSLink::haveYellow(), MSVehicle::ignoreRed(), MSAbstractLaneChangeModel::isOpposite(), MSVehicle::isStopped(), LCA_BLOCKED, LCA_COOPERATIVE, LCA_WANTS_LANECHANGE, MSVehicle::LaneQ::length, LINKDIR_STRAIGHT, LINKSTATE_ZIPPER, MAX2(), MIN2(), MSVehicle::State::myBackPos, MSLaneChanger::myCandi, MSLaneChanger::myChangeToOpposite, MSVehicle::State::myPos, MSVehicle::myState, MSVehicle::nextStopDist(), MSMoveReminder::NOTIFICATION_LANE_CHANGE, OPPOSITE_OVERTAKING_MAX_LOOKAHEAD, OPPOSITE_OVERTAKING_MAX_LOOKAHEAD_EMERGENCY, OPPOSITE_OVERTAKING_ONCOMING_LOOKAHEAD, SIMTIME, MSAbstractLaneChangeModel::startLaneChangeManeuver(), SVC_EMERGENCY, toString(), and MSLaneChanger::veh().
Referenced by MSLaneChanger::change(), and MSLaneChanger::veh().
checkChange()
int MSLaneChanger::checkChange (int laneOffset, const MSLane * targetLane, const std::pair< MSVehicle *const, double > & leader, const std::pair< MSVehicle *const, double > & neighLead, const std::pair< MSVehicle *const, double > & neighFollow, const std::vector< MSVehicle::LaneQ > & preb) const protected inherited
Definition at line 695 of file MSLaneChanger.cpp.
References ACCEL2SPEED, MSCFModel::brakeGap(), DEBUG_COND, DELTA_T, MSVehicle::getAcceleration(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getCriticalLeader(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLeader(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getParallelLane(), MSVehicle::getPositionOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gLaneChangeDuration, MSVehicle::influenceChangeDecision(), MSEdge::isInternal(), MSLane::isLinkEnd(), LCA_BLOCKED, LCA_BLOCKED_BY_LEFT_FOLLOWER, LCA_BLOCKED_BY_LEFT_LEADER, LCA_BLOCKED_BY_RIGHT_FOLLOWER, LCA_BLOCKED_BY_RIGHT_LEADER, LCA_INSUFFICIENT_SPACE, LCA_OVERLAPPING, LCA_WANTS_LANECHANGE, LINKDIR_LEFT, LINKDIR_RIGHT, MAX2(), MIN2(), MSLaneChanger::myCandi, MSAbstractLaneChangeModel::NO_NEIGHBOR, MSAbstractLaneChangeModel::saveState(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), SIMTIME, STEPS2TIME, MSLane::succLinkSec(), toString(), TS, MSVehicle::unsafeLinkAhead(), MSLaneChanger::veh(), and MSAbstractLaneChangeModel::wantsChange().
Referenced by MSLaneChanger::changeOpposite(), MSLaneChanger::checkChangeWithinEdge(), and MSLaneChanger::veh().
checkChangeHelper()
MSLaneChangerSublane::StateAndDist MSLaneChangerSublane::checkChangeHelper (MSVehicle * vehicle, int laneOffset, LaneChangeAction alternatives) protected
helper function that calls checkChangeSublane and sets blocker information
Definition at line 232 of file MSLaneChangerSublane.cpp.
References checkChangeSublane(), MSAbstractLaneChangeModel::StateAndDist::dir, MSVehicle::getBestLanes(), MSAbstractLaneChangeModel::StateAndDist::latDist, LCA_BLOCKED, LCA_URGENT, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::StateAndDist::maneuverDist, MSLaneChanger::mayChange(), MSLaneChanger::myCandi, and MSAbstractLaneChangeModel::StateAndDist::state.
Referenced by change().
checkChangeSublane()
int MSLaneChangerSublane::checkChangeSublane (int laneOffset, LaneChangeAction alternatives, const std::vector< MSVehicle::LaneQ > & preb, double & latDist, double & maneuverDist) const protected
check whether sub-lane changing in the given direction is desirable and possible
Parameters
[in] laneOffset The direction in which changing should be checked
[in] leaders The candidate vehicle's leaders
[in] preb The bestLanse of the candidaet vehicle
[out] latDist The distance by which the vehicle changes laterally
[out] maneuverDist The lateral distance for the complete envisioned maneuver (used for maneuver continuation in non-actionsteps).
Definition at line 517 of file MSLaneChangerSublane.cpp.
References DEBUG_COND, MSVehicle::getBackPositionOnLane(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSVehicle::influenceChangeDecision(), MSLaneChanger::myCandi, MSAbstractLaneChangeModel::saveState(), SIMTIME, toString(), MSLeaderDistanceInfo::toString(), MSLaneChanger::veh(), and MSAbstractLaneChangeModel::wantsChangeSublane().
Referenced by checkChangeHelper().
checkChangeToNewLane()
bool MSLaneChangerSublane::checkChangeToNewLane (MSVehicle * vehicle, const int direction, ChangerIt from, ChangerIt to) protected
check whether the given vehicle has entered the new lane 'to->lane' during a sublane LC-step
Definition at line 382 of file MSLaneChangerSublane.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), getLeaders(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSLane::getWidth(), MSAbstractLaneChangeModel::haveLCOutput(), MSVehicle::isActive(), MSLaneChanger::mayChange(), MSVehicle::State::myPosLat, MSVehicle::myState, MSLaneChanger::registerUnchanged(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
Referenced by startChangeSublane().
checkChangeWithinEdge()
int MSLaneChanger::checkChangeWithinEdge (int laneOffset, const std::pair< MSVehicle *const, double > & leader, const std::vector< MSVehicle::LaneQ > & preb) const protected inherited
Definition at line 678 of file MSLaneChanger.cpp.
References MSLaneChanger::checkChange(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), and MSLaneChanger::myCandi.
Referenced by MSLaneChanger::change(), and MSLaneChanger::veh().
checkTraCICommands()
void MSLaneChanger::checkTraCICommands (MSVehicle * vehicle) protected inherited
Take into account traci LC-commands.
Note
This is currently only used within non-actionsteps.
Definition at line 389 of file MSLaneChanger.cpp.
References MSAbstractLaneChangeModel::checkTraCICommands(), DEBUG_COND, MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getOwnState(), LCA_BLOCKED, LCA_OVERLAPPING, SIMTIME, and toString().
Referenced by change(), MSLaneChanger::change(), and MSLaneChanger::veh().
computeOvertakingTime()
void MSLaneChanger::computeOvertakingTime (const MSVehicle * vehicle, const MSVehicle * leader, double gap, double & timeToOvertake, double & spaceToOvertake) static protected inherited
Compute the time and space required for overtaking the given leader.
Parameters
[in] vehicle The vehicle that wants to overtake
[in] leader The vehicle to be overtaken
[in] gap The gap between vehicle and leader
[out] timeToOvertake The time for overtaking
[out] spaceToOvertake The space for overtaking
XXX ignore speed limit when overtaking through the opposite lane?
Definition at line 1225 of file MSLaneChanger.cpp.
References MSVehicle::getCarFollowModel(), MSVehicle::getLane(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), OPPOSITE_OVERTAKING_SAFE_TIMEGAP, and TS.
Referenced by MSLaneChanger::changeOpposite(), and MSLaneChanger::veh().
continueChange()
bool MSLaneChanger::continueChange (MSVehicle * vehicle, ChangerIt & from) protected inherited
continue a lane change maneuver and return whether the midpoint was passed in this step (used if gLaneChangeDuration > 0)
Definition at line 446 of file MSLaneChanger.cpp.
References MSVehicle::computeAngle(), DEBUG_COND, MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSBaseVehicle::getID(), Named::getIDSecure(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::getSpeedLat(), MSLane::getWidth(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::myAngle, MSVehicle::myCachedPosition, MSLaneChanger::myCandi, MSVehicle::State::myPosLat, MSVehicle::myState, MSAbstractLaneChangeModel::primaryLaneChanged(), SIMTIME, MSAbstractLaneChangeModel::updateCompletion(), and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSLaneChanger::applyTraCICommands(), MSLaneChanger::change(), MSLaneChanger::startChange(), and MSLaneChanger::veh().
continueChangeSublane()
bool MSLaneChangerSublane::continueChangeSublane (MSVehicle * vehicle, ChangerIt & from) protected
Continue a sublane-lane change maneuver and return whether the midpoint was passed in this step.
Definition at line 252 of file MSLaneChangerSublane.cpp.
References MSAbstractLaneChangeModel::computeSpeedLat(), DEBUG_COND, MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getManeuverDist(), MSLaneChanger::registerUnchanged(), SIMTIME, SPEED2DIST, and startChangeSublane().
Referenced by change().
findCandidate()
MSLaneChanger::ChangerIt MSLaneChanger::findCandidate () protected inherited
Find current candidate. If there is none, myChanger.end() is returned.
Definition at line 197 of file MSLaneChanger.cpp.
References MSBaseVehicle::getID(), MSVehicle::getPositionOnLane(), MSVehicle::isFrontOnLane(), MSLaneChanger::myChanger, SIMTIME, and MSLaneChanger::veh().
Referenced by change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), and MSLaneChanger::veh().
getCloserFollower()
MSVehicle * MSLaneChanger::getCloserFollower (const double maxPos, MSVehicle * follow1, MSVehicle * follow2) static protected inherited
return the closer follower of ego
Definition at line 663 of file MSLaneChanger.cpp.
References MSVehicle::getPositionOnLane().
Referenced by MSLaneChanger::getRealFollower(), and MSLaneChanger::veh().
getLeaders()
MSLeaderDistanceInfo MSLaneChangerSublane::getLeaders (const ChangerIt & target, const MSVehicle * ego) const protected
get leaders for ego on the given lane
Definition at line 449 of file MSLaneChangerSublane.cpp.
References MSLeaderDistanceInfo::addLeader(), MSCFModel::brakeGap(), DEBUG_COND, MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLaneChanger::myCandi, MSLeaderInfo::numFreeSublanes(), MSLeaderInfo::numSublanes(), SIMTIME, MSLeaderDistanceInfo::toString(), and MSLaneChanger::veh().
Referenced by change(), and checkChangeToNewLane().
getRealFollower()
std::pair< MSVehicle *const, double > MSLaneChanger::getRealFollower (const ChangerIt & target) const protected inherited
Definition at line 590 of file MSLaneChanger.cpp.
References DEBUG_COND, MSVehicle::getBackPositionOnLane(), MSLaneChanger::getCloserFollower(), MSBaseVehicle::getID(), MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSLaneChanger::myCandi, SIMTIME, and MSLaneChanger::veh().
Referenced by MSLaneChanger::checkChangeWithinEdge(), and MSLaneChanger::veh().
getRealLeader()
std::pair< MSVehicle *const, double > MSLaneChanger::getRealLeader (const ChangerIt & target) const protected inherited
Definition at line 493 of file MSLaneChanger.cpp.
References MSCFModel::brakeGap(), DEBUG_COND, MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLaneChanger::myCandi, MSLane::myPartialVehicles, SIMTIME, and MSLaneChanger::veh().
Referenced by MSLaneChanger::change(), MSLaneChanger::checkChangeWithinEdge(), and MSLaneChanger::veh().
initChanger()
void MSLaneChangerSublane::initChanger () protected virtual
Initialize the changer before looping over all vehicles.
Reimplemented from MSLaneChanger.
Definition at line 77 of file MSLaneChangerSublane.cpp.
References MSLaneChanger::initChanger(), and MSLaneChanger::myChanger.
laneChange()
void MSLaneChanger::laneChange (SUMOTime t) inherited
Start lane-change-process for all vehicles on the edge'e lanes.
Definition at line 122 of file MSLaneChanger.cpp.
References MSLaneChanger::change(), MSLaneChanger::initChanger(), MSLaneChanger::myChanger, MSLaneChanger::updateChanger(), MSLaneChanger::updateLanes(), and MSLaneChanger::vehInChanger().
Referenced by MSEdge::changeLanes().
mayChange()
bool MSLaneChanger::mayChange (int direction) const protected inherited
whether changing to the lane in the given direction should be considered
Definition at line 236 of file MSLaneChanger.cpp.
References MSLaneChanger::myAllowsChanging, MSLaneChanger::myCandi, and MSLaneChanger::veh().
Referenced by change(), MSLaneChanger::change(), checkChangeHelper(), checkChangeToNewLane(), startChangeSublane(), and MSLaneChanger::veh().
operator=()
MSLaneChangerSublane& MSLaneChangerSublane::operator= (const MSLaneChangerSublane &) private
Assignment operator.
outputLCEnded()
void MSLaneChangerSublane::outputLCEnded (MSVehicle * vehicle, ChangerIt & from, ChangerIt & to, int direction) protected
optional output for end of lane-change maneuvre
Definition at line 436 of file MSLaneChangerSublane.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getOwnState(), MSAbstractLaneChangeModel::haveLCOutput(), MSAbstractLaneChangeModel::laneChangeOutput(), LCA_CHANGE_REASONS, LCA_SUBLANE, MSAbstractLaneChangeModel::outputLCEnded(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
Referenced by startChangeSublane().
outputLCStarted()
void MSLaneChangerSublane::outputLCStarted (MSVehicle * vehicle, ChangerIt & from, ChangerIt & to, int direction) protected
optional output for start of lane-change maneuvre
Definition at line 409 of file MSLaneChangerSublane.cpp.
References DEBUG_COND, MSVehicle::getBackPositionOnLane(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getOwnState(), MSAbstractLaneChangeModel::getPrevState(), MSAbstractLaneChangeModel::haveLCOutput(), MSAbstractLaneChangeModel::laneChangeOutput(), LCA_BLOCKED, LCA_CHANGE_REASONS, LCA_STAY, LCA_SUBLANE, MSAbstractLaneChangeModel::outputLCStarted(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), SIMTIME, and toString().
Referenced by startChangeSublane().
registerUnchanged()
void MSLaneChanger::registerUnchanged (MSVehicle * vehicle) protected inherited
Update changer for vehicles that did not change
Definition at line 380 of file MSLaneChanger.cpp.
References MSVehicle::getLaneChangeModel(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSLaneChanger::myCandi, MSAbstractLaneChangeModel::unchanged(), and MSLaneChanger::veh().
Referenced by abortLCManeuver(), change(), MSLaneChanger::change(), checkChangeToNewLane(), continueChangeSublane(), and MSLaneChanger::veh().
startChange()
void MSLaneChanger::startChange (MSVehicle * vehicle, ChangerIt & from, int direction) protected inherited
start the lane change maneuver (and finish it instantly if gLaneChangeDuration == 0)
Definition at line 432 of file MSLaneChanger.cpp.
References MSLaneChanger::continueChange(), MSVehicle::getLaneChangeModel(), MSLaneChanger::myCandi, and MSAbstractLaneChangeModel::startLaneChangeManeuver().
Referenced by MSLaneChanger::change(), and MSLaneChanger::veh().
startChangeSublane()
bool MSLaneChangerSublane::startChangeSublane (MSVehicle * vehicle, ChangerIt & from, double latDist) protected
change by the specified amount and return whether a new lane was entered
Definition at line 274 of file MSLaneChangerSublane.cpp.
References abortLCManeuver(), checkChangeToNewLane(), DEBUG_COND, MSAbstractLaneChangeModel::debugVehicle(), DIST2SPEED, MSVehicle::getAngle(), MSAbstractLaneChangeModel::getCommittedSpeed(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getIndex(), MSVehicle::getInfluencer(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getManeuverDist(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getPositionOnLane(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::getShape(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::getTargetLane(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MSLane::getWidth(), MSLane::interpolateLanePosToGeometryPos(), Position::INVALID, LCA_TRACI, MSLaneChanger::mayChange(), MSVehicle::myCachedPosition, MSLaneChanger::myChanger, MSVehicle::State::myPosLat, MSVehicle::myState, NUMERICAL_EPS, outputLCEnded(), outputLCStarted(), RAD2DEG, PositionVector::rotationAtOffset(), MSVehicle::setAngle(), MSAbstractLaneChangeModel::setManeuverDist(), MSAbstractLaneChangeModel::setSpeedLat(), MSVehicle::Influencer::setSublaneChange(), SIMTIME, SPEED2DIST, MSAbstractLaneChangeModel::updateSafeLatDist(), MSAbstractLaneChangeModel::updateShadowLane(), and MSAbstractLaneChangeModel::updateTargetLane().
Referenced by change(), and continueChangeSublane().
updateChanger()
void MSLaneChangerSublane::updateChanger (bool vehHasChanged) protected virtual
After the possible change, update the changer.
Reimplemented from MSLaneChanger.
Definition at line 91 of file MSLaneChangerSublane.cpp.
References MSLane::getIndex(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), MSLaneChanger::myCandi, MSLaneChanger::myChanger, and MSLaneChanger::updateChanger().
updateLanes()
void MSLaneChanger::updateLanes (SUMOTime t) protected inherited
During lane-change a temporary vehicle container is filled within the lanes (bad practice to modify foreign members, I know). Swap this container with the real one.
Definition at line 179 of file MSLaneChanger.cpp.
References MSLaneChanger::myChanger.
Referenced by MSLaneChanger::laneChange(), and MSLaneChanger::veh().
veh()
MSVehicle* MSLaneChanger::veh (ConstChangerIt ce) const inline protected inherited
Returns the furthes unhandled vehicle on this change-elements lane or 0 if there is none.
Definition at line 139 of file MSLaneChanger.h.
References MSLaneChanger::applyTraCICommands(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLaneChanger::checkChangeWithinEdge(), MSLaneChanger::checkTraCICommands(), MSLaneChanger::computeOvertakingTime(), MSLaneChanger::continueChange(), MSLaneChanger::findCandidate(), MSLaneChanger::getCloserFollower(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLaneChanger::mayChange(), MSLaneChanger::registerUnchanged(), MSLaneChanger::startChange(), MSLaneChanger::updateChanger(), and MSLaneChanger::updateLanes().
Referenced by change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), checkChangeSublane(), MSLaneChanger::findCandidate(), getLeaders(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLaneChanger::mayChange(), MSLaneChanger::registerUnchanged(), MSLaneChanger::updateChanger(), and MSLaneChanger::vehInChanger().
vehInChanger()
bool MSLaneChanger::vehInChanger () const inline protected inherited
Check if there is a single change-candidate in the changer. Returns true if there is one.
Definition at line 126 of file MSLaneChanger.h.
References MSLaneChanger::myChanger, and MSLaneChanger::veh().
Referenced by MSLaneChanger::laneChange().
Field Documentation
myAllowsChanging
const bool MSLaneChanger::myAllowsChanging protected inherited
Definition at line 233 of file MSLaneChanger.h.
Referenced by MSLaneChanger::change(), and MSLaneChanger::mayChange().
myCandi
ChangerIt MSLaneChanger::myCandi protected inherited
Change-candidate. Last of the vehicles in changer. Only this one will try to change. Every vehicle on the edge will be a candidate once in the change-process.
Definition at line 229 of file MSLaneChanger.h.
Referenced by MSLaneChanger::applyTraCICommands(), change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), checkChangeHelper(), checkChangeSublane(), MSLaneChanger::checkChangeWithinEdge(), MSLaneChanger::continueChange(), getLeaders(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLaneChanger::mayChange(), MSLaneChanger::registerUnchanged(), MSLaneChanger::startChange(), updateChanger(), and MSLaneChanger::updateChanger().
myChanger
Changer MSLaneChanger::myChanger protected inherited
Container for ChangeElemements, one for every lane in the edge.
Definition at line 224 of file MSLaneChanger.h.
Referenced by change(), MSLaneChanger::change(), MSLaneChanger::findCandidate(), initChanger(), MSLaneChanger::initChanger(), MSLaneChanger::laneChange(), MSLaneChanger::MSLaneChanger(), MSLaneChangerSublane(), startChangeSublane(), updateChanger(), MSLaneChanger::updateLanes(), and MSLaneChanger::vehInChanger().
myChangeToOpposite
const bool MSLaneChanger::myChangeToOpposite protected inherited
whether this edge allows changing to the opposite direction edge
Definition at line 236 of file MSLaneChanger.h.
Referenced by MSLaneChanger::changeOpposite().
The documentation for this class was generated from the following files:
MSLaneChangerSublane.h
MSLaneChangerSublane.cpp