SUMO - Simulation of Urban MObility: GUISUMOViewParent Class Reference
GUISUMOViewParent Class Reference
A single child window which contains a view of the simulation area.
#include <GUISUMOViewParent.h>
Public Types
enum ViewType { VIEW_2D_OPENGL, VIEW_3D_OSG }
Available view types.
Public Member Functions
void buildColoringToolBar ()
void buildNavigationToolBar ()
void buildScreenshotToolBar ()
virtual void create ()
virtual FXGLCanvas * getBuildGLCanvas () const
FXComboBox & getColoringSchemesCombo ()
FXPopup * getLocatorPopup ()
FXToolBar & getNavigationToolBar (GUISUMOAbstractView &v)
GUIMainWindow * getParent ()
Returns the main window.
GUISUMOAbstractView * getView () const
GUISUMOViewParent (FXMDIClient *p, FXMDIMenu *mdimenu, const FXString &name, GUIMainWindow *parentWindow, FXIcon *ic=NULL, FXuint opts=0, FXint x=0, FXint y=0, FXint w=0, FXint h=0)
Constructor.
virtual GUISUMOAbstractView * init (FXGLCanvas *share, GUINet &net, ViewType type)
"Initialises" this window by building the contents
bool isSelected (GUIGlObject *o) const
true if the object is selected (may include extra logic besides calling gSelected)
long onCmdChangeColorScheme (FXObject *, FXSelector sel, void *)
long onCmdEditViewport (FXObject *, FXSelector, void *)
long onCmdEditViewScheme (FXObject *, FXSelector, void *)
long onCmdLocate (FXObject *, FXSelector, void *)
locator-callback
long onCmdMakeSnapshot (FXObject *sender, FXSelector, void *)
Called if the user wants to make a snapshot (screenshot)
long onCmdRecenterView (FXObject *, FXSelector, void *)
long onCmdShowToolTips (FXObject *sender, FXSelector, void *)
long onCmdZoomStyle (FXObject *sender, FXSelector, void *)
long onKeyPress (FXObject *o, FXSelector sel, void *data)
handle keys
long onKeyRelease (FXObject *o, FXSelector sel, void *data)
long onSimStep (FXObject *sender, FXSelector, void *)
Called on a simulation step.
void setToolBarVisibility (const bool value)
about toggled gaming status
void setView (GUIGlID id)
Centers the view onto the given artifact.
~GUISUMOViewParent ()
Destructor.
Protected Member Functions
GUISUMOViewParent ()
FOX needs this.
Protected Attributes
FXComboBox * myColoringSchemes
FXVerticalFrame * myContentFrame
FXMenuButton * myLocatorButton
FXPopup * myLocatorPopup
The locator menu.
FXToolBar * myNavigationToolBar
The tool bar.
GUIMainWindow * myParent
The parent window.
GUISUMOAbstractView * myView
the view
Detailed Description
A single child window which contains a view of the simulation area.
It is made of a tool-bar containing a field to change the type of display, buttons that allow to choose an artifact and some other view controlling options.
The rest of the window is a canvas that contains the display itself
Definition at line 65 of file GUISUMOViewParent.h.
Member Enumeration Documentation
ViewType
enum GUISUMOViewParent::ViewType
Available view types.
Enumerator
VIEW_2D_OPENGL
plain 2D openGL view (
See also
GUIViewTraffic)
VIEW_3D_OSG
plain 3D OSG view (
See also
GUIOSGView)
Definition at line 71 of file GUISUMOViewParent.h.
Constructor & Destructor Documentation
GUISUMOViewParent() [1/2]
GUISUMOViewParent::GUISUMOViewParent (FXMDIClient * p, FXMDIMenu * mdimenu, const FXString & name, GUIMainWindow * parentWindow, FXIcon * ic = NULL, FXuint opts = 0, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0)
Constructor.
Parameters
[in] p The MDI-pane this window is shown within
[in] mdimenu The MDI-menu for alignment
[in] name The name of the window
[in] parentWindow The main window
[in] ic The icon of this window
[in] opts Window options
[in] x Initial x-position
[in] y Initial x-position
[in] w Initial width
[in] h Initial height
Definition at line 98 of file GUISUMOViewParent.cpp.
~GUISUMOViewParent()
GUISUMOViewParent::~GUISUMOViewParent ()
Destructor.
Definition at line 129 of file GUISUMOViewParent.cpp.
References GUIGlChildWindow::myParent, and GUIMainWindow::removeChild().
GUISUMOViewParent() [2/2]
GUISUMOViewParent::GUISUMOViewParent () inline protected
FOX needs this.
Definition at line 130 of file GUISUMOViewParent.h.
Member Function Documentation
buildColoringToolBar()
void GUIGlChildWindow::buildColoringToolBar () inherited
Definition at line 126 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignComboBoxNCol, GUIDesignComboBoxStatic, GUIDesignVerticalSeparator, ICON_COLORWHEEL, MID_COLOURSCHEMECHANGE, MID_EDITVIEWSCHEME, GUIGlChildWindow::myColoringSchemes, and GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIGlChildWindow::getView().
buildNavigationToolBar()
void GUIGlChildWindow::buildNavigationToolBar () inherited
Definition at line 93 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignBar, GUIDesignButtonToolbar, GUIDesignButtonToolbarCheckable, GUIDesignButtonToolbarLocator, ICON_EDITVIEWPORT, ICON_LOCATE, ICON_RECENTERVIEW, ICON_SHOWTOOLTIPS, ICON_ZOOMSTYLE, MID_EDITVIEWPORT, MID_RECENTERVIEW, MID_SHOWTOOLTIPS, MID_ZOOM_STYLE, GUIGlChildWindow::myContentFrame, GUIGlChildWindow::myLocatorButton, GUIGlChildWindow::myLocatorPopup, GUIGlChildWindow::myNavigationToolBar, and MFXCheckableButton::setChecked().
Referenced by GUIGlChildWindow::getView().
buildScreenshotToolBar()
void GUIGlChildWindow::buildScreenshotToolBar () inherited
Definition at line 141 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignVerticalSeparator, ICON_CAMERA, MID_MAKESNAPSHOT, and GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIGlChildWindow::getView().
create()
void GUIGlChildWindow::create () virtual inherited
Definition at line 84 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myLocatorPopup, GUIGlChildWindow::myNavigationToolBar, and GUIGlChildWindow::myView.
Referenced by GNEViewParent::GNEViewParent(), and GUIApplicationWindow::openNewView().
getBuildGLCanvas()
FXGLCanvas * GUIGlChildWindow::getBuildGLCanvas () const virtual inherited
Definition at line 152 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView.
Referenced by GUIApplicationWindow::getBuildGLCanvas(), and GNEApplicationWindow::getBuildGLCanvas().
getColoringSchemesCombo()
FXComboBox & GUIGlChildWindow::getColoringSchemesCombo () inherited
Definition at line 170 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myColoringSchemes.
Referenced by GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), GUISUMOAbstractView::getColoringSchemesCombo(), and GUIGlChildWindow::getView().
getLocatorPopup()
FXPopup * GUIGlChildWindow::getLocatorPopup () inherited
Definition at line 164 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myLocatorPopup.
Referenced by GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), and GUIGlChildWindow::getView().
getNavigationToolBar()
FXToolBar & GUIGlChildWindow::getNavigationToolBar (GUISUMOAbstractView & v) inherited
Definition at line 158 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIGlChildWindow::getView().
getParent()
GUIMainWindow* GUIGlChildWindow::getParent () inline inherited
Returns the main window.
Returns
This view's parent
Definition at line 88 of file GUIGlChildWindow.h.
References GUIGlChildWindow::isSelected(), and GUIGlChildWindow::myParent.
Referenced by GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser().
getView()
GUISUMOAbstractView* GUIGlChildWindow::getView () const inline inherited
Definition at line 59 of file GUIGlChildWindow.h.
References GUIGlChildWindow::buildColoringToolBar(), GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::buildScreenshotToolBar(), GUIGlChildWindow::getColoringSchemesCombo(), GUIGlChildWindow::getLocatorPopup(), GUIGlChildWindow::getNavigationToolBar(), GUIGlChildWindow::myView, GUIGlChildWindow::onCmdChangeColorScheme(), GUIGlChildWindow::onCmdEditViewport(), GUIGlChildWindow::onCmdEditViewScheme(), GUIGlChildWindow::onCmdRecenterView(), GUIGlChildWindow::onCmdShowToolTips(), GUIGlChildWindow::onCmdZoomStyle(), and GUIGlChildWindow::setView().
Referenced by GUIMainWindow::getActiveView(), TraCIServerAPI_GUI::getNamedView(), GUIApplicationWindow::onCmdEditChosen(), GUIApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdShowStats(), GUIDialog_GLObjChooser::onCmdToggleSelection(), GUIApplicationWindow::openNewView(), and GNEApplicationWindow::openNewView().
init()
GUISUMOAbstractView * GUISUMOViewParent::init (FXGLCanvas * share, GUINet & net, GUISUMOViewParent::ViewType type) virtual
"Initialises" this window by building the contents
Parameters
[in] share A canvas tor get the shared context from
[in] net The network to show
[in] vt The view type to use
Todo:
Check whether this could be done in the constructor
Definition at line 109 of file GUISUMOViewParent.cpp.
References GUISUMOAbstractView::buildViewToolBars(), GUIMainWindow::getGLVisual(), GUIMainWindow::isGaming(), GUIGlChildWindow::myContentFrame, GUIGlChildWindow::myNavigationToolBar, GUIGlChildWindow::myParent, GUIGlChildWindow::myView, VIEW_2D_OPENGL, and VIEW_3D_OSG.
Referenced by GUIApplicationWindow::openNewView().
isSelected()
bool GUISUMOViewParent::isSelected (GUIGlObject * o) const virtual
true if the object is selected (may include extra logic besides calling gSelected)
Reimplemented from GUIGlChildWindow.
Definition at line 260 of file GUISUMOViewParent.cpp.
References GUIGlObject::getGlID(), MSEdge::getLanes(), GUIGlObject::getType(), GLO_EDGE, GLO_LANE, gSelected, and GUISelectedStorage::isSelected().
onCmdChangeColorScheme()
long GUIGlChildWindow::onCmdChangeColorScheme (FXObject * , FXSelector sel, void * data) inherited
Definition at line 221 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::setColorScheme().
Referenced by GUIGlChildWindow::getView().
onCmdEditViewport()
long GUIGlChildWindow::onCmdEditViewport (FXObject * , FXSelector , void *) inherited
Definition at line 184 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::showViewportEditor().
Referenced by GUIGlChildWindow::getView().
onCmdEditViewScheme()
long GUIGlChildWindow::onCmdEditViewScheme (FXObject * , FXSelector , void *) inherited
Definition at line 191 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::showViewschemeEditor().
Referenced by GUIGlChildWindow::getView().
onCmdLocate()
long GUISUMOViewParent::onCmdLocate (FXObject * , FXSelector sel, void *)
locator-callback
Definition at line 187 of file GUISUMOViewParent.cpp.
References GUIIconSubSys::getIcon(), GUIGlObject_AbstractAdd::getIDList(), GUIEdge::getIDs(), MSNet::getInstance(), MSNet::getPersonControl(), MSNet::getShapeContainer(), MSNet::getVehicleControl(), GUIGlObjectStorage::gIDStorage, GLO_ADDITIONAL, MSGlobals::gUseMesoSim, ICON_LOCATEADD, ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATEPERSON, ICON_LOCATEPOI, ICON_LOCATEPOLY, ICON_LOCATETLS, ICON_LOCATEVEHICLE, GUIMainWindow::listInternal(), GUIMainWindow::listParking(), GUIMainWindow::listTeleporting(), MID_LOCATEADD, MID_LOCATEEDGE, MID_LOCATEJUNCTION, MID_LOCATEPERSON, MID_LOCATEPOI, MID_LOCATEPOLY, MID_LOCATETLS, MID_LOCATEVEHICLE, GUIGlChildWindow::myLocatorButton, GUIGlChildWindow::myLocatorPopup, GUIGlChildWindow::myParent, and GUIDialog_GLObjChooser::show().
Referenced by GUIApplicationWindow::onCmdLocate().
onCmdMakeSnapshot()
long GUISUMOViewParent::onCmdMakeSnapshot (FXObject * sender, FXSelector , void *)
Called if the user wants to make a snapshot (screenshot)
Definition at line 145 of file GUISUMOViewParent.cpp.
References MFXCheckableButton::amChecked(), GUISUMOAbstractView::endSnapshot(), gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, GUISUMOAbstractView::makeSnapshot(), GUIGlChildWindow::myView, MFXCheckableButton::setChecked(), and MFXUtils::userPermitsOverwritingWhenFileExists().
onCmdRecenterView()
long GUIGlChildWindow::onCmdRecenterView (FXObject * , FXSelector , void *) inherited
Definition at line 176 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::recenterView().
Referenced by GUIGlChildWindow::getView().
onCmdShowToolTips()
long GUIGlChildWindow::onCmdShowToolTips (FXObject * sender, FXSelector , void *) inherited
Definition at line 198 of file GUIGlChildWindow.cpp.
References MFXCheckableButton::amChecked(), GUIGlChildWindow::myView, MFXCheckableButton::setChecked(), and GUISUMOAbstractView::showToolTips().
Referenced by GUIGlChildWindow::getView().
onCmdZoomStyle()
long GUIGlChildWindow::onCmdZoomStyle (FXObject * sender, FXSelector , void *) inherited
Definition at line 209 of file GUIGlChildWindow.cpp.
References MFXCheckableButton::amChecked(), GUIGlChildWindow::myView, and MFXCheckableButton::setChecked().
Referenced by GUIGlChildWindow::getView().
onKeyPress()
long GUISUMOViewParent::onKeyPress (FXObject * o, FXSelector sel, void * data)
handle keys
Definition at line 285 of file GUISUMOViewParent.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::onKeyPress().
Referenced by GUIApplicationWindow::onKeyPress().
onKeyRelease()
long GUISUMOViewParent::onKeyRelease (FXObject * o, FXSelector sel, void * data)
Definition at line 292 of file GUISUMOViewParent.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::onKeyRelease().
Referenced by GUIApplicationWindow::onKeyRelease().
onSimStep()
long GUISUMOViewParent::onSimStep (FXObject * sender, FXSelector , void *)
Called on a simulation step.
Definition at line 252 of file GUISUMOViewParent.cpp.
References GUISUMOAbstractView::checkSnapshots(), and GUIGlChildWindow::myView.
setToolBarVisibility()
void GUISUMOViewParent::setToolBarVisibility (const bool value)
about toggled gaming status
Definition at line 135 of file GUISUMOViewParent.cpp.
References GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIApplicationWindow::onCmdFullScreen(), and GUIApplicationWindow::onCmdGaming().
setView()
void GUIGlChildWindow::setView (GUIGlID id) inherited
Centers the view onto the given artifact.
Parameters
[in] id The id of the object to center the view on
Definition at line 228 of file GUIGlChildWindow.cpp.
References GUISUMOAbstractView::centerTo(), and GUIGlChildWindow::myView.
Referenced by GUIGlChildWindow::getView(), GUIDialog_GLObjChooser::onCmdCenter(), GUIDialog_GLObjChooser::onCmdText(), and GUIMessageWindow::setCursorPos().
Field Documentation
myColoringSchemes
FXComboBox* GUIGlChildWindow::myColoringSchemes protected inherited
Definition at line 110 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildColoringToolBar(), and GUIGlChildWindow::getColoringSchemesCombo().
myContentFrame
FXVerticalFrame* GUIGlChildWindow::myContentFrame protected inherited
Definition at line 108 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), and init().
myLocatorButton
FXMenuButton* GUIGlChildWindow::myLocatorButton protected inherited
Definition at line 106 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), onCmdLocate(), and GNEViewParent::onCmdLocate().
myLocatorPopup
FXPopup* GUIGlChildWindow::myLocatorPopup protected inherited
The locator menu.
Definition at line 105 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::create(), GUIGlChildWindow::getLocatorPopup(), onCmdLocate(), GNEViewParent::onCmdLocate(), and GUIGlChildWindow::~GUIGlChildWindow().
myNavigationToolBar
FXToolBar* GUIGlChildWindow::myNavigationToolBar protected inherited
The tool bar.
Definition at line 102 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildColoringToolBar(), GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::buildScreenshotToolBar(), GUIGlChildWindow::create(), GUIGlChildWindow::getNavigationToolBar(), init(), setToolBarVisibility(), and GUIGlChildWindow::~GUIGlChildWindow().
myParent
GUIMainWindow* GUIGlChildWindow::myParent protected inherited
The parent window.
Definition at line 113 of file GUIGlChildWindow.h.
Referenced by GNEViewParent::getApp(), GUIGlChildWindow::getParent(), init(), GNEViewParent::onCmdClose(), onCmdLocate(), GNEViewParent::~GNEViewParent(), and ~GUISUMOViewParent().
myView
GUISUMOAbstractView* GUIGlChildWindow::myView protected inherited
the view
Definition at line 99 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::create(), GUIGlChildWindow::getBuildGLCanvas(), GUIGlChildWindow::getView(), init(), GUIGlChildWindow::onCmdChangeColorScheme(), GUIGlChildWindow::onCmdEditViewport(), GUIGlChildWindow::onCmdEditViewScheme(), GNEViewParent::onCmdLocate(), onCmdMakeSnapshot(), GNEViewParent::onCmdMakeSnapshot(), GUIGlChildWindow::onCmdRecenterView(), GUIGlChildWindow::onCmdShowToolTips(), GUIGlChildWindow::onCmdZoomStyle(), onKeyPress(), GNEViewParent::onKeyPress(), onKeyRelease(), GNEViewParent::onKeyRelease(), onSimStep(), and GUIGlChildWindow::setView().
The documentation for this class was generated from the following files:
GUISUMOViewParent.h
GUISUMOViewParent.cpp