SUMO - Simulation of Urban MObility: ROJTRTurnDefLoader Class Reference
ROJTRTurnDefLoader Class Reference
Loader for the of turning percentages and source/sink definitions.
#include <ROJTRTurnDefLoader.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
ROJTRTurnDefLoader (RONet &net)
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~ROJTRTurnDefLoader ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Private Member Functions
void addToEdge (const SUMOSAXAttributes &attrs)
Parses the probability to use a certain outgoing edge.
void beginFromEdge (const SUMOSAXAttributes &attrs)
Begins the processing of a incoming edge definition.
Private Attributes
ROJTREdge * myEdge
The current incoming edge the turning probabilities are set into.
double myIntervalBegin
The begin and the end of the current interval.
double myIntervalEnd
RONet & myNet
The network to set the information into.
Detailed Description
Loader for the of turning percentages and source/sink definitions.
This handler parses XML-descriptions of jtrrouter-definitions, including percentage ratios at junctions and definitions of sink/source edges.
All read values are stored directly into the given network's structures (edges).
Definition at line 61 of file ROJTRTurnDefLoader.h.
Constructor & Destructor Documentation
ROJTRTurnDefLoader()
ROJTRTurnDefLoader::ROJTRTurnDefLoader (RONet & net)
Constructor.
Parameters
[in] net The net to add loaded turning percentages into
Definition at line 49 of file ROJTRTurnDefLoader.cpp.
~ROJTRTurnDefLoader()
ROJTRTurnDefLoader::~ROJTRTurnDefLoader ()
Destructor.
Definition at line 54 of file ROJTRTurnDefLoader.cpp.
Member Function Documentation
addToEdge()
void ROJTRTurnDefLoader::addToEdge (const SUMOSAXAttributes & attrs) private
Parses the probability to use a certain outgoing edge.
Tries to retreive the outgoing edge and then the probability to use it. If one of both operations could not be accomplished, an error is generated.
If everything is ok, this means the destination edge is defined and known and the probability is valid, too, this probability is added to "myEdge", the last parsed incoming edge. As time, the previously parsed interval begin/end is used.
Parameters
[in] attrs The SAX-attributes to parse the destination edge and the probability to use it from
Definition at line 125 of file ROJTRTurnDefLoader.cpp.
References ROJTREdge::addFollowerProbability(), SUMOSAXAttributes::get(), RONet::getEdge(), myEdge, myIntervalBegin, myIntervalEnd, myNet, SUMO_ATTR_ID, SUMO_ATTR_PROB, and WRITE_ERROR.
Referenced by myStartElement().
beginFromEdge()
void ROJTRTurnDefLoader::beginFromEdge (const SUMOSAXAttributes & attrs) private
Begins the processing of a incoming edge definition.
Tries to retrieve the currently described incoming edge. If the edge id is not given in the attributes or the edge is not known, an error is reported.
If everything is ok, the edge's address is stored in myEdge.
Parameters
[in] attrs The SAX-attributes to parse incoming edge from
Definition at line 107 of file ROJTRTurnDefLoader.cpp.
References SUMOSAXAttributes::get(), RONet::getEdge(), myEdge, myNet, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, PCLoaderOSM::EdgesHandler, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, MSCalibrator, NIXMLEdgesHandler, NIXMLNodesHandler, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, ShapeHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, and ROMARouteHandler.
Definition at line 226 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), and SUMOSAXReader::parseNext().
myStartElement()
void ROJTRTurnDefLoader::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 58 of file ROJTRTurnDefLoader.cpp.
References addToEdge(), beginFromEdge(), SUMOSAXAttributes::get(), RONet::getEdge(), SUMOSAXAttributes::hasAttribute(), myIntervalBegin, myIntervalEnd, myNet, ROEdge::setSink(), ROEdge::setSource(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGES, SUMO_ATTR_END, SUMO_TAG_FROMEDGE, SUMO_TAG_INTERVAL, SUMO_TAG_SINK, SUMO_TAG_SOURCE, SUMO_TAG_TOEDGE, and StringTokenizer::WHITECHARS.
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myEdge
ROJTREdge* ROJTRTurnDefLoader::myEdge private
The current incoming edge the turning probabilities are set into.
Definition at line 127 of file ROJTRTurnDefLoader.h.
Referenced by addToEdge(), and beginFromEdge().
myIntervalBegin
double ROJTRTurnDefLoader::myIntervalBegin private
The begin and the end of the current interval.
Definition at line 124 of file ROJTRTurnDefLoader.h.
Referenced by addToEdge(), and myStartElement().
myIntervalEnd
double ROJTRTurnDefLoader::myIntervalEnd private
Definition at line 124 of file ROJTRTurnDefLoader.h.
Referenced by addToEdge(), and myStartElement().
myNet
RONet& ROJTRTurnDefLoader::myNet private
The network to set the information into.
Definition at line 121 of file ROJTRTurnDefLoader.h.
Referenced by addToEdge(), beginFromEdge(), and myStartElement().
The documentation for this class was generated from the following files:
ROJTRTurnDefLoader.h
ROJTRTurnDefLoader.cpp