SUMO - Simulation of Urban MObility: NGNet Class Reference
NGNet Class Reference
The class storing the generated network.
#include <NGNet.h>
Public Member Functions
void add (NGNode *node)
Adds the given node to the network.
void add (NGEdge *edge)
Adds the given edge to the network.
void createChequerBoard (int numX, int numY, double spaceX, double spaceY, double attachLength, bool alphaIDs)
Creates a grid network.
void createSpiderWeb (int numRadDiv, int numCircles, double spaceRad, bool hasCenter)
Creates a spider network.
NGNode * findNode (int xPos, int yPos)
Returns the node at the given position.
std::string getNextFreeID ()
Returns the next free id.
NGNet (NBNetBuilder &nb)
Constructor.
int nodeNo () const
Returns the number of stored nodes.
double radialToX (double radius, double phi)
Returns the x-position resulting from the given radius and angle.
double radialToY (double radius, double phi)
Returns the y-position resulting from the given radius and angle.
void toNB () const
Converts the stored network into its netbuilder-representation.
~NGNet ()
Destructor.
Private Member Functions
void connect (NGNode *node1, NGNode *node2)
Connects both nodes with two edges, one for each direction.
NGNet (const NGNet &)
Invalidated copy constructor.
NGNet & operator= (const NGNet &)
Invalidated assignment operator.
Private Attributes
NGEdgeList myEdgeList
The list of links.
int myLastID
The last ID given to node or link.
NBNetBuilder & myNetBuilder
The builder used to build NB*-structures.
NGNodeList myNodeList
The list of nodes.
Detailed Description
The class storing the generated network.
An instance of this class stores both the edges and the nodes build during the generation of a network (using any type of generation algorithm). These instances are later transformed into netbuild-structures using toNB().
Definition at line 55 of file NGNet.h.
Constructor & Destructor Documentation
NGNet() [1/2]
NGNet::NGNet (NBNetBuilder & nb)
Constructor.
Definition at line 52 of file NGNet.cpp.
References myLastID.
~NGNet()
NGNet::~NGNet ()
Destructor.
Definition at line 58 of file NGNet.cpp.
References myEdgeList, and myNodeList.
NGNet() [2/2]
NGNet::NGNet (const NGNet &) private
Invalidated copy constructor.
Member Function Documentation
add() [1/2]
void NGNet::add (NGNode * node)
Adds the given node to the network.
The node is added to myNodeList.
Parameters
[in] node The node to add
Definition at line 240 of file NGNet.cpp.
References myNodeList.
Referenced by NGRandomNetBuilder::createNet(), and NGRandomNetBuilder::createNewNode().
add() [2/2]
void NGNet::add (NGEdge * edge)
Adds the given edge to the network.
The edge is added to myEdgeList.
Parameters
[in] edge The edge to add
Definition at line 246 of file NGNet.cpp.
References myEdgeList.
connect()
void NGNet::connect (NGNode * node1, NGNode * node2) private
Connects both nodes with two edges, one for each direction.
Builds one link for each direction and appends the links to myEdgeList. The name of a link is as following: <FROM_NODE_ID>to<TO_NODE_ID>.
Parameters
[in] node1 The first node to connect
[in] node2 The second node to connect
Definition at line 199 of file NGNet.cpp.
References Named::getID(), and myEdgeList.
Referenced by createChequerBoard(), and createSpiderWeb().
createChequerBoard()
void NGNet::createChequerBoard (int numX, int numY, double spaceX, double spaceY, double attachLength, bool alphaIDs)
Creates a grid network.
Performs a souble-loop over numX, then numY. Builds NGNodes at the according positions and connects them using NGNet::connect. Stores both the nodes and the edges within the internal container.
The nodes get an id using <RUNNING_X>/<RUNNING_Y>. The ids of the links are set in NGNet::connect.
Parameters
[in] numX The number of nodes in x-direction
[in] numY The number of nodes in y-direction
[in] spaceX The space between nodes in x-direction
[in] spaceY The space between nodes in y-direction
[in] attachLength The length of streets attached at the border
[in] alphaIDs Whether to use alphanumerial node ids
See also
NGNet::connect
Definition at line 86 of file NGNet.cpp.
References connect(), findNode(), myNodeList, NGNode::setX(), NGNode::setY(), and toString().
Referenced by buildNetwork().
createSpiderWeb()
void NGNet::createSpiderWeb (int numRadDiv, int numCircles, double spaceRad, bool hasCenter)
Creates a spider network.
Creates a spider web by going through all arms and then all circles in a loop. Builds the NGNodes at the positions obtained using radialToX and radialToY and connects them using NGNet::connect. Builds optionally a center node, and connects it, too.
The nodes get an id using <RUNNING_ARM_NUMBER>/<RUNNING_CIRCLE_NUMBER>. The ids of the links are set in NGNet::connect.
Parameters
[in] numRadDiv The number of arms to build
[in] numCircles The number of circles to build
[in] spaceRad The distance between the circles
[in] hasCenter Information whether a center node shall be built
See also
NGNet::connect
Todo:
consolidate the name of the center node
Definition at line 153 of file NGNet.cpp.
References connect(), findNode(), getNextFreeID(), M_PI, myNodeList, radialToX(), radialToY(), NGNode::setX(), and NGNode::setY().
Referenced by buildNetwork().
findNode()
NGNode * NGNet::findNode (int xPos, int yPos)
Returns the node at the given position.
Searches for a node with the given position within myNodeList. Returns the matching node, if one exists, or 0 otherwise.
Parameters
[in] xPos The x-position of the searched node
[in] yPos The y-position of the searched node
Returns
The node with the given position, or 0 if no such node exists
Definition at line 75 of file NGNet.cpp.
References myNodeList.
Referenced by createChequerBoard(), and createSpiderWeb().
getNextFreeID()
std::string NGNet::getNextFreeID ()
Returns the next free id.
Uses the value of myLastID to return a new (numeric) id. Increases myLastID.
Returns
A new, unique numerical id
Definition at line 69 of file NGNet.cpp.
References myLastID.
Referenced by NGRandomNetBuilder::createNet(), NGRandomNetBuilder::createNewNode(), and createSpiderWeb().
nodeNo()
int NGNet::nodeNo () const
Returns the number of stored nodes.
Returns
The number of stored nodes
Definition at line 252 of file NGNet.cpp.
References myNodeList.
Referenced by NGRandomNetBuilder::createNet().
operator=()
NGNet& NGNet::operator= (const NGNet &) private
Invalidated assignment operator.
radialToX()
double NGNet::radialToX (double radius, double phi)
Returns the x-position resulting from the given radius and angle.
Parameters
[in] radius The radius of the circle
[in] phi The angle the position is located at
Returns
The x-position at the described circle at angle phi
Definition at line 141 of file NGNet.cpp.
Referenced by createSpiderWeb().
radialToY()
double NGNet::radialToY (double radius, double phi)
Returns the y-position resulting from the given radius and angle.
Parameters
[in] radius The radius of the circle
[in] phi The angle the position is located at
Returns
The y-position at the described circle at angle phi
Definition at line 147 of file NGNet.cpp.
Referenced by createSpiderWeb().
toNB()
void NGNet::toNB () const
Converts the stored network into its netbuilder-representation.
Goes through all stored nodes, first, converts them into their netbuilder representations using NGNode::buildNBNode, and stores the built NBNodes into the net builder myNetBuilder.
Then, the method goes through all edges, converts them into their netbuilder representations using NGEdge::buildNBEdge, and stores the built NBEdges into the net builder myNetBuilder.
If one of the nodes is controlled by a tls and the built logic could not be added to net builder's storage, a ProcessError is thrown. This in fact may only happen when two same ids occur, what is not possible.
Exceptions
ProcessError If a built tls logic could not be added (should never happen)
Todo:
Check whether throwing an exception is really necessary, here
Definition at line 210 of file NGNet.cpp.
References NBNode::getConnectionTo(), NBNetBuilder::getEdgeCont(), OptionsCont::getFloat(), NBNode::getIncomingEdges(), NBNetBuilder::getNodeCont(), NBTypeCont::getNumLanes(), OptionsCont::getOptions(), NBTypeCont::getPriority(), NBTypeCont::getSpeed(), NBNetBuilder::getTypeCont(), NBTypeCont::getWidth(), NBNodeCont::insert(), NBEdgeCont::insert(), myEdgeList, myNetBuilder, myNodeList, RandHelper::rand(), and NBEdge::UNSPECIFIED_OFFSET.
Referenced by main().
Field Documentation
myEdgeList
NGEdgeList NGNet::myEdgeList private
The list of links.
Definition at line 213 of file NGNet.h.
Referenced by add(), connect(), toNB(), and ~NGNet().
myLastID
int NGNet::myLastID private
The last ID given to node or link.
Definition at line 204 of file NGNet.h.
Referenced by getNextFreeID(), and NGNet().
myNetBuilder
NBNetBuilder& NGNet::myNetBuilder private
The builder used to build NB*-structures.
Definition at line 207 of file NGNet.h.
Referenced by toNB().
myNodeList
NGNodeList NGNet::myNodeList private
The list of nodes.
Definition at line 210 of file NGNet.h.
Referenced by add(), createChequerBoard(), createSpiderWeb(), findNode(), nodeNo(), toNB(), and ~NGNet().
The documentation for this class was generated from the following files:
NGNet.h
NGNet.cpp