SUMO - Simulation of Urban MObility: IntermodalNetwork< E, L, N, V > Class Template Reference
IntermodalNetwork< E, L, N, V > Class Template Reference
the intermodal network storing edges, connections and the mappings to the "real" edges
#include <IntermodalNetwork.h>
Public Member Functions
void addConnectors (_IntermodalEdge *const depConn, _IntermodalEdge *const arrConn, const int splitIndex)
void addEdge (_IntermodalEdge *edge)
const std::vector< _IntermodalEdge * > & getAllEdges ()
_IntermodalEdge * getArrivalConnector (const E *e, const int splitIndex=0) const
Returns the arriving intermodal connector at the given split offset.
_IntermodalEdge * getArrivalEdge (const E *e, const double pos) const
Returns the arriving intermodal edge.
const EdgePair & getBothDirections (const E *e) const
Returns the pair of forward and backward edge.
_IntermodalEdge * getDepartConnector (const E *e, const int splitIndex=0) const
Returns the departing intermodal connector at the given split offset.
_IntermodalEdge * getDepartEdge (const E *e, const double pos) const
Returns the departing intermodal edge.
_IntermodalEdge * getWalkingConnector (const E *e) const
Returns the outgoing pedestrian edge, which is either a walking area or a walking connector.
IntermodalNetwork (const std::vector< E *> &edges, int numericalID=0)
~IntermodalNetwork ()
Private Types
typedef IntermodalEdge< E, L, N, V > _IntermodalEdge
typedef PedestrianEdge< E, L, N, V > _PedestrianEdge
typedef std::pair< _IntermodalEdge *, _IntermodalEdge * > EdgePair
Private Attributes
std::map< const E *, std::vector< _IntermodalEdge * > > myArrivalLookup
retrieve the arrival edges for the given input edge E
std::map< const E *, EdgePair > myBidiLookup
retrieve the forward and backward edge for the given input edge E
std::map< const E *, std::vector< _IntermodalEdge * > > myDepartLookup
retrieve the depart edges for the given input edge E
std::vector< _IntermodalEdge * > myEdges
the edge dictionary
std::map< const N *, _IntermodalEdge * > myWalkingConnectorLookup
the walking connector edge (fake walking area)
Detailed Description
template<class E, class L, class N, class V>
class IntermodalNetwork< E, L, N, V >
the intermodal network storing edges, connections and the mappings to the "real" edges
Definition at line 51 of file IntermodalNetwork.h.
Member Typedef Documentation
_IntermodalEdge
template<class E , class L , class N , class V > typedef IntermodalEdge<E, L, N, V> IntermodalNetwork< E, L, N, V >::_IntermodalEdge private
Definition at line 53 of file IntermodalNetwork.h.
_PedestrianEdge
template<class E , class L , class N , class V > typedef PedestrianEdge<E, L, N, V> IntermodalNetwork< E, L, N, V >::_PedestrianEdge private
Definition at line 54 of file IntermodalNetwork.h.
EdgePair
template<class E , class L , class N , class V > typedef std::pair<_IntermodalEdge*, _IntermodalEdge*> IntermodalNetwork< E, L, N, V >::EdgePair private
Definition at line 55 of file IntermodalNetwork.h.
Constructor & Destructor Documentation
IntermodalNetwork()
template<class E , class L , class N , class V > IntermodalNetwork< E, L, N, V >::IntermodalNetwork (const std::vector< E *> & edges, int numericalID = 0) inline
Definition at line 62 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::addConnectors(), IntermodalNetwork< E, L, N, V >::addEdge(), IntermodalEdge< E, L, N, V >::addSuccessor(), IntermodalNetwork< E, L, N, V >::getArrivalConnector(), IntermodalNetwork< E, L, N, V >::getBothDirections(), IntermodalNetwork< E, L, N, V >::getDepartConnector(), Named::getID(), IntermodalNetwork< E, L, N, V >::myArrivalLookup, IntermodalNetwork< E, L, N, V >::myBidiLookup, IntermodalNetwork< E, L, N, V >::myDepartLookup, IntermodalNetwork< E, L, N, V >::myEdges, and IntermodalNetwork< E, L, N, V >::myWalkingConnectorLookup.
~IntermodalNetwork()
template<class E , class L , class N , class V > IntermodalNetwork< E, L, N, V >::~IntermodalNetwork () inline
Definition at line 196 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myEdges.
Member Function Documentation
addConnectors()
template<class E , class L , class N , class V > void IntermodalNetwork< E, L, N, V >::addConnectors (_IntermodalEdge *const depConn, _IntermodalEdge *const arrConn, const int splitIndex) inline
Definition at line 209 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::addEdge(), IntermodalEdge< E, L, N, V >::getEdge(), IntermodalNetwork< E, L, N, V >::myArrivalLookup, and IntermodalNetwork< E, L, N, V >::myDepartLookup.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
addEdge()
template<class E , class L , class N , class V > void IntermodalNetwork< E, L, N, V >::addEdge (_IntermodalEdge * edge) inline
Definition at line 202 of file IntermodalNetwork.h.
References IntermodalEdge< E, L, N, V >::getNumericalID(), and IntermodalNetwork< E, L, N, V >::myEdges.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), IntermodalNetwork< E, L, N, V >::addConnectors(), IntermodalRouter< E, L, N, V >::addSchedule(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), and IntermodalRouter< E, L, N, V >::splitEdge().
getAllEdges()
template<class E , class L , class N , class V > const std::vector<_IntermodalEdge*>& IntermodalNetwork< E, L, N, V >::getAllEdges () inline
Definition at line 216 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myEdges.
Referenced by IntermodalRouter< E, L, N, V >::createNet(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::PedestrianRouter(), IntermodalRouter< E, L, N, V >::writeNetwork(), and IntermodalRouter< E, L, N, V >::writeWeights().
getArrivalConnector()
template<class E , class L , class N , class V > _IntermodalEdge* IntermodalNetwork< E, L, N, V >::getArrivalConnector (const E * e, const int splitIndex = 0) const inline
Returns the arriving intermodal connector at the given split offset.
Definition at line 268 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myArrivalLookup.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
getArrivalEdge()
template<class E , class L , class N , class V > _IntermodalEdge* IntermodalNetwork< E, L, N, V >::getArrivalEdge (const E * e, const double pos) const inline
Returns the arriving intermodal edge.
Definition at line 252 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myArrivalLookup.
Referenced by IntermodalRouter< E, L, N, V >::compute().
getBothDirections()
template<class E , class L , class N , class V > const EdgePair& IntermodalNetwork< E, L, N, V >::getBothDirections (const E * e) const inline
Returns the pair of forward and backward edge.
Definition at line 221 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myBidiLookup.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), IntermodalNetwork< E, L, N, V >::getWalkingConnector(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::prohibit(), and IntermodalRouter< E, L, N, V >::prohibit().
getDepartConnector()
template<class E , class L , class N , class V > _IntermodalEdge* IntermodalNetwork< E, L, N, V >::getDepartConnector (const E * e, const int splitIndex = 0) const inline
Returns the departing intermodal connector at the given split offset.
Definition at line 247 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myDepartLookup.
Referenced by IntermodalRouter< E, L, N, V >::addAccess(), IntermodalRouter< E, L, N, V >::addCarEdges(), PedestrianRouter< E, L, N, V, DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
getDepartEdge()
template<class E , class L , class N , class V > _IntermodalEdge* IntermodalNetwork< E, L, N, V >::getDepartEdge (const E * e, const double pos) const inline
Returns the departing intermodal edge.
Definition at line 231 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::myDepartLookup.
Referenced by IntermodalRouter< E, L, N, V >::compute().
getWalkingConnector()
template<class E , class L , class N , class V > _IntermodalEdge* IntermodalNetwork< E, L, N, V >::getWalkingConnector (const E * e) const inline
Returns the outgoing pedestrian edge, which is either a walking area or a walking connector.
Definition at line 273 of file IntermodalNetwork.h.
References IntermodalNetwork< E, L, N, V >::getBothDirections(), and IntermodalNetwork< E, L, N, V >::myWalkingConnectorLookup.
Referenced by IntermodalRouter< E, L, N, V >::addCarEdges().
Field Documentation
myArrivalLookup
template<class E , class L , class N , class V > std::map<const E*, std::vector<_IntermodalEdge*> > IntermodalNetwork< E, L, N, V >::myArrivalLookup private
retrieve the arrival edges for the given input edge E
Definition at line 302 of file IntermodalNetwork.h.
Referenced by IntermodalNetwork< E, L, N, V >::addConnectors(), IntermodalNetwork< E, L, N, V >::getArrivalConnector(), IntermodalNetwork< E, L, N, V >::getArrivalEdge(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
myBidiLookup
template<class E , class L , class N , class V > std::map<const E*, EdgePair> IntermodalNetwork< E, L, N, V >::myBidiLookup private
retrieve the forward and backward edge for the given input edge E
Definition at line 296 of file IntermodalNetwork.h.
Referenced by IntermodalNetwork< E, L, N, V >::getBothDirections(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
myDepartLookup
template<class E , class L , class N , class V > std::map<const E*, std::vector<_IntermodalEdge*> > IntermodalNetwork< E, L, N, V >::myDepartLookup private
retrieve the depart edges for the given input edge E
Definition at line 299 of file IntermodalNetwork.h.
Referenced by IntermodalNetwork< E, L, N, V >::addConnectors(), IntermodalNetwork< E, L, N, V >::getDepartConnector(), IntermodalNetwork< E, L, N, V >::getDepartEdge(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
myEdges
template<class E , class L , class N , class V > std::vector<_IntermodalEdge*> IntermodalNetwork< E, L, N, V >::myEdges private
the edge dictionary
Definition at line 293 of file IntermodalNetwork.h.
Referenced by IntermodalNetwork< E, L, N, V >::addEdge(), IntermodalNetwork< E, L, N, V >::getAllEdges(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), and IntermodalNetwork< E, L, N, V >::~IntermodalNetwork().
myWalkingConnectorLookup
template<class E , class L , class N , class V > std::map<const N*, _IntermodalEdge*> IntermodalNetwork< E, L, N, V >::myWalkingConnectorLookup private
the walking connector edge (fake walking area)
Definition at line 305 of file IntermodalNetwork.h.
Referenced by IntermodalNetwork< E, L, N, V >::getWalkingConnector(), and IntermodalNetwork< E, L, N, V >::IntermodalNetwork().
The documentation for this class was generated from the following file:
IntermodalNetwork.h