SUMO - Simulation of Urban MObility: GNECalibratorFlowDialog Class Reference
GNECalibratorFlowDialog Class Reference
Dialog for edit rerouter intervals.
#include <GNECalibratorFlowDialog.h>
Public Member Functions
GNECalibratorFlowDialog (GNECalibratorFlow *editedCalibratorFlowParent, bool updatingElement)
FOX-declaration.
~GNECalibratorFlowDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdSetVariable (FXObject *, FXSelector, void *)
event after change value
long onCmdSetTypeOfFlow (FXObject *radioButton, FXSelector, void *)
event after change type of flow
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNECalibratorFlowDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
void updateCalibratorFlowValues ()
update data fields
Protected Attributes
bool myCalibratorFlowValid
flag to check if current calibrator flow is valid
FXComboBox * myComboBoxRoute
TextField for Route.
FXComboBox * myComboBoxVehicleType
ComboBox for Type.
FXVerticalFrame * myContentFrame
frame for contents
GNECalibratorFlow * myEditedCalibratorFlow
interator to edited calibrator flow
SumoXMLAttr myInvalidAttr
current sumo attribute invalid
FXRadioButton * myRadioButtonPeriod
RadioButton for Period.
FXRadioButton * myRadioButtonProbability
RadioButton for Probability.
FXRadioButton * myRadioButtonVehsPerHour
RadioButton for VehsPerHour.
FXCheckButton * myRerouteCheckButton
checkButton for Reroute
FXTextField * myTextFieldArrivalLane
TextField for Arrival Lane.
FXTextField * myTextFieldArrivalPos
TextField for Arrival Pos.
FXTextField * myTextFieldArrivalPosLat
TextField for ArrivalPosLat.
FXTextField * myTextFieldArrivalSpeed
TextField for Arrival Speed.
FXTextField * myTextFieldBegin
TextField for Begin.
FXTextField * myTextFieldColor
TextField for Color.
FXTextField * myTextFieldContainerNumber
TextField for Container Number.
FXTextField * myTextFieldDepartLane
TextField for Depart Lane.
FXTextField * myTextFieldDepartPos
TextField for Depart Pos.
FXTextField * myTextFieldDepartPosLat
TextField for DepartPosLat.
FXTextField * myTextFieldDepartSpeed
TextField for Depart Speed.
FXTextField * myTextFieldEnd
TextField for End.
FXTextField * myTextFieldFlowID
TextField for flow ID.
FXTextField * myTextFieldLine
TextField for Line.
FXTextField * myTextFieldNumber
TextField for Number.
FXTextField * myTextFieldPeriod
TextField for Period.
FXTextField * myTextFieldPersonNumber
TextField for PersonNumber.
FXTextField * myTextFieldProbability
TextField for Probability.
FXTextField * myTextFieldVehsPerHour
TextField for VehsPerHour.
bool myUpdatingElement
flag to indicate if flow are being created or modified
Private Member Functions
GNECalibratorFlowDialog (const GNECalibratorFlowDialog &)=delete
Invalidated copy constructor.
GNECalibratorFlowDialog & operator= (const GNECalibratorFlowDialog &)=delete
Invalidated assignment operator.
Detailed Description
Dialog for edit rerouter intervals.
Definition at line 49 of file GNECalibratorFlowDialog.h.
Constructor & Destructor Documentation
GNECalibratorFlowDialog() [1/3]
GNECalibratorFlowDialog::GNECalibratorFlowDialog (GNECalibratorFlow * editedCalibratorFlowParent, bool updatingElement)
FOX-declaration.
constructor
Definition at line 68 of file GNECalibratorFlowDialog.cpp.
References GUIDesignAuxiliarFrame, GUIDesignCheckButtonAttribute, GUIDesignComboBox, GUIDesignComboBoxNCol, GUIDesignLabelThick, GUIDesignRadioButtonAttribute, GUIDesignTextField, GUIDesignTextFieldInt, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, GUIDesignUniformHorizontalFrame, MID_GNE_CALIBRATORDIALOG_SET_FLOWTYPE, MID_GNE_CALIBRATORDIALOG_SET_VARIABLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_VTYPE, and toString().
~GNECalibratorFlowDialog()
GNECalibratorFlowDialog::~GNECalibratorFlowDialog ()
destructor
Definition at line 179 of file GNECalibratorFlowDialog.cpp.
GNECalibratorFlowDialog() [2/3]
GNECalibratorFlowDialog::GNECalibratorFlowDialog () inline protected
FOX needs this.
Definition at line 80 of file GNECalibratorFlowDialog.h.
GNECalibratorFlowDialog() [3/3]
GNECalibratorFlowDialog::GNECalibratorFlowDialog (const GNECalibratorFlowDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNECalibratorDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), GNERerouterDialog::onCmdCancel(), GNECalibratorDialog::onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNECalibratorFlowDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 183 of file GNECalibratorFlowDialog.cpp.
References GNEAdditionalDialog::acceptChanges(), GNECalibratorFlow::getCalibratorParent(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), myCalibratorFlowValid, myEditedCalibratorFlow, myInvalidAttr, myUpdatingElement, toString(), and WRITE_WARNING.
onCmdCancel()
long GNECalibratorFlowDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 215 of file GNECalibratorFlowDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdReset()
long GNECalibratorFlowDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 225 of file GNECalibratorFlowDialog.cpp.
References GNEAdditionalDialog::resetChanges(), and updateCalibratorFlowValues().
onCmdSetTypeOfFlow()
long GNECalibratorFlowDialog::onCmdSetTypeOfFlow (FXObject * radioButton, FXSelector , void *)
event after change type of flow
Definition at line 455 of file GNECalibratorFlowDialog.cpp.
References GNECalibratorFlow::GNE_CALIBRATORFLOW_PERIOD, GNECalibratorFlow::GNE_CALIBRATORFLOW_PROBABILITY, GNECalibratorFlow::GNE_CALIBRATORFLOW_VEHSPERHOUR, myEditedCalibratorFlow, myRadioButtonPeriod, myRadioButtonProbability, myRadioButtonVehsPerHour, myTextFieldPeriod, myTextFieldProbability, myTextFieldVehsPerHour, onCmdSetVariable(), and GNECalibratorFlow::setFlowType().
Referenced by updateCalibratorFlowValues().
onCmdSetVariable()
long GNECalibratorFlowDialog::onCmdSetVariable (FXObject * , FXSelector , void *)
event after change value
Definition at line 235 of file GNECalibratorFlowDialog.cpp.
References GNECalibratorFlow::getCalibratorParent(), GNEAttributeCarrier::getID(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), GNECalibratorFlow::isValid(), myCalibratorFlowValid, myComboBoxRoute, myComboBoxVehicleType, myEditedCalibratorFlow, myInvalidAttr, myRadioButtonPeriod, myRadioButtonProbability, myRadioButtonVehsPerHour, myRerouteCheckButton, myTextFieldArrivalLane, myTextFieldArrivalPos, myTextFieldArrivalPosLat, myTextFieldArrivalSpeed, myTextFieldBegin, myTextFieldColor, myTextFieldContainerNumber, myTextFieldDepartLane, myTextFieldDepartPos, myTextFieldDepartPosLat, myTextFieldDepartSpeed, myTextFieldEnd, myTextFieldFlowID, myTextFieldLine, myTextFieldNumber, myTextFieldPeriod, myTextFieldPersonNumber, myTextFieldProbability, myTextFieldVehsPerHour, GNECalibratorFlow::setAttribute(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NOTHING, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, and SUMO_ATTR_VEHSPERHOUR.
Referenced by onCmdSetTypeOfFlow().
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNECalibratorFlowDialog& GNECalibratorFlowDialog::operator= (const GNECalibratorFlowDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), GNERerouterDialog::onCmdReset(), GNECalibratorDialog::onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
updateCalibratorFlowValues()
void GNECalibratorFlowDialog::updateCalibratorFlowValues () protected
update data fields
Definition at line 496 of file GNECalibratorFlowDialog.cpp.
References GNECalibratorFlow::getAttribute(), GNECalibratorFlow::getFlowType(), GNECalibratorFlow::GNE_CALIBRATORFLOW_PERIOD, GNECalibratorFlow::GNE_CALIBRATORFLOW_PROBABILITY, GNECalibratorFlow::GNE_CALIBRATORFLOW_VEHSPERHOUR, myComboBoxRoute, myComboBoxVehicleType, myEditedCalibratorFlow, myRadioButtonPeriod, myRadioButtonProbability, myRadioButtonVehsPerHour, myRerouteCheckButton, myTextFieldArrivalLane, myTextFieldArrivalPos, myTextFieldArrivalPosLat, myTextFieldArrivalSpeed, myTextFieldBegin, myTextFieldColor, myTextFieldContainerNumber, myTextFieldDepartLane, myTextFieldDepartPos, myTextFieldDepartPosLat, myTextFieldDepartSpeed, myTextFieldEnd, myTextFieldFlowID, myTextFieldLine, myTextFieldNumber, myTextFieldPeriod, myTextFieldPersonNumber, myTextFieldProbability, myTextFieldVehsPerHour, onCmdSetTypeOfFlow(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, and SUMO_ATTR_VEHSPERHOUR.
Referenced by onCmdReset().
Field Documentation
myCalibratorFlowValid
bool GNECalibratorFlowDialog::myCalibratorFlowValid protected
flag to check if current calibrator flow is valid
Definition at line 89 of file GNECalibratorFlowDialog.h.
Referenced by onCmdAccept(), and onCmdSetVariable().
myComboBoxRoute
FXComboBox* GNECalibratorFlowDialog::myComboBoxRoute protected
TextField for Route.
Definition at line 101 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myComboBoxVehicleType
FXComboBox* GNECalibratorFlowDialog::myComboBoxVehicleType protected
ComboBox for Type.
Definition at line 98 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myEditedCalibratorFlow
GNECalibratorFlow* GNECalibratorFlowDialog::myEditedCalibratorFlow protected
interator to edited calibrator flow
Definition at line 83 of file GNECalibratorFlowDialog.h.
Referenced by onCmdAccept(), onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myInvalidAttr
SumoXMLAttr GNECalibratorFlowDialog::myInvalidAttr protected
current sumo attribute invalid
Definition at line 92 of file GNECalibratorFlowDialog.h.
Referenced by onCmdAccept(), and onCmdSetVariable().
myRadioButtonPeriod
FXRadioButton* GNECalibratorFlowDialog::myRadioButtonPeriod protected
RadioButton for Period.
Definition at line 158 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myRadioButtonProbability
FXRadioButton* GNECalibratorFlowDialog::myRadioButtonProbability protected
RadioButton for Probability.
Definition at line 164 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myRadioButtonVehsPerHour
FXRadioButton* GNECalibratorFlowDialog::myRadioButtonVehsPerHour protected
RadioButton for VehsPerHour.
Definition at line 152 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myRerouteCheckButton
FXCheckButton* GNECalibratorFlowDialog::myRerouteCheckButton protected
checkButton for Reroute
Definition at line 134 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldArrivalLane
FXTextField* GNECalibratorFlowDialog::myTextFieldArrivalLane protected
TextField for Arrival Lane.
Definition at line 116 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldArrivalPos
FXTextField* GNECalibratorFlowDialog::myTextFieldArrivalPos protected
TextField for Arrival Pos.
Definition at line 119 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldArrivalPosLat
FXTextField* GNECalibratorFlowDialog::myTextFieldArrivalPosLat protected
TextField for ArrivalPosLat.
Definition at line 140 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldArrivalSpeed
FXTextField* GNECalibratorFlowDialog::myTextFieldArrivalSpeed protected
TextField for Arrival Speed.
Definition at line 122 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldBegin
FXTextField* GNECalibratorFlowDialog::myTextFieldBegin protected
TextField for Begin.
Definition at line 143 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldColor
FXTextField* GNECalibratorFlowDialog::myTextFieldColor protected
TextField for Color.
Definition at line 104 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldContainerNumber
FXTextField* GNECalibratorFlowDialog::myTextFieldContainerNumber protected
TextField for Container Number.
Definition at line 131 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldDepartLane
FXTextField* GNECalibratorFlowDialog::myTextFieldDepartLane protected
TextField for Depart Lane.
Definition at line 107 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldDepartPos
FXTextField* GNECalibratorFlowDialog::myTextFieldDepartPos protected
TextField for Depart Pos.
Definition at line 110 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldDepartPosLat
FXTextField* GNECalibratorFlowDialog::myTextFieldDepartPosLat protected
TextField for DepartPosLat.
Definition at line 137 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldDepartSpeed
FXTextField* GNECalibratorFlowDialog::myTextFieldDepartSpeed protected
TextField for Depart Speed.
Definition at line 113 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldEnd
FXTextField* GNECalibratorFlowDialog::myTextFieldEnd protected
TextField for End.
Definition at line 146 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldFlowID
FXTextField* GNECalibratorFlowDialog::myTextFieldFlowID protected
TextField for flow ID.
Definition at line 95 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldLine
FXTextField* GNECalibratorFlowDialog::myTextFieldLine protected
TextField for Line.
Definition at line 125 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldNumber
FXTextField* GNECalibratorFlowDialog::myTextFieldNumber protected
TextField for Number.
Definition at line 149 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldPeriod
FXTextField* GNECalibratorFlowDialog::myTextFieldPeriod protected
TextField for Period.
Definition at line 161 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldPersonNumber
FXTextField* GNECalibratorFlowDialog::myTextFieldPersonNumber protected
TextField for PersonNumber.
Definition at line 128 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldProbability
FXTextField* GNECalibratorFlowDialog::myTextFieldProbability protected
TextField for Probability.
Definition at line 167 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myTextFieldVehsPerHour
FXTextField* GNECalibratorFlowDialog::myTextFieldVehsPerHour protected
TextField for VehsPerHour.
Definition at line 155 of file GNECalibratorFlowDialog.h.
Referenced by onCmdSetTypeOfFlow(), onCmdSetVariable(), and updateCalibratorFlowValues().
myUpdatingElement
bool GNECalibratorFlowDialog::myUpdatingElement protected
flag to indicate if flow are being created or modified
Definition at line 86 of file GNECalibratorFlowDialog.h.
Referenced by onCmdAccept().
The documentation for this class was generated from the following files:
GNECalibratorFlowDialog.h
GNECalibratorFlowDialog.cpp