SUMO - Simulation of Urban MObility: activitygen_main.cpp File Reference
activitygen_main.cpp File Reference
#include <config.h>
#include <iostream>
#include <exception>
#include <typeinfo>
#include <router/RONet.h>
#include <router/ROLoader.h>
#include <router/RONetHandler.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/common/FileHelpers.h>
#include <utils/common/RandHelper.h>
#include <utils/common/SystemFrame.h>
#include <utils/options/OptionsCont.h>
#include <utils/iodevices/OutputDevice.h>
#include "AGFrame.h"
#include "AGActivityGen.h"
#include "city/AGTime.h"
Functions
void loadNet (RONet &toFill, ROAbstractEdgeBuilder &eb)
Loads the network.
int main (int argc, char *argv[])
Detailed Description
Author
Piotr Woznica
Walter Bamberger
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Tue, 20 Jul 2010
Version
$Id$
Definition in file activitygen_main.cpp.
Function Documentation
loadNet()
void loadNet (RONet & toFill, ROAbstractEdgeBuilder & eb)
Loads the network.
Definition at line 68 of file activitygen_main.cpp.
References deprecatedVehicleClassesSeen, OptionsCont::getOptions(), OptionsCont::getString(), FileHelpers::isReadable(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, XMLSubSys::runParser(), GenericSAXHandler::setFileName(), toString(), and WRITE_WARNING.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 94 of file activitygen_main.cpp.
References OptionsCont::addCopyrightNotice(), SystemFrame::close(), OutputDevice::createDeviceByOption(), AGFrame::fillOptions(), OptionsCont::getBool(), OutputDevice::getDevice(), RONet::getEdgeNumber(), MsgHandler::getErrorInstance(), OptionsCont::getInt(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), loadNet(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), toString(), VERSION_STRING, WRITE_ERROR, and WRITE_MESSAGE.
Referenced by GUIMessageWindow::setCursorPos().