SUMO - Simulation of Urban MObility: MSE2Collector Class Reference
MSE2Collector Class Reference
An areal detector corresponding to a sequence of consecutive lanes.
#include <MSE2Collector.h>
Data Structures
struct JamInfo
Internal representation of a jam.
struct MoveNotificationInfo
Values collected in notifyMove and needed in detectorUpdate() to calculate the accumulated quantities for the detector. These are temporarily stored in myMoveNotifications for each step.
struct VehicleInfo
A VehicleInfo stores values that are tracked for the individual vehicles on the detector, e.g., accumulated timeloss. These infos are stored in myVehicles. If a vehicle leaves the detector (may it be temporarily), the entry in myVehicles is discarded, i.e. all information on the vehicle is reset.
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
typedef std::map< std::string, VehicleInfo * > VehicleInfoMap
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const std::string & getDescription () const
double getEndPos () const
Returns the end position of the detector.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
std::vector< MSLane * > getLanes ()
Returns a vector containing pointers to the lanes covered by the detector ordered from its first to its last lane.
MSLane * getLastLane () const
Returns the id of the detector's last lane.
double getLength () const
Returns the length of the detector.
double getStartPos () const
Returns the begin position of the detector.
virtual DetectorUsage getUsageType () const
Returns the detector's usage type.
MSE2Collector (const std::string &id, DetectorUsage usage, MSLane *lane, double startPos, double endPos, double length, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string &vTypes)
Constructor with given end position and detector length.
MSE2Collector (const std::string &id, DetectorUsage usage, std::vector< MSLane *> lanes, double startPos, double endPos, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string &vTypes)
Constructor with a sequence of lanes and given start and end position on the first and last lanes.
virtual void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane)
Internal notification about the vehicle moves.
virtual void reset ()
Resets all values.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
virtual ~MSE2Collector ()
Destructor.
Methods inherited from MSMoveReminder
virtual bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Adds/removes vehicles from the list of vehicles to regard.
virtual bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Removes a known vehicle due to its lane-change.
virtual bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason, const MSLane *enteredLane)
Adds the vehicle to known vehicles if not beyond the dector.
Methods inherited from MSDetectorFileOutput.
virtual void detectorUpdate (const SUMOTime step)
Computes the detector values in each time step.
virtual void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Write the generated output to the given device.
virtual void writeXMLDetectorProlog (OutputDevice &dev) const
Open the XML-output.
Methods returning current values
int getCurrentVehicleNumber () const
Returns the number of vehicles currently on the detector.
double getCurrentOccupancy () const
Returns the current detector occupancy.
double getCurrentMeanSpeed () const
Returns the mean vehicle speed of vehicles currently on the detector.
double getCurrentMeanLength () const
Returns the mean vehicle length of vehicles currently on the detector.
int getCurrentJamNumber () const
Returns the current number of jams.
int getCurrentMaxJamLengthInVehicles () const
Returns the length in vehicles of the currently largest jam.
double getCurrentMaxJamLengthInMeters () const
Returns the length in meters of the currently largest jam.
int getCurrentJamLengthInVehicles () const
Returns the length of all jams in vehicles.
double getCurrentJamLengthInMeters () const
Returns the length of all jams in meters.
int getCurrentStartedHalts () const
Returns the length of all jams in meters.
int getCurrentHaltingNumber () const
Returns the number of current haltings within the area.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the IDs of the vehicles within the area.
std::vector< VehicleInfo * > getCurrentVehicles () const
Returns the VehicleInfos for the vehicles currently on the detector.
int getPassedVeh ()
Returns the number of vehicles passed over the sensor (i.e. entered the sensor)
void subtractPassedVeh (int passed)
Subtract the number of vehicles indicated from passed from the sensor count.
Estimation methods
TODO: Need documentation, used for tls control in MSSOTLE2Sensors (->Daniel?)
int getEstimatedCurrentVehicleNumber (double speedThreshold) const
Returns an estimate of the number of vehicles currently on the detector.
double getEstimateQueueLength () const
Returns an estimate of the lenght of the queue of vehicles currently stopped on the detector.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
void addDetectorToLanes (std::vector< MSLane *> &lanes)
This adds the detector as a MoveReminder to the associated lanes.
void aggregateOutputValues ()
Aggregates and normalize some values for the detector output during detectorUpdate()
void buildJam (bool isInJam, std::vector< MoveNotificationInfo *>::const_iterator mni, JamInfo *&currentJam, std::vector< JamInfo *> &jams)
Either adds the vehicle to the end of an existing jam, or closes the last jam, and/or creates a new jam.
void calculateTimeLossAndTimeOnDetector (const SUMOVehicle &veh, double oldPos, double newPos, const VehicleInfo &vi, double &timeOnDetector, double &timeLoss) const
Calculates the time spent on the detector in the last step and the timeloss suffered in the last step for the given vehicle.
bool checkJam (std::vector< MoveNotificationInfo *>::const_iterator mni, std::map< std::string, SUMOTime > &haltingVehicles, std::map< std::string, SUMOTime > &intervalHaltingVehicles)
checks whether the vehicle stands in a jam
void checkPositioning (bool posGiven=false, double desiredLength=0.)
Adjusts positioning if the detector length is less than POSITION_EPS and tests some assertions.
void initAuxiliaries (std::vector< MSLane *> &lanes)
Checks integrity of myLanes, adds internal-lane information, inits myLength, myFirstLane, myLastLane, myOffsets Called once at construction. myLanes should form a continuous sequence.
void integrateMoveNotification (VehicleInfo *vi, const MoveNotificationInfo *mni)
This updates the detector values and the VehicleInfo of a vehicle on the detector with the given MoveNotificationInfo generated by the vehicle during the last time step.
MoveNotificationInfo * makeMoveNotification (const SUMOVehicle &veh, double oldPos, double newPos, double newSpeed, const VehicleInfo &vehInfo) const
Creates and returns a MoveNotificationInfo containing detector specific information on the vehicle's last movement.
VehicleInfo * makeVehicleInfo (const SUMOVehicle &veh, const MSLane *enteredLane) const
Creates and returns a VehicleInfo (called at the vehicle's entry)
MSE2Collector (const MSE2Collector &)
Invalidated copy constructor.
MSE2Collector & operator= (const MSE2Collector &)
Invalidated assignment operator.
void processJams (std::vector< JamInfo *> &jams, JamInfo *currentJam)
Calculates aggregated values from the given jam structure, deletes all jam-pointers.
void recalculateDetectorLength ()
Updates the detector length after myStartPos and myEndPos have been modified.
std::vector< MSLane * > selectLanes (MSLane *endLane, double length, std::string dir)
This is called if no lane sequence is given to the constructor. Builds myLanes from the given information. Also inits startPos (case dir=="bw") / endPos (case dir=="fw"). Selects lanes heuristically if no unambiguous continuation exists.
Static Private Member Functions
static double calculateSegmentTimeLoss (double timespan, double initialSpeed, double accel, double vmax)
Calculates the time loss for a segment with constant vmax.
static bool compareMoveNotification (MoveNotificationInfo *mni1, MoveNotificationInfo *mni2)
static double snap (double value, double snapPoint, double snapDist)
Snaps value to snpPoint if they are closer than snapDist.
Private Attributes
DetectorUsage myUsage
Information about how this detector is used.
Detector parameter
The detector's lane sequence
std::vector< std::string > myLanes
std::vector< double > myOffsets
The distances of the lane-beginnings from the detector start-point.
MSLane * myFirstLane
The first lane of the detector's lane sequence.
MSLane * myLastLane
The last lane of the detector's lane sequence.
double myStartPos
The position the detector starts at on the first lane.
double myEndPos
The position the detector ends at on the last lane.
double myDetectorLength
The total detector length.
double myJamHaltingSpeedThreshold
A vehicle must driver slower than this to be counted as a part of a jam.
SUMOTime myJamHaltingTimeThreshold
A vehicle must be that long beyond myJamHaltingSpeedThreshold to be counted as a part of a jam.
double myJamDistanceThreshold
Two standing vehicles must be closer than this to be counted into the same jam.
Container
List of informations about the vehicles currently on the detector
VehicleInfoMap myVehicleInfos
std::vector< MoveNotificationInfo * > myMoveNotifications
Temporal storage for notifications from vehicles that did call the detector's notifyMove() in the last time step.
std::set< std::string > myLeftVehicles
Keep track of vehicles that left the detector by a regular move along a junction (not lanechange, teleport, etc.) and should be removed from myVehicleInfos after taking into account their movement. Non-longitudinal exits are processed immediately in notifyLeave()
std::map< std::string, SUMOTime > myHaltingVehicleDurations
Storage for halting durations of known vehicles (for halting vehicles)
std::map< std::string, SUMOTime > myIntervalHaltingVehicleDurations
Storage for halting durations of known vehicles (current interval)
std::vector< SUMOTime > myPastStandingDurations
Halting durations of ended halts [s].
std::vector< SUMOTime > myPastIntervalStandingDurations
Halting durations of ended halts for the current interval [s].
Values generated for aggregated file output
The number of collected samples [time x vehicle] since the last reset
double myVehicleSamples
double myTotalTimeLoss
The total amount of all time losses [time x vehicle] since the last reset.
double mySpeedSum
The sum of collected vehicle speeds [m/s].
double myStartedHalts
The number of started halts [#].
double myJamLengthInMetersSum
The sum of jam lengths [m].
int myJamLengthInVehiclesSum
The sum of jam lengths [#veh].
int myTimeSamples
The current aggregation duration [#steps].
double myOccupancySum
The sum of occupancies [%].
double myMaxOccupancy
The maximum occupancy [%].
int myMeanMaxJamInVehicles
The mean jam length [#veh].
double myMeanMaxJamInMeters
The mean jam length [m].
int myMaxJamInVehicles
The max jam length [#veh].
double myMaxJamInMeters
The max jam length [m].
int myMeanVehicleNumber
The mean number of vehicles [#veh].
Values generated describing the current state
The number of vehicles, which have entered the detector since the last reset
int myNumberOfEnteredVehicles
int myNumberOfSeenVehicles
The number of vehicles, present on the detector at the last reset.
int myNumberOfLeftVehicles
The number of vehicles, which have left the detector since the last reset.
int myMaxVehicleNumber
The maximal number of vehicles located on the detector simultaneously since the last reset.
double myCurrentOccupancy
The current occupancy.
double myCurrentMeanSpeed
The current mean speed.
double myCurrentMeanLength
The current mean length.
int myCurrentJamNo
The current jam number.
double myCurrentMaxJamLengthInMeters
the current maximum jam length in meters
int myCurrentMaxJamLengthInVehicles
The current maximum jam length in vehicles.
double myCurrentJamLengthInMeters
The overall jam length in meters.
int myCurrentJamLengthInVehicles
The overall jam length in vehicles.
int myCurrentStartedHalts
The number of started halts in the last step.
int myCurrentHaltingsNumber
The number of halted vehicles [#].
Virtual methods to implement by derived classes
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
bool vehicleApplies (const SUMOVehicle &veh) const
Checks whether the detector measures vehicles of the given type.
bool isTyped () const
Checks whether the detector is type specific.
std::set< std::string > myVehicleTypes
The vehicle types to look for (empty means all)
Detailed Description
An areal detector corresponding to a sequence of consecutive lanes.
This detector traces vehicles which are on a sequence of consecutive lanes. A vehicle that enters the detector is stored and the stored vehicles' speeds are used within each timestep to compute the detector values. As soon as the vehicle leaves the detector, it is no longer tracked.
Determining entering and leaving vehicles is done via the MSMoveReminder interface. The values are computed by an event-callback (at the end of a time step).
Note
As soon as a vehicle enters the detector, a VehicleInfo object is created and stored in myVehicleInfos. This is constantly updated as long as the vehicle stays on the detector (i.e. calls notifyMove()). All movement notifications sent by vehicles on the detector are temporarily stored in myMoveNotifications, see notifyMove(). Finally they are integrated into myVehicleInfos when updateDetector is called.
When subclassing this detector, it is probably sufficient to adapt the definition of the structs VehicleInfo and the MoveNotification, as well as the methods that define and create those structs, i.e., makeVehicleInfo() and makeMoveNotification(). Further the integration of new movement notifications of the last time step into the vehicle infos is done in updateVehicleInfos().
Definition at line 86 of file MSE2Collector.h.
Member Typedef Documentation
VehicleInfoMap
typedef std::map<std::string, VehicleInfo*> MSE2Collector::VehicleInfoMap
Definition at line 158 of file MSE2Collector.h.
Member Enumeration Documentation
Notification
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSE2Collector() [1/3]
MSE2Collector::MSE2Collector (const std::string & id, DetectorUsage usage, MSLane * lane, double startPos, double endPos, double length, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string & vTypes)
Constructor with given end position and detector length.
Parameters
[in] id The detector's unique id.
[in] usage Information how the detector is used
[in] lane The lane the detector ends
[in] startPos The start position on the lane the detector is placed at
[in] endPos The end position on the lane the detector is placed at
[in] length The length the detector has (heuristic lane selection is done if the continuation is not unique)
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
[in] vTypes Vehicle types, that the detector takes into account
Note
Exactly one of the arguments startPos, endPos and length should be invalid (i.e. equal to std::numeric_limits<double>::max()). If length is invalid, it is required that 0 <= startPos < endPos <= lane->length If endPos is invalid, the detector may span over several lanes downstream of the lane If pos is invalid, the detector may span over several lanes upstream of the lane
Definition at line 63 of file MSE2Collector.cpp.
References addDetectorToLanes(), checkPositioning(), Named::getID(), MSLane::getLength(), initAuxiliaries(), myEndPos, myStartPos, POSITION_EPS, reset(), selectLanes(), snap(), and WRITE_WARNING.
MSE2Collector() [2/3]
MSE2Collector::MSE2Collector (const std::string & id, DetectorUsage usage, std::vector< MSLane *> lanes, double startPos, double endPos, SUMOTime haltingTimeThreshold, double haltingSpeedThreshold, double jamDistThreshold, const std::string & vTypes)
Constructor with a sequence of lanes and given start and end position on the first and last lanes.
Parameters
[in] id The detector's unique id.
[in] usage Information how the detector is used
[in] lanes A sequence of lanes the detector covers (must form a continuous piece)
[in] startPos The position of the detector start on the first lane the detector is placed at
[in] endPos The position of the detector end on the last lane the detector is placed at
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
[in] vTypes Vehicle types, that the detector takes into account
Definition at line 147 of file MSE2Collector.cpp.
References addDetectorToLanes(), checkPositioning(), Named::getID(), initAuxiliaries(), myEndPos, myFirstLane, myLastLane, myStartPos, POSITION_EPS, and reset().
~MSE2Collector()
MSE2Collector::~MSE2Collector () virtual
Destructor.
Definition at line 292 of file MSE2Collector.cpp.
References myMoveNotifications, and myVehicleInfos.
MSE2Collector() [3/3]
MSE2Collector::MSE2Collector (const MSE2Collector &) private
Invalidated copy constructor.
Member Function Documentation
addDetectorToLanes()
void MSE2Collector::addDetectorToLanes (std::vector< MSLane *> & lanes) private
This adds the detector as a MoveReminder to the associated lanes.
Definition at line 412 of file MSE2Collector.cpp.
References Named::myID.
Referenced by MSE2Collector(), and subtractPassedVeh().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
aggregateOutputValues()
void MSE2Collector::aggregateOutputValues () private
Aggregates and normalize some values for the detector output during detectorUpdate()
Definition at line 847 of file MSE2Collector.cpp.
References MAX2(), myCurrentMaxJamLengthInMeters, myCurrentMaxJamLengthInVehicles, myCurrentMeanLength, myCurrentMeanSpeed, myCurrentOccupancy, myDetectorLength, myMaxJamInMeters, myMaxJamInVehicles, myMaxOccupancy, myMaxVehicleNumber, myMeanMaxJamInMeters, myMeanMaxJamInVehicles, myMeanVehicleNumber, myMoveNotifications, myOccupancySum, and myTimeSamples.
Referenced by detectorUpdate(), and subtractPassedVeh().
buildDetectorGUIRepresentation()
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () inline virtual inherited
Builds the graphical representation.
Meant to be overridden by graphical versions of the detectors
Returns
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUIE2Collector, GUIInductLoop, GUIE3Collector, GUIInstantInductLoop, and GUIMEInductLoop.
Definition at line 135 of file MSDetectorFileOutput.h.
buildJam()
void MSE2Collector::buildJam (bool isInJam, std::vector< MoveNotificationInfo *>::const_iterator mni, JamInfo *& currentJam, std::vector< JamInfo *> & jams) private
Either adds the vehicle to the end of an existing jam, or closes the last jam, and/or creates a new jam.
Parameters
isInJam
mni
Definition at line 945 of file MSE2Collector.cpp.
References MSE2Collector::MoveNotificationInfo::distToDetectorEnd, MSE2Collector::JamInfo::firstStandingVehicle, MSE2Collector::JamInfo::lastStandingVehicle, myJamDistanceThreshold, and SIMTIME.
Referenced by detectorUpdate(), and subtractPassedVeh().
calculateSegmentTimeLoss()
static double MSE2Collector::calculateSegmentTimeLoss (double timespan, double initialSpeed, double accel, double vmax) static private
Calculates the time loss for a segment with constant vmax.
Parameters
timespan time needed to cover the segment
initialSpeed speed at segment entry
accel constant acceleration assumed during movement on the segment
vmax Maximal possible speed for the considered vehicle on the segment
Returns
Time loss (== MAX(timespan*(vmax - (initialSpeed + accel/2))/vmax), 0)
Referenced by subtractPassedVeh().
calculateTimeLossAndTimeOnDetector()
void MSE2Collector::calculateTimeLossAndTimeOnDetector (const SUMOVehicle & veh, double oldPos, double newPos, const VehicleInfo & vi, double & timeOnDetector, double & timeLoss) const private
Calculates the time spent on the detector in the last step and the timeloss suffered in the last step for the given vehicle.
Parameters
[in] veh Vehicle for which the values are to be calculated
[in] oldPos Last position (before the last timestep) of the vehicle relative to the beginning of its entry lane
[in] newPos Current position of the vehicle
[in] vi VehicleInfo corresponding to the vehicle
Definition at line 1090 of file MSE2Collector.cpp.
References MSE2Collector::VehicleInfo::entryOffset, MSE2Collector::VehicleInfo::exitOffset, SUMOVehicle::getID(), SUMOVehicle::getLane(), SUMOVehicle::getPreviousSpeed(), SUMOVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSE2Collector::VehicleInfo::id, MSE2Collector::VehicleInfo::length, MAX2(), MIN2(), NUMERICAL_EPS, MSCFModel::passingTime(), SIMTIME, MSCFModel::speedAfterTime(), and TS.
Referenced by makeMoveNotification(), and subtractPassedVeh().
checkJam()
bool MSE2Collector::checkJam (std::vector< MoveNotificationInfo *>::const_iterator mni, std::map< std::string, SUMOTime > & haltingVehicles, std::map< std::string, SUMOTime > & intervalHaltingVehicles) private
checks whether the vehicle stands in a jam
Parameters
[in] mni
Definition at line 992 of file MSE2Collector.cpp.
References DELTA_T, myCurrentHaltingsNumber, myCurrentStartedHalts, myHaltingVehicleDurations, myIntervalHaltingVehicleDurations, myJamHaltingSpeedThreshold, myJamHaltingTimeThreshold, myPastIntervalStandingDurations, myPastStandingDurations, myStartedHalts, and SIMTIME.
Referenced by detectorUpdate(), and subtractPassedVeh().
checkPositioning()
void MSE2Collector::checkPositioning (bool posGiven = false, double desiredLength = 0.) private
Adjusts positioning if the detector length is less than POSITION_EPS and tests some assertions.
Definition at line 200 of file MSE2Collector.cpp.
References Named::getID(), getLength(), MSLane::getLength(), MAX2(), MIN2(), myDetectorLength, myEndPos, myFirstLane, myLastLane, myStartPos, NUMERICAL_EPS, POSITION_EPS, recalculateDetectorLength(), snap(), toString(), and WRITE_WARNING.
Referenced by MSE2Collector(), and subtractPassedVeh().
compareMoveNotification()
static bool MSE2Collector::compareMoveNotification (MoveNotificationInfo * mni1, MoveNotificationInfo * mni2) inline static private
brief returns true if the vehicle corresponding to mni1 is closer to the detector end than the vehicle corresponding to mni2
Definition at line 644 of file MSE2Collector.h.
References MSE2Collector::MoveNotificationInfo::distToDetectorEnd.
Referenced by detectorUpdate().
detectorUpdate()
void MSE2Collector::detectorUpdate (const SUMOTime step) virtual
Computes the detector values in each time step.
This method should be called at the end of a simulation step, when all vehicles have moved. The current values are computed and summed up with the previous.
Parameters
[in] currentTime The current simulation time
Reimplemented from MSDetectorFileOutput.
Definition at line 754 of file MSE2Collector.cpp.
References aggregateOutputValues(), buildJam(), checkJam(), compareMoveNotification(), integrateMoveNotification(), myCurrentHaltingsNumber, myCurrentMeanLength, myCurrentMeanSpeed, myCurrentStartedHalts, myHaltingVehicleDurations, Named::myID, myIntervalHaltingVehicleDurations, myLeftVehicles, myMoveNotifications, myNumberOfEnteredVehicles, myNumberOfLeftVehicles, myNumberOfSeenVehicles, myVehicleInfos, processJams(), and SIMTIME.
Referenced by getUsageType().
getCurrentHaltingNumber()
int MSE2Collector::getCurrentHaltingNumber () const inline
Returns the number of current haltings within the area.
If no vehicle is within the area, 0 is returned.
Returns
The mean number of haltings within the area
Definition at line 475 of file MSE2Collector.h.
References getCurrentVehicleIDs(), getCurrentVehicles(), and myCurrentHaltingsNumber.
Referenced by libsumo::LaneArea::getLastStepHaltingNumber().
getCurrentJamLengthInMeters()
double MSE2Collector::getCurrentJamLengthInMeters () const inline
Returns the length of all jams in meters.
Definition at line 460 of file MSE2Collector.h.
References myCurrentJamLengthInMeters.
Referenced by libsumo::LaneArea::getJamLengthMeters(), and GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentJamLengthInVehicles()
int MSE2Collector::getCurrentJamLengthInVehicles () const inline
Returns the length of all jams in vehicles.
Definition at line 455 of file MSE2Collector.h.
References myCurrentJamLengthInVehicles.
Referenced by libsumo::LaneArea::getJamLengthVehicle(), and GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentJamNumber()
int MSE2Collector::getCurrentJamNumber () const inline
Returns the current number of jams.
Definition at line 440 of file MSE2Collector.h.
References myCurrentJamNo.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentMaxJamLengthInMeters()
double MSE2Collector::getCurrentMaxJamLengthInMeters () const inline
Returns the length in meters of the currently largest jam.
Definition at line 450 of file MSE2Collector.h.
References myCurrentMaxJamLengthInMeters.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentMaxJamLengthInVehicles()
int MSE2Collector::getCurrentMaxJamLengthInVehicles () const inline
Returns the length in vehicles of the currently largest jam.
Definition at line 445 of file MSE2Collector.h.
References myCurrentMaxJamLengthInVehicles.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentMeanLength()
double MSE2Collector::getCurrentMeanLength () const inline
Returns the mean vehicle length of vehicles currently on the detector.
Definition at line 435 of file MSE2Collector.h.
References myCurrentMeanLength.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentMeanSpeed()
double MSE2Collector::getCurrentMeanSpeed () const inline
Returns the mean vehicle speed of vehicles currently on the detector.
Definition at line 430 of file MSE2Collector.h.
References myCurrentMeanSpeed.
Referenced by libsumo::LaneArea::getLastStepMeanSpeed(), GUIE2Collector::MyWrapper::getParameterWindow(), and MSSOTLE2Sensors::meanVehiclesSpeed().
getCurrentOccupancy()
double MSE2Collector::getCurrentOccupancy () const inline
Returns the current detector occupancy.
Definition at line 425 of file MSE2Collector.h.
References myCurrentOccupancy.
Referenced by libsumo::LaneArea::getLastStepOccupancy(), and GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentStartedHalts()
int MSE2Collector::getCurrentStartedHalts () const inline
Returns the length of all jams in meters.
Definition at line 465 of file MSE2Collector.h.
References myCurrentStartedHalts.
Referenced by GUIE2Collector::MyWrapper::getParameterWindow().
getCurrentVehicleIDs()
std::vector< std::string > MSE2Collector::getCurrentVehicleIDs () const
Returns the IDs of the vehicles within the area.
Returns
The IDs of the vehicles that have passed the entry, but not yet an exit point
Definition at line 1276 of file MSE2Collector.cpp.
References myVehicleInfos.
Referenced by getCurrentHaltingNumber(), and libsumo::LaneArea::getLastStepVehicleIDs().
getCurrentVehicleNumber()
int MSE2Collector::getCurrentVehicleNumber () const
Returns the number of vehicles currently on the detector.
Definition at line 1263 of file MSE2Collector.cpp.
References myVehicleInfos.
Referenced by MSSOTLE2Sensors::count(), getLastLane(), libsumo::LaneArea::getLastStepVehicleNumber(), GUIE2Collector::MyWrapper::getParameterWindow(), and MSSOTLE2Sensors::meanVehiclesSpeed().
getCurrentVehicles()
std::vector< MSE2Collector::VehicleInfo * > MSE2Collector::getCurrentVehicles () const
Returns the VehicleInfos for the vehicles currently on the detector.
Definition at line 1289 of file MSE2Collector.cpp.
References myVehicleInfos.
Referenced by MSSOTLE2Sensors::count(), getCurrentHaltingNumber(), and MSDelayBasedTrafficLightLogic::proposeProlongation().
getDescription()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 234 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::getSingularType(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::write().
getEndPos()
double MSE2Collector::getEndPos () const inline
Returns the end position of the detector.
Returns
The detector's end position
Definition at line 383 of file MSE2Collector.h.
References myEndPos.
Referenced by libsumo::LaneArea::getLength().
getEstimatedCurrentVehicleNumber()
int MSE2Collector::getEstimatedCurrentVehicleNumber (double speedThreshold) const
Returns an estimate of the number of vehicles currently on the detector.
Definition at line 1303 of file MSE2Collector.cpp.
References MSLane::getSpeedLimit(), MSMoveReminder::myLane, and myVehicleInfos.
Referenced by subtractPassedVeh().
getEstimateQueueLength()
double MSE2Collector::getEstimateQueueLength () const
Returns an estimate of the lenght of the queue of vehicles currently stopped on the detector.
Definition at line 1327 of file MSE2Collector.cpp.
References MSLane::getLength(), MIN2(), MSMoveReminder::myLane, and myVehicleInfos.
Referenced by subtractPassedVeh().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getLane()
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), libsumo::InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
getLanes()
std::vector< MSLane * > MSE2Collector::getLanes ()
Returns a vector containing pointers to the lanes covered by the detector ordered from its first to its last lane.
Definition at line 564 of file MSE2Collector.cpp.
References MSLane::dictionary(), and myLanes.
Referenced by getLastLane(), initAuxiliaries(), and GUIE2Collector::MyWrapper::MyWrapper().
getLastLane()
MSLane* MSE2Collector::getLastLane () const inline
Returns the id of the detector's last lane.
Returns
The detector's end position
Definition at line 400 of file MSE2Collector.h.
References getCurrentVehicleNumber(), getLanes(), myLastLane, and reset().
getLength()
double MSE2Collector::getLength () const inline
Returns the length of the detector.
Returns
The detector's length
Definition at line 391 of file MSE2Collector.h.
References myDetectorLength.
Referenced by checkPositioning(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::MyWrapper(), and selectLanes().
getPassedVeh()
int MSE2Collector::getPassedVeh () inline
Returns the number of vehicles passed over the sensor (i.e. entered the sensor)
Returns
number of cars passed over the sensor
Definition at line 493 of file MSE2Collector.h.
References myNumberOfEnteredVehicles.
Referenced by MSSOTLE2Sensors::getPassedVeh().
getStartPos()
double MSE2Collector::getStartPos () const inline
Returns the begin position of the detector.
Returns
The detector's begin position
Definition at line 374 of file MSE2Collector.h.
References myStartPos.
Referenced by libsumo::LaneArea::getLength(), GUIE2Collector::MyWrapper::getParameterWindow(), libsumo::LaneArea::getPosition(), and GUIE2Collector::MyWrapper::MyWrapper().
getUsageType()
virtual DetectorUsage MSE2Collector::getUsageType () const inline virtual
Returns the detector's usage type.
See also
DetectorUsage
Returns
How the detector is used.
Definition at line 271 of file MSE2Collector.h.
References detectorUpdate(), MSE2Collector::VehicleInfo::lastPos, myUsage, notifyEnter(), notifyLeave(), notifyMove(), writeXMLDetectorProlog(), and writeXMLOutput().
Referenced by GUIE2Collector::MyWrapper::drawGL().
initAuxiliaries()
void MSE2Collector::initAuxiliaries (std::vector< MSLane *> & lanes) private
Checks integrity of myLanes, adds internal-lane information, inits myLength, myFirstLane, myLastLane, myOffsets Called once at construction. myLanes should form a continuous sequence.
Definition at line 425 of file MSE2Collector.cpp.
References Named::getID(), getLanes(), MSLink::getLength(), MSLane::getLength(), MSLane::getLinkTo(), MSLink::getViaLane(), MSGlobals::gUsingInternalLanes, MSLane::isInternal(), myDetectorLength, myEndPos, myFirstLane, myLanes, myLastLane, myOffsets, and myStartPos.
Referenced by MSE2Collector(), and subtractPassedVeh().
integrateMoveNotification()
void MSE2Collector::integrateMoveNotification (VehicleInfo * vi, const MoveNotificationInfo * mni) private
This updates the detector values and the VehicleInfo of a vehicle on the detector with the given MoveNotificationInfo generated by the vehicle during the last time step.
Parameters
Definition at line 871 of file MSE2Collector.cpp.
References MSE2Collector::MoveNotificationInfo::accel, MSE2Collector::VehicleInfo::accumulatedTimeLoss, MSE2Collector::VehicleInfo::entryOffset, MSE2Collector::MoveNotificationInfo::id, MSE2Collector::VehicleInfo::lastAccel, MSE2Collector::VehicleInfo::lastPos, MSE2Collector::VehicleInfo::lastSpeed, MSE2Collector::MoveNotificationInfo::lengthOnDetector, myCurrentMeanLength, myCurrentMeanSpeed, mySpeedSum, myStartPos, myTotalTimeLoss, myVehicleSamples, MSE2Collector::MoveNotificationInfo::newPos, MSE2Collector::VehicleInfo::onDetector, MSE2Collector::MoveNotificationInfo::onDetector, SIMTIME, MSE2Collector::MoveNotificationInfo::speed, MSE2Collector::MoveNotificationInfo::timeLoss, MSE2Collector::MoveNotificationInfo::timeOnDetector, and MSE2Collector::VehicleInfo::totalTimeOnDetector.
Referenced by detectorUpdate(), and subtractPassedVeh().
isTyped()
bool MSDetectorFileOutput::isTyped () const inline inherited
Checks whether the detector is type specific.
Returns
whether vehicle types are considered
Definition at line 154 of file MSDetectorFileOutput.h.
References MSDetectorFileOutput::myVehicleTypes.
Referenced by MSMeanData_Amitran::MSLaneMeanDataValues::write().
makeMoveNotification()
MSE2Collector::MoveNotificationInfo * MSE2Collector::makeMoveNotification (const SUMOVehicle & veh, double oldPos, double newPos, double newSpeed, const VehicleInfo & vehInfo) const private
Creates and returns a MoveNotificationInfo containing detector specific information on the vehicle's last movement.
Parameters
veh The vehicle sending the notification
oldPos The vehicle's position before the last integration step
newPos The vehicle's position after the last integration step
newSpeed The vehicle's speed after the last integration step
vehInfo Info on the detector's memory of the vehicle
Returns
A MoveNotificationInfo containing quantities of interest for the detector
Definition at line 905 of file MSE2Collector.cpp.
References calculateTimeLossAndTimeOnDetector(), MSE2Collector::VehicleInfo::entryOffset, MSE2Collector::VehicleInfo::exitOffset, SUMOVehicle::getAcceleration(), SUMOVehicle::getID(), MSE2Collector::VehicleInfo::length, MAX2(), MIN2(), myDetectorLength, and SIMTIME.
Referenced by notifyMove(), and subtractPassedVeh().
makeVehicleInfo()
MSE2Collector::VehicleInfo * MSE2Collector::makeVehicleInfo (const SUMOVehicle & veh, const MSLane * enteredLane) const private
Creates and returns a VehicleInfo (called at the vehicle's entry)
Parameters
veh The entering vehicle
enteredLane The entry lane
Returns
A vehicle info which can be used to store information about the vehicle's stay on the detector
Definition at line 734 of file MSE2Collector.cpp.
References Named::getID(), SUMOVehicle::getID(), MSVehicleType::getID(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), myDetectorLength, myLanes, myOffsets, and SIMTIME.
Referenced by notifyEnter(), and subtractPassedVeh().
notifyEnter()
bool MSE2Collector::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason, const MSLane * enteredLane) virtual
Adds the vehicle to known vehicles if not beyond the dector.
If the vehicles is within the detector are, it is added to the list of known vehicles. The method returns true as long as the vehicle is not beyond the detector.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
False, if vehicle passed the detector entirely, else true.
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 679 of file MSE2Collector.cpp.
References Named::getID(), SUMOVehicle::getID(), SUMOVehicle::getLane(), SUMOVehicle::isOnRoad(), makeVehicleInfo(), Named::myID, MSMoveReminder::myLane, myLanes, myVehicleInfos, SIMTIME, and MSDetectorFileOutput::vehicleApplies().
Referenced by getUsageType().
notifyLeave()
bool MSE2Collector::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Removes a known vehicle due to its lane-change.
If the reported vehicle is known, it is removed from the list of vehicles to regard (myKnownVehicles).
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 639 of file MSE2Collector.cpp.
References Named::getID(), SUMOVehicle::getID(), MAX2(), Named::myID, MSMoveReminder::myLane, myLanes, myNumberOfLeftVehicles, myOffsets, myVehicleInfos, MSMoveReminder::NOTIFICATION_JUNCTION, and SIMTIME.
Referenced by getUsageType().
notifyMove()
bool MSE2Collector::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual
Adds/removes vehicles from the list of vehicles to regard.
As soon as the reported vehicle enters the detector area (position>myStartPos) it is added to the list of vehicles to regard (myKnownVehicles). It is removed from this list if it leaves the detector (position<length>myEndPos). The method returns true as long as the vehicle is not beyond the detector.
Parameters
[in] veh The vehicle in question.
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep. Note that this position is given in reference to the begin of the entry lane of the vehicle.
[in] newSpeed Unused here.
Returns
False, if vehicle passed the detector entirely, else true.
See also
MSMoveReminder
MSMoveReminder::notifyMove
Reimplemented from MSMoveReminder.
Definition at line 574 of file MSE2Collector.cpp.
References MSE2Collector::VehicleInfo::distToDetectorEnd, MSE2Collector::VehicleInfo::entryOffset, MSE2Collector::VehicleInfo::exitOffset, Named::getID(), SUMOVehicle::getID(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), MSE2Collector::VehicleInfo::hasEntered, makeMoveNotification(), myDetectorLength, Named::myID, MSMoveReminder::myLane, myLeftVehicles, myMoveNotifications, myNumberOfEnteredVehicles, myNumberOfSeenVehicles, myVehicleInfos, and SIMTIME.
Referenced by getUsageType().
notifyMoveInternal()
virtual void MSMoveReminder::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane) inline virtual inherited
Internal notification about the vehicle moves.
Note
meso uses this though it never calls notifyMove()
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] frontOnLane time the front of the vehicle spent on the lane.
[in] timeOnLane time some part of the vehicle spent on the lane.
[in] meanSpeedFrontOnLane Average speed for the time that the front is on the lane.
[in] meanSpeedVehicleOnLane Average speed for the time that the vehicle is on the lane (with front or back).
[in] travelledDistanceFrontOnLane distance travelled while overlapping with the lane.
[in] travelledDistanceVehicleOnLane distance travelled while front was on the lane.
[in] meanLengthOnLane the average length of the vehicle's part on the lane during the last step (==complete length in meso case)
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 212 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
operator=()
MSE2Collector& MSE2Collector::operator= (const MSE2Collector &) private
Invalidated assignment operator.
processJams()
void MSE2Collector::processJams (std::vector< JamInfo *> & jams, JamInfo * currentJam) private
Calculates aggregated values from the given jam structure, deletes all jam-pointers.
Parameters
jams
Definition at line 1042 of file MSE2Collector.cpp.
References MSE2Collector::MoveNotificationInfo::distToDetectorEnd, MSE2Collector::MoveNotificationInfo::lengthOnDetector, MAX2(), myCurrentJamLengthInMeters, myCurrentJamLengthInVehicles, myCurrentJamNo, myCurrentMaxJamLengthInMeters, myCurrentMaxJamLengthInVehicles, myJamLengthInMetersSum, myJamLengthInVehiclesSum, and SIMTIME.
Referenced by detectorUpdate(), and subtractPassedVeh().
recalculateDetectorLength()
void MSE2Collector::recalculateDetectorLength () private
Updates the detector length after myStartPos and myEndPos have been modified.
Definition at line 260 of file MSE2Collector.cpp.
References MSLane::dictionary(), MSLink::getLength(), MSLane::getLength(), MSLane::getLinkTo(), MSGlobals::gUsingInternalLanes, myDetectorLength, myEndPos, myLanes, myLastLane, and myStartPos.
Referenced by checkPositioning(), and subtractPassedVeh().
removeFromVehicleUpdateValues()
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 93 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
reset()
void MSE2Collector::reset () virtual
Resets all values.
This method is called on initialisation and as soon as the values were written. Values for the next interval may be collected, then. The list of known vehicles stays untouched.
Reimplemented from MSDetectorFileOutput.
Definition at line 1234 of file MSE2Collector.cpp.
References myIntervalHaltingVehicleDurations, myJamLengthInMetersSum, myJamLengthInVehiclesSum, myMaxJamInMeters, myMaxJamInVehicles, myMaxOccupancy, myMaxVehicleNumber, myMeanMaxJamInMeters, myMeanMaxJamInVehicles, myMeanVehicleNumber, myNumberOfEnteredVehicles, myNumberOfLeftVehicles, myNumberOfSeenVehicles, myOccupancySum, myPastIntervalStandingDurations, myPastStandingDurations, mySpeedSum, myStartedHalts, myTimeSamples, myTotalTimeLoss, and myVehicleSamples.
Referenced by getLastLane(), MSE2Collector(), and writeXMLOutput().
selectLanes()
std::vector< MSLane * > MSE2Collector::selectLanes (MSLane * endLane, double length, std::string dir) private
This is called if no lane sequence is given to the constructor. Builds myLanes from the given information. Also inits startPos (case dir=="bw") / endPos (case dir=="fw"). Selects lanes heuristically if no unambiguous continuation exists.
Parameters
[in] lane Lane, where the detector starts/ends
[in] length Length of the detector
[in] dir Direction of detector extension with value in {"fw", "bw"} (forward / backward) If dir == "fw" lane is interpreted as corresponding to the start lane of the detector, otherwise the lane is interpreted as the end lane.
Definition at line 308 of file MSE2Collector.cpp.
References MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), MSLink::getLength(), getLength(), MSLane::getLength(), MSLane::getLinkTo(), MSGlobals::gUsingInternalLanes, MAX2(), myEndPos, myStartPos, and POSITION_EPS.
Referenced by MSE2Collector(), and subtractPassedVeh().
setDescription()
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 230 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
snap()
double MSE2Collector::snap (double value, double snapPoint, double snapDist) static private
Snaps value to snpPoint if they are closer than snapDist.
Definition at line 250 of file MSE2Collector.cpp.
Referenced by checkPositioning(), MSE2Collector(), and subtractPassedVeh().
subtractPassedVeh()
void MSE2Collector::subtractPassedVeh (int passed) inline
Subtract the number of vehicles indicated from passed from the sensor count.
Parameters
[in] passed - int that indicates the number of vehicles to subtract
Definition at line 501 of file MSE2Collector.h.
References addDetectorToLanes(), aggregateOutputValues(), buildJam(), calculateSegmentTimeLoss(), calculateTimeLossAndTimeOnDetector(), checkJam(), checkPositioning(), getEstimatedCurrentVehicleNumber(), getEstimateQueueLength(), initAuxiliaries(), integrateMoveNotification(), MSE2Collector::VehicleInfo::length, makeMoveNotification(), makeVehicleInfo(), myNumberOfEnteredVehicles, processJams(), recalculateDetectorLength(), selectLanes(), and snap().
updateDetector()
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 50 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
vehicleApplies()
bool MSDetectorFileOutput::vehicleApplies (const SUMOVehicle & veh) const inline inherited
Checks whether the detector measures vehicles of the given type.
Parameters
[in] veh the vehicle of which the type is checked.
Returns
whether it should be measured
Definition at line 145 of file MSDetectorFileOutput.h.
References MSVehicleType::getID(), SUMOVehicle::getVehicleType(), and MSDetectorFileOutput::myVehicleTypes.
Referenced by MSMeanData::MeanDataValues::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSInductLoop::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSInstantInductLoop::notifyMove().
writeXMLDetectorProlog()
void MSE2Collector::writeXMLDetectorProlog (OutputDevice & dev) const virtual
Open the XML-output.
The implementing function should open an xml element using OutputDevice::writeXMLHeader.
Parameters
[in] dev The output device to write the root into
Exceptions
IOError If an error on writing occurs
Implements MSDetectorFileOutput.
Definition at line 1148 of file MSE2Collector.cpp.
References OutputDevice::writeXMLHeader().
Referenced by getUsageType().
writeXMLOutput()
void MSE2Collector::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual
Write the generated output to the given device.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
Exceptions
IOError If an error on writing occurs
Implements MSDetectorFileOutput.
Definition at line 1153 of file MSE2Collector.cpp.
References Named::getID(), MAX2(), myHaltingVehicleDurations, myIntervalHaltingVehicleDurations, myJamLengthInMetersSum, myJamLengthInVehiclesSum, myMaxJamInMeters, myMaxJamInVehicles, myMaxOccupancy, myMaxVehicleNumber, myMeanMaxJamInMeters, myMeanMaxJamInVehicles, myMeanVehicleNumber, myNumberOfEnteredVehicles, myNumberOfLeftVehicles, myNumberOfSeenVehicles, myOccupancySum, myPastIntervalStandingDurations, myPastStandingDurations, mySpeedSum, myStartedHalts, myTimeSamples, myTotalTimeLoss, myVehicleSamples, reset(), STEPS2TIME, and time2string().
Referenced by getUsageType().
Field Documentation
myCurrentHaltingsNumber
int MSE2Collector::myCurrentHaltingsNumber private
The number of halted vehicles [#].
Definition at line 772 of file MSE2Collector.h.
Referenced by checkJam(), detectorUpdate(), and getCurrentHaltingNumber().
myCurrentJamLengthInMeters
double MSE2Collector::myCurrentJamLengthInMeters private
The overall jam length in meters.
Definition at line 766 of file MSE2Collector.h.
Referenced by getCurrentJamLengthInMeters(), and processJams().
myCurrentJamLengthInVehicles
int MSE2Collector::myCurrentJamLengthInVehicles private
The overall jam length in vehicles.
Definition at line 768 of file MSE2Collector.h.
Referenced by getCurrentJamLengthInVehicles(), and processJams().
myCurrentJamNo
int MSE2Collector::myCurrentJamNo private
The current jam number.
Definition at line 760 of file MSE2Collector.h.
Referenced by getCurrentJamNumber(), and processJams().
myCurrentMaxJamLengthInMeters
double MSE2Collector::myCurrentMaxJamLengthInMeters private
the current maximum jam length in meters
Definition at line 762 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), getCurrentMaxJamLengthInMeters(), and processJams().
myCurrentMaxJamLengthInVehicles
int MSE2Collector::myCurrentMaxJamLengthInVehicles private
The current maximum jam length in vehicles.
Definition at line 764 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), getCurrentMaxJamLengthInVehicles(), and processJams().
myCurrentMeanLength
double MSE2Collector::myCurrentMeanLength private
The current mean length.
Definition at line 758 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), detectorUpdate(), getCurrentMeanLength(), and integrateMoveNotification().
myCurrentMeanSpeed
double MSE2Collector::myCurrentMeanSpeed private
The current mean speed.
Definition at line 756 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), detectorUpdate(), getCurrentMeanSpeed(), and integrateMoveNotification().
myCurrentOccupancy
double MSE2Collector::myCurrentOccupancy private
The current occupancy.
Definition at line 754 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), and getCurrentOccupancy().
myCurrentStartedHalts
int MSE2Collector::myCurrentStartedHalts private
The number of started halts in the last step.
Definition at line 770 of file MSE2Collector.h.
Referenced by checkJam(), detectorUpdate(), and getCurrentStartedHalts().
myDescription
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 246 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
myDetectorLength
double MSE2Collector::myDetectorLength private
The total detector length.
Definition at line 669 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), checkPositioning(), getLength(), initAuxiliaries(), makeMoveNotification(), makeVehicleInfo(), notifyMove(), and recalculateDetectorLength().
myEndPos
double MSE2Collector::myEndPos private
The position the detector ends at on the last lane.
Definition at line 667 of file MSE2Collector.h.
Referenced by checkPositioning(), getEndPos(), initAuxiliaries(), MSE2Collector(), recalculateDetectorLength(), and selectLanes().
myFirstLane
MSLane* MSE2Collector::myFirstLane private
The first lane of the detector's lane sequence.
Definition at line 661 of file MSE2Collector.h.
Referenced by checkPositioning(), initAuxiliaries(), and MSE2Collector().
myHaltingVehicleDurations
std::map<std::string, SUMOTime> MSE2Collector::myHaltingVehicleDurations private
Storage for halting durations of known vehicles (for halting vehicles)
Definition at line 695 of file MSE2Collector.h.
Referenced by checkJam(), detectorUpdate(), and writeXMLOutput().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), notifyEnter(), notifyLeave(), notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myIntervalHaltingVehicleDurations
std::map<std::string, SUMOTime> MSE2Collector::myIntervalHaltingVehicleDurations private
Storage for halting durations of known vehicles (current interval)
Definition at line 698 of file MSE2Collector.h.
Referenced by checkJam(), detectorUpdate(), reset(), and writeXMLOutput().
myJamDistanceThreshold
double MSE2Collector::myJamDistanceThreshold private
Two standing vehicles must be closer than this to be counted into the same jam.
Definition at line 676 of file MSE2Collector.h.
Referenced by buildJam().
myJamHaltingSpeedThreshold
double MSE2Collector::myJamHaltingSpeedThreshold private
A vehicle must driver slower than this to be counted as a part of a jam.
Definition at line 672 of file MSE2Collector.h.
Referenced by checkJam().
myJamHaltingTimeThreshold
SUMOTime MSE2Collector::myJamHaltingTimeThreshold private
A vehicle must be that long beyond myJamHaltingSpeedThreshold to be counted as a part of a jam.
Definition at line 674 of file MSE2Collector.h.
Referenced by checkJam().
myJamLengthInMetersSum
double MSE2Collector::myJamLengthInMetersSum private
The sum of jam lengths [m].
Definition at line 720 of file MSE2Collector.h.
Referenced by processJams(), reset(), and writeXMLOutput().
myJamLengthInVehiclesSum
int MSE2Collector::myJamLengthInVehiclesSum private
The sum of jam lengths [#veh].
Definition at line 722 of file MSE2Collector.h.
Referenced by processJams(), reset(), and writeXMLOutput().
myLane
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 244 of file MSMoveReminder.h.
Referenced by getEstimatedCurrentVehicleNumber(), getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), notifyEnter(), notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), notifyMove(), and MSMeanData::MeanDataValueTracker::reset().
myLanes
std::vector<std::string> MSE2Collector::myLanes private
Definition at line 657 of file MSE2Collector.h.
Referenced by getLanes(), initAuxiliaries(), makeVehicleInfo(), notifyEnter(), notifyLeave(), and recalculateDetectorLength().
myLastLane
MSLane* MSE2Collector::myLastLane private
The last lane of the detector's lane sequence.
Definition at line 663 of file MSE2Collector.h.
Referenced by checkPositioning(), getLastLane(), initAuxiliaries(), MSE2Collector(), and recalculateDetectorLength().
myLeftVehicles
std::set<std::string> MSE2Collector::myLeftVehicles private
Keep track of vehicles that left the detector by a regular move along a junction (not lanechange, teleport, etc.) and should be removed from myVehicleInfos after taking into account their movement. Non-longitudinal exits are processed immediately in notifyLeave()
Definition at line 692 of file MSE2Collector.h.
Referenced by detectorUpdate(), and notifyMove().
myMaxJamInMeters
double MSE2Collector::myMaxJamInMeters private
The max jam length [m].
Definition at line 736 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMaxJamInVehicles
int MSE2Collector::myMaxJamInVehicles private
The max jam length [#veh].
Definition at line 734 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMaxOccupancy
double MSE2Collector::myMaxOccupancy private
The maximum occupancy [%].
Definition at line 728 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMaxVehicleNumber
int MSE2Collector::myMaxVehicleNumber private
The maximal number of vehicles located on the detector simultaneously since the last reset.
Definition at line 751 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMeanMaxJamInMeters
double MSE2Collector::myMeanMaxJamInMeters private
The mean jam length [m].
Definition at line 732 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMeanMaxJamInVehicles
int MSE2Collector::myMeanMaxJamInVehicles private
The mean jam length [#veh].
Definition at line 730 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMeanVehicleNumber
int MSE2Collector::myMeanVehicleNumber private
The mean number of vehicles [#veh].
Definition at line 738 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myMoveNotifications
std::vector<MoveNotificationInfo*> MSE2Collector::myMoveNotifications private
Temporal storage for notifications from vehicles that did call the detector's notifyMove() in the last time step.
Definition at line 687 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), detectorUpdate(), notifyMove(), and ~MSE2Collector().
myNumberOfEnteredVehicles
int MSE2Collector::myNumberOfEnteredVehicles private
Definition at line 745 of file MSE2Collector.h.
Referenced by detectorUpdate(), getPassedVeh(), notifyMove(), reset(), subtractPassedVeh(), and writeXMLOutput().
myNumberOfLeftVehicles
int MSE2Collector::myNumberOfLeftVehicles private
The number of vehicles, which have left the detector since the last reset.
Definition at line 749 of file MSE2Collector.h.
Referenced by detectorUpdate(), notifyLeave(), reset(), and writeXMLOutput().
myNumberOfSeenVehicles
int MSE2Collector::myNumberOfSeenVehicles private
The number of vehicles, present on the detector at the last reset.
Definition at line 747 of file MSE2Collector.h.
Referenced by detectorUpdate(), notifyMove(), reset(), and writeXMLOutput().
myOccupancySum
double MSE2Collector::myOccupancySum private
The sum of occupancies [%].
Definition at line 726 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myOffsets
std::vector<double> MSE2Collector::myOffsets private
The distances of the lane-beginnings from the detector start-point.
Definition at line 659 of file MSE2Collector.h.
Referenced by initAuxiliaries(), makeVehicleInfo(), and notifyLeave().
myPastIntervalStandingDurations
std::vector<SUMOTime> MSE2Collector::myPastIntervalStandingDurations private
Halting durations of ended halts for the current interval [s].
Definition at line 704 of file MSE2Collector.h.
Referenced by checkJam(), reset(), and writeXMLOutput().
myPastStandingDurations
std::vector<SUMOTime> MSE2Collector::myPastStandingDurations private
Halting durations of ended halts [s].
Definition at line 701 of file MSE2Collector.h.
Referenced by checkJam(), reset(), and writeXMLOutput().
mySpeedSum
double MSE2Collector::mySpeedSum private
The sum of collected vehicle speeds [m/s].
Definition at line 716 of file MSE2Collector.h.
Referenced by integrateMoveNotification(), reset(), and writeXMLOutput().
myStartedHalts
double MSE2Collector::myStartedHalts private
The number of started halts [#].
Definition at line 718 of file MSE2Collector.h.
Referenced by checkJam(), reset(), and writeXMLOutput().
myStartPos
double MSE2Collector::myStartPos private
The position the detector starts at on the first lane.
Definition at line 665 of file MSE2Collector.h.
Referenced by checkPositioning(), getStartPos(), initAuxiliaries(), integrateMoveNotification(), MSE2Collector(), recalculateDetectorLength(), and selectLanes().
myTimeSamples
int MSE2Collector::myTimeSamples private
The current aggregation duration [#steps].
Definition at line 724 of file MSE2Collector.h.
Referenced by aggregateOutputValues(), reset(), and writeXMLOutput().
myTotalTimeLoss
double MSE2Collector::myTotalTimeLoss private
The total amount of all time losses [time x vehicle] since the last reset.
Definition at line 714 of file MSE2Collector.h.
Referenced by integrateMoveNotification(), reset(), and writeXMLOutput().
myUsage
DetectorUsage MSE2Collector::myUsage private
Information about how this detector is used.
Definition at line 652 of file MSE2Collector.h.
Referenced by getUsageType().
myVehicleInfos
VehicleInfoMap MSE2Collector::myVehicleInfos private
Definition at line 683 of file MSE2Collector.h.
Referenced by detectorUpdate(), getCurrentVehicleIDs(), getCurrentVehicleNumber(), getCurrentVehicles(), getEstimatedCurrentVehicleNumber(), getEstimateQueueLength(), notifyEnter(), notifyLeave(), notifyMove(), and ~MSE2Collector().
myVehicleSamples
double MSE2Collector::myVehicleSamples private
Definition at line 712 of file MSE2Collector.h.
Referenced by integrateMoveNotification(), reset(), and writeXMLOutput().
myVehicleTypes
std::set<std::string> MSDetectorFileOutput::myVehicleTypes protected inherited
The vehicle types to look for (empty means all)
Definition at line 161 of file MSDetectorFileOutput.h.
Referenced by MSDetectorFileOutput::isTyped(), MSDetectorFileOutput::MSDetectorFileOutput(), and MSDetectorFileOutput::vehicleApplies().
The documentation for this class was generated from the following files:
MSE2Collector.h
MSE2Collector.cpp