SUMO - Simulation of Urban MObility: GNECalibratorFlow Class Reference
GNECalibratorFlow Class Reference
#include <GNECalibratorFlow.h>
Public Types
enum TypeOfFlow { GNE_CALIBRATORFLOW_INVALID, GNE_CALIBRATORFLOW_VEHSPERHOUR, GNE_CALIBRATORFLOW_PERIOD, GNE_CALIBRATORFLOW_PROBABILITY }
type of flow
Public Member Functions
void decRef (const std::string &debugMsg="")
Decrease reference.
virtual std::string getAttributeForSelection (SumoXMLAttr key) const
method for getting the attribute in the context of object selection
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
GNECalibrator * getCalibratorParent () const
get pointer to calibrator parent
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
double getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleClass getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleShape getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
RGBColor getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< double > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
GNECalibratorFlow::TypeOfFlow getFlowType () const
get type of flow
const GUIGlObject * getGUIGLObject () const
get const pointer to GUIGlObject vinculated with this Attribute Carrier
GUIGlObject * getGUIGLObject ()
get pointer to GUIGlObject vinculated with this Attribute Carrier
GUIIcon getGUIIcon () const
get GUI icon assigned to this object
FXIcon * getIcon () const
get FXIcon assigned to this object
const std::string getID () const
function to support debugging
SumoXMLTag getTag () const
get XML Tag assigned to this object
GNECalibratorFlow (GNECalibratorDialog *calibratorDialog)
constructor (used only in GNECalibratorDialog)
GNECalibratorFlow (GNECalibrator *calibratorParent, const std::string &flowID, GNECalibratorVehicleType *vehicleType, GNECalibratorRoute *route, const RGBColor &color, const std::string &departLane, const std::string &departPos, const std::string &departSpeed, const std::string &arrivalLane, const std::string &arrivalPos, const std::string &arrivalSpeed, const std::string &line, int personNumber, int containerNumber, bool reroute, const std::string &departPosLat, const std::string &arrivalPosLat, double begin, double end, double vehsPerHour, double period, double probability, int number, GNECalibratorFlow::TypeOfFlow flowType)
parameter constructor
void incRef (const std::string &debugMsg="")
Increarse reference.
template<>
int parse (const std::string &string)
template<>
double parse (const std::string &string)
template<>
bool parse (const std::string &string)
template<>
std::string parse (const std::string &string)
template<>
SUMOVehicleClass parse (const std::string &string)
template<>
RGBColor parse (const std::string &string)
template<>
SUMOVehicleShape parse (const std::string &string)
template<>
std::vector< std::string > parse (const std::string &string)
template<>
std::vector< int > parse (const std::string &string)
template<>
std::vector< double > parse (const std::string &string)
template<>
std::vector< bool > parse (const std::string &string)
void setFlowType (GNECalibratorFlow::TypeOfFlow type)
set type of flow
bool unreferenced ()
check if object ins't referenced
void writeFlow (OutputDevice &device)
write Flow values into a XML
~GNECalibratorFlow ()
destructor
std::string getAttribute (SumoXMLAttr key) const
inherited from GNEAttributeCarrier
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
bool isValid (SumoXMLAttr key, const std::string &value)
Static Public Member Functions
static const std::vector< SumoXMLTag > & allowedAdditionalTags ()
get all editable for tag additional elements
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedNetElementsTags ()
get all editable for tag net elements
static const std::vector< SumoXMLTag > & allowedShapeTags ()
get all editable for tag shape elements
static std::vector< SumoXMLTag > allowedTags ()
get all editable for tag elements of all types
static bool canBlockMovement (SumoXMLTag tag)
return true if element tag can block their movement
static bool canBlockShape (SumoXMLTag tag)
return true if element tag can block their shape
static bool canOpenDialog (SumoXMLTag tag)
return true if element tag can open a values editor
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
static std::string getAttributeType (SumoXMLTag tag, SumoXMLAttr attr)
get type of attribute
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if an element with certain tag has a certain attribute
static bool hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
check if attribute of an element has a default avlue
static bool isBool (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool for a certain tag
static bool isColor (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type color for a certain tag
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFilename (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a filename
static bool isFloat (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNonEditable (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is non editable
static bool isNumerical (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical (int or float)
static bool isPositive (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is only Positive (i.e. cannot take negative values)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isProbability (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is a probability (i.e. oly can values between [0, 1])
static bool isString (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type string
static bool isTime (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is time
static bool isUnique (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
static bool isValidFilename (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
static bool isVClass (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a list of Vehicle Classes
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
template<typename T >
static T parseAttributeFromXML (const SUMOSAXAttributes &attrs, const std::string &objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool &abort, bool report=true)
Parse attribute from XML and show warnings if there are problems parsing it.
function used to parse GNEEdges and GNELanes
static bool checkGNEEdgesValid (GNENet *net, const std::string &value, bool report)
check if a list of edge IDs is valid
static bool checkGNELanesValid (GNENet *net, const std::string &value, bool report)
check if a list of Lane IDs is valid
static std::vector< GNEEdge * > parseGNEEdges (GNENet *net, const std::string &value)
parse string into vector of GNEEdges
static std::string parseGNEEdges (const std::vector< GNEEdge *> &edges)
parse vector of GNEEdges into string
static std::vector< GNELane * > parseGNELanes (GNENet *net, const std::string &value)
parse string into vector of GNELanes
static std::string parseGNELanes (const std::vector< GNELane *> &lanes)
parse vector of GNELanes into string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const double INVALID_POSITION = -1000000
default value for invalid positions (used by POIs and Polygons)
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
Protected Attributes
std::string myArrivalLane
arrival lane
std::string myArrivalPos
arrival pos
std::string myArrivalPosLat
std::string myArrivalSpeed
arrival speed
GNECalibrator * myCalibratorParent
pointer to calibrator parent
RGBColor myColor
color of flow
int myContainerNumber
number of container
std::string myDepartLane
depart lane
std::string myDepartPos
depart position
std::string myDepartPosLat
departPosLat
std::string myDepartSpeed
depart speed
std::string myFlowID
ID of flow.
TypeOfFlow myFlowType
type of flow
std::string myLine
line of bus/container stop
int myPersonNumber
number of person
bool myReroute
reroute
GNECalibratorRoute * myRoute
route in which this flow is used
GNECalibratorVehicleType * myVehicleType
type of flow
specific of flows
time step begin
double myBegin
double myEnd
time step end
double myVehsPerHour
flows per hour
double myPeriod
period
double myProbability
probability
int myNumber
number of flow
Private Member Functions
GNECalibratorFlow (const GNECalibratorFlow &)=delete
Invalidated copy constructor.
GNECalibratorFlow & operator= (const GNECalibratorFlow &)=delete
Invalidated assignment operator.
void setAttribute (SumoXMLAttr key, const std::string &value)
method for setting the attribute and nothing else
Detailed Description
flow flow used by GNECalibrators
Definition at line 54 of file GNECalibratorFlow.h.
Member Enumeration Documentation
TypeOfFlow
enum GNECalibratorFlow::TypeOfFlow
type of flow
Enumerator
GNE_CALIBRATORFLOW_INVALID
GNE_CALIBRATORFLOW_VEHSPERHOUR
GNE_CALIBRATORFLOW_PERIOD
GNE_CALIBRATORFLOW_PROBABILITY
Definition at line 59 of file GNECalibratorFlow.h.
Constructor & Destructor Documentation
GNECalibratorFlow() [1/3]
GNECalibratorFlow::GNECalibratorFlow (GNECalibratorDialog * calibratorDialog)
constructor (used only in GNECalibratorDialog)
Definition at line 63 of file GNECalibratorFlow.cpp.
GNECalibratorFlow() [2/3]
GNECalibratorFlow::GNECalibratorFlow (GNECalibrator * calibratorParent, const std::string & flowID, GNECalibratorVehicleType * vehicleType, GNECalibratorRoute * route, const RGBColor & color, const std::string & departLane, const std::string & departPos, const std::string & departSpeed, const std::string & arrivalLane, const std::string & arrivalPos, const std::string & arrivalSpeed, const std::string & line, int personNumber, int containerNumber, bool reroute, const std::string & departPosLat, const std::string & arrivalPosLat, double begin, double end, double vehsPerHour, double period, double probability, int number, GNECalibratorFlow::TypeOfFlow flowType)
parameter constructor
Definition at line 91 of file GNECalibratorFlow.cpp.
~GNECalibratorFlow()
GNECalibratorFlow::~GNECalibratorFlow ()
destructor
Definition at line 124 of file GNECalibratorFlow.cpp.
GNECalibratorFlow() [3/3]
GNECalibratorFlow::GNECalibratorFlow (const GNECalibratorFlow &) private delete
Invalidated copy constructor.
Member Function Documentation
allowedAdditionalTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedAdditionalTags () static inherited
get all editable for tag additional elements
Definition at line 621 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedAttributes()
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 287 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, OptionsCont::getOptions(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, NODEFAULTVALUE, SUMO_ATTR_ACCEL, SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPE, toString(), NBEdge::UNSPECIFIED_CONTPOS, NBEdge::UNSPECIFIED_SPEED, and NBEdge::UNSPECIFIED_VISIBILITY_DISTANCE.
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getDefaultValue(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNESelectorFrame::onCmdSelMBAttribute(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedNetElementsTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedNetElementsTags () static inherited
get all editable for tag net elements
Definition at line 607 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedShapeTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedShapeTags () static inherited
get all editable for tag shape elements
Definition at line 644 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedShapeTags, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEPolygonFrame::GNEPolygonFrame(), GNEPolygonFrame::onCmdSelectShape(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedTags()
std::vector< SumoXMLTag > GNEAttributeCarrier::allowedTags () static inherited
get all editable for tag elements of all types
Definition at line 596 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedNetElementsTags(), and GNEAttributeCarrier::allowedShapeTags().
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
canBlockMovement()
bool GNEAttributeCarrier::canBlockMovement (SumoXMLTag tag) static inherited
return true if element tag can block their movement
Definition at line 656 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockMovementTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::onCmdSelectAdditional(), GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canBlockShape()
bool GNEAttributeCarrier::canBlockShape (SumoXMLTag tag) static inherited
return true if element tag can block their shape
Definition at line 678 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockShapeTags, and SUMO_TAG_POLY.
Referenced by GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canOpenDialog()
bool GNEAttributeCarrier::canOpenDialog (SumoXMLTag tag) static inherited
return true if element tag can open a values editor
Definition at line 688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myDialogTags, SUMO_TAG_CALIBRATOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditional::getPopUpMenu(), GNEViewNet::onCmdOpenAdditionalDialog(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canParse()
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 230 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
checkGNEEdgesValid()
bool GNEAttributeCarrier::checkGNEEdgesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of edge IDs is valid
value string with a list of edges report enable or disable show warning if edges aren't valid
Definition at line 1712 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge(), SUMO_ATTR_EDGES, SUMO_TAG_EDGE, toString(), and WRITE_WARNING.
Referenced by GNECalibratorRoute::isValid(), GNECrossing::isValid(), GNERerouter::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), and GNEAttributeCarrier::parseAttributeFromXML().
checkGNELanesValid()
bool GNEAttributeCarrier::checkGNELanesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of Lane IDs is valid
value string with a list of lanes report enable or disable show warning if lanes aren't valid
Definition at line 1730 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane(), SUMO_ATTR_LANES, SUMO_TAG_LANE, toString(), and WRITE_WARNING.
Referenced by GNEVariableSpeedSign::isValid(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), and GNEAttributeCarrier::parseAttributeFromXML().
decRef()
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Decrease reference.
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
discreteChoices()
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 1233 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_GUISHAPE, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_VCLASS, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_VTYPE, SumoVehicleClassStrings, SumoVehicleShapeStrings, TLTYPE_INVALID, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
discreteCombinableChoices()
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 1290 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttribute()
std::string GNECalibratorFlow::getAttribute (SumoXMLAttr key) const virtual
inherited from GNEAttributeCarrier
Implements GNEAttributeCarrier.
Definition at line 202 of file GNECalibratorFlow.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myArrivalLane, myArrivalPos, myArrivalPosLat, myArrivalSpeed, myBegin, myColor, myContainerNumber, myDepartLane, myDepartPos, myDepartPosLat, myDepartSpeed, myEnd, myFlowID, myLine, myNumber, myPeriod, myPersonNumber, myProbability, myReroute, myRoute, myVehicleType, myVehsPerHour, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, and toString().
Referenced by setAttribute(), and GNECalibratorFlowDialog::updateCalibratorFlowValues().
getAttributeForSelection()
std::string GNEAttributeCarrier::getAttributeForSelection (SumoXMLAttr key) const virtual inherited
method for getting the attribute in the context of object selection
Reimplemented in GNEEdge, and GNELane.
Definition at line 183 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute().
Referenced by GNESelectorFrame::getMatches(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttributeType()
std::string GNEAttributeCarrier::getAttributeType (SumoXMLTag tag, SumoXMLAttr attr) static inherited
get type of attribute
Definition at line 247 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), and toString().
Referenced by GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttrs()
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 231 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getCalibratorParent()
GNECalibrator * GNECalibratorFlow::getCalibratorParent () const
get pointer to calibrator parent
Definition at line 184 of file GNECalibratorFlow.cpp.
References myCalibratorParent.
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdSetVariable(), GNEChange_CalibratorItem::redo(), GNEChange_CalibratorItem::undo(), and GNEChange_CalibratorItem::~GNEChange_CalibratorItem().
getDefaultValue() [1/12]
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getDefaultValue() [2/12]
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1580 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [3/12]
template<> double GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1592 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [4/12]
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1604 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [5/12]
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1616 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [6/12]
template<> SUMOVehicleClass GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1628 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1640 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [8/12]
template<> RGBColor GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1652 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [9/12]
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1664 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [10/12]
template<> std::vector<double> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1676 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [12/12]
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1700 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefinition()
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 1296 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ACCEL, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEO, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
Referenced by GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getFlowType()
GNECalibratorFlow::TypeOfFlow GNECalibratorFlow::getFlowType () const
get type of flow
Definition at line 190 of file GNECalibratorFlow.cpp.
References myFlowType.
Referenced by GNECalibratorFlowDialog::updateCalibratorFlowValues().
getGUIGLObject() [1/2]
const GUIGlObject * GNEAttributeCarrier::getGUIGLObject () const inherited
get const pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to const GUIGlObject
Definition at line 207 of file GNEAttributeCarrier.cpp.
Referenced by GNEShape::drawLockIcon(), GNENet::insertShape(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::removePolygonForEditShapes(), GNENet::removeShape(), GNENet::retrieveAttributeCarriers(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getGUIGLObject() [2/2]
GUIGlObject * GNEAttributeCarrier::getGUIGLObject () inherited
get pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to GUIGlObject
Definition at line 219 of file GNEAttributeCarrier.cpp.
getGUIIcon()
GUIIcon GNEAttributeCarrier::getGUIIcon () const inherited
get GUI icon assigned to this object
Definition at line 201 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myIcon.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
getHigherNumberOfAttributes()
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 1563 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedNetElementsTags(), GNEAttributeCarrier::allowedShapeTags(), MAX2(), and GNEAttributeCarrier::myMaxNumAttribute.
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getIcon()
FXIcon * GNEAttributeCarrier::getIcon () const inherited
get FXIcon assigned to this object
Definition at line 195 of file GNEAttributeCarrier.cpp.
References GUIIconSubSys::getIcon(), and GNEAttributeCarrier::myIcon.
Referenced by GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNEAdditional::getPopUpMenu(), GNEDeleteFrame::markAttributeCarrier(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEDeleteFrame::updateCurrentLabel(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getID()
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 241 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNECrossingFrame::addCrossing(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), GNEAdditional::addLaneChild(), GNEJunction::addOutgoingGNEEdge(), GNENet::addPOI(), GNEPolygonFrame::addPOILane(), GNENet::addReversedEdge(), GNELane::addShapeChild(), GNEAdditionalHandler::buildRerouterInterval(), GNENet::changeCalibratorFlowID(), GNENet::changeCalibratorRouteID(), GNENet::changeCalibratorVehicleTypeID(), GNENet::changeShapeID(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNECalibrator::getAttribute(), GNEJunction::getAttribute(), GNEAdditionalHandler::getPosition(), GNECalibratorRoute::GNECalibratorRoute(), GNENet::insertAdditional(), GNENet::insertCalibratorFlow(), GNENet::insertCalibratorRoute(), GNENet::insertCalibratorVehicleType(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNEDeleteFrame::markAttributeCarrier(), GNECrossingFrame::crossingParameters::markEdge(), GNERerouterDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdSetVariable(), GNECalibratorRouteDialog::onCmdSetVariable(), GNEViewNet::onCmdTransformPOI(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEPolygonFrame::processClick(), GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_CalibratorItem::redo(), GNEChange_RerouterItem::redo(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), GNEJunction::removeEdgeFromCrossings(), GNEEdge::removeEdgeOfAdditionalParents(), GNEJunction::removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), GNELane::removeLaneOfAdditionalParents(), GNEJunction::removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceIncomingEdge(), GNENet::retrieveEdge(), GNEEdge::retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNENet::reverseEdge(), GNEInspectorFrame::NeteditParameters::show(), GNEEdge::smooth(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_TLS::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_CalibratorItem::undo(), GNEChange_RerouterItem::undo(), GNENet::updateAdditionalID(), GNECalibratorRouteDialog::updateCalibratorRouteValues(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNECalibrator::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), GNEPOILane::writeShape(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEJunction::~GNEJunction().
getTag()
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get XML Tag assigned to this object
Definition at line 189 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), GNEAdditional::addLaneChild(), GNEJunction::addOutgoingGNEEdge(), GNENet::addPOI(), GNELane::addShapeChild(), GNEViewNet::begingMoveSelection(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildClosingLaneReroute(), GNEAdditionalHandler::buildClosingReroute(), GNEAdditionalHandler::builDestProbReroute(), GNEAdditionalHandler::buildRerouterInterval(), GNEAdditionalHandler::buildRouteProbReroute(), GNEAdditionalHandler::buildVariableSpeedSignStep(), GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNENet::changeShapeID(), GNEDetectorE3::commitGeometryMoving(), GNEPOI::commitGeometryMoving(), GNEDetector::commitGeometryMoving(), GNEPOILane::commitGeometryMoving(), GNEStoppingPlace::commitGeometryMoving(), GNEVariableSpeedSign::commitGeometryMoving(), GNERerouter::commitGeometryMoving(), GNEJunction::commitGeometryMoving(), GNEPoly::commitShapeChange(), GNEEdge::commitShapeChange(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteShape(), GNERouteProbReroute::getAttribute(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNEVariableSpeedSignStep::getAttribute(), GNECalibratorRoute::getAttribute(), GNECalibratorVehicleType::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNECrossing::getAttribute(), GNEDetectorE3::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), GNECalibrator::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNESelectorFrame::getMatches(), GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEEdge::getRouteProbeRelativePosition(), GNEEdge::getVaporizerRelativePosition(), GNECalibratorRoute::GNECalibratorRoute(), GNEViewNet::hotkeyEnter(), GNENet::insertAdditional(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNERouteProbReroute::isValid(), GNEDestProbReroute::isValid(), GNEClosingLaneReroute::isValid(), GNEClosingReroute::isValid(), GNEVariableSpeedSignStep::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNERerouterInterval::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), isValid(), GNEVaporizer::isValid(), GNECrossing::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNEConnection::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNELane::isValid(), GNEJunction::isValid(), GNEEdge::isValid(), GNEAdditional::isValidAdditionalID(), GNEDeleteFrame::markAttributeCarrier(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNEViewNet::onCmdOpenAdditionalDialog(), GNEViewNet::onLeftBtnPress(), GNEAdditional::openAdditionalDialog(), GNEChange_Shape::redo(), GNEChange_Junction::redo(), GNEChange_TLS::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_Shape::redoName(), GNEChange_VariableSpeedSignItem::redoName(), GNEChange_Additional::redoName(), GNEChange_Attribute::redoName(), GNEChange_CalibratorItem::redoName(), GNEChange_RerouterItem::redoName(), GNEAdditionalFrame::removeAdditional(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), GNEJunction::removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), GNEJunction::removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceInListAttribute(), GNEEdge::retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNERouteProbReroute::setAttribute(), GNEDestProbReroute::setAttribute(), GNEClosingLaneReroute::setAttribute(), GNEClosingReroute::setAttribute(), GNEVariableSpeedSignStep::setAttribute(), GNECalibratorRoute::setAttribute(), GNECalibratorVehicleType::setAttribute(), GNERerouterInterval::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), setAttribute(), GNEVaporizer::setAttribute(), GNECrossing::setAttribute(), GNEDetectorE3::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNEConnection::setAttribute(), GNERerouter::setAttribute(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), GNECalibrator::setAttribute(), GNELane::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setAttribute(), GNEAdditional::setBlockIconRotation(), GNEInspectorFrame::NeteditParameters::show(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_TLS::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_Shape::undoName(), GNEChange_VariableSpeedSignItem::undoName(), GNEChange_Additional::undoName(), GNEChange_Attribute::undoName(), GNEChange_CalibratorItem::undoName(), GNEChange_RerouterItem::undoName(), GNENet::updateAdditionalID(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), writeFlow(), GNERerouterInterval::writeRerouterInterval(), GNECalibratorRoute::writeRoute(), GNERouteProbReroute::writeRouteProbReroute(), GNECalibratorVehicleType::writeVehicleType(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_Shape::~GNEChange_Shape(), and GNEChange_TLS::~GNEChange_TLS().
hasAttribute()
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if an element with certain tag has a certain attribute
Definition at line 1211 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), GNEChange_Additional::GNEChange_Additional(), GNEViewNet::hotkeyEnter(), GNEAdditional::setBlockIconRotation(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
hasDefaultValue()
bool GNEAttributeCarrier::hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if attribute of an element has a default avlue
Definition at line 1222 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
incRef()
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Increarse reference.
Definition at line 76 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNEChange_CalibratorItem::GNEChange_CalibratorItem(), GNEChange_RerouterItem::GNEChange_RerouterItem(), GNEJunction::rebuildGNECrossings(), GNENet::registerEdge(), GNENet::registerJunction(), GNEEdge::remakeGNEConnections(), and GNEInspectorFrame::setEdgeTemplate().
isBool()
bool GNEAttributeCarrier::isBool (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool for a certain tag
Definition at line 867 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBoolAttrs, SUMO_ATTR_ACCELERATION, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_FILL, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_GEO, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PASS, SUMO_ATTR_PRIORITY, SUMO_ATTR_REROUTE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POLY, and SUMO_TAG_REROUTER.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isColor()
bool GNEAttributeCarrier::isColor (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type color for a certain tag
Definition at line 910 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myColorAttrs, SUMO_ATTR_COLOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_ROUTE, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isDiscrete()
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 1045 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFilename()
bool GNEAttributeCarrier::isFilename (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a filename
Definition at line 1141 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, SUMO_ATTR_FILE, SUMO_ATTR_IMGFILE, SUMO_ATTR_OUTPUT, SUMO_TAG_CALIBRATOR, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFloat()
bool GNEAttributeCarrier::isFloat (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 741 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_ANGLE, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERIOD, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_STEP, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isInt()
bool GNEAttributeCarrier::isInt (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 707 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_FROM_LANE, SUMO_ATTR_INDEX, SUMO_ATTR_LAYER, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isList()
bool GNEAttributeCarrier::isList (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 935 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, SUMO_ATTR_LINES, SUMO_ATTR_SHAPE, SUMO_TAG_BUS_STOP, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNENet::replaceInListAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isNonEditable()
bool GNEAttributeCarrier::isNonEditable (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is non editable
Definition at line 1193 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNonEditableAttrs, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
isNumerical()
bool GNEAttributeCarrier::isNumerical (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 701 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [1/2]
bool GNEAttributeCarrier::isPositive (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is only Positive (i.e. cannot take negative values)
Definition at line 1055 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myPositiveAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [2/2]
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 249 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFilename(), and GNEAttributeCarrier::isValidID().
isProbability()
bool GNEAttributeCarrier::isProbability (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is a probability (i.e. oly can values between [0, 1])
Definition at line 1122 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myProbabilityAttrs, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_PROB, SUMO_TAG_CHARGING_STATION, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_FLOW, SUMO_TAG_REROUTER, and SUMO_TAG_ROUTE_PROB_REROUTE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isString()
bool GNEAttributeCarrier::isString (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 929 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isNumerical(), and GNEAttributeCarrier::isTime().
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isTime()
bool GNEAttributeCarrier::isTime (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is time
Definition at line 830 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTimeAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_END, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_STARTTIME, SUMO_ATTR_TIME, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isUnique()
bool GNEAttributeCarrier::isUnique (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
Definition at line 958 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspectMultisection(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isValid()
bool GNECalibratorFlow::isValid (SumoXMLAttr key, const std::string & value) virtual
Implements GNEAttributeCarrier.
Definition at line 291 of file GNECalibratorFlow.cpp.
References GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEAdditional::getViewNet(), GNEAttributeCarrier::isValidID(), myCalibratorParent, GNENet::retrieveCalibratorFlow(), GNENet::retrieveCalibratorRoute(), GNENet::retrieveCalibratorVehicleType(), GNENet::retrieveLane(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, and toString().
Referenced by GNECalibratorFlowDialog::onCmdSetVariable().
isValidFilename()
bool GNEAttributeCarrier::isValidFilename (const std::string & value) static inherited
true if value is a valid file value
Definition at line 275 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNECalibratorVehicleType::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isValidID()
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 269 of file GNEAttributeCarrier.cpp.
Referenced by GNEAdditional::changeAdditionalID(), GNEAttributeCarrier::isPositive(), GNERouteProbReroute::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEJunction::isValid(), GNEEdge::isValid(), GNEAdditional::isValidAdditionalID(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isVClass()
bool GNEAttributeCarrier::isVClass (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a list of Vehicle Classes
Definition at line 1172 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, GNEAttributeCarrier::myVClassAttrs, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_EDGE, and SUMO_TAG_LANE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
operator=()
GNECalibratorFlow& GNECalibratorFlow::operator= (const GNECalibratorFlow &) private delete
Invalidated assignment operator.
parse() [1/12]
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 88 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int().
parse() [2/12]
template<> double GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 94 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2double().
parse() [3/12]
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 100 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
parse() [4/12]
template<> std::string GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 106 of file GNEAttributeCarrier.cpp.
parse() [5/12]
template<> SUMOVehicleClass GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 112 of file GNEAttributeCarrier.cpp.
References SumoVehicleClassStrings, and SVC_IGNORING.
parse() [6/12]
template<> RGBColor GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 124 of file GNEAttributeCarrier.cpp.
References RGBColor::parseColor().
parse() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 130 of file GNEAttributeCarrier.cpp.
References SumoVehicleShapeStrings, and SVS_UNKNOWN.
parse() [8/12]
template<> std::vector<std::string> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 142 of file GNEAttributeCarrier.cpp.
References SUMOSAXAttributes::parseStringVector().
parse() [9/12]
template<> std::vector<int> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 150 of file GNEAttributeCarrier.cpp.
parse() [10/12]
template<> std::vector<double> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 161 of file GNEAttributeCarrier.cpp.
parse() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 172 of file GNEAttributeCarrier.cpp.
parse() [12/12]
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse().
parseAttributeFromXML()
template<typename T > static T GNEAttributeCarrier::parseAttributeFromXML (const SUMOSAXAttributes & attrs, const std::string & objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool & abort, bool report = true) inline static inherited
Parse attribute from XML and show warnings if there are problems parsing it.
Definition at line 276 of file GNEAttributeCarrier.h.
References canParseVehicleClasses(), GNEAttributeCarrier::checkGNEEdgesValid(), GNEAttributeCarrier::checkGNELanesValid(), SUMOSAXAttributes::get(), GNEAttributeCarrier::getAttributeType(), SUMOSAXAttributes::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), GNEAttributeCarrier::isValidID(), GNEAttributeCarrier::isVClass(), GNEAttributeCarrier::parseGNEEdges(), GNEAttributeCarrier::parseGNELanes(), GNEAttributeCarrier::setAttribute(), SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_VCLASS, toString(), and WRITE_WARNING.
parseGNEEdges() [1/2]
std::vector< GNEEdge * > GNEAttributeCarrier::parseGNEEdges (GNENet * net, const std::string & value) static inherited
parse string into vector of GNEEdges
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1748 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge().
Referenced by GNEAdditionalHandler::buildAdditional(), GNECalibratorRoute::getAttribute(), GNERerouter::getAttribute(), GNECalibratorRoute::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAttributeCarrier::parseAttributeFromXML(), GNECalibratorRoute::setAttribute(), GNECrossing::setAttribute(), GNERerouter::setAttribute(), GNERerouter::writeAdditional(), and GNECalibratorRoute::writeRoute().
parseGNEEdges() [2/2]
std::string GNEAttributeCarrier::parseGNEEdges (const std::vector< GNEEdge *> & edges) static inherited
parse vector of GNEEdges into string
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1774 of file GNEAttributeCarrier.cpp.
References joinToString().
parseGNELanes() [1/2]
std::vector< GNELane * > GNEAttributeCarrier::parseGNELanes (GNENet * net, const std::string & value) static inherited
parse string into vector of GNELanes
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1761 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane().
Referenced by GNEAdditionalHandler::buildAdditional(), GNEVariableSpeedSign::getAttribute(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAttributeCarrier::parseAttributeFromXML(), GNEVariableSpeedSign::setAttribute(), and GNEVariableSpeedSign::writeAdditional().
parseGNELanes() [2/2]
std::string GNEAttributeCarrier::parseGNELanes (const std::vector< GNELane *> & lanes) static inherited
parse vector of GNELanes into string
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1785 of file GNEAttributeCarrier.cpp.
References joinToString().
setAttribute() [1/2]
void GNECalibratorFlow::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
Implements GNEAttributeCarrier.
Definition at line 255 of file GNECalibratorFlow.cpp.
References getAttribute(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::GNEChange_Attribute, GNEUndoList::p_add(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, and toString().
Referenced by GNECalibratorFlowDialog::onCmdSetVariable().
setAttribute() [2/2]
void GNECalibratorFlow::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
method for setting the attribute and nothing else
Implements GNEAttributeCarrier.
Definition at line 379 of file GNECalibratorFlow.cpp.
References GNENet::changeCalibratorFlowID(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEAdditional::getViewNet(), myArrivalLane, myArrivalPos, myArrivalPosLat, myArrivalSpeed, myBegin, myCalibratorParent, myColor, myContainerNumber, myDepartLane, myDepartPos, myDepartPosLat, myDepartSpeed, myEnd, myFlowID, myLine, myNumber, myPeriod, myPersonNumber, myProbability, myReroute, myRoute, myVehicleType, myVehsPerHour, GNENet::retrieveCalibratorRoute(), GNENet::retrieveCalibratorVehicleType(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, and toString().
setFlowType()
void GNECalibratorFlow::setFlowType (GNECalibratorFlow::TypeOfFlow type)
set type of flow
Definition at line 196 of file GNECalibratorFlow.cpp.
References myFlowType.
Referenced by GNECalibratorFlowDialog::onCmdSetTypeOfFlow().
unreferenced()
bool GNEReferenceCounter::unreferenced () inline inherited
check if object ins't referenced
Definition at line 87 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
writeFlow()
void GNECalibratorFlow::writeFlow (OutputDevice & device)
write Flow values into a XML
Definition at line 128 of file GNECalibratorFlow.cpp.
References OutputDevice::closeTag(), GNEAttributeCarrier::getTag(), GNE_CALIBRATORFLOW_PERIOD, GNE_CALIBRATORFLOW_PROBABILITY, GNE_CALIBRATORFLOW_VEHSPERHOUR, myArrivalLane, myArrivalPos, myArrivalPosLat, myArrivalSpeed, myBegin, myColor, myContainerNumber, myDepartLane, myDepartPos, myDepartPosLat, myDepartSpeed, myEnd, myFlowType, myLine, myNumber, myPeriod, myPersonNumber, myProbability, myReroute, myRoute, myVehicleType, myVehsPerHour, OutputDevice::openTag(), SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_END, SUMO_ATTR_LINE, SUMO_ATTR_NUMBER, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PROB, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_TYPE, SUMO_ATTR_VEHSPERHOUR, and OutputDevice::writeAttr().
Field Documentation
APPROVED
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 269 of file GNEAttributeCarrier.h.
GUESSED
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 263 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::setAttribute(), and GNEEdge::setAttribute().
INVALID_POSITION
const double GNEAttributeCarrier::INVALID_POSITION = -1000000 static inherited
default value for invalid positions (used by POIs and Polygons)
Definition at line 272 of file GNEAttributeCarrier.h.
LOADED
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 260 of file GNEAttributeCarrier.h.
MODIFIED
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 266 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::markAsModified(), and GNEConnectorFrame::onCmdClearSelectedConnections().
myArrivalLane
std::string GNECalibratorFlow::myArrivalLane protected
arrival lane
Definition at line 141 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myArrivalPos
std::string GNECalibratorFlow::myArrivalPos protected
arrival pos
Definition at line 144 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myArrivalPosLat
std::string GNECalibratorFlow::myArrivalPosLat protected
Definition at line 165 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myArrivalSpeed
std::string GNECalibratorFlow::myArrivalSpeed protected
arrival speed
Definition at line 147 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myBegin
double GNECalibratorFlow::myBegin protected
Definition at line 170 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myCalibratorParent
GNECalibrator* GNECalibratorFlow::myCalibratorParent protected
pointer to calibrator parent
Definition at line 117 of file GNECalibratorFlow.h.
Referenced by getCalibratorParent(), isValid(), and setAttribute().
myColor
RGBColor GNECalibratorFlow::myColor protected
color of flow
Definition at line 129 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myContainerNumber
int GNECalibratorFlow::myContainerNumber protected
number of container
Definition at line 156 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myDepartLane
std::string GNECalibratorFlow::myDepartLane protected
depart lane
Definition at line 132 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myDepartPos
std::string GNECalibratorFlow::myDepartPos protected
depart position
Definition at line 135 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myDepartPosLat
std::string GNECalibratorFlow::myDepartPosLat protected
departPosLat
Definition at line 162 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myDepartSpeed
std::string GNECalibratorFlow::myDepartSpeed protected
depart speed
Definition at line 138 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myEnd
double GNECalibratorFlow::myEnd protected
time step end
Definition at line 173 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myFlowID
std::string GNECalibratorFlow::myFlowID protected
ID of flow.
Definition at line 120 of file GNECalibratorFlow.h.
Referenced by getAttribute(), and setAttribute().
myFlowType
TypeOfFlow GNECalibratorFlow::myFlowType protected
type of flow
Definition at line 189 of file GNECalibratorFlow.h.
Referenced by getFlowType(), setFlowType(), and writeFlow().
myLine
std::string GNECalibratorFlow::myLine protected
line of bus/container stop
Definition at line 150 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myNumber
int GNECalibratorFlow::myNumber protected
number of flow
Definition at line 185 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myPeriod
double GNECalibratorFlow::myPeriod protected
period
Definition at line 179 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myPersonNumber
int GNECalibratorFlow::myPersonNumber protected
number of person
Definition at line 153 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myProbability
double GNECalibratorFlow::myProbability protected
probability
Definition at line 182 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myReroute
bool GNECalibratorFlow::myReroute protected
reroute
Definition at line 159 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myRoute
GNECalibratorRoute* GNECalibratorFlow::myRoute protected
route in which this flow is used
Definition at line 126 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myVehicleType
GNECalibratorVehicleType* GNECalibratorFlow::myVehicleType protected
type of flow
Definition at line 123 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
myVehsPerHour
double GNECalibratorFlow::myVehsPerHour protected
flows per hour
Definition at line 176 of file GNECalibratorFlow.h.
Referenced by getAttribute(), setAttribute(), and writeFlow().
The documentation for this class was generated from the following files:
GNECalibratorFlow.h
GNECalibratorFlow.cpp