SUMO - Simulation of Urban MObility: ROJTRFrame Class Reference
ROJTRFrame Class Reference
Sets and checks options for jtr-routing.
#include <ROJTRFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid for usage within jtrrouter.
static void fillOptions ()
Inserts options used by jtrrouter into the OptionsCont-singleton.
Detailed Description
Sets and checks options for jtr-routing.
Definition at line 41 of file ROJTRFrame.h.
Member Function Documentation
checkOptions()
bool ROJTRFrame::checkOptions () static
Checks set options from the OptionsCont-singleton for being valid for usage within jtrrouter.
Returns
Whether all needed options are set
Todo:
probably, more things should be checked...
Definition at line 98 of file ROJTRFrame.cpp.
References SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, ROFrame::checkOptions(), SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), SUMOVehicleParameter::parseArrivalLane(), SUMOVehicleParameter::parseArrivalPos(), SUMOVehicleParameter::parseArrivalSpeed(), SUMOVehicleParameter::parseDepartLane(), SUMOVehicleParameter::parseDepartPos(), SUMOVehicleParameter::parseDepartSpeed(), and WRITE_ERROR.
Referenced by main().
fillOptions()
void ROJTRFrame::fillOptions () static
Inserts options used by jtrrouter into the OptionsCont-singleton.
As jtrrouter shares several options with other routing appplications, the insertion of these is done via a call to ROFrame::fillOptions.
jtrrouer-specific options are added afterwards.
Definition at line 51 of file ROJTRFrame.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), ROFrame::fillOptions(), OptionsCont::getOptions(), and RandHelper::insertRandOptions().
Referenced by main().
The documentation for this class was generated from the following files:
ROJTRFrame.h
ROJTRFrame.cpp