SUMO - Simulation of Urban MObility: AGChild Class Reference
AGChild Class Reference
#include <AGChild.h>
Public Member Functions
AGChild (int age)
bool allocateASchool (std::list< AGSchool > *schools, AGPosition housePos)
virtual bool decide (double probability) const
Lets the person make a decision.
virtual int getAge () const
Provides the age of the person.
int getSchoolClosing () const
AGPosition getSchoolLocation () const
int getSchoolOpening () const
bool haveASchool () const
bool leaveSchool ()
void print () const
Puts out a summary of the class properties.
bool setSchool (AGSchool *school)
Protected Attributes
int age
Private Attributes
AGSchool * school
Detailed Description
Definition at line 47 of file AGChild.h.
Constructor & Destructor Documentation
AGChild()
AGChild::AGChild (int age) inline
Definition at line 49 of file AGChild.h.
References allocateASchool(), getSchoolClosing(), getSchoolLocation(), getSchoolOpening(), haveASchool(), leaveSchool(), print(), school, and setSchool().
Member Function Documentation
allocateASchool()
bool AGChild::allocateASchool (std::list< AGSchool > * schools, AGPosition housePos)
Parameters
schools school vector from City object
housepos Position of the households habitation
Returns
if a school was found corresponding to the child's age.
Definition at line 64 of file AGChild.cpp.
References AGPerson::age, AGPosition::distanceTo(), and setSchool().
Referenced by AGChild().
decide()
bool AGPerson::decide (double probability) const virtual inherited
Lets the person make a decision.
The higher the degree of belief is, the more likely this method returns true.
Parameters
[in] degreeOfBelief how strong the person beliefs the proposition
Returns
whether the person agrees with the proposition
Definition at line 62 of file AGPerson.cpp.
References RandHelper::rand().
Referenced by AGAdult::tryToWork().
getAge()
int AGPerson::getAge () const virtual inherited
Provides the age of the person.
Returns
the age in years
Definition at line 56 of file AGPerson.cpp.
References AGPerson::age.
getSchoolClosing()
int AGChild::getSchoolClosing () const
Definition at line 102 of file AGChild.cpp.
References AGSchool::getClosingHour(), and school.
Referenced by AGChild().
getSchoolLocation()
AGPosition AGChild::getSchoolLocation () const
Definition at line 97 of file AGChild.cpp.
References AGSchool::getPosition(), and school.
Referenced by AGChild().
getSchoolOpening()
int AGChild::getSchoolOpening () const
Definition at line 107 of file AGChild.cpp.
References AGSchool::getOpeningHour(), and school.
Referenced by AGChild().
haveASchool()
bool AGChild::haveASchool () const
Definition at line 92 of file AGChild.cpp.
References school.
Referenced by AGChild().
leaveSchool()
bool AGChild::leaveSchool ()
Returns
if the child is now without any school
Definition at line 82 of file AGChild.cpp.
References AGSchool::removeChild(), and school.
Referenced by AGChild().
print()
void AGChild::print () const virtual
Puts out a summary of the class properties.
Reimplemented from AGPerson.
Definition at line 47 of file AGChild.cpp.
References AGPerson::age, and school.
Referenced by AGChild().
setSchool()
bool AGChild::setSchool (AGSchool * school)
Definition at line 52 of file AGChild.cpp.
References AGSchool::addNewChild(), and school.
Referenced by AGChild(), and allocateASchool().
Field Documentation
age
int AGPerson::age protected inherited
Definition at line 71 of file AGPerson.h.
Referenced by allocateASchool(), AGPerson::getAge(), print(), AGAdult::print(), and AGPerson::print().
school
AGSchool* AGChild::school private
Definition at line 70 of file AGChild.h.
Referenced by AGChild(), getSchoolClosing(), getSchoolLocation(), getSchoolOpening(), haveASchool(), leaveSchool(), print(), and setSchool().
The documentation for this class was generated from the following files:
AGChild.h
AGChild.cpp