SUMO - Simulation of Urban MObility: GNEEdge Class Reference
GNEEdge Class Reference
A road/street connecting two junctions (netedit-version)
#include <GNEEdge.h>
Public Types
typedef std::vector< GNEConnection * > ConnectionVector
Definition of the connection's vector.
typedef std::vector< GNELane * > LaneVector
Definition of the lane's vector.
Public Member Functions
void addAdditionalChild (GNEAdditional *additional)
add additional child to this edge
void addAdditionalParent (GNEAdditional *additional)
add additional child to this edge
void clearGNEConnections ()
clear current connections
void commitShapeChange (const PositionVector &oldShape, GNEUndoList *undoList)
commit geometry changes in the attributes of an element after use of changeShapeGeometry(...)
void copyTemplate (GNEEdge *tpl, GNEUndoList *undolist)
copy edge attributes from tpl
void decRef (const std::string &debugMsg="")
Decrease reference.
void deleteGeometryPoint (const Position &pos, bool allowUndo=true)
delete the geometry point closest to the given pos
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
const std::vector< GNEAdditional * > & getAdditionalChilds () const
return vector of additionals that have as Parent this edge (For example, Calibrators)
const std::vector< GNEAdditional * > & getAdditionalParents () const
return vector of additionals that have as Parameter this edge (For example, Rerouters)
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
Boundary getBoundary () const
Returns the street's geometry.
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
double getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleClass getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleShape getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
RGBColor getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< double > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
const std::vector< GNEConnection * > & getGNEConnections ()
returns a reference to the GNEConnection vector
std::vector< GNECrossing * > getGNECrossings ()
get GNECrossings vinculated with this Edge
GNEJunction * getGNEJunctionDestiny () const
returns the destination-junction
GNEJunction * getGNEJunctionSource () const
returns the source-junction
const GUIGlObject * getGUIGLObject () const
get const pointer to GUIGlObject vinculated with this Attribute Carrier
GUIGlObject * getGUIGLObject ()
get pointer to GUIGlObject vinculated with this Attribute Carrier
GUIIcon getGUIIcon () const
get GUI icon assigned to this object
FXIcon * getIcon () const
get FXIcon assigned to this object
const std::string getID () const
function to support debugging
std::set< GUIGlID > getLaneGlIDs ()
returns GLIDs of all lanes
const std::vector< GNELane * > & getLanes ()
returns a reference to the lane vector
NBEdge * getNBEdge ()
returns the internal NBEdge
GNENet * getNet () const
get Net in which this element is placed
GNEEdge * getOppositeEdge () const
get opposite edge
int getRouteProbeRelativePosition (GNERouteProbe *routeProbe) const
obtain relative positions of RouteProbes
Position getSplitPos (const Position &clickPos)
SumoXMLTag getTag () const
get XML Tag assigned to this object
int getVaporizerRelativePosition (GNEVaporizer *vaporizer) const
obtain relative positions of Vaporizer
int getVertexIndex (const Position &pos, bool createIfNoExist=true)
return index of a vertex of shape, or of a new vertex if position is over an shape's edge
int getVertexIndex (const double offset, bool createIfNoExist=true)
return index of a vertex of shape, or of a new vertex if position is over an shape's edge
GNEEdge (NBEdge &nbe, GNENet *net, bool wasSplit=false, bool loaded=false)
Constructor.
bool hasRestrictedLane (SUMOVehicleClass vclass) const
check if edge has a restricted lane
void incRef (const std::string &debugMsg="")
Increarse reference.
bool isInverted () const
return true if edge is inverted (Angle between origin and destiny junction is -PI/2 <= angle < PI/2
void moveEntireShape (const PositionVector &oldShape, const Position &offset)
move entire shape without commiting change
int moveVertexShape (const int index, const Position &oldPos, const Position &offset)
change position of a vertex of shape without commiting change
template<>
int parse (const std::string &string)
template<>
double parse (const std::string &string)
template<>
bool parse (const std::string &string)
template<>
std::string parse (const std::string &string)
template<>
SUMOVehicleClass parse (const std::string &string)
template<>
RGBColor parse (const std::string &string)
template<>
SUMOVehicleShape parse (const std::string &string)
template<>
std::vector< std::string > parse (const std::string &string)
template<>
std::vector< int > parse (const std::string &string)
template<>
std::vector< double > parse (const std::string &string)
template<>
std::vector< bool > parse (const std::string &string)
void remakeGNEConnections ()
remake connections
void removeAdditionalChild (GNEAdditional *additional)
remove additional child from this edge
void removeAdditionalParent (GNEAdditional *additional)
remove additional child from this edge
void removeEdgeOfAdditionalParents (GNEUndoList *undoList, bool allowEmpty)
remove Edge of Additional Parent
void resetEndpoint (const Position &pos, GNEUndoList *undoList)
restores the endpoint to the junction position at the appropriate end
GNEConnection * retrieveGNEConnection (int fromLane, NBEdge *to, int toLane, bool createIfNoExist=true)
get GNEConnection if exist, and if not create it if create is enabled
void setEndpoint (Position pos, GNEUndoList *undoList)
makes pos the new geometry endpoint at the appropriate end
void setGeometry (PositionVector geom, bool inner)
update edge geometry and inform the lanes
void setMicrosimID (const std::string &newID)
override to also set lane ids
void setResponsible (bool newVal)
set responsibility for deleting internal strctures
void smooth (GNEUndoList *undoList)
make geometry smooth
void smoothElevation (GNEUndoList *undoList)
smooth elevation with regard to adjoining edges
PositionVector smoothShape (const PositionVector &shape, bool forElevation)
return smoothed shape
void straightenElevation (GNEUndoList *undoList)
interpolate z values linear between junctions
bool unreferenced ()
check if object ins't referenced
void updateGeometry ()
update pre-computed geometry information
void updateJunctionPosition (GNEJunction *junction, const Position &origPos)
update edge geometry after junction move
bool wasSplit ()
whether this edge was created from a split
~GNEEdge ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GNEAttributeCarrier
std::string getAttribute (SumoXMLAttr key) const
This functions has to be implemented in all GNEAttributeCarriers.
std::string getAttributeForSelection (SumoXMLAttr key) const
method for getting the attribute in the context of object selection
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
bool isValid (SumoXMLAttr key, const std::string &value)
inherited from GUIGlObject
virtual const std::string & getParentName () const
Returns the name of the parent object.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static const std::vector< SumoXMLTag > & allowedAdditionalTags ()
get all editable for tag additional elements
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedNetElementsTags ()
get all editable for tag net elements
static const std::vector< SumoXMLTag > & allowedShapeTags ()
get all editable for tag shape elements
static std::vector< SumoXMLTag > allowedTags ()
get all editable for tag elements of all types
static bool canBlockMovement (SumoXMLTag tag)
return true if element tag can block their movement
static bool canBlockShape (SumoXMLTag tag)
return true if element tag can block their shape
static bool canOpenDialog (SumoXMLTag tag)
return true if element tag can open a values editor
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
static std::string getAttributeType (SumoXMLTag tag, SumoXMLAttr attr)
get type of attribute
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if an element with certain tag has a certain attribute
static bool hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
check if attribute of an element has a default avlue
static bool isBool (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool for a certain tag
static bool isColor (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type color for a certain tag
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFilename (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a filename
static bool isFloat (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNonEditable (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is non editable
static bool isNumerical (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical (int or float)
static bool isPositive (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is only Positive (i.e. cannot take negative values)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isProbability (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is a probability (i.e. oly can values between [0, 1])
static bool isString (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type string
static bool isTime (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is time
static bool isUnique (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
static bool isValidFilename (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
static bool isVClass (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a list of Vehicle Classes
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
template<typename T >
static T parseAttributeFromXML (const SUMOSAXAttributes &attrs, const std::string &objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool &abort, bool report=true)
Parse attribute from XML and show warnings if there are problems parsing it.
function used to parse GNEEdges and GNELanes
static bool checkGNEEdgesValid (GNENet *net, const std::string &value, bool report)
check if a list of edge IDs is valid
static bool checkGNELanesValid (GNENet *net, const std::string &value, bool report)
check if a list of Lane IDs is valid
static std::vector< GNEEdge * > parseGNEEdges (GNENet *net, const std::string &value)
parse string into vector of GNEEdges
static std::string parseGNEEdges (const std::vector< GNEEdge *> &edges)
parse vector of GNEEdges into string
static std::vector< GNELane * > parseGNELanes (GNENet *net, const std::string &value)
parse string into vector of GNELanes
static std::string parseGNELanes (const std::vector< GNELane *> &lanes)
parse vector of GNELanes into string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const GUIGlID INVALID_ID = 0
static const double INVALID_POSITION = -1000000
default value for invalid positions (used by POIs and Polygons)
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
static const double SNAP_RADIUS = SUMO_const_halfLaneWidth
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
std::vector< GNEAdditional * > myAdditionalChilds
list of Additional Childs of this NetElement
std::vector< GNEAdditional * > myAdditionalParents
list of Additional parents of this NetElement
bool myAmResponsible
whether we are responsible for deleting myNBNode
std::string myConnectionStatus
modification status of the connections
ConnectionVector myGNEConnections
vector with the connections of this edge
GNEJunction * myGNEJunctionDestiny
pointer to GNEJunction destiny
GNEJunction * myGNEJunctionSource
pointer to GNEJunction source
LaneVector myLanes
vectgor with the lanes of this edge
NBEdge & myNBEdge
the underlying NBEdge
GNENet * myNet
the net to inform about updates
PositionVector myOrigShape
restore point for undo
bool myWasSplit
whether this edge was created from a split
Private Member Functions
void addConnection (NBEdge::Connection nbCon, bool selectAfterCreation=false)
adds a connection
void addLane (GNELane *lane, const NBEdge::Lane &laneAttrs)
increase number of lanes by one use the given attributes and restore the GNELane
GNEEdge (const GNEEdge &s)=delete
invalidated copy constructor
GNEEdge & operator= (const GNEEdge &s)=delete
invalidated assignment operator
void removeConnection (NBEdge::Connection nbCon)
removes a connection
void removeEdgeFromCrossings (GNEJunction *junction, GNEUndoList *undoList)
remove crossing of junction
void removeLane (GNELane *lane)
the number of lanes by one. argument is only used to increase robustness (assertions)
void setAttribute (SumoXMLAttr key, const std::string &value)
set attribute after validation
void setNumLanes (int numLanes, GNEUndoList *undoList)
changes the number of lanes. When reducing the number of lanes, higher-numbered lanes are removed first. When increasing the number of lanes, the last known attributes for a lane with this number are restored. If none are found the attributes for the leftmost lane are copied
Friends
class GNEChange_Connection
class GNEChange_Lane
Friend class.
Detailed Description
A road/street connecting two junctions (netedit-version)
See also
MSEdge
Definition at line 56 of file GNEEdge.h.
Member Typedef Documentation
ConnectionVector
typedef std::vector<GNEConnection*> GNEEdge::ConnectionVector
Definition of the connection's vector.
Definition at line 67 of file GNEEdge.h.
LaneVector
typedef std::vector<GNELane*> GNEEdge::LaneVector
Definition of the lane's vector.
Definition at line 64 of file GNEEdge.h.
Constructor & Destructor Documentation
GNEEdge() [1/2]
GNEEdge::GNEEdge (NBEdge & nbe, GNENet * net, bool wasSplit = false, bool loaded = false)
Constructor.
Parameters
[in] nbe The represented edge
[in] net The net to inform about gui updates
[in] loaded Whether the edge was loaded from a file
Definition at line 70 of file GNEEdge.cpp.
References NBEdge::getNumLanes(), myLanes, and myNBEdge.
~GNEEdge()
GNEEdge::~GNEEdge ()
Destructor.
Definition at line 94 of file GNEEdge.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), myAmResponsible, myGNEConnections, myLanes, myNBEdge, toString(), and WRITE_WARNING.
GNEEdge() [2/2]
GNEEdge::GNEEdge (const GNEEdge & s) private delete
invalidated copy constructor
Member Function Documentation
addAdditionalChild()
void GNENetElement::addAdditionalChild (GNEAdditional * additional) inherited
add additional child to this edge
Definition at line 85 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalChilds, toString(), and GNENetElement::updateGeometry().
Referenced by GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNEChange_Additional::redo(), and GNEChange_Additional::undo().
addAdditionalParent()
void GNENetElement::addAdditionalParent (GNEAdditional * additional) inherited
add additional child to this edge
Definition at line 58 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalParents, toString(), and GNENetElement::updateGeometry().
addConnection()
void GNEEdge::addConnection (NBEdge::Connection nbCon, bool selectAfterCreation = false) private
adds a connection
Definition at line 1159 of file GNEEdge.cpp.
References NBEdge::Connection::contPos, GUISelectedStorage::deselect(), NBEdge::Connection::fromLane, GUIGlObject::getGlID(), gSelected, NBEdge::Connection::keepClear, NBEdge::L2L_USER, NBEdge::Connection::mayDefinitelyPass, myGNEConnections, myNBEdge, GNENetElement::myNet, GNENet::refreshElement(), retrieveGNEConnection(), NBEdge::setConnection(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, GNEConnection::updateGeometry(), and NBEdge::Connection::visibility.
Referenced by GNEChange_Connection::redo(), and GNEChange_Connection::undo().
addLane()
void GNEEdge::addLane (GNELane * lane, const NBEdge::Lane & laneAttrs) private
increase number of lanes by one use the given attributes and restore the GNELane
Definition at line 1071 of file GNEEdge.cpp.
References NBEdge::addLane(), NBEdge::Lane::endOffset, GNEJunction::getGNEEdges(), GNELane::getIndex(), NBEdge::getNumLanes(), GNEReferenceCounter::incRef(), myGNEJunctionDestiny, myGNEJunctionSource, myLanes, myNBEdge, NBEdge::Lane::permissions, NBEdge::Lane::preferred, remakeGNEConnections(), NBEdge::setEndOffset(), NBEdge::setLaneWidth(), NBEdge::setPermissions(), NBEdge::setPreferredVehicleClass(), NBEdge::setSpeed(), NBEdge::Lane::speed, updateGeometry(), and NBEdge::Lane::width.
Referenced by GNEChange_Lane::redo(), and GNEChange_Lane::undo().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
allowedAdditionalTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedAdditionalTags () static inherited
get all editable for tag additional elements
Definition at line 621 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedAttributes()
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 287 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, OptionsCont::getOptions(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, NODEFAULTVALUE, SUMO_ATTR_ACCEL, SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPE, toString(), NBEdge::UNSPECIFIED_CONTPOS, NBEdge::UNSPECIFIED_SPEED, and NBEdge::UNSPECIFIED_VISIBILITY_DISTANCE.
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getDefaultValue(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNESelectorFrame::onCmdSelMBAttribute(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedNetElementsTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedNetElementsTags () static inherited
get all editable for tag net elements
Definition at line 607 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedShapeTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedShapeTags () static inherited
get all editable for tag shape elements
Definition at line 644 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedShapeTags, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEPolygonFrame::GNEPolygonFrame(), GNEPolygonFrame::onCmdSelectShape(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedTags()
std::vector< SumoXMLTag > GNEAttributeCarrier::allowedTags () static inherited
get all editable for tag elements of all types
Definition at line 596 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedNetElementsTags(), and GNEAttributeCarrier::allowedShapeTags().
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
canBlockMovement()
bool GNEAttributeCarrier::canBlockMovement (SumoXMLTag tag) static inherited
return true if element tag can block their movement
Definition at line 656 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockMovementTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::onCmdSelectAdditional(), GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canBlockShape()
bool GNEAttributeCarrier::canBlockShape (SumoXMLTag tag) static inherited
return true if element tag can block their shape
Definition at line 678 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockShapeTags, and SUMO_TAG_POLY.
Referenced by GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canOpenDialog()
bool GNEAttributeCarrier::canOpenDialog (SumoXMLTag tag) static inherited
return true if element tag can open a values editor
Definition at line 688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myDialogTags, SUMO_TAG_CALIBRATOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditional::getPopUpMenu(), GNEViewNet::onCmdOpenAdditionalDialog(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canParse()
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 230 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
checkGNEEdgesValid()
bool GNEAttributeCarrier::checkGNEEdgesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of edge IDs is valid
value string with a list of edges report enable or disable show warning if edges aren't valid
Definition at line 1712 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge(), SUMO_ATTR_EDGES, SUMO_TAG_EDGE, toString(), and WRITE_WARNING.
Referenced by GNECalibratorRoute::isValid(), GNECrossing::isValid(), GNERerouter::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), and GNEAttributeCarrier::parseAttributeFromXML().
checkGNELanesValid()
bool GNEAttributeCarrier::checkGNELanesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of Lane IDs is valid
value string with a list of lanes report enable or disable show warning if lanes aren't valid
Definition at line 1730 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane(), SUMO_ATTR_LANES, SUMO_TAG_LANE, toString(), and WRITE_WARNING.
Referenced by GNEVariableSpeedSign::isValid(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), and GNEAttributeCarrier::parseAttributeFromXML().
clearGNEConnections()
void GNEEdge::clearGNEConnections ()
clear current connections
Definition at line 519 of file GNEEdge.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), myGNEConnections, toString(), and WRITE_WARNING.
Referenced by setAttribute().
commitShapeChange()
void GNEEdge::commitShapeChange (const PositionVector & oldShape, GNEUndoList * undoList)
commit geometry changes in the attributes of an element after use of changeShapeGeometry(...)
Parameters
[in] oldShape the old shape of polygon
[in] undoList The undoList on which to register changes
Definition at line 218 of file GNEEdge.cpp.
References GNEJunction::BUBBLE_RADIUS, GUIVisualizationSizeSettings::exaggeration, NBEdge::getGeometry(), NBEdge::getInnerGeometry(), GNEAttributeCarrier::getTag(), GNENet::getViewNet(), GUISUMOAbstractView::getVisualisationSettings(), GNEAttributeCarrier::GNEChange_Attribute, GUIVisualizationSettings::junctionSize, myNBEdge, GNENetElement::myNet, GNEUndoList::p_add(), GNEUndoList::p_begin(), GNEUndoList::p_end(), PositionVector::removeClosest(), PositionVector::removeDoublePoints(), setGeometry(), SNAP_RADIUS, SUMO_ATTR_SHAPE, toString(), and WRITE_WARNING.
Referenced by GNEViewNet::onLeftBtnRelease().
copyTemplate()
void GNEEdge::copyTemplate (GNEEdge * tpl, GNEUndoList * undolist)
copy edge attributes from tpl
Definition at line 621 of file GNEEdge.cpp.
References getAttribute(), myLanes, GNEUndoList::p_begin(), GNEUndoList::p_end(), setAttribute(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TYPE, and SUMO_ATTR_WIDTH.
Referenced by GNEInspectorFrame::onCmdCopyTemplate().
decRef()
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Decrease reference.
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), removeConnection(), removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
deleteGeometryPoint()
void GNEEdge::deleteGeometryPoint (const Position & pos, bool allowUndo = true)
delete the geometry point closest to the given pos
Definition at line 245 of file GNEEdge.cpp.
References NBEdge::getInnerGeometry(), GNEViewNet::getUndoList(), GNENet::getViewNet(), PositionVector::indexOfClosest(), myNBEdge, GNENetElement::myNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), setAttribute(), setGeometry(), SUMO_ATTR_SHAPE, and toString().
Referenced by GNEDeleteFrame::removeAttributeCarrier(), and setEndpoint().
discreteChoices()
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 1233 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_GUISHAPE, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_VCLASS, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_VTYPE, SumoVehicleClassStrings, SumoVehicleShapeStrings, TLTYPE_INVALID, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
discreteCombinableChoices()
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 1290 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
drawGL()
void GNEEdge::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GNENetElement.
Definition at line 335 of file GNEEdge.cpp.
References Position::add(), GUIVisualizationTextSettings::color, GLHelper::drawFilledCircle(), GUIGlObject::drawName(), GLHelper::drawText(), GUIVisualizationSettings::edgeName, GUIPropertySchemeStorage< T >::getActive(), NBEdge::getGeometry(), GUIGlObject::getGlID(), GUIPropertySchemeStorage< T >::getSchemes(), GNELane::getShape(), NBEdge::getStreetName(), GUIGlObject::getType(), GLO_JUNCTION, GLO_MAX, gSelected, GUISelectedStorage::isSelected(), GUIVisualizationSettings::junctionColorer, GUIVisualizationSettings::laneColorer, GUIVisualizationSettings::laneWidthExaggeration, PositionVector::length(), MIN2(), Position::mul(), myGNEConnections, myLanes, myNBEdge, PositionVector::positionAtOffset(), PositionVector::rotationDegreeAtOffset(), GUIVisualizationSettings::scale, GNENet::selectionColor, GLHelper::setColor(), GUIVisualizationTextSettings::show, GUIVisualizationTextSettings::size, SNAP_RADIUS, GUIVisualizationSettings::streetName, Position::x(), and Position::y().
drawGLAdditional()
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 153 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GNERouteProbe::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
getAdditionalChilds()
const std::vector< GNEAdditional * > & GNENetElement::getAdditionalChilds () const inherited
return vector of additionals that have as Parent this edge (For example, Calibrators)
Definition at line 118 of file GNENetElement.cpp.
References GNENetElement::myAdditionalChilds.
Referenced by GNENet::deleteEdge(), GNENet::deleteLane(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::replaceIncomingEdge(), GNEInspectorFrame::showAttributeCarrierChilds(), and GNEDeleteFrame::showChildsOfMarkedAttributeCarrier().
getAdditionalParents()
const std::vector< GNEAdditional * > & GNENetElement::getAdditionalParents () const inherited
return vector of additionals that have as Parameter this edge (For example, Rerouters)
Definition at line 112 of file GNENetElement.cpp.
References GNENetElement::myAdditionalParents.
Referenced by GNEDeleteFrame::removeAttributeCarrier(), GNENet::replaceIncomingEdge(), and GNEDeleteFrame::showChildsOfMarkedAttributeCarrier().
getAttribute()
std::string GNEEdge::getAttribute (SumoXMLAttr key) const virtual
This functions has to be implemented in all GNEAttributeCarriers.
Implements GNENetElement.
Definition at line 671 of file GNEEdge.cpp.
References NBEdge::getEndOffset(), NBEdge::getFinalLength(), NBEdge::getGeometry(), NBEdge::getInnerGeometry(), NBEdge::getLaneSpreadFunction(), NBEdge::getLaneWidth(), GUIGlObject::getMicrosimID(), NBEdge::getNumLanes(), NBEdge::getPermissions(), GNEJunction::getPositionInView(), NBEdge::getPriority(), NBEdge::getSpeed(), NBEdge::getStreetName(), GNEAttributeCarrier::getTag(), NBEdge::getTypeID(), getVehicleClassNames(), GNE_ATTR_MODIFICATION_STATUS, GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, NBEdge::hasLaneSpecificEndOffset(), NBEdge::hasLaneSpecificPermissions(), NBEdge::hasLaneSpecificSpeed(), NBEdge::hasLaneSpecificWidth(), invertPermissions(), myConnectionStatus, myGNEJunctionDestiny, myGNEJunctionSource, myNBEdge, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, toString(), and NBEdge::UNSPECIFIED_WIDTH.
Referenced by copyTemplate(), getAttributeForSelection(), GNENet::remapEdge(), GNENet::replaceIncomingEdge(), GNENet::replaceJunctionByGeometry(), and setAttribute().
getAttributeForSelection()
std::string GNEEdge::getAttributeForSelection (SumoXMLAttr key) const virtual
method for getting the attribute in the context of object selection
Reimplemented from GNEAttributeCarrier.
Definition at line 738 of file GNEEdge.cpp.
References getAttribute(), getVehicleClassNames(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, and SVCAll.
getAttributeType()
std::string GNEAttributeCarrier::getAttributeType (SumoXMLTag tag, SumoXMLAttr attr) static inherited
get type of attribute
Definition at line 247 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), and toString().
Referenced by GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttrs()
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 231 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getBoundary()
Boundary GNEEdge::getBoundary () const
Returns the street's geometry.
Definition at line 277 of file GNEEdge.cpp.
References Boundary::add(), Boundary::grow(), and myLanes.
Referenced by getCenteringBoundary(), and GNENet::registerEdge().
getCenteringBoundary()
Boundary GNEEdge::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GNENetElement.
Definition at line 294 of file GNEEdge.cpp.
References getBoundary(), and Boundary::grow().
getDefaultValue() [1/12]
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getDefaultValue() [2/12]
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1580 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [3/12]
template<> double GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1592 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [4/12]
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1604 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [5/12]
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1616 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [6/12]
template<> SUMOVehicleClass GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1628 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1640 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [8/12]
template<> RGBColor GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1652 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [9/12]
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1664 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [10/12]
template<> std::vector<double> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1676 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [12/12]
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1700 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefinition()
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 1296 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ACCEL, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEO, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
Referenced by GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getGNEConnections()
const std::vector< GNEConnection * > & GNEEdge::getGNEConnections ()
returns a reference to the GNEConnection vector
Definition at line 659 of file GNEEdge.cpp.
References myGNEConnections.
Referenced by GNELane::getGNEOutcomingConnections().
getGNECrossings()
std::vector< GNECrossing * > GNEEdge::getGNECrossings ()
get GNECrossings vinculated with this Edge
Definition at line 574 of file GNEEdge.cpp.
References GNEJunction::getGNECrossings(), myGNEJunctionDestiny, and myGNEJunctionSource.
Referenced by GNENet::remapEdge().
getGNEJunctionDestiny()
GNEJunction * GNEEdge::getGNEJunctionDestiny () const
returns the destination-junction
Definition at line 323 of file GNEEdge.cpp.
References myGNEJunctionDestiny.
Referenced by GNENet::addReversedEdge(), GNEViewNet::begingMoveSelection(), GNENet::deleteConnection(), GNENet::deleteEdge(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNELane::drawGL(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNEConnectorFrame::initTargets(), GNEAdditional::isRouteValid(), GNENet::joinSelectedJunctions(), GNENet::mergeJunctions(), GNENet::registerEdge(), GNENet::replaceIncomingEdge(), and GNENet::reverseEdge().
getGNEJunctionSource()
GNEJunction * GNEEdge::getGNEJunctionSource () const
returns the source-junction
Definition at line 317 of file GNEEdge.cpp.
References myGNEJunctionSource.
Referenced by GNENet::addReversedEdge(), GNEViewNet::begingMoveSelection(), GNENet::deleteEdge(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNELane::getGNEIncomingConnections(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNENet::joinSelectedJunctions(), GNENet::mergeJunctions(), GNENet::registerEdge(), GNENet::reverseEdge(), and GNENet::splitEdge().
getGUIGLObject() [1/2]
const GUIGlObject * GNEAttributeCarrier::getGUIGLObject () const inherited
get const pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to const GUIGlObject
Definition at line 207 of file GNEAttributeCarrier.cpp.
Referenced by GNEShape::drawLockIcon(), GNENet::insertShape(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::removePolygonForEditShapes(), GNENet::removeShape(), GNENet::retrieveAttributeCarriers(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getGUIGLObject() [2/2]
GUIGlObject * GNEAttributeCarrier::getGUIGLObject () inherited
get pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to GUIGlObject
Definition at line 219 of file GNEAttributeCarrier.cpp.
getGUIIcon()
GUIIcon GNEAttributeCarrier::getGUIIcon () const inherited
get GUI icon assigned to this object
Definition at line 201 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myIcon.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
getHigherNumberOfAttributes()
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 1563 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedNetElementsTags(), GNEAttributeCarrier::allowedShapeTags(), MAX2(), and GNEAttributeCarrier::myMaxNumAttribute.
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getIcon()
FXIcon * GNEAttributeCarrier::getIcon () const inherited
get FXIcon assigned to this object
Definition at line 195 of file GNEAttributeCarrier.cpp.
References GUIIconSubSys::getIcon(), and GNEAttributeCarrier::myIcon.
Referenced by GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNEAdditional::getPopUpMenu(), GNEDeleteFrame::markAttributeCarrier(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEDeleteFrame::updateCurrentLabel(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getID()
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 241 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNECrossingFrame::addCrossing(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), GNEAdditional::addLaneChild(), GNEJunction::addOutgoingGNEEdge(), GNENet::addPOI(), GNEPolygonFrame::addPOILane(), GNENet::addReversedEdge(), GNELane::addShapeChild(), GNEAdditionalHandler::buildRerouterInterval(), GNENet::changeCalibratorFlowID(), GNENet::changeCalibratorRouteID(), GNENet::changeCalibratorVehicleTypeID(), GNENet::changeShapeID(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECalibratorFlow::getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNECalibrator::getAttribute(), GNEJunction::getAttribute(), GNEAdditionalHandler::getPosition(), GNECalibratorRoute::GNECalibratorRoute(), GNENet::insertAdditional(), GNENet::insertCalibratorFlow(), GNENet::insertCalibratorRoute(), GNENet::insertCalibratorVehicleType(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNEDeleteFrame::markAttributeCarrier(), GNECrossingFrame::crossingParameters::markEdge(), GNERerouterDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdSetVariable(), GNECalibratorRouteDialog::onCmdSetVariable(), GNEViewNet::onCmdTransformPOI(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEPolygonFrame::processClick(), GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_TLS::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_CalibratorItem::redo(), GNEChange_RerouterItem::redo(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), removeConnection(), GNEAdditional::removeEdgeChild(), GNEJunction::removeEdgeFromCrossings(), removeEdgeOfAdditionalParents(), GNEJunction::removeIncomingGNEEdge(), removeLane(), GNEAdditional::removeLaneChild(), GNELane::removeLaneOfAdditionalParents(), GNEJunction::removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceIncomingEdge(), GNENet::retrieveEdge(), retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNENet::reverseEdge(), GNEInspectorFrame::NeteditParameters::show(), smooth(), smoothElevation(), smoothShape(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_TLS::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_CalibratorItem::undo(), GNEChange_RerouterItem::undo(), GNENet::updateAdditionalID(), GNECalibratorRouteDialog::updateCalibratorRouteValues(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNECalibrator::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), GNEPOILane::writeShape(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEJunction::~GNEJunction().
getLaneGlIDs()
std::set< GUIGlID > GNEEdge::getLaneGlIDs ()
returns GLIDs of all lanes
Definition at line 643 of file GNEEdge.cpp.
References myLanes.
Referenced by GNEViewParent::isSelected(), and GNEConnectorFrame::onCmdSelectDeadStarts().
getLanes()
const std::vector< GNELane * > & GNEEdge::getLanes ()
returns a reference to the lane vector
Definition at line 653 of file GNEEdge.cpp.
References myLanes.
Referenced by GNEAdditionalFrame::addAdditional(), GNENet::addSRestrictedLane(), GNENet::deleteEdge(), GNECalibrator::getAttribute(), GNECalibrator::getParentName(), GNEAdditional::getPopUpMenu(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), GNECalibrator::getPositionInView(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::initTargets(), GNECalibrator::isValid(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::removeRestrictedLane(), GNENet::renameEdge(), GNENet::replaceIncomingEdge(), GNENet::restrictLane(), retrieveGNEConnection(), GNENet::retrieveLane(), GNECalibrator::setAttribute(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEVaporizer::updateGeometry(), GNERouteProbe::updateGeometry(), GNECalibrator::updateGeometry(), and GNECalibrator::writeAdditional().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNEPoly::getParentName(), GNERerouter::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), removeConnection(), setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNBEdge()
NBEdge * GNEEdge::getNBEdge ()
returns the internal NBEdge
Definition at line 412 of file GNEEdge.cpp.
References myNBEdge.
Referenced by GNENet::addReversedEdge(), GNENet::changeEdgeEndpoints(), GNECrossing::checkEdgeBelong(), GNENet::createEdge(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNELane::drawArrows(), GNELane::drawAsRailway(), GNELane::drawAsWaterway(), GNELane::drawDirectionIndicators(), GNELane::drawGL(), GNELane::drawLane2LaneConnections(), GNELane::drawLinkNo(), GNELane::drawMarkings(), GNELane::drawTLSLinkNo(), GNENet::duplicateLane(), GNELane::getAttribute(), GNELane::getBoundary(), GNELane::getColorValue(), GNELane::getLaneParametricLength(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), GNEConnectorFrame::getLaneStatus(), GNEConnection::getNBEdgeConnection(), GNELane::getShape(), GNELane::getSpeed(), GNEConnectorFrame::handleLaneClick(), GNEConnectorFrame::initTargets(), GNENet::insertEdge(), GNELane::isRestricted(), GNEConnection::isValid(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onLeftBtnPress(), GNEChange_Connection::redo(), GNENet::remapEdge(), GNEJunction::removeEdgeFromCrossings(), GNENet::renameEdge(), GNENet::replaceIncomingEdge(), GNENet::replaceJunctionByGeometry(), GNENet::restrictLane(), GNENet::reverseEdge(), GNEConnection::setAttribute(), GNELane::setAttribute(), GNELane::setIndex(), setMicrosimID(), GNENet::splitEdge(), GNEChange_Connection::undo(), GNEConnection::updateGeometry(), and GNEConnection::updateLinkState().
getNet()
GNENet * GNENetElement::getNet () const inherited
get Net in which this element is placed
Definition at line 52 of file GNENetElement.cpp.
References GNENetElement::myNet.
Referenced by GNEConnection::setAttribute().
getOppositeEdge()
GNEEdge * GNEEdge::getOppositeEdge () const
get opposite edge
Definition at line 329 of file GNEEdge.cpp.
References myGNEJunctionDestiny, myGNEJunctionSource, GNENetElement::myNet, and GNENet::retrieveEdge().
getParameterWindow()
GUIParameterTableWindow * GNENetElement::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 130 of file GNENetElement.cpp.
References GUIParameterTableWindow::closeBuilding(), GNENetElement::getAttribute(), GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::isUnique(), GUIParameterTableWindow::mkItem(), and toString().
getParentName()
const std::string & GNENetElement::getParentName () const virtual inherited
Returns the name of the parent object.
Returns
This object's parent id
Reimplemented from GUIGlObject.
Reimplemented in GNELane.
Definition at line 124 of file GNENetElement.cpp.
References GUIGlObject::getMicrosimID(), and GNENetElement::myNet.
getPopUpMenu()
GUIGLObjectPopupMenu * GNEEdge::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GNENetElement.
Definition at line 302 of file GNEEdge.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
getRouteProbeRelativePosition()
int GNEEdge::getRouteProbeRelativePosition (GNERouteProbe * routeProbe) const
obtain relative positions of RouteProbes
Definition at line 538 of file GNEEdge.cpp.
References GNEAttributeCarrier::getTag(), and GNENetElement::myAdditionalChilds.
Referenced by GNERouteProbe::updateGeometry().
getSplitPos()
Position GNEEdge::getSplitPos (const Position & clickPos)
Definition at line 418 of file GNEEdge.cpp.
References NBEdge::getGeometry(), PositionVector::indexOfClosest(), myNBEdge, PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset(), and SNAP_RADIUS.
Referenced by GNEViewNet::onCmdSplitEdge().
getTag()
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get XML Tag assigned to this object
Definition at line 189 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), GNEAdditional::addLaneChild(), GNEJunction::addOutgoingGNEEdge(), GNENet::addPOI(), GNELane::addShapeChild(), GNEViewNet::begingMoveSelection(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildClosingLaneReroute(), GNEAdditionalHandler::buildClosingReroute(), GNEAdditionalHandler::builDestProbReroute(), GNEAdditionalHandler::buildRerouterInterval(), GNEAdditionalHandler::buildRouteProbReroute(), GNEAdditionalHandler::buildVariableSpeedSignStep(), GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNENet::changeShapeID(), GNEDetectorE3::commitGeometryMoving(), GNEPOI::commitGeometryMoving(), GNEDetector::commitGeometryMoving(), GNEPOILane::commitGeometryMoving(), GNEStoppingPlace::commitGeometryMoving(), GNEVariableSpeedSign::commitGeometryMoving(), GNERerouter::commitGeometryMoving(), GNEJunction::commitGeometryMoving(), GNEPoly::commitShapeChange(), commitShapeChange(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteShape(), GNERouteProbReroute::getAttribute(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNEVariableSpeedSignStep::getAttribute(), GNECalibratorRoute::getAttribute(), GNECalibratorVehicleType::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECalibratorFlow::getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNECrossing::getAttribute(), GNEDetectorE3::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), GNECalibrator::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), getAttribute(), GNESelectorFrame::getMatches(), GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), getRouteProbeRelativePosition(), getVaporizerRelativePosition(), GNECalibratorRoute::GNECalibratorRoute(), GNEViewNet::hotkeyEnter(), GNENet::insertAdditional(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNERouteProbReroute::isValid(), GNEDestProbReroute::isValid(), GNEClosingLaneReroute::isValid(), GNEClosingReroute::isValid(), GNEVariableSpeedSignStep::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNERerouterInterval::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), GNECalibratorFlow::isValid(), GNEVaporizer::isValid(), GNECrossing::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNEConnection::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNELane::isValid(), GNEJunction::isValid(), isValid(), GNEAdditional::isValidAdditionalID(), GNEDeleteFrame::markAttributeCarrier(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNEViewNet::onCmdOpenAdditionalDialog(), GNEViewNet::onLeftBtnPress(), GNEAdditional::openAdditionalDialog(), GNEChange_Shape::redo(), GNEChange_Junction::redo(), GNEChange_TLS::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_Shape::redoName(), GNEChange_VariableSpeedSignItem::redoName(), GNEChange_Additional::redoName(), GNEChange_Attribute::redoName(), GNEChange_CalibratorItem::redoName(), GNEChange_RerouterItem::redoName(), GNEAdditionalFrame::removeAdditional(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), removeConnection(), GNEAdditional::removeEdgeChild(), GNEJunction::removeIncomingGNEEdge(), removeLane(), GNEAdditional::removeLaneChild(), GNEJunction::removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceInListAttribute(), retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNERouteProbReroute::setAttribute(), GNEDestProbReroute::setAttribute(), GNEClosingLaneReroute::setAttribute(), GNEClosingReroute::setAttribute(), GNEVariableSpeedSignStep::setAttribute(), GNECalibratorRoute::setAttribute(), GNECalibratorVehicleType::setAttribute(), GNERerouterInterval::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNECalibratorFlow::setAttribute(), GNEVaporizer::setAttribute(), GNECrossing::setAttribute(), GNEDetectorE3::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNEConnection::setAttribute(), GNERerouter::setAttribute(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), GNECalibrator::setAttribute(), GNELane::setAttribute(), GNEJunction::setAttribute(), setAttribute(), GNEAdditional::setBlockIconRotation(), GNEInspectorFrame::NeteditParameters::show(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_TLS::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_Shape::undoName(), GNEChange_VariableSpeedSignItem::undoName(), GNEChange_Additional::undoName(), GNEChange_Attribute::undoName(), GNEChange_CalibratorItem::undoName(), GNEChange_RerouterItem::undoName(), GNENet::updateAdditionalID(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), GNECalibratorFlow::writeFlow(), GNERerouterInterval::writeRerouterInterval(), GNECalibratorRoute::writeRoute(), GNERouteProbReroute::writeRouteProbReroute(), GNECalibratorVehicleType::writeVehicleType(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_Shape::~GNEChange_Shape(), and GNEChange_TLS::~GNEChange_TLS().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, GUIPerson, and GUIContainer.
Definition at line 126 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
getVaporizerRelativePosition()
int GNEEdge::getVaporizerRelativePosition (GNEVaporizer * vaporizer) const
obtain relative positions of Vaporizer
Definition at line 556 of file GNEEdge.cpp.
References GNEAttributeCarrier::getTag(), and GNENetElement::myAdditionalChilds.
Referenced by GNEVaporizer::updateGeometry().
getVertexIndex() [1/2]
int GNEEdge::getVertexIndex (const Position & pos, bool createIfNoExist = true)
return index of a vertex of shape, or of a new vertex if position is over an shape's edge
Parameters
pos position of new/existent vertex
createIfNoExist enable or disable creation of new verte if there isn't another vertex in position
Returns
index of position vector
Definition at line 143 of file GNEEdge.cpp.
References NBEdge::getGeometry(), NBEdge::getInnerGeometry(), PositionVector::indexOfClosest(), PositionVector::insertAtClosest(), myNBEdge, setGeometry(), and SNAP_RADIUS.
Referenced by GNEViewNet::begingMoveSelection(), getVertexIndex(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), and setEndpoint().
getVertexIndex() [2/2]
int GNEEdge::getVertexIndex (const double offset, bool createIfNoExist = true)
return index of a vertex of shape, or of a new vertex if position is over an shape's edge
Parameters
offset position over edge
createIfNoExist enable or disable creation of new verte if there isn't another vertex in position
Returns
index of position vector
Definition at line 170 of file GNEEdge.cpp.
References NBEdge::getGeometry(), getVertexIndex(), PositionVector::length(), myNBEdge, and PositionVector::positionAtOffset2D().
hasAttribute()
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if an element with certain tag has a certain attribute
Definition at line 1211 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), GNEChange_Additional::GNEChange_Additional(), GNEViewNet::hotkeyEnter(), GNEAdditional::setBlockIconRotation(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
hasDefaultValue()
bool GNEAttributeCarrier::hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if attribute of an element has a default avlue
Definition at line 1222 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
hasRestrictedLane()
bool GNEEdge::hasRestrictedLane (SUMOVehicleClass vclass) const
check if edge has a restricted lane
Definition at line 1236 of file GNEEdge.cpp.
References myLanes.
Referenced by GNELane::getPopUpMenu().
incRef()
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Increarse reference.
Definition at line 76 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by addLane(), GNEChange_CalibratorItem::GNEChange_CalibratorItem(), GNEChange_RerouterItem::GNEChange_RerouterItem(), GNEJunction::rebuildGNECrossings(), GNENet::registerEdge(), GNENet::registerJunction(), remakeGNEConnections(), and GNEInspectorFrame::setEdgeTemplate().
isBool()
bool GNEAttributeCarrier::isBool (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool for a certain tag
Definition at line 867 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBoolAttrs, SUMO_ATTR_ACCELERATION, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_FILL, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_GEO, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PASS, SUMO_ATTR_PRIORITY, SUMO_ATTR_REROUTE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POLY, and SUMO_TAG_REROUTER.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isColor()
bool GNEAttributeCarrier::isColor (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type color for a certain tag
Definition at line 910 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myColorAttrs, SUMO_ATTR_COLOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_ROUTE, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isDiscrete()
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 1045 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFilename()
bool GNEAttributeCarrier::isFilename (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a filename
Definition at line 1141 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, SUMO_ATTR_FILE, SUMO_ATTR_IMGFILE, SUMO_ATTR_OUTPUT, SUMO_TAG_CALIBRATOR, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFloat()
bool GNEAttributeCarrier::isFloat (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 741 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_ANGLE, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERIOD, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_STEP, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isInt()
bool GNEAttributeCarrier::isInt (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 707 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_FROM_LANE, SUMO_ATTR_INDEX, SUMO_ATTR_LAYER, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isInverted()
bool GNEEdge::isInverted () const
return true if edge is inverted (Angle between origin and destiny junction is -PI/2 <= angle < PI/2
Definition at line 287 of file GNEEdge.cpp.
References PositionVector::beginEndAngle(), NBEdge::getGeometry(), and myNBEdge.
isList()
bool GNEAttributeCarrier::isList (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 935 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, SUMO_ATTR_LINES, SUMO_ATTR_SHAPE, SUMO_TAG_BUS_STOP, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNENet::replaceInListAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isNonEditable()
bool GNEAttributeCarrier::isNonEditable (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is non editable
Definition at line 1193 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNonEditableAttrs, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
isNumerical()
bool GNEAttributeCarrier::isNumerical (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 701 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [1/2]
bool GNEAttributeCarrier::isPositive (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is only Positive (i.e. cannot take negative values)
Definition at line 1055 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myPositiveAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [2/2]
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 249 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFilename(), and GNEAttributeCarrier::isValidID().
isProbability()
bool GNEAttributeCarrier::isProbability (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is a probability (i.e. oly can values between [0, 1])
Definition at line 1122 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myProbabilityAttrs, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_PROB, SUMO_TAG_CHARGING_STATION, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_FLOW, SUMO_TAG_REROUTER, and SUMO_TAG_ROUTE_PROB_REROUTE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isString()
bool GNEAttributeCarrier::isString (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 929 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isNumerical(), and GNEAttributeCarrier::isTime().
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isTime()
bool GNEAttributeCarrier::isTime (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is time
Definition at line 830 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTimeAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_END, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_STARTTIME, SUMO_ATTR_TIME, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isUnique()
bool GNEAttributeCarrier::isUnique (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
Definition at line 958 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspectMultisection(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isValid()
bool GNEEdge::isValid (SumoXMLAttr key, const std::string & value) virtual
Implements GNENetElement.
Definition at line 844 of file GNEEdge.cpp.
References canParseVehicleClasses(), NBEdge::getGeometry(), GUIGlObject::getMicrosimID(), GNEAttributeCarrier::getTag(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, StringBijection< T >::hasString(), GNEAttributeCarrier::isValidID(), SUMOXMLDefinitions::LaneSpreadFunctions, myGNEJunctionDestiny, myGNEJunctionSource, myNBEdge, GNENetElement::myNet, GeomConvHelper::parseShapeReporting(), GNENet::retrieveEdge(), GNENet::retrieveJunction(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, toString(), NBEdge::UNSPECIFIED_LOADED_LENGTH, and NBEdge::UNSPECIFIED_WIDTH.
isValidFilename()
bool GNEAttributeCarrier::isValidFilename (const std::string & value) static inherited
true if value is a valid file value
Definition at line 275 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNECalibratorVehicleType::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isValidID()
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 269 of file GNEAttributeCarrier.cpp.
Referenced by GNEAdditional::changeAdditionalID(), GNEAttributeCarrier::isPositive(), GNERouteProbReroute::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNECalibratorFlow::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEJunction::isValid(), isValid(), GNEAdditional::isValidAdditionalID(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isVClass()
bool GNEAttributeCarrier::isVClass (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a list of Vehicle Classes
Definition at line 1172 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, GNEAttributeCarrier::myVClassAttrs, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_EDGE, and SUMO_TAG_LANE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
moveEntireShape()
void GNEEdge::moveEntireShape (const PositionVector & oldShape, const Position & offset)
move entire shape without commiting change
Parameters
[in] oldShape the old shape of polygon before moving
[in] offset the offset of movement
Definition at line 203 of file GNEEdge.cpp.
References PositionVector::add(), GNENetElement::myNet, GNENet::refreshElement(), and setGeometry().
moveVertexShape()
int GNEEdge::moveVertexShape (const int index, const Position & oldPos, const Position & offset)
change position of a vertex of shape without commiting change
Parameters
[in] index index of Vertex shape
[in] newPos The new position of vertex
Returns
index of vertex (in some cases index can change
Definition at line 180 of file GNEEdge.cpp.
References PositionVector::add(), NBEdge::getInnerGeometry(), myNBEdge, and setGeometry().
Referenced by GNEViewNet::onMouseMove().
operator=()
GNEEdge& GNEEdge::operator= (const GNEEdge & s) private delete
invalidated assignment operator
parse() [1/12]
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 88 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int().
parse() [2/12]
template<> double GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 94 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2double().
parse() [3/12]
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 100 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
parse() [4/12]
template<> std::string GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 106 of file GNEAttributeCarrier.cpp.
parse() [5/12]
template<> SUMOVehicleClass GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 112 of file GNEAttributeCarrier.cpp.
References SumoVehicleClassStrings, and SVC_IGNORING.
parse() [6/12]
template<> RGBColor GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 124 of file GNEAttributeCarrier.cpp.
References RGBColor::parseColor().
parse() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 130 of file GNEAttributeCarrier.cpp.
References SumoVehicleShapeStrings, and SVS_UNKNOWN.
parse() [8/12]
template<> std::vector<std::string> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 142 of file GNEAttributeCarrier.cpp.
References SUMOSAXAttributes::parseStringVector().
parse() [9/12]
template<> std::vector<int> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 150 of file GNEAttributeCarrier.cpp.
parse() [10/12]
template<> std::vector<double> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 161 of file GNEAttributeCarrier.cpp.
parse() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 172 of file GNEAttributeCarrier.cpp.
parse() [12/12]
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse().
parseAttributeFromXML()
template<typename T > static T GNEAttributeCarrier::parseAttributeFromXML (const SUMOSAXAttributes & attrs, const std::string & objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool & abort, bool report = true) inline static inherited
Parse attribute from XML and show warnings if there are problems parsing it.
Definition at line 276 of file GNEAttributeCarrier.h.
References canParseVehicleClasses(), GNEAttributeCarrier::checkGNEEdgesValid(), GNEAttributeCarrier::checkGNELanesValid(), SUMOSAXAttributes::get(), GNEAttributeCarrier::getAttributeType(), SUMOSAXAttributes::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), GNEAttributeCarrier::isValidID(), GNEAttributeCarrier::isVClass(), GNEAttributeCarrier::parseGNEEdges(), GNEAttributeCarrier::parseGNELanes(), GNEAttributeCarrier::setAttribute(), SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_VCLASS, toString(), and WRITE_WARNING.
parseGNEEdges() [1/2]
std::vector< GNEEdge * > GNEAttributeCarrier::parseGNEEdges (GNENet * net, const std::string & value) static inherited
parse string into vector of GNEEdges
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1748 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge().
Referenced by GNEAdditionalHandler::buildAdditional(), GNECalibratorRoute::getAttribute(), GNERerouter::getAttribute(), GNECalibratorRoute::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAttributeCarrier::parseAttributeFromXML(), GNECalibratorRoute::setAttribute(), GNECrossing::setAttribute(), GNERerouter::setAttribute(), GNERerouter::writeAdditional(), and GNECalibratorRoute::writeRoute().
parseGNEEdges() [2/2]
std::string GNEAttributeCarrier::parseGNEEdges (const std::vector< GNEEdge *> & edges) static inherited
parse vector of GNEEdges into string
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1774 of file GNEAttributeCarrier.cpp.
References joinToString().
parseGNELanes() [1/2]
std::vector< GNELane * > GNEAttributeCarrier::parseGNELanes (GNENet * net, const std::string & value) static inherited
parse string into vector of GNELanes
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1761 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane().
Referenced by GNEAdditionalHandler::buildAdditional(), GNEVariableSpeedSign::getAttribute(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAttributeCarrier::parseAttributeFromXML(), GNEVariableSpeedSign::setAttribute(), and GNEVariableSpeedSign::writeAdditional().
parseGNELanes() [2/2]
std::string GNEAttributeCarrier::parseGNELanes (const std::vector< GNELane *> & lanes) static inherited
parse vector of GNELanes into string
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1785 of file GNEAttributeCarrier.cpp.
References joinToString().
remakeGNEConnections()
void GNEEdge::remakeGNEConnections ()
remake connections
Definition at line 482 of file GNEEdge.cpp.
References OptionsCont::getBool(), NBEdge::getConnections(), OptionsCont::getOptions(), GNEReferenceCounter::incRef(), myGNEConnections, myNBEdge, retrieveGNEConnection(), toString(), GNEConnection::updateLinkState(), and WRITE_WARNING.
Referenced by addLane(), and removeLane().
removeAdditionalChild()
void GNENetElement::removeAdditionalChild (GNEAdditional * additional) inherited
remove additional child from this edge
Definition at line 98 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalChilds, toString(), and GNENetElement::updateGeometry().
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNEChange_Additional::redo(), and GNEChange_Additional::undo().
removeAdditionalParent()
void GNENetElement::removeAdditionalParent (GNEAdditional * additional) inherited
remove additional child from this edge
Definition at line 71 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalParents, toString(), and GNENetElement::updateGeometry().
removeConnection()
void GNEEdge::removeConnection (NBEdge::Connection nbCon) private
removes a connection
Definition at line 1180 of file GNEEdge.cpp.
References GNEReferenceCounter::decRef(), NBEdge::Connection::fromLane, OptionsCont::getBool(), GNEAttributeCarrier::getID(), GUIGlObject::getMicrosimID(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), NBEdge::getTurnDestination(), myGNEConnections, myNBEdge, GNENetElement::myNet, GNENet::refreshElement(), GNENet::removeExplicitTurnaround(), NBEdge::removeFromConnections(), retrieveGNEConnection(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, toString(), GNEReferenceCounter::unreferenced(), and WRITE_WARNING.
Referenced by GNEChange_Connection::redo(), and GNEChange_Connection::undo().
removeEdgeFromCrossings()
void GNEEdge::removeEdgeFromCrossings (GNEJunction * junction, GNEUndoList * undoList) private
remove crossing of junction
Definition at line 1247 of file GNEEdge.cpp.
References GNENet::deleteCrossing(), GNEJunction::getGNECrossings(), and GNENetElement::myNet.
Referenced by setAttribute().
removeEdgeOfAdditionalParents()
void GNEEdge::removeEdgeOfAdditionalParents (GNEUndoList * undoList, bool allowEmpty)
remove Edge of Additional Parent
Definition at line 591 of file GNEEdge.cpp.
References GNEAttributeCarrier::getID(), GNENetElement::myAdditionalParents, SUMO_ATTR_EDGES, and toString().
Referenced by GNENet::deleteEdge().
removeLane()
void GNEEdge::removeLane (GNELane * lane) private
the number of lanes by one. argument is only used to increase robustness (assertions)
Definition at line 1115 of file GNEEdge.cpp.
References GNEReferenceCounter::decRef(), NBEdge::deleteLane(), OptionsCont::getBool(), GNEJunction::getGNEEdges(), GNEAttributeCarrier::getID(), GNELane::getIndex(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), myGNEJunctionDestiny, myGNEJunctionSource, myLanes, myNBEdge, GNENetElement::myNet, GNENet::refreshElement(), remakeGNEConnections(), SUMO_TAG_LANE, toString(), GNEReferenceCounter::unreferenced(), updateGeometry(), and WRITE_WARNING.
Referenced by GNEChange_Lane::redo(), and GNEChange_Lane::undo().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
resetEndpoint()
void GNEEdge::resetEndpoint (const Position & pos, GNEUndoList * undoList)
restores the endpoint to the junction position at the appropriate end
Definition at line 457 of file GNEEdge.cpp.
References Position::distanceTo2D(), GNEJunction::getNBNode(), NBNode::getPosition(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEJunction::invalidateShape(), myGNEJunctionDestiny, myGNEJunctionSource, setAttribute(), and toString().
Referenced by GNEViewNet::onCmdResetEdgeEndpoint().
retrieveGNEConnection()
GNEConnection * GNEEdge::retrieveGNEConnection (int fromLane, NBEdge * to, int toLane, bool createIfNoExist = true)
get GNEConnection if exist, and if not create it if create is enabled
Definition at line 1205 of file GNEEdge.cpp.
References OptionsCont::getBool(), Named::getID(), GNEAttributeCarrier::getID(), getLanes(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), myGNEConnections, myLanes, GNENetElement::myNet, GNENet::retrieveEdge(), toString(), and WRITE_WARNING.
Referenced by addConnection(), GNEConnectorFrame::handleLaneClick(), remakeGNEConnections(), and removeConnection().
setAttribute() [1/2]
void GNEEdge::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
Implements GNENetElement.
Definition at line 747 of file GNEEdge.cpp.
References getAttribute(), GNEJunction::getNBNode(), OptionsCont::getOptions(), NBNode::getPosition(), GNEAttributeCarrier::getTag(), GNE_ATTR_MODIFICATION_STATUS, GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEAttributeCarrier::GNEChange_Attribute, GNEJunction::invalidateShape(), myGNEJunctionDestiny, myGNEJunctionSource, myLanes, myNBEdge, GNENetElement::myNet, myOrigShape, GNEUndoList::p_add(), GNEUndoList::p_begin(), GNEUndoList::p_end(), removeEdgeFromCrossings(), OptionsCont::resetWritable(), GNENet::retrieveJunction(), OptionsCont::set(), NBEdge::setGeometry(), GNEJunction::setLogicValid(), setNumLanes(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, toString(), and GNEJunction::updateGeometry().
Referenced by GNENet::addReversedEdge(), copyTemplate(), deleteGeometryPoint(), GNEViewNet::onCmdStraightenEdges(), GNENet::remapEdge(), GNENet::replaceJunctionByGeometry(), resetEndpoint(), GNENet::reverseEdge(), setEndpoint(), smooth(), smoothElevation(), GNENet::splitEdge(), and straightenElevation().
setAttribute() [2/2]
void GNEEdge::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
set attribute after validation
Implements GNENetElement.
Definition at line 948 of file GNEEdge.cpp.
References GNEJunction::addIncomingGNEEdge(), GNEJunction::addOutgoingGNEEdge(), GNENet::changeEdgeEndpoints(), clearGNEConnections(), NBEdge::declareConnectionsAsLoaded(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), GUIGlObject::getMicrosimID(), GNEJunction::getPositionInView(), GNEAttributeCarrier::getTag(), NBEdge::getToNode(), GNE_ATTR_MODIFICATION_STATUS, GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, GNEAttributeCarrier::GUESSED, NBEdge::invalidateConnections(), SUMOXMLDefinitions::LaneSpreadFunctions, myConnectionStatus, myGNEJunctionDestiny, myGNEJunctionSource, myNBEdge, GNENetElement::myNet, myOrigShape, NBEdge::myPriority, NBEdge::myType, GeomConvHelper::parseShapeReporting(), PositionVector::push_back_noDoublePos(), PositionVector::push_front_noDoublePos(), GNEJunction::removeIncomingGNEEdge(), GNEJunction::removeOutgoingGNEEdge(), GNENet::renameEdge(), GNENet::retrieveJunction(), NBEdge::setEndOffset(), setGeometry(), NBEdge::setLaneSpreadFunction(), NBEdge::setLaneWidth(), NBEdge::setLoadedLength(), NBEdge::setSpeed(), NBEdge::setStreetName(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, toString(), and NBEdge::UNSPECIFIED_WIDTH.
setEndpoint()
void GNEEdge::setEndpoint (Position pos, GNEUndoList * undoList)
makes pos the new geometry endpoint at the appropriate end
Definition at line 432 of file GNEEdge.cpp.
References deleteGeometryPoint(), Position::distanceTo2D(), NBEdge::getGeometry(), NBEdge::getInnerGeometry(), GNEJunction::getNBNode(), NBNode::getPosition(), getVertexIndex(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, PositionVector::indexOfClosest(), GNEJunction::invalidateShape(), myGNEJunctionDestiny, myGNEJunctionSource, myNBEdge, GNEUndoList::p_begin(), GNEUndoList::p_end(), setAttribute(), SNAP_RADIUS, and toString().
Referenced by GNEViewNet::onCmdSetEdgeEndpoint().
setGeometry()
void GNEEdge::setGeometry (PositionVector geom, bool inner)
update edge geometry and inform the lanes
Parameters
[in] geom The new geometry
[in] inner Whether geom is only the inner points
Definition at line 471 of file GNEEdge.cpp.
References GNEJunction::invalidateShape(), myGNEJunctionDestiny, myGNEJunctionSource, myNBEdge, GNENetElement::myNet, GNENet::refreshElement(), NBEdge::setGeometry(), and updateGeometry().
Referenced by commitShapeChange(), deleteGeometryPoint(), getVertexIndex(), moveEntireShape(), moveVertexShape(), setAttribute(), and updateJunctionPosition().
setMicrosimID()
void GNEEdge::setMicrosimID (const std::string & newID) virtual
override to also set lane ids
Reimplemented from GUIGlObject.
Definition at line 1227 of file GNEEdge.cpp.
References getNBEdge(), myLanes, and GUIGlObject::setMicrosimID().
Referenced by GNENet::renameEdge().
setNumLanes()
void GNEEdge::setNumLanes (int numLanes, GNEUndoList * undoList) private
changes the number of lanes. When reducing the number of lanes, higher-numbered lanes are removed first. When increasing the number of lanes, the last known attributes for a lane with this number are restored. If none are found the attributes for the leftmost lane are copied
Definition at line 1051 of file GNEEdge.cpp.
References NBEdge::getLaneStruct(), GNEChange_Lane, myGNEJunctionDestiny, myGNEJunctionSource, myLanes, myNBEdge, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEJunction::setLogicValid(), SUMO_TAG_LANE, and toString().
Referenced by setAttribute().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setResponsible()
void GNEEdge::setResponsible (bool newVal)
set responsibility for deleting internal strctures
Definition at line 939 of file GNEEdge.cpp.
References myAmResponsible.
Referenced by GNENet::deleteSingleEdge(), and GNENet::registerEdge().
smooth()
void GNEEdge::smooth (GNEUndoList * undoList)
make geometry smooth
Definition at line 1341 of file GNEEdge.cpp.
References NBEdge::getGeometry(), GNEAttributeCarrier::getID(), myNBEdge, setAttribute(), smoothShape(), SUMO_ATTR_SHAPE, toString(), and WRITE_WARNING.
Referenced by GNEViewNet::onCmdSmoothEdges().
smoothElevation()
void GNEEdge::smoothElevation (GNEUndoList * undoList)
smooth elevation with regard to adjoining edges
Definition at line 1353 of file GNEEdge.cpp.
References NBEdge::getGeometry(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), PositionVector::length2D(), myNBEdge, PositionVector::positionAtOffset2D(), PositionVector::resample(), setAttribute(), smoothShape(), SUMO_ATTR_SHAPE, toString(), WRITE_WARNING, and Position::z().
Referenced by GNEViewNet::onCmdSmoothEdgesElevation().
smoothShape()
PositionVector GNEEdge::smoothShape (const PositionVector & shape, bool forElevation)
return smoothed shape
Definition at line 1268 of file GNEEdge.cpp.
References bezier(), NBNode::bezierControlPoints(), DEBUGCOND, DEG2RAD, PositionVector::EMPTY, NBNode::geometryLike(), OptionsCont::getFloat(), NBEdge::getFromNode(), GNEAttributeCarrier::getID(), NBNode::getIncomingEdges(), OptionsCont::getInt(), OptionsCont::getOptions(), NBNode::getOutgoingEdges(), NBEdge::getToNode(), NBEdge::isTurningDirectionAt(), PositionVector::length2D(), MAX2(), MIN2(), myNBEdge, PositionVector::positionAtOffset2D(), and Position::z().
Referenced by smooth(), and smoothElevation().
straightenElevation()
void GNEEdge::straightenElevation (GNEUndoList * undoList)
interpolate z values linear between junctions
Definition at line 1258 of file GNEEdge.cpp.
References NBEdge::getFromNode(), NBEdge::getGeometry(), NBNode::getPosition(), NBEdge::getToNode(), PositionVector::interpolateZ(), myNBEdge, setAttribute(), SUMO_ATTR_SHAPE, toString(), and Position::z().
Referenced by GNEViewNet::onCmdStraightenEdgesElevation().
unreferenced()
bool GNEReferenceCounter::unreferenced () inline inherited
check if object ins't referenced
Definition at line 87 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by removeConnection(), removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
updateGeometry()
void GNEEdge::updateGeometry () virtual
update pre-computed geometry information
Note
if current editing mode is Move, connection's geometry will not be updated
Implements GNENetElement.
Definition at line 124 of file GNEEdge.cpp.
References GNENetElement::myAdditionalChilds, GNENetElement::myAdditionalParents, myLanes, GNENetElement::myNet, and GNENet::refreshElement().
Referenced by addLane(), removeLane(), and setGeometry().
updateJunctionPosition()
void GNEEdge::updateJunctionPosition (GNEJunction * junction, const Position & origPos)
update edge geometry after junction move
Definition at line 263 of file GNEEdge.cpp.
References PositionVector::add(), NBEdge::getGeometry(), GNEJunction::getNBNode(), NBNode::getPosition(), myGNEJunctionSource, myNBEdge, and setGeometry().
wasSplit()
bool GNEEdge::wasSplit ()
whether this edge was created from a split
Definition at line 665 of file GNEEdge.cpp.
References myWasSplit.
Referenced by GNENet::splitEdge().
Friends And Related Function Documentation
GNEChange_Connection
friend class GNEChange_Connection friend
Definition at line 60 of file GNEEdge.h.
GNEChange_Lane
friend class GNEChange_Lane friend
Friend class.
Definition at line 59 of file GNEEdge.h.
Referenced by setNumLanes().
Field Documentation
APPROVED
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 269 of file GNEAttributeCarrier.h.
GUESSED
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 263 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::setAttribute(), and setAttribute().
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
INVALID_POSITION
const double GNEAttributeCarrier::INVALID_POSITION = -1000000 static inherited
default value for invalid positions (used by POIs and Polygons)
Definition at line 272 of file GNEAttributeCarrier.h.
LOADED
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 260 of file GNEAttributeCarrier.h.
MODIFIED
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 266 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::markAsModified(), and GNEConnectorFrame::onCmdClearSelectedConnections().
myAdditionalChilds
std::vector<GNEAdditional*> GNENetElement::myAdditionalChilds protected inherited
list of Additional Childs of this NetElement
Definition at line 168 of file GNENetElement.h.
Referenced by GNENetElement::addAdditionalChild(), GNENetElement::getAdditionalChilds(), getRouteProbeRelativePosition(), getVaporizerRelativePosition(), GNENetElement::removeAdditionalChild(), updateGeometry(), and GNELane::updateGeometry().
myAdditionalParents
std::vector<GNEAdditional*> GNENetElement::myAdditionalParents protected inherited
list of Additional parents of this NetElement
Definition at line 165 of file GNENetElement.h.
Referenced by GNENetElement::addAdditionalParent(), GNENetElement::getAdditionalParents(), GNENetElement::removeAdditionalParent(), removeEdgeOfAdditionalParents(), GNELane::removeLaneOfAdditionalParents(), updateGeometry(), and GNELane::updateGeometry().
myAmResponsible
bool GNEEdge::myAmResponsible protected
whether we are responsible for deleting myNBNode
Definition at line 286 of file GNEEdge.h.
Referenced by setResponsible(), and ~GNEEdge().
myConnectionStatus
std::string GNEEdge::myConnectionStatus protected
modification status of the connections
Definition at line 292 of file GNEEdge.h.
Referenced by getAttribute(), and setAttribute().
myGNEConnections
ConnectionVector GNEEdge::myGNEConnections protected
vector with the connections of this edge
Definition at line 283 of file GNEEdge.h.
Referenced by addConnection(), clearGNEConnections(), drawGL(), getGNEConnections(), remakeGNEConnections(), removeConnection(), retrieveGNEConnection(), and ~GNEEdge().
myGNEJunctionDestiny
GNEJunction* GNEEdge::myGNEJunctionDestiny protected
pointer to GNEJunction destiny
Definition at line 274 of file GNEEdge.h.
Referenced by addLane(), getAttribute(), getGNECrossings(), getGNEJunctionDestiny(), getOppositeEdge(), isValid(), removeLane(), resetEndpoint(), setAttribute(), setEndpoint(), setGeometry(), and setNumLanes().
myGNEJunctionSource
GNEJunction* GNEEdge::myGNEJunctionSource protected
pointer to GNEJunction source
Definition at line 271 of file GNEEdge.h.
Referenced by addLane(), getAttribute(), getGNECrossings(), getGNEJunctionSource(), getOppositeEdge(), isValid(), removeLane(), resetEndpoint(), setAttribute(), setEndpoint(), setGeometry(), setNumLanes(), and updateJunctionPosition().
myLanes
LaneVector GNEEdge::myLanes protected
vectgor with the lanes of this edge
Definition at line 280 of file GNEEdge.h.
Referenced by addLane(), copyTemplate(), drawGL(), getBoundary(), getLaneGlIDs(), getLanes(), GNEEdge(), hasRestrictedLane(), removeLane(), retrieveGNEConnection(), setAttribute(), setMicrosimID(), setNumLanes(), updateGeometry(), and ~GNEEdge().
myNBEdge
NBEdge& GNEEdge::myNBEdge protected
the underlying NBEdge
Definition at line 268 of file GNEEdge.h.
Referenced by addConnection(), addLane(), commitShapeChange(), deleteGeometryPoint(), drawGL(), getAttribute(), getNBEdge(), getSplitPos(), getVertexIndex(), GNEEdge(), isInverted(), isValid(), moveVertexShape(), remakeGNEConnections(), removeConnection(), removeLane(), setAttribute(), setEndpoint(), setGeometry(), setNumLanes(), smooth(), smoothElevation(), smoothShape(), straightenElevation(), updateJunctionPosition(), and ~GNEEdge().
myNet
GNENet* GNENetElement::myNet protected inherited
the net to inform about updates
Definition at line 162 of file GNENetElement.h.
Referenced by addConnection(), GNEJunction::addTrafficLight(), commitShapeChange(), deleteGeometryPoint(), GNEJunction::drawGL(), GNEConnection::drawGL(), GNENetElement::getNet(), getOppositeEdge(), GNENetElement::getParentName(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNELane::getPopUpMenu(), GNEConnection::getPopUpMenu(), GNEJunction::invalidateShape(), GNEJunction::invalidateTLS(), GNECrossing::isValid(), GNEJunction::isValid(), isValid(), GNEJunction::markAsModified(), moveEntireShape(), GNEJunction::moveJunctionGeometry(), GNEJunction::rebuildGNECrossings(), removeConnection(), GNEJunction::removeEdgeFromCrossings(), removeEdgeFromCrossings(), removeLane(), GNEJunction::removeTrafficLight(), retrieveGNEConnection(), GNECrossing::setAttribute(), GNEConnection::setAttribute(), GNEJunction::setAttribute(), setAttribute(), GNELane::setAttribute(), setGeometry(), GNEJunction::setLogicValid(), updateGeometry(), GNELane::updateGeometry(), and GNEJunction::updateShapesAndGeometries().
myOrigShape
PositionVector GNEEdge::myOrigShape protected
restore point for undo
Definition at line 277 of file GNEEdge.h.
Referenced by setAttribute().
myWasSplit
bool GNEEdge::myWasSplit protected
whether this edge was created from a split
Definition at line 289 of file GNEEdge.h.
Referenced by wasSplit().
SNAP_RADIUS
const double GNEEdge::SNAP_RADIUS = SUMO_const_halfLaneWidth static
Definition at line 237 of file GNEEdge.h.
Referenced by commitShapeChange(), drawGL(), getSplitPos(), getVertexIndex(), and setEndpoint().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GNEEdge.h
GNEEdge.cpp