SUMO - Simulation of Urban MObility: AGWorkAndSchool Class Reference
AGWorkAndSchool Class Reference
#include <AGWorkAndSchool.h>
Public Member Functions
AGWorkAndSchool (AGHousehold *hh, AGDataAndStatistics *das, std::list< AGTrip > *prevTrips)
int arrHour (AGPosition from, AGPosition to, int departure)
int availableTranspMeans (AGPosition from, AGPosition to)
void buildChildrenAccompaniment ()
void buildWorkDestinations ()
void carAllocation ()
bool carsToTrips ()
bool checkAndBuildTripConsistancy ()
bool checkDriversScheduleMatching ()
int depHour (AGPosition from, AGPosition to, int arrival)
void generateListTrips ()
bool generateTrips ()
std::list< AGTrip > & getPartialActivityTrips ()
std::string getUnusedCar ()
bool isGenerated ()
bool isThereUnusedCar ()
void makePossibleDriversDrive ()
int possibleTranspMean (AGPosition destination)
int randomTimeBetween (int begin, int end)
int timeToDrive (AGPosition from, AGPosition to)
Protected Attributes
int activityPriority
double carPreference
bool genDone
AGHousehold * myHousehold
std::list< AGTrip > myPartialActivityTrips
std::list< AGTrip > * myPreviousTrips
AGDataAndStatistics * myStatData
double timePerKm
Private Attributes
std::list< AGAdult > adultNeedingCarAccompaniment
std::list< AGChild > childrenNeedingCarAccompaniment
std::list< AGAdult > notNeedingDrivers
std::list< AGAdult > personsDrivingCars
std::list< AGTrip > tempAccTrip
std::list< AGTrip > tempTrip
std::list< AGAdult > workingPeoplePossCar
Detailed Description
Definition at line 44 of file AGWorkAndSchool.h.
Constructor & Destructor Documentation
AGWorkAndSchool()
AGWorkAndSchool::AGWorkAndSchool (AGHousehold * hh, AGDataAndStatistics * das, std::list< AGTrip > * prevTrips) inline
Definition at line 46 of file AGWorkAndSchool.h.
References buildChildrenAccompaniment(), buildWorkDestinations(), carAllocation(), carsToTrips(), checkAndBuildTripConsistancy(), checkDriversScheduleMatching(), generateListTrips(), generateTrips(), getUnusedCar(), isThereUnusedCar(), and makePossibleDriversDrive().
Member Function Documentation
arrHour()
int AGActivity::arrHour (AGPosition from, AGPosition to, int departure) inherited
Definition at line 121 of file AGActivity.cpp.
References AGActivity::timeToDrive().
Referenced by AGActivity::AGActivity(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
availableTranspMeans()
int AGActivity::availableTranspMeans (AGPosition from, AGPosition to) inherited
determine the possible means for a trip from one position to a destination. whether CAR is necessary or not, BUS available or not... 1 = by foot possible. 2 = by bus possible. 0 = by bus or foot NOT possible => only by car. : 4 is useless because it is always possible : 3 = 2 + 1 = means bus and foot possible.
Definition at line 91 of file AGActivity.cpp.
References AGDataAndStatistics::busStations, AGPosition::distanceTo(), AGDataAndStatistics::maxFootDistance, AGPosition::minDistanceTo(), and AGActivity::myStatData.
Referenced by AGActivity::AGActivity(), and buildChildrenAccompaniment().
buildChildrenAccompaniment()
void AGWorkAndSchool::buildChildrenAccompaniment ()
generate objects
Definition at line 77 of file AGWorkAndSchool.cpp.
References AGActivity::availableTranspMeans(), childrenNeedingCarAccompaniment, AGHousehold::getChildren(), AGHousehold::getPosition(), and AGActivity::myHousehold.
Referenced by AGWorkAndSchool(), and generateTrips().
buildWorkDestinations()
void AGWorkAndSchool::buildWorkDestinations ()
Definition at line 90 of file AGWorkAndSchool.cpp.
References adultNeedingCarAccompaniment, AGActivity::carPreference, AGHousehold::getAdults(), AGHousehold::getCarNbr(), AGActivity::myHousehold, personsDrivingCars, AGActivity::possibleTranspMean(), and workingPeoplePossCar.
Referenced by AGWorkAndSchool(), and generateTrips().
carAllocation()
void AGWorkAndSchool::carAllocation ()
allocation of cars to the convenient adult: the adult able to accompany the other (adult) and children in need.
Definition at line 124 of file AGWorkAndSchool.cpp.
References adultNeedingCarAccompaniment, childrenNeedingCarAccompaniment, AGHousehold::getAdultNbr(), AGHousehold::getAdults(), AGActivity::myHousehold, notNeedingDrivers, personsDrivingCars, and workingPeoplePossCar.
Referenced by AGWorkAndSchool(), and generateTrips().
carsToTrips()
bool AGWorkAndSchool::carsToTrips ()
trip generation for adults and children
Definition at line 155 of file AGWorkAndSchool.cpp.
References adultNeedingCarAccompaniment, AGStreet::allows(), checkAndBuildTripConsistancy(), checkDriversScheduleMatching(), childrenNeedingCarAccompaniment, AGActivity::depHour(), generateListTrips(), AGHousehold::getCars(), AGPosition::getPosition(), AGHousehold::getPosition(), AGPosition::getStreet(), isThereUnusedCar(), makePossibleDriversDrive(), AGActivity::myHousehold, personsDrivingCars, SVC_PASSENGER, tempAccTrip, and tempTrip.
Referenced by AGWorkAndSchool(), and generateTrips().
checkAndBuildTripConsistancy()
bool AGWorkAndSchool::checkAndBuildTripConsistancy ()
main function of Accompaniment trip management: simple trips are analyzed whether they can be grouped together or not. return true if every thing worked well
Definition at line 203 of file AGWorkAndSchool.cpp.
References tempAccTrip, and AGActivity::timePerKm.
Referenced by AGWorkAndSchool(), and carsToTrips().
checkDriversScheduleMatching()
bool AGWorkAndSchool::checkDriversScheduleMatching ()
checks whether the driver is able to accompany all people or if the others have to go too late to work for him
Definition at line 244 of file AGWorkAndSchool.cpp.
References notNeedingDrivers, tempAccTrip, tempTrip, and AGActivity::timePerKm.
Referenced by AGWorkAndSchool(), and carsToTrips().
depHour()
int AGActivity::depHour (AGPosition from, AGPosition to, int arrival) inherited
estimates the departure/arrival time given the departure location the arrival location and the wished arrival/departure time
Definition at line 114 of file AGActivity.cpp.
References AGActivity::timeToDrive().
Referenced by AGActivity::AGActivity(), carsToTrips(), and AGFreeTime::typeFromHomeNight().
generateListTrips()
void AGWorkAndSchool::generateListTrips ()
function generating Trip objects using the local objects
1 / 3 : Accompaniment
2/3 : drivers way
3/3: way return
Definition at line 271 of file AGWorkAndSchool.cpp.
References AGHousehold::getPosition(), getUnusedCar(), AGActivity::myHousehold, AGActivity::myPartialActivityTrips, notNeedingDrivers, personsDrivingCars, tempAccTrip, tempTrip, and AGActivity::timePerKm.
Referenced by AGWorkAndSchool(), and carsToTrips().
generateTrips()
bool AGWorkAndSchool::generateTrips () virtual
Implements AGActivity.
Definition at line 44 of file AGWorkAndSchool.cpp.
References adultNeedingCarAccompaniment, buildChildrenAccompaniment(), buildWorkDestinations(), carAllocation(), carsToTrips(), childrenNeedingCarAccompaniment, AGActivity::genDone, AGHousehold::getCarNbr(), AGActivity::myHousehold, notNeedingDrivers, and personsDrivingCars.
Referenced by AGWorkAndSchool(), and AGActivities::generateTrips().
getPartialActivityTrips()
std::list< AGTrip > & AGActivity::getPartialActivityTrips () inherited
Definition at line 138 of file AGActivity.cpp.
References AGActivity::myPartialActivityTrips.
Referenced by AGActivity::AGActivity(), and AGActivities::generateTrips().
getUnusedCar()
std::string AGWorkAndSchool::getUnusedCar ()
return the name of a car that is not used by another adult driver of the household in fact there is only 1 or 2 adults, so if the number of cars is greater that 1 at least one car isn't used
Definition at line 353 of file AGWorkAndSchool.cpp.
References AGHousehold::getCars(), AGActivity::myHousehold, AGActivity::myPartialActivityTrips, and tempTrip.
Referenced by AGWorkAndSchool(), and generateListTrips().
isGenerated()
bool AGActivity::isGenerated () inherited
returns whether the generation could have been well done
Definition at line 44 of file AGActivity.cpp.
References AGActivity::genDone.
Referenced by AGActivity::AGActivity().
isThereUnusedCar()
bool AGWorkAndSchool::isThereUnusedCar ()
returns true if there is an unused car that can be driven by an adult
Definition at line 198 of file AGWorkAndSchool.cpp.
References AGHousehold::getCarNbr(), AGActivity::myHousehold, notNeedingDrivers, and personsDrivingCars.
Referenced by AGWorkAndSchool(), and carsToTrips().
makePossibleDriversDrive()
void AGWorkAndSchool::makePossibleDriversDrive ()
function adding new drivers when a not used car is needed
when the person prefer the car to the bus (choice variable)
Definition at line 374 of file AGWorkAndSchool.cpp.
References adultNeedingCarAccompaniment, AGHousehold::getAdultNbr(), AGHousehold::getAdults(), AGActivity::myHousehold, notNeedingDrivers, personsDrivingCars, and workingPeoplePossCar.
Referenced by AGWorkAndSchool(), and carsToTrips().
possibleTranspMean()
int AGActivity::possibleTranspMean (AGPosition destination) inherited
determine the possible transportation means, what would be chosen: 1 = foot 2 = bus 4 = car any combination is possible by simply addition of these values (ex. 7 means: 4+2+1 <=> foot, bus and car possible / 5 means: 4+1 <=> only foot and car are possible)
Definition at line 54 of file AGActivity.cpp.
References AGDataAndStatistics::busStations, AGPosition::distanceTo(), AGHousehold::getCarNbr(), AGHousehold::getPosition(), AGDataAndStatistics::maxFootDistance, AGPosition::minDistanceTo(), AGActivity::myHousehold, and AGActivity::myStatData.
Referenced by AGActivity::AGActivity(), and buildWorkDestinations().
randomTimeBetween()
int AGActivity::randomTimeBetween (int begin, int end) inherited
evaluates a random time between the given two time instants
Definition at line 126 of file AGActivity.cpp.
References RandHelper::rand().
Referenced by AGActivity::AGActivity(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
timeToDrive()
int AGActivity::timeToDrive (AGPosition from, AGPosition to) inherited
evaluation of the needed time for going from one point to an other using the car
Definition at line 108 of file AGActivity.cpp.
References AGPosition::distanceTo(), and AGActivity::timePerKm.
Referenced by AGActivity::AGActivity(), AGActivity::arrHour(), and AGActivity::depHour().
Field Documentation
activityPriority
int AGActivity::activityPriority protected inherited
Definition at line 115 of file AGActivity.h.
adultNeedingCarAccompaniment
std::list<AGAdult> AGWorkAndSchool::adultNeedingCarAccompaniment private
adult needing a car having a car but this car is not available because of an other person
Definition at line 120 of file AGWorkAndSchool.h.
Referenced by buildWorkDestinations(), carAllocation(), carsToTrips(), generateTrips(), and makePossibleDriversDrive().
carPreference
double AGActivity::carPreference protected inherited
rate of taking the car instead of the bus because of personal preference
Definition at line 121 of file AGActivity.h.
Referenced by buildWorkDestinations().
childrenNeedingCarAccompaniment
std::list<AGChild> AGWorkAndSchool::childrenNeedingCarAccompaniment private
list of destinations for children, which can be reach only using a car (too far from home) and therefore need to be accompanied: waiting list for the accompaniment
Definition at line 115 of file AGWorkAndSchool.h.
Referenced by buildChildrenAccompaniment(), carAllocation(), carsToTrips(), and generateTrips().
genDone
bool AGActivity::genDone protected inherited
Definition at line 116 of file AGActivity.h.
Referenced by generateTrips(), AGFreeTime::generateTrips(), and AGActivity::isGenerated().
myHousehold
AGHousehold* AGActivity::myHousehold protected inherited
Definition at line 109 of file AGActivity.h.
Referenced by buildChildrenAccompaniment(), buildWorkDestinations(), carAllocation(), carsToTrips(), AGFreeTime::decideTypeOfTrip(), generateListTrips(), generateTrips(), getUnusedCar(), isThereUnusedCar(), makePossibleDriversDrive(), AGActivity::possibleTranspMean(), AGFreeTime::possibleTypeOfTrip(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
myPartialActivityTrips
std::list<AGTrip> AGActivity::myPartialActivityTrips protected inherited
Definition at line 114 of file AGActivity.h.
Referenced by generateListTrips(), AGActivity::getPartialActivityTrips(), getUnusedCar(), AGFreeTime::typeFromHomeDay(), AGFreeTime::typeFromHomeEvening(), and AGFreeTime::typeFromHomeNight().
myPreviousTrips
std::list<AGTrip>* AGActivity::myPreviousTrips protected inherited
Definition at line 113 of file AGActivity.h.
Referenced by AGFreeTime::whenBackHome(), AGFreeTime::whenBackHomeThisDay(), and AGFreeTime::whenBeginActivityNextDay().
myStatData
AGDataAndStatistics* AGActivity::myStatData protected inherited
Definition at line 111 of file AGActivity.h.
Referenced by AGActivity::availableTranspMeans(), AGActivity::possibleTranspMean(), and AGFreeTime::possibleTypeOfTrip().
notNeedingDrivers
std::list<AGAdult> AGWorkAndSchool::notNeedingDrivers private
adults of the household who are not in need of car for work but are able to accompany someone. used only in case of need.
Definition at line 136 of file AGWorkAndSchool.h.
Referenced by carAllocation(), checkDriversScheduleMatching(), generateListTrips(), generateTrips(), isThereUnusedCar(), and makePossibleDriversDrive().
personsDrivingCars
std::list<AGAdult> AGWorkAndSchool::personsDrivingCars private
work destinations with use of car
Definition at line 131 of file AGWorkAndSchool.h.
Referenced by buildWorkDestinations(), carAllocation(), carsToTrips(), generateListTrips(), generateTrips(), isThereUnusedCar(), and makePossibleDriversDrive().
tempAccTrip
std::list<AGTrip> AGWorkAndSchool::tempAccTrip private
list of temporary trips: contains accompaniment trips without any return to home.
Definition at line 141 of file AGWorkAndSchool.h.
Referenced by carsToTrips(), checkAndBuildTripConsistancy(), checkDriversScheduleMatching(), and generateListTrips().
tempTrip
std::list<AGTrip> AGWorkAndSchool::tempTrip private
Definition at line 142 of file AGWorkAndSchool.h.
Referenced by carsToTrips(), checkDriversScheduleMatching(), generateListTrips(), and getUnusedCar().
timePerKm
double AGActivity::timePerKm protected inherited
Definition at line 117 of file AGActivity.h.
Referenced by checkAndBuildTripConsistancy(), checkDriversScheduleMatching(), generateListTrips(), AGActivity::timeToDrive(), AGFreeTime::whenBackHome(), and AGFreeTime::whenBackHomeThisDay().
workingPeoplePossCar
std::list<AGAdult> AGWorkAndSchool::workingPeoplePossCar private
list of destinations for work by bus or car, car being possible (other wise bus or feet)
Definition at line 126 of file AGWorkAndSchool.h.
Referenced by buildWorkDestinations(), carAllocation(), and makePossibleDriversDrive().
The documentation for this class was generated from the following files:
AGWorkAndSchool.h
AGWorkAndSchool.cpp