SUMO - Simulation of Urban MObility: MEVehicleControl Class Reference
MEVehicleControl Class Reference
The class responsible for building and deletion of vehicles (gui-version)
#include <MEVehicleControl.h>
Public Types
typedef std::map< std::string, SUMOVehicle * >::const_iterator constVehIt
Definition of the internal vehicles map iterator.
Public Member Functions
void abortWaiting ()
informes about all waiting vehicles (deletion in destructor)
void adaptIntermodalRouter (MSNet::MSIntermodalRouter &router) const
void addWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
Adds a vehicle to the list of waiting vehiclse to a given edge.
SUMOTime computeRandomDepartOffset () const
compute (optional) random offset to the departure time
void discountStateLoaded (bool removed=false)
avoid counting a vehicle twice if it was loaded from state and route input
double getMaxSpeedFactor () const
return the maximum speed factor for all vehicles that ever entered the network
double getMinDeceleration () const
return the minimum deceleration capability for all vehicles that ever entered the network
SUMOVehicle * getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > &lines, const double position, const std::string ridingID)
MEVehicleControl ()
Constructor.
void registerCollision ()
registers one collision-related teleport
void registerEmergencyStop ()
register emergency stop
void registerOneWaiting (const bool isPerson)
increases the count of vehicles waiting for a transport to allow recognition of person / container related deadlocks
void registerTeleportJam ()
register one non-collision-related teleport
void registerTeleportWrongLane ()
register one non-collision-related teleport
void registerTeleportYield ()
register one non-collision-related teleport
void removeWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
Removes a vehicle from the list of waiting vehicles to a given edge.
void unregisterOneWaiting (const bool isPerson)
decreases the count of vehicles waiting for a transport to allow recognition of person / container related deadlocks
~MEVehicleControl ()
Destructor.
Vehicle creation
virtual SUMOVehicle * buildVehicle (SUMOVehicleParameter *defs, const MSRoute *route, MSVehicleType *type, const bool ignoreStopErrors, const bool fromRouteFile=true)
Builds a vehicle, increases the number of built vehicles.
Insertion, deletion and retrieval of vehicles
virtual bool addVehicle (const std::string &id, SUMOVehicle *v)
Tries to insert the vehicle into the internal vehicle container.
SUMOVehicle * getVehicle (const std::string &id) const
Returns the vehicle with the given id.
virtual void deleteVehicle (SUMOVehicle *v, bool discard=false)
Deletes the vehicle.
void scheduleVehicleRemoval (SUMOVehicle *veh)
Removes a vehicle after it has ended.
constVehIt loadedVehBegin () const
Returns the begin of the internal vehicle map.
constVehIt loadedVehEnd () const
Returns the end of the internal vehicle map.
Setting vehicle statistics
void vehicleDeparted (const SUMOVehicle &v)
Informs this control about a vehicle's departure.
Retrieval of vehicle statistics (always accessable)
int getLoadedVehicleNo () const
Returns the number of build vehicles.
int getEndedVehicleNo () const
Returns the number of removed vehicles.
int getRunningVehicleNo () const
Returns the number of build and inserted, but not yet deleted vehicles.
int getDepartedVehicleNo () const
Returns the number of inserted vehicles.
int getQuota (double frac=-1) const
Returns the number of instances of the current vehicle that shall be emitted considering that "frac" of all vehicles shall be emitted overall if a negative fraction is given the demand scaling factor is used (–scale)
int getActiveVehicleCount () const
Returns the number of build vehicles that have not been removed or need to wait for a passenger or a container.
int getCollisionCount () const
return the number of collisions
int getTeleportsJam () const
return the number of teleports due to jamming
int getTeleportsYield () const
return the number of teleports due to vehicles stuck on a minor road
int getTeleportsWrongLane () const
return the number of teleports due to vehicles stuck on the wrong lane
int getTeleportCount () const
return the number of teleports (including collisions)
int getEmergencyStops () const
return the number of emergency stops
double getTotalDepartureDelay () const
Returns the total departure delay.
double getTotalTravelTime () const
Returns the total travel time.
Insertion and retrieval of vehicle types
bool addVType (MSVehicleType *vehType)
Adds a vehicle type.
void removeVType (const MSVehicleType *vehType)
bool addVTypeDistribution (const std::string &id, RandomDistributor< MSVehicleType *> *vehTypeDistribution)
Adds a vehicle type distribution.
bool hasVType (const std::string &id) const
Asks for existence of a vehicle type.
bool hasVTypeDistribution (const std::string &id) const
Asks for a vehicle type distribution.
MSVehicleType * getVType (const std::string &id=DEFAULT_VTYPE_ID, std::mt19937 *rng=0)
Returns the named vehicle type or a sample from the named distribution.
void insertVTypeIDs (std::vector< std::string > &into) const
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
State I/O
void setState (int runningVehNo, int loadedVehNo, int endedVehNo, double totalDepartureDelay, double totalTravelTime)
Sets the current state variables as loaded from the stream.
void saveState (OutputDevice &out)
Saves the current state into the given stream.
Protected Attributes
Vehicle statistics (always accessible)
int myLoadedVehNo
The number of build vehicles.
Private Member Functions
MEVehicleControl (const MEVehicleControl &s)
invalidated copy constructor
MEVehicleControl & operator= (const MEVehicleControl &s)
invalidated assignment operator
Vehicle container
typedef std::map< std::string, SUMOVehicle *> VehicleDictType
Vehicle dictionary type.
VehicleDictType myVehicleDict
Dictionary of vehicles.
Detailed Description
The class responsible for building and deletion of vehicles (gui-version)
Builds GUIVehicle instances instead of MSVehicle.
See also
MSVehicleControl
Todo:
This is partially unsecure due to concurrent access...
Recheck vehicle deletion
Definition at line 49 of file MEVehicleControl.h.
Member Typedef Documentation
constVehIt
typedef std::map<std::string, SUMOVehicle*>::const_iterator MSVehicleControl::constVehIt inherited
Definition of the internal vehicles map iterator.
Definition at line 77 of file MSVehicleControl.h.
VehicleDictType
typedef std::map< std::string, SUMOVehicle* > MSVehicleControl::VehicleDictType protected inherited
Vehicle dictionary type.
Definition at line 531 of file MSVehicleControl.h.
Constructor & Destructor Documentation
MEVehicleControl() [1/2]
MEVehicleControl::MEVehicleControl ()
Constructor.
Definition at line 46 of file MEVehicleControl.cpp.
~MEVehicleControl()
MEVehicleControl::~MEVehicleControl ()
Destructor.
Definition at line 50 of file MEVehicleControl.cpp.
MEVehicleControl() [2/2]
MEVehicleControl::MEVehicleControl (const MEVehicleControl & s) private
invalidated copy constructor
Member Function Documentation
abortWaiting()
void MSVehicleControl::abortWaiting () inherited
informes about all waiting vehicles (deletion in destructor)
Definition at line 386 of file MSVehicleControl.cpp.
References MSVehicleControl::myVehicleDict, and WRITE_WARNING.
Referenced by MSVehicleControl::discountStateLoaded(), and MSNet::simulationState().
adaptIntermodalRouter()
void MSVehicleControl::adaptIntermodalRouter (MSNet::MSIntermodalRouter & router) const inherited
Definition at line 418 of file MSVehicleControl.cpp.
References IntermodalRouter< E, L, N, V, INTERNALROUTER >::addSchedule(), and MSVehicleControl::myPTVehicles.
Referenced by MSNet::adaptIntermodalRouter(), and MSVehicleControl::getMinDeceleration().
addVehicle()
bool MSVehicleControl::addVehicle (const std::string & id, SUMOVehicle * v) virtual inherited
Tries to insert the vehicle into the internal vehicle container.
Checks whether another vehicle with the same id exists; returns false if so. Otherwise, the vehicle is added to "myVehicleDict". It also checks whether the vehicle has a "triggered" departure and registers it accordingly.
The vehicle control gets responsible for vehicle deletion.
Parameters
[in] id The id of the vehicle
[in] v The vehicle
Returns
Whether the vehicle could be inserted (no other vehicle with the same id was inserted before)
Reimplemented in GUIVehicleControl, and GUIMEVehicleControl.
Definition at line 188 of file MSVehicleControl.cpp.
References MSVehicleControl::addWaiting(), DEPART_CONTAINER_TRIGGERED, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departProcedure, MSRoute::getEdges(), MSEdge::getLanes(), SUMOVehicle::getParameter(), SUMOVehicle::getRoute(), MSGlobals::gUseMesoSim, SUMOVehicleParameter::line, MSVehicleControl::myPTVehicles, MSVehicleControl::myVehicleDict, MSVehicleControl::registerOneWaiting(), and SUMOVehicleParameter::repetitionNumber.
Referenced by libsumo::Vehicle::add(), MSRouteHandler::addPersonTrip(), GUIMEVehicleControl::addVehicle(), GUIVehicleControl::addVehicle(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), MSCalibrator::execute(), TraCIServerAPI_Vehicle::processSet(), and METriggeredCalibrator::tryEmit().
addVType()
bool MSVehicleControl::addVType (MSVehicleType * vehType) inherited
Adds a vehicle type.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type is added to the internal vehicle type container "myVTypeDict".
This control get responsible for deletion of the added vehicle type.
Parameters
[in] vehType The vehicle type to add
Returns
Whether the vehicle type could be added
Definition at line 262 of file MSVehicleControl.cpp.
References MSVehicleControl::checkVType(), MSVehicleType::getID(), and MSVehicleControl::myVTypeDict.
Referenced by MSVehicleControl::getTotalTravelTime().
addVTypeDistribution()
bool MSVehicleControl::addVTypeDistribution (const std::string & id, RandomDistributor< MSVehicleType *> * vehTypeDistribution) inherited
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns
Whether the vehicle type could be added
Definition at line 281 of file MSVehicleControl.cpp.
References MSVehicleControl::checkVType(), and MSVehicleControl::myVTypeDistDict.
Referenced by MSVehicleControl::getTotalTravelTime().
addWaiting()
void MSVehicleControl::addWaiting (const MSEdge *const edge, SUMOVehicle * vehicle) inherited
Adds a vehicle to the list of waiting vehiclse to a given edge.
Definition at line 334 of file MSVehicleControl.cpp.
References MSVehicleControl::myWaiting.
Referenced by MSVehicleControl::addVehicle(), MSVehicleControl::getTotalTravelTime(), and MSVehicle::processNextStop().
buildVehicle()
SUMOVehicle * MEVehicleControl::buildVehicle (SUMOVehicleParameter * defs, const MSRoute * route, MSVehicleType * type, const bool ignoreStopErrors, const bool fromRouteFile = true) virtual
Builds a vehicle, increases the number of built vehicles.
Instead of a MSVehicle, a GUIVehicle is built
Parameters
[in] defs The parameter defining the vehicle
[in] route The route of this vehicle
[in] type The type of this vehicle
[in] ignoreStopErrors whether invalid stops trigger a warning only
[in] fromRouteFile whether we are just reading the route file or creating via trigger, traci, ...
Returns
The built vehicle (MEVehicle instance)
See also
MSVehicleControl::buildVehicle
Reimplemented from MSVehicleControl.
Reimplemented in GUIMEVehicleControl.
Definition at line 54 of file MEVehicleControl.cpp.
References MSBaseVehicle::addStops(), MSVehicleType::computeChosenSpeedDeviation(), MSVehicleControl::computeRandomDepartOffset(), SUMOVehicleParameter::depart, MSNet::getInstance(), MSRouteHandler::getParsingRNG(), MSNet::informVehicleStateListener(), MSVehicleControl::myLoadedVehNo, and MSNet::VEHICLE_STATE_BUILT.
computeRandomDepartOffset()
SUMOTime MSVehicleControl::computeRandomDepartOffset () const inherited
compute (optional) random offset to the departure time
Definition at line 98 of file MSVehicleControl.cpp.
References DELTA_T, MSRouteHandler::getParsingRNG(), MSVehicleControl::myMaxRandomDepartOffset, and RandHelper::rand().
Referenced by buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), and MSVehicleControl::discountStateLoaded().
deleteVehicle()
void MSVehicleControl::deleteVehicle (SUMOVehicle * v, bool discard = false) virtual inherited
Deletes the vehicle.
Parameters
[in] v The vehicle to delete
Reimplemented in GUIVehicleControl, and GUIMEVehicleControl.
Definition at line 223 of file MSVehicleControl.cpp.
References SUMOVehicle::getID(), MSVehicleControl::myDiscarded, MSVehicleControl::myEndedVehNo, and MSVehicleControl::myVehicleDict.
Referenced by MSRouteHandler::addPersonTrip(), MSInsertionControl::clearPendingVehicles(), MSRouteHandler::closeVehicle(), GUIMEVehicleControl::deleteVehicle(), GUIVehicleControl::deleteVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), TraCIServerAPI_Vehicle::processSet(), MSVehicleControl::scheduleVehicleRemoval(), and MSInsertionControl::tryInsert().
discountStateLoaded()
void MSVehicleControl::discountStateLoaded (bool removed = false) inline inherited
avoid counting a vehicle twice if it was loaded from state and route input
Definition at line 441 of file MSVehicleControl.h.
References MSVehicleControl::abortWaiting(), MSVehicleControl::computeRandomDepartOffset(), MSVehicleControl::myDiscarded, MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, and MSVehicleControl::myRunningVehNo.
Referenced by MSStateHandler::closeVehicle(), and MSInsertionControl::determineCandidates().
getActiveVehicleCount()
int MSVehicleControl::getActiveVehicleCount () const inline inherited
Returns the number of build vehicles that have not been removed or need to wait for a passenger or a container.
Returns
Number of active vehicles
Definition at line 244 of file MSVehicleControl.h.
References MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, MSVehicleControl::myWaitingForContainer, and MSVehicleControl::myWaitingForPerson.
Referenced by libsumo::Simulation::getMinExpectedNumber(), and MSNet::simulationState().
getCollisionCount()
int MSVehicleControl::getCollisionCount () const inline inherited
return the number of collisions
Definition at line 250 of file MSVehicleControl.h.
References MSVehicleControl::myCollisions.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSNet::closeSimulation(), and GUINet::getParameterWindow().
getDepartedVehicleNo()
int MSVehicleControl::getDepartedVehicleNo () const inline inherited
Returns the number of inserted vehicles.
Returns
The number of vehicles that have entered the simulation so far
Definition at line 226 of file MSVehicleControl.h.
References MSVehicleControl::getQuota(), MSVehicleControl::myDiscarded, MSVehicleControl::myEndedVehNo, and MSVehicleControl::myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSNet::postSimStepOutput(), and MSNet::writeOutput().
getEmergencyStops()
int MSVehicleControl::getEmergencyStops () const inline inherited
return the number of emergency stops
Definition at line 273 of file MSVehicleControl.h.
References MSVehicleControl::myEmergencyStops.
Referenced by MSNet::closeSimulation().
getEndedVehicleNo()
int MSVehicleControl::getEndedVehicleNo () const inline inherited
Returns the number of removed vehicles.
Returns
The number of vehicles that have left the simulation
Definition at line 210 of file MSVehicleControl.h.
References MSVehicleControl::myEndedVehNo.
Referenced by GUINet::getParameterWindow(), and MSNet::writeOutput().
getLoadedVehicleNo()
int MSVehicleControl::getLoadedVehicleNo () const inline inherited
Returns the number of build vehicles.
Returns
The number of loaded (build) vehicles
Definition at line 202 of file MSVehicleControl.h.
References MSVehicleControl::myLoadedVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and MSNet::writeOutput().
getMaxSpeedFactor()
double MSVehicleControl::getMaxSpeedFactor () const inline inherited
return the maximum speed factor for all vehicles that ever entered the network
Definition at line 460 of file MSVehicleControl.h.
References MSVehicleControl::myMaxSpeedFactor.
Referenced by MSLane::getMaximumBrakeDist().
getMinDeceleration()
double MSVehicleControl::getMinDeceleration () const inline inherited
return the minimum deceleration capability for all vehicles that ever entered the network
Definition at line 465 of file MSVehicleControl.h.
References MSVehicleControl::adaptIntermodalRouter(), MSVehicleControl::checkVType(), and MSVehicleControl::myMinDeceleration.
Referenced by MSLane::getMaximumBrakeDist().
getQuota()
int MSVehicleControl::getQuota (double frac = -1) const inherited
Returns the number of instances of the current vehicle that shall be emitted considering that "frac" of all vehicles shall be emitted overall if a negative fraction is given the demand scaling factor is used (–scale)
Returns
the number of vehicles to create (something between 0 and ceil(frac))
Definition at line 394 of file MSVehicleControl.cpp.
References MSVehicleControl::myLoadedVehNo, and MSVehicleControl::myScale.
Referenced by MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), and MSVehicleControl::getDepartedVehicleNo().
getRunningVehicleNo()
int MSVehicleControl::getRunningVehicleNo () const inline inherited
Returns the number of build and inserted, but not yet deleted vehicles.
Returns
The number simulated vehicles (including those in teleporter)
Definition at line 218 of file MSVehicleControl.h.
References MSVehicleControl::myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), GUIApplicationWindow::handleEvent_SimulationStep(), MSNet::postSimStepOutput(), GUINet::setSimDuration(), MSNet::simulationStep(), and MSNet::writeOutput().
getTeleportCount()
int MSVehicleControl::getTeleportCount () const inherited
return the number of teleports (including collisions)
Definition at line 412 of file MSVehicleControl.cpp.
References MSVehicleControl::myCollisions, MSVehicleControl::myTeleportsJam, MSVehicleControl::myTeleportsWrongLane, MSVehicleControl::myTeleportsYield, and MSLane::teleportOnCollision().
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSVehicleControl::getTeleportsWrongLane(), and MSNet::simulationState().
getTeleportsJam()
int MSVehicleControl::getTeleportsJam () const inline inherited
return the number of teleports due to jamming
Definition at line 255 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsJam.
Referenced by MSNet::closeSimulation().
getTeleportsWrongLane()
int MSVehicleControl::getTeleportsWrongLane () const inline inherited
return the number of teleports due to vehicles stuck on the wrong lane
Definition at line 265 of file MSVehicleControl.h.
References MSVehicleControl::getTeleportCount(), and MSVehicleControl::myTeleportsWrongLane.
Referenced by MSNet::closeSimulation().
getTeleportsYield()
int MSVehicleControl::getTeleportsYield () const inline inherited
return the number of teleports due to vehicles stuck on a minor road
Definition at line 260 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsYield.
Referenced by MSNet::closeSimulation().
getTotalDepartureDelay()
double MSVehicleControl::getTotalDepartureDelay () const inline inherited
Returns the total departure delay.
Returns
Sum of steps vehicles had to wait until being inserted
Definition at line 281 of file MSVehicleControl.h.
References MSVehicleControl::myTotalDepartureDelay.
Referenced by MSNet::writeOutput().
getTotalTravelTime()
double MSVehicleControl::getTotalTravelTime () const inline inherited
Returns the total travel time.
Returns
Sum of travel times of arrived vehicles
Definition at line 289 of file MSVehicleControl.h.
References MSVehicleControl::addVType(), MSVehicleControl::addVTypeDistribution(), MSVehicleControl::addWaiting(), DEFAULT_VTYPE_ID, MSVehicleControl::getVType(), MSVehicleControl::getWaitingVehicle(), MSVehicleControl::hasVType(), MSVehicleControl::hasVTypeDistribution(), MSVehicleControl::insertVTypeIDs(), MSVehicleControl::myTotalTravelTime, MSVehicleControl::removeVType(), and MSVehicleControl::removeWaiting().
Referenced by MSNet::writeOutput().
getVehicle()
SUMOVehicle * MSVehicleControl::getVehicle (const std::string & id) const inherited
Returns the vehicle with the given id.
If no vehicle with the given id is store din "myVehicleDict", 0 is returned.
Parameters
[in] id The id of the vehicle to retrieve
Returns
The vehicle with the given id, 0 if no such vehicle exists
Definition at line 213 of file MSVehicleControl.cpp.
References MSVehicleControl::myVehicleDict.
Referenced by libsumo::Vehicle::add(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), TraCIServerAPI_Vehicle::getPosition(), libsumo::Vehicle::getVehicle(), libsumo::Vehicle::isOnInit(), MSVehicleTransfer::loadState(), MESegment::loadState(), MSLane::loadState(), MSDevice_SSM::processEncounters(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), MSCalibrator::removePending(), and GUINet::vehicleExists().
getVType()
MSVehicleType * MSVehicleControl::getVType (const std::string & id = DEFAULT_VTYPE_ID, std::mt19937 * rng = 0) inherited
Returns the named vehicle type or a sample from the named distribution.
Parameters
[in] id The id of the vehicle type to return. If left out, the default type is returned.
Returns
The named vehicle type, or 0 if no such type exists
Definition at line 303 of file MSVehicleControl.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, MSVehicleControl::myDefaultPedTypeMayBeDeleted, MSVehicleControl::myDefaultVTypeMayBeDeleted, MSVehicleControl::myVTypeDict, and MSVehicleControl::myVTypeDistDict.
Referenced by libsumo::Person::add(), libsumo::Vehicle::add(), MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), libsumo::Simulation::findIntermodalRoute(), libsumo::Simulation::findRoute(), MSVehicleControl::getTotalTravelTime(), libsumo::VehicleType::getVType(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSDevice_Bluelight::notifyMove(), MSRouteHandler::openVehicleTypeDistribution(), TraCIServerAPI_Vehicle::processSet(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), libsumo::Person::setType(), libsumo::Vehicle::setType(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
getWaitingVehicle()
SUMOVehicle * MSVehicleControl::getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > & lines, const double position, const std::string ridingID) inherited
Definition at line 354 of file MSVehicleControl.cpp.
References DEPART_TRIGGERED, Named::getID(), SUMOVehicle::getParameter(), SUMOVehicleParameter::line, MSVehicleControl::myWaiting, toString(), and WRITE_WARNING.
Referenced by MSVehicleControl::getTotalTravelTime(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
hasVType()
bool MSVehicleControl::hasVType (const std::string & id) const inherited
Asks for existence of a vehicle type.
If vehicle type or distribution with the id exists, true is returned, false otherwise.
Parameters
[in] id The id of the type or distribution
Returns
Whether the vehicle type or distribution exists
Definition at line 291 of file MSVehicleControl.cpp.
References MSVehicleControl::myVTypeDict, and MSVehicleControl::myVTypeDistDict.
Referenced by libsumo::Simulation::findIntermodalRoute(), and MSVehicleControl::getTotalTravelTime().
hasVTypeDistribution()
bool MSVehicleControl::hasVTypeDistribution (const std::string & id) const inherited
Asks for a vehicle type distribution.
If vehicle type distribution with the id exists, true is returned, false otherwise.
Parameters
[in] id The id of the distribution
Returns
Whether the vehicle type distribution exists
Definition at line 297 of file MSVehicleControl.cpp.
References MSVehicleControl::myVTypeDistDict.
Referenced by MSVehicleControl::getTotalTravelTime().
insertVTypeIDs()
void MSVehicleControl::insertVTypeIDs (std::vector< std::string > & into) const inherited
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
Parameters
[in] into The vector to fill with ids
Definition at line 322 of file MSVehicleControl.cpp.
References MSVehicleControl::myVTypeDict, and MSVehicleControl::myVTypeDistDict.
Referenced by libsumo::VehicleType::getIDList(), and MSVehicleControl::getTotalTravelTime().
loadedVehBegin()
constVehIt MSVehicleControl::loadedVehBegin () const inline inherited
Returns the begin of the internal vehicle map.
Returns
The begin of the internal vehicle map
Definition at line 166 of file MSVehicleControl.h.
References MSVehicleControl::myVehicleDict.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSVTypeProbe::execute(), MSNet::getHaltingVehicleNumber(), libsumo::Vehicle::getIDList(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSNet::getVehicleMeanSpeeds(), MSDevice_Bluelight::notifyMove(), MSVehicleType::setActionStepLength(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), and MSFullExport::writeVehicles().
loadedVehEnd()
constVehIt MSVehicleControl::loadedVehEnd () const inline inherited
Returns the end of the internal vehicle map.
Returns
The end of the internal vehicle map
Definition at line 174 of file MSVehicleControl.h.
References MSVehicleControl::myVehicleDict, and MSVehicleControl::vehicleDeparted().
Referenced by GUIApplicationWindow::checkGamingEvents(), MSVTypeProbe::execute(), MSNet::getHaltingVehicleNumber(), libsumo::Vehicle::getIDList(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSNet::getVehicleMeanSpeeds(), MSDevice_Bluelight::notifyMove(), MSVehicleType::setActionStepLength(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), and MSFullExport::writeVehicles().
operator=()
MEVehicleControl& MEVehicleControl::operator= (const MEVehicleControl & s) private
invalidated assignment operator
registerCollision()
void MSVehicleControl::registerCollision () inline inherited
registers one collision-related teleport
Definition at line 404 of file MSVehicleControl.h.
References MSVehicleControl::myCollisions.
Referenced by MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSLane::executeMovements(), and MSLane::handleCollisionBetween().
registerEmergencyStop()
void MSVehicleControl::registerEmergencyStop () inline inherited
register emergency stop
Definition at line 424 of file MSVehicleControl.h.
References MSVehicleControl::myEmergencyStops, MSVehicleControl::saveState(), and MSVehicleControl::setState().
Referenced by MSVehicle::executeMove().
registerOneWaiting()
void MSVehicleControl::registerOneWaiting (const bool isPerson) inline inherited
increases the count of vehicles waiting for a transport to allow recognition of person / container related deadlocks
Definition at line 385 of file MSVehicleControl.h.
References MSVehicleControl::myWaitingForContainer, and MSVehicleControl::myWaitingForPerson.
Referenced by MSVehicleControl::addVehicle(), and MSVehicle::processNextStop().
registerTeleportJam()
void MSVehicleControl::registerTeleportJam () inline inherited
register one non-collision-related teleport
Definition at line 409 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsJam.
Referenced by MSLane::executeMovements(), and MELoop::teleportVehicle().
registerTeleportWrongLane()
void MSVehicleControl::registerTeleportWrongLane () inline inherited
register one non-collision-related teleport
Definition at line 419 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsWrongLane.
Referenced by MSLane::executeMovements().
registerTeleportYield()
void MSVehicleControl::registerTeleportYield () inline inherited
register one non-collision-related teleport
Definition at line 414 of file MSVehicleControl.h.
References MSVehicleControl::myTeleportsYield.
Referenced by MSLane::executeMovements().
removeVType()
void MSVehicleControl::removeVType (const MSVehicleType * vehType) inherited
Definition at line 272 of file MSVehicleControl.cpp.
References MSVehicleType::getID(), and MSVehicleControl::myVTypeDict.
Referenced by MSVehicleControl::getTotalTravelTime(), MSBaseVehicle::replaceVehicleType(), MSTransportable::replaceVehicleType(), MSTransportable::~MSTransportable(), and MSVehicle::~MSVehicle().
removeWaiting()
void MSVehicleControl::removeWaiting (const MSEdge *const edge, SUMOVehicle * vehicle) inherited
Removes a vehicle from the list of waiting vehicles to a given edge.
Definition at line 343 of file MSVehicleControl.cpp.
References MSVehicleControl::myWaiting.
Referenced by MSVehicleControl::getTotalTravelTime(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), and MSVehicle::resumeFromStopping().
saveState()
void MSVehicleControl::saveState (OutputDevice & out) inherited
Saves the current state into the given stream.
Definition at line 164 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalDepartureDelay, MSVehicleControl::myTotalTravelTime, MSVehicleControl::myVehicleDict, MSVehicleControl::myVTypeDict, MSVehicleControl::myVTypeDistDict, OutputDevice::openTag(), SUMO_ATTR_BEGIN, SUMO_ATTR_DEPART, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_NUMBER, SUMO_ATTR_PROBS, SUMO_ATTR_TIME, SUMO_ATTR_VTYPES, SUMO_TAG_DELAY, SUMO_TAG_VTYPE_DISTRIBUTION, and OutputDevice::writeAttr().
Referenced by MSVehicleControl::registerEmergencyStop(), and MSStateHandler::saveState().
scheduleVehicleRemoval()
void MSVehicleControl::scheduleVehicleRemoval (SUMOVehicle * veh) inherited
Removes a vehicle after it has ended.
Writes output to tripinfos and vehroutes if wished; decrements the number of running vehicles and increments the number of ended vehicles. Then deletes the vehicle using "deleteVehicle".
This method should be called for each vehicle that was inserted into the network and quits its ride.
Parameters
[in] veh The vehicle to remove
Definition at line 124 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), MSVehicleControl::deleteVehicle(), SUMOVehicle::getDeparture(), OutputDevice::getDeviceByOption(), SUMOVehicle::getDevices(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::informVehicleStateListener(), MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalTravelTime, STEPS2TIME, and MSNet::VEHICLE_STATE_ARRIVED.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), MSVehicleTransfer::checkInsertions(), MSLane::detectCollisions(), MSLane::executeMovements(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MSCalibrator::removePending().
setState()
void MSVehicleControl::setState (int runningVehNo, int loadedVehNo, int endedVehNo, double totalDepartureDelay, double totalTravelTime) inherited
Sets the current state variables as loaded from the stream.
Definition at line 154 of file MSVehicleControl.cpp.
References MSVehicleControl::myEndedVehNo, MSVehicleControl::myLoadedVehNo, MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalDepartureDelay, and MSVehicleControl::myTotalTravelTime.
Referenced by MSStateHandler::myStartElement(), and MSVehicleControl::registerEmergencyStop().
unregisterOneWaiting()
void MSVehicleControl::unregisterOneWaiting (const bool isPerson) inline inherited
decreases the count of vehicles waiting for a transport to allow recognition of person / container related deadlocks
Definition at line 395 of file MSVehicleControl.h.
References MSVehicleControl::myWaitingForContainer, and MSVehicleControl::myWaitingForPerson.
Referenced by MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
vehicleDeparted()
void MSVehicleControl::vehicleDeparted (const SUMOVehicle & v) inherited
Informs this control about a vehicle's departure.
If the mean waiting time shall be computed (f.e. for summary-output), the absolut waiting time is increased by the waiting time of the given vehicle.
Parameters
[in] v The inserted vehicle
Definition at line 141 of file MSVehicleControl.cpp.
References SUMOVehicleParameter::depart, MSVehicleType::getCarFollowModel(), SUMOVehicle::getChosenSpeedFactor(), SUMOVehicle::getDeparture(), MSNet::getInstance(), MSCFModel::getMaxDecel(), SUMOVehicle::getParameter(), SUMOVehicle::getVClass(), SUMOVehicle::getVehicleType(), MSNet::informVehicleStateListener(), MAX2(), MIN2(), MSVehicleControl::myMaxSpeedFactor, MSVehicleControl::myMinDeceleration, MSVehicleControl::myRunningVehNo, MSVehicleControl::myTotalDepartureDelay, STEPFLOOR, STEPS2TIME, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, and MSNet::VEHICLE_STATE_DEPARTED.
Referenced by MSVehicleControl::loadedVehEnd(), and MSBaseVehicle::onDepart().
Field Documentation
myLoadedVehNo
int MSVehicleControl::myLoadedVehNo protected inherited
The number of build vehicles.
Definition at line 485 of file MSVehicleControl.h.
Referenced by buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::discountStateLoaded(), MSVehicleControl::getActiveVehicleCount(), MSVehicleControl::getLoadedVehicleNo(), MSVehicleControl::getQuota(), MSVehicleControl::saveState(), and MSVehicleControl::setState().
myVehicleDict
VehicleDictType MSVehicleControl::myVehicleDict protected inherited
Dictionary of vehicles.
Definition at line 533 of file MSVehicleControl.h.
Referenced by MSVehicleControl::abortWaiting(), MSVehicleControl::addVehicle(), MSVehicleControl::deleteVehicle(), MSVehicleControl::getVehicle(), GUIMEVehicleControl::insertVehicleIDs(), GUIVehicleControl::insertVehicleIDs(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), MSVehicleControl::saveState(), and MSVehicleControl::~MSVehicleControl().
The documentation for this class was generated from the following files:
MEVehicleControl.h
MEVehicleControl.cpp