SUMO - Simulation of Urban MObility: MSSOTLPolicy5DFamilyStimulus Class Reference
MSSOTLPolicy5DFamilyStimulus Class Reference
#include <MSSOTLPolicy5DFamilyStimulus.h>
Public Member Functions
void clearParameter ()
Clears the parameter map.
virtual double computeDesirability (double vehInMeasure, double vehOutMeasure)
Calculates the desirability of the policy.
virtual double computeDesirability (double vehInMeasure, double vehOutMeasure, double vehInDispersionMeasure, double vehOutDispersionMeasure)
Calculates the desirability of the policy.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
std::vector< MSSOTLPolicy5DStimulus * > getFamilies ()
std::string getKeyPrefix ()
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
std::string getMessage ()
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSSOTLPolicy5DFamilyStimulus (std::string keyPrefix, const std::map< std::string, std::string > &parameters)
void setKeyPrefix (std::string val)
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Protected Member Functions
double readParameter (std::string parName, double defValue)
Private Attributes
std::map< std::string, std::string > default_values
std::vector< MSSOTLPolicy5DStimulus * > family
std::vector< std::string > params_names
Detailed Description
Definition at line 49 of file MSSOTLPolicy5DFamilyStimulus.h.
Constructor & Destructor Documentation
MSSOTLPolicy5DFamilyStimulus()
MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus (std::string keyPrefix, const std::map< std::string, std::string > & parameters)
Definition at line 38 of file MSSOTLPolicy5DFamilyStimulus.cpp.
References DBG, default_values, family, Parameterised::getParameter(), StringTokenizer::getVector(), params_names, MSSOTLPolicyDesirability::readParameter(), WRITE_ERROR, and WRITE_MESSAGE.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
computeDesirability() [1/2]
double MSSOTLPolicy5DFamilyStimulus::computeDesirability (double vehInMeasure, double vehOutMeasure) virtual
Calculates the desirability of the policy.
Implements MSSOTLPolicyDesirability.
Definition at line 146 of file MSSOTLPolicy5DFamilyStimulus.cpp.
Referenced by getFamilies().
computeDesirability() [2/2]
double MSSOTLPolicy5DFamilyStimulus::computeDesirability (double vehInMeasure, double vehOutMeasure, double vehInDispersionMeasure, double vehOutDispersionMeasure) virtual
Calculates the desirability of the policy.
Implements MSSOTLPolicyDesirability.
Definition at line 115 of file MSSOTLPolicy5DFamilyStimulus.cpp.
References DBG, family, and WRITE_MESSAGE.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getFamilies()
std::vector<MSSOTLPolicy5DStimulus*> MSSOTLPolicy5DFamilyStimulus::getFamilies () inline
Definition at line 70 of file MSSOTLPolicy5DFamilyStimulus.h.
References computeDesirability(), and family.
getKeyPrefix()
std::string MSSOTLPolicyDesirability::getKeyPrefix () inline inherited
Definition at line 73 of file MSSOTLPolicyDesirability.h.
References MSSOTLPolicyDesirability::myKeyPrefix.
Referenced by MSSOTLPolicy5DStimulus::getStimCox(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut(), MSSOTLPolicy5DStimulus::getStimCoxExpIn(), MSSOTLPolicy5DStimulus::getStimCoxExpOut(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut(), MSSOTLPolicy5DStimulus::getStimDivisorIn(), MSSOTLPolicy5DStimulus::getStimDivisorOut(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut(), MSSOTLPolicy5DStimulus::getStimOffsetIn(), and MSSOTLPolicy5DStimulus::getStimOffsetOut().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getMessage()
std::string MSSOTLPolicy5DFamilyStimulus::getMessage () virtual
Implements MSSOTLPolicyDesirability.
Definition at line 151 of file MSSOTLPolicy5DFamilyStimulus.cpp.
References family.
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
readParameter()
double MSSOTLPolicyDesirability::readParameter (std::string parName, double defValue) inline protected inherited
Definition at line 48 of file MSSOTLPolicyDesirability.h.
References TplConvert::_2doubleSec(), MSSOTLPolicyDesirability::computeDesirability(), MSSOTLPolicyDesirability::getMessage(), Parameterised::getParameter(), MSSOTLPolicyDesirability::MSSOTLPolicyDesirability(), and MSSOTLPolicyDesirability::~MSSOTLPolicyDesirability().
Referenced by MSSOTLPolicy5DStimulus::getStimCox(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut(), MSSOTLPolicy5DStimulus::getStimCoxExpIn(), MSSOTLPolicy5DStimulus::getStimCoxExpOut(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut(), MSSOTLPolicy5DStimulus::getStimDivisorIn(), MSSOTLPolicy5DStimulus::getStimDivisorOut(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut(), MSSOTLPolicy5DStimulus::getStimOffsetIn(), MSSOTLPolicy5DStimulus::getStimOffsetOut(), and MSSOTLPolicy5DFamilyStimulus().
setKeyPrefix()
void MSSOTLPolicyDesirability::setKeyPrefix (std::string val) inline inherited
Definition at line 70 of file MSSOTLPolicyDesirability.h.
Referenced by MSSOTLCongestionPolicy::MSSOTLCongestionPolicy(), MSSOTLMarchingPolicy::MSSOTLMarchingPolicy(), MSSOTLPhasePolicy::MSSOTLPhasePolicy(), MSSOTLPlatoonPolicy::MSSOTLPlatoonPolicy(), and MSSOTLRequestPolicy::MSSOTLRequestPolicy().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
default_values
std::map<std::string, std::string> MSSOTLPolicy5DFamilyStimulus::default_values private
Definition at line 58 of file MSSOTLPolicy5DFamilyStimulus.h.
Referenced by MSSOTLPolicy5DFamilyStimulus().
family
std::vector<MSSOTLPolicy5DStimulus*> MSSOTLPolicy5DFamilyStimulus::family private
Definition at line 60 of file MSSOTLPolicy5DFamilyStimulus.h.
Referenced by computeDesirability(), getFamilies(), getMessage(), and MSSOTLPolicy5DFamilyStimulus().
params_names
std::vector<std::string> MSSOTLPolicy5DFamilyStimulus::params_names private
Definition at line 59 of file MSSOTLPolicy5DFamilyStimulus.h.
Referenced by MSSOTLPolicy5DFamilyStimulus().
The documentation for this class was generated from the following files:
MSSOTLPolicy5DFamilyStimulus.h
MSSOTLPolicy5DFamilyStimulus.cpp