SUMO - Simulation of Urban MObility: RouteCostCalculator< R, E, V > Class Template Reference
RouteCostCalculator< R, E, V > Class Template Reference abstract
Abstract base class providing static factory method.
#include <RouteCostCalculator.h>
Public Member Functions
virtual void calculateProbabilities (std::vector< R *> alternatives, const V *const veh, const SUMOTime time)=0
calculate the probabilities in the logit model
int getMaxRouteNumber () const
bool keepRoutes () const
virtual void setCosts (R *route, const double costs, const bool isActive=false) const =0
bool skipRouteCalculation () const
Static Public Member Functions
static void cleanup ()
static RouteCostCalculator< R, E, V > & getCalculator ()
Protected Member Functions
RouteCostCalculator ()
Constructor.
virtual ~RouteCostCalculator ()
Destructor.
Private Attributes
bool myKeepRoutes
Information whether all routes should be saved.
int myMaxRouteNumber
The maximum route alternatives number.
bool mySkipRouteCalculation
Information whether new routes should be calculated.
Static Private Attributes
static RouteCostCalculator * myInstance = 0
Detailed Description
template<class R, class E, class V>
class RouteCostCalculator< R, E, V >
Abstract base class providing static factory method.
Definition at line 50 of file RouteCostCalculator.h.
Constructor & Destructor Documentation
RouteCostCalculator()
template<class R, class E, class V> RouteCostCalculator< R, E, V >::RouteCostCalculator () inline protected
Constructor.
Definition at line 78 of file RouteCostCalculator.h.
References OptionsCont::getBool(), OptionsCont::getInt(), OptionsCont::getOptions(), RouteCostCalculator< R, E, V >::myKeepRoutes, RouteCostCalculator< R, E, V >::myMaxRouteNumber, and RouteCostCalculator< R, E, V >::mySkipRouteCalculation.
~RouteCostCalculator()
template<class R, class E, class V> virtual RouteCostCalculator< R, E, V >::~RouteCostCalculator () inline protected virtual
Destructor.
Definition at line 86 of file RouteCostCalculator.h.
Member Function Documentation
calculateProbabilities()
template<class R, class E, class V> virtual void RouteCostCalculator< R, E, V >::calculateProbabilities (std::vector< R *> alternatives, const V *const veh, const SUMOTime time) pure virtual
calculate the probabilities in the logit model
Implemented in GawronCalculator< R, E, V >, and LogitCalculator< R, E, V >.
Referenced by RouteCostCalculator< R, E, V >::cleanup().
cleanup()
template<class R, class E, class V> static void RouteCostCalculator< R, E, V >::cleanup () inline static
Definition at line 54 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::calculateProbabilities(), RouteCostCalculator< R, E, V >::myInstance, and RouteCostCalculator< R, E, V >::setCosts().
Referenced by RONet::cleanup().
getCalculator()
template<class R , class E , class V > RouteCostCalculator< R, E, V > & RouteCostCalculator< R, E, V >::getCalculator () static
Definition at line 114 of file RouteCostCalculator.h.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and RouteCostCalculator< R, E, V >::myInstance.
Referenced by RORouteDef::addAlternative(), and ROMAAssignments::sue().
getMaxRouteNumber()
template<class R, class E, class V> int RouteCostCalculator< R, E, V >::getMaxRouteNumber () const inline
Definition at line 64 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myMaxRouteNumber.
keepRoutes()
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::keepRoutes () const inline
Definition at line 68 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myKeepRoutes.
Referenced by RORouteDef::addAlternative().
setCosts()
template<class R, class E, class V> virtual void RouteCostCalculator< R, E, V >::setCosts (R * route, const double costs, const bool isActive = false) const pure virtual
Implemented in LogitCalculator< R, E, V >, and GawronCalculator< R, E, V >.
Referenced by RouteCostCalculator< R, E, V >::cleanup().
skipRouteCalculation()
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::skipRouteCalculation () const inline
Definition at line 72 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::mySkipRouteCalculation.
Field Documentation
myInstance
template<class R, class E, class V> RouteCostCalculator< R, E, V > * RouteCostCalculator< R, E, V >::myInstance = 0 static private
Definition at line 89 of file RouteCostCalculator.h.
Referenced by RouteCostCalculator< R, E, V >::cleanup(), and RouteCostCalculator< R, E, V >::getCalculator().
myKeepRoutes
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::myKeepRoutes private
Information whether all routes should be saved.
Definition at line 95 of file RouteCostCalculator.h.
Referenced by RouteCostCalculator< R, E, V >::keepRoutes(), and RouteCostCalculator< R, E, V >::RouteCostCalculator().
myMaxRouteNumber
template<class R, class E, class V> int RouteCostCalculator< R, E, V >::myMaxRouteNumber private
The maximum route alternatives number.
Definition at line 92 of file RouteCostCalculator.h.
Referenced by RouteCostCalculator< R, E, V >::getMaxRouteNumber(), and RouteCostCalculator< R, E, V >::RouteCostCalculator().
mySkipRouteCalculation
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::mySkipRouteCalculation private
Information whether new routes should be calculated.
Definition at line 98 of file RouteCostCalculator.h.
Referenced by RouteCostCalculator< R, E, V >::RouteCostCalculator(), and RouteCostCalculator< R, E, V >::skipRouteCalculation().
The documentation for this class was generated from the following file:
RouteCostCalculator.h