SUMO - Simulation of Urban MObility: SUMOTime.cpp File Reference
SUMOTime.cpp File Reference
#include <config.h>
#include <sstream>
#include "SUMOTime.h"
#include "TplConvert.h"
#include "StdDefs.h"
Functions
SUMOTime string2time (const std::string &r)
std::string time2string (SUMOTime t)
Variables
SUMOTime DELTA_T = 1000
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Fri, 29.04.2005
Version
$Id$
Definition in file SUMOTime.cpp.
Function Documentation
string2time()
SUMOTime string2time (const std::string & r)
Definition at line 46 of file SUMOTime.cpp.
References STEPS2TIME, SUMOTime_MAX, and TIME2STEPS.
Referenced by ODMatrix::add(), MSDetectorControl::add(), MSDetectorControl::addDetectorAndInterval(), NLHandler::addEdgeLaneMeanData(), NLBuilder::build(), NLBuilder::buildRouteLoaderControl(), MELoop::buildSegmentsFor(), NLTriggerBuilder::buildVaporizer(), MSDevice_Routing::buildVehicleDevices(), MSFrame::checkOptions(), MSDevice_Routing::checkOptions(), TraCIServer::cleanup(), MSNet::closeBuilding(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), computeRoutes(), MSPhaseDefinition::init(), MSLane::initCollisionOptions(), GUISettingsHandler::loadBreakpoints(), main(), MSNet::MSNet(), MSPModel_Striping::MSPModel_Striping(), MSVehicleControl::MSVehicleControl(), SUMORouteHandler::myEndElement(), MSStateHandler::myStartElement(), GUIDialog_Breakpoints::onCmdEditTable(), ROLoader::openRoutes(), TraCIServer::openSocket(), SUMOVehicleParameter::parseDepart(), SUMOVehicleParserHelper::parseVTypeEmbedded(), readDetectorFlows(), MSDevice_Routing::reroute(), GUILoadThread::run(), TraCITestClient::run(), MSFrame::setMSGlobals(), and startComputation().
time2string()
std::string time2string (SUMOTime t)
Definition at line 59 of file SUMOTime.cpp.
References gPrecision, and STEPS2TIME.
Referenced by MSPModel_Striping::add(), libsumo::Person::add(), MSVehicleTransfer::add(), IntermodalRouter< E, L, N, V >::addSchedule(), GUIRunThread::begin(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLBuilder::build(), CHBuilder< E, V >::buildContractionHierarchy(), NLBuilder::buildNet(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), CHRouter< E, V, PF >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), NBOwnTLDef::computeLogicAndConts(), computeRoutes(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSOTLPolicy::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), GUIVehicle::drawRouteHelper(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), GUITLLogicPhasesTrackerWindow::drawValues(), GUIDialog_Breakpoints::encode2TXT(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSDevice_Tripinfo::generateOutput(), MSVehicle::getBackPositionOnLane(), IntermodalTrip< E, N, V >::getID(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), MSPModel_Striping::getNextLane(), MSDevice_Routing::getParameter(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUICalibrator::getParameterWindow(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUIVehicle::getStopInfo(), MSLane::handleCollisionBetween(), GUIApplicationWindow::handleEvent_SimulationEnded(), ROMAAssignments::incremental(), MSVehicle::Influencer::influenceChangeDecision(), MSActuatedTrafficLightLogic::init(), MSEdge::insertVehicle(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::leaveLane(), GUIRunThread::makeStep(), MSPModel_Striping::moveInDirectionOnLane(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::notifyEnter(), MSCalibrator::VehicleRemover::notifyEnter(), ROLoader::openRoutes(), MSNet::postSimStepOutput(), MSNet::preSimStepOutput(), MSVehicle::processLaneAdvances(), ROLoader::processRoutes(), GUIDialog_Breakpoints::rebuildList(), MSPerson::MSPersonStage_Walking::routeOutput(), MSContainer::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), MSPerson::routeOutput(), MSStateHandler::saveState(), MSNet::simulate(), MSNet::simulationStep(), MSStopOut::stopEnded(), MSLane::succLinkSec(), MELoop::teleportVehicle(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSContainer::tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), MSPerson::tripInfoOutput(), MSSOTLTrafficLightLogic::trySwitch(), MSSOTLTrafficLightLogic::updateDecayThreshold(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateShadowLane(), MSPModel_Striping::PState::walk(), MSBatteryExport::write(), MSQueueExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::write(), MSXMLRawOut::write(), ODMatrix::write(), SUMOVehicleParameter::write(), MSLink::writeApproaching(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), ODMatrix::writeFlows(), writeInterval(), MSDevice_Vehroutes::writeOutput(), MSNet::writeOutput(), RODFDetector::writeSingleSpeedTrigger(), ROLoader::writeStats(), TrajectoriesHandler::writeXMLEmissions(), MEInductLoop::writeXMLOutput(), MSRouteProbe::writeXMLOutput(), MSCalibrator::writeXMLOutput(), MSE3Collector::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and MSDevice_Vehroutes::writeXMLRoute().
Variable Documentation
DELTA_T
SUMOTime DELTA_T = 1000
Definition at line 39 of file SUMOTime.cpp.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), MSTransportableControl::add(), GUITLLogicPhasesTrackerWindow::addValue(), MSTransportableControl::boardAnyWaiting(), MSFrame::buildStreams(), MSInsertionControl::checkCandidates(), MSLaneChanger::checkChange(), RONet::checkFlows(), GUIApplicationWindow::checkGamingEvents(), MSE2Collector::checkJam(), GUISUMOAbstractView::checkSnapshots(), NLJunctionControlBuilder::closeTrafficLightLogic(), MSVehicleControl::computeRandomDepartOffset(), MSSOTLTrafficLightLogic::computeReturnTime(), MSSwarmTrafficLightLogic::computeReturnTime(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSLane::detectCollisionBetween(), MSMeanData::detectorUpdate(), MSInsertionControl::determineCandidates(), TraCIServer::dispatchCommand(), MSVehicle::enterLaneAtInsertion(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSEventControl::execute(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSPModel_Striping::MovePedestrians::execute(), MSVehicle::executeMove(), MSDevice_Tripinfo::generateOutput(), TrackerValueDesc::getAggregationSpan(), MEVehicle::getConservativeSpeed(), MSInductLoop::getCurrentLength(), MSInductLoop::getCurrentOccupancy(), MSInductLoop::getCurrentPassedNumber(), MSInductLoop::getCurrentSpeed(), MSInductLoop::getCurrentVehicleIDs(), libsumo::Simulation::getDeltaT(), GUINet::getRTFactor(), MSLeaderInfo::getSubLanes(), libsumo::InductionLoop::getVehicleData(), MSVehicle::hasStops(), MSVehicle::Influencer::influenceSpeed(), MSVehicle::keepStopping(), GUIRunThread::makeStep(), MSCFModel_Rail::maxNextSpeed(), MSCFModel_Rail::minNextSpeed(), MSPModel_Striping::MSPModel_Striping(), MSRailSignal::MSRailSignal(), MSDevice_Tripinfo::notifyMove(), MSVehicleContainer::DepartFinder::operator()(), NLTriggerBuilder::parseAndBuildCalibrator(), SUMOVehicleParserHelper::parseVTypeEmbedded(), MSVehicle::planMoveInternal(), MSNet::postSimStepOutput(), MSDevice_Routing::preInsertionReroute(), SUMOVehicleParserHelper::processActionStepLength(), TraCIServerAPI_Vehicle::processSet(), GUIRunThread::run(), TrackerValueDesc::setAggregationSpan(), MSFrame::setMSGlobals(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSTransportableControl::setWaitEnd(), MELoop::simulate(), MSNet::simulationStep(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSInsertionControl::tryInsert(), MSOffTrafficLightLogic::trySwitch(), MSRailSignal::trySwitch(), MSAbstractLaneChangeModel::unchanged(), MSLaneChanger::updateChanger(), MSAbstractLaneChangeModel::updateCompletion(), MSRailCrossing::updateCurrentPhase(), MSRailSignal::updateCurrentPhase(), GUIApplicationWindow::updateTimeLCD(), MSVehicle::updateWaitingTime(), MSPModel_Striping::PState::walk(), ODMatrix::write(), MSNet::writeOutput(), and MSMeanData::writeXMLOutput().