SUMO - Simulation of Urban MObility: libsumo::Lane Class Reference
libsumo::Lane Class Reference
#include <Lane.h>
Static Public Member Functions
static std::vector< std::string > getAllowed (std::string laneID)
static double getCO2Emission (std::string laneID)
static double getCOEmission (std::string laneID)
static std::vector< std::string > getDisallowed (std::string laneID)
static std::string getEdgeID (std::string laneID)
static double getElectricityConsumption (std::string laneID)
static std::vector< std::string > getFoes (const std::string &laneID, const std::string &toLaneID)
static double getFuelConsumption (std::string laneID)
static double getHCEmission (std::string laneID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::vector< std::string > getInternalFoes (const std::string &laneID)
static const MSLane * getLane (const std::string &id)
static int getLastStepHaltingNumber (std::string laneID)
static double getLastStepLength (std::string laneID)
static double getLastStepMeanSpeed (std::string laneID)
static double getLastStepOccupancy (std::string laneID)
static std::vector< std::string > getLastStepVehicleIDs (std::string laneID)
static int getLastStepVehicleNumber (std::string laneID)
static double getLength (std::string laneID)
static int getLinkNumber (std::string laneID)
static std::vector< TraCIConnection > getLinks (std::string laneID)
static double getMaxSpeed (std::string laneID)
static double getNoiseEmission (std::string laneID)
static double getNOxEmission (std::string laneID)
static std::string getParameter (const std::string &laneID, const std::string &param)
static double getPMxEmission (std::string laneID)
static TraCIPositionVector getShape (std::string laneID)
static double getTraveltime (std::string laneID)
static double getWaitingTime (std::string laneID)
static double getWidth (std::string laneID)
static void setAllowed (std::string laneID, std::vector< std::string > allowedClasses)
static void setDisallowed (std::string laneID, std::vector< std::string > disallowedClasses)
static void setLength (std::string laneID, double length)
static void setMaxSpeed (std::string laneID, double speed)
static void setParameter (const std::string &routeID, const std::string &key, const std::string &value)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
Lane ()
invalidated standard constructor
Lane (const Lane &src)
invalidated copy constructor
Lane & operator= (const Lane &src)
invalidated assignment operator
Detailed Description
Definition at line 52 of file Lane.h.
Constructor & Destructor Documentation
Lane() [1/2]
libsumo::Lane::Lane () private
invalidated standard constructor
Lane() [2/2]
libsumo::Lane::Lane (const Lane & src) private
invalidated copy constructor
Member Function Documentation
getAllowed()
std::vector< std::string > Lane::getAllowed (std::string laneID) static
Definition at line 109 of file Lane.cpp.
References getLane(), MSLane::getPermissions(), getVehicleClassNamesList(), and SVCAll.
Referenced by TraCIServerAPI_Lane::processGet().
getCO2Emission()
double Lane::getCO2Emission (std::string laneID) static
Definition at line 146 of file Lane.cpp.
References MSLane::getCO2Emissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getCOEmission()
double Lane::getCOEmission (std::string laneID) static
Definition at line 152 of file Lane.cpp.
References MSLane::getCOEmissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getDisallowed()
std::vector< std::string > Lane::getDisallowed (std::string laneID) static
Definition at line 119 of file Lane.cpp.
References getLane(), getVehicleClassNamesList(), and invertPermissions().
Referenced by TraCIServerAPI_Lane::processGet().
getEdgeID()
std::string Lane::getEdgeID (std::string laneID) static
Definition at line 61 of file Lane.cpp.
References MSLane::getEdge(), Named::getID(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getElectricityConsumption()
double Lane::getElectricityConsumption (std::string laneID) static
Definition at line 187 of file Lane.cpp.
References MSLane::getElectricityConsumption(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getFoes()
std::vector< std::string > Lane::getFoes (const std::string & laneID, const std::string & toLaneID) static
Definition at line 271 of file Lane.cpp.
References MSLinkContHelper::getConnectingLink(), MSLink::getFoeLinks(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getFuelConsumption()
double Lane::getFuelConsumption (std::string laneID) static
Definition at line 175 of file Lane.cpp.
References MSLane::getFuelConsumption(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getHCEmission()
double Lane::getHCEmission (std::string laneID) static
Definition at line 158 of file Lane.cpp.
References MSLane::getHCEmissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getIDCount()
int Lane::getIDCount () static
Definition at line 55 of file Lane.cpp.
References getIDList().
Referenced by TraCIServerAPI_Lane::processGet().
getIDList()
std::vector< std::string > Lane::getIDList () static
Definition at line 47 of file Lane.cpp.
References MSLane::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Lane::processGet().
getInternalFoes()
std::vector< std::string > Lane::getInternalFoes (const std::string & laneID) static
Definition at line 287 of file Lane.cpp.
References MSLink::getFoeLanes(), getLane(), MSLane::getLinkCont(), and MSLane::isInternal().
Referenced by TraCIServerAPI_Lane::processGet().
getLane()
const MSLane * Lane::getLane (const std::string & id) static
Definition at line 349 of file Lane.cpp.
References MSLane::dictionary().
Referenced by getAllowed(), getCO2Emission(), getCOEmission(), getDisallowed(), getEdgeID(), getElectricityConsumption(), getFoes(), getFuelConsumption(), getHCEmission(), getInternalFoes(), getLastStepHaltingNumber(), getLastStepLength(), getLastStepMeanSpeed(), getLastStepOccupancy(), getLastStepVehicleIDs(), getLastStepVehicleNumber(), getLength(), getLinkNumber(), getLinks(), getMaxSpeed(), getNoiseEmission(), getNOxEmission(), getParameter(), getPMxEmission(), getShape(), getTraveltime(), getWaitingTime(), getWidth(), setAllowed(), setDisallowed(), setLength(), setMaxSpeed(), and setParameter().
getLastStepHaltingNumber()
int Lane::getLastStepHaltingNumber (std::string laneID) static
Definition at line 244 of file Lane.cpp.
References getLane(), MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMO_const_haltingSpeed.
Referenced by TraCIServerAPI_Lane::processGet().
getLastStepLength()
double Lane::getLastStepLength (std::string laneID) static
Definition at line 205 of file Lane.cpp.
References getLane(), MSLane::getVehiclesSecure(), and MSLane::releaseVehicles().
Referenced by TraCIServerAPI_Lane::processGet().
getLastStepMeanSpeed()
double Lane::getLastStepMeanSpeed (std::string laneID) static
Definition at line 193 of file Lane.cpp.
References getLane(), and MSLane::getMeanSpeed().
Referenced by TraCIServerAPI_Lane::processGet().
getLastStepOccupancy()
double Lane::getLastStepOccupancy (std::string laneID) static
Definition at line 199 of file Lane.cpp.
References getLane(), and MSLane::getNettoOccupancy().
Referenced by TraCIServerAPI_Lane::processGet().
getLastStepVehicleIDs()
std::vector< std::string > Lane::getLastStepVehicleIDs (std::string laneID) static
Definition at line 259 of file Lane.cpp.
References getLane(), MSLane::getVehiclesSecure(), and MSLane::releaseVehicles().
Referenced by TraCIServerAPI_Lane::processGet().
getLastStepVehicleNumber()
int Lane::getLastStepVehicleNumber (std::string laneID) static
Definition at line 239 of file Lane.cpp.
References getLane(), and MSLane::getVehicleNumber().
Referenced by TraCIServerAPI_Lane::processGet().
getLength()
double Lane::getLength (std::string laneID) static
Definition at line 67 of file Lane.cpp.
References getLane(), and MSLane::getLength().
Referenced by TraCIServerAPI_Lane::processGet().
getLinkNumber()
int Lane::getLinkNumber (std::string laneID) static
Definition at line 79 of file Lane.cpp.
References getLane(), and MSLane::getLinkCont().
Referenced by TraCIServerAPI_Lane::processGet().
getLinks()
std::vector< TraCIConnection > Lane::getLinks (std::string laneID) static
Definition at line 85 of file Lane.cpp.
References MSNet::getCurrentTimeStep(), SUMOVTypeParameter::getDefault(), SUMOVTypeParameter::getDefaultDecel(), MSLink::getDirection(), Named::getID(), MSNet::getInstance(), getLane(), MSLink::getLane(), MSLink::getLength(), MSLane::getLinkCont(), MSLane::getSpeedLimit(), MSLink::getState(), StringBijection< T >::getString(), MSLink::getViaLane(), MSLink::hasApproachingFoe(), MSLink::havePriority(), SUMOXMLDefinitions::LinkDirections, SUMOXMLDefinitions::LinkStates, MIN2(), and MSLink::opened().
Referenced by TraCIServerAPI_Lane::processGet().
getMaxSpeed()
double Lane::getMaxSpeed (std::string laneID) static
Definition at line 73 of file Lane.cpp.
References getLane(), and MSLane::getSpeedLimit().
Referenced by TraCIServerAPI_Lane::processGet().
getNoiseEmission()
double Lane::getNoiseEmission (std::string laneID) static
Definition at line 181 of file Lane.cpp.
References MSLane::getHarmonoise_NoiseEmissions(), and getLane().
Referenced by TraCIServerAPI_Lane::processGet().
getNOxEmission()
double Lane::getNOxEmission (std::string laneID) static
Definition at line 170 of file Lane.cpp.
References getLane(), and MSLane::getNOxEmissions().
Referenced by TraCIServerAPI_Lane::processGet().
getParameter()
std::string Lane::getParameter (const std::string & laneID, const std::string & param) static
Definition at line 336 of file Lane.cpp.
References getLane(), and Parameterised::getParameter().
Referenced by TraCIServerAPI_Lane::processGet().
getPMxEmission()
double Lane::getPMxEmission (std::string laneID) static
Definition at line 164 of file Lane.cpp.
References getLane(), and MSLane::getPMxEmissions().
Referenced by TraCIServerAPI_Lane::processGet().
getShape()
TraCIPositionVector Lane::getShape (std::string laneID) static
Definition at line 125 of file Lane.cpp.
References getLane(), MSLane::getShape(), libsumo::TraCIPosition::x, libsumo::TraCIPosition::y, and libsumo::TraCIPosition::z.
Referenced by TraCIServerAPI_Lane::processGet().
getTraveltime()
double Lane::getTraveltime (std::string laneID) static
Definition at line 227 of file Lane.cpp.
References getLane(), MSLane::getLength(), and MSLane::getMeanSpeed().
Referenced by TraCIServerAPI_Lane::processGet().
getWaitingTime()
double Lane::getWaitingTime (std::string laneID) static
Definition at line 221 of file Lane.cpp.
References getLane(), and MSLane::getWaitingSeconds().
Referenced by TraCIServerAPI_Lane::processGet().
getWidth()
double Lane::getWidth (std::string laneID) static
Definition at line 140 of file Lane.cpp.
References getLane(), and MSLane::getWidth().
Referenced by TraCIServerAPI_Lane::processGet().
operator=()
Lane& libsumo::Lane::operator= (const Lane & src) private
invalidated assignment operator
setAllowed()
void Lane::setAllowed (std::string laneID, std::vector< std::string > allowedClasses) static
Definition at line 306 of file Lane.cpp.
References MSLane::CHANGE_PERMISSIONS_PERMANENT, MSLane::getEdge(), getLane(), parseVehicleClasses(), MSEdge::rebuildAllowedLanes(), and MSLane::setPermissions().
Referenced by TraCIServerAPI_Lane::processSet().
setDisallowed()
void Lane::setDisallowed (std::string laneID, std::vector< std::string > disallowedClasses) static
Definition at line 314 of file Lane.cpp.
References MSLane::CHANGE_PERMISSIONS_PERMANENT, MSLane::getEdge(), getLane(), invertPermissions(), parseVehicleClasses(), MSEdge::rebuildAllowedLanes(), and MSLane::setPermissions().
Referenced by TraCIServerAPI_Lane::processSet().
setLength()
void Lane::setLength (std::string laneID, double length) static
Definition at line 329 of file Lane.cpp.
References getLane(), and MSLane::setLength().
Referenced by TraCIServerAPI_Lane::processSet().
setMaxSpeed()
void Lane::setMaxSpeed (std::string laneID, double speed) static
Definition at line 322 of file Lane.cpp.
References getLane(), and MSLane::setMaxSpeed().
Referenced by TraCIServerAPI_Lane::processSet().
setParameter()
void Lane::setParameter (const std::string & routeID, const std::string & key, const std::string & value) static
Definition at line 342 of file Lane.cpp.
References getLane(), and Parameterised::setParameter().
Referenced by TraCIServerAPI_Lane::processSet().
subscribe()
static void libsumo::Lane::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
subscribeContext()
static void libsumo::Lane::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
Lane.h
Lane.cpp