SUMO - Simulation of Urban MObility: MSDevice_Tripinfo Class Reference
MSDevice_Tripinfo Class Reference
A device which collects info on the vehicle trip (mainly on departure and arrival)
#include <MSDevice_Tripinfo.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const std::string deviceName () const
return the name for this type of device
void generateOutput () const
Called on writing tripinfo output.
const std::string & getDescription () const
SUMOVehicle & getHolder () const
Returns the vehicle that holds this device.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
virtual std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this device. Throw exception for unsupported key
void loadState (const SUMOSAXAttributes &attrs)
Loads the state of the device from the given description.
void saveState (OutputDevice &out) const
Saves the state of the device.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
virtual void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this device. Throw exception for unsupported key
void updateStatistics (SUMOTime timeLoss) const
update tripinfo statistics
~MSDevice_Tripinfo ()
Destructor.
Methods called on vehicle movement / state change, overwriting MSDevice
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Checks for waiting steps when the vehicle moves.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Saves departure info on insertion.
bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Saves arrival info.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Static Public Member Functions
static void addPedestrianData (double walkLength, SUMOTime walkDuration, SUMOTime walkTimeLoss)
record tripinfo data for pedestrians
static void addRideData (double rideLength, SUMOTime rideDuration, SUMOVehicleClass vClass, const std::string &line, SUMOTime waitingTime)
record tripinfo data for rides
static void buildVehicleDevices (SUMOVehicle &v, std::vector< MSDevice *> &into)
Build devices for the given vehicle, if needed.
static bool checkOptions (OptionsCont &oc)
check device-specific options
static void cleanup ()
resets counters
static void cleanupAll ()
perform cleanup for all devices
static void generateOutputForUnfinished ()
generate output for vehicles which are still in the network
static double getAvgDepartDelay ()
static double getAvgDuration ()
static double getAvgRideDuration ()
static double getAvgRideRouteLength ()
static double getAvgRideWaitingTime ()
static double getAvgRouteLength ()
accessors for GUINet-Parameters
static double getAvgTimeLoss ()
static double getAvgWaitingTime ()
static double getAvgWalkDuration ()
static double getAvgWalkRouteLength ()
static double getAvgWalkTimeLoss ()
static std::mt19937 * getEquipmentRNG ()
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void insertOptions (OptionsCont &oc)
Inserts options for building devices.
static std::string printStatistics ()
get statistics for printing to stdout
Protected Member Functions
void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double)
Internal notification about the vehicle moves, see MSMoveReminder::notifyMoveInternal()
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Static Protected Member Functions
Helper methods for device assignment
static void insertDefaultAssignmentOptions (const std::string &deviceName, const std::string &optionsTopic, OptionsCont &oc)
Adds common command options that allow to assign devices to vehicles.
static bool equippedByDefaultAssignmentOptions (const OptionsCont &oc, const std::string &deviceName, SUMOVehicle &v)
Determines whether a vehicle should get a certain device.
Protected Attributes
std::string myDescription
a description of this moveReminder
SUMOVehicle & myHolder
The vehicle that stores the device.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Private Types
typedef std::set< const MSDevice_Tripinfo *, Named::NamedLikeComparatorIdLess< MSDevice_Tripinfo > > DeviceSet
devices which may still need to produce output
Private Member Functions
void computeLengthAndDuration (double &routeLength, SUMOTime &duration) const
MSDevice_Tripinfo (SUMOVehicle &holder, const std::string &id)
Constructor.
MSDevice_Tripinfo ()
dummy constructor
MSDevice_Tripinfo (const MSDevice_Tripinfo &)
Invalidated copy constructor.
MSDevice_Tripinfo & operator= (const MSDevice_Tripinfo &)
Invalidated assignment operator.
Private Attributes
std::string myArrivalLane
The lane the vehicle arrived at.
double myArrivalPos
The position on the lane the vehicle arrived at.
double myArrivalPosLat
The lateral position on the lane the vehicle arrived at.
double myArrivalSpeed
The speed when arriving.
SUMOTime myArrivalTime
The vehicle's arrival time.
std::string myDepartLane
The lane the vehicle departed at.
double myDepartPosLat
The lateral depart position.
double myDepartSpeed
The speed on departure.
SUMOTime myMesoTimeLoss
The time loss when compared to the desired and allowed speed.
SUMOTime myWaitingTime
The overall waiting time.
Static Private Attributes
static DeviceSet myPendingOutput
static int myRideAbortCount
static int myRideBikeCount
static int myRideBusCount
static int myRideCount
static int myRideRailCount
static SUMOTime myTotalDepartDelay
static SUMOTime myTotalDuration
static SUMOTime myTotalRideDuration
static double myTotalRideRouteLength
static double myTotalRideWaitingTime
static double myTotalRouteLength
static SUMOTime myTotalTimeLoss
static SUMOTime myTotalWaitingTime
static SUMOTime myTotalWalkDuration
static double myTotalWalkRouteLength
static SUMOTime myTotalWalkTimeLoss
static double myVehicleCount
global tripinfo statistics
static int myWalkCount
Detailed Description
A device which collects info on the vehicle trip (mainly on departure and arrival)
Each device collects departure time, lane and speed and the same for arrival.
See also
MSDevice
Definition at line 53 of file MSDevice_Tripinfo.h.
Member Typedef Documentation
DeviceSet
typedef std::set<const MSDevice_Tripinfo*, Named::NamedLikeComparatorIdLess<MSDevice_Tripinfo> > MSDevice_Tripinfo::DeviceSet private
devices which may still need to produce output
Definition at line 231 of file MSDevice_Tripinfo.h.
Member Enumeration Documentation
Notification
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
~MSDevice_Tripinfo()
MSDevice_Tripinfo::~MSDevice_Tripinfo ()
Destructor.
Definition at line 105 of file MSDevice_Tripinfo.cpp.
References myPendingOutput.
MSDevice_Tripinfo() [1/3]
MSDevice_Tripinfo::MSDevice_Tripinfo (SUMOVehicle & holder, const std::string & id) private
Constructor.
Parameters
[in] holder The vehicle that holds this device
[in] id The ID of the device
Definition at line 90 of file MSDevice_Tripinfo.cpp.
MSDevice_Tripinfo() [2/3]
MSDevice_Tripinfo::MSDevice_Tripinfo () private
dummy constructor
Referenced by buildVehicleDevices(), and deviceName().
MSDevice_Tripinfo() [3/3]
MSDevice_Tripinfo::MSDevice_Tripinfo (const MSDevice_Tripinfo &) private
Invalidated copy constructor.
Member Function Documentation
addPedestrianData()
void MSDevice_Tripinfo::addPedestrianData (double walkLength, SUMOTime walkDuration, SUMOTime walkTimeLoss) static
record tripinfo data for pedestrians
Definition at line 311 of file MSDevice_Tripinfo.cpp.
References myTotalWalkDuration, myTotalWalkRouteLength, myTotalWalkTimeLoss, and myWalkCount.
Referenced by MSPerson::MSPersonStage_Walking::tripInfoOutput().
addRideData()
void MSDevice_Tripinfo::addRideData (double rideLength, SUMOTime rideDuration, SUMOVehicleClass vClass, const std::string & line, SUMOTime waitingTime) static
record tripinfo data for rides
Definition at line 319 of file MSDevice_Tripinfo.cpp.
References isRailway(), myRideAbortCount, myRideBikeCount, myRideBusCount, myRideCount, myRideRailCount, myTotalRideDuration, myTotalRideRouteLength, myTotalRideWaitingTime, and SVC_BICYCLE.
Referenced by MSPerson::MSPersonStage_Driving::tripInfoOutput().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
buildVehicleDevices()
void MSDevice_Tripinfo::buildVehicleDevices (SUMOVehicle & v, std::vector< MSDevice *> & into) static
Build devices for the given vehicle, if needed.
The options are read and evaluated whether a tripinfo-device shall be built for the given vehicle.
The built device is stored in the given vector.
Parameters
[in] v The vehicle for which a device may be built
Definition at line 78 of file MSDevice_Tripinfo.cpp.
References SUMOVehicle::getID(), OptionsCont::getOptions(), MSDevice_Tripinfo(), and myPendingOutput.
Referenced by MSDevice::buildVehicleDevices().
checkOptions()
bool MSDevice::checkOptions (OptionsCont & oc) static inherited
check device-specific options
Parameters
Definition at line 73 of file MSDevice.cpp.
References MSDevice_Routing::checkOptions().
Referenced by MSFrame::checkOptions().
cleanup()
void MSDevice_Tripinfo::cleanup () static
resets counters
Definition at line 111 of file MSDevice_Tripinfo.cpp.
References myRideAbortCount, myRideBikeCount, myRideBusCount, myRideCount, myRideRailCount, myTotalDepartDelay, myTotalDuration, myTotalRideDuration, myTotalRideRouteLength, myTotalRideWaitingTime, myTotalRouteLength, myTotalTimeLoss, myTotalWaitingTime, myTotalWalkDuration, myTotalWalkRouteLength, myTotalWalkTimeLoss, myVehicleCount, and myWalkCount.
Referenced by MSDevice::cleanupAll().
cleanupAll()
void MSDevice::cleanupAll () static inherited
perform cleanup for all devices
Definition at line 95 of file MSDevice.cpp.
References cleanup(), and MSDevice_Routing::cleanup().
Referenced by MSNet::clearAll(), and MSDevice::getEquipmentRNG().
computeLengthAndDuration()
void MSDevice_Tripinfo::computeLengthAndDuration (double & routeLength, SUMOTime & duration) const private
Definition at line 200 of file MSDevice_Tripinfo.cpp.
References MSRoute::begin(), SUMOVehicle::getCurrentRouteEdge(), MSNet::getCurrentTimeStep(), SUMOVehicle::getDepartPos(), SUMOVehicle::getDeparture(), MSRoute::getDistanceBetween(), SUMOVehicle::getEdge(), MSLane::getEdge(), MSNet::getInstance(), MSMoveReminder::getLane(), MSEdge::getLength(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getRoute(), MSGlobals::gUseMesoSim, MSGlobals::gUsingInternalLanes, MSNet::hasInternalLinks(), MSEdge::isInternal(), myArrivalPos, myArrivalTime, MSDevice::myHolder, and NOT_ARRIVED.
Referenced by deviceName(), generateOutput(), and updateStatistics().
deviceName()
const std::string MSDevice_Tripinfo::deviceName () const inline virtual
return the name for this type of device
Implements MSDevice.
Definition at line 144 of file MSDevice_Tripinfo.h.
References computeLengthAndDuration(), generateOutput(), loadState(), MSDevice_Tripinfo(), notifyMoveInternal(), and saveState().
equippedByDefaultAssignmentOptions()
bool MSDevice::equippedByDefaultAssignmentOptions (const OptionsCont & oc, const std::string & deviceName, SUMOVehicle & v) static protected inherited
Determines whether a vehicle should get a certain device.
Parameters
[in] oc The options container to get the information about assignment from
[in] deviceName The name of the device type
[in] v The vehicle to determine whether it shall be equipped or not
Definition at line 115 of file MSDevice.cpp.
References TplConvert::_2bool(), MSDevice::deviceName(), OptionsCont::exists(), OptionsCont::getBool(), OptionsCont::getFloat(), SUMOVehicle::getID(), MSNet::getInstance(), OptionsCont::getOptions(), Parameterised::getParameter(), SUMOVehicle::getParameter(), MSVehicleType::getParameter(), MSVehicleControl::getQuota(), OptionsCont::getStringVector(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), OptionsCont::isSet(), Parameterised::knowsParameter(), MSDevice::myEquipmentRNG, MSDevice::myExplicitIDs, and RandHelper::rand().
Referenced by MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSDevice_SSM::buildVehicleDevices(), and MSDevice::setParameter().
generateOutput()
void MSDevice_Tripinfo::generateOutput () const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
See also
MSDevice::generateOutput
Reimplemented from MSDevice.
Definition at line 227 of file MSDevice_Tripinfo.cpp.
References computeLengthAndDuration(), DELTA_T, MSRoute::end(), SUMOVehicle::getChosenSpeedFactor(), SUMOVehicle::getDepartDelay(), SUMOVehicle::getDepartPos(), SUMOVehicle::getDeparture(), OutputDevice::getDeviceByOption(), SUMOVehicle::getDevices(), SUMOVehicle::getEdge(), SUMOVehicle::getID(), MSVehicleType::getID(), SUMOVehicle::getNumberReroutes(), OptionsCont::getOptions(), SUMOVehicle::getRoute(), SUMOVehicle::getVehicleType(), MSGlobals::gLateralResolution, MSGlobals::gUseMesoSim, myArrivalLane, myArrivalPos, myArrivalPosLat, myArrivalSpeed, myArrivalTime, myDepartLane, myDepartPosLat, myDepartSpeed, MSDevice::myHolder, myMesoTimeLoss, myPendingOutput, myWaitingTime, OutputDevice::openTag(), time2string(), updateStatistics(), and OutputDevice::writeAttr().
Referenced by deviceName(), and generateOutputForUnfinished().
generateOutputForUnfinished()
void MSDevice_Tripinfo::generateOutputForUnfinished () static
generate output for vehicles which are still in the network
Definition at line 278 of file MSDevice_Tripinfo.cpp.
References OutputDevice::closeTag(), generateOutput(), OutputDevice::getDeviceByOption(), OptionsCont::getOptions(), SUMOVehicle::hasDeparted(), MSDevice::myHolder, and myPendingOutput.
Referenced by MSNet::closeSimulation().
getAvgDepartDelay()
double MSDevice_Tripinfo::getAvgDepartDelay () static
Definition at line 411 of file MSDevice_Tripinfo.cpp.
References myTotalDepartDelay, myVehicleCount, and STEPS2TIME.
Referenced by GUINet::getAvgDepartDelay(), and printStatistics().
getAvgDuration()
double MSDevice_Tripinfo::getAvgDuration () static
Definition at line 382 of file MSDevice_Tripinfo.cpp.
References myTotalDuration, myVehicleCount, and STEPS2TIME.
Referenced by GUINet::getAvgDuration(), GUINet::getAvgTripSpeed(), and printStatistics().
getAvgRideDuration()
double MSDevice_Tripinfo::getAvgRideDuration () static
Definition at line 450 of file MSDevice_Tripinfo.cpp.
References myRideCount, myTotalRideDuration, and STEPS2TIME.
Referenced by printStatistics().
getAvgRideRouteLength()
double MSDevice_Tripinfo::getAvgRideRouteLength () static
Definition at line 468 of file MSDevice_Tripinfo.cpp.
References myRideCount, and myTotalRideRouteLength.
Referenced by printStatistics().
getAvgRideWaitingTime()
double MSDevice_Tripinfo::getAvgRideWaitingTime () static
Definition at line 459 of file MSDevice_Tripinfo.cpp.
References myRideCount, myTotalRideWaitingTime, and STEPS2TIME.
Referenced by printStatistics().
getAvgRouteLength()
double MSDevice_Tripinfo::getAvgRouteLength () static
accessors for GUINet-Parameters
Definition at line 373 of file MSDevice_Tripinfo.cpp.
References myTotalRouteLength, and myVehicleCount.
Referenced by GUINet::getAvgRouteLength(), GUINet::getAvgTripSpeed(), and printStatistics().
getAvgTimeLoss()
double MSDevice_Tripinfo::getAvgTimeLoss () static
Definition at line 401 of file MSDevice_Tripinfo.cpp.
References myTotalTimeLoss, myVehicleCount, and STEPS2TIME.
Referenced by GUINet::getAvgTimeLoss(), and printStatistics().
getAvgWaitingTime()
double MSDevice_Tripinfo::getAvgWaitingTime () static
Definition at line 391 of file MSDevice_Tripinfo.cpp.
References myTotalWaitingTime, myVehicleCount, and STEPS2TIME.
Referenced by GUINet::getAvgWaitingTime(), and printStatistics().
getAvgWalkDuration()
double MSDevice_Tripinfo::getAvgWalkDuration () static
Definition at line 430 of file MSDevice_Tripinfo.cpp.
References myTotalWalkDuration, myWalkCount, and STEPS2TIME.
Referenced by GUINet::getAvgWalkDuration(), and printStatistics().
getAvgWalkRouteLength()
double MSDevice_Tripinfo::getAvgWalkRouteLength () static
Definition at line 421 of file MSDevice_Tripinfo.cpp.
References myTotalWalkRouteLength, and myWalkCount.
Referenced by GUINet::getAvgWalkRouteLength(), and printStatistics().
getAvgWalkTimeLoss()
double MSDevice_Tripinfo::getAvgWalkTimeLoss () static
Definition at line 440 of file MSDevice_Tripinfo.cpp.
References myTotalWalkTimeLoss, myWalkCount, and STEPS2TIME.
Referenced by GUINet::getAvgWalkTimeLoss(), and printStatistics().
getDescription()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 234 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::getSingularType(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::write().
getEquipmentRNG()
static std::mt19937* MSDevice::getEquipmentRNG () inline static inherited
Definition at line 90 of file MSDevice.h.
References MSDevice::cleanupAll(), MSDevice::deviceName(), and MSDevice::myEquipmentRNG.
Referenced by NLBuilder::init(), and GUILoadThread::run().
getHolder()
SUMOVehicle& MSDevice::getHolder () const inline inherited
Returns the vehicle that holds this device.
Returns
The vehicle that holds this device
Definition at line 119 of file MSDevice.h.
References MSDevice::myHolder.
Referenced by MSChargingStation::addChargeValueForOutput().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getLane()
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by computeLengthAndDuration(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), libsumo::InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
getParameter()
virtual std::string MSDevice::getParameter (const std::string & key) const inline virtual inherited
try to retrieve the given parameter from this device. Throw exception for unsupported key
Reimplemented in MSDevice_Routing, MSDevice_Bluelight, MSDevice_Example, MSDevice_Transportable, and MSDevice_Battery.
Definition at line 154 of file MSDevice.h.
References MSDevice::deviceName().
insertDefaultAssignmentOptions()
void MSDevice::insertDefaultAssignmentOptions (const std::string & deviceName, const std::string & optionsTopic, OptionsCont & oc) static protected inherited
Adds common command options that allow to assign devices to vehicles.
Parameters
[in] deviceName The name of the device type
[in] optionsTopic The options topic into which the options shall be added
!! describe
!! describe
!! describe
Definition at line 101 of file MSDevice.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), and OptionsCont::doRegister().
Referenced by MSDevice_Battery::insertOptions(), MSDevice_Bluelight::insertOptions(), MSDevice_Example::insertOptions(), MSDevice_BTsender::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Emissions::insertOptions(), MSDevice_Routing::insertOptions(), MSDevice_SSM::insertOptions(), and MSDevice::setParameter().
insertOptions()
void MSDevice::insertOptions (OptionsCont & oc) static inherited
Inserts options for building devices.
Parameters
Definition at line 60 of file MSDevice.cpp.
References MSDevice_Battery::insertOptions(), MSDevice_Bluelight::insertOptions(), MSDevice_Example::insertOptions(), MSDevice_BTsender::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Emissions::insertOptions(), MSDevice_Routing::insertOptions(), and MSDevice_SSM::insertOptions().
Referenced by MSFrame::fillOptions().
loadState()
void MSDevice_Tripinfo::loadState (const SUMOSAXAttributes & attrs) virtual
Loads the state of the device from the given description.
Parameters
[in] attrs XML attributes describing the current state
Reimplemented from MSDevice.
Definition at line 491 of file MSDevice_Tripinfo.cpp.
References SUMOSAXAttributes::getString(), myDepartLane, myDepartPosLat, myDepartSpeed, and SUMO_ATTR_STATE.
Referenced by deviceName().
notifyEnter()
bool MSDevice_Tripinfo::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Saves departure info on insertion.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
Always true
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 165 of file MSDevice_Tripinfo.cpp.
References Named::getID(), MSMoveReminder::getLane(), SUMOVehicle::getSpeed(), MSGlobals::gUseMesoSim, myDepartLane, myDepartPosLat, myDepartSpeed, and MSMoveReminder::NOTIFICATION_DEPARTED.
notifyLeave()
bool MSDevice_Tripinfo::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Saves arrival info.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
Returns
True if it did not leave the net.
Reimplemented from MSMoveReminder.
Definition at line 178 of file MSDevice_Tripinfo.cpp.
References SUMOVehicle::getArrivalPos(), MSNet::getCurrentTimeStep(), Named::getID(), MSNet::getInstance(), MSMoveReminder::getLane(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getSpeed(), MSGlobals::gUseMesoSim, myArrivalLane, myArrivalPos, myArrivalPosLat, myArrivalSpeed, myArrivalTime, MSDevice::myHolder, MSMoveReminder::NOTIFICATION_ARRIVED, and MSMoveReminder::NOTIFICATION_VAPORIZED.
notifyMove()
bool MSDevice_Tripinfo::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual
Checks for waiting steps when the vehicle moves.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True (always).
Reimplemented from MSMoveReminder.
Definition at line 135 of file MSDevice_Tripinfo.cpp.
References DELTA_T, SUMOVehicle::isStopped(), myWaitingTime, and SUMO_const_haltingSpeed.
notifyMoveInternal()
void MSDevice_Tripinfo::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double) protected virtual
Internal notification about the vehicle moves, see MSMoveReminder::notifyMoveInternal()
Reimplemented from MSMoveReminder.
Definition at line 147 of file MSDevice_Tripinfo.cpp.
References SUMOVehicle::getEdge(), MSEdge::getVehicleMaxSpeed(), SUMOVehicle::getWaitingTime(), myMesoTimeLoss, myWaitingTime, and TIME2STEPS.
Referenced by deviceName().
operator=()
MSDevice_Tripinfo& MSDevice_Tripinfo::operator= (const MSDevice_Tripinfo &) private
Invalidated assignment operator.
printStatistics()
std::string MSDevice_Tripinfo::printStatistics () static
get statistics for printing to stdout
Definition at line 342 of file MSDevice_Tripinfo.cpp.
References getAvgDepartDelay(), getAvgDuration(), getAvgRideDuration(), getAvgRideRouteLength(), getAvgRideWaitingTime(), getAvgRouteLength(), getAvgTimeLoss(), getAvgWaitingTime(), getAvgWalkDuration(), getAvgWalkRouteLength(), getAvgWalkTimeLoss(), gPrecision, myRideAbortCount, myRideBikeCount, myRideBusCount, myRideCount, myRideRailCount, and myWalkCount.
Referenced by MSNet::closeSimulation().
removeFromVehicleUpdateValues()
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 93 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
saveState()
void MSDevice_Tripinfo::saveState (OutputDevice & out) const virtual
Saves the state of the device.
Parameters
[in] out The OutputDevice to write the information into
Reimplemented from MSDevice.
Definition at line 478 of file MSDevice_Tripinfo.cpp.
References OutputDevice::closeTag(), Named::getID(), myDepartLane, myDepartPosLat, myDepartSpeed, OutputDevice::openTag(), SUMO_ATTR_ID, SUMO_ATTR_STATE, SUMO_TAG_DEVICE, toString(), and OutputDevice::writeAttr().
Referenced by deviceName().
setDescription()
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 230 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setParameter()
virtual void MSDevice::setParameter (const std::string & key, const std::string & value) inline virtual inherited
try to set the given parameter for this device. Throw exception for unsupported key
Reimplemented in MSDevice_Routing, MSDevice_Bluelight, MSDevice_Example, and MSDevice_Battery.
Definition at line 159 of file MSDevice.h.
References MSDevice::deviceName(), MSDevice::equippedByDefaultAssignmentOptions(), MSDevice::insertDefaultAssignmentOptions(), and UNUSED_PARAMETER.
updateDetector()
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 50 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
updateStatistics()
void MSDevice_Tripinfo::updateStatistics (SUMOTime timeLoss) const
update tripinfo statistics
Definition at line 296 of file MSDevice_Tripinfo.cpp.
References computeLengthAndDuration(), SUMOVehicle::getDepartDelay(), MSDevice::myHolder, myTotalDepartDelay, myTotalDuration, myTotalRouteLength, myTotalTimeLoss, myTotalWaitingTime, myVehicleCount, and myWaitingTime.
Referenced by generateOutput().
Field Documentation
myArrivalLane
std::string MSDevice_Tripinfo::myArrivalLane private
The lane the vehicle arrived at.
Definition at line 216 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), and notifyLeave().
myArrivalPos
double MSDevice_Tripinfo::myArrivalPos private
The position on the lane the vehicle arrived at.
Definition at line 219 of file MSDevice_Tripinfo.h.
Referenced by computeLengthAndDuration(), generateOutput(), and notifyLeave().
myArrivalPosLat
double MSDevice_Tripinfo::myArrivalPosLat private
The lateral position on the lane the vehicle arrived at.
Definition at line 222 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), and notifyLeave().
myArrivalSpeed
double MSDevice_Tripinfo::myArrivalSpeed private
The speed when arriving.
Definition at line 225 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), and notifyLeave().
myArrivalTime
SUMOTime MSDevice_Tripinfo::myArrivalTime private
The vehicle's arrival time.
Definition at line 213 of file MSDevice_Tripinfo.h.
Referenced by computeLengthAndDuration(), generateOutput(), and notifyLeave().
myDepartLane
std::string MSDevice_Tripinfo::myDepartLane private
The lane the vehicle departed at.
Definition at line 201 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), loadState(), notifyEnter(), and saveState().
myDepartPosLat
double MSDevice_Tripinfo::myDepartPosLat private
The lateral depart position.
Definition at line 207 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), loadState(), notifyEnter(), and saveState().
myDepartSpeed
double MSDevice_Tripinfo::myDepartSpeed private
The speed on departure.
Definition at line 204 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), loadState(), notifyEnter(), and saveState().
myDescription
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 246 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
myHolder
SUMOVehicle& MSDevice::myHolder protected inherited
The vehicle that stores the device.
Definition at line 188 of file MSDevice.h.
Referenced by MSDevice_Vehroutes::addRoute(), MSDevice_Transportable::addTransportable(), computeLengthAndDuration(), generateOutput(), generateOutputForUnfinished(), MSDevice::getHolder(), MSDevice_Routing::getParameter(), MSDevice_Vehroutes::notifyEnter(), notifyLeave(), MSDevice_Routing::preInsertionReroute(), MSDevice_Transportable::removeTransportable(), MSDevice_Routing::reroute(), MSDevice_Routing::setParameter(), MSDevice_SSM::updateAndWriteOutput(), updateStatistics(), MSDevice_Vehroutes::writeOutput(), MSDevice_Vehroutes::writeXMLRoute(), and MSDevice_Vehroutes::~MSDevice_Vehroutes().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myLane
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 244 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), and MSMeanData::MeanDataValueTracker::reset().
myMesoTimeLoss
SUMOTime MSDevice_Tripinfo::myMesoTimeLoss private
The time loss when compared to the desired and allowed speed.
Definition at line 228 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), and notifyMoveInternal().
myPendingOutput
MSDevice_Tripinfo::DeviceSet MSDevice_Tripinfo::myPendingOutput static private
Definition at line 233 of file MSDevice_Tripinfo.h.
Referenced by buildVehicleDevices(), generateOutput(), generateOutputForUnfinished(), and ~MSDevice_Tripinfo().
myRideAbortCount
int MSDevice_Tripinfo::myRideAbortCount static private
Definition at line 252 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and printStatistics().
myRideBikeCount
int MSDevice_Tripinfo::myRideBikeCount static private
Definition at line 251 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and printStatistics().
myRideBusCount
int MSDevice_Tripinfo::myRideBusCount static private
Definition at line 249 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and printStatistics().
myRideCount
int MSDevice_Tripinfo::myRideCount static private
Definition at line 248 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), getAvgRideDuration(), getAvgRideRouteLength(), getAvgRideWaitingTime(), and printStatistics().
myRideRailCount
int MSDevice_Tripinfo::myRideRailCount static private
Definition at line 250 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and printStatistics().
myTotalDepartDelay
SUMOTime MSDevice_Tripinfo::myTotalDepartDelay static private
Definition at line 241 of file MSDevice_Tripinfo.h.
Referenced by cleanup(), getAvgDepartDelay(), and updateStatistics().
myTotalDuration
SUMOTime MSDevice_Tripinfo::myTotalDuration static private
Definition at line 238 of file MSDevice_Tripinfo.h.
Referenced by cleanup(), getAvgDuration(), and updateStatistics().
myTotalRideDuration
SUMOTime MSDevice_Tripinfo::myTotalRideDuration static private
Definition at line 255 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and getAvgRideDuration().
myTotalRideRouteLength
double MSDevice_Tripinfo::myTotalRideRouteLength static private
Definition at line 254 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and getAvgRideRouteLength().
myTotalRideWaitingTime
double MSDevice_Tripinfo::myTotalRideWaitingTime static private
Definition at line 253 of file MSDevice_Tripinfo.h.
Referenced by addRideData(), cleanup(), and getAvgRideWaitingTime().
myTotalRouteLength
double MSDevice_Tripinfo::myTotalRouteLength static private
Definition at line 237 of file MSDevice_Tripinfo.h.
Referenced by cleanup(), getAvgRouteLength(), and updateStatistics().
myTotalTimeLoss
SUMOTime MSDevice_Tripinfo::myTotalTimeLoss static private
Definition at line 240 of file MSDevice_Tripinfo.h.
Referenced by cleanup(), getAvgTimeLoss(), and updateStatistics().
myTotalWaitingTime
SUMOTime MSDevice_Tripinfo::myTotalWaitingTime static private
Definition at line 239 of file MSDevice_Tripinfo.h.
Referenced by cleanup(), getAvgWaitingTime(), and updateStatistics().
myTotalWalkDuration
SUMOTime MSDevice_Tripinfo::myTotalWalkDuration static private
Definition at line 245 of file MSDevice_Tripinfo.h.
Referenced by addPedestrianData(), cleanup(), and getAvgWalkDuration().
myTotalWalkRouteLength
double MSDevice_Tripinfo::myTotalWalkRouteLength static private
Definition at line 244 of file MSDevice_Tripinfo.h.
Referenced by addPedestrianData(), cleanup(), and getAvgWalkRouteLength().
myTotalWalkTimeLoss
SUMOTime MSDevice_Tripinfo::myTotalWalkTimeLoss static private
Definition at line 246 of file MSDevice_Tripinfo.h.
Referenced by addPedestrianData(), cleanup(), and getAvgWalkTimeLoss().
myVehicleCount
double MSDevice_Tripinfo::myVehicleCount static private
global tripinfo statistics
Definition at line 236 of file MSDevice_Tripinfo.h.
Referenced by cleanup(), getAvgDepartDelay(), getAvgDuration(), getAvgRouteLength(), getAvgTimeLoss(), getAvgWaitingTime(), and updateStatistics().
myWaitingTime
SUMOTime MSDevice_Tripinfo::myWaitingTime private
The overall waiting time.
Definition at line 210 of file MSDevice_Tripinfo.h.
Referenced by generateOutput(), notifyMove(), notifyMoveInternal(), and updateStatistics().
myWalkCount
int MSDevice_Tripinfo::myWalkCount static private
Definition at line 243 of file MSDevice_Tripinfo.h.
Referenced by addPedestrianData(), cleanup(), getAvgWalkDuration(), getAvgWalkRouteLength(), getAvgWalkTimeLoss(), and printStatistics().
The documentation for this class was generated from the following files:
MSDevice_Tripinfo.h
MSDevice_Tripinfo.cpp