SUMO - Simulation of Urban MObility: NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter Class Reference
NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
edge_by_angle_to_nodeShapeCentroid_sorter (const NBNode *n)
constructor
int operator() (const NBEdge *e1, const NBEdge *e2) const
comparing operation
Private Attributes
const NBNode * myNode
the edge to compute the relative angle of
Detailed Description
edge_by_angle_to_nodeShapeCentroid_sorter Class to sort edges by their angle in relation to the node shape
Definition at line 412 of file NBContHelper.h.
Constructor & Destructor Documentation
edge_by_angle_to_nodeShapeCentroid_sorter()
NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::edge_by_angle_to_nodeShapeCentroid_sorter (const NBNode * n) inline explicit
constructor
Definition at line 415 of file NBContHelper.h.
References NBContHelper::relative_outgoing_edge_sorter::operator()().
Member Function Documentation
operator()()
int NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator() (const NBEdge * e1, const NBEdge * e2) const
comparing operation
Definition at line 300 of file NBContHelper.cpp.
References NBEdge::getAngleAtNodeToCenter(), NBEdge::getFromNode(), Named::getID(), NBEdge::getPermissions(), NBEdge::getToNode(), and SVC_PEDESTRIAN.
Field Documentation
myNode
const NBNode* NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::myNode private
the edge to compute the relative angle of
Definition at line 423 of file NBContHelper.h.
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp