SUMO - Simulation of Urban MObility: GUIDialog_ViewSettings Class Reference
GUIDialog_ViewSettings Class Reference
The dialog to change the view (gui) settings.
#include <GUIDialog_ViewSettings.h>
Data Structures
class NamePanel
class SizePanel
Public Member Functions
std::string getCurrentScheme () const
Returns the name of the currently chosen scheme.
GUIDialog_ViewSettings (GUISUMOAbstractView *parent, GUIVisualizationSettings *settings, std::vector< GUISUMOAbstractView::Decal > *decals, MFXMutex *decalsLock)
Constructor.
void setCurrent (GUIVisualizationSettings *settings)
Sets current settings (called if reopened)
void setCurrentScheme (const std::string &)
Sets the named scheme as the current.
void show ()
show view settings dialog
~GUIDialog_ViewSettings ()
Destructor.
FOX-callbacks
long onCmdOk (FXObject *, FXSelector, void *)
Called if the OK-button was pressed.
long onCmdCancel (FXObject *, FXSelector, void *)
Called if the Cancel-button was pressed.
long onCmdColorChange (FXObject *, FXSelector, void *)
Called if something (color, width, etc.) has been changed.
long onCmdEditTable (FXObject *, FXSelector, void *data)
Called if the decals-table was changed.
long onCmdNameChange (FXObject *, FXSelector, void *)
Called if the name of the scheme was changed.
long onCmdSaveSetting (FXObject *, FXSelector, void *data)
Called if the settings shall be saved into the registry.
long onUpdSaveSetting (FXObject *, FXSelector, void *data)
Called when updating the button that allows to save the settings into the registry.
long onCmdDeleteSetting (FXObject *, FXSelector, void *data)
Called if the settings shall be deleted.
long onUpdDeleteSetting (FXObject *, FXSelector, void *data)
Called when updating the button that allows to delete settings.
long onCmdExportSetting (FXObject *, FXSelector, void *data)
Called if the settings shall be exported into a file.
long onUpdExportSetting (FXObject *, FXSelector, void *data)
Called when updating the button that allows to export settings into a file.
long onCmdImportSetting (FXObject *, FXSelector, void *data)
Called if the settings shall be read from a file.
long onUpdImportSetting (FXObject *, FXSelector, void *data)
Called when updating the button that allows to read settings from a file.
long onCmdLoadDecals (FXObject *, FXSelector, void *data)
Called if the decals shall be loaded from a file.
long onCmdSaveDecals (FXObject *, FXSelector, void *data)
Called if the decals shall be saved to a file.
Protected Member Functions
GUIDialog_ViewSettings ()
Default constructor (needed by FOX)
Private Member Functions
GUIDialog_ViewSettings (const GUIDialog_ViewSettings &s)
invalidated copy constructor
void loadDecals (const std::string &file)
Loads decals from a file.
void loadSettings (const std::string &file)
Loads a scheme from a file.
GUIDialog_ViewSettings & operator= (const GUIDialog_ViewSettings &s)
invalidated assignment operator
void rebuildColorMatrices (bool doCreate=false)
Rebuilds color changing dialogs after choosing another coloring scheme.
FXMatrix * rebuildColorMatrix (FXVerticalFrame *frame, std::vector< FXColorWell *> &colors, std::vector< FXRealSpinDial *> &thresholds, std::vector< FXButton *> &buttons, FXCheckButton *interpolation, GUIColorScheme &scheme)
Rebuilds manipulators for the current coloring scheme.
void rebuildList ()
Rebuilds the decals table.
FXMatrix * rebuildScaleMatrix (FXVerticalFrame *frame, std::vector< FXRealSpinDial *> &scales, std::vector< FXRealSpinDial *> &thresholds, std::vector< FXButton *> &buttons, FXCheckButton *interpolation, GUIScaleScheme &scheme)
Rebuilds manipulators for the current scaling scheme.
void saveDecals (OutputDevice &dev) const
Writes the currently used decals into a file.
void saveWindowSize ()
save window position and size to the registry
bool updateColorRanges (FXObject *sender, std::vector< FXColorWell *>::const_iterator colIt, std::vector< FXColorWell *>::const_iterator colEnd, std::vector< FXRealSpinDial *>::const_iterator threshIt, std::vector< FXRealSpinDial *>::const_iterator threshEnd, std::vector< FXButton *>::const_iterator buttonIt, GUIColorScheme &scheme)
bool updateScaleRanges (FXObject *sender, std::vector< FXRealSpinDial *>::const_iterator colIt, std::vector< FXRealSpinDial *>::const_iterator colEnd, std::vector< FXRealSpinDial *>::const_iterator threshIt, std::vector< FXRealSpinDial *>::const_iterator threshEnd, std::vector< FXButton *>::const_iterator buttonIt, GUIScaleScheme &scheme)
Private Attributes
GUIVisualizationSettings myBackup
A backup of the settings (used if the "Cancel" button is pressed)
std::vector< GUISUMOAbstractView::Decal > * myDecals
The parent's decals.
MFXMutex * myDecalsLock
Lock used when changing the decals.
GUISUMOAbstractView * myParent
The parent view (which settings are changed)
GUIVisualizationSettings * mySettings
The current settings.
Dialog elements
FXComboBox * mySchemeName
FXCheckButton * myShowGrid
FXRealSpinDial * myGridXSizeDialer
FXRealSpinDial * myGridYSizeDialer
FXColorWell * myBackgroundColor
FXVerticalFrame * myDecalsFrame
MFXAddEditTypedTable * myDecalsTable
FXComboBox * myLaneEdgeColorMode
... lane colorer
FXVerticalFrame * myLaneColorSettingFrame
std::vector< FXColorWell * > myLaneColors
std::vector< FXRealSpinDial * > myLaneThresholds
std::vector< FXButton * > myLaneButtons
FXCheckButton * myLaneColorInterpolation
FXButton * myLaneColorRainbow
FXButton * myJunctionColorRainbow
FXComboBox * myLaneEdgeScaleMode
... lane scaler
FXVerticalFrame * myLaneScaleSettingFrame
std::vector< FXRealSpinDial * > myLaneScales
std::vector< FXRealSpinDial * > myLaneScaleThresholds
std::vector< FXButton * > myLaneScaleButtons
FXCheckButton * myLaneScaleInterpolation
FXCheckButton * myShowLaneBorders
FXCheckButton * myShowLaneDecals
FXCheckButton * myShowLinkRules
FXCheckButton * myShowRails
FXCheckButton * myHideMacroConnectors
FXCheckButton * myShowLaneDirection
FXCheckButton * myShowSublanes
FXRealSpinDial * myLaneWidthUpscaleDialer
FXRealSpinDial * myLaneMinWidthDialer
FXComboBox * myVehicleColorMode
FXComboBox * myVehicleShapeDetail
FXVerticalFrame * myVehicleColorSettingFrame
std::vector< FXColorWell * > myVehicleColors
std::vector< FXRealSpinDial * > myVehicleThresholds
std::vector< FXButton * > myVehicleButtons
FXCheckButton * myVehicleColorInterpolation
FXCheckButton * myShowBlinker
FXCheckButton * myShowMinGap
FXCheckButton * myShowBTRange
FXComboBox * myPersonColorMode
FXComboBox * myPersonShapeDetail
FXVerticalFrame * myPersonColorSettingFrame
std::vector< FXColorWell * > myPersonColors
std::vector< FXRealSpinDial * > myPersonThresholds
std::vector< FXButton * > myPersonButtons
FXCheckButton * myPersonColorInterpolation
FXComboBox * myContainerColorMode
FXComboBox * myContainerShapeDetail
FXVerticalFrame * myContainerColorSettingFrame
std::vector< FXColorWell * > myContainerColors
std::vector< FXRealSpinDial * > myContainerThresholds
std::vector< FXButton * > myContainerButtons
FXCheckButton * myContainerColorInterpolation
FXRealSpinDial * myContainerMinSizeDialer
FXRealSpinDial * myContainerUpscaleDialer
FXComboBox * myJunctionColorMode
FXVerticalFrame * myJunctionColorSettingFrame
std::vector< FXColorWell * > myJunctionColors
std::vector< FXRealSpinDial * > myJunctionThresholds
std::vector< FXButton * > myJunctionButtons
FXCheckButton * myJunctionColorInterpolation
FXCheckButton * myShowLane2Lane
FXCheckButton * myDrawJunctionShape
FXCheckButton * myDrawCrossingsAndWalkingAreas
FXCheckButton * myDither
FXCheckButton * myShowSizeLegend
NamePanel * myEdgeNamePanel
NamePanel * myInternalEdgeNamePanel
NamePanel * myCwaEdgeNamePanel
NamePanel * myStreetNamePanel
NamePanel * myJunctionIndexPanel
NamePanel * myTLIndexPanel
NamePanel * myJunctionNamePanel
NamePanel * myInternalJunctionNamePanel
NamePanel * myVehicleNamePanel
NamePanel * myPersonNamePanel
NamePanel * myContainerNamePanel
NamePanel * myAddNamePanel
NamePanel * myAddFullNamePanel
NamePanel * myPOINamePanel
NamePanel * myPolyNamePanel
NamePanel * myPOITypePanel
NamePanel * myPolyTypePanel
SizePanel * myVehicleSizePanel
SizePanel * myPersonSizePanel
SizePanel * myContainerSizePanel
SizePanel * myPOISizePanel
SizePanel * myPolySizePanel
SizePanel * myAddSizePanel
SizePanel * myJunctionSizePanel
FXCheckButton * mySaveViewPort
FXCheckButton * mySaveDelay
FXCheckButton * mySaveDecals
Detailed Description
The dialog to change the view (gui) settings.
Todo:
Check whether saving/loading settings should be done via XML
Definition at line 55 of file GUIDialog_ViewSettings.h.
Constructor & Destructor Documentation
GUIDialog_ViewSettings() [1/3]
GUIDialog_ViewSettings::GUIDialog_ViewSettings (GUISUMOAbstractView * parent, GUIVisualizationSettings * settings, std::vector< GUISUMOAbstractView::Decal > * decals, MFXMutex * decalsLock)
Constructor.
Parameters
[in] parent The view to report changed settings to
[in,out] settings The current settings that can be changed
[in] laneEdgeModeSource Class storing known lane coloring schemes
[in] vehicleModeSource Class storing known vehicle coloring schemes
[in] decals Decals used
[in] decalsLock A lock to set if the decals are changed
Definition at line 85 of file GUIDialog_ViewSettings.cpp.
References MFXUtils::getFXColor(), GUIIconSubSys::getIcon(), GUICompleteSchemeStorage::getNames(), gSchemeStorage, GUIDesignButtonToolbar, GUIDesignCheckButton, GUIDesignComboBoxStatic, GUIDesignHorizontalSeparator, GUIDesignMatrixViewSettings, GUIDesignViewSettingsButton1, GUIDesignViewSettingsButton2, GUIDesignViewSettingsButton3, GUIDesignViewSettingsColorWell, GUIDesignViewSettingsComboBox1, GUIDesignViewSettingsHorizontalFrame1, GUIDesignViewSettingsHorizontalFrame2, GUIDesignViewSettingsLabel1, GUIDesignViewSettingsMatrix1, GUIDesignViewSettingsMatrix2, GUIDesignViewSettingsMatrix3, GUIDesignViewSettingsSpinDial1, GUIDesignViewSettingsSpinDial2, GUIDesignViewSettingsTabBook1, GUIDesignViewSettingsTabItemBook1, GUIDesignViewSettingsVerticalFrame1, GUIDesignViewSettingsVerticalFrame2, GUIDesignViewSettingsVerticalFrame3, GUIDesignViewSettingsVerticalFrame4, GUIDesignViewSettingsVerticalFrame6, ICON_EMPTY, ICON_OPEN_CONFIG, ICON_REMOVEDB, ICON_SAVE, ICON_SAVEDB, MAX2(), MID_SETTINGS_CANCEL, MID_SETTINGS_OK, MID_SIMPLE_VIEW_COLORCHANGE, MID_SIMPLE_VIEW_DELETE, MID_SIMPLE_VIEW_EXPORT, MID_SIMPLE_VIEW_IMPORT, MID_SIMPLE_VIEW_LOAD_DECALS, MID_SIMPLE_VIEW_NAMECHANGE, MID_SIMPLE_VIEW_SAVE, MID_SIMPLE_VIEW_SAVE_DECALS, MIN2(), and GUIVisualizationSettings::UseMesoSim.
~GUIDialog_ViewSettings()
GUIDialog_ViewSettings::~GUIDialog_ViewSettings ()
Destructor.
Definition at line 481 of file GUIDialog_ViewSettings.cpp.
References myAddFullNamePanel, myAddNamePanel, myAddSizePanel, myCwaEdgeNamePanel, myEdgeNamePanel, myInternalEdgeNamePanel, myInternalJunctionNamePanel, myJunctionIndexPanel, myJunctionNamePanel, myJunctionSizePanel, myParent, myPersonSizePanel, myPOINamePanel, myPOISizePanel, myPOITypePanel, myPolyNamePanel, myPolySizePanel, myPolyTypePanel, myStreetNamePanel, myTLIndexPanel, myVehicleNamePanel, myVehicleSizePanel, and GUISUMOAbstractView::remove().
GUIDialog_ViewSettings() [2/3]
GUIDialog_ViewSettings::GUIDialog_ViewSettings () inline protected
Default constructor (needed by FOX)
Definition at line 337 of file GUIDialog_ViewSettings.h.
References operator=().
GUIDialog_ViewSettings() [3/3]
GUIDialog_ViewSettings::GUIDialog_ViewSettings (const GUIDialog_ViewSettings & s) private
invalidated copy constructor
Member Function Documentation
getCurrentScheme()
std::string GUIDialog_ViewSettings::getCurrentScheme () const
Returns the name of the currently chosen scheme.
Returns
The name of the edited (chosen) scheme)
Definition at line 1519 of file GUIDialog_ViewSettings.cpp.
References mySchemeName.
Referenced by GUIViewTraffic::setColorScheme(), and GNEViewNet::setColorScheme().
loadDecals()
void GUIDialog_ViewSettings::loadDecals (const std::string & file) private
Loads decals from a file.
Parameters
[in] file The name of the file to read the decals from
Definition at line 996 of file GUIDialog_ViewSettings.cpp.
References GUISettingsHandler::getDecals(), GUISettingsHandler::hasDecals(), MFXMutex::lock(), myDecalsLock, myParent, rebuildList(), and MFXMutex::unlock().
Referenced by onCmdLoadDecals().
loadSettings()
void GUIDialog_ViewSettings::loadSettings (const std::string & file) private
Loads a scheme from a file.
Parameters
[in] file The name of the file to read the settings from
Definition at line 949 of file GUIDialog_ViewSettings.cpp.
References GUISettingsHandler::addSettings(), GUISettingsHandler::applyViewport(), GUICompleteSchemeStorage::get(), GUISettingsHandler::getDecals(), GUISettingsHandler::getDelay(), gSchemeStorage, GUISettingsHandler::hasDecals(), MFXMutex::lock(), myDecalsLock, myParent, mySchemeName, mySettings, GUIVisualizationSettings::netedit, rebuildColorMatrices(), rebuildList(), GUISUMOAbstractView::setDelay(), and MFXMutex::unlock().
Referenced by onCmdImportSetting().
onCmdCancel()
long GUIDialog_ViewSettings::onCmdCancel (FXObject * , FXSelector , void *)
Called if the Cancel-button was pressed.
Definition at line 534 of file GUIDialog_ViewSettings.cpp.
References myBackup, and saveWindowSize().
onCmdColorChange()
long GUIDialog_ViewSettings::onCmdColorChange (FXObject * sender, FXSelector , void *)
Called if something (color, width, etc.) has been changed.
Definition at line 736 of file GUIDialog_ViewSettings.cpp.
References GUICompleteSchemeStorage::add(), GUIVisualizationSettings::addFullName, GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GUIVisualizationSettings::backgroundColor, GUISUMOAbstractView::buildColorRainbow(), GUIVisualizationSettings::containerColorer, GUIVisualizationSettings::containerName, GUIVisualizationSettings::containerQuality, GUIVisualizationSettings::containerSize, GUICompleteSchemeStorage::contains(), GUIVisualizationSettings::cwaEdgeName, GUIVisualizationSettings::dither, GUIVisualizationSettings::drawCrossingsAndWalkingareas, GUIVisualizationSettings::drawJunctionShape, GUIVisualizationSettings::drawLinkJunctionIndex, GUIVisualizationSettings::drawLinkTLIndex, GUIVisualizationSettings::drawMinGap, GUIVisualizationSettings::edgeColorer, GUIVisualizationSettings::edgeName, GUIVisualizationSettings::edgeScaler, GUICompleteSchemeStorage::get(), GUIPropertySchemeStorage< T >::getActive(), GUISUMOAbstractView::getColoringSchemesCombo(), GUIVisualizationSettings::getLaneEdgeMode(), GUIVisualizationSettings::getLaneEdgeScaleMode(), GUIVisualizationSettings::getLaneEdgeScaleScheme(), GUIVisualizationSettings::getLaneEdgeScheme(), GUICompleteSchemeStorage::getNumInitialSettings(), MFXUtils::getRGBColor(), GUIPropertySchemeStorage< T >::getScheme(), GUIDialog_ViewSettings::NamePanel::getSettings(), GUIDialog_ViewSettings::SizePanel::getSettings(), GLO_JUNCTION, GLO_LANE, GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, gSchemeStorage, GUIVisualizationSettings::hideConnectors, GUIVisualizationSettings::internalEdgeName, GUIVisualizationSettings::internalJunctionName, GUIVisualizationSettings::junctionColorer, GUIVisualizationSettings::junctionName, GUIVisualizationSettings::junctionSize, GUIVisualizationSettings::laneColorer, GUIVisualizationSettings::laneMinSize, GUIVisualizationSettings::laneScaler, GUIVisualizationSettings::laneShowBorders, GUIVisualizationSettings::laneWidthExaggeration, myAddFullNamePanel, myAddNamePanel, myAddSizePanel, myBackgroundColor, myContainerButtons, myContainerColorInterpolation, myContainerColorMode, myContainerColors, myContainerNamePanel, myContainerShapeDetail, myContainerSizePanel, myContainerThresholds, myCwaEdgeNamePanel, myDither, myDrawCrossingsAndWalkingAreas, myDrawJunctionShape, myEdgeNamePanel, myGridXSizeDialer, myGridYSizeDialer, myHideMacroConnectors, myInternalEdgeNamePanel, myInternalJunctionNamePanel, myJunctionButtons, myJunctionColorInterpolation, myJunctionColorMode, myJunctionColorRainbow, myJunctionColors, myJunctionIndexPanel, myJunctionNamePanel, myJunctionSizePanel, myJunctionThresholds, myLaneButtons, myLaneColorInterpolation, myLaneColorRainbow, myLaneColors, myLaneEdgeColorMode, myLaneEdgeScaleMode, myLaneMinWidthDialer, myLaneScaleButtons, myLaneScaleInterpolation, myLaneScales, myLaneScaleThresholds, myLaneThresholds, myLaneWidthUpscaleDialer, myParent, myPersonButtons, myPersonColorInterpolation, myPersonColorMode, myPersonColors, myPersonNamePanel, myPersonShapeDetail, myPersonSizePanel, myPersonThresholds, myPOINamePanel, myPOISizePanel, myPOITypePanel, myPolyNamePanel, myPolySizePanel, myPolyTypePanel, mySchemeName, mySettings, myShowBlinker, myShowBTRange, myShowGrid, myShowLane2Lane, myShowLaneBorders, myShowLaneDecals, myShowLaneDirection, myShowLinkRules, myShowMinGap, myShowRails, myShowSizeLegend, myShowSublanes, myStreetNamePanel, myTLIndexPanel, myVehicleButtons, myVehicleColorInterpolation, myVehicleColorMode, myVehicleColors, myVehicleNamePanel, myVehicleShapeDetail, myVehicleSizePanel, myVehicleThresholds, GUIVisualizationSettings::name, GUIVisualizationSettings::personColorer, GUIVisualizationSettings::personName, GUIVisualizationSettings::personQuality, GUIVisualizationSettings::personSize, GUIVisualizationSettings::poiName, GUIVisualizationSettings::poiSize, GUIVisualizationSettings::poiType, GUIVisualizationSettings::polyName, GUIVisualizationSettings::polySize, GUIVisualizationSettings::polyType, rebuildColorMatrices(), GUIPropertySchemeStorage< T >::setActive(), GUISUMOAbstractView::setColorScheme(), GUIPropertyScheme< T >::setInterpolated(), GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationSettings::showGrid, GUIVisualizationSettings::showLane2Lane, GUIVisualizationSettings::showLaneDirection, GUIVisualizationSettings::showLinkDecals, GUIVisualizationSettings::showLinkRules, GUIVisualizationSettings::showRails, GUIVisualizationSettings::showSizeLegend, GUIVisualizationSettings::showSublanes, GUIVisualizationSettings::streetName, toString(), updateColorRanges(), updateScaleRanges(), GUIVisualizationSettings::UseMesoSim, GUIVisualizationSettings::vehicleColorer, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, and GUIVisualizationSettings::vehicleSize.
onCmdDeleteSetting()
long GUIDialog_ViewSettings::onCmdDeleteSetting (FXObject * , FXSelector , void * data)
Called if the settings shall be deleted.
Definition at line 1063 of file GUIDialog_ViewSettings.cpp.
References GUICompleteSchemeStorage::getNumInitialSettings(), gSchemeStorage, mySchemeName, onCmdNameChange(), GUICompleteSchemeStorage::remove(), and GUICompleteSchemeStorage::writeSettings().
onCmdEditTable()
long GUIDialog_ViewSettings::onCmdEditTable (FXObject * , FXSelector , void * data)
Called if the decals-table was changed.
Definition at line 1413 of file GUIDialog_ViewSettings.cpp.
References TplConvert::_2bool(), TplConvert::_2double(), GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, MFXEditedTableItem::col, GUISUMOAbstractView::Decal::filename, GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getGridWidth(), GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::initialised, MFXEditedTableItem::item, GUISUMOAbstractView::Decal::layer, MFXMutex::lock(), myDecals, myDecalsLock, myParent, rebuildList(), GUISUMOAbstractView::Decal::rot, MFXEditedTableItem::row, GUISUMOAbstractView::Decal::screenRelative, MFXMutex::unlock(), MFXEditedTableItem::updateOnly, and GUISUMOAbstractView::Decal::width.
onCmdExportSetting()
long GUIDialog_ViewSettings::onCmdExportSetting (FXObject * , FXSelector , void * data)
Called if the settings shall be exported into a file.
Definition at line 1088 of file GUIDialog_ViewSettings.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), gCurrentFolder, GUISUMOAbstractView::getDelay(), OutputDevice::getDevice(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), GUISUMOAbstractView::getViewportEditor(), ICON_EMPTY, myParent, mySaveDecals, mySaveDelay, mySaveViewPort, mySettings, OutputDevice::openTag(), GUIVisualizationSettings::save(), saveDecals(), SUMO_ATTR_VALUE, SUMO_TAG_DELAY, SUMO_TAG_VIEWSETTINGS, OutputDevice::writeAttr(), and GUIDialog_EditViewport::writeXML().
onCmdImportSetting()
long GUIDialog_ViewSettings::onCmdImportSetting (FXObject * , FXSelector , void * data)
Called if the settings shall be read from a file.
Definition at line 1129 of file GUIDialog_ViewSettings.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, and loadSettings().
onCmdLoadDecals()
long GUIDialog_ViewSettings::onCmdLoadDecals (FXObject * , FXSelector , void * data)
Called if the decals shall be loaded from a file.
Definition at line 1146 of file GUIDialog_ViewSettings.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, and loadDecals().
onCmdNameChange()
long GUIDialog_ViewSettings::onCmdNameChange (FXObject * , FXSelector , void * data)
Called if the name of the scheme was changed.
Definition at line 543 of file GUIDialog_ViewSettings.cpp.
References GUIVisualizationSettings::addFullName, GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GUIVisualizationSettings::backgroundColor, GUIVisualizationSettings::containerColorer, GUIVisualizationSettings::containerName, GUIVisualizationSettings::containerQuality, GUIVisualizationSettings::containerSize, GUIVisualizationSettings::cwaEdgeName, GUIVisualizationSettings::dither, GUIVisualizationSettings::drawCrossingsAndWalkingareas, GUIVisualizationSettings::drawJunctionShape, GUIVisualizationSettings::drawLinkJunctionIndex, GUIVisualizationSettings::drawLinkTLIndex, GUIVisualizationSettings::drawMinGap, GUIVisualizationSettings::edgeName, GUICompleteSchemeStorage::get(), GUIPropertySchemeStorage< T >::getActive(), MFXUtils::getFXColor(), GUIVisualizationSettings::getLaneEdgeMode(), GUIVisualizationSettings::getLaneEdgeScaleMode(), gSchemeStorage, GUIVisualizationSettings::hideConnectors, GUIVisualizationSettings::internalEdgeName, GUIVisualizationSettings::internalJunctionName, GUIVisualizationSettings::junctionColorer, GUIVisualizationSettings::junctionName, GUIVisualizationSettings::junctionSize, GUIVisualizationSettings::laneMinSize, GUIVisualizationSettings::laneShowBorders, GUIVisualizationSettings::laneWidthExaggeration, myAddFullNamePanel, myAddNamePanel, myAddSizePanel, myBackgroundColor, myBackup, myContainerColorMode, myContainerNamePanel, myContainerShapeDetail, myContainerSizePanel, myCwaEdgeNamePanel, myDither, myDrawCrossingsAndWalkingAreas, myDrawJunctionShape, myEdgeNamePanel, myHideMacroConnectors, myInternalEdgeNamePanel, myInternalJunctionNamePanel, myJunctionColorMode, myJunctionIndexPanel, myJunctionNamePanel, myJunctionSizePanel, myLaneEdgeColorMode, myLaneEdgeScaleMode, myLaneMinWidthDialer, myLaneWidthUpscaleDialer, myParent, myPersonColorMode, myPersonNamePanel, myPersonShapeDetail, myPersonSizePanel, myPOINamePanel, myPOISizePanel, myPOITypePanel, myPolyNamePanel, myPolySizePanel, myPolyTypePanel, mySchemeName, mySettings, myShowBlinker, myShowBTRange, myShowLane2Lane, myShowLaneBorders, myShowLaneDecals, myShowLaneDirection, myShowLinkRules, myShowMinGap, myShowRails, myShowSizeLegend, myShowSublanes, myStreetNamePanel, myTLIndexPanel, myVehicleColorMode, myVehicleNamePanel, myVehicleShapeDetail, myVehicleSizePanel, GUIVisualizationSettings::name, GUIVisualizationSettings::personColorer, GUIVisualizationSettings::personName, GUIVisualizationSettings::personQuality, GUIVisualizationSettings::personSize, GUIVisualizationSettings::poiName, GUIVisualizationSettings::poiSize, GUIVisualizationSettings::poiType, GUIVisualizationSettings::polyName, GUIVisualizationSettings::polySize, GUIVisualizationSettings::polyType, rebuildColorMatrices(), GUISUMOAbstractView::setColorScheme(), GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationSettings::showLane2Lane, GUIVisualizationSettings::showLaneDirection, GUIVisualizationSettings::showLinkDecals, GUIVisualizationSettings::showLinkRules, GUIVisualizationSettings::showRails, GUIVisualizationSettings::showSizeLegend, GUIVisualizationSettings::showSublanes, GUIVisualizationSettings::streetName, GUIDialog_ViewSettings::NamePanel::update(), GUIDialog_ViewSettings::SizePanel::update(), GUIVisualizationSettings::vehicleColorer, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, and GUIVisualizationSettings::vehicleSize.
Referenced by onCmdDeleteSetting(), setCurrent(), and setCurrentScheme().
onCmdOk()
long GUIDialog_ViewSettings::onCmdOk (FXObject * , FXSelector , void *)
Called if the OK-button was pressed.
Definition at line 526 of file GUIDialog_ViewSettings.cpp.
References saveWindowSize().
onCmdSaveDecals()
long GUIDialog_ViewSettings::onCmdSaveDecals (FXObject * , FXSelector , void * data)
Called if the decals shall be saved to a file.
Definition at line 1163 of file GUIDialog_ViewSettings.cpp.
References OutputDevice::close(), OutputDevice::closeTag(), gCurrentFolder, OutputDevice::getDevice(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), ICON_EMPTY, myParent, OutputDevice::openTag(), and saveDecals().
onCmdSaveSetting()
long GUIDialog_ViewSettings::onCmdSaveSetting (FXObject * , FXSelector , void * data)
Called if the settings shall be saved into the registry.
Definition at line 1009 of file GUIDialog_ViewSettings.cpp.
References GUICompleteSchemeStorage::add(), GUICompleteSchemeStorage::get(), GUISUMOAbstractView::getColoringSchemesCombo(), GUICompleteSchemeStorage::getNumInitialSettings(), gSchemeStorage, GUIDesignHorizontalSeparator, GUIDesignViewSettingsButton4, GUIDesignViewSettingsButton5, GUIDesignViewSettingsDialog, GUIDesignViewSettingsHorizontalFrame3, GUIDesignViewSettingsLabel2, GUIDesignViewSettingsTextField1, GUIDesignViewSettingsVerticalFrame5, myBackup, myParent, mySchemeName, mySettings, GUIVisualizationSettings::name, GUICompleteSchemeStorage::remove(), GUISUMOAbstractView::setColorScheme(), and GUICompleteSchemeStorage::writeSettings().
onUpdDeleteSetting()
long GUIDialog_ViewSettings::onUpdDeleteSetting (FXObject * sender, FXSelector , void * data)
Called when updating the button that allows to delete settings.
Definition at line 1078 of file GUIDialog_ViewSettings.cpp.
References GUICompleteSchemeStorage::getNumInitialSettings(), gSchemeStorage, and mySchemeName.
onUpdExportSetting()
long GUIDialog_ViewSettings::onUpdExportSetting (FXObject * sender, FXSelector , void * data)
Called when updating the button that allows to export settings into a file.
Definition at line 1118 of file GUIDialog_ViewSettings.cpp.
References GUICompleteSchemeStorage::getNumInitialSettings(), gSchemeStorage, mySaveDecals, mySaveDelay, mySaveViewPort, and mySchemeName.
onUpdImportSetting()
long GUIDialog_ViewSettings::onUpdImportSetting (FXObject * sender, FXSelector , void * data)
Called when updating the button that allows to read settings from a file.
Definition at line 1184 of file GUIDialog_ViewSettings.cpp.
onUpdSaveSetting()
long GUIDialog_ViewSettings::onUpdSaveSetting (FXObject * sender, FXSelector , void * data)
Called when updating the button that allows to save the settings into the registry.
Definition at line 1053 of file GUIDialog_ViewSettings.cpp.
References GUICompleteSchemeStorage::getNumInitialSettings(), gSchemeStorage, and mySchemeName.
operator=()
GUIDialog_ViewSettings& GUIDialog_ViewSettings::operator= (const GUIDialog_ViewSettings & s) private
invalidated assignment operator
Referenced by GUIDialog_ViewSettings().
rebuildColorMatrices()
void GUIDialog_ViewSettings::rebuildColorMatrices (bool doCreate = false) private
Rebuilds color changing dialogs after choosing another coloring scheme.
Parameters
[in] doCreate Whether "create" shall be called (only if built the first time)
Definition at line 1346 of file GUIDialog_ViewSettings.cpp.
References GUIVisualizationSettings::containerColorer, CT_REAL, GUIVisualizationSettings::getLaneEdgeScaleScheme(), GUIVisualizationSettings::getLaneEdgeScheme(), GUIPropertySchemeStorage< T >::getScheme(), GUIDesignViewSettingsMFXTable, GUIPropertyScheme< T >::isFixed(), GUIVisualizationSettings::junctionColorer, MID_TABLE, myContainerButtons, myContainerColorInterpolation, myContainerColors, myContainerColorSettingFrame, myContainerThresholds, myDecalsFrame, myDecalsTable, myJunctionButtons, myJunctionColorInterpolation, myJunctionColorRainbow, myJunctionColors, myJunctionColorSettingFrame, myJunctionThresholds, myLaneButtons, myLaneColorInterpolation, myLaneColorRainbow, myLaneColors, myLaneColorSettingFrame, myLaneScaleButtons, myLaneScaleInterpolation, myLaneScales, myLaneScaleSettingFrame, myLaneScaleThresholds, myLaneThresholds, myPersonButtons, myPersonColorInterpolation, myPersonColors, myPersonColorSettingFrame, myPersonThresholds, mySettings, myVehicleButtons, myVehicleColorInterpolation, myVehicleColors, myVehicleColorSettingFrame, myVehicleThresholds, GUIVisualizationSettings::personColorer, rebuildColorMatrix(), rebuildList(), rebuildScaleMatrix(), MFXAddEditTypedTable::setCellType(), MFXAddEditTypedTable::setNumberCellParams(), and GUIVisualizationSettings::vehicleColorer.
Referenced by loadSettings(), onCmdColorChange(), and onCmdNameChange().
rebuildColorMatrix()
FXMatrix * GUIDialog_ViewSettings::rebuildColorMatrix (FXVerticalFrame * frame, std::vector< FXColorWell *> & colors, std::vector< FXRealSpinDial *> & thresholds, std::vector< FXButton *> & buttons, FXCheckButton * interpolation, GUIColorScheme & scheme) private
Rebuilds manipulators for the current coloring scheme.
Definition at line 1236 of file GUIDialog_ViewSettings.cpp.
References GUIPropertyScheme< T >::allowsNegativeValues(), MFXUtils::deleteChildren(), GUIPropertyScheme< T >::getColors(), MFXUtils::getFXColor(), GUIPropertyScheme< T >::getNames(), GUIPropertyScheme< T >::getThresholds(), GUIDesignSpinDial, GUIDesignViewSettingsButton1, GUIDesignViewSettingsColorWell1, GUIDesignViewSettingsMatrix4, GUIPropertyScheme< T >::isFixed(), GUIPropertyScheme< T >::isInterpolated(), MID_SIMPLE_VIEW_COLORCHANGE, FX::SPINDIAL_NOMAX, and FX::SPINDIAL_NOMIN.
Referenced by rebuildColorMatrices().
rebuildList()
void GUIDialog_ViewSettings::rebuildList () private
Rebuilds the decals table.
Definition at line 1191 of file GUIDialog_ViewSettings.cpp.
References GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::Decal::filename, GUIDesignViewSettingsMFXTableJustify, GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::layer, MAX2(), myDecals, myDecalsTable, GUISUMOAbstractView::Decal::rot, GUISUMOAbstractView::Decal::screenRelative, and GUISUMOAbstractView::Decal::width.
Referenced by loadDecals(), loadSettings(), onCmdEditTable(), and rebuildColorMatrices().
rebuildScaleMatrix()
FXMatrix * GUIDialog_ViewSettings::rebuildScaleMatrix (FXVerticalFrame * frame, std::vector< FXRealSpinDial *> & scales, std::vector< FXRealSpinDial *> & thresholds, std::vector< FXButton *> & buttons, FXCheckButton * interpolation, GUIScaleScheme & scheme) private
Rebuilds manipulators for the current scaling scheme.
Definition at line 1290 of file GUIDialog_ViewSettings.cpp.
References GUIPropertyScheme< T >::allowsNegativeValues(), MFXUtils::deleteChildren(), GUIPropertyScheme< T >::getColors(), GUIPropertyScheme< T >::getNames(), GUIPropertyScheme< T >::getThresholds(), GUIDesignSpinDial, GUIDesignViewSettingsButton1, GUIDesignViewSettingsMatrix4, GUIPropertyScheme< T >::isFixed(), GUIPropertyScheme< T >::isInterpolated(), MID_SIMPLE_VIEW_COLORCHANGE, FX::SPINDIAL_NOMAX, and FX::SPINDIAL_NOMIN.
Referenced by rebuildColorMatrices().
saveDecals()
void GUIDialog_ViewSettings::saveDecals (OutputDevice & dev) const private
Writes the currently used decals into a file.
Parameters
[in] file The name of the file to write the decals into
Definition at line 973 of file GUIDialog_ViewSettings.cpp.
References GUISUMOAbstractView::Decal::altitude, GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::Decal::centerZ, OutputDevice::closeTag(), GUISUMOAbstractView::Decal::filename, GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::layer, myDecals, OutputDevice::openTag(), GUISUMOAbstractView::Decal::roll, GUISUMOAbstractView::Decal::rot, GUISUMOAbstractView::Decal::screenRelative, SUMO_ATTR_CENTER_X, SUMO_ATTR_CENTER_Y, SUMO_ATTR_CENTER_Z, SUMO_ATTR_HEIGHT, SUMO_ATTR_LAYER, SUMO_ATTR_WIDTH, SUMO_TAG_VIEWSETTINGS_DECAL, GUISUMOAbstractView::Decal::tilt, GUISUMOAbstractView::Decal::width, and OutputDevice::writeAttr().
Referenced by onCmdExportSetting(), and onCmdSaveDecals().
saveWindowSize()
void GUIDialog_ViewSettings::saveWindowSize () private
save window position and size to the registry
Definition at line 1606 of file GUIDialog_ViewSettings.cpp.
Referenced by onCmdCancel(), and onCmdOk().
setCurrent()
void GUIDialog_ViewSettings::setCurrent (GUIVisualizationSettings * settings)
Sets current settings (called if reopened)
Parameters
[in,out] settings The current settings that can be changed
Definition at line 518 of file GUIDialog_ViewSettings.cpp.
References myBackup, mySettings, and onCmdNameChange().
Referenced by GUISUMOAbstractView::showViewschemeEditor().
setCurrentScheme()
void GUIDialog_ViewSettings::setCurrentScheme (const std::string & name)
Sets the named scheme as the current.
Parameters
[in] The name of the scheme that shall be set as current
Definition at line 1525 of file GUIDialog_ViewSettings.cpp.
References mySchemeName, and onCmdNameChange().
Referenced by GUIViewTraffic::setColorScheme(), and GNEViewNet::setColorScheme().
show()
void GUIDialog_ViewSettings::show ()
show view settings dialog
Definition at line 510 of file GUIDialog_ViewSettings.cpp.
References mySettings, myShowGrid, and GUIVisualizationSettings::showGrid.
Referenced by GUISUMOAbstractView::showViewschemeEditor().
updateColorRanges()
bool GUIDialog_ViewSettings::updateColorRanges (FXObject * sender, std::vector< FXColorWell *>::const_iterator colIt, std::vector< FXColorWell *>::const_iterator colEnd, std::vector< FXRealSpinDial *>::const_iterator threshIt, std::vector< FXRealSpinDial *>::const_iterator threshEnd, std::vector< FXButton *>::const_iterator buttonIt, GUIColorScheme & scheme) private
Definition at line 631 of file GUIDialog_ViewSettings.cpp.
References GUIPropertyScheme< T >::addColor(), MFXUtils::getRGBColor(), GUIPropertyScheme< T >::isFixed(), GUIPropertyScheme< T >::removeColor(), GUIPropertyScheme< T >::setColor(), and GUIPropertyScheme< T >::setThreshold().
Referenced by onCmdColorChange().
updateScaleRanges()
bool GUIDialog_ViewSettings::updateScaleRanges (FXObject * sender, std::vector< FXRealSpinDial *>::const_iterator colIt, std::vector< FXRealSpinDial *>::const_iterator colEnd, std::vector< FXRealSpinDial *>::const_iterator threshIt, std::vector< FXRealSpinDial *>::const_iterator threshEnd, std::vector< FXButton *>::const_iterator buttonIt, GUIScaleScheme & scheme) private
Definition at line 684 of file GUIDialog_ViewSettings.cpp.
References GUIPropertyScheme< T >::addColor(), GUIPropertyScheme< T >::isFixed(), GUIPropertyScheme< T >::removeColor(), GUIPropertyScheme< T >::setColor(), and GUIPropertyScheme< T >::setThreshold().
Referenced by onCmdColorChange().
Field Documentation
myAddFullNamePanel
NamePanel * GUIDialog_ViewSettings::myAddFullNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myAddNamePanel
NamePanel * GUIDialog_ViewSettings::myAddNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myAddSizePanel
SizePanel * GUIDialog_ViewSettings::myAddSizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myBackgroundColor
FXColorWell* GUIDialog_ViewSettings::myBackgroundColor private
Definition at line 258 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myBackup
GUIVisualizationSettings GUIDialog_ViewSettings::myBackup private
A backup of the settings (used if the "Cancel" button is pressed)
Definition at line 244 of file GUIDialog_ViewSettings.h.
Referenced by onCmdCancel(), onCmdNameChange(), onCmdSaveSetting(), and setCurrent().
myContainerButtons
std::vector<FXButton*> GUIDialog_ViewSettings::myContainerButtons private
Definition at line 304 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myContainerColorInterpolation
FXCheckButton* GUIDialog_ViewSettings::myContainerColorInterpolation private
Definition at line 305 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myContainerColorMode
FXComboBox* GUIDialog_ViewSettings::myContainerColorMode private
Definition at line 300 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myContainerColors
std::vector<FXColorWell*> GUIDialog_ViewSettings::myContainerColors private
Definition at line 302 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myContainerColorSettingFrame
FXVerticalFrame* GUIDialog_ViewSettings::myContainerColorSettingFrame private
Definition at line 301 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myContainerMinSizeDialer
FXRealSpinDial* GUIDialog_ViewSettings::myContainerMinSizeDialer private
Definition at line 306 of file GUIDialog_ViewSettings.h.
myContainerNamePanel
NamePanel * GUIDialog_ViewSettings::myContainerNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myContainerShapeDetail
FXComboBox * GUIDialog_ViewSettings::myContainerShapeDetail private
Definition at line 300 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myContainerSizePanel
SizePanel * GUIDialog_ViewSettings::myContainerSizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myContainerThresholds
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myContainerThresholds private
Definition at line 303 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myContainerUpscaleDialer
FXRealSpinDial * GUIDialog_ViewSettings::myContainerUpscaleDialer private
Definition at line 306 of file GUIDialog_ViewSettings.h.
myCwaEdgeNamePanel
NamePanel * GUIDialog_ViewSettings::myCwaEdgeNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myDecals
std::vector<GUISUMOAbstractView::Decal>* GUIDialog_ViewSettings::myDecals private
The parent's decals.
Definition at line 247 of file GUIDialog_ViewSettings.h.
Referenced by onCmdEditTable(), rebuildList(), and saveDecals().
myDecalsFrame
FXVerticalFrame* GUIDialog_ViewSettings::myDecalsFrame private
Definition at line 259 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myDecalsLock
MFXMutex* GUIDialog_ViewSettings::myDecalsLock private
Lock used when changing the decals.
Definition at line 250 of file GUIDialog_ViewSettings.h.
Referenced by loadDecals(), loadSettings(), and onCmdEditTable().
myDecalsTable
MFXAddEditTypedTable* GUIDialog_ViewSettings::myDecalsTable private
Definition at line 260 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices(), and rebuildList().
myDither
FXCheckButton* GUIDialog_ViewSettings::myDither private
Definition at line 318 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myDrawCrossingsAndWalkingAreas
FXCheckButton* GUIDialog_ViewSettings::myDrawCrossingsAndWalkingAreas private
Definition at line 317 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myDrawJunctionShape
FXCheckButton* GUIDialog_ViewSettings::myDrawJunctionShape private
Definition at line 316 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myEdgeNamePanel
NamePanel* GUIDialog_ViewSettings::myEdgeNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myGridXSizeDialer
FXRealSpinDial* GUIDialog_ViewSettings::myGridXSizeDialer private
Definition at line 256 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange().
myGridYSizeDialer
FXRealSpinDial * GUIDialog_ViewSettings::myGridYSizeDialer private
Definition at line 256 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange().
myHideMacroConnectors
FXCheckButton * GUIDialog_ViewSettings::myHideMacroConnectors private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myInternalEdgeNamePanel
NamePanel * GUIDialog_ViewSettings::myInternalEdgeNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myInternalJunctionNamePanel
NamePanel * GUIDialog_ViewSettings::myInternalJunctionNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myJunctionButtons
std::vector<FXButton*> GUIDialog_ViewSettings::myJunctionButtons private
Definition at line 312 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myJunctionColorInterpolation
FXCheckButton* GUIDialog_ViewSettings::myJunctionColorInterpolation private
Definition at line 313 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myJunctionColorMode
FXComboBox* GUIDialog_ViewSettings::myJunctionColorMode private
Definition at line 308 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myJunctionColorRainbow
FXButton* GUIDialog_ViewSettings::myJunctionColorRainbow private
Definition at line 270 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myJunctionColors
std::vector<FXColorWell*> GUIDialog_ViewSettings::myJunctionColors private
Definition at line 310 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myJunctionColorSettingFrame
FXVerticalFrame* GUIDialog_ViewSettings::myJunctionColorSettingFrame private
Definition at line 309 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myJunctionIndexPanel
NamePanel * GUIDialog_ViewSettings::myJunctionIndexPanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myJunctionNamePanel
NamePanel * GUIDialog_ViewSettings::myJunctionNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myJunctionSizePanel
SizePanel * GUIDialog_ViewSettings::myJunctionSizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myJunctionThresholds
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myJunctionThresholds private
Definition at line 311 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneButtons
std::vector<FXButton*> GUIDialog_ViewSettings::myLaneButtons private
Definition at line 267 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneColorInterpolation
FXCheckButton* GUIDialog_ViewSettings::myLaneColorInterpolation private
Definition at line 268 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneColorRainbow
FXButton* GUIDialog_ViewSettings::myLaneColorRainbow private
Definition at line 269 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneColors
std::vector<FXColorWell*> GUIDialog_ViewSettings::myLaneColors private
Definition at line 265 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneColorSettingFrame
FXVerticalFrame* GUIDialog_ViewSettings::myLaneColorSettingFrame private
Definition at line 264 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myLaneEdgeColorMode
FXComboBox* GUIDialog_ViewSettings::myLaneEdgeColorMode private
... lane colorer
Definition at line 263 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myLaneEdgeScaleMode
FXComboBox* GUIDialog_ViewSettings::myLaneEdgeScaleMode private
... lane scaler
Definition at line 273 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myLaneMinWidthDialer
FXRealSpinDial* GUIDialog_ViewSettings::myLaneMinWidthDialer private
Definition at line 283 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myLaneScaleButtons
std::vector<FXButton*> GUIDialog_ViewSettings::myLaneScaleButtons private
Definition at line 277 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneScaleInterpolation
FXCheckButton* GUIDialog_ViewSettings::myLaneScaleInterpolation private
Definition at line 278 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneScales
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myLaneScales private
Definition at line 275 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneScaleSettingFrame
FXVerticalFrame* GUIDialog_ViewSettings::myLaneScaleSettingFrame private
Definition at line 274 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myLaneScaleThresholds
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myLaneScaleThresholds private
Definition at line 276 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneThresholds
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myLaneThresholds private
Definition at line 266 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myLaneWidthUpscaleDialer
FXRealSpinDial* GUIDialog_ViewSettings::myLaneWidthUpscaleDialer private
Definition at line 282 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myParent
GUISUMOAbstractView* GUIDialog_ViewSettings::myParent private
The parent view (which settings are changed)
Definition at line 238 of file GUIDialog_ViewSettings.h.
Referenced by loadDecals(), loadSettings(), onCmdColorChange(), onCmdEditTable(), onCmdExportSetting(), onCmdNameChange(), onCmdSaveDecals(), onCmdSaveSetting(), and ~GUIDialog_ViewSettings().
myPersonButtons
std::vector<FXButton*> GUIDialog_ViewSettings::myPersonButtons private
Definition at line 297 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myPersonColorInterpolation
FXCheckButton* GUIDialog_ViewSettings::myPersonColorInterpolation private
Definition at line 298 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myPersonColorMode
FXComboBox* GUIDialog_ViewSettings::myPersonColorMode private
Definition at line 293 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myPersonColors
std::vector<FXColorWell*> GUIDialog_ViewSettings::myPersonColors private
Definition at line 295 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myPersonColorSettingFrame
FXVerticalFrame* GUIDialog_ViewSettings::myPersonColorSettingFrame private
Definition at line 294 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myPersonNamePanel
NamePanel * GUIDialog_ViewSettings::myPersonNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myPersonShapeDetail
FXComboBox * GUIDialog_ViewSettings::myPersonShapeDetail private
Definition at line 293 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myPersonSizePanel
SizePanel * GUIDialog_ViewSettings::myPersonSizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myPersonThresholds
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myPersonThresholds private
Definition at line 296 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myPOINamePanel
NamePanel * GUIDialog_ViewSettings::myPOINamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myPOISizePanel
SizePanel * GUIDialog_ViewSettings::myPOISizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myPOITypePanel
NamePanel * GUIDialog_ViewSettings::myPOITypePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myPolyNamePanel
NamePanel * GUIDialog_ViewSettings::myPolyNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myPolySizePanel
SizePanel * GUIDialog_ViewSettings::myPolySizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myPolyTypePanel
NamePanel * GUIDialog_ViewSettings::myPolyTypePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
mySaveDecals
FXCheckButton * GUIDialog_ViewSettings::mySaveDecals private
Definition at line 331 of file GUIDialog_ViewSettings.h.
Referenced by onCmdExportSetting(), and onUpdExportSetting().
mySaveDelay
FXCheckButton * GUIDialog_ViewSettings::mySaveDelay private
Definition at line 331 of file GUIDialog_ViewSettings.h.
Referenced by onCmdExportSetting(), and onUpdExportSetting().
mySaveViewPort
FXCheckButton* GUIDialog_ViewSettings::mySaveViewPort private
Definition at line 331 of file GUIDialog_ViewSettings.h.
Referenced by onCmdExportSetting(), and onUpdExportSetting().
mySchemeName
FXComboBox* GUIDialog_ViewSettings::mySchemeName private
Definition at line 254 of file GUIDialog_ViewSettings.h.
Referenced by getCurrentScheme(), loadSettings(), onCmdColorChange(), onCmdDeleteSetting(), onCmdNameChange(), onCmdSaveSetting(), onUpdDeleteSetting(), onUpdExportSetting(), onUpdSaveSetting(), and setCurrentScheme().
mySettings
GUIVisualizationSettings* GUIDialog_ViewSettings::mySettings private
The current settings.
Definition at line 241 of file GUIDialog_ViewSettings.h.
Referenced by loadSettings(), onCmdColorChange(), onCmdExportSetting(), onCmdNameChange(), onCmdSaveSetting(), rebuildColorMatrices(), setCurrent(), and show().
myShowBlinker
FXCheckButton* GUIDialog_ViewSettings::myShowBlinker private
Definition at line 291 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowBTRange
FXCheckButton * GUIDialog_ViewSettings::myShowBTRange private
Definition at line 291 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowGrid
FXCheckButton* GUIDialog_ViewSettings::myShowGrid private
Definition at line 255 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and show().
myShowLane2Lane
FXCheckButton* GUIDialog_ViewSettings::myShowLane2Lane private
Definition at line 315 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowLaneBorders
FXCheckButton* GUIDialog_ViewSettings::myShowLaneBorders private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowLaneDecals
FXCheckButton * GUIDialog_ViewSettings::myShowLaneDecals private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowLaneDirection
FXCheckButton * GUIDialog_ViewSettings::myShowLaneDirection private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowLinkRules
FXCheckButton * GUIDialog_ViewSettings::myShowLinkRules private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowMinGap
FXCheckButton * GUIDialog_ViewSettings::myShowMinGap private
Definition at line 291 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowRails
FXCheckButton * GUIDialog_ViewSettings::myShowRails private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowSizeLegend
FXCheckButton* GUIDialog_ViewSettings::myShowSizeLegend private
Definition at line 319 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myShowSublanes
FXCheckButton * GUIDialog_ViewSettings::myShowSublanes private
Definition at line 280 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myStreetNamePanel
NamePanel * GUIDialog_ViewSettings::myStreetNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myTLIndexPanel
NamePanel * GUIDialog_ViewSettings::myTLIndexPanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myVehicleButtons
std::vector<FXButton*> GUIDialog_ViewSettings::myVehicleButtons private
Definition at line 289 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myVehicleColorInterpolation
FXCheckButton* GUIDialog_ViewSettings::myVehicleColorInterpolation private
Definition at line 290 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myVehicleColorMode
FXComboBox* GUIDialog_ViewSettings::myVehicleColorMode private
Definition at line 285 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myVehicleColors
std::vector<FXColorWell*> GUIDialog_ViewSettings::myVehicleColors private
Definition at line 287 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
myVehicleColorSettingFrame
FXVerticalFrame* GUIDialog_ViewSettings::myVehicleColorSettingFrame private
Definition at line 286 of file GUIDialog_ViewSettings.h.
Referenced by rebuildColorMatrices().
myVehicleNamePanel
NamePanel * GUIDialog_ViewSettings::myVehicleNamePanel private
Definition at line 321 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myVehicleShapeDetail
FXComboBox * GUIDialog_ViewSettings::myVehicleShapeDetail private
Definition at line 285 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and onCmdNameChange().
myVehicleSizePanel
SizePanel* GUIDialog_ViewSettings::myVehicleSizePanel private
Definition at line 327 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), onCmdNameChange(), and ~GUIDialog_ViewSettings().
myVehicleThresholds
std::vector<FXRealSpinDial*> GUIDialog_ViewSettings::myVehicleThresholds private
Definition at line 288 of file GUIDialog_ViewSettings.h.
Referenced by onCmdColorChange(), and rebuildColorMatrices().
The documentation for this class was generated from the following files:
GUIDialog_ViewSettings.h
GUIDialog_ViewSettings.cpp