SUMO - Simulation of Urban MObility: GNEVariableSpeedSignDialog Class Reference
GNEVariableSpeedSignDialog Class Reference
#include <GNEVariableSpeedSignDialog.h>
Public Member Functions
GNEVariableSpeedSign * getEditedVariableSpeedSign () const
get edited Variable Speed Sign
GNEVariableSpeedSignDialog (GNEVariableSpeedSign *editedVariableSpeedSign)
FOX-declaration.
~GNEVariableSpeedSignDialog ()
destructor
FOX-callbacks
event called after press add row button
long onCmdAddStep (FXObject *, FXSelector, void *)
long onCmdEditStep (FXObject *, FXSelector, void *)
event called after edit row
long onCmdClickedStep (FXObject *, FXSelector, void *)
event called after clicked a row
long onCmdAccept (FXObject *, FXSelector, void *)
event called after press accept button
long onCmdCancel (FXObject *, FXSelector, void *)
event called after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event called after press cancel button
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNEVariableSpeedSignDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
Protected Attributes
FXButton * myAddStepButton
Button for insert row.
FXHorizontalFrame * myAddStepFrame
Horizontal frame for row elements.
FXVerticalFrame * myContentFrame
frame for contents
GNEVariableSpeedSign * myEditedVariableSpeedSign
Pointer to Variable Speed Signal.
FXTable * myStepsTable
Table with the data.
bool myStepsValids
Private Member Functions
GNEVariableSpeedSignDialog (const GNEVariableSpeedSignDialog &)=delete
Invalidated copy constructor.
GNEVariableSpeedSignDialog & operator= (const GNEVariableSpeedSignDialog &)=delete
Invalidated assignment operator.
void updateTableSteps ()
update data table
Detailed Description
Definition at line 51 of file GNEVariableSpeedSignDialog.h.
Constructor & Destructor Documentation
GNEVariableSpeedSignDialog() [1/3]
GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog (GNEVariableSpeedSign * editedVariableSpeedSign)
FOX-declaration.
constructor
Definition at line 61 of file GNEVariableSpeedSignDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelThick, GUIDesignTableAdditionals, ICON_ADD, MID_GNE_VARIABLESPEEDSIGN_ADDROW, MID_GNE_VARIABLESPEEDSIGN_TABLE_STEPS, SUMO_TAG_STEP, and toString().
~GNEVariableSpeedSignDialog()
GNEVariableSpeedSignDialog::~GNEVariableSpeedSignDialog ()
destructor
Definition at line 88 of file GNEVariableSpeedSignDialog.cpp.
GNEVariableSpeedSignDialog() [2/3]
GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog () inline protected
FOX needs this.
Definition at line 88 of file GNEVariableSpeedSignDialog.h.
GNEVariableSpeedSignDialog() [3/3]
GNEVariableSpeedSignDialog::GNEVariableSpeedSignDialog (const GNEVariableSpeedSignDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNECalibratorDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), GNERerouterDialog::onCmdCancel(), GNECalibratorDialog::onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
getEditedVariableSpeedSign()
GNEVariableSpeedSign * GNEVariableSpeedSignDialog::getEditedVariableSpeedSign () const
get edited Variable Speed Sign
Definition at line 92 of file GNEVariableSpeedSignDialog.cpp.
References myEditedVariableSpeedSign.
Referenced by GNEVariableSpeedSignStep::GNEVariableSpeedSignStep().
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNEVariableSpeedSignDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
event called after press accept button
Implements GNEAdditionalDialog.
Definition at line 151 of file GNEVariableSpeedSignDialog.cpp.
References GNEAdditionalDialog::acceptChanges(), OptionsCont::getOptions(), myEditedVariableSpeedSign, myStepsValids, GNEVariableSpeedSign::sortVariableSpeedSignSteps(), SUMO_TAG_STEP, SUMO_TAG_VSS, toString(), and WRITE_WARNING.
onCmdAddStep()
long GNEVariableSpeedSignDialog::onCmdAddStep (FXObject * , FXSelector , void *)
Definition at line 98 of file GNEVariableSpeedSignDialog.cpp.
References GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), myEditedVariableSpeedSign, and updateTableSteps().
onCmdCancel()
long GNEVariableSpeedSignDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event called after press cancel button
Implements GNEAdditionalDialog.
Definition at line 179 of file GNEVariableSpeedSignDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdClickedStep()
long GNEVariableSpeedSignDialog::onCmdClickedStep (FXObject * , FXSelector , void *)
event called after clicked a row
Definition at line 135 of file GNEVariableSpeedSignDialog.cpp.
References GNEViewNet::getUndoList(), GNEVariableSpeedSign::getVariableSpeedSignSteps(), GNEAdditional::getViewNet(), myEditedVariableSpeedSign, myStepsTable, and updateTableSteps().
onCmdEditStep()
long GNEVariableSpeedSignDialog::onCmdEditStep (FXObject * , FXSelector , void *)
event called after edit row
Definition at line 109 of file GNEVariableSpeedSignDialog.cpp.
References GUIIconSubSys::getIcon(), GNEViewNet::getUndoList(), GNEVariableSpeedSign::getVariableSpeedSignSteps(), GNEAdditional::getViewNet(), ICON_CORRECT, ICON_ERROR, GNEVariableSpeedSignStep::isValid(), myEditedVariableSpeedSign, myStepsTable, myStepsValids, GNEVariableSpeedSignStep::setAttribute(), SUMO_ATTR_SPEED, and SUMO_ATTR_TIME.
onCmdReset()
long GNEVariableSpeedSignDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event called after press cancel button
Implements GNEAdditionalDialog.
Definition at line 189 of file GNEVariableSpeedSignDialog.cpp.
References GNEAdditionalDialog::resetChanges(), and updateTableSteps().
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNEVariableSpeedSignDialog& GNEVariableSpeedSignDialog::operator= (const GNEVariableSpeedSignDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), GNERerouterDialog::onCmdReset(), GNECalibratorDialog::onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and onCmdReset().
updateTableSteps()
void GNEVariableSpeedSignDialog::updateTableSteps () private
update data table
Definition at line 199 of file GNEVariableSpeedSignDialog.cpp.
References GUIIconSubSys::getIcon(), GNEVariableSpeedSign::getVariableSpeedSignSteps(), GUIDesignTableIconCellWidth, ICON_CORRECT, ICON_REMOVE, myEditedVariableSpeedSign, myStepsTable, SUMO_ATTR_SPEED, and SUMO_ATTR_TIME.
Referenced by onCmdAddStep(), onCmdClickedStep(), and onCmdReset().
Field Documentation
myAddStepButton
FXButton* GNEVariableSpeedSignDialog::myAddStepButton protected
Button for insert row.
Definition at line 100 of file GNEVariableSpeedSignDialog.h.
myAddStepFrame
FXHorizontalFrame* GNEVariableSpeedSignDialog::myAddStepFrame protected
Horizontal frame for row elements.
Definition at line 97 of file GNEVariableSpeedSignDialog.h.
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myEditedVariableSpeedSign
GNEVariableSpeedSign* GNEVariableSpeedSignDialog::myEditedVariableSpeedSign protected
Pointer to Variable Speed Signal.
Definition at line 91 of file GNEVariableSpeedSignDialog.h.
Referenced by getEditedVariableSpeedSign(), onCmdAccept(), onCmdAddStep(), onCmdClickedStep(), onCmdEditStep(), and updateTableSteps().
myStepsTable
FXTable* GNEVariableSpeedSignDialog::myStepsTable protected
Table with the data.
Definition at line 94 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdClickedStep(), onCmdEditStep(), and updateTableSteps().
myStepsValids
bool GNEVariableSpeedSignDialog::myStepsValids protected
Definition at line 102 of file GNEVariableSpeedSignDialog.h.
Referenced by onCmdAccept(), and onCmdEditStep().
The documentation for this class was generated from the following files:
GNEVariableSpeedSignDialog.h
GNEVariableSpeedSignDialog.cpp