SUMO - Simulation of Urban MObility: GUIPropertySchemeStorage< T > Class Template Reference
GUIPropertySchemeStorage< T > Class Template Reference
Base class for coloring. Allows changing the used colors and sets the used color in dependence to a value.
#include <GUIPropertySchemeStorage.h>
Public Member Functions
void addScheme (T scheme)
void fill (FXComboBox &cb)
Fills the given combobox with the names of available colorings.
int getActive () const
T & getScheme ()
const T & getScheme () const
T * getSchemeByName (std::string name)
const std::vector< T > & getSchemes () const
GUIPropertySchemeStorage ()
Constructor.
bool operator== (const GUIPropertySchemeStorage &c) const
void save (OutputDevice &dev) const
void setActive (int scheme)
int size () const
virtual ~GUIPropertySchemeStorage ()
Destructor.
Protected Attributes
int myActiveScheme
std::vector< T > mySchemes
Detailed Description
template<class T>
class GUIPropertySchemeStorage< T >
Base class for coloring. Allows changing the used colors and sets the used color in dependence to a value.
Definition at line 55 of file GUIPropertySchemeStorage.h.
Constructor & Destructor Documentation
GUIPropertySchemeStorage()
template<class T> GUIPropertySchemeStorage< T >::GUIPropertySchemeStorage () inline
Constructor.
Definition at line 58 of file GUIPropertySchemeStorage.h.
~GUIPropertySchemeStorage()
template<class T> virtual GUIPropertySchemeStorage< T >::~GUIPropertySchemeStorage () inline virtual
Destructor.
Definition at line 61 of file GUIPropertySchemeStorage.h.
Member Function Documentation
addScheme()
template<class T> void GUIPropertySchemeStorage< T >::addScheme (T scheme) inline
Definition at line 113 of file GUIPropertySchemeStorage.h.
Referenced by GUIVisualizationSettings::initNeteditDefaults(), and GUIVisualizationSettings::initSumoGuiDefaults().
fill()
template<class T> void GUIPropertySchemeStorage< T >::fill (FXComboBox & cb) inline
Fills the given combobox with the names of available colorings.
Definition at line 64 of file GUIPropertySchemeStorage.h.
getActive()
template<class T> int GUIPropertySchemeStorage< T >::getActive () const inline
Definition at line 77 of file GUIPropertySchemeStorage.h.
Referenced by GUILane::drawAsWaterway(), GNEConnection::drawGL(), GNEEdge::drawGL(), GUILane::drawGL(), GUIJunctionWrapper::getColorValue(), GNEJunction::getColorValue(), GUIVisualizationSettings::getLaneEdgeMode(), GUIVisualizationSettings::getLaneEdgeScaleMode(), GUIDialog_ViewSettings::onCmdColorChange(), GUIDialog_ViewSettings::onCmdNameChange(), GUIVisualizationSettings::save(), GUIEdge::setColor(), GUIContainer::setColor(), GUIPerson::setColor(), GNEJunction::setColor(), GUILane::setColor(), GUIBaseVehicle::setColor(), GNELane::setLaneColor(), GUIEdge::setMultiColor(), GNELane::setMultiColor(), and GUILane::setMultiColor().
getScheme() [1/2]
template<class T> T& GUIPropertySchemeStorage< T >::getScheme () inline
Definition at line 81 of file GUIPropertySchemeStorage.h.
Referenced by GUILane::drawAsWaterway(), GUIJunctionWrapper::drawGL(), GUILane::drawGL(), GUIJunctionWrapper::getColorValue(), GUIVisualizationSettings::getLaneEdgeScaleScheme(), GUIVisualizationSettings::getLaneEdgeScheme(), GUIDialog_ViewSettings::onCmdColorChange(), GUIDialog_ViewSettings::rebuildColorMatrices(), GUIEdge::setColor(), GUIContainer::setColor(), GUIPerson::setColor(), GNEJunction::setColor(), GUILane::setColor(), GUIBaseVehicle::setColor(), GNELane::setLaneColor(), GUIEdge::setMultiColor(), GNELane::setMultiColor(), and GUILane::setMultiColor().
getScheme() [2/2]
template<class T> const T& GUIPropertySchemeStorage< T >::getScheme () const inline
Definition at line 85 of file GUIPropertySchemeStorage.h.
getSchemeByName()
template<class T> T* GUIPropertySchemeStorage< T >::getSchemeByName (std::string name) inline
Definition at line 93 of file GUIPropertySchemeStorage.h.
Referenced by GUISettingsHandler::myStartElement().
getSchemes()
template<class T> const std::vector<T>& GUIPropertySchemeStorage< T >::getSchemes () const inline
Definition at line 89 of file GUIPropertySchemeStorage.h.
Referenced by GNEEdge::drawGL().
operator==()
template<class T> bool GUIPropertySchemeStorage< T >::operator== (const GUIPropertySchemeStorage< T > & c) const inline
Definition at line 108 of file GUIPropertySchemeStorage.h.
save()
template<class T> void GUIPropertySchemeStorage< T >::save (OutputDevice & dev) const inline
Definition at line 102 of file GUIPropertySchemeStorage.h.
Referenced by GUIVisualizationSettings::save().
setActive()
template<class T> void GUIPropertySchemeStorage< T >::setActive (int scheme) inline
Definition at line 71 of file GUIPropertySchemeStorage.h.
Referenced by GUISettingsHandler::myStartElement(), GUIDialog_ViewSettings::onCmdColorChange(), and GUIApplicationWindow::onCmdEditChosen().
size()
template<class T> int GUIPropertySchemeStorage< T >::size () const inline
Definition at line 117 of file GUIPropertySchemeStorage.h.
Field Documentation
myActiveScheme
template<class T> int GUIPropertySchemeStorage< T >::myActiveScheme protected
Definition at line 123 of file GUIPropertySchemeStorage.h.
Referenced by GUIPropertySchemeStorage< GUIScaleScheme >::fill(), GUIPropertySchemeStorage< GUIScaleScheme >::getActive(), GUIPropertySchemeStorage< GUIScaleScheme >::getScheme(), GUIPropertySchemeStorage< GUIScaleScheme >::operator==(), and GUIPropertySchemeStorage< GUIScaleScheme >::setActive().
mySchemes
template<class T> std::vector<T> GUIPropertySchemeStorage< T >::mySchemes protected
Definition at line 124 of file GUIPropertySchemeStorage.h.
Referenced by GUIPropertySchemeStorage< GUIScaleScheme >::addScheme(), GUIPropertySchemeStorage< GUIScaleScheme >::fill(), GUIPropertySchemeStorage< GUIScaleScheme >::getScheme(), GUIPropertySchemeStorage< GUIScaleScheme >::getSchemeByName(), GUIPropertySchemeStorage< GUIScaleScheme >::getSchemes(), GUIPropertySchemeStorage< GUIScaleScheme >::operator==(), GUIPropertySchemeStorage< GUIScaleScheme >::save(), GUIPropertySchemeStorage< GUIScaleScheme >::setActive(), and GUIPropertySchemeStorage< GUIScaleScheme >::size().
The documentation for this class was generated from the following file:
GUIPropertySchemeStorage.h