SUMO - Simulation of Urban MObility: MFXAddEditTypedTable Class Reference
MFXAddEditTypedTable Class Reference
#include <MFXAddEditTypedTable.h>
Data Structures
struct EditedTableItem
struct NumberCellParams
Public Types
enum { ID_TEXT_CHANGED = FXTable::ID_LAST, ID_LAST }
Public Member Functions
void addEnum (int pos, const std::string &e)
void cancelInput ()
CellType getCellType (int pos) const
const std::vector< std::string > & getEnums (int pos) const
NumberCellParams getNumberCellParams (int pos) const
MFXAddEditTypedTable (FXComposite *p, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=0, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_MARGIN, FXint pr=DEFAULT_MARGIN, FXint pt=DEFAULT_MARGIN, FXint pb=DEFAULT_MARGIN)
long onClicked (FXObject *, FXSelector, void *ptr)
long onDoubleClicked (FXObject *, FXSelector, void *ptr)
long onLeftBtnPress (FXObject *, FXSelector, void *ptr)
long onLeftBtnRelease (FXObject *, FXSelector, void *ptr)
void setCellType (int pos, CellType t)
void setEnums (int pos, const std::vector< std::string > &params)
void setNumberCellParams (int pos, double min, double max, double steps1, double steps2, double steps3, const std::string &format)
~MFXAddEditTypedTable ()
Protected Member Functions
void acceptInput (FXbool notify)
virtual FXWindow * getControlForItem (FXint r, FXint c)
MFXAddEditTypedTable ()
virtual void setItemFromControl (FXint r, FXint c, FXWindow *control)
void setItemFromControl_NoRelease (FXint r, FXint c, FXWindow *control)
Protected Attributes
std::vector< CellType > myCellTypes
std::vector< std::vector< std::string > > myEnums
std::vector< NumberCellParams > myNumberCellParams
Detailed Description
Definition at line 48 of file MFXAddEditTypedTable.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_TEXT_CHANGED
ID_LAST
Definition at line 136 of file MFXAddEditTypedTable.h.
Constructor & Destructor Documentation
MFXAddEditTypedTable() [1/2]
MFXAddEditTypedTable::MFXAddEditTypedTable (FXComposite * p, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = 0, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_MARGIN, FXint pr = DEFAULT_MARGIN, FXint pt = DEFAULT_MARGIN, FXint pb = DEFAULT_MARGIN)
Definition at line 49 of file MFXAddEditTypedTable.cpp.
~MFXAddEditTypedTable()
MFXAddEditTypedTable::~MFXAddEditTypedTable ()
Definition at line 56 of file MFXAddEditTypedTable.cpp.
MFXAddEditTypedTable() [2/2]
MFXAddEditTypedTable::MFXAddEditTypedTable () inline protected
Definition at line 159 of file MFXAddEditTypedTable.h.
Member Function Documentation
acceptInput()
void MFXAddEditTypedTable::acceptInput (FXbool notify) protected
Definition at line 289 of file MFXAddEditTypedTable.cpp.
References cancelInput(), setItemFromControl(), and setItemFromControl_NoRelease().
addEnum()
void MFXAddEditTypedTable::addEnum (int pos, const std::string & e)
Definition at line 614 of file MFXAddEditTypedTable.cpp.
References myEnums.
cancelInput()
void MFXAddEditTypedTable::cancelInput ()
Definition at line 276 of file MFXAddEditTypedTable.cpp.
Referenced by acceptInput().
getCellType()
CellType MFXAddEditTypedTable::getCellType (int pos) const
Definition at line 552 of file MFXAddEditTypedTable.cpp.
References CT_UNDEFINED, and myCellTypes.
Referenced by getControlForItem(), setItemFromControl(), and setItemFromControl_NoRelease().
getControlForItem()
FXWindow * MFXAddEditTypedTable::getControlForItem (FXint r, FXint c) protected virtual
Definition at line 197 of file MFXAddEditTypedTable.cpp.
References TplConvert::_2double(), TplConvert::_2int(), CT_BOOL, CT_ENUM, CT_INT, CT_REAL, CT_STRING, CT_UNDEFINED, MFXAddEditTypedTable::NumberCellParams::format, getCellType(), getNumberCellParams(), MFXAddEditTypedTable::NumberCellParams::max, MFXAddEditTypedTable::NumberCellParams::min, MFXAddEditTypedTable::NumberCellParams::steps1, MFXAddEditTypedTable::NumberCellParams::steps2, and MFXAddEditTypedTable::NumberCellParams::steps3.
getEnums()
const std::vector< std::string > & MFXAddEditTypedTable::getEnums (int pos) const
Definition at line 624 of file MFXAddEditTypedTable.cpp.
References myEnums.
getNumberCellParams()
MFXAddEditTypedTable::NumberCellParams MFXAddEditTypedTable::getNumberCellParams (int pos) const
Definition at line 592 of file MFXAddEditTypedTable.cpp.
References MFXAddEditTypedTable::NumberCellParams::format, and myNumberCellParams.
Referenced by getControlForItem().
onClicked()
long MFXAddEditTypedTable::onClicked (FXObject * , FXSelector , void * ptr)
Definition at line 513 of file MFXAddEditTypedTable.cpp.
onDoubleClicked()
long MFXAddEditTypedTable::onDoubleClicked (FXObject * , FXSelector , void * ptr)
Definition at line 533 of file MFXAddEditTypedTable.cpp.
onLeftBtnPress()
long MFXAddEditTypedTable::onLeftBtnPress (FXObject * , FXSelector , void * ptr)
Definition at line 452 of file MFXAddEditTypedTable.cpp.
onLeftBtnRelease()
long MFXAddEditTypedTable::onLeftBtnRelease (FXObject * , FXSelector , void * ptr)
Definition at line 412 of file MFXAddEditTypedTable.cpp.
setCellType()
void MFXAddEditTypedTable::setCellType (int pos, CellType t)
Definition at line 561 of file MFXAddEditTypedTable.cpp.
References CT_UNDEFINED, and myCellTypes.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrices().
setEnums()
void MFXAddEditTypedTable::setEnums (int pos, const std::vector< std::string > & params)
Definition at line 604 of file MFXAddEditTypedTable.cpp.
References myEnums.
setItemFromControl()
void MFXAddEditTypedTable::setItemFromControl (FXint r, FXint c, FXWindow * control) protected virtual
Definition at line 320 of file MFXAddEditTypedTable.cpp.
References MFXAddEditTypedTable::EditedTableItem::col, CT_BOOL, CT_ENUM, CT_INT, CT_REAL, CT_STRING, CT_UNDEFINED, getCellType(), ID_TEXT_CHANGED, MFXAddEditTypedTable::EditedTableItem::item, MFXAddEditTypedTable::EditedTableItem::row, toString(), and MFXAddEditTypedTable::EditedTableItem::updateOnly.
Referenced by acceptInput().
setItemFromControl_NoRelease()
void MFXAddEditTypedTable::setItemFromControl_NoRelease (FXint r, FXint c, FXWindow * control) protected
Definition at line 375 of file MFXAddEditTypedTable.cpp.
References MFXAddEditTypedTable::EditedTableItem::col, CT_BOOL, CT_ENUM, CT_INT, CT_REAL, CT_STRING, CT_UNDEFINED, getCellType(), ID_TEXT_CHANGED, MFXAddEditTypedTable::EditedTableItem::item, MFXAddEditTypedTable::EditedTableItem::row, toString(), and MFXAddEditTypedTable::EditedTableItem::updateOnly.
Referenced by acceptInput().
setNumberCellParams()
void MFXAddEditTypedTable::setNumberCellParams (int pos, double min, double max, double steps1, double steps2, double steps3, const std::string & format)
Definition at line 569 of file MFXAddEditTypedTable.cpp.
References MFXAddEditTypedTable::NumberCellParams::format, MFXAddEditTypedTable::NumberCellParams::max, MFXAddEditTypedTable::NumberCellParams::min, myNumberCellParams, MFXAddEditTypedTable::NumberCellParams::pos, MFXAddEditTypedTable::NumberCellParams::steps1, MFXAddEditTypedTable::NumberCellParams::steps2, and MFXAddEditTypedTable::NumberCellParams::steps3.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrices().
Field Documentation
myCellTypes
std::vector<CellType> MFXAddEditTypedTable::myCellTypes protected
Definition at line 154 of file MFXAddEditTypedTable.h.
Referenced by getCellType(), and setCellType().
myEnums
std::vector<std::vector<std::string> > MFXAddEditTypedTable::myEnums protected
Definition at line 156 of file MFXAddEditTypedTable.h.
Referenced by addEnum(), getEnums(), and setEnums().
myNumberCellParams
std::vector<NumberCellParams> MFXAddEditTypedTable::myNumberCellParams protected
Definition at line 155 of file MFXAddEditTypedTable.h.
Referenced by getNumberCellParams(), and setNumberCellParams().
The documentation for this class was generated from the following files:
MFXAddEditTypedTable.h
MFXAddEditTypedTable.cpp