SUMO - Simulation of Urban MObility: libsumo::InductionLoop Class Reference
libsumo::InductionLoop Class Reference
#include <InductionLoop.h>
Static Public Member Functions
static int getIDCount ()
static std::vector< std::string > getIDList ()
static std::string getLaneID (const std::string &detID)
static double getLastStepMeanLength (const std::string &detID)
static double getLastStepMeanSpeed (const std::string &detID)
static double getLastStepOccupancy (const std::string &detID)
static std::vector< std::string > getLastStepVehicleIDs (const std::string &detID)
static int getLastStepVehicleNumber (const std::string &detID)
static double getPosition (const std::string &detID)
static double getTimeSinceDetection (const std::string &detID)
static NamedRTree * getTree ()
Returns a tree filled with inductive loop instances.
static std::vector< libsumo::TraCIVehicleData > getVehicleData (const std::string &detID)
Private Member Functions
InductionLoop ()
invalidated standard constructor
InductionLoop (const InductionLoop &src)
invalidated copy constructor
InductionLoop & operator= (const InductionLoop &src)
invalidated assignment operator
Static Private Member Functions
static MSInductLoop * getDetector (const std::string &detID)
Detailed Description
Definition at line 52 of file InductionLoop.h.
Constructor & Destructor Documentation
InductionLoop() [1/2]
libsumo::InductionLoop::InductionLoop () private
invalidated standard constructor
InductionLoop() [2/2]
libsumo::InductionLoop::InductionLoop (const InductionLoop & src) private
invalidated copy constructor
Member Function Documentation
getDetector()
MSInductLoop * InductionLoop::getDetector (const std::string & detID) static private
Definition at line 125 of file InductionLoop.cpp.
References NamedObjectCont< T >::get(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), and SUMO_TAG_INDUCTION_LOOP.
Referenced by getLaneID(), getLastStepMeanLength(), getLastStepMeanSpeed(), getLastStepOccupancy(), getLastStepVehicleIDs(), getLastStepVehicleNumber(), getPosition(), getTimeSinceDetection(), and getVehicleData().
getIDCount()
int InductionLoop::getIDCount () static
Definition at line 53 of file InductionLoop.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::size(), and SUMO_TAG_INDUCTION_LOOP.
Referenced by TraCIServerAPI_InductionLoop::processGet().
getIDList()
std::vector< std::string > InductionLoop::getIDList () static
Definition at line 45 of file InductionLoop.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::insertIDs(), and SUMO_TAG_INDUCTION_LOOP.
Referenced by TraCIServerAPI_InductionLoop::processGet().
getLaneID()
std::string InductionLoop::getLaneID (const std::string & detID) static
Definition at line 66 of file InductionLoop.cpp.
References getDetector(), Named::getID(), and MSMoveReminder::getLane().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getLastStepMeanLength()
double InductionLoop::getLastStepMeanLength (const std::string & detID) static
Definition at line 96 of file InductionLoop.cpp.
References MSInductLoop::getCurrentLength(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getLastStepMeanSpeed()
double InductionLoop::getLastStepMeanSpeed (const std::string & detID) static
Definition at line 78 of file InductionLoop.cpp.
References MSInductLoop::getCurrentSpeed(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getLastStepOccupancy()
double InductionLoop::getLastStepOccupancy (const std::string & detID) static
Definition at line 90 of file InductionLoop.cpp.
References MSInductLoop::getCurrentOccupancy(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getLastStepVehicleIDs()
std::vector< std::string > InductionLoop::getLastStepVehicleIDs (const std::string & detID) static
Definition at line 84 of file InductionLoop.cpp.
References MSInductLoop::getCurrentVehicleIDs(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getLastStepVehicleNumber()
int InductionLoop::getLastStepVehicleNumber (const std::string & detID) static
Definition at line 72 of file InductionLoop.cpp.
References MSInductLoop::getCurrentPassedNumber(), and getDetector().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getPosition()
double InductionLoop::getPosition (const std::string & detID) static
Definition at line 60 of file InductionLoop.cpp.
References getDetector(), and MSInductLoop::getPosition().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getTimeSinceDetection()
double InductionLoop::getTimeSinceDetection (const std::string & detID) static
Definition at line 102 of file InductionLoop.cpp.
References getDetector(), and MSInductLoop::getTimeSinceLastDetection().
Referenced by TraCIServerAPI_InductionLoop::processGet().
getTree()
NamedRTree * InductionLoop::getTree () static
Returns a tree filled with inductive loop instances.
Returns
The rtree of inductive loops
Definition at line 134 of file InductionLoop.cpp.
References MSNet::getInstance(), MSMoveReminder::getLane(), MSInductLoop::getPosition(), MSLane::getShape(), NamedRTree::Insert(), PositionVector::positionAtOffset(), SUMO_TAG_INDUCTION_LOOP, Position::x(), and Position::y().
getVehicleData()
std::vector< libsumo::TraCIVehicleData > InductionLoop::getVehicleData (const std::string & detID) static
Definition at line 108 of file InductionLoop.cpp.
References MSInductLoop::collectVehiclesOnDet(), DELTA_T, getDetector(), and MSNet::getInstance().
Referenced by TraCIServerAPI_InductionLoop::processGet().
operator=()
InductionLoop& libsumo::InductionLoop::operator= (const InductionLoop & src) private
invalidated assignment operator
The documentation for this class was generated from the following files:
InductionLoop.h
InductionLoop.cpp