SUMO - Simulation of Urban MObility: AGWorkPosition Class Reference
AGWorkPosition Class Reference
#include <AGWorkPosition.h>
Public Member Functions
AGWorkPosition (AGDataAndStatistics *ds, const AGStreet &inStreet)
AGWorkPosition (AGDataAndStatistics *ds, const AGStreet &inStreet, double pos)
int getClosing () const
int getOpening () const
AGPosition getPosition () const
bool isTaken () const
void let ()
void print () const
void take (AGAdult *ad)
~AGWorkPosition ()
Static Private Member Functions
static int generateClosingTime (const AGDataAndStatistics &ds)
static int generateOpeningTime (const AGDataAndStatistics &ds)
Private Attributes
AGAdult * myAdult
int myClosingTime
AGPosition myLocation
int myOpeningTime
AGDataAndStatistics * myStatData
Detailed Description
Definition at line 55 of file AGWorkPosition.h.
Constructor & Destructor Documentation
AGWorkPosition() [1/2]
AGWorkPosition::AGWorkPosition (AGDataAndStatistics * ds, const AGStreet & inStreet)
Definition at line 47 of file AGWorkPosition.cpp.
References AGDataAndStatistics::workPositions.
AGWorkPosition() [2/2]
AGWorkPosition::AGWorkPosition (AGDataAndStatistics * ds, const AGStreet & inStreet, double pos)
Definition at line 57 of file AGWorkPosition.cpp.
References AGDataAndStatistics::workPositions.
~AGWorkPosition()
AGWorkPosition::~AGWorkPosition ()
Definition at line 66 of file AGWorkPosition.cpp.
Member Function Documentation
generateClosingTime()
int AGWorkPosition::generateClosingTime (const AGDataAndStatistics & ds) static private
Definition at line 97 of file AGWorkPosition.cpp.
References AGDataAndStatistics::endWorkHours, and RandHelper::rand().
generateOpeningTime()
int AGWorkPosition::generateOpeningTime (const AGDataAndStatistics & ds) static private
Definition at line 80 of file AGWorkPosition.cpp.
References AGDataAndStatistics::beginWorkHours, and RandHelper::rand().
getClosing()
int AGWorkPosition::getClosing () const
Definition at line 146 of file AGWorkPosition.cpp.
References myClosingTime.
getOpening()
int AGWorkPosition::getOpening () const
Definition at line 152 of file AGWorkPosition.cpp.
References myOpeningTime.
getPosition()
AGPosition AGWorkPosition::getPosition () const
Definition at line 140 of file AGWorkPosition.cpp.
References myLocation.
isTaken()
bool AGWorkPosition::isTaken () const
Definition at line 113 of file AGWorkPosition.cpp.
References myAdult.
Referenced by print().
let()
void AGWorkPosition::let ()
Definition at line 119 of file AGWorkPosition.cpp.
References AGAdult::lostWorkPosition(), myAdult, myStatData, and AGDataAndStatistics::workPositions.
Referenced by AGAdult::resignFromWorkPosition(), and AGAdult::tryToWork().
print()
void AGWorkPosition::print () const
Definition at line 72 of file AGWorkPosition.cpp.
References isTaken(), myClosingTime, myLocation, myOpeningTime, and AGPosition::print().
take()
void AGWorkPosition::take (AGAdult * ad)
Definition at line 129 of file AGWorkPosition.cpp.
References myAdult, myStatData, and AGDataAndStatistics::workPositions.
Referenced by AGAdult::tryToWork().
Field Documentation
myAdult
AGAdult* AGWorkPosition::myAdult private
Definition at line 78 of file AGWorkPosition.h.
Referenced by isTaken(), let(), and take().
myClosingTime
int AGWorkPosition::myClosingTime private
Definition at line 80 of file AGWorkPosition.h.
Referenced by getClosing(), and print().
myLocation
AGPosition AGWorkPosition::myLocation private
Definition at line 77 of file AGWorkPosition.h.
Referenced by getPosition(), and print().
myOpeningTime
int AGWorkPosition::myOpeningTime private
Definition at line 79 of file AGWorkPosition.h.
Referenced by getOpening(), and print().
myStatData
AGDataAndStatistics* AGWorkPosition::myStatData private
Definition at line 76 of file AGWorkPosition.h.
Referenced by let(), and take().
The documentation for this class was generated from the following files:
AGWorkPosition.h
AGWorkPosition.cpp