SUMO - Simulation of Urban MObility: MFXImageHelper Class Reference
MFXImageHelper Class Reference
#include <MFXImageHelper.h>
Static Public Member Functions
static void checkSupported (FXString ext)
static FXImage * loadImage (FXApp *a, const std::string &file)
static FXbool saveImage (const std::string &file, int width, int height, FXColor *data)
static FXbool scalePower2 (FXImage *image, int maxSize=(2<< 29))
Detailed Description
Definition at line 37 of file MFXImageHelper.h.
Member Function Documentation
checkSupported()
void MFXImageHelper::checkSupported (FXString ext) static
Definition at line 48 of file MFXImageHelper.cpp.
Referenced by loadImage(), and saveImage().
loadImage()
FXImage * MFXImageHelper::loadImage (FXApp * a, const std::string & file) static
Definition at line 66 of file MFXImageHelper.cpp.
References checkSupported(), and toString().
Referenced by GUISUMOAbstractView::drawDecals(), and GUITexturesHelper::getTextureID().
saveImage()
FXbool MFXImageHelper::saveImage (const std::string & file, int width, int height, FXColor * data) static
Definition at line 145 of file MFXImageHelper.cpp.
References checkSupported().
Referenced by GUISUMOAbstractView::makeSnapshot().
scalePower2()
FXbool MFXImageHelper::scalePower2 (FXImage * image, int maxSize = (2 << 29)) static
Definition at line 113 of file MFXImageHelper.cpp.
Referenced by GUISUMOAbstractView::drawDecals(), and GUITexturesHelper::getTextureID().
The documentation for this class was generated from the following files:
MFXImageHelper.h
MFXImageHelper.cpp