SUMO - Simulation of Urban MObility: MSEdgeWeightsStorage Class Reference
MSEdgeWeightsStorage Class Reference
A storage for edge travel times and efforts.
#include <MSEdgeWeightsStorage.h>
Public Member Functions
void addEffort (const MSEdge *const e, double begin, double end, double value)
Adds an effort information for an edge and a time span.
void addTravelTime (const MSEdge *const e, double begin, double end, double value)
Adds a travel time information for an edge and a time span.
bool knowsEffort (const MSEdge *const e) const
Returns the information whether any effort is known for the given edge.
bool knowsTravelTime (const MSEdge *const e) const
Returns the information whether any travel time is known for the given edge.
MSEdgeWeightsStorage ()
Constructor.
void removeEffort (const MSEdge *const e)
Removes the effort information for an edge.
void removeTravelTime (const MSEdge *const e)
Removes the travel time information for an edge.
bool retrieveExistingEffort (const MSEdge *const e, const double t, double &value) const
Returns an effort for an edge and time if stored.
bool retrieveExistingTravelTime (const MSEdge *const e, const double t, double &value) const
Returns a travel time for an edge and time if stored.
~MSEdgeWeightsStorage ()
Destructor.
Private Member Functions
MSEdgeWeightsStorage (const MSEdgeWeightsStorage &)
Invalidated copy constructor.
MSEdgeWeightsStorage & operator= (const MSEdgeWeightsStorage &)
Invalidated assignment operator.
Private Attributes
std::map< const MSEdge *, ValueTimeLine< double > > myEfforts
A map of edge->time->effort.
std::map< const MSEdge *, ValueTimeLine< double > > myTravelTimes
A map of edge->time->travel time.
Detailed Description
A storage for edge travel times and efforts.
Definition at line 50 of file MSEdgeWeightsStorage.h.
Constructor & Destructor Documentation
MSEdgeWeightsStorage() [1/2]
MSEdgeWeightsStorage::MSEdgeWeightsStorage ()
Constructor.
Definition at line 37 of file MSEdgeWeightsStorage.cpp.
~MSEdgeWeightsStorage()
MSEdgeWeightsStorage::~MSEdgeWeightsStorage ()
Destructor.
Definition at line 41 of file MSEdgeWeightsStorage.cpp.
MSEdgeWeightsStorage() [2/2]
MSEdgeWeightsStorage::MSEdgeWeightsStorage (const MSEdgeWeightsStorage &) private
Invalidated copy constructor.
Member Function Documentation
addEffort()
void MSEdgeWeightsStorage::addEffort (const MSEdge *const e, double begin, double end, double value)
Adds an effort information for an edge and a time span.
Parameters
[in] e The described edge
[in] begin The begin of the described time span
[in] end The end of the described time span
[in] value Theeffort value for this edge and time span
Definition at line 89 of file MSEdgeWeightsStorage.cpp.
References myEfforts.
Referenced by NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), libsumo::Edge::addEffort(), and libsumo::Vehicle::setEffort().
addTravelTime()
void MSEdgeWeightsStorage::addTravelTime (const MSEdge *const e, double begin, double end, double value)
Adds a travel time information for an edge and a time span.
Parameters
[in] e The described edge
[in] begin The begin of the described time span
[in] end The end of the described time span
[in] value The travel time value for this edge and time span
Definition at line 76 of file MSEdgeWeightsStorage.cpp.
References myTravelTimes.
Referenced by NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), libsumo::Edge::addTravelTime(), and libsumo::Vehicle::setAdaptedTraveltime().
knowsEffort()
bool MSEdgeWeightsStorage::knowsEffort (const MSEdge *const e) const
Returns the information whether any effort is known for the given edge.
Parameters
[in] e The investigated edge
Returns
Whether any travel time information about this edge is stored
Definition at line 126 of file MSEdgeWeightsStorage.cpp.
References myEfforts.
Referenced by GUILane::getLoadedEdgeWeight(), and libsumo::Vehicle::setEffort().
knowsTravelTime()
bool MSEdgeWeightsStorage::knowsTravelTime (const MSEdge *const e) const
Returns the information whether any travel time is known for the given edge.
Parameters
[in] e The investigated edge
Returns
Whether any travel time information about this edge is stored
Definition at line 120 of file MSEdgeWeightsStorage.cpp.
References myTravelTimes.
Referenced by GUILane::getColorValue(), GUILane::getScaleValue(), GUILane::getStoredEdgeTravelTime(), and libsumo::Vehicle::setAdaptedTraveltime().
operator=()
MSEdgeWeightsStorage& MSEdgeWeightsStorage::operator= (const MSEdgeWeightsStorage &) private
Invalidated assignment operator.
removeEffort()
void MSEdgeWeightsStorage::removeEffort (const MSEdge *const e)
Removes the effort information for an edge.
Parameters
[in] e The described edge
Definition at line 111 of file MSEdgeWeightsStorage.cpp.
References myEfforts.
Referenced by libsumo::Vehicle::setEffort().
removeTravelTime()
void MSEdgeWeightsStorage::removeTravelTime (const MSEdge *const e)
Removes the travel time information for an edge.
Parameters
[in] e The described edge
Definition at line 102 of file MSEdgeWeightsStorage.cpp.
References myTravelTimes.
Referenced by libsumo::Vehicle::setAdaptedTraveltime().
retrieveExistingEffort()
bool MSEdgeWeightsStorage::retrieveExistingEffort (const MSEdge *const e, const double t, double & value) const
Returns an effort for an edge and time if stored.
Parameters
[in] e The edge for which the effort shall be retrieved
[in] t The time for which the effort shall be retrieved
[in] value The value if the requested edge/time is described
Returns
Whether the requested edge/time is described
Definition at line 61 of file MSEdgeWeightsStorage.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getValue(), and myEfforts.
Referenced by libsumo::Vehicle::getEffort(), MSNet::getEffort(), and GUILane::getLoadedEdgeWeight().
retrieveExistingTravelTime()
bool MSEdgeWeightsStorage::retrieveExistingTravelTime (const MSEdge *const e, const double t, double & value) const
Returns a travel time for an edge and time if stored.
Parameters
[in] e The edge for which the travel time shall be retrieved
[in] t The time for which the travel time shall be retrieved
[in] value The value if the requested edge/time is described
Returns
Whether the requested edge/time is described
Definition at line 46 of file MSEdgeWeightsStorage.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getValue(), and myTravelTimes.
Referenced by libsumo::Vehicle::getAdaptedTraveltime(), GUILane::getColorValue(), GUILane::getScaleValue(), GUILane::getStoredEdgeTravelTime(), and MSNet::getTravelTime().
Field Documentation
myEfforts
std::map<const MSEdge*, ValueTimeLine<double> > MSEdgeWeightsStorage::myEfforts private
A map of edge->time->effort.
Definition at line 127 of file MSEdgeWeightsStorage.h.
Referenced by addEffort(), knowsEffort(), removeEffort(), and retrieveExistingEffort().
myTravelTimes
std::map<const MSEdge*, ValueTimeLine<double> > MSEdgeWeightsStorage::myTravelTimes private
A map of edge->time->travel time.
Definition at line 124 of file MSEdgeWeightsStorage.h.
Referenced by addTravelTime(), knowsTravelTime(), removeTravelTime(), and retrieveExistingTravelTime().
The documentation for this class was generated from the following files:
MSEdgeWeightsStorage.h
MSEdgeWeightsStorage.cpp