SUMO - Simulation of Urban MObility: NBHeightMapper::Triangle Class Reference
NBHeightMapper::Triangle Class Reference
#include <NBHeightMapper.h>
Public Member Functions
void addSelf (const QueryResult &queryResult) const
callback for RTree search
bool contains (const Position &pos) const
checks whether pos lies within triangle (only checks x,y)
double getZ (const Position &geo) const
returns the projection of the give geoCoordinate (WGS84) onto triangle plane
Position normalVector () const
returns the normal vector for this triangles plane
Triangle (const PositionVector &corners)
~Triangle ()
Data Fields
PositionVector myCorners
the corners of the triangle
Detailed Description
Definition at line 96 of file NBHeightMapper.h.
Constructor & Destructor Documentation
Triangle()
NBHeightMapper::Triangle::Triangle (const PositionVector & corners)
Definition at line 350 of file NBHeightMapper.cpp.
References myCorners.
~Triangle()
NBHeightMapper::Triangle::~Triangle () inline
Definition at line 100 of file NBHeightMapper.h.
References addSelf(), contains(), getZ(), and normalVector().
Member Function Documentation
addSelf()
void NBHeightMapper::Triangle::addSelf (const QueryResult & queryResult) const
callback for RTree search
Definition at line 358 of file NBHeightMapper.cpp.
References NBHeightMapper::QueryResult::triangles.
Referenced by ~Triangle().
contains()
bool NBHeightMapper::Triangle::contains (const Position & pos) const
checks whether pos lies within triangle (only checks x,y)
Definition at line 364 of file NBHeightMapper.cpp.
References PositionVector::around(), and myCorners.
Referenced by NBHeightMapper::getZ(), and ~Triangle().
getZ()
double NBHeightMapper::Triangle::getZ (const Position & geo) const
returns the projection of the give geoCoordinate (WGS84) onto triangle plane
Definition at line 370 of file NBHeightMapper.cpp.
References Position::dotProduct(), myCorners, normalVector(), and Position::sub().
Referenced by NBHeightMapper::getZ(), and ~Triangle().
normalVector()
Position NBHeightMapper::Triangle::normalVector () const
returns the normal vector for this triangles plane
Definition at line 381 of file NBHeightMapper.cpp.
References Position::crossProduct(), and myCorners.
Referenced by getZ(), and ~Triangle().
Field Documentation
myCorners
PositionVector NBHeightMapper::Triangle::myCorners
the corners of the triangle
Definition at line 115 of file NBHeightMapper.h.
Referenced by contains(), getZ(), normalVector(), and Triangle().
The documentation for this class was generated from the following files:
NBHeightMapper.h
NBHeightMapper.cpp