SUMO - Simulation of Urban MObility: GUIVisualizationSettings.cpp File Reference
GUIVisualizationSettings.cpp File Reference
#include <config.h>
#include <map>
#include <vector>
#include "GUIVisualizationSettings.h"
#include "GUIPropertyScheme.h"
Variables
const RGBColor SUMO_color_ALLWAY_STOP (0, 0, 192)
const RGBColor SUMO_color_DEADEND (0, 0, 0)
const RGBColor SUMO_color_EQUAL (128, 128, 128)
const RGBColor SUMO_color_MAJOR (255, 255, 255)
const RGBColor SUMO_color_MINOR (51, 51, 51)
const RGBColor SUMO_color_STOP (128, 0, 128)
const RGBColor SUMO_color_TL_GREEN_MAJOR (0, 255, 0)
const RGBColor SUMO_color_TL_GREEN_MINOR (0, 179, 0)
const RGBColor SUMO_color_TL_OFF_BLINKING (128, 64, 0)
const RGBColor SUMO_color_TL_OFF_NOSIGNAL (0, 255, 255)
const RGBColor SUMO_color_TL_RED (255, 0, 0)
const RGBColor SUMO_color_TL_REDYELLOW (255, 128, 0)
const RGBColor SUMO_color_TL_YELLOW_MAJOR (255, 255, 0)
const RGBColor SUMO_color_TL_YELLOW_MINOR (255, 255, 0)
const RGBColor SUMO_color_ZIPPER (192, 128, 64)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Sept 2002
Version
$Id$
Definition in file GUIVisualizationSettings.cpp.
Variable Documentation
SUMO_color_ALLWAY_STOP
const RGBColor SUMO_color_ALLWAY_STOP(0, 0, 192)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_DEADEND
const RGBColor SUMO_color_DEADEND(0, 0, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_EQUAL
const RGBColor SUMO_color_EQUAL(128, 128, 128)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_MAJOR
const RGBColor SUMO_color_MAJOR(255, 255, 255)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_MINOR
const RGBColor SUMO_color_MINOR(51, 51, 51)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_STOP
const RGBColor SUMO_color_STOP(128, 0, 128)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_GREEN_MAJOR
const RGBColor SUMO_color_TL_GREEN_MAJOR(0, 255, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_GREEN_MINOR
const RGBColor SUMO_color_TL_GREEN_MINOR(0, 179, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_OFF_BLINKING
const RGBColor SUMO_color_TL_OFF_BLINKING(128, 64, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_OFF_NOSIGNAL
const RGBColor SUMO_color_TL_OFF_NOSIGNAL(0, 255, 255)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_RED
const RGBColor SUMO_color_TL_RED(255, 0, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_REDYELLOW
const RGBColor SUMO_color_TL_REDYELLOW(255, 128, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_YELLOW_MAJOR
const RGBColor SUMO_color_TL_YELLOW_MAJOR(255, 255, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_TL_YELLOW_MINOR
const RGBColor SUMO_color_TL_YELLOW_MINOR(255, 255, 0)
Referenced by GUIVisualizationSettings::getLinkColor().
SUMO_color_ZIPPER
const RGBColor SUMO_color_ZIPPER(192, 128, 64)
Referenced by GUIVisualizationSettings::getLinkColor().