SUMO - Simulation of Urban MObility: GeoConvHelper Class Reference
GeoConvHelper Class Reference
static methods for processing the coordinates conversion for the current net
#include <GeoConvHelper.h>
Public Member Functions
void cartesian2geo (Position &cartesian) const
Converts the given cartesian (shifted) position to its geo (lat/long) representation.
GeoConvHelper (OptionsCont &oc)
Constructor based on the stored options.
GeoConvHelper (const std::string &proj, const Position &offset, const Boundary &orig, const Boundary &conv, double scale=1.0, bool inverse=false)
Constructor.
const Boundary & getConvBoundary () const
Returns the converted boundary.
const Position getOffset () const
Returns the network offset.
const Position getOffsetBase () const
Returns the network base.
const Boundary & getOrigBoundary () const
Returns the original boundary.
const std::string & getProjString () const
Returns the network offset.
void moveConvertedBy (double x, double y)
Shifts the converted boundary by the given amounts.
void setConvBoundary (const Boundary &boundary)
sets the converted boundary
bool usingGeoProjection () const
Returns whether a transformation from geo to metric coordinates will be performed.
bool usingInverseGeoProjection () const
Returns the information whether an inverse transformation will happen.
bool x2cartesian (Position &from, bool includeInBoundary=true)
Converts the given coordinate into a cartesian and optionally update myConvBoundary.
bool x2cartesian_const (Position &from) const
Converts the given coordinate into a cartesian using the previous initialisation.
~GeoConvHelper ()
Destructor.
Static Public Member Functions
static void addProjectionOptions (OptionsCont &oc)
Adds projection options to the given container.
static void computeFinal (bool lefthand=false)
compute the location attributes which will be used for output based on the loaded location data, the given options and the transformations applied during processing
static const GeoConvHelper & getFinal ()
the coordinate transformation for writing the location element and for tracking the original coordinate system
static GeoConvHelper & getLoaded ()
the coordinate transformation that was loaded fron an input file
static GeoConvHelper & getProcessing ()
the coordinate transformation to use for input conversion and processing
static bool init (OptionsCont &oc)
Initialises the processing and the final instance using the given options.
static void init (const std::string &proj, const Position &offset, const Boundary &orig, const Boundary &conv, double scale=1.0)
Initialises the processing and the final instance using the given proj.4-definition and complete network parameter.
static void resetLoaded ()
resets loaded location elements
static void setLoaded (const GeoConvHelper &loaded)
sets the coordinate transformation loaded from a location element
static void writeLocation (OutputDevice &into)
writes the location element
Private Types
enum ProjectionMethod {
NONE, SIMPLE, UTM, DHDN,
DHDN_UTM, PROJ
}
projection method
Private Member Functions
GeoConvHelper (const GeoConvHelper &)=delete
invalidated copy constructor.
GeoConvHelper & operator= (const GeoConvHelper &)
make assignment operator private
Private Attributes
Boundary myConvBoundary
The boundary after conversion (x2cartesian)
double myGeoScale
The scaling to apply to geo-coordinates.
Position myOffset
The offset to apply.
Boundary myOrigBoundary
The boundary before conversion (x2cartesian)
ProjectionMethod myProjectionMethod
Information whether no projection shall be done.
std::string myProjString
A proj options string describing the proj.4-projection to use.
bool myUseInverseProjection
Information whether inverse projection shall be used.
Static Private Attributes
static GeoConvHelper myFinal
coordinate transformation to use for writing the location element and for tracking the original coordinate system
static GeoConvHelper myLoaded
coordinate transformation loaded from a location element
static int myNumLoaded = 0
the numer of coordinate transformations loaded from location elements
static GeoConvHelper myProcessing
coordinate transformation to use for input conversion and processing
Detailed Description
static methods for processing the coordinates conversion for the current net
Definition at line 59 of file GeoConvHelper.h.
Member Enumeration Documentation
ProjectionMethod
enum GeoConvHelper::ProjectionMethod private
projection method
Enumerator
NONE
SIMPLE
UTM
DHDN
DHDN_UTM
PROJ
Definition at line 160 of file GeoConvHelper.h.
Constructor & Destructor Documentation
GeoConvHelper() [1/3]
GeoConvHelper::GeoConvHelper (OptionsCont & oc)
Constructor based on the stored options.
Parameters
[in] oc The OptionsCont from which to read options
Referenced by computeFinal(), and init().
GeoConvHelper() [2/3]
GeoConvHelper::GeoConvHelper (const std::string & proj, const Position & offset, const Boundary & orig, const Boundary & conv, double scale = 1.0, bool inverse = false)
Constructor.
Definition at line 57 of file GeoConvHelper.cpp.
References DHDN, DHDN_UTM, myProjectionMethod, NONE, PROJ, SIMPLE, and UTM.
~GeoConvHelper()
GeoConvHelper::~GeoConvHelper ()
Destructor.
Definition at line 94 of file GeoConvHelper.cpp.
GeoConvHelper() [3/3]
GeoConvHelper::GeoConvHelper (const GeoConvHelper &) private delete
invalidated copy constructor.
Member Function Documentation
addProjectionOptions()
void GeoConvHelper::addProjectionOptions (OptionsCont & oc) static
Adds projection options to the given container.
Parameters
[in] oc The options container to add the options to
Todo:
let the container be retrieved
Definition at line 192 of file GeoConvHelper.cpp.
References OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), OptionsCont::addSynonyme(), and OptionsCont::doRegister().
Referenced by fillOptions(), and GNELoadThread::fillOptions().
cartesian2geo()
void GeoConvHelper::cartesian2geo (Position & cartesian) const
Converts the given cartesian (shifted) position to its geo (lat/long) representation.
Definition at line 234 of file GeoConvHelper.cpp.
References DEG2RAD, getOffsetBase(), myProjectionMethod, NONE, Position::set(), SIMPLE, Position::sub(), Position::x(), and Position::y().
Referenced by TraCIServerAPI_Simulation::commandPositionConversion(), MSVTypeProbe::execute(), getFinal(), GNEPOI::GNEPOI(), GNEPoly::GNEPoly(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PCPolyContainer::saveDlrTDP(), GNEPOI::setAttribute(), GNEPoly::setAttribute(), MSDevice_SSM::toGeo(), NBNetBuilder::transformCoordinate(), GUISUMOAbstractView::updatePositionInformation(), MSFCDExport::write(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), and x2cartesian_const().
computeFinal()
void GeoConvHelper::computeFinal (bool lefthand = false) static
compute the location attributes which will be used for output based on the loaded location data, the given options and the transformations applied during processing
Definition at line 409 of file GeoConvHelper.cpp.
References Boundary::flipY(), GeoConvHelper(), getConvBoundary(), getOffset(), getOrigBoundary(), getProjString(), Position::mul(), myConvBoundary, myFinal, myLoaded, myNumLoaded, myOffset, myProcessing, and usingGeoProjection().
Referenced by NBNetBuilder::compute(), getLoaded(), main(), and GNELoadThread::run().
getConvBoundary()
const Boundary & GeoConvHelper::getConvBoundary () const
Returns the converted boundary.
Definition at line 385 of file GeoConvHelper.cpp.
References myConvBoundary.
Referenced by NBNetBuilder::compute(), computeFinal(), getFinal(), libsumo::Simulation::getNetBoundary(), main(), NBNetBuilder::moveToOrigin(), writeLocation(), NWWriter_OpenDrive::writeNetwork(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
getFinal()
static const GeoConvHelper& GeoConvHelper::getFinal () inline static
the coordinate transformation for writing the location element and for tracking the original coordinate system
Definition at line 105 of file GeoConvHelper.h.
References cartesian2geo(), getConvBoundary(), getOrigBoundary(), moveConvertedBy(), myFinal, resetLoaded(), setLoaded(), usingGeoProjection(), usingInverseGeoProjection(), x2cartesian(), and x2cartesian_const().
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), GUIGlObject::buildPositionCopyEntry(), TraCIServerAPI_Simulation::commandPositionConversion(), GNENet::computeAndUpdate(), MSVTypeProbe::execute(), libsumo::Simulation::getNetBoundary(), GNEPOI::GNEPOI(), GNEPoly::GNEPoly(), main(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), GNEPOI::setAttribute(), GNEPoly::setAttribute(), NLHandler::setLocation(), MSDevice_SSM::toGeo(), GUISUMOAbstractView::updatePositionInformation(), MSFCDExport::write(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
getLoaded()
static GeoConvHelper& GeoConvHelper::getLoaded () inline static
the coordinate transformation that was loaded fron an input file
Definition at line 95 of file GeoConvHelper.h.
References computeFinal(), and myLoaded.
Referenced by NBEdgeCont::ignoreFilterMatch().
getOffset()
const Position GeoConvHelper::getOffset () const
Returns the network offset.
Definition at line 391 of file GeoConvHelper.cpp.
References myOffset.
Referenced by computeFinal(), and setConvBoundary().
getOffsetBase()
const Position GeoConvHelper::getOffsetBase () const
Returns the network base.
Definition at line 397 of file GeoConvHelper.cpp.
References myOffset.
Referenced by cartesian2geo(), NBNetBuilder::compute(), setConvBoundary(), and writeLocation().
getOrigBoundary()
const Boundary & GeoConvHelper::getOrigBoundary () const
Returns the original boundary.
Definition at line 379 of file GeoConvHelper.cpp.
References myOrigBoundary.
Referenced by NBNetBuilder::compute(), computeFinal(), getFinal(), and writeLocation().
getProcessing()
static GeoConvHelper& GeoConvHelper::getProcessing () inline static
the coordinate transformation to use for input conversion and processing
Note
instance is modified during use: boundary may adapt to new coordinates
Definition at line 90 of file GeoConvHelper.h.
References myProcessing.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), NGNode::buildNBNode(), GUISUMOAbstractView::checkGDALImage(), NBNetBuilder::compute(), NBEdgeCont::ignoreFilterMatch(), NILoader::load(), PCLoaderVisum::load(), PCLoaderArcView::load(), PCLoaderOSM::loadIfSet(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), and NBNetBuilder::transformCoordinate().
getProjString()
const std::string & GeoConvHelper::getProjString () const
Returns the network offset.
Definition at line 403 of file GeoConvHelper.cpp.
References myProjString.
Referenced by computeFinal(), setConvBoundary(), and writeLocation().
init() [1/2]
bool GeoConvHelper::init (OptionsCont & oc) static
Initialises the processing and the final instance using the given options.
Definition at line 146 of file GeoConvHelper.cpp.
References OptionsCont::exists(), GeoConvHelper(), OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getString(), OptionsCont::isDefault(), myFinal, myProcessing, and WRITE_ERROR.
Referenced by main(), PCNetProjectionLoader::myStartElement(), GNELoadThread::run(), and NLHandler::setLocation().
init() [2/2]
void GeoConvHelper::init (const std::string & proj, const Position & offset, const Boundary & orig, const Boundary & conv, double scale = 1.0) static
Initialises the processing and the final instance using the given proj.4-definition and complete network parameter.
Definition at line 184 of file GeoConvHelper.cpp.
References GeoConvHelper(), myFinal, and myProcessing.
moveConvertedBy()
void GeoConvHelper::moveConvertedBy (double x, double y)
Shifts the converted boundary by the given amounts.
Definition at line 372 of file GeoConvHelper.cpp.
References Position::add(), Boundary::moveby(), myConvBoundary, and myOffset.
Referenced by getFinal(), and NBNetBuilder::moveToOrigin().
operator=()
GeoConvHelper & GeoConvHelper::operator= (const GeoConvHelper & orig) private
make assignment operator private
Definition at line 110 of file GeoConvHelper.cpp.
References myConvBoundary, myGeoScale, myOffset, myOrigBoundary, myProjectionMethod, myProjString, and myUseInverseProjection.
resetLoaded()
void GeoConvHelper::resetLoaded () static
resets loaded location elements
Definition at line 446 of file GeoConvHelper.cpp.
References myNumLoaded.
Referenced by GNEApplicationWindow::closeAllWindows(), and getFinal().
setConvBoundary()
void GeoConvHelper::setConvBoundary (const Boundary & boundary) inline
sets the converted boundary
Definition at line 142 of file GeoConvHelper.h.
References getOffset(), getOffsetBase(), getProjString(), myConvBoundary, and writeLocation().
Referenced by NBNetBuilder::compute().
setLoaded()
void GeoConvHelper::setLoaded (const GeoConvHelper & loaded) static
sets the coordinate transformation loaded from a location element
Definition at line 435 of file GeoConvHelper.cpp.
References myLoaded, myNumLoaded, toString(), and WRITE_WARNING.
Referenced by getFinal(), and NIImporter_SUMO::loadLocation().
usingGeoProjection()
bool GeoConvHelper::usingGeoProjection () const
Returns whether a transformation from geo to metric coordinates will be performed.
Definition at line 222 of file GeoConvHelper.cpp.
References myProjectionMethod, and NONE.
Referenced by ShapeHandler::addPOI(), computeFinal(), MSVTypeProbe::execute(), getFinal(), NBEdgeCont::ignoreFilterMatch(), PCPolyContainer::save(), PCPolyContainer::saveDlrTDP(), NBNetBuilder::transformCoordinate(), writeLocation(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
usingInverseGeoProjection()
bool GeoConvHelper::usingInverseGeoProjection () const
Returns the information whether an inverse transformation will happen.
Definition at line 228 of file GeoConvHelper.cpp.
References myUseInverseProjection.
Referenced by getFinal(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_XML::writeNodes().
writeLocation()
void GeoConvHelper::writeLocation (OutputDevice & into) static
writes the location element
Definition at line 452 of file GeoConvHelper.cpp.
References OutputDevice::closeTag(), getConvBoundary(), getOffsetBase(), getOrigBoundary(), getProjString(), gPrecisionGeo, OutputDevice::lf(), myFinal, OutputDevice::openTag(), OutputDevice::setPrecision(), SUMO_ATTR_CONV_BOUNDARY, SUMO_ATTR_NET_OFFSET, SUMO_ATTR_ORIG_BOUNDARY, SUMO_ATTR_ORIG_PROJ, SUMO_TAG_LOCATION, usingGeoProjection(), and OutputDevice::writeAttr().
Referenced by PCPolyContainer::save(), setConvBoundary(), NWWriter_SUMO::writeNetwork(), and NWWriter_XML::writeNodes().
x2cartesian()
bool GeoConvHelper::x2cartesian (Position & from, bool includeInBoundary = true)
Converts the given coordinate into a cartesian and optionally update myConvBoundary.
Note
: initializes UTM / DHDN projection on first use (select zone)
Definition at line 259 of file GeoConvHelper.cpp.
References Boundary::add(), DHDN, DHDN_UTM, myConvBoundary, myGeoScale, myOrigBoundary, myProjectionMethod, myProjString, Position::set(), toString(), UTM, WRITE_WARNING, Position::x(), x2cartesian_const(), and Position::y().
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), NGNode::buildNBNode(), GUISUMOAbstractView::checkGDALImage(), getFinal(), PCLoaderVisum::load(), PCLoaderArcView::load(), and NBNetBuilder::transformCoordinate().
x2cartesian_const()
bool GeoConvHelper::x2cartesian_const (Position & from) const
Converts the given coordinate into a cartesian using the previous initialisation.
!! recheck whether the axes are mirrored
Definition at line 328 of file GeoConvHelper.cpp.
References Position::add(), cartesian2geo(), DEG2RAD, myGeoScale, myOffset, myProjectionMethod, myUseInverseProjection, NONE, Position::set(), SIMPLE, toString(), WRITE_WARNING, Position::x(), and Position::y().
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), TraCIServerAPI_Simulation::commandPositionConversion(), getFinal(), NBEdgeCont::ignoreFilterMatch(), GNEPOI::setAttribute(), GNEPoly::setAttribute(), and x2cartesian().
Field Documentation
myConvBoundary
Boundary GeoConvHelper::myConvBoundary private
The boundary after conversion (x2cartesian)
Definition at line 199 of file GeoConvHelper.h.
Referenced by computeFinal(), getConvBoundary(), moveConvertedBy(), operator=(), setConvBoundary(), and x2cartesian().
myFinal
GeoConvHelper GeoConvHelper::myFinal static private
coordinate transformation to use for writing the location element and for tracking the original coordinate system
Definition at line 208 of file GeoConvHelper.h.
Referenced by computeFinal(), getFinal(), init(), and writeLocation().
myGeoScale
double GeoConvHelper::myGeoScale private
The scaling to apply to geo-coordinates.
Definition at line 187 of file GeoConvHelper.h.
Referenced by operator=(), x2cartesian(), and x2cartesian_const().
myLoaded
GeoConvHelper GeoConvHelper::myLoaded static private
coordinate transformation loaded from a location element
Definition at line 205 of file GeoConvHelper.h.
Referenced by computeFinal(), getLoaded(), and setLoaded().
myNumLoaded
int GeoConvHelper::myNumLoaded = 0 static private
the numer of coordinate transformations loaded from location elements
Definition at line 211 of file GeoConvHelper.h.
Referenced by computeFinal(), resetLoaded(), and setLoaded().
myOffset
Position GeoConvHelper::myOffset private
The offset to apply.
Definition at line 184 of file GeoConvHelper.h.
Referenced by computeFinal(), getOffset(), getOffsetBase(), moveConvertedBy(), operator=(), and x2cartesian_const().
myOrigBoundary
Boundary GeoConvHelper::myOrigBoundary private
The boundary before conversion (x2cartesian)
Definition at line 196 of file GeoConvHelper.h.
Referenced by getOrigBoundary(), operator=(), and x2cartesian().
myProcessing
GeoConvHelper GeoConvHelper::myProcessing static private
coordinate transformation to use for input conversion and processing
Definition at line 202 of file GeoConvHelper.h.
Referenced by computeFinal(), getProcessing(), and init().
myProjectionMethod
ProjectionMethod GeoConvHelper::myProjectionMethod private
Information whether no projection shall be done.
Definition at line 190 of file GeoConvHelper.h.
Referenced by cartesian2geo(), GeoConvHelper(), operator=(), usingGeoProjection(), x2cartesian(), and x2cartesian_const().
myProjString
std::string GeoConvHelper::myProjString private
A proj options string describing the proj.4-projection to use.
Definition at line 170 of file GeoConvHelper.h.
Referenced by getProjString(), operator=(), and x2cartesian().
myUseInverseProjection
bool GeoConvHelper::myUseInverseProjection private
Information whether inverse projection shall be used.
Definition at line 193 of file GeoConvHelper.h.
Referenced by operator=(), usingInverseGeoProjection(), and x2cartesian_const().
The documentation for this class was generated from the following files:
GeoConvHelper.h
GeoConvHelper.cpp