SUMO - Simulation of Urban MObility: MSSOTLE2Sensors.cpp File Reference
MSSOTLE2Sensors.cpp File Reference
#include <utils/common/TplConvert.h>
#include <microsim/output/MSDetectorControl.h>
#include <microsim/MSEdge.h>
#include <microsim/MSVehicleType.h>
#include "MSSOTLE2Sensors.h"
Macros
#define INVALID_POSITION std::numeric_limits<double>::max()
Functions
std::vector< std::string > & split (const std::string &s, char delim, std::vector< std::string > &elems)
std::string trim (std::string &str)
Detailed Description
Author
Gianfilippo Slager
Alessio Bonfietti
Federico Caselli
Date
2010-02-25
Version
$Id$
Definition in file MSSOTLE2Sensors.cpp.
Macro Definition Documentation
INVALID_POSITION
#define INVALID_POSITION std::numeric_limits<double>::max()
Definition at line 28 of file MSSOTLE2Sensors.cpp.
Referenced by MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), MSSOTLE2Sensors::buildSensorForLane(), and MSSOTLE2Sensors::buildSensorForOutLane().
Function Documentation
split()
std::vector<std::string>& split (const std::string & s, char delim, std::vector< std::string > & elems)
Definition at line 491 of file MSSOTLE2Sensors.cpp.
Referenced by NBEdge::buildInnerEdges(), ROEdge::getTravelTime(), MSSOTLE2Sensors::setVehicleWeigths(), and IntermodalRouter< E, L, N, V >::splitEdge().
trim()
std::string trim (std::string & str)
Definition at line 485 of file MSSOTLE2Sensors.cpp.
Referenced by MSSOTLE2Sensors::setVehicleWeigths().