SUMO - Simulation of Urban MObility: SystemFrame Class Reference
SystemFrame Class Reference
A set of actions common to all applications.
#include <SystemFrame.h>
Static Public Member Functions
static void addConfigurationOptions (OptionsCont &oc)
Adds configuration options to the given container.
static void addReportOptions (OptionsCont &oc)
Adds reporting options to the given container.
static bool checkOptions ()
checks shared options and sets StdDefs
static void close ()
Closes all of an applications subsystems.
Detailed Description
A set of actions common to all applications.
As almost all applications within the SUMO-package share the same initialisation procedure, it is encapsulated within this class.
Only two things are done herein, so far. The first is to insert options into the given options container that are used for dealing with the application's configuration.
Additionally, a closing method may be found, which closes all used subsystems.
Definition at line 57 of file SystemFrame.h.
Member Function Documentation
addConfigurationOptions()
void SystemFrame::addConfigurationOptions (OptionsCont & oc) static
Adds configuration options to the given container.
Parameters
[in] oc The options container to add the options to
Todo:
let the container be retrieved
Definition at line 46 of file SystemFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), OptionsCont::addSynonyme(), OptionsCont::addXMLDefault(), and OptionsCont::doRegister().
Referenced by RODFFrame::fillOptions(), AGFrame::fillOptions(), ROJTRFrame::fillOptions(), RODUAFrame::fillOptions(), ROMAFrame::fillOptions(), fillOptions(), MSFrame::fillOptions(), GNELoadThread::fillOptions(), and main().
addReportOptions()
void SystemFrame::addReportOptions (OptionsCont & oc) static
Adds reporting options to the given container.
Parameters
[in] oc The options container to add the options to
Todo:
let the container be retrieved
Definition at line 71 of file SystemFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), OptionsCont::addSynonyme(), and OptionsCont::doRegister().
Referenced by RODFFrame::fillOptions(), AGFrame::fillOptions(), ROJTRFrame::fillOptions(), RODUAFrame::fillOptions(), ROMAFrame::fillOptions(), fillOptions(), MSFrame::fillOptions(), GNELoadThread::fillOptions(), and main().
checkOptions()
bool SystemFrame::checkOptions () static
checks shared options and sets StdDefs
Definition at line 118 of file SystemFrame.cpp.
References OptionsCont::getInt(), OptionsCont::getOptions(), gPrecision, and gPrecisionGeo.
Referenced by MSFrame::checkOptions(), checkOptions(), main(), GNEApplicationWindow::onCmdOptions(), and GNELoadThread::run().
close()
void SystemFrame::close () static
Closes all of an applications subsystems.
Closes (in this order)
The xml subsystem
The options subsystem
The message subsystem
See also
XMLSubSys::close()
OptionsCont::clear()
MsgHandler::cleanupOnEnd()
Definition at line 127 of file SystemFrame.cpp.
References MsgHandler::cleanupOnEnd(), OptionsCont::clear(), XMLSubSys::close(), OutputDevice::closeAll(), and OptionsCont::getOptions().
Referenced by NLBuilder::init(), and main().
The documentation for this class was generated from the following files:
SystemFrame.h
SystemFrame.cpp