SUMO - Simulation of Urban MObility: NIVissimNodeDef Class Reference
NIVissimNodeDef Class Reference abstract
#include <NIVissimNodeDef.h>
Public Member Functions
int buildNodeCluster ()
virtual double getEdgePosition (int edgeid) const =0
NIVissimNodeDef (int id, const std::string &name)
virtual ~NIVissimNodeDef ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int id, NIVissimNodeDef *o)
static NIVissimNodeDef * dictionary (int id)
static int dictSize ()
static int getMaxID ()
Protected Attributes
int myID
std::string myName
Private Types
typedef std::map< int, NIVissimNodeDef * > DictType
Static Private Attributes
static DictType myDict
static int myMaxID = 0
Detailed Description
Definition at line 40 of file NIVissimNodeDef.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimNodeDef*> NIVissimNodeDef::DictType private
Definition at line 64 of file NIVissimNodeDef.h.
Constructor & Destructor Documentation
NIVissimNodeDef()
NIVissimNodeDef::NIVissimNodeDef (int id, const std::string & name)
Definition at line 50 of file NIVissimNodeDef.cpp.
~NIVissimNodeDef()
NIVissimNodeDef::~NIVissimNodeDef () virtual
Definition at line 54 of file NIVissimNodeDef.cpp.
Member Function Documentation
buildNodeCluster()
int NIVissimNodeDef::buildNodeCluster ()
clearDict()
void NIVissimNodeDef::clearDict () static
Definition at line 132 of file NIVissimNodeDef.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/2]
bool NIVissimNodeDef::dictionary (int id, NIVissimNodeDef * o) static
Definition at line 58 of file NIVissimNodeDef.cpp.
References myDict, and myMaxID.
Referenced by NIVissimNodeDef_Edges::dictionary(), NIVissimNodeDef_Poly::dictionary(), and NIVissimConnectionCluster::getPositionForEdge().
dictionary() [2/2]
NIVissimNodeDef * NIVissimNodeDef::dictionary (int id) static
Definition at line 73 of file NIVissimNodeDef.cpp.
References myDict.
dictSize()
int NIVissimNodeDef::dictSize () static
Definition at line 125 of file NIVissimNodeDef.cpp.
References myDict.
getEdgePosition()
virtual double NIVissimNodeDef::getEdgePosition (int edgeid) const pure virtual
Implemented in NIVissimNodeDef_Edges.
Referenced by NIVissimConnectionCluster::getPositionForEdge().
getMaxID()
int NIVissimNodeDef::getMaxID () static
Definition at line 141 of file NIVissimNodeDef.cpp.
References myMaxID.
Referenced by NIImporter_Vissim::postLoadBuild().
Field Documentation
myDict
NIVissimNodeDef::DictType NIVissimNodeDef::myDict static private
Definition at line 65 of file NIVissimNodeDef.h.
Referenced by clearDict(), dictionary(), and dictSize().
myID
int NIVissimNodeDef::myID protected
Definition at line 60 of file NIVissimNodeDef.h.
myMaxID
int NIVissimNodeDef::myMaxID = 0 static private
Definition at line 66 of file NIVissimNodeDef.h.
Referenced by dictionary(), and getMaxID().
myName
std::string NIVissimNodeDef::myName protected
Definition at line 61 of file NIVissimNodeDef.h.
The documentation for this class was generated from the following files:
NIVissimNodeDef.h
NIVissimNodeDef.cpp