SUMO - Simulation of Urban MObility: MSCFModel Class Reference
MSCFModel Class Reference abstract
The car-following model abstraction.
#include <MSCFModel.h>
Data Structures
class VehicleVariables
Public Member Functions
double estimateSpeedAfterDistance (const double dist, const double v, const double accel) const
double getApparentDecel () const
Get the vehicle type's apparent deceleration [m/s^2] (the one regarded by its followers.
double getEmergencyDecel () const
Get the vehicle type's maximal phisically possible deceleration [m/s^2].
double getMaxAccel () const
Get the vehicle type's maximum acceleration [m/s^2].
double getMaxDecel () const
Get the vehicle type's maximal comfortable deceleration [m/s^2].
double getMinimalArrivalSpeed (double dist, double currentSpeed) const
Computes the minimal possible arrival speed after covering a given distance.
double getMinimalArrivalSpeedEuler (double dist, double currentSpeed) const
Computes the minimal possible arrival speed after covering a given distance for Euler update.
SUMOTime getMinimalArrivalTime (double dist, double currentSpeed, double arrivalSpeed) const
Computes the minimal time needed to cover a distance given the desired speed at arrival.
double maximumSafeFollowSpeed (double gap, double egoSpeed, double predSpeed, double predMaxDecel, bool onInsertion=false) const
Returns the maximum safe velocity for following the given leader.
double maximumSafeStopSpeed (double gap, double currentSpeed, bool onInsertion=false, double headway=-1) const
Returns the maximum next velocity for stopping within gap.
double maximumSafeStopSpeedBallistic (double gap, double currentSpeed, bool onInsertion=false, double headway=-1) const
Returns the maximum next velocity for stopping within gap when using the ballistic positional update.
double maximumSafeStopSpeedEuler (double gap) const
Returns the maximum next velocity for stopping within gap when using the semi-implicit Euler update.
MSCFModel (const MSVehicleType *vtype, double accel, double decel, double emergencyDecel, double apparentDecel, double headwayTime)
Constructor.
virtual ~MSCFModel ()
Destructor.
Methods to override by model implementation
virtual double moveHelper (MSVehicle *const veh, double vPos) const
Applies interaction with stops and lane changing model influences.
virtual double freeSpeed (const MSVehicle *const veh, double speed, double seen, double maxSpeed, const bool onInsertion=false) const
Computes the vehicle's safe speed without a leader.
virtual double followSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const =0
Computes the vehicle's follow speed (no dawdling)
virtual double insertionFollowSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const
Computes the vehicle's safe speed (no dawdling) This method is used during the insertion stage. Whereas the method followSpeed returns the desired speed which may be lower than the safe speed, this method only considers safety constraints.
virtual double stopSpeed (const MSVehicle *const veh, const double speed, double gap) const =0
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling)
virtual double insertionStopSpeed (const MSVehicle *const veh, double speed, double gap) const
Computes the vehicle's safe speed for approaching an obstacle at insertion without constraints due to acceleration capabilities and previous speeds.
virtual double followSpeedTransient (double duration, const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const
Computes the vehicle's follow speed that avoids a collision for the given amount of time.
virtual double interactionGap (const MSVehicle *const veh, double vL) const
Returns the maximum gap at which an interaction between both vehicles occurs.
virtual int getModelID () const =0
Returns the model's ID; the XML-Tag number is used.
virtual MSCFModel * duplicate (const MSVehicleType *vtype) const =0
Duplicates the car-following model.
virtual VehicleVariables * createVehicleVariables () const
Returns model specific values which are stored inside a vehicle and must be used with casting.
Virtual methods with default implementation
virtual double getImperfection () const
Get the driver's imperfection.
virtual double getHeadwayTime () const
Get the driver's desired headway [s].
Setter methods
virtual void setMaxAccel (double accel)
Sets a new value for maximum acceleration [m/s^2].
virtual void setMaxDecel (double decel)
Sets a new value for maximal comfortable deceleration [m/s^2].
virtual void setEmergencyDecel (double decel)
Sets a new value for maximal physically possible deceleration [m/s^2].
virtual void setApparentDecel (double decel)
Sets a new value for the apparent deceleration [m/s^2].
virtual void setImperfection (double imperfection)
Sets a new value for driver imperfection.
virtual void setHeadwayTime (double headwayTime)
Sets a new value for desired headway [s].
Static Public Member Functions
static double avoidArrivalAccel (double dist, double time, double speed)
Computes the acceleration needed to arrive not before the given time.
static double distAfterTime (double t, double speed, double accel)
calculates the distance travelled after accelerating for time t
static double estimateArrivalTime (double dist, double speed, double maxSpeed, double accel)
Computes the time needed to travel a distance dist given an initial speed and constant acceleration. The speed during traveling is assumed not to exceed the max speed.
static double estimateArrivalTime (double dist, double initialSpeed, double arrivalSpeed, double maxSpeed, double accel, double decel)
Computes the time needed to travel a distance dist given an initial speed, arrival speed, constant acceleration and deceleration. The speed during traveling is assumed not to exceed the max speed.
static double gapExtrapolation (const double duration, const double currentGap, double v1, double v2, double a1=0, double a2=0, const double maxV1=std::numeric_limits< double >::max(), const double maxV2=std::numeric_limits< double >::max())
return the resulting gap if, starting with gap currentGap, two vehicles continue with constant accelerations (velocities bounded by 0 and maxSpeed) for a given timespan of length 'duration'.
static double passingTime (const double lastPos, const double passedPos, const double currentPos, const double lastSpeed, const double currentSpeed)
Calculates the time at which the position passedPosition has been passed In case of a ballistic update, the possibility of a stop within a time step requires more information about the last time-step than in case of the euler update to determine the last position if the currentSpeed is zero.
static double speedAfterTime (const double t, const double oldSpeed, const double dist)
Calculates the speed after a time t [0,TS] given the initial speed and the distance traveled in an interval of step length TS.
Protected Attributes
double myAccel
The vehicle's maximum acceleration [m/s^2].
double myApparentDecel
The vehicle's deceleration as expected by surrounding traffic [m/s^2].
double myDecel
The vehicle's maximum deceleration [m/s^2].
double myEmergencyDecel
The vehicle's maximum emergency deceleration [m/s^2].
double myHeadwayTime
The driver's desired time headway (aka reaction time tau) [s].
const MSVehicleType * myType
The type to which this model definition belongs to.
Currently fixed methods
virtual double maxNextSpeed (double speed, const MSVehicle *const veh) const
Returns the maximum speed given the current speed.
virtual double minNextSpeed (double speed, const MSVehicle *const veh=0) const
Returns the minimum speed given the current speed (depends on the numerical update scheme and its step width) Note that it wouldn't have to depend on the numerical update scheme if the semantics would rely on acceleration instead of velocity.
double brakeGap (const double speed) const
Returns the distance the vehicle needs to halt including driver's reaction time tau (i.e. desired headway), assuming that during the reaction time, the speed remains constant.
double getSecureGap (const double speed, const double leaderSpeed, const double leaderMaxDecel) const
Returns the minimum gap to reserve if the leader is braking at maximum (>=0)
virtual double getSpeedAfterMaxDecel (double v) const
Returns the velocity after maximum deceleration.
static double brakeGap (const double speed, const double decel, const double headwayTime)
static double brakeGapEuler (const double speed, const double decel, const double headwayTime)
static double freeSpeed (const double currentSpeed, const double decel, const double dist, const double maxSpeed, const bool onInsertion, const double actionStepLength)
Detailed Description
The car-following model abstraction.
MSCFModel is an interface for different car following Models to implement. It provides methods to compute a vehicles velocity for a simulation step.
Definition at line 59 of file MSCFModel.h.
Constructor & Destructor Documentation
MSCFModel()
MSCFModel::MSCFModel (const MSVehicleType * vtype, double accel, double decel, double emergencyDecel, double apparentDecel, double headwayTime)
Constructor.
Parameters
[in] rvtype a reference to the corresponding vtype
Definition at line 47 of file MSCFModel.cpp.
~MSCFModel()
MSCFModel::~MSCFModel () virtual
Destructor.
Definition at line 58 of file MSCFModel.cpp.
Member Function Documentation
avoidArrivalAccel()
double MSCFModel::avoidArrivalAccel (double dist, double time, double speed) static
Computes the acceleration needed to arrive not before the given time.
Parameters
[in] dist - the distance of the critical point
[in] time - the time after which an arrival at dist is allowed
[in] speed - the current speed
Returns
Returns the acceleration which would ensure an arrival at distance dist earliest for the given time
Definition at line 415 of file MSCFModel.cpp.
Referenced by MSLCM_SL2015::commitManoeuvre(), and getSpeedAfterMaxDecel().
brakeGap() [1/2]
double MSCFModel::brakeGap (const double speed) const inline
Returns the distance the vehicle needs to halt including driver's reaction time tau (i.e. desired headway), assuming that during the reaction time, the speed remains constant.
Parameters
[in] speed The vehicle's current speed
Returns
The distance needed to halt
Definition at line 289 of file MSCFModel.h.
References brakeGapEuler(), freeSpeed(), myDecel, and myHeadwayTime.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSPModel_Striping::addCrossingVehs(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSVehicle::checkRewindLinkLanes(), distAfterTime(), followSpeedTransient(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLaneChanger::getRealLeader(), MSVehicle::getRerouteOrigin(), getSecureGap(), MSLane::handleCollisionBetween(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), maximumSafeFollowSpeed(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), and MSVehicle::unsafeLinkAhead().
brakeGap() [2/2]
double MSCFModel::brakeGap (const double speed, const double decel, const double headwayTime) static
Definition at line 65 of file MSCFModel.cpp.
References brakeGapEuler(), and MSGlobals::gSemiImplicitEulerUpdate.
brakeGapEuler()
double MSCFModel::brakeGapEuler (const double speed, const double decel, const double headwayTime) static
Definition at line 80 of file MSCFModel.cpp.
References ACCEL2SPEED, and SPEED2DIST.
Referenced by brakeGap(), and MSLCM_SL2015::computeSpeedLat().
createVehicleVariables()
virtual VehicleVariables* MSCFModel::createVehicleVariables () const inline virtual
Returns model specific values which are stored inside a vehicle and must be used with casting.
Reimplemented in MSCFModel_SmartSK, MSCFModel_IDM, MSCFModel_Wiedemann, MSCFModel_PWag2009, MSCFModel_Kerner, and MSCFModel_Rail.
Definition at line 194 of file MSCFModel.h.
Referenced by MSVehicle::MSVehicle().
distAfterTime()
double MSCFModel::distAfterTime (double t, double speed, double accel) static
calculates the distance travelled after accelerating for time t
Definition at line 306 of file MSCFModel.cpp.
References ACCEL2SPEED, brakeGap(), MSGlobals::gSemiImplicitEulerUpdate, MAX2(), SPEED2DIST, and TS.
Referenced by followSpeedTransient(), and getSpeedAfterMaxDecel().
duplicate()
virtual MSCFModel* MSCFModel::duplicate (const MSVehicleType * vtype) const pure virtual
Duplicates the car-following model.
Parameters
[in] vtype The vehicle type this model belongs to (1:1)
Returns
A duplicate of this car-following model
Implemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, MSCFModel_Daniel1, MSCFModel_IDM, MSCFModel_Wiedemann, MSCFModel_PWag2009, MSCFModel_Kerner, MSCFModel_Krauss, MSCFModel_KraussPS, MSCFModel_KraussX, and MSCFModel_Rail.
Referenced by MSVehicleType::duplicateType().
estimateArrivalTime() [1/2]
double MSCFModel::estimateArrivalTime (double dist, double speed, double maxSpeed, double accel) static
Computes the time needed to travel a distance dist given an initial speed and constant acceleration. The speed during traveling is assumed not to exceed the max speed.
Parameters
[in] dist Distance to be covered (assumed >= 0.)
[in] speed Initial speed of vehicle
[in] accel Assumed acceleration until reaching maxspeed or speed=0.
Returns
Returns the estimated time needed to cover the given distance If distance will never be covered with the given parameters INVALID_DOUBLE (from MSLink.h) is returned.
Definition at line 344 of file MSCFModel.cpp.
References INVALID_DOUBLE.
Referenced by MSLCM_SL2015::commitManoeuvre(), MSDevice_SSM::estimateConflictTimes(), and getSpeedAfterMaxDecel().
estimateArrivalTime() [2/2]
double MSCFModel::estimateArrivalTime (double dist, double initialSpeed, double arrivalSpeed, double maxSpeed, double accel, double decel) static
Computes the time needed to travel a distance dist given an initial speed, arrival speed, constant acceleration and deceleration. The speed during traveling is assumed not to exceed the max speed.
Parameters
[in] dist Distance to be covered (assumed >= 0.)
[in] initialSpeed Initial speed of vehicle
[in] arrivalSpeed desired arrival speed of vehicle
[in] accel Assumed acceleration until reaching maxspeed.
[in] accel Assumed deceleration until reaching targetspeed.
Returns
Returns the estimated time needed to cover the given distance If distance will never be covered with the given parameters INVALID_DOUBLE (from MSLink.h) is returned.
Note
Currently, this is still a stub for actually very special situations in LC context: It is assumed that 0==initialSpeed==arrivalSpeed<=maxspeed, accel==decel>0 (because currently this is only used for lane change purposes, where lateral accel == lateral decel)
Definition at line 383 of file MSCFModel.cpp.
References UNUSED_PARAMETER.
estimateSpeedAfterDistance()
double MSCFModel::estimateSpeedAfterDistance (const double dist, const double v, const double accel) const
Definition at line 653 of file MSCFModel.cpp.
References MSVehicleType::getMaxSpeed(), MAX2(), MIN2(), and myType.
Referenced by MSVehicle::estimateLeaveSpeed(), getMinimalArrivalSpeed(), getMinimalArrivalSpeedEuler(), getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
followSpeed()
virtual double MSCFModel::followSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const pure virtual
Computes the vehicle's follow speed (no dawdling)
Returns the velocity of the vehicle in dependence to the vehicle's and its leader's values and the distance between them.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns
EGO's safe speed
Implemented in MSCFModel_IDM, MSCFModel_Krauss, MSCFModel_Wiedemann, MSCFModel_SmartSK, MSCFModel_Daniel1, MSCFModel_KraussOrig1, MSCFModel_PWag2009, MSCFModel_Kerner, and MSCFModel_Rail.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitFollowSpeed(), MSVehicle::getSafeFollowSpeed(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
followSpeedTransient()
double MSCFModel::followSpeedTransient (double duration, const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const virtual
Computes the vehicle's follow speed that avoids a collision for the given amount of time.
Returns the velocity of the vehicle in dependence to the vehicle's and its leader's values and the distance between them.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
[in] predMaxDecel The maximum leader decelration
Returns
EGO's safe speed
Definition at line 255 of file MSCFModel.cpp.
References ACCEL2SPEED, brakeGap(), DIST2SPEED, distAfterTime(), gDebugFlag2, getMaxDecel(), MSGlobals::gSemiImplicitEulerUpdate, myDecel, SPEED2DIST, and TS.
Referenced by MSLCM_SL2015::commitFollowSpeed().
freeSpeed() [1/2]
double MSCFModel::freeSpeed (const MSVehicle *const veh, double speed, double seen, double maxSpeed, const bool onInsertion = false) const virtual
Computes the vehicle's safe speed without a leader.
Returns the velocity of the vehicle in dependence to the length of the free street and the target velocity at the end of the free range. If onInsertion is true, the vehicle may still brake before the next movement.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] seen The look ahead distance
[in] maxSpeed The maximum allowed speed
[in] onInsertion whether speed at insertion is asked for
Returns
EGO's safe speed
Reimplemented in MSCFModel_Rail.
Definition at line 223 of file MSCFModel.cpp.
References MSVehicle::getActionStepLengthSecs(), and myDecel.
Referenced by brakeGap(), MSLane::isInsertionSuccess(), and MSVehicle::planMoveInternal().
freeSpeed() [2/2]
double MSCFModel::freeSpeed (const double currentSpeed, const double decel, const double dist, const double maxSpeed, const bool onInsertion, const double actionStepLength) static
Definition at line 90 of file MSCFModel.cpp.
References ACCEL2DIST, ACCEL2SPEED, DIST2SPEED, MSGlobals::gSemiImplicitEulerUpdate, MAX2(), NUMERICAL_EPS, SPEED2DIST, and TS.
gapExtrapolation()
double MSCFModel::gapExtrapolation (const double duration, const double currentGap, double v1, double v2, double a1 = 0, double a2 = 0, const double maxV1 = std::numeric_limits<double>::max(), const double maxV2 = std::numeric_limits<double>::max()) static
return the resulting gap if, starting with gap currentGap, two vehicles continue with constant accelerations (velocities bounded by 0 and maxSpeed) for a given timespan of length 'duration'.
Parameters
[in] currentGap (pos(veh1) - pos(veh2) at start)
[in] v1 initial speed of vehicle 1
[in] v2 initial speed of vehicle 2
[in] a1 acceleration of vehicle 1
[in] a2 acceleration of vehicle 2
[in] maxV1 maximal speed of vehicle 1
[in] maxV2 maximal speed of vehicle 2
[in] duration time span for the process
Returns
estimated gap after 'duration' seconds
Definition at line 458 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, MAX2(), MIN2(), and TS.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), getSpeedAfterMaxDecel(), and MSLCM_LC2013::informFollower().
getApparentDecel()
double MSCFModel::getApparentDecel () const inline
Get the vehicle type's apparent deceleration [m/s^2] (the one regarded by its followers.
Returns
The apparent deceleration (in m/s^2) of vehicles of this class
Definition at line 227 of file MSCFModel.h.
References myApparentDecel.
Referenced by libsumo::VehicleType::getApparentDecel(), and libsumo::Vehicle::getApparentDecel().
getEmergencyDecel()
double MSCFModel::getEmergencyDecel () const inline
Get the vehicle type's maximal phisically possible deceleration [m/s^2].
Returns
The maximal physically possible deceleration (in m/s^2) of vehicles of this class
Definition at line 219 of file MSCFModel.h.
References myEmergencyDecel.
Referenced by libsumo::VehicleType::getEmergencyDecel(), and libsumo::Vehicle::getEmergencyDecel().
getHeadwayTime()
virtual double MSCFModel::getHeadwayTime () const inline virtual
Get the driver's desired headway [s].
Returns
The desired headway of this class' drivers in s
Definition at line 246 of file MSCFModel.h.
References maxNextSpeed(), minNextSpeed(), and myHeadwayTime.
Referenced by MSVehicleType::check(), MSLaneChanger::checkChange(), MSVehicle::checkRewindLinkLanes(), getMinimalArrivalSpeed(), getMinimalArrivalSpeedEuler(), libsumo::VehicleType::getTau(), libsumo::Vehicle::getTau(), and MSCalibrator::remainingVehicleCapacity().
getImperfection()
virtual double MSCFModel::getImperfection () const inline virtual
Get the driver's imperfection.
Returns
The imperfection of drivers of this class
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, MSCFModel_Daniel1, and MSCFModel_PWag2009.
Definition at line 238 of file MSCFModel.h.
Referenced by libsumo::VehicleType::getImperfection(), and libsumo::Vehicle::getImperfection().
getMaxAccel()
double MSCFModel::getMaxAccel () const inline
Get the vehicle type's maximum acceleration [m/s^2].
Returns
The maximum acceleration (in m/s^2) of vehicles of this class
Definition at line 203 of file MSCFModel.h.
References myAccel.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), libsumo::VehicleType::getAccel(), getMinimalArrivalTime(), MSLCM_LC2013::informFollower(), MSCFModel_KraussPS::maxNextSpeed(), maxNextSpeed(), MSVehicle::planMoveInternal(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
getMaxDecel()
double MSCFModel::getMaxDecel () const inline
Get the vehicle type's maximal comfortable deceleration [m/s^2].
Returns
The maximal comfortable deceleration (in m/s^2) of vehicles of this class
Definition at line 211 of file MSCFModel.h.
References myDecel.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSPModel_Striping::addCrossingVehs(), MSCriticalFollowerDistanceInfo::addFollower(), MSLink::blockedByFoe(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkForPedestrians(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitFollowSpeed(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), followSpeedTransient(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), libsumo::VehicleType::getDecel(), libsumo::Vehicle::getDecel(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), getMinimalArrivalSpeed(), getMinimalArrivalSpeedEuler(), getMinimalArrivalTime(), MSLane::getMissingRearGap(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSLCM_LC2013::overtakeDistance(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSVehicleControl::vehicleDeparted(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
getMinimalArrivalSpeed()
double MSCFModel::getMinimalArrivalSpeed (double dist, double currentSpeed) const
Computes the minimal possible arrival speed after covering a given distance.
Parameters
[in] dist Distance to be covered
[in] currentSpeed Actual speed of vehicle
Definition at line 432 of file MSCFModel.cpp.
References estimateSpeedAfterDistance(), getHeadwayTime(), and getMaxDecel().
Referenced by getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
getMinimalArrivalSpeedEuler()
double MSCFModel::getMinimalArrivalSpeedEuler (double dist, double currentSpeed) const
Computes the minimal possible arrival speed after covering a given distance for Euler update.
Parameters
[in] dist Distance to be covered
[in] currentSpeed Actual speed of vehicle
Definition at line 439 of file MSCFModel.cpp.
References estimateSpeedAfterDistance(), getHeadwayTime(), getMaxDecel(), and INVALID_SPEED.
Referenced by getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
getMinimalArrivalTime()
SUMOTime MSCFModel::getMinimalArrivalTime (double dist, double currentSpeed, double arrivalSpeed) const
Computes the minimal time needed to cover a distance given the desired speed at arrival.
Parameters
[in] dist Distance to be covered
[in] currentSpeed Actual speed of vehicle
[in] arrivalSpeed Desired speed at arrival
Definition at line 331 of file MSCFModel.cpp.
References getMaxAccel(), getMaxDecel(), MAX2(), MAX3(), SUMO_const_haltingSpeed, and TIME2STEPS.
Referenced by getSpeedAfterMaxDecel(), and MSVehicle::planMoveInternal().
getModelID()
virtual int MSCFModel::getModelID () const pure virtual
Returns the model's ID; the XML-Tag number is used.
Returns
The model's ID
Implemented in MSCFModel_IDM, MSCFModel_Wiedemann, MSCFModel_KraussOrig1, MSCFModel_SmartSK, MSCFModel_Daniel1, MSCFModel_PWag2009, MSCFModel_Kerner, MSCFModel_Krauss, MSCFModel_KraussPS, MSCFModel_KraussX, and MSCFModel_Rail.
getSecureGap()
double MSCFModel::getSecureGap (const double speed, const double leaderSpeed, const double leaderMaxDecel) const inline
Returns the minimum gap to reserve if the leader is braking at maximum (>=0)
Parameters
[in] speed EGO's speed
[in] leaderSpeed LEADER's speed
[in] leaderMaxDecel LEADER's max. deceleration rate
Definition at line 304 of file MSCFModel.h.
References brakeGap(), MAX2(), myDecel, and myHeadwayTime.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLCM_SL2015::commitFollowSpeed(), MSLaneChanger::computeOvertakingTime(), MSLane::freeInsertion(), MSLane::getMissingRearGap(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLCM_LC2013::overtakeDistance(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
getSpeedAfterMaxDecel()
virtual double MSCFModel::getSpeedAfterMaxDecel (double v) const inline virtual
Returns the velocity after maximum deceleration.
Parameters
[in] v The velocity
Returns
The velocity after maximum deceleration
Reimplemented in MSCFModel_Rail.
Definition at line 318 of file MSCFModel.h.
References ACCEL2SPEED, avoidArrivalAccel(), distAfterTime(), estimateArrivalTime(), estimateSpeedAfterDistance(), gapExtrapolation(), getMinimalArrivalSpeed(), getMinimalArrivalSpeedEuler(), getMinimalArrivalTime(), MAX2(), myDecel, passingTime(), and speedAfterTime().
Referenced by MSLCM_LC2013::_wantsChange(), MSCFModel_SmartSK::followSpeed(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_Wiedemann::stopSpeed().
insertionFollowSpeed()
double MSCFModel::insertionFollowSpeed (const MSVehicle *const veh, double speed, double gap2pred, double predSpeed, double predMaxDecel) const virtual
Computes the vehicle's safe speed (no dawdling) This method is used during the insertion stage. Whereas the method followSpeed returns the desired speed which may be lower than the safe speed, this method only considers safety constraints.
Returns the velocity of the vehicle in dependence to the vehicle's and its leader's values and the distance between them.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns
EGO's safe speed
Reimplemented in MSCFModel_KraussOrig1.
Definition at line 234 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, and maximumSafeFollowSpeed().
Referenced by MSLane::freeInsertion(), MSLane::getCriticalLeader(), and MSLane::safeInsertionSpeed().
insertionStopSpeed()
double MSCFModel::insertionStopSpeed (const MSVehicle *const veh, double speed, double gap) const virtual
Computes the vehicle's safe speed for approaching an obstacle at insertion without constraints due to acceleration capabilities and previous speeds.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap The (netto) distance to the the obstacle
Returns
EGO's safe speed for approaching a non-moving obstacle at insertion
See also
stopSpeed() and insertionFollowSpeed()
Definition at line 245 of file MSCFModel.cpp.
References MSVehicleType::getMaxSpeed(), MSGlobals::gSemiImplicitEulerUpdate, maximumSafeStopSpeed(), MIN2(), myType, and stopSpeed().
Referenced by MSLane::isInsertionSuccess().
interactionGap()
double MSCFModel::interactionGap (const MSVehicle *const veh, double vL) const virtual
Returns the maximum gap at which an interaction between both vehicles occurs.
"interaction" means that the LEADER influences EGO's speed.
Parameters
[in] veh The EGO vehicle
[in] vL LEADER's speed
Returns
The interaction gap
Todo:
evaluate signature
Reimplemented in MSCFModel_IDM, and MSCFModel_Wiedemann.
Definition at line 189 of file MSCFModel.cpp.
References MSVehicle::getLane(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MAX2(), maxNextSpeed(), MIN2(), myDecel, myHeadwayTime, and SPEED2DIST.
Referenced by MSAbstractLaneChangeModel::predInteraction().
maximumSafeFollowSpeed()
double MSCFModel::maximumSafeFollowSpeed (double gap, double egoSpeed, double predSpeed, double predMaxDecel, bool onInsertion = false) const
Returns the maximum safe velocity for following the given leader.
Parameters
[in] gap2pred The (netto) distance to the LEADER
[in] egoSpeed The FOLLOWERS's speed
[in] predSpeed The LEADER's speed
[in] predMaxDecel The LEADER's maximum deceleration
[in] onInsertion Indicator whether the call is triggered during vehicle insertion
Returns
the safe velocity
Returns the SK-vsafe.
Definition at line 770 of file MSCFModel.cpp.
References brakeGap(), MSGlobals::gSemiImplicitEulerUpdate, ISNAN(), MAX2(), maximumSafeStopSpeed(), myDecel, and myHeadwayTime.
Referenced by MSLCM_LC2013::_wantsChange(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel_KraussOrig1::insertionFollowSpeed(), insertionFollowSpeed(), and setHeadwayTime().
maximumSafeStopSpeed()
double MSCFModel::maximumSafeStopSpeed (double gap, double currentSpeed, bool onInsertion = false, double headway = -1) const
Returns the maximum next velocity for stopping within gap.
Parameters
[in] gap The (netto) distance to the desired stopping point
[in] currentSpeed The current speed of the ego vehicle
[in] onInsertion Indicator whether the call is triggered during vehicle insertion
[in] headway The desired time headway to be included in the calculations (default argument -1 induces the use of myHeadway)
Definition at line 662 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, maximumSafeStopSpeedBallistic(), and maximumSafeStopSpeedEuler().
Referenced by MSLCM_LC2013::_wantsChange(), insertionStopSpeed(), maximumSafeFollowSpeed(), MSVehicle::planMoveInternal(), setHeadwayTime(), MSCFModel_Rail::stopSpeed(), and MSCFModel_Krauss::stopSpeed().
maximumSafeStopSpeedBallistic()
double MSCFModel::maximumSafeStopSpeedBallistic (double gap, double currentSpeed, bool onInsertion = false, double headway = -1) const
Returns the maximum next velocity for stopping within gap when using the ballistic positional update.
Note
This takes into account the driver's reaction time tau (i.e. the desired headway) and the car's current speed. (The latter is required to calculate the distance covered in the following timestep.)
Parameters
[in] gap The (netto) distance to the desired stopping point
[in] currentSpeed The current speed of the ego vehicle
[in] onInsertion Indicator whether the call is triggered during vehicle insertion
[in] headway The desired time headway to be included in the calculations (default argument -1 induces the use of myHeadway)
Returns
the safe velocity (to be attained at the end of the following time step) that assures the possibility of stopping within gap. If a negative value is returned, the required stop has to take place before the end of the time step.
Definition at line 703 of file MSCFModel.cpp.
References INVALID_SPEED, MAX2(), myDecel, myHeadwayTime, NUMERICAL_EPS, and TS.
Referenced by maximumSafeStopSpeed(), setHeadwayTime(), and MSCFModel_KraussOrig1::stopSpeed().
maximumSafeStopSpeedEuler()
double MSCFModel::maximumSafeStopSpeedEuler (double gap) const
Returns the maximum next velocity for stopping within gap when using the semi-implicit Euler update.
Parameters
[in] gap The (netto) distance to the LEADER
Definition at line 672 of file MSCFModel.cpp.
References ACCEL2SPEED, DIST2SPEED, MIN2(), myDecel, myHeadwayTime, NUMERICAL_EPS, and TS.
Referenced by maximumSafeStopSpeed(), and setHeadwayTime().
maxNextSpeed()
double MSCFModel::maxNextSpeed (double speed, const MSVehicle *const veh) const virtual
Returns the maximum speed given the current speed.
The implementation of this method must take into account the time step duration.
Justification: Due to air brake or other influences, the vehicle's next maximum speed may depend on the vehicle's current speed (given).
Parameters
[in] speed The vehicle's current speed
[in] speed The vehicle itself, for obtaining other values
Returns
The maximum possible speed for the next step
Reimplemented in MSCFModel_KraussPS, and MSCFModel_Rail.
Definition at line 204 of file MSCFModel.cpp.
References ACCEL2SPEED, getMaxAccel(), MSVehicleType::getMaxSpeed(), MIN2(), and myType.
Referenced by MSLCM_SL2015::commitManoeuvre(), MSCFModel_Kerner::followSpeed(), MSCFModel_Daniel1::followSpeed(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_Krauss::followSpeed(), getHeadwayTime(), interactionGap(), MSCFModel_Krauss::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussX::moveHelper(), moveHelper(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::processTraCISpeedControl(), MSCFModel_Krauss::stopSpeed(), MSCFModel_Kerner::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), MSCFModel_Daniel1::stopSpeed(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_Wiedemann::stopSpeed().
minNextSpeed()
double MSCFModel::minNextSpeed (double speed, const MSVehicle *const veh = 0) const virtual
Returns the minimum speed given the current speed (depends on the numerical update scheme and its step width) Note that it wouldn't have to depend on the numerical update scheme if the semantics would rely on acceleration instead of velocity.
Parameters
[in] speed The vehicle's current speed
[in] speed The vehicle itself, for obtaining other values, if needed as e.g. road conditions.
Returns
The minimum possible speed for the next step
Reimplemented in MSCFModel_Rail.
Definition at line 210 of file MSCFModel.cpp.
References ACCEL2SPEED, MSGlobals::gSemiImplicitEulerUpdate, MAX2(), and myEmergencyDecel.
Referenced by MSLCM_SL2015::commitManoeuvre(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_Krauss::followSpeed(), getHeadwayTime(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussX::moveHelper(), moveHelper(), and MSVehicle::planMoveInternal().
moveHelper()
double MSCFModel::moveHelper (MSVehicle *const veh, double vPos) const virtual
Applies interaction with stops and lane changing model influences.
Parameters
[in] veh The ego vehicle
[in] vPos The possible velocity
Returns
The velocity after applying interactions with stops and lane change model influences
Reimplemented in MSCFModel_IDM, MSCFModel_Wiedemann, MSCFModel_KraussX, MSCFModel_SmartSK, MSCFModel_Daniel1, MSCFModel_Kerner, MSCFModel_Krauss, MSCFModel_KraussOrig1, MSCFModel_PWag2009, and MSCFModel_Rail.
Definition at line 155 of file MSCFModel.cpp.
References ACCEL2SPEED, MSVehicle::getActionStepLengthSecs(), MSVehicle::getLaneChangeModel(), MSVehicle::getMaxSpeedOnLane(), MSVehicle::getSpeed(), MSGlobals::gSemiImplicitEulerUpdate, MAX2(), maxNextSpeed(), MIN2(), MIN3(), minNextSpeed(), MSAbstractLaneChangeModel::patchSpeed(), and MSVehicle::processNextStop().
Referenced by MSCFModel_Kerner::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_Wiedemann::moveHelper(), and MSCFModel_IDM::moveHelper().
passingTime()
double MSCFModel::passingTime (const double lastPos, const double passedPos, const double currentPos, const double lastSpeed, const double currentSpeed) static
Calculates the time at which the position passedPosition has been passed In case of a ballistic update, the possibility of a stop within a time step requires more information about the last time-step than in case of the euler update to determine the last position if the currentSpeed is zero.
Parameters
[in] lastPos the position at time t=0 (must be < currentPos)
[in] passedPos the position for which the passing time is to be determined (has to lie within [lastPos, currentPos]!)
[in] currentPos the position at time t=TS (one time-step after lastPos) (must be > lastPos)
[in] lastSpeed the speed at moment t=0
[in] currentSpeed the speed at moment t=TS
Returns
time t in [0,TS] at which passedPos in [lastPos, currentPos] was passed.
Definition at line 552 of file MSCFModel.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, MAX2(), MIN2(), NUMERICAL_EPS, SPEED2ACCEL, TS, and WRITE_ERROR.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSDevice_SSM::checkConflictEntryAndExit(), getSpeedAfterMaxDecel(), MSE3Collector::MSE3EntryReminder::notifyMove(), MSInstantInductLoop::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), and MSE3Collector::MSE3LeaveReminder::notifyMove().
setApparentDecel()
virtual void MSCFModel::setApparentDecel (double decel) inline virtual
Sets a new value for the apparent deceleration [m/s^2].
Parameters
[in] decel The new deceleration in m/s^2
Definition at line 467 of file MSCFModel.h.
References myApparentDecel.
Referenced by libsumo::VehicleType::setApparentDecel().
setEmergencyDecel()
virtual void MSCFModel::setEmergencyDecel (double decel) inline virtual
Sets a new value for maximal physically possible deceleration [m/s^2].
Parameters
[in] decel The new deceleration in m/s^2
Definition at line 459 of file MSCFModel.h.
References myEmergencyDecel.
Referenced by libsumo::VehicleType::setEmergencyDecel().
setHeadwayTime()
virtual void MSCFModel::setHeadwayTime (double headwayTime) inline virtual
Sets a new value for desired headway [s].
Parameters
[in] headwayTime The new desired headway (in s)
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 483 of file MSCFModel.h.
References maximumSafeFollowSpeed(), maximumSafeStopSpeed(), maximumSafeStopSpeedBallistic(), maximumSafeStopSpeedEuler(), and myHeadwayTime.
Referenced by libsumo::VehicleType::setTau().
setImperfection()
virtual void MSCFModel::setImperfection (double imperfection) inline virtual
Sets a new value for driver imperfection.
Parameters
[in] accel The new driver imperfection
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 475 of file MSCFModel.h.
References UNUSED_PARAMETER.
Referenced by libsumo::VehicleType::setImperfection().
setMaxAccel()
virtual void MSCFModel::setMaxAccel (double accel) inline virtual
Sets a new value for maximum acceleration [m/s^2].
Parameters
[in] accel The new acceleration in m/s^2
Definition at line 443 of file MSCFModel.h.
References myAccel.
Referenced by libsumo::VehicleType::setAccel().
setMaxDecel()
virtual void MSCFModel::setMaxDecel (double decel) inline virtual
Sets a new value for maximal comfortable deceleration [m/s^2].
Parameters
[in] decel The new deceleration in m/s^2
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 451 of file MSCFModel.h.
References myDecel.
Referenced by MSLCM_SL2015::commitFollowSpeed(), MSCFModel_Rail::MSCFModel_Rail(), and libsumo::VehicleType::setDecel().
speedAfterTime()
double MSCFModel::speedAfterTime (const double t, const double oldSpeed, const double dist) static
Calculates the speed after a time t [0,TS] given the initial speed and the distance traveled in an interval of step length TS.
Note
If the acceleration were known, this would be much nicer, but in this way we need to reconstruct it (for the ballistic update at least, where we assume that a stop may occur within the interval)
Parameters
[in] t time in [0,TS] for which the speed shall be determined
[in] oldSpeed speed before the last time step (referred to as t == 0)
[in] distance covered
Returns
speed at time t
Definition at line 624 of file MSCFModel.cpp.
References DIST2SPEED, MSGlobals::gSemiImplicitEulerUpdate, and TS.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), getSpeedAfterMaxDecel(), MSInstantInductLoop::notifyMove(), and MSMeanData::MeanDataValues::notifyMove().
stopSpeed()
virtual double MSCFModel::stopSpeed (const MSVehicle *const veh, const double speed, double gap) const pure virtual
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling)
Returns the velocity of the vehicle when approaching a static object (such as the end of a lane) assuming no reaction time is needed.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap The (netto) distance to the the obstacle
Returns
EGO's safe speed for approaching a non-moving obstacle
Todo:
generic Interface, models can call for the values they need
Implemented in MSCFModel_IDM, MSCFModel_Wiedemann, MSCFModel_SmartSK, MSCFModel_Daniel1, MSCFModel_KraussOrig1, MSCFModel_PWag2009, MSCFModel_Kerner, MSCFModel_Krauss, and MSCFModel_Rail.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSLane::checkForPedestrians(), MSVehicle::getSafeFollowSpeed(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), insertionStopSpeed(), MSLane::isInsertionSuccess(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
Field Documentation
myAccel
double MSCFModel::myAccel protected
The vehicle's maximum acceleration [m/s^2].
Definition at line 534 of file MSCFModel.h.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_Daniel1::dawdle(), MSCFModel_SmartSK::dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_Krauss::dawdle2(), MSCFModel_KraussX::dawdleX(), MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_PWag2009::followSpeed(), MSCFModel_Wiedemann::fullspeed(), getMaxAccel(), MSCFModel_IDM::interactionGap(), MSCFModel_SmartSK::MSCFModel_SmartSK(), setMaxAccel(), and MSCFModel_PWag2009::stopSpeed().
myApparentDecel
double MSCFModel::myApparentDecel protected
The vehicle's deceleration as expected by surrounding traffic [m/s^2].
Definition at line 541 of file MSCFModel.h.
Referenced by MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), getApparentDecel(), and setApparentDecel().
myDecel
double MSCFModel::myDecel protected
The vehicle's maximum deceleration [m/s^2].
Definition at line 537 of file MSCFModel.h.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_Daniel1::_vsafe(), MSCFModel_SmartSK::_vsafe(), brakeGap(), MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_Wiedemann::emergency(), MSCFModel_PWag2009::followSpeed(), followSpeedTransient(), MSCFModel_Rail::freeSpeed(), freeSpeed(), getMaxDecel(), getSecureGap(), getSpeedAfterMaxDecel(), MSCFModel_IDM::interactionGap(), interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), maximumSafeFollowSpeed(), maximumSafeStopSpeedBallistic(), maximumSafeStopSpeedEuler(), MSCFModel_SmartSK::MSCFModel_SmartSK(), MSCFModel_Daniel1::setHeadwayTime(), MSCFModel_SmartSK::setHeadwayTime(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel_Daniel1::setMaxDecel(), MSCFModel_SmartSK::setMaxDecel(), MSCFModel_KraussOrig1::setMaxDecel(), setMaxDecel(), MSCFModel_PWag2009::stopSpeed(), and MSCFModel_KraussOrig1::vsafe().
myEmergencyDecel
double MSCFModel::myEmergencyDecel protected
The vehicle's maximum emergency deceleration [m/s^2].
Definition at line 539 of file MSCFModel.h.
Referenced by MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_Wiedemann::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), getEmergencyDecel(), minNextSpeed(), and setEmergencyDecel().
myHeadwayTime
double MSCFModel::myHeadwayTime protected
The driver's desired time headway (aka reaction time tau) [s].
Definition at line 544 of file MSCFModel.h.
Referenced by MSCFModel_IDM::_v(), brakeGap(), MSCFModel_SmartSK::createVehicleVariables(), MSCFModel_KraussX::duplicate(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_IDM::duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_PWag2009::followSpeed(), getHeadwayTime(), getSecureGap(), interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), maximumSafeFollowSpeed(), maximumSafeStopSpeedBallistic(), maximumSafeStopSpeedEuler(), MSCFModel_Daniel1::setHeadwayTime(), MSCFModel_SmartSK::setHeadwayTime(), MSCFModel_KraussOrig1::setHeadwayTime(), setHeadwayTime(), MSCFModel_Daniel1::setMaxDecel(), MSCFModel_SmartSK::setMaxDecel(), MSCFModel_KraussOrig1::setMaxDecel(), MSCFModel_PWag2009::stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
myType
const MSVehicleType* MSCFModel::myType protected
The type to which this model definition belongs to.
Definition at line 531 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), estimateSpeedAfterDistance(), insertionStopSpeed(), MSCFModel_KraussPS::maxNextSpeed(), and maxNextSpeed().
The documentation for this class was generated from the following files:
MSCFModel.h
MSCFModel.cpp