SUMO - Simulation of Urban MObility: MSPushButton.cpp File Reference
MSPushButton.cpp File Reference
#include <utils/common/SwarmDebug.h>
#include "MSPushButton.h"
#include "MSPhaseDefinition.h"
#include "../MSEdge.h"
#include "../MSLane.h"
#include "../MSVehicle.h"
#include <microsim/pedestrians/MSPerson.h>
Macros
#define SWARM_DEBUG
Functions
void getWalking (const std::vector< MSEdge *> &edges, std::vector< MSEdge *> &walkingEdges)
Checks if any of the edges is a walking area.
const std::vector< MSEdge * > getWalkingAreas (const MSEdge *crossing)
Get the walking areas adjacent to the crossing.
Detailed Description
Author
Federico Caselli
Date
2015-07-15
Version
$Id$
Definition in file MSPushButton.cpp.
Macro Definition Documentation
SWARM_DEBUG
#define SWARM_DEBUG
Definition at line 20 of file MSPushButton.cpp.
Function Documentation
getWalking()
void getWalking (const std::vector< MSEdge *> & edges, std::vector< MSEdge *> & walkingEdges)
Checks if any of the edges is a walking area.
Definition at line 121 of file MSPushButton.cpp.
References MSEdge::getPermissions(), MSEdge::isWalkingArea(), and SVC_PEDESTRIAN.
Referenced by getWalkingAreas().
getWalkingAreas()
const std::vector<MSEdge*> getWalkingAreas (const MSEdge * crossing)
Get the walking areas adjacent to the crossing.
Definition at line 131 of file MSPushButton.cpp.
References MSEdge::getPredecessors(), MSEdge::getSuccessors(), and getWalking().
Referenced by MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), and MSPedestrianPushButton::loadPushButtons().