SUMO - Simulation of Urban MObility: NIImporter_VISUM Class Reference
NIImporter_VISUM Class Reference
A VISUM network importer.
#include <NIImporter_VISUM.h>
Data Structures
struct TypeParser
A complete call description for parsing a single db.
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads network definition from the assigned option and stores it in the given network builder.
Protected Member Functions
void load ()
Parses the VISUM-network file storing the parsed structures within myNetBuilder.
NIImporter_VISUM (NBNetBuilder &nb, const std::string &file, NBCapacity2Lanes capacity2Lanes, bool useVisumPrio)
constructor
~NIImporter_VISUM ()
destructor
Private Types
typedef std::map< std::string, NIVisumTL * > NIVisumTL_Map
Definition of a map for loaded traffic lights (id->tls)
typedef std::vector< TypeParser > ParserVector
Definition of the list of known parsers.
typedef void(NIImporter_VISUM::* ParsingFunction) ()
Definition of a function for parsing a single line from a certain db.
typedef std::map< std::string, std::string > VSysTypeNames
Definition of a storage for vsystypes.
Private Member Functions
void addParser (const std::string &name, ParsingFunction function)
Adds a parser into the sorted list of parsers to use.
NBNode * buildDistrictNode (const std::string &id, NBNode *dest, bool isSource)
Builds a node for the given district and returns it.
bool checkNodes (NBNode *from, NBNode *to)
Returns whether both nodes are a valid combination of from/to-nodes.
NBEdge * getEdge (NBNode *FromNode, NBNode *ToNode)
Returns the edge that connects both nodes.
NBEdge * getNamedEdge (const std::string &fieldName)
Tries to get the edge which name is stored in the given field.
NBEdge * getNamedEdge (const std::string &fieldName1, const std::string &fieldName2)
The same, but two different names for the field are allowed.
NBEdge * getNamedEdgeContinuating (const std::string &fieldName, NBNode *node)
Tries to get the edge which name is stored in the given field continuating the search for a subedge that ends at the given node.
NBEdge * getNamedEdgeContinuating (const std::string &fieldName1, const std::string &fieldName2, NBNode *node)
The same, but two different names for the field are allowed.
NBEdge * getNamedEdgeContinuating (NBEdge *begin, NBNode *node)
The same, but for an already given edge.
double getNamedFloat (const std::string &fieldName)
Returns the value from the named column as a float.
double getNamedFloat (const std::string &fieldName1, const std::string &fieldName2)
The same, but two different names for the field are allowed.
double getNamedFloat (const std::string &fieldName, double defaultValue)
Returns the value from the named column as a float or the default value if an error occurs.
double getNamedFloat (const std::string &fieldName1, const std::string &fieldName2, double defaultValue)
The same, but two different names for the field are allowed.
NBNode * getNamedNode (const std::string &fieldName)
Tries to get the node which name is stored in the given field.
NBNode * getNamedNode (const std::string &fieldName1, const std::string &fieldName2)
The same, but two different names for the field are allowed.
std::string getNamedString (const std::string &fieldName)
Returns the value from the named column as a normalised string.
std::string getNamedString (const std::string &fieldName1, const std::string &fieldName2)
The same, but two different names for the field are allowed.
NBEdge * getReversedContinuating (NBEdge *edge, NBNode *node)
Returns the opposite direction of the given edge.
bool getWeightedBool (const std::string &name)
tries to get a bool which is possibly assigned to a certain modality
double getWeightedFloat (const std::string &name)
tries to get a double which is possibly assigned to a certain modality
void parse_AreaSubPartElement ()
Parses ABBZULSASIGNALGRUPPE/SIGNALGRUPPEZUABBIEGER.
void parse_Connectors ()
Parses ANBINDUNG.
void parse_Districts ()
Parses BEZIRK.
void parse_EdgePolys ()
Parses STRECKENPOLY.
void parse_Edges ()
Parses STRECKE/STRECKEN.
void parse_Kante ()
Parses FLAECHENELEMENT.
void parse_Lanes ()
Parses FAHRSTREIFEN.
void parse_LanesConnections ()
Parses FAHRSTREIFENABBIEGER.
void parse_Nodes ()
Parses KNOTEN.
void parse_NodesToTrafficLights ()
Parses KNOTENZULSA/SIGNALANLAGEZUKNOTEN.
void parse_PartOfArea ()
Parses FLAECHENELEMENT.
void parse_Phases ()
Parses LSAPHASE/PHASE.
void parse_Point ()
Parses PUNKT.
void parse_SignalGroups ()
Parses LSASIGNALGRUPPE/SIGNALGRUPPE.
void parse_SignalGroupsToPhases ()
Parses LSASIGNALGRUPPEZULSAPHASE.
void parse_TrafficLights ()
Parses LSA/SIGNALANLAGE.
void parse_Turns ()
Parses ABBIEGEBEZIEHUNG/ABBIEGER.
void parse_TurnsToSignalGroups ()
Parses ABBZULSASIGNALGRUPPE/SIGNALGRUPPEZUABBIEGER.
void parse_Types ()
Parses STRECKENTYP.
void parse_VSysTypes ()
Parses VSYS.
Private Attributes
NBCapacity2Lanes myCapacity2Lanes
The converter to compute the lane number of edges from their capacity.
std::string myCurrentID
The name of the currently parsed item used for error reporting.
std::map< NBDistrict *, PositionVector > myDistrictShapes
A temporary storage for district shapes as they are filled incrementally.
std::map< long long int, std::pair< long long int, long long int > > myEdges
A map of edge (not road, but "edge" in this case) ids to from/to-points.
std::string myFileName
The name of the parsed file, for error reporting.
NamedColumnsParser myLineParser
the parser to parse the information from the data lines
LineReader myLineReader
The line reader to use to read from the file.
NBNetBuilder & myNetBuilder
The network builder to fill with loaded values.
std::map< long long int, Position > myPoints
A map of point ids to positions.
std::map< long long int, NBDistrict * > myShapeDistrictMap
A map from district shape definition name to the district.
ParserVector mySingleDataParsers
List of known parsers.
std::map< long long int, std::vector< long long int > > mySubPartsAreas
A map from area parts to area ids.
NIVisumTL_Map myTLS
List of visum traffic lights.
std::vector< std::string > myTouchedEdges
Already read edges.
bool myUseVisumPrio
Information whether VISUM priority information shall be used.
VSysTypeNames myVSysTypes
The used vsystypes.
Detailed Description
A VISUM network importer.
This class build an internal list of those VISUM-db entries which are supported, first. This list is sorted in a way that the parsed dbs can build upon each other as their related structures within the XML-input. So, nodes are loaded first, then edges, etc.
Because these structures may have a different order within the VISUM-file than we need, at first the file is scanned and any occurence of one of the searched dbs is saved. That's where the "Found $XXX at YYY" are printed. "YYY" is the character position within the file.
In a second step, the dbs are parsed in the order we need. It is asked for each subsequently whether it was found and if so, the proper parse_XXX() method is called.
Definition at line 75 of file NIImporter_VISUM.h.
Member Typedef Documentation
NIVisumTL_Map
typedef std::map<std::string, NIVisumTL*> NIImporter_VISUM::NIVisumTL_Map private
Definition of a map for loaded traffic lights (id->tls)
Definition at line 489 of file NIImporter_VISUM.h.
ParserVector
typedef std::vector<TypeParser> NIImporter_VISUM::ParserVector private
Definition of the list of known parsers.
Definition at line 484 of file NIImporter_VISUM.h.
ParsingFunction
typedef void(NIImporter_VISUM::* NIImporter_VISUM::ParsingFunction) () private
Definition of a function for parsing a single line from a certain db.
This function may assume that both the LineParser is initialised with the current line.
Definition at line 357 of file NIImporter_VISUM.h.
VSysTypeNames
typedef std::map<std::string, std::string> NIImporter_VISUM::VSysTypeNames private
Definition of a storage for vsystypes.
Definition at line 479 of file NIImporter_VISUM.h.
Constructor & Destructor Documentation
NIImporter_VISUM()
NIImporter_VISUM::NIImporter_VISUM (NBNetBuilder & nb, const std::string & file, NBCapacity2Lanes capacity2Lanes, bool useVisumPrio) protected
constructor
Builds the list of typed db parsers ("TypeParser") and stores them in mySingleDataParsers in the order the according db values must be parsed.
Parameters
[in,out] nb the network builder (storage) to fill with parsed values
[in] file The name of the file to parse
[in] capacity2Lanes The converter from flow to lanes
[in] useVisumPrio Information whether the VISUM type's priority shall be used
Definition at line 71 of file NIImporter_VISUM.cpp.
References addParser(), parse_AreaSubPartElement(), parse_Connectors(), parse_Districts(), parse_EdgePolys(), parse_Edges(), parse_Kante(), parse_Lanes(), parse_LanesConnections(), parse_Nodes(), parse_NodesToTrafficLights(), parse_PartOfArea(), parse_Phases(), parse_Point(), parse_SignalGroups(), parse_SignalGroupsToPhases(), parse_TrafficLights(), parse_Turns(), parse_TurnsToSignalGroups(), parse_Types(), and parse_VSysTypes().
~NIImporter_VISUM()
NIImporter_VISUM::~NIImporter_VISUM () protected
destructor
Definition at line 128 of file NIImporter_VISUM.cpp.
References myTLS.
Member Function Documentation
addParser()
void NIImporter_VISUM::addParser (const std::string & name, ParsingFunction function) private
Adds a parser into the sorted list of parsers to use.
Parameters
[in] name db name to assign the parser to
[in] function The function to use for parsing the named db
Definition at line 136 of file NIImporter_VISUM.cpp.
References NIImporter_VISUM::TypeParser::function, mySingleDataParsers, NIImporter_VISUM::TypeParser::name, and NIImporter_VISUM::TypeParser::position.
Referenced by NIImporter_VISUM().
buildDistrictNode()
NBNode * NIImporter_VISUM::buildDistrictNode (const std::string & id, NBNode * dest, bool isSource) private
Builds a node for the given district and returns it.
If the district does not exist, an error is generated and 0 returned. Otherwise a position for the new node is computed and the new node is built using a combination of the district name and the node name as id. If Inserting this node into the net builder fails, zero is returned.
Parameters
[in] id Name of the district
[in] dest Name of the according network node
[in] isSource Information whether this node will be used as a source
Returns
The built node, zero if an error occured
Definition at line 1255 of file NIImporter_VISUM.cpp.
References NBNetBuilder::getDistrictCont(), Named::getID(), NBNetBuilder::getNodeCont(), NBDistrict::getPosition(), NBNodeCont::insert(), myNetBuilder, NBDistrictCont::retrieve(), NBNodeCont::retrieve(), and WRITE_ERROR.
Referenced by parse_Connectors().
checkNodes()
bool NIImporter_VISUM::checkNodes (NBNode * from, NBNode * to) private
Returns whether both nodes are a valid combination of from/to-nodes.
They are valid if both are !=0 and differ.
Parameters
[in] from The from-node
[in] from The to-node
Returns
Whether the nodes may be used
Definition at line 1278 of file NIImporter_VISUM.cpp.
References WRITE_ERROR.
Referenced by parse_EdgePolys(), and parse_Edges().
getEdge()
NBEdge * NIImporter_VISUM::getEdge (NBNode * FromNode, NBNode * ToNode) private
Returns the edge that connects both nodes.
Parameters
[in] FromNode Name of the node the edge shall start at
[in] ToNode Name of the node the edge shall end at
Returns
The edge connecting both nodes, 0 if no such edge exists
!!
Definition at line 1180 of file NIImporter_VISUM.cpp.
References NBNode::getOutgoingEdges().
Referenced by parse_TurnsToSignalGroups().
getNamedEdge() [1/2]
NBEdge * NIImporter_VISUM::getNamedEdge (const std::string & fieldName) private
Tries to get the edge which name is stored in the given field.
If the field can not be parsed, an exception is thrown. Prints an error if the edge could not be found, returning 0. Otherwise, if the field could be parsed and the edge was found, this edge is returned.
Parameters
[in] fieldName Name of the column to extract the edge's name from
Returns
An already known edge with the found name
Exceptions
OutOfBoundsException If the current data line has less entries than the edge id's position
NumberFormatException If the edge id is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1060 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), NBNetBuilder::getEdgeCont(), myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), NBEdgeCont::retrieve(), and WRITE_ERROR.
Referenced by getNamedEdge(), and parse_Lanes().
getNamedEdge() [2/2]
NBEdge * NIImporter_VISUM::getNamedEdge (const std::string & fieldName1, const std::string & fieldName2) private
The same, but two different names for the field are allowed.
Parameters
[in] fieldName1 Name of the first column to extract the edge's name from
[in] fieldName2 Name of the second column to extract the edge's name from
Returns
An already known edge with the found name
Exceptions
OutOfBoundsException If the current data line has less entries than the edge id's position
NumberFormatException If the edge id is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1071 of file NIImporter_VISUM.cpp.
References getNamedEdge(), NamedColumnsParser::know(), and myLineParser.
getNamedEdgeContinuating() [1/3]
NBEdge * NIImporter_VISUM::getNamedEdgeContinuating (const std::string & fieldName, NBNode * node) private
Tries to get the edge which name is stored in the given field continuating the search for a subedge that ends at the given node.
If the field can not be parsed, an exception is thrown. Prints an error if the edge could not be found, returning 0. Otherwise, if the field could be parsed and the edge was found, this edge is returned.
Parameters
[in] fieldName Name of the column to extract the edge's name from
[in] node The node the consecutive edge must end at in order to be returned
Returns
The edge's continuation up to the given node, 0 if not found
Exceptions
OutOfBoundsException If the current data line has less entries than the edge id's position
NumberFormatException If the edge id is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1158 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), NBNetBuilder::getEdgeCont(), myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), NBEdgeCont::retrieve(), and WRITE_ERROR.
Referenced by getNamedEdgeContinuating(), getReversedContinuating(), parse_Lanes(), parse_LanesConnections(), and parse_TurnsToSignalGroups().
getNamedEdgeContinuating() [2/3]
NBEdge * NIImporter_VISUM::getNamedEdgeContinuating (const std::string & fieldName1, const std::string & fieldName2, NBNode * node) private
The same, but two different names for the field are allowed.
Parameters
[in] fieldName1 Name of the first column to extract the edge's name from
[in] fieldName2 Name of the second column to extract the edge's name from
[in] node The node the consecutive edge must end at in order to be returned
Returns
The edge's continuation up to the given node, 0 if not found
Exceptions
OutOfBoundsException If the current data line has less entries than the edge id's position
NumberFormatException If the edge id is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1169 of file NIImporter_VISUM.cpp.
References getNamedEdgeContinuating(), NamedColumnsParser::know(), and myLineParser.
getNamedEdgeContinuating() [3/3]
NBEdge * NIImporter_VISUM::getNamedEdgeContinuating (NBEdge * begin, NBNode * node) private
The same, but for an already given edge.
Parameters
[in] begin The edge to get the continuation of
[in] node The node the consecutive edge must end at in order to be returned
Returns
The edge's continuation up to the given node, 0 if not found
Definition at line 1097 of file NIImporter_VISUM.cpp.
References NBEdge::getFromNode(), Named::getID(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), and NBEdge::getToNode().
getNamedFloat() [1/4]
double NIImporter_VISUM::getNamedFloat (const std::string & fieldName) private
Returns the value from the named column as a float.
Parameters
[in] fieldName Name of the column to extract the float from
Returns
The parsed real
Exceptions
OutOfBoundsException If the current data line has less entries than the float's position
NumberFormatException If the float is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1193 of file NIImporter_VISUM.cpp.
References TplConvert::_2double(), StringUtils::endsWith(), NamedColumnsParser::get(), and myLineParser.
Referenced by getNamedFloat(), parse_Districts(), parse_EdgePolys(), parse_Nodes(), parse_Phases(), parse_SignalGroups(), parse_TrafficLights(), and parse_Types().
getNamedFloat() [2/4]
double NIImporter_VISUM::getNamedFloat (const std::string & fieldName1, const std::string & fieldName2) private
The same, but two different names for the field are allowed.
Parameters
[in] fieldName1 Name of the first column to extract the float from
[in] fieldName2 Name of the second column to extract the efloat from
Returns
The parsed real
Exceptions
OutOfBoundsException If the current data line has less entries than the float's position
NumberFormatException If the float is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1213 of file NIImporter_VISUM.cpp.
References getNamedFloat(), NamedColumnsParser::know(), and myLineParser.
getNamedFloat() [3/4]
double NIImporter_VISUM::getNamedFloat (const std::string & fieldName, double defaultValue) private
Returns the value from the named column as a float or the default value if an error occurs.
Parameters
[in] fieldName Name of the column to extract the float from
[in] defaultValue The default to return in the case of an error
Returns
The parsed real or the default value if an error while parsing occured
Definition at line 1203 of file NIImporter_VISUM.cpp.
References TplConvert::_2double(), NamedColumnsParser::get(), and myLineParser.
getNamedFloat() [4/4]
double NIImporter_VISUM::getNamedFloat (const std::string & fieldName1, const std::string & fieldName2, double defaultValue) private
The same, but two different names for the field are allowed.
Parameters
[in] fieldName1 Name of the first column to extract the float from
[in] fieldName2 Name of the second column to extract the efloat from
[in] defaultValue The default to return in the case of an error
Returns
The parsed real or the default value if an error while parsing occured
Definition at line 1223 of file NIImporter_VISUM.cpp.
References getNamedFloat(), NamedColumnsParser::know(), and myLineParser.
getNamedNode() [1/2]
NBNode * NIImporter_VISUM::getNamedNode (const std::string & fieldName) private
Tries to get the node which name is stored in the given field.
If the field can not be parsed, an exception is thrown. Prints an error if the node could not be found, returning 0. Otherwise, if the field could be parsed and the node was found, this node is returned.
Parameters
[in] fieldName Name of the column to extract the node's name from
Returns
An already known node with the found name
Exceptions
OutOfBoundsException If the current data line has less entries than the node id's position
NumberFormatException If the node id is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1039 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), NBNetBuilder::getNodeCont(), myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), NBNodeCont::retrieve(), and WRITE_ERROR.
Referenced by getNamedNode(), parse_Connectors(), parse_EdgePolys(), parse_Edges(), parse_Lanes(), parse_LanesConnections(), parse_Turns(), and parse_TurnsToSignalGroups().
getNamedNode() [2/2]
NBNode * NIImporter_VISUM::getNamedNode (const std::string & fieldName1, const std::string & fieldName2) private
The same, but two different names for the field are allowed.
Parameters
[in] fieldName1 Name of the first column to extract the node's name from
[in] fieldName2 Name of the second column to extract the node's name from
Returns
An already known node with the found name
Exceptions
OutOfBoundsException If the current data line has less entries than the node id's position
NumberFormatException If the node id is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1050 of file NIImporter_VISUM.cpp.
References getNamedNode(), NamedColumnsParser::know(), and myLineParser.
getNamedString() [1/2]
std::string NIImporter_VISUM::getNamedString (const std::string & fieldName) private
Returns the value from the named column as a normalised string.
"Normalised" means herein that the leading '0' (zeros) are prunned.
Parameters
[in] fieldName Name of the column to extract the string from
Returns
The parsed, normalised string
Exceptions
OutOfBoundsException If the current data line has less entries than the string's position
NumberFormatException If the string is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1234 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), myLineParser, and NBHelpers::normalIDRepresentation().
Referenced by getNamedString(), and parse_TurnsToSignalGroups().
getNamedString() [2/2]
std::string NIImporter_VISUM::getNamedString (const std::string & fieldName1, const std::string & fieldName2) private
The same, but two different names for the field are allowed.
Parameters
[in] fieldName1 Name of the first column to extract the string from
[in] fieldName2 Name of the second column to extract the string from
Returns
The parsed, normalised string
Exceptions
OutOfBoundsException If the current data line has less entries than the string's position
NumberFormatException If the string is not numeric
UnknownElement If the named data field is not in the line
Definition at line 1240 of file NIImporter_VISUM.cpp.
References getNamedString(), NamedColumnsParser::know(), and myLineParser.
getReversedContinuating()
NBEdge * NIImporter_VISUM::getReversedContinuating (NBEdge * edge, NBNode * node) private
Returns the opposite direction of the given edge.
Because the opposite direction edge may be split, not the the plain opposite edge, the one which name is obtained by adding/removing the leading '-', is returned, but its continuation until the named node.
Parameters
[in] edge Name of the edge to find the opposite of
[in] node Name of the node the opposite edge's continuation must end at
Returns
The found opposite edge's continuation, 0 if not found
Definition at line 1082 of file NIImporter_VISUM.cpp.
References NBNetBuilder::getEdgeCont(), Named::getID(), getNamedEdgeContinuating(), myNetBuilder, and NBEdgeCont::retrieve().
Referenced by parse_Lanes(), and parse_LanesConnections().
getWeightedBool()
bool NIImporter_VISUM::getWeightedBool (const std::string & name) private
tries to get a bool which is possibly assigned to a certain modality
When the bool cannot be extracted using the given name, "IV" is appended to the begin of the name. Note that this function does not yet support public traffic.
Parameters
[in] name Name of the column to extract the bool from
Returns
The bool stored under the named column, or if not found the one from "(IV)"+name, or if not found false
Definition at line 1027 of file NIImporter_VISUM.cpp.
References TplConvert::_2bool(), NamedColumnsParser::get(), and myLineParser.
getWeightedFloat()
double NIImporter_VISUM::getWeightedFloat (const std::string & name) private
tries to get a double which is possibly assigned to a certain modality
When the double cannot be extracted using the given name, "(IV)" is appended to the begin of the name. Note that this function does not yet support public traffic.
Parameters
[in] name Name of the column to extract the real from
Returns
The real stored under the named column, or if not found the one from "(IV)"+name, or if not found -1
Definition at line 1015 of file NIImporter_VISUM.cpp.
References TplConvert::_2double(), NamedColumnsParser::get(), and myLineParser.
Referenced by parse_Connectors().
load()
void NIImporter_VISUM::load () protected
Parses the VISUM-network file storing the parsed structures within myNetBuilder.
At first, it is checked whether the file can be opened. A ProcessError is thrown if not. Otherwise, the file is scanned for occurences of db table begins. For each found db, its position within the file, and the column names are stored in the according TypeParser. After this, the sorted list of type parsers is one through and each found is used to parse the entries at the found positions using the found column names.
Exceptions
ProcessError If the file could not be opened
Definition at line 146 of file NIImporter_VISUM.cpp.
References NBNetBuilder::getEdgeCont(), LineReader::getPosition(), NBNetBuilder::getTLLogicCont(), LineReader::hasMore(), myCurrentID, myDistrictShapes, myFileName, myLineParser, myLineReader, myNetBuilder, mySingleDataParsers, myTLS, NamedColumnsParser::parseLine(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, LineReader::readLine(), NamedColumnsParser::reinit(), LineReader::reinit(), LineReader::setFile(), LineReader::setPos(), WRITE_ERROR, and WRITE_MESSAGE.
Referenced by loadNetwork().
loadNetwork()
void NIImporter_VISUM::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads network definition from the assigned option and stores it in the given network builder.
If the option "visum" is set, the file stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "visum" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 54 of file NIImporter_VISUM.cpp.
References OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getString(), OptionsCont::isSet(), and load().
Referenced by NILoader::load().
parse_AreaSubPartElement()
void NIImporter_VISUM::parse_AreaSubPartElement () private
Parses ABBZULSASIGNALGRUPPE/SIGNALGRUPPEZUABBIEGER.
Definition at line 846 of file NIImporter_VISUM.cpp.
References TplConvert::_2long(), NamedColumnsParser::get(), myCurrentID, myDistrictShapes, myEdges, myLineParser, myPoints, myShapeDistrictMap, mySubPartsAreas, PositionVector::reverse(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_Connectors()
void NIImporter_VISUM::parse_Connectors () private
Parses ANBINDUNG.
Definition at line 433 of file NIImporter_VISUM.cpp.
References NBDistrictCont::addSink(), NBDistrictCont::addSource(), buildDistrictNode(), NamedColumnsParser::get(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), getNamedNode(), OptionsCont::getOptions(), getWeightedFloat(), NBEdgeCont::insert(), NamedColumnsParser::know(), LANESPREAD_RIGHT, myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), NBEdgeCont::retrieve(), NBEdge::setAsMacroscopicConnector(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, WRITE_ERROR, and WRITE_WARNING.
Referenced by NIImporter_VISUM().
parse_Districts()
void NIImporter_VISUM::parse_Districts () private
Parses BEZIRK.
Definition at line 263 of file NIImporter_VISUM.cpp.
References TplConvert::_2long(), NamedColumnsParser::get(), NBNetBuilder::getDistrictCont(), getNamedFloat(), NBDistrictCont::insert(), NamedColumnsParser::know(), myCurrentID, myLineParser, myNetBuilder, myShapeDistrictMap, NBHelpers::normalIDRepresentation(), NBNetBuilder::transformCoordinate(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_EdgePolys()
void NIImporter_VISUM::parse_EdgePolys () private
Parses STRECKENPOLY.
Definition at line 583 of file NIImporter_VISUM.cpp.
References TplConvert::_2int(), NBEdge::addGeometryPoint(), checkNodes(), NamedColumnsParser::get(), NBNode::getConnectionTo(), Named::getID(), getNamedFloat(), getNamedNode(), OptionsCont::getOptions(), myLineParser, NBNetBuilder::transformCoordinate(), WRITE_ERROR, and WRITE_WARNING.
Referenced by NIImporter_VISUM().
parse_Edges()
void NIImporter_VISUM::parse_Edges () private
Parses STRECKE/STRECKEN.
Definition at line 307 of file NIImporter_VISUM.cpp.
References TplConvert::_2bool(), TplConvert::_2doubleSec(), TplConvert::_2intSec(), checkNodes(), NBCapacity2Lanes::get(), NamedColumnsParser::get(), NBNetBuilder::getEdgeCont(), getNamedNode(), NBTypeCont::getNumLanes(), OptionsCont::getOptions(), NBTypeCont::getPriority(), NBTypeCont::getSpeed(), NBNetBuilder::getTypeCont(), NBEdgeCont::insert(), NamedColumnsParser::know(), LANESPREAD_CENTER, LANESPREAD_RIGHT, myCapacity2Lanes, myCurrentID, myLineParser, myNetBuilder, myTouchedEdges, myUseVisumPrio, NBHelpers::normalIDRepresentation(), NBEdgeCont::retrieve(), NBEdge::setLaneSpreadFunction(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_Kante()
void NIImporter_VISUM::parse_Kante () private
Parses FLAECHENELEMENT.
Definition at line 413 of file NIImporter_VISUM.cpp.
References TplConvert::_2long(), NamedColumnsParser::get(), myEdges, and myLineParser.
Referenced by NIImporter_VISUM().
parse_Lanes()
void NIImporter_VISUM::parse_Lanes () private
Parses FAHRSTREIFEN.
Definition at line 627 of file NIImporter_VISUM.cpp.
References TplConvert::_2double(), TplConvert::_2int(), NamedColumnsParser::get(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::getLength(), getNamedEdge(), getNamedEdgeContinuating(), getNamedNode(), NBNetBuilder::getNodeCont(), NBEdge::getNumLanes(), NBNode::getOutgoingEdges(), getReversedContinuating(), NBEdge::getToNode(), NBNode::hasIncoming(), NBNode::hasOutgoing(), NBEdge::incLaneNo(), NBNodeCont::insert(), NamedColumnsParser::know(), myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), PositionVector::positionAtOffset(), NBEdgeCont::retrieve(), NBEdgeCont::splitAt(), toString(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_LanesConnections()
void NIImporter_VISUM::parse_LanesConnections () private
Parses FAHRSTREIFENABBIEGER.
Definition at line 919 of file NIImporter_VISUM.cpp.
References TplConvert::_2int(), NBEdge::addLane2LaneConnection(), NamedColumnsParser::get(), NBNetBuilder::getEdgeCont(), Named::getID(), getNamedEdgeContinuating(), getNamedNode(), NBEdge::getNumLanes(), getReversedContinuating(), NBNode::hasIncoming(), NBNode::hasOutgoing(), NBEdge::L2L_VALIDATED, myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), NBEdgeCont::retrieve(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_Nodes()
void NIImporter_VISUM::parse_Nodes () private
Parses KNOTEN.
Definition at line 244 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), getNamedFloat(), NBNetBuilder::getNodeCont(), NBNodeCont::insert(), myCurrentID, myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), NBNetBuilder::transformCoordinate(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_NodesToTrafficLights()
void NIImporter_VISUM::parse_NodesToTrafficLights () private
Parses KNOTENZULSA/SIGNALANLAGEZUKNOTEN.
Definition at line 768 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), NBNetBuilder::getNodeCont(), myLineParser, myNetBuilder, myTLS, and NBNodeCont::retrieve().
Referenced by NIImporter_VISUM().
parse_PartOfArea()
void NIImporter_VISUM::parse_PartOfArea () private
Parses FLAECHENELEMENT.
Definition at line 422 of file NIImporter_VISUM.cpp.
References TplConvert::_2long(), NamedColumnsParser::get(), myLineParser, and mySubPartsAreas.
Referenced by NIImporter_VISUM().
parse_Phases()
void NIImporter_VISUM::parse_Phases () private
Parses LSAPHASE/PHASE.
Definition at line 895 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), getNamedFloat(), NamedColumnsParser::know(), myLineParser, myTLS, and NBHelpers::normalIDRepresentation().
Referenced by NIImporter_VISUM().
parse_Point()
void NIImporter_VISUM::parse_Point () private
Parses PUNKT.
Definition at line 293 of file NIImporter_VISUM.cpp.
References TplConvert::_2double(), TplConvert::_2long(), NamedColumnsParser::get(), myLineParser, myPoints, toString(), NBNetBuilder::transformCoordinate(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_SignalGroups()
void NIImporter_VISUM::parse_SignalGroups () private
Parses LSASIGNALGRUPPE/SIGNALGRUPPE.
Definition at line 777 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), getNamedFloat(), NamedColumnsParser::know(), myCurrentID, myLineParser, myTLS, NBHelpers::normalIDRepresentation(), and WRITE_ERROR.
Referenced by NIImporter_VISUM().
parse_SignalGroupsToPhases()
void NIImporter_VISUM::parse_SignalGroupsToPhases () private
Parses LSASIGNALGRUPPEZULSAPHASE.
Definition at line 906 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), myLineParser, myTLS, NBHelpers::normalIDRepresentation(), and NIVisumTL::SignalGroup::phases().
Referenced by NIImporter_VISUM().
parse_TrafficLights()
void NIImporter_VISUM::parse_TrafficLights () private
Parses LSA/SIGNALANLAGE.
Definition at line 754 of file NIImporter_VISUM.cpp.
References TplConvert::_2bool(), NamedColumnsParser::get(), getNamedFloat(), NamedColumnsParser::know(), myCurrentID, myLineParser, myTLS, NBHelpers::normalIDRepresentation(), and TIME2STEPS.
Referenced by NIImporter_VISUM().
parse_Turns()
void NIImporter_VISUM::parse_Turns () private
Parses ABBIEGEBEZIEHUNG/ABBIEGER.
Definition at line 542 of file NIImporter_VISUM.cpp.
References NBEdge::addEdge2EdgeConnection(), NamedColumnsParser::get(), OptionsCont::getBool(), NBNode::getConnectionTo(), Named::getID(), getNamedNode(), OptionsCont::getOptions(), NamedColumnsParser::know(), myLineParser, myVSysTypes, and WRITE_WARNING.
Referenced by NIImporter_VISUM().
parse_TurnsToSignalGroups()
void NIImporter_VISUM::parse_TurnsToSignalGroups () private
Parses ABBZULSASIGNALGRUPPE/SIGNALGRUPPEZUABBIEGER.
Definition at line 793 of file NIImporter_VISUM.cpp.
References NIVisumTL::SignalGroup::connections(), getEdge(), NBNetBuilder::getEdgeCont(), Named::getID(), getNamedEdgeContinuating(), getNamedNode(), getNamedString(), NBNode::hasIncoming(), NBNode::hasOutgoing(), NamedColumnsParser::know(), myLineParser, myNetBuilder, myTLS, and NBEdgeCont::retrieve().
Referenced by NIImporter_VISUM().
parse_Types()
void NIImporter_VISUM::parse_Types () private
Parses STRECKENTYP.
Definition at line 225 of file NIImporter_VISUM.cpp.
References TplConvert::_2int(), NBCapacity2Lanes::get(), NamedColumnsParser::get(), getNamedFloat(), NBNetBuilder::getTypeCont(), NBTypeCont::insert(), NBTypeCont::markAsSet(), myCapacity2Lanes, myCurrentID, myLineParser, myNetBuilder, NBHelpers::normalIDRepresentation(), SUMO_ATTR_NUMLANES, SUMO_ATTR_ONEWAY, SUMO_ATTR_PRIORITY, SUMO_ATTR_SPEED, SVCAll, and NBEdge::UNSPECIFIED_WIDTH.
Referenced by NIImporter_VISUM().
parse_VSysTypes()
void NIImporter_VISUM::parse_VSysTypes () private
Parses VSYS.
Definition at line 217 of file NIImporter_VISUM.cpp.
References NamedColumnsParser::get(), NamedColumnsParser::know(), myLineParser, and myVSysTypes.
Referenced by NIImporter_VISUM().
Field Documentation
myCapacity2Lanes
NBCapacity2Lanes NIImporter_VISUM::myCapacity2Lanes private
The converter to compute the lane number of edges from their capacity.
Definition at line 476 of file NIImporter_VISUM.h.
Referenced by parse_Edges(), and parse_Types().
myCurrentID
std::string NIImporter_VISUM::myCurrentID private
The name of the currently parsed item used for error reporting.
Definition at line 500 of file NIImporter_VISUM.h.
Referenced by load(), parse_AreaSubPartElement(), parse_Districts(), parse_Edges(), parse_Nodes(), parse_SignalGroups(), parse_TrafficLights(), and parse_Types().
myDistrictShapes
std::map<NBDistrict*, PositionVector> NIImporter_VISUM::myDistrictShapes private
A temporary storage for district shapes as they are filled incrementally.
Definition at line 516 of file NIImporter_VISUM.h.
Referenced by load(), and parse_AreaSubPartElement().
myEdges
std::map<long long int, std::pair<long long int, long long int> > NIImporter_VISUM::myEdges private
A map of edge (not road, but "edge" in this case) ids to from/to-points.
Definition at line 507 of file NIImporter_VISUM.h.
Referenced by parse_AreaSubPartElement(), and parse_Kante().
myFileName
std::string NIImporter_VISUM::myFileName private
The name of the parsed file, for error reporting.
Definition at line 465 of file NIImporter_VISUM.h.
Referenced by load().
myLineParser
NamedColumnsParser NIImporter_VISUM::myLineParser private
the parser to parse the information from the data lines
the order of columns within the visum format seems to vary, so a named parser is needed
Definition at line 473 of file NIImporter_VISUM.h.
Referenced by getNamedEdge(), getNamedEdgeContinuating(), getNamedFloat(), getNamedNode(), getNamedString(), getWeightedBool(), getWeightedFloat(), load(), parse_AreaSubPartElement(), parse_Connectors(), parse_Districts(), parse_EdgePolys(), parse_Edges(), parse_Kante(), parse_Lanes(), parse_LanesConnections(), parse_Nodes(), parse_NodesToTrafficLights(), parse_PartOfArea(), parse_Phases(), parse_Point(), parse_SignalGroups(), parse_SignalGroupsToPhases(), parse_TrafficLights(), parse_Turns(), parse_TurnsToSignalGroups(), parse_Types(), and parse_VSysTypes().
myLineReader
LineReader NIImporter_VISUM::myLineReader private
The line reader to use to read from the file.
Definition at line 468 of file NIImporter_VISUM.h.
Referenced by load().
myNetBuilder
NBNetBuilder& NIImporter_VISUM::myNetBuilder private
The network builder to fill with loaded values.
Definition at line 462 of file NIImporter_VISUM.h.
Referenced by buildDistrictNode(), getNamedEdge(), getNamedEdgeContinuating(), getNamedNode(), getReversedContinuating(), load(), parse_Connectors(), parse_Districts(), parse_Edges(), parse_Lanes(), parse_LanesConnections(), parse_Nodes(), parse_NodesToTrafficLights(), parse_TurnsToSignalGroups(), and parse_Types().
myPoints
std::map<long long int, Position> NIImporter_VISUM::myPoints private
A map of point ids to positions.
Definition at line 504 of file NIImporter_VISUM.h.
Referenced by parse_AreaSubPartElement(), and parse_Point().
myShapeDistrictMap
std::map<long long int, NBDistrict*> NIImporter_VISUM::myShapeDistrictMap private
A map from district shape definition name to the district.
Definition at line 510 of file NIImporter_VISUM.h.
Referenced by parse_AreaSubPartElement(), and parse_Districts().
mySingleDataParsers
ParserVector NIImporter_VISUM::mySingleDataParsers private
List of known parsers.
Definition at line 486 of file NIImporter_VISUM.h.
Referenced by addParser(), and load().
mySubPartsAreas
std::map<long long int, std::vector<long long int> > NIImporter_VISUM::mySubPartsAreas private
A map from area parts to area ids.
Definition at line 513 of file NIImporter_VISUM.h.
Referenced by parse_AreaSubPartElement(), and parse_PartOfArea().
myTLS
NIVisumTL_Map NIImporter_VISUM::myTLS private
List of visum traffic lights.
Definition at line 491 of file NIImporter_VISUM.h.
Referenced by load(), parse_NodesToTrafficLights(), parse_Phases(), parse_SignalGroups(), parse_SignalGroupsToPhases(), parse_TrafficLights(), parse_TurnsToSignalGroups(), and ~NIImporter_VISUM().
myTouchedEdges
std::vector<std::string > NIImporter_VISUM::myTouchedEdges private
Already read edges.
Definition at line 494 of file NIImporter_VISUM.h.
Referenced by parse_Edges().
myUseVisumPrio
bool NIImporter_VISUM::myUseVisumPrio private
Information whether VISUM priority information shall be used.
Definition at line 497 of file NIImporter_VISUM.h.
Referenced by parse_Edges().
myVSysTypes
VSysTypeNames NIImporter_VISUM::myVSysTypes private
The used vsystypes.
Definition at line 481 of file NIImporter_VISUM.h.
Referenced by parse_Turns(), and parse_VSysTypes().
The documentation for this class was generated from the following files:
NIImporter_VISUM.h
NIImporter_VISUM.cpp