SUMO - Simulation of Urban MObility: MSPerson Class Reference
MSPerson Class Reference
#include <MSPerson.h>
Data Structures
class Influencer
Changes the wished person speed and position.
class MSPersonStage_Driving
class MSPersonStage_Walking
Public Types
typedef std::vector< MSTransportable::Stage * > MSTransportablePlan
the structure holding the plan of a transportable
enum StageType { WAITING_FOR_DEPART = 0, WAITING = 1, MOVING_WITHOUT_VEHICLE = 2, DRIVING = 3 }
Public Member Functions
void appendStage (Stage *stage, int next=-1)
Appends the given stage to the current plan.
virtual double getAngle () const
return the current angle of the transportable
const MSEdge * getArrivalEdge () const
returns the final arrival edge
double getArrivalPos () const
returns the final arrival pos
PositionVector getBoundingBox () const
return the bounding box of the person
MSTransportable::Stage * getCurrentStage () const
Return the current stage.
std::string getCurrentStageDescription () const
Returns the current stage description as a string.
StageType getCurrentStageType () const
the current stage type of the transportable
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
virtual double getEdgePos () const
Return the position on the edge.
ConstMSEdgeVector getEdges (int next) const
Return the edges of the nth next stage.
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the id of the transportable
Influencer & getInfluencer ()
Returns the velocity/lane influencer.
const Influencer * getInfluencer () const
const MSEdge & getNextDestination () const
Returns the destination after the current destination.
const std::string & getNextEdge () const
return the list of internal edges if this person is walking and the pedestrian model allows it
const MSEdge * getNextEdgePtr () const
returns the next edge ptr if this person is walking and the pedestrian model allows it
int getNumRemainingStages () const
Return the number of remaining stages (including the current)
int getNumStages () const
Return the total number stages in this persons plan.
const SUMOVehicleParameter & getParameter () const
virtual Position getPosition () const
Return the Network coordinate of the transportable.
MSVehicleType & getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
virtual double getSpeed () const
the current speed of the transportable
double getSpeedFactor () const
the current speed factor of the transportable (where applicable)
StageType getStageType (int next) const
the stage type for the nth next stage
SUMOVehicle * getVehicle () const
The vehicle associated with this transportable.
const MSVehicleType & getVehicleType () const
virtual double getWaitingSeconds () const
the time this transportable spent waiting in seconds
bool hasInfluencer () const
virtual bool isSelected () const
whether this person is selected in the GUI
bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
MSPerson (const SUMOVehicleParameter *pars, MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan, const double speedFactor)
constructor
bool proceed (MSNet *net, SUMOTime time)
void removeStage (int next)
removes the nth next stage
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (ConstMSEdgeVector &newEdges)
set new walk
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs depart time of the current stage
void setRemoteState (Position xyPos)
sets position outside the road network
void setSpeed (double speed)
sets the walking speed (ignored in other stages)
virtual void tripInfoOutput (OutputDevice &os, MSTransportable *transportable) const
Called on writing tripinfo output.
virtual ~MSPerson ()
destructor
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the transportable
MSTransportablePlan * myPlan
the plan of the transportable
MSTransportablePlan::iterator myStep
the iterator over the route
MSVehicleType * myVType
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
bool myWriteEvents
Whether events shall be written.
Static Protected Attributes
static const double ROADSIDE_OFFSET
the offset for computing positions when standing at an edge
Private Member Functions
MSPerson (const MSPerson &)
Invalidated copy constructor.
MSPerson & operator= (const MSPerson &)
Invalidated assignment operator.
Private Attributes
const double myChosenSpeedFactor
Influencer * myInfluencer
An instance of a speed/position influencing instance; built in "getInfluencer".
Detailed Description
The class holds a simulated person together with her movement stages
Definition at line 69 of file MSPerson.h.
Member Typedef Documentation
MSTransportablePlan
typedef std::vector<MSTransportable::Stage*> MSTransportable::MSTransportablePlan inherited
the structure holding the plan of a transportable
Definition at line 387 of file MSTransportable.h.
Member Enumeration Documentation
StageType
enum MSTransportable::StageType inherited
Enumerator
WAITING_FOR_DEPART
WAITING
MOVING_WITHOUT_VEHICLE
DRIVING
Definition at line 64 of file MSTransportable.h.
Constructor & Destructor Documentation
MSPerson() [1/2]
MSPerson::MSPerson (const SUMOVehicleParameter * pars, MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan, const double speedFactor)
constructor
Definition at line 397 of file MSPerson.cpp.
~MSPerson()
MSPerson::~MSPerson () virtual
destructor
Definition at line 403 of file MSPerson.cpp.
MSPerson() [2/2]
MSPerson::MSPerson (const MSPerson &) private
Invalidated copy constructor.
Member Function Documentation
appendStage()
void MSTransportable::appendStage (Stage * stage, int next = -1) inherited
Appends the given stage to the current plan.
Definition at line 466 of file MSTransportable.cpp.
References MSTransportable::getID(), MSTransportable::myPlan, MSTransportable::myStep, and toString().
Referenced by libsumo::Person::appendDrivingStage(), libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), MSTransportable::getVehicle(), MSTransportable::removeStage(), and reroute().
getAngle()
double MSTransportable::getAngle () const virtual inherited
return the current angle of the transportable
Reimplemented in GUIContainer.
Definition at line 440 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIPerson::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), GUIContainer::getAngle(), MSTransportable::getBoundingBox(), GUIPerson::getNaviDegree(), GUIPerson::setFunctionalColor(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
getArrivalEdge()
const MSEdge* MSTransportable::getArrivalEdge () const inline inherited
returns the final arrival edge
Definition at line 535 of file MSTransportable.h.
References MSTransportable::getBoundingBox(), MSTransportable::getSingularType(), MSTransportable::myPlan, and MSTransportable::replaceVehicleType().
Referenced by libsumo::Person::appendWaitingStage(), and libsumo::Person::rerouteTraveltime().
getArrivalPos()
double MSTransportable::getArrivalPos () const inline inherited
returns the final arrival pos
Definition at line 530 of file MSTransportable.h.
References MSTransportable::myPlan.
Referenced by libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), reroute(), and libsumo::Person::rerouteTraveltime().
getBoundingBox()
PositionVector MSTransportable::getBoundingBox () const inherited
return the bounding box of the person
Definition at line 531 of file MSTransportable.cpp.
References PositionVector::append(), MSTransportable::getAngle(), MSVehicleType::getLength(), MSTransportable::getPosition(), MSTransportable::getVehicleType(), PositionVector::move2side(), POSITION_EPS, and PositionVector::reverse().
Referenced by MSTransportable::getArrivalEdge().
getCurrentStage()
MSTransportable::Stage* MSTransportable::getCurrentStage () const inline inherited
Return the current stage.
Definition at line 474 of file MSTransportable.h.
References MSTransportable::myStep.
Referenced by MSTransportableControl::abortWaitingForVehicle(), GUIPerson::drawAction_drawWalkingareaPath(), GUIPerson::drawGLAdditional(), libsumo::Person::moveToXY(), MSEdge::transportable_by_position_sorter::operator()(), and MSPerson::Influencer::postProcessRemoteControl().
getCurrentStageDescription()
std::string MSTransportable::getCurrentStageDescription () const inline inherited
Returns the current stage description as a string.
Definition at line 469 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), libsumo::Person::moveTo(), libsumo::Person::moveToXY(), and MSXMLRawOut::writeTransportable().
getCurrentStageType()
StageType MSTransportable::getCurrentStageType () const inline inherited
the current stage type of the transportable
Definition at line 457 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPerson::drawGLAdditional(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), getNextEdgePtr(), GUIContainer::getPosition(), and libsumo::Person::rerouteTraveltime().
getDesiredDepart()
SUMOTime MSTransportable::getDesiredDepart () const inherited
Returns the desired departure time.
Definition at line 420 of file MSTransportable.cpp.
References SUMOVehicleParameter::depart, and MSTransportable::myParameter.
Referenced by MSTransportable::getVehicleType(), MSContainer::routeOutput(), MSContainer::tripInfoOutput(), and tripInfoOutput().
getDestination()
const MSEdge& MSTransportable::getDestination () const inline inherited
Returns the current destination.
Definition at line 417 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), MSDevice_Transportable::notifyLeave(), and MSDevice_Transportable::notifyMove().
getEdge()
const MSEdge* MSTransportable::getEdge () const inline inherited
Returns the current edge.
Definition at line 427 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUIContainer::getPosition(), libsumo::Person::getRoadID(), libsumo::Person::moveToXY(), MSTransportable::removeStage(), and libsumo::Person::rerouteTraveltime().
getEdgePos()
double MSTransportable::getEdgePos () const virtual inherited
Return the position on the edge.
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 430 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIContainer::getEdgePos(), GUIPerson::getEdgePos(), libsumo::Person::getLanePosition(), libsumo::Person::moveToXY(), MSTransportable::removeStage(), reroute(), libsumo::Person::rerouteTraveltime(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
getEdges()
ConstMSEdgeVector MSTransportable::getEdges (int next) const inline inherited
Return the edges of the nth next stage.
Definition at line 479 of file MSTransportable.h.
References MSTransportable::Stage::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::myPlan, MSTransportable::myStep, MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
Referenced by libsumo::Person::getEdges(), and libsumo::Person::rerouteTraveltime().
getFromEdge()
const MSEdge* MSTransportable::getFromEdge () const inline inherited
Returns the departure edge.
Definition at line 432 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getPosition(), MSTransportable::Stage::getSpeed(), and MSTransportable::getWaitingSeconds().
Referenced by GUIContainer::getParameterWindow(), and GUIPerson::getParameterWindow().
getID()
const std::string & MSTransportable::getID () const inherited
returns the id of the transportable
Definition at line 415 of file MSTransportable.cpp.
References SUMOVehicleParameter::id, and MSTransportable::myParameter.
Referenced by MSTransportableControl::abortWaitingForVehicle(), MSPModel_Striping::add(), MSBaseVehicle::addContainer(), MSVehicle::addContainer(), MSBaseVehicle::addPerson(), MSVehicle::addPerson(), MSTransportable::appendStage(), libsumo::Person::appendWalkingStage(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSTransportableControl::erase(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), MSTransportable::getSingularType(), MSPedestrianPushButton::isActiveForEdge(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), MSDevice_Transportable::notifyLeave(), MSPModel_Striping::by_xpos_sorter::operator()(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPModel_Striping::PState::PState(), reroute(), MSContainer::MSContainerStage_Driving::routeOutput(), MSContainer::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), libsumo::Helper::setRemoteControlled(), MSContainer::tripInfoOutput(), tripInfoOutput(), MSPModel_Striping::PState::walk(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
getInfluencer() [1/2]
MSPerson::Influencer & MSPerson::getInfluencer ()
Returns the velocity/lane influencer.
If no influencer was existing before, one is built, first
Returns
Reference to this vehicle's speed influencer
Definition at line 513 of file MSPerson.cpp.
References myInfluencer.
Referenced by libsumo::Helper::setRemoteControlled().
getInfluencer() [2/2]
const MSPerson::Influencer * MSPerson::getInfluencer () const
Definition at line 522 of file MSPerson.cpp.
References myInfluencer.
getNextDestination()
const MSEdge& MSTransportable::getNextDestination () const inline inherited
Returns the destination after the current destination.
Definition at line 422 of file MSTransportable.h.
References MSTransportable::myStep.
getNextEdge()
const std::string & MSPerson::getNextEdge () const
return the list of internal edges if this person is walking and the pedestrian model allows it
Definition at line 437 of file MSPerson.cpp.
References StringUtils::emptyString, Named::getID(), and getNextEdgePtr().
Referenced by libsumo::Person::getNextEdge().
getNextEdgePtr()
const MSEdge * MSPerson::getNextEdgePtr () const
returns the next edge ptr if this person is walking and the pedestrian model allows it
Definition at line 456 of file MSPerson.cpp.
References MSTransportable::getCurrentStageType(), PedestrianState::getNextEdge(), MSPerson::MSPersonStage_Walking::getPedestrianState(), and MSTransportable::MOVING_WITHOUT_VEHICLE.
Referenced by getNextEdge(), and MSPedestrianPushButton::isActiveForEdge().
getNumRemainingStages()
int MSTransportable::getNumRemainingStages () const inherited
Return the number of remaining stages (including the current)
Definition at line 456 of file MSTransportable.cpp.
References MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by libsumo::Person::getEdges(), MSTransportable::getEdges(), libsumo::Person::getRemainingStages(), libsumo::Person::getStage(), libsumo::Person::removeStage(), reroute(), and libsumo::Person::rerouteTraveltime().
getNumStages()
int MSTransportable::getNumStages () const inherited
Return the total number stages in this persons plan.
Definition at line 461 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by libsumo::Person::getEdges(), MSTransportable::getEdges(), and libsumo::Person::getStage().
getParameter()
const SUMOVehicleParameter& MSTransportable::getParameter () const inline inherited
Definition at line 402 of file MSTransportable.h.
References MSTransportable::myParameter.
Referenced by MSTransportableControl::add(), libsumo::Person::getColor(), libsumo::Person::getParameter(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUIContainer::setFunctionalColor(), GUIPerson::setFunctionalColor(), and libsumo::Person::setParameter().
getPosition()
Position MSTransportable::getPosition () const virtual inherited
Return the Network coordinate of the transportable.
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 435 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by MSTransportable::getBoundingBox(), MSLink::getLeaderInfo(), libsumo::Person::getPosition(), TraCIServerAPI_Person::getPosition(), GUIContainer::getPosition(), GUIPerson::getPosition(), libsumo::Person::moveToXY(), and MSFCDExport::writeTransportable().
getSingularType()
MSVehicleType & MSTransportable::getSingularType () inherited
Replaces the current vehicle type with a new one used by this vehicle only.
If the currently used vehicle type is already marked as being used by this vehicle only, no new type is created.
Returns
The new modifiable vehicle type
See also
MSTransportable::myVType
Definition at line 520 of file MSTransportable.cpp.
References MSVehicleType::buildSingularType(), MSVehicleType::getID(), MSTransportable::getID(), MSVehicleType::isVehicleSpecific(), MSTransportable::myVType, and MSTransportable::replaceVehicleType().
Referenced by MSTransportable::getArrivalEdge(), and libsumo::Person::getSingularVType().
getSpeed()
double MSTransportable::getSpeed () const virtual inherited
the current speed of the transportable
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 450 of file MSTransportable.cpp.
Referenced by libsumo::Person::getSpeed(), GUIContainer::getSpeed(), GUIPerson::getSpeed(), and MSFCDExport::writeTransportable().
getSpeedFactor()
double MSPerson::getSpeedFactor () const inline virtual
the current speed factor of the transportable (where applicable)
Reimplemented from MSTransportable.
Definition at line 302 of file MSPerson.h.
References myChosenSpeedFactor, and reroute().
Referenced by MSPerson::MSPersonStage_Walking::getMaxSpeed(), and GUIPerson::getParameterWindow().
getStageType()
StageType MSTransportable::getStageType (int next) const inline inherited
the stage type for the nth next stage
Definition at line 462 of file MSTransportable.h.
References MSTransportable::Stage::getStageType(), MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by libsumo::Person::getStage(), libsumo::Person::moveToXY(), and MSPerson::Influencer::postProcessRemoteControl().
getVehicle()
SUMOVehicle* MSTransportable::getVehicle () const inline inherited
The vehicle associated with this transportable.
Definition at line 516 of file MSTransportable.h.
References MSTransportable::appendStage(), MSTransportable::removeStage(), and MSTransportable::Stage::setSpeed().
Referenced by libsumo::Person::getVehicle().
getVehicleType()
const MSVehicleType& MSTransportable::getVehicleType () const inline inherited
Definition at line 406 of file MSTransportable.h.
References MSTransportable::getDesiredDepart(), MSTransportable::myVType, and MSTransportable::Stage::setDeparted().
Referenced by MSStoppingPlace::addTransportable(), libsumo::Person::appendWalkingStage(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIContainer::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), MSTransportable::getBoundingBox(), GUIPerson::getCenteringBoundary(), MSPModel_Striping::PState::getImpatience(), MSLink::getLeaderInfo(), MSPModel_Striping::PState::getLength(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSPModel_Striping::PState::getMinGap(), MSPModel_Striping::getNextLaneObstacles(), libsumo::Person::getTypeID(), MSPModel_Striping::PState::ignoreRed(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Person::moveToXY(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::PState::otherStripe(), MSStoppingPlace::removeTransportable(), reroute(), libsumo::Person::rerouteTraveltime(), routeOutput(), GUIContainer::setFunctionalColor(), and GUIPerson::setFunctionalColor().
getWaitingSeconds()
double MSTransportable::getWaitingSeconds () const virtual inherited
the time this transportable spent waiting in seconds
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 445 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and STEPS2TIME.
Referenced by MSTransportable::getFromEdge(), GUIContainer::getWaitingSeconds(), GUIPerson::getWaitingSeconds(), libsumo::Person::getWaitingTime(), and MSPedestrianPushButton::isActiveForEdge().
hasInfluencer()
bool MSPerson::hasInfluencer () const inline
Definition at line 359 of file MSPerson.h.
References myInfluencer, and setRemoteState().
isSelected()
virtual bool MSPerson::isSelected () const inline virtual
whether this person is selected in the GUI
Reimplemented in GUIPerson.
Definition at line 298 of file MSPerson.h.
isWaiting4Vehicle()
bool MSTransportable::isWaiting4Vehicle () const inline inherited
Whether the transportable waits for a vehicle.
Definition at line 511 of file MSTransportable.h.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIContainer::getColorValue(), and GUIPerson::getColorValue().
isWaitingFor()
bool MSTransportable::isWaitingFor (const std::string & line) const inline inherited
Whether the transportable waits for a vehicle of the line specified.
Definition at line 506 of file MSTransportable.h.
operator=()
MSPerson& MSPerson::operator= (const MSPerson &) private
Invalidated assignment operator.
proceed()
bool MSPerson::proceed (MSNet * net, SUMOTime time) virtual
Implements MSTransportable.
Definition at line 408 of file MSPerson.cpp.
References MSTransportable::Stage::getEdge(), MSTransportable::myPlan, MSTransportable::myStep, MSEdge::removePerson(), and MSTransportable::Stage::setArrived().
Referenced by MSPerson::MSPersonStage_Walking::moveToNextEdge().
removeStage()
void MSTransportable::removeStage (int next) inherited
removes the nth next stage
Definition at line 482 of file MSTransportable.cpp.
References MSTransportable::appendStage(), MSTransportable::getEdge(), MSTransportable::getEdgePos(), MSNet::getInstance(), MSTransportable::myPlan, MSTransportable::myStep, and MSTransportable::proceed().
Referenced by MSTransportable::getVehicle(), libsumo::Person::removeStage(), and reroute().
replaceVehicleType()
void MSTransportable::replaceVehicleType (MSVehicleType * type) inherited
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myVType".
Parameters
[in] type The new vehicle type
See also
MSTransportable::myVType
Definition at line 511 of file MSTransportable.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleType::isVehicleSpecific(), MSTransportable::myVType, and MSVehicleControl::removeVType().
Referenced by MSTransportable::getArrivalEdge(), MSTransportable::getSingularType(), and libsumo::Person::setType().
reroute()
void MSPerson::reroute (ConstMSEdgeVector & newEdges)
set new walk
Definition at line 494 of file MSPerson.cpp.
References MSTransportable::appendStage(), MSTransportable::getArrivalPos(), MSTransportable::getEdgePos(), MSTransportable::getID(), MSVehicleType::getMaxSpeed(), MSTransportable::getNumRemainingStages(), MSTransportable::getVehicleType(), and MSTransportable::removeStage().
Referenced by getSpeedFactor(), and libsumo::Person::rerouteTraveltime().
routeOutput()
void MSPerson::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 479 of file MSPerson.cpp.
References OutputDevice::closeTag(), DEFAULT_PEDTYPE_ID, MSVehicleType::getID(), MSNet::getInstance(), OptionsCont::getOptions(), MSTransportable::getVehicleType(), OutputDevice::lf(), MSTransportable::myParameter, MSTransportable::myPlan, MSTransportable::myStep, SUMO_TAG_PERSON, time2string(), SUMOVehicleParameter::write(), and OutputDevice::writeAttr().
setDeparted()
void MSTransportable::setDeparted (SUMOTime now) inherited
logs depart time of the current stage
Definition at line 425 of file MSTransportable.cpp.
Referenced by MSTransportableControl::abortWaitingForVehicle().
setRemoteState()
void MSPerson::setRemoteState (Position xyPos)
sets position outside the road network
Referenced by hasInfluencer().
setSpeed()
void MSTransportable::setSpeed (double speed) inherited
sets the walking speed (ignored in other stages)
Definition at line 503 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by libsumo::Person::setSpeed().
tripInfoOutput()
void MSPerson::tripInfoOutput (OutputDevice & os, MSTransportable * transportable) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 469 of file MSPerson.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::myPlan, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Field Documentation
myChosenSpeedFactor
const double MSPerson::myChosenSpeedFactor private
Definition at line 372 of file MSPerson.h.
Referenced by getSpeedFactor().
myInfluencer
Influencer* MSPerson::myInfluencer private
An instance of a speed/position influencing instance; built in "getInfluencer".
Definition at line 368 of file MSPerson.h.
Referenced by getInfluencer(), and hasInfluencer().
myParameter
const SUMOVehicleParameter* MSTransportable::myParameter protected inherited
the plan of the transportable
Definition at line 568 of file MSTransportable.h.
Referenced by MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::getParameter(), routeOutput(), and MSTransportable::~MSTransportable().
myPlan
MSTransportablePlan* MSTransportable::myPlan protected inherited
the plan of the transportable
Definition at line 578 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getArrivalEdge(), MSTransportable::getArrivalPos(), MSTransportable::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), MSContainer::proceed(), proceed(), MSTransportable::removeStage(), MSContainer::routeOutput(), routeOutput(), MSTransportable::setSpeed(), MSContainer::tripInfoOutput(), tripInfoOutput(), and MSTransportable::~MSTransportable().
myStep
MSTransportablePlan::iterator MSTransportable::myStep protected inherited
the iterator over the route
Definition at line 581 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getCurrentStage(), MSTransportable::getEdges(), MSTransportable::getNextDestination(), MSTransportable::getNumRemainingStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), MSContainer::proceed(), proceed(), MSTransportable::removeStage(), MSContainer::routeOutput(), and routeOutput().
myVType
MSVehicleType* MSTransportable::myVType protected inherited
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
Definition at line 572 of file MSTransportable.h.
Referenced by MSTransportable::getSingularType(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), MSTransportable::getVehicleType(), MSTransportable::replaceVehicleType(), and MSTransportable::~MSTransportable().
myWriteEvents
bool MSTransportable::myWriteEvents protected inherited
Whether events shall be written.
Definition at line 575 of file MSTransportable.h.
ROADSIDE_OFFSET
const double MSTransportable::ROADSIDE_OFFSET static protected inherited
the offset for computing positions when standing at an edge
Definition at line 565 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getPosition(), and MSTransportable::Stage_Driving::getPosition().
The documentation for this class was generated from the following files:
MSPerson.h
MSPerson.cpp