SUMO - Simulation of Urban MObility: GNEPolygonFrame::ShapeAttributes Class Reference
GNEPolygonFrame::ShapeAttributes Class Reference
#include <GNEPolygonFrame.h>
Public Member Functions
void addAttribute (SumoXMLTag shapeTag, SumoXMLAttr ShapeAttributeSingle)
add attribute
bool areValuesValid () const
check if parameters of attributes are valid
void clearAttributes ()
clear attributes
std::map< SumoXMLAttr, std::string > getAttributesAndValues () const
get attributes and their values
int getNumberOfAddedAttributes () const
get number of added attributes
void hideShapeParameters ()
hide group box
ShapeAttributes (GNEViewNet *viewNet, FXComposite *parent)
FOX-declaration.
void showShapeParameters ()
show group box
void showWarningMessage (std::string extra="") const
show warning message with information about non-valid attributes
~ShapeAttributes ()
destructor
FOX-callbacks
Called when help button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Protected Member Functions
ShapeAttributes ()
FOX needs this.
Private Attributes
FXButton * helpShape
button for help
int maxNumberOfListParameters
max number of parameters (Defined in constructor)
int maxNumberOfParameters
max number of parameters (Defined in constructor)
int myIndexParameter
Index for myVectorOfsingleShapeParameter.
int myIndexParameterList
index for myIndexParameterList
SumoXMLTag myShapeTag
current shape tag
std::vector< ShapeAttributeSingle * > myVectorOfsingleShapeParameter
vector with the shape parameters
GNEViewNet * myViewNet
pointer to viewNet
Detailed Description
Definition at line 157 of file GNEPolygonFrame.h.
Constructor & Destructor Documentation
ShapeAttributes() [1/2]
GNEPolygonFrame::ShapeAttributes::ShapeAttributes (GNEViewNet * viewNet, FXComposite * parent)
FOX-declaration.
constructor
Definition at line 642 of file GNEPolygonFrame.cpp.
References GUIDesignButtonRectangular, helpShape, maxNumberOfParameters, MID_HELP, and myVectorOfsingleShapeParameter.
~ShapeAttributes()
GNEPolygonFrame::ShapeAttributes::~ShapeAttributes ()
destructor
Definition at line 660 of file GNEPolygonFrame.cpp.
ShapeAttributes() [2/2]
GNEPolygonFrame::ShapeAttributes::ShapeAttributes () inline protected
FOX needs this.
Definition at line 200 of file GNEPolygonFrame.h.
Member Function Documentation
addAttribute()
void GNEPolygonFrame::ShapeAttributes::addAttribute (SumoXMLTag shapeTag, SumoXMLAttr ShapeAttributeSingle)
add attribute
Definition at line 678 of file GNEPolygonFrame.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), maxNumberOfParameters, myIndexParameter, myShapeTag, myVectorOfsingleShapeParameter, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by GNEPolygonFrame::setParametersOfShape().
areValuesValid()
bool GNEPolygonFrame::ShapeAttributes::areValuesValid () const
check if parameters of attributes are valid
Definition at line 757 of file GNEPolygonFrame.cpp.
References myIndexParameter, and myVectorOfsingleShapeParameter.
Referenced by GNEPolygonFrame::buildPoly(), and GNEPolygonFrame::processClick().
clearAttributes()
void GNEPolygonFrame::ShapeAttributes::clearAttributes ()
clear attributes
Definition at line 665 of file GNEPolygonFrame.cpp.
References maxNumberOfParameters, myIndexParameter, myIndexParameterList, and myVectorOfsingleShapeParameter.
Referenced by GNEPolygonFrame::setParametersOfShape().
getAttributesAndValues()
std::map< SumoXMLAttr, std::string > GNEPolygonFrame::ShapeAttributes::getAttributesAndValues () const
get attributes and their values
Definition at line 719 of file GNEPolygonFrame.cpp.
References myIndexParameter, and myVectorOfsingleShapeParameter.
Referenced by GNEPolygonFrame::buildPoly(), and GNEPolygonFrame::processClick().
getNumberOfAddedAttributes()
int GNEPolygonFrame::ShapeAttributes::getNumberOfAddedAttributes () const
get number of added attributes
Definition at line 770 of file GNEPolygonFrame.cpp.
References myIndexParameter, and myIndexParameterList.
Referenced by GNEPolygonFrame::setParametersOfShape().
hideShapeParameters()
void GNEPolygonFrame::ShapeAttributes::hideShapeParameters ()
hide group box
Definition at line 713 of file GNEPolygonFrame.cpp.
References GNEFrame::hide().
Referenced by GNEPolygonFrame::setParametersOfShape().
onCmdHelp()
long GNEPolygonFrame::ShapeAttributes::onCmdHelp (FXObject * , FXSelector , void *)
Definition at line 776 of file GNEPolygonFrame.cpp.
References GNEAttributeCarrier::getDefinition(), GUIIconSubSys::getIcon(), GUIDesignButtonOK, GUIDesignDialogBox, ICON_ACCEPT, GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), MID_TABLE, myIndexParameter, myIndexParameterList, myShapeTag, myVectorOfsingleShapeParameter, and toString().
showShapeParameters()
void GNEPolygonFrame::ShapeAttributes::showShapeParameters ()
show group box
Definition at line 706 of file GNEPolygonFrame.cpp.
References GNEPolygonFrame::show().
Referenced by GNEPolygonFrame::setParametersOfShape().
showWarningMessage()
void GNEPolygonFrame::ShapeAttributes::showWarningMessage (std::string extra = "") const
show warning message with information about non-valid attributes
Definition at line 730 of file GNEPolygonFrame.cpp.
References OptionsCont::getOptions(), myIndexParameter, myShapeTag, myVectorOfsingleShapeParameter, myViewNet, GNEViewNet::setStatusBarText(), toString(), and WRITE_WARNING.
Referenced by GNEPolygonFrame::buildPoly(), and GNEPolygonFrame::processClick().
Field Documentation
helpShape
FXButton* GNEPolygonFrame::ShapeAttributes::helpShape private
button for help
Definition at line 225 of file GNEPolygonFrame.h.
Referenced by ShapeAttributes().
maxNumberOfListParameters
int GNEPolygonFrame::ShapeAttributes::maxNumberOfListParameters private
max number of parameters (Defined in constructor)
Definition at line 222 of file GNEPolygonFrame.h.
maxNumberOfParameters
int GNEPolygonFrame::ShapeAttributes::maxNumberOfParameters private
max number of parameters (Defined in constructor)
Definition at line 219 of file GNEPolygonFrame.h.
Referenced by addAttribute(), clearAttributes(), and ShapeAttributes().
myIndexParameter
int GNEPolygonFrame::ShapeAttributes::myIndexParameter private
Index for myVectorOfsingleShapeParameter.
Definition at line 213 of file GNEPolygonFrame.h.
Referenced by addAttribute(), areValuesValid(), clearAttributes(), getAttributesAndValues(), getNumberOfAddedAttributes(), onCmdHelp(), and showWarningMessage().
myIndexParameterList
int GNEPolygonFrame::ShapeAttributes::myIndexParameterList private
index for myIndexParameterList
Definition at line 216 of file GNEPolygonFrame.h.
Referenced by clearAttributes(), getNumberOfAddedAttributes(), and onCmdHelp().
myShapeTag
SumoXMLTag GNEPolygonFrame::ShapeAttributes::myShapeTag private
current shape tag
Definition at line 207 of file GNEPolygonFrame.h.
Referenced by addAttribute(), onCmdHelp(), and showWarningMessage().
myVectorOfsingleShapeParameter
std::vector<ShapeAttributeSingle*> GNEPolygonFrame::ShapeAttributes::myVectorOfsingleShapeParameter private
vector with the shape parameters
Definition at line 210 of file GNEPolygonFrame.h.
Referenced by addAttribute(), areValuesValid(), clearAttributes(), getAttributesAndValues(), onCmdHelp(), ShapeAttributes(), and showWarningMessage().
myViewNet
GNEViewNet* GNEPolygonFrame::ShapeAttributes::myViewNet private
pointer to viewNet
Definition at line 204 of file GNEPolygonFrame.h.
Referenced by showWarningMessage().
The documentation for this class was generated from the following files:
GNEPolygonFrame.h
GNEPolygonFrame.cpp