SUMO - Simulation of Urban MObility: NBConnection Class Reference
NBConnection Class Reference
#include <NBConnection.h>
Public Member Functions
bool check (const NBEdgeCont &ec)
checks whether the edges are still valid
NBEdge * getFrom () const
returns the from-edge (start of the connection)
int getFromLane () const
returns the from-lane
std::string getID () const
returns the id of the connection (!!! not really pretty)
int getTLIndex () const
returns the index within the controlling tls or InvalidTLIndex if this link is unontrolled
NBEdge * getTo () const
returns the to-edge (end of the connection)
int getToLane () const
returns the to-lane
NBConnection (NBEdge *from, NBEdge *to)
Constructor.
NBConnection (NBEdge *from, int fromLane, NBEdge *to, int toLane, int tlIndex=InvalidTlIndex)
Constructor.
NBConnection (const std::string &fromID, NBEdge *from, const std::string &toID, NBEdge *to)
Constructor.
NBConnection (const NBConnection &c)
Constructor.
bool operator!= (const NBConnection &c) const
Comparison operator.
bool operator== (const NBConnection &c) const
Comparison operator.
bool replaceFrom (NBEdge *which, NBEdge *by)
replaces the from-edge by the one given
bool replaceFrom (NBEdge *which, int whichLane, NBEdge *by, int byLane)
replaces the from-edge by the one given
bool replaceTo (NBEdge *which, NBEdge *by)
replaces the to-edge by the one given
bool replaceTo (NBEdge *which, int whichLane, NBEdge *by, int byLane)
replaces the to-edge by the one given
void setTLIndex (int tlIndex)
void shiftLaneIndex (NBEdge *edge, int offset)
patches lane indices refering to the given edge
virtual ~NBConnection ()
Destructor.
Static Public Attributes
static const NBConnection InvalidConnection
static const int InvalidTlIndex = -1
Private Member Functions
NBEdge * checkFrom (const NBEdgeCont &ec)
Checks whether the from-edge is still valid.
NBEdge * checkTo (const NBEdgeCont &ec)
Checks whether the to-edge is still valid.
Private Attributes
NBEdge * myFrom
The from- and the to-edges.
std::string myFromID
The names of both edges, needed for verification of validity.
int myFromLane
The lanes; may be -1 if no certain lane was specified.
int myTlIndex
NBEdge * myTo
std::string myToID
int myToLane
Friends
bool operator< (const NBConnection &c1, const NBConnection &c2)
Compares both connections in order to allow sorting.
std::ostream & operator<< (std::ostream &os, const NBConnection &c)
Output operator.
Detailed Description
Definition at line 50 of file NBConnection.h.
Constructor & Destructor Documentation
NBConnection() [1/4]
NBConnection::NBConnection (NBEdge * from, NBEdge * to)
Constructor.
Definition at line 49 of file NBConnection.cpp.
NBConnection() [2/4]
NBConnection::NBConnection (NBEdge * from, int fromLane, NBEdge * to, int toLane, int tlIndex = InvalidTlIndex)
Constructor.
Definition at line 66 of file NBConnection.cpp.
References Named::getID(), myFromID, and myToID.
NBConnection() [3/4]
NBConnection::NBConnection (const std::string & fromID, NBEdge * from, const std::string & toID, NBEdge * to)
Constructor.
Definition at line 57 of file NBConnection.cpp.
NBConnection() [4/4]
NBConnection::NBConnection (const NBConnection & c)
Constructor.
Definition at line 83 of file NBConnection.cpp.
~NBConnection()
NBConnection::~NBConnection () virtual
Destructor.
Definition at line 80 of file NBConnection.cpp.
Member Function Documentation
check()
bool NBConnection::check (const NBEdgeCont & ec)
checks whether the edges are still valid
Definition at line 196 of file NBConnection.cpp.
References checkFrom(), checkTo(), myFrom, and myTo.
Referenced by NIVissimDisturbance::addToNode(), NBLoadedTLDef::buildPhaseState(), NBLoadedTLDef::mustBrake(), and NBRequest::NBRequest().
checkFrom()
NBEdge * NBConnection::checkFrom (const NBEdgeCont & ec) private
Checks whether the from-edge is still valid.
Definition at line 204 of file NBConnection.cpp.
References myFrom, myFromID, myToID, NBEdgeCont::retrieve(), and NBEdgeCont::retrievePossiblySplit().
Referenced by check().
checkTo()
NBEdge * NBConnection::checkTo (const NBEdgeCont & ec) private
Checks whether the to-edge is still valid.
Definition at line 216 of file NBConnection.cpp.
References myFromID, myTo, myToID, NBEdgeCont::retrieve(), and NBEdgeCont::retrievePossiblySplit().
Referenced by check().
getFrom()
NBEdge * NBConnection::getFrom () const
returns the from-edge (start of the connection)
Definition at line 92 of file NBConnection.cpp.
References myFrom.
Referenced by NBLoadedTLDef::SignalGroup::addConnection(), NBNode::addSortedLinkFoes(), NBLoadedTLDef::addToSignalGroup(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedTLDef::collectNodes(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), NBLoadedTLDef::mustBrake(), NBLoadedTLDef::myCompute(), NIXMLConnectionsHandler::myStartElement(), NBRequest::NBRequest(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NWWriter_SUMO::prohibitionConnection(), NBLoadedSUMOTLDef::reconstructLogic(), NBNode::remapRemoved(), NBLoadedSUMOTLDef::removeConnection(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), and NBLoadedTLDef::setTLControllingInformation().
getFromLane()
int NBConnection::getFromLane () const
returns the from-lane
Definition at line 236 of file NBConnection.cpp.
References myFromLane.
Referenced by NBLoadedTLDef::SignalGroup::addConnection(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NBLoadedSUMOTLDef::reconstructLogic(), NBLoadedSUMOTLDef::removeConnection(), NBEdge::removeFromConnections(), NBEdge::setControllingTLInformation(), and NBLoadedSUMOTLDef::setTLControllingInformation().
getID()
std::string NBConnection::getID () const
returns the id of the connection (!!! not really pretty)
Definition at line 228 of file NBConnection.cpp.
References myFromID, myFromLane, myToID, and myToLane.
Referenced by setTLIndex().
getTLIndex()
int NBConnection::getTLIndex () const inline
returns the index within the controlling tls or InvalidTLIndex if this link is unontrolled
Definition at line 99 of file NBConnection.h.
References myTlIndex.
Referenced by NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedTLDef::myCompute(), operator<<(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::reconstructLogic(), NBEdge::setControllingTLInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), and NBLoadedTLDef::setTLControllingInformation().
getTo()
NBEdge * NBConnection::getTo () const
returns the to-edge (end of the connection)
Definition at line 98 of file NBConnection.cpp.
References myTo.
Referenced by NBNode::addSortedLinkFoes(), NBLoadedTLDef::addToSignalGroup(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), NBLoadedTLDef::myCompute(), NBRequest::NBRequest(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NWWriter_SUMO::prohibitionConnection(), NBLoadedSUMOTLDef::reconstructLogic(), NBNode::remapRemoved(), NBLoadedSUMOTLDef::removeConnection(), NBEdge::removeFromConnections(), and NBEdge::setControllingTLInformation().
getToLane()
int NBConnection::getToLane () const
returns the to-lane
Definition at line 242 of file NBConnection.cpp.
References myToLane.
Referenced by NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NBLoadedSUMOTLDef::reconstructLogic(), NBLoadedSUMOTLDef::removeConnection(), NBEdge::removeFromConnections(), and NBEdge::setControllingTLInformation().
operator!=()
bool NBConnection::operator!= (const NBConnection & c) const inline
Comparison operator.
Definition at line 118 of file NBConnection.h.
References operator<<.
operator==()
bool NBConnection::operator== (const NBConnection & c) const
Comparison operator.
Definition at line 187 of file NBConnection.cpp.
References myFrom, myFromID, myFromLane, myTlIndex, myTo, myToID, and myToLane.
Referenced by setTLIndex().
replaceFrom() [1/2]
bool NBConnection::replaceFrom (NBEdge * which, NBEdge * by)
replaces the from-edge by the one given
Definition at line 104 of file NBConnection.cpp.
References Named::getID(), myFrom, and myFromID.
Referenced by NBLoadedTLDef::SignalGroup::remapIncoming(), and NBNode::replaceInConnectionProhibitions().
replaceFrom() [2/2]
bool NBConnection::replaceFrom (NBEdge * which, int whichLane, NBEdge * by, int byLane)
replaces the from-edge by the one given
Definition at line 119 of file NBConnection.cpp.
References Named::getID(), myFrom, myFromID, and myFromLane.
replaceTo() [1/2]
bool NBConnection::replaceTo (NBEdge * which, NBEdge * by)
replaces the to-edge by the one given
Definition at line 138 of file NBConnection.cpp.
References Named::getID(), myTo, and myToID.
Referenced by NBLoadedTLDef::SignalGroup::remapOutgoing(), and NBNode::replaceInConnectionProhibitions().
replaceTo() [2/2]
bool NBConnection::replaceTo (NBEdge * which, int whichLane, NBEdge * by, int byLane)
replaces the to-edge by the one given
Definition at line 153 of file NBConnection.cpp.
References Named::getID(), myFromLane, myTo, myToID, and myToLane.
setTLIndex()
void NBConnection::setTLIndex (int tlIndex) inline
Definition at line 104 of file NBConnection.h.
References getID(), myTlIndex, operator<, and operator==().
Referenced by NBLoadedTLDef::collectLinks(), and NBLoadedSUMOTLDef::reconstructLogic().
shiftLaneIndex()
void NBConnection::shiftLaneIndex (NBEdge * edge, int offset)
patches lane indices refering to the given edge
Definition at line 248 of file NBConnection.cpp.
References myFrom, myFromLane, myTo, and myToLane.
Referenced by NBEdge::removeFromConnections().
Friends And Related Function Documentation
operator<
bool operator< (const NBConnection & c1, const NBConnection & c2) friend
Compares both connections in order to allow sorting.
Definition at line 172 of file NBConnection.cpp.
Referenced by setTLIndex().
operator<<
std::ostream& operator<< (std::ostream & os, const NBConnection & c) friend
Output operator.
Definition at line 258 of file NBConnection.cpp.
Referenced by operator!=().
Field Documentation
InvalidConnection
const NBConnection NBConnection::InvalidConnection static
Definition at line 126 of file NBConnection.h.
Referenced by NIVissimDisturbance::getConnection(), GNEJunction::invalidateTLS(), NIXMLConnectionsHandler::myStartElement(), and NIXMLConnectionsHandler::parseConnection().
InvalidTlIndex
const int NBConnection::InvalidTlIndex = -1 static
Definition at line 125 of file NBConnection.h.
Referenced by NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedTLDef::setTLControllingInformation().
myFrom
NBEdge* NBConnection::myFrom private
The from- and the to-edges.
Definition at line 137 of file NBConnection.h.
Referenced by check(), checkFrom(), getFrom(), operator==(), replaceFrom(), and shiftLaneIndex().
myFromID
std::string NBConnection::myFromID private
The names of both edges, needed for verification of validity.
Definition at line 140 of file NBConnection.h.
Referenced by checkFrom(), checkTo(), getID(), NBConnection(), operator<(), operator==(), and replaceFrom().
myFromLane
int NBConnection::myFromLane private
The lanes; may be -1 if no certain lane was specified.
Definition at line 143 of file NBConnection.h.
Referenced by getFromLane(), getID(), operator<(), operator==(), replaceFrom(), replaceTo(), and shiftLaneIndex().
myTlIndex
int NBConnection::myTlIndex private
Definition at line 146 of file NBConnection.h.
Referenced by getTLIndex(), operator==(), and setTLIndex().
myTo
NBEdge * NBConnection::myTo private
Definition at line 137 of file NBConnection.h.
Referenced by check(), checkTo(), getTo(), operator==(), replaceTo(), and shiftLaneIndex().
myToID
std::string NBConnection::myToID private
Definition at line 140 of file NBConnection.h.
Referenced by checkFrom(), checkTo(), getID(), NBConnection(), operator<(), operator==(), and replaceTo().
myToLane
int NBConnection::myToLane private
Definition at line 143 of file NBConnection.h.
Referenced by getID(), getToLane(), operator<(), operator==(), replaceTo(), and shiftLaneIndex().
The documentation for this class was generated from the following files:
NBConnection.h
NBConnection.cpp