SUMO - Simulation of Urban MObility: TraCIAPI::SimulationScope Class Reference
TraCIAPI::SimulationScope Class Reference
Scope for interaction with the simulation.
#include <TraCIAPI.h>
Public Member Functions
std::vector< std::string > getArrivedIDList () const
int getArrivedNumber () const
const SubscribedContextValues & getContextSubscriptionResults () const
const SubscribedValues & getContextSubscriptionResults (const std::string &objID) const
SUMOTime getCurrentTime () const
SUMOTime getDeltaT () const
std::vector< std::string > getDepartedIDList () const
int getDepartedNumber () const
std::vector< std::string > getEndingTeleportIDList () const
int getEndingTeleportNumber () const
std::vector< std::string > getLoadedIDList () const
int getLoadedNumber () const
int getMinExpectedNumber () const
libsumo::TraCIBoundary getNetBoundary () const
std::vector< std::string > getStartingTeleportIDList () const
int getStartingTeleportNumber () const
const SubscribedValues & getSubscriptionResults () const
const TraCIValues & getSubscriptionResults (const std::string &objID) const
SimulationScope (TraCIAPI &parent)
void subscribe (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars) const
void subscribeContext (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars) const
virtual ~SimulationScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
SimulationScope & operator= (const SimulationScope &src)
invalidated assignment operator
SimulationScope (const SimulationScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with the simulation.
Definition at line 475 of file TraCIAPI.h.
Constructor & Destructor Documentation
SimulationScope() [1/2]
TraCIAPI::SimulationScope::SimulationScope (TraCIAPI & parent) inline
Definition at line 477 of file TraCIAPI.h.
~SimulationScope()
virtual TraCIAPI::SimulationScope::~SimulationScope () inline virtual
Definition at line 478 of file TraCIAPI.h.
References TraCIAPI::TraCIScopeWrapper::operator=().
SimulationScope() [2/2]
TraCIAPI::SimulationScope::SimulationScope (const SimulationScope & src) private
invalidated copy constructor
Member Function Documentation
getArrivedIDList()
std::vector< std::string > TraCIAPI::SimulationScope::getArrivedIDList () const
Definition at line 1519 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_ARRIVED_VEHICLES_IDS.
getArrivedNumber()
int TraCIAPI::SimulationScope::getArrivedNumber () const
Definition at line 1514 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_ARRIVED_VEHICLES_NUMBER.
getContextSubscriptionResults() [1/2]
const TraCIAPI::SubscribedContextValues & TraCIAPI::SimulationScope::getContextSubscriptionResults () const
Definition at line 1596 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
getContextSubscriptionResults() [2/2]
const TraCIAPI::SubscribedValues & TraCIAPI::SimulationScope::getContextSubscriptionResults (const std::string & objID) const
Definition at line 1602 of file TraCIAPI.cpp.
getCurrentTime()
SUMOTime TraCIAPI::SimulationScope::getCurrentTime () const
Definition at line 1489 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TIME_STEP.
Referenced by TraCITestClient::testAPI().
getDeltaT()
SUMOTime TraCIAPI::SimulationScope::getDeltaT () const
Definition at line 1544 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_DELTA_T.
getDepartedIDList()
std::vector< std::string > TraCIAPI::SimulationScope::getDepartedIDList () const
Definition at line 1509 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_DEPARTED_VEHICLES_IDS.
getDepartedNumber()
int TraCIAPI::SimulationScope::getDepartedNumber () const
Definition at line 1504 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_DEPARTED_VEHICLES_NUMBER.
getEndingTeleportIDList()
std::vector< std::string > TraCIAPI::SimulationScope::getEndingTeleportIDList () const
Definition at line 1539 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_ENDING_VEHICLES_IDS.
getEndingTeleportNumber()
int TraCIAPI::SimulationScope::getEndingTeleportNumber () const
Definition at line 1534 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_ENDING_VEHICLES_NUMBER.
getLoadedIDList()
std::vector< std::string > TraCIAPI::SimulationScope::getLoadedIDList () const
Definition at line 1499 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_LOADED_VEHICLES_IDS.
getLoadedNumber()
int TraCIAPI::SimulationScope::getLoadedNumber () const
Definition at line 1494 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_LOADED_VEHICLES_NUMBER.
getMinExpectedNumber()
int TraCIAPI::SimulationScope::getMinExpectedNumber () const
Definition at line 1554 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_MIN_EXPECTED_VEHICLES.
getNetBoundary()
TraCIBoundary TraCIAPI::SimulationScope::getNetBoundary () const
Definition at line 1549 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_NET_BOUNDING_BOX.
getStartingTeleportIDList()
std::vector< std::string > TraCIAPI::SimulationScope::getStartingTeleportIDList () const
Definition at line 1529 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_STARTING_VEHICLES_IDS.
getStartingTeleportNumber()
int TraCIAPI::SimulationScope::getStartingTeleportNumber () const
Definition at line 1524 of file TraCIAPI.cpp.
References CMD_GET_SIM_VARIABLE, and VAR_TELEPORT_STARTING_VEHICLES_NUMBER.
getSubscriptionResults() [1/2]
const TraCIAPI::SubscribedValues & TraCIAPI::SimulationScope::getSubscriptionResults () const
Definition at line 1580 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
getSubscriptionResults() [2/2]
const TraCIAPI::TraCIValues & TraCIAPI::SimulationScope::getSubscriptionResults (const std::string & objID) const
Definition at line 1586 of file TraCIAPI.cpp.
operator=()
SimulationScope& TraCIAPI::SimulationScope::operator= (const SimulationScope & src) private
invalidated assignment operator
subscribe()
void TraCIAPI::SimulationScope::subscribe (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) const
Definition at line 1559 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
subscribeContext()
void TraCIAPI::SimulationScope::subscribeContext (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) const
Definition at line 1570 of file TraCIAPI.cpp.
Referenced by TraCITestClient::testAPI().
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp