SUMO - Simulation of Urban MObility: GUIContainer Class Reference
GUIContainer Class Reference
#include <GUIContainer.h>
Data Structures
class GUIContainerPopupMenu
Public Types
typedef std::vector< MSTransportable::Stage * > MSTransportablePlan
the structure holding the plan of a transportable
enum StageType { WAITING_FOR_DEPART = 0, WAITING = 1, MOVING_WITHOUT_VEHICLE = 2, DRIVING = 3 }
Public Member Functions
void appendStage (Stage *stage, int next=-1)
Appends the given stage to the current plan.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
const MSEdge * getArrivalEdge () const
returns the final arrival edge
double getArrivalPos () const
returns the final arrival pos
PositionVector getBoundingBox () const
return the bounding box of the person
MSTransportable::Stage * getCurrentStage () const
Return the current stage.
std::string getCurrentStageDescription () const
Returns the current stage description as a string.
StageType getCurrentStageType () const
the current stage type of the transportable
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
ConstMSEdgeVector getEdges (int next) const
Return the edges of the nth next stage.
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the id of the transportable
const MSEdge & getNextDestination () const
Returns the destination after the current destination.
int getNumRemainingStages () const
Return the number of remaining stages (including the current)
int getNumStages () const
Return the total number stages in this persons plan.
const SUMOVehicleParameter & getParameter () const
MSVehicleType & getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
virtual double getSpeedFactor () const
the current speed factor of the transportable (where applicable)
StageType getStageType (int next) const
the stage type for the nth next stage
SUMOVehicle * getVehicle () const
The vehicle associated with this transportable.
const MSVehicleType & getVehicleType () const
GUIContainer (const SUMOVehicleParameter *pars, MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan)
Constructor.
bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
virtual bool proceed (MSNet *net, SUMOTime time)
void removeStage (int next)
removes the nth next stage
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs depart time of the current stage
void setPositionInVehicle (const Position &pos)
void setSpeed (double speed)
sets the walking speed (ignored in other stages)
virtual void tripInfoOutput (OutputDevice &os, MSTransportable *transportable) const
Called on writing tripinfo output.
~GUIContainer ()
destructor
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
inherited from MSContainer with added locking
double getEdgePos () const
return the offset from the start of the current edge
Position getPosition () const
return the Network coordinate of the container
double getAngle () const
return the current angle of the container
double getWaitingSeconds () const
the time this container spent waiting in seconds
double getSpeed () const
the current speed of the container
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Data Fields
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the transportable
MSTransportablePlan * myPlan
the plan of the transportable
MSTransportablePlan::iterator myStep
the iterator over the route
MSVehicleType * myVType
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
bool myWriteEvents
Whether events shall be written.
Static Protected Attributes
static const double ROADSIDE_OFFSET
the offset for computing positions when standing at an edge
Private Member Functions
double getColorValue (int activeScheme) const
gets the color value according to the current scheme index
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
bool setFunctionalColor (int activeScheme) const
sets the color according to the current scheme index and some vehicle function
drawing helper methods
void drawAction_drawAsPoly (const GUIVisualizationSettings &s) const
void drawAction_drawAsImage (const GUIVisualizationSettings &s) const
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
Position myPositionInVehicle
The position of a container while riding a vehicle.
Detailed Description
Definition at line 58 of file GUIContainer.h.
Member Typedef Documentation
MSTransportablePlan
typedef std::vector<MSTransportable::Stage*> MSTransportable::MSTransportablePlan inherited
the structure holding the plan of a transportable
Definition at line 387 of file MSTransportable.h.
Member Enumeration Documentation
StageType
enum MSTransportable::StageType inherited
Enumerator
WAITING_FOR_DEPART
WAITING
MOVING_WITHOUT_VEHICLE
DRIVING
Definition at line 64 of file MSTransportable.h.
Constructor & Destructor Documentation
GUIContainer()
GUIContainer::GUIContainer (const SUMOVehicleParameter * pars, MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan)
Constructor.
Definition at line 105 of file GUIContainer.cpp.
~GUIContainer()
GUIContainer::~GUIContainer ()
destructor
Definition at line 111 of file GUIContainer.cpp.
Member Function Documentation
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
appendStage()
void MSTransportable::appendStage (Stage * stage, int next = -1) inherited
Appends the given stage to the current plan.
Definition at line 466 of file MSTransportable.cpp.
References MSTransportable::getID(), MSTransportable::myPlan, MSTransportable::myStep, and toString().
Referenced by libsumo::Person::appendDrivingStage(), libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), MSTransportable::getVehicle(), MSTransportable::removeStage(), and MSPerson::reroute().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
drawAction_drawAsImage()
void GUIContainer::drawAction_drawAsImage (const GUIVisualizationSettings & s) const private
Definition at line 400 of file GUIContainer.cpp.
References drawAction_drawAsPoly(), GUITexturesHelper::drawTexturedBox(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), MSTransportable::getVehicleType(), MSVehicleType::getWidth(), and GUIVisualizationSettings::personSize.
Referenced by drawGL().
drawAction_drawAsPoly()
void GUIContainer::drawAction_drawAsPoly (const GUIVisualizationSettings & s) const private
Definition at line 378 of file GUIContainer.cpp.
References getAngle(), GLHelper::getColor(), MSTransportable::getVehicleType(), M_PI, RAD2DEG, and GLHelper::setColor().
Referenced by drawAction_drawAsImage(), and drawGL().
drawGL()
void GUIContainer::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 182 of file GUIContainer.cpp.
References GUIVisualizationSettings::containerName, GUIVisualizationSettings::containerQuality, GUIVisualizationSettings::containerSize, drawAction_drawAsImage(), drawAction_drawAsPoly(), GUIGlObject::drawName(), MSTransportable::DRIVING, MSTransportable::getCurrentStageType(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), getPosition(), GUIGlObject::getType(), MSTransportable::isWaiting4Vehicle(), myPositionInVehicle, GUIVisualizationSettings::scale, setColor(), Position::x(), and Position::y().
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers(), GUIContainerStop::drawGL(), GUIParkingArea::drawGL(), and GUIEdge::drawGL().
drawGLAdditional()
void GUIContainer::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 216 of file GUIContainer.cpp.
References GUIGlObject::getGlID().
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), drawGL(), GNERouteProbe::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
getAngle()
double GUIContainer::getAngle () const virtual
return the current angle of the container
Reimplemented from MSTransportable.
Definition at line 357 of file GUIContainer.cpp.
References MSTransportable::getAngle(), and myLock.
Referenced by drawAction_drawAsPoly(), getParameterWindow(), setFunctionalColor(), and setPositionInVehicle().
getArrivalEdge()
const MSEdge* MSTransportable::getArrivalEdge () const inline inherited
returns the final arrival edge
Definition at line 535 of file MSTransportable.h.
References MSTransportable::getBoundingBox(), MSTransportable::getSingularType(), MSTransportable::myPlan, and MSTransportable::replaceVehicleType().
Referenced by libsumo::Person::appendWaitingStage(), and libsumo::Person::rerouteTraveltime().
getArrivalPos()
double MSTransportable::getArrivalPos () const inline inherited
returns the final arrival pos
Definition at line 530 of file MSTransportable.h.
References MSTransportable::myPlan.
Referenced by libsumo::Person::appendWaitingStage(), libsumo::Person::appendWalkingStage(), MSPerson::reroute(), and libsumo::Person::rerouteTraveltime().
getBoundingBox()
PositionVector MSTransportable::getBoundingBox () const inherited
return the bounding box of the person
Definition at line 531 of file MSTransportable.cpp.
References PositionVector::append(), MSTransportable::getAngle(), MSVehicleType::getLength(), MSTransportable::getPosition(), MSTransportable::getVehicleType(), PositionVector::move2side(), POSITION_EPS, and PositionVector::reverse().
Referenced by MSTransportable::getArrivalEdge().
getCenteringBoundary()
Boundary GUIContainer::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 172 of file GUIContainer.cpp.
References Boundary::add(), getPosition(), and Boundary::grow().
getColorValue()
double GUIContainer::getColorValue (int activeScheme) const private
gets the color value according to the current scheme index
Definition at line 318 of file GUIContainer.cpp.
References MSTransportable::getCurrentStageType(), GUIGlObject::getGlID(), getSpeed(), getWaitingSeconds(), GLO_CONTAINER, gSelected, GUISelectedStorage::isSelected(), and MSTransportable::isWaiting4Vehicle().
Referenced by setColor().
getCurrentStage()
MSTransportable::Stage* MSTransportable::getCurrentStage () const inline inherited
Return the current stage.
Definition at line 474 of file MSTransportable.h.
References MSTransportable::myStep.
Referenced by MSTransportableControl::abortWaitingForVehicle(), GUIPerson::drawAction_drawWalkingareaPath(), GUIPerson::drawGLAdditional(), libsumo::Person::moveToXY(), MSEdge::transportable_by_position_sorter::operator()(), and MSPerson::Influencer::postProcessRemoteControl().
getCurrentStageDescription()
std::string MSTransportable::getCurrentStageDescription () const inline inherited
Returns the current stage description as a string.
Definition at line 469 of file MSTransportable.h.
Referenced by getParameterWindow(), GUIPerson::getParameterWindow(), libsumo::Person::moveTo(), libsumo::Person::moveToXY(), and MSXMLRawOut::writeTransportable().
getCurrentStageType()
StageType MSTransportable::getCurrentStageType () const inline inherited
the current stage type of the transportable
Definition at line 457 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), drawGL(), GUIPerson::drawGL(), GUIPerson::drawGLAdditional(), getColorValue(), GUIPerson::getColorValue(), MSPerson::getNextEdgePtr(), getPosition(), and libsumo::Person::rerouteTraveltime().
getDesiredDepart()
SUMOTime MSTransportable::getDesiredDepart () const inherited
Returns the desired departure time.
Definition at line 420 of file MSTransportable.cpp.
References SUMOVehicleParameter::depart, and MSTransportable::myParameter.
Referenced by MSTransportable::getVehicleType(), MSContainer::routeOutput(), MSContainer::tripInfoOutput(), and MSPerson::tripInfoOutput().
getDestination()
const MSEdge& MSTransportable::getDestination () const inline inherited
Returns the current destination.
Definition at line 417 of file MSTransportable.h.
Referenced by getParameterWindow(), GUIPerson::getParameterWindow(), MSDevice_Transportable::notifyLeave(), and MSDevice_Transportable::notifyMove().
getEdge()
const MSEdge* MSTransportable::getEdge () const inline inherited
Returns the current edge.
Definition at line 427 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), getParameterWindow(), GUIPerson::getParameterWindow(), getPosition(), libsumo::Person::getRoadID(), libsumo::Person::moveToXY(), MSTransportable::removeStage(), and libsumo::Person::rerouteTraveltime().
getEdgePos()
double GUIContainer::getEdgePos () const virtual
return the offset from the start of the current edge
Reimplemented from MSTransportable.
Definition at line 338 of file GUIContainer.cpp.
References MSTransportable::getEdgePos(), and myLock.
Referenced by getParameterWindow(), getPosition(), and setPositionInVehicle().
getEdges()
ConstMSEdgeVector MSTransportable::getEdges (int next) const inline inherited
Return the edges of the nth next stage.
Definition at line 479 of file MSTransportable.h.
References MSTransportable::Stage::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::myPlan, MSTransportable::myStep, MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
Referenced by libsumo::Person::getEdges(), and libsumo::Person::rerouteTraveltime().
getFromEdge()
const MSEdge* MSTransportable::getFromEdge () const inline inherited
Returns the departure edge.
Definition at line 432 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getPosition(), MSTransportable::Stage::getSpeed(), and MSTransportable::getWaitingSeconds().
Referenced by getParameterWindow(), and GUIPerson::getParameterWindow().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getID()
const std::string & MSTransportable::getID () const inherited
returns the id of the transportable
Definition at line 415 of file MSTransportable.cpp.
References SUMOVehicleParameter::id, and MSTransportable::myParameter.
Referenced by MSTransportableControl::abortWaitingForVehicle(), MSPModel_Striping::add(), MSBaseVehicle::addContainer(), MSVehicle::addContainer(), MSBaseVehicle::addPerson(), MSVehicle::addPerson(), MSTransportable::appendStage(), libsumo::Person::appendWalkingStage(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSTransportableControl::erase(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), getParameterWindow(), GUIPerson::getParameterWindow(), MSTransportable::getSingularType(), MSPedestrianPushButton::isActiveForEdge(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), MSDevice_Transportable::notifyLeave(), MSPModel_Striping::by_xpos_sorter::operator()(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPModel_Striping::PState::PState(), MSPerson::reroute(), MSContainer::MSContainerStage_Driving::routeOutput(), MSContainer::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), libsumo::Helper::setRemoteControlled(), MSContainer::tripInfoOutput(), MSPerson::tripInfoOutput(), MSPModel_Striping::PState::walk(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNEPoly::getParentName(), GNERerouter::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNextDestination()
const MSEdge& MSTransportable::getNextDestination () const inline inherited
Returns the destination after the current destination.
Definition at line 422 of file MSTransportable.h.
References MSTransportable::myStep.
getNumRemainingStages()
int MSTransportable::getNumRemainingStages () const inherited
Return the number of remaining stages (including the current)
Definition at line 456 of file MSTransportable.cpp.
References MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by libsumo::Person::getEdges(), MSTransportable::getEdges(), libsumo::Person::getRemainingStages(), libsumo::Person::getStage(), libsumo::Person::removeStage(), MSPerson::reroute(), and libsumo::Person::rerouteTraveltime().
getNumStages()
int MSTransportable::getNumStages () const inherited
Return the total number stages in this persons plan.
Definition at line 461 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by libsumo::Person::getEdges(), MSTransportable::getEdges(), and libsumo::Person::getStage().
getParameter()
const SUMOVehicleParameter& MSTransportable::getParameter () const inline inherited
Definition at line 402 of file MSTransportable.h.
References MSTransportable::myParameter.
Referenced by MSTransportableControl::add(), libsumo::Person::getColor(), libsumo::Person::getParameter(), getParameterWindow(), GUIPerson::getParameterWindow(), setFunctionalColor(), GUIPerson::setFunctionalColor(), and libsumo::Person::setParameter().
getParameterWindow()
GUIParameterTableWindow * GUIContainer::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 131 of file GUIContainer.cpp.
References GUIParameterTableWindow::closeBuilding(), getAngle(), MSTransportable::getCurrentStageDescription(), MSTransportable::getDestination(), MSTransportable::getEdge(), getEdgePos(), MSTransportable::getFromEdge(), MSTransportable::getID(), MSTransportable::getParameter(), getSpeed(), MSTransportable::getSpeedFactor(), getWaitingSeconds(), GUIParameterTableWindow::mkItem(), and time2string().
getParentName()
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEPoly, GNERerouter, GNEPOILane, GNEVariableSpeedSign, GNENetElement, GNEPOI, GNERouteProbe, GNEStoppingPlace, GNEDetector, GUILane, GNEDetectorE3, GNEVaporizer, and GNELane.
Definition at line 114 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
getPopUpMenu()
GUIGLObjectPopupMenu * GUIContainer::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 116 of file GUIContainer.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), and myAdditionalVisualizations.
getPosition()
Position GUIContainer::getPosition () const virtual
return the Network coordinate of the container
Reimplemented from MSTransportable.
Definition at line 345 of file GUIContainer.cpp.
References MSTransportable::getCurrentStageType(), MSTransportable::getEdge(), getEdgePos(), MSEdge::getLanes(), MSTransportable::getPosition(), MSLane::getShape(), myLock, PositionVector::positionAtOffset2D(), SVC_SHIP, MSTransportable::WAITING, and WATER_WAY_OFFSET.
Referenced by drawGL(), getCenteringBoundary(), and setPositionInVehicle().
getSingularType()
MSVehicleType & MSTransportable::getSingularType () inherited
Replaces the current vehicle type with a new one used by this vehicle only.
If the currently used vehicle type is already marked as being used by this vehicle only, no new type is created.
Returns
The new modifiable vehicle type
See also
MSTransportable::myVType
Definition at line 520 of file MSTransportable.cpp.
References MSVehicleType::buildSingularType(), MSVehicleType::getID(), MSTransportable::getID(), MSVehicleType::isVehicleSpecific(), MSTransportable::myVType, and MSTransportable::replaceVehicleType().
Referenced by MSTransportable::getArrivalEdge(), and libsumo::Person::getSingularVType().
getSpeed()
double GUIContainer::getSpeed () const virtual
the current speed of the container
Reimplemented from MSTransportable.
Definition at line 371 of file GUIContainer.cpp.
References MSTransportable::getSpeed(), and myLock.
Referenced by getColorValue(), getParameterWindow(), and setPositionInVehicle().
getSpeedFactor()
virtual double MSTransportable::getSpeedFactor () const inline virtual inherited
the current speed factor of the transportable (where applicable)
Reimplemented in MSPerson.
Definition at line 452 of file MSTransportable.h.
Referenced by getParameterWindow().
getStageType()
StageType MSTransportable::getStageType (int next) const inline inherited
the stage type for the nth next stage
Definition at line 462 of file MSTransportable.h.
References MSTransportable::Stage::getStageType(), MSTransportable::myPlan, and MSTransportable::myStep.
Referenced by libsumo::Person::getStage(), libsumo::Person::moveToXY(), and MSPerson::Influencer::postProcessRemoteControl().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIContainer::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented from GUIGlObject.
Definition at line 153 of file GUIContainer.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicleType::getHeight(), MSVehicleType::getID(), MSVehicleType::getLength(), Parameterised::getMap(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicleType::getParameter(), MSVehicleType::getWidth(), GUIParameterTableWindow::mkItem(), and MSTransportable::myVType.
getVehicle()
SUMOVehicle* MSTransportable::getVehicle () const inline inherited
The vehicle associated with this transportable.
Definition at line 516 of file MSTransportable.h.
References MSTransportable::appendStage(), MSTransportable::removeStage(), and MSTransportable::Stage::setSpeed().
Referenced by libsumo::Person::getVehicle().
getVehicleType()
const MSVehicleType& MSTransportable::getVehicleType () const inline inherited
Definition at line 406 of file MSTransportable.h.
References MSTransportable::getDesiredDepart(), MSTransportable::myVType, and MSTransportable::Stage::setDeparted().
Referenced by MSStoppingPlace::addTransportable(), libsumo::Person::appendWalkingStage(), drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), MSTransportable::getBoundingBox(), GUIPerson::getCenteringBoundary(), MSPModel_Striping::PState::getImpatience(), MSLink::getLeaderInfo(), MSPModel_Striping::PState::getLength(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSPModel_Striping::PState::getMinGap(), MSPModel_Striping::getNextLaneObstacles(), libsumo::Person::getTypeID(), MSPModel_Striping::PState::ignoreRed(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Person::moveToXY(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::PState::otherStripe(), MSStoppingPlace::removeTransportable(), MSPerson::reroute(), libsumo::Person::rerouteTraveltime(), MSPerson::routeOutput(), setFunctionalColor(), and GUIPerson::setFunctionalColor().
getWaitingSeconds()
double GUIContainer::getWaitingSeconds () const virtual
the time this container spent waiting in seconds
Reimplemented from MSTransportable.
Definition at line 364 of file GUIContainer.cpp.
References MSTransportable::getWaitingSeconds(), and myLock.
Referenced by getColorValue(), getParameterWindow(), and setPositionInVehicle().
isWaiting4Vehicle()
bool MSTransportable::isWaiting4Vehicle () const inline inherited
Whether the transportable waits for a vehicle.
Definition at line 511 of file MSTransportable.h.
Referenced by drawGL(), GUIPerson::drawGL(), getColorValue(), and GUIPerson::getColorValue().
isWaitingFor()
bool MSTransportable::isWaitingFor (const std::string & line) const inline inherited
Whether the transportable waits for a vehicle of the line specified.
Definition at line 506 of file MSTransportable.h.
proceed()
bool MSContainer::proceed (MSNet * net, SUMOTime time) virtual inherited
Implements MSTransportable.
Definition at line 269 of file MSContainer.cpp.
References MSTransportable::Stage::getEdge(), MSTransportable::myPlan, MSTransportable::myStep, MSEdge::removeContainer(), and MSTransportable::Stage::setArrived().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
removeStage()
void MSTransportable::removeStage (int next) inherited
removes the nth next stage
Definition at line 482 of file MSTransportable.cpp.
References MSTransportable::appendStage(), MSTransportable::getEdge(), MSTransportable::getEdgePos(), MSNet::getInstance(), MSTransportable::myPlan, MSTransportable::myStep, and MSTransportable::proceed().
Referenced by MSTransportable::getVehicle(), libsumo::Person::removeStage(), and MSPerson::reroute().
replaceVehicleType()
void MSTransportable::replaceVehicleType (MSVehicleType * type) inherited
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myVType".
Parameters
[in] type The new vehicle type
See also
MSTransportable::myVType
Definition at line 511 of file MSTransportable.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleType::isVehicleSpecific(), MSTransportable::myVType, and MSVehicleControl::removeVType().
Referenced by MSTransportable::getArrivalEdge(), MSTransportable::getSingularType(), and libsumo::Person::setType().
routeOutput()
void MSContainer::routeOutput (OutputDevice & os) const virtual inherited
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 295 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSNet::getInstance(), OutputDevice::lf(), MSTransportable::myPlan, MSTransportable::myStep, OutputDevice::openTag(), SUMO_ATTR_DEPART, SUMO_ATTR_ID, SUMO_TAG_CONTAINER, time2string(), and OutputDevice::writeAttr().
setColor()
void GUIContainer::setColor (const GUIVisualizationSettings & s) const private
sets the color according to the currente settings
Definition at line 270 of file GUIContainer.cpp.
References GUIVisualizationSettings::containerColorer, GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GLHelper::setColor(), and setFunctionalColor().
Referenced by drawGL().
setDeparted()
void MSTransportable::setDeparted (SUMOTime now) inherited
logs depart time of the current stage
Definition at line 425 of file MSTransportable.cpp.
Referenced by MSTransportableControl::abortWaitingForVehicle().
setFunctionalColor()
bool GUIContainer::setFunctionalColor (int activeScheme) const private
sets the color according to the current scheme index and some vehicle function
Definition at line 279 of file GUIContainer.cpp.
References RGBColor::fromHSV(), getAngle(), MSTransportable::getParameter(), MSTransportable::getVehicleType(), GeomHelper::naviDegree(), GLHelper::setColor(), VEHPARS_COLOR_SET, and VTYPEPARS_COLOR_SET.
Referenced by setColor().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPositionInVehicle()
void GUIContainer::setPositionInVehicle (const Position & pos) inline
Definition at line 124 of file GUIContainer.h.
References getAngle(), getEdgePos(), getPosition(), getSpeed(), getWaitingSeconds(), and myPositionInVehicle.
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setSpeed()
void MSTransportable::setSpeed (double speed) inherited
sets the walking speed (ignored in other stages)
Definition at line 503 of file MSTransportable.cpp.
References MSTransportable::myPlan.
Referenced by libsumo::Person::setSpeed().
tripInfoOutput()
void MSContainer::tripInfoOutput (OutputDevice & os, MSTransportable * transportable) const virtual inherited
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 285 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::myPlan, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Field Documentation
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
myAdditionalVisualizations
std::map<GUISUMOAbstractView*, int> GUIContainer::myAdditionalVisualizations
Enabled visualisations, per view.
Definition at line 187 of file GUIContainer.h.
Referenced by getPopUpMenu().
myLock
MFXMutex GUIContainer::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 194 of file GUIContainer.h.
Referenced by getAngle(), getEdgePos(), getPosition(), getSpeed(), and getWaitingSeconds().
myParameter
const SUMOVehicleParameter* MSTransportable::myParameter protected inherited
the plan of the transportable
Definition at line 568 of file MSTransportable.h.
Referenced by MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::getParameter(), MSPerson::routeOutput(), and MSTransportable::~MSTransportable().
myPlan
MSTransportablePlan* MSTransportable::myPlan protected inherited
the plan of the transportable
Definition at line 578 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getArrivalEdge(), MSTransportable::getArrivalPos(), MSTransportable::getEdges(), MSTransportable::getNumRemainingStages(), MSTransportable::getNumStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::removeStage(), MSContainer::routeOutput(), MSPerson::routeOutput(), MSTransportable::setSpeed(), MSContainer::tripInfoOutput(), MSPerson::tripInfoOutput(), and MSTransportable::~MSTransportable().
myPositionInVehicle
Position GUIContainer::myPositionInVehicle private
The position of a container while riding a vehicle.
Definition at line 197 of file GUIContainer.h.
Referenced by drawGL(), and setPositionInVehicle().
myStep
MSTransportablePlan::iterator MSTransportable::myStep protected inherited
the iterator over the route
Definition at line 581 of file MSTransportable.h.
Referenced by MSTransportable::appendStage(), MSTransportable::getCurrentStage(), MSTransportable::getEdges(), MSTransportable::getNextDestination(), MSTransportable::getNumRemainingStages(), MSTransportable::getStageType(), MSTransportable::MSTransportable(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::removeStage(), MSContainer::routeOutput(), and MSPerson::routeOutput().
myVType
MSVehicleType* MSTransportable::myVType protected inherited
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
Definition at line 572 of file MSTransportable.h.
Referenced by MSTransportable::getSingularType(), getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), MSTransportable::getVehicleType(), MSTransportable::replaceVehicleType(), and MSTransportable::~MSTransportable().
myWriteEvents
bool MSTransportable::myWriteEvents protected inherited
Whether events shall be written.
Definition at line 575 of file MSTransportable.h.
ROADSIDE_OFFSET
const double MSTransportable::ROADSIDE_OFFSET static protected inherited
the offset for computing positions when standing at an edge
Definition at line 565 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getPosition(), and MSTransportable::Stage_Driving::getPosition().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIContainer.h
GUIContainer.cpp