SUMO - Simulation of Urban MObility: GUIEvent_SimulationEnded Class Reference
GUIEvent_SimulationEnded Class Reference
Event sent when the the simulation is over.
#include <GUIEvent_SimulationEnded.h>
Public Member Functions
GUIEventType getOwnType () const
returns the event type
MSNet::SimulationState getReason () const
Returns the reason the simulation has ended due.
SUMOTime getTimeStep () const
Returns the time step the simulation has ended at.
GUIEvent_SimulationEnded (MSNet::SimulationState reason, SUMOTime step)
Constructor.
~GUIEvent_SimulationEnded ()
Destructor.
Protected Attributes
MSNet::SimulationState myReason
The reason the simulation has ended.
SUMOTime myStep
The time step the simulation has ended at.
GUIEventType myType
the type of the event
Detailed Description
Event sent when the the simulation is over.
Throw from GUIRunThread to GUIApplicationWindow.
Definition at line 47 of file GUIEvent_SimulationEnded.h.
Constructor & Destructor Documentation
GUIEvent_SimulationEnded()
GUIEvent_SimulationEnded::GUIEvent_SimulationEnded (MSNet::SimulationState reason, SUMOTime step) inline
Constructor.
Parameters
[in] reason The reason the simulation has ended
[in] step The time step the simulation has ended at
Definition at line 53 of file GUIEvent_SimulationEnded.h.
~GUIEvent_SimulationEnded()
GUIEvent_SimulationEnded::~GUIEvent_SimulationEnded () inline
Destructor.
Definition at line 58 of file GUIEvent_SimulationEnded.h.
Member Function Documentation
getOwnType()
GUIEventType GUIEvent::getOwnType () const inline inherited
returns the event type
Definition at line 83 of file GUIEvent.h.
References GUIEvent::myType.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
getReason()
MSNet::SimulationState GUIEvent_SimulationEnded::getReason () const inline
Returns the reason the simulation has ended due.
Returns
The reason the simulation has ended
Definition at line 72 of file GUIEvent_SimulationEnded.h.
References myReason.
Referenced by GUIApplicationWindow::handleEvent_SimulationEnded().
getTimeStep()
SUMOTime GUIEvent_SimulationEnded::getTimeStep () const inline
Returns the time step the simulation has ended at.
Returns
The time step the simulation has ended at
Definition at line 64 of file GUIEvent_SimulationEnded.h.
References myStep.
Referenced by GUIApplicationWindow::handleEvent_SimulationEnded().
Field Documentation
myReason
MSNet::SimulationState GUIEvent_SimulationEnded::myReason protected
The reason the simulation has ended.
Definition at line 79 of file GUIEvent_SimulationEnded.h.
Referenced by getReason().
myStep
SUMOTime GUIEvent_SimulationEnded::myStep protected
The time step the simulation has ended at.
Definition at line 82 of file GUIEvent_SimulationEnded.h.
Referenced by getTimeStep().
myType
GUIEventType GUIEvent::myType protected inherited
the type of the event
Definition at line 98 of file GUIEvent.h.
Referenced by GUIEvent::getOwnType(), and GUIEvent_Message::GUIEvent_Message().
The documentation for this class was generated from the following file:
GUIEvent_SimulationEnded.h