SUMO - Simulation of Urban MObility: NIImporter_ArcView Class Reference
NIImporter_ArcView Class Reference
Importer for networks stored in ArcView-shape format.
#include <NIImporter_ArcView.h>
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given ArcView Shape files.
Protected Member Functions
void load ()
Loads the shape files.
NIImporter_ArcView (const OptionsCont &oc, NBNodeCont &nc, NBEdgeCont &ec, NBTypeCont &tc, const std::string &dbf_name, const std::string &shp_name, bool speedInKMH)
Constructor.
~NIImporter_ArcView ()
Destructor.
Private Member Functions
NIImporter_ArcView (const NIImporter_ArcView &)
Invalidated copy constructor.
NIImporter_ArcView & operator= (const NIImporter_ArcView &)
Invalidated assignment operator.
Private Attributes
NBEdgeCont & myEdgeCont
The container to add edges to.
int myNameAddition
A running number to assure unique edge ids.
NBNodeCont & myNodeCont
The container to add nodes to.
const OptionsCont & myOptions
The options to use.
int myRunningNodeID
A running number to assure unique node ids.
std::string mySHPName
The name of the shape file.
bool mySpeedInKMH
Whether the speed is given in km/h.
NBTypeCont & myTypeCont
The container to get the types from.
Detailed Description
Importer for networks stored in ArcView-shape format.
The current importer works only if SUMO was compiled with GDAL-support. If not, an error message is generated.
Todo:
reinsert import via shapelib
Definition at line 56 of file NIImporter_ArcView.h.
Constructor & Destructor Documentation
NIImporter_ArcView() [1/2]
NIImporter_ArcView::NIImporter_ArcView (const OptionsCont & oc, NBNodeCont & nc, NBEdgeCont & ec, NBTypeCont & tc, const std::string & dbf_name, const std::string & shp_name, bool speedInKMH) protected
Constructor.
Parameters
[in] oc Options container to read options from
[in] nc The node container to store nodes into
[in] ec The edge container to store edges into
[in] tc The type container to get edge types from
[in] dbf_name The name of the according database file
[in] shp_name The name of the according shape file
[in] speedInKMH Whether the speed shall be assumed to be given in km/h
Definition at line 107 of file NIImporter_ArcView.cpp.
References UNUSED_PARAMETER.
~NIImporter_ArcView()
NIImporter_ArcView::~NIImporter_ArcView () protected
Destructor.
Definition at line 123 of file NIImporter_ArcView.cpp.
NIImporter_ArcView() [2/2]
NIImporter_ArcView::NIImporter_ArcView (const NIImporter_ArcView &) private
Invalidated copy constructor.
Member Function Documentation
load()
void NIImporter_ArcView::load () protected
Loads the shape files.
Definition at line 127 of file NIImporter_ArcView.cpp.
References OptionsCont::getBool(), NBNode::getConnectionTo(), NBEdge::getFromNode(), NINavTeqHelper::getLaneNumber(), NBTypeCont::getNumLanes(), OptionsCont::getOptions(), NBTypeCont::getPriority(), NINavTeqHelper::getSpeed(), NBTypeCont::getSpeed(), OptionsCont::getString(), NBEdge::getToNode(), NBTypeCont::getWidth(), NBNodeCont::insert(), NBEdgeCont::insert(), OptionsCont::isSet(), LANESPREAD_CENTER, LANESPREAD_RIGHT, myEdgeCont, myNodeCont, myOptions, myRunningNodeID, mySHPName, mySpeedInKMH, myTypeCont, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, StringUtils::prune(), PositionVector::push_back_noDoublePos(), StringUtils::replace(), NBNodeCont::retrieve(), NBEdgeCont::retrieve(), PositionVector::reverse(), NBEdge::setLaneSpreadFunction(), toString(), NBNetBuilder::transformCoordinate(), NBEdge::UNSPECIFIED_OFFSET, WRITE_ERROR, and WRITE_WARNING.
Referenced by loadNetwork().
loadNetwork()
void NIImporter_ArcView::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads content of the optionally given ArcView Shape files.
If the option "shapefile-prefix" is set, the file stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "shapefile-prefix" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 73 of file NIImporter_ArcView.cpp.
References OptionsCont::getBool(), NBNetBuilder::getEdgeCont(), MsgHandler::getErrorInstance(), NBNetBuilder::getNodeCont(), OptionsCont::getString(), NBNetBuilder::getTypeCont(), FileHelpers::isReadable(), OptionsCont::isSet(), load(), and WRITE_ERROR.
Referenced by NILoader::load().
operator=()
NIImporter_ArcView& NIImporter_ArcView::operator= (const NIImporter_ArcView &) private
Invalidated assignment operator.
Field Documentation
myEdgeCont
NBEdgeCont& NIImporter_ArcView::myEdgeCont private
The container to add edges to.
Definition at line 160 of file NIImporter_ArcView.h.
Referenced by load().
myNameAddition
int NIImporter_ArcView::myNameAddition private
A running number to assure unique edge ids.
Definition at line 154 of file NIImporter_ArcView.h.
myNodeCont
NBNodeCont& NIImporter_ArcView::myNodeCont private
The container to add nodes to.
Definition at line 157 of file NIImporter_ArcView.h.
Referenced by load().
myOptions
const OptionsCont& NIImporter_ArcView::myOptions private
The options to use.
Definition at line 148 of file NIImporter_ArcView.h.
Referenced by load().
myRunningNodeID
int NIImporter_ArcView::myRunningNodeID private
A running number to assure unique node ids.
Definition at line 169 of file NIImporter_ArcView.h.
Referenced by load().
mySHPName
std::string NIImporter_ArcView::mySHPName private
The name of the shape file.
Definition at line 151 of file NIImporter_ArcView.h.
Referenced by load().
mySpeedInKMH
bool NIImporter_ArcView::mySpeedInKMH private
Whether the speed is given in km/h.
Definition at line 166 of file NIImporter_ArcView.h.
Referenced by load().
myTypeCont
NBTypeCont& NIImporter_ArcView::myTypeCont private
The container to get the types from.
Definition at line 163 of file NIImporter_ArcView.h.
Referenced by load().
The documentation for this class was generated from the following files:
NIImporter_ArcView.h
NIImporter_ArcView.cpp