SUMO - Simulation of Urban MObility: MSVehicle::DriveProcessItem Struct Reference
MSVehicle::DriveProcessItem Struct Reference
Drive process items represent bounds on the safe velocity corresponding to the upcoming links.
#include <MSVehicle.h>
Public Member Functions
void adaptLeaveSpeed (const double v)
DriveProcessItem (MSLink *link, double vPass, double vWait, bool setRequest, SUMOTime arrivalTime, double arrivalSpeed, SUMOTime arrivalTimeBraking, double arrivalSpeedBraking, double distance, double leaveSpeed=-1.)
DriveProcessItem (double vWait, double distance, double _availableSpace=0)
constructor if the link shall not be passed
double getLeaveSpeed () const
Data Fields
double accelV
double availableSpace
bool hadVehicle
double myArrivalSpeed
double myArrivalSpeedBraking
SUMOTime myArrivalTime
SUMOTime myArrivalTimeBraking
double myDistance
MSLink * myLink
bool mySetRequest
double myVLinkPass
double myVLinkWait
Detailed Description
Drive process items represent bounds on the safe velocity corresponding to the upcoming links.
Todo:
: improve documentation
Definition at line 1759 of file MSVehicle.h.
Constructor & Destructor Documentation
DriveProcessItem() [1/2]
MSVehicle::DriveProcessItem::DriveProcessItem (MSLink * link, double vPass, double vWait, bool setRequest, SUMOTime arrivalTime, double arrivalSpeed, SUMOTime arrivalTimeBraking, double arrivalSpeedBraking, double distance, double leaveSpeed = -1.) inline
Definition at line 1773 of file MSVehicle.h.
References MSGlobals::gSemiImplicitEulerUpdate.
DriveProcessItem() [2/2]
MSVehicle::DriveProcessItem::DriveProcessItem (double vWait, double distance, double _availableSpace = 0) inline
constructor if the link shall not be passed
Definition at line 1789 of file MSVehicle.h.
References MSGlobals::gSemiImplicitEulerUpdate.
Member Function Documentation
adaptLeaveSpeed()
void MSVehicle::DriveProcessItem::adaptLeaveSpeed (const double v) inline
Definition at line 1799 of file MSVehicle.h.
References MIN2().
Referenced by MSVehicle::adaptToLeader(), and MSVehicle::planMoveInternal().
getLeaveSpeed()
double MSVehicle::DriveProcessItem::getLeaveSpeed () const inline
Definition at line 1806 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
Field Documentation
accelV
double MSVehicle::DriveProcessItem::accelV
Definition at line 1769 of file MSVehicle.h.
availableSpace
double MSVehicle::DriveProcessItem::availableSpace
Definition at line 1771 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes().
hadVehicle
bool MSVehicle::DriveProcessItem::hadVehicle
Definition at line 1770 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes().
myArrivalSpeed
double MSVehicle::DriveProcessItem::myArrivalSpeed
Definition at line 1765 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
myArrivalSpeedBraking
double MSVehicle::DriveProcessItem::myArrivalSpeedBraking
Definition at line 1767 of file MSVehicle.h.
myArrivalTime
SUMOTime MSVehicle::DriveProcessItem::myArrivalTime
Definition at line 1764 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
myArrivalTimeBraking
SUMOTime MSVehicle::DriveProcessItem::myArrivalTimeBraking
Definition at line 1766 of file MSVehicle.h.
myDistance
double MSVehicle::DriveProcessItem::myDistance
Definition at line 1768 of file MSVehicle.h.
myLink
MSLink* MSVehicle::DriveProcessItem::myLink
Definition at line 1760 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
mySetRequest
bool MSVehicle::DriveProcessItem::mySetRequest
Definition at line 1763 of file MSVehicle.h.
Referenced by MSVehicle::checkLinkLeader().
myVLinkPass
double MSVehicle::DriveProcessItem::myVLinkPass
Definition at line 1761 of file MSVehicle.h.
myVLinkWait
double MSVehicle::DriveProcessItem::myVLinkWait
Definition at line 1762 of file MSVehicle.h.
Referenced by MSVehicle::checkLinkLeader().
The documentation for this struct was generated from the following file:
MSVehicle.h