SUMO - Simulation of Urban MObility: MSLeaderInfo Class Reference
MSLeaderInfo Class Reference
#include <MSLeaderInfo.h>
Public Member Functions
virtual int addLeader (const MSVehicle *veh, bool beyond, double latOffset=0)
virtual void clear ()
discard all information
void getSublaneBorders (int sublane, double latOffset, double &rightSide, double &leftSide) const
void getSubLanes (const MSVehicle *veh, double latOffset, int &rightmost, int &leftmost) const
bool hasStoppedVehicle () const
whether a stopped vehicle is leader
bool hasVehicles () const
MSLeaderInfo (const MSLane *lane, const MSVehicle *ego=0, double latOffset=0)
Constructor.
int numFreeSublanes () const
int numSublanes () const
const MSVehicle * operator[] (int sublane) const
return the vehicle for the given sublane
virtual std::string toString () const
print a debugging representation
virtual ~MSLeaderInfo ()
Destructor.
Protected Attributes
int egoLeftMost
int egoRightMost
borders of the ego vehicle for filtering of free sublanes
int myFreeSublanes
the number of free sublanes
bool myHasVehicles
std::vector< const MSVehicle * > myVehicles
double myWidth
the width of the lane to which this instance applies
Detailed Description
Definition at line 56 of file MSLeaderInfo.h.
Constructor & Destructor Documentation
MSLeaderInfo()
MSLeaderInfo::MSLeaderInfo (const MSLane * lane, const MSVehicle * ego = 0, double latOffset = 0)
Constructor.
Definition at line 49 of file MSLeaderInfo.cpp.
References egoLeftMost, egoRightMost, getSubLanes(), myFreeSublanes, and myVehicles.
~MSLeaderInfo()
MSLeaderInfo::~MSLeaderInfo () virtual
Destructor.
Definition at line 65 of file MSLeaderInfo.cpp.
Member Function Documentation
addLeader()
int MSLeaderInfo::addLeader (const MSVehicle * veh, bool beyond, double latOffset = 0) virtual
Reimplemented in MSCriticalFollowerDistanceInfo, and MSLeaderDistanceInfo.
Definition at line 69 of file MSLeaderInfo.cpp.
References egoLeftMost, egoRightMost, getSubLanes(), myFreeSublanes, myHasVehicles, and myVehicles.
Referenced by MSVehicle::checkLinkLeader(), MSLane::getFirstVehicleInformation(), MSLane::getLastVehicleInformation(), MSLane::getPartialBeyond(), MSVehicle::planMoveInternal(), MSLane::planMovements(), and MSLane::updateLeaderInfo().
clear()
void MSLeaderInfo::clear () virtual
discard all information
Reimplemented in MSCriticalFollowerDistanceInfo, and MSLeaderDistanceInfo.
Definition at line 101 of file MSLeaderInfo.cpp.
References egoLeftMost, egoRightMost, myFreeSublanes, and myVehicles.
Referenced by MSLeaderDistanceInfo::addLeader(), MSCriticalFollowerDistanceInfo::addLeader(), MSLeaderDistanceInfo::clear(), and MSVehicle::planMoveInternal().
getSublaneBorders()
void MSLeaderInfo::getSublaneBorders (int sublane, double latOffset, double & rightSide, double & leftSide) const
Definition at line 152 of file MSLeaderInfo.cpp.
References MSGlobals::gLateralResolution, MIN2(), myVehicles, and myWidth.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLCM_SL2015::updateGaps().
getSubLanes()
void MSLeaderInfo::getSubLanes (const MSVehicle * veh, double latOffset, int & rightmost, int & leftmost) const
Definition at line 112 of file MSLeaderInfo.cpp.
References DELTA_T, MSVehicle::getActionStepLength(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getManeuverDist(), MSVehicleType::getMaxSpeedLat(), MSAbstractLaneChangeModel::getSpeedLat(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, MAX2(), MIN2(), myVehicles, myWidth, and NUMERICAL_EPS.
Referenced by MSVehicle::adaptToLeaders(), MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), MSLeaderInfo(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
hasStoppedVehicle()
bool MSLeaderInfo::hasStoppedVehicle () const
whether a stopped vehicle is leader
Definition at line 185 of file MSLeaderInfo.cpp.
References myHasVehicles, and myVehicles.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkStrategicChange(), and hasVehicles().
hasVehicles()
bool MSLeaderInfo::hasVehicles () const inline
Definition at line 102 of file MSLeaderInfo.h.
References hasStoppedVehicle(), myHasVehicles, and toString().
Referenced by MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitFollowSpeed(), MSLane::isInsertionSuccess(), and MSLCM_SL2015::updateGaps().
numFreeSublanes()
int MSLeaderInfo::numFreeSublanes () const inline
Definition at line 98 of file MSLeaderInfo.h.
References myFreeSublanes.
Referenced by MSLane::getFollowersOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), and MSLane::isInsertionSuccess().
numSublanes()
int MSLeaderInfo::numSublanes () const inline
Definition at line 94 of file MSLeaderInfo.h.
References myVehicles.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::computeSublaneShift(), MSLane::detectCollisions(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLCM_SL2015::getLongest(), MSLCM_SL2015::getSlowest(), MSEdge::initialize(), MSLane::isInsertionSuccess(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLCM_SL2015::updateGaps().
operator[]()
const MSVehicle * MSLeaderInfo::operator[] (int sublane) const
return the vehicle for the given sublane
Definition at line 161 of file MSLeaderInfo.cpp.
References myVehicles.
Referenced by MSLeaderDistanceInfo::addLeader().
toString()
std::string MSLeaderInfo::toString () const virtual
print a debugging representation
Reimplemented in MSCriticalFollowerDistanceInfo, and MSLeaderDistanceInfo.
Definition at line 169 of file MSLeaderInfo.cpp.
References Named::getIDSecure(), myFreeSublanes, and myVehicles.
Referenced by MSVehicle::adaptToLeaders(), MSLeaderDistanceInfo::addLeader(), MSCriticalFollowerDistanceInfo::addLeader(), MSVehicle::checkLinkLeader(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSLane::getLeadersOnConsecutive(), hasVehicles(), MSLane::isInsertionSuccess(), and MSLane::planMovements().
Field Documentation
egoLeftMost
int MSLeaderInfo::egoLeftMost protected
Definition at line 127 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), and MSLeaderInfo().
egoRightMost
int MSLeaderInfo::egoRightMost protected
borders of the ego vehicle for filtering of free sublanes
Definition at line 126 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), and MSLeaderInfo().
myFreeSublanes
int MSLeaderInfo::myFreeSublanes protected
the number of free sublanes
Definition at line 123 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), MSLeaderInfo(), numFreeSublanes(), toString(), MSLeaderDistanceInfo::toString(), and MSCriticalFollowerDistanceInfo::toString().
myHasVehicles
bool MSLeaderInfo::myHasVehicles protected
Definition at line 129 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), hasStoppedVehicle(), and hasVehicles().
myVehicles
std::vector<const MSVehicle*> MSLeaderInfo::myVehicles protected
Definition at line 118 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), MSLeaderDistanceInfo::clear(), MSCriticalFollowerDistanceInfo::clear(), getSublaneBorders(), getSubLanes(), hasStoppedVehicle(), MSLeaderDistanceInfo::MSLeaderDistanceInfo(), MSLeaderInfo(), numSublanes(), operator[](), MSLeaderDistanceInfo::operator[](), toString(), MSLeaderDistanceInfo::toString(), and MSCriticalFollowerDistanceInfo::toString().
myWidth
double MSLeaderInfo::myWidth protected
the width of the lane to which this instance applies
Definition at line 116 of file MSLeaderInfo.h.
Referenced by getSublaneBorders(), and getSubLanes().
The documentation for this class was generated from the following files:
MSLeaderInfo.h
MSLeaderInfo.cpp