SUMO - Simulation of Urban MObility: GUILoadThread Class Reference
GUILoadThread Class Reference
#include <GUILoadThread.h>
Public Types
enum { ID_THREAD_EVENT }
Public Member Functions
const std::string & getFileName () const
GUILoadThread (FXApp *app, GUIApplicationWindow *mw, MFXEventQue< GUIEvent *> &eq, FXEX::FXThreadEvent &ev)
constructor
void loadConfigOrNet (const std::string &file, bool isNet)
begins the loading of the given file
long onThreadEvent (FXObject *, FXSelector, void *)
long onThreadSignal (FXObject *, FXSelector, void *)
void retrieveMessage (const MsgHandler::MsgType type, const std::string &msg)
Retrieves messages from the loading module.
FXint run ()
void signal ()
void signal (FXuint seltype)
virtual ~GUILoadThread ()
destructor
Static Public Member Functions
static void sleep (long ms)
Protected Member Functions
void submitEndAndCleanup (GUINet *net, const SUMOTime simStartTime, const SUMOTime simEndTime, const std::vector< std::string > &guiSettingsFiles=std::vector< std::string >(), const bool osgView=false)
Closes the loading process.
Protected Attributes
OutputDevice * myErrorRetriever
The instances of message retriever encapsulations Needed to be deleted from the handler later on.
MFXEventQue< GUIEvent * > & myEventQue
FXEX::FXThreadEvent & myEventThrow
std::string myFile
the path to load the simulation from
bool myLoadNet
Information whether only the network shall be loaded.
OutputDevice * myMessageRetriever
GUIApplicationWindow * myParent
the parent window to inform about the loading
std::string myTitle
the title string for the application
OutputDevice * myWarningRetriever
Detailed Description
Definition at line 56 of file GUILoadThread.h.
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
Enumerator
ID_THREAD_EVENT
Definition at line 52 of file FXSingleEventThread.h.
Constructor & Destructor Documentation
GUILoadThread()
GUILoadThread::GUILoadThread (FXApp * app, GUIApplicationWindow * mw, MFXEventQue< GUIEvent *> & eq, FXEX::FXThreadEvent & ev)
constructor
Definition at line 77 of file GUILoadThread.cpp.
References MsgHandler::addRetriever(), MsgHandler::getErrorInstance(), MsgHandler::MT_ERROR, MsgHandler::MT_MESSAGE, MsgHandler::MT_WARNING, myErrorRetriever, myMessageRetriever, myWarningRetriever, and retrieveMessage().
~GUILoadThread()
GUILoadThread::~GUILoadThread () virtual
destructor
Definition at line 88 of file GUILoadThread.cpp.
References myErrorRetriever, myMessageRetriever, and myWarningRetriever.
Member Function Documentation
getFileName()
const std::string & GUILoadThread::getFileName () const
Definition at line 276 of file GUILoadThread.cpp.
References myFile.
Referenced by GUIApplicationWindow::onUpdReload().
loadConfigOrNet()
void GUILoadThread::loadConfigOrNet (const std::string & file, bool isNet)
begins the loading of the given file
Definition at line 257 of file GUILoadThread.cpp.
References myFile, myLoadNet, and OptionsIO::setArgs().
Referenced by GUIApplicationWindow::loadConfigOrNet().
onThreadEvent()
long FXSingleEventThread::onThreadEvent (FXObject * , FXSelector , void *) inherited
Definition at line 131 of file FXSingleEventThread.cpp.
onThreadSignal()
long FXSingleEventThread::onThreadSignal (FXObject * , FXSelector , void *) inherited
Definition at line 116 of file FXSingleEventThread.cpp.
References PIPE_READ, FXEX::SEL_THREAD, and UNUSED_PARAMETER.
retrieveMessage()
void GUILoadThread::retrieveMessage (const MsgHandler::MsgType type, const std::string & msg)
Retrieves messages from the loading module.
Definition at line 268 of file GUILoadThread.cpp.
References MFXEventQue< T >::add(), myEventQue, myEventThrow, and FXEX::FXThreadEvent::signal().
Referenced by GUILoadThread().
run()
FXint GUILoadThread::run () virtual
starts the thread the thread ends after the net has been loaded
Reimplemented from FXSingleEventThread.
Definition at line 96 of file GUILoadThread.cpp.
References MFXEventQue< T >::add(), GUIApplicationWindow::addRecentFile(), MsgHandler::addRetriever(), GUITexturesHelper::allowTextures(), NLBuilder::build(), MSFrame::checkOptions(), MsgHandler::clear(), OptionsCont::clear(), MSNet::clearAll(), CMD_GET_GUI_VARIABLE, CMD_SET_GUI_VARIABLE, MSFrame::fillOptions(), GUIGlobals::gDemoAutoReload, OptionsCont::getBool(), OutputDevice::getDevice(), MSDevice::getEquipmentRNG(), MsgHandler::getErrorInstance(), OptionsCont::getFloat(), MsgHandler::getMessageInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), MSRouteHandler::getParsingRNG(), OptionsCont::getString(), OptionsCont::getStringVector(), MsgHandler::getWarningInstance(), GUIGlobals::gQuitOnEnd, GUIGlobals::gRunAfterLoad, GUIGlobals::gTrackerInterval, MSGlobals::gUseMesoSim, MsgHandler::inform(), GUINet::initGUIStructures(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), OptionsCont::isDefault(), OptionsCont::isSet(), myErrorRetriever, myEventQue, myEventThrow, myFile, myLoadNet, myMessageRetriever, myParent, myTitle, myWarningRetriever, TraCIServer::openSocket(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), MsgHandler::removeRetriever(), OptionsCont::resetWritable(), OptionsCont::set(), NLTriggerBuilder::setHandler(), MSFrame::setMSGlobals(), XMLSubSys::setValidation(), FXEX::FXThreadEvent::signal(), string2time(), submitEndAndCleanup(), GUIVisualizationSettings::UseMesoSim, and WRITE_ERROR.
signal() [1/2]
void FXSingleEventThread::signal () inherited
Definition at line 92 of file FXSingleEventThread.cpp.
References PIPE_WRITE, FXEX::SEL_THREAD, and UNUSED_PARAMETER.
signal() [2/2]
void FXSingleEventThread::signal (FXuint seltype) inherited
Definition at line 104 of file FXSingleEventThread.cpp.
References PIPE_WRITE, and UNUSED_PARAMETER.
sleep()
void FXSingleEventThread::sleep (long ms) static inherited
Definition at line 145 of file FXSingleEventThread.cpp.
Referenced by GUISUMOAbstractView::makeSnapshot(), FXSingleEventThread::run(), GUIRunThread::run(), and GUIRunThread::waitForSnapshots().
submitEndAndCleanup()
void GUILoadThread::submitEndAndCleanup (GUINet * net, const SUMOTime simStartTime, const SUMOTime simEndTime, const std::vector< std::string > & guiSettingsFiles = std::vector<std::string>(), const bool osgView = false) protected
Closes the loading process.
This method is called both on success and failure. All message callbacks to this instance are removed and the parent application is informed about the loading
Definition at line 240 of file GUILoadThread.cpp.
References MFXEventQue< T >::add(), MsgHandler::getErrorInstance(), MsgHandler::getMessageInstance(), MsgHandler::getWarningInstance(), myErrorRetriever, myEventQue, myEventThrow, myMessageRetriever, myTitle, myWarningRetriever, MsgHandler::removeRetriever(), and FXEX::FXThreadEvent::signal().
Referenced by run().
Field Documentation
myErrorRetriever
OutputDevice* GUILoadThread::myErrorRetriever protected
The instances of message retriever encapsulations Needed to be deleted from the handler later on.
Definition at line 99 of file GUILoadThread.h.
Referenced by GUILoadThread(), run(), submitEndAndCleanup(), and ~GUILoadThread().
myEventQue
MFXEventQue<GUIEvent*>& GUILoadThread::myEventQue protected
Definition at line 101 of file GUILoadThread.h.
Referenced by retrieveMessage(), run(), and submitEndAndCleanup().
myEventThrow
FXEX::FXThreadEvent& GUILoadThread::myEventThrow protected
Definition at line 103 of file GUILoadThread.h.
Referenced by retrieveMessage(), run(), and submitEndAndCleanup().
myFile
std::string GUILoadThread::myFile protected
the path to load the simulation from
Definition at line 92 of file GUILoadThread.h.
Referenced by getFileName(), loadConfigOrNet(), and run().
myLoadNet
bool GUILoadThread::myLoadNet protected
Information whether only the network shall be loaded.
Definition at line 106 of file GUILoadThread.h.
Referenced by loadConfigOrNet(), and run().
myMessageRetriever
OutputDevice * GUILoadThread::myMessageRetriever protected
Definition at line 99 of file GUILoadThread.h.
Referenced by GUILoadThread(), run(), submitEndAndCleanup(), and ~GUILoadThread().
myParent
GUIApplicationWindow* GUILoadThread::myParent protected
the parent window to inform about the loading
Definition at line 89 of file GUILoadThread.h.
Referenced by run().
myTitle
std::string GUILoadThread::myTitle protected
the title string for the application
Definition at line 95 of file GUILoadThread.h.
Referenced by run(), and submitEndAndCleanup().
myWarningRetriever
OutputDevice * GUILoadThread::myWarningRetriever protected
Definition at line 99 of file GUILoadThread.h.
Referenced by GUILoadThread(), run(), submitEndAndCleanup(), and ~GUILoadThread().
The documentation for this class was generated from the following files:
GUILoadThread.h
GUILoadThread.cpp