SUMO - Simulation of Urban MObility: MSAmitranTrajectories Class Reference
MSAmitranTrajectories Class Reference
Realises dumping the complete network state.
#include <MSAmitranTrajectories.h>
Static Public Member Functions
static void write (OutputDevice &of, const SUMOTime timestep)
Writes the complete network state into the given device.
Private Member Functions
MSAmitranTrajectories (const MSAmitranTrajectories &)
Invalidated copy constructor.
MSAmitranTrajectories & operator= (const MSAmitranTrajectories &)
Invalidated assignment operator.
Static Private Member Functions
static void writeVehicle (OutputDevice &of, const SUMOVehicle &veh, const SUMOTime timestep)
Writes the dump of the given vehicle into the given device.
Static Private Attributes
static std::set< std::string > myWrittenTypes
static std::map< std::string, int > myWrittenVehicles
Detailed Description
Realises dumping the complete network state.
The class offers a static method, which writes the complete dump of the given network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 57 of file MSAmitranTrajectories.h.
Constructor & Destructor Documentation
MSAmitranTrajectories()
MSAmitranTrajectories::MSAmitranTrajectories (const MSAmitranTrajectories &) private
Invalidated copy constructor.
Member Function Documentation
operator=()
MSAmitranTrajectories& MSAmitranTrajectories::operator= (const MSAmitranTrajectories &) private
Invalidated assignment operator.
write()
void MSAmitranTrajectories::write (OutputDevice & of, const SUMOTime timestep) static
Writes the complete network state into the given device.
Opens the current time step, goes through the vehicles and writes each using writeVehicle.
Parameters
[in] of The output device to use
[in] timestep The current time step
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 51 of file MSAmitranTrajectories.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), and writeVehicle().
Referenced by MSNet::writeOutput().
writeVehicle()
void MSAmitranTrajectories::writeVehicle (OutputDevice & of, const SUMOVehicle & veh, const SUMOTime timestep) static private
Writes the dump of the given vehicle into the given device.
Parameters
[in] of The output device to use
[in] veh The vehicle to dump
[in] timestep The current time step
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 60 of file MSAmitranTrajectories.cpp.
References OutputDevice::closeTag(), SUMOVehicle::getAcceleration(), PollutantsInterface::getAmitranVehicleClass(), SUMOVehicle::getDeparture(), MSVehicleType::getEmissionClass(), PollutantsInterface::getEuroClass(), PollutantsInterface::getFuel(), SUMOVehicle::getID(), MSVehicleType::getID(), MSVehicleType::getNumericalID(), SUMOVehicle::getSpeed(), SUMOVehicle::getVehicleType(), PollutantsInterface::getWeight(), SUMOVehicle::isOnRoad(), myWrittenTypes, myWrittenVehicles, OutputDevice::openTag(), STEPS2MS, SUMO_ATTR_ACCELERATION, SUMO_ATTR_ACTORCONFIG, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_ID, SUMO_ATTR_REF, SUMO_ATTR_SPEED, SUMO_ATTR_STARTTIME, SUMO_ATTR_TIME, SUMO_ATTR_VEHICLE, SUMO_ATTR_VEHICLECLASS, SUMO_ATTR_WEIGHT, SUMO_TAG_ACTORCONFIG, SUMO_TAG_MOTIONSTATE, SUMO_TAG_VEHICLE, toString(), and OutputDevice::writeAttr().
Referenced by write().
Field Documentation
myWrittenTypes
std::set< std::string > MSAmitranTrajectories::myWrittenTypes static private
Definition at line 83 of file MSAmitranTrajectories.h.
Referenced by writeVehicle().
myWrittenVehicles
std::map< std::string, int > MSAmitranTrajectories::myWrittenVehicles static private
Definition at line 84 of file MSAmitranTrajectories.h.
Referenced by writeVehicle().
The documentation for this class was generated from the following files:
MSAmitranTrajectories.h
MSAmitranTrajectories.cpp