SUMO - Simulation of Urban MObility: FXSingleEventThread Class Reference
FXSingleEventThread Class Reference
#include <FXSingleEventThread.h>
Public Types
enum { ID_THREAD_EVENT }
Public Member Functions
FXSingleEventThread (FXApp *a, MFXInterThreadEventClient *client)
long onThreadEvent (FXObject *, FXSelector, void *)
long onThreadSignal (FXObject *, FXSelector, void *)
virtual FXint run ()
void signal ()
void signal (FXuint seltype)
virtual ~FXSingleEventThread ()
Static Public Member Functions
static void sleep (long ms)
Protected Member Functions
FXSingleEventThread ()
Private Member Functions
FXSingleEventThread (const FXSingleEventThread &)
FXSingleEventThread & operator= (const FXSingleEventThread &)
Private Attributes
FXEX::FXThreadEventHandle event
FXApp * myApp
MFXInterThreadEventClient * myClient
Detailed Description
Definition at line 41 of file FXSingleEventThread.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_THREAD_EVENT
Definition at line 52 of file FXSingleEventThread.h.
Constructor & Destructor Documentation
FXSingleEventThread() [1/3]
FXSingleEventThread::FXSingleEventThread (const FXSingleEventThread &) private
FXSingleEventThread() [2/3]
FXSingleEventThread::FXSingleEventThread (FXApp * a, MFXInterThreadEventClient * client)
Definition at line 61 of file FXSingleEventThread.cpp.
References ID_THREAD_EVENT, PIPE_READ, and UNUSED_PARAMETER.
~FXSingleEventThread()
FXSingleEventThread::~FXSingleEventThread () virtual
Definition at line 78 of file FXSingleEventThread.cpp.
References PIPE_READ, and PIPE_WRITE.
Referenced by run().
FXSingleEventThread() [3/3]
FXSingleEventThread::FXSingleEventThread () inline protected
Definition at line 80 of file FXSingleEventThread.h.
Member Function Documentation
onThreadEvent()
long FXSingleEventThread::onThreadEvent (FXObject * , FXSelector , void *)
Definition at line 131 of file FXSingleEventThread.cpp.
onThreadSignal()
long FXSingleEventThread::onThreadSignal (FXObject * , FXSelector , void *)
Definition at line 116 of file FXSingleEventThread.cpp.
References PIPE_READ, FXEX::SEL_THREAD, and UNUSED_PARAMETER.
operator=()
FXSingleEventThread& FXSingleEventThread::operator= (const FXSingleEventThread &) private
run()
virtual FXint FXSingleEventThread::run () inline virtual
Reimplemented in GUIRunThread, GUILoadThread, and GNELoadThread.
Definition at line 67 of file FXSingleEventThread.h.
References sleep(), and ~FXSingleEventThread().
signal() [1/2]
void FXSingleEventThread::signal ()
Definition at line 92 of file FXSingleEventThread.cpp.
References PIPE_WRITE, FXEX::SEL_THREAD, and UNUSED_PARAMETER.
signal() [2/2]
void FXSingleEventThread::signal (FXuint seltype)
Definition at line 104 of file FXSingleEventThread.cpp.
References PIPE_WRITE, and UNUSED_PARAMETER.
sleep()
void FXSingleEventThread::sleep (long ms) static
Definition at line 145 of file FXSingleEventThread.cpp.
Referenced by GUISUMOAbstractView::makeSnapshot(), run(), GUIRunThread::run(), and GUIRunThread::waitForSnapshots().
Field Documentation
event
FXEX::FXThreadEventHandle FXSingleEventThread::event private
Definition at line 45 of file FXSingleEventThread.h.
myApp
FXApp* FXSingleEventThread::myApp private
Definition at line 76 of file FXSingleEventThread.h.
myClient
MFXInterThreadEventClient* FXSingleEventThread::myClient private
Definition at line 77 of file FXSingleEventThread.h.
The documentation for this class was generated from the following files:
FXSingleEventThread.h
FXSingleEventThread.cpp