SUMO - Simulation of Urban MObility: NIVissimAbstractEdge Class Reference
NIVissimAbstractEdge Class Reference abstract
#include <NIVissimAbstractEdge.h>
Public Member Functions
void addDisturbance (int disturbance)
virtual void buildGeom ()=0
bool crossesEdge (NIVissimAbstractEdge *c) const
Position crossesEdgeAtPoint (NIVissimAbstractEdge *c) const
const std::vector< int > & getDisturbances () const
const PositionVector & getGeometry () const
Position getGeomPosition (double pos) const
int getID () const
bool hasNodeCluster () const
NIVissimAbstractEdge (int id, const PositionVector &geom)
bool overlapsWith (const AbstractPoly &p, double offset=0.0) const
virtual void setNodeCluster (int nodeid)=0
void splitAssigning ()
virtual ~NIVissimAbstractEdge ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int id, NIVissimAbstractEdge *e)
static NIVissimAbstractEdge * dictionary (int id)
static std::vector< int > getWithin (const AbstractPoly &p, double offset=0.0)
static void splitAndAssignToNodes ()
Protected Attributes
std::vector< int > myDisturbances
PositionVector myGeom
int myID
int myNode
Private Types
typedef std::map< int, NIVissimAbstractEdge * > DictType
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 43 of file NIVissimAbstractEdge.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimAbstractEdge*> NIVissimAbstractEdge::DictType private
Definition at line 78 of file NIVissimAbstractEdge.h.
Constructor & Destructor Documentation
NIVissimAbstractEdge()
NIVissimAbstractEdge::NIVissimAbstractEdge (int id, const PositionVector & geom)
Definition at line 45 of file NIVissimAbstractEdge.cpp.
References dictionary(), myGeom, PositionVector::push_back_noDoublePos(), toString(), NBNetBuilder::transformCoordinate(), and WRITE_WARNING.
~NIVissimAbstractEdge()
NIVissimAbstractEdge::~NIVissimAbstractEdge () virtual
Definition at line 61 of file NIVissimAbstractEdge.cpp.
Member Function Documentation
addDisturbance()
void NIVissimAbstractEdge::addDisturbance (int disturbance)
Definition at line 174 of file NIVissimAbstractEdge.cpp.
References myDisturbances.
buildGeom()
virtual void NIVissimAbstractEdge::buildGeom () pure virtual
Implemented in NIVissimConnection, and NIVissimEdge.
Referenced by NIVissimNodeCluster::buildNBNode().
clearDict()
void NIVissimAbstractEdge::clearDict () static
Definition at line 159 of file NIVissimAbstractEdge.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
crossesEdge()
bool NIVissimAbstractEdge::crossesEdge (NIVissimAbstractEdge * c) const
Definition at line 117 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersects(), and myGeom.
Referenced by NIVissimNodeCluster::buildNBNode().
crossesEdgeAtPoint()
Position NIVissimAbstractEdge::crossesEdgeAtPoint (NIVissimAbstractEdge * c) const
Definition at line 123 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersectionPosition2D(), and myGeom.
Referenced by NIVissimDisturbance::addToNode(), and NIVissimNodeCluster::buildNBNode().
dictionary() [1/2]
bool NIVissimAbstractEdge::dictionary (int id, NIVissimAbstractEdge * e) static
Definition at line 65 of file NIVissimAbstractEdge.cpp.
References myDict.
Referenced by NIVissimNodeCluster::buildNBNode(), NIVissimDisturbance::computeBounding(), NIVissimDisturbance::dict_SetDisturbances(), NIVissimExtendedEdgePoint::getGeomPosition(), NIVissimTL::NIVissimTLSignal::getPosition(), and NIVissimAbstractEdge().
dictionary() [2/2]
NIVissimAbstractEdge * NIVissimAbstractEdge::dictionary (int id) static
Definition at line 76 of file NIVissimAbstractEdge.cpp.
References myDict.
getDisturbances()
const std::vector< int > & NIVissimAbstractEdge::getDisturbances () const
Definition at line 180 of file NIVissimAbstractEdge.cpp.
References myDisturbances.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
getGeometry()
const PositionVector & NIVissimAbstractEdge::getGeometry () const
Definition at line 168 of file NIVissimAbstractEdge.cpp.
References myGeom.
Referenced by NIVissimEdge::dict_checkEdges2Join(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::same_direction_sorter::operator()(), and NIVissimConnectionCluster::recomputeBoundary().
getGeomPosition()
Position NIVissimAbstractEdge::getGeomPosition (double pos) const
Definition at line 87 of file NIVissimAbstractEdge.cpp.
References PositionVector::extrapolate(), PositionVector::length(), myGeom, and PositionVector::positionAtOffset().
Referenced by NIVissimDistrictConnection::geomPosition().
getID()
int NIVissimAbstractEdge::getID () const
Definition at line 154 of file NIVissimAbstractEdge.cpp.
References myID.
Referenced by NIVissimDisturbance::addToNode(), NIVissimConnection::buildEdgeConnections(), NIVissimEdge::dict_checkEdges2Join(), NIVissimEdge::getConnectionTo(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), and NIVissimConnectionCluster::removeConnections().
getWithin()
std::vector< int > NIVissimAbstractEdge::getWithin (const AbstractPoly & p, double offset = 0.0) static
Definition at line 129 of file NIVissimAbstractEdge.cpp.
References myDict, myID, and overlapsWith().
hasNodeCluster()
bool NIVissimAbstractEdge::hasNodeCluster () const
Definition at line 148 of file NIVissimAbstractEdge.cpp.
References myNode.
overlapsWith()
bool NIVissimAbstractEdge::overlapsWith (const AbstractPoly & p, double offset = 0.0) const
Definition at line 142 of file NIVissimAbstractEdge.cpp.
References myGeom, and PositionVector::overlapsWith().
Referenced by getWithin().
setNodeCluster()
virtual void NIVissimAbstractEdge::setNodeCluster (int nodeid) pure virtual
Implemented in NIVissimConnection, and NIVissimEdge.
splitAndAssignToNodes()
void NIVissimAbstractEdge::splitAndAssignToNodes () static
Definition at line 102 of file NIVissimAbstractEdge.cpp.
References myDict, and splitAssigning().
splitAssigning()
void NIVissimAbstractEdge::splitAssigning ()
Definition at line 110 of file NIVissimAbstractEdge.cpp.
Referenced by splitAndAssignToNodes().
Field Documentation
myDict
NIVissimAbstractEdge::DictType NIVissimAbstractEdge::myDict static private
Definition at line 79 of file NIVissimAbstractEdge.h.
Referenced by clearDict(), dictionary(), getWithin(), and splitAndAssignToNodes().
myDisturbances
std::vector<int> NIVissimAbstractEdge::myDisturbances protected
Definition at line 74 of file NIVissimAbstractEdge.h.
Referenced by addDisturbance(), and getDisturbances().
myGeom
PositionVector NIVissimAbstractEdge::myGeom protected
Definition at line 73 of file NIVissimAbstractEdge.h.
Referenced by NIVissimConnection::buildGeom(), NIVissimEdge::buildNBEdge(), crossesEdge(), crossesEdgeAtPoint(), NIVissimEdge::getBegin2D(), NIVissimEdge::getEnd2D(), NIVissimEdge::getFromNode(), getGeometry(), getGeomPosition(), NIVissimEdge::getLength(), NIVissimEdge::getToNode(), NIVissimAbstractEdge(), overlapsWith(), and NIVissimEdge::resolveSameNode().
myID
int NIVissimAbstractEdge::myID protected
Definition at line 72 of file NIVissimAbstractEdge.h.
Referenced by NIVissimEdge::buildNBEdge(), NIVissimEdge::getFromNode(), getID(), NIVissimEdge::getToNode(), getWithin(), NIVissimEdge::NIVissimEdge(), NIVissimEdge::resolveSameNode(), and NIVissimEdge::setDistrictSpeed().
myNode
int NIVissimAbstractEdge::myNode protected
Definition at line 75 of file NIVissimAbstractEdge.h.
Referenced by hasNodeCluster(), NIVissimEdge::setNodeCluster(), and NIVissimConnection::setNodeCluster().
The documentation for this class was generated from the following files:
NIVissimAbstractEdge.h
NIVissimAbstractEdge.cpp