SUMO - Simulation of Urban MObility: ROPerson::PlanItem Class Reference
ROPerson::PlanItem Class Reference abstract
Every person has a plan comprising of multiple planItems.
#include <ROPerson.h>
Public Member Functions
virtual void addTripItem (TripItem *)
virtual const ROEdge * getDestination () const =0
virtual const ROEdge * getOrigin () const =0
virtual bool isStop () const
virtual bool needsRouting () const
virtual void saveAsXML (OutputDevice &os, const bool extended) const =0
virtual void saveVehicles (OutputDevice &, OutputDevice *const, bool, OptionsCont &) const
virtual ~PlanItem ()
Destructor.
Detailed Description
Every person has a plan comprising of multiple planItems.
Definition at line 86 of file ROPerson.h.
Constructor & Destructor Documentation
~PlanItem()
virtual ROPerson::PlanItem::~PlanItem () inline virtual
Destructor.
Definition at line 89 of file ROPerson.h.
Member Function Documentation
addTripItem()
virtual void ROPerson::PlanItem::addTripItem (TripItem *) inline virtual
Reimplemented in ROPerson::PersonTrip.
Definition at line 91 of file ROPerson.h.
References getDestination(), and getOrigin().
getDestination()
virtual const ROEdge* ROPerson::PlanItem::getDestination () const pure virtual
Implemented in ROPerson::PersonTrip, and ROPerson::Stop.
Referenced by addTripItem(), and ROPerson::TripItem::~TripItem().
getOrigin()
virtual const ROEdge* ROPerson::PlanItem::getOrigin () const pure virtual
Implemented in ROPerson::PersonTrip, and ROPerson::Stop.
Referenced by addTripItem(), and ROPerson::TripItem::~TripItem().
isStop()
virtual bool ROPerson::PlanItem::isStop () const inline virtual
Reimplemented in ROPerson::Stop.
Definition at line 98 of file ROPerson.h.
needsRouting()
virtual bool ROPerson::PlanItem::needsRouting () const inline virtual
Reimplemented in ROPerson::PersonTrip.
Definition at line 101 of file ROPerson.h.
saveAsXML()
virtual void ROPerson::PlanItem::saveAsXML (OutputDevice & os, const bool extended) const pure virtual
Implemented in ROPerson::PersonTrip, and ROPerson::Stop.
Referenced by ROPerson::getDepartEdge(), ROPerson::Ride::getDestination(), ROPerson::Walk::getDestination(), saveVehicles(), and ROPerson::TripItem::~TripItem().
saveVehicles()
virtual void ROPerson::PlanItem::saveVehicles (OutputDevice & , OutputDevice * const, bool , OptionsCont &) const inline virtual
Reimplemented in ROPerson::PersonTrip.
Definition at line 96 of file ROPerson.h.
References saveAsXML().
Referenced by ROPerson::PersonTrip::needsRouting().
The documentation for this class was generated from the following file:
ROPerson.h