SUMO - Simulation of Urban MObility: MSPModel_Striping::PState Class Reference
MSPModel_Striping::PState Class Reference
Container for pedestrian state and individual position update function.
#include <MSPModel_Striping.h>
Public Member Functions
double distanceTo (const Obstacle &obs, const bool includeMinGap=true) const
double distToLaneEnd () const
the absolute distance to the end of the lane in walking direction (or to the arrivalPos)
double getImpatience (SUMOTime now) const
returns the impatience
double getLength () const
return the length of the pedestrian
double getMaxX (const bool includeMinGap=true) const
return the maximum position on the lane
double getMinGap () const
return the minimum gap of the pedestrian
double getMinX (const bool includeMinGap=true) const
return the minimum position on the lane
bool ignoreRed (const MSLink *link) const
whether the pedestrian may ignore a red light
void mergeObstacles (Obstacles &into, const Obstacles &obs2)
replace obstacles in the first vector with obstacles from the second if they are closer to me
bool moveToNextLane (SUMOTime currentTime)
return whether this pedestrian has passed the end of the current lane and update myRelX if so
int otherStripe () const
int otherStripe (const double relY) const
PState (MSPerson *person, MSPerson::MSPersonStage_Walking *stage, const MSLane *lane)
int stripe () const
void walk (const Obstacles &obs, SUMOTime currentTime)
perform position update
~PState ()
double getEdgePos (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
abstract methods inherited from PedestrianState
Position getPosition (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the network coordinate of the person
double getAngle (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the direction in which the person faces in degrees
SUMOTime getWaitingTime (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the time the person spent standing
double getSpeed (const MSPerson::MSPersonStage_Walking &stage) const
return the current speed of the person
const MSEdge * getNextEdge (const MSPerson::MSPersonStage_Walking &stage) const
return the list of internal edges if the pedestrian is on an intersection
void moveToXY (MSPerson *p, Position pos, MSLane *lane, double lanePos, double lanePosLat, double angle, int routeOffset, const ConstMSEdgeVector &edges, SUMOTime t)
try to move person to the given position
Static Public Member Functions
static int stripe (const double relY)
Data Fields
bool myAmJammed
whether the person is jammed
int myDir
the walking direction on the current lane (1 forward, -1 backward)
const MSLane * myLane
the current lane of this pedestrian
NextLaneInfo myNLI
information about the upcoming lane
MSPerson * myPerson
double myRelX
the advancement along the current lane
double myRelY
the orthogonal shift on the current lane
double mySpeed
the current walking speed
MSPerson::MSPersonStage_Walking * myStage
SUMOTime myWaitingTime
the consecutive time spent at speed 0
bool myWaitingToEnter
whether the pedestrian is waiting to start its walk
WalkingAreaPath * myWalkingAreaPath
the current walkingAreaPath or 0
Detailed Description
Container for pedestrian state and individual position update function.
Definition at line 266 of file MSPModel_Striping.h.
Constructor & Destructor Documentation
PState()
MSPModel_Striping::PState::PState (MSPerson * person, MSPerson::MSPersonStage_Walking * stage, const MSLane * lane)
Definition at line 1103 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, MSPModel::canTraverse(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), DEBUGCOND, EDGEFUNC_NORMAL, MSPModel::FORWARD, MSPModel_Striping::getArbitraryPath(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSLane::getEdge(), MSEdge::getFromJunction(), Named::getID(), MSTransportable::getID(), MSNet::getInstance(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSPModel_Striping::getNextLane(), MSNet::getPedestrianRouter(), MSPerson::MSPersonStage_Walking::getRoute(), MSEdge::getToJunction(), MSLane::getVehicleNumberWithPartials(), myDir, myNLI, myPerson, myRelX, myRelY, myStage, myWalkingAreaPath, MSPModel_Striping::numStripes(), MSPModel_Striping::stripeWidth, and toString().
~PState()
MSPModel_Striping::PState::~PState () inline
Definition at line 285 of file MSPModel_Striping.h.
Member Function Documentation
distanceTo()
double MSPModel_Striping::PState::distanceTo (const Obstacle & obs, const bool includeMinGap = true) const
Definition at line 1665 of file MSPModel_Striping.cpp.
References MSPModel_Striping::DIST_BEHIND, MSPModel_Striping::DIST_OVERLAP, MSPModel::FORWARD, getMaxX(), getMinX(), myDir, MSPModel_Striping::Obstacle::xBack, and MSPModel_Striping::Obstacle::xFwd.
Referenced by MSPModel_Striping::getNeighboringObstacles(), mergeObstacles(), MSPModel_Striping::moveInDirectionOnLane(), and walk().
distToLaneEnd()
double MSPModel_Striping::PState::distToLaneEnd () const
the absolute distance to the end of the lane in walking direction (or to the arrivalPos)
Definition at line 1237 of file MSPModel_Striping.cpp.
References MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getArrivalPos(), MSLane::getLength(), MSPerson::MSPersonStage_Walking::getNextRouteEdge(), MSPModel_Striping::WalkingAreaPath::length, myDir, myLane, myRelX, myStage, myWalkingAreaPath, and POSITION_EPS.
Referenced by MSPModel_Striping::arriveAndAdvance(), MSPModel_Striping::moveInDirectionOnLane(), and moveToNextLane().
getAngle()
double MSPModel_Striping::PState::getAngle (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the direction in which the person faces in degrees
Implements PedestrianState.
Definition at line 1605 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, MSLane::getShape(), M_PI, myDir, myLane, myRelX, myWalkingAreaPath, PositionVector::rotationAtOffset(), and MSPModel_Striping::WalkingAreaPath::shape.
getEdgePos()
double MSPModel_Striping::PState::getEdgePos (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
abstract methods inherited from PedestrianState
Implements PedestrianState.
Definition at line 1573 of file MSPModel_Striping.cpp.
References myRelX.
getImpatience()
double MSPModel_Striping::PState::getImpatience (SUMOTime now) const
returns the impatience
Definition at line 1566 of file MSPModel_Striping.cpp.
References MSVehicleType::getImpatience(), MSTransportable::getVehicleType(), MSPerson::MSPersonStage_Walking::getWaitingTime(), MAX2(), MSPModel_Striping::MAX_WAIT_TOLERANCE, MIN2(), myPerson, myStage, and STEPS2TIME.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
getLength()
double MSPModel_Striping::PState::getLength () const
return the length of the pedestrian
Definition at line 1188 of file MSPModel_Striping.cpp.
References MSVehicleType::getLength(), MSTransportable::getVehicleType(), and myPerson.
Referenced by MSPModel_Striping::blockedAtDist(), getMaxX(), getMinX(), and MSPModel_Striping::moveInDirectionOnLane().
getMaxX()
double MSPModel_Striping::PState::getMaxX (const bool includeMinGap = true) const
return the maximum position on the lane
Definition at line 1178 of file MSPModel_Striping.cpp.
References MSPModel::FORWARD, getLength(), getMinGap(), myDir, and myRelX.
Referenced by distanceTo(), and MSPModel_Striping::moveInDirectionOnLane().
getMinGap()
double MSPModel_Striping::PState::getMinGap () const
return the minimum gap of the pedestrian
Definition at line 1194 of file MSPModel_Striping.cpp.
References MSVehicleType::getMinGap(), MSTransportable::getVehicleType(), and myPerson.
Referenced by getMaxX(), getMinX(), and MSPModel_Striping::moveInDirectionOnLane().
getMinX()
double MSPModel_Striping::PState::getMinX (const bool includeMinGap = true) const
return the minimum position on the lane
Definition at line 1168 of file MSPModel_Striping.cpp.
References MSPModel::FORWARD, getLength(), getMinGap(), myDir, and myRelX.
Referenced by distanceTo(), and MSPModel_Striping::moveInDirectionOnLane().
getNextEdge()
const MSEdge * MSPModel_Striping::PState::getNextEdge (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the list of internal edges if the pedestrian is on an intersection
Implements PedestrianState.
Definition at line 1632 of file MSPModel_Striping.cpp.
References MSLane::getEdge(), MSPModel_Striping::NextLaneInfo::lane, and myNLI.
getPosition()
Position MSPModel_Striping::PState::getPosition (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the network coordinate of the person
Implements PedestrianState.
Definition at line 1579 of file MSPModel_Striping.cpp.
References MSTransportable::Stage::getLanePosition(), MSLane::getWidth(), Position::INVALID, myLane, myRelX, myRelY, myWalkingAreaPath, PositionVector::positionAtOffset(), MSPModel_Striping::WalkingAreaPath::shape, and MSPModel_Striping::stripeWidth.
Referenced by MSPModel_Striping::getNextLaneObstacles(), and MSPModel_Striping::moveInDirection().
getSpeed()
double MSPModel_Striping::PState::getSpeed (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the current speed of the person
Implements PedestrianState.
Definition at line 1626 of file MSPModel_Striping.cpp.
References mySpeed.
getWaitingTime()
SUMOTime MSPModel_Striping::PState::getWaitingTime (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the time the person spent standing
Implements PedestrianState.
Definition at line 1620 of file MSPModel_Striping.cpp.
References myWaitingTime.
ignoreRed()
bool MSPModel_Striping::PState::ignoreRed (const MSLink * link) const
whether the pedestrian may ignore a red light
Definition at line 1697 of file MSPModel_Striping.cpp.
References DEBUGCOND, MSNet::getInstance(), SUMOVTypeParameter::getJMParam(), MSLink::getLastStateChange(), MSVehicleType::getParameter(), MSTransportable::getVehicleType(), MSLink::haveRed(), myPerson, SIMTIME, STEPS2TIME, and SUMO_ATTR_JM_DRIVE_AFTER_RED_TIME.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
mergeObstacles()
void MSPModel_Striping::PState::mergeObstacles (Obstacles & into, const Obstacles & obs2)
replace obstacles in the first vector with obstacles from the second if they are closer to me
Definition at line 1684 of file MSPModel_Striping.cpp.
References distanceTo(), and gDebugFlag1.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
moveToNextLane()
bool MSPModel_Striping::PState::moveToNextLane (SUMOTime currentTime)
return whether this pedestrian has passed the end of the current lane and update myRelX if so
Definition at line 1248 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, DEBUGCOND, MSPModel_Striping::NextLaneInfo::dir, distToLaneEnd(), EDGEFUNC_NORMAL, MSPModel::FORWARD, MSPModel_Striping::WalkingAreaPath::from, MSPerson::MSPersonStage_Walking::getArrivalPos(), MSLane::getEdge(), MSEdge::getFromJunction(), MSEdge::getFunction(), Named::getID(), MSTransportable::getID(), Named::getIDSecure(), MSLane::getLength(), MSPModel_Striping::getNextLane(), MSPerson::MSPersonStage_Walking::getNextRouteEdge(), OptionsCont::getOptions(), MSPerson::MSPersonStage_Walking::getRouteEdge(), MSPModel_Striping::getStripeOffset(), MSEdge::getToJunction(), MSEdge::isWalkingArea(), MSPModel_Striping::NextLaneInfo::lane, MSPModel_Striping::WalkingAreaPath::length, MSPerson::MSPersonStage_Walking::moveToNextEdge(), myDir, myLane, myNLI, myPerson, myRelX, myRelY, myStage, myWalkingAreaPath, MSPModel_Striping::myWalkingAreaPaths, MSPModel_Striping::numStripes(), MSPModel_Striping::WalkingAreaPath::shape, SIMTIME, MSPModel_Striping::stripeWidth, MSPModel_Striping::WalkingAreaPath::to, and MSPModel::UNDEFINED_DIRECTION.
Referenced by MSPModel_Striping::arriveAndAdvance().
moveToXY()
void MSPModel_Striping::PState::moveToXY (MSPerson * p, Position pos, MSLane * lane, double lanePos, double lanePosLat, double angle, int routeOffset, const ConstMSEdgeVector & edges, SUMOTime t) virtual
try to move person to the given position
Reimplemented from PedestrianState.
Definition at line 1637 of file MSPModel_Striping.cpp.
References MSLane::getWidth(), myLane, myRelX, myRelY, MSPModel_Striping::stripeWidth, and UNUSED_PARAMETER.
otherStripe() [1/2]
int MSPModel_Striping::PState::otherStripe () const
Definition at line 1231 of file MSPModel_Striping.cpp.
References MAX2(), MIN2(), myLane, myRelY, and MSPModel_Striping::numStripes().
Referenced by MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), and walk().
otherStripe() [2/2]
int MSPModel_Striping::PState::otherStripe (const double relY) const
Definition at line 1206 of file MSPModel_Striping.cpp.
References MSTransportable::getVehicleType(), MSVehicleType::getWidth(), MAX2(), myPerson, NUMERICAL_EPS, MSPModel_Striping::SQUEEZE, stripe(), and MSPModel_Striping::stripeWidth.
stripe() [1/2]
int MSPModel_Striping::PState::stripe () const
Definition at line 1225 of file MSPModel_Striping.cpp.
References MAX2(), MIN2(), myLane, myRelY, and MSPModel_Striping::numStripes().
Referenced by MSPModel_Striping::addCrossingVehs(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), otherStripe(), and walk().
stripe() [2/2]
int MSPModel_Striping::PState::stripe (const double relY) static
Definition at line 1200 of file MSPModel_Striping.cpp.
References MSPModel_Striping::stripeWidth.
walk()
void MSPModel_Striping::PState::walk (const Obstacles & obs, SUMOTime currentTime)
perform position update
Definition at line 1366 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, MSPModel_Striping::dawdling, MSPModel_Striping::DEBUG_PRINT(), DEBUGCOND, DELTA_T, DIST2SPEED, MSPModel_Striping::DIST_OVERLAP, distanceTo(), MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getEdge(), MSLane::getEdge(), Named::getID(), MSTransportable::getID(), MSNet::getInstance(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSNet::getPersonControl(), MSPerson::MSPersonStage_Walking::getWaitingTime(), MSPModel_Striping::INAPPROPRIATE_PENALTY, MSEdge::isCrossing(), MSEdge::isWalkingArea(), MSPModel_Striping::jamTime, MSPModel_Striping::LATERAL_PENALTY, MSPModel_Striping::LATERAL_SPEED_FACTOR, MSPModel_Striping::LOOKAHEAD_ONCOMING, MSPModel_Striping::LOOKAHEAD_SAMEDIR, MAX2(), MIN2(), MIN3(), MSPModel_Striping::MIN_STARTUP_DIST, myAmJammed, myDir, myLane, myPerson, myRelX, myRelY, mySpeed, myStage, myWaitingTime, myWaitingToEnter, NUMERICAL_EPS, MSPModel_Striping::numStripes(), MSPModel_Striping::OBSTACLE_END, MSPModel_Striping::OBSTACLE_PED, MSPModel_Striping::OBSTACLE_VEHICLE, MSPModel_Striping::OBSTRUCTED_PENALTY, MSPModel_Striping::OBSTRUCTION_THRESHOLD, MSPModel_Striping::ONCOMING_CONFLICT_PENALTY, otherStripe(), RandHelper::rand(), MSTransportableControl::registerJammed(), MSPModel_Striping::RESERVE_FOR_ONCOMING_FACTOR, MSPModel_Striping::RESERVE_FOR_ONCOMING_FACTOR_JUNCTIONS, SIMTIME, SPEED2DIST, stripe(), MSPModel_Striping::stripeWidth, SUMO_const_haltingSpeed, time2string(), toString(), and WRITE_WARNING.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
Field Documentation
myAmJammed
bool MSPModel_Striping::PState::myAmJammed
whether the person is jammed
Definition at line 307 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), and walk().
myDir
int MSPModel_Striping::PState::myDir
the walking direction on the current lane (1 forward, -1 backward)
Definition at line 295 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::arriveAndAdvance(), MSPModel_Striping::blockedAtDist(), distanceTo(), distToLaneEnd(), MSPModel_Striping::MovePedestrians::execute(), getAngle(), getMaxX(), getMinX(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), MSPModel_Striping::nextBlocking(), PState(), and walk().
myLane
const MSLane* MSPModel_Striping::PState::myLane
the current lane of this pedestrian
Definition at line 289 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::arriveAndAdvance(), distToLaneEnd(), getAngle(), getPosition(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), moveToXY(), otherStripe(), stripe(), and walk().
myNLI
NextLaneInfo MSPModel_Striping::PState::myNLI
information about the upcoming lane
Definition at line 303 of file MSPModel_Striping.h.
Referenced by getNextEdge(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), and PState().
myPerson
MSPerson* MSPModel_Striping::PState::myPerson
Definition at line 285 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::arriveAndAdvance(), MSPModel_Striping::blockedAtDist(), MSPModel_Striping::MovePedestrians::execute(), getImpatience(), getLength(), getMinGap(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), ignoreRed(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::by_xpos_sorter::operator()(), otherStripe(), PState(), and walk().
myRelX
double MSPModel_Striping::PState::myRelX
the advancement along the current lane
Definition at line 291 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::blockedAtDist(), distToLaneEnd(), MSPModel_Striping::MovePedestrians::execute(), getAngle(), getEdgePos(), getMaxX(), getMinX(), getPosition(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), moveToXY(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::by_xpos_sorter::operator()(), PState(), and walk().
myRelY
double MSPModel_Striping::PState::myRelY
the orthogonal shift on the current lane
Definition at line 293 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNextLaneObstacles(), getPosition(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), moveToXY(), MSPModel_Striping::nextBlocking(), otherStripe(), PState(), stripe(), and walk().
mySpeed
double MSPModel_Striping::PState::mySpeed
the current walking speed
Definition at line 297 of file MSPModel_Striping.h.
Referenced by getSpeed(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), and walk().
myStage
MSPerson::MSPersonStage_Walking* MSPModel_Striping::PState::myStage
Definition at line 287 of file MSPModel_Striping.h.
Referenced by distToLaneEnd(), getImpatience(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), PState(), and walk().
myWaitingTime
SUMOTime MSPModel_Striping::PState::myWaitingTime
the consecutive time spent at speed 0
Definition at line 301 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::blockedAtDist(), getWaitingTime(), and walk().
myWaitingToEnter
bool MSPModel_Striping::PState::myWaitingToEnter
whether the pedestrian is waiting to start its walk
Definition at line 299 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::Obstacle::Obstacle(), and walk().
myWalkingAreaPath
WalkingAreaPath* MSPModel_Striping::PState::myWalkingAreaPath
the current walkingAreaPath or 0
Definition at line 305 of file MSPModel_Striping.h.
Referenced by distToLaneEnd(), GUIPerson::drawAction_drawWalkingareaPath(), getAngle(), getPosition(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), and PState().
The documentation for this class was generated from the following files:
MSPModel_Striping.h
MSPModel_Striping.cpp