SUMO - Simulation of Urban MObility: AGActivityGen Class Reference
AGActivityGen Class Reference
Central object handling City, Activities and Trips.
#include <AGActivityGen.h>
Public Member Functions
AGActivityGen (std::string input, OutputDevice &output, RONet *net)
Constructor.
void importInfoCity ()
build the internal city
void makeActivityTrips (int days=1, int beginTime=0, int endTime=0)
build activities and trips of the population and generate routes
Protected Member Functions
void generateOutputFile (std::list< AGTrip > &trips)
generate the output file (trips or routes) using a trip list
bool timeTripValidation (const AGTrip &trip) const
validation: compatibility of the given trip
void varDepTime (AGTrip &trip) const
Protected Attributes
int beginTime
AGCity city
int durationInDays
int endTime
std::string inputFile
RONet * net
OutputDevice & outputFile
The generated routes.
Private Member Functions
AGActivityGen & operator= (const AGActivityGen &)
invalidated assignment operator
Detailed Description
Central object handling City, Activities and Trips.
Definition at line 55 of file AGActivityGen.h.
Constructor & Destructor Documentation
AGActivityGen()
AGActivityGen::AGActivityGen (std::string input, OutputDevice & output, RONet * net) inline
Constructor.
Parameters
[in] input input stat-file name (containing information about the city)
[in] output xml file in which we'll write the routes generated
[in] net network of the city
Definition at line 64 of file AGActivityGen.h.
References beginTime, endTime, importInfoCity(), and makeActivityTrips().
Member Function Documentation
generateOutputFile()
void AGActivityGen::generateOutputFile (std::list< AGTrip > & trips) protected
generate the output file (trips or routes) using a trip list
Parameters
[in] trips generated by the different activities
Definition at line 140 of file AGActivityGen.cpp.
References AGActivityTripWriter::addTrip(), AGTime::getDay(), AGTime::getHour(), AGTime::getMinute(), AGTime::getSecond(), and outputFile.
Referenced by makeActivityTrips().
importInfoCity()
void AGActivityGen::importInfoCity ()
build the internal city
TO CALL 1: First function to be called: imports the XML input file and generates the whole city.
Definition at line 52 of file AGActivityGen.cpp.
References AGCity::carAllocation(), city, AGCity::completeBusLines(), AGCity::completeStreets(), AGDataAndStatistics::consolidateStat(), AGCity::generatePopulation(), AGCity::generateWorkPositions(), inputFile, net, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PROGRESS_FAILED_MESSAGE, XMLSubSys::runParser(), AGCity::schoolAllocation(), AGCity::statData, and AGCity::workAllocation().
Referenced by AGActivityGen().
makeActivityTrips()
void AGActivityGen::makeActivityTrips (int days = 1, int beginTime = 0, int endTime = 0)
build activities and trips of the population and generate routes
TO CALL 2: generates City's Activity and the corresponding trips
Parameters
[in] days : duration of the simulation (>=0) (day of the end - day of the beginning)
[in] beginTime : instant of the simulation beginning (in the first day)
[in] endTime : instant of the simulation ending (in the last day) NOTE: if (days==0) : endTime > beginTime
EXAMPLE: if days=1, endTime=0, beginTime=0: The duration will be 24 hours from 12am to 12amof the next day
making the activity trips
validating the trips with the simulation's time limits
re-ordering of trips: SUMO needs routes ordered by departure time.
trip file generation
Definition at line 181 of file AGActivityGen.cpp.
References beginTime, city, durationInDays, endTime, AGActivities::generateActivityTrips(), generateOutputFile(), AGTrip::setType(), timeTripValidation(), AGActivities::trips, and varDepTime().
Referenced by AGActivityGen().
operator=()
AGActivityGen& AGActivityGen::operator= (const AGActivityGen &) private
invalidated assignment operator
timeTripValidation()
bool AGActivityGen::timeTripValidation (const AGTrip & trip) const protected
validation: compatibility of the given trip
Parameters
[in] trip to be validated
Returns
whether the trip is compatible with the time boundaries or not. for this begin, end and duration of the simulation must be defined
Definition at line 97 of file AGActivityGen.cpp.
References beginTime, durationInDays, endTime, AGTrip::getDay(), and AGTrip::getTime().
Referenced by makeActivityTrips().
varDepTime()
void AGActivityGen::varDepTime (AGTrip & trip) const protected
introduce a slight variation into the departure time of "default" vehicles
Parameters
[in] trip on which a random (normally distributed) variation will be tried
Definition at line 121 of file AGActivityGen.cpp.
References city, AGDataAndStatistics::departureVariation, AGTrip::getDay(), AGTrip::getTime(), AGTrip::getType(), RandHelper::randNorm(), AGTrip::setDay(), AGTrip::setDepTime(), and AGCity::statData.
Referenced by makeActivityTrips().
Field Documentation
beginTime
int AGActivityGen::beginTime protected
Definition at line 103 of file AGActivityGen.h.
Referenced by AGActivityGen(), makeActivityTrips(), and timeTripValidation().
city
AGCity AGActivityGen::city protected
Definition at line 101 of file AGActivityGen.h.
Referenced by importInfoCity(), makeActivityTrips(), and varDepTime().
durationInDays
int AGActivityGen::durationInDays protected
Definition at line 103 of file AGActivityGen.h.
Referenced by makeActivityTrips(), and timeTripValidation().
endTime
int AGActivityGen::endTime protected
Definition at line 103 of file AGActivityGen.h.
Referenced by AGActivityGen(), makeActivityTrips(), and timeTripValidation().
inputFile
std::string AGActivityGen::inputFile protected
Definition at line 94 of file AGActivityGen.h.
Referenced by importInfoCity().
net
RONet* AGActivityGen::net protected
Definition at line 98 of file AGActivityGen.h.
Referenced by importInfoCity().
outputFile
OutputDevice& AGActivityGen::outputFile protected
The generated routes.
Definition at line 96 of file AGActivityGen.h.
Referenced by generateOutputFile().
The documentation for this class was generated from the following files:
AGActivityGen.h
AGActivityGen.cpp