SUMO - Simulation of Urban MObility: FX::FXRealSpinDialDial Class Reference
FX::FXRealSpinDialDial Class Reference
Public Types
enum { ID_AUTOSPIN = FXDial::ID_LAST, ID_LAST }
Public Member Functions
FXRealSpinDialDial (FXComposite *p, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=DIAL_NORMAL, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
Construct a dial widget.
long onAuto (FXObject *, FXSelector, void *)
long onButtonPress (FXObject *, FXSelector, void *)
long onButtonRelease (FXObject *, FXSelector, void *)
long onKey (FXObject *, FXSelector, void *)
long onMotion (FXObject *, FXSelector, void *)
long onRightButtonPress (FXObject *, FXSelector, void *)
long onRightButtonRelease (FXObject *, FXSelector, void *)
Protected Member Functions
FXRealSpinDialDial ()
Private Member Functions
FXRealSpinDialDial (const FXRealSpinDialDial &)
FXRealSpinDialDial & operator= (const FXRealSpinDialDial &)
Detailed Description
Definition at line 111 of file FXRealSpinDial.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_AUTOSPIN
ID_LAST
Definition at line 127 of file FXRealSpinDial.cpp.
Constructor & Destructor Documentation
FXRealSpinDialDial() [1/3]
FX::FXRealSpinDialDial::FXRealSpinDialDial () inline protected
Definition at line 114 of file FXRealSpinDial.cpp.
References onAuto(), onButtonPress(), onButtonRelease(), onKey(), onMotion(), onRightButtonPress(), onRightButtonRelease(), and operator=().
FXRealSpinDialDial() [2/3]
FX::FXRealSpinDialDial::FXRealSpinDialDial (const FXRealSpinDialDial &) private
FXRealSpinDialDial() [3/3]
FX::FXRealSpinDialDial::FXRealSpinDialDial (FXComposite * p, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = DIAL_NORMAL, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD) inline
Construct a dial widget.
Definition at line 134 of file FXRealSpinDial.cpp.
References FX::FXDEFMAP(), ID_AUTOSPIN, onAuto(), onButtonPress(), onButtonRelease(), onKey(), onMotion(), onRightButtonPress(), and onRightButtonRelease().
Member Function Documentation
onAuto()
long FX::FXRealSpinDialDial::onAuto (FXObject * , FXSelector , void *)
Definition at line 203 of file FXRealSpinDial.cpp.
References ID_AUTOSPIN.
Referenced by FXRealSpinDialDial().
onButtonPress()
long FX::FXRealSpinDialDial::onButtonPress (FXObject * o, FXSelector s, void * p)
Definition at line 170 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDialBtn::FXRealSpinDialBtn(), and FXRealSpinDialDial().
onButtonRelease()
long FX::FXRealSpinDialDial::onButtonRelease (FXObject * o, FXSelector s, void * p)
Definition at line 174 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDialBtn::FXRealSpinDialBtn(), and FXRealSpinDialDial().
onKey()
long FX::FXRealSpinDialDial::onKey (FXObject * o, FXSelector s, void * p)
Definition at line 164 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDialBtn::FXRealSpinDialBtn(), and FXRealSpinDialDial().
onMotion()
long FX::FXRealSpinDialDial::onMotion (FXObject * o, FXSelector s, void * p)
Definition at line 213 of file FXRealSpinDial.cpp.
Referenced by FXRealSpinDialDial(), and FX::FXRealSpinDialText::FXRealSpinDialText().
onRightButtonPress()
long FX::FXRealSpinDialDial::onRightButtonPress (FXObject * , FXSelector , void * p)
Definition at line 178 of file FXRealSpinDial.cpp.
References ID_AUTOSPIN.
Referenced by FXRealSpinDialDial().
onRightButtonRelease()
long FX::FXRealSpinDialDial::onRightButtonRelease (FXObject * , FXSelector , void *)
Definition at line 193 of file FXRealSpinDial.cpp.
References ID_AUTOSPIN.
Referenced by FXRealSpinDialDial().
operator=()
FXRealSpinDialDial& FX::FXRealSpinDialDial::operator= (const FXRealSpinDialDial &) private
Referenced by FX::FXRealSpinDialBtn::FXRealSpinDialBtn(), FXRealSpinDialDial(), and FX::FXRealSpinDialText::FXRealSpinDialText().
The documentation for this class was generated from the following file:
FXRealSpinDial.cpp