SUMO - Simulation of Urban MObility: NBRequest Class Reference
NBRequest Class Reference
#include <NBRequest.h>
Public Member Functions
void buildBitfieldLogic ()
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
std::pair< int, int > getSizes () const
returns the number of the junction's lanes and the number of the junction's links in respect.
bool mustBrake (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
bool mustBrake (const NBEdge *const from, const NBEdge *const to, int fromLane, int toLane, bool includePedCrossings) const
Returns the information whether the described flow must let any other flow pass.
NBRequest (const NBEdgeCont &ec, NBNode *junction, const EdgeVector &all, const EdgeVector &incoming, const EdgeVector &outgoing, const NBConnectionProhibits &loadedProhibits)
void writeLogic (std::string key, OutputDevice &into, const bool checkLaneFoes) const
~NBRequest ()
Static Public Member Functions
static bool mergeConflict (const NBEdge *from, const NBEdge::Connection &con, const NBEdge *prohibitorFrom, const NBEdge::Connection &prohibitorCon, bool foes)
whether multple connections from the same edge target the same lane
static bool mustBrakeForCrossing (const NBNode *node, const NBEdge *const from, const NBEdge *const to, const NBNode::Crossing &crossing)
Returns the information whether the described flow must brake for the given crossing.
static void reportWarnings ()
reports warnings if any occured
Private Types
typedef std::vector< LinkInfoCont > CombinationsCont
typedef std::vector< bool > LinkInfoCont
typedef std::map< NBEdge *, LaneVector > OccupiedLanes
Private Member Functions
void computeLeftOutgoingLinkCrossings (NBEdge *from, NBEdge *to)
void computeRightOutgoingLinkCrossings (NBEdge *from, NBEdge *to)
int distanceCounterClockwise (NBEdge *from, NBEdge *to)
std::string getFoesString (NBEdge *from, NBEdge *to, int fromLane, int toLane, const bool checkLaneFoes) const
int getIndex (const NBEdge *const from, const NBEdge *const to) const
Returns the index to the internal combination container for the given edge combination.
std::string getResponseString (int tlIndex, const NBEdge *const from, const NBEdge *const to, int fromLane, int toLane, bool mayDefinitelyPass, const bool checkLaneFoes) const
Writes the response of a certain link.
bool laneConflict (const NBEdge *from, const NBEdge *to, int toLane, const NBEdge *prohibitorFrom, const NBEdge *prohibitorTo, int prohibitorToLane) const
return whether the given laneToLane connections prohibit each other under the assumption that the edge2edge connections are in conflict
int numLinks () const
return to total number of edge-to-edge connections of this request-logic
NBRequest & operator= (const NBRequest &s)
Invalidated assignment operator.
void resetCooperating ()
reset foes it the number of lanes matches (or exceeds) the number of incoming connections for an edge
void resetSignalised ()
void setBlocking (NBEdge *from1, NBEdge *to1, NBEdge *from2, NBEdge *to2)
int writeCrossingResponse (OutputDevice &od, const NBNode::Crossing &crossing, int pos) const
writes the response of a certain crossing Returns the next link index within the junction
int writeLaneResponse (OutputDevice &od, NBEdge *from, int lane, int pos, const bool checkLaneFoes) const
writes the response of a certain lane Returns the next link index within the junction
Private Attributes
const EdgeVector & myAll
std::vector< NBNode::Crossing * > myCrossings
CombinationsCont myDone
CombinationsCont myForbids
const EdgeVector & myIncoming
NBNode * myJunction
the node the request is assigned to
const EdgeVector & myOutgoing
Static Private Attributes
static int myGoodBuilds = 0
static int myNotBuild = 0
Friends
std::ostream & operator<< (std::ostream &os, const NBRequest &r)
prints the request
Detailed Description
Given a special node, this class builds the logic of this (junction) regarding the relationships between the incoming and outgoing edges and their priorities. The junction's logic is saved when it does not yet exist.
Definition at line 65 of file NBRequest.h.
Member Typedef Documentation
CombinationsCont
typedef std::vector<LinkInfoCont> NBRequest::CombinationsCont private
definition of a container for link(edge->edge) X link(edge->edge) combinations (size = |myIncoming|*|myOutgoing|)
Definition at line 259 of file NBRequest.h.
LinkInfoCont
typedef std::vector<bool> NBRequest::LinkInfoCont private
definition of a container to store boolean informations about a link into
Definition at line 255 of file NBRequest.h.
OccupiedLanes
typedef std::map<NBEdge*, LaneVector> NBRequest::OccupiedLanes private
a container for approached lanes of a certain edge
Definition at line 262 of file NBRequest.h.
Constructor & Destructor Documentation
NBRequest()
NBRequest::NBRequest (const NBEdgeCont & ec, NBNode * junction, const EdgeVector & all, const EdgeVector & incoming, const EdgeVector & outgoing, const NBConnectionProhibits & loadedProhibits)
constructor The parameter are the logic's lists of edges (all, incoming only and outgoing only edges). By now no further informations are needed to describe the junctions. These parameter must not be changed during the logic's building
Definition at line 61 of file NBRequest.cpp.
References NBConnection::check(), NBConnection::getFrom(), Named::getID(), getIndex(), NBConnection::getTo(), myDone, myForbids, myGoodBuilds, myIncoming, myNotBuild, myOutgoing, numLinks(), and WRITE_WARNING.
~NBRequest()
NBRequest::~NBRequest ()
destructor
Definition at line 147 of file NBRequest.cpp.
Member Function Documentation
buildBitfieldLogic()
void NBRequest::buildBitfieldLogic ()
builds the bitset-representation of the logic
Definition at line 151 of file NBRequest.cpp.
References computeLeftOutgoingLinkCrossings(), computeRightOutgoingLinkCrossings(), myIncoming, myOutgoing, resetCooperating(), and resetSignalised().
Referenced by NBNode::computeLogic().
computeLeftOutgoingLinkCrossings()
void NBRequest::computeLeftOutgoingLinkCrossings (NBEdge * from, NBEdge * to) private
computes the relationships between links outgoing left of the given link
Definition at line 185 of file NBRequest.cpp.
References myAll, myJunction, NBContHelper::nextCW(), and setBlocking().
Referenced by buildBitfieldLogic().
computeRightOutgoingLinkCrossings()
void NBRequest::computeRightOutgoingLinkCrossings (NBEdge * from, NBEdge * to) private
computes the relationships between links outgoing right of the given link
Definition at line 167 of file NBRequest.cpp.
References myAll, myJunction, NBContHelper::nextCCW(), and setBlocking().
Referenced by buildBitfieldLogic().
distanceCounterClockwise()
int NBRequest::distanceCounterClockwise (NBEdge * from, NBEdge * to) private
returns the distance between the incoming (from) and the outgoing (to) edge clockwise in edges
Definition at line 305 of file NBRequest.cpp.
References myAll.
foes()
bool NBRequest::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
Parameters
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns
Whether both stream are foes (cross)
Definition at line 417 of file NBRequest.cpp.
References getIndex(), myForbids, myIncoming, and myOutgoing.
Referenced by NBNode::foes(), getFoesString(), resetSignalised(), writeCrossingResponse(), and writeLaneResponse().
forbids()
bool NBRequest::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the first flow prohibits the second one
Definition at line 436 of file NBRequest.cpp.
References getIndex(), NBEdge::hasSignalisedConnectionTo(), myForbids, myIncoming, and myOutgoing.
Referenced by NBNode::forbids().
getFoesString()
std::string NBRequest::getFoesString (NBEdge * from, NBEdge * to, int fromLane, int toLane, const bool checkLaneFoes) const private
writes which participating links are foes to the given
Definition at line 577 of file NBRequest.cpp.
References foes(), NBEdge::getConnection(), laneConflict(), mergeConflict(), myCrossings, myIncoming, and NBNode::rightTurnConflict().
Referenced by writeLaneResponse().
getIndex()
int NBRequest::getIndex (const NBEdge *const from, const NBEdge *const to) const private
Returns the index to the internal combination container for the given edge combination.
If one of the edges is not known, -1 is returned.
Parameters
[in] from The starting edge (incoming to this logic)
[in] to The destination edge (outgoing from this logic)
Returns
The index within the internal container
Definition at line 657 of file NBRequest.cpp.
References myIncoming, and myOutgoing.
Referenced by foes(), forbids(), getResponseString(), mustBrake(), NBRequest(), resetCooperating(), resetSignalised(), and setBlocking().
getResponseString()
std::string NBRequest::getResponseString (int tlIndex, const NBEdge *const from, const NBEdge *const to, int fromLane, int toLane, bool mayDefinitelyPass, const bool checkLaneFoes) const private
Writes the response of a certain link.
For the link (described by the connected edges and lanes), the response in dependence to all other links of this junction is computed. Herefor, the method goes through all links of this junction and writes a '0' if the link is not blocked by the currently investigated one, or '1' if it is.
In the case "mayDefinitelyPass" is true, the link will not be disturbed by any other (special case for on-ramps).
Parameters
[in] tlIndex The tl index of the connection for which the responses shall be written
[in] from The link's starting edge
[in] to The link's destination edge
[in] fromLane The link's starting lane
[in] toLane The link's destination lane
[in] mayDefinitelyPass Whether this link is definitely not disturbed
Returns
the response string
Exceptions
IOError not yet implemented
Definition at line 526 of file NBRequest.cpp.
References OptionsCont::getBool(), NBEdge::getConnection(), getIndex(), OptionsCont::getOptions(), laneConflict(), mergeConflict(), mustBrakeForCrossing(), myCrossings, myForbids, myIncoming, myJunction, myOutgoing, NBNode::rightOnRedConflict(), and NBNode::rightTurnConflict().
Referenced by writeLaneResponse().
getSizes()
std::pair< int, int > NBRequest::getSizes () const
returns the number of the junction's lanes and the number of the junction's links in respect.
Note
: only connected lanes are counted
Definition at line 398 of file NBRequest.cpp.
References myIncoming.
Referenced by NBNode::numNormalConnections().
laneConflict()
bool NBRequest::laneConflict (const NBEdge * from, const NBEdge * to, int toLane, const NBEdge * prohibitorFrom, const NBEdge * prohibitorTo, int prohibitorToLane) const private
return whether the given laneToLane connections prohibit each other under the assumption that the edge2edge connections are in conflict
Definition at line 635 of file NBRequest.cpp.
References NBEdge::getAngleAtNode(), NBEdge::getFromNode(), NBEdge::getToNode(), NBEdge::isTurningDirectionAt(), and NBHelpers::relAngle().
Referenced by getFoesString(), and getResponseString().
mergeConflict()
bool NBRequest::mergeConflict (const NBEdge * from, const NBEdge::Connection & con, const NBEdge * prohibitorFrom, const NBEdge::Connection & prohibitorCon, bool foes) static
whether multple connections from the same edge target the same lane
Definition at line 619 of file NBRequest.cpp.
References NBEdge::Connection::fromLane, NBEdge::getPermissions(), NBEdge::Connection::mayDefinitelyPass, SVC_BICYCLE, NBEdge::Connection::toEdge, and NBEdge::Connection::toLane.
Referenced by getFoesString(), getResponseString(), and mustBrake().
mustBrake() [1/2]
bool NBRequest::mustBrake (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
Returns
Whether the first flow prohibits the second one
Definition at line 763 of file NBRequest.cpp.
References getIndex(), and myForbids.
Referenced by NBNode::mustBrake().
mustBrake() [2/2]
bool NBRequest::mustBrake (const NBEdge *const from, const NBEdge *const to, int fromLane, int toLane, bool includePedCrossings) const
Returns the information whether the described flow must let any other flow pass.
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
[in] fromLane The connection starting lane
[in] includePedCrossings Whether braking due to a pedestrian crossing counts
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 688 of file NBRequest.cpp.
References NBEdge::getConnection(), NBEdge::getConnections(), NBNode::getDirection(), getIndex(), NBNode::getType(), LINKDIR_PARTRIGHT, LINKDIR_RIGHT, mergeConflict(), mustBrakeForCrossing(), myCrossings, myDone, myForbids, myIncoming, myJunction, myOutgoing, NODETYPE_ZIPPER, numLinks(), and NBNode::rightTurnConflict().
mustBrakeForCrossing()
bool NBRequest::mustBrakeForCrossing (const NBNode * node, const NBEdge *const from, const NBEdge *const to, const NBNode::Crossing & crossing) static
Returns the information whether the described flow must brake for the given crossing.
Parameters
[in] node The parent node of this request
[in] from The connection's start edge
[in] to The connection's end edge
[in] crossing The pedestrian crossing to check
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 747 of file NBRequest.cpp.
References NBNode::Crossing::edges, NBNode::getDirection(), LINKDIR_LEFT, LINKDIR_RIGHT, and NBNode::Crossing::priority.
Referenced by getResponseString(), mustBrake(), NBNode::mustBrakeForCrossing(), and writeCrossingResponse().
numLinks()
int NBRequest::numLinks () const inline private
return to total number of edge-to-edge connections of this request-logic
Definition at line 814 of file NBRequest.cpp.
References myCrossings, myIncoming, and myOutgoing.
Referenced by mustBrake(), NBRequest(), and operator<<().
operator=()
NBRequest& NBRequest::operator= (const NBRequest & s) private
Invalidated assignment operator.
reportWarnings()
void NBRequest::reportWarnings () static
reports warnings if any occured
Definition at line 773 of file NBRequest.cpp.
References myGoodBuilds, myNotBuild, toString(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute().
resetCooperating()
void NBRequest::resetCooperating () private
reset foes it the number of lanes matches (or exceeds) the number of incoming connections for an edge
Definition at line 782 of file NBRequest.cpp.
References getIndex(), myForbids, and myIncoming.
Referenced by buildBitfieldLogic().
resetSignalised()
void NBRequest::resetSignalised () private
Definition at line 338 of file NBRequest.cpp.
References foes(), getIndex(), myForbids, and myIncoming.
Referenced by buildBitfieldLogic().
setBlocking()
void NBRequest::setBlocking (NBEdge * from1, NBEdge * to1, NBEdge * from2, NBEdge * to2) private
sets the information that the edge from1->to1 blocks the edge from2->to2 (is higher priorised than this)
Definition at line 203 of file NBRequest.cpp.
References getIndex(), NBEdge::getJunctionPriority(), NBNode::getType(), NBEdge::isTurningDirectionAt(), myAll, myDone, myForbids, myIncoming, myJunction, myOutgoing, NBContHelper::nextCW(), NODETYPE_ALLWAY_STOP, and NODETYPE_RIGHT_BEFORE_LEFT.
Referenced by computeLeftOutgoingLinkCrossings(), and computeRightOutgoingLinkCrossings().
writeCrossingResponse()
int NBRequest::writeCrossingResponse (OutputDevice & od, const NBNode::Crossing & crossing, int pos) const private
writes the response of a certain crossing Returns the next link index within the junction
Definition at line 490 of file NBRequest.cpp.
References OutputDevice::closeTag(), NBNode::Crossing::edges, foes(), NBEdge::getConnectionsFromLane(), NBEdge::getNumLanes(), mustBrakeForCrossing(), myCrossings, myIncoming, myJunction, OutputDevice::openTag(), SUMO_ATTR_CONT, SUMO_ATTR_FOES, SUMO_ATTR_INDEX, SUMO_ATTR_RESPONSE, SUMO_TAG_REQUEST, and OutputDevice::writeAttr().
Referenced by writeLogic().
writeLaneResponse()
int NBRequest::writeLaneResponse (OutputDevice & od, NBEdge * from, int lane, int pos, const bool checkLaneFoes) const private
writes the response of a certain lane Returns the next link index within the junction
Definition at line 468 of file NBRequest.cpp.
References OutputDevice::closeTag(), foes(), NBEdge::getConnectionsFromLane(), getFoesString(), OptionsCont::getOptions(), getResponseString(), NBNode::getType(), myJunction, NODETYPE_ZIPPER, OutputDevice::openTag(), SUMO_ATTR_CONT, SUMO_ATTR_FOES, SUMO_ATTR_INDEX, SUMO_ATTR_RESPONSE, SUMO_TAG_REQUEST, and OutputDevice::writeAttr().
Referenced by writeLogic().
writeLogic()
void NBRequest::writeLogic (std::string key, OutputDevice & into, const bool checkLaneFoes) const
writes the XML-representation of the logic as a bitset-logic XML representation
Definition at line 320 of file NBRequest.cpp.
References myCrossings, myIncoming, writeCrossingResponse(), and writeLaneResponse().
Referenced by NBNode::writeLogic().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const NBRequest & r) friend
prints the request
Definition at line 669 of file NBRequest.cpp.
Field Documentation
myAll
const EdgeVector& NBRequest::myAll private
all (icoming and outgoing) of the junctions edges
Definition at line 242 of file NBRequest.h.
Referenced by computeLeftOutgoingLinkCrossings(), computeRightOutgoingLinkCrossings(), distanceCounterClockwise(), and setBlocking().
myCrossings
std::vector<NBNode::Crossing*> NBRequest::myCrossings private
edges outgoing from the junction
Definition at line 251 of file NBRequest.h.
Referenced by getFoesString(), getResponseString(), mustBrake(), numLinks(), writeCrossingResponse(), and writeLogic().
myDone
CombinationsCont NBRequest::myDone private
the link X link is done-checks
Definition at line 268 of file NBRequest.h.
Referenced by mustBrake(), NBRequest(), and setBlocking().
myForbids
CombinationsCont NBRequest::myForbids private
the link X link blockings
Definition at line 265 of file NBRequest.h.
Referenced by foes(), forbids(), getResponseString(), mustBrake(), NBRequest(), operator<<(), resetCooperating(), resetSignalised(), and setBlocking().
myGoodBuilds
int NBRequest::myGoodBuilds = 0 static private
Definition at line 271 of file NBRequest.h.
Referenced by NBRequest(), and reportWarnings().
myIncoming
const EdgeVector& NBRequest::myIncoming private
edges incoming to the junction
Definition at line 245 of file NBRequest.h.
Referenced by buildBitfieldLogic(), foes(), forbids(), getFoesString(), getIndex(), getResponseString(), getSizes(), mustBrake(), NBRequest(), numLinks(), resetCooperating(), resetSignalised(), setBlocking(), writeCrossingResponse(), and writeLogic().
myJunction
NBNode* NBRequest::myJunction private
the node the request is assigned to
Definition at line 239 of file NBRequest.h.
Referenced by computeLeftOutgoingLinkCrossings(), computeRightOutgoingLinkCrossings(), getResponseString(), mustBrake(), setBlocking(), writeCrossingResponse(), and writeLaneResponse().
myNotBuild
int NBRequest::myNotBuild = 0 static private
Definition at line 271 of file NBRequest.h.
Referenced by NBRequest(), and reportWarnings().
myOutgoing
const EdgeVector& NBRequest::myOutgoing private
edges outgoing from the junction
Definition at line 248 of file NBRequest.h.
Referenced by buildBitfieldLogic(), foes(), forbids(), getIndex(), getResponseString(), mustBrake(), NBRequest(), numLinks(), and setBlocking().
The documentation for this class was generated from the following files:
NBRequest.h
NBRequest.cpp