SUMO - Simulation of Urban MObility: Command_SaveTLCoupledLaneDet Class Reference
Command_SaveTLCoupledLaneDet Class Reference
Writes e2 state of a link for the time the link has yellow/red.
#include <Command_SaveTLCoupledLaneDet.h>
Public Member Functions
Command_SaveTLCoupledLaneDet (MSTLLogicControl::TLSLogicVariants &tlls, MSDetectorFileOutput *dtf, SUMOTime begin, OutputDevice &device, MSLink *link)
Constructor.
void execute ()
Executes the command.
~Command_SaveTLCoupledLaneDet ()
Destructor.
Protected Attributes
MSDetectorFileOutput * myDetector
The detector to use.
OutputDevice & myDevice
The file to write the output to.
const MSTLLogicControl::TLSLogicVariants & myLogics
The logic to use.
SUMOTime myStartTime
The last time the values were written.
Private Member Functions
Command_SaveTLCoupledLaneDet (const Command_SaveTLCoupledLaneDet &)
Invalidated copy constructor.
Command_SaveTLCoupledLaneDet & operator= (const Command_SaveTLCoupledLaneDet &)
Invalidated assignment operator.
Private Attributes
bool myHadOne
Whether the last link state was already saved.
LinkState myLastState
The state the link had the last time.
MSLink * myLink
The link to observe.
Detailed Description
Writes e2 state of a link for the time the link has yellow/red.
Todo:
Problem: The detector may not save the last state (on simulation end)
Definition at line 47 of file Command_SaveTLCoupledLaneDet.h.
Constructor & Destructor Documentation
Command_SaveTLCoupledLaneDet() [1/2]
Command_SaveTLCoupledLaneDet::Command_SaveTLCoupledLaneDet (MSTLLogicControl::TLSLogicVariants & tlls, MSDetectorFileOutput * dtf, SUMOTime begin, OutputDevice & device, MSLink * link)
Constructor.
Parameters
[in] tlls The logic to observe
[in] dtf The detector used to generate the values
[in] begin The begin simulation time
[in] device The output device to write the detector values into
[in] link The link that shall be observed
Definition at line 46 of file Command_SaveTLCoupledLaneDet.cpp.
References execute().
~Command_SaveTLCoupledLaneDet()
Command_SaveTLCoupledLaneDet::~Command_SaveTLCoupledLaneDet ()
Destructor.
Definition at line 55 of file Command_SaveTLCoupledLaneDet.cpp.
Command_SaveTLCoupledLaneDet() [2/2]
Command_SaveTLCoupledLaneDet::Command_SaveTLCoupledLaneDet (const Command_SaveTLCoupledLaneDet &) private
Invalidated copy constructor.
Member Function Documentation
execute()
void Command_SaveTLCoupledLaneDet::execute () virtual
Executes the command.
Called when an active tls program switches, this method checks whether the tls signal responsible for the link has switched to green. If so, the values collected so far are written using "writeXMLOutput". Otherwise, the values are reset.
See also
MSDetectorFileOutput::writeXMLOutput
MSE2Collector::writeXMLOutput
Reimplemented from Command_SaveTLCoupledDet.
Definition at line 60 of file Command_SaveTLCoupledLaneDet.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSLink::getState(), LINKSTATE_TL_RED, Command_SaveTLCoupledDet::myDetector, Command_SaveTLCoupledDet::myDevice, myHadOne, myLastState, myLink, Command_SaveTLCoupledDet::myStartTime, MSDetectorFileOutput::reset(), and MSDetectorFileOutput::writeXMLOutput().
Referenced by Command_SaveTLCoupledLaneDet().
operator=()
Command_SaveTLCoupledLaneDet& Command_SaveTLCoupledLaneDet::operator= (const Command_SaveTLCoupledLaneDet &) private
Invalidated assignment operator.
Field Documentation
myDetector
MSDetectorFileOutput* Command_SaveTLCoupledDet::myDetector protected inherited
The detector to use.
Definition at line 91 of file Command_SaveTLCoupledDet.h.
Referenced by execute(), and Command_SaveTLCoupledDet::execute().
myDevice
OutputDevice& Command_SaveTLCoupledDet::myDevice protected inherited
The file to write the output to.
Definition at line 85 of file Command_SaveTLCoupledDet.h.
Referenced by execute(), and Command_SaveTLCoupledDet::execute().
myHadOne
bool Command_SaveTLCoupledLaneDet::myHadOne private
Whether the last link state was already saved.
Definition at line 87 of file Command_SaveTLCoupledLaneDet.h.
Referenced by execute().
myLastState
LinkState Command_SaveTLCoupledLaneDet::myLastState private
The state the link had the last time.
Definition at line 84 of file Command_SaveTLCoupledLaneDet.h.
Referenced by execute().
myLink
MSLink* Command_SaveTLCoupledLaneDet::myLink private
The link to observe.
Definition at line 81 of file Command_SaveTLCoupledLaneDet.h.
Referenced by execute().
myLogics
const MSTLLogicControl::TLSLogicVariants& Command_SaveTLCoupledDet::myLogics protected inherited
The logic to use.
Definition at line 88 of file Command_SaveTLCoupledDet.h.
myStartTime
SUMOTime Command_SaveTLCoupledDet::myStartTime protected inherited
The last time the values were written.
Definition at line 94 of file Command_SaveTLCoupledDet.h.
Referenced by execute(), and Command_SaveTLCoupledDet::execute().
The documentation for this class was generated from the following files:
Command_SaveTLCoupledLaneDet.h
Command_SaveTLCoupledLaneDet.cpp