SUMO - Simulation of Urban MObility: MSTLLogicControl::TLSLogicVariants Class Reference
MSTLLogicControl::TLSLogicVariants Class Reference
Storage for all programs of a single tls.
#include <MSTLLogicControl.h>
Public Member Functions
void addLink (MSLink *link, MSLane *lane, int pos)
bool addLogic (const std::string &programID, MSTrafficLightLogic *logic, bool netWasLoaded, bool isNewDefault=true)
Adds a logic (program)
void addSwitchCommand (OnSwitchAction *c)
bool checkOriginalTLS () const
Verifies traffic lights loaded from the network.
void executeOnSwitchActions () const
MSTrafficLightLogic * getActive () const
std::vector< MSTrafficLightLogic * > getAllLogics () const
MSTrafficLightLogic * getLogic (const std::string &programID) const
MSTrafficLightLogic * getLogicInstantiatingOff (MSTLLogicControl &tlc, const std::string &programID)
bool isActive (const MSTrafficLightLogic *tl) const
void saveInitialStates ()
void setStateInstantiatingOnline (MSTLLogicControl &tlc, const std::string &state)
void switchTo (MSTLLogicControl &tlc, const std::string &programID)
TLSLogicVariants ()
Constructor.
~TLSLogicVariants ()
Destructor.
Private Member Functions
TLSLogicVariants & operator= (const TLSLogicVariants &)
Invalidated assignment operator.
TLSLogicVariants (const TLSLogicVariants &)
Invalidated copy constructor.
Private Attributes
MSTrafficLightLogic * myCurrentProgram
The currently used program.
std::map< MSLink *, LinkState > myOriginalLinkStates
Originally loaded link states.
std::vector< OnSwitchAction * > mySwitchActions
The list of actions/commands to execute on switch.
std::map< std::string, MSTrafficLightLogic * > myVariants
A map of subkeys to programs.
Detailed Description
Storage for all programs of a single tls.
This class joins all programs of a single tls.
Definition at line 92 of file MSTLLogicControl.h.
Constructor & Destructor Documentation
TLSLogicVariants() [1/2]
MSTLLogicControl::TLSLogicVariants::TLSLogicVariants ()
Constructor.
Definition at line 55 of file MSTLLogicControl.cpp.
~TLSLogicVariants()
MSTLLogicControl::TLSLogicVariants::~TLSLogicVariants ()
Destructor.
Definition at line 60 of file MSTLLogicControl.cpp.
References mySwitchActions, and myVariants.
TLSLogicVariants() [2/2]
MSTLLogicControl::TLSLogicVariants::TLSLogicVariants (const TLSLogicVariants &) private
Invalidated copy constructor.
Member Function Documentation
addLink()
void MSTLLogicControl::TLSLogicVariants::addLink (MSLink * link, MSLane * lane, int pos)
Definition at line 225 of file MSTLLogicControl.cpp.
References myVariants.
Referenced by NLHandler::addConnection().
addLogic()
bool MSTLLogicControl::TLSLogicVariants::addLogic (const std::string & programID, MSTrafficLightLogic * logic, bool netWasLoaded, bool isNewDefault = true)
Adds a logic (program)
Parameters
[in] programID The sub-id of this program
[in] logic The logic to add
[in] netWasLoaded Whether the network has already been loaded (the links have been assigned)
[in] isNewDefault Whether this logic shall be treated as the currently active logic
Definition at line 99 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::adaptLinkInformationFrom(), executeOnSwitchActions(), Named::getID(), MSNet::getInstance(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getPhase(), MSPhaseDefinition::getState(), myCurrentProgram, myVariants, and MSTrafficLightLogic::setTrafficLightSignals().
Referenced by MSTLLogicControl::add(), getLogicInstantiatingOff(), libsumo::TrafficLight::setCompleteRedYellowGreenDefinition(), and setStateInstantiatingOnline().
addSwitchCommand()
void MSTLLogicControl::TLSLogicVariants::addSwitchCommand (OnSwitchAction * c)
Definition at line 179 of file MSTLLogicControl.cpp.
References mySwitchActions.
Referenced by Command_SaveTLCoupledDet::Command_SaveTLCoupledDet().
checkOriginalTLS()
bool MSTLLogicControl::TLSLogicVariants::checkOriginalTLS () const
Verifies traffic lights loaded from the network.
Compare the phase state sizes of each phase with the according tls' number of controlled links.
Returns
Whether all tls programs are valid
Definition at line 72 of file MSTLLogicControl.cpp.
References myVariants, and WRITE_ERROR.
executeOnSwitchActions()
void MSTLLogicControl::TLSLogicVariants::executeOnSwitchActions () const
Definition at line 217 of file MSTLLogicControl.cpp.
References mySwitchActions.
Referenced by addLogic(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::SwitchCommand::execute(), and switchTo().
getActive()
MSTrafficLightLogic * MSTLLogicControl::TLSLogicVariants::getActive () const
Definition at line 202 of file MSTLLogicControl.cpp.
References myCurrentProgram.
Referenced by NLHandler::addConnection(), NLHandler::addE2Detector(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), libsumo::TrafficLight::getControlledJunctions(), libsumo::TrafficLight::getControlledLanes(), libsumo::TrafficLight::getControlledLinks(), libsumo::TrafficLight::getNextSwitch(), libsumo::TrafficLight::getParameter(), libsumo::TrafficLight::getPhase(), libsumo::TrafficLight::getPhaseDuration(), libsumo::TrafficLight::getProgram(), libsumo::TrafficLight::getRedYellowGreenState(), MSTLLogicControl::initWautSwitch(), TraCIServerAPI_TrafficLight::processGet(), libsumo::TrafficLight::setParameter(), libsumo::TrafficLight::setPhase(), libsumo::TrafficLight::setPhaseDuration(), and MSFullExport::writeTLS().
getAllLogics()
std::vector< MSTrafficLightLogic * > MSTLLogicControl::TLSLogicVariants::getAllLogics () const
Definition at line 185 of file MSTLLogicControl.cpp.
References myVariants.
Referenced by libsumo::TrafficLight::getCompleteRedYellowGreenDefinition(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIViewTraffic::onGamingClick(), and GUITrafficLightLogicWrapper::switchTLSLogic().
getLogic()
MSTrafficLightLogic * MSTLLogicControl::TLSLogicVariants::getLogic (const std::string & programID) const
Definition at line 130 of file MSTLLogicControl.cpp.
References myVariants.
Referenced by getLogicInstantiatingOff(), libsumo::TrafficLight::setCompleteRedYellowGreenDefinition(), and setStateInstantiatingOnline().
getLogicInstantiatingOff()
MSTrafficLightLogic * MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff (MSTLLogicControl & tlc, const std::string & programID)
Definition at line 139 of file MSTLLogicControl.cpp.
References addLogic(), Named::getID(), getLogic(), myCurrentProgram, and myVariants.
Referenced by MSTLLogicControl::initWautSwitch(), and switchTo().
isActive()
bool MSTLLogicControl::TLSLogicVariants::isActive (const MSTrafficLightLogic * tl) const
Definition at line 196 of file MSTLLogicControl.cpp.
References myCurrentProgram.
Referenced by GUITrafficLightLogicWrapper::getPopUpMenu().
operator=()
TLSLogicVariants& MSTLLogicControl::TLSLogicVariants::operator= (const TLSLogicVariants &) private
Invalidated assignment operator.
saveInitialStates()
void MSTLLogicControl::TLSLogicVariants::saveInitialStates ()
Definition at line 93 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::collectLinkStates(), myCurrentProgram, and myOriginalLinkStates.
setStateInstantiatingOnline()
void MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline (MSTLLogicControl & tlc, const std::string & state)
Definition at line 158 of file MSTLLogicControl.cpp.
References addLogic(), DELTA_T, MSNet::getCurrentTimeStep(), Named::getID(), MSNet::getInstance(), getLogic(), myCurrentProgram, and switchTo().
Referenced by libsumo::TrafficLight::setRedYellowGreenState().
switchTo()
void MSTLLogicControl::TLSLogicVariants::switchTo (MSTLLogicControl & tlc, const std::string & programID)
Definition at line 208 of file MSTLLogicControl.cpp.
References executeOnSwitchActions(), MSNet::getInstance(), getLogicInstantiatingOff(), myCurrentProgram, and MSTrafficLightLogic::setTrafficLightSignals().
Referenced by libsumo::TrafficLight::setProgram(), and setStateInstantiatingOnline().
Field Documentation
myCurrentProgram
MSTrafficLightLogic* MSTLLogicControl::TLSLogicVariants::myCurrentProgram private
The currently used program.
Definition at line 148 of file MSTLLogicControl.h.
Referenced by addLogic(), getActive(), getLogicInstantiatingOff(), isActive(), saveInitialStates(), setStateInstantiatingOnline(), and switchTo().
myOriginalLinkStates
std::map<MSLink*, LinkState> MSTLLogicControl::TLSLogicVariants::myOriginalLinkStates private
Originally loaded link states.
Definition at line 154 of file MSTLLogicControl.h.
Referenced by saveInitialStates().
mySwitchActions
std::vector<OnSwitchAction*> MSTLLogicControl::TLSLogicVariants::mySwitchActions private
The list of actions/commands to execute on switch.
Definition at line 157 of file MSTLLogicControl.h.
Referenced by addSwitchCommand(), executeOnSwitchActions(), and ~TLSLogicVariants().
myVariants
std::map<std::string, MSTrafficLightLogic*> MSTLLogicControl::TLSLogicVariants::myVariants private
A map of subkeys to programs.
Definition at line 151 of file MSTLLogicControl.h.
Referenced by addLink(), addLogic(), checkOriginalTLS(), getAllLogics(), getLogic(), getLogicInstantiatingOff(), and ~TLSLogicVariants().
The documentation for this class was generated from the following files:
MSTLLogicControl.h
MSTLLogicControl.cpp