SUMO - Simulation of Urban MObility: HelpersEnergy Class Reference
HelpersEnergy Class Reference
Helper methods for energy-based electricity consumption computation based on the battery device.
#include <HelpersEnergy.h>
Public Member Functions
void addAllClassesInto (std::vector< SUMOEmissionClass > &list) const
Add all known emission classes of this model to the given container.
double compute (const SUMOEmissionClass c, const PollutantsInterface::EmissionType e, const double v, const double a, const double slope, const std::map< int, double > *param) const
Computes the emitted pollutant amount using the given speed and acceleration.
virtual SUMOEmissionClass getClassByName (const std::string &eClass, const SUMOVehicleClass vc)
Returns the emission class associated with the given name, aliases are possible If this method is asked for the "unknown" class it should return the default (possibly depending on the given vehicle class). The class name is case insensitive.
const std::string getClassName (const SUMOEmissionClass c) const
Returns the complete name of the emission class including the model.
double getDefaultParam (int paramKey) const
virtual double getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) const
Returns the adapted acceleration value, useful for comparing with external PHEMlight references. Default implementation returns always the input accel.
const std::string & getName () const
Returns the name of the model.
HelpersEnergy ()
Constructor (initializes myEmissionClassStrings)
virtual bool isSilent (const SUMOEmissionClass c)
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Methods for Amitran interfaces
virtual SUMOEmissionClass getClass (const SUMOEmissionClass base, const std::string &vClass, const std::string &fuel, const std::string &eClass, const double weight) const
Returns the emission class described by the given parameters. The base is used to determine the model to use and as default return values. Default implementation returns always base.
virtual std::string getAmitranVehicleClass (const SUMOEmissionClass c) const
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...) Default implementation returns always "Passenger".
virtual std::string getFuel (const SUMOEmissionClass c) const
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...) Default implementation returns always "Gasoline".
virtual int getEuroClass (const SUMOEmissionClass c) const
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6) Default implementation returns always 0.
virtual double getWeight (const SUMOEmissionClass c) const
Returns a reference weight in kg described by this emission class as described in the Amitran interface It might return -1, if the weight is not important to distinguish different emission classes. Default implementation returns always -1.
Static Public Attributes
static const int ENERGY_BASE = 3 << 16
Protected Attributes
StringBijection< SUMOEmissionClass > myEmissionClassStrings
Mapping between emission class names and integer representations.
const std::string myName
the name of the model
Private Attributes
std::map< int, double > myDefaultParameter
The default parameter.
Detailed Description
Helper methods for energy-based electricity consumption computation based on the battery device.
Definition at line 49 of file HelpersEnergy.h.
Constructor & Destructor Documentation
HelpersEnergy()
HelpersEnergy::HelpersEnergy ()
Constructor (initializes myEmissionClassStrings)
Definition at line 40 of file HelpersEnergy.cpp.
References ENERGY_BASE, StringBijection< T >::insert(), myDefaultParameter, PollutantsInterface::Helper::myEmissionClassStrings, SUMO_ATTR_AIRDRAGCOEFFICIENT, SUMO_ATTR_ANGLE, SUMO_ATTR_CONSTANTPOWERINTAKE, SUMO_ATTR_FRONTSURFACEAREA, SUMO_ATTR_INTERNALMOMENTOFINERTIA, SUMO_ATTR_PROPULSIONEFFICIENCY, SUMO_ATTR_RADIALDRAGCOEFFICIENT, SUMO_ATTR_RECUPERATIONEFFICIENCY, SUMO_ATTR_ROLLDRAGCOEFFICIENT, SUMO_ATTR_VEHICLEMASS, and PollutantsInterface::ZERO_EMISSIONS.
Member Function Documentation
addAllClassesInto()
void PollutantsInterface::Helper::addAllClassesInto (std::vector< SUMOEmissionClass > & list) const inline inherited
Add all known emission classes of this model to the given container.
Parameters
[in] list the vector to add to
Definition at line 253 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getAllClasses().
compute()
double HelpersEnergy::compute (const SUMOEmissionClass c, const PollutantsInterface::EmissionType e, const double v, const double a, const double slope, const std::map< int, double > * param) const virtual
Computes the emitted pollutant amount using the given speed and acceleration.
Returns only valid values for electricity all other types give 0.
Parameters
[in] c emission class for the function parameters to use
[in] e the type of emission (CO, CO2, ...), only electricity gives valid results
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
[in] slope The road's slope at vehicle's position [deg]
Returns
The amount emitted by the given emission class when moving with the given velocity and acceleration [mg/s or ml/s]
Implements PollutantsInterface::Helper.
Definition at line 57 of file HelpersEnergy.cpp.
References ACCEL2SPEED, DEG2RAD, PollutantsInterface::ELEC, myDefaultParameter, SPEED2DIST, SUMO_ATTR_AIRDRAGCOEFFICIENT, SUMO_ATTR_ANGLE, SUMO_ATTR_CONSTANTPOWERINTAKE, SUMO_ATTR_FRONTSURFACEAREA, SUMO_ATTR_INTERNALMOMENTOFINERTIA, SUMO_ATTR_PROPULSIONEFFICIENCY, SUMO_ATTR_RADIALDRAGCOEFFICIENT, SUMO_ATTR_RECUPERATIONEFFICIENCY, SUMO_ATTR_ROLLDRAGCOEFFICIENT, and SUMO_ATTR_VEHICLEMASS.
Referenced by MSDevice_Battery::notifyMove().
getAmitranVehicleClass()
virtual std::string PollutantsInterface::Helper::getAmitranVehicleClass (const SUMOEmissionClass c) const inline virtual inherited
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...) Default implementation returns always "Passenger".
Parameters
[in] c the emission class
Returns
the name of the vehicle class
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 188 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getAmitranVehicleClass().
getClass()
virtual SUMOEmissionClass PollutantsInterface::Helper::getClass (const SUMOEmissionClass base, const std::string & vClass, const std::string & fuel, const std::string & eClass, const double weight) const inline virtual inherited
Returns the emission class described by the given parameters. The base is used to determine the model to use and as default return values. Default implementation returns always base.
Parameters
[in] base the base class giving the model and the default
[in] vClass the vehicle class as described in the Amitran interface (Passenger, ...)
[in] fuel the fuel type as described in the Amitran interface (Gasoline, Diesel, ...)
[in] eClass the emission class as described in the Amitran interface (Euro0, ...)
[in] weight the vehicle weight in kg as described in the Amitran interface
Returns
the class described by the parameters
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 174 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getClass().
getClassByName()
virtual SUMOEmissionClass PollutantsInterface::Helper::getClassByName (const std::string & eClass, const SUMOVehicleClass vc) inline virtual inherited
Returns the emission class associated with the given name, aliases are possible If this method is asked for the "unknown" class it should return the default (possibly depending on the given vehicle class). The class name is case insensitive.
Parameters
[in] eClass the name of the emission class (string after the '/' in the emission class attribute)
[in] vc the vehicle class to use when determining default class
Returns
the name of the model (string before the '/' in the emission class)
Reimplemented in HelpersPHEMlight.
Definition at line 134 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getClassByName().
getClassName()
const std::string PollutantsInterface::Helper::getClassName (const SUMOEmissionClass c) const inline inherited
Returns the complete name of the emission class including the model.
Parameters
[in] c the emission class
Returns
the name of the class (the complete emission class attribute)
Definition at line 148 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getName().
getDefaultParam()
double HelpersEnergy::getDefaultParam (int paramKey) const inline
Definition at line 71 of file HelpersEnergy.h.
References myDefaultParameter.
Referenced by MSDevice_Battery::buildVehicleDevices(), and MSDevice_Battery::checkParam().
getEuroClass()
virtual int PollutantsInterface::Helper::getEuroClass (const SUMOEmissionClass c) const inline virtual inherited
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6) Default implementation returns always 0.
Parameters
[in] c the emission class
Returns
the Euro class
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 208 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getEuroClass().
getFuel()
virtual std::string PollutantsInterface::Helper::getFuel (const SUMOEmissionClass c) const inline virtual inherited
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...) Default implementation returns always "Gasoline".
Parameters
[in] c the emission class
Returns
the fuel type
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 198 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getFuel().
getModifiedAccel()
virtual double PollutantsInterface::Helper::getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) const inline virtual inherited
Returns the adapted acceleration value, useful for comparing with external PHEMlight references. Default implementation returns always the input accel.
Parameters
[in] c the emission class
[in] v the speed value
[in] a the acceleration value
[in] slope The road's slope at vehicle's position [deg]
Returns
the modified acceleration
Reimplemented in HelpersPHEMlight.
Definition at line 243 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getModifiedAccel().
getName()
const std::string& PollutantsInterface::Helper::getName () const inline inherited
Returns the name of the model.
Returns
the name of the model (string before the '/' in the emission class attribute)
Definition at line 121 of file PollutantsInterface.h.
getWeight()
virtual double PollutantsInterface::Helper::getWeight (const SUMOEmissionClass c) const inline virtual inherited
Returns a reference weight in kg described by this emission class as described in the Amitran interface It might return -1, if the weight is not important to distinguish different emission classes. Default implementation returns always -1.
Parameters
[in] c the emission class
Returns
a reference weight
Reimplemented in HelpersPHEMlight.
Definition at line 219 of file PollutantsInterface.h.
References PollutantsInterface::compute(), and UNUSED_PARAMETER.
Referenced by PollutantsInterface::getWeight().
isSilent()
virtual bool PollutantsInterface::Helper::isSilent (const SUMOEmissionClass c) inline virtual inherited
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Parameters
[in] c the emission class
Returns
whether the class denotes a silent vehicle
Definition at line 157 of file PollutantsInterface.h.
References PollutantsInterface::HEAVY_BIT.
Referenced by PollutantsInterface::isSilent().
Field Documentation
ENERGY_BASE
const int HelpersEnergy::ENERGY_BASE = 3 << 16 static
Definition at line 51 of file HelpersEnergy.h.
Referenced by HelpersEnergy().
myDefaultParameter
std::map<int, double> HelpersEnergy::myDefaultParameter private
The default parameter.
Definition at line 78 of file HelpersEnergy.h.
Referenced by compute(), getDefaultParam(), and HelpersEnergy().
myEmissionClassStrings
StringBijection<SUMOEmissionClass> PollutantsInterface::Helper::myEmissionClassStrings protected inherited
Mapping between emission class names and integer representations.
Definition at line 263 of file PollutantsInterface.h.
Referenced by HelpersHBEFA3::getAmitranVehicleClass(), HelpersPHEMlight::getAmitranVehicleClass(), HelpersHBEFA3::getClass(), HelpersPHEMlight::getClass(), HelpersPHEMlight::getClassByName(), HelpersHBEFA3::getEuroClass(), HelpersPHEMlight::getEuroClass(), HelpersHBEFA3::getFuel(), HelpersPHEMlight::getFuel(), HelpersPHEMlight::getWeight(), HelpersEnergy(), HelpersHBEFA::HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), and HelpersPHEMlight::HelpersPHEMlight().
myName
const std::string PollutantsInterface::Helper::myName protected inherited
the name of the model
Definition at line 260 of file PollutantsInterface.h.
The documentation for this class was generated from the following files:
HelpersEnergy.h
HelpersEnergy.cpp