SUMO - Simulation of Urban MObility: GNEAdditionalFrame::AdditionalAttributeSingle Class Reference
GNEAdditionalFrame::AdditionalAttributeSingle Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
AdditionalAttributeSingle (FXComposite *parent)
FOX-declaration.
SumoXMLAttr getAttr () const
return Attr
SumoXMLTag getTag () const
return tag
std::string getValue () const
return value
void hideParameter ()
hide all parameters
const std::string & isAttributeValid () const
returns a empty string if current value is valid, a string with information about invalid value in other case
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, std::string value)
show name and value of attribute of type string
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, int value)
show name and value of parameters of type int
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, double value)
show name and value of parameters of type float/real/time
void showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, bool value)
show name and value of parameters of type bool
~AdditionalAttributeSingle ()
destructor
FOX-callbacks
called when user set the value of an attribute of type int/float/string
long onCmdSetAttribute (FXObject *, FXSelector, void *)
long onCmdSetBooleanAttribute (FXObject *, FXSelector, void *)
called when user change the value of myBoolCheckButton
Protected Member Functions
AdditionalAttributeSingle ()
FOX needs this.
Private Attributes
SumoXMLAttr myAdditionalAttr
current XML attribute
SumoXMLTag myAdditionalTag
current XML attribute
FXCheckButton * myBoolCheckButton
check button to enable/disable the value of boolean parameters
std::string myInvalidValue
string which indicates the reason due current value is invalid
FXLabel * myLabel
lael with the name of the parameter
FXTextField * myTextFieldInt
textField to modify the default value of int/float/string parameters
FXTextField * myTextFieldReal
textField to modify the default value of real/times parameters
FXTextField * myTextFieldStrings
textField to modify the default value of string parameters
Detailed Description
Definition at line 65 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
AdditionalAttributeSingle() [1/2]
GNEAdditionalFrame::AdditionalAttributeSingle::AdditionalAttributeSingle (FXComposite * parent)
FOX-declaration.
constructor
Definition at line 568 of file GNEAdditionalFrame.cpp.
References GUIDesignCheckButtonAttribute, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldInt, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, hideParameter(), MID_GNE_ADDITIONALFRAME_CHANGEPARAMETER_BOOL, MID_GNE_ADDITIONALFRAME_CHANGEPARAMETER_TEXT, myBoolCheckButton, myLabel, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
~AdditionalAttributeSingle()
GNEAdditionalFrame::AdditionalAttributeSingle::~AdditionalAttributeSingle ()
destructor
Definition at line 583 of file GNEAdditionalFrame.cpp.
AdditionalAttributeSingle() [2/2]
GNEAdditionalFrame::AdditionalAttributeSingle::AdditionalAttributeSingle () inline protected
FOX needs this.
Definition at line 114 of file GNEAdditionalFrame.h.
Member Function Documentation
getAttr()
SumoXMLAttr GNEAdditionalFrame::AdditionalAttributeSingle::getAttr () const
return Attr
Definition at line 667 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr.
getTag()
SumoXMLTag GNEAdditionalFrame::AdditionalAttributeSingle::getTag () const
return tag
Definition at line 661 of file GNEAdditionalFrame.cpp.
References myAdditionalTag.
getValue()
std::string GNEAdditionalFrame::AdditionalAttributeSingle::getValue () const
return value
Definition at line 673 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isTime(), myAdditionalAttr, myAdditionalTag, myBoolCheckButton, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
hideParameter()
void GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter ()
hide all parameters
Definition at line 648 of file GNEAdditionalFrame.cpp.
References GNEFrame::hide(), myAdditionalAttr, myAdditionalTag, myBoolCheckButton, myLabel, myTextFieldInt, myTextFieldReal, myTextFieldStrings, SUMO_ATTR_NOTHING, and SUMO_TAG_NOTHING.
Referenced by AdditionalAttributeSingle().
isAttributeValid()
const std::string & GNEAdditionalFrame::AdditionalAttributeSingle::isAttributeValid () const
returns a empty string if current value is valid, a string with information about invalid value in other case
Definition at line 687 of file GNEAdditionalFrame.cpp.
References myInvalidValue.
onCmdSetAttribute()
long GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute (FXObject * , FXSelector , void *)
Definition at line 693 of file GNEAdditionalFrame.cpp.
References canParseVehicleClasses(), GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isProbability(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), GNEAttributeCarrier::isValidID(), GNEAttributeCarrier::isVClass(), myAdditionalAttr, myAdditionalTag, myInvalidValue, myTextFieldInt, myTextFieldReal, myTextFieldStrings, SUMO_ATTR_ROUTEPROBE, and toString().
onCmdSetBooleanAttribute()
long GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetBooleanAttribute (FXObject * , FXSelector , void *)
called when user change the value of myBoolCheckButton
Definition at line 771 of file GNEAdditionalFrame.cpp.
References myBoolCheckButton.
showParameter() [1/4]
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, std::string value)
show name and value of attribute of type string
Definition at line 587 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myInvalidValue, myLabel, myTextFieldStrings, GNEAdditionalFrame::show(), and toString().
showParameter() [2/4]
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, int value)
show name and value of parameters of type int
Definition at line 601 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myInvalidValue, myLabel, myTextFieldInt, GNEAdditionalFrame::show(), and toString().
showParameter() [3/4]
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, double value)
show name and value of parameters of type float/real/time
Definition at line 615 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myInvalidValue, myLabel, myTextFieldReal, GNEAdditionalFrame::show(), and toString().
showParameter() [4/4]
void GNEAdditionalFrame::AdditionalAttributeSingle::showParameter (SumoXMLTag additionalTag, SumoXMLAttr additionalAttr, bool value)
show name and value of parameters of type bool
Definition at line 629 of file GNEAdditionalFrame.cpp.
References myAdditionalAttr, myAdditionalTag, myBoolCheckButton, myInvalidValue, myLabel, GNEAdditionalFrame::show(), and toString().
Field Documentation
myAdditionalAttr
SumoXMLAttr GNEAdditionalFrame::AdditionalAttributeSingle::myAdditionalAttr private
current XML attribute
Definition at line 121 of file GNEAdditionalFrame.h.
Referenced by getAttr(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
myAdditionalTag
SumoXMLTag GNEAdditionalFrame::AdditionalAttributeSingle::myAdditionalTag private
current XML attribute
Definition at line 118 of file GNEAdditionalFrame.h.
Referenced by getTag(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
myBoolCheckButton
FXCheckButton* GNEAdditionalFrame::AdditionalAttributeSingle::myBoolCheckButton private
check button to enable/disable the value of boolean parameters
Definition at line 136 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetBooleanAttribute(), and showParameter().
myInvalidValue
std::string GNEAdditionalFrame::AdditionalAttributeSingle::myInvalidValue private
string which indicates the reason due current value is invalid
Definition at line 139 of file GNEAdditionalFrame.h.
Referenced by isAttributeValid(), onCmdSetAttribute(), and showParameter().
myLabel
FXLabel* GNEAdditionalFrame::AdditionalAttributeSingle::myLabel private
lael with the name of the parameter
Definition at line 124 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), hideParameter(), and showParameter().
myTextFieldInt
FXTextField* GNEAdditionalFrame::AdditionalAttributeSingle::myTextFieldInt private
textField to modify the default value of int/float/string parameters
Definition at line 127 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
myTextFieldReal
FXTextField* GNEAdditionalFrame::AdditionalAttributeSingle::myTextFieldReal private
textField to modify the default value of real/times parameters
Definition at line 130 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
myTextFieldStrings
FXTextField* GNEAdditionalFrame::AdditionalAttributeSingle::myTextFieldStrings private
textField to modify the default value of string parameters
Definition at line 133 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributeSingle(), getValue(), hideParameter(), onCmdSetAttribute(), and showParameter().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp