SUMO - Simulation of Urban MObility: NIVisumTL::SignalGroup Class Reference
NIVisumTL::SignalGroup Class Reference
A signal group can be defined either by a time period or by phases.
#include <NIVisumTL.h>
Public Member Functions
NBConnectionVector & connections ()
Returns the connections vector.
SUMOTime getEndTime ()
Returns the stored end time.
SUMOTime getStartTime ()
Returns the stored start time.
SUMOTime getYellowTime ()
Returns the stored yellow time.
std::map< std::string, Phase * > & phases ()
Returns the phases map.
SignalGroup (const std::string &name, SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
constructor
~SignalGroup ()
destructor
Private Attributes
NBConnectionVector myConnections
Connections.
std::string myName
name
std::map< std::string, Phase * > myPhases
phases
Detailed Description
A signal group can be defined either by a time period or by phases.
Definition at line 108 of file NIVisumTL.h.
Constructor & Destructor Documentation
SignalGroup()
NIVisumTL::SignalGroup::SignalGroup (const std::string & name, SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime) inline
constructor
Definition at line 111 of file NIVisumTL.h.
~SignalGroup()
NIVisumTL::SignalGroup::~SignalGroup () inline
destructor
Definition at line 115 of file NIVisumTL.h.
Member Function Documentation
connections()
NBConnectionVector& NIVisumTL::SignalGroup::connections () inline
Returns the connections vector.
Definition at line 118 of file NIVisumTL.h.
Referenced by NIVisumTL::build(), and NIImporter_VISUM::parse_TurnsToSignalGroups().
getEndTime()
SUMOTime NIVisumTL::TimePeriod::getEndTime () inline inherited
Returns the stored end time.
Definition at line 70 of file NIVisumTL.h.
References NIVisumTL::TimePeriod::myEndTime.
Referenced by NIVisumTL::build().
getStartTime()
SUMOTime NIVisumTL::TimePeriod::getStartTime () inline inherited
Returns the stored start time.
Definition at line 65 of file NIVisumTL.h.
References NIVisumTL::TimePeriod::myStartTime.
Referenced by NIVisumTL::build().
getYellowTime()
SUMOTime NIVisumTL::TimePeriod::getYellowTime () inline inherited
Returns the stored yellow time.
Definition at line 75 of file NIVisumTL.h.
References NIVisumTL::TimePeriod::myYellowTime.
Referenced by NIVisumTL::build().
phases()
std::map<std::string, Phase*>& NIVisumTL::SignalGroup::phases () inline
Returns the phases map.
Definition at line 123 of file NIVisumTL.h.
References NIVisumTL::myPhases.
Referenced by NIVisumTL::build(), and NIImporter_VISUM::parse_SignalGroupsToPhases().
Field Documentation
myConnections
NBConnectionVector NIVisumTL::SignalGroup::myConnections private
Connections.
Definition at line 129 of file NIVisumTL.h.
myName
std::string NIVisumTL::SignalGroup::myName private
name
Definition at line 133 of file NIVisumTL.h.
myPhases
std::map<std::string, Phase*> NIVisumTL::SignalGroup::myPhases private
phases
Definition at line 131 of file NIVisumTL.h.
The documentation for this class was generated from the following file:
NIVisumTL.h