SUMO - Simulation of Urban MObility: NIVissimDisturbance Class Reference
NIVissimDisturbance Class Reference
#include <NIVissimDisturbance.h>
Public Member Functions
bool addToNode (NBNode *node, NBDistrictCont &dc, NBNodeCont &nc, NBEdgeCont &ec)
bool clustered () const
void computeBounding ()
bool crosses (const AbstractPoly &poly, double offset=0) const
const Boundary & getBoundary () const
NBConnection getConnection (NBNode *node, int aedgeid)
int getDisturbanceID () const
int getEdgeID () const
void inCluster (int id)
NIVissimDisturbance (int id, const std::string &name, const NIVissimExtendedEdgePoint &edge, const NIVissimExtendedEdgePoint &by)
virtual ~NIVissimDisturbance ()
Static Public Member Functions
static void clearDict ()
static void closeLoading ()
static void dict_SetDisturbances ()
static bool dictionary (const std::string &name, const NIVissimExtendedEdgePoint &edge, const NIVissimExtendedEdgePoint &by)
static bool dictionary (int id, NIVissimDisturbance *o)
static NIVissimDisturbance * dictionary (int id)
static std::vector< int > getWithin (const AbstractPoly &poly)
static void reportRefused ()
Protected Types
typedef std::set< NIVissimBoundedClusterObject * > ContType
Protected Attributes
Boundary * myBoundary
int myClusterID
Private Types
typedef std::map< int, NIVissimDisturbance * > DictType
Private Attributes
NIVissimExtendedEdgePoint myDisturbance
NIVissimExtendedEdgePoint myEdge
int myID
std::string myName
int myNode
Static Private Attributes
static DictType myDict
static int myRunningID = 100000000
static int refusedProhibits = 0
Detailed Description
Definition at line 49 of file NIVissimDisturbance.h.
Member Typedef Documentation
ContType
typedef std::set<NIVissimBoundedClusterObject*> NIVissimBoundedClusterObject::ContType protected inherited
Definition at line 59 of file NIVissimBoundedClusterObject.h.
DictType
typedef std::map<int, NIVissimDisturbance*> NIVissimDisturbance::DictType private
Definition at line 85 of file NIVissimDisturbance.h.
Constructor & Destructor Documentation
NIVissimDisturbance()
NIVissimDisturbance::NIVissimDisturbance (int id, const std::string & name, const NIVissimExtendedEdgePoint & edge, const NIVissimExtendedEdgePoint & by)
Definition at line 63 of file NIVissimDisturbance.cpp.
Referenced by dictionary().
~NIVissimDisturbance()
NIVissimDisturbance::~NIVissimDisturbance () virtual
Definition at line 70 of file NIVissimDisturbance.cpp.
Member Function Documentation
addToNode()
bool NIVissimDisturbance::addToNode (NBNode * node, NBDistrictCont & dc, NBNodeCont & nc, NBEdgeCont & ec)
Definition at line 137 of file NIVissimDisturbance.cpp.
References NBNode::addSortedLinkFoes(), NBConnection::check(), NIVissimAbstractEdge::crossesEdgeAtPoint(), NIVissimConnection::dictionary(), NIVissimEdge::dictionary(), NBEdge::getConnectedEdges(), getConnection(), NIVissimExtendedEdgePoint::getEdgeID(), NIVissimConnection::getFromEdgeID(), NBEdge::getFromNode(), NIVissimAbstractEdge::getID(), Named::getID(), NIVissimExtendedEdgePoint::getPosition(), NIVissimConnection::getToEdgeID(), NBEdge::getToNode(), myDisturbance, myEdge, myNode, refusedProhibits, NBNodeCont::retrieve(), NBEdgeCont::retrieve(), NBEdgeCont::retrievePossiblySplit(), NBEdgeCont::splitAt(), and WRITE_WARNING.
Referenced by NIVissimNodeCluster::dict_addDisturbances().
clearDict()
void NIVissimDisturbance::clearDict () static
Definition at line 331 of file NIVissimDisturbance.cpp.
References myDict.
Referenced by getDisturbanceID(), and NIImporter_Vissim::~NIImporter_Vissim().
closeLoading()
void NIVissimBoundedClusterObject::closeLoading () static inherited
Definition at line 69 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
clustered()
bool NIVissimBoundedClusterObject::clustered () const inherited
Definition at line 63 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myClusterID.
Referenced by NIVissimConnection::buildNodeClusters().
computeBounding()
void NIVissimDisturbance::computeBounding () virtual
Implements NIVissimBoundedClusterObject.
Definition at line 121 of file NIVissimDisturbance.cpp.
References Boundary::add(), NIVissimAbstractEdge::dictionary(), NIVissimExtendedEdgePoint::getEdgeID(), NIVissimExtendedEdgePoint::getGeomPosition(), NIVissimBoundedClusterObject::myBoundary, myDisturbance, myEdge, Boundary::xmax(), and Boundary::xmin().
crosses()
bool NIVissimBoundedClusterObject::crosses (const AbstractPoly & poly, double offset = 0) const inherited
Definition at line 49 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myBoundary, Boundary::overlapsWith(), Boundary::xmax(), and Boundary::xmin().
dict_SetDisturbances()
void NIVissimDisturbance::dict_SetDisturbances () static
Definition at line 340 of file NIVissimDisturbance.cpp.
References NIVissimAbstractEdge::dictionary(), NIVissimExtendedEdgePoint::getEdgeID(), myDict, myDisturbance, and myEdge.
Referenced by getDisturbanceID(), and NIImporter_Vissim::postLoadBuild().
dictionary() [1/3]
bool NIVissimDisturbance::dictionary (const std::string & name, const NIVissimExtendedEdgePoint & edge, const NIVissimExtendedEdgePoint & by) static
Definition at line 75 of file NIVissimDisturbance.cpp.
References myRunningID, and NIVissimDisturbance().
Referenced by NIVissimNodeCluster::dict_addDisturbances(), getDisturbanceID(), NIVissimConnectionCluster::getDisturbanceParticipators(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), and NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed().
dictionary() [2/3]
bool NIVissimDisturbance::dictionary (int id, NIVissimDisturbance * o) static
Definition at line 89 of file NIVissimDisturbance.cpp.
References myDict.
dictionary() [3/3]
NIVissimDisturbance * NIVissimDisturbance::dictionary (int id) static
Definition at line 100 of file NIVissimDisturbance.cpp.
References myDict.
getBoundary()
const Boundary & NIVissimBoundedClusterObject::getBoundary () const inherited
Definition at line 77 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myBoundary.
Referenced by NIVissimConnectionCluster::liesOnSameEdgesEnd().
getConnection()
NBConnection NIVissimDisturbance::getConnection (NBNode * node, int aedgeid)
Definition at line 311 of file NIVissimDisturbance.cpp.
References NIVissimConnection::dictionary(), NIVissimEdge::dictionary(), NIVissimExtendedEdgePoint::getEdgeID(), NIVissimConnection::getFromEdgeID(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIVissimConnection::getToEdgeID(), NBConnection::InvalidConnection, myEdge, and WRITE_WARNING.
Referenced by addToNode(), and getDisturbanceID().
getDisturbanceID()
int NIVissimDisturbance::getDisturbanceID () const inline
Definition at line 62 of file NIVissimDisturbance.h.
References clearDict(), dict_SetDisturbances(), dictionary(), getConnection(), NIVissimExtendedEdgePoint::getEdgeID(), getWithin(), myDisturbance, and reportRefused().
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
getEdgeID()
int NIVissimDisturbance::getEdgeID () const inline
Definition at line 59 of file NIVissimDisturbance.h.
References NIVissimExtendedEdgePoint::getEdgeID(), and myEdge.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
getWithin()
std::vector< int > NIVissimDisturbance::getWithin (const AbstractPoly & poly) static
Definition at line 109 of file NIVissimDisturbance.cpp.
References myDict.
Referenced by NIVissimConnectionCluster::buildNodeClusters(), and getDisturbanceID().
inCluster()
void NIVissimBoundedClusterObject::inCluster (int id) inherited
Definition at line 57 of file NIVissimBoundedClusterObject.cpp.
References NIVissimBoundedClusterObject::myClusterID.
reportRefused()
void NIVissimDisturbance::reportRefused () static
Definition at line 354 of file NIVissimDisturbance.cpp.
References myDict, refusedProhibits, and WRITE_WARNING.
Referenced by NIVissimNodeCluster::dict_addDisturbances(), and getDisturbanceID().
Field Documentation
myBoundary
Boundary* NIVissimBoundedClusterObject::myBoundary protected inherited
Definition at line 61 of file NIVissimBoundedClusterObject.h.
Referenced by NIVissimConnection::buildNodeClusters(), computeBounding(), NIVissimConnection::computeBounding(), NIVissimBoundedClusterObject::crosses(), NIVissimBoundedClusterObject::getBoundary(), NIVissimConnection::getBoundingBox(), and NIVissimBoundedClusterObject::~NIVissimBoundedClusterObject().
myClusterID
int NIVissimBoundedClusterObject::myClusterID protected inherited
Definition at line 62 of file NIVissimBoundedClusterObject.h.
Referenced by NIVissimBoundedClusterObject::clustered(), and NIVissimBoundedClusterObject::inCluster().
myDict
NIVissimDisturbance::DictType NIVissimDisturbance::myDict static private
Definition at line 86 of file NIVissimDisturbance.h.
Referenced by clearDict(), dict_SetDisturbances(), dictionary(), getWithin(), and reportRefused().
myDisturbance
NIVissimExtendedEdgePoint NIVissimDisturbance::myDisturbance private
Definition at line 83 of file NIVissimDisturbance.h.
Referenced by addToNode(), computeBounding(), dict_SetDisturbances(), and getDisturbanceID().
myEdge
NIVissimExtendedEdgePoint NIVissimDisturbance::myEdge private
Definition at line 82 of file NIVissimDisturbance.h.
Referenced by addToNode(), computeBounding(), dict_SetDisturbances(), getConnection(), and getEdgeID().
myID
int NIVissimDisturbance::myID private
Definition at line 79 of file NIVissimDisturbance.h.
myName
std::string NIVissimDisturbance::myName private
Definition at line 81 of file NIVissimDisturbance.h.
myNode
int NIVissimDisturbance::myNode private
Definition at line 80 of file NIVissimDisturbance.h.
Referenced by addToNode().
myRunningID
int NIVissimDisturbance::myRunningID = 100000000 static private
Definition at line 87 of file NIVissimDisturbance.h.
Referenced by dictionary().
refusedProhibits
int NIVissimDisturbance::refusedProhibits = 0 static private
Definition at line 88 of file NIVissimDisturbance.h.
Referenced by addToNode(), and reportRefused().
The documentation for this class was generated from the following files:
NIVissimDisturbance.h
NIVissimDisturbance.cpp