SUMO - Simulation of Urban MObility: GUIPerson::GUIPersonPopupMenu Class Reference
GUIPerson::GUIPersonPopupMenu Class Reference
#include <GUIPerson.h>
Public Member Functions
GUISUMOAbstractView * getParentView ()
return the real owner of this popup
GUIPersonPopupMenu (GUIMainWindow &app, GUISUMOAbstractView &parent, GUIGlObject &o, std::map< GUISUMOAbstractView *, int > &additionalVisualizations)
Constructor.
void insertMenuPaneChild (FXMenuPane *child)
Insert a sub-menu pane in this GUIGLObjectPopupMenu.
long onCmdHideCurrentRoute (FXObject *, FXSelector, void *)
Called if the current route of the person shall be hidden.
long onCmdHideWalkingareaPath (FXObject *, FXSelector, void *)
Called if the walkingarea path of the person shall be hidden.
long onCmdShowCurrentRoute (FXObject *, FXSelector, void *)
Called if the current route of the person shall be shown.
long onCmdShowWalkingareaPath (FXObject *, FXSelector, void *)
Called if the walkingarea path of the person shall be shown.
long onCmdStartTrack (FXObject *, FXSelector, void *)
Called if the person shall be tracked.
long onCmdStopTrack (FXObject *, FXSelector, void *)
Called if the person shall not be tracked any longer.
~GUIPersonPopupMenu ()
Destructor.
FX Calls
Called if the assigned objects shall be centered
long onCmdCenter (FXObject *, FXSelector, void *)
long onCmdCopyName (FXObject *, FXSelector, void *)
Called if the name shall be copied to clipboard.
long onCmdCopyTypedName (FXObject *, FXSelector, void *)
Called if the typed name shall be copied to clipboard.
long onCmdCopyEdgeName (FXObject *, FXSelector, void *)
Called if the edge name shall be copied to clipboard (for lanes only)
long onCmdCopyCursorPosition (FXObject *, FXSelector, void *)
Called if the cursor position shall be copied to clipboard.
long onCmdCopyCursorGeoPosition (FXObject *, FXSelector, void *)
Called if the cursor geo-position shall be copied to clipboard.
long onCmdShowPars (FXObject *, FXSelector, void *)
Called if the parameter of this object shall be shown.
long onCmdShowTypePars (FXObject *, FXSelector, void *)
Called if the type parameter of this object shall be shown.
long onCmdAddSelected (FXObject *, FXSelector, void *)
Called if the object shall be added to the list of selected objects.
long onCmdRemoveSelected (FXObject *, FXSelector, void *)
Called if the object shall be removed from the list of selected objects.
Protected Member Functions
GUIPersonPopupMenu ()
default constructor needed by FOX
Protected Attributes
std::map< GUISUMOAbstractView *, int > dummy
Needed for parameterless instantiation.
GUIMainWindow * myApplication
The main application.
std::vector< FXMenuPane * > myMenuPanes
vector mit Sub-MenuPanes
Position myNetworkPosition
The position within the network the cursor was above when instanting the popup.
GUIGlObject * myObject
The object that belongs to this popup-menu.
GUISUMOAbstractView * myParent
The parent window.
std::map< GUISUMOAbstractView *, int > & myVehiclesAdditionalVisualizations
Information which additional visualisations are enabled (per view)
Detailed Description
A popup-menu for vehicles. In comparison to the normal popup-menu, this one also allows to trigger further visualisations and to track the vehicle.
Definition at line 159 of file GUIPerson.h.
Constructor & Destructor Documentation
GUIPersonPopupMenu() [1/2]
GUIPerson::GUIPersonPopupMenu::GUIPersonPopupMenu (GUIMainWindow & app, GUISUMOAbstractView & parent, GUIGlObject & o, std::map< GUISUMOAbstractView *, int > & additionalVisualizations)
Constructor.
Parameters
[in] app The main window for instantiation of other windows
[in] parent The parent view for changing it
[in] o The object of interest
[in,out] additionalVisualizations Information which additional visualisations are enabled (per view)
Definition at line 86 of file GUIPerson.cpp.
~GUIPersonPopupMenu()
GUIPerson::GUIPersonPopupMenu::~GUIPersonPopupMenu ()
Destructor.
Definition at line 94 of file GUIPerson.cpp.
GUIPersonPopupMenu() [2/2]
GUIPerson::GUIPersonPopupMenu::GUIPersonPopupMenu () inline protected
default constructor needed by FOX
Definition at line 196 of file GUIPerson.h.
Member Function Documentation
getParentView()
GUISUMOAbstractView* GUIGLObjectPopupMenu::getParentView () inline inherited
return the real owner of this popup
Definition at line 73 of file GUIGLObjectPopupMenu.h.
References GUIGLObjectPopupMenu::myParent, GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIGLObjectPopupMenu::onCmdShowPars(), and GUIGLObjectPopupMenu::onCmdShowTypePars().
Referenced by GNEInternalLane::onDefault().
insertMenuPaneChild()
void GUIGLObjectPopupMenu::insertMenuPaneChild (FXMenuPane * child) inherited
Insert a sub-menu pane in this GUIGLObjectPopupMenu.
Definition at line 86 of file GUIGLObjectPopupMenu.cpp.
References GUIGLObjectPopupMenu::myMenuPanes.
Referenced by GNELane::getPopUpMenu().
onCmdAddSelected()
long GUIGLObjectPopupMenu::onCmdAddSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be added to the list of selected objects.
Definition at line 166 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISelectedStorage::select().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCenter()
long GUIGLObjectPopupMenu::onCmdCenter (FXObject * , FXSelector , void *) inherited
Definition at line 103 of file GUIGLObjectPopupMenu.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyCursorGeoPosition()
long GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor geo-position shall be copied to clipboard.
Definition at line 140 of file GUIGLObjectPopupMenu.cpp.
References GeoConvHelper::cartesian2geo(), GUIUserIO::copyToClipboard(), GeoConvHelper::getFinal(), gPrecisionGeo, GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, toString(), Position::x(), and Position::y().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyCursorPosition()
long GUIGLObjectPopupMenu::onCmdCopyCursorPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor position shall be copied to clipboard.
Definition at line 133 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, and toString().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyEdgeName()
long GUIGLObjectPopupMenu::onCmdCopyEdgeName (FXObject * , FXSelector , void *) inherited
Called if the edge name shall be copied to clipboard (for lanes only)
Definition at line 125 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getParentName(), GUIGlObject::getType(), GLO_LANE, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyName()
long GUIGLObjectPopupMenu::onCmdCopyName (FXObject * , FXSelector , void *) inherited
Called if the name shall be copied to clipboard.
Definition at line 111 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getMicrosimID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyTypedName()
long GUIGLObjectPopupMenu::onCmdCopyTypedName (FXObject * , FXSelector , void *) inherited
Called if the typed name shall be copied to clipboard.
Definition at line 118 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getFullName(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdHideCurrentRoute()
long GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute (FXObject * , FXSelector , void *)
Called if the current route of the person shall be hidden.
Definition at line 106 of file GUIPerson.cpp.
References GUIGlObject::getType(), GLO_PERSON, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIPerson::removeActiveAddVisualisation(), and GUIPerson::VO_SHOW_ROUTE.
onCmdHideWalkingareaPath()
long GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath (FXObject * , FXSelector , void *)
Called if the walkingarea path of the person shall be hidden.
Definition at line 124 of file GUIPerson.cpp.
References GUIGlObject::getType(), GLO_PERSON, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, GUIPerson::removeActiveAddVisualisation(), and GUIPerson::VO_SHOW_WALKINGAREA_PATH.
onCmdRemoveSelected()
long GUIGLObjectPopupMenu::onCmdRemoveSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be removed from the list of selected objects.
Definition at line 174 of file GUIGLObjectPopupMenu.cpp.
References GUISelectedStorage::deselect(), GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowCurrentRoute()
long GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute (FXObject * , FXSelector , void *)
Called if the current route of the person shall be shown.
Definition at line 97 of file GUIPerson.cpp.
References GUIPerson::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_PERSON, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIPerson::VO_SHOW_ROUTE.
onCmdShowPars()
long GUIGLObjectPopupMenu::onCmdShowPars (FXObject * , FXSelector , void *) inherited
Called if the parameter of this object shall be shown.
Definition at line 151 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowTypePars()
long GUIGLObjectPopupMenu::onCmdShowTypePars (FXObject * , FXSelector , void *) inherited
Called if the type parameter of this object shall be shown.
Definition at line 159 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getTypeParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowWalkingareaPath()
long GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath (FXObject * , FXSelector , void *)
Called if the walkingarea path of the person shall be shown.
Definition at line 115 of file GUIPerson.cpp.
References GUIPerson::addActiveAddVisualisation(), GUIGlObject::getType(), GLO_PERSON, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUIPerson::VO_SHOW_WALKINGAREA_PATH.
onCmdStartTrack()
long GUIPerson::GUIPersonPopupMenu::onCmdStartTrack (FXObject * , FXSelector , void *)
Called if the person shall be tracked.
Definition at line 132 of file GUIPerson.cpp.
References GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUIGlObject::getType(), GLO_PERSON, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISUMOAbstractView::startTrack().
onCmdStopTrack()
long GUIPerson::GUIPersonPopupMenu::onCmdStopTrack (FXObject * , FXSelector , void *)
Called if the person shall not be tracked any longer.
Definition at line 141 of file GUIPerson.cpp.
References GUIGlObject::getType(), GLO_PERSON, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISUMOAbstractView::stopTrack().
Field Documentation
dummy
std::map<GUISUMOAbstractView*, int> GUIPerson::GUIPersonPopupMenu::dummy protected
Needed for parameterless instantiation.
Definition at line 192 of file GUIPerson.h.
myApplication
GUIMainWindow* GUIGLObjectPopupMenu::myApplication protected inherited
The main application.
Definition at line 122 of file GUIGLObjectPopupMenu.h.
Referenced by GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdShowPars(), and GUIGLObjectPopupMenu::onCmdShowTypePars().
myMenuPanes
std::vector<FXMenuPane*> GUIGLObjectPopupMenu::myMenuPanes protected inherited
vector mit Sub-MenuPanes
Definition at line 128 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::insertMenuPaneChild(), and GUIGLObjectPopupMenu::~GUIGLObjectPopupMenu().
myNetworkPosition
Position GUIGLObjectPopupMenu::myNetworkPosition protected inherited
The position within the network the cursor was above when instanting the popup.
Definition at line 125 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), and GUIGLObjectPopupMenu::onCmdCopyCursorPosition().
myObject
GUIGlObject* GUIGLObjectPopupMenu::myObject protected inherited
The object that belongs to this popup-menu.
Definition at line 119 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdAddSelected(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), onCmdHideWalkingareaPath(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUIGLObjectPopupMenu::onCmdShowPars(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIGLObjectPopupMenu::onCmdShowTypePars(), onCmdShowWalkingareaPath(), onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), and GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic().
myParent
GUISUMOAbstractView* GUIGLObjectPopupMenu::myParent protected inherited
The parent window.
Definition at line 116 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::getParentView(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), onCmdHideWalkingareaPath(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUIGLObjectPopupMenu::onCmdShowPars(), GUIGLObjectPopupMenu::onCmdShowTypePars(), onCmdShowWalkingareaPath(), onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), onCmdStopTrack(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack().
myVehiclesAdditionalVisualizations
std::map<GUISUMOAbstractView*, int>& GUIPerson::GUIPersonPopupMenu::myVehiclesAdditionalVisualizations protected
Information which additional visualisations are enabled (per view)
Definition at line 190 of file GUIPerson.h.
The documentation for this class was generated from the following files:
GUIPerson.h
GUIPerson.cpp