SUMO - Simulation of Urban MObility: ROPerson Class Reference
ROPerson Class Reference
A person as used by router.
#include <ROPerson.h>
Data Structures
class PersonTrip
A planItem can be a Trip which contains multiple tripItems.
class PlanItem
Every person has a plan comprising of multiple planItems.
class Ride
A ride is part of a trip, e.g., go from here to here by car or bus.
class Stop
A planItem can be a Stop.
class TripItem
A TripItem is part of a trip, e.g., go from here to here by car.
class Walk
A walk is part of a trip, e.g., go from here to here by foot.
Public Member Functions
void addRide (const ROEdge *const from, const ROEdge *const to, const std::string &lines, const std::string &destStop)
void addStop (const SUMOVehicleParameter::Stop &stopPar, const ROEdge *const stopEdge)
void addTrip (const ROEdge *const from, const ROEdge *const to, const SVCPermissions modeSet, const std::string &vTypes, const double departPos, const double arrivalPos, const std::string &busStop, double walkFactor)
void addWalk (const ConstROEdgeVector &edges, const double duration, const double speed, const double departPos, const double arrivalPos, const std::string &busStop)
void computeRoute (const RORouterProvider &provider, const bool removeLoops, MsgHandler *errorHandler)
SUMOTime getDepart () const
Returns the time the vehicle starts at, -1 for triggered vehicles.
const ROEdge * getDepartEdge () const
Returns the first edge the person takes.
const std::string & getID () const
Returns the id of the routable.
double getMaxSpeed () const
Returns the vehicle's maximum speed.
const SUMOVehicleParameter & getParameter () const
Returns the definition of the vehicle / person parameter.
std::vector< PlanItem * > & getPlan ()
bool getRoutingSuccess () const
const SUMOVTypeParameter * getType () const
Returns the type of the routable.
SUMOVehicleClass getVClass () const
bool isPartOfFlow () const
bool isPublicTransport () const
ROPerson (const SUMOVehicleParameter &pars, const SUMOVTypeParameter *type)
Constructor.
void saveAsXML (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const
Saves the complete person description.
void write (OutputDevice &os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont &options) const
Saves the routable including the vehicle type (if it was not saved before).
virtual ~ROPerson ()
Destructor.
Protected Attributes
bool myRoutingSuccess
Whether the last routing was successful.
Private Member Functions
bool computeIntermodal (const RORouterProvider &provider, PersonTrip *const trip, const ROVehicle *const veh, MsgHandler *const errorHandler)
ROPerson & operator= (const ROPerson &src)
Invalidated assignment operator.
ROPerson (const ROPerson &src)
Invalidated copy constructor.
Private Attributes
std::vector< PlanItem * > myPlan
The plan of the person.
Detailed Description
A person as used by router.
Definition at line 57 of file ROPerson.h.
Constructor & Destructor Documentation
ROPerson() [1/2]
ROPerson::ROPerson (const SUMOVehicleParameter & pars, const SUMOVTypeParameter * type)
Constructor.
Parameters
[in] pars Parameter of this person
[in] type The type of the person
Definition at line 53 of file ROPerson.cpp.
~ROPerson()
ROPerson::~ROPerson () virtual
Destructor.
Definition at line 58 of file ROPerson.cpp.
References myPlan.
ROPerson() [2/2]
ROPerson::ROPerson (const ROPerson & src) private
Invalidated copy constructor.
Member Function Documentation
addRide()
void ROPerson::addRide (const ROEdge *const from, const ROEdge *const to, const std::string & lines, const std::string & destStop)
Definition at line 93 of file ROPerson.cpp.
References myPlan.
Referenced by RORouteHandler::myStartElement().
addStop()
void ROPerson::addStop (const SUMOVehicleParameter::Stop & stopPar, const ROEdge *const stopEdge)
Definition at line 111 of file ROPerson.cpp.
References myPlan.
Referenced by RORouteHandler::addStop().
addTrip()
void ROPerson::addTrip (const ROEdge *const from, const ROEdge *const to, const SVCPermissions modeSet, const std::string & vTypes, const double departPos, const double arrivalPos, const std::string & busStop, double walkFactor)
Definition at line 66 of file ROPerson.cpp.
References ROPerson::PersonTrip::addVehicle(), DEFAULT_VTYPE_ID, DEPART_TRIGGERED, SUMOVehicleParameter::departProcedure, RORoutable::getID(), RONet::getInstance(), ROPerson::PersonTrip::getVehicles(), RONet::getVehicleTypeSecure(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, myPlan, SUMOVehicleParameter::parametersSet, SVC_PASSENGER, toString(), VEHPARS_VTYPE_SET, and SUMOVehicleParameter::vtypeid.
Referenced by RORouteHandler::addPersonTrip().
addWalk()
void ROPerson::addWalk (const ConstROEdgeVector & edges, const double duration, const double speed, const double departPos, const double arrivalPos, const std::string & busStop)
Definition at line 102 of file ROPerson.cpp.
References myPlan.
Referenced by RORouteHandler::addWalk().
computeIntermodal()
bool ROPerson::computeIntermodal (const RORouterProvider & provider, PersonTrip *const trip, const ROVehicle *const veh, MsgHandler *const errorHandler) private
Definition at line 171 of file ROPerson.cpp.
References RORouteDef::addLoadedAlternative(), ROPerson::PersonTrip::addTripItem(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::compute(), SUMOVehicleParameter::depart, ROPerson::PersonTrip::getArrivalPos(), ROPerson::PersonTrip::getDepartPos(), ROPerson::PersonTrip::getDestination(), RORoutable::getID(), RouterProvider< E, L, N, V >::getIntermodalRouter(), ROPerson::PersonTrip::getModes(), ROPerson::PersonTrip::getOrigin(), RORoutable::getParameter(), ROVehicle::getRouteDefinition(), RORoutable::getType(), ROPerson::PersonTrip::getWalkFactor(), ROPerson::PersonTrip::hasBusStopDest(), MsgHandler::inform(), SUMOVTypeParameter::maxSpeed, and RORoutable::myRoutingSuccess.
Referenced by computeRoute(), and getPlan().
computeRoute()
void ROPerson::computeRoute (const RORouterProvider & provider, const bool removeLoops, MsgHandler * errorHandler) virtual
Implements RORoutable.
Definition at line 202 of file ROPerson.cpp.
References computeIntermodal(), ROPerson::PersonTrip::getVehicles(), myPlan, and RORoutable::myRoutingSuccess.
Referenced by getDepartEdge().
getDepart()
SUMOTime RORoutable::getDepart () const inline inherited
Returns the time the vehicle starts at, -1 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 109 of file RORoutable.h.
References SUMOVehicleParameter::depart, and RORoutable::myParameter.
Referenced by RONet::addPerson(), RONet::addVehicle(), and ROVehicleByDepartureComperator::operator()().
getDepartEdge()
const ROEdge* ROPerson::getDepartEdge () const inline virtual
Returns the first edge the person takes.
Returns
The person's departure edge
Implements RORoutable.
Definition at line 305 of file ROPerson.h.
References computeRoute(), myPlan, and ROPerson::PlanItem::saveAsXML().
getID()
const std::string& RORoutable::getID () const inline inherited
Returns the id of the routable.
Returns
The id of the routable
Definition at line 100 of file RORoutable.h.
References SUMOVehicleParameter::id, and RORoutable::myParameter.
Referenced by RORouteDef::addAlternative(), RONet::addPerson(), ROVehicle::addStop(), addTrip(), computeIntermodal(), ROVehicle::computeRoute(), RONet::createBulkRouteRequests(), ROVehicleByDepartureComperator::operator()(), RORouteDef::preComputeCurrentRoute(), and RORouteDef::repairCurrentRoute().
getMaxSpeed()
double RORoutable::getMaxSpeed () const inline inherited
Returns the vehicle's maximum speed.
Definition at line 120 of file RORoutable.h.
References RORoutable::getDepartEdge(), SUMOVTypeParameter::maxSpeed, and RORoutable::myType.
Referenced by RONet::createBulkRouteRequests().
getParameter()
const SUMOVehicleParameter& RORoutable::getParameter () const inline inherited
Returns the definition of the vehicle / person parameter.
Returns
The vehicle / person's parameter
Definition at line 80 of file RORoutable.h.
References RORoutable::myParameter.
Referenced by RONet::adaptIntermodalRouter(), ROVehicle::addStop(), computeIntermodal(), ROVehicle::getDepartureTime(), ROVehicle::ROVehicle(), ROVehicle::saveAsXML(), and saveAsXML().
getPlan()
std::vector<PlanItem*>& ROPerson::getPlan () inline
Definition at line 326 of file ROPerson.h.
References computeIntermodal(), and myPlan.
Referenced by RORouteHandler::closePerson(), and RORouteHandler::myStartElement().
getRoutingSuccess()
bool RORoutable::getRoutingSuccess () const inline inherited
Definition at line 160 of file RORoutable.h.
References RORoutable::myRoutingSuccess, and RORoutable::saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
getType()
const SUMOVTypeParameter* RORoutable::getType () const inline inherited
Returns the type of the routable.
Returns
The routable's type
Todo:
Why not return a reference?
Definition at line 91 of file RORoutable.h.
References RORoutable::myType.
Referenced by computeIntermodal(), ROVehicle::getChosenSpeedFactor(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), RORoutable::getVClass(), ROVehicle::saveAsXML(), and saveAsXML().
getVClass()
SUMOVehicleClass RORoutable::getVClass () const inline inherited
Definition at line 114 of file RORoutable.h.
References RORoutable::getType(), SVC_IGNORING, and SUMOVTypeParameter::vehicleClass.
Referenced by RONet::createBulkRouteRequests(), ROEdge::isConnectedTo(), and ROEdge::prohibits().
isPartOfFlow()
bool RORoutable::isPartOfFlow () const inline inherited
Definition at line 132 of file RORoutable.h.
References RORoutable::computeRoute(), RORoutable::myParameter, and SUMOVehicleParameter::repetitionNumber.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
isPublicTransport()
bool RORoutable::isPublicTransport () const inline inherited
Definition at line 128 of file RORoutable.h.
References SUMOVehicleParameter::line, and RORoutable::myParameter.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
operator=()
ROPerson& ROPerson::operator= (const ROPerson & src) private
Invalidated assignment operator.
saveAsXML()
void ROPerson::saveAsXML (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const virtual
Saves the complete person description.
Saves the person itself including the trips and stops.
Parameters
[in] os The routes or alternatives output device to store the routable's description into
[in] typeos The types - output device to store additional types into
[in] asAlternatives Whether the route shall be saved as route alternatives
[in] options to find out about defaults and whether exit times for the edges shall be written
Exceptions
IOError If something fails (not yet implemented)
Implements RORoutable.
Definition at line 226 of file ROPerson.cpp.
References OutputDevice::closeTag(), Parameterised::getMap(), RORoutable::getParameter(), RORoutable::getType(), myPlan, OutputDevice::openTag(), SUMOVTypeParameter::saved, SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, SUMO_TAG_PERSON, SUMOVTypeParameter::write(), SUMOVehicleParameter::write(), and OutputDevice::writeAttr().
write()
void RORoutable::write (OutputDevice & os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont & options) const inline inherited
Saves the routable including the vehicle type (if it was not saved before).
Parameters
[in] os The routes - output device to store the vehicle's description into
[in] altos The route alternatives - output device to store the vehicle's description into
[in] typeos The types - output device to store the vehicle types into
Exceptions
IOError If something fails (not yet implemented)
Definition at line 147 of file RORoutable.h.
References RORoutable::saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
Field Documentation
myPlan
std::vector<PlanItem*> ROPerson::myPlan private
The plan of the person.
Definition at line 337 of file ROPerson.h.
Referenced by addRide(), addStop(), addTrip(), addWalk(), computeRoute(), getDepartEdge(), getPlan(), saveAsXML(), and ~ROPerson().
myRoutingSuccess
bool RORoutable::myRoutingSuccess protected inherited
Whether the last routing was successful.
Definition at line 188 of file RORoutable.h.
Referenced by computeIntermodal(), ROVehicle::computeRoute(), computeRoute(), and RORoutable::getRoutingSuccess().
The documentation for this class was generated from the following files:
ROPerson.h
ROPerson.cpp