SUMO - Simulation of Urban MObility: GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu Class Reference
GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu Class Reference
#include <GUITrafficLightLogicWrapper.h>
Public Member Functions
GUISUMOAbstractView * getParentView ()
return the real owner of this popup
GUITrafficLightLogicWrapperPopupMenu (GUIMainWindow &app, GUISUMOAbstractView &parent, GUIGlObject &o)
Constructor.
void insertMenuPaneChild (FXMenuPane *child)
Insert a sub-menu pane in this GUIGLObjectPopupMenu.
long onCmdBegin2TrackPhases (FXObject *, FXSelector, void *)
Called if the phases shall be begun to track.
long onCmdShowPhases (FXObject *, FXSelector, void *)
Called if the phases shall be shown.
long onCmdSwitchTLS2Off (FXObject *, FXSelector, void *)
long onCmdSwitchTLSLogic (FXObject *, FXSelector, void *)
~GUITrafficLightLogicWrapperPopupMenu ()
Destructor.
FX Calls
Called if the assigned objects shall be centered
long onCmdCenter (FXObject *, FXSelector, void *)
long onCmdCopyName (FXObject *, FXSelector, void *)
Called if the name shall be copied to clipboard.
long onCmdCopyTypedName (FXObject *, FXSelector, void *)
Called if the typed name shall be copied to clipboard.
long onCmdCopyEdgeName (FXObject *, FXSelector, void *)
Called if the edge name shall be copied to clipboard (for lanes only)
long onCmdCopyCursorPosition (FXObject *, FXSelector, void *)
Called if the cursor position shall be copied to clipboard.
long onCmdCopyCursorGeoPosition (FXObject *, FXSelector, void *)
Called if the cursor geo-position shall be copied to clipboard.
long onCmdShowPars (FXObject *, FXSelector, void *)
Called if the parameter of this object shall be shown.
long onCmdShowTypePars (FXObject *, FXSelector, void *)
Called if the type parameter of this object shall be shown.
long onCmdAddSelected (FXObject *, FXSelector, void *)
Called if the object shall be added to the list of selected objects.
long onCmdRemoveSelected (FXObject *, FXSelector, void *)
Called if the object shall be removed from the list of selected objects.
Protected Member Functions
GUITrafficLightLogicWrapperPopupMenu ()
protected constructor for FOX
Protected Attributes
GUIMainWindow * myApplication
The main application.
std::vector< FXMenuPane * > myMenuPanes
vector mit Sub-MenuPanes
Position myNetworkPosition
The position within the network the cursor was above when instanting the popup.
GUIGlObject * myObject
The object that belongs to this popup-menu.
GUISUMOAbstractView * myParent
The parent window.
Detailed Description
The popup-menu for a TLS-logic. Adds the functionality to open a view on the tls-logic and to start tracking of the tls-logic.
Definition at line 124 of file GUITrafficLightLogicWrapper.h.
Constructor & Destructor Documentation
GUITrafficLightLogicWrapperPopupMenu() [1/2]
GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::GUITrafficLightLogicWrapperPopupMenu (GUIMainWindow & app, GUISUMOAbstractView & parent, GUIGlObject & o)
Constructor.
Definition at line 76 of file GUITrafficLightLogicWrapper.cpp.
~GUITrafficLightLogicWrapperPopupMenu()
GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::~GUITrafficLightLogicWrapperPopupMenu ()
Destructor.
Definition at line 82 of file GUITrafficLightLogicWrapper.cpp.
GUITrafficLightLogicWrapperPopupMenu() [2/2]
GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::GUITrafficLightLogicWrapperPopupMenu () inline protected
protected constructor for FOX
Definition at line 145 of file GUITrafficLightLogicWrapper.h.
Member Function Documentation
getParentView()
GUISUMOAbstractView* GUIGLObjectPopupMenu::getParentView () inline inherited
return the real owner of this popup
Definition at line 73 of file GUIGLObjectPopupMenu.h.
References GUIGLObjectPopupMenu::myParent, GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIGLObjectPopupMenu::onCmdShowPars(), and GUIGLObjectPopupMenu::onCmdShowTypePars().
Referenced by GNEInternalLane::onDefault().
insertMenuPaneChild()
void GUIGLObjectPopupMenu::insertMenuPaneChild (FXMenuPane * child) inherited
Insert a sub-menu pane in this GUIGLObjectPopupMenu.
Definition at line 86 of file GUIGLObjectPopupMenu.cpp.
References GUIGLObjectPopupMenu::myMenuPanes.
Referenced by GNELane::getPopUpMenu().
onCmdAddSelected()
long GUIGLObjectPopupMenu::onCmdAddSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be added to the list of selected objects.
Definition at line 166 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, GUIGLObjectPopupMenu::myParent, and GUISelectedStorage::select().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdBegin2TrackPhases()
long GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases (FXObject * , FXSelector , void *)
Called if the phases shall be begun to track.
Definition at line 87 of file GUITrafficLightLogicWrapper.cpp.
References GUITrafficLightLogicWrapper::begin2TrackPhases(), GUIGlObject::getType(), GLO_TLLOGIC, and GUIGLObjectPopupMenu::myObject.
onCmdCenter()
long GUIGLObjectPopupMenu::onCmdCenter (FXObject * , FXSelector , void *) inherited
Definition at line 103 of file GUIGLObjectPopupMenu.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyCursorGeoPosition()
long GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor geo-position shall be copied to clipboard.
Definition at line 140 of file GUIGLObjectPopupMenu.cpp.
References GeoConvHelper::cartesian2geo(), GUIUserIO::copyToClipboard(), GeoConvHelper::getFinal(), gPrecisionGeo, GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, toString(), Position::x(), and Position::y().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyCursorPosition()
long GUIGLObjectPopupMenu::onCmdCopyCursorPosition (FXObject * , FXSelector , void *) inherited
Called if the cursor position shall be copied to clipboard.
Definition at line 133 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGLObjectPopupMenu::myNetworkPosition, GUIGLObjectPopupMenu::myParent, and toString().
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyEdgeName()
long GUIGLObjectPopupMenu::onCmdCopyEdgeName (FXObject * , FXSelector , void *) inherited
Called if the edge name shall be copied to clipboard (for lanes only)
Definition at line 125 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getParentName(), GUIGlObject::getType(), GLO_LANE, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyName()
long GUIGLObjectPopupMenu::onCmdCopyName (FXObject * , FXSelector , void *) inherited
Called if the name shall be copied to clipboard.
Definition at line 111 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getMicrosimID(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdCopyTypedName()
long GUIGLObjectPopupMenu::onCmdCopyTypedName (FXObject * , FXSelector , void *) inherited
Called if the typed name shall be copied to clipboard.
Definition at line 118 of file GUIGLObjectPopupMenu.cpp.
References GUIUserIO::copyToClipboard(), GUIGlObject::getFullName(), GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdRemoveSelected()
long GUIGLObjectPopupMenu::onCmdRemoveSelected (FXObject * , FXSelector , void *) inherited
Called if the object shall be removed from the list of selected objects.
Definition at line 174 of file GUIGLObjectPopupMenu.cpp.
References GUISelectedStorage::deselect(), GUIGlObject::getGlID(), gSelected, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowPars()
long GUIGLObjectPopupMenu::onCmdShowPars (FXObject * , FXSelector , void *) inherited
Called if the parameter of this object shall be shown.
Definition at line 151 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdShowPhases()
long GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases (FXObject * , FXSelector , void *)
Called if the phases shall be shown.
Definition at line 96 of file GUITrafficLightLogicWrapper.cpp.
References GUIGlObject::getType(), GLO_TLLOGIC, GUIGLObjectPopupMenu::myObject, and GUITrafficLightLogicWrapper::showPhases().
onCmdShowTypePars()
long GUIGLObjectPopupMenu::onCmdShowTypePars (FXObject * , FXSelector , void *) inherited
Called if the type parameter of this object shall be shown.
Definition at line 159 of file GUIGLObjectPopupMenu.cpp.
References GUIGlObject::getTypeParameterWindow(), GUIGLObjectPopupMenu::myApplication, GUIGLObjectPopupMenu::myObject, and GUIGLObjectPopupMenu::myParent.
Referenced by GUIGLObjectPopupMenu::getParentView().
onCmdSwitchTLS2Off()
long GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off (FXObject * , FXSelector , void *)
Definition at line 105 of file GUITrafficLightLogicWrapper.cpp.
References GUIGlObject::getType(), GLO_TLLOGIC, GUIGLObjectPopupMenu::myObject, and GUITrafficLightLogicWrapper::switchTLSLogic().
onCmdSwitchTLSLogic()
long GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic (FXObject * , FXSelector sel, void *)
Definition at line 114 of file GUITrafficLightLogicWrapper.cpp.
References GUIGlObject::getType(), GLO_TLLOGIC, MID_SWITCH, GUIGLObjectPopupMenu::myObject, and GUITrafficLightLogicWrapper::switchTLSLogic().
Field Documentation
myApplication
GUIMainWindow* GUIGLObjectPopupMenu::myApplication protected inherited
The main application.
Definition at line 122 of file GUIGLObjectPopupMenu.h.
Referenced by GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdShowPars(), and GUIGLObjectPopupMenu::onCmdShowTypePars().
myMenuPanes
std::vector<FXMenuPane*> GUIGLObjectPopupMenu::myMenuPanes protected inherited
vector mit Sub-MenuPanes
Definition at line 128 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::insertMenuPaneChild(), and GUIGLObjectPopupMenu::~GUIGLObjectPopupMenu().
myNetworkPosition
Position GUIGLObjectPopupMenu::myNetworkPosition protected inherited
The position within the network the cursor was above when instanting the popup.
Definition at line 125 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), and GUIGLObjectPopupMenu::onCmdCopyCursorPosition().
myObject
GUIGlObject* GUIGLObjectPopupMenu::myObject protected inherited
The object that belongs to this popup-menu.
Definition at line 119 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::onCmdAddSelected(), onCmdBegin2TrackPhases(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUIGLObjectPopupMenu::onCmdShowPars(), onCmdShowPhases(), GUIGLObjectPopupMenu::onCmdShowTypePars(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), onCmdSwitchTLS2Off(), and onCmdSwitchTLSLogic().
myParent
GUISUMOAbstractView* GUIGLObjectPopupMenu::myParent protected inherited
The parent window.
Definition at line 116 of file GUIGLObjectPopupMenu.h.
Referenced by GUIGLObjectPopupMenu::getParentView(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GUIGLObjectPopupMenu::onCmdCopyCursorPosition(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIGLObjectPopupMenu::onCmdCopyName(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUILaneSpeedTrigger::GUILaneSpeedTriggerPopupMenu::onCmdOpenManip(), GUICalibrator::GUICalibratorPopupMenu::onCmdOpenManip(), GUITriggeredRerouter::GUITriggeredRerouterPopupMenu::onCmdOpenManip(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUIGLObjectPopupMenu::onCmdShowPars(), GUIGLObjectPopupMenu::onCmdShowTypePars(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack().
The documentation for this class was generated from the following files:
GUITrafficLightLogicWrapper.h
GUITrafficLightLogicWrapper.cpp