SUMO - Simulation of Urban MObility: MSLane::vehicle_natural_position_sorter Class Reference
MSLane::vehicle_natural_position_sorter Class Reference
Public Member Functions
int operator() (MSVehicle *v1, MSVehicle *v2) const
Comparing operator.
vehicle_natural_position_sorter (const MSLane *lane)
Constructor.
Data Fields
const MSLane * myLane
Detailed Description
Definition at line 1309 of file MSLane.h.
Constructor & Destructor Documentation
vehicle_natural_position_sorter()
MSLane::vehicle_natural_position_sorter::vehicle_natural_position_sorter (const MSLane * lane) inline explicit
Constructor.
Definition at line 1312 of file MSLane.h.
References MSLane::VehPosition::operator()().
Member Function Documentation
operator()()
int MSLane::vehicle_natural_position_sorter::operator() (MSVehicle * v1, MSVehicle * v2) const
Comparing operator.
Parameters
[in] v1 First vehicle to compare
[in] v2 Second vehicle to compare
Returns
Whether the first vehicle is further on the lane than the second
Definition at line 2554 of file MSLane.cpp.
References MSVehicle::getBackPositionOnLane(), and MSVehicle::getLateralPositionOnLane().
Field Documentation
myLane
const MSLane* MSLane::vehicle_natural_position_sorter::myLane
Definition at line 1324 of file MSLane.h.
The documentation for this class was generated from the following files:
MSLane.h
MSLane.cpp