SUMO - Simulation of Urban MObility: GNEInspectorFrame Class Reference
GNEInspectorFrame Class Reference
#include <GNEInspectorFrame.h>
Data Structures
class AttributeInput
FOX-declaration.
class NeteditParameters
Public Member Functions
void focusUpperElement ()
focus upper element of frame
const std::vector< GNEAttributeCarrier * > & getACs () const
get current list of ACs
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
GNEEdge * getEdgeTemplate () const
get the template edge (to copy attributes from)
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNEInspectorFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
virtual void hide ()
hide Frame
void inspectChild (GNEAttributeCarrier *AC, GNEAttributeCarrier *previousElement)
inspect child of already inspected element
void inspectElement (GNEAttributeCarrier *AC)
Inspect a single element.
void inspectFromDeleteFrame (GNEAttributeCarrier *AC, GNEAttributeCarrier *previousElement, bool previousElementWasMarked)
inspect called from DeleteFrame
void inspectMultisection (const std::vector< GNEAttributeCarrier *> &ACs)
Inspect the given multi-selection.
void refreshValues ()
Refresh inspected values (used when values can be changed externally by other modul)
void setEdgeTemplate (GNEEdge *tpl)
seh the template edge (we assume shared responsibility via reference counting)
void setFrameWidth (int newWidth)
set width of GNEFrame
void show ()
show inspector frame
~GNEInspectorFrame ()
Destructor.
FOX-callbacks
copy edge attributes from edge template
long onCmdCopyTemplate (FXObject *, FXSelector, void *)
long onCmdSetTemplate (FXObject *, FXSelector, void *)
set current edge as new template
long onUpdCopyTemplate (FXObject *, FXSelector, void *)
update the copy button with the name of the template
long onCmdGoBack (FXObject *, FXSelector, void *)
called when user toogle the go back button
long onCmdShowChildMenu (FXObject *, FXSelector, void *data)
called when user press right click over an item of list of childs
long onCmdCenterItem (FXObject *, FXSelector, void *)
called when user select option "center item" of child Menu
long onCmdInspectItem (FXObject *, FXSelector, void *)
called when user select option "inspect item" of child menu
long onCmdDeleteItem (FXObject *, FXSelector, void *)
called when user select option "delte item" of child menu
Protected Member Functions
void createPopUpMenu (int X, int Y, GNEAttributeCarrier *ac)
const std::vector< GNEAttributeCarrier * > & getInspectedACs () const
get reference to current inspected Attribute carriers
GNEInspectorFrame ()
FOX needs this.
void showAttributeCarrierChilds ()
show child of current attributeCarrier
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Attributes
std::vector< GNEAttributeCarrier * > myACs
the multi-selection currently being inspected
FXButton * myBackButton
back Button
FXButton * myCopyTemplateButton
copy template button
GNEEdge * myEdgeTemplate
the edge template
FXGroupBox * myGroupBoxForAttributes
groupBox for attributes
FXGroupBox * myGroupBoxForTemplates
groupBox for templates
FXGroupBox * myGroupBoxForTreeList
groupBox for AttrConnection
NeteditParameters * myNeteditParameters
Netedit Parameters.
GNEAttributeCarrier * myPreviousElementDelete
pointer to previous element called by Delete Frame
bool myPreviousElementDeleteWasMarked
flag to ckec if myPreviousElementDelete was marked in Delete Frame
GNEAttributeCarrier * myPreviousElementInspect
pointer to previous element called by Inspector Frame
GNEAttributeCarrier * myRightClickedAC
pointer to current right clicked Attribute Carrier
FXButton * mySetTemplateButton
set template button
std::set< FXTreeItem * > myTreeItemsWithoutAC
set used to save tree items without AC assigned (for example, Incoming/Outcoming connections)
std::map< FXTreeItem *, GNEAttributeCarrier * > myTreeItemToACMap
map used to save the Tree items with their AC
FXTreeList * myTreelist
tree list to show the childs of the element to erase
std::vector< GNEInspectorFrame::AttributeInput * > myVectorOfAttributeInputs
list of Attribute inputs
Detailed Description
The Widget for modifying network-element attributes (i.e. lane speed)
Definition at line 48 of file GNEInspectorFrame.h.
Constructor & Destructor Documentation
GNEInspectorFrame() [1/2]
GNEInspectorFrame::GNEInspectorFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 107 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::getHigherNumberOfAttributes(), GUIIconSubSys::getIcon(), GUIDesignButton, GUIDesignButtonIconRectangular, GUIDesignGroupBoxFrame, GUIDesignTreeListFrame, ICON_NETEDITARROW, MID_GNE_DELETEFRAME_CHILDS, MID_GNE_INSPECTORFRAME_COPYTEMPLATE, MID_GNE_INSPECTORFRAME_GOBACK, and MID_GNE_INSPECTORFRAME_SETTEMPLATE.
~GNEInspectorFrame()
GNEInspectorFrame::~GNEInspectorFrame ()
Destructor.
Definition at line 152 of file GNEInspectorFrame.cpp.
References GNEReferenceCounter::decRef(), myEdgeTemplate, and GNEReferenceCounter::unreferenced().
GNEInspectorFrame() [2/2]
GNEInspectorFrame::GNEInspectorFrame () inline protected
FOX needs this.
Definition at line 281 of file GNEInspectorFrame.h.
References createPopUpMenu(), getInspectedACs(), and showAttributeCarrierChilds().
Member Function Documentation
createPopUpMenu()
void GNEInspectorFrame::createPopUpMenu (int X, int Y, GNEAttributeCarrier * ac) protected
Definition at line 456 of file GNEInspectorFrame.cpp.
References GNEViewParent::getApp(), GUIMainWindow::getBoldFont(), GUIIconSubSys::getIcon(), GNEAttributeCarrier::getIcon(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNEViewNet::getViewParent(), ICON_MODEDELETE, ICON_MODEINSPECT, ICON_RECENTERVIEW, MID_GNE_INSPECTORFRAME_CENTER, MID_GNE_INSPECTORFRAME_DELETE, MID_GNE_INSPECTORFRAME_INSPECT, myRightClickedAC, myTreelist, GNEFrame::myViewNet, and toString().
Referenced by GNEInspectorFrame(), and onCmdShowChildMenu().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getACs()
const std::vector< GNEAttributeCarrier * > & GNEInspectorFrame::getACs () const
get current list of ACs
Definition at line 406 of file GNEInspectorFrame.cpp.
References myACs.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEInspectorFrame::AttributeInput::refreshAttribute().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getEdgeTemplate()
GNEEdge * GNEInspectorFrame::getEdgeTemplate () const
get the template edge (to copy attributes from)
Definition at line 330 of file GNEInspectorFrame.cpp.
References myEdgeTemplate.
Referenced by GNEViewNet::onLeftBtnPress().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getInspectedACs()
const std::vector< GNEAttributeCarrier * > & GNEInspectorFrame::getInspectedACs () const protected
get reference to current inspected Attribute carriers
Definition at line 709 of file GNEInspectorFrame.cpp.
References myACs.
Referenced by GNEInspectorFrame(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), and GNEInspectorFrame::NeteditParameters::show().
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
hide()
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), onCmdDeleteItem(), onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), and GNEDeleteFrame::removeAttributeCarrier().
inspectChild()
void GNEInspectorFrame::inspectChild (GNEAttributeCarrier * AC, GNEAttributeCarrier * previousElement)
inspect child of already inspected element
Definition at line 291 of file GNEInspectorFrame.cpp.
References inspectElement(), myBackButton, GNEFrame::myHeaderLeftFrame, myPreviousElementDelete, and myPreviousElementInspect.
Referenced by onCmdInspectItem().
inspectElement()
void GNEInspectorFrame::inspectElement (GNEAttributeCarrier * AC)
Inspect a single element.
Definition at line 170 of file GNEInspectorFrame.cpp.
References inspectMultisection().
Referenced by inspectChild(), inspectFromDeleteFrame(), onCmdGoBack(), GNEViewNet::onLeftBtnPress(), and show().
inspectFromDeleteFrame()
void GNEInspectorFrame::inspectFromDeleteFrame (GNEAttributeCarrier * AC, GNEAttributeCarrier * previousElement, bool previousElementWasMarked)
inspect called from DeleteFrame
Definition at line 305 of file GNEInspectorFrame.cpp.
References inspectElement(), myBackButton, GNEFrame::myHeaderLeftFrame, myPreviousElementDelete, myPreviousElementDeleteWasMarked, and myPreviousElementInspect.
Referenced by GNEDeleteFrame::onCmdInspectChildItem().
inspectMultisection()
void GNEInspectorFrame::inspectMultisection (const std::vector< GNEAttributeCarrier *> & ACs)
Inspect the given multi-selection.
Definition at line 181 of file GNEInspectorFrame.cpp.
References GNEFrame::getFrameHeaderLabel(), GNEInspectorFrame::NeteditParameters::hide(), GNEFrame::GEOAttributes::hideGEOAttributes(), GNEAttributeCarrier::isUnique(), myACs, myBackButton, GNEFrame::myContentFrame, myCopyTemplateButton, GNEFrame::myGEOAttributes, myGroupBoxForAttributes, myGroupBoxForTemplates, myGroupBoxForTreeList, GNEFrame::myHeaderLeftFrame, myNeteditParameters, mySetTemplateButton, myVectorOfAttributeInputs, GNEInspectorFrame::NeteditParameters::show(), showAttributeCarrierChilds(), GNEFrame::GEOAttributes::showGEOAttributes(), SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_TAG_JUNCTION, and toString().
Referenced by inspectElement(), onCmdCopyTemplate(), and GNEViewNet::onLeftBtnPress().
onCmdCenterItem()
long GNEInspectorFrame::onCmdCenterItem (FXObject * , FXSelector , void *)
called when user select option "center item" of child Menu
Definition at line 425 of file GNEInspectorFrame.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GNEAttributeCarrier::getGUIGLObject(), myRightClickedAC, and GNEFrame::myViewNet.
onCmdCopyTemplate()
long GNEInspectorFrame::onCmdCopyTemplate (FXObject * , FXSelector , void *)
Definition at line 349 of file GNEInspectorFrame.cpp.
References GNEEdge::copyTemplate(), GNEViewNet::getUndoList(), inspectMultisection(), myACs, myEdgeTemplate, and GNEFrame::myViewNet.
onCmdDeleteItem()
long GNEInspectorFrame::onCmdDeleteItem (FXObject * , FXSelector , void *)
called when user select option "delte item" of child menu
Definition at line 444 of file GNEInspectorFrame.cpp.
References GNEViewParent::getDeleteFrame(), GNEViewNet::getViewParent(), GNEFrame::hide(), myRightClickedAC, GNEFrame::myViewNet, GNEDeleteFrame::removeAttributeCarrier(), GNEFrame::show(), and showAttributeCarrierChilds().
onCmdGoBack()
long GNEInspectorFrame::onCmdGoBack (FXObject * , FXSelector , void *)
called when user toogle the go back button
Definition at line 386 of file GNEInspectorFrame.cpp.
References GNEViewParent::getDeleteFrame(), GNEViewNet::getViewParent(), GNEFrame::hide(), inspectElement(), GNEDeleteFrame::markAttributeCarrier(), myPreviousElementDelete, myPreviousElementDeleteWasMarked, myPreviousElementInspect, GNEFrame::myViewNet, GNEFrame::show(), and GNEDeleteFrame::showChildsOfMarkedAttributeCarrier().
onCmdInspectItem()
long GNEInspectorFrame::onCmdInspectItem (FXObject * , FXSelector , void *)
called when user select option "inspect item" of child menu
Definition at line 435 of file GNEInspectorFrame.cpp.
References inspectChild(), myACs, and myRightClickedAC.
onCmdSetTemplate()
long GNEInspectorFrame::onCmdSetTemplate (FXObject * , FXSelector , void *)
set current edge as new template
Definition at line 361 of file GNEInspectorFrame.cpp.
References myACs, and setEdgeTemplate().
onCmdShowChildMenu()
long GNEInspectorFrame::onCmdShowChildMenu (FXObject * , FXSelector , void * data)
called when user press right click over an item of list of childs
Definition at line 412 of file GNEInspectorFrame.cpp.
References createPopUpMenu(), myTreeItemsWithoutAC, myTreeItemToACMap, and myTreelist.
onUpdCopyTemplate()
long GNEInspectorFrame::onUpdCopyTemplate (FXObject * sender, FXSelector , void *)
update the copy button with the name of the template
Definition at line 371 of file GNEInspectorFrame.cpp.
References GUIGlObject::getMicrosimID(), and myEdgeTemplate.
refreshValues()
void GNEInspectorFrame::refreshValues ()
Refresh inspected values (used when values can be changed externally by other modul)
Definition at line 320 of file GNEInspectorFrame.cpp.
References myVectorOfAttributeInputs, and SUMO_ATTR_NOTHING.
Referenced by GNEFrame::GEOAttributes::onCmdSetGEOAttribute().
setEdgeTemplate()
void GNEInspectorFrame::setEdgeTemplate (GNEEdge * tpl)
seh the template edge (we assume shared responsibility via reference counting)
Definition at line 336 of file GNEInspectorFrame.cpp.
References GNEReferenceCounter::decRef(), GNEReferenceCounter::incRef(), myEdgeTemplate, and GNEReferenceCounter::unreferenced().
Referenced by onCmdSetTemplate().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
show()
void GNEInspectorFrame::show () virtual
show inspector frame
Reimplemented from GNEFrame.
Definition at line 163 of file GNEInspectorFrame.cpp.
References inspectElement(), and GNEFrame::show().
Referenced by GNEDeleteFrame::onCmdInspectChildItem(), and GNEViewNet::updateModeSpecificControls().
showAttributeCarrierChilds()
void GNEInspectorFrame::showAttributeCarrierChilds () protected
show child of current attributeCarrier
NOTE: This function has to be simplified
Definition at line 477 of file GNEInspectorFrame.cpp.
References GNENetElement::getAdditionalChilds(), GNEJunction::getGNECrossings(), GNEJunction::getGNEEdges(), GNELane::getGNEIncomingConnections(), GNELane::getGNEOutcomingConnections(), GNEAttributeCarrier::getIcon(), GNEEdge::getLanes(), GNEAttributeCarrier::getTag(), GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, myACs, myGroupBoxForTreeList, myTreeItemsWithoutAC, myTreeItemToACMap, myTreelist, SUMO_TAG_POI, and toString().
Referenced by GNEInspectorFrame(), inspectMultisection(), and onCmdDeleteItem().
Field Documentation
myACs
std::vector<GNEAttributeCarrier*> GNEInspectorFrame::myACs private
the multi-selection currently being inspected
Definition at line 327 of file GNEInspectorFrame.h.
Referenced by getACs(), getInspectedACs(), inspectMultisection(), onCmdCopyTemplate(), onCmdInspectItem(), onCmdSetTemplate(), and showAttributeCarrierChilds().
myBackButton
FXButton* GNEInspectorFrame::myBackButton private
back Button
Definition at line 303 of file GNEInspectorFrame.h.
Referenced by inspectChild(), inspectFromDeleteFrame(), and inspectMultisection().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and inspectMultisection().
myCopyTemplateButton
FXButton* GNEInspectorFrame::myCopyTemplateButton private
copy template button
Definition at line 309 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myEdgeTemplate
GNEEdge* GNEInspectorFrame::myEdgeTemplate private
the edge template
Definition at line 315 of file GNEInspectorFrame.h.
Referenced by getEdgeTemplate(), onCmdCopyTemplate(), onUpdCopyTemplate(), setEdgeTemplate(), and ~GNEInspectorFrame().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxForAttributes
FXGroupBox* GNEInspectorFrame::myGroupBoxForAttributes private
groupBox for attributes
Definition at line 294 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
myGroupBoxForTemplates
FXGroupBox* GNEInspectorFrame::myGroupBoxForTemplates private
groupBox for templates
Definition at line 306 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
myGroupBoxForTreeList
FXGroupBox* GNEInspectorFrame::myGroupBoxForTreeList private
groupBox for AttrConnection
Definition at line 330 of file GNEInspectorFrame.h.
Referenced by inspectMultisection(), and showAttributeCarrierChilds().
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), inspectChild(), inspectFromDeleteFrame(), and inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myNeteditParameters
NeteditParameters* GNEInspectorFrame::myNeteditParameters private
Netedit Parameters.
Definition at line 300 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
myPreviousElementDelete
GNEAttributeCarrier* GNEInspectorFrame::myPreviousElementDelete private
pointer to previous element called by Delete Frame
Definition at line 321 of file GNEInspectorFrame.h.
Referenced by inspectChild(), inspectFromDeleteFrame(), and onCmdGoBack().
myPreviousElementDeleteWasMarked
bool GNEInspectorFrame::myPreviousElementDeleteWasMarked private
flag to ckec if myPreviousElementDelete was marked in Delete Frame
Definition at line 324 of file GNEInspectorFrame.h.
Referenced by inspectFromDeleteFrame(), and onCmdGoBack().
myPreviousElementInspect
GNEAttributeCarrier* GNEInspectorFrame::myPreviousElementInspect private
pointer to previous element called by Inspector Frame
Definition at line 318 of file GNEInspectorFrame.h.
Referenced by inspectChild(), inspectFromDeleteFrame(), and onCmdGoBack().
myRightClickedAC
GNEAttributeCarrier* GNEInspectorFrame::myRightClickedAC private
pointer to current right clicked Attribute Carrier
Definition at line 342 of file GNEInspectorFrame.h.
Referenced by createPopUpMenu(), onCmdCenterItem(), onCmdDeleteItem(), and onCmdInspectItem().
mySetTemplateButton
FXButton* GNEInspectorFrame::mySetTemplateButton private
set template button
Definition at line 312 of file GNEInspectorFrame.h.
Referenced by inspectMultisection().
myTreeItemsWithoutAC
std::set<FXTreeItem*> GNEInspectorFrame::myTreeItemsWithoutAC private
set used to save tree items without AC assigned (for example, Incoming/Outcoming connections)
Definition at line 339 of file GNEInspectorFrame.h.
Referenced by onCmdShowChildMenu(), and showAttributeCarrierChilds().
myTreeItemToACMap
std::map<FXTreeItem*, GNEAttributeCarrier*> GNEInspectorFrame::myTreeItemToACMap private
map used to save the Tree items with their AC
Definition at line 336 of file GNEInspectorFrame.h.
Referenced by onCmdShowChildMenu(), and showAttributeCarrierChilds().
myTreelist
FXTreeList* GNEInspectorFrame::myTreelist private
tree list to show the childs of the element to erase
Definition at line 333 of file GNEInspectorFrame.h.
Referenced by createPopUpMenu(), onCmdShowChildMenu(), and showAttributeCarrierChilds().
myVectorOfAttributeInputs
std::vector<GNEInspectorFrame::AttributeInput*> GNEInspectorFrame::myVectorOfAttributeInputs private
list of Attribute inputs
Definition at line 297 of file GNEInspectorFrame.h.
Referenced by inspectMultisection(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and refreshValues().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), onCmdDeleteItem(), onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNEInspectorFrame.h
GNEInspectorFrame.cpp