SUMO - Simulation of Urban MObility: GNEFrame Class Reference
GNEFrame Class Reference
#include <GNEFrame.h>
Data Structures
class DrawingMode
class GEOAttributes
class NeteditAttributes
Public Member Functions
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNEFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet, const std::string &frameLabel)
Constructor.
virtual void hide ()
hide Frame
void setFrameWidth (int newWidth)
set width of GNEFrame
virtual void show ()
show Frame
~GNEFrame ()
destructor
Protected Member Functions
GNEFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Member Functions
GNEFrame (const GNEFrame &)=delete
Invalidated copy constructor.
GNEFrame & operator= (const GNEFrame &)=delete
Invalidated assignment operator.
Private Attributes
FXFont * myFrameHeaderFont
Font for the Header.
FXLabel * myFrameHeaderLabel
the label for the frame's header
FXScrollWindow * myScrollWindowsContents
scroll windows that holds the content frame
Detailed Description
Abstract class for lateral frames in NetEdit
Definition at line 54 of file GNEFrame.h.
Constructor & Destructor Documentation
GNEFrame() [1/3]
GNEFrame::GNEFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet, const std::string & frameLabel)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame frameLabel label of the frame
Definition at line 493 of file GNEFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignContentsFrame, GUIDesignContentsScrollWindow, GUIDesignHorizontalSeparator, GUIDesignLabelFrameInformation, myContentFrame, myFrameHeaderFont, myFrameHeaderLabel, myHeaderFrame, myHeaderLeftFrame, myHeaderRightFrame, and myScrollWindowsContents.
~GNEFrame()
GNEFrame::~GNEFrame ()
destructor
Definition at line 534 of file GNEFrame.cpp.
References myFrameHeaderFont.
GNEFrame() [2/3]
GNEFrame::GNEFrame () inline protected
FOX needs this.
Definition at line 334 of file GNEFrame.h.
GNEFrame() [3/3]
GNEFrame::GNEFrame (const GNEFrame &) private delete
Invalidated copy constructor.
Member Function Documentation
focusUpperElement()
void GNEFrame::focusUpperElement ()
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References myGEOAttributes.
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const
get view net
Definition at line 571 of file GNEFrame.cpp.
References myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
hide()
void GNEFrame::hide () virtual
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), and GNEDeleteFrame::removeAttributeCarrier().
operator=()
GNEFrame& GNEFrame::operator= (const GNEFrame &) private delete
Invalidated assignment operator.
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth)
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References myScrollWindowsContents.
show()
void GNEFrame::show () virtual
show Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNEAdditionalFrame, GNEPolygonFrame, GNEInspectorFrame, and GNESelectorFrame.
Definition at line 546 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), myViewNet, and GNEViewParent::showFramesArea().
Referenced by GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::removeAttributeCarrier(), GNESelectorFrame::show(), GNEInspectorFrame::show(), GNEPolygonFrame::show(), GNEAdditionalFrame::show(), and GNEViewNet::updateModeSpecificControls().
Field Documentation
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myFrameHeaderFont
FXFont* GNEFrame::myFrameHeaderFont private
Font for the Header.
Definition at line 365 of file GNEFrame.h.
Referenced by getFrameHeaderFont(), GNEFrame(), and ~GNEFrame().
myFrameHeaderLabel
FXLabel* GNEFrame::myFrameHeaderLabel private
the label for the frame's header
Definition at line 368 of file GNEFrame.h.
Referenced by focusUpperElement(), getFrameHeaderLabel(), and GNEFrame().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myScrollWindowsContents
FXScrollWindow* GNEFrame::myScrollWindowsContents private
scroll windows that holds the content frame
Definition at line 362 of file GNEFrame.h.
Referenced by GNEFrame(), and setFrameWidth().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and show().
The documentation for this class was generated from the following files:
GNEFrame.h
GNEFrame.cpp