SUMO - Simulation of Urban MObility: PedestrianState Class Reference
PedestrianState Class Reference abstract
abstract base class for managing callbacks to retrieve various state information from the model
#include <MSPModel.h>
Public Member Functions
virtual double getAngle (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the direction in which the person faces in degrees
virtual double getEdgePos (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the offset from the start of the current edge measured in its natural direction
virtual const MSEdge * getNextEdge (const MSPerson::MSPersonStage_Walking &stage) const =0
return the list of internal edges if the pedestrian is on an intersection
virtual Position getPosition (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the network coordinate of the person
virtual double getSpeed (const MSPerson::MSPersonStage_Walking &stage) const =0
return the current speed of the person
virtual SUMOTime getWaitingTime (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the time the person spent standing
virtual void moveToXY (MSPerson *p, Position pos, MSLane *lane, double lanePos, double lanePosLat, double angle, int routeOffset, const ConstMSEdgeVector &edges, SUMOTime t)
try to move person to the given position
virtual ~PedestrianState ()
Detailed Description
abstract base class for managing callbacks to retrieve various state information from the model
Definition at line 131 of file MSPModel.h.
Constructor & Destructor Documentation
~PedestrianState()
virtual PedestrianState::~PedestrianState () inline virtual
Definition at line 133 of file MSPModel.h.
Member Function Documentation
getAngle()
virtual double PedestrianState::getAngle (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the direction in which the person faces in degrees
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getAngle().
getEdgePos()
virtual double PedestrianState::getEdgePos (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the offset from the start of the current edge measured in its natural direction
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getEdgePos().
getNextEdge()
virtual const MSEdge* PedestrianState::getNextEdge (const MSPerson::MSPersonStage_Walking & stage) const pure virtual
return the list of internal edges if the pedestrian is on an intersection
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::getNextEdgePtr().
getPosition()
virtual Position PedestrianState::getPosition (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the network coordinate of the person
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getPosition().
getSpeed()
virtual double PedestrianState::getSpeed (const MSPerson::MSPersonStage_Walking & stage) const pure virtual
return the current speed of the person
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getSpeed().
getWaitingTime()
virtual SUMOTime PedestrianState::getWaitingTime (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the time the person spent standing
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getWaitingTime().
moveToXY()
virtual void PedestrianState::moveToXY (MSPerson * p, Position pos, MSLane * lane, double lanePos, double lanePosLat, double angle, int routeOffset, const ConstMSEdgeVector & edges, SUMOTime t) inline virtual
try to move person to the given position
Reimplemented in MSPModel_Striping::PState.
Definition at line 154 of file MSPModel.h.
References UNUSED_PARAMETER.
Referenced by MSPerson::Influencer::postProcessRemoteControl().
The documentation for this class was generated from the following file:
MSPModel.h