SUMO - Simulation of Urban MObility: AbstractPoly Class Reference
AbstractPoly Class Reference abstract
#include <AbstractPoly.h>
Public Member Functions
AbstractPoly ()
AbstractPoly (const AbstractPoly &)
virtual bool around (const Position &p, double offset=0) const =0
virtual bool crosses (const Position &p1, const Position &p2) const =0
virtual bool overlapsWith (const AbstractPoly &poly, double offset=0) const =0
virtual bool partialWithin (const AbstractPoly &poly, double offset=0) const =0
virtual ~AbstractPoly ()
Detailed Description
Definition at line 42 of file AbstractPoly.h.
Constructor & Destructor Documentation
AbstractPoly() [1/2]
AbstractPoly::AbstractPoly () inline
Definition at line 44 of file AbstractPoly.h.
AbstractPoly() [2/2]
AbstractPoly::AbstractPoly (const AbstractPoly &) inline
Definition at line 45 of file AbstractPoly.h.
~AbstractPoly()
virtual AbstractPoly::~AbstractPoly () inline virtual
Definition at line 46 of file AbstractPoly.h.
References around(), crosses(), overlapsWith(), and partialWithin().
Member Function Documentation
around()
virtual bool AbstractPoly::around (const Position & p, double offset = 0) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by Boundary::partialWithin(), PositionVector::partialWithin(), and ~AbstractPoly().
crosses()
virtual bool AbstractPoly::crosses (const Position & p1, const Position & p2) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by Boundary::overlapsWith(), PositionVector::overlapsWith(), and ~AbstractPoly().
overlapsWith()
virtual bool AbstractPoly::overlapsWith (const AbstractPoly & poly, double offset = 0) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by ~AbstractPoly().
partialWithin()
virtual bool AbstractPoly::partialWithin (const AbstractPoly & poly, double offset = 0) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by Boundary::overlapsWith(), PositionVector::overlapsWith(), and ~AbstractPoly().
The documentation for this class was generated from the following file:
AbstractPoly.h