SUMO - Simulation of Urban MObility: GUIDialog_GLObjChooser Class Reference
GUIDialog_GLObjChooser Class Reference
#include <GUIDialog_GLObjChooser.h>
Public Member Functions
GUIGlObject * getObject () const
Returns the chosen (selected) object.
GUIDialog_GLObjChooser (GUIGlChildWindow *parent, FXIcon *icon, const FXString &title, const std::vector< GUIGlID > &ids, GUIGlObjectStorage &glStorage)
Constructor.
void show ()
sets the focus after the window is created to work-around bug in libfox
~GUIDialog_GLObjChooser ()
Destructor.
FOX-callbacks
long onCmdCenter (FXObject *, FXSelector, void *)
Callback: The selected item shall be centered within the calling view.
long onCmdClose (FXObject *, FXSelector, void *)
Callback: The dialog shall be closed.
long onChgText (FXObject *, FXSelector, void *)
Callback: Something has been typed into the the field.
long onCmdText (FXObject *, FXSelector, void *)
Callback: Selects to current item if enter is pressed.
long onListKeyPress (FXObject *, FXSelector, void *)
Callback: Selects to current item if enter is pressed.
long onCmdFilter (FXObject *, FXSelector, void *)
Callback: Hides unselected items if pressed.
long onCmdToggleSelection (FXObject *, FXSelector, void *)
Callback: Toggle selection status of current object.
Protected Member Functions
GUIDialog_GLObjChooser ()
FOX needs this.
Private Attributes
FXButton * myCenterButton
The button that triggers centering on the select object.
std::set< GUIGlID > myIDs
myList contains (void) pointers to elements of myIDs instead of the more
FXList * myList
The list that holds the ids.
GUIGlChildWindow * myParent
The parent window.
GUIGlObject * mySelected
The chosen id.
FXTextField * myTextEntry
The text field.
Detailed Description
Instances of this class are windows that display the list of instances from a given artifact like vehicles, edges or junctions and allow one of their items
Definition at line 58 of file GUIDialog_GLObjChooser.h.
Constructor & Destructor Documentation
GUIDialog_GLObjChooser() [1/2]
GUIDialog_GLObjChooser::GUIDialog_GLObjChooser (GUIGlChildWindow * parent, FXIcon * icon, const FXString & title, const std::vector< GUIGlID > & ids, GUIGlObjectStorage & glStorage)
Constructor.
Parameters
[in] parent The calling view
[in] icon The icon to use
[in] title The title to use
[in] glStorage The storage to retrieve ids from
Definition at line 66 of file GUIDialog_GLObjChooser.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getMicrosimID(), GUIDesignHorizontalSeparator, ICON_FLAG, ICON_NO, ICON_RECENTERVIEW, MID_CANCEL, MID_CHOOSEN_INVERT, MID_CHOOSER_CENTER, MID_CHOOSER_FILTER, MID_CHOOSER_LIST, and MID_CHOOSER_TEXT.
~GUIDialog_GLObjChooser()
GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser ()
Destructor.
Definition at line 113 of file GUIDialog_GLObjChooser.cpp.
References GUIGlChildWindow::getParent(), myParent, and GUIMainWindow::removeChild().
GUIDialog_GLObjChooser() [2/2]
GUIDialog_GLObjChooser::GUIDialog_GLObjChooser () inline protected
FOX needs this.
Definition at line 138 of file GUIDialog_GLObjChooser.h.
Member Function Documentation
getObject()
GUIGlObject* GUIDialog_GLObjChooser::getObject () const inline
Returns the chosen (selected) object.
Returns
The selected object
Definition at line 81 of file GUIDialog_GLObjChooser.h.
References mySelected, onChgText(), onCmdCenter(), onCmdClose(), onCmdFilter(), onCmdText(), onCmdToggleSelection(), onListKeyPress(), and show().
onChgText()
long GUIDialog_GLObjChooser::onChgText (FXObject * , FXSelector , void *)
Callback: Something has been typed into the the field.
Definition at line 143 of file GUIDialog_GLObjChooser.cpp.
References myCenterButton, myList, and myTextEntry.
Referenced by getObject().
onCmdCenter()
long GUIDialog_GLObjChooser::onCmdCenter (FXObject * , FXSelector , void *)
Callback: The selected item shall be centered within the calling view.
Definition at line 126 of file GUIDialog_GLObjChooser.cpp.
References myList, myParent, and GUIGlChildWindow::setView().
Referenced by getObject().
onCmdClose()
long GUIDialog_GLObjChooser::onCmdClose (FXObject * , FXSelector , void *)
Callback: The dialog shall be closed.
Definition at line 136 of file GUIDialog_GLObjChooser.cpp.
Referenced by getObject().
onCmdFilter()
long GUIDialog_GLObjChooser::onCmdFilter (FXObject * , FXSelector , void *)
Callback: Hides unselected items if pressed.
Definition at line 187 of file GUIDialog_GLObjChooser.cpp.
References flag, GUIIconSubSys::getIcon(), ICON_FLAG, myIDs, and myList.
Referenced by getObject().
onCmdText()
long GUIDialog_GLObjChooser::onCmdText (FXObject * , FXSelector , void *)
Callback: Selects to current item if enter is pressed.
Definition at line 162 of file GUIDialog_GLObjChooser.cpp.
References myList, myParent, and GUIGlChildWindow::setView().
Referenced by getObject(), and onListKeyPress().
onCmdToggleSelection()
long GUIDialog_GLObjChooser::onCmdToggleSelection (FXObject * , FXSelector , void *)
Callback: Toggle selection status of current object.
Definition at line 209 of file GUIDialog_GLObjChooser.cpp.
References flag, GUIIconSubSys::getIcon(), GUIGlChildWindow::getView(), gSelected, ICON_FLAG, myList, myParent, and GUISelectedStorage::toggleSelection().
Referenced by getObject().
onListKeyPress()
long GUIDialog_GLObjChooser::onListKeyPress (FXObject * , FXSelector , void * ptr)
Callback: Selects to current item if enter is pressed.
Definition at line 173 of file GUIDialog_GLObjChooser.cpp.
References onCmdText().
Referenced by getObject().
show()
void GUIDialog_GLObjChooser::show ()
sets the focus after the window is created to work-around bug in libfox
Definition at line 119 of file GUIDialog_GLObjChooser.cpp.
References myTextEntry.
Referenced by getObject(), GUISUMOViewParent::onCmdLocate(), and GNEViewParent::onCmdLocate().
Field Documentation
myCenterButton
FXButton* GUIDialog_GLObjChooser::myCenterButton private
The button that triggers centering on the select object.
Definition at line 120 of file GUIDialog_GLObjChooser.h.
Referenced by onChgText().
myIDs
std::set<GUIGlID> GUIDialog_GLObjChooser::myIDs private
myList contains (void) pointers to elements of myIDs instead of the more
Definition at line 133 of file GUIDialog_GLObjChooser.h.
Referenced by onCmdFilter().
myList
FXList* GUIDialog_GLObjChooser::myList private
The list that holds the ids.
Definition at line 117 of file GUIDialog_GLObjChooser.h.
Referenced by onChgText(), onCmdCenter(), onCmdFilter(), onCmdText(), and onCmdToggleSelection().
myParent
GUIGlChildWindow* GUIDialog_GLObjChooser::myParent private
The parent window.
Definition at line 123 of file GUIDialog_GLObjChooser.h.
Referenced by onCmdCenter(), onCmdText(), onCmdToggleSelection(), and ~GUIDialog_GLObjChooser().
mySelected
GUIGlObject* GUIDialog_GLObjChooser::mySelected private
The chosen id.
Definition at line 126 of file GUIDialog_GLObjChooser.h.
Referenced by getObject().
myTextEntry
FXTextField* GUIDialog_GLObjChooser::myTextEntry private
The text field.
Definition at line 129 of file GUIDialog_GLObjChooser.h.
Referenced by onChgText(), and show().
The documentation for this class was generated from the following files:
GUIDialog_GLObjChooser.h
GUIDialog_GLObjChooser.cpp