SUMO - Simulation of Urban MObility: GNEJunction Class Reference
GNEJunction Class Reference
#include <GNEJunction.h>
Public Member Functions
void addAdditionalChild (GNEAdditional *additional)
add additional child to this edge
void addAdditionalParent (GNEAdditional *additional)
add additional child to this edge
void addIncomingGNEEdge (GNEEdge *edge)
add incoming GNEEdge
void addOutgoingGNEEdge (GNEEdge *edge)
add outgoing GNEEdge
void commitGeometryMoving (const Position &oldPos, GNEUndoList *undoList)
registers completed movement with the undoList
void decRef (const std::string &debugMsg="")
Decrease reference.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
const std::vector< GNEAdditional * > & getAdditionalChilds () const
return vector of additionals that have as Parent this edge (For example, Calibrators)
const std::vector< GNEAdditional * > & getAdditionalParents () const
return vector of additionals that have as Parameter this edge (For example, Rerouters)
virtual std::string getAttributeForSelection (SumoXMLAttr key) const
method for getting the attribute in the context of object selection
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
Boundary getBoundary () const
Returns the boundary of the junction.
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
double getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleClass getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleShape getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
RGBColor getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< double > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
std::vector< GNEConnection * > getGNEConnections () const
Returns all GNEConnections vinculated with this junction.
const std::vector< GNECrossing * > & getGNECrossings () const
Returns GNECrossings.
const std::vector< GNEEdge * > & getGNEEdges () const
Returns all GNEEdges vinculated with this Junction.
const std::vector< GNEEdge * > & getGNEIncomingEdges () const
Returns incoming GNEEdges.
const std::vector< GNEEdge * > & getGNEOutgoingEdges () const
Returns incoming GNEEdges.
const GUIGlObject * getGUIGLObject () const
get const pointer to GUIGlObject vinculated with this Attribute Carrier
GUIGlObject * getGUIGLObject ()
get pointer to GUIGlObject vinculated with this Attribute Carrier
GUIIcon getGUIIcon () const
get GUI icon assigned to this object
FXIcon * getIcon () const
get FXIcon assigned to this object
const std::string getID () const
function to support debugging
std::vector< GNEJunction * > getJunctionNeighbours () const
return GNEJunction neighbours
NBNode * getNBNode () const
Return net build node.
GNENet * getNet () const
get Net in which this element is placed
Position getPositionInView () const
Return current position.
SumoXMLTag getTag () const
get XML Tag assigned to this object
GNEJunction (NBNode &nbn, GNENet *net, bool loaded=false)
Constructor.
void incRef (const std::string &debugMsg="")
Increarse reference.
void invalidateShape ()
void invalidateTLS (GNEUndoList *undoList, const NBConnection &deletedConnection=NBConnection::InvalidConnection)
bool isLogicValid ()
whether this junction has a valid logic
void markAsCreateEdgeSource ()
marks as first junction in createEdge-mode
void markAsModified (GNEUndoList *undoList)
prevent re-guessing connections at this junction
void moveGeometry (const Position &oldPos, const Position &offset)
change the position of the element geometry without saving in undoList
template<>
int parse (const std::string &string)
template<>
double parse (const std::string &string)
template<>
bool parse (const std::string &string)
template<>
std::string parse (const std::string &string)
template<>
SUMOVehicleClass parse (const std::string &string)
template<>
RGBColor parse (const std::string &string)
template<>
SUMOVehicleShape parse (const std::string &string)
template<>
std::vector< std::string > parse (const std::string &string)
template<>
std::vector< int > parse (const std::string &string)
template<>
std::vector< double > parse (const std::string &string)
template<>
std::vector< bool > parse (const std::string &string)
void removeAdditionalChild (GNEAdditional *additional)
remove additional child from this edge
void removeAdditionalParent (GNEAdditional *additional)
remove additional child from this edge
void removeEdgeFromCrossings (GNEEdge *edge, GNEUndoList *undoList)
removes the given edge from all pedestrian crossings
void removeIncomingGNEEdge (GNEEdge *edge)
remove incoming GNEEdge
void removeOutgoingGNEEdge (GNEEdge *edge)
remove outgoing GNEEdge
GNECrossing * retrieveGNECrossing (NBNode::Crossing *crossing, bool createIfNoExist=true)
get GNECrossing if exist, and if not create it if create is enabled
void selectTLS (bool selected)
notify the junction of being selected in tls-mode. (used to control drawing)
void setLogicValid (bool valid, GNEUndoList *undoList, const std::string &status=GUESSED)
void setResponsible (bool newVal)
set responsibility for deleting internal strctures
void unMarkAsCreateEdgeSource ()
removes mark as first junction in createEdge-mode
bool unreferenced ()
check if object ins't referenced
void updateGeometry ()
Update the boundary of the junction.
void updateShapesAndGeometries ()
update shapes of all elements associated to the junction
~GNEJunction ()
Destructor.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GNEAttributeCarrier
std::string getAttribute (SumoXMLAttr key) const
This functions has to be implemented in all GNEAttributeCarriers.
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
bool isValid (SumoXMLAttr key, const std::string &value)
inherited from GUIGlObject
virtual const std::string & getParentName () const
Returns the name of the parent object.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static const std::vector< SumoXMLTag > & allowedAdditionalTags ()
get all editable for tag additional elements
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedNetElementsTags ()
get all editable for tag net elements
static const std::vector< SumoXMLTag > & allowedShapeTags ()
get all editable for tag shape elements
static std::vector< SumoXMLTag > allowedTags ()
get all editable for tag elements of all types
static bool canBlockMovement (SumoXMLTag tag)
return true if element tag can block their movement
static bool canBlockShape (SumoXMLTag tag)
return true if element tag can block their shape
static bool canOpenDialog (SumoXMLTag tag)
return true if element tag can open a values editor
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
static std::string getAttributeType (SumoXMLTag tag, SumoXMLAttr attr)
get type of attribute
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if an element with certain tag has a certain attribute
static bool hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
check if attribute of an element has a default avlue
static bool isBool (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool for a certain tag
static bool isColor (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type color for a certain tag
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFilename (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a filename
static bool isFloat (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNonEditable (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is non editable
static bool isNumerical (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical (int or float)
static bool isPositive (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is only Positive (i.e. cannot take negative values)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isProbability (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is a probability (i.e. oly can values between [0, 1])
static bool isString (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type string
static bool isTime (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is time
static bool isUnique (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
static bool isValidFilename (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
static bool isVClass (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a list of Vehicle Classes
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
template<typename T >
static T parseAttributeFromXML (const SUMOSAXAttributes &attrs, const std::string &objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool &abort, bool report=true)
Parse attribute from XML and show warnings if there are problems parsing it.
function used to parse GNEEdges and GNELanes
static bool checkGNEEdgesValid (GNENet *net, const std::string &value, bool report)
check if a list of edge IDs is valid
static bool checkGNELanesValid (GNENet *net, const std::string &value, bool report)
check if a list of Lane IDs is valid
static std::vector< GNEEdge * > parseGNEEdges (GNENet *net, const std::string &value)
parse string into vector of GNEEdges
static std::string parseGNEEdges (const std::vector< GNEEdge *> &edges)
parse vector of GNEEdges into string
static std::vector< GNELane * > parseGNELanes (GNENet *net, const std::string &value)
parse string into vector of GNELanes
static std::string parseGNELanes (const std::vector< GNELane *> &lanes)
parse vector of GNELanes into string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const double BUBBLE_RADIUS
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const GUIGlID INVALID_ID = 0
static const double INVALID_POSITION = -1000000
default value for invalid positions (used by POIs and Polygons)
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
std::vector< GNEAdditional * > myAdditionalChilds
list of Additional Childs of this NetElement
std::vector< GNEAdditional * > myAdditionalParents
list of Additional parents of this NetElement
GNENet * myNet
the net to inform about updates
Private Member Functions
void addTrafficLight (NBTrafficLightDefinition *tlDef, bool forceInsert)
adds a traffic light
double getColorValue (const GUIVisualizationSettings &s, bool bubble) const
determines color value
GNEJunction (const GNEJunction &)=delete
Invalidated copy constructor.
void moveJunctionGeometry (const Position &pos)
reposition the node at pos and informs the edges
GNEJunction & operator= (const GNEJunction &)=delete
Invalidated assignment operator.
void rebuildGNECrossings (bool rebuildNBNodeCrossings=true)
rebuilds crossing objects for this junction
void removeTrafficLight (NBTrafficLightDefinition *tlDef)
removes a traffic light
void setAttribute (SumoXMLAttr key, const std::string &value)
method for setting the attribute and nothing else (used in GNEChange_Attribute)
void setColor (const GUIVisualizationSettings &s, bool bubble) const
sets junction color depending on circumstances
Private Attributes
bool myAmCreateEdgeSource
whether this junction is the first junction for a newly creatededge
bool myAmResponsible
whether we are responsible for deleting myNBNode
bool myAmTLSSelected
whether this junction is selected in tls-mode
Boundary myBoundary
The represented junction's boundary.
std::vector< GNECrossing * > myGNECrossings
the built crossing objects
std::vector< GNEEdge * > myGNEEdges
vector with the GNEEdges vinculated with this junction
std::vector< GNEEdge * > myGNEIncomingEdges
vector with the incomings GNEEdges vinculated with this junction
std::vector< GNEEdge * > myGNEOutgoingEdges
vector with the outgoings GNEEdges vinculated with this junction
bool myHasValidLogic
whether this junctions logic is valid
std::string myLogicStatus
modification status of the junction logic (all connections across this junction)
double myMaxSize
The maximum size (in either x-, or y-dimension) for determining whether to draw or not.
NBNode & myNBNode
A reference to the represented junction.
Friends
class GNEChange_Crossing
class GNEChange_TLS
Declare friend class.
Detailed Description
In the case the represented junction's shape is empty, the boundary is computed using the junction's position to which an offset of 1m to each side is added.
Definition at line 54 of file GNEJunction.h.
Constructor & Destructor Documentation
GNEJunction() [1/2]
GNEJunction::GNEJunction (NBNode & nbn, GNENet * net, bool loaded = false)
Constructor.
Parameters
[in] nbn The represented node
[in] net The net to inform about gui updates
[in] loaded Whether the junction was loaded from a file
Definition at line 66 of file GNEJunction.cpp.
References updateGeometry().
~GNEJunction()
GNEJunction::~GNEJunction ()
Destructor.
Definition at line 78 of file GNEJunction.cpp.
References OptionsCont::getBool(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), myAmResponsible, myGNECrossings, myNBNode, toString(), and WRITE_WARNING.
GNEJunction() [2/2]
GNEJunction::GNEJunction (const GNEJunction &) private delete
Invalidated copy constructor.
Member Function Documentation
addAdditionalChild()
void GNENetElement::addAdditionalChild (GNEAdditional * additional) inherited
add additional child to this edge
Definition at line 85 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalChilds, toString(), and GNENetElement::updateGeometry().
Referenced by GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNEChange_Additional::redo(), and GNEChange_Additional::undo().
addAdditionalParent()
void GNENetElement::addAdditionalParent (GNEAdditional * additional) inherited
add additional child to this edge
Definition at line 58 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalParents, toString(), and GNENetElement::updateGeometry().
addIncomingGNEEdge()
void GNEJunction::addIncomingGNEEdge (GNEEdge * edge)
add incoming GNEEdge
Definition at line 339 of file GNEJunction.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myGNEEdges, myGNEIncomingEdges, SUMO_TAG_EDGE, and toString().
Referenced by GNENet::registerEdge(), and GNEEdge::setAttribute().
addOutgoingGNEEdge()
void GNEJunction::addOutgoingGNEEdge (GNEEdge * edge)
add outgoing GNEEdge
Definition at line 354 of file GNEJunction.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myGNEEdges, myGNEOutgoingEdges, SUMO_TAG_EDGE, and toString().
Referenced by GNENet::registerEdge(), and GNEEdge::setAttribute().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
addTrafficLight()
void GNEJunction::addTrafficLight (NBTrafficLightDefinition * tlDef, bool forceInsert) private
adds a traffic light
Definition at line 953 of file GNEJunction.cpp.
References NBTrafficLightDefinition::addNode(), GNENet::getTLLogicCont(), NBTrafficLightLogicCont::insert(), myNBNode, and GNENetElement::myNet.
Referenced by GNEChange_TLS::redo(), and GNEChange_TLS::undo().
allowedAdditionalTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedAdditionalTags () static inherited
get all editable for tag additional elements
Definition at line 621 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedAttributes()
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 287 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, OptionsCont::getOptions(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, NODEFAULTVALUE, SUMO_ATTR_ACCEL, SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPE, toString(), NBEdge::UNSPECIFIED_CONTPOS, NBEdge::UNSPECIFIED_SPEED, and NBEdge::UNSPECIFIED_VISIBILITY_DISTANCE.
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getDefaultValue(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNESelectorFrame::onCmdSelMBAttribute(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedNetElementsTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedNetElementsTags () static inherited
get all editable for tag net elements
Definition at line 607 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedShapeTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedShapeTags () static inherited
get all editable for tag shape elements
Definition at line 644 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedShapeTags, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEPolygonFrame::GNEPolygonFrame(), GNEPolygonFrame::onCmdSelectShape(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedTags()
std::vector< SumoXMLTag > GNEAttributeCarrier::allowedTags () static inherited
get all editable for tag elements of all types
Definition at line 596 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedNetElementsTags(), and GNEAttributeCarrier::allowedShapeTags().
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
canBlockMovement()
bool GNEAttributeCarrier::canBlockMovement (SumoXMLTag tag) static inherited
return true if element tag can block their movement
Definition at line 656 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockMovementTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::onCmdSelectAdditional(), GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canBlockShape()
bool GNEAttributeCarrier::canBlockShape (SumoXMLTag tag) static inherited
return true if element tag can block their shape
Definition at line 678 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockShapeTags, and SUMO_TAG_POLY.
Referenced by GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canOpenDialog()
bool GNEAttributeCarrier::canOpenDialog (SumoXMLTag tag) static inherited
return true if element tag can open a values editor
Definition at line 688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myDialogTags, SUMO_TAG_CALIBRATOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditional::getPopUpMenu(), GNEViewNet::onCmdOpenAdditionalDialog(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canParse()
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 230 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
checkGNEEdgesValid()
bool GNEAttributeCarrier::checkGNEEdgesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of edge IDs is valid
value string with a list of edges report enable or disable show warning if edges aren't valid
Definition at line 1712 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge(), SUMO_ATTR_EDGES, SUMO_TAG_EDGE, toString(), and WRITE_WARNING.
Referenced by GNECalibratorRoute::isValid(), GNECrossing::isValid(), GNERerouter::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), and GNEAttributeCarrier::parseAttributeFromXML().
checkGNELanesValid()
bool GNEAttributeCarrier::checkGNELanesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of Lane IDs is valid
value string with a list of lanes report enable or disable show warning if lanes aren't valid
Definition at line 1730 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane(), SUMO_ATTR_LANES, SUMO_TAG_LANE, toString(), and WRITE_WARNING.
Referenced by GNEVariableSpeedSign::isValid(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), and GNEAttributeCarrier::parseAttributeFromXML().
commitGeometryMoving()
void GNEJunction::commitGeometryMoving (const Position & oldPos, GNEUndoList * undoList)
registers completed movement with the undoList
Definition at line 468 of file GNEJunction.cpp.
References NBNode::getPosition(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::GNEChange_Attribute, isValid(), moveJunctionGeometry(), myNBNode, GNEUndoList::p_add(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_ATTR_POSITION, and toString().
Referenced by GNEViewNet::onLeftBtnRelease().
decRef()
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Decrease reference.
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
discreteChoices()
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 1233 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_GUISHAPE, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_VCLASS, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_VTYPE, SumoVehicleClassStrings, SumoVehicleShapeStrings, TLTYPE_INVALID, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
discreteCombinableChoices()
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 1290 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
drawGL()
void GNEJunction::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GNENetElement.
Definition at line 214 of file GNEJunction.cpp.
References PositionVector::area(), BUBBLE_RADIUS, PositionVector::closePolygon(), GLHelper::drawBoxLine(), GLHelper::drawFilledCircle(), GLHelper::drawFilledPoly(), GLHelper::drawFilledPolyTesselated(), GUIVisualizationSettings::drawJunctionShape, GUIGlObject::drawName(), GUITexturesHelper::drawTexturedBox(), GUIVisualizationSettings::editMode, GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), NBNode::getPosition(), NBNode::getShape(), GUITextureSubSys::getTexture(), GUIGlObject::getType(), GNENet::getViewNet(), GNE_MODE_TLS, GNETEXTURE_TLS, gSelected, GUISelectedStorage::isSelected(), NBNode::isTLControlled(), GUIVisualizationSettings::junctionName, GUIVisualizationSettings::junctionSize, myAmTLSSelected, myGNECrossings, myMaxSize, myNBNode, GNENetElement::myNet, GUIVisualizationSettings::scale, PositionVector::scaleRelative(), GUIVisualizationSettings::selectionScale, setColor(), GNEViewNet::showJunctionAsBubbles(), Position::x(), and Position::y().
drawGLAdditional()
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 153 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GNERouteProbe::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
getAdditionalChilds()
const std::vector< GNEAdditional * > & GNENetElement::getAdditionalChilds () const inherited
return vector of additionals that have as Parent this edge (For example, Calibrators)
Definition at line 118 of file GNENetElement.cpp.
References GNENetElement::myAdditionalChilds.
Referenced by GNENet::deleteEdge(), GNENet::deleteLane(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::replaceIncomingEdge(), GNEInspectorFrame::showAttributeCarrierChilds(), and GNEDeleteFrame::showChildsOfMarkedAttributeCarrier().
getAdditionalParents()
const std::vector< GNEAdditional * > & GNENetElement::getAdditionalParents () const inherited
return vector of additionals that have as Parameter this edge (For example, Rerouters)
Definition at line 112 of file GNENetElement.cpp.
References GNENetElement::myAdditionalParents.
Referenced by GNEDeleteFrame::removeAttributeCarrier(), GNENet::replaceIncomingEdge(), and GNEDeleteFrame::showChildsOfMarkedAttributeCarrier().
getAttribute()
std::string GNEJunction::getAttribute (SumoXMLAttr key) const virtual
This functions has to be implemented in all GNEAttributeCarriers.
Implements GNENetElement.
Definition at line 658 of file GNEJunction.cpp.
References NBNode::getControllingTLS(), GNEAttributeCarrier::getID(), NBNode::getKeepClear(), GUIGlObject::getMicrosimID(), NBNode::getPosition(), NBNode::getRadius(), NBNode::getShape(), GNEAttributeCarrier::getTag(), GUIGlObject::getType(), NBNode::getType(), GNE_ATTR_MODIFICATION_STATUS, NBNode::isTLControlled(), myLogicStatus, myNBNode, SUMO_ATTR_ID, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_POSITION, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, and toString().
Referenced by GNENet::mergeJunctions(), GNETLSEditorFrame::onCmdDefCreate(), and setAttribute().
getAttributeForSelection()
std::string GNEAttributeCarrier::getAttributeForSelection (SumoXMLAttr key) const virtual inherited
method for getting the attribute in the context of object selection
Reimplemented in GNEEdge, and GNELane.
Definition at line 183 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute().
Referenced by GNESelectorFrame::getMatches(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttributeType()
std::string GNEAttributeCarrier::getAttributeType (SumoXMLTag tag, SumoXMLAttr attr) static inherited
get type of attribute
Definition at line 247 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), and toString().
Referenced by GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttrs()
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 231 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getBoundary()
Boundary GNEJunction::getBoundary () const
Returns the boundary of the junction.
Definition at line 307 of file GNEJunction.cpp.
References myBoundary.
Referenced by GNENet::registerJunction().
getCenteringBoundary()
Boundary GNEJunction::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GNENetElement.
Definition at line 206 of file GNEJunction.cpp.
References Boundary::grow(), and myBoundary.
getColorValue()
double GNEJunction::getColorValue (const GUIVisualizationSettings & s, bool bubble) const private
determines color value
Definition at line 874 of file GNEJunction.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIGlObject::getGlID(), NBNode::getPosition(), GUIGlObject::getType(), NBNode::getType(), gSelected, GUISelectedStorage::isSelected(), GUIVisualizationSettings::junctionColorer, myNBNode, NODETYPE_ALLWAY_STOP, NODETYPE_DEAD_END, NODETYPE_DEAD_END_DEPRECATED, NODETYPE_DISTRICT, NODETYPE_INTERNAL, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED, NODETYPE_UNKNOWN, NODETYPE_ZIPPER, and Position::z().
Referenced by setColor().
getDefaultValue() [1/12]
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getDefaultValue() [2/12]
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1580 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [3/12]
template<> double GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1592 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [4/12]
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1604 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [5/12]
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1616 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [6/12]
template<> SUMOVehicleClass GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1628 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1640 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [8/12]
template<> RGBColor GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1652 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [9/12]
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1664 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [10/12]
template<> std::vector<double> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1676 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [12/12]
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1700 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefinition()
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 1296 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ACCEL, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEO, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
Referenced by GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getGNEConnections()
std::vector< GNEConnection * > GNEJunction::getGNEConnections () const
Returns all GNEConnections vinculated with this junction.
Definition at line 420 of file GNEJunction.cpp.
References myGNEIncomingEdges.
Referenced by GNENet::clearJunctionConnections(), and getPopUpMenu().
getGNECrossings()
const std::vector< GNECrossing * > & GNEJunction::getGNECrossings () const
Returns GNECrossings.
Definition at line 414 of file GNEJunction.cpp.
References myGNECrossings.
Referenced by GNENet::deleteJunction(), GNEEdge::getGNECrossings(), GNEChange_Crossing::redo(), GNEEdge::removeEdgeFromCrossings(), GNENet::replaceIncomingEdge(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GNEChange_Crossing::undo().
getGNEEdges()
const std::vector< GNEEdge * > & GNEJunction::getGNEEdges () const
Returns all GNEEdges vinculated with this Junction.
Definition at line 396 of file GNEJunction.cpp.
References myGNEEdges.
Referenced by GNEEdge::addLane(), GNENet::deleteJunction(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNECrossingFrame::crossingParameters::invertEdges(), GNECrossingFrame::crossingParameters::markEdge(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeLane(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GNECrossingFrame::crossingParameters::useSelectedEdges().
getGNEIncomingEdges()
const std::vector< GNEEdge * > & GNEJunction::getGNEIncomingEdges () const
Returns incoming GNEEdges.
Definition at line 402 of file GNEJunction.cpp.
References myGNEIncomingEdges.
Referenced by GNELane::getGNEIncomingConnections().
getGNEOutgoingEdges()
const std::vector< GNEEdge * > & GNEJunction::getGNEOutgoingEdges () const
Returns incoming GNEEdges.
Definition at line 408 of file GNEJunction.cpp.
References myGNEOutgoingEdges.
Referenced by GNEAdditional::isRouteValid().
getGUIGLObject() [1/2]
const GUIGlObject * GNEAttributeCarrier::getGUIGLObject () const inherited
get const pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to const GUIGlObject
Definition at line 207 of file GNEAttributeCarrier.cpp.
Referenced by GNEShape::drawLockIcon(), GNENet::insertShape(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::removePolygonForEditShapes(), GNENet::removeShape(), GNENet::retrieveAttributeCarriers(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getGUIGLObject() [2/2]
GUIGlObject * GNEAttributeCarrier::getGUIGLObject () inherited
get pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to GUIGlObject
Definition at line 219 of file GNEAttributeCarrier.cpp.
getGUIIcon()
GUIIcon GNEAttributeCarrier::getGUIIcon () const inherited
get GUI icon assigned to this object
Definition at line 201 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myIcon.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
getHigherNumberOfAttributes()
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 1563 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedNetElementsTags(), GNEAttributeCarrier::allowedShapeTags(), MAX2(), and GNEAttributeCarrier::myMaxNumAttribute.
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getIcon()
FXIcon * GNEAttributeCarrier::getIcon () const inherited
get FXIcon assigned to this object
Definition at line 195 of file GNEAttributeCarrier.cpp.
References GUIIconSubSys::getIcon(), and GNEAttributeCarrier::myIcon.
Referenced by GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNEAdditional::getPopUpMenu(), GNEDeleteFrame::markAttributeCarrier(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEDeleteFrame::updateCurrentLabel(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getID()
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 241 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNECrossingFrame::addCrossing(), GNEAdditional::addEdgeChild(), addIncomingGNEEdge(), GNEAdditional::addLaneChild(), addOutgoingGNEEdge(), GNENet::addPOI(), GNEPolygonFrame::addPOILane(), GNENet::addReversedEdge(), GNELane::addShapeChild(), GNEAdditionalHandler::buildRerouterInterval(), GNENet::changeCalibratorFlowID(), GNENet::changeCalibratorRouteID(), GNENet::changeCalibratorVehicleTypeID(), GNENet::changeShapeID(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECalibratorFlow::getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNECalibrator::getAttribute(), getAttribute(), GNEAdditionalHandler::getPosition(), GNECalibratorRoute::GNECalibratorRoute(), GNENet::insertAdditional(), GNENet::insertCalibratorFlow(), GNENet::insertCalibratorRoute(), GNENet::insertCalibratorVehicleType(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNEDeleteFrame::markAttributeCarrier(), GNECrossingFrame::crossingParameters::markEdge(), GNERerouterDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdSetVariable(), GNECalibratorRouteDialog::onCmdSetVariable(), GNEViewNet::onCmdTransformPOI(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEPolygonFrame::processClick(), GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_TLS::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_CalibratorItem::redo(), GNEChange_RerouterItem::redo(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), removeEdgeFromCrossings(), GNEEdge::removeEdgeOfAdditionalParents(), removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), GNELane::removeLaneOfAdditionalParents(), removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceIncomingEdge(), GNENet::retrieveEdge(), GNEEdge::retrieveGNEConnection(), retrieveGNECrossing(), GNENet::reverseEdge(), GNEInspectorFrame::NeteditParameters::show(), GNEEdge::smooth(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_CalibratorItem::undo(), GNEChange_RerouterItem::undo(), GNENet::updateAdditionalID(), GNECalibratorRouteDialog::updateCalibratorRouteValues(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEBusStop::writeAdditional(), GNEContainerStop::writeAdditional(), GNECalibrator::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), GNEPOILane::writeShape(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and ~GNEJunction().
getJunctionNeighbours()
std::vector< GNEJunction * > GNEJunction::getJunctionNeighbours () const
return GNEJunction neighbours
Definition at line 325 of file GNEJunction.cpp.
References myGNEIncomingEdges, and myGNEOutgoingEdges.
Referenced by GNENet::deleteJunction(), and moveGeometry().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNEPoly::getParentName(), GNERerouter::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNBNode()
NBNode * GNEJunction::getNBNode () const
Return net build node.
Definition at line 313 of file GNEJunction.cpp.
References myNBNode.
Referenced by GNETLSEditorFrame::buildIinternalLanes(), GNENet::changeEdgeEndpoints(), GNENet::computeJunction(), GNENet::createEdge(), GNENet::deleteJunction(), GNENet::deleteSingleJunction(), GNEConnectorFrame::initTargets(), GNETLSEditorFrame::TLSAttributes::initTLSAttributes(), GNENet::insertJunction(), GNECrossing::isValid(), GNENet::mergeJunctions(), GNEViewNet::mergeJunctions(), moveJunctionGeometry(), GNECrossingFrame::onCmdCreateCrossing(), GNEViewNet::onCmdEditJunctionShape(), GNEChange_Crossing::redo(), GNENet::registerJunction(), GNENet::removeSolitaryJunctions(), GNENet::renameJunction(), GNENet::replaceJunctionByGeometry(), GNEEdge::resetEndpoint(), setAttribute(), GNEEdge::setAttribute(), GNEEdge::setEndpoint(), GNEChange_Crossing::undo(), GNETLSEditorFrame::updateDescription(), GNECrossing::updateGeometry(), and GNEEdge::updateJunctionPosition().
getNet()
GNENet * GNENetElement::getNet () const inherited
get Net in which this element is placed
Definition at line 52 of file GNENetElement.cpp.
References GNENetElement::myNet.
Referenced by GNEConnection::setAttribute().
getParameterWindow()
GUIParameterTableWindow * GNENetElement::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 130 of file GNENetElement.cpp.
References GUIParameterTableWindow::closeBuilding(), GNENetElement::getAttribute(), GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::isUnique(), GUIParameterTableWindow::mkItem(), and toString().
getParentName()
const std::string & GNENetElement::getParentName () const virtual inherited
Returns the name of the parent object.
Returns
This object's parent id
Reimplemented from GUIGlObject.
Reimplemented in GNELane.
Definition at line 124 of file GNENetElement.cpp.
References GUIGlObject::getMicrosimID(), and GNENetElement::myNet.
getPopUpMenu()
GUIGLObjectPopupMenu * GNEJunction::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GNENetElement.
Definition at line 162 of file GNEJunction.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), NBNode::checkIsRemovableReporting(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), GNEViewNet::getCurrentEditMode(), getGNEConnections(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), GNENet::getViewNet(), GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_TLS, MID_GNE_JUNCTION_CLEAR_CONNECTIONS, MID_GNE_JUNCTION_EDIT_SHAPE, MID_GNE_JUNCTION_REPLACE, MID_GNE_JUNCTION_RESET_CONNECTIONS, myNBNode, and GNENetElement::myNet.
getPositionInView()
Position GNEJunction::getPositionInView () const
Return current position.
Definition at line 319 of file GNEJunction.cpp.
References NBNode::getPosition(), and myNBNode.
Referenced by GNEViewNet::begingMoveSelection(), GNEEdge::getAttribute(), GNEViewNet::onLeftBtnPress(), and GNEEdge::setAttribute().
getTag()
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get XML Tag assigned to this object
Definition at line 189 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNEAdditional::addEdgeChild(), addIncomingGNEEdge(), GNEAdditional::addLaneChild(), addOutgoingGNEEdge(), GNENet::addPOI(), GNELane::addShapeChild(), GNEViewNet::begingMoveSelection(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildClosingLaneReroute(), GNEAdditionalHandler::buildClosingReroute(), GNEAdditionalHandler::builDestProbReroute(), GNEAdditionalHandler::buildRerouterInterval(), GNEAdditionalHandler::buildRouteProbReroute(), GNEAdditionalHandler::buildVariableSpeedSignStep(), GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNENet::changeShapeID(), GNEDetectorE3::commitGeometryMoving(), GNEPOI::commitGeometryMoving(), GNEDetector::commitGeometryMoving(), GNEPOILane::commitGeometryMoving(), GNEStoppingPlace::commitGeometryMoving(), GNEVariableSpeedSign::commitGeometryMoving(), GNERerouter::commitGeometryMoving(), commitGeometryMoving(), GNEPoly::commitShapeChange(), GNEEdge::commitShapeChange(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteShape(), GNERouteProbReroute::getAttribute(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNEVariableSpeedSignStep::getAttribute(), GNECalibratorRoute::getAttribute(), GNECalibratorVehicleType::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECalibratorFlow::getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNECrossing::getAttribute(), GNEDetectorE3::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), GNECalibrator::getAttribute(), GNELane::getAttribute(), getAttribute(), GNEEdge::getAttribute(), GNESelectorFrame::getMatches(), GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEEdge::getRouteProbeRelativePosition(), GNEEdge::getVaporizerRelativePosition(), GNECalibratorRoute::GNECalibratorRoute(), GNEViewNet::hotkeyEnter(), GNENet::insertAdditional(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNERouteProbReroute::isValid(), GNEDestProbReroute::isValid(), GNEClosingLaneReroute::isValid(), GNEClosingReroute::isValid(), GNEVariableSpeedSignStep::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNERerouterInterval::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), GNECalibratorFlow::isValid(), GNEVaporizer::isValid(), GNECrossing::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNEConnection::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNELane::isValid(), isValid(), GNEEdge::isValid(), GNEAdditional::isValidAdditionalID(), GNEDeleteFrame::markAttributeCarrier(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNEViewNet::onCmdOpenAdditionalDialog(), GNEViewNet::onLeftBtnPress(), GNEAdditional::openAdditionalDialog(), GNEChange_Shape::redo(), GNEChange_Junction::redo(), GNEChange_TLS::redo(), GNEChange_Additional::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_Shape::redoName(), GNEChange_VariableSpeedSignItem::redoName(), GNEChange_Additional::redoName(), GNEChange_Attribute::redoName(), GNEChange_CalibratorItem::redoName(), GNEChange_RerouterItem::redoName(), GNEAdditionalFrame::removeAdditional(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceInListAttribute(), GNEEdge::retrieveGNEConnection(), retrieveGNECrossing(), GNERouteProbReroute::setAttribute(), GNEDestProbReroute::setAttribute(), GNEClosingReroute::setAttribute(), GNEClosingLaneReroute::setAttribute(), GNEVariableSpeedSignStep::setAttribute(), GNECalibratorRoute::setAttribute(), GNECalibratorVehicleType::setAttribute(), GNERerouterInterval::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNECalibratorFlow::setAttribute(), GNEVaporizer::setAttribute(), GNECrossing::setAttribute(), GNEDetectorE3::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNEConnection::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERerouter::setAttribute(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), GNECalibrator::setAttribute(), GNELane::setAttribute(), setAttribute(), GNEEdge::setAttribute(), GNEAdditional::setBlockIconRotation(), GNEInspectorFrame::NeteditParameters::show(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEChange_Shape::undo(), GNEChange_Junction::undo(), GNEChange_TLS::undo(), GNEChange_Additional::undo(), GNEChange_Lane::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_Shape::undoName(), GNEChange_VariableSpeedSignItem::undoName(), GNEChange_Additional::undoName(), GNEChange_Attribute::undoName(), GNEChange_CalibratorItem::undoName(), GNEChange_RerouterItem::undoName(), GNENet::updateAdditionalID(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), GNECalibratorFlow::writeFlow(), GNERerouterInterval::writeRerouterInterval(), GNECalibratorRoute::writeRoute(), GNERouteProbReroute::writeRouteProbReroute(), GNECalibratorVehicleType::writeVehicleType(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_Shape::~GNEChange_Shape(), and GNEChange_TLS::~GNEChange_TLS().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), setAttribute(), setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, GUIPerson, and GUIContainer.
Definition at line 126 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
hasAttribute()
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if an element with certain tag has a certain attribute
Definition at line 1211 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), GNEChange_Additional::GNEChange_Additional(), GNEViewNet::hotkeyEnter(), GNEAdditional::setBlockIconRotation(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
hasDefaultValue()
bool GNEAttributeCarrier::hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if attribute of an element has a default avlue
Definition at line 1222 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
incRef()
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Increarse reference.
Definition at line 76 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNEChange_CalibratorItem::GNEChange_CalibratorItem(), GNEChange_RerouterItem::GNEChange_RerouterItem(), rebuildGNECrossings(), GNENet::registerEdge(), GNENet::registerJunction(), GNEEdge::remakeGNEConnections(), and GNEInspectorFrame::setEdgeTemplate().
invalidateShape()
void GNEJunction::invalidateShape ()
Definition at line 519 of file GNEJunction.cpp.
References NBNode::hasCustomShape(), myNBNode, GNENetElement::myNet, NBNode::myPoly, and GNENet::requireRecompute().
Referenced by GNEEdge::resetEndpoint(), GNEEdge::setAttribute(), GNEEdge::setEndpoint(), and GNEEdge::setGeometry().
invalidateTLS()
void GNEJunction::invalidateTLS (GNEUndoList * undoList, const NBConnection & deletedConnection = NBConnection::InvalidConnection)
Definition at line 575 of file GNEJunction.cpp.
References NBNode::getControllingTLS(), Named::getID(), NBLoadedSUMOTLDef::getLogic(), NBTrafficLightDefinition::getNodes(), NBTrafficLightDefinition::getOffset(), NBTrafficLightDefinition::getProgramID(), NBTrafficLightDefinition::getType(), GNEChange_TLS, GNEUndoList::hasCommandGroup(), NBConnection::InvalidConnection, myNBNode, GNENetElement::myNet, NBLoadedSUMOTLDef::removeConnection(), GNENet::retrieveJunction(), and NBTrafficLightDefinition::setProgramID().
Referenced by GNENet::deleteConnection(), GNEConnectorFrame::handleLaneClick(), and setLogicValid().
isBool()
bool GNEAttributeCarrier::isBool (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool for a certain tag
Definition at line 867 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBoolAttrs, SUMO_ATTR_ACCELERATION, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_FILL, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_GEO, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PASS, SUMO_ATTR_PRIORITY, SUMO_ATTR_REROUTE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POLY, and SUMO_TAG_REROUTER.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isColor()
bool GNEAttributeCarrier::isColor (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type color for a certain tag
Definition at line 910 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myColorAttrs, SUMO_ATTR_COLOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_ROUTE, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isDiscrete()
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 1045 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFilename()
bool GNEAttributeCarrier::isFilename (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a filename
Definition at line 1141 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, SUMO_ATTR_FILE, SUMO_ATTR_IMGFILE, SUMO_ATTR_OUTPUT, SUMO_TAG_CALIBRATOR, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFloat()
bool GNEAttributeCarrier::isFloat (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 741 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_ANGLE, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERIOD, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_STEP, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isInt()
bool GNEAttributeCarrier::isInt (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 707 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_FROM_LANE, SUMO_ATTR_INDEX, SUMO_ATTR_LAYER, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isList()
bool GNEAttributeCarrier::isList (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 935 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, SUMO_ATTR_LINES, SUMO_ATTR_SHAPE, SUMO_TAG_BUS_STOP, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNENet::replaceInListAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isLogicValid()
bool GNEJunction::isLogicValid ()
whether this junction has a valid logic
Definition at line 631 of file GNEJunction.cpp.
References myHasValidLogic.
Referenced by GNELane::drawGL().
isNonEditable()
bool GNEAttributeCarrier::isNonEditable (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is non editable
Definition at line 1193 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNonEditableAttrs, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
isNumerical()
bool GNEAttributeCarrier::isNumerical (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 701 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [1/2]
bool GNEAttributeCarrier::isPositive (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is only Positive (i.e. cannot take negative values)
Definition at line 1055 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myPositiveAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [2/2]
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 249 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFilename(), and GNEAttributeCarrier::isValidID().
isProbability()
bool GNEAttributeCarrier::isProbability (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is a probability (i.e. oly can values between [0, 1])
Definition at line 1122 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myProbabilityAttrs, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_PROB, SUMO_TAG_CHARGING_STATION, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_FLOW, SUMO_TAG_REROUTER, and SUMO_TAG_ROUTE_PROB_REROUTE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isString()
bool GNEAttributeCarrier::isString (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 929 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isNumerical(), and GNEAttributeCarrier::isTime().
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isTime()
bool GNEAttributeCarrier::isTime (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is time
Definition at line 830 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTimeAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_END, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_STARTTIME, SUMO_ATTR_TIME, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isUnique()
bool GNEAttributeCarrier::isUnique (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
Definition at line 958 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspectMultisection(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isValid()
bool GNEJunction::isValid (SumoXMLAttr key, const std::string & value) virtual
Implements GNENetElement.
Definition at line 776 of file GNEJunction.cpp.
References GNEAttributeCarrier::getTag(), StringBijection< T >::hasString(), NBNode::isTLControlled(), GNEAttributeCarrier::isValidID(), myNBNode, GNENetElement::myNet, SUMOXMLDefinitions::NodeTypes, GeomConvHelper::parseShapeReporting(), GNENet::retrieveJunction(), SUMO_ATTR_ID, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_POSITION, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by commitGeometryMoving().
isValidFilename()
bool GNEAttributeCarrier::isValidFilename (const std::string & value) static inherited
true if value is a valid file value
Definition at line 275 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNECalibratorVehicleType::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isValidID()
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 269 of file GNEAttributeCarrier.cpp.
Referenced by GNEAdditional::changeAdditionalID(), GNEAttributeCarrier::isPositive(), GNERouteProbReroute::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNECalibratorFlow::isValid(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), isValid(), GNEEdge::isValid(), GNEAdditional::isValidAdditionalID(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isVClass()
bool GNEAttributeCarrier::isVClass (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a list of Vehicle Classes
Definition at line 1172 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, GNEAttributeCarrier::myVClassAttrs, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_EDGE, and SUMO_TAG_LANE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
markAsCreateEdgeSource()
void GNEJunction::markAsCreateEdgeSource ()
marks as first junction in createEdge-mode
Definition at line 432 of file GNEJunction.cpp.
References myAmCreateEdgeSource.
Referenced by GNEViewNet::onLeftBtnPress().
markAsModified()
void GNEJunction::markAsModified (GNEUndoList * undoList)
prevent re-guessing connections at this junction
Definition at line 564 of file GNEJunction.cpp.
References Named::getID(), NBNode::getIncomingEdges(), GNE_ATTR_MODIFICATION_STATUS, GNEAttributeCarrier::GNEChange_Attribute, GNEAttributeCarrier::MODIFIED, myNBNode, GNENetElement::myNet, and GNENet::retrieveEdge().
Referenced by GNENet::deleteConnection().
moveGeometry()
void GNEJunction::moveGeometry (const Position & oldPos, const Position & offset)
change the position of the element geometry without saving in undoList
Parameters
[in] oldPos old position before start moving
Definition at line 450 of file GNEJunction.cpp.
References Position::add(), getJunctionNeighbours(), NBNode::getPosition(), moveJunctionGeometry(), and myNBNode.
Referenced by GNEViewNet::mergeJunctions(), and GNEViewNet::onMouseMove().
moveJunctionGeometry()
void GNEJunction::moveJunctionGeometry (const Position & pos) private
reposition the node at pos and informs the edges
Parameters
[in] pos The new position
Note
: those operations are not added to the undoList.
Definition at line 928 of file GNEJunction.cpp.
References NBNode::getEdges(), getNBNode(), NBNode::getPosition(), NBNode::getType(), myNBNode, GNENetElement::myNet, NBNode::reinit(), GNENet::retrieveEdge(), and updateShapesAndGeometries().
Referenced by commitGeometryMoving(), moveGeometry(), and setAttribute().
operator=()
GNEJunction& GNEJunction::operator= (const GNEJunction &) private delete
Invalidated assignment operator.
parse() [1/12]
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 88 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int().
parse() [2/12]
template<> double GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 94 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2double().
parse() [3/12]
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 100 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
parse() [4/12]
template<> std::string GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 106 of file GNEAttributeCarrier.cpp.
parse() [5/12]
template<> SUMOVehicleClass GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 112 of file GNEAttributeCarrier.cpp.
References SumoVehicleClassStrings, and SVC_IGNORING.
parse() [6/12]
template<> RGBColor GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 124 of file GNEAttributeCarrier.cpp.
References RGBColor::parseColor().
parse() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 130 of file GNEAttributeCarrier.cpp.
References SumoVehicleShapeStrings, and SVS_UNKNOWN.
parse() [8/12]
template<> std::vector<std::string> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 142 of file GNEAttributeCarrier.cpp.
References SUMOSAXAttributes::parseStringVector().
parse() [9/12]
template<> std::vector<int> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 150 of file GNEAttributeCarrier.cpp.
parse() [10/12]
template<> std::vector<double> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 161 of file GNEAttributeCarrier.cpp.
parse() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 172 of file GNEAttributeCarrier.cpp.
parse() [12/12]
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse().
parseAttributeFromXML()
template<typename T > static T GNEAttributeCarrier::parseAttributeFromXML (const SUMOSAXAttributes & attrs, const std::string & objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool & abort, bool report = true) inline static inherited
Parse attribute from XML and show warnings if there are problems parsing it.
Definition at line 276 of file GNEAttributeCarrier.h.
References canParseVehicleClasses(), GNEAttributeCarrier::checkGNEEdgesValid(), GNEAttributeCarrier::checkGNELanesValid(), SUMOSAXAttributes::get(), GNEAttributeCarrier::getAttributeType(), SUMOSAXAttributes::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), GNEAttributeCarrier::isValidID(), GNEAttributeCarrier::isVClass(), GNEAttributeCarrier::parseGNEEdges(), GNEAttributeCarrier::parseGNELanes(), GNEAttributeCarrier::setAttribute(), SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_VCLASS, toString(), and WRITE_WARNING.
parseGNEEdges() [1/2]
std::vector< GNEEdge * > GNEAttributeCarrier::parseGNEEdges (GNENet * net, const std::string & value) static inherited
parse string into vector of GNEEdges
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1748 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge().
Referenced by GNEAdditionalHandler::buildAdditional(), GNECalibratorRoute::getAttribute(), GNERerouter::getAttribute(), GNECalibratorRoute::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAttributeCarrier::parseAttributeFromXML(), GNECalibratorRoute::setAttribute(), GNECrossing::setAttribute(), GNERerouter::setAttribute(), GNERerouter::writeAdditional(), and GNECalibratorRoute::writeRoute().
parseGNEEdges() [2/2]
std::string GNEAttributeCarrier::parseGNEEdges (const std::vector< GNEEdge *> & edges) static inherited
parse vector of GNEEdges into string
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1774 of file GNEAttributeCarrier.cpp.
References joinToString().
parseGNELanes() [1/2]
std::vector< GNELane * > GNEAttributeCarrier::parseGNELanes (GNENet * net, const std::string & value) static inherited
parse string into vector of GNELanes
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1761 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane().
Referenced by GNEAdditionalHandler::buildAdditional(), GNEVariableSpeedSign::getAttribute(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAttributeCarrier::parseAttributeFromXML(), GNEVariableSpeedSign::setAttribute(), and GNEVariableSpeedSign::writeAdditional().
parseGNELanes() [2/2]
std::string GNEAttributeCarrier::parseGNELanes (const std::vector< GNELane *> & lanes) static inherited
parse vector of GNELanes into string
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1785 of file GNEAttributeCarrier.cpp.
References joinToString().
rebuildGNECrossings()
void GNEJunction::rebuildGNECrossings (bool rebuildNBNodeCrossings = true) private
rebuilds crossing objects for this junction
Definition at line 119 of file GNEJunction.cpp.
References NBNode::buildCrossingsAndWalkingAreas(), OptionsCont::getBool(), NBNode::getCrossingsIncludingInvalid(), GNENet::getNetBuilder(), OptionsCont::getOptions(), NBNetBuilder::haveNetworkCrossings(), GNEReferenceCounter::incRef(), myGNECrossings, myNBNode, GNENetElement::myNet, retrieveGNECrossing(), toString(), GNECrossing::updateGeometry(), and WRITE_WARNING.
Referenced by GNEChange_Crossing::redo(), setLogicValid(), GNEChange_Crossing::undo(), and updateGeometry().
removeAdditionalChild()
void GNENetElement::removeAdditionalChild (GNEAdditional * additional) inherited
remove additional child from this edge
Definition at line 98 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalChilds, toString(), and GNENetElement::updateGeometry().
Referenced by GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNEChange_Additional::redo(), and GNEChange_Additional::undo().
removeAdditionalParent()
void GNENetElement::removeAdditionalParent (GNEAdditional * additional) inherited
remove additional child from this edge
Definition at line 71 of file GNENetElement.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNENetElement::myAdditionalParents, toString(), and GNENetElement::updateGeometry().
removeEdgeFromCrossings()
void GNEJunction::removeEdgeFromCrossings (GNEEdge * edge, GNEUndoList * undoList)
removes the given edge from all pedestrian crossings
Definition at line 607 of file GNEJunction.cpp.
References GNENet::deleteCrossing(), GNEAttributeCarrier::getID(), GNEEdge::getNBEdge(), joinToString(), myGNECrossings, GNENetElement::myNet, and SUMO_ATTR_EDGES.
Referenced by GNENet::deleteEdge().
removeIncomingGNEEdge()
void GNEJunction::removeIncomingGNEEdge (GNEEdge * edge)
remove incoming GNEEdge
Definition at line 368 of file GNEJunction.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myGNEEdges, myGNEIncomingEdges, SUMO_TAG_EDGE, and toString().
Referenced by GNENet::deleteSingleEdge(), and GNEEdge::setAttribute().
removeOutgoingGNEEdge()
void GNEJunction::removeOutgoingGNEEdge (GNEEdge * edge)
remove outgoing GNEEdge
Definition at line 382 of file GNEJunction.cpp.
References GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myGNEEdges, myGNEOutgoingEdges, SUMO_TAG_EDGE, and toString().
Referenced by GNENet::deleteSingleEdge(), and GNEEdge::setAttribute().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
removeTrafficLight()
void GNEJunction::removeTrafficLight (NBTrafficLightDefinition * tlDef) private
removes a traffic light
Definition at line 961 of file GNEJunction.cpp.
References NBTrafficLightLogicCont::extract(), NBTrafficLightDefinition::getNodes(), GNENet::getTLLogicCont(), myNBNode, GNENetElement::myNet, and NBNode::removeTrafficLight().
Referenced by GNEChange_TLS::redo(), and GNEChange_TLS::undo().
retrieveGNECrossing()
GNECrossing * GNEJunction::retrieveGNECrossing (NBNode::Crossing * crossing, bool createIfNoExist = true)
get GNECrossing if exist, and if not create it if create is enabled
Definition at line 637 of file GNEJunction.cpp.
References GNEAttributeCarrier::getID(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), myGNECrossings, toString(), and WRITE_WARNING.
Referenced by rebuildGNECrossings().
selectTLS()
void GNEJunction::selectTLS (bool selected)
notify the junction of being selected in tls-mode. (used to control drawing)
Definition at line 444 of file GNEJunction.cpp.
References myAmTLSSelected.
Referenced by GNETLSEditorFrame::cleanup(), and GNETLSEditorFrame::editJunction().
setAttribute() [1/2]
void GNEJunction::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
Implements GNENetElement.
Definition at line 686 of file GNEJunction.cpp.
References getAttribute(), NBNode::getControllingTLS(), getNBNode(), NBTrafficLightDefinition::getNodes(), OptionsCont::getOptions(), NBTrafficLightLogicCont::getPrograms(), GNEAttributeCarrier::getTag(), GNENet::getTLLogicCont(), GUIGlObject::getType(), GNE_ATTR_MODIFICATION_STATUS, GNEAttributeCarrier::GNEChange_Attribute, GNEChange_TLS, NBNode::isTrafficLight(), myNBNode, GNENetElement::myNet, NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED, SUMOXMLDefinitions::NodeTypes, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveJunction(), SUMO_ATTR_ID, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_POSITION, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, SUMO_TAG_TRAFFIC_LIGHT, and toString().
Referenced by GNENet::deleteJunction(), GNENet::joinSelectedJunctions(), GNENet::mergeJunctions(), GNETLSEditorFrame::onCmdDefCreate(), and GNETLSEditorFrame::onCmdDefDelete().
setAttribute() [2/2]
void GNEJunction::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
method for setting the attribute and nothing else (used in GNEChange_Attribute)
Implements GNENetElement.
Definition at line 815 of file GNEJunction.cpp.
References StringBijection< T >::get(), NBNode::getControllingTLS(), NBNode::getPosition(), GNEAttributeCarrier::getTag(), GNE_ATTR_MODIFICATION_STATUS, GNEAttributeCarrier::GUESSED, NBNode::invalidateIncomingConnections(), moveJunctionGeometry(), myGNEIncomingEdges, myLogicStatus, myNBNode, GNENetElement::myNet, SUMOXMLDefinitions::NodeTypes, GeomConvHelper::parseShapeReporting(), GNENet::refreshElement(), NBNode::reinit(), GNENet::renameJunction(), NBNode::setCustomShape(), NBNode::setKeepClear(), NBNode::setRadius(), SUMO_ATTR_ID, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_POSITION, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
setColor()
void GNEJunction::setColor (const GUIVisualizationSettings & s, bool bubble) const private
sets junction color depending on circumstances
Definition at line 941 of file GNEJunction.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIGlObject::getGlID(), GUIPropertySchemeStorage< T >::getScheme(), GUIGlObject::getType(), gSelected, GUISelectedStorage::isSelected(), GUIVisualizationSettings::junctionColorer, myAmCreateEdgeSource, GNENet::selectionColor, and GLHelper::setColor().
Referenced by drawGL().
setLogicValid()
void GNEJunction::setLogicValid (bool valid, GNEUndoList * undoList, const std::string & status = GUESSED)
Definition at line 528 of file GNEJunction.cpp.
References GNENet::addExplicitTurnaround(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NBEdge::getConnections(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::getTurnDestination(), GNE_ATTR_MODIFICATION_STATUS, GNEAttributeCarrier::GNEChange_Attribute, GNEUndoList::hasCommandGroup(), invalidateTLS(), myHasValidLogic, myNBNode, GNENetElement::myNet, rebuildGNECrossings(), and GNENet::retrieveEdge().
Referenced by GNENet::createEdge(), GNENet::deleteEdge(), GNENet::deleteLane(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNENet::resetJunctionConnections(), GNEEdge::setAttribute(), and GNEEdge::setNumLanes().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setResponsible()
void GNEJunction::setResponsible (bool newVal)
set responsibility for deleting internal strctures
Definition at line 806 of file GNEJunction.cpp.
References myAmResponsible.
Referenced by GNENet::deleteSingleJunction(), and GNENet::registerJunction().
unMarkAsCreateEdgeSource()
void GNEJunction::unMarkAsCreateEdgeSource ()
removes mark as first junction in createEdge-mode
Definition at line 438 of file GNEJunction.cpp.
References myAmCreateEdgeSource.
Referenced by GNEViewNet::abortOperation(), and GNEViewNet::onLeftBtnPress().
unreferenced()
bool GNEReferenceCounter::unreferenced () inline inherited
check if object ins't referenced
Definition at line 87 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
updateGeometry()
void GNEJunction::updateGeometry () virtual
Update the boundary of the junction.
Implements GNENetElement.
Definition at line 102 of file GNEJunction.cpp.
References Boundary::add(), PositionVector::getBoxBoundary(), Boundary::getHeight(), NBNode::getPosition(), NBNode::getShape(), Boundary::getWidth(), MAX2(), myBoundary, myMaxSize, myNBNode, rebuildGNECrossings(), Position::x(), and Position::y().
Referenced by GNEJunction(), GNECrossing::setAttribute(), GNEEdge::setAttribute(), and updateShapesAndGeometries().
updateShapesAndGeometries()
void GNEJunction::updateShapesAndGeometries ()
update shapes of all elements associated to the junction
Note
this include the adyacent nodes connected by edges
if this function is called during 'Move' mode, connections will not be updated to improve efficiency
Definition at line 481 of file GNEJunction.cpp.
References GNENet::getViewNet(), myGNEEdges, GNENetElement::myNet, and updateGeometry().
Referenced by moveJunctionGeometry().
Friends And Related Function Documentation
GNEChange_Crossing
friend class GNEChange_Crossing friend
Definition at line 58 of file GNEJunction.h.
GNEChange_TLS
friend class GNEChange_TLS friend
Declare friend class.
Definition at line 57 of file GNEJunction.h.
Referenced by invalidateTLS(), and setAttribute().
Field Documentation
APPROVED
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 269 of file GNEAttributeCarrier.h.
BUBBLE_RADIUS
const double GNEJunction::BUBBLE_RADIUS static
Definition at line 62 of file GNEJunction.h.
Referenced by GNEEdge::commitShapeChange(), and drawGL().
GUESSED
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 263 of file GNEAttributeCarrier.h.
Referenced by setAttribute(), and GNEEdge::setAttribute().
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
INVALID_POSITION
const double GNEAttributeCarrier::INVALID_POSITION = -1000000 static inherited
default value for invalid positions (used by POIs and Polygons)
Definition at line 272 of file GNEAttributeCarrier.h.
LOADED
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 260 of file GNEAttributeCarrier.h.
MODIFIED
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 266 of file GNEAttributeCarrier.h.
Referenced by markAsModified(), and GNEConnectorFrame::onCmdClearSelectedConnections().
myAdditionalChilds
std::vector<GNEAdditional*> GNENetElement::myAdditionalChilds protected inherited
list of Additional Childs of this NetElement
Definition at line 168 of file GNENetElement.h.
Referenced by GNENetElement::addAdditionalChild(), GNENetElement::getAdditionalChilds(), GNEEdge::getRouteProbeRelativePosition(), GNEEdge::getVaporizerRelativePosition(), GNENetElement::removeAdditionalChild(), GNEEdge::updateGeometry(), and GNELane::updateGeometry().
myAdditionalParents
std::vector<GNEAdditional*> GNENetElement::myAdditionalParents protected inherited
list of Additional parents of this NetElement
Definition at line 165 of file GNENetElement.h.
Referenced by GNENetElement::addAdditionalParent(), GNENetElement::getAdditionalParents(), GNENetElement::removeAdditionalParent(), GNEEdge::removeEdgeOfAdditionalParents(), GNELane::removeLaneOfAdditionalParents(), GNEEdge::updateGeometry(), and GNELane::updateGeometry().
myAmCreateEdgeSource
bool GNEJunction::myAmCreateEdgeSource private
whether this junction is the first junction for a newly creatededge
See also
GNEApplicationWindow::createEdgeSource)
Definition at line 241 of file GNEJunction.h.
Referenced by markAsCreateEdgeSource(), setColor(), and unMarkAsCreateEdgeSource().
myAmResponsible
bool GNEJunction::myAmResponsible private
whether we are responsible for deleting myNBNode
Definition at line 247 of file GNEJunction.h.
Referenced by setResponsible(), and ~GNEJunction().
myAmTLSSelected
bool GNEJunction::myAmTLSSelected private
whether this junction is selected in tls-mode
Definition at line 253 of file GNEJunction.h.
Referenced by drawGL(), and selectTLS().
myBoundary
Boundary GNEJunction::myBoundary private
The represented junction's boundary.
Definition at line 237 of file GNEJunction.h.
Referenced by getBoundary(), getCenteringBoundary(), and updateGeometry().
myGNECrossings
std::vector<GNECrossing*> GNEJunction::myGNECrossings private
the built crossing objects
Definition at line 256 of file GNEJunction.h.
Referenced by drawGL(), getGNECrossings(), rebuildGNECrossings(), removeEdgeFromCrossings(), retrieveGNECrossing(), and ~GNEJunction().
myGNEEdges
std::vector<GNEEdge*> GNEJunction::myGNEEdges private
vector with the GNEEdges vinculated with this junction
Definition at line 225 of file GNEJunction.h.
Referenced by addIncomingGNEEdge(), addOutgoingGNEEdge(), getGNEEdges(), removeIncomingGNEEdge(), removeOutgoingGNEEdge(), and updateShapesAndGeometries().
myGNEIncomingEdges
std::vector<GNEEdge*> GNEJunction::myGNEIncomingEdges private
vector with the incomings GNEEdges vinculated with this junction
Definition at line 228 of file GNEJunction.h.
Referenced by addIncomingGNEEdge(), getGNEConnections(), getGNEIncomingEdges(), getJunctionNeighbours(), removeIncomingGNEEdge(), and setAttribute().
myGNEOutgoingEdges
std::vector<GNEEdge*> GNEJunction::myGNEOutgoingEdges private
vector with the outgoings GNEEdges vinculated with this junction
Definition at line 231 of file GNEJunction.h.
Referenced by addOutgoingGNEEdge(), getGNEOutgoingEdges(), getJunctionNeighbours(), and removeOutgoingGNEEdge().
myHasValidLogic
bool GNEJunction::myHasValidLogic private
whether this junctions logic is valid
Definition at line 250 of file GNEJunction.h.
Referenced by isLogicValid(), and setLogicValid().
myLogicStatus
std::string GNEJunction::myLogicStatus private
modification status of the junction logic (all connections across this junction)
Definition at line 244 of file GNEJunction.h.
Referenced by getAttribute(), and setAttribute().
myMaxSize
double GNEJunction::myMaxSize private
The maximum size (in either x-, or y-dimension) for determining whether to draw or not.
Definition at line 234 of file GNEJunction.h.
Referenced by drawGL(), and updateGeometry().
myNBNode
NBNode& GNEJunction::myNBNode private
A reference to the represented junction.
Definition at line 222 of file GNEJunction.h.
Referenced by addTrafficLight(), commitGeometryMoving(), drawGL(), getAttribute(), getColorValue(), getNBNode(), getPopUpMenu(), getPositionInView(), invalidateShape(), invalidateTLS(), isValid(), markAsModified(), moveGeometry(), moveJunctionGeometry(), rebuildGNECrossings(), removeTrafficLight(), setAttribute(), setLogicValid(), updateGeometry(), and ~GNEJunction().
myNet
GNENet* GNENetElement::myNet protected inherited
the net to inform about updates
Definition at line 162 of file GNENetElement.h.
Referenced by GNEEdge::addConnection(), addTrafficLight(), GNEEdge::commitShapeChange(), GNEEdge::deleteGeometryPoint(), drawGL(), GNEConnection::drawGL(), GNENetElement::getNet(), GNEEdge::getOppositeEdge(), GNENetElement::getParentName(), GNECrossing::getPopUpMenu(), getPopUpMenu(), GNELane::getPopUpMenu(), GNEConnection::getPopUpMenu(), invalidateShape(), invalidateTLS(), GNECrossing::isValid(), isValid(), GNEEdge::isValid(), markAsModified(), GNEEdge::moveEntireShape(), moveJunctionGeometry(), rebuildGNECrossings(), GNEEdge::removeConnection(), removeEdgeFromCrossings(), GNEEdge::removeEdgeFromCrossings(), GNEEdge::removeLane(), removeTrafficLight(), GNEEdge::retrieveGNEConnection(), GNECrossing::setAttribute(), GNEConnection::setAttribute(), setAttribute(), GNEEdge::setAttribute(), GNELane::setAttribute(), GNEEdge::setGeometry(), setLogicValid(), GNEEdge::updateGeometry(), GNELane::updateGeometry(), and updateShapesAndGeometries().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GNEJunction.h
GNEJunction.cpp