SUMO - Simulation of Urban MObility: MSLeaderDistanceInfo Class Reference
MSLeaderDistanceInfo Class Reference
saves leader/follower vehicles and their distances relative to an ego vehicle
#include <MSLeaderInfo.h>
Public Member Functions
virtual int addLeader (const MSVehicle *veh, double gap, double latOffset=0, int sublane=-1)
virtual int addLeader (const MSVehicle *veh, bool beyond, double latOffset=0)
virtual void clear ()
discard all information
void getSublaneBorders (int sublane, double latOffset, double &rightSide, double &leftSide) const
void getSubLanes (const MSVehicle *veh, double latOffset, int &rightmost, int &leftmost) const
bool hasStoppedVehicle () const
whether a stopped vehicle is leader
bool hasVehicles () const
MSLeaderDistanceInfo (const MSLane *lane, const MSVehicle *ego, double latOffset)
Constructor.
MSLeaderDistanceInfo (const CLeaderDist &cLeaderDist, const MSLane *dummy)
Construct for the non-sublane-case.
int numFreeSublanes () const
int numSublanes () const
CLeaderDist operator[] (int sublane) const
return the vehicle and its distance for the given sublane
virtual std::string toString () const
print a debugging representation
virtual ~MSLeaderDistanceInfo ()
Destructor.
Protected Attributes
int egoLeftMost
int egoRightMost
borders of the ego vehicle for filtering of free sublanes
std::vector< double > myDistances
int myFreeSublanes
the number of free sublanes
bool myHasVehicles
std::vector< const MSVehicle * > myVehicles
double myWidth
the width of the lane to which this instance applies
Detailed Description
saves leader/follower vehicles and their distances relative to an ego vehicle
Definition at line 135 of file MSLeaderInfo.h.
Constructor & Destructor Documentation
MSLeaderDistanceInfo() [1/2]
MSLeaderDistanceInfo::MSLeaderDistanceInfo (const MSLane * lane, const MSVehicle * ego, double latOffset)
Constructor.
Definition at line 202 of file MSLeaderInfo.cpp.
MSLeaderDistanceInfo() [2/2]
MSLeaderDistanceInfo::MSLeaderDistanceInfo (const CLeaderDist & cLeaderDist, const MSLane * dummy)
Construct for the non-sublane-case.
Definition at line 208 of file MSLeaderInfo.cpp.
References MSLeaderInfo::myVehicles.
~MSLeaderDistanceInfo()
MSLeaderDistanceInfo::~MSLeaderDistanceInfo () virtual
Destructor.
Definition at line 215 of file MSLeaderInfo.cpp.
Member Function Documentation
addLeader() [1/2]
int MSLeaderDistanceInfo::addLeader (const MSVehicle * veh, double gap, double latOffset = 0, int sublane = -1) virtual
Reimplemented in MSCriticalFollowerDistanceInfo.
Definition at line 219 of file MSLeaderInfo.cpp.
References MSLeaderInfo::egoLeftMost, MSLeaderInfo::egoRightMost, MSLeaderInfo::getSubLanes(), myDistances, MSLeaderInfo::myFreeSublanes, MSLeaderInfo::myHasVehicles, and MSLeaderInfo::myVehicles.
Referenced by MSLaneChangerSublane::getLeaders(), and MSLane::getLeadersOnConsecutive().
addLeader() [2/2]
virtual int MSLeaderDistanceInfo::addLeader (const MSVehicle * veh, bool beyond, double latOffset = 0) inline virtual
Reimplemented from MSLeaderInfo.
Reimplemented in MSCriticalFollowerDistanceInfo.
Definition at line 156 of file MSLeaderInfo.h.
References MSLeaderInfo::clear(), MSLeaderInfo::operator[](), MSLeaderInfo::toString(), and UNUSED_PARAMETER.
clear()
void MSLeaderDistanceInfo::clear () virtual
discard all information
Reimplemented from MSLeaderInfo.
Reimplemented in MSCriticalFollowerDistanceInfo.
Definition at line 260 of file MSLeaderInfo.cpp.
References MSLeaderInfo::clear(), myDistances, and MSLeaderInfo::myVehicles.
Referenced by MSCriticalFollowerDistanceInfo::clear().
getSublaneBorders()
void MSLeaderInfo::getSublaneBorders (int sublane, double latOffset, double & rightSide, double & leftSide) const inherited
Definition at line 152 of file MSLeaderInfo.cpp.
References MSGlobals::gLateralResolution, MIN2(), MSLeaderInfo::myVehicles, and MSLeaderInfo::myWidth.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLCM_SL2015::updateGaps().
getSubLanes()
void MSLeaderInfo::getSubLanes (const MSVehicle * veh, double latOffset, int & rightmost, int & leftmost) const inherited
Definition at line 112 of file MSLeaderInfo.cpp.
References DELTA_T, MSVehicle::getActionStepLength(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getManeuverDist(), MSVehicleType::getMaxSpeedLat(), MSAbstractLaneChangeModel::getSpeedLat(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, MAX2(), MIN2(), MSLeaderInfo::myVehicles, MSLeaderInfo::myWidth, and NUMERICAL_EPS.
Referenced by MSVehicle::adaptToLeaders(), MSCriticalFollowerDistanceInfo::addFollower(), MSLeaderInfo::addLeader(), addLeader(), MSLeaderInfo::MSLeaderInfo(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
hasStoppedVehicle()
bool MSLeaderInfo::hasStoppedVehicle () const inherited
whether a stopped vehicle is leader
Definition at line 185 of file MSLeaderInfo.cpp.
References MSLeaderInfo::myHasVehicles, and MSLeaderInfo::myVehicles.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkStrategicChange(), and MSLeaderInfo::hasVehicles().
hasVehicles()
bool MSLeaderInfo::hasVehicles () const inline inherited
Definition at line 102 of file MSLeaderInfo.h.
References MSLeaderInfo::hasStoppedVehicle(), MSLeaderInfo::myHasVehicles, and MSLeaderInfo::toString().
Referenced by MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitFollowSpeed(), MSLane::isInsertionSuccess(), and MSLCM_SL2015::updateGaps().
numFreeSublanes()
int MSLeaderInfo::numFreeSublanes () const inline inherited
Definition at line 98 of file MSLeaderInfo.h.
References MSLeaderInfo::myFreeSublanes.
Referenced by MSLane::getFollowersOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), and MSLane::isInsertionSuccess().
numSublanes()
int MSLeaderInfo::numSublanes () const inline inherited
Definition at line 94 of file MSLeaderInfo.h.
References MSLeaderInfo::myVehicles.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::computeSublaneShift(), MSLane::detectCollisions(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLCM_SL2015::getLongest(), MSLCM_SL2015::getSlowest(), MSEdge::initialize(), MSLane::isInsertionSuccess(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLCM_SL2015::updateGaps().
operator[]()
CLeaderDist MSLeaderDistanceInfo::operator[] (int sublane) const
return the vehicle and its distance for the given sublane
Definition at line 267 of file MSLeaderInfo.cpp.
References myDistances, and MSLeaderInfo::myVehicles.
toString()
std::string MSLeaderDistanceInfo::toString () const virtual
print a debugging representation
Reimplemented from MSLeaderInfo.
Reimplemented in MSCriticalFollowerDistanceInfo.
Definition at line 275 of file MSLeaderInfo.cpp.
References Named::getIDSecure(), myDistances, MSLeaderInfo::myFreeSublanes, and MSLeaderInfo::myVehicles.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLaneChangerSublane::checkChangeSublane(), MSLaneChangerSublane::getLeaders(), and MSLCM_SL2015::updateCFRelated().
Field Documentation
egoLeftMost
int MSLeaderInfo::egoLeftMost protected inherited
Definition at line 127 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), MSLeaderInfo::addLeader(), addLeader(), MSLeaderInfo::clear(), and MSLeaderInfo::MSLeaderInfo().
egoRightMost
int MSLeaderInfo::egoRightMost protected inherited
borders of the ego vehicle for filtering of free sublanes
Definition at line 126 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), MSLeaderInfo::addLeader(), addLeader(), MSLeaderInfo::clear(), and MSLeaderInfo::MSLeaderInfo().
myDistances
std::vector<double> MSLeaderDistanceInfo::myDistances protected
Definition at line 174 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), clear(), operator[](), toString(), and MSCriticalFollowerDistanceInfo::toString().
myFreeSublanes
int MSLeaderInfo::myFreeSublanes protected inherited
the number of free sublanes
Definition at line 123 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), MSLeaderInfo::addLeader(), addLeader(), MSLeaderInfo::clear(), MSLeaderInfo::MSLeaderInfo(), MSLeaderInfo::numFreeSublanes(), MSLeaderInfo::toString(), toString(), and MSCriticalFollowerDistanceInfo::toString().
myHasVehicles
bool MSLeaderInfo::myHasVehicles protected inherited
Definition at line 129 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), MSLeaderInfo::addLeader(), addLeader(), MSLeaderInfo::hasStoppedVehicle(), and MSLeaderInfo::hasVehicles().
myVehicles
std::vector<const MSVehicle*> MSLeaderInfo::myVehicles protected inherited
Definition at line 118 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), MSLeaderInfo::addLeader(), addLeader(), MSLeaderInfo::clear(), clear(), MSCriticalFollowerDistanceInfo::clear(), MSLeaderInfo::getSublaneBorders(), MSLeaderInfo::getSubLanes(), MSLeaderInfo::hasStoppedVehicle(), MSLeaderDistanceInfo(), MSLeaderInfo::MSLeaderInfo(), MSLeaderInfo::numSublanes(), MSLeaderInfo::operator[](), operator[](), MSLeaderInfo::toString(), toString(), and MSCriticalFollowerDistanceInfo::toString().
myWidth
double MSLeaderInfo::myWidth protected inherited
the width of the lane to which this instance applies
Definition at line 116 of file MSLeaderInfo.h.
Referenced by MSLeaderInfo::getSublaneBorders(), and MSLeaderInfo::getSubLanes().
The documentation for this class was generated from the following files:
MSLeaderInfo.h
MSLeaderInfo.cpp