SUMO - Simulation of Urban MObility: PCPolyContainer Class Reference
PCPolyContainer Class Reference
A storage for loaded polygons and pois.
#include <PCPolyContainer.h>
Data Structures
struct LanePos
Public Types
typedef NamedObjectCont< PointOfInterest * > POIs
typedef NamedObjectCont< SUMOPolygon * > Polygons
containers
Public Member Functions
bool add (SUMOPolygon *poly, bool ignorePruning=false)
Adds a polygon to the storage.
bool add (PointOfInterest *poi, bool ignorePruning=false)
Adds a poi to the storage.
void addLanePos (const std::string &poiID, const std::string &laneID, double lanePos, double lanePosLat)
virtual bool addPOI (const std::string &id, const std::string &type, const RGBColor &color, const Position &pos, bool geo, const std::string &lane, double posOverLane, double posLat, double layer, double angle, const std::string &imgFile, double width, double height, bool ignorePruning=false)
Builds a POI using the given values and adds it to the container.
virtual bool addPolygon (const std::string &id, const std::string &type, const RGBColor &color, double layer, double angle, const std::string &imgFile, const PositionVector &shape, bool geo, bool fill, bool ignorePruning=false)
Builds a polygon using the given values and adds it to the container.
int getEnumIDFor (const std::string &key)
Retuns a unique id for a given name.
const POIs & getPOIs () const
Returns all pois.
const Polygons & getPolygons () const
Returns all polygons.
virtual void movePOI (const std::string &id, const Position &pos)
Assigns a new position to the named PoI.
PCPolyContainer (bool prune, const Boundary &pruningBoundary, const std::vector< std::string > &removeByNames)
Constructor.
virtual bool removePOI (const std::string &id)
Removes a PoI from the container.
virtual bool removePolygon (const std::string &id)
Removes a polygon from the container.
virtual void reshapePolygon (const std::string &id, const PositionVector &shape)
Assigns a shape to the named polygon.
void save (const std::string &file, bool useGeo)
Saves the stored polygons and pois into the given file.
void saveDlrTDP (const std::string &prefix)
Saves the stored polygons and pois into the given file in dlrTDP format.
~PCPolyContainer ()
Destructor.
Protected Attributes
POIs myPOIs
stored POIs
Polygons myPolygons
stored Polygons
Private Member Functions
PCPolyContainer & operator= (const PCPolyContainer &s)
Invalidated assignment operator.
PCPolyContainer (const PCPolyContainer &s)
Invalidated copy constructor.
Static Private Member Functions
static void writeDlrTDPHeader (OutputDevice &device, const OptionsCont &oc)
Private Attributes
bool myDoPrune
Information whether the pruning boundary shall be used.
std::map< std::string, int > myIDEnums
An id to int map for proper enumeration.
std::map< std::string, LanePos > myLanePosPois
An id to pos map for lane pos specs.
Boundary myPruningBoundary
The boundary that described the rectangle within which an object must be in order to be kept.
std::vector< std::string > myRemoveByNames
List of names of polygons/pois that shall be removed.
Detailed Description
A storage for loaded polygons and pois.
Definition at line 57 of file PCPolyContainer.h.
Member Typedef Documentation
POIs
typedef NamedObjectCont<PointOfInterest*> ShapeContainer::POIs inherited
Definition at line 52 of file ShapeContainer.h.
Polygons
typedef NamedObjectCont<SUMOPolygon*> ShapeContainer::Polygons inherited
containers
Definition at line 51 of file ShapeContainer.h.
Constructor & Destructor Documentation
PCPolyContainer() [1/2]
PCPolyContainer::PCPolyContainer (bool prune, const Boundary & pruningBoundary, const std::vector< std::string > & removeByNames)
Constructor.
Parameters
[in] prune Whether added polygons/pois shall be pruned
[in] pruningBoundary The pruning boundary (only valid if prune==true)
[in] removeByNames Names of objects that shall not be added
Definition at line 51 of file PCPolyContainer.cpp.
~PCPolyContainer()
PCPolyContainer::~PCPolyContainer ()
Destructor.
Definition at line 58 of file PCPolyContainer.cpp.
References NamedObjectCont< T >::clear(), ShapeContainer::myPOIs, and ShapeContainer::myPolygons.
PCPolyContainer() [2/2]
PCPolyContainer::PCPolyContainer (const PCPolyContainer & s) private
Invalidated copy constructor.
Member Function Documentation
add() [1/2]
bool PCPolyContainer::add (SUMOPolygon * poly, bool ignorePruning = false) virtual
Adds a polygon to the storage.
If pruning is enabled, "ignorePruning" is false and the polygon lies outside the pruning boundary, or if the polygon's name is within the names of objects to discard, the polygon is deleted and false is returned.
Afterwards it is tested whether a polygon with the same name is already stored. If so, an error message is printed, the polygon is deleted and false is returned, otherwise true.
Parameters
[in] poly The polygon to add
[in] ignorePruning Whether the polygon shall be kept, even though it would be pruned
Returns
Whether the polygon could be added
Reimplemented from ShapeContainer.
Definition at line 65 of file PCPolyContainer.cpp.
References ShapeContainer::add(), PositionVector::getBoxBoundary(), Named::getID(), SUMOPolygon::getShape(), myDoPrune, myPruningBoundary, myRemoveByNames, and Boundary::partialWithin().
Referenced by PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), PCLoaderVisum::load(), PCLoaderArcView::load(), PCLoaderDlrNavteq::loadPOIFile(), and PCLoaderDlrNavteq::loadPolyFile().
add() [2/2]
bool PCPolyContainer::add (PointOfInterest * poi, bool ignorePruning = false) virtual
Adds a poi to the storage.
If pruning is enabled, "ignorePruning" is false and the poi lies outside the pruning boundary, or if the poi's name is within the names of objects to discard, the poi is deleted and false is returned.
Afterwards it is tested whether a poi with the same name is already stored. If so, an error message is printed, the poi is deleted and false is returned, otherwise true.
Parameters
[in] poly The poi to add
[in] ignorePruning Whether the poi shall be kept, even though it would be pruned
Returns
Whether the poi could be added
Reimplemented from ShapeContainer.
Definition at line 85 of file PCPolyContainer.cpp.
References ShapeContainer::add(), Boundary::around(), Named::getID(), myDoPrune, myPruningBoundary, and myRemoveByNames.
addLanePos()
void PCPolyContainer::addLanePos (const std::string & poiID, const std::string & laneID, double lanePos, double lanePosLat)
Definition at line 104 of file PCPolyContainer.cpp.
References myLanePosPois.
addPOI()
bool ShapeContainer::addPOI (const std::string & id, const std::string & type, const RGBColor & color, const Position & pos, bool geo, const std::string & lane, double posOverLane, double posLat, double layer, double angle, const std::string & imgFile, double width, double height, bool ignorePruning = false) virtual inherited
Builds a POI using the given values and adds it to the container.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] pos The position of the POI
Reimplemented in GNENet, and GUIShapeContainer.
Definition at line 64 of file ShapeContainer.cpp.
References ShapeContainer::add().
Referenced by libsumo::POI::add(), and ShapeHandler::addPOI().
addPolygon()
bool ShapeContainer::addPolygon (const std::string & id, const std::string & type, const RGBColor & color, double layer, double angle, const std::string & imgFile, const PositionVector & shape, bool geo, bool fill, bool ignorePruning = false) virtual inherited
Builds a polygon using the given values and adds it to the container.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] geo specify if shape was loaded as GEO coordinate
[in] fill Whether the polygon shall be filled
Returns
whether the polygon could be added
Reimplemented in GNENet, and GUIShapeContainer.
Definition at line 55 of file ShapeContainer.cpp.
References ShapeContainer::add().
Referenced by libsumo::Polygon::add(), NLHandler::addDistrict(), and ShapeHandler::addPoly().
getEnumIDFor()
int PCPolyContainer::getEnumIDFor (const std::string & key)
Retuns a unique id for a given name.
The unique id is generated by having an internal map of ids to running numbers. The first call to this method will return 0, all subsequent with the same key will return numbers increased by one at each call.
Parameters
[in] key The key to get a running number for
Returns
Unique id (running number of calls that used this key)
Definition at line 216 of file PCPolyContainer.cpp.
References myIDEnums.
Referenced by PCLoaderDlrNavteq::loadPolyFile().
getPOIs()
const POIs& ShapeContainer::getPOIs () const inline inherited
Returns all pois.
Definition at line 128 of file ShapeContainer.h.
References ShapeContainer::add(), and ShapeContainer::myPOIs.
Referenced by ShapeHandler::addPOI(), libsumo::POI::getIDList(), libsumo::POI::getPoI(), TraCIServerAPI_POI::getPoI(), GUIShapeContainer::getPOIIds(), libsumo::POI::getTree(), GNESelectorFrame::onCmdInvert(), and GNENet::retrieveShapes().
getPolygons()
const Polygons& ShapeContainer::getPolygons () const inline inherited
Returns all polygons.
Definition at line 123 of file ShapeContainer.h.
References ShapeContainer::myPolygons.
Referenced by ShapeHandler::addPoly(), libsumo::Polygon::getIDList(), libsumo::Polygon::getPolygon(), TraCIServerAPI_Polygon::getPolygon(), GUIShapeContainer::getPolygonIDs(), libsumo::Polygon::getTree(), PCLoaderDlrNavteq::loadPolyFile(), GNESelectorFrame::onCmdInvert(), and GNENet::retrieveShapes().
movePOI()
void ShapeContainer::movePOI (const std::string & id, const Position & pos) virtual inherited
Assigns a new position to the named PoI.
Parameters
[in] id The id of the PoI to move
[in] pos The PoI's new position
Reimplemented in GUIShapeContainer.
Definition at line 84 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), and ShapeContainer::myPOIs.
operator=()
PCPolyContainer& PCPolyContainer::operator= (const PCPolyContainer & s) private
Invalidated assignment operator.
removePOI()
bool ShapeContainer::removePOI (const std::string & id) virtual inherited
Removes a PoI from the container.
Parameters
[in] id The id of the PoI
Returns
Whether the poi could be removed
Reimplemented in GUIShapeContainer.
Definition at line 78 of file ShapeContainer.cpp.
References ShapeContainer::myPOIs, and NamedObjectCont< T >::remove().
Referenced by libsumo::POI::remove(), and GNEChange_Attribute::~GNEChange_Attribute().
removePolygon()
bool ShapeContainer::removePolygon (const std::string & id) virtual inherited
Removes a polygon from the container.
Parameters
[in] id The id of the polygon
Returns
Whether the polygon could be removed
Reimplemented in GUIShapeContainer.
Definition at line 72 of file ShapeContainer.cpp.
References ShapeContainer::myPolygons, and NamedObjectCont< T >::remove().
Referenced by libsumo::Polygon::remove(), and GNEChange_Attribute::~GNEChange_Attribute().
reshapePolygon()
void ShapeContainer::reshapePolygon (const std::string & id, const PositionVector & shape) virtual inherited
Assigns a shape to the named polygon.
Parameters
[in] id The id of the polygon to reshape
[in] shape The polygon's new shape
Reimplemented in GUIShapeContainer.
Definition at line 93 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), ShapeContainer::myPolygons, and SUMOPolygon::setShape().
Referenced by libsumo::Polygon::setShape().
save()
void PCPolyContainer::save (const std::string & file, bool useGeo)
Saves the stored polygons and pois into the given file.
Parameters
[in] file The name of the file to write stored objects' definitions into
[in] useGeo Whether to write output in geo-coordinates
Exceptions
IOError If the file could not be opened
Definition at line 110 of file PCPolyContainer.cpp.
References OutputDevice::close(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), OptionsCont::getFloat(), OptionsCont::getOptions(), gPrecisionGeo, myLanePosPois, ShapeContainer::myPOIs, ShapeContainer::myPolygons, OutputDevice::setPrecision(), GeoConvHelper::usingGeoProjection(), WRITE_WARNING, GeoConvHelper::writeLocation(), and OutputDevice::writeXMLHeader().
saveDlrTDP()
void PCPolyContainer::saveDlrTDP (const std::string & prefix)
Saves the stored polygons and pois into the given file in dlrTDP format.
Parameters
[in] prefix The prefix of the file to write stored objects' definitions into
Definition at line 163 of file PCPolyContainer.cpp.
References GeoConvHelper::cartesian2geo(), OutputDevice::close(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), OptionsCont::getOptions(), Position::mul(), ShapeContainer::myPOIs, ShapeContainer::myPolygons, OutputDevice::setPrecision(), GeoConvHelper::usingGeoProjection(), writeDlrTDPHeader(), Position::x(), and Position::y().
writeDlrTDPHeader()
void PCPolyContainer::writeDlrTDPHeader (OutputDevice & device, const OptionsCont & oc) static private
Definition at line 141 of file PCPolyContainer.cpp.
References OptionsCont::getFullName(), OUTPUT_VERSION, and OptionsCont::writeConfiguration().
Referenced by saveDlrTDP().
Field Documentation
myDoPrune
bool PCPolyContainer::myDoPrune private
Information whether the pruning boundary shall be used.
Definition at line 151 of file PCPolyContainer.h.
Referenced by add().
myIDEnums
std::map<std::string, int> PCPolyContainer::myIDEnums private
An id to int map for proper enumeration.
Definition at line 145 of file PCPolyContainer.h.
Referenced by getEnumIDFor().
myLanePosPois
std::map<std::string, LanePos> PCPolyContainer::myLanePosPois private
An id to pos map for lane pos specs.
Definition at line 142 of file PCPolyContainer.h.
Referenced by addLanePos(), and save().
myPOIs
POIs ShapeContainer::myPOIs protected inherited
stored POIs
Definition at line 144 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), GUIShapeContainer::addPOI(), GNENet::addPOI(), GNENet::changeShapeID(), GNENet::computeAndUpdate(), GNENet::generateShapeID(), GNENet::getGlIDs(), GNENet::getNumberOfShapes(), ShapeContainer::getPOIs(), GNENet::insertShape(), ShapeContainer::movePOI(), GUIShapeContainer::movePOI(), ShapeContainer::removePOI(), GUIShapeContainer::removePOI(), GNENet::removeShape(), GNENet::retrievePOI(), GNENet::retrievePOILane(), save(), saveDlrTDP(), GNENet::saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and ~PCPolyContainer().
myPolygons
Polygons ShapeContainer::myPolygons protected inherited
stored Polygons
Definition at line 141 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), GUIShapeContainer::addPolygon(), GNENet::addPolygon(), GNENet::changeShapeID(), GNENet::computeAndUpdate(), GNENet::generateShapeID(), GNENet::getGlIDs(), GNENet::getNumberOfShapes(), ShapeContainer::getPolygons(), GNENet::insertShape(), ShapeContainer::removePolygon(), GUIShapeContainer::removePolygon(), GNENet::removeShape(), ShapeContainer::reshapePolygon(), GUIShapeContainer::reshapePolygon(), GNENet::retrievePolygon(), save(), saveDlrTDP(), GNENet::saveShapes(), GNEChange_Shape::~GNEChange_Shape(), and ~PCPolyContainer().
myPruningBoundary
Boundary PCPolyContainer::myPruningBoundary private
The boundary that described the rectangle within which an object must be in order to be kept.
Definition at line 148 of file PCPolyContainer.h.
Referenced by add().
myRemoveByNames
std::vector<std::string> PCPolyContainer::myRemoveByNames private
List of names of polygons/pois that shall be removed.
Definition at line 154 of file PCPolyContainer.h.
Referenced by add().
The documentation for this class was generated from the following files:
PCPolyContainer.h
PCPolyContainer.cpp