SUMO - Simulation of Urban MObility: NIVissimEdge Class Reference
NIVissimEdge Class Reference
A temporary storage for edges imported from Vissim.
#include <NIVissimEdge.h>
Data Structures
class connection_cluster_position_sorter
class connection_position_sorter
Public Member Functions
void addDisturbance (int disturbance)
void addIncomingConnection (int id)
Adds a connection where this edge is the destination.
void addOutgoingConnection (int id)
Adds a connection where this edge is the source.
void addToConnectionCluster (NIVissimConnectionCluster *c)
bool addToTreatAsSame (NIVissimEdge *e)
void buildGeom ()
void checkDistrictConnectionExistanceAt (double pos)
bool crossesEdge (NIVissimAbstractEdge *c) const
Position crossesEdgeAtPoint (NIVissimAbstractEdge *c) const
Position getBegin2D () const
NIVissimEdge * getBestIncoming () const
NIVissimEdge * getBestOutgoing () const
NIVissimConnection * getConnectionTo (NIVissimEdge *e)
const std::vector< int > & getDisturbances () const
Position getEnd2D () const
Returns the end position of the edge.
const PositionVector & getGeometry () const
Position getGeomPosition (double pos) const
int getID () const
double getLength () const
Returns the length of the node.
NBNode * getNodeAt (const Position &p, NBNode *other=0)
Returns the node at the given position As this may be ambigous, a second node not to return may be supplied.
const std::vector< NIVissimEdge * > & getToTreatAsSame () const
bool hasNodeCluster () const
void mergedInto (NIVissimConnectionCluster *old, NIVissimConnectionCluster *act)
NIVissimEdge (int id, const std::string &name, const std::string &type, int noLanes, double zuschlag1, double zuschlag2, double length, const PositionVector &geom, const NIVissimClosedLanesVector &clv)
Constructor.
bool overlapsWith (const AbstractPoly &p, double offset=0.0) const
void removeFromConnectionCluster (NIVissimConnectionCluster *c)
void setNodeCluster (int nodeid)
void setSpeed (int lane, int speedDist)
void splitAssigning ()
bool wasWithinAJunction () const
Returns whether this edge was found to be within a junction.
~NIVissimEdge ()
Destructor.
Static Public Member Functions
static void buildConnectionClusters ()
Clusters connections of each edge.
static void clearDict ()
static void dict_buildNBEdges (NBDistrictCont &dc, NBNodeCont &nc, NBEdgeCont &ec, double offset)
Builds NBEdges from the VissimEdges within the dictionary.
static void dict_checkEdges2Join ()
static void dict_propagateSpeeds ()
static bool dictionary (int id, NIVissimAbstractEdge *e)
static bool dictionary (int id, const std::string &name, const std::string &type, int noLanes, double zuschlag1, double zuschlag2, double length, const PositionVector &geom, const NIVissimClosedLanesVector &clv)
Adds the described item to the dictionary Builds the edge first.
static bool dictionary (int id, NIVissimEdge *o)
Adds the edge to the dictionary.
static NIVissimEdge * dictionary (int id)
Returns the named edge from the dictionary.
static std::vector< int > getWithin (const AbstractPoly &p, double offset=0.0)
static void reportUnsetSpeeds ()
Writes edges with unset speeds to the warnings message log instance.
static void splitAndAssignToNodes ()
Protected Attributes
std::vector< int > myDisturbances
PositionVector myGeom
int myID
int myNode
Private Types
typedef std::vector< NIVissimConnectionCluster * > ConnectionClusters
The definition for a container for connection clusters.
typedef std::map< int, NIVissimEdge * > DictType
Definition of the dictionary type.
Private Member Functions
void buildNBEdge (NBDistrictCont &dc, NBNodeCont &nc, NBEdgeCont &ec, double sameNodesOffset)
Builds the NBEdge from this VissimEdge.
void checkUnconnectedLaneSpeeds ()
std::pair< NIVissimConnectionCluster *, NBNode * > getFromNode (NBNodeCont &nc, ConnectionClusters &clusters)
Returns the origin node.
std::vector< NIVissimConnection * > getOutgoingConnected (int lane) const
double getRealSpeed (int distNo)
std::pair< NIVissimConnectionCluster *, NBNode * > getToNode (NBNodeCont &nc, ConnectionClusters &clusters)
Returns the destination node.
void propagateOwn ()
void propagateSpeed (double speed, std::vector< int > forLanes)
std::pair< NBNode *, NBNode * > remapOneOfNodes (NBNodeCont &nc, NIVissimDistrictConnection *d, NBNode *fromNode, NBNode *toNode)
std::pair< NBNode *, NBNode * > resolveSameNode (NBNodeCont &nc, double offset, NBNode *prevFrom, NBNode *prevTo)
Tries to resolve the problem that the same node has been returned as origin and destination node.
void setDistrictSpeed ()
Static Private Member Functions
static NBNode * getNodeSecure (int nodeid, const Position &pos, const std::string &possibleName)
Private Attributes
bool myAmWithinJunction
Information whether this edge was not build due to being within a junction.
NIVissimClosedLanesVector myClosedLanes
List of lanes closed on this edge.
ConnectionClusters myConnectionClusters
List of connection clusters along this edge.
std::vector< double > myDistrictConnections
std::vector< int > myIncomingConnections
List of connections incoming to this edge.
std::vector< double > myLaneSpeeds
std::string myName
The name of the edge.
int myNoLanes
The number of lanes the edge has.
std::vector< int > myOutgoingConnections
List of connections outgoing from this edge.
std::vector< int > myPatchedSpeeds
std::vector< NIVissimEdge * > myToTreatAsSame
std::string myType
The type of the edge.
double myZuschlag1
Additional load values for this edge.
double myZuschlag2
Static Private Attributes
static DictType myDict
The dictionary.
static std::vector< std::string > myLanesWithMissingSpeeds
static int myMaxID = 0
The current maximum id; needed for further id assignment.
Friends
class NIVissimNodeDef_Edges
class NIVissimNodeDef_Poly
Detailed Description
A temporary storage for edges imported from Vissim.
Definition at line 59 of file NIVissimEdge.h.
Member Typedef Documentation
ConnectionClusters
typedef std::vector<NIVissimConnectionCluster*> NIVissimEdge::ConnectionClusters private
The definition for a container for connection clusters.
Definition at line 168 of file NIVissimEdge.h.
DictType
typedef std::map<int, NIVissimEdge*> NIVissimEdge::DictType private
Definition of the dictionary type.
Definition at line 294 of file NIVissimEdge.h.
Constructor & Destructor Documentation
NIVissimEdge()
NIVissimEdge::NIVissimEdge (int id, const std::string & name, const std::string & type, int noLanes, double zuschlag1, double zuschlag2, double length, const PositionVector & geom, const NIVissimClosedLanesVector & clv)
Constructor.
Definition at line 114 of file NIVissimEdge.cpp.
References NIVissimAbstractEdge::myID, myLaneSpeeds, and myMaxID.
Referenced by dictionary().
~NIVissimEdge()
NIVissimEdge::~NIVissimEdge ()
Destructor.
Definition at line 133 of file NIVissimEdge.cpp.
References myClosedLanes.
Member Function Documentation
addDisturbance()
void NIVissimAbstractEdge::addDisturbance (int disturbance) inherited
Definition at line 174 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDisturbances.
addIncomingConnection()
void NIVissimEdge::addIncomingConnection (int id)
Adds a connection where this edge is the destination.
Definition at line 782 of file NIVissimEdge.cpp.
References myIncomingConnections.
addOutgoingConnection()
void NIVissimEdge::addOutgoingConnection (int id)
Adds a connection where this edge is the source.
Definition at line 788 of file NIVissimEdge.cpp.
References myOutgoingConnections.
addToConnectionCluster()
void NIVissimEdge::addToConnectionCluster (NIVissimConnectionCluster * c)
Definition at line 820 of file NIVissimEdge.cpp.
References myConnectionClusters.
Referenced by NIVissimConnectionCluster::recheckEdges().
addToTreatAsSame()
bool NIVissimEdge::addToTreatAsSame (NIVissimEdge * e)
Definition at line 923 of file NIVissimEdge.cpp.
References myToTreatAsSame.
Referenced by dict_checkEdges2Join().
buildConnectionClusters()
void NIVissimEdge::buildConnectionClusters () static
Clusters connections of each edge.
For every edge stored in this container, its connections are collected and joined into "clusters" if they have the same "direction" (incoming/outgoing) and are not further than 10m away from each other.
Todo:
Probably the distance (MAX_CLUSTER_DISTANCE=10m) should be made variable
Definition at line 181 of file NIVissimEdge.cpp.
References NIVissimConnection::dictionary(), myConnectionClusters, myDict, myIncomingConnections, myOutgoingConnections, and VectorHelper< T >::removeDouble().
Referenced by NIImporter_Vissim::postLoadBuild().
buildGeom()
void NIVissimEdge::buildGeom () virtual
Implements NIVissimAbstractEdge.
Definition at line 778 of file NIVissimEdge.cpp.
buildNBEdge()
void NIVissimEdge::buildNBEdge (NBDistrictCont & dc, NBNodeCont & nc, NBEdgeCont & ec, double sameNodesOffset) private
Builds the NBEdge from this VissimEdge.
Parameters
[in] dc The district container used if this edge must be split
[in] nc The node container used for (optionally) building this edge's nodes
[in] ec The edge control to add this edge to
[in] sameNodesOffset Offset used to discriminate nodes
Exceptions
ProcessError If one of the built nodes or edges could not be added to the according container
Definition at line 423 of file NIVissimEdge.cpp.
References OptionsCont::getFloat(), getFromNode(), Named::getID(), OptionsCont::getOptions(), NBNode::getPosition(), getToNode(), NBNodeCont::insert(), NBEdgeCont::insert(), LANESPREAD_CENTER, myAmWithinJunction, myConnectionClusters, myDistrictConnections, NIVissimAbstractEdge::myGeom, NIVissimAbstractEdge::myID, myLaneSpeeds, myLanesWithMissingSpeeds, myName, myNoLanes, myType, NODETYPE_NOJUNCTION, resolveSameNode(), NBEdgeCont::retrieve(), NBEdge::setSpeed(), NBEdgeCont::splitAt(), toString(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, and WRITE_WARNING.
Referenced by dict_buildNBEdges().
checkDistrictConnectionExistanceAt()
void NIVissimEdge::checkDistrictConnectionExistanceAt (double pos)
Definition at line 848 of file NIVissimEdge.cpp.
References myDistrictConnections.
Referenced by NIVissimDistrictConnection::checkEdgeEnd().
checkUnconnectedLaneSpeeds()
void NIVissimEdge::checkUnconnectedLaneSpeeds () private
Definition at line 278 of file NIVissimEdge.cpp.
References dictionary(), getOutgoingConnected(), NIVissimConnection::getToEdgeID(), NIVissimConnection::getToLanes(), myLaneSpeeds, and propagateSpeed().
Referenced by dict_propagateSpeeds().
clearDict()
void NIVissimAbstractEdge::clearDict () static inherited
Definition at line 159 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
crossesEdge()
bool NIVissimAbstractEdge::crossesEdge (NIVissimAbstractEdge * c) const inherited
Definition at line 117 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersects(), and NIVissimAbstractEdge::myGeom.
Referenced by NIVissimNodeCluster::buildNBNode().
crossesEdgeAtPoint()
Position NIVissimAbstractEdge::crossesEdgeAtPoint (NIVissimAbstractEdge * c) const inherited
Definition at line 123 of file NIVissimAbstractEdge.cpp.
References PositionVector::intersectionPosition2D(), and NIVissimAbstractEdge::myGeom.
Referenced by NIVissimDisturbance::addToNode(), and NIVissimNodeCluster::buildNBNode().
dict_buildNBEdges()
void NIVissimEdge::dict_buildNBEdges (NBDistrictCont & dc, NBNodeCont & nc, NBEdgeCont & ec, double offset) static
Builds NBEdges from the VissimEdges within the dictionary.
Definition at line 244 of file NIVissimEdge.cpp.
References buildNBEdge(), and myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
dict_checkEdges2Join()
void NIVissimEdge::dict_checkEdges2Join () static
Definition at line 870 of file NIVissimEdge.cpp.
References addToTreatAsSame(), GeomHelper::angleDiff(), PositionVector::beginEndAngle(), DEG2RAD, getConnectionTo(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getFromPosition(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getID(), PositionVector::length(), and myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
dict_propagateSpeeds()
void NIVissimEdge::dict_propagateSpeeds () static
Definition at line 254 of file NIVissimEdge.cpp.
References checkUnconnectedLaneSpeeds(), myDict, propagateOwn(), propagateSpeed(), and setDistrictSpeed().
Referenced by NIImporter_Vissim::postLoadBuild().
dictionary() [1/4]
bool NIVissimAbstractEdge::dictionary (int id, NIVissimAbstractEdge * e) static inherited
Definition at line 65 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict.
Referenced by NIVissimNodeCluster::buildNBNode(), NIVissimDisturbance::computeBounding(), NIVissimDisturbance::dict_SetDisturbances(), NIVissimExtendedEdgePoint::getGeomPosition(), NIVissimTL::NIVissimTLSignal::getPosition(), and NIVissimAbstractEdge::NIVissimAbstractEdge().
dictionary() [2/4]
bool NIVissimEdge::dictionary (int id, const std::string & name, const std::string & type, int noLanes, double zuschlag1, double zuschlag2, double length, const PositionVector & geom, const NIVissimClosedLanesVector & clv) static
Adds the described item to the dictionary Builds the edge first.
Definition at line 142 of file NIVissimEdge.cpp.
References NIVissimEdge().
Referenced by NIVissimConnectionCluster::add(), NIVissimDisturbance::addToNode(), NIVissimConnection::buildEdgeConnections(), NIVissimDistrictConnection::checkEdgeEnd(), checkUnconnectedLaneSpeeds(), NIVissimConnection::dict_assignToEdges(), NIVissimConnectionCluster::extendByToTreatAsSame(), NIVissimDistrictConnection::geomPosition(), getBestIncoming(), getBestOutgoing(), NIVissimDisturbance::getConnection(), getOutgoingConnected(), NIVissimConnectionCluster::getPositionForEdge(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition::myEndElement(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), propagateOwn(), propagateSpeed(), NIVissimConnectionCluster::recheckEdges(), and setDistrictSpeed().
dictionary() [3/4]
bool NIVissimEdge::dictionary (int id, NIVissimEdge * o) static
Adds the edge to the dictionary.
Definition at line 159 of file NIVissimEdge.cpp.
References myDict.
dictionary() [4/4]
NIVissimEdge * NIVissimEdge::dictionary (int id) static
Returns the named edge from the dictionary.
Definition at line 171 of file NIVissimEdge.cpp.
References myDict.
getBegin2D()
Position NIVissimEdge::getBegin2D () const
Returns the begin position of the edge
Definition at line 830 of file NIVissimEdge.cpp.
References NIVissimAbstractEdge::myGeom.
getBestIncoming()
NIVissimEdge * NIVissimEdge::getBestIncoming () const
Definition at line 994 of file NIVissimEdge.cpp.
References NIVissimConnection::dictionary(), dictionary(), and myIncomingConnections.
Referenced by NIVissimConnection::buildEdgeConnections(), and wasWithinAJunction().
getBestOutgoing()
NIVissimEdge * NIVissimEdge::getBestOutgoing () const
Definition at line 1011 of file NIVissimEdge.cpp.
References NIVissimConnection::dictionary(), dictionary(), and myOutgoingConnections.
Referenced by NIVissimConnection::buildEdgeConnections(), and wasWithinAJunction().
getConnectionTo()
NIVissimConnection * NIVissimEdge::getConnectionTo (NIVissimEdge * e)
Definition at line 952 of file NIVissimEdge.cpp.
References NIVissimConnection::dictionary(), NIVissimConnection::getFromEdgeID(), NIVissimAbstractEdge::getID(), NIVissimConnection::getToEdgeID(), myIncomingConnections, and myOutgoingConnections.
Referenced by dict_checkEdges2Join().
getDisturbances()
const std::vector< int > & NIVissimAbstractEdge::getDisturbances () const inherited
Definition at line 180 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDisturbances.
Referenced by NIVissimConnectionCluster::getDisturbanceParticipators().
getEnd2D()
Position NIVissimEdge::getEnd2D () const
Returns the end position of the edge.
Definition at line 836 of file NIVissimEdge.cpp.
References NIVissimAbstractEdge::myGeom.
getFromNode()
std::pair< NIVissimConnectionCluster *, NBNode * > NIVissimEdge::getFromNode (NBNodeCont & nc, ConnectionClusters & clusters) private
Returns the origin node.
Definition at line 580 of file NIVissimEdge.cpp.
References NIVissimConnectionCluster::around(), NIVissimConnectionCluster::getNBNode(), NBNodeCont::insert(), myDistrictConnections, NIVissimAbstractEdge::myGeom, NIVissimAbstractEdge::myID, and NODETYPE_NOJUNCTION.
Referenced by buildNBEdge().
getGeometry()
const PositionVector & NIVissimAbstractEdge::getGeometry () const inherited
Definition at line 168 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myGeom.
Referenced by dict_checkEdges2Join(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::same_direction_sorter::operator()(), and NIVissimConnectionCluster::recomputeBoundary().
getGeomPosition()
Position NIVissimAbstractEdge::getGeomPosition (double pos) const inherited
Definition at line 87 of file NIVissimAbstractEdge.cpp.
References PositionVector::extrapolate(), PositionVector::length(), NIVissimAbstractEdge::myGeom, and PositionVector::positionAtOffset().
Referenced by NIVissimDistrictConnection::geomPosition().
getID()
int NIVissimAbstractEdge::getID () const inherited
Definition at line 154 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myID.
Referenced by NIVissimDisturbance::addToNode(), NIVissimConnection::buildEdgeConnections(), dict_checkEdges2Join(), getConnectionTo(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), and NIVissimConnectionCluster::removeConnections().
getLength()
double NIVissimEdge::getLength () const
Returns the length of the node.
Definition at line 842 of file NIVissimEdge.cpp.
References PositionVector::length(), and NIVissimAbstractEdge::myGeom.
Referenced by setDistrictSpeed().
getNodeAt()
NBNode* NIVissimEdge::getNodeAt (const Position & p, NBNode * other = 0)
Returns the node at the given position As this may be ambigous, a second node not to return may be supplied.
getNodeSecure()
static NBNode* NIVissimEdge::getNodeSecure (int nodeid, const Position & pos, const std::string & possibleName) static private
getOutgoingConnected()
std::vector< NIVissimConnection * > NIVissimEdge::getOutgoingConnected (int lane) const private
Definition at line 406 of file NIVissimEdge.cpp.
References NIVissimConnection::dictionary(), dictionary(), NIVissimConnection::getFromLanes(), NIVissimConnection::getToEdgeID(), and myOutgoingConnections.
Referenced by checkUnconnectedLaneSpeeds(), propagateOwn(), propagateSpeed(), and setDistrictSpeed().
getRealSpeed()
double NIVissimEdge::getRealSpeed (int distNo) private
Definition at line 526 of file NIVissimEdge.cpp.
References DistributionCont::dictionary(), and WRITE_WARNING.
Referenced by propagateSpeed().
getToNode()
std::pair< NIVissimConnectionCluster *, NBNode * > NIVissimEdge::getToNode (NBNodeCont & nc, ConnectionClusters & clusters) private
Returns the destination node.
Definition at line 616 of file NIVissimEdge.cpp.
References NBNodeCont::insert(), PositionVector::length(), myDistrictConnections, NIVissimAbstractEdge::myGeom, NIVissimAbstractEdge::myID, and NODETYPE_NOJUNCTION.
Referenced by buildNBEdge().
getToTreatAsSame()
const std::vector< NIVissimEdge * > & NIVissimEdge::getToTreatAsSame () const
Definition at line 971 of file NIVissimEdge.cpp.
References myToTreatAsSame.
Referenced by NIVissimConnectionCluster::extendByToTreatAsSame().
getWithin()
std::vector< int > NIVissimAbstractEdge::getWithin (const AbstractPoly & p, double offset = 0.0) static inherited
Definition at line 129 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict, NIVissimAbstractEdge::myID, and NIVissimAbstractEdge::overlapsWith().
hasNodeCluster()
bool NIVissimAbstractEdge::hasNodeCluster () const inherited
Definition at line 148 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myNode.
mergedInto()
void NIVissimEdge::mergedInto (NIVissimConnectionCluster * old, NIVissimConnectionCluster * act)
Definition at line 795 of file NIVissimEdge.cpp.
References myConnectionClusters.
overlapsWith()
bool NIVissimAbstractEdge::overlapsWith (const AbstractPoly & p, double offset = 0.0) const inherited
Definition at line 142 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myGeom, and PositionVector::overlapsWith().
Referenced by NIVissimAbstractEdge::getWithin().
propagateOwn()
void NIVissimEdge::propagateOwn () private
Definition at line 315 of file NIVissimEdge.cpp.
References dictionary(), getOutgoingConnected(), NIVissimConnection::getToEdgeID(), NIVissimConnection::getToLanes(), myLaneSpeeds, and propagateSpeed().
Referenced by dict_propagateSpeeds().
propagateSpeed()
void NIVissimEdge::propagateSpeed (double speed, std::vector< int > forLanes) private
Definition at line 332 of file NIVissimEdge.cpp.
References dictionary(), getOutgoingConnected(), getRealSpeed(), NIVissimConnection::getToEdgeID(), NIVissimConnection::getToLanes(), myLaneSpeeds, myNoLanes, myPatchedSpeeds, and propagateSpeed().
Referenced by checkUnconnectedLaneSpeeds(), dict_propagateSpeeds(), propagateOwn(), propagateSpeed(), and setDistrictSpeed().
remapOneOfNodes()
std::pair< NBNode *, NBNode * > NIVissimEdge::remapOneOfNodes (NBNodeCont & nc, NIVissimDistrictConnection * d, NBNode * fromNode, NBNode * toNode) private
Definition at line 663 of file NIVissimEdge.cpp.
References Position::distanceTo(), NBNodeCont::erase(), NIVissimDistrictConnection::geomPosition(), NIVissimDistrictConnection::getID(), NBNode::getPosition(), NBNodeCont::insert(), and NODETYPE_NOJUNCTION.
removeFromConnectionCluster()
void NIVissimEdge::removeFromConnectionCluster (NIVissimConnectionCluster * c)
Definition at line 811 of file NIVissimEdge.cpp.
References myConnectionClusters.
Referenced by NIVissimConnectionCluster::recheckEdges().
reportUnsetSpeeds()
void NIVissimEdge::reportUnsetSpeeds () static
Writes edges with unset speeds to the warnings message log instance.
Vissim has no direct speed definition of edges; still, we try to propagate speed changes along the streets. If a lane is not covered by such, its id is put into the static container "myLanesWithMissingSpeeds". If the option "vissim.report-unset-speeds" is set, all lane ids stored within this container are written.
Definition at line 977 of file NIVissimEdge.cpp.
References myLanesWithMissingSpeeds, and WRITE_WARNING.
Referenced by NIImporter_Vissim::postLoadBuild().
resolveSameNode()
std::pair< NBNode *, NBNode * > NIVissimEdge::resolveSameNode (NBNodeCont & nc, double offset, NBNode * prevFrom, NBNode * prevTo) private
Tries to resolve the problem that the same node has been returned as origin and destination node.
Definition at line 690 of file NIVissimEdge.cpp.
References NIVissimConnectionCluster::around(), NIVissimDistrictConnection::dict_findForEdge(), NIVissimDistrictConnection::geomPosition(), NIVissimDistrictConnection::getID(), NIVissimDistrictConnection::getPosition(), NBNodeCont::insert(), PositionVector::length(), myConnectionClusters, NIVissimAbstractEdge::myGeom, NIVissimAbstractEdge::myID, NODETYPE_NOJUNCTION, and NBNodeCont::retrieve().
Referenced by buildNBEdge().
setDistrictSpeed()
void NIVissimEdge::setDistrictSpeed () private
Definition at line 375 of file NIVissimEdge.cpp.
References NIVissimDistrictConnection::dict_findForEdge(), dictionary(), getLength(), NIVissimDistrictConnection::getMeanSpeed(), getOutgoingConnected(), NIVissimConnection::getToEdgeID(), NIVissimConnection::getToLanes(), myDistrictConnections, NIVissimAbstractEdge::myID, myLaneSpeeds, myNoLanes, and propagateSpeed().
Referenced by dict_propagateSpeeds().
setNodeCluster()
void NIVissimEdge::setNodeCluster (int nodeid) virtual
Implements NIVissimAbstractEdge.
Definition at line 772 of file NIVissimEdge.cpp.
References NIVissimAbstractEdge::myNode.
setSpeed()
void NIVissimEdge::setSpeed (int lane, int speedDist)
Definition at line 861 of file NIVissimEdge.cpp.
References myPatchedSpeeds.
splitAndAssignToNodes()
void NIVissimAbstractEdge::splitAndAssignToNodes () static inherited
Definition at line 102 of file NIVissimAbstractEdge.cpp.
References NIVissimAbstractEdge::myDict, and NIVissimAbstractEdge::splitAssigning().
splitAssigning()
void NIVissimAbstractEdge::splitAssigning () inherited
Definition at line 110 of file NIVissimAbstractEdge.cpp.
Referenced by NIVissimAbstractEdge::splitAndAssignToNodes().
wasWithinAJunction()
bool NIVissimEdge::wasWithinAJunction () const inline
Returns whether this edge was found to be within a junction.
Returns
Whether this node is assumed to be within a junction
Definition at line 111 of file NIVissimEdge.h.
References getBestIncoming(), getBestOutgoing(), and myAmWithinJunction.
Referenced by NIVissimConnection::buildEdgeConnections().
Friends And Related Function Documentation
NIVissimNodeDef_Edges
friend class NIVissimNodeDef_Edges friend
Definition at line 118 of file NIVissimEdge.h.
NIVissimNodeDef_Poly
friend class NIVissimNodeDef_Poly friend
Definition at line 119 of file NIVissimEdge.h.
Field Documentation
myAmWithinJunction
bool NIVissimEdge::myAmWithinJunction private
Information whether this edge was not build due to being within a junction.
Definition at line 290 of file NIVissimEdge.h.
Referenced by buildNBEdge(), and wasWithinAJunction().
myClosedLanes
NIVissimClosedLanesVector NIVissimEdge::myClosedLanes private
List of lanes closed on this edge.
Definition at line 270 of file NIVissimEdge.h.
Referenced by ~NIVissimEdge().
myConnectionClusters
ConnectionClusters NIVissimEdge::myConnectionClusters private
List of connection clusters along this edge.
Definition at line 273 of file NIVissimEdge.h.
Referenced by addToConnectionCluster(), buildConnectionClusters(), buildNBEdge(), mergedInto(), removeFromConnectionCluster(), and resolveSameNode().
myDict
NIVissimEdge::DictType NIVissimEdge::myDict static private
The dictionary.
Definition at line 297 of file NIVissimEdge.h.
Referenced by buildConnectionClusters(), dict_buildNBEdges(), dict_checkEdges2Join(), dict_propagateSpeeds(), and dictionary().
myDistrictConnections
std::vector<double> NIVissimEdge::myDistrictConnections private
Definition at line 281 of file NIVissimEdge.h.
Referenced by buildNBEdge(), checkDistrictConnectionExistanceAt(), getFromNode(), getToNode(), and setDistrictSpeed().
myDisturbances
std::vector<int> NIVissimAbstractEdge::myDisturbances protected inherited
Definition at line 74 of file NIVissimAbstractEdge.h.
Referenced by NIVissimAbstractEdge::addDisturbance(), and NIVissimAbstractEdge::getDisturbances().
myGeom
PositionVector NIVissimAbstractEdge::myGeom protected inherited
Definition at line 73 of file NIVissimAbstractEdge.h.
Referenced by NIVissimConnection::buildGeom(), buildNBEdge(), NIVissimAbstractEdge::crossesEdge(), NIVissimAbstractEdge::crossesEdgeAtPoint(), getBegin2D(), getEnd2D(), getFromNode(), NIVissimAbstractEdge::getGeometry(), NIVissimAbstractEdge::getGeomPosition(), getLength(), getToNode(), NIVissimAbstractEdge::NIVissimAbstractEdge(), NIVissimAbstractEdge::overlapsWith(), and resolveSameNode().
myID
int NIVissimAbstractEdge::myID protected inherited
Definition at line 72 of file NIVissimAbstractEdge.h.
Referenced by buildNBEdge(), getFromNode(), NIVissimAbstractEdge::getID(), getToNode(), NIVissimAbstractEdge::getWithin(), NIVissimEdge(), resolveSameNode(), and setDistrictSpeed().
myIncomingConnections
std::vector<int> NIVissimEdge::myIncomingConnections private
List of connections incoming to this edge.
Definition at line 276 of file NIVissimEdge.h.
Referenced by addIncomingConnection(), buildConnectionClusters(), getBestIncoming(), and getConnectionTo().
myLaneSpeeds
std::vector<double> NIVissimEdge::myLaneSpeeds private
Definition at line 285 of file NIVissimEdge.h.
Referenced by buildNBEdge(), checkUnconnectedLaneSpeeds(), NIVissimEdge(), propagateOwn(), propagateSpeed(), and setDistrictSpeed().
myLanesWithMissingSpeeds
std::vector< std::string > NIVissimEdge::myLanesWithMissingSpeeds static private
Definition at line 302 of file NIVissimEdge.h.
Referenced by buildNBEdge(), and reportUnsetSpeeds().
myMaxID
int NIVissimEdge::myMaxID = 0 static private
The current maximum id; needed for further id assignment.
Definition at line 300 of file NIVissimEdge.h.
Referenced by NIVissimEdge().
myName
std::string NIVissimEdge::myName private
The name of the edge.
Definition at line 258 of file NIVissimEdge.h.
Referenced by buildNBEdge().
myNode
int NIVissimAbstractEdge::myNode protected inherited
Definition at line 75 of file NIVissimAbstractEdge.h.
Referenced by NIVissimAbstractEdge::hasNodeCluster(), setNodeCluster(), and NIVissimConnection::setNodeCluster().
myNoLanes
int NIVissimEdge::myNoLanes private
The number of lanes the edge has.
Definition at line 264 of file NIVissimEdge.h.
Referenced by buildNBEdge(), propagateSpeed(), and setDistrictSpeed().
myOutgoingConnections
std::vector<int> NIVissimEdge::myOutgoingConnections private
List of connections outgoing from this edge.
Definition at line 279 of file NIVissimEdge.h.
Referenced by addOutgoingConnection(), buildConnectionClusters(), getBestOutgoing(), getConnectionTo(), and getOutgoingConnected().
myPatchedSpeeds
std::vector<int> NIVissimEdge::myPatchedSpeeds private
Definition at line 283 of file NIVissimEdge.h.
Referenced by propagateSpeed(), and setSpeed().
myToTreatAsSame
std::vector<NIVissimEdge*> NIVissimEdge::myToTreatAsSame private
Definition at line 287 of file NIVissimEdge.h.
Referenced by addToTreatAsSame(), and getToTreatAsSame().
myType
std::string NIVissimEdge::myType private
The type of the edge.
Definition at line 261 of file NIVissimEdge.h.
Referenced by buildNBEdge().
myZuschlag1
double NIVissimEdge::myZuschlag1 private
Additional load values for this edge.
Definition at line 267 of file NIVissimEdge.h.
myZuschlag2
double NIVissimEdge::myZuschlag2 private
Definition at line 267 of file NIVissimEdge.h.
The documentation for this class was generated from the following files:
NIVissimEdge.h
NIVissimEdge.cpp