SUMO - Simulation of Urban MObility: tcpip::Storage Class Reference
tcpip::Storage Class Reference
#include <storage.h>
Public Types
typedef std::vector< unsigned char > StorageType
Public Member Functions
StorageType::const_iterator begin () const
StorageType::const_iterator end () const
std::string hexDump () const
Dump storage content as series of hex values.
virtual unsigned int position () const
virtual int readByte () throw (std::invalid_argument)
virtual unsigned char readChar () throw (std::invalid_argument)
virtual double readDouble () throw (std::invalid_argument)
virtual float readFloat () throw (std::invalid_argument)
virtual int readInt () throw (std::invalid_argument)
virtual int readShort () throw (std::invalid_argument)
virtual std::string readString () throw (std::invalid_argument)
virtual std::vector< std::string > readStringList () throw (std::invalid_argument)
virtual int readUnsignedByte () throw (std::invalid_argument)
void reset ()
StorageType::size_type size () const
Storage ()
Standard Constructor.
Storage (const unsigned char[], int length=-1)
Constructor, that fills the storage with an char array. If length is -1, the whole array is handed over.
virtual bool valid_pos ()
virtual void writeByte (int) throw (std::invalid_argument)
virtual void writeChar (unsigned char) throw ()
virtual void writeDouble (double) throw ()
virtual void writeFloat (float) throw ()
virtual void writeInt (int) throw ()
virtual void writePacket (unsigned char *packet, int length)
virtual void writePacket (const std::vector< unsigned char > &packet)
virtual void writeShort (int) throw (std::invalid_argument)
virtual void writeStorage (tcpip::Storage &store)
virtual void writeString (const std::string &s) throw ()
virtual void writeStringList (const std::vector< std::string > &s) throw ()
virtual void writeUnsignedByte (int) throw (std::invalid_argument)
virtual ~Storage ()
Private Member Functions
void checkReadSafe (unsigned int num) const throw (std::invalid_argument)
Check if the next num bytes can be read safely.
void init ()
Used in constructors to initialize local variables.
void readByEndianess (unsigned char *array, int size)
Read size elements into array according to endianess.
unsigned char readCharUnsafe ()
Read a byte without validity check.
void writeByEndianess (const unsigned char *begin, unsigned int size)
Write size elements of array begin according to endianess.
Private Attributes
bool bigEndian_
StorageType::const_iterator iter_
StorageType store
Detailed Description
Definition at line 37 of file storage.h.
Member Typedef Documentation
StorageType
typedef std::vector<unsigned char> tcpip::Storage::StorageType
Definition at line 41 of file storage.h.
Constructor & Destructor Documentation
Storage() [1/2]
tcpip::Storage::Storage ()
Standard Constructor.
Storage() [2/2]
tcpip::Storage::Storage (const unsigned char[], int length = -1)
Constructor, that fills the storage with an char array. If length is -1, the whole array is handed over.
~Storage()
virtual tcpip::Storage::~Storage () virtual
Member Function Documentation
begin()
StorageType::const_iterator tcpip::Storage::begin () const inline
Definition at line 117 of file storage.h.
Referenced by TraCIServer::cleanup(), and tcpip::Socket::sendExact().
checkReadSafe()
void tcpip::Storage::checkReadSafe (unsigned int num) const throw (std::invalid_argument) private
Check if the next num bytes can be read safely.
end()
StorageType::const_iterator tcpip::Storage::end () const inline
Definition at line 118 of file storage.h.
Referenced by TraCIServer::cleanup(), and tcpip::Socket::sendExact().
hexDump()
std::string tcpip::Storage::hexDump () const
Dump storage content as series of hex values.
init()
void tcpip::Storage::init () private
Used in constructors to initialize local variables.
position()
virtual unsigned int tcpip::Storage::position () const virtual
Referenced by TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), TraCIServer::dispatchCommand(), and TraCIServer::readCommandID().
readByEndianess()
void tcpip::Storage::readByEndianess (unsigned char * array, int size) private
Read size elements into array according to endianess.
readByte()
virtual int tcpip::Storage::readByte () throw (std::invalid_argument) virtual
Referenced by TraCIAPI::VehicleScope::getBestLanes(), TraCIAPI::getByte(), TraCIAPI::VehicleScope::getNextTLS(), TraCIAPI::getPolygon(), TraCIServer::initialiseSubscription(), TraCITestClient::readAndReportTypeDependent(), and TraCIServer::readTypeCheckingByte().
readChar()
virtual unsigned char tcpip::Storage::readChar () throw (std::invalid_argument) virtual
Referenced by TraCIServer::addObjectVariableSubscription(), and TraCIServer::dispatchCommand().
readCharUnsafe()
unsigned char tcpip::Storage::readCharUnsafe () private
Read a byte without validity check.
readDouble()
virtual double tcpip::Storage::readDouble () throw (std::invalid_argument) virtual
Referenced by TraCIServer::addObjectVariableSubscription(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), TraCIAPI::VehicleScope::getBestLanes(), TraCIAPI::getBoundingBox(), TraCIAPI::getDouble(), TraCIAPI::VehicleScope::getLeader(), TraCIAPI::LaneScope::getLinks(), TraCIAPI::VehicleScope::getNextTLS(), TraCIAPI::getPolygon(), TraCIAPI::getPosition(), TraCIAPI::getPosition3D(), TraCIAPI::InductionLoopScope::getVehicleData(), TraCIServerAPI_Vehicle::processGet(), TraCITestClient::readAndReportTypeDependent(), TraCIServer::readTypeCheckingBoundary(), TraCIServer::readTypeCheckingDouble(), TraCIServer::readTypeCheckingPolygon(), TraCIServer::readTypeCheckingPosition2D(), and TraCIAPI::readVariables().
readFloat()
virtual float tcpip::Storage::readFloat () throw (std::invalid_argument) virtual
Referenced by TraCIAPI::getFloat(), and TraCITestClient::readAndReportTypeDependent().
readInt()
virtual int tcpip::Storage::readInt () throw (std::invalid_argument) virtual
Referenced by TraCIServer::addObjectVariableSubscription(), TraCIAPI::check_commandGetResult(), TraCIServer::dispatchCommand(), TraCIAPI::VehicleScope::getBestLanes(), TraCIAPI::TrafficLightScope::getCompleteRedYellowGreenDefinition(), TraCIAPI::TrafficLightScope::getControlledLinks(), TraCIAPI::LaneScope::getFoes(), TraCIAPI::getInt(), TraCIAPI::VehicleScope::getLeader(), TraCIAPI::LaneScope::getLinks(), TraCIAPI::VehicleScope::getNextTLS(), TraCIAPI::getStringVector(), TraCIAPI::getSUMOTime(), TraCIAPI::InductionLoopScope::getVehicleData(), TraCIServer::initialiseSubscription(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServer::processSingleSubscription(), TraCITestClient::readAndReportTypeDependent(), TraCIServer::readCommandID(), TraCIAPI::readContextSubscription(), TraCIServer::readTypeCheckingInt(), TraCIAPI::readVariables(), tcpip::Socket::receiveExact(), TraCIServerAPI_VehicleType::setVariable(), TraCIAPI::simulationStep(), TraCITestClient::validateSimulationStep2(), and TraCITestClient::validateSubscription().
readShort()
virtual int tcpip::Storage::readShort () throw (std::invalid_argument) virtual
readString()
virtual std::string tcpip::Storage::readString () throw (std::invalid_argument) virtual
Referenced by TraCIServer::addObjectVariableSubscription(), TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCITestClient::commandGetVariable(), TraCIServerAPI_Simulation::commandPositionConversion(), TraCIAPI::VehicleScope::getBestLanes(), TraCIAPI::TrafficLightScope::getCompleteRedYellowGreenDefinition(), TraCIAPI::TrafficLightScope::getControlledLinks(), TraCIAPI::LaneScope::getFoes(), TraCIAPI::VehicleScope::getLeader(), TraCIAPI::LaneScope::getLinks(), TraCIAPI::VehicleScope::getNextTLS(), TraCIAPI::getString(), TraCIAPI::getStringVector(), TraCIAPI::InductionLoopScope::getVehicleData(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServerAPI_VehicleType::processSet(), TraCIServer::processSingleSubscription(), TraCITestClient::readAndReportTypeDependent(), TraCIAPI::readContextSubscription(), TraCIServer::readTypeCheckingString(), TraCIAPI::readVariables(), TraCIAPI::readVariableSubscription(), and TraCITestClient::validateSubscription().
readStringList()
virtual std::vector<std::string> tcpip::Storage::readStringList () throw (std::invalid_argument) virtual
Referenced by TraCITestClient::readAndReportTypeDependent(), and TraCIServer::readTypeCheckingStringList().
readUnsignedByte()
virtual int tcpip::Storage::readUnsignedByte () throw (std::invalid_argument) virtual
Referenced by TraCIServer::addObjectVariableSubscription(), TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCITestClient::commandGetVariable(), TraCIServerAPI_Simulation::commandPositionConversion(), TraCIAPI::VehicleScope::getBestLanes(), TraCIAPI::getColor(), TraCIAPI::TrafficLightScope::getCompleteRedYellowGreenDefinition(), TraCIAPI::TrafficLightScope::getControlledLinks(), TraCIAPI::VehicleScope::getLeader(), TraCIAPI::LaneScope::getLinks(), TraCIAPI::VehicleScope::getNextTLS(), TraCIAPI::getUnsignedByte(), TraCIAPI::InductionLoopScope::getVehicleData(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServerAPI_VehicleType::processSet(), TraCIServer::processSingleSubscription(), TraCITestClient::readAndReportTypeDependent(), TraCIServer::readCommandID(), TraCIAPI::readContextSubscription(), TraCIServer::readTypeCheckingBoundary(), TraCIServer::readTypeCheckingByte(), TraCIServer::readTypeCheckingColor(), TraCIServer::readTypeCheckingDouble(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingPolygon(), TraCIServer::readTypeCheckingPosition2D(), TraCIServer::readTypeCheckingString(), TraCIServer::readTypeCheckingStringList(), TraCIServer::readTypeCheckingUnsignedByte(), TraCIAPI::readVariables(), TraCIAPI::readVariableSubscription(), TraCIServerAPI_VehicleType::setVariable(), and TraCITestClient::validateSubscription().
reset()
void tcpip::Storage::reset ()
Referenced by TraCIServer::checkClientOrdering(), TraCIServer::cleanup(), TraCIServer::dispatchCommand(), TraCIServer::initialiseSubscription(), TraCIServer::postProcessSimulationStep(), TraCIServer::processCommandsUntilSimStep(), and TraCIServer::sendSingleSimStepResponse().
size()
StorageType::size_type tcpip::Storage::size () const inline
Definition at line 115 of file storage.h.
Referenced by TraCIServer::commandGetVersion(), TraCIServer::initialiseSubscription(), TraCIServer::postProcessSimulationStep(), TraCIServer::processCommandsUntilSimStep(), TraCIServer::processSingleSubscription(), TraCIAPI::send_commandGetVariable(), TraCIAPI::send_commandSetValue(), TraCIAPI::send_commandSubscribeObjectContext(), TraCIAPI::send_commandSubscribeObjectVariable(), TraCIServer::sendSingleSimStepResponse(), and TraCIServer::writeResponseWithLength().
valid_pos()
virtual bool tcpip::Storage::valid_pos () virtual
Referenced by TraCIServer::dispatchCommand(), TraCIServer::initialiseSubscription(), and TraCIServer::processCommandsUntilSimStep().
writeByEndianess()
void tcpip::Storage::writeByEndianess (const unsigned char * begin, unsigned int size) private
Write size elements of array begin according to endianess.
writeByte()
virtual void tcpip::Storage::writeByte (int) throw (std::invalid_argument) virtual
Referenced by TraCIAPI::EdgeScope::adaptTraveltime(), TraCIAPI::EdgeScope::getAdaptedTraveltime(), TraCIAPI::PersonScope::getEdges(), TraCIAPI::EdgeScope::getEffort(), TraCIAPI::VehicleScope::getLeader(), TraCIAPI::PersonScope::getStage(), TraCIServer::initialiseSubscription(), TraCIServerAPI_Vehicle::processGet(), TraCIAPI::PersonScope::removeStage(), TraCIAPI::send_commandMoveToXY(), TraCIAPI::EdgeScope::setEffort(), and TraCITestClient::setValueTypeDependant().
writeChar()
virtual void tcpip::Storage::writeChar (unsigned char) throw () virtual
Referenced by TraCIServer::cleanup().
writeDouble()
virtual void tcpip::Storage::writeDouble (double) throw () virtual
Referenced by TraCIAPI::EdgeScope::adaptTraveltime(), TraCIAPI::POIScope::add(), TraCIAPI::PolygonScope::add(), TraCIAPI::PersonScope::add(), TraCIAPI::PersonScope::appendWalkingStage(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), TraCIAPI::VehicleScope::getLeader(), TraCIServerAPI_VehicleType::getVariable(), TraCIAPI::VehicleScope::moveTo(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIAPI::send_commandMoveToXY(), TraCIAPI::send_commandSubscribeObjectContext(), TraCIAPI::VehicleTypeScope::setAccel(), TraCIAPI::VehicleTypeScope::setApparentDecel(), TraCIAPI::GUIScope::setBoundary(), TraCIAPI::VehicleTypeScope::setDecel(), TraCIAPI::EdgeScope::setEffort(), TraCIAPI::VehicleTypeScope::setEmergencyDecel(), TraCIAPI::VehicleTypeScope::setHeight(), TraCIAPI::PersonScope::setHeight(), TraCIAPI::VehicleTypeScope::setImperfection(), TraCIAPI::LaneScope::setLength(), TraCIAPI::VehicleTypeScope::setLength(), TraCIAPI::PersonScope::setLength(), TraCIAPI::EdgeScope::setMaxSpeed(), TraCIAPI::LaneScope::setMaxSpeed(), TraCIAPI::VehicleTypeScope::setMaxSpeed(), TraCIAPI::VehicleScope::setMaxSpeed(), TraCIAPI::VehicleTypeScope::setMaxSpeedLat(), TraCIAPI::VehicleTypeScope::setMinGap(), TraCIAPI::PersonScope::setMinGap(), TraCIAPI::VehicleTypeScope::setMinGapLat(), TraCIAPI::GUIScope::setOffset(), TraCIAPI::POIScope::setPosition(), TraCIAPI::PolygonScope::setShape(), TraCIAPI::VehicleScope::setSpeed(), TraCIAPI::PersonScope::setSpeed(), TraCIAPI::VehicleTypeScope::setSpeedDeviation(), TraCIAPI::VehicleTypeScope::setSpeedFactor(), TraCIAPI::VehicleTypeScope::setTau(), TraCITestClient::setValueTypeDependant(), TraCIAPI::VehicleTypeScope::setWidth(), TraCIAPI::PersonScope::setWidth(), TraCIAPI::GUIScope::setZoom(), TraCIAPI::VehicleScope::slowDown(), and TraCIServerAPI_Simulation::writeStage().
writeFloat()
virtual void tcpip::Storage::writeFloat (float) throw () virtual
Referenced by TraCITestClient::setValueTypeDependant().
writeInt()
virtual void tcpip::Storage::writeInt (int) throw () virtual
Referenced by TraCIAPI::EdgeScope::adaptTraveltime(), TraCIAPI::POIScope::add(), TraCIAPI::PolygonScope::add(), TraCIAPI::VehicleScope::add(), TraCIAPI::PersonScope::add(), TraCIAPI::PersonScope::appendDrivingStage(), TraCIAPI::PersonScope::appendWaitingStage(), TraCIAPI::PersonScope::appendWalkingStage(), TraCIServer::commandGetVersion(), TraCIAPI::EdgeScope::getAdaptedTraveltime(), TraCIAPI::PersonScope::getEdges(), TraCIAPI::EdgeScope::getEffort(), TraCIAPI::PersonScope::getStage(), TraCIServer::initialiseSubscription(), TraCIAPI::load(), TraCIAPI::VehicleScope::moveTo(), TraCIServer::postProcessSimulationStep(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServer::processSingleSubscription(), TraCIAPI::POIScope::remove(), TraCIAPI::PolygonScope::remove(), TraCIAPI::PersonScope::removeStage(), TraCIAPI::VehicleScope::rerouteTraveltime(), TraCIAPI::PersonScope::rerouteTraveltime(), TraCIAPI::send_commandMoveToXY(), TraCIAPI::send_commandSetOrder(), TraCIAPI::send_commandSimulationStep(), TraCIAPI::send_commandSubscribeObjectContext(), TraCIAPI::send_commandSubscribeObjectVariable(), tcpip::Socket::sendExact(), TraCIAPI::LaneScope::setAllowed(), TraCIAPI::TrafficLightScope::setCompleteRedYellowGreenDefinition(), TraCIAPI::LaneScope::setDisallowed(), TraCIAPI::EdgeScope::setEffort(), TraCIAPI::setOrder(), TraCIAPI::TrafficLightScope::setPhase(), TraCIAPI::TrafficLightScope::setPhaseDuration(), TraCIAPI::VehicleScope::setRoute(), TraCIAPI::PolygonScope::setShape(), TraCITestClient::setValueTypeDependant(), TraCIAPI::VehicleScope::setVia(), TraCIAPI::VehicleScope::slowDown(), TraCIServer::writeResponseWithLength(), TraCIServerAPI_Simulation::writeStage(), and TraCIServerAPI_Simulation::writeVehicleStateNumber().
writePacket() [1/2]
virtual void tcpip::Storage::writePacket (unsigned char * packet, int length) virtual
Referenced by TraCIServer::processSingleSubscription().
writePacket() [2/2]
virtual void tcpip::Storage::writePacket (const std::vector< unsigned char > & packet) virtual
writeShort()
virtual void tcpip::Storage::writeShort (int) throw (std::invalid_argument) virtual
writeStorage()
virtual void tcpip::Storage::writeStorage (tcpip::Storage & store) virtual
Referenced by TraCIServer::checkClientOrdering(), TraCIServer::commandGetVersion(), TraCIServer::initialiseSubscription(), TraCIServer::postProcessSimulationStep(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServer::processSingleSubscription(), TraCIAPI::send_commandGetVariable(), TraCIAPI::send_commandSetValue(), TraCIServer::sendSingleSimStepResponse(), and TraCIServer::writeResponseWithLength().
writeString()
virtual void tcpip::Storage::writeString (const std::string & s) throw () virtual
Referenced by TraCIAPI::POIScope::add(), TraCIAPI::PolygonScope::add(), TraCIAPI::VehicleScope::add(), TraCIAPI::PersonScope::add(), TraCIAPI::PersonScope::appendDrivingStage(), TraCIAPI::PersonScope::appendWaitingStage(), TraCIAPI::PersonScope::appendWalkingStage(), TraCIAPI::VehicleScope::changeTarget(), TraCIServer::commandGetVersion(), TraCIServerAPI_Simulation::commandPositionConversion(), TraCIAPI::VehicleTypeScope::copy(), TraCIAPI::LaneScope::getFoes(), TraCIServerAPI_VehicleType::getVariable(), TraCIAPI::VehicleScope::moveTo(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServer::processSingleSubscription(), TraCIAPI::GUIScope::screenshot(), TraCIAPI::send_commandGetVariable(), TraCIAPI::send_commandMoveToXY(), TraCIAPI::send_commandSetValue(), TraCIAPI::send_commandSubscribeObjectContext(), TraCIAPI::send_commandSubscribeObjectVariable(), TraCIAPI::LaneScope::setAllowed(), TraCIAPI::TrafficLightScope::setCompleteRedYellowGreenDefinition(), TraCIAPI::LaneScope::setDisallowed(), TraCIAPI::VehicleTypeScope::setEmissionClass(), TraCIAPI::VehicleScope::setEmissionClass(), TraCIAPI::VehicleTypeScope::setLateralAlignment(), TraCIAPI::VehicleScope::setLine(), TraCIAPI::TrafficLightScope::setProgram(), TraCIAPI::TrafficLightScope::setRedYellowGreenState(), TraCIAPI::VehicleScope::setRoute(), TraCIAPI::VehicleScope::setRouteID(), TraCIAPI::GUIScope::setSchema(), TraCIAPI::VehicleTypeScope::setShapeClass(), TraCIAPI::VehicleScope::setShapeClass(), TraCIAPI::POIScope::setType(), TraCIAPI::PolygonScope::setType(), TraCIAPI::VehicleScope::setType(), TraCIAPI::PersonScope::setType(), TraCITestClient::setValueTypeDependant(), TraCIAPI::VehicleTypeScope::setVehicleClass(), TraCIAPI::VehicleScope::setVia(), TraCIAPI::GUIScope::trackVehicle(), TraCIServerAPI_Simulation::writeStage(), and TraCIServer::writeStatusCmd().
writeStringList()
virtual void tcpip::Storage::writeStringList (const std::vector< std::string > & s) throw () virtual
Referenced by TraCIAPI::RouteScope::add(), TraCIAPI::PersonScope::appendWalkingStage(), TraCIAPI::load(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCITestClient::setValueTypeDependant(), TraCIServerAPI_Simulation::writeStage(), and TraCIServerAPI_Simulation::writeVehicleStateIDs().
writeUnsignedByte()
virtual void tcpip::Storage::writeUnsignedByte (int) throw (std::invalid_argument) virtual
Referenced by TraCIAPI::POIScope::add(), TraCIAPI::PolygonScope::add(), TraCIAPI::RouteScope::add(), TraCIAPI::VehicleScope::add(), TraCIAPI::PersonScope::add(), TraCIAPI::PersonScope::appendDrivingStage(), TraCIAPI::PersonScope::appendWaitingStage(), TraCIAPI::PersonScope::appendWalkingStage(), TraCIAPI::VehicleScope::changeTarget(), TraCIServer::checkClientOrdering(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServer::commandGetVersion(), TraCIServerAPI_Simulation::commandPositionConversion(), TraCIAPI::VehicleTypeScope::copy(), TraCIAPI::LaneScope::getFoes(), TraCIServerAPI_VehicleType::getVariable(), TraCIAPI::load(), TraCIAPI::VehicleScope::moveTo(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServer::processSingleSubscription(), TraCIAPI::POIScope::remove(), TraCIAPI::PolygonScope::remove(), TraCIAPI::VehicleScope::remove(), TraCIAPI::VehicleScope::rerouteTraveltime(), TraCIAPI::PersonScope::rerouteTraveltime(), TraCIAPI::GUIScope::screenshot(), TraCIAPI::send_commandClose(), TraCIAPI::send_commandGetVariable(), TraCIAPI::send_commandMoveToXY(), TraCIAPI::send_commandSetOrder(), TraCIAPI::send_commandSetValue(), TraCIAPI::send_commandSimulationStep(), TraCIAPI::send_commandSubscribeObjectContext(), TraCIAPI::send_commandSubscribeObjectVariable(), TraCIAPI::VehicleTypeScope::setAccel(), TraCIAPI::LaneScope::setAllowed(), TraCIAPI::VehicleTypeScope::setApparentDecel(), TraCIAPI::GUIScope::setBoundary(), TraCIAPI::POIScope::setColor(), TraCIAPI::PolygonScope::setColor(), TraCIAPI::VehicleTypeScope::setColor(), TraCIAPI::VehicleScope::setColor(), TraCIAPI::PersonScope::setColor(), TraCIAPI::TrafficLightScope::setCompleteRedYellowGreenDefinition(), TraCIAPI::VehicleTypeScope::setDecel(), TraCIAPI::LaneScope::setDisallowed(), TraCIAPI::VehicleTypeScope::setEmergencyDecel(), TraCIAPI::VehicleTypeScope::setEmissionClass(), TraCIAPI::VehicleScope::setEmissionClass(), TraCIAPI::VehicleTypeScope::setHeight(), TraCIAPI::PersonScope::setHeight(), TraCIAPI::VehicleTypeScope::setImperfection(), TraCIAPI::VehicleTypeScope::setLateralAlignment(), TraCIAPI::LaneScope::setLength(), TraCIAPI::VehicleTypeScope::setLength(), TraCIAPI::PersonScope::setLength(), TraCIAPI::VehicleScope::setLine(), TraCIAPI::LaneScope::setMaxSpeed(), TraCIAPI::VehicleTypeScope::setMaxSpeed(), TraCIAPI::VehicleScope::setMaxSpeed(), TraCIAPI::VehicleTypeScope::setMaxSpeedLat(), TraCIAPI::VehicleTypeScope::setMinGap(), TraCIAPI::PersonScope::setMinGap(), TraCIAPI::VehicleTypeScope::setMinGapLat(), TraCIAPI::GUIScope::setOffset(), TraCIAPI::setOrder(), TraCIAPI::TrafficLightScope::setPhase(), TraCIAPI::TrafficLightScope::setPhaseDuration(), TraCIAPI::POIScope::setPosition(), TraCIAPI::TrafficLightScope::setProgram(), TraCIAPI::TrafficLightScope::setRedYellowGreenState(), TraCIAPI::VehicleScope::setRoute(), TraCIAPI::VehicleScope::setRouteID(), TraCIAPI::GUIScope::setSchema(), TraCIAPI::PolygonScope::setShape(), TraCIAPI::VehicleTypeScope::setShapeClass(), TraCIAPI::VehicleScope::setShapeClass(), TraCIAPI::VehicleScope::setSpeed(), TraCIAPI::PersonScope::setSpeed(), TraCIAPI::VehicleTypeScope::setSpeedDeviation(), TraCIAPI::VehicleTypeScope::setSpeedFactor(), TraCIAPI::VehicleTypeScope::setTau(), TraCIAPI::POIScope::setType(), TraCIAPI::PolygonScope::setType(), TraCIAPI::VehicleScope::setType(), TraCIAPI::PersonScope::setType(), TraCITestClient::setValueTypeDependant(), TraCIAPI::VehicleTypeScope::setVehicleClass(), TraCIAPI::VehicleScope::setVia(), TraCIAPI::VehicleTypeScope::setWidth(), TraCIAPI::PersonScope::setWidth(), TraCIAPI::VehicleScope::slowDown(), TraCIAPI::GUIScope::trackVehicle(), TraCIServer::writeResponseWithLength(), TraCIServerAPI_Simulation::writeStage(), TraCIServer::writeStatusCmd(), TraCIServerAPI_Simulation::writeVehicleStateIDs(), and TraCIServerAPI_Simulation::writeVehicleStateNumber().
Field Documentation
bigEndian_
bool tcpip::Storage::bigEndian_ private
Definition at line 48 of file storage.h.
iter_
StorageType::const_iterator tcpip::Storage::iter_ private
Definition at line 45 of file storage.h.
store
StorageType tcpip::Storage::store private
Definition at line 44 of file storage.h.
The documentation for this class was generated from the following file:
storage.h