SUMO - Simulation of Urban MObility: FXWorkerThread::Pool Class Reference
FXWorkerThread::Pool Class Reference
A pool of worker threads which distributes the tasks and collects the results.
#include <FXWorkerThread.h>
Public Member Functions
void add (Task *const t, int index=-1)
Gives a number to the given task and assigns it to the worker with the given index. If the index is negative, assign to the next (round robin) one.
void addFinished (Task *const t)
Adds the given task to the list of finished tasks and assigns it to a randomly chosen worker.
void addWorker (FXWorkerThread *const w)
Adds the given thread to the pool.
void clear ()
Stops and deletes all worker threads.
bool isFull () const
Checks whether there are currently more pending tasks than threads.
void lock ()
locks the pool mutex
Pool (int numThreads=0)
Constructor.
int size () const
Returns the number of threads in the pool.
void unlock ()
unlocks the pool mutex
void waitAll (const bool deleteFinished=true)
waits for all tasks to be finished
virtual ~Pool ()
Destructor.
Private Attributes
FXCondition myCondition
the semaphore to wait on for finishing all tasks
std::list< Task * > myFinishedTasks
list of finished tasks
FXMutex myMutex
the internal mutex for the task list
int myNumFinished
the number of finished tasks (is reset when the pool runs empty)
FXMutex myPoolMutex
the pool mutex for external sync
int myRunningIndex
the running index for the next task
std::vector< FXWorkerThread * > myWorkers
the current worker threads
Detailed Description
A pool of worker threads which distributes the tasks and collects the results.
Definition at line 86 of file FXWorkerThread.h.
Constructor & Destructor Documentation
Pool()
FXWorkerThread::Pool::Pool (int numThreads = 0) inline
Constructor.
May initialize the pool with a given number of workers.
Parameters
[in] numThreads the number of threads to create
Definition at line 94 of file FXWorkerThread.h.
References FXWorkerThread::FXWorkerThread().
~Pool()
virtual FXWorkerThread::Pool::~Pool () inline virtual
Destructor.
Stopping and deleting all workers by calling clear.
Definition at line 105 of file FXWorkerThread.h.
Member Function Documentation
add()
void FXWorkerThread::Pool::add (Task *const t, int index = -1) inline
Gives a number to the given task and assigns it to the worker with the given index. If the index is negative, assign to the next (round robin) one.
Parameters
[in] t the task to add
[in] index index of the worker thread to use or -1 for an arbitrary one
Definition at line 133 of file FXWorkerThread.h.
References FXWorkerThread::Task::setIndex().
Referenced by LandmarkLookupTable< E, V >::LandmarkLookupTable().
addFinished()
void FXWorkerThread::Pool::addFinished (Task *const t) inline
Adds the given task to the list of finished tasks and assigns it to a randomly chosen worker.
Locks the internal mutex and counts the finished tasks. This is to be called by the worker thread only.
Parameters
[in] t the task to add
Definition at line 147 of file FXWorkerThread.h.
References FXWorkerThread::myCondition, and FXWorkerThread::myMutex.
Referenced by FXWorkerThread::run().
addWorker()
void FXWorkerThread::Pool::addWorker (FXWorkerThread *const w) inline
Adds the given thread to the pool.
Parameters
[in] w the thread to add
Definition at line 122 of file FXWorkerThread.h.
Referenced by FXWorkerThread::FXWorkerThread().
clear()
void FXWorkerThread::Pool::clear () inline
Stops and deletes all worker threads.
Definition at line 111 of file FXWorkerThread.h.
isFull()
bool FXWorkerThread::Pool::isFull () const inline
Checks whether there are currently more pending tasks than threads.
This is only a rough estimate because the tasks are already assigned and there could be an idle thread even though the number of tasks is large.
Returns
whether there are enough tasks to let all threads work
Definition at line 180 of file FXWorkerThread.h.
lock()
void FXWorkerThread::Pool::lock () inline
locks the pool mutex
Definition at line 193 of file FXWorkerThread.h.
size()
int FXWorkerThread::Pool::size () const inline
Returns the number of threads in the pool.
Returns
the number of threads
Definition at line 188 of file FXWorkerThread.h.
Referenced by LandmarkLookupTable< E, V >::LandmarkLookupTable().
unlock()
void FXWorkerThread::Pool::unlock () inline
unlocks the pool mutex
Definition at line 198 of file FXWorkerThread.h.
waitAll()
void FXWorkerThread::Pool::waitAll (const bool deleteFinished = true) inline
waits for all tasks to be finished
Definition at line 156 of file FXWorkerThread.h.
References FXWorkerThread::myCondition, and FXWorkerThread::myMutex.
Referenced by LandmarkLookupTable< E, V >::LandmarkLookupTable().
Field Documentation
myCondition
FXCondition FXWorkerThread::Pool::myCondition private
the semaphore to wait on for finishing all tasks
Definition at line 210 of file FXWorkerThread.h.
myFinishedTasks
std::list<Task*> FXWorkerThread::Pool::myFinishedTasks private
list of finished tasks
Definition at line 212 of file FXWorkerThread.h.
myMutex
FXMutex FXWorkerThread::Pool::myMutex private
the internal mutex for the task list
Definition at line 206 of file FXWorkerThread.h.
myNumFinished
int FXWorkerThread::Pool::myNumFinished private
the number of finished tasks (is reset when the pool runs empty)
Definition at line 216 of file FXWorkerThread.h.
myPoolMutex
FXMutex FXWorkerThread::Pool::myPoolMutex private
the pool mutex for external sync
Definition at line 208 of file FXWorkerThread.h.
myRunningIndex
int FXWorkerThread::Pool::myRunningIndex private
the running index for the next task
Definition at line 214 of file FXWorkerThread.h.
myWorkers
std::vector<FXWorkerThread*> FXWorkerThread::Pool::myWorkers private
the current worker threads
Definition at line 204 of file FXWorkerThread.h.
The documentation for this class was generated from the following file:
FXWorkerThread.h