SUMO - Simulation of Urban MObility: GUISelectedStorage::SingleTypeSelections Class Reference
GUISelectedStorage::SingleTypeSelections Class Reference
A container for ids of selected objects of a certain type.
#include <GUISelectedStorage.h>
Public Member Functions
void clear ()
Clears the list of selected objects.
void deselect (GUIGlID id)
Deselects the object with the given id from the list of selected objects.
const std::set< GUIGlID > & getSelected () const
Returns the list of selected ids.
bool isSelected (GUIGlID id)
Returns the information whether the object with the given id is qithin the selection.
void save (const std::string &filename)
Saves the list of selected objects to a file named as given.
void select (GUIGlID id)
Adds the object with the given id to the list of selected objects.
SingleTypeSelections ()
Constructor.
~SingleTypeSelections ()
Destructor.
Private Attributes
std::set< GUIGlID > mySelected
The list of selected ids.
Detailed Description
A container for ids of selected objects of a certain type.
Definition at line 228 of file GUISelectedStorage.h.
Constructor & Destructor Documentation
SingleTypeSelections()
GUISelectedStorage::SingleTypeSelections::SingleTypeSelections ()
Constructor.
Definition at line 49 of file GUISelectedStorage.cpp.
~SingleTypeSelections()
GUISelectedStorage::SingleTypeSelections::~SingleTypeSelections ()
Destructor.
Definition at line 52 of file GUISelectedStorage.cpp.
Member Function Documentation
clear()
void GUISelectedStorage::SingleTypeSelections::clear ()
Clears the list of selected objects.
Definition at line 74 of file GUISelectedStorage.cpp.
References mySelected.
deselect()
void GUISelectedStorage::SingleTypeSelections::deselect (GUIGlID id)
Deselects the object with the given id from the list of selected objects.
Parameters
[in] id The id of the object
Definition at line 68 of file GUISelectedStorage.cpp.
References mySelected.
Referenced by GUISelectedStorage::toggleSelection().
getSelected()
const std::set< GUIGlID > & GUISelectedStorage::SingleTypeSelections::getSelected () const
Returns the list of selected ids.
Returns
A list containing the ids of all selected objects
Definition at line 86 of file GUISelectedStorage.cpp.
References mySelected.
isSelected()
bool GUISelectedStorage::SingleTypeSelections::isSelected (GUIGlID id)
Returns the information whether the object with the given id is qithin the selection.
Parameters
[in] id The id of the object
Returns
Whether the object is selected
Definition at line 56 of file GUISelectedStorage.cpp.
References mySelected.
Referenced by GUISelectedStorage::isSelected(), and GUISelectedStorage::toggleSelection().
save()
void GUISelectedStorage::SingleTypeSelections::save (const std::string & filename)
Saves the list of selected objects to a file named as given.
Parameters
[in] filename The name of the file to save the list into
Definition at line 80 of file GUISelectedStorage.cpp.
References mySelected, and GUISelectedStorage::save().
Referenced by GUISelectedStorage::save().
select()
void GUISelectedStorage::SingleTypeSelections::select (GUIGlID id)
Adds the object with the given id to the list of selected objects.
Parameters
[in] id The id of the object
Definition at line 62 of file GUISelectedStorage.cpp.
References mySelected.
Referenced by GUISelectedStorage::load(), and GUISelectedStorage::toggleSelection().
Field Documentation
mySelected
std::set<GUIGlID> GUISelectedStorage::SingleTypeSelections::mySelected private
The list of selected ids.
Definition at line 268 of file GUISelectedStorage.h.
Referenced by clear(), deselect(), getSelected(), isSelected(), save(), and select().
The documentation for this class was generated from the following files:
GUISelectedStorage.h
GUISelectedStorage.cpp