SUMO - Simulation of Urban MObility: NBNode Class Reference
NBNode Class Reference
Represents a single node (junction) during network building.
#include <NBNode.h>
Data Structures
class ApproachingDivider
Computes lane-2-lane connections.
struct Crossing
A definition of a pedestrian crossing.
class edge_by_direction_sorter
Sorts outgoing before incoming edges.
class nodes_by_id_sorter
Used for sorting the cells by the begin time they describe.
struct WalkingArea
A definition of a pedestrian walking area.
struct WalkingAreaCustomShape
Public Member Functions
void addCrossing (EdgeVector edges, double width, bool priority, int tlIndex=-1, const PositionVector &customShape=PositionVector::EMPTY, bool fromSumoNet=false)
add a pedestrian crossing to this node
void addIncomingEdge (NBEdge *edge)
adds an incoming edge
void addOutgoingEdge (NBEdge *edge)
adds an outgoing edge
void addSortedLinkFoes (const NBConnection &mayDrive, const NBConnection &mustStop)
add shorted link FOES
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void addWalkingAreaShape (EdgeVector edges, const PositionVector &shape)
add custom shape for walkingArea
void avoidOverlap ()
fix overlap
int buildCrossings ()
build pedestrian crossings
void buildCrossingsAndWalkingAreas ()
build crossings, and walkingareas. Also removes invalid loaded crossings if wished
void buildInnerEdges ()
build internal lanes, pedestrian crossings and walking areas
void buildWalkingAreas (int cornerDetail)
build pedestrian walking areas and set connections from/to walkingAreas
int checkCrossing (EdgeVector candidates)
bool checkCrossingDuplicated (EdgeVector edges)
return true if already exist a crossing with the same edges as the input
bool checkIsRemovable () const
check if node is removable
bool checkIsRemovableReporting (std::string &reason) const
check if node is removable and return reason if not
void clearParameter ()
Clears the parameter map.
PositionVector computeInternalLaneShape (NBEdge *fromE, const NBEdge::Connection &con, int numPoints, NBNode *recordError=0) const
Compute the shape for an internal lane.
void computeLanes2Lanes ()
computes the connections of lanes to edges
void computeLogic (const NBEdgeCont &ec, OptionsCont &oc)
computes the node's type, logic and traffic light
void computeNodeShape (double mismatchThreshold)
Compute the junction shape for this node.
PositionVector computeSmoothShape (const PositionVector &begShape, const PositionVector &endShape, int numPoints, bool isTurnaround, double extrapolateBeg, double extrapolateEnd, NBNode *recordError=0) const
Compute a smooth curve between the given geometries.
bool crossingBetween (const NBEdge *e1, const NBEdge *e2) const
return true if the given edges are connected by a crossing
void discardAllCrossings (bool rejectAll)
discard all current (and optionally future) crossings
EdgeVector edgesBetween (const NBEdge *e1, const NBEdge *e2) const
return all edges that lie clockwise between the given edges
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
bool geometryLike () const
whether this is structurally similar to a geometry node
int getConnectionIndex (const NBEdge *from, const NBEdge::Connection &con) const
return the index of the given connection
NBEdge * getConnectionTo (NBNode *n) const
get connection to certain node
Crossing * getCrossing (const std::string &id) const
return the crossing with the given id
std::vector< Crossing * > getCrossings () const
return this junctions pedestrian crossings
const std::vector< Crossing * > & getCrossingsIncludingInvalid () const
LinkDirection getDirection (const NBEdge *const incoming, const NBEdge *const outgoing, bool leftHand=false) const
Returns the representation of the described stream's direction.
double getDisplacementError () const
compute the displacement error during s-curve computation
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
std::vector< std::pair< NBEdge *, NBEdge * > > getEdgesToJoin () const
get edges to join
Position getEmptyDir () const
Returns something like the most unused direction Should only be used to add source or sink nodes.
const std::string & getID () const
Returns the id.
LinkState getLinkState (const NBEdge *incoming, NBEdge *outgoing, int fromLane, int toLane, bool mayDefinitelyPass, const std::string &tlID) const
get link state
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
NBEdge * getOppositeIncoming (NBEdge *e) const
returns the opposite incoming edge of certain edge
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
NBEdge * getPossiblySplittedIncoming (const std::string &edgeid)
get possibly splitted incoming edge
NBEdge * getPossiblySplittedOutgoing (const std::string &edgeid)
get possibly splitted outgoing edge
const NBConnectionProhibits & getProhibitions ()
get prohibitions (BLocked connections)
const PositionVector & getShape () const
retrieve the junction shape
const std::vector< WalkingArea > & getWalkingAreas () const
return this junctions pedestrian walking areas
int guessCrossings ()
guess pedestrian crossings and return how many were guessed
bool hasCustomShape () const
return whether the shape was set by the user
bool hasIncoming (const NBEdge *const e) const
Returns whether the given edge ends at this node.
bool hasOutgoing (const NBEdge *const e) const
Returns whether the given edge starts at this node.
void invalidateIncomingConnections ()
invalidate incoming connections
void invalidateOutgoingConnections ()
invalidate outgoing connections
bool isDistrict () const
check if node is a district
bool isLeftMover (const NBEdge *const from, const NBEdge *const to) const
Computes whether the given connection is a left mover across the junction.
bool isNearDistrict () const
if node is near district
bool isSimpleContinuation (bool checkLaneNumbers=true) const
check if node is a simple continuation
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
bool mustBrake (const NBEdge *const from, const NBEdge *const to, int fromLane, int toLane, bool includePedCrossings) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrakeForCrossing (const NBEdge *const from, const NBEdge *const to, const Crossing &crossing) const
Returns the information whether the described flow must brake for the given crossing.
NBNode (const std::string &id, const Position &position, SumoXMLNodeType type)
Constructor.
NBNode (const std::string &id, const Position &position, NBDistrict *district=0)
Constructor.
bool needsCont (const NBEdge *fromE, const NBEdge *otherFromE, const NBEdge::Connection &c, const NBEdge::Connection &otherC) const
whether an internal junction should be built at from and respect other
int numCrossingsFromSumoNet () const
get num of crossings from sumo net
int numNormalConnections () const
return the number of lane-to-lane connections at this junction (excluding crossings)
void reinit (const Position &position, SumoXMLNodeType type, bool updateEdgeGeometries=false)
Resets initial values.
void removeCrossing (const EdgeVector &edges)
remove a pedestrian crossing from this node (identified by its edges)
void removeDoubleEdges ()
remove duble edges
void removeEdge (NBEdge *edge, bool removeFromConnections=true)
Removes edge from this node and optionally removes connections as well.
void replaceIncoming (NBEdge *which, NBEdge *by, int laneOff)
Replaces occurences of the first edge within the list of incoming by the second Connections are remapped, too.
void replaceIncoming (const EdgeVector &which, NBEdge *by)
Replaces occurences of every edge from the given list within the list of incoming by the second Connections are remapped, too.
void replaceOutgoing (NBEdge *which, NBEdge *by, int laneOff)
Replaces occurences of the first edge within the list of outgoing by the second Connections are remapped, too.
void replaceOutgoing (const EdgeVector &which, NBEdge *by)
Replaces occurences of every edge from the given list within the list of outgoing by the second Connections are remapped, too.
bool rightOnRedConflict (int index, int foeIndex) const
whether the given index must yield to the foeIndex while turing right on a red light
void setCrossingTLIndices (const std::string &tlID, int startIndex)
set tl indices of this nodes crossing starting at the given index
void setCustomShape (const PositionVector &shape)
set the junction shape
void setID (const std::string &newID)
resets the id
void setKeepClear (bool keepClear)
set the keepClear flag
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void setRadius (double radius)
set the turning radius
void setRoundabout ()
update the type of this node as a roundabout
void sortEdges (bool useNodeShape)
sort all edge containers for this node
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
bool writeLogic (OutputDevice &into, const bool checkLaneFoes) const
writes the XML-representation of the logic as a bitset-logic XML representation
void writeParams (OutputDevice &out) const
~NBNode ()
Destructor.
Atomar getter methods
Returns the position of this node
const Position & getPosition () const
Position getCenter () const
Returns a position that is guaranteed to lie within the node shape.
const EdgeVector & getIncomingEdges () const
Returns this node's incoming edges (The edges which yield in this node)
const EdgeVector & getOutgoingEdges () const
Returns this node's outgoing edges (The edges which start at this node)
const EdgeVector & getEdges () const
Returns all edges which participate in this node (Edges that start or end at this node)
SumoXMLNodeType getType () const
Returns the type of this node.
double getRadius () const
Returns the turning radius of this node.
bool getKeepClear () const
Returns the keepClear flag.
Methods for dealing with assigned traffic lights
void addTrafficLight (NBTrafficLightDefinition *tlDef)
Adds a traffic light to the list of traffic lights that control this node.
void removeTrafficLight (NBTrafficLightDefinition *tlDef)
Removes the given traffic light from this node.
void removeTrafficLights ()
Removes all references to traffic lights that control this tls.
bool isTLControlled () const
Returns whether this node is controlled by any tls.
const std::set< NBTrafficLightDefinition * > & getControllingTLS () const
Returns the traffic lights that were assigned to this node (The set of tls that control this node)
void invalidateTLS (NBTrafficLightLogicCont &tlCont, bool removedConnections, bool addedConnections)
causes the traffic light to be computed anew
void shiftTLConnectionLaneIndex (NBEdge *edge, int offset)
patches loaded signal plans by modifying lane indices
Prunning the input
int removeSelfLoops (NBDistrictCont &dc, NBEdgeCont &ec, NBTrafficLightLogicCont &tc)
Removes edges which are both incoming and outgoing into this node.
Applying offset
void reshiftPosition (double xoff, double yoff)
Applies an offset to the node.
void mirrorX ()
mirror coordinates along the x-axis
Static Public Member Functions
static PositionVector bezierControlPoints (const PositionVector &begShape, const PositionVector &endShape, bool isTurnaround, double extrapolateBeg, double extrapolateEnd, bool &ok, NBNode *recordError=0, double straightThresh=DEG2RAD(5))
get bezier control points
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static std::string getNodeIDFromInternalLane (const std::string id)
returns the node id for internal lanes, crossings and walkingareas
static bool isTrafficLight (SumoXMLNodeType type)
return whether the given type is a traffic light
static bool rightTurnConflict (const NBEdge *from, const NBEdge *to, int fromLane, const NBEdge *prohibitorFrom, const NBEdge *prohibitorTo, int prohibitorFromLane, bool lefthand=false)
return whether the given laneToLane connection is a right turn which must yield to a bicycle crossings
Static Public Attributes
static const int BACKWARD
static const int FORWARD
edge directions (for pedestrian related stuff)
static const double UNSPECIFIED_RADIUS = -1
unspecified lane width
Protected Attributes
std::string myID
The name of the object.
Private Member Functions
bool forbidsPedestriansAfter (std::vector< std::pair< NBEdge *, bool > > normalizedLanes, int startIndex)
return whether there is a non-sidewalk lane after the given index;
EdgeVector getEdgesSortedByAngleAtNodeCenter () const
returns the list of all edges sorted clockwise by getAngleAtNodeToCenter
EdgeVector * getEdgesThatApproach (NBEdge *currentOutgoing)
returns a list of edges which are connected to the given outgoing edge
NBNode (const NBNode &s)
invalidated copy constructor
NBNode & operator= (const NBNode &s)
invalidated assignment operator
void remapRemoved (NBTrafficLightLogicCont &tc, NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)
remap removed
void removeJoinedTrafficLights ()
remove all traffic light definitions that are part of a joined tls
void replaceInConnectionProhibitions (NBEdge *which, NBEdge *by, int whichLaneOff, int byLaneOff)
replace incoming connections prohibitions
void setPriorityJunctionPriorities ()
sets the priorites in case of a priority junction
Static Private Member Functions
static bool isLongEnough (NBEdge *out, double minLength)
check if is long enough
Private Attributes
EdgeVector myAllEdges
Vector of incoming and outgoing edges.
NBConnectionProhibits myBlockedConnections
The container for connection block dependencies.
std::vector< Crossing * > myCrossings
Vector of crossings.
int myCrossingsLoadedFromSumoNet
number of crossings loaded from a sumo net
bool myDiscardAllCrossings
whether to discard all pedestrian crossings
double myDisplacementError
geometry error after computation of internal lane shapes
NBDistrict * myDistrict
The district the node is the centre of.
bool myHaveCustomPoly
whether this nodes shape was set by the user
EdgeVector myIncomingEdges
Vector of incoming edges.
bool myKeepClear
whether the junction area must be kept clear
EdgeVector myOutgoingEdges
Vector of outgoing edges.
PositionVector myPoly
the (outer) shape of the junction
Position myPosition
The position the node lies at.
double myRadius
the turning radius (for all corners) at this node in m.
NBRequest * myRequest
Node requests.
std::set< NBTrafficLightDefinition * > myTrafficLights
traffic lights of node
SumoXMLNodeType myType
The type of the junction.
std::vector< WalkingAreaCustomShape > myWalkingAreaCustomShapes
Vector of custom walking areas shapes.
std::vector< WalkingArea > myWalkingAreas
Vector of walking areas.
Friends
class GNEJunction
class NBEdgePriorityComputer
class NBNodeCont
class NBNodesEdgesSorter
class NBNodeShapeComputer
class NBNodeTypeComputer
Detailed Description
Represents a single node (junction) during network building.
Definition at line 74 of file NBNode.h.
Constructor & Destructor Documentation
NBNode() [1/3]
NBNode::NBNode (const std::string & id, const Position & position, SumoXMLNodeType type)
Constructor.
Parameters
[in] id The id of the node
[in] position The position of the node
[in] type The type of the node
Definition at line 236 of file NBNode.cpp.
NBNode() [2/3]
NBNode::NBNode (const std::string & id, const Position & position, NBDistrict * district = 0)
Constructor.
Parameters
[in] id The id of the node
[in] position The position of the node
[in] district The district this district node represents, 0 means no district node
Definition at line 252 of file NBNode.cpp.
~NBNode()
NBNode::~NBNode ()
Destructor.
Definition at line 267 of file NBNode.cpp.
References myRequest.
NBNode() [3/3]
NBNode::NBNode (const NBNode & s) private
invalidated copy constructor
Member Function Documentation
addCrossing()
void NBNode::addCrossing (EdgeVector edges, double width, bool priority, int tlIndex = -1, const PositionVector & customShape = PositionVector::EMPTY, bool fromSumoNet = false)
add a pedestrian crossing to this node
Definition at line 2635 of file NBNode.cpp.
References myCrossings, and myCrossingsLoadedFromSumoNet.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLConnectionsHandler::addCrossing(), checkCrossing(), getProhibitions(), GNEChange_Crossing::redo(), and GNEChange_Crossing::undo().
addIncomingEdge()
void NBNode::addIncomingEdge (NBEdge * edge)
adds an incoming edge
Definition at line 411 of file NBNode.cpp.
References myAllEdges, and myIncomingEdges.
Referenced by getControllingTLS(), NBEdge::init(), GNENet::insertEdge(), NBEdge::reinitNodes(), and NBEdge::splitGeometry().
addOutgoingEdge()
void NBNode::addOutgoingEdge (NBEdge * edge)
adds an outgoing edge
Definition at line 421 of file NBNode.cpp.
References myAllEdges, and myOutgoingEdges.
Referenced by getControllingTLS(), NBEdge::init(), GNENet::insertEdge(), and NBEdge::reinitNodes().
addSortedLinkFoes()
void NBNode::addSortedLinkFoes (const NBConnection & mayDrive, const NBConnection & mustStop)
add shorted link FOES
Definition at line 1238 of file NBNode.cpp.
References NBConnection::getFrom(), NBConnection::getTo(), myBlockedConnections, and WRITE_WARNING.
Referenced by NIImporter_SUMO::_loadNetwork(), NIVissimDisturbance::addToNode(), getControllingTLS(), NIXMLConnectionsHandler::myStartElement(), and NIVissimConflictArea::setPriorityRegulation().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
addTrafficLight()
void NBNode::addTrafficLight (NBTrafficLightDefinition * tlDef)
Adds a traffic light to the list of traffic lights that control this node.
Parameters
[in] tld The traffic light that controls this node
Definition at line 321 of file NBNode.cpp.
References isTrafficLight(), myTrafficLights, myType, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, and NODETYPE_TRAFFIC_LIGHT.
Referenced by NBTrafficLightDefinition::addNode(), NBLoadedTLDef::addToSignalGroup(), getKeepClear(), and NIImporter_OpenDrive::loadNetwork().
addWalkingAreaShape()
void NBNode::addWalkingAreaShape (EdgeVector edges, const PositionVector & shape)
add custom shape for walkingArea
Definition at line 2587 of file NBNode.cpp.
References NBNode::WalkingAreaCustomShape::edges, myWalkingAreaCustomShapes, and NBNode::WalkingAreaCustomShape::shape.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLConnectionsHandler::addWalkingArea(), and getProhibitions().
avoidOverlap()
void NBNode::avoidOverlap ()
fix overlap
Definition at line 2778 of file NBNode.cpp.
References NBEdge::getTurnDestination(), myIncomingEdges, and NBEdge::shiftPositionAtNode().
Referenced by getWalkingAreas().
bezierControlPoints()
PositionVector NBNode::bezierControlPoints (const PositionVector & begShape, const PositionVector & endShape, bool isTurnaround, double extrapolateBeg, double extrapolateEnd, bool & ok, NBNode * recordError = 0, double straightThresh = DEG2RAD(5)) static
get bezier control points
Definition at line 486 of file NBNode.cpp.
References PositionVector::angleAt2D(), GeomHelper::angleDiff(), Position::angleTo2D(), DEBUGCOND, Position::distanceTo2D(), PositionVector::extrapolate2D(), Position::INVALID, M_PI, MAX2(), MIN2(), myDisplacementError, PositionVector::nearest_offset_to_point2D(), POSITION_EPS, PositionVector::positionAtOffset2D(), RAD2DEG, Position::set(), Position::sub(), Position::x(), Position::y(), and Position::z().
Referenced by computeSmoothShape(), hasCustomShape(), GNEEdge::smoothShape(), NWWriter_OpenDrive::writeGeomSmooth(), and NWWriter_OpenDrive::writeInternalEdge().
buildCrossings()
int NBNode::buildCrossings ()
build pedestrian crossings
Returns
The next index for creating internal lanes
Definition at line 2091 of file NBNode.cpp.
References BACKWARD, DEBUGCOND, PositionVector::extrapolate(), FORWARD, gDebugFlag1, OptionsCont::getFloat(), Named::getID(), OptionsCont::getOptions(), PositionVector::move2side(), myCrossings, myDiscardAllCrossings, NBHelpers::relAngle(), NBEdge::Lane::shape, SUMO_const_laneWidth, toString(), NBEdge::UNSPECIFIED_WIDTH, NBEdge::Lane::width, and WRITE_WARNING.
Referenced by buildCrossingsAndWalkingAreas(), and getDisplacementError().
buildCrossingsAndWalkingAreas()
void NBNode::buildCrossingsAndWalkingAreas ()
build crossings, and walkingareas. Also removes invalid loaded crossings if wished
Definition at line 2015 of file NBNode.cpp.
References buildCrossings(), buildWalkingAreas(), Named::getID(), OptionsCont::getOptions(), myCrossings, myWalkingAreas, toString(), and WRITE_WARNING.
Referenced by getDisplacementError(), and GNEJunction::rebuildGNECrossings().
buildInnerEdges()
void NBNode::buildInnerEdges ()
build internal lanes, pedestrian crossings and walking areas
Definition at line 2068 of file NBNode.cpp.
References myDisplacementError, and myIncomingEdges.
Referenced by getDisplacementError().
buildWalkingAreas()
void NBNode::buildWalkingAreas (int cornerDetail)
build pedestrian walking areas and set connections from/to walkingAreas
Parameters
[in] cornerDetail The detail level when generating the inner curve
Definition at line 2180 of file NBNode.cpp.
References PositionVector::append(), computeSmoothShape(), crossingBetween(), DEBUGCOND, Position::distanceTo2D(), NBNode::Crossing::edges, gDebugFlag1, getCrossings(), getEdgesSortedByAngleAtNodeCenter(), NBEdge::getFromNode(), Named::getID(), NBEdge::getLanes(), NBEdge::getLaneShape(), NBEdge::getSidewalkID(), PositionVector::getSubpartByIndex(), NBEdge::hasConnectionTo(), NBNode::WalkingArea::hasCustomShape, NBNode::Crossing::id, NBNode::WalkingArea::id, NBNode::WalkingArea::length, MAX2(), NBNode::WalkingArea::minNextCrossingEdges, NBNode::WalkingArea::minPrevCrossingEdges, PositionVector::move2side(), myAllEdges, myWalkingAreaCustomShapes, myWalkingAreas, NBNode::WalkingArea::nextCrossings, NBNode::WalkingArea::nextSidewalks, NBNode::Crossing::nextWalkingArea, NBEdge::Lane::permissions, POSITION_EPS, NBNode::WalkingArea::prevSidewalks, NBNode::Crossing::prevWalkingArea, PositionVector::push_back_noDoublePos(), PositionVector::push_front_noDoublePos(), PositionVector::reverse(), NBEdge::Lane::shape, NBNode::Crossing::shape, NBNode::WalkingArea::shape, SUMO_const_laneWidth, SVC_PEDESTRIAN, toString(), NBEdge::UNSPECIFIED_WIDTH, NBNode::Crossing::valid, NBEdge::Lane::width, NBNode::Crossing::width, NBNode::WalkingArea::width, and WRITE_WARNING.
Referenced by buildCrossingsAndWalkingAreas(), and getDisplacementError().
checkCrossing()
int NBNode::checkCrossing (EdgeVector candidates)
Definition at line 1896 of file NBNode.cpp.
References addCrossing(), Position::distanceTo2D(), EXTEND_CROSSING_ANGLE_THRESHOLD, gDebugFlag1, NBEdge::getCrossingAngle(), OptionsCont::getFloat(), NBEdge::getFromNode(), NBEdge::getLanes(), NBEdge::getLaneWidth(), NBEdge::getNumLanes(), OptionsCont::getOptions(), NBEdge::getSpeed(), NBEdge::getToNode(), isTLControlled(), myType, NODETYPE_RAIL_CROSSING, SPLIT_CROSSING_ANGLE_THRESHOLD, SPLIT_CROSSING_WIDTH_THRESHOLD, toString(), and NBEdge::UNSPECIFIED_WIDTH.
Referenced by getDisplacementError(), and guessCrossings().
checkCrossingDuplicated()
bool NBNode::checkCrossingDuplicated (EdgeVector edges)
return true if already exist a crossing with the same edges as the input
Definition at line 1987 of file NBNode.cpp.
References myCrossings.
Referenced by getDisplacementError(), and GNECrossingFrame::onCmdCreateCrossing().
checkIsRemovable()
bool NBNode::checkIsRemovable () const
check if node is removable
Definition at line 1634 of file NBNode.cpp.
References checkIsRemovableReporting().
Referenced by getEdgesToJoin(), hasCustomShape(), NBNodeCont::removeUnwishedNodes(), and GNENet::replaceJunctionByGeometry().
checkIsRemovableReporting()
bool NBNode::checkIsRemovableReporting (std::string & reason) const
check if node is removable and return reason if not
Definition at line 1640 of file NBNode.cpp.
References NBEdge::getTurnDestination(), myCrossings, myIncomingEdges, myOutgoingEdges, and myTrafficLights.
Referenced by checkIsRemovable(), GNEJunction::getPopUpMenu(), and hasCustomShape().
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
computeInternalLaneShape()
PositionVector NBNode::computeInternalLaneShape (NBEdge * fromE, const NBEdge::Connection & con, int numPoints, NBNode * recordError = 0) const
Compute the shape for an internal lane.
Parameters
[in] fromE The starting edge
[in] con The connection for this internal lane
[in] numPoints The number of geometry points for the internal lane
[in] recordError The node itself if the displacement error during shape computation shall be recorded
Returns
The shape of the internal lane
Definition at line 626 of file NBNode.cpp.
References PositionVector::append(), computeSmoothShape(), NBEdge::Connection::customShape, NBEdge::Lane::endOffset, NBEdge::Connection::fromLane, NBEdge::Connection::getDescription(), NBEdge::getLaneShape(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), PositionVector::getSubpart(), NBEdge::getTurnDestination(), PositionVector::length(), NBEdge::Lane::shape, NBEdge::Connection::toEdge, and NBEdge::Connection::toLane.
Referenced by GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), and hasCustomShape().
computeLanes2Lanes()
void NBNode::computeLanes2Lanes ()
computes the connections of lanes to edges
Definition at line 803 of file NBNode.cpp.
References NBEdge::addLane2LaneConnections(), Bresenham::compute(), NBEdge::Lane::connectionsDone, FORWARD, NBEdge::Connection::fromLane, NBEdge::getAngleAtNode(), GeomHelper::getCCWAngleDiff(), NBEdge::getConnectionLanes(), NBEdge::getConnections(), GeomHelper::getCWAngleDiff(), getDirection(), getEdgesThatApproach(), NBEdge::getFirstNonPedestrianLaneIndex(), NBEdge::getLaneStruct(), NBEdge::getNumLanes(), NBEdge::getPermissions(), NBEdge::getPermissionVariants(), NBEdge::getStep(), NBEdge::getTurnDestination(), NBEdge::isConnectedTo(), isLongEnough(), NBEdge::isTurningDirectionAt(), NBEdge::L2L_COMPUTED, NBEdge::L2L_VALIDATED, NBEdge::LANES2EDGES, NBEdge::LANES2LANES_DONE, LINKDIR_TURN, MAX2(), MIN2(), MIN_WEAVE_LENGTH, myIncomingEdges, myOutgoingEdges, myType, NODETYPE_RAIL_CROSSING, NODETYPE_ZIPPER, NBNode::ApproachingDivider::numAvailableLanes(), NBEdge::setConnection(), SVC_PEDESTRIAN, NBEdge::Connection::toEdge, and NBEdge::Connection::toLane.
Referenced by getControllingTLS().
computeLogic()
void NBNode::computeLogic (const NBEdgeCont & ec, OptionsCont & oc)
computes the node's type, logic and traffic light
Definition at line 716 of file NBNode.cpp.
References NBRequest::buildBitfieldLogic(), OptionsCont::getBool(), Named::getID(), isDistrict(), OptionsCont::isInStringVector(), isNearDistrict(), myAllEdges, myBlockedConnections, myIncomingEdges, myOutgoingEdges, myRequest, myType, NODETYPE_DEAD_END, NODETYPE_DISTRICT, NODETYPE_NOJUNCTION, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, numNormalConnections(), removeJoinedTrafficLights(), SUMO_MAX_CONNECTIONS, toString(), and WRITE_WARNING.
Referenced by getControllingTLS().
computeNodeShape()
void NBNode::computeNodeShape (double mismatchThreshold)
Compute the junction shape for this node.
Parameters
[in] mismatchThreshold The threshold for warning about shapes which are away from myPosition
Definition at line 771 of file NBNode.cpp.
References PositionVector::around(), NBNodeShapeComputer::compute(), PositionVector::distance2D(), Named::getID(), myHaveCustomPoly, Named::myID, myIncomingEdges, myOutgoingEdges, myPoly, myPosition, PositionVector::push_back_noDoublePos(), toString(), and WRITE_WARNING.
Referenced by getControllingTLS(), and GNEViewNet::onCmdEditJunctionShape().
computeSmoothShape()
PositionVector NBNode::computeSmoothShape (const PositionVector & begShape, const PositionVector & endShape, int numPoints, bool isTurnaround, double extrapolateBeg, double extrapolateEnd, NBNode * recordError = 0) const
Compute a smooth curve between the given geometries.
Parameters
[in] begShape The geometry at the start
[in] endShape The geometry at the end
[in] numPoints The number of geometry points for the internal lane
[in] isTurnaround Whether this shall be the shape for a turnaround
[in] extrapolateBeg Extrapolation distance at the beginning
[in] extrapolateEnd Extrapolation distance at the end
[in] recordError The node itself if the displacement error during shape computation shall be recorded
Returns
The shape of the internal lane
Definition at line 460 of file NBNode.cpp.
References bezier(), bezierControlPoints(), DEBUGCOND, and Named::getID().
Referenced by buildWalkingAreas(), computeInternalLaneShape(), NBNodeShapeComputer::getSmoothCorner(), hasCustomShape(), and GNEConnection::updateGeometry().
crossingBetween()
bool NBNode::crossingBetween (const NBEdge * e1, const NBEdge * e2) const
return true if the given edges are connected by a crossing
Definition at line 2550 of file NBNode.cpp.
References getCrossings(), and myAllEdges.
Referenced by buildWalkingAreas(), and getDisplacementError().
discardAllCrossings()
void NBNode::discardAllCrossings (bool rejectAll)
discard all current (and optionally future) crossings
Definition at line 2056 of file NBNode.cpp.
References myCrossings, and myDiscardAllCrossings.
Referenced by NIXMLConnectionsHandler::addCrossing(), and getProhibitions().
edgesBetween()
EdgeVector NBNode::edgesBetween (const NBEdge * e1, const NBEdge * e2) const
return all edges that lie clockwise between the given edges
Definition at line 2571 of file NBNode.cpp.
References myAllEdges, and NBContHelper::nextCW().
Referenced by getDisplacementError().
foes()
bool NBNode::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
Parameters
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns
Whether both stream are foes (cross)
Definition at line 1451 of file NBNode.cpp.
References NBRequest::foes(), and myRequest.
Referenced by NBEdge::buildInnerEdges(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), getControllingTLS(), and needsCont().
forbids()
bool NBNode::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
Definition at line 1441 of file NBNode.cpp.
References NBRequest::forbids(), and myRequest.
Referenced by NBEdge::buildInnerEdges(), NBTrafficLightDefinition::forbids(), and getControllingTLS().
forbidsPedestriansAfter()
bool NBNode::forbidsPedestriansAfter (std::vector< std::pair< NBEdge *, bool > > normalizedLanes, int startIndex) private
return whether there is a non-sidewalk lane after the given index;
Definition at line 2004 of file NBNode.cpp.
Referenced by guessCrossings().
geometryLike()
bool NBNode::geometryLike () const
whether this is structurally similar to a geometry node
Definition at line 2596 of file NBNode.cpp.
References NBEdge::getAngleAtNode(), NBEdge::isTurningDirectionAt(), MAX2(), myIncomingEdges, myOutgoingEdges, and NBHelpers::relAngle().
Referenced by NBEdge::cutAtIntersection(), NBNodeCont::discardTrafficLights(), NBNodeCont::generateNodeClusters(), getProhibitions(), NBNodeCont::guessTLs(), GNEEdge::smoothShape(), NBEdge::startShapeAt(), NWWriter_OpenDrive::writeInternalEdge(), and NWWriter_OpenDrive::writeNetwork().
getCenter()
Position NBNode::getCenter () const
Returns a position that is guaranteed to lie within the node shape.
Definition at line 2717 of file NBNode.cpp.
References PositionVector::around(), PositionVector::closePolygon(), PositionVector::distance2D(), PositionVector::getPolygonCenter(), myPoly, myPosition, and POSITION_EPS.
Referenced by getPosition().
getConnectionIndex()
int NBNode::getConnectionIndex (const NBEdge * from, const NBEdge::Connection & con) const
return the index of the given connection
Definition at line 2698 of file NBNode.cpp.
References NBEdge::Connection::fromLane, myIncomingEdges, NBEdge::Connection::toEdge, and NBEdge::Connection::toLane.
Referenced by GNELane::drawLinkNo(), and getWalkingAreas().
getConnectionTo()
NBEdge * NBNode::getConnectionTo (NBNode * n) const
get connection to certain node
Definition at line 1744 of file NBNode.cpp.
References myOutgoingEdges.
Referenced by getControllingTLS(), NBEdgeCont::guessRoundabouts(), NBNodeCont::joinJunctions(), NIImporter_ArcView::load(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Turns(), and NGNet::toNB().
getControllingTLS()
const std::set<NBTrafficLightDefinition*>& NBNode::getControllingTLS () const inline
Returns the traffic lights that were assigned to this node (The set of tls that control this node)
Definition at line 302 of file NBNode.h.
References addIncomingEdge(), addOutgoingEdge(), addSortedLinkFoes(), computeLanes2Lanes(), computeLogic(), computeNodeShape(), foes(), forbids(), getConnectionTo(), getDirection(), getEmptyDir(), getLinkState(), getOppositeIncoming(), getPossiblySplittedIncoming(), getPossiblySplittedOutgoing(), getShape(), hasIncoming(), hasOutgoing(), invalidateIncomingConnections(), invalidateOutgoingConnections(), invalidateTLS(), isLeftMover(), mirrorX(), mustBrake(), mustBrakeForCrossing(), myTrafficLights, removeDoubleEdges(), removeEdge(), removeSelfLoops(), reshiftPosition(), rightTurnConflict(), setCustomShape(), shiftTLConnectionLaneIndex(), and writeLogic().
Referenced by GNENet::computeJunction(), NBNodeCont::discardTrafficLights(), GNEJunction::getAttribute(), NBNodeCont::guessTLs(), GNETLSEditorFrame::TLSAttributes::initTLSAttributes(), GNEJunction::invalidateTLS(), GNECrossing::isValid(), GNEConnection::isValid(), NIImporter_OpenDrive::loadNetwork(), NIXMLNodesHandler::processNodeType(), NIXMLNodesHandler::processTrafficLightDefinitions(), NBEdge::removeFromConnections(), GNEConnection::setAttribute(), GNEJunction::setAttribute(), NBEdgeCont::splitAt(), and NWWriter_XML::writeNodes().
getCrossing()
NBNode::Crossing * NBNode::getCrossing (const std::string & id) const
return the crossing with the given id
Definition at line 2660 of file NBNode.cpp.
References myCrossings.
Referenced by getWalkingAreas(), and NWWriter_SUMO::writeNetwork().
getCrossings()
std::vector< NBNode::Crossing * > NBNode::getCrossings () const
return this junctions pedestrian crossings
Definition at line 2038 of file NBNode.cpp.
References myCrossings.
Referenced by GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), buildWalkingAreas(), crossingBetween(), numCrossingsFromSumoNet(), setCrossingTLIndices(), NWWriter_SUMO::writeInternalEdges(), NWWriter_SUMO::writeInternalNodes(), NWWriter_SUMO::writeJunction(), and NWWriter_SUMO::writeNetwork().
getCrossingsIncludingInvalid()
const std::vector<Crossing*>& NBNode::getCrossingsIncludingInvalid () const inline
Definition at line 622 of file NBNode.h.
References myCrossings.
Referenced by GNEJunction::rebuildGNECrossings().
getDirection()
LinkDirection NBNode::getDirection (const NBEdge *const incoming, const NBEdge *const outgoing, bool leftHand = false) const
Returns the representation of the described stream's direction.
Parameters
[in] incoming The edge the stream starts at
[in] outgoing The edge the stream ends at
[in] leftHand Whether a lefthand network is being built. Should only be set at writing time
Returns
The direction of the stream
Definition at line 1539 of file NBNode.cpp.
References NBEdge::getAngleAtNode(), NBEdge::getJunctionPriority(), NBEdge::isTurningDirectionAt(), LINKDIR_LEFT, LINKDIR_NODIR, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, LINKDIR_TURN, LINKDIR_TURN_LEFTHAND, myAllEdges, NBContHelper::nextCCW(), NBContHelper::nextCW(), NBHelpers::normRelAngle(), and NBEdge::ROUNDABOUT.
Referenced by NBEdge::addStraightConnections(), NBEdge::buildInnerEdges(), computeLanes2Lanes(), NBOwnTLDef::computeUnblockedWeightedStreamNumber(), GNELane::drawArrows(), NBTrafficLightDefinition::forbids(), getControllingTLS(), NBEdge::MainDirections::MainDirections(), NBRequest::mustBrake(), NBRequest::mustBrakeForCrossing(), needsCont(), NBOwnTLDef::patchStateForCrossings(), rightTurnConflict(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeInternalConnections(), and NWWriter_OpenDrive::writeInternalEdge().
getDisplacementError()
double NBNode::getDisplacementError () const inline
compute the displacement error during s-curve computation
Definition at line 541 of file NBNode.h.
References buildCrossings(), buildCrossingsAndWalkingAreas(), buildInnerEdges(), buildWalkingAreas(), checkCrossing(), checkCrossingDuplicated(), crossingBetween(), edgesBetween(), guessCrossings(), myDisplacementError, replaceIncoming(), and replaceOutgoing().
Referenced by NBNodeShapeComputer::computeNodeShapeDefault().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getEdges()
const EdgeVector& NBNode::getEdges () const inline
Returns all edges which participate in this node (Edges that start or end at this node)
Definition at line 259 of file NBNode.h.
References myAllEdges.
Referenced by NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), GNENet::deleteJunction(), NBNodeCont::generateNodeClusters(), NIImporter_OpenStreetMap::getNeighboringNodes(), NBRampsComputer::getOffRampEdges(), NBEdgeCont::guessRoundabouts(), GNEJunction::moveJunctionGeometry(), GNENet::removeSolitaryJunctions(), and NBNodeCont::removeUnwishedNodes().
getEdgesSortedByAngleAtNodeCenter()
EdgeVector NBNode::getEdgesSortedByAngleAtNodeCenter () const private
returns the list of all edges sorted clockwise by getAngleAtNodeToCenter
Definition at line 2735 of file NBNode.cpp.
References gDebugFlag1, myAllEdges, and toString().
Referenced by buildWalkingAreas(), and guessCrossings().
getEdgesThatApproach()
EdgeVector * NBNode::getEdgesThatApproach (NBEdge * currentOutgoing) private
returns a list of edges which are connected to the given outgoing edge
Definition at line 1043 of file NBNode.cpp.
References myAllEdges, and NBContHelper::nextCW().
Referenced by computeLanes2Lanes().
getEdgesToJoin()
std::vector< std::pair< NBEdge *, NBEdge * > > NBNode::getEdgesToJoin () const
get edges to join
Definition at line 1703 of file NBNode.cpp.
References checkIsRemovable(), NBEdge::getTurnDestination(), myIncomingEdges, and myOutgoingEdges.
Referenced by hasCustomShape(), NBNodeCont::removeUnwishedNodes(), and GNENet::replaceJunctionByGeometry().
getEmptyDir()
Position NBNode::getEmptyDir () const
Returns something like the most unused direction Should only be used to add source or sink nodes.
Definition at line 1311 of file NBNode.cpp.
References Position::add(), getPosition(), Position::mul(), myIncomingEdges, myOutgoingEdges, myPosition, Position::norm2d(), Position::sub(), Position::x(), and Position::y().
Referenced by getControllingTLS().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), buildCrossings(), buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), computeLogic(), NBOwnTLDef::computeLogicAndConts(), computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), getPossiblySplittedIncoming(), getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getIncomingEdges()
const EdgeVector& NBNode::getIncomingEdges () const inline
Returns this node's incoming edges (The edges which yield in this node)
Definition at line 249 of file NBNode.h.
References myIncomingEdges.
Referenced by NBEdge::addLane(), NBEdge::addRestrictedLane(), NIImporter_OpenStreetMap::RelationHandler::applyRestriction(), NBEdge::buildInnerEdges(), NBRampsComputer::buildOffRamp(), NBNodeShapeComputer::compute(), NBRampsComputer::computeRamps(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NBEdge::deleteLane(), NBEdge::getIncomingEdges(), NIImporter_VISUM::getNamedEdgeContinuating(), NBRampsComputer::getOffRampEdges(), NBRampsComputer::getOnRampEdges(), GNEJunction::getPopUpMenu(), NBNodeCont::guessTLs(), NBEdge::init(), isLongEnough(), isNearDistrict(), NBNodeCont::joinJunctions(), GNEJunction::markAsModified(), NBEdgeCont::markRoundabouts(), NBRampsComputer::mayNeedOffRamp(), NBRampsComputer::mayNeedOnRamp(), GNENet::mergeJunctions(), NBContHelper::node_with_incoming_finder::operator()(), NIImporter_VISUM::parse_Lanes(), NBEdge::recheckLanes(), NBNodeCont::removeComponents(), NBNodeCont::removeIsolatedRoads(), NBNodeCont::removeUnwishedNodes(), NBEdge::restoreRestrictedLane(), NBEdgeCont::retrievePossiblySplit(), GNEJunction::setLogicValid(), GNEEdge::smoothShape(), NGNet::toNB(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeInternalConnections(), NWWriter_SUMO::writeInternalEdges(), NWWriter_SUMO::writeInternalNodes(), NWWriter_SUMO::writeJunction(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), and NWWriter_DlrNavteq::writeTrafficSignals().
getKeepClear()
bool NBNode::getKeepClear () const inline
Returns the keepClear flag.
Definition at line 276 of file NBNode.h.
References addTrafficLight(), myKeepClear, removeTrafficLight(), and removeTrafficLights().
Referenced by GNEJunction::getAttribute(), NWWriter_SUMO::writeConnection(), and NWWriter_XML::writeNodes().
getLinkState()
LinkState NBNode::getLinkState (const NBEdge * incoming, NBEdge * outgoing, int fromLane, int toLane, bool mayDefinitelyPass, const std::string & tlID) const
get link state
Definition at line 1606 of file NBNode.cpp.
References NBEdge::getPermissions(), NBEdge::isInnerEdge(), isRailway(), LINKSTATE_ALLWAY_STOP, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_STOP, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_ZIPPER, mustBrake(), myType, NODETYPE_ALLWAY_STOP, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RIGHT_BEFORE_LEFT, and NODETYPE_ZIPPER.
Referenced by GNELane::drawLane2LaneConnections(), getControllingTLS(), GNEConnection::updateLinkState(), and NWWriter_SUMO::writeConnection().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getNodeIDFromInternalLane()
std::string NBNode::getNodeIDFromInternalLane (const std::string id) static
returns the node id for internal lanes, crossings and walkingareas
Definition at line 2758 of file NBNode.cpp.
References WRITE_ERROR.
getOppositeIncoming()
NBEdge * NBNode::getOppositeIncoming (NBEdge * e) const
returns the opposite incoming edge of certain edge
Definition at line 1220 of file NBNode.cpp.
References NBEdge::getToNode(), and myIncomingEdges.
Referenced by NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), and getControllingTLS().
getOutgoingEdges()
const EdgeVector& NBNode::getOutgoingEdges () const inline
Returns this node's outgoing edges (The edges which start at this node)
Definition at line 254 of file NBNode.h.
References myOutgoingEdges.
Referenced by NIImporter_OpenStreetMap::RelationHandler::applyRestriction(), NBRampsComputer::buildOnRamp(), NBNodeShapeComputer::compute(), NBEdge::computeEdge2Edges(), NBRampsComputer::computeRamps(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), GNENet::createEdge(), NBNodeCont::discardTrafficLights(), NBEdge::getConnectedSorted(), NIImporter_VISUM::getEdge(), NIImporter_VISUM::getNamedEdgeContinuating(), NBRampsComputer::getOffRampEdges(), NBRampsComputer::getOnRampEdges(), GNEJunction::getPopUpMenu(), NBPTStopCont::getReverseEdge(), NBEdgeCont::guessOpposites(), NBNodeCont::guessTLs(), GNEConnectorFrame::initTargets(), isLongEnough(), isNearDistrict(), NBNodeCont::joinJunctions(), NBEdge::markAsInLane2LaneState(), NBRampsComputer::mayNeedOffRamp(), NBRampsComputer::mayNeedOnRamp(), GNENet::mergeJunctions(), NIXMLEdgesHandler::myEndElement(), NBContHelper::node_with_outgoing_finder::operator()(), NIImporter_VISUM::parse_Lanes(), NBEdge::recheckLanes(), NBNodeCont::removeComponents(), NBNodeCont::removeIsolatedRoads(), NBNodeCont::removeUnwishedNodes(), NBEdgeCont::retrievePossiblySplit(), GNEEdge::smoothShape(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_DlrNavteq::writeProhibitedManoeuvres().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getPosition()
const Position& NBNode::getPosition () const inline
Definition at line 241 of file NBNode.h.
References getCenter(), and myPosition.
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLNodesHandler::addNode(), NIXMLEdgesHandler::addSplit(), NIVissimEdge::buildNBEdge(), GNEJunction::commitGeometryMoving(), NBEdge::computeAngle(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBEdge::cutAtIntersection(), NBNodeCont::discardTrafficLights(), NBHelpers::distance(), GNEJunction::drawGL(), NBEdge::extendGeometryAtNode(), NBNodeCont::extract(), GNEJunction::getAttribute(), GNEJunction::getColorValue(), getEmptyDir(), NWWriter_DlrNavteq::getGraphLength(), GNEJunction::getPositionInView(), NBEdge::hasDefaultGeometryEndpointAtNode(), NBEdge::hasDefaultGeometryEndpoints(), NBEdge::init(), NBNodeCont::insert(), GNEViewNet::mergeJunctions(), GNEJunction::moveGeometry(), GNEJunction::moveJunctionGeometry(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), NIImporter_OpenStreetMap::reconstructLayerElevation(), GNENet::registerJunction(), NIVissimEdge::remapOneOfNodes(), GNENet::replaceJunctionByGeometry(), NIImporter_DlrNavteq::EdgesHandler::report(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), GNEEdge::resetEndpoint(), NBNodeCont::retrieve(), GNEEdge::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setEndpoint(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), NBEdge::splitGeometry(), NBEdge::startShapeAt(), GNEEdge::straightenElevation(), GNEJunction::updateGeometry(), GNEEdge::updateJunctionPosition(), NWWriter_SUMO::writeJunction(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
getPossiblySplittedIncoming()
NBEdge * NBNode::getPossiblySplittedIncoming (const std::string & edgeid)
get possibly splitted incoming edge
Definition at line 1255 of file NBNode.cpp.
References Named::getID(), and myIncomingEdges.
Referenced by NIVissimDisturbance::getConnection(), and getControllingTLS().
getPossiblySplittedOutgoing()
NBEdge * NBNode::getPossiblySplittedOutgoing (const std::string & edgeid)
get possibly splitted outgoing edge
Definition at line 1268 of file NBNode.cpp.
References Named::getID(), and myOutgoingEdges.
Referenced by NIVissimDisturbance::getConnection(), and getControllingTLS().
getProhibitions()
const NBConnectionProhibits& NBNode::getProhibitions () inline
get prohibitions (BLocked connections)
Definition at line 592 of file NBNode.h.
References addCrossing(), addWalkingAreaShape(), discardAllCrossings(), PositionVector::EMPTY, geometryLike(), myBlockedConnections, removeCrossing(), and setRoundabout().
getRadius()
double NBNode::getRadius () const inline
Returns the turning radius of this node.
Definition at line 271 of file NBNode.h.
References myRadius.
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), GNEJunction::getAttribute(), NWWriter_SUMO::writeJunction(), and NWWriter_XML::writeNodes().
getShape()
const PositionVector & NBNode::getShape () const
retrieve the junction shape
Definition at line 1726 of file NBNode.cpp.
References myPoly.
Referenced by NBEdge::computeAngle(), GNEJunction::drawGL(), GNEJunction::getAttribute(), getControllingTLS(), GNEViewNet::onCmdEditJunctionShape(), sortEdges(), NBEdge::startShapeAt(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEJunction::updateGeometry(), NWWriter_SUMO::writeJunction(), and NWWriter_XML::writeNodes().
getType()
SumoXMLNodeType NBNode::getType () const inline
Returns the type of this node.
See also
SumoXMLNodeType
Definition at line 266 of file NBNode.h.
References myType.
Referenced by NIXMLTrafficLightsHandler::addTlConnection(), NBEdge::appendTurnaround(), NBTrafficLightDefinition::collectAllLinks(), NBEdgePriorityComputer::computeEdgePrioritiesSingleNode(), NBEdgeCont::generateStreetSigns(), GNEJunction::getAttribute(), GNEJunction::getColorValue(), NBEdge::MainDirections::MainDirections(), GNEJunction::moveJunctionGeometry(), NBRequest::mustBrake(), NIXMLConnectionsHandler::parseLaneBound(), NBEdge::prepareEdgePriorities(), NIXMLNodesHandler::processNodeType(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NBRequest::setBlocking(), NBTrafficLightLogicCont::setTLControllingInformation(), NWWriter_SUMO::writeJunction(), NBRequest::writeLaneResponse(), and NWWriter_XML::writeNodes().
getWalkingAreas()
const std::vector<WalkingArea>& NBNode::getWalkingAreas () const inline
return this junctions pedestrian walking areas
Definition at line 627 of file NBNode.h.
References avoidOverlap(), getConnectionIndex(), getCrossing(), myWalkingAreas, numNormalConnections(), rightOnRedConflict(), setCrossingTLIndices(), and sortEdges().
Referenced by NWWriter_SUMO::writeInternalEdges(), and NWWriter_SUMO::writeNetwork().
guessCrossings()
int NBNode::guessCrossings ()
guess pedestrian crossings and return how many were guessed
Definition at line 1792 of file NBNode.cpp.
References checkCrossing(), DEBUGCOND, forbidsPedestriansAfter(), gDebugFlag1, getEdgesSortedByAngleAtNodeCenter(), NBEdge::getFromNode(), Named::getID(), NBEdge::getLanes(), myAllEdges, myCrossings, myDiscardAllCrossings, SVC_PEDESTRIAN, and toString().
Referenced by getDisplacementError().
hasCustomShape()
bool NBNode::hasCustomShape () const inline
return whether the shape was set by the user
Definition at line 489 of file NBNode.h.
References bezierControlPoints(), checkIsRemovable(), checkIsRemovableReporting(), computeInternalLaneShape(), computeSmoothShape(), DEG2RAD, getEdgesToJoin(), isDistrict(), isNearDistrict(), myHaveCustomPoly, and needsCont().
Referenced by GNEJunction::invalidateShape(), NWWriter_SUMO::writeJunction(), and NWWriter_XML::writeNodes().
hasIncoming()
bool NBNode::hasIncoming (const NBEdge *const e) const
Returns whether the given edge ends at this node.
Parameters
[in] e The edge
Returns
Whether the given edge is one of this node's incoming edges
Definition at line 1208 of file NBNode.cpp.
References myIncomingEdges.
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeUniqueDirectionList(), NBNodeCont::generateNodeClusters(), getControllingTLS(), NIImporter_OpenStreetMap::getNeighboringNodes(), NBNodeShapeComputer::joinSameDirectionEdges(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), and NIImporter_VISUM::parse_TurnsToSignalGroups().
hasOutgoing()
bool NBNode::hasOutgoing (const NBEdge *const e) const
Returns whether the given edge starts at this node.
Parameters
[in] e The edge
Returns
Whether the given edge is one of this node's outgoing edges
Definition at line 1214 of file NBNode.cpp.
References myOutgoingEdges.
Referenced by getControllingTLS(), isLeftMover(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), and NIImporter_VISUM::parse_TurnsToSignalGroups().
invalidateIncomingConnections()
void NBNode::invalidateIncomingConnections ()
invalidate incoming connections
Definition at line 1339 of file NBNode.cpp.
References myIncomingEdges.
Referenced by NIVissimDistrictConnection::dict_BuildDistricts(), getControllingTLS(), and GNEJunction::setAttribute().
invalidateOutgoingConnections()
void NBNode::invalidateOutgoingConnections ()
invalidate outgoing connections
Definition at line 1347 of file NBNode.cpp.
References myOutgoingEdges.
Referenced by NIVissimDistrictConnection::dict_BuildDistricts(), and getControllingTLS().
invalidateTLS()
void NBNode::invalidateTLS (NBTrafficLightLogicCont & tlCont, bool removedConnections, bool addedConnections)
causes the traffic light to be computed anew
Definition at line 347 of file NBNode.cpp.
References NBTrafficLightDefinition::addNode(), Named::getID(), NBTrafficLightDefinition::getNodes(), NBTrafficLightDefinition::getOffset(), NBTrafficLightDefinition::getType(), NBTrafficLightLogicCont::insert(), isTLControlled(), myTrafficLights, and NBTrafficLightLogicCont::removeFully().
Referenced by getControllingTLS(), NIXMLEdgesHandler::myEndElement(), and NIXMLConnectionsHandler::myStartElement().
isDistrict()
bool NBNode::isDistrict () const
check if node is a district
Definition at line 1786 of file NBNode.cpp.
References myType, and NODETYPE_DISTRICT.
Referenced by computeLogic(), hasCustomShape(), and isNearDistrict().
isLeftMover()
bool NBNode::isLeftMover (const NBEdge *const from, const NBEdge *const to) const
Computes whether the given connection is a left mover across the junction.
It is assumed, that it is a left-mover if the clockwise angle is lower than the counter-clockwise angle.
Parameters
[in] from The incoming edge (the begin of the connection)
[in] from The outgoing edge (the end of the connection)
Returns
Whether the described connection is a left-mover
Definition at line 1422 of file NBNode.cpp.
References NBEdge::getAngleAtNode(), GeomHelper::getCCWAngleDiff(), GeomHelper::getCWAngleDiff(), hasOutgoing(), NBEdge::isTurningDirectionAt(), myAllEdges, myIncomingEdges, myOutgoingEdges, and NBContHelper::nextCW().
Referenced by NBEdge::computeEdge2Edges(), and getControllingTLS().
isLongEnough()
bool NBNode::isLongEnough (NBEdge * out, double minLength) static private
check if is long enough
Definition at line 1027 of file NBNode.cpp.
References getIncomingEdges(), NBEdge::getLoadedLength(), getOutgoingEdges(), and NBEdge::getToNode().
Referenced by computeLanes2Lanes().
isNearDistrict()
bool NBNode::isNearDistrict () const
if node is near district
Definition at line 1755 of file NBNode.cpp.
References NBEdge::getFromNode(), getIncomingEdges(), getOutgoingEdges(), NBEdge::getToNode(), and isDistrict().
Referenced by computeLogic(), NBNodeCont::guessTLs(), and hasCustomShape().
isSimpleContinuation()
bool NBNode::isSimpleContinuation (bool checkLaneNumbers = true) const
check if node is a simple continuation
Definition at line 431 of file NBNode.cpp.
References NBEdge::getNumLanes(), myIncomingEdges, myOutgoingEdges, and NBContHelper::nextCW().
Referenced by NBNodeShapeComputer::compute(), NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), and NBEdgeCont::generateStreetSigns().
isTLControlled()
bool NBNode::isTLControlled () const inline
Returns whether this node is controlled by any tls.
Returns
Whether a traffic light was assigned to this node
Definition at line 297 of file NBNode.h.
References myTrafficLights.
Referenced by NIXMLConnectionsHandler::addCrossing(), NBEdge::appendTurnaround(), NBEdge::buildInnerEdges(), checkCrossing(), NBNodeCont::discardTrafficLights(), GNEJunction::drawGL(), GNEJunction::getAttribute(), NBNodeCont::guessTLs(), invalidateTLS(), GNEJunction::isValid(), NIImporter_OpenDrive::loadNetwork(), NIXMLNodesHandler::processTrafficLightDefinitions(), NBEdge::removeFromConnections(), GNETLSEditorFrame::updateDescription(), NWWriter_XML::writeNodes(), and NWWriter_DlrNavteq::writeTrafficSignals().
isTrafficLight()
bool NBNode::isTrafficLight (SumoXMLNodeType type) static
return whether the given type is a traffic light
Definition at line 2793 of file NBNode.cpp.
References NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, and NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED.
Referenced by addTrafficLight(), NGNode::buildNBNode(), NBEdge::MainDirections::MainDirections(), NBEdge::prepareEdgePriorities(), NIXMLNodesHandler::processNodeType(), reinit(), and GNEJunction::setAttribute().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
mirrorX()
void NBNode::mirrorX ()
mirror coordinates along the x-axis
Definition at line 306 of file NBNode.cpp.
References PositionVector::mirrorX(), Position::mul(), myCrossings, myPoly, myPosition, and myWalkingAreas.
Referenced by getControllingTLS().
mustBrake()
bool NBNode::mustBrake (const NBEdge *const from, const NBEdge *const to, int fromLane, int toLane, bool includePedCrossings) const
Returns the information whether the described flow must let any other flow pass.
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
[in] fromLane The lane the connection start at
[in] toLane The lane the connection ends at
[in] includePedCrossings Whether braking due to a pedestrian crossing counts
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 1355 of file NBNode.cpp.
References NBRequest::mustBrake(), and myRequest.
Referenced by getControllingTLS(), getLinkState(), NBTrafficLightDefinition::mustBrake(), and needsCont().
mustBrakeForCrossing()
bool NBNode::mustBrakeForCrossing (const NBEdge *const from, const NBEdge *const to, const Crossing & crossing) const
Returns the information whether the described flow must brake for the given crossing.
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
[in] crossing The pedestrian crossing to check
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 1369 of file NBNode.cpp.
References NBRequest::mustBrakeForCrossing().
Referenced by getControllingTLS(), and NBOwnTLDef::patchStateForCrossings().
needsCont()
bool NBNode::needsCont (const NBEdge * fromE, const NBEdge * otherFromE, const NBEdge::Connection & c, const NBEdge::Connection & otherC) const
whether an internal junction should be built at from and respect other
Definition at line 653 of file NBNode.cpp.
References foes(), NBEdge::Connection::fromLane, getDirection(), NBEdge::getJunctionPriority(), LINKDIR_LEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, LINKDIR_TURN, mustBrake(), myRequest, myTrafficLights, myType, NODETYPE_ALLWAY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, rightTurnConflict(), NBEdge::Connection::tlID, NBEdge::Connection::toEdge, and NBEdge::Connection::toLane.
Referenced by NBEdge::buildInnerEdges(), and hasCustomShape().
numCrossingsFromSumoNet()
int NBNode::numCrossingsFromSumoNet () const inline
get num of crossings from sumo net
Definition at line 616 of file NBNode.h.
References getCrossings(), and myCrossingsLoadedFromSumoNet.
numNormalConnections()
int NBNode::numNormalConnections () const
return the number of lane-to-lane connections at this junction (excluding crossings)
Definition at line 2683 of file NBNode.cpp.
References NBRequest::getSizes(), myIncomingEdges, and myRequest.
Referenced by computeLogic(), getWalkingAreas(), and NWWriter_OpenDrive::writeNetwork().
operator=()
NBNode& NBNode::operator= (const NBNode & s) private
invalidated assignment operator
reinit()
void NBNode::reinit (const Position & position, SumoXMLNodeType type, bool updateEdgeGeometries = false)
Resets initial values.
Parameters
[in] position The position of the node
[in] type The type of the node
[in] updateEdgeGeometries Whether the geometires of all connected edges shall be updated
Definition at line 273 of file NBNode.cpp.
References isTrafficLight(), myIncomingEdges, myOutgoingEdges, myPosition, myType, and removeTrafficLights().
Referenced by NBNodeCont::discardTrafficLights(), NIImporter_OpenStreetMap::insertNodeChecking(), GNEJunction::moveJunctionGeometry(), NIXMLNodesHandler::processNodeType(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), and GNEJunction::setAttribute().
remapRemoved()
void NBNode::remapRemoved (NBTrafficLightLogicCont & tc, NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) private
remap removed
Definition at line 1458 of file NBNode.cpp.
References NBConnection::getFrom(), NBConnection::getTo(), myBlockedConnections, and NBTrafficLightLogicCont::remapRemoved().
Referenced by removeSelfLoops().
removeCrossing()
void NBNode::removeCrossing (const EdgeVector & edges)
remove a pedestrian crossing from this node (identified by its edges)
Definition at line 2645 of file NBNode.cpp.
References myCrossings.
Referenced by NIXMLConnectionsHandler::addCrossing(), getProhibitions(), GNEChange_Crossing::redo(), and GNEChange_Crossing::undo().
removeDoubleEdges()
void NBNode::removeDoubleEdges ()
remove duble edges
Definition at line 1170 of file NBNode.cpp.
References myAllEdges, myIncomingEdges, and myOutgoingEdges.
Referenced by getControllingTLS(), replaceIncoming(), replaceOutgoing(), and NBEdgeCont::splitAt().
removeEdge()
void NBNode::removeEdge (NBEdge * edge, bool removeFromConnections = true)
Removes edge from this node and optionally removes connections as well.
Definition at line 1281 of file NBNode.cpp.
References myAllEdges, myIncomingEdges, myOutgoingEdges, and myTrafficLights.
Referenced by NBEdgeCont::extract(), getControllingTLS(), NBEdgeCont::insert(), NBEdge::reinit(), NBEdge::reinitNodes(), NBEdgeCont::removeUnwishedEdges(), and NBEdge::splitGeometry().
removeJoinedTrafficLights()
void NBNode::removeJoinedTrafficLights () private
remove all traffic light definitions that are part of a joined tls
Definition at line 702 of file NBNode.cpp.
References myTrafficLights.
Referenced by computeLogic().
removeSelfLoops()
int NBNode::removeSelfLoops (NBDistrictCont & dc, NBEdgeCont & ec, NBTrafficLightLogicCont & tc)
Removes edges which are both incoming and outgoing into this node.
If given, the connections to other edges participating in this node are updated
Parameters
Definition at line 378 of file NBNode.cpp.
References NBEdgeCont::erase(), NBEdge::getConnectedEdges(), Named::getID(), NBEdge::getIncomingEdges(), myIncomingEdges, myOutgoingEdges, NBEdge::remapConnections(), remapRemoved(), and WRITE_WARNING.
Referenced by getControllingTLS().
removeTrafficLight()
void NBNode::removeTrafficLight (NBTrafficLightDefinition * tlDef)
Removes the given traffic light from this node.
Definition at line 331 of file NBNode.cpp.
References myTrafficLights, and NBTrafficLightDefinition::removeNode().
Referenced by NBNodeCont::discardTrafficLights(), getKeepClear(), GNEJunction::removeTrafficLight(), removeTrafficLights(), and NBTrafficLightLogicCont::setTLControllingInformation().
removeTrafficLights()
void NBNode::removeTrafficLights ()
Removes all references to traffic lights that control this tls.
Definition at line 338 of file NBNode.cpp.
References myTrafficLights, and removeTrafficLight().
Referenced by NBNodeCont::extract(), getKeepClear(), NBNodeCont::guessTLs(), NIXMLNodesHandler::processTrafficLightDefinitions(), and reinit().
replaceIncoming() [1/2]
void NBNode::replaceIncoming (NBEdge * which, NBEdge * by, int laneOff)
Replaces occurences of the first edge within the list of incoming by the second Connections are remapped, too.
Definition at line 1102 of file NBNode.cpp.
References myAllEdges, myIncomingEdges, and replaceInConnectionProhibitions().
Referenced by getDisplacementError(), NBEdgeCont::joinSameNodeConnectingEdges(), NBNodeCont::removeUnwishedNodes(), replaceIncoming(), and NBEdgeCont::splitAt().
replaceIncoming() [2/2]
void NBNode::replaceIncoming (const EdgeVector & which, NBEdge * by)
Replaces occurences of every edge from the given list within the list of incoming by the second Connections are remapped, too.
Definition at line 1116 of file NBNode.cpp.
References myDistrict, removeDoubleEdges(), NBDistrict::replaceIncoming(), and replaceIncoming().
replaceInConnectionProhibitions()
void NBNode::replaceInConnectionProhibitions (NBEdge * which, NBEdge * by, int whichLaneOff, int byLaneOff) private
replace incoming connections prohibitions
Definition at line 1135 of file NBNode.cpp.
References myBlockedConnections, NBConnection::replaceFrom(), and NBConnection::replaceTo().
Referenced by replaceIncoming(), and replaceOutgoing().
replaceOutgoing() [1/2]
void NBNode::replaceOutgoing (NBEdge * which, NBEdge * by, int laneOff)
Replaces occurences of the first edge within the list of outgoing by the second Connections are remapped, too.
Definition at line 1066 of file NBNode.cpp.
References myAllEdges, myIncomingEdges, myOutgoingEdges, replaceInConnectionProhibitions(), and NBEdge::replaceInConnections().
Referenced by getDisplacementError(), NBEdgeCont::joinSameNodeConnectingEdges(), replaceOutgoing(), and NBEdgeCont::splitAt().
replaceOutgoing() [2/2]
void NBNode::replaceOutgoing (const EdgeVector & which, NBEdge * by)
Replaces occurences of every edge from the given list within the list of outgoing by the second Connections are remapped, too.
Definition at line 1084 of file NBNode.cpp.
References myDistrict, removeDoubleEdges(), NBDistrict::replaceOutgoing(), and replaceOutgoing().
reshiftPosition()
void NBNode::reshiftPosition (double xoff, double yoff)
Applies an offset to the node.
Parameters
[in] xoff The x-offset to apply
[in] yoff The y-offset to apply
Definition at line 299 of file NBNode.cpp.
References Position::add(), PositionVector::add(), myPoly, and myPosition.
Referenced by getControllingTLS().
rightOnRedConflict()
bool NBNode::rightOnRedConflict (int index, int foeIndex) const
whether the given index must yield to the foeIndex while turing right on a red light
Definition at line 2801 of file NBNode.cpp.
References myTrafficLights, myType, and NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED.
Referenced by NBRequest::getResponseString(), and getWalkingAreas().
rightTurnConflict()
bool NBNode::rightTurnConflict (const NBEdge * from, const NBEdge * to, int fromLane, const NBEdge * prohibitorFrom, const NBEdge * prohibitorTo, int prohibitorFromLane, bool lefthand = false) static
return whether the given laneToLane connection is a right turn which must yield to a bicycle crossings
Definition at line 1375 of file NBNode.cpp.
References GeomHelper::getCWAngleDiff(), getDirection(), NBEdge::getEndAngle(), NBEdge::getStartAngle(), NBEdge::getToNode(), NBEdge::isTurningDirectionAt(), LINKDIR_LEFT, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, and LINKDIR_STRAIGHT.
Referenced by NBEdge::buildInnerEdges(), NBOwnTLDef::correctConflicting(), getControllingTLS(), NBRequest::getFoesString(), NBRequest::getResponseString(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBRequest::mustBrake(), NBLoadedTLDef::myCompute(), and needsCont().
setCrossingTLIndices()
void NBNode::setCrossingTLIndices (const std::string & tlID, int startIndex)
set tl indices of this nodes crossing starting at the given index
Definition at line 2671 of file NBNode.cpp.
References getCrossings().
Referenced by getWalkingAreas(), and NBTrafficLightLogicCont::setTLControllingInformation().
setCustomShape()
void NBNode::setCustomShape (const PositionVector & shape)
set the junction shape
Definition at line 1732 of file NBNode.cpp.
References myAllEdges, myHaveCustomPoly, and myPoly.
Referenced by NIImporter_SUMO::addJunction(), getControllingTLS(), NIXMLNodesHandler::processNodeType(), and GNEJunction::setAttribute().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setKeepClear()
void NBNode::setKeepClear (bool keepClear) inline
set the keepClear flag
Definition at line 484 of file NBNode.h.
References myKeepClear.
Referenced by NIXMLNodesHandler::processNodeType(), and GNEJunction::setAttribute().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setPriorityJunctionPriorities()
void NBNode::setPriorityJunctionPriorities () private
sets the priorites in case of a priority junction
setRadius()
void NBNode::setRadius (double radius) inline
set the turning radius
Definition at line 479 of file NBNode.h.
References myRadius.
Referenced by NIImporter_SUMO::addJunction(), NIXMLNodesHandler::processNodeType(), and GNEJunction::setAttribute().
setRoundabout()
void NBNode::setRoundabout ()
update the type of this node as a roundabout
Definition at line 2627 of file NBNode.cpp.
References myType, NODETYPE_PRIORITY, and NODETYPE_RIGHT_BEFORE_LEFT.
Referenced by getProhibitions(), and NBEdgeCont::markRoundabouts().
shiftTLConnectionLaneIndex()
void NBNode::shiftTLConnectionLaneIndex (NBEdge * edge, int offset)
patches loaded signal plans by modifying lane indices
Definition at line 370 of file NBNode.cpp.
References myTrafficLights.
Referenced by NBEdge::addRestrictedLane(), getControllingTLS(), and NBEdge::restoreRestrictedLane().
sortEdges()
void NBNode::sortEdges (bool useNodeShape)
sort all edge containers for this node
Definition at line 2814 of file NBNode.cpp.
References PositionVector::area(), getShape(), myAllEdges, myCrossings, myIncomingEdges, myOutgoingEdges, and NBNodesEdgesSorter::swapWhenReversed().
Referenced by getWalkingAreas().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeLogic()
bool NBNode::writeLogic (OutputDevice & into, const bool checkLaneFoes) const
writes the XML-representation of the logic as a bitset-logic XML representation
Definition at line 761 of file NBNode.cpp.
References Named::myID, myRequest, and NBRequest::writeLogic().
Referenced by getControllingTLS(), and NWWriter_SUMO::writeJunction().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Friends And Related Function Documentation
GNEJunction
friend class GNEJunction friend
Definition at line 76 of file NBNode.h.
NBEdgePriorityComputer
friend class NBEdgePriorityComputer friend
Definition at line 79 of file NBNode.h.
NBNodeCont
friend class NBNodeCont friend
Definition at line 75 of file NBNode.h.
NBNodesEdgesSorter
friend class NBNodesEdgesSorter friend
Definition at line 77 of file NBNode.h.
NBNodeShapeComputer
friend class NBNodeShapeComputer friend
Definition at line 80 of file NBNode.h.
NBNodeTypeComputer
friend class NBNodeTypeComputer friend
Definition at line 78 of file NBNode.h.
Field Documentation
BACKWARD
const int NBNode::BACKWARD static
Definition at line 206 of file NBNode.h.
Referenced by buildCrossings(), NBEdge::getCCWBoundaryLine(), NBEdge::getCWBoundaryLine(), NBEdge::getFirstAllowedLaneIndex(), and NBEdge::getFirstNonPedestrianLaneIndex().
FORWARD
const int NBNode::FORWARD static
edge directions (for pedestrian related stuff)
Definition at line 205 of file NBNode.h.
Referenced by buildCrossings(), NBTrafficLightDefinition::collectEdges(), computeLanes2Lanes(), NBEdge::expandableBy(), NBEdge::getCCWBoundaryLine(), NBEdge::getCWBoundaryLine(), NBEdge::getFirstAllowedLaneIndex(), and NBEdge::getFirstNonPedestrianLaneIndex().
myAllEdges
EdgeVector NBNode::myAllEdges private
Vector of incoming and outgoing edges.
Definition at line 734 of file NBNode.h.
Referenced by addIncomingEdge(), addOutgoingEdge(), buildWalkingAreas(), NBNodeShapeComputer::compute(), NBEdgePriorityComputer::computeEdgePrioritiesSingleNode(), computeLogic(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBNodeShapeComputer::computeUniqueDirectionList(), crossingBetween(), edgesBetween(), getDirection(), getEdges(), getEdgesSortedByAngleAtNodeCenter(), getEdgesThatApproach(), guessCrossings(), isLeftMover(), NBNodeShapeComputer::joinSameDirectionEdges(), removeDoubleEdges(), removeEdge(), replaceIncoming(), replaceOutgoing(), setCustomShape(), and sortEdges().
myBlockedConnections
NBConnectionProhibits NBNode::myBlockedConnections private
The container for connection block dependencies.
Definition at line 749 of file NBNode.h.
Referenced by addSortedLinkFoes(), computeLogic(), getProhibitions(), remapRemoved(), and replaceInConnectionProhibitions().
myCrossings
std::vector<Crossing*> NBNode::myCrossings private
Vector of crossings.
Definition at line 737 of file NBNode.h.
Referenced by addCrossing(), buildCrossings(), buildCrossingsAndWalkingAreas(), checkCrossingDuplicated(), checkIsRemovableReporting(), discardAllCrossings(), getCrossing(), getCrossings(), getCrossingsIncludingInvalid(), guessCrossings(), mirrorX(), removeCrossing(), and sortEdges().
myCrossingsLoadedFromSumoNet
int NBNode::myCrossingsLoadedFromSumoNet private
number of crossings loaded from a sumo net
Definition at line 776 of file NBNode.h.
Referenced by addCrossing(), and numCrossingsFromSumoNet().
myDiscardAllCrossings
bool NBNode::myDiscardAllCrossings private
whether to discard all pedestrian crossings
Definition at line 773 of file NBNode.h.
Referenced by buildCrossings(), discardAllCrossings(), and guessCrossings().
myDisplacementError
double NBNode::myDisplacementError private
geometry error after computation of internal lane shapes
Definition at line 779 of file NBNode.h.
Referenced by bezierControlPoints(), buildInnerEdges(), and getDisplacementError().
myDistrict
NBDistrict* NBNode::myDistrict private
The district the node is the centre of.
Definition at line 752 of file NBNode.h.
Referenced by replaceIncoming(), and replaceOutgoing().
myHaveCustomPoly
bool NBNode::myHaveCustomPoly private
whether this nodes shape was set by the user
Definition at line 758 of file NBNode.h.
Referenced by computeNodeShape(), hasCustomShape(), and setCustomShape().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myIncomingEdges
EdgeVector NBNode::myIncomingEdges private
Vector of incoming edges.
Definition at line 728 of file NBNode.h.
Referenced by addIncomingEdge(), avoidOverlap(), buildInnerEdges(), checkIsRemovableReporting(), NBEdgePriorityComputer::computeEdgePrioritiesSingleNode(), computeLanes2Lanes(), computeLogic(), computeNodeShape(), NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), geometryLike(), getConnectionIndex(), getEdgesToJoin(), getEmptyDir(), getIncomingEdges(), getOppositeIncoming(), getPossiblySplittedIncoming(), hasIncoming(), invalidateIncomingConnections(), isLeftMover(), isSimpleContinuation(), numNormalConnections(), reinit(), removeDoubleEdges(), removeEdge(), removeSelfLoops(), replaceIncoming(), replaceOutgoing(), NBEdgePriorityComputer::setPriorityJunctionPriorities(), and sortEdges().
myKeepClear
bool NBNode::myKeepClear private
whether the junction area must be kept clear
Definition at line 770 of file NBNode.h.
Referenced by getKeepClear(), and setKeepClear().
myOutgoingEdges
EdgeVector NBNode::myOutgoingEdges private
Vector of outgoing edges.
Definition at line 731 of file NBNode.h.
Referenced by addOutgoingEdge(), checkIsRemovableReporting(), NBEdgePriorityComputer::computeEdgePrioritiesSingleNode(), computeLanes2Lanes(), computeLogic(), computeNodeShape(), geometryLike(), getConnectionTo(), getEdgesToJoin(), getEmptyDir(), getOutgoingEdges(), getPossiblySplittedOutgoing(), hasOutgoing(), invalidateOutgoingConnections(), isLeftMover(), isSimpleContinuation(), reinit(), removeDoubleEdges(), removeEdge(), removeSelfLoops(), replaceOutgoing(), NBEdgePriorityComputer::setPriorityJunctionPriorities(), and sortEdges().
myPoly
PositionVector NBNode::myPoly private
the (outer) shape of the junction
Definition at line 755 of file NBNode.h.
Referenced by computeNodeShape(), getCenter(), getShape(), GNEJunction::invalidateShape(), mirrorX(), reshiftPosition(), and setCustomShape().
myPosition
Position NBNode::myPosition private
The position the node lies at.
Definition at line 725 of file NBNode.h.
Referenced by computeNodeShape(), getCenter(), getEmptyDir(), getPosition(), mirrorX(), reinit(), and reshiftPosition().
myRadius
double NBNode::myRadius private
the turning radius (for all corners) at this node in m.
Definition at line 767 of file NBNode.h.
Referenced by getRadius(), and setRadius().
myRequest
NBRequest* NBNode::myRequest private
Node requests.
Definition at line 761 of file NBNode.h.
Referenced by computeLogic(), foes(), forbids(), mustBrake(), needsCont(), numNormalConnections(), writeLogic(), and ~NBNode().
myTrafficLights
std::set<NBTrafficLightDefinition*> NBNode::myTrafficLights private
traffic lights of node
Definition at line 764 of file NBNode.h.
Referenced by addTrafficLight(), checkIsRemovableReporting(), getControllingTLS(), invalidateTLS(), isTLControlled(), needsCont(), removeEdge(), removeJoinedTrafficLights(), removeTrafficLight(), removeTrafficLights(), rightOnRedConflict(), and shiftTLConnectionLaneIndex().
myType
SumoXMLNodeType NBNode::myType private
The type of the junction.
Definition at line 746 of file NBNode.h.
Referenced by addTrafficLight(), checkCrossing(), computeLanes2Lanes(), computeLogic(), NBNodeTypeComputer::computeNodeTypes(), NBNodeTypeComputer::computeSingleNodeType(), getLinkState(), getType(), isDistrict(), needsCont(), reinit(), rightOnRedConflict(), and setRoundabout().
myWalkingAreaCustomShapes
std::vector<WalkingAreaCustomShape> NBNode::myWalkingAreaCustomShapes private
Vector of custom walking areas shapes.
Definition at line 743 of file NBNode.h.
Referenced by addWalkingAreaShape(), and buildWalkingAreas().
myWalkingAreas
std::vector<WalkingArea> NBNode::myWalkingAreas private
Vector of walking areas.
Definition at line 740 of file NBNode.h.
Referenced by buildCrossingsAndWalkingAreas(), buildWalkingAreas(), getWalkingAreas(), and mirrorX().
UNSPECIFIED_RADIUS
const double NBNode::UNSPECIFIED_RADIUS = -1 static
unspecified lane width
Definition at line 209 of file NBNode.h.
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), NWWriter_SUMO::writeJunction(), and NWWriter_XML::writeNodes().
The documentation for this class was generated from the following files:
NBNode.h
NBNode.cpp