SUMO - Simulation of Urban MObility: NIImporter_RobocupRescue Class Reference
NIImporter_RobocupRescue Class Reference
Importer for networks stored in robocup rescue league format.
#include <NIImporter_RobocupRescue.h>
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given RoboCup Rescue League files.
Protected Member Functions
void loadEdges (const std::string &file)
Loads edges from the given file.
void loadNodes (const std::string &file)
Loads nodes from the given file.
NIImporter_RobocupRescue (NBNodeCont &nc, NBEdgeCont &ec)
Constructor.
~NIImporter_RobocupRescue ()
Destructor.
Protected Attributes
NBEdgeCont & myEdgeCont
The edge container to fill.
NBNodeCont & myNodeCont
The node container to fill.
Private Member Functions
NIImporter_RobocupRescue & operator= (const NIImporter_RobocupRescue &s)
Invalidated assignment operator.
Detailed Description
Importer for networks stored in robocup rescue league format.
Definition at line 54 of file NIImporter_RobocupRescue.h.
Constructor & Destructor Documentation
NIImporter_RobocupRescue()
NIImporter_RobocupRescue::NIImporter_RobocupRescue (NBNodeCont & nc, NBEdgeCont & ec) protected
Constructor.
Parameters
[in] nc The node control to fill
[in] ec The edge control to fill
Definition at line 96 of file NIImporter_RobocupRescue.cpp.
~NIImporter_RobocupRescue()
NIImporter_RobocupRescue::~NIImporter_RobocupRescue () protected
Destructor.
Definition at line 100 of file NIImporter_RobocupRescue.cpp.
Member Function Documentation
loadEdges()
void NIImporter_RobocupRescue::loadEdges (const std::string & file) protected
Loads edges from the given file.
Parameters
[in] file The file to read edges from
Definition at line 173 of file NIImporter_RobocupRescue.cpp.
References NBEdgeCont::insert(), LANESPREAD_CENTER, LANESPREAD_RIGHT, myEdgeCont, myNodeCont, NBNodeCont::retrieve(), toString(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, and WRITE_ERROR.
loadNetwork()
void NIImporter_RobocupRescue::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads content of the optionally given RoboCup Rescue League files.
If the option "robocup-dir" is set, the files contained in the folder are read.
If the option "robocup-dir" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 60 of file NIImporter_RobocupRescue.cpp.
References NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), OptionsCont::getStringVector(), FileHelpers::isReadable(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, and WRITE_ERROR.
Referenced by NILoader::load().
loadNodes()
void NIImporter_RobocupRescue::loadNodes (const std::string & file) protected
Loads nodes from the given file.
Parameters
[in] file The file to read nodes from
Definition at line 105 of file NIImporter_RobocupRescue.cpp.
References NBNodeCont::insert(), myNodeCont, toString(), NBNetBuilder::transformCoordinate(), and WRITE_MESSAGE.
operator=()
NIImporter_RobocupRescue& NIImporter_RobocupRescue::operator= (const NIImporter_RobocupRescue & s) private
Invalidated assignment operator.
Field Documentation
myEdgeCont
NBEdgeCont& NIImporter_RobocupRescue::myEdgeCont protected
The edge container to fill.
Definition at line 98 of file NIImporter_RobocupRescue.h.
Referenced by loadEdges().
myNodeCont
NBNodeCont& NIImporter_RobocupRescue::myNodeCont protected
The node container to fill.
Definition at line 95 of file NIImporter_RobocupRescue.h.
Referenced by loadEdges(), and loadNodes().
The documentation for this class was generated from the following files:
NIImporter_RobocupRescue.h
NIImporter_RobocupRescue.cpp