SUMO - Simulation of Urban MObility: NIVissimConflictArea Class Reference
NIVissimConflictArea Class Reference
A temporary storage for conflict areas imported from Vissim.
#include <NIVissimConflictArea.h>
Public Member Functions
std::string getFirstLink ()
Returns the first link of the conflic area.
int getID ()
Returns the ID of the conflic area.
std::string getSecondLink ()
Returns the second link of the conflic area.
std::string getStatus ()
Returns the priority regulation of the conflic area.
NIVissimConflictArea (int id, const std::string &link1, const std::string &link2, const std::string &status)
Constructor.
~NIVissimConflictArea ()
Destructor.
Static Public Member Functions
static void clearDict ()
Clears the dictionary.
static NIVissimConflictArea * dict_findByLinks (const std::string &link1, const std::string &link2)
static bool dictionary (int id, const std::string &link1, const std::string &link2, const std::string &status)
Adds the described item to the dictionary Builds the conflict area first.
static bool dictionary (int id, NIVissimConflictArea *ca)
Adds the conflict area to the dictionary.
static NIVissimConflictArea * dictionary (int id)
Returns the named dictionary.
static std::map< int, NIVissimConflictArea * > getConflictAreas ()
Returns the dictionary including all conflict areas.
static void setPriorityRegulation (NBEdgeCont &ec)
Sets the priority regulation according to the VISSIM conflict area data.
Private Types
typedef std::map< int, NIVissimConflictArea * > DictType
Definition of the dictionary type.
Private Attributes
int myConflictID
The id of the conflict area.
std::string myFirstLink
The first link of the conflict area.
std::string mySecondLink
The second link of the conflict area.
std::string myStatus
The priority regulation of the conflict area.
Static Private Attributes
static DictType myDict
The dictionary.
Detailed Description
A temporary storage for conflict areas imported from Vissim.
Definition at line 55 of file NIVissimConflictArea.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimConflictArea*> NIVissimConflictArea::DictType private
Definition of the dictionary type.
Definition at line 131 of file NIVissimConflictArea.h.
Constructor & Destructor Documentation
NIVissimConflictArea()
NIVissimConflictArea::NIVissimConflictArea (int id, const std::string & link1, const std::string & link2, const std::string & status)
Constructor.
Definition at line 51 of file NIVissimConflictArea.cpp.
Referenced by dictionary().
~NIVissimConflictArea()
NIVissimConflictArea::~NIVissimConflictArea ()
Destructor.
Definition at line 59 of file NIVissimConflictArea.cpp.
Member Function Documentation
clearDict()
void NIVissimConflictArea::clearDict () static
Clears the dictionary.
Definition at line 115 of file NIVissimConflictArea.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dict_findByLinks()
NIVissimConflictArea * NIVissimConflictArea::dict_findByLinks (const std::string & link1, const std::string & link2) static
Returns the conflict area from the dictionary, which defines the priority rule of the two given links
Definition at line 102 of file NIVissimConflictArea.cpp.
References myDict.
dictionary() [1/3]
bool NIVissimConflictArea::dictionary (int id, const std::string & link1, const std::string & link2, const std::string & status) static
Adds the described item to the dictionary Builds the conflict area first.
Definition at line 65 of file NIVissimConflictArea.cpp.
References dictionary(), and NIVissimConflictArea().
Referenced by dictionary(), and NIImporter_Vissim::NIVissimXMLHandler_ConflictArea::myStartElement().
dictionary() [2/3]
bool NIVissimConflictArea::dictionary (int id, NIVissimConflictArea * ca) static
Adds the conflict area to the dictionary.
Definition at line 79 of file NIVissimConflictArea.cpp.
References myDict.
dictionary() [3/3]
NIVissimConflictArea * NIVissimConflictArea::dictionary (int id) static
Returns the named dictionary.
Definition at line 91 of file NIVissimConflictArea.cpp.
References myDict.
getConflictAreas()
static std::map<int, NIVissimConflictArea*> NIVissimConflictArea::getConflictAreas () inline static
Returns the dictionary including all conflict areas.
Definition at line 87 of file NIVissimConflictArea.h.
References myDict.
getFirstLink()
std::string NIVissimConflictArea::getFirstLink () inline
Returns the first link of the conflic area.
Definition at line 97 of file NIVissimConflictArea.h.
References myFirstLink.
Referenced by setPriorityRegulation().
getID()
int NIVissimConflictArea::getID () inline
Returns the ID of the conflic area.
Definition at line 92 of file NIVissimConflictArea.h.
References myConflictID.
getSecondLink()
std::string NIVissimConflictArea::getSecondLink () inline
Returns the second link of the conflic area.
Definition at line 102 of file NIVissimConflictArea.h.
References mySecondLink.
Referenced by setPriorityRegulation().
getStatus()
std::string NIVissimConflictArea::getStatus () inline
Returns the priority regulation of the conflic area.
Definition at line 107 of file NIVissimConflictArea.h.
References myStatus, and setPriorityRegulation().
Referenced by setPriorityRegulation().
setPriorityRegulation()
void NIVissimConflictArea::setPriorityRegulation (NBEdgeCont & ec) static
Sets the priority regulation according to the VISSIM conflict area data.
Definition at line 124 of file NIVissimConflictArea.cpp.
References TplConvert::_str2int(), NBNode::addSortedLinkFoes(), NIVissimConnection::dictionary(), getFirstLink(), NIVissimConnection::getFromEdgeID(), getSecondLink(), getStatus(), NIVissimConnection::getToEdgeID(), myDict, and NBEdgeCont::retrievePossiblySplit().
Referenced by getStatus(), and NIImporter_Vissim::postLoadBuild().
Field Documentation
myConflictID
int NIVissimConflictArea::myConflictID private
The id of the conflict area.
Definition at line 118 of file NIVissimConflictArea.h.
Referenced by getID().
myDict
NIVissimConflictArea::DictType NIVissimConflictArea::myDict static private
The dictionary.
Definition at line 134 of file NIVissimConflictArea.h.
Referenced by clearDict(), dict_findByLinks(), dictionary(), getConflictAreas(), and setPriorityRegulation().
myFirstLink
std::string NIVissimConflictArea::myFirstLink private
The first link of the conflict area.
Definition at line 121 of file NIVissimConflictArea.h.
Referenced by getFirstLink().
mySecondLink
std::string NIVissimConflictArea::mySecondLink private
The second link of the conflict area.
Definition at line 124 of file NIVissimConflictArea.h.
Referenced by getSecondLink().
myStatus
std::string NIVissimConflictArea::myStatus private
The priority regulation of the conflict area.
Definition at line 127 of file NIVissimConflictArea.h.
Referenced by getStatus().
The documentation for this class was generated from the following files:
NIVissimConflictArea.h
NIVissimConflictArea.cpp