SUMO - Simulation of Urban MObility: MSTransportable::Stage Class Reference
MSTransportable::Stage Class Reference abstract
#include <MSTransportable.h>
Public Member Functions
virtual void abort (MSTransportable *)
abort this stage (TraCI)
virtual void beginEventOutput (const MSTransportable &transportable, SUMOTime t, OutputDevice &os) const =0
Called for writing the events output (begin of an action)
virtual void endEventOutput (const MSTransportable &transportable, SUMOTime t, OutputDevice &os) const =0
Called for writing the events output (end of an action)
virtual double getAngle (SUMOTime now) const =0
returns the angle of the transportable
double getArrivalPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
virtual const MSEdge * getEdge () const =0
Returns the current edge.
double getEdgeAngle (const MSEdge *e, double at) const
get angle of the edge at a certain position
virtual double getEdgePos (SUMOTime now) const =0
Position getEdgePosition (const MSEdge *e, double at, double offset) const
get position on edge e at length at with orthogonal offset
virtual ConstMSEdgeVector getEdges () const =0
the edges of the current stage
virtual const MSEdge * getFromEdge () const =0
Position getLanePosition (const MSLane *lane, double at, double offset) const
get position on lane at length at with orthogonal offset
virtual Position getPosition (SUMOTime now) const =0
returns the position of the transportable
virtual double getSpeed () const =0
the speed of the transportable
virtual std::string getStageDescription () const =0
return string representation of the current stage
StageType getStageType () const
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
virtual SUMOTime getWaitingTime (SUMOTime now) const =0
the time this transportable spent waiting
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
virtual void proceed (MSNet *net, MSTransportable *transportable, SUMOTime now, Stage *previous)=0
proceeds to this stage
virtual void routeOutput (OutputDevice &os) const =0
Called on writing vehroute output.
virtual void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void setSpeed (double)
sets the walking speed (ignored in other stages)
Stage (const MSEdge &destination, MSStoppingPlace *toStop, const double arrivalPos, StageType type)
constructor
virtual void tripInfoOutput (OutputDevice &os, MSTransportable *transportable) const =0
Called on writing tripinfo output.
virtual ~Stage ()
destructor
Protected Attributes
double myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
Stage & operator= (const Stage &)
Invalidated assignment operator.
Stage (const Stage &)
Invalidated copy constructor.
Detailed Description
The "abstract" class for a single stage of a movement Contains the destination of the current movement step
Definition at line 75 of file MSTransportable.h.
Constructor & Destructor Documentation
Stage() [1/2]
MSTransportable::Stage::Stage (const MSEdge & destination, MSStoppingPlace * toStop, const double arrivalPos, StageType type)
constructor
Definition at line 54 of file MSTransportable.cpp.
~Stage()
MSTransportable::Stage::~Stage () virtual
destructor
Definition at line 57 of file MSTransportable.cpp.
Stage() [2/2]
MSTransportable::Stage::Stage (const Stage &) private
Invalidated copy constructor.
Member Function Documentation
abort()
virtual void MSTransportable::Stage::abort (MSTransportable *) inline virtual
abort this stage (TraCI)
Reimplemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, and MSPerson::MSPersonStage_Walking.
Definition at line 118 of file MSTransportable.h.
beginEventOutput()
virtual void MSTransportable::Stage::beginEventOutput (const MSTransportable & transportable, SUMOTime t, OutputDevice & os) const pure virtual
Called for writing the events output (begin of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
endEventOutput()
virtual void MSTransportable::Stage::endEventOutput (const MSTransportable & transportable, SUMOTime t, OutputDevice & os) const pure virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
getAngle()
virtual double MSTransportable::Stage::getAngle (SUMOTime now) const pure virtual
returns the angle of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), and MSTransportable::getFromEdge().
getArrivalPos()
double MSTransportable::Stage::getArrivalPos () const inline
Definition at line 91 of file MSTransportable.h.
References getAngle(), getEdge(), getEdgePos(), getFromEdge(), getPosition(), and myArrivalPos.
Referenced by MSRouteHandler::parseWalkPositions().
getDestination()
const MSEdge & MSTransportable::Stage::getDestination () const
returns the destination edge
Definition at line 60 of file MSTransportable.cpp.
References myDestination.
Referenced by MSTransportable::Stage_Waiting::getEdges(), MSTransportable::Stage_Driving::getEdges(), MSPModel_Striping::moveInDirectionOnLane(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), and MSTransportable::Stage_Waiting::routeOutput().
getDestinationStop()
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline
returns the destination stop (if any)
Definition at line 87 of file MSTransportable.h.
References myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
getEdge()
virtual const MSEdge* MSTransportable::Stage::getEdge () const pure virtual
Returns the current edge.
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Driving::proceed(), MSContainer::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSTransportable::Stage_Waiting::proceed(), and MSPerson::proceed().
getEdgeAngle()
double MSTransportable::Stage::getEdgeAngle (const MSEdge * e, double at) const
get angle of the edge at a certain position
Definition at line 93 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), and getVehicle().
getEdgePos()
virtual double MSTransportable::Stage::getEdgePos (SUMOTime now) const pure virtual
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), MSTransportable::getFromEdge(), MSEdge::transportable_by_position_sorter::operator()(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Driving::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
getEdgePosition()
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, double at, double offset) const
get position on edge e at length at with orthogonal offset
Definition at line 83 of file MSTransportable.cpp.
References getLanePosition(), and MSEdge::getLanes().
Referenced by MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), and getVehicle().
getEdges()
virtual ConstMSEdgeVector MSTransportable::Stage::getEdges () const pure virtual
the edges of the current stage
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::getEdges(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
getFromEdge()
virtual const MSEdge* MSTransportable::Stage::getFromEdge () const pure virtual
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos().
getLanePosition()
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, double at, double offset) const
get position on lane at length at with orthogonal offset
Definition at line 88 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::positionAtOffset().
Referenced by CState::computeTranshipTime(), getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and getVehicle().
getPosition()
virtual Position MSTransportable::Stage::getPosition (SUMOTime now) const pure virtual
returns the position of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), and MSTransportable::getFromEdge().
getSpeed()
virtual double MSTransportable::Stage::getSpeed () const pure virtual
the speed of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::getFromEdge(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
getStageDescription()
virtual std::string MSTransportable::Stage::getStageDescription () const pure virtual
return string representation of the current stage
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by getStageType().
getStageType()
StageType MSTransportable::Stage::getStageType () const inline
Definition at line 107 of file MSTransportable.h.
References getStageDescription(), myType, and proceed().
Referenced by MSTransportable::getStageType().
getVehicle()
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 138 of file MSTransportable.h.
References beginEventOutput(), endEventOutput(), getEdgeAngle(), getEdgePosition(), getEdges(), getLanePosition(), getSpeed(), getWaitingTime(), routeOutput(), and tripInfoOutput().
getWaitingTime()
virtual SUMOTime MSTransportable::Stage::getWaitingTime (SUMOTime now) const pure virtual
the time this transportable spent waiting
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
isWaiting4Vehicle()
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 133 of file MSTransportable.h.
isWaitingFor()
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 78 of file MSTransportable.cpp.
Referenced by setSpeed().
operator=()
Stage& MSTransportable::Stage::operator= (const Stage &) private
Invalidated assignment operator.
proceed()
virtual void MSTransportable::Stage::proceed (MSNet * net, MSTransportable * transportable, SUMOTime now, Stage * previous) pure virtual
proceeds to this stage
Implemented in MSTransportable::Stage_Waiting, MSPerson::MSPersonStage_Driving, MSContainer::MSContainerStage_Tranship, MSContainer::MSContainerStage_Driving, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), and getStageType().
routeOutput()
virtual void MSTransportable::Stage::routeOutput (OutputDevice & os) const pure virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Waiting, MSPerson::MSPersonStage_Driving, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::getEdges(), MSTransportable::Stage_Waiting::getStageDescription(), and getVehicle().
setArrived()
void MSTransportable::Stage::setArrived (SUMOTime now) virtual
logs end of the step
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 73 of file MSTransportable.cpp.
References myArrived.
Referenced by MSTransportable::Stage_Driving::getVehicle(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::Stage_Driving::setArrived(), and setSpeed().
setDeparted()
void MSTransportable::Stage::setDeparted (SUMOTime now)
logs end of the step
Definition at line 66 of file MSTransportable.cpp.
References myDeparted.
Referenced by MSTransportable::getVehicleType(), and setSpeed().
setSpeed()
virtual void MSTransportable::Stage::setSpeed (double) inline virtual
sets the walking speed (ignored in other stages)
Reimplemented in MSPerson::MSPersonStage_Walking.
Definition at line 121 of file MSTransportable.h.
References isWaitingFor(), setArrived(), and setDeparted().
Referenced by MSTransportable::getVehicle().
tripInfoOutput()
virtual void MSTransportable::Stage::tripInfoOutput (OutputDevice & os, MSTransportable * transportable) const pure virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Waiting, MSPerson::MSPersonStage_Driving, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::getEdges(), MSTransportable::Stage_Waiting::getStageDescription(), and getVehicle().
Field Documentation
myArrivalPos
double MSTransportable::Stage::myArrivalPos protected
the position at which we want to arrive
Definition at line 192 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getArrivalPos(), MSTransportable::Stage_Waiting::getEdgePos(), MSTransportable::Stage_Waiting::getPosition(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Walking::walkDistance().
myArrived
SUMOTime MSTransportable::Stage::myArrived protected
the time at which this stage ended
Definition at line 198 of file MSTransportable.h.
Referenced by setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
myDeparted
SUMOTime MSTransportable::Stage::myDeparted protected
the time at which this stage started
Definition at line 195 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getWaitingTime(), MSTransportable::Stage_Driving::getWaitingTime(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), MSTransportable::Stage_Waiting::proceed(), setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
myDestination
const MSEdge& MSTransportable::Stage::myDestination protected
the next edge to reach by getting transported
Definition at line 186 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), getDestination(), MSTransportable::Stage_Waiting::getEdge(), MSTransportable::Stage_Waiting::getFromEdge(), and MSTransportable::Stage_Waiting::getPosition().
myDestinationStop
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected
the stop to reach by getting transported (if any)
Definition at line 189 of file MSTransportable.h.
Referenced by getDestinationStop(), MSTransportable::Stage_Driving::getWaitingDescription(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSPerson::MSPersonStage_Walking::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
myType
StageType MSTransportable::Stage::myType protected
The type of this stage.
Definition at line 201 of file MSTransportable.h.
Referenced by getStageType(), MSTransportable::Stage_Waiting::routeOutput(), and MSTransportable::Stage_Waiting::tripInfoOutput().
The documentation for this class was generated from the following files:
MSTransportable.h
MSTransportable.cpp