SUMO - Simulation of Urban MObility: NGFrame Class Reference
NGFrame Class Reference
Sets and checks options for netgen.
#include <NGFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid.
static void fillOptions ()
Inserts options used by the network generator.
Detailed Description
Sets and checks options for netgen.
Definition at line 40 of file NGFrame.h.
Member Function Documentation
checkOptions()
bool NGFrame::checkOptions () static
Checks set options from the OptionsCont-singleton for being valid.
Returns
Whether needed (netgen) options are set and have proper values
Definition at line 189 of file NGFrame.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), NODETYPE_ALLWAY_STOP, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED, NODETYPE_ZIPPER, toString(), and WRITE_ERROR.
Referenced by checkOptions().
fillOptions()
void NGFrame::fillOptions () static
Inserts options used by the network generator.
Definition at line 46 of file NGFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), DEG2RAD, OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by fillOptions().
The documentation for this class was generated from the following files:
NGFrame.h
NGFrame.cpp