SUMO - Simulation of Urban MObility: SUMOVTypeParameter Class Reference
SUMOVTypeParameter Class Reference
Structure representing possible vehicle parameter.
#include <SUMOVTypeParameter.h>
Public Types
typedef std::map< SumoXMLAttr, std::string > SubParams
sub-model parameters
Public Member Functions
void clearParameter ()
Clears the parameter map.
double getCFParam (const SumoXMLAttr attr, const double defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
std::string getCFParamString (const SumoXMLAttr attr, const std::string defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
double getJMParam (const SumoXMLAttr attr, const double defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
double getLCParam (const SumoXMLAttr attr, const double defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
SUMOVTypeParameter (const std::string &vtid, const SUMOVehicleClass vc=SVC_IGNORING)
Constructor.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void validateCFParameter () const
Validates stored car-following parameter.
bool wasSet (int what) const
Returns whether the given parameter was set.
void write (OutputDevice &dev) const
Writes the vtype.
void writeParams (OutputDevice &out) const
Static Public Member Functions
static const SUMOVTypeParameter & getDefault ()
return the default parameters, this is a function due to the http://www.parashift.com/c++-faq/static-init-order.html
static double getDefaultAccel (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default acceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
static double getDefaultDecel (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default deceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
static double getDefaultEmergencyDecel (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default emergency deceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
static double getDefaultImperfection (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default driver's imperfection (sigma or epsilon in Krauss' model) for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Data Fields
SUMOTime actionStepLength
The vehicle type's default actionStepLength [ms], i.e. the interval between two control actions. The default value of 0ms. induces the value to be traced from MSGlobals::gActionStepLength.
SUMOTime boardingDuration
The time a person needs to board the vehicle.
SumoXMLTag cfModel
The enum-representation of the car-following model to use.
SubParams cfParameter
Car-following parameter.
RGBColor color
The color.
int containerCapacity
The container capacity of the vehicle.
double defaultProbability
The probability when being added to a distribution without an explicit probability.
SUMOEmissionClass emissionClass
The emission class of this vehicle.
std::string id
The vehicle type's id.
double impatience
The vehicle's impatience (willingness to obstruct others)
SubParams jmParameter
Junction-model parameter.
LateralAlignment latAlignment
The vehicles desired lateral alignment.
LaneChangeModel lcModel
The lane-change model to use.
SubParams lcParameter
Lane-changing parameter.
double length
The physical vehicle length.
SUMOTime loadingDuration
The time a container needs to get loaded on the vehicle.
double maxSpeed
The vehicle type's maximum speed [m/s].
double maxSpeedLat
The vehicle type's maximum lateral speed [m/s].
double minGap
This class' free space in front of the vehicle itself.
double minGapLat
The vehicle type's minimum lateral gap [m].
bool onlyReferenced
Information whether this is a type-stub, being only referenced but not defined (needed by routers)
int parametersSet
Information for the router which parameter were set.
int personCapacity
The person capacity of the vehicle.
bool saved
Information whether this type was already saved (needed by routers)
Distribution_Parameterized speedFactor
The factor by which the maximum speed may deviate from the allowed max speed on the street.
SUMOVehicleClass vehicleClass
The vehicle's class.
Values for drawing this class' vehicles
double width
This class' width.
double height
This class' height.
SUMOVehicleShape shape
This class' shape.
std::string osgFile
3D model file for this class
std::string imgFile
Image file for this class.
Detailed Description
Structure representing possible vehicle parameter.
Definition at line 87 of file SUMOVTypeParameter.h.
Member Typedef Documentation
SubParams
typedef std::map<SumoXMLAttr, std::string> SUMOVTypeParameter::SubParams
sub-model parameters
Definition at line 203 of file SUMOVTypeParameter.h.
Constructor & Destructor Documentation
SUMOVTypeParameter()
SUMOVTypeParameter::SUMOVTypeParameter (const std::string & vtid, const SUMOVehicleClass vc = SVC_IGNORING)
Constructor.
Initialises the structure with default values
Definition at line 48 of file SUMOVTypeParameter.cpp.
References containerCapacity, DEFAULT_PEDESTRIAN_SPEED, emissionClass, EMPREFIX, PollutantsInterface::getClassByName(), height, length, maxSpeed, minGap, osgFile, personCapacity, shape, SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_DELIVERY, SVC_E_VEHICLE, SVC_EMERGENCY, SVC_MOPED, SVC_MOTORCYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, SVC_TRUCK, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_DELIVERY, SVS_E_VEHICLE, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_SEMITRAILER, and width.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
getCFParam()
double SUMOVTypeParameter::getCFParam (const SumoXMLAttr attr, const double defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
Parameters
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns
The named value from the map or the default if it does not exist there
Definition at line 311 of file SUMOVTypeParameter.cpp.
References TplConvert::_str2double(), and cfParameter.
Referenced by MSVehicleType::build(), ROEdge::getEmissionEffort(), and wasSet().
getCFParamString()
std::string SUMOVTypeParameter::getCFParamString (const SumoXMLAttr attr, const std::string defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
Parameters
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns
The named value from the map or the default if it does not exist there
Definition at line 321 of file SUMOVTypeParameter.cpp.
References cfParameter.
Referenced by MSVehicleType::build(), and wasSet().
getDefault()
const SUMOVTypeParameter & SUMOVTypeParameter::getDefault () static
return the default parameters, this is a function due to the http://www.parashift.com/c++-faq/static-init-order.html
Definition at line 470 of file SUMOVTypeParameter.cpp.
Referenced by libsumo::Lane::getLinks().
getDefaultAccel()
double SUMOVTypeParameter::getDefaultAccel (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default acceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the acceleration in m/s^2
Definition at line 349 of file SUMOVTypeParameter.cpp.
References SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_MOPED, SVC_MOTORCYCLE, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, and SVC_TRUCK.
Referenced by MSVehicleType::build(), and ROEdge::getEmissionEffort().
getDefaultDecel()
double SUMOVTypeParameter::getDefaultDecel (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default deceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the deceleration in m/s^2
Definition at line 384 of file SUMOVTypeParameter.cpp.
References SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_MOPED, SVC_MOTORCYCLE, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, and SVC_TRUCK.
Referenced by MSVehicleType::build(), and libsumo::Lane::getLinks().
getDefaultEmergencyDecel()
double SUMOVTypeParameter::getDefaultEmergencyDecel (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default emergency deceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the deceleration in m/s^2
Definition at line 419 of file SUMOVTypeParameter.cpp.
References SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_MOPED, SVC_MOTORCYCLE, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, and SVC_TRUCK.
getDefaultImperfection()
double SUMOVTypeParameter::getDefaultImperfection (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default driver's imperfection (sigma or epsilon in Krauss' model) for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the imperfection as a value between 0 and 1
Definition at line 455 of file SUMOVTypeParameter.cpp.
References SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, and SVC_TRAM.
Referenced by MSVehicleType::build(), and ROEdge::getEmissionEffort().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getJMParam()
double SUMOVTypeParameter::getJMParam (const SumoXMLAttr attr, const double defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
Parameters
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns
The named value from the map or the default if it does not exist there
Definition at line 340 of file SUMOVTypeParameter.cpp.
References TplConvert::_str2double(), and jmParameter.
Referenced by MSLink::blockedAtTime(), MSLink::blockedByFoe(), MSLink::getLeaderInfo(), MSPModel_Striping::PState::ignoreRed(), MSVehicle::ignoreRed(), MSVehicle::keepClear(), MSCFModel_Krauss::moveHelper(), and wasSet().
getLCParam()
double SUMOVTypeParameter::getLCParam (const SumoXMLAttr attr, const double defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
Parameters
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns
The named value from the map or the default if it does not exist there
Definition at line 330 of file SUMOVTypeParameter.cpp.
References TplConvert::_str2double(), and lcParameter.
Referenced by wasSet().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
validateCFParameter()
void SUMOVTypeParameter::validateCFParameter () const
Validates stored car-following parameter.
Referenced by wasSet().
wasSet()
bool SUMOVTypeParameter::wasSet (int what) const inline
Returns whether the given parameter was set.
Parameters
[in] what The parameter which one asks for
Returns
Whether the given parameter was set
Definition at line 100 of file SUMOVTypeParameter.h.
References getCFParam(), getCFParamString(), getJMParam(), getLCParam(), parametersSet, validateCFParameter(), and write().
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::check(), MSVehicleType::MSVehicleType(), and write().
write()
void SUMOVTypeParameter::write (OutputDevice & dev) const
Writes the vtype.
Parameters
[in,out] dev The device to write into
Exceptions
IOError not yet implemented
Definition at line 213 of file SUMOVTypeParameter.cpp.
References actionStepLength, boardingDuration, SUMOXMLDefinitions::CarFollowModels, cfModel, cfParameter, OutputDevice::closeTag(), color, containerCapacity, defaultProbability, emissionClass, PollutantsInterface::getName(), getVehicleShapeName(), height, imgFile, impatience, jmParameter, latAlignment, lcModel, lcParameter, length, loadingDuration, maxSpeed, maxSpeedLat, minGap, minGapLat, onlyReferenced, OutputDevice::openTag(), osgFile, personCapacity, shape, speedFactor, STEPS2TIME, SUMO_ATTR_ACTIONSTEPLENGTH, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_OSGFILE, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PROB, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_VCLASS, SUMO_ATTR_WIDTH, SUMO_TAG_VTYPE, toString(), vehicleClass, VTYPEPARS_ACTIONSTEPLENGTH_SET, VTYPEPARS_BOARDING_DURATION, VTYPEPARS_CAR_FOLLOW_MODEL, VTYPEPARS_COLOR_SET, VTYPEPARS_CONTAINER_CAPACITY, VTYPEPARS_EMISSIONCLASS_SET, VTYPEPARS_HEIGHT_SET, VTYPEPARS_IMGFILE_SET, VTYPEPARS_IMPATIENCE_SET, VTYPEPARS_LANE_CHANGE_MODEL_SET, VTYPEPARS_LATALIGNMENT_SET, VTYPEPARS_LENGTH_SET, VTYPEPARS_LOADING_DURATION, VTYPEPARS_MAXSPEED_LAT_SET, VTYPEPARS_MAXSPEED_SET, VTYPEPARS_MINGAP_LAT_SET, VTYPEPARS_MINGAP_SET, VTYPEPARS_OSGFILE_SET, VTYPEPARS_PERSON_CAPACITY, VTYPEPARS_PROBABILITY_SET, VTYPEPARS_SHAPE_SET, VTYPEPARS_SPEEDFACTOR_SET, VTYPEPARS_VEHICLECLASS_SET, VTYPEPARS_WIDTH_SET, wasSet(), width, OutputDevice::writeAttr(), and Parameterised::writeParams().
Referenced by ROVehicle::saveAsXML(), ROPerson::saveAsXML(), wasSet(), and RODFDetectorCon::writeEmitters().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
actionStepLength
SUMOTime SUMOVTypeParameter::actionStepLength
The vehicle type's default actionStepLength [ms], i.e. the interval between two control actions. The default value of 0ms. induces the value to be traced from MSGlobals::gActionStepLength.
Definition at line 157 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::check(), MSVehicleType::getActionStepLength(), MSVehicleType::MSVehicleType(), MSVehicleType::setActionStepLength(), and write().
boardingDuration
SUMOTime SUMOVTypeParameter::boardingDuration
The time a person needs to board the vehicle.
Definition at line 175 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getBoardingDuration(), and write().
cfModel
SumoXMLTag SUMOVTypeParameter::cfModel
The enum-representation of the car-following model to use.
Definition at line 200 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::build(), SUMOVehicleParserHelper::parseVTypeEmbedded(), and write().
cfParameter
SubParams SUMOVTypeParameter::cfParameter
Car-following parameter.
Definition at line 205 of file SUMOVTypeParameter.h.
Referenced by getCFParam(), getCFParamString(), SUMOVehicleParserHelper::parseVTypeEmbedded(), and write().
color
RGBColor SUMOVTypeParameter::color
The color.
Definition at line 165 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getColor(), MSVehicleType::setColor(), and write().
containerCapacity
int SUMOVTypeParameter::containerCapacity
The container capacity of the vehicle.
Definition at line 173 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getContainerCapacity(), SUMOVTypeParameter(), and write().
defaultProbability
double SUMOVTypeParameter::defaultProbability
The probability when being added to a distribution without an explicit probability.
Definition at line 159 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getDefaultProbability(), RORouteHandler::myEndElement(), MSVehicleType::setDefaultProbability(), and write().
emissionClass
SUMOEmissionClass SUMOVTypeParameter::emissionClass
The emission class of this vehicle.
Definition at line 163 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getEmissionClass(), ROEdge::getEmissionEffort(), ROEdge::getNoiseEffort(), MSVehicleType::setEmissionClass(), SUMOVTypeParameter(), and write().
height
double SUMOVTypeParameter::height
This class' height.
Definition at line 186 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getHeight(), MSVehicleType::setHeight(), SUMOVTypeParameter(), and write().
id
std::string SUMOVTypeParameter::id
The vehicle type's id.
Definition at line 147 of file SUMOVTypeParameter.h.
Referenced by RONet::addVehicleType(), SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::build(), RONet::checkFlows(), RORouteHandler::closeVehicle(), MSVehicleType::duplicateType(), MSVehicleType::getID(), SUMORouteHandler::myStartElement(), SUMOVehicleParserHelper::parseJMParams(), SUMOVehicleParserHelper::parseLCParams(), SUMOVehicleParserHelper::parseVTypeEmbedded(), and RONet::RONet().
imgFile
std::string SUMOVTypeParameter::imgFile
Image file for this class.
Definition at line 195 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getImgFile(), and write().
impatience
double SUMOVTypeParameter::impatience
The vehicle's impatience (willingness to obstruct others)
Definition at line 169 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getImpatience(), MSVehicleType::setImpatience(), and write().
jmParameter
SubParams SUMOVTypeParameter::jmParameter
Junction-model parameter.
Definition at line 209 of file SUMOVTypeParameter.h.
Referenced by getJMParam(), SUMOVehicleParserHelper::parseJMParams(), and write().
latAlignment
LateralAlignment SUMOVTypeParameter::latAlignment
The vehicles desired lateral alignment.
Definition at line 217 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getPreferredLateralAlignment(), MSVehicleType::setPreferredLateralAlignment(), and write().
lcModel
LaneChangeModel SUMOVTypeParameter::lcModel
The lane-change model to use.
Definition at line 212 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLaneChangeModel(), and write().
lcParameter
SubParams SUMOVTypeParameter::lcParameter
Lane-changing parameter.
Definition at line 207 of file SUMOVTypeParameter.h.
Referenced by getLCParam(), SUMOVehicleParserHelper::parseLCParams(), and write().
length
double SUMOVTypeParameter::length
The physical vehicle length.
Definition at line 150 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSVehicleType::setLength(), SUMOVTypeParameter(), and write().
loadingDuration
SUMOTime SUMOVTypeParameter::loadingDuration
The time a container needs to get loaded on the vehicle.
Definition at line 177 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLoadingDuration(), and write().
maxSpeed
double SUMOVTypeParameter::maxSpeed
The vehicle type's maximum speed [m/s].
Definition at line 154 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), ROPerson::computeIntermodal(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), RORoutable::getMaxSpeed(), MSVehicleType::getMaxSpeed(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), MSVehicleType::setMaxSpeed(), SUMOVTypeParameter(), and write().
maxSpeedLat
double SUMOVTypeParameter::maxSpeedLat
The vehicle type's maximum lateral speed [m/s].
Definition at line 215 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getMaxSpeedLat(), MSVehicleType::setMaxSpeedLat(), and write().
minGap
double SUMOVTypeParameter::minGap
This class' free space in front of the vehicle itself.
Definition at line 152 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLengthWithGap(), MSVehicleType::getMinGap(), MSVehicleType::setMinGap(), SUMOVTypeParameter(), and write().
minGapLat
double SUMOVTypeParameter::minGapLat
The vehicle type's minimum lateral gap [m].
Definition at line 219 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getMinGapLat(), MSVehicleType::setMinGapLat(), and write().
onlyReferenced
bool SUMOVTypeParameter::onlyReferenced mutable
Information whether this is a type-stub, being only referenced but not defined (needed by routers)
Definition at line 229 of file SUMOVTypeParameter.h.
Referenced by RONet::RONet(), and write().
osgFile
std::string SUMOVTypeParameter::osgFile
3D model file for this class
Definition at line 192 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getOSGFile(), SUMOVTypeParameter(), and write().
parametersSet
int SUMOVTypeParameter::parametersSet
Information for the router which parameter were set.
Definition at line 222 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleControl::MSVehicleControl(), SUMOVehicleParserHelper::parseVTypeEmbedded(), RONet::RONet(), MSVehicleType::setActionStepLength(), MSVehicleType::setColor(), MSVehicleType::setDefaultProbability(), MSVehicleType::setEmissionClass(), MSVehicleType::setHeight(), MSVehicleType::setImpatience(), MSVehicleType::setLength(), MSVehicleType::setMaxSpeed(), MSVehicleType::setMaxSpeedLat(), MSVehicleType::setMinGap(), MSVehicleType::setMinGapLat(), MSVehicleType::setPreferredLateralAlignment(), MSVehicleType::setShape(), MSVehicleType::setSpeedDeviation(), MSVehicleType::setSpeedFactor(), RODFDetectorCon::setSpeedFactorAndDev(), MSVehicleType::setVClass(), MSVehicleType::setWidth(), MSVehicleType::wasSet(), wasSet(), and RODFDetectorCon::writeEmitters().
personCapacity
int SUMOVTypeParameter::personCapacity
The person capacity of the vehicle.
Definition at line 171 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getPersonCapacity(), SUMOVTypeParameter(), and write().
saved
bool SUMOVTypeParameter::saved mutable
Information whether this type was already saved (needed by routers)
Definition at line 226 of file SUMOVTypeParameter.h.
Referenced by ROVehicle::saveAsXML(), and ROPerson::saveAsXML().
shape
SUMOVehicleShape SUMOVTypeParameter::shape
This class' shape.
Definition at line 189 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getGuiShape(), MSVehicleType::setShape(), SUMOVTypeParameter(), and write().
speedFactor
Distribution_Parameterized SUMOVTypeParameter::speedFactor
The factor by which the maximum speed may deviate from the allowed max speed on the street.
Definition at line 161 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::computeChosenSpeedDeviation(), ROVehicle::getChosenSpeedFactor(), MSVehicleType::getSpeedFactor(), ROEdge::getTravelTime(), MSVehicleType::setSpeedDeviation(), MSVehicleType::setSpeedFactor(), RODFDetectorCon::setSpeedFactorAndDev(), and write().
vehicleClass
SUMOVehicleClass SUMOVTypeParameter::vehicleClass
The vehicle's class.
Definition at line 167 of file SUMOVTypeParameter.h.
Referenced by MSVehicleType::build(), RORouteHandler::closeVehicle(), ROEdge::getEmissionEffort(), RORoutable::getVClass(), MSBaseVehicle::getVClass(), MSVehicleType::getVehicleClass(), MSVehicleType::setVClass(), and write().
width
double SUMOVTypeParameter::width
This class' width.
Definition at line 183 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getWidth(), MSVehicleType::setWidth(), SUMOVTypeParameter(), and write().
The documentation for this class was generated from the following files:
SUMOVTypeParameter.h
SUMOVTypeParameter.cpp