SUMO - Simulation of Urban MObility: PHEMlightdll::Helpers Class Reference
PHEMlightdll::Helpers Class Reference
#include <Helpers.h>
Public Member Functions
const std::string & getCommentPrefix () const
const std::string & geteClass () const
const std::string & getErrMsg () const
const std::string & getgClass () const
const std::string & getPHEMDataV () const
const std::string & getsClass () const
const std::string & gettClass () const
const std::string & getvClass () const
bool setclass (const std::string &VEH)
void setCommentPrefix (const std::string &value)
void seteClass (const std::string &value)
void setErrMsg (const std::string &value)
void setgClass (const std::string &value)
void setPHEMDataV (const std::string &value)
void setsClass (const std::string &value)
void settClass (const std::string &value)
void setvClass (const std::string &value)
Private Member Functions
bool geteclass (const std::string &VEH)
bool getsclass (const std::string &VEH)
bool gettclass (const std::string &VEH)
bool getvclass (const std::string &VEH)
Private Attributes
std::string _Class
std::string _commentPrefix
std::string _eClass
std::string _ErrMsg
std::string _PHEMDataV
std::string _sClass
std::string _tClass
std::string _vClass
Detailed Description
Definition at line 31 of file Helpers.h.
Member Function Documentation
getCommentPrefix()
const std::string & PHEMlightdll::Helpers::getCommentPrefix () const
Definition at line 78 of file Helpers.cpp.
References _commentPrefix.
Referenced by PHEMlightdll::CEPHandler::ReadVehicleFile().
geteClass()
const std::string & PHEMlightdll::Helpers::geteClass () const
Definition at line 38 of file Helpers.cpp.
References _eClass.
Referenced by setclass().
geteclass()
bool PHEMlightdll::Helpers::geteclass (const std::string & VEH) private
Definition at line 216 of file Helpers.cpp.
References _eClass, _ErrMsg, PHEMlightdll::Constants::strBEV, and PHEMlightdll::Constants::strEU.
Referenced by setclass().
getErrMsg()
const std::string & PHEMlightdll::Helpers::getErrMsg () const
Definition at line 70 of file Helpers.cpp.
References _ErrMsg.
Referenced by HelpersPHEMlight::getClassByName().
getgClass()
const std::string & PHEMlightdll::Helpers::getgClass () const
Definition at line 62 of file Helpers.cpp.
References _Class.
Referenced by PHEMlightdll::CEPHandler::GetCEP(), HelpersPHEMlight::getClassByName(), and PHEMlightdll::CEPHandler::Load().
getPHEMDataV()
const std::string & PHEMlightdll::Helpers::getPHEMDataV () const
Definition at line 86 of file Helpers.cpp.
References _PHEMDataV.
getsClass()
const std::string & PHEMlightdll::Helpers::getsClass () const
Definition at line 54 of file Helpers.cpp.
References _sClass.
Referenced by setclass().
getsclass()
bool PHEMlightdll::Helpers::getsclass (const std::string & VEH) private
Definition at line 176 of file Helpers.cpp.
References _ErrMsg, _sClass, PHEMlightdll::Constants::strLKW, PHEMlightdll::Constants::strLNF, PHEMlightdll::Constants::strSI, PHEMlightdll::Constants::strSII, and PHEMlightdll::Constants::strSIII.
Referenced by setclass().
gettClass()
const std::string & PHEMlightdll::Helpers::gettClass () const
Definition at line 46 of file Helpers.cpp.
References _tClass.
Referenced by setclass().
gettclass()
bool PHEMlightdll::Helpers::gettclass (const std::string & VEH) private
Definition at line 141 of file Helpers.cpp.
References _ErrMsg, _tClass, PHEMlightdll::Constants::strBEV, PHEMlightdll::Constants::strCNG, PHEMlightdll::Constants::strDiesel, PHEMlightdll::Constants::strGasoline, and PHEMlightdll::Constants::strHybrid.
Referenced by setclass().
getvClass()
const std::string & PHEMlightdll::Helpers::getvClass () const
Definition at line 30 of file Helpers.cpp.
References _vClass.
getvclass()
bool PHEMlightdll::Helpers::getvclass (const std::string & VEH) private
Definition at line 94 of file Helpers.cpp.
References _ErrMsg, _vClass, PHEMlightdll::Constants::DRIVE_TRAIN_EFFICIENCY_All, PHEMlightdll::Constants::DRIVE_TRAIN_EFFICIENCY_CB, PHEMlightdll::Constants::setDRIVE_TRAIN_EFFICIENCY(), PHEMlightdll::Constants::strKKR, PHEMlightdll::Constants::strLB, PHEMlightdll::Constants::strLKW, PHEMlightdll::Constants::strLNF, PHEMlightdll::Constants::strLSZ, PHEMlightdll::Constants::strMR2, PHEMlightdll::Constants::strMR4, PHEMlightdll::Constants::strPKW, and PHEMlightdll::Constants::strRB.
Referenced by setclass().
setclass()
bool PHEMlightdll::Helpers::setclass (const std::string & VEH)
Definition at line 240 of file Helpers.cpp.
References _Class, _eClass, _sClass, _vClass, geteClass(), geteclass(), getsClass(), getsclass(), gettClass(), gettclass(), and getvclass().
Referenced by HelpersPHEMlight::getClassByName().
setCommentPrefix()
void PHEMlightdll::Helpers::setCommentPrefix (const std::string & value)
Definition at line 82 of file Helpers.cpp.
References _commentPrefix.
Referenced by HelpersPHEMlight::getClassByName().
seteClass()
void PHEMlightdll::Helpers::seteClass (const std::string & value)
Definition at line 42 of file Helpers.cpp.
References _eClass.
setErrMsg()
void PHEMlightdll::Helpers::setErrMsg (const std::string & value)
Definition at line 74 of file Helpers.cpp.
References _ErrMsg.
Referenced by PHEMlightdll::CEP::GetCO2Emission(), PHEMlightdll::CEP::GetEmission(), PHEMlightdll::CEPHandler::ReadEmissionData(), and PHEMlightdll::CEPHandler::ReadVehicleFile().
setgClass()
void PHEMlightdll::Helpers::setgClass (const std::string & value)
Definition at line 66 of file Helpers.cpp.
References _Class.
setPHEMDataV()
void PHEMlightdll::Helpers::setPHEMDataV (const std::string & value)
Definition at line 90 of file Helpers.cpp.
References _PHEMDataV.
Referenced by HelpersPHEMlight::getClassByName().
setsClass()
void PHEMlightdll::Helpers::setsClass (const std::string & value)
Definition at line 58 of file Helpers.cpp.
References _sClass.
settClass()
void PHEMlightdll::Helpers::settClass (const std::string & value)
Definition at line 50 of file Helpers.cpp.
References _tClass.
setvClass()
void PHEMlightdll::Helpers::setvClass (const std::string & value)
Definition at line 34 of file Helpers.cpp.
References _vClass.
Field Documentation
_Class
std::string PHEMlightdll::Helpers::_Class private
Definition at line 56 of file Helpers.h.
Referenced by getgClass(), setclass(), and setgClass().
_commentPrefix
std::string PHEMlightdll::Helpers::_commentPrefix private
Definition at line 66 of file Helpers.h.
Referenced by getCommentPrefix(), and setCommentPrefix().
_eClass
std::string PHEMlightdll::Helpers::_eClass private
Definition at line 41 of file Helpers.h.
Referenced by geteClass(), geteclass(), setclass(), and seteClass().
_ErrMsg
std::string PHEMlightdll::Helpers::_ErrMsg private
Definition at line 61 of file Helpers.h.
Referenced by geteclass(), getErrMsg(), getsclass(), gettclass(), getvclass(), and setErrMsg().
_PHEMDataV
std::string PHEMlightdll::Helpers::_PHEMDataV private
Definition at line 71 of file Helpers.h.
Referenced by getPHEMDataV(), and setPHEMDataV().
_sClass
std::string PHEMlightdll::Helpers::_sClass private
Definition at line 51 of file Helpers.h.
Referenced by getsClass(), getsclass(), setclass(), and setsClass().
_tClass
std::string PHEMlightdll::Helpers::_tClass private
Definition at line 46 of file Helpers.h.
Referenced by gettClass(), gettclass(), and settClass().
_vClass
std::string PHEMlightdll::Helpers::_vClass private
Definition at line 36 of file Helpers.h.
Referenced by getvClass(), getvclass(), setclass(), and setvClass().
The documentation for this class was generated from the following files:
Helpers.h
Helpers.cpp