SUMO - Simulation of Urban MObility: GUITexturesHelper Class Reference
GUITexturesHelper Class Reference
Global storage for textures; manages and draws them.
#include <GUITexturesHelper.h>
Static Public Member Functions
static GUIGlID add (FXImage *i)
Adds a texture to use.
static void allowTextures (const bool val)
switch texture drawing on and off
static void clearTextures ()
clears loaded textures
static void drawTexturedBox (int which, double size)
Draws a named texture as a box with the given size.
static void drawTexturedBox (int which, double sizeX1, double sizeY1, double sizeX2, double sizeY2)
Draws a named texture as a rectangle with the given sizes.
static int getMaxTextureSize ()
return maximum number of pixels in x and y direction
static int getTextureID (const std::string &filename, const bool mirrorX=false)
return texture id for the given filename (initialize on first use)
static bool texturesAllowed ()
ask whether texture drawing is enabled
Static Private Attributes
static bool myAllowTextures = true
whether textures are drawn
static std::map< std::string, int > myTextures
mapping from image paths to decals (initialization on first use)
Detailed Description
Global storage for textures; manages and draws them.
Definition at line 45 of file GUITexturesHelper.h.
Member Function Documentation
add()
GUIGlID GUITexturesHelper::add (FXImage * i) static
Adds a texture to use.
Definition at line 61 of file GUITexturesHelper.cpp.
Referenced by GUISUMOAbstractView::drawDecals(), GUITextureSubSys::getTexture(), and getTextureID().
allowTextures()
static void GUITexturesHelper::allowTextures (const bool val) inline static
switch texture drawing on and off
Definition at line 68 of file GUITexturesHelper.h.
References myAllowTextures.
Referenced by GUIDialog_AppSettings::onCmdOk(), and GUILoadThread::run().
clearTextures()
void GUITexturesHelper::clearTextures () static
clears loaded textures
Definition at line 140 of file GUITexturesHelper.cpp.
References myTextures.
Referenced by GUIApplicationWindow::closeAllWindows(), and GUITextureSubSys::resetTextures().
drawTexturedBox() [1/2]
void GUITexturesHelper::drawTexturedBox (int which, double size) static
Draws a named texture as a box with the given size.
Definition at line 78 of file GUITexturesHelper.cpp.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUISUMOAbstractView::drawDecals(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GNELane::drawGL(), GNERouteProbe::drawGL(), GUIPointOfInterest::drawGL(), GNEVariableSpeedSign::drawGL(), GNERerouter::drawGL(), GNEShape::drawLockIcon(), and GNEAdditional::drawLockIcon().
drawTexturedBox() [2/2]
void GUITexturesHelper::drawTexturedBox (int which, double sizeX1, double sizeY1, double sizeX2, double sizeY2) static
Draws a named texture as a rectangle with the given sizes.
Definition at line 84 of file GUITexturesHelper.cpp.
References myAllowTextures.
getMaxTextureSize()
int GUITexturesHelper::getMaxTextureSize () static
return maximum number of pixels in x and y direction
Definition at line 53 of file GUITexturesHelper.cpp.
Referenced by GUISUMOAbstractView::drawDecals(), and getTextureID().
getTextureID()
int GUITexturesHelper::getTextureID (const std::string & filename, const bool mirrorX = false) static
return texture id for the given filename (initialize on first use)
Note
return -1 on failure
Definition at line 119 of file GUITexturesHelper.cpp.
References add(), GUIMainWindow::getInstance(), getMaxTextureSize(), MFXImageHelper::loadImage(), myTextures, MFXImageHelper::scalePower2(), and WRITE_ERROR.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GNEPoly::GNEPoly(), GNEPOI::isValid(), GNEPOILane::isValid(), GNEPoly::isValid(), and GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute().
texturesAllowed()
static bool GUITexturesHelper::texturesAllowed () inline static
ask whether texture drawing is enabled
Definition at line 73 of file GUITexturesHelper.h.
References myAllowTextures.
Field Documentation
myAllowTextures
bool GUITexturesHelper::myAllowTextures = true static private
whether textures are drawn
Definition at line 82 of file GUITexturesHelper.h.
Referenced by allowTextures(), drawTexturedBox(), and texturesAllowed().
myTextures
std::map< std::string, int > GUITexturesHelper::myTextures static private
mapping from image paths to decals (initialization on first use)
Definition at line 79 of file GUITexturesHelper.h.
Referenced by clearTextures(), and getTextureID().
The documentation for this class was generated from the following files:
GUITexturesHelper.h
GUITexturesHelper.cpp