SUMO - Simulation of Urban MObility: DijkstraRouter< E, V, PF >::EdgeInfo Class Reference
DijkstraRouter< E, V, PF >::EdgeInfo Class Reference
#include <DijkstraRouter.h>
Public Member Functions
EdgeInfo (const E *const e)
Constructor.
void reset ()
Data Fields
const E *const edge
The current edge.
double effort
Effort to reach the edge.
double leaveTime
The time the vehicle leaves the edge.
const EdgeInfo * prev
The previous edge.
bool visited
The previous edge.
Private Member Functions
EdgeInfo & operator= (const EdgeInfo &s)=delete
Invalidated assignment operator.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouter< E, V, PF >::EdgeInfo
A definition about a route's edge with the effort needed to reach it and the information about the previous edge.
Definition at line 79 of file DijkstraRouter.h.
Constructor & Destructor Documentation
EdgeInfo()
template<class E, class V, class PF> DijkstraRouter< E, V, PF >::EdgeInfo::EdgeInfo (const E *const e) inline
Constructor.
Definition at line 82 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::DijkstraRouter().
Member Function Documentation
operator=()
template<class E, class V, class PF> EdgeInfo& DijkstraRouter< E, V, PF >::EdgeInfo::operator= (const EdgeInfo & s) private delete
Invalidated assignment operator.
Referenced by DijkstraRouter< E, V, PF >::EdgeInfo::reset().
reset()
template<class E, class V, class PF> void DijkstraRouter< E, V, PF >::EdgeInfo::reset () inline
Definition at line 100 of file DijkstraRouter.h.
References DijkstraRouter< E, V, PF >::EdgeInfo::operator=().
Field Documentation
edge
template<class E, class V, class PF> const E* const DijkstraRouter< E, V, PF >::EdgeInfo::edge
The current edge.
Definition at line 86 of file DijkstraRouter.h.
Referenced by DijkstraRouter< E, V, PF >::EdgeInfoByEffortComparator::operator()().
effort
template<class E, class V, class PF> double DijkstraRouter< E, V, PF >::EdgeInfo::effort
Effort to reach the edge.
Definition at line 89 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::getTravelTime(), and DijkstraRouter< E, V, PF >::EdgeInfoByEffortComparator::operator()().
leaveTime
template<class E, class V, class PF> double DijkstraRouter< E, V, PF >::EdgeInfo::leaveTime
The time the vehicle leaves the edge.
Definition at line 92 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute().
prev
template<class E, class V, class PF> const EdgeInfo* DijkstraRouter< E, V, PF >::EdgeInfo::prev
The previous edge.
Definition at line 95 of file DijkstraRouter.h.
visited
template<class E, class V, class PF> bool DijkstraRouter< E, V, PF >::EdgeInfo::visited
The previous edge.
Definition at line 98 of file DijkstraRouter.h.
The documentation for this class was generated from the following file:
DijkstraRouter.h