SUMO - Simulation of Urban MObility: ROPerson::Walk Class Reference
ROPerson::Walk Class Reference
A walk is part of a trip, e.g., go from here to here by foot.
#include <ROPerson.h>
Public Member Functions
const ROEdge * getDestination () const
const ROEdge * getOrigin () const
void saveAsXML (OutputDevice &os, const bool extended) const
Walk (const ConstROEdgeVector &_edges, const double _cost, double departPos=std::numeric_limits< double >::infinity(), double arrivalPos=std::numeric_limits< double >::infinity(), const std::string &_destStop="")
Walk (const ConstROEdgeVector &edges, const double _cost, const double duration, const double speed, const double departPos, const double arrivalPos, const std::string &_destStop)
Protected Attributes
double cost
Private Member Functions
Walk & operator= (const Walk &src)
Invalidated assignment operator.
Private Attributes
const double arr
const double dep
const std::string destStop
const double dur
const ConstROEdgeVector edges
const double v
Detailed Description
A walk is part of a trip, e.g., go from here to here by foot.
Definition at line 190 of file ROPerson.h.
Constructor & Destructor Documentation
Walk() [1/2]
ROPerson::Walk::Walk (const ConstROEdgeVector & _edges, const double _cost, double departPos = std::numeric_limits<double>::infinity(), double arrivalPos = std::numeric_limits<double>::infinity(), const std::string & _destStop = "") inline
Definition at line 192 of file ROPerson.h.
Walk() [2/2]
ROPerson::Walk::Walk (const ConstROEdgeVector & edges, const double _cost, const double duration, const double speed, const double departPos, const double arrivalPos, const std::string & _destStop) inline
Definition at line 197 of file ROPerson.h.
Member Function Documentation
getDestination()
const ROEdge* ROPerson::Walk::getDestination () const inline virtual
Implements ROPerson::TripItem.
Definition at line 203 of file ROPerson.h.
References ROPerson::PlanItem::saveAsXML().
getOrigin()
const ROEdge* ROPerson::Walk::getOrigin () const inline virtual
Implements ROPerson::TripItem.
Definition at line 200 of file ROPerson.h.
operator=()
Walk& ROPerson::Walk::operator= (const Walk & src) private
Invalidated assignment operator.
saveAsXML()
void ROPerson::Walk::saveAsXML (OutputDevice & os, const bool extended) const virtual
Implements ROPerson::TripItem.
Definition at line 137 of file ROPerson.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_COST, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_SPEED, SUMO_TAG_WALK, and OutputDevice::writeAttr().
Field Documentation
arr
const double ROPerson::Walk::arr private
Definition at line 210 of file ROPerson.h.
cost
double ROPerson::TripItem::cost protected inherited
Definition at line 153 of file ROPerson.h.
dep
const double ROPerson::Walk::dep private
Definition at line 210 of file ROPerson.h.
destStop
const std::string ROPerson::Walk::destStop private
Definition at line 211 of file ROPerson.h.
dur
const double ROPerson::Walk::dur private
Definition at line 210 of file ROPerson.h.
edges
const ConstROEdgeVector ROPerson::Walk::edges private
Definition at line 209 of file ROPerson.h.
v
const double ROPerson::Walk::v private
Definition at line 210 of file ROPerson.h.
The documentation for this class was generated from the following files:
ROPerson.h
ROPerson.cpp