SUMO - Simulation of Urban MObility: GNEDeleteFrame Class Reference
GNEDeleteFrame Class Reference
#include <GNEDeleteFrame.h>
Public Member Functions
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEAttributeCarrier * getMarkedAttributeCarrier () const
returns marked atrribute carrier
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNEDeleteFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
FOX-declaration.
virtual void hide ()
hide Frame
void markAttributeCarrier (GNEAttributeCarrier *ac)
mark attribute carrier (element)
void removeAttributeCarrier (GNEAttributeCarrier *ac)
remove attribute carrier (element)
void setFrameWidth (int newWidth)
set width of GNEFrame
virtual void show ()
show Frame
void showChildsOfMarkedAttributeCarrier ()
show childs of marked attribute carrier
void updateCurrentLabel (GNEAttributeCarrier *ac)
update current label
~GNEDeleteFrame ()
Destructor.
FOX-callbacks
called when user press right click over an item of list of childs
long onCmdShowChildMenu (FXObject *, FXSelector, void *eventData)
long onCmdCenterChildItem (FXObject *, FXSelector, void *)
called when user select option "center item" of child Menu
long onCmdInspectChildItem (FXObject *, FXSelector, void *)
called when user select option "inspect item" of child menu
long onCmdDeleteChildItem (FXObject *, FXSelector, void *)
called when user select option "delte item" of child menu
Protected Member Functions
void createPopUpMenu (int X, int Y, GNEAttributeCarrier *ac)
GNEDeleteFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Attributes
FXCheckButton * myAutomaticallyDeleteAdditionalsCheckButton
checkbox for enable/disable automatically delete additionals childs
GNEAttributeCarrier * myClickedAC
current attribute carrier selected in three
FXLabel * myCurrentElementLabel
label for current element
FXCheckButton * myDeleteOnlyGeometryPoints
checkbox for enable/disable delete only geometry points
FXGroupBox * myGroupBoxCurrentElement
groupbox for current element
FXGroupBox * myGroupBoxInformation
groupbox for information
FXGroupBox * myGroupBoxOptions
groupbox options
FXGroupBox * myGroupBoxTreeList
groupbox for tree list childs
FXLabel * myInformationLabel
Label for information 1.
GNEAttributeCarrier * myMarkedAC
pointer to marked attributeCarrier (element)
FXLabel * myMarkedElementLabel
label for marked element
std::set< FXTreeItem * > myTreeItemsWithoutAC
set used to save tree items without AC assigned (for example, Incoming/Outcoming connections)
std::map< FXTreeItem *, GNEAttributeCarrier * > myTreeItemToACMap
map used to save the Tree items with their AC
FXTreeList * myTreelist
tree list to show the childs of the element to erase
Detailed Description
The Widget for deleting elements
Definition at line 45 of file GNEDeleteFrame.h.
Constructor & Destructor Documentation
GNEDeleteFrame() [1/2]
GNEDeleteFrame::GNEDeleteFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
FOX-declaration.
Constructor parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 80 of file GNEDeleteFrame.cpp.
References GUIDesignCheckButtonAttribute, GUIDesignGroupBoxFrame, GUIDesignLabelFrameInformation, GUIDesignTreeListFrame, MID_GNE_DELETEFRAME_AUTODELETEADDITIONALS, MID_GNE_DELETEFRAME_CHILDS, and MID_GNE_DELETEFRAME_ONLYGEOMETRYPOINTS.
~GNEDeleteFrame()
GNEDeleteFrame::~GNEDeleteFrame ()
Destructor.
Definition at line 109 of file GNEDeleteFrame.cpp.
GNEDeleteFrame() [2/2]
GNEDeleteFrame::GNEDeleteFrame () inline protected
FOX needs this.
Definition at line 94 of file GNEDeleteFrame.h.
References createPopUpMenu().
Member Function Documentation
createPopUpMenu()
void GNEDeleteFrame::createPopUpMenu (int X, int Y, GNEAttributeCarrier * ac) protected
Definition at line 588 of file GNEDeleteFrame.cpp.
References GNEViewParent::getApp(), GUIMainWindow::getBoldFont(), GUIIconSubSys::getIcon(), GNEAttributeCarrier::getIcon(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), GNEViewNet::getViewParent(), ICON_MODEDELETE, ICON_MODEINSPECT, ICON_RECENTERVIEW, MID_GNE_DELETEFRAME_CENTER, MID_GNE_DELETEFRAME_DELETE, MID_GNE_DELETEFRAME_INSPECT, myClickedAC, myTreelist, GNEFrame::myViewNet, and toString().
Referenced by GNEDeleteFrame(), and onCmdShowChildMenu().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getMarkedAttributeCarrier()
GNEAttributeCarrier * GNEDeleteFrame::getMarkedAttributeCarrier () const
returns marked atrribute carrier
Definition at line 542 of file GNEDeleteFrame.cpp.
References myMarkedAC.
Referenced by GNEViewNet::onLeftBtnPress().
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
hide()
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), onCmdInspectChildItem(), and removeAttributeCarrier().
markAttributeCarrier()
void GNEDeleteFrame::markAttributeCarrier (GNEAttributeCarrier * ac)
mark attribute carrier (element)
Note
if ac == NULL current marked attribute carrier will be dismarked
Definition at line 514 of file GNEDeleteFrame.cpp.
References GUIIconSubSys::getIcon(), GNEAttributeCarrier::getIcon(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), ICON_EMPTY, myMarkedAC, myMarkedElementLabel, and toString().
Referenced by GNEInspectorFrame::onCmdGoBack(), and GNEViewNet::onLeftBtnPress().
onCmdCenterChildItem()
long GNEDeleteFrame::onCmdCenterChildItem (FXObject * , FXSelector , void *)
called when user select option "center item" of child Menu
Definition at line 561 of file GNEDeleteFrame.cpp.
References GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), GNEAttributeCarrier::getGUIGLObject(), myClickedAC, and GNEFrame::myViewNet.
onCmdDeleteChildItem()
long GNEDeleteFrame::onCmdDeleteChildItem (FXObject * , FXSelector , void *)
called when user select option "delte item" of child menu
Definition at line 581 of file GNEDeleteFrame.cpp.
References myClickedAC, and removeAttributeCarrier().
onCmdInspectChildItem()
long GNEDeleteFrame::onCmdInspectChildItem (FXObject * , FXSelector , void *)
called when user select option "inspect item" of child menu
Definition at line 569 of file GNEDeleteFrame.cpp.
References GNEViewParent::getInspectorFrame(), GNEViewNet::getViewParent(), GNEFrame::hide(), GNEInspectorFrame::inspectFromDeleteFrame(), myClickedAC, myMarkedAC, GNEFrame::myViewNet, and GNEInspectorFrame::show().
onCmdShowChildMenu()
long GNEDeleteFrame::onCmdShowChildMenu (FXObject * , FXSelector , void * eventData)
Definition at line 548 of file GNEDeleteFrame.cpp.
References createPopUpMenu(), myTreeItemsWithoutAC, myTreeItemToACMap, and myTreelist.
removeAttributeCarrier()
void GNEDeleteFrame::removeAttributeCarrier (GNEAttributeCarrier * ac)
remove attribute carrier (element)
Definition at line 343 of file GNEDeleteFrame.cpp.
References GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNEEdge::deleteGeometryPoint(), GNEPoly::deleteGeometryPoint(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteShape(), GNENetElement::getAdditionalChilds(), GNEViewParent::getAdditionalFrame(), GNENetElement::getAdditionalParents(), OptionsCont::getBool(), GNEJunction::getGNEEdges(), GNEAttributeCarrier::getGUIGLObject(), GNEAttributeCarrier::getID(), GNEViewParent::getInspectorFrame(), GNEEdge::getLanes(), GNEViewNet::getNet(), OptionsCont::getOptions(), GUISUMOAbstractView::getPositionInformation(), GNEAttributeCarrier::getTag(), GUIGlObject::getType(), GNEViewNet::getUndoList(), GNEEdge::getVertexIndex(), GNEPoly::getVertexIndex(), GNEFrame::getViewNet(), GNEViewNet::getViewParent(), GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, GNEFrame::hide(), myAutomaticallyDeleteAdditionalsCheckButton, myDeleteOnlyGeometryPoints, GNEFrame::myViewNet, GNEAdditionalFrame::removeAdditional(), GNEFrame::show(), toString(), UNUSED_PARAMETER, and WRITE_WARNING.
Referenced by onCmdDeleteChildItem(), GNEInspectorFrame::onCmdDeleteItem(), and GNEViewNet::onLeftBtnPress().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
show()
void GNEFrame::show () virtual inherited
show Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNEAdditionalFrame, GNEPolygonFrame, GNEInspectorFrame, and GNESelectorFrame.
Definition at line 546 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEFrame::myViewNet, and GNEViewParent::showFramesArea().
Referenced by GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), removeAttributeCarrier(), GNESelectorFrame::show(), GNEInspectorFrame::show(), GNEPolygonFrame::show(), GNEAdditionalFrame::show(), and GNEViewNet::updateModeSpecificControls().
showChildsOfMarkedAttributeCarrier()
void GNEDeleteFrame::showChildsOfMarkedAttributeCarrier ()
show childs of marked attribute carrier
Definition at line 113 of file GNEDeleteFrame.cpp.
References GNENetElement::getAdditionalChilds(), GNENetElement::getAdditionalParents(), GNEJunction::getGNECrossings(), GNEJunction::getGNEEdges(), GNELane::getGNEIncomingConnections(), GNELane::getGNEOutcomingConnections(), GNEAttributeCarrier::getGUIGLObject(), GNEAttributeCarrier::getIcon(), GNEEdge::getLanes(), GNEAttributeCarrier::getTag(), GUIGlObject::getType(), GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, myMarkedAC, myTreeItemsWithoutAC, myTreeItemToACMap, myTreelist, and toString().
Referenced by GNEInspectorFrame::onCmdGoBack().
updateCurrentLabel()
void GNEDeleteFrame::updateCurrentLabel (GNEAttributeCarrier * ac)
update current label
Definition at line 529 of file GNEDeleteFrame.cpp.
References GUIIconSubSys::getIcon(), GNEAttributeCarrier::getIcon(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), ICON_EMPTY, myCurrentElementLabel, and toString().
Referenced by GNEViewNet::onMouseMove().
Field Documentation
myAutomaticallyDeleteAdditionalsCheckButton
FXCheckButton* GNEDeleteFrame::myAutomaticallyDeleteAdditionalsCheckButton private
checkbox for enable/disable automatically delete additionals childs
Definition at line 122 of file GNEDeleteFrame.h.
Referenced by removeAttributeCarrier().
myClickedAC
GNEAttributeCarrier* GNEDeleteFrame::myClickedAC private
current attribute carrier selected in three
Definition at line 140 of file GNEDeleteFrame.h.
Referenced by createPopUpMenu(), onCmdCenterChildItem(), onCmdDeleteChildItem(), and onCmdInspectChildItem().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myCurrentElementLabel
FXLabel* GNEDeleteFrame::myCurrentElementLabel private
label for current element
Definition at line 104 of file GNEDeleteFrame.h.
Referenced by updateCurrentLabel().
myDeleteOnlyGeometryPoints
FXCheckButton* GNEDeleteFrame::myDeleteOnlyGeometryPoints private
checkbox for enable/disable delete only geometry points
Definition at line 125 of file GNEDeleteFrame.h.
Referenced by removeAttributeCarrier().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxCurrentElement
FXGroupBox* GNEDeleteFrame::myGroupBoxCurrentElement private
groupbox for current element
Definition at line 101 of file GNEDeleteFrame.h.
myGroupBoxInformation
FXGroupBox* GNEDeleteFrame::myGroupBoxInformation private
groupbox for information
Definition at line 116 of file GNEDeleteFrame.h.
myGroupBoxOptions
FXGroupBox* GNEDeleteFrame::myGroupBoxOptions private
groupbox options
Definition at line 110 of file GNEDeleteFrame.h.
myGroupBoxTreeList
FXGroupBox* GNEDeleteFrame::myGroupBoxTreeList private
groupbox for tree list childs
Definition at line 113 of file GNEDeleteFrame.h.
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myInformationLabel
FXLabel* GNEDeleteFrame::myInformationLabel private
Label for information 1.
Definition at line 119 of file GNEDeleteFrame.h.
myMarkedAC
GNEAttributeCarrier* GNEDeleteFrame::myMarkedAC private
pointer to marked attributeCarrier (element)
Definition at line 137 of file GNEDeleteFrame.h.
Referenced by getMarkedAttributeCarrier(), markAttributeCarrier(), onCmdInspectChildItem(), and showChildsOfMarkedAttributeCarrier().
myMarkedElementLabel
FXLabel* GNEDeleteFrame::myMarkedElementLabel private
label for marked element
Definition at line 107 of file GNEDeleteFrame.h.
Referenced by markAttributeCarrier().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myTreeItemsWithoutAC
std::set<FXTreeItem*> GNEDeleteFrame::myTreeItemsWithoutAC private
set used to save tree items without AC assigned (for example, Incoming/Outcoming connections)
Definition at line 134 of file GNEDeleteFrame.h.
Referenced by onCmdShowChildMenu(), and showChildsOfMarkedAttributeCarrier().
myTreeItemToACMap
std::map<FXTreeItem*, GNEAttributeCarrier*> GNEDeleteFrame::myTreeItemToACMap private
map used to save the Tree items with their AC
Definition at line 131 of file GNEDeleteFrame.h.
Referenced by onCmdShowChildMenu(), and showChildsOfMarkedAttributeCarrier().
myTreelist
FXTreeList* GNEDeleteFrame::myTreelist private
tree list to show the childs of the element to erase
Definition at line 128 of file GNEDeleteFrame.h.
Referenced by createPopUpMenu(), onCmdShowChildMenu(), and showChildsOfMarkedAttributeCarrier().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNEDeleteFrame.h
GNEDeleteFrame.cpp