SUMO - Simulation of Urban MObility: netgen_main.cpp File Reference
netgen_main.cpp File Reference
#include <config.h>
#include <iostream>
#include <fstream>
#include <string>
#include <ctime>
#include <netgen/NGNet.h>
#include <netgen/NGRandomNetBuilder.h>
#include <netgen/NGFrame.h>
#include <netbuild/NBNetBuilder.h>
#include <netbuild/NBFrame.h>
#include <netwrite/NWFrame.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/options/Option.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/RandHelper.h>
#include <utils/common/ToString.h>
#include <utils/distribution/RandomDistributor.h>
#include <utils/geom/GeoConvHelper.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/iodevices/OutputDevice.h>
Functions
NGNet * buildNetwork (NBNetBuilder &nb)
bool checkOptions ()
void fillOptions ()
int main (int argc, char **argv)
Detailed Description
Author
Markus Hartinger
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Mar, 2003
Version
$Id$
Definition in file netgen_main.cpp.
Function Documentation
buildNetwork()
NGNet* buildNetwork (NBNetBuilder & nb)
Definition at line 108 of file netgen_main.cpp.
References RandomDistributor< T >::add(), NGNet::createChequerBoard(), NGRandomNetBuilder::createNet(), NGNet::createSpiderWeb(), OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getInt(), OptionsCont::getOptions(), OptionsCont::isDefault(), and WRITE_ERROR.
Referenced by main().
checkOptions()
bool checkOptions ()
Definition at line 99 of file netgen_main.cpp.
References NGFrame::checkOptions(), NWFrame::checkOptions(), and NBFrame::checkOptions().
Referenced by main().
fillOptions()
void fillOptions ()
Definition at line 65 of file netgen_main.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), NGFrame::fillOptions(), NWFrame::fillOptions(), NBFrame::fillOptions(), OptionsCont::getOptions(), RandHelper::insertRandOptions(), and OptionsCont::setAdditionalHelpMessage().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 206 of file netgen_main.cpp.
References NBNetBuilder::applyOptions(), buildNetwork(), checkOptions(), SystemFrame::close(), NBNetBuilder::compute(), fillOptions(), NBNetBuilder::getEdgeCont(), MsgHandler::getErrorInstance(), OptionsCont::getFloat(), NBNetBuilder::getNodeCont(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), GeoConvHelper::init(), XMLSubSys::init(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), OptionsCont::processMetaOptions(), OptionsCont::resetWritable(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), NBNodeCont::size(), NBEdgeCont::size(), NGNet::toNB(), VERSION_STRING, WRITE_ERROR, WRITE_MESSAGE, and NWFrame::writeNetwork().