SUMO - Simulation of Urban MObility: PCLoaderOSM::RelationsHandler Class Reference
PCLoaderOSM::RelationsHandler Class Reference
A class which extracts relevant way-ids from relations in a parsed OSM-file.
#include <PCLoaderOSM.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RelationsHandler (RelationsMap &additionalWays, Relations &relations, bool withAttributes, MsgHandler &errorHandler)
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~RelationsHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int element)
Called when a closing tag occurs.
Private Member Functions
RelationsHandler & operator= (const RelationsHandler &s)
Invalidated assignment operator.
RelationsHandler (const RelationsHandler &s)
Invalidated copy constructor.
Private Attributes
RelationsMap & myAdditionalWays
additional ways which are reference by relations
PCOSMRelation * myCurrentRelation
The currently parsed relation.
std::vector< long long int > myCurrentWays
the ways within the current relation
MsgHandler & myErrorHandler
The handler to report errors to (will be the WarningsHandler if –ignore-errors was set)
bool myKeep
whether the last edge (way) should be kept because it had a key from the inclusion list
std::vector< long long int > myParentElements
Current path in order to know to what occuring values belong.
Relations & myRelations
the loaded relations
bool myWithAttributes
Whether all attributes shall be stored.
Detailed Description
A class which extracts relevant way-ids from relations in a parsed OSM-file.
Definition at line 210 of file PCLoaderOSM.h.
Constructor & Destructor Documentation
RelationsHandler() [1/2]
PCLoaderOSM::RelationsHandler::RelationsHandler (RelationsMap & additionalWays, Relations & relations, bool withAttributes, MsgHandler & errorHandler)
Constructor.
Parameters
[in] osmNodes The previously parsed (osm-)nodes
[in] toFill The edges container to fill with read edges
[in] withAttributes Whether all attributes shall be stored
[in] errorHandler The handler to report errors to (WarningHandler for ignoring errors)
Definition at line 348 of file PCLoaderOSM.cpp.
~RelationsHandler()
PCLoaderOSM::RelationsHandler::~RelationsHandler ()
Destructor.
Definition at line 361 of file PCLoaderOSM.cpp.
RelationsHandler() [2/2]
PCLoaderOSM::RelationsHandler::RelationsHandler (const RelationsHandler & s) private
Invalidated copy constructor.
Member Function Documentation
buildErrorMessage()
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 187 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
characters()
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 170 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
endElement()
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 121 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
error()
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 206 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::addPersonTrip(), MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), and MSRouteHandler::myStartElement().
fatalError()
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 212 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
getFileName()
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 81 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
myCharacters()
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 222 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
myEndElement()
void PCLoaderOSM::RelationsHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 422 of file PCLoaderOSM.cpp.
References myCurrentRelation, myCurrentWays, myParentElements, and SUMO_TAG_RELATION.
myStartElement()
void PCLoaderOSM::RelationsHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 366 of file PCLoaderOSM.cpp.
References SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::hasAttribute(), PCLoaderOSM::PCOSMRelation::id, MsgHandler::inform(), myAdditionalWays, PCLoaderOSM::PCOSMRelation::myAttributes, myCurrentRelation, myCurrentWays, myErrorHandler, PCLoaderOSM::MyKeysToInclude, myParentElements, myRelations, PCLoaderOSM::PCOSMRelation::name, SUMO_ATTR_ID, SUMO_ATTR_K, SUMO_ATTR_REF, SUMO_ATTR_TYPE, SUMO_ATTR_V, SUMO_TAG_MEMBER, SUMO_TAG_RELATION, SUMO_TAG_TAG, and toString().
operator=()
RelationsHandler& PCLoaderOSM::RelationsHandler::operator= (const RelationsHandler & s) private
Invalidated assignment operator.
registerParent()
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 162 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
setFileName()
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 75 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
startElement()
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 100 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
warning()
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 200 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
myAdditionalWays
RelationsMap& PCLoaderOSM::RelationsHandler::myAdditionalWays private
additional ways which are reference by relations
Definition at line 255 of file PCLoaderOSM.h.
Referenced by myStartElement().
myCurrentRelation
PCOSMRelation* PCLoaderOSM::RelationsHandler::myCurrentRelation private
The currently parsed relation.
Definition at line 267 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
myCurrentWays
std::vector<long long int> PCLoaderOSM::RelationsHandler::myCurrentWays private
the ways within the current relation
Definition at line 270 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
myErrorHandler
MsgHandler& PCLoaderOSM::RelationsHandler::myErrorHandler private
The handler to report errors to (will be the WarningsHandler if –ignore-errors was set)
Definition at line 264 of file PCLoaderOSM.h.
Referenced by myStartElement().
myKeep
bool PCLoaderOSM::RelationsHandler::myKeep private
whether the last edge (way) should be kept because it had a key from the inclusion list
Definition at line 276 of file PCLoaderOSM.h.
myParentElements
std::vector<long long int> PCLoaderOSM::RelationsHandler::myParentElements private
Current path in order to know to what occuring values belong.
Definition at line 273 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
myRelations
Relations& PCLoaderOSM::RelationsHandler::myRelations private
the loaded relations
Definition at line 258 of file PCLoaderOSM.h.
Referenced by myStartElement().
myWithAttributes
bool PCLoaderOSM::RelationsHandler::myWithAttributes private
Whether all attributes shall be stored.
Definition at line 261 of file PCLoaderOSM.h.
The documentation for this class was generated from the following files:
PCLoaderOSM.h
PCLoaderOSM.cpp