SUMO - Simulation of Urban MObility: MSLane::VehPosition Struct Reference
MSLane::VehPosition Struct Reference
#include <MSLane.h>
Public Member Functions
bool operator() (const MSVehicle *cmp, double pos) const
compares vehicle position to the detector position
Detailed Description
Function-object in order to find the vehicle, that has just passed the detector.
Definition at line 93 of file MSLane.h.
Member Function Documentation
operator()()
bool MSLane::VehPosition::operator() (const MSVehicle * cmp, double pos) const
compares vehicle position to the detector position
Definition at line 2543 of file MSLane.cpp.
References MSVehicle::getPositionOnLane().
Referenced by MSLane::vehicle_natural_position_sorter::vehicle_natural_position_sorter(), and MSLane::vehicle_position_sorter::vehicle_position_sorter().
The documentation for this struct was generated from the following files:
MSLane.h
MSLane.cpp