SUMO - Simulation of Urban MObility: GUIEvent_SimulationLoaded Class Reference
GUIEvent_SimulationLoaded Class Reference
#include <GUIEvent_SimulationLoaded.h>
Public Member Functions
GUIEventType getOwnType () const
returns the event type
GUIEvent_SimulationLoaded (GUINet *net, SUMOTime startTime, SUMOTime endTime, const std::string &file, const std::vector< std::string > &settingsFiles, const bool osgView)
constructor
~GUIEvent_SimulationLoaded ()
destructor
Data Fields
const SUMOTime myBegin
the time the simulation shall start with
const SUMOTime myEnd
the time the simulation shall end with
const std::string myFile
the name of the loaded file
GUINet * myNet
the loaded net
const bool myOsgView
whether to load the OpenSceneGraph view
const std::vector< std::string > mySettingsFiles
the name of the settings file to load
Protected Attributes
GUIEventType myType
the type of the event
Private Member Functions
GUIEvent_SimulationLoaded & operator= (const GUIEvent_SimulationLoaded &s)
Invalidated assignment operator.
Detailed Description
Throw to GUIApplicationWindow from GUILoadThread after a simulation has been loaded or the loading process failed
Definition at line 56 of file GUIEvent_SimulationLoaded.h.
Constructor & Destructor Documentation
GUIEvent_SimulationLoaded()
GUIEvent_SimulationLoaded::GUIEvent_SimulationLoaded (GUINet * net, SUMOTime startTime, SUMOTime endTime, const std::string & file, const std::vector< std::string > & settingsFiles, const bool osgView) inline
constructor
Definition at line 59 of file GUIEvent_SimulationLoaded.h.
~GUIEvent_SimulationLoaded()
GUIEvent_SimulationLoaded::~GUIEvent_SimulationLoaded () inline
destructor
Definition at line 71 of file GUIEvent_SimulationLoaded.h.
Member Function Documentation
getOwnType()
GUIEventType GUIEvent::getOwnType () const inline inherited
returns the event type
Definition at line 83 of file GUIEvent.h.
References GUIEvent::myType.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
operator=()
GUIEvent_SimulationLoaded& GUIEvent_SimulationLoaded::operator= (const GUIEvent_SimulationLoaded & s) private
Invalidated assignment operator.
Field Documentation
myBegin
const SUMOTime GUIEvent_SimulationLoaded::myBegin
the time the simulation shall start with
Definition at line 78 of file GUIEvent_SimulationLoaded.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
myEnd
const SUMOTime GUIEvent_SimulationLoaded::myEnd
the time the simulation shall end with
Definition at line 81 of file GUIEvent_SimulationLoaded.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
myFile
const std::string GUIEvent_SimulationLoaded::myFile
the name of the loaded file
Definition at line 84 of file GUIEvent_SimulationLoaded.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
myNet
GUINet* GUIEvent_SimulationLoaded::myNet
the loaded net
Definition at line 75 of file GUIEvent_SimulationLoaded.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
myOsgView
const bool GUIEvent_SimulationLoaded::myOsgView
whether to load the OpenSceneGraph view
Definition at line 90 of file GUIEvent_SimulationLoaded.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
mySettingsFiles
const std::vector<std::string> GUIEvent_SimulationLoaded::mySettingsFiles
the name of the settings file to load
Definition at line 87 of file GUIEvent_SimulationLoaded.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
myType
GUIEventType GUIEvent::myType protected inherited
the type of the event
Definition at line 98 of file GUIEvent.h.
Referenced by GUIEvent::getOwnType(), and GUIEvent_Message::GUIEvent_Message().
The documentation for this class was generated from the following file:
GUIEvent_SimulationLoaded.h