SUMO - Simulation of Urban MObility: SUMOVehicle Class Reference
SUMOVehicle Class Reference abstract
Representation of a vehicle.
#include <SUMOVehicle.h>
Public Types
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
virtual void addContainer (MSTransportable *container)=0
Adds a container to this vehicle.
virtual void addPerson (MSTransportable *person)=0
Adds a person to this vehicle.
virtual bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0, bool collision=false, ConstMSEdgeVector::const_iterator *searchStart=0)=0
Adds a stop.
virtual double getAcceleration () const =0
Returns the vehicle's acceleration.
virtual SUMOTime getAccumulatedWaitingTime () const =0
virtual double getAngle () const =0
Get the vehicle's angle.
virtual double getArrivalPos () const =0
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
virtual double getBackPositionOnLane (const MSLane *lane) const =0
Get the vehicle's back position along the given lane.
virtual double getChosenSpeedFactor () const =0
virtual const ConstMSEdgeVector::const_iterator & getCurrentRouteEdge () const =0
Returns an iterator pointing to the current edge in this vehicles route.
virtual SUMOTime getDepartDelay () const =0
virtual double getDepartPos () const =0
Returns this vehicle's real departure position.
virtual SUMOTime getDeparture () const =0
Returns this vehicle's real departure time.
virtual MSDevice * getDevice (const std::type_info &type) const =0
Returns a device of the given type if it exists or 0.
virtual const std::vector< MSDevice * > & getDevices () const =0
Returns this vehicle's devices.
virtual const MSEdge * getEdge () const =0
Returns the edge the vehicle is currently at.
virtual const std::string & getID () const =0
Get the vehicle's ID.
virtual double getImpatience () const =0
Returns this vehicles impatience.
virtual MSLane * getLane () const =0
Returns the lane the vehicle is on.
virtual double getLateralPositionOnLane () const =0
Get the vehicle's lateral position on the lane.
virtual double getMaxSpeed () const =0
Returns the vehicle's maximum speed.
virtual MSParkingArea * getNextParkingArea ()=0
virtual int getNumberReroutes () const =0
Returns the number of new routes this vehicle got.
virtual const SUMOVehicleParameter & getParameter () const =0
Returns the vehicle's parameter (including departure definition)
virtual Position getPosition (const double offset=0) const =0
Return current position (x/y, cartesian)
virtual double getPositionOnLane () const =0
Get the vehicle's position along the lane.
virtual double getPreviousSpeed () const =0
Returns the vehicle's previous speed.
virtual const MSRoute & getRoute () const =0
Returns the current route.
virtual double getSlope () const =0
Returns the slope of the road at vehicle's position.
virtual double getSpeed () const =0
Returns the vehicle's current speed.
virtual SUMOVehicleClass getVClass () const =0
Returns the vehicle's access class.
virtual const MSVehicleType & getVehicleType () const =0
Returns the vehicle's type.
virtual SUMOTime getWaitingTime () const =0
virtual bool hasArrived () const =0
Returns whether this vehicle has arrived.
virtual bool hasDeparted () const =0
Returns whether this vehicle has departed.
virtual bool hasValidRoute (std::string &msg, const MSRoute *route=0) const =0
Validates the current or given route.
virtual bool isFrontOnLane (const MSLane *) const =0
Returns the information whether the front of the vehhicle is on the given lane.
virtual bool isOnRoad () const =0
Returns the information whether the vehicle is on a road (is simulated)
virtual bool isParking () const =0
Returns the information whether the vehicle is parked.
virtual bool isRemoteControlled () const =0
Returns the information whether the vehicle is fully controlled via TraCI.
virtual bool isSelected () const =0
whether this vehicle is selected in the GUI
virtual bool isStopped () const =0
Returns whether the vehicle is at a stop.
virtual bool isStoppedInRange (double pos) const =0
Returns whether the vehicle is stoped in range of the given position.
virtual bool isStoppedTriggered () const =0
Returns whether the vehicle is at a stop and waiting for a person or container to continue.
virtual void onDepart ()=0
Called when the vehicle is inserted into the network.
virtual bool replaceParkingArea (MSParkingArea *parkingArea, std::string &errorMsg)=0
Replaces a stop.
virtual bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0, bool addStops=true, bool removeStops=true)=0
Replaces the current route by the given one.
virtual bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false, bool removeStops=true)=0
Replaces the current route by the given edges.
virtual void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)=0
Performs a rerouting using the given router.
virtual void setArrivalPos (double arrivalPos)=0
Sets this vehicle's desired arrivalPos for its current route.
virtual void setChosenSpeedFactor (const double factor)=0
virtual const MSEdge * succEdge (int nSuccs) const =0
Returns the nSuccs'th successor of edge the vehicle is currently at.
virtual ~SUMOVehicle ()
Destructor.
state io
virtual void saveState (OutputDevice &out)=0
Saves the states of a vehicle.
virtual void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)=0
Loads the state of this vehicle from the given description.
Detailed Description
Representation of a vehicle.
Definition at line 66 of file SUMOVehicle.h.
Member Typedef Documentation
ComparatorIdLess
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess
Definition at line 79 of file SUMOVehicle.h.
Constructor & Destructor Documentation
~SUMOVehicle()
virtual SUMOVehicle::~SUMOVehicle () inline virtual
Destructor.
Definition at line 82 of file SUMOVehicle.h.
References addContainer(), addPerson(), addStop(), getAcceleration(), getAccumulatedWaitingTime(), getAngle(), getArrivalPos(), getBackPositionOnLane(), getChosenSpeedFactor(), getCurrentRouteEdge(), getDepartDelay(), getDepartPos(), getDeparture(), getDevice(), getDevices(), getEdge(), getID(), getImpatience(), getLane(), getLateralPositionOnLane(), getMaxSpeed(), getNextParkingArea(), getNumberReroutes(), getParameter(), getPosition(), getPositionOnLane(), getRoute(), getSlope(), getSpeed(), getVClass(), getVehicleType(), getWaitingTime(), hasArrived(), hasDeparted(), hasValidRoute(), isFrontOnLane(), isOnRoad(), isParking(), isRemoteControlled(), isSelected(), isStopped(), isStoppedInRange(), isStoppedTriggered(), loadState(), onDepart(), replaceParkingArea(), replaceRoute(), replaceRouteEdges(), reroute(), saveState(), setArrivalPos(), setChosenSpeedFactor(), and succEdge().
Member Function Documentation
addContainer()
virtual void SUMOVehicle::addContainer (MSTransportable * container) pure virtual
Adds a container to this vehicle.
May do nothing since containers are not supported by default
Parameters
[in] container The container to add
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSContainer::MSContainerStage_Driving::proceed(), and ~SUMOVehicle().
addPerson()
virtual void SUMOVehicle::addPerson (MSTransportable * person) pure virtual
Adds a person to this vehicle.
May do nothing since persons are not supported by default
Parameters
[in] person The person to add
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSPerson::MSPersonStage_Driving::proceed(), and ~SUMOVehicle().
addStop()
virtual bool SUMOVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0, bool collision = false, ConstMSEdgeVector::const_iterator * searchStart = 0) pure virtual
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implemented in MSVehicle, and MEVehicle.
Referenced by MSBaseVehicle::addStops(), and ~SUMOVehicle().
getAcceleration()
virtual double SUMOVehicle::getAcceleration () const pure virtual
Returns the vehicle's acceleration.
Returns
The acceleration
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSE2Collector::makeMoveNotification(), MSDevice_Battery::notifyMove(), MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), MSAmitranTrajectories::writeVehicle(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getAccumulatedWaitingTime()
virtual SUMOTime SUMOVehicle::getAccumulatedWaitingTime () const pure virtual
Implemented in MSVehicle, and MEVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), and ~SUMOVehicle().
getAngle()
virtual double SUMOVehicle::getAngle () const pure virtual
Get the vehicle's angle.
Returns
The angle of the vehicle (in degree)
Implemented in MSVehicle, GUIMEVehicle, GUIVehicle, and MEVehicle.
Referenced by MSDevice_Battery::notifyMove(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getArrivalPos()
virtual double SUMOVehicle::getArrivalPos () const pure virtual
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implemented in MSBaseVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSTriggeredRerouter::rerouteParkingArea(), MSDevice_Vehroutes::writeOutput(), and ~SUMOVehicle().
getBackPositionOnLane()
virtual double SUMOVehicle::getBackPositionOnLane (const MSLane * lane) const pure virtual
Get the vehicle's back position along the given lane.
Returns
The position of the vehicle (in m from the given lane's begin)
Implemented in MSVehicle, and MEVehicle.
Referenced by MSInductLoop::notifyEnter(), and ~SUMOVehicle().
getChosenSpeedFactor()
virtual double SUMOVehicle::getChosenSpeedFactor () const pure virtual
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput(), MSLane::getVehicleMaxSpeed(), MSEdge::insertVehicle(), MSDevice_Routing::reroute(), MSVehicleControl::vehicleDeparted(), and ~SUMOVehicle().
getCurrentRouteEdge()
virtual const ConstMSEdgeVector::const_iterator& SUMOVehicle::getCurrentRouteEdge () const pure virtual
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSTransportable::Stage_Driving::setArrived(), MSTransportable::Stage_Driving::setVehicle(), MSDevice_Vehroutes::writeOutput(), and ~SUMOVehicle().
getDepartDelay()
virtual SUMOTime SUMOVehicle::getDepartDelay () const pure virtual
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput(), MSDevice_Tripinfo::updateStatistics(), and ~SUMOVehicle().
getDepartPos()
virtual double SUMOVehicle::getDepartPos () const pure virtual
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSDevice_Tripinfo::generateOutput(), MSTransportable::Stage_Driving::setArrived(), MSTransportable::Stage_Driving::setVehicle(), MSDevice_Vehroutes::writeOutput(), and ~SUMOVehicle().
getDeparture()
virtual SUMOTime SUMOVehicle::getDeparture () const pure virtual
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSDevice_Tripinfo::generateOutput(), MSVehicleControl::scheduleVehicleRemoval(), MSVehicleControl::vehicleDeparted(), MSDevice_Vehroutes::writeOutput(), MSAmitranTrajectories::writeVehicle(), and ~SUMOVehicle().
getDevice()
virtual MSDevice* SUMOVehicle::getDevice (const std::type_info & type) const pure virtual
Returns a device of the given type if it exists or 0.
Implemented in MSBaseVehicle.
Referenced by MSInsertionControl::checkCandidates(), MSStateHandler::closeVehicle(), MSTriggeredRerouter::notifyEnter(), MSDevice_Example::notifyMove(), and ~SUMOVehicle().
getDevices()
virtual const std::vector<MSDevice*>& SUMOVehicle::getDevices () const pure virtual
Returns this vehicle's devices.
Returns
This vehicle's devices
Implemented in MSBaseVehicle.
Referenced by MSStateHandler::closeVehicle(), MSDevice_Tripinfo::generateOutput(), MSVehicleControl::scheduleVehicleRemoval(), and ~SUMOVehicle().
getEdge()
virtual const MSEdge* SUMOVehicle::getEdge () const pure virtual
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implemented in MSBaseVehicle.
Referenced by MSDevice_Vehroutes::addRoute(), MSInsertionControl::checkCandidates(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDevice_Tripinfo::generateOutput(), MSNet::getVehicleMeanSpeeds(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSDevice_Vehroutes::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Transportable::notifyMove(), MSDevice_Tripinfo::notifyMoveInternal(), MSTriggeredRerouter::rerouteParkingArea(), MSInsertionControl::tryInsert(), and ~SUMOVehicle().
getID()
virtual const std::string& SUMOVehicle::getID () const pure virtual
Get the vehicle's ID.
Returns
The the ID of the vehicle
Implemented in MSBaseVehicle.
Referenced by MSChargingStation::addChargeValueForOutput(), MSLink::blockedByFoe(), MSDevice_Transportable::buildVehicleDevices(), MSDevice_Tripinfo::buildVehicleDevices(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Vehroutes::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSDevice_SSM::buildVehicleDevices(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSInductLoop::collectVehiclesOnDet(), MSVehicleControl::deleteVehicle(), MSE3Collector::enter(), MSDevice::equippedByDefaultAssignmentOptions(), MSVTypeProbe::execute(), MSDevice_Tripinfo::generateOutput(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), libsumo::Person::getVehicle(), MSEdge::insertVehicle(), MSE3Collector::leave(), MSInductLoop::leaveDetectorByMove(), MSE3Collector::leaveFront(), MSE2Collector::makeMoveNotification(), MSE2Collector::makeVehicleInfo(), MSDevice_BTreceiver::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_Battery::notifyMove(), MSDevice_Example::notifyMove(), MSDevice_Bluelight::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSLink::opened(), MSLink::removeApproaching(), MSDevice_SSM::requestsTrajectories(), MSTriggeredRerouter::rerouteParkingArea(), MSLink::setApproaching(), MSTransportable::Stage_Driving::setVehicle(), MSStopOut::stopEnded(), MSStopOut::stopStarted(), MSLane::succLinkSec(), MSDevice_SSM::useGeoCoords(), TraCIServer::vehicleStateChanged(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSDevice_Vehroutes::writeOutput(), MSAmitranTrajectories::writeVehicle(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getImpatience()
virtual double SUMOVehicle::getImpatience () const pure virtual
Returns this vehicles impatience.
Implemented in MSBaseVehicle.
Referenced by ~SUMOVehicle().
getLane()
virtual MSLane* SUMOVehicle::getLane () const pure virtual
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implemented in MSVehicle, and MEVehicle.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), GUIBaseVehicle::drawOnPos(), MSTransportable::Stage_Driving::getEdge(), libsumo::Vehicle::isOnInit(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_SSM::notifyLeave(), MSDevice_Battery::notifyMove(), MSDevice_Bluelight::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and ~SUMOVehicle().
getLateralPositionOnLane()
virtual double SUMOVehicle::getLateralPositionOnLane () const pure virtual
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSLink::opened(), and ~SUMOVehicle().
getMaxSpeed()
virtual double SUMOVehicle::getMaxSpeed () const pure virtual
Returns the vehicle's maximum speed.
Returns
The vehicle's maximum speed
Implemented in MSBaseVehicle.
Referenced by MSLane::getVehicleMaxSpeed(), and ~SUMOVehicle().
getNextParkingArea()
virtual MSParkingArea* SUMOVehicle::getNextParkingArea () pure virtual
returns the next imminent stop in the stop queue
Returns
the upcoming stop
Implemented in MSVehicle, and MEVehicle.
Referenced by MSTriggeredRerouter::rerouteParkingArea(), and ~SUMOVehicle().
getNumberReroutes()
virtual int SUMOVehicle::getNumberReroutes () const pure virtual
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implemented in MSBaseVehicle.
Referenced by MSDevice_Tripinfo::generateOutput(), MSDevice_Vehroutes::writeXMLRoute(), and ~SUMOVehicle().
getParameter()
virtual const SUMOVehicleParameter& SUMOVehicle::getParameter () const pure virtual
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implemented in MSBaseVehicle.
Referenced by MSVehicleContainer::add(), MSVehicleControl::addVehicle(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSRouteHandler::closeVehicle(), MSDevice::equippedByDefaultAssignmentOptions(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSVehicleControl::getWaitingVehicle(), MSTriggeredRerouter::getWeight(), MSEdge::insertVehicle(), MSDevice_Routing::MSDevice_Routing(), MSDevice_Vehroutes::notifyEnter(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSVehicleContainer::remove(), MSDevice_SSM::requestsTrajectories(), MSTransportable::Stage_Driving::setVehicle(), MSInsertionControl::tryInsert(), MSDevice_SSM::useGeoCoords(), MSVehicleControl::vehicleDeparted(), MSDevice_Vehroutes::writeOutput(), and ~SUMOVehicle().
getPosition()
virtual Position SUMOVehicle::getPosition (const double offset = 0) const pure virtual
Return current position (x/y, cartesian)
If the vehicle is not in the net, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See also
myLane
Implemented in MSVehicle, MEVehicle, GUIMEVehicle, and GUIVehicle.
Referenced by GUIBaseVehicle::drawOnPos(), MSVTypeProbe::execute(), MSTransportable::Stage_Driving::getPosition(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Bluelight::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getPositionOnLane()
virtual double SUMOVehicle::getPositionOnLane () const pure virtual
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implemented in MSVehicle, and MEVehicle.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSVTypeProbe::execute(), MSTransportable::Stage_Driving::getEdgePos(), MSE2Collector::makeVehicleInfo(), MSDevice_Vehroutes::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSInductLoop::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Battery::notifyMove(), MSBaseVehicle::onDepart(), MSTransportable::Stage_Driving::setArrived(), MSTransportable::Stage_Driving::setVehicle(), MSStopOut::stopEnded(), MSEmissionExport::write(), MSFCDExport::write(), MSXMLRawOut::writeVehicle(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getPreviousSpeed()
virtual double SUMOVehicle::getPreviousSpeed () const pure virtual
Returns the vehicle's previous speed.
Returns
The vehicle's speed
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSE3Collector::MSE3EntryReminder::notifyMove(), MSInstantInductLoop::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), and MSE3Collector::MSE3LeaveReminder::notifyMove().
getRoute()
virtual const MSRoute& SUMOVehicle::getRoute () const pure virtual
Returns the current route.
Implemented in MSBaseVehicle.
Referenced by MSDevice_Vehroutes::addRoute(), MSVehicleControl::addVehicle(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDevice_Tripinfo::generateOutput(), MSTriggeredRerouter::getCurrentReroute(), MSRouteProbe::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), MSTriggeredRerouter::rerouteParkingArea(), MSTransportable::Stage_Driving::setArrived(), MSTransportable::Stage_Driving::setVehicle(), MSEmissionExport::write(), MSDevice_Vehroutes::writeOutput(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getSlope()
virtual double SUMOVehicle::getSlope () const pure virtual
Returns the slope of the road at vehicle's position.
Returns
The slope
Implemented in MSVehicle, MSBaseVehicle, and MEVehicle.
Referenced by MSDevice_Battery::notifyMove(), MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), MSFCDExport::write(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getSpeed()
virtual double SUMOVehicle::getSpeed () const pure virtual
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implemented in MSVehicle, and MEVehicle.
Referenced by MSChargingStation::addChargeValueForOutput(), MSE2Collector::calculateTimeLossAndTimeOnDetector(), MSInductLoop::collectVehiclesOnDet(), MSE3Collector::detectorUpdate(), MSE3Collector::enter(), MSVTypeProbe::execute(), MSNet::getHaltingVehicleNumber(), MSTransportable::Stage_Driving::getSpeed(), MSNet::getVehicleMeanSpeeds(), MSE3Collector::leave(), MSDevice_Vehroutes::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSInstantInductLoop::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Battery::notifyMove(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::writeVehicle(), MSXMLRawOut::writeVehicle(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getVClass()
virtual SUMOVehicleClass SUMOVehicle::getVClass () const pure virtual
Returns the vehicle's access class.
Returns
The vehicle's access class
Implemented in MSBaseVehicle.
Referenced by MSLane::getVehicleMaxSpeed(), MSEdge::prohibits(), MSDevice_Routing::reroute(), MSTransportable::Stage_Driving::setVehicle(), MSVehicleControl::vehicleDeparted(), and ~SUMOVehicle().
getVehicleType()
virtual const MSVehicleType& SUMOVehicle::getVehicleType () const pure virtual
Returns the vehicle's type.
Returns
The vehicle's type
Implemented in MSBaseVehicle.
Referenced by MSChargingStation::addChargeValueForOutput(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSInductLoop::collectVehiclesOnDet(), MSDevice::equippedByDefaultAssignmentOptions(), MSVTypeProbe::execute(), MSDevice_Tripinfo::generateOutput(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSStoppingPlace::getLastFreePos(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSEdge::insertVehicle(), MSInductLoop::leaveDetectorByMove(), MSE2Collector::makeVehicleInfo(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyMove(), MSInstantInductLoop::notifyMove(), MSDevice_Emissions::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), MSE3Collector::MSE3LeaveReminder::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSDevice_SSM::requestsTrajectories(), MSLink::setApproaching(), MSStopOut::stopEnded(), MSLane::succLinkSec(), MSDevice_SSM::useGeoCoords(), MSDetectorFileOutput::vehicleApplies(), MSVehicleControl::vehicleDeparted(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSDevice_Vehroutes::writeOutput(), MSAmitranTrajectories::writeVehicle(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
getWaitingTime()
virtual SUMOTime SUMOVehicle::getWaitingTime () const pure virtual
Implemented in MSVehicle, and MEVehicle.
Referenced by MSBaseVehicle::getImpatience(), MSTriggeredRerouter::notifyEnter(), MSDevice_Tripinfo::notifyMoveInternal(), and ~SUMOVehicle().
hasArrived()
virtual bool SUMOVehicle::hasArrived () const pure virtual
Returns whether this vehicle has arrived.
Implemented in MSBaseVehicle, MSVehicle, and MEVehicle.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and ~SUMOVehicle().
hasDeparted()
virtual bool SUMOVehicle::hasDeparted () const pure virtual
Returns whether this vehicle has departed.
Implemented in MSBaseVehicle.
Referenced by MSDevice_Vehroutes::addRoute(), MSStateHandler::closeVehicle(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), and ~SUMOVehicle().
hasValidRoute()
virtual bool SUMOVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const pure virtual
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implemented in MSBaseVehicle.
Referenced by ~SUMOVehicle().
isFrontOnLane()
virtual bool SUMOVehicle::isFrontOnLane (const MSLane *) const pure virtual
Returns the information whether the front of the vehhicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by ~SUMOVehicle().
isOnRoad()
virtual bool SUMOVehicle::isOnRoad () const pure virtual
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Implemented in MSVehicle, MSBaseVehicle, and MEVehicle.
Referenced by MSVTypeProbe::execute(), MSNet::getHaltingVehicleNumber(), MSNet::getVehicleMeanSpeeds(), GUIMEVehicleControl::insertVehicleIDs(), GUIVehicleControl::insertVehicleIDs(), MSE2Collector::notifyEnter(), MSInsertionControl::tryInsert(), MSDevice_SSM::updateAndWriteOutput(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::writeVehicle(), MSFullExport::writeVehicles(), and ~SUMOVehicle().
isParking()
virtual bool SUMOVehicle::isParking () const pure virtual
Returns the information whether the vehicle is parked.
Returns
Whether the vehicle is parked
Implemented in MSVehicle, and MEVehicle.
Referenced by GUIVehicleControl::insertVehicleIDs(), MSFCDExport::write(), and ~SUMOVehicle().
isRemoteControlled()
virtual bool SUMOVehicle::isRemoteControlled () const pure virtual
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Implemented in MSVehicle, and MSBaseVehicle.
Referenced by MSNet::getHaltingVehicleNumber(), MSNet::getVehicleMeanSpeeds(), MSFCDExport::write(), and ~SUMOVehicle().
isSelected()
virtual bool SUMOVehicle::isSelected () const pure virtual
whether this vehicle is selected in the GUI
Implemented in MSBaseVehicle, and GUIVehicle.
Referenced by ~SUMOVehicle().
isStopped()
virtual bool SUMOVehicle::isStopped () const pure virtual
Returns whether the vehicle is at a stop.
Returns
Whether the has stopped
Implemented in MSVehicle, and MEVehicle.
Referenced by MSNet::getVehicleMeanSpeeds(), MSDevice_Transportable::notifyMove(), MSDevice_Tripinfo::notifyMove(), MSDevice_Transportable::removeTransportable(), and ~SUMOVehicle().
isStoppedInRange()
virtual bool SUMOVehicle::isStoppedInRange (double pos) const pure virtual
Returns whether the vehicle is stoped in range of the given position.
Implemented in MSVehicle, and MEVehicle.
Referenced by ~SUMOVehicle().
isStoppedTriggered()
virtual bool SUMOVehicle::isStoppedTriggered () const pure virtual
Returns whether the vehicle is at a stop and waiting for a person or container to continue.
Implemented in MSVehicle, and MEVehicle.
Referenced by ~SUMOVehicle().
loadState()
virtual void SUMOVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) pure virtual
Loads the state of this vehicle from the given description.
Implemented in MSVehicle, and MEVehicle.
Referenced by MSStateHandler::closeVehicle(), and ~SUMOVehicle().
onDepart()
virtual void SUMOVehicle::onDepart () pure virtual
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implemented in MSBaseVehicle.
Referenced by ~SUMOVehicle().
replaceParkingArea()
virtual bool SUMOVehicle::replaceParkingArea (MSParkingArea * parkingArea, std::string & errorMsg) pure virtual
Replaces a stop.
The stop replace the next stop into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implemented in MSVehicle, and MEVehicle.
Referenced by ~SUMOVehicle().
replaceRoute()
virtual bool SUMOVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0, bool addStops = true, bool removeStops = true) pure virtual
Replaces the current route by the given one.
Implemented in MEVehicle, and MSVehicle.
Referenced by MSTriggeredRerouter::notifyEnter(), MSDevice_Routing::preInsertionReroute(), MSBaseVehicle::replaceRouteEdges(), and ~SUMOVehicle().
replaceRouteEdges()
virtual bool SUMOVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false, bool removeStops = true) pure virtual
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
[in] removeStops Whether stops should be removed if they do not fit onto the new route
Returns
Whether the new route was accepted
Implemented in MSBaseVehicle.
Referenced by ~SUMOVehicle().
reroute()
virtual void SUMOVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) pure virtual
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implemented in MSBaseVehicle.
Referenced by MSDevice_Routing::reroute(), and ~SUMOVehicle().
saveState()
virtual void SUMOVehicle::saveState (OutputDevice & out) pure virtual
Saves the states of a vehicle.
Implemented in MSVehicle, MSBaseVehicle, and MEVehicle.
Referenced by ~SUMOVehicle().
setArrivalPos()
virtual void SUMOVehicle::setArrivalPos (double arrivalPos) pure virtual
Sets this vehicle's desired arrivalPos for its current route.
Implemented in MSBaseVehicle.
Referenced by ~SUMOVehicle().
setChosenSpeedFactor()
virtual void SUMOVehicle::setChosenSpeedFactor (const double factor) pure virtual
Implemented in MSBaseVehicle.
Referenced by MSEdge::insertVehicle(), MSDevice_Routing::reroute(), and ~SUMOVehicle().
succEdge()
virtual const MSEdge* SUMOVehicle::succEdge (int nSuccs) const pure virtual
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) than nSuccs, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implemented in MSBaseVehicle.
Referenced by MSLane::succLinkSec(), and ~SUMOVehicle().
The documentation for this class was generated from the following file:
SUMOVehicle.h