SUMO - Simulation of Urban MObility: GNEChange_CalibratorItem Class Reference
GNEChange_CalibratorItem Class Reference
#include <GNEChange_CalibratorItem.h>
Public Member Functions
GNEChange_CalibratorItem (GNECalibratorFlow *calibratorFlow, bool forward)
Constructor.
GNEChange_CalibratorItem (GNECalibratorRoute *calibratorRoute, bool forward)
Constructor.
GNEChange_CalibratorItem (GNECalibratorVehicleType *calibratorVehicleType, bool forward)
Constructor.
virtual FXuint size () const
return actual size
~GNEChange_CalibratorItem ()
Destructor.
inherited from GNEChange
get undo Name
FXString undoName () const
return undoName
FXString redoName () const
get Redo name
void undo ()
undo action
void redo ()
redo action
Protected Attributes
bool myForward
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
GNENet * myNet
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Private Attributes
GNECalibratorFlow * myCalibratorFlow
modified calibrator flow
GNECalibratorRoute * myCalibratorRoute
modified calibrator route
GNECalibratorVehicleType * myCalibratorVehicleType
modified calibrator vehicle type
Detailed Description
A change to the network selection
Definition at line 54 of file GNEChange_CalibratorItem.h.
Constructor & Destructor Documentation
GNEChange_CalibratorItem() [1/3]
GNEChange_CalibratorItem::GNEChange_CalibratorItem (GNECalibratorFlow * calibratorFlow, bool forward)
Constructor.
Parameters
[in] calibratorFlow calibrator flow to be added or removed
[in] forward Whether to create/delete (true/false)
Definition at line 51 of file GNEChange_CalibratorItem.cpp.
GNEChange_CalibratorItem() [2/3]
GNEChange_CalibratorItem::GNEChange_CalibratorItem (GNECalibratorRoute * calibratorRoute, bool forward)
Constructor.
Parameters
[in] calibratorRoute calibrator route to be added or removed
[in] forward Whether to create/delete (true/false)
Definition at line 60 of file GNEChange_CalibratorItem.cpp.
References GNEReferenceCounter::incRef(), and myCalibratorRoute.
GNEChange_CalibratorItem() [3/3]
GNEChange_CalibratorItem::GNEChange_CalibratorItem (GNECalibratorVehicleType * calibratorVehicleType, bool forward)
Constructor.
Parameters
[in] calibratorVehicleType calibrator vehicle type to be added or removed
[in] forward Whether to create/delete (true/false)
Definition at line 69 of file GNEChange_CalibratorItem.cpp.
References GNEReferenceCounter::incRef(), and myCalibratorVehicleType.
~GNEChange_CalibratorItem()
GNEChange_CalibratorItem::~GNEChange_CalibratorItem ()
Destructor.
Definition at line 78 of file GNEChange_CalibratorItem.cpp.
References GNEReferenceCounter::decRef(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), OptionsCont::getBool(), GNECalibratorRoute::getCalibratorParent(), GNECalibratorVehicleType::getCalibratorParent(), GNECalibratorFlow::getCalibratorParent(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), myCalibratorFlow, myCalibratorRoute, myCalibratorVehicleType, GNEChange::myNet, GNENet::retrieveCalibratorFlow(), GNENet::retrieveCalibratorRoute(), GNENet::retrieveCalibratorVehicleType(), GNEReferenceCounter::unreferenced(), and WRITE_WARNING.
Member Function Documentation
redo()
void GNEChange_CalibratorItem::redo () virtual
redo action
Reimplemented from GNEChange.
Definition at line 187 of file GNEChange_CalibratorItem.cpp.
References GNECalibrator::addCalibratorFlow(), GNECalibrator::addCalibratorRoute(), GNECalibrator::addCalibratorVehicleType(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), GNECalibratorRoute::getCalibratorParent(), GNECalibratorVehicleType::getCalibratorParent(), GNECalibratorFlow::getCalibratorParent(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), GNENet::insertCalibratorFlow(), GNENet::insertCalibratorRoute(), GNENet::insertCalibratorVehicleType(), myCalibratorFlow, myCalibratorRoute, myCalibratorVehicleType, GNEChange::myForward, GNEChange::myNet, GNECalibrator::removeCalibratorFlow(), GNECalibrator::removeCalibratorRoute(), GNECalibrator::removeCalibratorVehicleType(), GNENet::requiereSaveAdditionals(), and WRITE_WARNING.
redoName()
FXString GNEChange_CalibratorItem::redoName () const virtual
get Redo name
Reimplemented from GNEChange.
Definition at line 265 of file GNEChange_CalibratorItem.cpp.
References GNEAttributeCarrier::getTag(), myCalibratorFlow, myCalibratorRoute, myCalibratorVehicleType, and toString().
size()
FXuint GNEChange::size () const virtual inherited
return actual size
Definition at line 52 of file GNEChange.cpp.
undo()
void GNEChange_CalibratorItem::undo () virtual
undo action
Reimplemented from GNEChange.
Definition at line 123 of file GNEChange_CalibratorItem.cpp.
References GNECalibrator::addCalibratorFlow(), GNECalibrator::addCalibratorRoute(), GNECalibrator::addCalibratorVehicleType(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), GNECalibratorRoute::getCalibratorParent(), GNECalibratorVehicleType::getCalibratorParent(), GNECalibratorFlow::getCalibratorParent(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), GNENet::insertCalibratorFlow(), GNENet::insertCalibratorRoute(), GNENet::insertCalibratorVehicleType(), myCalibratorFlow, myCalibratorRoute, myCalibratorVehicleType, GNEChange::myForward, GNEChange::myNet, GNECalibrator::removeCalibratorFlow(), GNECalibrator::removeCalibratorRoute(), GNECalibrator::removeCalibratorVehicleType(), GNENet::requiereSaveAdditionals(), and WRITE_WARNING.
undoName()
FXString GNEChange_CalibratorItem::undoName () const virtual
return undoName
Reimplemented from GNEChange.
Definition at line 251 of file GNEChange_CalibratorItem.cpp.
References GNEAttributeCarrier::getTag(), myCalibratorFlow, myCalibratorRoute, myCalibratorVehicleType, and toString().
Field Documentation
myCalibratorFlow
GNECalibratorFlow* GNEChange_CalibratorItem::myCalibratorFlow private
modified calibrator flow
Definition at line 96 of file GNEChange_CalibratorItem.h.
Referenced by redo(), redoName(), undo(), undoName(), and ~GNEChange_CalibratorItem().
myCalibratorRoute
GNECalibratorRoute* GNEChange_CalibratorItem::myCalibratorRoute private
modified calibrator route
Definition at line 99 of file GNEChange_CalibratorItem.h.
Referenced by GNEChange_CalibratorItem(), redo(), redoName(), undo(), undoName(), and ~GNEChange_CalibratorItem().
myCalibratorVehicleType
GNECalibratorVehicleType* GNEChange_CalibratorItem::myCalibratorVehicleType private
modified calibrator vehicle type
Definition at line 102 of file GNEChange_CalibratorItem.h.
Referenced by GNEChange_CalibratorItem(), redo(), redoName(), undo(), undoName(), and ~GNEChange_CalibratorItem().
myForward
bool GNEChange::myForward protected inherited
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
Definition at line 86 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Additional::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), redo(), GNEChange_RerouterItem::redo(), GNEChange_Shape::redoName(), GNEChange_Junction::redoName(), GNEChange_Selection::redoName(), GNEChange_TLS::redoName(), GNEChange_Additional::redoName(), GNEChange_Connection::redoName(), GNEChange_Lane::redoName(), GNEChange_Edge::redoName(), GNEChange_Crossing::redoName(), GNEChange_Shape::undo(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), undo(), GNEChange_RerouterItem::undo(), GNEChange_Shape::undoName(), GNEChange_Junction::undoName(), GNEChange_Selection::undoName(), GNEChange_TLS::undoName(), GNEChange_Lane::undoName(), GNEChange_Additional::undoName(), GNEChange_Connection::undoName(), GNEChange_Edge::undoName(), and GNEChange_Crossing::undoName().
myNet
GNENet* GNEChange::myNet protected inherited
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Definition at line 81 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_Selection::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Additional::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), redo(), GNEChange_RerouterItem::redo(), GNEChange_Shape::undo(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Additional::undo(), GNEChange_Lane::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), undo(), GNEChange_RerouterItem::undo(), GNEChange_Additional::~GNEChange_Additional(), ~GNEChange_CalibratorItem(), GNEChange_Crossing::~GNEChange_Crossing(), and GNEChange_Shape::~GNEChange_Shape().
The documentation for this class was generated from the following files:
GNEChange_CalibratorItem.h
GNEChange_CalibratorItem.cpp