SUMO - Simulation of Urban MObility: GUIMessageWindow Class Reference
GUIMessageWindow Class Reference
A logging window for the gui.
#include <GUIMessageWindow.h>
Data Structures
class MsgOutputDevice
Public Member Functions
void addSeparator ()
Adds a a separator to this log window.
void appendMsg (GUIEventType eType, const std::string &msg)
Adds new text to the window.
void clear ()
Clears the window.
GUIMessageWindow (FXComposite *parent)
Constructor.
void registerMsgHandlers ()
register and unregister message handlers
virtual void setCursorPos (FXint pos, FXbool notify=FALSE)
void unregisterMsgHandlers ()
~GUIMessageWindow ()
Destructor.
Static Public Member Functions
static void enableLocateLinks (const bool val)
switch locate links on and off
static bool locateLinksEnabled ()
ask whether locate links is enabled
Private Member Functions
const GUIGlObject * getActiveStringObject (const FXString &text, const FXint pos, const FXint lineS, const FXint lineE) const
Private Attributes
OutputDevice * myErrorRetriever
The instances of message retriever encapsulations.
OutputDevice * myMessageRetriever
FXHiliteStyle * myStyles
The text colors used.
OutputDevice * myWarningRetriever
Static Private Attributes
static bool myLocateLinks = true
whether messages are linked to the GUI elements
Detailed Description
A logging window for the gui.
This class displays messages incoming to the gui from either the load or the run thread.
The text is colored in dependence to its type (messages: green, warnings: yellow, errors: red)
Each time a new message is passed, the window is reopened.
Definition at line 60 of file GUIMessageWindow.h.
Constructor & Destructor Documentation
GUIMessageWindow()
GUIMessageWindow::GUIMessageWindow (FXComposite * parent)
Constructor.
Parameters
[in] parent The parent window
Definition at line 51 of file GUIMessageWindow.cpp.
References myStyles.
~GUIMessageWindow()
GUIMessageWindow::~GUIMessageWindow ()
Destructor.
Definition at line 99 of file GUIMessageWindow.cpp.
References myErrorRetriever, myMessageRetriever, myStyles, and myWarningRetriever.
Member Function Documentation
addSeparator()
void GUIMessageWindow::addSeparator ()
Adds a a separator to this log window.
Definition at line 210 of file GUIMessageWindow.cpp.
Referenced by GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::onCmdComputeJunctionsVolatile(), GNEApplicationWindow::onCmdSaveAdditionals(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onCmdSaveNetwork(), and GNEApplicationWindow::onCmdSaveShapes().
appendMsg()
void GUIMessageWindow::appendMsg (GUIEventType eType, const std::string & msg)
Adds new text to the window.
The type of the text is determined by the first parameter
Parameters
[in] eType The type of the event the message was generated by
[in] msg The message
See also
GUIEventType
Definition at line 158 of file GUIMessageWindow.cpp.
References EVENT_ERROR_OCCURED, EVENT_MESSAGE_OCCURED, EVENT_WARNING_OCCURED, getActiveStringObject(), GUIGlObject::getGlID(), GUIGlObjectStorage::gIDStorage, myLocateLinks, and GUIGlObjectStorage::unblockObject().
Referenced by GUIApplicationWindow::handleEvent_Message(), GNEApplicationWindow::handleEvent_Message(), GNEApplicationWindow::onCmdSaveAdditionals(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onCmdSaveNetwork(), GNEApplicationWindow::onCmdSaveShapes(), and GUIMessageWindow::MsgOutputDevice::postWriteHook().
clear()
void GUIMessageWindow::clear ()
Clears the window.
Definition at line 223 of file GUIMessageWindow.cpp.
Referenced by GUIApplicationWindow::onCmdClearMsgWindow(), and GNEApplicationWindow::onCmdClearMsgWindow().
enableLocateLinks()
static void GUIMessageWindow::enableLocateLinks (const bool val) inline static
switch locate links on and off
Definition at line 99 of file GUIMessageWindow.h.
References myLocateLinks.
Referenced by GUIDialog_AppSettings::onCmdOk().
getActiveStringObject()
const GUIGlObject * GUIMessageWindow::getActiveStringObject (const FXString & text, const FXint pos, const FXint lineS, const FXint lineE) const private
Definition at line 108 of file GUIMessageWindow.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, and MAX2().
Referenced by appendMsg(), and setCursorPos().
locateLinksEnabled()
static bool GUIMessageWindow::locateLinksEnabled () inline static
ask whether locate links is enabled
Definition at line 104 of file GUIMessageWindow.h.
References myLocateLinks.
registerMsgHandlers()
void GUIMessageWindow::registerMsgHandlers ()
register and unregister message handlers
Definition at line 236 of file GUIMessageWindow.cpp.
References MsgHandler::addRetriever(), EVENT_ERROR_OCCURED, EVENT_MESSAGE_OCCURED, EVENT_WARNING_OCCURED, MsgHandler::getErrorInstance(), MsgHandler::getMessageInstance(), MsgHandler::getWarningInstance(), myErrorRetriever, myMessageRetriever, and myWarningRetriever.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded().
setCursorPos()
void GUIMessageWindow::setCursorPos (FXint pos, FXbool notify = FALSE) virtual
Definition at line 135 of file GUIMessageWindow.cpp.
References getActiveStringObject(), GUIGlObject::getGlID(), GUIMainWindow::getInstance(), GUIMainWindow::getViewByID(), GUIMainWindow::getViewIDs(), GUIGlObjectStorage::gIDStorage, gSelected, main(), myLocateLinks, GUIGlChildWindow::setView(), GUISelectedStorage::toggleSelection(), and GUIGlObjectStorage::unblockObject().
unregisterMsgHandlers()
void GUIMessageWindow::unregisterMsgHandlers ()
Definition at line 250 of file GUIMessageWindow.cpp.
References MsgHandler::getErrorInstance(), MsgHandler::getMessageInstance(), MsgHandler::getWarningInstance(), myErrorRetriever, myMessageRetriever, myWarningRetriever, and MsgHandler::removeRetriever().
Referenced by GNEApplicationWindow::closeAllWindows().
Field Documentation
myErrorRetriever
OutputDevice* GUIMessageWindow::myErrorRetriever private
The instances of message retriever encapsulations.
Definition at line 144 of file GUIMessageWindow.h.
Referenced by registerMsgHandlers(), unregisterMsgHandlers(), and ~GUIMessageWindow().
myLocateLinks
bool GUIMessageWindow::myLocateLinks = true static private
whether messages are linked to the GUI elements
Definition at line 138 of file GUIMessageWindow.h.
Referenced by appendMsg(), enableLocateLinks(), locateLinksEnabled(), and setCursorPos().
myMessageRetriever
OutputDevice * GUIMessageWindow::myMessageRetriever private
Definition at line 144 of file GUIMessageWindow.h.
Referenced by registerMsgHandlers(), unregisterMsgHandlers(), and ~GUIMessageWindow().
myStyles
FXHiliteStyle* GUIMessageWindow::myStyles private
The text colors used.
Definition at line 141 of file GUIMessageWindow.h.
Referenced by GUIMessageWindow(), and ~GUIMessageWindow().
myWarningRetriever
OutputDevice * GUIMessageWindow::myWarningRetriever private
Definition at line 144 of file GUIMessageWindow.h.
Referenced by registerMsgHandlers(), unregisterMsgHandlers(), and ~GUIMessageWindow().
The documentation for this class was generated from the following files:
GUIMessageWindow.h
GUIMessageWindow.cpp