SUMO - Simulation of Urban MObility: GNECrossingFrame::crossingParameters Class Reference
GNECrossingFrame::crossingParameters Class Reference
#include <GNECrossingFrame.h>
Public Member Functions
void clearEdges ()
clear edges
crossingParameters (GNECrossingFrame *crossingFrameParent, GNECrossingFrame::edgesSelector *es)
FOX-declaration.
void disableCrossingParameters ()
disable crossing parameters and clear parameters
void enableCrossingParameters ()
enable crossing parameters and set the default value of parameters
const RGBColor & getCandidateColor () const
get candidate color
std::vector< NBEdge * > getCrossingEdges () const
get crossing NBedges
bool getCrossingPriority () const
get crossing priority
double getCrossingWidth () const
get crossing width
const RGBColor & getSelectedColor () const
get selected color
void invertEdges (GNEJunction *parentJunction)
invert edges
bool isCrossingParametersEnabled () const
check if currently the crossingParameters is enabled
bool isCurrentParametersValid () const
check if current parameters are valid
void markEdge (GNEEdge *edge)
mark or dismark edge
void useSelectedEdges (GNEJunction *parentJunction)
use selected eges
~crossingParameters ()
destructor
FOX-callbacks
Called when user set a value
long onCmdSetAttribute (FXObject *, FXSelector, void *)
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
crossingParameters ()
FOX needs this.
Private Attributes
FXTextField * myCrossingEdges
TextField for edges.
FXLabel * myCrossingEdgesLabel
Label for edges.
GNECrossingFrame * myCrossingFrameParent
pointer to GNECrossingFrame parent
FXCheckButton * myCrossingPriorityCheckButton
CheckBox for Priority.
FXLabel * myCrossingPriorityLabel
Label for Priority.
FXTextField * myCrossingWidth
TextField for width.
FXLabel * myCrossingWidthLabel
Label for width.
bool myCurrentParametersValid
flag to check if current parameters are valid
std::vector< GNEEdge * > myCurrentSelectedEdges
current selected edges
GNECrossingFrame::edgesSelector * myEdgeSelector
pointer to edge selector
FXButton * myHelpCrossingAttribute
button for help
Static Private Attributes
static RGBColor myCandidateColor
color for candidate edges
static RGBColor mySelectedColor
color for selected edges
Detailed Description
Definition at line 131 of file GNECrossingFrame.h.
Constructor & Destructor Documentation
crossingParameters() [1/2]
GNECrossingFrame::crossingParameters::crossingParameters (GNECrossingFrame * crossingFrameParent, GNECrossingFrame::edgesSelector * es)
FOX-declaration.
constructor
Definition at line 207 of file GNECrossingFrame.cpp.
References RGBColor::GREEN, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonRectangular, GUIDesignCheckButtonAttribute, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, MID_GNE_SET_ATTRIBUTE, MID_HELP, myCandidateColor, myCrossingEdges, myCrossingEdgesLabel, myCrossingPriorityCheckButton, myCrossingPriorityLabel, myCrossingWidth, myCrossingWidthLabel, myHelpCrossingAttribute, mySelectedColor, SUMO_ATTR_EDGES, SUMO_ATTR_PRIORITY, SUMO_ATTR_WIDTH, and toString().
~crossingParameters()
GNECrossingFrame::crossingParameters::~crossingParameters ()
destructor
Definition at line 240 of file GNECrossingFrame.cpp.
crossingParameters() [2/2]
GNECrossingFrame::crossingParameters::crossingParameters () inline protected
FOX needs this.
Definition at line 192 of file GNECrossingFrame.h.
Member Function Documentation
clearEdges()
void GNECrossingFrame::crossingParameters::clearEdges ()
clear edges
Definition at line 310 of file GNECrossingFrame.cpp.
References myCrossingEdges, and onCmdSetAttribute().
Referenced by GNECrossingFrame::addCrossing(), and GNECrossingFrame::edgesSelector::onCmdClearSelection().
disableCrossingParameters()
void GNECrossingFrame::crossingParameters::disableCrossingParameters ()
disable crossing parameters and clear parameters
Definition at line 262 of file GNECrossingFrame.cpp.
References myCrossingEdges, myCrossingEdgesLabel, myCrossingFrameParent, myCrossingPriorityCheckButton, myCrossingPriorityLabel, myCrossingWidth, myCrossingWidthLabel, myHelpCrossingAttribute, and GNECrossingFrame::setCreateCrossingButton().
Referenced by GNECrossingFrame::edgesSelector::disableEdgeSelector().
enableCrossingParameters()
void GNECrossingFrame::crossingParameters::enableCrossingParameters ()
enable crossing parameters and set the default value of parameters
Definition at line 244 of file GNECrossingFrame.cpp.
References myCrossingEdges, myCrossingEdgesLabel, myCrossingPriorityCheckButton, myCrossingPriorityLabel, myCrossingWidth, myCrossingWidthLabel, myHelpCrossingAttribute, onCmdSetAttribute(), SUMO_ATTR_PRIORITY, SUMO_ATTR_WIDTH, and SUMO_TAG_CROSSING.
Referenced by GNECrossingFrame::addCrossing().
getCandidateColor()
const RGBColor & GNECrossingFrame::crossingParameters::getCandidateColor () const
get candidate color
Definition at line 379 of file GNECrossingFrame.cpp.
References myCandidateColor.
Referenced by GNECrossingFrame::GNECrossingFrame().
getCrossingEdges()
std::vector< NBEdge * > GNECrossingFrame::crossingParameters::getCrossingEdges () const
get crossing NBedges
Definition at line 346 of file GNECrossingFrame.cpp.
References myCurrentSelectedEdges.
Referenced by GNECrossingFrame::onCmdCreateCrossing().
getCrossingPriority()
bool GNECrossingFrame::crossingParameters::getCrossingPriority () const
get crossing priority
Definition at line 357 of file GNECrossingFrame.cpp.
References myCrossingPriorityCheckButton.
Referenced by GNECrossingFrame::onCmdCreateCrossing().
getCrossingWidth()
double GNECrossingFrame::crossingParameters::getCrossingWidth () const
get crossing width
Definition at line 373 of file GNECrossingFrame.cpp.
References myCrossingWidth.
Referenced by GNECrossingFrame::onCmdCreateCrossing().
getSelectedColor()
const RGBColor & GNECrossingFrame::crossingParameters::getSelectedColor () const
get selected color
Definition at line 385 of file GNECrossingFrame.cpp.
References mySelectedColor.
Referenced by GNECrossingFrame::GNECrossingFrame().
invertEdges()
void GNECrossingFrame::crossingParameters::invertEdges (GNEJunction * parentJunction)
invert edges
Definition at line 318 of file GNECrossingFrame.cpp.
References GNEJunction::getGNEEdges(), joinToString(), myCrossingEdges, myCurrentSelectedEdges, and onCmdSetAttribute().
Referenced by GNECrossingFrame::edgesSelector::onCmdInvertSelection().
isCrossingParametersEnabled()
bool GNECrossingFrame::crossingParameters::isCrossingParametersEnabled () const
check if currently the crossingParameters is enabled
Definition at line 281 of file GNECrossingFrame.cpp.
References myCrossingEdgesLabel.
isCurrentParametersValid()
bool GNECrossingFrame::crossingParameters::isCurrentParametersValid () const
check if current parameters are valid
Definition at line 367 of file GNECrossingFrame.cpp.
References myCurrentParametersValid.
Referenced by GNECrossingFrame::onCmdCreateCrossing().
markEdge()
void GNECrossingFrame::crossingParameters::markEdge (GNEEdge * edge)
mark or dismark edge
Definition at line 287 of file GNECrossingFrame.cpp.
References GNECrossingFrame::edgesSelector::getCurrentJunction(), GNECrossingFrame::getEdgeSelector(), GNEJunction::getGNEEdges(), GNEAttributeCarrier::getID(), joinToString(), myCrossingEdges, myCrossingFrameParent, and onCmdSetAttribute().
Referenced by GNECrossingFrame::addCrossing().
onCmdHelp()
long GNECrossingFrame::crossingParameters::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 470 of file GNECrossingFrame.cpp.
References GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::getDefinition(), GUIIconSubSys::getIcon(), GUIDesignButtonOK, GUIDesignDialogBox, ICON_ACCEPT, GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), MID_TABLE, SUMO_TAG_CROSSING, and toString().
onCmdSetAttribute()
long GNECrossingFrame::crossingParameters::onCmdSetAttribute (FXObject * , FXSelector , void *)
Definition at line 391 of file GNECrossingFrame.cpp.
References GNECrossingFrame::edgesSelector::getCurrentJunction(), GNECrossingFrame::getEdgeSelector(), GNEJunction::getGNEEdges(), GNEViewNet::getNet(), GNEFrame::getViewNet(), myCandidateColor, myCrossingEdges, myCrossingFrameParent, myCrossingPriorityCheckButton, myCrossingWidth, myCurrentParametersValid, myCurrentSelectedEdges, myEdgeSelector, mySelectedColor, GNENet::retrieveEdge(), and GNECrossingFrame::setCreateCrossingButton().
Referenced by clearEdges(), enableCrossingParameters(), invertEdges(), markEdge(), and useSelectedEdges().
useSelectedEdges()
void GNECrossingFrame::crossingParameters::useSelectedEdges (GNEJunction * parentJunction)
use selected eges
Definition at line 332 of file GNECrossingFrame.cpp.
References GNEJunction::getGNEEdges(), gSelected, GUISelectedStorage::isSelected(), joinToString(), myCrossingEdges, and onCmdSetAttribute().
Referenced by GNECrossingFrame::edgesSelector::onCmdUseSelectedEdges().
Field Documentation
myCandidateColor
RGBColor GNECrossingFrame::crossingParameters::myCandidateColor static private
color for candidate edges
Definition at line 229 of file GNECrossingFrame.h.
Referenced by crossingParameters(), getCandidateColor(), and onCmdSetAttribute().
myCrossingEdges
FXTextField* GNECrossingFrame::crossingParameters::myCrossingEdges private
TextField for edges.
Definition at line 208 of file GNECrossingFrame.h.
Referenced by clearEdges(), crossingParameters(), disableCrossingParameters(), enableCrossingParameters(), invertEdges(), markEdge(), onCmdSetAttribute(), and useSelectedEdges().
myCrossingEdgesLabel
FXLabel* GNECrossingFrame::crossingParameters::myCrossingEdgesLabel private
Label for edges.
Definition at line 205 of file GNECrossingFrame.h.
Referenced by crossingParameters(), disableCrossingParameters(), enableCrossingParameters(), and isCrossingParametersEnabled().
myCrossingFrameParent
GNECrossingFrame* GNECrossingFrame::crossingParameters::myCrossingFrameParent private
pointer to GNECrossingFrame parent
Definition at line 196 of file GNECrossingFrame.h.
Referenced by disableCrossingParameters(), markEdge(), and onCmdSetAttribute().
myCrossingPriorityCheckButton
FXCheckButton* GNECrossingFrame::crossingParameters::myCrossingPriorityCheckButton private
CheckBox for Priority.
Definition at line 214 of file GNECrossingFrame.h.
Referenced by crossingParameters(), disableCrossingParameters(), enableCrossingParameters(), getCrossingPriority(), and onCmdSetAttribute().
myCrossingPriorityLabel
FXLabel* GNECrossingFrame::crossingParameters::myCrossingPriorityLabel private
Label for Priority.
Definition at line 211 of file GNECrossingFrame.h.
Referenced by crossingParameters(), disableCrossingParameters(), and enableCrossingParameters().
myCrossingWidth
FXTextField* GNECrossingFrame::crossingParameters::myCrossingWidth private
TextField for width.
Definition at line 220 of file GNECrossingFrame.h.
Referenced by crossingParameters(), disableCrossingParameters(), enableCrossingParameters(), getCrossingWidth(), and onCmdSetAttribute().
myCrossingWidthLabel
FXLabel* GNECrossingFrame::crossingParameters::myCrossingWidthLabel private
Label for width.
Definition at line 217 of file GNECrossingFrame.h.
Referenced by crossingParameters(), disableCrossingParameters(), and enableCrossingParameters().
myCurrentParametersValid
bool GNECrossingFrame::crossingParameters::myCurrentParametersValid private
flag to check if current parameters are valid
Definition at line 226 of file GNECrossingFrame.h.
Referenced by isCurrentParametersValid(), and onCmdSetAttribute().
myCurrentSelectedEdges
std::vector<GNEEdge*> GNECrossingFrame::crossingParameters::myCurrentSelectedEdges private
current selected edges
Definition at line 202 of file GNECrossingFrame.h.
Referenced by getCrossingEdges(), invertEdges(), and onCmdSetAttribute().
myEdgeSelector
GNECrossingFrame::edgesSelector* GNECrossingFrame::crossingParameters::myEdgeSelector private
pointer to edge selector
Definition at line 199 of file GNECrossingFrame.h.
Referenced by onCmdSetAttribute().
myHelpCrossingAttribute
FXButton* GNECrossingFrame::crossingParameters::myHelpCrossingAttribute private
button for help
Definition at line 223 of file GNECrossingFrame.h.
Referenced by crossingParameters(), disableCrossingParameters(), and enableCrossingParameters().
mySelectedColor
RGBColor GNECrossingFrame::crossingParameters::mySelectedColor static private
color for selected edges
Definition at line 232 of file GNECrossingFrame.h.
Referenced by crossingParameters(), getSelectedColor(), and onCmdSetAttribute().
The documentation for this class was generated from the following files:
GNECrossingFrame.h
GNECrossingFrame.cpp