SUMO - Simulation of Urban MObility: GNECrossingFrame::edgesSelector Class Reference
GNECrossingFrame::edgesSelector Class Reference
FOX-declaration.
#include <GNECrossingFrame.h>
Public Member Functions
void disableEdgeSelector ()
disable edgeSelector
edgesSelector (FXComposite *parent, GNECrossingFrame *crossingFrameParent)
FOX-declaration.
void enableEdgeSelector (GNEJunction *currentJunction)
enable edgeSelector
const RGBColor & getCandidateColor () const
return candidate color
GNEJunction * getCurrentJunction () const
get current junction
const RGBColor & getSelectedColor () const
return selected color
void restoreEdgeColors ()
restore colors of all edges
~edgesSelector ()
destructor
FOX-callbacks
called when useSelectedEdges button edge is pressed
long onCmdUseSelectedEdges (FXObject *, FXSelector, void *)
long onCmdClearSelection (FXObject *, FXSelector, void *)
called when clear selection button is pressed
long onCmdInvertSelection (FXObject *, FXSelector, void *)
called when invert selection button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
called when help button is pressed
Protected Member Functions
edgesSelector ()
FOX needs this.
Private Attributes
FXButton * helpEdges
button for help
FXButton * myClearEdgesSelection
button for clear selection
GNECrossingFrame * myCrossingFrameParent
pointer to GNECrossingFrame parent
GNEJunction * myCurrentJunction
current Junction
FXButton * myInvertEdgesSelection
button for invert selection
FXButton * myUseSelectedEdges
CheckBox for selected edges.
Detailed Description
FOX-declaration.
Definition at line 59 of file GNECrossingFrame.h.
Constructor & Destructor Documentation
edgesSelector() [1/2]
GNECrossingFrame::edgesSelector::edgesSelector (FXComposite * parent, GNECrossingFrame * crossingFrameParent)
FOX-declaration.
constructor
Definition at line 95 of file GNECrossingFrame.cpp.
References GUIDesignButton, GUIDesignButtonRectangular, helpEdges, MID_GNE_ADDITIONALFRAME_CLEAREDGESELECTION, MID_GNE_ADDITIONALFRAME_INVERTEDGESELECTION, MID_GNE_CROSSINGFRAME_USEONLYSELECTEDEDGES, MID_HELP, myClearEdgesSelection, myInvertEdgesSelection, myUseSelectedEdges, SUMO_TAG_EDGE, and toString().
~edgesSelector()
GNECrossingFrame::edgesSelector::~edgesSelector ()
destructor
Definition at line 114 of file GNECrossingFrame.cpp.
edgesSelector() [2/2]
GNECrossingFrame::edgesSelector::edgesSelector () inline protected
FOX needs this.
Definition at line 105 of file GNECrossingFrame.h.
Member Function Documentation
disableEdgeSelector()
void GNECrossingFrame::edgesSelector::disableEdgeSelector ()
disable edgeSelector
Definition at line 146 of file GNECrossingFrame.cpp.
References GNECrossingFrame::crossingParameters::disableCrossingParameters(), GNECrossingFrame::getCrossingParameters(), helpEdges, myClearEdgesSelection, myCrossingFrameParent, myCurrentJunction, myInvertEdgesSelection, and myUseSelectedEdges.
Referenced by GNECrossingFrame::addCrossing(), and GNECrossingFrame::GNECrossingFrame().
enableEdgeSelector()
void GNECrossingFrame::edgesSelector::enableEdgeSelector (GNEJunction * currentJunction)
enable edgeSelector
Definition at line 124 of file GNECrossingFrame.cpp.
References GNEJunction::getGNEEdges(), GNEFrame::getViewNet(), gSelected, helpEdges, GUISelectedStorage::isSelected(), myClearEdgesSelection, myCrossingFrameParent, myCurrentJunction, myInvertEdgesSelection, myUseSelectedEdges, and restoreEdgeColors().
Referenced by GNECrossingFrame::addCrossing().
getCandidateColor()
const RGBColor& GNECrossingFrame::edgesSelector::getCandidateColor () const
return candidate color
getCurrentJunction()
GNEJunction * GNECrossingFrame::edgesSelector::getCurrentJunction () const
get current junction
Definition at line 118 of file GNECrossingFrame.cpp.
References myCurrentJunction.
Referenced by GNECrossingFrame::crossingParameters::markEdge(), GNECrossingFrame::onCmdCreateCrossing(), and GNECrossingFrame::crossingParameters::onCmdSetAttribute().
getSelectedColor()
const RGBColor& GNECrossingFrame::edgesSelector::getSelectedColor () const
return selected color
onCmdClearSelection()
long GNECrossingFrame::edgesSelector::onCmdClearSelection (FXObject * , FXSelector , void *)
called when clear selection button is pressed
Definition at line 183 of file GNECrossingFrame.cpp.
References GNECrossingFrame::crossingParameters::clearEdges(), GNECrossingFrame::getCrossingParameters(), and myCrossingFrameParent.
Referenced by GNECrossingFrame::onCmdCreateCrossing().
onCmdHelp()
long GNECrossingFrame::edgesSelector::onCmdHelp (FXObject * , FXSelector , void *)
called when help button is pressed
Definition at line 197 of file GNECrossingFrame.cpp.
onCmdInvertSelection()
long GNECrossingFrame::edgesSelector::onCmdInvertSelection (FXObject * , FXSelector , void *)
called when invert selection button is pressed
Definition at line 190 of file GNECrossingFrame.cpp.
References GNECrossingFrame::getCrossingParameters(), GNECrossingFrame::crossingParameters::invertEdges(), myCrossingFrameParent, and myCurrentJunction.
onCmdUseSelectedEdges()
long GNECrossingFrame::edgesSelector::onCmdUseSelectedEdges (FXObject * , FXSelector , void *)
Definition at line 176 of file GNECrossingFrame.cpp.
References GNECrossingFrame::getCrossingParameters(), myCrossingFrameParent, myCurrentJunction, and GNECrossingFrame::crossingParameters::useSelectedEdges().
restoreEdgeColors()
void GNECrossingFrame::edgesSelector::restoreEdgeColors ()
restore colors of all edges
Definition at line 160 of file GNECrossingFrame.cpp.
References GNEJunction::getGNEEdges(), GNEFrame::getViewNet(), myCrossingFrameParent, and myCurrentJunction.
Referenced by GNECrossingFrame::addCrossing(), enableEdgeSelector(), and GNECrossingFrame::hide().
Field Documentation
helpEdges
FXButton* GNECrossingFrame::edgesSelector::helpEdges private
button for help
Definition at line 115 of file GNECrossingFrame.h.
Referenced by disableEdgeSelector(), edgesSelector(), and enableEdgeSelector().
myClearEdgesSelection
FXButton* GNECrossingFrame::edgesSelector::myClearEdgesSelection private
button for clear selection
Definition at line 118 of file GNECrossingFrame.h.
Referenced by disableEdgeSelector(), edgesSelector(), and enableEdgeSelector().
myCrossingFrameParent
GNECrossingFrame* GNECrossingFrame::edgesSelector::myCrossingFrameParent private
pointer to GNECrossingFrame parent
Definition at line 109 of file GNECrossingFrame.h.
Referenced by disableEdgeSelector(), enableEdgeSelector(), onCmdClearSelection(), onCmdInvertSelection(), onCmdUseSelectedEdges(), and restoreEdgeColors().
myCurrentJunction
GNEJunction* GNECrossingFrame::edgesSelector::myCurrentJunction private
current Junction
Definition at line 124 of file GNECrossingFrame.h.
Referenced by disableEdgeSelector(), enableEdgeSelector(), getCurrentJunction(), onCmdInvertSelection(), onCmdUseSelectedEdges(), and restoreEdgeColors().
myInvertEdgesSelection
FXButton* GNECrossingFrame::edgesSelector::myInvertEdgesSelection private
button for invert selection
Definition at line 121 of file GNECrossingFrame.h.
Referenced by disableEdgeSelector(), edgesSelector(), and enableEdgeSelector().
myUseSelectedEdges
FXButton* GNECrossingFrame::edgesSelector::myUseSelectedEdges private
CheckBox for selected edges.
Definition at line 112 of file GNECrossingFrame.h.
Referenced by disableEdgeSelector(), edgesSelector(), and enableEdgeSelector().
The documentation for this class was generated from the following files:
GNECrossingFrame.h
GNECrossingFrame.cpp