SUMO - Simulation of Urban MObility: NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime Class Reference
NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime Class Reference
Obtains edge efforts from a weights handler and stores them within the edges.
#include <NLBuilder.h>
Public Member Functions
void addEdgeWeight (const std::string &id, double val, double beg, double end) const
Adds a travel time for a given edge and time period.
EdgeFloatTimeLineRetriever_EdgeTravelTime (MSNet &net)
Constructor.
~EdgeFloatTimeLineRetriever_EdgeTravelTime ()
Destructor.
Private Attributes
MSNet & myNet
The network edges shall be obtained from.
Detailed Description
Obtains edge efforts from a weights handler and stores them within the edges.
Obtains edge travel times from a weights handler and stores them within the edges.
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever
Definition at line 180 of file NLBuilder.h.
Constructor & Destructor Documentation
EdgeFloatTimeLineRetriever_EdgeTravelTime()
NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::EdgeFloatTimeLineRetriever_EdgeTravelTime (MSNet & net) inline
Constructor.
Definition at line 183 of file NLBuilder.h.
~EdgeFloatTimeLineRetriever_EdgeTravelTime()
NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::~EdgeFloatTimeLineRetriever_EdgeTravelTime () inline
Destructor.
Definition at line 186 of file NLBuilder.h.
References NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight().
Member Function Documentation
addEdgeWeight()
void NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight (const std::string & id, double val, double beg, double end) const virtual
Adds a travel time for a given edge and time period.
Parameters
[in] id The id of the object to add a weight for
[in] val The travel time
[in] beg The begin of the interval the weight is valid for
[in] end The end of the interval the weight is valid for
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever::addEdgeWeight
Implements SAXWeightsHandler::EdgeFloatTimeLineRetriever.
Definition at line 97 of file NLBuilder.cpp.
References MSEdgeWeightsStorage::addTravelTime(), MSEdge::dictionary(), MSNet::getWeightsStorage(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::myNet, and WRITE_ERROR.
Field Documentation
myNet
MSNet& NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::myNet private
The network edges shall be obtained from.
Definition at line 201 of file NLBuilder.h.
The documentation for this class was generated from the following files:
NLBuilder.h
NLBuilder.cpp