SUMO - Simulation of Urban MObility: NBContHelper::straightness_sorter Class Reference
NBContHelper::straightness_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
straightness_sorter (const NBNode *n, const NBEdge *e)
constructor
Private Attributes
double myReferenceAngle
Position myReferencePos
bool myRefIncoming
Detailed Description
straightness_sorter Class to sort edges according to how straight they are in relation to the reference edge at the given node
Definition at line 103 of file NBContHelper.h.
Constructor & Destructor Documentation
straightness_sorter()
NBContHelper::straightness_sorter::straightness_sorter (const NBNode * n, const NBEdge * e) inline explicit
constructor
Definition at line 106 of file NBContHelper.h.
References NBEdge::getLaneShape(), NBEdge::getShapeEndAngle(), NBEdge::getShapeStartAngle(), and NBContHelper::relative_outgoing_edge_sorter::operator()().
Member Function Documentation
operator()()
int NBContHelper::straightness_sorter::operator() (NBEdge * e1, NBEdge * e2) const
comparing operation
Definition at line 177 of file NBContHelper.cpp.
References NBEdge::ANGLE_LOOKAHEAD, NBEdge::getGeometry(), NBEdge::getLaneShape(), NBEdge::getShapeEndAngle(), NBEdge::getShapeStartAngle(), GeomHelper::legacyDegree(), PositionVector::length2D(), MAX2(), MIN2(), NBHelpers::normRelAngle(), and PositionVector::positionAtOffset2D().
Field Documentation
myReferenceAngle
double NBContHelper::straightness_sorter::myReferenceAngle private
Definition at line 124 of file NBContHelper.h.
myReferencePos
Position NBContHelper::straightness_sorter::myReferencePos private
Definition at line 123 of file NBContHelper.h.
myRefIncoming
bool NBContHelper::straightness_sorter::myRefIncoming private
Definition at line 122 of file NBContHelper.h.
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp