SUMO - Simulation of Urban MObility: NWWriter_DlrNavteq Class Reference
NWWriter_DlrNavteq Class Reference
Exporter writing networks using XML (native input) format.
#include <NWWriter_DlrNavteq.h>
Static Public Member Functions
static int getBrunnelType (NBEdge *edge)
get the navteq brunnel type
static int getFormOfWay (NBEdge *edge)
get the form of way
static int getRoadClass (NBEdge *edge)
get the navteq road class
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into XML-files (nodes, edges, connections, traffic lights)
Static Private Member Functions
static std::string getAllowedTypes (SVCPermissions permissions)
build the ascii-bit-vector for column vehicle_type
static double getGraphLength (NBEdge *edge)
get the length of the edge when measured up to the junction center
static int getNavteqLaneCode (const int numLanes)
get the lane number encoding
static std::string getSinglePostalCode (const std::string &zipCode, const std::string edgeID)
static int getSpeedCategory (int kph)
get the navteq speed class based on the speed in km/h
static int getSpeedCategoryUpperBound (int kph)
get the SPEED_LIMIT as defined by elmar (upper bound of speed category)
static int speedInKph (double metersPerSecond)
get edge speed rounded to kmh
static void writeConnectedLanes (const OptionsCont &oc, NBNodeCont &nc)
Writes the connected_lanes file.
static void writeHeader (OutputDevice &device, const OptionsCont &oc)
write header comments (input paramters, date, etc...)
static void writeLinksUnsplitted (const OptionsCont &oc, NBEdgeCont &ec, std::map< NBEdge *, std::string > &internalNodes)
Writes the links_unsplitted file.
static void writeNodesUnsplitted (const OptionsCont &oc, NBNodeCont &nc, NBEdgeCont &ec, std::map< NBEdge *, std::string > &internalNodes)
Writes the nodes_unsplitted file.
static void writeProhibitedManoeuvres (const OptionsCont &oc, const NBNodeCont &nc, const NBEdgeCont &ec)
Writes the prohibited_manoeuvres file.
static void writeTrafficSignals (const OptionsCont &oc, NBNodeCont &nc)
Writes the traffic_signals file.
Static Private Attributes
static const std::string UNDEFINED
magic value for undefined stuff
Detailed Description
Exporter writing networks using XML (native input) format.
Definition at line 60 of file NWWriter_DlrNavteq.h.
Member Function Documentation
getAllowedTypes()
std::string NWWriter_DlrNavteq::getAllowedTypes (SVCPermissions permissions) static private
build the ascii-bit-vector for column vehicle_type
Definition at line 273 of file NWWriter_DlrNavteq.cpp.
References SVCAll.
Referenced by writeConnectedLanes(), writeLinksUnsplitted(), and writeProhibitedManoeuvres().
getBrunnelType()
int NWWriter_DlrNavteq::getBrunnelType (NBEdge * edge) static
get the navteq brunnel type
Definition at line 401 of file NWWriter_DlrNavteq.cpp.
References NBEdge::getTypeID(), and Parameterised::knowsParameter().
Referenced by writeLinksUnsplitted().
getFormOfWay()
int NWWriter_DlrNavteq::getFormOfWay (NBEdge * edge) static
get the form of way
Definition at line 414 of file NWWriter_DlrNavteq.cpp.
References NBEdge::getJunctionPriority(), NBEdge::getPermissions(), NBEdge::getToNode(), NBEdge::getTypeID(), NBEdge::ROUNDABOUT, and SVC_PEDESTRIAN.
Referenced by writeLinksUnsplitted().
getGraphLength()
double NWWriter_DlrNavteq::getGraphLength (NBEdge * edge) static private
get the length of the edge when measured up to the junction center
Definition at line 429 of file NWWriter_DlrNavteq.cpp.
References NBEdge::getFromNode(), NBEdge::getGeometry(), NBNode::getPosition(), NBEdge::getToNode(), PositionVector::length(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
Referenced by writeLinksUnsplitted().
getNavteqLaneCode()
int NWWriter_DlrNavteq::getNavteqLaneCode (const int numLanes) static private
get the lane number encoding
Definition at line 393 of file NWWriter_DlrNavteq.cpp.
Referenced by writeLinksUnsplitted().
getRoadClass()
int NWWriter_DlrNavteq::getRoadClass (NBEdge * edge) static
get the navteq road class
Definition at line 295 of file NWWriter_DlrNavteq.cpp.
References NBEdge::getNumLanes(), NBEdge::getSpeed(), NBEdge::getTypeID(), speedInKph(), and StringUtils::startsWith().
Referenced by writeLinksUnsplitted(), and NWWriter_Amitran::writeNetwork().
getSinglePostalCode()
std::string NWWriter_DlrNavteq::getSinglePostalCode (const std::string & zipCode, const std::string edgeID) static private
Definition at line 438 of file NWWriter_DlrNavteq.cpp.
References StringTokenizer::getVector(), and WRITE_WARNING.
Referenced by writeLinksUnsplitted().
getSpeedCategory()
int NWWriter_DlrNavteq::getSpeedCategory (int kph) static private
get the navteq speed class based on the speed in km/h
Definition at line 339 of file NWWriter_DlrNavteq.cpp.
Referenced by writeLinksUnsplitted().
getSpeedCategoryUpperBound()
int NWWriter_DlrNavteq::getSpeedCategoryUpperBound (int kph) static private
get the SPEED_LIMIT as defined by elmar (upper bound of speed category)
Definition at line 366 of file NWWriter_DlrNavteq.cpp.
Referenced by writeLinksUnsplitted().
speedInKph()
static int NWWriter_DlrNavteq::speedInKph (double metersPerSecond) inline static private
get edge speed rounded to kmh
Definition at line 137 of file NWWriter_DlrNavteq.h.
Referenced by getRoadClass(), and writeLinksUnsplitted().
writeConnectedLanes()
void NWWriter_DlrNavteq::writeConnectedLanes (const OptionsCont & oc, NBNodeCont & nc) static private
Writes the connected_lanes file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 528 of file NWWriter_DlrNavteq.cpp.
References NBNodeCont::begin(), OutputDevice::close(), NBNodeCont::end(), NBEdge::Connection::fromLane, getAllowedTypes(), NBEdge::getConnections(), OutputDevice::getDevice(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::getPermissions(), OptionsCont::getString(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, and writeHeader().
Referenced by writeNetwork().
writeHeader()
void NWWriter_DlrNavteq::writeHeader (OutputDevice & device, const OptionsCont & oc) static private
write header comments (input paramters, date, etc...)
Definition at line 75 of file NWWriter_DlrNavteq.cpp.
References OptionsCont::getFullName(), OUTPUT_VERSION, and OptionsCont::writeConfiguration().
Referenced by writeConnectedLanes(), writeLinksUnsplitted(), writeNodesUnsplitted(), writeProhibitedManoeuvres(), and writeTrafficSignals().
writeLinksUnsplitted()
void NWWriter_DlrNavteq::writeLinksUnsplitted (const OptionsCont & oc, NBEdgeCont & ec, std::map< NBEdge *, std::string > & internalNodes) static private
Writes the links_unsplitted file.
Parameters
[in] oc The options to use
[in] ec The edge-container from which to read data
Definition at line 208 of file NWWriter_DlrNavteq.cpp.
References NBEdgeCont::begin(), OutputDevice::close(), NBEdgeCont::end(), getAllowedTypes(), OptionsCont::getBool(), getBrunnelType(), OutputDevice::getDevice(), getFormOfWay(), NBEdge::getFromNode(), NBEdge::getGeometry(), getGraphLength(), Named::getID(), getNavteqLaneCode(), NBEdge::getNumLanes(), Parameterised::getParameter(), NBEdge::getPermissions(), getRoadClass(), getSinglePostalCode(), NBEdge::getSpeed(), getSpeedCategory(), getSpeedCategoryUpperBound(), OptionsCont::getString(), NBEdge::getToNode(), speedInKph(), toString(), UNDEFINED, and writeHeader().
Referenced by writeNetwork().
writeNetwork()
void NWWriter_DlrNavteq::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into XML-files (nodes, edges, connections, traffic lights)
Parameters
[in] oc The options to use
[in] nb The network builder from which to read data
Definition at line 61 of file NWWriter_DlrNavteq.cpp.
References NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), OptionsCont::isSet(), writeConnectedLanes(), writeLinksUnsplitted(), writeNodesUnsplitted(), writeProhibitedManoeuvres(), and writeTrafficSignals().
Referenced by NWFrame::writeNetwork().
writeNodesUnsplitted()
void NWWriter_DlrNavteq::writeNodesUnsplitted (const OptionsCont & oc, NBNodeCont & nc, NBEdgeCont & ec, std::map< NBEdge *, std::string > & internalNodes) static private
Writes the nodes_unsplitted file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
[in] ec The edge-container from which to read data
[out] internalNodes The internal node ids, generated for edges with complex geometry
Definition at line 94 of file NWWriter_DlrNavteq.cpp.
References NBNodeCont::begin(), NBEdgeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), NBNodeCont::end(), NBEdgeCont::end(), NBNodeCont::getAllNames(), NBEdgeCont::getAllNames(), OptionsCont::getBool(), GeoConvHelper::getConvBoundary(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), NBEdge::getGeometry(), Named::getID(), OptionsCont::getInt(), NBEdge::getLaneSpreadFunction(), IDSupplier::getNext(), NBEdgeCont::getOppositeByID(), NBNode::getPosition(), OptionsCont::getString(), NBEdge::getTotalWidth(), OptionsCont::isSet(), LANESPREAD_CENTER, LANESPREAD_RIGHT, NBHelpers::loadPrefixedIDsFomFile(), PositionVector::move2side(), Position::mul(), NBNodeCont::retrieve(), OutputDevice::setPrecision(), NBNodeCont::size(), UNDEFINED, GeoConvHelper::usingGeoProjection(), WRITE_WARNING, writeHeader(), Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by writeNetwork().
writeProhibitedManoeuvres()
void NWWriter_DlrNavteq::writeProhibitedManoeuvres (const OptionsCont & oc, const NBNodeCont & nc, const NBEdgeCont & ec) static private
Writes the prohibited_manoeuvres file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 485 of file NWWriter_DlrNavteq.cpp.
References NBNodeCont::begin(), OutputDevice::close(), NBNodeCont::end(), NBEdgeCont::getAllNames(), getAllowedTypes(), OutputDevice::getDevice(), Named::getID(), NBNode::getIncomingEdges(), IDSupplier::getNext(), NBNode::getOutgoingEdges(), NBEdge::getPermissions(), OptionsCont::getString(), NBEdge::isConnectedTo(), OptionsCont::isSet(), NBHelpers::loadPrefixedIDsFomFile(), SVC_PEDESTRIAN, SVCAll, UNDEFINED, and writeHeader().
Referenced by writeNetwork().
writeTrafficSignals()
void NWWriter_DlrNavteq::writeTrafficSignals (const OptionsCont & oc, NBNodeCont & nc) static private
Writes the traffic_signals file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 452 of file NWWriter_DlrNavteq.cpp.
References NBNodeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), NBNodeCont::end(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), Named::getID(), NBNode::getIncomingEdges(), OptionsCont::getInt(), NBNode::getPosition(), OptionsCont::getString(), NBNode::isTLControlled(), Position::mul(), OutputDevice::setPrecision(), GeoConvHelper::usingGeoProjection(), writeHeader(), Position::x(), and Position::y().
Referenced by writeNetwork().
Field Documentation
UNDEFINED
const std::string NWWriter_DlrNavteq::UNDEFINED static private
magic value for undefined stuff
Definition at line 134 of file NWWriter_DlrNavteq.h.
Referenced by writeLinksUnsplitted(), writeNodesUnsplitted(), and writeProhibitedManoeuvres().
The documentation for this class was generated from the following files:
NWWriter_DlrNavteq.h
NWWriter_DlrNavteq.cpp