SUMO - Simulation of Urban MObility: NBTypeCont Class Reference
NBTypeCont Class Reference
A storage for available types of edges.
#include <NBTypeCont.h>
Data Structures
struct TypeDefinition
Public Member Functions
bool addRestriction (const std::string &id, const SUMOVehicleClass svc, const double speed)
Adds a restriction to a type.
bool copyRestrictionsAndAttrs (const std::string &fromId, const std::string &toId)
Copy restrictions to a type.
void insert (const std::string &id, int numLanes, double maxSpeed, int prio, SVCPermissions permissions, double width, bool oneWayIsDefault, double sidewalkWidth, double bikeLaneWidth)
Adds a type into the list.
bool knows (const std::string &type) const
Returns whether the named type is in the container.
bool markAsSet (const std::string &id, const SumoXMLAttr attr)
Marks an attribute of a type as set.
bool markAsToDiscard (const std::string &id)
Marks a type as to be discarded.
NBTypeCont ()
Constructor.
void setDefaults (int defaultNumLanes, double defaultLaneWidth, double defaultSpeed, int defaultPriority, SVCPermissions defaultPermissions)
Sets the default values.
int size () const
Returns the number of known types.
void writeTypes (OutputDevice &into) const
writes all types a s XML
~NBTypeCont ()
Destructor.
Type-dependant Retrieval methods
int getNumLanes (const std::string &type) const
Returns the number of lanes for the given type.
double getSpeed (const std::string &type) const
Returns the maximal velocity for the given type [m/s].
int getPriority (const std::string &type) const
Returns the priority for the given type.
bool getIsOneWay (const std::string &type) const
Returns whether edges are one-way per default for the given type.
bool getShallBeDiscarded (const std::string &type) const
Returns the information whether edges of this type shall be discarded.
bool wasSet (const std::string &type, const SumoXMLAttr attr) const
Returns whether an attribute of a type was set.
SVCPermissions getPermissions (const std::string &type) const
Returns allowed vehicle classes for the given type.
double getWidth (const std::string &type) const
Returns the lane width for the given type [m].
double getSidewalkWidth (const std::string &type) const
Returns the lane width for a sidewalk to be added [m].
double getBikeLaneWidth (const std::string &type) const
Returns the lane width for a bike lane to be added [m].
Private Types
typedef std::map< std::string, TypeDefinition > TypesCont
A container of types, accessed by the string id.
Private Member Functions
const TypeDefinition & getType (const std::string &name) const
Retrieve the name or the default type.
NBTypeCont (const NBTypeCont &s)
invalid copy constructor
NBTypeCont & operator= (const NBTypeCont &s)
invalid assignment operator
Private Attributes
TypeDefinition myDefaultType
The default type.
TypesCont myTypes
The container of types.
Detailed Description
A storage for available types of edges.
NBTypeCont stores properties of edge-types of edges. Additionally, a default type is stored which is used if no type information is given.
This structure also contains a structure for determining node types using edge speeds.
Definition at line 61 of file NBTypeCont.h.
Member Typedef Documentation
TypesCont
typedef std::map<std::string, TypeDefinition> NBTypeCont::TypesCont private
A container of types, accessed by the string id.
Definition at line 301 of file NBTypeCont.h.
Constructor & Destructor Documentation
NBTypeCont() [1/2]
NBTypeCont::NBTypeCont () inline
Constructor.
Definition at line 64 of file NBTypeCont.h.
~NBTypeCont()
NBTypeCont::~NBTypeCont () inline
Destructor.
Definition at line 68 of file NBTypeCont.h.
References insert(), and setDefaults().
NBTypeCont() [2/2]
NBTypeCont::NBTypeCont (const NBTypeCont & s) private
invalid copy constructor
Member Function Documentation
addRestriction()
bool NBTypeCont::addRestriction (const std::string & id, const SUMOVehicleClass svc, const double speed)
Adds a restriction to a type.
Parameters
[in] id The id of the type
[in] svc The vehicle class the restriction refers to
[in] speed The restricted speed
Definition at line 102 of file NBTypeCont.cpp.
References myTypes.
Referenced by NIXMLTypesHandler::myStartElement(), and size().
copyRestrictionsAndAttrs()
bool NBTypeCont::copyRestrictionsAndAttrs (const std::string & fromId, const std::string & toId)
Copy restrictions to a type.
Parameters
[in] fromId The id of the source type
[in] toId The id of the destination type
Definition at line 113 of file NBTypeCont.cpp.
References myTypes.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and size().
getBikeLaneWidth()
double NBTypeCont::getBikeLaneWidth (const std::string & type) const
Returns the lane width for a bike lane to be added [m].
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the width for
Returns
The width of lanes of edges of this type
Definition at line 228 of file NBTypeCont.cpp.
References NBTypeCont::TypeDefinition::bikeLaneWidth, and getType().
Referenced by NIXMLEdgesHandler::addEdge(), NIImporter_OpenStreetMap::insertEdge(), NIXMLTypesHandler::myStartElement(), and size().
getIsOneWay()
bool NBTypeCont::getIsOneWay (const std::string & type) const
Returns whether edges are one-way per default for the given type.
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the one-way information for
Returns
Whether edges of this type are one-way per default
Todo:
There is no default for one-way!?
Definition at line 192 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::oneWay.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIXMLTypesHandler::myStartElement(), and size().
getNumLanes()
int NBTypeCont::getNumLanes (const std::string & type) const
Returns the number of lanes for the given type.
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the lane number for
Returns
The number of lanes an edge of this type has
Definition at line 174 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::numLanes.
Referenced by NIXMLEdgesHandler::addEdge(), NGEdge::buildNBEdge(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_ArcView::load(), NIXMLTypesHandler::myStartElement(), NIImporter_VISUM::parse_Edges(), size(), and NGNet::toNB().
getPermissions()
SVCPermissions NBTypeCont::getPermissions (const std::string & type) const
Returns allowed vehicle classes for the given type.
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the list of allowed vehicles classes for
Returns
List of vehicles class which may use edges of the given type
Definition at line 210 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::permissions.
Referenced by NIXMLEdgesHandler::addEdge(), NIImporter_OpenDrive::findWidthSplit(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenDrive::loadNetwork(), NIXMLTypesHandler::myStartElement(), NIImporter_DlrNavteq::EdgesHandler::report(), and size().
getPriority()
int NBTypeCont::getPriority (const std::string & type) const
Returns the priority for the given type.
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the priority for
Returns
The priority of edges of this type
Definition at line 186 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::priority.
Referenced by NIXMLEdgesHandler::addEdge(), NGEdge::buildNBEdge(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_ArcView::load(), NIXMLTypesHandler::myStartElement(), NIImporter_VISUM::parse_Edges(), size(), and NGNet::toNB().
getShallBeDiscarded()
bool NBTypeCont::getShallBeDiscarded (const std::string & type) const
Returns the information whether edges of this type shall be discarded.
Returns false if the type is not known.
Parameters
[in] type The id of the type
Returns
Whether edges of this type shall be discarded.
Definition at line 198 of file NBTypeCont.cpp.
References NBTypeCont::TypeDefinition::discard, and getType().
Referenced by NIImporter_OpenDrive::OpenDriveLaneSection::buildLaneMapping(), NIImporter_OpenDrive::findWidthSplit(), NBEdgeCont::ignoreFilterMatch(), NIImporter_OpenStreetMap::insertEdge(), and size().
getSidewalkWidth()
double NBTypeCont::getSidewalkWidth (const std::string & type) const
Returns the lane width for a sidewalk to be added [m].
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the width for
Returns
The width of lanes of edges of this type
Definition at line 222 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::sidewalkWidth.
Referenced by NIXMLEdgesHandler::addEdge(), NIImporter_OpenStreetMap::insertEdge(), NIXMLTypesHandler::myStartElement(), and size().
getSpeed()
double NBTypeCont::getSpeed (const std::string & type) const
Returns the maximal velocity for the given type [m/s].
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the speed for
Returns
The allowed speed on edges of this type
Definition at line 180 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::speed.
Referenced by NIXMLEdgesHandler::addEdge(), NGEdge::buildNBEdge(), NIImporter_OpenDrive::OpenDriveLaneSection::buildSpeedChanges(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_ArcView::load(), NIImporter_OpenDrive::loadNetwork(), NIXMLTypesHandler::myStartElement(), NIImporter_VISUM::parse_Edges(), size(), and NGNet::toNB().
getType()
const NBTypeCont::TypeDefinition & NBTypeCont::getType (const std::string & name) const private
Retrieve the name or the default type.
If no name is given, the default type is returned
Parameters
[in] name The name of the type to retrieve
Returns
The named type
Definition at line 234 of file NBTypeCont.cpp.
References myDefaultType, and myTypes.
Referenced by getBikeLaneWidth(), getIsOneWay(), getNumLanes(), getPermissions(), getPriority(), getShallBeDiscarded(), getSidewalkWidth(), getSpeed(), getWidth(), and wasSet().
getWidth()
double NBTypeCont::getWidth (const std::string & type) const
Returns the lane width for the given type [m].
If the named type is not known, the default is returned
Parameters
[in] type The name of the type to return the width for
Returns
The width of lanes of edges of this type
Definition at line 216 of file NBTypeCont.cpp.
References getType(), and NBTypeCont::TypeDefinition::width.
Referenced by NIXMLEdgesHandler::addEdge(), NGEdge::buildNBEdge(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_ArcView::load(), NIImporter_OpenDrive::loadNetwork(), NIXMLTypesHandler::myStartElement(), size(), and NGNet::toNB().
insert()
void NBTypeCont::insert (const std::string & id, int numLanes, double maxSpeed, int prio, SVCPermissions permissions, double width, bool oneWayIsDefault, double sidewalkWidth, double bikeLaneWidth)
Adds a type into the list.
Parameters
[in] id The id of the type
[in] numLanes The number of lanes an edge of this type has
[in] maxSpeed The speed allowed on an edge of this type
[in] prio The priority of an edge of this type
[in] permissions The encoding of vehicle classes allowed on an edge of this type
[in] width The width of lanes of edgesof this type
[in] oneWayIsDefault Whether edges of this type are one-way per default
Returns
Whether the type could be added (no type with the same id existed)
Definition at line 60 of file NBTypeCont.cpp.
References NBTypeCont::TypeDefinition::attrs, myTypes, and NBTypeCont::TypeDefinition::restrictions.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIXMLTypesHandler::myStartElement(), NIImporter_VISUM::parse_Types(), and ~NBTypeCont().
knows()
bool NBTypeCont::knows (const std::string & type) const
Returns whether the named type is in the container.
Returns
Whether the named type is known
Definition at line 74 of file NBTypeCont.cpp.
References myTypes.
Referenced by NIXMLEdgesHandler::addEdge(), NIImporter_OpenDrive::OpenDriveLaneSection::buildLaneMapping(), NIImporter_OpenDrive::findWidthSplit(), NBEdgeCont::ignoreFilterMatch(), NIImporter_OpenStreetMap::insertEdge(), NIXMLTypesHandler::myStartElement(), NIImporter_DlrNavteq::EdgesHandler::report(), and size().
markAsSet()
bool NBTypeCont::markAsSet (const std::string & id, const SumoXMLAttr attr)
Marks an attribute of a type as set.
Parameters
[in] id The id of the type
[in] attr The id of the attribute
Definition at line 91 of file NBTypeCont.cpp.
References myTypes.
Referenced by NIXMLTypesHandler::myStartElement(), NIImporter_VISUM::parse_Types(), and size().
markAsToDiscard()
bool NBTypeCont::markAsToDiscard (const std::string & id)
Marks a type as to be discarded.
Parameters
[in] id The id of the type
Definition at line 80 of file NBTypeCont.cpp.
References myTypes.
Referenced by NIXMLTypesHandler::myStartElement(), and size().
operator=()
NBTypeCont& NBTypeCont::operator= (const NBTypeCont & s) private
invalid assignment operator
setDefaults()
void NBTypeCont::setDefaults (int defaultNumLanes, double defaultLaneWidth, double defaultSpeed, int defaultPriority, SVCPermissions defaultPermissions)
Sets the default values.
Parameters
[in] defaultNumLanes The default number of lanes an edge has
[in] defaultLaneWidth The default width of lanes
[in] defaultSpeed The default speed allowed on an edge
[in] defaultPriority The default priority of an edge
[in] defaultPermissions The default permissions of an edge
Definition at line 46 of file NBTypeCont.cpp.
References myDefaultType, NBTypeCont::TypeDefinition::numLanes, NBTypeCont::TypeDefinition::permissions, NBTypeCont::TypeDefinition::priority, NBTypeCont::TypeDefinition::speed, and NBTypeCont::TypeDefinition::width.
Referenced by NBNetBuilder::applyOptions(), and ~NBTypeCont().
size()
int NBTypeCont::size () const inline
Returns the number of known types.
Returns
The number of known edge types (excluding the default)
Definition at line 103 of file NBTypeCont.h.
References addRestriction(), copyRestrictionsAndAttrs(), getBikeLaneWidth(), getIsOneWay(), getNumLanes(), getPermissions(), getPriority(), getShallBeDiscarded(), getSidewalkWidth(), getSpeed(), getWidth(), knows(), markAsSet(), markAsToDiscard(), myTypes, wasSet(), and writeTypes().
Referenced by NILoader::load(), and NWWriter_XML::writeNetwork().
wasSet()
bool NBTypeCont::wasSet (const std::string & type, const SumoXMLAttr attr) const
Returns whether an attribute of a type was set.
Parameters
[in] type The id of the type
[in] attr The id of the attribute
Returns
Whether the attribute was set
Definition at line 204 of file NBTypeCont.cpp.
References NBTypeCont::TypeDefinition::attrs, and getType().
Referenced by size().
writeTypes()
void NBTypeCont::writeTypes (OutputDevice & into) const
writes all types a s XML
Definition at line 126 of file NBTypeCont.cpp.
References NBTypeCont::TypeDefinition::attrs, NBTypeCont::TypeDefinition::bikeLaneWidth, OutputDevice::closeTag(), NBTypeCont::TypeDefinition::discard, getVehicleClassNames(), OutputDevice::lf(), myTypes, NBTypeCont::TypeDefinition::numLanes, NBTypeCont::TypeDefinition::oneWay, OutputDevice::openTag(), NBTypeCont::TypeDefinition::permissions, NBTypeCont::TypeDefinition::priority, NBTypeCont::TypeDefinition::restrictions, NBTypeCont::TypeDefinition::sidewalkWidth, NBTypeCont::TypeDefinition::speed, SUMO_ATTR_ALLOW, SUMO_ATTR_BIKELANEWIDTH, SUMO_ATTR_DISALLOW, SUMO_ATTR_DISCARD, SUMO_ATTR_ID, SUMO_ATTR_NUMLANES, SUMO_ATTR_ONEWAY, SUMO_ATTR_PRIORITY, SUMO_ATTR_SIDEWALKWIDTH, SUMO_ATTR_SPEED, SUMO_ATTR_VCLASS, SUMO_ATTR_WIDTH, SUMO_TAG_RESTRICTION, SUMO_TAG_TYPE, NBTypeCont::TypeDefinition::width, OutputDevice::writeAttr(), and writePermissions().
Referenced by size(), NWWriter_SUMO::writeNetwork(), and NWWriter_XML::writeTypes().
Field Documentation
myDefaultType
TypeDefinition NBTypeCont::myDefaultType private
The default type.
Definition at line 298 of file NBTypeCont.h.
Referenced by getType(), and setDefaults().
myTypes
TypesCont NBTypeCont::myTypes private
The container of types.
Definition at line 304 of file NBTypeCont.h.
Referenced by addRestriction(), copyRestrictionsAndAttrs(), getType(), insert(), knows(), markAsSet(), markAsToDiscard(), size(), and writeTypes().
The documentation for this class was generated from the following files:
NBTypeCont.h
NBTypeCont.cpp