SUMO - Simulation of Urban MObility: NIFrame Class Reference
NIFrame Class Reference
Sets and checks options for netimport.
#include <NIFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid.
static void fillOptions ()
Inserts options used by the network importer and network building modules.
Detailed Description
Sets and checks options for netimport.
Definition at line 41 of file NIFrame.h.
Member Function Documentation
checkOptions()
bool NIFrame::checkOptions () static
Checks set options from the OptionsCont-singleton for being valid.
Returns
Whether all needed options are set
Todo:
Unused currently; repair/fill
Definition at line 299 of file NIFrame.cpp.
References OptionsCont::checkDependingSuboptions(), NIImporter_DlrNavteq::GEO_SCALE, OptionsCont::getBool(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isDefault(), OptionsCont::isSet(), OptionsCont::isWriteable(), OptionsCont::set(), OptionsCont::setDefault(), WRITE_ERROR, and WRITE_WARNING.
Referenced by checkOptions(), GNEApplicationWindow::onCmdOpenForeign(), GNEApplicationWindow::onCmdOptions(), and GNELoadThread::run().
fillOptions()
void NIFrame::fillOptions () static
Inserts options used by the network importer and network building modules.
Calls "NBNetBuilder::insertNetBuildOptions" for inserting network building options.
Definition at line 55 of file NIFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::addXMLDefault(), OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by fillOptions(), and GNELoadThread::fillOptions().
The documentation for this class was generated from the following files:
NIFrame.h
NIFrame.cpp