SUMO - Simulation of Urban MObility: MSVehicle::WaitingTimeCollector Class Reference
MSVehicle::WaitingTimeCollector Class Reference
Stores the waiting intervals over the previous seconds (memory is to be specified in ms.).
#include <MSVehicle.h>
Public Member Functions
SUMOTime cumulatedWaitingTime (SUMOTime memory=-1) const
SUMOTime getMemorySize () const
const waitingIntervalList & getWaitingIntervals () const
bool operator!= (const WaitingTimeCollector &wt) const
Operator !=.
WaitingTimeCollector & operator= (const WaitingTimeCollector &wt)
Assignment operator.
WaitingTimeCollector & operator= (SUMOTime t)
Assignment operator (in place!)
void passTime (SUMOTime dt, bool waiting)
WaitingTimeCollector (SUMOTime memory=MSGlobals::gWaitingTimeMemory)
Constructor.
WaitingTimeCollector (const WaitingTimeCollector &wt)
Copy constructor.
Private Types
typedef std::list< std::pair< SUMOTime, SUMOTime > > waitingIntervalList
Private Member Functions
void appendWaitingTime (SUMOTime dt)
append an amount of dt millisecs to the stored waiting times
Private Attributes
SUMOTime myMemorySize
the maximal memory to store
waitingIntervalList myWaitingIntervals
Friends
class MSVehicle
Detailed Description
Stores the waiting intervals over the previous seconds (memory is to be specified in ms.).
Definition at line 168 of file MSVehicle.h.
Member Typedef Documentation
waitingIntervalList
typedef std::list<std::pair<SUMOTime, SUMOTime> > MSVehicle::WaitingTimeCollector::waitingIntervalList private
Definition at line 171 of file MSVehicle.h.
Constructor & Destructor Documentation
WaitingTimeCollector() [1/2]
MSVehicle::WaitingTimeCollector::WaitingTimeCollector (SUMOTime memory = MSGlobals::gWaitingTimeMemory)
Constructor.
Definition at line 164 of file MSVehicle.cpp.
WaitingTimeCollector() [2/2]
MSVehicle::WaitingTimeCollector::WaitingTimeCollector (const WaitingTimeCollector & wt)
Copy constructor.
Definition at line 166 of file MSVehicle.cpp.
Member Function Documentation
appendWaitingTime()
void MSVehicle::WaitingTimeCollector::appendWaitingTime (SUMOTime dt) private
append an amount of dt millisecs to the stored waiting times
cumulatedWaitingTime()
SUMOTime MSVehicle::WaitingTimeCollector::cumulatedWaitingTime (SUMOTime memory = -1) const
Definition at line 183 of file MSVehicle.cpp.
References myMemorySize, and myWaitingIntervals.
Referenced by MSVehicle::getAccumulatedWaitingTime().
getMemorySize()
SUMOTime MSVehicle::WaitingTimeCollector::getMemorySize () const inline
Definition at line 196 of file MSVehicle.h.
Referenced by operator=().
getWaitingIntervals()
const waitingIntervalList& MSVehicle::WaitingTimeCollector::getWaitingIntervals () const inline
Definition at line 201 of file MSVehicle.h.
Referenced by operator=().
operator!=()
bool MSVehicle::WaitingTimeCollector::operator!= (const WaitingTimeCollector & wt) const
Operator !=.
operator=() [1/2]
MSVehicle::WaitingTimeCollector & MSVehicle::WaitingTimeCollector::operator= (const WaitingTimeCollector & wt)
Assignment operator.
Definition at line 169 of file MSVehicle.cpp.
References getMemorySize(), getWaitingIntervals(), myMemorySize, and myWaitingIntervals.
operator=() [2/2]
MSVehicle::WaitingTimeCollector & MSVehicle::WaitingTimeCollector::operator= (SUMOTime t)
Assignment operator (in place!)
Definition at line 176 of file MSVehicle.cpp.
References myWaitingIntervals, and passTime().
passTime()
void MSVehicle::WaitingTimeCollector::passTime (SUMOTime dt, bool waiting)
Definition at line 204 of file MSVehicle.cpp.
References myMemorySize, and myWaitingIntervals.
Referenced by operator=(), and MSVehicle::updateWaitingTime().
Friends And Related Function Documentation
MSVehicle
friend class MSVehicle friend
Definition at line 169 of file MSVehicle.h.
Field Documentation
myMemorySize
SUMOTime MSVehicle::WaitingTimeCollector::myMemorySize private
the maximal memory to store
Definition at line 207 of file MSVehicle.h.
Referenced by cumulatedWaitingTime(), operator=(), and passTime().
myWaitingIntervals
waitingIntervalList MSVehicle::WaitingTimeCollector::myWaitingIntervals private
the stored waiting intervals within the last memory milliseconds If the current (ongoing) waiting interval has begun at time t - dt (where t is the current time) then waitingIntervalList[0]->first = 0., waitingIntervalList[0]->second = dt
Definition at line 212 of file MSVehicle.h.
Referenced by cumulatedWaitingTime(), operator=(), and passTime().
The documentation for this class was generated from the following files:
MSVehicle.h
MSVehicle.cpp