SUMO - Simulation of Urban MObility: MSVehicleTransfer Class Reference
MSVehicleTransfer Class Reference
#include <MSVehicleTransfer.h>
Data Structures
struct VehicleInformation
Holds the information needed to move the vehicle over the network.
Public Member Functions
void add (const SUMOTime t, MSVehicle *veh)
Adds a vehicle to this transfer object.
void checkInsertions (SUMOTime time)
Checks "movement" of stored vehicles.
bool hasPending () const
Checks whether stored vehicles are present.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset, MSVehicleControl &vc)
Loads one transfer vehicle state from the given descriptionn.
void remove (MSVehicle *veh)
Remove a vehicle from this transfer object.
void saveState (OutputDevice &out) const
Saves the current state into the given stream.
virtual ~MSVehicleTransfer ()
Destructor.
Static Public Member Functions
static MSVehicleTransfer * getInstance ()
Returns the instance of this object.
Static Public Attributes
static const double TeleportMinSpeed = 1
The minimum speed while teleporting.
Protected Types
typedef std::vector< VehicleInformation > VehicleInfVector
Definition of a container for vehicle information.
Protected Attributes
VehicleInfVector myVehicles
The information about stored vehicles to move virtually.
Static Protected Attributes
static const std::set< const MSVehicle * > myEmptyVehicleSet
an empty set for convenience
static MSVehicleTransfer * myInstance = 0
The static singleton-instance.
Private Member Functions
MSVehicleTransfer ()
Constructor.
Detailed Description
This object (each simulation owns exactly one) is responsible for the transfer of vehicles that got stuck within the network due to grid locks. It also manages vehicles that are removed from the network because of stops with the parking attribute.
The method add is called by a lane if a vehicle stood to long at this lane's end. After being added to this transfer object and removed from the lane, it is moved over the consecutive edges. On each edge, it is tried to insert the vehicle again. The lanes are of course chosen by examining the vehicle's real route.
This object is used as a singleton
Definition at line 69 of file MSVehicleTransfer.h.
Member Typedef Documentation
VehicleInfVector
typedef std::vector<VehicleInformation> MSVehicleTransfer::VehicleInfVector protected
Definition of a container for vehicle information.
Definition at line 159 of file MSVehicleTransfer.h.
Constructor & Destructor Documentation
~MSVehicleTransfer()
MSVehicleTransfer::~MSVehicleTransfer () virtual
Destructor.
Definition at line 181 of file MSVehicleTransfer.cpp.
References myInstance.
MSVehicleTransfer()
MSVehicleTransfer::MSVehicleTransfer () private
Constructor.
Definition at line 178 of file MSVehicleTransfer.cpp.
Referenced by getInstance().
Member Function Documentation
add()
void MSVehicleTransfer::add (const SUMOTime t, MSVehicle * veh)
Adds a vehicle to this transfer object.
The vehicle is removed from the network as it would end the trip. If the vehicle's next edge is his last one, the vehicle is also removed from the vehicle control.
Parameters
[in] veh The vehicle to add
Definition at line 56 of file MSVehicleTransfer.cpp.
References MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::enterLaneAtMove(), MSEdge::getCurrentTravelTime(), MSBaseVehicle::getEdge(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSEdge::getLanes(), MSNet::getVehicleControl(), MSNet::informVehicleStateListener(), MSVehicle::isParking(), myVehicles, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, MSMoveReminder::NOTIFICATION_TELEPORT_ARRIVED, MSVehicle::onRemovalFromNet(), MSVehicleControl::scheduleVehicleRemoval(), MSBaseVehicle::succEdge(), TeleportMinSpeed, TIME2STEPS, time2string(), MSNet::VEHICLE_STATE_STARTING_PARKING, MSNet::VEHICLE_STATE_STARTING_TELEPORT, and WRITE_WARNING.
Referenced by MSLane::detectCollisions(), and MSLane::executeMovements().
checkInsertions()
void MSVehicleTransfer::checkInsertions (SUMOTime time)
Checks "movement" of stored vehicles.
Checks whether one of the stored vehicles may be inserted back into the network. If not, the vehicle may move virtually to the next lane of it's route
Parameters
[in] time The current simulation time
Definition at line 94 of file MSVehicleTransfer.cpp.
References MSEdge::allowedLanes(), MSVehicle::enterLaneAtMove(), MSLane::freeInsertion(), MSEdge::getCurrentTravelTime(), MSBaseVehicle::getEdge(), MSEdge::getFreeLane(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicle::getLateralPositionOnLane(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getPositionOnLane(), MSLane::getSpeedLimit(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSNet::informVehicleStateListener(), MSLane::isInsertionSuccess(), MSVehicle::keepStopping(), MSVehicle::leaveLane(), MIN2(), MSVehicleTransfer::VehicleInformation::myParking, MSVehicleTransfer::VehicleInformation::myProceedTime, MSVehicleTransfer::VehicleInformation::myTransferTime, MSVehicleTransfer::VehicleInformation::myVeh, myVehicles, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, MSMoveReminder::NOTIFICATION_TELEPORT_ARRIVED, MSVehicle::processNextStop(), MSLane::removeParking(), MSVehicleControl::scheduleVehicleRemoval(), MSBaseVehicle::succEdge(), TeleportMinSpeed, TIME2STEPS, time2string(), MSNet::VEHICLE_STATE_ENDING_PARKING, MSNet::VEHICLE_STATE_ENDING_TELEPORT, and WRITE_WARNING.
Referenced by MSNet::simulationStep().
getInstance()
MSVehicleTransfer * MSVehicleTransfer::getInstance (void) static
Returns the instance of this object.
Returns
The singleton instance
Definition at line 170 of file MSVehicleTransfer.cpp.
References MSVehicleTransfer(), and myInstance.
Referenced by MSNet::clearAll(), MSLane::detectCollisions(), MSLane::executeMovements(), MSStateHandler::myStartElement(), MSVehicle::onRemovalFromNet(), MSStateHandler::saveState(), and MSNet::simulationStep().
hasPending()
bool MSVehicleTransfer::hasPending () const
Checks whether stored vehicles are present.
Returns
whether any vehicles wait for transfer
Definition at line 164 of file MSVehicleTransfer.cpp.
References myVehicles.
loadState()
void MSVehicleTransfer::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset, MSVehicleControl & vc)
Loads one transfer vehicle state from the given descriptionn.
Definition at line 201 of file MSVehicleTransfer.cpp.
References MSLane::addParking(), MSInsertionControl::alreadyDeparted(), MSLane::dictionary(), MSNet::getInsertionControl(), MSNet::getInstance(), SUMOSAXAttributes::getLong(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), SUMOSAXAttributes::getString(), MSVehicleControl::getVehicle(), SUMOSAXAttributes::hasAttribute(), myVehicles, MSVehicle::processNextStop(), MSVehicle::setTentativeLaneAndPosition(), SUMO_ATTR_DEPART, SUMO_ATTR_ID, and SUMO_ATTR_PARKING.
Referenced by MSStateHandler::myStartElement().
remove()
void MSVehicleTransfer::remove (MSVehicle * veh)
Remove a vehicle from this transfer object.
The vehicle is removed from the transfer if present. This should be necessary only in the context of TraCI removals.
Parameters
[in] veh The vehicle to remove
Definition at line 80 of file MSVehicleTransfer.cpp.
References MSVehicle::getLane(), myVehicles, and MSLane::removeParking().
Referenced by MSVehicle::onRemovalFromNet().
saveState()
void MSVehicleTransfer::saveState (OutputDevice & out) const
Saves the current state into the given stream.
Definition at line 187 of file MSVehicleTransfer.cpp.
References OutputDevice::closeTag(), myVehicles, OutputDevice::openTag(), SUMO_ATTR_DEPART, SUMO_ATTR_ID, SUMO_ATTR_PARKING, SUMO_TAG_VEHICLETRANSFER, and OutputDevice::writeAttr().
Referenced by MSStateHandler::saveState().
Field Documentation
myEmptyVehicleSet
const std::set< const MSVehicle * > MSVehicleTransfer::myEmptyVehicleSet static protected
an empty set for convenience
Definition at line 168 of file MSVehicleTransfer.h.
myInstance
MSVehicleTransfer * MSVehicleTransfer::myInstance = 0 static protected
The static singleton-instance.
Definition at line 165 of file MSVehicleTransfer.h.
Referenced by getInstance(), and ~MSVehicleTransfer().
myVehicles
VehicleInfVector MSVehicleTransfer::myVehicles protected
The information about stored vehicles to move virtually.
Definition at line 162 of file MSVehicleTransfer.h.
Referenced by add(), checkInsertions(), hasPending(), loadState(), remove(), and saveState().
TeleportMinSpeed
const double MSVehicleTransfer::TeleportMinSpeed = 1 static
The minimum speed while teleporting.
Definition at line 125 of file MSVehicleTransfer.h.
Referenced by add(), and checkInsertions().
The documentation for this class was generated from the following files:
MSVehicleTransfer.h
MSVehicleTransfer.cpp