SUMO - Simulation of Urban MObility: NBRampsComputer Class Reference
NBRampsComputer Class Reference
#include <NBAlgorithms_Ramps.h>
Static Public Member Functions
static void computeRamps (NBNetBuilder &nb, OptionsCont &oc)
Computes highway on-/off-ramps (if wished)
Static Public Attributes
static const std::string ADDED_ON_RAMP_EDGE
suffix for newly generated on-ramp edges
Static Private Member Functions
static void buildOffRamp (NBNode *cur, NBNodeCont &nc, NBEdgeCont &ec, NBDistrictCont &dc, double rampLength, bool dontSplit)
Builds an off-ramp ending at the given node.
static void buildOnRamp (NBNode *cur, NBNodeCont &nc, NBEdgeCont &ec, NBDistrictCont &dc, double rampLength, bool dontSplit)
Builds an on-ramp starting at the given node.
static bool determinedByLaneNumber (NBEdge **potHighway, NBEdge **potRamp)
static bool determinedBySpeed (NBEdge **potHighway, NBEdge **potRamp)
static bool fulfillsRampConstraints (NBEdge *potHighway, NBEdge *potRamp, NBEdge *other, double minHighwaySpeed, double maxRampSpeed, const std::set< std::string > &noramps)
Checks whether an on-/off-ramp can be bult here.
static void getOffRampEdges (NBNode *n, NBEdge **potHighway, NBEdge **potRamp, NBEdge **other)
static void getOnRampEdges (NBNode *n, NBEdge **potHighway, NBEdge **potRamp, NBEdge **other)
static bool hasWrongMode (NBEdge *edge)
whether the edge has a mode that does not indicate a ramp edge
static bool mayNeedOffRamp (NBNode *cur, double minHighwaySpeed, double maxRampSpeed, const std::set< std::string > &noramps)
Determines whether the given node may be an off-ramp end.
static bool mayNeedOnRamp (NBNode *cur, double minHighwaySpeed, double maxRampSpeed, const std::set< std::string > &noramps)
Determines whether the given node may be an on-ramp begin.
static void moveRampRight (NBEdge *ramp, int addedLanes)
Moves the ramp to the right, as new lanes were added.
Detailed Description
Definition at line 55 of file NBAlgorithms_Ramps.h.
Member Function Documentation
buildOffRamp()
void NBRampsComputer::buildOffRamp (NBNode * cur, NBNodeCont & nc, NBEdgeCont & ec, NBDistrictCont & dc, double rampLength, bool dontSplit) static private
Builds an off-ramp ending at the given node.
Parameters
[in] cur The node at which the off-ramp shall end
[in] nc The container of nodes
[in] ec The container of edges
[in] dc The container of districts
[in] rampLength The wished ramp length
[in] dontSplit Whether no edges shall be split
Definition at line 268 of file NBAlgorithms_Ramps.cpp.
References NBEdge::addLane2LaneConnections(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBNode::getIncomingEdges(), NBEdge::getLaneShape(), NBEdge::getNumLanes(), getOffRampEdges(), NBEdge::getStep(), NBEdge::incLaneNo(), NBNodeCont::insert(), NBEdge::invalidateConnections(), NBEdge::isTurningDirectionAt(), NBEdge::L2L_VALIDATED, NBEdge::LANES2LANES_USER, PositionVector::length(), MIN2(), moveRampRight(), POSITION_EPS, PositionVector::positionAtOffset(), NBEdgeCont::retrieve(), NBEdge::setGeometry(), NBEdgeCont::splitAt(), WRITE_ERROR, and WRITE_WARNING.
Referenced by computeRamps().
buildOnRamp()
void NBRampsComputer::buildOnRamp (NBNode * cur, NBNodeCont & nc, NBEdgeCont & ec, NBDistrictCont & dc, double rampLength, bool dontSplit) static private
Builds an on-ramp starting at the given node.
Parameters
[in] cur The node at which the on-ramp shall begin
[in] nc The container of nodes
[in] ec The container of edges
[in] dc The container of districts
[in] rampLength The wished ramp length
[in] dontSplit Whether no edges shall be split
Definition at line 165 of file NBAlgorithms_Ramps.cpp.
References ADDED_ON_RAMP_EDGE, NBEdge::addLane2LaneConnections(), NBEdge::getGeometry(), Named::getID(), NBEdge::getLaneShape(), NBEdge::getNumLanes(), getOnRampEdges(), NBNode::getOutgoingEdges(), NBEdge::getStep(), NBEdge::getToNode(), NBEdge::incLaneNo(), NBNodeCont::insert(), NBEdge::invalidateConnections(), NBEdge::isTurningDirectionAt(), NBEdge::L2L_VALIDATED, NBEdge::LANES2LANES_USER, PositionVector::length(), MIN2(), moveRampRight(), POSITION_EPS, PositionVector::positionAtOffset(), NBEdgeCont::retrieve(), NBEdge::setAcceleration(), NBEdge::setGeometry(), NBEdgeCont::splitAt(), WRITE_ERROR, and WRITE_WARNING.
Referenced by computeRamps().
computeRamps()
void NBRampsComputer::computeRamps (NBNetBuilder & nb, OptionsCont & oc) static
Computes highway on-/off-ramps (if wished)
Parameters
Definition at line 55 of file NBAlgorithms_Ramps.cpp.
References NBPTLineCont::addEdges2Keep(), NBParkingCont::addEdges2Keep(), NBPTStopCont::addEdges2Keep(), NBNodeCont::begin(), buildOffRamp(), buildOnRamp(), NBNodeCont::end(), OptionsCont::getBool(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), OptionsCont::getFloat(), NBEdge::getFromNode(), NBNode::getIncomingEdges(), NBNetBuilder::getNodeCont(), NBNode::getOutgoingEdges(), NBNetBuilder::getParkingCont(), NBNetBuilder::getPTLineCont(), NBNetBuilder::getPTStopCont(), NBEdgeCont::getRoundabouts(), OptionsCont::getStringVector(), NBEdge::getToNode(), OptionsCont::isSet(), mayNeedOffRamp(), mayNeedOnRamp(), NBEdgeCont::retrieve(), and WRITE_WARNING.
Referenced by NBNetBuilder::compute().
determinedByLaneNumber()
bool NBRampsComputer::determinedByLaneNumber (NBEdge ** potHighway, NBEdge ** potRamp) static private
Definition at line 387 of file NBAlgorithms_Ramps.cpp.
determinedBySpeed()
bool NBRampsComputer::determinedBySpeed (NBEdge ** potHighway, NBEdge ** potRamp) static private
Definition at line 375 of file NBAlgorithms_Ramps.cpp.
fulfillsRampConstraints()
bool NBRampsComputer::fulfillsRampConstraints (NBEdge * potHighway, NBEdge * potRamp, NBEdge * other, double minHighwaySpeed, double maxRampSpeed, const std::set< std::string > & noramps) static private
Checks whether an on-/off-ramp can be bult here.
none of the participating edges must be a macroscopic connector
ramp+highways together must have more lanes than the continuation
speeds must match the defined swells
Parameters
[in] potHighway The highway part to check
[in] potRamp The ramp part to check
[in] other The successor/predecessor edge
[in] minHighwaySpeed The minimum speed limit a highway must have for being a highway
[in] maxRampSpeed The maximum speed limit a ramp must have for being a ramp
[in] noramps Edges that shall not be treated as ramps
Returns
Whether a ramp can be built here
Definition at line 456 of file NBAlgorithms_Ramps.cpp.
References NBEdge::getAngleAtNode(), NBEdge::getFromNode(), Named::getID(), NBEdge::getNumLanes(), NBEdge::getSpeed(), NBEdge::getToNode(), hasWrongMode(), NBEdge::isMacroscopicConnector(), NBEdge::isTurningDirectionAt(), MAX3(), and NBHelpers::relAngle().
Referenced by mayNeedOffRamp(), and mayNeedOnRamp().
getOffRampEdges()
void NBRampsComputer::getOffRampEdges (NBNode * n, NBEdge ** potHighway, NBEdge ** potRamp, NBEdge ** other) static private
Definition at line 423 of file NBAlgorithms_Ramps.cpp.
References NBNode::getEdges(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), and NBContHelper::nextCW().
Referenced by buildOffRamp(), and mayNeedOffRamp().
getOnRampEdges()
void NBRampsComputer::getOnRampEdges (NBNode * n, NBEdge ** potHighway, NBEdge ** potRamp, NBEdge ** other) static private
Definition at line 399 of file NBAlgorithms_Ramps.cpp.
References NBNode::getIncomingEdges(), and NBNode::getOutgoingEdges().
Referenced by buildOnRamp(), and mayNeedOnRamp().
hasWrongMode()
bool NBRampsComputer::hasWrongMode (NBEdge * edge) static private
whether the edge has a mode that does not indicate a ramp edge
Definition at line 517 of file NBAlgorithms_Ramps.cpp.
References NBEdge::getNumLanes(), NBEdge::getPermissions(), SVC_BICYCLE, SVC_PASSENGER, and SVC_PEDESTRIAN.
Referenced by fulfillsRampConstraints().
mayNeedOffRamp()
bool NBRampsComputer::mayNeedOffRamp (NBNode * cur, double minHighwaySpeed, double maxRampSpeed, const std::set< std::string > & noramps) static private
Determines whether the given node may be an off-ramp end.
Parameters
[in] cur The node to check
[in] minHighwaySpeed The minimum speed limit a highway must have for being a highway
[in] maxRampSpeed The maximum speed limit a ramp must have for being a ramp
[in] noramps Edges that shall not be treated as ramps
Returns
Whether the node is assumed to be an off-ramp end
Definition at line 153 of file NBAlgorithms_Ramps.cpp.
References fulfillsRampConstraints(), NBNode::getIncomingEdges(), getOffRampEdges(), and NBNode::getOutgoingEdges().
Referenced by computeRamps().
mayNeedOnRamp()
bool NBRampsComputer::mayNeedOnRamp (NBNode * cur, double minHighwaySpeed, double maxRampSpeed, const std::set< std::string > & noramps) static private
Determines whether the given node may be an on-ramp begin.
Parameters
[in] cur The node to check
[in] minHighwaySpeed The minimum speed limit a highway must have for being a highway
[in] maxRampSpeed The maximum speed limit a ramp must have for being a ramp
[in] noramps Edges that shall not be treated as ramps
Returns
Whether the node is assumed to be an on-ramp begin
Definition at line 141 of file NBAlgorithms_Ramps.cpp.
References fulfillsRampConstraints(), NBNode::getIncomingEdges(), getOnRampEdges(), and NBNode::getOutgoingEdges().
Referenced by computeRamps().
moveRampRight()
void NBRampsComputer::moveRampRight (NBEdge * ramp, int addedLanes) static private
Moves the ramp to the right, as new lanes were added.
Parameters
[in] ramp The ramp to move
[in] addedLanes The number of added lanes
Definition at line 358 of file NBAlgorithms_Ramps.cpp.
References NBEdge::getGeometry(), Named::getID(), NBEdge::getLaneSpreadFunction(), NBEdge::getLaneWidth(), LANESPREAD_CENTER, PositionVector::move2side(), NBEdge::setGeometry(), SUMO_const_laneWidth, NBEdge::UNSPECIFIED_WIDTH, and WRITE_WARNING.
Referenced by buildOffRamp(), and buildOnRamp().
Field Documentation
ADDED_ON_RAMP_EDGE
const std::string NBRampsComputer::ADDED_ON_RAMP_EDGE static
suffix for newly generated on-ramp edges
Definition at line 64 of file NBAlgorithms_Ramps.h.
Referenced by buildOnRamp().
The documentation for this class was generated from the following files:
NBAlgorithms_Ramps.h
NBAlgorithms_Ramps.cpp