SUMO - Simulation of Urban MObility: GNEAdditionalFrame::SelectorParentLanes Class Reference
GNEAdditionalFrame::SelectorParentLanes Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
std::string getIdsSelected () const
get list of selecte id's in string format
void hideList ()
hide SelectorParentLanes
bool isUseSelectedLanesEnable () const
get status of checkBox UseSelectedLanes
SelectorParentLanes (FXComposite *parent, GNEViewNet *viewNet)
FOX-declaration.
void showList (std::string search="")
Show list of SelectorParentLanes.
void updateUseSelectedLanes ()
~SelectorParentLanes ()
destructor
FOX-callbacks
called when user trigger checkBox of useSelectedLanes
long onCmdUseSelectedLanes (FXObject *, FXSelector, void *)
long onCmdTypeInSearchBox (FXObject *, FXSelector, void *)
called when user type in search box
long onCmdSelectLane (FXObject *, FXSelector, void *)
called when user select a lane of the list
long onCmdClearSelection (FXObject *, FXSelector, void *)
called when clear selection button is pressed
long onCmdInvertSelection (FXObject *, FXSelector, void *)
called when invert selection button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
SelectorParentLanes ()
FOX needs this.
Private Attributes
FXButton * clearLanesSelection
button for clear selection
FXButton * helpLanes
button for help
FXButton * invertLanesSelection
button for invert selection
FXTextField * myLanesSearch
text field for search lane IDs
FXList * myList
List of SelectorParentLanes.
FXCheckButton * myUseSelectedLanesCheckButton
CheckBox for selected lanes.
GNEViewNet * myViewNet
viewNet associated to GNEAdditionalFrame
Detailed Description
Definition at line 530 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
SelectorParentLanes() [1/2]
GNEAdditionalFrame::SelectorParentLanes::SelectorParentLanes (FXComposite * parent, GNEViewNet * viewNet)
FOX-declaration.
constructor
Definition at line 1597 of file GNEAdditionalFrame.cpp.
References clearLanesSelection, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonRectangular, GUIDesignCheckButtonAttribute, GUIDesignList, GUIDesignTextField, GUIDesignTextFieldNCol, helpLanes, hideList(), invertLanesSelection, MID_GNE_ADDITIONALFRAME_CLEARLANESELECTION, MID_GNE_ADDITIONALFRAME_INVERTLANESELECTION, MID_GNE_ADDITIONALFRAME_SEARCHLANE, MID_GNE_ADDITIONALFRAME_SELECTLANE, MID_GNE_ADDITIONALFRAME_USESELECTEDLANES, MID_HELP, myLanesSearch, myList, myUseSelectedLanesCheckButton, SUMO_TAG_LANE, and toString().
~SelectorParentLanes()
GNEAdditionalFrame::SelectorParentLanes::~SelectorParentLanes ()
destructor
Definition at line 1626 of file GNEAdditionalFrame.cpp.
SelectorParentLanes() [2/2]
GNEAdditionalFrame::SelectorParentLanes::SelectorParentLanes () inline protected
FOX needs this.
Definition at line 579 of file GNEAdditionalFrame.h.
Member Function Documentation
getIdsSelected()
std::string GNEAdditionalFrame::SelectorParentLanes::getIdsSelected () const
get list of selecte id's in string format
Definition at line 1630 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::getIdsSelected(), and myList.
Referenced by GNEAdditionalFrame::addAdditional().
hideList()
void GNEAdditionalFrame::SelectorParentLanes::hideList ()
hide SelectorParentLanes
Definition at line 1652 of file GNEAdditionalFrame.cpp.
References GNEFrame::hide().
Referenced by SelectorParentLanes(), and GNEAdditionalFrame::setParametersOfAdditional().
isUseSelectedLanesEnable()
bool GNEAdditionalFrame::SelectorParentLanes::isUseSelectedLanesEnable () const
get status of checkBox UseSelectedLanes
Definition at line 1669 of file GNEAdditionalFrame.cpp.
References myUseSelectedLanesCheckButton.
Referenced by GNEAdditionalFrame::addAdditional().
onCmdClearSelection()
long GNEAdditionalFrame::SelectorParentLanes::onCmdClearSelection (FXObject * , FXSelector , void *)
called when clear selection button is pressed
Definition at line 1716 of file GNEAdditionalFrame.cpp.
References myList.
onCmdHelp()
long GNEAdditionalFrame::SelectorParentLanes::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1740 of file GNEAdditionalFrame.cpp.
onCmdInvertSelection()
long GNEAdditionalFrame::SelectorParentLanes::onCmdInvertSelection (FXObject * , FXSelector , void *)
called when invert selection button is pressed
Definition at line 1727 of file GNEAdditionalFrame.cpp.
References myList.
onCmdSelectLane()
long GNEAdditionalFrame::SelectorParentLanes::onCmdSelectLane (FXObject * , FXSelector , void *)
called when user select a lane of the list
Definition at line 1710 of file GNEAdditionalFrame.cpp.
onCmdTypeInSearchBox()
long GNEAdditionalFrame::SelectorParentLanes::onCmdTypeInSearchBox (FXObject * , FXSelector , void *)
called when user type in search box
Definition at line 1702 of file GNEAdditionalFrame.cpp.
References myLanesSearch, and showList().
onCmdUseSelectedLanes()
long GNEAdditionalFrame::SelectorParentLanes::onCmdUseSelectedLanes (FXObject * , FXSelector , void *)
Definition at line 1679 of file GNEAdditionalFrame.cpp.
References clearLanesSelection, helpLanes, invertLanesSelection, myLanesSearch, myList, and myUseSelectedLanesCheckButton.
showList()
void GNEAdditionalFrame::SelectorParentLanes::showList (std::string search = "")
Show list of SelectorParentLanes.
Definition at line 1636 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myList, myUseSelectedLanesCheckButton, myViewNet, GNENet::retrieveLanes(), and GNEAdditionalFrame::show().
Referenced by onCmdTypeInSearchBox(), and GNEAdditionalFrame::setParametersOfAdditional().
updateUseSelectedLanes()
void GNEAdditionalFrame::SelectorParentLanes::updateUseSelectedLanes ()
Definition at line 1658 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myUseSelectedLanesCheckButton, myViewNet, and GNENet::retrieveLanes().
Referenced by GNEAdditionalFrame::show().
Field Documentation
clearLanesSelection
FXButton* GNEAdditionalFrame::SelectorParentLanes::clearLanesSelection private
button for clear selection
Definition at line 595 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedLanes(), and SelectorParentLanes().
helpLanes
FXButton* GNEAdditionalFrame::SelectorParentLanes::helpLanes private
button for help
Definition at line 592 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedLanes(), and SelectorParentLanes().
invertLanesSelection
FXButton* GNEAdditionalFrame::SelectorParentLanes::invertLanesSelection private
button for invert selection
Definition at line 598 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedLanes(), and SelectorParentLanes().
myLanesSearch
FXTextField* GNEAdditionalFrame::SelectorParentLanes::myLanesSearch private
text field for search lane IDs
Definition at line 589 of file GNEAdditionalFrame.h.
Referenced by onCmdTypeInSearchBox(), onCmdUseSelectedLanes(), and SelectorParentLanes().
myList
FXList* GNEAdditionalFrame::SelectorParentLanes::myList private
List of SelectorParentLanes.
Definition at line 586 of file GNEAdditionalFrame.h.
Referenced by getIdsSelected(), onCmdClearSelection(), onCmdInvertSelection(), onCmdUseSelectedLanes(), SelectorParentLanes(), and showList().
myUseSelectedLanesCheckButton
FXCheckButton* GNEAdditionalFrame::SelectorParentLanes::myUseSelectedLanesCheckButton private
CheckBox for selected lanes.
Definition at line 583 of file GNEAdditionalFrame.h.
Referenced by isUseSelectedLanesEnable(), onCmdUseSelectedLanes(), SelectorParentLanes(), showList(), and updateUseSelectedLanes().
myViewNet
GNEViewNet* GNEAdditionalFrame::SelectorParentLanes::myViewNet private
viewNet associated to GNEAdditionalFrame
Definition at line 601 of file GNEAdditionalFrame.h.
Referenced by showList(), and updateUseSelectedLanes().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp