SUMO - Simulation of Urban MObility: GUIDialog_GLChosenEditor Class Reference
GUIDialog_GLChosenEditor Class Reference
Editor for the list of chosen objects.
#include <GUIDialog_GLChosenEditor.h>
Public Member Functions
GUIDialog_GLChosenEditor (GUIMainWindow *parent, GUISelectedStorage *str)
Constructor.
void rebuildList ()
Rebuilds the entire list.
void selectionUpdated ()
called when selection is updated
~GUIDialog_GLChosenEditor ()
Destructor.
FOX-callbacks
long onCmdLoad (FXObject *, FXSelector, void *)
Called when the user presses the Load-button.
long onCmdSave (FXObject *, FXSelector, void *)
Called when the user presses the Save-button.
long onCmdDeselect (FXObject *, FXSelector, void *)
Called when the user presses the Deselect-button.
long onCmdClear (FXObject *, FXSelector, void *)
Called when the user presses the Clear-button.
long onCmdClose (FXObject *, FXSelector, void *)
Called when the user presses the Close-button.
Protected Member Functions
GUIDialog_GLChosenEditor ()
FOX needs this.
Private Attributes
FXList * myList
The list that holds the ids.
GUIMainWindow * myParent
The parent window.
GUISelectedStorage * myStorage
The storage.
Detailed Description
Editor for the list of chosen objects.
See also
GUIMainWindow
GUISelectedStorage
Definition at line 56 of file GUIDialog_GLChosenEditor.h.
Constructor & Destructor Documentation
GUIDialog_GLChosenEditor() [1/2]
GUIDialog_GLChosenEditor::GUIDialog_GLChosenEditor (GUIMainWindow * parent, GUISelectedStorage * str)
Constructor.
Notifies both the parent and the storage about being initialised.
Parameters
[in] parent The parent window
[in] str The storage of object selections to use
Definition at line 65 of file GUIDialog_GLChosenEditor.cpp.
References GUIIconSubSys::getIcon(), GUIDesignHorizontalSeparator, ICON_APP_SELECTOR, MID_CANCEL, MID_CHOOSEN_CLEAR, MID_CHOOSEN_DESELECT, MID_CHOOSEN_LOAD, and MID_CHOOSEN_SAVE.
~GUIDialog_GLChosenEditor()
GUIDialog_GLChosenEditor::~GUIDialog_GLChosenEditor ()
Destructor.
Notifies both the parent and the storage about being destroyed.
Definition at line 111 of file GUIDialog_GLChosenEditor.cpp.
References myParent, myStorage, GUISelectedStorage::remove2Update(), and GUIMainWindow::removeChild().
GUIDialog_GLChosenEditor() [2/2]
GUIDialog_GLChosenEditor::GUIDialog_GLChosenEditor () inline protected
FOX needs this.
Definition at line 147 of file GUIDialog_GLChosenEditor.h.
Member Function Documentation
onCmdClear()
long GUIDialog_GLChosenEditor::onCmdClear (FXObject * , FXSelector , void *)
Called when the user presses the Clear-button.
Clear the internal list and calls GUISelectedStorage::clear. Repaints itself
Definition at line 201 of file GUIDialog_GLChosenEditor.cpp.
References GUISelectedStorage::clear(), gSelected, myList, myParent, and GUIMainWindow::updateChildren().
onCmdClose()
long GUIDialog_GLChosenEditor::onCmdClose (FXObject * , FXSelector , void *)
Called when the user presses the Close-button.
Closes itself.
Definition at line 211 of file GUIDialog_GLChosenEditor.cpp.
onCmdDeselect()
long GUIDialog_GLChosenEditor::onCmdDeselect (FXObject * , FXSelector , void *)
Called when the user presses the Deselect-button.
Determines which items were chosen and calls GUISelectedStorage::deselect for each.
Definition at line 179 of file GUIDialog_GLChosenEditor.cpp.
References GUISelectedStorage::deselect(), gSelected, myList, myParent, rebuildList(), and GUIMainWindow::updateChildren().
onCmdLoad()
long GUIDialog_GLChosenEditor::onCmdLoad (FXObject * , FXSelector , void *)
Called when the user presses the Load-button.
Opens a file dialog and forces the parent to load the list of selected objects when a file was chosen. Rebuilds the list, then, and redraws itself.
Todo:
Recheck loading/saving of selections
Definition at line 141 of file GUIDialog_GLChosenEditor.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), gSelected, ICON_EMPTY, GUISelectedStorage::load(), and rebuildList().
onCmdSave()
long GUIDialog_GLChosenEditor::onCmdSave (FXObject * , FXSelector , void *)
Called when the user presses the Save-button.
Opens a file dialog and forces the selection container to save the list of selected objects when a file was chosen.
If the saveing failed, a message window is shown.
Todo:
Recheck loading/saving of selections
Definition at line 164 of file GUIDialog_GLChosenEditor.cpp.
References gCurrentFolder, MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), gSelected, ICON_EMPTY, and GUISelectedStorage::save().
rebuildList()
void GUIDialog_GLChosenEditor::rebuildList ()
Rebuilds the entire list.
Definition at line 118 of file GUIDialog_GLChosenEditor.cpp.
References GUIGlObject::getFullName(), GUIGlObjectStorage::getObjectBlocking(), GUISelectedStorage::getSelected(), GUIGlObjectStorage::gIDStorage, gSelected, myList, and GUIGlObjectStorage::unblockObject().
Referenced by onCmdDeselect(), onCmdLoad(), and selectionUpdated().
selectionUpdated()
void GUIDialog_GLChosenEditor::selectionUpdated () virtual
called when selection is updated
Implements GUISelectedStorage::UpdateTarget.
Definition at line 134 of file GUIDialog_GLChosenEditor.cpp.
References rebuildList().
Field Documentation
myList
FXList* GUIDialog_GLChosenEditor::myList private
The list that holds the ids.
Definition at line 137 of file GUIDialog_GLChosenEditor.h.
Referenced by onCmdClear(), onCmdDeselect(), and rebuildList().
myParent
GUIMainWindow* GUIDialog_GLChosenEditor::myParent private
The parent window.
Definition at line 140 of file GUIDialog_GLChosenEditor.h.
Referenced by onCmdClear(), onCmdDeselect(), and ~GUIDialog_GLChosenEditor().
myStorage
GUISelectedStorage* GUIDialog_GLChosenEditor::myStorage private
The storage.
Definition at line 143 of file GUIDialog_GLChosenEditor.h.
Referenced by ~GUIDialog_GLChosenEditor().
The documentation for this class was generated from the following files:
GUIDialog_GLChosenEditor.h
GUIDialog_GLChosenEditor.cpp