SUMO - Simulation of Urban MObility: MSDevice_Battery Class Reference
MSDevice_Battery Class Reference
Battery device for electric vehicles.
#include <MSDevice_Battery.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const std::string deviceName () const
return the name for this type of device
virtual void generateOutput () const
Called on writing tripinfo output.
double getActualBatteryCapacity () const
Get the actual vehicle's Battery Capacity in kWh.
double getChargingStartTime () const
Get charging start time.
std::string getChargingStationID () const
Get current Charging Station ID.
double getConsum () const
Get consum.
const std::string & getDescription () const
double getEnergyCharged () const
Get charged energy.
SUMOVehicle & getHolder () const
Returns the vehicle that holds this device.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
double getMaximumBatteryCapacity () const
Get the total vehicle's Battery Capacity in kWh.
double getMaximumPower () const
Get the maximum power when accelerating.
std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this device. Throw exception for unsupported key
double getStoppingTreshold () const
Get stopping treshold.
int getVehicleStopped () const
Get number of timestep that vehicle is stopped.
void increaseChargingStartTime ()
Increase Charging Start time.
void increaseVehicleStoppedTimer ()
Increase myVehicleStopped.
bool isChargingInTransit () const
Get true if Vehicle it's charging, false if not.
bool isChargingStopped () const
Get true if Vehicle is charging, false if not.
virtual void loadState (const SUMOSAXAttributes &attrs)
Loads the state of the device from the given description.
virtual void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane)
Internal notification about the vehicle moves.
void resetChargingStartTime ()
Reset charging start time.
void resetVehicleStoppedTimer ()
Reset myVehicleStopped.
virtual void saveState (OutputDevice &out) const
Saves the state of the device.
void setActualBatteryCapacity (const double actualBatteryCapacity)
Set actual vehicle's Battery Capacity in kWh.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
void setMaximumBatteryCapacity (const double maximumBatteryCapacity)
Set total vehicle's Battery Capacity in kWh.
void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this device. Throw exception for unsupported key
void setPowerMax (const double new_Pmax)
Set maximum power when accelerating.
void setStoppingTreshold (const double stoppingTreshold)
Set vehicle's stopping treshold.
~MSDevice_Battery ()
Destructor.
Methods called on vehicle movement / state change, overwriting MSDevice
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Checks for waiting steps when the vehicle moves.
Interface methods, to be derived by subclasses
virtual bool notifyEnter (SUMOVehicle &veh, Notification reason, const MSLane *enteredLane)
Checks whether the reminder is activated by a vehicle entering the lane.
virtual bool notifyLeave (SUMOVehicle &veh, double lastPos, Notification reason, const MSLane *enteredLane=0)
Called if the vehicle leaves the reminder's lane.
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Static Public Member Functions
static void buildVehicleDevices (SUMOVehicle &v, std::vector< MSDevice *> &into)
Build devices for the given vehicle, if needed.
static bool checkOptions (OptionsCont &oc)
check device-specific options
static void cleanupAll ()
perform cleanup for all devices
static std::mt19937 * getEquipmentRNG ()
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void insertOptions (OptionsCont &oc)
Inserts MSDevice_Example-options.
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Static Protected Member Functions
Helper methods for device assignment
static void insertDefaultAssignmentOptions (const std::string &deviceName, const std::string &optionsTopic, OptionsCont &oc)
Adds common command options that allow to assign devices to vehicles.
static bool equippedByDefaultAssignmentOptions (const OptionsCont &oc, const std::string &deviceName, SUMOVehicle &v)
Determines whether a vehicle should get a certain device.
Protected Attributes
MSChargingStation * myActChargingStation
Parameter, Pointer to current charging station in which vehicle is placed (by default is NULL)
double myActualBatteryCapacity
Parameter, The actual vehicles's Battery Capacity in kWh, [myActualBatteryCapacity <= myMaximumBatteryCapacity].
bool myChargingInTransit
Parameter, Flag: Vehicles it's charging in transit (by default is false)
double myChargingStartTime
Parameter, Moment, wich the vehicle has beging to charging.
bool myChargingStopped
Parameter, Flag: Vehicles it's charging stopped (by default is false)
double myConsum
Parameter, Vehicle consum during a time step (by default is 0.)
std::string myDescription
a description of this moveReminder
double myEnergyCharged
Parameter, Energy charged in each timestep.
SUMOVehicle & myHolder
The vehicle that stores the device.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
double myLastAngle
Parameter, Vehicle's last angle.
double myMaximumBatteryCapacity
Parameter, The total vehicles's Battery Capacity in kWh, [myMaximumBatteryCapacity >= 0].
std::map< int, double > myParam
Parameter collection.
double myPowerMax
Parameter, The Maximum Power when accelerating, [myPowerMax >= 0].
double myStoppingTreshold
Parameter, stopping vehicle treshold [myStoppingTreshold >= 0].
int myVehicleStopped
Parameter, How many timestep the vehicle is stopped.
Private Member Functions
void checkParam (const SumoXMLAttr paramKey, const double lower=0., const double upper=std::numeric_limits< double >::infinity())
MSDevice_Battery (SUMOVehicle &holder, const std::string &id, const double actualBatteryCapacity, const double maximumBatteryCapacity, const double powerMax, const double stoppingTreshold, const std::map< int, double > &param)
Constructor.
MSDevice_Battery (const MSDevice_Battery &)
Invalidated copy constructor.
MSDevice_Battery & operator= (const MSDevice_Battery &)
Invalidated assignment operator.
Detailed Description
Battery device for electric vehicles.
Definition at line 53 of file MSDevice_Battery.h.
Member Enumeration Documentation
Notification
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
~MSDevice_Battery()
MSDevice_Battery::~MSDevice_Battery ()
Destructor.
Definition at line 267 of file MSDevice_Battery.cpp.
MSDevice_Battery() [1/2]
MSDevice_Battery::MSDevice_Battery (SUMOVehicle & holder, const std::string & id, const double actualBatteryCapacity, const double maximumBatteryCapacity, const double powerMax, const double stoppingTreshold, const std::map< int, double > & param) private
Constructor.
Parameters
[in] holder The vehicle that holds this device
[in] id The ID of the device
[in] period The period with which a new route shall be searched
[in] preInsertionPeriod The route search period before insertion
Definition at line 214 of file MSDevice_Battery.cpp.
References checkParam(), Named::getID(), myActualBatteryCapacity, myMaximumBatteryCapacity, myPowerMax, myStoppingTreshold, SUMO_ATTR_ACTUALBATTERYCAPACITY, SUMO_ATTR_AIRDRAGCOEFFICIENT, SUMO_ATTR_CONSTANTPOWERINTAKE, SUMO_ATTR_FRONTSURFACEAREA, SUMO_ATTR_INTERNALMOMENTOFINERTIA, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, SUMO_ATTR_MAXIMUMPOWER, SUMO_ATTR_PROPULSIONEFFICIENCY, SUMO_ATTR_RADIALDRAGCOEFFICIENT, SUMO_ATTR_RECUPERATIONEFFICIENCY, SUMO_ATTR_ROLLDRAGCOEFFICIENT, SUMO_ATTR_STOPPINGTRESHOLD, SUMO_ATTR_VEHICLEMASS, toString(), and WRITE_WARNING.
Referenced by buildVehicleDevices(), and deviceName().
MSDevice_Battery() [2/2]
MSDevice_Battery::MSDevice_Battery (const MSDevice_Battery &) private
Invalidated copy constructor.
Member Function Documentation
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
buildVehicleDevices()
void MSDevice_Battery::buildVehicleDevices (SUMOVehicle & v, std::vector< MSDevice *> & into) static
Build devices for the given vehicle, if needed.
The options are read and evaluated whether a example-device shall be built for the given vehicle.
The built device is stored in the given vector.
Parameters
[in] v The vehicle for which a device may be built
Definition at line 60 of file MSDevice_Battery.cpp.
References TplConvert::_2double(), DEFAULT_CHARGE_RATIO, DEFAULT_MAX_CAPACITY, MSDevice::equippedByDefaultAssignmentOptions(), HelpersEnergy::getDefaultParam(), Parameterised::getDouble(), PollutantsInterface::getEnergyHelper(), SUMOVehicle::getID(), OptionsCont::getOptions(), Parameterised::getParameter(), SUMOVehicle::getParameter(), MSVehicleType::getParameter(), SUMOVehicle::getVehicleType(), MSDevice_Battery(), SUMO_ATTR_ACTUALBATTERYCAPACITY, SUMO_ATTR_AIRDRAGCOEFFICIENT, SUMO_ATTR_CONSTANTPOWERINTAKE, SUMO_ATTR_FRONTSURFACEAREA, SUMO_ATTR_INTERNALMOMENTOFINERTIA, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, SUMO_ATTR_MAXIMUMPOWER, SUMO_ATTR_PROPULSIONEFFICIENCY, SUMO_ATTR_RADIALDRAGCOEFFICIENT, SUMO_ATTR_RECUPERATIONEFFICIENCY, SUMO_ATTR_ROLLDRAGCOEFFICIENT, SUMO_ATTR_STOPPINGTRESHOLD, SUMO_ATTR_VEHICLEMASS, and toString().
Referenced by MSDevice::buildVehicleDevices().
checkOptions()
bool MSDevice::checkOptions (OptionsCont & oc) static inherited
check device-specific options
Parameters
Definition at line 73 of file MSDevice.cpp.
References MSDevice_Routing::checkOptions().
Referenced by MSFrame::checkOptions().
checkParam()
void MSDevice_Battery::checkParam (const SumoXMLAttr paramKey, const double lower = 0., const double upper = std::numeric_limits<double>::infinity()) private
Definition at line 272 of file MSDevice_Battery.cpp.
References HelpersEnergy::getDefaultParam(), PollutantsInterface::getEnergyHelper(), Named::getID(), myParam, toString(), and WRITE_WARNING.
Referenced by deviceName(), and MSDevice_Battery().
cleanupAll()
void MSDevice::cleanupAll () static inherited
perform cleanup for all devices
Definition at line 95 of file MSDevice.cpp.
References MSDevice_Tripinfo::cleanup(), and MSDevice_Routing::cleanup().
Referenced by MSNet::clearAll(), and MSDevice::getEquipmentRNG().
deviceName()
const std::string MSDevice_Battery::deviceName () const inline virtual
return the name for this type of device
Implements MSDevice.
Definition at line 91 of file MSDevice_Battery.h.
References checkParam(), getActualBatteryCapacity(), getChargingStartTime(), getChargingStationID(), getConsum(), getEnergyCharged(), getMaximumBatteryCapacity(), getMaximumPower(), getParameter(), getStoppingTreshold(), getVehicleStopped(), increaseChargingStartTime(), increaseVehicleStoppedTimer(), isChargingInTransit(), isChargingStopped(), MSDevice_Battery(), resetChargingStartTime(), resetVehicleStoppedTimer(), setActualBatteryCapacity(), setMaximumBatteryCapacity(), setParameter(), setPowerMax(), and setStoppingTreshold().
Referenced by getParameter(), and setParameter().
equippedByDefaultAssignmentOptions()
bool MSDevice::equippedByDefaultAssignmentOptions (const OptionsCont & oc, const std::string & deviceName, SUMOVehicle & v) static protected inherited
Determines whether a vehicle should get a certain device.
Parameters
[in] oc The options container to get the information about assignment from
[in] deviceName The name of the device type
[in] v The vehicle to determine whether it shall be equipped or not
Definition at line 115 of file MSDevice.cpp.
References TplConvert::_2bool(), MSDevice::deviceName(), OptionsCont::exists(), OptionsCont::getBool(), OptionsCont::getFloat(), SUMOVehicle::getID(), MSNet::getInstance(), OptionsCont::getOptions(), Parameterised::getParameter(), SUMOVehicle::getParameter(), MSVehicleType::getParameter(), MSVehicleControl::getQuota(), OptionsCont::getStringVector(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), OptionsCont::isSet(), Parameterised::knowsParameter(), MSDevice::myEquipmentRNG, MSDevice::myExplicitIDs, and RandHelper::rand().
Referenced by buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), MSDevice_SSM::buildVehicleDevices(), and MSDevice::setParameter().
generateOutput()
virtual void MSDevice::generateOutput () const inline virtual inherited
Called on writing tripinfo output.
The device may write some statistics into the tripinfo output. It is assumed that the written information is a valid xml-snipplet, which will be embedded within the vehicle's information.
The device should use the openTag / closeTag methods of the OutputDevice for correct indentation.
Exceptions
IOError not yet implemented
Reimplemented in MSDevice_SSM, MSDevice_Tripinfo, MSDevice_Bluelight, MSDevice_Example, MSDevice_Vehroutes, and MSDevice_Emissions.
Definition at line 135 of file MSDevice.h.
References MSDevice::loadState(), and MSDevice::saveState().
getActualBatteryCapacity()
double MSDevice_Battery::getActualBatteryCapacity () const
Get the actual vehicle's Battery Capacity in kWh.
Definition at line 347 of file MSDevice_Battery.cpp.
References myActualBatteryCapacity.
Referenced by MSChargingStation::addChargeValueForOutput(), deviceName(), getParameter(), notifyMove(), and MSBatteryExport::write().
getChargingStartTime()
double MSDevice_Battery::getChargingStartTime () const
Get charging start time.
Definition at line 383 of file MSDevice_Battery.cpp.
References myChargingStartTime.
Referenced by MSChargingStation::addChargeValueForOutput(), deviceName(), and notifyMove().
getChargingStationID()
std::string MSDevice_Battery::getChargingStationID () const
Get current Charging Station ID.
Definition at line 389 of file MSDevice_Battery.cpp.
References Named::getID(), and myActChargingStation.
Referenced by deviceName(), getParameter(), and MSBatteryExport::write().
getConsum()
double MSDevice_Battery::getConsum () const
Get consum.
Definition at line 365 of file MSDevice_Battery.cpp.
References myConsum.
Referenced by deviceName(), getParameter(), and MSBatteryExport::write().
getDescription()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 234 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::getSingularType(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::write().
getEnergyCharged()
double MSDevice_Battery::getEnergyCharged () const
Get charged energy.
Definition at line 398 of file MSDevice_Battery.cpp.
References myEnergyCharged.
Referenced by deviceName(), getParameter(), and MSBatteryExport::write().
getEquipmentRNG()
static std::mt19937* MSDevice::getEquipmentRNG () inline static inherited
Definition at line 90 of file MSDevice.h.
References MSDevice::cleanupAll(), MSDevice::deviceName(), and MSDevice::myEquipmentRNG.
Referenced by NLBuilder::init(), and GUILoadThread::run().
getHolder()
SUMOVehicle& MSDevice::getHolder () const inline inherited
Returns the vehicle that holds this device.
Returns
The vehicle that holds this device
Definition at line 119 of file MSDevice.h.
References MSDevice::myHolder.
Referenced by MSChargingStation::addChargeValueForOutput().
getID()
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice::saveState(), MSDevice_Vehroutes::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getLane()
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), libsumo::InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
getMaximumBatteryCapacity()
double MSDevice_Battery::getMaximumBatteryCapacity () const
Get the total vehicle's Battery Capacity in kWh.
Definition at line 353 of file MSDevice_Battery.cpp.
References myMaximumBatteryCapacity.
Referenced by MSChargingStation::addChargeValueForOutput(), deviceName(), getParameter(), notifyMove(), and MSBatteryExport::write().
getMaximumPower()
double MSDevice_Battery::getMaximumPower () const
Get the maximum power when accelerating.
Definition at line 359 of file MSDevice_Battery.cpp.
References myPowerMax.
Referenced by deviceName().
getParameter()
std::string MSDevice_Battery::getParameter (const std::string & key) const virtual
try to retrieve the given parameter from this device. Throw exception for unsupported key
Reimplemented from MSDevice.
Definition at line 416 of file MSDevice_Battery.cpp.
References deviceName(), getActualBatteryCapacity(), getChargingStationID(), getConsum(), getEnergyCharged(), getMaximumBatteryCapacity(), SUMO_ATTR_ACTUALBATTERYCAPACITY, SUMO_ATTR_CHARGINGSTATIONID, SUMO_ATTR_ENERGYCHARGED, SUMO_ATTR_ENERGYCONSUMED, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, and toString().
Referenced by deviceName().
getStoppingTreshold()
double MSDevice_Battery::getStoppingTreshold () const
Get stopping treshold.
Definition at line 410 of file MSDevice_Battery.cpp.
References myStoppingTreshold.
Referenced by MSChargingStation::addChargeValueForOutput(), and deviceName().
getVehicleStopped()
int MSDevice_Battery::getVehicleStopped () const
Get number of timestep that vehicle is stopped.
Definition at line 404 of file MSDevice_Battery.cpp.
References myVehicleStopped.
Referenced by deviceName(), and MSBatteryExport::write().
increaseChargingStartTime()
void MSDevice_Battery::increaseChargingStartTime ()
Increase Charging Start time.
Definition at line 329 of file MSDevice_Battery.cpp.
References myChargingStartTime, and TS.
Referenced by deviceName(), and notifyMove().
increaseVehicleStoppedTimer()
void MSDevice_Battery::increaseVehicleStoppedTimer ()
Increase myVehicleStopped.
Definition at line 341 of file MSDevice_Battery.cpp.
References myVehicleStopped.
Referenced by deviceName(), and notifyMove().
insertDefaultAssignmentOptions()
void MSDevice::insertDefaultAssignmentOptions (const std::string & deviceName, const std::string & optionsTopic, OptionsCont & oc) static protected inherited
Adds common command options that allow to assign devices to vehicles.
Parameters
[in] deviceName The name of the device type
[in] optionsTopic The options topic into which the options shall be added
!! describe
!! describe
!! describe
Definition at line 101 of file MSDevice.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), and OptionsCont::doRegister().
Referenced by insertOptions(), MSDevice_Bluelight::insertOptions(), MSDevice_Example::insertOptions(), MSDevice_BTsender::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Emissions::insertOptions(), MSDevice_Routing::insertOptions(), MSDevice_SSM::insertOptions(), and MSDevice::setParameter().
insertOptions()
void MSDevice_Battery::insertOptions (OptionsCont & oc) static
Inserts MSDevice_Example-options.
Parameters
Definition at line 54 of file MSDevice_Battery.cpp.
References MSDevice::insertDefaultAssignmentOptions().
Referenced by MSDevice::insertOptions().
isChargingInTransit()
bool MSDevice_Battery::isChargingInTransit () const
Get true if Vehicle it's charging, false if not.
Definition at line 377 of file MSDevice_Battery.cpp.
References myChargingInTransit.
Referenced by deviceName(), and MSBatteryExport::write().
isChargingStopped()
bool MSDevice_Battery::isChargingStopped () const
Get true if Vehicle is charging, false if not.
Definition at line 371 of file MSDevice_Battery.cpp.
References myChargingStopped.
Referenced by deviceName(), and MSBatteryExport::write().
loadState()
void MSDevice::loadState (const SUMOSAXAttributes & attrs) virtual inherited
Loads the state of the device from the given description.
The default implementation does nothing.
Parameters
[in] attrs XML attributes describing the current state
Reimplemented in MSDevice_Tripinfo, and MSDevice_Vehroutes.
Definition at line 157 of file MSDevice.cpp.
Referenced by MSDevice::generateOutput().
notifyEnter()
virtual bool MSMoveReminder::notifyEnter (SUMOVehicle & veh, Notification reason, const MSLane * enteredLane) inline virtual inherited
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
True if vehicle enters the reminder.
See also
Notification
Reimplemented in MSDevice_SSM, MSE2Collector, MSMeanData::MeanDataValueTracker, MSDevice_Routing, MSCalibrator::VehicleRemover, MSTriggeredRerouter, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSInductLoop, MSMeanData_Amitran::MSLaneMeanDataValues, MSDevice_Bluelight, MSDevice_Example, MSDevice_BTreceiver, MSDevice_BTsender, MSMeanData::MeanDataValues, MSDevice_Vehroutes, MSRouteProbe, and MSDevice_Transportable.
Definition at line 134 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
notifyLeave()
virtual bool MSMoveReminder::notifyLeave (SUMOVehicle & veh, double lastPos, Notification reason, const MSLane * enteredLane = 0) inline virtual inherited
Called if the vehicle leaves the reminder's lane.
Informs if vehicle leaves reminder lane (due to lane change, removal from the network, or leaving to the next lane). The default is to do nothing.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also
Notification
Returns
True if the reminder wants to receive further info.
Reimplemented in MSDevice_SSM, MSE2Collector, MSMeanData::MeanDataValueTracker, MSE3Collector::MSE3LeaveReminder, MSTriggeredRerouter, MSInductLoop, MSDevice_Tripinfo, MSDevice_BTreceiver, MSDevice_BTsender, MSMeanData::MeanDataValues, MSDevice_Bluelight, MSDevice_Example, MSInstantInductLoop, MSDevice_Vehroutes, MSE3Collector::MSE3EntryReminder, MSMeanData_Net::MSLaneMeanDataValues, and MSDevice_Transportable.
Definition at line 180 of file MSMoveReminder.h.
References UNUSED_PARAMETER, and MSMoveReminder::updateDetector().
notifyMove()
bool MSDevice_Battery::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual
Checks for waiting steps when the vehicle moves.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True (always).
Reimplemented from MSMoveReminder.
Definition at line 100 of file MSDevice_Battery.cpp.
References MSChargingStation::addChargeValueForOutput(), GeomHelper::angleDiff(), HelpersEnergy::compute(), PollutantsInterface::ELEC, SUMOVehicle::getAcceleration(), getActualBatteryCapacity(), SUMOVehicle::getAngle(), MSChargingStation::getChargeDelay(), MSChargingStation::getChargeInTransit(), MSChargingStation::getChargingPower(), getChargingStartTime(), MSChargingStation::getEfficency(), PollutantsInterface::getEnergyHelper(), SUMOVehicle::getID(), MSNet::getInstance(), SUMOVehicle::getLane(), getMaximumBatteryCapacity(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getSlope(), SUMOVehicle::getSpeed(), MSNet::getStoppingPlace(), MSNet::getStoppingPlaceID(), increaseChargingStartTime(), increaseVehicleStoppedTimer(), myActChargingStation, myChargingInTransit, myChargingStopped, myConsum, myEnergyCharged, myLastAngle, myParam, myStoppingTreshold, resetChargingStartTime(), resetVehicleStoppedTimer(), setActualBatteryCapacity(), MSChargingStation::setChargingVehicle(), SUMO_ATTR_ANGLE, SUMO_TAG_CHARGING_STATION, and WRITE_WARNING.
notifyMoveInternal()
virtual void MSMoveReminder::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane) inline virtual inherited
Internal notification about the vehicle moves.
Note
meso uses this though it never calls notifyMove()
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] frontOnLane time the front of the vehicle spent on the lane.
[in] timeOnLane time some part of the vehicle spent on the lane.
[in] meanSpeedFrontOnLane Average speed for the time that the front is on the lane.
[in] meanSpeedVehicleOnLane Average speed for the time that the vehicle is on the lane (with front or back).
[in] travelledDistanceFrontOnLane distance travelled while overlapping with the lane.
[in] travelledDistanceVehicleOnLane distance travelled while front was on the lane.
[in] meanLengthOnLane the average length of the vehicle's part on the lane during the last step (==complete length in meso case)
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 212 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
operator=()
MSDevice_Battery& MSDevice_Battery::operator= (const MSDevice_Battery &) private
Invalidated assignment operator.
removeFromVehicleUpdateValues()
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 93 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
resetChargingStartTime()
void MSDevice_Battery::resetChargingStartTime ()
Reset charging start time.
Definition at line 323 of file MSDevice_Battery.cpp.
References myChargingStartTime.
Referenced by deviceName(), and notifyMove().
resetVehicleStoppedTimer()
void MSDevice_Battery::resetVehicleStoppedTimer ()
Reset myVehicleStopped.
Definition at line 335 of file MSDevice_Battery.cpp.
References myVehicleStopped.
Referenced by deviceName(), and notifyMove().
saveState()
void MSDevice::saveState (OutputDevice & out) const virtual inherited
Saves the state of the device.
The default implementation writes a warning and does nothing.
Parameters
[in] out The OutputDevice to write the information into
Reimplemented in MSDevice_Tripinfo, and MSDevice_Vehroutes.
Definition at line 151 of file MSDevice.cpp.
References Named::getID(), and WRITE_WARNING.
Referenced by MSDevice::generateOutput().
setActualBatteryCapacity()
void MSDevice_Battery::setActualBatteryCapacity (const double actualBatteryCapacity)
Set actual vehicle's Battery Capacity in kWh.
Definition at line 281 of file MSDevice_Battery.cpp.
References myActualBatteryCapacity, and myMaximumBatteryCapacity.
Referenced by deviceName(), notifyMove(), and setParameter().
setDescription()
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 230 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setMaximumBatteryCapacity()
void MSDevice_Battery::setMaximumBatteryCapacity (const double maximumBatteryCapacity)
Set total vehicle's Battery Capacity in kWh.
Definition at line 293 of file MSDevice_Battery.cpp.
References Named::getID(), myMaximumBatteryCapacity, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, toString(), and WRITE_WARNING.
Referenced by deviceName(), and setParameter().
setParameter()
void MSDevice_Battery::setParameter (const std::string & key, const std::string & value) virtual
try to set the given parameter for this device. Throw exception for unsupported key
Reimplemented from MSDevice.
Definition at line 433 of file MSDevice_Battery.cpp.
References TplConvert::_2double(), deviceName(), setActualBatteryCapacity(), setMaximumBatteryCapacity(), SUMO_ATTR_ACTUALBATTERYCAPACITY, SUMO_ATTR_MAXIMUMBATTERYCAPACITY, and toString().
Referenced by deviceName().
setPowerMax()
void MSDevice_Battery::setPowerMax (const double new_Pmax)
Set maximum power when accelerating.
Definition at line 303 of file MSDevice_Battery.cpp.
References Named::getID(), myPowerMax, SUMO_ATTR_MAXIMUMPOWER, toString(), and WRITE_WARNING.
Referenced by deviceName().
setStoppingTreshold()
void MSDevice_Battery::setStoppingTreshold (const double stoppingTreshold)
Set vehicle's stopping treshold.
Definition at line 313 of file MSDevice_Battery.cpp.
References Named::getID(), myStoppingTreshold, SUMO_ATTR_STOPPINGTRESHOLD, toString(), and WRITE_WARNING.
Referenced by deviceName().
updateDetector()
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 50 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
Field Documentation
myActChargingStation
MSChargingStation* MSDevice_Battery::myActChargingStation protected
Parameter, Pointer to current charging station in which vehicle is placed (by default is NULL)
Definition at line 204 of file MSDevice_Battery.h.
Referenced by getChargingStationID(), and notifyMove().
myActualBatteryCapacity
double MSDevice_Battery::myActualBatteryCapacity protected
Parameter, The actual vehicles's Battery Capacity in kWh, [myActualBatteryCapacity <= myMaximumBatteryCapacity].
Definition at line 174 of file MSDevice_Battery.h.
Referenced by getActualBatteryCapacity(), MSDevice_Battery(), and setActualBatteryCapacity().
myChargingInTransit
bool MSDevice_Battery::myChargingInTransit protected
Parameter, Flag: Vehicles it's charging in transit (by default is false)
Definition at line 195 of file MSDevice_Battery.h.
Referenced by isChargingInTransit(), and notifyMove().
myChargingStartTime
double MSDevice_Battery::myChargingStartTime protected
Parameter, Moment, wich the vehicle has beging to charging.
Definition at line 198 of file MSDevice_Battery.h.
Referenced by getChargingStartTime(), increaseChargingStartTime(), and resetChargingStartTime().
myChargingStopped
bool MSDevice_Battery::myChargingStopped protected
Parameter, Flag: Vehicles it's charging stopped (by default is false)
Definition at line 192 of file MSDevice_Battery.h.
Referenced by isChargingStopped(), and notifyMove().
myConsum
double MSDevice_Battery::myConsum protected
Parameter, Vehicle consum during a time step (by default is 0.)
Definition at line 201 of file MSDevice_Battery.h.
Referenced by getConsum(), and notifyMove().
myDescription
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 246 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
myEnergyCharged
double MSDevice_Battery::myEnergyCharged protected
Parameter, Energy charged in each timestep.
Definition at line 207 of file MSDevice_Battery.h.
Referenced by getEnergyCharged(), and notifyMove().
myHolder
SUMOVehicle& MSDevice::myHolder protected inherited
The vehicle that stores the device.
Definition at line 188 of file MSDevice.h.
Referenced by MSDevice_Vehroutes::addRoute(), MSDevice_Transportable::addTransportable(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDevice_Tripinfo::generateOutput(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSDevice::getHolder(), MSDevice_Routing::getParameter(), MSDevice_Vehroutes::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Routing::preInsertionReroute(), MSDevice_Transportable::removeTransportable(), MSDevice_Routing::reroute(), MSDevice_Routing::setParameter(), MSDevice_SSM::updateAndWriteOutput(), MSDevice_Tripinfo::updateStatistics(), MSDevice_Vehroutes::writeOutput(), MSDevice_Vehroutes::writeXMLRoute(), and MSDevice_Vehroutes::~MSDevice_Vehroutes().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), GNEPOILane::getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), GNEPOILane::setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myLane
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 244 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), and MSMeanData::MeanDataValueTracker::reset().
myLastAngle
double MSDevice_Battery::myLastAngle protected
Parameter, Vehicle's last angle.
Definition at line 189 of file MSDevice_Battery.h.
Referenced by notifyMove().
myMaximumBatteryCapacity
double MSDevice_Battery::myMaximumBatteryCapacity protected
Parameter, The total vehicles's Battery Capacity in kWh, [myMaximumBatteryCapacity >= 0].
Definition at line 177 of file MSDevice_Battery.h.
Referenced by getMaximumBatteryCapacity(), MSDevice_Battery(), setActualBatteryCapacity(), and setMaximumBatteryCapacity().
myParam
std::map<int, double> MSDevice_Battery::myParam protected
Parameter collection.
Definition at line 186 of file MSDevice_Battery.h.
Referenced by checkParam(), and notifyMove().
myPowerMax
double MSDevice_Battery::myPowerMax protected
Parameter, The Maximum Power when accelerating, [myPowerMax >= 0].
Definition at line 180 of file MSDevice_Battery.h.
Referenced by getMaximumPower(), MSDevice_Battery(), and setPowerMax().
myStoppingTreshold
double MSDevice_Battery::myStoppingTreshold protected
Parameter, stopping vehicle treshold [myStoppingTreshold >= 0].
Definition at line 183 of file MSDevice_Battery.h.
Referenced by getStoppingTreshold(), MSDevice_Battery(), notifyMove(), and setStoppingTreshold().
myVehicleStopped
int MSDevice_Battery::myVehicleStopped protected
Parameter, How many timestep the vehicle is stopped.
Definition at line 210 of file MSDevice_Battery.h.
Referenced by getVehicleStopped(), increaseVehicleStoppedTimer(), and resetVehicleStoppedTimer().
The documentation for this class was generated from the following files:
MSDevice_Battery.h
MSDevice_Battery.cpp