SUMO - Simulation of Urban MObility: MSTransportable::Stage_Waiting Class Reference
MSTransportable::Stage_Waiting Class Reference
#include <MSTransportable.h>
Public Member Functions
void abort (MSTransportable *)
abort this stage (TraCI)
virtual void beginEventOutput (const MSTransportable &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output.
virtual void endEventOutput (const MSTransportable &p, SUMOTime t, OutputDevice &os) const
Called for writing the events output (end of an action)
double getAngle (SUMOTime now) const
returns the angle of the transportable
double getArrivalPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
const MSEdge * getEdge () const
Returns the current edge.
double getEdgeAngle (const MSEdge *e, double at) const
get angle of the edge at a certain position
double getEdgePos (SUMOTime now) const
Position getEdgePosition (const MSEdge *e, double at, double offset) const
get position on edge e at length at with orthogonal offset
ConstMSEdgeVector getEdges () const
the edges of the current stage
const MSEdge * getFromEdge () const
Position getLanePosition (const MSLane *lane, double at, double offset) const
get position on lane at length at with orthogonal offset
Position getPosition (SUMOTime now) const
returns the position of the transportable
double getSpeed () const
the speed of the transportable
std::string getStageDescription () const
return string representation of the current stage
StageType getStageType () const
SUMOTime getUntil () const
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
SUMOTime getWaitingTime (SUMOTime now) const
the time this transportable spent waiting
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
virtual void proceed (MSNet *net, MSTransportable *transportable, SUMOTime now, Stage *previous)
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
virtual void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void setSpeed (double)
sets the walking speed (ignored in other stages)
Stage_Waiting (const MSEdge &destination, SUMOTime duration, SUMOTime until, double pos, const std::string &actType, const bool initial)
constructor
virtual void tripInfoOutput (OutputDevice &os, MSTransportable *transportable) const
Called on writing tripinfo output.
virtual ~Stage_Waiting ()
destructor
Protected Attributes
double myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
Stage_Waiting & operator= (const Stage_Waiting &)
Invalidated assignment operator.
Stage_Waiting (const Stage_Waiting &)
Invalidated copy constructor.
Private Attributes
std::string myActType
The type of activity.
SUMOTime myWaitingDuration
the time the person is waiting
SUMOTime myWaitingUntil
the time until the person is waiting
Detailed Description
A "real" stage performing a waiting over the specified time
Definition at line 215 of file MSTransportable.h.
Constructor & Destructor Documentation
Stage_Waiting() [1/2]
MSTransportable::Stage_Waiting::Stage_Waiting (const MSEdge & destination, SUMOTime duration, SUMOTime until, double pos, const std::string & actType, const bool initial)
constructor
Definition at line 101 of file MSTransportable.cpp.
~Stage_Waiting()
MSTransportable::Stage_Waiting::~Stage_Waiting () virtual
destructor
Definition at line 113 of file MSTransportable.cpp.
Stage_Waiting() [2/2]
MSTransportable::Stage_Waiting::Stage_Waiting (const Stage_Waiting &) private
Invalidated copy constructor.
Member Function Documentation
abort()
void MSTransportable::Stage_Waiting::abort (MSTransportable * t) virtual
abort this stage (TraCI)
Reimplemented from MSTransportable::Stage.
Definition at line 229 of file MSTransportable.cpp.
References MSTransportableControl::abortWaiting(), MSNet::getContainerControl(), MSNet::getInstance(), and MSNet::getPersonControl().
beginEventOutput()
void MSTransportable::Stage_Waiting::beginEventOutput (const MSTransportable & p, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 196 of file MSTransportable.cpp.
References getEdge(), Named::getID(), MSTransportable::getID(), myActType, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
endEventOutput()
void MSTransportable::Stage_Waiting::endEventOutput (const MSTransportable & p, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 203 of file MSTransportable.cpp.
References getEdge(), Named::getID(), MSTransportable::getID(), myActType, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
getAngle()
double MSTransportable::Stage_Waiting::getAngle (SUMOTime now) const virtual
returns the angle of the transportable
Implements MSTransportable::Stage.
Definition at line 148 of file MSTransportable.cpp.
References MSTransportable::Stage::getEdgeAngle(), MSNet::getInstance(), MSNet::lefthand(), M_PI, MSTransportable::Stage::myArrivalPos, and MSTransportable::Stage::myDestination.
getArrivalPos()
double MSTransportable::Stage::getArrivalPos () const inline inherited
Definition at line 91 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdge(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getFromEdge(), MSTransportable::Stage::getPosition(), and MSTransportable::Stage::myArrivalPos.
Referenced by MSRouteHandler::parseWalkPositions().
getDestination()
const MSEdge & MSTransportable::Stage::getDestination () const inherited
returns the destination edge
Definition at line 60 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by getEdges(), MSTransportable::Stage_Driving::getEdges(), MSPModel_Striping::moveInDirectionOnLane(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), and routeOutput().
getDestinationStop()
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline inherited
returns the destination stop (if any)
Definition at line 87 of file MSTransportable.h.
References MSTransportable::Stage::myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSRouteHandler::parseWalkPositions(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
getEdge()
const MSEdge * MSTransportable::Stage_Waiting::getEdge () const virtual
Returns the current edge.
Implements MSTransportable::Stage.
Definition at line 117 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by beginEventOutput(), and endEventOutput().
getEdgeAngle()
double MSTransportable::Stage::getEdgeAngle (const MSEdge * e, double at) const inherited
get angle of the edge at a certain position
Definition at line 93 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), getAngle(), MSTransportable::Stage_Driving::getAngle(), and MSTransportable::Stage::getVehicle().
getEdgePos()
double MSTransportable::Stage_Waiting::getEdgePos (SUMOTime now) const virtual
Implements MSTransportable::Stage.
Definition at line 129 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrivalPos.
getEdgePosition()
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, double at, double offset) const inherited
get position on edge e at length at with orthogonal offset
Definition at line 83 of file MSTransportable.cpp.
References MSTransportable::Stage::getLanePosition(), and MSEdge::getLanes().
Referenced by getPosition(), MSTransportable::Stage_Driving::getPosition(), and MSTransportable::Stage::getVehicle().
getEdges()
ConstMSEdgeVector MSTransportable::Stage_Waiting::getEdges () const virtual
the edges of the current stage
Implements MSTransportable::Stage.
Definition at line 222 of file MSTransportable.cpp.
References MSTransportable::Stage::getDestination().
getFromEdge()
const MSEdge * MSTransportable::Stage_Waiting::getFromEdge () const virtual
Implements MSTransportable::Stage.
Definition at line 123 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
getLanePosition()
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, double at, double offset) const inherited
get position on lane at length at with orthogonal offset
Definition at line 88 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::positionAtOffset().
Referenced by CState::computeTranshipTime(), MSTransportable::Stage::getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and MSTransportable::Stage::getVehicle().
getPosition()
Position MSTransportable::Stage_Waiting::getPosition (SUMOTime now) const virtual
returns the position of the transportable
Implements MSTransportable::Stage.
Definition at line 141 of file MSTransportable.cpp.
References MSTransportable::Stage::getEdgePosition(), MSNet::getInstance(), MSTransportable::Stage::myArrivalPos, MSTransportable::Stage::myDestination, and MSTransportable::ROADSIDE_OFFSET.
getSpeed()
double MSTransportable::Stage_Waiting::getSpeed () const virtual
the speed of the transportable
Implements MSTransportable::Stage.
Definition at line 216 of file MSTransportable.cpp.
getStageDescription()
std::string MSTransportable::Stage_Waiting::getStageDescription () const inline virtual
return string representation of the current stage
Implements MSTransportable::Stage.
Definition at line 244 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), MSTransportable::Stage::endEventOutput(), MSTransportable::Stage::proceed(), MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
getStageType()
StageType MSTransportable::Stage::getStageType () const inline inherited
Definition at line 107 of file MSTransportable.h.
References MSTransportable::Stage::getStageDescription(), MSTransportable::Stage::myType, and MSTransportable::Stage::proceed().
Referenced by MSTransportable::getStageType().
getUntil()
SUMOTime MSTransportable::Stage_Waiting::getUntil () const
Definition at line 135 of file MSTransportable.cpp.
References myWaitingUntil.
getVehicle()
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 138 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), MSTransportable::Stage::endEventOutput(), MSTransportable::Stage::getEdgeAngle(), MSTransportable::Stage::getEdgePosition(), MSTransportable::Stage::getEdges(), MSTransportable::Stage::getLanePosition(), MSTransportable::Stage::getSpeed(), MSTransportable::Stage::getWaitingTime(), MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
getWaitingTime()
SUMOTime MSTransportable::Stage_Waiting::getWaitingTime (SUMOTime now) const virtual
the time this transportable spent waiting
Implements MSTransportable::Stage.
Definition at line 210 of file MSTransportable.cpp.
References MSTransportable::Stage::myDeparted.
isWaiting4Vehicle()
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 133 of file MSTransportable.h.
isWaitingFor()
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual inherited
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 78 of file MSTransportable.cpp.
Referenced by MSTransportable::Stage::setSpeed().
operator=()
Stage_Waiting& MSTransportable::Stage_Waiting::operator= (const Stage_Waiting &) private
Invalidated assignment operator.
proceed()
void MSTransportable::Stage_Waiting::proceed (MSNet * net, MSTransportable * transportable, SUMOTime now, Stage * previous) virtual
proceeds to the next step
Implements MSTransportable::Stage.
Definition at line 154 of file MSTransportable.cpp.
References MSEdge::addContainer(), MSEdge::addPerson(), MSNet::getContainerControl(), MSTransportable::Stage::getEdge(), MSNet::getPersonControl(), MAX3(), MSTransportable::Stage::myDeparted, myWaitingDuration, myWaitingUntil, and MSTransportableControl::setWaitEnd().
routeOutput()
void MSTransportable::Stage_Waiting::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 181 of file MSTransportable.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::getDestination(), MSTransportable::getID(), MSTransportable::Stage::myType, myWaitingDuration, myWaitingUntil, OutputDevice::openTag(), SUMO_ATTR_DURATION, SUMO_ATTR_LANE, SUMO_ATTR_UNTIL, time2string(), MSTransportable::WAITING_FOR_DEPART, and OutputDevice::writeAttr().
setArrived()
void MSTransportable::Stage::setArrived (SUMOTime now) virtual inherited
logs end of the step
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 73 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrived.
Referenced by MSTransportable::Stage_Driving::getVehicle(), MSContainer::proceed(), MSPerson::proceed(), MSTransportable::Stage_Driving::setArrived(), and MSTransportable::Stage::setSpeed().
setDeparted()
void MSTransportable::Stage::setDeparted (SUMOTime now) inherited
logs end of the step
Definition at line 66 of file MSTransportable.cpp.
References MSTransportable::Stage::myDeparted.
Referenced by MSTransportable::getVehicleType(), and MSTransportable::Stage::setSpeed().
setSpeed()
virtual void MSTransportable::Stage::setSpeed (double) inline virtual inherited
sets the walking speed (ignored in other stages)
Reimplemented in MSPerson::MSPersonStage_Walking.
Definition at line 121 of file MSTransportable.h.
References MSTransportable::Stage::isWaitingFor(), MSTransportable::Stage::setArrived(), and MSTransportable::Stage::setDeparted().
Referenced by MSTransportable::getVehicle().
tripInfoOutput()
void MSTransportable::Stage_Waiting::tripInfoOutput (OutputDevice & os, MSTransportable * transportable) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 168 of file MSTransportable.cpp.
References OutputDevice::closeTag(), myActType, MSTransportable::Stage::myArrivalPos, MSTransportable::Stage::myArrived, MSTransportable::Stage::myDeparted, MSTransportable::Stage::myType, OutputDevice::openTag(), time2string(), toString(), MSTransportable::WAITING_FOR_DEPART, and OutputDevice::writeAttr().
Field Documentation
myActType
std::string MSTransportable::Stage_Waiting::myActType private
The type of activity.
Definition at line 285 of file MSTransportable.h.
Referenced by beginEventOutput(), endEventOutput(), and tripInfoOutput().
myArrivalPos
double MSTransportable::Stage::myArrivalPos protected inherited
the position at which we want to arrive
Definition at line 192 of file MSTransportable.h.
Referenced by getAngle(), MSTransportable::Stage::getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getArrivalPos(), getEdgePos(), getPosition(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSPerson::MSPersonStage_Driving::tripInfoOutput(), tripInfoOutput(), and MSPerson::MSPersonStage_Walking::walkDistance().
myArrived
SUMOTime MSTransportable::Stage::myArrived protected inherited
the time at which this stage ended
Definition at line 198 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
myDeparted
SUMOTime MSTransportable::Stage::myDeparted protected inherited
the time at which this stage started
Definition at line 195 of file MSTransportable.h.
Referenced by getWaitingTime(), MSTransportable::Stage_Driving::getWaitingTime(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), proceed(), MSTransportable::Stage::setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
myDestination
const MSEdge& MSTransportable::Stage::myDestination protected inherited
the next edge to reach by getting transported
Definition at line 186 of file MSTransportable.h.
Referenced by getAngle(), MSTransportable::Stage::getDestination(), getEdge(), getFromEdge(), and getPosition().
myDestinationStop
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected inherited
the stop to reach by getting transported (if any)
Definition at line 189 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getDestinationStop(), MSTransportable::Stage_Driving::getWaitingDescription(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSPerson::MSPersonStage_Walking::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
myType
StageType MSTransportable::Stage::myType protected inherited
The type of this stage.
Definition at line 201 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getStageType(), routeOutput(), and tripInfoOutput().
myWaitingDuration
SUMOTime MSTransportable::Stage_Waiting::myWaitingDuration private
the time the person is waiting
Definition at line 279 of file MSTransportable.h.
Referenced by proceed(), and routeOutput().
myWaitingUntil
SUMOTime MSTransportable::Stage_Waiting::myWaitingUntil private
the time until the person is waiting
Definition at line 282 of file MSTransportable.h.
Referenced by getUntil(), proceed(), and routeOutput().
The documentation for this class was generated from the following files:
MSTransportable.h
MSTransportable.cpp