SUMO - Simulation of Urban MObility: NIVisumTL::Phase Class Reference
NIVisumTL::Phase Class Reference
A phase.
#include <NIVisumTL.h>
Public Member Functions
SUMOTime getEndTime ()
Returns the stored end time.
SUMOTime getStartTime ()
Returns the stored start time.
SUMOTime getYellowTime ()
Returns the stored yellow time.
Phase (SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime)
Constructor.
~Phase ()
Destructor.
Detailed Description
A phase.
Definition at line 93 of file NIVisumTL.h.
Constructor & Destructor Documentation
Phase()
NIVisumTL::Phase::Phase (SUMOTime startTime, SUMOTime endTime, SUMOTime yellowTime) inline
Constructor.
Definition at line 96 of file NIVisumTL.h.
~Phase()
NIVisumTL::Phase::~Phase () inline
Destructor.
Definition at line 99 of file NIVisumTL.h.
Member Function Documentation
getEndTime()
SUMOTime NIVisumTL::TimePeriod::getEndTime () inline inherited
Returns the stored end time.
Definition at line 70 of file NIVisumTL.h.
References NIVisumTL::TimePeriod::myEndTime.
Referenced by NIVisumTL::build().
getStartTime()
SUMOTime NIVisumTL::TimePeriod::getStartTime () inline inherited
Returns the stored start time.
Definition at line 65 of file NIVisumTL.h.
References NIVisumTL::TimePeriod::myStartTime.
Referenced by NIVisumTL::build().
getYellowTime()
SUMOTime NIVisumTL::TimePeriod::getYellowTime () inline inherited
Returns the stored yellow time.
Definition at line 75 of file NIVisumTL.h.
References NIVisumTL::TimePeriod::myYellowTime.
Referenced by NIVisumTL::build().
The documentation for this class was generated from the following file:
NIVisumTL.h