SUMO - Simulation of Urban MObility: GNEAdditionalDialog Class Reference
GNEAdditionalDialog Class Reference abstract
Dialog to edit sequences, parameters, etc.. of Additionals.
#include <GNEAdditionalDialog.h>
Public Member Functions
GNEAdditionalDialog (GNEAdditional *parent, int width, int height)
FOX-declaration abstract.
~GNEAdditionalDialog ()
destructor
FOX-callbacks
event after press accept button
virtual long onCmdAccept (FXObject *sender, FXSelector sel, void *ptr)=0
virtual long onCmdCancel (FXObject *sender, FXSelector sel, void *ptr)=0
event after press cancel button
virtual long onCmdReset (FXObject *, FXSelector, void *)=0
event after press cancel button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNEAdditionalDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
Protected Attributes
FXVerticalFrame * myContentFrame
frame for contents
Private Member Functions
GNEAdditionalDialog (const GNEAdditionalDialog &)=delete
Invalidated copy constructor.
GNEAdditionalDialog & operator= (const GNEAdditionalDialog &)=delete
Invalidated assignment operator.
Private Attributes
FXButton * myAcceptButton
accept button
FXButton * myCancelButton
cancel button
std::string myChangesDescription
description of changes did in this additional dialog
int myNumberOfChanges
number of GNEChanges_... in dialog
FXButton * myResetButton
cancel button
GNEUndoList * myUndoList
pointer to UndoList
Detailed Description
Dialog to edit sequences, parameters, etc.. of Additionals.
Definition at line 51 of file GNEAdditionalDialog.h.
Constructor & Destructor Documentation
GNEAdditionalDialog() [1/3]
GNEAdditionalDialog::GNEAdditionalDialog (GNEAdditional * parent, int width, int height)
FOX-declaration abstract.
constructor
Definition at line 60 of file GNEAdditionalDialog.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonAccept, GUIDesignButtonCancel, GUIDesignButtonReset, GUIDesignContentsFrame, GUIDesignHorizontalFrame, ICON_ACCEPT, ICON_CANCEL, ICON_RESET, MID_GNE_ADDITIONALDIALOG_BUTTONACCEPT, MID_GNE_ADDITIONALDIALOG_BUTTONCANCEL, and MID_GNE_ADDITIONALDIALOG_BUTTONRESET.
~GNEAdditionalDialog()
GNEAdditionalDialog::~GNEAdditionalDialog ()
destructor
Definition at line 79 of file GNEAdditionalDialog.cpp.
GNEAdditionalDialog() [2/3]
GNEAdditionalDialog::GNEAdditionalDialog () inline protected
FOX needs this.
Definition at line 83 of file GNEAdditionalDialog.h.
GNEAdditionalDialog() [3/3]
GNEAdditionalDialog::GNEAdditionalDialog (const GNEAdditionalDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNECalibratorDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), GNERerouterDialog::onCmdCancel(), GNECalibratorDialog::onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
initChanges()
void GNEAdditionalDialog::initChanges () protected
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), myChangesDescription, myNumberOfChanges, myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
virtual long GNEAdditionalDialog::onCmdAccept (FXObject * sender, FXSelector sel, void * ptr) pure virtual
Implemented in GNEVariableSpeedSignDialog, GNERerouterIntervalDialog, GNECalibratorDialog, GNERerouterDialog, GNECalibratorFlowDialog, GNECalibratorRouteDialog, and GNECalibratorVehicleTypeDialog.
onCmdCancel()
virtual long GNEAdditionalDialog::onCmdCancel (FXObject * sender, FXSelector sel, void * ptr) pure virtual
event after press cancel button
Implemented in GNEVariableSpeedSignDialog, GNERerouterIntervalDialog, GNECalibratorDialog, GNERerouterDialog, GNECalibratorFlowDialog, GNECalibratorRouteDialog, and GNECalibratorVehicleTypeDialog.
onCmdReset()
virtual long GNEAdditionalDialog::onCmdReset (FXObject * , FXSelector , void *) pure virtual
event after press cancel button
Implemented in GNEVariableSpeedSignDialog, GNERerouterIntervalDialog, GNECalibratorDialog, GNERerouterDialog, GNECalibratorFlowDialog, GNECalibratorRouteDialog, and GNECalibratorVehicleTypeDialog.
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr)
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr)
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNEAdditionalDialog& GNEAdditionalDialog::operator= (const GNEAdditionalDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References myChangesDescription, myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), GNERerouterDialog::onCmdReset(), GNECalibratorDialog::onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
Field Documentation
myAcceptButton
FXButton* GNEAdditionalDialog::myAcceptButton private
accept button
Definition at line 108 of file GNEAdditionalDialog.h.
myCancelButton
FXButton* GNEAdditionalDialog::myCancelButton private
cancel button
Definition at line 111 of file GNEAdditionalDialog.h.
myChangesDescription
std::string GNEAdditionalDialog::myChangesDescription private
description of changes did in this additional dialog
Definition at line 117 of file GNEAdditionalDialog.h.
Referenced by initChanges(), and resetChanges().
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myNumberOfChanges
int GNEAdditionalDialog::myNumberOfChanges private
number of GNEChanges_... in dialog
Definition at line 120 of file GNEAdditionalDialog.h.
Referenced by initChanges().
myResetButton
FXButton* GNEAdditionalDialog::myResetButton private
cancel button
Definition at line 114 of file GNEAdditionalDialog.h.
myUndoList
GNEUndoList* GNEAdditionalDialog::myUndoList private
pointer to UndoList
Definition at line 123 of file GNEAdditionalDialog.h.
Referenced by acceptChanges(), cancelChanges(), initChanges(), and resetChanges().
The documentation for this class was generated from the following files:
GNEAdditionalDialog.h
GNEAdditionalDialog.cpp