SUMO - Simulation of Urban MObility: MSE3Collector::MSE3LeaveReminder Class Reference
MSE3Collector::MSE3LeaveReminder Class Reference
A place on the road net (at a certain lane and position on it) where the E3 area ends.
#include <MSE3Collector.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
MSE3LeaveReminder (const MSCrossSection &crossSection, MSE3Collector &collector)
Constructor.
virtual void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane)
Internal notification about the vehicle moves.
void setDescription (const std::string &description)
methods from MSMoveReminder
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double)
Checks whether the vehicle leaves.
bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Processes state changes of a vehicle.
Interface methods, to be derived by subclasses
virtual bool notifyEnter (SUMOVehicle &veh, Notification reason, const MSLane *enteredLane)
Checks whether the reminder is activated by a vehicle entering the lane.
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
MSE3LeaveReminder (const MSE3LeaveReminder &)
Invalidated copy constructor.
MSE3LeaveReminder & operator= (const MSE3LeaveReminder &)
Invalidated assignment operator.
Private Attributes
MSE3Collector & myCollector
The parent collector.
double myPosition
The position on the lane.
Detailed Description
A place on the road net (at a certain lane and position on it) where the E3 area ends.
Definition at line 137 of file MSE3Collector.h.
Member Enumeration Documentation
Notification
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSE3LeaveReminder() [1/2]
MSE3Collector::MSE3LeaveReminder::MSE3LeaveReminder (const MSCrossSection & crossSection, MSE3Collector & collector)
Constructor.
Parameters
[in] crossSection The position at which the exit lies
[in] collector The detector the exit belongs to
Definition at line 87 of file MSE3Collector.cpp.
MSE3LeaveReminder() [2/2]
MSE3Collector::MSE3LeaveReminder::MSE3LeaveReminder (const MSE3LeaveReminder &) private
Invalidated copy constructor.
Member Function Documentation
getDescription()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 234 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::getSingularType(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::write().
getLane()
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), libsumo::InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
notifyEnter()
virtual bool MSMoveReminder::notifyEnter (SUMOVehicle & veh, Notification reason, const MSLane * enteredLane) inline virtual inherited
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
True if vehicle enters the reminder.
See also
Notification
Reimplemented in MSDevice_SSM, MSE2Collector, MSMeanData::MeanDataValueTracker, MSDevice_Routing, MSCalibrator::VehicleRemover, MSTriggeredRerouter, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSInductLoop, MSMeanData_Amitran::MSLaneMeanDataValues, MSDevice_Bluelight, MSDevice_Example, MSDevice_BTreceiver, MSDevice_BTsender, MSMeanData::MeanDataValues, MSDevice_Vehroutes, MSRouteProbe, and MSDevice_Transportable.
Definition at line 134 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
notifyLeave()
bool MSE3Collector::MSE3LeaveReminder::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Processes state changes of a vehicle.
Checks whether the vehicle has changed lanes and this reminder needs to be removed
Parameters
[in] veh The leaving vehicle (unused).
[in] lastPos Position on the lane when leaving (unused).
[in] reason The reason for the state change
See also
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 124 of file MSE3Collector.cpp.
References Named::getID(), SUMOVehicle::getID(), myCollector, MSE3Collector::myEnteredContainer, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_TELEPORT, SUMO_TAG_E3DETECTOR, toString(), and WRITE_WARNING.
notifyMove()
bool MSE3Collector::MSE3LeaveReminder::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual
Checks whether the vehicle leaves.
As soon as the reported vehicle leaves the detector area (position-length>myPosition) the leaving time is computed and both are made known to the parent detector using "leave".
Parameters
[in] veh The vehicle in question.
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep.
[in] newSpeed Unused here.
Returns
False, if vehicle passed the detector entirely, else true.
See also
MSMoveReminder
MSMoveReminder::notifyMove
MSE3Collector::leave
Reimplemented from MSMoveReminder.
Definition at line 94 of file MSE3Collector.cpp.
References MSVehicleType::getLength(), SUMOVehicle::getPreviousSpeed(), SUMOVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, MSE3Collector::leave(), MSE3Collector::leaveFront(), myCollector, myPosition, MSCFModel::passingTime(), SIMTIME, and TS.
notifyMoveInternal()
virtual void MSMoveReminder::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane) inline virtual inherited
Internal notification about the vehicle moves.
Note
meso uses this though it never calls notifyMove()
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] frontOnLane time the front of the vehicle spent on the lane.
[in] timeOnLane time some part of the vehicle spent on the lane.
[in] meanSpeedFrontOnLane Average speed for the time that the front is on the lane.
[in] meanSpeedVehicleOnLane Average speed for the time that the vehicle is on the lane (with front or back).
[in] travelledDistanceFrontOnLane distance travelled while overlapping with the lane.
[in] travelledDistanceVehicleOnLane distance travelled while front was on the lane.
[in] meanLengthOnLane the average length of the vehicle's part on the lane during the last step (==complete length in meso case)
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 212 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
operator=()
MSE3LeaveReminder& MSE3Collector::MSE3LeaveReminder::operator= (const MSE3LeaveReminder &) private
Invalidated assignment operator.
removeFromVehicleUpdateValues()
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 93 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
setDescription()
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 230 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
updateDetector()
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 50 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
Field Documentation
myCollector
MSE3Collector& MSE3Collector::MSE3LeaveReminder::myCollector private
The parent collector.
Definition at line 182 of file MSE3Collector.h.
Referenced by notifyLeave(), and notifyMove().
myDescription
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 246 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
myLane
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 244 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), and MSMeanData::MeanDataValueTracker::reset().
myPosition
double MSE3Collector::MSE3LeaveReminder::myPosition private
The position on the lane.
Definition at line 185 of file MSE3Collector.h.
Referenced by notifyMove().
The documentation for this class was generated from the following files:
MSE3Collector.h
MSE3Collector.cpp