SUMO - Simulation of Urban MObility: AStarRouter< E, V, PF > Class Template Reference
AStarRouter< E, V, PF > Class Template Reference
Computes the shortest path through a network using the A* algorithm.
#include <AStarRouter.h>
Data Structures
struct EdgeInfo
class EdgeInfoComparator
Public Types
typedef FullLookupTable< E, V > FLT
typedef LandmarkLookupTable< E, V > LMLT
typedef AbstractLookupTable< E, V > LookupTable
typedef double(* Operation) (const E *const, const V *const, double)
Public Member Functions
AStarRouter (const std::vector< E *> &edges, bool unbuildIsWarning, Operation operation, const LookupTable *const lookup=0)
Constructor.
AStarRouter (const std::vector< EdgeInfo > &edgeInfos, bool unbuildIsWarning, Operation operation, const LookupTable *const lookup=0)
void buildPathFrom (const EdgeInfo *rbegin, std::vector< const E *> &edges)
Builds the path from marked edges.
virtual SUMOAbstractRouter< E, V > * clone ()
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> &into)
Builds the route between the given edges using the minimum travel time.
void endQuery (int visits)
double getEffort (const E *const e, const V *const v, double t) const
void init ()
double recomputeCosts (const std::vector< const E *> &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~AStarRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
EdgeInfoComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
const LookupTable *const myLookupTable
the lookup table for travel time heuristics
double myMaxSpeed
maximum speed in the network
Operation myOperation
The object's operation to perform.
Detailed Description
template<class E, class V, class PF>
class AStarRouter< E, V, PF >
Computes the shortest path through a network using the A* algorithm.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
EC The class to retrieve the effort for an edge from
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 84 of file AStarRouter.h.
Member Typedef Documentation
FLT
template<class E, class V, class PF> typedef FullLookupTable<E, V> AStarRouter< E, V, PF >::FLT
Definition at line 88 of file AStarRouter.h.
LMLT
template<class E, class V, class PF> typedef LandmarkLookupTable<E, V> AStarRouter< E, V, PF >::LMLT
Definition at line 89 of file AStarRouter.h.
LookupTable
template<class E, class V, class PF> typedef AbstractLookupTable<E, V> AStarRouter< E, V, PF >::LookupTable
Definition at line 87 of file AStarRouter.h.
Operation
template<class E, class V, class PF> typedef double(* AStarRouter< E, V, PF >::Operation) (const E *const, const V *const, double)
Definition at line 90 of file AStarRouter.h.
Constructor & Destructor Documentation
AStarRouter() [1/2]
template<class E, class V, class PF> AStarRouter< E, V, PF >::AStarRouter (const std::vector< E *> & edges, bool unbuildIsWarning, Operation operation, const LookupTable *const lookup = 0) inline
Constructor.
Definition at line 149 of file AStarRouter.h.
AStarRouter() [2/2]
template<class E, class V, class PF> AStarRouter< E, V, PF >::AStarRouter (const std::vector< EdgeInfo > & edgeInfos, bool unbuildIsWarning, Operation operation, const LookupTable *const lookup = 0) inline
Definition at line 160 of file AStarRouter.h.
~AStarRouter()
template<class E, class V, class PF> virtual AStarRouter< E, V, PF >::~AStarRouter () inline virtual
Destructor.
Definition at line 172 of file AStarRouter.h.
Member Function Documentation
buildPathFrom()
template<class E, class V, class PF> void AStarRouter< E, V, PF >::buildPathFrom (const EdgeInfo * rbegin, std::vector< const E *> & edges) inline
Builds the path from marked edges.
Definition at line 343 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
clone()
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* AStarRouter< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 174 of file AStarRouter.h.
compute()
template<class E, class V, class PF> virtual bool AStarRouter< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> & into) inline virtual
Builds the route between the given edges using the minimum travel time.
Implements SUMOAbstractRouter< E, V >.
Definition at line 192 of file AStarRouter.h.
endQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
getEffort()
template<class E, class V> double SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHBuilder< E, V >::synchronize().
init()
template<class E, class V, class PF> void AStarRouter< E, V, PF >::init () inline
Definition at line 178 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
recomputeCosts()
template<class E, class V, class PF> double AStarRouter< E, V, PF >::recomputeCosts (const std::vector< const E *> & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 329 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
setBulkMode()
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
startQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
myBulkMode
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
myComparator
template<class E, class V, class PF> EdgeInfoComparator AStarRouter< E, V, PF >::myComparator protected
Definition at line 361 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
myEdgeInfos
template<class E, class V, class PF> std::vector<EdgeInfo> AStarRouter< E, V, PF >::myEdgeInfos protected
The container of edge information.
Definition at line 354 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::AStarRouter(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), and AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
myErrorMsgHandler
template<class E, class V, class PF> MsgHandler* const AStarRouter< E, V, PF >::myErrorMsgHandler protected
the handler for routing errors
Definition at line 364 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), and AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
myFound
template<class E, class V, class PF> std::vector<EdgeInfo*> AStarRouter< E, V, PF >::myFound protected
list of visited Edges (for resetting)
Definition at line 359 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::init().
myFrontierList
template<class E, class V, class PF> std::vector<EdgeInfo*> AStarRouter< E, V, PF >::myFrontierList protected
A container for reusage of the min edge heap.
Definition at line 357 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::init().
myLookupTable
template<class E, class V, class PF> const LookupTable* const AStarRouter< E, V, PF >::myLookupTable protected
the lookup table for travel time heuristics
Definition at line 367 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), and AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
myMaxSpeed
template<class E, class V, class PF> double AStarRouter< E, V, PF >::myMaxSpeed protected
maximum speed in the network
Definition at line 370 of file AStarRouter.h.
Referenced by AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::AStarRouter(), and AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
myOperation
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
The documentation for this class was generated from the following file:
AStarRouter.h