SUMO - Simulation of Urban MObility: GNEInspectorFrame::AttributeInput Class Reference
GNEInspectorFrame::AttributeInput Class Reference
FOX-declaration.
#include <GNEInspectorFrame.h>
Public Member Functions
AttributeInput (FXComposite *parent, GNEInspectorFrame *inspectorFrameParent)
FOX-declaration.
SumoXMLAttr getAttr () const
get current Attr
SumoXMLTag getTag () const
get current tag
void hideAttribute ()
show attribute
void refreshAttribute ()
refresh attribute
void showAttribute (SumoXMLTag ACTag, SumoXMLAttr ACAttribute, const std::string &value)
show attribute of ac
FOX-callbacks
try to set new attribute value
long onCmdSetAttribute (FXObject *, FXSelector, void *)
long onCmdOpenAllowDisallowEditor (FXObject *, FXSelector, void *)
open model dialog for more comfortable attribute editing
Protected Member Functions
AttributeInput ()
FOX needs this.
std::string stripWhitespaceAfterComma (const std::string &stringValue)
removed invalid spaces of Positions and shapes
Private Member Functions
void hide ()
set hide as private function
void show ()
set show as private function
Private Attributes
SumoXMLAttr myAttr
current Attr
FXCheckButton * myBoolCheckButton
pointer to menu check
FXButton * myButtonCombinableChoices
pointer to buttonCombinableChoices
FXComboBox * myChoicesCombo
pointer to combo box choices
GNEInspectorFrame * myInspectorFrameParent
pointer to GNEInspectorFrame parent
FXLabel * myLabel
pointer to label
SumoXMLTag myTag
current tag
FXTextField * myTextFieldInt
textField to modify the value of int attributes
FXTextField * myTextFieldReal
textField to modify the value of real/Time attributes
FXTextField * myTextFieldStrings
textField to modify the value of string attributes
Detailed Description
FOX-declaration.
Definition at line 58 of file GNEInspectorFrame.h.
Constructor & Destructor Documentation
AttributeInput() [1/2]
GNEInspectorFrame::AttributeInput::AttributeInput (FXComposite * parent, GNEInspectorFrame * inspectorFrameParent)
FOX-declaration.
constructor
Definition at line 717 of file GNEInspectorFrame.cpp.
References GUIDesignButtonAttribute, GUIDesignCheckButtonAttribute, GUIDesignComboBoxAttribute, GUIDesignComboBoxNCol, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldInt, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, MID_GNE_INSPECTORFRAME_ATTRIBUTEEDITOR, MID_GNE_SET_ATTRIBUTE, myBoolCheckButton, myButtonCombinableChoices, myChoicesCombo, myLabel, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
AttributeInput() [2/2]
GNEInspectorFrame::AttributeInput::AttributeInput () inline protected
FOX needs this.
Definition at line 92 of file GNEInspectorFrame.h.
References stripWhitespaceAfterComma().
Member Function Documentation
getAttr()
SumoXMLAttr GNEInspectorFrame::AttributeInput::getAttr () const
get current Attr
Definition at line 867 of file GNEInspectorFrame.cpp.
References myAttr.
getTag()
SumoXMLTag GNEInspectorFrame::AttributeInput::getTag () const
get current tag
Definition at line 861 of file GNEInspectorFrame.cpp.
References myTag.
hide()
void GNEInspectorFrame::AttributeInput::hide () private
set hide as private function
Definition at line 1025 of file GNEInspectorFrame.cpp.
Referenced by hideAttribute().
hideAttribute()
void GNEInspectorFrame::AttributeInput::hideAttribute ()
show attribute
Definition at line 826 of file GNEInspectorFrame.cpp.
References hide(), myBoolCheckButton, myButtonCombinableChoices, myChoicesCombo, myLabel, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
onCmdOpenAllowDisallowEditor()
long GNEInspectorFrame::AttributeInput::onCmdOpenAllowDisallowEditor (FXObject * , FXSelector , void *)
open model dialog for more comfortable attribute editing
Definition at line 873 of file GNEInspectorFrame.cpp.
References canParseVehicleClasses(), getVehicleClassNames(), myAttr, myTextFieldStrings, onCmdSetAttribute(), SUMO_ATTR_ALLOW, and SVCAll.
onCmdSetAttribute()
long GNEInspectorFrame::AttributeInput::onCmdSetAttribute (FXObject * , FXSelector , void *)
Definition at line 894 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::discreteChoices(), GNEAttributeCarrier::discreteCombinableChoices(), GNEInspectorFrame::getACs(), OptionsCont::getOptions(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNEAttributeCarrier::hasDefaultValue(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isDiscrete(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), myAttr, myBoolCheckButton, myChoicesCombo, GNEFrame::myGEOAttributes, myInspectorFrameParent, myTag, myTextFieldInt, myTextFieldReal, myTextFieldStrings, GNEInspectorFrame::myVectorOfAttributeInputs, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEFrame::GEOAttributes::refreshGEOAttributes(), stripWhitespaceAfterComma(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_POSITION, SUMO_ATTR_SHAPE, toString(), and WRITE_WARNING.
Referenced by onCmdOpenAllowDisallowEditor().
refreshAttribute()
void GNEInspectorFrame::AttributeInput::refreshAttribute ()
refresh attribute
Definition at line 841 of file GNEInspectorFrame.cpp.
References GNEInspectorFrame::getACs(), myAttr, myInspectorFrameParent, myTag, and showAttribute().
show()
void GNEInspectorFrame::AttributeInput::show () private
set show as private function
Definition at line 1019 of file GNEInspectorFrame.cpp.
Referenced by showAttribute().
showAttribute()
void GNEInspectorFrame::AttributeInput::showAttribute (SumoXMLTag ACTag, SumoXMLAttr ACAttribute, const std::string & value)
show attribute of ac
Definition at line 747 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::discreteChoices(), GNEAttributeCarrier::discreteCombinableChoices(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isDiscrete(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isTime(), myAttr, myBoolCheckButton, myButtonCombinableChoices, myChoicesCombo, myLabel, myTag, myTextFieldInt, myTextFieldReal, myTextFieldStrings, show(), and toString().
Referenced by refreshAttribute().
stripWhitespaceAfterComma()
std::string GNEInspectorFrame::AttributeInput::stripWhitespaceAfterComma (const std::string & stringValue) protected
removed invalid spaces of Positions and shapes
Definition at line 1031 of file GNEInspectorFrame.cpp.
References StringUtils::replace().
Referenced by AttributeInput(), and onCmdSetAttribute().
Field Documentation
myAttr
SumoXMLAttr GNEInspectorFrame::AttributeInput::myAttr private
current Attr
Definition at line 105 of file GNEInspectorFrame.h.
Referenced by getAttr(), onCmdOpenAllowDisallowEditor(), onCmdSetAttribute(), refreshAttribute(), and showAttribute().
myBoolCheckButton
FXCheckButton* GNEInspectorFrame::AttributeInput::myBoolCheckButton private
pointer to menu check
Definition at line 123 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), onCmdSetAttribute(), and showAttribute().
myButtonCombinableChoices
FXButton* GNEInspectorFrame::AttributeInput::myButtonCombinableChoices private
pointer to buttonCombinableChoices
Definition at line 126 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), and showAttribute().
myChoicesCombo
FXComboBox* GNEInspectorFrame::AttributeInput::myChoicesCombo private
pointer to combo box choices
Definition at line 120 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), onCmdSetAttribute(), and showAttribute().
myInspectorFrameParent
GNEInspectorFrame* GNEInspectorFrame::AttributeInput::myInspectorFrameParent private
pointer to GNEInspectorFrame parent
Definition at line 99 of file GNEInspectorFrame.h.
Referenced by onCmdSetAttribute(), and refreshAttribute().
myLabel
FXLabel* GNEInspectorFrame::AttributeInput::myLabel private
pointer to label
Definition at line 108 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), and showAttribute().
myTag
SumoXMLTag GNEInspectorFrame::AttributeInput::myTag private
current tag
Definition at line 102 of file GNEInspectorFrame.h.
Referenced by getTag(), onCmdSetAttribute(), refreshAttribute(), and showAttribute().
myTextFieldInt
FXTextField* GNEInspectorFrame::AttributeInput::myTextFieldInt private
textField to modify the value of int attributes
Definition at line 111 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), onCmdSetAttribute(), and showAttribute().
myTextFieldReal
FXTextField* GNEInspectorFrame::AttributeInput::myTextFieldReal private
textField to modify the value of real/Time attributes
Definition at line 114 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), onCmdSetAttribute(), and showAttribute().
myTextFieldStrings
FXTextField* GNEInspectorFrame::AttributeInput::myTextFieldStrings private
textField to modify the value of string attributes
Definition at line 117 of file GNEInspectorFrame.h.
Referenced by AttributeInput(), hideAttribute(), onCmdOpenAllowDisallowEditor(), onCmdSetAttribute(), and showAttribute().
The documentation for this class was generated from the following files:
GNEInspectorFrame.h
GNEInspectorFrame.cpp