SUMO - Simulation of Urban MObility: AGCar Class Reference
AGCar Class Reference
#include <AGCar.h>
Public Member Functions
AGCar (std::string name)
AGCar (int idHH, int idCar)
bool associateTo (AGAdult *pers)
std::string getName () const
bool isAssociated () const
Private Member Functions
std::string createName (int idHH, int idCar)
Private Attributes
AGAdult * currentUser
std::string idName
Detailed Description
Definition at line 45 of file AGCar.h.
Constructor & Destructor Documentation
AGCar() [1/2]
AGCar::AGCar (std::string name) inline
Definition at line 47 of file AGCar.h.
AGCar() [2/2]
AGCar::AGCar (int idHH, int idCar) inline
Definition at line 49 of file AGCar.h.
References associateTo(), createName(), getName(), and isAssociated().
Member Function Documentation
associateTo()
bool AGCar::associateTo (AGAdult * pers)
Definition at line 53 of file AGCar.cpp.
References currentUser.
Referenced by AGCar().
createName()
std::string AGCar::createName (int idHH, int idCar) private
Definition at line 46 of file AGCar.cpp.
Referenced by AGCar().
getName()
std::string AGCar::getName () const
Definition at line 67 of file AGCar.cpp.
References idName.
Referenced by AGCar().
isAssociated()
bool AGCar::isAssociated () const
Definition at line 62 of file AGCar.cpp.
References currentUser.
Referenced by AGCar().
Field Documentation
currentUser
AGAdult* AGCar::currentUser private
Definition at line 59 of file AGCar.h.
Referenced by associateTo(), and isAssociated().
idName
std::string AGCar::idName private
Definition at line 58 of file AGCar.h.
Referenced by getName().
The documentation for this class was generated from the following files:
AGCar.h
AGCar.cpp