SUMO - Simulation of Urban MObility: NBPTStopCont Class Reference
NBPTStopCont Class Reference
#include <NBPTStopCont.h>
Public Member Functions
void addEdges2Keep (const OptionsCont &oc, std::set< std::string > &into)
add edges that must be kept
void alignIdSigns ()
void assignLanes (NBEdgeCont &cont)
std::map< std::string, NBPTStop * >::const_iterator begin () const
Returns the pointer to the begin of the stored pt stops.
std::map< std::string, NBPTStop * >::const_iterator end () const
Returns the pointer to the end of the stored pt stops.
void findAccessEdgesForRailStops (NBEdgeCont &cont, double d, int i)
NBPTStop * get (std::string id)
Retrieve a previously inserted pt stop.
bool insert (NBPTStop *ptStop)
Inserts a node into the map.
void localizePTStops (NBEdgeCont &cont)
void postprocess (std::set< std::string > &usedStops)
void reviseStops (NBEdgeCont &cont)
revise pt stops and remove stops on non existing (removed) edges
int size () const
Returns the number of pt stops stored in this container.
~NBPTStopCont ()
Static Public Member Functions
static NBEdge * getReverseEdge (NBEdge *edge)
Private Types
typedef std::map< std::string, NBPTStop * > PTStopsCont
Definition of the map of names to pt stops.
Private Member Functions
NBPTStop * assignAndCreatNewPTStopAsNeeded (NBPTStop *pStop, NBEdgeCont &cont)
void assignPTStopToEdgeOfClosestPlatform (NBPTStop *pStop, NBEdgeCont &cont)
double computeCrossProductEdgePosition (const NBEdge *edge, const Position *closestPlatform) const
NBPTPlatform * getClosestPlatformToPTStopPosition (NBPTStop *pStop)
NBPTStop * getReverseStop (NBPTStop *pStop, NBEdgeCont &cont)
Private Attributes
PTStopsCont myPTStops
The map of names to pt stops.
Detailed Description
Definition at line 30 of file NBPTStopCont.h.
Member Typedef Documentation
PTStopsCont
typedef std::map<std::string, NBPTStop*> NBPTStopCont::PTStopsCont private
Definition of the map of names to pt stops.
Definition at line 84 of file NBPTStopCont.h.
Constructor & Destructor Documentation
~NBPTStopCont()
NBPTStopCont::~NBPTStopCont ()
Definition at line 32 of file NBPTStopCont.cpp.
References myPTStops.
Member Function Documentation
addEdges2Keep()
void NBPTStopCont::addEdges2Keep (const OptionsCont & oc, std::set< std::string > & into)
add edges that must be kept
Definition at line 276 of file NBPTStopCont.cpp.
References OptionsCont::isSet(), and myPTStops.
Referenced by NBRampsComputer::computeRamps(), end(), and NBNodeCont::removeUnwishedNodes().
alignIdSigns()
void NBPTStopCont::alignIdSigns ()
Definition at line 298 of file NBPTStopCont.cpp.
References myPTStops.
Referenced by NBNetBuilder::compute().
assignAndCreatNewPTStopAsNeeded()
NBPTStop * NBPTStopCont::assignAndCreatNewPTStopAsNeeded (NBPTStop * pStop, NBEdgeCont & cont) private
Definition at line 131 of file NBPTStopCont.cpp.
References computeCrossProductEdgePosition(), NBEdgeCont::getByID(), NBPTStop::getEdgeId(), Named::getID(), NBPTPlatform::getMyLength(), NBPTPlatform::getMyPos(), NBPTStop::getPlatformCands(), getReverseEdge(), getReverseStop(), NBPTStop::setEdgeId(), and NBPTStop::setMyPTStopLength().
Referenced by localizePTStops().
assignLanes()
void NBPTStopCont::assignLanes (NBEdgeCont & cont)
Definition at line 97 of file NBPTStopCont.cpp.
References NBPTStop::findLaneAndComputeBusStopExtend(), NBEdgeCont::getGeneratedFrom(), myPTStops, and WRITE_WARNING.
Referenced by NBNetBuilder::compute(), and end().
assignPTStopToEdgeOfClosestPlatform()
void NBPTStopCont::assignPTStopToEdgeOfClosestPlatform (NBPTStop * pStop, NBEdgeCont & cont) private
Definition at line 171 of file NBPTStopCont.cpp.
References computeCrossProductEdgePosition(), NBEdgeCont::getByID(), getClosestPlatformToPTStopPosition(), NBPTStop::getEdgeId(), Named::getID(), NBPTPlatform::getMyLength(), NBPTPlatform::getMyPos(), getReverseEdge(), NBPTStop::setEdgeId(), and NBPTStop::setMyPTStopLength().
Referenced by localizePTStops().
begin()
std::map<std::string, NBPTStop*>::const_iterator NBPTStopCont::begin () const inline
Returns the pointer to the begin of the stored pt stops.
Returns
The iterator to the beginning of stored pt stops
Definition at line 53 of file NBPTStopCont.h.
References myPTStops.
Referenced by NBNodeCont::joinJunctions(), NBNetBuilder::moveToOrigin(), and NWWriter_XML::writePTStops().
computeCrossProductEdgePosition()
double NBPTStopCont::computeCrossProductEdgePosition (const NBEdge * edge, const Position * closestPlatform) const private
Definition at line 194 of file NBPTStopCont.cpp.
References NBEdge::getGeometry(), PositionVector::indexOfClosest(), PositionVector::nearest_offset_to_point2D(), PositionVector::offsetAtIndex2D(), WRITE_WARNING, Position::x(), and Position::y().
Referenced by assignAndCreatNewPTStopAsNeeded(), and assignPTStopToEdgeOfClosestPlatform().
end()
std::map<std::string, NBPTStop*>::const_iterator NBPTStopCont::end () const inline
Returns the pointer to the end of the stored pt stops.
Returns
The iterator to the end of stored pt stops
Definition at line 61 of file NBPTStopCont.h.
References addEdges2Keep(), assignLanes(), findAccessEdgesForRailStops(), localizePTStops(), myPTStops, postprocess(), and reviseStops().
Referenced by NBNodeCont::joinJunctions(), NBNetBuilder::moveToOrigin(), and NWWriter_XML::writePTStops().
findAccessEdgesForRailStops()
void NBPTStopCont::findAccessEdgesForRailStops (NBEdgeCont & cont, double d, int i)
Definition at line 316 of file NBPTStopCont.cpp.
References PositionVector::distance2D(), NBEdge::getFinalLength(), NBEdge::getGeometry(), NBEdge::getPermissions(), NamedRTree::Insert(), isRailway(), myPTStops, NamedRTree::Search(), SVC_PEDESTRIAN, Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by NBNetBuilder::compute(), and end().
get()
NBPTStop * NBPTStopCont::get (std::string id)
Retrieve a previously inserted pt stop.
Definition at line 53 of file NBPTStopCont.cpp.
References myPTStops.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::RelationHandler::myEndElement().
getClosestPlatformToPTStopPosition()
NBPTPlatform * NBPTStopCont::getClosestPlatformToPTStopPosition (NBPTStop * pStop) private
Definition at line 226 of file NBPTStopCont.cpp.
References Position::distanceSquaredTo2D(), NBPTPlatform::getMyPos(), NBPTStop::getPlatformCands(), and NBPTStop::getPosition().
Referenced by assignPTStopToEdgeOfClosestPlatform().
getReverseEdge()
NBEdge * NBPTStopCont::getReverseEdge (NBEdge * edge) static
Definition at line 247 of file NBPTStopCont.cpp.
References NBEdge::getFromNode(), NBNode::getOutgoingEdges(), and NBEdge::getToNode().
Referenced by assignAndCreatNewPTStopAsNeeded(), assignPTStopToEdgeOfClosestPlatform(), getReverseStop(), and NBPTLineCont::reviseStops().
getReverseStop()
NBPTStop * NBPTStopCont::getReverseStop (NBPTStop * pStop, NBEdgeCont & cont) private
Definition at line 116 of file NBPTStopCont.cpp.
References NBEdgeCont::getByID(), NBPTStop::getEdgeId(), NBPTStop::getID(), Named::getID(), NBPTStop::getLength(), NBPTStop::getName(), NBPTStop::getPermissions(), NBPTStop::getPosition(), and getReverseEdge().
Referenced by assignAndCreatNewPTStopAsNeeded(), and localizePTStops().
insert()
bool NBPTStopCont::insert (NBPTStop * ptStop)
Inserts a node into the map.
Parameters
[in] stop The pt stop to insert
Returns
Whether the pt stop could be added
Definition at line 41 of file NBPTStopCont.cpp.
References NBPTStop::getID(), and myPTStops.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and localizePTStops().
localizePTStops()
void NBPTStopCont::localizePTStops (NBEdgeCont & cont)
Definition at line 62 of file NBPTStopCont.cpp.
References assignAndCreatNewPTStopAsNeeded(), assignPTStopToEdgeOfClosestPlatform(), NBPTStop::getIsMultipleStopPositions(), NBPTStop::getPlatformCands(), getReverseStop(), insert(), and myPTStops.
Referenced by NBNetBuilder::compute(), and end().
postprocess()
void NBPTStopCont::postprocess (std::set< std::string > & usedStops)
Definition at line 286 of file NBPTStopCont.cpp.
References myPTStops.
Referenced by NBNetBuilder::compute(), and end().
reviseStops()
void NBPTStopCont::reviseStops (NBEdgeCont & cont)
revise pt stops and remove stops on non existing (removed) edges
Parameters
cont
Definition at line 262 of file NBPTStopCont.cpp.
References NBEdgeCont::getByID(), myPTStops, and WRITE_WARNING.
Referenced by end(), and NIImporter_OpenStreetMap::load().
size()
int NBPTStopCont::size () const inline
Returns the number of pt stops stored in this container.
Definition at line 46 of file NBPTStopCont.h.
References myPTStops.
Field Documentation
myPTStops
PTStopsCont NBPTStopCont::myPTStops private
The map of names to pt stops.
Definition at line 87 of file NBPTStopCont.h.
Referenced by addEdges2Keep(), alignIdSigns(), assignLanes(), begin(), end(), findAccessEdgesForRailStops(), get(), insert(), localizePTStops(), postprocess(), reviseStops(), size(), and ~NBPTStopCont().
The documentation for this class was generated from the following files:
NBPTStopCont.h
NBPTStopCont.cpp