SUMO - Simulation of Urban MObility: MSLane::incoming_lane_priority_sorter Class Reference
MSLane::incoming_lane_priority_sorter Class Reference
Sorts lanes (IncomingLaneInfos) by their priority or, if this doesn't apply, wrt. the angle difference magnitude relative to the target lane's angle (straight comes first)
Public Member Functions
incoming_lane_priority_sorter (const MSLane *targetLane)
constructor
int operator() (const IncomingLaneInfo &lane1, const IncomingLaneInfo &lane2) const
comparing operator
Private Member Functions
incoming_lane_priority_sorter & operator= (const incoming_lane_priority_sorter &)
Private Attributes
const MSLane *const myLane
double myLaneDir
Detailed Description
Sorts lanes (IncomingLaneInfos) by their priority or, if this doesn't apply, wrt. the angle difference magnitude relative to the target lane's angle (straight comes first)
Definition at line 1353 of file MSLane.h.
Constructor & Destructor Documentation
incoming_lane_priority_sorter()
MSLane::incoming_lane_priority_sorter::incoming_lane_priority_sorter (const MSLane * targetLane) explicit
constructor
Definition at line 2605 of file MSLane.cpp.
Member Function Documentation
operator()()
int MSLane::incoming_lane_priority_sorter::operator() (const IncomingLaneInfo & lane1, const IncomingLaneInfo & lane2) const
comparing operator
Definition at line 2610 of file MSLane.cpp.
References PositionVector::angleAt2D(), GeomHelper::angleDiff(), MSLink::getFoeLinks(), Named::getID(), MSLane::getIncomingLanes(), MSLane::getLinkTo(), MSLane::getShape(), MSLane::isInternal(), MSLane::IncomingLaneInfo::lane, myLane, myLaneDir, and MSLane::IncomingLaneInfo::viaLink.
operator=()
incoming_lane_priority_sorter& MSLane::incoming_lane_priority_sorter::operator= (const incoming_lane_priority_sorter &) private
Field Documentation
myLane
const MSLane* const MSLane::incoming_lane_priority_sorter::myLane private
Definition at line 1364 of file MSLane.h.
Referenced by operator()().
myLaneDir
double MSLane::incoming_lane_priority_sorter::myLaneDir private
Definition at line 1365 of file MSLane.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
MSLane.h
MSLane.cpp