SUMO - Simulation of Urban MObility: MSFCDExport Class Reference
MSFCDExport Class Reference
Realises dumping FCD Data.
#include <MSFCDExport.h>
Static Public Member Functions
static void write (OutputDevice &of, SUMOTime timestep, bool elevation)
Writes the position and the angle of each vehicle into the given device.
Private Member Functions
MSFCDExport (const MSFCDExport &)
Invalidated copy constructor.
MSFCDExport & operator= (const MSFCDExport &)
Invalidated assignment operator.
Static Private Member Functions
static void writeTransportable (OutputDevice &of, const MSEdge *e, MSTransportable *p, SumoXMLTag tag, bool useGeo, bool elevation)
write transportable
Detailed Description
Realises dumping FCD Data.
The class offers a static method, which writes Position of each vehicle of the network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 56 of file MSFCDExport.h.
Constructor & Destructor Documentation
MSFCDExport()
MSFCDExport::MSFCDExport (const MSFCDExport &) private
Invalidated copy constructor.
Member Function Documentation
operator=()
MSFCDExport& MSFCDExport::operator= (const MSFCDExport &) private
Invalidated assignment operator.
write()
void MSFCDExport::write (OutputDevice & of, SUMOTime timestep, bool elevation) static
Writes the position and the angle of each vehicle into the given device.
Opens the current time step and export the values vehicle id, position and angle
Parameters
[in] of The output device to use
[in] timestep The current time step
[in] elevation Whether elevation data shall be written
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 54 of file MSFCDExport.cpp.
References GeoConvHelper::cartesian2geo(), OutputDevice::closeTag(), SUMOVehicle::getAngle(), OptionsCont::getBool(), MSVehicle::getContainers(), MSLane::getEdge(), MSNet::getEdgeControl(), MSEdgeControl::getEdges(), GeoConvHelper::getFinal(), Named::getID(), SUMOVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicle::getLane(), OptionsCont::getOptions(), MSNet::getPersonControl(), MSVehicle::getPersons(), SUMOVehicle::getPosition(), SUMOVehicle::getPositionOnLane(), MSVehicle::getSignals(), SUMOVehicle::getSlope(), SUMOVehicle::getSpeed(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), gPrecisionGeo, MSTransportableControl::hasTransportables(), SUMOVehicle::isOnRoad(), SUMOVehicle::isParking(), SUMOVehicle::isRemoteControlled(), MSVehicleControl::loadedVehBegin(), MSVehicleControl::loadedVehEnd(), GeomHelper::naviDegree(), OutputDevice::openTag(), OutputDevice::setPrecision(), SUMO_ATTR_ANGLE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SLOPE, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TYPE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_Z, SUMO_TAG_CONTAINER, SUMO_TAG_PERSON, SUMO_TAG_VEHICLE, time2string(), toString(), OutputDevice::writeAttr(), writeTransportable(), Position::x(), Position::y(), and Position::z().
Referenced by MSNet::writeOutput().
writeTransportable()
void MSFCDExport::writeTransportable (OutputDevice & of, const MSEdge * e, MSTransportable * p, SumoXMLTag tag, bool useGeo, bool elevation) static private
write transportable
Definition at line 127 of file MSFCDExport.cpp.
References GeoConvHelper::cartesian2geo(), OutputDevice::closeTag(), MSTransportable::getAngle(), MSTransportable::getEdgePos(), GeoConvHelper::getFinal(), Named::getID(), MSTransportable::getID(), MSEdge::getLanes(), MSTransportable::getPosition(), MSTransportable::getSpeed(), gPrecisionGeo, GeomHelper::naviDegree(), OutputDevice::openTag(), OutputDevice::setPrecision(), SUMO_ATTR_ANGLE, SUMO_ATTR_EDGE, SUMO_ATTR_ID, SUMO_ATTR_POSITION, SUMO_ATTR_SLOPE, SUMO_ATTR_SPEED, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_Z, OutputDevice::writeAttr(), Position::x(), Position::y(), and Position::z().
Referenced by write().
The documentation for this class was generated from the following files:
MSFCDExport.h
MSFCDExport.cpp