SUMO - Simulation of Urban MObility: MSStopOut Class Reference
MSStopOut Class Reference
Realises dumping the complete network state.
#include <MSStopOut.h>
Data Structures
struct StopInfo
Public Member Functions
void loadedContainers (const SUMOVehicle *veh, int n)
void loadedPersons (const SUMOVehicle *veh, int n)
MSStopOut (OutputDevice &dev)
constructor.
void stopEnded (const SUMOVehicle *veh, const MSVehicle::Stop &stop)
void stopStarted (const SUMOVehicle *veh, int numPersons, int numContainers)
void unloadedContainers (const SUMOVehicle *veh, int n)
void unloadedPersons (const SUMOVehicle *veh, int n)
virtual ~MSStopOut ()
Destructor.
Static Public Member Functions
static bool active ()
static MSStopOut * getInstance ()
static void init ()
Static intialization.
Private Types
typedef std::map< const SUMOVehicle *, StopInfo > Stopped
Private Member Functions
MSStopOut (const MSStopOut &)
Invalidated copy constructor.
MSStopOut & operator= (const MSStopOut &)
Invalidated assignment operator.
Private Attributes
OutputDevice & myDevice
Stopped myStopped
Static Private Attributes
static MSStopOut * myInstance = 0
Detailed Description
Realises dumping the complete network state.
The class offers a static method, which writes the complete dump of the given network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 56 of file MSStopOut.h.
Member Typedef Documentation
Stopped
typedef std::map<const SUMOVehicle*, StopInfo> MSStopOut::Stopped private
Definition at line 121 of file MSStopOut.h.
Constructor & Destructor Documentation
MSStopOut() [1/2]
MSStopOut::MSStopOut (OutputDevice & dev)
constructor.
Definition at line 55 of file MSStopOut.cpp.
Referenced by getInstance(), and init().
~MSStopOut()
MSStopOut::~MSStopOut () virtual
Destructor.
Definition at line 59 of file MSStopOut.cpp.
Referenced by getInstance().
MSStopOut() [2/2]
MSStopOut::MSStopOut (const MSStopOut &) private
Invalidated copy constructor.
Member Function Documentation
active()
static bool MSStopOut::active () inline static
Definition at line 63 of file MSStopOut.h.
References myInstance.
Referenced by MSDevice_Transportable::addTransportable(), MSDevice_Transportable::notifyMove(), MSVehicle::processNextStop(), MSDevice_Transportable::removeTransportable(), and MSVehicle::resumeFromStopping().
getInstance()
static MSStopOut* MSStopOut::getInstance (void) inline static
Definition at line 67 of file MSStopOut.h.
References loadedContainers(), loadedPersons(), MSStopOut(), myInstance, stopEnded(), stopStarted(), unloadedContainers(), unloadedPersons(), and ~MSStopOut().
Referenced by MSDevice_Transportable::addTransportable(), MSDevice_Transportable::notifyMove(), MSVehicle::processNextStop(), MSDevice_Transportable::removeTransportable(), and MSVehicle::resumeFromStopping().
init()
void MSStopOut::init () static
Static intialization.
Definition at line 45 of file MSStopOut.cpp.
References OutputDevice::getDeviceByOption(), OptionsCont::getOptions(), MSStopOut(), and myInstance.
Referenced by MSFrame::buildStreams().
loadedContainers()
void MSStopOut::loadedContainers (const SUMOVehicle * veh, int n)
Definition at line 83 of file MSStopOut.cpp.
References myStopped.
Referenced by MSDevice_Transportable::addTransportable(), getInstance(), and MSDevice_Transportable::removeTransportable().
loadedPersons()
void MSStopOut::loadedPersons (const SUMOVehicle * veh, int n)
Definition at line 73 of file MSStopOut.cpp.
References myStopped.
Referenced by MSDevice_Transportable::addTransportable(), getInstance(), and MSDevice_Transportable::removeTransportable().
operator=()
MSStopOut& MSStopOut::operator= (const MSStopOut &) private
Invalidated assignment operator.
stopEnded()
void MSStopOut::stopEnded (const SUMOVehicle * veh, const MSVehicle::Stop & stop)
Definition at line 93 of file MSStopOut.cpp.
References MSVehicle::Stop::busstop, MSVehicle::Stop::chargingStation, OutputDevice::closeTag(), MSVehicle::Stop::containerstop, Named::getID(), SUMOVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), MSStopOut::StopInfo::initialNumContainers, MSStopOut::StopInfo::initialNumPersons, MSVehicle::Stop::lane, MSStopOut::StopInfo::loadedContainers, MSStopOut::StopInfo::loadedPersons, myDevice, myStopped, OutputDevice::openTag(), SUMOVehicleParameter::Stop::parking, MSVehicle::Stop::parkingarea, MSVehicle::Stop::pars, MSStopOut::StopInfo::started, STEPS2TIME, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_PARKING, SUMO_ATTR_PARKING_AREA, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, time2string(), MSStopOut::StopInfo::unloadedContainers, MSStopOut::StopInfo::unloadedPersons, SUMOVehicleParameter::Stop::until, WRITE_WARNING, and OutputDevice::writeAttr().
Referenced by getInstance(), and MSVehicle::resumeFromStopping().
stopStarted()
void MSStopOut::stopStarted (const SUMOVehicle * veh, int numPersons, int numContainers)
Definition at line 63 of file MSStopOut.cpp.
References SUMOVehicle::getID(), MSNet::getInstance(), myStopped, and WRITE_WARNING.
Referenced by getInstance(), and MSVehicle::processNextStop().
unloadedContainers()
void MSStopOut::unloadedContainers (const SUMOVehicle * veh, int n)
Definition at line 88 of file MSStopOut.cpp.
References myStopped.
Referenced by getInstance(), and MSDevice_Transportable::notifyMove().
unloadedPersons()
void MSStopOut::unloadedPersons (const SUMOVehicle * veh, int n)
Definition at line 78 of file MSStopOut.cpp.
References myStopped.
Referenced by getInstance(), and MSDevice_Transportable::notifyMove().
Field Documentation
myDevice
OutputDevice& MSStopOut::myDevice private
Definition at line 124 of file MSStopOut.h.
Referenced by stopEnded().
myInstance
MSStopOut * MSStopOut::myInstance = 0 static private
Definition at line 126 of file MSStopOut.h.
Referenced by active(), getInstance(), and init().
myStopped
Stopped MSStopOut::myStopped private
Definition at line 122 of file MSStopOut.h.
Referenced by loadedContainers(), loadedPersons(), stopEnded(), stopStarted(), unloadedContainers(), and unloadedPersons().
The documentation for this class was generated from the following files:
MSStopOut.h
MSStopOut.cpp