SUMO - Simulation of Urban MObility: GNEAdditionalFrame::AdditionalAttributes Class Reference
GNEAdditionalFrame::AdditionalAttributes Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
void addAttribute (SumoXMLTag additionalTag, SumoXMLAttr AdditionalAttributeSingle)
add attribute
AdditionalAttributes (GNEViewNet *viewNet, FXComposite *parent)
FOX-declaration.
bool areValuesValid () const
check if parameters of attributes are valid
void clearAttributes ()
clear attributes
std::map< SumoXMLAttr, std::string > getAttributesAndValues () const
get attributes and their values
int getNumberOfAddedAttributes () const
get number of added attributes
void hideAdditionalParameters ()
hide group box
void showAdditionalParameters ()
show group box
void showWarningMessage (std::string extra="") const
show warning message with information about non-valid attributes
~AdditionalAttributes ()
destructor
FOX-callbacks
Called when help button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Protected Member Functions
AdditionalAttributes ()
FOX needs this.
Private Attributes
FXButton * helpAdditional
button for help
int maxNumberOfListParameters
max number of parameters (Defined in constructor)
int maxNumberOfParameters
max number of parameters (Defined in constructor)
SumoXMLTag myAdditionalTag
current additional tag
int myIndexParameter
Index for myVectorOfsingleAdditionalParameter.
int myIndexParameterList
index for myIndexParameterList
std::vector< AdditionalAttributeSingle * > myVectorOfsingleAdditionalParameter
vector with the additional parameters
std::vector< AdditionalAttributeList * > myVectorOfsingleAdditionalParameterList
vector with the additional parameters of type list
GNEViewNet * myViewNet
pointer to viewNet
Detailed Description
Definition at line 233 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
AdditionalAttributes() [1/2]
GNEAdditionalFrame::AdditionalAttributes::AdditionalAttributes (GNEViewNet * viewNet, FXComposite * parent)
FOX-declaration.
constructor
Definition at line 926 of file GNEAdditionalFrame.cpp.
References GUIDesignButtonRectangular, helpAdditional, maxNumberOfListParameters, maxNumberOfParameters, MID_HELP, myVectorOfsingleAdditionalParameter, and myVectorOfsingleAdditionalParameterList.
~AdditionalAttributes()
GNEAdditionalFrame::AdditionalAttributes::~AdditionalAttributes ()
destructor
Definition at line 949 of file GNEAdditionalFrame.cpp.
AdditionalAttributes() [2/2]
GNEAdditionalFrame::AdditionalAttributes::AdditionalAttributes () inline protected
FOX needs this.
Definition at line 276 of file GNEAdditionalFrame.h.
Member Function Documentation
addAttribute()
void GNEAdditionalFrame::AdditionalAttributes::addAttribute (SumoXMLTag additionalTag, SumoXMLAttr AdditionalAttributeSingle)
add attribute
Definition at line 971 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::getDefaultValue(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), maxNumberOfListParameters, maxNumberOfParameters, myAdditionalTag, myIndexParameter, myIndexParameterList, myVectorOfsingleAdditionalParameter, myVectorOfsingleAdditionalParameterList, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
areValuesValid()
bool GNEAdditionalFrame::AdditionalAttributes::areValuesValid () const
check if parameters of attributes are valid
Definition at line 1081 of file GNEAdditionalFrame.cpp.
References myIndexParameter, myIndexParameterList, myVectorOfsingleAdditionalParameter, and myVectorOfsingleAdditionalParameterList.
Referenced by GNEAdditionalFrame::addAdditional().
clearAttributes()
void GNEAdditionalFrame::AdditionalAttributes::clearAttributes ()
clear attributes
Definition at line 953 of file GNEAdditionalFrame.cpp.
References maxNumberOfListParameters, maxNumberOfParameters, myIndexParameter, myIndexParameterList, myVectorOfsingleAdditionalParameter, and myVectorOfsingleAdditionalParameterList.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
getAttributesAndValues()
std::map< SumoXMLAttr, std::string > GNEAdditionalFrame::AdditionalAttributes::getAttributesAndValues () const
get attributes and their values
Definition at line 1032 of file GNEAdditionalFrame.cpp.
References myIndexParameter, myIndexParameterList, myVectorOfsingleAdditionalParameter, and myVectorOfsingleAdditionalParameterList.
Referenced by GNEAdditionalFrame::addAdditional().
getNumberOfAddedAttributes()
int GNEAdditionalFrame::AdditionalAttributes::getNumberOfAddedAttributes () const
get number of added attributes
Definition at line 1101 of file GNEAdditionalFrame.cpp.
References myIndexParameter, and myIndexParameterList.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
hideAdditionalParameters()
void GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters ()
hide group box
Definition at line 1026 of file GNEAdditionalFrame.cpp.
References GNEFrame::hide().
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
onCmdHelp()
long GNEAdditionalFrame::AdditionalAttributes::onCmdHelp (FXObject * , FXSelector , void *)
Definition at line 1107 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::getDefinition(), GUIIconSubSys::getIcon(), GUIDesignButtonOK, GUIDesignDialogBox, ICON_ACCEPT, GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), MID_TABLE, myAdditionalTag, myIndexParameter, myIndexParameterList, myVectorOfsingleAdditionalParameter, myVectorOfsingleAdditionalParameterList, and toString().
showAdditionalParameters()
void GNEAdditionalFrame::AdditionalAttributes::showAdditionalParameters ()
show group box
Definition at line 1019 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::show().
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
showWarningMessage()
void GNEAdditionalFrame::AdditionalAttributes::showWarningMessage (std::string extra = "") const
show warning message with information about non-valid attributes
Definition at line 1047 of file GNEAdditionalFrame.cpp.
References OptionsCont::getOptions(), myAdditionalTag, myIndexParameter, myIndexParameterList, myVectorOfsingleAdditionalParameter, myVectorOfsingleAdditionalParameterList, myViewNet, GNEViewNet::setStatusBarText(), toString(), and WRITE_WARNING.
Referenced by GNEAdditionalFrame::addAdditional().
Field Documentation
helpAdditional
FXButton* GNEAdditionalFrame::AdditionalAttributes::helpAdditional private
button for help
Definition at line 304 of file GNEAdditionalFrame.h.
Referenced by AdditionalAttributes().
maxNumberOfListParameters
int GNEAdditionalFrame::AdditionalAttributes::maxNumberOfListParameters private
max number of parameters (Defined in constructor)
Definition at line 301 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), AdditionalAttributes(), and clearAttributes().
maxNumberOfParameters
int GNEAdditionalFrame::AdditionalAttributes::maxNumberOfParameters private
max number of parameters (Defined in constructor)
Definition at line 298 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), AdditionalAttributes(), and clearAttributes().
myAdditionalTag
SumoXMLTag GNEAdditionalFrame::AdditionalAttributes::myAdditionalTag private
current additional tag
Definition at line 283 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), onCmdHelp(), and showWarningMessage().
myIndexParameter
int GNEAdditionalFrame::AdditionalAttributes::myIndexParameter private
Index for myVectorOfsingleAdditionalParameter.
Definition at line 289 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), areValuesValid(), clearAttributes(), getAttributesAndValues(), getNumberOfAddedAttributes(), onCmdHelp(), and showWarningMessage().
myIndexParameterList
int GNEAdditionalFrame::AdditionalAttributes::myIndexParameterList private
index for myIndexParameterList
Definition at line 295 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), areValuesValid(), clearAttributes(), getAttributesAndValues(), getNumberOfAddedAttributes(), onCmdHelp(), and showWarningMessage().
myVectorOfsingleAdditionalParameter
std::vector<AdditionalAttributeSingle*> GNEAdditionalFrame::AdditionalAttributes::myVectorOfsingleAdditionalParameter private
vector with the additional parameters
Definition at line 286 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), AdditionalAttributes(), areValuesValid(), clearAttributes(), getAttributesAndValues(), onCmdHelp(), and showWarningMessage().
myVectorOfsingleAdditionalParameterList
std::vector<AdditionalAttributeList*> GNEAdditionalFrame::AdditionalAttributes::myVectorOfsingleAdditionalParameterList private
vector with the additional parameters of type list
Definition at line 292 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), AdditionalAttributes(), areValuesValid(), clearAttributes(), getAttributesAndValues(), onCmdHelp(), and showWarningMessage().
myViewNet
GNEViewNet* GNEAdditionalFrame::AdditionalAttributes::myViewNet private
pointer to viewNet
Definition at line 280 of file GNEAdditionalFrame.h.
Referenced by showWarningMessage().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp