SUMO - Simulation of Urban MObility: libsumo::MultiEntryExit Class Reference
libsumo::MultiEntryExit Class Reference
#include <MultiEntryExit.h>
Static Public Member Functions
static int getIDCount ()
static std::vector< std::string > getIDList ()
static int getLastStepHaltingNumber (const std::string &detID)
static double getLastStepMeanSpeed (const std::string &detID)
static std::vector< std::string > getLastStepVehicleIDs (const std::string &detID)
static int getLastStepVehicleNumber (const std::string &detID)
Private Member Functions
MultiEntryExit ()
invalidated standard constructor
MultiEntryExit (const MultiEntryExit &src)
invalidated copy constructor
MultiEntryExit & operator= (const MultiEntryExit &src)
invalidated assignment operator
Static Private Member Functions
static MSE3Collector * getDetector (const std::string &detID)
Detailed Description
Definition at line 49 of file MultiEntryExit.h.
Constructor & Destructor Documentation
MultiEntryExit() [1/2]
libsumo::MultiEntryExit::MultiEntryExit () private
invalidated standard constructor
MultiEntryExit() [2/2]
libsumo::MultiEntryExit::MultiEntryExit (const MultiEntryExit & src) private
invalidated copy constructor
Member Function Documentation
getDetector()
MSE3Collector * MultiEntryExit::getDetector (const std::string & detID) static private
Definition at line 84 of file MultiEntryExit.cpp.
References NamedObjectCont< T >::get(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), and SUMO_TAG_ENTRY_EXIT_DETECTOR.
Referenced by getLastStepHaltingNumber(), getLastStepMeanSpeed(), getLastStepVehicleIDs(), and getLastStepVehicleNumber().
getIDCount()
int MultiEntryExit::getIDCount () static
Definition at line 53 of file MultiEntryExit.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::size(), and SUMO_TAG_ENTRY_EXIT_DETECTOR.
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
getIDList()
std::vector< std::string > MultiEntryExit::getIDList () static
Definition at line 45 of file MultiEntryExit.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::insertIDs(), and SUMO_TAG_ENTRY_EXIT_DETECTOR.
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
getLastStepHaltingNumber()
int MultiEntryExit::getLastStepHaltingNumber (const std::string & detID) static
Definition at line 78 of file MultiEntryExit.cpp.
References MSE3Collector::getCurrentHaltingNumber(), and getDetector().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
getLastStepMeanSpeed()
double MultiEntryExit::getLastStepMeanSpeed (const std::string & detID) static
Definition at line 66 of file MultiEntryExit.cpp.
References MSE3Collector::getCurrentMeanSpeed(), and getDetector().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
getLastStepVehicleIDs()
std::vector< std::string > MultiEntryExit::getLastStepVehicleIDs (const std::string & detID) static
Definition at line 72 of file MultiEntryExit.cpp.
References MSE3Collector::getCurrentVehicleIDs(), and getDetector().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
getLastStepVehicleNumber()
int MultiEntryExit::getLastStepVehicleNumber (const std::string & detID) static
Definition at line 60 of file MultiEntryExit.cpp.
References getDetector(), and MSE3Collector::getVehiclesWithin().
Referenced by TraCIServerAPI_MultiEntryExit::processGet().
operator=()
MultiEntryExit& libsumo::MultiEntryExit::operator= (const MultiEntryExit & src) private
invalidated assignment operator
The documentation for this class was generated from the following files:
MultiEntryExit.h
MultiEntryExit.cpp