SUMO - Simulation of Urban MObility: RODFNet Class Reference
RODFNet Class Reference
A DFROUTER-network.
#include <RODFNet.h>
Data Structures
class DFRouteDescByTimeComperator
struct idComp
comparator for maps using edges as key, used only in myDetectorsOnEdges to make tests comparable
struct IterationEdge
Public Types
typedef std::map< const SUMOTime, std::vector< RORoutable * > > RoutablesMap
Public Member Functions
void addRestriction (const std::string &id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
void buildApproachList ()
void buildDetectorDependencies (RODFDetectorCon &detectors)
void buildEdgeFlowMap (const RODFDetectorFlows &flows, const RODFDetectorCon &detectors, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
void buildRoutes (RODFDetectorCon &det, bool keepUnfoundEnds, bool includeInBetween, bool keepShortestOnly, int maxFollowingLength) const
void cleanup ()
closes the file output for computed routes and deletes associated threads if necessary
void computeTypes (RODFDetectorCon &dets, bool sourcesStrict) const
double getAbsPos (const RODFDetector &det) const
double getAvgSpeedFactorLKW () const
double getAvgSpeedFactorPKW () const
const std::vector< std::string > & getDetectorList (ROEdge *edge) const
const NamedObjectCont< ROEdge * > & getEdgeMap () const
int getEdgeNumber () const
Returns the total number of edges the network contains including internal edges.
int getInternalEdgeNumber () const
Returns the number of internal edges the network contains.
double getMaxSpeedFactorLKW () const
double getMaxSpeedFactorPKW () const
const std::map< SUMOVehicleClass, double > * getRestrictions (const std::string &id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
OutputDevice * getRouteOutput (const bool alternative=false)
bool hasDetector (ROEdge *edge) const
bool hasPermissions () const
void mesoJoin (RODFDetectorCon &detectors, RODFDetectorFlows &flows)
void openOutput (const OptionsCont &options)
Opens the output for computed routes.
void removeEmptyDetectors (RODFDetectorCon &detectors, RODFDetectorFlows &flows)
void reportEmptyDetectors (RODFDetectorCon &detectors, RODFDetectorFlows &flows)
void revalidateFlows (const RODFDetectorCon &detectors, RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
RODFNet (bool amInHighwayMode)
Constructor.
void setPermissionsFound ()
void writeIntermodal (const OptionsCont &options, ROIntermodalRouter &router) const
Writes the intermodal network and weights if requested.
~RODFNet ()
Destructor.
Insertion and retrieval of graph parts
virtual bool addEdge (ROEdge *edge)
bool addDistrict (const std::string id, ROEdge *source, ROEdge *sink)
bool addDistrictEdge (const std::string tazID, const std::string edgeID, const bool isSource)
const std::map< std::string, std::pair< std::vector< std::string >, std::vector< std::string > > > & getDistricts () const
Retrieves all TAZ (districts) from the network.
ROEdge * getEdge (const std::string &name) const
Retrieves an edge from the network.
ROEdge * getEdgeForLaneID (const std::string &laneID) const
Retrieves an edge from the network when the lane id is given.
void addNode (RONode *node)
RONode * getNode (const std::string &id) const
Retrieves an node from the network.
void addStoppingPlace (const std::string &id, const SumoXMLTag category, SUMOVehicleParameter::Stop *stop)
const SUMOVehicleParameter::Stop * getStoppingPlace (const std::string &id, const SumoXMLTag category) const
Retrieves a stopping place from the network.
Insertion and retrieval of vehicle types, vehicles, routes, and route definitions
bool checkVType (const std::string &id)
Checks whether the vehicle type (distribution) may be added.
virtual bool addVehicleType (SUMOVTypeParameter *type)
Adds a read vehicle type definition to the network.
bool addVTypeDistribution (const std::string &id, RandomDistributor< SUMOVTypeParameter *> *vehTypeDistribution)
Adds a vehicle type distribution.
SUMOVTypeParameter * getVehicleTypeSecure (const std::string &id)
Retrieves the named vehicle type.
bool addRouteDef (RORouteDef *def)
RORouteDef * getRouteDef (const std::string &name) const
Returns the named route definition.
virtual bool addVehicle (const std::string &id, ROVehicle *veh)
bool addFlow (SUMOVehicleParameter *flow, const bool randomize)
bool addPerson (ROPerson *person)
void addContainer (const SUMOTime depart, const std::string desc)
Processing stored vehicle definitions
SUMOTime saveAndRemoveRoutesUntil (OptionsCont &options, const RORouterProvider &provider, SUMOTime time)
Computes routes described by their definitions and saves them.
virtual bool furtherStored ()
Returns the information whether further vehicles, persons or containers are stored.
Static Public Member Functions
static void adaptIntermodalRouter (ROIntermodalRouter &router)
static RONet * getInstance ()
Returns the pointer to the unique instance of RONet (singleton).
Protected Member Functions
void buildDetectorEdgeDependencies (RODFDetectorCon &dets) const
void computeRoutesFor (ROEdge *edge, RODFRouteDesc &base, int no, bool keepUnfoundEnds, bool keepShortestOnly, ROEdgeVector &visited, const RODFDetector &det, RODFRouteCont &into, const RODFDetectorCon &detectors, int maxFollowingLength, ROEdgeVector &seen) const
ROEdge * getDetectorEdge (const RODFDetector &det) const
bool hasApproached (ROEdge *edge) const
bool hasApproaching (ROEdge *edge) const
bool hasInBetweenDetectorsOnly (ROEdge *edge, const RODFDetectorCon &detectors) const
bool hasSourceDetector (ROEdge *edge, const RODFDetectorCon &detectors) const
bool isDestination (const RODFDetector &det, const RODFDetectorCon &detectors) const
bool isDestination (const RODFDetector &det, ROEdge *edge, ROEdgeVector &seen, const RODFDetectorCon &detectors) const
bool isFalseSource (const RODFDetector &det, const RODFDetectorCon &detectors) const
bool isFalseSource (const RODFDetector &det, ROEdge *edge, ROEdgeVector &seen, const RODFDetectorCon &detectors) const
bool isSource (const RODFDetector &det, const RODFDetectorCon &detectors, bool strict) const
bool isSource (const RODFDetector &det, ROEdge *edge, ROEdgeVector &seen, const RODFDetectorCon &detectors, bool strict) const
void revalidateFlows (const RODFDetector *detector, RODFDetectorFlows &flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Private Attributes
bool myAmInHighwayMode
std::map< ROEdge *, ROEdgeVector > myApproachedEdges
Map of edge name->list of names of edges approached by this edge.
std::map< ROEdge *, ROEdgeVector > myApproachingEdges
Map of edge name->list of names of this edge approaching edges.
double myAvgSpeedFactorLKW
double myAvgSpeedFactorPKW
std::map< std::string, ROEdge * > myDetectorEdges
std::map< ROEdge *, std::vector< std::string >, idComp > myDetectorsOnEdges
std::vector< std::string > myDisallowedEdges
List of ids of edges that shall not be used.
int myInBetweenNumber
int myInvalidNumber
bool myKeepTurnarounds
double myMaxSpeedFactorLKW
double myMaxSpeedFactorPKW
maximum speed factor in measurements
int mySinkNumber
int mySourceNumber
Detailed Description
A DFROUTER-network.
Definition at line 51 of file RODFNet.h.
Member Typedef Documentation
RoutablesMap
typedef std::map<const SUMOTime, std::vector<RORoutable*> > RONet::RoutablesMap inherited
Definition at line 77 of file RONet.h.
Constructor & Destructor Documentation
RODFNet()
RODFNet::RODFNet (bool amInHighwayMode)
Constructor.
Parameters
[in] amInHighwayMode Whether search for following edges shall stop at slow edges
Definition at line 52 of file RODFNet.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), OptionsCont::getStringVector(), myDisallowedEdges, and myKeepTurnarounds.
~RODFNet()
RODFNet::~RODFNet ()
Destructor.
Definition at line 64 of file RODFNet.cpp.
Member Function Documentation
adaptIntermodalRouter()
void RONet::adaptIntermodalRouter (ROIntermodalRouter & router) static inherited
Definition at line 657 of file RONet.cpp.
References IntermodalRouter< E, L, N, V, INTERNALROUTER >::addAccess(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::addSchedule(), RONet::getEdgeForLaneID(), RORouteDef::getFirstRoute(), RORoutable::getParameter(), RONet::getRouteDef(), RORoute::getStops(), RONet::myFlows, RONet::myInstance, RONet::myPTVehicles, RONet::myStoppingPlaces, SUMO_TAG_BUS_STOP, and SUMO_TAG_PARKING_AREA.
Referenced by computeRoutes(), and RONet::getEdgeMap().
addContainer()
void RONet::addContainer (const SUMOTime depart, const std::string desc) inherited
Definition at line 398 of file RONet.cpp.
References RONet::myContainers.
Referenced by RORouteHandler::closeContainer(), and RONet::getRouteDef().
addDistrict()
bool RONet::addDistrict (const std::string id, ROEdge * source, ROEdge * sink) inherited
Definition at line 151 of file RONet.cpp.
References RONet::addEdge(), EDGEFUNC_CONNECTOR, RONet::myDistricts, ROEdge::setFunction(), and WRITE_ERROR.
Referenced by RONetHandler::parseDistrict().
addDistrictEdge()
bool RONet::addDistrictEdge (const std::string tazID, const std::string edgeID, const bool isSource) inherited
Definition at line 168 of file RONet.cpp.
References ROEdge::addSuccessor(), RONet::getEdge(), RONet::myDistricts, and WRITE_ERROR.
Referenced by RONetHandler::parseDistrict(), and RONetHandler::parseDistrictEdge().
addEdge()
bool RONet::addEdge (ROEdge * edge) virtual inherited
Definition at line 137 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), ROEdge::isInternal(), RONet::myEdges, RONet::myNumInternalEdges, and WRITE_ERROR.
Referenced by RONet::addDistrict(), and RONetHandler::parseEdge().
addFlow()
bool RONet::addFlow (SUMOVehicleParameter * flow, const bool randomize) inherited
Definition at line 372 of file RONet.cpp.
References NamedObjectCont< T >::add(), SUMOVehicleParameter::depart, SUMOVehicleParameter::id, RONet::myDepartures, RONet::myFlows, RandHelper::rand(), SUMOVehicleParameter::repetitionNumber, and SUMOVehicleParameter::repetitionOffset.
Referenced by RORouteHandler::closeFlow(), and RONet::getRouteDef().
addNode()
void RONet::addNode (RONode * node) inherited
Definition at line 190 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), RONet::myNodes, and WRITE_ERROR.
Referenced by RONet::getEdgeForLaneID(), and RONetHandler::parseEdge().
addPerson()
bool RONet::addPerson (ROPerson * person) inherited
Definition at line 386 of file RONet.cpp.
References RORoutable::getDepart(), RORoutable::getID(), RONet::myPersonIDs, RONet::myRoutables, and WRITE_ERROR.
Referenced by RORouteHandler::closePerson(), and RONet::getRouteDef().
addRestriction()
void RONet::addRestriction (const std::string & id, const SUMOVehicleClass svc, const double speed) inherited
Adds a restriction for an edge type.
Parameters
[in] id The id of the type
[in] svc The vehicle class the restriction refers to
[in] speed The restricted speed
Definition at line 121 of file RONet.cpp.
References RONet::myRestrictions.
Referenced by RONetHandler::myStartElement().
addRouteDef()
bool RONet::addRouteDef (RORouteDef * def) inherited
Definition at line 208 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and RONet::myRoutes.
Referenced by RORouteHandler::closeRoute(), RORouteHandler::closeRouteDistribution(), and RONet::getStoppingPlace().
addStoppingPlace()
void RONet::addStoppingPlace (const std::string & id, const SumoXMLTag category, SUMOVehicleParameter::Stop * stop) inherited
Definition at line 199 of file RONet.cpp.
References RONet::myStoppingPlaces, SUMO_TAG_BUS_STOP, SUMO_TAG_TRAIN_STOP, toString(), and WRITE_ERROR.
Referenced by RONet::getNode(), and RONetHandler::parseStoppingPlace().
addVehicle()
bool RONet::addVehicle (const std::string & id, ROVehicle * veh) virtual inherited
Definition at line 352 of file RONet.cpp.
References RORoutable::getDepart(), OptionsCont::getOptions(), RORoutable::isPartOfFlow(), RORoutable::isPublicTransport(), RONet::myPTVehicles, RONet::myRoutables, RONet::myVehIDs, and WRITE_ERROR.
Referenced by RONet::checkFlows(), RORouteHandler::closeVehicle(), and RONet::getRouteDef().
addVehicleType()
bool RONet::addVehicleType (SUMOVTypeParameter * type) virtual inherited
Adds a read vehicle type definition to the network.
If the vehicle type definition is already known (another one with the same id exists), false is returned, and the vehicle type is deleted.
Parameters
[in] def The vehicle type to add
Returns
Whether the vehicle type could be added
Definition at line 329 of file RONet.cpp.
References NamedObjectCont< T >::add(), RONet::checkVType(), SUMOVTypeParameter::id, RONet::myVehicleTypes, and WRITE_ERROR.
Referenced by RONet::getStoppingPlace(), and RORouteHandler::myEndElement().
addVTypeDistribution()
bool RONet::addVTypeDistribution (const std::string & id, RandomDistributor< SUMOVTypeParameter *> * vehTypeDistribution) inherited
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns
Whether the vehicle type could be added
Definition at line 342 of file RONet.cpp.
References RONet::checkVType(), and RONet::myVTypeDistDict.
Referenced by RORouteHandler::closeVehicleTypeDistribution(), and RONet::getStoppingPlace().
buildApproachList()
void RODFNet::buildApproachList ()
Definition at line 69 of file RODFNet.cpp.
References RONet::getEdgeMap(), ROEdge::getFromJunction(), Named::getID(), ROEdge::getSuccessors(), ROEdge::getToJunction(), ROEdge::isInternal(), myApproachedEdges, myApproachingEdges, myDisallowedEdges, and myKeepTurnarounds.
buildDetectorDependencies()
void RODFNet::buildDetectorDependencies (RODFDetectorCon & detectors)
Definition at line 1032 of file RODFNet.cpp.
References RODFDetector::addPriorDetector(), buildDetectorEdgeDependencies(), RODFDetectorCon::getDetector(), RODFDetectorCon::getModifiableDetector(), RODFDetector::getRouteVector(), RODFDetector::hasRoutes(), myDetectorEdges, and myDetectorsOnEdges.
Referenced by startComputation().
buildDetectorEdgeDependencies()
void RODFNet::buildDetectorEdgeDependencies (RODFDetectorCon & dets) const protected
Definition at line 102 of file RODFNet.cpp.
References getDetectorEdge(), RODFDetectorCon::getDetectors(), myDetectorEdges, and myDetectorsOnEdges.
Referenced by buildDetectorDependencies(), buildRoutes(), computeTypes(), getAvgSpeedFactorLKW(), and mesoJoin().
buildEdgeFlowMap()
void RODFNet::buildEdgeFlowMap (const RODFDetectorFlows & flows, const RODFDetectorCon & detectors, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 934 of file RODFNet.cpp.
References fd, FlowDef::fLKW, RODFDetectorCon::getDetector(), RODFDetectorFlows::getFlowDefs(), Named::getID(), RODFDetector::getPos(), ROEdge::getSpeedLimit(), ROEdge::getVClassMaxSpeed(), FlowDef::isLKW, RODFDetectorFlows::knows(), MAX2(), myAvgSpeedFactorLKW, myAvgSpeedFactorPKW, myDetectorsOnEdges, myMaxSpeedFactorLKW, myMaxSpeedFactorPKW, FlowDef::qLKW, FlowDef::qPKW, SVC_PASSENGER, SVC_TRUCK, toString(), FlowDef::vLKW, FlowDef::vPKW, and WRITE_MESSAGE.
Referenced by startComputation().
buildRoutes()
void RODFNet::buildRoutes (RODFDetectorCon & det, bool keepUnfoundEnds, bool includeInBetween, bool keepShortestOnly, int maxFollowingLength) const
!!;
!!routes->removeIllegal(illegals);
!!;
Definition at line 347 of file RODFNet.cpp.
References BETWEEN_DETECTOR, buildDetectorEdgeDependencies(), computeRoutesFor(), RODFRouteDesc::distance, RODFRouteDesc::distance2Last, RODFRouteDesc::duration2Last, RODFRouteDesc::duration_2, RODFRouteDesc::edges2Pass, RODFRouteDesc::endDetectorEdge, RODFRouteDesc::factor, RODFRouteCont::get(), RODFDetectorCon::getDetector(), getDetectorEdge(), RODFDetectorCon::getDetectors(), ROEdge::getLength(), ROEdge::getSpeedLimit(), RODFDetector::getType(), RODFRouteDesc::lastDetectorEdge, myDetectorsOnEdges, and RODFRouteDesc::overallProb.
Referenced by startComputation().
checkVType()
bool RONet::checkVType (const std::string & id) inherited
Checks whether the vehicle type (distribution) may be added.
This method checks also whether the default type may still be replaced
Parameters
[in] id The id of the vehicle type (distribution) to add
Returns
Whether the type (distribution) may be added
Definition at line 304 of file RONet.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, NamedObjectCont< T >::get(), RONet::myDefaultPedTypeMayBeDeleted, RONet::myDefaultVTypeMayBeDeleted, RONet::myVehicleTypes, RONet::myVTypeDistDict, and NamedObjectCont< T >::remove().
Referenced by RONet::addVehicleType(), RONet::addVTypeDistribution(), and RONet::getStoppingPlace().
cleanup()
void RONet::cleanup () inherited
closes the file output for computed routes and deletes associated threads if necessary
Definition at line 253 of file RONet.cpp.
References RouteCostCalculator< R, E, V >::cleanup(), OutputDevice::close(), RONet::myRouteAlternativesOutput, RONet::myRoutesOutput, and RONet::myTypesOutput.
Referenced by computeRoutes(), and RONet::getRouteDef().
computeRoutesFor()
void RODFNet::computeRoutesFor (ROEdge * edge, RODFRouteDesc & base, int no, bool keepUnfoundEnds, bool keepShortestOnly, ROEdgeVector & visited, const RODFDetector & det, RODFRouteCont & into, const RODFDetectorCon & detectors, int maxFollowingLength, ROEdgeVector & seen) const protected
!!! //toDiscard.push_back(current);
!!
Definition at line 188 of file RODFNet.cpp.
References RODFRouteCont::addRouteDesc(), RODFRouteDesc::distance, RODFRouteDesc::distance2Last, RODFRouteDesc::duration2Last, RODFRouteDesc::duration_2, RODFRouteDesc::edges2Pass, RODFRouteDesc::endDetectorEdge, RODFRouteDesc::factor, getDetectorEdge(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getOptions(), ROEdge::getSpeedLimit(), hasApproached(), hasDetector(), hasInBetweenDetectorsOnly(), hasSourceDetector(), RODFRouteDesc::lastDetectorEdge, myAmInHighwayMode, myApproachedEdges, RODFRouteDesc::passedNo, RODFRouteCont::removeRouteDesc(), UNUSED_PARAMETER, and WRITE_WARNING.
Referenced by buildRoutes(), and getAvgSpeedFactorLKW().
computeTypes()
void RODFNet::computeTypes (RODFDetectorCon & dets, bool sourcesStrict) const
Definition at line 115 of file RODFNet.cpp.
References BETWEEN_DETECTOR, buildDetectorEdgeDependencies(), DISCARDED_DETECTOR, RODFDetectorCon::getDetectors(), isDestination(), isFalseSource(), isSource(), myInBetweenNumber, myInvalidNumber, mySinkNumber, mySourceNumber, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, SINK_DETECTOR, SOURCE_DETECTOR, toString(), TYPE_NOT_DEFINED, and WRITE_MESSAGE.
Referenced by startComputation().
furtherStored()
bool RONet::furtherStored () virtual inherited
Returns the information whether further vehicles, persons or containers are stored.
Definition at line 639 of file RONet.cpp.
References RONet::myContainers, RONet::myFlows, RONet::myRoutables, and NamedObjectCont< T >::size().
Referenced by RONet::getRouteDef(), ROLoader::openRoutes(), and ROLoader::processRoutes().
getAbsPos()
double RODFNet::getAbsPos (const RODFDetector & det) const
Definition at line 677 of file RODFNet.cpp.
References getDetectorEdge(), ROEdge::getLength(), and RODFDetector::getPos().
Referenced by isDestination(), and isSource().
getAvgSpeedFactorLKW()
double RODFNet::getAvgSpeedFactorLKW () const inline
Definition at line 105 of file RODFNet.h.
References buildDetectorEdgeDependencies(), computeRoutesFor(), getDetectorEdge(), hasApproached(), hasApproaching(), hasInBetweenDetectorsOnly(), hasSourceDetector(), isDestination(), isFalseSource(), isSource(), myAvgSpeedFactorLKW, and revalidateFlows().
Referenced by RODFDetectorCon::writeEmitters().
getAvgSpeedFactorPKW()
double RODFNet::getAvgSpeedFactorPKW () const inline
Definition at line 101 of file RODFNet.h.
References myAvgSpeedFactorPKW.
Referenced by RODFDetectorCon::writeEmitters().
getDetectorEdge()
ROEdge * RODFNet::getDetectorEdge (const RODFDetector & det) const protected
Definition at line 632 of file RODFNet.cpp.
References RONet::getEdge(), Named::getID(), and RODFDetector::getLaneID().
Referenced by buildDetectorEdgeDependencies(), buildRoutes(), computeRoutesFor(), getAbsPos(), getAvgSpeedFactorLKW(), isDestination(), isFalseSource(), isSource(), and revalidateFlows().
getDetectorList()
const std::vector< std::string > & RODFNet::getDetectorList (ROEdge * edge) const
Definition at line 671 of file RODFNet.cpp.
References myDetectorsOnEdges.
getDistricts()
const std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string> > >& RONet::getDistricts () const inline inherited
Retrieves all TAZ (districts) from the network.
Returns
The map of all districts
Definition at line 151 of file RONet.h.
References RONet::myDistricts.
Referenced by main().
getEdge()
ROEdge* RONet::getEdge (const std::string & name) const inline inherited
Retrieves an edge from the network.
This is not very pretty, but necessary, though, as routes run over instances, not over ids.
Parameters
[in] name The name of the edge to retrieve
Returns
The named edge if known, otherwise 0
Definition at line 163 of file RONet.h.
References NamedObjectCont< T >::get(), and RONet::myEdges.
Referenced by RONet::addDistrictEdge(), ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), RORouteHandler::addPersonTrip(), RORouteHandler::addStop(), ROJTRTurnDefLoader::addToEdge(), ROJTRTurnDefLoader::beginFromEdge(), getDetectorEdge(), RONet::getEdgeForLaneID(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), loadJTRDefinitions(), RODFDetectorHandler::myStartElement(), ROJTRTurnDefLoader::myStartElement(), RORouteHandler::myStartElement(), RONetHandler::parseConnection(), RORouteHandler::parseEdges(), RORouteHandler::parseFromViaTo(), AGActivityGenHandler::parseStreets(), ROVehicle::ROVehicle(), ROMAAssignments::sue(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
getEdgeForLaneID()
ROEdge* RONet::getEdgeForLaneID (const std::string & laneID) const inline inherited
Retrieves an edge from the network when the lane id is given.
Parameters
[in] laneID The name of the lane to retrieve the edge for
Returns
The edge of the named lane if known, otherwise 0
Definition at line 173 of file RONet.h.
References RONet::addNode(), and RONet::getEdge().
Referenced by RONet::adaptIntermodalRouter(), ROVehicle::addStop(), RONetHandler::parseAccess(), and RONetHandler::parseStoppingPlace().
getEdgeMap()
const NamedObjectCont<ROEdge*>& RONet::getEdgeMap () const inline inherited
Definition at line 400 of file RONet.h.
References RONet::adaptIntermodalRouter(), RONet::hasPermissions(), RONet::myEdges, and RONet::setPermissionsFound().
Referenced by buildApproachList(), AGCity::completeStreets(), ROMAAssignments::incremental(), initNet(), ROLoader::loadWeights(), ROMAAssignments::resetFlows(), ROMAAssignments::sue(), and writeInterval().
getEdgeNumber()
int RONet::getEdgeNumber () const inherited
Returns the total number of edges the network contains including internal edges.
Definition at line 645 of file RONet.cpp.
References RONet::myEdges, and NamedObjectCont< T >::size().
Referenced by computeAllPairs(), computeRoutes(), RONet::getRouteDef(), and main().
getInstance()
RONet * RONet::getInstance (void) static inherited
Returns the pointer to the unique instance of RONet (singleton).
Returns
Pointer to the unique RONet-instance
Definition at line 61 of file RONet.cpp.
References RONet::myInstance.
Referenced by ROPerson::addTrip(), and ROEdge::getSuccessors().
getInternalEdgeNumber()
int RONet::getInternalEdgeNumber () const inherited
Returns the number of internal edges the network contains.
Definition at line 651 of file RONet.cpp.
References RONet::myNumInternalEdges.
Referenced by computeAllPairs(), and RONet::getRouteDef().
getMaxSpeedFactorLKW()
double RODFNet::getMaxSpeedFactorLKW () const inline
Definition at line 97 of file RODFNet.h.
References myMaxSpeedFactorLKW.
Referenced by RODFDetectorCon::writeEmitters().
getMaxSpeedFactorPKW()
double RODFNet::getMaxSpeedFactorPKW () const inline
Definition at line 93 of file RODFNet.h.
References myMaxSpeedFactorPKW.
Referenced by RODFDetectorCon::writeEmitters().
getNode()
RONode* RONet::getNode (const std::string & id) const inline inherited
Retrieves an node from the network.
Parameters
[in] name The name of the node to retrieve
Returns
The named node if known, otherwise 0
Todo:
Check whether a const pointer may be returned
Definition at line 195 of file RONet.h.
References RONet::addStoppingPlace(), NamedObjectCont< T >::get(), and RONet::myNodes.
Referenced by RONetHandler::parseEdge(), and RONetHandler::parseJunction().
getRestrictions()
const std::map< SUMOVehicleClass, double > * RONet::getRestrictions (const std::string & id) const inherited
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
Parameters
[in] id The id of the type
Returns
The mapping of vehicle classes to maximum speeds
Definition at line 127 of file RONet.cpp.
References RONet::myRestrictions.
Referenced by RONetHandler::parseEdge().
getRouteDef()
RORouteDef* RONet::getRouteDef (const std::string & name) const inline inherited
Returns the named route definition.
Parameters
[in] name The name of the route definition to retrieve
Returns
The named route definition if known, otherwise 0
Todo:
Check whether a const pointer may be returned
Rename myRoutes to myRouteDefinitions
Definition at line 301 of file RONet.h.
References RONet::addContainer(), RONet::addFlow(), RONet::addPerson(), RONet::addVehicle(), RONet::cleanup(), RONet::furtherStored(), NamedObjectCont< T >::get(), RONet::getEdgeNumber(), RONet::getInternalEdgeNumber(), RONet::myRoutes, RONet::openOutput(), RONet::saveAndRemoveRoutesUntil(), and RONet::writeIntermodal().
Referenced by RONet::adaptIntermodalRouter(), RORouteHandler::addWalk(), RONet::checkFlows(), RORouteHandler::closeFlow(), RORouteHandler::closeRoute(), RORouteHandler::closeVehicle(), RORouteHandler::openRoute(), and RORouteHandler::openRouteDistribution().
getRouteOutput()
OutputDevice* RONet::getRouteOutput (const bool alternative = false) inline inherited
Definition at line 410 of file RONet.h.
References RONet::checkFlows(), RONet::createBulkRouteRequests(), RONet::myRouteAlternativesOutput, RONet::myRoutesOutput, and RONet::operator=().
Referenced by computeRoutes().
getStoppingPlace()
const SUMOVehicleParameter::Stop* RONet::getStoppingPlace (const std::string & id, const SumoXMLTag category) const inline inherited
Retrieves a stopping place from the network.
Parameters
[in] id The name of the stop to retrieve
[in] category The type of stop
Returns
The named stop if known, otherwise 0
Definition at line 218 of file RONet.h.
References RONet::addRouteDef(), RONet::addVehicleType(), RONet::addVTypeDistribution(), RONet::checkVType(), RONet::getVehicleTypeSecure(), and RONet::myStoppingPlaces.
Referenced by RORouteHandler::addStop().
getVehicleTypeSecure()
SUMOVTypeParameter * RONet::getVehicleTypeSecure (const std::string & id) inherited
Retrieves the named vehicle type.
If the name is "" the default type is returned. If the named vehicle type (or typeDistribution) was not added to the net before 0 is returned
Parameters
[in] id The id of the vehicle type to return
Returns
The named vehicle type
Todo:
Check whether a const pointer may be returned
Definition at line 277 of file RONet.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, NamedObjectCont< T >::get(), RONet::myDefaultPedTypeMayBeDeleted, RONet::myDefaultVTypeMayBeDeleted, RONet::myVehicleTypes, and RONet::myVTypeDistDict.
Referenced by ROPerson::addTrip(), RONet::checkFlows(), RORouteHandler::closeFlow(), RORouteHandler::closeVehicle(), computeRoutes(), RONet::getStoppingPlace(), RORouteHandler::myStartElement(), RORouteHandler::openVehicleTypeDistribution(), and ROMAAssignments::ROMAAssignments().
hasApproached()
bool RODFNet::hasApproached (ROEdge * edge) const protected
Definition at line 653 of file RODFNet.cpp.
References myApproachedEdges.
Referenced by computeRoutesFor(), getAvgSpeedFactorLKW(), and isDestination().
hasApproaching()
bool RODFNet::hasApproaching (ROEdge * edge) const protected
Definition at line 644 of file RODFNet.cpp.
References myApproachingEdges.
Referenced by getAvgSpeedFactorLKW(), and isSource().
hasDetector()
bool RODFNet::hasDetector (ROEdge * edge) const
Definition at line 662 of file RODFNet.cpp.
References myDetectorsOnEdges.
Referenced by RODFDetector::buildDestinationDistribution(), computeRoutesFor(), RODFDetector::computeSplitProbabilities(), isDestination(), isFalseSource(), isSource(), and revalidateFlows().
hasInBetweenDetectorsOnly()
bool RODFNet::hasInBetweenDetectorsOnly (ROEdge * edge, const RODFDetectorCon & detectors) const protected
Definition at line 155 of file RODFNet.cpp.
References BETWEEN_DETECTOR, RODFDetectorCon::getDetector(), RODFDetector::getType(), and myDetectorsOnEdges.
Referenced by computeRoutesFor(), and getAvgSpeedFactorLKW().
hasPermissions()
bool RONet::hasPermissions () const inherited
Definition at line 688 of file RONet.cpp.
References RONet::myHavePermissions.
Referenced by computeRoutes(), and RONet::getEdgeMap().
hasSourceDetector()
bool RODFNet::hasSourceDetector (ROEdge * edge, const RODFDetectorCon & detectors) const protected
Definition at line 171 of file RODFNet.cpp.
References RODFDetectorCon::getDetector(), RODFDetector::getType(), myDetectorsOnEdges, and SOURCE_DETECTOR.
Referenced by computeRoutesFor(), and getAvgSpeedFactorLKW().
isDestination() [1/2]
bool RODFNet::isDestination (const RODFDetector & det, const RODFDetectorCon & detectors) const protected
Definition at line 700 of file RODFNet.cpp.
References getDetectorEdge().
Referenced by computeTypes(), getAvgSpeedFactorLKW(), and isDestination().
isDestination() [2/2]
bool RODFNet::isDestination (const RODFDetector & det, ROEdge * edge, ROEdgeVector & seen, const RODFDetectorCon & detectors) const protected
Definition at line 809 of file RODFNet.cpp.
References getAbsPos(), RODFDetectorCon::getDetector(), getDetectorEdge(), Named::getID(), ROEdge::getSpeedLimit(), hasApproached(), hasDetector(), isDestination(), myAmInHighwayMode, myApproachedEdges, myDetectorEdges, myDetectorsOnEdges, and WRITE_WARNING.
isFalseSource() [1/2]
bool RODFNet::isFalseSource (const RODFDetector & det, const RODFDetectorCon & detectors) const protected
Definition at line 693 of file RODFNet.cpp.
References getDetectorEdge().
Referenced by computeTypes(), getAvgSpeedFactorLKW(), and isFalseSource().
isFalseSource() [2/2]
bool RODFNet::isFalseSource (const RODFDetector & det, ROEdge * edge, ROEdgeVector & seen, const RODFDetectorCon & detectors) const protected
Definition at line 885 of file RODFNet.cpp.
References BETWEEN_DETECTOR, RODFDetectorCon::getDetector(), getDetectorEdge(), Named::getID(), ROEdge::getSpeedLimit(), RODFDetector::getType(), hasDetector(), isFalseSource(), myAmInHighwayMode, myApproachedEdges, myDetectorsOnEdges, SINK_DETECTOR, SOURCE_DETECTOR, and WRITE_WARNING.
isSource() [1/2]
bool RODFNet::isSource (const RODFDetector & det, const RODFDetectorCon & detectors, bool strict) const protected
Definition at line 685 of file RODFNet.cpp.
References getDetectorEdge().
Referenced by computeTypes(), getAvgSpeedFactorLKW(), and isSource().
isSource() [2/2]
bool RODFNet::isSource (const RODFDetector & det, ROEdge * edge, ROEdgeVector & seen, const RODFDetectorCon & detectors, bool strict) const protected
Definition at line 707 of file RODFNet.cpp.
References getAbsPos(), RODFDetectorCon::getDetector(), getDetectorEdge(), Named::getID(), ROEdge::getSpeedLimit(), hasApproaching(), hasDetector(), isSource(), myAmInHighwayMode, myApproachingEdges, myDetectorEdges, myDetectorsOnEdges, and WRITE_WARNING.
mesoJoin()
void RODFNet::mesoJoin (RODFDetectorCon & detectors, RODFDetectorFlows & flows)
Definition at line 1079 of file RODFNet.cpp.
References buildDetectorEdgeDependencies(), RODFDetectorCon::getDetector(), RODFDetector::getPos(), RODFDetectorFlows::mesoJoin(), RODFDetectorCon::mesoJoin(), and myDetectorsOnEdges.
openOutput()
void RONet::openOutput (const OptionsCont & options) inherited
Opens the output for computed routes.
If one of the file outputs can not be build, an IOError is thrown.
Parameters
[in] options The options to be asked for "output-file", "alternatives-output" and "vtype-output"
Definition at line 214 of file RONet.cpp.
References OptionsCont::exists(), OutputDevice::getDevice(), OptionsCont::getString(), OptionsCont::isSet(), RONet::myRouteAlternativesOutput, RONet::myRoutesOutput, RONet::myTypesOutput, SUMO_TAG_ROUTES, OutputDevice::writeAttr(), and OutputDevice::writeHeader().
Referenced by computeRoutes(), and RONet::getRouteDef().
removeEmptyDetectors()
void RODFNet::removeEmptyDetectors (RODFDetectorCon & detectors, RODFDetectorFlows & flows)
Definition at line 591 of file RODFNet.cpp.
References RODFDetectorCon::getDetectors(), RODFDetectorFlows::knows(), RODFDetectorCon::removeDetector(), RODFDetectorFlows::removeFlow(), and WRITE_MESSAGE.
Referenced by startComputation().
reportEmptyDetectors()
void RODFNet::reportEmptyDetectors (RODFDetectorCon & detectors, RODFDetectorFlows & flows)
Definition at line 614 of file RODFNet.cpp.
References RODFDetectorCon::getDetectors(), RODFDetectorFlows::knows(), and WRITE_MESSAGE.
Referenced by startComputation().
revalidateFlows() [1/2]
void RODFNet::revalidateFlows (const RODFDetectorCon & detectors, RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 577 of file RODFNet.cpp.
References RODFDetectorCon::getDetectors().
Referenced by getAvgSpeedFactorLKW(), and startComputation().
revalidateFlows() [2/2]
void RODFNet::revalidateFlows (const RODFDetector * detector, RODFDetectorFlows & flows, SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset) protected
Definition at line 429 of file RODFNet.cpp.
References RODFNet::IterationEdge::depth, RODFNet::IterationEdge::edge, getDetectorEdge(), RODFDetectorFlows::getFlowDefs(), RODFEdge::getFlows(), Named::getID(), hasDetector(), RODFDetectorFlows::knows(), myApproachedEdges, myApproachingEdges, FlowDef::qLKW, FlowDef::qPKW, RODFDetectorFlows::setFlows(), FlowDef::vLKW, FlowDef::vPKW, and WRITE_WARNING.
saveAndRemoveRoutesUntil()
SUMOTime RONet::saveAndRemoveRoutesUntil (OptionsCont & options, const RORouterProvider & provider, SUMOTime time) inherited
Computes routes described by their definitions and saves them.
As long as a vehicle with a departure time smaller than the given exists, its route is computed and it is written and removed from the internal container.
Parameters
[in] options The options used during this process
[in] provider The router provider for routes computation
[in] time The time until which route definitions shall be processed
Returns
The last seen departure time>=time
Definition at line 533 of file RONet.cpp.
References RONet::checkFlows(), RORoutable::computeRoute(), RONet::createBulkRouteRequests(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), Named::getID(), OptionsCont::getInt(), RouterProvider< E, L, N, V >::getIntermodalRouter(), ROVehicle::getRouteDefinition(), RORoutable::getRoutingSuccess(), MsgHandler::getWarningInstance(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::hasNet(), RORoutable::isPartOfFlow(), RORoutable::isPublicTransport(), MIN2(), RONet::myContainers, RONet::myDiscardedRouteNo, RONet::myErrorHandler, RONet::myRoutables, RONet::myRouteAlternativesOutput, RONet::myRoutes, RONet::myRoutesOutput, RONet::myTypesOutput, RONet::myVehIDs, RONet::myWrittenRouteNo, NamedObjectCont< T >::remove(), SUMOTime_MAX, toString(), RORoutable::write(), WRITE_MESSAGE, and OutputDevice::writePreformattedTag().
Referenced by RONet::getRouteDef(), and ROLoader::processRoutes().
setPermissionsFound()
void RONet::setPermissionsFound () inherited
Definition at line 694 of file RONet.cpp.
References RONet::myErrorHandler, and RONet::myHavePermissions.
Referenced by RONet::getEdgeMap(), and RONetHandler::parseLane().
writeIntermodal()
void RONet::writeIntermodal (const OptionsCont & options, ROIntermodalRouter & router) const inherited
Writes the intermodal network and weights if requested.
If one of the file outputs can not be build, an IOError is thrown.
Parameters
[in] options The options to be asked for "intermodal-network-output" and "intermodal-weight-output"
Definition at line 234 of file RONet.cpp.
References OutputDevice::closeTag(), OutputDevice::createDeviceByOption(), OptionsCont::exists(), OutputDevice::getDevice(), OutputDevice::getDeviceByOption(), OptionsCont::getString(), OptionsCont::isSet(), OutputDevice::openTag(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_TAG_INTERVAL, SUMOTime_MAX, OutputDevice::writeAttr(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::writeNetwork(), and IntermodalRouter< E, L, N, V, INTERNALROUTER >::writeWeights().
Referenced by computeRoutes(), and RONet::getRouteDef().
Field Documentation
myAmInHighwayMode
bool RODFNet::myAmInHighwayMode private
Definition at line 184 of file RODFNet.h.
Referenced by computeRoutesFor(), isDestination(), isFalseSource(), and isSource().
myApproachedEdges
std::map<ROEdge*, ROEdgeVector > RODFNet::myApproachedEdges private
Map of edge name->list of names of edges approached by this edge.
Definition at line 179 of file RODFNet.h.
Referenced by buildApproachList(), computeRoutesFor(), hasApproached(), isDestination(), isFalseSource(), and revalidateFlows().
myApproachingEdges
std::map<ROEdge*, ROEdgeVector > RODFNet::myApproachingEdges private
Map of edge name->list of names of this edge approaching edges.
Definition at line 176 of file RODFNet.h.
Referenced by buildApproachList(), hasApproaching(), isSource(), and revalidateFlows().
myAvgSpeedFactorLKW
double RODFNet::myAvgSpeedFactorLKW private
Definition at line 197 of file RODFNet.h.
Referenced by buildEdgeFlowMap(), and getAvgSpeedFactorLKW().
myAvgSpeedFactorPKW
double RODFNet::myAvgSpeedFactorPKW private
Definition at line 196 of file RODFNet.h.
Referenced by buildEdgeFlowMap(), and getAvgSpeedFactorPKW().
myDetectorEdges
std::map<std::string, ROEdge*> RODFNet::myDetectorEdges mutable private
Definition at line 182 of file RODFNet.h.
Referenced by buildDetectorDependencies(), buildDetectorEdgeDependencies(), isDestination(), and isSource().
myDetectorsOnEdges
std::map<ROEdge*, std::vector<std::string>, idComp> RODFNet::myDetectorsOnEdges mutable private
Definition at line 181 of file RODFNet.h.
Referenced by buildDetectorDependencies(), buildDetectorEdgeDependencies(), buildEdgeFlowMap(), buildRoutes(), getDetectorList(), hasDetector(), hasInBetweenDetectorsOnly(), hasSourceDetector(), isDestination(), isFalseSource(), isSource(), and mesoJoin().
myDisallowedEdges
std::vector<std::string> RODFNet::myDisallowedEdges private
List of ids of edges that shall not be used.
Definition at line 188 of file RODFNet.h.
Referenced by buildApproachList(), and RODFNet().
myInBetweenNumber
int RODFNet::myInBetweenNumber mutable private
Definition at line 185 of file RODFNet.h.
Referenced by computeTypes().
myInvalidNumber
int RODFNet::myInvalidNumber mutable private
Definition at line 185 of file RODFNet.h.
Referenced by computeTypes().
myKeepTurnarounds
bool RODFNet::myKeepTurnarounds private
Definition at line 191 of file RODFNet.h.
Referenced by buildApproachList(), and RODFNet().
myMaxSpeedFactorLKW
double RODFNet::myMaxSpeedFactorLKW private
Definition at line 195 of file RODFNet.h.
Referenced by buildEdgeFlowMap(), and getMaxSpeedFactorLKW().
myMaxSpeedFactorPKW
double RODFNet::myMaxSpeedFactorPKW private
maximum speed factor in measurements
Definition at line 194 of file RODFNet.h.
Referenced by buildEdgeFlowMap(), and getMaxSpeedFactorPKW().
mySinkNumber
int RODFNet::mySinkNumber mutable private
Definition at line 185 of file RODFNet.h.
Referenced by computeTypes().
mySourceNumber
int RODFNet::mySourceNumber mutable private
Definition at line 185 of file RODFNet.h.
Referenced by computeTypes().
The documentation for this class was generated from the following files:
RODFNet.h
RODFNet.cpp