SUMO - Simulation of Urban MObility: libsumo::Junction Class Reference
libsumo::Junction Class Reference
#include <Junction.h>
Static Public Member Functions
static TraCIColor getColor (const std::string &poiID)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static MSJunction * getJunction (const std::string &id)
static TraCIPosition getPosition (const std::string &junctionID)
static TraCIPositionVector getShape (const std::string &junctionID)
static NamedRTree * getTree ()
Returns a tree filled with junction instances.
static std::string getType (const std::string &poiID)
static void subscribe (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars)
static void subscribeContext (const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > &vars)
Private Member Functions
Junction ()
invalidated standard constructor
Junction (const Junction &src)
invalidated copy constructor
Junction & operator= (const Junction &src)
invalidated assignment operator
Detailed Description
Definition at line 52 of file Junction.h.
Constructor & Destructor Documentation
Junction() [1/2]
libsumo::Junction::Junction () private
invalidated standard constructor
Junction() [2/2]
libsumo::Junction::Junction (const Junction & src) private
invalidated copy constructor
Member Function Documentation
getColor()
static TraCIColor libsumo::Junction::getColor (const std::string & poiID) static
getIDCount()
int Junction::getIDCount () static
Definition at line 54 of file Junction.cpp.
References getIDList().
Referenced by TraCIServerAPI_Junction::processGet().
getIDList()
std::vector< std::string > Junction::getIDList () static
Definition at line 47 of file Junction.cpp.
References MSNet::getInstance(), MSNet::getJunctionControl(), and NamedObjectCont< T >::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Junction::processGet().
getJunction()
MSJunction * Junction::getJunction (const std::string & id) static
Definition at line 69 of file Junction.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), and MSNet::getJunctionControl().
Referenced by getPosition(), TraCIServerAPI_Junction::getPosition(), and getShape().
getPosition()
TraCIPosition Junction::getPosition (const std::string & junctionID) static
Definition at line 59 of file Junction.cpp.
References getJunction(), and libsumo::Helper::makeTraCIPosition().
Referenced by TraCIServerAPI_Junction::processGet().
getShape()
TraCIPositionVector Junction::getShape (const std::string & junctionID) static
Definition at line 64 of file Junction.cpp.
References getJunction(), and libsumo::Helper::makeTraCIPositionVector().
Referenced by TraCIServerAPI_Junction::processGet().
getTree()
NamedRTree * Junction::getTree () static
Returns a tree filled with junction instances.
Returns
The rtree of junctions
Definition at line 78 of file Junction.cpp.
References MSNet::getInstance(), NamedRTree::Insert(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
getType()
static std::string libsumo::Junction::getType (const std::string & poiID) static
operator=()
Junction& libsumo::Junction::operator= (const Junction & src) private
invalidated assignment operator
subscribe()
static void libsumo::Junction::subscribe (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) static
subscribeContext()
static void libsumo::Junction::subscribeContext (const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, double range, const std::vector< int > & vars) static
The documentation for this class was generated from the following files:
Junction.h
Junction.cpp