SUMO - Simulation of Urban MObility: GUIVisualizationSizeSettings Struct Reference
GUIVisualizationSizeSettings Struct Reference
#include <GUIVisualizationSettings.h>
Public Member Functions
double getExaggeration (const GUIVisualizationSettings &s, double factor=20) const
return the drawing size including exaggeration and constantSize values
GUIVisualizationSizeSettings (double _minSize, double _exaggeration=1.0, bool _constantSize=false)
bool operator!= (const GUIVisualizationSizeSettings &other)
bool operator== (const GUIVisualizationSizeSettings &other)
void print (OutputDevice &dev, const std::string &name) const
Data Fields
bool constantSize
double exaggeration
The size exaggeration (upscale)
double minSize
The minimum size to draw this object.
Detailed Description
Definition at line 81 of file GUIVisualizationSettings.h.
Constructor & Destructor Documentation
GUIVisualizationSizeSettings()
GUIVisualizationSizeSettings::GUIVisualizationSizeSettings (double _minSize, double _exaggeration = 1.0, bool _constantSize = false) inline
Definition at line 82 of file GUIVisualizationSettings.h.
Member Function Documentation
getExaggeration()
double GUIVisualizationSizeSettings::getExaggeration (const GUIVisualizationSettings & s, double factor = 20) const
return the drawing size including exaggeration and constantSize values
Note
should look normal-sized at zoom 1000
Definition at line 1160 of file GUIVisualizationSettings.cpp.
References GUIVisualizationSettings::drawForSelecting, MAX2(), and GUIVisualizationSettings::scale.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEPoly::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawOnPos(), GUIVehicle::drawRouteHelper(), GUIMEVehicle::drawRouteHelper(), and GUISUMOAbstractView::paintGLGrid().
operator!=()
bool GUIVisualizationSizeSettings::operator!= (const GUIVisualizationSizeSettings & other) inline
Definition at line 97 of file GUIVisualizationSettings.h.
operator==()
bool GUIVisualizationSizeSettings::operator== (const GUIVisualizationSizeSettings & other) inline
Definition at line 92 of file GUIVisualizationSettings.h.
References constantSize, exaggeration, and minSize.
print()
void GUIVisualizationSizeSettings::print (OutputDevice & dev, const std::string & name) const inline
Definition at line 101 of file GUIVisualizationSettings.h.
References OutputDevice::writeAttr().
Referenced by GUIVisualizationSettings::save().
Field Documentation
constantSize
bool GUIVisualizationSizeSettings::constantSize
Definition at line 90 of file GUIVisualizationSettings.h.
Referenced by operator==(), GUISettingsHandler::parseSizeSettings(), GUIDialog_ViewSettings::SizePanel::SizePanel(), and GUIDialog_ViewSettings::SizePanel::update().
exaggeration
double GUIVisualizationSizeSettings::exaggeration
The size exaggeration (upscale)
Definition at line 88 of file GUIVisualizationSettings.h.
Referenced by GNEEdge::commitShapeChange(), operator==(), GUISettingsHandler::parseSizeSettings(), GUIDialog_ViewSettings::SizePanel::SizePanel(), and GUIDialog_ViewSettings::SizePanel::update().
minSize
double GUIVisualizationSizeSettings::minSize
The minimum size to draw this object.
Definition at line 86 of file GUIVisualizationSettings.h.
Referenced by GUIPolygon::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GUIEdge::drawGL(), GUILane::drawGL(), GUICompleteSchemeStorage::init(), operator==(), GUISettingsHandler::parseSizeSettings(), GUIDialog_ViewSettings::SizePanel::SizePanel(), and GUIDialog_ViewSettings::SizePanel::update().
The documentation for this struct was generated from the following files:
GUIVisualizationSettings.h
GUIVisualizationSettings.cpp