SUMO - Simulation of Urban MObility: GNECrossingFrame Class Reference
GNECrossingFrame Class Reference
#include <GNECrossingFrame.h>
Data Structures
class crossingParameters
class edgesSelector
FOX-declaration.
Public Member Functions
bool addCrossing (GNENetElement *netElement)
add Crossing element
void focusUpperElement ()
focus upper element of frame
GNECrossingFrame::crossingParameters * getCrossingParameters () const
get Crossing parameters
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
GNECrossingFrame::edgesSelector * getEdgeSelector () const
get edge selector
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNECrossingFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
void hide ()
hide crossing frame
void removeCrossing (GNECrossing *Crossing)
remove an Crossing element previously added
void setCreateCrossingButton (bool value)
enable or disable button create edges
void setFrameWidth (int newWidth)
set width of GNEFrame
virtual void show ()
show Frame
~GNECrossingFrame ()
Destructor.
FOX-callbacks
Called when the user press the button create edge
long onCmdCreateCrossing (FXObject *, FXSelector, void *)
Static Public Member Functions
static std::string getIdsSelected (const FXList *list)
get list of selecte id's in string format
Protected Member Functions
GNECrossingFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Attributes
FXLabel * myColorCandidateLabel
Label for color candidate.
FXLabel * myColorSelectedLabel
Label for color selected.
FXButton * myCreateCrossingButton
FXButton for create Crossing
GNECrossingFrame::crossingParameters * myCrossingParameters
crossing parameters
FXLabel * myCurrentJunctionLabel
Label for current Junction.
GNECrossingFrame::edgesSelector * myEdgeSelector
edge selector
FXGroupBox * myGroupBoxButtons
groupbox for buttons
FXGroupBox * myGroupBoxLabel
groupbox for the junction label
FXGroupBox * myGroupBoxLegend
groupbox for Legend
Detailed Description
The Widget for setting internal attributes of Crossing elements
Definition at line 49 of file GNECrossingFrame.h.
Constructor & Destructor Documentation
GNECrossingFrame() [1/2]
GNECrossingFrame::GNECrossingFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 531 of file GNECrossingFrame.cpp.
References GNECrossingFrame::edgesSelector::disableEdgeSelector(), GNECrossingFrame::crossingParameters::getCandidateColor(), MFXUtils::getFXColor(), GNECrossingFrame::crossingParameters::getSelectedColor(), GUIDesignButton, GUIDesignGroupBoxFrame, GUIDesignLabelLeft, MID_GNE_CROSSINGFRAME_CREATECROSSING, myColorCandidateLabel, myColorSelectedLabel, GNEFrame::myContentFrame, myCreateCrossingButton, myCrossingParameters, myCurrentJunctionLabel, myEdgeSelector, myGroupBoxButtons, myGroupBoxLabel, and myGroupBoxLegend.
~GNECrossingFrame()
GNECrossingFrame::~GNECrossingFrame ()
Destructor.
Definition at line 560 of file GNECrossingFrame.cpp.
References gSelected, and GUISelectedStorage::remove2Update().
GNECrossingFrame() [2/2]
GNECrossingFrame::GNECrossingFrame () inline protected
FOX needs this.
Definition at line 279 of file GNECrossingFrame.h.
Member Function Documentation
addCrossing()
bool GNECrossingFrame::addCrossing (GNENetElement * netElement)
add Crossing element
Parameters
[in] netElement clicked netElement. if user didn't clicked over a GNENetElement in view, netElement will be NULL
Returns
true if a GNECrossing was added, false in other case
Definition at line 575 of file GNECrossingFrame.cpp.
References GNECrossingFrame::crossingParameters::clearEdges(), GNECrossingFrame::edgesSelector::disableEdgeSelector(), GNECrossingFrame::crossingParameters::enableCrossingParameters(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEAttributeCarrier::getID(), GNELane::getParentEdge(), GNECrossingFrame::crossingParameters::markEdge(), myCrossingParameters, myCurrentJunctionLabel, myEdgeSelector, and GNECrossingFrame::edgesSelector::restoreEdgeColors().
Referenced by GNEViewNet::onLeftBtnPress().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getCrossingParameters()
GNECrossingFrame::crossingParameters * GNECrossingFrame::getCrossingParameters () const
get Crossing parameters
Definition at line 647 of file GNECrossingFrame.cpp.
References myCrossingParameters.
Referenced by GNECrossingFrame::edgesSelector::disableEdgeSelector(), GNECrossingFrame::edgesSelector::onCmdClearSelection(), GNECrossingFrame::edgesSelector::onCmdInvertSelection(), and GNECrossingFrame::edgesSelector::onCmdUseSelectedEdges().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getEdgeSelector()
GNECrossingFrame::edgesSelector * GNECrossingFrame::getEdgeSelector () const
get edge selector
Definition at line 641 of file GNECrossingFrame.cpp.
References myEdgeSelector.
Referenced by GNECrossingFrame::crossingParameters::markEdge(), and GNECrossingFrame::crossingParameters::onCmdSetAttribute().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getIdsSelected()
static std::string GNECrossingFrame::getIdsSelected (const FXList * list) static
get list of selecte id's in string format
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
hide()
void GNECrossingFrame::hide () virtual
hide crossing frame
Reimplemented from GNEFrame.
Definition at line 566 of file GNECrossingFrame.cpp.
References GNEFrame::hide(), myEdgeSelector, and GNECrossingFrame::edgesSelector::restoreEdgeColors().
onCmdCreateCrossing()
long GNECrossingFrame::onCmdCreateCrossing (FXObject * , FXSelector , void *)
Definition at line 607 of file GNECrossingFrame.cpp.
References NBNode::checkCrossingDuplicated(), PositionVector::EMPTY, GNECrossingFrame::crossingParameters::getCrossingEdges(), GNECrossingFrame::crossingParameters::getCrossingPriority(), GNECrossingFrame::crossingParameters::getCrossingWidth(), GNECrossingFrame::edgesSelector::getCurrentJunction(), GNEJunction::getNBNode(), GNEViewNet::getUndoList(), GNECrossingFrame::crossingParameters::isCurrentParametersValid(), myCrossingParameters, myEdgeSelector, GNEFrame::myViewNet, GNECrossingFrame::edgesSelector::onCmdClearSelection(), and WRITE_WARNING.
Referenced by GNEViewNet::hotkeyEnter().
removeCrossing()
void GNECrossingFrame::removeCrossing (GNECrossing * Crossing)
remove an Crossing element previously added
Parameters
[in] Crossing element to erase
setCreateCrossingButton()
void GNECrossingFrame::setCreateCrossingButton (bool value)
enable or disable button create edges
Definition at line 631 of file GNECrossingFrame.cpp.
References myCreateCrossingButton.
Referenced by GNECrossingFrame::crossingParameters::disableCrossingParameters(), and GNECrossingFrame::crossingParameters::onCmdSetAttribute().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
show()
void GNEFrame::show () virtual inherited
show Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNEAdditionalFrame, GNEPolygonFrame, GNEInspectorFrame, and GNESelectorFrame.
Definition at line 546 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEFrame::myViewNet, and GNEViewParent::showFramesArea().
Referenced by GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::removeAttributeCarrier(), GNESelectorFrame::show(), GNEInspectorFrame::show(), GNEPolygonFrame::show(), GNEAdditionalFrame::show(), and GNEViewNet::updateModeSpecificControls().
Field Documentation
myColorCandidateLabel
FXLabel* GNECrossingFrame::myColorCandidateLabel private
Label for color candidate.
Definition at line 304 of file GNECrossingFrame.h.
Referenced by GNECrossingFrame().
myColorSelectedLabel
FXLabel* GNECrossingFrame::myColorSelectedLabel private
Label for color selected.
Definition at line 307 of file GNECrossingFrame.h.
Referenced by GNECrossingFrame().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myCreateCrossingButton
FXButton* GNECrossingFrame::myCreateCrossingButton private
FXButton for create Crossing
Definition at line 298 of file GNECrossingFrame.h.
Referenced by GNECrossingFrame(), and setCreateCrossingButton().
myCrossingParameters
GNECrossingFrame::crossingParameters* GNECrossingFrame::myCrossingParameters private
crossing parameters
Definition at line 286 of file GNECrossingFrame.h.
Referenced by addCrossing(), getCrossingParameters(), GNECrossingFrame(), and onCmdCreateCrossing().
myCurrentJunctionLabel
FXLabel* GNECrossingFrame::myCurrentJunctionLabel private
Label for current Junction.
Definition at line 292 of file GNECrossingFrame.h.
Referenced by addCrossing(), and GNECrossingFrame().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myEdgeSelector
GNECrossingFrame::edgesSelector* GNECrossingFrame::myEdgeSelector private
edge selector
Definition at line 283 of file GNECrossingFrame.h.
Referenced by addCrossing(), getEdgeSelector(), GNECrossingFrame(), hide(), and onCmdCreateCrossing().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxButtons
FXGroupBox* GNECrossingFrame::myGroupBoxButtons private
groupbox for buttons
Definition at line 295 of file GNECrossingFrame.h.
Referenced by GNECrossingFrame().
myGroupBoxLabel
FXGroupBox* GNECrossingFrame::myGroupBoxLabel private
groupbox for the junction label
Definition at line 289 of file GNECrossingFrame.h.
Referenced by GNECrossingFrame().
myGroupBoxLegend
FXGroupBox* GNECrossingFrame::myGroupBoxLegend private
groupbox for Legend
Definition at line 301 of file GNECrossingFrame.h.
Referenced by GNECrossingFrame().
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNECrossingFrame.h
GNECrossingFrame.cpp