SUMO - Simulation of Urban MObility: RONet Class Reference
RONet Class Reference
The router's network representation.
#include <RONet.h>
Public Types
typedef std::map< const SUMOTime, std::vector< RORoutable * > > RoutablesMap
Public Member Functions
void addRestriction (const std::string &id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
void cleanup ()
closes the file output for computed routes and deletes associated threads if necessary
const NamedObjectCont< ROEdge * > & getEdgeMap () const
int getEdgeNumber () const
Returns the total number of edges the network contains including internal edges.
int getInternalEdgeNumber () const
Returns the number of internal edges the network contains.
const std::map< SUMOVehicleClass, double > * getRestrictions (const std::string &id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
OutputDevice * getRouteOutput (const bool alternative=false)
bool hasPermissions () const
void openOutput (const OptionsCont &options)
Opens the output for computed routes.
RONet ()
Constructor.
void setPermissionsFound ()
void writeIntermodal (const OptionsCont &options, ROIntermodalRouter &router) const
Writes the intermodal network and weights if requested.
virtual ~RONet ()
Destructor.
Insertion and retrieval of graph parts
virtual bool addEdge (ROEdge *edge)
bool addDistrict (const std::string id, ROEdge *source, ROEdge *sink)
bool addDistrictEdge (const std::string tazID, const std::string edgeID, const bool isSource)
const std::map< std::string, std::pair< std::vector< std::string >, std::vector< std::string > > > & getDistricts () const
Retrieves all TAZ (districts) from the network.
ROEdge * getEdge (const std::string &name) const
Retrieves an edge from the network.
ROEdge * getEdgeForLaneID (const std::string &laneID) const
Retrieves an edge from the network when the lane id is given.
void addNode (RONode *node)
RONode * getNode (const std::string &id) const
Retrieves an node from the network.
void addStoppingPlace (const std::string &id, const SumoXMLTag category, SUMOVehicleParameter::Stop *stop)
const SUMOVehicleParameter::Stop * getStoppingPlace (const std::string &id, const SumoXMLTag category) const
Retrieves a stopping place from the network.
Insertion and retrieval of vehicle types, vehicles, routes, and route definitions
bool checkVType (const std::string &id)
Checks whether the vehicle type (distribution) may be added.
virtual bool addVehicleType (SUMOVTypeParameter *type)
Adds a read vehicle type definition to the network.
bool addVTypeDistribution (const std::string &id, RandomDistributor< SUMOVTypeParameter *> *vehTypeDistribution)
Adds a vehicle type distribution.
SUMOVTypeParameter * getVehicleTypeSecure (const std::string &id)
Retrieves the named vehicle type.
bool addRouteDef (RORouteDef *def)
RORouteDef * getRouteDef (const std::string &name) const
Returns the named route definition.
virtual bool addVehicle (const std::string &id, ROVehicle *veh)
bool addFlow (SUMOVehicleParameter *flow, const bool randomize)
bool addPerson (ROPerson *person)
void addContainer (const SUMOTime depart, const std::string desc)
Processing stored vehicle definitions
SUMOTime saveAndRemoveRoutesUntil (OptionsCont &options, const RORouterProvider &provider, SUMOTime time)
Computes routes described by their definitions and saves them.
virtual bool furtherStored ()
Returns the information whether further vehicles, persons or containers are stored.
Static Public Member Functions
static void adaptIntermodalRouter (ROIntermodalRouter &router)
static RONet * getInstance ()
Returns the pointer to the unique instance of RONet (singleton).
Private Types
typedef std::multimap< const SUMOTime, const std::string > ContainerMap
Known containers.
typedef std::map< std::string, RandomDistributor< SUMOVTypeParameter * > *> VTypeDistDictType
Vehicle type distribution dictionary type.
Private Member Functions
void checkFlows (SUMOTime time, MsgHandler *errorHandler, const bool keepPT)
void createBulkRouteRequests (const RORouterProvider &provider, const SUMOTime time, const bool removeLoops)
RONet & operator= (const RONet &src)
Invalidated assignment operator.
RONet (const RONet &src)
Invalidated copy constructor.
Private Attributes
ContainerMap myContainers
bool myDefaultPedTypeMayBeDeleted
Whether no pedestrian type has been loaded yet.
bool myDefaultVTypeMayBeDeleted
Whether no vehicle type has been loaded yet.
std::map< std::string, std::vector< SUMOTime > > myDepartures
Departure times for randomized flows.
int myDiscardedRouteNo
The number of discarded routes.
std::map< std::string, std::pair< std::vector< std::string >, std::vector< std::string > > > myDistricts
traffic assignment zones with sources and sinks
NamedObjectCont< ROEdge * > myEdges
Known edges.
MsgHandler * myErrorHandler
handler for ignorable error messages
NamedObjectCont< SUMOVehicleParameter * > myFlows
Known flows.
bool myHavePermissions
Whether the network contains edges which not all vehicles may pass.
const bool myKeepVTypeDist
whether to keep the the vtype distribution in output
NamedObjectCont< RONode * > myNodes
Known nodes.
int myNumInternalEdges
The number of internal edges in the dictionary.
std::set< std::string > myPersonIDs
Known person ids.
std::vector< const RORoutable * > myPTVehicles
vehicles to keep for public transport routing
int myReadRouteNo
The number of read routes.
std::map< std::string, std::map< SUMOVehicleClass, double > > myRestrictions
The vehicle class specific speed restrictions.
RoutablesMap myRoutables
Known routables.
OutputDevice * myRouteAlternativesOutput
The file to write the computed route alternatives into.
NamedObjectCont< RORouteDef * > myRoutes
Known routes.
OutputDevice * myRoutesOutput
The file to write the computed routes into.
std::map< SumoXMLTag, NamedObjectCont< SUMOVehicleParameter::Stop * > > myStoppingPlaces
Known bus / train / container stops and parking areas.
OutputDevice * myTypesOutput
The file to write the vehicle types into.
NamedObjectCont< SUMOVTypeParameter * > myVehicleTypes
Known vehicle types.
std::set< std::string > myVehIDs
Known vehicle ids.
VTypeDistDictType myVTypeDistDict
A distribution of vehicle types (probability->vehicle type)
int myWrittenRouteNo
The number of written routes.
Static Private Attributes
static RONet * myInstance = 0
Unique instance of RONet.
Detailed Description
The router's network representation.
A router network is responsible for watching loaded edges, nodes,!!!
Definition at line 74 of file RONet.h.
Member Typedef Documentation
ContainerMap
typedef std::multimap<const SUMOTime, const std::string> RONet::ContainerMap private
Known containers.
Definition at line 495 of file RONet.h.
RoutablesMap
typedef std::map<const SUMOTime, std::vector<RORoutable*> > RONet::RoutablesMap
Definition at line 77 of file RONet.h.
VTypeDistDictType
typedef std::map< std::string, RandomDistributor<SUMOVTypeParameter*>* > RONet::VTypeDistDictType private
Vehicle type distribution dictionary type.
Definition at line 475 of file RONet.h.
Constructor & Destructor Documentation
RONet() [1/2]
RONet::RONet ()
Constructor.
Definition at line 69 of file RONet.cpp.
References NamedObjectCont< T >::add(), DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, SUMOVTypeParameter::id, myInstance, myVehicleTypes, SUMOVTypeParameter::onlyReferenced, SUMOVTypeParameter::parametersSet, SVC_PASSENGER, SVC_PEDESTRIAN, and VTYPEPARS_VEHICLECLASS_SET.
~RONet()
RONet::~RONet () virtual
Destructor.
Definition at line 93 of file RONet.cpp.
References Named::getID(), ROVehicle::getRouteDefinition(), myPTVehicles, myRoutables, myRoutes, and NamedObjectCont< T >::remove().
RONet() [2/2]
RONet::RONet (const RONet & src) private
Invalidated copy constructor.
Member Function Documentation
adaptIntermodalRouter()
void RONet::adaptIntermodalRouter (ROIntermodalRouter & router) static
Definition at line 657 of file RONet.cpp.
References IntermodalRouter< E, L, N, V, INTERNALROUTER >::addAccess(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::addSchedule(), getEdgeForLaneID(), RORouteDef::getFirstRoute(), RORoutable::getParameter(), getRouteDef(), RORoute::getStops(), myFlows, myInstance, myPTVehicles, myStoppingPlaces, SUMO_TAG_BUS_STOP, and SUMO_TAG_PARKING_AREA.
Referenced by computeRoutes(), and getEdgeMap().
addContainer()
void RONet::addContainer (const SUMOTime depart, const std::string desc)
Definition at line 398 of file RONet.cpp.
References myContainers.
Referenced by RORouteHandler::closeContainer(), and getRouteDef().
addDistrict()
bool RONet::addDistrict (const std::string id, ROEdge * source, ROEdge * sink)
Definition at line 151 of file RONet.cpp.
References addEdge(), EDGEFUNC_CONNECTOR, myDistricts, ROEdge::setFunction(), and WRITE_ERROR.
Referenced by RONetHandler::parseDistrict().
addDistrictEdge()
bool RONet::addDistrictEdge (const std::string tazID, const std::string edgeID, const bool isSource)
Definition at line 168 of file RONet.cpp.
References ROEdge::addSuccessor(), getEdge(), myDistricts, and WRITE_ERROR.
Referenced by RONetHandler::parseDistrict(), and RONetHandler::parseDistrictEdge().
addEdge()
bool RONet::addEdge (ROEdge * edge) virtual
Definition at line 137 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), ROEdge::isInternal(), myEdges, myNumInternalEdges, and WRITE_ERROR.
Referenced by addDistrict(), and RONetHandler::parseEdge().
addFlow()
bool RONet::addFlow (SUMOVehicleParameter * flow, const bool randomize)
Definition at line 372 of file RONet.cpp.
References NamedObjectCont< T >::add(), SUMOVehicleParameter::depart, SUMOVehicleParameter::id, myDepartures, myFlows, RandHelper::rand(), SUMOVehicleParameter::repetitionNumber, and SUMOVehicleParameter::repetitionOffset.
Referenced by RORouteHandler::closeFlow(), and getRouteDef().
addNode()
void RONet::addNode (RONode * node)
Definition at line 190 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), myNodes, and WRITE_ERROR.
Referenced by getEdgeForLaneID(), and RONetHandler::parseEdge().
addPerson()
bool RONet::addPerson (ROPerson * person)
Definition at line 386 of file RONet.cpp.
References RORoutable::getDepart(), RORoutable::getID(), myPersonIDs, myRoutables, and WRITE_ERROR.
Referenced by RORouteHandler::closePerson(), and getRouteDef().
addRestriction()
void RONet::addRestriction (const std::string & id, const SUMOVehicleClass svc, const double speed)
Adds a restriction for an edge type.
Parameters
[in] id The id of the type
[in] svc The vehicle class the restriction refers to
[in] speed The restricted speed
Definition at line 121 of file RONet.cpp.
References myRestrictions.
Referenced by RONetHandler::myStartElement().
addRouteDef()
bool RONet::addRouteDef (RORouteDef * def)
Definition at line 208 of file RONet.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and myRoutes.
Referenced by RORouteHandler::closeRoute(), RORouteHandler::closeRouteDistribution(), and getStoppingPlace().
addStoppingPlace()
void RONet::addStoppingPlace (const std::string & id, const SumoXMLTag category, SUMOVehicleParameter::Stop * stop)
Definition at line 199 of file RONet.cpp.
References myStoppingPlaces, SUMO_TAG_BUS_STOP, SUMO_TAG_TRAIN_STOP, toString(), and WRITE_ERROR.
Referenced by getNode(), and RONetHandler::parseStoppingPlace().
addVehicle()
bool RONet::addVehicle (const std::string & id, ROVehicle * veh) virtual
Definition at line 352 of file RONet.cpp.
References RORoutable::getDepart(), OptionsCont::getOptions(), RORoutable::isPartOfFlow(), RORoutable::isPublicTransport(), myPTVehicles, myRoutables, myVehIDs, and WRITE_ERROR.
Referenced by checkFlows(), RORouteHandler::closeVehicle(), and getRouteDef().
addVehicleType()
bool RONet::addVehicleType (SUMOVTypeParameter * type) virtual
Adds a read vehicle type definition to the network.
If the vehicle type definition is already known (another one with the same id exists), false is returned, and the vehicle type is deleted.
Parameters
[in] def The vehicle type to add
Returns
Whether the vehicle type could be added
Definition at line 329 of file RONet.cpp.
References NamedObjectCont< T >::add(), checkVType(), SUMOVTypeParameter::id, myVehicleTypes, and WRITE_ERROR.
Referenced by getStoppingPlace(), and RORouteHandler::myEndElement().
addVTypeDistribution()
bool RONet::addVTypeDistribution (const std::string & id, RandomDistributor< SUMOVTypeParameter *> * vehTypeDistribution)
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns
Whether the vehicle type could be added
Definition at line 342 of file RONet.cpp.
References checkVType(), and myVTypeDistDict.
Referenced by RORouteHandler::closeVehicleTypeDistribution(), and getStoppingPlace().
checkFlows()
void RONet::checkFlows (SUMOTime time, MsgHandler * errorHandler, const bool keepPT) private
Definition at line 404 of file RONet.cpp.
References addVehicle(), RORouteDef::copy(), DEFAULT_VTYPE_ID, DELTA_T, SUMOVehicleParameter::depart, getRouteDef(), getVehicleTypeSecure(), SUMOVTypeParameter::id, SUMOVehicleParameter::id, SUMOVehicleParameter::line, myDepartures, myFlows, myKeepVTypeDist, RandHelper::rand(), SUMOVehicleParameter::repetitionEnd, SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, SUMOVehicleParameter::stops, toString(), TS, and SUMOVehicleParameter::vtypeid.
Referenced by getRouteOutput(), and saveAndRemoveRoutesUntil().
checkVType()
bool RONet::checkVType (const std::string & id)
Checks whether the vehicle type (distribution) may be added.
This method checks also whether the default type may still be replaced
Parameters
[in] id The id of the vehicle type (distribution) to add
Returns
Whether the type (distribution) may be added
Definition at line 304 of file RONet.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, NamedObjectCont< T >::get(), myDefaultPedTypeMayBeDeleted, myDefaultVTypeMayBeDeleted, myVehicleTypes, myVTypeDistDict, and NamedObjectCont< T >::remove().
Referenced by addVehicleType(), addVTypeDistribution(), and getStoppingPlace().
cleanup()
void RONet::cleanup ()
closes the file output for computed routes and deletes associated threads if necessary
Definition at line 253 of file RONet.cpp.
References RouteCostCalculator< R, E, V >::cleanup(), OutputDevice::close(), myRouteAlternativesOutput, myRoutesOutput, and myTypesOutput.
Referenced by computeRoutes(), and getRouteDef().
createBulkRouteRequests()
void RONet::createBulkRouteRequests (const RORouterProvider & provider, const SUMOTime time, const bool removeLoops) private
Definition at line 487 of file RONet.cpp.
References RORoutable::computeRoute(), RORoutable::getDepartEdge(), RORoutable::getID(), RORoutable::getMaxSpeed(), ROEdge::getNumericalID(), RORoutable::getVClass(), RouterProvider< E, L, N, V >::getVehicleRouter(), myErrorHandler, myRoutables, and WRITE_WARNING.
Referenced by getRouteOutput(), and saveAndRemoveRoutesUntil().
furtherStored()
bool RONet::furtherStored () virtual
Returns the information whether further vehicles, persons or containers are stored.
Definition at line 639 of file RONet.cpp.
References myContainers, myFlows, myRoutables, and NamedObjectCont< T >::size().
Referenced by getRouteDef(), ROLoader::openRoutes(), and ROLoader::processRoutes().
getDistricts()
const std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string> > >& RONet::getDistricts () const inline
Retrieves all TAZ (districts) from the network.
Returns
The map of all districts
Definition at line 151 of file RONet.h.
References myDistricts.
Referenced by main().
getEdge()
ROEdge* RONet::getEdge (const std::string & name) const inline
Retrieves an edge from the network.
This is not very pretty, but necessary, though, as routes run over instances, not over ids.
Parameters
[in] name The name of the edge to retrieve
Returns
The named edge if known, otherwise 0
Definition at line 163 of file RONet.h.
References NamedObjectCont< T >::get(), and myEdges.
Referenced by addDistrictEdge(), ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), RORouteHandler::addPersonTrip(), RORouteHandler::addStop(), ROJTRTurnDefLoader::addToEdge(), ROJTRTurnDefLoader::beginFromEdge(), RODFNet::getDetectorEdge(), getEdgeForLaneID(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), loadJTRDefinitions(), RODFDetectorHandler::myStartElement(), ROJTRTurnDefLoader::myStartElement(), RORouteHandler::myStartElement(), RONetHandler::parseConnection(), RORouteHandler::parseEdges(), RORouteHandler::parseFromViaTo(), AGActivityGenHandler::parseStreets(), ROVehicle::ROVehicle(), ROMAAssignments::sue(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
getEdgeForLaneID()
ROEdge* RONet::getEdgeForLaneID (const std::string & laneID) const inline
Retrieves an edge from the network when the lane id is given.
Parameters
[in] laneID The name of the lane to retrieve the edge for
Returns
The edge of the named lane if known, otherwise 0
Definition at line 173 of file RONet.h.
References addNode(), and getEdge().
Referenced by adaptIntermodalRouter(), ROVehicle::addStop(), RONetHandler::parseAccess(), and RONetHandler::parseStoppingPlace().
getEdgeMap()
const NamedObjectCont<ROEdge*>& RONet::getEdgeMap () const inline
Definition at line 400 of file RONet.h.
References adaptIntermodalRouter(), hasPermissions(), myEdges, and setPermissionsFound().
Referenced by RODFNet::buildApproachList(), AGCity::completeStreets(), ROMAAssignments::incremental(), initNet(), ROLoader::loadWeights(), ROMAAssignments::resetFlows(), ROMAAssignments::sue(), and writeInterval().
getEdgeNumber()
int RONet::getEdgeNumber () const
Returns the total number of edges the network contains including internal edges.
Definition at line 645 of file RONet.cpp.
References myEdges, and NamedObjectCont< T >::size().
Referenced by computeAllPairs(), computeRoutes(), getRouteDef(), and main().
getInstance()
RONet * RONet::getInstance (void) static
Returns the pointer to the unique instance of RONet (singleton).
Returns
Pointer to the unique RONet-instance
Definition at line 61 of file RONet.cpp.
References myInstance.
Referenced by ROPerson::addTrip(), and ROEdge::getSuccessors().
getInternalEdgeNumber()
int RONet::getInternalEdgeNumber () const
Returns the number of internal edges the network contains.
Definition at line 651 of file RONet.cpp.
References myNumInternalEdges.
Referenced by computeAllPairs(), and getRouteDef().
getNode()
RONode* RONet::getNode (const std::string & id) const inline
Retrieves an node from the network.
Parameters
[in] name The name of the node to retrieve
Returns
The named node if known, otherwise 0
Todo:
Check whether a const pointer may be returned
Definition at line 195 of file RONet.h.
References addStoppingPlace(), NamedObjectCont< T >::get(), and myNodes.
Referenced by RONetHandler::parseEdge(), and RONetHandler::parseJunction().
getRestrictions()
const std::map< SUMOVehicleClass, double > * RONet::getRestrictions (const std::string & id) const
Returns the restrictions for an edge type If no restrictions are present, 0 is returned.
Parameters
[in] id The id of the type
Returns
The mapping of vehicle classes to maximum speeds
Definition at line 127 of file RONet.cpp.
References myRestrictions.
Referenced by RONetHandler::parseEdge().
getRouteDef()
RORouteDef* RONet::getRouteDef (const std::string & name) const inline
Returns the named route definition.
Parameters
[in] name The name of the route definition to retrieve
Returns
The named route definition if known, otherwise 0
Todo:
Check whether a const pointer may be returned
Rename myRoutes to myRouteDefinitions
Definition at line 301 of file RONet.h.
References addContainer(), addFlow(), addPerson(), addVehicle(), cleanup(), furtherStored(), NamedObjectCont< T >::get(), getEdgeNumber(), getInternalEdgeNumber(), myRoutes, openOutput(), saveAndRemoveRoutesUntil(), and writeIntermodal().
Referenced by adaptIntermodalRouter(), RORouteHandler::addWalk(), checkFlows(), RORouteHandler::closeFlow(), RORouteHandler::closeRoute(), RORouteHandler::closeVehicle(), RORouteHandler::openRoute(), and RORouteHandler::openRouteDistribution().
getRouteOutput()
OutputDevice* RONet::getRouteOutput (const bool alternative = false) inline
Definition at line 410 of file RONet.h.
References checkFlows(), createBulkRouteRequests(), myRouteAlternativesOutput, myRoutesOutput, and operator=().
Referenced by computeRoutes().
getStoppingPlace()
const SUMOVehicleParameter::Stop* RONet::getStoppingPlace (const std::string & id, const SumoXMLTag category) const inline
Retrieves a stopping place from the network.
Parameters
[in] id The name of the stop to retrieve
[in] category The type of stop
Returns
The named stop if known, otherwise 0
Definition at line 218 of file RONet.h.
References addRouteDef(), addVehicleType(), addVTypeDistribution(), checkVType(), getVehicleTypeSecure(), and myStoppingPlaces.
Referenced by RORouteHandler::addStop().
getVehicleTypeSecure()
SUMOVTypeParameter * RONet::getVehicleTypeSecure (const std::string & id)
Retrieves the named vehicle type.
If the name is "" the default type is returned. If the named vehicle type (or typeDistribution) was not added to the net before 0 is returned
Parameters
[in] id The id of the vehicle type to return
Returns
The named vehicle type
Todo:
Check whether a const pointer may be returned
Definition at line 277 of file RONet.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, NamedObjectCont< T >::get(), myDefaultPedTypeMayBeDeleted, myDefaultVTypeMayBeDeleted, myVehicleTypes, and myVTypeDistDict.
Referenced by ROPerson::addTrip(), checkFlows(), RORouteHandler::closeFlow(), RORouteHandler::closeVehicle(), computeRoutes(), getStoppingPlace(), RORouteHandler::myStartElement(), RORouteHandler::openVehicleTypeDistribution(), and ROMAAssignments::ROMAAssignments().
hasPermissions()
bool RONet::hasPermissions () const
Definition at line 688 of file RONet.cpp.
References myHavePermissions.
Referenced by computeRoutes(), and getEdgeMap().
openOutput()
void RONet::openOutput (const OptionsCont & options)
Opens the output for computed routes.
If one of the file outputs can not be build, an IOError is thrown.
Parameters
[in] options The options to be asked for "output-file", "alternatives-output" and "vtype-output"
Definition at line 214 of file RONet.cpp.
References OptionsCont::exists(), OutputDevice::getDevice(), OptionsCont::getString(), OptionsCont::isSet(), myRouteAlternativesOutput, myRoutesOutput, myTypesOutput, SUMO_TAG_ROUTES, OutputDevice::writeAttr(), and OutputDevice::writeHeader().
Referenced by computeRoutes(), and getRouteDef().
operator=()
RONet& RONet::operator= (const RONet & src) private
Invalidated assignment operator.
Referenced by getRouteOutput().
saveAndRemoveRoutesUntil()
SUMOTime RONet::saveAndRemoveRoutesUntil (OptionsCont & options, const RORouterProvider & provider, SUMOTime time)
Computes routes described by their definitions and saves them.
As long as a vehicle with a departure time smaller than the given exists, its route is computed and it is written and removed from the internal container.
Parameters
[in] options The options used during this process
[in] provider The router provider for routes computation
[in] time The time until which route definitions shall be processed
Returns
The last seen departure time>=time
Definition at line 533 of file RONet.cpp.
References checkFlows(), RORoutable::computeRoute(), createBulkRouteRequests(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), Named::getID(), OptionsCont::getInt(), RouterProvider< E, L, N, V >::getIntermodalRouter(), ROVehicle::getRouteDefinition(), RORoutable::getRoutingSuccess(), MsgHandler::getWarningInstance(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::hasNet(), RORoutable::isPartOfFlow(), RORoutable::isPublicTransport(), MIN2(), myContainers, myDiscardedRouteNo, myErrorHandler, myRoutables, myRouteAlternativesOutput, myRoutes, myRoutesOutput, myTypesOutput, myVehIDs, myWrittenRouteNo, NamedObjectCont< T >::remove(), SUMOTime_MAX, toString(), RORoutable::write(), WRITE_MESSAGE, and OutputDevice::writePreformattedTag().
Referenced by getRouteDef(), and ROLoader::processRoutes().
setPermissionsFound()
void RONet::setPermissionsFound ()
Definition at line 694 of file RONet.cpp.
References myErrorHandler, and myHavePermissions.
Referenced by getEdgeMap(), and RONetHandler::parseLane().
writeIntermodal()
void RONet::writeIntermodal (const OptionsCont & options, ROIntermodalRouter & router) const
Writes the intermodal network and weights if requested.
If one of the file outputs can not be build, an IOError is thrown.
Parameters
[in] options The options to be asked for "intermodal-network-output" and "intermodal-weight-output"
Definition at line 234 of file RONet.cpp.
References OutputDevice::closeTag(), OutputDevice::createDeviceByOption(), OptionsCont::exists(), OutputDevice::getDevice(), OutputDevice::getDeviceByOption(), OptionsCont::getString(), OptionsCont::isSet(), OutputDevice::openTag(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_TAG_INTERVAL, SUMOTime_MAX, OutputDevice::writeAttr(), IntermodalRouter< E, L, N, V, INTERNALROUTER >::writeNetwork(), and IntermodalRouter< E, L, N, V, INTERNALROUTER >::writeWeights().
Referenced by computeRoutes(), and getRouteDef().
Field Documentation
myContainers
ContainerMap RONet::myContainers private
Definition at line 496 of file RONet.h.
Referenced by addContainer(), furtherStored(), and saveAndRemoveRoutesUntil().
myDefaultPedTypeMayBeDeleted
bool RONet::myDefaultPedTypeMayBeDeleted private
Whether no pedestrian type has been loaded yet.
Definition at line 483 of file RONet.h.
Referenced by checkVType(), and getVehicleTypeSecure().
myDefaultVTypeMayBeDeleted
bool RONet::myDefaultVTypeMayBeDeleted private
Whether no vehicle type has been loaded yet.
Definition at line 480 of file RONet.h.
Referenced by checkVType(), and getVehicleTypeSecure().
myDepartures
std::map<std::string, std::vector<SUMOTime> > RONet::myDepartures private
Departure times for randomized flows.
Definition at line 502 of file RONet.h.
Referenced by addFlow(), and checkFlows().
myDiscardedRouteNo
int RONet::myDiscardedRouteNo private
The number of discarded routes.
Definition at line 520 of file RONet.h.
Referenced by saveAndRemoveRoutesUntil().
myDistricts
std::map<std::string, std::pair<std::vector<std::string>, std::vector<std::string> > > RONet::myDistricts private
traffic assignment zones with sources and sinks
Definition at line 505 of file RONet.h.
Referenced by addDistrict(), addDistrictEdge(), and getDistricts().
myEdges
NamedObjectCont<ROEdge*> RONet::myEdges private
Known edges.
Definition at line 466 of file RONet.h.
Referenced by addEdge(), getEdge(), getEdgeMap(), and getEdgeNumber().
myErrorHandler
MsgHandler* RONet::myErrorHandler private
handler for ignorable error messages
Definition at line 535 of file RONet.h.
Referenced by createBulkRouteRequests(), saveAndRemoveRoutesUntil(), and setPermissionsFound().
myFlows
NamedObjectCont<SUMOVehicleParameter*> RONet::myFlows private
Known flows.
Definition at line 492 of file RONet.h.
Referenced by adaptIntermodalRouter(), addFlow(), checkFlows(), and furtherStored().
myHavePermissions
bool RONet::myHavePermissions private
Whether the network contains edges which not all vehicles may pass.
Definition at line 526 of file RONet.h.
Referenced by hasPermissions(), and setPermissionsFound().
myInstance
RONet * RONet::myInstance = 0 static private
Unique instance of RONet.
Definition at line 454 of file RONet.h.
Referenced by adaptIntermodalRouter(), getInstance(), and RONet().
myKeepVTypeDist
const bool RONet::myKeepVTypeDist private
whether to keep the the vtype distribution in output
Definition at line 538 of file RONet.h.
Referenced by checkFlows().
myNodes
NamedObjectCont<RONode*> RONet::myNodes private
Known nodes.
Definition at line 463 of file RONet.h.
Referenced by addNode(), and getNode().
myNumInternalEdges
int RONet::myNumInternalEdges private
The number of internal edges in the dictionary.
Definition at line 532 of file RONet.h.
Referenced by addEdge(), and getInternalEdgeNumber().
myPersonIDs
std::set<std::string> RONet::myPersonIDs private
Known person ids.
Definition at line 460 of file RONet.h.
Referenced by addPerson().
myPTVehicles
std::vector<const RORoutable*> RONet::myPTVehicles private
vehicles to keep for public transport routing
Definition at line 499 of file RONet.h.
Referenced by adaptIntermodalRouter(), addVehicle(), and ~RONet().
myReadRouteNo
int RONet::myReadRouteNo private
The number of read routes.
Definition at line 517 of file RONet.h.
myRestrictions
std::map<std::string, std::map<SUMOVehicleClass, double> > RONet::myRestrictions private
The vehicle class specific speed restrictions.
Definition at line 529 of file RONet.h.
Referenced by addRestriction(), and getRestrictions().
myRoutables
RoutablesMap RONet::myRoutables private
Known routables.
Definition at line 489 of file RONet.h.
Referenced by addPerson(), addVehicle(), createBulkRouteRequests(), furtherStored(), saveAndRemoveRoutesUntil(), and ~RONet().
myRouteAlternativesOutput
OutputDevice* RONet::myRouteAlternativesOutput private
The file to write the computed route alternatives into.
Definition at line 511 of file RONet.h.
Referenced by cleanup(), getRouteOutput(), openOutput(), and saveAndRemoveRoutesUntil().
myRoutes
NamedObjectCont<RORouteDef*> RONet::myRoutes private
Known routes.
Definition at line 486 of file RONet.h.
Referenced by addRouteDef(), getRouteDef(), saveAndRemoveRoutesUntil(), and ~RONet().
myRoutesOutput
OutputDevice* RONet::myRoutesOutput private
The file to write the computed routes into.
Definition at line 508 of file RONet.h.
Referenced by cleanup(), getRouteOutput(), openOutput(), and saveAndRemoveRoutesUntil().
myStoppingPlaces
std::map<SumoXMLTag, NamedObjectCont<SUMOVehicleParameter::Stop*> > RONet::myStoppingPlaces private
Known bus / train / container stops and parking areas.
Definition at line 469 of file RONet.h.
Referenced by adaptIntermodalRouter(), addStoppingPlace(), and getStoppingPlace().
myTypesOutput
OutputDevice* RONet::myTypesOutput private
The file to write the vehicle types into.
Definition at line 514 of file RONet.h.
Referenced by cleanup(), openOutput(), and saveAndRemoveRoutesUntil().
myVehicleTypes
NamedObjectCont<SUMOVTypeParameter*> RONet::myVehicleTypes private
Known vehicle types.
Definition at line 472 of file RONet.h.
Referenced by addVehicleType(), checkVType(), getVehicleTypeSecure(), and RONet().
myVehIDs
std::set<std::string> RONet::myVehIDs private
Known vehicle ids.
Definition at line 457 of file RONet.h.
Referenced by addVehicle(), and saveAndRemoveRoutesUntil().
myVTypeDistDict
VTypeDistDictType RONet::myVTypeDistDict private
A distribution of vehicle types (probability->vehicle type)
Definition at line 477 of file RONet.h.
Referenced by addVTypeDistribution(), checkVType(), and getVehicleTypeSecure().
myWrittenRouteNo
int RONet::myWrittenRouteNo private
The number of written routes.
Definition at line 523 of file RONet.h.
Referenced by saveAndRemoveRoutesUntil().
The documentation for this class was generated from the following files:
RONet.h
RONet.cpp