SUMO - Simulation of Urban MObility: GNEConnectorFrame Class Reference
GNEConnectorFrame Class Reference
#include <GNEConnectorFrame.h>
Public Member Functions
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNEConnectorFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
FOX-declaration.
void handleLaneClick (GNELane *lane, bool mayDefinitelyPass, bool allowConflict, bool toggle)
either sets the current lane or toggles the connection of the current lane to this lane (if they share a junction)
virtual void hide ()
hide Frame
void setFrameWidth (int newWidth)
set width of GNEFrame
virtual void show ()
show Frame
~GNEConnectorFrame ()
Destructor.
FOX-callbacks
Called when the user presses the OK-Button saves any connection modifications
long onCmdOK (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
Called when the user presses the Cancel-button discards any connection modifications.
long onCmdSelectDeadEnds (FXObject *, FXSelector, void *)
Called when the user presses the Corresponding-button.
long onCmdSelectDeadStarts (FXObject *, FXSelector, void *)
long onCmdSelectConflicts (FXObject *, FXSelector, void *)
long onCmdSelectPass (FXObject *, FXSelector, void *)
long onCmdClearSelectedConnections (FXObject *, FXSelector, void *)
long onCmdResetSelectedConnections (FXObject *, FXSelector, void *)
Protected Member Functions
GNEConnectorFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Types
enum LaneStatus { UNCONNECTED, CONNECTED, CONNECTED_PASS, CONFLICTED }
the status of a target lane
Private Member Functions
void cleanup ()
clean up when deselecting current lane
LaneStatus getLaneStatus (const std::vector< NBEdge::Connection > &connections, GNELane *targetLane)
return the status of toLane
void initTargets ()
init targets
void removeConnections (GNELane *lane)
remove connections
void updateDescription () const
update description
Private Attributes
FXButton * myCancelButton
"Cancel" button
FXButton * myClearSelectedButton
"Clear Selected"
FXLabel * myConflictLabel
conflict label
GNELane * myCurrentLane
the lane of which connections are to be modified
FXGroupBox * myGroupBoxDescription
Groupbox for description.
FXGroupBox * myGroupBoxLegend
group box for legend
FXGroupBox * myGroupBoxModifications
GroupBox for Buttons.
FXGroupBox * myGroupBoxOperations
groupbox for operations
FXGroupBox * myGroupBoxSelection
groupbox for selection hints
FXLabel * myHoldControlLabel
hold control label
FXLabel * myHoldShiftLabel
Selection Hint.
std::map< int, GNEInternalLane * > myInternalLanes
the internal lanes belonging the the current junction indexed by their tl-index
FXLabel * myLaneDescriptionLabel
the label that shows the current editing state
int myNumChanges
number of changes
FXLabel * myPossibleTargetLabel
possible target label
std::set< GNELane * > myPotentialTargets
the set of lanes to which the current lane may be connected
FXButton * myResetSelectedButton
"Reset Selected"
FXButton * mySaveButton
"OK" button
FXButton * mySelectConflictsButton
"Select Conflicts" button
FXButton * mySelectDeadEndsButton
"Select Dead Ends" button
FXButton * mySelectDeadStartsButton
"Select Dead Starts" button
FXButton * mySelectPassingButton
"Select Edges which may always pass"
FXLabel * mySourceLabel
source label
FXLabel * myTargetLabel
target label
FXLabel * myTargetPassLabel
target pass label
Static Private Attributes
static RGBColor conflictColor
color for a to-lane that cannot be used because another connection conflicts
static RGBColor potentialTargetColor
color for potential to-lane targets (currently unconnected)
static RGBColor sourceColor
color for the from-lane of a connection
static RGBColor targetColor
color for the to-lane of a connection
static RGBColor targetPassColor
color for the to-lane of a connection with pass attribute
Detailed Description
The Widget for modifying selections of network-elements
Definition at line 46 of file GNEConnectorFrame.h.
Member Enumeration Documentation
LaneStatus
enum GNEConnectorFrame::LaneStatus private
the status of a target lane
Enumerator
UNCONNECTED
CONNECTED
CONNECTED_PASS
CONFLICTED
Definition at line 92 of file GNEConnectorFrame.h.
Constructor & Destructor Documentation
GNEConnectorFrame() [1/2]
GNEConnectorFrame::GNEConnectorFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
FOX-declaration.
Constructor parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 84 of file GNEConnectorFrame.cpp.
References conflictColor, RGBColor::CYAN, MFXUtils::getFXColor(), GUIIconSubSys::getIcon(), RGBColor::GREEN, GUIDesignButton, GUIDesignGroupBoxFrame, GUIDesignLabelFrameInformation, GUIDesignLabelLeft, ICON_ACCEPT, ICON_CANCEL, RGBColor::MAGENTA, MID_CANCEL, MID_CHOOSEN_CLEAR, MID_CHOOSEN_RESET, MID_GNE_CONNECTORFRAME_SELECTCONFLICTS, MID_GNE_CONNECTORFRAME_SELECTDEADENDS, MID_GNE_CONNECTORFRAME_SELECTDEADSTARTS, MID_GNE_CONNECTORFRAME_SELECTPASS, MID_OK, myCancelButton, myClearSelectedButton, myConflictLabel, GNEFrame::myContentFrame, myGroupBoxDescription, myGroupBoxLegend, myGroupBoxModifications, myGroupBoxOperations, myGroupBoxSelection, myHoldControlLabel, myHoldShiftLabel, myLaneDescriptionLabel, myPossibleTargetLabel, myResetSelectedButton, mySaveButton, mySelectConflictsButton, mySelectDeadEndsButton, mySelectDeadStartsButton, mySelectPassingButton, mySourceLabel, myTargetLabel, myTargetPassLabel, potentialTargetColor, sourceColor, targetColor, targetPassColor, updateDescription(), and RGBColor::YELLOW.
~GNEConnectorFrame()
GNEConnectorFrame::~GNEConnectorFrame ()
Destructor.
Definition at line 166 of file GNEConnectorFrame.cpp.
GNEConnectorFrame() [2/2]
GNEConnectorFrame::GNEConnectorFrame () inline protected
FOX needs this.
Definition at line 87 of file GNEConnectorFrame.h.
Member Function Documentation
cleanup()
void GNEConnectorFrame::cleanup () private
clean up when deselecting current lane
Definition at line 465 of file GNEConnectorFrame.cpp.
References myCurrentLane, myNumChanges, myPotentialTargets, GNELane::setSpecialColor(), and updateDescription().
Referenced by onCmdCancel(), and onCmdOK().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getLaneStatus()
GNEConnectorFrame::LaneStatus GNEConnectorFrame::getLaneStatus (const std::vector< NBEdge::Connection > & connections, GNELane * targetLane) private
return the status of toLane
Definition at line 479 of file GNEConnectorFrame.cpp.
References CONFLICTED, CONNECTED, CONNECTED_PASS, GNELane::getIndex(), GNEEdge::getNBEdge(), GNELane::getParentEdge(), NBEdge::hasConnectionTo(), myCurrentLane, and UNCONNECTED.
Referenced by handleLaneClick(), and initTargets().
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
handleLaneClick()
void GNEConnectorFrame::handleLaneClick (GNELane * lane, bool mayDefinitelyPass, bool allowConflict, bool toggle)
either sets the current lane or toggles the connection of the current lane to this lane (if they share a junction)
Parameters
[in] lane Either the lane to set as current lane, or the destination from current lane
[in] mayDefinitelyPass Whether new connections shall have the pass attribute set
[in] toggle Whether non-existing connections shall be created
Definition at line 170 of file GNEConnectorFrame.cpp.
References CONFLICTED, CONNECTED, CONNECTED_PASS, GNENet::deleteConnection(), NBEdge::getConnectionsFromLane(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNELane::getIndex(), getLaneStatus(), GNEEdge::getNBEdge(), GNEViewNet::getNet(), GNELane::getParentEdge(), GNEViewNet::getUndoList(), initTargets(), GNEJunction::invalidateTLS(), myCurrentLane, myNumChanges, myPotentialTargets, GNEFrame::myViewNet, GNEUndoList::p_begin(), potentialTargetColor, GNEEdge::retrieveGNEConnection(), GNELane::setSpecialColor(), GNEViewNet::setStatusBarText(), sourceColor, SUMO_TAG_CONNECTION, SUMO_TAG_LANE, targetColor, targetPassColor, toString(), UNCONNECTED, and updateDescription().
Referenced by GNEViewNet::onLeftBtnPress(), and removeConnections().
hide()
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), and GNEDeleteFrame::removeAttributeCarrier().
initTargets()
void GNEConnectorFrame::initTargets () private
init targets
Definition at line 429 of file GNEConnectorFrame.cpp.
References conflictColor, CONFLICTED, CONNECTED, CONNECTED_PASS, NBEdge::getConnectionsFromLane(), GNEEdge::getGNEJunctionDestiny(), GNELane::getIndex(), GNEEdge::getLanes(), getLaneStatus(), GNEEdge::getNBEdge(), GNEJunction::getNBNode(), GNEViewNet::getNet(), NBNode::getOutgoingEdges(), GNELane::getParentEdge(), myCurrentLane, myPotentialTargets, GNEFrame::myViewNet, potentialTargetColor, GNENet::retrieveEdge(), targetColor, targetPassColor, and UNCONNECTED.
Referenced by handleLaneClick().
onCmdCancel()
long GNEConnectorFrame::onCmdCancel (FXObject * , FXSelector , void *)
Called when the user presses the Cancel-button discards any connection modifications.
Definition at line 222 of file GNEConnectorFrame.cpp.
References cleanup(), GNEViewNet::getUndoList(), myCurrentLane, myNumChanges, GNEFrame::myViewNet, GNEUndoList::p_abort(), and GNEViewNet::setStatusBarText().
Referenced by GNEViewNet::abortOperation(), onCmdClearSelectedConnections(), and onCmdResetSelectedConnections().
onCmdClearSelectedConnections()
long GNEConnectorFrame::onCmdClearSelectedConnections (FXObject * , FXSelector , void *)
Definition at line 352 of file GNEConnectorFrame.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUISelectedStorage::getSelected(), GUIGlObject::getType(), GNEViewNet::getUndoList(), GUIGlObjectStorage::gIDStorage, GLO_EDGE, GLO_JUNCTION, GLO_LANE, gSelected, GNEAttributeCarrier::MODIFIED, GNEFrame::myViewNet, onCmdCancel(), GNEUndoList::p_begin(), GNEUndoList::p_end(), removeConnections(), GNEJunction::setLogicValid(), SUMO_TAG_JUNCTION, and toString().
onCmdOK()
long GNEConnectorFrame::onCmdOK (FXObject * , FXSelector , void *)
Definition at line 236 of file GNEConnectorFrame.cpp.
References cleanup(), GNEViewNet::getUndoList(), myCurrentLane, myNumChanges, GNEFrame::myViewNet, GNEUndoList::p_end(), and GNEViewNet::setStatusBarText().
Referenced by GNEViewNet::hotkeyEnter(), and removeConnections().
onCmdResetSelectedConnections()
long GNEConnectorFrame::onCmdResetSelectedConnections (FXObject * , FXSelector , void *)
Definition at line 398 of file GNEConnectorFrame.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUISelectedStorage::getSelected(), GNEViewNet::getUndoList(), GUIGlObjectStorage::gIDStorage, GLO_JUNCTION, gSelected, GNEFrame::myViewNet, onCmdCancel(), GNEUndoList::p_begin(), GNEUndoList::p_end(), and GNEJunction::setLogicValid().
onCmdSelectConflicts()
long GNEConnectorFrame::onCmdSelectConflicts (FXObject * , FXSelector , void *)
Definition at line 304 of file GNEConnectorFrame.cpp.
References NBEdge::getConnectedEdges(), NBEdge::getConnections(), GNEEdge::getLanes(), GNEViewNet::getNet(), GNEViewParent::getSelectorFrame(), GNEViewNet::getViewParent(), GNESelectorFrame::handleIDs(), GNEFrame::myViewNet, GNENet::retrieveEdge(), GNENet::retrieveEdges(), and GNESelectorFrame::SET_REPLACE.
onCmdSelectDeadEnds()
long GNEConnectorFrame::onCmdSelectDeadEnds (FXObject * , FXSelector , void *)
Called when the user presses the Corresponding-button.
Definition at line 250 of file GNEConnectorFrame.cpp.
References GNEViewNet::getNet(), GNEViewParent::getSelectorFrame(), GNEViewNet::getViewParent(), GNESelectorFrame::handleIDs(), GNEFrame::myViewNet, GNENet::retrieveEdges(), and GNESelectorFrame::SET_REPLACE.
onCmdSelectDeadStarts()
long GNEConnectorFrame::onCmdSelectDeadStarts (FXObject * , FXSelector , void *)
Definition at line 268 of file GNEConnectorFrame.cpp.
References NBEdge::getConnections(), GUIGlObject::getGlID(), GNEEdge::getLaneGlIDs(), GNEEdge::getLanes(), GNEEdge::getNBEdge(), GNEViewNet::getNet(), GNEViewParent::getSelectorFrame(), GNEViewNet::getViewParent(), GNESelectorFrame::handleIDs(), GNEFrame::myViewNet, GNENet::retrieveEdge(), GNENet::retrieveJunctions(), and GNESelectorFrame::SET_REPLACE.
onCmdSelectPass()
long GNEConnectorFrame::onCmdSelectPass (FXObject * , FXSelector , void *)
Definition at line 332 of file GNEConnectorFrame.cpp.
References NBEdge::getConnections(), GUIGlObject::getGlID(), GNEEdge::getLanes(), GNEEdge::getNBEdge(), GNEViewNet::getNet(), GNEViewParent::getSelectorFrame(), GNEViewNet::getViewParent(), GNESelectorFrame::handleIDs(), GNEFrame::myViewNet, GNENet::retrieveEdges(), and GNESelectorFrame::SET_REPLACE.
removeConnections()
void GNEConnectorFrame::removeConnections (GNELane * lane) private
remove connections
Definition at line 388 of file GNEConnectorFrame.cpp.
References handleLaneClick(), myPotentialTargets, and onCmdOK().
Referenced by onCmdClearSelectedConnections().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
show()
void GNEFrame::show () virtual inherited
show Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNEAdditionalFrame, GNEPolygonFrame, GNEInspectorFrame, and GNESelectorFrame.
Definition at line 546 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEFrame::myViewNet, and GNEViewParent::showFramesArea().
Referenced by GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::removeAttributeCarrier(), GNESelectorFrame::show(), GNEInspectorFrame::show(), GNEPolygonFrame::show(), GNEAdditionalFrame::show(), and GNEViewNet::updateModeSpecificControls().
updateDescription()
void GNEConnectorFrame::updateDescription () const private
update description
Definition at line 419 of file GNEConnectorFrame.cpp.
References GUIGlObject::getMicrosimID(), myCurrentLane, myLaneDescriptionLabel, myNumChanges, and toString().
Referenced by cleanup(), GNEConnectorFrame(), and handleLaneClick().
Field Documentation
conflictColor
RGBColor GNEConnectorFrame::conflictColor static private
color for a to-lane that cannot be used because another connection conflicts
Definition at line 181 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame(), and initTargets().
myCancelButton
FXButton* GNEConnectorFrame::myCancelButton private
"Cancel" button
Definition at line 109 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myClearSelectedButton
FXButton* GNEConnectorFrame::myClearSelectedButton private
"Clear Selected"
Definition at line 130 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myConflictLabel
FXLabel* GNEConnectorFrame::myConflictLabel private
conflict label
Definition at line 160 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myCurrentLane
GNELane* GNEConnectorFrame::myCurrentLane private
the lane of which connections are to be modified
Definition at line 163 of file GNEConnectorFrame.h.
Referenced by cleanup(), getLaneStatus(), handleLaneClick(), initTargets(), onCmdCancel(), onCmdOK(), and updateDescription().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxDescription
FXGroupBox* GNEConnectorFrame::myGroupBoxDescription private
Groupbox for description.
Definition at line 100 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myGroupBoxLegend
FXGroupBox* GNEConnectorFrame::myGroupBoxLegend private
group box for legend
Definition at line 145 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myGroupBoxModifications
FXGroupBox* GNEConnectorFrame::myGroupBoxModifications private
GroupBox for Buttons.
Definition at line 106 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myGroupBoxOperations
FXGroupBox* GNEConnectorFrame::myGroupBoxOperations private
groupbox for operations
Definition at line 115 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myGroupBoxSelection
FXGroupBox* GNEConnectorFrame::myGroupBoxSelection private
groupbox for selection hints
Definition at line 136 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHoldControlLabel
FXLabel* GNEConnectorFrame::myHoldControlLabel private
hold control label
Definition at line 142 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myHoldShiftLabel
FXLabel* GNEConnectorFrame::myHoldShiftLabel private
Selection Hint.
Definition at line 139 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myInternalLanes
std::map<int, GNEInternalLane*> GNEConnectorFrame::myInternalLanes private
the internal lanes belonging the the current junction indexed by their tl-index
Definition at line 172 of file GNEConnectorFrame.h.
myLaneDescriptionLabel
FXLabel* GNEConnectorFrame::myLaneDescriptionLabel private
the label that shows the current editing state
Definition at line 103 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame(), and updateDescription().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myNumChanges
int GNEConnectorFrame::myNumChanges private
number of changes
Definition at line 169 of file GNEConnectorFrame.h.
Referenced by cleanup(), handleLaneClick(), onCmdCancel(), onCmdOK(), and updateDescription().
myPossibleTargetLabel
FXLabel* GNEConnectorFrame::myPossibleTargetLabel private
possible target label
Definition at line 154 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myPotentialTargets
std::set<GNELane*> GNEConnectorFrame::myPotentialTargets private
the set of lanes to which the current lane may be connected
Definition at line 166 of file GNEConnectorFrame.h.
Referenced by cleanup(), handleLaneClick(), initTargets(), and removeConnections().
myResetSelectedButton
FXButton* GNEConnectorFrame::myResetSelectedButton private
"Reset Selected"
Definition at line 133 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
mySaveButton
FXButton* GNEConnectorFrame::mySaveButton private
"OK" button
Definition at line 112 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
mySelectConflictsButton
FXButton* GNEConnectorFrame::mySelectConflictsButton private
"Select Conflicts" button
Definition at line 124 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
mySelectDeadEndsButton
FXButton* GNEConnectorFrame::mySelectDeadEndsButton private
"Select Dead Ends" button
Definition at line 118 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
mySelectDeadStartsButton
FXButton* GNEConnectorFrame::mySelectDeadStartsButton private
"Select Dead Starts" button
Definition at line 121 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
mySelectPassingButton
FXButton* GNEConnectorFrame::mySelectPassingButton private
"Select Edges which may always pass"
Definition at line 127 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
mySourceLabel
FXLabel* GNEConnectorFrame::mySourceLabel private
source label
Definition at line 148 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myTargetLabel
FXLabel* GNEConnectorFrame::myTargetLabel private
target label
Definition at line 151 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myTargetPassLabel
FXLabel* GNEConnectorFrame::myTargetPassLabel private
target pass label
Definition at line 157 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), initTargets(), onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), onCmdSelectConflicts(), onCmdSelectDeadEnds(), onCmdSelectDeadStarts(), onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
potentialTargetColor
RGBColor GNEConnectorFrame::potentialTargetColor static private
color for potential to-lane targets (currently unconnected)
Definition at line 187 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame(), handleLaneClick(), and initTargets().
sourceColor
RGBColor GNEConnectorFrame::sourceColor static private
color for the from-lane of a connection
Definition at line 175 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame(), and handleLaneClick().
targetColor
RGBColor GNEConnectorFrame::targetColor static private
color for the to-lane of a connection
Definition at line 178 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame(), handleLaneClick(), and initTargets().
targetPassColor
RGBColor GNEConnectorFrame::targetPassColor static private
color for the to-lane of a connection with pass attribute
Definition at line 184 of file GNEConnectorFrame.h.
Referenced by GNEConnectorFrame(), handleLaneClick(), and initTargets().
The documentation for this class was generated from the following files:
GNEConnectorFrame.h
GNEConnectorFrame.cpp