SUMO - Simulation of Urban MObility: jtrrouter_main.cpp File Reference
jtrrouter_main.cpp File Reference
#include <config.h>
#include <xercesc/sax/SAXException.hpp>
#include <xercesc/sax/SAXParseException.hpp>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <limits.h>
#include <ctime>
#include <set>
#include <utils/common/MsgHandler.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/ToString.h>
#include <utils/common/RandHelper.h>
#include <utils/common/StringTokenizer.h>
#include <utils/iodevices/OutputDevice.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/xml/XMLSubSys.h>
#include <router/ROFrame.h>
#include <router/ROLoader.h>
#include <router/RONet.h>
#include <router/RORouteDef.h>
#include "ROJTREdgeBuilder.h"
#include "ROJTRRouter.h"
#include "ROJTREdge.h"
#include "ROJTRTurnDefLoader.h"
#include "ROJTRFrame.h"
Functions
void computeRoutes (RONet &net, ROLoader &loader, OptionsCont &oc)
std::vector< double > getTurningDefaults (OptionsCont &oc)
void initNet (RONet &net, ROLoader &loader, const std::vector< double > &turnDefs)
void loadJTRDefinitions (RONet &net, OptionsCont &oc)
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Tue, 20 Jan 2004
Version
$Id$
Definition in file jtrrouter_main.cpp.
Function Documentation
computeRoutes()
void computeRoutes (RONet & net, ROLoader & loader, OptionsCont & oc)
Computes the routes saving them
Definition at line 141 of file jtrrouter_main.cpp.
References RONet::adaptIntermodalRouter(), RONet::cleanup(), OptionsCont::getBool(), RONet::getEdgeNumber(), OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), RONet::openOutput(), ROLoader::openRoutes(), ROLoader::processRoutes(), RORouteDef::setUsingJTRR(), and string2time().
Referenced by main().
getTurningDefaults()
std::vector<double> getTurningDefaults (OptionsCont & oc)
Definition at line 90 of file jtrrouter_main.cpp.
References TplConvert::_2double(), and OptionsCont::getStringVector().
Referenced by main().
initNet()
void initNet (RONet & net, ROLoader & loader, const std::vector< double > & turnDefs)
loads the net The net is in this meaning made up by the net itself and the dynamic weights which may be supplied in a separate file
Definition at line 78 of file jtrrouter_main.cpp.
References RONet::getEdgeMap(), and ROLoader::loadNet().
Referenced by main().
loadJTRDefinitions()
void loadJTRDefinitions (RONet & net, OptionsCont & oc)
Definition at line 109 of file jtrrouter_main.cpp.
References MsgHandler::clear(), OptionsCont::getBool(), RONet::getEdge(), MsgHandler::getErrorInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), XMLSubSys::runParser(), and ROEdge::setSink().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 163 of file jtrrouter_main.cpp.
References TplConvert::_2str(), ROJTRFrame::checkOptions(), SystemFrame::close(), computeRoutes(), ROJTRFrame::fillOptions(), OptionsCont::getBool(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), getTurningDefaults(), MsgHandler::inform(), XMLSubSys::init(), initNet(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), loadJTRDefinitions(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), toString(), VERSION_STRING, and WRITE_ERROR.