SUMO - Simulation of Urban MObility: PushButtonLogic Class Reference
PushButtonLogic Class Reference
#include <MSSOTLPolicy.h>
Protected Member Functions
void init (std::string prefix, const Parameterised *parameterised)
bool pushButtonLogic (SUMOTime elapsed, bool pushButtonPressed, const MSPhaseDefinition *stage)
Protected Attributes
std::string m_prefix
double m_pushButtonScaleFactor
Detailed Description
Definition at line 45 of file MSSOTLPolicy.h.
Member Function Documentation
init()
void PushButtonLogic::init (std::string prefix, const Parameterised * parameterised) protected
Definition at line 27 of file MSSOTLPolicy.cpp.
References TplConvert::_2double(), Parameterised::getParameter(), m_prefix, m_pushButtonScaleFactor, and WRITE_MESSAGE.
Referenced by MSSOTLPhasePolicy::init(), MSSOTLMarchingPolicy::init(), and MSSOTLPlatoonPolicy::init().
pushButtonLogic()
bool PushButtonLogic::pushButtonLogic (SUMOTime elapsed, bool pushButtonPressed, const MSPhaseDefinition * stage) protected
Definition at line 33 of file MSSOTLPolicy.cpp.
References MSPhaseDefinition::duration, m_prefix, m_pushButtonScaleFactor, and WRITE_MESSAGE.
Referenced by MSSOTLPhasePolicy::canRelease(), MSSOTLMarchingPolicy::canRelease(), and MSSOTLPlatoonPolicy::canRelease().
Field Documentation
m_prefix
std::string PushButtonLogic::m_prefix protected
Definition at line 52 of file MSSOTLPolicy.h.
Referenced by init(), SigmoidLogic::init(), pushButtonLogic(), and SigmoidLogic::sigmoidLogic().
m_pushButtonScaleFactor
double PushButtonLogic::m_pushButtonScaleFactor protected
Definition at line 51 of file MSSOTLPolicy.h.
Referenced by init(), and pushButtonLogic().
The documentation for this class was generated from the following files:
MSSOTLPolicy.h
MSSOTLPolicy.cpp