SUMO - Simulation of Urban MObility: MFXCheckableButton Class Reference
MFXCheckableButton Class Reference
#include <MFXCheckableButton.h>
Public Member Functions
bool amChecked () const
check if this MFXCheckableButton is checked
MFXCheckableButton (bool amChecked, FXComposite *p, const FXString &text, FXIcon *ic=NULL, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=BUTTON_NORMAL, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
fox declaration
void setChecked (bool val)
check or uncheck this MFXCheckableButton
~MFXCheckableButton ()
destructor (Called automatically)
FOX callbacks
called when this MFXCheckableButton is painted
long onPaint (FXObject *, FXSelector, void *)
long onUpdate (FXObject *, FXSelector, void *)
called when this MFXCheckableButton is updated
Protected Member Functions
MFXCheckableButton ()
fox need this
Private Member Functions
void buildColors ()
build color of this MFXCheckableButton
void setColors ()
set colors of this MFXCheckableButton
Private Attributes
bool myAmChecked
flag to indicate if this MFXCheckableButton is checked
bool myAmInitialised
check if this MFXCheckableButton is initialised
FXColor myBackColor
colors of this MFXCheckableButton
FXColor myDarkColor
FXColor myHiliteColor
FXColor myShadowColor
Detailed Description
Definition at line 37 of file MFXCheckableButton.h.
Constructor & Destructor Documentation
MFXCheckableButton() [1/2]
MFXCheckableButton::MFXCheckableButton (bool amChecked, FXComposite * p, const FXString & text, FXIcon * ic = NULL, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = BUTTON_NORMAL, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD)
fox declaration
constructor (Very similar to the FXButton constructor)
Definition at line 42 of file MFXCheckableButton.cpp.
~MFXCheckableButton()
MFXCheckableButton::~MFXCheckableButton ()
destructor (Called automatically)
Definition at line 54 of file MFXCheckableButton.cpp.
MFXCheckableButton() [2/2]
MFXCheckableButton::MFXCheckableButton () inline protected
fox need this
Definition at line 69 of file MFXCheckableButton.h.
References buildColors(), and setColors().
Member Function Documentation
amChecked()
bool MFXCheckableButton::amChecked () const
check if this MFXCheckableButton is checked
Definition at line 58 of file MFXCheckableButton.cpp.
References myAmChecked.
Referenced by GUISUMOViewParent::onCmdMakeSnapshot(), GUIGlChildWindow::onCmdShowToolTips(), and GUIGlChildWindow::onCmdZoomStyle().
buildColors()
void MFXCheckableButton::buildColors () private
build color of this MFXCheckableButton
Definition at line 91 of file MFXCheckableButton.cpp.
References myAmInitialised, myBackColor, myDarkColor, myHiliteColor, and myShadowColor.
Referenced by MFXCheckableButton(), onPaint(), and onUpdate().
onPaint()
long MFXCheckableButton::onPaint (FXObject * sender, FXSelector sel, void * data)
Definition at line 70 of file MFXCheckableButton.cpp.
References buildColors(), myAmInitialised, and setColors().
onUpdate()
long MFXCheckableButton::onUpdate (FXObject * sender, FXSelector sel, void * data)
called when this MFXCheckableButton is updated
Definition at line 80 of file MFXCheckableButton.cpp.
References buildColors(), myAmInitialised, and setColors().
setChecked()
void MFXCheckableButton::setChecked (bool val)
check or uncheck this MFXCheckableButton
Definition at line 64 of file MFXCheckableButton.cpp.
References myAmChecked.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), GUISUMOViewParent::onCmdMakeSnapshot(), GUIGlChildWindow::onCmdShowToolTips(), GUIGlChildWindow::onCmdZoomStyle(), and GNEViewNet::updateModeSpecificControls().
setColors()
void MFXCheckableButton::setColors () private
set colors of this MFXCheckableButton
Definition at line 101 of file MFXCheckableButton.cpp.
References myAmChecked, myBackColor, myDarkColor, myHiliteColor, and myShadowColor.
Referenced by MFXCheckableButton(), onPaint(), and onUpdate().
Field Documentation
myAmChecked
bool MFXCheckableButton::myAmChecked private
flag to indicate if this MFXCheckableButton is checked
Definition at line 80 of file MFXCheckableButton.h.
Referenced by amChecked(), setChecked(), and setColors().
myAmInitialised
bool MFXCheckableButton::myAmInitialised private
check if this MFXCheckableButton is initialised
Definition at line 89 of file MFXCheckableButton.h.
Referenced by buildColors(), onPaint(), and onUpdate().
myBackColor
FXColor MFXCheckableButton::myBackColor private
colors of this MFXCheckableButton
Definition at line 83 of file MFXCheckableButton.h.
Referenced by buildColors(), and setColors().
myDarkColor
FXColor MFXCheckableButton::myDarkColor private
Definition at line 83 of file MFXCheckableButton.h.
Referenced by buildColors(), and setColors().
myHiliteColor
FXColor MFXCheckableButton::myHiliteColor private
Definition at line 83 of file MFXCheckableButton.h.
Referenced by buildColors(), and setColors().
myShadowColor
FXColor MFXCheckableButton::myShadowColor private
Definition at line 83 of file MFXCheckableButton.h.
Referenced by buildColors(), and setColors().
The documentation for this class was generated from the following files:
MFXCheckableButton.h
MFXCheckableButton.cpp