SUMO - Simulation of Urban MObility: GUIDialog_Breakpoints Class Reference
GUIDialog_Breakpoints Class Reference
Editor for simulation breakpoints.
#include <GUIDialog_Breakpoints.h>
Public Member Functions
GUIDialog_Breakpoints (GUIMainWindow *parent, std::vector< SUMOTime > &breakpoints, FXMutex &breakpointLock)
Constructor.
void show ()
sets the focus after the window is created
~GUIDialog_Breakpoints ()
Destructor.
FOX-callbacks
long onCmdLoad (FXObject *, FXSelector, void *)
Called when the user presses the Load-button.
long onCmdSave (FXObject *, FXSelector, void *)
Called when the user presses the Save-button.
long onCmdClear (FXObject *, FXSelector, void *)
Called when the user presses the Clear-button.
long onCmdClose (FXObject *, FXSelector, void *)
Called when the user presses the Close-button.
long onCmdEditTable (FXObject *, FXSelector, void *)
Called when the table was changed.
Protected Member Functions
GUIDialog_Breakpoints ()
FOX needs this.
Private Member Functions
std::string encode2TXT ()
Builds a text representation of the items in the list.
void rebuildList ()
Rebuilds the entire list.
Private Attributes
FXMutex * myBreakpointLock
Lock for modifying the list of breakpoints.
std::vector< SUMOTime > * myBreakpoints
List of breakpoints.
GUIMainWindow * myParent
The parent window.
FXTable * myTable
The list that holds the ids.
Detailed Description
Editor for simulation breakpoints.
This dialog shows and lets the user edit the list of breakpoints - simulation time steps where the simulation halts.
Todo:
Use a LineReader instead of >> while reading
Definition at line 49 of file GUIDialog_Breakpoints.h.
Constructor & Destructor Documentation
GUIDialog_Breakpoints() [1/2]
GUIDialog_Breakpoints::GUIDialog_Breakpoints (GUIMainWindow * parent, std::vector< SUMOTime > & breakpoints, FXMutex & breakpointLock)
Constructor.
Parameters
[in] parent The parent window
Definition at line 74 of file GUIDialog_Breakpoints.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignButtonBreakpoint, GUIDesignHorizontalSeparator, GUIDesignTable, ICON_APP_BREAKPOINTS, MID_CANCEL, MID_CHOOSEN_CLEAR, MID_CHOOSEN_LOAD, MID_CHOOSEN_SAVE, and MID_TABLE.
~GUIDialog_Breakpoints()
GUIDialog_Breakpoints::~GUIDialog_Breakpoints ()
Destructor.
Definition at line 110 of file GUIDialog_Breakpoints.cpp.
References myParent, and GUIMainWindow::removeChild().
GUIDialog_Breakpoints() [2/2]
GUIDialog_Breakpoints::GUIDialog_Breakpoints () inline protected
FOX needs this.
Definition at line 114 of file GUIDialog_Breakpoints.h.
Member Function Documentation
encode2TXT()
std::string GUIDialog_Breakpoints::encode2TXT () private
Builds a text representation of the items in the list.
Returns
Breakpoints encoded as a string
Definition at line 181 of file GUIDialog_Breakpoints.cpp.
References myBreakpointLock, myBreakpoints, and time2string().
Referenced by onCmdSave().
onCmdClear()
long GUIDialog_Breakpoints::onCmdClear (FXObject * , FXSelector , void *)
Called when the user presses the Clear-button.
Definition at line 193 of file GUIDialog_Breakpoints.cpp.
References myBreakpointLock, myBreakpoints, and rebuildList().
onCmdClose()
long GUIDialog_Breakpoints::onCmdClose (FXObject * , FXSelector , void *)
Called when the user presses the Close-button.
Definition at line 203 of file GUIDialog_Breakpoints.cpp.
onCmdEditTable()
long GUIDialog_Breakpoints::onCmdEditTable (FXObject * , FXSelector , void * data)
Called when the table was changed.
Definition at line 210 of file GUIDialog_Breakpoints.cpp.
References myBreakpointLock, myBreakpoints, myTable, rebuildList(), and string2time().
onCmdLoad()
long GUIDialog_Breakpoints::onCmdLoad (FXObject * , FXSelector , void *)
Called when the user presses the Load-button.
Definition at line 142 of file GUIDialog_Breakpoints.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), ICON_EMPTY, GUISettingsHandler::loadBreakpoints(), myBreakpointLock, myBreakpoints, and rebuildList().
onCmdSave()
long GUIDialog_Breakpoints::onCmdSave (FXObject * , FXSelector , void *)
Called when the user presses the Save-button.
Definition at line 163 of file GUIDialog_Breakpoints.cpp.
References OutputDevice::close(), encode2TXT(), gCurrentFolder, OutputDevice::getDevice(), MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), and ICON_EMPTY.
rebuildList()
void GUIDialog_Breakpoints::rebuildList () private
Rebuilds the entire list.
Definition at line 123 of file GUIDialog_Breakpoints.cpp.
References myBreakpoints, myTable, and time2string().
Referenced by onCmdClear(), onCmdEditTable(), and onCmdLoad().
show()
void GUIDialog_Breakpoints::show ()
sets the focus after the window is created
Definition at line 116 of file GUIDialog_Breakpoints.cpp.
References myBreakpoints, and myTable.
Referenced by GUIApplicationWindow::onCmdEditBreakpoints().
Field Documentation
myBreakpointLock
FXMutex* GUIDialog_Breakpoints::myBreakpointLock private
Lock for modifying the list of breakpoints.
Definition at line 109 of file GUIDialog_Breakpoints.h.
Referenced by encode2TXT(), onCmdClear(), onCmdEditTable(), and onCmdLoad().
myBreakpoints
std::vector<SUMOTime>* GUIDialog_Breakpoints::myBreakpoints private
List of breakpoints.
Definition at line 106 of file GUIDialog_Breakpoints.h.
Referenced by encode2TXT(), onCmdClear(), onCmdEditTable(), onCmdLoad(), rebuildList(), and show().
myParent
GUIMainWindow* GUIDialog_Breakpoints::myParent private
The parent window.
Definition at line 103 of file GUIDialog_Breakpoints.h.
Referenced by ~GUIDialog_Breakpoints().
myTable
FXTable* GUIDialog_Breakpoints::myTable private
The list that holds the ids.
Definition at line 100 of file GUIDialog_Breakpoints.h.
Referenced by onCmdEditTable(), rebuildList(), and show().
The documentation for this class was generated from the following files:
GUIDialog_Breakpoints.h
GUIDialog_Breakpoints.cpp