SUMO - Simulation of Urban MObility: GNEAdditionalFrame::SelectorParentAdditional Class Reference
GNEAdditionalFrame::SelectorParentAdditional Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
std::string getIdSelected () const
get if currently additional Set
void hideListOfAdditionals ()
hide SelectorParentAdditional
SelectorParentAdditional (FXComposite *parent, GNEViewNet *viewNet)
FOX-declaration.
void showListOfAdditionals (SumoXMLTag type, bool uniqueSelection)
Show list of SelectorParentAdditional.
~SelectorParentAdditional ()
destructor
FOX-callbacks
called when user select an SelectorParentAdditional of the list
long onCmdSelectAdditionalParent (FXObject *, FXSelector, void *)
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
SelectorParentAdditional ()
FOX needs this.
Private Attributes
FXButton * myHelpAdditionalParentSelector
button for help
FXList * myList
List of additional sets.
FXLabel * mySetLabel
Label with the name of additional.
bool myUniqueSelection
flag to check if only a single parent is allowed
GNEViewNet * myViewNet
viewNet associated to GNEAdditionalFrame
Detailed Description
Definition at line 397 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
SelectorParentAdditional() [1/2]
GNEAdditionalFrame::SelectorParentAdditional::SelectorParentAdditional (FXComposite * parent, GNEViewNet * viewNet)
FOX-declaration.
constructor
Definition at line 1366 of file GNEAdditionalFrame.cpp.
References GUIDesignButtonRectangular, GUIDesignLabelLeftThick, GUIDesignList, hideListOfAdditionals(), MID_GNE_ADDITIONALFRAME_SELECTADDITIONALPARENT, MID_HELP, myHelpAdditionalParentSelector, myList, and mySetLabel.
~SelectorParentAdditional()
GNEAdditionalFrame::SelectorParentAdditional::~SelectorParentAdditional ()
destructor
Definition at line 1385 of file GNEAdditionalFrame.cpp.
SelectorParentAdditional() [2/2]
GNEAdditionalFrame::SelectorParentAdditional::SelectorParentAdditional () inline protected
FOX needs this.
Definition at line 428 of file GNEAdditionalFrame.h.
Member Function Documentation
getIdSelected()
std::string GNEAdditionalFrame::SelectorParentAdditional::getIdSelected () const
get if currently additional Set
Definition at line 1389 of file GNEAdditionalFrame.cpp.
References myList.
Referenced by GNEAdditionalFrame::addAdditional().
hideListOfAdditionals()
void GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals ()
hide SelectorParentAdditional
Definition at line 1415 of file GNEAdditionalFrame.cpp.
References GNEFrame::hide().
Referenced by SelectorParentAdditional(), and GNEAdditionalFrame::setParametersOfAdditional().
onCmdHelp()
long GNEAdditionalFrame::SelectorParentAdditional::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1427 of file GNEAdditionalFrame.cpp.
onCmdSelectAdditionalParent()
long GNEAdditionalFrame::SelectorParentAdditional::onCmdSelectAdditionalParent (FXObject * , FXSelector , void *)
Definition at line 1421 of file GNEAdditionalFrame.cpp.
showListOfAdditionals()
void GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals (SumoXMLTag type, bool uniqueSelection)
Show list of SelectorParentAdditional.
Definition at line 1400 of file GNEAdditionalFrame.cpp.
References GNENet::getAdditionals(), GNEViewNet::getNet(), myList, mySetLabel, myUniqueSelection, myViewNet, GNEAdditionalFrame::show(), and toString().
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
Field Documentation
myHelpAdditionalParentSelector
FXButton* GNEAdditionalFrame::SelectorParentAdditional::myHelpAdditionalParentSelector private
button for help
Definition at line 442 of file GNEAdditionalFrame.h.
Referenced by SelectorParentAdditional().
myList
FXList* GNEAdditionalFrame::SelectorParentAdditional::myList private
List of additional sets.
Definition at line 433 of file GNEAdditionalFrame.h.
Referenced by getIdSelected(), SelectorParentAdditional(), and showListOfAdditionals().
mySetLabel
FXLabel* GNEAdditionalFrame::SelectorParentAdditional::mySetLabel private
Label with the name of additional.
Definition at line 436 of file GNEAdditionalFrame.h.
Referenced by SelectorParentAdditional(), and showListOfAdditionals().
myUniqueSelection
bool GNEAdditionalFrame::SelectorParentAdditional::myUniqueSelection private
flag to check if only a single parent is allowed
Definition at line 439 of file GNEAdditionalFrame.h.
Referenced by showListOfAdditionals().
myViewNet
GNEViewNet* GNEAdditionalFrame::SelectorParentAdditional::myViewNet private
viewNet associated to GNEAdditionalFrame
Definition at line 445 of file GNEAdditionalFrame.h.
Referenced by showListOfAdditionals().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp