SUMO - Simulation of Urban MObility: GNEViewNet Class Reference
GNEViewNet Class Reference
#include <GNEViewNet.h>
Data Structures
struct movingEdges
Public Member Functions
void abortOperation (bool clearSelection=true)
abort current edition operation
void addDecals (const std::vector< Decal > &decals)
add decals
bool autoSelectNodes ()
whether to autoselect nodes or to lanes
void begingMoveSelection (GNEAttributeCarrier *originAC, const Position &originPosition)
begin move selection
void buildColorRainbow (GUIColorScheme &scheme, int active, GUIGlObjectType objectType)
recalibrate color scheme according to the current value range
virtual void buildViewToolBars (GUIGlChildWindow &)
builds the view toolbars
virtual void centerTo (GUIGlID id, bool applyZoom, double zoomDist=20)
centers to the chosen artifact
void centerTo (const Boundary &bound)
centers to the chosen artifact
bool changeAllPhases () const
change all phases
virtual void copyViewportTo (GUISUMOAbstractView *view)
copy the viewport to the given view
void destroyPopup ()
destoys the popup
void finishMoveSelection ()
finish moving selection
GUIPerspectiveChanger & getChanger () const
get changer
FXComboBox & getColoringSchemesCombo ()
get coloring schemes combo
EditMode getCurrentEditMode () const
get the current edit mode
double getDelay () const
Returns the delay of the parent application.
double getGridHeight () const
get grid Height
double getGridWidth () const
get grid width
GNENet * getNet () const
get the net object
const Position & getPopupPosition () const
get position of current popup
Position getPositionInformation () const
Returns the cursor's x/y position within the network.
virtual GUIGlID getTrackedID () const
get tracked id
GNEUndoList * getUndoList () const
get the undoList object
GNEViewParent * getViewParent () const
get the net object
GUIDialog_EditViewport * getViewportEditor ()
get the viewport and create it on first access
Boundary getVisibleBoundary () const
get visible boundary
GUIVisualizationSettings * getVisualisationSettings () const
get visualitation settings
GUIVisualizationSettings * getVisualisationSettings ()
get visualisation settings
GNEViewNet (FXComposite *tmpParent, FXComposite *actualParent, GUIMainWindow &app, GNEViewParent *viewParent, GNENet *net, GNEUndoList *undoList, FXGLVisual *glVis, FXGLCanvas *share, FXToolBar *toolBar)
FOX-declaration.
void hotkeyDel ()
handle del keypress
void hotkeyEnter ()
handle enter keypress
void hotkeyFocusFrame ()
handle focus frame keypress
bool isInEditMode ()
returns true, if the edit button was pressed
double m2p (double meter) const
meter-to-pixels conversion method
FXbool makeCurrent ()
A reimplementation due to some internal reasons.
void moveSelection (const Position &offset)
move selection
long onCmdAddRestrictedLaneBikelane (FXObject *, FXSelector typeOfTransformation, void *)
Add restricted lane for bikes.
long onCmdAddRestrictedLaneBuslane (FXObject *, FXSelector typeOfTransformation, void *)
Add restricted lane for buses.
long onCmdAddRestrictedLaneSidewalk (FXObject *, FXSelector typeOfTransformation, void *)
Add restricted lane for pedestrians.
long onCmdAddReversedEdge (FXObject *, FXSelector, void *)
add reversed edge
long onCmdClearConnections (FXObject *, FXSelector, void *)
clear junction connections
long onCmdClosePolygon (FXObject *, FXSelector, void *)
close opened polygon
long onCmdDeleteGeometryPoint (FXObject *, FXSelector, void *)
delete the closes geometry point
long onCmdDuplicateLane (FXObject *, FXSelector, void *)
duplicate selected lane
long onCmdEditConnectionShape (FXObject *, FXSelector, void *)
edit connection shape
long onCmdEditCrossingShape (FXObject *, FXSelector, void *)
edit crossing shape
long onCmdEditJunctionShape (FXObject *, FXSelector, void *)
edit junction shape
long onCmdOpenAdditionalDialog (FXObject *, FXSelector, void *)
open additional dialog
long onCmdOpenPolygon (FXObject *, FXSelector, void *)
open closed polygon
long onCmdRemoveRestrictedLaneBikelane (FXObject *, FXSelector typeOfTransformation, void *)
remove restricted lane for bikes
long onCmdRemoveRestrictedLaneBuslane (FXObject *, FXSelector typeOfTransformation, void *)
remove restricted lane for bus
long onCmdRemoveRestrictedLaneSidewalk (FXObject *, FXSelector typeOfTransformation, void *)
remove restricted lane for pedestrians
long onCmdReplaceJunction (FXObject *, FXSelector, void *)
replace node by geometry
long onCmdResetConnections (FXObject *, FXSelector, void *)
reset junction connections
long onCmdResetEdgeEndpoint (FXObject *, FXSelector, void *)
restore geometry endpoint to node position
long onCmdRestrictLaneBikelane (FXObject *, FXSelector typeOfTransformation, void *)
restrict lane to bikes
long onCmdRestrictLaneBuslane (FXObject *, FXSelector typeOfTransformation, void *)
restrict lane to buslanes
long onCmdRestrictLaneSidewalk (FXObject *, FXSelector typeOfTransformation, void *)
restrict lane to pedestrians
long onCmdReverseEdge (FXObject *, FXSelector, void *)
reverse edge
long onCmdSetEdgeEndpoint (FXObject *, FXSelector, void *)
set non-default geometry endpoint
long onCmdSetFirstGeometryPoint (FXObject *, FXSelector, void *)
set as first geometry point the closes geometry point
long onCmdShowGrid (FXObject *, FXSelector, void *)
toogle show grid
long onCmdSimplifyShape (FXObject *, FXSelector, void *)
simply shape of current polygon
long onCmdSmoothEdges (FXObject *, FXSelector, void *)
smooth geometry
long onCmdSmoothEdgesElevation (FXObject *, FXSelector, void *)
smooth elevation with regard to adjoining edges
long onCmdSplitEdge (FXObject *, FXSelector, void *)
split edge at cursor position
long onCmdSplitEdgeBidi (FXObject *, FXSelector, void *)
split edge at cursor position
long onCmdStraightenEdges (FXObject *, FXSelector, void *)
makes selected edges straight
long onCmdStraightenEdgesElevation (FXObject *, FXSelector, void *)
interpolate z values linear between junctions
long onCmdToogleSelectEdges (FXObject *, FXSelector, void *)
toogle selet edges
long onCmdToogleShowBubbles (FXObject *, FXSelector, void *)
toogle show bubbles
long onCmdToogleShowConnection (FXObject *, FXSelector, void *)
toogle show connections
long onCmdTransformPOI (FXObject *, FXSelector, void *)
Transform POI to POILane, and viceversa.
virtual void onGamingClick (Position)
on gaming click
virtual void openObjectDialog ()
double p2m (double pixel) const
pixels-to-meters conversion method
virtual void recenterView ()
recenters the view
void remove (GUIDialog_EditViewport *)
remove viewport
void remove (GUIDialog_ViewSettings *)
remove view settings
Position screenPos2NetPos (int x, int y) const
Translate screen position to network position.
bool selectEdges ()
whether inspection, selection and inversion should apply to edges or to lanes
void setApplicationSnapshots (std::set< SUMOTime > *snapshots, FXMutex *lock)
add snapshot synchronization
bool setColorScheme (const std::string &name)
set color scheme
void setDelay (double delay)
Sets the delay of the parent application.
void setEditModeFromHotkey (FXushort selid)
sets edit mode (from hotkey)
void setSelectionScaling (double selectionScale)
set selection scaling
void setStatusBarText (const std::string &text)
set staturBar text
virtual void setViewportFromTo (const Position &lookFrom, const Position &lookAt)
applies the given viewport settings
void setWindowCursorPosition (FXint x, FXint y)
Returns the information whether rotation is allowd.
bool showConnections ()
show connections over junctions
bool showJunctionAsBubbles () const
return true if junction must be showed as bubbles
bool showLockIcon () const
check if lock icon should be visible
void showToolTips (bool val)
show tool tips
virtual void showViewportEditor ()
show viewport editor
void showViewschemeEditor ()
show viewsscheme editor
Position snapToActiveGrid (const Position &pos) const
Returns a position that is mapped to the closest grid point if the grid is active.
void startEditCustomShape (GNENetElement *element, const PositionVector &shape, bool fill)
start edit custom shape
virtual void startTrack (int)
star track
void stopEditCustomShape ()
edit edit shape
virtual void stopTrack ()
stop track
void updateControls ()
update control contents after undo/redo or recompute
void updateToolTip ()
A method that updates the tooltip.
virtual ~GNEViewNet ()
destructor
overloaded handlers
called when user press mouse's left button
long onLeftBtnPress (FXObject *, FXSelector, void *)
long onLeftBtnRelease (FXObject *, FXSelector, void *)
called when user releases mouse's left button
long onRightBtnPress (FXObject *, FXSelector, void *)
called when user press mouse's right button
long onRightBtnRelease (FXObject *, FXSelector, void *)
called when user releases mouse's right button
long onMouseMove (FXObject *, FXSelector, void *)
called when user moves mouse
long onKeyPress (FXObject *o, FXSelector sel, void *data)
called when user press a key
long onKeyRelease (FXObject *o, FXSelector sel, void *data)
called when user release a key
set mode call backs
called when user press the button for create edge mode
long onCmdSetModeCreateEdge (FXObject *, FXSelector, void *)
long onCmdSetModeMove (FXObject *, FXSelector, void *)
called when user press the button for move mode
long onCmdSetModeDelete (FXObject *, FXSelector, void *)
called when user press the button for delete mode
long onCmdSetModeInspect (FXObject *, FXSelector, void *)
called when user press the button for inspect mode
long onCmdSetModeSelect (FXObject *, FXSelector, void *)
called when user press the button for select mode
long onCmdSetModeConnect (FXObject *, FXSelector, void *)
called when user press the button for connect mode
long onCmdSetModeTLS (FXObject *, FXSelector, void *)
called when user press the button for traffic lights mode
long onCmdSetModeAdditional (FXObject *, FXSelector, void *)
called when user press the button for additional mode
long onCmdSetModeCrossing (FXObject *, FXSelector, void *)
called when user press the button for crossing mode
long onCmdSetModePolygon (FXObject *, FXSelector, void *)
called when user press the button for polygon mode
virtual long onConfigure (FXObject *, FXSelector, void *)
mouse functions
virtual long onPaint (FXObject *, FXSelector, void *)
virtual long onMiddleBtnPress (FXObject *, FXSelector, void *)
virtual long onMiddleBtnRelease (FXObject *, FXSelector, void *)
virtual long onDoubleClicked (FXObject *, FXSelector, void *)
virtual long onMouseWheel (FXObject *, FXSelector, void *)
virtual long onMouseLeft (FXObject *, FXSelector, void *)
Dealing with snapshots
void addSnapshot (SUMOTime time, const std::string &file)
Sets the snapshot time to file map.
std::string makeSnapshot (const std::string &destFile)
Takes a snapshots and writes it into the given file.
virtual void saveFrame (const std::string &destFile, FXColor *buf)
Adds a frame to a video snapshot which will be initialized if neccessary.
virtual void endSnapshot ()
Ends a video snapshot.
virtual void checkSnapshots ()
Checks whether it is time for a snapshot.
virtual SUMOTime getCurrentTimeStep () const
get the current simulation time
Additional visualisations
bool addAdditionalGLVisualisation (const GUIGlObject *const which)
Adds an object to call its additional visualisation method.
bool removeAdditionalGLVisualisation (const GUIGlObject *const which)
Removes an object from the list of objects that show additional things.
bool isAdditionalGLVisualisationEnabled (GUIGlObject *const which) const
Check if an object is added in the additional GL visualitation.
Protected Member Functions
void applyGLTransform (bool fixRatio=true)
applies gl-transformations to fit the Boundary given by myChanger onto the canvas. If fixRatio is true, this boundary will be enlarged to prevent anisotropic stretching. (this should be set to false when doing selections)
FXImage * checkGDALImage (Decal &d)
check whether we can read image data or position with gdal
void displayLegend ()
a line with ticks, and the length information.
void doInit ()
called after some features are already initialized
int doPaintGL (int mode, const Boundary &bound)
do paintGL
void drawDecals ()
Draws the stored decals.
GUIGlID getObjectAtPosition (Position pos)
returns the id of the object at position using GL_SELECT
std::vector< GUIGlID > getObjectsAtPosition (Position pos, double radius)
returns the ids of the object at position within the given (rectangular) radius using GL_SELECT
std::vector< GUIGlID > getObjectsInBoundary (const Boundary &bound)
returns the ids of all objects in the given boundary
GUIGlID getObjectUnderCursor ()
returns the id of the object under the cursor using GL_SELECT
GNEViewNet ()
FOX needs this.
void paintGL ()
performs the painting of the simulation
void paintGLGrid ()
paints a grid
void showToolTipFor (const GUIGlID id)
invokes the tooltip for the given object
void updatePositionInformation () const
update position information
Protected Attributes
std::map< const GUIGlObject *, int > myAdditionallyDrawn
List of objects for which GUIGlObject::drawGLAdditional is called.
bool myAmInitialised
Internal information whether doInit() was called.
GUIMainWindow * myApp
The application.
std::set< SUMOTime > * myApplicationSnapshots
FXMutex * myApplicationSnapshotsLock
GUIPerspectiveChanger * myChanger
The perspective changer.
SUMORTree * myGrid
The visualization speed-up.
bool myInEditMode
Information whether too-tip informations shall be generated.
int myMouseHotspotX
Offset to the mouse-hotspot from the mouse position.
int myMouseHotspotY
GUIGlChildWindow * myParent
The parent window.
MFXMutex myPolyDrawLock
poly draw lock
GUIGLObjectPopupMenu * myPopup
The current popup-menu.
Position myPopupPosition
The current popup-menu position.
std::map< SUMOTime, std::vector< std::string > > mySnapshots
Snapshots.
MFXMutex mySnapshotsLock
The mutex to use before accessing the decals list in order to avoid thread conficts.
bool myUseToolTips
use tool tips
GUIDialog_EditViewport * myViewportChooser
viewport chooser
GUIDialog_ViewSettings * myVisualizationChanger
Visualization changer.
GUIVisualizationSettings * myVisualizationSettings
visualization settings
FXint myWindowCursorPositionX
Position of the cursor relative to the window.
FXint myWindowCursorPositionY
Optionally shown decals
The list of decals to show
std::vector< Decal > myDecals
MFXMutex myDecalsLock
The mutex to use before accessing the decals list in order to avoid thread conficts.
Private Member Functions
bool addRestrictedLane (SUMOVehicleClass vclass)
add restricted lane
void buildEditModeControls ()
adds controls for setting the edit mode
void deleteSelectedAdditionals ()
delete all currently selected additionals
void deleteSelectedConnections ()
delete all currently selected connections
void deleteSelectedCrossings ()
delete all currently selected crossings
void deleteSelectedEdges ()
delete all currently selected edges
void deleteSelectedJunctions ()
delete all currently selected junctions
void deleteSelectedLanes ()
delete all currently selected lanes
void deleteSelectedShapes (SumoXMLTag shapeTag=SUMO_TAG_NOTHING)
delete all currently selected shapes
GNEAdditional * getAdditionalAtPopupPosition ()
try to retrieve a additional at popup position
GNEConnection * getConnectionAtPopupPosition ()
try to retrieve a connection at popup position
GNECrossing * getCrossingAtPopupPosition ()
try to retrieve a crossing at popup position
GNEEdge * getEdgeAtPopupPosition ()
try to retrieve an edge at popup position
std::set< GNEEdge * > getEdgesAtPopupPosition ()
try to retrieve multiple edges at popup position
GNEJunction * getJunctionAtPopupPosition ()
try to retrieve a junction at popup position
GNELane * getLaneAtPopupPosition ()
try to retrieve a lane at popup position
GNEPOI * getPOIAtPopupPosition ()
try to retrieve a POILane at popup position
GNEPOILane * getPOILaneAtPopupPosition ()
try to retrieve a POILane at popup position
GNEPoly * getPolygonAtPopupPosition ()
try to retrieve a polygon at popup position
GNEViewNet (const GNEViewNet &)=delete
Invalidated copy constructor.
bool mergeJunctions (GNEJunction *moved, const Position &oldPos)
try to merge moved junction with another junction in that spot return true if merging did take place
GNEViewNet & operator= (const GNEViewNet &)=delete
Invalidated assignment operator.
void processClick (FXEvent *e, void *data)
Auxiliar function used by onLeftBtnPress(...)
bool removeRestrictedLane (SUMOVehicleClass vclass)
remove restricted lane
bool restrictLane (SUMOVehicleClass vclass)
restrict lane
void setEditMode (EditMode mode)
set edit mode
void updateModeSpecificControls ()
updates mode specific controls
Private Attributes
GNEFrame * myCurrentFrame
the current frame
EditMode myEditMode
the current edit mode
FXMenuCheck * myMenuCheckChangeAllPhases
menu check to set change all phases
FXMenuCheck * myMenuCheckExtendToEdgeNodes
menu check to extend to edge nodes
FXMenuCheck * myMenuCheckSelectEdges
menu check to select only edges
FXMenuCheck * myMenuCheckShowConnections
menu check to show connections
FXMenuCheck * myMenuCheckShowGrid
show grid button
GNENet * myNet
Pointer to current net. (We are not responsible for deletion)
bool mySelectEdges
flag to check if select edges is enabled
bool myShowConnections
whether show connections has been activated once
FXToolBar * myToolbar
a reference to the toolbar in myParent
GNEUndoList * myUndoList
a reference to the undolist maintained in the application
GNEViewParent * myViewParent
view parent
the state-variables of the create-edge state-machine
GNEJunction * myCreateEdgeSource
source junction for new edge 0 if no edge source is selected an existing (or newly created) junction otherwise
FXMenuCheck * myChainCreateEdge
whether the endpoint for a created edge should be set as the new source
FXMenuCheck * myAutoCreateOppositeEdge
the state-variables of the move state-machine
FXMenuCheck * myMenuCheckWarnAboutMerge
whether we should warn about merging junctions
FXMenuCheck * myMenuCheckShowBubbleOverJunction
show connection as buuble in "Move" mode.
FXMenuCheck * myMenuCheckMoveElevation
apply movement to elevation
Variables for move elements
GNEJunction * myJunctionToMove
the Junction to be moved.
GNEEdge * myEdgeToMove
the edge of which geometry is being moved
GNEEdge * myOppositeEdgeToMove
the edge of which geometry is being moved
GNEPoly * myPolyToMove
the poly of which geometry is being moved
GNEPOI * myPoiToMove
the poi which is being moved
GNEPOILane * myPoiLaneToMove
the poiLane which is being moved
GNEAdditional * myAdditionalToMove
the stoppingPlace element which shape is being moved
Position myMovingReference
variable for calculating moving offset (Used when user doesn't click exactly over the center of shape)
Position myMovingOriginalPosition
original Position of element before moving (needed for commmit position changes)
PositionVector myMovingOriginalShape
Shape of elements before moving (needed for commmit shape changes)
PositionVector myMovingOriginalShape2
int myMovingIndexShape
current index of shape that are being moved
Position myMovingOriginalPositionOppositeEdge
PositionVector myMovingOriginalShapenOppositeEdge
bool myMovingSelection
whether a selection is being moved
std::map< GNEJunction *, Position > myOriginPositionOfMovedJunctions
Selected Junctions that are being moved.
std::map< GNEEdge *, PositionVector > myOriginShapesMovedEntireShapes
Selected Edges that are being moved < Edge, PositionVector >
std::map< GNEEdge *, movingEdges > myOriginShapesMovedPartialShapes
state-variables of inspect-mode and select-mode
bool myAmInRectSelect
whether we have started rectangle-selection
Position mySelCorner1
firstcorner of the rectangle-selection
Position mySelCorner2
second corner of the rectangle-selection
buttons for selecting the edit mode
chekable button for edit mode create edge
MFXCheckableButton * myEditModeCreateEdge
MFXCheckableButton * myEditModeMove
chekable button for edit mode move
MFXCheckableButton * myEditModeDelete
chekable button for edit mode delete
MFXCheckableButton * myEditModeInspect
chekable button for edit mode inspect
MFXCheckableButton * myEditModeSelect
chekable button for edit mode select
MFXCheckableButton * myEditModeConnection
chekable button for edit mode connection
MFXCheckableButton * myEditModeTrafficLight
chekable button for edit mode traffic light
MFXCheckableButton * myEditModeAdditional
chekable button for edit mode additional
MFXCheckableButton * myEditModeCrossing
chekable button for edit mode crossing
MFXCheckableButton * myEditModePolygon
chekable button for edit mode polygon
StringBijection< EditMode > myEditModeNames
since we cannot switch on strings we map the mode names to an enum
StringBijection< EditMode > myEditAdditionalModeNames
stringBijection for edit additional mode names
variables for edit shapes
polygon used for edit shapes
GNEPoly * myEditShapePoly
EditMode myPreviousEditMode
the previous edit mode before edit junction's shapes
variables for testing mode
flag to enable or disable testing mode
bool myTestingMode
int myTestingWidth
Width of viewNet in testing mode.
int myTestingHeight
Height of viewNet in testing mode.
Detailed Description
Microsocopic view at the simulation
Definition at line 97 of file GNEViewNet.h.
Constructor & Destructor Documentation
GNEViewNet() [1/3]
GNEViewNet::GNEViewNet (FXComposite * tmpParent, FXComposite * actualParent, GUIMainWindow & app, GNEViewParent * viewParent, GNENet * net, GNEUndoList * undoList, FXGLVisual * glVis, FXGLCanvas * share, FXToolBar * toolBar)
FOX-declaration.
Definition at line 155 of file GNEViewNet.cpp.
References OptionsCont::getOptions(), OptionsCont::getStringVector(), toString(), and WRITE_ERROR.
~GNEViewNet()
GNEViewNet::~GNEViewNet () virtual
destructor
Definition at line 212 of file GNEViewNet.cpp.
GNEViewNet() [2/3]
GNEViewNet::GNEViewNet () inline protected
FOX needs this.
Definition at line 370 of file GNEViewNet.h.
References doInit(), and doPaintGL().
GNEViewNet() [3/3]
GNEViewNet::GNEViewNet (const GNEViewNet &) private delete
Invalidated copy constructor.
Member Function Documentation
abortOperation()
void GNEViewNet::abortOperation (bool clearSelection = true)
abort current edition operation
Definition at line 1143 of file GNEViewNet.cpp.
References GNEFrame::DrawingMode::abortDrawing(), GUISelectedStorage::clear(), GNEViewParent::getConnectorFrame(), GNEFrame::getDrawingMode(), GNEViewParent::getPolygonFrame(), GNEViewParent::getTLSEditorFrame(), GNE_MODE_CONNECT, GNE_MODE_MOVE, GNE_MODE_POLYGON, GNE_MODE_SELECT, GNE_MODE_TLS, gSelected, myAmInRectSelect, myCreateEdgeSource, myEditMode, myUndoList, myViewParent, GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEUndoList::p_abort(), stopEditCustomShape(), and GNEJunction::unMarkAsCreateEdgeSource().
Referenced by GNEApplicationWindow::onCmdAbort(), and setEditMode().
addAdditionalGLVisualisation()
bool GUISUMOAbstractView::addAdditionalGLVisualisation (const GUIGlObject *const which) inherited
Adds an object to call its additional visualisation method.
Parameters
[in] which The object to add
Returns
Always true
See also
GUIGlObject::drawGLAdditional
Definition at line 1281 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myAdditionallyDrawn.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), GUIPerson::addActiveAddVisualisation(), GUISUMOAbstractView::buildColorRainbow(), and GUIVehicle::drawOutsideNetwork().
addDecals()
void GUISUMOAbstractView::addDecals (const std::vector< Decal > & decals) inherited
add decals
Definition at line 215 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myDecals.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
addRestrictedLane()
bool GNEViewNet::addRestrictedLane (SUMOVehicleClass vclass) private
add restricted lane
Definition at line 2014 of file GNEViewNet.cpp.
References GNENet::addSRestrictedLane(), OptionsCont::getBool(), getLaneAtPopupPosition(), OptionsCont::getOptions(), GNELane::getParentEdge(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdge(), GNENet::retrieveEdges(), GNENet::retrieveLanes(), toString(), and WRITE_WARNING.
Referenced by onCmdAddRestrictedLaneBikelane(), onCmdAddRestrictedLaneBuslane(), and onCmdAddRestrictedLaneSidewalk().
addSnapshot()
void GUISUMOAbstractView::addSnapshot (SUMOTime time, const std::string & file) inherited
Sets the snapshot time to file map.
Parameters
[in] snaps The snapshots to take at certain times
Definition at line 825 of file GUISUMOAbstractView.cpp.
References MFXMutex::lock(), GUISUMOAbstractView::myApplicationSnapshots, GUISUMOAbstractView::myApplicationSnapshotsLock, GUISUMOAbstractView::mySnapshots, GUISUMOAbstractView::mySnapshotsLock, and MFXMutex::unlock().
Referenced by GUISUMOAbstractView::buildViewToolBars(), TraCIServerAPI_GUI::processSet(), and GUISettingsHandler::setSnapshots().
applyGLTransform()
void GUISUMOAbstractView::applyGLTransform (bool fixRatio = true) protected inherited
applies gl-transformations to fit the Boundary given by myChanger onto the canvas. If fixRatio is true, this boundary will be enlarged to prevent anisotropic stretching. (this should be set to false when doing selections)
Definition at line 1319 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), GLO_MAX, GUISUMOAbstractView::myChanger, Boundary::xmin(), and Boundary::ymin().
Referenced by GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::makeSnapshot(), and GUISUMOAbstractView::paintGL().
autoSelectNodes()
bool GNEViewNet::autoSelectNodes ()
whether to autoselect nodes or to lanes
Definition at line 346 of file GNEViewNet.cpp.
References myMenuCheckExtendToEdgeNodes.
Referenced by GNESelectorFrame::handleIDs().
begingMoveSelection()
void GNEViewNet::begingMoveSelection (GNEAttributeCarrier * originAC, const Position & originPosition)
begin move selection
Definition at line 398 of file GNEViewNet.cpp.
References Position::almostSame(), Position::distanceTo(), GNEEdge::getGNEJunctionDestiny(), GNEEdge::getGNEJunctionSource(), GNEJunction::getPositionInView(), GNEAttributeCarrier::getTag(), GNEEdge::getVertexIndex(), PositionVector::length(), myMovingSelection, myNet, myOriginPositionOfMovedJunctions, myOriginShapesMovedEntireShapes, myOriginShapesMovedPartialShapes, PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset(), GNENet::retrieveEdges(), GNENet::retrieveJunctions(), SUMO_TAG_EDGE, and SUMO_TAG_JUNCTION.
Referenced by onLeftBtnPress().
buildColorRainbow()
void GNEViewNet::buildColorRainbow (GUIColorScheme & scheme, int active, GUIGlObjectType objectType) virtual
recalibrate color scheme according to the current value range
Reimplemented from GUISUMOAbstractView.
Definition at line 281 of file GNEViewNet.cpp.
References GUIPropertyScheme< T >::addColor(), RGBColor::BLUE, GUIPropertyScheme< T >::clear(), RGBColor::CYAN, GLO_JUNCTION, GLO_LANE, RGBColor::GREEN, GUIPropertyScheme< T >::isFixed(), RGBColor::MAGENTA, MAX2(), MIN2(), myNet, RGBColor::ORANGE, RGBColor::RED, GNENet::retrieveJunctions(), GNENet::retrieveLanes(), and RGBColor::YELLOW.
buildEditModeControls()
void GNEViewNet::buildEditModeControls () private
adds controls for setting the edit mode
Definition at line 2378 of file GNEViewNet.cpp.
References GUIIconSubSys::getIcon(), GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_CROSSING, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_POLYGON, GNE_MODE_SELECT, GNE_MODE_TLS, GUIDesignButtonToolbarCheckable, ICON_MODEADDITIONAL, ICON_MODECONNECTION, ICON_MODECREATEEDGE, ICON_MODECROSSING, ICON_MODEDELETE, ICON_MODEINSPECT, ICON_MODEMOVE, ICON_MODEPOLYGON, ICON_MODESELECT, ICON_MODETLS, StringBijection< T >::insert(), MID_GNE_SETMODE_ADDITIONAL, MID_GNE_SETMODE_CONNECT, MID_GNE_SETMODE_CREATE_EDGE, MID_GNE_SETMODE_CROSSING, MID_GNE_SETMODE_DELETE, MID_GNE_SETMODE_INSPECT, MID_GNE_SETMODE_MOVE, MID_GNE_SETMODE_POLYGON, MID_GNE_SETMODE_SELECT, MID_GNE_SETMODE_TLS, MID_GNE_VIEWNET_MOVE_ELEVATION, MID_GNE_VIEWNET_SELECT_EDGES, MID_GNE_VIEWNET_SHOW_BUBBLES, MID_GNE_VIEWNET_SHOW_CONNECTIONS, MID_GNE_VIEWNET_SHOW_GRID, myAutoCreateOppositeEdge, myChainCreateEdge, myEditModeAdditional, myEditModeConnection, myEditModeCreateEdge, myEditModeCrossing, myEditModeDelete, myEditModeInspect, myEditModeMove, myEditModeNames, myEditModePolygon, myEditModeSelect, myEditModeTrafficLight, myMenuCheckChangeAllPhases, myMenuCheckExtendToEdgeNodes, myMenuCheckMoveElevation, myMenuCheckSelectEdges, myMenuCheckShowBubbleOverJunction, myMenuCheckShowConnections, myMenuCheckShowGrid, myMenuCheckWarnAboutMerge, myToolbar, GUISUMOAbstractView::myVisualizationSettings, GUIVisualizationSettings::showLane2Lane, SUMO_TAG_CONNECTION, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_TRAFFIC_LIGHT, and toString().
buildViewToolBars()
void GNEViewNet::buildViewToolBars (GUIGlChildWindow & cw) virtual
builds the view toolbars
Reimplemented from GUISUMOAbstractView.
Definition at line 220 of file GNEViewNet.cpp.
References GUIGlChildWindow::getColoringSchemesCombo(), GUIIconSubSys::getIcon(), GUIGlChildWindow::getLocatorPopup(), GUICompleteSchemeStorage::getNames(), gSchemeStorage, ICON_LOCATEADD, ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATEPOI, ICON_LOCATEPOLY, ICON_LOCATETLS, MAX2(), MID_LOCATEADD, MID_LOCATEEDGE, MID_LOCATEJUNCTION, MID_LOCATEPOI, MID_LOCATEPOLY, MID_LOCATETLS, GUISUMOAbstractView::myVisualizationSettings, and GUIVisualizationSettings::name.
Referenced by GNEViewParent::GNEViewParent().
centerTo() [1/2]
void GUISUMOAbstractView::centerTo (GUIGlID id, bool applyZoom, double zoomDist = 20) virtual inherited
centers to the chosen artifact
Parameters
[in] id The id of the artifact to center to
[in] applyZoom Whether to zoom in
[in] zoomDist The distance in m to use for the zoom, values < 0 means: use the centeringBoundary
Note
caller is responsible for calling update
Definition at line 560 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::centerTo(), Boundary::getCenter(), GUIGlObject::getCenteringBoundary(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::myChanger, GUIPerspectiveChanger::setViewport(), GUIGlObjectStorage::unblockObject(), and GUISUMOAbstractView::updatePositionInformation().
Referenced by GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GUISUMOAbstractView::buildViewToolBars(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_GUI::processSet(), and GUIGlChildWindow::setView().
centerTo() [2/2]
void GUISUMOAbstractView::centerTo (const Boundary & bound) inherited
centers to the chosen artifact
Definition at line 577 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, and GUIPerspectiveChanger::setViewport().
changeAllPhases()
bool GNEViewNet::changeAllPhases () const
change all phases
Definition at line 358 of file GNEViewNet.cpp.
References myMenuCheckChangeAllPhases.
Referenced by GNETLSEditorFrame::handleChange().
checkGDALImage()
FXImage * GUISUMOAbstractView::checkGDALImage (Decal & d) protected inherited
check whether we can read image data or position with gdal
Definition at line 1154 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::Decal::filename, GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getGridWidth(), GeoConvHelper::getProcessing(), GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::width, WRITE_MESSAGE, WRITE_WARNING, Position::x(), GeoConvHelper::x2cartesian(), and Position::y().
Referenced by GUISUMOAbstractView::drawDecals().
checkSnapshots()
void GUISUMOAbstractView::checkSnapshots () virtual inherited
Checks whether it is time for a snapshot.
Reimplemented in GUIViewTraffic.
Definition at line 991 of file GUISUMOAbstractView.cpp.
References DELTA_T, GUISUMOAbstractView::getCurrentTimeStep(), joinToString(), MFXMutex::lock(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::myApplicationSnapshots, GUISUMOAbstractView::myApplicationSnapshotsLock, GUISUMOAbstractView::mySnapshots, GUISUMOAbstractView::mySnapshotsLock, toString(), MFXMutex::unlock(), and WRITE_WARNING.
Referenced by GUIViewTraffic::checkSnapshots(), GUISUMOAbstractView::endSnapshot(), GUISUMOAbstractView::onConfigure(), and GUISUMOViewParent::onSimStep().
copyViewportTo()
void GUISUMOAbstractView::copyViewportTo (GUISUMOAbstractView * view) virtual inherited
copy the viewport to the given view
Definition at line 1077 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), GUISUMOAbstractView::myChanger, and GUISUMOAbstractView::setViewportFromTo().
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUIApplicationWindow::openNewView().
deleteSelectedAdditionals()
void GNEViewNet::deleteSelectedAdditionals () private
delete all currently selected additionals
Definition at line 2612 of file GNEViewNet.cpp.
References GNEViewParent::getAdditionalFrame(), getViewParent(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEAdditionalFrame::removeAdditional(), and GNENet::retrieveAdditionals().
Referenced by hotkeyDel().
deleteSelectedConnections()
void GNEViewNet::deleteSelectedConnections () private
delete all currently selected connections
Definition at line 2651 of file GNEViewNet.cpp.
References GNENet::deleteConnection(), GLO_CONNECTION, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), SUMO_TAG_CONNECTION, and toString().
Referenced by hotkeyDel().
deleteSelectedCrossings()
void GNEViewNet::deleteSelectedCrossings () private
delete all currently selected crossings
Definition at line 2627 of file GNEViewNet.cpp.
References GNENet::deleteCrossing(), GLO_CROSSING, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveJunctions(), SUMO_TAG_CROSSING, and toString().
Referenced by hotkeyDel().
deleteSelectedEdges()
void GNEViewNet::deleteSelectedEdges () private
delete all currently selected edges
Definition at line 2598 of file GNEViewNet.cpp.
References GNENet::deleteEdge(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), SUMO_TAG_EDGE, and toString().
Referenced by hotkeyDel().
deleteSelectedJunctions()
void GNEViewNet::deleteSelectedJunctions () private
delete all currently selected junctions
Definition at line 2570 of file GNEViewNet.cpp.
References GNENet::deleteJunction(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveJunctions(), SUMO_TAG_JUNCTION, and toString().
Referenced by hotkeyDel().
deleteSelectedLanes()
void GNEViewNet::deleteSelectedLanes () private
delete all currently selected lanes
Definition at line 2584 of file GNEViewNet.cpp.
References GNENet::deleteLane(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveLanes(), SUMO_TAG_LANE, and toString().
Referenced by hotkeyDel().
deleteSelectedShapes()
void GNEViewNet::deleteSelectedShapes (SumoXMLTag shapeTag = SUMO_TAG_NOTHING) private
delete all currently selected shapes
Definition at line 2675 of file GNEViewNet.cpp.
References GNENet::deleteShape(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveShapes(), and toString().
Referenced by hotkeyDel().
destroyPopup()
void GUISUMOAbstractView::destroyPopup () inherited
destoys the popup
Definition at line 641 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myPopup, GUISUMOAbstractView::myPopupPosition, and Position::set().
Referenced by GUISUMOAbstractView::buildColorRainbow(), onCmdClearConnections(), onCmdEditConnectionShape(), onCmdEditCrossingShape(), onCmdEditJunctionShape(), onCmdReplaceJunction(), onCmdResetConnections(), GNEInternalLane::onDefault(), GUISUMOAbstractView::onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseMove(), GUISUMOAbstractView::onRightBtnPress(), GUISUMOAbstractView::onRightBtnRelease(), and processClick().
displayLegend()
void GUISUMOAbstractView::displayLegend () protected inherited
a line with ticks, and the length information.
Definition at line 479 of file GUISUMOAbstractView.cpp.
References RGBColor::BLACK, GLHelper::drawText(), FONS_ALIGN_LEFT, and GUISUMOAbstractView::m2p().
Referenced by GUISUMOAbstractView::makeSnapshot(), and GUISUMOAbstractView::paintGL().
doInit()
void GNEViewNet::doInit () protected virtual
called after some features are already initialized
Reimplemented from GUISUMOAbstractView.
Definition at line 216 of file GNEViewNet.cpp.
Referenced by GNEViewNet().
doPaintGL()
int GNEViewNet::doPaintGL (int mode, const Boundary & bound) protected virtual
do paintGL
Reimplemented from GUISUMOAbstractView.
Definition at line 536 of file GNEViewNet.cpp.
References RGBColor::BLUE, GUISUMOAbstractView::drawDecals(), GLHelper::drawLine(), GUIVisualizationSettings::editMode, GNEFrame::getDrawingMode(), GNEViewParent::getPolygonFrame(), GUISUMOAbstractView::getPositionInformation(), GNEFrame::DrawingMode::getTemporalShape(), GLO_ADDITIONAL, GLO_MAX, GNEFrame::DrawingMode::isDrawing(), GUISUMOAbstractView::m2p(), RGBColor::MAGENTA, GUISUMOAbstractView::myAdditionallyDrawn, myAmInRectSelect, GUISUMOAbstractView::myApp, myEditMode, GUISUMOAbstractView::myGrid, myMenuCheckShowConnections, myMenuCheckShowGrid, mySelCorner1, mySelCorner2, myTestingHeight, myTestingMode, myTestingWidth, GUISUMOAbstractView::myUseToolTips, myViewParent, GUISUMOAbstractView::myVisualizationSettings, GUISUMOAbstractView::p2m(), GUISUMOAbstractView::paintGLGrid(), RGBColor::RED, GUITextureSubSys::resetTextures(), GUIVisualizationSettings::scale, GUISUMOAbstractView::screenPos2NetPos(), SUMORTree::Search(), GNENet::selectionColor, GLHelper::setColor(), GUIVisualizationSettings::showGrid, GUIVisualizationSettings::showLane2Lane, GUISUMOAbstractView::snapToActiveGrid(), SUMO_const_laneWidth, Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by GNEViewNet().
drawDecals()
void GUISUMOAbstractView::drawDecals () protected inherited
Draws the stored decals.
Definition at line 1233 of file GUISUMOAbstractView.cpp.
References GUITexturesHelper::add(), GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::checkGDALImage(), GUITexturesHelper::drawTexturedBox(), GUISUMOAbstractView::Decal::filename, GUITexturesHelper::getMaxTextureSize(), GUISUMOAbstractView::Decal::glID, GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::image, GUISUMOAbstractView::Decal::initialised, GUISUMOAbstractView::Decal::layer, MFXImageHelper::loadImage(), MFXMutex::lock(), GUISUMOAbstractView::myDecals, GUISUMOAbstractView::myDecalsLock, GUISUMOAbstractView::p2m(), GUISUMOAbstractView::Decal::rot, MFXImageHelper::scalePower2(), GUISUMOAbstractView::screenPos2NetPos(), GUISUMOAbstractView::Decal::screenRelative, GUISUMOAbstractView::Decal::skip2D, MFXMutex::unlock(), GUISUMOAbstractView::Decal::width, WRITE_ERROR, Position::x(), and Position::y().
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
endSnapshot()
virtual void GUISUMOAbstractView::endSnapshot () inline virtual inherited
Ends a video snapshot.
Reimplemented in GUIViewTraffic.
Definition at line 185 of file GUISUMOAbstractView.h.
References GUISUMOAbstractView::checkSnapshots(), GUISUMOAbstractView::getCurrentTimeStep(), GUISUMOAbstractView::getViewportEditor(), GUISUMOAbstractView::getVisualisationSettings(), GUISUMOAbstractView::setColorScheme(), GUISUMOAbstractView::showToolTips(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::showViewschemeEditor().
Referenced by GUISUMOViewParent::onCmdMakeSnapshot().
finishMoveSelection()
void GNEViewNet::finishMoveSelection ()
finish moving selection
Definition at line 510 of file GNEViewNet.cpp.
References myMovingSelection, myOriginPositionOfMovedJunctions, myOriginShapesMovedEntireShapes, myOriginShapesMovedPartialShapes, myUndoList, GNEUndoList::p_begin(), and GNEUndoList::p_end().
Referenced by onLeftBtnRelease().
getAdditionalAtPopupPosition()
GNEAdditional * GNEViewNet::getAdditionalAtPopupPosition () private
try to retrieve a additional at popup position
Definition at line 1431 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdOpenAdditionalDialog().
getChanger()
GUIPerspectiveChanger & GUISUMOAbstractView::getChanger () const inherited
get changer
Definition at line 171 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger.
Referenced by GUISettingsHandler::applyViewport(), GUISUMOAbstractView::buildViewToolBars(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), and GUIDialog_EditViewport::setValues().
getColoringSchemesCombo()
FXComboBox & GUISUMOAbstractView::getColoringSchemesCombo () inherited
get coloring schemes combo
Definition at line 1148 of file GUISUMOAbstractView.cpp.
References GUIGlChildWindow::getColoringSchemesCombo(), and GUISUMOAbstractView::myParent.
Referenced by GUISettingsHandler::addSettings(), GUIDialog_ViewSettings::onCmdColorChange(), and GUIDialog_ViewSettings::onCmdSaveSetting().
getConnectionAtPopupPosition()
GNEConnection * GNEViewNet::getConnectionAtPopupPosition () private
try to retrieve a connection at popup position
Definition at line 1323 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_CONNECTION, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdEditConnectionShape().
getCrossingAtPopupPosition()
GNECrossing * GNEViewNet::getCrossingAtPopupPosition () private
try to retrieve a crossing at popup position
Definition at line 1344 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_CROSSING, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdEditCrossingShape().
getCurrentEditMode()
EditMode GNEViewNet::getCurrentEditMode () const
get the current edit mode
Definition at line 1290 of file GNEViewNet.cpp.
References myEditMode.
Referenced by GNEPoly::drawGL(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GNEConnection::getPopUpMenu(), and GNELane::updateGeometry().
getCurrentTimeStep()
SUMOTime GUISUMOAbstractView::getCurrentTimeStep () const virtual inherited
get the current simulation time
Reimplemented in GUIViewTraffic.
Definition at line 1029 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::checkSnapshots(), and GUISUMOAbstractView::endSnapshot().
getDelay()
double GUISUMOAbstractView::getDelay () const inherited
Returns the delay of the parent application.
Definition at line 1337 of file GUISUMOAbstractView.cpp.
References GUIMainWindow::getDelay(), and GUISUMOAbstractView::myApp.
Referenced by GUIDialog_ViewSettings::onCmdExportSetting().
getEdgeAtPopupPosition()
GNEEdge * GNEViewNet::getEdgeAtPopupPosition () private
try to retrieve an edge at popup position
Definition at line 1364 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_EDGE, GLO_LANE, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdAddReversedEdge(), onCmdResetEdgeEndpoint(), onCmdReverseEdge(), onCmdSetEdgeEndpoint(), onCmdSmoothEdges(), onCmdSmoothEdgesElevation(), onCmdSplitEdge(), onCmdStraightenEdges(), and onCmdStraightenEdgesElevation().
getEdgesAtPopupPosition()
std::set< GNEEdge * > GNEViewNet::getEdgesAtPopupPosition () private
try to retrieve multiple edges at popup position
Definition at line 1405 of file GNEViewNet.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsAtPosition(), GUISUMOAbstractView::getPopupPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_EDGE, GLO_LANE, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdSplitEdgeBidi().
getGridHeight()
double GUISUMOAbstractView::getGridHeight () const inherited
get grid Height
Definition at line 1121 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), and GUISUMOAbstractView::myGrid.
Referenced by GUISUMOAbstractView::buildColorRainbow(), GUISUMOAbstractView::checkGDALImage(), and GUIDialog_ViewSettings::onCmdEditTable().
getGridWidth()
double GUISUMOAbstractView::getGridWidth () const inherited
get grid width
Definition at line 1115 of file GUISUMOAbstractView.cpp.
References Boundary::getWidth(), and GUISUMOAbstractView::myGrid.
Referenced by GUISUMOAbstractView::buildColorRainbow(), GUISUMOAbstractView::checkGDALImage(), and GUIDialog_ViewSettings::onCmdEditTable().
getJunctionAtPopupPosition()
GNEJunction * GNEViewNet::getJunctionAtPopupPosition () private
try to retrieve a junction at popup position
Definition at line 1302 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_JUNCTION, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdClearConnections(), onCmdEditJunctionShape(), onCmdReplaceJunction(), and onCmdResetConnections().
getLaneAtPopupPosition()
GNELane * GNEViewNet::getLaneAtPopupPosition () private
try to retrieve a lane at popup position
Definition at line 1388 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_LANE, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by addRestrictedLane(), onCmdDuplicateLane(), removeRestrictedLane(), and restrictLane().
getNet()
GNENet * GNEViewNet::getNet () const
get the net object
Definition at line 1278 of file GNEViewNet.cpp.
References myNet.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNEAdditionalHandler::buildAdditional(), GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNERouteProbe::drawGL(), GNEChargingStation::drawGL(), GNECalibrator::drawGL(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEDetectorE3::getParentName(), GNEVariableSpeedSign::getParentName(), GNERerouter::getParentName(), GNEAdditional::getParentName(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::initTargets(), GNEDestProbReroute::isValid(), GNEClosingLaneReroute::isValid(), GNEClosingReroute::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), GNECalibratorFlow::isValid(), GNEVaporizer::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNECalibrator::isValid(), GNEAdditional::isValidAdditionalID(), GNEDialog_FixAdditionalPositions::onCmdAccept(), GNESelectorFrame::onCmdClear(), GNETLSEditorFrame::onCmdDefSwitch(), GNESelectorFrame::onCmdInvert(), GNEViewParent::onCmdLocate(), GNETLSEditorFrame::onCmdOK(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), onCmdToogleShowConnection(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildCalibratorFlow(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildCalibratorVehicleType(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEAdditionalHandler::parseAndBuildDetectorE1(), GNEAdditionalHandler::parseAndBuildDetectorE2(), GNEAdditionalHandler::parseAndBuildDetectorE3(), GNEAdditionalHandler::parseAndBuildDetectorEntry(), GNEAdditionalHandler::parseAndBuildDetectorExit(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAdditionalHandler::parseAndBuildRerouterClosingLaneReroute(), GNEAdditionalHandler::parseAndBuildRerouterClosingReroute(), GNEAdditionalHandler::parseAndBuildRerouterDestProbReroute(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEAdditionalHandler::parseAndBuildRerouterRouteProbReroute(), GNEAdditionalHandler::parseAndBuildRouteProbe(), GNEAdditionalHandler::parseAndBuildVaporizer(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAdditionalHandler::parseAndBuildVariableSpeedSignStep(), GNEPolygonFrame::processClick(), GNEChange_Attribute::redo(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), GNEDestProbReroute::setAttribute(), GNEClosingLaneReroute::setAttribute(), GNEClosingReroute::setAttribute(), GNECalibratorRoute::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERerouter::setAttribute(), GNECalibratorVehicleType::setAttribute(), GNECalibratorFlow::setAttribute(), GNECalibrator::setAttribute(), GNEAdditionalFrame::SelectorParentEdges::showList(), GNEAdditionalFrame::SelectorParentLanes::showList(), GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals(), GNEChange_Attribute::undo(), GNEDetectorE1::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEVaporizer::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEDetectorE3::updateGeometry(), GNERouteProbe::updateGeometry(), GNEVariableSpeedSign::updateGeometry(), GNEChargingStation::updateGeometry(), GNERerouter::updateGeometry(), GNECalibrator::updateGeometry(), GNEAdditionalFrame::SelectorParentEdges::updateUseSelectedEdges(), and GNEAdditionalFrame::SelectorParentLanes::updateUseSelectedLanes().
getObjectAtPosition()
GUIGlID GUISUMOAbstractView::getObjectAtPosition (Position pos) protected inherited
returns the id of the object at position using GL_SELECT
Definition at line 311 of file GUISUMOAbstractView.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_LANE, GLO_POI, GLO_POLYGON, Boundary::grow(), GUIGlObjectStorage::unblockObject(), and GUIVisualizationSettings::UseMesoSim.
Referenced by getAdditionalAtPopupPosition(), getConnectionAtPopupPosition(), getCrossingAtPopupPosition(), getEdgeAtPopupPosition(), getJunctionAtPopupPosition(), getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectUnderCursor(), getPOIAtPopupPosition(), getPOILaneAtPopupPosition(), and getPolygonAtPopupPosition().
getObjectsAtPosition()
std::vector< GUIGlID > GUISUMOAbstractView::getObjectsAtPosition (Position pos, double radius) protected inherited
returns the ids of the object at position within the given (rectangular) radius using GL_SELECT
Definition at line 356 of file GUISUMOAbstractView.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, Boundary::grow(), and GUIGlObjectStorage::unblockObject().
Referenced by getEdgesAtPopupPosition().
getObjectsInBoundary()
std::vector< GUIGlID > GUISUMOAbstractView::getObjectsInBoundary (const Boundary & bound) protected inherited
returns the ids of all objects in the given boundary
Definition at line 384 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::doPaintGL(), GUIVisualizationSettings::drawForSelecting, GUIPerspectiveChanger::getViewport(), GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myVisualizationSettings, GUIMainWindow::setStatusBarText(), GUIPerspectiveChanger::setViewport(), and toString().
Referenced by GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), mergeJunctions(), onCmdTransformPOI(), and onLeftBtnRelease().
getObjectUnderCursor()
GUIGlID GUISUMOAbstractView::getObjectUnderCursor () protected inherited
returns the id of the object under the cursor using GL_SELECT
Definition at line 305 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), and GUISUMOAbstractView::getPositionInformation().
Referenced by GUIViewTraffic::getLaneUnderCursor(), onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnPress(), onMouseMove(), GUISUMOAbstractView::openObjectDialog(), and GUISUMOAbstractView::paintGL().
getPOIAtPopupPosition()
GNEPOI * GNEViewNet::getPOIAtPopupPosition () private
try to retrieve a POILane at popup position
Definition at line 1459 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdTransformPOI().
getPOILaneAtPopupPosition()
GNEPOILane * GNEViewNet::getPOILaneAtPopupPosition () private
try to retrieve a POILane at popup position
Definition at line 1473 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdTransformPOI().
getPolygonAtPopupPosition()
GNEPoly * GNEViewNet::getPolygonAtPopupPosition () private
try to retrieve a polygon at popup position
Definition at line 1445 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPopupPosition(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::makeCurrent(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdClosePolygon(), onCmdDeleteGeometryPoint(), onCmdOpenPolygon(), onCmdSetFirstGeometryPoint(), and onCmdSimplifyShape().
getPopupPosition()
const Position & GUISUMOAbstractView::getPopupPosition () const inherited
get position of current popup
Definition at line 636 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myPopupPosition.
Referenced by GUISUMOAbstractView::buildColorRainbow(), getAdditionalAtPopupPosition(), getConnectionAtPopupPosition(), getCrossingAtPopupPosition(), getEdgeAtPopupPosition(), getEdgesAtPopupPosition(), getJunctionAtPopupPosition(), getLaneAtPopupPosition(), getPOIAtPopupPosition(), getPOILaneAtPopupPosition(), getPolygonAtPopupPosition(), onCmdDeleteGeometryPoint(), onCmdResetEdgeEndpoint(), onCmdSetEdgeEndpoint(), onCmdSetFirstGeometryPoint(), onCmdSplitEdge(), and onCmdSplitEdgeBidi().
getPositionInformation()
Position GUISUMOAbstractView::getPositionInformation () const inherited
Returns the cursor's x/y position within the network.
Definition at line 186 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myWindowCursorPositionX, GUISUMOAbstractView::myWindowCursorPositionY, and GUISUMOAbstractView::screenPos2NetPos().
Referenced by GNEAdditionalFrame::addAdditional(), doPaintGL(), GNEPoly::drawGL(), GUISUMOAbstractView::getObjectUnderCursor(), GUIEdge::getParameterWindow(), GNELane::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GUILane::getPopUpMenu(), GNEAdditional::getPopUpMenu(), GUIDanielPerspectiveChanger::onKeyPress(), onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnRelease(), onMouseMove(), GUIDanielPerspectiveChanger::onMouseWheel(), GUIDanielPerspectiveChanger::onRightBtnPress(), GUISUMOAbstractView::openObjectDialog(), GNEDeleteFrame::removeAttributeCarrier(), GUISUMOAbstractView::showToolTipFor(), and GUISUMOAbstractView::updatePositionInformation().
getTrackedID()
GUIGlID GUISUMOAbstractView::getTrackedID () const virtual inherited
get tracked id
Reimplemented in GUIViewTraffic.
Definition at line 1137 of file GUISUMOAbstractView.cpp.
References GUIGlObject::INVALID_ID.
Referenced by GUISUMOAbstractView::buildColorRainbow(), GUIPerson::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUISUMOAbstractView::paintGL(), and TraCIServerAPI_GUI::processSet().
getUndoList()
GNEUndoList * GNEViewNet::getUndoList () const
get the undoList object
Definition at line 1284 of file GNEViewNet.cpp.
References myUndoList.
Referenced by GNENet::addPOI(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNENet::addPolygon(), GNEPolygonFrame::addPolygon(), GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildClosingLaneReroute(), GNEAdditionalHandler::buildClosingReroute(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::builDestProbReroute(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRerouterInterval(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildRouteProbReroute(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSign(), GNEAdditionalHandler::buildVariableSpeedSignStep(), GNEPoly::changeFirstGeometryPoint(), GNEPoly::closePolygon(), GNENet::computeAndUpdate(), GNENet::deleteConnection(), GNEEdge::deleteGeometryPoint(), GNEPoly::deleteGeometryPoint(), GNENet::deleteShape(), GNETLSEditorFrame::editJunction(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNEDialog_FixAdditionalPositions::onCmdAccept(), GNERerouterIntervalDialog::onCmdAddClosingLaneReroute(), GNERerouterIntervalDialog::onCmdAddClosingReroute(), GNERerouterIntervalDialog::onCmdAddDestProbReroute(), GNERerouterIntervalDialog::onCmdAddRouteProbReroute(), GNEVariableSpeedSignDialog::onCmdAddStep(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNERerouterIntervalDialog::onCmdChangeBeginEnd(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNERerouterIntervalDialog::onCmdClickedClosingLaneReroute(), GNERerouterIntervalDialog::onCmdClickedClosingReroute(), GNERerouterIntervalDialog::onCmdClickedDestProbReroute(), GNECalibratorDialog::onCmdClickedFlow(), GNERerouterDialog::onCmdClickedInterval(), GNECalibratorDialog::onCmdClickedRoute(), GNERerouterIntervalDialog::onCmdClickedRouteProbReroute(), GNEVariableSpeedSignDialog::onCmdClickedStep(), GNECalibratorDialog::onCmdClickedVehicleType(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNERerouterIntervalDialog::onCmdEditClosingLaneReroute(), GNERerouterIntervalDialog::onCmdEditClosingReroute(), GNERerouterIntervalDialog::onCmdEditDestProbReroute(), GNERerouterIntervalDialog::onCmdEditRouteProbReroute(), GNEVariableSpeedSignDialog::onCmdEditStep(), GNESelectorFrame::onCmdInvert(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNECalibratorFlowDialog::onCmdSetVariable(), GNECalibratorVehicleTypeDialog::onCmdSetVariable(), GNECalibratorRouteDialog::onCmdSetVariable(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEPoly::openPolygon(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEPoly::simplifyShape().
getViewParent()
GNEViewParent * GNEViewNet::getViewParent () const
get the net object
Definition at line 1272 of file GNEViewNet.cpp.
References myViewParent.
Referenced by GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), deleteSelectedAdditionals(), GNEFrame::hide(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::requiereSaveAdditionals(), GNENet::requiereSaveShapes(), and GNEFrame::show().
getViewportEditor()
GUIDialog_EditViewport * GUISUMOAbstractView::getViewportEditor () inherited
get the viewport and create it on first access
Definition at line 1050 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myViewportChooser, and GUIDialog_EditViewport::setValues().
Referenced by GUISUMOAbstractView::endSnapshot(), GUIDialog_ViewSettings::onCmdExportSetting(), and GUISUMOAbstractView::showViewportEditor().
getVisibleBoundary()
Boundary GUISUMOAbstractView::getVisibleBoundary () const inherited
get visible boundary
Definition at line 253 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), and GUISUMOAbstractView::myChanger.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and TraCIServerAPI_GUI::processGet().
getVisualisationSettings() [1/2]
GUIVisualizationSettings * GUISUMOAbstractView::getVisualisationSettings () const inherited
get visualitation settings
Definition at line 1097 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myVisualizationSettings.
Referenced by GNEEdge::commitShapeChange(), GUISUMOAbstractView::endSnapshot(), GNELane::getPopUpMenu(), GUIApplicationWindow::onCmdEditChosen(), and TraCIServerAPI_GUI::processGet().
getVisualisationSettings() [2/2]
GUIVisualizationSettings * GUISUMOAbstractView::getVisualisationSettings () inherited
get visualisation settings
Definition at line 221 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myVisualizationSettings.
hotkeyDel()
void GNEViewNet::hotkeyDel ()
handle del keypress
Definition at line 1170 of file GNEViewNet.cpp.
References deleteSelectedAdditionals(), deleteSelectedConnections(), deleteSelectedCrossings(), deleteSelectedEdges(), deleteSelectedJunctions(), deleteSelectedLanes(), deleteSelectedShapes(), GNE_MODE_CONNECT, GNE_MODE_TLS, myEditMode, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), and setStatusBarText().
Referenced by GNEApplicationWindow::onCmdDel().
hotkeyEnter()
void GNEViewNet::hotkeyEnter ()
handle enter keypress
Definition at line 1188 of file GNEViewNet.cpp.
References GNEViewParent::getConnectorFrame(), GNEViewParent::getCrossingFrame(), GNEFrame::getDrawingMode(), GNEViewParent::getPolygonFrame(), SUMOPolygon::getShape(), GNEPoly::getShapeEditedElement(), GNEAttributeCarrier::getTag(), GNEViewParent::getTLSEditorFrame(), GNE_MODE_CONNECT, GNE_MODE_CROSSING, GNE_MODE_MOVE, GNE_MODE_POLYGON, GNE_MODE_TLS, GNEAttributeCarrier::hasAttribute(), GNEFrame::DrawingMode::isDrawing(), myEditMode, myEditShapePoly, myUndoList, myViewParent, GNECrossingFrame::onCmdCreateCrossing(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENetElement::setAttribute(), GNEFrame::DrawingMode::startDrawing(), GNEFrame::DrawingMode::stopDrawing(), stopEditCustomShape(), SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_SHAPE, and toString().
Referenced by GNEApplicationWindow::onCmdEnter().
hotkeyFocusFrame()
void GNEViewNet::hotkeyFocusFrame ()
handle focus frame keypress
Definition at line 1221 of file GNEViewNet.cpp.
References GNEFrame::focusUpperElement(), and myCurrentFrame.
Referenced by GNEApplicationWindow::onCmdFocusFrame().
isAdditionalGLVisualisationEnabled()
bool GUISUMOAbstractView::isAdditionalGLVisualisationEnabled (GUIGlObject *const which) const inherited
Check if an object is added in the additional GL visualitation.
Parameters
[in] which The object to check
See also
GUIGlObject::drawGLAdditional
Definition at line 1309 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myAdditionallyDrawn.
Referenced by GUISUMOAbstractView::buildColorRainbow().
isInEditMode()
bool GUISUMOAbstractView::isInEditMode () inherited
returns true, if the edit button was pressed
Definition at line 165 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myInEditMode.
Referenced by GUISUMOAbstractView::buildViewToolBars().
m2p()
double GUISUMOAbstractView::m2p (double meter) const inherited
meter-to-pixels conversion method
Definition at line 542 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), and GUISUMOAbstractView::myChanger.
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUISUMOAbstractView::displayLegend(), GUIViewTraffic::doPaintGL(), doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
makeCurrent()
FXbool GUISUMOAbstractView::makeCurrent () inherited
A reimplementation due to some internal reasons.
Definition at line 598 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars(), getAdditionalAtPopupPosition(), getConnectionAtPopupPosition(), getCrossingAtPopupPosition(), getEdgeAtPopupPosition(), getEdgesAtPopupPosition(), getJunctionAtPopupPosition(), getLaneAtPopupPosition(), GUIViewTraffic::getLaneUnderCursor(), getPOIAtPopupPosition(), getPOILaneAtPopupPosition(), getPolygonAtPopupPosition(), GUISUMOAbstractView::makeSnapshot(), mergeJunctions(), GUISUMOAbstractView::onConfigure(), onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), GUISUMOAbstractView::onPaint(), and GUISUMOAbstractView::openObjectDialog().
makeSnapshot()
std::string GUISUMOAbstractView::makeSnapshot (const std::string & destFile) inherited
Takes a snapshots and writes it into the given file.
The format to use is determined from the extension. If compiled with ffmpeg and a video format is requested it will instantiate a video encoder.
Parameters
[in] destFile The name of the file to write the snapshot into
Returns
The error message, if an error occcured; "" otherwise
Definition at line 840 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUISUMOAbstractView::applyGLTransform(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), GUISUMOAbstractView::displayLegend(), GUIVisualizationSettings::dither, GUISUMOAbstractView::doPaintGL(), GUISUMOAbstractView::drawDecals(), GUIPerspectiveChanger::getViewport(), RGBColor::green(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myGrid, GUISUMOAbstractView::myUseToolTips, GUISUMOAbstractView::myVisualizationSettings, GUISUMOAbstractView::paintGLGrid(), RGBColor::red(), GUISUMOAbstractView::saveFrame(), MFXImageHelper::saveImage(), GUIVisualizationSettings::scale, SUMORTree::Search(), GUIVisualizationSettings::showGrid, GUIVisualizationSettings::showSizeLegend, FXSingleEventThread::sleep(), SUMO_const_laneWidth, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIViewTraffic::checkSnapshots(), GUISUMOAbstractView::checkSnapshots(), GUIApplicationWindow::handleEvent_Screenshot(), GUISUMOViewParent::onCmdMakeSnapshot(), and GNEViewParent::onCmdMakeSnapshot().
mergeJunctions()
bool GNEViewNet::mergeJunctions (GNEJunction * moved, const Position & oldPos) private
try to merge moved junction with another junction in that spot return true if merging did take place
Definition at line 2691 of file GNEViewNet.cpp.
References Boundary::add(), OptionsCont::getBool(), GUIGlObject::getGlID(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), OptionsCont::getOptions(), NBNode::getPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_JUNCTION, Boundary::grow(), GUISUMOAbstractView::makeCurrent(), GNENet::mergeJunctions(), GNEJunction::moveGeometry(), myMenuCheckWarnAboutMerge, myNet, myUndoList, toString(), GUIGlObjectStorage::unblockObject(), and WRITE_WARNING.
Referenced by onLeftBtnRelease().
moveSelection()
void GNEViewNet::moveSelection (const Position & offset)
move selection
Definition at line 491 of file GNEViewNet.cpp.
References myOriginPositionOfMovedJunctions, myOriginShapesMovedEntireShapes, and myOriginShapesMovedPartialShapes.
Referenced by onMouseMove().
onCmdAddRestrictedLaneBikelane()
long GNEViewNet::onCmdAddRestrictedLaneBikelane (FXObject * , FXSelector typeOfTransformation, void *)
Add restricted lane for bikes.
Definition at line 1893 of file GNEViewNet.cpp.
References addRestrictedLane(), and SVC_BICYCLE.
onCmdAddRestrictedLaneBuslane()
long GNEViewNet::onCmdAddRestrictedLaneBuslane (FXObject * , FXSelector typeOfTransformation, void *)
Add restricted lane for buses.
Definition at line 1899 of file GNEViewNet.cpp.
References addRestrictedLane(), and SVC_BUS.
onCmdAddRestrictedLaneSidewalk()
long GNEViewNet::onCmdAddRestrictedLaneSidewalk (FXObject * , FXSelector typeOfTransformation, void *)
Add restricted lane for pedestrians.
Definition at line 1887 of file GNEViewNet.cpp.
References addRestrictedLane(), and SVC_PEDESTRIAN.
onCmdAddReversedEdge()
long GNEViewNet::onCmdAddReversedEdge (FXObject * , FXSelector , void *)
add reversed edge
Definition at line 1587 of file GNEViewNet.cpp.
References GNENet::addReversedEdge(), getEdgeAtPopupPosition(), myNet, and myUndoList.
onCmdClearConnections()
long GNEViewNet::onCmdClearConnections (FXObject * , FXSelector , void *)
clear junction connections
Definition at line 2221 of file GNEViewNet.cpp.
References GNENet::clearJunctionConnections(), GUISUMOAbstractView::destroyPopup(), GUIGlObject::getGlID(), getJunctionAtPopupPosition(), GLO_JUNCTION, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), and GNENet::retrieveJunctions().
onCmdClosePolygon()
long GNEViewNet::onCmdClosePolygon (FXObject * , FXSelector , void *)
close opened polygon
Definition at line 1731 of file GNEViewNet.cpp.
References GNEPoly::closePolygon(), getPolygonAtPopupPosition(), and myEditShapePoly.
onCmdDeleteGeometryPoint()
long GNEViewNet::onCmdDeleteGeometryPoint (FXObject * , FXSelector , void *)
delete the closes geometry point
Definition at line 1716 of file GNEViewNet.cpp.
References GNEPoly::deleteGeometryPoint(), getPolygonAtPopupPosition(), GUISUMOAbstractView::getPopupPosition(), and myEditShapePoly.
onCmdDuplicateLane()
long GNEViewNet::onCmdDuplicateLane (FXObject * , FXSelector , void *)
duplicate selected lane
Definition at line 1848 of file GNEViewNet.cpp.
References GNENet::duplicateLane(), GUIGlObject::getGlID(), getLaneAtPopupPosition(), GLO_LANE, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveLanes(), SUMO_TAG_LANE, and toString().
onCmdEditConnectionShape()
long GNEViewNet::onCmdEditConnectionShape (FXObject * , FXSelector , void *)
edit connection shape
Definition at line 2269 of file GNEViewNet.cpp.
References GUISUMOAbstractView::destroyPopup(), getConnectionAtPopupPosition(), GNEConnection::getShape(), and startEditCustomShape().
onCmdEditCrossingShape()
long GNEViewNet::onCmdEditCrossingShape (FXObject * , FXSelector , void *)
edit crossing shape
Definition at line 2283 of file GNEViewNet.cpp.
References NBNode::Crossing::customShape, GUISUMOAbstractView::destroyPopup(), getCrossingAtPopupPosition(), GNECrossing::getNBCrossing(), NBNode::Crossing::shape, and startEditCustomShape().
onCmdEditJunctionShape()
long GNEViewNet::onCmdEditJunctionShape (FXObject * , FXSelector , void *)
edit junction shape
Definition at line 2190 of file GNEViewNet.cpp.
References PositionVector::closePolygon(), NBNode::computeNodeShape(), GUISUMOAbstractView::destroyPopup(), getJunctionAtPopupPosition(), GNEJunction::getNBNode(), NBNode::getShape(), and startEditCustomShape().
onCmdOpenAdditionalDialog()
long GNEViewNet::onCmdOpenAdditionalDialog (FXObject * , FXSelector , void *)
open additional dialog
Definition at line 1923 of file GNEViewNet.cpp.
References GNEAttributeCarrier::canOpenDialog(), getAdditionalAtPopupPosition(), GNEAttributeCarrier::getTag(), and GNEAdditional::openAdditionalDialog().
onCmdOpenPolygon()
long GNEViewNet::onCmdOpenPolygon (FXObject * , FXSelector , void *)
open closed polygon
Definition at line 1746 of file GNEViewNet.cpp.
References getPolygonAtPopupPosition(), myEditShapePoly, and GNEPoly::openPolygon().
onCmdRemoveRestrictedLaneBikelane()
long GNEViewNet::onCmdRemoveRestrictedLaneBikelane (FXObject * , FXSelector typeOfTransformation, void *)
remove restricted lane for bikes
Definition at line 1911 of file GNEViewNet.cpp.
References removeRestrictedLane(), and SVC_BICYCLE.
onCmdRemoveRestrictedLaneBuslane()
long GNEViewNet::onCmdRemoveRestrictedLaneBuslane (FXObject * , FXSelector typeOfTransformation, void *)
remove restricted lane for bus
Definition at line 1917 of file GNEViewNet.cpp.
References removeRestrictedLane(), and SVC_BUS.
onCmdRemoveRestrictedLaneSidewalk()
long GNEViewNet::onCmdRemoveRestrictedLaneSidewalk (FXObject * , FXSelector typeOfTransformation, void *)
remove restricted lane for pedestrians
Definition at line 1905 of file GNEViewNet.cpp.
References removeRestrictedLane(), and SVC_PEDESTRIAN.
onCmdReplaceJunction()
long GNEViewNet::onCmdReplaceJunction (FXObject * , FXSelector , void *)
replace node by geometry
Definition at line 2207 of file GNEViewNet.cpp.
References GUISUMOAbstractView::destroyPopup(), getJunctionAtPopupPosition(), myNet, myUndoList, and GNENet::replaceJunctionByGeometry().
onCmdResetConnections()
long GNEViewNet::onCmdResetConnections (FXObject * , FXSelector , void *)
reset junction connections
Definition at line 2245 of file GNEViewNet.cpp.
References GUISUMOAbstractView::destroyPopup(), GUIGlObject::getGlID(), getJunctionAtPopupPosition(), GLO_JUNCTION, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::resetJunctionConnections(), and GNENet::retrieveJunctions().
onCmdResetEdgeEndpoint()
long GNEViewNet::onCmdResetEdgeEndpoint (FXObject * , FXSelector , void *)
restore geometry endpoint to node position
Definition at line 1607 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUISUMOAbstractView::getPopupPosition(), myUndoList, and GNEEdge::resetEndpoint().
onCmdRestrictLaneBikelane()
long GNEViewNet::onCmdRestrictLaneBikelane (FXObject * , FXSelector typeOfTransformation, void *)
restrict lane to bikes
Definition at line 1875 of file GNEViewNet.cpp.
References restrictLane(), and SVC_BICYCLE.
onCmdRestrictLaneBuslane()
long GNEViewNet::onCmdRestrictLaneBuslane (FXObject * , FXSelector typeOfTransformation, void *)
restrict lane to buslanes
Definition at line 1881 of file GNEViewNet.cpp.
References restrictLane(), and SVC_BUS.
onCmdRestrictLaneSidewalk()
long GNEViewNet::onCmdRestrictLaneSidewalk (FXObject * , FXSelector typeOfTransformation, void *)
restrict lane to pedestrians
Definition at line 1869 of file GNEViewNet.cpp.
References restrictLane(), and SVC_PEDESTRIAN.
onCmdReverseEdge()
long GNEViewNet::onCmdReverseEdge (FXObject * , FXSelector , void *)
reverse edge
Definition at line 1577 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), myNet, myUndoList, and GNENet::reverseEdge().
onCmdSetEdgeEndpoint()
long GNEViewNet::onCmdSetEdgeEndpoint (FXObject * , FXSelector , void *)
set non-default geometry endpoint
Definition at line 1597 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUISUMOAbstractView::getPopupPosition(), myUndoList, and GNEEdge::setEndpoint().
onCmdSetFirstGeometryPoint()
long GNEViewNet::onCmdSetFirstGeometryPoint (FXObject * , FXSelector , void *)
set as first geometry point the closes geometry point
Definition at line 1761 of file GNEViewNet.cpp.
References GNEPoly::changeFirstGeometryPoint(), getPolygonAtPopupPosition(), GUISUMOAbstractView::getPopupPosition(), GNEPoly::getVertexIndex(), and myEditShapePoly.
onCmdSetModeAdditional()
long GNEViewNet::onCmdSetModeAdditional (FXObject * , FXSelector , void *)
called when user press the button for additional mode
Definition at line 1536 of file GNEViewNet.cpp.
References GNE_MODE_ADDITIONAL, and setEditMode().
onCmdSetModeConnect()
long GNEViewNet::onCmdSetModeConnect (FXObject * , FXSelector , void *)
called when user press the button for connect mode
Definition at line 1522 of file GNEViewNet.cpp.
References GNE_MODE_CONNECT, and setEditMode().
onCmdSetModeCreateEdge()
long GNEViewNet::onCmdSetModeCreateEdge (FXObject * , FXSelector , void *)
Definition at line 1487 of file GNEViewNet.cpp.
References GNE_MODE_CREATE_EDGE, and setEditMode().
onCmdSetModeCrossing()
long GNEViewNet::onCmdSetModeCrossing (FXObject * , FXSelector , void *)
called when user press the button for crossing mode
Definition at line 1543 of file GNEViewNet.cpp.
References GNE_MODE_CROSSING, and setEditMode().
onCmdSetModeDelete()
long GNEViewNet::onCmdSetModeDelete (FXObject * , FXSelector , void *)
called when user press the button for delete mode
Definition at line 1501 of file GNEViewNet.cpp.
References GNE_MODE_DELETE, and setEditMode().
onCmdSetModeInspect()
long GNEViewNet::onCmdSetModeInspect (FXObject * , FXSelector , void *)
called when user press the button for inspect mode
Definition at line 1508 of file GNEViewNet.cpp.
References GNE_MODE_INSPECT, and setEditMode().
onCmdSetModeMove()
long GNEViewNet::onCmdSetModeMove (FXObject * , FXSelector , void *)
called when user press the button for move mode
Definition at line 1494 of file GNEViewNet.cpp.
References GNE_MODE_MOVE, and setEditMode().
onCmdSetModePolygon()
long GNEViewNet::onCmdSetModePolygon (FXObject * , FXSelector , void *)
called when user press the button for polygon mode
Definition at line 1550 of file GNEViewNet.cpp.
References GNE_MODE_POLYGON, and setEditMode().
onCmdSetModeSelect()
long GNEViewNet::onCmdSetModeSelect (FXObject * , FXSelector , void *)
called when user press the button for select mode
Definition at line 1515 of file GNEViewNet.cpp.
References GNE_MODE_SELECT, and setEditMode().
onCmdSetModeTLS()
long GNEViewNet::onCmdSetModeTLS (FXObject * , FXSelector , void *)
called when user press the button for traffic lights mode
Definition at line 1529 of file GNEViewNet.cpp.
References GNE_MODE_TLS, and setEditMode().
onCmdShowGrid()
long GNEViewNet::onCmdShowGrid (FXObject * , FXSelector , void *)
toogle show grid
Definition at line 2333 of file GNEViewNet.cpp.
References myMenuCheckShowGrid, GUISUMOAbstractView::myVisualizationSettings, and GUIVisualizationSettings::showGrid.
onCmdSimplifyShape()
long GNEViewNet::onCmdSimplifyShape (FXObject * , FXSelector , void *)
simply shape of current polygon
Definition at line 1701 of file GNEViewNet.cpp.
References getPolygonAtPopupPosition(), myEditShapePoly, and GNEPoly::simplifyShape().
onCmdSmoothEdges()
long GNEViewNet::onCmdSmoothEdges (FXObject * , FXSelector , void *)
smooth geometry
Definition at line 1638 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUIGlObject::getGlID(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), GNEEdge::smooth(), SUMO_TAG_EDGE, and toString().
onCmdSmoothEdgesElevation()
long GNEViewNet::onCmdSmoothEdgesElevation (FXObject * , FXSelector , void *)
smooth elevation with regard to adjoining edges
Definition at line 1680 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUIGlObject::getGlID(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), GNEEdge::smoothElevation(), SUMO_TAG_EDGE, and toString().
onCmdSplitEdge()
long GNEViewNet::onCmdSplitEdge (FXObject * , FXSelector , void *)
split edge at cursor position
Definition at line 1557 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUISUMOAbstractView::getPopupPosition(), GNEEdge::getSplitPos(), myNet, myUndoList, and GNENet::splitEdge().
onCmdSplitEdgeBidi()
long GNEViewNet::onCmdSplitEdgeBidi (FXObject * , FXSelector , void *)
split edge at cursor position
Definition at line 1567 of file GNEViewNet.cpp.
References getEdgesAtPopupPosition(), GUISUMOAbstractView::getPopupPosition(), myNet, myUndoList, and GNENet::splitEdgesBidi().
onCmdStraightenEdges()
long GNEViewNet::onCmdStraightenEdges (FXObject * , FXSelector , void *)
makes selected edges straight
Definition at line 1617 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUIGlObject::getGlID(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), GNEEdge::setAttribute(), SUMO_ATTR_SHAPE, SUMO_TAG_EDGE, and toString().
onCmdStraightenEdgesElevation()
long GNEViewNet::onCmdStraightenEdgesElevation (FXObject * , FXSelector , void *)
interpolate z values linear between junctions
Definition at line 1659 of file GNEViewNet.cpp.
References getEdgeAtPopupPosition(), GUIGlObject::getGlID(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), GNEEdge::straightenElevation(), SUMO_TAG_EDGE, and toString().
onCmdToogleSelectEdges()
long GNEViewNet::onCmdToogleSelectEdges (FXObject * , FXSelector , void *)
toogle selet edges
Definition at line 2314 of file GNEViewNet.cpp.
References myMenuCheckSelectEdges, and mySelectEdges.
onCmdToogleShowBubbles()
long GNEViewNet::onCmdToogleShowBubbles (FXObject * , FXSelector , void *)
toogle show bubbles
Definition at line 2325 of file GNEViewNet.cpp.
onCmdToogleShowConnection()
long GNEViewNet::onCmdToogleShowConnection (FXObject * , FXSelector , void *)
toogle show connections
Definition at line 2299 of file GNEViewNet.cpp.
References getNet(), GNENet::initGNEConnections(), myMenuCheckShowConnections, myShowConnections, GUISUMOAbstractView::myVisualizationSettings, GNENet::requireRecompute(), and GUIVisualizationSettings::showLane2Lane.
onCmdTransformPOI()
long GNEViewNet::onCmdTransformPOI (FXObject * , FXSelector , void *)
Transform POI to POILane, and viceversa.
Definition at line 1776 of file GNEViewNet.cpp.
References GNENet::addPOI(), GNENet::deleteShape(), Position::distanceTo(), GNEPOI::getCenteringBoundary(), Shape::getColor(), PointOfInterest::getHeight(), GNEAttributeCarrier::getID(), Shape::getImgFile(), Shape::getLayer(), Shape::getNaviDegree(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), getPOIAtPopupPosition(), getPOILaneAtPopupPosition(), GNEPOI::getPositionInView(), GNELane::getShape(), Shape::getType(), PointOfInterest::getWidth(), GUIGlObjectStorage::gIDStorage, myNet, myUndoList, PositionVector::nearest_offset_to_point2D(), GNEUndoList::p_begin(), GNEUndoList::p_end(), PositionVector::positionAtOffset(), SUMO_TAG_LANE, SUMO_TAG_POILANE, toString(), and WRITE_WARNING.
onConfigure()
long GUISUMOAbstractView::onConfigure (FXObject * , FXSelector , void *) virtual inherited
mouse functions
Definition at line 605 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), GUISUMOAbstractView::checkSnapshots(), GUISUMOAbstractView::doInit(), RGBColor::green(), GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myAmInitialised, GUISUMOAbstractView::myVisualizationSettings, and RGBColor::red().
Referenced by GUISUMOAbstractView::buildViewToolBars().
onDoubleClicked()
long GUISUMOAbstractView::onDoubleClicked (FXObject * , FXSelector , void *) virtual inherited
Definition at line 727 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
onGamingClick()
void GUISUMOAbstractView::onGamingClick (Position) virtual inherited
on gaming click
Reimplemented in GUIViewTraffic.
Definition at line 1143 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildColorRainbow(), and GUISUMOAbstractView::onLeftBtnRelease().
onKeyPress()
long GNEViewNet::onKeyPress (FXObject * o, FXSelector sel, void * data) virtual
called when user press a key
Reimplemented from GUISUMOAbstractView.
Definition at line 1127 of file GNEViewNet.cpp.
References GUISUMOAbstractView::onKeyPress().
onKeyRelease()
long GNEViewNet::onKeyRelease (FXObject * o, FXSelector sel, void * data) virtual
called when user release a key
Reimplemented from GUISUMOAbstractView.
Definition at line 1133 of file GNEViewNet.cpp.
References myAmInRectSelect, and GUISUMOAbstractView::onKeyRelease().
onLeftBtnPress()
long GNEViewNet::onLeftBtnPress (FXObject * , FXSelector , void * eventData) virtual
Reimplemented from GUISUMOAbstractView.
Definition at line 645 of file GNEViewNet.cpp.
References GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::ADDADDITIONAL_INVALID_PARENT, GNEAdditionalFrame::ADDADDITIONAL_SUCCESS, GNECrossingFrame::addCrossing(), GNEPolygonFrame::ADDSHAPE_NEWPOINT, begingMoveSelection(), GNENet::createEdge(), GNENet::createJunction(), GNETLSEditorFrame::editJunction(), GNEFrame::focusUpperElement(), GNEViewParent::getAdditionalFrame(), GNEViewParent::getConnectorFrame(), GNEViewParent::getCrossingFrame(), GNEViewParent::getDeleteFrame(), GNEInspectorFrame::getEdgeTemplate(), GUIGlObject::getGlID(), Named::getID(), NBEdge::getInnerGeometry(), GNEViewParent::getInspectorFrame(), GNEDeleteFrame::getMarkedAttributeCarrier(), GNEEdge::getNBEdge(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectUnderCursor(), GNELane::getParentEdge(), GNEViewParent::getPolygonFrame(), GUISUMOAbstractView::getPositionInformation(), GNEPOI::getPositionInView(), GNEPOILane::getPositionInView(), GNEJunction::getPositionInView(), GNEAdditional::getPositionInView(), GUISelectedStorage::getSelected(), GNEViewParent::getSelectorFrame(), SUMOPolygon::getShape(), GNEAttributeCarrier::getTag(), GNEViewParent::getTLSEditorFrame(), GUIGlObject::getType(), GNEEdge::getVertexIndex(), GNEPoly::getVertexIndex(), GUIGlObjectStorage::gIDStorage, GLO_ADDITIONAL, GLO_CONNECTION, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_CROSSING, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_POLYGON, GNE_MODE_SELECT, GNE_MODE_TLS, gSelected, GNEConnectorFrame::handleLaneClick(), GNEUndoList::hasCommandGroup(), GNEInspectorFrame::inspectElement(), GNEInspectorFrame::inspectMultisection(), GNEShape::isMovementBlocked(), GUISelectedStorage::isSelected(), GNEShape::isShapeBlocked(), GNESelectorFrame::locked(), GUISUMOAbstractView::makeCurrent(), GNEJunction::markAsCreateEdgeSource(), GNEDeleteFrame::markAttributeCarrier(), myAdditionalToMove, myAmInRectSelect, myAutoCreateOppositeEdge, myChainCreateEdge, myCreateEdgeSource, myEdgeToMove, myEditMode, myEditShapePoly, myJunctionToMove, myMovingIndexShape, myMovingOriginalPosition, myMovingOriginalShape, myMovingReference, myMovingSelection, myNet, myPoiLaneToMove, myPoiToMove, myPolyToMove, mySelCorner1, mySelCorner2, mySelectEdges, myUndoList, myViewParent, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEPolygonFrame::processClick(), processClick(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarrier(), GNENet::retrieveAttributeCarriers(), setStatusBarText(), GUISUMOAbstractView::snapToActiveGrid(), SUMO_TAG_EDGE, GUISelectedStorage::toggleSelection(), toString(), GUIGlObjectStorage::unblockObject(), and GNEJunction::unMarkAsCreateEdgeSource().
onLeftBtnRelease()
long GNEViewNet::onLeftBtnRelease (FXObject * obj, FXSelector sel, void * eventData) virtual
called when user releases mouse's left button
Reimplemented from GUISUMOAbstractView.
Definition at line 998 of file GNEViewNet.cpp.
References Boundary::add(), GNEPOI::commitGeometryMoving(), GNEPOILane::commitGeometryMoving(), GNEAdditional::commitGeometryMoving(), GNEJunction::commitGeometryMoving(), GNEPoly::commitShapeChange(), GNEEdge::commitShapeChange(), finishMoveSelection(), GUISUMOAbstractView::getObjectsInBoundary(), GNEViewParent::getSelectorFrame(), GNESelectorFrame::handleIDs(), GUISUMOAbstractView::makeCurrent(), mergeJunctions(), myAdditionalToMove, myAmInRectSelect, myEdgeToMove, myJunctionToMove, myMovingOriginalPosition, myMovingOriginalShape, myMovingSelection, myPoiLaneToMove, myPoiToMove, myPolyToMove, mySelCorner1, mySelCorner2, mySelectEdges, myUndoList, myViewParent, and GUISUMOAbstractView::onLeftBtnRelease().
onMiddleBtnPress()
long GUISUMOAbstractView::onMiddleBtnPress (FXObject * , FXSelector , void *) virtual inherited
Definition at line 694 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
onMiddleBtnRelease()
long GUISUMOAbstractView::onMiddleBtnRelease (FXObject * , FXSelector , void *) virtual inherited
Definition at line 700 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
onMouseLeft()
long GUISUMOAbstractView::onMouseLeft (FXObject * , FXSelector , void *) virtual inherited
Definition at line 762 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
onMouseMove()
long GNEViewNet::onMouseMove (FXObject * obj, FXSelector sel, void * eventData) virtual
called when user moves mouse
Reimplemented from GUISUMOAbstractView.
Definition at line 1065 of file GNEViewNet.cpp.
References GNEViewParent::getDeleteFrame(), GUISUMOAbstractView::getObjectUnderCursor(), GUISUMOAbstractView::getPositionInformation(), GNE_MODE_DELETE, GUIVisualizationSettings::gridXSize, GNEAdditional::isAdditionalBlocked(), GNEShape::isShapeBlocked(), GUISUMOAbstractView::makeCurrent(), GNEPoly::moveEntireShape(), GNEPOI::moveGeometry(), GNEPOILane::moveGeometry(), GNEAdditional::moveGeometry(), GNEJunction::moveGeometry(), moveSelection(), GNEPoly::moveVertexShape(), GNEEdge::moveVertexShape(), myAdditionalToMove, myAmInRectSelect, myEdgeToMove, myEditMode, myJunctionToMove, myMenuCheckMoveElevation, myMovingIndexShape, myMovingOriginalPosition, myMovingOriginalShape, myMovingReference, myMovingSelection, myNet, myPoiLaneToMove, myPoiToMove, myPolyToMove, mySelCorner2, myViewParent, GUISUMOAbstractView::myVisualizationSettings, GUISUMOAbstractView::onMouseMove(), GNENet::retrieveAttributeCarrier(), GUIVisualizationSettings::showGrid, GUISUMOAbstractView::snapToActiveGrid(), GNEDeleteFrame::updateCurrentLabel(), Position::x(), and Position::y().
onMouseWheel()
long GUISUMOAbstractView::onMouseWheel (FXObject * , FXSelector , void * data) virtual inherited
Definition at line 733 of file GUISUMOAbstractView.cpp.
References GUIMainWindow::isGaming(), GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUIPerspectiveChanger::onMouseWheel(), and GUISUMOAbstractView::updatePositionInformation().
Referenced by GUISUMOAbstractView::buildViewToolBars().
onPaint()
long GUISUMOAbstractView::onPaint (FXObject * , FXSelector , void *) virtual inherited
Definition at line 623 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myAmInitialised, and GUISUMOAbstractView::paintGL().
Referenced by GUISUMOAbstractView::buildViewToolBars(), and updateModeSpecificControls().
onRightBtnPress()
long GNEViewNet::onRightBtnPress (FXObject * obj, FXSelector sel, void * eventData) virtual
called when user press mouse's right button
Reimplemented from GUISUMOAbstractView.
Definition at line 1041 of file GNEViewNet.cpp.
References GNEFrame::getDrawingMode(), GNEViewParent::getPolygonFrame(), GNE_MODE_POLYGON, GNEFrame::DrawingMode::isDrawing(), myEditMode, myViewParent, GUISUMOAbstractView::onRightBtnPress(), and GNEFrame::DrawingMode::removeLastPoint().
onRightBtnRelease()
long GNEViewNet::onRightBtnRelease (FXObject * obj, FXSelector sel, void * eventData) virtual
called when user releases mouse's right button
Reimplemented from GUISUMOAbstractView.
Definition at line 1054 of file GNEViewNet.cpp.
References GNEFrame::getDrawingMode(), GNEViewParent::getPolygonFrame(), GNE_MODE_POLYGON, GNEFrame::DrawingMode::isDrawing(), myEditMode, myViewParent, and GUISUMOAbstractView::onRightBtnRelease().
openObjectDialog()
void GUISUMOAbstractView::openObjectDialog () virtual inherited
Definition at line 768 of file GUISUMOAbstractView.cpp.
References GUIGlObjectStorage::getNetObject(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectUnderCursor(), GUIGlObject::getPopUpMenu(), GUISUMOAbstractView::getPositionInformation(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myAmInitialised, GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myPopup, GUISUMOAbstractView::myPopupPosition, GUIPerspectiveChanger::onRightBtnRelease(), and GUIGlObjectStorage::unblockObject().
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUISUMOAbstractView::onRightBtnRelease().
operator=()
GNEViewNet& GNEViewNet::operator= (const GNEViewNet &) private delete
Invalidated assignment operator.
p2m()
double GUISUMOAbstractView::p2m (double pixel) const inherited
pixels-to-meters conversion method
Definition at line 548 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), and GUISUMOAbstractView::myChanger.
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), doPaintGL(), GUISUMOAbstractView::drawDecals(), GUIDanielPerspectiveChanger::move(), and GUISUMOAbstractView::showToolTipFor().
paintGL()
void GUISUMOAbstractView::paintGL () protected inherited
performs the painting of the simulation
Definition at line 259 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUISUMOAbstractView::applyGLTransform(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::displayLegend(), GUIVisualizationSettings::dither, GUISUMOAbstractView::doPaintGL(), GUISUMOAbstractView::getObjectUnderCursor(), GUISUMOAbstractView::getTrackedID(), GUIPerspectiveChanger::getViewport(), RGBColor::green(), GUIGlObject::INVALID_ID, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myUseToolTips, GUISUMOAbstractView::myVisualizationSettings, RGBColor::red(), GUIVisualizationSettings::showSizeLegend, and GUISUMOAbstractView::showToolTipFor().
Referenced by GUISUMOAbstractView::onPaint().
paintGLGrid()
void GUISUMOAbstractView::paintGLGrid () protected inherited
paints a grid
Definition at line 437 of file GUISUMOAbstractView.cpp.
References GUIVisualizationSettings::addSize, GUIVisualizationSizeSettings::getExaggeration(), GUIPerspectiveChanger::getViewport(), GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myVisualizationSettings, GUIVisualizationSettings::scale, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
processClick()
void GNEViewNet::processClick (FXEvent * e, void * data) private
Auxiliar function used by onLeftBtnPress(...)
Definition at line 2176 of file GNEViewNet.cpp.
References GUISUMOAbstractView::destroyPopup(), GUISUMOAbstractView::myChanger, and GUIPerspectiveChanger::onLeftBtnPress().
Referenced by onLeftBtnPress().
recenterView()
void GUISUMOAbstractView::recenterView () virtual inherited
recenters the view
Definition at line 554 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myGrid, and GUIPerspectiveChanger::setViewport().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIGlChildWindow::onCmdRecenterView(), GUIDanielPerspectiveChanger::onKeyPress(), and GUICompleteSchemeStorage::setViewport().
remove() [1/2]
void GUISUMOAbstractView::remove (GUIDialog_EditViewport *) inherited
remove viewport
Definition at line 1103 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myViewportChooser.
Referenced by GUIDialog_ViewSettings::~GUIDialog_ViewSettings().
remove() [2/2]
void GUISUMOAbstractView::remove (GUIDialog_ViewSettings *) inherited
remove view settings
Definition at line 1109 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myVisualizationChanger.
removeAdditionalGLVisualisation()
bool GUISUMOAbstractView::removeAdditionalGLVisualisation (const GUIGlObject *const which) inherited
Removes an object from the list of objects that show additional things.
Parameters
[in] which The object to remoe
Returns
True if the object was known, false otherwise
See also
GUIGlObject::drawGLAdditional
Definition at line 1293 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myAdditionallyDrawn.
Referenced by GUISUMOAbstractView::buildColorRainbow(), GUIVehicle::drawOutsideNetwork(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIPerson::removeActiveAddVisualisation().
removeRestrictedLane()
bool GNEViewNet::removeRestrictedLane (SUMOVehicleClass vclass) private
remove restricted lane
Definition at line 2095 of file GNEViewNet.cpp.
References getLaneAtPopupPosition(), OptionsCont::getOptions(), GNELane::getParentEdge(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::removeRestrictedLane(), GNENet::retrieveEdge(), GNENet::retrieveEdges(), GNENet::retrieveLanes(), toString(), and WRITE_WARNING.
Referenced by onCmdRemoveRestrictedLaneBikelane(), onCmdRemoveRestrictedLaneBuslane(), and onCmdRemoveRestrictedLaneSidewalk().
restrictLane()
bool GNEViewNet::restrictLane (SUMOVehicleClass vclass) private
restrict lane
Definition at line 1935 of file GNEViewNet.cpp.
References OptionsCont::getBool(), getLaneAtPopupPosition(), OptionsCont::getOptions(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::restrictLane(), GNENet::retrieveEdge(), GNENet::retrieveLanes(), toString(), and WRITE_WARNING.
Referenced by onCmdRestrictLaneBikelane(), onCmdRestrictLaneBuslane(), and onCmdRestrictLaneSidewalk().
saveFrame()
void GUISUMOAbstractView::saveFrame (const std::string & destFile, FXColor * buf) virtual inherited
Adds a frame to a video snapshot which will be initialized if neccessary.
Reimplemented in GUIViewTraffic.
Definition at line 984 of file GUISUMOAbstractView.cpp.
References UNUSED_PARAMETER.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUISUMOAbstractView::makeSnapshot().
screenPos2NetPos()
Position GUISUMOAbstractView::screenPos2NetPos (int x, int y) const inherited
Translate screen position to network position.
Definition at line 205 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), GUISUMOAbstractView::myChanger, Boundary::xmin(), and Boundary::ymin().
Referenced by doPaintGL(), GUISUMOAbstractView::drawDecals(), and GUISUMOAbstractView::getPositionInformation().
selectEdges()
bool GNEViewNet::selectEdges ()
whether inspection, selection and inversion should apply to edges or to lanes
Definition at line 328 of file GNEViewNet.cpp.
References mySelectEdges.
Referenced by GNESelectorFrame::onCmdInvert().
setApplicationSnapshots()
void GUISUMOAbstractView::setApplicationSnapshots (std::set< SUMOTime > * snapshots, FXMutex * lock) inline inherited
add snapshot synchronization
Definition at line 271 of file GUISUMOAbstractView.h.
References GUISUMOAbstractView::myApplicationSnapshots, and GUISUMOAbstractView::myApplicationSnapshotsLock.
Referenced by GUIApplicationWindow::openNewView().
setColorScheme()
bool GNEViewNet::setColorScheme (const std::string & name) virtual
set color scheme
Reimplemented from GUISUMOAbstractView.
Definition at line 265 of file GNEViewNet.cpp.
References GUICompleteSchemeStorage::contains(), GUICompleteSchemeStorage::get(), GUIDialog_ViewSettings::getCurrentScheme(), gSchemeStorage, GUISUMOAbstractView::myVisualizationChanger, GUISUMOAbstractView::myVisualizationSettings, and GUIDialog_ViewSettings::setCurrentScheme().
setDelay()
void GUISUMOAbstractView::setDelay (double delay) inherited
Sets the delay of the parent application.
Definition at line 1343 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myApp, and GUIMainWindow::setDelay().
Referenced by GUIDialog_ViewSettings::loadSettings().
setEditMode()
void GNEViewNet::setEditMode (EditMode mode) private
set edit mode
Definition at line 2350 of file GNEViewNet.cpp.
References abortOperation(), GNENet::computeEverything(), GNEFrame::focusUpperElement(), GNE_MODE_CONNECT, GNE_MODE_TLS, GUISUMOAbstractView::myApp, myCurrentFrame, myEditMode, myNet, setStatusBarText(), stopEditCustomShape(), and updateModeSpecificControls().
Referenced by onCmdSetModeAdditional(), onCmdSetModeConnect(), onCmdSetModeCreateEdge(), onCmdSetModeCrossing(), onCmdSetModeDelete(), onCmdSetModeInspect(), onCmdSetModeMove(), onCmdSetModePolygon(), onCmdSetModeSelect(), onCmdSetModeTLS(), setEditModeFromHotkey(), and stopEditCustomShape().
setEditModeFromHotkey()
void GNEViewNet::setEditModeFromHotkey (FXushort selid)
sets edit mode (from hotkey)
Parameters
[in] selid An id MID_GNE_SETMODE_<foo> as defined in GUIAppEnum
Definition at line 1232 of file GNEViewNet.cpp.
References GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_CROSSING, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_POLYGON, GNE_MODE_SELECT, GNE_MODE_TLS, MID_GNE_SETMODE_ADDITIONAL, MID_GNE_SETMODE_CONNECT, MID_GNE_SETMODE_CREATE_EDGE, MID_GNE_SETMODE_CROSSING, MID_GNE_SETMODE_DELETE, MID_GNE_SETMODE_INSPECT, MID_GNE_SETMODE_MOVE, MID_GNE_SETMODE_POLYGON, MID_GNE_SETMODE_SELECT, MID_GNE_SETMODE_TLS, and setEditMode().
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), GNEApplicationWindow::onCmdSetMode(), and startEditCustomShape().
setSelectionScaling()
void GNEViewNet::setSelectionScaling (double selectionScale)
set selection scaling
Definition at line 352 of file GNEViewNet.cpp.
References GUISUMOAbstractView::myVisualizationSettings, and GUIVisualizationSettings::selectionScale.
Referenced by GNESelectorFrame::onCmdScaleSelection().
setStatusBarText()
void GNEViewNet::setStatusBarText (const std::string & text)
set staturBar text
Definition at line 322 of file GNEViewNet.cpp.
References GUISUMOAbstractView::myApp, and GUIMainWindow::setStatusBarText().
Referenced by GNEAdditionalFrame::addAdditional(), GNETLSEditorFrame::editJunction(), GNEConnectorFrame::handleLaneClick(), hotkeyDel(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdDefSwitch(), GNEConnectorFrame::onCmdOK(), onLeftBtnPress(), GNEPolygonFrame::processClick(), setEditMode(), GNEPolygonFrame::ShapeAttributes::showWarningMessage(), and GNEAdditionalFrame::AdditionalAttributes::showWarningMessage().
setViewportFromTo()
void GUISUMOAbstractView::setViewportFromTo (const Position & lookFrom, const Position & lookAt) virtual inherited
applies the given viewport settings
Definition at line 1070 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, GUIPerspectiveChanger::setViewportFrom(), Position::x(), Position::y(), and Position::z().
Referenced by GUISettingsHandler::applyViewport(), GUISUMOAbstractView::buildViewToolBars(), GUISUMOAbstractView::copyViewportTo(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIDialog_EditViewport::onCmdCancel(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), TraCIServerAPI_GUI::processSet(), and GUICompleteSchemeStorage::setViewport().
setWindowCursorPosition()
void GUISUMOAbstractView::setWindowCursorPosition (FXint x, FXint y) inherited
Returns the information whether rotation is allowd.
Note
disabled Returns the gl-id of the object under the given coordinates
Definition at line 591 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myMouseHotspotX, GUISUMOAbstractView::myMouseHotspotY, GUISUMOAbstractView::myWindowCursorPositionX, and GUISUMOAbstractView::myWindowCursorPositionY.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUIDanielPerspectiveChanger::onMouseMove().
showConnections()
bool GNEViewNet::showConnections ()
show connections over junctions
Definition at line 334 of file GNEViewNet.cpp.
References GNE_MODE_CONNECT, myEditMode, myMenuCheckShowConnections, GUISUMOAbstractView::myVisualizationSettings, and GUIVisualizationSettings::showLane2Lane.
Referenced by GNEConnection::drawGL().
showJunctionAsBubbles()
bool GNEViewNet::showJunctionAsBubbles () const
return true if junction must be showed as bubbles
Definition at line 364 of file GNEViewNet.cpp.
References GNE_MODE_MOVE, myEditMode, and myMenuCheckShowBubbleOverJunction.
Referenced by GNEJunction::drawGL().
showLockIcon()
bool GNEViewNet::showLockIcon () const
check if lock icon should be visible
Definition at line 1296 of file GNEViewNet.cpp.
References GNE_MODE_ADDITIONAL, GNE_MODE_INSPECT, GNE_MODE_MOVE, and myEditMode.
Referenced by GNEShape::drawLockIcon(), and GNEAdditional::drawLockIcon().
showToolTipFor()
void GUISUMOAbstractView::showToolTipFor (const GUIGlID id) protected inherited
invokes the tooltip for the given object
Definition at line 423 of file GUISUMOAbstractView.cpp.
References Position::add(), RGBColor::BLACK, GLHelper::drawTextBox(), GUIGlObject::getFullName(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPositionInformation(), GUIGlObjectStorage::gIDStorage, GLO_MAX, GUISUMOAbstractView::p2m(), and GUIGlObjectStorage::unblockObject().
Referenced by GUISUMOAbstractView::paintGL().
showToolTips()
void GUISUMOAbstractView::showToolTips (bool val) inherited
show tool tips
Definition at line 1085 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myUseToolTips.
Referenced by GUISUMOAbstractView::endSnapshot(), and GUIGlChildWindow::onCmdShowToolTips().
showViewportEditor()
void GUISUMOAbstractView::showViewportEditor () virtual inherited
show viewport editor
Definition at line 1061 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::getViewportEditor(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), Position::INVALID, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myViewportChooser, GUIDialog_EditViewport::setOldValues(), and GUIDialog_EditViewport::show().
Referenced by GUISUMOAbstractView::endSnapshot(), GUIGlChildWindow::onCmdEditViewport(), and GNEApplicationWindow::onCmdEditViewport().
showViewschemeEditor()
void GUISUMOAbstractView::showViewschemeEditor () inherited
show viewsscheme editor
Definition at line 1035 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myDecals, GUISUMOAbstractView::myDecalsLock, GUISUMOAbstractView::myVisualizationChanger, GUISUMOAbstractView::myVisualizationSettings, GUIDialog_ViewSettings::setCurrent(), and GUIDialog_ViewSettings::show().
Referenced by GUISUMOAbstractView::endSnapshot(), GUIGlChildWindow::onCmdEditViewScheme(), and GUIDanielPerspectiveChanger::onKeyPress().
snapToActiveGrid()
Position GUISUMOAbstractView::snapToActiveGrid (const Position & pos) const inherited
Returns a position that is mapped to the closest grid point if the grid is active.
Definition at line 192 of file GUISUMOAbstractView.cpp.
References GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, GUISUMOAbstractView::myVisualizationSettings, Position::setx(), Position::sety(), GUIVisualizationSettings::showGrid, Position::x(), and Position::y().
Referenced by GNEAdditionalFrame::addAdditional(), doPaintGL(), onLeftBtnPress(), and onMouseMove().
startEditCustomShape()
void GNEViewNet::startEditCustomShape (GNENetElement * element, const PositionVector & shape, bool fill)
start edit custom shape
Definition at line 370 of file GNEViewNet.cpp.
References GNENet::addPolygonForEditShapes(), MID_GNE_SETMODE_MOVE, myEditMode, myEditShapePoly, myNet, myPreviousEditMode, and setEditModeFromHotkey().
Referenced by onCmdEditConnectionShape(), onCmdEditCrossingShape(), and onCmdEditJunctionShape().
startTrack()
void GUISUMOAbstractView::startTrack (int) virtual inherited
star track
Reimplemented in GUIViewTraffic.
Definition at line 1127 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildColorRainbow(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), and TraCIServerAPI_GUI::processSet().
stopEditCustomShape()
void GNEViewNet::stopEditCustomShape ()
edit edit shape
Definition at line 384 of file GNEViewNet.cpp.
References myEditMode, myEditShapePoly, myNet, myPreviousEditMode, GNENet::removePolygonForEditShapes(), and setEditMode().
Referenced by abortOperation(), hotkeyEnter(), and setEditMode().
stopTrack()
void GUISUMOAbstractView::stopTrack () virtual inherited
stop track
Reimplemented in GUIViewTraffic.
Definition at line 1132 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildColorRainbow(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), and TraCIServerAPI_GUI::processSet().
updateControls()
void GNEViewNet::updateControls ()
update control contents after undo/redo or recompute
Definition at line 2756 of file GNEViewNet.cpp.
References GNEViewParent::getInspectorFrame(), GNE_MODE_INSPECT, myEditMode, and myViewParent.
Referenced by GNEApplicationWindow::updateControls().
updateModeSpecificControls()
void GNEViewNet::updateModeSpecificControls () private
updates mode specific controls
Definition at line 2448 of file GNEViewNet.cpp.
References GNEFrame::focusUpperElement(), GNEViewParent::getAdditionalFrame(), GNEViewParent::getConnectorFrame(), GNEViewParent::getCrossingFrame(), GNEViewParent::getDeleteFrame(), GNEViewParent::getInspectorFrame(), GNEViewParent::getPolygonFrame(), GNEViewParent::getSelectorFrame(), GNEViewParent::getTLSEditorFrame(), GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_CROSSING, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_POLYGON, GNE_MODE_SELECT, GNE_MODE_TLS, GNEViewParent::hideAllFrames(), myAutoCreateOppositeEdge, myChainCreateEdge, myCurrentFrame, myEditMode, myEditModeAdditional, myEditModeConnection, myEditModeCreateEdge, myEditModeCrossing, myEditModeDelete, myEditModeInspect, myEditModeMove, myEditModePolygon, myEditModeSelect, myEditModeTrafficLight, myMenuCheckChangeAllPhases, myMenuCheckExtendToEdgeNodes, myMenuCheckMoveElevation, myMenuCheckSelectEdges, myMenuCheckShowBubbleOverJunction, myMenuCheckShowConnections, myMenuCheckShowGrid, myMenuCheckWarnAboutMerge, myToolbar, myViewParent, GUISUMOAbstractView::myVisualizationSettings, GUISUMOAbstractView::onPaint(), MFXCheckableButton::setChecked(), GNESelectorFrame::show(), GNEInspectorFrame::show(), GNEPolygonFrame::show(), GNEFrame::show(), GNEAdditionalFrame::show(), and GUIVisualizationSettings::showGrid.
Referenced by setEditMode().
updatePositionInformation()
void GUISUMOAbstractView::updatePositionInformation () const protected inherited
update position information
Definition at line 227 of file GUISUMOAbstractView.cpp.
References GeoConvHelper::cartesian2geo(), GUIMainWindow::getCartesianLabel(), GeoConvHelper::getFinal(), GUIMainWindow::getGeoLabel(), GUISUMOAbstractView::getPositionInformation(), gPrecisionGeo, GUISUMOAbstractView::myApp, toString(), Position::x(), and Position::y().
Referenced by GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::onMouseMove(), and GUISUMOAbstractView::onMouseWheel().
updateToolTip()
void GUISUMOAbstractView::updateToolTip () inherited
A method that updates the tooltip.
Definition at line 177 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myUseToolTips.
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIDanielPerspectiveChanger::onKeyPress(), GUIDanielPerspectiveChanger::onMouseMove(), and GUIDanielPerspectiveChanger::onMouseWheel().
Field Documentation
myAdditionallyDrawn
std::map<const GUIGlObject*, int> GUISUMOAbstractView::myAdditionallyDrawn protected inherited
List of objects for which GUIGlObject::drawGLAdditional is called.
Definition at line 452 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addAdditionalGLVisualisation(), GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::isAdditionalGLVisualisationEnabled(), and GUISUMOAbstractView::removeAdditionalGLVisualisation().
myAdditionalToMove
GNEAdditional* GNEViewNet::myAdditionalToMove private
the stoppingPlace element which shape is being moved
Definition at line 455 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myAmInitialised
bool GUISUMOAbstractView::myAmInitialised protected inherited
Internal information whether doInit() was called.
Definition at line 420 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::onPaint(), and GUISUMOAbstractView::openObjectDialog().
myAmInRectSelect
bool GNEViewNet::myAmInRectSelect private
whether we have started rectangle-selection
Definition at line 501 of file GNEViewNet.h.
Referenced by abortOperation(), doPaintGL(), onKeyRelease(), onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myApp
GUIMainWindow* GUISUMOAbstractView::myApp protected inherited
The application.
Definition at line 390 of file GUISUMOAbstractView.h.
Referenced by doPaintGL(), GUISUMOAbstractView::getDelay(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnRelease(), GUISUMOAbstractView::openObjectDialog(), GUIViewTraffic::saveFrame(), GUIViewTraffic::setColorScheme(), GUISUMOAbstractView::setDelay(), setEditMode(), setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
myApplicationSnapshots
std::set<SUMOTime>* GUISUMOAbstractView::myApplicationSnapshots protected inherited
Definition at line 442 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addSnapshot(), GUISUMOAbstractView::checkSnapshots(), and GUISUMOAbstractView::setApplicationSnapshots().
myApplicationSnapshotsLock
FXMutex* GUISUMOAbstractView::myApplicationSnapshotsLock protected inherited
Definition at line 446 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addSnapshot(), GUISUMOAbstractView::checkSnapshots(), and GUISUMOAbstractView::setApplicationSnapshots().
myAutoCreateOppositeEdge
FXMenuCheck* GNEViewNet::myAutoCreateOppositeEdge private
Definition at line 419 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onLeftBtnPress(), and updateModeSpecificControls().
myChainCreateEdge
FXMenuCheck* GNEViewNet::myChainCreateEdge private
whether the endpoint for a created edge should be set as the new source
Definition at line 418 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onLeftBtnPress(), and updateModeSpecificControls().
myChanger
GUIPerspectiveChanger* GUISUMOAbstractView::myChanger protected inherited
The perspective changer.
Definition at line 399 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::copyViewportTo(), GUISUMOAbstractView::getChanger(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getViewportEditor(), GUISUMOAbstractView::getVisibleBoundary(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onKeyPress(), GUISUMOAbstractView::onKeyRelease(), GUISUMOAbstractView::onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseMove(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnPress(), GUISUMOAbstractView::onRightBtnRelease(), GUISUMOAbstractView::openObjectDialog(), GUISUMOAbstractView::p2m(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::paintGLGrid(), processClick(), GUISUMOAbstractView::recenterView(), GUISUMOAbstractView::screenPos2NetPos(), GUISUMOAbstractView::setViewportFromTo(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
myCreateEdgeSource
GNEJunction* GNEViewNet::myCreateEdgeSource private
source junction for new edge 0 if no edge source is selected an existing (or newly created) junction otherwise
Definition at line 415 of file GNEViewNet.h.
Referenced by abortOperation(), and onLeftBtnPress().
myCurrentFrame
GNEFrame* GNEViewNet::myCurrentFrame private
the current frame
Definition at line 389 of file GNEViewNet.h.
Referenced by hotkeyFocusFrame(), setEditMode(), and updateModeSpecificControls().
myDecals
std::vector<Decal> GUISUMOAbstractView::myDecals protected inherited
Definition at line 434 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addDecals(), GUISUMOAbstractView::drawDecals(), GUISUMOAbstractView::showViewschemeEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
myDecalsLock
MFXMutex GUISUMOAbstractView::myDecalsLock protected inherited
The mutex to use before accessing the decals list in order to avoid thread conficts.
Definition at line 437 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::drawDecals(), and GUISUMOAbstractView::showViewschemeEditor().
myEdgeToMove
GNEEdge* GNEViewNet::myEdgeToMove private
the edge of which geometry is being moved
Definition at line 440 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myEditAdditionalModeNames
StringBijection<EditMode> GNEViewNet::myEditAdditionalModeNames private
stringBijection for edit additional mode names
Definition at line 552 of file GNEViewNet.h.
myEditMode
EditMode GNEViewNet::myEditMode private
the current edit mode
Definition at line 386 of file GNEViewNet.h.
Referenced by abortOperation(), doPaintGL(), getCurrentEditMode(), hotkeyDel(), hotkeyEnter(), onLeftBtnPress(), onMouseMove(), onRightBtnPress(), onRightBtnRelease(), setEditMode(), showConnections(), showJunctionAsBubbles(), showLockIcon(), startEditCustomShape(), stopEditCustomShape(), updateControls(), and updateModeSpecificControls().
myEditModeAdditional
MFXCheckableButton* GNEViewNet::myEditModeAdditional private
chekable button for edit mode additional
Definition at line 537 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeConnection
MFXCheckableButton* GNEViewNet::myEditModeConnection private
chekable button for edit mode connection
Definition at line 531 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeCreateEdge
MFXCheckableButton* GNEViewNet::myEditModeCreateEdge private
Definition at line 516 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeCrossing
MFXCheckableButton* GNEViewNet::myEditModeCrossing private
chekable button for edit mode crossing
Definition at line 540 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeDelete
MFXCheckableButton* GNEViewNet::myEditModeDelete private
chekable button for edit mode delete
Definition at line 522 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeInspect
MFXCheckableButton* GNEViewNet::myEditModeInspect private
chekable button for edit mode inspect
Definition at line 525 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeMove
MFXCheckableButton* GNEViewNet::myEditModeMove private
chekable button for edit mode move
Definition at line 519 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeNames
StringBijection<EditMode> GNEViewNet::myEditModeNames private
since we cannot switch on strings we map the mode names to an enum
stringBijection for edit mode names
Definition at line 549 of file GNEViewNet.h.
Referenced by buildEditModeControls().
myEditModePolygon
MFXCheckableButton* GNEViewNet::myEditModePolygon private
chekable button for edit mode polygon
Definition at line 543 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeSelect
MFXCheckableButton* GNEViewNet::myEditModeSelect private
chekable button for edit mode select
Definition at line 528 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditModeTrafficLight
MFXCheckableButton* GNEViewNet::myEditModeTrafficLight private
chekable button for edit mode traffic light
Definition at line 534 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myEditShapePoly
GNEPoly* GNEViewNet::myEditShapePoly private
Definition at line 561 of file GNEViewNet.h.
Referenced by hotkeyEnter(), onCmdClosePolygon(), onCmdDeleteGeometryPoint(), onCmdOpenPolygon(), onCmdSetFirstGeometryPoint(), onCmdSimplifyShape(), onLeftBtnPress(), startEditCustomShape(), and stopEditCustomShape().
myGrid
SUMORTree* GUISUMOAbstractView::myGrid protected inherited
The visualization speed-up.
Definition at line 396 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getGridWidth(), GUISUMOAbstractView::makeSnapshot(), and GUISUMOAbstractView::recenterView().
myInEditMode
bool GUISUMOAbstractView::myInEditMode protected inherited
Information whether too-tip informations shall be generated.
Definition at line 402 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::isInEditMode().
myJunctionToMove
GNEJunction* GNEViewNet::myJunctionToMove private
the Junction to be moved.
Definition at line 437 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myMenuCheckChangeAllPhases
FXMenuCheck* GNEViewNet::myMenuCheckChangeAllPhases private
menu check to set change all phases
Definition at line 401 of file GNEViewNet.h.
Referenced by buildEditModeControls(), changeAllPhases(), and updateModeSpecificControls().
myMenuCheckExtendToEdgeNodes
FXMenuCheck* GNEViewNet::myMenuCheckExtendToEdgeNodes private
menu check to extend to edge nodes
Definition at line 398 of file GNEViewNet.h.
Referenced by autoSelectNodes(), buildEditModeControls(), and updateModeSpecificControls().
myMenuCheckMoveElevation
FXMenuCheck* GNEViewNet::myMenuCheckMoveElevation private
apply movement to elevation
Definition at line 431 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onMouseMove(), and updateModeSpecificControls().
myMenuCheckSelectEdges
FXMenuCheck* GNEViewNet::myMenuCheckSelectEdges private
menu check to select only edges
Definition at line 392 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onCmdToogleSelectEdges(), and updateModeSpecificControls().
myMenuCheckShowBubbleOverJunction
FXMenuCheck* GNEViewNet::myMenuCheckShowBubbleOverJunction private
show connection as buuble in "Move" mode.
Definition at line 428 of file GNEViewNet.h.
Referenced by buildEditModeControls(), showJunctionAsBubbles(), and updateModeSpecificControls().
myMenuCheckShowConnections
FXMenuCheck* GNEViewNet::myMenuCheckShowConnections private
menu check to show connections
Definition at line 395 of file GNEViewNet.h.
Referenced by buildEditModeControls(), doPaintGL(), onCmdToogleShowConnection(), showConnections(), and updateModeSpecificControls().
myMenuCheckShowGrid
FXMenuCheck* GNEViewNet::myMenuCheckShowGrid private
show grid button
Definition at line 404 of file GNEViewNet.h.
Referenced by buildEditModeControls(), doPaintGL(), onCmdShowGrid(), and updateModeSpecificControls().
myMenuCheckWarnAboutMerge
FXMenuCheck* GNEViewNet::myMenuCheckWarnAboutMerge private
whether we should warn about merging junctions
Definition at line 425 of file GNEViewNet.h.
Referenced by buildEditModeControls(), mergeJunctions(), and updateModeSpecificControls().
myMouseHotspotX
int GUISUMOAbstractView::myMouseHotspotX protected inherited
Offset to the mouse-hotspot from the mouse position.
Definition at line 405 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::setWindowCursorPosition().
myMouseHotspotY
int GUISUMOAbstractView::myMouseHotspotY protected inherited
Definition at line 405 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::setWindowCursorPosition().
myMovingIndexShape
int GNEViewNet::myMovingIndexShape private
current index of shape that are being moved
Definition at line 468 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), and onMouseMove().
myMovingOriginalPosition
Position GNEViewNet::myMovingOriginalPosition private
original Position of element before moving (needed for commmit position changes)
Definition at line 461 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myMovingOriginalPositionOppositeEdge
Position GNEViewNet::myMovingOriginalPositionOppositeEdge private
Definition at line 471 of file GNEViewNet.h.
myMovingOriginalShape
PositionVector GNEViewNet::myMovingOriginalShape private
Shape of elements before moving (needed for commmit shape changes)
Definition at line 464 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myMovingOriginalShape2
PositionVector GNEViewNet::myMovingOriginalShape2 private
Definition at line 465 of file GNEViewNet.h.
myMovingOriginalShapenOppositeEdge
PositionVector GNEViewNet::myMovingOriginalShapenOppositeEdge private
Definition at line 474 of file GNEViewNet.h.
myMovingReference
Position GNEViewNet::myMovingReference private
variable for calculating moving offset (Used when user doesn't click exactly over the center of shape)
Definition at line 458 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), and onMouseMove().
myMovingSelection
bool GNEViewNet::myMovingSelection private
whether a selection is being moved
Definition at line 477 of file GNEViewNet.h.
Referenced by begingMoveSelection(), finishMoveSelection(), onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myNet
GNENet* GNEViewNet::myNet private
Pointer to current net. (We are not responsible for deletion)
Definition at line 383 of file GNEViewNet.h.
Referenced by addRestrictedLane(), begingMoveSelection(), buildColorRainbow(), deleteSelectedAdditionals(), deleteSelectedConnections(), deleteSelectedCrossings(), deleteSelectedEdges(), deleteSelectedJunctions(), deleteSelectedLanes(), deleteSelectedShapes(), getNet(), mergeJunctions(), onCmdAddReversedEdge(), onCmdClearConnections(), onCmdDuplicateLane(), onCmdReplaceJunction(), onCmdResetConnections(), onCmdReverseEdge(), onCmdSmoothEdges(), onCmdSmoothEdgesElevation(), onCmdSplitEdge(), onCmdSplitEdgeBidi(), onCmdStraightenEdges(), onCmdStraightenEdgesElevation(), onCmdTransformPOI(), onLeftBtnPress(), onMouseMove(), removeRestrictedLane(), restrictLane(), setEditMode(), startEditCustomShape(), and stopEditCustomShape().
myOppositeEdgeToMove
GNEEdge* GNEViewNet::myOppositeEdgeToMove private
the edge of which geometry is being moved
Definition at line 443 of file GNEViewNet.h.
myOriginPositionOfMovedJunctions
std::map<GNEJunction*, Position> GNEViewNet::myOriginPositionOfMovedJunctions private
Selected Junctions that are being moved.
NOTE: IN the future will be changed to std::map<GNENetElement*, Position>
Definition at line 481 of file GNEViewNet.h.
Referenced by begingMoveSelection(), finishMoveSelection(), and moveSelection().
myOriginShapesMovedEntireShapes
std::map<GNEEdge*, PositionVector> GNEViewNet::myOriginShapesMovedEntireShapes private
Selected Edges that are being moved < Edge, PositionVector >
Definition at line 484 of file GNEViewNet.h.
Referenced by begingMoveSelection(), finishMoveSelection(), and moveSelection().
myOriginShapesMovedPartialShapes
std::map<GNEEdge*, movingEdges> GNEViewNet::myOriginShapesMovedPartialShapes private
Definition at line 493 of file GNEViewNet.h.
Referenced by begingMoveSelection(), finishMoveSelection(), and moveSelection().
myParent
GUIGlChildWindow* GUISUMOAbstractView::myParent protected inherited
The parent window.
Definition at line 393 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getColoringSchemesCombo().
myPoiLaneToMove
GNEPOILane* GNEViewNet::myPoiLaneToMove private
the poiLane which is being moved
Definition at line 452 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myPoiToMove
GNEPOI* GNEViewNet::myPoiToMove private
the poi which is being moved
Definition at line 449 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myPolyDrawLock
MFXMutex GUISUMOAbstractView::myPolyDrawLock mutable protected inherited
poly draw lock
Definition at line 449 of file GUISUMOAbstractView.h.
myPolyToMove
GNEPoly* GNEViewNet::myPolyToMove private
the poly of which geometry is being moved
Definition at line 446 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
myPopup
GUIGLObjectPopupMenu* GUISUMOAbstractView::myPopup protected inherited
The current popup-menu.
Definition at line 408 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::destroyPopup(), GUISUMOAbstractView::onKeyPress(), GUISUMOAbstractView::onKeyRelease(), GUISUMOAbstractView::onMouseMove(), GUISUMOAbstractView::openObjectDialog(), and GUISUMOAbstractView::~GUISUMOAbstractView().
myPopupPosition
Position GUISUMOAbstractView::myPopupPosition protected inherited
The current popup-menu position.
Definition at line 411 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::destroyPopup(), GUISUMOAbstractView::getPopupPosition(), and GUISUMOAbstractView::openObjectDialog().
myPreviousEditMode
EditMode GNEViewNet::myPreviousEditMode private
the previous edit mode before edit junction's shapes
Definition at line 564 of file GNEViewNet.h.
Referenced by startEditCustomShape(), and stopEditCustomShape().
mySelCorner1
Position GNEViewNet::mySelCorner1 private
firstcorner of the rectangle-selection
Definition at line 504 of file GNEViewNet.h.
Referenced by doPaintGL(), onLeftBtnPress(), and onLeftBtnRelease().
mySelCorner2
Position GNEViewNet::mySelCorner2 private
second corner of the rectangle-selection
Definition at line 507 of file GNEViewNet.h.
Referenced by doPaintGL(), onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
mySelectEdges
bool GNEViewNet::mySelectEdges private
flag to check if select edges is enabled
Definition at line 410 of file GNEViewNet.h.
Referenced by onCmdToogleSelectEdges(), onLeftBtnPress(), onLeftBtnRelease(), and selectEdges().
myShowConnections
bool GNEViewNet::myShowConnections private
whether show connections has been activated once
Definition at line 407 of file GNEViewNet.h.
Referenced by onCmdToogleShowConnection().
mySnapshots
std::map<SUMOTime, std::vector<std::string> > GUISUMOAbstractView::mySnapshots protected inherited
Snapshots.
Definition at line 441 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addSnapshot(), and GUISUMOAbstractView::checkSnapshots().
mySnapshotsLock
MFXMutex GUISUMOAbstractView::mySnapshotsLock protected inherited
The mutex to use before accessing the decals list in order to avoid thread conficts.
Definition at line 445 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addSnapshot(), and GUISUMOAbstractView::checkSnapshots().
myTestingHeight
int GNEViewNet::myTestingHeight private
Height of viewNet in testing mode.
Definition at line 576 of file GNEViewNet.h.
Referenced by doPaintGL().
myTestingMode
bool GNEViewNet::myTestingMode private
Definition at line 570 of file GNEViewNet.h.
Referenced by doPaintGL().
myTestingWidth
int GNEViewNet::myTestingWidth private
Width of viewNet in testing mode.
Definition at line 573 of file GNEViewNet.h.
Referenced by doPaintGL().
myToolbar
FXToolBar* GNEViewNet::myToolbar private
a reference to the toolbar in myParent
Definition at line 511 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
myUndoList
GNEUndoList* GNEViewNet::myUndoList private
a reference to the undolist maintained in the application
Definition at line 556 of file GNEViewNet.h.
Referenced by abortOperation(), addRestrictedLane(), deleteSelectedAdditionals(), deleteSelectedConnections(), deleteSelectedCrossings(), deleteSelectedEdges(), deleteSelectedJunctions(), deleteSelectedLanes(), deleteSelectedShapes(), finishMoveSelection(), getUndoList(), hotkeyDel(), hotkeyEnter(), mergeJunctions(), onCmdAddReversedEdge(), onCmdClearConnections(), onCmdDuplicateLane(), onCmdReplaceJunction(), onCmdResetConnections(), onCmdResetEdgeEndpoint(), onCmdReverseEdge(), onCmdSetEdgeEndpoint(), onCmdSmoothEdges(), onCmdSmoothEdgesElevation(), onCmdSplitEdge(), onCmdSplitEdgeBidi(), onCmdStraightenEdges(), onCmdStraightenEdgesElevation(), onCmdTransformPOI(), onLeftBtnPress(), onLeftBtnRelease(), removeRestrictedLane(), and restrictLane().
myUseToolTips
bool GUISUMOAbstractView::myUseToolTips protected inherited
use tool tips
Definition at line 417 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::showToolTips(), and GUISUMOAbstractView::updateToolTip().
myViewParent
GNEViewParent* GNEViewNet::myViewParent private
view parent
Definition at line 380 of file GNEViewNet.h.
Referenced by abortOperation(), doPaintGL(), getViewParent(), hotkeyEnter(), onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), onRightBtnPress(), onRightBtnRelease(), updateControls(), and updateModeSpecificControls().
myViewportChooser
GUIDialog_EditViewport* GUISUMOAbstractView::myViewportChooser protected inherited
viewport chooser
Definition at line 423 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getViewportEditor(), GUISUMOAbstractView::onMouseMove(), GUISUMOAbstractView::remove(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
myVisualizationChanger
GUIDialog_ViewSettings* GUISUMOAbstractView::myVisualizationChanger protected inherited
Visualization changer.
Definition at line 429 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::remove(), GUIViewTraffic::setColorScheme(), setColorScheme(), GUISUMOAbstractView::showViewschemeEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
myVisualizationSettings
GUIVisualizationSettings* GUISUMOAbstractView::myVisualizationSettings protected inherited
visualization settings
Definition at line 414 of file GUISUMOAbstractView.h.
Referenced by buildEditModeControls(), GUIViewTraffic::buildViewToolBars(), buildViewToolBars(), GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getVisualisationSettings(), GUISUMOAbstractView::makeSnapshot(), onCmdShowGrid(), onCmdToogleShowConnection(), GUISUMOAbstractView::onConfigure(), onMouseMove(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::paintGLGrid(), GUIViewTraffic::setColorScheme(), setColorScheme(), setSelectionScaling(), showConnections(), GUISUMOAbstractView::showViewschemeEditor(), GUISUMOAbstractView::snapToActiveGrid(), updateModeSpecificControls(), and GUISUMOAbstractView::~GUISUMOAbstractView().
myWindowCursorPositionX
FXint GUISUMOAbstractView::myWindowCursorPositionX protected inherited
Position of the cursor relative to the window.
Definition at line 426 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getPositionInformation(), and GUISUMOAbstractView::setWindowCursorPosition().
myWindowCursorPositionY
FXint GUISUMOAbstractView::myWindowCursorPositionY protected inherited
Definition at line 426 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getPositionInformation(), and GUISUMOAbstractView::setWindowCursorPosition().
The documentation for this class was generated from the following files:
GNEViewNet.h
GNEViewNet.cpp