SUMO - Simulation of Urban MObility: NBContHelper::edge_opposite_direction_sorter Class Reference
NBContHelper::edge_opposite_direction_sorter Class Reference
Class to sort edges by their angle in relation to the given edge.
#include <NBContHelper.h>
Public Member Functions
edge_opposite_direction_sorter (const NBEdge *const e, const NBNode *const n, bool regardPriority)
Constructor.
int operator() (NBEdge *e1, NBEdge *e2) const
Comparing operation.
Protected Member Functions
double getDiff (const NBEdge *const e) const
Computes the angle difference between the related and the given edge.
double getEdgeAngleAt (const NBEdge *const e, const NBNode *const n) const
Returns the given edge's angle at the given node.
Private Member Functions
edge_opposite_direction_sorter & operator= (const edge_opposite_direction_sorter &s)
Invalidated assignment operator.
Private Attributes
double myAngle
The angle of the related edge at the given node.
const NBEdge *const myEdge
the reference edge
const NBNode *const myNode
The related node.
bool myRegardPriority
Whether edge priority may override closer angles.
Detailed Description
Class to sort edges by their angle in relation to the given edge.
The resulting sorted list has the edge in the most opposite direction to the given edge as her first entry.
Definition at line 177 of file NBContHelper.h.
Constructor & Destructor Documentation
edge_opposite_direction_sorter()
NBContHelper::edge_opposite_direction_sorter::edge_opposite_direction_sorter (const NBEdge *const e, const NBNode *const n, bool regardPriority) inline explicit
Constructor.
Parameters
[in] e The edge to which the sorting relates
[in] n The node to consider
Definition at line 183 of file NBContHelper.h.
Member Function Documentation
getDiff()
double NBContHelper::edge_opposite_direction_sorter::getDiff (const NBEdge *const e) const inline protected
Computes the angle difference between the related and the given edge.
Parameters
[in] e The edge to compare the angle difference of
Returns
The angle difference
Definition at line 208 of file NBContHelper.h.
References GeomHelper::angleDiff().
getEdgeAngleAt()
double NBContHelper::edge_opposite_direction_sorter::getEdgeAngleAt (const NBEdge *const e, const NBNode *const n) const inline protected
Returns the given edge's angle at the given node.
Please note that we always consider the "outgoing direction".
Parameters
[in] e The edge to which the sorting relates
[in] n The node to consider
Definition at line 218 of file NBContHelper.h.
References PositionVector::angleAt2D(), NBEdge::getFromNode(), and NBEdge::getGeometry().
operator()()
int NBContHelper::edge_opposite_direction_sorter::operator() (NBEdge * e1, NBEdge * e2) const inline
Comparing operation.
Parameters
[in] e1 The first edge to compare
[in] e2 The second edge to compare
Returns
Which edge is more opposite to the related one
Definition at line 195 of file NBContHelper.h.
References NBEdge::getPriority(), and NBContHelper::relative_outgoing_edge_sorter::myEdge.
operator=()
edge_opposite_direction_sorter& NBContHelper::edge_opposite_direction_sorter::operator= (const edge_opposite_direction_sorter & s) private
Invalidated assignment operator.
Field Documentation
myAngle
double NBContHelper::edge_opposite_direction_sorter::myAngle private
The angle of the related edge at the given node.
Definition at line 235 of file NBContHelper.h.
myEdge
const NBEdge* const NBContHelper::edge_opposite_direction_sorter::myEdge private
the reference edge
Definition at line 232 of file NBContHelper.h.
myNode
const NBNode* const NBContHelper::edge_opposite_direction_sorter::myNode private
The related node.
Definition at line 229 of file NBContHelper.h.
myRegardPriority
bool NBContHelper::edge_opposite_direction_sorter::myRegardPriority private
Whether edge priority may override closer angles.
Definition at line 238 of file NBContHelper.h.
The documentation for this class was generated from the following file:
NBContHelper.h