SUMO - Simulation of Urban MObility: MSPModel_NonInteracting Class Reference
MSPModel_NonInteracting Class Reference
The pedestrian following model.
#include <MSPModel_NonInteracting.h>
Data Structures
class MoveToNextEdge
class PState
abstract base class for managing callbacks to retrieve various state information from the model
Public Member Functions
PedestrianState * add (MSPerson *person, MSPerson::MSPersonStage_Walking *stage, SUMOTime now)
register the given person as a pedestrian
virtual bool blockedAtDist (const MSLane *lane, double vehSide, double vehWidth, double oncomingGap, std::vector< const MSPerson *> *collectBlockers)
whether a pedestrian is blocking the crossing of lane for the given vehicle bondaries
virtual void cleanupHelper ()
virtual bool hasPedestrians (const MSLane *lane)
whether the given lane has pedestrians on it
MSPModel_NonInteracting (const OptionsCont &oc, MSNet *net)
Constructor (it should not be necessary to construct more than one instance)
virtual PersonDist nextBlocking (const MSLane *lane, double minPos, double minRight, double maxLeft, double stopTime=0)
returns the next pedestrian beyond minPos that is laterally between minRight and maxLeft or 0
void remove (PedestrianState *state)
remove the specified person from the pedestrian simulation
bool usingInternalLanes ()
whether movements on intersections are modelled
~MSPModel_NonInteracting ()
Static Public Member Functions
static bool canTraverse (int dir, const ConstMSEdgeVector &route)
return whether the route may traversed with the given starting direction
static void cleanup ()
remove state at simulation end
static MSPModel * getModel ()
Static Public Attributes
static const int BACKWARD
static const int FORWARD
static const double SAFETY_GAP
static const double SIDEWALK_OFFSET
the offset for computing person positions when walking on edges without a sidewalk
static const int UNDEFINED_DIRECTION
Private Attributes
MSNet * myNet
the net to which to issue moveToNextEdge commands
Detailed Description
The pedestrian following model.
Definition at line 55 of file MSPModel_NonInteracting.h.
Constructor & Destructor Documentation
MSPModel_NonInteracting()
MSPModel_NonInteracting::MSPModel_NonInteracting (const OptionsCont & oc, MSNet * net)
Constructor (it should not be necessary to construct more than one instance)
Definition at line 64 of file MSPModel_NonInteracting.cpp.
References myNet, and UNUSED_PARAMETER.
~MSPModel_NonInteracting()
MSPModel_NonInteracting::~MSPModel_NonInteracting ()
Definition at line 71 of file MSPModel_NonInteracting.cpp.
Member Function Documentation
add()
PedestrianState * MSPModel_NonInteracting::add (MSPerson * person, MSPerson::MSPersonStage_Walking * stage, SUMOTime now) virtual
register the given person as a pedestrian
Implements MSPModel.
Definition at line 76 of file MSPModel_NonInteracting.cpp.
References MSEventControl::addEvent(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSNet::getBeginOfTimestepEvents(), and myNet.
blockedAtDist()
virtual bool MSPModel::blockedAtDist (const MSLane * lane, double vehSide, double vehWidth, double oncomingGap, std::vector< const MSPerson *> * collectBlockers) inline virtual inherited
whether a pedestrian is blocking the crossing of lane for the given vehicle bondaries
Parameters
[in] lane The crossing to check
[in] vehSide The offset to the vehicle side near the start of the crossing
[in] vehWidth The width of the vehicle
[in] oncomingGap The distance which the vehicle wants to keep from oncoming pedestrians
[in] collectBlockers The list of persons blocking the crossing
Returns
Whether the vehicle must wait
Reimplemented in MSPModel_Striping.
Definition at line 79 of file MSPModel.h.
References UNUSED_PARAMETER.
Referenced by MSLink::getLeaderInfo().
canTraverse()
bool MSPModel::canTraverse (int dir, const ConstMSEdgeVector & route) static inherited
return whether the route may traversed with the given starting direction
Definition at line 98 of file MSPModel.cpp.
References MSPModel::BACKWARD, MSPModel::FORWARD, MSEdge::getFromJunction(), and MSEdge::getToJunction().
Referenced by MSPModel_Striping::PState::PState().
cleanup()
void MSPModel::cleanup () static inherited
remove state at simulation end
Definition at line 88 of file MSPModel.cpp.
References MSPModel::cleanupHelper(), and MSPModel::myModel.
Referenced by MSNet::clearAll().
cleanupHelper()
virtual void MSPModel::cleanupHelper () inline virtual inherited
Reimplemented in MSPModel_Striping.
Definition at line 105 of file MSPModel.h.
Referenced by MSPModel::cleanup().
getModel()
MSPModel * MSPModel::getModel () static inherited
Definition at line 65 of file MSPModel.cpp.
References MSNet::getInstance(), OptionsCont::getOptions(), OptionsCont::getString(), and MSPModel::myModel.
Referenced by MSPerson::MSPersonStage_Walking::abort(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSLane::checkForPedestrians(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSLink::getLeaderInfo(), MSVehicle::planMoveInternal(), MSPerson::MSPersonStage_Walking::proceed(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSPerson::MSPersonStage_Walking::walkDistance().
hasPedestrians()
virtual bool MSPModel::hasPedestrians (const MSLane * lane) inline virtual inherited
whether the given lane has pedestrians on it
Reimplemented in MSPModel_Striping.
Definition at line 90 of file MSPModel.h.
References UNUSED_PARAMETER.
Referenced by MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSVehicle::planMoveInternal(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
nextBlocking()
virtual PersonDist MSPModel::nextBlocking (const MSLane * lane, double minPos, double minRight, double maxLeft, double stopTime = 0) inline virtual inherited
returns the next pedestrian beyond minPos that is laterally between minRight and maxLeft or 0
Reimplemented in MSPModel_Striping.
Definition at line 96 of file MSPModel.h.
References UNUSED_PARAMETER.
Referenced by MSLCM_LC2013::adaptSpeedToPedestrians(), MSLane::checkForPedestrians(), MSLane::detectCollisions(), MSVehicle::planMoveInternal(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
remove()
void MSPModel_NonInteracting::remove (PedestrianState * state) virtual
remove the specified person from the pedestrian simulation
Implements MSPModel.
Definition at line 88 of file MSPModel_NonInteracting.cpp.
usingInternalLanes()
bool MSPModel_NonInteracting::usingInternalLanes () inline virtual
whether movements on intersections are modelled
Implements MSPModel.
Definition at line 70 of file MSPModel_NonInteracting.h.
Field Documentation
BACKWARD
const int MSPModel::BACKWARD static inherited
Definition at line 109 of file MSPModel.h.
Referenced by MSPModel_Striping::addCloserObstacle(), MSPModel_Striping::addCrossingVehs(), MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSPModel_Striping::connectedDirection(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::PState::getAngle(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::initWalkingAreaPaths(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), MSPModel_Striping::PState::PState(), and MSPModel_Striping::PState::walk().
FORWARD
const int MSPModel::FORWARD static inherited
Definition at line 105 of file MSPModel.h.
Referenced by MSPModel_Striping::addCloserObstacle(), MSPModel_Striping::addCrossingVehs(), MSPModel_Striping::blockedAtDist(), MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSPModel_Striping::connectedDirection(), MSPModel_Striping::PState::distanceTo(), MSPModel_Striping::PState::distToLaneEnd(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::PState::getMaxX(), MSPModel_Striping::PState::getMinX(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::getNextWalkingArea(), MSPModel_Striping::initWalkingAreaPaths(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), MSPModel_Striping::nextBlocking(), MSPModel_Striping::PState::PState(), MSPModel_Striping::transformToCurrentLanePositions(), and MSPModel_Striping::PState::walk().
myNet
MSNet* MSPModel_NonInteracting::myNet private
the net to which to issue moveToNextEdge commands
Definition at line 127 of file MSPModel_NonInteracting.h.
Referenced by add(), and MSPModel_NonInteracting().
SAFETY_GAP
const double MSPModel::SAFETY_GAP static inherited
Definition at line 113 of file MSPModel.h.
Referenced by MSLink::getLeaderInfo(), and MSPModel_Striping::moveInDirectionOnLane().
SIDEWALK_OFFSET
const double MSPModel::SIDEWALK_OFFSET static inherited
the offset for computing person positions when walking on edges without a sidewalk
Definition at line 116 of file MSPModel.h.
Referenced by MSPModel_NonInteracting::PState::getPosition(), and GUINet::initGUIStructures().
UNDEFINED_DIRECTION
const int MSPModel::UNDEFINED_DIRECTION static inherited
Definition at line 110 of file MSPModel.h.
Referenced by MSPModel_NonInteracting::PState::computeWalkingTime(), MSPModel_Striping::connectedDirection(), MSPModel_Striping::getNextLane(), and MSPModel_Striping::PState::moveToNextLane().
The documentation for this class was generated from the following files:
MSPModel_NonInteracting.h
MSPModel_NonInteracting.cpp