SUMO - Simulation of Urban MObility: GNEDialog_AllowDisallow Class Reference
GNEDialog_AllowDisallow Class Reference
Dialog for edit rerouters.
#include <GNEDialog_AllowDisallow.h>
Public Member Functions
GNEDialog_AllowDisallow (FXApp *app, std::string *allow)
FOX-declaration.
~GNEDialog_AllowDisallow ()
destructor
FOX-callbacks
event when user press a enable/disable button
long onCmdValueChanged (FXObject *, FXSelector, void *)
long onCmdSelectAll (FXObject *, FXSelector, void *)
event when user press select all VClasses button
long onCmdUnselectAll (FXObject *, FXSelector, void *)
event when user press unselect all VClasses button
long onCmdSelectOnlyNonRoad (FXObject *, FXSelector, void *)
event when user press select only non road button
long onCmdAccept (FXObject *, FXSelector, void *)
event after press accept button
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
Protected Member Functions
GNEDialog_AllowDisallow ()
FOX needs this.
Protected Attributes
FXButton * myAcceptButton
accept button
std::string * myAllow
pointer to current allowed vehicles
FXButton * myCancelButton
cancel button
std::string myCopyOfAllow
copy of current allowed vehicles
FXButton * myResetButton
cancel button
FXButton * mySelectAllVClassButton
select all VClass
FXButton * mySelectOnlyNonRoadVClassButton
select only non-road vehicles
FXButton * myUnselectAllVClassButton
unselect all VCLass
std::map< SUMOVehicleClass, std::pair< FXButton *, FXLabel * > > myVClassMap
map with the buttons for every VClass
Private Member Functions
void buildVClass (FXVerticalFrame *contentsFrame, SUMOVehicleClass vclass, GUIIcon vclassIcon, const std::string &description)
build VClass
GNEDialog_AllowDisallow (const GNEDialog_AllowDisallow &)
Invalidated copy constructor.
GNEDialog_AllowDisallow & operator= (const GNEDialog_AllowDisallow &)
Invalidated assignment operator.
Detailed Description
Dialog for edit rerouters.
Definition at line 42 of file GNEDialog_AllowDisallow.h.
Constructor & Destructor Documentation
GNEDialog_AllowDisallow() [1/3]
GNEDialog_AllowDisallow::GNEDialog_AllowDisallow (FXApp * app, std::string * allow)
FOX-declaration.
Constructor
Definition at line 59 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonAccept, GUIDesignButtonCancel, GUIDesignButtonIcon, GUIDesignButtonReset, GUIDesignContentsFrame, GUIDesignGroupBoxFrame, GUIDesignHorizontalFrame, GUIDesignLabelLeftThick, ICON_ACCEPT, ICON_CANCEL, ICON_GREENVEHICLE, ICON_OK, ICON_RESET, ICON_VCLASS_ARMY, ICON_VCLASS_AUTHORITY, ICON_VCLASS_BICYCLE, ICON_VCLASS_BUS, ICON_VCLASS_COACH, ICON_VCLASS_CUSTOM1, ICON_VCLASS_CUSTOM2, ICON_VCLASS_DELIVERY, ICON_VCLASS_EMERGENCY, ICON_VCLASS_EVEHICLE, ICON_VCLASS_HOV, ICON_VCLASS_MOPED, ICON_VCLASS_MOTORCYCLE, ICON_VCLASS_PASSENGER, ICON_VCLASS_PEDESTRIAN, ICON_VCLASS_PRIVATE, ICON_VCLASS_RAIL, ICON_VCLASS_RAIL_ELECTRIC, ICON_VCLASS_RAIL_URBAN, ICON_VCLASS_SHIP, ICON_VCLASS_TAXI, ICON_VCLASS_TRAILER, ICON_VCLASS_TRAM, ICON_VCLASS_TRUCK, ICON_VCLASS_VIP, MID_GNE_ADDITIONALDIALOG_BUTTONACCEPT, MID_GNE_ADDITIONALDIALOG_BUTTONCANCEL, MID_GNE_ADDITIONALDIALOG_BUTTONRESET, MID_GNE_ALLOWDISALLOW_SELECTALL, MID_GNE_ALLOWDISALLOW_SELECTONLYNONROAD, MID_GNE_ALLOWDISALLOW_UNSELECTALL, SUMO_ATTR_VCLASS, SVC_ARMY, SVC_AUTHORITY, SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_CUSTOM1, SVC_CUSTOM2, SVC_DELIVERY, SVC_E_VEHICLE, SVC_EMERGENCY, SVC_HOV, SVC_MOPED, SVC_MOTORCYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_PRIVATE, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TAXI, SVC_TRAILER, SVC_TRAM, SVC_TRUCK, SVC_VIP, and toString().
~GNEDialog_AllowDisallow()
GNEDialog_AllowDisallow::~GNEDialog_AllowDisallow ()
destructor
Definition at line 123 of file GNEDialog_AllowDisallow.cpp.
GNEDialog_AllowDisallow() [2/3]
GNEDialog_AllowDisallow::GNEDialog_AllowDisallow () inline protected
FOX needs this.
Definition at line 79 of file GNEDialog_AllowDisallow.h.
GNEDialog_AllowDisallow() [3/3]
GNEDialog_AllowDisallow::GNEDialog_AllowDisallow (const GNEDialog_AllowDisallow &) private
Invalidated copy constructor.
Member Function Documentation
buildVClass()
void GNEDialog_AllowDisallow::buildVClass (FXVerticalFrame * contentsFrame, SUMOVehicleClass vclass, GUIIcon vclassIcon, const std::string & description) private
build VClass
Definition at line 229 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonIcon, GUIDesignLabelIcon64x32Thicked, GUIDesignLabelLeftThick, ICON_EMPTY, MID_GNE_ALLOWDISALLOW_CHANGE, and myVClassMap.
onCmdAccept()
long GNEDialog_AllowDisallow::onCmdAccept (FXObject * , FXSelector , void *)
event after press accept button
Definition at line 180 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), getVehicleClassNames(), ICON_ACCEPT, joinToString(), and myVClassMap.
onCmdCancel()
long GNEDialog_AllowDisallow::onCmdCancel (FXObject * , FXSelector , void *)
event after press cancel button
Definition at line 202 of file GNEDialog_AllowDisallow.cpp.
onCmdReset()
long GNEDialog_AllowDisallow::onCmdReset (FXObject * , FXSelector , void *)
event after press reset button
Definition at line 210 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), getVehicleClassNames(), ICON_ACCEPT, ICON_CANCEL, myCopyOfAllow, myVClassMap, and SUMOSAXAttributes::parseStringVector().
onCmdSelectAll()
long GNEDialog_AllowDisallow::onCmdSelectAll (FXObject * , FXSelector , void *)
event when user press select all VClasses button
Definition at line 146 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), ICON_ACCEPT, and myVClassMap.
onCmdSelectOnlyNonRoad()
long GNEDialog_AllowDisallow::onCmdSelectOnlyNonRoad (FXObject * , FXSelector , void *)
event when user press select only non road button
Definition at line 166 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), ICON_ACCEPT, ICON_CANCEL, myVClassMap, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, and SVC_TRAM.
onCmdUnselectAll()
long GNEDialog_AllowDisallow::onCmdUnselectAll (FXObject * , FXSelector , void *)
event when user press unselect all VClasses button
Definition at line 156 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), ICON_CANCEL, and myVClassMap.
onCmdValueChanged()
long GNEDialog_AllowDisallow::onCmdValueChanged (FXObject * obj, FXSelector , void *)
Definition at line 128 of file GNEDialog_AllowDisallow.cpp.
References GUIIconSubSys::getIcon(), ICON_ACCEPT, ICON_CANCEL, and myVClassMap.
operator=()
GNEDialog_AllowDisallow& GNEDialog_AllowDisallow::operator= (const GNEDialog_AllowDisallow &) private
Invalidated assignment operator.
Field Documentation
myAcceptButton
FXButton* GNEDialog_AllowDisallow::myAcceptButton protected
accept button
Definition at line 97 of file GNEDialog_AllowDisallow.h.
myAllow
std::string* GNEDialog_AllowDisallow::myAllow protected
pointer to current allowed vehicles
Definition at line 82 of file GNEDialog_AllowDisallow.h.
myCancelButton
FXButton* GNEDialog_AllowDisallow::myCancelButton protected
cancel button
Definition at line 100 of file GNEDialog_AllowDisallow.h.
myCopyOfAllow
std::string GNEDialog_AllowDisallow::myCopyOfAllow protected
copy of current allowed vehicles
Definition at line 85 of file GNEDialog_AllowDisallow.h.
Referenced by onCmdReset().
myResetButton
FXButton* GNEDialog_AllowDisallow::myResetButton protected
cancel button
Definition at line 103 of file GNEDialog_AllowDisallow.h.
mySelectAllVClassButton
FXButton* GNEDialog_AllowDisallow::mySelectAllVClassButton protected
select all VClass
Definition at line 88 of file GNEDialog_AllowDisallow.h.
mySelectOnlyNonRoadVClassButton
FXButton* GNEDialog_AllowDisallow::mySelectOnlyNonRoadVClassButton protected
select only non-road vehicles
Definition at line 94 of file GNEDialog_AllowDisallow.h.
myUnselectAllVClassButton
FXButton* GNEDialog_AllowDisallow::myUnselectAllVClassButton protected
unselect all VCLass
Definition at line 91 of file GNEDialog_AllowDisallow.h.
myVClassMap
std::map<SUMOVehicleClass, std::pair<FXButton*, FXLabel*> > GNEDialog_AllowDisallow::myVClassMap protected
map with the buttons for every VClass
Definition at line 106 of file GNEDialog_AllowDisallow.h.
Referenced by buildVClass(), onCmdAccept(), onCmdReset(), onCmdSelectAll(), onCmdSelectOnlyNonRoad(), onCmdUnselectAll(), and onCmdValueChanged().
The documentation for this class was generated from the following files:
GNEDialog_AllowDisallow.h
GNEDialog_AllowDisallow.cpp