SUMO - Simulation of Urban MObility: GUIPropertyScheme< T > Class Template Reference
GUIPropertyScheme< T > Class Template Reference
#include <GUIPropertyScheme.h>
Public Member Functions
int addColor (const T &color, const double threshold, const std::string &name="")
bool allowsNegativeValues () const
void clear ()
const T getColor (const double value) const
const std::vector< T > & getColors () const
const std::string & getName () const
const std::vector< std::string > & getNames () const
std::string getTagName (std::vector< RGBColor >) const
std::string getTagName (std::vector< double >) const
const std::vector< double > & getThresholds () const
GUIPropertyScheme (const std::string &name, const T &baseColor, const std::string &colName="", const bool isFixed=false, double baseValue=0)
Constructor.
RGBColor interpolate (const RGBColor &min, const RGBColor &max, double weight) const
specializations for GUIColorScheme
double interpolate (const double &min, const double &max, double weight) const
specializations for GUIScaleScheme
bool isFixed () const
bool isInterpolated () const
bool operator== (const GUIPropertyScheme &c) const
void removeColor (const int pos)
void save (OutputDevice &dev) const
void setAllowsNegativeValues (bool value)
void setColor (const int pos, const T &color)
bool setColor (const std::string &name, const T &color)
void setInterpolated (const bool interpolate, double interpolationStart=0.f)
void setThreshold (const int pos, const double threshold)
Private Attributes
bool myAllowNegativeValues
std::vector< T > myColors
bool myIsFixed
bool myIsInterpolated
std::string myName
std::vector< std::string > myNames
std::vector< double > myThresholds
Detailed Description
template<class T>
class GUIPropertyScheme< T >
This class provides a mapping from real values to properties (mainly colors). Each color is stored along with a threshold value. Color values between thresholds are obtained by interpolation
Definition at line 51 of file GUIPropertyScheme.h.
Constructor & Destructor Documentation
GUIPropertyScheme()
template<class T > GUIPropertyScheme< T >::GUIPropertyScheme (const std::string & name, const T & baseColor, const std::string & colName = "", const bool isFixed = false, double baseValue = 0) inline
Constructor.
Definition at line 54 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::addColor().
Member Function Documentation
addColor()
template<class T > int GUIPropertyScheme< T >::addColor (const T & color, const double threshold, const std::string & name = "") inline
Definition at line 82 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors, GUIPropertyScheme< T >::myNames, and GUIPropertyScheme< T >::myThresholds.
Referenced by GUIViewTraffic::buildColorRainbow(), GNEViewNet::buildColorRainbow(), GUIPropertyScheme< T >::GUIPropertyScheme(), GUIVisualizationSettings::initNeteditDefaults(), GUIVisualizationSettings::initSumoGuiDefaults(), GUISettingsHandler::myStartElement(), GUIDialog_ViewSettings::updateColorRanges(), and GUIDialog_ViewSettings::updateScaleRanges().
allowsNegativeValues()
template<class T > bool GUIPropertyScheme< T >::allowsNegativeValues () const inline
Definition at line 163 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myAllowNegativeValues.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::rebuildScaleMatrix().
clear()
template<class T > void GUIPropertyScheme< T >::clear () inline
Definition at line 106 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors, GUIPropertyScheme< T >::myNames, and GUIPropertyScheme< T >::myThresholds.
Referenced by GUIViewTraffic::buildColorRainbow(), GNEViewNet::buildColorRainbow(), and GUISettingsHandler::myStartElement().
getColor()
template<class T > const T GUIPropertyScheme< T >::getColor (const double value) const inline
Definition at line 112 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::interpolate(), GUIPropertyScheme< T >::myColors, GUIPropertyScheme< T >::myIsInterpolated, and GUIPropertyScheme< T >::myThresholds.
Referenced by GUILane::drawAsWaterway(), GUIJunctionWrapper::drawGL(), GUILane::drawGL(), GUIJunctionWrapper::getColorValue(), GUIEdge::setColor(), GUIContainer::setColor(), GUIPerson::setColor(), GNEJunction::setColor(), GUILane::setColor(), GUIBaseVehicle::setColor(), GNELane::setLaneColor(), GUIEdge::setMultiColor(), GNELane::setMultiColor(), and GUILane::setMultiColor().
getColors()
template<class T > const std::vector<T>& GUIPropertyScheme< T >::getColors () const inline
Definition at line 143 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::rebuildScaleMatrix().
getName()
template<class T > const std::string& GUIPropertyScheme< T >::getName () const inline
Definition at line 139 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myName.
getNames()
template<class T > const std::vector<std::string>& GUIPropertyScheme< T >::getNames () const inline
Definition at line 155 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myNames.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::rebuildScaleMatrix().
getTagName() [1/2]
template<class T > std::string GUIPropertyScheme< T >::getTagName (std::vector< RGBColor >) const inline
Definition at line 209 of file GUIPropertyScheme.h.
References SUMO_TAG_COLORSCHEME, and toString().
Referenced by GUIPropertyScheme< T >::save().
getTagName() [2/2]
template<class T > std::string GUIPropertyScheme< T >::getTagName (std::vector< double >) const inline
Definition at line 219 of file GUIPropertyScheme.h.
References SUMO_TAG_SCALINGSCHEME, and toString().
getThresholds()
template<class T > const std::vector<double>& GUIPropertyScheme< T >::getThresholds () const inline
Definition at line 147 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myThresholds.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::rebuildScaleMatrix().
interpolate() [1/2]
template<class T > RGBColor GUIPropertyScheme< T >::interpolate (const RGBColor & min, const RGBColor & max, double weight) const inline
specializations for GUIColorScheme
Definition at line 205 of file GUIPropertyScheme.h.
References RGBColor::interpolate().
Referenced by GUIPropertyScheme< T >::getColor(), and GUIPropertyScheme< T >::setInterpolated().
interpolate() [2/2]
template<class T > double GUIPropertyScheme< T >::interpolate (const double & min, const double & max, double weight) const inline
specializations for GUIScaleScheme
Definition at line 215 of file GUIPropertyScheme.h.
isFixed()
template<class T > bool GUIPropertyScheme< T >::isFixed () const inline
Definition at line 159 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myIsFixed.
Referenced by GUIViewTraffic::buildColorRainbow(), GNEViewNet::buildColorRainbow(), GUISettingsHandler::myStartElement(), GUIDialog_ViewSettings::rebuildColorMatrices(), GUIDialog_ViewSettings::rebuildColorMatrix(), GUIDialog_ViewSettings::rebuildScaleMatrix(), GUIDialog_ViewSettings::updateColorRanges(), and GUIDialog_ViewSettings::updateScaleRanges().
isInterpolated()
template<class T > bool GUIPropertyScheme< T >::isInterpolated () const inline
Definition at line 151 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myIsInterpolated.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::rebuildScaleMatrix().
operator==()
template<class T > bool GUIPropertyScheme< T >::operator== (const GUIPropertyScheme< T > & c) const inline
Definition at line 199 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors, GUIPropertyScheme< T >::myIsInterpolated, GUIPropertyScheme< T >::myName, and GUIPropertyScheme< T >::myThresholds.
removeColor()
template<class T > void GUIPropertyScheme< T >::removeColor (const int pos) inline
Definition at line 99 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors, GUIPropertyScheme< T >::myNames, and GUIPropertyScheme< T >::myThresholds.
Referenced by GUIDialog_ViewSettings::updateColorRanges(), and GUIDialog_ViewSettings::updateScaleRanges().
save()
template<class T > void GUIPropertyScheme< T >::save (OutputDevice & dev) const inline
Definition at line 171 of file GUIPropertyScheme.h.
References OutputDevice::closeTag(), GUIPropertyScheme< T >::getTagName(), GUIPropertyScheme< T >::myColors, GUIPropertyScheme< T >::myIsFixed, GUIPropertyScheme< T >::myIsInterpolated, GUIPropertyScheme< T >::myName, GUIPropertyScheme< T >::myNames, GUIPropertyScheme< T >::myThresholds, OutputDevice::openTag(), SUMO_ATTR_COLOR, SUMO_ATTR_INTERPOLATED, SUMO_ATTR_NAME, SUMO_ATTR_THRESHOLD, SUMO_TAG_ENTRY, and OutputDevice::writeAttr().
setAllowsNegativeValues()
template<class T > void GUIPropertyScheme< T >::setAllowsNegativeValues (bool value) inline
Definition at line 167 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myAllowNegativeValues.
Referenced by GUIVisualizationSettings::initNeteditDefaults(), and GUIVisualizationSettings::initSumoGuiDefaults().
setColor() [1/2]
template<class T > void GUIPropertyScheme< T >::setColor (const int pos, const T & color) inline
Definition at line 66 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors.
Referenced by GUISettingsHandler::myStartElement(), GUIDialog_ViewSettings::updateColorRanges(), and GUIDialog_ViewSettings::updateScaleRanges().
setColor() [2/2]
template<class T > bool GUIPropertyScheme< T >::setColor (const std::string & name, const T & color) inline
Definition at line 70 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myColors, and GUIPropertyScheme< T >::myNames.
setInterpolated()
template<class T > void GUIPropertyScheme< T >::setInterpolated (const bool interpolate, double interpolationStart = 0.f) inline
Definition at line 132 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::interpolate(), GUIPropertyScheme< T >::myIsInterpolated, and GUIPropertyScheme< T >::myThresholds.
Referenced by GUISettingsHandler::myStartElement(), and GUIDialog_ViewSettings::onCmdColorChange().
setThreshold()
template<class T > void GUIPropertyScheme< T >::setThreshold (const int pos, const double threshold) inline
Definition at line 62 of file GUIPropertyScheme.h.
References GUIPropertyScheme< T >::myThresholds.
Referenced by GUIDialog_ViewSettings::updateColorRanges(), and GUIDialog_ViewSettings::updateScaleRanges().
Field Documentation
myAllowNegativeValues
template<class T > bool GUIPropertyScheme< T >::myAllowNegativeValues private
Definition at line 231 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::allowsNegativeValues(), and GUIPropertyScheme< T >::setAllowsNegativeValues().
myColors
template<class T > std::vector<T> GUIPropertyScheme< T >::myColors private
Definition at line 226 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::addColor(), GUIPropertyScheme< T >::clear(), GUIPropertyScheme< T >::getColor(), GUIPropertyScheme< T >::getColors(), GUIPropertyScheme< T >::operator==(), GUIPropertyScheme< T >::removeColor(), GUIPropertyScheme< T >::save(), and GUIPropertyScheme< T >::setColor().
myIsFixed
template<class T > bool GUIPropertyScheme< T >::myIsFixed private
Definition at line 230 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::isFixed(), and GUIPropertyScheme< T >::save().
myIsInterpolated
template<class T > bool GUIPropertyScheme< T >::myIsInterpolated private
Definition at line 228 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::getColor(), GUIPropertyScheme< T >::isInterpolated(), GUIPropertyScheme< T >::operator==(), GUIPropertyScheme< T >::save(), and GUIPropertyScheme< T >::setInterpolated().
myName
template<class T > std::string GUIPropertyScheme< T >::myName private
Definition at line 225 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::getName(), GUIPropertyScheme< T >::operator==(), and GUIPropertyScheme< T >::save().
myNames
template<class T > std::vector<std::string> GUIPropertyScheme< T >::myNames private
Definition at line 229 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::addColor(), GUIPropertyScheme< T >::clear(), GUIPropertyScheme< T >::getNames(), GUIPropertyScheme< T >::removeColor(), GUIPropertyScheme< T >::save(), and GUIPropertyScheme< T >::setColor().
myThresholds
template<class T > std::vector<double> GUIPropertyScheme< T >::myThresholds private
Definition at line 227 of file GUIPropertyScheme.h.
Referenced by GUIPropertyScheme< T >::addColor(), GUIPropertyScheme< T >::clear(), GUIPropertyScheme< T >::getColor(), GUIPropertyScheme< T >::getThresholds(), GUIPropertyScheme< T >::operator==(), GUIPropertyScheme< T >::removeColor(), GUIPropertyScheme< T >::save(), GUIPropertyScheme< T >::setInterpolated(), and GUIPropertyScheme< T >::setThreshold().
The documentation for this class was generated from the following file:
GUIPropertyScheme.h