SUMO - Simulation of Urban MObility: libsumo::Edge Class Reference
libsumo::Edge Class Reference
#include <Edge.h>
Static Public Member Functions
static void addEffort (const std::string &id, double begTime, double endTime, double value)
static void addTravelTime (const std::string &id, double begTime, double endTime, double value)
static double getCO2Emissions (const std::string &id)
static double getCOEmissions (const std::string &id)
static double getCurrentTravelTime (const std::string &id)
static MSEdge * getEdge (const std::string &id)
static double getElectricityConsumption (const std::string &id)
static double getFuelConsumption (const std::string &id)
static double getHCEmissions (const std::string &id)
static int getIDCount ()
static std::vector< std::string > getIDList ()
static double getMeanSpeed (const std::string &id)
static double getNoiseEmissions (const std::string &id)
static double getNOxEmissions (const std::string &id)
static double getOccupancy (const std::string &id)
static std::string getParameter (const std::string &id, const std::string &paramName)
static const std::vector< std::string > getPersonIDs (const std::string &id)
static double getPMxEmissions (const std::string &id)
static void getShape (const std::string &id, PositionVector &shape)
static double getVehicleAverageLength (const std::string &id)
static int getVehicleHaltingNumber (const std::string &id)
static const std::vector< std::string > getVehicleIDs (const std::string &id)
static int getVehicleNumber (const std::string &id)
static double getWaitingSeconds (const std::string &id)
static double retrieveExistingEffort (const std::string &id, double time)
static double retrieveExistingTravelTime (const std::string &id, double time)
static void setAllowedSVCPermissions (const std::string &id, SVCPermissions permissions)
static void setAllowedVehicleClasses (const std::string &id, std::vector< std::string > vector)
static void setDisallowedVehicleClasses (const std::string &id, std::vector< std::string > classes)
static void setMaxSpeed (const std::string &id, double value)
static void setParameter (const std::string &id, const std::string &name, const std::string &value)
Detailed Description
Definition at line 27 of file Edge.h.
Member Function Documentation
addEffort()
void libsumo::Edge::addEffort (const std::string & id, double begTime, double endTime, double value) static
Definition at line 289 of file Edge.cpp.
References MSEdgeWeightsStorage::addEffort(), getEdge(), MSNet::getInstance(), and MSNet::getWeightsStorage().
Referenced by TraCIServerAPI_Edge::processSet().
addTravelTime()
void libsumo::Edge::addTravelTime (const std::string & id, double begTime, double endTime, double value) static
Definition at line 284 of file Edge.cpp.
References MSEdgeWeightsStorage::addTravelTime(), getEdge(), MSNet::getInstance(), and MSNet::getWeightsStorage().
Referenced by TraCIServerAPI_Edge::processSet().
getCO2Emissions()
double libsumo::Edge::getCO2Emissions (const std::string & id) static
Definition at line 114 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getCOEmissions()
double libsumo::Edge::getCOEmissions (const std::string & id) static
Definition at line 124 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getCurrentTravelTime()
double libsumo::Edge::getCurrentTravelTime (const std::string & id) static
Definition at line 64 of file Edge.cpp.
References MSEdge::getCurrentTravelTime(), and getEdge().
Referenced by TraCIServerAPI_Edge::processGet().
getEdge()
MSEdge * libsumo::Edge::getEdge (const std::string & id) static
Definition at line 69 of file Edge.cpp.
References MSEdge::dictionary().
Referenced by addEffort(), addTravelTime(), getCO2Emissions(), getCOEmissions(), getCurrentTravelTime(), getElectricityConsumption(), getFuelConsumption(), getHCEmissions(), getMeanSpeed(), getNoiseEmissions(), getNOxEmissions(), getOccupancy(), getParameter(), getPersonIDs(), getPMxEmissions(), getShape(), getVehicleAverageLength(), getVehicleHaltingNumber(), getVehicleIDs(), getVehicleNumber(), getWaitingSeconds(), retrieveExistingEffort(), retrieveExistingTravelTime(), setAllowedSVCPermissions(), setMaxSpeed(), and setParameter().
getElectricityConsumption()
double libsumo::Edge::getElectricityConsumption (const std::string & id) static
Definition at line 187 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getFuelConsumption()
double libsumo::Edge::getFuelConsumption (const std::string & id) static
Definition at line 164 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getHCEmissions()
double libsumo::Edge::getHCEmissions (const std::string & id) static
Definition at line 134 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getIDCount()
int libsumo::Edge::getIDCount () static
Definition at line 40 of file Edge.cpp.
References getIDList().
Referenced by TraCIServerAPI_Edge::processGet().
getIDList()
std::vector< std::string > libsumo::Edge::getIDList () static
Definition at line 33 of file Edge.cpp.
References MSEdge::insertIDs().
Referenced by getIDCount(), and TraCIServerAPI_Edge::processGet().
getMeanSpeed()
double libsumo::Edge::getMeanSpeed (const std::string & id) static
Definition at line 207 of file Edge.cpp.
References getEdge(), and MSEdge::getMeanSpeed().
Referenced by TraCIServerAPI_Edge::processGet().
getNoiseEmissions()
double libsumo::Edge::getNoiseEmissions (const std::string & id) static
Definition at line 174 of file Edge.cpp.
References getEdge(), MSEdge::getLanes(), and HelpersHarmonoise::sum().
Referenced by TraCIServerAPI_Edge::processGet().
getNOxEmissions()
double libsumo::Edge::getNOxEmissions (const std::string & id) static
Definition at line 154 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getOccupancy()
double libsumo::Edge::getOccupancy (const std::string & id) static
Definition at line 212 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getParameter()
std::string libsumo::Edge::getParameter (const std::string & id, const std::string & paramName) static
Definition at line 257 of file Edge.cpp.
References getEdge(), and Parameterised::getParameter().
Referenced by TraCIServerAPI_Edge::processGet().
getPersonIDs()
const std::vector< std::string > libsumo::Edge::getPersonIDs (const std::string & id) static
Definition at line 88 of file Edge.cpp.
References getEdge(), MSNet::getInstance(), and MSEdge::getSortedPersons().
Referenced by TraCIServerAPI_Edge::processGet().
getPMxEmissions()
double libsumo::Edge::getPMxEmissions (const std::string & id) static
Definition at line 144 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getShape()
void libsumo::Edge::getShape (const std::string & id, PositionVector & shape) static
Definition at line 307 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::getShape().
getVehicleAverageLength()
double libsumo::Edge::getVehicleAverageLength (const std::string & id) static
Definition at line 238 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getVehicleHaltingNumber()
int libsumo::Edge::getVehicleHaltingNumber (const std::string & id) static
Definition at line 222 of file Edge.cpp.
References getEdge(), MSEdge::getLanes(), and SUMO_const_haltingSpeed.
Referenced by TraCIServerAPI_Edge::processGet().
getVehicleIDs()
const std::vector< std::string > libsumo::Edge::getVehicleIDs (const std::string & id) static
Definition at line 99 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getVehicleNumber()
int libsumo::Edge::getVehicleNumber (const std::string & id) static
Definition at line 197 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
getWaitingSeconds()
double libsumo::Edge::getWaitingSeconds (const std::string & id) static
Definition at line 78 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processGet().
retrieveExistingEffort()
double libsumo::Edge::retrieveExistingEffort (const std::string & id, double time) static
Definition at line 54 of file Edge.cpp.
References getEdge(), and MSNet::getInstance().
Referenced by TraCIServerAPI_Edge::processGet().
retrieveExistingTravelTime()
double libsumo::Edge::retrieveExistingTravelTime (const std::string & id, double time) static
Definition at line 44 of file Edge.cpp.
References getEdge(), and MSNet::getInstance().
Referenced by TraCIServerAPI_Edge::processGet().
setAllowedSVCPermissions()
void libsumo::Edge::setAllowedSVCPermissions (const std::string & id, SVCPermissions permissions) static
Definition at line 274 of file Edge.cpp.
References MSLane::CHANGE_PERMISSIONS_PERMANENT, getEdge(), MSEdge::getLanes(), and MSEdge::rebuildAllowedLanes().
Referenced by setAllowedVehicleClasses(), and setDisallowedVehicleClasses().
setAllowedVehicleClasses()
void libsumo::Edge::setAllowedVehicleClasses (const std::string & id, std::vector< std::string > vector) static
Definition at line 262 of file Edge.cpp.
References parseVehicleClasses(), and setAllowedSVCPermissions().
Referenced by TraCIServerAPI_Edge::processSet().
setDisallowedVehicleClasses()
void libsumo::Edge::setDisallowedVehicleClasses (const std::string & id, std::vector< std::string > classes) static
Definition at line 268 of file Edge.cpp.
References invertPermissions(), parseVehicleClasses(), and setAllowedSVCPermissions().
Referenced by TraCIServerAPI_Edge::processSet().
setMaxSpeed()
void libsumo::Edge::setMaxSpeed (const std::string & id, double value) static
Definition at line 294 of file Edge.cpp.
References getEdge(), and MSEdge::getLanes().
Referenced by TraCIServerAPI_Edge::processSet().
setParameter()
void libsumo::Edge::setParameter (const std::string & id, const std::string & name, const std::string & value) static
Definition at line 302 of file Edge.cpp.
References getEdge(), and Parameterised::setParameter().
Referenced by TraCIServerAPI_Edge::processSet().
The documentation for this class was generated from the following files:
Edge.h
Edge.cpp