SUMO - Simulation of Urban MObility: GNEDialog_Wizard::InputFloat Class Reference
GNEDialog_Wizard::InputFloat Class Reference
#include <GNEDialog_Wizard.h>
Public Member Functions
InputFloat (FXComposite *parent, const std::string &name)
FOX-declaration.
long onCmdSetOption (FXObject *, FXSelector, void *)
try to set new attribute value
Protected Member Functions
InputFloat ()
FOX needs this.
Private Attributes
std::string myName
name
FXTextField * myTextField
text field
Detailed Description
Definition at line 128 of file GNEDialog_Wizard.h.
Constructor & Destructor Documentation
InputFloat() [1/2]
GNEDialog_Wizard::InputFloat::InputFloat (FXComposite * parent, const std::string & name)
FOX-declaration.
constructor
Definition at line 163 of file GNEDialog_Wizard.cpp.
References OptionsCont::getFloat(), OptionsCont::getOptions(), MID_GNE_SET_ATTRIBUTE, myTextField, and toString().
InputFloat() [2/2]
GNEDialog_Wizard::InputFloat::InputFloat () inline protected
FOX needs this.
Definition at line 141 of file GNEDialog_Wizard.h.
Member Function Documentation
onCmdSetOption()
long GNEDialog_Wizard::InputFloat::onCmdSetOption (FXObject * , FXSelector , void *)
try to set new attribute value
Definition at line 174 of file GNEDialog_Wizard.cpp.
References OptionsCont::getOptions(), myName, myTextField, OptionsCont::resetWritable(), and OptionsCont::set().
Field Documentation
myName
std::string GNEDialog_Wizard::InputFloat::myName private
name
Definition at line 145 of file GNEDialog_Wizard.h.
Referenced by onCmdSetOption().
myTextField
FXTextField* GNEDialog_Wizard::InputFloat::myTextField private
text field
Definition at line 148 of file GNEDialog_Wizard.h.
Referenced by InputFloat(), and onCmdSetOption().
The documentation for this class was generated from the following files:
GNEDialog_Wizard.h
GNEDialog_Wizard.cpp