SUMO - Simulation of Urban MObility: MSAbstractLaneChangeModel::MSLCMessager Class Reference
MSAbstractLaneChangeModel::MSLCMessager Class Reference
A class responsible for exchanging messages between cars involved in lane-change interaction.
#include <MSAbstractLaneChangeModel.h>
Public Member Functions
void * informLeader (void *info, MSVehicle *sender)
Informs the leader on the same lane.
void * informNeighFollower (void *info, MSVehicle *sender)
Informs the follower on the desired lane.
void * informNeighLeader (void *info, MSVehicle *sender)
Informs the leader on the desired lane.
MSLCMessager (MSVehicle *leader, MSVehicle *neighLead, MSVehicle *neighFollow)
Constructor.
~MSLCMessager ()
Destructor.
Private Attributes
MSVehicle * myLeader
The leader on the informed vehicle's lane.
MSVehicle * myNeighFollower
The follower on the lane the vehicle want to change to.
MSVehicle * myNeighLeader
The leader on the lane the vehicle want to change to.
Detailed Description
A class responsible for exchanging messages between cars involved in lane-change interaction.
Definition at line 57 of file MSAbstractLaneChangeModel.h.
Constructor & Destructor Documentation
MSLCMessager()
MSAbstractLaneChangeModel::MSLCMessager::MSLCMessager (MSVehicle * leader, MSVehicle * neighLead, MSVehicle * neighFollow) inline
Constructor.
Parameters
[in] leader The leader on the informed vehicle's lane
[in] neighLead The leader on the lane the vehicle want to change to
[in] neighFollow The follower on the lane the vehicle want to change to
Definition at line 64 of file MSAbstractLaneChangeModel.h.
~MSLCMessager()
MSAbstractLaneChangeModel::MSLCMessager::~MSLCMessager () inline
Destructor.
Definition at line 70 of file MSAbstractLaneChangeModel.h.
Member Function Documentation
informLeader()
void* MSAbstractLaneChangeModel::MSLCMessager::informLeader (void * info, MSVehicle * sender) inline
Informs the leader on the same lane.
Parameters
[in] info The information to pass
[in] sender The sending vehicle (the lane changing vehicle)
Returns
Something!?
Definition at line 78 of file MSAbstractLaneChangeModel.h.
References MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::inform(), and myLeader.
informNeighFollower()
void* MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower (void * info, MSVehicle * sender) inline
Informs the follower on the desired lane.
Parameters
[in] info The information to pass
[in] sender The sending vehicle (the lane changing vehicle)
Returns
Something!?
Definition at line 100 of file MSAbstractLaneChangeModel.h.
References MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::inform(), and myNeighFollower.
Referenced by MSLCM_DK2008::informBlocker(), and MSLCM_LC2013::informFollower().
informNeighLeader()
void* MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader (void * info, MSVehicle * sender) inline
Informs the leader on the desired lane.
Parameters
[in] info The information to pass
[in] sender The sending vehicle (the lane changing vehicle)
Returns
Something!?
Definition at line 89 of file MSAbstractLaneChangeModel.h.
References MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::inform(), and myNeighLeader.
Referenced by MSLCM_DK2008::informBlocker(), and MSLCM_LC2013::informLeader().
Field Documentation
myLeader
MSVehicle* MSAbstractLaneChangeModel::MSLCMessager::myLeader private
The leader on the informed vehicle's lane.
Definition at line 108 of file MSAbstractLaneChangeModel.h.
Referenced by informLeader().
myNeighFollower
MSVehicle* MSAbstractLaneChangeModel::MSLCMessager::myNeighFollower private
The follower on the lane the vehicle want to change to.
Definition at line 112 of file MSAbstractLaneChangeModel.h.
Referenced by informNeighFollower().
myNeighLeader
MSVehicle* MSAbstractLaneChangeModel::MSLCMessager::myNeighLeader private
The leader on the lane the vehicle want to change to.
Definition at line 110 of file MSAbstractLaneChangeModel.h.
Referenced by informNeighLeader().
The documentation for this class was generated from the following file:
MSAbstractLaneChangeModel.h