SUMO - Simulation of Urban MObility: libsumo::VehicleType Class Reference
libsumo::VehicleType Class Reference
#include <VehicleType.h>
Static Public Member Functions
static void copy (const std::string &origTypeID, const std::string &newTypeID)
static double getAccel (const std::string &typeID)
static double getActionStepLength (const std::string &typeID)
static double getApparentDecel (const std::string &typeID)
static TraCIColor getColor (const std::string &typeID)
static double getDecel (const std::string &typeID)
static double getEmergencyDecel (const std::string &typeID)
static std::string getEmissionClass (const std::string &typeID)
static double getHeight (const std::string &typeID)
static std::vector< std::string > getIDList ()
static double getImperfection (const std::string &typeID)
static std::string getLateralAlignment (const std::string &typeID)
static double getLength (const std::string &typeID)
static double getMaxSpeed (const std::string &typeID)
static double getMaxSpeedLat (const std::string &typeID)
static double getMinGap (const std::string &typeID)
static double getMinGapLat (const std::string &typeID)
static std::string getParameter (const std::string &typeID, const std::string &key)
static std::string getShapeClass (const std::string &typeID)
static double getSpeedDeviation (const std::string &typeID)
static double getSpeedFactor (const std::string &typeID)
static double getTau (const std::string &typeID)
static std::string getVehicleClass (const std::string &typeID)
static MSVehicleType * getVType (std::string id)
static double getWidth (const std::string &typeID)
static void setAccel (const std::string &typeID, double accel)
static void setActionStepLength (const std::string &typeID, double actionStepLength, bool resetActionOffset)
static void setApparentDecel (const std::string &typeID, double decel)
static void setColor (const std::string &typeID, const TraCIColor &c)
static void setDecel (const std::string &typeID, double decel)
static void setEmergencyDecel (const std::string &typeID, double decel)
static void setEmissionClass (const std::string &typeID, const std::string &clazz)
static void setHeight (const std::string &typeID, double height)
static void setImperfection (const std::string &typeID, double imperfection)
static void setLateralAlignment (const std::string &typeID, const std::string &latAlignment)
static void setLength (const std::string &typeID, double length)
static void setMaxSpeed (const std::string &typeID, double speed)
static void setMaxSpeedLat (const std::string &typeID, double speed)
static void setMinGap (const std::string &typeID, double minGap)
static void setMinGapLat (const std::string &typeID, double minGapLat)
static void setParameter (const std::string &id, const std::string &name, const std::string &value)
static void setShapeClass (const std::string &typeID, const std::string &shapeClass)
static void setSpeedDeviation (const std::string &typeID, double deviation)
static void setSpeedFactor (const std::string &typeID, double factor)
static void setTau (const std::string &typeID, double tau)
static void setVehicleClass (const std::string &typeID, const std::string &clazz)
static void setWidth (const std::string &typeID, double width)
Private Member Functions
VehicleType & operator= (const VehicleType &src)
invalidated assignment operator
VehicleType ()
invalidated standard constructor
VehicleType (const VehicleType &src)
invalidated copy constructor
Detailed Description
Definition at line 40 of file VehicleType.h.
Constructor & Destructor Documentation
VehicleType() [1/2]
libsumo::VehicleType::VehicleType () private
invalidated standard constructor
VehicleType() [2/2]
libsumo::VehicleType::VehicleType (const VehicleType & src) private
invalidated copy constructor
Member Function Documentation
copy()
void VehicleType::copy (const std::string & origTypeID, const std::string & newTypeID) static
Definition at line 309 of file VehicleType.cpp.
References MSVehicleType::duplicateType(), and getVType().
Referenced by TraCIServerAPI_VehicleType::setVariable().
getAccel()
double VehicleType::getAccel (const std::string & typeID) static
Definition at line 79 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getMaxAccel(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getActionStepLength()
double VehicleType::getActionStepLength (const std::string & typeID) static
Definition at line 61 of file VehicleType.cpp.
References MSVehicleType::getActionStepLengthSecs(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getApparentDecel()
double VehicleType::getApparentDecel (const std::string & typeID) static
Definition at line 97 of file VehicleType.cpp.
References MSCFModel::getApparentDecel(), MSVehicleType::getCarFollowModel(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getColor()
TraCIColor VehicleType::getColor (const std::string & typeID) static
Definition at line 151 of file VehicleType.cpp.
References MSVehicleType::getColor(), getVType(), and libsumo::Helper::makeTraCIColor().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getDecel()
double VehicleType::getDecel (const std::string & typeID) static
Definition at line 85 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getMaxDecel(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getEmergencyDecel()
double VehicleType::getEmergencyDecel (const std::string & typeID) static
Definition at line 91 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getEmergencyDecel(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getEmissionClass()
std::string VehicleType::getEmissionClass (const std::string & typeID) static
Definition at line 121 of file VehicleType.cpp.
References MSVehicleType::getEmissionClass(), PollutantsInterface::getName(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getHeight()
double VehicleType::getHeight (const std::string & typeID) static
Definition at line 145 of file VehicleType.cpp.
References MSVehicleType::getHeight(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getIDList()
std::vector< std::string > VehicleType::getIDList () static
Definition at line 42 of file VehicleType.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), and MSVehicleControl::insertVTypeIDs().
Referenced by TraCIServerAPI_VehicleType::processGet().
getImperfection()
double VehicleType::getImperfection (const std::string & typeID) static
Definition at line 103 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getImperfection(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getLateralAlignment()
std::string VehicleType::getLateralAlignment (const std::string & typeID) static
Definition at line 169 of file VehicleType.cpp.
References MSVehicleType::getPreferredLateralAlignment(), getVType(), and toString().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getLength()
double VehicleType::getLength (const std::string & typeID) static
Definition at line 49 of file VehicleType.cpp.
References MSVehicleType::getLength(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getMaxSpeed()
double VehicleType::getMaxSpeed (const std::string & typeID) static
Definition at line 55 of file VehicleType.cpp.
References MSVehicleType::getMaxSpeed(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getMaxSpeedLat()
double VehicleType::getMaxSpeedLat (const std::string & typeID) static
Definition at line 163 of file VehicleType.cpp.
References MSVehicleType::getMaxSpeedLat(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getMinGap()
double VehicleType::getMinGap (const std::string & typeID) static
Definition at line 133 of file VehicleType.cpp.
References MSVehicleType::getMinGap(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getMinGapLat()
double VehicleType::getMinGapLat (const std::string & typeID) static
Definition at line 157 of file VehicleType.cpp.
References MSVehicleType::getMinGapLat(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getParameter()
std::string VehicleType::getParameter (const std::string & typeID, const std::string & key) static
Definition at line 176 of file VehicleType.cpp.
References Parameterised::getParameter(), MSVehicleType::getParameter(), and getVType().
Referenced by TraCIServerAPI_VehicleType::processGet().
getShapeClass()
std::string VehicleType::getShapeClass (const std::string & typeID) static
Definition at line 127 of file VehicleType.cpp.
References MSVehicleType::getGuiShape(), getVehicleShapeName(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getSpeedDeviation()
double VehicleType::getSpeedDeviation (const std::string & typeID) static
Definition at line 73 of file VehicleType.cpp.
References Distribution_Parameterized::getParameter(), MSVehicleType::getSpeedFactor(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getSpeedFactor()
double VehicleType::getSpeedFactor (const std::string & typeID) static
Definition at line 67 of file VehicleType.cpp.
References Distribution_Parameterized::getParameter(), MSVehicleType::getSpeedFactor(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getTau()
double VehicleType::getTau (const std::string & typeID) static
Definition at line 109 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getHeadwayTime(), and getVType().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getVehicleClass()
std::string VehicleType::getVehicleClass (const std::string & typeID) static
Definition at line 115 of file VehicleType.cpp.
References MSVehicleType::getVehicleClass(), getVType(), and toString().
Referenced by TraCIServerAPI_VehicleType::getVariable().
getVType()
MSVehicleType * VehicleType::getVType (std::string id) static
Definition at line 320 of file VehicleType.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), and MSVehicleControl::getVType().
Referenced by copy(), getAccel(), getActionStepLength(), getApparentDecel(), getColor(), getDecel(), getEmergencyDecel(), getEmissionClass(), getHeight(), getImperfection(), getLateralAlignment(), getLength(), getMaxSpeed(), getMaxSpeedLat(), getMinGap(), getMinGapLat(), getParameter(), getShapeClass(), getSpeedDeviation(), getSpeedFactor(), getTau(), getVehicleClass(), getWidth(), setAccel(), setActionStepLength(), setApparentDecel(), setColor(), libsumo::Person::setColor(), setDecel(), setEmergencyDecel(), setEmissionClass(), setHeight(), libsumo::Person::setHeight(), setImperfection(), setLateralAlignment(), setLength(), libsumo::Person::setLength(), setMaxSpeed(), setMaxSpeedLat(), setMinGap(), libsumo::Person::setMinGap(), setMinGapLat(), setParameter(), setShapeClass(), setSpeedDeviation(), setSpeedFactor(), setTau(), setVehicleClass(), setWidth(), and libsumo::Person::setWidth().
getWidth()
double VehicleType::getWidth (const std::string & typeID) static
Definition at line 139 of file VehicleType.cpp.
References getVType(), and MSVehicleType::getWidth().
Referenced by TraCIServerAPI_VehicleType::getVariable().
operator=()
VehicleType& libsumo::VehicleType::operator= (const VehicleType & src) private
invalidated assignment operator
setAccel()
void VehicleType::setAccel (const std::string & typeID, double accel) static
Definition at line 248 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setMaxAccel().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setActionStepLength()
void VehicleType::setActionStepLength (const std::string & typeID, double actionStepLength, bool resetActionOffset) static
Definition at line 194 of file VehicleType.cpp.
References getVType(), SUMOVehicleParserHelper::processActionStepLength(), and MSVehicleType::setActionStepLength().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setApparentDecel()
void VehicleType::setApparentDecel (const std::string & typeID, double decel) static
Definition at line 266 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setApparentDecel().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setColor()
void VehicleType::setColor (const std::string & typeID, const TraCIColor & c) static
Definition at line 284 of file VehicleType.cpp.
References getVType(), libsumo::Helper::makeRGBColor(), and MSVehicleType::setColor().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setDecel()
void VehicleType::setDecel (const std::string & typeID, double decel) static
Definition at line 254 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setMaxDecel().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setEmergencyDecel()
void VehicleType::setEmergencyDecel (const std::string & typeID, double decel) static
Definition at line 260 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setEmergencyDecel().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setEmissionClass()
void VehicleType::setEmissionClass (const std::string & typeID, const std::string & clazz) static
Definition at line 218 of file VehicleType.cpp.
References PollutantsInterface::getClassByName(), getVType(), and MSVehicleType::setEmissionClass().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setHeight()
void VehicleType::setHeight (const std::string & typeID, double height) static
Definition at line 236 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setHeight().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setImperfection()
void VehicleType::setImperfection (const std::string & typeID, double imperfection) static
Definition at line 272 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setImperfection().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setLateralAlignment()
void VehicleType::setLateralAlignment (const std::string & typeID, const std::string & latAlignment) static
Definition at line 303 of file VehicleType.cpp.
References getVType(), SUMOXMLDefinitions::LateralAlignments, and MSVehicleType::setPreferredLateralAlignment().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setLength()
void VehicleType::setLength (const std::string & typeID, double length) static
Definition at line 182 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setLength().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setMaxSpeed()
void VehicleType::setMaxSpeed (const std::string & typeID, double speed) static
Definition at line 188 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setMaxSpeed().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setMaxSpeedLat()
void VehicleType::setMaxSpeedLat (const std::string & typeID, double speed) static
Definition at line 297 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setMaxSpeedLat().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setMinGap()
void VehicleType::setMinGap (const std::string & typeID, double minGap) static
Definition at line 242 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setMinGap().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setMinGapLat()
void VehicleType::setMinGapLat (const std::string & typeID, double minGapLat) static
Definition at line 291 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setMinGapLat().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setParameter()
void VehicleType::setParameter (const std::string & id, const std::string & name, const std::string & value) static
Definition at line 314 of file VehicleType.cpp.
References MSVehicleType::getParameter(), and getVType().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setShapeClass()
void VehicleType::setShapeClass (const std::string & typeID, const std::string & shapeClass) static
Definition at line 224 of file VehicleType.cpp.
References getVehicleShapeID(), getVType(), and MSVehicleType::setShape().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setSpeedDeviation()
void VehicleType::setSpeedDeviation (const std::string & typeID, double deviation) static
Definition at line 212 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setSpeedDeviation().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setSpeedFactor()
void VehicleType::setSpeedFactor (const std::string & typeID, double factor) static
Definition at line 206 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setSpeedFactor().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setTau()
void VehicleType::setTau (const std::string & typeID, double tau) static
Definition at line 278 of file VehicleType.cpp.
References MSVehicleType::getCarFollowModel(), getVType(), and MSCFModel::setHeadwayTime().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setVehicleClass()
void VehicleType::setVehicleClass (const std::string & typeID, const std::string & clazz) static
Definition at line 200 of file VehicleType.cpp.
References getVehicleClassID(), getVType(), and MSVehicleType::setVClass().
Referenced by TraCIServerAPI_VehicleType::setVariable().
setWidth()
void VehicleType::setWidth (const std::string & typeID, double width) static
Definition at line 230 of file VehicleType.cpp.
References getVType(), and MSVehicleType::setWidth().
Referenced by TraCIServerAPI_VehicleType::setVariable().
The documentation for this class was generated from the following files:
VehicleType.h
VehicleType.cpp