SUMO - Simulation of Urban MObility: MSAbstractLaneChangeModel Class Reference
MSAbstractLaneChangeModel Class Reference abstract
Interface for lane-change models.
#include <MSAbstractLaneChangeModel.h>
Data Structures
class MSLCMessager
A class responsible for exchanging messages between cars involved in lane-change interaction.
struct StateAndDist
Public Member Functions
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
virtual void changed ()=0
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void checkTraCICommands ()
Check for commands issued for the vehicle via TraCI and apply the appropriate state changes For the sublane case, this includes setting a new maneuver distance if appropriate.
void cleanupShadowLane ()
void cleanupTargetLane ()
virtual double computeSpeedLat (double latDist, double &maneuverDist)
decides the next lateral speed depending on the remaining lane change distance to be covered and updates maneuverDist according to lateral safety constraints.
virtual bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
MSLane * determineTargetLane (int &targetDir) const
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
double getAngleOffset () const
return the angle offset during a continuous change maneuver
double getCommittedSpeed () const
const std::vector< MSLane * > & getFurtherTargetLanes () const
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
double getManeuverDist () const
Returns the remaining unblocked distance for the current maneuver. (only used by sublane model)
int getOwnState () const
virtual std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this laneChangeModel. Throw exception for unsupported key
int getPrevState () const
const std::pair< int, int > & getSavedState (const int dir) const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< double > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicle's shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
MSLane * getShadowLane (const MSLane *lane, double posLat) const
return the shadow lane for the given lane and lateral offset
double getSpeedLat () const
return the lateral speed of the current lane change maneuver
MSLane * getTargetLane () const
Returns the lane the vehicle has committed to enter during a sublane lane change.
virtual void * inform (void *info, MSVehicle *sender)=0
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
void laneChangeOutput (const std::string &tag, MSLane *source, MSLane *target, int direction)
called once the vehicle ends a lane change manoeuvre (non-instant)
MSAbstractLaneChangeModel (MSVehicle &v, const LaneChangeModel model)
Constructor.
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
virtual double patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)=0
Called to adapt the speed in order to allow a lane change. It uses information on LC-related desired speed-changes from the call to wantsChange() at the end of the previous simulation step.
virtual void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
virtual void saveBlockerLength (double length)
reserve space at the end of the lane to avoid dead locks
void saveState (const int dir, const int stateWithoutTraCI, const int state)
void setFollowerGaps (CLeaderDist follower, double secGap)
void setFollowerGaps (const MSLeaderDistanceInfo &vehicles)
void setLeaderGaps (CLeaderDist, double secGap)
void setLeaderGaps (const MSLeaderDistanceInfo &vehicles)
void setManeuverDist (const double dist)
Updates the remaining distance for the current maneuver while it is continued within non-action steps (only used by sublane model)
void setNoShadowPartialOccupator (MSLane *lane)
void setOrigLeaderGaps (CLeaderDist, double secGap)
void setOrigLeaderGaps (const MSLeaderDistanceInfo &vehicles)
virtual void setOwnState (const int state)
virtual void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
void setSpeedLat (double speedLat)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
virtual bool sublaneChangeCompleted (const double latDist) const
whether the current change completes the manoeuvre
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderDistanceInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
virtual void updateSafeLatDist (const double travelledLatDist)
Updates the value of safe lateral distances (in SL2015) during maneuver continuation in non-action steps.
void updateShadowLane ()
void updateTargetLane ()
virtual int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, LaneChangeAction alternatives, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, double &latDist, double &targetDistLat, int &blocked)
virtual ~MSAbstractLaneChangeModel ()
Destructor.
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static bool haveLCOutput ()
whether lanechange-output is active
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
static bool outputLCEnded ()
whether start of maneuvers shall be recorede
static bool outputLCStarted ()
whether start of maneuvers shall be recorede
Static Public Attributes
static const double NO_NEIGHBOR
Protected Member Functions
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, double > &leader)
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
double myCommittedSpeed
the speed when committing to a change maneuver
std::vector< MSLane * > myFurtherTargetLanes
double myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
double myLastFollowerGap
double myLastFollowerSecureGap
double myLastLateralGapLeft
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
double myLastLateralGapRight
double myLastLeaderGap
the actual minimum longitudinal distances to vehicles on the target lane
double myLastLeaderSecureGap
the minimum longitudinal distances to vehicles on the target lane that would be necessary for stringent security
double myLastOrigLeaderGap
acutal and secure distance to closest leader vehicle on the original when performing lane change
double myLastOrigLeaderSecureGap
double myManeuverDist
The complete lateral distance the vehicle wants to travel to finish its maneuver Only used by sublane model, currently.
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
int myPreviousState
lane changing state from the previous simulation step
int myPreviousState2
lane changing state from step before the previous simulation step
std::map< int, std::pair< int, int > > mySavedStates
std::vector< MSLane * > myShadowFurtherLanes
std::vector< double > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
double mySpeedLat
the current lateral speed
MSLane * myTargetLane
The target lane for the vehicle's current maneuver.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCEndedOutput
static bool myLCOutput
whether to record lane-changing
static bool myLCStartedOutput
Private Member Functions
MSAbstractLaneChangeModel & operator= (const MSAbstractLaneChangeModel &s)
Invalidated assignment operator.
Private Attributes
bool myAmOpposite
whether the vehicle is driving in the opposite direction
std::vector< MSLink * > myApproachedByShadow
links which are approached by the shadow vehicle
SUMOTime myLastLaneChangeOffset
Detailed Description
Interface for lane-change models.
Definition at line 51 of file MSAbstractLaneChangeModel.h.
Constructor & Destructor Documentation
MSAbstractLaneChangeModel()
MSAbstractLaneChangeModel::MSAbstractLaneChangeModel (MSVehicle & v, const LaneChangeModel model)
Constructor.
Parameters
[in] v The vehicle this lane-changer belongs to
[in] model The type of lane change model
Definition at line 97 of file MSAbstractLaneChangeModel.cpp.
Referenced by outputLCEnded().
~MSAbstractLaneChangeModel()
MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel () virtual
Destructor.
Definition at line 125 of file MSAbstractLaneChangeModel.cpp.
Referenced by outputLCEnded().
Member Function Documentation
alreadyChanged()
bool MSAbstractLaneChangeModel::alreadyChanged () const inline
reset the flag whether a vehicle already moved to false
Definition at line 399 of file MSAbstractLaneChangeModel.h.
References myAlreadyChanged.
Referenced by MSLaneChanger::change().
build()
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 74 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::sameDirection().
cancelRequest()
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected
whether the influencer cancels the given request
Definition at line 347 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and myVehicle.
Referenced by MSLCM_LC2013::_wantsChange(), and MSLCM_SL2015::_wantsChangeSublane().
changed()
virtual void MSAbstractLaneChangeModel::changed () pure virtual
Implemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Referenced by decideDirection(), and primaryLaneChanged().
changedToOpposite()
void MSAbstractLaneChangeModel::changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
Definition at line 580 of file MSAbstractLaneChangeModel.cpp.
References myAlreadyChanged, and myAmOpposite.
Referenced by debugVehicle(), endLaneChangeManeuver(), MSVehicle::executeMove(), and startLaneChangeManeuver().
checkTraCICommands()
void MSAbstractLaneChangeModel::checkTraCICommands ()
Check for commands issued for the vehicle via TraCI and apply the appropriate state changes For the sublane case, this includes setting a new maneuver distance if appropriate.
Definition at line 534 of file MSAbstractLaneChangeModel.cpp.
References DEBUG_COND, gDebugFlag2, MSBaseVehicle::getID(), MSVehicle::getInfluencer(), MSVehicle::getLaneChangeModel(), MSVehicle::Influencer::getLatDist(), getOwnState(), MSGlobals::gLateralResolution, MSVehicle::hasInfluencer(), MSVehicle::influenceChangeDecision(), MSVehicle::lateralDistanceToLane(), LCA_LEFT, LCA_RIGHT, LCA_STAY, LCA_TRACI, myOwnState, myVehicle, MSVehicle::Influencer::resetLatDist(), setManeuverDist(), setOwnState(), SIMTIME, and toString().
Referenced by MSLaneChanger::checkTraCICommands(), and setParameter().
cleanupShadowLane()
void MSAbstractLaneChangeModel::cleanupShadowLane ()
Definition at line 306 of file MSAbstractLaneChangeModel.cpp.
References debugVehicle(), myNoPartiallyOccupatedByShadow, myShadowFurtherLanes, myShadowLane, myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by endLaneChangeManeuver(), resetChanged(), and MSVehicle::~MSVehicle().
cleanupTargetLane()
void MSAbstractLaneChangeModel::cleanupTargetLane ()
Definition at line 325 of file MSAbstractLaneChangeModel.cpp.
References debugVehicle(), myFurtherTargetLanes, myTargetLane, myVehicle, MSLane::resetManeuverReservation(), and SIMTIME.
Referenced by endLaneChangeManeuver(), resetChanged(), and MSVehicle::~MSVehicle().
computeSpeedLat()
virtual double MSAbstractLaneChangeModel::computeSpeedLat (double latDist, double & maneuverDist) inline virtual
decides the next lateral speed depending on the remaining lane change distance to be covered and updates maneuverDist according to lateral safety constraints.
Reimplemented in MSLCM_SL2015.
Definition at line 487 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::continueChangeSublane().
congested()
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual
Definition at line 162 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and myVehicle.
Referenced by MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
debugVehicle()
virtual bool MSAbstractLaneChangeModel::debugVehicle () const inline virtual
whether the current vehicles shall be debugged
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 317 of file MSAbstractLaneChangeModel.h.
References changedToOpposite().
Referenced by MSLaneChangerSublane::change(), cleanupShadowLane(), cleanupTargetLane(), getShadowLane(), MSLCM_SL2015::inform(), MSLaneChangerSublane::startChangeSublane(), updateShadowLane(), and updateTargetLane().
decideDirection()
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 287 of file MSAbstractLaneChangeModel.h.
References changed(), inform(), myModel, patchSpeed(), toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
determineTargetLane()
MSLane * MSAbstractLaneChangeModel::determineTargetLane (int & targetDir) const
Definition at line 472 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSBaseVehicle::getWidth(), MSLane::getWidth(), myManeuverDist, myShadowLane, and myVehicle.
Referenced by resetChanged(), and updateTargetLane().
endLaneChangeManeuver()
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE)
Definition at line 263 of file MSAbstractLaneChangeModel.cpp.
References changedToOpposite(), cleanupShadowLane(), cleanupTargetLane(), MSVehicle::fixPosition(), myAmOpposite, myLaneChangeCompletion, myNoPartiallyOccupatedByShadow, myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::processLaneAdvances(), resetChanged(), and updateShadowLane().
getAngleOffset()
double MSAbstractLaneChangeModel::getAngleOffset () const
return the angle offset during a continuous change maneuver
Definition at line 504 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, myLaneChangeDirection, pastMidpoint(), and STEPS2TIME.
Referenced by getLaneChangeDirection().
getCommittedSpeed()
double MSAbstractLaneChangeModel::getCommittedSpeed () const inline
Definition at line 472 of file MSAbstractLaneChangeModel.h.
References myCommittedSpeed.
Referenced by MSVehicle::planMoveInternal(), and MSLaneChangerSublane::startChangeSublane().
getFurtherTargetLanes()
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getFurtherTargetLanes () const inline
Definition at line 365 of file MSAbstractLaneChangeModel.h.
References myFurtherTargetLanes.
Referenced by MSVehicle::getBackPositionOnLane(), and MSVehicle::getLatOffset().
getLaneChangeDirection()
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline
return the direction of the current lane change maneuver
Definition at line 388 of file MSAbstractLaneChangeModel.h.
References getAngleOffset(), getShadowDirection(), and myLaneChangeDirection.
Referenced by MSLaneChanger::continueChange().
getLastLaneChangeOffset()
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline
Definition at line 369 of file MSAbstractLaneChangeModel.h.
References myLastLaneChangeOffset.
getManeuverDist()
double MSAbstractLaneChangeModel::getManeuverDist () const
Returns the remaining unblocked distance for the current maneuver. (only used by sublane model)
Definition at line 156 of file MSAbstractLaneChangeModel.cpp.
References myManeuverDist.
Referenced by MSLaneChangerSublane::change(), MSLaneChangerSublane::continueChangeSublane(), MSVehicle::getLatOffset(), GUIVehicle::getManeuverDist(), getPrevState(), MSLeaderInfo::getSubLanes(), MSLaneChangerSublane::startChangeSublane(), and MSLCM_SL2015::updateGaps().
getOwnState()
int MSAbstractLaneChangeModel::getOwnState () const inline
Definition at line 170 of file MSAbstractLaneChangeModel.h.
References myOwnState.
Referenced by MSLaneChanger::applyTraCICommands(), MSLaneChanger::change(), MSLaneChanger::checkTraCICommands(), checkTraCICommands(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSVehicle::setBlinkerInformation(), and MSLaneChangerSublane::startChangeSublane().
getParameter()
virtual std::string MSAbstractLaneChangeModel::getParameter (const std::string & key) const inline virtual
try to retrieve the given parameter from this laneChangeModel. Throw exception for unsupported key
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 494 of file MSAbstractLaneChangeModel.h.
References myModel, and toString().
Referenced by libsumo::Vehicle::getParameter().
getPrevState()
int MSAbstractLaneChangeModel::getPrevState () const inline
at the time of this call myPreviousState already holds the new value
Definition at line 174 of file MSAbstractLaneChangeModel.h.
References getManeuverDist(), myPreviousState2, setManeuverDist(), setOwnState(), and updateSafeLatDist().
Referenced by MSLaneChangerSublane::outputLCStarted().
getSavedState()
const std::pair<int, int>& MSAbstractLaneChangeModel::getSavedState (const int dir) const inline
Definition at line 189 of file MSAbstractLaneChangeModel.h.
References mySavedStates.
Referenced by libsumo::Vehicle::getLaneChangeState().
getShadowDirection()
int MSAbstractLaneChangeModel::getShadowDirection () const
return the direction in which the current shadow lane lies
Definition at line 408 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), isChangingLanes(), myLaneChangeDirection, myShadowLane, myVehicle, and pastMidpoint().
Referenced by MSLaneChanger::continueChange(), getLaneChangeDirection(), MSVehicle::processLinkAproaches(), and GUIVehicle::selectBlockingFoes().
getShadowFurtherLanes()
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline
Definition at line 350 of file MSAbstractLaneChangeModel.h.
References myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
getShadowFurtherLanesPosLat()
const std::vector<double>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline
Definition at line 354 of file MSAbstractLaneChangeModel.h.
References myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
getShadowLane() [1/3]
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline
Returns the lane the vehicle's shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 335 of file MSAbstractLaneChangeModel.h.
References myShadowLane.
Referenced by MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), getShadowLane(), MSVehicle::isFrontOnLane(), MSLane::isInsertionSuccess(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and updateShadowLane().
getShadowLane() [2/3]
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const
return the shadow lane for the given lane
Definition at line 300 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getLateralPositionOnLane(), getShadowLane(), and myVehicle.
getShadowLane() [3/3]
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane, double posLat) const
return the shadow lane for the given lane and lateral offset
Definition at line 278 of file MSAbstractLaneChangeModel.cpp.
References debugVehicle(), MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSLane::getParallelLane(), isChangingLanes(), myLaneChangeCompletion, myNoPartiallyOccupatedByShadow, myVehicle, NUMERICAL_EPS, and SIMTIME.
getSpeedLat()
double MSAbstractLaneChangeModel::getSpeedLat () const inline
return the lateral speed of the current lane change maneuver
Definition at line 477 of file MSAbstractLaneChangeModel.h.
References mySpeedLat.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::continueChange(), GUIVehicle::getParameterWindow(), and MSLeaderInfo::getSubLanes().
getTargetLane()
MSLane* MSAbstractLaneChangeModel::getTargetLane () const inline
Returns the lane the vehicle has committed to enter during a sublane lane change.
Returns
The vehicle's target lane.
Definition at line 361 of file MSAbstractLaneChangeModel.h.
References myTargetLane.
Referenced by GUIVehicle::getParameterWindow(), and MSLaneChangerSublane::startChangeSublane().
haveLCOutput()
static bool MSAbstractLaneChangeModel::haveLCOutput () inline static
whether lanechange-output is active
Definition at line 147 of file MSAbstractLaneChangeModel.h.
References myLCOutput.
Referenced by MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), and MSLaneChangerSublane::outputLCStarted().
inform()
virtual void* MSAbstractLaneChangeModel::inform (void * info, MSVehicle * sender) pure virtual
Implemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Referenced by decideDirection(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), and MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader().
initGlobalOptions()
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static
init global model parameters
Definition at line 65 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), myAllowOvertakingRight, myLCEndedOutput, myLCOutput, and myLCStartedOutput.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection(), and MSFrame::setMSGlobals().
initLastLaneChangeOffset()
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected
Definition at line 354 of file MSAbstractLaneChangeModel.cpp.
References myLastLaneChangeOffset.
Referenced by primaryLaneChanged().
isChangingLanes()
bool MSAbstractLaneChangeModel::isChangingLanes () const inline
return true if the vehicle currently performs a lane change maneuver
Definition at line 383 of file MSAbstractLaneChangeModel.h.
References myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), getShadowDirection(), getShadowLane(), and updateShadowLane().
isOpposite()
bool MSAbstractLaneChangeModel::isOpposite () const inline
Definition at line 468 of file MSAbstractLaneChangeModel.h.
References myAmOpposite.
Referenced by MSLCM_LC2013::_wantsChange(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtInsertion(), MSLink::getLeaderInfo(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSLCM_LC2013::informLeader(), and MSVehicle::planMoveInternal().
laneChangeOutput()
void MSAbstractLaneChangeModel::laneChangeOutput (const std::string & tag, MSLane * source, MSLane * target, int direction)
called once the vehicle ends a lane change manoeuvre (non-instant)
Definition at line 225 of file MSAbstractLaneChangeModel.cpp.
References OutputDevice::closeTag(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gLateralResolution, LCA_LEFT, LCA_RIGHT, myLastFollowerGap, myLastFollowerSecureGap, myLastLateralGapLeft, myLastLateralGapRight, myLastLeaderGap, myLastLeaderSecureGap, myLastOrigLeaderGap, myLastOrigLeaderSecureGap, myLCOutput, myOwnState, myVehicle, NO_NEIGHBOR, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_POSITION, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, SUMO_ATTR_TYPE, time2string(), toString(), MSVehicle::updateDriveItems(), and OutputDevice::writeAttr().
Referenced by MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), primaryLaneChanged(), and setNoShadowPartialOccupator().
operator=()
MSAbstractLaneChangeModel& MSAbstractLaneChangeModel::operator= (const MSAbstractLaneChangeModel & s) private
Invalidated assignment operator.
outputLCEnded()
static bool MSAbstractLaneChangeModel::outputLCEnded () inline static
whether start of maneuvers shall be recorede
Definition at line 157 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel(), myLCEndedOutput, and ~MSAbstractLaneChangeModel().
Referenced by MSLaneChangerSublane::outputLCEnded().
outputLCStarted()
static bool MSAbstractLaneChangeModel::outputLCStarted () inline static
whether start of maneuvers shall be recorede
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References myLCStartedOutput.
Referenced by MSLaneChangerSublane::outputLCStarted().
pastMidpoint()
bool MSAbstractLaneChangeModel::pastMidpoint () const inline
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 375 of file MSAbstractLaneChangeModel.h.
References myLaneChangeCompletion, and remainingTime().
Referenced by getAngleOffset(), getShadowDirection(), and updateCompletion().
patchSpeed()
virtual double MSAbstractLaneChangeModel::patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel) pure virtual
Called to adapt the speed in order to allow a lane change. It uses information on LC-related desired speed-changes from the call to wantsChange() at the end of the previous simulation step.
It is guaranteed that min<=wanted<=max, but the implementation needs to make sure that the return value is between min and max.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Referenced by decideDirection(), MSCFModel_Rail::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussX::moveHelper(), and MSCFModel::moveHelper().
predInteraction()
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, double > & leader) protected virtual
Definition at line 182 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), myCarFollowModel, and myVehicle.
Referenced by MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
prepareStep()
virtual void MSAbstractLaneChangeModel::prepareStep () inline virtual
Reimplemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Definition at line 204 of file MSAbstractLaneChangeModel.h.
References LCA_UNKNOWN, myCommittedSpeed, myLastFollowerGap, myLastFollowerSecureGap, myLastLateralGapLeft, myLastLateralGapRight, myLastLeaderGap, myLastLeaderSecureGap, myLastOrigLeaderGap, myLastOrigLeaderSecureGap, NO_NEIGHBOR, and saveState().
Referenced by MSVehicle::executeMove(), MSLCM_DK2008::prepareStep(), MSLCM_LC2013::prepareStep(), and MSLCM_SL2015::prepareStep().
primaryLaneChanged()
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction)
called once when the vehicles primary lane changes
Definition at line 214 of file MSAbstractLaneChangeModel.cpp.
References changed(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), initLastLaneChangeOffset(), laneChangeOutput(), MSVehicle::leaveLane(), MSLane::leftByLaneChange(), myVehicle, and MSMoveReminder::NOTIFICATION_LANE_CHANGE.
Referenced by MSLaneChanger::continueChange(), setNoShadowPartialOccupator(), and startLaneChangeManeuver().
remainingTime()
SUMOTime MSAbstractLaneChangeModel::remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 511 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and myLaneChangeCompletion.
Referenced by pastMidpoint().
removeShadowApproachingInformation()
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const
Definition at line 523 of file MSAbstractLaneChangeModel.cpp.
References myApproachedByShadow, and myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and sublaneChangeCompleted().
resetChanged()
void MSAbstractLaneChangeModel::resetChanged () inline
reset the flag whether a vehicle already moved to false
Definition at line 404 of file MSAbstractLaneChangeModel.h.
References cleanupShadowLane(), cleanupTargetLane(), determineTargetLane(), endLaneChangeManeuver(), myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, startLaneChangeManeuver(), updateCompletion(), updateShadowLane(), and updateTargetLane().
Referenced by MSVehicle::planMove().
saveBlockerLength()
virtual void MSAbstractLaneChangeModel::saveBlockerLength (double length) inline virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented in MSLCM_LC2013, and MSLCM_SL2015.
Definition at line 440 of file MSAbstractLaneChangeModel.h.
References UNUSED_PARAMETER.
Referenced by MSLCM_LC2013::saveBlockerLength().
saveState()
void MSAbstractLaneChangeModel::saveState (const int dir, const int stateWithoutTraCI, const int state) inline
Definition at line 193 of file MSAbstractLaneChangeModel.h.
References mySavedStates, setFollowerGaps(), setLeaderGaps(), and setOrigLeaderGaps().
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), and prepareStep().
setFollowerGaps() [1/2]
void MSAbstractLaneChangeModel::setFollowerGaps (CLeaderDist follower, double secGap)
Definition at line 586 of file MSAbstractLaneChangeModel.cpp.
References myLastFollowerGap, and myLastFollowerSecureGap.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and saveState().
setFollowerGaps() [2/2]
void MSAbstractLaneChangeModel::setFollowerGaps (const MSLeaderDistanceInfo & vehicles)
Definition at line 610 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), myLastFollowerGap, myLastFollowerSecureGap, and myVehicle.
setLeaderGaps() [1/2]
void MSAbstractLaneChangeModel::setLeaderGaps (CLeaderDist leader, double secGap)
Definition at line 594 of file MSAbstractLaneChangeModel.cpp.
References MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), myLastLeaderGap, myLastLeaderSecureGap, and myVehicle.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and saveState().
setLeaderGaps() [2/2]
void MSAbstractLaneChangeModel::setLeaderGaps (const MSLeaderDistanceInfo & vehicles)
Definition at line 629 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), myLastLeaderGap, myLastLeaderSecureGap, and myVehicle.
setManeuverDist()
void MSAbstractLaneChangeModel::setManeuverDist (const double dist)
Updates the remaining distance for the current maneuver while it is continued within non-action steps (only used by sublane model)
Definition at line 142 of file MSAbstractLaneChangeModel.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), myManeuverDist, myVehicle, and SIMTIME.
Referenced by MSLaneChangerSublane::abortLCManeuver(), MSLaneChangerSublane::change(), checkTraCICommands(), getPrevState(), and MSLaneChangerSublane::startChangeSublane().
setNoShadowPartialOccupator()
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline
Definition at line 448 of file MSAbstractLaneChangeModel.h.
References laneChangeOutput(), myNoPartiallyOccupatedByShadow, and primaryLaneChanged().
Referenced by MSVehicle::enterLaneAtLaneChange().
setOrigLeaderGaps() [1/2]
void MSAbstractLaneChangeModel::setOrigLeaderGaps (CLeaderDist leader, double secGap)
Definition at line 602 of file MSAbstractLaneChangeModel.cpp.
References MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), myLastOrigLeaderGap, myLastOrigLeaderSecureGap, and myVehicle.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and saveState().
setOrigLeaderGaps() [2/2]
void MSAbstractLaneChangeModel::setOrigLeaderGaps (const MSLeaderDistanceInfo & vehicles)
Definition at line 648 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), myLastOrigLeaderGap, myLastOrigLeaderSecureGap, and myVehicle.
setOwnState()
void MSAbstractLaneChangeModel::setOwnState (const int state) virtual
Reimplemented in MSLCM_SL2015.
Definition at line 129 of file MSAbstractLaneChangeModel.cpp.
References myOwnState, myPreviousState, and myPreviousState2.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), checkTraCICommands(), getPrevState(), and MSLCM_SL2015::setOwnState().
setParameter()
virtual void MSAbstractLaneChangeModel::setParameter (const std::string & key, const std::string & value) inline virtual
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
Reimplemented in MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 499 of file MSAbstractLaneChangeModel.h.
References checkTraCICommands(), myModel, toString(), and UNUSED_PARAMETER.
Referenced by libsumo::Vehicle::setParameter().
setShadowApproachingInformation()
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const
set approach information for the shadow vehicle
Definition at line 517 of file MSAbstractLaneChangeModel.cpp.
References myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and sublaneChangeCompleted().
setShadowLane()
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline
set the shadow lane
Definition at line 346 of file MSAbstractLaneChangeModel.h.
References myShadowLane.
setShadowPartialOccupator()
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline
Definition at line 444 of file MSAbstractLaneChangeModel.h.
References myPartiallyOccupatedByShadow.
setSpeedLat()
void MSAbstractLaneChangeModel::setSpeedLat (double speedLat) inline
Definition at line 481 of file MSAbstractLaneChangeModel.h.
References mySpeedLat.
Referenced by MSLaneChangerSublane::abortLCManeuver(), and MSLaneChangerSublane::startChangeSublane().
startLaneChangeManeuver()
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction)
start the lane change maneuver and return whether it continues
Definition at line 195 of file MSAbstractLaneChangeModel.cpp.
References changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, myLaneChangeDirection, mySpeedLat, myVehicle, primaryLaneChanged(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::applyTraCICommands(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeToNewLane(), resetChanged(), and MSLaneChanger::startChange().
sublaneChangeCompleted()
virtual bool MSAbstractLaneChangeModel::sublaneChangeCompleted (const double latDist) const inline virtual
whether the current change completes the manoeuvre
Definition at line 459 of file MSAbstractLaneChangeModel.h.
References myModel, removeShadowApproachingInformation(), setShadowApproachingInformation(), toString(), and UNUSED_PARAMETER.
unchanged()
void MSAbstractLaneChangeModel::unchanged () inline
Definition at line 324 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
updateCompletion()
bool MSAbstractLaneChangeModel::updateCompletion ()
Definition at line 255 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, and pastMidpoint().
Referenced by MSLaneChanger::continueChange(), and resetChanged().
updateExpectedSublaneSpeeds()
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderDistanceInfo & ahead, int sublaneOffset, int laneIndex) inline virtual
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 279 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
updateSafeLatDist()
void MSAbstractLaneChangeModel::updateSafeLatDist (const double travelledLatDist) virtual
Updates the value of safe lateral distances (in SL2015) during maneuver continuation in non-action steps.
Reimplemented in MSLCM_SL2015.
Definition at line 136 of file MSAbstractLaneChangeModel.cpp.
References UNUSED_PARAMETER.
Referenced by getPrevState(), and MSLaneChangerSublane::startChangeSublane().
updateShadowLane()
void MSAbstractLaneChangeModel::updateShadowLane ()
Definition at line 363 of file MSAbstractLaneChangeModel.cpp.
References debugVehicle(), endLaneChangeManeuver(), MSLinkContHelper::getConnectingLink(), MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), getShadowLane(), isChangingLanes(), myShadowFurtherLanes, myShadowFurtherLanesPosLat, myShadowLane, myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), resetChanged(), and MSLaneChangerSublane::startChangeSublane().
updateTargetLane()
void MSAbstractLaneChangeModel::updateTargetLane ()
Definition at line 425 of file MSAbstractLaneChangeModel.cpp.
References debugVehicle(), determineTargetLane(), MSVehicle::getFurtherLanes(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getParallelLane(), myFurtherTargetLanes, myTargetLane, myVehicle, MSLane::resetManeuverReservation(), MSLane::setManeuverReservation(), SIMTIME, and toString().
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), resetChanged(), and MSLaneChangerSublane::startChangeSublane().
wantsChange()
virtual int MSAbstractLaneChangeModel::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) inline virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_DK2008.
Definition at line 223 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChanger::checkChange().
wantsChangeSublane()
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, LaneChangeAction alternatives, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, double & latDist, double & targetDistLat, int & blocked) inline virtual
Reimplemented in MSLCM_SL2015.
Definition at line 246 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
Field Documentation
myAllowOvertakingRight
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected
whether overtaking on the right is permitted
Definition at line 609 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), and initGlobalOptions().
myAlreadyChanged
bool MSAbstractLaneChangeModel::myAlreadyChanged protected
whether the vehicle has already moved this step
Definition at line 550 of file MSAbstractLaneChangeModel.h.
Referenced by alreadyChanged(), changedToOpposite(), and resetChanged().
myAmOpposite
bool MSAbstractLaneChangeModel::myAmOpposite private
whether the vehicle is driving in the opposite direction
Definition at line 627 of file MSAbstractLaneChangeModel.h.
Referenced by changedToOpposite(), endLaneChangeManeuver(), and isOpposite().
myApproachedByShadow
std::vector<MSLink*> MSAbstractLaneChangeModel::myApproachedByShadow mutable private
links which are approached by the shadow vehicle
Definition at line 624 of file MSAbstractLaneChangeModel.h.
Referenced by removeShadowApproachingInformation(), and setShadowApproachingInformation().
myCarFollowModel
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected
The vehicle's car following model.
Definition at line 578 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), predInteraction(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
myCommittedSpeed
double MSAbstractLaneChangeModel::myCommittedSpeed protected
the speed when committing to a change maneuver
Definition at line 537 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::commitManoeuvre(), getCommittedSpeed(), and prepareStep().
myFurtherTargetLanes
std::vector<MSLane*> MSAbstractLaneChangeModel::myFurtherTargetLanes protected
Definition at line 575 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupTargetLane(), getFurtherTargetLanes(), and updateTargetLane().
myLaneChangeCompletion
double MSAbstractLaneChangeModel::myLaneChangeCompletion protected
progress of the lane change maneuver 0:started, 1:complete
Definition at line 540 of file MSAbstractLaneChangeModel.h.
Referenced by endLaneChangeManeuver(), getAngleOffset(), getShadowLane(), isChangingLanes(), pastMidpoint(), remainingTime(), startLaneChangeManeuver(), and updateCompletion().
myLaneChangeDirection
int MSAbstractLaneChangeModel::myLaneChangeDirection protected
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 543 of file MSAbstractLaneChangeModel.h.
Referenced by getAngleOffset(), getLaneChangeDirection(), getShadowDirection(), and startLaneChangeManeuver().
myLastFollowerGap
double MSAbstractLaneChangeModel::myLastFollowerGap protected
Definition at line 596 of file MSAbstractLaneChangeModel.h.
Referenced by laneChangeOutput(), prepareStep(), and setFollowerGaps().
myLastFollowerSecureGap
double MSAbstractLaneChangeModel::myLastFollowerSecureGap protected
Definition at line 599 of file MSAbstractLaneChangeModel.h.
Referenced by laneChangeOutput(), prepareStep(), and setFollowerGaps().
myLastLaneChangeOffset
SUMOTime MSAbstractLaneChangeModel::myLastLaneChangeOffset private
Definition at line 621 of file MSAbstractLaneChangeModel.h.
Referenced by getLastLaneChangeOffset(), initLastLaneChangeOffset(), and unchanged().
myLastLateralGapLeft
double MSAbstractLaneChangeModel::myLastLateralGapLeft protected
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
Definition at line 591 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), laneChangeOutput(), prepareStep(), and MSLCM_SL2015::updateGaps().
myLastLateralGapRight
double MSAbstractLaneChangeModel::myLastLateralGapRight protected
Definition at line 592 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), laneChangeOutput(), prepareStep(), and MSLCM_SL2015::updateGaps().
myLastLeaderGap
double MSAbstractLaneChangeModel::myLastLeaderGap protected
the actual minimum longitudinal distances to vehicles on the target lane
Definition at line 595 of file MSAbstractLaneChangeModel.h.
Referenced by laneChangeOutput(), prepareStep(), and setLeaderGaps().
myLastLeaderSecureGap
double MSAbstractLaneChangeModel::myLastLeaderSecureGap protected
the minimum longitudinal distances to vehicles on the target lane that would be necessary for stringent security
Definition at line 598 of file MSAbstractLaneChangeModel.h.
Referenced by laneChangeOutput(), prepareStep(), and setLeaderGaps().
myLastOrigLeaderGap
double MSAbstractLaneChangeModel::myLastOrigLeaderGap protected
acutal and secure distance to closest leader vehicle on the original when performing lane change
Definition at line 601 of file MSAbstractLaneChangeModel.h.
Referenced by laneChangeOutput(), prepareStep(), and setOrigLeaderGaps().
myLastOrigLeaderSecureGap
double MSAbstractLaneChangeModel::myLastOrigLeaderSecureGap protected
Definition at line 602 of file MSAbstractLaneChangeModel.h.
Referenced by laneChangeOutput(), prepareStep(), and setOrigLeaderGaps().
myLCEndedOutput
bool MSAbstractLaneChangeModel::myLCEndedOutput static protected
Definition at line 614 of file MSAbstractLaneChangeModel.h.
Referenced by initGlobalOptions(), and outputLCEnded().
myLCOutput
bool MSAbstractLaneChangeModel::myLCOutput static protected
whether to record lane-changing
Definition at line 612 of file MSAbstractLaneChangeModel.h.
Referenced by haveLCOutput(), initGlobalOptions(), and laneChangeOutput().
myLCStartedOutput
bool MSAbstractLaneChangeModel::myLCStartedOutput static protected
Definition at line 613 of file MSAbstractLaneChangeModel.h.
Referenced by initGlobalOptions(), and outputLCStarted().
myManeuverDist
double MSAbstractLaneChangeModel::myManeuverDist protected
The complete lateral distance the vehicle wants to travel to finish its maneuver Only used by sublane model, currently.
Definition at line 547 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), determineTargetLane(), getManeuverDist(), MSLCM_SL2015::prepareStep(), setManeuverDist(), MSLCM_SL2015::setOwnState(), and MSLCM_SL2015::wantsChange().
myModel
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected
the type of this model
Definition at line 581 of file MSAbstractLaneChangeModel.h.
Referenced by computeSpeedLat(), decideDirection(), MSLCM_LC2013::getParameter(), MSLCM_SL2015::getParameter(), getParameter(), MSLCM_LC2013::setParameter(), MSLCM_SL2015::setParameter(), setParameter(), sublaneChangeCompleted(), updateExpectedSublaneSpeeds(), wantsChange(), and wantsChangeSublane().
myNoPartiallyOccupatedByShadow
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected
Definition at line 588 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), endLaneChangeManeuver(), getShadowLane(), and setNoShadowPartialOccupator().
myOwnState
int MSAbstractLaneChangeModel::myOwnState protected
The current state of the vehicle.
Definition at line 525 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), MSLCM_DK2008::changed(), MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), checkTraCICommands(), getOwnState(), MSLCM_DK2008::inform(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), laneChangeOutput(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), MSLCM_LC2013::prepareStep(), MSLCM_SL2015::prepareStep(), setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
myPartiallyOccupatedByShadow
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected
list of lanes where the shadow vehicle is partial occupator
Definition at line 584 of file MSAbstractLaneChangeModel.h.
Referenced by setShadowPartialOccupator().
myPreviousState
int MSAbstractLaneChangeModel::myPreviousState protected
lane changing state from the previous simulation step
Definition at line 527 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), and setOwnState().
myPreviousState2
int MSAbstractLaneChangeModel::myPreviousState2 protected
lane changing state from step before the previous simulation step
Definition at line 529 of file MSAbstractLaneChangeModel.h.
Referenced by getPrevState(), and setOwnState().
mySavedStates
std::map<int, std::pair<int, int> > MSAbstractLaneChangeModel::mySavedStates protected
Definition at line 531 of file MSAbstractLaneChangeModel.h.
Referenced by getSavedState(), and saveState().
myShadowFurtherLanes
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected
Definition at line 556 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), getShadowFurtherLanes(), and updateShadowLane().
myShadowFurtherLanesPosLat
std::vector<double> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected
Definition at line 557 of file MSAbstractLaneChangeModel.h.
Referenced by getShadowFurtherLanesPosLat(), and updateShadowLane().
myShadowLane
MSLane* MSAbstractLaneChangeModel::myShadowLane protected
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 553 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), determineTargetLane(), getShadowDirection(), getShadowLane(), setShadowLane(), and updateShadowLane().
mySpeedLat
double MSAbstractLaneChangeModel::mySpeedLat protected
the current lateral speed
Definition at line 534 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::computeSpeedLat(), getSpeedLat(), setSpeedLat(), startLaneChangeManeuver(), and MSLCM_SL2015::wantsChangeSublane().
myTargetLane
MSLane* MSAbstractLaneChangeModel::myTargetLane protected
The target lane for the vehicle's current maneuver.
Note
This is used by the sublane model to register the vehicle at lanes, it will reach within the current action step, so vehicles on that lane may react to the started lc-maneuver during the car-following process. If the shadow lane is the same as the lc maneuver target, myTargetLane is set to nullptr. The current shadow lanes and further lanes should always be updated before updating the target lane.
Definition at line 567 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupTargetLane(), getTargetLane(), and updateTargetLane().
myVehicle
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected
The vehicle this lane-changer belongs to.
Definition at line 522 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSLCM_SL2015::addLCSpeedAdvice(), MSLCM_LC2013::addLCSpeedAdvice(), cancelRequest(), MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), checkTraCICommands(), cleanupShadowLane(), cleanupTargetLane(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::commitManoeuvre(), MSLCM_SL2015::computeSpeedGain(), MSLCM_SL2015::computeSpeedLat(), congested(), MSLCM_SL2015::decideDirection(), determineTargetLane(), endLaneChangeManeuver(), MSLCM_LC2013::getRoundaboutAheadInfo(), getShadowDirection(), getShadowLane(), MSLCM_SL2015::getSublaneWidth(), MSLCM_SL2015::getWidth(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), laneChangeOutput(), MSLCM_SL2015::msg(), MSLCM_LC2013::MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), predInteraction(), MSLCM_SL2015::prepareStep(), primaryLaneChanged(), removeShadowApproachingInformation(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), setFollowerGaps(), setLeaderGaps(), setManeuverDist(), setOrigLeaderGaps(), MSLCM_SL2015::setOwnState(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), startLaneChangeManeuver(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), updateShadowLane(), updateTargetLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
NO_NEIGHBOR
const double MSAbstractLaneChangeModel::NO_NEIGHBOR static
Definition at line 509 of file MSAbstractLaneChangeModel.h.
Referenced by MSLaneChanger::checkChange(), MSLCM_SL2015::keepLatGap(), laneChangeOutput(), and prepareStep().
The documentation for this class was generated from the following files:
MSAbstractLaneChangeModel.h
MSAbstractLaneChangeModel.cpp