SUMO - Simulation of Urban MObility: CHRouter< E, V, PF > Class Template Reference
CHRouter< E, V, PF > Class Template Reference
Computes the shortest path through a contracted network.
#include <CHRouter.h>
Data Structures
struct EdgeInfo
class Unidirectional
Public Types
typedef std::pair< const EdgeInfo *, const EdgeInfo * > Meeting
A meeting point of the two search scopes.
typedef double(* Operation) (const E *const, const V *const, double)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
void buildContractionHierarchy (SUMOTime time, const V *const vehicle)
void buildPathFromMeeting (Meeting meeting, std::vector< const E *> &into) const
normal routing methods
CHRouter (const std::vector< E *> &edges, bool unbuildIsWarning, Operation operation, const SUMOVehicleClass svc, SUMOTime weightPeriod, bool validatePermissions)
Constructor.
CHRouter (const std::vector< E *> &edges, bool unbuildIsWarning, Operation operation, const SUMOVehicleClass svc, SUMOTime weightPeriod, const typename CHBuilder< E, V >::Hierarchy *hierarchy)
Cloning constructor.
virtual SUMOAbstractRouter< E, V > * clone ()
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> &into)
Builds the route between the given edges using the minimum traveltime in the contracted graph.
void endQuery (int visits)
double getEffort (const E *const e, const V *const v, double t) const
double recomputeCosts (const std::vector< const E *> &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~CHRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Member Functions
const E * getVia (const E *forwardFrom, const E *forwardTo) const
Private Attributes
Unidirectional myBackwardSearch
const std::vector< E * > & myEdges
all edges with numerical ids
MsgHandler *const myErrorMsgHandler
the handler for routing errors
Unidirectional myForwardSearch
the unidirectional search queues
const CHBuilder< E, V >::Hierarchy * myHierarchy
CHBuilder< E, V > * myHierarchyBuilder
const SUMOVehicleClass mySVC
the permissions for which the hierarchy was constructed
SUMOTime myValidUntil
the validity duration of the current hierarchy (exclusive)
const SUMOTime myWeightPeriod
the validity duration of one weight interval
Detailed Description
template<class E, class V, class PF>
class CHRouter< E, V, PF >
Computes the shortest path through a contracted network.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 69 of file CHRouter.h.
Member Typedef Documentation
Meeting
template<class E, class V, class PF> typedef std::pair<const EdgeInfo*, const EdgeInfo*> CHRouter< E, V, PF >::Meeting
A meeting point of the two search scopes.
Definition at line 110 of file CHRouter.h.
Operation
template<class E, class V, class PF> typedef double(* CHRouter< E, V, PF >::Operation) (const E *const, const V *const, double)
Type of the function that is used to retrieve the edge effort.
Definition at line 73 of file CHRouter.h.
Constructor & Destructor Documentation
CHRouter() [1/2]
template<class E, class V, class PF> CHRouter< E, V, PF >::CHRouter (const std::vector< E *> & edges, bool unbuildIsWarning, Operation operation, const SUMOVehicleClass svc, SUMOTime weightPeriod, bool validatePermissions) inline
Constructor.
Parameters
[in] validatePermissions Whether a multi-permission hierarchy shall be built If set to false, the net is pruned in synchronize() and the hierarchy is tailored to the svc
Definition at line 266 of file CHRouter.h.
CHRouter() [2/2]
template<class E, class V, class PF> CHRouter< E, V, PF >::CHRouter (const std::vector< E *> & edges, bool unbuildIsWarning, Operation operation, const SUMOVehicleClass svc, SUMOTime weightPeriod, const typename CHBuilder< E, V >::Hierarchy * hierarchy) inline
Cloning constructor.
Definition at line 284 of file CHRouter.h.
~CHRouter()
template<class E, class V, class PF> virtual CHRouter< E, V, PF >::~CHRouter () inline virtual
Destructor.
Definition at line 301 of file CHRouter.h.
References CHRouter< E, V, PF >::myHierarchy, and CHRouter< E, V, PF >::myHierarchyBuilder.
Member Function Documentation
buildContractionHierarchy()
template<class E, class V, class PF> void CHRouter< E, V, PF >::buildContractionHierarchy (SUMOTime time, const V *const vehicle) inline
Definition at line 415 of file CHRouter.h.
References CHRouter< E, V, PF >::myHierarchy, CHRouter< E, V, PF >::myHierarchyBuilder, CHRouter< E, V, PF >::myValidUntil, and CHRouter< E, V, PF >::myWeightPeriod.
Referenced by CHRouter< E, V, PF >::compute().
buildPathFromMeeting()
template<class E, class V, class PF> void CHRouter< E, V, PF >::buildPathFromMeeting (Meeting meeting, std::vector< const E *> & into) const inline
normal routing methods
Builds the path from marked edges
Definition at line 382 of file CHRouter.h.
References CHRouter< E, V, PF >::EdgeInfo::edge, CHRouter< E, V, PF >::getVia(), and CHRouter< E, V, PF >::EdgeInfo::prev.
Referenced by CHRouter< E, V, PF >::compute().
clone()
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* CHRouter< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 309 of file CHRouter.h.
References MsgHandler::getWarningInstance(), CHRouter< E, V, PF >::myEdges, CHRouter< E, V, PF >::myErrorMsgHandler, CHRouter< E, V, PF >::myHierarchy, SUMOAbstractRouter< E, V >::myOperation, CHRouter< E, V, PF >::mySVC, CHRouter< E, V, PF >::myValidUntil, CHRouter< E, V, PF >::myWeightPeriod, SumoVehicleClassStrings, time2string(), and WRITE_MESSAGE.
compute()
template<class E, class V, class PF> virtual bool CHRouter< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> & into) inline virtual
Builds the route between the given edges using the minimum traveltime in the contracted graph.
Note
: since the contracted graph is static (weights averaged over time) the computed routes only approximated shortest paths in the real graph
Implements SUMOAbstractRouter< E, V >.
Definition at line 321 of file CHRouter.h.
References CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::buildPathFromMeeting(), SUMOAbstractRouter< E, V >::endQuery(), MsgHandler::inform(), CHRouter< E, V, PF >::Unidirectional::init(), CHRouter< E, V, PF >::myBackwardSearch, CHRouter< E, V, PF >::myErrorMsgHandler, CHRouter< E, V, PF >::myForwardSearch, CHRouter< E, V, PF >::myHierarchy, CHRouter< E, V, PF >::myValidUntil, CHRouter< E, V, PF >::myWeightPeriod, SUMOAbstractRouter< E, V >::startQuery(), CHRouter< E, V, PF >::Unidirectional::step(), and toString().
endQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
getEffort()
template<class E, class V> double SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHBuilder< E, V >::synchronize().
getVia()
template<class E, class V, class PF> const E* CHRouter< E, V, PF >::getVia (const E * forwardFrom, const E * forwardTo) const inline private
Definition at line 430 of file CHRouter.h.
References CHRouter< E, V, PF >::myHierarchy.
Referenced by CHRouter< E, V, PF >::buildPathFromMeeting().
recomputeCosts()
template<class E, class V, class PF> double CHRouter< E, V, PF >::recomputeCosts (const std::vector< const E *> & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 367 of file CHRouter.h.
References SUMOAbstractRouter< E, V >::getEffort(), and STEPS2TIME.
setBulkMode()
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
startQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
myBackwardSearch
template<class E, class V, class PF> Unidirectional CHRouter< E, V, PF >::myBackwardSearch private
Definition at line 450 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::compute().
myBulkMode
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
myEdges
template<class E, class V, class PF> const std::vector<E*>& CHRouter< E, V, PF >::myEdges private
all edges with numerical ids
Definition at line 443 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::clone().
myErrorMsgHandler
template<class E, class V, class PF> MsgHandler* const CHRouter< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 446 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::clone(), and CHRouter< E, V, PF >::compute().
myForwardSearch
template<class E, class V, class PF> Unidirectional CHRouter< E, V, PF >::myForwardSearch private
the unidirectional search queues
Definition at line 449 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::compute().
myHierarchy
template<class E, class V, class PF> const CHBuilder<E, V>::Hierarchy* CHRouter< E, V, PF >::myHierarchy private
Definition at line 453 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), CHRouter< E, V, PF >::compute(), CHRouter< E, V, PF >::getVia(), and CHRouter< E, V, PF >::~CHRouter().
myHierarchyBuilder
template<class E, class V, class PF> CHBuilder<E, V>* CHRouter< E, V, PF >::myHierarchyBuilder private
Definition at line 452 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::~CHRouter().
myOperation
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
mySVC
template<class E, class V, class PF> const SUMOVehicleClass CHRouter< E, V, PF >::mySVC private
the permissions for which the hierarchy was constructed
Definition at line 462 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::clone().
myValidUntil
template<class E, class V, class PF> SUMOTime CHRouter< E, V, PF >::myValidUntil private
the validity duration of the current hierarchy (exclusive)
Definition at line 459 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), and CHRouter< E, V, PF >::compute().
myWeightPeriod
template<class E, class V, class PF> const SUMOTime CHRouter< E, V, PF >::myWeightPeriod private
the validity duration of one weight interval
Definition at line 456 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), and CHRouter< E, V, PF >::compute().
The documentation for this class was generated from the following file:
CHRouter.h