SUMO - Simulation of Urban MObility: TraCIAPI::InductionLoopScope Class Reference
TraCIAPI::InductionLoopScope Class Reference
Scope for interaction with inductive loops.
#include <TraCIAPI.h>
Public Member Functions
std::vector< std::string > getIDList () const
std::string getLaneID (const std::string &loopID) const
double getLastStepMeanLength (const std::string &loopID) const
double getLastStepMeanSpeed (const std::string &loopID) const
double getLastStepOccupancy (const std::string &loopID) const
std::vector< std::string > getLastStepVehicleIDs (const std::string &loopID) const
int getLastStepVehicleNumber (const std::string &loopID) const
double getPosition (const std::string &loopID) const
double getTimeSinceDetection (const std::string &loopID) const
std::vector< libsumo::TraCIVehicleData > getVehicleData (const std::string &loopID) const
InductionLoopScope (TraCIAPI &parent)
virtual ~InductionLoopScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
InductionLoopScope (const InductionLoopScope &src)
invalidated copy constructor
InductionLoopScope & operator= (const InductionLoopScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with inductive loops.
Definition at line 226 of file TraCIAPI.h.
Constructor & Destructor Documentation
InductionLoopScope() [1/2]
TraCIAPI::InductionLoopScope::InductionLoopScope (TraCIAPI & parent) inline
Definition at line 228 of file TraCIAPI.h.
~InductionLoopScope()
virtual TraCIAPI::InductionLoopScope::~InductionLoopScope () inline virtual
Definition at line 229 of file TraCIAPI.h.
References TraCIAPI::getPosition(), and TraCIAPI::TraCIScopeWrapper::operator=().
InductionLoopScope() [2/2]
TraCIAPI::InductionLoopScope::InductionLoopScope (const InductionLoopScope & src) private
invalidated copy constructor
Member Function Documentation
getIDList()
std::vector< std::string > TraCIAPI::InductionLoopScope::getIDList () const
Definition at line 879 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and ID_LIST.
Referenced by TraCITestClient::testAPI().
getLaneID()
std::string TraCIAPI::InductionLoopScope::getLaneID (const std::string & loopID) const
Definition at line 889 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and VAR_LANE_ID.
getLastStepMeanLength()
double TraCIAPI::InductionLoopScope::getLastStepMeanLength (const std::string & loopID) const
Definition at line 914 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_LENGTH.
getLastStepMeanSpeed()
double TraCIAPI::InductionLoopScope::getLastStepMeanSpeed (const std::string & loopID) const
Definition at line 899 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_MEAN_SPEED.
getLastStepOccupancy()
double TraCIAPI::InductionLoopScope::getLastStepOccupancy (const std::string & loopID) const
Definition at line 909 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_OCCUPANCY.
getLastStepVehicleIDs()
std::vector< std::string > TraCIAPI::InductionLoopScope::getLastStepVehicleIDs (const std::string & loopID) const
Definition at line 904 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_VEHICLE_ID_LIST.
getLastStepVehicleNumber()
int TraCIAPI::InductionLoopScope::getLastStepVehicleNumber (const std::string & loopID) const
Definition at line 894 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_VEHICLE_NUMBER.
getPosition()
double TraCIAPI::InductionLoopScope::getPosition (const std::string & loopID) const
Definition at line 884 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and VAR_POSITION.
getTimeSinceDetection()
double TraCIAPI::InductionLoopScope::getTimeSinceDetection (const std::string & loopID) const
Definition at line 919 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_TIME_SINCE_DETECTION.
getVehicleData()
std::vector< TraCIVehicleData > TraCIAPI::InductionLoopScope::getVehicleData (const std::string & loopID) const
Definition at line 924 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, libsumo::TraCIVehicleData::entryTime, libsumo::TraCIVehicleData::id, LAST_STEP_VEHICLE_DATA, libsumo::TraCIVehicleData::leaveTime, libsumo::TraCIVehicleData::length, tcpip::Storage::readDouble(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), TYPE_COMPOUND, and libsumo::TraCIVehicleData::typeID.
Referenced by TraCITestClient::testAPI().
operator=()
InductionLoopScope& TraCIAPI::InductionLoopScope::operator= (const InductionLoopScope & src) private
invalidated assignment operator
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp