SUMO - Simulation of Urban MObility: NBPTLineCont Class Reference
NBPTLineCont Class Reference
#include <NBPTLineCont.h>
Public Member Functions
void addEdges2Keep (const OptionsCont &oc, std::set< std::string > &into)
add edges that must be kept
std::vector< NBPTLine * >::const_iterator begin () const
Returns the pointer to the begin of the stored pt lines.
std::vector< NBPTLine * >::const_iterator end () const
Returns the pointer to the end of the stored pt lines.
std::set< std::string > & getServedPTStops ()
void insert (NBPTLine *pLine)
insert new line
NBPTLineCont ()
constructor
void process (NBEdgeCont &cont)
~NBPTLineCont ()
destructor
Private Types
typedef std::vector< NBPTLine * > PTLinesCont
Definition of the map of names to pt lines.
Private Member Functions
void constructRoute (NBPTLine *myPTLine, NBEdgeCont &cont)
void reviseStops (NBPTLine *myPTLine, NBEdgeCont &cont)
Private Attributes
long long int myIdCnt
PTLinesCont myPTLines
The map of names to pt lines.
std::set< std::string > myServedPTStops
Static Private Attributes
static const int BWD
static const int FWD
Detailed Description
Definition at line 28 of file NBPTLineCont.h.
Member Typedef Documentation
PTLinesCont
typedef std::vector<NBPTLine*> NBPTLineCont::PTLinesCont private
Definition of the map of names to pt lines.
Definition at line 66 of file NBPTLineCont.h.
Constructor & Destructor Documentation
NBPTLineCont()
NBPTLineCont::NBPTLineCont ()
constructor
Definition at line 40 of file NBPTLineCont.cpp.
~NBPTLineCont()
NBPTLineCont::~NBPTLineCont ()
destructor
Definition at line 45 of file NBPTLineCont.cpp.
References myPTLines.
Member Function Documentation
addEdges2Keep()
void NBPTLineCont::addEdges2Keep (const OptionsCont & oc, std::set< std::string > & into)
add edges that must be kept
Definition at line 294 of file NBPTLineCont.cpp.
References OptionsCont::isSet(), and myPTLines.
Referenced by NBRampsComputer::computeRamps(), end(), and NBNodeCont::removeUnwishedNodes().
begin()
std::vector<NBPTLine*>::const_iterator NBPTLineCont::begin () const inline
Returns the pointer to the begin of the stored pt lines.
Returns
The iterator to the beginning of stored pt lines
Definition at line 43 of file NBPTLineCont.h.
References myPTLines.
Referenced by NWWriter_XML::writePTLines().
constructRoute()
void NBPTLineCont::constructRoute (NBPTLine * myPTLine, NBEdgeCont & cont) private
Definition at line 174 of file NBPTLineCont.cpp.
References NBPTLine::addEdgeVector(), NBPTStop::getEdgeId(), NBPTLine::getLineID(), NBPTLine::getMyWays(), NBPTLine::getName(), NBPTLine::getStops(), NBEdgeCont::retrieve(), toString(), and WRITE_WARNING.
Referenced by process().
end()
std::vector<NBPTLine*>::const_iterator NBPTLineCont::end () const inline
Returns the pointer to the end of the stored pt lines.
Returns
The iterator to the end of stored pt lines
Definition at line 50 of file NBPTLineCont.h.
References addEdges2Keep(), getServedPTStops(), myPTLines, and process().
Referenced by NWWriter_XML::writePTLines().
getServedPTStops()
std::set< std::string > & NBPTLineCont::getServedPTStops ()
Definition at line 303 of file NBPTLineCont.cpp.
References myServedPTStops.
Referenced by NBNetBuilder::compute(), and end().
insert()
void NBPTLineCont::insert (NBPTLine * pLine)
insert new line
Definition at line 53 of file NBPTLineCont.cpp.
References myIdCnt, myPTLines, and NBPTLine::setId().
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
process()
void NBPTLineCont::process (NBEdgeCont & cont)
Definition at line 57 of file NBPTLineCont.cpp.
References constructRoute(), myPTLines, and reviseStops().
Referenced by NBNetBuilder::compute(), and end().
reviseStops()
void NBPTLineCont::reviseStops (NBPTLine * myPTLine, NBEdgeCont & cont) private
Definition at line 70 of file NBPTLineCont.cpp.
References BWD, FWD, NBEdgeCont::getByID(), Named::getID(), NBPTLine::getMyWays(), NBPTLine::getName(), NBPTStopCont::getReverseEdge(), NBPTLine::getStops(), NBPTLine::getWaysNodes(), myServedPTStops, and WRITE_WARNING.
Referenced by process().
Field Documentation
BWD
const int NBPTLineCont::BWD static private
Definition at line 63 of file NBPTLineCont.h.
Referenced by reviseStops().
FWD
const int NBPTLineCont::FWD static private
Definition at line 62 of file NBPTLineCont.h.
Referenced by reviseStops().
myIdCnt
long long int NBPTLineCont::myIdCnt private
Definition at line 71 of file NBPTLineCont.h.
Referenced by insert().
myPTLines
PTLinesCont NBPTLineCont::myPTLines private
The map of names to pt lines.
Definition at line 69 of file NBPTLineCont.h.
Referenced by addEdges2Keep(), begin(), end(), insert(), process(), and ~NBPTLineCont().
myServedPTStops
std::set<std::string> NBPTLineCont::myServedPTStops private
Definition at line 75 of file NBPTLineCont.h.
Referenced by getServedPTStops(), and reviseStops().
The documentation for this class was generated from the following files:
NBPTLineCont.h
NBPTLineCont.cpp