SUMO - Simulation of Urban MObility: NIVissimSingleTypeParser_Signalgruppendefinition Class Reference
NIVissimSingleTypeParser_Signalgruppendefinition Class Reference
#include <NIVissimSingleTypeParser_Signalgruppendefinition.h>
Public Member Functions
NIVissimSingleTypeParser_Signalgruppendefinition (NIImporter_Vissim &parent)
Constructor.
bool parse (std::istream &from)
Parses the data type from the given stream.
~NIVissimSingleTypeParser_Signalgruppendefinition ()
Destructor.
Protected Member Functions
Position getPosition (std::istream &from)
returns the 2d-position saved as next within the stream
std::string myRead (std::istream &from)
reads from the stream and returns the lower case version of the read value
std::string overrideOptionalLabel (std::istream &from, const std::string &tag="")
overrides the optional label definition; returns the next tag as done by readEndSecure
std::vector< int > parseAssignedVehicleTypes (std::istream &from, const std::string &next)
parses a listof vehicle types assigned to the current data field One should remeber, that -1 means "all" vehicle types
std::string readEndSecure (std::istream &from, const std::string &excl="")
as myRead, but returns "DATAEND" when the current field has ended
std::string readEndSecure (std::istream &from, const std::vector< std::string > &excl)
NIVissimExtendedEdgePoint readExtEdgePointDef (std::istream &from)
std::string readName (std::istream &from)
Reads the structures name We cannot use the "<<" operator, as names may contain more than one word which are joined using '"'.
void readUntil (std::istream &from, const std::string &name)
Reads from the stream until the keywor occurs.
bool skipOverreading (std::istream &from, const std::string &name="")
Overreads the named parameter (if) given and skips the rest until "DATAEND".
Private Member Functions
bool parseExternFixedTime (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs fixed time traffic light with an extern definition.
bool parseFixedTime (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a fixed time traffic light.
bool parsePOS (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a POS traffic light.
bool parseTL (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a TL traffic light.
bool parseTRENDS (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a TRENDS traffic light.
bool parseVAP (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a VAStraffic light.
bool parseVAS (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a VAS traffic light.
bool parseVSPLUS (int id, const std::string &name, int lsaid, std::istream &from)
Parses a traffic light group which belongs to a VSPLUS traffic light.
Detailed Description
Definition at line 43 of file NIVissimSingleTypeParser_Signalgruppendefinition.h.
Constructor & Destructor Documentation
NIVissimSingleTypeParser_Signalgruppendefinition()
NIVissimSingleTypeParser_Signalgruppendefinition::NIVissimSingleTypeParser_Signalgruppendefinition (NIImporter_Vissim & parent)
Constructor.
Definition at line 46 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
~NIVissimSingleTypeParser_Signalgruppendefinition()
NIVissimSingleTypeParser_Signalgruppendefinition::~NIVissimSingleTypeParser_Signalgruppendefinition ()
Destructor.
Definition at line 50 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
Member Function Documentation
getPosition()
Position NIImporter_Vissim::VissimSingleTypeParser::getPosition (std::istream & from) protected inherited
returns the 2d-position saved as next within the stream
Definition at line 769 of file NIImporter_Vissim.cpp.
Referenced by NIVissimSingleTypeParser_Knotendefinition::parse(), and NIVissimSingleTypeParser_Streckendefinition::parse().
myRead()
std::string NIImporter_Vissim::VissimSingleTypeParser::myRead (std::istream & from) protected inherited
reads from the stream and returns the lower case version of the read value
Definition at line 691 of file NIImporter_Vissim.cpp.
References StringUtils::to_lower_case().
Referenced by NIImporter_Vissim::VissimSingleTypeParser::overrideOptionalLabel(), NIVissimSingleTypeParser_Auswertungsdefinition::parse(), NIVissimSingleTypeParser_Haltestellendefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_Routenentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Fensterdefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Querschnittsmessungsdefinition::parse(), NIVissimSingleTypeParser_Reisezeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Detektordefinition::parse(), NIVissimSingleTypeParser_Zusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Langsamfahrbereichdefinition::parse(), parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Verlustzeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), parseFixedTime(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), parseVAS(), NIImporter_Vissim::VissimSingleTypeParser::readEndSecure(), NIImporter_Vissim::VissimSingleTypeParser::readUntil(), and NIImporter_Vissim::VissimSingleTypeParser::skipOverreading().
overrideOptionalLabel()
std::string NIImporter_Vissim::VissimSingleTypeParser::overrideOptionalLabel (std::istream & from, const std::string & tag = "") protected inherited
overrides the optional label definition; returns the next tag as done by readEndSecure
Definition at line 748 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead().
Referenced by NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), and NIVissimSingleTypeParser_Verbindungsdefinition::parse().
parse()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parse (std::istream & from) virtual
Parses the data type from the given stream.
Implements NIImporter_Vissim::VissimSingleTypeParser.
Definition at line 54 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References NIVissimTL::dictionary(), NIVissimTL::getType(), NIImporter_Vissim::VissimSingleTypeParser::myRead(), parseFixedTime(), parsePOS(), parseTL(), parseTRENDS(), parseVAP(), parseVAS(), parseVSPLUS(), NIImporter_Vissim::VissimSingleTypeParser::readName(), WRITE_ERROR, and WRITE_WARNING.
parseAssignedVehicleTypes()
std::vector< int > NIImporter_Vissim::VissimSingleTypeParser::parseAssignedVehicleTypes (std::istream & from, const std::string & next) protected inherited
parses a listof vehicle types assigned to the current data field One should remeber, that -1 means "all" vehicle types
Definition at line 778 of file NIImporter_Vissim.cpp.
References TplConvert::_2int(), and NIImporter_Vissim::VissimSingleTypeParser::readEndSecure().
Referenced by NIVissimSingleTypeParser_Signalgeberdefinition::parse().
parseExternFixedTime()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseExternFixedTime (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs fixed time traffic light with an extern definition.
Definition at line 200 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References WRITE_WARNING.
parseFixedTime()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseFixedTime (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a fixed time traffic light.
Definition at line 107 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References NIVissimTL::NIVissimTLSignalGroup::dictionary(), and NIImporter_Vissim::VissimSingleTypeParser::myRead().
Referenced by parse().
parsePOS()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parsePOS (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a POS traffic light.
Definition at line 192 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References WRITE_WARNING.
Referenced by parse().
parseTL()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseTL (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a TL traffic light.
Definition at line 184 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References WRITE_WARNING.
Referenced by parse().
parseTRENDS()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseTRENDS (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a TRENDS traffic light.
Definition at line 168 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References WRITE_WARNING.
Referenced by parse().
parseVAP()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseVAP (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a VAStraffic light.
Definition at line 176 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References WRITE_WARNING.
Referenced by parse().
parseVAS()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseVAS (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a VAS traffic light.
Definition at line 148 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead(), and WRITE_WARNING.
Referenced by parse().
parseVSPLUS()
bool NIVissimSingleTypeParser_Signalgruppendefinition::parseVSPLUS (int id, const std::string & name, int lsaid, std::istream & from) private
Parses a traffic light group which belongs to a VSPLUS traffic light.
Definition at line 160 of file NIVissimSingleTypeParser_Signalgruppendefinition.cpp.
References WRITE_WARNING.
Referenced by parse().
readEndSecure() [1/2]
std::string NIImporter_Vissim::VissimSingleTypeParser::readEndSecure (std::istream & from, const std::string & excl = "") protected inherited
as myRead, but returns "DATAEND" when the current field has ended
Definition at line 700 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::admitContinue(), NIImporter_Vissim::VissimSingleTypeParser::myRead(), NIImporter_Vissim::VissimSingleTypeParser::myVissimParent, and StringUtils::to_lower_case().
Referenced by NIVissimSingleTypeParser_Auswertungsdefinition::parse(), NIVissimSingleTypeParser_Zusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Zeitenverteilungsdefinition::parse(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_Detektordefinition::parse(), NIVissimSingleTypeParser_Reisezeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Verlustzeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Stopschilddefinition::parse(), NIVissimSingleTypeParser_DynUml::parse(), NIVissimSingleTypeParser_Laengenverteilungsdefinition::parse(), NIVissimSingleTypeParser_Querschnittsmessungsdefinition::parse(), NIVissimSingleTypeParser_Haltestellendefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Kantensperrung::parse(), NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Routenentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIImporter_Vissim::VissimSingleTypeParser::parseAssignedVehicleTypes(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseFixedTime(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePos(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseVAS(), NIImporter_Vissim::VissimSingleTypeParser::readExtEdgePointDef(), and NIImporter_Vissim::VissimSingleTypeParser::skipOverreading().
readEndSecure() [2/2]
std::string NIImporter_Vissim::VissimSingleTypeParser::readEndSecure (std::istream & from, const std::vector< std::string > & excl) protected inherited
Definition at line 718 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::admitContinue(), NIImporter_Vissim::VissimSingleTypeParser::myRead(), NIImporter_Vissim::VissimSingleTypeParser::myVissimParent, and StringUtils::to_lower_case().
readExtEdgePointDef()
NIVissimExtendedEdgePoint NIImporter_Vissim::VissimSingleTypeParser::readExtEdgePointDef (std::istream & from) protected inherited
Definition at line 795 of file NIImporter_Vissim.cpp.
References TplConvert::_2int(), and NIImporter_Vissim::VissimSingleTypeParser::readEndSecure().
Referenced by NIVissimSingleTypeParser_Verbindungsdefinition::parse().
readName()
std::string NIImporter_Vissim::VissimSingleTypeParser::readName (std::istream & from) protected inherited
Reads the structures name We cannot use the "<<" operator, as names may contain more than one word which are joined using '"'.
Definition at line 818 of file NIImporter_Vissim.cpp.
References StringUtils::convertUmlaute().
Referenced by NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Kennungszeile::parse(), parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), and NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered().
readUntil()
void NIImporter_Vissim::VissimSingleTypeParser::readUntil (std::istream & from, const std::string & name) protected inherited
Reads from the stream until the keywor occurs.
Definition at line 834 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead().
Referenced by NIVissimSingleTypeParser_DynUml::parse(), NIVissimSingleTypeParser_Fahrverhaltendefinition::parse(), NIVissimSingleTypeParser_Fensterdefinition::parse(), NIVissimSingleTypeParser_Langsamfahrbereichdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Stopschilddefinition::parse(), and NIVissimSingleTypeParser_Streckentypdefinition::parse().
skipOverreading()
bool NIImporter_Vissim::VissimSingleTypeParser::skipOverreading (std::istream & from, const std::string & name = "") protected inherited
Overreads the named parameter (if) given and skips the rest until "DATAEND".
Definition at line 843 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead(), and NIImporter_Vissim::VissimSingleTypeParser::readEndSecure().
Referenced by NIVissimSingleTypeParser_Messungsdefinition::parse(), NIVissimSingleTypeParser_Richtungsentscheidungsdefinition::parse(), and NIVissimSingleTypeParser_Stauzaehlerdefinition::parse().
The documentation for this class was generated from the following files:
NIVissimSingleTypeParser_Signalgruppendefinition.h
NIVissimSingleTypeParser_Signalgruppendefinition.cpp