SUMO - Simulation of Urban MObility: MSMeanData::MeanDataValueTracker Class Reference
MSMeanData::MeanDataValueTracker Class Reference
Data structure for mean (aggregated) edge/lane values for tracked vehicles.
#include <MSMeanData.h>
Data Structures
class TrackerEntry
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED, NOTIFICATION_PARKING_REROUTE
}
Definition of a vehicle state.
Public Member Functions
void addTo (MSMeanData::MeanDataValues &val) const
Add the values of this to the given one and store them there.
void clearFirst ()
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
int getNumReady () const
double getSamples () const
Returns the number of collected sample seconds.
double getTravelledDistance () const
Returns the total travelled distance.
bool isEmpty () const
Returns whether any data was collected.
MeanDataValueTracker (MSLane *const lane, const double length, const MSMeanData *const parent)
Constructor.
bool notifyMove (SUMOVehicle &veh, double oldPos, double newPos, double newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
void reset (bool afterWrite)
Resets values so they may be used for the next interval.
void setDescription (const std::string &description)
virtual void update ()
Called if a per timestep update is needed. Default does nothing.
void write (OutputDevice &dev, const SUMOTime period, const double numLanes, const double defaultTravelTime, const int numVehicles=-1) const
Writes output values into the given stream.
virtual ~MeanDataValueTracker ()
Destructor.
Methods inherited from MSMoveReminder
void notifyMoveInternal (const SUMOVehicle &veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane)
Internal notification about the vehicle moves.
bool notifyLeave (SUMOVehicle &veh, double lastPos, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Called if the vehicle leaves the reminder's lane.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
Computes current values and adds them to their sums.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
const double myLaneLength
The length of the lane / edge the data collector is on.
const MSMeanData *const myParent
The meandata parent.
Collected values
The number of sampled vehicle movements (in s)
double sampleSeconds
double travelledDistance
The sum of the distances the vehicles travelled.
Private Attributes
std::list< TrackerEntry * > myCurrentData
The currently active meandata "intervals".
std::map< const SUMOVehicle *, TrackerEntry * > myTrackedData
The map of vehicles to data entries.
Detailed Description
Data structure for mean (aggregated) edge/lane values for tracked vehicles.
Definition at line 192 of file MSMeanData.h.
Member Enumeration Documentation
Notification
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
NOTIFICATION_PARKING_REROUTE
The vehicle needs another parking area.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MeanDataValueTracker()
MSMeanData::MeanDataValueTracker::MeanDataValueTracker (MSLane *const lane, const double length, const MSMeanData *const parent)
Constructor.
Definition at line 289 of file MSMeanData.cpp.
References MSMeanData::createValues(), and myCurrentData.
~MeanDataValueTracker()
MSMeanData::MeanDataValueTracker::~MeanDataValueTracker () virtual
Destructor.
Definition at line 297 of file MSMeanData.cpp.
References myCurrentData.
Member Function Documentation
addTo()
void MSMeanData::MeanDataValueTracker::addTo (MSMeanData::MeanDataValues & val) const virtual
Add the values of this to the given one and store them there.
Parameters
[in] val The meandata to add to
Implements MSMeanData::MeanDataValues.
Definition at line 326 of file MSMeanData.cpp.
References myCurrentData.
clearFirst()
void MSMeanData::MeanDataValueTracker::clearFirst ()
getDescription()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 234 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::getSingularType(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), and MSMeanData_Net::MSLaneMeanDataValues::write().
getLane()
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder is anchored on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), libsumo::InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSDevice_Vehroutes::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), and MSMeanData::writeEdge().
getNumReady()
int MSMeanData::MeanDataValueTracker::getNumReady () const
Definition at line 389 of file MSMeanData.cpp.
References myCurrentData.
getSamples()
double MSMeanData::MeanDataValueTracker::getSamples () const virtual
Returns the number of collected sample seconds.
Returns
the number of collected sample seconds
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 403 of file MSMeanData.cpp.
References myCurrentData.
getTravelledDistance()
double MSMeanData::MeanDataValues::getTravelledDistance () const inline inherited
Returns the total travelled distance.
Returns
the total travelled distance
Definition at line 165 of file MSMeanData.h.
References MSMeanData::MeanDataValues::travelledDistance.
Referenced by MSCalibrator::currentSpeed(), and MSCalibrator::writeXMLOutput().
isEmpty()
bool MSMeanData::MeanDataValueTracker::isEmpty () const virtual
Returns whether any data was collected.
Returns
whether no data was collected
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 371 of file MSMeanData.cpp.
References myCurrentData.
notifyEnter()
bool MSMeanData::MeanDataValueTracker::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Computes current values and adds them to their sums.
The fraction of time the vehicle is on the lane is computed and used as a weight for the vehicle's current values. The "emitted" field is incremented, additionally.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
See also
MSMoveReminder::notifyEnter
Returns
Always true
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 347 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), myCurrentData, MSMeanData::MeanDataValues::myParent, myTrackedData, MSMoveReminder::NOTIFICATION_SEGMENT, SIMTIME, UNUSED_PARAMETER, and MSDetectorFileOutput::vehicleApplies().
notifyLeave()
bool MSMeanData::MeanDataValueTracker::notifyLeave (SUMOVehicle & veh, double lastPos, MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual
Called if the vehicle leaves the reminder's lane.
Parameters
veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 338 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::myParent, myTrackedData, and MSMoveReminder::NOTIFICATION_SEGMENT.
notifyMove()
bool MSMeanData::MeanDataValues::notifyMove (SUMOVehicle & veh, double oldPos, double newPos, double newSpeed) virtual inherited
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented from MSMoveReminder.
Definition at line 91 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), MSMoveReminder::getLane(), MSVehicleType::getLength(), SUMOVehicle::getPreviousSpeed(), SUMOVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, SUMOVehicle::hasArrived(), MAX2(), MIN2(), MIN4(), MSMoveReminder::myLane, MSMeanData::MeanDataValues::myLaneLength, MSMoveReminder::notifyMoveInternal(), NUMERICAL_EPS, MSCFModel::passingTime(), MSCFModel::speedAfterTime(), TS, and WRITE_ERROR.
notifyMoveInternal()
void MSMeanData::MeanDataValueTracker::notifyMoveInternal (const SUMOVehicle & veh, const double frontOnLane, const double timeOnLane, const double meanSpeedFrontOnLane, const double meanSpeedVehicleOnLane, const double travelledDistanceFrontOnLane, const double travelledDistanceVehicleOnLane, const double meanLengthOnLane) virtual
Internal notification about the vehicle moves.
See also
MSMoveReminder::notifyMoveInternal().
Reimplemented from MSMoveReminder.
Definition at line 332 of file MSMeanData.cpp.
References myTrackedData.
removeFromVehicleUpdateValues()
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 93 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
reset()
void MSMeanData::MeanDataValueTracker::reset (bool afterWrite) virtual
Resets values so they may be used for the next interval.
Implements MSMeanData::MeanDataValues.
Definition at line 314 of file MSMeanData.cpp.
References MSMeanData::createValues(), myCurrentData, MSMoveReminder::myLane, MSMeanData::MeanDataValues::myLaneLength, and MSMeanData::MeanDataValues::myParent.
setDescription()
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 230 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
update()
void MSMeanData::MeanDataValues::update () virtual inherited
Called if a per timestep update is needed. Default does nothing.
Reimplemented in MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 276 of file MSMeanData.cpp.
updateDetector()
void MSMoveReminder::updateDetector (SUMOVehicle & veh, double entryPos, double leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 50 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), and STEPS2TIME.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
write()
void MSMeanData::MeanDataValueTracker::write (OutputDevice & dev, const SUMOTime period, const double numLanes, const double defaultTravelTime, const int numVehicles = -1) const virtual
Writes output values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] period Length of the period the data were gathered
[in] numLanes The total number of lanes for which the data was collected
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSMeanData::MeanDataValues.
Definition at line 377 of file MSMeanData.cpp.
References myCurrentData.
Field Documentation
myCurrentData
std::list<TrackerEntry*> MSMeanData::MeanDataValueTracker::myCurrentData private
The currently active meandata "intervals".
Definition at line 291 of file MSMeanData.h.
Referenced by addTo(), getNumReady(), getSamples(), isEmpty(), MeanDataValueTracker(), notifyEnter(), reset(), write(), and ~MeanDataValueTracker().
myDescription
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 246 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
myLane
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 244 of file MSMoveReminder.h.
Referenced by MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSMoveReminder::MSMoveReminder(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), and reset().
myLaneLength
const double MSMeanData::MeanDataValues::myLaneLength protected inherited
The length of the lane / edge the data collector is on.
Definition at line 174 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyMove(), reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
myParent
const MSMeanData* const MSMeanData::MeanDataValues::myParent protected inherited
The meandata parent.
Definition at line 171 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), notifyEnter(), notifyLeave(), reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), and MSMeanData_Amitran::MSLaneMeanDataValues::write().
myTrackedData
std::map<const SUMOVehicle*, TrackerEntry*> MSMeanData::MeanDataValueTracker::myTrackedData private
The map of vehicles to data entries.
Definition at line 288 of file MSMeanData.h.
Referenced by notifyEnter(), notifyLeave(), and notifyMoveInternal().
sampleSeconds
double MSMeanData::MeanDataValues::sampleSeconds protected inherited
Definition at line 179 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData::MeanDataValues::getSamples(), MSMeanData_Amitran::MSLaneMeanDataValues::isEmpty(), MSMeanData_Net::MSLaneMeanDataValues::isEmpty(), MSMeanData::MeanDataValues::isEmpty(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
travelledDistance
double MSMeanData::MeanDataValues::travelledDistance protected inherited
The sum of the distances the vehicles travelled.
Definition at line 182 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData::MeanDataValues::getTravelledDistance(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
The documentation for this class was generated from the following files:
MSMeanData.h
MSMeanData.cpp