SUMO - Simulation of Urban MObility: GNEDialog_Wizard::InputString Class Reference
GNEDialog_Wizard::InputString Class Reference
#include <GNEDialog_Wizard.h>
Public Member Functions
InputString (FXComposite *parent, const std::string &name)
FOX-declaration.
long onCmdSetOption (FXObject *, FXSelector, void *)
try to set new attribute value
Protected Member Functions
InputString ()
FOX needs this.
Private Attributes
std::string myName
name
FXTextField * myTextField
text field
Detailed Description
Definition at line 59 of file GNEDialog_Wizard.h.
Constructor & Destructor Documentation
InputString() [1/2]
GNEDialog_Wizard::InputString::InputString (FXComposite * parent, const std::string & name)
FOX-declaration.
constructor
Definition at line 106 of file GNEDialog_Wizard.cpp.
References OptionsCont::getOptions(), OptionsCont::getString(), MID_GNE_SET_ATTRIBUTE, and myTextField.
InputString() [2/2]
GNEDialog_Wizard::InputString::InputString () inline protected
FOX needs this.
Definition at line 72 of file GNEDialog_Wizard.h.
Member Function Documentation
onCmdSetOption()
long GNEDialog_Wizard::InputString::onCmdSetOption (FXObject * , FXSelector , void *)
try to set new attribute value
Definition at line 117 of file GNEDialog_Wizard.cpp.
References OptionsCont::getOptions(), myName, myTextField, OptionsCont::resetWritable(), and OptionsCont::set().
Field Documentation
myName
std::string GNEDialog_Wizard::InputString::myName private
name
Definition at line 76 of file GNEDialog_Wizard.h.
Referenced by onCmdSetOption().
myTextField
FXTextField* GNEDialog_Wizard::InputString::myTextField private
text field
Definition at line 79 of file GNEDialog_Wizard.h.
Referenced by InputString(), and onCmdSetOption().
The documentation for this class was generated from the following files:
GNEDialog_Wizard.h
GNEDialog_Wizard.cpp