SUMO - Simulation of Urban MObility: MSJunctionLogic Class Reference
MSJunctionLogic Class Reference
#include <MSJunctionLogic.h>
Public Member Functions
virtual const MSLogicJunction::LinkBits & getFoesFor (int linkIndex) const
Returns the foes for the given link.
virtual bool getIsCont (int linkIndex) const
int getLogicSize () const
virtual const MSLogicJunction::LinkBits & getResponseFor (int linkIndex) const
Returns the response for the given link.
virtual bool hasFoes () const
int nLinks ()
Returns the logic's number of links.
virtual ~MSJunctionLogic ()
Destructor.
Protected Member Functions
MSJunctionLogic (int nLinks)
Constructor.
Protected Attributes
int myNLinks
The logic's number of links.
Static Protected Attributes
static MSLogicJunction::LinkBits myDummyFoes
A dummy foe container.
Private Member Functions
MSJunctionLogic ()
Default constructor.
MSJunctionLogic (const MSJunctionLogic &)
Copy constructor.
MSJunctionLogic & operator= (const MSJunctionLogic &)
Assignment operator.
Detailed Description
Definition at line 45 of file MSJunctionLogic.h.
Constructor & Destructor Documentation
~MSJunctionLogic()
MSJunctionLogic::~MSJunctionLogic () virtual
Destructor.
Definition at line 54 of file MSJunctionLogic.cpp.
MSJunctionLogic() [1/3]
MSJunctionLogic::MSJunctionLogic (int nLinks) protected
Constructor.
Definition at line 50 of file MSJunctionLogic.cpp.
MSJunctionLogic() [2/3]
MSJunctionLogic::MSJunctionLogic () private
Default constructor.
Referenced by hasFoes().
MSJunctionLogic() [3/3]
MSJunctionLogic::MSJunctionLogic (const MSJunctionLogic &) private
Copy constructor.
Member Function Documentation
getFoesFor()
virtual const MSLogicJunction::LinkBits& MSJunctionLogic::getFoesFor (int linkIndex) const inline virtual
Returns the foes for the given link.
Reimplemented in MSBitSetLogic< N >.
Definition at line 60 of file MSJunctionLogic.h.
References myDummyFoes, and UNUSED_PARAMETER.
Referenced by MSRightOfWayJunction::postloadInit().
getIsCont()
virtual bool MSJunctionLogic::getIsCont (int linkIndex) const inline virtual
Reimplemented in MSBitSetLogic< N >.
Definition at line 64 of file MSJunctionLogic.h.
References UNUSED_PARAMETER.
Referenced by MSRightOfWayJunction::postloadInit().
getLogicSize()
int MSJunctionLogic::getLogicSize () const inline
Definition at line 70 of file MSJunctionLogic.h.
References myNLinks.
Referenced by MSRightOfWayJunction::postloadInit().
getResponseFor()
virtual const MSLogicJunction::LinkBits& MSJunctionLogic::getResponseFor (int linkIndex) const inline virtual
Returns the response for the given link.
Reimplemented in MSBitSetLogic< N >.
Definition at line 54 of file MSJunctionLogic.h.
References myDummyFoes, and UNUSED_PARAMETER.
Referenced by MSInternalJunction::postloadInit(), and MSRightOfWayJunction::postloadInit().
hasFoes()
virtual bool MSJunctionLogic::hasFoes () const inline virtual
Reimplemented in MSBitSetLogic< N >.
Definition at line 74 of file MSJunctionLogic.h.
References MSJunctionLogic().
Referenced by MSRightOfWayJunction::postloadInit().
nLinks()
int MSJunctionLogic::nLinks ()
Returns the logic's number of links.
Definition at line 45 of file MSJunctionLogic.cpp.
References myNLinks.
operator=()
MSJunctionLogic& MSJunctionLogic::operator= (const MSJunctionLogic &) private
Assignment operator.
Field Documentation
myDummyFoes
MSLogicJunction::LinkBits MSJunctionLogic::myDummyFoes static protected
A dummy foe container.
Definition at line 89 of file MSJunctionLogic.h.
Referenced by getFoesFor(), and getResponseFor().
myNLinks
int MSJunctionLogic::myNLinks protected
The logic's number of links.
Definition at line 86 of file MSJunctionLogic.h.
Referenced by getLogicSize(), and nLinks().
The documentation for this class was generated from the following files:
MSJunctionLogic.h
MSJunctionLogic.cpp