SUMO - Simulation of Urban MObility: NBNode::ApproachingDivider Class Reference
NBNode::ApproachingDivider Class Reference
Computes lane-2-lane connections.
#include <NBNode.h>
Public Member Functions
ApproachingDivider (EdgeVector *approaching, NBEdge *currentOutgoing)
Constructor.
void execute (const int src, const int dest)
the bresenham-callback
int numAvailableLanes () const
@ get number of avaliable lanes
std::deque< int > * spread (const std::vector< int > &approachingLanes, int dest) const
the method that spreads the wished number of lanes from the the lane given by the bresenham-call to both left and right
~ApproachingDivider ()
Destructor.
Private Attributes
EdgeVector * myApproaching
The list of edges that approach the current edge.
std::vector< int > myAvailableLanes
The available lanes to which connections shall be built.
NBEdge * myCurrentOutgoing
The approached current edge.
Detailed Description
Computes lane-2-lane connections.
Being a bresenham-callback, this class computes which lanes are approached by the current lane (first callback parameter). The second callback parameter is the destination lane that is the middle of the computed lanes. The lanes are spreaded from this middle position both to left and right but may also be transposed in full when there is not enough space.
Definition at line 94 of file NBNode.h.
Constructor & Destructor Documentation
ApproachingDivider()
NBNode::ApproachingDivider::ApproachingDivider (EdgeVector * approaching, NBEdge * currentOutgoing)
Constructor.
Parameters
[in] approaching The list of the edges that approach the outgoing edge
[in] currentOutgoing The outgoing edge
Definition at line 94 of file NBNode.cpp.
References NBEdge::getNumLanes(), NBEdge::getPermissions(), isForbidden(), myApproaching, myAvailableLanes, myCurrentOutgoing, and SVC_PEDESTRIAN.
~ApproachingDivider()
NBNode::ApproachingDivider::~ApproachingDivider ()
Destructor.
Definition at line 124 of file NBNode.cpp.
Member Function Documentation
execute()
void NBNode::ApproachingDivider::execute (const int src, const int dest) virtual
the bresenham-callback
Implements Bresenham::BresenhamCallBack.
Definition at line 128 of file NBNode.cpp.
References NBEdge::getConnectionLanes(), NBEdge::L2L_COMPUTED, NBEdge::LANES2LANES_DONE, NBEdge::LANES2LANES_USER, myApproaching, myAvailableLanes, myCurrentOutgoing, and spread().
Referenced by numAvailableLanes().
numAvailableLanes()
int NBNode::ApproachingDivider::numAvailableLanes () const inline
@ get number of avaliable lanes
Definition at line 116 of file NBNode.h.
References execute(), and spread().
Referenced by NBNode::computeLanes2Lanes().
spread()
std::deque< int > * NBNode::ApproachingDivider::spread (const std::vector< int > & approachingLanes, int dest) const
the method that spreads the wished number of lanes from the the lane given by the bresenham-call to both left and right
Definition at line 152 of file NBNode.cpp.
References myAvailableLanes.
Referenced by execute(), and numAvailableLanes().
Field Documentation
myApproaching
EdgeVector* NBNode::ApproachingDivider::myApproaching private
The list of edges that approach the current edge.
Definition at line 97 of file NBNode.h.
Referenced by ApproachingDivider(), and execute().
myAvailableLanes
std::vector<int> NBNode::ApproachingDivider::myAvailableLanes private
The available lanes to which connections shall be built.
Definition at line 103 of file NBNode.h.
Referenced by ApproachingDivider(), execute(), and spread().
myCurrentOutgoing
NBEdge* NBNode::ApproachingDivider::myCurrentOutgoing private
The approached current edge.
Definition at line 100 of file NBNode.h.
Referenced by ApproachingDivider(), and execute().
The documentation for this class was generated from the following files:
NBNode.h
NBNode.cpp