SUMO - Simulation of Urban MObility: LayeredRTree Class Reference
LayeredRTree Class Reference
A RT-tree for efficient storing of SUMO's GL-objects in layers.
#include <LayeredRTree.h>
Public Member Functions
void add (double x, double y, double z=0)
Makes the boundary include the given coordinate.
void add (const Position &p)
Makes the boundary include the given coordinate.
void add (const Boundary &p)
Makes the boundary include the given boundary.
void addAdditionalGLObject (GUIGlObject *o)
Adds an additional object (detector/shape/trigger) for visualisation.
bool around (const Position &p, double offset=0) const
Returns whether the boundary contains the given coordinate.
bool crosses (const Position &p1, const Position &p2) const
Returns whether the boundary crosses the given line.
double distanceTo2D (const Position &p) const
returns the euclidean distance in the x-y-plane
double distanceTo2D (const Boundary &b) const
returns the euclidean distance in the x-y-plane
void flipY ()
flips ymin and ymax
Position getCenter () const
Returns the center of the boundary.
double getHeight () const
Returns the height of the boundary (y-axis)
double getWidth () const
Returns the width of the boudary (x-axis)
double getZRange () const
Returns the elevation range of the boundary (z-axis)
Boundary & grow (double by)
extends the boundary by the given amount
void growHeight (double by)
Increases the height of the boundary (y-axis)
void growWidth (double by)
Increases the width of the boundary (x-axis)
void Insert (const float a_min[2], const float a_max[2], GUIGlObject *const &a_dataId)
Insert entry (delegate to appropriate layer)
LayeredRTree ()
Constructor.
void moveby (double x, double y, double z=0)
Moves the boundary by the given amount.
bool overlapsWith (const AbstractPoly &poly, double offset=0) const
Returns whether the boundary overlaps with the given polygon.
bool partialWithin (const AbstractPoly &poly, double offset=0) const
Returns whether the boundary is partially within the given polygon.
void Remove (const float a_min[2], const float a_max[2], GUIGlObject *const &a_dataId)
Remove entry (delegate to appropriate layer)
void removeAdditionalGLObject (GUIGlObject *o)
Removes an additional object (detector/shape/trigger) from being visualised.
void reset ()
Resets the boundary.
int Search (const float a_min[2], const float a_max[2], const GUIVisualizationSettings &c) const
Find all within search rectangle (searches all layers in order)
void set (double xmin, double ymin, double xmax, double ymax)
Sets the boundary to the given values.
double xmax () const
Returns maximum x-coordinate.
double xmin () const
Returns minimum x-coordinate.
double ymax () const
Returns maximum y-coordinate.
double ymin () const
Returns minimum y-coordinate.
double zmax () const
Returns maximum z-coordinate.
double zmin () const
Returns minimum z-coordinate.
~LayeredRTree ()
Destructor.
Protected Attributes
std::vector< SUMORTree * > myLayers
the layers for drawing
MFXMutex myLock
A mutex avoiding parallel change and traversal of the tree.
Private Member Functions
size_t selectLayer (GUIGlObject *o)
select the appropriate layer for each object
Detailed Description
A RT-tree for efficient storing of SUMO's GL-objects in layers.
This class maintains SUMORTrees for each layer (only 2 at the moment) but provides the same interface as SUMORTree
Definition at line 55 of file LayeredRTree.h.
Constructor & Destructor Documentation
LayeredRTree()
LayeredRTree::LayeredRTree () inline
Constructor.
Definition at line 58 of file LayeredRTree.h.
References myLayers, and SUMORTree::SUMORTree().
~LayeredRTree()
LayeredRTree::~LayeredRTree () inline
Destructor.
Definition at line 65 of file LayeredRTree.h.
References myLayers.
Member Function Documentation
add() [1/3]
void Boundary::add (double x, double y, double z = 0) inherited
Makes the boundary include the given coordinate.
Definition at line 85 of file Boundary.cpp.
References Boundary::myWasInitialised, Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by Boundary::add(), NIVissimConnectionCluster::NodeSubCluster::add(), NIVissimConnectionCluster::add(), ROEdge::addSuccessor(), MSEdge::addSuccessor(), Boundary::Boundary(), GUIDanielPerspectiveChanger::centerTo(), NBNetBuilder::compute(), GNENet::computeAndUpdate(), NIVissimDisturbance::computeBounding(), NIVissimConnection::computeBounding(), GUIEdge::getBoundary(), GNEEdge::getBoundary(), MSDevice_BTsender::VehicleInformation::getBoxBoundary(), PositionVector::getBoxBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIContainer::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GUIParkingArea::getCenteringBoundary(), GUIBaseVehicle::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUICalibrator::GUICalibrator(), GUILaneSpeedTrigger::GUILaneSpeedTrigger(), GUITriggeredRerouter::GUITriggeredRerouter(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), GUINet::initGUIStructures(), GNENet::initJunctionsAndEdges(), NBHeightMapper::loadShapeFile(), NBHeightMapper::loadTiff(), GNEViewNet::mergeJunctions(), GUITriggeredRerouter::myEndElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE3Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GNEViewNet::onLeftBtnRelease(), NIVissimConnectionCluster::recomputeBoundary(), GNENet::registerEdge(), GNENet::registerJunction(), GUIDanielPerspectiveChanger::setViewport(), GNEJunction::updateGeometry(), and GeoConvHelper::x2cartesian().
add() [2/3]
void Boundary::add (const Position & p) inherited
Makes the boundary include the given coordinate.
Definition at line 106 of file Boundary.cpp.
References Boundary::add(), Position::x(), Position::y(), and Position::z().
add() [3/3]
void Boundary::add (const Boundary & p) inherited
Makes the boundary include the given boundary.
Definition at line 112 of file Boundary.cpp.
References Boundary::add(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), Boundary::ymin(), Boundary::zmax(), and Boundary::zmin().
addAdditionalGLObject()
void SUMORTree::addAdditionalGLObject (GUIGlObject * o) inline inherited
Adds an additional object (detector/shape/trigger) for visualisation.
Parameters
[in] o The object to add
Definition at line 128 of file SUMORTree.h.
References GUIGlObject::getCenteringBoundary(), SUMORTree::Insert(), SUMORTree::myLock, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIShapeContainer::addPOI(), GUIShapeContainer::addPolygon(), GNENet::addPolygonForEditShapes(), GNETLSEditorFrame::buildIinternalLanes(), GUINet::createTLWrapper(), GUITriggeredRerouter::GUITriggeredRerouter(), GUINet::initGUIStructures(), GNENet::insertAdditional(), GNENet::insertShape(), GUIShapeContainer::movePOI(), GNENet::refreshElement(), GNENet::registerEdge(), GNENet::registerJunction(), and GUIShapeContainer::reshapePolygon().
around()
bool Boundary::around (const Position & p, double offset = 0) const virtual inherited
Returns whether the boundary contains the given coordinate.
Implements AbstractPoly.
Definition at line 179 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, Boundary::myZmin, Position::x(), Position::y(), and Position::z().
Referenced by PCPolyContainer::add(), NIVissimConnectionCluster::around(), NBHeightMapper::getZ(), and NIVissimConnectionCluster::recheckEdges().
crosses()
bool Boundary::crosses (const Position & p1, const Position & p2) const virtual inherited
Returns whether the boundary crosses the given line.
Implements AbstractPoly.
Definition at line 209 of file Boundary.cpp.
References PositionVector::intersects(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
distanceTo2D() [1/2]
double Boundary::distanceTo2D (const Position & p) const inherited
returns the euclidean distance in the x-y-plane
Definition at line 223 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Position::x(), and Position::y().
Referenced by ROEdge::getDistanceTo(), and MSEdge::getDistanceTo().
distanceTo2D() [2/2]
double Boundary::distanceTo2D (const Boundary & b) const inherited
returns the euclidean distance in the x-y-plane
Definition at line 257 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
flipY()
void Boundary::flipY () inherited
flips ymin and ymax
Definition at line 323 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GeoConvHelper::computeFinal().
getCenter()
Position Boundary::getCenter () const inherited
Returns the center of the boundary.
Definition at line 119 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by GUISUMOAbstractView::centerTo(), GUIDanielPerspectiveChanger::getXPos(), GUIDanielPerspectiveChanger::getYPos(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), GUIBaseVehicle::setFunctionalColor(), and GUIDanielPerspectiveChanger::zoom().
getHeight()
double Boundary::getHeight () const inherited
Returns the height of the boundary (y-axis)
Definition at line 167 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridHeight(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GNENet::initJunctionsAndEdges(), GUIDanielPerspectiveChanger::onKeyPress(), GUIPerspectiveChanger::patchedViewPort(), GUISUMOAbstractView::screenPos2NetPos(), and GNEJunction::updateGeometry().
getWidth()
double Boundary::getWidth () const inherited
Returns the width of the boudary (x-axis)
Definition at line 161 of file Boundary.cpp.
References Boundary::myXmax, and Boundary::myXmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridWidth(), GUIDanielPerspectiveChanger::getZoom(), GUIDanielPerspectiveChanger::getZPos(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GNENet::initJunctionsAndEdges(), GUISUMOAbstractView::m2p(), GUIDanielPerspectiveChanger::onKeyPress(), GUISUMOAbstractView::p2m(), GUIPerspectiveChanger::patchedViewPort(), GUISUMOAbstractView::screenPos2NetPos(), and GNEJunction::updateGeometry().
getZRange()
double Boundary::getZRange () const inherited
Returns the elevation range of the boundary (z-axis)
Definition at line 173 of file Boundary.cpp.
References Boundary::myZmax, and Boundary::myZmin.
Referenced by NBNetBuilder::compute().
grow()
Boundary & Boundary::grow (double by) inherited
extends the boundary by the given amount
The method returns a reference to the instance for further use
Definition at line 301 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), NBEdgeCont::checkOverlap(), libsumo::Helper::collectObjectsInRange(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), GUIEdge::getBoundary(), GNEEdge::getBoundary(), GNECrossing::getCenteringBoundary(), GNEJunction::getCenteringBoundary(), GNEInternalLane::getCenteringBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIInstantInductLoop::MyWrapper::getCenteringBoundary(), GUILaneSpeedTrigger::getCenteringBoundary(), GUIContainer::getCenteringBoundary(), GNELane::getCenteringBoundary(), GUICalibrator::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIJunctionWrapper::getCenteringBoundary(), GUIMEInductLoop::MyWrapper::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GNEConnection::getCenteringBoundary(), GUIE3Collector::MyWrapper::getCenteringBoundary(), GUITriggeredRerouter::getCenteringBoundary(), GUIChargingStation::getCenteringBoundary(), GUIContainerStop::getCenteringBoundary(), GUIBusStop::getCenteringBoundary(), GUIParkingArea::getCenteringBoundary(), GUIEdge::getCenteringBoundary(), GNEEdge::getCenteringBoundary(), GUIE2Collector::MyWrapper::getCenteringBoundary(), GUIBaseVehicle::getCenteringBoundary(), GUIInductLoop::MyWrapper::getCenteringBoundary(), GUITriggeredRerouter::GUITriggeredRerouterEdge::getCenteringBoundary(), GUILane::getCenteringBoundary(), GNEAdditional::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), NBEdgeCont::ignoreFilterMatch(), GUINet::initGUIStructures(), and GNEViewNet::mergeJunctions().
growHeight()
void Boundary::growHeight (double by) inherited
Increases the height of the boundary (y-axis)
Definition at line 317 of file Boundary.cpp.
References Boundary::myYmax, and Boundary::myYmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
growWidth()
void Boundary::growWidth (double by) inherited
Increases the width of the boundary (x-axis)
Definition at line 310 of file Boundary.cpp.
References Boundary::myXmax, and Boundary::myXmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
Insert()
void LayeredRTree::Insert (const float a_min[2], const float a_max[2], GUIGlObject *const & a_dataId) inline virtual
Insert entry (delegate to appropriate layer)
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
Reimplemented from SUMORTree.
Definition at line 78 of file LayeredRTree.h.
References myLayers, and selectLayer().
Referenced by GUINet::initGUIStructures().
moveby()
void Boundary::moveby (double x, double y, double z = 0) inherited
Moves the boundary by the given amount.
Definition at line 350 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), GUIDanielPerspectiveChanger::move(), GeoConvHelper::moveConvertedBy(), and GUIDanielPerspectiveChanger::onKeyPress().
overlapsWith()
bool Boundary::overlapsWith (const AbstractPoly & poly, double offset = 0) const virtual inherited
Returns whether the boundary overlaps with the given polygon.
Implements AbstractPoly.
Definition at line 188 of file Boundary.cpp.
References AbstractPoly::crosses(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, AbstractPoly::partialWithin(), and Boundary::partialWithin().
Referenced by NBEdgeCont::checkOverlap(), NIVissimBoundedClusterObject::crosses(), NBEdgeCont::ignoreFilterMatch(), NIVissimConnectionCluster::overlapsWith(), and NIVissimConnectionCluster::NodeSubCluster::overlapsWith().
partialWithin()
bool Boundary::partialWithin (const AbstractPoly & poly, double offset = 0) const virtual inherited
Returns whether the boundary is partially within the given polygon.
Implements AbstractPoly.
Definition at line 291 of file Boundary.cpp.
References AbstractPoly::around(), Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, and Boundary::myYmin.
Referenced by PCPolyContainer::add(), and Boundary::overlapsWith().
Remove()
void LayeredRTree::Remove (const float a_min[2], const float a_max[2], GUIGlObject *const & a_dataId) inline virtual
Remove entry (delegate to appropriate layer)
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_dataId Positive Id of data. Maybe zero, but negative numbers not allowed.
Reimplemented from SUMORTree.
Definition at line 88 of file LayeredRTree.h.
References myLayers, and selectLayer().
removeAdditionalGLObject()
void SUMORTree::removeAdditionalGLObject (GUIGlObject * o) inline inherited
Removes an additional object (detector/shape/trigger) from being visualised.
Parameters
[in] o The object to remove
Definition at line 140 of file SUMORTree.h.
References GUIGlObject::getCenteringBoundary(), SUMORTree::myLock, SUMORTree::Remove(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GNETLSEditorFrame::buildIinternalLanes(), GNENet::computeAndUpdate(), GNENet::deleteAdditional(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIShapeContainer::movePOI(), GNENet::refreshElement(), GUIShapeContainer::removePOI(), GUIShapeContainer::removePolygon(), GNENet::removePolygonForEditShapes(), GNENet::removeShape(), and GUIShapeContainer::reshapePolygon().
reset()
void Boundary::reset () inherited
Resets the boundary.
Definition at line 73 of file Boundary.cpp.
References Boundary::myWasInitialised, Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::myZmax, and Boundary::myZmin.
Referenced by NBHeightMapper::clearData(), and GNENet::computeAndUpdate().
Search()
int LayeredRTree::Search (const float a_min[2], const float a_max[2], const GUIVisualizationSettings & c) const inline virtual
Find all within search rectangle (searches all layers in order)
Parameters
a_min Min of search bounding rect
a_max Max of search bounding rect
a_searchResult Search result array. Caller should set grow size. Function will reset, not append to array.
a_resultCallback Callback function to return result. Callback should return 'true' to continue searching
a_context User context to pass as parameter to a_resultCallback
Returns
Returns the number of entries found
Reimplemented from SUMORTree.
Definition at line 100 of file LayeredRTree.h.
References myLayers.
selectLayer()
size_t LayeredRTree::selectLayer (GUIGlObject * o) inline private
select the appropriate layer for each object
Definition at line 116 of file LayeredRTree.h.
References GUIGlObject::getType(), GLO_EDGE, GLO_LANE, GLO_PERSON, GLO_POI, and GLO_VEHICLE.
Referenced by Insert(), and Remove().
set()
void Boundary::set (double xmin, double ymin, double xmax, double ymax) inherited
Sets the boundary to the given values.
Definition at line 341 of file Boundary.cpp.
References Boundary::myXmax, Boundary::myXmin, Boundary::myYmax, Boundary::myYmin, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::readTypeCheckingBoundary().
xmax()
double Boundary::xmax () const inherited
Returns maximum x-coordinate.
Definition at line 131 of file Boundary.cpp.
References Boundary::myXmax.
Referenced by Boundary::add(), NIVissimConnectionCluster::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), libsumo::Helper::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NBPTStopCont::findAccessEdgesForRailStops(), NIVissimConnection::getBoundingBox(), libsumo::Simulation::getNetBoundary(), NIVissimConnectionCluster::getPositionForEdge(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), SUMORTree::removeAdditionalGLObject(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
xmin()
double Boundary::xmin () const inherited
Returns minimum x-coordinate.
Definition at line 125 of file Boundary.cpp.
References Boundary::myXmin.
Referenced by Boundary::add(), NIVissimConnectionCluster::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUISUMOAbstractView::applyGLTransform(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), libsumo::Helper::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NBPTStopCont::findAccessEdgesForRailStops(), NIVissimConnection::getBoundingBox(), libsumo::Simulation::getNetBoundary(), NIVissimConnectionCluster::getPositionForEdge(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), SUMORTree::removeAdditionalGLObject(), GUISUMOAbstractView::screenPos2NetPos(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
ymax()
double Boundary::ymax () const inherited
Returns maximum y-coordinate.
Definition at line 143 of file Boundary.cpp.
References Boundary::myYmax.
Referenced by Boundary::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), libsumo::Helper::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NBPTStopCont::findAccessEdgesForRailStops(), libsumo::Simulation::getNetBoundary(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), SUMORTree::removeAdditionalGLObject(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
ymin()
double Boundary::ymin () const inherited
Returns minimum y-coordinate.
Definition at line 137 of file Boundary.cpp.
References Boundary::myYmin.
Referenced by Boundary::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUISUMOAbstractView::applyGLTransform(), GUIDanielPerspectiveChanger::changeCanvasSizeLeft(), libsumo::Helper::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NBPTStopCont::findAccessEdgesForRailStops(), libsumo::Simulation::getNetBoundary(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), SUMORTree::removeAdditionalGLObject(), GUISUMOAbstractView::screenPos2NetPos(), Boundary::set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and GUIDanielPerspectiveChanger::zoom().
zmax()
double Boundary::zmax () const inherited
Returns maximum z-coordinate.
Definition at line 155 of file Boundary.cpp.
References Boundary::myZmax.
Referenced by Boundary::add(), and libsumo::Simulation::getNetBoundary().
zmin()
double Boundary::zmin () const inherited
Returns minimum z-coordinate.
Definition at line 149 of file Boundary.cpp.
References Boundary::myZmin.
Referenced by Boundary::add(), and libsumo::Simulation::getNetBoundary().
Field Documentation
myLayers
std::vector<SUMORTree*> LayeredRTree::myLayers protected
the layers for drawing
Definition at line 111 of file LayeredRTree.h.
Referenced by Insert(), LayeredRTree(), Remove(), Search(), and ~LayeredRTree().
myLock
MFXMutex SUMORTree::myLock mutable protected inherited
A mutex avoiding parallel change and traversal of the tree.
Definition at line 151 of file SUMORTree.h.
Referenced by SUMORTree::addAdditionalGLObject(), SUMORTree::Insert(), SUMORTree::Remove(), SUMORTree::removeAdditionalGLObject(), and SUMORTree::Search().
The documentation for this class was generated from the following file:
LayeredRTree.h