SUMO - Simulation of Urban MObility: HelpersPHEMlight Class Reference
HelpersPHEMlight Class Reference
Helper methods for PHEMlight-based emission computation.
#include <HelpersPHEMlight.h>
Public Member Functions
void addAllClassesInto (std::vector< SUMOEmissionClass > &list) const
Add all known emission classes of this model to the given container.
double compute (const SUMOEmissionClass c, const PollutantsInterface::EmissionType e, const double v, const double a, const double slope, const std::map< int, double > *param) const
Returns the amount of emitted pollutant given the vehicle type and state (in mg/s or in ml/s for fuel)
std::string getAmitranVehicleClass (const SUMOEmissionClass c) const
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...)
SUMOEmissionClass getClass (const SUMOEmissionClass base, const std::string &vClass, const std::string &fuel, const std::string &eClass, const double weight) const
Returns the emission class described by the given parameters.
SUMOEmissionClass getClassByName (const std::string &eClass, const SUMOVehicleClass vc)
Checks whether the string describes a known vehicle class.
const std::string getClassName (const SUMOEmissionClass c) const
Returns the complete name of the emission class including the model.
int getEuroClass (const SUMOEmissionClass c) const
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6)
std::string getFuel (const SUMOEmissionClass c) const
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...)
double getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) const
Returns the adapted acceleration value, useful for comparing with external PHEMlight references.
const std::string & getName () const
Returns the name of the model.
double getWeight (const SUMOEmissionClass c) const
Returns a reference weight in kg described by this emission class as described in the Amitran interface This implementation returns only meaningful values for Solo_LKW (truck without trailer) and LNF (light duty vehicles).
HelpersPHEMlight ()
Constructor.
virtual bool isSilent (const SUMOEmissionClass c)
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Static Public Attributes
static const int PHEMLIGHT_BASE = 2 << 16
Protected Attributes
StringBijection< SUMOEmissionClass > myEmissionClassStrings
Mapping between emission class names and integer representations.
const std::string myName
the name of the model
Private Member Functions
double getEmission (const PHEMCEP *oldCep, PHEMlightdll::CEP *currCep, const std::string &e, const double p, const double v) const
Returns the amount of emitted pollutant given the vehicle type and state (in mg/s or in ml/s for fuel)
Private Attributes
PHEMlightdll::CEPHandler myCEPHandler
std::map< SUMOEmissionClass, PHEMlightdll::CEP * > myCEPs
PHEMlightdll::Helpers myHelper
int myIndex
the index of the next class
Detailed Description
Helper methods for PHEMlight-based emission computation.
Definition at line 55 of file HelpersPHEMlight.h.
Constructor & Destructor Documentation
HelpersPHEMlight()
HelpersPHEMlight::HelpersPHEMlight ()
Constructor.
Definition at line 48 of file HelpersPHEMlight.cpp.
References StringBijection< T >::insert(), PollutantsInterface::Helper::myEmissionClassStrings, and myIndex.
Member Function Documentation
addAllClassesInto()
void PollutantsInterface::Helper::addAllClassesInto (std::vector< SUMOEmissionClass > & list) const inline inherited
Add all known emission classes of this model to the given container.
Parameters
[in] list the vector to add to
Definition at line 253 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getAllClasses().
compute()
double HelpersPHEMlight::compute (const SUMOEmissionClass c, const PollutantsInterface::EmissionType e, const double v, const double a, const double slope, const std::map< int, double > * param) const virtual
Returns the amount of emitted pollutant given the vehicle type and state (in mg/s or in ml/s for fuel)
Parameters
[in] c The vehicle emission class
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
[in] slope The road's slope at vehicle's position [deg]
Returns
The amount of the pollutant emitted by the given emission class when moving with the given velocity and acceleration [mg/s or ml/s]
Implements PollutantsInterface::Helper.
Definition at line 262 of file HelpersPHEMlight.cpp.
References PHEMCEP::CalcPower(), PHEMlightdll::CEP::CalcPower(), PollutantsInterface::CO, PollutantsInterface::CO2, PollutantsInterface::ELEC, PollutantsInterface::FUEL, PHEMCEPHandler::GetCep(), PHEMlightdll::CEP::GetCO2Emission(), PHEMlightdll::CEP::GetDecelCoast(), getEmission(), PHEMlightdll::CEP::getFuelType(), PHEMCEPHandler::getHandlerInstance(), getModifiedAccel(), PHEMCEP::GetVehicleFuelType(), PollutantsInterface::HC, IDLE_SPEED, MAX2(), myCEPs, myHelper, PollutantsInterface::NO_X, PHEMLIGHT_BASE, PollutantsInterface::PM_X, SECONDS_PER_HOUR, PHEMlightdll::Constants::strBEV, PHEMlightdll::Constants::strDiesel, PHEMlightdll::Constants::strGasoline, and PHEMlightdll::Constants::ZERO_SPEED_ACCURACY.
getAmitranVehicleClass()
std::string HelpersPHEMlight::getAmitranVehicleClass (const SUMOEmissionClass c) const virtual
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...)
Parameters
[in] c the emission class
Returns
the name of the vehicle class
Reimplemented from PollutantsInterface::Helper.
Definition at line 164 of file HelpersPHEMlight.cpp.
References StringBijection< T >::getString(), and PollutantsInterface::Helper::myEmissionClassStrings.
getClass()
SUMOEmissionClass HelpersPHEMlight::getClass (const SUMOEmissionClass base, const std::string & vClass, const std::string & fuel, const std::string & eClass, const double weight) const virtual
Returns the emission class described by the given parameters.
Parameters
[in] base the base class giving the default
[in] vClass the vehicle class as described in the Amitran interface (Passenger, ...)
[in] fuel the fuel type as described in the Amitran interface (Gasoline, Diesel, ...)
[in] eClass the emission class as described in the Amitran interface (Euro0, ...)
[in] weight the vehicle weight in kg as described in the Amitran interface
Returns
the class described by the parameters
Reimplemented from PollutantsInterface::Helper.
Definition at line 101 of file HelpersPHEMlight.cpp.
References StringBijection< T >::get(), StringBijection< T >::hasString(), and PollutantsInterface::Helper::myEmissionClassStrings.
getClassByName()
SUMOEmissionClass HelpersPHEMlight::getClassByName (const std::string & eClass, const SUMOVehicleClass vc) virtual
Checks whether the string describes a known vehicle class.
Parameters
[in] eClass The string describing the vehicle emission class
Returns
whether it describes a valid emission class
Reimplemented from PollutantsInterface::Helper.
Definition at line 54 of file HelpersPHEMlight.cpp.
References StringBijection< T >::addAlias(), StringBijection< T >::get(), PHEMlightdll::CEPHandler::GetCEP(), PHEMlightdll::CEPHandler::getCEPS(), PHEMlightdll::Helpers::getErrMsg(), PHEMlightdll::Helpers::getgClass(), PHEMCEPHandler::getHandlerInstance(), OptionsCont::getOptions(), StringBijection< T >::hasString(), PollutantsInterface::HEAVY_BIT, StringBijection< T >::insert(), myCEPHandler, myCEPs, PollutantsInterface::Helper::myEmissionClassStrings, myHelper, myIndex, StringBijection< T >::remove(), PHEMlightdll::Helpers::setclass(), PHEMlightdll::Helpers::setCommentPrefix(), and PHEMlightdll::Helpers::setPHEMDataV().
getClassName()
const std::string PollutantsInterface::Helper::getClassName (const SUMOEmissionClass c) const inline inherited
Returns the complete name of the emission class including the model.
Parameters
[in] c the emission class
Returns
the name of the class (the complete emission class attribute)
Definition at line 148 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getName().
getEmission()
double HelpersPHEMlight::getEmission (const PHEMCEP * oldCep, PHEMlightdll::CEP * currCep, const std::string & e, const double p, const double v) const private
Returns the amount of emitted pollutant given the vehicle type and state (in mg/s or in ml/s for fuel)
Parameters
[in] currCep The vehicle emission class
[in] e The emission type
[in] p The vehicle's current power
[in] v The vehicle's current velocity
Returns
The amount of the pollutant emitted by the given emission class when moving with the given velocity and acceleration [mg/s or ml/s]
Definition at line 243 of file HelpersPHEMlight.cpp.
References PHEMCEP::GetEmission(), PHEMlightdll::CEP::GetEmission(), and myHelper.
Referenced by compute().
getEuroClass()
int HelpersPHEMlight::getEuroClass (const SUMOEmissionClass c) const virtual
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6)
Parameters
[in] c the emission class
Returns
the Euro class
Reimplemented from PollutantsInterface::Helper.
Definition at line 200 of file HelpersPHEMlight.cpp.
References StringBijection< T >::getString(), and PollutantsInterface::Helper::myEmissionClassStrings.
getFuel()
std::string HelpersPHEMlight::getFuel (const SUMOEmissionClass c) const virtual
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...)
Parameters
[in] c the emission class
Returns
the fuel type
Reimplemented from PollutantsInterface::Helper.
Definition at line 186 of file HelpersPHEMlight.cpp.
References StringBijection< T >::getString(), and PollutantsInterface::Helper::myEmissionClassStrings.
getModifiedAccel()
double HelpersPHEMlight::getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) const virtual
Returns the adapted acceleration value, useful for comparing with external PHEMlight references.
Parameters
[in] c the emission class
[in] v the speed value
[in] a the acceleration value
[in] slope The road's slope at vehicle's position [deg]
Returns
the modified acceleration
Reimplemented from PollutantsInterface::Helper.
Definition at line 252 of file HelpersPHEMlight.cpp.
References PHEMlightdll::CEP::GetMaxAccel(), MIN2(), and myCEPs.
Referenced by compute().
getName()
const std::string& PollutantsInterface::Helper::getName () const inline inherited
Returns the name of the model.
Returns
the name of the model (string before the '/' in the emission class attribute)
Definition at line 121 of file PollutantsInterface.h.
getWeight()
double HelpersPHEMlight::getWeight (const SUMOEmissionClass c) const virtual
Returns a reference weight in kg described by this emission class as described in the Amitran interface This implementation returns only meaningful values for Solo_LKW (truck without trailer) and LNF (light duty vehicles).
Parameters
[in] c the emission class
Returns
a reference weight
Reimplemented from PollutantsInterface::Helper.
Definition at line 220 of file HelpersPHEMlight.cpp.
References StringBijection< T >::getString(), and PollutantsInterface::Helper::myEmissionClassStrings.
isSilent()
virtual bool PollutantsInterface::Helper::isSilent (const SUMOEmissionClass c) inline virtual inherited
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Parameters
[in] c the emission class
Returns
whether the class denotes a silent vehicle
Definition at line 157 of file PollutantsInterface.h.
References PollutantsInterface::HEAVY_BIT.
Referenced by PollutantsInterface::isSilent().
Field Documentation
myCEPHandler
PHEMlightdll::CEPHandler HelpersPHEMlight::myCEPHandler private
Definition at line 137 of file HelpersPHEMlight.h.
Referenced by getClassByName().
myCEPs
std::map<SUMOEmissionClass, PHEMlightdll::CEP*> HelpersPHEMlight::myCEPs private
Definition at line 139 of file HelpersPHEMlight.h.
Referenced by compute(), getClassByName(), and getModifiedAccel().
myEmissionClassStrings
StringBijection<SUMOEmissionClass> PollutantsInterface::Helper::myEmissionClassStrings protected inherited
Mapping between emission class names and integer representations.
Definition at line 263 of file PollutantsInterface.h.
Referenced by HelpersHBEFA3::getAmitranVehicleClass(), getAmitranVehicleClass(), HelpersHBEFA3::getClass(), getClass(), getClassByName(), HelpersHBEFA3::getEuroClass(), getEuroClass(), HelpersHBEFA3::getFuel(), getFuel(), getWeight(), HelpersEnergy::HelpersEnergy(), HelpersHBEFA::HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), and HelpersPHEMlight().
myHelper
PHEMlightdll::Helpers HelpersPHEMlight::myHelper mutable private
Definition at line 138 of file HelpersPHEMlight.h.
Referenced by compute(), getClassByName(), and getEmission().
myIndex
int HelpersPHEMlight::myIndex private
the index of the next class
Definition at line 136 of file HelpersPHEMlight.h.
Referenced by getClassByName(), and HelpersPHEMlight().
myName
const std::string PollutantsInterface::Helper::myName protected inherited
the name of the model
Definition at line 260 of file PollutantsInterface.h.
PHEMLIGHT_BASE
const int HelpersPHEMlight::PHEMLIGHT_BASE = 2 << 16 static
Definition at line 57 of file HelpersPHEMlight.h.
Referenced by compute().
The documentation for this class was generated from the following files:
HelpersPHEMlight.h
HelpersPHEMlight.cpp