SUMO - Simulation of Urban MObility: NBTurningDirectionsComputer Class Reference
NBTurningDirectionsComputer Class Reference
#include <NBAlgorithms.h>
Data Structures
struct Combination
Stores the information about the angle between an incoming ("from") and an outgoing ("to") edge.
class combination_by_angle_sorter
Sorts "Combination"s by decreasing angle.
Static Public Member Functions
static void computeTurnDirections (NBNodeCont &nc, bool warn=true)
Computes turnaround destinations for all edges (if exist)
static void computeTurnDirectionsForNode (NBNode *node, bool warn)
Computes turnaround destinations for all incoming edges of the given nodes (if any)
Detailed Description
Definition at line 52 of file NBAlgorithms.h.
Member Function Documentation
computeTurnDirections()
void NBTurningDirectionsComputer::computeTurnDirections (NBNodeCont & nc, bool warn = true) static
Computes turnaround destinations for all edges (if exist)
Parameters
[in] nc The container of nodes to loop along
[in] warn Whether warnings shall be issued
Definition at line 51 of file NBAlgorithms.cpp.
References NBNodeCont::begin(), computeTurnDirectionsForNode(), and NBNodeCont::end().
Referenced by NBNetBuilder::compute().
computeTurnDirectionsForNode()
void NBTurningDirectionsComputer::computeTurnDirectionsForNode (NBNode * node, bool warn) static
Computes turnaround destinations for all incoming edges of the given nodes (if any)
Parameters
[in] node The node for which to compute turnaround destinations
[in] warn Whether warnings shall be issued
Note
: This is needed by NETEDIT
Definition at line 58 of file NBAlgorithms.cpp.
References NBTurningDirectionsComputer::Combination::angle, NBTurningDirectionsComputer::Combination::from, NBEdge::getAngleAtNode(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), NBNode::getIncomingEdges(), NBNode::getOutgoingEdges(), NBEdge::getToNode(), NBHelpers::normRelAngle(), POSITION_EPS, NBTurningDirectionsComputer::Combination::to, and WRITE_WARNING.
Referenced by computeTurnDirections(), GNEJunction::getPopUpMenu(), and GNEJunction::setLogicValid().
The documentation for this class was generated from the following files:
NBAlgorithms.h
NBAlgorithms.cpp