SUMO - Simulation of Urban MObility: NBPTStop Class Reference
NBPTStop Class Reference
The representation of a single pt stop.
#include <NBPTStop.h>
Public Member Functions
void addAccess (std::string laneID, double offset)
void addPlatformCand (NBPTPlatform platform)
void computExtent (double center, double d)
bool findLaneAndComputeBusStopExtend (NBEdgeCont &ec)
const std::string getEdgeId ()
std::string getID () const
bool getIsMultipleStopPositions ()
double getLength ()
const std::map< std::string, std::string > & getMyAdditionalEdgeCandidates () const
const std::string getName ()
const std::string getOrigEdgeId ()
SVCPermissions getPermissions ()
std::vector< NBPTPlatform > & getPlatformCands ()
const Position & getPosition ()
NBPTStop (std::string ptStopId, Position position, std::string edgeId, std::string origEdgeId, double length, std::string name, SVCPermissions svcPermissions)
Constructor.
void registerAdditionalEdge (std::string wayId, std::string edgeId)
void reshiftPostion (const double offsetX, const double offsetY)
bool setEdgeId (std::string edgeId, NBEdgeCont &ec)
void setIsMultipleStopPositions (bool multipleStopPositions)
void setMyOrigEdgeId (const std::string &myOrigEdgeId)
void setMyPTStopId (std::string id)
void setMyPTStopLength (double myPTStopLength)
void write (OutputDevice &device)
Private Member Functions
NBPTStop & operator= (const NBPTStop &)
Invalidated assignment operator.
Private Attributes
std::vector< std::tuple< std::string, double > > myAccesses
std::map< std::string, std::string > myAdditionalEdgeCandidates
std::string myEdgeId
double myEndPos
bool myIsMultipleStopPositions
std::string myLaneId
const std::string myName
std::string myOrigEdgeId
const SVCPermissions myPermissions
std::vector< NBPTPlatform > myPlatformCands
Position myPosition
std::string myPTStopId
double myPTStopLength
double myStartPos
Detailed Description
The representation of a single pt stop.
Definition at line 51 of file NBPTStop.h.
Constructor & Destructor Documentation
NBPTStop()
NBPTStop::NBPTStop (std::string ptStopId, Position position, std::string edgeId, std::string origEdgeId, double length, std::string name, SVCPermissions svcPermissions)
Constructor.
Parameters
[in] id The id of the pt stop
[in] position The position of the pt stop
[in] edgeId The edge id of the pt stop
[in] length The length of the pt stop
Definition at line 40 of file NBPTStop.cpp.
Member Function Documentation
addAccess()
void NBPTStop::addAccess (std::string laneID, double offset)
Definition at line 179 of file NBPTStop.cpp.
References myAccesses.
addPlatformCand()
void NBPTStop::addPlatformCand (NBPTPlatform platform)
Definition at line 116 of file NBPTStop.cpp.
References myPlatformCands.
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
computExtent()
void NBPTStop::computExtent (double center, double d)
Definition at line 76 of file NBPTStop.cpp.
References MAX2(), MIN2(), myEndPos, myPTStopLength, and myStartPos.
Referenced by findLaneAndComputeBusStopExtend().
findLaneAndComputeBusStopExtend()
bool NBPTStop::findLaneAndComputeBusStopExtend (NBEdgeCont & ec)
Definition at line 155 of file NBPTStop.cpp.
References computExtent(), NBEdgeCont::getByID(), NBEdge::getLaneID(), NBEdge::getLanes(), NBEdge::getLaneShape(), getPermissions(), getPosition(), PositionVector::length(), myEdgeId, myLaneId, and PositionVector::nearest_offset_to_point2D().
Referenced by NBPTStopCont::assignLanes(), and setEdgeId().
getEdgeId()
const std::string NBPTStop::getEdgeId ()
Definition at line 64 of file NBPTStop.cpp.
References myEdgeId.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), NBPTLineCont::constructRoute(), and NBPTStopCont::getReverseStop().
getID()
std::string NBPTStop::getID () const
Definition at line 54 of file NBPTStop.cpp.
References myPTStopId.
Referenced by NBPTStopCont::getReverseStop(), and NBPTStopCont::insert().
getIsMultipleStopPositions()
bool NBPTStop::getIsMultipleStopPositions ()
Definition at line 122 of file NBPTStop.cpp.
References myIsMultipleStopPositions.
Referenced by NBPTStopCont::localizePTStops().
getLength()
double NBPTStop::getLength ()
Definition at line 129 of file NBPTStop.cpp.
References myPTStopLength.
Referenced by NBPTStopCont::getReverseStop().
getMyAdditionalEdgeCandidates()
const std::map< std::string, std::string > & NBPTStop::getMyAdditionalEdgeCandidates () const
Definition at line 142 of file NBPTStop.cpp.
References myAdditionalEdgeCandidates.
getName()
const std::string NBPTStop::getName ()
Definition at line 69 of file NBPTStop.cpp.
References myName.
Referenced by NBPTStopCont::getReverseStop().
getOrigEdgeId()
const std::string NBPTStop::getOrigEdgeId ()
Definition at line 59 of file NBPTStop.cpp.
References myOrigEdgeId.
getPermissions()
SVCPermissions NBPTStop::getPermissions ()
Definition at line 113 of file NBPTStop.cpp.
References myPermissions.
Referenced by findLaneAndComputeBusStopExtend(), and NBPTStopCont::getReverseStop().
getPlatformCands()
std::vector< NBPTPlatform > & NBPTStop::getPlatformCands ()
Definition at line 119 of file NBPTStop.cpp.
References myPlatformCands.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::getClosestPlatformToPTStopPosition(), and NBPTStopCont::localizePTStops().
getPosition()
const Position & NBPTStop::getPosition ()
Definition at line 72 of file NBPTStop.cpp.
References myPosition.
Referenced by findLaneAndComputeBusStopExtend(), NBPTStopCont::getClosestPlatformToPTStopPosition(), and NBPTStopCont::getReverseStop().
operator=()
NBPTStop& NBPTStop::operator= (const NBPTStop &) private
Invalidated assignment operator.
registerAdditionalEdge()
void NBPTStop::registerAdditionalEdge (std::string wayId, std::string edgeId)
Definition at line 139 of file NBPTStop.cpp.
References myAdditionalEdgeCandidates.
Referenced by NIImporter_OpenStreetMap::insertEdge().
reshiftPostion()
void NBPTStop::reshiftPostion (const double offsetX, const double offsetY)
Definition at line 104 of file NBPTStop.cpp.
References Position::add(), myPlatformCands, and myPosition.
setEdgeId()
bool NBPTStop::setEdgeId (std::string edgeId, NBEdgeCont & ec)
Definition at line 134 of file NBPTStop.cpp.
References findLaneAndComputeBusStopExtend(), and myEdgeId.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), and NBPTStopCont::assignPTStopToEdgeOfClosestPlatform().
setIsMultipleStopPositions()
void NBPTStop::setIsMultipleStopPositions (bool multipleStopPositions)
Definition at line 126 of file NBPTStop.cpp.
References myIsMultipleStopPositions.
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
setMyOrigEdgeId()
void NBPTStop::setMyOrigEdgeId (const std::string & myOrigEdgeId)
Definition at line 145 of file NBPTStop.cpp.
References myOrigEdgeId.
setMyPTStopId()
void NBPTStop::setMyPTStopId (std::string id)
Definition at line 176 of file NBPTStop.cpp.
References myPTStopId.
setMyPTStopLength()
void NBPTStop::setMyPTStopLength (double myPTStopLength)
Definition at line 149 of file NBPTStop.cpp.
References myPTStopLength.
Referenced by NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), and NBPTStopCont::assignPTStopToEdgeOfClosestPlatform().
write()
void NBPTStop::write (OutputDevice & device)
Definition at line 81 of file NBPTStop.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), myAccesses, myEndPos, myLaneId, myName, myPTStopId, myStartPos, OutputDevice::openTag(), SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_NAME, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_TAG_ACCESS, SUMO_TAG_BUS_STOP, and OutputDevice::writeAttr().
Field Documentation
myAccesses
std::vector<std::tuple<std::string, double> > NBPTStop::myAccesses private
Definition at line 106 of file NBPTStop.h.
Referenced by addAccess(), and write().
myAdditionalEdgeCandidates
std::map<std::string, std::string> NBPTStop::myAdditionalEdgeCandidates private
Definition at line 87 of file NBPTStop.h.
Referenced by getMyAdditionalEdgeCandidates(), and registerAdditionalEdge().
myEdgeId
std::string NBPTStop::myEdgeId private
Definition at line 86 of file NBPTStop.h.
Referenced by findLaneAndComputeBusStopExtend(), getEdgeId(), and setEdgeId().
myEndPos
double NBPTStop::myEndPos private
Definition at line 104 of file NBPTStop.h.
Referenced by computExtent(), and write().
myIsMultipleStopPositions
bool NBPTStop::myIsMultipleStopPositions private
Definition at line 115 of file NBPTStop.h.
Referenced by getIsMultipleStopPositions(), and setIsMultipleStopPositions().
myLaneId
std::string NBPTStop::myLaneId private
Definition at line 100 of file NBPTStop.h.
Referenced by findLaneAndComputeBusStopExtend(), and write().
myName
const std::string NBPTStop::myName private
Definition at line 99 of file NBPTStop.h.
Referenced by getName(), and write().
myOrigEdgeId
std::string NBPTStop::myOrigEdgeId private
Definition at line 91 of file NBPTStop.h.
Referenced by getOrigEdgeId(), and setMyOrigEdgeId().
myPermissions
const SVCPermissions NBPTStop::myPermissions private
Definition at line 101 of file NBPTStop.h.
Referenced by getPermissions().
myPlatformCands
std::vector<NBPTPlatform> NBPTStop::myPlatformCands private
Definition at line 114 of file NBPTStop.h.
Referenced by addPlatformCand(), getPlatformCands(), and reshiftPostion().
myPosition
Position NBPTStop::myPosition private
Definition at line 85 of file NBPTStop.h.
Referenced by getPosition(), and reshiftPostion().
myPTStopId
std::string NBPTStop::myPTStopId private
Definition at line 84 of file NBPTStop.h.
Referenced by getID(), setMyPTStopId(), and write().
myPTStopLength
double NBPTStop::myPTStopLength private
Definition at line 95 of file NBPTStop.h.
Referenced by computExtent(), getLength(), and setMyPTStopLength().
myStartPos
double NBPTStop::myStartPos private
Definition at line 103 of file NBPTStop.h.
Referenced by computExtent(), and write().
The documentation for this class was generated from the following files:
NBPTStop.h
NBPTStop.cpp