SUMO - Simulation of Urban MObility: NBPTLine Class Reference
NBPTLine Class Reference
#include <NBPTLine.h>
Public Member Functions
void addEdgeVector (std::vector< NBEdge *>::iterator fr, std::vector< NBEdge *>::iterator to)
void addPTStop (NBPTStop *pStop)
void addWayNode (long long int way, long long int node)
long long int getLineID () const
const std::vector< std::string > & getMyWays () const
const std::string & getName () const
const std::vector< NBEdge * > & getRoute () const
std::vector< NBPTStop * > getStops ()
std::vector< long long int > * getWaysNodes (std::string wayId)
NBPTLine (const std::string &name, const std::string &type)
void setId (long long int id)
void setMyNumOfStops (int numStops)
void setRef (std::string basic_string)
void write (OutputDevice &device, NBEdgeCont &ec)
Private Attributes
std::string myCurrentWay
std::string myName
int myNumOfStops
long long int myPTLineId
std::vector< NBPTStop * > myPTStops
std::string myRef
std::vector< NBEdge * > myRoute
std::string myType
std::vector< std::string > myWays
std::map< std::string, std::vector< long long int > > myWaysNodes
Detailed Description
Definition at line 36 of file NBPTLine.h.
Constructor & Destructor Documentation
NBPTLine()
NBPTLine::NBPTLine (const std::string & name, const std::string & type) explicit
Definition at line 29 of file NBPTLine.cpp.
Member Function Documentation
addEdgeVector()
void NBPTLine::addEdgeVector (std::vector< NBEdge *>::iterator fr, std::vector< NBEdge *>::iterator to)
Definition at line 115 of file NBPTLine.cpp.
References myRoute.
Referenced by NBPTLineCont::constructRoute().
addPTStop()
void NBPTLine::addPTStop (NBPTStop * pStop)
Definition at line 36 of file NBPTLine.cpp.
References myPTStops.
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
addWayNode()
void NBPTLine::addWayNode (long long int way, long long int node)
Definition at line 93 of file NBPTLine.cpp.
References myCurrentWay, myWays, myWaysNodes, and toString().
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
getLineID()
long long int NBPTLine::getLineID () const
Definition at line 45 of file NBPTLine.cpp.
References myPTLineId.
Referenced by NBPTLineCont::constructRoute().
getMyWays()
const std::vector< std::string > & NBPTLine::getMyWays () const
Definition at line 102 of file NBPTLine.cpp.
References myWays.
Referenced by NBPTLineCont::constructRoute(), and NBPTLineCont::reviseStops().
getName()
const std::string & NBPTLine::getName () const
Definition at line 40 of file NBPTLine.cpp.
References myName.
Referenced by NBPTLineCont::constructRoute(), and NBPTLineCont::reviseStops().
getRoute()
const std::vector< NBEdge * > & NBPTLine::getRoute () const
Definition at line 122 of file NBPTLine.cpp.
References myRoute.
getStops()
std::vector< NBPTStop * > NBPTLine::getStops ()
Definition at line 49 of file NBPTLine.cpp.
References myPTStops.
Referenced by NBPTLineCont::constructRoute(), NIImporter_OpenStreetMap::RelationHandler::myEndElement(), and NBPTLineCont::reviseStops().
getWaysNodes()
std::vector< long long int > * NBPTLine::getWaysNodes (std::string wayId)
Definition at line 105 of file NBPTLine.cpp.
References myWaysNodes.
Referenced by NBPTLineCont::reviseStops().
setId()
void NBPTLine::setId (long long int id)
Definition at line 90 of file NBPTLine.cpp.
References myPTLineId.
Referenced by NBPTLineCont::insert().
setMyNumOfStops()
void NBPTLine::setMyNumOfStops (int numStops)
Definition at line 119 of file NBPTLine.cpp.
References myNumOfStops.
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
setRef()
void NBPTLine::setRef (std::string basic_string)
Definition at line 111 of file NBPTLine.cpp.
References myRef.
Referenced by NIImporter_OpenStreetMap::RelationHandler::myEndElement().
write()
void NBPTLine::write (OutputDevice & device, NBEdgeCont & ec)
Definition at line 52 of file NBPTLine.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), myName, myNumOfStops, myPTLineId, myPTStops, myRef, myRoute, myType, OutputDevice::openTag(), NBEdgeCont::retrieve(), SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_NAME, SUMO_ATTR_TYPE, SUMO_TAG_BUS_STOP, SUMO_TAG_PT_LINE, SUMO_TAG_ROUTE, toString(), and OutputDevice::writeAttr().
Field Documentation
myCurrentWay
std::string NBPTLine::myCurrentWay private
Definition at line 64 of file NBPTLine.h.
Referenced by addWayNode().
myName
std::string NBPTLine::myName private
Definition at line 52 of file NBPTLine.h.
Referenced by getName(), and write().
myNumOfStops
int NBPTLine::myNumOfStops private
Definition at line 77 of file NBPTLine.h.
Referenced by setMyNumOfStops(), and write().
myPTLineId
long long int NBPTLine::myPTLineId private
Definition at line 65 of file NBPTLine.h.
Referenced by getLineID(), setId(), and write().
myPTStops
std::vector<NBPTStop*> NBPTLine::myPTStops private
Definition at line 54 of file NBPTLine.h.
Referenced by addPTStop(), getStops(), and write().
myRef
std::string NBPTLine::myRef private
Definition at line 66 of file NBPTLine.h.
Referenced by setRef(), and write().
myRoute
std::vector<NBEdge*> NBPTLine::myRoute private
Definition at line 72 of file NBPTLine.h.
Referenced by addEdgeVector(), getRoute(), and write().
myType
std::string NBPTLine::myType private
Definition at line 53 of file NBPTLine.h.
Referenced by write().
myWays
std::vector<std::string> NBPTLine::myWays private
Definition at line 58 of file NBPTLine.h.
Referenced by addWayNode(), and getMyWays().
myWaysNodes
std::map<std::string, std::vector<long long int> > NBPTLine::myWaysNodes private
Definition at line 57 of file NBPTLine.h.
Referenced by addWayNode(), and getWaysNodes().
The documentation for this class was generated from the following files:
NBPTLine.h
NBPTLine.cpp