SUMO - Simulation of Urban MObility: GUIParam_PopupMenuInterface Class Reference
GUIParam_PopupMenuInterface Class Reference
A popup-menu for dynamic patameter table entries.
#include <GUIParam_PopupMenu.h>
Public Member Functions
GUIParam_PopupMenuInterface (GUIMainWindow &app, GUIParameterTableWindow &parentWindow, GUIGlObject &o, const std::string &varName, ValueSource< double > *src)
Constructor.
~GUIParam_PopupMenuInterface ()
Destructor.
FOX-callbacks
long onCmdOpenTracker (FXObject *, FXSelector, void *)
Called when a tracker for the value shall be opened.
Protected Member Functions
GUIParam_PopupMenuInterface ()
FOX needs this.
Protected Attributes
GUIMainWindow * myApplication
The main application window; holder of some needed values.
GUIGlObject * myObject
The object the table displays.
GUIParameterTableWindow * myParentWindow
The parameter window this popup was initiated by.
ValueSource< double > * mySource
The source of the value.
std::string myVarName
The name of the value.
Detailed Description
A popup-menu for dynamic patameter table entries.
Definition at line 54 of file GUIParam_PopupMenu.h.
Constructor & Destructor Documentation
GUIParam_PopupMenuInterface() [1/2]
GUIParam_PopupMenuInterface::GUIParam_PopupMenuInterface (GUIMainWindow & app, GUIParameterTableWindow & parentWindow, GUIGlObject & o, const std::string & varName, ValueSource< double > * src)
Constructor.
Parameters
[in] app The main application window
[in] parentWindow The parent window (the table the popup belongs to)
[in] o The object represented by the table
[in] varName The name of the value
[in] src The value source
Definition at line 56 of file GUIParam_PopupMenu.cpp.
~GUIParam_PopupMenuInterface()
GUIParam_PopupMenuInterface::~GUIParam_PopupMenuInterface ()
Destructor.
Definition at line 64 of file GUIParam_PopupMenu.cpp.
References mySource.
GUIParam_PopupMenuInterface() [2/2]
GUIParam_PopupMenuInterface::GUIParam_PopupMenuInterface () inline protected
FOX needs this.
Definition at line 105 of file GUIParam_PopupMenu.h.
Member Function Documentation
onCmdOpenTracker()
long GUIParam_PopupMenuInterface::onCmdOpenTracker (FXObject * , FXSelector , void *)
Called when a tracker for the value shall be opened.
Builds a new GUIParameterTracker adding the stored value to it. Initialises this tracker, then.
Definition at line 70 of file GUIParam_PopupMenu.cpp.
References GUIParameterTracker::addTracked(), RGBColor::BLACK, ValueSource< T >::copy(), GUIParameterTracker::create(), GUIMainWindow::getCurrentSimTime(), GUIGlObject::getFullName(), GUIMainWindow::getTrackerInterval(), myApplication, myObject, mySource, and myVarName.
Field Documentation
myApplication
GUIMainWindow* GUIParam_PopupMenuInterface::myApplication protected
The main application window; holder of some needed values.
Definition at line 95 of file GUIParam_PopupMenu.h.
Referenced by onCmdOpenTracker().
myObject
GUIGlObject* GUIParam_PopupMenuInterface::myObject protected
The object the table displays.
Definition at line 89 of file GUIParam_PopupMenu.h.
Referenced by onCmdOpenTracker().
myParentWindow
GUIParameterTableWindow* GUIParam_PopupMenuInterface::myParentWindow protected
The parameter window this popup was initiated by.
Definition at line 92 of file GUIParam_PopupMenu.h.
mySource
ValueSource<double>* GUIParam_PopupMenuInterface::mySource protected
The source of the value.
Definition at line 101 of file GUIParam_PopupMenu.h.
Referenced by onCmdOpenTracker(), and ~GUIParam_PopupMenuInterface().
myVarName
std::string GUIParam_PopupMenuInterface::myVarName protected
The name of the value.
Definition at line 98 of file GUIParam_PopupMenu.h.
Referenced by onCmdOpenTracker().
The documentation for this class was generated from the following files:
GUIParam_PopupMenu.h
GUIParam_PopupMenu.cpp