SUMO - Simulation of Urban MObility: NBCapacity2Lanes Class Reference
NBCapacity2Lanes Class Reference
A helper class which computes the lane number from given capacity.
#include <NBCapacity2Lanes.h>
Public Member Functions
int get (double capacity) const
Returns the number of lanes computed from the given capacity.
NBCapacity2Lanes (double divider)
Donstructor.
~NBCapacity2Lanes ()
Destructor.
Private Attributes
double myDivider
The norming divider.
Detailed Description
A helper class which computes the lane number from given capacity.
A helper class for the computation of the number of lanes an edge has in dependence to this edge's capacity. The computation is done by the (trivial) assumption, the number of lanes increases linear with the number of lanes.
Definition at line 46 of file NBCapacity2Lanes.h.
Constructor & Destructor Documentation
NBCapacity2Lanes()
NBCapacity2Lanes::NBCapacity2Lanes (double divider) inline
Donstructor.
Parameters
[in] divider Value for the norming divider
Definition at line 52 of file NBCapacity2Lanes.h.
~NBCapacity2Lanes()
NBCapacity2Lanes::~NBCapacity2Lanes () inline
Destructor.
Definition at line 56 of file NBCapacity2Lanes.h.
Member Function Documentation
get()
int NBCapacity2Lanes::get (double capacity) const inline
Returns the number of lanes computed from the given capacity.
Returns the esimtaed number of lanes by returning the given capacity divided by the norming divider given in the constructor.
Parameters
[in] capacity The capacity to convert
Returns
The capacity converted to the number of lanes
Definition at line 67 of file NBCapacity2Lanes.h.
References myDivider.
Referenced by NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_VISUM::parse_Edges(), and NIImporter_VISUM::parse_Types().
Field Documentation
myDivider
double NBCapacity2Lanes::myDivider private
The norming divider.
Definition at line 81 of file NBCapacity2Lanes.h.
Referenced by get().
The documentation for this class was generated from the following file:
NBCapacity2Lanes.h