SUMO - Simulation of Urban MObility: NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort Class Reference
NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort Class Reference
#include <NLBuilder.h>
Public Member Functions
void addEdgeWeight (const std::string &id, double val, double beg, double end) const
Adds an effort for a given edge and time period.
EdgeFloatTimeLineRetriever_EdgeEffort (MSNet &net)
Constructor.
~EdgeFloatTimeLineRetriever_EdgeEffort ()
Destructor.
Private Attributes
MSNet & myNet
The network edges shall be obtained from.
Detailed Description
Definition at line 149 of file NLBuilder.h.
Constructor & Destructor Documentation
EdgeFloatTimeLineRetriever_EdgeEffort()
NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::EdgeFloatTimeLineRetriever_EdgeEffort (MSNet & net) inline
Constructor.
Definition at line 152 of file NLBuilder.h.
~EdgeFloatTimeLineRetriever_EdgeEffort()
NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::~EdgeFloatTimeLineRetriever_EdgeEffort () inline
Destructor.
Definition at line 155 of file NLBuilder.h.
References addEdgeWeight().
Member Function Documentation
addEdgeWeight()
void NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight (const std::string & id, double val, double beg, double end) const virtual
Adds an effort for a given edge and time period.
Parameters
[in] id The id of the object to add a weight for
[in] val The effort
[in] beg The begin of the interval the weight is valid for
[in] end The end of the interval the weight is valid for
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever::addEdgeWeight
Implements SAXWeightsHandler::EdgeFloatTimeLineRetriever.
Definition at line 82 of file NLBuilder.cpp.
References MSEdgeWeightsStorage::addEffort(), MSEdge::dictionary(), MSNet::getWeightsStorage(), myNet, and WRITE_ERROR.
Referenced by ~EdgeFloatTimeLineRetriever_EdgeEffort(), and NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::~EdgeFloatTimeLineRetriever_EdgeTravelTime().
Field Documentation
myNet
MSNet& NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::myNet private
The network edges shall be obtained from.
Definition at line 170 of file NLBuilder.h.
Referenced by addEdgeWeight(), and NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight().
The documentation for this class was generated from the following files:
NLBuilder.h
NLBuilder.cpp