SUMO - Simulation of Urban MObility: GNEDialog_Wizard::InputBool Class Reference
GNEDialog_Wizard::InputBool Class Reference
#include <GNEDialog_Wizard.h>
Public Member Functions
InputBool (FXComposite *parent, const std::string &name)
FOX-declaration.
long onCmdSetOption (FXObject *, FXSelector, void *)
try to set new attribute value
Protected Member Functions
InputBool ()
FOX needs this.
Private Attributes
FXMenuCheck * myCheck
menu check
std::string myName
name
Detailed Description
Definition at line 82 of file GNEDialog_Wizard.h.
Constructor & Destructor Documentation
InputBool() [1/2]
GNEDialog_Wizard::InputBool::InputBool (FXComposite * parent, const std::string & name)
FOX-declaration.
constructor
Definition at line 125 of file GNEDialog_Wizard.cpp.
References OptionsCont::getBool(), OptionsCont::getOptions(), MID_GNE_SET_ATTRIBUTE, and myCheck.
InputBool() [2/2]
GNEDialog_Wizard::InputBool::InputBool () inline protected
FOX needs this.
Definition at line 95 of file GNEDialog_Wizard.h.
Member Function Documentation
onCmdSetOption()
long GNEDialog_Wizard::InputBool::onCmdSetOption (FXObject * , FXSelector , void *)
try to set new attribute value
Definition at line 136 of file GNEDialog_Wizard.cpp.
References OptionsCont::getOptions(), myCheck, myName, OptionsCont::resetWritable(), and OptionsCont::set().
Field Documentation
myCheck
FXMenuCheck* GNEDialog_Wizard::InputBool::myCheck private
menu check
Definition at line 101 of file GNEDialog_Wizard.h.
Referenced by InputBool(), and onCmdSetOption().
myName
std::string GNEDialog_Wizard::InputBool::myName private
name
Definition at line 99 of file GNEDialog_Wizard.h.
Referenced by onCmdSetOption().
The documentation for this class was generated from the following files:
GNEDialog_Wizard.h
GNEDialog_Wizard.cpp