SUMO - Simulation of Urban MObility: TraCIServer Class Reference
TraCIServer Class Reference
TraCI server used to control sumo by a remote TraCI client.
#include <TraCIServer.h>
Data Structures
struct SocketInfo
class Subscription
Representation of a subscription.
Public Types
typedef bool(* CmdExecutor) (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Definition of a method to be called for serving an associated commandID.
Public Member Functions
void cleanup ()
clean up subscriptions
void collectObjectsInRange (int domain, const PositionVector &shape, double range, std::set< std::string > &into)
std::vector< std::string > & getLoadArgs ()
SUMOTime getTargetTime () const
const std::map< MSNet::VehicleState, std::vector< std::string > > & getVehicleStateChanges () const
bool isEmbedded () const
void processCommandsUntilSimStep (SUMOTime step)
process all commands until the next SUMO simulation step. It is guaranteed that t->getTargetTime() >= myStep after call (except the case that a load or close command is received)s
void setTargetTime (SUMOTime targetTime)
Sets myTargetTime on server and sockets to the given value.
void vehicleStateChanged (const SUMOVehicle *const vehicle, MSNet::VehicleState to)
Called if a vehicle changes its state.
void writeResponseWithLength (tcpip::Storage &outputStorage, tcpip::Storage &tempMsg)
Writing Status Messages
void writeStatusCmd (int commandId, int status, const std::string &description, tcpip::Storage &outputStorage)
Writes a status command to the given storage.
void writeStatusCmd (int commandId, int status, const std::string &description)
Writes a status command to myOutputStorage.
bool writeErrorStatusCmd (int commandId, const std::string &description, tcpip::Storage &outputStorage)
Writes a status command to the given storage with status = RTYPE_ERR.
Helpers for reading and checking values
bool readTypeCheckingInt (tcpip::Storage &inputStorage, int &into)
Reads the value type and an int, verifying the type.
bool readTypeCheckingDouble (tcpip::Storage &inputStorage, double &into)
Reads the value type and a double, verifying the type.
bool readTypeCheckingString (tcpip::Storage &inputStorage, std::string &into)
Reads the value type and a string, verifying the type.
bool readTypeCheckingStringList (tcpip::Storage &inputStorage, std::vector< std::string > &into)
Reads the value type and a string list, verifying the type.
bool readTypeCheckingColor (tcpip::Storage &inputStorage, libsumo::TraCIColor &into)
Reads the value type and a color, verifying the type.
bool readTypeCheckingPosition2D (tcpip::Storage &inputStorage, libsumo::TraCIPosition &into)
Reads the value type and a 2D position, verifying the type.
bool readTypeCheckingBoundary (tcpip::Storage &inputStorage, Boundary &into)
Reads the value type and a 2D bounding box, verifying the type.
bool readTypeCheckingByte (tcpip::Storage &inputStorage, int &into)
Reads the value type and a byte, verifying the type.
bool readTypeCheckingUnsignedByte (tcpip::Storage &inputStorage, int &into)
Reads the value type and an unsigned byte, verifying the type.
bool readTypeCheckingPolygon (tcpip::Storage &inputStorage, PositionVector &into)
Reads the value type and a polygon, verifying the type.
Static Public Member Functions
static TraCIServer * getInstance ()
Initialisation and Shutdown
static void openSocket (const std::map< int, CmdExecutor > &execs)
Initialises the server.
static void close ()
request termination of connection
static bool wasClosed ()
check whether close was requested
Private Member Functions
bool addObjectVariableSubscription (const int commandId, const bool hasContext)
void checkClientOrdering ()
Called once after connection of all clients for executing SET_ORDER (and possibly prior GET_VERSION) commands, that should be executed before simulation starts (in processCommandsUntilNextSimStep()).
int dispatchCommand ()
Handles command, writes response to myOutputStorage.
bool findObjectShape (int domain, const std::string &id, PositionVector &shape)
void initialiseSubscription (const Subscription &s)
SUMOTime nextTargetTime () const
get the minimal next target time among all clients
TraCIServer & operator= (const TraCIServer &s)
Invalidated assignment operator.
void processReorderingRequests ()
checks for and processes reordering requests (relevant for multiple clients)
bool processSingleSubscription (const TraCIServer::Subscription &s, tcpip::Storage &writeInto, std::string &errors)
int readCommandID (int &commandStart, int &commandLength)
Reads the next command ID from the input storage.
std::map< int, SocketInfo * >::iterator removeCurrentSocket ()
removes myCurrentSocket from mySockets and returns an iterator pointing to the next member according to the ordering
void removeSubscription (int commandId, const std::string &identity, int domain)
void sendOutputToAll () const
send out subscription results (actually just the content of myOutputStorage) to clients which will act in this step (i.e. with client target time <= myTargetTime)
void sendSingleSimStepResponse ()
sends an empty response to a simstep command to the current client. (This applies to a situation where the TraCI step frequency is higher than the SUMO step frequency)
TraCIServer (const SUMOTime begin, const int port, const int numClients)
Constructor.
virtual ~TraCIServer ()
Destructor.
Server-internal command handling
bool commandGetVersion ()
Returns the TraCI-version.
void postProcessSimulationStep ()
Handles subscriptions to send after a simstep2 command.
Private Attributes
const bool myAmEmbedded
Whether the server runs in embedded mode.
std::map< int, SocketInfo * >::iterator myCurrentSocket
The currently active client socket.
std::map< int, CmdExecutor > myExecutors
Map of commandIds -> their executors; applicable if the executor applies to the method footprint.
tcpip::Storage myInputStorage
The storage to read from.
std::vector< std::string > myLoadArgs
tcpip::Storage myOutputStorage
The storage to writeto.
std::map< int, int > myParameterSizes
Map of variable ids to the size of the parameter in bytes.
tcpip::Socket * myServerSocket
The server socket.
std::map< int, SocketInfo * > mySocketReorderRequests
This stores the setOrder(int) requests of the clients.
std::map< int, SocketInfo * > mySockets
The socket connections to the clients the first component (index) determines the client's order (lowest index's commands are processed first),.
tcpip::Storage mySubscriptionCache
The last timestep's subscription results.
std::vector< Subscription > mySubscriptions
The list of known, still valid subscriptions.
SUMOTime myTargetTime
The time step to reach until processing the next commands.
std::map< MSNet::VehicleState, std::vector< std::string > > myVehicleStateChanges
Changes in the states of simulated vehicles.
Static Private Attributes
static bool myDoCloseConnection = false
Whether the connection was set to be to close.
static TraCIServer * myInstance = 0
Singleton instance of the server.
Detailed Description
TraCI server used to control sumo by a remote TraCI client.
Definition at line 69 of file TraCIServer.h.
Member Typedef Documentation
CmdExecutor
typedef bool(* TraCIServer::CmdExecutor) (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Definition of a method to be called for serving an associated commandID.
Definition at line 72 of file TraCIServer.h.
Constructor & Destructor Documentation
TraCIServer()
TraCIServer::TraCIServer (const SUMOTime begin, const int port, const int numClients) private
Constructor.
Parameters
[in] port The port to listen to (to open)
Definition at line 110 of file TraCIServer.cpp.
References tcpip::Socket::accept(), checkClientOrdering(), CMD_GET_EDGE_VARIABLE, CMD_GET_INDUCTIONLOOP_VARIABLE, CMD_GET_JUNCTION_VARIABLE, CMD_GET_LANE_VARIABLE, CMD_GET_LANEAREA_VARIABLE, CMD_GET_MULTIENTRYEXIT_VARIABLE, CMD_GET_PERSON_VARIABLE, CMD_GET_POI_VARIABLE, CMD_GET_POLYGON_VARIABLE, CMD_GET_ROUTE_VARIABLE, CMD_GET_SIM_VARIABLE, CMD_GET_TL_VARIABLE, CMD_GET_VEHICLE_VARIABLE, CMD_GET_VEHICLETYPE_VARIABLE, CMD_SET_EDGE_VARIABLE, CMD_SET_LANE_VARIABLE, CMD_SET_PERSON_VARIABLE, CMD_SET_POI_VARIABLE, CMD_SET_POLYGON_VARIABLE, CMD_SET_ROUTE_VARIABLE, CMD_SET_SIM_VARIABLE, CMD_SET_TL_VARIABLE, CMD_SET_VEHICLE_VARIABLE, CMD_SET_VEHICLETYPE_VARIABLE, MsgHandler::getWarningInstance(), MSGlobals::gUsingInternalLanes, MsgHandler::inform(), MAX_ORDER, myAmEmbedded, myCurrentSocket, myDoCloseConnection, myExecutors, myParameterSizes, myServerSocket, mySockets, myVehicleStateChanges, TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServerAPI_VehicleType::processSet(), toString(), VAR_LEADER, MSNet::VEHICLE_STATE_ARRIVED, MSNet::VEHICLE_STATE_BUILT, MSNet::VEHICLE_STATE_DEPARTED, MSNet::VEHICLE_STATE_ENDING_PARKING, MSNet::VEHICLE_STATE_ENDING_STOP, MSNet::VEHICLE_STATE_ENDING_TELEPORT, MSNet::VEHICLE_STATE_NEWROUTE, MSNet::VEHICLE_STATE_STARTING_PARKING, MSNet::VEHICLE_STATE_STARTING_STOP, MSNet::VEHICLE_STATE_STARTING_TELEPORT, tcpip::SocketException::what(), WRITE_MESSAGE, and WRITE_WARNING.
Referenced by getLoadArgs(), and openSocket().
~TraCIServer()
TraCIServer::~TraCIServer () private virtual
Destructor.
Definition at line 196 of file TraCIServer.cpp.
References cleanup(), myCurrentSocket, myServerSocket, and mySockets.
Referenced by getLoadArgs().
Member Function Documentation
addObjectVariableSubscription()
bool TraCIServer::addObjectVariableSubscription (const int commandId, const bool hasContext) private
Definition at line 1229 of file TraCIServer.cpp.
References initialiseSubscription(), myInputStorage, myParameterSizes, tcpip::Storage::readChar(), tcpip::Storage::readDouble(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and removeSubscription().
Referenced by dispatchCommand().
checkClientOrdering()
void TraCIServer::checkClientOrdering () private
Called once after connection of all clients for executing SET_ORDER (and possibly prior GET_VERSION) commands, that should be executed before simulation starts (in processCommandsUntilNextSimStep()).
Definition at line 260 of file TraCIServer.cpp.
References CMD_GETVERSION, CMD_SETORDER, dispatchCommand(), myCurrentSocket, myInputStorage, myOutputStorage, mySockets, readCommandID(), tcpip::Storage::reset(), tcpip::Storage::writeStorage(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer().
cleanup()
void TraCIServer::cleanup ()
clean up subscriptions
Definition at line 574 of file TraCIServer.cpp.
References tcpip::Storage::begin(), dispatchCommand(), tcpip::Storage::end(), FileHelpers::getFilePath(), OptionsCont::getOptions(), myCurrentSocket, myInputStorage, myInstance, myOutputStorage, mySockets, mySubscriptionCache, mySubscriptions, myTargetTime, myVehicleStateChanges, tcpip::Storage::reset(), string2time(), tcpip::SocketException::what(), and tcpip::Storage::writeChar().
Referenced by MSNet::clearAll(), getInstance(), and ~TraCIServer().
close()
void TraCIServer::close () static
request termination of connection
Definition at line 228 of file TraCIServer.cpp.
References myDoCloseConnection, and myInstance.
Referenced by getInstance(), and main().
collectObjectsInRange()
void TraCIServer::collectObjectsInRange (int domain, const PositionVector & shape, double range, std::set< std::string > & into)
Referenced by getVehicleStateChanges().
commandGetVersion()
bool TraCIServer::commandGetVersion () private
Returns the TraCI-version.
Returns
Always true
Definition at line 870 of file TraCIServer.cpp.
References CMD_GETVERSION, myOutputStorage, RTYPE_OK, tcpip::Storage::size(), TRACI_VERSION, VERSION_STRING, tcpip::Storage::writeInt(), writeStatusCmd(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by dispatchCommand().
dispatchCommand()
int TraCIServer::dispatchCommand () private
Handles command, writes response to myOutputStorage.
Definition at line 714 of file TraCIServer.cpp.
References addObjectVariableSubscription(), CMD_CLOSE, CMD_GETVERSION, CMD_LOAD, CMD_SETORDER, CMD_SIMSTEP, CMD_SUBSCRIBE_EDGE_CONTEXT, CMD_SUBSCRIBE_EDGE_VARIABLE, CMD_SUBSCRIBE_GUI_CONTEXT, CMD_SUBSCRIBE_GUI_VARIABLE, CMD_SUBSCRIBE_INDUCTIONLOOP_CONTEXT, CMD_SUBSCRIBE_INDUCTIONLOOP_VARIABLE, CMD_SUBSCRIBE_JUNCTION_CONTEXT, CMD_SUBSCRIBE_JUNCTION_VARIABLE, CMD_SUBSCRIBE_LANE_CONTEXT, CMD_SUBSCRIBE_LANE_VARIABLE, CMD_SUBSCRIBE_LANEAREA_CONTEXT, CMD_SUBSCRIBE_LANEAREA_VARIABLE, CMD_SUBSCRIBE_MULTIENTRYEXIT_CONTEXT, CMD_SUBSCRIBE_MULTIENTRYEXIT_VARIABLE, CMD_SUBSCRIBE_PERSON_CONTEXT, CMD_SUBSCRIBE_PERSON_VARIABLE, CMD_SUBSCRIBE_POI_CONTEXT, CMD_SUBSCRIBE_POI_VARIABLE, CMD_SUBSCRIBE_POLYGON_CONTEXT, CMD_SUBSCRIBE_POLYGON_VARIABLE, CMD_SUBSCRIBE_ROUTE_CONTEXT, CMD_SUBSCRIBE_ROUTE_VARIABLE, CMD_SUBSCRIBE_SIM_CONTEXT, CMD_SUBSCRIBE_SIM_VARIABLE, CMD_SUBSCRIBE_TL_CONTEXT, CMD_SUBSCRIBE_TL_VARIABLE, CMD_SUBSCRIBE_VEHICLE_CONTEXT, CMD_SUBSCRIBE_VEHICLE_VARIABLE, CMD_SUBSCRIBE_VEHICLETYPE_CONTEXT, CMD_SUBSCRIBE_VEHICLETYPE_VARIABLE, commandGetVersion(), DELTA_T, MSNet::getCurrentTimeStep(), MSNet::getInstance(), MAX_ORDER, myAmEmbedded, myCurrentSocket, myDoCloseConnection, myExecutors, myInputStorage, myLoadArgs, myOutputStorage, mySocketReorderRequests, mySockets, myTargetTime, myVehicleStateChanges, tcpip::Storage::position(), postProcessSimulationStep(), tcpip::Storage::readChar(), readCommandID(), tcpip::Storage::readInt(), readTypeCheckingStringList(), tcpip::Storage::reset(), RTYPE_ERR, RTYPE_NOTIMPLEMENTED, RTYPE_OK, sendSingleSimStepResponse(), MSNet::simulationStep(), toString(), tcpip::Storage::valid_pos(), writeErrorStatusCmd(), and writeStatusCmd().
Referenced by checkClientOrdering(), cleanup(), and processCommandsUntilSimStep().
findObjectShape()
bool TraCIServer::findObjectShape (int domain, const std::string & id, PositionVector & shape) private
Definition at line 1066 of file TraCIServer.cpp.
References CMD_SUBSCRIBE_EDGE_CONTEXT, CMD_SUBSCRIBE_GUI_CONTEXT, CMD_SUBSCRIBE_INDUCTIONLOOP_CONTEXT, CMD_SUBSCRIBE_JUNCTION_CONTEXT, CMD_SUBSCRIBE_LANE_CONTEXT, CMD_SUBSCRIBE_MULTIENTRYEXIT_CONTEXT, CMD_SUBSCRIBE_PERSON_CONTEXT, CMD_SUBSCRIBE_POI_CONTEXT, CMD_SUBSCRIBE_POLYGON_CONTEXT, CMD_SUBSCRIBE_ROUTE_CONTEXT, CMD_SUBSCRIBE_SIM_CONTEXT, CMD_SUBSCRIBE_TL_CONTEXT, CMD_SUBSCRIBE_VEHICLE_CONTEXT, CMD_SUBSCRIBE_VEHICLETYPE_CONTEXT, TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_Junction::getPosition(), TraCIServerAPI_POI::getPosition(), TraCIServerAPI_Vehicle::getPosition(), TraCIServerAPI_Person::getPosition(), TraCIServerAPI_Edge::getShape(), TraCIServerAPI_Polygon::getShape(), and TraCIServerAPI_Lane::getShape().
Referenced by processSingleSubscription().
getInstance()
static TraCIServer* TraCIServer::getInstance (void) inline static
Definition at line 81 of file TraCIServer.h.
References cleanup(), close(), myInstance, openSocket(), processCommandsUntilSimStep(), vehicleStateChanged(), wasClosed(), writeErrorStatusCmd(), and writeStatusCmd().
Referenced by NLBuilder::build(), MSNet::clearAll(), GUIRunThread::makeStep(), MSNet::postSimStepOutput(), MSNet::simulate(), MSNet::simulationState(), and MSNet::simulationStep().
getLoadArgs()
std::vector<std::string>& TraCIServer::getLoadArgs () inline
Definition at line 269 of file TraCIServer.h.
References myLoadArgs, TraCIServer(), and ~TraCIServer().
Referenced by GUIRunThread::makeStep(), and MSNet::simulate().
getTargetTime()
SUMOTime TraCIServer::getTargetTime () const inline
Definition at line 75 of file TraCIServer.h.
References myTargetTime.
Referenced by MSNet::simulationStep().
getVehicleStateChanges()
const std::map<MSNet::VehicleState, std::vector<std::string> >& TraCIServer::getVehicleStateChanges () const inline
Definition at line 154 of file TraCIServer.h.
References collectObjectsInRange(), myAmEmbedded, myCurrentSocket, mySockets, myVehicleStateChanges, readTypeCheckingBoundary(), readTypeCheckingByte(), readTypeCheckingColor(), readTypeCheckingDouble(), readTypeCheckingInt(), readTypeCheckingPolygon(), readTypeCheckingPosition2D(), readTypeCheckingString(), readTypeCheckingStringList(), readTypeCheckingUnsignedByte(), setTargetTime(), and writeResponseWithLength().
Referenced by TraCIServerAPI_Simulation::writeVehicleStateIDs(), and TraCIServerAPI_Simulation::writeVehicleStateNumber().
initialiseSubscription()
void TraCIServer::initialiseSubscription (const Subscription & s) private
Definition at line 996 of file TraCIServer.cpp.
References TraCIServer::Subscription::beginTime, TraCIServer::Subscription::commandId, TraCIServer::Subscription::contextDomain, TraCIServer::Subscription::contextVars, TraCIServer::Subscription::endTime, MSNet::getCurrentTimeStep(), MSNet::getInstance(), TraCIServer::Subscription::id, myOutputStorage, mySubscriptionCache, mySubscriptions, TraCIServer::Subscription::parameters, processSingleSubscription(), TraCIServer::Subscription::range, tcpip::Storage::readByte(), tcpip::Storage::readInt(), tcpip::Storage::reset(), RTYPE_ERR, RTYPE_OK, tcpip::Storage::size(), tcpip::Storage::valid_pos(), TraCIServer::Subscription::variables, tcpip::Storage::writeByte(), tcpip::Storage::writeInt(), writeStatusCmd(), and tcpip::Storage::writeStorage().
Referenced by addObjectVariableSubscription().
isEmbedded()
bool TraCIServer::isEmbedded () const inline
Definition at line 78 of file TraCIServer.h.
References myAmEmbedded.
Referenced by MSNet::simulationStep().
nextTargetTime()
SUMOTime TraCIServer::nextTargetTime () const private
get the minimal next target time among all clients
Definition at line 369 of file TraCIServer.cpp.
References MIN2(), and mySockets.
Referenced by processCommandsUntilSimStep().
openSocket()
void TraCIServer::openSocket (const std::map< int, CmdExecutor > & execs) static
Initialises the server.
Parameters
[in] execs The (additional) command executors to use
Definition at line 207 of file TraCIServer.cpp.
References MSNet::addVehicleStateListener(), MSNet::getInstance(), OptionsCont::getOptions(), myDoCloseConnection, myExecutors, myInstance, string2time(), and TraCIServer().
Referenced by getInstance(), NLBuilder::init(), and GUILoadThread::run().
operator=()
TraCIServer& TraCIServer::operator= (const TraCIServer & s) private
Invalidated assignment operator.
postProcessSimulationStep()
void TraCIServer::postProcessSimulationStep () private
Handles subscriptions to send after a simstep2 command.
Definition at line 889 of file TraCIServer.cpp.
References TraCIServer::Subscription::beginTime, CMD_SIMSTEP, CMD_SUBSCRIBE_PERSON_CONTEXT, CMD_SUBSCRIBE_PERSON_VARIABLE, CMD_SUBSCRIBE_VEHICLE_CONTEXT, CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIServer::Subscription::commandId, TraCIServer::Subscription::endTime, MSTransportableControl::get(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSNet::getPersonControl(), TraCIServer::Subscription::id, myOutputStorage, mySubscriptionCache, mySubscriptions, myVehicleStateChanges, processSingleSubscription(), tcpip::Storage::reset(), RTYPE_OK, tcpip::Storage::size(), MSNet::VEHICLE_STATE_ARRIVED, tcpip::Storage::writeInt(), writeStatusCmd(), and tcpip::Storage::writeStorage().
Referenced by dispatchCommand(), and processCommandsUntilSimStep().
processCommandsUntilSimStep()
void TraCIServer::processCommandsUntilSimStep (SUMOTime step)
process all commands until the next SUMO simulation step. It is guaranteed that t->getTargetTime() >= myStep after call (except the case that a load or close command is received)s
Definition at line 415 of file TraCIServer.cpp.
References CMD_CLOSE, CMD_LOAD, CMD_SIMSTEP, dispatchCommand(), MSNet::getInstance(), myAmEmbedded, myCurrentSocket, myDoCloseConnection, myInputStorage, myLoadArgs, myOutputStorage, mySockets, myTargetTime, myVehicleStateChanges, nextTargetTime(), postProcessSimulationStep(), processReorderingRequests(), removeCurrentSocket(), tcpip::Storage::reset(), sendOutputToAll(), SIMTIME, tcpip::Storage::size(), tcpip::Storage::valid_pos(), and tcpip::SocketException::what().
Referenced by getInstance(), and MSNet::simulationStep().
processReorderingRequests()
void TraCIServer::processReorderingRequests () private
checks for and processes reordering requests (relevant for multiple clients)
Definition at line 325 of file TraCIServer.cpp.
References mySocketReorderRequests, mySockets, and SIMTIME.
Referenced by processCommandsUntilSimStep().
processSingleSubscription()
bool TraCIServer::processSingleSubscription (const TraCIServer::Subscription & s, tcpip::Storage & writeInto, std::string & errors) private
Definition at line 1133 of file TraCIServer.cpp.
References libsumo::Helper::collectObjectsInRange(), TraCIServer::Subscription::commandId, TraCIServer::Subscription::contextDomain, TraCIServer::Subscription::contextVars, findObjectShape(), TraCIServer::Subscription::id, ID_LIST, myExecutors, TraCIServer::Subscription::parameters, TraCIServer::Subscription::range, tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RTYPE_ERR, RTYPE_NOTIMPLEMENTED, RTYPE_OK, tcpip::Storage::size(), TYPE_STRING, TraCIServer::Subscription::variables, tcpip::Storage::writeInt(), tcpip::Storage::writePacket(), writeStatusCmd(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by initialiseSubscription(), and postProcessSimulationStep().
readCommandID()
int TraCIServer::readCommandID (int & commandStart, int & commandLength) private
Reads the next command ID from the input storage.
Returns
the command ID
Parameters
[out] the version with reference parameters provides information on the command start position and length used in dispatchCommand for checking purposes
Definition at line 703 of file TraCIServer.cpp.
References myInputStorage, tcpip::Storage::position(), tcpip::Storage::readInt(), and tcpip::Storage::readUnsignedByte().
Referenced by checkClientOrdering(), and dispatchCommand().
readTypeCheckingBoundary()
bool TraCIServer::readTypeCheckingBoundary (tcpip::Storage & inputStorage, Boundary & into)
Reads the value type and a 2D bounding box, verifying the type.
Parameters
Definition at line 1336 of file TraCIServer.cpp.
References tcpip::Storage::readDouble(), tcpip::Storage::readUnsignedByte(), Boundary::set(), and TYPE_BOUNDINGBOX.
Referenced by getVehicleStateChanges(), and TraCIServerAPI_GUI::processSet().
readTypeCheckingByte()
bool TraCIServer::readTypeCheckingByte (tcpip::Storage & inputStorage, int & into)
Reads the value type and a byte, verifying the type.
Parameters
Definition at line 1350 of file TraCIServer.cpp.
References tcpip::Storage::readByte(), tcpip::Storage::readUnsignedByte(), and TYPE_BYTE.
Referenced by getVehicleStateChanges(), TraCIServerAPI_Vehicle::processSet(), and TraCIServerAPI_Person::processSet().
readTypeCheckingColor()
bool TraCIServer::readTypeCheckingColor (tcpip::Storage & inputStorage, libsumo::TraCIColor & into)
Reads the value type and a color, verifying the type.
Parameters
Definition at line 1311 of file TraCIServer.cpp.
References libsumo::TraCIColor::a, libsumo::TraCIColor::b, libsumo::TraCIColor::g, libsumo::TraCIColor::r, tcpip::Storage::readUnsignedByte(), and TYPE_COLOR.
Referenced by getVehicleStateChanges(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServerAPI_VehicleType::setVariable().
readTypeCheckingDouble()
bool TraCIServer::readTypeCheckingDouble (tcpip::Storage & inputStorage, double & into)
Reads the value type and a double, verifying the type.
Parameters
Definition at line 1281 of file TraCIServer.cpp.
References tcpip::Storage::readDouble(), tcpip::Storage::readUnsignedByte(), and TYPE_DOUBLE.
Referenced by getVehicleStateChanges(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), and TraCIServerAPI_VehicleType::setVariable().
readTypeCheckingInt()
bool TraCIServer::readTypeCheckingInt (tcpip::Storage & inputStorage, int & into)
Reads the value type and an int, verifying the type.
Parameters
Definition at line 1271 of file TraCIServer.cpp.
References tcpip::Storage::readInt(), tcpip::Storage::readUnsignedByte(), and TYPE_INTEGER.
Referenced by getVehicleStateChanges(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServerAPI_Person::processSet().
readTypeCheckingPolygon()
bool TraCIServer::readTypeCheckingPolygon (tcpip::Storage & inputStorage, PositionVector & into)
Reads the value type and a polygon, verifying the type.
Parameters
Definition at line 1370 of file TraCIServer.cpp.
References tcpip::Storage::readDouble(), tcpip::Storage::readUnsignedByte(), and TYPE_POLYGON.
Referenced by getVehicleStateChanges(), and TraCIServerAPI_Polygon::processSet().
readTypeCheckingPosition2D()
bool TraCIServer::readTypeCheckingPosition2D (tcpip::Storage & inputStorage, libsumo::TraCIPosition & into)
Reads the value type and a 2D position, verifying the type.
Parameters
Definition at line 1324 of file TraCIServer.cpp.
References POSITION_2D, tcpip::Storage::readDouble(), tcpip::Storage::readUnsignedByte(), libsumo::TraCIPosition::x, libsumo::TraCIPosition::y, and libsumo::TraCIPosition::z.
Referenced by getVehicleStateChanges(), TraCIServerAPI_POI::processSet(), and TraCIServerAPI_GUI::processSet().
readTypeCheckingString()
bool TraCIServer::readTypeCheckingString (tcpip::Storage & inputStorage, std::string & into)
Reads the value type and a string, verifying the type.
Parameters
Definition at line 1291 of file TraCIServer.cpp.
References tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and TYPE_STRING.
Referenced by getVehicleStateChanges(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), and TraCIServerAPI_VehicleType::setVariable().
readTypeCheckingStringList()
bool TraCIServer::readTypeCheckingStringList (tcpip::Storage & inputStorage, std::vector< std::string > & into)
Reads the value type and a string list, verifying the type.
Parameters
Definition at line 1301 of file TraCIServer.cpp.
References tcpip::Storage::readStringList(), tcpip::Storage::readUnsignedByte(), and TYPE_STRINGLIST.
Referenced by dispatchCommand(), getVehicleStateChanges(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Person::processSet(), and TraCIServerAPI_Lane::processSet().
readTypeCheckingUnsignedByte()
bool TraCIServer::readTypeCheckingUnsignedByte (tcpip::Storage & inputStorage, int & into)
Reads the value type and an unsigned byte, verifying the type.
Parameters
Definition at line 1360 of file TraCIServer.cpp.
References tcpip::Storage::readUnsignedByte(), and TYPE_UBYTE.
Referenced by TraCIServerAPI_Simulation::commandPositionConversion(), getVehicleStateChanges(), and TraCIServerAPI_Polygon::processSet().
removeCurrentSocket()
std::map< int, TraCIServer::SocketInfo * >::iterator TraCIServer::removeCurrentSocket () private
removes myCurrentSocket from mySockets and returns an iterator pointing to the next member according to the ordering
Definition at line 673 of file TraCIServer.cpp.
References myCurrentSocket, and mySockets.
Referenced by processCommandsUntilSimStep().
removeSubscription()
void TraCIServer::removeSubscription (int commandId, const std::string & identity, int domain) private
Definition at line 1046 of file TraCIServer.cpp.
References mySubscriptions, RTYPE_OK, and writeStatusCmd().
Referenced by addObjectVariableSubscription().
sendOutputToAll()
void TraCIServer::sendOutputToAll () const private
send out subscription results (actually just the content of myOutputStorage) to clients which will act in this step (i.e. with client target time <= myTargetTime)
Definition at line 393 of file TraCIServer.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), myOutputStorage, and mySockets.
Referenced by processCommandsUntilSimStep().
sendSingleSimStepResponse()
void TraCIServer::sendSingleSimStepResponse () private
sends an empty response to a simstep command to the current client. (This applies to a situation where the TraCI step frequency is higher than the SUMO step frequency)
Definition at line 948 of file TraCIServer.cpp.
References CMD_SIMSTEP, myCurrentSocket, myOutputStorage, mySubscriptionCache, tcpip::Storage::reset(), RTYPE_OK, tcpip::Storage::size(), writeStatusCmd(), and tcpip::Storage::writeStorage().
Referenced by dispatchCommand().
setTargetTime()
void TraCIServer::setTargetTime (SUMOTime targetTime)
Sets myTargetTime on server and sockets to the given value.
Note
Used in MSStateHandler to update the server's time after loading a state
Definition at line 1386 of file TraCIServer.cpp.
References mySockets, and myTargetTime.
Referenced by NLBuilder::build(), and getVehicleStateChanges().
vehicleStateChanged()
void TraCIServer::vehicleStateChanged (const SUMOVehicle *const vehicle, MSNet::VehicleState to) virtual
Called if a vehicle changes its state.
Parameters
[in] vehicle The vehicle which changed its state
[in] to The state the vehicle has changed to
Implements MSNet::VehicleStateListener.
Definition at line 248 of file TraCIServer.cpp.
References SUMOVehicle::getID(), myAmEmbedded, myDoCloseConnection, mySockets, and myVehicleStateChanges.
Referenced by getInstance().
wasClosed()
bool TraCIServer::wasClosed () static
check whether close was requested
Returns
Whether the connection was closed
Definition at line 239 of file TraCIServer.cpp.
References myDoCloseConnection.
Referenced by getInstance(), GUIRunThread::makeStep(), MSNet::simulate(), MSNet::simulationState(), and MSNet::simulationStep().
writeErrorStatusCmd()
bool TraCIServer::writeErrorStatusCmd (int commandId, const std::string & description, tcpip::Storage & outputStorage)
Writes a status command to the given storage with status = RTYPE_ERR.
Parameters
[in] commandId The id of the command to respond to
[in] description The status description (error message, for example)
Definition at line 989 of file TraCIServer.cpp.
References RTYPE_ERR, and writeStatusCmd().
Referenced by dispatchCommand(), getInstance(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServerAPI_VehicleType::processSet(), and TraCIServerAPI_VehicleType::setVariable().
writeResponseWithLength()
void TraCIServer::writeResponseWithLength (tcpip::Storage & outputStorage, tcpip::Storage & tempMsg)
Definition at line 1259 of file TraCIServer.cpp.
References tcpip::Storage::size(), tcpip::Storage::writeInt(), tcpip::Storage::writeStorage(), and tcpip::Storage::writeUnsignedByte().
Referenced by getVehicleStateChanges(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), and TraCIServerAPI_Junction::processGet().
writeStatusCmd() [1/2]
void TraCIServer::writeStatusCmd (int commandId, int status, const std::string & description, tcpip::Storage & outputStorage)
Writes a status command to the given storage.
Parameters
[in] commandId The id of the command to respond to
[in] status The status to send
[in] description The status description (error message, for example)
Definition at line 975 of file TraCIServer.cpp.
References RTYPE_ERR, RTYPE_NOTIMPLEMENTED, toHex(), WRITE_ERROR, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), commandGetVersion(), TraCIServerAPI_Simulation::commandPositionConversion(), dispatchCommand(), getInstance(), initialiseSubscription(), postProcessSimulationStep(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TrafficLight::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_MultiEntryExit::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_LaneArea::processGet(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TrafficLight::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), TraCIServerAPI_Simulation::processSet(), TraCIServerAPI_Person::processSet(), TraCIServerAPI_Lane::processSet(), TraCIServerAPI_VehicleType::processSet(), processSingleSubscription(), removeSubscription(), sendSingleSimStepResponse(), writeErrorStatusCmd(), and writeStatusCmd().
writeStatusCmd() [2/2]
void TraCIServer::writeStatusCmd (int commandId, int status, const std::string & description)
Writes a status command to myOutputStorage.
Parameters
[in] commandId The id of the command to respond to
[in] status The status to send
[in] description The status description (error message, for example)
Definition at line 969 of file TraCIServer.cpp.
References myOutputStorage, and writeStatusCmd().
Field Documentation
myAmEmbedded
const bool TraCIServer::myAmEmbedded private
Whether the server runs in embedded mode.
Definition at line 381 of file TraCIServer.h.
Referenced by dispatchCommand(), getVehicleStateChanges(), isEmbedded(), processCommandsUntilSimStep(), TraCIServer(), and vehicleStateChanged().
myCurrentSocket
std::map<int, SocketInfo*>::iterator TraCIServer::myCurrentSocket private
The currently active client socket.
Definition at line 366 of file TraCIServer.h.
Referenced by checkClientOrdering(), cleanup(), dispatchCommand(), getVehicleStateChanges(), processCommandsUntilSimStep(), removeCurrentSocket(), sendSingleSimStepResponse(), TraCIServer(), and ~TraCIServer().
myDoCloseConnection
bool TraCIServer::myDoCloseConnection = false static private
Whether the connection was set to be to close.
Definition at line 353 of file TraCIServer.h.
Referenced by close(), dispatchCommand(), openSocket(), processCommandsUntilSimStep(), TraCIServer(), vehicleStateChanged(), and wasClosed().
myExecutors
std::map<int, CmdExecutor> TraCIServer::myExecutors private
Map of commandIds -> their executors; applicable if the executor applies to the method footprint.
Definition at line 384 of file TraCIServer.h.
Referenced by dispatchCommand(), openSocket(), processSingleSubscription(), and TraCIServer().
myInputStorage
tcpip::Storage TraCIServer::myInputStorage private
The storage to read from.
Definition at line 372 of file TraCIServer.h.
Referenced by addObjectVariableSubscription(), checkClientOrdering(), cleanup(), dispatchCommand(), processCommandsUntilSimStep(), and readCommandID().
myInstance
TraCIServer * TraCIServer::myInstance = 0 static private
Singleton instance of the server.
Definition at line 350 of file TraCIServer.h.
Referenced by cleanup(), close(), getInstance(), and openSocket().
myLoadArgs
std::vector<std::string> TraCIServer::myLoadArgs private
Definition at line 389 of file TraCIServer.h.
Referenced by dispatchCommand(), getLoadArgs(), and processCommandsUntilSimStep().
myOutputStorage
tcpip::Storage TraCIServer::myOutputStorage private
The storage to writeto.
Definition at line 375 of file TraCIServer.h.
Referenced by checkClientOrdering(), cleanup(), commandGetVersion(), dispatchCommand(), initialiseSubscription(), postProcessSimulationStep(), processCommandsUntilSimStep(), sendOutputToAll(), sendSingleSimStepResponse(), and writeStatusCmd().
myParameterSizes
std::map<int, int> TraCIServer::myParameterSizes private
Map of variable ids to the size of the parameter in bytes.
Definition at line 387 of file TraCIServer.h.
Referenced by addObjectVariableSubscription(), and TraCIServer().
myServerSocket
tcpip::Socket* TraCIServer::myServerSocket private
The server socket.
Definition at line 356 of file TraCIServer.h.
Referenced by TraCIServer(), and ~TraCIServer().
mySocketReorderRequests
std::map<int, SocketInfo*> TraCIServer::mySocketReorderRequests private
This stores the setOrder(int) requests of the clients.
Definition at line 363 of file TraCIServer.h.
Referenced by dispatchCommand(), and processReorderingRequests().
mySockets
std::map<int, SocketInfo*> TraCIServer::mySockets private
The socket connections to the clients the first component (index) determines the client's order (lowest index's commands are processed first),.
See also
CMD_SETORDER
Definition at line 360 of file TraCIServer.h.
Referenced by checkClientOrdering(), cleanup(), dispatchCommand(), getVehicleStateChanges(), nextTargetTime(), processCommandsUntilSimStep(), processReorderingRequests(), removeCurrentSocket(), sendOutputToAll(), setTargetTime(), TraCIServer(), vehicleStateChanged(), and ~TraCIServer().
mySubscriptionCache
tcpip::Storage TraCIServer::mySubscriptionCache private
The last timestep's subscription results.
Definition at line 378 of file TraCIServer.h.
Referenced by cleanup(), initialiseSubscription(), postProcessSimulationStep(), and sendSingleSimStepResponse().
mySubscriptions
std::vector<Subscription> TraCIServer::mySubscriptions private
The list of known, still valid subscriptions.
Definition at line 434 of file TraCIServer.h.
Referenced by cleanup(), initialiseSubscription(), postProcessSimulationStep(), and removeSubscription().
myTargetTime
SUMOTime TraCIServer::myTargetTime private
The time step to reach until processing the next commands.
Definition at line 369 of file TraCIServer.h.
Referenced by cleanup(), dispatchCommand(), getTargetTime(), processCommandsUntilSimStep(), and setTargetTime().
myVehicleStateChanges
std::map<MSNet::VehicleState, std::vector<std::string> > TraCIServer::myVehicleStateChanges private
Changes in the states of simulated vehicles.
Note
Server cache myVehicleStateChanges is used for managing last steps subscription updates and for client information in case that myAmEmbedded==true, which implies a single client. For the potential multiclient case (myAmEmbedded==false), each socket in mySockets is associated with a proper vehicleStateChanges container mySockets[...].second->vehicleStateChanges Performance could be improved if for a single client, myVehicleStateChanges is used only.
Definition at line 443 of file TraCIServer.h.
Referenced by cleanup(), dispatchCommand(), getVehicleStateChanges(), postProcessSimulationStep(), processCommandsUntilSimStep(), TraCIServer(), and vehicleStateChanged().
The documentation for this class was generated from the following files:
TraCIServer.h
TraCIServer.cpp