SUMO - Simulation of Urban MObility: NGRandomNetBuilder Class Reference
NGRandomNetBuilder Class Reference
A class that builds random network using an algorithm by Markus Hartinger.
#include <NGRandomNetBuilder.h>
Public Member Functions
void createNet (int numNodes)
Builds a NGNet using the set values.
NGRandomNetBuilder (NGNet &net, double minAngle, double minDistance, double maxDistance, double connectivity, int numTries, const RandomDistributor< int > &neighborDist)
Constructor.
Private Member Functions
bool canConnect (NGNode *baseNode, NGNode *newNode)
Checks whether connecting the given two nodes complies with the set restrictions.
bool checkAngles (NGNode *node)
Checks whether the angle of this node's connections are valid.
bool createNewNode (NGNode *baseNode)
Creates new random node.
void findPossibleOuterNodes (NGNode *node)
finds possible connections between Node and OuterNodes complying with restrictions
NGRandomNetBuilder (const NGRandomNetBuilder &)
Invalidated copy constructor.
NGRandomNetBuilder & operator= (const NGRandomNetBuilder &)
Invalidated assignment operator.
void removeOuterNode (NGNode *node)
Removes the given node from the list of outer nodes.
Private Attributes
NGNodeList myConNodes
RandomDistributor< int > myNeighbourDistribution
The distribution of number of neighbours.
NGNet & myNet
The network to fill.
int myNumNodes
Number of nodes to be created.
int myNumTries
Number of tries to create a new node.
NGEdgeList myOuterLinks
The list of outer links.
NGNodeList myOuterNodes
The list of outer nodes.
restrictions
double myMinLinkAngle
Minimum angle allowed between two links.
double myMinDistance
Minimum distance allowed between two nodes.
double myMaxDistance
Maximum distance allowed between two nodes.
double myConnectivity
Probability of connecting to a existing node if possible.
Detailed Description
A class that builds random network using an algorithm by Markus Hartinger.
Todo:
Describe the algorithm
Definition at line 48 of file NGRandomNetBuilder.h.
Constructor & Destructor Documentation
NGRandomNetBuilder() [1/2]
NGRandomNetBuilder::NGRandomNetBuilder (NGNet & net, double minAngle, double minDistance, double maxDistance, double connectivity, int numTries, const RandomDistributor< int > & neighborDist)
Constructor.
Parameters
[in] net The network to fill with generated structures
[in] minAngle The minimum allowed angle between two streets
[in] minDistance The minimum allowed distance between two nodes
[in] maxDistance The maximum allowed distance between two nodes
[in] connectivity The connectivity factor
[in] numTries ?
Todo:
check meanings of connectivity/numTries
Definition at line 46 of file NGRandomNetBuilder.cpp.
NGRandomNetBuilder() [2/2]
NGRandomNetBuilder::NGRandomNetBuilder (const NGRandomNetBuilder &) private
Invalidated copy constructor.
Member Function Documentation
canConnect()
bool NGRandomNetBuilder::canConnect (NGNode * baseNode, NGNode * newNode) private
Checks whether connecting the given two nodes complies with the set restrictions.
Checks whether the distance, the angle, and the connectivity is within the defined range when both nodes would be connected
Parameters
[in] baseNode The first node of the combination to check
[in] newNode The second node of the combination to check
Returns
Whether the settings allow to connect both nodes
Definition at line 108 of file NGRandomNetBuilder.cpp.
References checkAngles(), Position::distanceTo2D(), NGNode::getPosition(), GeomHelper::INVALID_OFFSET, PositionVector::length(), myMaxDistance, myMinDistance, myOuterLinks, GeomHelper::nearest_offset_on_line_to_point2D(), and PositionVector::positionAtOffset2D().
Referenced by createNet(), createNewNode(), and findPossibleOuterNodes().
checkAngles()
bool NGRandomNetBuilder::checkAngles (NGNode * node) private
Checks whether the angle of this node's connections are valid.
Checks whether the connections of the nodes are in common with the value of myMinLinkAngle.
Parameters
[in] node The node to check connections of
Returns
Whether the settings allow to connect both nodes
Definition at line 67 of file NGRandomNetBuilder.cpp.
References GeomHelper::angle2D(), NGNode::getPosition(), NGNode::LinkList, myMinLinkAngle, Position::x(), and Position::y().
Referenced by canConnect().
createNet()
void NGRandomNetBuilder::createNet (int numNodes)
Builds a NGNet using the set values.
Parameters
[in] numNodes Number of iterations (node insertions) to perform
Todo:
Describe the algorithm
Definition at line 209 of file NGRandomNetBuilder.cpp.
References NGNet::add(), canConnect(), createNewNode(), findPossibleOuterNodes(), NGNode::getMaxNeighbours(), NGNet::getNextFreeID(), NGNode::LinkList, myConnectivity, myConNodes, myNet, myNumNodes, myNumTries, myOuterLinks, myOuterNodes, NGNet::nodeNo(), RandHelper::rand(), removeOuterNode(), NGNode::setMaxNeighbours(), NGNode::setX(), and NGNode::setY().
Referenced by buildNetwork().
createNewNode()
bool NGRandomNetBuilder::createNewNode (NGNode * baseNode) private
Creates new random node.
Returns true, if creation was successfull.
Parameters
[in] baseNode ?
Todo:
Describe better
Definition at line 178 of file NGRandomNetBuilder.cpp.
References NGNet::add(), canConnect(), RandomDistributor< T >::get(), NGNode::getMaxNeighbours(), NGNet::getNextFreeID(), NGNode::getPosition(), NGNode::LinkList, M_PI, myMaxDistance, myMinDistance, myNeighbourDistribution, myNet, myOuterLinks, myOuterNodes, RandHelper::rand(), removeOuterNode(), NGNode::setMaxNeighbours(), NGNode::setX(), NGNode::setY(), Position::x(), and Position::y().
Referenced by createNet().
findPossibleOuterNodes()
void NGRandomNetBuilder::findPossibleOuterNodes (NGNode * node) private
finds possible connections between Node and OuterNodes complying with restrictions
Parameters
[in] node ?
Todo:
Describe better
Definition at line 160 of file NGRandomNetBuilder.cpp.
References canConnect(), NGNode::connected(), NGNode::getMaxNeighbours(), NGNode::LinkList, myConNodes, and myOuterNodes.
Referenced by createNet().
operator=()
NGRandomNetBuilder& NGRandomNetBuilder::operator= (const NGRandomNetBuilder &) private
Invalidated assignment operator.
removeOuterNode()
void NGRandomNetBuilder::removeOuterNode (NGNode * node) private
Removes the given node from the list of outer nodes.
Parameters
[in] node The node to remove
Definition at line 56 of file NGRandomNetBuilder.cpp.
References myOuterNodes.
Referenced by createNet(), and createNewNode().
Field Documentation
myConnectivity
double NGRandomNetBuilder::myConnectivity private
Probability of connecting to a existing node if possible.
Definition at line 148 of file NGRandomNetBuilder.h.
Referenced by createNet().
myConNodes
NGNodeList NGRandomNetBuilder::myConNodes private
Definition at line 132 of file NGRandomNetBuilder.h.
Referenced by createNet(), and findPossibleOuterNodes().
myMaxDistance
double NGRandomNetBuilder::myMaxDistance private
Maximum distance allowed between two nodes.
Definition at line 145 of file NGRandomNetBuilder.h.
Referenced by canConnect(), and createNewNode().
myMinDistance
double NGRandomNetBuilder::myMinDistance private
Minimum distance allowed between two nodes.
Definition at line 142 of file NGRandomNetBuilder.h.
Referenced by canConnect(), and createNewNode().
myMinLinkAngle
double NGRandomNetBuilder::myMinLinkAngle private
Minimum angle allowed between two links.
Definition at line 139 of file NGRandomNetBuilder.h.
Referenced by checkAngles().
myNeighbourDistribution
RandomDistributor<int> NGRandomNetBuilder::myNeighbourDistribution private
The distribution of number of neighbours.
Definition at line 159 of file NGRandomNetBuilder.h.
Referenced by createNewNode().
myNet
NGNet& NGRandomNetBuilder::myNet private
The network to fill.
Definition at line 123 of file NGRandomNetBuilder.h.
Referenced by createNet(), and createNewNode().
myNumNodes
int NGRandomNetBuilder::myNumNodes private
Number of nodes to be created.
Definition at line 156 of file NGRandomNetBuilder.h.
Referenced by createNet().
myNumTries
int NGRandomNetBuilder::myNumTries private
Number of tries to create a new node.
Definition at line 153 of file NGRandomNetBuilder.h.
Referenced by createNet().
myOuterLinks
NGEdgeList NGRandomNetBuilder::myOuterLinks private
The list of outer links.
Definition at line 129 of file NGRandomNetBuilder.h.
Referenced by canConnect(), createNet(), and createNewNode().
myOuterNodes
NGNodeList NGRandomNetBuilder::myOuterNodes private
The list of outer nodes.
Definition at line 126 of file NGRandomNetBuilder.h.
Referenced by createNet(), createNewNode(), findPossibleOuterNodes(), and removeOuterNode().
The documentation for this class was generated from the following files:
NGRandomNetBuilder.h
NGRandomNetBuilder.cpp