SUMO - Simulation of Urban MObility: ROJTRRouter Class Reference
ROJTRRouter Class Reference abstract
Computes routes using junction turning percentages.
#include <ROJTRRouter.h>
Public Types
typedef double(* Operation) (const ROEdge *const, const ROVehicle *const, double)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter< ROEdge, ROVehicle > * clone ()
virtual bool compute (const ROEdge *from, const ROEdge *to, const ROVehicle *const vehicle, SUMOTime msTime, std::vector< const ROEdge * > &into)=0
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
double getEffort (const ROEdge *const e, const ROVehicle *const v, double t) const
virtual double recomputeCosts (const std::vector< const ROEdge * > &edges, const ROVehicle *const v, SUMOTime msTime) const=0
ROJTRRouter (bool unbuildIsWarningOnly, bool acceptAllDestinations, int maxEdges, bool ignoreClasses, bool allowLoops)
Constructor.
void setBulkMode (const bool mode)
void startQuery ()
~ROJTRRouter ()
Destructor.
Implementatios of SUMOAbstractRouter
bool compute (const ROEdge *from, const ROEdge *to, const ROVehicle *const vehicle, SUMOTime time, ConstROEdgeVector &into)
Computes a route.
double recomputeCosts (const ConstROEdgeVector &edges, const ROVehicle *const v, SUMOTime msTime) const
Recomputes the costs of a route.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Attributes
const bool myAcceptAllDestination
Whether all edges may be used as route end.
const bool myAllowLoops
Whether a vehicle may reuse a road.
const bool myIgnoreClasses
Whether vehicle class information shall be ignored.
const int myMaxEdges
The maximum number of edges a route may have.
const bool myUnbuildIsWarningOnly
Whether unbuildable routes shall be reported as warniings, not errors.
Detailed Description
Computes routes using junction turning percentages.
Definition at line 52 of file ROJTRRouter.h.
Member Typedef Documentation
Operation
typedef double(* SUMOAbstractRouter< ROEdge , ROVehicle >::Operation) (const ROEdge *const, const ROVehicle *const, double) inherited
Type of the function that is used to retrieve the edge effort.
Definition at line 55 of file SUMOAbstractRouter.h.
Constructor & Destructor Documentation
ROJTRRouter()
ROJTRRouter::ROJTRRouter (bool unbuildIsWarningOnly, bool acceptAllDestinations, int maxEdges, bool ignoreClasses, bool allowLoops)
Constructor.
Parameters
[in] unbuildIsWarningOnly Whether not closed routes shall not yield in an error
[in] acceptAllDestinations If false, only sinks will be used as final edges
[in] maxEdges The maximum number of edges a route may have
[in] ignoreClasses Whether routing shall be done without regarding vehicle classes
[in] allowLoops Whether a vehicle may reuse a road
Definition at line 41 of file ROJTRRouter.cpp.
Referenced by clone().
~ROJTRRouter()
ROJTRRouter::~ROJTRRouter ()
Destructor.
Definition at line 50 of file ROJTRRouter.cpp.
Member Function Documentation
clone()
virtual SUMOAbstractRouter<ROEdge, ROVehicle>* ROJTRRouter::clone () inline virtual
Implements SUMOAbstractRouter< ROEdge, ROVehicle >.
Definition at line 69 of file ROJTRRouter.h.
References compute(), myAcceptAllDestination, myAllowLoops, myIgnoreClasses, myMaxEdges, myUnbuildIsWarningOnly, recomputeCosts(), and ROJTRRouter().
compute() [1/2]
virtual bool SUMOAbstractRouter< ROEdge , ROVehicle >::compute (const ROEdge * from, const ROEdge * to, const ROVehicle *const vehicle, SUMOTime msTime, std::vector< const ROEdge *> & into) pure virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
compute() [2/2]
bool ROJTRRouter::compute (const ROEdge * from, const ROEdge * to, const ROVehicle *const vehicle, SUMOTime time, ConstROEdgeVector & into)
Computes a route.
The description how routes are computed is given in the user documentation
Parameters
[in] from The edge the vehicle starts at
[in] to The destination edge - invalid here
[in] vehicle The vehicle to compute the route for
[in] time The departure time of the vehicle
Definition at line 54 of file ROJTRRouter.cpp.
References ROJTREdge::chooseNext(), MsgHandler::getErrorInstance(), Named::getID(), ROEdge::getTravelTime(), MsgHandler::getWarningInstance(), MsgHandler::inform(), ROEdge::isSink(), myAcceptAllDestination, myAllowLoops, myIgnoreClasses, myMaxEdges, myUnbuildIsWarningOnly, ROEdge::prohibits(), and STEPS2TIME.
Referenced by clone().
endQuery()
void SUMOAbstractRouter< ROEdge , ROVehicle >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
getEffort()
double SUMOAbstractRouter< ROEdge , ROVehicle >::getEffort (const ROEdge *const e, const ROVehicle *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
recomputeCosts() [1/2]
virtual double SUMOAbstractRouter< ROEdge , ROVehicle >::recomputeCosts (const std::vector< const ROEdge *> & edges, const ROVehicle *const v, SUMOTime msTime) const pure virtual inherited
recomputeCosts() [2/2]
double ROJTRRouter::recomputeCosts (const ConstROEdgeVector & edges, const ROVehicle *const v, SUMOTime msTime) const
Recomputes the costs of a route.
Parameters
[in] edges The route
[in] v The vehicle that belongs to the route
[in] msTime The departure time of the vehicle
Returns
The route costs
Definition at line 91 of file ROJTRRouter.cpp.
References STEPS2TIME.
Referenced by clone().
setBulkMode()
void SUMOAbstractRouter< ROEdge , ROVehicle >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
startQuery()
void SUMOAbstractRouter< ROEdge , ROVehicle >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Field Documentation
myAcceptAllDestination
const bool ROJTRRouter::myAcceptAllDestination private
Whether all edges may be used as route end.
Definition at line 104 of file ROJTRRouter.h.
Referenced by clone(), and compute().
myAllowLoops
const bool ROJTRRouter::myAllowLoops private
Whether a vehicle may reuse a road.
Definition at line 113 of file ROJTRRouter.h.
Referenced by clone(), and compute().
myBulkMode
bool SUMOAbstractRouter< ROEdge , ROVehicle >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
myIgnoreClasses
const bool ROJTRRouter::myIgnoreClasses private
Whether vehicle class information shall be ignored.
Definition at line 110 of file ROJTRRouter.h.
Referenced by clone(), and compute().
myMaxEdges
const int ROJTRRouter::myMaxEdges private
The maximum number of edges a route may have.
Definition at line 107 of file ROJTRRouter.h.
Referenced by clone(), and compute().
myOperation
Operation SUMOAbstractRouter< ROEdge , ROVehicle >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
myUnbuildIsWarningOnly
const bool ROJTRRouter::myUnbuildIsWarningOnly private
Whether unbuildable routes shall be reported as warniings, not errors.
Definition at line 101 of file ROJTRRouter.h.
Referenced by clone(), and compute().
The documentation for this class was generated from the following files:
ROJTRRouter.h
ROJTRRouter.cpp