SUMO - Simulation of Urban MObility: RandomDistributor< T > Class Template Reference
RandomDistributor< T > Class Template Reference
Represents a generic random distribution.
#include <RandomDistributor.h>
Public Member Functions
bool add (T val, double prob, bool checkDuplicates=true)
Adds a value with an assigned probability to the distribution.
void clear ()
Clears the distribution.
T get (std::mt19937 *which=0) const
Draw a sample of the distribution.
double getOverallProb () const
Return the sum of the probabilites assigned to the members.
const std::vector< double > & getProbs () const
Returns the probabilities assigned to the members of the distribution.
const std::vector< T > & getVals () const
Returns the members of the distribution.
RandomDistributor ()
Constructor for an empty distribution.
~RandomDistributor ()
Destructor.
Private Attributes
double myProb
the total probability
std::vector< double > myProbs
the corresponding probabilities
std::vector< T > myVals
the members
Detailed Description
template<class T>
class RandomDistributor< T >
Represents a generic random distribution.
This class allows to create random distributions by assigning arbitrary (non-negative) probabilities to its elements. The random number generator used is specified in RandHelper.
See also
RandHelper
Definition at line 55 of file RandomDistributor.h.
Constructor & Destructor Documentation
RandomDistributor()
template<class T> RandomDistributor< T >::RandomDistributor () inline
Constructor for an empty distribution.
Definition at line 59 of file RandomDistributor.h.
~RandomDistributor()
template<class T> RandomDistributor< T >::~RandomDistributor () inline
Destructor.
Definition at line 64 of file RandomDistributor.h.
Member Function Documentation
add()
template<class T> bool RandomDistributor< T >::add (T val, double prob, bool checkDuplicates = true) inline
Adds a value with an assigned probability to the distribution.
If the value is already member of the distribution and checkDuplicates is true (the default) the given probability is added to the current. The probability has to be non-negative but values larger than one are allowed (and scaled accordingly when an element is drawn).
Parameters
[in] val The value to add to the distribution
[in] prob The probability assigned to the value
Returns
true if a new value was added, false if just the probability of an existing one was updated
Definition at line 77 of file RandomDistributor.h.
Referenced by GUIEdge::addRerouter(), ODDistrict::addSink(), ODDistrict::addSource(), buildNetwork(), ROJTREdge::chooseNext(), MSRouteHandler::closeRoute(), GUISettingsHandler::getEventDistribution(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition::myEndElement(), MSTriggeredRerouter::myStartElement(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), RORouteHandler::openVehicleTypeDistribution(), NIVissimSingleTypeParser_Zeitenverteilungsdefinition::parse(), NIVissimSingleTypeParser_Laengenverteilungsdefinition::parse(), NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), and ODMatrix::parseTimeLine().
clear()
template<class T> void RandomDistributor< T >::clear () inline
Clears the distribution.
Definition at line 125 of file RandomDistributor.h.
Referenced by MSTriggeredRerouter::myEndElement().
get()
template<class T> T RandomDistributor< T >::get (std::mt19937 * which = 0) const inline
Draw a sample of the distribution.
A random sample is drawn according to the assigned probabilities.
Parameters
[in] which The random number generator to use; the static one will be used if 0 is passed
Returns
the drawn member
Definition at line 100 of file RandomDistributor.h.
Referenced by GUIApplicationWindow::checkGamingEvents(), ROJTREdge::chooseNext(), NGRandomNetBuilder::createNewNode(), ODDistrict::getRandomSink(), ODDistrict::getRandomSource(), MSTriggeredRerouter::notifyEnter(), and RODFDetector::writeEmitterDefinition().
getOverallProb()
template<class T> double RandomDistributor< T >::getOverallProb () const inline
Return the sum of the probabilites assigned to the members.
This should be zero if and only if the distribution is empty.
Returns
the total probability
Definition at line 120 of file RandomDistributor.h.
Referenced by ODMatrix::applyCurve(), GUIApplicationWindow::checkGamingEvents(), ROJTREdge::chooseNext(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicleTypeDistribution(), RORouteHandler::closeVehicleTypeDistribution(), GUISettingsHandler::getEventDistribution(), MSTriggeredRerouter::notifyEnter(), and RODFDetector::writeEmitterDefinition().
getProbs()
template<class T> const std::vector<double>& RandomDistributor< T >::getProbs () const inline
Returns the probabilities assigned to the members of the distribution.
See getVals for the corresponding members.
Returns
the probabilities assigned to the distribution
See also
RandomDistributor::getVals
Definition at line 149 of file RandomDistributor.h.
Referenced by ODMatrix::applyCurve(), MSRouteHandler::openRoute(), MSTriggeredRerouter::rerouteParkingArea(), and MSDevice_Vehroutes::writeOutput().
getVals()
template<class T> const std::vector<T>& RandomDistributor< T >::getVals () const inline
Returns the members of the distribution.
See getProbs for the corresponding probabilities.
Returns
the members of the distribution
See also
RandomDistributor::getProbs
Definition at line 138 of file RandomDistributor.h.
Referenced by ODMatrix::applyCurve(), MSTriggeredRerouter::rerouteParkingArea(), ODDistrict::sinkNumber(), ODDistrict::sourceNumber(), and MSDevice_Vehroutes::writeOutput().
Field Documentation
myProb
template<class T> double RandomDistributor< T >::myProb private
the total probability
Definition at line 155 of file RandomDistributor.h.
Referenced by RandomDistributor< MSVehicleType *>::add(), RandomDistributor< MSVehicleType *>::clear(), RandomDistributor< MSVehicleType *>::get(), and RandomDistributor< MSVehicleType *>::getOverallProb().
myProbs
template<class T> std::vector<double> RandomDistributor< T >::myProbs private
the corresponding probabilities
Definition at line 159 of file RandomDistributor.h.
Referenced by RandomDistributor< MSVehicleType *>::add(), RandomDistributor< MSVehicleType *>::clear(), RandomDistributor< MSVehicleType *>::get(), and RandomDistributor< MSVehicleType *>::getProbs().
myVals
template<class T> std::vector<T> RandomDistributor< T >::myVals private
the members
Definition at line 157 of file RandomDistributor.h.
Referenced by RandomDistributor< MSVehicleType *>::add(), RandomDistributor< MSVehicleType *>::clear(), RandomDistributor< MSVehicleType *>::get(), and RandomDistributor< MSVehicleType *>::getVals().
The documentation for this class was generated from the following file:
RandomDistributor.h