SUMO - Simulation of Urban MObility: GUIBaseVehicle Class Reference
GUIBaseVehicle Class Reference abstract
A MSVehicle extended by some values for usage within the gui.
#include <GUIBaseVehicle.h>
Data Structures
class GUIBaseVehiclePopupMenu
Public Member Functions
virtual bool drawAction_drawCarriageClass (const GUIVisualizationSettings &s, SUMOVehicleShape guiShape, bool asImage) const =0
draws the given guiShape if it has distinc carriages/modules and eturns true if so
virtual void drawAction_drawLinkItems (const GUIVisualizationSettings &) const
virtual void drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &) const
virtual void drawAction_drawVehicleBlinker (double) const
virtual void drawAction_drawVehicleBlueLight () const
virtual void drawAction_drawVehicleBrakeLight (double length, bool onlyOne=false) const
virtual void drawBestLanes () const
Draws the vehicle's best lanes.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
virtual void drawRouteHelper (const GUIVisualizationSettings &s, const MSRoute &r) const =0
Draws the route.
virtual double getAngle () const =0
Returns the vehicle's direction in radians.
virtual double getColorValue (int activeScheme) const =0
gets the color value according to the current scheme index
virtual double getLastLaneChangeOffset () const =0
Returns the time since the last lane change in seconds.
double getNaviDegree () const
return the current angle in navigational degrees
virtual GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)=0
Returns an own parameter window.
virtual Position getPosition (const double offset=0) const =0
Return current position (x/y, cartesian)
virtual std::string getStopInfo () const =0
retrieve information about the current stop state
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)=0
Returns an own type parameter window.
GUIBaseVehicle (MSBaseVehicle &vehicle)
virtual void selectBlockingFoes () const =0
adds the blocking foes to the current selection
~GUIBaseVehicle ()
destructor
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawOnPos (const GUIVisualizationSettings &s, const Position &pos, const double angle) const
Draws the object on the specified position with the specified angle.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static bool setFunctionalColor (int activeScheme, const MSBaseVehicle *veh)
sets the color according to the current scheme index and some vehicle function
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
const Position & getSeatPosition (int personIndex) const
returns the seat position for the person with the given index
const MSVehicleType & getVType () const
A shortcut to myVehicle.myType.
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Member Functions
static void drawLinkItem (const Position &pos, SUMOTime arrivalTime, SUMOTime leaveTime, double exagerate)
Protected Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
PositionVector mySeatPositions
positions of seats in the vehicle (updated at every drawing step)
Private Attributes
MSDevice_Vehroutes * myRoutes
MSBaseVehicle & myVehicle
The vehicle to which all calls should be delegated.
Additional visualisations
enum VisualisationFeatures {
VO_SHOW_BEST_LANES = 1, VO_SHOW_ROUTE = 2, VO_SHOW_ALL_ROUTES = 4, VO_SHOW_LFLINKITEMS = 8,
VO_DRAW_OUTSIDE_NETWORK = 16
}
Additional visualisation feature ids.
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
bool hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
void addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void drawRoute (const GUIVisualizationSettings &s, int routeNo, double darken) const
Chooses the route to draw and draws it, darkening it as given.
drawing helper methods
void drawAction_drawVehicleAsBoxPlus () const
void drawAction_drawVehicleAsTrianglePlus () const
bool drawAction_drawVehicleAsPoly (const GUIVisualizationSettings &s) const
bool drawAction_drawVehicleAsImage (const GUIVisualizationSettings &s, double length=-1) const
static void drawPoly (double *poses, double offset)
Detailed Description
A MSVehicle extended by some values for usage within the gui.
A visualisable MSVehicle. Extended by the possibility to retrieve names of all available vehicles (static) and the possibility to retrieve the color of the vehicle which is available in different forms allowing an easier recognition of done actions such as lane changing.
Definition at line 68 of file GUIBaseVehicle.h.
Member Enumeration Documentation
VisualisationFeatures
enum GUIBaseVehicle::VisualisationFeatures
Additional visualisation feature ids.
Enumerator
VO_SHOW_BEST_LANES
show vehicle's best lanes
VO_SHOW_ROUTE
show vehicle's current route
VO_SHOW_ALL_ROUTES
show all vehicle's routes
VO_SHOW_LFLINKITEMS
LFLinkItems.
VO_DRAW_OUTSIDE_NETWORK
draw vehicle outside the road network
Definition at line 287 of file GUIBaseVehicle.h.
Constructor & Destructor Documentation
GUIBaseVehicle()
GUIBaseVehicle::GUIBaseVehicle (MSBaseVehicle & vehicle)
Definition at line 256 of file GUIBaseVehicle.cpp.
References MSDevice_Vehroutes::buildVehicleDevices(), MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, myRoutes, mySeatPositions, and myVehicle.
~GUIBaseVehicle()
GUIBaseVehicle::~GUIBaseVehicle ()
destructor
Definition at line 266 of file GUIBaseVehicle.cpp.
References GUIGlObject::getGlID(), MFXMutex::lock(), myAdditionalVisualizations, myLock, myRoutes, GLObjectValuePassConnector< T >::removeObject(), and MFXMutex::unlock().
Member Function Documentation
addActiveAddVisualisation()
void GUIBaseVehicle::addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::addAdditionalGLVisualisation
Definition at line 1174 of file GUIBaseVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), and myAdditionalVisualizations.
Referenced by drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and getPopUpMenu().
drawAction_drawCarriageClass()
virtual bool GUIBaseVehicle::drawAction_drawCarriageClass (const GUIVisualizationSettings & s, SUMOVehicleShape guiShape, bool asImage) const pure virtual
draws the given guiShape if it has distinc carriages/modules and eturns true if so
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by drawAction_drawVehicleAsPoly(), drawOnPos(), and getNaviDegree().
drawAction_drawLinkItems()
virtual void GUIBaseVehicle::drawAction_drawLinkItems (const GUIVisualizationSettings &) const inline virtual
Reimplemented in GUIVehicle.
Definition at line 141 of file GUIBaseVehicle.h.
Referenced by drawGLAdditional().
drawAction_drawPersonsAndContainers()
virtual void GUIBaseVehicle::drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &) const inline virtual
Reimplemented in GUIVehicle.
Definition at line 142 of file GUIBaseVehicle.h.
Referenced by drawOnPos().
drawAction_drawVehicleAsBoxPlus()
void GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus () const protected
Definition at line 336 of file GUIBaseVehicle.cpp.
References getVType().
Referenced by GUIMEVehicle::drawAction_drawCarriageClass(), drawAction_drawVehicleAsTrianglePlus(), and drawOnPos().
drawAction_drawVehicleAsImage()
bool GUIBaseVehicle::drawAction_drawVehicleAsImage (const GUIVisualizationSettings & s, double length = -1) const protected
Definition at line 848 of file GUIBaseVehicle.cpp.
References GUITexturesHelper::drawTexturedBox(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), getVType(), MSVehicleType::getWidth(), and GUIVisualizationSettings::vehicleSize.
Referenced by GUIVehicle::drawAction_drawRailCarriages(), and drawOnPos().
drawAction_drawVehicleAsPoly()
bool GUIBaseVehicle::drawAction_drawVehicleAsPoly (const GUIVisualizationSettings & s) const protected
Definition at line 385 of file GUIBaseVehicle.cpp.
References RGBColor::changedBrightness(), drawAction_drawCarriageClass(), GLHelper::drawBoxLine(), GLHelper::drawFilledCircle(), drawPoly(), GLHelper::getColor(), MSVehicleType::getGuiShape(), MSVehicleType::getLength(), getVType(), MSVehicleType::getWidth(), RGBColor::GREY, GLHelper::setColor(), SVS_ANT, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_BUS_FLEXIBLE, SVS_BUS_TROLLEY, SVS_DELIVERY, SVS_E_VEHICLE, SVS_EMERGENCY, SVS_FIREBRIGADE, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, SVS_PASSENGER_WAGON, SVS_PEDESTRIAN, SVS_POLICE, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_1TRAILER, SVS_TRUCK_SEMITRAILER, SVS_UNKNOWN, and vehiclePoly_PassengerCarBody.
Referenced by drawOnPos().
drawAction_drawVehicleAsTrianglePlus()
void GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus () const protected
Definition at line 351 of file GUIBaseVehicle.cpp.
References drawAction_drawVehicleAsBoxPlus(), MSVehicleType::getLength(), and getVType().
Referenced by drawOnPos().
drawAction_drawVehicleBlinker()
virtual void GUIBaseVehicle::drawAction_drawVehicleBlinker (double) const inline virtual
Reimplemented in GUIVehicle.
Definition at line 136 of file GUIBaseVehicle.h.
Referenced by drawOnPos().
drawAction_drawVehicleBlueLight()
virtual void GUIBaseVehicle::drawAction_drawVehicleBlueLight () const inline virtual
Reimplemented in GUIVehicle.
Definition at line 145 of file GUIBaseVehicle.h.
References addActiveAddVisualisation(), drawGL(), drawGLAdditional(), drawOnPos(), getCenteringBoundary(), getPopUpMenu(), hasActiveAddVisualisation(), and removeActiveAddVisualisation().
Referenced by drawOnPos().
drawAction_drawVehicleBrakeLight()
virtual void GUIBaseVehicle::drawAction_drawVehicleBrakeLight (double length, bool onlyOne = false) const inline virtual
Reimplemented in GUIVehicle.
Definition at line 137 of file GUIBaseVehicle.h.
References UNUSED_PARAMETER.
Referenced by drawOnPos().
drawBestLanes()
virtual void GUIBaseVehicle::drawBestLanes () const inline virtual
Draws the vehicle's best lanes.
Reimplemented in GUIVehicle.
Definition at line 144 of file GUIBaseVehicle.h.
Referenced by drawGLAdditional().
drawGL()
void GUIBaseVehicle::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 1030 of file GUIBaseVehicle.cpp.
References drawOnPos(), getAngle(), and getPosition().
Referenced by drawAction_drawVehicleBlueLight(), GUIParkingArea::drawGL(), GUILane::drawGL(), and drawGLAdditional().
drawGLAdditional()
void GUIBaseVehicle::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 1036 of file GUIBaseVehicle.cpp.
References drawAction_drawLinkItems(), drawBestLanes(), drawGL(), drawRoute(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), GUIGlObject::getType(), hasActiveAddVisualisation(), MSBaseVehicle::isOnRoad(), myVehicle, VO_SHOW_ALL_ROUTES, VO_SHOW_BEST_LANES, VO_SHOW_LFLINKITEMS, and VO_SHOW_ROUTE.
Referenced by drawAction_drawVehicleBlueLight().
drawLinkItem()
void GUIBaseVehicle::drawLinkItem (const Position & pos, SUMOTime arrivalTime, SUMOTime leaveTime, double exagerate) static protected
Definition at line 1069 of file GUIBaseVehicle.cpp.
References GLHelper::drawFilledCircle(), GLHelper::drawText(), RGBColor::GREEN, STEPS2TIME, toString(), Position::x(), and Position::y().
Referenced by GUIVehicle::drawAction_drawLinkItems().
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GNERouteProbe::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and drawOnPos().
drawOnPos()
void GUIBaseVehicle::drawOnPos (const GUIVisualizationSettings & s, const Position & pos, const double angle) const
Draws the object on the specified position with the specified angle.
Parameters
[in] s The settings for the current view (may influence drawing)
[in] pos The position to draw the vehicle on
[in] angle The drawing angle of the vehicle
Definition at line 867 of file GUIBaseVehicle.cpp.
References GUIVisualizationTextSettings::color, drawAction_drawCarriageClass(), drawAction_drawPersonsAndContainers(), drawAction_drawVehicleAsBoxPlus(), drawAction_drawVehicleAsImage(), drawAction_drawVehicleAsPoly(), drawAction_drawVehicleAsTrianglePlus(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBlueLight(), drawAction_drawVehicleBrakeLight(), GUIVisualizationSettings::drawLaneChangePreference, GUIVisualizationSettings::drawMinGap, GUIGlObject::drawName(), GLHelper::drawOutlineCircle(), GLHelper::drawText(), MSBaseVehicle::getDevice(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), SUMOVehicle::getLane(), MSVehicleType::getMinGap(), MSBaseVehicle::getParameter(), SUMOVehicle::getPosition(), MSDevice_BTreceiver::getRange(), GUIGlObject::getType(), getVType(), GLO_MAX, SUMOVehicleParameter::line, M_PI, MIN2(), mySeatPositions, myVehicle, GUIVisualizationSettings::personName, RAD2DEG, GUIVisualizationSettings::scale, setColor(), GUIVisualizationTextSettings::show, GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationTextSettings::size, SVS_ANT, SVS_BICYCLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by drawAction_drawVehicleBlueLight(), drawGL(), and GUIEdge::drawMesoVehicles().
drawPoly()
void GUIBaseVehicle::drawPoly (double * poses, double offset) static protected
Definition at line 369 of file GUIBaseVehicle.cpp.
Referenced by drawAction_drawVehicleAsPoly().
drawRoute()
void GUIBaseVehicle::drawRoute (const GUIVisualizationSettings & s, int routeNo, double darken) const
Chooses the route to draw and draws it, darkening it as given.
Parameters
[in] s The visualisation settings, needed to determine the vehicle's color
[in] routeNo The route to show (0: the current, >0: prior)
[in] darken The amount to darken the route by
Definition at line 1191 of file GUIBaseVehicle.cpp.
References drawRouteHelper(), MSBaseVehicle::getRoute(), MSDevice_Vehroutes::getRoute(), myRoutes, myVehicle, and setColor().
Referenced by drawGLAdditional().
drawRouteHelper()
virtual void GUIBaseVehicle::drawRouteHelper (const GUIVisualizationSettings & s, const MSRoute & r) const pure virtual
Draws the route.
Parameters
[in] r The route to draw
Implemented in GUIMEVehicle, and GUIVehicle.
Referenced by drawRoute(), and getNaviDegree().
getAngle()
virtual double GUIBaseVehicle::getAngle () const pure virtual
Returns the vehicle's direction in radians.
Returns
The vehicle's current angle
Implemented in GUIMEVehicle, and GUIVehicle.
Referenced by drawGL(), and getNaviDegree().
getCenteringBoundary()
Boundary GUIBaseVehicle::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 327 of file GUIBaseVehicle.cpp.
References Boundary::add(), MSVehicleType::getLength(), getPosition(), MSBaseVehicle::getVehicleType(), Boundary::grow(), and myVehicle.
Referenced by drawAction_drawVehicleBlueLight().
getColorValue()
virtual double GUIBaseVehicle::getColorValue (int activeScheme) const pure virtual
gets the color value according to the current scheme index
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by getNaviDegree(), and setColor().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), drawGLAdditional(), GUILane::drawLinkRule(), drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GUIVehicle::isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), ~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getLastLaneChangeOffset()
virtual double GUIBaseVehicle::getLastLaneChangeOffset () const pure virtual
Returns the time since the last lane change in seconds.
See also
MSVehicle::myLastLaneChangeOffset
Returns
The time since the last lane change in seconds
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by getNaviDegree().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNEPoly::getParentName(), GNERerouter::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNaviDegree()
double GUIBaseVehicle::getNaviDegree () const inline
return the current angle in navigational degrees
Definition at line 92 of file GUIBaseVehicle.h.
References drawAction_drawCarriageClass(), drawRouteHelper(), getAngle(), getColorValue(), getLastLaneChangeOffset(), getParameterWindow(), getStopInfo(), getTypeParameterWindow(), GeomHelper::naviDegree(), and selectBlockingFoes().
Referenced by GUIMEVehicle::getParameterWindow(), and GUIVehicle::getParameterWindow().
getParameterWindow()
virtual GUIParameterTableWindow* GUIBaseVehicle::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) pure virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by getNaviDegree().
getParentName()
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEPoly, GNERerouter, GNEPOILane, GNEVariableSpeedSign, GNENetElement, GNEPOI, GNERouteProbe, GNEStoppingPlace, GNEDetector, GUILane, GNEDetectorE3, GNEVaporizer, and GNELane.
Definition at line 114 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
getPopUpMenu()
GUIGLObjectPopupMenu * GUIBaseVehicle::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 281 of file GUIBaseVehicle.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), hasActiveAddVisualisation(), MID_HIDE_ALLROUTES, MID_HIDE_BEST_LANES, MID_HIDE_CURRENTROUTE, MID_HIDE_LFLINKITEMS, MID_SHOW_ALLROUTES, MID_SHOW_BEST_LANES, MID_SHOW_CURRENTROUTE, MID_SHOW_FOES, MID_SHOW_LFLINKITEMS, MID_START_TRACK, MID_STOP_TRACK, myAdditionalVisualizations, VO_SHOW_ALL_ROUTES, VO_SHOW_BEST_LANES, VO_SHOW_LFLINKITEMS, and VO_SHOW_ROUTE.
Referenced by drawAction_drawVehicleBlueLight().
getPosition()
virtual Position GUIBaseVehicle::getPosition (const double offset = 0) const pure virtual
Return current position (x/y, cartesian)
If the vehicle's myLane is 0, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See also
myLane
Implemented in GUIMEVehicle, and GUIVehicle.
Referenced by drawGL(), and getCenteringBoundary().
getSeatPosition()
const Position & GUIBaseVehicle::getSeatPosition (int personIndex) const protected
returns the seat position for the person with the given index
if there are not enough seats in the vehicle people have to squeeze onto the last seat
Definition at line 1225 of file GUIBaseVehicle.cpp.
References MIN2(), and mySeatPositions.
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers().
getStopInfo()
virtual std::string GUIBaseVehicle::getStopInfo () const pure virtual
retrieve information about the current stop state
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by getNaviDegree().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), drawGLAdditional(), GNEAdditional::drawLockIcon(), drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
virtual GUIParameterTableWindow* GUIBaseVehicle::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) pure virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented from GUIGlObject.
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by getNaviDegree().
getVType()
const MSVehicleType& GUIBaseVehicle::getVType () const inline protected
A shortcut to myVehicle.myType.
Definition at line 342 of file GUIBaseVehicle.h.
References MSBaseVehicle::getVehicleType(), and myVehicle.
Referenced by GUIVehicle::drawAction_drawRailCarriages(), drawAction_drawVehicleAsBoxPlus(), drawAction_drawVehicleAsImage(), drawAction_drawVehicleAsPoly(), drawAction_drawVehicleAsTrianglePlus(), and drawOnPos().
hasActiveAddVisualisation()
bool GUIBaseVehicle::hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
Parameters
[in] parent The view for which the feature may be enabled
[in] which The visualisation feature
Returns
see comment
Definition at line 1168 of file GUIBaseVehicle.cpp.
References myAdditionalVisualizations.
Referenced by drawAction_drawVehicleBlueLight(), drawGLAdditional(), and getPopUpMenu().
removeActiveAddVisualisation()
void GUIBaseVehicle::removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::removeAdditionalGLVisualisation
Definition at line 1184 of file GUIBaseVehicle.cpp.
References myAdditionalVisualizations, and GUISUMOAbstractView::removeAdditionalGLVisualisation().
Referenced by drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
selectBlockingFoes()
virtual void GUIBaseVehicle::selectBlockingFoes () const pure virtual
adds the blocking foes to the current selection
Implemented in GUIVehicle, and GUIMEVehicle.
Referenced by getNaviDegree(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes().
setColor()
void GUIBaseVehicle::setColor (const GUIVisualizationSettings & s) const protected
sets the color according to the currente settings
Definition at line 1079 of file GUIBaseVehicle.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), myVehicle, GLHelper::setColor(), setFunctionalColor(), and GUIVisualizationSettings::vehicleColorer.
Referenced by drawOnPos(), and drawRoute().
setFunctionalColor()
bool GUIBaseVehicle::setFunctionalColor (int activeScheme, const MSBaseVehicle * veh) static
sets the color according to the current scheme index and some vehicle function
Definition at line 1088 of file GUIBaseVehicle.cpp.
References SUMOVehicleParameter::color, RGBColor::DEFAULT_COLOR, Position::distanceTo(), RGBColor::fromHSV(), Boundary::getCenter(), MSRoute::getColor(), MSVehicleType::getColor(), MSRoute::getEdges(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSBaseVehicle::getRoute(), MSBaseVehicle::getVehicleType(), M_PI, GLHelper::setColor(), VEHPARS_COLOR_SET, VTYPEPARS_COLOR_SET, MSVehicleType::wasSet(), SUMOVehicleParameter::wasSet(), Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by setColor().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
myAdditionalVisualizations
std::map<GUISUMOAbstractView*, int> GUIBaseVehicle::myAdditionalVisualizations
Enabled visualisations, per view.
Definition at line 301 of file GUIBaseVehicle.h.
Referenced by addActiveAddVisualisation(), GUIVehicle::drawOutsideNetwork(), getPopUpMenu(), hasActiveAddVisualisation(), removeActiveAddVisualisation(), and ~GUIBaseVehicle().
myLock
MFXMutex GUIBaseVehicle::myLock mutable protected
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 349 of file GUIBaseVehicle.h.
Referenced by GUIVehicle::drawBestLanes(), and ~GUIBaseVehicle().
myRoutes
MSDevice_Vehroutes* GUIBaseVehicle::myRoutes private
Definition at line 358 of file GUIBaseVehicle.h.
Referenced by drawRoute(), GUIBaseVehicle(), and ~GUIBaseVehicle().
mySeatPositions
PositionVector GUIBaseVehicle::mySeatPositions mutable protected
positions of seats in the vehicle (updated at every drawing step)
Definition at line 352 of file GUIBaseVehicle.h.
Referenced by GUIVehicle::computeSeats(), GUIVehicle::drawAction_drawRailCarriages(), drawOnPos(), getSeatPosition(), and GUIBaseVehicle().
myVehicle
MSBaseVehicle& GUIBaseVehicle::myVehicle private
The vehicle to which all calls should be delegated.
Definition at line 356 of file GUIBaseVehicle.h.
Referenced by drawGLAdditional(), drawOnPos(), drawRoute(), getCenteringBoundary(), getVType(), GUIBaseVehicle(), and setColor().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIBaseVehicle.h
GUIBaseVehicle.cpp