SUMO - Simulation of Urban MObility: MSTLLogicControl::WAUTSwitchProcedure_JustSwitch Class Reference
MSTLLogicControl::WAUTSwitchProcedure_JustSwitch Class Reference
This class simply switches to the next program.
#include <MSTLLogicControl.h>
Public Member Functions
bool trySwitch (SUMOTime step)
Determines whether a switch is possible.
WAUTSwitchProcedure_JustSwitch (MSTLLogicControl &control, WAUT &waut, MSTrafficLightLogic *from, MSTrafficLightLogic *to, bool synchron)
Constructor.
~WAUTSwitchProcedure_JustSwitch ()
Destructor.
Protected Member Functions
SUMOTime getDiffToStartOfPhase (MSTrafficLightLogic &logic, SUMOTime toTime)
Returns the difference between a given time and the start of the phase.
int getGSPValue (const MSTrafficLightLogic &logic) const
Returns the GSP-value.
bool isPosAtGSP (SUMOTime currentTime, const MSTrafficLightLogic &logic)
Checks, whether the position of a signal programm is at the GSP ("GuenstigerUmschaltPunkt")
void switchToPos (SUMOTime simStep, MSTrafficLightLogic &logic, SUMOTime toTime)
switches the given logic directly to the given position
Protected Attributes
MSTLLogicControl & myControl
The control the logic belongs to.
MSTrafficLightLogic * myFrom
The current program of the tls to switch.
bool mySwitchSynchron
Information whether to switch synchron (?)
MSTrafficLightLogic * myTo
The program to switch the tls to.
WAUT & myWAUT
The WAUT responsible for switching.
Private Member Functions
WAUTSwitchProcedure_JustSwitch & operator= (const WAUTSwitchProcedure_JustSwitch &)
Invalidated assignment operator.
WAUTSwitchProcedure_JustSwitch (const WAUTSwitchProcedure_JustSwitch &)
Invalidated copy constructor.
Detailed Description
This class simply switches to the next program.
Definition at line 619 of file MSTLLogicControl.h.
Constructor & Destructor Documentation
WAUTSwitchProcedure_JustSwitch() [1/2]
MSTLLogicControl::WAUTSwitchProcedure_JustSwitch::WAUTSwitchProcedure_JustSwitch (MSTLLogicControl & control, WAUT & waut, MSTrafficLightLogic * from, MSTrafficLightLogic * to, bool synchron)
Constructor.
Parameters
[in] control The responsible tls control
[in] waut The WAUT to switch
[in] from The original tls program
[in] to The destination tls program
[in] synchron Whether the switch shall be done in synchronuous mode
Definition at line 281 of file MSTLLogicControl.cpp.
~WAUTSwitchProcedure_JustSwitch()
MSTLLogicControl::WAUTSwitchProcedure_JustSwitch::~WAUTSwitchProcedure_JustSwitch ()
Destructor.
Definition at line 287 of file MSTLLogicControl.cpp.
WAUTSwitchProcedure_JustSwitch() [2/2]
MSTLLogicControl::WAUTSwitchProcedure_JustSwitch::WAUTSwitchProcedure_JustSwitch (const WAUTSwitchProcedure_JustSwitch &) private
Invalidated copy constructor.
Member Function Documentation
getDiffToStartOfPhase()
SUMOTime MSTLLogicControl::WAUTSwitchProcedure::getDiffToStartOfPhase (MSTrafficLightLogic & logic, SUMOTime toTime) protected inherited
Returns the difference between a given time and the start of the phase.
Parameters
[in] logic The logic to consider
[in] toTime The time to ask for
Returns
How much time elapsed between the last pahse start and the given time
Definition at line 259 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::getIndexFromOffset(), and MSTrafficLightLogic::getOffsetFromIndex().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
getGSPValue()
int MSTLLogicControl::WAUTSwitchProcedure::getGSPValue (const MSTrafficLightLogic & logic) const protected inherited
Returns the GSP-value.
The GSP must be given as a logic's parameter ("GSP").
Parameters
[in] logic The logic to retrieve the GSP from
Returns
The GSP value; 0 if not given.
See also
MSTrafficLightLogic::getParameterValue
Definition at line 240 of file MSTLLogicControl.cpp.
References TplConvert::_2int(), and Parameterised::getParameter().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch().
isPosAtGSP()
bool MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP (SUMOTime currentTime, const MSTrafficLightLogic & logic) protected inherited
Checks, whether the position of a signal programm is at the GSP ("GuenstigerUmschaltPunkt")
The GSP must be given as a logic's parameter ("GSP"). Not the simulation second, but the phase the GSP lies within is used. If the phase the GSP lies within is the same as the logic's current phase, the result is true.
Parameters
[in] currentTime The current time step
[in] logic The logic for which this should be examined
Returns
Whether the current step is the GSP
See also
getGSPValue
Definition at line 250 of file MSTLLogicControl.cpp.
References MSPhaseDefinition::duration, MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getDefaultCycleTime(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), and TIME2STEPS.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch().
operator=()
WAUTSwitchProcedure_JustSwitch& MSTLLogicControl::WAUTSwitchProcedure_JustSwitch::operator= (const WAUTSwitchProcedure_JustSwitch &) private
Invalidated assignment operator.
switchToPos()
void MSTLLogicControl::WAUTSwitchProcedure::switchToPos (SUMOTime simStep, MSTrafficLightLogic & logic, SUMOTime toTime) protected inherited
switches the given logic directly to the given position
Parameters
[in] simStep The current simulation time
[in] logic The logic to switch
[in] toTime The time offset within the logic's phases to switch to
Definition at line 268 of file MSTLLogicControl.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), MSPhaseDefinition::duration, MSTrafficLightLogic::getIndexFromOffset(), and MSTrafficLightLogic::getPhase().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch().
trySwitch()
bool MSTLLogicControl::WAUTSwitchProcedure_JustSwitch::trySwitch (SUMOTime step) virtual
Determines whether a switch is possible.
Parameters
[in] step The current simulation step
Returns
This implementation alsways returns true
Implements MSTLLogicControl::WAUTSwitchProcedure.
Definition at line 291 of file MSTLLogicControl.cpp.
Field Documentation
myControl
MSTLLogicControl& MSTLLogicControl::WAUTSwitchProcedure::myControl protected inherited
The control the logic belongs to.
Definition at line 602 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
myFrom
MSTrafficLightLogic* MSTLLogicControl::WAUTSwitchProcedure::myFrom protected inherited
The current program of the tls to switch.
Definition at line 590 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch().
mySwitchSynchron
bool MSTLLogicControl::WAUTSwitchProcedure::mySwitchSynchron protected inherited
Information whether to switch synchron (?)
Definition at line 596 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch().
myTo
MSTrafficLightLogic* MSTLLogicControl::WAUTSwitchProcedure::myTo protected inherited
The program to switch the tls to.
Definition at line 593 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSTLLogicControl::WAUTSwitchProcedure_GSP::trySwitch(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::trySwitch().
myWAUT
WAUT& MSTLLogicControl::WAUTSwitchProcedure::myWAUT protected inherited
The WAUT responsible for switching.
Definition at line 599 of file MSTLLogicControl.h.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
The documentation for this class was generated from the following files:
MSTLLogicControl.h
MSTLLogicControl.cpp