SUMO - Simulation of Urban MObility: Option_Float Class Reference
Option_Float Class Reference
#include <Option.h>
Public Member Functions
virtual bool getBool () const
Returns the stored boolean value.
const std::string & getDescription () const
Returns the description of what this option does.
double getFloat () const
Returns the stored double value.
virtual int getInt () const
Returns the stored integer value.
virtual const IntVector & getIntVector () const
Returns the stored integer vector.
virtual std::string getString () const
Returns the stored string value.
virtual const std::string & getTypeName () const
Returns the mml-type name of this option.
std::string getValueString () const
Returns the string-representation of the value.
virtual bool isBool () const
Returns the information whether the option is a bool option.
virtual bool isDefault () const
Returns the information whether the option holds the default value.
virtual bool isFileName () const
Returns the information whether this option is a file name.
bool isSet () const
returns the information whether this options holds a valid value
bool isWriteable () const
Returns the information whether the option may be set a further time.
Option_Float & operator= (const Option_Float &s)
Assignment operator.
Option_Float (double value)
Constructor for an option with a default value.
Option_Float (const Option_Float &s)
Copy constructor.
void resetDefault ()
Resets the option to be on its default value.
void resetWritable ()
Resets the option to be writeable.
bool set (const std::string &v)
Stores the given value after parsing it into a double.
void setDescription (const std::string &desc)
Sets the description of what this option does.
void unSet ()
marks this option as unset
~Option_Float ()
Destructor.
Protected Member Functions
bool markSet ()
Marks the information as set.
Protected Attributes
std::string myTypeName
A type name for this option (has presets, but may be overwritten)
Private Attributes
double myValue
Detailed Description
Definition at line 451 of file Option.h.
Constructor & Destructor Documentation
Option_Float() [1/2]
Option_Float::Option_Float (double value)
Constructor for an option with a default value.
Calls Option(true)
Parameters
[in] value This option's default value
Definition at line 297 of file Option.cpp.
References Option::myTypeName.
Option_Float() [2/2]
Option_Float::Option_Float (const Option_Float & s)
Copy constructor.
Definition at line 306 of file Option.cpp.
References myValue.
~Option_Float()
Option_Float::~Option_Float ()
Destructor.
Definition at line 303 of file Option.cpp.
Member Function Documentation
getBool()
bool Option::getBool () const virtual inherited
Returns the stored boolean value.
Option_Bool returns the stored boolean in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored boolean if being an instance of Option_Bool
Exceptions
InvalidArgument If the class is not an instance of Option_Bool
Reimplemented in Option_Bool.
Definition at line 99 of file Option.cpp.
Referenced by OptionsCont::getBool().
getDescription()
const std::string & Option::getDescription () const inherited
Returns the description of what this option does.
The description stored in myDescription is returned.
Returns
The description of this option's purpose
Definition at line 164 of file Option.cpp.
References Option::myDescription.
Referenced by OptionsCont::printHelp(), and OptionsCont::writeConfiguration().
getFloat()
double Option_Float::getFloat () const virtual
Returns the stored double value.
See also
double Option::getFloat()
Returns
Returns the stored real number
Reimplemented from Option.
Definition at line 324 of file Option.cpp.
References myValue.
getInt()
int Option::getInt () const virtual inherited
Returns the stored integer value.
Option_Integer returns the stored integer number in this method's reimplementation. All other option classesdo not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored integer number if being an instance of Option_Integer
Exceptions
InvalidArgument If the class is not an instance of Option_Integer
Reimplemented in Option_Integer.
Definition at line 87 of file Option.cpp.
Referenced by OptionsCont::getInt().
getIntVector()
const IntVector & Option::getIntVector () const virtual inherited
Returns the stored integer vector.
Option_IntVector returns the stored integer vector in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored integer vector if being an instance of Option_IntVector
Exceptions
InvalidArgument If the class is not an instance of Option_IntVector
Reimplemented in Option_IntVector.
Definition at line 105 of file Option.cpp.
Referenced by OptionsCont::getIntVector().
getString()
std::string Option::getString () const virtual inherited
Returns the stored string value.
Option_String and Option_FileName return the stored string in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored string if being an instance of Option_String
Exceptions
InvalidArgument If the class is not an instance of Option_String
Reimplemented in Option_String.
Definition at line 93 of file Option.cpp.
Referenced by OptionsCont::getString(), and OptionsCont::getStringVector().
getTypeName()
const std::string & Option::getTypeName () const virtual inherited
Returns the mml-type name of this option.
The type name stored in myTypeName is returned.
Returns
The man-readable type name
Definition at line 176 of file Option.cpp.
References Option::myTypeName.
Referenced by OptionsCont::getTypeName(), OptionsCont::printHelp(), OptionsCont::writeConfiguration(), and OptionsCont::writeSchema().
getValueString()
std::string Option_Float::getValueString () const virtual
Returns the string-representation of the value.
The stored value is encoded into a string and returned.
See also
std::string Option::getValueString()
Returns
The stored value encoded into a string
Implements Option.
Definition at line 341 of file Option.cpp.
References myValue.
isBool()
bool Option::isBool () const virtual inherited
Returns the information whether the option is a bool option.
Returns false. Only Option_Bool overrides this method returning true.
Returns
true if the Option is an Option_Bool, false otherwise
Reimplemented in Option_Bool.
Definition at line 128 of file Option.cpp.
Referenced by OptionsCont::isBool(), and OptionsCont::printHelp().
isDefault()
bool Option::isDefault () const virtual inherited
Returns the information whether the option holds the default value.
Returns
true if the option was not set from command line / configuration, false otherwise
Definition at line 134 of file Option.cpp.
References Option::myHaveTheDefaultValue.
Referenced by OptionsCont::writeConfiguration().
isFileName()
bool Option::isFileName () const virtual inherited
Returns the information whether this option is a file name.
Returns false. Only Option_FileName overrides this method returning true.
Returns
true if the Option is an Option_FileName, false otherwise
Reimplemented in Option_FileName.
Definition at line 140 of file Option.cpp.
isSet()
bool Option::isSet () const inherited
returns the information whether this options holds a valid value
Returns
Whether a value has been set
Definition at line 75 of file Option.cpp.
References Option::myAmSet.
Referenced by OptionsCont::checkDependingSuboptions(), OptionsCont::isUsableFileList(), and OptionsCont::writeConfiguration().
isWriteable()
bool Option::isWriteable () const inherited
Returns the information whether the option may be set a further time.
This method returns whether the option was not already set using command line options / configuration. This is done by returning the value of myAmWritable.
Returns
Whether the option may be set from the command line / configuration
Definition at line 146 of file Option.cpp.
References Option::myAmWritable.
Referenced by OptionsCont::isWriteable(), and OptionsCont::set().
markSet()
bool Option::markSet () protected inherited
Marks the information as set.
Sets the "myAmSet" - information. Returns whether the option was writeable before.
Returns
Whether the option was not set before.
Definition at line 111 of file Option.cpp.
References Option::myAmSet, Option::myAmWritable, and Option::myHaveTheDefaultValue.
Referenced by Option_Integer::set(), Option_String::set(), set(), Option_Bool::set(), and Option_IntVector::set().
operator=()
Option_Float & Option_Float::operator= (const Option_Float & s)
Assignment operator.
Definition at line 313 of file Option.cpp.
References myValue, and Option::operator=().
resetDefault()
void Option::resetDefault () inherited
Resets the option to be on its default value.
An option is on its default after initialisation with a value, but as soon as it gets set, it is no longer. This method resets the default-flag.
Definition at line 158 of file Option.cpp.
References Option::myHaveTheDefaultValue.
Referenced by OptionsCont::setDefault().
resetWritable()
void Option::resetWritable () inherited
Resets the option to be writeable.
An option is writable after initialisation, but as soon as it gets set, it is no longer writeable. This method resets the writable-flag.
Definition at line 152 of file Option.cpp.
References Option::myAmWritable.
set()
bool Option_Float::set (const std::string & v) virtual
Stores the given value after parsing it into a double.
The value is converted into a double and stored in "myValue". Then, "markSet" is called in order to know that a value has been set.
The method returns whether the value could be set (the return value from "markSet").
If the string could not be converted into a double, an InvalidArgument is thrown.
See also
bool Option::set(std::string v)
Returns
Whether the new value could be set
Exceptions
InvalidArgument If the value could not be converted into a double
Implements Option.
Definition at line 330 of file Option.cpp.
References TplConvert::_2double(), Option::markSet(), and myValue.
setDescription()
void Option::setDescription (const std::string & desc) inherited
Sets the description of what this option does.
The description stored in myDescription is returned.
Returns
The description of this option's purpose
Definition at line 170 of file Option.cpp.
References Option::myDescription.
Referenced by OptionsCont::addDescription().
unSet()
void Option::unSet () inherited
marks this option as unset
Definition at line 121 of file Option.cpp.
References Option::myAmSet, and Option::myAmWritable.
Field Documentation
myTypeName
std::string Option::myTypeName protected inherited
A type name for this option (has presets, but may be overwritten)
Definition at line 286 of file Option.h.
Referenced by Option::getTypeName(), Option_Bool::Option_Bool(), Option_FileName::Option_FileName(), Option_Float(), Option_Integer::Option_Integer(), Option_IntVector::Option_IntVector(), and Option_String::Option_String().
myValue
double Option_Float::myValue private
the value, valid only when the base-classes "myAmSet"-member is true
Definition at line 511 of file Option.h.
Referenced by getFloat(), getValueString(), operator=(), Option_Float(), and set().
The documentation for this class was generated from the following files:
Option.h
Option.cpp