SUMO - Simulation of Urban MObility: GNEDialog_FixAdditionalPositions Class Reference
GNEDialog_FixAdditionalPositions Class Reference
Dialog for edit rerouters.
#include <GNEDialog_FixAdditionalPositions.h>
Public Member Functions
GNEDialog_FixAdditionalPositions (GNEViewNet *viewNet, const std::vector< GNEStoppingPlace *> &invalidStoppingPlaces, const std::vector< GNEDetector *> &invalidDetectors)
FOX-declaration.
~GNEDialog_FixAdditionalPositions ()
destructor
FOX-callbacks
event when user select a option
long onCmdSelectOption (FXObject *obj, FXSelector, void *)
long onCmdAccept (FXObject *, FXSelector, void *)
event after press accept button
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
Protected Member Functions
GNEDialog_FixAdditionalPositions ()
FOX needs this.
Protected Attributes
FXButton * myAcceptButton
accept button
FXButton * myCancelButton
cancel button
std::vector< GNEDetector * > myInvalidDetectors
vector with the invalid stoppingplaces
std::vector< GNEStoppingPlace * > myInvalidStoppingPlaces
vector with the invalid stoppingplaces
FXRadioButton * myOptionA
Option "Activate friendlyPos and save".
FXRadioButton * myOptionB
Option "Fix Positions and save".
FXRadioButton * myOptionC
Option "Save invalid".
FXRadioButton * myOptionD
Option "Select invalid stops and cancel".
FXTable * myTable
list with the stoppingPlaces and detectors
GNEViewNet * myViewNet
view net
Private Member Functions
GNEDialog_FixAdditionalPositions (const GNEDialog_FixAdditionalPositions &)=delete
Invalidated copy constructor.
GNEDialog_FixAdditionalPositions & operator= (const GNEDialog_FixAdditionalPositions &)=delete
Invalidated assignment operator.
Detailed Description
Dialog for edit rerouters.
Definition at line 49 of file GNEDialog_FixAdditionalPositions.h.
Constructor & Destructor Documentation
GNEDialog_FixAdditionalPositions() [1/3]
GNEDialog_FixAdditionalPositions::GNEDialog_FixAdditionalPositions (GNEViewNet * viewNet, const std::vector< GNEStoppingPlace *> & invalidStoppingPlaces, const std::vector< GNEDetector *> & invalidDetectors)
FOX-declaration.
Constructor
Definition at line 65 of file GNEDialog_FixAdditionalPositions.cpp.
References GNEDetectorE2::getAbsoluteLenght(), GNEDetector::getAbsolutePositionOverLane(), GUIIconSubSys::getIcon(), GUIDesignAuxiliarFrame, GUIDesignAuxiliarHorizontalFrame, GUIDesignAuxiliarVerticalFrame, GUIDesignButtonAccept, GUIDesignButtonCancel, GUIDesignHorizontalFrame, GUIDesignLabelCenterThick, GUIDesignRadioButton, GUIDesignTableAdditionals, GUIDesignTableIconCellWidth, ICON_ACCEPT, ICON_BUSSTOP, ICON_CANCEL, MID_CHOOSEN_OPERATION, MID_GNE_ADDITIONALDIALOG_BUTTONACCEPT, MID_GNE_ADDITIONALDIALOG_BUTTONCANCEL, MID_GNE_FIXSTOPPINGPLACES_CHANGE, SUMO_ATTR_ENDPOS, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, and toString().
~GNEDialog_FixAdditionalPositions()
GNEDialog_FixAdditionalPositions::~GNEDialog_FixAdditionalPositions ()
destructor
Definition at line 189 of file GNEDialog_FixAdditionalPositions.cpp.
GNEDialog_FixAdditionalPositions() [2/3]
GNEDialog_FixAdditionalPositions::GNEDialog_FixAdditionalPositions () inline protected
FOX needs this.
Definition at line 74 of file GNEDialog_FixAdditionalPositions.h.
GNEDialog_FixAdditionalPositions() [3/3]
GNEDialog_FixAdditionalPositions::GNEDialog_FixAdditionalPositions (const GNEDialog_FixAdditionalPositions &) private delete
Invalidated copy constructor.
Member Function Documentation
onCmdAccept()
long GNEDialog_FixAdditionalPositions::onCmdAccept (FXObject * , FXSelector , void *)
event after press accept button
Definition at line 226 of file GNEDialog_FixAdditionalPositions.cpp.
References GNEAdditionalHandler::checkAndFixDetectorPositionPosition(), GNEAdditionalHandler::fixE2DetectorPositionPosition(), GNEAdditionalHandler::fixStoppinPlacePosition(), GNEDetectorE2::getAttribute(), GNEStoppingPlace::getAttribute(), GNEStoppingPlace::getLane(), GNEDetector::getLane(), GNELane::getLaneParametricLength(), GNEViewNet::getNet(), GUISelectedStorage::getSelected(), GNEViewNet::getUndoList(), gSelected, myInvalidDetectors, myInvalidStoppingPlaces, myOptionA, myOptionB, myOptionC, myOptionD, myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), POSITION_EPS, GNEDetectorE2::setAttribute(), GNEStoppingPlace::setAttribute(), SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, and toString().
onCmdCancel()
long GNEDialog_FixAdditionalPositions::onCmdCancel (FXObject * , FXSelector , void *)
event after press cancel button
Definition at line 315 of file GNEDialog_FixAdditionalPositions.cpp.
onCmdSelectOption()
long GNEDialog_FixAdditionalPositions::onCmdSelectOption (FXObject * obj, FXSelector , void *)
Definition at line 194 of file GNEDialog_FixAdditionalPositions.cpp.
References myOptionA, myOptionB, myOptionC, and myOptionD.
operator=()
GNEDialog_FixAdditionalPositions& GNEDialog_FixAdditionalPositions::operator= (const GNEDialog_FixAdditionalPositions &) private delete
Invalidated assignment operator.
Field Documentation
myAcceptButton
FXButton* GNEDialog_FixAdditionalPositions::myAcceptButton protected
accept button
Definition at line 101 of file GNEDialog_FixAdditionalPositions.h.
myCancelButton
FXButton* GNEDialog_FixAdditionalPositions::myCancelButton protected
cancel button
Definition at line 104 of file GNEDialog_FixAdditionalPositions.h.
myInvalidDetectors
std::vector<GNEDetector*> GNEDialog_FixAdditionalPositions::myInvalidDetectors protected
vector with the invalid stoppingplaces
Definition at line 83 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept().
myInvalidStoppingPlaces
std::vector<GNEStoppingPlace*> GNEDialog_FixAdditionalPositions::myInvalidStoppingPlaces protected
vector with the invalid stoppingplaces
Definition at line 80 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept().
myOptionA
FXRadioButton* GNEDialog_FixAdditionalPositions::myOptionA protected
Option "Activate friendlyPos and save".
Definition at line 89 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept(), and onCmdSelectOption().
myOptionB
FXRadioButton* GNEDialog_FixAdditionalPositions::myOptionB protected
Option "Fix Positions and save".
Definition at line 92 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept(), and onCmdSelectOption().
myOptionC
FXRadioButton* GNEDialog_FixAdditionalPositions::myOptionC protected
Option "Save invalid".
Definition at line 95 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept(), and onCmdSelectOption().
myOptionD
FXRadioButton* GNEDialog_FixAdditionalPositions::myOptionD protected
Option "Select invalid stops and cancel".
Definition at line 98 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept(), and onCmdSelectOption().
myTable
FXTable* GNEDialog_FixAdditionalPositions::myTable protected
list with the stoppingPlaces and detectors
Definition at line 86 of file GNEDialog_FixAdditionalPositions.h.
myViewNet
GNEViewNet* GNEDialog_FixAdditionalPositions::myViewNet protected
view net
Definition at line 77 of file GNEDialog_FixAdditionalPositions.h.
Referenced by onCmdAccept().
The documentation for this class was generated from the following files:
GNEDialog_FixAdditionalPositions.h
GNEDialog_FixAdditionalPositions.cpp