SUMO - Simulation of Urban MObility: NIVissimBoundedClusterObject Class Reference
NIVissimBoundedClusterObject Class Reference abstract
#include <NIVissimBoundedClusterObject.h>
Public Member Functions
bool clustered () const
virtual void computeBounding ()=0
bool crosses (const AbstractPoly &poly, double offset=0) const
const Boundary & getBoundary () const
void inCluster (int id)
NIVissimBoundedClusterObject ()
virtual ~NIVissimBoundedClusterObject ()
Static Public Member Functions
static void closeLoading ()
Protected Types
typedef std::set< NIVissimBoundedClusterObject * > ContType
Protected Attributes
Boundary * myBoundary
int myClusterID
Static Protected Attributes
static ContType myDict
Detailed Description
Definition at line 47 of file NIVissimBoundedClusterObject.h.
Member Typedef Documentation
ContType
typedef std::set<NIVissimBoundedClusterObject*> NIVissimBoundedClusterObject::ContType protected
Definition at line 59 of file NIVissimBoundedClusterObject.h.
Constructor & Destructor Documentation
NIVissimBoundedClusterObject()
NIVissimBoundedClusterObject::NIVissimBoundedClusterObject ()
Definition at line 37 of file NIVissimBoundedClusterObject.cpp.
References myDict.
~NIVissimBoundedClusterObject()
NIVissimBoundedClusterObject::~NIVissimBoundedClusterObject () virtual
Definition at line 43 of file NIVissimBoundedClusterObject.cpp.
References myBoundary.
Member Function Documentation
closeLoading()
void NIVissimBoundedClusterObject::closeLoading () static
Definition at line 69 of file NIVissimBoundedClusterObject.cpp.
References myDict.
Referenced by NIImporter_Vissim::postLoadBuild().
clustered()
bool NIVissimBoundedClusterObject::clustered () const
Definition at line 63 of file NIVissimBoundedClusterObject.cpp.
References myClusterID.
Referenced by NIVissimConnection::buildNodeClusters().
computeBounding()
virtual void NIVissimBoundedClusterObject::computeBounding () pure virtual
Implemented in NIVissimConnection, and NIVissimDisturbance.
crosses()
bool NIVissimBoundedClusterObject::crosses (const AbstractPoly & poly, double offset = 0) const
Definition at line 49 of file NIVissimBoundedClusterObject.cpp.
References myBoundary, Boundary::overlapsWith(), Boundary::xmax(), and Boundary::xmin().
getBoundary()
const Boundary & NIVissimBoundedClusterObject::getBoundary () const
Definition at line 77 of file NIVissimBoundedClusterObject.cpp.
References myBoundary.
Referenced by NIVissimConnectionCluster::liesOnSameEdgesEnd().
inCluster()
void NIVissimBoundedClusterObject::inCluster (int id)
Definition at line 57 of file NIVissimBoundedClusterObject.cpp.
References myClusterID.
Field Documentation
myBoundary
Boundary* NIVissimBoundedClusterObject::myBoundary protected
Definition at line 61 of file NIVissimBoundedClusterObject.h.
Referenced by NIVissimConnection::buildNodeClusters(), NIVissimDisturbance::computeBounding(), NIVissimConnection::computeBounding(), crosses(), getBoundary(), NIVissimConnection::getBoundingBox(), and ~NIVissimBoundedClusterObject().
myClusterID
int NIVissimBoundedClusterObject::myClusterID protected
Definition at line 62 of file NIVissimBoundedClusterObject.h.
Referenced by clustered(), and inCluster().
myDict
NIVissimBoundedClusterObject::ContType NIVissimBoundedClusterObject::myDict static protected
Definition at line 60 of file NIVissimBoundedClusterObject.h.
Referenced by closeLoading(), and NIVissimBoundedClusterObject().
The documentation for this class was generated from the following files:
NIVissimBoundedClusterObject.h
NIVissimBoundedClusterObject.cpp