SUMO - Simulation of Urban MObility: GNEInspectorFrame::NeteditParameters Class Reference
GNEInspectorFrame::NeteditParameters Class Reference
#include <GNEInspectorFrame.h>
Public Member Functions
void hide ()
hide all NeteditParameters
NeteditParameters (GNEInspectorFrame *inspectorFrameParent)
FOX-declaration.
void show ()
show NeteditParameters
~NeteditParameters ()
destructor
FOX-callbacks
called when user change the parent of an additional
long onCmdChangeAdditionalParent (FXObject *, FXSelector, void *)
long onCmdSetBlockingMovement (FXObject *, FXSelector, void *)
called when user toogle the blocking movement CheckBox
long onCmdSetBlockingShape (FXObject *, FXSelector, void *)
called when user toogle the blocking shape CheckBox
long onCmdSetClosingShape (FXObject *, FXSelector, void *)
called when user toogle the closiong shape CheckBox
Protected Member Functions
NeteditParameters ()
FOX needs this.
Private Attributes
FXCheckButton * myCheckBoxBlockMovement
pointer to check box "Block movement"
FXCheckButton * myCheckBoxBlockShape
pointer to check box "Block Shape"
FXCheckButton * myCheckBoxCloseShape
pointer to check box "Block movement"
FXHorizontalFrame * myHorizontalFrameAdditionalParent
horizontal frame for change additional parent
FXHorizontalFrame * myHorizontalFrameBlockMovement
horizontal frame for block movement
FXHorizontalFrame * myHorizontalFrameBlockShape
horizontal frame for block shape
FXHorizontalFrame * myHorizontalFrameCloseShape
horizontal frame for close shape
GNEInspectorFrame * myInspectorFrameParent
pointer to inspector frame parent
FXLabel * myLabelAdditionalParent
Label for additional parent.
FXLabel * myLabelBlockMovement
Label for Check blocked movement.
FXLabel * myLabelBlockShape
Label for Check blocked shape.
FXLabel * myLabelCloseShape
Label for close shape.
FXTextField * myTextFieldAdditionalParent
pointer for change additional parent
Detailed Description
Definition at line 139 of file GNEInspectorFrame.h.
Constructor & Destructor Documentation
NeteditParameters() [1/2]
GNEInspectorFrame::NeteditParameters::NeteditParameters (GNEInspectorFrame * inspectorFrameParent)
FOX-declaration.
constructor
Definition at line 1043 of file GNEInspectorFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignCheckButtonAttribute, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldNCol, MID_GNE_ADDITIONALFRAME_BLOCKMOVEMENT, MID_GNE_ADDITIONALFRAME_CHANGEPARENT, MID_GNE_SET_BLOCKING_SHAPE, MID_GNE_SET_CLOSING_SHAPE, myCheckBoxBlockMovement, myCheckBoxBlockShape, myCheckBoxCloseShape, myHorizontalFrameAdditionalParent, myHorizontalFrameBlockMovement, myHorizontalFrameBlockShape, myHorizontalFrameCloseShape, myLabelAdditionalParent, myLabelBlockMovement, myLabelBlockShape, myLabelCloseShape, and myTextFieldAdditionalParent.
~NeteditParameters()
GNEInspectorFrame::NeteditParameters::~NeteditParameters ()
destructor
Definition at line 1069 of file GNEInspectorFrame.cpp.
NeteditParameters() [2/2]
GNEInspectorFrame::NeteditParameters::NeteditParameters () inline protected
FOX needs this.
Definition at line 173 of file GNEInspectorFrame.h.
Member Function Documentation
hide()
void GNEInspectorFrame::NeteditParameters::hide ()
hide all NeteditParameters
Definition at line 1143 of file GNEInspectorFrame.cpp.
References myHorizontalFrameAdditionalParent, myHorizontalFrameBlockMovement, myHorizontalFrameBlockShape, and myHorizontalFrameCloseShape.
Referenced by GNEInspectorFrame::inspectMultisection().
onCmdChangeAdditionalParent()
long GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent (FXObject * , FXSelector , void *)
Definition at line 1154 of file GNEInspectorFrame.cpp.
References GNEInspectorFrame::getInspectedACs(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNE_ATTR_PARENT, myInspectorFrameParent, and myTextFieldAdditionalParent.
onCmdSetBlockingMovement()
long GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement (FXObject * , FXSelector , void *)
called when user toogle the blocking movement CheckBox
Definition at line 1167 of file GNEInspectorFrame.cpp.
References GNEInspectorFrame::getInspectedACs(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNE_ATTR_BLOCK_MOVEMENT, myCheckBoxBlockMovement, and myInspectorFrameParent.
onCmdSetBlockingShape()
long GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape (FXObject * , FXSelector , void *)
called when user toogle the blocking shape CheckBox
Definition at line 1187 of file GNEInspectorFrame.cpp.
References GNEInspectorFrame::getInspectedACs(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNE_ATTR_BLOCK_SHAPE, myCheckBoxBlockShape, and myInspectorFrameParent.
onCmdSetClosingShape()
long GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape (FXObject * , FXSelector , void *)
called when user toogle the closiong shape CheckBox
Definition at line 1207 of file GNEInspectorFrame.cpp.
References GNEInspectorFrame::getInspectedACs(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNE_ATTR_CLOSE_SHAPE, myCheckBoxCloseShape, and myInspectorFrameParent.
show()
void GNEInspectorFrame::NeteditParameters::show ()
show NeteditParameters
Definition at line 1073 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::canBlockMovement(), GNEAttributeCarrier::canBlockShape(), GNEAdditional::getAdditionalParent(), GNEAttributeCarrier::getID(), GNEInspectorFrame::getInspectedACs(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNE_ATTR_BLOCK_SHAPE, GNE_ATTR_CLOSE_SHAPE, myCheckBoxBlockMovement, myCheckBoxBlockShape, myCheckBoxCloseShape, myHorizontalFrameAdditionalParent, myHorizontalFrameBlockMovement, myHorizontalFrameBlockShape, myHorizontalFrameCloseShape, myInspectorFrameParent, myLabelAdditionalParent, myTextFieldAdditionalParent, and toString().
Referenced by GNEInspectorFrame::inspectMultisection().
Field Documentation
myCheckBoxBlockMovement
FXCheckButton* GNEInspectorFrame::NeteditParameters::myCheckBoxBlockMovement private
pointer to check box "Block movement"
Definition at line 195 of file GNEInspectorFrame.h.
Referenced by NeteditParameters(), onCmdSetBlockingMovement(), and show().
myCheckBoxBlockShape
FXCheckButton* GNEInspectorFrame::NeteditParameters::myCheckBoxBlockShape private
pointer to check box "Block Shape"
Definition at line 204 of file GNEInspectorFrame.h.
Referenced by NeteditParameters(), onCmdSetBlockingShape(), and show().
myCheckBoxCloseShape
FXCheckButton* GNEInspectorFrame::NeteditParameters::myCheckBoxCloseShape private
pointer to check box "Block movement"
Definition at line 213 of file GNEInspectorFrame.h.
Referenced by NeteditParameters(), onCmdSetClosingShape(), and show().
myHorizontalFrameAdditionalParent
FXHorizontalFrame* GNEInspectorFrame::NeteditParameters::myHorizontalFrameAdditionalParent private
horizontal frame for change additional parent
Definition at line 180 of file GNEInspectorFrame.h.
Referenced by hide(), NeteditParameters(), and show().
myHorizontalFrameBlockMovement
FXHorizontalFrame* GNEInspectorFrame::NeteditParameters::myHorizontalFrameBlockMovement private
horizontal frame for block movement
Definition at line 189 of file GNEInspectorFrame.h.
Referenced by hide(), NeteditParameters(), and show().
myHorizontalFrameBlockShape
FXHorizontalFrame* GNEInspectorFrame::NeteditParameters::myHorizontalFrameBlockShape private
horizontal frame for block shape
Definition at line 198 of file GNEInspectorFrame.h.
Referenced by hide(), NeteditParameters(), and show().
myHorizontalFrameCloseShape
FXHorizontalFrame* GNEInspectorFrame::NeteditParameters::myHorizontalFrameCloseShape private
horizontal frame for close shape
Definition at line 207 of file GNEInspectorFrame.h.
Referenced by hide(), NeteditParameters(), and show().
myInspectorFrameParent
GNEInspectorFrame* GNEInspectorFrame::NeteditParameters::myInspectorFrameParent private
pointer to inspector frame parent
Definition at line 177 of file GNEInspectorFrame.h.
Referenced by onCmdChangeAdditionalParent(), onCmdSetBlockingMovement(), onCmdSetBlockingShape(), onCmdSetClosingShape(), and show().
myLabelAdditionalParent
FXLabel* GNEInspectorFrame::NeteditParameters::myLabelAdditionalParent private
Label for additional parent.
Definition at line 183 of file GNEInspectorFrame.h.
Referenced by NeteditParameters(), and show().
myLabelBlockMovement
FXLabel* GNEInspectorFrame::NeteditParameters::myLabelBlockMovement private
Label for Check blocked movement.
Definition at line 192 of file GNEInspectorFrame.h.
Referenced by NeteditParameters().
myLabelBlockShape
FXLabel* GNEInspectorFrame::NeteditParameters::myLabelBlockShape private
Label for Check blocked shape.
Definition at line 201 of file GNEInspectorFrame.h.
Referenced by NeteditParameters().
myLabelCloseShape
FXLabel* GNEInspectorFrame::NeteditParameters::myLabelCloseShape private
Label for close shape.
Definition at line 210 of file GNEInspectorFrame.h.
Referenced by NeteditParameters().
myTextFieldAdditionalParent
FXTextField* GNEInspectorFrame::NeteditParameters::myTextFieldAdditionalParent private
pointer for change additional parent
Definition at line 186 of file GNEInspectorFrame.h.
Referenced by NeteditParameters(), onCmdChangeAdditionalParent(), and show().
The documentation for this class was generated from the following files:
GNEInspectorFrame.h
GNEInspectorFrame.cpp