SUMO - Simulation of Urban MObility: SAXWeightsHandler::EdgeFloatTimeLineRetriever Class Reference
SAXWeightsHandler::EdgeFloatTimeLineRetriever Class Reference abstract
Interface for a class which obtains read weights for named edges.
#include <SAXWeightsHandler.h>
Public Member Functions
virtual void addEdgeWeight (const std::string &id, double val, double beg, double end) const =0
Adds a weight for a given edge and time period.
EdgeFloatTimeLineRetriever ()
Constructor.
virtual ~EdgeFloatTimeLineRetriever ()
Destructor.
Private Member Functions
EdgeFloatTimeLineRetriever & operator= (const EdgeFloatTimeLineRetriever &)
Detailed Description
Interface for a class which obtains read weights for named edges.
Definition at line 81 of file SAXWeightsHandler.h.
Constructor & Destructor Documentation
EdgeFloatTimeLineRetriever()
SAXWeightsHandler::EdgeFloatTimeLineRetriever::EdgeFloatTimeLineRetriever () inline
Constructor.
Definition at line 84 of file SAXWeightsHandler.h.
~EdgeFloatTimeLineRetriever()
virtual SAXWeightsHandler::EdgeFloatTimeLineRetriever::~EdgeFloatTimeLineRetriever () inline virtual
Destructor.
Definition at line 87 of file SAXWeightsHandler.h.
References addEdgeWeight(), and operator=().
Member Function Documentation
addEdgeWeight()
virtual void SAXWeightsHandler::EdgeFloatTimeLineRetriever::addEdgeWeight (const std::string & id, double val, double beg, double end) const pure virtual
Adds a weight for a given edge and time period.
Parameters
[in] id The id of the object to add a weight for
[in] val The weight
[in] beg The begin of the interval the weight is valid for
[in] end The end of the interval the weight is valid for
Implemented in NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime, ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime, NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort, and ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight.
Referenced by ~EdgeFloatTimeLineRetriever().
operator=()
EdgeFloatTimeLineRetriever& SAXWeightsHandler::EdgeFloatTimeLineRetriever::operator= (const EdgeFloatTimeLineRetriever &) private
Referenced by ~EdgeFloatTimeLineRetriever().
The documentation for this class was generated from the following file:
SAXWeightsHandler.h