SUMO - Simulation of Urban MObility: NIImporter_OpenStreetMap::Edge Struct Reference
NIImporter_OpenStreetMap::Edge Struct Reference
An internal definition of a loaded edge.
#include <NIImporter_OpenStreetMap.h>
Public Member Functions
void clearParameter ()
Clears the parameter map.
Edge (long long int _id)
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Data Fields
const long long int id
The edge's id.
WayType myBuswayType
Information about the kind of busway along this road.
bool myCurrentIsPlatform
Information whether this is a pt platform.
bool myCurrentIsRoad
Information whether this is a road.
std::vector< long long int > myCurrentNodes
The list of nodes this edge is made of.
WayType myCyclewayType
Information about the kind of cycleway along this road.
std::string myHighWayType
The type, stored in "highway" key.
std::string myIsOneWay
Information whether this is an one-way road.
int myLayer
Information about the relative z-ordering of ways.
double myMaxSpeed
maximum speed in km/h, or MAXSPEED_UNGIVEN
int myNoLanes
number of lanes, or -1 if unknown
int myNoLanesForward
number of lanes in forward direction or 0 if unknown, negative if backwards lanes are meant
int myParkingType
Information about road-side parking.
std::string streetName
The edge's street name.
Private Member Functions
Edge & operator= (const Edge &s)=delete
invalidated assignment operator
Detailed Description
An internal definition of a loaded edge.
Definition at line 147 of file NIImporter_OpenStreetMap.h.
Constructor & Destructor Documentation
Edge()
NIImporter_OpenStreetMap::Edge::Edge (long long int _id) inline explicit
Definition at line 149 of file NIImporter_OpenStreetMap.h.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
operator=()
Edge& NIImporter_OpenStreetMap::Edge::operator= (const Edge & s) private delete
invalidated assignment operator
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
id
const long long int NIImporter_OpenStreetMap::Edge::id
The edge's id.
Definition at line 161 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::load(), NIImporter_OpenStreetMap::EdgesHandler::myEndElement(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
myBuswayType
WayType NIImporter_OpenStreetMap::Edge::myBuswayType
Information about the kind of busway along this road.
Definition at line 177 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
myCurrentIsPlatform
bool NIImporter_OpenStreetMap::Edge::myCurrentIsPlatform
Information whether this is a pt platform.
Definition at line 187 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::EdgesHandler::myEndElement(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
myCurrentIsRoad
bool NIImporter_OpenStreetMap::Edge::myCurrentIsRoad
Information whether this is a road.
Definition at line 185 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::load(), NIImporter_OpenStreetMap::EdgesHandler::myEndElement(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
myCurrentNodes
std::vector<long long int> NIImporter_OpenStreetMap::Edge::myCurrentNodes
The list of nodes this edge is made of.
Definition at line 183 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::load(), NIImporter_OpenStreetMap::RelationHandler::myEndElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::CompareEdges::operator()(), and NIImporter_OpenStreetMap::reconstructLayerElevation().
myCyclewayType
WayType NIImporter_OpenStreetMap::Edge::myCyclewayType
Information about the kind of cycleway along this road.
Definition at line 175 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
myHighWayType
std::string NIImporter_OpenStreetMap::Edge::myHighWayType
The type, stored in "highway" key.
Definition at line 171 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
myIsOneWay
std::string NIImporter_OpenStreetMap::Edge::myIsOneWay
Information whether this is an one-way road.
Definition at line 173 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
myLayer
int NIImporter_OpenStreetMap::Edge::myLayer
Information about the relative z-ordering of ways.
Definition at line 181 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::reconstructLayerElevation().
myMaxSpeed
double NIImporter_OpenStreetMap::Edge::myMaxSpeed
maximum speed in km/h, or MAXSPEED_UNGIVEN
Definition at line 169 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
myNoLanes
int NIImporter_OpenStreetMap::Edge::myNoLanes
number of lanes, or -1 if unknown
Definition at line 165 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
myNoLanesForward
int NIImporter_OpenStreetMap::Edge::myNoLanesForward
number of lanes in forward direction or 0 if unknown, negative if backwards lanes are meant
Definition at line 167 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
myParkingType
int NIImporter_OpenStreetMap::Edge::myParkingType
Information about road-side parking.
Definition at line 179 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
streetName
std::string NIImporter_OpenStreetMap::Edge::streetName
The edge's street name.
Definition at line 163 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::insertEdge(), and NIImporter_OpenStreetMap::EdgesHandler::myStartElement().
The documentation for this struct was generated from the following file:
NIImporter_OpenStreetMap.h