SUMO - Simulation of Urban MObility: RouterProvider< E, L, N, V > Class Template Reference
RouterProvider< E, L, N, V > Class Template Reference
#include <IntermodalRouter.h>
Public Member Functions
IntermodalRouter< E, L, N, V > & getIntermodalRouter () const
PedestrianRouterDijkstra< E, L, N, V > & getPedestrianRouter () const
SUMOAbstractRouter< E, V > & getVehicleRouter () const
RouterProvider (SUMOAbstractRouter< E, V > *vehRouter, PedestrianRouterDijkstra< E, L, N, V > *pedRouter, IntermodalRouter< E, L, N, V > *interRouter)
RouterProvider (const RouterProvider &original)
virtual ~RouterProvider ()
Private Member Functions
RouterProvider & operator= (const RouterProvider &src)
Invalidated assignment operator.
Private Attributes
IntermodalRouter< E, L, N, V > *const myInterRouter
PedestrianRouterDijkstra< E, L, N, V > *const myPedRouter
SUMOAbstractRouter< E, V > *const myVehRouter
Detailed Description
template<class E, class L, class N, class V>
class RouterProvider< E, L, N, V >
The encapsulation of the routers for vehicles and pedestrians
Definition at line 540 of file IntermodalRouter.h.
Constructor & Destructor Documentation
RouterProvider() [1/2]
template<class E , class L , class N , class V > RouterProvider< E, L, N, V >::RouterProvider (SUMOAbstractRouter< E, V > * vehRouter, PedestrianRouterDijkstra< E, L, N, V > * pedRouter, IntermodalRouter< E, L, N, V > * interRouter) inline
Definition at line 542 of file IntermodalRouter.h.
RouterProvider() [2/2]
template<class E , class L , class N , class V > RouterProvider< E, L, N, V >::RouterProvider (const RouterProvider< E, L, N, V > & original) inline
Definition at line 547 of file IntermodalRouter.h.
~RouterProvider()
template<class E , class L , class N , class V > virtual RouterProvider< E, L, N, V >::~RouterProvider () inline virtual
Definition at line 564 of file IntermodalRouter.h.
Member Function Documentation
getIntermodalRouter()
template<class E , class L , class N , class V > IntermodalRouter<E, L, N, V>& RouterProvider< E, L, N, V >::getIntermodalRouter () const inline
Definition at line 560 of file IntermodalRouter.h.
Referenced by ROPerson::computeIntermodal(), computeRoutes(), and RONet::saveAndRemoveRoutesUntil().
getPedestrianRouter()
template<class E , class L , class N , class V > PedestrianRouterDijkstra<E, L, N, V>& RouterProvider< E, L, N, V >::getPedestrianRouter () const inline
Definition at line 556 of file IntermodalRouter.h.
getVehicleRouter()
template<class E , class L , class N , class V > SUMOAbstractRouter<E, V>& RouterProvider< E, L, N, V >::getVehicleRouter () const inline
Definition at line 552 of file IntermodalRouter.h.
Referenced by ROVehicle::computeRoute(), and RONet::createBulkRouteRequests().
operator=()
template<class E , class L , class N , class V > RouterProvider& RouterProvider< E, L, N, V >::operator= (const RouterProvider< E, L, N, V > & src) private
Invalidated assignment operator.
Field Documentation
myInterRouter
template<class E , class L , class N , class V > IntermodalRouter<E, L, N, V>* const RouterProvider< E, L, N, V >::myInterRouter private
Definition at line 574 of file IntermodalRouter.h.
myPedRouter
template<class E , class L , class N , class V > PedestrianRouterDijkstra<E, L, N, V>* const RouterProvider< E, L, N, V >::myPedRouter private
Definition at line 573 of file IntermodalRouter.h.
myVehRouter
template<class E , class L , class N , class V > SUMOAbstractRouter<E, V>* const RouterProvider< E, L, N, V >::myVehRouter private
Definition at line 572 of file IntermodalRouter.h.
The documentation for this class was generated from the following file:
IntermodalRouter.h