SUMO - Simulation of Urban MObility: NBHelpers Class Reference
NBHelpers Class Reference
#include <NBHelpers.h>
Static Public Member Functions
static double distance (NBNode *node1, NBNode *node2)
returns the distance between both nodes
static void interpretLaneID (const std::string &lane_id, std::string &edge_id, int &index)
parses edge-id and index from lane-id
static void loadEdgesFromFile (const std::string &file, std::set< std::string > &into)
Add edge ids defined in file (either ID or edge:ID per line) into the given set.
static void loadPrefixedIDsFomFile (const std::string &file, const std::string prefix, std::set< std::string > &into)
Add prefixed ids defined in file.
static std::string normalIDRepresentation (const std::string &id)
converts the numerical id to its "normal" string representation
static double normRelAngle (double angle1, double angle2)
ensure that reverse relAngles (>=179.999) always count as turnarounds (-180)
static double relAngle (double angle1, double angle2)
computes the relative angle between the two angles
Detailed Description
Some mathmatical methods for the computation of angles
Definition at line 53 of file NBHelpers.h.
Member Function Documentation
distance()
double NBHelpers::distance (NBNode * node1, NBNode * node2) static
returns the distance between both nodes
Definition at line 88 of file NBHelpers.cpp.
References Position::distanceTo(), and NBNode::getPosition().
interpretLaneID()
void NBHelpers::interpretLaneID (const std::string & lane_id, std::string & edge_id, int & index) static
parses edge-id and index from lane-id
Parameters
[in] lane_id The lane-id
[out] edge_id ID of this lane's edge
[out] index Index of this lane
Definition at line 127 of file NBHelpers.cpp.
References TplConvert::_2int(), and WRITE_ERROR.
Referenced by NIImporter_SUMO::getLaneAttrsFromID(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), and NWWriter_SUMO::writeNetwork().
loadEdgesFromFile()
void NBHelpers::loadEdgesFromFile (const std::string & file, std::set< std::string > & into) static
Add edge ids defined in file (either ID or edge:ID per line) into the given set.
Definition at line 94 of file NBHelpers.cpp.
References StringUtils::startsWith().
Referenced by NBEdgeCont::applyOptions(), and NBNodeCont::removeUnwishedNodes().
loadPrefixedIDsFomFile()
void NBHelpers::loadPrefixedIDsFomFile (const std::string & file, const std::string prefix, std::set< std::string > & into) static
Add prefixed ids defined in file.
Definition at line 112 of file NBHelpers.cpp.
References StringUtils::startsWith().
Referenced by NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeProhibitedManoeuvres().
normalIDRepresentation()
std::string NBHelpers::normalIDRepresentation (const std::string & id) static
converts the numerical id to its "normal" string representation
Definition at line 77 of file NBHelpers.cpp.
Referenced by NIImporter_VISUM::getNamedEdge(), NIImporter_VISUM::getNamedEdgeContinuating(), NIImporter_VISUM::getNamedNode(), NIImporter_VISUM::getNamedString(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_Districts(), NIImporter_VISUM::parse_Edges(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Nodes(), NIImporter_VISUM::parse_Phases(), NIImporter_VISUM::parse_SignalGroups(), NIImporter_VISUM::parse_SignalGroupsToPhases(), NIImporter_VISUM::parse_TrafficLights(), and NIImporter_VISUM::parse_Types().
normRelAngle()
double NBHelpers::normRelAngle (double angle1, double angle2) static
ensure that reverse relAngles (>=179.999) always count as turnarounds (-180)
Definition at line 66 of file NBHelpers.cpp.
References NUMERICAL_EPS, and relAngle().
Referenced by NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NBNode::getDirection(), NBContHelper::same_connection_edge_sorter::getMinMaxRelAngles(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::straightness_sorter::operator()(), and NBContHelper::relative_incoming_edge_sorter::operator()().
relAngle()
double NBHelpers::relAngle (double angle1, double angle2) static
computes the relative angle between the two angles
Definition at line 53 of file NBHelpers.cpp.
Referenced by NBNode::buildCrossings(), NBOwnTLDef::computeLogicAndConts(), NBNodeShapeComputer::computeNodeShapeDefault(), NBRampsComputer::fulfillsRampConstraints(), NBNode::geometryLike(), NBEdgeCont::guessRoundabouts(), NBRequest::laneConflict(), and normRelAngle().
The documentation for this class was generated from the following files:
NBHelpers.h
NBHelpers.cpp