SUMO - Simulation of Urban MObility: NBEdge::Lane Struct Reference
NBEdge::Lane Struct Reference
An (internal) definition of a single lane of an edge.
#include <NBEdge.h>
Public Member Functions
void clearParameter ()
Clears the parameter map.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
Lane (NBEdge *e, const std::string &_origID)
constructor
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Data Fields
bool accelRamp
Whether this lane is an acceleration lane.
bool connectionsDone
Whether connection information for this lane is already completed.
PositionVector customShape
A custom shape for this lane set by the user.
double endOffset
This lane's offset to the intersection begin.
std::string oppositeID
An opposite lane ID, if given.
SVCPermissions permissions
List of vehicle types that are allowed on this lane.
SVCPermissions preferred
List of vehicle types that are preferred on this lane.
PositionVector shape
The lane's shape.
double speed
The speed allowed on this lane.
double width
This lane's width.
Detailed Description
An (internal) definition of a single lane of an edge.
Definition at line 121 of file NBEdge.h.
Constructor & Destructor Documentation
Lane()
NBEdge::Lane::Lane (NBEdge * e, const std::string & _origID)
constructor
Definition at line 125 of file NBEdge.cpp.
References Parameterised::setParameter(), and SUMO_PARAM_ORIGID.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
accelRamp
bool NBEdge::Lane::accelRamp
Whether this lane is an acceleration lane.
Definition at line 147 of file NBEdge.h.
Referenced by GNELane::getAttribute(), NBEdge::getTypeID(), NWWriter_SUMO::writeEdge(), and NWWriter_XML::writeEdgesAndConnections().
connectionsDone
bool NBEdge::Lane::connectionsDone
Whether connection information for this lane is already completed.
Definition at line 151 of file NBEdge.h.
Referenced by NBNode::computeLanes2Lanes(), NBNodeCont::joinNodeClusters(), and NIImporter_DlrNavteq::ConnectedLanesHandler::report().
customShape
PositionVector NBEdge::Lane::customShape
A custom shape for this lane set by the user.
Definition at line 154 of file NBEdge.h.
Referenced by GNELane::getAttribute(), NBEdge::getLaneSpreadFunction(), NWWriter_SUMO::writeEdge(), and NWWriter_XML::writeEdgesAndConnections().
endOffset
double NBEdge::Lane::endOffset
This lane's offset to the intersection begin.
Definition at line 138 of file NBEdge.h.
Referenced by GNEEdge::addLane(), NBNode::computeInternalLaneShape(), GNELane::getAttribute(), NWWriter_SUMO::writeEdge(), and NWWriter_XML::writeEdgesAndConnections().
oppositeID
std::string NBEdge::Lane::oppositeID
An opposite lane ID, if given.
Definition at line 144 of file NBEdge.h.
Referenced by NIImporter_SUMO::_loadNetwork(), NWWriter_SUMO::getOppositeInternalID(), NBEdgeCont::guessOpposites(), NWWriter_SUMO::writeEdge(), and NWWriter_XML::writeEdgesAndConnections().
permissions
SVCPermissions NBEdge::Lane::permissions
List of vehicle types that are allowed on this lane.
Definition at line 132 of file NBEdge.h.
Referenced by GNEEdge::addLane(), NBNode::buildWalkingAreas(), NBEdge::getTypeID(), NIImporter_OpenDrive::loadNetwork(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_SUMO::writeInternalEdges().
preferred
SVCPermissions NBEdge::Lane::preferred
List of vehicle types that are preferred on this lane.
Definition at line 135 of file NBEdge.h.
Referenced by GNEEdge::addLane(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_SUMO::writeInternalEdges().
shape
PositionVector NBEdge::Lane::shape
The lane's shape.
Definition at line 126 of file NBEdge.h.
Referenced by NBNode::buildCrossings(), NBNode::buildWalkingAreas(), NBNode::computeInternalLaneShape(), GNELane::getBoundary(), NBEdge::getTypeID(), NBEdgeCont::guessOpposites(), and NWWriter_SUMO::writeEdge().
speed
double NBEdge::Lane::speed
The speed allowed on this lane.
Definition at line 129 of file NBEdge.h.
Referenced by GNEEdge::addLane(), NBEdge::getLaneSpreadFunction(), NBEdge::getTypeID(), NIImporter_OpenDrive::loadNetwork(), NWWriter_SUMO::writeEdge(), and NWWriter_XML::writeEdgesAndConnections().
width
double NBEdge::Lane::width
This lane's width.
Definition at line 141 of file NBEdge.h.
Referenced by GNEEdge::addLane(), NBNode::buildCrossings(), NBNode::buildWalkingAreas(), GNELane::drawGL(), GNELane::getAttribute(), NBEdge::getTypeID(), NIImporter_OpenDrive::loadNetwork(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_SUMO::writeInternalEdges().
The documentation for this struct was generated from the following files:
NBEdge.h
NBEdge.cpp