SUMO - Simulation of Urban MObility: GNEPOILane Class Reference
GNEPOILane Class Reference
#include <GNEPOILane.h>
Public Member Functions
void add (const Position &pos)
Adds the given position to this one.
void add (double dx, double dy)
Adds the given position to this one.
void add (double dx, double dy, double dz)
Adds the given position to this one.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool almostSame (const Position &p2, double maxDiv=POSITION_EPS) const
checki if two position is almost the sme as other
double angleTo2D (const Position &other) const
returns the angle in the plane of the vector pointing from here to the other position
void clearParameter ()
Clears the parameter map.
void commitGeometryMoving (const Position &oldPos, GNEUndoList *undoList)
commit geometry changes in the attributes of an element after use of moveGeometry(...)
Position crossProduct (const Position &pos)
returns the cross product between this point and the second one
void decRef (const std::string &debugMsg="")
Decrease reference.
double distanceSquaredTo (const Position &p2) const
returns the square of the distance to another position
double distanceSquaredTo2D (const Position &p2) const
returns the square of the distance to another position (Only using x and y positions)
double distanceTo (const Position &p2) const
returns the euclidean distance in 3 dimension
double distanceTo2D (const Position &p2) const
returns the euclidean distance in the x-y-plane
double dotProduct (const Position &pos)
returns the dot product (scalar product) between this point and the second one
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawLockIcon (const Position &pos, double layer, double size=0.5) const
draw lock icon
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
virtual std::string getAttributeForSelection (SumoXMLAttr key) const
method for getting the attribute in the context of object selection
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
double getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleClass getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOVehicleShape getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
RGBColor getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< double > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const GUIGlObject * getGUIGLObject () const
get const pointer to GUIGlObject vinculated with this Attribute Carrier
GUIGlObject * getGUIGLObject ()
get pointer to GUIGlObject vinculated with this Attribute Carrier
GUIIcon getGUIIcon () const
get GUI icon assigned to this object
FXIcon * getIcon () const
get FXIcon assigned to this object
const std::string & getID () const
Returns the id.
const std::string getID () const
function to support debugging
GNELane * getLane () const
get GNELane
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
GNENet * getNet () const
get Net in which this element is placed
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
SumoXMLTag getTag () const
get XML Tag assigned to this object
GNEPOILane (GNENet *net, const std::string &id, const std::string &type, const RGBColor &color, double layer, double angle, const std::string &imgFile, GNELane *lane, double posOverLane, double posLat, double width, double height, bool movementBlocked)
Constructor.
void incRef (const std::string &debugMsg="")
Increarse reference.
bool isMovementBlocked () const
return true if movement is blocked
bool isShapeBlocked () const
return true if shape is blocked
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void moveGeometry (const Position &oldPos, const Position &offset)
change the position of the element geometry without saving in undoList
void mul (double val)
Multiplies both positions with the given value.
void mul (double mx, double my)
Multiplies position with the given values.
void mul (double mx, double my, double mz)
Multiplies position with the given values.
void norm2d ()
bool operator!= (const Position &p2) const
difference operator
Position operator* (double scalar) const
keep the direction but modify the length of the (location) vector to length * scalar
Position operator+ (const Position &p2) const
add operator
Position operator+ (double offset) const
keep the direction but modify the length of the (location) vector to length + scalar
Position operator- (const Position &p2) const
sub operator
bool operator< (const Position &p2) const
lexicographical sorting for use in maps and sets
bool operator== (const Position &p2) const
comparation operator
template<>
int parse (const std::string &string)
template<>
double parse (const std::string &string)
template<>
bool parse (const std::string &string)
template<>
std::string parse (const std::string &string)
template<>
SUMOVehicleClass parse (const std::string &string)
template<>
RGBColor parse (const std::string &string)
template<>
SUMOVehicleShape parse (const std::string &string)
template<>
std::vector< std::string > parse (const std::string &string)
template<>
std::vector< int > parse (const std::string &string)
template<>
std::vector< double > parse (const std::string &string)
template<>
std::vector< bool > parse (const std::string &string)
void set (double x, double y)
set positions x and y
void set (double x, double y, double z)
set positions x, y and z
void set (const Position &pos)
set position with another position
void setID (const std::string &newID)
resets the id
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void setx (double x)
set position x
void sety (double y)
set position y
void setz (double z)
set position z
void sub (double dx, double dy)
Substracts the given position from this one.
void sub (double dx, double dy, double dz)
Substracts the given position from this one.
void sub (const Position &pos)
Substracts the given position from this one.
bool unreferenced ()
check if object ins't referenced
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
void writeXML (OutputDevice &out, const bool geo=false, const double zOffset=0., const std::string laneID="", const double pos=0., const double posLat=0.)
double x () const
Returns the x-position.
double y () const
Returns the y-position.
double z () const
Returns the z-position.
~GNEPOILane ()
Destructor.
inherited from GNEShape
update pre-computed geometry information
void updateGeometry ()
update pre-computed geometry information
void writeShape (OutputDevice &device)
writte shape element into a xml file
Position getPositionInView () const
Returns position of additional in view.
GUIGlID getGlID () const
Returns the numerical id of the object.
inherited from GUIGlObject
const std::string & getParentName () const
Returns the name of the parent object.
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GNEAttributeCarrier
std::string getAttribute (SumoXMLAttr key) const
method for getting the Attribute of an XML key
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
method for setting the attribute and letting the object perform additional changes
bool isValid (SumoXMLAttr key, const std::string &value)
method for checking if the key and their correspond attribute are valids
Getter
double getWidth () const
Returns the image width of the POI.
double getHeight () const
Returns the image height of the POI.
Setter
void setWidth (double width)
set the image width of the POI
void setHeight (double height)
set the image height of the POI
Getter
const std::string & getType () const
Returns the (abstract) type of the Shape.
const RGBColor & getColor () const
Returns the color of the Shape.
double getLayer () const
Returns the layer of the Shape.
double getNaviDegree () const
Returns the angle of the Shape in navigational degrees.
const std::string & getImgFile () const
Returns the imgFile of the Shape.
interfaces to be implemented by derived classes
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
Setter
void setType (const std::string &type)
Sets a new type.
void setColor (const RGBColor &col)
Sets a new color.
void setLayer (const double layer)
Sets a new layer.
void setNaviDegree (const double angle)
Sets a new angle in navigational degrees.
void setImgFile (const std::string &imgFile)
Sets a new imgFile.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static const std::vector< SumoXMLTag > & allowedAdditionalTags ()
get all editable for tag additional elements
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedNetElementsTags ()
get all editable for tag net elements
static const std::vector< SumoXMLTag > & allowedShapeTags ()
get all editable for tag shape elements
static std::vector< SumoXMLTag > allowedTags ()
get all editable for tag elements of all types
static bool canBlockMovement (SumoXMLTag tag)
return true if element tag can block their movement
static bool canBlockShape (SumoXMLTag tag)
return true if element tag can block their shape
static bool canOpenDialog (SumoXMLTag tag)
return true if element tag can open a values editor
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::string getAttributeType (SumoXMLTag tag, SumoXMLAttr attr)
get type of attribute
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static std::vector< GUIGlID > getIDList (int typeFilter)
Returns the list of gl-ids of all additional objects that match the given type.
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static const std::vector< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if an element with certain tag has a certain attribute
static bool hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
check if attribute of an element has a default avlue
static const Position & invalidPosition ()
reference to invalid position (needed if INVALID is taken by macro-definition)
static bool isBool (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool for a certain tag
static bool isColor (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type color for a certain tag
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFilename (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a filename
static bool isFloat (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNonEditable (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is non editable
static bool isNumerical (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is numerical (int or float)
static bool isPositive (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is only Positive (i.e. cannot take negative values)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isProbability (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is a probability (i.e. oly can values between [0, 1])
static bool isString (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is of type string
static bool isTime (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is time
static bool isUnique (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
static bool isValidFilename (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
static bool isVClass (SumoXMLTag tag, SumoXMLAttr attr)
whether a string attribute is a list of Vehicle Classes
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
template<typename T >
static T parseAttributeFromXML (const SUMOSAXAttributes &attrs, const std::string &objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool &abort, bool report=true)
Parse attribute from XML and show warnings if there are problems parsing it.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
function used to parse GNEEdges and GNELanes
static bool checkGNEEdgesValid (GNENet *net, const std::string &value, bool report)
check if a list of edge IDs is valid
static bool checkGNELanesValid (GNENet *net, const std::string &value, bool report)
check if a list of Lane IDs is valid
static std::vector< GNEEdge * > parseGNEEdges (GNENet *net, const std::string &value)
parse string into vector of GNEEdges
static std::string parseGNEEdges (const std::vector< GNEEdge *> &edges)
parse vector of GNEEdges into string
static std::vector< GNELane * > parseGNELanes (GNENet *net, const std::string &value)
parse string into vector of GNELanes
static std::string parseGNELanes (const std::vector< GNELane *> &lanes)
parse vector of GNELanes into string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const double DEFAULT_ANGLE = 0
static const std::string DEFAULT_IMG_FILE = ""
static const double DEFAULT_IMG_HEIGHT = 1
static const double DEFAULT_IMG_WIDTH = 1
static const double DEFAULT_LAYER = 128
static const std::string DEFAULT_TYPE = ""
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const Position INVALID
used to indicate that a position is valid
static const GUIGlID INVALID_ID = 0
static const double INVALID_POSITION = -1000000
default value for invalid positions (used by POIs and Polygons)
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
bool myBlockMovement
flag to block movement
bool myBlockShape
flag for block shape
RGBColor myColor
The color of the Shape.
bool myGeo
flag to check if POI was loaded as GEO Position (main used by netedit)
GNELane * myGNELane
GNElane in which this POILane is placed.
double myHalfImgHeight
The half height of the image when rendering this POI.
double myHalfImgWidth
The half width of the image when rendering this POI.
std::string myID
The name of the object.
std::string myImgFile
The angle of the Shape.
std::string myLane
ID of lane in which this POI is placed (main used by netedit)
double myLayer
The layer of the Shape.
double myNaviDegreeAngle
The angle of the Shape.
GNENet * myNet
the net to inform about updates
double myPosLat
latereal position over lane in which this POI is placed (main used by netedit)
double myPosOverLane
position over lane in which this POI is placed (main used by netedit)
std::string myType
The type of the Shape.
Static Protected Attributes
static std::vector< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string, GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Member Functions
GNEPOILane (const GNEPOILane &)=delete
Invalidated copy constructor.
GNEPOILane & operator= (const GNEPOILane &)=delete
Invalidated assignment operator.
void setAttribute (SumoXMLAttr key, const std::string &value)
set attribute after validation
Detailed Description
Definition at line 50 of file GNEPOILane.h.
Constructor & Destructor Documentation
GNEPOILane() [1/2]
GNEPOILane::GNEPOILane (GNENet * net, const std::string & id, const std::string & type, const RGBColor & color, double layer, double angle, const std::string & imgFile, GNELane * lane, double posOverLane, double posLat, double width, double height, bool movementBlocked)
Constructor.
Parameters
[in] net net in which this polygon is placed
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] layer The layer of the POI
[in] angle The rotation of the POI
[in] imgFile The raster image of the shape
[in] lane lane in which tis POILane is placed
[in] posOverLane Position over lane in which this POILane is placed
[in] posLat Lateral position over lane
[in] width The width of the POI image
[in] height The height of the POI image
[in] movementBlocked if movement of POI is blocked
Definition at line 64 of file GNEPOILane.cpp.
~GNEPOILane()
GNEPOILane::~GNEPOILane ()
Destructor.
Definition at line 73 of file GNEPOILane.cpp.
GNEPOILane() [2/2]
GNEPOILane::GNEPOILane (const GNEPOILane &) private delete
Invalidated copy constructor.
Member Function Documentation
add() [1/3]
void Position::add (const Position & pos) inline inherited
Adds the given position to this one.
Definition at line 132 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeNodeShapeDefault(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GUIEdge::drawGL(), GNEEdge::drawGL(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), GeoConvHelper::moveConvertedBy(), GNEDetectorE3::moveGeometry(), GNEPOI::moveGeometry(), GNEDetector::moveGeometry(), moveGeometry(), GNEStoppingPlace::moveGeometry(), GNEVariableSpeedSign::moveGeometry(), GNERerouter::moveGeometry(), GNEJunction::moveGeometry(), NBDistrict::reshiftPosition(), NBNode::reshiftPosition(), NBPTStop::reshiftPostion(), GUISUMOAbstractView::showToolTipFor(), and GeoConvHelper::x2cartesian_const().
add() [2/3]
void Position::add (double dx, double dy) inline inherited
Adds the given position to this one.
Definition at line 139 of file Position.h.
References Position::myX, and Position::myY.
add() [3/3]
void Position::add (double dx, double dy, double dz) inline inherited
Adds the given position to this one.
Definition at line 145 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
addTo()
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 128 of file Named.h.
References Named::StoringVisitor::add().
allowedAdditionalTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedAdditionalTags () static inherited
get all editable for tag additional elements
Definition at line 621 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedAttributes()
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 287 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, OptionsCont::getOptions(), GNE_ATTR_SHAPE_END, GNE_ATTR_SHAPE_START, NODEFAULTVALUE, SUMO_ATTR_ACCEL, SUMO_ATTR_ACCELERATION, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPE, toString(), NBEdge::UNSPECIFIED_CONTPOS, NBEdge::UNSPECIFIED_SPEED, and NBEdge::UNSPECIFIED_VISIBILITY_DISTANCE.
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getDefaultValue(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNESelectorFrame::onCmdSelMBAttribute(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedNetElementsTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedNetElementsTags () static inherited
get all editable for tag net elements
Definition at line 607 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedShapeTags()
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedShapeTags () static inherited
get all editable for tag shape elements
Definition at line 644 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedShapeTags, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_POLY.
Referenced by GNEAttributeCarrier::allowedTags(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEPolygonFrame::GNEPolygonFrame(), GNEPolygonFrame::onCmdSelectShape(), GNESelectorFrame::onCmdSelMBTag(), GNESelectorFrame::onCmdSubset(), and GNEAttributeCarrier::~GNEAttributeCarrier().
allowedTags()
std::vector< SumoXMLTag > GNEAttributeCarrier::allowedTags () static inherited
get all editable for tag elements of all types
Definition at line 596 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedNetElementsTags(), and GNEAttributeCarrier::allowedShapeTags().
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
almostSame()
bool Position::almostSame (const Position & p2, double maxDiv = POSITION_EPS) const inline inherited
checki if two position is almost the sme as other
Definition at line 234 of file Position.h.
References Position::distanceTo().
Referenced by GNEViewNet::begingMoveSelection(), PositionVector::insert_noDoublePos(), AGPosition::operator==(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
angleTo2D()
double Position::angleTo2D (const Position & other) const inline inherited
returns the angle in the plane of the vector pointing from here to the other position
Definition at line 259 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), NBEdge::computeAngle(), GUIBusStop::drawGL(), GLHelper::drawTriangleAtEnd(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), PositionVector::rotationAtOffset(), and NWWriter_OpenDrive::writeGeomSmooth().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
canBlockMovement()
bool GNEAttributeCarrier::canBlockMovement (SumoXMLTag tag) static inherited
return true if element tag can block their movement
Definition at line 656 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockMovementTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::onCmdSelectAdditional(), GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canBlockShape()
bool GNEAttributeCarrier::canBlockShape (SumoXMLTag tag) static inherited
return true if element tag can block their shape
Definition at line 678 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBlockShapeTags, and SUMO_TAG_POLY.
Referenced by GNEInspectorFrame::NeteditParameters::show(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canOpenDialog()
bool GNEAttributeCarrier::canOpenDialog (SumoXMLTag tag) static inherited
return true if element tag can open a values editor
Definition at line 688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myDialogTags, SUMO_TAG_CALIBRATOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_REROUTER, and SUMO_TAG_VSS.
Referenced by GNEAdditional::getPopUpMenu(), GNEViewNet::onCmdOpenAdditionalDialog(), and GNEAttributeCarrier::~GNEAttributeCarrier().
canParse()
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 230 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
checkGNEEdgesValid()
bool GNEAttributeCarrier::checkGNEEdgesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of edge IDs is valid
value string with a list of edges report enable or disable show warning if edges aren't valid
Definition at line 1712 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge(), SUMO_ATTR_EDGES, SUMO_TAG_EDGE, toString(), and WRITE_WARNING.
Referenced by GNECalibratorRoute::isValid(), GNECrossing::isValid(), GNERerouter::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), and GNEAttributeCarrier::parseAttributeFromXML().
checkGNELanesValid()
bool GNEAttributeCarrier::checkGNELanesValid (GNENet * net, const std::string & value, bool report) static inherited
check if a list of Lane IDs is valid
value string with a list of lanes report enable or disable show warning if lanes aren't valid
Definition at line 1730 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane(), SUMO_ATTR_LANES, SUMO_TAG_LANE, toString(), and WRITE_WARNING.
Referenced by GNEVariableSpeedSign::isValid(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), and GNEAttributeCarrier::parseAttributeFromXML().
clearDictionary()
void GUIGlObject_AbstractAdd::clearDictionary () static inherited
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 60 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
commitGeometryMoving()
void GNEPOILane::commitGeometryMoving (const Position & oldPos, GNEUndoList * undoList)
commit geometry changes in the attributes of an element after use of moveGeometry(...)
Parameters
[in] oldPos the old position of additional
[in] undoList The undoList on which to register changes
Definition at line 97 of file GNEPOILane.cpp.
References GNELane::getLaneParametricLength(), GNELane::getShape(), GNEAttributeCarrier::getTag(), GNEAttributeCarrier::GNEChange_Attribute, GNEShape::myBlockMovement, myGNELane, PointOfInterest::myPosOverLane, PositionVector::nearest_offset_to_point2D(), GNEUndoList::p_add(), GNEUndoList::p_begin(), GNEUndoList::p_end(), SUMO_ATTR_POSITION, and toString().
Referenced by GNEViewNet::onLeftBtnRelease().
crossProduct()
Position Position::crossProduct (const Position & pos) inline inherited
returns the cross product between this point and the second one
Definition at line 264 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Referenced by NBHeightMapper::Triangle::normalVector().
decRef()
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Decrease reference.
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
discreteChoices()
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 1233 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_GUISHAPE, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TLTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_VCLASS, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_VTYPE, SumoVehicleClassStrings, SumoVehicleShapeStrings, TLTYPE_INVALID, toString(), and SUMOXMLDefinitions::TrafficLightTypes.
Referenced by GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
discreteCombinableChoices()
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 1290 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
distanceSquaredTo()
double Position::distanceSquaredTo (const Position & p2) const inline inherited
returns the square of the distance to another position
Definition at line 244 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by Position::distanceTo().
distanceSquaredTo2D()
double Position::distanceSquaredTo2D (const Position & p2) const inline inherited
returns the square of the distance to another position (Only using x and y positions)
Definition at line 254 of file Position.h.
References Position::myX, and Position::myY.
Referenced by Position::distanceTo2D(), and NBPTStopCont::getClosestPlatformToPTStopPosition().
distanceTo()
double Position::distanceTo (const Position & p2) const inline inherited
returns the euclidean distance in 3 dimension
Definition at line 239 of file Position.h.
References Position::distanceSquaredTo().
Referenced by Position::almostSame(), GNEViewNet::begingMoveSelection(), TraCIServerAPI_Simulation::commandDistanceRequest(), NBHelpers::distance(), AGPosition::distanceTo(), GLHelper::drawBoxLines(), GLHelper::drawTriangleAtEnd(), PositionVector::extrapolate(), ROEdge::getLengthGeometryFactor(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), PositionVector::indexOfClosest(), NBEdge::init(), GUIE2Collector::MyWrapper::MyWrapper(), MSDevice_Bluelight::notifyMove(), GNEViewNet::onCmdTransformPOI(), GUIViewTraffic::onGamingClick(), Position::operator+(), PositionVector::positionAtOffset(), NIVissimEdge::remapOneOfNodes(), PositionVector::rotationAtOffset(), GUIBaseVehicle::setFunctionalColor(), GNEStoppingPlace::setStoppingPlaceGeometry(), PositionVector::slopeDegreeAtOffset(), GUILane::splitAtSegments(), GNEDetectorE2::updateGeometry(), and MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility().
distanceTo2D()
double Position::distanceTo2D (const Position & p2) const inline inherited
returns the euclidean distance in the x-y-plane
Definition at line 249 of file Position.h.
References Position::distanceSquaredTo2D().
Referenced by NBNode::bezierControlPoints(), NBNode::buildWalkingAreas(), NGRandomNetBuilder::canConnect(), NBNode::checkCrossing(), GUIVehicle::computeSeats(), NIImporter_OpenDrive::computeShapes(), PositionVector::distance2D(), GUIVehicle::drawAction_drawRailCarriages(), GUIBusStop::drawGL(), PositionVector::extrapolate2D(), ROEdge::getDistanceTo(), MSEdge::getDistanceTo(), MSLink::getLeaderInfo(), PositionVector::getMaxGrade(), CState::getPosition(), GNEInternalLane::GNEInternalLane(), GUILane::GUILane(), MSVehicle::Influencer::implicitDeltaPosRemote(), MSVehicle::Influencer::implicitSpeedRemote(), MSPModel_Striping::initWalkingAreaPaths(), PositionVector::insertAtClosest(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::move2side(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), GeomHelper::nearest_offset_on_line_to_point2D(), PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), PositionVector::removeClosest(), GNEEdge::resetEndpoint(), GNEEdge::setEndpoint(), PositionVector::sideOffset(), PositionVector::simplified(), PositionVector::slopeDegreeAtOffset(), PositionVector::smoothedZFront(), PositionVector::transformToVectorCoordinates(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNELane::updateGeometry(), MSPerson::MSPersonStage_Walking::walkDistance(), NWWriter_OpenDrive::writeGeomLines(), and NWWriter_OpenDrive::writeGeomSmooth().
dotProduct()
double Position::dotProduct (const Position & pos) inline inherited
returns the dot product (scalar product) between this point and the second one
Definition at line 272 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBHeightMapper::Triangle::getZ().
drawGL()
void GNEPOILane::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GNEShape.
Definition at line 167 of file GNEPOILane.cpp.
References GUIPointOfInterest::drawGL(), GNEShape::drawLockIcon(), GLHelper::drawText(), GLO_POI, RGBColor::invertedColor(), Shape::myColor, Shape::myLayer, and Position::Position().
drawGLAdditional()
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 153 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
drawLockIcon()
void GNEShape::drawLockIcon (const Position & pos, double layer, double size = 0.5) const inherited
draw lock icon
Definition at line 74 of file GNEShape.cpp.
References GUITexturesHelper::drawTexturedBox(), GNEShape::getGlID(), GNEAttributeCarrier::getGUIGLObject(), GUITextureSubSys::getTexture(), GNENet::getViewNet(), GNETEXTURE_EMPTY, GNETEXTURE_EMPTYSELECTED, GNETEXTURE_LOCK, GNETEXTURE_LOCKSELECTED, gSelected, GUISelectedStorage::isSelected(), GNEShape::myBlockMovement, GNEShape::myNet, GNEViewNet::showLockIcon(), Position::x(), and Position::y().
Referenced by GNEPOI::drawGL(), and drawGL().
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
get()
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static inherited
Returns a named object.
Definition at line 71 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
getAttribute()
std::string GNEPOILane::getAttribute (SumoXMLAttr key) const virtual
method for getting the Attribute of an XML key
Parameters
[in] key The attribute key
Returns
string with the value associated to key
Implements GNEShape.
Definition at line 177 of file GNEPOILane.cpp.
References PointOfInterest::getHeight(), GNELane::getLaneParametricLength(), Shape::getNaviDegree(), GNEAttributeCarrier::getTag(), PointOfInterest::getWidth(), GNE_ATTR_BLOCK_MOVEMENT, GNEShape::myBlockMovement, Shape::myColor, myGNELane, Named::myID, Shape::myImgFile, PointOfInterest::myLane, Shape::myLayer, PointOfInterest::myPosLat, PointOfInterest::myPosOverLane, Shape::myType, SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, and toString().
Referenced by setAttribute().
getAttributeForSelection()
std::string GNEAttributeCarrier::getAttributeForSelection (SumoXMLAttr key) const virtual inherited
method for getting the attribute in the context of object selection
Reimplemented in GNEEdge, and GNELane.
Definition at line 183 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute().
Referenced by GNESelectorFrame::getMatches(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttributeType()
std::string GNEAttributeCarrier::getAttributeType (SumoXMLTag tag, SumoXMLAttr attr) static inherited
get type of attribute
Definition at line 247 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), GNEAttributeCarrier::isTime(), and toString().
Referenced by GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getAttrs()
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 231 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getCenteringBoundary()
Boundary GNEPOILane::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Implements GNEShape.
Definition at line 161 of file GNEPOILane.cpp.
References GUIPointOfInterest::getCenteringBoundary().
getColor()
const RGBColor& Shape::getColor () const inline inherited
Returns the color of the Shape.
Returns
The Shape's color
Definition at line 78 of file Shape.h.
References Shape::myColor.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), libsumo::Polygon::getColor(), libsumo::POI::getColor(), GNEViewNet::onCmdTransformPOI(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
getDefaultValue() [1/12]
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getDefaultValue() [2/12]
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1580 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [3/12]
template<> double GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1592 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [4/12]
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1604 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [5/12]
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1616 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [6/12]
template<> SUMOVehicleClass GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1628 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1640 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [8/12]
template<> RGBColor GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1652 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [9/12]
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1664 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [10/12]
template<> std::vector<double> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1676 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1688 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefaultValue() [12/12]
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 1700 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
getDefinition()
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 1296 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ACCEL, SUMO_ATTR_ALLOW, SUMO_ATTR_ANGLE, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_COLOR, SUMO_ATTR_CONT, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_DECEL, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FILL, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEO, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LANES, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LAYER, SUMO_ATTR_LENGTH, SUMO_ATTR_LINE, SUMO_ATTR_LINES, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NAME, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_REROUTE, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_TIME, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TLTYPE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_VCLASS, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_VTYPES, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_PROB_REROUTE, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VSS, and SUMO_TAG_VTYPE.
Referenced by GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getGlID()
GUIGlID GNEPOILane::getGlID () const virtual
Returns the numerical id of the object.
Implements GNEShape.
Definition at line 132 of file GNEPOILane.cpp.
References GUIGlObject::getGlID().
Referenced by GNENet::retrieveShapes().
getGUIGLObject() [1/2]
const GUIGlObject * GNEAttributeCarrier::getGUIGLObject () const inherited
get const pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to const GUIGlObject
Definition at line 207 of file GNEAttributeCarrier.cpp.
Referenced by GNEShape::drawLockIcon(), GNENet::insertShape(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::removePolygonForEditShapes(), GNENet::removeShape(), GNENet::retrieveAttributeCarriers(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getGUIGLObject() [2/2]
GUIGlObject * GNEAttributeCarrier::getGUIGLObject () inherited
get pointer to GUIGlObject vinculated with this Attribute Carrier
Exceptions
ProcessError if AC cannot be casted to GUIGlObject
Definition at line 219 of file GNEAttributeCarrier.cpp.
getGUIIcon()
GUIIcon GNEAttributeCarrier::getGUIIcon () const inherited
get GUI icon assigned to this object
Definition at line 201 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myIcon.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
getHeight()
double PointOfInterest::getHeight () const inline inherited
Returns the image height of the POI.
Definition at line 99 of file PointOfInterest.h.
References PointOfInterest::myHalfImgHeight.
Referenced by GNEPOI::getAttribute(), getAttribute(), GNEViewNet::onCmdTransformPOI(), and PointOfInterest::writeXML().
getHigherNumberOfAttributes()
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 1563 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedNetElementsTags(), GNEAttributeCarrier::allowedShapeTags(), MAX2(), and GNEAttributeCarrier::myMaxNumAttribute.
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getIcon()
FXIcon * GNEAttributeCarrier::getIcon () const inherited
get FXIcon assigned to this object
Definition at line 195 of file GNEAttributeCarrier.cpp.
References GUIIconSubSys::getIcon(), and GNEAttributeCarrier::myIcon.
Referenced by GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNEAdditional::getPopUpMenu(), GNEDeleteFrame::markAttributeCarrier(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEDeleteFrame::updateCurrentLabel(), and GNEAttributeCarrier::~GNEAttributeCarrier().
getID() [1/2]
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 65 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), LaneStoringVisitor::add(), MSPModel_Striping::add(), MSVehicleTransfer::add(), PCPolyContainer::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), MSPModel_Striping::addCrossingVehs(), RODFDetectorCon::addDetector(), RONet::addEdge(), NBParkingCont::addEdges2Keep(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), ROVehicle::addStop(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSNet::addStoppingPlace(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), AGActivityTripWriter::addTrip(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::append(), NBPTStopCont::assignAndCreatNewPTStopAsNeeded(), NBPTStopCont::assignPTStopToEdgeOfClosestPlatform(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPModel_Striping::blockedAtDist(), MSLink::blockedAtTime(), MSLink::blockedByFoe(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NLDetectorBuilder::buildE2Detector(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSEdge::checkAndRegisterBiDirEdge(), MSLane::checkForPedestrians(), NBEdge::checkGeometry(), NBEdgeCont::checkGrade(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), NBEdgeCont::checkOverlap(), MSDevice_Battery::checkParam(), MSE2Collector::checkPositioning(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), MSDevice_SSM::classifyEncounter(), NBTrafficLightLogic::closeBuilding(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBEdge::computeAngle(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), MSDevice_SSM::createEncounters(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), MSVehicle::enterLaneAtMove(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), libsumo::Helper::findCloserLane(), MSDevice_SSM::findFoeConflictLane(), libsumo::Simulation::findIntermodalRoute(), MSDevice_SSM::findSurroundingVehicles(), MSDevice_SSM::flushConflicts(), NBTrafficLightDefinition::forbids(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSPModel_Striping::getArbitraryPath(), GNEConnection::getAttribute(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), libsumo::Vehicle::getBestLanes(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), NBEdge::getConnection(), NBEdge::getConnectionRef(), libsumo::TrafficLight::getControlledLinks(), NBEdge::getCrossingAngle(), RODFNet::getDetectorEdge(), libsumo::Lane::getEdgeID(), MSMeanData::getEdgeID(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), libsumo::InductionLoop::getLaneID(), libsumo::LaneArea::getLaneID(), libsumo::Vehicle::getLaneID(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLink::getLengthBeforeCrossing(), libsumo::Lane::getLinks(), MSLane::getLinkTo(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIE2Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), NBPTStopCont::getReverseStop(), libsumo::Person::getRoadID(), libsumo::Vehicle::getRoadID(), libsumo::Vehicle::getRouteID(), MSNet::getStoppingPlaceID(), MSDevice_SSM::getUpstreamVehicles(), MSDevice_SSM::getVehiclesOnJunction(), MSTransportable::Stage_Driving::getWaitingDescription(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSVehicle::ignoreRed(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NBEdge::init(), MSE2Collector::initAuxiliaries(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSAbstractLaneChangeModel::laneChangeOutput(), MSE3Collector::leave(), MSE3Collector::leaveFront(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), MSE2Collector::makeVehicleInfo(), GNEJunction::markAsModified(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), MSE2Collector::MSE2Collector(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSPModel_Striping::nextBlocking(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSMeanData::MeanDataValues::notifyEnter(), MSDevice_Bluelight::notifyEnter(), MSDevice_Example::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_SSM::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Bluelight::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSE3Collector::MSE3LeaveReminder::notifyLeave(), MSE2Collector::notifyLeave(), MSDevice_SSM::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSE2Collector::notifyMove(), MSDevice_SSM::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), MSLink::opened(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NLTriggerBuilder::parseAndBuildCalibrator(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLane::planMovements(), MSInternalJunction::postloadInit(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), AGStreet::print(), MSDevice_SSM::processEncounters(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSDelayBasedTrafficLightLogic::proposeProlongation(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckLanes(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), MSLink::removeApproaching(), NBNodeCont::removeIsolatedRoads(), MSVehicle::removePassedDriveItems(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSVehicle::replaceParkingArea(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), MSBaseVehicle::reroute(), MSTriggeredRerouter::rerouteParkingArea(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), NBEdge::restoreRestrictedLane(), GNEEdge::retrieveGNEConnection(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), NBPTLineCont::reviseStops(), MSPerson::MSPersonStage_Walking::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), RONet::saveAndRemoveRoutesUntil(), MSDevice_Vehroutes::saveState(), MSDevice::saveState(), MSDevice_Tripinfo::saveState(), MSBaseVehicle::saveState(), MSLane::saveState(), GUIVehicle::selectBlockingFoes(), MSE2Collector::selectLanes(), MSLink::setApproaching(), NBNodeCont::setAsTLControlled(), GNEEdge::setAttribute(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), GNEJunction::setLogicValid(), MSLane::setManeuverReservation(), MSDevice_Battery::setMaximumBatteryCapacity(), NBEdge::setNodeBorder(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSLink::setRequestInformation(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), MSDevice_Battery::setStoppingTreshold(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), IntermodalRouter< E, L, N, V >::splitEdge(), MSLaneChangerSublane::startChangeSublane(), MSStopOut::stopEnded(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSDevice_SSM::update(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateCFRelated(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSVehicle::updateDriveItems(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSAbstractLaneChangeModel::updateTargetLane(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), MSPModel_Striping::PState::walk(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), NBParking::write(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), NWWriter_OpenDrive::writeInternalEdge(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_OpenDrive::writeNormalEdge(), NWWriter_DlrNavteq::writeProhibitedManoeuvres(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), SUMOPolygon::writeXML(), PointOfInterest::writeXML(), MSRouteProbe::writeXMLOutput(), MSInductLoop::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
getID() [2/2]
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 241 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNECrossingFrame::addCrossing(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), GNEAdditional::addLaneChild(), GNEJunction::addOutgoingGNEEdge(), GNENet::addPOI(), GNEPolygonFrame::addPOILane(), GNENet::addReversedEdge(), GNELane::addShapeChild(), GNEAdditionalHandler::buildRerouterInterval(), GNENet::changeCalibratorFlowID(), GNENet::changeCalibratorRouteID(), GNENet::changeCalibratorVehicleTypeID(), GNENet::changeShapeID(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteCalibratorFlow(), GNENet::deleteCalibratorRoute(), GNENet::deleteCalibratorVehicleType(), GNEDetectorE3::generateEntryID(), GNEDetectorE3::generateExitID(), GNEAdditionalFrame::generateID(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECalibratorFlow::getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNECalibrator::getAttribute(), GNEJunction::getAttribute(), GNEAdditionalHandler::getPosition(), GNECalibratorRoute::GNECalibratorRoute(), GNENet::insertAdditional(), GNENet::insertCalibratorFlow(), GNENet::insertCalibratorRoute(), GNENet::insertCalibratorVehicleType(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNEDeleteFrame::markAttributeCarrier(), GNECrossingFrame::crossingParameters::markEdge(), GNERerouterDialog::onCmdAccept(), GNECalibratorFlowDialog::onCmdSetVariable(), GNECalibratorRouteDialog::onCmdSetVariable(), GNEViewNet::onCmdTransformPOI(), GNEAdditionalHandler::parseAndBuildRerouterInterval(), GNEPolygonFrame::processClick(), GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_TLS::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Additional::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_CalibratorItem::redo(), GNEChange_RerouterItem::redo(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), GNEJunction::removeEdgeFromCrossings(), GNEEdge::removeEdgeOfAdditionalParents(), GNEJunction::removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), GNELane::removeLaneOfAdditionalParents(), GNEJunction::removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceIncomingEdge(), GNENet::retrieveEdge(), GNEEdge::retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNENet::reverseEdge(), GNEInspectorFrame::NeteditParameters::show(), GNEEdge::smooth(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), GNEChange_Junction::undo(), GNEChange_Shape::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_TLS::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_CalibratorItem::undo(), GNEChange_RerouterItem::undo(), GNENet::updateAdditionalID(), GNECalibratorRouteDialog::updateCalibratorRouteValues(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEBusStop::writeAdditional(), GNEContainerStop::writeAdditional(), GNECalibrator::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), writeShape(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEJunction::~GNEJunction().
getIDList()
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList (int typeFilter) static inherited
Returns the list of gl-ids of all additional objects that match the given type.
Definition at line 94 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
getIDSecure()
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 58 of file Named.h.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPositionOnLane(), NBOwnTLDef::getBestPair(), MSVehicle::getCenterOnEdge(), NBEdge::Connection::getDescription(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealLeader(), NBEdge::init(), MSLane::isInsertionSuccess(), MSPModel_Striping::PState::moveToNextLane(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), operator<<(), NBEdge::recheckLanes(), MSTriggeredRerouter::rerouteParkingArea(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), toString(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
getImgFile()
const std::string& Shape::getImgFile () const inline inherited
Returns the imgFile of the Shape.
Returns
The Shape's rotation imgFile
Definition at line 100 of file Shape.h.
References Shape::myImgFile.
Referenced by GUIPolygon::drawGL(), GNEViewNet::onCmdTransformPOI(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
getLane()
GNELane * GNEPOILane::getLane () const
get GNELane
Definition at line 109 of file GNEPOILane.cpp.
References myGNELane.
getLayer()
double Shape::getLayer () const inline inherited
Returns the layer of the Shape.
Returns
The Shape's layer
Definition at line 86 of file Shape.h.
References Shape::myLayer.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GNEViewNet::onCmdTransformPOI(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), getParentName(), GNERerouter::getParentName(), GNEPoly::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNaviDegree()
double Shape::getNaviDegree () const inline inherited
Returns the angle of the Shape in navigational degrees.
Returns
The Shape's rotation angle
Definition at line 93 of file Shape.h.
References Shape::myNaviDegreeAngle.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), GNEViewNet::onCmdTransformPOI(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
getNet()
GNENet * GNEShape::getNet () const inherited
get Net in which this element is placed
Definition at line 56 of file GNEShape.cpp.
References GNEShape::myNet.
Referenced by GNEChange_Attribute::redo(), GNEChange_Attribute::undo(), and GNEChange_Attribute::~GNEChange_Attribute().
getObjectList()
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static inherited
Returns the list of all additional objects.
Definition at line 88 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getParameterWindow()
GUIParameterTableWindow * GNEPOILane::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GNEShape.
Definition at line 155 of file GNEPOILane.cpp.
References GUIPointOfInterest::getParameterWindow().
getParentName()
const std::string & GNEPOILane::getParentName () const virtual
Returns the name of the parent object.
Returns
This object's parent id
Implements GNEShape.
Definition at line 138 of file GNEPOILane.cpp.
References GUIGlObject::getMicrosimID(), and GNEShape::myNet.
getPopUpMenu()
GUIGLObjectPopupMenu * GNEPOILane::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GNEShape.
Definition at line 144 of file GNEPOILane.cpp.
References GUIGlObject::buildShapePopupOptions(), GUIIconSubSys::getIcon(), ICON_LANE, MID_GNE_POI_TRANSFORM, Shape::myType, SUMO_TAG_LANE, and toString().
getPositionInView()
Position GNEPOILane::getPositionInView () const virtual
Returns position of additional in view.
Implements GNEShape.
Definition at line 126 of file GNEPOILane.cpp.
References Position::Position(), Position::x(), and Position::y().
Referenced by GNEViewNet::onLeftBtnPress().
getTag()
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get XML Tag assigned to this object
Definition at line 189 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNENetElement::addAdditionalChild(), GNEAdditional::addAdditionalChild(), GNENetElement::addAdditionalParent(), GNEAdditional::addEdgeChild(), GNEJunction::addIncomingGNEEdge(), GNEAdditional::addLaneChild(), GNEJunction::addOutgoingGNEEdge(), GNENet::addPOI(), GNELane::addShapeChild(), GNEViewNet::begingMoveSelection(), GNEAdditionalHandler::buildCalibratorFlow(), GNEAdditionalHandler::buildCalibratorRoute(), GNEAdditionalHandler::buildCalibratorVehicleType(), GNEAdditionalHandler::buildClosingLaneReroute(), GNEAdditionalHandler::buildClosingReroute(), GNEAdditionalHandler::builDestProbReroute(), GNEAdditionalHandler::buildRerouterInterval(), GNEAdditionalHandler::buildRouteProbReroute(), GNEAdditionalHandler::buildVariableSpeedSignStep(), GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNENet::changeShapeID(), GNEDetectorE3::commitGeometryMoving(), GNEPOI::commitGeometryMoving(), GNEDetector::commitGeometryMoving(), commitGeometryMoving(), GNEStoppingPlace::commitGeometryMoving(), GNEVariableSpeedSign::commitGeometryMoving(), GNERerouter::commitGeometryMoving(), GNEJunction::commitGeometryMoving(), GNEPoly::commitShapeChange(), GNEEdge::commitShapeChange(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNENet::deleteAdditional(), GNENet::deleteShape(), GNERouteProbReroute::getAttribute(), GNEDestProbReroute::getAttribute(), GNEClosingLaneReroute::getAttribute(), GNEClosingReroute::getAttribute(), GNEVariableSpeedSignStep::getAttribute(), GNECalibratorRoute::getAttribute(), GNECalibratorVehicleType::getAttribute(), GNERerouterInterval::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNECalibratorFlow::getAttribute(), GNEDetectorE2::getAttribute(), GNEVaporizer::getAttribute(), GNECrossing::getAttribute(), GNEDetectorE3::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNEConnection::getAttribute(), GNEVariableSpeedSign::getAttribute(), GNERerouter::getAttribute(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), GNECalibrator::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNESelectorFrame::getMatches(), GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEEdge::getRouteProbeRelativePosition(), GNEEdge::getVaporizerRelativePosition(), GNECalibratorRoute::GNECalibratorRoute(), GNEViewNet::hotkeyEnter(), GNENet::insertAdditional(), GNENet::insertShape(), GNEAdditional::isRouteValid(), GNERouteProbReroute::isValid(), GNEDestProbReroute::isValid(), GNEClosingLaneReroute::isValid(), GNEClosingReroute::isValid(), GNEVariableSpeedSignStep::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNERerouterInterval::isValid(), GNEDetectorE1::isValid(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE2::isValid(), GNECalibratorFlow::isValid(), GNEVaporizer::isValid(), GNECrossing::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNEConnection::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNELane::isValid(), GNEJunction::isValid(), GNEEdge::isValid(), GNEAdditional::isValidAdditionalID(), GNEDeleteFrame::markAttributeCarrier(), GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), GNEViewNet::onCmdOpenAdditionalDialog(), GNEViewNet::onLeftBtnPress(), GNEAdditional::openAdditionalDialog(), GNEChange_Shape::redo(), GNEChange_Junction::redo(), GNEChange_TLS::redo(), GNEChange_Additional::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Attribute::redo(), GNEChange_Crossing::redo(), GNEChange_Shape::redoName(), GNEChange_VariableSpeedSignItem::redoName(), GNEChange_Additional::redoName(), GNEChange_Attribute::redoName(), GNEChange_CalibratorItem::redoName(), GNEChange_RerouterItem::redoName(), GNEAdditionalFrame::removeAdditional(), GNENetElement::removeAdditionalChild(), GNEAdditional::removeAdditionalChild(), GNENetElement::removeAdditionalParent(), GNEDeleteFrame::removeAttributeCarrier(), GNEEdge::removeConnection(), GNEAdditional::removeEdgeChild(), GNEJunction::removeIncomingGNEEdge(), GNEEdge::removeLane(), GNEAdditional::removeLaneChild(), GNEJunction::removeOutgoingGNEEdge(), GNENet::removeShape(), GNELane::removeShapeChild(), GNENet::replaceInListAttribute(), GNEEdge::retrieveGNEConnection(), GNEJunction::retrieveGNECrossing(), GNERouteProbReroute::setAttribute(), GNEDestProbReroute::setAttribute(), GNEClosingReroute::setAttribute(), GNEClosingLaneReroute::setAttribute(), GNEVariableSpeedSignStep::setAttribute(), GNECalibratorRoute::setAttribute(), GNECalibratorVehicleType::setAttribute(), GNERerouterInterval::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNECalibratorFlow::setAttribute(), GNEVaporizer::setAttribute(), GNECrossing::setAttribute(), GNEDetectorE3::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNEConnection::setAttribute(), GNEVariableSpeedSign::setAttribute(), GNERerouter::setAttribute(), GNEPOI::setAttribute(), setAttribute(), GNEPoly::setAttribute(), GNECalibrator::setAttribute(), GNELane::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setAttribute(), GNEAdditional::setBlockIconRotation(), GNEInspectorFrame::NeteditParameters::show(), GNEInspectorFrame::showAttributeCarrierChilds(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), GNEChange_Shape::undo(), GNEChange_Junction::undo(), GNEChange_TLS::undo(), GNEChange_Additional::undo(), GNEChange_Lane::undo(), GNEChange_Edge::undo(), GNEChange_Attribute::undo(), GNEChange_Crossing::undo(), GNEChange_Shape::undoName(), GNEChange_VariableSpeedSignItem::undoName(), GNEChange_Additional::undoName(), GNEChange_Attribute::undoName(), GNEChange_CalibratorItem::undoName(), GNEChange_RerouterItem::undoName(), GNENet::updateAdditionalID(), GNEDeleteFrame::updateCurrentLabel(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE3::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNEDetectorE2::writeAdditional(), GNERerouter::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEClosingLaneReroute::writeClosingLaneReroute(), GNEClosingReroute::writeClosingReroute(), GNEDestProbReroute::writeDestProbReroute(), GNECalibratorFlow::writeFlow(), GNERerouterInterval::writeRerouterInterval(), GNECalibratorRoute::writeRoute(), GNERouteProbReroute::writeRouteProbReroute(), GNECalibratorVehicleType::writeVehicleType(), GNEAttributeCarrier::~GNEAttributeCarrier(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_Shape::~GNEChange_Shape(), and GNEChange_TLS::~GNEChange_TLS().
getType() [1/2]
const std::string& Shape::getType () const inline inherited
Returns the (abstract) type of the Shape.
Returns
The Shape's (abstract) type
Definition at line 70 of file Shape.h.
References Shape::myType.
Referenced by libsumo::Polygon::getType(), libsumo::POI::getType(), GNEViewNet::onCmdTransformPOI(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
getType() [2/2]
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, GUIMEVehicle, GUIPerson, and GUIContainer.
Definition at line 126 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
getWidth()
double PointOfInterest::getWidth () const inline inherited
Returns the image width of the POI.
Definition at line 94 of file PointOfInterest.h.
References PointOfInterest::myHalfImgWidth.
Referenced by GNEPOI::getAttribute(), getAttribute(), GNEViewNet::onCmdTransformPOI(), and PointOfInterest::writeXML().
hasAttribute()
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if an element with certain tag has a certain attribute
Definition at line 1211 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditional::getPopUpMenu(), GNECalibratorRoute::GNECalibratorRoute(), GNEChange_Additional::GNEChange_Additional(), GNEViewNet::hotkeyEnter(), GNEAdditional::setBlockIconRotation(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
hasDefaultValue()
bool GNEAttributeCarrier::hasDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if attribute of an element has a default avlue
Definition at line 1222 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), NODEFAULTVALUE, and toString().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
incRef()
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Increarse reference.
Definition at line 76 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNEChange_CalibratorItem::GNEChange_CalibratorItem(), GNEChange_RerouterItem::GNEChange_RerouterItem(), GNEJunction::rebuildGNECrossings(), GNENet::registerEdge(), GNENet::registerJunction(), GNEEdge::remakeGNEConnections(), and GNEInspectorFrame::setEdgeTemplate().
invalidPosition()
static const Position& Position::invalidPosition () inline static inherited
reference to invalid position (needed if INVALID is taken by macro-definition)
Definition at line 280 of file Position.h.
References Position::INVALID.
isBool()
bool GNEAttributeCarrier::isBool (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool for a certain tag
Definition at line 867 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myBoolAttrs, SUMO_ATTR_ACCELERATION, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_FILL, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_GEO, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PASS, SUMO_ATTR_PRIORITY, SUMO_ATTR_REROUTE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POLY, and SUMO_TAG_REROUTER.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isColor()
bool GNEAttributeCarrier::isColor (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type color for a certain tag
Definition at line 910 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myColorAttrs, SUMO_ATTR_COLOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_ROUTE, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isDiscrete()
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 1045 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFilename()
bool GNEAttributeCarrier::isFilename (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a filename
Definition at line 1141 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, SUMO_ATTR_FILE, SUMO_ATTR_IMGFILE, SUMO_ATTR_OUTPUT, SUMO_TAG_CALIBRATOR, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isFloat()
bool GNEAttributeCarrier::isFloat (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 741 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_ANGLE, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERIOD, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_STARTPOS, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_STEP, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isInt()
bool GNEAttributeCarrier::isInt (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 707 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_FROM_LANE, SUMO_ATTR_INDEX, SUMO_ATTR_LAYER, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isNumerical(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isList()
bool GNEAttributeCarrier::isList (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 935 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, SUMO_ATTR_LINES, SUMO_ATTR_SHAPE, SUMO_TAG_BUS_STOP, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNENet::replaceInListAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isMovementBlocked()
bool GNEShape::isMovementBlocked () const inherited
return true if movement is blocked
Definition at line 62 of file GNEShape.cpp.
References GNEShape::myBlockMovement.
Referenced by GNEViewNet::onLeftBtnPress().
isNonEditable()
bool GNEAttributeCarrier::isNonEditable (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is non editable
Definition at line 1193 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNonEditableAttrs, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
isNumerical()
bool GNEAttributeCarrier::isNumerical (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 701 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [1/2]
bool GNEAttributeCarrier::isPositive (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is only Positive (i.e. cannot take negative values)
Definition at line 1055 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myPositiveAttrs, SUMO_ATTR_ACCEL, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_CONTPOS, SUMO_ATTR_DECEL, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_HEIGHT, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NUMBER, SUMO_ATTR_NUMLANES, SUMO_ATTR_PERIOD, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_RADIUS, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEED, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VEHSPERHOUR, SUMO_ATTR_VISIBILITY_DISTANCE, SUMO_ATTR_WIDTH, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_FLOW, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, and SUMO_TAG_VTYPE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isPositive() [2/2]
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 249 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFilename(), and GNEAttributeCarrier::isValidID().
isProbability()
bool GNEAttributeCarrier::isProbability (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is a probability (i.e. oly can values between [0, 1])
Definition at line 1122 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myProbabilityAttrs, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_PROB, SUMO_TAG_CHARGING_STATION, SUMO_TAG_DEST_PROB_REROUTE, SUMO_TAG_FLOW, SUMO_TAG_REROUTER, and SUMO_TAG_ROUTE_PROB_REROUTE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isShapeBlocked()
bool GNEShape::isShapeBlocked () const inherited
return true if shape is blocked
Definition at line 68 of file GNEShape.cpp.
References GNEShape::myBlockShape.
Referenced by GNEViewNet::onLeftBtnPress(), and GNEViewNet::onMouseMove().
isString()
bool GNEAttributeCarrier::isString (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 929 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isNumerical(), and GNEAttributeCarrier::isTime().
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isTime()
bool GNEAttributeCarrier::isTime (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is time
Definition at line 830 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTimeAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_END, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_STARTTIME, SUMO_ATTR_TIME, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_FLOW, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_ROUTEPROBE, SUMO_TAG_STEP, SUMO_TAG_VAPORIZER, and SUMO_TAG_VTYPE.
Referenced by GNEPolygonFrame::ShapeAttributes::addAttribute(), GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::getAttributeType(), GNEAdditionalFrame::AdditionalAttributeSingle::getValue(), GNEPolygonFrame::ShapeAttributeSingle::getValue(), GNEAttributeCarrier::isString(), GNECrossingFrame::crossingParameters::onCmdHelp(), GNEPolygonFrame::ShapeAttributes::onCmdHelp(), GNEAdditionalFrame::AdditionalAttributes::onCmdHelp(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), GNEInspectorFrame::AttributeInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isUnique()
bool GNEAttributeCarrier::isUnique (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection and don't have a default value)
Definition at line 958 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_CUSTOMSHAPE, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANECALIBRATOR, SUMO_TAG_POI, SUMO_TAG_POILANE, SUMO_TAG_POLY, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNENetElement::getParameterWindow(), GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspectMultisection(), GNEAdditionalFrame::setParametersOfAdditional(), GNEPolygonFrame::setParametersOfShape(), and GNEAttributeCarrier::~GNEAttributeCarrier().
isValid()
bool GNEPOILane::isValid (SumoXMLAttr key, const std::string & value) virtual
method for checking if the key and their correspond attribute are valids
Parameters
[in] key The attribute key
[in] value The value asociated to key key
Returns
true if the value is valid, false in other case
Implements GNEShape.
Definition at line 236 of file GNEPOILane.cpp.
References GNEAttributeCarrier::getTag(), GUITexturesHelper::getTextureID(), GNE_ATTR_BLOCK_MOVEMENT, GNEAttributeCarrier::isValidFilename(), GNEAttributeCarrier::isValidID(), GNEShape::myNet, GNENet::retrieveLane(), GNENet::retrievePOI(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, and toString().
isValidFilename()
bool GNEAttributeCarrier::isValidFilename (const std::string & value) static inherited
true if value is a valid file value
Definition at line 275 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNECalibratorVehicleType::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEDetectorE3::isValid(), GNERouteProbe::isValid(), GNEVariableSpeedSign::isValid(), GNERerouter::isValid(), GNEPOI::isValid(), isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEPolygonFrame::ShapeAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isValidID()
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 269 of file GNEAttributeCarrier.cpp.
Referenced by GNEAdditional::changeAdditionalID(), GNEAttributeCarrier::isPositive(), GNERouteProbReroute::isValid(), GNECalibratorRoute::isValid(), GNECalibratorVehicleType::isValid(), GNECalibratorFlow::isValid(), GNEPOI::isValid(), isValid(), GNEPoly::isValid(), GNECalibrator::isValid(), GNEJunction::isValid(), GNEEdge::isValid(), GNEAdditional::isValidAdditionalID(), GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), and GNEAttributeCarrier::parseAttributeFromXML().
isVClass()
bool GNEAttributeCarrier::isVClass (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether a string attribute is a list of Vehicle Classes
Definition at line 1172 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myFileAttrs, GNEAttributeCarrier::myVClassAttrs, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_TAG_CLOSING_LANE_REROUTE, SUMO_TAG_CLOSING_REROUTE, SUMO_TAG_EDGE, and SUMO_TAG_LANE.
Referenced by GNEAdditionalFrame::AdditionalAttributeSingle::onCmdSetAttribute(), GNEAttributeCarrier::parseAttributeFromXML(), and GNEAttributeCarrier::~GNEAttributeCarrier().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
moveGeometry()
void GNEPOILane::moveGeometry (const Position & oldPos, const Position & offset)
change the position of the element geometry without saving in undoList
Parameters
[in] newPosition new position of geometry
Note
should't be called in drawGL(...) functions to avoid smoothness issues
Definition at line 86 of file GNEPOILane.cpp.
References Position::add(), GNELane::getLaneShapeLength(), GNELane::getShape(), myGNELane, PointOfInterest::myPosOverLane, PositionVector::nearest_offset_to_point2D(), and updateGeometry().
Referenced by GNEViewNet::onMouseMove().
mul() [1/3]
void Position::mul (double val) inline inherited
Multiplies both positions with the given value.
Definition at line 112 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), GeoConvHelper::computeFinal(), NBNodeShapeComputer::computeNodeShapeDefault(), GUIEdge::drawGL(), GNEEdge::drawGL(), NBNode::getEmptyDir(), NBDistrict::mirrorX(), NBNode::mirrorX(), PCPolyContainer::saveDlrTDP(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
mul() [2/3]
void Position::mul (double mx, double my) inline inherited
Multiplies position with the given values.
Definition at line 119 of file Position.h.
References Position::myX, and Position::myY.
mul() [3/3]
void Position::mul (double mx, double my, double mz) inline inherited
Multiplies position with the given values.
Definition at line 125 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
norm2d()
void Position::norm2d () inline inherited
Definition at line 172 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::getEmptyDir().
operator!=()
bool Position::operator!= (const Position & p2) const inline inherited
difference operator
Definition at line 218 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
operator*()
Position Position::operator* (double scalar) const inline inherited
keep the direction but modify the length of the (location) vector to length * scalar
Definition at line 198 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
operator+() [1/2]
Position Position::operator+ (const Position & p2) const inline inherited
add operator
Definition at line 188 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
operator+() [2/2]
Position Position::operator+ (double offset) const inline inherited
keep the direction but modify the length of the (location) vector to length + scalar
Definition at line 203 of file Position.h.
References Position::distanceTo(), Position::myX, Position::myY, Position::myZ, and Position::Position().
operator-()
Position Position::operator- (const Position & p2) const inline inherited
sub operator
Definition at line 193 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
operator<()
bool Position::operator< (const Position & p2) const inline inherited
lexicographical sorting for use in maps and sets
Definition at line 223 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
operator=()
GNEPOILane& GNEPOILane::operator= (const GNEPOILane &) private delete
Invalidated assignment operator.
operator==()
bool Position::operator== (const Position & p2) const inline inherited
comparation operator
Definition at line 213 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
parse() [1/12]
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 88 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int().
parse() [2/12]
template<> double GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 94 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2double().
parse() [3/12]
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 100 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
parse() [4/12]
template<> std::string GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 106 of file GNEAttributeCarrier.cpp.
parse() [5/12]
template<> SUMOVehicleClass GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 112 of file GNEAttributeCarrier.cpp.
References SumoVehicleClassStrings, and SVC_IGNORING.
parse() [6/12]
template<> RGBColor GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 124 of file GNEAttributeCarrier.cpp.
References RGBColor::parseColor().
parse() [7/12]
template<> SUMOVehicleShape GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 130 of file GNEAttributeCarrier.cpp.
References SumoVehicleShapeStrings, and SVS_UNKNOWN.
parse() [8/12]
template<> std::vector<std::string> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 142 of file GNEAttributeCarrier.cpp.
References SUMOSAXAttributes::parseStringVector().
parse() [9/12]
template<> std::vector<int> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 150 of file GNEAttributeCarrier.cpp.
parse() [10/12]
template<> std::vector<double> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 161 of file GNEAttributeCarrier.cpp.
parse() [11/12]
template<> std::vector<bool> GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 172 of file GNEAttributeCarrier.cpp.
parse() [12/12]
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse().
parseAttributeFromXML()
template<typename T > static T GNEAttributeCarrier::parseAttributeFromXML (const SUMOSAXAttributes & attrs, const std::string & objectID, const SumoXMLTag tag, const SumoXMLAttr attribute, bool & abort, bool report = true) inline static inherited
Parse attribute from XML and show warnings if there are problems parsing it.
Definition at line 276 of file GNEAttributeCarrier.h.
References canParseVehicleClasses(), GNEAttributeCarrier::checkGNEEdgesValid(), GNEAttributeCarrier::checkGNELanesValid(), SUMOSAXAttributes::get(), GNEAttributeCarrier::getAttributeType(), SUMOSAXAttributes::hasAttribute(), GNEAttributeCarrier::hasDefaultValue(), GNEAttributeCarrier::isColor(), GNEAttributeCarrier::isFilename(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isPositive(), GNEAttributeCarrier::isTime(), GNEAttributeCarrier::isValidFilename(), GNEAttributeCarrier::isValidID(), GNEAttributeCarrier::isVClass(), GNEAttributeCarrier::parseGNEEdges(), GNEAttributeCarrier::parseGNELanes(), GNEAttributeCarrier::setAttribute(), SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_VCLASS, toString(), and WRITE_WARNING.
parseGNEEdges() [1/2]
std::vector< GNEEdge * > GNEAttributeCarrier::parseGNEEdges (GNENet * net, const std::string & value) static inherited
parse string into vector of GNEEdges
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1748 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveEdge().
Referenced by GNEAdditionalHandler::buildAdditional(), GNECalibratorRoute::getAttribute(), GNERerouter::getAttribute(), GNECalibratorRoute::isValid(), GNEAdditionalHandler::parseAndBuildCalibratorRoute(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAttributeCarrier::parseAttributeFromXML(), GNECalibratorRoute::setAttribute(), GNECrossing::setAttribute(), GNERerouter::setAttribute(), GNERerouter::writeAdditional(), and GNECalibratorRoute::writeRoute().
parseGNEEdges() [2/2]
std::string GNEAttributeCarrier::parseGNEEdges (const std::vector< GNEEdge *> & edges) static inherited
parse vector of GNEEdges into string
Exceptions
exception one of GNEEdges doesn't exist
Definition at line 1774 of file GNEAttributeCarrier.cpp.
References joinToString().
parseGNELanes() [1/2]
std::vector< GNELane * > GNEAttributeCarrier::parseGNELanes (GNENet * net, const std::string & value) static inherited
parse string into vector of GNELanes
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1761 of file GNEAttributeCarrier.cpp.
References GNENet::retrieveLane().
Referenced by GNEAdditionalHandler::buildAdditional(), GNEVariableSpeedSign::getAttribute(), GNEAdditionalHandler::parseAndBuildVariableSpeedSign(), GNEAttributeCarrier::parseAttributeFromXML(), GNEVariableSpeedSign::setAttribute(), and GNEVariableSpeedSign::writeAdditional().
parseGNELanes() [2/2]
std::string GNEAttributeCarrier::parseGNELanes (const std::vector< GNELane *> & lanes) static inherited
parse vector of GNELanes into string
Exceptions
exception one of GNELanes doesn't exist
Definition at line 1785 of file GNEAttributeCarrier.cpp.
References joinToString().
remove()
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static inherited
Removes an object.
Definition at line 81 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
set() [1/3]
void Position::set (double x, double y) inline inherited
set positions x and y
Definition at line 92 of file Position.h.
References Position::myX, Position::myY, Position::x(), and Position::y().
Referenced by NIXMLNodesHandler::addNode(), ShapeHandler::addPOI(), NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeSmall(), GUISUMOAbstractView::destroyPopup(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUICompleteSchemeStorage::init(), NBHeightMapper::loadTiff(), libsumo::Helper::makePosition(), GUISettingsHandler::myStartElement(), NLJunctionControlBuilder::openJunction(), operator>>(), TraCIServerAPI_GUI::processSet(), GUICompleteSchemeStorage::saveViewport(), libsumo::POI::setPosition(), NGNode::setX(), NGNode::setY(), GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
set() [2/3]
void Position::set (double x, double y, double z) inline inherited
set positions x, y and z
Definition at line 98 of file Position.h.
References Position::myX, Position::myY, Position::myZ, Position::x(), Position::y(), and Position::z().
set() [3/3]
void Position::set (const Position & pos) inline inherited
set position with another position
Definition at line 105 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
setAttribute() [1/2]
void GNEPOILane::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
method for setting the attribute and letting the object perform additional changes
Parameters
[in] key The attribute key
[in] value The new value
[in] undoList The undoList on which to register changes
Implements GNEShape.
Definition at line 210 of file GNEPOILane.cpp.
References getAttribute(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNEAttributeCarrier::GNEChange_Attribute, GNEUndoList::p_add(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, and toString().
Referenced by GNEPolygonFrame::addPOILane().
setAttribute() [2/2]
void GNEPOILane::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
set attribute after validation
Implements GNEShape.
Definition at line 279 of file GNEPOILane.cpp.
References GNELane::addShapeChild(), GNENet::changeShapeID(), GNELane::getLaneParametricLength(), GNEAttributeCarrier::getTag(), GNE_ATTR_BLOCK_MOVEMENT, GNEShape::myBlockMovement, Shape::myColor, myGNELane, Named::myID, Shape::myImgFile, PointOfInterest::myLane, Shape::myLayer, GNEShape::myNet, PointOfInterest::myPosLat, PointOfInterest::myPosOverLane, Shape::myType, GNELane::removeShapeChild(), GNENet::retrieveLane(), PointOfInterest::setHeight(), Shape::setNaviDegree(), PointOfInterest::setWidth(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAYER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, toString(), and updateGeometry().
setColor()
void Shape::setColor (const RGBColor & col) inline inherited
Sets a new color.
Parameters
[in] col The new color to use
Definition at line 120 of file Shape.h.
References Shape::myColor.
Referenced by libsumo::Polygon::setColor(), and libsumo::POI::setColor().
setHeight()
void PointOfInterest::setHeight (double height) inline inherited
set the image height of the POI
Definition at line 114 of file PointOfInterest.h.
References PointOfInterest::myHalfImgHeight.
Referenced by GNEPOI::setAttribute(), and setAttribute().
setID()
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 73 of file Named.h.
References Named::myID.
Referenced by Distribution_Parameterized::parse(), NBLoadedSUMOTLDef::reconstructLogic(), NBNodeCont::remapIDs(), NBEdgeCont::remapIDs(), NBNodeCont::rename(), NBEdgeCont::rename(), and IntermodalRouter< E, L, N, V >::splitEdge().
setImgFile()
void Shape::setImgFile (const std::string & imgFile) inline inherited
Sets a new imgFile.
Parameters
[in] imgFile The new imgFile to use
Definition at line 143 of file Shape.h.
References Shape::myImgFile.
Referenced by GNEPoly::GNEPoly().
setLayer()
void Shape::setLayer (const double layer) inline inherited
Sets a new layer.
Parameters
[in] layer The new layer to use
Definition at line 128 of file Shape.h.
References Shape::myLayer.
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setNaviDegree()
void Shape::setNaviDegree (const double angle) inline inherited
Sets a new angle in navigational degrees.
Parameters
[in] layer The new angle to use
Definition at line 136 of file Shape.h.
References Shape::myNaviDegreeAngle.
Referenced by GNEPOI::setAttribute(), setAttribute(), and GNEPoly::setAttribute().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setType()
void Shape::setType (const std::string & type) inline inherited
Sets a new type.
Parameters
[in] type The new type to use
Definition at line 112 of file Shape.h.
References Shape::myType.
Referenced by libsumo::Polygon::setType(), and libsumo::POI::setType().
setWidth()
void PointOfInterest::setWidth (double width) inline inherited
set the image width of the POI
Definition at line 109 of file PointOfInterest.h.
References PointOfInterest::myHalfImgWidth.
Referenced by GNEPOI::setAttribute(), and setAttribute().
setx()
void Position::setx (double x) inline inherited
set position x
Definition at line 77 of file Position.h.
References Position::myX, and Position::x().
Referenced by GNENet::joinSelectedJunctions(), GNEDetectorE3::setAttribute(), and GUISUMOAbstractView::snapToActiveGrid().
sety()
void Position::sety (double y) inline inherited
set position y
Definition at line 82 of file Position.h.
References Position::myY, and Position::y().
Referenced by GNENet::joinSelectedJunctions(), GNEDetectorE3::setAttribute(), and GUISUMOAbstractView::snapToActiveGrid().
setz()
void Position::setz (double z) inline inherited
set position z
Definition at line 87 of file Position.h.
References Position::myZ, and Position::z().
Referenced by NBNodeShapeComputer::computeNodeShapeDefault(), and NBEdge::startShapeAt().
sub() [1/3]
void Position::sub (double dx, double dy) inline inherited
Substracts the given position from this one.
Definition at line 152 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), AGPosition::compute2dPosition(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), and NBHeightMapper::Triangle::getZ().
sub() [2/3]
void Position::sub (double dx, double dy, double dz) inline inherited
Substracts the given position from this one.
Definition at line 158 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
sub() [3/3]
void Position::sub (const Position & pos) inline inherited
Substracts the given position from this one.
Definition at line 165 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
unreferenced()
bool GNEReferenceCounter::unreferenced () inline inherited
check if object ins't referenced
Definition at line 87 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateGeometry()
void GNEPOILane::updateGeometry () virtual
update pre-computed geometry information
Note
: must be called when geometry changes (i.e. lane moved) and implemented in ALL childrens
Implements GNEShape.
Definition at line 115 of file GNEPOILane.cpp.
References GNELane::getLaneShapeLength(), GNELane::getShape(), myGNELane, GNEShape::myNet, PointOfInterest::myPosLat, PointOfInterest::myPosOverLane, PositionVector::positionAtOffset(), and GNENet::refreshElement().
Referenced by moveGeometry(), and setAttribute().
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
writeShape()
void GNEPOILane::writeShape (OutputDevice & device) virtual
writte shape element into a xml file
Parameters
[in] device device in which write parameters of additional element
Implements GNEShape.
Definition at line 77 of file GNEPOILane.cpp.
References GNEAttributeCarrier::getID(), GNELane::getShape(), PositionVector::length(), myGNELane, PointOfInterest::myPosLat, PointOfInterest::myPosOverLane, and PointOfInterest::writeXML().
writeXML()
void PointOfInterest::writeXML (OutputDevice & out, const bool geo = false, const double zOffset = 0., const std::string laneID = "", const double pos = 0., const double posLat = 0.) inline inherited
Definition at line 123 of file PointOfInterest.h.
References GeoConvHelper::cartesian2geo(), OutputDevice::closeTag(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, StringUtils::escapeXML(), Shape::getColor(), GeoConvHelper::getFinal(), PointOfInterest::getHeight(), Named::getID(), Shape::getImgFile(), Shape::getLayer(), Shape::getNaviDegree(), Shape::getType(), PointOfInterest::getWidth(), OutputDevice::openTag(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAT, SUMO_ATTR_LAYER, SUMO_ATTR_LON, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_POI, OutputDevice::writeAttr(), Parameterised::writeParams(), Position::x(), and Position::y().
Referenced by GNEPOI::writeShape(), and writeShape().
x()
double Position::x () const inline inherited
Returns the x-position.
Definition at line 62 of file Position.h.
References Position::myX.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), GNEDetectorE3::commitGeometryMoving(), NBPTStopCont::computeCrossProductEdgePosition(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), Boundary::distanceTo2D(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GUISUMOAbstractView::drawDecals(), GLHelper::drawFilledPoly(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEPoly::drawGL(), GNEEdge::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEShape::drawLockIcon(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextAtEnd(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), NBPTStopCont::findAccessEdgesForRailStops(), GeomHelper::findLineCircleIntersections(), GNEDetectorE3::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), PositionVector::getPolygonCenter(), libsumo::Person::getPosition(), libsumo::POI::getPosition(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), getPositionInView(), MSVTKExport::getPositions(), libsumo::InductionLoop::getTree(), GUIDanielPerspectiveChanger::getXPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), NBNodeCont::insert(), PositionVector::intersects(), PositionVector::isLeft(), GNENet::joinSelectedJunctions(), NBHeightMapper::loadTiff(), libsumo::Helper::makeTraCIPosition(), MSPModel_Striping::moveInDirection(), MSParkingArea::MSParkingArea(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE2Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), PCPolyContainer::saveDlrTDP(), Position::set(), GUIBaseVehicle::setFunctionalColor(), GNEStoppingPlace::setStoppingPlaceGeometry(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), Position::setx(), NGNode::setY(), PositionVector::sideOffset(), PositionVector::simplified(), GUISUMOAbstractView::snapToActiveGrid(), NBNetBuilder::transformCoordinate(), GNEAdditional::updateChildConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEDetectorE2::updateGeometry(), GNELane::updateGeometry(), GNEJunction::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), GNEDetectorE3::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
y()
double Position::y () const inline inherited
Returns the y-position.
Definition at line 67 of file Position.h.
References Position::myY.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), GNEDetectorE3::commitGeometryMoving(), NBPTStopCont::computeCrossProductEdgePosition(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), Boundary::distanceTo2D(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GUISUMOAbstractView::drawDecals(), GLHelper::drawFilledPoly(), GNEDetectorE1::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEPoly::drawGL(), GNEEdge::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEShape::drawLockIcon(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GLHelper::drawTextAtEnd(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), NBPTStopCont::findAccessEdgesForRailStops(), GeomHelper::findLineCircleIntersections(), GNEDetectorE3::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), libsumo::Person::getPosition(), libsumo::POI::getPosition(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), getPositionInView(), MSVTKExport::getPositions(), libsumo::InductionLoop::getTree(), GUIDanielPerspectiveChanger::getYPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), NBNodeCont::insert(), PositionVector::intersects(), PositionVector::isLeft(), GNENet::joinSelectedJunctions(), NBHeightMapper::loadTiff(), libsumo::Helper::makeTraCIPosition(), MSPModel_Striping::moveInDirection(), MSParkingArea::MSParkingArea(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIE2Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), PCPolyContainer::saveDlrTDP(), Position::set(), GUIBaseVehicle::setFunctionalColor(), GNEStoppingPlace::setStoppingPlaceGeometry(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setX(), Position::sety(), PositionVector::sideOffset(), PositionVector::simplified(), GUISUMOAbstractView::snapToActiveGrid(), NBNetBuilder::transformCoordinate(), GNEAdditional::updateChildConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEDetectorE2::updateGeometry(), GNELane::updateGeometry(), GNEJunction::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), GNEDetectorE3::writeAdditional(), GNEVariableSpeedSign::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
z()
double Position::z () const inline inherited
Returns the z-position.
Definition at line 72 of file Position.h.
References Position::myZ.
Referenced by Boundary::add(), PositionVector::add(), GUISettingsHandler::applyViewport(), Boundary::around(), bezier(), NBNode::bezierControlPoints(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBEdge::cutAtIntersection(), MSVTypeProbe::execute(), GUIJunctionWrapper::getColorValue(), GNEJunction::getColorValue(), PositionVector::getMaxGrade(), PositionVector::getOverlapWith(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), libsumo::POI::getPosition(), libsumo::Person::getPosition(), MSVTKExport::getPositions(), libsumo::Helper::makeTraCIPosition(), PositionVector::move2side(), GUISettingsHandler::myStartElement(), GNENet::registerJunction(), Position::set(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), Position::setz(), PositionVector::slopeDegreeAtOffset(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), NBEdge::startShapeAt(), GNEEdge::straightenElevation(), MSFCDExport::write(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_OpenDrive::writeGeomPP3(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), and MSFCDExport::writeTransportable().
Field Documentation
APPROVED
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 269 of file GNEAttributeCarrier.h.
DEFAULT_ANGLE
const double Shape::DEFAULT_ANGLE = 0 static inherited
Definition at line 150 of file Shape.h.
Referenced by libsumo::Polygon::add(), libsumo::POI::add(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
DEFAULT_IMG_FILE
const std::string Shape::DEFAULT_IMG_FILE = "" static inherited
Definition at line 151 of file Shape.h.
Referenced by libsumo::Polygon::add(), libsumo::POI::add(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
DEFAULT_IMG_HEIGHT
const double Shape::DEFAULT_IMG_HEIGHT = 1 static inherited
Definition at line 153 of file Shape.h.
Referenced by libsumo::POI::add(), ShapeHandler::addPOI(), and PointOfInterest::writeXML().
DEFAULT_IMG_WIDTH
const double Shape::DEFAULT_IMG_WIDTH = 1 static inherited
Definition at line 152 of file Shape.h.
Referenced by libsumo::POI::add(), ShapeHandler::addPOI(), and PointOfInterest::writeXML().
DEFAULT_LAYER
const double Shape::DEFAULT_LAYER = 128 static inherited
Definition at line 149 of file Shape.h.
Referenced by ShapeHandler::myStartElement().
DEFAULT_TYPE
const std::string Shape::DEFAULT_TYPE = "" static inherited
Definition at line 148 of file Shape.h.
Referenced by ShapeHandler::addPoly().
GUESSED
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 263 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::setAttribute(), and GNEEdge::setAttribute().
INVALID
const Position Position::INVALID static inherited
used to indicate that a position is valid
Definition at line 277 of file Position.h.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), NLShapeHandler::getLanePos(), PCLoaderXML::getLanePos(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), MSPModel_Striping::PState::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSVehicle::getPosition(), MSVehicle::getPositionAlongBestLanes(), MSParkingArea::getVehiclePosition(), PositionVector::intersectionPosition2D(), Position::invalidPosition(), PositionVector::move2side(), MSPModel_Striping::moveInDirection(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), PositionVector::positionAtOffset(), PositionVector::positionAtOffset2D(), MSPerson::MSPersonStage_Driving::proceed(), GUISUMOAbstractView::showViewportEditor(), MSLaneChangerSublane::startChangeSublane(), PositionVector::transformToVectorCoordinates(), MSVehicle::updateState(), and MSVehicle::validatePosition().
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
INVALID_POSITION
const double GNEAttributeCarrier::INVALID_POSITION = -1000000 static inherited
default value for invalid positions (used by POIs and Polygons)
Definition at line 272 of file GNEAttributeCarrier.h.
LOADED
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 260 of file GNEAttributeCarrier.h.
MODIFIED
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 266 of file GNEAttributeCarrier.h.
Referenced by GNEJunction::markAsModified(), and GNEConnectorFrame::onCmdClearSelectedConnections().
myBlockMovement
bool GNEShape::myBlockMovement protected inherited
flag to block movement
Definition at line 160 of file GNEShape.h.
Referenced by GNEPOI::commitGeometryMoving(), commitGeometryMoving(), GNEPoly::commitShapeChange(), GNEPoly::drawGL(), GNEShape::drawLockIcon(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), GNEShape::isMovementBlocked(), GNEPoly::moveEntireShape(), GNEPOI::moveGeometry(), GNEPoly::moveVertexShape(), GNEPOI::setAttribute(), setAttribute(), and GNEPoly::setAttribute().
myBlockShape
bool GNEShape::myBlockShape protected inherited
flag for block shape
Definition at line 163 of file GNEShape.h.
Referenced by GNEPoly::drawGL(), GNEPoly::getAttribute(), GNEShape::isShapeBlocked(), GNEPoly::moveEntireShape(), GNEPoly::moveVertexShape(), and GNEPoly::setAttribute().
myColor
RGBColor Shape::myColor protected inherited
The color of the Shape.
Definition at line 160 of file Shape.h.
Referenced by GNEPOI::drawGL(), drawGL(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), Shape::getColor(), GNEPOI::setAttribute(), setAttribute(), GNEPoly::setAttribute(), and Shape::setColor().
myGeo
bool PointOfInterest::myGeo protected inherited
flag to check if POI was loaded as GEO Position (main used by netedit)
Definition at line 167 of file PointOfInterest.h.
Referenced by GNEPOI::getAttribute(), GNEPOI::setAttribute(), and GNEPOI::writeShape().
myGNELane
GNELane* GNEPOILane::myGNELane protected
GNElane in which this POILane is placed.
Definition at line 171 of file GNEPOILane.h.
Referenced by commitGeometryMoving(), getAttribute(), getLane(), moveGeometry(), setAttribute(), updateGeometry(), and writeShape().
myHalfImgHeight
double PointOfInterest::myHalfImgHeight protected inherited
The half height of the image when rendering this POI.
Definition at line 182 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), PointOfInterest::getHeight(), and PointOfInterest::setHeight().
myHalfImgWidth
double PointOfInterest::myHalfImgWidth protected inherited
The half width of the image when rendering this POI.
Definition at line 179 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), PointOfInterest::getWidth(), and PointOfInterest::setWidth().
myID
std::string Named::myID protected inherited
The name of the object.
Definition at line 135 of file Named.h.
Referenced by MSE2Collector::addDetectorToLanes(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), MSE2Collector::detectorUpdate(), METriggeredCalibrator::execute(), MSCalibrator::execute(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), MSLane::getCanonicalPredecessorLane(), MSLane::getCanonicalSuccessorLane(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSDelayBasedTrafficLightLogic::init(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSLane::isInsertionSuccess(), MSCalibrator::myStartElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSE2Collector::notifyMove(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), GNEPOI::setAttribute(), setAttribute(), GNEPoly::setAttribute(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), Distribution_Parameterized::toStr(), MSChargingStation::writeChargingStationOutput(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
myImgFile
std::string Shape::myImgFile protected inherited
The angle of the Shape.
Definition at line 169 of file Shape.h.
Referenced by GUIPointOfInterest::drawGL(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), Shape::getImgFile(), GNEPOI::setAttribute(), setAttribute(), and Shape::setImgFile().
myLane
std::string PointOfInterest::myLane protected inherited
ID of lane in which this POI is placed (main used by netedit)
Definition at line 170 of file PointOfInterest.h.
Referenced by getAttribute(), and setAttribute().
myLayer
double Shape::myLayer protected inherited
The layer of the Shape.
Definition at line 163 of file Shape.h.
Referenced by GNEPOI::drawGL(), drawGL(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), Shape::getLayer(), GNEPOI::setAttribute(), setAttribute(), GNEPoly::setAttribute(), and Shape::setLayer().
myNaviDegreeAngle
double Shape::myNaviDegreeAngle protected inherited
The angle of the Shape.
Definition at line 166 of file Shape.h.
Referenced by Shape::getNaviDegree(), and Shape::setNaviDegree().
myNet
GNENet* GNEShape::myNet protected inherited
the net to inform about updates
Definition at line 157 of file GNEShape.h.
Referenced by GNEPoly::changeFirstGeometryPoint(), GNEPoly::closePolygon(), GNEPoly::deleteGeometryPoint(), GNEPoly::drawGL(), GNEShape::drawLockIcon(), GNEShape::getNet(), GNEPOI::getParentName(), getParentName(), GNEPoly::getParentName(), GNEPoly::getPopUpMenu(), GNEPOI::isValid(), isValid(), GNEPoly::isValid(), GNEPOI::moveGeometry(), GNEPoly::openPolygon(), GNEPOI::setAttribute(), setAttribute(), GNEPoly::setAttribute(), GNEPoly::simplifyShape(), GNEPOI::updateGeometry(), updateGeometry(), and GNEPoly::updateGeometry().
myObjectList
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected inherited
The list of all addtional objects currently loaded.
Definition at line 77 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
myObjects
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected inherited
Map from names of loaded additional objects to the objects themselves.
Definition at line 74 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
myPosLat
double PointOfInterest::myPosLat protected inherited
latereal position over lane in which this POI is placed (main used by netedit)
Definition at line 176 of file PointOfInterest.h.
Referenced by getAttribute(), setAttribute(), updateGeometry(), and writeShape().
myPosOverLane
double PointOfInterest::myPosOverLane protected inherited
position over lane in which this POI is placed (main used by netedit)
Definition at line 173 of file PointOfInterest.h.
Referenced by commitGeometryMoving(), getAttribute(), moveGeometry(), setAttribute(), updateGeometry(), and writeShape().
myType
std::string Shape::myType protected inherited
The type of the Shape.
Definition at line 157 of file Shape.h.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GNEPOI::getAttribute(), getAttribute(), GNEPoly::getAttribute(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), getPopUpMenu(), Shape::getType(), GNEPOI::setAttribute(), setAttribute(), GNEPoly::setAttribute(), and Shape::setType().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GNEPOILane.h
GNEPOILane.cpp