SUMO - Simulation of Urban MObility: RODFDetFlowLoader Class Reference
RODFDetFlowLoader Class Reference
A loader for detector flows.
#include <RODFDetFlowLoader.h>
Public Member Functions
void read (const std::string &file)
Reads the given file assuming it contains detector values.
RODFDetFlowLoader (const RODFDetectorCon &dets, RODFDetectorFlows &into, SUMOTime startTime, SUMOTime endTime, SUMOTime timeOffset, SUMOTime timeScale)
Constructor.
~RODFDetFlowLoader ()
Destructor.
Private Member Functions
RODFDetFlowLoader & operator= (const RODFDetFlowLoader &src)
Invalidated assignment operator.
RODFDetFlowLoader (const RODFDetFlowLoader &src)
Invalidated copy constructor.
Private Attributes
const RODFDetectorCon & myDetectorContainer
Container holding known detectors.
const SUMOTime myEndTime
bool myHaveWarnedAboutOverridingBoundaries
Whether a warning about overriding boundaries was already written.
bool myHaveWarnedAboutPartialDefs
Whether a warning about partial definitions was already written.
NamedColumnsParser myLineHandler
The value extractor.
const SUMOTime myStartTime
The first and the last time step to read.
RODFDetectorFlows & myStorage
The container for read detector values.
const SUMOTime myTimeOffset
The time offset to apply to read time values.
const SUMOTime myTimeScale
The time scale to apply to read time values.
Detailed Description
A loader for detector flows.
Definition at line 49 of file RODFDetFlowLoader.h.
Constructor & Destructor Documentation
RODFDetFlowLoader() [1/2]
RODFDetFlowLoader::RODFDetFlowLoader (const RODFDetectorCon & dets, RODFDetectorFlows & into, SUMOTime startTime, SUMOTime endTime, SUMOTime timeOffset, SUMOTime timeScale)
Constructor.
Parameters
[in] dets Definitions of known detectors
Definition at line 47 of file RODFDetFlowLoader.cpp.
~RODFDetFlowLoader()
RODFDetFlowLoader::~RODFDetFlowLoader ()
Destructor.
Definition at line 57 of file RODFDetFlowLoader.cpp.
RODFDetFlowLoader() [2/2]
RODFDetFlowLoader::RODFDetFlowLoader (const RODFDetFlowLoader & src) private
Invalidated copy constructor.
Member Function Documentation
operator=()
RODFDetFlowLoader& RODFDetFlowLoader::operator= (const RODFDetFlowLoader & src) private
Invalidated assignment operator.
read()
void RODFDetFlowLoader::read (const std::string & file)
Reads the given file assuming it contains detector values.
Reads the first line, first, and parses it assuming it contains the names of the columns that follow within the next lines.
Then, the rest of the file is read and the read values for vehicle/heavy vehicle amounts and speeds are stored into "myStorage". Values that lie before "myStartTime" and behind "myEndTime" as well as values which refer to an unknown detector are omitted.
Parameters
[in] file The name of the file to read
Exceptions
IOError Not yet implemented!
ProcessError Thrown if a value could not be parsed properly or a needed value is missing
Definition at line 61 of file RODFDetFlowLoader.cpp.
References TplConvert::_2double(), RODFDetectorFlows::addFlow(), fd, NamedColumnsParser::get(), LineReader::getFileName(), NamedColumnsParser::hasFullDefinition(), LineReader::hasMore(), FlowDef::isLKW, NamedColumnsParser::know(), RODFDetectorCon::knows(), myDetectorContainer, myEndTime, myHaveWarnedAboutOverridingBoundaries, myHaveWarnedAboutPartialDefs, myLineHandler, myStorage, myTimeOffset, myTimeScale, NamedColumnsParser::parseLine(), FlowDef::qLKW, FlowDef::qPKW, LineReader::readLine(), NamedColumnsParser::reinit(), FlowDef::vLKW, FlowDef::vPKW, and WRITE_WARNING.
Referenced by readDetectorFlows().
Field Documentation
myDetectorContainer
const RODFDetectorCon& RODFDetFlowLoader::myDetectorContainer private
Container holding known detectors.
Definition at line 102 of file RODFDetFlowLoader.h.
Referenced by read().
myEndTime
const SUMOTime RODFDetFlowLoader::myEndTime private
Definition at line 96 of file RODFDetFlowLoader.h.
Referenced by read().
myHaveWarnedAboutOverridingBoundaries
bool RODFDetFlowLoader::myHaveWarnedAboutOverridingBoundaries private
Whether a warning about overriding boundaries was already written.
Definition at line 105 of file RODFDetFlowLoader.h.
Referenced by read().
myHaveWarnedAboutPartialDefs
bool RODFDetFlowLoader::myHaveWarnedAboutPartialDefs private
Whether a warning about partial definitions was already written.
Definition at line 108 of file RODFDetFlowLoader.h.
Referenced by read().
myLineHandler
NamedColumnsParser RODFDetFlowLoader::myLineHandler private
The value extractor.
Definition at line 99 of file RODFDetFlowLoader.h.
Referenced by read().
myStartTime
const SUMOTime RODFDetFlowLoader::myStartTime private
The first and the last time step to read.
Definition at line 96 of file RODFDetFlowLoader.h.
myStorage
RODFDetectorFlows& RODFDetFlowLoader::myStorage private
The container for read detector values.
Definition at line 87 of file RODFDetFlowLoader.h.
Referenced by read().
myTimeOffset
const SUMOTime RODFDetFlowLoader::myTimeOffset private
The time offset to apply to read time values.
Definition at line 90 of file RODFDetFlowLoader.h.
Referenced by read().
myTimeScale
const SUMOTime RODFDetFlowLoader::myTimeScale private
The time scale to apply to read time values.
Definition at line 93 of file RODFDetFlowLoader.h.
Referenced by read().
The documentation for this class was generated from the following files:
RODFDetFlowLoader.h
RODFDetFlowLoader.cpp