SUMO - Simulation of Urban MObility: GNEChange_RerouterItem Class Reference
GNEChange_RerouterItem Class Reference
#include <GNEChange_RerouterItem.h>
Public Member Functions
GNEChange_RerouterItem (GNERerouterInterval *rerouterInterval, bool forward)
Constructor.
GNEChange_RerouterItem (GNEClosingReroute *closingReroute, bool forward)
Constructor.
GNEChange_RerouterItem (GNEClosingLaneReroute *closingLaneReroute, bool forward)
Constructor.
GNEChange_RerouterItem (GNEDestProbReroute *destProbReroute, bool forward)
Constructor.
GNEChange_RerouterItem (GNERouteProbReroute *routeProbReroute, bool forward)
Constructor.
virtual FXuint size () const
return actual size
~GNEChange_RerouterItem ()
Destructor.
inherited from GNEChange
get undo Name
FXString undoName () const
return undoName
FXString redoName () const
get Redo name
void undo ()
undo action
void redo ()
redo action
Protected Attributes
bool myForward
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
GNENet * myNet
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Private Attributes
GNEClosingLaneReroute * myClosingLaneReroute
modified Closing lane Reroute
GNEClosingReroute * myClosingReroute
modified Closing Reroute
GNEDestProbReroute * myDestProbReroute
modified Closing Interval
GNERerouterInterval * myRerouterInterval
modified rerouter interval
GNERouteProbReroute * myRouteProbReroute
modified Route Probability Reroute
Detailed Description
A change to the network selection
Definition at line 56 of file GNEChange_RerouterItem.h.
Constructor & Destructor Documentation
GNEChange_RerouterItem() [1/5]
GNEChange_RerouterItem::GNEChange_RerouterItem (GNERerouterInterval * rerouterInterval, bool forward)
Constructor.
Parameters
[in] rerouterInterval rerouter interval to be added
[in] forward Whether to create/delete (true/false)
Definition at line 52 of file GNEChange_RerouterItem.cpp.
GNEChange_RerouterItem() [2/5]
GNEChange_RerouterItem::GNEChange_RerouterItem (GNEClosingReroute * closingReroute, bool forward)
Constructor.
Parameters
[in] closingReroute Closing Reroute to be added
[in] forward Whether to create/delete (true/false)
Definition at line 63 of file GNEChange_RerouterItem.cpp.
References GNEReferenceCounter::incRef(), and myClosingReroute.
GNEChange_RerouterItem() [3/5]
GNEChange_RerouterItem::GNEChange_RerouterItem (GNEClosingLaneReroute * closingLaneReroute, bool forward)
Constructor.
Parameters
[in] closingLaneReroute Closing Lane Reroute to be added
[in] forward Whether to create/delete (true/false)
Definition at line 74 of file GNEChange_RerouterItem.cpp.
References GNEReferenceCounter::incRef(), and myClosingLaneReroute.
GNEChange_RerouterItem() [4/5]
GNEChange_RerouterItem::GNEChange_RerouterItem (GNEDestProbReroute * destProbReroute, bool forward)
Constructor.
Parameters
[in] destProbReroute Destiny Probability Reroute to be added
[in] forward Whether to create/delete (true/false)
Definition at line 85 of file GNEChange_RerouterItem.cpp.
References GNEReferenceCounter::incRef(), and myDestProbReroute.
GNEChange_RerouterItem() [5/5]
GNEChange_RerouterItem::GNEChange_RerouterItem (GNERouteProbReroute * routeProbReroute, bool forward)
Constructor.
Parameters
[in] routeProbReroute Route Probability Reroute to be added
[in] forward Whether to create/delete (true/false)
Definition at line 96 of file GNEChange_RerouterItem.cpp.
References GNEReferenceCounter::incRef(), and myRouteProbReroute.
~GNEChange_RerouterItem()
GNEChange_RerouterItem::~GNEChange_RerouterItem ()
Destructor.
Definition at line 107 of file GNEChange_RerouterItem.cpp.
References GNEReferenceCounter::decRef(), OptionsCont::getBool(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), GNERouteProbReroute::getRerouterIntervalParent(), GNEDestProbReroute::getRerouterIntervalParent(), GNEClosingReroute::getRerouterIntervalParent(), GNEClosingLaneReroute::getRerouterIntervalParent(), GNERerouterInterval::getRerouterParent(), myClosingLaneReroute, myClosingReroute, myDestProbReroute, myRerouterInterval, myRouteProbReroute, GNEReferenceCounter::unreferenced(), and WRITE_WARNING.
Member Function Documentation
redo()
void GNEChange_RerouterItem::redo () virtual
redo action
Reimplemented from GNEChange.
Definition at line 244 of file GNEChange_RerouterItem.cpp.
References GNERerouterInterval::addClosingLaneReroute(), GNERerouterInterval::addClosingReroute(), GNERerouterInterval::addDestProbReroute(), GNERerouter::addRerouterInterval(), GNERerouterInterval::addRouteProbReroute(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), GNERouteProbReroute::getRerouterIntervalParent(), GNEDestProbReroute::getRerouterIntervalParent(), GNEClosingReroute::getRerouterIntervalParent(), GNEClosingLaneReroute::getRerouterIntervalParent(), GNERerouterInterval::getRerouterParent(), myClosingLaneReroute, myClosingReroute, myDestProbReroute, GNEChange::myForward, GNEChange::myNet, myRerouterInterval, myRouteProbReroute, GNERerouterInterval::removeClosingLaneReroute(), GNERerouterInterval::removeClosingReroute(), GNERerouterInterval::removeDestProbReroute(), GNERerouter::removeRerouterInterval(), GNERerouterInterval::removeRouteProbReroute(), GNENet::requiereSaveAdditionals(), and WRITE_WARNING.
redoName()
FXString GNEChange_RerouterItem::redoName () const virtual
get Redo name
Reimplemented from GNEChange.
Definition at line 348 of file GNEChange_RerouterItem.cpp.
References GNEAttributeCarrier::getTag(), myClosingLaneReroute, myClosingReroute, myDestProbReroute, myRerouterInterval, myRouteProbReroute, and toString().
size()
FXuint GNEChange::size () const virtual inherited
return actual size
Definition at line 52 of file GNEChange.cpp.
undo()
void GNEChange_RerouterItem::undo () virtual
undo action
Reimplemented from GNEChange.
Definition at line 158 of file GNEChange_RerouterItem.cpp.
References GNERerouterInterval::addClosingLaneReroute(), GNERerouterInterval::addClosingReroute(), GNERerouterInterval::addDestProbReroute(), GNERerouter::addRerouterInterval(), GNERerouterInterval::addRouteProbReroute(), GNEAttributeCarrier::getID(), OptionsCont::getOptions(), GNERouteProbReroute::getRerouterIntervalParent(), GNEDestProbReroute::getRerouterIntervalParent(), GNEClosingReroute::getRerouterIntervalParent(), GNEClosingLaneReroute::getRerouterIntervalParent(), GNERerouterInterval::getRerouterParent(), myClosingLaneReroute, myClosingReroute, myDestProbReroute, GNEChange::myForward, GNEChange::myNet, myRerouterInterval, myRouteProbReroute, GNERerouterInterval::removeClosingLaneReroute(), GNERerouterInterval::removeClosingReroute(), GNERerouterInterval::removeDestProbReroute(), GNERerouter::removeRerouterInterval(), GNERerouterInterval::removeRouteProbReroute(), GNENet::requiereSaveAdditionals(), and WRITE_WARNING.
undoName()
FXString GNEChange_RerouterItem::undoName () const virtual
return undoName
Reimplemented from GNEChange.
Definition at line 330 of file GNEChange_RerouterItem.cpp.
References GNEAttributeCarrier::getTag(), myClosingLaneReroute, myClosingReroute, myDestProbReroute, myRerouterInterval, myRouteProbReroute, and toString().
Field Documentation
myClosingLaneReroute
GNEClosingLaneReroute* GNEChange_RerouterItem::myClosingLaneReroute private
modified Closing lane Reroute
Definition at line 116 of file GNEChange_RerouterItem.h.
Referenced by GNEChange_RerouterItem(), redo(), redoName(), undo(), undoName(), and ~GNEChange_RerouterItem().
myClosingReroute
GNEClosingReroute* GNEChange_RerouterItem::myClosingReroute private
modified Closing Reroute
Definition at line 113 of file GNEChange_RerouterItem.h.
Referenced by GNEChange_RerouterItem(), redo(), redoName(), undo(), undoName(), and ~GNEChange_RerouterItem().
myDestProbReroute
GNEDestProbReroute* GNEChange_RerouterItem::myDestProbReroute private
modified Closing Interval
Definition at line 119 of file GNEChange_RerouterItem.h.
Referenced by GNEChange_RerouterItem(), redo(), redoName(), undo(), undoName(), and ~GNEChange_RerouterItem().
myForward
bool GNEChange::myForward protected inherited
we group antagonistic commands (create junction/delete junction) and keep them apart by this flag
Definition at line 86 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_Selection::redo(), GNEChange_TLS::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Additional::redo(), GNEChange_Connection::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNEChange_CalibratorItem::redo(), redo(), GNEChange_Shape::redoName(), GNEChange_Junction::redoName(), GNEChange_Selection::redoName(), GNEChange_TLS::redoName(), GNEChange_Additional::redoName(), GNEChange_Connection::redoName(), GNEChange_Lane::redoName(), GNEChange_Edge::redoName(), GNEChange_Crossing::redoName(), GNEChange_Shape::undo(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_TLS::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Connection::undo(), GNEChange_Lane::undo(), GNEChange_Additional::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNEChange_CalibratorItem::undo(), undo(), GNEChange_Shape::undoName(), GNEChange_Junction::undoName(), GNEChange_Selection::undoName(), GNEChange_TLS::undoName(), GNEChange_Lane::undoName(), GNEChange_Additional::undoName(), GNEChange_Connection::undoName(), GNEChange_Edge::undoName(), and GNEChange_Crossing::undoName().
myNet
GNENet* GNEChange::myNet protected inherited
the net to which operations shall be applied or which shall be informed about gui updates (we are not responsible for the pointer)
Definition at line 81 of file GNEChange.h.
Referenced by GNEChange_Junction::redo(), GNEChange_Shape::redo(), GNEChange_Selection::redo(), GNEChange_VariableSpeedSignItem::redo(), GNEChange_Additional::redo(), GNEChange_Lane::redo(), GNEChange_Edge::redo(), GNEChange_Crossing::redo(), GNEChange_CalibratorItem::redo(), redo(), GNEChange_Shape::undo(), GNEChange_Junction::undo(), GNEChange_Selection::undo(), GNEChange_VariableSpeedSignItem::undo(), GNEChange_Additional::undo(), GNEChange_Lane::undo(), GNEChange_Edge::undo(), GNEChange_Crossing::undo(), GNEChange_CalibratorItem::undo(), undo(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Crossing::~GNEChange_Crossing(), and GNEChange_Shape::~GNEChange_Shape().
myRerouterInterval
GNERerouterInterval* GNEChange_RerouterItem::myRerouterInterval private
modified rerouter interval
Definition at line 110 of file GNEChange_RerouterItem.h.
Referenced by redo(), redoName(), undo(), undoName(), and ~GNEChange_RerouterItem().
myRouteProbReroute
GNERouteProbReroute* GNEChange_RerouterItem::myRouteProbReroute private
modified Route Probability Reroute
Definition at line 122 of file GNEChange_RerouterItem.h.
Referenced by GNEChange_RerouterItem(), redo(), redoName(), undo(), undoName(), and ~GNEChange_RerouterItem().
The documentation for this class was generated from the following files:
GNEChange_RerouterItem.h
GNEChange_RerouterItem.cpp