SUMO - Simulation of Urban MObility: NIVissimNodeParticipatingEdge Class Reference
NIVissimNodeParticipatingEdge Class Reference
#include <NIVissimNodeParticipatingEdge.h>
Public Member Functions
double getFromPos () const
int getID () const
double getToPos () const
NIVissimNodeParticipatingEdge (int edgeid, double frompos, double topos)
bool positionLiesWithin (double pos) const
~NIVissimNodeParticipatingEdge ()
Private Attributes
int myEdgeID
double myFromPos
double myToPos
Detailed Description
Definition at line 43 of file NIVissimNodeParticipatingEdge.h.
Constructor & Destructor Documentation
NIVissimNodeParticipatingEdge()
NIVissimNodeParticipatingEdge::NIVissimNodeParticipatingEdge (int edgeid, double frompos, double topos)
Definition at line 37 of file NIVissimNodeParticipatingEdge.cpp.
~NIVissimNodeParticipatingEdge()
NIVissimNodeParticipatingEdge::~NIVissimNodeParticipatingEdge ()
Definition at line 41 of file NIVissimNodeParticipatingEdge.cpp.
Member Function Documentation
getFromPos()
double NIVissimNodeParticipatingEdge::getFromPos () const
Definition at line 59 of file NIVissimNodeParticipatingEdge.cpp.
References myFromPos.
Referenced by NIVissimNodeDef_Edges::getEdgePosition().
getID()
int NIVissimNodeParticipatingEdge::getID () const
Definition at line 45 of file NIVissimNodeParticipatingEdge.cpp.
References myEdgeID.
Referenced by NIVissimNodeDef_Edges::getEdgePosition(), and NIVissimNodeDef_Edges::id_matches::operator()().
getToPos()
double NIVissimNodeParticipatingEdge::getToPos () const
Definition at line 65 of file NIVissimNodeParticipatingEdge.cpp.
References myToPos.
Referenced by NIVissimNodeDef_Edges::getEdgePosition().
positionLiesWithin()
bool NIVissimNodeParticipatingEdge::positionLiesWithin (double pos) const
Definition at line 51 of file NIVissimNodeParticipatingEdge.cpp.
References myFromPos, and myToPos.
Field Documentation
myEdgeID
int NIVissimNodeParticipatingEdge::myEdgeID private
Definition at line 53 of file NIVissimNodeParticipatingEdge.h.
Referenced by getID().
myFromPos
double NIVissimNodeParticipatingEdge::myFromPos private
Definition at line 54 of file NIVissimNodeParticipatingEdge.h.
Referenced by getFromPos(), and positionLiesWithin().
myToPos
double NIVissimNodeParticipatingEdge::myToPos private
Definition at line 54 of file NIVissimNodeParticipatingEdge.h.
Referenced by getToPos(), and positionLiesWithin().
The documentation for this class was generated from the following files:
NIVissimNodeParticipatingEdge.h
NIVissimNodeParticipatingEdge.cpp