SUMO - Simulation of Urban MObility: GNEDialog_Wizard Class Reference
GNEDialog_Wizard Class Reference
#include <GNEDialog_Wizard.h>
Data Structures
class InputBool
class InputFloat
class InputInt
class InputString
Public Member Functions
GNEDialog_Wizard (FXWindow *parent, const char *titleName, int width, int height)
Constructor.
~GNEDialog_Wizard ()
Destructor.
Detailed Description
Dialog for setting options (see OptionsCont)
Definition at line 42 of file GNEDialog_Wizard.h.
Constructor & Destructor Documentation
GNEDialog_Wizard()
GNEDialog_Wizard::GNEDialog_Wizard (FXWindow * parent, const char * titleName, int width, int height)
Constructor.
Parameters
[in] parent The parent window
[in] name The title to show
[in] width The initial width of the dialog
[in] height The initial height of the dialog
Definition at line 64 of file GNEDialog_Wizard.cpp.
References GUIIconSubSys::getIcon(), OptionsCont::getOptions(), OptionsCont::getSubTopics(), OptionsCont::getSubTopicsEntries(), OptionsCont::getTypeName(), GUIDesignButtonOK, GUIDesignContentsFrame, GUIDesignTabBook, and ICON_ACCEPT.
~GNEDialog_Wizard()
GNEDialog_Wizard::~GNEDialog_Wizard ()
Destructor.
Definition at line 101 of file GNEDialog_Wizard.cpp.
The documentation for this class was generated from the following files:
GNEDialog_Wizard.h
GNEDialog_Wizard.cpp