SUMO - Simulation of Urban MObility: NIVissimExtendedEdgePoint Class Reference
NIVissimExtendedEdgePoint Class Reference
#include <NIVissimExtendedEdgePoint.h>
Public Member Functions
int getEdgeID () const
Position getGeomPosition () const
const std::vector< int > & getLanes () const
double getPosition () const
NIVissimExtendedEdgePoint (int edgeid, const std::vector< int > &lanes, double position, const std::vector< int > &assignedVehicles)
Constructor.
void recheckLanes (const NBEdge *const edge)
Resets lane numbers if all lanes shall be used.
~NIVissimExtendedEdgePoint ()
Private Attributes
std::vector< int > myAssignedVehicles
int myEdgeID
std::vector< int > myLanes
double myPosition
Detailed Description
Definition at line 49 of file NIVissimExtendedEdgePoint.h.
Constructor & Destructor Documentation
NIVissimExtendedEdgePoint()
NIVissimExtendedEdgePoint::NIVissimExtendedEdgePoint (int edgeid, const std::vector< int > & lanes, double position, const std::vector< int > & assignedVehicles)
Constructor.
Parameters
[in] edgeid The id of the Vissim-edge
[in] lanes Lanes on which this point lies
[in] position The position of this point at the edge
[in] assignedVehicles Vehicle (type) indices which should be regarded by this point
Definition at line 40 of file NIVissimExtendedEdgePoint.cpp.
~NIVissimExtendedEdgePoint()
NIVissimExtendedEdgePoint::~NIVissimExtendedEdgePoint ()
Definition at line 47 of file NIVissimExtendedEdgePoint.cpp.
Member Function Documentation
getEdgeID()
int NIVissimExtendedEdgePoint::getEdgeID () const
Definition at line 51 of file NIVissimExtendedEdgePoint.cpp.
References myEdgeID.
Referenced by NIVissimDisturbance::addToNode(), NIVissimDisturbance::computeBounding(), NIVissimDisturbance::dict_SetDisturbances(), NIVissimDisturbance::getConnection(), NIVissimDisturbance::getDisturbanceID(), NIVissimDisturbance::getEdgeID(), NIVissimConnection::getFromEdgeID(), NIVissimConnection::getToEdgeID(), and NIVissimNodeDef_Edges::lying_within_match::operator()().
getGeomPosition()
Position NIVissimExtendedEdgePoint::getGeomPosition () const
Definition at line 63 of file NIVissimExtendedEdgePoint.cpp.
References NIVissimAbstractEdge::dictionary(), myEdgeID, and myPosition.
Referenced by NIVissimConnection::buildGeom(), NIVissimDisturbance::computeBounding(), NIVissimConnection::computeBounding(), NIVissimConnection::getFromGeomPosition(), and NIVissimConnection::getToGeomPosition().
getLanes()
const std::vector< int > & NIVissimExtendedEdgePoint::getLanes () const
Definition at line 70 of file NIVissimExtendedEdgePoint.cpp.
References myLanes.
Referenced by NIVissimConnection::getFromLanes(), and NIVissimConnection::getToLanes().
getPosition()
double NIVissimExtendedEdgePoint::getPosition () const
Definition at line 57 of file NIVissimExtendedEdgePoint.cpp.
References myPosition.
Referenced by NIVissimDisturbance::addToNode(), NIVissimConnection::getFromPosition(), NIVissimConnection::getToPosition(), and NIVissimNodeDef_Edges::lying_within_match::operator()().
recheckLanes()
void NIVissimExtendedEdgePoint::recheckLanes (const NBEdge *const edge)
Resets lane numbers if all lanes shall be used.
If myLanes contains a -1, the content of myLanes is replaced by indices of all lanes of the given edge.
Parameters
[in] The built edge
Definition at line 76 of file NIVissimExtendedEdgePoint.cpp.
References NBEdge::getNumLanes(), and myLanes.
Referenced by NIVissimConnection::recheckLanes().
Field Documentation
myAssignedVehicles
std::vector<int> NIVissimExtendedEdgePoint::myAssignedVehicles private
Definition at line 79 of file NIVissimExtendedEdgePoint.h.
myEdgeID
int NIVissimExtendedEdgePoint::myEdgeID private
Definition at line 76 of file NIVissimExtendedEdgePoint.h.
Referenced by getEdgeID(), and getGeomPosition().
myLanes
std::vector<int> NIVissimExtendedEdgePoint::myLanes private
Definition at line 77 of file NIVissimExtendedEdgePoint.h.
Referenced by getLanes(), and recheckLanes().
myPosition
double NIVissimExtendedEdgePoint::myPosition private
Definition at line 78 of file NIVissimExtendedEdgePoint.h.
Referenced by getGeomPosition(), and getPosition().
The documentation for this class was generated from the following files:
NIVissimExtendedEdgePoint.h
NIVissimExtendedEdgePoint.cpp