SUMO - Simulation of Urban MObility: TraCIAPI::GUIScope Class Reference
TraCIAPI::GUIScope Class Reference
Scope for interaction with the gui.
#include <TraCIAPI.h>
Public Member Functions
libsumo::TraCIBoundary getBoundary (const std::string &viewID=DEFAULT_VIEW) const
std::vector< std::string > getIDList () const
libsumo::TraCIPosition getOffset (const std::string &viewID=DEFAULT_VIEW) const
std::string getSchema (const std::string &viewID=DEFAULT_VIEW) const
double getZoom (const std::string &viewID=DEFAULT_VIEW) const
GUIScope (TraCIAPI &parent)
void screenshot (const std::string &viewID, const std::string &filename) const
void setBoundary (const std::string &viewID, double xmin, double ymin, double xmax, double ymax) const
void setOffset (const std::string &viewID, double x, double y) const
void setSchema (const std::string &viewID, const std::string &schemeName) const
void setZoom (const std::string &viewID, double zoom) const
void trackVehicle (const std::string &viewID, const std::string &vehID) const
virtual ~GUIScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
GUIScope (const GUIScope &src)
invalidated copy constructor
GUIScope & operator= (const GUIScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with the gui.
Definition at line 193 of file TraCIAPI.h.
Constructor & Destructor Documentation
GUIScope() [1/2]
TraCIAPI::GUIScope::GUIScope (TraCIAPI & parent) inline
Definition at line 195 of file TraCIAPI.h.
~GUIScope()
virtual TraCIAPI::GUIScope::~GUIScope () inline virtual
Definition at line 196 of file TraCIAPI.h.
References DEFAULT_VIEW, and TraCIAPI::TraCIScopeWrapper::operator=().
GUIScope() [2/2]
TraCIAPI::GUIScope::GUIScope (const GUIScope & src) private
invalidated copy constructor
Member Function Documentation
getBoundary()
TraCIBoundary TraCIAPI::GUIScope::getBoundary (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 804 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_BOUNDARY.
getIDList()
std::vector< std::string > TraCIAPI::GUIScope::getIDList () const
Definition at line 784 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and ID_LIST.
getOffset()
TraCIPosition TraCIAPI::GUIScope::getOffset (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 794 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_OFFSET.
getSchema()
std::string TraCIAPI::GUIScope::getSchema (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 799 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_SCHEMA.
Referenced by TraCITestClient::testAPI().
getZoom()
double TraCIAPI::GUIScope::getZoom (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 789 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_ZOOM.
operator=()
GUIScope& TraCIAPI::GUIScope::operator= (const GUIScope & src) private
invalidated assignment operator
screenshot()
void TraCIAPI::GUIScope::screenshot (const std::string & viewID, const std::string & filename) const
Definition at line 853 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_STRING, VAR_SCREENSHOT, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setBoundary()
void TraCIAPI::GUIScope::setBoundary (const std::string & viewID, double xmin, double ymin, double xmax, double ymax) const
Definition at line 840 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_BOUNDINGBOX, VAR_VIEW_BOUNDARY, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
setOffset()
void TraCIAPI::GUIScope::setOffset (const std::string & viewID, double x, double y) const
Definition at line 819 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, POSITION_2D, VAR_VIEW_OFFSET, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
setSchema()
void TraCIAPI::GUIScope::setSchema (const std::string & viewID, const std::string & schemeName) const
Definition at line 830 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_STRING, VAR_VIEW_SCHEMA, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
setZoom()
void TraCIAPI::GUIScope::setZoom (const std::string & viewID, double zoom) const
Definition at line 810 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, VAR_VIEW_ZOOM, and tcpip::Storage::writeDouble().
trackVehicle()
void TraCIAPI::GUIScope::trackVehicle (const std::string & viewID, const std::string & vehID) const
Definition at line 863 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_STRING, VAR_TRACK_VEHICLE, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp