SUMO - Simulation of Urban MObility: MSSOTLPolicy5DStimulus Class Reference
MSSOTLPolicy5DStimulus Class Reference
#include <MSSOTLPolicy5DStimulus.h>
Public Member Functions
void clearParameter ()
Clears the parameter map.
virtual double computeDesirability (double vehInMeasure, double vehOutMeasure)
Computes stimulus function stimulus = cox * exp(-pow(pheroIn - offsetIn, 2)/divisor -pow(pheroOut - offsetOut, 2)/divisor);.
virtual double computeDesirability (double vehInMeasure, double vehOutMeasure, double vehInDispersionMeasure, double vehOutDispersionMeasure)
Calculates the desirability of the policy.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
std::string getKeyPrefix ()
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
std::string getMessage ()
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
double getStimCox ()
double getStimCoxExpDispersionIn ()
double getStimCoxExpDispersionOut ()
double getStimCoxExpIn ()
double getStimCoxExpOut ()
double getStimDivisorDispersionIn ()
double getStimDivisorDispersionOut ()
double getStimDivisorIn ()
double getStimDivisorOut ()
double getStimOffsetDispersionIn ()
double getStimOffsetDispersionOut ()
double getStimOffsetIn ()
double getStimOffsetOut ()
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSSOTLPolicy5DStimulus (std::string keyPrefix, const std::map< std::string, std::string > &parameters)
void setKeyPrefix (std::string val)
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void setStimCoxDefVal (double defVal)
void setStimCoxExpDispersionInDefVal (double defVal)
void setStimCoxExpDispersionOutDefVal (double defVal)
void setStimCoxExpInDefVal (double defVal)
void setStimCoxExpOutDefVal (double defVal)
void setStimDivisorDispersionInDefVal (double defVal)
void setStimDivisorDispersionOutDefVal (double defVal)
void setStimDivisorInDefVal (double defVal)
void setStimDivisorOutDefVal (double defVal)
void setStimOffsetDispersionInDefVal (double defVal)
void setStimOffsetDispersionOutDefVal (double defVal)
void setStimOffsetInDefVal (double defVal)
void setStimOffsetOutDefVal (double defVal)
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
Protected Member Functions
double readParameter (std::string parName, double defValue)
Private Attributes
double stimCoxDVal
double stimCoxExpDispersionInDVal
double stimCoxExpDispersionOutDVal
double stimCoxExpInDVal
double stimCoxExpOutDVal
double stimDivDispersionInDVal
double stimDivDispersionOutDVal
double stimDivInDVal
double stimDivOutDVal
double stimOffsetDispersionInDVal
double stimOffsetDispersionOutDVal
double stimOffsetInDVal
double stimOffsetOutDVal
Detailed Description
Definition at line 47 of file MSSOTLPolicy5DStimulus.h.
Constructor & Destructor Documentation
MSSOTLPolicy5DStimulus()
MSSOTLPolicy5DStimulus::MSSOTLPolicy5DStimulus (std::string keyPrefix, const std::map< std::string, std::string > & parameters)
Definition at line 23 of file MSSOTLPolicy5DStimulus.cpp.
References stimCoxDVal, stimCoxExpDispersionInDVal, stimCoxExpDispersionOutDVal, stimCoxExpInDVal, stimCoxExpOutDVal, stimDivDispersionInDVal, stimDivDispersionOutDVal, stimDivInDVal, stimDivOutDVal, stimOffsetDispersionInDVal, stimOffsetDispersionOutDVal, stimOffsetInDVal, and stimOffsetOutDVal.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
computeDesirability() [1/2]
double MSSOTLPolicy5DStimulus::computeDesirability (double vehInMeasure, double vehOutMeasure) virtual
Computes stimulus function stimulus = cox * exp(-pow(pheroIn - offsetIn, 2)/divisor -pow(pheroOut - offsetOut, 2)/divisor);.
Implements MSSOTLPolicyDesirability.
Definition at line 80 of file MSSOTLPolicy5DStimulus.cpp.
Referenced by setStimCoxExpDispersionOutDefVal().
computeDesirability() [2/2]
double MSSOTLPolicy5DStimulus::computeDesirability (double vehInMeasure, double vehOutMeasure, double vehInDispersionMeasure, double vehOutDispersionMeasure) virtual
Calculates the desirability of the policy.
Implements MSSOTLPolicyDesirability.
Definition at line 42 of file MSSOTLPolicy5DStimulus.cpp.
References DBG, getStimCox(), getStimCoxExpDispersionIn(), getStimCoxExpDispersionOut(), getStimCoxExpIn(), getStimCoxExpOut(), getStimDivisorDispersionIn(), getStimDivisorDispersionOut(), getStimDivisorIn(), getStimDivisorOut(), getStimOffsetDispersionIn(), getStimOffsetDispersionOut(), getStimOffsetIn(), getStimOffsetOut(), WRITE_ERROR, and WRITE_MESSAGE.
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getKeyPrefix()
std::string MSSOTLPolicyDesirability::getKeyPrefix () inline inherited
Definition at line 73 of file MSSOTLPolicyDesirability.h.
References MSSOTLPolicyDesirability::myKeyPrefix.
Referenced by getStimCox(), getStimCoxExpDispersionIn(), getStimCoxExpDispersionOut(), getStimCoxExpIn(), getStimCoxExpOut(), getStimDivisorDispersionIn(), getStimDivisorDispersionOut(), getStimDivisorIn(), getStimDivisorOut(), getStimOffsetDispersionIn(), getStimOffsetDispersionOut(), getStimOffsetIn(), and getStimOffsetOut().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getMessage()
std::string MSSOTLPolicy5DStimulus::getMessage () virtual
Implements MSSOTLPolicyDesirability.
Definition at line 84 of file MSSOTLPolicy5DStimulus.cpp.
References getStimCox(), getStimCoxExpIn(), getStimCoxExpOut(), getStimDivisorIn(), getStimDivisorOut(), getStimOffsetIn(), and getStimOffsetOut().
Referenced by setStimCoxExpDispersionOutDefVal().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
getStimCox()
double MSSOTLPolicy5DStimulus::getStimCox () inline
Definition at line 60 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
getStimCoxExpDispersionIn()
double MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn () inline
Definition at line 146 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability().
getStimCoxExpDispersionOut()
double MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut () inline
Definition at line 153 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability().
getStimCoxExpIn()
double MSSOTLPolicy5DStimulus::getStimCoxExpIn () inline
Definition at line 131 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
getStimCoxExpOut()
double MSSOTLPolicy5DStimulus::getStimCoxExpOut () inline
Definition at line 138 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
getStimDivisorDispersionIn()
double MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn () inline
Definition at line 115 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability().
getStimDivisorDispersionOut()
double MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut () inline
Definition at line 123 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability().
getStimDivisorIn()
double MSSOTLPolicy5DStimulus::getStimDivisorIn () inline
Definition at line 97 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
getStimDivisorOut()
double MSSOTLPolicy5DStimulus::getStimDivisorOut () inline
Definition at line 106 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
getStimOffsetDispersionIn()
double MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn () inline
Definition at line 83 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability().
getStimOffsetDispersionOut()
double MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut () inline
Definition at line 90 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability().
getStimOffsetIn()
double MSSOTLPolicy5DStimulus::getStimOffsetIn () inline
Definition at line 67 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
getStimOffsetOut()
double MSSOTLPolicy5DStimulus::getStimOffsetOut () inline
Definition at line 74 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by computeDesirability(), and getMessage().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
readParameter()
double MSSOTLPolicyDesirability::readParameter (std::string parName, double defValue) inline protected inherited
Definition at line 48 of file MSSOTLPolicyDesirability.h.
References TplConvert::_2doubleSec(), MSSOTLPolicyDesirability::computeDesirability(), MSSOTLPolicyDesirability::getMessage(), Parameterised::getParameter(), MSSOTLPolicyDesirability::MSSOTLPolicyDesirability(), and MSSOTLPolicyDesirability::~MSSOTLPolicyDesirability().
Referenced by getStimCox(), getStimCoxExpDispersionIn(), getStimCoxExpDispersionOut(), getStimCoxExpIn(), getStimCoxExpOut(), getStimDivisorDispersionIn(), getStimDivisorDispersionOut(), getStimDivisorIn(), getStimDivisorOut(), getStimOffsetDispersionIn(), getStimOffsetDispersionOut(), getStimOffsetIn(), getStimOffsetOut(), and MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus().
setKeyPrefix()
void MSSOTLPolicyDesirability::setKeyPrefix (std::string val) inline inherited
Definition at line 70 of file MSSOTLPolicyDesirability.h.
Referenced by MSSOTLCongestionPolicy::MSSOTLCongestionPolicy(), MSSOTLMarchingPolicy::MSSOTLMarchingPolicy(), MSSOTLPhasePolicy::MSSOTLPhasePolicy(), MSSOTLPlatoonPolicy::MSSOTLPlatoonPolicy(), and MSSOTLRequestPolicy::MSSOTLRequestPolicy().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
setStimCoxDefVal()
void MSSOTLPolicy5DStimulus::setStimCoxDefVal (double defVal) inline
Definition at line 64 of file MSSOTLPolicy5DStimulus.h.
setStimCoxExpDispersionInDefVal()
void MSSOTLPolicy5DStimulus::setStimCoxExpDispersionInDefVal (double defVal) inline
Definition at line 150 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy3DStimulus::MSSOTLPolicy3DStimulus().
setStimCoxExpDispersionOutDefVal()
void MSSOTLPolicy5DStimulus::setStimCoxExpDispersionOutDefVal (double defVal) inline
Definition at line 157 of file MSSOTLPolicy5DStimulus.h.
References computeDesirability(), and getMessage().
Referenced by MSSOTLPolicy3DStimulus::MSSOTLPolicy3DStimulus().
setStimCoxExpInDefVal()
void MSSOTLPolicy5DStimulus::setStimCoxExpInDefVal (double defVal) inline
Definition at line 135 of file MSSOTLPolicy5DStimulus.h.
setStimCoxExpOutDefVal()
void MSSOTLPolicy5DStimulus::setStimCoxExpOutDefVal (double defVal) inline
Definition at line 142 of file MSSOTLPolicy5DStimulus.h.
setStimDivisorDispersionInDefVal()
void MSSOTLPolicy5DStimulus::setStimDivisorDispersionInDefVal (double defVal) inline
Definition at line 120 of file MSSOTLPolicy5DStimulus.h.
setStimDivisorDispersionOutDefVal()
void MSSOTLPolicy5DStimulus::setStimDivisorDispersionOutDefVal (double defVal) inline
Definition at line 128 of file MSSOTLPolicy5DStimulus.h.
setStimDivisorInDefVal()
void MSSOTLPolicy5DStimulus::setStimDivisorInDefVal (double defVal) inline
Definition at line 102 of file MSSOTLPolicy5DStimulus.h.
setStimDivisorOutDefVal()
void MSSOTLPolicy5DStimulus::setStimDivisorOutDefVal (double defVal) inline
Definition at line 111 of file MSSOTLPolicy5DStimulus.h.
setStimOffsetDispersionInDefVal()
void MSSOTLPolicy5DStimulus::setStimOffsetDispersionInDefVal (double defVal) inline
Definition at line 87 of file MSSOTLPolicy5DStimulus.h.
setStimOffsetDispersionOutDefVal()
void MSSOTLPolicy5DStimulus::setStimOffsetDispersionOutDefVal (double defVal) inline
Definition at line 94 of file MSSOTLPolicy5DStimulus.h.
setStimOffsetInDefVal()
void MSSOTLPolicy5DStimulus::setStimOffsetInDefVal (double defVal) inline
Definition at line 71 of file MSSOTLPolicy5DStimulus.h.
setStimOffsetOutDefVal()
void MSSOTLPolicy5DStimulus::setStimOffsetOutDefVal (double defVal) inline
Definition at line 79 of file MSSOTLPolicy5DStimulus.h.
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
stimCoxDVal
double MSSOTLPolicy5DStimulus::stimCoxDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimCoxExpDispersionInDVal
double MSSOTLPolicy5DStimulus::stimCoxExpDispersionInDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimCoxExpDispersionOutDVal
double MSSOTLPolicy5DStimulus::stimCoxExpDispersionOutDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimCoxExpInDVal
double MSSOTLPolicy5DStimulus::stimCoxExpInDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimCoxExpOutDVal
double MSSOTLPolicy5DStimulus::stimCoxExpOutDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimDivDispersionInDVal
double MSSOTLPolicy5DStimulus::stimDivDispersionInDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimDivDispersionOutDVal
double MSSOTLPolicy5DStimulus::stimDivDispersionOutDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimDivInDVal
double MSSOTLPolicy5DStimulus::stimDivInDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimDivOutDVal
double MSSOTLPolicy5DStimulus::stimDivOutDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimOffsetDispersionInDVal
double MSSOTLPolicy5DStimulus::stimOffsetDispersionInDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimOffsetDispersionOutDVal
double MSSOTLPolicy5DStimulus::stimOffsetDispersionOutDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimOffsetInDVal
double MSSOTLPolicy5DStimulus::stimOffsetInDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
stimOffsetOutDVal
double MSSOTLPolicy5DStimulus::stimOffsetOutDVal private
Definition at line 51 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy5DStimulus().
The documentation for this class was generated from the following files:
MSSOTLPolicy5DStimulus.h
MSSOTLPolicy5DStimulus.cpp