SUMO - Simulation of Urban MObility: bezier.h File Reference
bezier.h File Reference
#include <config.h>
#include "PositionVector.h"
Functions
void bezier (int npts, double b[], int cpts, double p[])
PositionVector bezier (const PositionVector &init, int numPoints)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
2003-11-19
Version
$Id$
Definition in file bezier.h.
Function Documentation
bezier() [1/2]
void bezier (int npts, double b[], int cpts, double p[])
Definition at line 96 of file bezier.cpp.
References Basis().
Referenced by bezier(), NBNode::computeSmoothShape(), GNEEdge::smoothShape(), NWWriter_OpenDrive::writeGeomSmooth(), and NWWriter_OpenDrive::writeInternalEdge().
bezier() [2/2]
PositionVector bezier (const PositionVector & init, int numPoints)
Definition at line 133 of file bezier.cpp.
References bezier(), ISNAN(), Position::x(), Position::y(), and Position::z().