SUMO - Simulation of Urban MObility: libsumo::LaneArea Class Reference
libsumo::LaneArea Class Reference
#include <LaneArea.h>
Static Public Member Functions
static int getIDCount ()
static std::vector< std::string > getIDList ()
static double getJamLengthMeters (const std::string &detID)
static int getJamLengthVehicle (const std::string &detID)
static std::string getLaneID (const std::string &detID)
static int getLastStepHaltingNumber (const std::string &detID)
static double getLastStepMeanSpeed (const std::string &detID)
static double getLastStepOccupancy (const std::string &detID)
static std::vector< std::string > getLastStepVehicleIDs (const std::string &detID)
static int getLastStepVehicleNumber (const std::string &detID)
static double getLength (const std::string &detID)
static double getPosition (const std::string &detID)
Private Member Functions
LaneArea ()
invalidated standard constructor
LaneArea (const LaneArea &src)
invalidated copy constructor
LaneArea & operator= (const LaneArea &src)
invalidated assignment operator
Static Private Member Functions
static MSE2Collector * getDetector (const std::string &detID)
Detailed Description
Definition at line 49 of file LaneArea.h.
Constructor & Destructor Documentation
LaneArea() [1/2]
libsumo::LaneArea::LaneArea () private
invalidated standard constructor
LaneArea() [2/2]
libsumo::LaneArea::LaneArea (const LaneArea & src) private
invalidated copy constructor
Member Function Documentation
getDetector()
MSE2Collector * LaneArea::getDetector (const std::string & detID) static private
Definition at line 121 of file LaneArea.cpp.
References NamedObjectCont< T >::get(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by getJamLengthMeters(), getJamLengthVehicle(), getLaneID(), getLastStepHaltingNumber(), getLastStepMeanSpeed(), getLastStepOccupancy(), getLastStepVehicleIDs(), getLastStepVehicleNumber(), getLength(), and getPosition().
getIDCount()
int LaneArea::getIDCount () static
Definition at line 53 of file LaneArea.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::size(), and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by TraCIServerAPI_LaneArea::processGet().
getIDList()
std::vector< std::string > LaneArea::getIDList () static
Definition at line 45 of file LaneArea.cpp.
References MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), NamedObjectCont< T >::insertIDs(), and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by TraCIServerAPI_LaneArea::processGet().
getJamLengthMeters()
double LaneArea::getJamLengthMeters (const std::string & detID) static
Definition at line 66 of file LaneArea.cpp.
References MSE2Collector::getCurrentJamLengthInMeters(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getJamLengthVehicle()
int LaneArea::getJamLengthVehicle (const std::string & detID) static
Definition at line 60 of file LaneArea.cpp.
References MSE2Collector::getCurrentJamLengthInVehicles(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLaneID()
std::string LaneArea::getLaneID (const std::string & detID) static
Definition at line 96 of file LaneArea.cpp.
References getDetector(), Named::getID(), and MSMoveReminder::getLane().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLastStepHaltingNumber()
int LaneArea::getLastStepHaltingNumber (const std::string & detID) static
Definition at line 115 of file LaneArea.cpp.
References MSE2Collector::getCurrentHaltingNumber(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLastStepMeanSpeed()
double LaneArea::getLastStepMeanSpeed (const std::string & detID) static
Definition at line 72 of file LaneArea.cpp.
References MSE2Collector::getCurrentMeanSpeed(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLastStepOccupancy()
double LaneArea::getLastStepOccupancy (const std::string & detID) static
Definition at line 84 of file LaneArea.cpp.
References MSE2Collector::getCurrentOccupancy(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLastStepVehicleIDs()
std::vector< std::string > LaneArea::getLastStepVehicleIDs (const std::string & detID) static
Definition at line 78 of file LaneArea.cpp.
References MSE2Collector::getCurrentVehicleIDs(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLastStepVehicleNumber()
int LaneArea::getLastStepVehicleNumber (const std::string & detID) static
Definition at line 109 of file LaneArea.cpp.
References MSE2Collector::getCurrentVehicleNumber(), and getDetector().
Referenced by TraCIServerAPI_LaneArea::processGet().
getLength()
double LaneArea::getLength (const std::string & detID) static
Definition at line 102 of file LaneArea.cpp.
References getDetector(), MSE2Collector::getEndPos(), and MSE2Collector::getStartPos().
Referenced by TraCIServerAPI_LaneArea::processGet().
getPosition()
double LaneArea::getPosition (const std::string & detID) static
Definition at line 90 of file LaneArea.cpp.
References getDetector(), and MSE2Collector::getStartPos().
Referenced by TraCIServerAPI_LaneArea::processGet().
operator=()
LaneArea& libsumo::LaneArea::operator= (const LaneArea & src) private
invalidated assignment operator
The documentation for this class was generated from the following files:
LaneArea.h
LaneArea.cpp