SUMO - Simulation of Urban MObility: NLEdgeControlBuilder Class Reference
NLEdgeControlBuilder Class Reference
Interface for building edges.
#include <NLEdgeControlBuilder.h>
Public Member Functions
virtual void addCrossingEdges (const std::vector< std::string > &)
add the crossingEdges in a crossing edge if present
virtual MSLane * addLane (const std::string &id, double maxSpeed, double length, const PositionVector &shape, double width, SVCPermissions permissions, int index, bool isRampAccel)
Adds a lane to the current edge.
virtual void addNeigh (const std::string id)
Adds a neighbor to the current lane.
void beginEdgeParsing (const std::string &id, const SumoXMLEdgeFunc function, const std::string &streetName, const std::string &edgeType, int priority)
Begins building of an MSEdge.
MSEdgeControl * build ()
builds the MSEdgeControl-class which holds all edges
virtual MSEdge * buildEdge (const std::string &id, const SumoXMLEdgeFunc function, const std::string &streetName, const std::string &edgeType, const int priority)
Builds an edge instance (MSEdge in this case)
virtual MSEdge * closeEdge ()
Closes the building of an edge; The edge is completely described by now and may not be opened again.
NLEdgeControlBuilder ()
Constructor.
virtual ~NLEdgeControlBuilder ()
Destructor.
Protected Attributes
MSEdge * myActiveEdge
pointer to the currently chosen edge
int myCurrentNumericalEdgeID
A running number for edge numbering.
int myCurrentNumericalLaneID
A running number for lane numbering.
MSEdgeVector myEdges
Temporary, internal storage for built edges.
std::vector< MSLane * > * myLaneStorage
pointer to a temporary lane storage
Private Member Functions
NLEdgeControlBuilder (const NLEdgeControlBuilder &s)
invalidated copy constructor
NLEdgeControlBuilder & operator= (const NLEdgeControlBuilder &s)
invalidated assignment operator
Detailed Description
Interface for building edges.
This class is the container for MSEdge-instances while they are build.
While building instances of MSEdge, these are stored in a list. The list of edges is later split into two lists, one containing single-lane-edges and one containing multi-lane-edges.
Todo:
Assignment of lanes is not really well. Should be reworked after shapes are given as params.
Definition at line 63 of file NLEdgeControlBuilder.h.
Constructor & Destructor Documentation
NLEdgeControlBuilder() [1/2]
NLEdgeControlBuilder::NLEdgeControlBuilder ()
Constructor.
Definition at line 52 of file NLEdgeControlBuilder.cpp.
References myActiveEdge, and myLaneStorage.
~NLEdgeControlBuilder()
NLEdgeControlBuilder::~NLEdgeControlBuilder () virtual
Destructor.
Definition at line 59 of file NLEdgeControlBuilder.cpp.
References myLaneStorage.
NLEdgeControlBuilder() [2/2]
NLEdgeControlBuilder::NLEdgeControlBuilder (const NLEdgeControlBuilder & s) private
invalidated copy constructor
Member Function Documentation
addCrossingEdges()
void NLEdgeControlBuilder::addCrossingEdges (const std::vector< std::string > & crossingEdges) virtual
add the crossingEdges in a crossing edge if present
Parameters
[in] the vector of crossed edges id
Definition at line 148 of file NLEdgeControlBuilder.cpp.
References myActiveEdge, and MSEdge::setCrossingEdges().
Referenced by NLHandler::beginEdgeParsing().
addLane()
MSLane * NLEdgeControlBuilder::addLane (const std::string & id, double maxSpeed, double length, const PositionVector & shape, double width, SVCPermissions permissions, int index, bool isRampAccel) virtual
Adds a lane to the current edge.
Parameters
[in] id The lane's id
[in] maxSpeed The speed allowed on this lane
[in] length The lane's length
[in] shape The shape of the lane
[in] width The width of the lane
[in] permissions Encoding of vehicle classes that may drive on this lane
[in] index The index of this lane within its parent edge
See also
SUMOVehicleClass
MSLane
Todo:
Definitely not a good way
Reimplemented in GUIEdgeControlBuilder.
Definition at line 81 of file NLEdgeControlBuilder.cpp.
References myActiveEdge, myCurrentNumericalLaneID, and myLaneStorage.
Referenced by NLHandler::addLane().
addNeigh()
void NLEdgeControlBuilder::addNeigh (const std::string id) virtual
Adds a neighbor to the current lane.
Parameters
[in] id The lane's id
See also
MSLane
Definition at line 92 of file NLEdgeControlBuilder.cpp.
References myLaneStorage.
Referenced by NLHandler::myStartElement().
beginEdgeParsing()
void NLEdgeControlBuilder::beginEdgeParsing (const std::string & id, const SumoXMLEdgeFunc function, const std::string & streetName, const std::string & edgeType, int priority)
Begins building of an MSEdge.
Builds an instance of MSEdge using "buildEdge". Stores it as the current edge in "myActiveEdge" and appends it to the list of built edges ("myEdges").
The given information is used to build the edge.
Parameters
[in] id The id of the edge
[in] function The function of the edge
[in] streetName The street name of the edge
Exceptions
InvalidArgument If an edge with the same name was already built
Definition at line 65 of file NLEdgeControlBuilder.cpp.
References buildEdge(), MSEdge::dictionary(), myActiveEdge, myEdges, and myLaneStorage.
Referenced by NLHandler::beginEdgeParsing().
build()
MSEdgeControl * NLEdgeControlBuilder::build ()
builds the MSEdgeControl-class which holds all edges
Definition at line 109 of file NLEdgeControlBuilder.cpp.
References deprecatedVehicleClassesSeen, Named::getID(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), MSEdge::getPredecessors(), MSEdge::getSuccessors(), MSGlobals::gUsingInternalLanes, MSEdge::isInternal(), MSEdge::markAsRoundabout(), myEdges, toString(), and WRITE_WARNING.
Referenced by NLBuilder::buildNet().
buildEdge()
MSEdge * NLEdgeControlBuilder::buildEdge (const std::string & id, const SumoXMLEdgeFunc function, const std::string & streetName, const std::string & edgeType, const int priority) virtual
Builds an edge instance (MSEdge in this case)
Builds an MSEdge-instance using the given name and the current index "myCurrentNumericalEdgeID". Post-increments the index, returns the built edge.
Parameters
[in] id The id of the edge to build
[in] streetName The street name of the edge to build
Reimplemented in GUIEdgeControlBuilder.
Definition at line 143 of file NLEdgeControlBuilder.cpp.
References myCurrentNumericalEdgeID.
Referenced by NLHandler::addDistrict(), and beginEdgeParsing().
closeEdge()
MSEdge * NLEdgeControlBuilder::closeEdge () virtual
Closes the building of an edge; The edge is completely described by now and may not be opened again.
Definition at line 98 of file NLEdgeControlBuilder.cpp.
References MSEdge::initialize(), myActiveEdge, and myLaneStorage.
Referenced by NLHandler::closeEdge().
operator=()
NLEdgeControlBuilder& NLEdgeControlBuilder::operator= (const NLEdgeControlBuilder & s) private
invalidated assignment operator
Field Documentation
myActiveEdge
MSEdge* NLEdgeControlBuilder::myActiveEdge protected
pointer to the currently chosen edge
Definition at line 153 of file NLEdgeControlBuilder.h.
Referenced by addCrossingEdges(), GUIEdgeControlBuilder::addLane(), addLane(), beginEdgeParsing(), closeEdge(), and NLEdgeControlBuilder().
myCurrentNumericalEdgeID
int NLEdgeControlBuilder::myCurrentNumericalEdgeID protected
A running number for edge numbering.
Definition at line 147 of file NLEdgeControlBuilder.h.
Referenced by GUIEdgeControlBuilder::buildEdge(), and buildEdge().
myCurrentNumericalLaneID
int NLEdgeControlBuilder::myCurrentNumericalLaneID protected
A running number for lane numbering.
Definition at line 144 of file NLEdgeControlBuilder.h.
Referenced by GUIEdgeControlBuilder::addLane(), and addLane().
myEdges
MSEdgeVector NLEdgeControlBuilder::myEdges protected
Temporary, internal storage for built edges.
Definition at line 150 of file NLEdgeControlBuilder.h.
Referenced by beginEdgeParsing(), and build().
myLaneStorage
std::vector<MSLane*>* NLEdgeControlBuilder::myLaneStorage protected
pointer to a temporary lane storage
Definition at line 156 of file NLEdgeControlBuilder.h.
Referenced by GUIEdgeControlBuilder::addLane(), addLane(), addNeigh(), beginEdgeParsing(), closeEdge(), NLEdgeControlBuilder(), and ~NLEdgeControlBuilder().
The documentation for this class was generated from the following files:
NLEdgeControlBuilder.h
NLEdgeControlBuilder.cpp