SUMO - Simulation of Urban MObility: NBEdge::Connection Struct Reference
NBEdge::Connection Struct Reference
A structure which describes a connection between edges or lanes.
#include <NBEdge.h>
Public Member Functions
void clearParameter ()
Clears the parameter map.
Connection (int fromLane_, NBEdge *toEdge_, int toLane_)
Constructor.
Connection (int fromLane_, NBEdge *toEdge_, int toLane_, bool mayDefinitelyPass_, bool keepClear_=true, double contPos_=UNSPECIFIED_CONTPOS, double visibility_=UNSPECIFIED_VISIBILITY_DISTANCE, double speed_=UNSPECIFIED_SPEED, bool haveVia_=false, bool uncontrolled_=false, const PositionVector &customShape_=PositionVector::EMPTY)
constructor with more parameters
std::string getDescription (const NBEdge *parent) const
get string describing this connection
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
std::string getInternalLaneID () const
get ID of internal lane
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
void writeParams (OutputDevice &out) const
~Connection ()
destructor
Data Fields
double contPos
custom position for internal junction on this connection
PositionVector customShape
custom shape for connection
std::string foeIncomingLanes
FOE Incomings lanes.
std::vector< int > foeInternalLinks
FOE Internal links.
int fromLane
The lane the connections starts at.
bool haveVia
check if Connection have a Via
std::string id
id of Connection
int internalLaneIndex
The lane index of this internal lane within the internal edge.
bool keepClear
whether the junction must be kept clear when using this connection
bool mayDefinitelyPass
Information about being definitely free to drive (on-ramps)
PositionVector shape
shape of Connection
double speed
custom speed for connection
std::string tlID
The id of the traffic light that controls this connection.
int tlLinkNo
The index of this connection within the controlling traffic light.
NBEdge * toEdge
The edge the connections yields in.
int toLane
The lane the connections yields in.
bool uncontrolled
check if Connection is uncontrolled
std::string viaID
if Connection have a via, ID of it
PositionVector viaShape
shape of via
double visibility
custom foe visiblity for connection
double vmax
maximun velocity
Detailed Description
A structure which describes a connection between edges or lanes.
Definition at line 161 of file NBEdge.h.
Constructor & Destructor Documentation
Connection() [1/2]
NBEdge::Connection::Connection (int fromLane_, NBEdge * toEdge_, int toLane_)
Constructor.
Parameters
[in] fromLane_ The lane the connections starts at
[in] toEdge_ The edge the connections yields in
[in] toLane_ The lane the connections yields in
Definition at line 91 of file NBEdge.cpp.
Connection() [2/2]
NBEdge::Connection::Connection (int fromLane_, NBEdge * toEdge_, int toLane_, bool mayDefinitelyPass_, bool keepClear_ = true, double contPos_ = UNSPECIFIED_CONTPOS, double visibility_ = UNSPECIFIED_VISIBILITY_DISTANCE, double speed_ = UNSPECIFIED_SPEED, bool haveVia_ = false, bool uncontrolled_ = false, const PositionVector & customShape_ = PositionVector::EMPTY)
constructor with more parameters
Definition at line 107 of file NBEdge.cpp.
~Connection()
NBEdge::Connection::~Connection () inline
destructor
Definition at line 180 of file NBEdge.h.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
getDescription()
std::string NBEdge::Connection::getDescription (const NBEdge * parent) const
get string describing this connection
Definition at line 86 of file NBEdge.cpp.
References fromLane, Named::getIDSecure(), toEdge, toLane, and toString().
Referenced by NBEdgeCont::checkGrade(), and NBNode::computeInternalLaneShape().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getInternalLaneID()
std::string NBEdge::Connection::getInternalLaneID () const
get ID of internal lane
Definition at line 80 of file NBEdge.cpp.
References internalLaneIndex, and toString().
Referenced by NWWriter_SUMO::getOppositeInternalID(), and NWWriter_SUMO::writeConnection().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
contPos
double NBEdge::Connection::contPos
custom position for internal junction on this connection
Definition at line 204 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), NBEdge::buildInnerEdges(), GNEConnection::getAttribute(), GNEConnection::setAttribute(), and NWWriter_SUMO::writeConnection().
customShape
PositionVector NBEdge::Connection::customShape
custom shape for connection
Definition at line 213 of file NBEdge.h.
Referenced by NBNode::computeInternalLaneShape(), GNEConnection::getAttribute(), GNEConnection::getShape(), GNEConnection::setAttribute(), GNEConnection::updateGeometry(), and NWWriter_SUMO::writeConnection().
foeIncomingLanes
std::string NBEdge::Connection::foeIncomingLanes
FOE Incomings lanes.
Definition at line 237 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges().
foeInternalLinks
std::vector<int> NBEdge::Connection::foeInternalLinks
FOE Internal links.
Definition at line 234 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges().
fromLane
int NBEdge::Connection::fromLane
The lane the connections starts at.
Definition at line 183 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), NBEdge::addRestrictedLane(), NIXMLTrafficLightsHandler::addTlConnection(), NBEdge::buildInnerEdges(), NBTrafficLightDefinition::collectAllLinks(), NBNode::computeInternalLaneShape(), NBNode::computeLanes2Lanes(), NBEdge::connections_sorter(), NBNode::getConnectionIndex(), getDescription(), NWWriter_SUMO::getOppositeInternalID(), NBRequest::mergeConflict(), NBNode::needsCont(), NBEdge::connections_toedge_finder::operator()(), NBEdge::connections_toedgelane_finder::operator()(), NBEdge::connections_finder::operator()(), NBEdge::connections_conflict_finder::operator()(), NBEdge::connections_fromlane_finder::operator()(), NBEdge::recheckLanes(), GNEChange_Connection::redo(), GNEEdge::removeConnection(), NBEdge::removeFromConnections(), GNEChange_Connection::undo(), GNEConnection::updateGeometry(), GNEConnection::updateLinkState(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), and NWWriter_OpenDrive::writeInternalEdge().
haveVia
bool NBEdge::Connection::haveVia
check if Connection have a Via
Definition at line 225 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), GNEConnection::updateGeometry(), and NWWriter_SUMO::writeInternalConnections().
id
std::string NBEdge::Connection::id
id of Connection
Definition at line 216 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), and NWWriter_SUMO::writeInternalConnections().
internalLaneIndex
int NBEdge::Connection::internalLaneIndex
The lane index of this internal lane within the internal edge.
Definition at line 240 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), getInternalLaneID(), and NWWriter_SUMO::writeInternalConnections().
keepClear
bool NBEdge::Connection::keepClear
whether the junction must be kept clear when using this connection
Definition at line 201 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), GNEConnection::getAttribute(), GNEConnection::setAttribute(), and NWWriter_SUMO::writeConnection().
mayDefinitelyPass
bool NBEdge::Connection::mayDefinitelyPass
Information about being definitely free to drive (on-ramps)
Definition at line 198 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), GNEConnection::getAttribute(), NBRequest::mergeConflict(), GNEConnection::setAttribute(), GNEConnection::updateLinkState(), and NWWriter_SUMO::writeConnection().
shape
PositionVector NBEdge::Connection::shape
shape of Connection
Definition at line 219 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), NBEdgeCont::checkGrade(), NWWriter_SUMO::getOppositeInternalID(), and GNEConnection::updateGeometry().
speed
double NBEdge::Connection::speed
custom speed for connection
Definition at line 210 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), GNEConnection::getAttribute(), GNEConnection::setAttribute(), and NWWriter_SUMO::writeConnection().
tlID
std::string NBEdge::Connection::tlID
The id of the traffic light that controls this connection.
Definition at line 192 of file NBEdge.h.
Referenced by NIXMLTrafficLightsHandler::addTlConnection(), NBEdge::moveOutgoingConnectionsFrom(), NBNode::needsCont(), NBEdge::setControllingTLInformation(), GNEConnection::updateLinkState(), and NWWriter_SUMO::writeConnection().
tlLinkNo
int NBEdge::Connection::tlLinkNo
The index of this connection within the controlling traffic light.
Definition at line 195 of file NBEdge.h.
Referenced by NIXMLTrafficLightsHandler::addTlConnection(), GNEConnection::getAttribute(), NBEdge::setControllingTLInformation(), and NWWriter_SUMO::writeConnection().
toEdge
NBEdge* NBEdge::Connection::toEdge
The edge the connections yields in.
Definition at line 186 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimTL::NIVissimTLSignal::addTo(), NBEdge::buildInnerEdges(), NBEdge::canMoveConnection(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedTLDef::collectLinks(), NBNode::computeInternalLaneShape(), NBNode::computeLanes2Lanes(), NBEdge::connections_sorter(), GNEConnection::getAttribute(), NBNode::getConnectionIndex(), getDescription(), NWWriter_SUMO::getOppositeInternalID(), NBRequest::mergeConflict(), NBEdge::moveConnectionToLeft(), NBEdge::moveConnectionToRight(), NBEdge::moveOutgoingConnectionsFrom(), NBNode::needsCont(), NBEdge::connections_toedge_finder::operator()(), NBEdge::connections_toedgelane_finder::operator()(), NBEdge::connections_finder::operator()(), NBEdge::connections_conflict_finder::operator()(), NBEdge::connections_relative_edgelane_sorter::operator()(), NBEdge::recheckLanes(), NBEdgeCont::recheckPostProcessConnections(), GNEChange_Connection::redo(), GNEEdge::removeConnection(), NBEdge::removeFromConnections(), GNEChange_Connection::undo(), GNEConnection::updateGeometry(), GNEConnection::updateLinkState(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeInternalConnections(), and NWWriter_OpenDrive::writeNetwork().
toLane
int NBEdge::Connection::toLane
The lane the connections yields in.
Definition at line 189 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimTL::NIVissimTLSignal::addTo(), NBEdge::buildInnerEdges(), NBEdge::canMoveConnection(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedTLDef::collectLinks(), NBNode::computeInternalLaneShape(), NBNode::computeLanes2Lanes(), NBEdge::connections_sorter(), GNEConnection::getAttribute(), NBNode::getConnectionIndex(), getDescription(), NWWriter_SUMO::getOppositeInternalID(), NBRequest::mergeConflict(), NBEdge::moveConnectionToLeft(), NBEdge::moveConnectionToRight(), NBEdge::moveOutgoingConnectionsFrom(), NBNode::needsCont(), NBEdge::connections_toedgelane_finder::operator()(), NBEdge::connections_finder::operator()(), NBEdge::connections_relative_edgelane_sorter::operator()(), NBEdge::recheckLanes(), GNEChange_Connection::redo(), GNEEdge::removeConnection(), NBEdge::removeFromConnections(), GNEChange_Connection::undo(), GNEConnection::updateGeometry(), GNEConnection::updateLinkState(), NWWriter_DlrNavteq::writeConnectedLanes(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeInternalConnections(), and NWWriter_OpenDrive::writeInternalEdge().
uncontrolled
bool NBEdge::Connection::uncontrolled
check if Connection is uncontrolled
Definition at line 243 of file NBEdge.h.
Referenced by GNEConnection::getAttribute(), and GNEConnection::setAttribute().
viaID
std::string NBEdge::Connection::viaID
if Connection have a via, ID of it
Definition at line 228 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), and NWWriter_SUMO::writeInternalConnections().
viaShape
PositionVector NBEdge::Connection::viaShape
shape of via
Definition at line 231 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), NBEdgeCont::checkGrade(), and GNEConnection::updateGeometry().
visibility
double NBEdge::Connection::visibility
custom foe visiblity for connection
Definition at line 207 of file NBEdge.h.
Referenced by GNEEdge::addConnection(), GNEConnection::getAttribute(), GNEConnection::setAttribute(), and NWWriter_SUMO::writeConnection().
vmax
double NBEdge::Connection::vmax
maximun velocity
Definition at line 222 of file NBEdge.h.
Referenced by NBEdge::buildInnerEdges(), and NWWriter_OpenDrive::writeInternalEdge().
The documentation for this struct was generated from the following files:
NBEdge.h
NBEdge.cpp