SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::ProhibitionHandler Class Reference
NIImporter_DlrNavteq::ProhibitionHandler Class Reference
Imports prohibitions regarding connectivity.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
ProhibitionHandler (NBEdgeCont &ne, const std::string &file, time_t constructionTime)
Constructor.
bool report (const std::string &result)
Parsing method.
~ProhibitionHandler ()
Destructor.
Protected Attributes
time_t myConstructionTime
NBEdgeCont & myEdgeCont
The edge container to store loaded edges into.
const std::string myFile
double myVersion
Private Member Functions
ProhibitionHandler & operator= (const ProhibitionHandler &)
Invalidated assignment operator.
ProhibitionHandler (const ProhibitionHandler &)
Invalidated copy constructor.
Detailed Description
Imports prohibitions regarding connectivity.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain prohibited manoeuver definitions in DLRNavteq's format.
Definition at line 427 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
ProhibitionHandler() [1/2]
NIImporter_DlrNavteq::ProhibitionHandler::ProhibitionHandler (NBEdgeCont & ne, const std::string & file, time_t constructionTime)
Constructor.
Parameters
[in] file The name of the parsed file
Definition at line 706 of file NIImporter_DlrNavteq.cpp.
~ProhibitionHandler()
NIImporter_DlrNavteq::ProhibitionHandler::~ProhibitionHandler ()
Destructor.
Definition at line 715 of file NIImporter_DlrNavteq.cpp.
ProhibitionHandler() [2/2]
NIImporter_DlrNavteq::ProhibitionHandler::ProhibitionHandler (const ProhibitionHandler &) private
Invalidated copy constructor.
Member Function Documentation
operator=()
ProhibitionHandler& NIImporter_DlrNavteq::ProhibitionHandler::operator= (const ProhibitionHandler &) private
Invalidated assignment operator.
report()
bool NIImporter_DlrNavteq::ProhibitionHandler::report (const std::string & result) virtual
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and stores the streetNames
Parameters
[in] result The read line
Returns
Whether the parsing shall continue
Exceptions
ProcessError if something fails
See also
LineHandler::report
Implements LineHandler.
Definition at line 719 of file NIImporter_DlrNavteq.cpp.
References StringTokenizer::get(), myEdgeCont, myFile, myVersion, StringTokenizer::next(), NIImporter_DlrNavteq::readVersion(), NBEdge::removeFromConnections(), NBEdgeCont::retrieve(), StringTokenizer::size(), StringTokenizer::TAB, NIImporter_DlrNavteq::UNDEFINED, and WRITE_WARNING.
Field Documentation
myConstructionTime
time_t NIImporter_DlrNavteq::ProhibitionHandler::myConstructionTime protected
Definition at line 457 of file NIImporter_DlrNavteq.h.
myEdgeCont
NBEdgeCont& NIImporter_DlrNavteq::ProhibitionHandler::myEdgeCont protected
The edge container to store loaded edges into.
Definition at line 454 of file NIImporter_DlrNavteq.h.
Referenced by report().
myFile
const std::string NIImporter_DlrNavteq::ProhibitionHandler::myFile protected
Definition at line 455 of file NIImporter_DlrNavteq.h.
Referenced by report().
myVersion
double NIImporter_DlrNavteq::ProhibitionHandler::myVersion protected
Definition at line 456 of file NIImporter_DlrNavteq.h.
Referenced by report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp