SUMO - Simulation of Urban MObility: MSCModel_NonInteracting Class Reference
MSCModel_NonInteracting Class Reference
The container following model for tranship.
#include <MSCModel_NonInteracting.h>
Data Structures
class MoveToNextEdge
Public Member Functions
CState * add (MSTransportable *container, MSContainer::MSContainerStage_Tranship *stage, SUMOTime now)
register the given container as a transhiped container
MSCModel_NonInteracting (MSNet *net)
Constructor (it should not be necessary to construct more than one instance)
~MSCModel_NonInteracting ()
Static Public Member Functions
static void cleanup ()
remove state at simulation end
static MSCModel_NonInteracting * getModel ()
Private Attributes
MSNet * myNet
the net to which to issue moveToNextEdge commands
Static Private Attributes
static MSCModel_NonInteracting * myModel
Detailed Description
The container following model for tranship.
Definition at line 57 of file MSCModel_NonInteracting.h.
Constructor & Destructor Documentation
MSCModel_NonInteracting()
MSCModel_NonInteracting::MSCModel_NonInteracting (MSNet * net)
Constructor (it should not be necessary to construct more than one instance)
Definition at line 58 of file MSCModel_NonInteracting.cpp.
References myNet.
Referenced by getModel().
~MSCModel_NonInteracting()
MSCModel_NonInteracting::~MSCModel_NonInteracting ()
Definition at line 64 of file MSCModel_NonInteracting.cpp.
Member Function Documentation
add()
CState * MSCModel_NonInteracting::add (MSTransportable * container, MSContainer::MSContainerStage_Tranship * stage, SUMOTime now)
register the given container as a transhiped container
Definition at line 77 of file MSCModel_NonInteracting.cpp.
References MSEventControl::addEvent(), CState::computeTranshipTime(), MSNet::getBeginOfTimestepEvents(), and myNet.
Referenced by MSContainer::MSContainerStage_Tranship::proceed().
cleanup()
void MSCModel_NonInteracting::cleanup () static
remove state at simulation end
Definition at line 86 of file MSCModel_NonInteracting.cpp.
References myModel.
Referenced by MSNet::clearAll().
getModel()
MSCModel_NonInteracting * MSCModel_NonInteracting::getModel () static
Definition at line 68 of file MSCModel_NonInteracting.cpp.
References MSNet::getInstance(), MSCModel_NonInteracting(), and myModel.
Referenced by MSContainer::MSContainerStage_Tranship::proceed().
Field Documentation
myModel
MSCModel_NonInteracting * MSCModel_NonInteracting::myModel static private
Definition at line 74 of file MSCModel_NonInteracting.h.
Referenced by cleanup(), and getModel().
myNet
MSNet* MSCModel_NonInteracting::myNet private
the net to which to issue moveToNextEdge commands
Definition at line 94 of file MSCModel_NonInteracting.h.
Referenced by add(), and MSCModel_NonInteracting().
The documentation for this class was generated from the following files:
MSCModel_NonInteracting.h
MSCModel_NonInteracting.cpp