SUMO - Simulation of Urban MObility: ValueSource< T > Class Template Reference
ValueSource< T > Class Template Reference abstract
#include <ValueSource.h>
Public Member Functions
virtual ValueSource * copy () const =0
virtual T getValue () const =0
virtual ValueSource< double > * makedoubleReturningCopy () const =0
ValueSource ()
virtual ~ValueSource ()
Detailed Description
template<typename T>
class ValueSource< T >
Definition at line 40 of file ValueSource.h.
Constructor & Destructor Documentation
ValueSource()
template<typename T> ValueSource< T >::ValueSource () inline
Definition at line 42 of file ValueSource.h.
~ValueSource()
template<typename T> virtual ValueSource< T >::~ValueSource () inline virtual
Definition at line 43 of file ValueSource.h.
Member Function Documentation
copy()
template<typename T> virtual ValueSource* ValueSource< T >::copy () const pure virtual
Implemented in FuncBinding_IntParam< T, R >, FunctionBinding< T, R >, FuncBinding_StringParam< T, R >, and CastingFunctionBinding< T, R, O >.
Referenced by GUIParam_PopupMenuInterface::onCmdOpenTracker(), and ValueSource< std::pair< SUMOTime, MSPhaseDefinition > >::~ValueSource().
getValue()
template<typename T> virtual T ValueSource< T >::getValue () const pure virtual
Implemented in FuncBinding_IntParam< T, R >, FunctionBinding< T, R >, FuncBinding_StringParam< T, R >, and CastingFunctionBinding< T, R, O >.
Referenced by GUIParameterTableItem< T >::GUIParameterTableItem(), and ValueSource< std::pair< SUMOTime, MSPhaseDefinition > >::~ValueSource().
makedoubleReturningCopy()
template<typename T> virtual ValueSource<double>* ValueSource< T >::makedoubleReturningCopy () const pure virtual
Implemented in FuncBinding_IntParam< T, R >, FunctionBinding< T, R >, FuncBinding_StringParam< T, R >, and CastingFunctionBinding< T, R, O >.
Referenced by GUIParameterTableItem< T >::getdoubleSourceCopy(), and ValueSource< std::pair< SUMOTime, MSPhaseDefinition > >::~ValueSource().
The documentation for this class was generated from the following file:
ValueSource.h