SUMO - Simulation of Urban MObility: NamedRTree Class Reference
NamedRTree Class Reference
A RT-tree for efficient storing of SUMO's Named objects.
#include <NamedRTree.h>
Public Member Functions
void Insert (const float a_min[2], const float a_max[2], Named *const &a_data)
Insert entry.
NamedRTree ()
Constructor.
void Remove (const float a_min[2], const float a_max[2], Named *const &a_data)
Remove entry.
void RemoveAll ()
Remove all enrties.
int Search (const float a_min[2], const float a_max[2], const Named::StoringVisitor &c) const
Find all within search rectangle.
~NamedRTree ()
Destructor.
Detailed Description
A RT-tree for efficient storing of SUMO's Named objects.
This class specialises the used RT-tree implementation from "rttree.h". It stores names of "Named"-objects.
See also
Named
Definition at line 71 of file NamedRTree.h.
Constructor & Destructor Documentation
NamedRTree()
NamedRTree::NamedRTree () inline
Constructor.
Definition at line 74 of file NamedRTree.h.
~NamedRTree()
NamedRTree::~NamedRTree () inline
Destructor.
Definition at line 79 of file NamedRTree.h.
Member Function Documentation
Insert()
void NamedRTree::Insert (const float a_min[2], const float a_max[2], Named *const & a_data) inline
Insert entry.
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_data The instance of a Named-object to add (the ID is added)
See also
RTree::Insert
Definition at line 89 of file NamedRTree.h.
Referenced by MSDevice_BTreceiver::BTreceiverUpdate::execute(), NBPTStopCont::findAccessEdgesForRailStops(), libsumo::InductionLoop::getTree(), libsumo::Polygon::getTree(), libsumo::Junction::getTree(), libsumo::POI::getTree(), and NBNodeCont::insert().
Remove()
void NamedRTree::Remove (const float a_min[2], const float a_max[2], Named *const & a_data) inline
Remove entry.
Parameters
a_min Min of bounding rect
a_max Max of bounding rect
a_data The instance of a Named-object to remove
See also
RTree::Remove
Definition at line 100 of file NamedRTree.h.
Referenced by NBNodeCont::extract().
RemoveAll()
void NamedRTree::RemoveAll () inline
Remove all enrties.
See also
RTree::RemoveAll
Definition at line 108 of file NamedRTree.h.
Search()
int NamedRTree::Search (const float a_min[2], const float a_max[2], const Named::StoringVisitor & c) const inline
Find all within search rectangle.
Parameters
a_min Min of search bounding rect
a_max Max of search bounding rect
a_searchResult Search result array. Caller should set grow size. Function will reset, not append to array.
a_resultCallback Callback function to return result. Callback should return 'true' to continue searching
a_context User context to pass as parameter to a_resultCallback
Returns
Returns the number of entries found
See also
RTree::Search
Definition at line 122 of file NamedRTree.h.
Referenced by MSDevice_BTreceiver::BTreceiverUpdate::execute(), NBPTStopCont::findAccessEdgesForRailStops(), and NBNodeCont::retrieve().
The documentation for this class was generated from the following file:
NamedRTree.h