SUMO - Simulation of Urban MObility: PositionVector Class Reference
PositionVector Class Reference
A list of positions.
#include <PositionVector.h>
Data Structures
class as_poly_cw_sorter
clase for CW Sorter
class increasing_x_y_sorter
clase for increasing Sorter
Public Member Functions
void add (double xoff, double yoff, double zoff)
void add (const Position &offset)
double angleAt2D (int pos) const
get angle in certain position of position vector
void append (const PositionVector &v, double sameThreshold=2.0)
double area () const
Returns the area (0 for non-closed)
bool around (const Position &p, double offset=0) const
Returns the information whether the position vector describes a polygon lying around the given point.
double beginEndAngle () const
returns the angle in radians of the line connecting the first and the last position
void closePolygon ()
ensures that the last position equals the first
bool crosses (const Position &p1, const Position &p2) const
double distance2D (const Position &p, bool perpendicular=false) const
closest 2D-distance to point p (or -1 if perpendicular is true and the point is beyond this vector)
std::vector< double > distances (const PositionVector &s, bool perpendicular=false) const
distances of all my points to s and all of s points to myself
void extrapolate (const double val, const bool onlyFirst=false, const bool onlyLast=false)
extrapolate position vector
void extrapolate2D (const double val, const bool onlyFirst=false)
extrapolate position vector in two dimensions (Z is ignored)
Boundary getBoxBoundary () const
Returns a boundary enclosing this list of lines.
Position getCentroid () const
Returns the centroid (closes the polygon if unclosed)
Position getLineCenter () const
get line center
double getMaxGrade () const
return the maximum grade of all segments as a fraction of zRange/length2D
PositionVector getOrthogonal (const Position &p, double extend, bool before, double length=1.0) const
return orthogonal through p (extending this vector if necessary)
double getOverlapWith (const PositionVector &poly, double zThreshold) const
Returns the maximum overlaps between this and the given polygon (when not separated by at least zThreshold)
Position getPolygonCenter () const
Returns the arithmetic of all corner points.
PositionVector getSubpart (double beginOffset, double endOffset) const
get subpart of a position vector
PositionVector getSubpart2D (double beginOffset, double endOffset) const
get subpart of a position vector in two dimensions (Z is ignored)
PositionVector getSubpartByIndex (int beginIndex, int count) const
get subpart of a position vector using index and a cout
bool hasElevation () const
return whether two positions differ in z-coordinate
int indexOfClosest (const Position &p) const
index of the closest position to p
void insert_noDoublePos (const std::vector< Position >::iterator &at, const Position &p)
insert in front a non double position
int insertAtClosest (const Position &p)
inserts p between the two closest positions and returns the insertion index
PositionVector interpolateZ (double zStart, double zEnd) const
returned vector that varies z smoothly over its length
Position intersectionPosition2D (const Position &p1, const Position &p2, const double withinDist=0.) const
Returns the position of the intersection.
Position intersectionPosition2D (const PositionVector &v1) const
Returns the position of the intersection.
bool intersects (const Position &p1, const Position &p2) const
Returns the information whether this list of points interesects the given line.
bool intersects (const PositionVector &v1) const
Returns the information whether this list of points interesects one the given lines.
std::vector< double > intersectsAtLengths2D (const PositionVector &other) const
For all intersections between this vector and other, return the 2D-length of the subvector from this vectors start to the intersection.
std::vector< double > intersectsAtLengths2D (const Position &lp1, const Position &lp2) const
For all intersections between this vector and line, return the 2D-length of the subvector from this vectors start to the intersection.
bool isClosed () const
check if PositionVector is closed
double isLeft (const Position &P0, const Position &P1, const Position &P2) const
get left
double length () const
Returns the length.
double length2D () const
Returns the length.
void mirrorX ()
void move2side (double amount)
move position vector to side using certain ammount
double nearest_offset_to_point2D (const Position &p, bool perpendicular=true) const
return the nearest offest to point 2D
double offsetAtIndex2D (int index) const
return the offset at the given index
bool operator!= (const PositionVector &v2) const
comparing operation
PositionVector operator+ (const PositionVector &v2) const
adds two vectors (requires vectors of the same length)
PositionVector operator- (const PositionVector &v2) const
substracts two vectors (requires vectors of the same length)
bool operator== (const PositionVector &v2) const
comparing operation
const Position & operator[] (int index) const
returns the constat position at the given index !!! exceptions?
Position & operator[] (int index)
returns the position at the given index !!! exceptions?
bool overlapsWith (const AbstractPoly &poly, double offset=0) const
Returns the information whether the given polygon overlaps with this.
bool partialWithin (const AbstractPoly &poly, double offset=0) const
Returns the information whether this polygon lies partially within the given polygon.
Position positionAtOffset (double pos, double lateralOffset=0) const
Returns the position at the given length.
Position positionAtOffset2D (double pos, double lateralOffset=0) const
Returns the position at the given length.
PositionVector ()
Constructor. Creates an empty position vector.
PositionVector (const std::vector< Position > &v)
Copy Constructor. Create a positionVector with the same elements as other positionVector.
PositionVector (const std::vector< Position >::const_iterator beg, const std::vector< Position >::const_iterator end)
Parameter Constructor. Create a positionVector using a part of other positionVector.
PositionVector (const Position &p1, const Position &p2)
Parameter Constructor used for lines.
void push_back_noDoublePos (const Position &p)
insert in back a non double position
void push_front_noDoublePos (const Position &p)
insert in front a non double position
int removeClosest (const Position &p)
removes the point closest to p and return the removal index
void removeDoublePoints (double minDist=POSITION_EPS, bool assertLength=false)
Removes positions if too near.
PositionVector resample (double maxLength) const
resample shape with the given number of points (equal spacing)
PositionVector reverse () const
reverse position vector
void rotate2D (double angle)
double rotationAtOffset (double pos) const
Returns the rotation at the given length.
double rotationDegreeAtOffset (double pos) const
Returns the rotation at the given length.
void scaleAbsolute (double offset)
enlarges/shrinks the polygon by an absolute offset based at the centroid
void scaleRelative (double factor)
enlarges/shrinks the polygon by a factor based at the centroid
PositionVector simplified () const
return the same shape with intermediate colinear points removed
double slopeDegreeAtOffset (double pos) const
Returns the slope at the given length.
PositionVector smoothedZFront (double dist=std::numeric_limits< double >::max()) const
returned vector that is smoothed at the front (within dist)
void sortAsPolyCWByAngle ()
short as polygon CV by angle
void sortByIncreasingXY ()
shory by increasing X-Y Psitions
std::pair< PositionVector, PositionVector > splitAt (double where) const
Returns the two lists made when this list vector is splitted at the given point.
Position transformToVectorCoordinates (const Position &p, bool extend=false) const
return position p within the length-wise coordinate system defined by this position vector. The x value is the same as that returned by nearest_offset_to_point2D(p) and the y value is the perpendicular distance to this vector with the sign indicating the side (right is postive). if extend is true, the vector is extended on both sides and the x-coordinate of the result may be below 0 or above the length of the original vector
~PositionVector ()
Destructor.
Static Public Member Functions
static Position positionAtOffset (const Position &p1, const Position &p2, double pos, double lateralOffset=0.)
Returns the position between the two given point at the specified position.
static Position positionAtOffset2D (const Position &p1, const Position &p2, double pos, double lateralOffset=0.)
Returns the position between the two given point at the specified position.
static Position sideOffset (const Position &beg, const Position &end, const double amount)
get a side position of position vector using a offset
Static Public Attributes
static const PositionVector EMPTY
empty Vector
Private Types
typedef std::vector< Position > vp
vector of position
Static Private Member Functions
static bool intersects (const Position &p11, const Position &p12, const Position &p21, const Position &p22, const double withinDist=0., double *x=0, double *y=0, double *mu=0)
return whether the line segments defined by Line p11,p12 and Line p21,p22 intersect
Friends
std::ostream & operator<< (std::ostream &os, const PositionVector &geom)
Detailed Description
A list of positions.
Definition at line 52 of file PositionVector.h.
Member Typedef Documentation
vp
typedef std::vector<Position> PositionVector::vp private
vector of position
Definition at line 56 of file PositionVector.h.
Constructor & Destructor Documentation
PositionVector() [1/4]
PositionVector::PositionVector ()
Constructor. Creates an empty position vector.
Definition at line 58 of file PositionVector.cpp.
PositionVector() [2/4]
PositionVector::PositionVector (const std::vector< Position > & v)
Copy Constructor. Create a positionVector with the same elements as other positionVector.
Parameters
[in] v The vector to copy
Definition at line 61 of file PositionVector.cpp.
PositionVector() [3/4]
PositionVector::PositionVector (const std::vector< Position >::const_iterator beg, const std::vector< Position >::const_iterator end)
Parameter Constructor. Create a positionVector using a part of other positionVector.
Parameters
[in] beg The begin iterator for copy
[in] end The end iterator to copy
Definition at line 66 of file PositionVector.cpp.
PositionVector() [4/4]
PositionVector::PositionVector (const Position & p1, const Position & p2)
Parameter Constructor used for lines.
Parameters
[in] p1 the first position
[in] p2 the second position
Definition at line 71 of file PositionVector.cpp.
~PositionVector()
PositionVector::~PositionVector ()
Destructor.
Definition at line 77 of file PositionVector.cpp.
Member Function Documentation
add() [1/2]
void PositionVector::add (double xoff, double yoff, double zoff)
Definition at line 567 of file PositionVector.cpp.
Referenced by add(), computeSameEnd(), NIImporter_OpenDrive::computeShapes(), NIImporter_OpenDrive::geomFromSpiral(), getOrthogonal(), NBEdge::init(), GNEPoly::moveEntireShape(), GNEEdge::moveEntireShape(), GNEPoly::moveVertexShape(), GNEEdge::moveVertexShape(), operator+(), operator-(), NBDistrict::reshiftPosition(), NBNode::reshiftPosition(), NBEdge::reshiftPosition(), GNEEdge::updateJunctionPosition(), NWWriter_OpenDrive::writeGeomPP3(), and NWWriter_OpenDrive::writeGeomSmooth().
add() [2/2]
void PositionVector::add (const Position & offset)
Definition at line 575 of file PositionVector.cpp.
References add(), Position::x(), Position::y(), and Position::z().
angleAt2D()
double PositionVector::angleAt2D (int pos) const
get angle in certain position of position vector
Definition at line 1012 of file PositionVector.cpp.
Referenced by NBNode::bezierControlPoints(), NBEdge::checkGeometry(), NBEdge::getAngleAtNode(), NBContHelper::edge_opposite_direction_sorter::getEdgeAngleAt(), NBNodeShapeComputer::joinSameDirectionEdges(), MSLane::incoming_lane_priority_sorter::operator()(), MSLane::outgoing_lane_priority_sorter::operator()(), NWWriter_OpenDrive::writeGeomLines(), and NWWriter_OpenDrive::writeGeomPP3().
append()
void PositionVector::append (const PositionVector & v, double sameThreshold = 2.0)
Definition at line 623 of file PositionVector.cpp.
Referenced by NBEdge::append(), NBNode::buildWalkingAreas(), NBEdgeCont::checkOverlap(), NBNode::computeInternalLaneShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBEdgeCont::formFactor(), MSTransportable::getBoundingBox(), MSVehicle::getBoundingBox(), GNENet::replaceJunctionByGeometry(), and GNEConnection::updateGeometry().
area()
double PositionVector::area () const
Returns the area (0 for non-closed)
Definition at line 466 of file PositionVector.cpp.
References isClosed().
Referenced by GNEJunction::drawGL(), NBEdgeCont::formFactor(), getCentroid(), NBNode::sortEdges(), and GNEConnection::updateGeometry().
around()
bool PositionVector::around (const Position & p, double offset = 0) const virtual
Returns the information whether the position vector describes a polygon lying around the given point.
Note
The optional offset is added to the polygon's boundaries
Implements AbstractPoly.
Definition at line 81 of file PositionVector.cpp.
References GeomHelper::angle2D(), around(), M_PI, scaleAbsolute(), Position::x(), and Position::y().
Referenced by around(), NBEdge::computeAngle(), NBNode::computeNodeShape(), NBHeightMapper::Triangle::contains(), NBNode::getCenter(), getOverlapWith(), and NIVissimTL::NIVissimTLSignal::isWithin().
beginEndAngle()
double PositionVector::beginEndAngle () const
returns the angle in radians of the line connecting the first and the last position
Definition at line 729 of file PositionVector.cpp.
Referenced by NBEdge::cutAtIntersection(), NIVissimEdge::dict_checkEdges2Join(), NIVissimConnectionCluster::getIncomingContinuation(), NIVissimConnectionCluster::getIncomingContinuationGeometry(), NIVissimConnectionCluster::getOutgoingContinuation(), NIVissimConnectionCluster::getOutgoingContinuationGeometry(), GNEEdge::isInverted(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::same_direction_sorter::operator()(), GUIEdge::setFunctionalColor(), and GUILane::setFunctionalColor().
closePolygon()
void PositionVector::closePolygon ()
ensures that the last position equals the first
Definition at line 1019 of file PositionVector.cpp.
Referenced by GNEPoly::closePolygon(), GNEJunction::drawGL(), GUIJunctionWrapper::drawGL(), NBNode::getCenter(), GNEViewNet::onCmdEditJunctionShape(), NLHandler::openJunction(), NIVissimSingleTypeParser_Knotendefinition::parse(), NIXMLNodesHandler::processNodeType(), GNEPoly::setAttribute(), NBEdge::startShapeAt(), and GNEFrame::DrawingMode::stopDrawing().
crosses()
bool PositionVector::crosses (const Position & p1, const Position & p2) const virtual
Implements AbstractPoly.
Definition at line 502 of file PositionVector.cpp.
References intersects().
distance2D()
double PositionVector::distance2D (const Position & p, bool perpendicular = false) const
closest 2D-distance to point p (or -1 if perpendicular is true and the point is beyond this vector)
Definition at line 1048 of file PositionVector.cpp.
References Position::distanceTo2D(), GeomHelper::INVALID_OFFSET, nearest_offset_to_point2D(), and positionAtOffset2D().
Referenced by LaneStoringVisitor::add(), NWWriter_OpenDrive::checkLaneGeometries(), NBEdge::computeAngle(), NBNode::computeNodeShape(), distances(), GNEPoly::drawGL(), NBPTStopCont::findAccessEdgesForRailStops(), libsumo::Helper::findCloserLane(), NBNode::getCenter(), getOverlapWith(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), NBEdge::shiftPositionAtNode(), and transformToVectorCoordinates().
distances()
std::vector< double > PositionVector::distances (const PositionVector & s, bool perpendicular = false) const
distances of all my points to s and all of s points to myself
Note
if perpendicular is set to true, only the perpendicular distances are returned
Definition at line 1028 of file PositionVector.cpp.
References distance2D(), and GeomHelper::INVALID_OFFSET.
Referenced by NBNodeShapeComputer::badIntersection(), NBEdgeCont::guessOpposites(), and NBEdge::isNearEnough2BeJoined2().
extrapolate()
void PositionVector::extrapolate (const double val, const bool onlyFirst = false, const bool onlyLast = false)
extrapolate position vector
Definition at line 897 of file PositionVector.cpp.
References Position::add(), Position::distanceTo(), and Position::sub().
Referenced by NBNode::buildCrossings(), NBEdge::buildInnerEdges(), GUILane::debugDrawFoeIntersections(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), NBEdge::extendGeometryAtNode(), NIVissimAbstractEdge::getGeomPosition(), MSPModel_Striping::initWalkingAreaPaths(), NIImporter_SUMO::reconstructEdgeShape(), NBEdge::startShapeAt(), transformToVectorCoordinates(), and GNEConnection::updateGeometry().
extrapolate2D()
void PositionVector::extrapolate2D (const double val, const bool onlyFirst = false)
extrapolate position vector in two dimensions (Z is ignored)
Definition at line 918 of file PositionVector.cpp.
References Position::add(), Position::distanceTo2D(), and Position::sub().
Referenced by NBNode::bezierControlPoints(), NBNodeShapeComputer::computeNodeShapeSmall(), computeSameEnd(), getOrthogonal(), move2side(), and NBEdge::setNodeBorder().
getBoxBoundary()
Boundary PositionVector::getBoxBoundary () const
Returns a boundary enclosing this list of lines.
Definition at line 356 of file PositionVector.cpp.
References Boundary::add().
Referenced by PCPolyContainer::add(), NBHeightMapper::addTriangle(), NBEdgeCont::checkOverlap(), libsumo::Helper::collectObjectsInRange(), GUIPolygon::drawGL(), MSLane::fill(), GNEConnection::getBoundary(), GNELane::getBoundary(), GNECrossing::getCenteringBoundary(), GNEInternalLane::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GNELane::getCenteringBoundary(), GNEConnection::getCenteringBoundary(), GUIChargingStation::getCenteringBoundary(), GUIContainerStop::getCenteringBoundary(), GUIBusStop::getCenteringBoundary(), GUIParkingArea::getCenteringBoundary(), GNEAdditional::getCenteringBoundary(), GUIJunctionWrapper::GUIJunctionWrapper(), NBEdgeCont::ignoreFilterMatch(), NIImporter_OpenDrive::loadNetwork(), GUIE2Collector::MyWrapper::MyWrapper(), NIVissimConnectionCluster::recomputeBoundary(), GNEPoly::simplifyShape(), and GNEJunction::updateGeometry().
getCentroid()
Position PositionVector::getCentroid () const
Returns the centroid (closes the polygon if unclosed)
Definition at line 380 of file PositionVector.cpp.
References area(), isClosed(), and length().
Referenced by NBEdge::computeAngle(), scaleAbsolute(), and scaleRelative().
getLineCenter()
Position PositionVector::getLineCenter () const
get line center
Definition at line 437 of file PositionVector.cpp.
References length(), and positionAtOffset().
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), GNEDetectorE1::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEVaporizer::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNEDetectorE2::updateGeometry(), GNERouteProbe::updateGeometry(), and GNEChargingStation::updateGeometry().
getMaxGrade()
double PositionVector::getMaxGrade () const
return the maximum grade of all segments as a fraction of zRange/length2D
Definition at line 1406 of file PositionVector.cpp.
References Position::distanceTo2D(), MAX2(), and Position::z().
Referenced by NBEdgeCont::checkGrade().
getOrthogonal()
PositionVector PositionVector::getOrthogonal (const Position & p, double extend, bool before, double length = 1.0) const
return orthogonal through p (extending this vector if necessary)
Parameters
[in] p The point through which to draw the orthogonal
[in] extend how long to extend this vector for finding an orthogonal
[in] front Whether to take the segment before or after the base point in case of ambiguity
[in] length the length of the orthogonal
Definition at line 1293 of file PositionVector.cpp.
References add(), DEG2RAD, extrapolate2D(), getSubpart2D(), indexOfClosest(), GeomHelper::INVALID_OFFSET, nearest_offset_to_point2D(), NUMERICAL_EPS, offsetAtIndex2D(), positionAtOffset2D(), and rotate2D().
Referenced by GUILane::debugDrawFoeIntersections(), NBEdge::setNodeBorder(), and GNEConnection::updateGeometry().
getOverlapWith()
double PositionVector::getOverlapWith (const PositionVector & poly, double zThreshold) const
Returns the maximum overlaps between this and the given polygon (when not separated by at least zThreshold)
Definition at line 135 of file PositionVector.cpp.
References around(), distance2D(), MAX2(), nearest_offset_to_point2D(), positionAtOffset2D(), and Position::z().
Referenced by NBEdgeCont::checkOverlap().
getPolygonCenter()
Position PositionVector::getPolygonCenter () const
Returns the arithmetic of all corner points.
Note
: this is different from the centroid!
Definition at line 366 of file PositionVector.cpp.
References Position::x().
Referenced by NIVissimNodeCluster::buildNBNode(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GUIPolygon::drawGL(), NBNode::getCenter(), and GNEPoly::getPositionInView().
getSubpart()
PositionVector PositionVector::getSubpart (double beginOffset, double endOffset) const
get subpart of a position vector
Definition at line 633 of file PositionVector.cpp.
References length(), POSITION_EPS, positionAtOffset(), and push_back_noDoublePos().
Referenced by NBNode::computeInternalLaneShape(), NBEdge::cutAtIntersection(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), MSParkingArea::MSParkingArea(), GUIE2Collector::MyWrapper::MyWrapper(), GNEStoppingPlace::setStoppingPlaceGeometry(), GNEDetectorE2::updateGeometry(), and NWWriter_SUMO::writeLane().
getSubpart2D()
PositionVector PositionVector::getSubpart2D (double beginOffset, double endOffset) const
get subpart of a position vector in two dimensions (Z is ignored)
Definition at line 673 of file PositionVector.cpp.
References length2D(), POSITION_EPS, positionAtOffset2D(), and push_back_noDoublePos().
Referenced by NBNodeShapeComputer::badIntersection(), computeSameEnd(), NBEdge::extendGeometryAtNode(), NIImporter_OpenDrive::geomFromArc(), NIImporter_OpenDrive::geomFromParamPoly(), NIImporter_OpenDrive::geomFromPoly(), NIImporter_OpenDrive::geomFromSpiral(), getOrthogonal(), NIImporter_OpenDrive::loadNetwork(), NBEdge::shortenGeometryAtNode(), and NBEdge::startShapeAt().
getSubpartByIndex()
PositionVector PositionVector::getSubpartByIndex (int beginIndex, int count) const
get subpart of a position vector using index and a cout
Definition at line 713 of file PositionVector.cpp.
Referenced by NBNode::buildWalkingAreas(), NBNodeShapeComputer::computeNodeShapeSmall(), NBEdge::getInnerGeometry(), and NBEdge::startShapeAt().
hasElevation()
bool PositionVector::hasElevation () const
return whether two positions differ in z-coordinate
Definition at line 1155 of file PositionVector.cpp.
indexOfClosest()
int PositionVector::indexOfClosest (const Position & p) const
index of the closest position to p
Note
: may only be called for a non-empty vector
Definition at line 815 of file PositionVector.cpp.
References Position::distanceTo().
Referenced by NBPTStopCont::computeCrossProductEdgePosition(), NIImporter_OpenDrive::computeShapes(), GNEEdge::deleteGeometryPoint(), GNEPoly::deleteGeometryPoint(), getOrthogonal(), GNEEdge::getSplitPos(), GNEEdge::getVertexIndex(), GNEEdge::setEndpoint(), smoothedZFront(), and GUILane::splitAtSegments().
insert_noDoublePos()
void PositionVector::insert_noDoublePos (const std::vector< Position >::iterator & at, const Position & p)
insert in front a non double position
Definition at line 1080 of file PositionVector.cpp.
References Position::almostSame(), push_back_noDoublePos(), and push_front_noDoublePos().
Referenced by NBEdge::addGeometryPoint().
insertAtClosest()
int PositionVector::insertAtClosest (const Position & p)
inserts p between the two closest positions and returns the insertion index
Definition at line 832 of file PositionVector.cpp.
References Position::distanceTo2D(), length(), GeomHelper::nearest_offset_on_line_to_point2D(), and positionAtOffset2D().
Referenced by NIImporter_OpenDrive::computeShapes(), GNEEdge::getVertexIndex(), smoothedZFront(), and GUILane::splitAtSegments().
interpolateZ()
PositionVector PositionVector::interpolateZ (double zStart, double zEnd) const
returned vector that varies z smoothly over its length
Definition at line 1361 of file PositionVector.cpp.
References length(), and length2D().
Referenced by GNEEdge::straightenElevation().
intersectionPosition2D() [1/2]
Position PositionVector::intersectionPosition2D (const Position & p1, const Position & p2, const double withinDist = 0.) const
Returns the position of the intersection.
Definition at line 188 of file PositionVector.cpp.
References intersects(), and Position::INVALID.
Referenced by NIVissimAbstractEdge::crossesEdgeAtPoint(), GeomHelper::crossPoint(), intersectionPosition2D(), move2side(), and NIImporter_SUMO::reconstructEdgeShape().
intersectionPosition2D() [2/2]
Position PositionVector::intersectionPosition2D (const PositionVector & v1) const
Returns the position of the intersection.
Definition at line 200 of file PositionVector.cpp.
References intersectionPosition2D(), intersects(), and Position::INVALID.
intersects() [1/3]
bool PositionVector::intersects (const Position & p1, const Position & p2) const
Returns the information whether this list of points interesects the given line.
Definition at line 160 of file PositionVector.cpp.
Referenced by NBNodeShapeComputer::badIntersection(), NBNodeShapeComputer::computeNodeShapeDefault(), computeSameEnd(), Boundary::crosses(), crosses(), NIVissimAbstractEdge::crossesEdge(), GeomHelper::crossPoint(), intersectionPosition2D(), intersects(), intersectsAtLengths2D(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIImporter_SUMO::reconstructEdgeShape(), and NBEdge::startShapeAt().
intersects() [2/3]
bool PositionVector::intersects (const PositionVector & v1) const
Returns the information whether this list of points interesects one the given lines.
Definition at line 174 of file PositionVector.cpp.
References intersects().
intersects() [3/3]
bool PositionVector::intersects (const Position & p11, const Position & p12, const Position & p21, const Position & p22, const double withinDist = 0., double * x = 0, double * y = 0, double * mu = 0) static private
return whether the line segments defined by Line p11,p12 and Line p21,p22 intersect
Definition at line 1169 of file PositionVector.cpp.
References Position::distanceTo2D(), Position::x(), and Position::y().
intersectsAtLengths2D() [1/2]
std::vector< double > PositionVector::intersectsAtLengths2D (const PositionVector & other) const
For all intersections between this vector and other, return the 2D-length of the subvector from this vectors start to the intersection.
Definition at line 869 of file PositionVector.cpp.
Referenced by NBNodeShapeComputer::closestIntersection(), NBNodeShapeComputer::computeNodeShapeDefault(), computeSameEnd(), NBEdge::firstIntersection(), MSLink::setRequestInformation(), and NBEdge::startShapeAt().
intersectsAtLengths2D() [2/2]
std::vector< double > PositionVector::intersectsAtLengths2D (const Position & lp1, const Position & lp2) const
For all intersections between this vector and line, return the 2D-length of the subvector from this vectors start to the intersection.
Definition at line 880 of file PositionVector.cpp.
References Position::distanceTo2D(), and intersects().
isClosed()
bool PositionVector::isClosed () const
check if PositionVector is closed
Definition at line 1094 of file PositionVector.cpp.
Referenced by area(), and getCentroid().
isLeft()
double PositionVector::isLeft (const Position & P0, const Position & P1, const Position & P2) const
get left
Note
previously marked with "!!!"
Definition at line 617 of file PositionVector.cpp.
References Position::x(), and Position::y().
Referenced by transformToVectorCoordinates().
length()
double PositionVector::length () const
Returns the length.
Definition at line 446 of file PositionVector.cpp.
Referenced by NIXMLEdgesHandler::addSplit(), NBNodeShapeComputer::badIntersection(), GNEViewNet::begingMoveSelection(), NBEdge::buildInnerEdges(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), NGRandomNetBuilder::canConnect(), NBEdge::computeAngle(), NBNode::computeInternalLaneShape(), NBEdge::cutAtIntersection(), GUILane::debugDrawFoeIntersections(), NIVissimEdge::dict_checkEdges2Join(), GUIVehicle::drawBestLanes(), GUIEdge::drawGL(), GNEEdge::drawGL(), NBPTStop::findLaneAndComputeBusStopExtend(), NBEdge::firstIntersection(), getCentroid(), NBEdge::getFinalLength(), NIVissimAbstractEdge::getGeomPosition(), NWWriter_DlrNavteq::getGraphLength(), GNELane::getLaneShapeLength(), NIVissimEdge::getLength(), getLineCenter(), NWWriter_SUMO::getOppositeInternalID(), GNEDetector::getPositionInView(), GNECalibrator::getPositionInView(), NBEdge::getShapeEndAngle(), getSubpart(), NIVissimEdge::getToNode(), GNEEdge::getVertexIndex(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUILane::GUILane(), GUIParkingArea::GUIParkingArea(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), insertAtClosest(), interpolateZ(), NIXMLEdgesHandler::myEndElement(), NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition::myEndElement(), NIImporter_OpenStreetMap::RelationHandler::myEndElement(), NBContHelper::relative_incoming_edge_sorter::operator()(), operator+(), operator-(), resample(), NIVissimEdge::resolveSameNode(), rotationAtOffset(), GNEAdditional::setBlockIconRotation(), GNEStoppingPlace::setStoppingPlaceGeometry(), smoothedZFront(), splitAt(), NBEdgeCont::splitAt(), GNEConnection::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEVaporizer::updateGeometry(), GNEDetectorE2::updateGeometry(), GNECalibrator::updateGeometry(), NWWriter_SUMO::writeLane(), and GNEPOILane::writeShape().
length2D()
double PositionVector::length2D () const
Returns the length.
Definition at line 456 of file PositionVector.cpp.
Referenced by NBEdge::computeAngle(), NBNodeShapeComputer::computeNodeShapeDefault(), computeSameEnd(), NBEdge::extendGeometryAtNode(), NBEdgeCont::formFactor(), NBEdge::getShapeEndAngle(), NBEdge::getShapeStartAngle(), getSubpart2D(), interpolateZ(), NIImporter_OpenDrive::loadNetwork(), move2side(), NBContHelper::straightness_sorter::operator()(), NIImporter_OpenStreetMap::reconstructLayerElevation(), resample(), NBEdge::shortenGeometryAtNode(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), NBEdge::startShapeAt(), NWWriter_OpenDrive::writeGeomSmooth(), and NWWriter_OpenDrive::writeInternalEdge().
mirrorX()
void PositionVector::mirrorX ()
Definition at line 581 of file PositionVector.cpp.
Referenced by NBDistrict::mirrorX(), NBNode::mirrorX(), and NBEdge::mirrorX().
move2side()
void PositionVector::move2side (double amount)
move position vector to side using certain ammount
Definition at line 954 of file PositionVector.cpp.
References Position::distanceTo2D(), extrapolate2D(), intersectionPosition2D(), Position::INVALID, length2D(), POSITION_EPS, removeDoublePoints(), sideOffset(), and Position::z().
Referenced by NBEdge::addRestrictedLane(), GNENet::addReversedEdge(), NBNodeShapeComputer::badIntersection(), NBNode::buildCrossings(), NBNode::buildWalkingAreas(), NBEdge::computeLaneShape(), NIImporter_OpenDrive::computeShapes(), GUIVehicle::drawBestLanes(), NBEdge::firstIntersection(), MSTransportable::getBoundingBox(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), NBEdge::getCCWBoundaryLine(), NBEdge::getCWBoundaryLine(), NWWriter_OpenDrive::getLeftLaneBorder(), MSVehicle::getPosition(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIParkingArea::GUIParkingArea(), NBRampsComputer::moveRampRight(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), MSParkingArea::MSParkingArea(), NIXMLEdgesHandler::myEndElement(), GNEStoppingPlace::setStoppingPlaceGeometry(), NBEdge::shiftPositionAtNode(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), GNEChargingStation::updateGeometry(), NBSign::writeAsPOI(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
nearest_offset_to_point2D()
double PositionVector::nearest_offset_to_point2D (const Position & p, bool perpendicular = true) const
return the nearest offest to point 2D
Definition at line 735 of file PositionVector.cpp.
References Position::distanceTo2D(), GeomHelper::INVALID_OFFSET, GeomHelper::nearest_offset_on_line_to_point2D(), and positionAtOffset2D().
Referenced by GNEAdditionalFrame::addAdditional(), GNEViewNet::begingMoveSelection(), NBNode::bezierControlPoints(), GNEDetector::commitGeometryMoving(), GNEPOILane::commitGeometryMoving(), GNEStoppingPlace::commitGeometryMoving(), NBPTStopCont::computeCrossProductEdgePosition(), distance2D(), GNEPoly::drawGL(), NBEdge::extendGeometryAtNode(), NBPTStop::findLaneAndComputeBusStopExtend(), getOrthogonal(), getOverlapWith(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), GNEAdditional::getPopUpMenu(), GUIEdge::getSegmentAtPosition(), GNEEdge::getSplitPos(), GNEDetector::moveGeometry(), GNEPOILane::moveGeometry(), GNEStoppingPlace::moveGeometry(), libsumo::Helper::moveToXYMap(), GNEViewNet::onCmdTransformPOI(), GNEPolygonFrame::processClick(), GNEAdditional::setBlockIconRotation(), NBEdgeCont::splitAt(), and GNENet::splitEdge().
offsetAtIndex2D()
double PositionVector::offsetAtIndex2D (int index) const
return the offset at the given index
Definition at line 1393 of file PositionVector.cpp.
References GeomHelper::INVALID_OFFSET.
Referenced by NBPTStopCont::computeCrossProductEdgePosition(), getOrthogonal(), and smoothedZFront().
operator!=()
bool PositionVector::operator!= (const PositionVector & v2) const
comparing operation
Definition at line 1122 of file PositionVector.cpp.
operator+()
PositionVector PositionVector::operator+ (const PositionVector & v2) const
adds two vectors (requires vectors of the same length)
Definition at line 1141 of file PositionVector.cpp.
References add(), length(), and WRITE_ERROR.
operator-()
PositionVector PositionVector::operator- (const PositionVector & v2) const
substracts two vectors (requires vectors of the same length)
Definition at line 1127 of file PositionVector.cpp.
References add(), length(), and WRITE_ERROR.
operator==()
bool PositionVector::operator== (const PositionVector & v2) const
comparing operation
Definition at line 1116 of file PositionVector.cpp.
operator[]() [1/2]
const Position & PositionVector::operator[] (int index) const
returns the constat position at the given index !!! exceptions?
Definition at line 211 of file PositionVector.cpp.
operator[]() [2/2]
Position & PositionVector::operator[] (int index)
returns the position at the given index !!! exceptions?
Definition at line 221 of file PositionVector.cpp.
overlapsWith()
bool PositionVector::overlapsWith (const AbstractPoly & poly, double offset = 0) const virtual
Returns the information whether the given polygon overlaps with this.
Note
Again a boundary may be specified
Implements AbstractPoly.
Definition at line 112 of file PositionVector.cpp.
References AbstractPoly::crosses(), AbstractPoly::partialWithin(), and partialWithin().
Referenced by MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), and NIVissimAbstractEdge::overlapsWith().
partialWithin()
bool PositionVector::partialWithin (const AbstractPoly & poly, double offset = 0) const virtual
Returns the information whether this polygon lies partially within the given polygon.
Implements AbstractPoly.
Definition at line 488 of file PositionVector.cpp.
References AbstractPoly::around().
Referenced by overlapsWith().
positionAtOffset() [1/2]
Position PositionVector::positionAtOffset (double pos, double lateralOffset = 0) const
Returns the position at the given length.
Definition at line 231 of file PositionVector.cpp.
Referenced by GUIBusStop::addAccess(), NIXMLEdgesHandler::addSplit(), GNEViewNet::begingMoveSelection(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), TraCIServerAPI_Simulation::commandPositionConversion(), GUIEdge::drawGL(), GNEEdge::drawGL(), GLHelper::drawTriangleAtEnd(), MSLane::geometryPositionAtOffset(), NIVissimAbstractEdge::getGeomPosition(), MSTransportable::Stage::getLanePosition(), getLineCenter(), TraCIServerAPI_InductionLoop::getPosition(), MSPModel_Striping::PState::getPosition(), MSVehicle::getPosition(), GNEDetector::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNECalibrator::getPositionInView(), MSVTKExport::getSpeed(), GNEEdge::getSplitPos(), getSubpart(), libsumo::InductionLoop::getTree(), MSStoppingPlace::getWaitPosition(), GUICalibrator::GUICalibrator(), GUILaneSpeedTrigger::GUILaneSpeedTrigger(), NIImporter_OpenDrive::loadNetwork(), MSParkingArea::MSParkingArea(), GNEViewNet::onCmdTransformPOI(), NIImporter_VISUM::parse_Lanes(), smoothedZFront(), splitAt(), GUILane::splitAtSegments(), transformToVectorCoordinates(), GNEConnection::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEVaporizer::updateGeometry(), GNERouteProbe::updateGeometry(), GNEPOILane::updateGeometry(), GNECalibrator::updateGeometry(), MSBatteryExport::write(), and NBSign::writeAsPOI().
positionAtOffset() [2/2]
Position PositionVector::positionAtOffset (const Position & p1, const Position & p2, double pos, double lateralOffset = 0.) static
Returns the position between the two given point at the specified position.
Definition at line 313 of file PositionVector.cpp.
References Position::distanceTo(), Position::INVALID, and sideOffset().
positionAtOffset2D() [1/2]
Position PositionVector::positionAtOffset2D (double pos, double lateralOffset = 0) const
Returns the position at the given length.
Definition at line 251 of file PositionVector.cpp.
Referenced by NBNode::bezierControlPoints(), NGRandomNetBuilder::canConnect(), NBEdge::computeAngle(), NBNodeShapeComputer::computeNodeShapeDefault(), computeSameEnd(), GUIVehicle::computeSeats(), NIImporter_OpenDrive::computeShapes(), distance2D(), GNEPoly::drawGL(), getOrthogonal(), getOverlapWith(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), CState::getPosition(), GUIContainer::getPosition(), NBEdge::getShapeEndAngle(), NBEdge::getShapeStartAngle(), getSubpart2D(), GNEEdge::getVertexIndex(), insertAtClosest(), nearest_offset_to_point2D(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::straightness_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), resample(), GNEEdge::smoothElevation(), GNEEdge::smoothShape(), NBEdge::startShapeAt(), and NWWriter_OpenDrive::writeGeomSmooth().
positionAtOffset2D() [2/2]
Position PositionVector::positionAtOffset2D (const Position & p1, const Position & p2, double pos, double lateralOffset = 0.) static
Returns the position between the two given point at the specified position.
Definition at line 336 of file PositionVector.cpp.
References Position::distanceTo2D(), Position::INVALID, and sideOffset().
push_back_noDoublePos()
void PositionVector::push_back_noDoublePos (const Position & p)
insert in back a non double position
Definition at line 1064 of file PositionVector.cpp.
References Position::almostSame().
Referenced by NIVissimNodeCluster::buildNBNode(), NBNode::buildWalkingAreas(), NBNode::computeNodeShape(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NIImporter_OpenDrive::computeShapes(), NBEdge::getFinalLength(), NWWriter_DlrNavteq::getGraphLength(), getSubpart(), getSubpart2D(), NBEdge::init(), MSPModel_Striping::initWalkingAreaPaths(), insert_noDoublePos(), PCLoaderArcView::load(), NIImporter_ArcView::load(), PCLoaderOSM::loadIfSet(), NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition::myEndElement(), NIVissimAbstractEdge::NIVissimAbstractEdge(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), GNENet::replaceJunctionByGeometry(), and GNEEdge::setAttribute().
push_front_noDoublePos()
void PositionVector::push_front_noDoublePos (const Position & p)
insert in front a non double position
Definition at line 1072 of file PositionVector.cpp.
References Position::almostSame().
Referenced by NBNode::buildWalkingAreas(), NBNodeShapeComputer::computeNodeShapeDefault(), NBEdge::getFinalLength(), NWWriter_DlrNavteq::getGraphLength(), NBEdge::init(), insert_noDoublePos(), GNEEdge::setAttribute(), and NBEdge::startShapeAt().
removeClosest()
int PositionVector::removeClosest (const Position & p)
removes the point closest to p and return the removal index
Definition at line 850 of file PositionVector.cpp.
References Position::distanceTo2D().
Referenced by GNEEdge::commitShapeChange().
removeDoublePoints()
void PositionVector::removeDoublePoints (double minDist = POSITION_EPS, bool assertLength = false)
Removes positions if too near.
Parameters
[in] minDist The minimum accepted distance; default: POSITION_EPS
[in] assertLength Whether the result must at least contain two points (be a line); default: false, to ensure original behaviour
Definition at line 1100 of file PositionVector.cpp.
Referenced by GNEPoly::commitShapeChange(), GNEEdge::commitShapeChange(), NIImporter_OpenDrive::computeShapes(), NBEdge::init(), move2side(), and NBEdge::reduceGeometry().
resample()
PositionVector PositionVector::resample (double maxLength) const
resample shape with the given number of points (equal spacing)
Definition at line 1379 of file PositionVector.cpp.
References length(), length2D(), POSITION_EPS, and positionAtOffset2D().
Referenced by GNEEdge::smoothElevation().
reverse()
PositionVector PositionVector::reverse () const
reverse position vector
Definition at line 937 of file PositionVector.cpp.
Referenced by GNENet::addReversedEdge(), NBNodeShapeComputer::badIntersection(), NBNode::buildWalkingAreas(), NBEdge::cutAtIntersection(), GUILane::drawLinkNo(), GUILane::drawLinkRules(), GUILane::drawTLSLinkNo(), MSTransportable::getBoundingBox(), MSVehicle::getBoundingBox(), NBNodeShapeComputer::getSmoothCorner(), MSPModel_Striping::initWalkingAreaPaths(), NIImporter_OpenStreetMap::insertEdge(), NIImporter_ArcView::load(), NIImporter_OpenDrive::loadNetwork(), NIImporter_VISUM::parse_AreaSubPartElement(), NIImporter_DlrNavteq::EdgesHandler::report(), and GNENet::reverseEdge().
rotate2D()
void PositionVector::rotate2D (double angle)
Definition at line 1253 of file PositionVector.cpp.
Referenced by NIImporter_OpenDrive::geomFromSpiral(), getOrthogonal(), and NWWriter_OpenDrive::writeGeomPP3().
rotationAtOffset()
double PositionVector::rotationAtOffset (double pos) const
Returns the rotation at the given length.
Definition at line 266 of file PositionVector.cpp.
References Position::angleTo2D(), Position::distanceTo(), and length().
Referenced by MSDevice_SSM::classifyEncounter(), MSVehicle::computeAngle(), GUIEdge::drawMesoVehicles(), MEVehicle::getAngle(), MSPModel_Striping::PState::getAngle(), libsumo::Person::moveToXY(), libsumo::Vehicle::moveToXY(), libsumo::Helper::moveToXYMap(), rotationDegreeAtOffset(), and MSLaneChangerSublane::startChangeSublane().
rotationDegreeAtOffset()
double PositionVector::rotationDegreeAtOffset (double pos) const
Returns the rotation at the given length.
Definition at line 288 of file PositionVector.cpp.
References GeomHelper::legacyDegree(), and rotationAtOffset().
Referenced by GUIE3Collector::MyWrapper::buildDefinition(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIBusStop::GUIBusStop(), GUICalibrator::GUICalibrator(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUILaneSpeedTrigger::GUILaneSpeedTrigger(), GUIParkingArea::GUIParkingArea(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GNEAdditional::setBlockIconRotation(), GNEDetectorE1::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEVaporizer::updateGeometry(), GNERouteProbe::updateGeometry(), and GNECalibrator::updateGeometry().
scaleAbsolute()
void PositionVector::scaleAbsolute (double offset)
enlarges/shrinks the polygon by an absolute offset based at the centroid
Definition at line 428 of file PositionVector.cpp.
References getCentroid().
Referenced by around().
scaleRelative()
void PositionVector::scaleRelative (double factor)
enlarges/shrinks the polygon by a factor based at the centroid
Definition at line 419 of file PositionVector.cpp.
References getCentroid().
Referenced by GNEJunction::drawGL(), GUIJunctionWrapper::drawGL(), and MSVehicle::getBoundingPoly().
sideOffset()
Position PositionVector::sideOffset (const Position & beg, const Position & end, const double amount) static
get a side position of position vector using a offset
Definition at line 947 of file PositionVector.cpp.
References Position::distanceTo2D(), Position::x(), and Position::y().
Referenced by NWWriter_OpenDrive::checkLaneGeometries(), move2side(), positionAtOffset(), positionAtOffset2D(), and NIImporter_SUMO::reconstructEdgeShape().
simplified()
PositionVector PositionVector::simplified () const
return the same shape with intermediate colinear points removed
Definition at line 1268 of file PositionVector.cpp.
References Position::distanceTo2D(), NUMERICAL_EPS, Position::x(), and Position::y().
Referenced by NWWriter_SUMO::writeJunction().
slopeDegreeAtOffset()
double PositionVector::slopeDegreeAtOffset (double pos) const
Returns the slope at the given length.
Definition at line 294 of file PositionVector.cpp.
References Position::distanceTo(), Position::distanceTo2D(), RAD2DEG, and Position::z().
Referenced by MEVehicle::getSlope(), and MSVehicle::getSlope().
smoothedZFront()
PositionVector PositionVector::smoothedZFront (double dist = std::numeric_limits<double>::max()) const
returned vector that is smoothed at the front (within dist)
Definition at line 1332 of file PositionVector.cpp.
References Position::distanceTo2D(), indexOfClosest(), insertAtClosest(), length(), MIN2(), offsetAtIndex2D(), POSITION_EPS, and positionAtOffset().
Referenced by NBEdge::startShapeAt().
sortAsPolyCWByAngle()
void PositionVector::sortAsPolyCWByAngle ()
short as polygon CV by angle
Definition at line 561 of file PositionVector.cpp.
sortByIncreasingXY()
void PositionVector::sortByIncreasingXY ()
shory by increasing X-Y Psitions
Definition at line 598 of file PositionVector.cpp.
splitAt()
std::pair< PositionVector, PositionVector > PositionVector::splitAt (double where) const
Returns the two lists made when this list vector is splitted at the given point.
Definition at line 508 of file PositionVector.cpp.
References length(), POSITION_EPS, positionAtOffset(), toString(), and WRITE_WARNING.
Referenced by NBEdge::buildInnerEdges(), NBEdgeCont::splitAt(), and GNENet::splitEdge().
transformToVectorCoordinates()
Position PositionVector::transformToVectorCoordinates (const Position & p, bool extend = false) const
return position p within the length-wise coordinate system defined by this position vector. The x value is the same as that returned by nearest_offset_to_point2D(p) and the y value is the perpendicular distance to this vector with the sign indicating the side (right is postive). if extend is true, the vector is extended on both sides and the x-coordinate of the result may be below 0 or above the length of the original vector
Definition at line 768 of file PositionVector.cpp.
References distance2D(), Position::distanceTo2D(), extrapolate(), Position::INVALID, GeomHelper::INVALID_OFFSET, isLeft(), GeomHelper::nearest_offset_on_line_to_point2D(), positionAtOffset(), and transformToVectorCoordinates().
Referenced by MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirection(), and transformToVectorCoordinates().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const PositionVector & geom) friend
Definition at line 549 of file PositionVector.cpp.
Field Documentation
EMPTY
const PositionVector PositionVector::EMPTY static
empty Vector
Definition at line 80 of file PositionVector.h.
Referenced by NIImporter_SUMO::addConnection(), NIXMLConnectionsHandler::addCrossing(), NIXMLConnectionsHandler::addWalkingArea(), NBEdge::getLaneSpreadFunction(), NBNode::getProhibitions(), GNECrossingFrame::onCmdCreateCrossing(), NIXMLConnectionsHandler::parseLaneBound(), NIImporter_DlrNavteq::ConnectedLanesHandler::report(), and GNEEdge::smoothShape().
The documentation for this class was generated from the following files:
PositionVector.h
PositionVector.cpp