SUMO - Simulation of Urban MObility: MSLCM_LC2013 Class Reference
MSLCM_LC2013 Class Reference
A lane change model developed by D. Krajzewicz, J. Erdmann et al. between 2004 and 2013.
#include <MSLCM_LC2013.h>
Public Types
enum MyLCAEnum {
LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18, LCA_MLEFT = 1 << 19,
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_CHANGE_TO_HELP = 1 << 23, LCA_AMBACKBLOCKER = 1 << 26, LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
double _patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
void changed ()
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void checkTraCICommands ()
Check for commands issued for the vehicle via TraCI and apply the appropriate state changes For the sublane case, this includes setting a new maneuver distance if appropriate.
void cleanupShadowLane ()
void cleanupTargetLane ()
virtual double computeSpeedLat (double latDist, double &maneuverDist)
decides the next lateral speed depending on the remaining lane change distance to be covered and updates maneuverDist according to lateral safety constraints.
bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
MSLane * determineTargetLane (int &targetDir) const
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
double getAngleOffset () const
return the angle offset during a continuous change maneuver
double getCommittedSpeed () const
const std::vector< MSLane * > & getFurtherTargetLanes () const
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
double getManeuverDist () const
Returns the remaining unblocked distance for the current maneuver. (only used by sublane model)
int getOwnState () const
std::string getParameter (const std::string &key) const
try to retrieve the given parameter from this device. Throw exception for unsupported key
int getPrevState () const
const std::pair< int, int > & getSavedState (const int dir) const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< double > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicle's shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
MSLane * getShadowLane (const MSLane *lane, double posLat) const
return the shadow lane for the given lane and lateral offset
double getSpeedLat () const
return the lateral speed of the current lane change maneuver
MSLane * getTargetLane () const
Returns the lane the vehicle has committed to enter during a sublane lane change.
void * inform (void *info, MSVehicle *sender)
void initDerivedParameters ()
init cached parameters derived directly from model parameters
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
void laneChangeOutput (const std::string &tag, MSLane *source, MSLane *target, int direction)
called once the vehicle ends a lane change manoeuvre (non-instant)
MSLCM_LC2013 (MSVehicle &v)
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
double patchSpeed (const double min, const double wanted, const double max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change. It uses information on LC-related desired speed-changes from the call to wantsChange() at the end of the previous simulation step.
void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
void saveState (const int dir, const int stateWithoutTraCI, const int state)
void setFollowerGaps (CLeaderDist follower, double secGap)
void setFollowerGaps (const MSLeaderDistanceInfo &vehicles)
void setLeaderGaps (CLeaderDist, double secGap)
void setLeaderGaps (const MSLeaderDistanceInfo &vehicles)
void setManeuverDist (const double dist)
Updates the remaining distance for the current maneuver while it is continued within non-action steps (only used by sublane model)
void setNoShadowPartialOccupator (MSLane *lane)
void setOrigLeaderGaps (CLeaderDist, double secGap)
void setOrigLeaderGaps (const MSLeaderDistanceInfo &vehicles)
virtual void setOwnState (const int state)
void setParameter (const std::string &key, const std::string &value)
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
void setSpeedLat (double speedLat)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
virtual bool sublaneChangeCompleted (const double latDist) const
whether the current change completes the manoeuvre
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderDistanceInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
virtual void updateSafeLatDist (const double travelledLatDist)
Updates the value of safe lateral distances (in SL2015) during maneuver continuation in non-action steps.
void updateShadowLane ()
void updateTargetLane ()
int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, LaneChangeAction alternatives, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, double &latDist, double &targetDistLat, int &blocked)
virtual ~MSLCM_LC2013 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static bool haveLCOutput ()
whether lanechange-output is active
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
static bool outputLCEnded ()
whether start of maneuvers shall be recorede
static bool outputLCStarted ()
whether start of maneuvers shall be recorede
Static Public Attributes
static const double NO_NEIGHBOR
Protected Types
typedef std::pair< double, int > Info
information regarding save velocity (unused) and state flags of the ego vehicle
Protected Member Functions
int _wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, double > &leader, const std::pair< MSVehicle *, double > &neighLead, const std::pair< MSVehicle *, double > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
helper function for doing the actual work
void adaptSpeedToPedestrians (const MSLane *lane, double &v)
react to pedestrians on the given lane
void addLCSpeedAdvice (const double vSafe)
Takes a vSafe (speed advice for speed in the next simulation step), converts it into an acceleration and stores it into myLCAccelerationAdvices.
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (double dist, int laneOffset, double lookForwardDist)
bool currentDistDisallows (double dist, int laneOffset, double lookForwardDist)
void informFollower (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, int dir, const std::pair< MSVehicle *, double > &neighFollow, double remainingSeconds, double plannedSpeed)
decide whether we will try cut in before the follower or allow to be overtaken
double informLeader (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, int dir, const std::pair< MSVehicle *, double > &neighLead, double remainingSeconds)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, double > &leader)
double roundaboutDistBonus (double roundaboutDistAhead, int roundaboutEdgesAhead) const
Computes the artificial bonus distance for roundabout lanes this additional distance reduces the sense of urgency within roundabouts and thereby promotes the use of the inner roundabout lane in multi-lane roundabouts.
void saveBlockerLength (MSVehicle *blocker, int lcaCounter)
save space for vehicles which need to counter-lane-change
void saveBlockerLength (double length)
reserve space at the end of the lane to avoid dead locks
int slowDownForBlocked (MSVehicle **blocked, int state)
compute useful slowdowns for blocked vehicles
Static Protected Member Functions
static double distanceAlongNextRoundabout (double position, const MSLane *initialLane, const std::vector< MSLane *> &continuationLanes)
compute the distance on the next upcoming roundabout along a given sequence of lanes.
static void getRoundaboutAheadInfo (const MSLCM_LC2013 *lcm, const MSVehicle::LaneQ &curr, const MSVehicle::LaneQ &neigh, double &roundaboutDistanceAhead, double &roundaboutDistanceAheadNeigh, int &roundaboutEdgesAhead, int &roundaboutEdgesAheadNeigh)
computes the distance and number of edges in the next upcoming roundabout along the lane continuations given in curr and neigh
static double overtakeDistance (const MSVehicle *follower, const MSVehicle *leader, const double gap, double followerSpeed=INVALID_SPEED, double leaderSpeed=INVALID_SPEED)
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
double myCommittedSpeed
the speed when committing to a change maneuver
bool myDontBrake
std::vector< MSLane * > myFurtherTargetLanes
double myKeepRightProbability
double myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
double myLastFollowerGap
double myLastFollowerSecureGap
double myLastLateralGapLeft
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
double myLastLateralGapRight
double myLastLeaderGap
the actual minimum longitudinal distances to vehicles on the target lane
double myLastLeaderSecureGap
the minimum longitudinal distances to vehicles on the target lane that would be necessary for stringent security
double myLastOrigLeaderGap
acutal and secure distance to closest leader vehicle on the original when performing lane change
double myLastOrigLeaderSecureGap
std::vector< double > myLCAccelerationAdvices
vector of LC-related acceleration recommendations Filled in wantsChange() and applied in patchSpeed()
double myLeadingBlockerLength
double myLeftSpace
double myLookAheadSpeed
double myManeuverDist
The complete lateral distance the vehicle wants to travel to finish its maneuver Only used by sublane model, currently.
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
int myPreviousState
lane changing state from the previous simulation step
int myPreviousState2
lane changing state from step before the previous simulation step
std::map< int, std::pair< int, int > > mySavedStates
std::vector< MSLane * > myShadowFurtherLanes
std::vector< double > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
double mySpeedGainProbability
a value for tracking the probability that a change to the offset with the same sign is beneficial
double mySpeedLat
the current lateral speed
MSLane * myTargetLane
The target lane for the vehicle's current maneuver.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
user configurable model parameters (can be changed via TraCI)
double myStrategicParam
double myCooperativeParam
double mySpeedGainParam
double myKeepRightParam
double myLookaheadLeft
double mySpeedGainRight
const double myExperimentalParam1
derived parameters
double myChangeProbThresholdRight
double myChangeProbThresholdLeft
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCEndedOutput
static bool myLCOutput
whether to record lane-changing
static bool myLCStartedOutput
Detailed Description
A lane change model developed by D. Krajzewicz, J. Erdmann et al. between 2004 and 2013.
Definition at line 54 of file MSLCM_LC2013.h.
Member Typedef Documentation
Info
typedef std::pair<double, int> MSLCM_LC2013::Info protected
information regarding save velocity (unused) and state flags of the ego vehicle
Definition at line 247 of file MSLCM_LC2013.h.
Member Enumeration Documentation
MyLCAEnum
enum MSLCM_LC2013::MyLCAEnum
Enumerator
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_CHANGE_TO_HELP
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 57 of file MSLCM_LC2013.h.
Constructor & Destructor Documentation
MSLCM_LC2013()
MSLCM_LC2013::MSLCM_LC2013 (MSVehicle & v)
Definition at line 100 of file MSLCM_LC2013.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), initDerivedParameters(), myCooperativeParam, myKeepRightParam, mySpeedGainParam, myStrategicParam, MSAbstractLaneChangeModel::myVehicle, and SIMTIME.
~MSLCM_LC2013()
MSLCM_LC2013::~MSLCM_LC2013 () virtual
Definition at line 128 of file MSLCM_LC2013.cpp.
References changed().
Member Function Documentation
_patchSpeed()
double MSLCM_LC2013::_patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel)
helper function which contains the actual logic
Definition at line 219 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, changed(), DEBUG_COND, MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, MSEdge::hasLaneChanger(), LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_COOPERATIVE, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, MAX2(), MIN2(), myCooperativeParam, myDontBrake, myLCAccelerationAdvices, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, SIMTIME, MSCFModel::stopSpeed(), and toString().
Referenced by patchSpeed().
_wantsChange()
int MSLCM_LC2013::_wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected
helper function for doing the actual work
we urgently need to change lanes to follow our route
Definition at line 1050 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, adaptSpeedToPedestrians(), addLCSpeedAdvice(), amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::cancelRequest(), MSVehicle::Influencer::changeRequestRemainingSeconds(), MSVehicle::congested(), currentDistAllows(), currentDistDisallows(), DEBUG_COND, MSCFModel::followSpeed(), MSVehicle::getActionStepLengthSecs(), MSLane::getBruttoOccupancy(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSLane::getOppositePos(), MSEdge::getPersons(), MSVehicle::getPositionOnLane(), getRoundaboutAheadInfo(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSCFModel::getSpeedAfterMaxDecel(), MSLane::getSpeedLimit(), MSVehicleType::getVehicleClass(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, MSVehicle::influenceChangeDecision(), informFollower(), informLeader(), MSEdge::isInternal(), MSAbstractLaneChangeModel::isOpposite(), JAM_FACTOR, KEEP_RIGHT_ACCEPTANCE, KEEP_RIGHT_TIME, MSVehicle::LaneQ::lane, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_LEFT, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_AHEAD_MIN_SPEED, LOOK_AHEAD_SPEED_MEMORY, LOOK_FORWARD, MAX2(), MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeed(), MIN2(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbThresholdLeft, myChangeProbThresholdRight, myCooperativeParam, myKeepRightParam, myKeepRightProbability, myLCAccelerationAdvices, myLeadingBlockerLength, myLeftSpace, myLookaheadLeft, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, myStrategicParam, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSVehicle::LaneQ::occupation, RELGAIN_NORMALIZATION_MIN_SPEED, roundaboutDistBonus(), saveBlockerLength(), SIMTIME, slowDownForBlocked(), STEPS2TIME, SUMO_const_haltingSpeed, SVC_EMERGENCY, toString(), TS, TURN_LANE_DIST, and URGENCY.
Referenced by wantsChange().
adaptSpeedToPedestrians()
void MSLCM_LC2013::adaptSpeedToPedestrians (const MSLane * lane, double & v) protected
react to pedestrians on the given lane
Definition at line 2025 of file MSLCM_LC2013.cpp.
References DEBUG_COND, MSVehicle::getCarFollowModel(), Named::getID(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSPModel::getModel(), MSVehicle::getPositionOnLane(), MSVehicle::getRightSideOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MIN2(), MSAbstractLaneChangeModel::myVehicle, MSPModel::nextBlocking(), SIMTIME, and MSCFModel::stopSpeed().
Referenced by _wantsChange().
addLCSpeedAdvice()
void MSLCM_LC2013::addLCSpeedAdvice (const double vSafe) protected
Takes a vSafe (speed advice for speed in the next simulation step), converts it into an acceleration and stores it into myLCAccelerationAdvices.
Note
This construction was introduced to deal with action step lengths, where operation on the speed in the next sim step had to be replaced by acceleration throughout the next action step.
Definition at line 2048 of file MSLCM_LC2013.cpp.
References MSVehicle::getSpeed(), myLCAccelerationAdvices, MSAbstractLaneChangeModel::myVehicle, and SPEED2ACCEL.
Referenced by _wantsChange(), currentDistAllows(), inform(), informFollower(), informLeader(), and slowDownForBlocked().
alreadyChanged()
bool MSAbstractLaneChangeModel::alreadyChanged () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 399 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyChanged.
Referenced by MSLaneChanger::change().
amBlockingFollower()
bool MSLCM_LC2013::amBlockingFollower () inline protected
Definition at line 220 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
amBlockingFollowerNB()
bool MSLCM_LC2013::amBlockingFollowerNB () inline protected
Definition at line 223 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
amBlockingFollowerPlusNB()
bool MSLCM_LC2013::amBlockingFollowerPlusNB () inline protected
Definition at line 226 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by _wantsChange().
amBlockingLeader()
bool MSLCM_LC2013::amBlockingLeader () inline protected
Definition at line 217 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
build()
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 74 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::sameDirection().
cancelRequest()
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 347 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by _wantsChange(), and MSLCM_SL2015::_wantsChangeSublane().
changed()
void MSLCM_LC2013::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 1033 of file MSLCM_LC2013.cpp.
References MSVehicle::getBestLaneOffset(), LOOK_AHEAD_MIN_SPEED, myDontBrake, myKeepRightProbability, myLCAccelerationAdvices, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, and MSAbstractLaneChangeModel::myVehicle.
Referenced by _patchSpeed(), and ~MSLCM_LC2013().
changedToOpposite()
void MSAbstractLaneChangeModel::changedToOpposite () inherited
called when a vehicle changes between lanes in opposite directions
Definition at line 580 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myAlreadyChanged, and MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
checkTraCICommands()
void MSAbstractLaneChangeModel::checkTraCICommands () inherited
Check for commands issued for the vehicle via TraCI and apply the appropriate state changes For the sublane case, this includes setting a new maneuver distance if appropriate.
Definition at line 534 of file MSAbstractLaneChangeModel.cpp.
References DEBUG_COND, gDebugFlag2, MSBaseVehicle::getID(), MSVehicle::getInfluencer(), MSVehicle::getLaneChangeModel(), MSVehicle::Influencer::getLatDist(), MSAbstractLaneChangeModel::getOwnState(), MSGlobals::gLateralResolution, MSVehicle::hasInfluencer(), MSVehicle::influenceChangeDecision(), MSVehicle::lateralDistanceToLane(), LCA_LEFT, LCA_RIGHT, LCA_STAY, LCA_TRACI, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSVehicle::Influencer::resetLatDist(), MSAbstractLaneChangeModel::setManeuverDist(), MSAbstractLaneChangeModel::setOwnState(), SIMTIME, and toString().
Referenced by MSLaneChanger::checkTraCICommands(), and MSAbstractLaneChangeModel::setParameter().
cleanupShadowLane()
void MSAbstractLaneChangeModel::cleanupShadowLane () inherited
Definition at line 306 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
cleanupTargetLane()
void MSAbstractLaneChangeModel::cleanupTargetLane () inherited
Definition at line 325 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::myFurtherTargetLanes, MSAbstractLaneChangeModel::myTargetLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetManeuverReservation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
computeSpeedLat()
virtual double MSAbstractLaneChangeModel::computeSpeedLat (double latDist, double & maneuverDist) inline virtual inherited
decides the next lateral speed depending on the remaining lane change distance to be covered and updates maneuverDist according to lateral safety constraints.
Reimplemented in MSLCM_SL2015.
Definition at line 487 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::continueChangeSublane().
congested()
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 162 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
currentDistAllows()
bool MSLCM_LC2013::currentDistAllows (double dist, int laneOffset, double lookForwardDist) inline protected
Definition at line 232 of file MSLCM_LC2013.h.
References addLCSpeedAdvice().
Referenced by _wantsChange().
currentDistDisallows()
bool MSLCM_LC2013::currentDistDisallows (double dist, int laneOffset, double lookForwardDist) inline protected
Definition at line 229 of file MSLCM_LC2013.h.
Referenced by _wantsChange().
debugVehicle()
bool MSLCM_LC2013::debugVehicle () const virtual
whether the current vehicles shall be debugged
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 141 of file MSLCM_LC2013.cpp.
References DEBUG_COND.
Referenced by getRoundaboutAheadInfo().
decideDirection()
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual inherited
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 287 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::changed(), MSAbstractLaneChangeModel::inform(), MSAbstractLaneChangeModel::myModel, MSAbstractLaneChangeModel::patchSpeed(), toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
determineTargetLane()
MSLane * MSAbstractLaneChangeModel::determineTargetLane (int & targetDir) const inherited
Definition at line 472 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSBaseVehicle::getWidth(), MSLane::getWidth(), MSAbstractLaneChangeModel::myManeuverDist, MSAbstractLaneChangeModel::myShadowLane, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateTargetLane().
distanceAlongNextRoundabout()
double MSLCM_LC2013::distanceAlongNextRoundabout (double position, const MSLane * initialLane, const std::vector< MSLane *> & continuationLanes) static protected
compute the distance on the next upcoming roundabout along a given sequence of lanes.
Parameters
[in] position position of the vehicle on the initial lane
[in] initialLane starting lane for the computation (may be internal)
[in] continuationLanes sequence of lanes along which the roundabout distance is to be computed (only containing non-internal lanes)
Returns
distance along next upcoming roundabout on the given sequence of lanes continuationLanes
Definition at line 1839 of file MSLCM_LC2013.cpp.
References MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLink::getInternalLengthsAfter(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::isInternal(), and MSEdge::isRoundabout().
Referenced by getRoundaboutAheadInfo().
endLaneChangeManeuver()
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE) inherited
Definition at line 263 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::cleanupTargetLane(), MSVehicle::fixPosition(), MSAbstractLaneChangeModel::myAmOpposite, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::processLaneAdvances(), MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateShadowLane().
getAngleOffset()
double MSAbstractLaneChangeModel::getAngleOffset () const inherited
return the angle offset during a continuous change maneuver
Definition at line 504 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::pastMidpoint(), and STEPS2TIME.
Referenced by MSAbstractLaneChangeModel::getLaneChangeDirection().
getCommittedSpeed()
double MSAbstractLaneChangeModel::getCommittedSpeed () const inline inherited
Definition at line 472 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myCommittedSpeed.
Referenced by MSVehicle::planMoveInternal(), and MSLaneChangerSublane::startChangeSublane().
getFurtherTargetLanes()
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getFurtherTargetLanes () const inline inherited
Definition at line 365 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myFurtherTargetLanes.
Referenced by MSVehicle::getBackPositionOnLane(), and MSVehicle::getLatOffset().
getLaneChangeDirection()
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 388 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::myLaneChangeDirection.
Referenced by MSLaneChanger::continueChange().
getLastLaneChangeOffset()
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 369 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
getManeuverDist()
double MSAbstractLaneChangeModel::getManeuverDist () const inherited
Returns the remaining unblocked distance for the current maneuver. (only used by sublane model)
Definition at line 156 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myManeuverDist.
Referenced by MSLaneChangerSublane::change(), MSLaneChangerSublane::continueChangeSublane(), MSVehicle::getLatOffset(), GUIVehicle::getManeuverDist(), MSAbstractLaneChangeModel::getPrevState(), MSLeaderInfo::getSubLanes(), MSLaneChangerSublane::startChangeSublane(), and MSLCM_SL2015::updateGaps().
getOwnState()
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 170 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::applyTraCICommands(), MSLaneChanger::change(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), MSLCM_SL2015::saveBlockerLength(), saveBlockerLength(), MSVehicle::setBlinkerInformation(), and MSLaneChangerSublane::startChangeSublane().
getParameter()
std::string MSLCM_LC2013::getParameter (const std::string & key) const virtual
try to retrieve the given parameter from this device. Throw exception for unsupported key
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 2055 of file MSLCM_LC2013.cpp.
References LCA_KEEPRIGHT, myCooperativeParam, myKeepRightParam, myLookaheadLeft, MSAbstractLaneChangeModel::myModel, mySpeedGainParam, mySpeedGainRight, myStrategicParam, SUMO_ATTR_LCA_COOPERATIVE_PARAM, SUMO_ATTR_LCA_LOOKAHEADLEFT, SUMO_ATTR_LCA_SPEEDGAIN_PARAM, SUMO_ATTR_LCA_SPEEDGAINRIGHT, SUMO_ATTR_LCA_STRATEGIC_PARAM, and toString().
getPrevState()
int MSAbstractLaneChangeModel::getPrevState () const inline inherited
at the time of this call myPreviousState already holds the new value
Definition at line 174 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getManeuverDist(), MSAbstractLaneChangeModel::myPreviousState2, MSAbstractLaneChangeModel::setManeuverDist(), MSAbstractLaneChangeModel::setOwnState(), and MSAbstractLaneChangeModel::updateSafeLatDist().
Referenced by MSLaneChangerSublane::outputLCStarted().
getRoundaboutAheadInfo()
void MSLCM_LC2013::getRoundaboutAheadInfo (const MSLCM_LC2013 * lcm, const MSVehicle::LaneQ & curr, const MSVehicle::LaneQ & neigh, double & roundaboutDistanceAhead, double & roundaboutDistanceAheadNeigh, int & roundaboutEdgesAhead, int & roundaboutEdgesAheadNeigh) static protected
computes the distance and number of edges in the next upcoming roundabout along the lane continuations given in curr and neigh
Parameters
[in] veh The considered ego Vehicle
[in] curr continuation info along veh's current lane
[in] neigh continuation info along a neighboring lane (in MSLCM_2013::_wantsChange() the considered lane for a lanechange)
[out] roundaboutDistanceAhead Accumulated length of lanes in the next oncoming roundabout in curr
[out] roundaboutDistanceAheadNeigh Accumulated length of lanes in the next oncoming roundabout in neigh
[out] roundaboutEdgesAhead Number of lanes in the next oncoming roundabout in curr
[out] roundaboutEdgesAheadNeigh Number of lanes in the next oncoming roundabout in neigh
Definition at line 1738 of file MSLCM_LC2013.cpp.
References MSVehicle::LaneQ::bestContinuations, debugVehicle(), distanceAlongNextRoundabout(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLink::getInternalLengthsAfter(), MSVehicle::getLane(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSEdge::isInternal(), MSAbstractLaneChangeModel::isOpposite(), MSEdge::isRoundabout(), MSVehicle::LaneQ::lane, and MSAbstractLaneChangeModel::myVehicle.
Referenced by _wantsChange().
getSavedState()
const std::pair<int, int>& MSAbstractLaneChangeModel::getSavedState (const int dir) const inline inherited
Definition at line 189 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySavedStates.
Referenced by libsumo::Vehicle::getLaneChangeState().
getShadowDirection()
int MSAbstractLaneChangeModel::getShadowDirection () const inherited
return the direction in which the current shadow lane lies
Definition at line 408 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, and MSAbstractLaneChangeModel::pastMidpoint().
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSVehicle::processLinkAproaches(), and GUIVehicle::selectBlockingFoes().
getShadowFurtherLanes()
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline inherited
Definition at line 350 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
getShadowFurtherLanesPosLat()
const std::vector<double>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline inherited
Definition at line 354 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
getShadowLane() [1/3]
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicle's shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 335 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::isFrontOnLane(), MSLane::isInsertionSuccess(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and MSAbstractLaneChangeModel::updateShadowLane().
getShadowLane() [2/3]
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const inherited
return the shadow lane for the given lane
Definition at line 300 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::myVehicle.
getShadowLane() [3/3]
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane, double posLat) const inherited
return the shadow lane for the given lane and lateral offset
Definition at line 278 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, and SIMTIME.
getSpeedLat()
double MSAbstractLaneChangeModel::getSpeedLat () const inline inherited
return the lateral speed of the current lane change maneuver
Definition at line 477 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySpeedLat.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::continueChange(), GUIVehicle::getParameterWindow(), and MSLeaderInfo::getSubLanes().
getTargetLane()
MSLane* MSAbstractLaneChangeModel::getTargetLane () const inline inherited
Returns the lane the vehicle has committed to enter during a sublane lane change.
Returns
The vehicle's target lane.
Definition at line 361 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myTargetLane.
Referenced by GUIVehicle::getParameterWindow(), and MSLaneChangerSublane::startChangeSublane().
haveLCOutput()
static bool MSAbstractLaneChangeModel::haveLCOutput () inline static inherited
whether lanechange-output is active
Definition at line 147 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLCOutput.
Referenced by MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), and MSLaneChangerSublane::outputLCStarted().
inform()
void * MSLCM_LC2013::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 406 of file MSLCM_LC2013.cpp.
References addLCSpeedAdvice(), DEBUG_COND, MSBaseVehicle::getID(), MSGlobals::gSemiImplicitEulerUpdate, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, SIMTIME, and UNUSED_PARAMETER.
informFollower()
void MSLCM_LC2013::informFollower (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, int dir, const std::pair< MSVehicle *, double > & neighFollow, double remainingSeconds, double plannedSpeed) protected
decide whether we will try cut in before the follower or allow to be overtaken
Definition at line 616 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, addLCSpeedAdvice(), MSVehicle::congested(), CUT_IN_LEFT_SPEED_THRESHOLD, DEBUG_COND, MSCFModel::followSpeed(), MSCFModel::gapExtrapolation(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSVehicle::getLane(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSVehicle::getMaxSpeedOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSVehicle::getWaitingSeconds(), MSGlobals::gSemiImplicitEulerUpdate, HELP_DECEL_FACTOR, HELP_OVERTAKE, MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSLane::isAccelLane(), LCA_AMBLOCKINGFOLLOWER, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT_IMPATIENCE, MAX2(), MAX_ONRAMP_LENGTH, MIN2(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myExperimentalParam1, myLCAccelerationAdvices, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, overtakeDistance(), POSITION_EPS, SIMTIME, SPEED2ACCEL, SPEED2DIST, and TS.
Referenced by _wantsChange().
informLeader()
double MSLCM_LC2013::informLeader (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, int dir, const std::pair< MSVehicle *, double > & neighLead, double remainingSeconds) protected
Definition at line 440 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, addLCSpeedAdvice(), MSCFModel::brakeGap(), MSVehicle::congested(), DEBUG_COND, MSCFModel::followSpeed(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSGlobals::gSemiImplicitEulerUpdate, HELP_OVERTAKE, MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), MSAbstractLaneChangeModel::isOpposite(), MSVehicle::isStopped(), LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_LEADER, LCA_MLEFT, MAX2(), MIN2(), MIN_FALLBEHIND, MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myLCAccelerationAdvices, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myVehicle, overtakeDistance(), SIMTIME, SPEED2DIST, and MSCFModel::stopSpeed().
Referenced by _wantsChange().
initDerivedParameters()
void MSLCM_LC2013::initDerivedParameters ()
init cached parameters derived directly from model parameters
Definition at line 134 of file MSLCM_LC2013.cpp.
References MAX2(), myChangeProbThresholdLeft, myChangeProbThresholdRight, mySpeedGainParam, mySpeedGainRight, and NUMERICAL_EPS.
Referenced by MSLCM_LC2013(), and setParameter().
initGlobalOptions()
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 65 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myLCEndedOutput, MSAbstractLaneChangeModel::myLCOutput, and MSAbstractLaneChangeModel::myLCStartedOutput.
Referenced by MSAbstractLaneChangeModel::StateAndDist::sameDirection(), and MSFrame::setMSGlobals().
initLastLaneChangeOffset()
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 354 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSAbstractLaneChangeModel::primaryLaneChanged().
isChangingLanes()
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 383 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
isOpposite()
bool MSAbstractLaneChangeModel::isOpposite () const inline inherited
Definition at line 468 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAmOpposite.
Referenced by _wantsChange(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtInsertion(), MSLink::getLeaderInfo(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), getRoundaboutAheadInfo(), informLeader(), and MSVehicle::planMoveInternal().
laneChangeOutput()
void MSAbstractLaneChangeModel::laneChangeOutput (const std::string & tag, MSLane * source, MSLane * target, int direction) inherited
called once the vehicle ends a lane change manoeuvre (non-instant)
Definition at line 225 of file MSAbstractLaneChangeModel.cpp.
References OutputDevice::closeTag(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gLateralResolution, LCA_LEFT, LCA_RIGHT, MSAbstractLaneChangeModel::myLastFollowerGap, MSAbstractLaneChangeModel::myLastFollowerSecureGap, MSAbstractLaneChangeModel::myLastLateralGapLeft, MSAbstractLaneChangeModel::myLastLateralGapRight, MSAbstractLaneChangeModel::myLastLeaderGap, MSAbstractLaneChangeModel::myLastLeaderSecureGap, MSAbstractLaneChangeModel::myLastOrigLeaderGap, MSAbstractLaneChangeModel::myLastOrigLeaderSecureGap, MSAbstractLaneChangeModel::myLCOutput, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::NO_NEIGHBOR, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_POSITION, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, SUMO_ATTR_TYPE, time2string(), toString(), MSVehicle::updateDriveItems(), and OutputDevice::writeAttr().
Referenced by MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), MSAbstractLaneChangeModel::primaryLaneChanged(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
outputLCEnded()
static bool MSAbstractLaneChangeModel::outputLCEnded () inline static inherited
whether start of maneuvers shall be recorede
Definition at line 157 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::MSAbstractLaneChangeModel(), MSAbstractLaneChangeModel::myLCEndedOutput, and MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel().
Referenced by MSLaneChangerSublane::outputLCEnded().
outputLCStarted()
static bool MSAbstractLaneChangeModel::outputLCStarted () inline static inherited
whether start of maneuvers shall be recorede
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLCStartedOutput.
Referenced by MSLaneChangerSublane::outputLCStarted().
overtakeDistance()
double MSLCM_LC2013::overtakeDistance (const MSVehicle * follower, const MSVehicle * leader, const double gap, double followerSpeed = INVALID_SPEED, double leaderSpeed = INVALID_SPEED) static protected
Definition at line 427 of file MSLCM_LC2013.cpp.
References MSVehicle::getCarFollowModel(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), INVALID_SPEED, and MAX2().
Referenced by informFollower(), and informLeader().
pastMidpoint()
bool MSAbstractLaneChangeModel::pastMidpoint () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 375 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::remainingTime().
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::updateCompletion().
patchSpeed()
double MSLCM_LC2013::patchSpeed (const double min, const double wanted, const double max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change. It uses information on LC-related desired speed-changes from the call to wantsChange() at the end of the previous simulation step.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 186 of file MSLCM_LC2013.cpp.
References _patchSpeed(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MAX2(), MSAbstractLaneChangeModel::myVehicle, SIMTIME, and toString().
predInteraction()
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, double > & leader) protected virtual inherited
Definition at line 182 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
prepareStep()
void MSLCM_LC2013::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 1018 of file MSLCM_LC2013.cpp.
References LCA_STRATEGIC, LCA_WANTS_LANECHANGE, myDontBrake, myKeepRightProbability, myLCAccelerationAdvices, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, and MSAbstractLaneChangeModel::prepareStep().
primaryLaneChanged()
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction) inherited
called once when the vehicles primary lane changes
Definition at line 214 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), MSAbstractLaneChangeModel::initLastLaneChangeOffset(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myVehicle, and MSMoveReminder::NOTIFICATION_LANE_CHANGE.
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
remainingTime()
SUMOTime MSAbstractLaneChangeModel::remainingTime () const inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 511 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSAbstractLaneChangeModel::pastMidpoint().
removeShadowApproachingInformation()
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const inherited
Definition at line 523 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and MSAbstractLaneChangeModel::sublaneChangeCompleted().
resetChanged()
void MSAbstractLaneChangeModel::resetChanged () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 404 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::cleanupTargetLane(), MSAbstractLaneChangeModel::determineTargetLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSAbstractLaneChangeModel::updateCompletion(), MSAbstractLaneChangeModel::updateShadowLane(), and MSAbstractLaneChangeModel::updateTargetLane().
Referenced by MSVehicle::planMove().
roundaboutDistBonus()
double MSLCM_LC2013::roundaboutDistBonus (double roundaboutDistAhead, int roundaboutEdgesAhead) const protected
Computes the artificial bonus distance for roundabout lanes this additional distance reduces the sense of urgency within roundabouts and thereby promotes the use of the inner roundabout lane in multi-lane roundabouts.
Parameters
[in] roundaboutDistAhead Distance on roundabout
[in] roundaboutEdgesAhead number of edges on roundabout
Definition at line 1810 of file MSLCM_LC2013.cpp.
References MSGlobals::gSemiImplicitEulerUpdate, myCooperativeParam, ROUNDABOUT_DIST_BONUS, ROUNDABOUT_DIST_FACTOR, and ROUNDABOUT_DIST_TRESH.
Referenced by _wantsChange().
saveBlockerLength() [1/2]
void MSLCM_LC2013::saveBlockerLength (MSVehicle * blocker, int lcaCounter) protected
save space for vehicles which need to counter-lane-change
Definition at line 1979 of file MSLCM_LC2013.cpp.
References MSCFModel::brakeGap(), DEBUG_COND, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::saveBlockerLength(), SIMTIME, and toString().
Referenced by _wantsChange().
saveBlockerLength() [2/2]
void MSLCM_LC2013::saveBlockerLength (double length) inline protected virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 213 of file MSLCM_LC2013.h.
References MAX2(), and myLeadingBlockerLength.
saveState()
void MSAbstractLaneChangeModel::saveState (const int dir, const int stateWithoutTraCI, const int state) inline inherited
Definition at line 193 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySavedStates, MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), and MSAbstractLaneChangeModel::prepareStep().
setFollowerGaps() [1/2]
void MSAbstractLaneChangeModel::setFollowerGaps (CLeaderDist follower, double secGap) inherited
Definition at line 586 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastFollowerGap, and MSAbstractLaneChangeModel::myLastFollowerSecureGap.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and MSAbstractLaneChangeModel::saveState().
setFollowerGaps() [2/2]
void MSAbstractLaneChangeModel::setFollowerGaps (const MSLeaderDistanceInfo & vehicles) inherited
Definition at line 610 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::myLastFollowerGap, MSAbstractLaneChangeModel::myLastFollowerSecureGap, and MSAbstractLaneChangeModel::myVehicle.
setLeaderGaps() [1/2]
void MSAbstractLaneChangeModel::setLeaderGaps (CLeaderDist leader, double secGap) inherited
Definition at line 594 of file MSAbstractLaneChangeModel.cpp.
References MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::myLastLeaderGap, MSAbstractLaneChangeModel::myLastLeaderSecureGap, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and MSAbstractLaneChangeModel::saveState().
setLeaderGaps() [2/2]
void MSAbstractLaneChangeModel::setLeaderGaps (const MSLeaderDistanceInfo & vehicles) inherited
Definition at line 629 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::myLastLeaderGap, MSAbstractLaneChangeModel::myLastLeaderSecureGap, and MSAbstractLaneChangeModel::myVehicle.
setManeuverDist()
void MSAbstractLaneChangeModel::setManeuverDist (const double dist) inherited
Updates the remaining distance for the current maneuver while it is continued within non-action steps (only used by sublane model)
Definition at line 142 of file MSAbstractLaneChangeModel.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSAbstractLaneChangeModel::myManeuverDist, MSAbstractLaneChangeModel::myVehicle, and SIMTIME.
Referenced by MSLaneChangerSublane::abortLCManeuver(), MSLaneChangerSublane::change(), MSAbstractLaneChangeModel::checkTraCICommands(), MSAbstractLaneChangeModel::getPrevState(), and MSLaneChangerSublane::startChangeSublane().
setNoShadowPartialOccupator()
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 448 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, and MSAbstractLaneChangeModel::primaryLaneChanged().
Referenced by MSVehicle::enterLaneAtLaneChange().
setOrigLeaderGaps() [1/2]
void MSAbstractLaneChangeModel::setOrigLeaderGaps (CLeaderDist leader, double secGap) inherited
Definition at line 602 of file MSAbstractLaneChangeModel.cpp.
References MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::myLastOrigLeaderGap, MSAbstractLaneChangeModel::myLastOrigLeaderSecureGap, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and MSAbstractLaneChangeModel::saveState().
setOrigLeaderGaps() [2/2]
void MSAbstractLaneChangeModel::setOrigLeaderGaps (const MSLeaderDistanceInfo & vehicles) inherited
Definition at line 648 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::myLastOrigLeaderGap, MSAbstractLaneChangeModel::myLastOrigLeaderSecureGap, and MSAbstractLaneChangeModel::myVehicle.
setOwnState()
void MSAbstractLaneChangeModel::setOwnState (const int state) virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 129 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myPreviousState, and MSAbstractLaneChangeModel::myPreviousState2.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSAbstractLaneChangeModel::checkTraCICommands(), MSAbstractLaneChangeModel::getPrevState(), and MSLCM_SL2015::setOwnState().
setParameter()
void MSLCM_LC2013::setParameter (const std::string & key, const std::string & value) virtual
try to set the given parameter for this laneChangeModel. Throw exception for unsupported key
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 2074 of file MSLCM_LC2013.cpp.
References TplConvert::_2double(), initDerivedParameters(), LCA_KEEPRIGHT, myCooperativeParam, myKeepRightParam, myLookaheadLeft, MSAbstractLaneChangeModel::myModel, mySpeedGainParam, mySpeedGainRight, myStrategicParam, SUMO_ATTR_LCA_COOPERATIVE_PARAM, SUMO_ATTR_LCA_LOOKAHEADLEFT, SUMO_ATTR_LCA_SPEEDGAIN_PARAM, SUMO_ATTR_LCA_SPEEDGAINRIGHT, SUMO_ATTR_LCA_STRATEGIC_PARAM, and toString().
setShadowApproachingInformation()
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const inherited
set approach information for the shadow vehicle
Definition at line 517 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSAbstractLaneChangeModel::sublaneChangeCompleted().
setShadowLane()
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline inherited
set the shadow lane
Definition at line 346 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
setShadowPartialOccupator()
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 444 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow.
setSpeedLat()
void MSAbstractLaneChangeModel::setSpeedLat (double speedLat) inline inherited
Definition at line 481 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::mySpeedLat.
Referenced by MSLaneChangerSublane::abortLCManeuver(), and MSLaneChangerSublane::startChangeSublane().
slowDownForBlocked()
int MSLCM_LC2013::slowDownForBlocked (MSVehicle ** blocked, int state) protected
compute useful slowdowns for blocked vehicles
Definition at line 1923 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, addLCSpeedAdvice(), DEBUG_COND, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, MSAbstractLaneChangeModel::myCarFollowModel, myLCAccelerationAdvices, MSAbstractLaneChangeModel::myVehicle, POSITION_EPS, SIMTIME, and SUMO_const_haltingSpeed.
Referenced by _wantsChange().
startLaneChangeManeuver()
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 195 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::mySpeedLat, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::primaryLaneChanged(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::applyTraCICommands(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeToNewLane(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChanger::startChange().
sublaneChangeCompleted()
virtual bool MSAbstractLaneChangeModel::sublaneChangeCompleted (const double latDist) const inline virtual inherited
whether the current change completes the manoeuvre
Definition at line 459 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, MSAbstractLaneChangeModel::removeShadowApproachingInformation(), MSAbstractLaneChangeModel::setShadowApproachingInformation(), toString(), and UNUSED_PARAMETER.
unchanged()
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 324 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
updateCompletion()
bool MSAbstractLaneChangeModel::updateCompletion () inherited
Definition at line 255 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::pastMidpoint().
Referenced by MSLaneChanger::continueChange(), and MSAbstractLaneChangeModel::resetChanged().
updateExpectedSublaneSpeeds()
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderDistanceInfo & ahead, int sublaneOffset, int laneIndex) inline virtual inherited
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 279 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
updateSafeLatDist()
void MSAbstractLaneChangeModel::updateSafeLatDist (const double travelledLatDist) virtual inherited
Updates the value of safe lateral distances (in SL2015) during maneuver continuation in non-action steps.
Reimplemented in MSLCM_SL2015.
Definition at line 136 of file MSAbstractLaneChangeModel.cpp.
References UNUSED_PARAMETER.
Referenced by MSAbstractLaneChangeModel::getPrevState(), and MSLaneChangerSublane::startChangeSublane().
updateShadowLane()
void MSAbstractLaneChangeModel::updateShadowLane () inherited
Definition at line 363 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSLinkContHelper::getConnectingLink(), MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
updateTargetLane()
void MSAbstractLaneChangeModel::updateTargetLane () inherited
Definition at line 425 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::debugVehicle(), MSAbstractLaneChangeModel::determineTargetLane(), MSVehicle::getFurtherLanes(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::myFurtherTargetLanes, MSAbstractLaneChangeModel::myTargetLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetManeuverReservation(), MSLane::setManeuverReservation(), SIMTIME, and toString().
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
wantsChange()
int MSLCM_LC2013::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, double > & leader, const std::pair< MSVehicle *, double > & neighLead, const std::pair< MSVehicle *, double > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
TODO: better documentation, refs #2
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 147 of file MSLCM_LC2013.cpp.
References _wantsChange(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), gPrecision, MSAbstractLaneChangeModel::myVehicle, SIMTIME, and toString().
wantsChangeSublane()
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, LaneChangeAction alternatives, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, double & latDist, double & targetDistLat, int & blocked) inline virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 246 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
Field Documentation
myAllowOvertakingRight
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 609 of file MSAbstractLaneChangeModel.h.
Referenced by _wantsChange(), MSLCM_SL2015::checkStrategicChange(), informFollower(), MSLCM_SL2015::informFollower(), informLeader(), MSLCM_SL2015::informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
myAlreadyChanged
bool MSAbstractLaneChangeModel::myAlreadyChanged protected inherited
whether the vehicle has already moved this step
Definition at line 550 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyChanged(), MSAbstractLaneChangeModel::changedToOpposite(), and MSAbstractLaneChangeModel::resetChanged().
myCarFollowModel
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 578 of file MSAbstractLaneChangeModel.h.
Referenced by _wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_DK2008::informBlocker(), informFollower(), informLeader(), MSLCM_SL2015::informLeader(), MSAbstractLaneChangeModel::predInteraction(), slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
myChangeProbThresholdLeft
double MSLCM_LC2013::myChangeProbThresholdLeft protected
Definition at line 288 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), and initDerivedParameters().
myChangeProbThresholdRight
double MSLCM_LC2013::myChangeProbThresholdRight protected
Definition at line 287 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), and initDerivedParameters().
myCommittedSpeed
double MSAbstractLaneChangeModel::myCommittedSpeed protected inherited
the speed when committing to a change maneuver
Definition at line 537 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::commitManoeuvre(), MSAbstractLaneChangeModel::getCommittedSpeed(), and MSAbstractLaneChangeModel::prepareStep().
myCooperativeParam
double MSLCM_LC2013::myCooperativeParam protected
Definition at line 272 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), getParameter(), MSLCM_LC2013(), roundaboutDistBonus(), and setParameter().
myDontBrake
bool MSLCM_LC2013::myDontBrake protected
Definition at line 267 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), changed(), and prepareStep().
myExperimentalParam1
const double MSLCM_LC2013::myExperimentalParam1 protected
Definition at line 281 of file MSLCM_LC2013.h.
Referenced by informFollower().
myFurtherTargetLanes
std::vector<MSLane*> MSAbstractLaneChangeModel::myFurtherTargetLanes protected inherited
Definition at line 575 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupTargetLane(), MSAbstractLaneChangeModel::getFurtherTargetLanes(), and MSAbstractLaneChangeModel::updateTargetLane().
myKeepRightParam
double MSLCM_LC2013::myKeepRightParam protected
Definition at line 274 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), getParameter(), MSLCM_LC2013(), and setParameter().
myKeepRightProbability
double MSLCM_LC2013::myKeepRightProbability protected
Definition at line 254 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), changed(), and prepareStep().
myLaneChangeCompletion
double MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 540 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::pastMidpoint(), MSAbstractLaneChangeModel::remainingTime(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::updateCompletion().
myLaneChangeDirection
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 543 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
myLastFollowerGap
double MSAbstractLaneChangeModel::myLastFollowerGap protected inherited
Definition at line 596 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSAbstractLaneChangeModel::setFollowerGaps().
myLastFollowerSecureGap
double MSAbstractLaneChangeModel::myLastFollowerSecureGap protected inherited
Definition at line 599 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSAbstractLaneChangeModel::setFollowerGaps().
myLastLateralGapLeft
double MSAbstractLaneChangeModel::myLastLateralGapLeft protected inherited
the minimum lateral gaps to other vehicles that were found when last changing to the left and right
Definition at line 591 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSLCM_SL2015::updateGaps().
myLastLateralGapRight
double MSAbstractLaneChangeModel::myLastLateralGapRight protected inherited
Definition at line 592 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSLCM_SL2015::updateGaps().
myLastLeaderGap
double MSAbstractLaneChangeModel::myLastLeaderGap protected inherited
the actual minimum longitudinal distances to vehicles on the target lane
Definition at line 595 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSAbstractLaneChangeModel::setLeaderGaps().
myLastLeaderSecureGap
double MSAbstractLaneChangeModel::myLastLeaderSecureGap protected inherited
the minimum longitudinal distances to vehicles on the target lane that would be necessary for stringent security
Definition at line 598 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSAbstractLaneChangeModel::setLeaderGaps().
myLastOrigLeaderGap
double MSAbstractLaneChangeModel::myLastOrigLeaderGap protected inherited
acutal and secure distance to closest leader vehicle on the original when performing lane change
Definition at line 601 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
myLastOrigLeaderSecureGap
double MSAbstractLaneChangeModel::myLastOrigLeaderSecureGap protected inherited
Definition at line 602 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::laneChangeOutput(), MSAbstractLaneChangeModel::prepareStep(), and MSAbstractLaneChangeModel::setOrigLeaderGaps().
myLCAccelerationAdvices
std::vector<double> MSLCM_LC2013::myLCAccelerationAdvices protected
vector of LC-related acceleration recommendations Filled in wantsChange() and applied in patchSpeed()
Definition at line 265 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), addLCSpeedAdvice(), changed(), informFollower(), informLeader(), prepareStep(), and slowDownForBlocked().
myLCEndedOutput
bool MSAbstractLaneChangeModel::myLCEndedOutput static protected inherited
Definition at line 614 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::outputLCEnded().
myLCOutput
bool MSAbstractLaneChangeModel::myLCOutput static protected inherited
whether to record lane-changing
Definition at line 612 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::haveLCOutput(), MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::laneChangeOutput().
myLCStartedOutput
bool MSAbstractLaneChangeModel::myLCStartedOutput static protected inherited
Definition at line 613 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::outputLCStarted().
myLeadingBlockerLength
double MSLCM_LC2013::myLeadingBlockerLength protected
Definition at line 256 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), informLeader(), prepareStep(), and saveBlockerLength().
myLeftSpace
double MSLCM_LC2013::myLeftSpace protected
Definition at line 257 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), informFollower(), informLeader(), prepareStep(), and saveBlockerLength().
myLookaheadLeft
double MSLCM_LC2013::myLookaheadLeft protected
Definition at line 277 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), getParameter(), and setParameter().
myLookAheadSpeed
double MSLCM_LC2013::myLookAheadSpeed protected
Definition at line 261 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), changed(), and informLeader().
myManeuverDist
double MSAbstractLaneChangeModel::myManeuverDist protected inherited
The complete lateral distance the vehicle wants to travel to finish its maneuver Only used by sublane model, currently.
Definition at line 547 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSAbstractLaneChangeModel::determineTargetLane(), MSAbstractLaneChangeModel::getManeuverDist(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::setManeuverDist(), MSLCM_SL2015::setOwnState(), and MSLCM_SL2015::wantsChange().
myModel
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected inherited
the type of this model
Definition at line 581 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::computeSpeedLat(), MSAbstractLaneChangeModel::decideDirection(), getParameter(), MSLCM_SL2015::getParameter(), MSAbstractLaneChangeModel::getParameter(), setParameter(), MSLCM_SL2015::setParameter(), MSAbstractLaneChangeModel::setParameter(), MSAbstractLaneChangeModel::sublaneChangeCompleted(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::wantsChange(), and MSAbstractLaneChangeModel::wantsChangeSublane().
myNoPartiallyOccupatedByShadow
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected inherited
Definition at line 588 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
myOwnState
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 525 of file MSAbstractLaneChangeModel.h.
Referenced by _patchSpeed(), MSLCM_SL2015::_patchSpeed(), _wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), amBlockingLeader(), MSLCM_DK2008::changed(), changed(), MSLCM_SL2015::changed(), MSAbstractLaneChangeModel::checkTraCICommands(), MSAbstractLaneChangeModel::getOwnState(), MSLCM_DK2008::inform(), inform(), MSLCM_SL2015::inform(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), prepareStep(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
myPartiallyOccupatedByShadow
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected inherited
list of lanes where the shadow vehicle is partial occupator
Definition at line 584 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::setShadowPartialOccupator().
myPreviousState
int MSAbstractLaneChangeModel::myPreviousState protected inherited
lane changing state from the previous simulation step
Definition at line 527 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), and MSAbstractLaneChangeModel::setOwnState().
myPreviousState2
int MSAbstractLaneChangeModel::myPreviousState2 protected inherited
lane changing state from step before the previous simulation step
Definition at line 529 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getPrevState(), and MSAbstractLaneChangeModel::setOwnState().
mySavedStates
std::map<int, std::pair<int, int> > MSAbstractLaneChangeModel::mySavedStates protected inherited
Definition at line 531 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getSavedState(), and MSAbstractLaneChangeModel::saveState().
myShadowFurtherLanes
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected inherited
Definition at line 556 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
myShadowFurtherLanesPosLat
std::vector<double> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected inherited
Definition at line 557 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), and MSAbstractLaneChangeModel::updateShadowLane().
myShadowLane
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 553 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::determineTargetLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::setShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
mySpeedGainParam
double MSLCM_LC2013::mySpeedGainParam protected
Definition at line 273 of file MSLCM_LC2013.h.
Referenced by getParameter(), initDerivedParameters(), MSLCM_LC2013(), and setParameter().
mySpeedGainProbability
double MSLCM_LC2013::mySpeedGainProbability protected
a value for tracking the probability that a change to the offset with the same sign is beneficial
Definition at line 250 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), changed(), and prepareStep().
mySpeedGainRight
double MSLCM_LC2013::mySpeedGainRight protected
Definition at line 279 of file MSLCM_LC2013.h.
Referenced by getParameter(), initDerivedParameters(), and setParameter().
mySpeedLat
double MSAbstractLaneChangeModel::mySpeedLat protected inherited
the current lateral speed
Definition at line 534 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_SL2015::computeSpeedLat(), MSAbstractLaneChangeModel::getSpeedLat(), MSAbstractLaneChangeModel::setSpeedLat(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSLCM_SL2015::wantsChangeSublane().
myStrategicParam
double MSLCM_LC2013::myStrategicParam protected
Definition at line 271 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), getParameter(), MSLCM_LC2013(), and setParameter().
myTargetLane
MSLane* MSAbstractLaneChangeModel::myTargetLane protected inherited
The target lane for the vehicle's current maneuver.
Note
This is used by the sublane model to register the vehicle at lanes, it will reach within the current action step, so vehicles on that lane may react to the started lc-maneuver during the car-following process. If the shadow lane is the same as the lc maneuver target, myTargetLane is set to nullptr. The current shadow lanes and further lanes should always be updated before updating the target lane.
Definition at line 567 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupTargetLane(), MSAbstractLaneChangeModel::getTargetLane(), and MSAbstractLaneChangeModel::updateTargetLane().
myVehicle
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 522 of file MSAbstractLaneChangeModel.h.
Referenced by _patchSpeed(), MSLCM_SL2015::_patchSpeed(), _wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptSpeedToPedestrians(), MSLCM_SL2015::addLCSpeedAdvice(), addLCSpeedAdvice(), MSAbstractLaneChangeModel::cancelRequest(), changed(), MSLCM_SL2015::changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::checkTraCICommands(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::cleanupTargetLane(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::commitManoeuvre(), MSLCM_SL2015::computeSpeedGain(), MSLCM_SL2015::computeSpeedLat(), MSAbstractLaneChangeModel::congested(), MSLCM_SL2015::decideDirection(), MSAbstractLaneChangeModel::determineTargetLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), getRoundaboutAheadInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSLCM_SL2015::getSublaneWidth(), MSLCM_SL2015::getWidth(), inform(), MSLCM_SL2015::inform(), MSLCM_DK2008::informBlocker(), informFollower(), MSLCM_SL2015::informFollower(), informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLCM_SL2015::msg(), MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), patchSpeed(), MSLCM_SL2015::patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), MSLCM_SL2015::saveBlockerLength(), saveBlockerLength(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setManeuverDist(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSLCM_SL2015::setOwnState(), slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSAbstractLaneChangeModel::updateTargetLane(), wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
NO_NEIGHBOR
const double MSAbstractLaneChangeModel::NO_NEIGHBOR static inherited
Definition at line 509 of file MSAbstractLaneChangeModel.h.
Referenced by MSLaneChanger::checkChange(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), and MSAbstractLaneChangeModel::prepareStep().
The documentation for this class was generated from the following files:
MSLCM_LC2013.h
MSLCM_LC2013.cpp