SUMO - Simulation of Urban MObility: AGActivityTripWriter Class Reference
AGActivityTripWriter Class Reference
#include <AGActivityTripWriter.h>
Public Member Functions
void addTrip (const AGTrip &trip)
AGActivityTripWriter (OutputDevice &file)
Private Member Functions
AGActivityTripWriter (const AGActivityTripWriter &)
Invalidated copy constructor.
AGActivityTripWriter & operator= (const AGActivityTripWriter &)
Invalidated assignment operator.
Private Attributes
OutputDevice & myTripOutput
Detailed Description
Definition at line 47 of file AGActivityTripWriter.h.
Constructor & Destructor Documentation
AGActivityTripWriter() [1/2]
AGActivityTripWriter::AGActivityTripWriter (OutputDevice & file)
Definition at line 44 of file AGActivityTripWriter.cpp.
References RGBColor::BLUE, OutputDevice::closeTag(), RGBColor::GREEN, OutputDevice::lf(), myTripOutput, OutputDevice::openTag(), RGBColor::RED, SUMO_ATTR_COLOR, SUMO_ATTR_ID, SUMO_ATTR_VCLASS, SUMO_TAG_VTYPE, and OutputDevice::writeAttr().
AGActivityTripWriter() [2/2]
AGActivityTripWriter::AGActivityTripWriter (const AGActivityTripWriter &) private
Invalidated copy constructor.
Member Function Documentation
addTrip()
void AGActivityTripWriter::addTrip (const AGTrip & trip)
Definition at line 62 of file AGActivityTripWriter.cpp.
References OutputDevice::closeTag(), AGTrip::getArr(), AGTrip::getDay(), AGTrip::getDep(), Named::getID(), AGTrip::getPassed(), AGPosition::getPosition(), AGPosition::getStreet(), AGTrip::getTime(), AGTrip::getType(), AGTrip::getVehicleName(), myTripOutput, OutputDevice::openTag(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_DEPART, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_TO, SUMO_ATTR_TYPE, SUMO_ATTR_VIA, SUMO_TAG_TRIP, and OutputDevice::writeAttr().
Referenced by AGActivityGen::generateOutputFile().
operator=()
AGActivityTripWriter& AGActivityTripWriter::operator= (const AGActivityTripWriter &) private
Invalidated assignment operator.
Field Documentation
myTripOutput
OutputDevice& AGActivityTripWriter::myTripOutput private
Definition at line 54 of file AGActivityTripWriter.h.
Referenced by addTrip(), and AGActivityTripWriter().
The documentation for this class was generated from the following files:
AGActivityTripWriter.h
AGActivityTripWriter.cpp