SUMO - Simulation of Urban MObility: GNECalibratorRouteDialog Class Reference
GNECalibratorRouteDialog Class Reference
Dialog for edit Calibrator Routes.
#include <GNECalibratorRouteDialog.h>
Public Member Functions
GNECalibratorRouteDialog (GNECalibratorRoute *editedCalibratorRoute, bool updatingElement)
FOX-declaration.
~GNECalibratorRouteDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdSetVariable (FXObject *, FXSelector, void *)
event after change value
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNECalibratorRouteDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
void updateCalibratorRouteValues ()
update data fields
Protected Attributes
bool myCalibratorRouteValid
flag to check if current calibrator vehicleType is valid
FXVerticalFrame * myContentFrame
frame for contents
GNECalibratorRoute * myEditedCalibratorRoute
pointer to modified rerouter interval
SumoXMLAttr myInvalidAttr
current sumo attribute invalid
FXTextField * myTextFieldColor
color of route
FXTextField * myTextFieldEdges
list of edges (string)
FXTextField * myTextFieldRouteID
route ID
bool myUpdatingElement
flag to indicate if flow are being created or modified
Private Member Functions
GNECalibratorRouteDialog (const GNECalibratorRouteDialog &)=delete
Invalidated copy constructor.
GNECalibratorRouteDialog & operator= (const GNECalibratorRouteDialog &)=delete
Invalidated assignment operator.
Detailed Description
Dialog for edit Calibrator Routes.
Definition at line 49 of file GNECalibratorRouteDialog.h.
Constructor & Destructor Documentation
GNECalibratorRouteDialog() [1/3]
GNECalibratorRouteDialog::GNECalibratorRouteDialog (GNECalibratorRoute * editedCalibratorRoute, bool updatingElement)
FOX-declaration.
constructor
Definition at line 61 of file GNECalibratorRouteDialog.cpp.
References GUIDesignAuxiliarFrame, GUIDesignLabelLeftThick, GUIDesignTextField, GUIDesignTextFieldNCol, GUIDesignUniformHorizontalFrame, MID_GNE_CALIBRATORDIALOG_SET_VARIABLE, SUMO_ATTR_COLOR, SUMO_ATTR_EDGES, SUMO_ATTR_ID, and toString().
~GNECalibratorRouteDialog()
GNECalibratorRouteDialog::~GNECalibratorRouteDialog ()
destructor
Definition at line 103 of file GNECalibratorRouteDialog.cpp.
GNECalibratorRouteDialog() [2/3]
GNECalibratorRouteDialog::GNECalibratorRouteDialog () inline protected
FOX needs this.
Definition at line 77 of file GNECalibratorRouteDialog.h.
GNECalibratorRouteDialog() [3/3]
GNECalibratorRouteDialog::GNECalibratorRouteDialog (const GNECalibratorRouteDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), GNECalibratorVehicleTypeDialog::onCmdAccept(), onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNECalibratorDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), GNECalibratorVehicleTypeDialog::onCmdCancel(), onCmdCancel(), GNERerouterDialog::onCmdCancel(), GNECalibratorDialog::onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNECalibratorRouteDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 107 of file GNECalibratorRouteDialog.cpp.
References GNEAdditionalDialog::acceptChanges(), GNECalibratorRoute::getCalibratorParent(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), myCalibratorRouteValid, myEditedCalibratorRoute, myInvalidAttr, myUpdatingElement, toString(), and WRITE_WARNING.
onCmdCancel()
long GNECalibratorRouteDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 139 of file GNECalibratorRouteDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdReset()
long GNECalibratorRouteDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 149 of file GNECalibratorRouteDialog.cpp.
References GNEAdditionalDialog::resetChanges(), and updateCalibratorRouteValues().
onCmdSetVariable()
long GNECalibratorRouteDialog::onCmdSetVariable (FXObject * , FXSelector , void *)
event after change value
Definition at line 159 of file GNECalibratorRouteDialog.cpp.
References GNECalibratorRoute::getCalibratorParent(), GNEAttributeCarrier::getID(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), GNECalibratorRoute::isValid(), myCalibratorRouteValid, myEditedCalibratorRoute, myInvalidAttr, myTextFieldColor, myTextFieldEdges, myTextFieldRouteID, GNECalibratorRoute::setAttribute(), SUMO_ATTR_COLOR, SUMO_ATTR_EDGES, SUMO_ATTR_ID, and SUMO_ATTR_NOTHING.
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNECalibratorRouteDialog& GNECalibratorRouteDialog::operator= (const GNECalibratorRouteDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), GNECalibratorVehicleTypeDialog::onCmdReset(), onCmdReset(), GNERerouterDialog::onCmdReset(), GNECalibratorDialog::onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
updateCalibratorRouteValues()
void GNECalibratorRouteDialog::updateCalibratorRouteValues () protected
update data fields
Definition at line 202 of file GNECalibratorRouteDialog.cpp.
References GNECalibratorRoute::getAttribute(), GNEAttributeCarrier::getID(), myEditedCalibratorRoute, myTextFieldColor, myTextFieldEdges, myTextFieldRouteID, SUMO_ATTR_COLOR, and SUMO_ATTR_EDGES.
Referenced by onCmdReset().
Field Documentation
myCalibratorRouteValid
bool GNECalibratorRouteDialog::myCalibratorRouteValid protected
flag to check if current calibrator vehicleType is valid
Definition at line 86 of file GNECalibratorRouteDialog.h.
Referenced by onCmdAccept(), and onCmdSetVariable().
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myEditedCalibratorRoute
GNECalibratorRoute* GNECalibratorRouteDialog::myEditedCalibratorRoute protected
pointer to modified rerouter interval
Definition at line 80 of file GNECalibratorRouteDialog.h.
Referenced by onCmdAccept(), onCmdSetVariable(), and updateCalibratorRouteValues().
myInvalidAttr
SumoXMLAttr GNECalibratorRouteDialog::myInvalidAttr protected
current sumo attribute invalid
Definition at line 89 of file GNECalibratorRouteDialog.h.
Referenced by onCmdAccept(), and onCmdSetVariable().
myTextFieldColor
FXTextField* GNECalibratorRouteDialog::myTextFieldColor protected
color of route
Definition at line 98 of file GNECalibratorRouteDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorRouteValues().
myTextFieldEdges
FXTextField* GNECalibratorRouteDialog::myTextFieldEdges protected
list of edges (string)
Definition at line 95 of file GNECalibratorRouteDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorRouteValues().
myTextFieldRouteID
FXTextField* GNECalibratorRouteDialog::myTextFieldRouteID protected
route ID
Definition at line 92 of file GNECalibratorRouteDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorRouteValues().
myUpdatingElement
bool GNECalibratorRouteDialog::myUpdatingElement protected
flag to indicate if flow are being created or modified
Definition at line 83 of file GNECalibratorRouteDialog.h.
Referenced by onCmdAccept().
The documentation for this class was generated from the following files:
GNECalibratorRouteDialog.h
GNECalibratorRouteDialog.cpp