SUMO - Simulation of Urban MObility: MELoop Class Reference
MELoop Class Reference
The main mesocopic simulation loop.
#include <MELoop.h>
Public Member Functions
void addLeaderCar (MEVehicle *veh, MSLink *link)
Adds the given car to the leading vehicles.
void buildSegmentsFor (const MSEdge &e, const OptionsCont &oc)
Build the segments for a given edge.
bool changeSegment (MEVehicle *veh, SUMOTime leaveTime, MESegment *const toSegment, const bool ignoreLink=false)
change to the next segment this handles combinations of the following cases: (ending / continuing route) and (leaving segment / finishing teleport)
MESegment * getSegmentForEdge (const MSEdge &e, double pos=0)
Get the segment for a given edge at a given position.
MELoop (const SUMOTime recheckInterval)
SUMO constructor.
void removeLeaderCar (MEVehicle *v)
Removes the given car from the leading vehicles.
void simulate (SUMOTime tMax)
Perform simulation up to the given time.
~MELoop ()
Static Public Member Functions
static int numSegmentsFor (const double length, const double slength)
Compute number of segments per edge (best value stay close to the configured segment length)
static void setApproaching (MEVehicle *veh, MSLink *link)
registers vehicle with the given link
Private Member Functions
void checkCar (MEVehicle *veh)
Check whether the vehicle may move.
MELoop (const MELoop &)
Invalidated copy constructor.
MESegment * nextSegment (MESegment *s, MEVehicle *v)
Retrieve next segment.
MELoop & operator= (const MELoop &)
Invalidated assignment operator.
void teleportVehicle (MEVehicle *veh, MESegment *const toSegment)
teleports a vehicle or continues a teleport
Private Attributes
std::vector< MESegment * > myEdges2FirstSegments
mapping from internal edge ids to their initial segments
const SUMOTime myFullRecheckInterval
the interval at which to recheck at full segments (<=0 means asap)
std::map< SUMOTime, std::vector< MEVehicle * > > myLeaderCars
leader cars in the segments sorted by exit time
const SUMOTime myLinkRecheckInterval
the interval at which to recheck at blocked junctions (<=0 means asap)
Detailed Description
The main mesocopic simulation loop.
Definition at line 55 of file MELoop.h.
Constructor & Destructor Documentation
MELoop() [1/2]
MELoop::MELoop (const SUMOTime recheckInterval)
SUMO constructor.
Definition at line 54 of file MELoop.cpp.
~MELoop()
MELoop::~MELoop ()
Definition at line 57 of file MELoop.cpp.
References MESegment::getNextSegment(), and myEdges2FirstSegments.
MELoop() [2/2]
MELoop::MELoop (const MELoop &) private
Invalidated copy constructor.
Member Function Documentation
addLeaderCar()
void MELoop::addLeaderCar (MEVehicle * veh, MSLink * link)
Adds the given car to the leading vehicles.
Parameters
[in] veh the car which became a leading one
[in] link the link on which the car shall register its approach
Definition at line 204 of file MELoop.cpp.
References MEVehicle::getEventTime(), myLeaderCars, and setApproaching().
Referenced by checkCar(), MESegment::loadState(), MEVehicle::loadState(), MESegment::receive(), MESegment::send(), MESegment::setSpeedForQueue(), and teleportVehicle().
buildSegmentsFor()
void MELoop::buildSegmentsFor (const MSEdge & e, const OptionsCont & oc)
Build the segments for a given edge.
Parameters
[in] e the edge to build for
Definition at line 261 of file MELoop.cpp.
References OptionsCont::getBool(), OptionsCont::getFloat(), Named::getID(), MSEdge::getLanes(), MSEdge::getLength(), MSEdge::getNumericalID(), OptionsCont::getString(), myEdges2FirstSegments, nextSegment(), numSegmentsFor(), string2time(), and toString().
Referenced by MSEdge::closeBuilding().
changeSegment()
bool MELoop::changeSegment (MEVehicle * veh, SUMOTime leaveTime, MESegment *const toSegment, const bool ignoreLink = false)
change to the next segment this handles combinations of the following cases: (ending / continuing route) and (leaving segment / finishing teleport)
Definition at line 87 of file MELoop.cpp.
References MSBaseVehicle::getEdge(), MESegment::getEdge(), Named::getID(), MSBaseVehicle::getID(), MESegment::getIndex(), MSNet::getInstance(), MSEdge::getNumericalID(), MEVehicle::getSegment(), MSNet::getVehicleControl(), MESegment::hasSpaceFor(), MESegment::isInvalid(), MEVehicle::mayProceed(), myEdges2FirstSegments, MESegment::receive(), MSVehicleControl::scheduleVehicleRemoval(), MESegment::send(), MEVehicle::setSegment(), time2string(), toString(), and WRITE_WARNING.
Referenced by checkCar(), teleportVehicle(), and MESegment::vaporizeAnyCar().
checkCar()
void MELoop::checkCar (MEVehicle * veh) private
Check whether the vehicle may move.
This method is called when the vehicle reaches its event time and checks whether it may proceed to the next segment.
Parameters
[in] veh The vehicle to check
Definition at line 118 of file MELoop.cpp.
References addLeaderCar(), changeSegment(), MEVehicle::getBlockTime(), MESegment::getEntryBlockTime(), MEVehicle::getEventTime(), MESegment::getEventTime(), MESegment::getLink(), MEVehicle::getSegment(), MEVehicle::getWaitingTime(), MSGlobals::gTimeToGridlock, MESegment::hasSpaceFor(), MEVehicle::isStopped(), MAX2(), MAX3(), MEVehicle::mayProceed(), MIN2(), myFullRecheckInterval, myLinkRecheckInterval, nextSegment(), MEVehicle::setBlockTime(), MEVehicle::setEventTime(), SUMOTime_MAX, and teleportVehicle().
Referenced by simulate().
getSegmentForEdge()
MESegment * MELoop::getSegmentForEdge (const MSEdge & e, double pos = 0)
Get the segment for a given edge at a given position.
Parameters
[in] e the edge to get the segment for
[in] pos the position to get the segment for
Returns
The relevant segment
Definition at line 289 of file MELoop.cpp.
References MESegment::getLength(), MESegment::getNextSegment(), MSEdge::getNumericalID(), and myEdges2FirstSegments.
Referenced by MEVehicle::addStop(), METriggeredCalibrator::execute(), GUIEdge::getSegmentAtPosition(), MSMeanData::init(), MSEdge::insertVehicle(), MESegment::limitedControlOverride(), MEVehicle::loadState(), MSRouteProbe::MSRouteProbe(), MSTriggeredRerouter::MSTriggeredRerouter(), MSStateHandler::myStartElement(), MSLaneSpeedTrigger::processCommand(), MSMeanData::resetOnly(), teleportVehicle(), MSXMLRawOut::writeEdge(), and MSMeanData::writeEdge().
nextSegment()
MESegment * MELoop::nextSegment (MESegment * s, MEVehicle * v) private
Retrieve next segment.
If the segment is not the last on the current edge, its successor is returned. Otherwise, the first segment of the edge at which the vehicle continues his journey is returned.
Parameters
[in] s The segment the vehicle is currently at
[in] v The vehicle to get the next segment for
Returns
The vehicle's next segment
Todo:
Recheck the "quick and dirty" stuff (
See also
MESegment::saveState,
MESegment::loadState)
Definition at line 231 of file MELoop.cpp.
References MESegment::getNextSegment(), MSEdge::getNumericalID(), myEdges2FirstSegments, and MSBaseVehicle::succEdge().
Referenced by buildSegmentsFor(), and checkCar().
numSegmentsFor()
int MELoop::numSegmentsFor (const double length, const double slength) static
Compute number of segments per edge (best value stay close to the configured segment length)
Definition at line 250 of file MELoop.cpp.
Referenced by buildSegmentsFor(), and GUILane::splitAtSegments().
operator=()
MELoop& MELoop::operator= (const MELoop &) private
Invalidated assignment operator.
removeLeaderCar()
void MELoop::removeLeaderCar (MEVehicle * v)
Removes the given car from the leading vehicles.
Parameters
[in] v the car which was a leading one
Definition at line 224 of file MELoop.cpp.
References MEVehicle::getEventTime(), and myLeaderCars.
Referenced by MESegment::receive(), MESegment::setSpeedForQueue(), and MESegment::vaporizeAnyCar().
setApproaching()
void MELoop::setApproaching (MEVehicle * veh, MSLink * link) static
registers vehicle with the given link
Parameters
[in] veh the car to register
[in] link the link on which the car shall register its approach
Definition at line 211 of file MELoop.cpp.
References MEVehicle::getEventTime(), MESegment::getLength(), MEVehicle::getSegment(), MEVehicle::getSpeed(), MSLink::getState(), MEVehicle::getWaitingTime(), LINKSTATE_ALLWAY_STOP, RandHelper::rand(), and MSLink::setApproaching().
Referenced by addLeaderCar(), and MEVehicle::replaceRoute().
simulate()
void MELoop::simulate (SUMOTime tMax)
Perform simulation up to the given time.
Checks all vehicles with an event time less or equal than the given time.
Parameters
[in] tMax the end time for the sim step
Definition at line 69 of file MELoop.cpp.
References checkCar(), DELTA_T, and myLeaderCars.
Referenced by MSNet::simulationStep().
teleportVehicle()
void MELoop::teleportVehicle (MEVehicle * veh, MESegment *const toSegment) private
teleports a vehicle or continues a teleport
Parameters
[in] veh The vehicle to teleport
[in] toSegment The first segment where the vehicle may reenter the network
Definition at line 152 of file MELoop.cpp.
References MSBaseVehicle::activateReminders(), addLeaderCar(), changeSegment(), MSBaseVehicle::getEdge(), MESegment::getEdge(), MEVehicle::getEventTime(), Named::getID(), MSBaseVehicle::getID(), MESegment::getIndex(), MSNet::getInstance(), MSEdge::getLength(), MESegment::getNextSegment(), MEVehicle::getSegment(), getSegmentForEdge(), MSEdge::getSpeedLimit(), MSNet::getVehicleControl(), MESegment::hasSpaceFor(), MEVehicle::moveRoutePointer(), MSMoveReminder::NOTIFICATION_JUNCTION, MSVehicleControl::registerTeleportJam(), MESegment::send(), MESegment::setEntryBlockTime(), MEVehicle::setEventTime(), MEVehicle::setSegment(), TIME2STEPS, time2string(), toString(), and WRITE_WARNING.
Referenced by checkCar().
Field Documentation
myEdges2FirstSegments
std::vector<MESegment*> MELoop::myEdges2FirstSegments private
mapping from internal edge ids to their initial segments
Definition at line 149 of file MELoop.h.
Referenced by buildSegmentsFor(), changeSegment(), getSegmentForEdge(), nextSegment(), and ~MELoop().
myFullRecheckInterval
const SUMOTime MELoop::myFullRecheckInterval private
the interval at which to recheck at full segments (<=0 means asap)
Definition at line 152 of file MELoop.h.
Referenced by checkCar().
myLeaderCars
std::map<SUMOTime, std::vector<MEVehicle*> > MELoop::myLeaderCars private
leader cars in the segments sorted by exit time
Definition at line 146 of file MELoop.h.
Referenced by addLeaderCar(), removeLeaderCar(), and simulate().
myLinkRecheckInterval
const SUMOTime MELoop::myLinkRecheckInterval private
the interval at which to recheck at blocked junctions (<=0 means asap)
Definition at line 155 of file MELoop.h.
Referenced by checkCar().
The documentation for this class was generated from the following files:
MELoop.h
MELoop.cpp