SUMO - Simulation of Urban MObility: TraCIServerAPI_Route Class Reference
TraCIServerAPI_Route Class Reference
APIs for getting/setting route values via TraCI.
#include <TraCIServerAPI_Route.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa6: Get Route Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc6: Change Route State)
Private Member Functions
TraCIServerAPI_Route & operator= (const TraCIServerAPI_Route &s)
invalidated assignment operator
TraCIServerAPI_Route (const TraCIServerAPI_Route &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting route values via TraCI.
Definition at line 46 of file TraCIServerAPI_Route.h.
Constructor & Destructor Documentation
TraCIServerAPI_Route()
TraCIServerAPI_Route::TraCIServerAPI_Route (const TraCIServerAPI_Route & s) private
invalidated copy constructor
Member Function Documentation
operator=()
TraCIServerAPI_Route& TraCIServerAPI_Route::operator= (const TraCIServerAPI_Route & s) private
invalidated assignment operator
processGet()
bool TraCIServerAPI_Route::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa6: Get Route Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 46 of file TraCIServerAPI_Route.cpp.
References CMD_GET_ROUTE_VARIABLE, libsumo::Route::getEdges(), libsumo::Route::getIDCount(), libsumo::Route::getIDList(), libsumo::Route::getParameter(), ID_COUNT, ID_LIST, tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_ROUTE_VARIABLE, RTYPE_OK, toHex(), TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, VAR_EDGES, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
processSet()
bool TraCIServerAPI_Route::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xc6: Change Route State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 98 of file TraCIServerAPI_Route.cpp.
References libsumo::Route::add(), ADD, CMD_SET_ROUTE_VARIABLE, tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), TraCIServer::readTypeCheckingStringList(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, libsumo::Route::setParameter(), toHex(), TYPE_COMPOUND, VAR_PARAMETER, TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_Route.h
TraCIServerAPI_Route.cpp