SUMO - Simulation of Urban MObility: glfontstash.h File Reference
glfontstash.h File Reference
Functions
FONScontext * glfonsCreate (int width, int height, int flags)
void glfonsDelete (FONScontext *ctx)
unsigned int glfonsRGBA (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
Function Documentation
glfonsCreate()
FONScontext* glfonsCreate (int width, int height, int flags)
Referenced by GLHelper::initFont().
glfonsDelete()
void glfonsDelete (FONScontext * ctx)
Referenced by GLHelper::resetFont().
glfonsRGBA()
unsigned int glfonsRGBA (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
Referenced by GLHelper::drawText().