SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::EdgesHandler Class Reference
NIImporter_DlrNavteq::EdgesHandler Class Reference
Importer of edges stored in unsplit elmar format.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
EdgesHandler (NBNodeCont &nc, NBEdgeCont &ec, NBTypeCont &tc, const std::string &file, std::map< std::string, PositionVector > &geoms, std::map< std::string, std::string > &streetNames)
Constructor.
bool report (const std::string &result)
Parsing method.
~EdgesHandler ()
Destructor.
Protected Types
enum ColumnName {
LINK_ID = 0, NODE_ID_FROM, NODE_ID_TO, BETWEEN_NODE_ID,
LENGTH, VEHICLE_TYPE, FORM_OF_WAY, BRUNNEL_TYPE,
FUNCTIONAL_ROAD_CLASS, SPEED_CATEGORY, NUMBER_OF_LANES, SPEED_LIMIT,
SPEED_RESTRICTION, NAME_ID1_REGIONAL, NAME_ID2_LOCAL, HOUSENUMBERS_RIGHT,
HOUSENUMBERS_LEFT, ZIP_CODE, AREA_ID, SUBAREA_ID,
THROUGH_TRAFFIC, SPECIAL_RESTRICTIONS, EXTENDED_NUMBER_OF_LANES, ISRAMP,
CONNECTION
}
Protected Member Functions
std::string getColumn (const StringTokenizer &st, ColumnName name, const std::string fallback="")
Protected Attributes
std::vector< int > myColumns
the version number of the edge file being parsed
NBEdgeCont & myEdgeCont
The edge container to store loaded edges into.
const std::string myFile
the file being parsed
std::map< std::string, PositionVector > & myGeoms
Previously read edge geometries (manipulated during use)
NBNodeCont & myNodeCont
The node container to get the referenced nodes from.
std::map< std::string, std::string > & myStreetNames
Previously read streat names (non-const because operate[] is more convenient)
bool myTryIgnoreNodePositions
Whether node positions shall not be added to the edge's geometry.
NBTypeCont & myTypeCont
The type container to retrieve type info from.
double myVersion
version number of current file
Static Protected Attributes
static const int MISSING_COLUMN = std::numeric_limits<int>::max()
Private Member Functions
EdgesHandler (const EdgesHandler &)
Invalidated copy constructor.
std::string getStreetNameFromIDs (const std::string &regionalID, const std::string &localID) const
build the street name for the given ids
EdgesHandler & operator= (const EdgesHandler &)
Invalidated assignment operator.
Detailed Description
Importer of edges stored in unsplit elmar format.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain edge definitions in DLRNavteq's unsplit format.
Definition at line 146 of file NIImporter_DlrNavteq.h.
Member Enumeration Documentation
ColumnName
enum NIImporter_DlrNavteq::EdgesHandler::ColumnName protected
Enumerator
LINK_ID
NODE_ID_FROM
NODE_ID_TO
BETWEEN_NODE_ID
LENGTH
VEHICLE_TYPE
FORM_OF_WAY
BRUNNEL_TYPE
FUNCTIONAL_ROAD_CLASS
SPEED_CATEGORY
NUMBER_OF_LANES
SPEED_LIMIT
SPEED_RESTRICTION
NAME_ID1_REGIONAL
NAME_ID2_LOCAL
HOUSENUMBERS_RIGHT
HOUSENUMBERS_LEFT
ZIP_CODE
AREA_ID
SUBAREA_ID
THROUGH_TRAFFIC
SPECIAL_RESTRICTIONS
EXTENDED_NUMBER_OF_LANES
ISRAMP
CONNECTION
Definition at line 209 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
EdgesHandler() [1/2]
NIImporter_DlrNavteq::EdgesHandler::EdgesHandler (NBNodeCont & nc, NBEdgeCont & ec, NBTypeCont & tc, const std::string & file, std::map< std::string, PositionVector > & geoms, std::map< std::string, std::string > & streetNames)
Constructor.
Parameters
[in] nc The node control to retrieve nodes from
Definition at line 256 of file NIImporter_DlrNavteq.cpp.
~EdgesHandler()
NIImporter_DlrNavteq::EdgesHandler::~EdgesHandler ()
Destructor.
Definition at line 270 of file NIImporter_DlrNavteq.cpp.
EdgesHandler() [2/2]
NIImporter_DlrNavteq::EdgesHandler::EdgesHandler (const EdgesHandler &) private
Invalidated copy constructor.
Member Function Documentation
getColumn()
std::string NIImporter_DlrNavteq::EdgesHandler::getColumn (const StringTokenizer & st, ColumnName name, const std::string fallback = "") protected
Definition at line 423 of file NIImporter_DlrNavteq.cpp.
References StringTokenizer::get(), MISSING_COLUMN, myColumns, StringTokenizer::size(), and toString().
Referenced by report().
getStreetNameFromIDs()
std::string NIImporter_DlrNavteq::EdgesHandler::getStreetNameFromIDs (const std::string & regionalID, const std::string & localID) const private
build the street name for the given ids
Definition at line 450 of file NIImporter_DlrNavteq.cpp.
References myStreetNames.
Referenced by report().
operator=()
EdgesHandler& NIImporter_DlrNavteq::EdgesHandler::operator= (const EdgesHandler &) private
Invalidated assignment operator.
report()
bool NIImporter_DlrNavteq::EdgesHandler::report (const std::string & result) virtual
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and stores it into "myEdgeCont".
Parameters
[in] result The read line
Returns
Whether the parsing shall continue
Exceptions
ProcessError if something fails
See also
LineHandler::report
Implements LineHandler.
Definition at line 274 of file NIImporter_DlrNavteq.cpp.
References TplConvert::_2int(), NINavTeqHelper::addVehicleClasses(), NINavTeqHelper::addVehicleClassesV6(), BETWEEN_NODE_ID, BRUNNEL_TYPE, CONNECTION, NBEdge::disallowVehicleClass(), EXTENDED_NUMBER_OF_LANES, FORM_OF_WAY, FUNCTIONAL_ROAD_CLASS, OptionsCont::getBool(), getColumn(), NINavTeqHelper::getLaneNumber(), OptionsCont::getOptions(), NBTypeCont::getPermissions(), NBEdge::getPermissions(), NBNode::getPosition(), NINavTeqHelper::getSpeed(), getStreetNameFromIDs(), NBEdgeCont::insert(), NBTypeCont::knows(), LANESPREAD_CENTER, LINK_ID, MISSING_COLUMN, myColumns, myEdgeCont, myFile, myGeoms, myNodeCont, myTypeCont, myVersion, NAME_ID1_REGIONAL, NAME_ID2_LOCAL, NODE_ID_FROM, NODE_ID_TO, NUMBER_OF_LANES, NIImporter_DlrNavteq::readVersion(), NBNodeCont::retrieve(), PositionVector::reverse(), NBEdge::setPermissions(), SPEED_CATEGORY, SPEED_RESTRICTION, SVC_PASSENGER, SVC_SHIP, SVCAll, NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, VEHICLE_TYPE, and StringTokenizer::WHITECHARS.
Field Documentation
MISSING_COLUMN
const int NIImporter_DlrNavteq::EdgesHandler::MISSING_COLUMN = std::numeric_limits<int>::max() static protected
Definition at line 207 of file NIImporter_DlrNavteq.h.
Referenced by getColumn(), and report().
myColumns
std::vector<int> NIImporter_DlrNavteq::EdgesHandler::myColumns protected
the version number of the edge file being parsed
Definition at line 202 of file NIImporter_DlrNavteq.h.
Referenced by getColumn(), and report().
myEdgeCont
NBEdgeCont& NIImporter_DlrNavteq::EdgesHandler::myEdgeCont protected
The edge container to store loaded edges into.
Definition at line 184 of file NIImporter_DlrNavteq.h.
Referenced by report().
myFile
const std::string NIImporter_DlrNavteq::EdgesHandler::myFile protected
the file being parsed
Definition at line 205 of file NIImporter_DlrNavteq.h.
Referenced by report().
myGeoms
std::map<std::string, PositionVector>& NIImporter_DlrNavteq::EdgesHandler::myGeoms protected
Previously read edge geometries (manipulated during use)
Definition at line 190 of file NIImporter_DlrNavteq.h.
Referenced by report().
myNodeCont
NBNodeCont& NIImporter_DlrNavteq::EdgesHandler::myNodeCont protected
The node container to get the referenced nodes from.
Definition at line 181 of file NIImporter_DlrNavteq.h.
Referenced by report().
myStreetNames
std::map<std::string, std::string>& NIImporter_DlrNavteq::EdgesHandler::myStreetNames protected
Previously read streat names (non-const because operate[] is more convenient)
Definition at line 193 of file NIImporter_DlrNavteq.h.
Referenced by getStreetNameFromIDs().
myTryIgnoreNodePositions
bool NIImporter_DlrNavteq::EdgesHandler::myTryIgnoreNodePositions protected
Whether node positions shall not be added to the edge's geometry.
Definition at line 196 of file NIImporter_DlrNavteq.h.
myTypeCont
NBTypeCont& NIImporter_DlrNavteq::EdgesHandler::myTypeCont protected
The type container to retrieve type info from.
Definition at line 187 of file NIImporter_DlrNavteq.h.
Referenced by report().
myVersion
double NIImporter_DlrNavteq::EdgesHandler::myVersion protected
version number of current file
Definition at line 199 of file NIImporter_DlrNavteq.h.
Referenced by report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp