SUMO - Simulation of Urban MObility: GUISelectedStorage::UpdateTarget Class Reference
GUISelectedStorage::UpdateTarget Class Reference abstract
#include <GUISelectedStorage.h>
Public Member Functions
virtual void selectionUpdated ()=0
called when selection is updated
virtual ~UpdateTarget ()
virtual destructor
Detailed Description
Definition at line 80 of file GUISelectedStorage.h.
Constructor & Destructor Documentation
~UpdateTarget()
virtual GUISelectedStorage::UpdateTarget::~UpdateTarget () inline virtual
virtual destructor
Definition at line 84 of file GUISelectedStorage.h.
References GUISelectedStorage::add2Update(), GUISelectedStorage::clear(), GUISelectedStorage::deselect(), GUISelectedStorage::getSelected(), GLO_MAX, GUISelectedStorage::GUISelectedStorage(), GUISelectedStorage::isSelected(), GUISelectedStorage::load(), GUISelectedStorage::loadIDs(), GUISelectedStorage::remove2Update(), GUISelectedStorage::save(), GUISelectedStorage::select(), selectionUpdated(), GUISelectedStorage::toggleSelection(), and GUISelectedStorage::~GUISelectedStorage().
Member Function Documentation
selectionUpdated()
virtual void GUISelectedStorage::UpdateTarget::selectionUpdated () pure virtual
called when selection is updated
Implemented in GNESelectorFrame, and GUIDialog_GLChosenEditor.
Referenced by GUISelectedStorage::clear(), GUISelectedStorage::deselect(), GUISelectedStorage::load(), GUISelectedStorage::select(), and ~UpdateTarget().
The documentation for this class was generated from the following file:
GUISelectedStorage.h