SUMO - Simulation of Urban MObility: LogitCalculator< R, E, V > Class Template Reference
LogitCalculator< R, E, V > Class Template Reference
Cost calculation with c-logit or logit method.
#include <LogitCalculator.h>
Public Member Functions
void calculateProbabilities (std::vector< R *> alternatives, const V *const veh, const SUMOTime time)
calculate the probabilities in the logit model
int getMaxRouteNumber () const
bool keepRoutes () const
LogitCalculator (const double beta, const double gamma, const double theta)
Constructor.
void setCosts (R *route, const double costs, const bool) const
bool skipRouteCalculation () const
virtual ~LogitCalculator ()
Destructor.
Static Public Member Functions
static void cleanup ()
static RouteCostCalculator< R, E, V > & getCalculator ()
Private Member Functions
double getBetaForCLogit (const std::vector< R *> alternatives) const
calculate the scaling factor in the logit model
double getThetaForCLogit (const std::vector< R *> alternatives) const
calculate the scaling factor in the logit model
LogitCalculator & operator= (const LogitCalculator &s)
invalidated assignment operator
Private Attributes
const double myBeta
logit beta - value
std::map< const R *, double > myCommonalities
The route commonality factors for c-logit.
const double myGamma
logit gamma - value
const double myTheta
logit theta - value
Detailed Description
template<class R, class E, class V>
class LogitCalculator< R, E, V >
Cost calculation with c-logit or logit method.
Definition at line 46 of file LogitCalculator.h.
Constructor & Destructor Documentation
LogitCalculator()
template<class R , class E , class V > LogitCalculator< R, E, V >::LogitCalculator (const double beta, const double gamma, const double theta) inline
Constructor.
Definition at line 49 of file LogitCalculator.h.
~LogitCalculator()
template<class R , class E , class V > virtual LogitCalculator< R, E, V >::~LogitCalculator () inline virtual
Destructor.
Definition at line 53 of file LogitCalculator.h.
Member Function Documentation
calculateProbabilities()
template<class R , class E , class V > void LogitCalculator< R, E, V >::calculateProbabilities (std::vector< R *> alternatives, const V *const veh, const SUMOTime time) inline virtual
calculate the probabilities in the logit model
Implements RouteCostCalculator< R, E, V >.
Definition at line 60 of file LogitCalculator.h.
References LogitCalculator< R, E, V >::getBetaForCLogit(), LogitCalculator< R, E, V >::getThetaForCLogit(), LogitCalculator< R, E, V >::myBeta, LogitCalculator< R, E, V >::myCommonalities, LogitCalculator< R, E, V >::myGamma, LogitCalculator< R, E, V >::myTheta, and STEPS2TIME.
cleanup()
template<class R, class E, class V> static void RouteCostCalculator< R, E, V >::cleanup () inline static inherited
Definition at line 54 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::calculateProbabilities(), RouteCostCalculator< R, E, V >::myInstance, and RouteCostCalculator< R, E, V >::setCosts().
Referenced by RONet::cleanup().
getBetaForCLogit()
template<class R , class E , class V > double LogitCalculator< R, E, V >::getBetaForCLogit (const std::vector< R *> alternatives) const inline private
calculate the scaling factor in the logit model
Definition at line 104 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
getCalculator()
template<class R , class E , class V > RouteCostCalculator< R, E, V > & RouteCostCalculator< R, E, V >::getCalculator () static inherited
Definition at line 114 of file RouteCostCalculator.h.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and RouteCostCalculator< R, E, V >::myInstance.
Referenced by RORouteDef::addAlternative(), and ROMAAssignments::sue().
getMaxRouteNumber()
template<class R, class E, class V> int RouteCostCalculator< R, E, V >::getMaxRouteNumber () const inline inherited
Definition at line 64 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myMaxRouteNumber.
getThetaForCLogit()
template<class R , class E , class V > double LogitCalculator< R, E, V >::getThetaForCLogit (const std::vector< R *> alternatives) const inline private
calculate the scaling factor in the logit model
Definition at line 116 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
keepRoutes()
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::keepRoutes () const inline inherited
Definition at line 68 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myKeepRoutes.
Referenced by RORouteDef::addAlternative().
operator=()
template<class R , class E , class V > LogitCalculator& LogitCalculator< R, E, V >::operator= (const LogitCalculator< R, E, V > & s) private
invalidated assignment operator
setCosts()
template<class R , class E , class V > void LogitCalculator< R, E, V >::setCosts (R * route, const double costs, const bool) const inline virtual
Implements RouteCostCalculator< R, E, V >.
Definition at line 55 of file LogitCalculator.h.
skipRouteCalculation()
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::skipRouteCalculation () const inline inherited
Definition at line 72 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::mySkipRouteCalculation.
Field Documentation
myBeta
template<class R , class E , class V > const double LogitCalculator< R, E, V >::myBeta private
logit beta - value
Definition at line 143 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
myCommonalities
template<class R , class E , class V > std::map<const R*, double> LogitCalculator< R, E, V >::myCommonalities private
The route commonality factors for c-logit.
Definition at line 152 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
myGamma
template<class R , class E , class V > const double LogitCalculator< R, E, V >::myGamma private
logit gamma - value
Definition at line 146 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
myTheta
template<class R , class E , class V > const double LogitCalculator< R, E, V >::myTheta private
logit theta - value
Definition at line 149 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
The documentation for this class was generated from the following file:
LogitCalculator.h