SUMO - Simulation of Urban MObility: NIVissimTrafficDescription Class Reference
NIVissimTrafficDescription Class Reference
#include <NIVissimTrafficDescription.h>
Public Member Functions
double meanSpeed () const
NIVissimTrafficDescription (const std::string &name, const NIVissimVehicleClassVector &vehicleTypes)
~NIVissimTrafficDescription ()
Static Public Member Functions
static void clearDict ()
static bool dictionary (int id, const std::string &name, const NIVissimVehicleClassVector &vehicleTypes)
static bool dictionary (int id, NIVissimTrafficDescription *o)
static NIVissimTrafficDescription * dictionary (int id)
static double meanSpeed (int id)
Private Types
typedef std::map< int, NIVissimTrafficDescription * > DictType
Private Attributes
std::string myName
NIVissimVehicleClassVector myVehicleTypes
Static Private Attributes
static DictType myDict
Detailed Description
Definition at line 43 of file NIVissimTrafficDescription.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimTrafficDescription*> NIVissimTrafficDescription::DictType private
Definition at line 59 of file NIVissimTrafficDescription.h.
Constructor & Destructor Documentation
NIVissimTrafficDescription()
NIVissimTrafficDescription::NIVissimTrafficDescription (const std::string & name, const NIVissimVehicleClassVector & vehicleTypes)
Definition at line 46 of file NIVissimTrafficDescription.cpp.
Referenced by dictionary().
~NIVissimTrafficDescription()
NIVissimTrafficDescription::~NIVissimTrafficDescription ()
Definition at line 52 of file NIVissimTrafficDescription.cpp.
References myVehicleTypes.
Member Function Documentation
clearDict()
void NIVissimTrafficDescription::clearDict () static
Definition at line 95 of file NIVissimTrafficDescription.cpp.
References myDict.
Referenced by NIImporter_Vissim::~NIImporter_Vissim().
dictionary() [1/3]
bool NIVissimTrafficDescription::dictionary (int id, const std::string & name, const NIVissimVehicleClassVector & vehicleTypes) static
Definition at line 61 of file NIVissimTrafficDescription.cpp.
References NIVissimTrafficDescription().
Referenced by meanSpeed(), and NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse().
dictionary() [2/3]
bool NIVissimTrafficDescription::dictionary (int id, NIVissimTrafficDescription * o) static
Definition at line 74 of file NIVissimTrafficDescription.cpp.
References myDict.
dictionary() [3/3]
NIVissimTrafficDescription * NIVissimTrafficDescription::dictionary (int id) static
Definition at line 85 of file NIVissimTrafficDescription.cpp.
References myDict.
meanSpeed() [1/2]
double NIVissimTrafficDescription::meanSpeed (int id) static
Definition at line 106 of file NIVissimTrafficDescription.cpp.
References dictionary(), and meanSpeed().
Referenced by meanSpeed().
meanSpeed() [2/2]
double NIVissimTrafficDescription::meanSpeed () const
Definition at line 114 of file NIVissimTrafficDescription.cpp.
References myVehicleTypes.
Field Documentation
myDict
NIVissimTrafficDescription::DictType NIVissimTrafficDescription::myDict static private
Definition at line 60 of file NIVissimTrafficDescription.h.
Referenced by clearDict(), and dictionary().
myName
std::string NIVissimTrafficDescription::myName private
Definition at line 56 of file NIVissimTrafficDescription.h.
myVehicleTypes
NIVissimVehicleClassVector NIVissimTrafficDescription::myVehicleTypes private
Definition at line 57 of file NIVissimTrafficDescription.h.
Referenced by meanSpeed(), and ~NIVissimTrafficDescription().
The documentation for this class was generated from the following files:
NIVissimTrafficDescription.h
NIVissimTrafficDescription.cpp