SUMO - Simulation of Urban MObility: FXWorkerThread::Task Class Reference
FXWorkerThread::Task Class Reference abstract
Abstract superclass of a task to be run with an index to keep track of pending tasks.
#include <FXWorkerThread.h>
Public Member Functions
virtual void run (FXWorkerThread *context)=0
Abstract method which in subclasses should contain the computations to be performed.
void setIndex (const int newIndex)
Sets the running index of this task.
virtual ~Task ()
Desctructor.
Private Attributes
int myIndex
the index of the task, valid only after the task has been added to the pool
Detailed Description
Abstract superclass of a task to be run with an index to keep track of pending tasks.
Definition at line 53 of file FXWorkerThread.h.
Constructor & Destructor Documentation
~Task()
virtual FXWorkerThread::Task::~Task () inline virtual
Desctructor.
Definition at line 56 of file FXWorkerThread.h.
References run().
Member Function Documentation
run()
virtual void FXWorkerThread::Task::run (FXWorkerThread * context) pure virtual
Abstract method which in subclasses should contain the computations to be performed.
If there is data to be shared among several tasks (but not among several threads) it can be put in the a thread class subclassing the FXWorkerThread. the instance of the thread is then made available via the context parameter.
Parameters
[in] context The thread which runs the task
Referenced by FXWorkerThread::run(), and ~Task().
setIndex()
void FXWorkerThread::Task::setIndex (const int newIndex) inline
Sets the running index of this task.
Every task receive an index which is unique among all pending tasks of the same thread pool.
Parameters
[in] newIndex the index to assign
Definition at line 74 of file FXWorkerThread.h.
References myIndex.
Referenced by FXWorkerThread::Pool::add().
Field Documentation
myIndex
int FXWorkerThread::Task::myIndex private
the index of the task, valid only after the task has been added to the pool
Definition at line 79 of file FXWorkerThread.h.
Referenced by setIndex().
The documentation for this class was generated from the following file:
FXWorkerThread.h