SUMO - Simulation of Urban MObility: GNEFrame::GEOAttributes Class Reference
GNEFrame::GEOAttributes Class Reference
#include <GNEFrame.h>
Public Member Functions
GEOAttributes (GNEFrame *frameParent)
FOX-declaration.
std::map< SumoXMLAttr, std::string > getGEOAttributes () const
get GEO Attributes
void hideGEOAttributes ()
hide GEOAttributes
void refreshGEOAttributes ()
refresh TextFields with the new GEO Attributes
void showGEOAttributes (const std::vector< GNEAttributeCarrier *> &ACs)
show GEOAttribute for the current AttributeCarriers
~GEOAttributes ()
destructor
FOX-callbacks
long onCmdSetGEOAttribute (FXObject *, FXSelector, void *)
Called when user change the current GEO Attribute.
long onCmdUseGEOParameters (FXObject *, FXSelector, void *)
Called when user enters a new length.
long onCmdHelp (FXObject *, FXSelector, void *)
Called when user press the help button.
Protected Member Functions
GEOAttributes ()
FOX needs this.
Private Attributes
std::vector< GNEAttributeCarrier * > myACs
current edited ACs
GNEFrame * myFrameParent
current GNEFrame parent
SumoXMLAttr myGEOAttribute
type of GEO Attribute
FXHorizontalFrame * myGEOAttributeFrame
horizontal frame for GEOAttribute
FXLabel * myGEOAttributeLabel
Label for GEOAttribute.
FXTextField * myGEOAttributeTextField
textField for GEOAttribute
FXButton * myHelpButton
button for help
FXCheckButton * myUseGEOCheckButton
checkBox for use GEO
FXHorizontalFrame * myUseGEOFrame
horizontal frame for use GEO
FXLabel * myUseGEOLabel
Label for use GEO.
Detailed Description
Definition at line 137 of file GNEFrame.h.
Constructor & Destructor Documentation
GEOAttributes() [1/2]
GNEFrame::GEOAttributes::GEOAttributes (GNEFrame * frameParent)
FOX-declaration.
constructor
Definition at line 181 of file GNEFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonRectangular, GUIDesignCheckButtonAttribute, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldNCol, MID_GNEFRAME_GEOATTRIBUTE, MID_GNEFRAME_USEGEO, MID_HELP, myGEOAttributeFrame, myGEOAttributeLabel, myGEOAttributeTextField, myHelpButton, myUseGEOCheckButton, myUseGEOFrame, and myUseGEOLabel.
~GEOAttributes()
GNEFrame::GEOAttributes::~GEOAttributes ()
destructor
Definition at line 200 of file GNEFrame.cpp.
GEOAttributes() [2/2]
GNEFrame::GEOAttributes::GEOAttributes () inline protected
FOX needs this.
Definition at line 175 of file GNEFrame.h.
Member Function Documentation
getGEOAttributes()
std::map< SumoXMLAttr, std::string > GNEFrame::GEOAttributes::getGEOAttributes () const
get GEO Attributes
Definition at line 277 of file GNEFrame.cpp.
References myGEOAttribute, myGEOAttributeTextField, myUseGEOCheckButton, and SUMO_ATTR_GEO.
hideGEOAttributes()
void GNEFrame::GEOAttributes::hideGEOAttributes ()
hide GEOAttributes
Definition at line 237 of file GNEFrame.cpp.
References myACs, myGEOAttribute, and SUMO_ATTR_NOTHING.
Referenced by GNEInspectorFrame::inspectMultisection(), and showGEOAttributes().
onCmdHelp()
long GNEFrame::GEOAttributes::onCmdHelp (FXObject * , FXSelector , void *)
Called when user press the help button.
Definition at line 320 of file GNEFrame.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonOK, GUIDesignDialogBox, GUIDesignLabelFrameInformation, and ICON_ACCEPT.
onCmdSetGEOAttribute()
long GNEFrame::GEOAttributes::onCmdSetGEOAttribute (FXObject * , FXSelector , void *)
Called when user change the current GEO Attribute.
Definition at line 287 of file GNEFrame.cpp.
References GNEViewParent::getInspectorFrame(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNEViewNet::getViewParent(), myACs, myFrameParent, myGEOAttribute, myGEOAttributeTextField, GNEInspectorFrame::refreshValues(), and WRITE_WARNING.
onCmdUseGEOParameters()
long GNEFrame::GEOAttributes::onCmdUseGEOParameters (FXObject * , FXSelector , void *)
Called when user enters a new length.
Definition at line 304 of file GNEFrame.cpp.
References GNEViewNet::getUndoList(), GNEFrame::getViewNet(), myACs, myFrameParent, myUseGEOCheckButton, and SUMO_ATTR_GEO.
refreshGEOAttributes()
void GNEFrame::GEOAttributes::refreshGEOAttributes ()
refresh TextFields with the new GEO Attributes
Definition at line 246 of file GNEFrame.cpp.
References myACs, myGEOAttribute, myGEOAttributeFrame, myGEOAttributeTextField, myUseGEOCheckButton, and SUMO_ATTR_GEO.
Referenced by GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), and showGEOAttributes().
showGEOAttributes()
void GNEFrame::GEOAttributes::showGEOAttributes (const std::vector< GNEAttributeCarrier *> & ACs)
show GEOAttribute for the current AttributeCarriers
Definition at line 204 of file GNEFrame.cpp.
References hideGEOAttributes(), myACs, myGEOAttribute, myGEOAttributeLabel, refreshGEOAttributes(), SUMO_ATTR_GEOPOSITION, SUMO_ATTR_GEOSHAPE, SUMO_TAG_POI, SUMO_TAG_POLY, and toString().
Referenced by GNEInspectorFrame::inspectMultisection().
Field Documentation
myACs
std::vector<GNEAttributeCarrier*> GNEFrame::GEOAttributes::myACs private
current edited ACs
Definition at line 185 of file GNEFrame.h.
Referenced by hideGEOAttributes(), onCmdSetGEOAttribute(), onCmdUseGEOParameters(), refreshGEOAttributes(), and showGEOAttributes().
myFrameParent
GNEFrame* GNEFrame::GEOAttributes::myFrameParent private
current GNEFrame parent
Definition at line 179 of file GNEFrame.h.
Referenced by onCmdSetGEOAttribute(), and onCmdUseGEOParameters().
myGEOAttribute
SumoXMLAttr GNEFrame::GEOAttributes::myGEOAttribute private
type of GEO Attribute
Definition at line 182 of file GNEFrame.h.
Referenced by getGEOAttributes(), hideGEOAttributes(), onCmdSetGEOAttribute(), refreshGEOAttributes(), and showGEOAttributes().
myGEOAttributeFrame
FXHorizontalFrame* GNEFrame::GEOAttributes::myGEOAttributeFrame private
horizontal frame for GEOAttribute
Definition at line 188 of file GNEFrame.h.
Referenced by GEOAttributes(), and refreshGEOAttributes().
myGEOAttributeLabel
FXLabel* GNEFrame::GEOAttributes::myGEOAttributeLabel private
Label for GEOAttribute.
Definition at line 191 of file GNEFrame.h.
Referenced by GEOAttributes(), and showGEOAttributes().
myGEOAttributeTextField
FXTextField* GNEFrame::GEOAttributes::myGEOAttributeTextField private
textField for GEOAttribute
Definition at line 194 of file GNEFrame.h.
Referenced by GEOAttributes(), getGEOAttributes(), onCmdSetGEOAttribute(), and refreshGEOAttributes().
myHelpButton
FXButton* GNEFrame::GEOAttributes::myHelpButton private
button for help
Definition at line 206 of file GNEFrame.h.
Referenced by GEOAttributes().
myUseGEOCheckButton
FXCheckButton* GNEFrame::GEOAttributes::myUseGEOCheckButton private
checkBox for use GEO
Definition at line 203 of file GNEFrame.h.
Referenced by GEOAttributes(), getGEOAttributes(), onCmdUseGEOParameters(), and refreshGEOAttributes().
myUseGEOFrame
FXHorizontalFrame* GNEFrame::GEOAttributes::myUseGEOFrame private
horizontal frame for use GEO
Definition at line 197 of file GNEFrame.h.
Referenced by GEOAttributes().
myUseGEOLabel
FXLabel* GNEFrame::GEOAttributes::myUseGEOLabel private
Label for use GEO.
Definition at line 200 of file GNEFrame.h.
Referenced by GEOAttributes().
The documentation for this class was generated from the following files:
GNEFrame.h
GNEFrame.cpp