SUMO - Simulation of Urban MObility: SUMOVehicleParameter Class Reference
SUMOVehicleParameter Class Reference
Structure representing possible vehicle parameter.
#include <SUMOVehicleParameter.h>
Data Structures
struct Stop
Definition of vehicle stop (position and duration)
Public Member Functions
void clearParameter ()
Clears the parameter map.
bool defaultOptionOverrides (const OptionsCont &oc, const std::string &optionName) const
Returns whether the defaults shall be used.
double getDouble (const std::string &key, const double defaultValue) const
Returns the value for a given key converted to a double.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string getParameter (const std::string &key, const std::string &defaultValue="") const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void setParameter (const std::string &key, const std::string &value)
Sets a parameter.
SUMOVehicleParameter ()
Constructor.
void unsetParameter (const std::string &key)
Removes a parameter.
void updateParameter (const std::map< std::string, std::string > &mapArg)
Adds or updates all given parameters from the map.
bool wasSet (int what) const
Returns whether the given parameter was set.
void write (OutputDevice &dev, const OptionsCont &oc, const SumoXMLTag tag=SUMO_TAG_VEHICLE, const std::string &typeID="") const
Writes the parameters as a beginning element.
void writeParams (OutputDevice &out) const
~SUMOVehicleParameter ()
Destructor.
Static Public Member Functions
static double interpretEdgePos (double pos, double maximumValue, SumoXMLAttr attr, const std::string &id)
Interprets negative edge positions and fits them onto a given edge.
Depart/arrival-attributes verification
static bool parseDepart (const std::string &val, const std::string &element, const std::string &id, SUMOTime &depart, DepartDefinition &dd, std::string &error)
Validates a given depart value.
static bool parseDepartLane (const std::string &val, const std::string &element, const std::string &id, int &lane, DepartLaneDefinition &dld, std::string &error)
Validates a given departLane value.
static bool parseDepartPos (const std::string &val, const std::string &element, const std::string &id, double &pos, DepartPosDefinition &dpd, std::string &error)
Validates a given departPos value.
static bool parseDepartPosLat (const std::string &val, const std::string &element, const std::string &id, double &pos, DepartPosLatDefinition &dpd, std::string &error)
Validates a given departPosLat value.
static bool parseDepartSpeed (const std::string &val, const std::string &element, const std::string &id, double &speed, DepartSpeedDefinition &dsd, std::string &error)
Validates a given departSpeed value.
static bool parseArrivalLane (const std::string &val, const std::string &element, const std::string &id, int &lane, ArrivalLaneDefinition &ald, std::string &error)
Validates a given arrivalLane value.
static bool parseArrivalPos (const std::string &val, const std::string &element, const std::string &id, double &pos, ArrivalPosDefinition &apd, std::string &error)
Validates a given arrivalPos value.
static bool parseArrivalPosLat (const std::string &val, const std::string &element, const std::string &id, double &pos, ArrivalPosLatDefinition &apd, std::string &error)
Validates a given arrivalPosLat value.
static bool parseArrivalSpeed (const std::string &val, const std::string &element, const std::string &id, double &speed, ArrivalSpeedDefinition &asd, std::string &error)
Validates a given arrivalSpeed value.
Data Fields
RGBColor color
The vehicle's color, TraCI may change this.
int containerNumber
The static number of containers in the vehicle when it departs.
std::string fromTaz
The vehicle's origin zone (district)
std::string id
The vehicle's id.
std::string line
The vehicle's line (mainly for public transport)
int parametersSet
Information for the router which parameter were set, TraCI may modify this (whe changing color)
int personNumber
The static number of persons in the vehicle when it departs (not including boarding persons)
std::string routeid
The vehicle's route id.
std::vector< Stop > stops
List of the stops the vehicle will make, TraCI may add entries here.
std::string toTaz
The vehicle's destination zone (district)
std::vector< std::string > via
List of the via-edges the vehicle must visit.
std::string vtypeid
The vehicle's type id.
Departure definition
SUMOTime depart
The vehicle's departure time.
DepartDefinition departProcedure
Information how the vehicle shall choose the depart time.
int departLane
(optional) The lane the vehicle shall depart from (index in edge)
DepartLaneDefinition departLaneProcedure
Information how the vehicle shall choose the lane to depart from.
double departPos
(optional) The position the vehicle shall depart from
DepartPosDefinition departPosProcedure
Information how the vehicle shall choose the departure position.
double departPosLat
(optional) The lateral position the vehicle shall depart from
DepartPosLatDefinition departPosLatProcedure
Information how the vehicle shall choose the lateral departure position.
double departSpeed
(optional) The initial speed of the vehicle
DepartSpeedDefinition departSpeedProcedure
Information how the vehicle's initial speed shall be chosen.
Arrival definition
int arrivalLane
(optional) The lane the vehicle shall arrive on (not used yet)
ArrivalLaneDefinition arrivalLaneProcedure
Information how the vehicle shall choose the lane to arrive on.
double arrivalPos
(optional) The position the vehicle shall arrive on
ArrivalPosDefinition arrivalPosProcedure
Information how the vehicle shall choose the arrival position.
double arrivalPosLat
(optional) The lateral position the vehicle shall arrive on
ArrivalPosLatDefinition arrivalPosLatProcedure
Information how the vehicle shall choose the lateral arrival position.
double arrivalSpeed
(optional) The final speed of the vehicle (not used yet)
ArrivalSpeedDefinition arrivalSpeedProcedure
Information how the vehicle's end speed shall be chosen.
Repetition definition
int repetitionNumber
The number of times the vehicle shall be repeatedly inserted.
int repetitionsDone
The number of times the vehicle was already inserted.
SUMOTime repetitionOffset
The time offset between vehicle reinsertions.
double repetitionProbability
The probability for emitting a vehicle per second.
SUMOTime repetitionEnd
The time at which the flow ends (only needed when using repetitionProbability)
Detailed Description
Structure representing possible vehicle parameter.
When used within a vehicle, parameter are usually const except for selected items adaptable via TraCI which are flagged as mutable below The fields yielding with "Procedure" describe whether the according value shall be used or another procedure is used to choose the value.
See also
DepartLaneDefinition
DepartPosDefinition
DepartSpeedDefinition
Definition at line 284 of file SUMOVehicleParameter.h.
Constructor & Destructor Documentation
SUMOVehicleParameter()
SUMOVehicleParameter::SUMOVehicleParameter ()
Constructor.
Initialises the structure with default values
Definition at line 43 of file SUMOVehicleParameter.cpp.
~SUMOVehicleParameter()
SUMOVehicleParameter::~SUMOVehicleParameter ()
Destructor.
Definition at line 58 of file SUMOVehicleParameter.cpp.
Member Function Documentation
clearParameter()
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 97 of file Parameterised.cpp.
References Parameterised::myMap.
defaultOptionOverrides()
bool SUMOVehicleParameter::defaultOptionOverrides (const OptionsCont & oc, const std::string & optionName) const
Returns whether the defaults shall be used.
Parameters
[in] oc The options to get the options from
[in] optionName The name of the option to determine whether its value shall be used
Returns
Whether the option is set and –defaults-override was set
Definition at line 62 of file SUMOVehicleParameter.cpp.
References OptionsCont::exists(), OptionsCont::getBool(), and OptionsCont::isSet().
Referenced by wasSet(), and write().
getDouble()
double Parameterised::getDouble (const std::string & key, const double defaultValue) const inherited
Returns the value for a given key converted to a double.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 87 of file Parameterised.cpp.
References TplConvert::_2double(), and Parameterised::myMap.
Referenced by MSDevice_Battery::buildVehicleDevices().
getMap()
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 117 of file Parameterised.h.
References Parameterised::myMap, and Parameterised::writeParams().
Referenced by NIImporter_SUMO::_loadNetwork(), NBEdge::addLane(), GUIParameterTableWindow::closeBuilding(), NBTrafficLightDefinition::compute(), GUITrafficLightLogicWrapper::getParameterWindow(), GUIPolygon::getParameterWindow(), GUIJunctionWrapper::getParameterWindow(), GUIPointOfInterest::getParameterWindow(), GUIContainer::getTypeParameterWindow(), GUIPerson::getTypeParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), NIImporter_OpenStreetMap::insertEdge(), GUIParameterTableWindow::numParams(), TraCIServerAPI_TrafficLight::processGet(), and ROPerson::saveAsXML().
getParameter()
const std::string Parameterised::getParameter (const std::string & key, const std::string & defaultValue = "") const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 77 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NBEdge::addRestrictedLane(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSDevice_SSM::getMeasuresAndThresholds(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSDevice_SSM::getOutputFilename(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), libsumo::Edge::getParameter(), libsumo::Polygon::getParameter(), libsumo::Route::getParameter(), libsumo::POI::getParameter(), libsumo::TrafficLight::getParameter(), libsumo::VehicleType::getParameter(), libsumo::Person::getParameter(), libsumo::Lane::getParameter(), libsumo::Vehicle::getParameter(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), MSTriggeredRerouter::getWeight(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_OpenStreetMap::insertEdge(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), libsumo::Helper::moveToXYMap(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSDelayBasedTrafficLightLogic::MSDelayBasedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), MSSOTLPolicyDesirability::readParameter(), MSDevice_SSM::requestsTrajectories(), NBEdgeCont::splitAt(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), MSDevice_SSM::useGeoCoords(), and NWWriter_DlrNavteq::writeLinksUnsplitted().
interpretEdgePos()
double SUMOVehicleParameter::interpretEdgePos (double pos, double maximumValue, SumoXMLAttr attr, const std::string & id) static
Interprets negative edge positions and fits them onto a given edge.
Parameters
[in] pos The position to be interpreted
[in] maximumValue The maximum allowed value (edge length)
[in] attr The attribute from which the value originated
[in] id The id of the object to which this attribute belongs
Returns
Whether the interpreted position
Definition at line 588 of file SUMOVehicleParameter.cpp.
References toString(), and WRITE_WARNING.
Referenced by MSContainer::MSContainerStage_Tranship::MSContainerStage_Tranship(), MSPerson::MSPersonStage_Walking::MSPersonStage_Walking(), SUMOVehicleParserHelper::parseWalkPos(), and wasSet().
knowsParameter()
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 71 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NBEdge::append(), MSDevice_Bluelight::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), NWWriter_DlrNavteq::getBrunnelType(), MSDevice_SSM::getDetectionRange(), MSDevice_SSM::getExtraTime(), MSDevice_SSM::getMeasuresAndThresholds(), MSDevice_SSM::getOutputFilename(), MSTriggeredRerouter::getWeight(), MSDevice_SSM::requestsTrajectories(), and MSDevice_SSM::useGeoCoords().
parseArrivalLane()
bool SUMOVehicleParameter::parseArrivalLane (const std::string & val, const std::string & element, const std::string & id, int & lane, ArrivalLaneDefinition & ald, std::string & error) static
Validates a given arrivalLane value.
Parameters
[in] val The arrivalLane value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] lane The parsed lane, if given
[out] ald The parsed arrivalLane definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid arrivalLane definition
Definition at line 492 of file SUMOVehicleParameter.cpp.
References TplConvert::_2int(), ARRIVAL_LANE_CURRENT, ARRIVAL_LANE_GIVEN, and OutputDevice::ok().
Referenced by ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
parseArrivalPos()
bool SUMOVehicleParameter::parseArrivalPos (const std::string & val, const std::string & element, const std::string & id, double & pos, ArrivalPosDefinition & apd, std::string & error) static
Validates a given arrivalPos value.
Parameters
[in] val The arrivalPos value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] pos The parsed position, if given
[out] apd The parsed arrivalPos definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid arrivalPos definition
Definition at line 516 of file SUMOVehicleParameter.cpp.
References TplConvert::_2double(), ARRIVAL_POS_GIVEN, ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, and OutputDevice::ok().
Referenced by ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), SUMOVehicleParserHelper::parseWalkPos(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
parseArrivalPosLat()
bool SUMOVehicleParameter::parseArrivalPosLat (const std::string & val, const std::string & element, const std::string & id, double & pos, ArrivalPosLatDefinition & apd, std::string & error) static
Validates a given arrivalPosLat value.
Parameters
[in] val The arrivalPosLat value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] pos The parsed position, if given
[out] apd The parsed arrivalPos definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid arrivalPos definition
Definition at line 539 of file SUMOVehicleParameter.cpp.
References TplConvert::_2double(), ARRIVAL_POSLAT_CENTER, ARRIVAL_POSLAT_GIVEN, ARRIVAL_POSLAT_LEFT, ARRIVAL_POSLAT_RIGHT, and OutputDevice::ok().
Referenced by SUMOVehicleParserHelper::parseCommonAttributes(), and wasSet().
parseArrivalSpeed()
bool SUMOVehicleParameter::parseArrivalSpeed (const std::string & val, const std::string & element, const std::string & id, double & speed, ArrivalSpeedDefinition & asd, std::string & error) static
Validates a given arrivalSpeed value.
Parameters
[in] val The arrivalSpeed value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] speed The parsed speed, if given
[out] asd The parsed arrivalSpeed definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid arrivalSpeed definition
Definition at line 564 of file SUMOVehicleParameter.cpp.
References TplConvert::_2double(), ARRIVAL_SPEED_CURRENT, ARRIVAL_SPEED_GIVEN, and OutputDevice::ok().
Referenced by ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
parseDepart()
bool SUMOVehicleParameter::parseDepart (const std::string & val, const std::string & element, const std::string & id, SUMOTime & depart, DepartDefinition & dd, std::string & error) static
Validates a given depart value.
Parameters
[in] val The depart value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] depart The parsed depart time, if given
[out] dd The parsed departProcedure definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid depart definition
Definition at line 348 of file SUMOVehicleParameter.cpp.
References DEPART_CONTAINER_TRIGGERED, DEPART_GIVEN, DEPART_NOW, DEPART_TRIGGERED, and string2time().
Referenced by SUMOVehicleParserHelper::parseVehicleAttributes(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
parseDepartLane()
bool SUMOVehicleParameter::parseDepartLane (const std::string & val, const std::string & element, const std::string & id, int & lane, DepartLaneDefinition & dld, std::string & error) static
Validates a given departLane value.
Parameters
[in] val The departLane value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] lane The parsed lane, if given
[out] dld The parsed departLane definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid departLane definition
Definition at line 374 of file SUMOVehicleParameter.cpp.
References TplConvert::_2int(), DEPART_LANE_ALLOWED_FREE, DEPART_LANE_BEST_FREE, DEPART_LANE_FIRST_ALLOWED, DEPART_LANE_FREE, DEPART_LANE_GIVEN, DEPART_LANE_RANDOM, and OutputDevice::ok().
Referenced by ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
parseDepartPos()
bool SUMOVehicleParameter::parseDepartPos (const std::string & val, const std::string & element, const std::string & id, double & pos, DepartPosDefinition & dpd, std::string & error) static
Validates a given departPos value.
Parameters
[in] val The departPos value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] pos The parsed position, if given
[out] dpd The parsed departPos definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid departPos definition
Definition at line 406 of file SUMOVehicleParameter.cpp.
References TplConvert::_2double(), DEPART_POS_BASE, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_LAST, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, and OutputDevice::ok().
Referenced by ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
parseDepartPosLat()
bool SUMOVehicleParameter::parseDepartPosLat (const std::string & val, const std::string & element, const std::string & id, double & pos, DepartPosLatDefinition & dpd, std::string & error) static
Validates a given departPosLat value.
Parameters
[in] val The departPosLat value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] pos The parsed position, if given
[out] dpd The parsed departPos definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid departPos definition
Definition at line 435 of file SUMOVehicleParameter.cpp.
References TplConvert::_2double(), DEPART_POSLAT_CENTER, DEPART_POSLAT_FREE, DEPART_POSLAT_GIVEN, DEPART_POSLAT_LEFT, DEPART_POSLAT_RANDOM, DEPART_POSLAT_RANDOM_FREE, DEPART_POSLAT_RIGHT, and OutputDevice::ok().
Referenced by SUMOVehicleParserHelper::parseCommonAttributes(), and wasSet().
parseDepartSpeed()
bool SUMOVehicleParameter::parseDepartSpeed (const std::string & val, const std::string & element, const std::string & id, double & speed, DepartSpeedDefinition & dsd, std::string & error) static
Validates a given departSpeed value.
Parameters
[in] val The departSpeed value to parse
[in] element The name of the type of the parsed element, for building the error message
[in] id The id of the parsed element, for building the error message
[out] speed The parsed speed, if given
[out] dsd The parsed departSpeed definition
[out] error Error message, if an error occures
Returns
Whether the given value is a valid departSpeed definition
Definition at line 466 of file SUMOVehicleParameter.cpp.
References TplConvert::_2double(), DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, and OutputDevice::ok().
Referenced by ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and wasSet().
setParameter()
void Parameterised::setParameter (const std::string & key, const std::string & value) inherited
Sets a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 51 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), ShapeHandler::addPOI(), NBEdge::Lane::Lane(), NIImporter_OpenDrive::loadNetwork(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), ShapeHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NBNodeCont::remapIDs(), libsumo::Edge::setParameter(), libsumo::Route::setParameter(), libsumo::Polygon::setParameter(), libsumo::POI::setParameter(), libsumo::TrafficLight::setParameter(), and libsumo::Lane::setParameter().
unsetParameter()
void Parameterised::unsetParameter (const std::string & key) inherited
Removes a parameter.
Parameters
[in] key The parameter's name
Definition at line 57 of file Parameterised.cpp.
References Parameterised::myMap.
updateParameter()
void Parameterised::updateParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds or updates all given parameters from the map.
Parameters
[in] mapArg The keys/values to insert
Definition at line 63 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by NIImporter_SUMO::_loadNetwork(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NLJunctionControlBuilder::closeJunction(), NBTrafficLightDefinition::compute(), and NIImporter_OpenStreetMap::insertEdge().
wasSet()
bool SUMOVehicleParameter::wasSet (int what) const inline
Returns whether the given parameter was set.
Parameters
[in] what The parameter which one asks for
Returns
Whether the given parameter was set
Definition at line 299 of file SUMOVehicleParameter.h.
References defaultOptionOverrides(), depart, interpretEdgePos(), parametersSet, parseArrivalLane(), parseArrivalPos(), parseArrivalPosLat(), parseArrivalSpeed(), parseDepart(), parseDepartLane(), parseDepartPos(), parseDepartPosLat(), parseDepartSpeed(), SUMO_TAG_VEHICLE, and write().
Referenced by MSDevice_Routing::buildVehicleDevices(), MSRouteHandler::closeVehicle(), MSBaseVehicle::MSBaseVehicle(), MSDevice_Routing::MSDevice_Routing(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), MSBaseVehicle::saveState(), GUIBaseVehicle::setFunctionalColor(), and write().
write()
void SUMOVehicleParameter::write (OutputDevice & dev, const OptionsCont & oc, const SumoXMLTag tag = SUMO_TAG_VEHICLE, const std::string & typeID = "") const
Writes the parameters as a beginning element.
Parameters
[in,out] dev The device to write into
[in] oc The options to get defaults from
[in] tag The "root" tag to write (defaults to vehicle)
[in] tag The typeID to write (defaults to member vtypeid)
Exceptions
IOError not yet implemented
Definition at line 68 of file SUMOVehicleParameter.cpp.
References ARRIVAL_LANE_CURRENT, ARRIVAL_LANE_DEFAULT, ARRIVAL_LANE_GIVEN, ARRIVAL_POS_DEFAULT, ARRIVAL_POS_GIVEN, ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, ARRIVAL_POSLAT_CENTER, ARRIVAL_POSLAT_DEFAULT, ARRIVAL_POSLAT_GIVEN, ARRIVAL_POSLAT_LEFT, ARRIVAL_POSLAT_RIGHT, ARRIVAL_SPEED_CURRENT, ARRIVAL_SPEED_DEFAULT, ARRIVAL_SPEED_GIVEN, arrivalLane, arrivalLaneProcedure, arrivalPos, arrivalPosProcedure, arrivalSpeed, arrivalSpeedProcedure, color, containerNumber, defaultOptionOverrides(), depart, DEPART_CONTAINER_TRIGGERED, DEPART_LANE_ALLOWED_FREE, DEPART_LANE_BEST_FREE, DEPART_LANE_DEFAULT, DEPART_LANE_FIRST_ALLOWED, DEPART_LANE_FREE, DEPART_LANE_GIVEN, DEPART_LANE_RANDOM, DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_LAST, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_POSLAT_CENTER, DEPART_POSLAT_DEFAULT, DEPART_POSLAT_FREE, DEPART_POSLAT_GIVEN, DEPART_POSLAT_LEFT, DEPART_POSLAT_RANDOM, DEPART_POSLAT_RANDOM_FREE, DEPART_POSLAT_RIGHT, DEPART_SPEED_DEFAULT, DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, DEPART_TRIGGERED, departLane, departLaneProcedure, departPos, departPosProcedure, departProcedure, departSpeed, departSpeedProcedure, OptionsCont::exists(), fromTaz, OptionsCont::getString(), OptionsCont::isSet(), line, OutputDevice::openTag(), personNumber, SUMO_ATTR_ARRIVALLANE, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_ARRIVALPOS_LAT, SUMO_ATTR_ARRIVALSPEED, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_DEPART, SUMO_ATTR_DEPARTLANE, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DEPARTPOS_LAT, SUMO_ATTR_DEPARTSPEED, SUMO_ATTR_FROM_TAZ, SUMO_ATTR_ID, SUMO_ATTR_LINE, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_TO_TAZ, SUMO_ATTR_TYPE, time2string(), toString(), toTaz, VEHPARS_ARRIVALLANE_SET, VEHPARS_ARRIVALPOS_SET, VEHPARS_ARRIVALPOSLAT_SET, VEHPARS_ARRIVALSPEED_SET, VEHPARS_COLOR_SET, VEHPARS_CONTAINER_NUMBER_SET, VEHPARS_DEPARTLANE_SET, VEHPARS_DEPARTPOS_SET, VEHPARS_DEPARTPOSLAT_SET, VEHPARS_DEPARTSPEED_SET, VEHPARS_FROM_TAZ_SET, VEHPARS_LINE_SET, VEHPARS_PERSON_NUMBER_SET, VEHPARS_TO_TAZ_SET, VEHPARS_VTYPE_SET, vtypeid, wasSet(), OutputDevice::writeAttr(), and OutputDevice::writeNonEmptyAttr().
Referenced by MSPerson::routeOutput(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), MSBaseVehicle::saveState(), and wasSet().
writeParams()
void Parameterised::writeParams (OutputDevice & out) const inherited
Definition at line 102 of file Parameterised.cpp.
References OutputDevice::closeTag(), StringUtils::escapeXML(), Parameterised::myMap, OutputDevice::openTag(), SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, and OutputDevice::writeAttr().
Referenced by Parameterised::getMap(), ROVehicle::saveAsXML(), MEVehicle::saveState(), MSVehicle::saveState(), SUMOVTypeParameter::write(), NWWriter_SUMO::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), NWWriter_SUMO::writeJunction(), NWWriter_SUMO::writeLane(), NWWriter_XML::writeNodes(), MSDevice_Vehroutes::writeOutput(), SUMOPolygon::writeXML(), and PointOfInterest::writeXML().
Field Documentation
arrivalLane
int SUMOVehicleParameter::arrivalLane
(optional) The lane the vehicle shall arrive on (not used yet)
Definition at line 494 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
arrivalLaneProcedure
ArrivalLaneDefinition SUMOVehicleParameter::arrivalLaneProcedure
Information how the vehicle shall choose the lane to arrive on.
Definition at line 496 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), MSVehicle::updateBestLanes(), and write().
arrivalPos
double SUMOVehicleParameter::arrivalPos
(optional) The position the vehicle shall arrive on
Definition at line 498 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
arrivalPosLat
double SUMOVehicleParameter::arrivalPosLat
(optional) The lateral position the vehicle shall arrive on
Definition at line 502 of file SUMOVehicleParameter.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), and SUMOVehicleParserHelper::parseCommonAttributes().
arrivalPosLatProcedure
ArrivalPosLatDefinition SUMOVehicleParameter::arrivalPosLatProcedure
Information how the vehicle shall choose the lateral arrival position.
Definition at line 504 of file SUMOVehicleParameter.h.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), and SUMOVehicleParserHelper::parseCommonAttributes().
arrivalPosProcedure
ArrivalPosDefinition SUMOVehicleParameter::arrivalPosProcedure
Information how the vehicle shall choose the arrival position.
Definition at line 500 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
arrivalSpeed
double SUMOVehicleParameter::arrivalSpeed
(optional) The final speed of the vehicle (not used yet)
Definition at line 506 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSLane::isInsertionSuccess(), SUMOVehicleParserHelper::parseCommonAttributes(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processSet(), and write().
arrivalSpeedProcedure
ArrivalSpeedDefinition SUMOVehicleParameter::arrivalSpeedProcedure
Information how the vehicle's end speed shall be chosen.
Definition at line 508 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSLane::isInsertionSuccess(), SUMOVehicleParserHelper::parseCommonAttributes(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processSet(), and write().
color
RGBColor SUMOVehicleParameter::color mutable
The vehicle's color, TraCI may change this.
Definition at line 462 of file SUMOVehicleParameter.h.
Referenced by libsumo::Person::getColor(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setColor(), GUIBaseVehicle::setFunctionalColor(), and write().
containerNumber
int SUMOVehicleParameter::containerNumber
The static number of containers in the vehicle when it departs.
Definition at line 594 of file SUMOVehicleParameter.h.
Referenced by MSVehicle::getContainerNumber(), SUMOVehicleParserHelper::parseCommonAttributes(), and write().
depart
SUMOTime SUMOVehicleParameter::depart
The vehicle's departure time.
Definition at line 468 of file SUMOVehicleParameter.h.
Referenced by MSVehicleContainer::add(), libsumo::Person::add(), MSTransportableControl::add(), libsumo::Vehicle::add(), RONet::addFlow(), MSRouteHandler::addPersonTrip(), IntermodalRouter< E, L, N, V >::addSchedule(), MSRouteHandler::addStop(), MSBaseVehicle::addStops(), MSRouteHandler::addWalk(), MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), RONet::checkFlows(), SUMORouteHandler::checkLastDepart(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), ROPerson::computeIntermodal(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), RORoutable::getDepart(), MSBaseVehicle::getDepartDelay(), MSTransportable::getDesiredDepart(), MSDevice_Routing::MSDevice_Routing(), ROMARouteHandler::myEndElement(), MSRouteHandler::myStartElement(), MSDevice_Vehroutes::notifyEnter(), TraCIServerAPI_Vehicle::processSet(), SUMORouteHandler::registerLastDepart(), MSVehicleContainer::remove(), METriggeredCalibrator::tryEmit(), MSInsertionControl::tryInsert(), MSVehicleControl::vehicleDeparted(), wasSet(), write(), and MSDevice_Vehroutes::writeOutput().
departLane
int SUMOVehicleParameter::departLane
(optional) The lane the vehicle shall depart from (index in edge)
Definition at line 472 of file SUMOVehicleParameter.h.
Referenced by libsumo::Vehicle::add(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSEdge::getDepartLane(), MSCalibrator::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
departLaneProcedure
DepartLaneDefinition SUMOVehicleParameter::departLaneProcedure
Information how the vehicle shall choose the lane to depart from.
Definition at line 474 of file SUMOVehicleParameter.h.
Referenced by libsumo::Vehicle::add(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSEdge::getDepartLane(), MSEdge::insertVehicle(), MSVehicle::MSVehicle(), MSCalibrator::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
departPos
double SUMOVehicleParameter::departPos
(optional) The position the vehicle shall depart from
Definition at line 476 of file SUMOVehicleParameter.h.
Referenced by libsumo::Person::add(), libsumo::Vehicle::add(), MSRouteHandler::addPersonTrip(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSVehicleControl::addVehicle(), MSRouteHandler::addWalk(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSEdge::getDepartPosBound(), MSLane::insertVehicle(), MSEdge::insertVehicle(), MSRouteHandler::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
departPosLat
double SUMOVehicleParameter::departPosLat
(optional) The lateral position the vehicle shall depart from
Definition at line 480 of file SUMOVehicleParameter.h.
Referenced by MSLane::getDepartPosLat(), and SUMOVehicleParserHelper::parseCommonAttributes().
departPosLatProcedure
DepartPosLatDefinition SUMOVehicleParameter::departPosLatProcedure
Information how the vehicle shall choose the lateral departure position.
Definition at line 482 of file SUMOVehicleParameter.h.
Referenced by MSLane::getDepartPosLat(), MSLane::insertVehicle(), and SUMOVehicleParserHelper::parseCommonAttributes().
departPosProcedure
DepartPosDefinition SUMOVehicleParameter::departPosProcedure
Information how the vehicle shall choose the departure position.
Definition at line 478 of file SUMOVehicleParameter.h.
Referenced by libsumo::Person::add(), libsumo::Vehicle::add(), MSRouteHandler::addPersonTrip(), MSVehicle::addStop(), MSRouteHandler::addWalk(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSEdge::getDepartPosBound(), MSLane::insertVehicle(), MSEdge::insertVehicle(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
departProcedure
DepartDefinition SUMOVehicleParameter::departProcedure
Information how the vehicle shall choose the depart time.
Definition at line 470 of file SUMOVehicleParameter.h.
Referenced by libsumo::Person::add(), libsumo::Vehicle::add(), ROPerson::addTrip(), MSVehicleControl::addVehicle(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), TraCIServerAPI_Vehicle::processSet(), SUMORouteHandler::registerLastDepart(), and write().
departSpeed
double SUMOVehicleParameter::departSpeed
(optional) The initial speed of the vehicle
Definition at line 484 of file SUMOVehicleParameter.h.
Referenced by libsumo::Vehicle::add(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSLane::getDepartSpeed(), MSEdge::insertVehicle(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
departSpeedProcedure
DepartSpeedDefinition SUMOVehicleParameter::departSpeedProcedure
Information how the vehicle's initial speed shall be chosen.
Definition at line 486 of file SUMOVehicleParameter.h.
Referenced by libsumo::Vehicle::add(), ROJTRFrame::checkOptions(), RODUAFrame::checkOptions(), checkOptions(), MSLane::getDepartSpeed(), MSEdge::insertVehicle(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSCalibrator::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
fromTaz
std::string SUMOVehicleParameter::fromTaz
The vehicle's origin zone (district)
Definition at line 532 of file SUMOVehicleParameter.h.
Referenced by ROMARouteHandler::myEndElement(), ROMARouteHandler::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::reroute(), and write().
id
std::string SUMOVehicleParameter::id
The vehicle's id.
Definition at line 455 of file SUMOVehicleParameter.h.
Referenced by libsumo::Person::add(), MSTransportableControl::add(), MSInsertionControl::add(), libsumo::Vehicle::add(), RONet::addFlow(), MSRouteHandler::addPersonTrip(), RORouteHandler::addPersonTrip(), IntermodalRouter< E, L, N, V >::addSchedule(), MSRouteHandler::addStop(), RORouteHandler::addStop(), MSVehicle::addStop(), ROPerson::addTrip(), MSRouteHandler::addWalk(), RORouteHandler::addWalk(), MSTransportableControl::boardAnyWaiting(), RONet::checkFlows(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSStateHandler::closeVehicle(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSBaseVehicle::getID(), RORoutable::getID(), MSTransportable::getID(), MSEdge::insertVehicle(), MSTransportableControl::loadAnyWaiting(), MEVehicle::MEVehicle(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::MSVehicle(), ROMARouteHandler::myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), SUMOVehicleParserHelper::parseCommonAttributes(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), TraCIServerAPI_Vehicle::processSet(), and MSVehicle::replaceParkingArea().
line
std::string SUMOVehicleParameter::line mutable
The vehicle's line (mainly for public transport)
Definition at line 529 of file SUMOVehicleParameter.h.
Referenced by IntermodalRouter< E, L, N, V >::addSchedule(), MSVehicleControl::addVehicle(), MSTransportableControl::boardAnyWaiting(), RONet::checkFlows(), GUIBaseVehicle::drawOnPos(), libsumo::Vehicle::getLine(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSVehicleControl::getWaitingVehicle(), RORoutable::isPublicTransport(), MSTransportableControl::loadAnyWaiting(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), SUMORouteHandler::registerLastDepart(), libsumo::Vehicle::setLine(), MSTransportable::Stage_Driving::setVehicle(), write(), and MSDevice_Vehroutes::writeOutput().
parametersSet
int SUMOVehicleParameter::parametersSet mutable
Information for the router which parameter were set, TraCI may modify this (whe changing color)
Definition at line 597 of file SUMOVehicleParameter.h.
Referenced by ROPerson::addTrip(), MSRouteHandler::closeFlow(), MSBaseVehicle::MSBaseVehicle(), MSRouteHandler::myEndElement(), SUMORouteHandler::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setColor(), wasSet(), and SUMOVehicleParameter::Stop::write().
personNumber
int SUMOVehicleParameter::personNumber
The static number of persons in the vehicle when it departs (not including boarding persons)
Definition at line 591 of file SUMOVehicleParameter.h.
Referenced by MSVehicle::getPersonNumber(), SUMOVehicleParserHelper::parseCommonAttributes(), TraCIServerAPI_Vehicle::processSet(), and write().
repetitionEnd
SUMOTime SUMOVehicleParameter::repetitionEnd
The time at which the flow ends (only needed when using repetitionProbability)
Definition at line 524 of file SUMOVehicleParameter.h.
Referenced by RONet::checkFlows(), and MSInsertionControl::determineCandidates().
repetitionNumber
int SUMOVehicleParameter::repetitionNumber
The number of times the vehicle shall be repeatedly inserted.
Definition at line 516 of file SUMOVehicleParameter.h.
Referenced by RONet::addFlow(), IntermodalRouter< E, L, N, V >::addSchedule(), MSVehicleControl::addVehicle(), RONet::checkFlows(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), MSInsertionControl::determineCandidates(), RORoutable::isPartOfFlow(), SUMORouteHandler::myEndElement(), and MSBaseVehicle::~MSBaseVehicle().
repetitionOffset
SUMOTime SUMOVehicleParameter::repetitionOffset
The time offset between vehicle reinsertions.
Definition at line 520 of file SUMOVehicleParameter.h.
Referenced by RONet::addFlow(), IntermodalRouter< E, L, N, V >::addSchedule(), MSBaseVehicle::addStops(), RONet::checkFlows(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), and MSInsertionControl::determineCandidates().
repetitionProbability
double SUMOVehicleParameter::repetitionProbability
The probability for emitting a vehicle per second.
Definition at line 522 of file SUMOVehicleParameter.h.
Referenced by RONet::checkFlows(), MSRouteHandler::closeFlow(), and MSInsertionControl::determineCandidates().
repetitionsDone
int SUMOVehicleParameter::repetitionsDone
The number of times the vehicle was already inserted.
Definition at line 518 of file SUMOVehicleParameter.h.
Referenced by MSBaseVehicle::addStops(), RONet::checkFlows(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), and MSInsertionControl::determineCandidates().
routeid
std::string SUMOVehicleParameter::routeid
The vehicle's route id.
Definition at line 458 of file SUMOVehicleParameter.h.
Referenced by RONet::checkFlows(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), RORouteHandler::openRoute(), RORouteHandler::openRouteDistribution(), SUMOVehicleParserHelper::parseCommonAttributes(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and MSBaseVehicle::~MSBaseVehicle().
stops
std::vector<Stop> SUMOVehicleParameter::stops mutable
List of the stops the vehicle will make, TraCI may add entries here.
Definition at line 585 of file SUMOVehicleParameter.h.
Referenced by IntermodalRouter< E, L, N, V >::addSchedule(), ROVehicle::addStop(), MSRouteHandler::addStop(), RORouteHandler::addStop(), MSBaseVehicle::addStops(), MSVehicle::addTraciStop(), RONet::checkFlows(), ROVehicle::ROVehicle(), ROVehicle::saveAsXML(), and MSDevice_Vehroutes::writeOutput().
toTaz
std::string SUMOVehicleParameter::toTaz
The vehicle's destination zone (district)
Definition at line 535 of file SUMOVehicleParameter.h.
Referenced by ROMARouteHandler::myEndElement(), ROMARouteHandler::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::reroute(), and write().
via
std::vector<std::string> SUMOVehicleParameter::via mutable
List of the via-edges the vehicle must visit.
Definition at line 588 of file SUMOVehicleParameter.h.
Referenced by MSVehicle::enterLaneAtMove(), libsumo::Vehicle::getVia(), MEVehicle::moveRoutePointer(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::reroute(), and ROVehicle::ROVehicle().
vtypeid
std::string SUMOVehicleParameter::vtypeid
The vehicle's type id.
Definition at line 460 of file SUMOVehicleParameter.h.
Referenced by MSRouteHandler::addPersonTrip(), ROPerson::addTrip(), RONet::checkFlows(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), ROMARouteHandler::myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), MSCalibrator::myStartElement(), SUMOVehicleParserHelper::parseCommonAttributes(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), and write().
The documentation for this class was generated from the following files:
SUMOVehicleParameter.h
SUMOVehicleParameter.cpp