SUMO - Simulation of Urban MObility: GNECalibratorVehicleTypeDialog Class Reference
GNECalibratorVehicleTypeDialog Class Reference
Dialog for edit rerouter intervals.
#include <GNECalibratorVehicleTypeDialog.h>
Public Member Functions
GNECalibratorVehicleTypeDialog (GNECalibratorVehicleType *editedCalibratorVehicleType, bool updatingElement)
FOX-declaration.
~GNECalibratorVehicleTypeDialog ()
destructor
FOX-callbacks
event after press accept button
long onCmdAccept (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
event after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event after press reset button
long onCmdSetVariable (FXObject *, FXSelector, void *)
after change a variable of vehicle type
FOX-callbacks
event after press accept button
long onKeyPress (FXObject *sender, FXSelector sel, void *ptr)
event after press a key
long onKeyRelease (FXObject *sender, FXSelector sel, void *ptr)
event after release a key
Protected Member Functions
void acceptChanges ()
Accept changes did in this dialog.
void cancelChanges ()
Cancel changes did in this dialog.
void changeAdditionalDialogHeader (const std::string &newHeader)
change additional dialog header
GNECalibratorVehicleTypeDialog ()
FOX needs this.
void initChanges ()
init a new group of changes that will be do it in dialog
FXint openAsModalDialog (FXuint placement=PLACEMENT_CURSOR)
execute dialog as modal
void resetChanges ()
reset changes did in this dialog.
void setVClassLabelImage ()
set VClass texture
void updateCalibratorVehicleTypeValues ()
update data fields
Protected Attributes
bool myCalibratorVehicleTypeValid
flag to check if current calibrator vehicleType is valid
FXComboBox * myComboBoxShape
FXComboBox for Shape.
FXLabel * myComboBoxShapeLabelImage
label with image of Shape
FXComboBox * myComboBoxVClass
FXComboBox for VClass.
FXLabel * myComboBoxVClassLabelImage
label with image of VClass
FXVerticalFrame * myContentFrame
frame for contents
GNECalibratorVehicleType * myEditedCalibratorVehicleType
pointer to original calibrator vehicle type
SumoXMLAttr myInvalidAttr
current sumo attribute invalid
FXTextField * myTextFieldAccel
FXTextfield for Accel.
FXTextField * myTextFieldBoardingDuration
FXTextfield for BoardingDuration.
FXTextField * myTextFieldCarFollowModel
FXTextfield for CarFollowModel.
FXTextField * myTextFieldColor
FXTextfield for Color.
FXTextField * myTextFieldContainerCapacity
FXTextfield for ContainerCapacity.
FXTextField * myTextFieldDecel
FXTextfield for Decel.
FXTextField * myTextFieldEmissionClass
FXTextfield for EmissionClass.
FXTextField * myTextFieldFilename
FXTextfield for Filename.
FXTextField * myTextFieldImpatience
FXTextfield for Impatience.
FXTextField * myTextFieldLaneChangeModel
FXTextfield for LaneChangeModel.
FXTextField * myTextFieldLatAlignment
FXTextfield for LatAlignment.
FXTextField * myTextFieldLength
FXTextfield for Length.
FXTextField * myTextFieldLoadingDuration
FXTextfield for LoadingDuration.
FXTextField * myTextFieldMaxSpeed
FXTextfield for MaxSpeed.
FXTextField * myTextFieldMaxSpeedLat
FXTextfield for MaxSpeedLat.
FXTextField * myTextFieldMinGap
FXTextfield for MinGap.
FXTextField * myTextFieldMinGapLat
FXTextfield for MinGapLat.
FXTextField * myTextFieldPersonCapacity
FXTextfield for PersonCapacity.
FXTextField * myTextFieldSigma
FXTextfield for Sigma.
FXTextField * myTextFieldSpeedDev
FXTextfield for SpeedDev.
FXTextField * myTextFieldSpeedFactor
FXTextfield for SpeedFactor.
FXTextField * myTextFieldTau
FXTextfield for Tau.
FXTextField * myTextFieldVehicleTypeID
FXTextfield for vehicleTypeID.
FXTextField * myTextFieldWidth
FXTextfield for Width.
bool myUpdatingElement
flag to indicate if flow are being created or modified
Private Member Functions
GNECalibratorVehicleTypeDialog (const GNECalibratorVehicleTypeDialog &)=delete
Invalidated copy constructor.
GNECalibratorVehicleTypeDialog & operator= (const GNECalibratorVehicleTypeDialog &)=delete
Invalidated assignment operator.
Detailed Description
Dialog for edit rerouter intervals.
Definition at line 49 of file GNECalibratorVehicleTypeDialog.h.
Constructor & Destructor Documentation
GNECalibratorVehicleTypeDialog() [1/3]
GNECalibratorVehicleTypeDialog::GNECalibratorVehicleTypeDialog (GNECalibratorVehicleType * editedCalibratorVehicleType, bool updatingElement)
FOX-declaration.
constructor
Definition at line 61 of file GNECalibratorVehicleTypeDialog.cpp.
References GUIDesignAuxiliarFrame, GUIDesignComboBox, GUIDesignComboBoxNCol, GUIDesignLabelIconExtendedx46Ticked, GUIDesignLabelThick, GUIDesignTextField, GUIDesignTextFieldInt, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, GUIDesignUniformHorizontalFrame, MID_GNE_CALIBRATORDIALOG_SET_VARIABLE, SUMO_ATTR_ACCEL, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_DECEL, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VCLASS, SUMO_ATTR_WIDTH, SumoVehicleClassStrings, SumoVehicleShapeStrings, SVC_IGNORING, SVS_UNKNOWN, and toString().
~GNECalibratorVehicleTypeDialog()
GNECalibratorVehicleTypeDialog::~GNECalibratorVehicleTypeDialog ()
destructor
Definition at line 220 of file GNECalibratorVehicleTypeDialog.cpp.
GNECalibratorVehicleTypeDialog() [2/3]
GNECalibratorVehicleTypeDialog::GNECalibratorVehicleTypeDialog () inline protected
FOX needs this.
Definition at line 77 of file GNECalibratorVehicleTypeDialog.h.
GNECalibratorVehicleTypeDialog() [3/3]
GNECalibratorVehicleTypeDialog::GNECalibratorVehicleTypeDialog (const GNECalibratorVehicleTypeDialog &) private delete
Invalidated copy constructor.
Member Function Documentation
acceptChanges()
void GNEAdditionalDialog::acceptChanges () protected inherited
Accept changes did in this dialog.
Definition at line 124 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_end().
Referenced by GNECalibratorFlowDialog::onCmdAccept(), onCmdAccept(), GNECalibratorRouteDialog::onCmdAccept(), GNERerouterDialog::onCmdAccept(), GNECalibratorDialog::onCmdAccept(), GNERerouterIntervalDialog::onCmdAccept(), and GNEVariableSpeedSignDialog::onCmdAccept().
cancelChanges()
void GNEAdditionalDialog::cancelChanges () protected inherited
Cancel changes did in this dialog.
Definition at line 135 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myUndoList, and GNEUndoList::p_abortLastCommandGroup().
Referenced by GNECalibratorFlowDialog::onCmdCancel(), onCmdCancel(), GNECalibratorRouteDialog::onCmdCancel(), GNERerouterDialog::onCmdCancel(), GNECalibratorDialog::onCmdCancel(), GNERerouterIntervalDialog::onCmdCancel(), and GNEVariableSpeedSignDialog::onCmdCancel().
changeAdditionalDialogHeader()
void GNEAdditionalDialog::changeAdditionalDialogHeader (const std::string & newHeader) protected inherited
change additional dialog header
Definition at line 108 of file GNEAdditionalDialog.cpp.
initChanges()
void GNEAdditionalDialog::initChanges () protected inherited
init a new group of changes that will be do it in dialog
Definition at line 115 of file GNEAdditionalDialog.cpp.
References GNEUndoList::currentCommandGroupSize(), GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myNumberOfChanges, GNEAdditionalDialog::myUndoList, and GNEUndoList::p_begin().
onCmdAccept()
long GNECalibratorVehicleTypeDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
Implements GNEAdditionalDialog.
Definition at line 224 of file GNECalibratorVehicleTypeDialog.cpp.
References GNEAdditionalDialog::acceptChanges(), GNECalibratorVehicleType::getCalibratorParent(), OptionsCont::getOptions(), GNEAttributeCarrier::getTag(), myCalibratorVehicleTypeValid, myEditedCalibratorVehicleType, myInvalidAttr, myUpdatingElement, toString(), and WRITE_WARNING.
onCmdCancel()
long GNECalibratorVehicleTypeDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event after press cancel button
Implements GNEAdditionalDialog.
Definition at line 256 of file GNECalibratorVehicleTypeDialog.cpp.
References GNEAdditionalDialog::cancelChanges().
onCmdReset()
long GNECalibratorVehicleTypeDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event after press reset button
Implements GNEAdditionalDialog.
Definition at line 266 of file GNECalibratorVehicleTypeDialog.cpp.
References GNEAdditionalDialog::resetChanges(), and updateCalibratorVehicleTypeValues().
onCmdSetVariable()
long GNECalibratorVehicleTypeDialog::onCmdSetVariable (FXObject * , FXSelector , void *)
after change a variable of vehicle type
Definition at line 276 of file GNECalibratorVehicleTypeDialog.cpp.
References GNECalibratorVehicleType::getCalibratorParent(), GNEViewNet::getUndoList(), GNEAdditional::getViewNet(), GNECalibratorVehicleType::isValid(), myCalibratorVehicleTypeValid, myComboBoxShape, myComboBoxVClass, myEditedCalibratorVehicleType, myInvalidAttr, myTextFieldAccel, myTextFieldBoardingDuration, myTextFieldCarFollowModel, myTextFieldColor, myTextFieldContainerCapacity, myTextFieldDecel, myTextFieldEmissionClass, myTextFieldFilename, myTextFieldImpatience, myTextFieldLaneChangeModel, myTextFieldLatAlignment, myTextFieldLength, myTextFieldLoadingDuration, myTextFieldMaxSpeed, myTextFieldMaxSpeedLat, myTextFieldMinGap, myTextFieldMinGapLat, myTextFieldPersonCapacity, myTextFieldSigma, myTextFieldSpeedDev, myTextFieldSpeedFactor, myTextFieldTau, myTextFieldVehicleTypeID, myTextFieldWidth, GNECalibratorVehicleType::setAttribute(), setVClassLabelImage(), SUMO_ATTR_ACCEL, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_DECEL, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_NOTHING, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VCLASS, and SUMO_ATTR_WIDTH.
onKeyPress()
long GNEAdditionalDialog::onKeyPress (FXObject * sender, FXSelector sel, void * ptr) inherited
event after press a key
Definition at line 96 of file GNEAdditionalDialog.cpp.
onKeyRelease()
long GNEAdditionalDialog::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr) inherited
event after release a key
Definition at line 102 of file GNEAdditionalDialog.cpp.
openAsModalDialog()
FXint GNEAdditionalDialog::openAsModalDialog (FXuint placement = PLACEMENT_CURSOR) protected inherited
execute dialog as modal
Definition at line 83 of file GNEAdditionalDialog.cpp.
operator=()
GNECalibratorVehicleTypeDialog& GNECalibratorVehicleTypeDialog::operator= (const GNECalibratorVehicleTypeDialog &) private delete
Invalidated assignment operator.
resetChanges()
void GNEAdditionalDialog::resetChanges () protected inherited
reset changes did in this dialog.
Definition at line 141 of file GNEAdditionalDialog.cpp.
References GNEAdditionalDialog::myChangesDescription, GNEAdditionalDialog::myUndoList, GNEUndoList::p_abortLastCommandGroup(), and GNEUndoList::p_begin().
Referenced by GNECalibratorFlowDialog::onCmdReset(), onCmdReset(), GNECalibratorRouteDialog::onCmdReset(), GNERerouterDialog::onCmdReset(), GNECalibratorDialog::onCmdReset(), GNERerouterIntervalDialog::onCmdReset(), and GNEVariableSpeedSignDialog::onCmdReset().
setVClassLabelImage()
void GNECalibratorVehicleTypeDialog::setVClassLabelImage () protected
set VClass texture
Definition at line 559 of file GNECalibratorVehicleTypeDialog.cpp.
References GNECalibratorVehicleType::getAttribute(), GUIIconSubSys::getIcon(), getVehicleClassID(), ICON_VCLASS_ARMY, ICON_VCLASS_AUTHORITY, ICON_VCLASS_BICYCLE, ICON_VCLASS_BUS, ICON_VCLASS_COACH, ICON_VCLASS_CUSTOM1, ICON_VCLASS_CUSTOM2, ICON_VCLASS_DELIVERY, ICON_VCLASS_EMERGENCY, ICON_VCLASS_EVEHICLE, ICON_VCLASS_HOV, ICON_VCLASS_MOPED, ICON_VCLASS_MOTORCYCLE, ICON_VCLASS_PASSENGER, ICON_VCLASS_PEDESTRIAN, ICON_VCLASS_PRIVATE, ICON_VCLASS_RAIL, ICON_VCLASS_RAIL_ELECTRIC, ICON_VCLASS_RAIL_URBAN, ICON_VCLASS_SHIP, ICON_VCLASS_TAXI, ICON_VCLASS_TRAILER, ICON_VCLASS_TRAM, ICON_VCLASS_TRUCK, ICON_VCLASS_VIP, myComboBoxVClassLabelImage, myEditedCalibratorVehicleType, SUMO_ATTR_VCLASS, SVC_ARMY, SVC_AUTHORITY, SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_CUSTOM1, SVC_CUSTOM2, SVC_DELIVERY, SVC_E_VEHICLE, SVC_EMERGENCY, SVC_HOV, SVC_MOPED, SVC_MOTORCYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_PRIVATE, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TAXI, SVC_TRAILER, SVC_TRAM, SVC_TRUCK, SVC_VIP, and toString().
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
updateCalibratorVehicleTypeValues()
void GNECalibratorVehicleTypeDialog::updateCalibratorVehicleTypeValues () protected
update data fields
Definition at line 525 of file GNECalibratorVehicleTypeDialog.cpp.
References GNECalibratorVehicleType::getAttribute(), myComboBoxShape, myComboBoxVClass, myEditedCalibratorVehicleType, myTextFieldAccel, myTextFieldBoardingDuration, myTextFieldCarFollowModel, myTextFieldColor, myTextFieldContainerCapacity, myTextFieldDecel, myTextFieldEmissionClass, myTextFieldFilename, myTextFieldImpatience, myTextFieldLaneChangeModel, myTextFieldLatAlignment, myTextFieldLength, myTextFieldLoadingDuration, myTextFieldMaxSpeed, myTextFieldMaxSpeedLat, myTextFieldMinGap, myTextFieldMinGapLat, myTextFieldPersonCapacity, myTextFieldSigma, myTextFieldSpeedDev, myTextFieldSpeedFactor, myTextFieldTau, myTextFieldVehicleTypeID, myTextFieldWidth, setVClassLabelImage(), SUMO_ATTR_ACCEL, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_CAR_FOLLOW_MODEL, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_DECEL, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_SIGMA, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_TAU, SUMO_ATTR_VCLASS, and SUMO_ATTR_WIDTH.
Referenced by onCmdReset().
Field Documentation
myCalibratorVehicleTypeValid
bool GNECalibratorVehicleTypeDialog::myCalibratorVehicleTypeValid protected
flag to check if current calibrator vehicleType is valid
Definition at line 86 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdAccept(), and onCmdSetVariable().
myComboBoxShape
FXComboBox* GNECalibratorVehicleTypeDialog::myComboBoxShape protected
FXComboBox for Shape.
Definition at line 101 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myComboBoxShapeLabelImage
FXLabel* GNECalibratorVehicleTypeDialog::myComboBoxShapeLabelImage protected
label with image of Shape
Definition at line 104 of file GNECalibratorVehicleTypeDialog.h.
myComboBoxVClass
FXComboBox* GNECalibratorVehicleTypeDialog::myComboBoxVClass protected
FXComboBox for VClass.
Definition at line 95 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myComboBoxVClassLabelImage
FXLabel* GNECalibratorVehicleTypeDialog::myComboBoxVClassLabelImage protected
label with image of VClass
Definition at line 98 of file GNECalibratorVehicleTypeDialog.h.
Referenced by setVClassLabelImage().
myContentFrame
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 86 of file GNEAdditionalDialog.h.
myEditedCalibratorVehicleType
GNECalibratorVehicleType* GNECalibratorVehicleTypeDialog::myEditedCalibratorVehicleType protected
pointer to original calibrator vehicle type
Definition at line 80 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdAccept(), onCmdSetVariable(), setVClassLabelImage(), and updateCalibratorVehicleTypeValues().
myInvalidAttr
SumoXMLAttr GNECalibratorVehicleTypeDialog::myInvalidAttr protected
current sumo attribute invalid
Definition at line 89 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdAccept(), and onCmdSetVariable().
myTextFieldAccel
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldAccel protected
FXTextfield for Accel.
Definition at line 107 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldBoardingDuration
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldBoardingDuration protected
FXTextfield for BoardingDuration.
Definition at line 161 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldCarFollowModel
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldCarFollowModel protected
FXTextfield for CarFollowModel.
Definition at line 152 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldColor
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldColor protected
FXTextfield for Color.
Definition at line 134 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldContainerCapacity
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldContainerCapacity protected
FXTextfield for ContainerCapacity.
Definition at line 158 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldDecel
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldDecel protected
FXTextfield for Decel.
Definition at line 110 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldEmissionClass
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldEmissionClass protected
FXTextfield for EmissionClass.
Definition at line 137 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldFilename
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldFilename protected
FXTextfield for Filename.
Definition at line 143 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldImpatience
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldImpatience protected
FXTextfield for Impatience.
Definition at line 146 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldLaneChangeModel
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldLaneChangeModel protected
FXTextfield for LaneChangeModel.
Definition at line 149 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldLatAlignment
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldLatAlignment protected
FXTextfield for LatAlignment.
Definition at line 167 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldLength
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldLength protected
FXTextfield for Length.
Definition at line 119 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldLoadingDuration
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldLoadingDuration protected
FXTextfield for LoadingDuration.
Definition at line 164 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldMaxSpeed
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldMaxSpeed protected
FXTextfield for MaxSpeed.
Definition at line 125 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldMaxSpeedLat
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldMaxSpeedLat protected
FXTextfield for MaxSpeedLat.
Definition at line 173 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldMinGap
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldMinGap protected
FXTextfield for MinGap.
Definition at line 122 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldMinGapLat
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldMinGapLat protected
FXTextfield for MinGapLat.
Definition at line 170 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldPersonCapacity
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldPersonCapacity protected
FXTextfield for PersonCapacity.
Definition at line 155 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldSigma
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldSigma protected
FXTextfield for Sigma.
Definition at line 113 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldSpeedDev
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldSpeedDev protected
FXTextfield for SpeedDev.
Definition at line 131 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldSpeedFactor
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldSpeedFactor protected
FXTextfield for SpeedFactor.
Definition at line 128 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldTau
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldTau protected
FXTextfield for Tau.
Definition at line 116 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldVehicleTypeID
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldVehicleTypeID protected
FXTextfield for vehicleTypeID.
Definition at line 92 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myTextFieldWidth
FXTextField* GNECalibratorVehicleTypeDialog::myTextFieldWidth protected
FXTextfield for Width.
Definition at line 140 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdSetVariable(), and updateCalibratorVehicleTypeValues().
myUpdatingElement
bool GNECalibratorVehicleTypeDialog::myUpdatingElement protected
flag to indicate if flow are being created or modified
Definition at line 83 of file GNECalibratorVehicleTypeDialog.h.
Referenced by onCmdAccept().
The documentation for this class was generated from the following files:
GNECalibratorVehicleTypeDialog.h
GNECalibratorVehicleTypeDialog.cpp