SUMO - Simulation of Urban MObility: PollutantsInterface Class Reference
PollutantsInterface Class Reference
Helper methods for PHEMlight-based emission computation.
#include <PollutantsInterface.h>
Data Structures
struct Emissions
Storage for collected values of all emission types.
class Helper
abstract superclass for the model helpers
Public Types
enum EmissionType {
CO2, CO, HC, FUEL,
NO_X, PM_X, ELEC
}
Enumerating all emission types, including fuel.
Static Public Member Functions
static double compute (const SUMOEmissionClass c, const EmissionType e, const double v, const double a, const double slope, const std::map< int, double > *param=0)
Returns the amount of the emitted pollutant given the vehicle type and state (in mg/s or ml/s for fuel)
static Emissions computeAll (const SUMOEmissionClass c, const double v, const double a, const double slope, const std::map< int, double > *param=0)
Returns the amount of all emitted pollutants given the vehicle type and state (in mg/s or ml/s for fuel)
static double computeDefault (const SUMOEmissionClass c, const EmissionType e, const double v, const double a, const double slope, const double tt, const std::map< int, double > *param=0)
Returns the amount of emitted pollutant given the vehicle type and default values for the state (in mg)
static const std::vector< SUMOEmissionClass > getAllClasses ()
Checks whether the string describes a known vehicle class.
static std::string getAmitranVehicleClass (const SUMOEmissionClass c)
Returns the vehicle class described by the given emission class.
static SUMOEmissionClass getClass (const SUMOEmissionClass base, const std::string &vClass, const std::string &fuel, const std::string &eClass, const double weight)
Returns the emission class fittig the given parameters.
static SUMOEmissionClass getClassByName (const std::string &eClass, const SUMOVehicleClass vc=SVC_IGNORING)
Checks whether the string describes a known vehicle class.
static const HelpersEnergy & getEnergyHelper ()
static int getEuroClass (const SUMOEmissionClass c)
Returns the Euro norm described by the given emission class.
static std::string getFuel (const SUMOEmissionClass c)
Returns the fuel type of the given emission class.
static double getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope)
Returns the adapted acceleration value, useful for comparing with external PHEMlight references.
static std::string getName (const SUMOEmissionClass c)
Checks whether the string describes a known vehicle class.
static double getWeight (const SUMOEmissionClass c)
Returns a representative weight for the given emission class see http://colombo-fp7.eu/deliverables/COLOMBO_D4.2_ExtendedPHEMSUMO_v1.7.pdf.
static bool isHeavy (const SUMOEmissionClass c)
Checks whether the emission class describes a bus, truck or similar vehicle.
static bool isSilent (const SUMOEmissionClass c)
Checks whether the emission class describes an electric or similar silent vehicle.
Static Public Attributes
static const int HEAVY_BIT = 1 << 15
the bit to set for denoting heavy vehicles
static const int ZERO_EMISSIONS = 0
the first class in each model representing a zero emission vehicle
Static Private Attributes
static HelpersEnergy myEnergyHelper
Instance of EnergyHelper which gets cleaned up automatically.
static HelpersHBEFA myHBEFA2Helper
Instance of HBEFA2Helper which gets cleaned up automatically.
static HelpersHBEFA3 myHBEFA3Helper
Instance of HBEFA3Helper which gets cleaned up automatically.
static Helper * myHelpers []
the known model helpers
static HelpersPHEMlight myPHEMlightHelper
Instance of PHEMlightHelper which gets cleaned up automatically.
Detailed Description
Helper methods for PHEMlight-based emission computation.
Definition at line 58 of file PollutantsInterface.h.
Member Enumeration Documentation
EmissionType
enum PollutantsInterface::EmissionType
Enumerating all emission types, including fuel.
Enumerator
CO2
CO
HC
FUEL
NO_X
PM_X
ELEC
Definition at line 62 of file PollutantsInterface.h.
Member Function Documentation
compute()
double PollutantsInterface::compute (const SUMOEmissionClass c, const EmissionType e, const double v, const double a, const double slope, const std::map< int, double > * param = 0) static
Returns the amount of the emitted pollutant given the vehicle type and state (in mg/s or ml/s for fuel)
Parameters
[in] c The vehicle emission class
[in] e the type of emission (CO, CO2, ...)
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
[in] slope The road's slope at vehicle's position [deg]
Returns
The amount emitted by the given vehicle class when moving with the given velocity and acceleration [mg/s]
Definition at line 135 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::compute(), and myHelpers.
Referenced by ROEdge::buildTimeLines(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHCEmissions(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), and PollutantsInterface::Helper::getWeight().
computeAll()
PollutantsInterface::Emissions PollutantsInterface::computeAll (const SUMOEmissionClass c, const double v, const double a, const double slope, const std::map< int, double > * param = 0) static
Returns the amount of all emitted pollutants given the vehicle type and state (in mg/s or ml/s for fuel)
Parameters
[in] c The vehicle emission class
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
[in] slope The road's slope at vehicle's position [deg]
Returns
The amount emitted by the given vehicle class when moving with the given velocity and acceleration [mg/s]
Definition at line 141 of file PollutantsInterface.cpp.
References CO, CO2, PollutantsInterface::Helper::compute(), ELEC, FUEL, HC, myHelpers, NO_X, and PM_X.
Referenced by TrajectoriesHandler::computeEmissions(), MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), single(), MSEmissionExport::write(), and MSFullExport::writeVehicles().
computeDefault()
double PollutantsInterface::computeDefault (const SUMOEmissionClass c, const EmissionType e, const double v, const double a, const double slope, const double tt, const std::map< int, double > * param = 0) static
Returns the amount of emitted pollutant given the vehicle type and default values for the state (in mg)
Parameters
[in] c The vehicle emission class
[in] e the type of emission (CO, CO2, ...)
[in] v The vehicle's average velocity
[in] a The vehicle's average acceleration
[in] slope The road's slope at vehicle's position [deg]
Definition at line 150 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::compute(), and myHelpers.
Referenced by ROEdge::getEmissionEffort(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
getAllClasses()
const std::vector< SUMOEmissionClass > PollutantsInterface::getAllClasses () static
Checks whether the string describes a known vehicle class.
Parameters
[in] eClass The string describing the vehicle emission class
Returns
whether it describes a valid emission class
Definition at line 76 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::addAllClassesInto(), and myHelpers.
Referenced by main().
getAmitranVehicleClass()
std::string PollutantsInterface::getAmitranVehicleClass (const SUMOEmissionClass c) static
Returns the vehicle class described by the given emission class.
Parameters
[in] c The vehicle emission class
Returns
The Amitran string describing the vehicle class
Definition at line 111 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getAmitranVehicleClass(), and myHelpers.
Referenced by MSAmitranTrajectories::writeVehicle().
getClass()
SUMOEmissionClass PollutantsInterface::getClass (const SUMOEmissionClass base, const std::string & vClass, const std::string & fuel, const std::string & eClass, const double weight) static
Returns the emission class fittig the given parameters.
Parameters
[in] base The base emission class to derive from
[in] vClass The vehicle class description (like "truck")
[in] eClass The emission class description (like "Euro5")
[in] fuel The fuel type (like "Diesel")
[in] weight The weight in kg
Returns
The best fitting emission class related to the base
Definition at line 104 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getClass(), and myHelpers.
Referenced by TrajectoriesHandler::myStartElement().
getClassByName()
SUMOEmissionClass PollutantsInterface::getClassByName (const std::string & eClass, const SUMOVehicleClass vc = SVC_IGNORING) static
Checks whether the string describes a known vehicle class.
Parameters
[in] eClass The string describing the vehicle emission class
Returns
whether it describes a valid emission class
Definition at line 57 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getClassByName(), getName(), and myHelpers.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), ROEdge::buildTimeLines(), main(), libsumo::VehicleType::setEmissionClass(), and SUMOVTypeParameter::SUMOVTypeParameter().
getEnergyHelper()
static const HelpersEnergy& PollutantsInterface::getEnergyHelper () inline static
Definition at line 394 of file PollutantsInterface.h.
References myEnergyHelper.
Referenced by MSDevice_Battery::buildVehicleDevices(), MSDevice_Battery::checkParam(), and MSDevice_Battery::notifyMove().
getEuroClass()
int PollutantsInterface::getEuroClass (const SUMOEmissionClass c) static
Returns the Euro norm described by the given emission class.
Parameters
[in] c The vehicle emission class
Returns
A value between 0 and 6 (inclusive)
Definition at line 123 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getEuroClass(), and myHelpers.
Referenced by MSAmitranTrajectories::writeVehicle().
getFuel()
std::string PollutantsInterface::getFuel (const SUMOEmissionClass c) static
Returns the fuel type of the given emission class.
Parameters
[in] c The vehicle emission class
Returns
"Diesel", "Gasoline", "HybridDiesel", or "HybridGasoline"
Definition at line 117 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getFuel(), and myHelpers.
Referenced by MSAmitranTrajectories::writeVehicle().
getModifiedAccel()
double PollutantsInterface::getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) static
Returns the adapted acceleration value, useful for comparing with external PHEMlight references.
Parameters
[in] c the emission class
[in] v the speed value
[in] a the acceleration value
[in] slope The road's slope at vehicle's position [deg]
Returns
the modified acceleration
Definition at line 157 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getModifiedAccel(), and myHelpers.
Referenced by TrajectoriesHandler::computeEmissions().
getName()
std::string PollutantsInterface::getName (const SUMOEmissionClass c) static
Checks whether the string describes a known vehicle class.
Parameters
[in] eClass The string describing the vehicle emission class
Returns
whether it describes a valid emission class
Definition at line 86 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getClassName(), and myHelpers.
Referenced by getClassByName(), libsumo::VehicleType::getEmissionClass(), libsumo::Vehicle::getEmissionClass(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), main(), MSEmissionExport::write(), SUMOVTypeParameter::write(), MSFullExport::writeVehicles(), and TrajectoriesHandler::writeXMLEmissions().
getWeight()
double PollutantsInterface::getWeight (const SUMOEmissionClass c) static
Returns a representative weight for the given emission class see http://colombo-fp7.eu/deliverables/COLOMBO_D4.2_ExtendedPHEMSUMO_v1.7.pdf.
Parameters
[in] c The vehicle emission class
Returns
the weight in kg if it matters, 0 otherwise
Definition at line 129 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::getWeight(), and myHelpers.
Referenced by MSAmitranTrajectories::writeVehicle().
isHeavy()
bool PollutantsInterface::isHeavy (const SUMOEmissionClass c) static
Checks whether the emission class describes a bus, truck or similar vehicle.
Parameters
[in] c The vehicle emission class
Returns
whether it describes a heavy vehicle
Definition at line 92 of file PollutantsInterface.cpp.
References HEAVY_BIT.
Referenced by HelpersHarmonoise::computeNoise().
isSilent()
bool PollutantsInterface::isSilent (const SUMOEmissionClass c) static
Checks whether the emission class describes an electric or similar silent vehicle.
Parameters
[in] c The vehicle emission class
Returns
whether it describes a silent vehicle
Definition at line 98 of file PollutantsInterface.cpp.
References PollutantsInterface::Helper::isSilent(), and myHelpers.
Referenced by HelpersHarmonoise::computeNoise().
Field Documentation
HEAVY_BIT
const int PollutantsInterface::HEAVY_BIT = 1 << 15 static
the bit to set for denoting heavy vehicles
Definition at line 276 of file PollutantsInterface.h.
Referenced by HelpersPHEMlight::getClassByName(), HelpersHBEFA::HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), isHeavy(), and PollutantsInterface::Helper::isSilent().
myEnergyHelper
HelpersEnergy PollutantsInterface::myEnergyHelper static private
Instance of EnergyHelper which gets cleaned up automatically.
Definition at line 406 of file PollutantsInterface.h.
Referenced by getEnergyHelper().
myHBEFA2Helper
HelpersHBEFA PollutantsInterface::myHBEFA2Helper static private
Instance of HBEFA2Helper which gets cleaned up automatically.
Definition at line 400 of file PollutantsInterface.h.
myHBEFA3Helper
HelpersHBEFA3 PollutantsInterface::myHBEFA3Helper static private
Instance of HBEFA3Helper which gets cleaned up automatically.
Definition at line 402 of file PollutantsInterface.h.
myHelpers
PollutantsInterface::Helper * PollutantsInterface::myHelpers static private
Initial value:
= { &PollutantsInterface::myHBEFA2Helper, &PollutantsInterface::myHBEFA3Helper,
                                                                  &PollutantsInterface::myPHEMlightHelper, &PollutantsInterface::myEnergyHelper
                                                                }
the known model helpers
Definition at line 408 of file PollutantsInterface.h.
Referenced by compute(), computeAll(), computeDefault(), getAllClasses(), getAmitranVehicleClass(), getClass(), getClassByName(), getEuroClass(), getFuel(), getModifiedAccel(), getName(), getWeight(), and isSilent().
myPHEMlightHelper
HelpersPHEMlight PollutantsInterface::myPHEMlightHelper static private
Instance of PHEMlightHelper which gets cleaned up automatically.
Definition at line 404 of file PollutantsInterface.h.
ZERO_EMISSIONS
const int PollutantsInterface::ZERO_EMISSIONS = 0 static
the first class in each model representing a zero emission vehicle
Definition at line 273 of file PollutantsInterface.h.
Referenced by HelpersHBEFA::compute(), HelpersEnergy::HelpersEnergy(), and HelpersHBEFA::HelpersHBEFA().
The documentation for this class was generated from the following files:
PollutantsInterface.h
PollutantsInterface.cpp