SUMO - Simulation of Urban MObility: GUITriggeredRerouter::GUIManip_TriggeredRerouter Class Reference
GUITriggeredRerouter::GUIManip_TriggeredRerouter Class Reference
#include <GUITriggeredRerouter.h>
Public Types
enum {
MID_USER_DEF = FXDialogBox::ID_LAST, MID_PRE_DEF, MID_OPTION, MID_CLOSE,
ID_LAST
}
Public Member Functions
GUIManip_TriggeredRerouter (GUIMainWindow &app, const std::string &name, GUITriggeredRerouter &o, int xpos, int ypos)
Constructor.
long onCmdChangeOption (FXObject *, FXSelector, void *)
long onCmdClose (FXObject *, FXSelector, void *)
long onCmdOverride (FXObject *, FXSelector, void *)
long onCmdUserDef (FXObject *, FXSelector, void *)
long onUpdUserDef (FXObject *, FXSelector, void *)
virtual ~GUIManip_TriggeredRerouter ()
Destructor.
Protected Member Functions
GUIManip_TriggeredRerouter ()
Private Attributes
FXDataTarget myChosenTarget
FXint myChosenValue
GUITriggeredRerouter * myObject
GUIMainWindow * myParent
double myUsageProbability
FXRealSpinDial * myUsageProbabilityDial
FXDataTarget myUsageProbabilityTarget
Detailed Description
Definition at line 227 of file GUITriggeredRerouter.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MID_USER_DEF
MID_PRE_DEF
MID_OPTION
MID_CLOSE
ID_LAST
Definition at line 230 of file GUITriggeredRerouter.h.
Constructor & Destructor Documentation
GUIManip_TriggeredRerouter() [1/2]
GUITriggeredRerouter::GUIManip_TriggeredRerouter::GUIManip_TriggeredRerouter (GUIMainWindow & app, const std::string & name, GUITriggeredRerouter & o, int xpos, int ypos)
Constructor.
Definition at line 90 of file GUITriggeredRerouter.cpp.
References MID_CLOSE.
~GUIManip_TriggeredRerouter()
GUITriggeredRerouter::GUIManip_TriggeredRerouter::~GUIManip_TriggeredRerouter () virtual
Destructor.
Definition at line 145 of file GUITriggeredRerouter.cpp.
GUIManip_TriggeredRerouter() [2/2]
GUITriggeredRerouter::GUIManip_TriggeredRerouter::GUIManip_TriggeredRerouter () inline protected
Definition at line 267 of file GUITriggeredRerouter.h.
Member Function Documentation
onCmdChangeOption()
long GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption (FXObject * , FXSelector , void *)
Definition at line 176 of file GUITriggeredRerouter.cpp.
References myChosenValue, myObject, myParent, myUsageProbability, MSTriggeredRerouter::setUserMode(), MSTriggeredRerouter::setUserUsageProbability(), and GUIMainWindow::updateChildren().
onCmdClose()
long GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdClose (FXObject * , FXSelector , void *)
Definition at line 149 of file GUITriggeredRerouter.cpp.
onCmdOverride()
long GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdOverride (FXObject * , FXSelector , void *)
onCmdUserDef()
long GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef (FXObject * , FXSelector , void *)
Definition at line 156 of file GUITriggeredRerouter.cpp.
References FX::FXRealSpinDial::getValue(), myObject, myParent, myUsageProbability, myUsageProbabilityDial, MSTriggeredRerouter::setUserMode(), MSTriggeredRerouter::setUserUsageProbability(), and GUIMainWindow::updateChildren().
onUpdUserDef()
long GUITriggeredRerouter::GUIManip_TriggeredRerouter::onUpdUserDef (FXObject * sender, FXSelector , void * ptr)
Definition at line 166 of file GUITriggeredRerouter.cpp.
References myChosenValue, myParent, and GUIMainWindow::updateChildren().
Field Documentation
myChosenTarget
FXDataTarget GUITriggeredRerouter::GUIManip_TriggeredRerouter::myChosenTarget private
Definition at line 256 of file GUITriggeredRerouter.h.
myChosenValue
FXint GUITriggeredRerouter::GUIManip_TriggeredRerouter::myChosenValue private
Definition at line 254 of file GUITriggeredRerouter.h.
Referenced by onCmdChangeOption(), and onUpdUserDef().
myObject
GUITriggeredRerouter* GUITriggeredRerouter::GUIManip_TriggeredRerouter::myObject private
Definition at line 264 of file GUITriggeredRerouter.h.
Referenced by onCmdChangeOption(), and onCmdUserDef().
myParent
GUIMainWindow* GUITriggeredRerouter::GUIManip_TriggeredRerouter::myParent private
Definition at line 252 of file GUITriggeredRerouter.h.
Referenced by onCmdChangeOption(), onCmdUserDef(), and onUpdUserDef().
myUsageProbability
double GUITriggeredRerouter::GUIManip_TriggeredRerouter::myUsageProbability private
Definition at line 258 of file GUITriggeredRerouter.h.
Referenced by onCmdChangeOption(), and onCmdUserDef().
myUsageProbabilityDial
FXRealSpinDial* GUITriggeredRerouter::GUIManip_TriggeredRerouter::myUsageProbabilityDial private
Definition at line 260 of file GUITriggeredRerouter.h.
Referenced by onCmdUserDef().
myUsageProbabilityTarget
FXDataTarget GUITriggeredRerouter::GUIManip_TriggeredRerouter::myUsageProbabilityTarget private
Definition at line 262 of file GUITriggeredRerouter.h.
The documentation for this class was generated from the following files:
GUITriggeredRerouter.h
GUITriggeredRerouter.cpp