SUMO - Simulation of Urban MObility: ROMAAssignments Class Reference
ROMAAssignments Class Reference
assignment methods
#include <ROMAAssignments.h>
Public Member Functions
double capacityConstraintFunction (const ROEdge *edge, const double flow) const
ROVehicle * getDefaultVehicle ()
void incremental (const int numIter, const bool verbose)
void resetFlows ()
ROMAAssignments (const SUMOTime begin, const SUMOTime end, const bool additiveTraffic, const double adaptionFactor, RONet &net, ODMatrix &matrix, SUMOAbstractRouter< ROEdge, ROVehicle > &router)
Constructor.
void sue (const int maxOuterIteration, const int maxInnerIteration, const int kPaths, const double penalty, const double tolerance, const std::string routeChoiceMethod)
void ue ()
~ROMAAssignments ()
Destructor.
Static Public Member Functions
static double getCapacity (const ROEdge *edge)
static double getPenalizedEffort (const ROEdge *const e, const ROVehicle *const v, double t)
Returns the effort to pass an edge including penalties.
static double getPenalizedTT (const ROEdge *const e, const ROVehicle *const v, double t)
Returns the traveltime on an edge including penalties.
static double getTravelTime (const ROEdge *const e, const ROVehicle *const v, double t)
Returns the traveltime on an edge without penalties.
Private Member Functions
bool addRoute (ConstROEdgeVector &edges, std::vector< RORoute *> &paths, std::string routeId, double prob)
add a route and check for duplicates
void getKPaths (const int kPaths, const double penalty)
get the k shortest paths
ROMAAssignments & operator= (const ROMAAssignments &src)
Invalidated assignment operator.
Private Attributes
const double myAdaptionFactor
const bool myAdditiveTraffic
const SUMOTime myBegin
ROVehicle * myDefaultVehicle
const SUMOTime myEnd
ODMatrix & myMatrix
RONet & myNet
SUMOAbstractRouter< ROEdge, ROVehicle > & myRouter
Static Private Attributes
static std::map< const ROEdge *const, double > myPenalties
Detailed Description
assignment methods
Definition at line 57 of file ROMAAssignments.h.
Constructor & Destructor Documentation
ROMAAssignments()
ROMAAssignments::ROMAAssignments (const SUMOTime begin, const SUMOTime end, const bool additiveTraffic, const double adaptionFactor, RONet & net, ODMatrix & matrix, SUMOAbstractRouter< ROEdge, ROVehicle > & router)
Constructor.
Definition at line 56 of file ROMAAssignments.cpp.
References DEFAULT_VTYPE_ID, RONet::getVehicleTypeSecure(), and myDefaultVehicle.
~ROMAAssignments()
ROMAAssignments::~ROMAAssignments ()
Destructor.
Definition at line 64 of file ROMAAssignments.cpp.
References myDefaultVehicle.
Member Function Documentation
addRoute()
bool ROMAAssignments::addRoute (ConstROEdgeVector & edges, std::vector< RORoute *> & paths, std::string routeId, double prob) private
add a route and check for duplicates
Definition at line 174 of file ROMAAssignments.cpp.
Referenced by getDefaultVehicle(), getKPaths(), incremental(), and sue().
capacityConstraintFunction()
double ROMAAssignments::capacityConstraintFunction (const ROEdge * edge, const double flow) const
Definition at line 122 of file ROMAAssignments.cpp.
References getCapacity(), ROEdge::getLength(), ROEdge::getNumLanes(), ROEdge::getPriority(), ROEdge::getSpeedLimit(), and ROEdge::isTazConnector().
Referenced by getDefaultVehicle(), incremental(), and sue().
getCapacity()
double ROMAAssignments::getCapacity (const ROEdge * edge) static
Definition at line 70 of file ROMAAssignments.cpp.
References ROEdge::getNumLanes(), ROEdge::getPriority(), ROEdge::getSpeedLimit(), and ROEdge::isTazConnector().
Referenced by capacityConstraintFunction(), getDefaultVehicle(), and writeInterval().
getDefaultVehicle()
ROVehicle* ROMAAssignments::getDefaultVehicle () inline
Definition at line 66 of file ROMAAssignments.h.
References addRoute(), capacityConstraintFunction(), getCapacity(), getKPaths(), getPenalizedEffort(), getPenalizedTT(), getTravelTime(), incremental(), myDefaultVehicle, resetFlows(), sue(), and ue().
getKPaths()
void ROMAAssignments::getKPaths (const int kPaths, const double penalty) private
get the k shortest paths
Definition at line 192 of file ROMAAssignments.cpp.
References addRoute(), SUMOAbstractRouter< E, V >::compute(), ODCell::destination, ODMatrix::getCells(), RONet::getEdge(), myDefaultVehicle, myMatrix, myNet, myPenalties, myRouter, ODCell::origin, ODCell::pathsVector, and toString().
Referenced by getDefaultVehicle(), and sue().
getPenalizedEffort()
double ROMAAssignments::getPenalizedEffort (const ROEdge *const e, const ROVehicle *const v, double t) static
Returns the effort to pass an edge including penalties.
This method is given to the used router in order to obtain the efforts to pass an edge from the internal edge weights container.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The (default) vehicle that is routed
[in] t The time for which the effort shall be returned
Returns
The effort (time to pass in this case) for an edge
See also
DijkstraRouter_ByProxi
Definition at line 425 of file ROMAAssignments.cpp.
References ROEdge::getEffort(), and myPenalties.
Referenced by computeRoutes(), and getDefaultVehicle().
getPenalizedTT()
double ROMAAssignments::getPenalizedTT (const ROEdge *const e, const ROVehicle *const v, double t) static
Returns the traveltime on an edge including penalties.
This method is given to the used router in order to obtain the efforts to pass an edge from the internal edge weights container.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The (default) vehicle that is routed
[in] t The time for which the effort shall be returned
Returns
The effort (time to pass in this case) for an edge
See also
DijkstraRouter_ByProxi
Definition at line 432 of file ROMAAssignments.cpp.
References ROEdge::getTravelTime(), and myPenalties.
Referenced by computeRoutes(), and getDefaultVehicle().
getTravelTime()
double ROMAAssignments::getTravelTime (const ROEdge *const e, const ROVehicle *const v, double t) static
Returns the traveltime on an edge without penalties.
This method is given to the used router in order to obtain the efforts to pass an edge from the internal edge weights container.
Parameters
[in] e The edge for which the effort to be passed shall be returned
[in] v The (default) vehicle that is routed
[in] t The time for which the effort shall be returned
Returns
The effort (time to pass in this case) for an edge
See also
DijkstraRouter_ByProxi
Definition at line 439 of file ROMAAssignments.cpp.
References ROEdge::getTravelTime(), myBegin, and toString().
Referenced by computeRoutes(), and getDefaultVehicle().
incremental()
void ROMAAssignments::incremental (const int numIter, const bool verbose)
Definition at line 221 of file ROMAAssignments.cpp.
References addRoute(), ROEdge::addTravelTime(), ODCell::begin, NamedObjectCont< T >::begin(), capacityConstraintFunction(), SUMOAbstractRouter< E, V >::compute(), ODCell::destination, ODCell::end, NamedObjectCont< T >::end(), ODMatrix::getCells(), RONet::getEdge(), RONet::getEdgeMap(), ROMAEdge::getFlow(), ROEdge::getTravelTime(), ROEdge::hasLoadedTravelTime(), myAdaptionFactor, myAdditiveTraffic, myBegin, myDefaultVehicle, myEnd, myMatrix, myNet, myRouter, ODCell::origin, ODCell::pathsVector, SUMOAbstractRouter< E, V >::setBulkMode(), ROMAEdge::setFlow(), STEPS2TIME, time2string(), toString(), ODCell::vehicleNumber, and WRITE_MESSAGE.
Referenced by getDefaultVehicle().
operator=()
ROMAAssignments& ROMAAssignments::operator= (const ROMAAssignments & src) private
Invalidated assignment operator.
resetFlows()
void ROMAAssignments::resetFlows ()
Definition at line 210 of file ROMAAssignments.cpp.
References NamedObjectCont< T >::begin(), NamedObjectCont< T >::end(), ODMatrix::getCells(), RONet::getEdgeMap(), MIN2(), myBegin, myEnd, myMatrix, myNet, ROMAEdge::setFlow(), ROMAEdge::setHelpFlow(), and STEPS2TIME.
Referenced by computeRoutes(), and getDefaultVehicle().
sue()
void ROMAAssignments::sue (const int maxOuterIteration, const int maxInnerIteration, const int kPaths, const double penalty, const double tolerance, const std::string routeChoiceMethod)
Definition at line 319 of file ROMAAssignments.cpp.
References addRoute(), ROEdge::addTravelTime(), ODCell::begin, NamedObjectCont< T >::begin(), capacityConstraintFunction(), SUMOAbstractRouter< E, V >::compute(), ODCell::destination, ODCell::end, NamedObjectCont< T >::end(), RouteCostCalculator< R, E, V >::getCalculator(), ODMatrix::getCells(), RONet::getEdge(), RONet::getEdgeMap(), RORoute::getEdgeVector(), ROMAEdge::getFlow(), ROMAEdge::getHelpFlow(), getKPaths(), RORoute::getProbability(), myAdditiveTraffic, myBegin, myDefaultVehicle, myEnd, myMatrix, myNet, myRouter, ODCell::origin, ODCell::pathsVector, SUMOAbstractRouter< E, V >::recomputeCosts(), RORoute::setCosts(), ROMAEdge::setFlow(), ROMAEdge::setHelpFlow(), RORoute::setProbability(), STEPS2TIME, toString(), and ODCell::vehicleNumber.
Referenced by getDefaultVehicle().
ue()
void ROMAAssignments::ue ()
Referenced by getDefaultVehicle().
Field Documentation
myAdaptionFactor
const double ROMAAssignments::myAdaptionFactor private
Definition at line 138 of file ROMAAssignments.h.
Referenced by incremental().
myAdditiveTraffic
const bool ROMAAssignments::myAdditiveTraffic private
Definition at line 137 of file ROMAAssignments.h.
Referenced by incremental(), and sue().
myBegin
const SUMOTime ROMAAssignments::myBegin private
Definition at line 135 of file ROMAAssignments.h.
Referenced by getTravelTime(), incremental(), resetFlows(), and sue().
myDefaultVehicle
ROVehicle* ROMAAssignments::myDefaultVehicle private
Definition at line 143 of file ROMAAssignments.h.
Referenced by getDefaultVehicle(), getKPaths(), incremental(), ROMAAssignments(), sue(), and ~ROMAAssignments().
myEnd
const SUMOTime ROMAAssignments::myEnd private
Definition at line 136 of file ROMAAssignments.h.
Referenced by incremental(), resetFlows(), and sue().
myMatrix
ODMatrix& ROMAAssignments::myMatrix private
Definition at line 140 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), resetFlows(), and sue().
myNet
RONet& ROMAAssignments::myNet private
Definition at line 139 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), resetFlows(), and sue().
myPenalties
std::map< const ROEdge *const, double > ROMAAssignments::myPenalties static private
Definition at line 142 of file ROMAAssignments.h.
Referenced by getKPaths(), getPenalizedEffort(), and getPenalizedTT().
myRouter
SUMOAbstractRouter<ROEdge, ROVehicle>& ROMAAssignments::myRouter private
Definition at line 141 of file ROMAAssignments.h.
Referenced by getKPaths(), incremental(), and sue().
The documentation for this class was generated from the following files:
ROMAAssignments.h
ROMAAssignments.cpp