SUMO - Simulation of Urban MObility: MFXEventQue< T > Class Template Reference
MFXEventQue< T > Class Template Reference
#include <MFXEventQue.h>
Public Member Functions
void add (T what)
bool empty ()
MFXEventQue ()
void pop ()
int size ()
T top ()
~MFXEventQue ()
Private Attributes
std::list< T > myItems
MFXMutex myMutex
Detailed Description
template<class T>
class MFXEventQue< T >
Definition at line 38 of file MFXEventQue.h.
Constructor & Destructor Documentation
MFXEventQue()
template<class T> MFXEventQue< T >::MFXEventQue () inline
Definition at line 40 of file MFXEventQue.h.
~MFXEventQue()
template<class T> MFXEventQue< T >::~MFXEventQue () inline
Definition at line 41 of file MFXEventQue.h.
Member Function Documentation
add()
template<class T> void MFXEventQue< T >::add (T what) inline
Definition at line 58 of file MFXEventQue.h.
Referenced by GUIRunThread::makeStep(), GUILoadThread::retrieveMessage(), GNELoadThread::retrieveMessage(), GUIRunThread::retrieveMessage(), GUILoadThread::run(), GUIApplicationWindow::sendBlockingEvent(), GUILoadThread::submitEndAndCleanup(), and GNELoadThread::submitEndAndCleanup().
empty()
template<class T> bool MFXEventQue< T >::empty () inline
Definition at line 71 of file MFXEventQue.h.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GNEApplicationWindow::~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
pop()
template<class T> void MFXEventQue< T >::pop () inline
Definition at line 52 of file MFXEventQue.h.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GNEApplicationWindow::~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
size()
template<class T> int MFXEventQue< T >::size () inline
Definition at line 64 of file MFXEventQue.h.
Referenced by MFXEventQue< GUIEvent *>::top().
top()
template<class T> T MFXEventQue< T >::top () inline
Definition at line 43 of file MFXEventQue.h.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GNEApplicationWindow::~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
Field Documentation
myItems
template<class T> std::list<T> MFXEventQue< T >::myItems private
Definition at line 80 of file MFXEventQue.h.
Referenced by MFXEventQue< GUIEvent *>::add(), MFXEventQue< GUIEvent *>::empty(), MFXEventQue< GUIEvent *>::pop(), MFXEventQue< GUIEvent *>::size(), and MFXEventQue< GUIEvent *>::top().
myMutex
template<class T> MFXMutex MFXEventQue< T >::myMutex private
Definition at line 79 of file MFXEventQue.h.
Referenced by MFXEventQue< GUIEvent *>::add(), MFXEventQue< GUIEvent *>::empty(), MFXEventQue< GUIEvent *>::pop(), MFXEventQue< GUIEvent *>::size(), and MFXEventQue< GUIEvent *>::top().
The documentation for this class was generated from the following file:
MFXEventQue.h