SUMO - Simulation of Urban MObility: ROPerson::TripItem Class Reference
ROPerson::TripItem Class Reference abstract
A TripItem is part of a trip, e.g., go from here to here by car.
#include <ROPerson.h>
Public Member Functions
virtual const ROEdge * getDestination () const =0
virtual const ROEdge * getOrigin () const =0
virtual void saveAsXML (OutputDevice &os, const bool extended) const =0
TripItem (const double _cost)
virtual ~TripItem ()
Destructor.
Protected Attributes
double cost
Detailed Description
A TripItem is part of a trip, e.g., go from here to here by car.
Definition at line 141 of file ROPerson.h.
Constructor & Destructor Documentation
TripItem()
ROPerson::TripItem::TripItem (const double _cost) inline
Definition at line 143 of file ROPerson.h.
~TripItem()
virtual ROPerson::TripItem::~TripItem () inline virtual
Destructor.
Definition at line 147 of file ROPerson.h.
References ROPerson::PlanItem::getDestination(), ROPerson::PlanItem::getOrigin(), and ROPerson::PlanItem::saveAsXML().
Member Function Documentation
getDestination()
virtual const ROEdge* ROPerson::TripItem::getDestination () const pure virtual
Implemented in ROPerson::Walk, and ROPerson::Ride.
getOrigin()
virtual const ROEdge* ROPerson::TripItem::getOrigin () const pure virtual
Implemented in ROPerson::Walk, and ROPerson::Ride.
saveAsXML()
virtual void ROPerson::TripItem::saveAsXML (OutputDevice & os, const bool extended) const pure virtual
Implemented in ROPerson::Walk, and ROPerson::Ride.
Field Documentation
cost
double ROPerson::TripItem::cost protected
Definition at line 153 of file ROPerson.h.
The documentation for this class was generated from the following file:
ROPerson.h