SUMO - Simulation of Urban MObility: FXEX::FXSevenSegment Class Reference
FXEX::FXSevenSegment Class Reference
#include <FXSevenSegment.h>
Public Member Functions
FXSevenSegment (FXComposite *p, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=FRAME_NONE, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
create a seven segment display
FXColor getBgColor () const
virtual FXint getDefaultHeight ()
Return minimum height.
virtual FXint getDefaultWidth ()
Return minimum width.
FXColor getFgColor () const
FXint getGroove () const
FXint getHorizontal () const
FXchar getText () const
get the text on the display
FXint getThickness () const
FXint getVertical () const
virtual void load (FXStream &store)
load resources
long onCmdGetIntValue (FXObject *, FXSelector, void *)
long onCmdGetStringValue (FXObject *, FXSelector, void *)
long onCmdSetIntValue (FXObject *, FXSelector, void *)
long onCmdSetStringValue (FXObject *, FXSelector, void *)
long onCmdSetValue (FXObject *, FXSelector, void *)
long onPaint (FXObject *, FXSelector, void *)
long onQueryHelp (FXObject *, FXSelector, void *)
long onQueryTip (FXObject *, FXSelector, void *)
virtual void save (FXStream &store) const
save resources
void setBgColor (const FXColor clr)
get/set background color
void setFgColor (const FXColor clr)
get/set foreground color
void setGroove (const FXint width)
get/set groove thickness
void setHorizontal (const FXint len)
get/set horizontal segment length
void setText (const FXchar val)
set the text on the display
void setThickness (const FXint width)
get/set segment thickness
void setVertical (const FXint len)
get/set vertical segment length
virtual ~FXSevenSegment ()
dtor
Protected Member Functions
void drawBottomSegment (FXDCWindow &dc, FXshort x, FXshort y)
virtual void drawFigure (FXDCWindow &dc, FXchar figure)
void drawLeftBottomSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawLeftTopSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawMiddleSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawRightBottomSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawRightTopSegment (FXDCWindow &dc, FXshort x, FXshort y)
void drawSegments (FXDCWindow &dc, FXbool s1, FXbool s2, FXbool s3, FXbool s4, FXbool s5, FXbool s6, FXbool s7)
void drawTopSegment (FXDCWindow &dc, FXshort x, FXshort y)
FXSevenSegment ()
Private Member Functions
void checkSize ()
Private Attributes
FXColor bgcolor
FXColor fgcolor
FXshort groove
FXshort hsl
FXshort st
FXchar value
FXshort vsl
Detailed Description
Seven-segment (eg LCD/watch style) widget
Definition at line 46 of file FXSevenSegment.h.
Constructor & Destructor Documentation
FXSevenSegment() [1/2]
FXEX::FXSevenSegment::FXSevenSegment () inline protected
Definition at line 63 of file FXSevenSegment.h.
FXSevenSegment() [2/2]
FXEX::FXSevenSegment::FXSevenSegment (FXComposite * p, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = FRAME_NONE, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD)
create a seven segment display
Definition at line 72 of file FXSevenSegment.cpp.
~FXSevenSegment()
virtual FXEX::FXSevenSegment::~FXSevenSegment () inline virtual
dtor
Definition at line 151 of file FXSevenSegment.h.
Member Function Documentation
checkSize()
void FXEX::FXSevenSegment::checkSize () private
Definition at line 377 of file FXSevenSegment.cpp.
drawBottomSegment()
void FXEX::FXSevenSegment::drawBottomSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 558 of file FXSevenSegment.cpp.
drawFigure()
void FXEX::FXSevenSegment::drawFigure (FXDCWindow & dc, FXchar figure) protected virtual
Definition at line 219 of file FXSevenSegment.cpp.
drawLeftBottomSegment()
void FXEX::FXSevenSegment::drawLeftBottomSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 532 of file FXSevenSegment.cpp.
drawLeftTopSegment()
void FXEX::FXSevenSegment::drawLeftTopSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 489 of file FXSevenSegment.cpp.
drawMiddleSegment()
void FXEX::FXSevenSegment::drawMiddleSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 515 of file FXSevenSegment.cpp.
drawRightBottomSegment()
void FXEX::FXSevenSegment::drawRightBottomSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 545 of file FXSevenSegment.cpp.
drawRightTopSegment()
void FXEX::FXSevenSegment::drawRightTopSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 502 of file FXSevenSegment.cpp.
drawSegments()
void FXEX::FXSevenSegment::drawSegments (FXDCWindow & dc, FXbool s1, FXbool s2, FXbool s3, FXbool s4, FXbool s5, FXbool s6, FXbool s7) protected
Definition at line 408 of file FXSevenSegment.cpp.
drawTopSegment()
void FXEX::FXSevenSegment::drawTopSegment (FXDCWindow & dc, FXshort x, FXshort y) protected
Definition at line 476 of file FXSevenSegment.cpp.
getBgColor()
FXColor FXEX::FXSevenSegment::getBgColor () const inline
Definition at line 110 of file FXSevenSegment.h.
Referenced by FXEX::FXLCDLabel::getBgColor(), FXEX::FXLCDLabel::onPaint(), and FXEX::FXLCDLabel::setBgColor().
getDefaultHeight()
FXint FXEX::FXSevenSegment::getDefaultHeight () virtual
Return minimum height.
Definition at line 84 of file FXSevenSegment.cpp.
getDefaultWidth()
FXint FXEX::FXSevenSegment::getDefaultWidth () virtual
Return minimum width.
Definition at line 79 of file FXSevenSegment.cpp.
getFgColor()
FXColor FXEX::FXSevenSegment::getFgColor () const inline
Definition at line 104 of file FXSevenSegment.h.
Referenced by FXEX::FXLCDLabel::getFgColor(), FXEX::FXLCDLabel::onPaint(), and FXEX::FXLCDLabel::setFgColor().
getGroove()
FXint FXEX::FXSevenSegment::getGroove () const inline
Definition at line 134 of file FXSevenSegment.h.
Referenced by FXEX::FXLCDLabel::getGroove(), and FXEX::FXLCDLabel::setGroove().
getHorizontal()
FXint FXEX::FXSevenSegment::getHorizontal () const inline
Definition at line 116 of file FXSevenSegment.h.
Referenced by FXEX::FXLCDLabel::getHorizontal(), and FXEX::FXLCDLabel::setHorizontal().
getText()
FXchar FXEX::FXSevenSegment::getText () const inline
get the text on the display
Definition at line 98 of file FXSevenSegment.h.
getThickness()
FXint FXEX::FXSevenSegment::getThickness () const inline
Definition at line 128 of file FXSevenSegment.h.
Referenced by FXEX::FXLCDLabel::getThickness(), and FXEX::FXLCDLabel::setThickness().
getVertical()
FXint FXEX::FXSevenSegment::getVertical () const inline
Definition at line 122 of file FXSevenSegment.h.
Referenced by FXEX::FXLCDLabel::getVertical(), and FXEX::FXLCDLabel::setVertical().
load()
void FXEX::FXSevenSegment::load (FXStream & store) virtual
load resources
Definition at line 582 of file FXSevenSegment.cpp.
onCmdGetIntValue()
long FXEX::FXSevenSegment::onCmdGetIntValue (FXObject * sender, FXSelector , void *)
Definition at line 177 of file FXSevenSegment.cpp.
References ASCII_ZERO.
onCmdGetStringValue()
long FXEX::FXSevenSegment::onCmdGetStringValue (FXObject * sender, FXSelector , void *)
Definition at line 203 of file FXSevenSegment.cpp.
onCmdSetIntValue()
long FXEX::FXSevenSegment::onCmdSetIntValue (FXObject * , FXSelector , void * ptr)
Definition at line 190 of file FXSevenSegment.cpp.
References ASCII_ZERO.
onCmdSetStringValue()
long FXEX::FXSevenSegment::onCmdSetStringValue (FXObject * , FXSelector , void * ptr)
Definition at line 210 of file FXSevenSegment.cpp.
onCmdSetValue()
long FXEX::FXSevenSegment::onCmdSetValue (FXObject * , FXSelector , void * ptr)
Definition at line 168 of file FXSevenSegment.cpp.
onPaint()
long FXEX::FXSevenSegment::onPaint (FXObject * , FXSelector , void * ptr)
Definition at line 156 of file FXSevenSegment.cpp.
onQueryHelp()
long FXEX::FXSevenSegment::onQueryHelp (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 602 of file FXSevenSegment.cpp.
onQueryTip()
long FXEX::FXSevenSegment::onQueryTip (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 594 of file FXSevenSegment.cpp.
save()
void FXEX::FXSevenSegment::save (FXStream & store) const virtual
save resources
Definition at line 571 of file FXSevenSegment.cpp.
setBgColor()
void FXEX::FXSevenSegment::setBgColor (const FXColor clr)
get/set background color
Definition at line 107 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::setBgColor().
setFgColor()
void FXEX::FXSevenSegment::setFgColor (const FXColor clr)
get/set foreground color
Definition at line 98 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::setFgColor().
setGroove()
void FXEX::FXSevenSegment::setGroove (const FXint width)
get/set groove thickness
Definition at line 146 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setGroove().
setHorizontal()
void FXEX::FXSevenSegment::setHorizontal (const FXint len)
get/set horizontal segment length
Definition at line 116 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setHorizontal().
setText()
void FXEX::FXSevenSegment::setText (const FXchar val)
set the text on the display
Definition at line 89 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::drawString().
setThickness()
void FXEX::FXSevenSegment::setThickness (const FXint width)
get/set segment thickness
Definition at line 136 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setThickness().
setVertical()
void FXEX::FXSevenSegment::setVertical (const FXint len)
get/set vertical segment length
Definition at line 126 of file FXSevenSegment.cpp.
Referenced by FXEX::FXLCDLabel::drawString(), and FXEX::FXLCDLabel::setVertical().
Field Documentation
bgcolor
FXColor FXEX::FXSevenSegment::bgcolor private
Definition at line 53 of file FXSevenSegment.h.
fgcolor
FXColor FXEX::FXSevenSegment::fgcolor private
Definition at line 52 of file FXSevenSegment.h.
groove
FXshort FXEX::FXSevenSegment::groove private
Definition at line 57 of file FXSevenSegment.h.
hsl
FXshort FXEX::FXSevenSegment::hsl private
Definition at line 54 of file FXSevenSegment.h.
st
FXshort FXEX::FXSevenSegment::st private
Definition at line 56 of file FXSevenSegment.h.
value
FXchar FXEX::FXSevenSegment::value private
Definition at line 51 of file FXSevenSegment.h.
vsl
FXshort FXEX::FXSevenSegment::vsl private
Definition at line 55 of file FXSevenSegment.h.
The documentation for this class was generated from the following files:
FXSevenSegment.h
FXSevenSegment.cpp