SUMO - Simulation of Urban MObility: HelpersHBEFA Class Reference
HelpersHBEFA Class Reference
Helper methods for HBEFA-based emission computation.
#include <HelpersHBEFA.h>
Public Member Functions
void addAllClassesInto (std::vector< SUMOEmissionClass > &list) const
Add all known emission classes of this model to the given container.
double compute (const SUMOEmissionClass c, const PollutantsInterface::EmissionType e, const double v, const double a, const double slope, const std::map< int, double > *param) const
Computes the emitted pollutant amount using the given speed and acceleration.
virtual SUMOEmissionClass getClassByName (const std::string &eClass, const SUMOVehicleClass vc)
Returns the emission class associated with the given name, aliases are possible If this method is asked for the "unknown" class it should return the default (possibly depending on the given vehicle class). The class name is case insensitive.
const std::string getClassName (const SUMOEmissionClass c) const
Returns the complete name of the emission class including the model.
virtual double getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) const
Returns the adapted acceleration value, useful for comparing with external PHEMlight references. Default implementation returns always the input accel.
const std::string & getName () const
Returns the name of the model.
HelpersHBEFA ()
Constructor (initializes myEmissionClassStrings)
virtual bool isSilent (const SUMOEmissionClass c)
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Methods for Amitran interfaces
virtual SUMOEmissionClass getClass (const SUMOEmissionClass base, const std::string &vClass, const std::string &fuel, const std::string &eClass, const double weight) const
Returns the emission class described by the given parameters. The base is used to determine the model to use and as default return values. Default implementation returns always base.
virtual std::string getAmitranVehicleClass (const SUMOEmissionClass c) const
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...) Default implementation returns always "Passenger".
virtual std::string getFuel (const SUMOEmissionClass c) const
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...) Default implementation returns always "Gasoline".
virtual int getEuroClass (const SUMOEmissionClass c) const
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6) Default implementation returns always 0.
virtual double getWeight (const SUMOEmissionClass c) const
Returns a reference weight in kg described by this emission class as described in the Amitran interface It might return -1, if the weight is not important to distinguish different emission classes. Default implementation returns always -1.
Protected Attributes
StringBijection< SUMOEmissionClass > myEmissionClassStrings
Mapping between emission class names and integer representations.
const std::string myName
the name of the model
Static Private Attributes
static double myFunctionParameter [42][36]
The function parameter.
Detailed Description
Helper methods for HBEFA-based emission computation.
The parameter are stored per vehicle class; 6*6 parameter are used, sorted by the pollutant (CO2, CO, HC, fuel, NOx, PMx), and the function part (c0, cav1, cav2, c1, c2, c3).
Definition at line 53 of file HelpersHBEFA.h.
Constructor & Destructor Documentation
HelpersHBEFA()
HelpersHBEFA::HelpersHBEFA ()
Constructor (initializes myEmissionClassStrings)
Definition at line 142 of file HelpersHBEFA.cpp.
References StringBijection< T >::addAlias(), StringBijection< T >::get(), PollutantsInterface::HEAVY_BIT, StringBijection< T >::insert(), PollutantsInterface::Helper::myEmissionClassStrings, toString(), and PollutantsInterface::ZERO_EMISSIONS.
Member Function Documentation
addAllClassesInto()
void PollutantsInterface::Helper::addAllClassesInto (std::vector< SUMOEmissionClass > & list) const inline inherited
Add all known emission classes of this model to the given container.
Parameters
[in] list the vector to add to
Definition at line 253 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getAllClasses().
compute()
double HelpersHBEFA::compute (const SUMOEmissionClass c, const PollutantsInterface::EmissionType e, const double v, const double a, const double slope, const std::map< int, double > * param) const inline virtual
Computes the emitted pollutant amount using the given speed and acceleration.
As the functions are defining emissions in g/hour, the function's result is normed by 3.6 (seconds in an hour/1000) yielding mg/s. For fuel ml/s is returned. Negative acceleration results directly in zero emission.
Parameters
[in] c emission class for the function parameters to use
[in] e the type of emission (CO, CO2, ...)
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
[in] slope The road's slope at vehicle's position [deg]
Returns
The amount emitted by the given emission class when moving with the given velocity and acceleration [mg/s or ml/s]
Implements PollutantsInterface::Helper.
Definition at line 73 of file HelpersHBEFA.h.
References PollutantsInterface::ELEC, PollutantsInterface::FUEL, M_PI, MAX2(), myFunctionParameter, UNUSED_PARAMETER, and PollutantsInterface::ZERO_EMISSIONS.
getAmitranVehicleClass()
virtual std::string PollutantsInterface::Helper::getAmitranVehicleClass (const SUMOEmissionClass c) const inline virtual inherited
Returns the vehicle class described by this emission class as described in the Amitran interface (Passenger, ...) Default implementation returns always "Passenger".
Parameters
[in] c the emission class
Returns
the name of the vehicle class
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 188 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getAmitranVehicleClass().
getClass()
virtual SUMOEmissionClass PollutantsInterface::Helper::getClass (const SUMOEmissionClass base, const std::string & vClass, const std::string & fuel, const std::string & eClass, const double weight) const inline virtual inherited
Returns the emission class described by the given parameters. The base is used to determine the model to use and as default return values. Default implementation returns always base.
Parameters
[in] base the base class giving the model and the default
[in] vClass the vehicle class as described in the Amitran interface (Passenger, ...)
[in] fuel the fuel type as described in the Amitran interface (Gasoline, Diesel, ...)
[in] eClass the emission class as described in the Amitran interface (Euro0, ...)
[in] weight the vehicle weight in kg as described in the Amitran interface
Returns
the class described by the parameters
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 174 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getClass().
getClassByName()
virtual SUMOEmissionClass PollutantsInterface::Helper::getClassByName (const std::string & eClass, const SUMOVehicleClass vc) inline virtual inherited
Returns the emission class associated with the given name, aliases are possible If this method is asked for the "unknown" class it should return the default (possibly depending on the given vehicle class). The class name is case insensitive.
Parameters
[in] eClass the name of the emission class (string after the '/' in the emission class attribute)
[in] vc the vehicle class to use when determining default class
Returns
the name of the model (string before the '/' in the emission class)
Reimplemented in HelpersPHEMlight.
Definition at line 134 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getClassByName().
getClassName()
const std::string PollutantsInterface::Helper::getClassName (const SUMOEmissionClass c) const inline inherited
Returns the complete name of the emission class including the model.
Parameters
[in] c the emission class
Returns
the name of the class (the complete emission class attribute)
Definition at line 148 of file PollutantsInterface.h.
Referenced by PollutantsInterface::getName().
getEuroClass()
virtual int PollutantsInterface::Helper::getEuroClass (const SUMOEmissionClass c) const inline virtual inherited
Returns the Euro emission class described by this emission class as described in the Amitran interface (0, ..., 6) Default implementation returns always 0.
Parameters
[in] c the emission class
Returns
the Euro class
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 208 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getEuroClass().
getFuel()
virtual std::string PollutantsInterface::Helper::getFuel (const SUMOEmissionClass c) const inline virtual inherited
Returns the fuel type described by this emission class as described in the Amitran interface (Gasoline, Diesel, ...) Default implementation returns always "Gasoline".
Parameters
[in] c the emission class
Returns
the fuel type
Reimplemented in HelpersPHEMlight, and HelpersHBEFA3.
Definition at line 198 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getFuel().
getModifiedAccel()
virtual double PollutantsInterface::Helper::getModifiedAccel (const SUMOEmissionClass c, const double v, const double a, const double slope) const inline virtual inherited
Returns the adapted acceleration value, useful for comparing with external PHEMlight references. Default implementation returns always the input accel.
Parameters
[in] c the emission class
[in] v the speed value
[in] a the acceleration value
[in] slope The road's slope at vehicle's position [deg]
Returns
the modified acceleration
Reimplemented in HelpersPHEMlight.
Definition at line 243 of file PollutantsInterface.h.
References UNUSED_PARAMETER.
Referenced by PollutantsInterface::getModifiedAccel().
getName()
const std::string& PollutantsInterface::Helper::getName () const inline inherited
Returns the name of the model.
Returns
the name of the model (string before the '/' in the emission class attribute)
Definition at line 121 of file PollutantsInterface.h.
getWeight()
virtual double PollutantsInterface::Helper::getWeight (const SUMOEmissionClass c) const inline virtual inherited
Returns a reference weight in kg described by this emission class as described in the Amitran interface It might return -1, if the weight is not important to distinguish different emission classes. Default implementation returns always -1.
Parameters
[in] c the emission class
Returns
a reference weight
Reimplemented in HelpersPHEMlight.
Definition at line 219 of file PollutantsInterface.h.
References PollutantsInterface::compute(), and UNUSED_PARAMETER.
Referenced by PollutantsInterface::getWeight().
isSilent()
virtual bool PollutantsInterface::Helper::isSilent (const SUMOEmissionClass c) inline virtual inherited
Returns whether the class denotes a silent vehicle for interfacing with the noise model. By default the first class in each model is the silent class.
Parameters
[in] c the emission class
Returns
whether the class denotes a silent vehicle
Definition at line 157 of file PollutantsInterface.h.
References PollutantsInterface::HEAVY_BIT.
Referenced by PollutantsInterface::isSilent().
Field Documentation
myEmissionClassStrings
StringBijection<SUMOEmissionClass> PollutantsInterface::Helper::myEmissionClassStrings protected inherited
Mapping between emission class names and integer representations.
Definition at line 263 of file PollutantsInterface.h.
Referenced by HelpersHBEFA3::getAmitranVehicleClass(), HelpersPHEMlight::getAmitranVehicleClass(), HelpersHBEFA3::getClass(), HelpersPHEMlight::getClass(), HelpersPHEMlight::getClassByName(), HelpersHBEFA3::getEuroClass(), HelpersPHEMlight::getEuroClass(), HelpersHBEFA3::getFuel(), HelpersPHEMlight::getFuel(), HelpersPHEMlight::getWeight(), HelpersEnergy::HelpersEnergy(), HelpersHBEFA(), HelpersHBEFA3::HelpersHBEFA3(), and HelpersPHEMlight::HelpersPHEMlight().
myFunctionParameter
double HelpersHBEFA::myFunctionParameter static private
The function parameter.
Definition at line 97 of file HelpersHBEFA.h.
Referenced by compute().
myName
const std::string PollutantsInterface::Helper::myName protected inherited
the name of the model
Definition at line 260 of file PollutantsInterface.h.
The documentation for this class was generated from the following files:
HelpersHBEFA.h
HelpersHBEFA.cpp