SUMO - Simulation of Urban MObility: ROVehicle Class Reference
ROVehicle Class Reference
A vehicle as used by router.
#include <ROVehicle.h>
Public Member Functions
void computeRoute (const RORouterProvider &provider, const bool removeLoops, MsgHandler *errorHandler)
double getChosenSpeedFactor () const
Returns an upper bound for the speed factor of this vehicle.
SUMOTime getDepart () const
Returns the time the vehicle starts at, -1 for triggered vehicles.
const ROEdge * getDepartEdge () const
Returns the first edge the vehicle takes.
SUMOTime getDepartureTime () const
Returns the time the vehicle starts at, 0 for triggered vehicles.
const std::string & getID () const
Returns the id of the routable.
double getMaxSpeed () const
Returns the vehicle's maximum speed.
const SUMOVehicleParameter & getParameter () const
Returns the definition of the vehicle / person parameter.
RORouteDef * getRouteDefinition () const
Returns the definition of the route the vehicle takes.
bool getRoutingSuccess () const
const ConstROEdgeVector & getStopEdges () const
const SUMOVTypeParameter * getType () const
Returns the type of the routable.
SUMOVehicleClass getVClass () const
bool isPartOfFlow () const
bool isPublicTransport () const
ROVehicle (const SUMOVehicleParameter &pars, RORouteDef *route, const SUMOVTypeParameter *type, const RONet *net, MsgHandler *errorHandler=0)
Constructor.
void saveAsXML (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const
Saves the complete vehicle description.
void write (OutputDevice &os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont &options) const
Saves the routable including the vehicle type (if it was not saved before).
virtual ~ROVehicle ()
Destructor.
Protected Attributes
bool myRoutingSuccess
Whether the last routing was successful.
Private Member Functions
void addStop (const SUMOVehicleParameter::Stop &stopPar, const RONet *net, MsgHandler *errorHandler)
Adds a stop to this vehicle.
ROVehicle & operator= (const ROVehicle &src)
Invalidated assignment operator.
ROVehicle (const ROVehicle &src)
Invalidated copy constructor.
Private Attributes
RORouteDef *const myRoute
The route the vehicle takes.
ConstROEdgeVector myStopEdges
The edges where the vehicle stops.
Detailed Description
A vehicle as used by router.
Definition at line 59 of file ROVehicle.h.
Constructor & Destructor Documentation
ROVehicle() [1/2]
ROVehicle::ROVehicle (const SUMOVehicleParameter & pars, RORouteDef * route, const SUMOVTypeParameter * type, const RONet * net, MsgHandler * errorHandler = 0)
Constructor.
Parameters
[in] pars Parameter of this vehicle
[in] route The definition of the route the vehicle shall use
[in] type The type of the vehicle
Definition at line 51 of file ROVehicle.cpp.
References addStop(), RONet::getEdge(), RORouteDef::getFirstRoute(), RORoutable::getParameter(), RORoute::getStops(), myStopEdges, SUMOVehicleParameter::stops, and SUMOVehicleParameter::via.
~ROVehicle()
ROVehicle::~ROVehicle () virtual
Destructor.
Definition at line 120 of file ROVehicle.cpp.
ROVehicle() [2/2]
ROVehicle::ROVehicle (const ROVehicle & src) private
Invalidated copy constructor.
Member Function Documentation
addStop()
void ROVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, const RONet * net, MsgHandler * errorHandler) private
Adds a stop to this vehicle.
Parameters
[in] stopPar the stop paramters
[in] net pointer to the network, used for edge retrieval
Definition at line 77 of file ROVehicle.cpp.
References SUMOVehicleParameter::Stop::endPos, RONet::getEdgeForLaneID(), RORoute::getEdgeVector(), RORouteDef::getFirstRoute(), Named::getID(), RORoutable::getID(), RORoutable::getParameter(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, myRoute, myStopEdges, ROEdge::prohibits(), STOP_INDEX_END, STOP_INDEX_FIT, and SUMOVehicleParameter::stops.
Referenced by getChosenSpeedFactor(), and ROVehicle().
computeRoute()
void ROVehicle::computeRoute (const RORouterProvider & provider, const bool removeLoops, MsgHandler * errorHandler) virtual
Implements RORoutable.
Definition at line 130 of file ROVehicle.cpp.
References RORouteDef::addAlternative(), RORouteDef::buildCurrentRoute(), getDepartureTime(), RORoutable::getID(), getRouteDefinition(), RouterProvider< E, L, N, V >::getVehicleRouter(), MsgHandler::inform(), RORoutable::myRoutingSuccess, RORoute::recheckForLoops(), and RORoute::size().
Referenced by getRouteDefinition().
getChosenSpeedFactor()
double ROVehicle::getChosenSpeedFactor () const inline
Returns an upper bound for the speed factor of this vehicle.
Returns
the maximum speed factor
Definition at line 114 of file ROVehicle.h.
References addStop(), Distribution_Parameterized::getMax(), RORoutable::getType(), saveAsXML(), and SUMOVTypeParameter::speedFactor.
Referenced by ROEdge::getMinimumTravelTime().
getDepart()
SUMOTime RORoutable::getDepart () const inline inherited
Returns the time the vehicle starts at, -1 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 109 of file RORoutable.h.
References SUMOVehicleParameter::depart, and RORoutable::myParameter.
Referenced by RONet::addPerson(), RONet::addVehicle(), and ROVehicleByDepartureComperator::operator()().
getDepartEdge()
const ROEdge * ROVehicle::getDepartEdge () const virtual
Returns the first edge the vehicle takes.
Returns
The vehicle's departure edge
Implements RORoutable.
Definition at line 124 of file ROVehicle.cpp.
References RORoute::getFirst(), RORouteDef::getFirstRoute(), and myRoute.
Referenced by getRouteDefinition().
getDepartureTime()
SUMOTime ROVehicle::getDepartureTime () const inline
Returns the time the vehicle starts at, 0 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 101 of file ROVehicle.h.
References RORoutable::getParameter(), and MAX2().
Referenced by RORouteDef::addAlternative(), computeRoute(), and RORoute::writeXMLDefinition().
getID()
const std::string& RORoutable::getID () const inline inherited
Returns the id of the routable.
Returns
The id of the routable
Definition at line 100 of file RORoutable.h.
References SUMOVehicleParameter::id, and RORoutable::myParameter.
Referenced by RORouteDef::addAlternative(), RONet::addPerson(), addStop(), ROPerson::addTrip(), ROPerson::computeIntermodal(), computeRoute(), RONet::createBulkRouteRequests(), ROVehicleByDepartureComperator::operator()(), RORouteDef::preComputeCurrentRoute(), and RORouteDef::repairCurrentRoute().
getMaxSpeed()
double RORoutable::getMaxSpeed () const inline inherited
Returns the vehicle's maximum speed.
Definition at line 120 of file RORoutable.h.
References RORoutable::getDepartEdge(), SUMOVTypeParameter::maxSpeed, and RORoutable::myType.
Referenced by RONet::createBulkRouteRequests().
getParameter()
const SUMOVehicleParameter& RORoutable::getParameter () const inline inherited
Returns the definition of the vehicle / person parameter.
Returns
The vehicle / person's parameter
Definition at line 80 of file RORoutable.h.
References RORoutable::myParameter.
Referenced by RONet::adaptIntermodalRouter(), addStop(), ROPerson::computeIntermodal(), getDepartureTime(), ROVehicle(), saveAsXML(), and ROPerson::saveAsXML().
getRouteDefinition()
RORouteDef* ROVehicle::getRouteDefinition () const inline
Returns the definition of the route the vehicle takes.
Returns
The vehicle's route definition
Todo:
Why not return a reference?
Definition at line 82 of file ROVehicle.h.
References computeRoute(), getDepartEdge(), and myRoute.
Referenced by ROPerson::computeIntermodal(), computeRoute(), RONet::saveAndRemoveRoutesUntil(), and RONet::~RONet().
getRoutingSuccess()
bool RORoutable::getRoutingSuccess () const inline inherited
Definition at line 160 of file RORoutable.h.
References RORoutable::myRoutingSuccess, and RORoutable::saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
getStopEdges()
const ConstROEdgeVector& ROVehicle::getStopEdges () const inline
Definition at line 106 of file ROVehicle.h.
References myStopEdges.
Referenced by RORouteDef::repairCurrentRoute().
getType()
const SUMOVTypeParameter* RORoutable::getType () const inline inherited
Returns the type of the routable.
Returns
The routable's type
Todo:
Why not return a reference?
Definition at line 91 of file RORoutable.h.
References RORoutable::myType.
Referenced by ROPerson::computeIntermodal(), getChosenSpeedFactor(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), RORoutable::getVClass(), saveAsXML(), and ROPerson::saveAsXML().
getVClass()
SUMOVehicleClass RORoutable::getVClass () const inline inherited
Definition at line 114 of file RORoutable.h.
References RORoutable::getType(), SVC_IGNORING, and SUMOVTypeParameter::vehicleClass.
Referenced by RONet::createBulkRouteRequests(), ROEdge::isConnectedTo(), and ROEdge::prohibits().
isPartOfFlow()
bool RORoutable::isPartOfFlow () const inline inherited
Definition at line 132 of file RORoutable.h.
References RORoutable::computeRoute(), RORoutable::myParameter, and SUMOVehicleParameter::repetitionNumber.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
isPublicTransport()
bool RORoutable::isPublicTransport () const inline inherited
Definition at line 128 of file RORoutable.h.
References SUMOVehicleParameter::line, and RORoutable::myParameter.
Referenced by RONet::addVehicle(), and RONet::saveAndRemoveRoutesUntil().
operator=()
ROVehicle& ROVehicle::operator= (const ROVehicle & src) private
Invalidated assignment operator.
saveAsXML()
void ROVehicle::saveAsXML (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const virtual
Saves the complete vehicle description.
Saves the vehicle itself including the route and stops.
Parameters
[in] os The routes or alternatives output device to store the vehicle's description into
[in] typeos The types - output device to store types into
[in] asAlternatives Whether the route shall be saved as route alternatives
[in] options to find out about defaults and whether exit times for the edges shall be written
Exceptions
IOError If something fails (not yet implemented)
Implements RORoutable.
Definition at line 166 of file ROVehicle.cpp.
References OutputDevice::closeTag(), OptionsCont::getBool(), RORoutable::getParameter(), RORoutable::getType(), myRoute, SUMOVTypeParameter::saved, SUMOVehicleParameter::stops, SUMOVTypeParameter::write(), SUMOVehicleParameter::write(), Parameterised::writeParams(), and RORouteDef::writeXMLDefinition().
Referenced by getChosenSpeedFactor().
write()
void RORoutable::write (OutputDevice & os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont & options) const inline inherited
Saves the routable including the vehicle type (if it was not saved before).
Parameters
[in] os The routes - output device to store the vehicle's description into
[in] altos The route alternatives - output device to store the vehicle's description into
[in] typeos The types - output device to store the vehicle types into
Exceptions
IOError If something fails (not yet implemented)
Definition at line 147 of file RORoutable.h.
References RORoutable::saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
Field Documentation
myRoute
RORouteDef* const ROVehicle::myRoute private
The route the vehicle takes.
Definition at line 143 of file ROVehicle.h.
Referenced by addStop(), getDepartEdge(), getRouteDefinition(), and saveAsXML().
myRoutingSuccess
bool RORoutable::myRoutingSuccess protected inherited
Whether the last routing was successful.
Definition at line 188 of file RORoutable.h.
Referenced by ROPerson::computeIntermodal(), computeRoute(), ROPerson::computeRoute(), and RORoutable::getRoutingSuccess().
myStopEdges
ConstROEdgeVector ROVehicle::myStopEdges private
The edges where the vehicle stops.
Definition at line 146 of file ROVehicle.h.
Referenced by addStop(), getStopEdges(), and ROVehicle().
The documentation for this class was generated from the following files:
ROVehicle.h
ROVehicle.cpp