SUMO - Simulation of Urban MObility: NBContHelper::same_connection_edge_sorter Class Reference
NBContHelper::same_connection_edge_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
std::pair< double, double > getMinMaxRelAngles (NBEdge *e) const
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
same_connection_edge_sorter ()
constructor
Detailed Description
same_connection_edge_sorter This class is used to sort edges which connect the same nodes. The edges are sorted in dependence to edges connecting them. The rightmost will be the first in the list; the leftmost the last one.
Definition at line 347 of file NBContHelper.h.
Constructor & Destructor Documentation
same_connection_edge_sorter()
NBContHelper::same_connection_edge_sorter::same_connection_edge_sorter () inline explicit
constructor
Definition at line 350 of file NBContHelper.h.
Member Function Documentation
getMinMaxRelAngles()
std::pair<double, double> NBContHelper::same_connection_edge_sorter::getMinMaxRelAngles (NBEdge * e) const inline
Definition at line 371 of file NBContHelper.h.
References NBEdge::getConnectedEdges(), NBEdge::getTotalAngle(), NBHelpers::normRelAngle(), and NBContHelper::operator<<.
operator()()
int NBContHelper::same_connection_edge_sorter::operator() (NBEdge * e1, NBEdge * e2) const inline
comparing operation
Definition at line 353 of file NBContHelper.h.
References Named::getID().
The documentation for this class was generated from the following file:
NBContHelper.h