SUMO - Simulation of Urban MObility: AGTrip Class Reference
AGTrip Class Reference
#include <AGTrip.h>
Public Member Functions
void addLayOver (AGPosition by)
void addLayOver (AGTrip &trip)
void addLayOverWithoutDestination (AGTrip &trip)
AGTrip (AGPosition from, AGPosition to, int at)
AGTrip (AGPosition from, AGPosition to, AGCar c, int at)
AGTrip (AGPosition from, AGPosition to, AGBus b, int at)
AGTrip (AGPosition from, AGPosition to, std::string v, int at)
AGTrip (AGPosition from, AGPosition to, std::string v, int at, int day)
int estimateDepTime (int arrTime, double secPerKm) const
AGPosition getArr () const
int getArrTime (double secPerKm) const
int getDay () const
AGPosition getDep () const
const std::list< AGPosition > * getPassed () const
int getRideBackArrTime (double secPerKm) const
int getTime () const
int getTimeTrip (double secPerKm) const
const std::string & getType () const
const std::string & getVehicleName () const
bool isDaily () const
bool operator< (const AGTrip &trip) const
void print () const
void setArr (AGPosition arrival)
void setDay (int day)
void setDep (AGPosition departure)
void setDepTime (int time)
void setType (std::string type)
void setVehicleName (std::string name)
Private Attributes
int myDay
int myDepTime
AGPosition myFrom
std::list< AGPosition > myPassBy
AGPosition myTo
std::string myType
std::string myVehicle
Detailed Description
Definition at line 47 of file AGTrip.h.
Constructor & Destructor Documentation
AGTrip() [1/5]
AGTrip::AGTrip (AGPosition from, AGPosition to, int at) inline
Definition at line 49 of file AGTrip.h.
AGTrip() [2/5]
AGTrip::AGTrip (AGPosition from, AGPosition to, AGCar c, int at) inline
Definition at line 55 of file AGTrip.h.
AGTrip() [3/5]
AGTrip::AGTrip (AGPosition from, AGPosition to, AGBus b, int at) inline
Definition at line 62 of file AGTrip.h.
AGTrip() [4/5]
AGTrip::AGTrip (AGPosition from, AGPosition to, std::string v, int at) inline
Definition at line 69 of file AGTrip.h.
AGTrip() [5/5]
AGTrip::AGTrip (AGPosition from, AGPosition to, std::string v, int at, int day) inline
Definition at line 76 of file AGTrip.h.
References addLayOver(), addLayOverWithoutDestination(), estimateDepTime(), getArr(), getArrTime(), getDay(), getDep(), getPassed(), getRideBackArrTime(), getTime(), getTimeTrip(), getType(), getVehicleName(), isDaily(), operator<(), print(), setArr(), setDay(), setDep(), setDepTime(), setType(), and setVehicleName().
Member Function Documentation
addLayOver() [1/2]
void AGTrip::addLayOver (AGPosition by)
Definition at line 67 of file AGTrip.cpp.
References myPassBy.
Referenced by AGTrip(), and AGActivities::generateBusTraffic().
addLayOver() [2/2]
void AGTrip::addLayOver (AGTrip & trip)
Definition at line 72 of file AGTrip.cpp.
References myPassBy, and myTo.
addLayOverWithoutDestination()
void AGTrip::addLayOverWithoutDestination (AGTrip & trip)
Definition at line 81 of file AGTrip.cpp.
References myPassBy.
Referenced by AGTrip().
estimateDepTime()
int AGTrip::estimateDepTime (int arrTime, double secPerKm) const
estimate the departure time needed for a given arrival time and a speed in seconds per kilometer
Definition at line 153 of file AGTrip.cpp.
References getTimeTrip().
Referenced by AGTrip().
getArr()
AGPosition AGTrip::getArr () const
Definition at line 109 of file AGTrip.cpp.
References myTo.
Referenced by AGActivityTripWriter::addTrip(), and AGTrip().
getArrTime()
int AGTrip::getArrTime (double secPerKm) const
returns the estimated arrival time given the time to make one kilometer
Definition at line 138 of file AGTrip.cpp.
References getTimeTrip(), and myDepTime.
Referenced by AGTrip(), and getRideBackArrTime().
getDay()
int AGTrip::getDay () const
Definition at line 183 of file AGTrip.cpp.
References myDay.
Referenced by AGActivityTripWriter::addTrip(), AGTrip(), operator<(), AGActivityGen::timeTripValidation(), and AGActivityGen::varDepTime().
getDep()
AGPosition AGTrip::getDep () const
Definition at line 104 of file AGTrip.cpp.
References myFrom.
Referenced by AGActivityTripWriter::addTrip(), and AGTrip().
getPassed()
const std::list< AGPosition > * AGTrip::getPassed () const
Definition at line 89 of file AGTrip.cpp.
References myPassBy.
Referenced by AGActivityTripWriter::addTrip(), and AGTrip().
getRideBackArrTime()
int AGTrip::getRideBackArrTime (double secPerKm) const
returns the time regarding the departure time going through the different points and coming back to the initial position given the time to make one kilometer
Definition at line 143 of file AGTrip.cpp.
References AGPosition::distanceTo(), getArrTime(), myFrom, and myTo.
Referenced by AGTrip().
getTime()
int AGTrip::getTime () const
Definition at line 114 of file AGTrip.cpp.
References myDepTime.
Referenced by AGActivityTripWriter::addTrip(), AGTrip(), operator<(), AGActivityGen::timeTripValidation(), and AGActivityGen::varDepTime().
getTimeTrip()
int AGTrip::getTimeTrip (double secPerKm) const
gives the time in seconds for the trip given a speed in seconds per kilometer (in city, not car speed but time needed to make a distance in the city)
Definition at line 119 of file AGTrip.cpp.
References AGPosition::distanceTo(), myFrom, myPassBy, and myTo.
Referenced by AGTrip(), estimateDepTime(), and getArrTime().
getType()
const std::string & AGTrip::getType () const
Definition at line 94 of file AGTrip.cpp.
References myType.
Referenced by AGActivityTripWriter::addTrip(), AGTrip(), and AGActivityGen::varDepTime().
getVehicleName()
const std::string & AGTrip::getVehicleName () const
Definition at line 158 of file AGTrip.cpp.
References myVehicle.
Referenced by AGActivityTripWriter::addTrip(), and AGTrip().
isDaily()
bool AGTrip::isDaily () const
returns whether this is a daily trip or a one day trip
Definition at line 178 of file AGTrip.cpp.
References myDay.
Referenced by AGTrip().
operator<()
bool AGTrip::operator< (const AGTrip & trip) const
Definition at line 43 of file AGTrip.cpp.
References getDay(), and getTime().
Referenced by AGTrip().
print()
void AGTrip::print () const
Definition at line 55 of file AGTrip.cpp.
References myDay, myDepTime, myFrom, myTo, myType, myVehicle, and AGPosition::print().
Referenced by AGTrip().
setArr()
void AGTrip::setArr (AGPosition arrival)
Definition at line 168 of file AGTrip.cpp.
References AGPosition::getPosition(), AGPosition::getStreet(), and myTo.
Referenced by AGTrip().
setDay()
void AGTrip::setDay (int day)
Definition at line 188 of file AGTrip.cpp.
References myDay.
Referenced by AGTrip(), and AGActivityGen::varDepTime().
setDep()
void AGTrip::setDep (AGPosition departure)
Definition at line 173 of file AGTrip.cpp.
References AGPosition::getPosition(), AGPosition::getStreet(), and myFrom.
Referenced by AGTrip().
setDepTime()
void AGTrip::setDepTime (int time)
Definition at line 148 of file AGTrip.cpp.
References myDepTime.
Referenced by AGTrip(), AGActivities::generateInOutTraffic(), and AGActivityGen::varDepTime().
setType()
void AGTrip::setType (std::string type)
Definition at line 99 of file AGTrip.cpp.
References myType.
Referenced by AGTrip(), AGActivities::generateRandomTraffic(), and AGActivityGen::makeActivityTrips().
setVehicleName()
void AGTrip::setVehicleName (std::string name)
Definition at line 163 of file AGTrip.cpp.
References myVehicle.
Referenced by AGTrip().
Field Documentation
myDay
int AGTrip::myDay private
if everyday : 0 else : number of the day (!= 0)
Definition at line 145 of file AGTrip.h.
Referenced by getDay(), isDaily(), print(), and setDay().
myDepTime
int AGTrip::myDepTime private
Definition at line 134 of file AGTrip.h.
Referenced by getArrTime(), getTime(), print(), and setDepTime().
myFrom
AGPosition AGTrip::myFrom private
Definition at line 132 of file AGTrip.h.
Referenced by getDep(), getRideBackArrTime(), getTimeTrip(), print(), and setDep().
myPassBy
std::list<AGPosition> AGTrip::myPassBy private
Definition at line 146 of file AGTrip.h.
Referenced by addLayOver(), addLayOverWithoutDestination(), getPassed(), and getTimeTrip().
myTo
AGPosition AGTrip::myTo private
Definition at line 133 of file AGTrip.h.
Referenced by addLayOver(), getArr(), getRideBackArrTime(), getTimeTrip(), print(), and setArr().
myType
std::string AGTrip::myType private
indicates if it is a bus or a car (or any type) "bus", "default" or "random" (which is a kind of default)
Definition at line 140 of file AGTrip.h.
Referenced by getType(), print(), and setType().
myVehicle
std::string AGTrip::myVehicle private
Definition at line 135 of file AGTrip.h.
Referenced by getVehicleName(), print(), and setVehicleName().
The documentation for this class was generated from the following files:
AGTrip.h
AGTrip.cpp