SUMO - Simulation of Urban MObility: GNEAdditionalFrame::SelectorParentEdges Class Reference
GNEAdditionalFrame::SelectorParentEdges Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
std::string getIdsSelected () const
get list of selecte id's in string format
void hideList ()
hide SelectorParentEdges
bool isUseSelectedEdgesEnable () const
get status of checkBox UseSelectedEdges
SelectorParentEdges (FXComposite *parent, GNEViewNet *viewNet)
FOX-declaration.
void showList (std::string search="")
Show list of SelectorParentEdges.
void updateUseSelectedEdges ()
Update use selectedEdges.
~SelectorParentEdges ()
destructor
FOX-callbacks
called when user trigger checkBox of useSelectedEdges
long onCmdUseSelectedEdges (FXObject *, FXSelector, void *)
long onCmdTypeInSearchBox (FXObject *, FXSelector, void *)
called when user type in search box
long onCmdSelectEdge (FXObject *, FXSelector, void *)
called when user select a edge of the list
long onCmdClearSelection (FXObject *, FXSelector, void *)
called when clear selection button is pressed
long onCmdInvertSelection (FXObject *, FXSelector, void *)
called when invert selection button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
SelectorParentEdges ()
FOX needs this.
Private Attributes
FXButton * myClearEdgesSelection
button for clear selection
FXTextField * myEdgesSearch
text field for search edge IDs
FXButton * myHelpedgeParentsSelector
button for help
FXButton * myInvertEdgesSelection
button for invert selection
FXList * myList
List of SelectorParentEdges.
FXCheckButton * myUseSelectedEdgesCheckButton
CheckBox for selected edges.
GNEViewNet * myViewNet
viewNet associated to GNEAdditionalFrame
Detailed Description
Definition at line 452 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
SelectorParentEdges() [1/2]
GNEAdditionalFrame::SelectorParentEdges::SelectorParentEdges (FXComposite * parent, GNEViewNet * viewNet)
FOX-declaration.
constructor
Definition at line 1436 of file GNEAdditionalFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignButtonRectangular, GUIDesignCheckButtonAttribute, GUIDesignList, GUIDesignTextField, GUIDesignTextFieldNCol, hideList(), MID_GNE_ADDITIONALFRAME_CLEAREDGESELECTION, MID_GNE_ADDITIONALFRAME_INVERTEDGESELECTION, MID_GNE_ADDITIONALFRAME_SEARCHEDGE, MID_GNE_ADDITIONALFRAME_SELECTEDGE, MID_GNE_ADDITIONALFRAME_SHOWONLYSELECTEDEDGES, MID_HELP, myClearEdgesSelection, myEdgesSearch, myHelpedgeParentsSelector, myInvertEdgesSelection, myList, myUseSelectedEdgesCheckButton, SUMO_TAG_EDGE, and toString().
~SelectorParentEdges()
GNEAdditionalFrame::SelectorParentEdges::~SelectorParentEdges ()
destructor
Definition at line 1465 of file GNEAdditionalFrame.cpp.
SelectorParentEdges() [2/2]
GNEAdditionalFrame::SelectorParentEdges::SelectorParentEdges () inline protected
FOX needs this.
Definition at line 501 of file GNEAdditionalFrame.h.
Member Function Documentation
getIdsSelected()
std::string GNEAdditionalFrame::SelectorParentEdges::getIdsSelected () const
get list of selecte id's in string format
Definition at line 1469 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::getIdsSelected(), and myList.
Referenced by GNEAdditionalFrame::addAdditional().
hideList()
void GNEAdditionalFrame::SelectorParentEdges::hideList ()
hide SelectorParentEdges
Definition at line 1500 of file GNEAdditionalFrame.cpp.
Referenced by SelectorParentEdges(), and GNEAdditionalFrame::setParametersOfAdditional().
isUseSelectedEdgesEnable()
bool GNEAdditionalFrame::SelectorParentEdges::isUseSelectedEdgesEnable () const
get status of checkBox UseSelectedEdges
Definition at line 1517 of file GNEAdditionalFrame.cpp.
References myUseSelectedEdgesCheckButton.
Referenced by GNEAdditionalFrame::addAdditional().
onCmdClearSelection()
long GNEAdditionalFrame::SelectorParentEdges::onCmdClearSelection (FXObject * , FXSelector , void *)
called when clear selection button is pressed
Definition at line 1564 of file GNEAdditionalFrame.cpp.
References myList.
onCmdHelp()
long GNEAdditionalFrame::SelectorParentEdges::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1588 of file GNEAdditionalFrame.cpp.
onCmdInvertSelection()
long GNEAdditionalFrame::SelectorParentEdges::onCmdInvertSelection (FXObject * , FXSelector , void *)
called when invert selection button is pressed
Definition at line 1575 of file GNEAdditionalFrame.cpp.
References myList.
onCmdSelectEdge()
long GNEAdditionalFrame::SelectorParentEdges::onCmdSelectEdge (FXObject * , FXSelector , void *)
called when user select a edge of the list
Definition at line 1558 of file GNEAdditionalFrame.cpp.
onCmdTypeInSearchBox()
long GNEAdditionalFrame::SelectorParentEdges::onCmdTypeInSearchBox (FXObject * , FXSelector , void *)
called when user type in search box
Definition at line 1550 of file GNEAdditionalFrame.cpp.
References myEdgesSearch, and showList().
onCmdUseSelectedEdges()
long GNEAdditionalFrame::SelectorParentEdges::onCmdUseSelectedEdges (FXObject * , FXSelector , void *)
Definition at line 1527 of file GNEAdditionalFrame.cpp.
References myClearEdgesSelection, myEdgesSearch, myHelpedgeParentsSelector, myInvertEdgesSelection, myList, and myUseSelectedEdgesCheckButton.
showList()
void GNEAdditionalFrame::SelectorParentEdges::showList (std::string search = "")
Show list of SelectorParentEdges.
Todo:
this function must be improved.
Definition at line 1475 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myList, myUseSelectedEdgesCheckButton, myViewNet, GNENet::retrieveEdges(), and GNEAdditionalFrame::show().
Referenced by onCmdTypeInSearchBox(), and GNEAdditionalFrame::setParametersOfAdditional().
updateUseSelectedEdges()
void GNEAdditionalFrame::SelectorParentEdges::updateUseSelectedEdges ()
Update use selectedEdges.
Definition at line 1506 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myUseSelectedEdgesCheckButton, myViewNet, and GNENet::retrieveEdges().
Referenced by GNEAdditionalFrame::show().
Field Documentation
myClearEdgesSelection
FXButton* GNEAdditionalFrame::SelectorParentEdges::myClearEdgesSelection private
button for clear selection
Definition at line 517 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedEdges(), and SelectorParentEdges().
myEdgesSearch
FXTextField* GNEAdditionalFrame::SelectorParentEdges::myEdgesSearch private
text field for search edge IDs
Definition at line 511 of file GNEAdditionalFrame.h.
Referenced by onCmdTypeInSearchBox(), onCmdUseSelectedEdges(), and SelectorParentEdges().
myHelpedgeParentsSelector
FXButton* GNEAdditionalFrame::SelectorParentEdges::myHelpedgeParentsSelector private
button for help
Definition at line 514 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedEdges(), and SelectorParentEdges().
myInvertEdgesSelection
FXButton* GNEAdditionalFrame::SelectorParentEdges::myInvertEdgesSelection private
button for invert selection
Definition at line 520 of file GNEAdditionalFrame.h.
Referenced by onCmdUseSelectedEdges(), and SelectorParentEdges().
myList
FXList* GNEAdditionalFrame::SelectorParentEdges::myList private
List of SelectorParentEdges.
Definition at line 508 of file GNEAdditionalFrame.h.
Referenced by getIdsSelected(), onCmdClearSelection(), onCmdInvertSelection(), onCmdUseSelectedEdges(), SelectorParentEdges(), and showList().
myUseSelectedEdgesCheckButton
FXCheckButton* GNEAdditionalFrame::SelectorParentEdges::myUseSelectedEdgesCheckButton private
CheckBox for selected edges.
Definition at line 505 of file GNEAdditionalFrame.h.
Referenced by isUseSelectedEdgesEnable(), onCmdUseSelectedEdges(), SelectorParentEdges(), showList(), and updateUseSelectedEdges().
myViewNet
GNEViewNet* GNEAdditionalFrame::SelectorParentEdges::myViewNet private
viewNet associated to GNEAdditionalFrame
Definition at line 523 of file GNEAdditionalFrame.h.
Referenced by showList(), and updateUseSelectedEdges().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp