SUMO - Simulation of Urban MObility: SUMOSAXAttributesImpl_Binary Class Reference
SUMOSAXAttributesImpl_Binary Class Reference
Encapsulated Xerces-SAX-attributes.
#include <SUMOSAXAttributesImpl_Binary.h>
Public Member Functions
template<typename T >
T get (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is an int.
template<>
int getInternal (const int attr) const
template<>
long long int getInternal (const int attr) const
template<>
double getInternal (const int attr) const
template<>
bool getInternal (const int attr) const
template<>
std::string getInternal (const int attr) const
template<>
RGBColor getInternal (const int) const
template<>
PositionVector getInternal (const int attr) const
template<>
Boundary getInternal (const int attr) const
template<typename T >
T getOpt (int attr, const char *objectid, bool &ok, T defaultValue, bool report=true) const
Tries to read given attribute assuming it is an int.
SUMOTime getOptSUMOTimeReporting (int attr, const char *objectid, bool &ok, SUMOTime defaultValue, bool report=true) const
Tries to read given attribute assuming it is a SUMOTime.
SUMOTime getSUMOTimeReporting (int attr, const char *objectid, bool &ok, bool report=true) const
Tries to read given attribute assuming it is a SUMOTime.
SUMOSAXAttributesImpl_Binary (const std::map< int, std::string > &predefinedTagsMML, const std::string &objectType, BinaryInputDevice *in, const char version)
Constructor.
virtual ~SUMOSAXAttributesImpl_Binary ()
Destructor.
virtual methods for retrieving attribute values
const std::string & getObjectType () const
return the objecttype to which these attributes belong
static const std::string ENCODING = " encoding=\"UTF-8\""
The encoding of parsed strings.
static void parseStringVector (const std::string &def, std::vector< std::string > &into)
Splits the given string.
static void parseStringSet (const std::string &def, std::set< std::string > &into)
Splits the given string, stores it in a set.
template<typename T >
T getInternal (const int attr) const
void emitUngivenError (const std::string &attrname, const char *objectid) const
void emitEmptyError (const std::string &attrname, const char *objectid) const
void emitFormatError (const std::string &attrname, const std::string &type, const char *objectid) const
methods for retrieving attribute values
const std::map< int, std::string > & myAttrIds
Map of attribute ids to names.
std::set< int > myAttrs
the attributes which are set
std::map< int, char > myCharValues
Map of attribute ids to char.
std::map< int, int > myIntValues
Map of attribute ids to integers.
std::map< int, double > myFloatValues
Map of attribute ids to floats.
std::map< int, std::string > myStringValues
Map of attribute ids to string.
std::map< int, PositionVector > myPositionVectors
Map of attribute ids to string.
bool hasAttribute (int id) const
Returns the information whether the named (by its enum-value) attribute is within the current list.
bool getBool (int id) const
Returns the bool-value of the named (by its enum-value) attribute.
int getInt (int id) const
Returns the int-value of the named (by its enum-value) attribute.
long long int getLong (int id) const
Returns the long-value of the named (by its enum-value) attribute.
std::string getString (int id) const
Returns the string-value of the named (by its enum-value) attribute.
std::string getStringSecure (int id, const std::string &def) const
Returns the string-value of the named (by its enum-value) attribute.
double getFloat (int id) const
Returns the double-value of the named (by its enum-value) attribute.
bool hasAttribute (const std::string &id) const
Returns the information whether the named attribute is within the current list.
double getFloat (const std::string &id) const
Returns the double-value of the named attribute.
std::string getStringSecure (const std::string &id, const std::string &def) const
Returns the string-value of the named (by its enum-value) attribute.
SumoXMLEdgeFunc getEdgeFunc (bool &ok) const
Returns the value of the named attribute.
SumoXMLNodeType getNodeType (bool &ok) const
Returns the value of the named attribute.
RGBColor getColor () const
Returns the value of the named attribute.
PositionVector getShape (int attr) const
Tries to read given attribute assuming it is a PositionVector.
Boundary getBoundary (int attr) const
Tries to read given attribute assuming it is a Boundary.
std::vector< std::string > getStringVector (int attr) const
Tries to read given attribute assuming it is a string vector.
std::string getName (int attr) const
Converts the given attribute id into a man readable string.
void serialize (std::ostream &os) const
Prints all attribute names and values into the given stream.
SUMOSAXAttributes * clone () const
return a new deep-copy attributes object
SUMOSAXAttributesImpl_Binary (const SUMOSAXAttributesImpl_Binary &src)
Invalidated copy constructor.
SUMOSAXAttributesImpl_Binary & operator= (const SUMOSAXAttributesImpl_Binary &src)
Invalidated assignment operator.
Detailed Description
Encapsulated Xerces-SAX-attributes.
See also
SUMOSAXAttributes
Definition at line 54 of file SUMOSAXAttributesImpl_Binary.h.
Constructor & Destructor Documentation
SUMOSAXAttributesImpl_Binary() [1/2]
SUMOSAXAttributesImpl_Binary::SUMOSAXAttributesImpl_Binary (const std::map< int, std::string > & predefinedTagsMML, const std::string & objectType, BinaryInputDevice * in, const char version)
Constructor.
Parameters
[in] attrs The encapsulated xerces-attributes
[in] predefinedTags Map of attribute ids to their xerces-representation
[in] predefinedTagsMML Map of attribute ids to their (readable) string-representation
Definition at line 47 of file SUMOSAXAttributesImpl_Binary.cpp.
References BinaryFormatter::BF_BOUNDARY, BinaryFormatter::BF_BYTE, BinaryFormatter::BF_COLOR, BinaryFormatter::BF_EDGE, BinaryFormatter::BF_EDGE_FUNCTION, BinaryFormatter::BF_FLOAT, BinaryFormatter::BF_INTEGER, BinaryFormatter::BF_LANE, BinaryFormatter::BF_LIST, BinaryFormatter::BF_NODE_TYPE, BinaryFormatter::BF_POSITION_2D, BinaryFormatter::BF_POSITION_3D, BinaryFormatter::BF_ROUTE, BinaryFormatter::BF_SCALED2INT, BinaryFormatter::BF_SCALED2INT_POSITION_2D, BinaryFormatter::BF_SCALED2INT_POSITION_3D, BinaryFormatter::BF_STRING, BinaryFormatter::BF_XML_ATTRIBUTE, myAttrs, myCharValues, myFloatValues, myIntValues, myPositionVectors, myStringValues, BinaryInputDevice::peek(), BinaryInputDevice::putback(), FileHelpers::writeByte(), and FileHelpers::writeInt().
~SUMOSAXAttributesImpl_Binary()
SUMOSAXAttributesImpl_Binary::~SUMOSAXAttributesImpl_Binary () virtual
Destructor.
Definition at line 161 of file SUMOSAXAttributesImpl_Binary.cpp.
SUMOSAXAttributesImpl_Binary() [2/2]
SUMOSAXAttributesImpl_Binary::SUMOSAXAttributesImpl_Binary (const SUMOSAXAttributesImpl_Binary & src) private
Invalidated copy constructor.
Member Function Documentation
clone()
SUMOSAXAttributes * SUMOSAXAttributesImpl_Binary::clone () const virtual
return a new deep-copy attributes object
Implements SUMOSAXAttributes.
Definition at line 337 of file SUMOSAXAttributesImpl_Binary.cpp.
References SUMOSAXAttributes::getObjectType(), myAttrIds, myCharValues, myFloatValues, myIntValues, myPositionVectors, myStringValues, and toString().
emitEmptyError()
void SUMOSAXAttributes::emitEmptyError (const std::string & attrname, const char * objectid) const protected inherited
Definition at line 123 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::myObjectType, and WRITE_ERROR.
Referenced by SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), and SUMOSAXAttributes::getSUMOTimeReporting().
emitFormatError()
void SUMOSAXAttributes::emitFormatError (const std::string & attrname, const std::string & type, const char * objectid) const protected inherited
Definition at line 137 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::myObjectType, and WRITE_ERROR.
Referenced by SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), and SUMOSAXAttributes::getSUMOTimeReporting().
emitUngivenError()
void SUMOSAXAttributes::emitUngivenError (const std::string & attrname, const char * objectid) const protected inherited
Definition at line 109 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::myObjectType, and WRITE_ERROR.
Referenced by SUMOSAXAttributes::get(), and SUMOSAXAttributes::getSUMOTimeReporting().
get()
template<typename T > T SUMOSAXAttributes::get (int attr, const char * objectid, bool & ok, bool report = true) const inherited
Tries to read given attribute assuming it is an int.
If an error occurs (the attribute is not there, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
If the value could be read, "ok" is not changed, and the value is returned.
Parameters
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns
The read value if given and correct; -1 if an error occured
Definition at line 445 of file SUMOSAXAttributes.h.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NIImporter_SUMO::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), NLHandler::addDistrict(), NLHandler::addDistrictEdge(), NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NIImporter_SUMO::addEdge(), NIXMLEdgesHandler::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NIXMLNodesHandler::addJoinCluster(), NIXMLNodesHandler::addJoinExclusion(), NIImporter_SUMO::addJunction(), NIImporter_SUMO::addLane(), NLHandler::addLane(), NIXMLEdgesHandler::addLane(), NIXMLNodesHandler::addNode(), SUMORouteHandler::addParam(), NLHandler::addParam(), RORouteHandler::addPersonTrip(), NIImporter_SUMO::addPhase(), NLHandler::addPhase(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NIImporter_SUMO::addRequest(), NLHandler::addRequest(), NLHandler::addRouteProbeDetector(), NIXMLEdgesHandler::addSplit(), ROJTRTurnDefLoader::addToEdge(), NLHandler::addVTypeProbeDetector(), MSRouteHandler::addWalk(), RORouteHandler::addWalk(), NIXMLConnectionsHandler::addWalkingArea(), NLHandler::addWAUTJunction(), NLHandler::addWAUTSwitch(), NLHandler::beginE3Detector(), NLHandler::beginEdgeParsing(), ROJTRTurnDefLoader::beginFromEdge(), SUMOVehicleParserHelper::beginVTypeParsing(), NLTriggerBuilder::buildVaporizer(), NIXMLEdgesHandler::deleteEdge(), NIXMLNodesHandler::deleteNode(), NLTriggerBuilder::getLane(), NLTriggerBuilder::getPosition(), NLHandler::initJunctionLogic(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NLHandler::initTrafficLightLogic(), NIImporter_SUMO::loadLocation(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), PCTypeDefHandler::myStartElement(), NIXMLTrafficLightsHandler::myStartElement(), MSStateHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), ODAmitranHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), MSRouteHandler::myStartElement(), ShapeHandler::myStartElement(), RONetHandler::myStartElement(), ROJTRTurnDefLoader::myStartElement(), RORouteHandler::myStartElement(), PCNetProjectionLoader::myStartElement(), TrajectoriesHandler::myStartElement(), NIXMLNodesHandler::myStartElement(), NIXMLEdgesHandler::myStartElement(), PCLoaderXML::myStartElement(), NIImporter_MATSim::NodesHandler::myStartElement(), NIImporter_SUMO::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition::myStartElement(), NLHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_Zuflussdefinition::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), SAXWeightsHandler::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_Parkplatzdefinition::myStartElement(), PCLoaderOSM::RelationsHandler::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition::myStartElement(), NIImporter_OpenStreetMap::NodesHandler::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition::myStartElement(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition::myStartElement(), NIImporter_Vissim::NIVissimXMLHandler_ConflictArea::myStartElement(), NIImporter_OpenStreetMap::RelationHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), ODDistrictHandler::openDistrict(), NLHandler::openJunction(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), RORouteHandler::openVehicleTypeDistribution(), NLHandler::openWAUT(), RONetHandler::parseAccess(), NLTriggerBuilder::parseAndAddLotEntry(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLTriggerBuilder::parseAndBuildRerouter(), NLTriggerBuilder::parseAndBuildStoppingPlace(), GNEAttributeCarrier::parseAttributeFromXML(), SUMOVehicleParserHelper::parseCommonAttributes(), RONetHandler::parseConnection(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), RONetHandler::parseDistrict(), RONetHandler::parseDistrictEdge(), RONetHandler::parseEdge(), SUMOVehicleParserHelper::parseFlowAttributes(), SUMOVehicleParserHelper::parseJMParams(), RONetHandler::parseJunction(), RONetHandler::parseLane(), NIXMLConnectionsHandler::parseLaneDefinition(), SUMOVehicleParserHelper::parseLCParams(), AGActivityGenHandler::parseStation(), SUMORouteHandler::parseStop(), RONetHandler::parseStoppingPlace(), ODDistrictHandler::parseTAZ(), SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParserHelper::parseVTypeEmbedded(), MSRouteHandler::parseWalkPositions(), NIXMLNodesHandler::processNodeType(), NIImporter_SUMO::readPosition(), NIXMLTrafficLightsHandler::removeTlConnection(), NIXMLTrafficLightsHandler::retrieveEdge(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), NLHandler::setLocation(), and NIXMLEdgesHandler::setNodes().
getBool()
bool SUMOSAXAttributesImpl_Binary::getBool (int id) const virtual
Returns the bool-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2bool. If the attribute is empty or ==0, TplConvert<XMLCh>::_2bool throws an EmptyData-exception which is passed. If the value can not be parsed to a bool, TplConvert<XMLCh>::_2bool throws a BoolFormatException-exception which is passed.
Parameters
[in] id The id of the attribute to return the value of
Returns
The attribute's value as a bool, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
BoolFormatException If the attribute value can not be parsed to a bool
Implements SUMOSAXAttributes.
Definition at line 172 of file SUMOSAXAttributesImpl_Binary.cpp.
References myCharValues.
getBoundary()
Boundary SUMOSAXAttributesImpl_Binary::getBoundary (int attr) const virtual
Tries to read given attribute assuming it is a Boundary.
Parameters
[in] attr The id of the attribute to read
Returns
The read value if given and not empty; "" if an error occured
Implements SUMOSAXAttributes.
Definition at line 297 of file SUMOSAXAttributesImpl_Binary.cpp.
References myPositionVectors.
getColor()
RGBColor SUMOSAXAttributesImpl_Binary::getColor () const virtual
Returns the value of the named attribute.
Tries to retrieve the attribute from the the attribute list.
Returns
The attribute's value as a RGBColor, if it could be read and parsed
Implements SUMOSAXAttributes.
Definition at line 276 of file SUMOSAXAttributesImpl_Binary.cpp.
References myIntValues, and SUMO_ATTR_COLOR.
getEdgeFunc()
SumoXMLEdgeFunc SUMOSAXAttributesImpl_Binary::getEdgeFunc (bool & ok) const virtual
Returns the value of the named attribute.
Tries to retrieve the attribute from the the attribute list.
Returns
The attribute's value as a string, if it could be read and parsed
Implements SUMOSAXAttributes.
Definition at line 248 of file SUMOSAXAttributesImpl_Binary.cpp.
References EDGEFUNC_NORMAL, SUMOXMLDefinitions::EdgeFunctions, myCharValues, StringBijection< T >::size(), and SUMO_ATTR_FUNCTION.
getFloat() [1/2]
double SUMOSAXAttributesImpl_Binary::getFloat (int id) const virtual
Returns the double-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2double. If the attribute is empty or ==0, TplConvert<XMLCh>::_2double throws an EmptyData-exception which is passed. If the value can not be parsed to a double, TplConvert<XMLCh>::_2double throws a NumberFormatException-exception which is passed.
Parameters
[in] id The id of the attribute to return the value of
Returns
The attribute's value as a float, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an double
Implements SUMOSAXAttributes.
Definition at line 219 of file SUMOSAXAttributesImpl_Binary.cpp.
References TplConvert::_2double(), getString(), and myFloatValues.
getFloat() [2/2]
double SUMOSAXAttributesImpl_Binary::getFloat (const std::string & id) const virtual
Returns the double-value of the named attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2double. If the attribute is empty or ==0, TplConvert<XMLCh>::_2double throws an EmptyData-exception which is passed. If the value can not be parsed to a double, TplConvert<XMLCh>::_2double throws a NumberFormatException-exception which is passed.
Parameters
[in] id The name of the attribute to return the value of
Returns
The attribute's value as a float, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an double
Implements SUMOSAXAttributes.
Definition at line 229 of file SUMOSAXAttributesImpl_Binary.cpp.
getInt()
int SUMOSAXAttributesImpl_Binary::getInt (int id) const virtual
Returns the int-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2int. If the attribute is empty or ==0, TplConvert<XMLCh>::_2int throws an EmptyData-exception which is passed. If the value can not be parsed to an int, TplConvert<XMLCh>::_2int throws a NumberFormatException-exception which is passed.
Parameters
[in] id The id of the attribute to return the value of
Returns
The attribute's value as an int, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an int
Implements SUMOSAXAttributes.
Definition at line 182 of file SUMOSAXAttributesImpl_Binary.cpp.
References myIntValues.
getInternal() [1/9]
template<> int SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 183 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getInt().
getInternal() [2/9]
template<> long long int SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 191 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getLong().
getInternal() [3/9]
template<> double SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 199 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getFloat().
getInternal() [4/9]
template<> bool SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 207 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getBool().
getInternal() [5/9]
template<> std::string SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 215 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getString().
getInternal() [6/9]
template<> RGBColor SUMOSAXAttributes::getInternal (const int) const inherited
Definition at line 227 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getColor().
getInternal() [7/9]
template<> PositionVector SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 235 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getShape().
getInternal() [8/9]
template<> Boundary SUMOSAXAttributes::getInternal (const int attr) const inherited
Definition at line 243 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::getBoundary().
getInternal() [9/9]
template<typename T > T SUMOSAXAttributes::getInternal (const int attr) const protected inherited
getLong()
long long int SUMOSAXAttributesImpl_Binary::getLong (int id) const virtual
Returns the long-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2long. If the attribute is empty or ==0, TplConvert<XMLCh>::_2long throws an EmptyData-exception which is passed. If the value can not be parsed to a long, TplConvert<XMLCh>::_2long throws a NumberFormatException-exception which is passed.
Parameters
[in] id The id of the attribute to return the value of
Returns
The attribute's value as an int, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
NumberFormatException If the attribute value can not be parsed to an int
Implements SUMOSAXAttributes.
Definition at line 192 of file SUMOSAXAttributesImpl_Binary.cpp.
getName()
std::string SUMOSAXAttributesImpl_Binary::getName (int attr) const virtual
Converts the given attribute id into a man readable string.
Returns a "?" if the attribute is not known.
Parameters
[in] attr The id of the attribute to return the name of
Returns
The name of the described attribute
Implements SUMOSAXAttributes.
Definition at line 319 of file SUMOSAXAttributesImpl_Binary.cpp.
References myAttrIds.
Referenced by serialize().
getNodeType()
SumoXMLNodeType SUMOSAXAttributesImpl_Binary::getNodeType (bool & ok) const virtual
Returns the value of the named attribute.
Tries to retrieve the attribute from the the attribute list.
Returns
The attribute's value as a string, if it could be read and parsed
Implements SUMOSAXAttributes.
Definition at line 262 of file SUMOSAXAttributesImpl_Binary.cpp.
References myCharValues, NODETYPE_UNKNOWN, SUMOXMLDefinitions::NodeTypes, StringBijection< T >::size(), and SUMO_ATTR_TYPE.
getObjectType()
const std::string& SUMOSAXAttributes::getObjectType () const inline inherited
return the objecttype to which these attributes belong
Definition at line 373 of file SUMOSAXAttributes.h.
References SUMOSAXAttributes::clone(), SUMOSAXAttributes::myObjectType, and SUMOSAXAttributes::operator<<.
Referenced by SUMOSAXAttributesImpl_Cached::clone(), SUMOSAXAttributesImpl_Xerces::clone(), clone(), SUMOVehicleParserHelper::parseGuiShape(), ODDistrictHandler::parseTAZ(), and SUMOVehicleParserHelper::parseVehicleClass().
getOpt()
template<typename T > T SUMOSAXAttributes::getOpt (int attr, const char * objectid, bool & ok, T defaultValue, bool report = true) const inherited
Tries to read given attribute assuming it is an int.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
If the value could be read, "ok" is not changed, and the value is returned.
Parameters
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns
The read value if given and correct; the default value if the attribute does not exist; -1 if an error occured
Definition at line 471 of file SUMOSAXAttributes.h.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLTriggerBuilder::addAccess(), NLDiscreteEventBuilder::addAction(), NIImporter_SUMO::addConnection(), NLHandler::addConnection(), NIXMLConnectionsHandler::addCrossing(), NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addE3Entry(), NLHandler::addE3Exit(), NIImporter_SUMO::addEdge(), NIXMLEdgesHandler::addEdge(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NIImporter_SUMO::addJunction(), NIImporter_SUMO::addLane(), NLHandler::addLane(), NIXMLEdgesHandler::addLane(), MSRouteHandler::addPersonTrip(), RORouteHandler::addPersonTrip(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NIImporter_SUMO::addProhibition(), NLHandler::addRequest(), NLHandler::addRouteProbeDetector(), NIXMLEdgesHandler::addSplit(), MSRouteHandler::addStop(), RORouteHandler::addStop(), NIXMLTrafficLightsHandler::addTlConnection(), MSRouteHandler::addWalk(), RORouteHandler::addWalk(), NIXMLConnectionsHandler::addWalkingArea(), NLHandler::addWAUTJunction(), NLHandler::beginE3Detector(), NLHandler::beginEdgeParsing(), SUMOVehicleParserHelper::beginVTypeParsing(), NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), NIXMLEdgesHandler::deleteEdge(), NLTriggerBuilder::getFileName(), GNEAdditionalHandler::getFileName(), NLTriggerBuilder::getPosition(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NLHandler::initTrafficLightLogic(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), PCTypeDefHandler::myStartElement(), NIXMLTypesHandler::myStartElement(), NIXMLConnectionsHandler::myStartElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), TrajectoriesHandler::myStartElement(), PCLoaderXML::myStartElement(), MSCalibrator::myStartElement(), NIImporter_SUMO::myStartElement(), MSLaneSpeedTrigger::myStartElement(), NLHandler::myStartElement(), NIImporter_MATSim::EdgesHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), SAXWeightsHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), PCLoaderOSM::RelationsHandler::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), NLHandler::openJunction(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), RORouteHandler::openRouteDistribution(), RONetHandler::parseAccess(), NLTriggerBuilder::parseAndAddLotEntry(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildRerouter(), NLTriggerBuilder::parseAndBuildStoppingPlace(), SUMOVehicleParserHelper::parseCommonAttributes(), RONetHandler::parseConnection(), RONetHandler::parseEdge(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), AGActivityGenHandler::parseGeneralCityInfo(), SUMOVehicleParserHelper::parseGuiShape(), RONetHandler::parseJunction(), RONetHandler::parseLane(), NIXMLConnectionsHandler::parseLaneBound(), AGActivityGenHandler::parseParameters(), SUMORouteHandler::parseStop(), RONetHandler::parseStoppingPlace(), SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParserHelper::parseVehicleClass(), MSRouteHandler::parseWalkPositions(), NIXMLNodesHandler::processNodeType(), NIXMLNodesHandler::processTrafficLightDefinitions(), NIImporter_SUMO::readPosition(), NIXMLEdgesHandler::tryGetLaneSpread(), NIXMLEdgesHandler::tryGetShape(), and SUMOSAXAttributes::~SUMOSAXAttributes().
getOptSUMOTimeReporting()
SUMOTime SUMOSAXAttributes::getOptSUMOTimeReporting (int attr, const char * objectid, bool & ok, SUMOTime defaultValue, bool report = true) const inherited
Tries to read given attribute assuming it is a SUMOTime.
If the attribute is not existing in the current element, the default value is returned. If an error occurs on parsing (the attribute is empty, it is not numeric), "ok" is set to false. If report is true an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
In dependence to the used time representation, either get<int> or get<double> is used.
Parameters
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] defaultValue The value to return if the attribute is not within the element
[in] report Whether errors shall be written to msg handler's error instance
Returns
The read value if given and correct; the default value if the attribute does not exist; -1 if an error occured
Definition at line 84 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getName(), and SUMOSAXAttributes::hasAttribute().
Referenced by NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), MSRouteHandler::addPersonTrip(), NIImporter_SUMO::addPhase(), NLHandler::addPhase(), NLHandler::addRouteProbeDetector(), MSRouteHandler::addWalk(), NLHandler::beginE3Detector(), NLHandler::initTrafficLightLogic(), GUISettingsHandler::myStartElement(), MSCalibrator::myStartElement(), MSTriggeredRerouter::myStartElement(), NLHandler::openWAUT(), NLTriggerBuilder::parseAndBuildCalibrator(), SUMORouteHandler::parseStop(), and SUMOSAXAttributes::~SUMOSAXAttributes().
getShape()
PositionVector SUMOSAXAttributesImpl_Binary::getShape (int attr) const virtual
Tries to read given attribute assuming it is a PositionVector.
Parameters
[in] attr The id of the attribute to read
Returns
The read value if given and not empty; "" if an error occured
Implements SUMOSAXAttributes.
Definition at line 287 of file SUMOSAXAttributesImpl_Binary.cpp.
References myPositionVectors.
getString()
std::string SUMOSAXAttributesImpl_Binary::getString (int id) const virtual
Returns the string-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2str. If the attribute is ==0, TplConvert<XMLCh>::_2str throws an EmptyData-exception which is passed.
Parameters
[in] id The id of the attribute to return the value of
Returns
The attribute's value as a string, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
Implements SUMOSAXAttributes.
Definition at line 198 of file SUMOSAXAttributesImpl_Binary.cpp.
References myStringValues.
Referenced by getFloat(), and getStringVector().
getStringSecure() [1/2]
std::string SUMOSAXAttributesImpl_Binary::getStringSecure (int id, const std::string & def) const virtual
Returns the string-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. The retrieved attribute (which may be 0) is then parsed using TplConvert<XMLCh>::_2strSec. If the attribute is ==0, TplConvert<XMLCh>::_2strSec returns the default value.
Parameters
[in] id The id of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns
The attribute's value as a string, if it could be read and parsed
Exceptions
EmptyData If the attribute is not known or the attribute value is an empty string
Implements SUMOSAXAttributes.
Definition at line 208 of file SUMOSAXAttributesImpl_Binary.cpp.
References myStringValues.
Referenced by serialize().
getStringSecure() [2/2]
std::string SUMOSAXAttributesImpl_Binary::getStringSecure (const std::string & id, const std::string & def) const virtual
Returns the string-value of the named (by its enum-value) attribute.
Tries to retrieve the attribute from the the attribute list. If the attribute is ==0, TplConvert<XMLCh>::_2strSec returns the default value.
Parameters
[in] id The name of the attribute to return the value of
[in] def The default value to return if the attribute is not in attributes
Returns
The attribute's value as a string, if it could be read and parsed
Implements SUMOSAXAttributes.
Definition at line 241 of file SUMOSAXAttributesImpl_Binary.cpp.
getStringVector()
std::vector< std::string > SUMOSAXAttributesImpl_Binary::getStringVector (int attr) const virtual
Tries to read given attribute assuming it is a string vector.
Parameters
[in] attr The id of the attribute to read
Returns
The read value if given and not empty; empty vector if an error occured
Implements SUMOSAXAttributes.
Definition at line 310 of file SUMOSAXAttributesImpl_Binary.cpp.
References getString(), and SUMOSAXAttributes::parseStringVector().
getSUMOTimeReporting()
SUMOTime SUMOSAXAttributes::getSUMOTimeReporting (int attr, const char * objectid, bool & ok, bool report = true) const inherited
Tries to read given attribute assuming it is a SUMOTime.
If an error occurs (the attribute is not there, it is not numeric), "ok" is set to false and an error message is written to MsgHandler::getErrorInstance.
Otherwise, "ok" is not changed.
In dependence to the used time representation, either get<int> or get<double> is used.
Parameters
[in] attr The id of the attribute to read
[in] objectid The name of the parsed object; used for error message generation
[out] ok Whether the value could be read
[in] report Whether errors shall be written to msg handler's error instance
Returns
The read value if given and correct; -1 if an error occured
Definition at line 58 of file SUMOSAXAttributes.cpp.
References SUMOSAXAttributes::emitEmptyError(), SUMOSAXAttributes::emitFormatError(), SUMOSAXAttributes::emitUngivenError(), SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getName(), SUMOSAXAttributes::hasAttribute(), and TIME2STEPS.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addPhase(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::addWAUTSwitch(), NLHandler::beginE3Detector(), SUMOVehicleParserHelper::beginVTypeParsing(), NLTriggerBuilder::buildVaporizer(), SUMORouteHandler::myStartElement(), TrajectoriesHandler::myStartElement(), MSCalibrator::myStartElement(), MSLaneSpeedTrigger::myStartElement(), SUMOVehicleParserHelper::parseFlowAttributes(), and SUMOSAXAttributes::~SUMOSAXAttributes().
hasAttribute() [1/2]
bool SUMOSAXAttributesImpl_Binary::hasAttribute (int id) const virtual
Returns the information whether the named (by its enum-value) attribute is within the current list.
Parameters
[in] id The id of the searched attribute
Returns
Whether the attribute is within the attributes
Implements SUMOSAXAttributes.
Definition at line 166 of file SUMOSAXAttributesImpl_Binary.cpp.
References myAttrs.
hasAttribute() [2/2]
bool SUMOSAXAttributesImpl_Binary::hasAttribute (const std::string & id) const virtual
Returns the information whether the named attribute is within the current list.
Implements SUMOSAXAttributes.
Definition at line 235 of file SUMOSAXAttributesImpl_Binary.cpp.
operator=()
SUMOSAXAttributesImpl_Binary& SUMOSAXAttributesImpl_Binary::operator= (const SUMOSAXAttributesImpl_Binary & src) private
Invalidated assignment operator.
parseStringSet()
void SUMOSAXAttributes::parseStringSet (const std::string & def, std::set< std::string > & into) static inherited
Splits the given string, stores it in a set.
Spaces, ",", and ";" are assumed to be separator characters. Though, in the case a "," or a ";" occurs, a warning is generated (once).
Parameters
[in] def The string to split
[out] into The set to fill
Definition at line 166 of file SUMOSAXAttributes.cpp.
References StringTokenizer::hasNext(), SUMOSAXAttributes::myHaveInformedAboutDeprecatedDivider, StringTokenizer::next(), and WRITE_WARNING.
Referenced by SUMORouteHandler::parseStop().
parseStringVector()
void SUMOSAXAttributes::parseStringVector (const std::string & def, std::vector< std::string > & into) static inherited
Splits the given string.
Spaces, ",", and ";" are assumed to be separator characters. Though, in the case a "," or a ";" occurs, a warning is generated (once).
Parameters
[in] def The string to split
[out] into The vector to fill
Definition at line 151 of file SUMOSAXAttributes.cpp.
References StringTokenizer::hasNext(), SUMOSAXAttributes::myHaveInformedAboutDeprecatedDivider, StringTokenizer::next(), and WRITE_WARNING.
Referenced by NIXMLConnectionsHandler::addCrossing(), NIImporter_SUMO::addEdge(), NIImporter_SUMO::addJunction(), NIXMLEdgesHandler::addSplit(), NIXMLConnectionsHandler::addWalkingArea(), SUMOSAXAttributesImpl_Cached::getStringVector(), SUMOSAXAttributesImpl_Xerces::getStringVector(), getStringVector(), MSStateHandler::myStartElement(), GNEDialog_AllowDisallow::onCmdReset(), GNEAttributeCarrier::parse(), NLTriggerBuilder::parseAndBeginParkingArea(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLTriggerBuilder::parseAndBuildRerouter(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and NIXMLNodesHandler::processTrafficLightDefinitions().
serialize()
void SUMOSAXAttributesImpl_Binary::serialize (std::ostream & os) const virtual
Prints all attribute names and values into the given stream.
Parameters
[in] os The stream to use
Implements SUMOSAXAttributes.
Definition at line 328 of file SUMOSAXAttributesImpl_Binary.cpp.
References getName(), getStringSecure(), and myAttrs.
Field Documentation
ENCODING
const std::string SUMOSAXAttributes::ENCODING = " encoding=\"UTF-8\"" static inherited
The encoding of parsed strings.
Definition at line 384 of file SUMOSAXAttributes.h.
Referenced by OptionsCont::writeConfiguration(), OptionsCont::writeSchema(), and OptionsCont::writeXMLHeader().
myAttrIds
const std::map<int, std::string>& SUMOSAXAttributesImpl_Binary::myAttrIds private
Map of attribute ids to names.
Definition at line 294 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by clone(), and getName().
myAttrs
std::set<int> SUMOSAXAttributesImpl_Binary::myAttrs private
the attributes which are set
Definition at line 297 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by hasAttribute(), serialize(), and SUMOSAXAttributesImpl_Binary().
myCharValues
std::map<int, char> SUMOSAXAttributesImpl_Binary::myCharValues private
Map of attribute ids to char.
Definition at line 300 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by clone(), getBool(), getEdgeFunc(), getNodeType(), and SUMOSAXAttributesImpl_Binary().
myFloatValues
std::map<int, double> SUMOSAXAttributesImpl_Binary::myFloatValues private
Map of attribute ids to floats.
Definition at line 306 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by clone(), getFloat(), and SUMOSAXAttributesImpl_Binary().
myIntValues
std::map<int, int> SUMOSAXAttributesImpl_Binary::myIntValues private
Map of attribute ids to integers.
Definition at line 303 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by clone(), getColor(), getInt(), and SUMOSAXAttributesImpl_Binary().
myPositionVectors
std::map<int, PositionVector> SUMOSAXAttributesImpl_Binary::myPositionVectors private
Map of attribute ids to string.
Definition at line 312 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by clone(), getBoundary(), getShape(), and SUMOSAXAttributesImpl_Binary().
myStringValues
std::map<int, std::string> SUMOSAXAttributesImpl_Binary::myStringValues private
Map of attribute ids to string.
Definition at line 309 of file SUMOSAXAttributesImpl_Binary.h.
Referenced by clone(), getString(), getStringSecure(), and SUMOSAXAttributesImpl_Binary().
The documentation for this class was generated from the following files:
SUMOSAXAttributesImpl_Binary.h
SUMOSAXAttributesImpl_Binary.cpp