SUMO - Simulation of Urban MObility: MSPModel_NonInteracting::MoveToNextEdge Class Reference
MSPModel_NonInteracting::MoveToNextEdge Class Reference
Public Member Functions
void abortWalk ()
SUMOTime execute (SUMOTime currentTime)
Executes the command.
const MSPerson * getPerson () const
MoveToNextEdge (MSPerson *person, MSPerson::MSPersonStage_Walking &walk)
~MoveToNextEdge ()
Private Member Functions
MoveToNextEdge & operator= (const MoveToNextEdge &)
Invalidated assignment operator.
Private Attributes
MSPerson::MSPersonStage_Walking & myParent
MSPerson * myPerson
Detailed Description
Definition at line 75 of file MSPModel_NonInteracting.h.
Constructor & Destructor Documentation
MoveToNextEdge()
MSPModel_NonInteracting::MoveToNextEdge::MoveToNextEdge (MSPerson * person, MSPerson::MSPersonStage_Walking & walk) inline
Definition at line 77 of file MSPModel_NonInteracting.h.
~MoveToNextEdge()
MSPModel_NonInteracting::MoveToNextEdge::~MoveToNextEdge () inline
Definition at line 78 of file MSPModel_NonInteracting.h.
References execute().
Member Function Documentation
abortWalk()
void MSPModel_NonInteracting::MoveToNextEdge::abortWalk () inline
Definition at line 80 of file MSPModel_NonInteracting.h.
References myPerson.
execute()
SUMOTime MSPModel_NonInteracting::MoveToNextEdge::execute (SUMOTime currentTime) virtual
Executes the command.
The implementations should return 0 if the command shall not be repeated, or a value larger than 0 that describe the time after which the command shall be executed again. Values below 0 must not be returned.
Parameters
[in] currentTime The current simulation time
Returns
The time after which the command shall be executed again, 0 if this command shall be descheduled.
Exceptions
ProcessError Derived actions may throw this exception
Implements Command.
Definition at line 94 of file MSPModel_NonInteracting.cpp.
References MSPModel_NonInteracting::PState::computeWalkingTime().
Referenced by ~MoveToNextEdge().
getPerson()
const MSPerson* MSPModel_NonInteracting::MoveToNextEdge::getPerson () const inline
Definition at line 83 of file MSPModel_NonInteracting.h.
References myPerson.
operator=()
MoveToNextEdge& MSPModel_NonInteracting::MoveToNextEdge::operator= (const MoveToNextEdge &) private
Invalidated assignment operator.
Field Documentation
myParent
MSPerson::MSPersonStage_Walking& MSPModel_NonInteracting::MoveToNextEdge::myParent private
Definition at line 88 of file MSPModel_NonInteracting.h.
myPerson
MSPerson* MSPModel_NonInteracting::MoveToNextEdge::myPerson private
Definition at line 89 of file MSPModel_NonInteracting.h.
Referenced by abortWalk(), and getPerson().
The documentation for this class was generated from the following files:
MSPModel_NonInteracting.h
MSPModel_NonInteracting.cpp