SUMO - Simulation of Urban MObility: GUIGlChildWindow Class Reference
GUIGlChildWindow Class Reference
#include <GUIGlChildWindow.h>
Public Member Functions
void buildColoringToolBar ()
void buildNavigationToolBar ()
void buildScreenshotToolBar ()
virtual void create ()
virtual FXGLCanvas * getBuildGLCanvas () const
FXComboBox & getColoringSchemesCombo ()
FXPopup * getLocatorPopup ()
FXToolBar & getNavigationToolBar (GUISUMOAbstractView &v)
GUIMainWindow * getParent ()
Returns the main window.
GUISUMOAbstractView * getView () const
GUIGlChildWindow (FXMDIClient *p, GUIMainWindow *parentWindow, FXMDIMenu *mdimenu, const FXString &name, FXIcon *ic=NULL, FXuint opts=0, FXint x=0, FXint y=0, FXint w=0, FXint h=0)
virtual bool isSelected (GUIGlObject *o) const
true if the object is selected (may include extra logic besides calling gSelected)
long onCmdChangeColorScheme (FXObject *, FXSelector sel, void *)
long onCmdEditViewport (FXObject *, FXSelector, void *)
long onCmdEditViewScheme (FXObject *, FXSelector, void *)
long onCmdRecenterView (FXObject *, FXSelector, void *)
long onCmdShowToolTips (FXObject *sender, FXSelector, void *)
long onCmdZoomStyle (FXObject *sender, FXSelector, void *)
void setView (GUIGlID id)
Centers the view onto the given artifact.
virtual ~GUIGlChildWindow ()
Protected Member Functions
GUIGlChildWindow ()
Protected Attributes
FXComboBox * myColoringSchemes
FXVerticalFrame * myContentFrame
FXMenuButton * myLocatorButton
FXPopup * myLocatorPopup
The locator menu.
FXToolBar * myNavigationToolBar
The tool bar.
GUIMainWindow * myParent
The parent window.
GUISUMOAbstractView * myView
the view
Detailed Description
Definition at line 47 of file GUIGlChildWindow.h.
Constructor & Destructor Documentation
GUIGlChildWindow() [1/2]
GUIGlChildWindow::GUIGlChildWindow (FXMDIClient * p, GUIMainWindow * parentWindow, FXMDIMenu * mdimenu, const FXString & name, FXIcon * ic = NULL, FXuint opts = 0, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0)
Definition at line 58 of file GUIGlChildWindow.cpp.
References GUIDesignFrameArea.
~GUIGlChildWindow()
GUIGlChildWindow::~GUIGlChildWindow () virtual
Definition at line 77 of file GUIGlChildWindow.cpp.
References myLocatorPopup, and myNavigationToolBar.
GUIGlChildWindow() [2/2]
GUIGlChildWindow::GUIGlChildWindow () inline protected
Definition at line 117 of file GUIGlChildWindow.h.
Member Function Documentation
buildColoringToolBar()
void GUIGlChildWindow::buildColoringToolBar ()
Definition at line 126 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignComboBoxNCol, GUIDesignComboBoxStatic, GUIDesignVerticalSeparator, ICON_COLORWHEEL, MID_COLOURSCHEMECHANGE, MID_EDITVIEWSCHEME, myColoringSchemes, and myNavigationToolBar.
Referenced by getView().
buildNavigationToolBar()
void GUIGlChildWindow::buildNavigationToolBar ()
Definition at line 93 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignBar, GUIDesignButtonToolbar, GUIDesignButtonToolbarCheckable, GUIDesignButtonToolbarLocator, ICON_EDITVIEWPORT, ICON_LOCATE, ICON_RECENTERVIEW, ICON_SHOWTOOLTIPS, ICON_ZOOMSTYLE, MID_EDITVIEWPORT, MID_RECENTERVIEW, MID_SHOWTOOLTIPS, MID_ZOOM_STYLE, myContentFrame, myLocatorButton, myLocatorPopup, myNavigationToolBar, and MFXCheckableButton::setChecked().
Referenced by getView().
buildScreenshotToolBar()
void GUIGlChildWindow::buildScreenshotToolBar ()
Definition at line 141 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignVerticalSeparator, ICON_CAMERA, MID_MAKESNAPSHOT, and myNavigationToolBar.
Referenced by getView().
create()
void GUIGlChildWindow::create () virtual
Definition at line 84 of file GUIGlChildWindow.cpp.
References myLocatorPopup, myNavigationToolBar, and myView.
Referenced by GNEViewParent::GNEViewParent(), and GUIApplicationWindow::openNewView().
getBuildGLCanvas()
FXGLCanvas * GUIGlChildWindow::getBuildGLCanvas () const virtual
Definition at line 152 of file GUIGlChildWindow.cpp.
References myView.
Referenced by GUIApplicationWindow::getBuildGLCanvas(), and GNEApplicationWindow::getBuildGLCanvas().
getColoringSchemesCombo()
FXComboBox & GUIGlChildWindow::getColoringSchemesCombo ()
Definition at line 170 of file GUIGlChildWindow.cpp.
References myColoringSchemes.
Referenced by GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), GUISUMOAbstractView::getColoringSchemesCombo(), and getView().
getLocatorPopup()
FXPopup * GUIGlChildWindow::getLocatorPopup ()
Definition at line 164 of file GUIGlChildWindow.cpp.
References myLocatorPopup.
Referenced by GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), and getView().
getNavigationToolBar()
FXToolBar & GUIGlChildWindow::getNavigationToolBar (GUISUMOAbstractView & v)
Definition at line 158 of file GUIGlChildWindow.cpp.
References myNavigationToolBar.
Referenced by getView().
getParent()
GUIMainWindow* GUIGlChildWindow::getParent () inline
Returns the main window.
Returns
This view's parent
Definition at line 88 of file GUIGlChildWindow.h.
References isSelected(), and myParent.
Referenced by GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser().
getView()
GUISUMOAbstractView* GUIGlChildWindow::getView () const inline
Definition at line 59 of file GUIGlChildWindow.h.
References buildColoringToolBar(), buildNavigationToolBar(), buildScreenshotToolBar(), getColoringSchemesCombo(), getLocatorPopup(), getNavigationToolBar(), myView, onCmdChangeColorScheme(), onCmdEditViewport(), onCmdEditViewScheme(), onCmdRecenterView(), onCmdShowToolTips(), onCmdZoomStyle(), and setView().
Referenced by GUIMainWindow::getActiveView(), TraCIServerAPI_GUI::getNamedView(), GUIApplicationWindow::onCmdEditChosen(), GUIApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdShowStats(), GUIDialog_GLObjChooser::onCmdToggleSelection(), GUIApplicationWindow::openNewView(), and GNEApplicationWindow::openNewView().
isSelected()
bool GUIGlChildWindow::isSelected (GUIGlObject * o) const virtual
true if the object is selected (may include extra logic besides calling gSelected)
Reimplemented in GNEViewParent, and GUISUMOViewParent.
Definition at line 236 of file GUIGlChildWindow.cpp.
References GUIGlObject::getGlID(), GUIGlObject::getType(), gSelected, and GUISelectedStorage::isSelected().
Referenced by getParent().
onCmdChangeColorScheme()
long GUIGlChildWindow::onCmdChangeColorScheme (FXObject * , FXSelector sel, void * data)
Definition at line 221 of file GUIGlChildWindow.cpp.
References myView, and GUISUMOAbstractView::setColorScheme().
Referenced by getView().
onCmdEditViewport()
long GUIGlChildWindow::onCmdEditViewport (FXObject * , FXSelector , void *)
Definition at line 184 of file GUIGlChildWindow.cpp.
References myView, and GUISUMOAbstractView::showViewportEditor().
Referenced by getView().
onCmdEditViewScheme()
long GUIGlChildWindow::onCmdEditViewScheme (FXObject * , FXSelector , void *)
Definition at line 191 of file GUIGlChildWindow.cpp.
References myView, and GUISUMOAbstractView::showViewschemeEditor().
Referenced by getView().
onCmdRecenterView()
long GUIGlChildWindow::onCmdRecenterView (FXObject * , FXSelector , void *)
Definition at line 176 of file GUIGlChildWindow.cpp.
References myView, and GUISUMOAbstractView::recenterView().
Referenced by getView().
onCmdShowToolTips()
long GUIGlChildWindow::onCmdShowToolTips (FXObject * sender, FXSelector , void *)
Definition at line 198 of file GUIGlChildWindow.cpp.
References MFXCheckableButton::amChecked(), myView, MFXCheckableButton::setChecked(), and GUISUMOAbstractView::showToolTips().
Referenced by getView().
onCmdZoomStyle()
long GUIGlChildWindow::onCmdZoomStyle (FXObject * sender, FXSelector , void *)
Definition at line 209 of file GUIGlChildWindow.cpp.
References MFXCheckableButton::amChecked(), myView, and MFXCheckableButton::setChecked().
Referenced by getView().
setView()
void GUIGlChildWindow::setView (GUIGlID id)
Centers the view onto the given artifact.
Parameters
[in] id The id of the object to center the view on
Definition at line 228 of file GUIGlChildWindow.cpp.
References GUISUMOAbstractView::centerTo(), and myView.
Referenced by getView(), GUIDialog_GLObjChooser::onCmdCenter(), GUIDialog_GLObjChooser::onCmdText(), and GUIMessageWindow::setCursorPos().
Field Documentation
myColoringSchemes
FXComboBox* GUIGlChildWindow::myColoringSchemes protected
Definition at line 110 of file GUIGlChildWindow.h.
Referenced by buildColoringToolBar(), and getColoringSchemesCombo().
myContentFrame
FXVerticalFrame* GUIGlChildWindow::myContentFrame protected
Definition at line 108 of file GUIGlChildWindow.h.
Referenced by buildNavigationToolBar(), and GUISUMOViewParent::init().
myLocatorButton
FXMenuButton* GUIGlChildWindow::myLocatorButton protected
Definition at line 106 of file GUIGlChildWindow.h.
Referenced by buildNavigationToolBar(), GUISUMOViewParent::onCmdLocate(), and GNEViewParent::onCmdLocate().
myLocatorPopup
FXPopup* GUIGlChildWindow::myLocatorPopup protected
The locator menu.
Definition at line 105 of file GUIGlChildWindow.h.
Referenced by buildNavigationToolBar(), create(), getLocatorPopup(), GUISUMOViewParent::onCmdLocate(), GNEViewParent::onCmdLocate(), and ~GUIGlChildWindow().
myNavigationToolBar
FXToolBar* GUIGlChildWindow::myNavigationToolBar protected
The tool bar.
Definition at line 102 of file GUIGlChildWindow.h.
Referenced by buildColoringToolBar(), buildNavigationToolBar(), buildScreenshotToolBar(), create(), getNavigationToolBar(), GUISUMOViewParent::init(), GUISUMOViewParent::setToolBarVisibility(), and ~GUIGlChildWindow().
myParent
GUIMainWindow* GUIGlChildWindow::myParent protected
The parent window.
Definition at line 113 of file GUIGlChildWindow.h.
Referenced by GNEViewParent::getApp(), getParent(), GUISUMOViewParent::init(), GNEViewParent::onCmdClose(), GUISUMOViewParent::onCmdLocate(), GNEViewParent::~GNEViewParent(), and GUISUMOViewParent::~GUISUMOViewParent().
myView
GUISUMOAbstractView* GUIGlChildWindow::myView protected
the view
Definition at line 99 of file GUIGlChildWindow.h.
Referenced by create(), getBuildGLCanvas(), getView(), GUISUMOViewParent::init(), onCmdChangeColorScheme(), onCmdEditViewport(), onCmdEditViewScheme(), GNEViewParent::onCmdLocate(), GUISUMOViewParent::onCmdMakeSnapshot(), GNEViewParent::onCmdMakeSnapshot(), onCmdRecenterView(), onCmdShowToolTips(), onCmdZoomStyle(), GUISUMOViewParent::onKeyPress(), GNEViewParent::onKeyPress(), GUISUMOViewParent::onKeyRelease(), GNEViewParent::onKeyRelease(), GUISUMOViewParent::onSimStep(), and setView().
The documentation for this class was generated from the following files:
GUIGlChildWindow.h
GUIGlChildWindow.cpp