SUMO - Simulation of Urban MObility: MSTransportableControl Class Reference
MSTransportableControl Class Reference
#include <MSTransportableControl.h>
Public Types
typedef std::map< std::string, MSTransportable * >::const_iterator constVehIt
Definition of the internal transportables map iterator.
typedef std::vector< MSTransportable * > TransportableVector
Definition of a list of transportables.
Public Member Functions
void abortWaiting (MSTransportable *t)
aborts waiting stage of transportable
void abortWaitingForVehicle ()
aborts the plan for any transportable that is still waiting for a ride
bool add (MSTransportable *transportable)
Adds a single transportable, returns false if an id clash occured.
void addWaiting (const MSEdge *edge, MSTransportable *person)
adds a transportable to the list of transportables waiting for a vehicle on the specified edge
bool boardAnyWaiting (MSEdge *edge, MSVehicle *vehicle, MSVehicle::Stop *stop)
board any applicable persons Boards any people who wait on that edge for the given vehicle and removes them from myWaiting
virtual MSTransportable * buildContainer (const SUMOVehicleParameter *pars, MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan) const
Builds a new container.
virtual MSTransportable * buildPerson (const SUMOVehicleParameter *pars, MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan, std::mt19937 *rng) const
Builds a new person.
void checkWaiting (MSNet *net, const SUMOTime time)
checks whether any transportables waiting time is over
virtual void erase (MSTransportable *transportable)
removes a single transportable
MSTransportable * get (const std::string &id) const
Returns the named transportable, if existing.
bool hasNonWaiting () const
checks whether any transportable is still engaged in walking / stopping
bool hasTransportables () const
checks whether any transportable waits to finish her plan
bool loadAnyWaiting (MSEdge *edge, MSVehicle *vehicle, MSVehicle::Stop *stop)
load any applicable containers Loads any container that is waiting on that edge for the given vehicle and removes them from myWaiting
constVehIt loadedBegin () const
Returns the begin of the internal transportables map.
constVehIt loadedEnd () const
Returns the end of the internal transportables map.
MSTransportableControl ()
Constructor.
void registerJammed ()
register a jammed transportable
void setWaitEnd (SUMOTime time, MSTransportable *transportable)
sets the arrival time for a waiting transportable
int size () const
Returns the number of known transportables.
virtual ~MSTransportableControl ()
Destructor.
Retrieval of transportable statistics (always accessable)
int getLoadedNumber () const
Returns the number of build transportables.
int getRunningNumber () const
Returns the number of build and inserted, but not yet deleted transportables.
int getJammedNumber () const
Returns the number of times a transportables was jammed.
Protected Attributes
bool myHaveNewWaiting
whether a new transportable waiting for a vehicle has been added in the last step
int myJammedNumber
The number of jammed transportables.
int myLoadedNumber
The number of build transportables.
int myRunningNumber
The number of transportables within the network (build and inserted but not removed)
std::map< std::string, MSTransportable * > myTransportables
all currently created transportables by id
std::map< SUMOTime, TransportableVector > myWaiting4Departure
Transportables waiting for departure.
std::map< const MSEdge *, TransportableVector > myWaiting4Vehicle
the lists of waiting transportables
int myWaitingForVehicleNumber
The number of transportables waiting for vehicles.
std::map< SUMOTime, TransportableVector > myWaitingUntil
the lists of walking / stopping transportables
Detailed Description
The class is used to handle transportables (persons and containers) who are not using a transportation system but are walking or waiting. This includes waiting for the arrival or departure time / the time the waiting is over.
Definition at line 58 of file MSTransportableControl.h.
Member Typedef Documentation
constVehIt
typedef std::map<std::string, MSTransportable*>::const_iterator MSTransportableControl::constVehIt
Definition of the internal transportables map iterator.
Definition at line 64 of file MSTransportableControl.h.
TransportableVector
typedef std::vector<MSTransportable*> MSTransportableControl::TransportableVector
Definition of a list of transportables.
Definition at line 61 of file MSTransportableControl.h.
Constructor & Destructor Documentation
MSTransportableControl()
MSTransportableControl::MSTransportableControl ()
Constructor.
Definition at line 49 of file MSTransportableControl.cpp.
~MSTransportableControl()
MSTransportableControl::~MSTransportableControl () virtual
Destructor.
Definition at line 58 of file MSTransportableControl.cpp.
References myTransportables, and myWaiting4Vehicle.
Member Function Documentation
abortWaiting()
void MSTransportableControl::abortWaiting (MSTransportable * t)
aborts waiting stage of transportable
Definition at line 275 of file MSTransportableControl.cpp.
References myWaiting4Departure.
Referenced by MSTransportable::Stage_Waiting::abort().
abortWaitingForVehicle()
void MSTransportableControl::abortWaitingForVehicle ()
aborts the plan for any transportable that is still waiting for a ride
Definition at line 250 of file MSTransportableControl.cpp.
References erase(), MSTransportable::getCurrentStage(), MSTransportable::getID(), MSNet::getInstance(), MSTransportable::Stage_Driving::getWaitingDescription(), myWaiting4Vehicle, MSEdge::removeContainer(), MSEdge::removePerson(), MSTransportable::setDeparted(), and WRITE_WARNING.
Referenced by MSNet::simulationState().
add()
bool MSTransportableControl::add (MSTransportable * transportable)
Adds a single transportable, returns false if an id clash occured.
Parameters
[in] transportable The transportable to add
Returns
Whether the transportable could be added (none with the same id existed before)
Definition at line 68 of file MSTransportableControl.cpp.
References DELTA_T, SUMOVehicleParameter::depart, MSTransportable::getParameter(), SUMOVehicleParameter::id, myLoadedNumber, myTransportables, and myWaiting4Departure.
Referenced by libsumo::Person::add().
addWaiting()
void MSTransportableControl::addWaiting (const MSEdge * edge, MSTransportable * person)
adds a transportable to the list of transportables waiting for a vehicle on the specified edge
Definition at line 152 of file MSTransportableControl.cpp.
References myHaveNewWaiting, myWaiting4Vehicle, and myWaitingForVehicleNumber.
Referenced by MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
boardAnyWaiting()
bool MSTransportableControl::boardAnyWaiting (MSEdge * edge, MSVehicle * vehicle, MSVehicle::Stop * stop)
board any applicable persons Boards any people who wait on that edge for the given vehicle and removes them from myWaiting
Parameters
[in] the edge on which the boarding should take place
[in] the vehicle which is taking on passengers / goods
[in] the stop at which the vehicle is stopping
Returns
Whether any transportables have been boarded
Definition at line 160 of file MSTransportableControl.cpp.
References MSVehicle::addPerson(), DELTA_T, MSVehicle::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSVehicleType::getBoardingDuration(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSVehicleType::getPersonCapacity(), MSVehicle::getPersonNumber(), MSBaseVehicle::getVehicleType(), SUMOVehicleParameter::id, SUMOVehicleParameter::line, myWaiting4Vehicle, myWaitingForVehicleNumber, MSVehicle::Stop::pars, MSEdge::removePerson(), SUMOVehicleParameter::Stop::startPos, and MSVehicle::Stop::timeToBoardNextPerson.
Referenced by MSVehicle::processNextStop().
buildContainer()
MSTransportable * MSTransportableControl::buildContainer (const SUMOVehicleParameter * pars, MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan) const virtual
Builds a new container.
Parameters
[in] pars The parameter
[in] vtype The type (reusing vehicle type container here)
[in] plan This container's plan
Reimplemented in GUITransportableControl.
Definition at line 302 of file MSTransportableControl.cpp.
Referenced by MSRouteHandler::closeContainer().
buildPerson()
MSTransportable * MSTransportableControl::buildPerson (const SUMOVehicleParameter * pars, MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan, std::mt19937 * rng) const virtual
Builds a new person.
Parameters
[in] pars The parameter
[in] vtype The type (reusing vehicle type container here)
[in] plan This person's plan
[in] rng The RNG to compute the optional speed deviation
Reimplemented in GUITransportableControl.
Definition at line 294 of file MSTransportableControl.cpp.
References MSVehicleType::computeChosenSpeedDeviation().
Referenced by libsumo::Person::add(), and MSRouteHandler::closePerson().
checkWaiting()
void MSTransportableControl::checkWaiting (MSNet * net, const SUMOTime time)
checks whether any transportables waiting time is over
Definition at line 124 of file MSTransportableControl.cpp.
References erase(), myHaveNewWaiting, myRunningNumber, myWaiting4Departure, and myWaitingUntil.
Referenced by MSNet::simulationStep().
erase()
void MSTransportableControl::erase (MSTransportable * transportable) virtual
removes a single transportable
Definition at line 92 of file MSTransportableControl.cpp.
References OutputDevice::getDeviceByOption(), MSTransportable::getID(), OptionsCont::getOptions(), myRunningNumber, myTransportables, MSTransportable::routeOutput(), and MSTransportable::tripInfoOutput().
Referenced by abortWaitingForVehicle(), checkWaiting(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSDevice_Transportable::notifyLeave(), MSDevice_Transportable::notifyMove(), and MSPerson::MSPersonStage_Walking::proceed().
get()
MSTransportable * MSTransportableControl::get (const std::string & id) const
Returns the named transportable, if existing.
Parameters
[in] id The id of the transportable
Returns
The named transportable, if existing, otherwise 0
Definition at line 82 of file MSTransportableControl.cpp.
References myTransportables.
Referenced by libsumo::Person::getPerson(), TraCIServerAPI_Person::getPosition(), TraCIServer::postProcessSimulationStep(), and TraCIServerAPI_Person::processSet().
getJammedNumber()
int MSTransportableControl::getJammedNumber () const inline
Returns the number of times a transportables was jammed.
Returns
The number of times transportables were jammed
Definition at line 196 of file MSTransportableControl.h.
References myJammedNumber.
Referenced by MSNet::closeSimulation(), and GUINet::getParameterWindow().
getLoadedNumber()
int MSTransportableControl::getLoadedNumber () const inline
Returns the number of build transportables.
Returns
The number of loaded (build) transportables
Definition at line 181 of file MSTransportableControl.h.
References myLoadedNumber.
Referenced by MSNet::closeSimulation(), and GUINet::getParameterWindow().
getRunningNumber()
int MSTransportableControl::getRunningNumber () const inline
Returns the number of build and inserted, but not yet deleted transportables.
Returns
The number of simulated transportables
Definition at line 189 of file MSTransportableControl.h.
References myRunningNumber.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and GUIApplicationWindow::handleEvent_SimulationStep().
hasNonWaiting()
bool MSTransportableControl::hasNonWaiting () const
checks whether any transportable is still engaged in walking / stopping
Definition at line 244 of file MSTransportableControl.cpp.
References myHaveNewWaiting, myRunningNumber, myWaiting4Departure, and myWaitingForVehicleNumber.
Referenced by MSNet::simulationState().
hasTransportables()
bool MSTransportableControl::hasTransportables () const
checks whether any transportable waits to finish her plan
Definition at line 238 of file MSTransportableControl.cpp.
References myTransportables.
Referenced by MSNet::simulationStep(), and MSFCDExport::write().
loadAnyWaiting()
bool MSTransportableControl::loadAnyWaiting (MSEdge * edge, MSVehicle * vehicle, MSVehicle::Stop * stop)
load any applicable containers Loads any container that is waiting on that edge for the given vehicle and removes them from myWaiting
Parameters
[in] the edge on which the loading should take place
[in] the vehicle which is taking on containers
Returns
Whether any containers have been loaded
Definition at line 200 of file MSTransportableControl.cpp.
References MSVehicle::addContainer(), MSVehicle::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSVehicleType::getContainerCapacity(), MSVehicle::getContainerNumber(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicleType::getLoadingDuration(), MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), SUMOVehicleParameter::id, SUMOVehicleParameter::line, myWaiting4Vehicle, myWaitingForVehicleNumber, MSVehicle::Stop::pars, MSEdge::removeContainer(), SUMOVehicleParameter::Stop::startPos, and MSVehicle::Stop::timeToLoadNextContainer.
Referenced by MSVehicle::processNextStop().
loadedBegin()
constVehIt MSTransportableControl::loadedBegin () const inline
Returns the begin of the internal transportables map.
Returns
The begin of the internal transportables map
Definition at line 150 of file MSTransportableControl.h.
References myTransportables.
Referenced by libsumo::Person::getIDList().
loadedEnd()
constVehIt MSTransportableControl::loadedEnd () const inline
Returns the end of the internal transportables map.
Returns
The end of the internal transportables map
Definition at line 158 of file MSTransportableControl.h.
References myTransportables.
Referenced by libsumo::Person::getIDList().
registerJammed()
void MSTransportableControl::registerJammed () inline
register a jammed transportable
Definition at line 171 of file MSTransportableControl.h.
References myJammedNumber.
Referenced by MSPModel_Striping::PState::walk().
setWaitEnd()
void MSTransportableControl::setWaitEnd (SUMOTime time, MSTransportable * transportable)
sets the arrival time for a waiting transportable
Definition at line 113 of file MSTransportableControl.cpp.
References DELTA_T, myWaiting4Departure, and myWaitingUntil.
Referenced by MSTransportable::Stage_Waiting::proceed().
size()
int MSTransportableControl::size () const inline
Returns the number of known transportables.
Returns
The number of stored transportables
Definition at line 166 of file MSTransportableControl.h.
References myTransportables.
Referenced by libsumo::Person::getIDCount().
Field Documentation
myHaveNewWaiting
bool MSTransportableControl::myHaveNewWaiting protected
whether a new transportable waiting for a vehicle has been added in the last step
Definition at line 228 of file MSTransportableControl.h.
Referenced by addWaiting(), checkWaiting(), and hasNonWaiting().
myJammedNumber
int MSTransportableControl::myJammedNumber protected
The number of jammed transportables.
Definition at line 222 of file MSTransportableControl.h.
Referenced by getJammedNumber(), and registerJammed().
myLoadedNumber
int MSTransportableControl::myLoadedNumber protected
The number of build transportables.
Definition at line 216 of file MSTransportableControl.h.
Referenced by add(), and getLoadedNumber().
myRunningNumber
int MSTransportableControl::myRunningNumber protected
The number of transportables within the network (build and inserted but not removed)
Definition at line 219 of file MSTransportableControl.h.
Referenced by checkWaiting(), erase(), getRunningNumber(), and hasNonWaiting().
myTransportables
std::map<std::string, MSTransportable*> MSTransportableControl::myTransportables protected
all currently created transportables by id
Definition at line 204 of file MSTransportableControl.h.
Referenced by add(), erase(), get(), hasTransportables(), GUITransportableControl::insertPersonIDs(), loadedBegin(), loadedEnd(), size(), and ~MSTransportableControl().
myWaiting4Departure
std::map<SUMOTime, TransportableVector> MSTransportableControl::myWaiting4Departure protected
Transportables waiting for departure.
Definition at line 207 of file MSTransportableControl.h.
Referenced by abortWaiting(), add(), checkWaiting(), hasNonWaiting(), and setWaitEnd().
myWaiting4Vehicle
std::map<const MSEdge*, TransportableVector> MSTransportableControl::myWaiting4Vehicle protected
the lists of waiting transportables
Definition at line 213 of file MSTransportableControl.h.
Referenced by abortWaitingForVehicle(), addWaiting(), boardAnyWaiting(), loadAnyWaiting(), and ~MSTransportableControl().
myWaitingForVehicleNumber
int MSTransportableControl::myWaitingForVehicleNumber protected
The number of transportables waiting for vehicles.
Definition at line 225 of file MSTransportableControl.h.
Referenced by addWaiting(), boardAnyWaiting(), hasNonWaiting(), and loadAnyWaiting().
myWaitingUntil
std::map<SUMOTime, TransportableVector> MSTransportableControl::myWaitingUntil protected
the lists of walking / stopping transportables
Definition at line 210 of file MSTransportableControl.h.
Referenced by checkWaiting(), and setWaitEnd().
The documentation for this class was generated from the following files:
MSTransportableControl.h
MSTransportableControl.cpp