SUMO - Simulation of Urban MObility: GUIEvent_SimulationStep Class Reference
GUIEvent_SimulationStep Class Reference
#include <GUIEvent_SimulationStep.h>
Public Member Functions
GUIEventType getOwnType () const
returns the event type
GUIEvent_SimulationStep ()
constructor
~GUIEvent_SimulationStep ()
destructor
Protected Attributes
GUIEventType myType
the type of the event
Detailed Description
GUIEvent_SimulationStep Throw from GUIRunThread to GUIApplicationWindow and then further to all displays after a step has been performed
Definition at line 43 of file GUIEvent_SimulationStep.h.
Constructor & Destructor Documentation
GUIEvent_SimulationStep()
GUIEvent_SimulationStep::GUIEvent_SimulationStep () inline
constructor
Definition at line 46 of file GUIEvent_SimulationStep.h.
~GUIEvent_SimulationStep()
GUIEvent_SimulationStep::~GUIEvent_SimulationStep () inline
destructor
Definition at line 50 of file GUIEvent_SimulationStep.h.
Member Function Documentation
getOwnType()
GUIEventType GUIEvent::getOwnType () const inline inherited
returns the event type
Definition at line 83 of file GUIEvent.h.
References GUIEvent::myType.
Referenced by GUIApplicationWindow::eventOccured(), GNEApplicationWindow::eventOccured(), GUIApplicationWindow::handleEvent_Message(), and GNEApplicationWindow::handleEvent_Message().
Field Documentation
myType
GUIEventType GUIEvent::myType protected inherited
the type of the event
Definition at line 98 of file GUIEvent.h.
Referenced by GUIEvent::getOwnType(), and GUIEvent_Message::GUIEvent_Message().
The documentation for this class was generated from the following file:
GUIEvent_SimulationStep.h