SUMO - Simulation of Urban MObility: MSVehicle::Influencer Class Reference
MSVehicle::Influencer Class Reference
Changes the wished vehicle speed / lanes.
#include <MSVehicle.h>
Public Member Functions
double changeRequestRemainingSeconds (const SUMOTime currentTime) const
Return the remaining number of seconds of the current laneTimeLine assuming one exists.
bool getEmergencyBrakeRedLight () const
Returns whether red lights shall be a reason to brake.
int getLanechangeMode () const
return the current lane change mode
SUMOTime getLastAccessTimeStep () const
double getLatDist () const
double getOriginalSpeed () const
Returns the originally longitudinal speed to use.
bool getRespectJunctionPriority () const
Returns whether junction priority rules shall be respected.
SUMOAbstractRouter< MSEdge, SUMOVehicle > & getRouterTT () const
int getRoutingMode () const
return the current routing mode
int getSignals () const
int getSpeedMode () const
return the current speed mode
double implicitDeltaPosRemote (const MSVehicle *veh)
return the change in longitudinal position that is implicit in the new remote position
double implicitSpeedRemote (const MSVehicle *veh, double oldSpeed)
return the speed that is implicit in the new remote position
int influenceChangeDecision (const SUMOTime currentTime, const MSEdge &currentEdge, const int currentLaneIndex, int state)
Applies stored LaneChangeMode information and laneTimeLine.
Influencer ()
Constructor.
double influenceSpeed (SUMOTime currentTime, double speed, double vSafe, double vMin, double vMax)
Applies stored velocity information on the speed to use.
bool isRemoteAffected (SUMOTime t) const
bool isRemoteControlled () const
void postProcessRemoteControl (MSVehicle *v)
void resetLatDist ()
void setLaneChangeMode (int value)
Sets lane changing behavior.
void setLaneTimeLine (const std::vector< std::pair< SUMOTime, int > > &laneTimeLine)
Sets a new lane timeline.
void setRemoteControlled (Position xyPos, MSLane *l, double pos, double posLat, double angle, int edgeOffset, const ConstMSEdgeVector &route, SUMOTime t)
void setRoutingMode (int value)
Sets routing behavior.
void setSignals (int signals)
void setSpeedMode (int speedMode)
Sets speed-constraining behaviors.
void setSpeedTimeLine (const std::vector< std::pair< SUMOTime, double > > &speedTimeLine)
Sets a new velocity timeline.
void setSublaneChange (double latDist)
Sets a new sublane-change request.
~Influencer ()
Destructor.
Private Attributes
bool myConsiderMaxAcceleration
Whether the maximum acceleration shall be regarded.
bool myConsiderMaxDeceleration
Whether the maximum deceleration shall be regarded.
bool myConsiderSafeVelocity
Whether the safe velocity shall be regarded.
bool myEmergencyBrakeRedLight
Whether red lights are a reason to brake.
std::vector< std::pair< SUMOTime, int > > myLaneTimeLine
The lane usage time line to apply.
SUMOTime myLastRemoteAccess
double myLatDist
The requested lateral change.
double myOriginalSpeed
The velocity before influence.
double myRemoteAngle
int myRemoteEdgeOffset
MSLane * myRemoteLane
double myRemotePos
double myRemotePosLat
ConstMSEdgeVector myRemoteRoute
Position myRemoteXYPos
bool myRespectJunctionPriority
Whether the junction priority rules are respected.
int myRoutingMode
routing mode (see TraCIConstants.h)
bool mySpeedAdaptationStarted
Whether influencing the speed has already started.
std::vector< std::pair< SUMOTime, double > > mySpeedTimeLine
The velocity time line to apply.
TraciLaneChangePriority myTraciLaneChangePriority
flags for determining the priority of traci lane change requests
int myTraCISignals
Flags for managing conflicts between the laneChangeModel and TraCI laneTimeLine
LaneChangeMode myStrategicLC
lane changing which is necessary to follow the current route
LaneChangeMode myCooperativeLC
lane changing with the intent to help other vehicles
LaneChangeMode mySpeedGainLC
lane changing to travel with higher speed
LaneChangeMode myRightDriveLC
changing to the rightmost lane
LaneChangeMode mySublaneLC
changing to the prefered lateral alignment
Detailed Description
Changes the wished vehicle speed / lanes.
The class is used for passing velocities or velocity profiles obtained via TraCI to the vehicle. The speed adaptation is controlled by the stored speedTimeLine Additionally, the variables myConsiderSafeVelocity, myConsiderMaxAcceleration, and myConsiderMaxDeceleration control whether the safe velocity, the maximum acceleration, and the maximum deceleration have to be regarded.
Furthermore this class is used to affect lane changing decisions according to LaneChangeMode and any given laneTimeLine
Definition at line 1329 of file MSVehicle.h.
Constructor & Destructor Documentation
Influencer()
MSVehicle::Influencer::Influencer ()
Constructor.
Definition at line 242 of file MSVehicle.cpp.
~Influencer()
MSVehicle::Influencer::~Influencer ()
Destructor.
Definition at line 262 of file MSVehicle.cpp.
Member Function Documentation
changeRequestRemainingSeconds()
double MSVehicle::Influencer::changeRequestRemainingSeconds (const SUMOTime currentTime) const
Return the remaining number of seconds of the current laneTimeLine assuming one exists.
Parameters
[in] currentTime The current simulation time
Returns
The remaining seconds to change lanes
Definition at line 430 of file MSVehicle.cpp.
References myLaneTimeLine, and STEPS2TIME.
Referenced by MSLCM_LC2013::_wantsChange(), and MSLCM_SL2015::_wantsChangeSublane().
getEmergencyBrakeRedLight()
bool MSVehicle::Influencer::getEmergencyBrakeRedLight () const inline
Returns whether red lights shall be a reason to brake.
Returns
Whether red lights shall be a reason to brake
Definition at line 1407 of file MSVehicle.h.
Referenced by MSVehicle::ignoreRed(), and MSVehicle::processLaneAdvances().
getLanechangeMode()
int MSVehicle::Influencer::getLanechangeMode () const
return the current lane change mode
Definition at line 293 of file MSVehicle.cpp.
References myCooperativeLC, myRightDriveLC, mySpeedGainLC, myStrategicLC, mySublaneLC, and myTraciLaneChangePriority.
Referenced by libsumo::Vehicle::getLanechangeMode().
getLastAccessTimeStep()
SUMOTime MSVehicle::Influencer::getLastAccessTimeStep () const inline
Definition at line 1435 of file MSVehicle.h.
References MSVehicle::isRemoteControlled().
Referenced by MSVehicle::wasRemoteControlled().
getLatDist()
double MSVehicle::Influencer::getLatDist () const inline
Definition at line 1459 of file MSVehicle.h.
Referenced by MSAbstractLaneChangeModel::checkTraCICommands(), and MSLCM_SL2015::keepLatGap().
getOriginalSpeed()
double MSVehicle::Influencer::getOriginalSpeed () const
Returns the originally longitudinal speed to use.
Returns
The speed given before influence or -1 if no influence is active
Definition at line 337 of file MSVehicle.cpp.
References myOriginalSpeed, and mySpeedTimeLine.
Referenced by MSVehicle::getSpeedWithoutTraciInfluence().
getRespectJunctionPriority()
bool MSVehicle::Influencer::getRespectJunctionPriority () const inline
Returns whether junction priority rules shall be respected.
Returns
Whether junction priority rules be respected
Definition at line 1399 of file MSVehicle.h.
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), and MSVehicle::processLinkAproaches().
getRouterTT()
SUMOAbstractRouter< MSEdge, SUMOVehicle > & MSVehicle::Influencer::getRouterTT () const
Definition at line 549 of file MSVehicle.cpp.
References MSNet::getInstance(), MSDevice_Routing::getRouterTT(), MSNet::getRouterTT(), and myRoutingMode.
getRoutingMode()
int MSVehicle::Influencer::getRoutingMode () const inline
return the current routing mode
Definition at line 1362 of file MSVehicle.h.
References MSVehicle::influenceChangeDecision().
Referenced by libsumo::Vehicle::getRoutingMode().
getSignals()
int MSVehicle::Influencer::getSignals () const inline
Definition at line 1455 of file MSVehicle.h.
Referenced by MSVehicle::setBlinkerInformation().
getSpeedMode()
int MSVehicle::Influencer::getSpeedMode () const
return the current speed mode
Definition at line 283 of file MSVehicle.cpp.
References myConsiderMaxAcceleration, myConsiderMaxDeceleration, myConsiderSafeVelocity, myEmergencyBrakeRedLight, and myRespectJunctionPriority.
Referenced by libsumo::Vehicle::getSpeedMode().
implicitDeltaPosRemote()
double MSVehicle::Influencer::implicitDeltaPosRemote (const MSVehicle * veh)
return the change in longitudinal position that is implicit in the new remote position
Definition at line 533 of file MSVehicle.cpp.
References DIST2SPEED, Position::distanceTo2D(), MSVehicle::getDistanceToPosition(), MSLane::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getPosition(), myRemoteLane, myRemotePos, and myRemoteXYPos.
Referenced by MSVehicle::updateState().
implicitSpeedRemote()
double MSVehicle::Influencer::implicitSpeedRemote (const MSVehicle * veh, double oldSpeed)
return the speed that is implicit in the new remote position
Definition at line 518 of file MSVehicle.cpp.
References DIST2SPEED, Position::distanceTo2D(), MSVehicle::getDistanceToPosition(), MSLane::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getPosition(), myRemoteLane, myRemotePos, and myRemoteXYPos.
Referenced by MSVehicle::processTraCISpeedControl().
influenceChangeDecision()
int MSVehicle::Influencer::influenceChangeDecision (const SUMOTime currentTime, const MSEdge & currentEdge, const int currentLaneIndex, int state)
Applies stored LaneChangeMode information and laneTimeLine.
Parameters
[in] currentTime The current simulation time
[in] currentEdge The current edge the vehicle is on
[in] currentLaneIndex The index of the lane the vehicle is currently on
[in] state The LaneChangeAction flags as computed by the laneChangeModel
Returns
The new LaneChangeAction flags to use
Definition at line 343 of file MSVehicle.cpp.
References MSEdge::getLanes(), MSVehicle::LC_ALWAYS, MSVehicle::LC_NEVER, MSVehicle::LC_NOCONFLICT, LCA_BLOCKED, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_LEFT, LCA_OVERLAPPING, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_SUBLANE, LCA_TRACI, LCA_URGENT, LCA_WANTS_LANECHANGE_OR_STAY, MSVehicle::LCP_ALWAYS, MSVehicle::LCP_NOOVERLAP, MSVehicle::LCP_OPPORTUNISTIC, myCooperativeLC, myLaneTimeLine, myLatDist, myRightDriveLC, mySpeedGainLC, myStrategicLC, mySublaneLC, myTraciLaneChangePriority, MSVehicle::REQUEST_HOLD, MSVehicle::REQUEST_LEFT, MSVehicle::REQUEST_NONE, MSVehicle::REQUEST_RIGHT, time2string(), toString(), and WRITE_WARNING.
Referenced by MSVehicle::influenceChangeDecision().
influenceSpeed()
double MSVehicle::Influencer::influenceSpeed (SUMOTime currentTime, double speed, double vSafe, double vMin, double vMax)
Applies stored velocity information on the speed to use.
The given speed is assumed to be the non-influenced speed from longitudinal control. It is stored for further usage in "myOriginalSpeed".
Parameters
[in] currentTime The current simulation time
[in] speed The undisturbed speed
[in] vSafe The safe velocity
[in] vMin The minimum velocity
[in] vMax The maximum simulation time
Returns
The speed to use
Definition at line 304 of file MSVehicle.cpp.
References DELTA_T, MAX2(), MIN2(), myConsiderMaxAcceleration, myConsiderMaxDeceleration, myConsiderSafeVelocity, myOriginalSpeed, mySpeedAdaptationStarted, mySpeedTimeLine, and STEPS2TIME.
Referenced by MSVehicle::planMoveInternal(), and MSVehicle::processTraCISpeedControl().
isRemoteAffected()
bool MSVehicle::Influencer::isRemoteAffected (SUMOTime t) const
Definition at line 478 of file MSVehicle.cpp.
References myLastRemoteAccess, and TIME2STEPS.
Referenced by MSLane::detectCollisionBetween(), MSVehicle::getPosition(), and MSLane::handleCollisionBetween().
isRemoteControlled()
bool MSVehicle::Influencer::isRemoteControlled () const
Definition at line 472 of file MSVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and myLastRemoteAccess.
Referenced by MSVehicle::isRemoteControlled(), MSVehicle::processTraCISpeedControl(), and MSVehicle::updateState().
postProcessRemoteControl()
void MSVehicle::Influencer::postProcessRemoteControl (MSVehicle * v)
Definition at line 483 of file MSVehicle.cpp.
References MSRoute::begin(), DEG2RAD, MSVehicle::drawOutsideNetwork(), MSLane::forceVehicleInsertion(), MSBaseVehicle::getDeparture(), MSVehicle::getLane(), MSLane::getLength(), MSBaseVehicle::getRoute(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSVehicle::isOnRoad(), M_PI, MSBaseVehicle::myCurrEdge, myRemoteAngle, myRemoteEdgeOffset, myRemoteLane, myRemotePos, myRemotePosLat, myRemoteRoute, myRemoteXYPos, MSBaseVehicle::NOT_YET_DEPARTED, MSMoveReminder::NOTIFICATION_TELEPORT, MSBaseVehicle::onDepart(), MSVehicle::onRemovalFromNet(), MSLane::removeVehicle(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::setAngle(), MSVehicle::setRemoteState(), and MSVehicle::updateBestLanes().
resetLatDist()
void MSVehicle::Influencer::resetLatDist () inline
Definition at line 1463 of file MSVehicle.h.
Referenced by MSAbstractLaneChangeModel::checkTraCICommands().
setLaneChangeMode()
void MSVehicle::Influencer::setLaneChangeMode (int value)
Sets lane changing behavior.
Parameters
[in] value a bitset controlling the different modes
Definition at line 448 of file MSVehicle.cpp.
References myCooperativeLC, myRightDriveLC, mySpeedGainLC, myStrategicLC, mySublaneLC, and myTraciLaneChangePriority.
Referenced by TraCIServerAPI_Vehicle::processSet().
setLaneTimeLine()
void MSVehicle::Influencer::setLaneTimeLine (const std::vector< std::pair< SUMOTime, int > > & laneTimeLine)
Sets a new lane timeline.
Parameters
[in] laneTimeLine The time line of lanes to use
Definition at line 273 of file MSVehicle.cpp.
References myLaneTimeLine.
Referenced by libsumo::Vehicle::changeLane().
setRemoteControlled()
void MSVehicle::Influencer::setRemoteControlled (Position xyPos, MSLane * l, double pos, double posLat, double angle, int edgeOffset, const ConstMSEdgeVector & route, SUMOTime t)
Definition at line 459 of file MSVehicle.cpp.
References myLastRemoteAccess, myRemoteAngle, myRemoteEdgeOffset, myRemoteLane, myRemotePos, myRemotePosLat, myRemoteRoute, and myRemoteXYPos.
Referenced by libsumo::Helper::setRemoteControlled().
setRoutingMode()
void MSVehicle::Influencer::setRoutingMode (int value) inline
Sets routing behavior.
Parameters
[in] value an enum value controlling the different modes
Definition at line 1424 of file MSVehicle.h.
Referenced by TraCIServerAPI_Vehicle::processSet().
setSignals()
void MSVehicle::Influencer::setSignals (int signals) inline
Definition at line 1451 of file MSVehicle.h.
Referenced by MSVehicle::setBlinkerInformation(), and libsumo::Vehicle::setSignals().
setSpeedMode()
void MSVehicle::Influencer::setSpeedMode (int speedMode)
Sets speed-constraining behaviors.
Parameters
[in] value a bitset controlling the different modes
Definition at line 438 of file MSVehicle.cpp.
References myConsiderMaxAcceleration, myConsiderMaxDeceleration, myConsiderSafeVelocity, myEmergencyBrakeRedLight, and myRespectJunctionPriority.
Referenced by TraCIServerAPI_Vehicle::processSet().
setSpeedTimeLine()
void MSVehicle::Influencer::setSpeedTimeLine (const std::vector< std::pair< SUMOTime, double > > & speedTimeLine)
Sets a new velocity timeline.
Parameters
[in] speedTimeLine The time line of speeds to use
Definition at line 266 of file MSVehicle.cpp.
References mySpeedAdaptationStarted, and mySpeedTimeLine.
Referenced by TraCIServerAPI_Vehicle::processSet(), and libsumo::Vehicle::slowDown().
setSublaneChange()
void MSVehicle::Influencer::setSublaneChange (double latDist)
Sets a new sublane-change request.
Parameters
[in] latDist The lateral distance for changing
Definition at line 278 of file MSVehicle.cpp.
References myLatDist.
Referenced by libsumo::Vehicle::changeSublane(), and MSLaneChangerSublane::startChangeSublane().
Field Documentation
myConsiderMaxAcceleration
bool MSVehicle::Influencer::myConsiderMaxAcceleration private
Whether the maximum acceleration shall be regarded.
Definition at line 1489 of file MSVehicle.h.
Referenced by getSpeedMode(), influenceSpeed(), and setSpeedMode().
myConsiderMaxDeceleration
bool MSVehicle::Influencer::myConsiderMaxDeceleration private
Whether the maximum deceleration shall be regarded.
Definition at line 1492 of file MSVehicle.h.
Referenced by getSpeedMode(), influenceSpeed(), and setSpeedMode().
myConsiderSafeVelocity
bool MSVehicle::Influencer::myConsiderSafeVelocity private
Whether the safe velocity shall be regarded.
Definition at line 1486 of file MSVehicle.h.
Referenced by getSpeedMode(), influenceSpeed(), and setSpeedMode().
myCooperativeLC
LaneChangeMode MSVehicle::Influencer::myCooperativeLC private
lane changing with the intent to help other vehicles
Definition at line 1514 of file MSVehicle.h.
Referenced by getLanechangeMode(), influenceChangeDecision(), and setLaneChangeMode().
myEmergencyBrakeRedLight
bool MSVehicle::Influencer::myEmergencyBrakeRedLight private
Whether red lights are a reason to brake.
Definition at line 1498 of file MSVehicle.h.
Referenced by getSpeedMode(), and setSpeedMode().
myLaneTimeLine
std::vector<std::pair<SUMOTime, int> > MSVehicle::Influencer::myLaneTimeLine private
The lane usage time line to apply.
Definition at line 1474 of file MSVehicle.h.
Referenced by changeRequestRemainingSeconds(), influenceChangeDecision(), and setLaneTimeLine().
myLastRemoteAccess
SUMOTime MSVehicle::Influencer::myLastRemoteAccess private
Definition at line 1507 of file MSVehicle.h.
Referenced by isRemoteAffected(), isRemoteControlled(), and setRemoteControlled().
myLatDist
double MSVehicle::Influencer::myLatDist private
The requested lateral change.
Definition at line 1480 of file MSVehicle.h.
Referenced by influenceChangeDecision(), and setSublaneChange().
myOriginalSpeed
double MSVehicle::Influencer::myOriginalSpeed private
The velocity before influence.
Definition at line 1477 of file MSVehicle.h.
Referenced by getOriginalSpeed(), and influenceSpeed().
myRemoteAngle
double MSVehicle::Influencer::myRemoteAngle private
Definition at line 1504 of file MSVehicle.h.
Referenced by postProcessRemoteControl(), and setRemoteControlled().
myRemoteEdgeOffset
int MSVehicle::Influencer::myRemoteEdgeOffset private
Definition at line 1505 of file MSVehicle.h.
Referenced by postProcessRemoteControl(), and setRemoteControlled().
myRemoteLane
MSLane* MSVehicle::Influencer::myRemoteLane private
Definition at line 1501 of file MSVehicle.h.
Referenced by implicitDeltaPosRemote(), implicitSpeedRemote(), postProcessRemoteControl(), and setRemoteControlled().
myRemotePos
double MSVehicle::Influencer::myRemotePos private
Definition at line 1502 of file MSVehicle.h.
Referenced by implicitDeltaPosRemote(), implicitSpeedRemote(), postProcessRemoteControl(), and setRemoteControlled().
myRemotePosLat
double MSVehicle::Influencer::myRemotePosLat private
Definition at line 1503 of file MSVehicle.h.
Referenced by postProcessRemoteControl(), and setRemoteControlled().
myRemoteRoute
ConstMSEdgeVector MSVehicle::Influencer::myRemoteRoute private
Definition at line 1506 of file MSVehicle.h.
Referenced by postProcessRemoteControl(), and setRemoteControlled().
myRemoteXYPos
Position MSVehicle::Influencer::myRemoteXYPos private
Definition at line 1500 of file MSVehicle.h.
Referenced by implicitDeltaPosRemote(), implicitSpeedRemote(), postProcessRemoteControl(), and setRemoteControlled().
myRespectJunctionPriority
bool MSVehicle::Influencer::myRespectJunctionPriority private
Whether the junction priority rules are respected.
Definition at line 1495 of file MSVehicle.h.
Referenced by getSpeedMode(), and setSpeedMode().
myRightDriveLC
LaneChangeMode MSVehicle::Influencer::myRightDriveLC private
changing to the rightmost lane
Definition at line 1518 of file MSVehicle.h.
Referenced by getLanechangeMode(), influenceChangeDecision(), and setLaneChangeMode().
myRoutingMode
int MSVehicle::Influencer::myRoutingMode private
routing mode (see TraCIConstants.h)
Definition at line 1529 of file MSVehicle.h.
Referenced by getRouterTT().
mySpeedAdaptationStarted
bool MSVehicle::Influencer::mySpeedAdaptationStarted private
Whether influencing the speed has already started.
Definition at line 1483 of file MSVehicle.h.
Referenced by influenceSpeed(), and setSpeedTimeLine().
mySpeedGainLC
LaneChangeMode MSVehicle::Influencer::mySpeedGainLC private
lane changing to travel with higher speed
Definition at line 1516 of file MSVehicle.h.
Referenced by getLanechangeMode(), influenceChangeDecision(), and setLaneChangeMode().
mySpeedTimeLine
std::vector<std::pair<SUMOTime, double> > MSVehicle::Influencer::mySpeedTimeLine private
The velocity time line to apply.
Definition at line 1471 of file MSVehicle.h.
Referenced by getOriginalSpeed(), influenceSpeed(), and setSpeedTimeLine().
myStrategicLC
LaneChangeMode MSVehicle::Influencer::myStrategicLC private
lane changing which is necessary to follow the current route
Definition at line 1512 of file MSVehicle.h.
Referenced by getLanechangeMode(), influenceChangeDecision(), and setLaneChangeMode().
mySublaneLC
LaneChangeMode MSVehicle::Influencer::mySublaneLC private
changing to the prefered lateral alignment
Definition at line 1520 of file MSVehicle.h.
Referenced by getLanechangeMode(), influenceChangeDecision(), and setLaneChangeMode().
myTraciLaneChangePriority
TraciLaneChangePriority MSVehicle::Influencer::myTraciLaneChangePriority private
flags for determining the priority of traci lane change requests
Definition at line 1523 of file MSVehicle.h.
Referenced by getLanechangeMode(), influenceChangeDecision(), and setLaneChangeMode().
myTraCISignals
int MSVehicle::Influencer::myTraCISignals private
Definition at line 1526 of file MSVehicle.h.
The documentation for this class was generated from the following files:
MSVehicle.h
MSVehicle.cpp