SUMO - Simulation of Urban MObility: NBContHelper::relative_incoming_edge_sorter Class Reference
NBContHelper::relative_incoming_edge_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
relative_incoming_edge_sorter (NBEdge *e)
constructor
Private Attributes
NBEdge * myEdge
the edge to compute the relative angle of
Detailed Description
relative_incoming_edge_sorter Class to sort edges by their angle in relation to an outgoing edge. This is normally done to sort edges incoming at the starting node of this edge by their angle in relation to the using edge's angle (this angle is the reference angle).
Definition at line 135 of file NBContHelper.h.
Constructor & Destructor Documentation
relative_incoming_edge_sorter()
NBContHelper::relative_incoming_edge_sorter::relative_incoming_edge_sorter (NBEdge * e) inline explicit
constructor
Definition at line 138 of file NBContHelper.h.
References NBContHelper::relative_outgoing_edge_sorter::operator()().
Member Function Documentation
operator()()
int NBContHelper::relative_incoming_edge_sorter::operator() (NBEdge * e1, NBEdge * e2) const
comparing operation
Definition at line 228 of file NBContHelper.cpp.
References NBEdge::ANGLE_LOOKAHEAD, Position::angleTo2D(), NBEdge::getEndAngle(), NBEdge::getGeometry(), NBEdge::getLength(), NBNode::getPosition(), NBEdge::getToNode(), GeomHelper::legacyDegree(), PositionVector::length(), MAX2(), NBHelpers::normRelAngle(), and PositionVector::positionAtOffset2D().
Field Documentation
myEdge
NBEdge* NBContHelper::relative_incoming_edge_sorter::myEdge private
the edge to compute the relative angle of
Definition at line 146 of file NBContHelper.h.
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp