SUMO - Simulation of Urban MObility: NIVissimDistrictConnection Class Reference
NIVissimDistrictConnection Class Reference
#include <NIVissimDistrictConnection.h>
Public Member Functions
Position geomPosition () const
Returns the position The position yields from the edge geometry and the place the connection is plaed at.
int getID () const
Returns the id of the connection.
double getMeanSpeed () const
double getPosition () const
Returns the position of the connection at the edge.
NIVissimDistrictConnection (int id, const std::string &name, const std::vector< int > &districts, const std::vector< double > &percentages, int edgeid, double position, const std::vector< std::pair< int, int > > &assignedVehicles)
Contructor.
~NIVissimDistrictConnection ()
Static Public Member Functions
static void clearDict ()
Clears the dictionary.
static void dict_BuildDistrictConnections ()
static void dict_BuildDistrictNodes (NBDistrictCont &dc, NBNodeCont &nc)
Builds the nodes that belong to a district.
static void dict_BuildDistricts (NBDistrictCont &dc, NBEdgeCont &ec, NBNodeCont &nc)
Builds the districts.
static void dict_CheckEdgeEnds ()
static NIVissimDistrictConnection * dict_findForEdge (int edgeid)
Returns the connection to a district placed at the given node Yep, there onyl should be one, there is no need to build a single edge as connection between two parking places.
static bool dictionary (int id, const std::string &name, const std::vector< int > &districts, const std::vector< double > &percentages, int edgeid, double position, const std::vector< std::pair< int, int > > &assignedVehicles)
Inserts the connection into the dictionary after building it.
static bool dictionary (int id, NIVissimDistrictConnection *o)
Inserts the build connection to the dictionary.
static NIVissimDistrictConnection * dictionary (int id)
Returns the named dictionary.
Private Types
typedef std::map< int, NIVissimDistrictConnection * > DictType
Definition of a dictionary of district connections.
typedef std::map< int, double > DistrictPercentages
Definition of a map of how many vehicles should leave to a certain district.
Private Member Functions
void checkEdgeEnd ()
double getRealSpeed (int distNo) const
Private Attributes
std::vector< std::pair< int, int > > myAssignedVehicles
The vehicles using this connection.
std::vector< int > myDistricts
The connected districts.
int myEdgeID
The id of the connected edge.
int myID
The id of the connections.
std::string myName
The name of the connections.
DistrictPercentages myPercentages
A map how many vehicles (key, amount) should leave to a district (key)
double myPosition
The position on the edge.
Static Private Attributes
static DictType myDict
District connection dictionary.
static std::map< int, std::vector< int > > myDistrictsConnections
Map from ditricts to connections.
Detailed Description
Definition at line 45 of file NIVissimDistrictConnection.h.
Member Typedef Documentation
DictType
typedef std::map<int, NIVissimDistrictConnection*> NIVissimDistrictConnection::DictType private
Definition of a dictionary of district connections.
Definition at line 136 of file NIVissimDistrictConnection.h.
DistrictPercentages
typedef std::map<int, double> NIVissimDistrictConnection::DistrictPercentages private
Definition of a map of how many vehicles should leave to a certain district.
Definition at line 120 of file NIVissimDistrictConnection.h.
Constructor & Destructor Documentation
NIVissimDistrictConnection()
NIVissimDistrictConnection::NIVissimDistrictConnection (int id, const std::string & name, const std::vector< int > & districts, const std::vector< double > & percentages, int edgeid, double position, const std::vector< std::pair< int, int > > & assignedVehicles)
Contructor.
Definition at line 65 of file NIVissimDistrictConnection.cpp.
References myDistricts, and myPercentages.
Referenced by dictionary().
~NIVissimDistrictConnection()
NIVissimDistrictConnection::~NIVissimDistrictConnection ()
Definition at line 83 of file NIVissimDistrictConnection.cpp.
Member Function Documentation
checkEdgeEnd()
void NIVissimDistrictConnection::checkEdgeEnd () private
Definition at line 150 of file NIVissimDistrictConnection.cpp.
References NIVissimEdge::checkDistrictConnectionExistanceAt(), NIVissimEdge::dictionary(), myEdgeID, and myPosition.
Referenced by dict_CheckEdgeEnds(), and getPosition().
clearDict()
void NIVissimDistrictConnection::clearDict () static
Clears the dictionary.
Definition at line 356 of file NIVissimDistrictConnection.cpp.
References myDict.
Referenced by getPosition(), and NIImporter_Vissim::~NIImporter_Vissim().
dict_BuildDistrictConnections()
void NIVissimDistrictConnection::dict_BuildDistrictConnections () static
Definition at line 124 of file NIVissimDistrictConnection.cpp.
References myDict, myDistricts, and myDistrictsConnections.
Referenced by getPosition(), and NIImporter_Vissim::postLoadBuild().
dict_BuildDistrictNodes()
void NIVissimDistrictConnection::dict_BuildDistrictNodes (NBDistrictCont & dc, NBNodeCont & nc) static
Builds the nodes that belong to a district.
Definition at line 158 of file NIVissimDistrictConnection.cpp.
References Position::add(), dictionary(), geomPosition(), PositionVector::getPolygonCenter(), NBDistrictCont::insert(), NBNodeCont::insert(), and myDistrictsConnections.
Referenced by getPosition(), and NIImporter_Vissim::postLoadBuild().
dict_BuildDistricts()
void NIVissimDistrictConnection::dict_BuildDistricts (NBDistrictCont & dc, NBEdgeCont & ec, NBNodeCont & nc) static
Builds the districts.
Definition at line 189 of file NIVissimDistrictConnection.cpp.
References NBDistrict::addSink(), NBDistrict::addSource(), dictionary(), NBEdge::getFromNode(), Named::getID(), getMeanSpeed(), getPosition(), NBEdge::getToNode(), NBEdgeCont::insert(), NBNode::invalidateIncomingConnections(), NBNode::invalidateOutgoingConnections(), myDistrictsConnections, myEdgeID, myID, myPercentages, myPosition, NBDistrictCont::retrieve(), NBNodeCont::retrieve(), NBEdgeCont::retrieve(), NBEdgeCont::retrievePossiblySplit(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, and WRITE_WARNING.
Referenced by getPosition(), and NIImporter_Vissim::postLoadBuild().
dict_CheckEdgeEnds()
void NIVissimDistrictConnection::dict_CheckEdgeEnds () static
Definition at line 138 of file NIVissimDistrictConnection.cpp.
References checkEdgeEnd(), dictionary(), and myDistrictsConnections.
Referenced by getPosition(), and NIImporter_Vissim::postLoadBuild().
dict_findForEdge()
NIVissimDistrictConnection * NIVissimDistrictConnection::dict_findForEdge (int edgeid) static
Returns the connection to a district placed at the given node Yep, there onyl should be one, there is no need to build a single edge as connection between two parking places.
Definition at line 345 of file NIVissimDistrictConnection.cpp.
References myDict.
Referenced by getPosition(), NIVissimEdge::resolveSameNode(), and NIVissimEdge::setDistrictSpeed().
dictionary() [1/3]
bool NIVissimDistrictConnection::dictionary (int id, const std::string & name, const std::vector< int > & districts, const std::vector< double > & percentages, int edgeid, double position, const std::vector< std::pair< int, int > > & assignedVehicles) static
Inserts the connection into the dictionary after building it.
Definition at line 88 of file NIVissimDistrictConnection.cpp.
References NIVissimDistrictConnection().
Referenced by dict_BuildDistrictNodes(), dict_BuildDistricts(), dict_CheckEdgeEnds(), getPosition(), NIImporter_Vissim::NIVissimXMLHandler_Parkplatzdefinition::myStartElement(), and NIVissimSingleTypeParser_Parkplatzdefinition::parse().
dictionary() [2/3]
bool NIVissimDistrictConnection::dictionary (int id, NIVissimDistrictConnection * o) static
Inserts the build connection to the dictionary.
Definition at line 104 of file NIVissimDistrictConnection.cpp.
References myDict.
dictionary() [3/3]
NIVissimDistrictConnection * NIVissimDistrictConnection::dictionary (int id) static
Returns the named dictionary.
Definition at line 115 of file NIVissimDistrictConnection.cpp.
References myDict.
geomPosition()
Position NIVissimDistrictConnection::geomPosition () const
Returns the position The position yields from the edge geometry and the place the connection is plaed at.
Definition at line 338 of file NIVissimDistrictConnection.cpp.
References NIVissimEdge::dictionary(), NIVissimAbstractEdge::getGeomPosition(), myEdgeID, and myPosition.
Referenced by dict_BuildDistrictNodes(), NIVissimEdge::remapOneOfNodes(), and NIVissimEdge::resolveSameNode().
getID()
int NIVissimDistrictConnection::getID () const inline
Returns the id of the connection.
Definition at line 61 of file NIVissimDistrictConnection.h.
References myID.
Referenced by NIVissimEdge::remapOneOfNodes(), and NIVissimEdge::resolveSameNode().
getMeanSpeed()
double NIVissimDistrictConnection::getMeanSpeed () const
Definition at line 365 of file NIVissimDistrictConnection.cpp.
References getRealSpeed(), myAssignedVehicles, myID, toString(), and WRITE_WARNING.
Referenced by dict_BuildDistricts(), getPosition(), and NIVissimEdge::setDistrictSpeed().
getPosition()
double NIVissimDistrictConnection::getPosition () const inline
Returns the position of the connection at the edge.
Definition at line 66 of file NIVissimDistrictConnection.h.
References checkEdgeEnd(), clearDict(), dict_BuildDistrictConnections(), dict_BuildDistrictNodes(), dict_BuildDistricts(), dict_CheckEdgeEnds(), dict_findForEdge(), dictionary(), getMeanSpeed(), getRealSpeed(), and myPosition.
Referenced by dict_BuildDistricts(), and NIVissimEdge::resolveSameNode().
getRealSpeed()
double NIVissimDistrictConnection::getRealSpeed (int distNo) const private
Definition at line 381 of file NIVissimDistrictConnection.cpp.
References DistributionCont::dictionary(), OptionsCont::getFloat(), OptionsCont::getOptions(), and WRITE_WARNING.
Referenced by getMeanSpeed(), and getPosition().
Field Documentation
myAssignedVehicles
std::vector<std::pair<int, int> > NIVissimDistrictConnection::myAssignedVehicles private
The vehicles using this connection.
Definition at line 132 of file NIVissimDistrictConnection.h.
Referenced by getMeanSpeed().
myDict
NIVissimDistrictConnection::DictType NIVissimDistrictConnection::myDict static private
District connection dictionary.
Definition at line 139 of file NIVissimDistrictConnection.h.
Referenced by clearDict(), dict_BuildDistrictConnections(), dict_findForEdge(), and dictionary().
myDistricts
std::vector<int> NIVissimDistrictConnection::myDistricts private
The connected districts.
Definition at line 117 of file NIVissimDistrictConnection.h.
Referenced by dict_BuildDistrictConnections(), and NIVissimDistrictConnection().
myDistrictsConnections
std::map< int, std::vector< int > > NIVissimDistrictConnection::myDistrictsConnections static private
Map from ditricts to connections.
Definition at line 142 of file NIVissimDistrictConnection.h.
Referenced by dict_BuildDistrictConnections(), dict_BuildDistrictNodes(), dict_BuildDistricts(), and dict_CheckEdgeEnds().
myEdgeID
int NIVissimDistrictConnection::myEdgeID private
The id of the connected edge.
Definition at line 126 of file NIVissimDistrictConnection.h.
Referenced by checkEdgeEnd(), dict_BuildDistricts(), and geomPosition().
myID
int NIVissimDistrictConnection::myID private
The id of the connections.
Definition at line 111 of file NIVissimDistrictConnection.h.
Referenced by dict_BuildDistricts(), getID(), and getMeanSpeed().
myName
std::string NIVissimDistrictConnection::myName private
The name of the connections.
Definition at line 114 of file NIVissimDistrictConnection.h.
myPercentages
DistrictPercentages NIVissimDistrictConnection::myPercentages private
A map how many vehicles (key, amount) should leave to a district (key)
Definition at line 123 of file NIVissimDistrictConnection.h.
Referenced by dict_BuildDistricts(), and NIVissimDistrictConnection().
myPosition
double NIVissimDistrictConnection::myPosition private
The position on the edge.
Definition at line 129 of file NIVissimDistrictConnection.h.
Referenced by checkEdgeEnd(), dict_BuildDistricts(), geomPosition(), and getPosition().
The documentation for this class was generated from the following files:
NIVissimDistrictConnection.h
NIVissimDistrictConnection.cpp