SUMO - Simulation of Urban MObility: FX::FXRealSpinDial Class Reference
FX::FXRealSpinDial Class Reference
Spinner control.
#include <FXRealSpinDial.h>
Public Types
enum {
ID_DIAL = FXPacker::ID_LAST, ID_INCREMENT, ID_DECREMENT, ID_ENTRY,
ID_LAST
}
Public Member Functions
virtual void create ()
Create server-side resources.
void decrement (FXint incMode=SPINDIAL_INC_NORMAL)
Decrement spinner.
virtual void disable ()
Disable spinner.
virtual void enable ()
Enable spinner.
FXRealSpinDial (FXComposite *p, FXint cols, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=SPINDIAL_NORMAL, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
Construct a spinner.
FXdouble getCoarseIncrement () const
Return spinner increment.
FXColor getCursorColor () const
Return the cursor color.
virtual FXint getDefaultHeight ()
Return default height.
virtual FXint getDefaultWidth ()
Return default width.
const FXDial & getDial () const
FXColor getDialColor () const
Return color of the dial.
FXColor getDownArrowColor () const
Return color of the the down arrow.
FXdouble getFineIncrement () const
Return spinner increment.
FXFont * getFont () const
Get the text font.
FXString getHelpText () const
Get the status line help text for this spinner.
FXdouble getIncrement () const
Return spinner increment.
FXbool getNumberFormatExponent () const
Return whether the exponent is used in number display.
FXint getNumberFormatPrecision () const
Return the digits of precision used to display numbers.
FXString getNumberFormatString () const
Return the format string for number display.
void getRange (FXdouble &lo, FXdouble &hi) const
Get the spinner's current range.
FXColor getSelBackColor () const
Return selected background color.
FXColor getSelTextColor () const
Return selected text color.
FXuint getSpinnerStyle () const
Return current spinner style.
FXColor getTextColor () const
Return text color.
FXString getTipText () const
Get the tool tip message for this spinner.
FXColor getUpArrowColor () const
Return color of the up arrow.
FXdouble getValue () const
Return current value.
void increment (FXint incMode=SPINDIAL_INC_NORMAL)
Increment spinner.
FXbool isCyclic () const
Return TRUE if in cyclic mode.
FXbool isDialVisible () const
Return TRUE if dial is visible.
FXbool isEditable () const
Return TRUE if text field is editable.
FXbool isTextVisible () const
Return TRUE if text is visible.
virtual void layout ()
Perform layout.
virtual void load (FXStream &store)
Load spinner from a stream.
long onChgDial (FXObject *, FXSelector, void *)
long onChgEntry (FXObject *, FXSelector, void *)
long onCmdDecrement (FXObject *, FXSelector, void *)
long onCmdDial (FXObject *, FXSelector, void *)
long onCmdEntry (FXObject *, FXSelector, void *)
long onCmdGetIntRange (FXObject *, FXSelector, void *)
long onCmdGetIntValue (FXObject *, FXSelector, void *)
long onCmdGetRealRange (FXObject *, FXSelector, void *)
long onCmdGetRealValue (FXObject *, FXSelector, void *)
long onCmdIncrement (FXObject *, FXSelector, void *)
long onCmdSetIntRange (FXObject *, FXSelector, void *)
long onCmdSetIntValue (FXObject *, FXSelector, void *)
long onCmdSetRealRange (FXObject *, FXSelector, void *)
long onCmdSetRealValue (FXObject *, FXSelector, void *)
long onCmdSetValue (FXObject *, FXSelector, void *)
long onKeyPress (FXObject *, FXSelector, void *)
long onKeyRelease (FXObject *, FXSelector, void *)
long onMotion (FXObject *, FXSelector, void *)
long onMouseWheel (FXObject *, FXSelector, void *)
long onUpdDecrement (FXObject *, FXSelector, void *)
long onUpdDial (FXObject *, FXSelector, void *)
long onUpdEntry (FXObject *, FXSelector, void *)
long onUpdIncrement (FXObject *, FXSelector, void *)
virtual void save (FXStream &store) const
Save spinner to a stream.
void selectAll ()
Mark the text entry as selected.
void setCoarseIncrement (FXdouble increment)
Change spinner coarse adjustment increment (when SHIFT key held down)
void setCursorColor (FXColor clr)
Changes the cursor color.
void setCyclic (FXbool cyclic)
Set to cyclic mode, i.e. wrap around at maximum/minimum.
void setDialColor (FXColor clr)
Change color of the dial.
void setDialVisible (FXbool shown)
Set dial visible flag.
void setDownArrowColor (FXColor clr)
Change color of the down arrow.
void setEditable (FXbool edit=TRUE)
Allow editing of the text field.
void setFineIncrement (FXdouble increment)
Change spinner fine adjustment increment (when CTRL key held down)
void setFont (FXFont *fnt)
Set the text font.
void setFormatString (const FXchar *fmt)
void setHelpText (const FXString &text)
Set the status line help text for this spinner.
void setIncrement (FXdouble increment)
Change spinner increment.
void setIncrements (FXdouble fine, FXdouble norm, FXdouble coarse)
Change all spinner increment.
void setNumberFormat (FXint prec, FXbool bExp=FALSE)
void setRange (FXdouble lo, FXdouble hi)
Change the spinner's range.
void setSelBackColor (FXColor clr)
Change selected background color.
void setSelTextColor (FXColor clr)
Change selected text color.
void setSpinnerStyle (FXuint style)
Change spinner style.
void setTextColor (FXColor clr)
Change text color.
void setTextVisible (FXbool shown)
Set text visible flag.
void setTipText (const FXString &text)
Set the tool tip message for this spinner.
void setUpArrowColor (FXColor clr)
Change color of the up arrow.
virtual void setValue (FXdouble value)
Change current value.
virtual ~FXRealSpinDial ()
Destructor.
Protected Member Functions
FXRealSpinDial ()
Protected Attributes
FXDial * dial
FXint dialpos
FXArrowButton * downButton
FXdouble incr [3]
FXint keystate
FXdouble pos
FXdouble range [2]
FXRealSpinDialText * textField
FXArrowButton * upButton
Private Member Functions
FXRealSpinDial (const FXRealSpinDial &)
FXRealSpinDial & operator= (const FXRealSpinDial &)
Detailed Description
Spinner control.
Definition at line 67 of file FXRealSpinDial.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_DIAL
ID_INCREMENT
ID_DECREMENT
ID_ENTRY
ID_LAST
Definition at line 110 of file FXRealSpinDial.h.
Constructor & Destructor Documentation
FXRealSpinDial() [1/3]
FX::FXRealSpinDial::FXRealSpinDial () protected
Definition at line 458 of file FXRealSpinDial.cpp.
FXRealSpinDial() [2/3]
FX::FXRealSpinDial::FXRealSpinDial (const FXRealSpinDial &) private
FXRealSpinDial() [3/3]
FX::FXRealSpinDial::FXRealSpinDial (FXComposite * p, FXint cols, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = SPINDIAL_NORMAL, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD)
Construct a spinner.
Definition at line 475 of file FXRealSpinDial.cpp.
References dial, DIALINCR, dialpos, downButton, ID_DECREMENT, ID_DIAL, ID_ENTRY, ID_INCREMENT, incr, INTMAX, INTMIN, keystate, pos, range, FX::SPINDIAL_NOMAX, FX::SPINDIAL_NOMIN, textField, and upButton.
~FXRealSpinDial()
FX::FXRealSpinDial::~FXRealSpinDial () virtual
Destructor.
Definition at line 1255 of file FXRealSpinDial.cpp.
References dial, downButton, textField, and upButton.
Referenced by getCoarseIncrement().
Member Function Documentation
create()
void FX::FXRealSpinDial::create () virtual
Create server-side resources.
Definition at line 518 of file FXRealSpinDial.cpp.
decrement()
void FX::FXRealSpinDial::decrement (FXint incMode = SPINDIAL_INC_NORMAL)
Decrement spinner.
Definition at line 950 of file FXRealSpinDial.cpp.
References incr, pos, range, setValue(), FX::SPINDIAL_CYCLIC, and FX::SPINDIAL_LOG.
Referenced by onCmdDecrement(), onKeyPress(), and onMouseWheel().
disable()
void FX::FXRealSpinDial::disable () virtual
Disable spinner.
Definition at line 534 of file FXRealSpinDial.cpp.
References dial, and textField.
enable()
void FX::FXRealSpinDial::enable () virtual
Enable spinner.
Definition at line 524 of file FXRealSpinDial.cpp.
References dial, and textField.
getCoarseIncrement()
FXdouble FX::FXRealSpinDial::getCoarseIncrement () const inline
Return spinner increment.
Definition at line 203 of file FXRealSpinDial.h.
References getCursorColor(), getDial(), getDialColor(), getDownArrowColor(), getFont(), getHelpText(), getNumberFormatExponent(), getNumberFormatPrecision(), getNumberFormatString(), getSelBackColor(), getSelTextColor(), getSpinnerStyle(), getTextColor(), getTipText(), getUpArrowColor(), isEditable(), load(), save(), selectAll(), setCursorColor(), setDialColor(), setDownArrowColor(), setEditable(), setFont(), setFormatString(), setHelpText(), setNumberFormat(), setSelBackColor(), setSelTextColor(), setSpinnerStyle(), setTextColor(), setTipText(), setUpArrowColor(), and ~FXRealSpinDial().
getCursorColor()
FXColor FX::FXRealSpinDial::getCursorColor () const
Return the cursor color.
Definition at line 1204 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getDefaultHeight()
FXint FX::FXRealSpinDial::getDefaultHeight () virtual
Return default height.
Definition at line 512 of file FXRealSpinDial.cpp.
References textField.
getDefaultWidth()
FXint FX::FXRealSpinDial::getDefaultWidth () virtual
Return default width.
Definition at line 502 of file FXRealSpinDial.cpp.
References DIALWIDTH, GAPWIDTH, FX::SPINDIAL_NOTEXT, and textField.
getDial()
const FXDial & FXRealSpinDial::getDial () const
Definition at line 1273 of file FXRealSpinDial.cpp.
References dial.
Referenced by getCoarseIncrement().
getDialColor()
FXColor FX::FXRealSpinDial::getDialColor () const
Return color of the dial.
Definition at line 1143 of file FXRealSpinDial.cpp.
References dial.
Referenced by getCoarseIncrement().
getDownArrowColor()
FXColor FX::FXRealSpinDial::getDownArrowColor () const
Return color of the the down arrow.
Definition at line 1163 of file FXRealSpinDial.cpp.
References downButton.
Referenced by getCoarseIncrement().
getFineIncrement()
FXdouble FX::FXRealSpinDial::getFineIncrement () const inline
Return spinner increment.
Definition at line 199 of file FXRealSpinDial.h.
getFont()
FXFont * FX::FXRealSpinDial::getFont () const
Get the text font.
Definition at line 1068 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getHelpText()
FXString FX::FXRealSpinDial::getHelpText () const
Get the status line help text for this spinner.
Definition at line 1083 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getIncrement()
FXdouble FX::FXRealSpinDial::getIncrement () const inline
Return spinner increment.
Definition at line 195 of file FXRealSpinDial.h.
getNumberFormatExponent()
FXbool FX::FXRealSpinDial::getNumberFormatExponent () const
Return whether the exponent is used in number display.
Definition at line 1216 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialText::getNumberFormatExponent(), and textField.
Referenced by getCoarseIncrement().
getNumberFormatPrecision()
FXint FX::FXRealSpinDial::getNumberFormatPrecision () const
Return the digits of precision used to display numbers.
Definition at line 1212 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialText::getNumberFormatPrecision(), and textField.
Referenced by getCoarseIncrement().
getNumberFormatString()
FXString FX::FXRealSpinDial::getNumberFormatString () const
Return the format string for number display.
Definition at line 1224 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialText::getNumberFormatString(), and textField.
Referenced by getCoarseIncrement().
getRange()
void FX::FXRealSpinDial::getRange (FXdouble & lo, FXdouble & hi) const inline
Get the spinner's current range.
Definition at line 180 of file FXRealSpinDial.h.
References increment(), setCoarseIncrement(), setFineIncrement(), setIncrement(), and setIncrements().
Referenced by onCmdGetRealRange().
getSelBackColor()
FXColor FX::FXRealSpinDial::getSelBackColor () const
Return selected background color.
Definition at line 1184 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getSelTextColor()
FXColor FX::FXRealSpinDial::getSelTextColor () const
Return selected text color.
Definition at line 1194 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getSpinnerStyle()
FXuint FX::FXRealSpinDial::getSpinnerStyle () const
Return current spinner style.
Definition at line 1121 of file FXRealSpinDial.cpp.
References SPINDIAL_MASK.
Referenced by getCoarseIncrement().
getTextColor()
FXColor FX::FXRealSpinDial::getTextColor () const
Return text color.
Definition at line 1174 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getTipText()
FXString FX::FXRealSpinDial::getTipText () const
Get the tool tip message for this spinner.
Definition at line 1099 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
getUpArrowColor()
FXColor FX::FXRealSpinDial::getUpArrowColor () const
Return color of the up arrow.
Definition at line 1153 of file FXRealSpinDial.cpp.
References upButton.
Referenced by getCoarseIncrement().
getValue()
FXdouble FX::FXRealSpinDial::getValue () const inline
Return current value.
Definition at line 172 of file FXRealSpinDial.h.
References pos, and setRange().
Referenced by GUIApplicationWindow::getDelay(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdChangeOption(), GUIApplicationWindow::onCmdDelayToggle(), onCmdGetIntValue(), onCmdGetRealValue(), GNESelectorFrame::onCmdScaleSelection(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdUserDef(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef(), and GUIRunThread::run().
increment()
void FX::FXRealSpinDial::increment (FXint incMode = SPINDIAL_INC_NORMAL)
Increment spinner.
Definition at line 927 of file FXRealSpinDial.cpp.
References incr, pos, range, setValue(), FX::SPINDIAL_CYCLIC, and FX::SPINDIAL_LOG.
Referenced by getRange(), onCmdIncrement(), onKeyPress(), and onMouseWheel().
isCyclic()
FXbool FX::FXRealSpinDial::isCyclic () const
Return TRUE if in cyclic mode.
Definition at line 973 of file FXRealSpinDial.cpp.
References FX::SPINDIAL_CYCLIC.
isDialVisible()
FXbool FX::FXRealSpinDial::isDialVisible () const
Return TRUE if dial is visible.
isEditable()
FXbool FX::FXRealSpinDial::isEditable () const
Return TRUE if text field is editable.
Definition at line 1133 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
isTextVisible()
FXbool FX::FXRealSpinDial::isTextVisible () const
Return TRUE if text is visible.
Definition at line 1046 of file FXRealSpinDial.cpp.
References textField.
layout()
void FX::FXRealSpinDial::layout () virtual
Perform layout.
Definition at line 544 of file FXRealSpinDial.cpp.
References BUTTONWIDTH, dial, DIALWIDTH, downButton, GAPWIDTH, FX::SPINDIAL_NOBUTTONS, FX::SPINDIAL_NODIAL, FX::SPINDIAL_NOTEXT, textField, and upButton.
load()
void FX::FXRealSpinDial::load (FXStream & store) virtual
Load spinner from a stream.
Definition at line 1242 of file FXRealSpinDial.cpp.
References dial, downButton, incr, pos, range, textField, and upButton.
Referenced by getCoarseIncrement().
onChgDial()
long FX::FXRealSpinDial::onChgDial (FXObject * , FXSelector , void *)
Definition at line 606 of file FXRealSpinDial.cpp.
References dial, DIALINCR, DIALMULT, dialpos, incr, pos, range, setValue(), FX::SPINDIAL_CYCLIC, and FX::SPINDIAL_LOG.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onChgEntry()
long FX::FXRealSpinDial::onChgEntry (FXObject * , FXSelector , void *)
Definition at line 762 of file FXRealSpinDial.cpp.
References pos, range, and textField.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdDecrement()
long FX::FXRealSpinDial::onCmdDecrement (FXObject * , FXSelector , void *)
Definition at line 714 of file FXRealSpinDial.cpp.
References decrement(), keystate, pos, FX::SPINDIAL_INC_COARSE, FX::SPINDIAL_INC_FINE, and FX::SPINDIAL_INC_NORMAL.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdDial()
long FX::FXRealSpinDial::onCmdDial (FXObject * , FXSelector , void *)
Definition at line 659 of file FXRealSpinDial.cpp.
References dial, DIALINCR, and dialpos.
onCmdEntry()
long FX::FXRealSpinDial::onCmdEntry (FXObject * , FXSelector , void *)
Definition at line 781 of file FXRealSpinDial.cpp.
References pos, and textField.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdGetIntRange()
long FX::FXRealSpinDial::onCmdGetIntRange (FXObject * , FXSelector , void * ptr)
Definition at line 890 of file FXRealSpinDial.cpp.
References range.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdGetIntValue()
long FX::FXRealSpinDial::onCmdGetIntValue (FXObject * , FXSelector , void * ptr)
Definition at line 874 of file FXRealSpinDial.cpp.
References getValue().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdGetRealRange()
long FX::FXRealSpinDial::onCmdGetRealRange (FXObject * , FXSelector , void * ptr)
Definition at line 919 of file FXRealSpinDial.cpp.
References getRange().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdGetRealValue()
long FX::FXRealSpinDial::onCmdGetRealValue (FXObject * , FXSelector , void * ptr)
Definition at line 905 of file FXRealSpinDial.cpp.
References getValue().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdIncrement()
long FX::FXRealSpinDial::onCmdIncrement (FXObject * , FXSelector , void *)
Definition at line 682 of file FXRealSpinDial.cpp.
References increment(), keystate, pos, FX::SPINDIAL_INC_COARSE, FX::SPINDIAL_INC_FINE, and FX::SPINDIAL_INC_NORMAL.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdSetIntRange()
long FX::FXRealSpinDial::onCmdSetIntRange (FXObject * , FXSelector , void * ptr)
Definition at line 881 of file FXRealSpinDial.cpp.
References setRange().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdSetIntValue()
long FX::FXRealSpinDial::onCmdSetIntValue (FXObject * , FXSelector , void * ptr)
Definition at line 867 of file FXRealSpinDial.cpp.
References setValue().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdSetRealRange()
long FX::FXRealSpinDial::onCmdSetRealRange (FXObject * , FXSelector , void * ptr)
Definition at line 912 of file FXRealSpinDial.cpp.
References setRange().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdSetRealValue()
long FX::FXRealSpinDial::onCmdSetRealValue (FXObject * , FXSelector , void * ptr)
Definition at line 898 of file FXRealSpinDial.cpp.
References setValue().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onCmdSetValue()
long FX::FXRealSpinDial::onCmdSetValue (FXObject * , FXSelector , void * ptr)
Definition at line 860 of file FXRealSpinDial.cpp.
References setValue().
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onKeyPress()
long FX::FXRealSpinDial::onKeyPress (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 791 of file FXRealSpinDial.cpp.
References decrement(), increment(), keystate, pos, FX::SPINDIAL_INC_COARSE, FX::SPINDIAL_INC_FINE, FX::SPINDIAL_INC_NORMAL, and textField.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onKeyRelease()
long FX::FXRealSpinDial::onKeyRelease (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 830 of file FXRealSpinDial.cpp.
References keystate, and textField.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onMotion()
long FX::FXRealSpinDial::onMotion (FXObject * , FXSelector , void * ptr)
Definition at line 851 of file FXRealSpinDial.cpp.
References keystate.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onMouseWheel()
long FX::FXRealSpinDial::onMouseWheel (FXObject * , FXSelector , void * p)
Definition at line 740 of file FXRealSpinDial.cpp.
References decrement(), increment(), keystate, pos, FX::SPINDIAL_INC_COARSE, FX::SPINDIAL_INC_FINE, and FX::SPINDIAL_INC_NORMAL.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onUpdDecrement()
long FX::FXRealSpinDial::onUpdDecrement (FXObject * sender, FXSelector , void *)
Definition at line 703 of file FXRealSpinDial.cpp.
References pos, and range.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onUpdDial()
long FX::FXRealSpinDial::onUpdDial (FXObject * sender, FXSelector , void *)
Definition at line 595 of file FXRealSpinDial.cpp.
References pos, range, and FX::SPINDIAL_CYCLIC.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onUpdEntry()
long FX::FXRealSpinDial::onUpdEntry (FXObject * , FXSelector , void *)
Definition at line 736 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
onUpdIncrement()
long FX::FXRealSpinDial::onUpdIncrement (FXObject * sender, FXSelector , void *)
Definition at line 671 of file FXRealSpinDial.cpp.
References pos, and range.
Referenced by FX::FXRealSpinDialText::onCmdSetRealValue().
operator=()
FXRealSpinDial& FX::FXRealSpinDial::operator= (const FXRealSpinDial &) private
save()
void FX::FXRealSpinDial::save (FXStream & store) const virtual
Save spinner to a stream.
Definition at line 1229 of file FXRealSpinDial.cpp.
References dial, downButton, incr, pos, range, textField, and upButton.
Referenced by getCoarseIncrement().
selectAll()
void FXRealSpinDial::selectAll ()
Mark the text entry as selected.
Definition at line 1266 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setCoarseIncrement()
void FX::FXRealSpinDial::setCoarseIncrement (FXdouble increment)
Change spinner coarse adjustment increment (when SHIFT key held down)
Definition at line 1029 of file FXRealSpinDial.cpp.
References incr.
Referenced by getRange().
setCursorColor()
void FX::FXRealSpinDial::setCursorColor (FXColor clr)
Changes the cursor color.
Definition at line 1199 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setCyclic()
void FX::FXRealSpinDial::setCyclic (FXbool cyclic)
Set to cyclic mode, i.e. wrap around at maximum/minimum.
Definition at line 979 of file FXRealSpinDial.cpp.
References FX::SPINDIAL_CYCLIC.
setDialColor()
void FX::FXRealSpinDial::setDialColor (FXColor clr)
Change color of the dial.
Definition at line 1138 of file FXRealSpinDial.cpp.
References dial.
Referenced by getCoarseIncrement().
setDialVisible()
void FX::FXRealSpinDial::setDialVisible (FXbool shown)
Set dial visible flag.
setDownArrowColor()
void FX::FXRealSpinDial::setDownArrowColor (FXColor clr)
Change color of the down arrow.
Definition at line 1158 of file FXRealSpinDial.cpp.
References downButton.
Referenced by getCoarseIncrement().
setEditable()
void FX::FXRealSpinDial::setEditable (FXbool edit = TRUE)
Allow editing of the text field.
Definition at line 1127 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setFineIncrement()
void FX::FXRealSpinDial::setFineIncrement (FXdouble increment)
Change spinner fine adjustment increment (when CTRL key held down)
Definition at line 1023 of file FXRealSpinDial.cpp.
References incr.
Referenced by getRange().
setFont()
void FX::FXRealSpinDial::setFont (FXFont * fnt)
Set the text font.
Definition at line 1062 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setFormatString()
void FX::FXRealSpinDial::setFormatString (const FXchar * fmt)
Set a format string for number display, using printf syntax. Format must contain no more than one fmt pattern. Calling this overrides the simple precision/exponent number format.
Definition at line 1220 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialText::setFormatString(), and textField.
Referenced by getCoarseIncrement().
setHelpText()
void FX::FXRealSpinDial::setHelpText (const FXString & text)
Set the status line help text for this spinner.
Definition at line 1074 of file FXRealSpinDial.cpp.
References dial, downButton, textField, and upButton.
Referenced by getCoarseIncrement(), and GNESelectorFrame::GNESelectorFrame().
setIncrement()
void FX::FXRealSpinDial::setIncrement (FXdouble increment)
Change spinner increment.
Definition at line 1017 of file FXRealSpinDial.cpp.
References incr.
Referenced by getRange().
setIncrements()
void FX::FXRealSpinDial::setIncrements (FXdouble fine, FXdouble norm, FXdouble coarse)
Change all spinner increment.
Definition at line 1035 of file FXRealSpinDial.cpp.
References incr.
Referenced by GUIApplicationWindow::buildToolBars(), getRange(), and GNESelectorFrame::GNESelectorFrame().
setNumberFormat()
void FX::FXRealSpinDial::setNumberFormat (FXint prec, FXbool bExp = FALSE)
Set the precision and exponent display for numbers Calling this overrides the number format string.
Definition at line 1208 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialText::setNumberFormat(), and textField.
Referenced by GUIApplicationWindow::buildToolBars(), getCoarseIncrement(), and GNESelectorFrame::GNESelectorFrame().
setRange()
void FX::FXRealSpinDial::setRange (FXdouble lo, FXdouble hi)
Change the spinner's range.
Definition at line 989 of file FXRealSpinDial.cpp.
References pos, range, and setValue().
Referenced by GUIApplicationWindow::buildToolBars(), getValue(), GNESelectorFrame::GNESelectorFrame(), onCmdSetIntRange(), and onCmdSetRealRange().
setSelBackColor()
void FX::FXRealSpinDial::setSelBackColor (FXColor clr)
Change selected background color.
Definition at line 1179 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setSelTextColor()
void FX::FXRealSpinDial::setSelTextColor (FXColor clr)
Change selected text color.
Definition at line 1189 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setSpinnerStyle()
void FX::FXRealSpinDial::setSpinnerStyle (FXuint style)
Change spinner style.
Definition at line 1105 of file FXRealSpinDial.cpp.
References range, SPINDIAL_MASK, FX::SPINDIAL_NOMAX, and FX::SPINDIAL_NOMIN.
Referenced by getCoarseIncrement().
setTextColor()
void FX::FXRealSpinDial::setTextColor (FXColor clr)
Change text color.
Definition at line 1169 of file FXRealSpinDial.cpp.
References textField.
Referenced by getCoarseIncrement().
setTextVisible()
void FX::FXRealSpinDial::setTextVisible (FXbool shown)
Set text visible flag.
Definition at line 1052 of file FXRealSpinDial.cpp.
References FX::SPINDIAL_NOTEXT.
setTipText()
void FX::FXRealSpinDial::setTipText (const FXString & text)
Set the tool tip message for this spinner.
Definition at line 1089 of file FXRealSpinDial.cpp.
References dial, downButton, textField, and upButton.
Referenced by getCoarseIncrement().
setUpArrowColor()
void FX::FXRealSpinDial::setUpArrowColor (FXColor clr)
Change color of the up arrow.
Definition at line 1148 of file FXRealSpinDial.cpp.
References upButton.
Referenced by getCoarseIncrement().
setValue()
void FX::FXRealSpinDial::setValue (FXdouble value) virtual
Change current value.
Definition at line 1002 of file FXRealSpinDial.cpp.
References pos, range, and textField.
Referenced by GUIApplicationWindow::buildToolBars(), decrement(), GNESelectorFrame::GNESelectorFrame(), GUIApplicationWindow::handleEvent_SimulationLoaded(), increment(), onChgDial(), GUIApplicationWindow::onCmdDelayToggle(), onCmdSetIntValue(), onCmdSetRealValue(), onCmdSetValue(), GUIApplicationWindow::setDelay(), and setRange().
Field Documentation
dial
FXDial* FX::FXRealSpinDial::dial protected
Definition at line 73 of file FXRealSpinDial.h.
Referenced by disable(), enable(), FXRealSpinDial(), getDial(), getDialColor(), layout(), load(), onChgDial(), onCmdDial(), save(), setDialColor(), setHelpText(), setTipText(), and ~FXRealSpinDial().
dialpos
FXint FX::FXRealSpinDial::dialpos protected
Definition at line 77 of file FXRealSpinDial.h.
Referenced by FXRealSpinDial(), onChgDial(), and onCmdDial().
downButton
FXArrowButton* FX::FXRealSpinDial::downButton protected
Definition at line 72 of file FXRealSpinDial.h.
Referenced by FXRealSpinDial(), getDownArrowColor(), layout(), load(), save(), setDownArrowColor(), setHelpText(), setTipText(), and ~FXRealSpinDial().
incr
FXdouble FX::FXRealSpinDial::incr[3] protected
Definition at line 75 of file FXRealSpinDial.h.
Referenced by decrement(), FXRealSpinDial(), increment(), load(), onChgDial(), save(), setCoarseIncrement(), setFineIncrement(), setIncrement(), and setIncrements().
keystate
FXint FX::FXRealSpinDial::keystate protected
Definition at line 78 of file FXRealSpinDial.h.
Referenced by FXRealSpinDial(), onCmdDecrement(), onCmdIncrement(), onKeyPress(), onKeyRelease(), onMotion(), and onMouseWheel().
pos
FXdouble FX::FXRealSpinDial::pos protected
Definition at line 76 of file FXRealSpinDial.h.
Referenced by decrement(), FXRealSpinDial(), getValue(), increment(), load(), onChgDial(), onChgEntry(), onCmdDecrement(), onCmdEntry(), onCmdIncrement(), onKeyPress(), onMouseWheel(), onUpdDecrement(), onUpdDial(), onUpdIncrement(), save(), setRange(), and setValue().
range
FXdouble FX::FXRealSpinDial::range[2] protected
Definition at line 74 of file FXRealSpinDial.h.
Referenced by decrement(), FXRealSpinDial(), increment(), load(), onChgDial(), onChgEntry(), onCmdGetIntRange(), onUpdDecrement(), onUpdDial(), onUpdIncrement(), save(), setRange(), setSpinnerStyle(), and setValue().
textField
FXRealSpinDialText* FX::FXRealSpinDial::textField protected
Definition at line 70 of file FXRealSpinDial.h.
Referenced by disable(), enable(), FXRealSpinDial(), getCursorColor(), getDefaultHeight(), getDefaultWidth(), getFont(), getHelpText(), getNumberFormatExponent(), getNumberFormatPrecision(), getNumberFormatString(), getSelBackColor(), getSelTextColor(), getTextColor(), getTipText(), isEditable(), isTextVisible(), layout(), load(), onChgEntry(), onCmdEntry(), onKeyPress(), onKeyRelease(), save(), selectAll(), setCursorColor(), setEditable(), setFont(), setFormatString(), setHelpText(), setNumberFormat(), setSelBackColor(), setSelTextColor(), setTextColor(), setTipText(), setValue(), and ~FXRealSpinDial().
upButton
FXArrowButton* FX::FXRealSpinDial::upButton protected
Definition at line 71 of file FXRealSpinDial.h.
Referenced by FXRealSpinDial(), getUpArrowColor(), layout(), load(), save(), setHelpText(), setTipText(), setUpArrowColor(), and ~FXRealSpinDial().
The documentation for this class was generated from the following files:
FXRealSpinDial.h
FXRealSpinDial.cpp