SUMO - Simulation of Urban MObility: TraCIAPI::RouteScope Class Reference
TraCIAPI::RouteScope Class Reference
Scope for interaction with routes.
#include <TraCIAPI.h>
Public Member Functions
void add (const std::string &routeID, const std::vector< std::string > &edges) const
std::vector< std::string > getEdges (const std::string &routeID) const
std::vector< std::string > getIDList () const
RouteScope (TraCIAPI &parent)
virtual ~RouteScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
RouteScope & operator= (const RouteScope &src)
invalidated assignment operator
RouteScope (const RouteScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with routes.
Definition at line 445 of file TraCIAPI.h.
Constructor & Destructor Documentation
RouteScope() [1/2]
TraCIAPI::RouteScope::RouteScope (TraCIAPI & parent) inline
Definition at line 447 of file TraCIAPI.h.
~RouteScope()
virtual TraCIAPI::RouteScope::~RouteScope () inline virtual
Definition at line 448 of file TraCIAPI.h.
References TraCIAPI::TraCIScopeWrapper::operator=().
RouteScope() [2/2]
TraCIAPI::RouteScope::RouteScope (const RouteScope & src) private
invalidated copy constructor
Member Function Documentation
add()
void TraCIAPI::RouteScope::add (const std::string & routeID, const std::vector< std::string > & edges) const
Definition at line 1472 of file TraCIAPI.cpp.
References ADD, CMD_SET_ROUTE_VARIABLE, TYPE_STRINGLIST, tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
getEdges()
std::vector< std::string > TraCIAPI::RouteScope::getEdges (const std::string & routeID) const
Definition at line 1466 of file TraCIAPI.cpp.
References CMD_GET_ROUTE_VARIABLE, and VAR_EDGES.
getIDList()
std::vector< std::string > TraCIAPI::RouteScope::getIDList () const
Definition at line 1461 of file TraCIAPI.cpp.
References CMD_GET_ROUTE_VARIABLE, and ID_LIST.
Referenced by TraCITestClient::testAPI().
operator=()
RouteScope& TraCIAPI::RouteScope::operator= (const RouteScope & src) private
invalidated assignment operator
Field Documentation
myParent
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 129 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp