SUMO - Simulation of Urban MObility: AGPosition Class Reference
AGPosition Class Reference
A location in the 2D plane freely positioned on a street.
#include <AGPosition.h>
Public Member Functions
AGPosition (const AGStreet &str, double pos)
Constructs an AGPosition at a certain point on a street.
AGPosition (const AGStreet &str)
Constructs an AGPosition at a random point on a street.
double distanceTo (const AGPosition &otherPos) const
Computes the distance between two AGPosition objects.
double getPosition () const
Provides the relative position of this AGPosition on the street.
const AGStreet & getStreet () const
Provides the street this AGPosition is located on.
double minDistanceTo (const std::list< AGPosition > &positions) const
Computes the distance to the closest position in a list.
double minDistanceTo (const std::map< int, AGPosition > &positions) const
Computes the distance to the closest position in a map.
bool operator== (const AGPosition &pos) const
Tests whether two positions are at the same place.
void print () const
Prints out a summary of the properties of this class on standard output.
Private Member Functions
Position compute2dPosition () const
Static Private Member Functions
static double randomPositionInStreet (const AGStreet &street)
Determines a random relative position on a street.
Private Attributes
Position pos2d
double position
const AGStreet * street
Detailed Description
A location in the 2D plane freely positioned on a street.
This class restricts the Position class in the way that it must be a position on a street. As a consequence, this position can be described either by x and y coordinates or by a street and its distance to the beginning of the street (the relative position).
Should this class be derived from Position?
Definition at line 62 of file AGPosition.h.
Constructor & Destructor Documentation
AGPosition() [1/2]
AGPosition::AGPosition (const AGStreet & str, double pos)
Constructs an AGPosition at a certain point on a street.
An AGPosition is determined by a street and the relative position on the street. This relative position is the distance from the from node of the street.
param[in] str the street on which the AGPosition is located param[in] pos the distance from the from node of the street
Definition at line 46 of file AGPosition.cpp.
AGPosition() [2/2]
AGPosition::AGPosition (const AGStreet & str)
Constructs an AGPosition at a random point on a street.
This constructor determines the distance from the from node with a random number based on a uniform density.
param[in] str the street on which the AGPosition is located
Definition at line 51 of file AGPosition.cpp.
Member Function Documentation
compute2dPosition()
Position AGPosition::compute2dPosition () const private
Creates a Position object to the street and position attribute of this class.
This method may only be called when street and position are initialised!
Returns
the Position object
Definition at line 125 of file AGPosition.cpp.
References Position::add(), ROEdge::getFromJunction(), ROEdge::getLength(), RONode::getPosition(), ROEdge::getToJunction(), Position::mul(), position, street, and Position::sub().
distanceTo()
double AGPosition::distanceTo (const AGPosition & otherPos) const
Computes the distance between two AGPosition objects.
Parameters
[in] the other position the distance in computed to
Returns
the distance
Definition at line 69 of file AGPosition.cpp.
References Position::distanceTo(), and pos2d.
Referenced by AGChild::allocateASchool(), AGActivity::availableTranspMeans(), AGTrip::getRideBackArrTime(), AGTrip::getTimeTrip(), minDistanceTo(), AGActivity::possibleTranspMean(), and AGActivity::timeToDrive().
getPosition()
double AGPosition::getPosition () const
Provides the relative position of this AGPosition on the street.
This relative position is the distance from the from node of the associated street.
Returns
the relative position
Definition at line 113 of file AGPosition.cpp.
References position.
Referenced by AGActivityTripWriter::addTrip(), AGWorkAndSchool::carsToTrips(), AGTrip::setArr(), and AGTrip::setDep().
getStreet()
const AGStreet & AGPosition::getStreet () const
Provides the street this AGPosition is located on.
Returns
the street
Definition at line 107 of file AGPosition.cpp.
References street.
Referenced by AGActivityTripWriter::addTrip(), AGWorkAndSchool::carsToTrips(), AGTrip::setArr(), and AGTrip::setDep().
minDistanceTo() [1/2]
double AGPosition::minDistanceTo (const std::list< AGPosition > & positions) const
Computes the distance to the closest position in a list.
minDistanceTo computes the distance to all positions in the given list and returns the minimal distance.
Parameters
[in] positions the list of positions the distances are computed to
Returns
the minimal distance
Definition at line 75 of file AGPosition.cpp.
References distanceTo().
Referenced by AGActivity::availableTranspMeans(), AGHousehold::isCloseFromPubTransport(), and AGActivity::possibleTranspMean().
minDistanceTo() [2/2]
double AGPosition::minDistanceTo (const std::map< int, AGPosition > & positions) const
Computes the distance to the closest position in a map.
minDistanceTo computes the distance to all positions given as the second elements of a map and returns the minimal distance.
Parameters
[in] positions the map of positions the distances are computed to
Returns
the minimal distance
Definition at line 91 of file AGPosition.cpp.
References distanceTo().
operator==()
bool AGPosition::operator== (const AGPosition & pos) const
Tests whether two positions are at the same place.
Compares the x and y coordinates with a threshold (see Position::almostSame)
Parameters
[in] pos the position with which the comparison is done
Returns
true if both AGPositions are (almost) at the same place
Definition at line 63 of file AGPosition.cpp.
References Position::almostSame(), and pos2d.
print()
void AGPosition::print () const
Prints out a summary of the properties of this class on standard output.
Definition at line 57 of file AGPosition.cpp.
References ROEdge::getLength(), position, and street.
Referenced by AGWorkPosition::print(), and AGTrip::print().
randomPositionInStreet()
double AGPosition::randomPositionInStreet (const AGStreet & street) static private
Determines a random relative position on a street.
Returns
the random relative position
Definition at line 119 of file AGPosition.cpp.
References ROEdge::getLength(), and RandHelper::rand().
Field Documentation
pos2d
Position AGPosition::pos2d private
Definition at line 143 of file AGPosition.h.
Referenced by distanceTo(), and operator==().
position
double AGPosition::position private
Definition at line 142 of file AGPosition.h.
Referenced by compute2dPosition(), getPosition(), and print().
street
const AGStreet* AGPosition::street private
Definition at line 141 of file AGPosition.h.
Referenced by compute2dPosition(), getStreet(), and print().
The documentation for this class was generated from the following files:
AGPosition.h
AGPosition.cpp