SUMO - Simulation of Urban MObility: NLBuilder Class Reference
NLBuilder Class Reference
The main interface for loading a microsim.
#include <NLBuilder.h>
Data Structures
class EdgeFloatTimeLineRetriever_EdgeEffort
class EdgeFloatTimeLineRetriever_EdgeTravelTime
Obtains edge efforts from a weights handler and stores them within the edges.
Public Member Functions
virtual bool build ()
Builds and initialises the simulation.
NLBuilder (OptionsCont &oc, MSNet &net, NLEdgeControlBuilder &eb, NLJunctionControlBuilder &jb, NLDetectorBuilder &db, NLHandler &xmlHandler)
Constructor.
virtual ~NLBuilder ()
Destructor.
Static Public Member Functions
static MSNet * init ()
Protected Member Functions
void buildNet ()
Closes the net building process.
SUMORouteLoaderControl * buildRouteLoaderControl (const OptionsCont &oc)
Builds the route loader control.
bool load (const std::string &mmlWhat, const bool isNet=false)
Loads a described subpart form the given list of files.
Protected Attributes
NLDetectorBuilder & myDetectorBuilder
The detector control builder to use.
NLEdgeControlBuilder & myEdgeBuilder
The edge control builder to use.
NLJunctionControlBuilder & myJunctionBuilder
The junction control builder to use.
MSNet & myNet
The net to fill.
OptionsCont & myOptions
The options to get the names of the files to load and further information from.
NLHandler & myXMLHandler
The handler used to parse the net.
Private Member Functions
NLBuilder (const NLBuilder &s)
invalidated copy operator
NLBuilder & operator= (const NLBuilder &s)
invalidated assignment operator
Detailed Description
The main interface for loading a microsim.
It is a black-box where only the options and factories must be supplied on the constructor call. An (empty) instance of the network must be supplied, too, and is filled during loading.
Definition at line 67 of file NLBuilder.h.
Constructor & Destructor Documentation
NLBuilder() [1/2]
NLBuilder::NLBuilder (OptionsCont & oc, MSNet & net, NLEdgeControlBuilder & eb, NLJunctionControlBuilder & jb, NLDetectorBuilder & db, NLHandler & xmlHandler)
Constructor.
Parameters
[in] oc The options to use
[in,out] net The network to fill
[in] eb The builder of edges to use
[in] jb The builder of junctions to use
[in] db The detector builder to use
[in] tb The trigger builder to use
[in] xmlHandler The xml handler to use
Definition at line 111 of file NLBuilder.cpp.
~NLBuilder()
NLBuilder::~NLBuilder () virtual
Destructor.
Definition at line 122 of file NLBuilder.cpp.
NLBuilder() [2/2]
NLBuilder::NLBuilder (const NLBuilder & s) private
invalidated copy operator
Member Function Documentation
build()
bool NLBuilder::build () virtual
Builds and initialises the simulation.
At first, the network is loaded and the built using "buildNet". If this could be done, additional information is loaded (state dump, weight files, route files, and additional files). If everything could be done, true is returned, otherwise false.
See also
buildNet
Exceptions
ProcessError If something fails on network building
Todo:
Again, both returning a bool and throwing an exception; quite inconsistent
Definition at line 126 of file NLBuilder.cpp.
References buildNet(), OptionsCont::getBool(), SysUtils::getCurrentMillis(), MSNet::getEdgeControl(), MsgHandler::getErrorInstance(), TraCIServer::getInstance(), MSNet::getShapeContainer(), OptionsCont::getString(), OptionsCont::getStringVector(), MSStateHandler::getTime(), MSNet::getTLSControl(), NLHandler::haveSeenAdditionalSpeedRestrictions(), NLHandler::haveSeenInternalEdge(), NLHandler::haveSeenNeighs(), OptionsCont::isDefault(), OptionsCont::isSet(), OptionsCont::isUsableFileList(), load(), ShapeHandler::loadFiles(), myNet, myOptions, myXMLHandler, PROGRESS_BEGIN_MESSAGE, PROGRESS_TIME_MESSAGE, XMLSubSys::runParser(), OptionsCont::set(), MSEdgeControl::setAdditionalRestrictions(), TraCIServer::setTargetTime(), string2time(), MSTLLogicControl::switchOffAll(), time2string(), MsgHandler::wasInformed(), WRITE_MESSAGE, and WRITE_WARNING.
Referenced by init(), and GUILoadThread::run().
buildNet()
void NLBuilder::buildNet () protected
Closes the net building process.
Builds the microsim-structures which belong to a MSNet using the factories filled while loading. Initialises the network using these structures by calling MSNet::closeBuilding. If an error occurs, all built structures are deleted and a ProcessError is thrown.
Exceptions
ProcessError If the loaded structures could not be built
Definition at line 277 of file NLBuilder.cpp.
References NLEdgeControlBuilder::build(), NLJunctionControlBuilder::build(), buildRouteLoaderControl(), MSFrame::buildStreams(), NLJunctionControlBuilder::buildTLLogics(), MSNet::closeBuilding(), OptionsCont::getIntVector(), OptionsCont::getString(), OptionsCont::getStringVector(), NLHandler::haveSeenInternalEdge(), NLHandler::haveSeenNeighs(), OptionsCont::isSet(), NLHandler::lefthand(), myEdgeBuilder, myJunctionBuilder, myNet, myOptions, myXMLHandler, NLHandler::networkVersion(), TIME2STEPS, time2string(), and WRITE_ERROR.
Referenced by build().
buildRouteLoaderControl()
SUMORouteLoaderControl * NLBuilder::buildRouteLoaderControl (const OptionsCont & oc) protected
Builds the route loader control.
Goes through the list of route files to open defined in the option "route-files" and builds loaders reading these files
Parameters
[in] oc The options to read the list of route files to open from
Returns
The built route loader control
Exceptions
ProcessError If an error occured
Definition at line 348 of file NLBuilder.cpp.
References SUMORouteLoaderControl::add(), OptionsCont::getString(), OptionsCont::getStringVector(), FileHelpers::isReadable(), OptionsCont::isSet(), and string2time().
Referenced by buildNet().
init()
MSNet * NLBuilder::init () static
loads the net, additional routes and the detectors
Definition at line 226 of file NLBuilder.cpp.
References build(), MSFrame::checkOptions(), MsgHandler::clear(), OptionsCont::clear(), SystemFrame::close(), MSFrame::fillOptions(), OptionsIO::getArgC(), MSDevice::getEquipmentRNG(), MsgHandler::getErrorInstance(), MsgHandler::getMessageInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), MSRouteHandler::getParsingRNG(), OptionsCont::getString(), MsgHandler::getWarningInstance(), MSGlobals::gUseMesoSim, MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), MSNet::loadRoutes(), TraCIServer::openSocket(), OptionsCont::processMetaOptions(), NLTriggerBuilder::setHandler(), MSFrame::setMSGlobals(), and XMLSubSys::setValidation().
Referenced by libsumo::Simulation::load(), and main().
load()
bool NLBuilder::load (const std::string & mmlWhat, const bool isNet = false) protected
Loads a described subpart form the given list of files.
Assuming the given string to be an option name behind which a list of files is stored, this method invokes an XML reader on all the files set for this option.
Parameters
[in] mmlWhat The option to get the file list from
[in] isNet whether a network gets loaded
Returns
Whether loading of all files was successfull
Definition at line 329 of file NLBuilder.cpp.
References SysUtils::getCurrentMillis(), OptionsCont::getStringVector(), OptionsCont::isUsableFileList(), myOptions, myXMLHandler, PROGRESS_BEGIN_MESSAGE, PROGRESS_TIME_MESSAGE, XMLSubSys::runParser(), and WRITE_MESSAGE.
Referenced by build().
operator=()
NLBuilder& NLBuilder::operator= (const NLBuilder & s) private
invalidated assignment operator
Field Documentation
myDetectorBuilder
NLDetectorBuilder& NLBuilder::myDetectorBuilder protected
The detector control builder to use.
Definition at line 217 of file NLBuilder.h.
myEdgeBuilder
NLEdgeControlBuilder& NLBuilder::myEdgeBuilder protected
The edge control builder to use.
Definition at line 211 of file NLBuilder.h.
Referenced by buildNet().
myJunctionBuilder
NLJunctionControlBuilder& NLBuilder::myJunctionBuilder protected
The junction control builder to use.
Definition at line 214 of file NLBuilder.h.
Referenced by buildNet().
myNet
MSNet& NLBuilder::myNet protected
The net to fill.
Definition at line 220 of file NLBuilder.h.
Referenced by build(), and buildNet().
myOptions
OptionsCont& NLBuilder::myOptions protected
The options to get the names of the files to load and further information from.
Definition at line 208 of file NLBuilder.h.
Referenced by build(), buildNet(), and load().
myXMLHandler
NLHandler& NLBuilder::myXMLHandler protected
The handler used to parse the net.
Definition at line 223 of file NLBuilder.h.
Referenced by build(), buildNet(), and load().
The documentation for this class was generated from the following files:
NLBuilder.h
NLBuilder.cpp