SUMO - Simulation of Urban MObility: GNEViewParent Class Reference
GNEViewParent Class Reference
A single child window which contains a view of the simulation area.
#include <GNEViewParent.h>
Public Member Functions
void buildColoringToolBar ()
void buildNavigationToolBar ()
void buildScreenshotToolBar ()
virtual void create ()
GNEAdditionalFrame * getAdditionalFrame () const
get frame for GNE_MODE_ADDITIONAL
GUIMainWindow * getApp () const
get App (GUIMainWindow)
virtual FXGLCanvas * getBuildGLCanvas () const
FXComboBox & getColoringSchemesCombo ()
GNEConnectorFrame * getConnectorFrame () const
get frame for GNE_MODE_CONNECT
GNECrossingFrame * getCrossingFrame () const
get frame for GNE_MODE_CROSSING
GNEDeleteFrame * getDeleteFrame () const
get frame for GNE_MODE_DELETE
GNEApplicationWindow * getGNEAppWindows () const
get GNE Application Windows
GNEInspectorFrame * getInspectorFrame () const
get frame for GNE_MODE_INSPECT
FXPopup * getLocatorPopup ()
FXToolBar & getNavigationToolBar (GUISUMOAbstractView &v)
GUIMainWindow * getParent ()
Returns the main window.
GNEPolygonFrame * getPolygonFrame () const
get frame for GNE_MODE_POLYGON
GNESelectorFrame * getSelectorFrame () const
get frame for GNE_MODE_SELECT
GNETLSEditorFrame * getTLSEditorFrame () const
get frame for GNE_MODE_TLS
GUISUMOAbstractView * getView () const
GNEViewParent (FXMDIClient *p, FXMDIMenu *mdimenu, const FXString &name, GNEApplicationWindow *parentWindow, FXGLCanvas *share, GNENet *net, GNEUndoList *undoList, FXIcon *ic=NULL, FXuint opts=0, FXint x=0, FXint y=0, FXint w=0, FXint h=0)
FOX-declaration.
void hideAllFrames ()
hide all frames
void hideFramesArea ()
hide frames area if all GNEFrames are hidden
bool isSelected (GUIGlObject *o) const
true if the object is selected (may include extra logic besides calling gSelected)
long onCmdChangeColorScheme (FXObject *, FXSelector sel, void *)
long onCmdEditViewport (FXObject *, FXSelector, void *)
long onCmdEditViewScheme (FXObject *, FXSelector, void *)
long onCmdRecenterView (FXObject *, FXSelector, void *)
long onCmdShowToolTips (FXObject *sender, FXSelector, void *)
long onCmdZoomStyle (FXObject *sender, FXSelector, void *)
void setView (GUIGlID id)
Centers the view onto the given artifact.
void showFramesArea ()
show frames area if at least a GNEFrame is showed
~GNEViewParent ()
Destructor.
FOX-callbacks
Called if the user wants to make a snapshot (screenshot)
long onCmdMakeSnapshot (FXObject *sender, FXSelector, void *)
long onCmdClose (FXObject *, FXSelector, void *)
Called when the user hits the close button (x)
long onCmdLocate (FXObject *, FXSelector, void *)
locator-callback
long onKeyPress (FXObject *o, FXSelector sel, void *data)
Called when user press a key.
long onKeyRelease (FXObject *o, FXSelector sel, void *data)
Called when user releases a key.
long onCmdUpdateFrameAreaWidth (FXObject *, FXSelector, void *)
Called when user change the splitter between FrameArea and ViewNet.
Protected Member Functions
GNEViewParent ()
FOX needs this.
Protected Attributes
FXComboBox * myColoringSchemes
FXVerticalFrame * myContentFrame
FXMenuButton * myLocatorButton
FXPopup * myLocatorPopup
The locator menu.
FXToolBar * myNavigationToolBar
The tool bar.
GUIMainWindow * myParent
The parent window.
GUISUMOAbstractView * myView
the view
Private Attributes
FXHorizontalFrame * myFramesArea
frame to hold GNEFrames
FXSplitter * myFramesSplitter
Splitter to divide ViewNet und GNEFrames.
GNEApplicationWindow * myGNEAppWindows
pointer to GNEApplicationWindow
std::map< int, GNEFrame * > myGNEFrames
map with the Frames
FXHorizontalFrame * myViewArea
frame to hold myView and myAttributePanel
Detailed Description
A single child window which contains a view of the simulation area.
It is made of a tool-bar containing a field to change the type of display, buttons that allow to choose an artifact and some other view controlling options.
The rest of the window is a canvas that contains the display itself
Definition at line 72 of file GNEViewParent.h.
Constructor & Destructor Documentation
GNEViewParent() [1/2]
GNEViewParent::GNEViewParent (FXMDIClient * p, FXMDIMenu * mdimenu, const FXString & name, GNEApplicationWindow * parentWindow, FXGLCanvas * share, GNENet * net, GNEUndoList * undoList, FXIcon * ic = NULL, FXuint opts = 0, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0)
FOX-declaration.
Constructor also builds the view and calls create()
Parameters
[in] p The MDI-pane this window is shown within
[in] mdimenu The MDI-menu for alignment
[in] name The name of the window
[in] parentWindow The main window
[in] ic The icon of this window
[in] opts Window options
[in] x Initial x-position
[in] y Initial x-position
[in] w Initial width
[in] h Initial height
[in] share A canvas tor get the shared context from
[in] net The network to show
Definition at line 91 of file GNEViewParent.cpp.
References GNEViewNet::buildViewToolBars(), GUIGlChildWindow::create(), GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignFrameArea, GUIDesignSplitter, GUIDesignVerticalSeparator, GUIDesignViewnArea, ICON_REDO, ICON_UNDO, MID_GNE_SETMODE_ADDITIONAL, MID_GNE_SETMODE_CONNECT, MID_GNE_SETMODE_CROSSING, MID_GNE_SETMODE_DELETE, MID_GNE_SETMODE_INSPECT, MID_GNE_SETMODE_POLYGON, MID_GNE_SETMODE_SELECT, MID_GNE_SETMODE_TLS, and MID_GNE_VIEWPARENT_FRAMEAREAWIDTH.
~GNEViewParent()
GNEViewParent::~GNEViewParent ()
Destructor.
Definition at line 160 of file GNEViewParent.cpp.
References GUIGlChildWindow::myParent, and GUIMainWindow::removeChild().
GNEViewParent() [2/2]
GNEViewParent::GNEViewParent () inline protected
FOX needs this.
Definition at line 168 of file GNEViewParent.h.
Member Function Documentation
buildColoringToolBar()
void GUIGlChildWindow::buildColoringToolBar () inherited
Definition at line 126 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignComboBoxNCol, GUIDesignComboBoxStatic, GUIDesignVerticalSeparator, ICON_COLORWHEEL, MID_COLOURSCHEMECHANGE, MID_EDITVIEWSCHEME, GUIGlChildWindow::myColoringSchemes, and GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIGlChildWindow::getView().
buildNavigationToolBar()
void GUIGlChildWindow::buildNavigationToolBar () inherited
Definition at line 93 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignBar, GUIDesignButtonToolbar, GUIDesignButtonToolbarCheckable, GUIDesignButtonToolbarLocator, ICON_EDITVIEWPORT, ICON_LOCATE, ICON_RECENTERVIEW, ICON_SHOWTOOLTIPS, ICON_ZOOMSTYLE, MID_EDITVIEWPORT, MID_RECENTERVIEW, MID_SHOWTOOLTIPS, MID_ZOOM_STYLE, GUIGlChildWindow::myContentFrame, GUIGlChildWindow::myLocatorButton, GUIGlChildWindow::myLocatorPopup, GUIGlChildWindow::myNavigationToolBar, and MFXCheckableButton::setChecked().
Referenced by GUIGlChildWindow::getView().
buildScreenshotToolBar()
void GUIGlChildWindow::buildScreenshotToolBar () inherited
Definition at line 141 of file GUIGlChildWindow.cpp.
References GUIIconSubSys::getIcon(), GUIDesignButtonToolbar, GUIDesignVerticalSeparator, ICON_CAMERA, MID_MAKESNAPSHOT, and GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIGlChildWindow::getView().
create()
void GUIGlChildWindow::create () virtual inherited
Definition at line 84 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myLocatorPopup, GUIGlChildWindow::myNavigationToolBar, and GUIGlChildWindow::myView.
Referenced by GNEViewParent(), and GUIApplicationWindow::openNewView().
getAdditionalFrame()
GNEAdditionalFrame * GNEViewParent::getAdditionalFrame () const
get frame for GNE_MODE_ADDITIONAL
Definition at line 198 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_ADDITIONAL, and myGNEFrames.
Referenced by GNEViewNet::deleteSelectedAdditionals(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), and GNEViewNet::updateModeSpecificControls().
getApp()
GUIMainWindow * GNEViewParent::getApp () const
get App (GUIMainWindow)
Definition at line 257 of file GNEViewParent.cpp.
References GUIGlChildWindow::myParent.
Referenced by GNEDeleteFrame::createPopUpMenu(), and GNEInspectorFrame::createPopUpMenu().
getBuildGLCanvas()
FXGLCanvas * GUIGlChildWindow::getBuildGLCanvas () const virtual inherited
Definition at line 152 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView.
Referenced by GUIApplicationWindow::getBuildGLCanvas(), and GNEApplicationWindow::getBuildGLCanvas().
getColoringSchemesCombo()
FXComboBox & GUIGlChildWindow::getColoringSchemesCombo () inherited
Definition at line 170 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myColoringSchemes.
Referenced by GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), GUISUMOAbstractView::getColoringSchemesCombo(), and GUIGlChildWindow::getView().
getConnectorFrame()
GNEConnectorFrame * GNEViewParent::getConnectorFrame () const
get frame for GNE_MODE_CONNECT
Definition at line 186 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_CONNECT, and myGNEFrames.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::hotkeyEnter(), GNEViewNet::onLeftBtnPress(), and GNEViewNet::updateModeSpecificControls().
getCrossingFrame()
GNECrossingFrame * GNEViewParent::getCrossingFrame () const
get frame for GNE_MODE_CROSSING
Definition at line 204 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_CROSSING, and myGNEFrames.
Referenced by GNEViewNet::hotkeyEnter(), GNEViewNet::onLeftBtnPress(), and GNEViewNet::updateModeSpecificControls().
getDeleteFrame()
GNEDeleteFrame * GNEViewParent::getDeleteFrame () const
get frame for GNE_MODE_DELETE
Definition at line 210 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_DELETE, and myGNEFrames.
Referenced by GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onMouseMove(), and GNEViewNet::updateModeSpecificControls().
getGNEAppWindows()
GNEApplicationWindow * GNEViewParent::getGNEAppWindows () const
get GNE Application Windows
Definition at line 263 of file GNEViewParent.cpp.
References myGNEAppWindows.
Referenced by GNENet::requiereSaveAdditionals(), and GNENet::requiereSaveShapes().
getInspectorFrame()
GNEInspectorFrame * GNEViewParent::getInspectorFrame () const
get frame for GNE_MODE_INSPECT
Definition at line 174 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_INSPECT, and myGNEFrames.
Referenced by GNEDeleteFrame::onCmdInspectChildItem(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNEViewNet::updateControls(), and GNEViewNet::updateModeSpecificControls().
getLocatorPopup()
FXPopup * GUIGlChildWindow::getLocatorPopup () inherited
Definition at line 164 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myLocatorPopup.
Referenced by GUIViewTraffic::buildViewToolBars(), GNEViewNet::buildViewToolBars(), and GUIGlChildWindow::getView().
getNavigationToolBar()
FXToolBar & GUIGlChildWindow::getNavigationToolBar (GUISUMOAbstractView & v) inherited
Definition at line 158 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myNavigationToolBar.
Referenced by GUIGlChildWindow::getView().
getParent()
GUIMainWindow* GUIGlChildWindow::getParent () inline inherited
Returns the main window.
Returns
This view's parent
Definition at line 88 of file GUIGlChildWindow.h.
References GUIGlChildWindow::isSelected(), and GUIGlChildWindow::myParent.
Referenced by GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser().
getPolygonFrame()
GNEPolygonFrame * GNEViewParent::getPolygonFrame () const
get frame for GNE_MODE_POLYGON
Definition at line 216 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_POLYGON, and myGNEFrames.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onRightBtnPress(), GNEViewNet::onRightBtnRelease(), and GNEViewNet::updateModeSpecificControls().
getSelectorFrame()
GNESelectorFrame * GNEViewParent::getSelectorFrame () const
get frame for GNE_MODE_SELECT
Definition at line 180 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_SELECT, and myGNEFrames.
Referenced by GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onLeftBtnRelease(), and GNEViewNet::updateModeSpecificControls().
getTLSEditorFrame()
GNETLSEditorFrame * GNEViewParent::getTLSEditorFrame () const
get frame for GNE_MODE_TLS
Definition at line 192 of file GNEViewParent.cpp.
References MID_GNE_SETMODE_TLS, and myGNEFrames.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::hotkeyEnter(), GNEViewNet::onLeftBtnPress(), and GNEViewNet::updateModeSpecificControls().
getView()
GUISUMOAbstractView* GUIGlChildWindow::getView () const inline inherited
Definition at line 59 of file GUIGlChildWindow.h.
References GUIGlChildWindow::buildColoringToolBar(), GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::buildScreenshotToolBar(), GUIGlChildWindow::getColoringSchemesCombo(), GUIGlChildWindow::getLocatorPopup(), GUIGlChildWindow::getNavigationToolBar(), GUIGlChildWindow::myView, GUIGlChildWindow::onCmdChangeColorScheme(), GUIGlChildWindow::onCmdEditViewport(), GUIGlChildWindow::onCmdEditViewScheme(), GUIGlChildWindow::onCmdRecenterView(), GUIGlChildWindow::onCmdShowToolTips(), GUIGlChildWindow::onCmdZoomStyle(), and GUIGlChildWindow::setView().
Referenced by GUIMainWindow::getActiveView(), TraCIServerAPI_GUI::getNamedView(), GUIApplicationWindow::onCmdEditChosen(), GUIApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdShowStats(), GUIDialog_GLObjChooser::onCmdToggleSelection(), GUIApplicationWindow::openNewView(), and GNEApplicationWindow::openNewView().
hideAllFrames()
void GNEViewParent::hideAllFrames ()
hide all frames
Definition at line 167 of file GNEViewParent.cpp.
References myGNEFrames.
Referenced by GNEViewNet::updateModeSpecificControls().
hideFramesArea()
void GNEViewParent::hideFramesArea ()
hide frames area if all GNEFrames are hidden
Note
this function is called in GNEFrame::Show();
Definition at line 239 of file GNEViewParent.cpp.
References myFramesArea, and myGNEFrames.
Referenced by GNEFrame::hide().
isSelected()
bool GNEViewParent::isSelected (GUIGlObject * o) const virtual
true if the object is selected (may include extra logic besides calling gSelected)
Reimplemented from GUIGlChildWindow.
Definition at line 368 of file GNEViewParent.cpp.
References GUIGlObject::getGlID(), GNEEdge::getLaneGlIDs(), GUIGlObject::getType(), GLO_EDGE, GLO_LANE, gSelected, and GUISelectedStorage::isSelected().
onCmdChangeColorScheme()
long GUIGlChildWindow::onCmdChangeColorScheme (FXObject * , FXSelector sel, void * data) inherited
Definition at line 221 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::setColorScheme().
Referenced by GUIGlChildWindow::getView().
onCmdClose()
long GNEViewParent::onCmdClose (FXObject * , FXSelector , void *)
Called when the user hits the close button (x)
Definition at line 307 of file GNEViewParent.cpp.
References MID_CLOSE, and GUIGlChildWindow::myParent.
onCmdEditViewport()
long GUIGlChildWindow::onCmdEditViewport (FXObject * , FXSelector , void *) inherited
Definition at line 184 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::showViewportEditor().
Referenced by GUIGlChildWindow::getView().
onCmdEditViewScheme()
long GUIGlChildWindow::onCmdEditViewScheme (FXObject * , FXSelector , void *) inherited
Definition at line 191 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::showViewschemeEditor().
Referenced by GUIGlChildWindow::getView().
onCmdLocate()
long GNEViewParent::onCmdLocate (FXObject * , FXSelector sel, void *)
locator-callback
Definition at line 314 of file GNEViewParent.cpp.
References GNENet::getGlIDs(), GUIIconSubSys::getIcon(), GNEViewNet::getNet(), GUIGlObjectStorage::gIDStorage, GLO_ADDITIONAL, GLO_EDGE, GLO_JUNCTION, GLO_POI, GLO_POLYGON, GLO_TLLOGIC, ICON_LOCATEADD, ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATEPOI, ICON_LOCATEPOLY, ICON_LOCATETLS, MID_LOCATEADD, MID_LOCATEEDGE, MID_LOCATEJUNCTION, MID_LOCATEPOI, MID_LOCATEPOLY, MID_LOCATETLS, GUIGlChildWindow::myLocatorButton, GUIGlChildWindow::myLocatorPopup, GUIGlChildWindow::myView, and GUIDialog_GLObjChooser::show().
Referenced by GNEApplicationWindow::onCmdLocate().
onCmdMakeSnapshot()
long GNEViewParent::onCmdMakeSnapshot (FXObject * sender, FXSelector , void *)
Definition at line 269 of file GNEViewParent.cpp.
References gCurrentFolder, OptionsCont::getBool(), GUIIconSubSys::getIcon(), OptionsCont::getOptions(), ICON_EMPTY, GUISUMOAbstractView::makeSnapshot(), GUIGlChildWindow::myView, MFXUtils::userPermitsOverwritingWhenFileExists(), and WRITE_WARNING.
onCmdRecenterView()
long GUIGlChildWindow::onCmdRecenterView (FXObject * , FXSelector , void *) inherited
Definition at line 176 of file GUIGlChildWindow.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::recenterView().
Referenced by GUIGlChildWindow::getView().
onCmdShowToolTips()
long GUIGlChildWindow::onCmdShowToolTips (FXObject * sender, FXSelector , void *) inherited
Definition at line 198 of file GUIGlChildWindow.cpp.
References MFXCheckableButton::amChecked(), GUIGlChildWindow::myView, MFXCheckableButton::setChecked(), and GUISUMOAbstractView::showToolTips().
Referenced by GUIGlChildWindow::getView().
onCmdUpdateFrameAreaWidth()
long GNEViewParent::onCmdUpdateFrameAreaWidth (FXObject * , FXSelector , void *)
Called when user change the splitter between FrameArea and ViewNet.
Definition at line 403 of file GNEViewParent.cpp.
References myFramesArea, and myGNEFrames.
onCmdZoomStyle()
long GUIGlChildWindow::onCmdZoomStyle (FXObject * sender, FXSelector , void *) inherited
Definition at line 209 of file GUIGlChildWindow.cpp.
References MFXCheckableButton::amChecked(), GUIGlChildWindow::myView, and MFXCheckableButton::setChecked().
Referenced by GUIGlChildWindow::getView().
onKeyPress()
long GNEViewParent::onKeyPress (FXObject * o, FXSelector sel, void * data)
Called when user press a key.
Definition at line 389 of file GNEViewParent.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::onKeyPress().
Referenced by GNEApplicationWindow::onKeyPress().
onKeyRelease()
long GNEViewParent::onKeyRelease (FXObject * o, FXSelector sel, void * data)
Called when user releases a key.
Definition at line 396 of file GNEViewParent.cpp.
References GUIGlChildWindow::myView, and GUISUMOAbstractView::onKeyRelease().
Referenced by GNEApplicationWindow::onKeyRelease().
setView()
void GUIGlChildWindow::setView (GUIGlID id) inherited
Centers the view onto the given artifact.
Parameters
[in] id The id of the object to center the view on
Definition at line 228 of file GUIGlChildWindow.cpp.
References GUISUMOAbstractView::centerTo(), and GUIGlChildWindow::myView.
Referenced by GUIGlChildWindow::getView(), GUIDialog_GLObjChooser::onCmdCenter(), GUIDialog_GLObjChooser::onCmdText(), and GUIMessageWindow::setCursorPos().
showFramesArea()
void GNEViewParent::showFramesArea ()
show frames area if at least a GNEFrame is showed
Note
this function is called in GNEFrame::Show();
Definition at line 221 of file GNEViewParent.cpp.
References myFramesArea, and myGNEFrames.
Referenced by GNEFrame::show().
Field Documentation
myColoringSchemes
FXComboBox* GUIGlChildWindow::myColoringSchemes protected inherited
Definition at line 110 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildColoringToolBar(), and GUIGlChildWindow::getColoringSchemesCombo().
myContentFrame
FXVerticalFrame* GUIGlChildWindow::myContentFrame protected inherited
Definition at line 108 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), and GUISUMOViewParent::init().
myFramesArea
FXHorizontalFrame* GNEViewParent::myFramesArea private
frame to hold GNEFrames
Definition at line 178 of file GNEViewParent.h.
Referenced by hideFramesArea(), onCmdUpdateFrameAreaWidth(), and showFramesArea().
myFramesSplitter
FXSplitter* GNEViewParent::myFramesSplitter private
Splitter to divide ViewNet und GNEFrames.
Definition at line 181 of file GNEViewParent.h.
myGNEAppWindows
GNEApplicationWindow* GNEViewParent::myGNEAppWindows private
pointer to GNEApplicationWindow
Definition at line 172 of file GNEViewParent.h.
Referenced by getGNEAppWindows().
myGNEFrames
std::map<int, GNEFrame*> GNEViewParent::myGNEFrames private
map with the Frames
Definition at line 184 of file GNEViewParent.h.
Referenced by getAdditionalFrame(), getConnectorFrame(), getCrossingFrame(), getDeleteFrame(), getInspectorFrame(), getPolygonFrame(), getSelectorFrame(), getTLSEditorFrame(), hideAllFrames(), hideFramesArea(), onCmdUpdateFrameAreaWidth(), and showFramesArea().
myLocatorButton
FXMenuButton* GUIGlChildWindow::myLocatorButton protected inherited
Definition at line 106 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), GUISUMOViewParent::onCmdLocate(), and onCmdLocate().
myLocatorPopup
FXPopup* GUIGlChildWindow::myLocatorPopup protected inherited
The locator menu.
Definition at line 105 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::create(), GUIGlChildWindow::getLocatorPopup(), GUISUMOViewParent::onCmdLocate(), onCmdLocate(), and GUIGlChildWindow::~GUIGlChildWindow().
myNavigationToolBar
FXToolBar* GUIGlChildWindow::myNavigationToolBar protected inherited
The tool bar.
Definition at line 102 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::buildColoringToolBar(), GUIGlChildWindow::buildNavigationToolBar(), GUIGlChildWindow::buildScreenshotToolBar(), GUIGlChildWindow::create(), GUIGlChildWindow::getNavigationToolBar(), GUISUMOViewParent::init(), GUISUMOViewParent::setToolBarVisibility(), and GUIGlChildWindow::~GUIGlChildWindow().
myParent
GUIMainWindow* GUIGlChildWindow::myParent protected inherited
The parent window.
Definition at line 113 of file GUIGlChildWindow.h.
Referenced by getApp(), GUIGlChildWindow::getParent(), GUISUMOViewParent::init(), onCmdClose(), GUISUMOViewParent::onCmdLocate(), ~GNEViewParent(), and GUISUMOViewParent::~GUISUMOViewParent().
myView
GUISUMOAbstractView* GUIGlChildWindow::myView protected inherited
the view
Definition at line 99 of file GUIGlChildWindow.h.
Referenced by GUIGlChildWindow::create(), GUIGlChildWindow::getBuildGLCanvas(), GUIGlChildWindow::getView(), GUISUMOViewParent::init(), GUIGlChildWindow::onCmdChangeColorScheme(), GUIGlChildWindow::onCmdEditViewport(), GUIGlChildWindow::onCmdEditViewScheme(), onCmdLocate(), GUISUMOViewParent::onCmdMakeSnapshot(), onCmdMakeSnapshot(), GUIGlChildWindow::onCmdRecenterView(), GUIGlChildWindow::onCmdShowToolTips(), GUIGlChildWindow::onCmdZoomStyle(), GUISUMOViewParent::onKeyPress(), onKeyPress(), GUISUMOViewParent::onKeyRelease(), onKeyRelease(), GUISUMOViewParent::onSimStep(), and GUIGlChildWindow::setView().
myViewArea
FXHorizontalFrame* GNEViewParent::myViewArea private
frame to hold myView and myAttributePanel
Definition at line 175 of file GNEViewParent.h.
The documentation for this class was generated from the following files:
GNEViewParent.h
GNEViewParent.cpp