SUMO - Simulation of Urban MObility: NBNodeShapeComputer Class Reference
NBNodeShapeComputer Class Reference
This class computes shapes of junctions.
#include <NBNodeShapeComputer.h>
Public Member Functions
PositionVector compute ()
Computes the shape of the assigned junction.
NBNodeShapeComputer (const NBNode &node)
Constructor.
~NBNodeShapeComputer ()
Destructor.
Private Types
typedef std::map< NBEdge *, PositionVector > GeomsMap
Private Member Functions
bool badIntersection (const NBEdge *e1, const NBEdge *e2, const PositionVector &e1cw, const PositionVector &e2ccw, double distance)
double closestIntersection (const PositionVector &geom1, const PositionVector &geom2, double offset)
return the intersection point closest to the given offset
PositionVector computeNodeShapeDefault (bool simpleContinuation)
Computes the node geometry Edges with the same direction are grouped. Then the node geometry is built from intersection between the borders of adjacent edge groups.
PositionVector computeNodeShapeSmall ()
Computes the node geometry using normals.
EdgeVector computeUniqueDirectionList (std::map< NBEdge *, std::set< NBEdge *> > &same, GeomsMap &geomsCCW, GeomsMap &geomsCW)
Joins edges and computes ccw/cw boundaries.
PositionVector getSmoothCorner (PositionVector begShape, PositionVector endShape, const Position &begPoint, const Position &endPoint, int cornerDetail)
Compute smoothed corner shape.
void joinSameDirectionEdges (std::map< NBEdge *, std::set< NBEdge *> > &same, GeomsMap &geomsCCW, GeomsMap &geomsCW)
Joins edges and computes ccw/cw boundaries.
NBNodeShapeComputer & operator= (const NBNodeShapeComputer &s)
Invalidated assignment operator.
Static Private Member Functions
static void initNeighbors (const EdgeVector &edges, const EdgeVector::const_iterator &current, GeomsMap &geomsCW, GeomsMap &geomsCCW, EdgeVector::const_iterator &cwi, EdgeVector::const_iterator &ccwi, double &cad, double &ccad)
Initialize neighbors and angles.
Private Attributes
const NBNode & myNode
The node to compute the geometry for.
Detailed Description
This class computes shapes of junctions.
Definition at line 51 of file NBNodeShapeComputer.h.
Member Typedef Documentation
GeomsMap
typedef std::map<NBEdge*, PositionVector> NBNodeShapeComputer::GeomsMap private
Definition at line 63 of file NBNodeShapeComputer.h.
Constructor & Destructor Documentation
NBNodeShapeComputer()
NBNodeShapeComputer::NBNodeShapeComputer (const NBNode & node)
Constructor.
Definition at line 51 of file NBNodeShapeComputer.cpp.
~NBNodeShapeComputer()
NBNodeShapeComputer::~NBNodeShapeComputer ()
Destructor.
Definition at line 55 of file NBNodeShapeComputer.cpp.
Member Function Documentation
badIntersection()
bool NBNodeShapeComputer::badIntersection (const NBEdge * e1, const NBEdge * e2, const PositionVector & e1cw, const PositionVector & e2ccw, double distance) private
Returns
whether trying to intersect these edges would probably fail
Definition at line 591 of file NBNodeShapeComputer.cpp.
References PositionVector::distances(), NBEdge::getGeometry(), NBEdge::getLaneSpreadFunction(), PositionVector::getSubpart2D(), NBEdge::getToNode(), NBEdge::getTotalWidth(), PositionVector::intersects(), LANESPREAD_RIGHT, PositionVector::length(), VectorHelper< T >::maxValue(), MIN3(), VectorHelper< T >::minValue(), PositionVector::move2side(), myNode, POSITION_EPS, and PositionVector::reverse().
Referenced by joinSameDirectionEdges().
closestIntersection()
double NBNodeShapeComputer::closestIntersection (const PositionVector & geom1, const PositionVector & geom2, double offset) private
return the intersection point closest to the given offset
Definition at line 458 of file NBNodeShapeComputer.cpp.
References PositionVector::intersectsAtLengths2D().
Referenced by computeNodeShapeDefault().
compute()
PositionVector NBNodeShapeComputer::compute ()
Computes the shape of the assigned junction.
Definition at line 59 of file NBNodeShapeComputer.cpp.
References computeNodeShapeDefault(), computeNodeShapeSmall(), NBNode::getIncomingEdges(), GeomHelper::getMinAngleDiff(), NBNode::getOutgoingEdges(), NBNode::isSimpleContinuation(), MAX2(), NBNode::myAllEdges, and myNode.
Referenced by NBNode::computeNodeShape().
computeNodeShapeDefault()
PositionVector NBNodeShapeComputer::computeNodeShapeDefault (bool simpleContinuation) private
Computes the node geometry Edges with the same direction are grouped. Then the node geometry is built from intersection between the borders of adjacent edge groups.
Definition at line 134 of file NBNodeShapeComputer.cpp.
References Position::add(), PositionVector::append(), closestIntersection(), computeUniqueDirectionList(), DEBUGCOND, DEG2RAD, OptionsCont::exists(), OptionsCont::getBool(), NBNode::getDisplacementError(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), OptionsCont::getOptions(), NBNode::getPosition(), NBNode::getRadius(), getSmoothCorner(), NBNode::hasIncoming(), initNeighbors(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), OptionsCont::isSet(), joinSameDirectionEdges(), PositionVector::length2D(), MAX2(), Position::mul(), NBNode::myAllEdges, myNode, NUMERICAL_EPS, PositionVector::positionAtOffset2D(), PositionVector::push_back_noDoublePos(), PositionVector::push_front_noDoublePos(), RAD2DEG, NBHelpers::relAngle(), Position::setz(), SUMO_const_laneWidth, NBNode::UNSPECIFIED_RADIUS, WRITE_WARNING, and Position::z().
Referenced by compute().
computeNodeShapeSmall()
PositionVector NBNodeShapeComputer::computeNodeShapeSmall () private
Computes the node geometry using normals.
In the case the other method does not work, this method computes the geometry of a node by adding points to the polygon which are computed by building the normals of participating edges' geometry boundaries (cw/ccw) at the node's height (the length of the edge the edge would cross the node point).
Note
This usually gives a very small node shape, appropriate for dead-ends or turn-around-only situations
Definition at line 703 of file NBNodeShapeComputer.cpp.
References DEBUGCOND, PositionVector::extrapolate2D(), Named::getID(), NBNode::getPosition(), PositionVector::getSubpartByIndex(), NBNode::myAllEdges, myNode, PositionVector::push_back_noDoublePos(), Position::set(), Position::x(), Position::y(), and Position::z().
Referenced by compute().
computeUniqueDirectionList()
EdgeVector NBNodeShapeComputer::computeUniqueDirectionList (std::map< NBEdge *, std::set< NBEdge *> > & same, GeomsMap & geomsCCW, GeomsMap & geomsCW) private
Joins edges and computes ccw/cw boundaries.
This methods joins edges which are in marked as being "same" in the means as given by joinSameDirectionEdges. The result (list of so-to-say "directions" is returned; additionally, the boundaries of these directions are stored in ccwBoundary/cwBoundary.
Definition at line 627 of file NBNodeShapeComputer.cpp.
References computeSameEnd(), NBNode::hasIncoming(), NBNode::myAllEdges, and myNode.
Referenced by computeNodeShapeDefault().
getSmoothCorner()
PositionVector NBNodeShapeComputer::getSmoothCorner (PositionVector begShape, PositionVector endShape, const Position & begPoint, const Position & endPoint, int cornerDetail) private
Compute smoothed corner shape.
Parameters
[in] begShape
[in] endShape
[in] begPoint
[in] endPoint
[in] cornerDetail
Returns
shape to be appended between begPoint and endPoint
Definition at line 471 of file NBNodeShapeComputer.cpp.
References NBNode::computeSmoothShape(), myNode, and PositionVector::reverse().
Referenced by computeNodeShapeDefault().
initNeighbors()
void NBNodeShapeComputer::initNeighbors (const EdgeVector & edges, const EdgeVector::const_iterator & current, GeomsMap & geomsCW, GeomsMap & geomsCCW, EdgeVector::const_iterator & cwi, EdgeVector::const_iterator & ccwi, double & cad, double & ccad) static private
Initialize neighbors and angles.
Parameters
[in] edges The list of edges sorted in clockwise direction
[in] current An iterator to the current edge
[in] geomsCW geometry map
[in] geomsCCW geometry map
[out] cwi An iterator to the clockwise neighbor
[out] ccwi An iterator to the counter-clockwise neighbor
[out] cad The angle difference to the clockwise neighbor
[out] ccad The angle difference to the counter-clockwise neighbor
Definition at line 666 of file NBNodeShapeComputer.cpp.
References M_PI.
Referenced by computeNodeShapeDefault().
joinSameDirectionEdges()
void NBNodeShapeComputer::joinSameDirectionEdges (std::map< NBEdge *, std::set< NBEdge *> > & same, GeomsMap & geomsCCW, GeomsMap & geomsCW) private
Joins edges and computes ccw/cw boundaries.
This method goes through all edges and stores each edge's ccw and cw boundary in geomsCCW/geomsCW. This boundary is extrapolated by 100m at the node's position. In addition, "same" is filled so that this map contains a list of all edges within the value-vector which direction at the node differs less than 1 from the key-edge's direction.
Definition at line 489 of file NBNodeShapeComputer.cpp.
References PositionVector::angleAt2D(), GeomHelper::angleDiff(), badIntersection(), DEBUGCOND, DEG2RAD, NBNode::hasIncoming(), NBNode::myAllEdges, myNode, and WRITE_WARNING.
Referenced by computeNodeShapeDefault().
operator=()
NBNodeShapeComputer& NBNodeShapeComputer::operator= (const NBNodeShapeComputer & s) private
Invalidated assignment operator.
Field Documentation
myNode
const NBNode& NBNodeShapeComputer::myNode private
The node to compute the geometry for.
Definition at line 149 of file NBNodeShapeComputer.h.
Referenced by badIntersection(), compute(), computeNodeShapeDefault(), computeNodeShapeSmall(), computeUniqueDirectionList(), getSmoothCorner(), and joinSameDirectionEdges().
The documentation for this class was generated from the following files:
NBNodeShapeComputer.h
NBNodeShapeComputer.cpp