SUMO - Simulation of Urban MObility: GNEAdditionalFrame Class Reference
GNEAdditionalFrame Class Reference
#include <GNEAdditionalFrame.h>
Data Structures
class AdditionalAttributeList
class AdditionalAttributes
class AdditionalAttributeSingle
class NeteditAttributes
class SelectorParentAdditional
class SelectorParentEdges
class SelectorParentLanes
Public Types
enum AddAdditionalResult { ADDADDITIONAL_INVALID_ARGUMENTS, ADDADDITIONAL_INVALID_PARENT, ADDADDITIONAL_SUCCESS }
FOX-declaration.
Public Member Functions
AddAdditionalResult addAdditional (GNENetElement *netElement, GUISUMOAbstractView *abstractViewParent)
add additional element
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNEAdditionalFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
virtual void hide ()
hide Frame
void removeAdditional (GNEAdditional *additional)
remove an additional element previously added
void setFrameWidth (int newWidth)
set width of GNEFrame
void show ()
show additional frame and update use selected edges/lanes
~GNEAdditionalFrame ()
Destructor.
FOX-callbacks
Called when the user select another additional Type
long onCmdSelectAdditional (FXObject *, FXSelector, void *)
Static Public Member Functions
static std::string getIdsSelected (const FXList *list)
get list of selecte id's in string format
Protected Member Functions
GNEAdditionalFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Member Functions
std::string generateID (GNENetElement *netElement) const
generate a ID for an additiona element
double setEndPosition (double laneLength, double positionOfTheMouseOverLane, double lengthOfAdditional)
obtain the End position values of StoppingPlaces and E2 detector over the lane
void setParametersOfAdditional (SumoXMLTag actualAdditionalType)
set parameters depending of the new additionalType
double setStartPosition (double positionOfTheMouseOverLane, double lengthOfAdditional)
obtain the Start position values of StoppingPlaces and E2 detector over the lane
Private Attributes
SumoXMLTag myActualAdditionalType
actual additional type selected in the match Box
FXComboBox * myAdditionalMatchBox
combo box with the list of additional elements
GNEAdditionalFrame::AdditionalAttributes * myadditionalParameters
additional internal attributes
GNEAdditionalFrame::SelectorParentAdditional * myAdditionalParentSelector
list of additional Set
GNEAdditionalFrame::SelectorParentEdges * myedgeParentsSelector
list of SelectorParentEdges
GNEAdditionalFrame::NeteditAttributes * myEditorParameters
Netedit parameter.
FXGroupBox * myGroupBoxForMyAdditionalMatchBox
groupBox for Match Box of additionals
GNEAdditionalFrame::SelectorParentLanes * mylaneParentsSelector
list of SelectorParentLanes
Detailed Description
The Widget for setting internal attributes of additional elements
Definition at line 48 of file GNEAdditionalFrame.h.
Member Enumeration Documentation
AddAdditionalResult
enum GNEAdditionalFrame::AddAdditionalResult
FOX-declaration.
enum with all possible values after try to create an additional using frame
Enumerator
ADDADDITIONAL_INVALID_ARGUMENTS
ADDADDITIONAL_INVALID_PARENT
ADDADDITIONAL_SUCCESS
Definition at line 55 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame() [1/2]
GNEAdditionalFrame::GNEAdditionalFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Create list for SelectorParentEdges
Create list for SelectorParentLanes
Definition at line 122 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GUIDesignComboBox, GUIDesignComboBoxNCol, GUIDesignGroupBoxFrame, MID_GNE_ADDITIONALFRAME_SELECTADDITIONALTYPE, and toString().
~GNEAdditionalFrame()
GNEAdditionalFrame::~GNEAdditionalFrame ()
Destructor.
Definition at line 164 of file GNEAdditionalFrame.cpp.
References gSelected, and GUISelectedStorage::remove2Update().
GNEAdditionalFrame() [2/2]
GNEAdditionalFrame::GNEAdditionalFrame () inline protected
FOX needs this.
Definition at line 639 of file GNEAdditionalFrame.h.
References generateID(), setEndPosition(), setParametersOfAdditional(), and setStartPosition().
Member Function Documentation
addAdditional()
GNEAdditionalFrame::AddAdditionalResult GNEAdditionalFrame::addAdditional (GNENetElement * netElement, GUISUMOAbstractView * abstractViewParent)
add additional element
Parameters
[in] netElement clicked netElement. if user dind't clicked over a GNENetElement in view, netElement will be NULL
[in] parent AbstractView to obtain the position of the mouse over the lane.
Returns
AddAdditionalStatus with the result of operation
Definition at line 170 of file GNEAdditionalFrame.cpp.
References ADDADDITIONAL_INVALID_ARGUMENTS, ADDADDITIONAL_INVALID_PARENT, ADDADDITIONAL_SUCCESS, GNEAdditionalFrame::AdditionalAttributes::areValuesValid(), GNEAdditionalHandler::buildAdditional(), GNEAttributeCarrier::canBlockMovement(), generateID(), GNEAdditionalFrame::NeteditAttributes::getActualReferencePoint(), GNEAdditionalFrame::AdditionalAttributes::getAttributesAndValues(), GNEAttributeCarrier::getID(), GNEAdditionalFrame::SelectorParentAdditional::getIdSelected(), GNEAdditionalFrame::SelectorParentEdges::getIdsSelected(), GNEAdditionalFrame::SelectorParentLanes::getIdsSelected(), GNEEdge::getLanes(), GNELane::getLaneShapeLength(), GNEAdditionalFrame::NeteditAttributes::getLength(), GNEViewNet::getNet(), GUISUMOAbstractView::getPositionInformation(), GNELane::getShape(), GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_INVALID, GNE_ATTR_BLOCK_MOVEMENT, GNE_ATTR_PARENT, GNEAttributeCarrier::hasAttribute(), GNEAdditionalFrame::NeteditAttributes::isBlockEnabled(), GNEAdditionalFrame::NeteditAttributes::isCurrentLengthValid(), GNEAdditionalFrame::SelectorParentEdges::isUseSelectedEdgesEnable(), GNEAdditionalFrame::SelectorParentLanes::isUseSelectedLanesEnable(), joinToString(), myActualAdditionalType, myadditionalParameters, myAdditionalParentSelector, myedgeParentsSelector, myEditorParameters, mylaneParentsSelector, GNEFrame::myViewNet, PositionVector::nearest_offset_to_point2D(), GNENet::retrieveEdges(), GNENet::retrieveLanes(), setEndPosition(), setStartPosition(), GNEViewNet::setStatusBarText(), GNEAdditionalFrame::AdditionalAttributes::showWarningMessage(), GUISUMOAbstractView::snapToActiveGrid(), SUMO_ATTR_CROSSING, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_END, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_JUNCTION, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_LANE, SUMO_TAG_NOTHING, and toString().
Referenced by GNEViewNet::onLeftBtnPress().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
generateID()
std::string GNEAdditionalFrame::generateID (GNENetElement * netElement) const private
generate a ID for an additiona element
Definition at line 517 of file GNEAdditionalFrame.cpp.
References GNENet::getAdditional(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), GNENet::getNumberOfAdditionals(), myActualAdditionalType, GNEFrame::myViewNet, and toString().
Referenced by addAdditional(), and GNEAdditionalFrame().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getIdsSelected()
std::string GNEAdditionalFrame::getIdsSelected (const FXList * list) static
get list of selecte id's in string format
Definition at line 1346 of file GNEAdditionalFrame.cpp.
Referenced by GNEAdditionalFrame::SelectorParentEdges::getIdsSelected(), and GNEAdditionalFrame::SelectorParentLanes::getIdsSelected().
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
hide()
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), and GNEDeleteFrame::removeAttributeCarrier().
onCmdSelectAdditional()
long GNEAdditionalFrame::onCmdSelectAdditional (FXObject * , FXSelector , void *)
Definition at line 431 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), GNEAttributeCarrier::canBlockMovement(), myActualAdditionalType, myAdditionalMatchBox, myadditionalParameters, myAdditionalParentSelector, myedgeParentsSelector, myEditorParameters, mylaneParentsSelector, setParametersOfAdditional(), SUMO_TAG_NOTHING, and toString().
removeAdditional()
void GNEAdditionalFrame::removeAdditional (GNEAdditional * additional)
remove an additional element previously added
Parameters
[in] additional element to erase
Definition at line 412 of file GNEAdditionalFrame.cpp.
References GNEAdditional::getAdditionalChilds(), GUIGlObject::getGlID(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GNEViewNet::getUndoList(), GLO_ADDITIONAL, gSelected, GUISelectedStorage::isSelected(), GNEFrame::myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), and toString().
Referenced by GNEViewNet::deleteSelectedAdditionals(), and GNEDeleteFrame::removeAttributeCarrier().
setEndPosition()
double GNEAdditionalFrame::setEndPosition (double laneLength, double positionOfTheMouseOverLane, double lengthOfAdditional) private
obtain the End position values of StoppingPlaces and E2 detector over the lane
Definition at line 551 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::NeteditAttributes::getActualReferencePoint(), GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_CENTER, GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_LEFT, GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_RIGHT, and myEditorParameters.
Referenced by addAdditional(), and GNEAdditionalFrame().
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
setParametersOfAdditional()
void GNEAdditionalFrame::setParametersOfAdditional (SumoXMLTag actualAdditionalType) private
set parameters depending of the new additionalType
Definition at line 474 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::AdditionalAttributes::addAttribute(), GNEAttributeCarrier::allowedAttributes(), GNEAdditionalFrame::AdditionalAttributes::clearAttributes(), GNEAdditionalFrame::AdditionalAttributes::getNumberOfAddedAttributes(), GNEAttributeCarrier::hasAttribute(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::NeteditAttributes::hideLengthFieldAndReferecePoint(), GNEAdditionalFrame::SelectorParentEdges::hideList(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAttributeCarrier::isUnique(), myActualAdditionalType, myadditionalParameters, myAdditionalParentSelector, myedgeParentsSelector, myEditorParameters, mylaneParentsSelector, GNEAdditionalFrame::AdditionalAttributes::showAdditionalParameters(), GNEAdditionalFrame::NeteditAttributes::showLengthFieldAndReferecePoint(), GNEAdditionalFrame::SelectorParentEdges::showList(), GNEAdditionalFrame::SelectorParentLanes::showList(), GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals(), SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_LANES, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, and SUMO_TAG_E3DETECTOR.
Referenced by GNEAdditionalFrame(), and onCmdSelectAdditional().
setStartPosition()
double GNEAdditionalFrame::setStartPosition (double positionOfTheMouseOverLane, double lengthOfAdditional) private
obtain the Start position values of StoppingPlaces and E2 detector over the lane
Definition at line 536 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::NeteditAttributes::getActualReferencePoint(), GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_CENTER, GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_LEFT, GNEAdditionalFrame::NeteditAttributes::GNE_ADDITIONALREFERENCEPOINT_RIGHT, and myEditorParameters.
Referenced by addAdditional(), and GNEAdditionalFrame().
show()
void GNEAdditionalFrame::show () virtual
show additional frame and update use selected edges/lanes
Reimplemented from GNEFrame.
Definition at line 463 of file GNEAdditionalFrame.cpp.
References myedgeParentsSelector, mylaneParentsSelector, GNEFrame::show(), GNEAdditionalFrame::SelectorParentEdges::updateUseSelectedEdges(), and GNEAdditionalFrame::SelectorParentLanes::updateUseSelectedLanes().
Referenced by GNEAdditionalFrame::AdditionalAttributes::showAdditionalParameters(), GNEAdditionalFrame::SelectorParentEdges::showList(), GNEAdditionalFrame::SelectorParentLanes::showList(), GNEAdditionalFrame::SelectorParentAdditional::showListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::showParameter(), and GNEViewNet::updateModeSpecificControls().
Field Documentation
myActualAdditionalType
SumoXMLTag GNEAdditionalFrame::myActualAdditionalType private
actual additional type selected in the match Box
Definition at line 676 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), generateID(), onCmdSelectAdditional(), and setParametersOfAdditional().
myAdditionalMatchBox
FXComboBox* GNEAdditionalFrame::myAdditionalMatchBox private
combo box with the list of additional elements
Definition at line 658 of file GNEAdditionalFrame.h.
Referenced by onCmdSelectAdditional().
myadditionalParameters
GNEAdditionalFrame::AdditionalAttributes* GNEAdditionalFrame::myadditionalParameters private
additional internal attributes
Definition at line 661 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), onCmdSelectAdditional(), and setParametersOfAdditional().
myAdditionalParentSelector
GNEAdditionalFrame::SelectorParentAdditional* GNEAdditionalFrame::myAdditionalParentSelector private
list of additional Set
Definition at line 667 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), onCmdSelectAdditional(), and setParametersOfAdditional().
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myedgeParentsSelector
GNEAdditionalFrame::SelectorParentEdges* GNEAdditionalFrame::myedgeParentsSelector private
list of SelectorParentEdges
Definition at line 670 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), onCmdSelectAdditional(), setParametersOfAdditional(), and show().
myEditorParameters
GNEAdditionalFrame::NeteditAttributes* GNEAdditionalFrame::myEditorParameters private
Netedit parameter.
Definition at line 664 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), onCmdSelectAdditional(), setEndPosition(), setParametersOfAdditional(), and setStartPosition().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxForMyAdditionalMatchBox
FXGroupBox* GNEAdditionalFrame::myGroupBoxForMyAdditionalMatchBox private
groupBox for Match Box of additionals
Definition at line 655 of file GNEAdditionalFrame.h.
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
mylaneParentsSelector
GNEAdditionalFrame::SelectorParentLanes* GNEAdditionalFrame::mylaneParentsSelector private
list of SelectorParentLanes
Definition at line 673 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), onCmdSelectAdditional(), setParametersOfAdditional(), and show().
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), GNETLSEditorFrame::buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), GNETLSEditorFrame::editJunction(), generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp