SUMO - Simulation of Urban MObility: FXEX::FXLCDLabel Class Reference
FXEX::FXLCDLabel Class Reference
#include <FXLCDLabel.h>
Public Types
enum { ID_SEVENSEGMENT = FXHorizontalFrame::ID_LAST, ID_LAST }
Public Member Functions
virtual void create ()
create resrouces
virtual void destroy ()
destroy resources
virtual void detach ()
detach resources
FXLCDLabel (FXComposite *p, FXuint nfig=1, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=LCDLABEL_NORMAL, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD, FXint hs=DEFAULT_PAD)
make me a label
FXColor getBgColor () const
virtual FXint getDefaultHeight ()
return minimum height
virtual FXint getDefaultWidth ()
return minimum width
FXColor getFgColor () const
FXint getGroove () const
FXint getHorizontal () const
FXString getText () const
FXint getThickness () const
FXint getVertical () const
virtual void load (FXStream &store)
load resources
long onCmdGetIntValue (FXObject *, FXSelector, void *ptr)
long onCmdGetRealValue (FXObject *, FXSelector, void *ptr)
long onCmdGetStringValue (FXObject *, FXSelector, void *ptr)
long onCmdSetIntValue (FXObject *, FXSelector, void *ptr)
long onCmdSetRealValue (FXObject *, FXSelector, void *ptr)
long onCmdSetStringValue (FXObject *, FXSelector, void *ptr)
long onCmdSetValue (FXObject *, FXSelector, void *ptr)
long onPaint (FXObject *, FXSelector, void *)
long onQueryHelp (FXObject *, FXSelector, void *ptr)
long onQueryTip (FXObject *, FXSelector, void *ptr)
long onRedirectEvent (FXObject *, FXSelector, void *ptr)
virtual void save (FXStream &store) const
save resources
void setBgColor (FXColor clr)
set/get background color
void setFgColor (FXColor clr)
set/get forground color
void setGroove (const FXint width)
set/get groove width - must be less than segment width
void setHorizontal (const FXint len)
set/get segment horizontal length - must be more than twice the segment width
void setText (FXString lbl)
manipulate text in LCD label
void setThickness (const FXint width)
set/get segment width - must be less than half the segment length
void setVertical (const FXint len)
set/get segment vertical length - must be more than twice the segment width
virtual ~FXLCDLabel ()
dtor
Protected Member Functions
virtual void drawString (const FXString &lbl)
The number of shown figuresi, greater than zero.
FXLCDLabel ()
Protected Attributes
FXString label
FXint nfigures
The currently shown label.
Detailed Description
A widget which has the seven-segment display used as the drawing object for each letter in the label. Supports display of leading zeros, such as when you need to display a number. Also supports the 'JUSTIFY_RIGHT' option, for right alignment.
Definition at line 55 of file FXLCDLabel.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_SEVENSEGMENT
ID_LAST
Definition at line 69 of file FXLCDLabel.h.
Constructor & Destructor Documentation
FXLCDLabel() [1/2]
FXEX::FXLCDLabel::FXLCDLabel () inline protected
Definition at line 60 of file FXLCDLabel.h.
FXLCDLabel() [2/2]
FXEX::FXLCDLabel::FXLCDLabel (FXComposite * p, FXuint nfig = 1, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = LCDLABEL_NORMAL, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD, FXint hs = DEFAULT_PAD)
make me a label
Definition at line 74 of file FXLCDLabel.cpp.
~FXLCDLabel()
FXEX::FXLCDLabel::~FXLCDLabel () virtual
dtor
Definition at line 87 of file FXLCDLabel.cpp.
Member Function Documentation
create()
void FXEX::FXLCDLabel::create () virtual
create resrouces
Definition at line 96 of file FXLCDLabel.cpp.
destroy()
void FXEX::FXLCDLabel::destroy () virtual
destroy resources
Definition at line 112 of file FXLCDLabel.cpp.
detach()
void FXEX::FXLCDLabel::detach () virtual
detach resources
Definition at line 104 of file FXLCDLabel.cpp.
drawString()
void FXEX::FXLCDLabel::drawString (const FXString & lbl) protected virtual
The number of shown figuresi, greater than zero.
Definition at line 290 of file FXLCDLabel.cpp.
References FXEX::LCDLABEL_LEADING_ZEROS, FXEX::FXSevenSegment::setGroove(), FXEX::FXSevenSegment::setHorizontal(), FXEX::FXSevenSegment::setText(), FXEX::FXSevenSegment::setThickness(), and FXEX::FXSevenSegment::setVertical().
getBgColor()
FXColor FXEX::FXLCDLabel::getBgColor () const
Definition at line 136 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getBgColor().
getDefaultHeight()
FXint FXEX::FXLCDLabel::getDefaultHeight () virtual
return minimum height
Definition at line 384 of file FXLCDLabel.cpp.
getDefaultWidth()
FXint FXEX::FXLCDLabel::getDefaultWidth () virtual
return minimum width
Definition at line 379 of file FXLCDLabel.cpp.
getFgColor()
FXColor FXEX::FXLCDLabel::getFgColor () const
Definition at line 120 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getFgColor().
getGroove()
FXint FXEX::FXLCDLabel::getGroove () const
Definition at line 215 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getGroove().
getHorizontal()
FXint FXEX::FXLCDLabel::getHorizontal () const
Definition at line 161 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getHorizontal().
getText()
FXString FXEX::FXLCDLabel::getText () const inline
Definition at line 102 of file FXLCDLabel.h.
getThickness()
FXint FXEX::FXLCDLabel::getThickness () const
Definition at line 197 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getThickness().
getVertical()
FXint FXEX::FXLCDLabel::getVertical () const
Definition at line 179 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getVertical().
load()
void FXEX::FXLCDLabel::load (FXStream & store) virtual
load resources
Definition at line 396 of file FXLCDLabel.cpp.
onCmdGetIntValue()
long FXEX::FXLCDLabel::onCmdGetIntValue (FXObject * , FXSelector , void * ptr)
Definition at line 257 of file FXLCDLabel.cpp.
onCmdGetRealValue()
long FXEX::FXLCDLabel::onCmdGetRealValue (FXObject * , FXSelector , void * ptr)
Definition at line 263 of file FXLCDLabel.cpp.
onCmdGetStringValue()
long FXEX::FXLCDLabel::onCmdGetStringValue (FXObject * , FXSelector , void * ptr)
Definition at line 269 of file FXLCDLabel.cpp.
onCmdSetIntValue()
long FXEX::FXLCDLabel::onCmdSetIntValue (FXObject * , FXSelector , void * ptr)
Definition at line 239 of file FXLCDLabel.cpp.
onCmdSetRealValue()
long FXEX::FXLCDLabel::onCmdSetRealValue (FXObject * , FXSelector , void * ptr)
Definition at line 245 of file FXLCDLabel.cpp.
onCmdSetStringValue()
long FXEX::FXLCDLabel::onCmdSetStringValue (FXObject * , FXSelector , void * ptr)
Definition at line 251 of file FXLCDLabel.cpp.
onCmdSetValue()
long FXEX::FXLCDLabel::onCmdSetValue (FXObject * , FXSelector , void * ptr)
Definition at line 233 of file FXLCDLabel.cpp.
onPaint()
long FXEX::FXLCDLabel::onPaint (FXObject * , FXSelector , void * ptr)
Definition at line 275 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getBgColor(), and FXEX::FXSevenSegment::getFgColor().
onQueryHelp()
long FXEX::FXLCDLabel::onQueryHelp (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 411 of file FXLCDLabel.cpp.
onQueryTip()
long FXEX::FXLCDLabel::onQueryTip (FXObject * sender, FXSelector sel, void * ptr)
Definition at line 403 of file FXLCDLabel.cpp.
onRedirectEvent()
long FXEX::FXLCDLabel::onRedirectEvent (FXObject * , FXSelector sel, void * ptr)
Definition at line 368 of file FXLCDLabel.cpp.
save()
void FXEX::FXLCDLabel::save (FXStream & store) const virtual
save resources
Definition at line 389 of file FXLCDLabel.cpp.
setBgColor()
void FXEX::FXLCDLabel::setBgColor (FXColor clr)
set/get background color
Definition at line 142 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getBgColor(), and FXEX::FXSevenSegment::setBgColor().
setFgColor()
void FXEX::FXLCDLabel::setFgColor (FXColor clr)
set/get forground color
Definition at line 126 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getFgColor(), and FXEX::FXSevenSegment::setFgColor().
Referenced by GUIApplicationWindow::onCmdGaming().
setGroove()
void FXEX::FXLCDLabel::setGroove (const FXint width)
set/get groove width - must be less than segment width
Definition at line 221 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getGroove(), and FXEX::FXSevenSegment::setGroove().
Referenced by GUIApplicationWindow::buildToolBars().
setHorizontal()
void FXEX::FXLCDLabel::setHorizontal (const FXint len)
set/get segment horizontal length - must be more than twice the segment width
Definition at line 167 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getHorizontal(), and FXEX::FXSevenSegment::setHorizontal().
Referenced by GUIApplicationWindow::buildToolBars().
setText()
void FXEX::FXLCDLabel::setText (FXString lbl)
manipulate text in LCD label
Definition at line 152 of file FXLCDLabel.cpp.
Referenced by GUIApplicationWindow::buildToolBars(), GUIApplicationWindow::checkGamingEvents(), GUIApplicationWindow::closeAllWindows(), GUIApplicationWindow::handleEvent_SimulationLoaded(), and GUIApplicationWindow::updateTimeLCD().
setThickness()
void FXEX::FXLCDLabel::setThickness (const FXint width)
set/get segment width - must be less than half the segment length
Definition at line 203 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getThickness(), and FXEX::FXSevenSegment::setThickness().
Referenced by GUIApplicationWindow::buildToolBars().
setVertical()
void FXEX::FXLCDLabel::setVertical (const FXint len)
set/get segment vertical length - must be more than twice the segment width
Definition at line 185 of file FXLCDLabel.cpp.
References FXEX::FXSevenSegment::getVertical(), and FXEX::FXSevenSegment::setVertical().
Referenced by GUIApplicationWindow::buildToolBars().
Field Documentation
label
FXString FXEX::FXLCDLabel::label protected
Definition at line 62 of file FXLCDLabel.h.
nfigures
FXint FXEX::FXLCDLabel::nfigures protected
The currently shown label.
Definition at line 63 of file FXLCDLabel.h.
The documentation for this class was generated from the following files:
FXLCDLabel.h
FXLCDLabel.cpp