SUMO - Simulation of Urban MObility: Command_SaveTLSSwitches Class Reference
Command_SaveTLSSwitches Class Reference
Writes information about the green durations of a tls.
#include <Command_SaveTLSSwitches.h>
Public Member Functions
Command_SaveTLSSwitches (const MSTLLogicControl::TLSLogicVariants &logics, OutputDevice &od)
Constructor.
~Command_SaveTLSSwitches ()
Destructor.
Derived from Command
SUMOTime execute (SUMOTime currentTime)
Writes the output if a change occured.
Private Member Functions
Command_SaveTLSSwitches (const Command_SaveTLSSwitches &)
Invalidated copy constructor.
Command_SaveTLSSwitches & operator= (const Command_SaveTLSSwitches &)
Invalidated assignment operator.
Private Attributes
const MSTLLogicControl::TLSLogicVariants & myLogics
The traffic light logic to use.
OutputDevice & myOutputDevice
The device to write to.
std::map< int, SUMOTime > myPreviousLinkStates
Storage for prior states; map from signal group to last green time begin.
Detailed Description
Writes information about the green durations of a tls.
Todo:
Revalidate this - as tls are not seting the link information directly ater being switched, the computed information may be delayed
Definition at line 55 of file Command_SaveTLSSwitches.h.
Constructor & Destructor Documentation
Command_SaveTLSSwitches() [1/2]
Command_SaveTLSSwitches::Command_SaveTLSSwitches (const MSTLLogicControl::TLSLogicVariants & logics, OutputDevice & od)
Constructor.
Parameters
[in] tlls The logic to write state of
[in] od The output device to write the state into
Definition at line 44 of file Command_SaveTLSSwitches.cpp.
References MSEventControl::addEvent(), MSNet::getEndOfTimestepEvents(), MSNet::getInstance(), myOutputDevice, and OutputDevice::writeXMLHeader().
~Command_SaveTLSSwitches()
Command_SaveTLSSwitches::~Command_SaveTLSSwitches ()
Destructor.
Definition at line 52 of file Command_SaveTLSSwitches.cpp.
Command_SaveTLSSwitches() [2/2]
Command_SaveTLSSwitches::Command_SaveTLSSwitches (const Command_SaveTLSSwitches &) private
Invalidated copy constructor.
Member Function Documentation
execute()
SUMOTime Command_SaveTLSSwitches::execute (SUMOTime currentTime) virtual
Writes the output if a change occured.
Called in each tme step, this class computes which link have red since the last tls switch and writes the information about their green duration into the given stream.
Information whether a link had green and since when is stored in "myPreviousLinkStates".
Parameters
[in] currentTime The current simulation time
Returns
Always DELTA_T (will be executed in next time step)
See also
Command
Implements Command.
Definition at line 57 of file Command_SaveTLSSwitches.cpp.
References DELTA_T, MSTLLogicControl::TLSLogicVariants::getActive(), MSTrafficLightLogic::getCurrentPhaseDef(), Named::getID(), MSLink::getLane(), MSTrafficLightLogic::getLanesAt(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getProgramID(), MSPhaseDefinition::getState(), LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, myLogics, myOutputDevice, myPreviousLinkStates, and time2string().
operator=()
Command_SaveTLSSwitches& Command_SaveTLSSwitches::operator= (const Command_SaveTLSSwitches &) private
Invalidated assignment operator.
Field Documentation
myLogics
const MSTLLogicControl::TLSLogicVariants& Command_SaveTLSSwitches::myLogics private
The traffic light logic to use.
Definition at line 95 of file Command_SaveTLSSwitches.h.
Referenced by execute().
myOutputDevice
OutputDevice& Command_SaveTLSSwitches::myOutputDevice private
The device to write to.
Definition at line 92 of file Command_SaveTLSSwitches.h.
Referenced by Command_SaveTLSSwitches(), and execute().
myPreviousLinkStates
std::map<int, SUMOTime> Command_SaveTLSSwitches::myPreviousLinkStates private
Storage for prior states; map from signal group to last green time begin.
Definition at line 98 of file Command_SaveTLSSwitches.h.
Referenced by execute().
The documentation for this class was generated from the following files:
Command_SaveTLSSwitches.h
Command_SaveTLSSwitches.cpp