SUMO - Simulation of Urban MObility: GNETLSEditorFrame::TLSAttributes Class Reference
GNETLSEditorFrame::TLSAttributes Class Reference
FOX-declaration.
#include <GNETLSEditorFrame.h>
Public Member Functions
void clearTLSAttributes ()
clear TLS attributes
NBTrafficLightDefinition * getCurrentTLSDefinition () const
get current definition
int getNumberOfPrograms () const
get number of programs
int getNumberOfTLSDefinitions () const
get number of definitions
SUMOTime getOffset () const
get current offset in SUMOTIme
void initTLSAttributes (GNEJunction *junction)
initializes the definitions and corresponding listbox
void setOffset (SUMOTime offset)
set new offset
TLSAttributes (FXComposite *parent, GNETLSEditorFrame *TLSEditorParent)
constructor
~TLSAttributes ()
destructor
Private Attributes
FXMatrix * myAttributeMatrix
matrix for attributes
FXLabel * myNameLabel
name label
FXTextField * myNameTextField
name text field
FXLabel * myOffsetLabel
offset label
FXTextField * myOffsetTextField
the control for modifying offset
FXComboBox * myProgramComboBox
the comboBox for selecting the tl-definition to edit
FXLabel * myProgramLabel
program label
std::vector< NBTrafficLightDefinition * > myTLSDefinitions
the list of Definitions for the current junction
GNETLSEditorFrame * myTLSEditorParent
pointer to TLSEditorParent
Detailed Description
FOX-declaration.
Definition at line 59 of file GNETLSEditorFrame.h.
Constructor & Destructor Documentation
TLSAttributes()
GNETLSEditorFrame::TLSAttributes::TLSAttributes (FXComposite * parent, GNETLSEditorFrame * TLSEditorParent)
constructor
Definition at line 697 of file GNETLSEditorFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignComboBoxAttribute, GUIDesignComboBoxNCol, GUIDesignLabelAttribute, GUIDesignTextField, GUIDesignTextFieldNCol, GUIDesignTextFieldReal, MID_GNE_TLSFRAME_OFFSET, MID_GNE_TLSFRAME_SWITCH, myNameLabel, myNameTextField, myOffsetLabel, myOffsetTextField, myProgramComboBox, myProgramLabel, and myTLSEditorParent.
~TLSAttributes()
GNETLSEditorFrame::TLSAttributes::~TLSAttributes ()
destructor
Definition at line 721 of file GNETLSEditorFrame.cpp.
Member Function Documentation
clearTLSAttributes()
void GNETLSEditorFrame::TLSAttributes::clearTLSAttributes ()
clear TLS attributes
Definition at line 749 of file GNETLSEditorFrame.cpp.
References myNameTextField, myOffsetTextField, myProgramComboBox, and myTLSDefinitions.
Referenced by GNETLSEditorFrame::cleanup().
getCurrentTLSDefinition()
NBTrafficLightDefinition * GNETLSEditorFrame::TLSAttributes::getCurrentTLSDefinition () const
get current definition
Definition at line 765 of file GNETLSEditorFrame.cpp.
References myProgramComboBox, and myTLSDefinitions.
Referenced by GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), and GNETLSEditorFrame::onCmdOK().
getNumberOfPrograms()
int GNETLSEditorFrame::TLSAttributes::getNumberOfPrograms () const
get number of programs
Definition at line 777 of file GNETLSEditorFrame.cpp.
References myProgramComboBox.
Referenced by GNETLSEditorFrame::onCmdDefSwitch().
getNumberOfTLSDefinitions()
int GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions () const
get number of definitions
Definition at line 771 of file GNETLSEditorFrame.cpp.
References myTLSDefinitions.
Referenced by GNETLSEditorFrame::initPhaseTable(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNETLSEditorFrame::onUpdDefSwitch(), GNETLSEditorFrame::onUpdNeedsDef(), and GNETLSEditorFrame::onUpdNeedsDefAndPhase().
getOffset()
SUMOTime GNETLSEditorFrame::TLSAttributes::getOffset () const
get current offset in SUMOTIme
Definition at line 783 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::getSUMOTime(), and myOffsetTextField.
Referenced by GNETLSEditorFrame::onCmdDefOffset().
initTLSAttributes()
void GNETLSEditorFrame::TLSAttributes::initTLSAttributes (GNEJunction * junction)
initializes the definitions and corresponding listbox
Definition at line 725 of file GNETLSEditorFrame.cpp.
References NBNode::getControllingTLS(), GNEJunction::getNBNode(), myNameTextField, myOffsetTextField, myProgramComboBox, myTLSDefinitions, myTLSEditorParent, and GNETLSEditorFrame::onCmdDefSwitch().
Referenced by GNETLSEditorFrame::editJunction().
setOffset()
void GNETLSEditorFrame::TLSAttributes::setOffset (SUMOTime offset)
set new offset
Definition at line 789 of file GNETLSEditorFrame.cpp.
References myOffsetTextField, STEPS2TIME, and toString().
Referenced by GNETLSEditorFrame::onCmdDefSwitch().
Field Documentation
myAttributeMatrix
FXMatrix* GNETLSEditorFrame::TLSAttributes::myAttributeMatrix private
matrix for attributes
Definition at line 97 of file GNETLSEditorFrame.h.
myNameLabel
FXLabel* GNETLSEditorFrame::TLSAttributes::myNameLabel private
name label
Definition at line 100 of file GNETLSEditorFrame.h.
Referenced by TLSAttributes().
myNameTextField
FXTextField* GNETLSEditorFrame::TLSAttributes::myNameTextField private
name text field
Definition at line 103 of file GNETLSEditorFrame.h.
Referenced by clearTLSAttributes(), initTLSAttributes(), and TLSAttributes().
myOffsetLabel
FXLabel* GNETLSEditorFrame::TLSAttributes::myOffsetLabel private
offset label
Definition at line 112 of file GNETLSEditorFrame.h.
Referenced by TLSAttributes().
myOffsetTextField
FXTextField* GNETLSEditorFrame::TLSAttributes::myOffsetTextField private
the control for modifying offset
Definition at line 115 of file GNETLSEditorFrame.h.
Referenced by clearTLSAttributes(), getOffset(), initTLSAttributes(), setOffset(), and TLSAttributes().
myProgramComboBox
FXComboBox* GNETLSEditorFrame::TLSAttributes::myProgramComboBox private
the comboBox for selecting the tl-definition to edit
Definition at line 109 of file GNETLSEditorFrame.h.
Referenced by clearTLSAttributes(), getCurrentTLSDefinition(), getNumberOfPrograms(), initTLSAttributes(), and TLSAttributes().
myProgramLabel
FXLabel* GNETLSEditorFrame::TLSAttributes::myProgramLabel private
program label
Definition at line 106 of file GNETLSEditorFrame.h.
Referenced by TLSAttributes().
myTLSDefinitions
std::vector<NBTrafficLightDefinition*> GNETLSEditorFrame::TLSAttributes::myTLSDefinitions private
the list of Definitions for the current junction
Definition at line 94 of file GNETLSEditorFrame.h.
Referenced by clearTLSAttributes(), getCurrentTLSDefinition(), getNumberOfTLSDefinitions(), and initTLSAttributes().
myTLSEditorParent
GNETLSEditorFrame* GNETLSEditorFrame::TLSAttributes::myTLSEditorParent private
pointer to TLSEditorParent
Definition at line 91 of file GNETLSEditorFrame.h.
Referenced by initTLSAttributes(), and TLSAttributes().
The documentation for this class was generated from the following files:
GNETLSEditorFrame.h
GNETLSEditorFrame.cpp