SUMO - Simulation of Urban MObility: DijkstraRouter< E, V, PF > Class Template Reference
DijkstraRouter< E, V, PF > Class Template Reference
Computes the shortest path through a network using the Dijkstra algorithm.
#include <DijkstraRouter.h>
Data Structures
class EdgeInfo
class EdgeInfoByEffortComparator
Public Types
typedef double(* Operation) (const E *const, const V *const, double)
Public Member Functions
void buildPathFrom (const EdgeInfo *rbegin, std::vector< const E *> &edges)
Builds the path from marked edges.
virtual SUMOAbstractRouter< E, V > * clone ()
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
DijkstraRouter (const std::vector< E *> &edges, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation=nullptr)
Constructor.
void endQuery (int visits)
const EdgeInfo & getEdgeInfo (int index) const
double getEffort (const E *const e, const V *const v, double t) const
double getTravelTime (const E *const e, const V *const v, const double t, const double effort) const
void init ()
double recomputeCosts (const std::vector< const E *> &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~DijkstraRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Member Functions
DijkstraRouter (const std::vector< EdgeInfo > &edgeInfos, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation)
Private Attributes
EdgeInfoByEffortComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Operation myTTOperation
The object's operation to perform for travel times.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouter< E, V, PF >
Computes the shortest path through a network using the Dijkstra algorithm.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
EC The class to retrieve the effort for an edge from
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 69 of file DijkstraRouter.h.
Member Typedef Documentation
Operation
template<class E, class V, class PF> typedef double(* DijkstraRouter< E, V, PF >::Operation) (const E *const, const V *const, double)
Definition at line 72 of file DijkstraRouter.h.
Constructor & Destructor Documentation
DijkstraRouter() [1/2]
template<class E, class V, class PF> DijkstraRouter< E, V, PF >::DijkstraRouter (const std::vector< E *> & edges, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation = nullptr) inline
Constructor.
Definition at line 128 of file DijkstraRouter.h.
~DijkstraRouter()
template<class E, class V, class PF> virtual DijkstraRouter< E, V, PF >::~DijkstraRouter () inline virtual
Destructor.
Definition at line 137 of file DijkstraRouter.h.
DijkstraRouter() [2/2]
template<class E, class V, class PF> DijkstraRouter< E, V, PF >::DijkstraRouter (const std::vector< EdgeInfo > & edgeInfos, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation) inline private
Definition at line 290 of file DijkstraRouter.h.
Member Function Documentation
buildPathFrom()
template<class E, class V, class PF> void DijkstraRouter< E, V, PF >::buildPathFrom (const EdgeInfo * rbegin, std::vector< const E *> & edges) inline
Builds the path from marked edges.
Definition at line 276 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute().
clone()
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* DijkstraRouter< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 139 of file DijkstraRouter.h.
compute()
template<class E, class V, class PF> virtual bool DijkstraRouter< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E *> & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 162 of file DijkstraRouter.h.
endQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 95 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
getEdgeInfo()
template<class E, class V, class PF> const EdgeInfo& DijkstraRouter< E, V, PF >::getEdgeInfo (int index) const inline
Definition at line 285 of file DijkstraRouter.h.
getEffort()
template<class E, class V> double SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, double t) const inline inherited
Definition at line 86 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHBuilder< E, V >::synchronize().
getTravelTime()
template<class E, class V, class PF> double DijkstraRouter< E, V, PF >::getTravelTime (const E *const e, const V *const v, const double t, const double effort) const inline
Definition at line 143 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::recomputeCosts().
init()
template<class E, class V, class PF> void DijkstraRouter< E, V, PF >::init () inline
Definition at line 147 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute().
recomputeCosts()
template<class E, class V, class PF> double DijkstraRouter< E, V, PF >::recomputeCosts (const std::vector< const E *> & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 261 of file DijkstraRouter.h.
setBulkMode()
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 100 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
startQuery()
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 90 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
myBulkMode
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 109 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
myComparator
template<class E, class V, class PF> EdgeInfoByEffortComparator DijkstraRouter< E, V, PF >::myComparator private
Definition at line 310 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute().
myEdgeInfos
template<class E, class V, class PF> std::vector<EdgeInfo> DijkstraRouter< E, V, PF >::myEdgeInfos private
The container of edge information.
Definition at line 303 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::DijkstraRouter(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::getEdgeInfo().
myErrorMsgHandler
template<class E, class V, class PF> MsgHandler* const DijkstraRouter< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 313 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute().
myFound
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouter< E, V, PF >::myFound private
list of visited Edges (for resetting)
Definition at line 308 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::init().
myFrontierList
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouter< E, V, PF >::myFrontierList private
A container for reusage of the min edge heap.
Definition at line 306 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::compute(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::init().
myOperation
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 106 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
myTTOperation
template<class E, class V, class PF> Operation DijkstraRouter< E, V, PF >::myTTOperation private
The object's operation to perform for travel times.
Definition at line 300 of file DijkstraRouter.h.
Referenced by DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::clone(), and DijkstraRouter< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >::getTravelTime().
The documentation for this class was generated from the following file:
DijkstraRouter.h