SUMO - Simulation of Urban MObility: GNEFrame::DrawingMode Class Reference
GNEFrame::DrawingMode Class Reference
#include <GNEFrame.h>
Public Member Functions
void abortDrawing ()
abort drawing
void addNewPoint (const Position &P)
add new point to temporal shape
DrawingMode (GNEFrame *frameParent)
FOX-declaration.
const PositionVector & getTemporalShape () const
get Temporal shape
void hideDrawingMode ()
hide Drawing mode
bool isDrawing () const
return true if currently a shape is drawed
void removeLastPoint ()
remove last added point
void showDrawingMode ()
show Drawing mode
void startDrawing ()
start drawing
void stopDrawing ()
stop drawing and create polygon or
~DrawingMode ()
destructor
FOX-callbacks
Called when the user press start drawing button
long onCmdStartDrawing (FXObject *, FXSelector, void *)
long onCmdStopDrawing (FXObject *, FXSelector, void *)
Called when the user press stop drawing button.
long onCmdAbortDrawing (FXObject *, FXSelector, void *)
Called when the user press abort drawing button.
Protected Member Functions
DrawingMode ()
FOX needs this.
Private Attributes
FXButton * myAbortDrawingButton
button for abort drawing
GNEFrame * myFrameParent
frame frame parent
FXLabel * myInformationLabel
Label with information.
FXButton * myStartDrawingButton
button for start drawing
FXButton * myStopDrawingButton
button for stop drawing
PositionVector myTemporalShapeShape
current drawed shape
Detailed Description
Definition at line 213 of file GNEFrame.h.
Constructor & Destructor Documentation
DrawingMode() [1/2]
GNEFrame::DrawingMode::DrawingMode (GNEFrame * frameParent)
FOX-declaration.
constructor
Definition at line 342 of file GNEFrame.cpp.
References GUIDesignButton, GUIDesignLabelFrameInformation, MID_GNE_POLYGONFRAME_ABORTDRAWING, MID_GNE_POLYGONFRAME_STARTDRAWING, MID_GNE_POLYGONFRAME_STOPDRAWING, myAbortDrawingButton, myInformationLabel, myStartDrawingButton, and myStopDrawingButton.
~DrawingMode()
GNEFrame::DrawingMode::~DrawingMode ()
destructor
Definition at line 366 of file GNEFrame.cpp.
DrawingMode() [2/2]
GNEFrame::DrawingMode::DrawingMode () inline protected
FOX needs this.
Definition at line 265 of file GNEFrame.h.
Member Function Documentation
abortDrawing()
void GNEFrame::DrawingMode::abortDrawing ()
abort drawing
Definition at line 424 of file GNEFrame.cpp.
References GNEFrame::getViewNet(), myAbortDrawingButton, myFrameParent, myStartDrawingButton, myStopDrawingButton, and myTemporalShapeShape.
Referenced by GNEViewNet::abortOperation(), hideDrawingMode(), onCmdAbortDrawing(), showDrawingMode(), and stopDrawing().
addNewPoint()
void GNEFrame::DrawingMode::addNewPoint (const Position & P)
add new point to temporal shape
Definition at line 436 of file GNEFrame.cpp.
References myStopDrawingButton, and myTemporalShapeShape.
Referenced by GNEPolygonFrame::processClick().
getTemporalShape()
const PositionVector & GNEFrame::DrawingMode::getTemporalShape () const
get Temporal shape
Definition at line 458 of file GNEFrame.cpp.
References myTemporalShapeShape.
Referenced by GNEViewNet::doPaintGL().
hideDrawingMode()
void GNEFrame::DrawingMode::hideDrawingMode ()
hide Drawing mode
Definition at line 377 of file GNEFrame.cpp.
References abortDrawing().
Referenced by GNEPolygonFrame::onCmdSelectShape().
isDrawing()
bool GNEFrame::DrawingMode::isDrawing () const
return true if currently a shape is drawed
Definition at line 464 of file GNEFrame.cpp.
References myStopDrawingButton.
Referenced by GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), GNEViewNet::onRightBtnRelease(), and GNEPolygonFrame::processClick().
onCmdAbortDrawing()
long GNEFrame::DrawingMode::onCmdAbortDrawing (FXObject * , FXSelector , void *)
Called when the user press abort drawing button.
Definition at line 484 of file GNEFrame.cpp.
References abortDrawing().
onCmdStartDrawing()
long GNEFrame::DrawingMode::onCmdStartDrawing (FXObject * , FXSelector , void *)
Definition at line 470 of file GNEFrame.cpp.
References startDrawing().
onCmdStopDrawing()
long GNEFrame::DrawingMode::onCmdStopDrawing (FXObject * , FXSelector , void *)
Called when the user press stop drawing button.
Definition at line 477 of file GNEFrame.cpp.
References stopDrawing().
removeLastPoint()
void GNEFrame::DrawingMode::removeLastPoint ()
remove last added point
Definition at line 446 of file GNEFrame.cpp.
References myStopDrawingButton, and myTemporalShapeShape.
Referenced by GNEViewNet::onRightBtnPress().
showDrawingMode()
void GNEFrame::DrawingMode::showDrawingMode ()
show Drawing mode
Definition at line 369 of file GNEFrame.cpp.
References abortDrawing().
Referenced by GNEPolygonFrame::onCmdSelectShape().
startDrawing()
void GNEFrame::DrawingMode::startDrawing ()
start drawing
Definition at line 386 of file GNEFrame.cpp.
References myAbortDrawingButton, myStartDrawingButton, and myStopDrawingButton.
Referenced by GNEViewNet::hotkeyEnter(), and onCmdStartDrawing().
stopDrawing()
void GNEFrame::DrawingMode::stopDrawing ()
stop drawing and create polygon or
NOTE: This solution using dynamic_cast is provisional, and has to be changed for task #1112.
Definition at line 398 of file GNEFrame.cpp.
References abortDrawing(), PositionVector::closePolygon(), GNEFrame::getNeteditAttributes(), GNEFrame::getViewNet(), GNEFrame::NeteditAttributes::isCloseShapeEnabled(), myAbortDrawingButton, myFrameParent, myStartDrawingButton, myStopDrawingButton, and myTemporalShapeShape.
Referenced by GNEViewNet::hotkeyEnter(), and onCmdStopDrawing().
Field Documentation
myAbortDrawingButton
FXButton* GNEFrame::DrawingMode::myAbortDrawingButton private
button for abort drawing
Definition at line 278 of file GNEFrame.h.
Referenced by abortDrawing(), DrawingMode(), startDrawing(), and stopDrawing().
myFrameParent
GNEFrame* GNEFrame::DrawingMode::myFrameParent private
frame frame parent
Definition at line 269 of file GNEFrame.h.
Referenced by abortDrawing(), and stopDrawing().
myInformationLabel
FXLabel* GNEFrame::DrawingMode::myInformationLabel private
Label with information.
Definition at line 281 of file GNEFrame.h.
Referenced by DrawingMode().
myStartDrawingButton
FXButton* GNEFrame::DrawingMode::myStartDrawingButton private
button for start drawing
Definition at line 272 of file GNEFrame.h.
Referenced by abortDrawing(), DrawingMode(), startDrawing(), and stopDrawing().
myStopDrawingButton
FXButton* GNEFrame::DrawingMode::myStopDrawingButton private
button for stop drawing
Definition at line 275 of file GNEFrame.h.
Referenced by abortDrawing(), addNewPoint(), DrawingMode(), isDrawing(), removeLastPoint(), startDrawing(), and stopDrawing().
myTemporalShapeShape
PositionVector GNEFrame::DrawingMode::myTemporalShapeShape private
current drawed shape
Definition at line 284 of file GNEFrame.h.
Referenced by abortDrawing(), addNewPoint(), getTemporalShape(), removeLastPoint(), and stopDrawing().
The documentation for this class was generated from the following files:
GNEFrame.h
GNEFrame.cpp