SUMO - Simulation of Urban MObility: GNEReferenceCounter Class Reference
GNEReferenceCounter Class Reference abstract
#include <GNEReferenceCounter.h>
Public Member Functions
void decRef (const std::string &debugMsg="")
Decrease reference.
virtual const std::string getID () const =0
return ID of object
GNEReferenceCounter ()
void incRef (const std::string &debugMsg="")
Increarse reference.
bool unreferenced ()
check if object ins't referenced
~GNEReferenceCounter ()
Private Attributes
int myCount
reference counter
Detailed Description
Definition at line 46 of file GNEReferenceCounter.h.
Constructor & Destructor Documentation
GNEReferenceCounter()
GNEReferenceCounter::GNEReferenceCounter () inline
Definition at line 49 of file GNEReferenceCounter.h.
~GNEReferenceCounter()
GNEReferenceCounter::~GNEReferenceCounter () inline
Definition at line 52 of file GNEReferenceCounter.h.
References myCount, toString(), and WRITE_ERROR.
Member Function Documentation
decRef()
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline
Decrease reference.
Definition at line 61 of file GNEReferenceCounter.h.
References getID(), myCount, toString(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
getID()
virtual const std::string GNEReferenceCounter::getID () const pure virtual
return ID of object
Implemented in GNEAttributeCarrier.
Referenced by decRef(), incRef(), and unreferenced().
incRef()
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline
Increarse reference.
Definition at line 76 of file GNEReferenceCounter.h.
References getID(), myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNEChange_CalibratorItem::GNEChange_CalibratorItem(), GNEChange_RerouterItem::GNEChange_RerouterItem(), GNEJunction::rebuildGNECrossings(), GNENet::registerEdge(), GNENet::registerJunction(), GNEEdge::remakeGNEConnections(), and GNEInspectorFrame::setEdgeTemplate().
unreferenced()
bool GNEReferenceCounter::unreferenced () inline
check if object ins't referenced
Definition at line 87 of file GNEReferenceCounter.h.
References getID(), and myCount.
Referenced by GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_CalibratorItem::~GNEChange_CalibratorItem(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_RerouterItem::~GNEChange_RerouterItem(), GNEChange_Shape::~GNEChange_Shape(), GNEChange_TLS::~GNEChange_TLS(), GNEChange_VariableSpeedSignItem::~GNEChange_VariableSpeedSignItem(), and GNEInspectorFrame::~GNEInspectorFrame().
Field Documentation
myCount
int GNEReferenceCounter::myCount private
reference counter
Definition at line 97 of file GNEReferenceCounter.h.
Referenced by decRef(), incRef(), unreferenced(), and ~GNEReferenceCounter().
The documentation for this class was generated from the following file:
GNEReferenceCounter.h