SUMO - Simulation of Urban MObility: GUIVehicle Class Reference
GUIVehicle Class Reference
A MSVehicle extended by some values for usage within the gui.
#include <GUIVehicle.h>
Public Types
enum ChangeRequest { REQUEST_NONE, REQUEST_LEFT, REQUEST_RIGHT, REQUEST_HOLD }
Requests set via TraCI.
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
void activateReminders (const MSMoveReminder::Notification reason, const MSLane *enteredLane=0)
"Activates" all current move reminder
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
bool addTraciStop (MSLane *const lane, const double startPos, const double endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string &errorMsg)
bool addTraciStopAtStoppingPlace (const std::string &stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const SumoXMLTag stoppingPlaceType, std::string &errorMsg)
bool checkActionStep (const SUMOTime t)
Returns whether the vehicle is supposed to take action in the current simulation step Updates myActionStep and myLastActionTime in case that the current simstep is an action step.
double computeAngle () const
compute the current vehicle angle
bool congested () const
void createDevice (const std::string &deviceName)
create device of the given type
void drawAction_drawLinkItems (const GUIVisualizationSettings &s) const
void drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &s) const
void drawAction_drawVehicleBlinker (double length) const
void drawAction_drawVehicleBlueLight () const
void drawAction_drawVehicleBrakeLight (double length, bool onlyOne=false) const
void drawBestLanes () const
Draws the vehicle's best lanes.
void drawName (const Position &pos, const double scale, const GUIVisualizationTextSettings &settings, const double angle=0) const
draw name of item
void drawRouteHelper (const GUIVisualizationSettings &s, const MSRoute &r) const
Draws the route.
void enterLaneAtInsertion (MSLane *enteredLane, double pos, double speed, double posLat, MSMoveReminder::Notification notification)
Update when the vehicle enters a new lane in the emit step.
void enterLaneAtLaneChange (MSLane *enteredLane)
Update when the vehicle enters a new lane in the laneChange step.
bool enterLaneAtMove (MSLane *enteredLane, bool onTeleporting=false)
Update when the vehicle enters a new lane in the move step.
bool executeMove ()
Executes planned vehicle movements with regards to right-of-way.
void fixPosition ()
repair errors in vehicle position after changing between internal edges
double getAngle () const
Return current angle.
virtual double getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
PositionVector getBoundingBox () const
get bounding rectangle
PositionVector getBoundingPoly () const
get bounding polygon
const MSCFModel & getCarFollowModel () const
Returns the vehicle's car following model definition.
MSCFModel::VehicleVariables * getCarFollowVariables () const
Returns the vehicle's car following model variables.
double getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
double getColorValue (int activeScheme) const
gets the color value according to the current scheme index
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
double getDeltaPos (double accel)
calculates the distance covered in the next integration step given an acceleration and assuming the current velocity. (gives different results for different integration methods, e.g., euler vs. ballistic)
SUMOTime getDepartDelay () const
Returns the depart delay.
double getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
std::string getDeviceParameter (const std::string &deviceName, const std::string &key) const
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
double getDistanceToPosition (double destPos, const MSEdge *destEdge) const
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
const std::vector< MSLane * > & getFurtherLanes () const
const std::vector< double > & getFurtherLanesPosLat () const
const std::string & getID () const
Returns the name of the vehicle.
double getImpatience () const
Returns this vehicles impatience.
Influencer & getInfluencer ()
Returns the velocity/lane influencer.
const Influencer * getInfluencer () const
MSAbstractLaneChangeModel & getLaneChangeModel ()
const MSAbstractLaneChangeModel & getLaneChangeModel () const
int getLaneIndex () const
double getLastLaneChangeOffset () const
Returns the time since the last lane change in seconds.
std::pair< const MSVehicle *const, double > getLeader (double dist=0) const
Returns the leader of the vehicle looking for a fixed distance.
double getLeftSideOnEdge () const
return left vehicle side on current edge
int getLeftSublaneOnEdge () const
double getLength () const
Returns the vehicle's length.
double getManeuverDist () const
return the lane-change maneuver distance
double getMaxSpeed () const
Returns the maximum speed.
double getNaviDegree () const
return the current angle in navigational degrees
Stop & getNextStop ()
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Position getPosition (const double offset=0) const
Return current position (x/y, cartesian)
double getRightSideOnEdge2 () const
return right vehicle side on current edge (without argument)
int getRightSublaneOnEdge () const
return the righmost sublane on the edge occupied by the vehicle
const MSRoute & getRoute () const
Returns the current route.
double getSafeFollowSpeed (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, const MSLane *const lane, double distToCrossing) const
compute safe speed for following the given leader
MSVehicleType & getSingularType ()
Replaces the current vehicle type with a new one used by this vehicle only.
double getSpeedWithoutTraciInfluence () const
Returns the uninfluenced velocity.
double getTimeGapOnLane () const
Returns the time gap in seconds to the leader of the vehicle on the same lane.
GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
double getWidth () const
Returns the vehicle's width.
GUIVehicle (SUMOVehicleParameter *pars, const MSRoute *route, MSVehicleType *type, const double speedFactor)
Constructor.
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasDevice (const std::string &deviceName) const
check whether the vehicle is equiped with a device of the given type
bool hasInfluencer () const
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
int influenceChangeDecision (int state)
allow TraCI to influence a lane change decision
bool isSelected () const
whether this vehicle is selected in the GUI
void leaveLane (const MSMoveReminder::Notification reason, const MSLane *approachedLane=0)
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
void onDepart ()
Called when the vehicle is inserted into the network.
bool onFurtherEdge (const MSEdge *edge) const
whether this vehicle has its back (and no its front) on the given edge
bool passingMinor () const
decide whether the vehicle is passing a minor link or has comitted to do so
void planMove (const SUMOTime t, const MSLeaderInfo &ahead, const double lengthsInFront)
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
double processNextStop (double currentVelocity)
Processes stops, returns the velocity needed to reach the stop.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false, bool removeStops=true)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
void resetActionOffset (const SUMOTime timeUntilNextAction=0)
Resets the action offset for the vehicle.
bool resumeFromStopping ()
void selectBlockingFoes () const
adds the blocking foes to the current selection
void setAngle (double angle, bool straightenFurther=false)
Set a custom vehicle angle in rad, optionally updates furtherLanePosLat.
virtual void setArrivalPos (double arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setChosenSpeedFactor (const double factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setDeviceParameter (const std::string &deviceName, const std::string &key, const std::string &value)
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
void setRemoteState (Position xyPos)
sets position outside the road network
void setTentativeLaneAndPosition (MSLane *lane, double pos, double posLat=0)
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
bool unsafeLinkAhead (const MSLane *lane) const
whether the vehicle may safely move to the given lane with regard to upcoming links
void updateActionOffset (const SUMOTime oldActionStepLength, const SUMOTime newActionStepLength)
Process an updated action step length value (only affects the vehicle's action offset, The actionStepLength is stored in the (singular) vtype)
void updateDriveItems ()
Check whether the drive items (myLFLinkLanes) are up to date, and update them if required.
double updateFurtherLanes (std::vector< MSLane *> &furtherLanes, std::vector< double > &furtherLanesPosLat, const std::vector< MSLane *> &passedLanes)
update a vector of further lanes and return the new backPos
~GUIVehicle ()
destructor
insertion/removal
void onRemovalFromNet (const MSMoveReminder::Notification reason)
Called when the vehicle is removed from the network.
interaction with the route
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0, bool addStops=true, bool removeStops=true)
Replaces the current route by the given one.
bool willPass (const MSEdge *const edge) const
Returns whether the vehicle wil pass the given edge.
int getRoutePosition () const
void resetRoutePosition (int index)
const MSEdgeWeightsStorage & getWeightsStorage () const
Returns the vehicle's internal edge travel times/efforts container.
MSEdgeWeightsStorage & getWeightsStorage ()
state setter/getter
double getPositionOnLane () const
Get the vehicle's position along the lane.
double getPositionOnLane (const MSLane *lane) const
Get the vehicle's front position relative to the given lane.
double getLastStepDist () const
Get the distance the vehicle covered in the previous timestep.
double getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
double getBackPositionOnLane () const
Get the vehicle's position relative to its current lane.
double getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
double getRightSideOnLane () const
Get the vehicle's lateral position on the lane:
double lateralDistanceToLane (const int offset) const
Get the minimal lateral distance required to move fully onto the lane at given offset.
double getLateralOverlap () const
return the amount by which the vehicle extends laterally outside it's primary lane
double getLateralOverlap (double posLat) const
double getRightSideOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
double getCenterOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
double getLatOffset (const MSLane *lane) const
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
double getSpeed () const
Returns the vehicle's current speed.
double getPreviousSpeed () const
Returns the vehicle's speed before the previous time step.
double getAcceleration () const
Returns the vehicle's acceleration in m/s (this is computed as the last step's mean acceleration in case that a stop occurs within the middle of the time-step)
SUMOTime getActionStepLength () const
Returns the vehicle's action step length in millisecs, i.e. the interval between two action points.
double getActionStepLengthSecs () const
Returns the vehicle's action step length in secs, i.e. the interval between two action points.
SUMOTime getLastActionTime () const
Returns the time of the vehicle's last action point.
Other getter methods
double getSlope () const
Returns the slope of the road at vehicle's position.
Position getPositionAlongBestLanes (double offset) const
Return the (x,y)-position, which the vehicle would reach if it continued along its best continuation lanes from the current for a distance of offset m.
MSLane * getLane () const
Returns the lane the vehicle is on.
double getMaxSpeedOnLane () const
Returns the maximal speed for the vehicle on its current lane (including speed factor and deviation, i.e., not necessarily the allowed speed limit)
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isActive () const
Returns whether the current simulation step is an action point for the vehicle.
bool isActionStep (SUMOTime t) const
Returns whether the next simulation step will be an action point for the vehicle.
bool isFrontOnLane (const MSLane *lane) const
Returns the information whether the front of the vehicle is on the given lane.
const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
SUMOTime getWaitingTime () const
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
SUMOTime getTimeLoss () const
Returns the SUMOTime lost (speed was lesser maximum speed)
SUMOTime getAccumulatedWaitingTime () const
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
double getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
double getAccumulatedWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
double getTimeLossSeconds () const
Returns the time loss in seconds.
Position getVelocityVector () const
Returns the vehicle's direction in radians.
strategical/tactical lane choosing methods
const std::vector< LaneQ > & getBestLanes () const
Returns the description of best lanes to use in order to continue the route.
void updateBestLanes (bool forceRebuild=false, const MSLane *startLane=0)
computes the best lanes to use in order to continue the route
const std::vector< MSLane * > & getBestLanesContinuation () const
Returns the best sequence of lanes to continue the route starting at myLane.
const std::vector< MSLane * > & getBestLanesContinuation (const MSLane *const l) const
Returns the best sequence of lanes to continue the route starting at the given lane.
int getBestLaneOffset () const
void adaptBestLanesOccupation (int laneIndex, double density)
update occupation from MSLaneChanger
vehicle stops definitions and i/o
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0, bool collision=false, MSRouteIterator *searchStart=0)
Adds a stop.
bool replaceParkingArea (MSParkingArea *parkingArea, std::string &errorMsg)
replace the current parking area stop with a new stop with merge duration
MSParkingArea * getNextParkingArea ()
get the current parking area stop
bool hasStops () const
Returns whether the vehicle has to stop somewhere.
bool isStopped () const
Returns whether the vehicle is at a stop.
bool isStoppedOnLane () const
bool keepStopping (bool afterProcessing=false) const
Returns whether the vehicle is stopped and must continue to do so.
SUMOTime collisionStopTime () const
Returns the remaining time a vehicle needs to stop due to a collision. A negative value indicates that the vehicle is not stopping due to a collision (or at all)
bool isParking () const
Returns whether the vehicle is parking.
bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
bool wasRemoteControlled (SUMOTime lookBack=DELTA_T) const
Returns the information whether the vehicle is fully controlled via TraCI within the lookBack time.
double nextStopDist () const
return the distance to the next stop or doubleMax if there is none.
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool isStoppedInRange (double pos) const
return whether the given position is within range of the current stop
Emission retrieval
double getCO2Emissions () const
Returns CO2 emission of the current state.
double getCOEmissions () const
Returns CO emission of the current state.
double getHCEmissions () const
Returns HC emission of the current state.
double getNOxEmissions () const
Returns NOx emission of the current state.
double getPMxEmissions () const
Returns PMx emission of the current state.
double getFuelConsumption () const
Returns fuel consumption of the current state.
double getElectricityConsumption () const
Returns electricity consumption of the current state.
double getHarmonoise_NoiseEmissions () const
Returns noise emissions of the current state.
Interaction with persons
void addPerson (MSTransportable *person)
Adds a passenger.
Interaction with containers
void addContainer (MSTransportable *container)
Adds a container.
void removeTransportable (MSTransportable *t)
removes a person or container
const std::vector< MSTransportable * > & getPersons () const
retrieve riding persons
const std::vector< MSTransportable * > & getContainers () const
retrieve riding containers
int getPersonNumber () const
Returns the number of persons.
int getContainerNumber () const
Returns the number of containers.
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawOnPos (const GUIVisualizationSettings &s, const Position &pos, const double angle) const
Draws the object on the specified position with the specified angle.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static int nextLinkPriority (const std::vector< MSLane *> &conts)
get a numerical value for the priority of the upcoming link
static bool overlap (const MSVehicle *veh1, const MSVehicle *veh2)
static bool setFunctionalColor (int activeScheme, const MSBaseVehicle *veh)
sets the color according to the current scheme index and some vehicle function
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::vector< DriveProcessItem > DriveItemVector
Container for used Links/visited Lanes during planMove() and executeMove.
Protected Member Functions
void adaptToLeader (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double &v, double &vLinkPass, double distToCrossing=-1) const
void adaptToLeaders (const MSLeaderInfo &ahead, double latOffset, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double &v, double &vLinkPass) const
void buildAdditionalsPopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void buildShapePopupOptions (GUIMainWindow &app, GUIGLObjectPopupMenu *ret, const std::string &type)
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
void checkLinkLeader (const MSLink *link, const MSLane *lane, double seen, DriveProcessItem *const lastLink, double &v, double &vLinkPass, double &vLinkWait, bool &setRequest, bool isShadowLink=false) const
checks for link leaders on the given link
void checkRewindLinkLanes (const double lengthsInFront, DriveItemVector &lfLinks) const
void drawOutsideNetwork (bool add)
register vehicle for drawing while outside the network
double estimateLeaveSpeed (const MSLink *const link, const double vLinkPass) const
estimate leaving speed when accelerating across a link
const MSLane * getBackLane () const
const Position getBackPosition () const
const Position & getSeatPosition (int personIndex) const
returns the seat position for the person with the given index
double getSpaceTillLastStanding (const MSLane *l, bool &foundStopped) const
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
const MSVehicleType & getVType () const
A shortcut to myVehicle.myType.
bool ignoreRed (const MSLink *link, bool canBrake) const
decide whether a red (or yellow light) may be ignore
bool keepClear (const MSLink *link) const
decide whether the given link must be kept clear
void planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector &lfLinks, double &myStopDist) const
void processLaneAdvances (std::vector< MSLane *> &passedLanes, bool &moved, std::string &emergencyReason)
This method checks if the vehicle has advanced over one or several lanes along its route and triggers the corresponding actions for the lanes and the vehicle. and adapts the given in/out parameters to the appropriate values.
void processLinkAproaches (double &vSafe, double &vSafeMin, double &vSafeMinDist)
This method iterates through the driveprocess items for the vehicle and adapts the given in/out parameters to the appropriate values.
void processTraCISpeedControl (double vSafe, double &vNext)
Check for speed advices from the traci client and adjust the speed vNext in the current (euler) / after the current (ballistic) simstep accordingly.
void removeApproachingInformation (DriveItemVector &lfLinks) const
unregister approach from all upcoming links
void removePassedDriveItems ()
Erase passed drive items from myLFLinkLanes (and unregister approaching information for corresponding links). Further, myNextDriveItem is reset.
void setBlinkerInformation ()
sets the blue flashing light for emergency vehicles
void setBrakingSignals (double vNext)
sets the braking lights on/off
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
void setEmergencyBlueLight (SUMOTime currentTime)
sets the blue flashing light for emergency vehicles
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
void updateOccupancyAndCurrentBestLane (const MSLane *startLane)
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
void updateState (double vNext)
updates the vehicles state, given a next value for its speed. This value can be negative in case of the ballistic update to indicate a stop within the next timestep. (You can call this a 'hack' to emulate reasoning based on accelerations: The assumed constant acceleration a within the next time step is then a = (vNext - vCurrent)/TS)
void updateTimeLoss (double vNext)
Updates the vehicle's time loss.
void updateWaitingTime (double vNext)
Updates the vehicle's waiting time counters (accumulated and consecutive)
Position validatePosition (Position result, double offset=0) const
ensure that a vehicle-relative position is not invalid
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Member Functions
static void drawLinkItem (const Position &pos, SUMOTime arrivalTime, SUMOTime leaveTime, double exagerate)
Protected Attributes
double myAcceleration
The current acceleration after dawdling in m/s.
bool myActionStep
The flag myActionStep indicates whether the current time step is an action point for the vehicle.
bool myAmOnNet
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
bool myAmRegisteredAsWaitingForContainer
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
bool myAmRegisteredAsWaitingForPerson
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
double myAngle
the angle in radians (
int myArrivalLane
The destination lane where the vehicle stops.
double myArrivalPos
The position on the destination lane where the vehicle stops.
std::vector< std::vector< LaneQ > > myBestLanes
Position myCachedPosition
double myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
SUMOTime myCollisionImmunity
amount of time for which the vehicle is immune from collisions
MSDevice_Transportable * myContainerDevice
The containers this vehicle may have.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
std::vector< LaneQ >::iterator myCurrentLaneInBestLanes
double myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
std::vector< MSLane * > myFurtherLanes
The information into which lanes the vehicle laps into.
std::vector< double > myFurtherLanesPosLat
lateral positions on further lanes
bool myHaveToWaitOnNextLink
MSLane * myLane
The lane the vehicle is on.
MSAbstractLaneChangeModel * myLaneChangeModel
SUMOTime myLastActionTime
Action offset (actions are taken at time myActionOffset + N*getActionStepLength()) Initialized to 0, to be set at insertion.
const MSEdge * myLastBestLanesEdge
const MSLane * myLastBestLanesInternalLane
DriveItemVector myLFLinkLanes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
DriveItemVector::iterator myNextDriveItem
iterator pointing to the next item in myLFLinkLanes
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This vehicle's parameter.
MSDevice_Transportable * myPersonDevice
The passengers this vehicle may have.
const MSRoute * myRoute
This vehicle's route.
PositionVector mySeatPositions
positions of seats in the vehicle (updated at every drawing step)
int mySignals
State of things of the vehicle that can be on or off.
State myState
This Vehicles driving state (pos and speed)
double myStopDist
distance to the next stop or -1 if there is none
std::list< Stop > myStops
The vehicle's list of stops.
double myTimeLoss
the time loss in seconds due to driving with less than maximum speed
MSVehicleType * myType
This vehicle's type.
SUMOTime myWaitingTime
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
WaitingTimeCollector myWaitingTimeCollector
Static Protected Attributes
static std::vector< MSLane * > myEmptyLaneVector
static std::vector< MSTransportable * > myEmptyTransportableVector
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Private Member Functions
void computeSeats (const Position &front, const Position &back, int &requiredSeats) const
add seats to mySeatPositions and update requiredSeats
bool drawAction_drawCarriageClass (const GUIVisualizationSettings &s, SUMOVehicleShape guiShape, bool asImage) const
draws the given guiShape if it has distinct carriages/modules and returns true if so
void drawAction_drawRailCarriages (const GUIVisualizationSettings &s, double defaultLength, double carriageGap, int firstPassengerCarriage, bool asImage) const
int getNumPassengers () const
return the number of passengers
MSLane * getPreviousLane (MSLane *current, int &furtherIndex) const
std::string getStopInfo () const
retrieve information about the current stop state
Additional visualisations
bool hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
void addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void drawRoute (const GUIVisualizationSettings &s, int routeNo, double darken) const
Chooses the route to draw and draws it, darkening it as given.
enum VisualisationFeatures {
VO_SHOW_BEST_LANES = 1, VO_SHOW_ROUTE = 2, VO_SHOW_ALL_ROUTES = 4, VO_SHOW_LFLINKITEMS = 8,
VO_DRAW_OUTSIDE_NETWORK = 16
}
Additional visualisation feature ids.
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
drawing helper methods
void drawAction_drawVehicleAsBoxPlus () const
void drawAction_drawVehicleAsTrianglePlus () const
bool drawAction_drawVehicleAsPoly (const GUIVisualizationSettings &s) const
bool drawAction_drawVehicleAsImage (const GUIVisualizationSettings &s, double length=-1) const
static void drawPoly (double *poses, double offset)
Move reminder structures
typedef std::vector< std::pair< MSMoveReminder *, double > > MoveReminderCont
Definition of a move reminder container.
MoveReminderCont myMoveReminders
Currently relevant move reminders.
Interaction with move reminders
void workOnMoveReminders (double oldPos, double newPos, double newSpeed)
Processes active move reminder.
void adaptLaneEntering2MoveReminder (const MSLane &enteredLane)
Adapts the vehicle's entering of a new lane.
Access to bool signals
void switchOnSignal (int signal)
Switches the given signal on.
void switchOffSignal (int signal)
Switches the given signal off.
int getSignals () const
Returns the signals.
bool signalSet (int which) const
Returns whether the given signal is on.
enum Signalling {
VEH_SIGNAL_NONE = 0, VEH_SIGNAL_BLINKER_RIGHT = 1, VEH_SIGNAL_BLINKER_LEFT = 2, VEH_SIGNAL_BLINKER_EMERGENCY = 4,
VEH_SIGNAL_BRAKELIGHT = 8, VEH_SIGNAL_FRONTLIGHT = 16, VEH_SIGNAL_FOGLIGHT = 32, VEH_SIGNAL_HIGHBEAM = 64,
VEH_SIGNAL_BACKDRIVE = 128, VEH_SIGNAL_WIPER = 256, VEH_SIGNAL_DOOR_OPEN_LEFT = 512, VEH_SIGNAL_DOOR_OPEN_RIGHT = 1024,
VEH_SIGNAL_EMERGENCY_BLUE = 2048, VEH_SIGNAL_EMERGENCY_RED = 4096, VEH_SIGNAL_EMERGENCY_YELLOW = 8192
}
Some boolean values which describe the state of some vehicle parts.
enum LaneChangeMode { LC_NEVER = 0, LC_NOCONFLICT = 1, LC_ALWAYS = 2 }
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
enum TraciLaneChangePriority { LCP_ALWAYS = 0, LCP_NOOVERLAP = 1, LCP_URGENT = 2, LCP_OPPORTUNISTIC = 3 }
modes for prioritizing traci lane change requests
Detailed Description
A MSVehicle extended by some values for usage within the gui.
A visualisable MSVehicle. Extended by the possibility to retrieve names of all available vehicles (static) and the possibility to retrieve the color of the vehicle which is available in different forms allowing an easier recognition of done actions such as lane changing.
Definition at line 60 of file GUIVehicle.h.
Member Typedef Documentation
ComparatorIdLess
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 79 of file SUMOVehicle.h.
DriveItemVector
typedef std::vector< DriveProcessItem > MSVehicle::DriveItemVector protected inherited
Container for used Links/visited Lanes during planMove() and executeMove.
Definition at line 1813 of file MSVehicle.h.
MoveReminderCont
typedef std::vector< std::pair<MSMoveReminder*, double> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 468 of file MSBaseVehicle.h.
Member Enumeration Documentation
ChangeRequest
enum MSVehicle::ChangeRequest inherited
Requests set via TraCI.
Enumerator
REQUEST_NONE
vehicle doesn't want to change
REQUEST_LEFT
vehicle want's to change to left lane
REQUEST_RIGHT
vehicle want's to change to right lane
REQUEST_HOLD
vehicle want's to keep the current lane
Definition at line 222 of file MSVehicle.h.
LaneChangeMode
enum MSVehicle::LaneChangeMode inherited
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
Enumerator
LC_NEVER
LC_NOCONFLICT
LC_ALWAYS
Definition at line 1196 of file MSVehicle.h.
Signalling
enum MSVehicle::Signalling inherited
Some boolean values which describe the state of some vehicle parts.
Enumerator
VEH_SIGNAL_NONE
Everything is switched off.
VEH_SIGNAL_BLINKER_RIGHT
Right blinker lights are switched on.
VEH_SIGNAL_BLINKER_LEFT
Left blinker lights are switched on.
VEH_SIGNAL_BLINKER_EMERGENCY
Blinker lights on both sides are switched on.
VEH_SIGNAL_BRAKELIGHT
The brake lights are on.
VEH_SIGNAL_FRONTLIGHT
The front lights are on (no visualisation)
VEH_SIGNAL_FOGLIGHT
The fog lights are on (no visualisation)
VEH_SIGNAL_HIGHBEAM
The high beam lights are on (no visualisation)
VEH_SIGNAL_BACKDRIVE
The backwards driving lights are on (no visualisation)
VEH_SIGNAL_WIPER
The wipers are on.
VEH_SIGNAL_DOOR_OPEN_LEFT
One of the left doors is opened.
VEH_SIGNAL_DOOR_OPEN_RIGHT
One of the right doors is opened.
VEH_SIGNAL_EMERGENCY_BLUE
A blue emergency light is on.
VEH_SIGNAL_EMERGENCY_RED
A red emergency light is on.
VEH_SIGNAL_EMERGENCY_YELLOW
A yellow emergency light is on.
Definition at line 1158 of file MSVehicle.h.
TraciLaneChangePriority
enum MSVehicle::TraciLaneChangePriority inherited
modes for prioritizing traci lane change requests
Enumerator
LCP_ALWAYS
LCP_NOOVERLAP
LCP_URGENT
LCP_OPPORTUNISTIC
Definition at line 1204 of file MSVehicle.h.
VisualisationFeatures
enum GUIBaseVehicle::VisualisationFeatures inherited
Additional visualisation feature ids.
Enumerator
VO_SHOW_BEST_LANES
show vehicle's best lanes
VO_SHOW_ROUTE
show vehicle's current route
VO_SHOW_ALL_ROUTES
show all vehicle's routes
VO_SHOW_LFLINKITEMS
LFLinkItems.
VO_DRAW_OUTSIDE_NETWORK
draw vehicle outside the road network
Definition at line 287 of file GUIBaseVehicle.h.
Constructor & Destructor Documentation
GUIVehicle()
GUIVehicle::GUIVehicle (SUMOVehicleParameter * pars, const MSRoute * route, MSVehicleType * type, const double speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 84 of file GUIVehicle.cpp.
~GUIVehicle()
GUIVehicle::~GUIVehicle ()
destructor
Definition at line 94 of file GUIVehicle.cpp.
Member Function Documentation
activateReminders()
void MSVehicle::activateReminders (const MSMoveReminder::Notification reason, const MSLane * enteredLane = 0) virtual inherited
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
[in] enteredLane The lane, which is entered (if applicable)
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSBaseVehicle.
Definition at line 3445 of file MSVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::congested(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), and MSVehicle::processNextStop().
adaptBestLanesOccupation()
void MSVehicle::adaptBestLanesOccupation (int laneIndex, double density) inherited
update occupation from MSLaneChanger
Definition at line 4065 of file MSVehicle.cpp.
References MSVehicle::myBestLanes.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
adaptLaneEntering2MoveReminder()
void MSVehicle::adaptLaneEntering2MoveReminder (const MSLane & enteredLane) protected inherited
Adapts the vehicle's entering of a new lane.
All offsets already stored in "myOldLaneMoveReminderOffsets" are increased by the length that has been left. All still active move reminders from "myMoveReminders" are put into "myOldLaneMoveReminders" and the offset to the last lane is added to "myOldLaneMoveReminderOffsets" for each of these.
Move reminder from the given lane are set into "myMoveReminders".
"myLane" must still be the left lane!
Parameters
[in] enteredLane
See also
MSMoveReminder
MSLane::getMoveReminder
Definition at line 868 of file MSVehicle.cpp.
References MSBaseVehicle::addReminder(), MSLane::getLength(), MSLane::getMoveReminders(), MSVehicle::myLane, and MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::enterLaneAtMove(), and MSVehicle::hasInfluencer().
adaptToLeader()
void MSVehicle::adaptToLeader (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double & v, double & vLinkPass, double distToCrossing = -1) const protected inherited
Definition at line 2123 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getSafeFollowSpeed(), MIN2(), MSVehicle::myLane, and SIMTIME.
Referenced by MSVehicle::adaptToLeaders(), MSVehicle::checkLinkLeader(), and MSVehicle::estimateLeaveSpeed().
adaptToLeaders()
void MSVehicle::adaptToLeaders (const MSLeaderInfo & ahead, double latOffset, const double seen, DriveProcessItem *const lastLink, const MSLane *const lane, double & v, double & vLinkPass) const protected inherited
Definition at line 2078 of file MSVehicle.cpp.
References MSVehicle::adaptToLeader(), DEBUG_COND, MSVehicle::getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::myState, SIMTIME, and MSLeaderInfo::toString().
Referenced by MSVehicle::checkLinkLeader(), MSVehicle::estimateLeaveSpeed(), and MSVehicle::planMoveInternal().
addActiveAddVisualisation()
void GUIBaseVehicle::addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::addAdditionalGLVisualisation
Definition at line 1174 of file GUIBaseVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), and GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems().
addContainer()
void MSVehicle::addContainer (MSTransportable * container) virtual inherited
Adds a container.
Parameters
[in] container The container to add
Reimplemented from MSBaseVehicle.
Definition at line 4201 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), MSVehicle::myContainerDevice, MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, and MSVehicle::myStops.
Referenced by MSTransportableControl::loadAnyWaiting(), and MSVehicle::nextStopDist().
addParameterTable()
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 255 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::GUIParameterTableWindow().
addPerson()
void MSVehicle::addPerson (MSTransportable * person) virtual inherited
Adds a passenger.
Parameters
[in] person The person to add
Reimplemented from MSBaseVehicle.
Definition at line 4186 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, MSVehicle::myPersonDevice, and MSVehicle::myStops.
Referenced by MSTransportableControl::boardAnyWaiting(), and MSVehicle::nextStopDist().
addReminder()
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 349 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MESegment::addReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSBaseVehicle::getDevices(), and MSVehicle::processNextStop().
addStop()
bool MSVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0, bool collision = false, MSRouteIterator * searchStart = 0) virtual inherited
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 1103 of file MSVehicle.cpp.
References MSLane::allowsVehicleClass(), SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, MSVehicle::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, MSVehicle::Stop::chargingStation, MSVehicle::Stop::collision, SUMOVehicleParameter::Stop::containerstop, MSVehicle::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, MSVehicle::Stop::containerTriggered, DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_GIVEN, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSRoute::end(), SUMOVehicleParameter::Stop::endPos, MSVehicle::getCarFollowModel(), MSLane::getEdge(), Named::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSBaseVehicle::getLength(), MSLane::getLength(), MSLane::getNextNormal(), MSEdge::getNormalBefore(), MSNet::getStoppingPlace(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasDeparted(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, MSEdge::isInternal(), SUMOVehicleParameter::Stop::lane, MSVehicle::Stop::lane, MIN2(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myStops, MSBaseVehicle::myType, MSVehicle::Stop::numExpectedContainer, MSVehicle::Stop::numExpectedPerson, SUMOVehicleParameter::Stop::parkingarea, MSVehicle::Stop::parkingarea, MSVehicle::Stop::pars, POSITION_EPS, MSVehicle::Stop::reached, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_END, STOP_INDEX_FIT, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_PARKING_AREA, MSVehicle::Stop::timeToBoardNextPerson, MSVehicle::Stop::timeToLoadNextContainer, SUMOVehicleParameter::Stop::triggered, MSVehicle::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSLane::handleCollisionBetween(), MSVehicle::replaceParkingArea(), and MSVehicle::replaceRoute().
addStops()
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 473 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), SUMOVehicleParameter::depart, MSRoute::getStops(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::stops, and WRITE_WARNING.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MEVehicle::getBlockTimeSeconds(), MSVehicle::replaceRoute(), and MSBaseVehicle::setChosenSpeedFactor().
addTraciStop()
bool MSVehicle::addTraciStop (MSLane *const lane, const double startPos, const double endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string & errorMsg) inherited
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
lane lane on wich to stop
startPos start position on the given lane at wich to stop
endPos end position on the given lane at wich to stop
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
XXX handle stops added out of order
Definition at line 4626 of file MSVehicle.cpp.
References MSVehicle::addStop(), SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, Named::getID(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::myLane, MSBaseVehicle::myParameter, MSVehicle::myStops, SUMOVehicleParameter::Stop::parametersSet, SUMOVehicleParameter::Stop::parking, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMOVehicleParameter::stops, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::updateBestLanes().
Referenced by libsumo::Vehicle::setStop(), and MSVehicle::signalSet().
addTraciStopAtStoppingPlace()
bool MSVehicle::addTraciStopAtStoppingPlace (const std::string & stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const SumoXMLTag stoppingPlaceType, std::string & errorMsg) inherited
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
stopId bus or container stop id
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
stoppingPlaceType a flag indicating the type of stopping place
Definition at line 4675 of file MSVehicle.cpp.
References MSVehicle::addStop(), SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSNet::getStoppingPlace(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::myLane, MSVehicle::myStops, SUMOVehicleParameter::Stop::parametersSet, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, SUMOVehicleParameter::Stop::startPos, STOP_CONTAINER_TRIGGER_SET, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_TRIGGER_SET, SUMO_TAG_BUS_STOP, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_PARKING_AREA, toString(), SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::updateBestLanes().
Referenced by libsumo::Vehicle::setStop(), and MSVehicle::signalSet().
buildAdditionalsPopupOptions()
void GUIGlObject::buildAdditionalsPopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic additional popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 300 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
buildCenterPopupEntry()
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 184 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildNameCopyPopupEntry()
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 193 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
buildPopupHeader()
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 174 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildPositionCopyEntry()
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 234 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNENet::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildSelectionPopupEntry()
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 203 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShapePopupOptions()
void GUIGlObject::buildShapePopupOptions (GUIMainWindow & app, GUIGLObjectPopupMenu * ret, const std::string & type) protected inherited
build basic shape popup options. Used to unify pop-ups menu in netedit and SUMO-GUI
Definition at line 277 of file GUIGlObject.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
Referenced by GUIPointOfInterest::getPopUpMenu(), GNEPOI::getPopUpMenu(), and GNEPOILane::getPopUpMenu().
buildShowManipulatorPopupEntry()
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 246 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
buildShowParamsPopupEntry()
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 216 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIGlObject::buildAdditionalsPopupOptions(), GUIGlObject::buildShapePopupOptions(), GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GNECrossing::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNELane::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIParkingArea::getPopUpMenu(), GNEConnection::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GNEPoly::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUILane::getPopUpMenu(), and GNEAdditional::getPopUpMenu().
buildShowTypeParamsPopupEntry()
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 225 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIPerson::getPopUpMenu(), and GUIBaseVehicle::getPopUpMenu().
calculateArrivalParams()
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 398 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MSEdge::isTazConnector(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::isSelected(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), and MSBaseVehicle::reroute().
checkActionStep()
bool MSVehicle::checkActionStep (const SUMOTime t) inherited
Returns whether the vehicle is supposed to take action in the current simulation step Updates myActionStep and myLastActionTime in case that the current simstep is an action step.
Parameters
[in] t
Definition at line 1604 of file MSVehicle.cpp.
References MSVehicle::isActionStep(), MSVehicle::myActionStep, and MSVehicle::myLastActionTime.
Referenced by MSVehicle::planMove().
checkLinkLeader()
void MSVehicle::checkLinkLeader (const MSLink * link, const MSLane * lane, double seen, DriveProcessItem *const lastLink, double & v, double & vLinkPass, double & vLinkWait, bool & setRequest, bool isShadowLink = false) const protected inherited
checks for link leaders on the given link
Definition at line 2159 of file MSVehicle.cpp.
References MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSLeaderInfo::addLeader(), DEBUG_COND, MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), MSLink::getInternalLaneBefore(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSVehicle::getLatOffset(), MSLink::getLeaderInfo(), MSLane::getLogicalPredecessorLane(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), MSLink::getViaLaneOrLane(), MSGlobals::gLateralResolution, MSLink::isLeader(), MAX2(), MIN2(), MSVehicle::myLane, MSVehicle::DriveProcessItem::mySetRequest, MSVehicle::DriveProcessItem::myVLinkWait, MSLink::passedJunction(), SIMTIME, SUMO_const_haltingSpeed, and MSLeaderInfo::toString().
Referenced by MSVehicle::estimateLeaveSpeed(), and MSVehicle::planMoveInternal().
checkRewindLinkLanes()
void MSVehicle::checkRewindLinkLanes (const double lengthsInFront, DriveItemVector & lfLinks) const protected inherited
Todo:
: documentation
XXX backward compatibility: why should partial occupators be treated differently here? XXX MAX2 redundant?
XXX spaceTillLastStanding should already be covered by getPartialOccupatorEnd()
XXX why not check BRAKELIGHT?
Definition at line 3229 of file MSVehicle.cpp.
References ACCEL2SPEED, MSVehicle::DriveProcessItem::availableSpace, MSCFModel::brakeGap(), DEBUG_COND, MSVehicle::getBackPositionOnLane(), MSLane::getBruttoVehLenSum(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSLink::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLastAnyVehicle(), MSVehicle::getLateralPositionOnLane(), MSVehicle::DriveProcessItem::getLeaveSpeed(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLink::getParallelLink(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpaceTillLastStanding(), MSVehicle::getSpeed(), MSLane::getVehicleNumber(), MSBaseVehicle::getVehicleType(), MSLink::getViaLane(), MSLink::getViaLaneOrLane(), MSVehicle::getWaitingTime(), MSGlobals::gUsingInternalLanes, MSVehicle::DriveProcessItem::hadVehicle, MSLink::havePriority(), MSLink::isCont(), MSVehicle::isFrontOnLane(), MSEdge::isInternal(), MSAbstractLaneChangeModel::isOpposite(), MSEdge::isRoundabout(), MSVehicle::keepClear(), LINKSTATE_ALLWAY_STOP, MAX2(), MSVehicle::DriveProcessItem::myArrivalSpeed, MSVehicle::DriveProcessItem::myArrivalTime, MSVehicle::myHaveToWaitOnNextLink, MSVehicle::myInfluencer, MSVehicle::myLane, MSVehicle::DriveProcessItem::myLink, MSVehicle::State::mySpeed, MSVehicle::myState, MSLink::opened(), RandHelper::rand(), MSLink::setApproaching(), MSAbstractLaneChangeModel::setShadowApproachingInformation(), MSVehicle::signalSet(), SIMTIME, and MSVehicle::VEH_SIGNAL_BRAKELIGHT.
Referenced by MSVehicle::planMove().
collisionStopTime()
SUMOTime MSVehicle::collisionStopTime () const inherited
Returns the remaining time a vehicle needs to stop due to a collision. A negative value indicates that the vehicle is not stopping due to a collision (or at all)
Definition at line 1352 of file MSVehicle.cpp.
References MAX2(), MSVehicle::myCollisionImmunity, and MSVehicle::myStops.
Referenced by MSLane::executeMovements(), MSLane::handleCollisionBetween(), and MSVehicle::hasStops().
computeAngle()
double MSVehicle::computeAngle () const inherited
compute the current vehicle angle
Definition at line 1038 of file MSVehicle.cpp.
References Position::angleTo2D(), DEBUG_COND, DEG2RAD, MSLane::geometryPositionAtOffset(), MSVehicle::getBackPosition(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSVehicle::getPosition(), MSVehicle::getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::isParking(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, MSVehicle::myStops, GeomHelper::naviDegree(), RAD2DEG, PositionVector::rotationAtOffset(), and SIMTIME.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), and MSVehicle::getVelocityVector().
computeSeats()
void GUIVehicle::computeSeats (const Position & front, const Position & back, int & requiredSeats) const private
add seats to mySeatPositions and update requiredSeats
Definition at line 666 of file GUIVehicle.cpp.
References Position::distanceTo2D(), GUIBaseVehicle::mySeatPositions, and PositionVector::positionAtOffset2D().
Referenced by drawAction_drawRailCarriages(), and getLeftSideOnEdge().
congested()
bool MSVehicle::congested () const inline inherited
Returns true if vehicle's speed is below 60km/h. This is only relevant on highways. Overtaking on the right is allowed then.
Definition at line 714 of file MSVehicle.h.
References MSVehicle::activateReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::getLaneChangeModel(), MSVehicle::leaveLane(), MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::State::pos(), MSVehicle::setTentativeLaneAndPosition(), MSVehicle::State::speed(), and MSVehicle::updateDriveItems().
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::congested(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), and MSLCM_SL2015::informLeader().
createDevice()
void MSBaseVehicle::createDevice (const std::string & deviceName) inherited
create device of the given type
Definition at line 508 of file MSBaseVehicle.cpp.
References MSDevice_Routing::buildVehicleDevices(), MSBaseVehicle::getDevice(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::hasDevice(), MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, MSMoveReminder::NOTIFICATION_DEPARTED, and MSDevice_Routing::notifyEnter().
Referenced by libsumo::Vehicle::setParameter().
drawAction_drawCarriageClass()
bool GUIVehicle::drawAction_drawCarriageClass (const GUIVisualizationSettings & s, SUMOVehicleShape guiShape, bool asImage) const private virtual
draws the given guiShape if it has distinct carriages/modules and returns true if so
Implements GUIBaseVehicle.
Definition at line 306 of file GUIVehicle.cpp.
References drawAction_drawRailCarriages(), SVS_BUS_FLEXIBLE, SVS_RAIL, SVS_RAIL_CAR, and SVS_RAIL_CARGO.
Referenced by getLeftSideOnEdge().
drawAction_drawLinkItems()
void GUIVehicle::drawAction_drawLinkItems (const GUIVisualizationSettings & s) const virtual
Reimplemented from GUIBaseVehicle.
Definition at line 276 of file GUIVehicle.cpp.
References MSLink::ApproachingVehicleInformation::arrivalTime, GUIBaseVehicle::drawLinkItem(), MSVehicleType::getLength(), MSLane::getShape(), GUIGlObject::getType(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSLink::ApproachingVehicleInformation::leavingTime, MSVehicle::myLFLinkLanes, GUIVisualizationSettings::scale, GUIVisualizationTextSettings::size, UNUSED_PARAMETER, and GUIVisualizationSettings::vehicleName.
Referenced by getAngle().
drawAction_drawPersonsAndContainers()
void GUIVehicle::drawAction_drawPersonsAndContainers (const GUIVisualizationSettings & s) const virtual
Reimplemented from GUIBaseVehicle.
Definition at line 236 of file GUIVehicle.cpp.
References GUIContainer::drawGL(), GUIPerson::drawGL(), GLHelper::drawLine(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), GUIGlObject::getGlID(), GUIBaseVehicle::getSeatPosition(), MSDevice_Transportable::getTransportables(), GUIGlObject::getType(), MSVehicle::myContainerDevice, MSVehicle::myPersonDevice, GUIContainer::setPositionInVehicle(), and GUIPerson::setPositionInVehicle().
Referenced by getAngle().
drawAction_drawRailCarriages()
void GUIVehicle::drawAction_drawRailCarriages (const GUIVisualizationSettings & s, double defaultLength, double carriageGap, int firstPassengerCarriage, bool asImage) const private
Definition at line 547 of file GUIVehicle.cpp.
References RGBColor::changedBrightness(), computeSeats(), Position::distanceTo2D(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), MSLane::geometryPositionAtOffset(), GLHelper::getColor(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getLength(), MSLane::getLength(), getNumPassengers(), getPosition(), getPreviousLane(), GUIGlObject::getType(), MSBaseVehicle::getVehicleType(), GUIBaseVehicle::getVType(), MSVehicleType::getWidth(), M_PI, MSVehicle::myLane, GUIBaseVehicle::mySeatPositions, MSVehicle::myState, MSVehicle::State::pos(), GLHelper::setColor(), SVS_RAIL_CAR, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by drawAction_drawCarriageClass(), and getLeftSideOnEdge().
drawAction_drawVehicleAsBoxPlus()
void GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus () const protected inherited
Definition at line 336 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::getVType().
Referenced by GUIMEVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), and GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsImage()
bool GUIBaseVehicle::drawAction_drawVehicleAsImage (const GUIVisualizationSettings & s, double length = -1) const protected inherited
Definition at line 848 of file GUIBaseVehicle.cpp.
References GUITexturesHelper::drawTexturedBox(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), GUIBaseVehicle::getVType(), MSVehicleType::getWidth(), and GUIVisualizationSettings::vehicleSize.
Referenced by drawAction_drawRailCarriages(), and GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsPoly()
bool GUIBaseVehicle::drawAction_drawVehicleAsPoly (const GUIVisualizationSettings & s) const protected inherited
Definition at line 385 of file GUIBaseVehicle.cpp.
References RGBColor::changedBrightness(), GUIBaseVehicle::drawAction_drawCarriageClass(), GLHelper::drawBoxLine(), GLHelper::drawFilledCircle(), GUIBaseVehicle::drawPoly(), GLHelper::getColor(), MSVehicleType::getGuiShape(), MSVehicleType::getLength(), GUIBaseVehicle::getVType(), MSVehicleType::getWidth(), RGBColor::GREY, GLHelper::setColor(), SVS_ANT, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_BUS_FLEXIBLE, SVS_BUS_TROLLEY, SVS_DELIVERY, SVS_E_VEHICLE, SVS_EMERGENCY, SVS_FIREBRIGADE, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, SVS_PASSENGER_WAGON, SVS_PEDESTRIAN, SVS_POLICE, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_1TRAILER, SVS_TRUCK_SEMITRAILER, SVS_UNKNOWN, and vehiclePoly_PassengerCarBody.
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleAsTrianglePlus()
void GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus () const protected inherited
Definition at line 351 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), MSVehicleType::getLength(), and GUIBaseVehicle::getVType().
Referenced by GUIBaseVehicle::drawOnPos().
drawAction_drawVehicleBlinker()
void GUIVehicle::drawAction_drawVehicleBlinker (double length) const virtual
Reimplemented from GUIBaseVehicle.
Definition at line 347 of file GUIVehicle.cpp.
References drawAction_drawBlinker(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MAX2(), MSVehicle::signalSet(), MSVehicle::VEH_SIGNAL_BLINKER_EMERGENCY, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by drawAction_drawRailCarriages(), and getAngle().
drawAction_drawVehicleBlueLight()
void GUIVehicle::drawAction_drawVehicleBlueLight () const inline virtual
Reimplemented from GUIBaseVehicle.
Definition at line 387 of file GUIVehicle.cpp.
References GLHelper::drawFilledCircle(), MSVehicle::signalSet(), and MSVehicle::VEH_SIGNAL_EMERGENCY_BLUE.
Referenced by getAngle().
drawAction_drawVehicleBrakeLight()
void GUIVehicle::drawAction_drawVehicleBrakeLight (double length, bool onlyOne = false) const inline virtual
Reimplemented from GUIBaseVehicle.
Definition at line 366 of file GUIVehicle.cpp.
References GLHelper::drawFilledCircle(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MSVehicle::signalSet(), and MSVehicle::VEH_SIGNAL_BRAKELIGHT.
Referenced by drawAction_drawRailCarriages(), and getAngle().
drawBestLanes()
void GUIVehicle::drawBestLanes () const virtual
Draws the vehicle's best lanes.
Reimplemented from GUIBaseVehicle.
Definition at line 462 of file GUIVehicle.cpp.
References GLHelper::drawBoxLines(), GLHelper::drawLine(), PositionVector::length(), MFXMutex::lock(), MAX2(), PositionVector::move2side(), MSVehicle::myBestLanes, GUIBaseVehicle::myLock, and MFXMutex::unlock().
Referenced by getAngle().
drawGL()
void GUIBaseVehicle::drawGL (const GUIVisualizationSettings & s) const virtual inherited
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 1030 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getAngle(), and GUIBaseVehicle::getPosition().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIParkingArea::drawGL(), GUILane::drawGL(), and GUIBaseVehicle::drawGLAdditional().
drawGLAdditional()
void GUIBaseVehicle::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 1036 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawLinkItems(), GUIBaseVehicle::drawBestLanes(), GUIBaseVehicle::drawGL(), GUIBaseVehicle::drawRoute(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), GUIGlObject::getType(), GUIBaseVehicle::hasActiveAddVisualisation(), MSBaseVehicle::isOnRoad(), GUIBaseVehicle::myVehicle, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
drawLinkItem()
void GUIBaseVehicle::drawLinkItem (const Position & pos, SUMOTime arrivalTime, SUMOTime leaveTime, double exagerate) static protected inherited
Definition at line 1069 of file GUIBaseVehicle.cpp.
References GLHelper::drawFilledCircle(), GLHelper::drawText(), RGBColor::GREEN, STEPS2TIME, toString(), Position::x(), and Position::y().
Referenced by drawAction_drawLinkItems().
drawName()
void GUIGlObject::drawName (const Position & pos, const double scale, const GUIVisualizationTextSettings & settings, const double angle = 0) const inherited
draw name of item
Definition at line 329 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIPointOfInterest::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), and GUIBaseVehicle::drawOnPos().
drawOnPos()
void GUIBaseVehicle::drawOnPos (const GUIVisualizationSettings & s, const Position & pos, const double angle) const inherited
Draws the object on the specified position with the specified angle.
Parameters
[in] s The settings for the current view (may influence drawing)
[in] pos The position to draw the vehicle on
[in] angle The drawing angle of the vehicle
Definition at line 867 of file GUIBaseVehicle.cpp.
References GUIVisualizationTextSettings::color, GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawPersonsAndContainers(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), GUIBaseVehicle::drawAction_drawVehicleBlinker(), GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawAction_drawVehicleBrakeLight(), GUIVisualizationSettings::drawLaneChangePreference, GUIVisualizationSettings::drawMinGap, GUIGlObject::drawName(), GLHelper::drawOutlineCircle(), GLHelper::drawText(), MSBaseVehicle::getDevice(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), SUMOVehicle::getLane(), MSVehicleType::getMinGap(), MSBaseVehicle::getParameter(), SUMOVehicle::getPosition(), MSDevice_BTreceiver::getRange(), GUIGlObject::getType(), GUIBaseVehicle::getVType(), GLO_MAX, SUMOVehicleParameter::line, M_PI, MIN2(), GUIBaseVehicle::mySeatPositions, GUIBaseVehicle::myVehicle, GUIVisualizationSettings::personName, RAD2DEG, GUIVisualizationSettings::scale, GUIBaseVehicle::setColor(), GUIVisualizationTextSettings::show, GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationTextSettings::size, SVS_ANT, SVS_BICYCLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGL(), and GUIEdge::drawMesoVehicles().
drawOutsideNetwork()
void GUIVehicle::drawOutsideNetwork (bool add) protected virtual
register vehicle for drawing while outside the network
Reimplemented from MSVehicle.
Definition at line 790 of file GUIVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), GUIMainWindow::getActiveView(), GUIMainWindow::getInstance(), GUIBaseVehicle::myAdditionalVisualizations, GUISUMOAbstractView::removeAdditionalGLVisualisation(), and GUIBaseVehicle::VO_DRAW_OUTSIDE_NETWORK.
Referenced by getLeftSideOnEdge().
drawPoly()
void GUIBaseVehicle::drawPoly (double * poses, double offset) static protected inherited
Definition at line 369 of file GUIBaseVehicle.cpp.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly().
drawRoute()
void GUIBaseVehicle::drawRoute (const GUIVisualizationSettings & s, int routeNo, double darken) const inherited
Chooses the route to draw and draws it, darkening it as given.
Parameters
[in] s The visualisation settings, needed to determine the vehicle's color
[in] routeNo The route to show (0: the current, >0: prior)
[in] darken The amount to darken the route by
Definition at line 1191 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawRouteHelper(), MSBaseVehicle::getRoute(), MSDevice_Vehroutes::getRoute(), GUIBaseVehicle::myRoutes, GUIBaseVehicle::myVehicle, and GUIBaseVehicle::setColor().
Referenced by GUIBaseVehicle::drawGLAdditional().
drawRouteHelper()
void GUIVehicle::drawRouteHelper (const GUIVisualizationSettings & s, const MSRoute & r) const virtual
Draws the route.
Parameters
[in] r The route to draw
Implements GUIBaseVehicle.
Definition at line 497 of file GUIVehicle.cpp.
References MSRoute::begin(), GUIVisualizationTextSettings::color, GLHelper::drawBoxLines(), GLHelper::drawText(), MSRoute::end(), MSVehicle::getBestLanesContinuation(), GUIVisualizationSizeSettings::getExaggeration(), GUILane::getShape(), GUILane::getShapeLengths(), GUILane::getShapeRotations(), MSBaseVehicle::getVClass(), MSBaseVehicle::myRoute, MSVehicle::myStops, GUIVisualizationSettings::scale, GUIVisualizationTextSettings::size, MSRoute::size(), time2string(), toString(), GUIVisualizationSettings::vehicleName, and GUIVisualizationSettings::vehicleSize.
Referenced by getAngle().
enterLaneAtInsertion()
void MSVehicle::enterLaneAtInsertion (MSLane * enteredLane, double pos, double speed, double posLat, MSMoveReminder::Notification notification) inherited
Update when the vehicle enters a new lane in the emit step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] pos The position the vehicle was inserted into the lane
[in] speed The speed with which the vehicle was inserted into the lane
[in] posLat The lateral position the vehicle was inserted into the lane
[in] notification The cause of insertion (i.e. departure, teleport, parking)
Definition at line 3566 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSBaseVehicle::addReminder(), MSVehicle::computeAngle(), DEBUG_COND, DELTA_T, MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSBaseVehicle::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, Position::INVALID, MSAbstractLaneChangeModel::isOpposite(), M_PI, MSVehicle::myAmOnNet, MSVehicle::myAngle, MSVehicle::State::myBackPos, MSVehicle::myCachedPosition, MSBaseVehicle::myDeparture, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::myLaneChangeModel, MSVehicle::myLastActionTime, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, MSVehicle::myState, MSBaseVehicle::myType, MSBaseVehicle::NOT_YET_DEPARTED, MSMoveReminder::NOTIFICATION_TELEPORT, MSBaseVehicle::onDepart(), SIMTIME, MSAbstractLaneChangeModel::updateShadowLane(), and MSAbstractLaneChangeModel::updateTargetLane().
Referenced by MSVehicle::congested(), and MSLane::incorporateVehicle().
enterLaneAtLaneChange()
void MSVehicle::enterLaneAtLaneChange (MSLane * enteredLane) inherited
Update when the vehicle enters a new lane in the laneChange step.
Parameters
[in] enteredLane The lane the vehicle enters
Definition at line 3516 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSBaseVehicle::addReminder(), MSVehicle::computeAngle(), DEBUG_COND, MSBaseVehicle::getEdge(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::myAmOnNet, MSVehicle::myAngle, MSVehicle::myCachedPosition, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::myLaneChangeModel, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), SIMTIME, toString(), and MSVehicle::updateBestLanes().
Referenced by MSVehicle::congested(), and MSAbstractLaneChangeModel::primaryLaneChanged().
enterLaneAtMove()
bool MSVehicle::enterLaneAtMove (MSLane * enteredLane, bool onTeleporting = false) inherited
Update when the vehicle enters a new lane in the move step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] onTeleporting Whether the lane was entered while being teleported
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 3478 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSLane::getEdge(), Named::getID(), MSVehicle::hasArrived(), Position::INVALID, MSEdge::isInternal(), MSVehicle::myAmOnNet, MSVehicle::myCachedPosition, MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::myLastBestLanesEdge, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSVehicle::myState, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_TELEPORT, and SUMOVehicleParameter::via.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), MSVehicle::congested(), libsumo::Vehicle::moveTo(), and MSVehicle::processLaneAdvances().
estimateLeaveSpeed()
double MSVehicle::estimateLeaveSpeed (const MSLink *const link, const double vLinkPass) const inline protected inherited
estimate leaving speed when accelerating across a link
Definition at line 1833 of file MSVehicle.h.
References MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicle::checkLinkLeader(), MSCFModel::estimateSpeedAfterDistance(), MSVehicle::getBackLane(), MSVehicle::getBackPosition(), MSVehicleType::getCarFollowModel(), MSVehicle::getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSVehicle::ignoreRed(), MSVehicle::keepClear(), MIN2(), and MSVehicle::updateState().
Referenced by MSVehicle::planMoveInternal().
executeMove()
bool MSVehicle::executeMove () inherited
Executes planned vehicle movements with regards to right-of-way.
This method goes through all DriveProcessItems in myLFLinkLanes in order to find a speed that is safe for all upcoming links.
Using this speed the position is updated and the vehicle is moved to the next lane (myLane is updated) if the end of the current lane is reached (this may happen multiple times in this method)
The vehicle also sets the lanes it is in-lapping into and informs them about it.
Returns
Whether the vehicle has moved to the next edge
Definition at line 2819 of file MSVehicle.cpp.
References ACCEL2SPEED, MSAbstractLaneChangeModel::changedToOpposite(), MSVehicle::computeAngle(), DEBUG_COND, DELTA_T, gDebugFlag1, MSVehicle::getBackLane(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getLength(), MSLane::getOpposite(), MSLane::getOppositePos(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSGlobals::gSemiImplicitEulerUpdate, MSVehicle::hasArrived(), Position::INVALID, MSEdge::isVaporizing(), MAX2(), MSVehicle::myAcceleration, MSVehicle::myActionStep, MSVehicle::myAngle, MSVehicle::State::myBackPos, MSVehicle::myCachedPosition, MSVehicle::myCollisionImmunity, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myLastCoveredDist, MSVehicle::myLFLinkLanes, MSVehicle::myNextDriveItem, MSVehicle::State::myPos, MSVehicle::State::mySpeed, MSVehicle::myState, MSBaseVehicle::myType, NUMERICAL_EPS, POSITION_EPS, MSAbstractLaneChangeModel::prepareStep(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processTraCISpeedControl(), MSVehicleControl::registerEmergencyStop(), MSVehicle::removeApproachingInformation(), MSVehicle::setBlinkerInformation(), MSVehicle::setBrakingSignals(), MSVehicle::setEmergencyBlueLight(), SIMTIME, SPEED2ACCEL, SVC_EMERGENCY, time2string(), toString(), TS, MSVehicle::updateBestLanes(), MSVehicle::updateFurtherLanes(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicle::updateState(), MSAbstractLaneChangeModel::updateTargetLane(), MSVehicle::updateTimeLoss(), MSVehicle::updateWaitingTime(), MSVehicle::workOnMoveReminders(), and WRITE_WARNING.
Referenced by MSLane::executeMovements().
fixPosition()
void MSVehicle::fixPosition () inherited
repair errors in vehicle position after changing between internal edges
Definition at line 4073 of file MSVehicle.cpp.
References MSVehicle::getLaneChangeModel(), MSGlobals::gLaneChangeDuration, MSVehicle::State::myPosLat, and MSVehicle::myState.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver().
getAcceleration()
double MSVehicle::getAcceleration () const inline virtual inherited
Returns the vehicle's acceleration in m/s (this is computed as the last step's mean acceleration in case that a stop occurs within the middle of the time-step)
Returns
The acceleration
Reimplemented from MSBaseVehicle.
Definition at line 499 of file MSVehicle.h.
References MSVehicle::myAcceleration.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLCM_SL2015::commitManoeuvre(), MSDevice_SSM::estimateConflictTimes(), getColorValue(), getParameterWindow(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSBatteryExport::write().
getAccumulatedWaitingSeconds()
double MSVehicle::getAccumulatedWaitingSeconds () const inline inherited
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 670 of file MSVehicle.h.
References MSVehicle::getAccumulatedWaitingTime(), and STEPS2TIME.
Referenced by libsumo::Vehicle::getAccumulatedWaitingTime(), getColorValue(), getParameterWindow(), and MSVehicle::keepClear().
getAccumulatedWaitingTime()
SUMOTime MSVehicle::getAccumulatedWaitingTime () const inline virtual inherited
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
Returns
The time the vehicle was standing within the configured memory interval
Implements SUMOVehicle.
Definition at line 650 of file MSVehicle.h.
References MSVehicle::WaitingTimeCollector::cumulatedWaitingTime(), MSGlobals::gWaitingTimeMemory, and MSVehicle::myWaitingTimeCollector.
Referenced by MSVehicle::getAccumulatedWaitingSeconds().
getActionStepLength()
SUMOTime MSVehicle::getActionStepLength () const inline inherited
Returns the vehicle's action step length in millisecs, i.e. the interval between two action points.
Returns
The current action step length in ms.
Definition at line 508 of file MSVehicle.h.
References MSVehicleType::getActionStepLength(), and MSBaseVehicle::myType.
Referenced by MSLeaderInfo::getSubLanes(), MSVehicle::isActionStep(), MSVehicle::processNextStop(), and libsumo::Vehicle::setActionStepLength().
getActionStepLengthSecs()
double MSVehicle::getActionStepLengthSecs () const inline inherited
Returns the vehicle's action step length in secs, i.e. the interval between two action points.
Returns
The current action step length in s.
Definition at line 516 of file MSVehicle.h.
References MSVehicleType::getActionStepLengthSecs(), and MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitManoeuvre(), MSCFModel::freeSpeed(), MSLeaderInfo::getSubLanes(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::keepLatGap(), MSCFModel_Krauss::moveHelper(), MSCFModel::moveHelper(), MSLCM_SL2015::setOwnState(), MSCFModel_Krauss::stopSpeed(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
getAngle()
double GUIVehicle::getAngle () const inline virtual
Return current angle.
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 88 of file GUIVehicle.h.
References drawAction_drawLinkItems(), drawAction_drawPersonsAndContainers(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBlueLight(), drawAction_drawVehicleBrakeLight(), drawBestLanes(), drawRouteHelper(), MSVehicle::getAngle(), getColorValue(), getLastLaneChangeOffset(), getParameterWindow(), getTypeParameterWindow(), isSelected(), and selectBlockingFoes().
getArrivalPos()
virtual double MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 269 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
getBackLane()
const MSLane * MSVehicle::getBackLane () const protected inherited
Definition at line 3044 of file MSVehicle.cpp.
References MSVehicle::myFurtherLanes, and MSVehicle::myLane.
Referenced by MSVehicle::estimateLeaveSpeed(), and MSVehicle::executeMove().
getBackPosition()
const Position MSVehicle::getBackPosition () const protected inherited
Definition at line 1079 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::geometryPositionAtOffset(), MSVehicle::getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, MSBaseVehicle::myType, and toString().
Referenced by MSVehicle::computeAngle(), MSVehicle::estimateLeaveSpeed(), MSVehicle::getBoundingBox(), and MSVehicle::getBoundingPoly().
getBackPositionOnLane() [1/2]
double MSVehicle::getBackPositionOnLane (const MSLane * lane) const virtual inherited
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Note
It is assumed that this function is only called for a vehicle that has a relation to the lane which makes it 'directly' relevant for car-following behavior on that lane, i.e., either it occupies part of the lanes surface (regular or partial vehicle for the lane), or (for the sublane model) it issued a maneuver reservation for a lane change.
Implements SUMOVehicle.
Definition at line 3120 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicle::getFurtherLanes(), MSAbstractLaneChangeModel::getFurtherTargetLanes(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSVehicle::State::myBackPos, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::myState, MSBaseVehicle::myType, SIMTIME, time2string(), toString(), and WRITE_WARNING.
Referenced by MSVehicle::adaptToLeaders(), MSLaneChangerSublane::checkChangeSublane(), MSLaneChangerSublane::checkChangeToNewLane(), MSVehicle::checkRewindLinkLanes(), MSDevice_SSM::classifyEncounter(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSPModel_Striping::moveInDirectionOnLane(), MSLane::vehicle_position_sorter::operator()(), MSLane::vehicle_natural_position_sorter::operator()(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), and MSLane::safeInsertionSpeed().
getBackPositionOnLane() [2/2]
double MSVehicle::getBackPositionOnLane () const inline inherited
Get the vehicle's position relative to its current lane.
Returns
The back position of the vehicle (in m from the current lane's begin)
Definition at line 431 of file MSVehicle.h.
References MSVehicle::myLane.
Referenced by MSVehicle::getBackPosition(), MSVehicle::getLastStepDist(), and MSVehicle::getPositionOnLane().
getBestLaneOffset()
int MSVehicle::getBestLaneOffset () const inherited
Definition at line 4055 of file MSVehicle.cpp.
References MSVehicle::myBestLanes.
Referenced by MSLCM_LC2013::changed(), MSLCM_SL2015::changed(), and getColorValue().
getBestLanes()
const std::vector< MSVehicle::LaneQ > & MSVehicle::getBestLanes () const inherited
Returns the description of best lanes to use in order to continue the route.
Returns
The LaneQ for all lanes of the current edge
Definition at line 3686 of file MSVehicle.cpp.
References MSVehicle::myBestLanes.
Referenced by MSLane::appropriate(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeHelper(), libsumo::Vehicle::getBestLanes(), MSEdge::getDepartLane(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
getBestLanesContinuation() [1/2]
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation () const inherited
Returns the best sequence of lanes to continue the route starting at myLane.
Returns
The bestContinuations of the LaneQ for myLane (see LaneQ)
Definition at line 4026 of file MSVehicle.cpp.
References MSVehicle::myBestLanes, and MSVehicle::myEmptyLaneVector.
Referenced by MSLane::appropriate(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), drawRouteHelper(), MSLane::executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSLane::getCriticalLeader(), MSVehicle::getLeader(), MSLaneChangerSublane::getLeaders(), libsumo::Vehicle::getNextTLS(), MSLane::getOppositeLeader(), MSVehicle::getPositionAlongBestLanes(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSVehicle::planMoveInternal(), MSVehicle::setBlinkerInformation(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateBestLanes(), and MSVehicle::updateDriveItems().
getBestLanesContinuation() [2/2]
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation (const MSLane *const l) const inherited
Returns the best sequence of lanes to continue the route starting at the given lane.
Returns
The bestContinuations of the LaneQ for the given lane (see LaneQ)
Definition at line 4035 of file MSVehicle.cpp.
References MSLane::getEdge(), MSLane::getLinkCont(), MSEdge::isInternal(), MSVehicle::myBestLanes, and MSVehicle::myEmptyLaneVector.
getBoundingBox()
PositionVector MSVehicle::getBoundingBox () const inherited
get bounding rectangle
Definition at line 4565 of file MSVehicle.cpp.
References PositionVector::append(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, POSITION_EPS, and PositionVector::reverse().
Referenced by MSLane::detectCollisions(), drawAction_drawPersonsAndContainers(), MSVehicle::getBoundingPoly(), and MSVehicle::signalSet().
getBoundingPoly()
PositionVector MSVehicle::getBoundingPoly () const inherited
get bounding polygon
Definition at line 4578 of file MSVehicle.cpp.
References MSVehicle::getBackPosition(), MSVehicle::getBoundingBox(), MSVehicleType::getGuiShape(), MSVehicle::getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, PositionVector::scaleRelative(), SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, and SVS_PASSENGER_WAGON.
Referenced by MSLane::detectCollisions(), drawAction_drawPersonsAndContainers(), and MSVehicle::signalSet().
getCarFollowModel()
const MSCFModel& MSVehicle::getCarFollowModel () const inline inherited
Returns the vehicle's car following model definition.
This is simply a wrapper around the vehicle type's car-following model retrieval for a shorter access.
Returns
The vehicle's car following model definition
Definition at line 882 of file MSVehicle.h.
References MSVehicleType::getCarFollowModel(), and MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSPModel_Striping::addCrossingVehs(), MSCriticalFollowerDistanceInfo::addFollower(), MSVehicle::addStop(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSLane::checkForPedestrians(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), MSDevice_SSM::estimateConflictTimes(), MSVehicle::estimateLeaveSpeed(), MSVehicle::executeMove(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getMissingRearGap(), MSLaneChanger::getRealLeader(), MSVehicle::getRerouteOrigin(), MSVehicle::getSafeFollowSpeed(), getTypeParameterWindow(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), selectBlockingFoes(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
getCarFollowVariables()
MSCFModel::VehicleVariables* MSVehicle::getCarFollowVariables () const inline inherited
Returns the vehicle's car following model variables.
Returns
The vehicle's car following model variables
Definition at line 891 of file MSVehicle.h.
References MSVehicle::myCFVariables.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_SmartSK::_vsafe(), MSCFModel_PWag2009::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_PWag2009::moveHelper(), MSCFModel_Kerner::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel_IDM::moveHelper(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
getCenteringBoundary()
Boundary GUIBaseVehicle::getCenteringBoundary () const virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 327 of file GUIBaseVehicle.cpp.
References Boundary::add(), MSVehicleType::getLength(), GUIBaseVehicle::getPosition(), MSBaseVehicle::getVehicleType(), Boundary::grow(), and GUIBaseVehicle::myVehicle.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
getCenterOnEdge()
double MSVehicle::getCenterOnEdge (const MSLane * lane = 0) const inherited
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between center of vehicle and ride side of edge
Definition at line 4343 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getCenterOnEdge(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::getWidth(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPosLat, and MSVehicle::myState.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::computeSpeedGain(), MSLane::detectCollisionBetween(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getRightSideOnEdge(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::prepareStep(), and MSLCM_SL2015::updateCFRelated().
getChosenSpeedFactor()
double MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 377 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by GUIMEVehicle::getParameterWindow(), getParameterWindow(), and libsumo::Vehicle::getSpeedFactor().
getCO2Emissions()
double MSVehicle::getCO2Emissions () const inherited
Returns CO2 emission of the current state.
Returns
The current CO2 emission
Definition at line 4138 of file MSVehicle.cpp.
References PollutantsInterface::CO2, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by libsumo::Vehicle::getCO2Emission(), getColorValue(), getParameterWindow(), and MSVehicle::nextStopDist().
getCOEmissions()
double MSVehicle::getCOEmissions () const inherited
Returns CO emission of the current state.
Returns
The current CO emission
Definition at line 4144 of file MSVehicle.cpp.
References PollutantsInterface::CO, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by libsumo::Vehicle::getCOEmission(), getColorValue(), getParameterWindow(), and MSVehicle::nextStopDist().
getColorValue()
double GUIVehicle::getColorValue (int activeScheme) const virtual
gets the color value according to the current scheme index
Implements GUIBaseVehicle.
Definition at line 399 of file GUIVehicle.cpp.
References MSVehicle::getAcceleration(), MSVehicle::getAccumulatedWaitingSeconds(), MSVehicle::getBestLaneOffset(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSBaseVehicle::getDepartDelay(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), GUIGlObject::getGlID(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getLane(), getLastLaneChangeOffset(), MSVehicle::getNOxEmissions(), MSBaseVehicle::getNumberReroutes(), MSVehicle::getPMxEmissions(), MSVehicle::getSpeed(), MSVehicle::getTimeGapOnLane(), MSVehicle::getTimeLossSeconds(), MSLane::getVehicleMaxSpeed(), MSVehicle::getWaitingSeconds(), GLO_VEHICLE, gSelected, MSVehicle::isActionStep(), MSVehicle::isActive(), GUISelectedStorage::isSelected(), SIMSTEP, and STEPS2TIME.
Referenced by getAngle().
getContainerNumber()
int MSVehicle::getContainerNumber () const inherited
Returns the number of containers.
Returns
The number of contaiers on-board
Definition at line 4253 of file MSVehicle.cpp.
References SUMOVehicleParameter::containerNumber, MSVehicle::myContainerDevice, MSBaseVehicle::myParameter, and MSDevice_Transportable::size().
Referenced by getParameterWindow(), MSTransportableControl::loadAnyWaiting(), MSVehicle::nextStopDist(), MSVehicle::processNextStop(), and MSXMLRawOut::writeVehicle().
getContainers()
const std::vector< MSTransportable * > & MSVehicle::getContainers () const inherited
retrieve riding containers
Definition at line 4237 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), MSVehicle::myContainerDevice, and MSVehicle::myEmptyTransportableVector.
Referenced by MSVehicle::nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
getCurrentRouteEdge()
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 192 of file MSBaseVehicle.h.
References MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
Referenced by MSDevice_SSM::findSurroundingVehicles(), libsumo::Vehicle::getDistance(), and libsumo::Vehicle::moveToXY().
getDeltaPos()
double MSVehicle::getDeltaPos (double accel) inherited
calculates the distance covered in the next integration step given an acceleration and assuming the current velocity. (gives different results for different integration methods, e.g., euler vs. ballistic)
Parameters
[in] accel the assumed acceleration
Returns
distance covered in next integration step
Definition at line 2248 of file MSVehicle.cpp.
References ACCEL2SPEED, MSGlobals::gSemiImplicitEulerUpdate, MAX2(), MSVehicle::State::mySpeed, MSVehicle::myState, and SPEED2DIST.
Referenced by MSVehicle::updateState().
getDepartDelay()
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 253 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by GUIMEVehicle::getColorValue(), getColorValue(), GUIMEVehicle::getParameterWindow(), and getParameterWindow().
getDepartPos()
double MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 261 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by libsumo::Vehicle::getDistance().
getDeparture()
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 248 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay(), and MSVehicle::Influencer::postProcessRemoteControl().
getDevice()
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 447 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), GUIBaseVehicle::drawOnPos(), MSVehicle::resumeFromStopping(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
getDeviceParameter()
std::string MSBaseVehicle::getDeviceParameter (const std::string & deviceName, const std::string & key) const inherited
try to retrieve the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 527 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by libsumo::Vehicle::getParameter().
getDevices()
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 302 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
getDistanceToPosition()
double MSVehicle::getDistanceToPosition (double destPos, const MSEdge * destEdge) const inherited
Compute distance that will be covered, if the vehicle moves to a given position on its route, starting at its current position.
Parameters
destPos position on the destination edge that shall be reached
destEdge destination edge that shall be reached
Returns
distance from the vehicles current position to the destination position, or a near infinite real value if the destination position is not contained within the vehicles route or the vehicle is not active
Definition at line 4081 of file MSVehicle.cpp.
References MSRoute::getDistanceBetween(), MSLane::getEdge(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSVehicle::isOnRoad(), MSBaseVehicle::myCurrEdge, MSVehicle::myLane, and MSBaseVehicle::myRoute.
Referenced by MSVehicle::Influencer::implicitDeltaPosRemote(), MSVehicle::Influencer::implicitSpeedRemote(), and MSVehicle::nextStopDist().
getEdge()
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 149 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), libsumo::Vehicle::getDrivingDistance2D(), MSVehicle::getLatOffset(), GUIMEVehicle::getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), MSBaseVehicle::getVClass(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MELoop::teleportVehicle().
getElectricityConsumption()
double MSVehicle::getElectricityConsumption () const inherited
Returns electricity consumption of the current state.
Returns
The current electricity consumption
Definition at line 4174 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::ELEC, MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by getColorValue(), libsumo::Vehicle::getElectricityConsumption(), getParameterWindow(), and MSVehicle::nextStopDist().
getFuelConsumption()
double MSVehicle::getFuelConsumption () const inherited
Returns fuel consumption of the current state.
Returns
The current fuel consumption
Definition at line 4168 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::FUEL, MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by getColorValue(), libsumo::Vehicle::getFuelConsumption(), getParameterWindow(), and MSVehicle::nextStopDist().
getFullName()
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 108 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
getFurtherLanes()
const std::vector<MSLane*>& MSVehicle::getFurtherLanes () const inline inherited
Definition at line 780 of file MSVehicle.h.
References MSVehicle::myFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSAbstractLaneChangeModel::updateShadowLane(), and MSAbstractLaneChangeModel::updateTargetLane().
getFurtherLanesPosLat()
const std::vector<double>& MSVehicle::getFurtherLanesPosLat () const inline inherited
Definition at line 784 of file MSVehicle.h.
References MSVehicle::myFurtherLanesPosLat, and MSVehicle::onFurtherEdge().
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
getGlID()
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 120 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNEEdge::addConnection(), GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildRouteProbe(), GUIGlObject::buildSelectionPopupEntry(), GNEAdditionalHandler::buildVaporizer(), GUINet::createTLWrapper(), GNENet::deleteConnection(), GNENet::deleteCrossing(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), drawAction_drawPersonsAndContainers(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEInternalLane::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GUIPointOfInterest::drawGL(), GNEConnection::drawGL(), GNEVariableSpeedSign::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GNERerouter::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GUIEdge::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), GNEJunction::getColorValue(), GNEPOI::getGlID(), GNEPOILane::getGlID(), GNEPoly::getGlID(), GUIEdge::getIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUILane::isLaneOrEdgeSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), isSelected(), GUIPerson::isSelected(), GNEViewParent::isSelected(), GUILane::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNEViewNet::onCmdClearConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEViewNet::onCmdResetConnections(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEViewNet::onCmdSmoothEdges(), GNEViewNet::onCmdSmoothEdgesElevation(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onCmdStraightenEdgesElevation(), GNEViewNet::onLeftBtnPress(), GNEAdditionalFrame::removeAdditional(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GNENet::replaceIncomingEdge(), selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), GNELane::setLaneColor(), GUIBaseVehicle::~GUIBaseVehicle(), GUIGlObject::~GUIGlObject(), and GUIPerson::~GUIPerson().
getHarmonoise_NoiseEmissions()
double MSVehicle::getHarmonoise_NoiseEmissions () const inherited
Returns noise emissions of the current state.
Returns
The noise produced
Definition at line 4180 of file MSVehicle.cpp.
References HelpersHarmonoise::computeNoise(), MSVehicleType::getEmissionClass(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by getColorValue(), libsumo::Vehicle::getNoiseEmission(), getParameterWindow(), and MSVehicle::nextStopDist().
getHCEmissions()
double MSVehicle::getHCEmissions () const inherited
Returns HC emission of the current state.
Returns
The current HC emission
Definition at line 4150 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), PollutantsInterface::HC, MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by getColorValue(), libsumo::Vehicle::getHCEmission(), getParameterWindow(), and MSVehicle::nextStopDist().
getID()
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 121 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChangerSublane::abortLCManeuver(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), MSBaseVehicle::addContainer(), MSPModel_Striping::addCrossingVehs(), MSLCM_SL2015::addLCSpeedAdvice(), MSBaseVehicle::addPerson(), MSVehicle::addTraciStopAtStoppingPlace(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), libsumo::Vehicle::changeTarget(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSVehicle::computeAngle(), MSLCM_SL2015::computeSpeedLat(), MSDevice_SSM::computeSSMs(), MSLaneChanger::continueChange(), MSLaneChangerSublane::continueChangeSublane(), MSLCM_SL2015::decideDirection(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSLane::detectPedestrianJunctionCollision(), MSDevice_SSM::Encounter::Encounter(), MSCalibrator::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLaneChanger::findCandidate(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), MSLane::getPartialBehind(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSAbstractLaneChangeModel::getShadowLane(), MSBaseVehicle::getSingularType(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSVehicle::ignoreRed(), MSLCM_LC2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicle::lateralDistanceToLane(), MSVehicle::leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSVehicle::onRemovalFromNet(), MSLaneChangerSublane::outputLCStarted(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLCM_SL2015::prepareStep(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::removePassedDriveItems(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetManeuverReservation(), MSLane::resetPartialOccupation(), libsumo::Vehicle::resume(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), MSCalibrator::scheduleRemoval(), selectBlockingFoes(), MSVehicle::setAngle(), MSAbstractLaneChangeModel::setManeuverDist(), MSLane::setManeuverReservation(), MSLCM_SL2015::setOwnState(), MSLane::setPartialOccupation(), libsumo::Helper::setRemoteControlled(), libsumo::Vehicle::setRoute(), libsumo::Vehicle::setRouteID(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSVehicle::updateBestLanes(), MSVehicle::updateDriveItems(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicle::updateState(), MSAbstractLaneChangeModel::updateTargetLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), and MSXMLRawOut::writeVehicle().
getImpatience()
double MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 440 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToImpatience, MAX2(), and MIN2().
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), getParameterWindow(), MSLCM_LC2013::informFollower(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::processLinkAproaches(), and selectBlockingFoes().
getInfluencer() [1/2]
MSVehicle::Influencer & MSVehicle::getInfluencer () inherited
Returns the velocity/lane influencer.
If no influencer was existing before, one is built, first
Returns
Reference to this vehicle's speed influencer
Definition at line 4812 of file MSVehicle.cpp.
References MSVehicle::myInfluencer.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), libsumo::Vehicle::changeLane(), MSLaneChanger::changeOpposite(), libsumo::Vehicle::changeSublane(), MSAbstractLaneChangeModel::checkTraCICommands(), MSLane::detectCollisionBetween(), libsumo::Vehicle::getLanechangeMode(), libsumo::Vehicle::getRoutingMode(), libsumo::Vehicle::getSpeedMode(), MSLane::handleCollisionBetween(), MSVehicle::influenceChangeDecision(), MSLCM_SL2015::keepLatGap(), TraCIServerAPI_Vehicle::processSet(), libsumo::Helper::setRemoteControlled(), libsumo::Vehicle::setSignals(), libsumo::Vehicle::slowDown(), and MSLaneChangerSublane::startChangeSublane().
getInfluencer() [2/2]
const MSVehicle::Influencer * MSVehicle::getInfluencer () const inherited
Definition at line 4821 of file MSVehicle.cpp.
References MSVehicle::myInfluencer.
getLane()
MSLane* MSVehicle::getLane () const inline virtual inherited
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 564 of file MSVehicle.h.
References MSVehicle::myLane.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeaders(), MSLaneChangerSublane::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLaneChangerSublane::checkChangeToNewLane(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkLinkLeader(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MSLCM_SL2015::computeSpeedGain(), MSAbstractLaneChangeModel::congested(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSAbstractLaneChangeModel::determineTargetLane(), MSVTypeProbe::execute(), MSLane::executeMovements(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSCFModel_IDM::followSpeed(), libsumo::Vehicle::getAllowedSpeed(), getColorValue(), libsumo::Vehicle::getDistance(), libsumo::Vehicle::getDrivingDistance(), MSLane::getFollowersOnConsecutive(), libsumo::Vehicle::getLaneID(), libsumo::Vehicle::getLaneIndex(), MSLink::getLeaderInfo(), MSLaneChangerSublane::getLeaders(), libsumo::Vehicle::getNextTLS(), MSVehicle::getPositionAlongBestLanes(), libsumo::Vehicle::getRoadID(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSAbstractLaneChangeModel::getShadowDirection(), MSVTKExport::getSpeed(), MSLCM_SL2015::getSublaneWidth(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLCM_LC2013::informFollower(), MSLane::integrateNewVehicle(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSJunction::isLeader(), MSLCM_SL2015::keepLatGap(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_IDM::moveHelper(), libsumo::Vehicle::moveTo(), libsumo::Vehicle::moveToXY(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSLCM_SL2015::prepareStep(), TraCIServerAPI_Vehicle::processSet(), MSVehicleTransfer::remove(), MSCalibrator::removePending(), MSLane::removeVehicle(), MSVehicle::setBlinkerInformation(), libsumo::Vehicle::setRoute(), libsumo::Vehicle::setRouteID(), MSLaneChangerSublane::startChangeSublane(), MSCFModel_IDM::stopSpeed(), MSLCM_SL2015::updateCFRelated(), MSLaneChangerSublane::updateChanger(), MSVehicle::updateDriveItems(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::updateShadowLane(), MSAbstractLaneChangeModel::updateTargetLane(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
getLaneChangeModel() [1/2]
MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel () inherited
Definition at line 3674 of file MSVehicle.cpp.
References MSVehicle::myLaneChangeModel.
Referenced by MSLaneChangerSublane::abortLCManeuver(), MSVehicleTransfer::add(), MSLaneChanger::applyTraCICommands(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLaneChangerSublane::checkChangeToNewLane(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::checkTraCICommands(), MSAbstractLaneChangeModel::checkTraCICommands(), MSVehicle::computeAngle(), MSVehicle::congested(), MSLaneChanger::continueChange(), MSLaneChangerSublane::continueChangeSublane(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::fixPosition(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), libsumo::Vehicle::getLaneChangeState(), getLastLaneChangeOffset(), MSVehicle::getLatOffset(), MSLink::getLeaderInfo(), getManeuverDist(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), libsumo::Vehicle::getParameter(), getParameterWindow(), MSVehicle::getPosition(), MSLeaderInfo::getSubLanes(), MSLCM_SL2015::inform(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), MSVehicle::isFrontOnLane(), MSLane::isInsertionSuccess(), MSCFModel_Rail::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), MSLaneChangerSublane::outputLCEnded(), MSLaneChangerSublane::outputLCStarted(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSLaneChanger::registerUnchanged(), MSVehicle::removeApproachingInformation(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), selectBlockingFoes(), MSVehicle::setBlinkerInformation(), libsumo::Vehicle::setParameter(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::updateBestLanes(), MSLaneChangerSublane::updateChanger(), MSLCM_SL2015::updateGaps(), and MSVehicle::updateState().
getLaneChangeModel() [2/2]
const MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel () const inherited
Definition at line 3680 of file MSVehicle.cpp.
References MSVehicle::myLaneChangeModel.
getLaneIndex()
int MSVehicle::getLaneIndex () const inherited
Definition at line 4314 of file MSVehicle.cpp.
References MSLane::getEdge(), MSEdge::getLanes(), and MSVehicle::myLane.
Referenced by MSLane::appropriate(), MSVehicle::influenceChangeDecision(), and MSVehicle::nextStopDist().
getLastActionTime()
SUMOTime MSVehicle::getLastActionTime () const inline inherited
Returns the time of the vehicle's last action point.
Returns
The time of the last action point
Definition at line 524 of file MSVehicle.h.
References MSVehicle::getPosition(), MSVehicle::getPositionAlongBestLanes(), MSVehicle::getSlope(), and MSVehicle::myLastActionTime.
getLastLaneChangeOffset()
double GUIVehicle::getLastLaneChangeOffset () const virtual
Returns the time since the last lane change in seconds.
See also
MSVehicle::myLastLaneChangeOffset
Returns
The time since the last lane change in seconds
Implements GUIBaseVehicle.
Definition at line 685 of file GUIVehicle.cpp.
References MSVehicle::getLaneChangeModel(), and STEPS2TIME.
Referenced by getAngle(), getColorValue(), and getParameterWindow().
getLastStepDist()
double MSVehicle::getLastStepDist () const inline inherited
Get the distance the vehicle covered in the previous timestep.
Returns
The distance covered in the last timestep (in m)
Definition at line 409 of file MSVehicle.h.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::State::lastCoveredDist(), and MSVehicle::myState.
Referenced by MSDevice_SSM::checkConflictEntryAndExit(), and MSDevice_SSM::updatePassedEncounter().
getLateralOverlap() [1/2]
double MSVehicle::getLateralOverlap () const inherited
return the amount by which the vehicle extends laterally outside it's primary lane
Definition at line 4495 of file MSVehicle.cpp.
References MSVehicle::getLateralPositionOnLane().
Referenced by MSLCM_SL2015::checkStrategicChange(), MSVehicle::executeMove(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::planMoveInternal(), and MSAbstractLaneChangeModel::updateShadowLane().
getLateralOverlap() [2/2]
double MSVehicle::getLateralOverlap (double posLat) const inherited
Definition at line 4488 of file MSVehicle.cpp.
References MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MSLane::getWidth(), and MSVehicle::myLane.
getLateralPositionOnLane()
double MSVehicle::getLateralPositionOnLane () const inline virtual inherited
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Reimplemented from MSBaseVehicle.
Definition at line 439 of file MSVehicle.h.
References MSVehicle::getCenterOnEdge(), MSVehicle::getLateralOverlap(), MSVehicle::getLatOffset(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSVehicle::lateralDistanceToLane(), MSVehicle::State::myPosLat, MSVehicle::myState, and MSVehicle::State::posLat().
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLaneChangerSublane::checkChangeToNewLane(), MSLane::checkForPedestrians(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::determineTargetLane(), MSVehicle::executeMove(), MSLane::getCriticalLeader(), libsumo::Vehicle::getLateralLanePosition(), MSVehicle::getLateralOverlap(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), getParameterWindow(), MSVehicle::getPosition(), MSVehicle::getPositionAlongBestLanes(), MSAbstractLaneChangeModel::getShadowLane(), MSLeaderInfo::getSubLanes(), MSLCM_SL2015::keepLatGap(), MSVehicle::lateralDistanceToLane(), MSLane::loadState(), MSPModel_Striping::moveInDirectionOnLane(), MSLane::vehicle_natural_position_sorter::operator()(), MSVehicle::planMove(), MSVehicle::processLinkAproaches(), selectBlockingFoes(), MSVehicle::setAngle(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::validatePosition(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), and MSXMLRawOut::writeVehicle().
getLatOffset()
double MSVehicle::getLatOffset (const MSLane * lane) const inherited
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
Note
This means that latOffset + myPosLat should give the relative shift of the vehicle's center wrt the centerline of the given lane.
Definition at line 4375 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getEdge(), MSLane::getEdge(), MSAbstractLaneChangeModel::getFurtherTargetLanes(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getManeuverDist(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), MSLane::getWidth(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPosLat, MSVehicle::myState, SIMTIME, and toString().
Referenced by MSVehicle::checkLinkLeader(), MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLateralPositionOnLane(), MSLink::getLeaderInfo(), MSLane::getLeadersOnConsecutive(), and MSLane::getPartialBeyond().
getLeader()
std::pair< const MSVehicle *const, double > MSVehicle::getLeader (double dist = 0) const inherited
Returns the leader of the vehicle looking for a fixed distance.
If the distance is not given it is calculated from the brake gap. The gap returned does not include the minGap.
Parameters
dist up to which distance to look for a leader
Returns
The leading vehicle together with the gap; (0, -1) if no leader was found.
Definition at line 4098 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getLeaderOnConsecutive(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MSVehicle::myLane, and MSLane::releaseVehicles().
Referenced by libsumo::Vehicle::getLeader(), MSVehicle::getTimeGapOnLane(), and MSVehicle::nextStopDist().
getLeftSideOnEdge()
double GUIVehicle::getLeftSideOnEdge () const inline
return left vehicle side on current edge
Definition at line 146 of file GUIVehicle.h.
References computeSeats(), drawAction_drawCarriageClass(), drawAction_drawRailCarriages(), drawOutsideNetwork(), getLeftSublaneOnEdge(), getManeuverDist(), getNumPassengers(), getPreviousLane(), MSVehicle::getRightSideOnEdge(), getRightSublaneOnEdge(), getStopInfo(), MSBaseVehicle::getVehicleType(), and MSVehicleType::getWidth().
Referenced by getLeftSublaneOnEdge(), and getParameterWindow().
getLeftSublaneOnEdge()
int GUIVehicle::getLeftSublaneOnEdge () const
Definition at line 824 of file GUIVehicle.cpp.
References MSLane::getEdge(), getLeftSideOnEdge(), MSEdge::getSubLaneSides(), and MSVehicle::myLane.
Referenced by getLeftSideOnEdge(), and getParameterWindow().
getLength()
double MSBaseVehicle::getLength () const inline inherited
Returns the vehicle's length.
Returns
vehicle's length
Definition at line 361 of file MSBaseVehicle.h.
References MSVehicleType::getLength(), and MSBaseVehicle::myType.
Referenced by MSVehicle::addStop(), MSDevice_SSM::checkConflictEntryAndExit(), MSDevice_SSM::classifyEncounter(), MSDevice_SSM::determineConflictPoint(), MSDevice_SSM::determineTTCandDRAC(), MSVehicle::enterLaneAtInsertion(), MSDevice_SSM::findSurroundingVehicles(), MSLink::getLeaderInfo(), MSDevice_SSM::getUpstreamVehicles(), MSVehicle::updateFurtherLanes(), MSDevice_SSM::updatePassedEncounter(), and MSVehicle::validatePosition().
getManeuverDist()
double GUIVehicle::getManeuverDist () const
return the lane-change maneuver distance
Definition at line 836 of file GUIVehicle.cpp.
References MSVehicle::getLaneChangeModel(), and MSAbstractLaneChangeModel::getManeuverDist().
Referenced by getLeftSideOnEdge(), and getParameterWindow().
getMaxSpeed()
double MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), GUIMEVehicle::getTypeParameterWindow(), getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosRemote(), and MSVehicle::Influencer::implicitSpeedRemote().
getMaxSpeedOnLane()
double MSVehicle::getMaxSpeedOnLane () const inline inherited
Returns the maximal speed for the vehicle on its current lane (including speed factor and deviation, i.e., not necessarily the allowed speed limit)
Returns
The vehicle's max speed
Definition at line 574 of file MSVehicle.h.
References MSVehicleType::getMaxSpeed(), MSLane::getVehicleMaxSpeed(), MSVehicle::myLane, and MSBaseVehicle::myType.
Referenced by MSDevice_SSM::estimateConflictTimes(), MSLCM_LC2013::informFollower(), MSCFModel_Rail::moveHelper(), MSCFModel_KraussX::moveHelper(), and MSCFModel::moveHelper().
getMicrosimID()
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 134 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNEAdditional::changeAdditionalParent(), GNEAdditional::changeEdge(), GNEAdditional::changeLane(), GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNECrossing::getAttribute(), GNEConnection::getAttribute(), GNELane::getAttribute(), GNEJunction::getAttribute(), GNEEdge::getAttribute(), GNELane::getParentName(), GNEVaporizer::getParentName(), GNEDetectorE3::getParentName(), GNEDetector::getParentName(), GNEStoppingPlace::getParentName(), GNERouteProbe::getParentName(), GNENetElement::getParentName(), GNEPOI::getParentName(), GNEVariableSpeedSign::getParentName(), GNEPOILane::getParentName(), GNERerouter::getParentName(), GNEPoly::getParentName(), GNECalibrator::getParentName(), GNEAdditional::getParentName(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNEEdge::setAttribute(), GNENet::splitEdge(), GNEConnectorFrame::updateDescription(), and GNEConnection::updateID().
getNaviDegree()
double GUIBaseVehicle::getNaviDegree () const inline inherited
return the current angle in navigational degrees
Definition at line 92 of file GUIBaseVehicle.h.
References GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawRouteHelper(), GUIBaseVehicle::getAngle(), GUIBaseVehicle::getColorValue(), GUIBaseVehicle::getLastLaneChangeOffset(), GUIBaseVehicle::getParameterWindow(), GUIBaseVehicle::getStopInfo(), GUIBaseVehicle::getTypeParameterWindow(), GeomHelper::naviDegree(), and GUIBaseVehicle::selectBlockingFoes().
Referenced by GUIMEVehicle::getParameterWindow(), and getParameterWindow().
getNextParkingArea()
MSParkingArea * MSVehicle::getNextParkingArea () virtual inherited
get the current parking area stop
Implements SUMOVehicle.
Definition at line 1318 of file MSVehicle.cpp.
References MSVehicle::myStops, MSVehicle::Stop::parkingarea, and MSVehicle::Stop::reached.
getNextStop()
MSVehicle::Stop & MSVehicle::getNextStop () inherited
returns the next imminent stop in the stop queue
Returns
the upcoming stop
Definition at line 4806 of file MSVehicle.cpp.
References MSVehicle::myStops.
Referenced by libsumo::Vehicle::getStopState(), MSLane::isInsertionSuccess(), libsumo::Vehicle::resume(), and MSVehicle::signalSet().
getNOxEmissions()
double MSVehicle::getNOxEmissions () const inherited
Returns NOx emission of the current state.
Returns
The current NOx emission
Definition at line 4156 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, PollutantsInterface::NO_X, and MSVehicle::State::speed().
Referenced by getColorValue(), libsumo::Vehicle::getNOxEmission(), getParameterWindow(), and MSVehicle::nextStopDist().
getNumberReroutes()
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 291 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), and MSBaseVehicle::myNumberReroutes.
Referenced by GUIBaseVehicle::drawGLAdditional(), GUIMEVehicle::getColorValue(), getColorValue(), and MSBaseVehicle::replaceRouteEdges().
getNumPassengers()
int GUIVehicle::getNumPassengers () const private
return the number of passengers
Definition at line 657 of file GUIVehicle.cpp.
References MSVehicle::myPersonDevice, and MSDevice_Transportable::size().
Referenced by drawAction_drawRailCarriages(), and getLeftSideOnEdge().
getParameter()
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 127 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getDepartSpeed(), libsumo::Vehicle::getLine(), libsumo::Vehicle::getParameter(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), libsumo::Vehicle::getVia(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setColor(), GUIBaseVehicle::setFunctionalColor(), libsumo::Vehicle::setLine(), libsumo::Vehicle::setParameter(), and METriggeredCalibrator::tryEmit().
getParameterWindow()
GUIParameterTableWindow * GUIVehicle::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIBaseVehicle.
Definition at line 99 of file GUIVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicle::getAcceleration(), MSVehicle::getAccumulatedWaitingSeconds(), MSBaseVehicle::getChosenSpeedFactor(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getContainerNumber(), MSBaseVehicle::getDepartDelay(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSBaseVehicle::getImpatience(), MSVehicle::getLaneChangeModel(), getLastLaneChangeOffset(), MSVehicle::getLateralPositionOnLane(), getLeftSideOnEdge(), getLeftSublaneOnEdge(), getManeuverDist(), GUIBaseVehicle::getNaviDegree(), MSVehicle::getNOxEmissions(), MSBaseVehicle::getParameter(), MSVehicle::getPersonNumber(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), getRightSideOnEdge2(), getRightSublaneOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSlope(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::getSpeedLat(), getStopInfo(), MSAbstractLaneChangeModel::getTargetLane(), MSVehicle::getTimeGapOnLane(), MSVehicle::getTimeLossSeconds(), MSVehicle::getWaitingSeconds(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, MSGlobals::gWaitingTimeMemory, SUMOVehicleParameter::line, GUIParameterTableWindow::mkItem(), MSBaseVehicle::myDevices, MSVehicle::myLane, MSBaseVehicle::myParameter, and time2string().
Referenced by getAngle().
getParentName()
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNEAdditional, GNECalibrator, GNEPoly, GNERerouter, GNEPOILane, GNEVariableSpeedSign, GNENetElement, GNEPOI, GNERouteProbe, GNEStoppingPlace, GNEDetector, GUILane, GNEDetectorE3, GNEVaporizer, and GNELane.
Definition at line 114 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
getPersonNumber()
int MSVehicle::getPersonNumber () const inherited
Returns the number of persons.
Returns
The number of passengers on-board
Definition at line 4247 of file MSVehicle.cpp.
References MSBaseVehicle::myParameter, MSVehicle::myPersonDevice, SUMOVehicleParameter::personNumber, and MSDevice_Transportable::size().
Referenced by MSTransportableControl::boardAnyWaiting(), getParameterWindow(), libsumo::Vehicle::getPersonNumber(), MSVehicle::nextStopDist(), MSVehicle::processNextStop(), and MSXMLRawOut::writeVehicle().
getPersons()
const std::vector< MSTransportable * > & MSVehicle::getPersons () const inherited
retrieve riding persons
Definition at line 4227 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), MSVehicle::myEmptyTransportableVector, and MSVehicle::myPersonDevice.
Referenced by MSVehicle::nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
getPMxEmissions()
double MSVehicle::getPMxEmissions () const inherited
Returns PMx emission of the current state.
Returns
The current PMx emission
Definition at line 4162 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, PollutantsInterface::PM_X, and MSVehicle::State::speed().
Referenced by getColorValue(), getParameterWindow(), libsumo::Vehicle::getPMxEmission(), and MSVehicle::nextStopDist().
getPopUpMenu()
GUIGLObjectPopupMenu * GUIBaseVehicle::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 281 of file GUIBaseVehicle.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUIBaseVehicle::hasActiveAddVisualisation(), MID_HIDE_ALLROUTES, MID_HIDE_BEST_LANES, MID_HIDE_CURRENTROUTE, MID_HIDE_LFLINKITEMS, MID_SHOW_ALLROUTES, MID_SHOW_BEST_LANES, MID_SHOW_CURRENTROUTE, MID_SHOW_FOES, MID_SHOW_LFLINKITEMS, MID_START_TRACK, MID_STOP_TRACK, GUIBaseVehicle::myAdditionalVisualizations, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
getPosition()
Position GUIVehicle::getPosition (const double offset = 0) const inline virtual
Return current position (x/y, cartesian)
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 80 of file GUIVehicle.h.
References MSVehicle::getPosition().
Referenced by drawAction_drawRailCarriages().
getPositionAlongBestLanes()
Position MSVehicle::getPositionAlongBestLanes (double offset) const inherited
Return the (x,y)-position, which the vehicle would reach if it continued along its best continuation lanes from the current for a distance of offset m.
Parameters
offset
Returns
(x,y)-Position
See also
getPosition()
Definition at line 933 of file MSVehicle.cpp.
References MSLane::geometryPositionAtOffset(), MSVehicle::getBestLanesContinuation(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::getLinkTo(), MSLink::getViaLaneOrLane(), MSGlobals::gUsingInternalLanes, Position::INVALID, MSLane::isInternal(), MSVehicle::State::myPos, and MSVehicle::myState.
Referenced by MSDevice_SSM::determineConflictPoint(), and MSVehicle::getLastActionTime().
getPositionOnLane() [1/2]
double MSVehicle::getPositionOnLane () const inline virtual inherited
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 402 of file MSVehicle.h.
References MSVehicle::State::myPos, and MSVehicle::myState.
Referenced by MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeaders(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSVehicle::computeAngle(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLaneChanger::findCandidate(), MSDevice_SSM::findFoeConflictLane(), MSDevice_SSM::findSurroundingVehicles(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLaneChanger::getCloserFollower(), MSEdge::getDepartPosBound(), libsumo::Vehicle::getDistance(), MSVehicle::getDistanceToPosition(), libsumo::Vehicle::getDrivingDistance(), libsumo::Vehicle::getDrivingDistance2D(), MSLane::getFirstAnyVehicle(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSEdge::getFreeLane(), libsumo::Vehicle::getLanePosition(), MSVehicle::getLastStepDist(), MSLane::getLastVehicleInformation(), MSLane::getLeader(), MSVehicle::getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getNettoOccupancy(), libsumo::Vehicle::getNextTLS(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), getParameterWindow(), MSLane::getPartialBehind(), MSVehicle::getPosition(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSLCM_LC2013::getRoundaboutAheadInfo(), MSVehicle::getSlope(), MSVTKExport::getSpeed(), MSDevice_SSM::getUpstreamVehicles(), MSLane::handleCollisionBetween(), MSLane::isInsertionSuccess(), MSAbstractLaneChangeModel::laneChangeOutput(), MSVehicleTransfer::loadState(), MSLane::loadState(), libsumo::Vehicle::moveToXY(), MSLane::VehPosition::operator()(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSVehicle::processLinkAproaches(), MSCalibrator::remainingVehicleCapacity(), selectBlockingFoes(), MSVehicle::setBlinkerInformation(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLane::updateLeaderInfo(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
getPositionOnLane() [2/2]
double MSVehicle::getPositionOnLane (const MSLane * lane) const inherited
Get the vehicle's front position relative to the given lane.
Returns
The front position of the vehicle (in m from the given lane's begin)
Definition at line 3196 of file MSVehicle.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicleType::getLength(), and MSBaseVehicle::myType.
getPreviousLane()
MSLane * GUIVehicle::getPreviousLane (MSLane * current, int & furtherIndex) const private
Definition at line 537 of file GUIVehicle.cpp.
References MSVehicle::myFurtherLanes.
Referenced by drawAction_drawRailCarriages(), and getLeftSideOnEdge().
getPreviousSpeed()
double MSVehicle::getPreviousSpeed () const inline virtual inherited
Returns the vehicle's speed before the previous time step.
Returns
The vehicle's speed before the previous time step
Reimplemented from MSBaseVehicle.
Definition at line 490 of file MSVehicle.h.
References MSVehicle::State::myPreviousSpeed, and MSVehicle::myState.
Referenced by MSDevice_SSM::checkConflictEntryAndExit().
getRerouteOrigin()
const MSEdge * MSVehicle::getRerouteOrigin () const virtual inherited
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge or very close to the junction
Returns
The rerouting start point
Reimplemented from MSBaseVehicle.
Definition at line 1011 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSRoute::end(), MSVehicle::getCarFollowModel(), MSLane::getLength(), MSLane::getNextNormal(), MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by libsumo::Vehicle::changeTarget(), and MSVehicle::isActionStep().
getRightSideOnEdge()
double MSVehicle::getRightSideOnEdge (const MSLane * lane = 0) const inherited
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of edge
Definition at line 4337 of file MSVehicle.cpp.
References MSVehicle::getCenterOnEdge(), MSBaseVehicle::getVehicleType(), and MSVehicleType::getWidth().
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLane::detectCollisions(), MSVehicle::getLateralPositionOnLane(), getLeftSideOnEdge(), getRightSideOnEdge2(), and getRightSublaneOnEdge().
getRightSideOnEdge2()
double GUIVehicle::getRightSideOnEdge2 () const inline
return right vehicle side on current edge (without argument)
Definition at line 142 of file GUIVehicle.h.
References MSVehicle::getRightSideOnEdge().
Referenced by getParameterWindow().
getRightSideOnLane()
double MSVehicle::getRightSideOnLane () const inherited
Get the vehicle's lateral position on the lane:
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of the lane it is on
Definition at line 4331 of file MSVehicle.cpp.
References MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSVehicle::myLane, MSVehicle::State::myPosLat, and MSVehicle::myState.
Referenced by MSLCM_LC2013::adaptSpeedToPedestrians(), MSLane::checkForPedestrians(), MSVehicle::getLateralPositionOnLane(), and MSVehicle::planMoveInternal().
getRightSublaneOnEdge()
int GUIVehicle::getRightSublaneOnEdge () const
return the righmost sublane on the edge occupied by the vehicle
Definition at line 812 of file GUIVehicle.cpp.
References MSLane::getEdge(), MSVehicle::getRightSideOnEdge(), MSEdge::getSubLaneSides(), MAX2(), and MSVehicle::myLane.
Referenced by getLeftSideOnEdge(), and getParameterWindow().
getRoute()
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 107 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), libsumo::Vehicle::getDistance(), libsumo::Vehicle::getDrivingDistance(), libsumo::Vehicle::getDrivingDistance2D(), libsumo::Vehicle::getEdges(), libsumo::Vehicle::getRouteID(), MSLane::isInsertionSuccess(), libsumo::Vehicle::moveToXY(), MSVehicle::Influencer::postProcessRemoteControl(), and GUIBaseVehicle::setFunctionalColor().
getRoutePosition()
int MSVehicle::getRoutePosition () const inherited
Definition at line 802 of file MSVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by libsumo::Vehicle::getRouteIndex(), libsumo::Vehicle::moveToXY(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), and MSDevice_BTsender::notifyMove().
getSafeFollowSpeed()
double MSVehicle::getSafeFollowSpeed (const std::pair< const MSVehicle *, double > leaderInfo, const double seen, const MSLane *const lane, double distToCrossing) const inherited
compute safe speed for following the given leader
Definition at line 2225 of file MSVehicle.cpp.
References MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSLane::getLength(), MSVehicle::getSpeed(), MSGlobals::gSemiImplicitEulerUpdate, MAX2(), POSITION_EPS, and MSCFModel::stopSpeed().
Referenced by MSVehicle::adaptToLeader(), MSLane::getCriticalLeader(), and MSVehicle::hasInfluencer().
getSeatPosition()
const Position & GUIBaseVehicle::getSeatPosition (int personIndex) const protected inherited
returns the seat position for the person with the given index
if there are not enough seats in the vehicle people have to squeeze onto the last seat
Definition at line 1225 of file GUIBaseVehicle.cpp.
References MIN2(), and GUIBaseVehicle::mySeatPositions.
Referenced by drawAction_drawPersonsAndContainers().
getSignals()
int MSVehicle::getSignals () const inline inherited
Returns the signals.
Returns
The signals' states
Definition at line 1231 of file MSVehicle.h.
References MSVehicle::mySignals.
Referenced by libsumo::Vehicle::getSignalStates(), and MSFCDExport::write().
getSingularType()
MSVehicleType & MSBaseVehicle::getSingularType () inherited
Replaces the current vehicle type with a new one used by this vehicle only.
If the currently used vehicle type is already marked as being used by this vehicle only, no new type is created.
Returns
The new modifiable vehicle type
See also
MSBaseVehicle::myType
Definition at line 559 of file MSBaseVehicle.cpp.
References MSVehicleType::buildSingularType(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSVehicleType::getID(), MSNet::getInstance(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSVehicleType::isVehicleSpecific(), MSBaseVehicle::myType, OutputDevice::openTag(), MSBaseVehicle::replaceVehicleType(), STEPS2TIME, SUMO_ATTR_ID, SUMO_ATTR_TIME, toString(), and OutputDevice::writeAttr().
Referenced by TraCIServerAPI_Vehicle::processSet(), libsumo::Vehicle::setActionStepLength(), MSBaseVehicle::setChosenSpeedFactor(), libsumo::Vehicle::setMaxSpeed(), and libsumo::Vehicle::setShapeClass().
getSlope()
double MSVehicle::getSlope () const virtual inherited
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 890 of file MSVehicle.cpp.
References MSVehicle::getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSVehicle::myLane, and PositionVector::slopeDegreeAtOffset().
Referenced by MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHCEmissions(), MSVehicle::getLastActionTime(), MSVehicle::getNOxEmissions(), getParameterWindow(), MSVehicle::getPMxEmissions(), libsumo::Vehicle::getSlope(), MSCFModel_Rail::maxNextSpeed(), MSCFModel_KraussPS::maxNextSpeed(), and MSCFModel_Rail::minNextSpeed().
getSpaceTillLastStanding()
double MSVehicle::getSpaceTillLastStanding (const MSLane * l, bool & foundStopped) const protected inherited
Definition at line 3208 of file MSVehicle.cpp.
References MSLane::getLength(), MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMO_const_haltingSpeed.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::hasInfluencer().
getSpeed()
double MSVehicle::getSpeed () const inline virtual inherited
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Definition at line 482 of file MSVehicle.h.
References MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSCFModel_Wiedemann::_v(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSPModel_Striping::addCrossingVehs(), MSCriticalFollowerDistanceInfo::addFollower(), MSLCM_SL2015::addLCSpeedAdvice(), MSLCM_LC2013::addLCSpeedAdvice(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSDevice_SSM::checkConflictEntryAndExit(), GUIApplicationWindow::checkGamingEvents(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLCM_SL2015::commitFollowSpeed(), MSLCM_SL2015::commitManoeuvre(), MSDevice_SSM::computeDRAC(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), MSDevice_SSM::determineTTCandDRAC(), MSDevice_SSM::estimateConflictTimes(), MSVehicle::executeMove(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), getColorValue(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getMissingRearGap(), getParameterWindow(), MSLaneChanger::getRealLeader(), MSVehicle::getSafeFollowSpeed(), libsumo::Vehicle::getSpeed(), MSVTKExport::getSpeed(), MSVehicle::getTimeGapOnLane(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MSLCM_DK2008::informBlocker(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLane::lastInsertion(), MSVehicleTransfer::loadState(), MSLane::loadState(), MSLink::maybeOccupied(), MSCFModel_Rail::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::predInteraction(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSVehicle::setBrakingSignals(), MSAbstractLaneChangeModel::setFollowerGaps(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), libsumo::Vehicle::slowDown(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
getSpeedWithoutTraciInfluence()
double MSVehicle::getSpeedWithoutTraciInfluence () const inherited
Returns the uninfluenced velocity.
If no influencer exists (myInfluencer==0) the vehicle's current speed is returned. Otherwise the speed returned from myInfluencer->getOriginalSpeed().
Returns
The vehicle's velocity as it would without an influence
See also
Influencer::getOriginalSpeed
Definition at line 4827 of file MSVehicle.cpp.
References MSVehicle::Influencer::getOriginalSpeed(), MSVehicle::myInfluencer, MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by libsumo::Vehicle::getSpeedWithoutTraCI(), and MSVehicle::signalSet().
getStopEdges()
const ConstMSEdgeVector MSVehicle::getStopEdges () const protected virtual inherited
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 1594 of file MSVehicle.cpp.
References MSVehicle::myStops.
Referenced by MSVehicle::hasInfluencer().
getStopInfo()
std::string GUIVehicle::getStopInfo () const private virtual
retrieve information about the current stop state
Implements GUIBaseVehicle.
Definition at line 691 of file GUIVehicle.cpp.
References MSVehicle::hasStops(), MSVehicle::isParking(), MSVehicle::isStopped(), MSVehicle::myStops, and time2string().
Referenced by getLeftSideOnEdge(), and getParameterWindow().
getTimeGapOnLane()
double MSVehicle::getTimeGapOnLane () const inherited
Returns the time gap in seconds to the leader of the vehicle on the same lane.
If the distance is too big -1 is returned. The gap returned takes the minGap into account.
Returns
The time gap in seconds; -1 if no leader was found or speed is 0.
Definition at line 4127 of file MSVehicle.cpp.
References MSVehicle::getLeader(), MSVehicle::getSpeed(), and MSBaseVehicle::getVehicleType().
Referenced by getColorValue(), getParameterWindow(), and MSVehicle::nextStopDist().
getTimeLoss()
SUMOTime MSVehicle::getTimeLoss () const inline inherited
Returns the SUMOTime lost (speed was lesser maximum speed)
Note
Intentional stopping does not count towards this time.
speedFactor is included so time loss can never be negative. The value is that of a driver who compares his travel time when the road is clear (which includes speed factor) with the actual travel time.
includes time lost due to low departSpeed and decelerating/accelerating for planned stops
Returns
The time the vehicle lost due to various effects
Definition at line 641 of file MSVehicle.h.
References MSVehicle::myTimeLoss, and TIME2STEPS.
getTimeLossSeconds()
double MSVehicle::getTimeLossSeconds () const inline inherited
Returns the time loss in seconds.
Definition at line 676 of file MSVehicle.h.
References MSVehicle::myTimeLoss.
Referenced by getColorValue(), and getParameterWindow().
getType()
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 147 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), drawAction_drawLinkItems(), drawAction_drawPersonsAndContainers(), drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditional::drawChildConnections(), GNEDetectorE1::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE2::drawGL(), GNEVaporizer::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GNEDetectorE3::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GNELane::drawGL(), GUIContainer::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GUIPerson::drawGL(), GNEChargingStation::drawGL(), GUIJunctionWrapper::drawGL(), GNEVariableSpeedSign::drawGL(), GNEConnection::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GNERerouter::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIParkingArea::drawGL(), GNEEdge::drawGL(), GUIE2Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEJunction::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNELane::getColorValue(), GNEJunction::getColorValue(), GNEViewNet::getConnectionAtPopupPosition(), GNEViewNet::getCrossingAtPopupPosition(), GNEViewNet::getEdgeAtPopupPosition(), GNEViewNet::getEdgesAtPopupPosition(), GNEViewNet::getJunctionAtPopupPosition(), GNEViewNet::getLaneAtPopupPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onLeftBtnPress(), GNEDeleteFrame::removeAttributeCarrier(), GNENet::retrieveAttributeCarriers(), LayeredRTree::selectLayer(), GNEJunction::setAttribute(), GNEJunction::setColor(), GNELane::setLaneColor(), GNEDeleteFrame::showChildsOfMarkedAttributeCarrier(), and GUISelectedStorage::toggleSelection().
getTypeParameterWindow()
GUIParameterTableWindow * GUIVehicle::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Implements GUIBaseVehicle.
Definition at line 196 of file GUIVehicle.cpp.
References SUMOXMLDefinitions::CarFollowModels, GUIParameterTableWindow::closeBuilding(), MSVehicleType::getBoardingDuration(), MSVehicle::getCarFollowModel(), MSVehicleType::getContainerCapacity(), MSVehicleType::getEmissionClass(), MSVehicleType::getHeight(), MSVehicleType::getID(), MSVehicleType::getLength(), MSVehicleType::getLoadingDuration(), Parameterised::getMap(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getMaxSpeedLat(), MSVehicleType::getMinGap(), MSVehicleType::getMinGapLat(), PollutantsInterface::getName(), MSVehicleType::getParameter(), MSVehicleType::getPersonCapacity(), MSVehicleType::getPreferredLateralAlignment(), MSVehicleType::getVehicleClass(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, GUIParameterTableWindow::mkItem(), MSBaseVehicle::myType, STEPS2TIME, SumoVehicleClassStrings, and toString().
Referenced by getAngle().
getVClass()
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), and SUMOVTypeParameter::vehicleClass.
Referenced by drawRouteHelper(), MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
getVehicleType()
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 115 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_LC2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_LC2013::adaptSpeedToPedestrians(), MSVehicle::adaptToLeaders(), MSPModel_Striping::addCrossingVehs(), MSVehicle::addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeToNewLane(), MSLane::checkFailure(), MSLane::checkForPedestrians(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSDevice_SSM::classifyEncounter(), MSLCM_SL2015::commitManoeuvre(), MSLaneChanger::computeOvertakingTime(), MSLCM_SL2015::computeSpeedLat(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), drawAction_drawLinkItems(), drawAction_drawRailCarriages(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSDevice_SSM::estimateConflictTimes(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSEdge::getDepartPosBound(), MSLane::getDepartPosLat(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), MSVehicle::getLateralOverlap(), MSLane::getLeader(), MSVehicle::getLeader(), MSLink::getLeaderInfo(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), getLeftSideOnEdge(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), MSVehicle::getTimeGapOnLane(), MESegment::getTimeHeadway(), libsumo::Vehicle::getTypeID(), libsumo::Vehicle::getVehicleType(), GUIBaseVehicle::getVType(), MSLCM_SL2015::getWidth(), MSLink::getZipperSpeed(), MSLane::handleCollisionBetween(), MESegment::hasSpaceFor(), MSVehicle::ignoreRed(), MSLane::incorporateVehicle(), MSLCM_SL2015::informFollower(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSVehicle::keepClear(), MSLCM_SL2015::keepLatGap(), MSAbstractLaneChangeModel::laneChangeOutput(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), MSCFModel_Krauss::moveHelper(), MSPModel_Striping::moveInDirectionOnLane(), libsumo::Vehicle::moveToXY(), MSVehicle::overlap(), MSLCM_LC2013::overtakeDistance(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MESegment::receive(), MSLaneChanger::ChangeElem::registerHop(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSBaseVehicle::saveState(), selectBlockingFoes(), MSVehicleType::setActionStepLength(), MSAbstractLaneChangeModel::setFollowerGaps(), GUIBaseVehicle::setFunctionalColor(), MSAbstractLaneChangeModel::setLeaderGaps(), MSAbstractLaneChangeModel::setOrigLeaderGaps(), MSVehicle::setTentativeLaneAndPosition(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateCFRelated(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
getVelocityVector()
Position MSVehicle::getVelocityVector () const inline inherited
Returns the vehicle's direction in radians.
Returns
The vehicle's current angle
Definition at line 692 of file MSVehicle.h.
References MSVehicle::computeAngle(), MSVehicle::myAngle, MSVehicle::myState, MSVehicle::setAngle(), and MSVehicle::State::speed().
Referenced by MSDevice_SSM::updateEncounter().
getVType()
const MSVehicleType& GUIBaseVehicle::getVType () const inline protected inherited
A shortcut to myVehicle.myType.
Definition at line 342 of file GUIBaseVehicle.h.
References MSBaseVehicle::getVehicleType(), and GUIBaseVehicle::myVehicle.
Referenced by drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), and GUIBaseVehicle::drawOnPos().
getWaitingSeconds()
double MSVehicle::getWaitingSeconds () const inline inherited
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 660 of file MSVehicle.h.
References MSVehicle::myWaitingTime, and STEPS2TIME.
Referenced by getColorValue(), getParameterWindow(), libsumo::Vehicle::getWaitingTime(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSPedestrianPushButton::isActiveForEdge(), MSEmissionExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
getWaitingTime()
SUMOTime MSVehicle::getWaitingTime () const inline virtual inherited
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Implements SUMOVehicle.
Definition at line 628 of file MSVehicle.h.
References MSVehicle::myWaitingTime.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::executeMovements(), MSLink::getLeaderInfo(), MSVehicle::processLinkAproaches(), and selectBlockingFoes().
getWeightsStorage() [1/2]
const MSEdgeWeightsStorage & MSVehicle::getWeightsStorage () const inherited
Returns the vehicle's internal edge travel times/efforts container.
If the vehicle does not have such a container, it is built.
Returns
The vehicle's knowledge about edge weights
Definition at line 817 of file MSVehicle.cpp.
References MSVehicle::_getWeightsStorage().
Referenced by libsumo::Vehicle::getAdaptedTraveltime(), libsumo::Vehicle::getEffort(), MSNet::getEffort(), MSNet::getTravelTime(), libsumo::Vehicle::setAdaptedTraveltime(), and libsumo::Vehicle::setEffort().
getWeightsStorage() [2/2]
MSEdgeWeightsStorage & MSVehicle::getWeightsStorage () inherited
Definition at line 823 of file MSVehicle.cpp.
References MSVehicle::_getWeightsStorage().
getWidth()
double MSBaseVehicle::getWidth () const inline inherited
Returns the vehicle's width.
Returns
vehicle's width
Definition at line 369 of file MSBaseVehicle.h.
References MSVehicleType::getWidth(), and MSBaseVehicle::myType.
Referenced by MSDevice_SSM::classifyEncounter(), MSAbstractLaneChangeModel::determineTargetLane(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), MSVehicle::getLateralOverlap(), MSVehicle::lateralDistanceToLane(), MSVehicle::planMoveInternal(), MSLaneChangerSublane::startChangeSublane(), and MSDevice_SSM::updatePassedEncounter().
hasActiveAddVisualisation()
bool GUIBaseVehicle::hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const inherited
Returns whether the named feature is enabled in the given view.
Parameters
[in] parent The view for which the feature may be enabled
[in] which The visualisation feature
Returns
see comment
Definition at line 1168 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGLAdditional(), and GUIBaseVehicle::getPopUpMenu().
hasArrived()
bool MSVehicle::hasArrived () const virtual inherited
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 723 of file MSVehicle.cpp.
References MSRoute::end(), MSVehicle::isRemoteControlled(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::myState, MSVehicle::myStops, and POSITION_EPS.
Referenced by MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSLane::executeMovements(), and MSVehicle::processLaneAdvances().
hasDeparted()
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 300 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by MSVehicle::addStop(), MSBaseVehicle::createDevice(), MSLane::forceVehicleInsertion(), libsumo::Vehicle::getRouteIndex(), MEVehicle::loadState(), MSVehicle::loadState(), libsumo::Vehicle::moveTo(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::saveState(), and MSBaseVehicle::setArrivalPos().
hasDevice()
bool MSBaseVehicle::hasDevice (const std::string & deviceName) const inherited
check whether the vehicle is equiped with a device of the given type
Definition at line 497 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by MSBaseVehicle::createDevice(), and libsumo::Vehicle::getParameter().
hasInfluencer()
bool MSVehicle::hasInfluencer () const inline inherited
Definition at line 1543 of file MSVehicle.h.
References MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpaceTillLastStanding(), MSVehicle::getStopEdges(), MSVehicle::influenceChangeDecision(), MSVehicle::loadState(), MSVehicle::myInfluencer, MSVehicle::nextLinkPriority(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processTraCISpeedControl(), MSVehicle::removePassedDriveItems(), MSVehicle::saveState(), MSVehicle::setBlinkerInformation(), MSVehicle::setBrakingSignals(), MSVehicle::setEmergencyBlueLight(), MSVehicle::setRemoteState(), MSVehicle::updateOccupancyAndCurrentBestLane(), MSVehicle::updateTimeLoss(), MSVehicle::updateWaitingTime(), and MSVehicle::validatePosition().
Referenced by MSLaneChanger::changeOpposite(), MSAbstractLaneChangeModel::checkTraCICommands(), MSLane::detectCollisionBetween(), MSLane::handleCollisionBetween(), MSVehicle::influenceChangeDecision(), and MSLCM_SL2015::keepLatGap().
hasStops()
bool MSVehicle::hasStops () const inline inherited
Returns whether the vehicle has to stop somewhere.
Returns
Whether the vehicle has to stop somewhere
Definition at line 973 of file MSVehicle.h.
References MSVehicle::collisionStopTime(), DELTA_T, MSVehicle::isParking(), MSVehicle::isRemoteControlled(), MSVehicle::isStopped(), MSVehicle::isStoppedOnLane(), MSVehicle::keepStopping(), MSVehicle::myStops, and MSVehicle::wasRemoteControlled().
Referenced by getStopInfo(), MSLane::isInsertionSuccess(), and libsumo::Vehicle::resume().
hasValidRoute()
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 321 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), libsumo::Vehicle::isRouteValid(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::replaceRouteEdges(), and libsumo::Vehicle::setRouteID().
ignoreRed()
bool MSVehicle::ignoreRed (const MSLink * link, bool canBrake) const protected inherited
decide whether a red (or yellow light) may be ignore
Definition at line 4880 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicle::Influencer::getEmergencyBrakeRedLight(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), SUMOVTypeParameter::getJMParam(), MSLink::getLastStateChange(), MSVehicleType::getParameter(), MSLink::getState(), MSLink::getTLLogic(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSLink::haveRed(), MSLink::haveYellow(), MSVehicle::myInfluencer, SIMTIME, STEPS2TIME, SUMO_ATTR_JM_DRIVE_AFTER_RED_TIME, and toString().
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::estimateLeaveSpeed(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), and MSVehicle::processLinkAproaches().
influenceChangeDecision()
int MSVehicle::influenceChangeDecision (int state) inherited
allow TraCI to influence a lane change decision
Definition at line 4836 of file MSVehicle.cpp.
References MSLane::getEdge(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLaneIndex(), MSVehicle::hasInfluencer(), MSVehicle::Influencer::influenceChangeDecision(), and MSVehicle::myLane.
Referenced by MSLCM_LC2013::_wantsChange(), MSAbstractLaneChangeModel::cancelRequest(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::checkTraCICommands(), MSVehicle::Influencer::getRoutingMode(), and MSVehicle::hasInfluencer().
isActionStep()
bool MSVehicle::isActionStep (SUMOTime t) const inline inherited
Returns whether the next simulation step will be an action point for the vehicle.
Returns
Whether the vehicle has scheduled an action point for the next step.
Definition at line 601 of file MSVehicle.h.
References MSVehicle::getActionStepLength(), MSVehicle::getRerouteOrigin(), MSVehicle::isFrontOnLane(), and MSVehicle::myLastActionTime.
Referenced by MSVehicle::checkActionStep(), and getColorValue().
isActive()
bool MSVehicle::isActive () const inline inherited
Returns whether the current simulation step is an action point for the vehicle.
Returns
Whether the vehicle has an action point in the current step.
Definition at line 594 of file MSVehicle.h.
References MSVehicle::myActionStep.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLaneChangerSublane::checkChangeToNewLane(), getColorValue(), and MSLCM_SL2015::setOwnState().
isFrontOnLane()
bool MSVehicle::isFrontOnLane (const MSLane * lane) const virtual inherited
Returns the information whether the front of the vehicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Reimplemented from MSBaseVehicle.
Definition at line 3202 of file MSVehicle.cpp.
References MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getShadowLane(), and MSVehicle::myLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLaneChanger::findCandidate(), MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLink::getLeaderInfo(), MSLane::getLeadersOnConsecutive(), MSLane::getPartialBehind(), MSLane::getPartialBeyond(), and MSVehicle::isActionStep().
isOnRoad()
bool MSVehicle::isOnRoad () const inline virtual inherited
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 586 of file MSVehicle.h.
References MSVehicle::myAmOnNet.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSDevice_SSM::findSurroundingVehicles(), libsumo::Vehicle::getAllowedSpeed(), libsumo::Vehicle::getBestLanes(), libsumo::Vehicle::getDistance(), MSVehicle::getDistanceToPosition(), libsumo::Vehicle::getDrivingDistance(), libsumo::Vehicle::getDrivingDistance2D(), libsumo::Vehicle::getLaneChangeState(), libsumo::Vehicle::getLaneID(), libsumo::Vehicle::getLaneIndex(), libsumo::Vehicle::getLanePosition(), libsumo::Vehicle::getLateralLanePosition(), libsumo::Vehicle::getLeader(), libsumo::Vehicle::getNextTLS(), MSVTKExport::getPositions(), libsumo::Vehicle::getSlope(), MSVTKExport::getSpeed(), libsumo::Vehicle::isVisible(), libsumo::Vehicle::moveTo(), libsumo::Vehicle::moveToXY(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processNextStop(), MSBatteryExport::write(), and MSQueueExport::writeLane().
isParking()
bool MSVehicle::isParking () const virtual inherited
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 1358 of file MSVehicle.cpp.
References MSVehicle::isStopped(), and MSVehicle::myStops.
Referenced by MSVehicleTransfer::add(), MSVehicle::computeAngle(), MSLane::executeMovements(), MSVehicle::getPosition(), getStopInfo(), MSVehicle::hasStops(), and libsumo::Vehicle::isVisible().
isRemoteControlled()
bool MSVehicle::isRemoteControlled () const virtual inherited
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Reimplemented from MSBaseVehicle.
Definition at line 4856 of file MSVehicle.cpp.
References MSVehicle::Influencer::isRemoteControlled(), and MSVehicle::myInfluencer.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::Influencer::getLastAccessTimeStep(), MSVehicle::hasArrived(), MSVehicle::hasStops(), and MSVehicle::processLinkAproaches().
isSelected()
bool GUIVehicle::isSelected () const virtual
whether this vehicle is selected in the GUI
Reimplemented from MSBaseVehicle.
Definition at line 807 of file GUIVehicle.cpp.
References GUIGlObject::getGlID(), GLO_VEHICLE, gSelected, and GUISelectedStorage::isSelected().
Referenced by getAngle().
isStopped()
bool MSVehicle::isStopped () const virtual inherited
Returns whether the vehicle is at a stop.
Returns
Whether the vehicle has stopped
Implements SUMOVehicle.
Definition at line 1332 of file MSVehicle.cpp.
References MSVehicle::myStops.
Referenced by MSLaneChanger::changeOpposite(), MSLane::executeMovements(), MSLink::getLeaderInfo(), getStopInfo(), libsumo::Vehicle::getStopState(), MSVehicle::hasStops(), MSLCM_LC2013::informLeader(), MSVehicle::isParking(), MSVehicle::isStoppedInRange(), MSVehicle::isStoppedOnLane(), MSVehicle::isStoppedTriggered(), MSVehicle::keepStopping(), MSVehicle::resumeFromStopping(), MSVehicle::setBrakingSignals(), MSVehicle::updateTimeLoss(), and MSVehicle::updateWaitingTime().
isStoppedInRange()
bool MSVehicle::isStoppedInRange (double pos) const virtual inherited
return whether the given position is within range of the current stop
Implements SUMOVehicle.
Definition at line 1370 of file MSVehicle.cpp.
References MSVehicle::isStopped(), and MSVehicle::myStops.
Referenced by MSVehicle::nextStopDist().
isStoppedOnLane()
bool MSVehicle::isStoppedOnLane () const inherited
Definition at line 1337 of file MSVehicle.cpp.
References MSVehicle::isStopped(), MSVehicle::myLane, and MSVehicle::myStops.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), and MSVehicle::hasStops().
isStoppedTriggered()
bool MSVehicle::isStoppedTriggered () const virtual inherited
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 1364 of file MSVehicle.cpp.
References MSVehicle::isStopped(), and MSVehicle::myStops.
Referenced by MSVehicle::keepStopping(), and MSVehicle::nextStopDist().
keepClear()
bool MSVehicle::keepClear (const MSLink * link) const protected inherited
decide whether the given link must be kept clear
Definition at line 4868 of file MSVehicle.cpp.
References MSVehicle::getAccumulatedWaitingSeconds(), SUMOVTypeParameter::getJMParam(), MSVehicleType::getParameter(), MSBaseVehicle::getVehicleType(), MSLink::hasFoes(), MSLink::keepClear(), and SUMO_ATTR_JM_IGNORE_KEEPCLEAR_TIME.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::estimateLeaveSpeed().
keepStopping()
bool MSVehicle::keepStopping (bool afterProcessing = false) const inherited
Returns whether the vehicle is stopped and must continue to do so.
Definition at line 1342 of file MSVehicle.cpp.
References DELTA_T, MSVehicle::isStopped(), MSVehicle::isStoppedTriggered(), and MSVehicle::myStops.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicle::hasStops(), and MSVehicle::processNextStop().
lateralDistanceToLane()
double MSVehicle::lateralDistanceToLane (const int offset) const inherited
Get the minimal lateral distance required to move fully onto the lane at given offset.
Returns
The lateral distance to be covered to move the vehicle fully onto the lane (in m)
Definition at line 4445 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSBaseVehicle::getWidth(), MSLane::getWidth(), MSVehicle::myLane, NUMERICAL_EPS, and SIMTIME.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSAbstractLaneChangeModel::checkTraCICommands(), and MSVehicle::getLateralPositionOnLane().
leaveLane()
void MSVehicle::leaveLane (const MSMoveReminder::Notification reason, const MSLane * approachedLane = 0) inherited
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
Definition at line 3624 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getEdge(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::myAmOnNet, MSBaseVehicle::myCurrEdge, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSBaseVehicle::myMoveReminders, MSVehicle::State::myPos, MSVehicle::myState, MSVehicle::myStops, MSVehicle::myWaitingTime, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, MSVehicle::resumeFromStopping(), SIMTIME, time2string(), and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicle::congested(), MSVehicle::onRemovalFromNet(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSVehicle::processLaneAdvances(), and MSLane::removeVehicle().
loadState()
void MSVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual inherited
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 4958 of file MSVehicle.cpp.
References SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, MSVehicle::myLastActionTime, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myWaitingTime, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, and SUMO_ATTR_STATE.
Referenced by MSVehicle::hasInfluencer().
nextLinkPriority()
int MSVehicle::nextLinkPriority (const std::vector< MSLane *> & conts) static inherited
get a numerical value for the priority of the upcoming link
Definition at line 3993 of file MSVehicle.cpp.
References MSLinkContHelper::getConnectingLink(), and MSLink::havePriority().
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::updateBestLanes().
nextStopDist()
double MSVehicle::nextStopDist () const inline inherited
return the distance to the next stop or doubleMax if there is none.
Definition at line 1009 of file MSVehicle.h.
References MSVehicle::addContainer(), MSVehicle::addPerson(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getContainerNumber(), MSVehicle::getContainers(), MSVehicle::getDistanceToPosition(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getLaneIndex(), MSVehicle::getLeader(), MSVehicle::getNOxEmissions(), MSVehicle::getPersonNumber(), MSVehicle::getPersons(), MSVehicle::getPMxEmissions(), MSVehicle::getTimeGapOnLane(), MSVehicle::isStoppedInRange(), MSVehicle::isStoppedTriggered(), MSVehicle::myStopDist, MSVehicle::processNextStop(), and MSVehicle::removeTransportable().
Referenced by MSLaneChanger::changeOpposite().
onDepart()
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 292 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), and MESegment::receive().
onFurtherEdge()
bool MSVehicle::onFurtherEdge (const MSEdge * edge) const inherited
whether this vehicle has its back (and no its front) on the given edge
Definition at line 4614 of file MSVehicle.cpp.
References MSVehicle::myFurtherLanes.
Referenced by MSVehicle::getFurtherLanesPosLat().
onRemovalFromNet()
void MSVehicle::onRemovalFromNet (const MSMoveReminder::Notification reason) inherited
Called when the vehicle is removed from the network.
Moves along work reminders and informs all devices about quitting. Calls "leaveLane" then.
Parameters
[in] reason why the vehicle leaves (reached its destination, parking, teleport)
Definition at line 709 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSVehicleTransfer::getInstance(), MSVehicle::leaveLane(), MSVehicle::myLFLinkLanes, MSVehicleTransfer::remove(), MSVehicle::removeApproachingInformation(), SIMTIME, and toString().
Referenced by MSVehicleTransfer::add(), MSLane::detectCollisions(), MSLane::executeMovements(), libsumo::Vehicle::moveTo(), MSVehicle::Influencer::postProcessRemoteControl(), TraCIServerAPI_Vehicle::processSet(), and MSCalibrator::removePending().
overlap()
static bool MSVehicle::overlap (const MSVehicle * veh1, const MSVehicle * veh2) inline static inherited
Returns true if the two vehicles overlap.
Definition at line 704 of file MSVehicle.h.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, and MSVehicle::myState.
passingMinor()
bool MSVehicle::passingMinor () const inherited
decide whether the vehicle is passing a minor link or has comitted to do so
Definition at line 4916 of file MSVehicle.cpp.
References MSLane::getEdge(), MSLink::getFoeVisibilityDistance(), MSLane::getIncomingLanes(), MSLink::havePriority(), MSEdge::isInternal(), MSVehicle::myLane, and MSVehicle::myLFLinkLanes.
Referenced by MSCFModel_Krauss::moveHelper(), and MSVehicle::signalSet().
planMove()
void MSVehicle::planMove (const SUMOTime t, const MSLeaderInfo & ahead, const double lengthsInFront) inherited
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
This method goes through the best continuation lanes of the current lane and computes the safe velocities for passing/stopping at the next link as a DriveProcessItem
Afterwards it checks if any DriveProcessItem should be discarded to avoid blocking a junction (checkRewindLinkLanes).
Finally the ApproachingVehicleInformation is registered for all links that shall be passed
Parameters
[in] t The current timeStep
[in] ahead The leaders (may be 0)
[in] lengthsInFront Sum of vehicle lengths in front of the vehicle
Definition at line 1637 of file MSVehicle.cpp.
References MSVehicle::checkActionStep(), MSVehicle::checkRewindLinkLanes(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::myNextDriveItem, MSVehicle::myStopDist, MSVehicle::planMoveInternal(), MSVehicle::removePassedDriveItems(), MSAbstractLaneChangeModel::resetChanged(), and STEPS2TIME.
planMoveInternal()
void MSVehicle::planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector & lfLinks, double & myStopDist) const protected inherited
Todo:
: documentation
Definition at line 1706 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), MSVehicle::adaptToLeaders(), MSLeaderInfo::addLeader(), ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, MSCFModel::brakeGap(), MSVehicle::checkLinkLeader(), MSLeaderInfo::clear(), CRLL_LOOK_AHEAD, DEBUG_COND, DELTA_T, DIST_TO_STOPLINE_EXPECT_PRIORITY, MSRoute::end(), MSVehicle::estimateLeaveSpeed(), MSCFModel::estimateSpeedAfterDistance(), MSCFModel::freeSpeed(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSAbstractLaneChangeModel::getCommittedSpeed(), MSLane::getEdge(), MSVehicle::Stop::getEndPos(), Named::getID(), MSBaseVehicle::getID(), MSLane::getIncomingLanes(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLastVehicleInformation(), MSVehicle::getLateralOverlap(), MSVehicleType::getLength(), MSLane::getLength(), MSLane::getLinkCont(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSCFModel::getMinimalArrivalSpeed(), MSCFModel::getMinimalArrivalSpeedEuler(), MSCFModel::getMinimalArrivalTime(), MSPModel::getModel(), MSLane::getOpposite(), MSLane::getOppositeLeader(), MSLane::getParallelLane(), MSLink::getParallelLink(), MSBaseVehicle::getParameter(), MSEdge::getPersons(), MSVehicle::getPositionOnLane(), MSLane::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSLane::getVehicleNumber(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSBaseVehicle::getWidth(), MSEdge::getWidth(), MSGlobals::gSemiImplicitEulerUpdate, MSGlobals::gUsingInternalLanes, MSPModel::hasPedestrians(), MSVehicle::ignoreRed(), MSVehicle::Influencer::influenceSpeed(), MSEdge::isFringe(), MSEdge::isInternal(), MSLane::isLinkEnd(), MSAbstractLaneChangeModel::isOpposite(), LINKDIR_LEFT, LINKDIR_RIGHT, MAX2(), MSCFModel::maximumSafeStopSpeed(), MSCFModel::maxNextSpeed(), MIN2(), MSCFModel::minNextSpeed(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MSVehicle::myInfluencer, MSVehicle::myLane, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myStops, MSPModel::nextBlocking(), NUMERICAL_EPS, POSITION_EPS, MSVehicle::removeApproachingInformation(), SIMTIME, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), MSLane::succLinkSec(), SUMO_ATTR_JM_DRIVE_RED_SPEED, TIME2STEPS, and toString().
Referenced by MSVehicle::planMove().
processLaneAdvances()
void MSVehicle::processLaneAdvances (std::vector< MSLane *> & passedLanes, bool & moved, std::string & emergencyReason) protected inherited
This method checks if the vehicle has advanced over one or several lanes along its route and triggers the corresponding actions for the lanes and the vehicle. and adapts the given in/out parameters to the appropriate values.
Parameters
[out] passedLanes Lanes, which the vehicle touched at some moment of the executed simstep
[out] moved Whether the vehicle did move to another lane
[out] emergencyReason Reason for a possible emergency stop
Definition at line 2719 of file MSVehicle.cpp.
References DEBUG_COND, MSRoute::end(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::enterLaneAtMove(), MSLink::getDirection(), MSLane::getEdge(), MSVehicle::Influencer::getEmergencyBrakeRedLight(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSLane::getLength(), MSLink::getViaLane(), MSLink::getViaLaneOrLane(), MSGlobals::gUsingInternalLanes, MSVehicle::hasArrived(), MSLink::haveRed(), MSVehicle::ignoreRed(), MSEdge::isVaporizing(), MSVehicle::leaveLane(), LINKDIR_LEFT, LINKDIR_RIGHT, MSBaseVehicle::myCurrEdge, MSVehicle::myFurtherLanes, MSVehicle::myInfluencer, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::myNextDriveItem, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::myState, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_VAPORIZED, NUMERICAL_EPS, MSLink::passedJunction(), time2string(), and WRITE_WARNING.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
processLinkAproaches()
void MSVehicle::processLinkAproaches (double & vSafe, double & vSafeMin, double & vSafeMinDist) protected inherited
This method iterates through the driveprocess items for the vehicle and adapts the given in/out parameters to the appropriate values.
Parameters
Definition at line 2270 of file MSVehicle.cpp.
References ACCEL2SPEED, MSCFModel::brakeGap(), DEBUG_COND, DIST2SPEED, gDebugFlag1, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSLink::getFoeVisibilityDistance(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSLink::getParallelLink(), MSVehicle::getPositionOnLane(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpeed(), MSLink::getState(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSVehicle::getWaitingTime(), MSLane::getWidth(), MSLink::getZipperSpeed(), MSGlobals::gSemiImplicitEulerUpdate, MSLink::havePriority(), MSLink::haveYellow(), MSVehicle::ignoreRed(), MSLink::isCont(), MSVehicle::isRemoteControlled(), MSEdge::isRoundabout(), MSLink::lastWasContMajor(), LINKSTATE_EQUAL, LINKSTATE_ZIPPER, MIN2(), MSVehicle::myHaveToWaitOnNextLink, MSVehicle::myInfluencer, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::State::mySpeed, MSVehicle::myState, NUMERICAL_EPS, MSLink::opened(), POSITION_EPS, MSLink::removeApproaching(), and SIMTIME.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
processNextStop()
double MSVehicle::processNextStop (double currentVelocity) inherited
Processes stops, returns the velocity needed to reach the stop.
Returns
The velocity in dependance to the next/current stop
Todo:
Describe more detailed
See also
Stop
MSStoppingPlace
MSStoppingPlace
Definition at line 1376 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSStopOut::active(), MSBaseVehicle::addReminder(), MSVehicleControl::addWaiting(), MSTransportableControl::boardAnyWaiting(), MSVehicle::Stop::busstop, MSVehicle::Stop::containerstop, MSVehicle::Stop::containerTriggered, DEBUG_COND, MSVehicle::Stop::duration, MSVehicle::Stop::edge, SUMOVehicleParameter::Stop::endPos, MSParkingArea::enter(), MSStoppingPlace::enter(), MSVehicle::getActionStepLength(), MSStoppingPlace::getBeginLanePosition(), MSParkingArea::getCapacity(), MSVehicle::getCarFollowModel(), MSNet::getContainerControl(), MSVehicle::getContainerNumber(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MSVehicle::Stop::getEndPos(), Named::getID(), MSBaseVehicle::getID(), MSStopOut::getInstance(), MSNet::getInstance(), MSParkingArea::getLastFreePos(), MSStoppingPlace::getLastFreePos(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getMinGap(), MSLane::getMoveReminders(), MSParkingArea::getOccupancy(), MSNet::getPersonControl(), MSVehicle::getPersonNumber(), MSVehicle::getSpeed(), MSDevice_Transportable::getTransportables(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSGlobals::gSemiImplicitEulerUpdate, MSNet::hasContainers(), MSNet::hasPersons(), MSNet::informVehicleStateListener(), MSEdge::isInternal(), MSVehicle::isOnRoad(), MSVehicle::keepStopping(), MSVehicle::Stop::lane, MSTransportableControl::loadAnyWaiting(), MAX2(), MSVehicle::myAmRegisteredAsWaitingForContainer, MSVehicle::myAmRegisteredAsWaitingForPerson, MSVehicle::myContainerDevice, MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::myPersonDevice, MSVehicle::State::myPos, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myStops, MSBaseVehicle::myType, MSMoveReminder::NOTIFICATION_PARKING_REROUTE, NUMERICAL_EPS, MSVehicle::Stop::numExpectedContainer, MSVehicle::Stop::numExpectedPerson, MSVehicle::Stop::parkingarea, MSVehicle::Stop::pars, MSVehicle::State::pos(), MSVehicle::Stop::reached, MSVehicleControl::registerOneWaiting(), MSStoppingPlace::removeTransportable(), MSVehicle::resumeFromStopping(), SIMTIME, SUMOVehicleParameter::Stop::startPos, STEPS2TIME, STOPPING_PLACE_OFFSET, MSCFModel::stopSpeed(), MSStopOut::stopStarted(), SUMO_const_haltingSpeed, MSVehicle::Stop::triggered, MSVehicleControl::unregisterOneWaiting(), SUMOVehicleParameter::Stop::until, MSNet::VEHICLE_STATE_STARTING_STOP, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicleTransfer::loadState(), MSLane::loadState(), MSCFModel_Rail::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_Daniel1::moveHelper(), MSCFModel_Krauss::moveHelper(), MSCFModel_KraussX::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), and MSVehicle::nextStopDist().
processTraCISpeedControl()
void MSVehicle::processTraCISpeedControl (double vSafe, double & vNext) protected inherited
Check for speed advices from the traci client and adjust the speed vNext in the current (euler) / after the current (ballistic) simstep accordingly.
Parameters
[in] vSafe The maximal safe (or admissible) velocity as determined from stops, junction approaches, car following, lane changing, etc.
Definition at line 2449 of file MSVehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSVehicle::getCarFollowModel(), MSNet::getInstance(), MSBaseVehicle::getVehicleType(), MSVehicle::Influencer::implicitSpeedRemote(), MSVehicle::Influencer::influenceSpeed(), MSVehicle::Influencer::isRemoteControlled(), MAX2(), MSCFModel::maxNextSpeed(), MSVehicle::myInfluencer, MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
removeActiveAddVisualisation()
void GUIBaseVehicle::removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::removeAdditionalGLVisualisation
Definition at line 1184 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations, and GUISUMOAbstractView::removeAdditionalGLVisualisation().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems().
removeApproachingInformation()
void MSVehicle::removeApproachingInformation (DriveItemVector & lfLinks) const protected inherited
unregister approach from all upcoming links
Definition at line 4500 of file MSVehicle.cpp.
References MSVehicle::getLaneChangeModel(), and MSAbstractLaneChangeModel::removeShadowApproachingInformation().
Referenced by MSVehicle::executeMove(), MSVehicle::onRemovalFromNet(), MSVehicle::planMoveInternal(), and MSVehicle::~MSVehicle().
removeParameterTable()
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 261 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
removePassedDriveItems()
void MSVehicle::removePassedDriveItems () protected inherited
Erase passed drive items from myLFLinkLanes (and unregister approaching information for corresponding links). Further, myNextDriveItem is reset.
Note
This is called in planMove() if the vehicle has no actionstep. All items until the position myNextDriveItem are deleted. This can happen if myNextDriveItem was increased in processLaneAdvances() of the previous step.
Definition at line 2462 of file MSVehicle.cpp.
References DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::myLFLinkLanes, MSVehicle::myNextDriveItem, and SIMTIME.
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::planMove().
removeReminder()
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 360 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
removeTransportable()
void MSVehicle::removeTransportable (MSTransportable * t) inherited
removes a person or container
Definition at line 4217 of file MSVehicle.cpp.
References MSVehicle::myContainerDevice, MSVehicle::myPersonDevice, and MSDevice_Transportable::removeTransportable().
Referenced by MSVehicle::nextStopDist().
replaceParkingArea()
bool MSVehicle::replaceParkingArea (MSParkingArea * parkingArea, std::string & errorMsg) virtual inherited
replace the current parking area stop with a new stop with merge duration
Implements SUMOVehicle.
Definition at line 1247 of file MSVehicle.cpp.
References MSVehicle::addStop(), SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSStoppingPlace::getLane(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::myLane, MSBaseVehicle::myParameter, MSVehicle::myStops, SUMOVehicleParameter::Stop::parametersSet, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::parkingarea, MSVehicle::Stop::parkingarea, MSVehicle::Stop::pars, MSVehicle::Stop::reached, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::updateBestLanes().
replaceRoute()
bool MSVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0, bool addStops = true, bool removeStops = true) virtual inherited
Replaces the current route by the given one.
It is possible that the new route is not accepted, if it does not contain the vehicle's current edge.
Parameters
[in] route The new route to pass
[in] removeStops Whether stops should be removed if they do not fit onto the new route
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 732 of file MSVehicle.cpp.
References MSRoute::addReference(), MSVehicle::addStop(), MSBaseVehicle::addStops(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSGlobals::gCheckRoutes, MSLane::getEdge(), MSRoute::getEdges(), MSNet::getInstance(), MSLane::getOutgoingLanes(), MSRoute::getStops(), MSNet::informVehicleStateListener(), MSEdge::isInternal(), MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::myLastBestLanesEdge, MSVehicle::myLastBestLanesInternalLane, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, MSVehicle::myStops, MSRoute::release(), MSVehicle::updateBestLanes(), MSNet::VEHICLE_STATE_NEWROUTE, and WRITE_WARNING.
Referenced by libsumo::Vehicle::setRouteID().
replaceRouteEdges()
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false, bool removeStops = true) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
[in] removeStops Whether stops should be removed if they do not fit onto the new route
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 227 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), toString(), and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessRemoteControl(), MSBaseVehicle::reroute(), and libsumo::Vehicle::setRoute().
replaceVehicleType()
void MSBaseVehicle::replaceVehicleType (MSVehicleType * type) inherited
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSBaseVehicle::myType
Definition at line 550 of file MSBaseVehicle.cpp.
References MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleType::isVehicleSpecific(), MSBaseVehicle::myType, and MSVehicleControl::removeVType().
Referenced by MSBaseVehicle::getSingularType(), MSBaseVehicle::setChosenSpeedFactor(), and libsumo::Vehicle::setType().
reroute()
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 155 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), MSBaseVehicle::calculateArrivalParams(), SUMOAbstractRouter< E, V >::compute(), MSInsertionControl::descheduleDeparture(), MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, MSGlobals::gCheckRoutes, Named::getID(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSEdge::isTazConnector(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, SUMOVehicleParameter::via, and WRITE_WARNING.
Referenced by libsumo::Vehicle::changeTarget(), MSBaseVehicle::getCurrentRouteEdge(), libsumo::Vehicle::rerouteEffort(), and libsumo::Vehicle::rerouteTraveltime().
resetActionOffset()
void MSVehicle::resetActionOffset (const SUMOTime timeUntilNextAction = 0) inherited
Resets the action offset for the vehicle.
Parameters
[in] timeUntilNextAction time interval from now for the next action, defaults to 0, which implies an immediate action point in the current step.
Definition at line 1613 of file MSVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSVehicle::myLastActionTime.
Referenced by libsumo::Vehicle::setActionStepLength(), MSVehicleType::setActionStepLength(), and MSVehicle::updateActionOffset().
resetRoutePosition()
void MSVehicle::resetRoutePosition (int index) inherited
Definition at line 808 of file MSVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSCalibrator::execute().
resumeFromStopping()
bool MSVehicle::resumeFromStopping () inherited
resumes a vehicle from stopping
Returns
true on success, the resuming fails if the vehicle wasn't parking in the first place
Definition at line 4755 of file MSVehicle.cpp.
References MSStopOut::active(), MSLane::COLLISION_ACTION_WARN, MSLane::getCollisionAction(), MSBaseVehicle::getDevice(), MSLane::getEdge(), MSStopOut::getInstance(), MSNet::getInstance(), MSNet::getVehicleControl(), MSNet::informVehicleStateListener(), MSVehicle::isStopped(), MSVehicle::myAmRegisteredAsWaitingForContainer, MSVehicle::myAmRegisteredAsWaitingForPerson, MSVehicle::myCollisionImmunity, MSVehicle::myLane, MSVehicle::myStops, MSVehicle::myWaitingTime, MSVehicleControl::removeWaiting(), MSStopOut::stopEnded(), MSDevice_Vehroutes::stopEnded(), TIME2STEPS, MSVehicleControl::unregisterOneWaiting(), MSVehicle::updateBestLanes(), and MSNet::VEHICLE_STATE_ENDING_STOP.
Referenced by MSLane::executeMovements(), MSVehicle::leaveLane(), MSVehicle::processNextStop(), libsumo::Vehicle::resume(), and MSVehicle::signalSet().
saveState()
void MSVehicle::saveState (OutputDevice & out) virtual inherited
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 4933 of file MSVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, MSBaseVehicle::myDevices, MSVehicle::myLastActionTime, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myStops, MSVehicle::myWaitingTime, MSBaseVehicle::saveState(), SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, SUMO_ATTR_STATE, toString(), OutputDevice::writeAttr(), and Parameterised::writeParams().
Referenced by MSVehicle::hasInfluencer().
selectBlockingFoes()
void GUIVehicle::selectBlockingFoes () const virtual
adds the blocking foes to the current selection
Implements GUIBaseVehicle.
Definition at line 716 of file GUIVehicle.cpp.
References MSVehicle::getCarFollowModel(), GUIGlObject::getGlID(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicle::DriveProcessItem::getLeaveSpeed(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSLink::getParallelLink(), MSVehicle::getPositionOnLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSVehicle::getWaitingTime(), MSLane::getWidth(), gSelected, MSLink::isLeader(), MSVehicle::DriveProcessItem::myArrivalSpeed, MSVehicle::DriveProcessItem::myArrivalTime, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::DriveProcessItem::myLink, MSLink::opened(), GUISelectedStorage::select(), and SIMTIME.
Referenced by getAngle().
setAngle()
void MSVehicle::setAngle (double angle, bool straightenFurther = false) inherited
Set a custom vehicle angle in rad, optionally updates furtherLanePosLat.
Definition at line 1024 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSVehicle::getLateralPositionOnLane(), MSVehicle::myAngle, MSVehicle::myFurtherLanesPosLat, and SIMTIME.
Referenced by MSVehicle::getVelocityVector(), MSVehicle::Influencer::postProcessRemoteControl(), and MSLaneChangerSublane::startChangeSublane().
setArrivalPos()
virtual void MSBaseVehicle::setArrivalPos (double arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 275 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
setBlinkerInformation()
void MSVehicle::setBlinkerInformation () protected inherited
sets the blue flashing light for emergency vehicles
Definition at line 4260 of file MSVehicle.cpp.
References MSVehicle::getBestLanesContinuation(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLength(), MSLane::getLinkCont(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getPositionOnLane(), MSVehicle::Influencer::getSignals(), MSLane::getVehicleMaxSpeed(), LCA_BLOCKED, LCA_KEEPRIGHT, LCA_LEFT, LCA_RIGHT, LCA_SUBLANE, LINKDIR_LEFT, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_TURN, MSVehicle::myInfluencer, MSVehicle::mySignals, MSVehicle::Influencer::setSignals(), MSLane::succLinkSec(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
setBrakingSignals()
void MSVehicle::setBrakingSignals (double vNext) protected inherited
sets the braking lights on/off
Definition at line 2676 of file MSVehicle.cpp.
References ACCEL2SPEED, MSVehicle::getSpeed(), MSVehicle::isStopped(), SUMO_const_haltingSpeed, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), and MSVehicle::VEH_SIGNAL_BRAKELIGHT.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
setChosenSpeedFactor()
void MSBaseVehicle::setChosenSpeedFactor (const double factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 384 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::getDevice(), MSBaseVehicle::getSingularType(), MSBaseVehicle::myChosenSpeedFactor, MSBaseVehicle::replaceVehicleType(), and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
setColor()
void GUIBaseVehicle::setColor (const GUIVisualizationSettings & s) const protected inherited
sets the color according to the currente settings
Definition at line 1079 of file GUIBaseVehicle.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIBaseVehicle::getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIBaseVehicle::myVehicle, GLHelper::setColor(), GUIBaseVehicle::setFunctionalColor(), and GUIVisualizationSettings::vehicleColorer.
Referenced by GUIBaseVehicle::drawOnPos(), and GUIBaseVehicle::drawRoute().
setDeviceParameter()
void MSBaseVehicle::setDeviceParameter (const std::string & deviceName, const std::string & key, const std::string & value) inherited
try to set the given parameter from any of the vehicles devices, raise InvalidArgument if no device parameter by that name exists
Definition at line 538 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by libsumo::Vehicle::setParameter().
setEmergencyBlueLight()
void MSVehicle::setEmergencyBlueLight (SUMOTime currentTime) protected inherited
sets the blue flashing light for emergency vehicles
Definition at line 4302 of file MSVehicle.cpp.
References MSVehicle::signalSet(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), and MSVehicle::VEH_SIGNAL_EMERGENCY_BLUE.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
setFunctionalColor()
bool GUIBaseVehicle::setFunctionalColor (int activeScheme, const MSBaseVehicle * veh) static inherited
sets the color according to the current scheme index and some vehicle function
Definition at line 1088 of file GUIBaseVehicle.cpp.
References SUMOVehicleParameter::color, RGBColor::DEFAULT_COLOR, Position::distanceTo(), RGBColor::fromHSV(), Boundary::getCenter(), MSRoute::getColor(), MSVehicleType::getColor(), MSRoute::getEdges(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSBaseVehicle::getRoute(), MSBaseVehicle::getVehicleType(), M_PI, GLHelper::setColor(), VEHPARS_COLOR_SET, VTYPEPARS_COLOR_SET, MSVehicleType::wasSet(), SUMOVehicleParameter::wasSet(), Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIBaseVehicle::setColor().
setMicrosimID()
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 140 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNEAdditional::changeAdditionalID(), GNENet::renameJunction(), GNELane::setIndex(), GNEEdge::setMicrosimID(), and GNEConnection::updateID().
setPrefix()
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 270 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
setRemoteState()
void MSVehicle::setRemoteState (Position xyPos) inherited
sets position outside the road network
Definition at line 4849 of file MSVehicle.cpp.
References MSVehicle::myCachedPosition.
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::Influencer::postProcessRemoteControl().
setTentativeLaneAndPosition()
void MSVehicle::setTentativeLaneAndPosition (MSLane * lane, double pos, double posLat = 0) inherited
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
Definition at line 4321 of file MSVehicle.cpp.
References MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myBackPos, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, and MSVehicle::myState.
Referenced by MSVehicle::congested(), MSLane::freeInsertion(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSVehicleTransfer::loadState(), and libsumo::Vehicle::moveTo().
signalSet()
bool MSVehicle::signalSet (int which) const inline inherited
Returns whether the given signal is on.
Parameters
[in] signal The signal to return the value of
Returns
Whether the given signal is on
Definition at line 1240 of file MSVehicle.h.
References MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getNextStop(), MSVehicle::getSpeedWithoutTraciInfluence(), MSVehicle::mySignals, MSVehicle::passingMinor(), MSVehicle::resumeFromStopping(), MSVehicle::unsafeLinkAhead(), and MSVehicle::updateFurtherLanes().
Referenced by MSVehicle::checkRewindLinkLanes(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBlueLight(), drawAction_drawVehicleBrakeLight(), and MSVehicle::setEmergencyBlueLight().
succEdge()
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), libsumo::Vehicle::moveTo(), MELoop::nextSegment(), and MESegment::receive().
switchOffSignal()
void MSVehicle::switchOffSignal (int signal) inline inherited
Switches the given signal off.
Parameters
[in] signal The signal to mark as being switched off
Definition at line 1223 of file MSVehicle.h.
References MSVehicle::mySignals.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::setBlinkerInformation(), MSVehicle::setBrakingSignals(), MSVehicle::setEmergencyBlueLight(), libsumo::Vehicle::setSignals(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
switchOnSignal()
void MSVehicle::switchOnSignal (int signal) inline inherited
Switches the given signal on.
Parameters
[in] signal The signal to mark as being switched on
Definition at line 1215 of file MSVehicle.h.
References MSVehicle::mySignals.
Referenced by MSVehicle::setBlinkerInformation(), MSVehicle::setBrakingSignals(), MSVehicle::setEmergencyBlueLight(), libsumo::Vehicle::setSignals(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
unsafeLinkAhead()
bool MSVehicle::unsafeLinkAhead (const MSLane * lane) const inherited
whether the vehicle may safely move to the given lane with regard to upcoming links
Definition at line 4512 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSEdge::isInternal(), MSLane::isLinkEnd(), LINKSTATE_ZIPPER, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSLane::succLinkSec(), and MSLink::ZIPPER_ADAPT_DIST.
Referenced by MSLaneChanger::checkChange(), and MSVehicle::signalSet().
updateActionOffset()
void MSVehicle::updateActionOffset (const SUMOTime oldActionStepLength, const SUMOTime newActionStepLength) inherited
Process an updated action step length value (only affects the vehicle's action offset, The actionStepLength is stored in the (singular) vtype)
Parameters
[in] oldActionStepLength The action step length previous to the update
[in] actionStepLength The new action step length (stored in the vehicle's vtype).
Note
The current action step length is updated. This implies an immediate action point, if the new step length is smaller than the length of the currently running action interval (the difference between now and the last action time).
Definition at line 1618 of file MSVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicle::myLastActionTime, and MSVehicle::resetActionOffset().
Referenced by libsumo::Vehicle::setActionStepLength(), and MSVehicleType::setActionStepLength().
updateBestLanes()
void MSVehicle::updateBestLanes (bool forceRebuild = false, const MSLane * startLane = 0) inherited
computes the best lanes to use in order to continue the route
The information is rebuilt if the vehicle is on a different edge than the one stored in "myLastBestLanesEdge" or "forceRebuild" is true.
Otherwise, only the density changes on the stored lanes are adapted to the container only.
A rebuild must be done if the vehicle leaves a stop; then, another lane may become the best one.
If no starting lane ("startLane") is given, the vehicle's current lane ("myLane") is used as start of bect lanes building.
Parameters
[in] forceRebuild Whether the best lanes container shall be rebuilt even if the vehicle's edge has not changed
[in] startLane The lane the process shall start at ("myLane" will be used if ==0)
Definition at line 3692 of file MSVehicle.cpp.
References MSEdge::allowedLanes(), MSVehicle::LaneQ::allowsContinuation, MSLane::allowsVehicleClass(), ARRIVAL_LANE_GIVEN, SUMOVehicleParameter::arrivalLaneProcedure, MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSEdge::clear(), MSVehicle::LaneQ::currentLength, DEBUG_COND, MSVehicle::Stop::edge, MSRoute::end(), MSVehicle::getBestLanesContinuation(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSEdge::getLanes(), MSLane::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSLane::getNextNormal(), MSLane::getOpposite(), MSVehicleType::getVehicleClass(), MSEdge::isInternal(), MSLane::isInternal(), MSVehicle::LaneQ::lane, MSVehicle::Stop::lane, MSVehicle::LaneQ::length, MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSVehicle::myBestLanes, MSBaseVehicle::myCurrEdge, MSVehicle::myCurrentLaneInBestLanes, MSVehicle::myLane, MSVehicle::myLastBestLanesEdge, MSVehicle::myLastBestLanesInternalLane, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSVehicle::myStops, MSBaseVehicle::myType, MSVehicle::nextLinkPriority(), MSVehicle::LaneQ::nextOccupation, MSVehicle::LaneQ::occupation, MSVehicle::Stop::pars, POSITION_EPS, SIMTIME, SUMOVehicleParameter::Stop::startPos, toString(), and MSVehicle::updateOccupancyAndCurrentBestLane().
Referenced by MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSLane::forceVehicleInsertion(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLane::loadState(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::replaceParkingArea(), MSVehicle::replaceRoute(), and MSVehicle::resumeFromStopping().
updateDriveItems()
void MSVehicle::updateDriveItems () inherited
Check whether the drive items (myLFLinkLanes) are up to date, and update them if required.
Note
This is the case if a lane change was completed. Only the links corresponding to the drive items are updated to the corresponding parallel links.
Definition at line 2516 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicle::getBestLanesContinuation(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLink::getLaneBefore(), MSLane::getLinkTo(), MSLink::getParallelLink(), MSLane::isInternal(), MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::myNextDriveItem, MSLink::removeApproaching(), and SIMTIME.
Referenced by MSVehicle::congested(), and MSAbstractLaneChangeModel::laneChangeOutput().
updateFurtherLanes()
double MSVehicle::updateFurtherLanes (std::vector< MSLane *> & furtherLanes, std::vector< double > & furtherLanesPosLat, const std::vector< MSLane *> & passedLanes) inherited
update a vector of further lanes and return the new backPos
Definition at line 3054 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getLength(), MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, SIMTIME, and toString().
Referenced by MSVehicle::executeMove(), MSVehicle::signalSet(), and MSAbstractLaneChangeModel::updateShadowLane().
updateOccupancyAndCurrentBestLane()
void MSVehicle::updateOccupancyAndCurrentBestLane (const MSLane * startLane) protected inherited
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
Definition at line 4009 of file MSVehicle.cpp.
References MSVehicle::myBestLanes, and MSVehicle::myCurrentLaneInBestLanes.
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::updateBestLanes().
updateState()
void MSVehicle::updateState (double vNext) protected inherited
updates the vehicles state, given a next value for its speed. This value can be negative in case of the ballistic update to indicate a stop within the next timestep. (You can call this a 'hack' to emulate reasoning based on accelerations: The assumed constant acceleration a within the next time step is then a = (vNext - vCurrent)/TS)
Parameters
[in] vNext speed in the next time step
Definition at line 3000 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicle::getDeltaPos(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSLane::getOpposite(), MSLane::getOppositePos(), MSGlobals::gSemiImplicitEulerUpdate, MSVehicle::Influencer::implicitDeltaPosRemote(), Position::INVALID, MSVehicle::Influencer::isRemoteControlled(), MAX2(), MSVehicle::myAcceleration, MSVehicle::myCachedPosition, MSVehicle::myInfluencer, MSVehicle::myLane, MSVehicle::State::myLastCoveredDist, MSVehicle::State::myPos, MSVehicle::State::myPreviousSpeed, MSVehicle::State::mySpeed, MSVehicle::myState, SIMTIME, SPEED2ACCEL, and SPEED2DIST.
Referenced by MSVehicle::estimateLeaveSpeed(), and MSVehicle::executeMove().
updateTimeLoss()
void MSVehicle::updateTimeLoss (double vNext) protected inherited
Updates the vehicle's time loss.
Definition at line 2707 of file MSVehicle.cpp.
References MSLane::getVehicleMaxSpeed(), MSVehicle::isStopped(), MSVehicle::myLane, MSVehicle::myTimeLoss, and TS.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
updateWaitingTime()
void MSVehicle::updateWaitingTime (double vNext) protected inherited
Updates the vehicle's waiting time counters (accumulated and consecutive)
Definition at line 2695 of file MSVehicle.cpp.
References DELTA_T, MSVehicle::isStopped(), MSVehicle::myWaitingTime, MSVehicle::myWaitingTimeCollector, MSVehicle::WaitingTimeCollector::passTime(), and SUMO_const_haltingSpeed.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
validatePosition()
Position MSVehicle::validatePosition (Position result, double offset = 0) const protected inherited
ensure that a vehicle-relative position is not invalid
Definition at line 995 of file MSVehicle.cpp.
References MSVehicle::getLateralPositionOnLane(), MSBaseVehicle::getLength(), Position::INVALID, and MSVehicle::myFurtherLanes.
Referenced by MSVehicle::getPosition(), and MSVehicle::hasInfluencer().
wasRemoteControlled()
bool MSVehicle::wasRemoteControlled (SUMOTime lookBack = DELTA_T) const inherited
Returns the information whether the vehicle is fully controlled via TraCI within the lookBack time.
Definition at line 4862 of file MSVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicle::Influencer::getLastAccessTimeStep(), and MSVehicle::myInfluencer.
Referenced by MSVehicle::hasStops(), and libsumo::Vehicle::isVisible().
willPass()
bool MSVehicle::willPass (const MSEdge *const edge) const inherited
Returns whether the vehicle wil pass the given edge.
Parameters
[in] The edge to find in the vehicle's current route
Returns
Whether the given edge will be passed by the vehicle
Todo:
Move to MSRoute?
Definition at line 796 of file MSVehicle.cpp.
References MSRoute::end(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by libsumo::Vehicle::moveTo().
workOnMoveReminders()
void MSVehicle::workOnMoveReminders (double oldPos, double newPos, double newSpeed) inherited
Processes active move reminder.
This method goes through all active move reminder, both those for the current lane, stored in "myMoveReminders" and those of prior lanes stored in "myOldLaneMoveReminders" calling "MSMoveReminder::notifyMove".
When processing move reminder from "myOldLaneMoveReminders", the offsets (prior lane lengths) are used, which are stored in "myOldLaneMoveReminderOffsets".
Each move reminder which is no longer active is removed from the container.
Parameters
[in] oldPos The position the vehicle had before it has moved
[in] newPos The position the vehicle has after it has moved
[in] newSpeed The vehicle's speed within this move
See also
MSMoveReminder
Definition at line 839 of file MSVehicle.cpp.
References MAX2(), and MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::executeMove().
Field Documentation
INVALID_ID
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 76 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
myAcceleration
double MSVehicle::myAcceleration protected inherited
The current acceleration after dawdling in m/s.
Definition at line 1722 of file MSVehicle.h.
Referenced by MSVehicle::executeMove(), MSVehicle::getAcceleration(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), and MSVehicle::updateState().
myActionStep
bool MSVehicle::myActionStep protected inherited
The flag myActionStep indicates whether the current time step is an action point for the vehicle.
Definition at line 1682 of file MSVehicle.h.
Referenced by MSVehicle::checkActionStep(), MSVehicle::executeMove(), and MSVehicle::isActive().
myAdditionalVisualizations
std::map<GUISUMOAbstractView*, int> GUIBaseVehicle::myAdditionalVisualizations inherited
Enabled visualisations, per view.
Definition at line 301 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), drawOutsideNetwork(), GUIBaseVehicle::getPopUpMenu(), GUIBaseVehicle::hasActiveAddVisualisation(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::~GUIBaseVehicle().
myAmOnNet
bool MSVehicle::myAmOnNet protected inherited
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
Definition at line 1733 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::isOnRoad(), and MSVehicle::leaveLane().
myAmRegisteredAsWaitingForContainer
bool MSVehicle::myAmRegisteredAsWaitingForContainer protected inherited
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
Definition at line 1739 of file MSVehicle.h.
Referenced by MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
myAmRegisteredAsWaitingForPerson
bool MSVehicle::myAmRegisteredAsWaitingForPerson protected inherited
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
Definition at line 1736 of file MSVehicle.h.
Referenced by MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
myAngle
double MSVehicle::myAngle protected inherited
the angle in radians (
Todo:
consider moving this into myState)
Definition at line 1744 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSVehicle::getAngle(), MSVehicle::getVelocityVector(), and MSVehicle::setAngle().
myArrivalLane
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 487 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and MSVehicle::updateBestLanes().
myArrivalPos
double MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 484 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and MSVehicle::updateBestLanes().
myBestLanes
std::vector<std::vector<LaneQ> > MSVehicle::myBestLanes protected inherited
Definition at line 1702 of file MSVehicle.h.
Referenced by MSVehicle::adaptBestLanesOccupation(), drawBestLanes(), MSVehicle::getBestLaneOffset(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::updateBestLanes(), and MSVehicle::updateOccupancyAndCurrentBestLane().
myCachedPosition
Position MSVehicle::myCachedPosition mutable protected inherited
Definition at line 1752 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSVehicle::getPosition(), MSVehicle::setRemoteState(), MSLaneChangerSublane::startChangeSublane(), and MSVehicle::updateState().
myChosenSpeedFactor
double MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 457 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
myCollisionImmunity
SUMOTime MSVehicle::myCollisionImmunity protected inherited
amount of time for which the vehicle is immune from collisions
Definition at line 1750 of file MSVehicle.h.
Referenced by MSVehicle::collisionStopTime(), MSVehicle::executeMove(), and MSVehicle::resumeFromStopping().
myContainerDevice
MSDevice_Transportable* MSVehicle::myContainerDevice protected inherited
The containers this vehicle may have.
Definition at line 1719 of file MSVehicle.h.
Referenced by MSVehicle::addContainer(), drawAction_drawPersonsAndContainers(), MSVehicle::getContainerNumber(), MSVehicle::getContainers(), MSVehicle::processNextStop(), and MSVehicle::removeTransportable().
myCurrEdge
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 454 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::enterLaneAtMove(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), MSVehicle::getRerouteOrigin(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MSVehicle::leaveLane(), MEVehicle::loadState(), MSVehicle::loadState(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessRemoteControl(), MSVehicle::processLaneAdvances(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), and MSVehicle::willPass().
myCurrentLaneInBestLanes
std::vector<LaneQ>::iterator MSVehicle::myCurrentLaneInBestLanes protected inherited
Definition at line 1707 of file MSVehicle.h.
Referenced by MSVehicle::updateBestLanes(), and MSVehicle::updateOccupancyAndCurrentBestLane().
myDepartPos
double MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 481 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), and MSVehicle::saveState().
myDeparture
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 478 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), MEVehicle::loadState(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), MEVehicle::saveState(), and MSVehicle::saveState().
myDevices
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 475 of file MSBaseVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::createDevice(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDeviceParameter(), MSBaseVehicle::getDevices(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::hasDevice(), MSBaseVehicle::MSBaseVehicle(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::setDeviceParameter(), and MSBaseVehicle::~MSBaseVehicle().
myEmptyLaneVector
std::vector< MSLane * > MSVehicle::myEmptyLaneVector static protected inherited
Definition at line 1709 of file MSVehicle.h.
Referenced by MSVehicle::getBestLanesContinuation().
myEmptyTransportableVector
std::vector< MSTransportable * > MSVehicle::myEmptyTransportableVector static protected inherited
Definition at line 1710 of file MSVehicle.h.
Referenced by MSVehicle::getContainers(), and MSVehicle::getPersons().
myFurtherLanes
std::vector<MSLane*> MSVehicle::myFurtherLanes protected inherited
The information into which lanes the vehicle laps into.
Definition at line 1725 of file MSVehicle.h.
Referenced by MSVehicle::computeAngle(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSVehicle::getBackLane(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getFurtherLanes(), MSVehicle::getLatOffset(), getPreviousLane(), MSVehicle::leaveLane(), MSVehicle::onFurtherEdge(), MSVehicle::processLaneAdvances(), MSVehicle::validatePosition(), and MSVehicle::~MSVehicle().
myFurtherLanesPosLat
std::vector<double> MSVehicle::myFurtherLanesPosLat protected inherited
lateral positions on further lanes
Definition at line 1727 of file MSVehicle.h.
Referenced by MSVehicle::computeAngle(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getFurtherLanesPosLat(), MSVehicle::getLatOffset(), MSVehicle::leaveLane(), MSVehicle::setAngle(), and MSVehicle::~MSVehicle().
myHaveToWaitOnNextLink
bool MSVehicle::myHaveToWaitOnNextLink protected inherited
Definition at line 1741 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::processLinkAproaches().
myLane
MSLane* MSVehicle::myLane protected inherited
The lane the vehicle is on.
Definition at line 1690 of file MSVehicle.h.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSVehicle::checkLinkLeader(), MSVehicle::checkRewindLinkLanes(), MSVehicle::computeAngle(), drawAction_drawRailCarriages(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSVehicle::getBackLane(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getDistanceToPosition(), MSVehicle::getLane(), MSVehicle::getLaneIndex(), MSVehicle::getLateralOverlap(), MSVehicle::getLatOffset(), MSVehicle::getLeader(), getLeftSublaneOnEdge(), MSVehicle::getMaxSpeedOnLane(), getParameterWindow(), MSVehicle::getPosition(), MSVehicle::getRerouteOrigin(), MSVehicle::getRightSideOnLane(), getRightSublaneOnEdge(), MSVehicle::getSlope(), MSVehicle::influenceChangeDecision(), MSVehicle::isFrontOnLane(), MSVehicle::isStoppedOnLane(), MSVehicle::lateralDistanceToLane(), MSVehicle::leaveLane(), MSVehicle::passingMinor(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::replaceParkingArea(), MSVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), selectBlockingFoes(), MSVehicle::setTentativeLaneAndPosition(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateBestLanes(), MSVehicle::updateDriveItems(), MSVehicle::updateState(), and MSVehicle::updateTimeLoss().
myLaneChangeModel
MSAbstractLaneChangeModel* MSVehicle::myLaneChangeModel protected inherited
Definition at line 1692 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getLaneChangeModel(), MSVehicle::MSVehicle(), and MSVehicle::~MSVehicle().
myLastActionTime
SUMOTime MSVehicle::myLastActionTime protected inherited
Action offset (actions are taken at time myActionOffset + N*getActionStepLength()) Initialized to 0, to be set at insertion.
Definition at line 1685 of file MSVehicle.h.
Referenced by MSVehicle::checkActionStep(), MSVehicle::enterLaneAtInsertion(), MSVehicle::getLastActionTime(), MSVehicle::isActionStep(), MSVehicle::loadState(), MSVehicle::resetActionOffset(), MSVehicle::saveState(), and MSVehicle::updateActionOffset().
myLastBestLanesEdge
const MSEdge* MSVehicle::myLastBestLanesEdge protected inherited
Definition at line 1694 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtMove(), MSVehicle::replaceRoute(), and MSVehicle::updateBestLanes().
myLastBestLanesInternalLane
const MSLane* MSVehicle::myLastBestLanesInternalLane protected inherited
Definition at line 1695 of file MSVehicle.h.
Referenced by MSVehicle::replaceRoute(), and MSVehicle::updateBestLanes().
myLFLinkLanes
DriveItemVector MSVehicle::myLFLinkLanes protected inherited
Definition at line 1814 of file MSVehicle.h.
Referenced by drawAction_drawLinkItems(), MSVehicle::executeMove(), MSVehicle::MSVehicle(), MSVehicle::onRemovalFromNet(), MSVehicle::passingMinor(), MSVehicle::planMove(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::removePassedDriveItems(), selectBlockingFoes(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateDriveItems(), and MSVehicle::~MSVehicle().
myLock
MFXMutex GUIBaseVehicle::myLock mutable protected inherited
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 349 of file GUIBaseVehicle.h.
Referenced by drawBestLanes(), and GUIBaseVehicle::~GUIBaseVehicle().
myMoveReminders
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Currently relevant move reminders.
Definition at line 471 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), MSVehicle::leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and MSVehicle::workOnMoveReminders().
myNextDriveItem
DriveItemVector::iterator MSVehicle::myNextDriveItem protected inherited
iterator pointing to the next item in myLFLinkLanes
Note
This is updated whenever the vehicle advances to a subsequent lane (see processLaneAdvances()) and used for inter-actionpoint actualization of myLFLinkLanes (i.e. deletion of passed items) in planMove().
Definition at line 1820 of file MSVehicle.h.
Referenced by MSVehicle::executeMove(), MSVehicle::MSVehicle(), MSVehicle::planMove(), MSVehicle::processLaneAdvances(), MSVehicle::removePassedDriveItems(), and MSVehicle::updateDriveItems().
myNumberReroutes
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 490 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), MSVehicle::replaceRoute(), and MEVehicle::replaceRoute().
myParameter
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This vehicle's parameter.
Definition at line 445 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSVehicle::addTraciStop(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::createDevice(), MSVehicle::enterLaneAtMove(), MSVehicle::getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), MSVehicle::getPersonNumber(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::replaceParkingArea(), MSBaseVehicle::reroute(), MEVehicle::saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSVehicle::updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
myPersonDevice
MSDevice_Transportable* MSVehicle::myPersonDevice protected inherited
The passengers this vehicle may have.
Definition at line 1716 of file MSVehicle.h.
Referenced by MSVehicle::addPerson(), drawAction_drawPersonsAndContainers(), getNumPassengers(), MSVehicle::getPersonNumber(), MSVehicle::getPersons(), MSVehicle::processNextStop(), and MSVehicle::removeTransportable().
myRoute
const MSRoute* MSBaseVehicle::myRoute protected inherited
This vehicle's route.
Definition at line 448 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), drawRouteHelper(), MSVehicle::getDistanceToPosition(), MSVehicle::getRerouteOrigin(), MSBaseVehicle::getRoute(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and MSBaseVehicle::~MSBaseVehicle().
mySeatPositions
PositionVector GUIBaseVehicle::mySeatPositions mutable protected inherited
positions of seats in the vehicle (updated at every drawing step)
Definition at line 352 of file GUIBaseVehicle.h.
Referenced by computeSeats(), drawAction_drawRailCarriages(), GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getSeatPosition(), and GUIBaseVehicle::GUIBaseVehicle().
mySignals
int MSVehicle::mySignals protected inherited
State of things of the vehicle that can be on or off.
Definition at line 1730 of file MSVehicle.h.
Referenced by MSVehicle::getSignals(), MSVehicle::setBlinkerInformation(), MSVehicle::signalSet(), MSVehicle::switchOffSignal(), and MSVehicle::switchOnSignal().
myState
State MSVehicle::myState protected inherited
This Vehicles driving state (pos and speed)
Definition at line 1679 of file MSVehicle.h.
Referenced by MSVehicle::adaptToLeaders(), MSVehicle::addStop(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeToNewLane(), MSVehicle::checkRewindLinkLanes(), MSVehicle::computeAngle(), MSVehicle::congested(), MSLaneChanger::continueChange(), drawAction_drawRailCarriages(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSVehicle::fixPosition(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getDeltaPos(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getLastStepDist(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getLatOffset(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPosition(), MSVehicle::getPositionAlongBestLanes(), MSVehicle::getPositionOnLane(), MSVehicle::getPreviousSpeed(), MSVehicle::getRerouteOrigin(), MSVehicle::getRightSideOnLane(), MSVehicle::getSpeed(), MSVehicle::getSpeedWithoutTraciInfluence(), MSVehicle::getVelocityVector(), MSVehicle::hasArrived(), MSVehicle::leaveLane(), MSVehicle::loadState(), MSVehicle::overlap(), MSVehicle::planMoveInternal(), MSVehicle::processLaneAdvances(), MSVehicle::processLinkAproaches(), MSVehicle::processNextStop(), MSVehicle::processTraCISpeedControl(), MSVehicle::saveState(), MSVehicle::setTentativeLaneAndPosition(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::updateFurtherLanes(), and MSVehicle::updateState().
myStopDist
double MSVehicle::myStopDist protected inherited
distance to the next stop or -1 if there is none
Definition at line 1747 of file MSVehicle.h.
Referenced by MSVehicle::nextStopDist(), and MSVehicle::planMove().
myStops
std::list<Stop> MSVehicle::myStops protected inherited
The vehicle's list of stops.
Definition at line 1713 of file MSVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSVehicle::addStop(), MSVehicle::addTraciStop(), MSVehicle::addTraciStopAtStoppingPlace(), MSVehicle::collisionStopTime(), MSVehicle::computeAngle(), drawRouteHelper(), MSVehicle::getNextParkingArea(), MSVehicle::getNextStop(), MSVehicle::getPosition(), MSVehicle::getStopEdges(), getStopInfo(), MSVehicle::hasArrived(), MSVehicle::hasStops(), MSVehicle::isParking(), MSVehicle::isStopped(), MSVehicle::isStoppedInRange(), MSVehicle::isStoppedOnLane(), MSVehicle::isStoppedTriggered(), MSVehicle::keepStopping(), MSVehicle::leaveLane(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), MSVehicle::replaceParkingArea(), MSVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), MSVehicle::saveState(), and MSVehicle::updateBestLanes().
myTimeLoss
double MSVehicle::myTimeLoss protected inherited
the time loss in seconds due to driving with less than maximum speed
Definition at line 1676 of file MSVehicle.h.
Referenced by MSVehicle::getTimeLoss(), MSVehicle::getTimeLossSeconds(), and MSVehicle::updateTimeLoss().
myType
MSVehicleType* MSBaseVehicle::myType protected inherited
This vehicle's type.
Definition at line 451 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getActionStepLength(), MSVehicle::getActionStepLengthSecs(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getCarFollowModel(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSBaseVehicle::getLength(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getMaxSpeedOnLane(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getSingularType(), GUIMEVehicle::getTypeParameterWindow(), getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::getWidth(), MSBaseVehicle::hasValidRoute(), MSVehicle::processNextStop(), MSBaseVehicle::replaceVehicleType(), MSVehicle::updateBestLanes(), and MSVehicle::~MSVehicle().
myWaitingTime
SUMOTime MSVehicle::myWaitingTime protected inherited
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
Definition at line 1669 of file MSVehicle.h.
Referenced by MSVehicle::getWaitingSeconds(), MSVehicle::getWaitingTime(), MSVehicle::leaveLane(), MSVehicle::loadState(), MSVehicle::resumeFromStopping(), MSVehicle::saveState(), and MSVehicle::updateWaitingTime().
myWaitingTimeCollector
WaitingTimeCollector MSVehicle::myWaitingTimeCollector protected inherited
Definition at line 1673 of file MSVehicle.h.
Referenced by MSVehicle::getAccumulatedWaitingTime(), and MSVehicle::updateWaitingTime().
NOT_YET_DEPARTED
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 495 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::hasDeparted(), and MSVehicle::Influencer::postProcessRemoteControl().
TypeNames
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 75 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIVehicle.h
GUIVehicle.cpp