SUMO - Simulation of Urban MObility: GNETLSEditorFrame Class Reference
GNETLSEditorFrame Class Reference
#include <GNETLSEditorFrame.h>
Data Structures
class TLSAttributes
FOX-declaration.
Public Member Functions
bool controlsEdge (GNEEdge &edge) const
whether the given edge is controlled by the currently edited tlDef
void editJunction (GNEJunction *junction)
edits the traffic light for the given junction
void focusUpperElement ()
focus upper element of frame
GNEFrame::DrawingMode * getDrawingMode () const
get drawing mode editor
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEFrame::GEOAttributes * getGEOAttributes () const
get GEO Parameters editor
GNEFrame::NeteditAttributes * getNeteditAttributes () const
get netedit attributes editor
GNEViewNet * getViewNet () const
get view net
GNETLSEditorFrame (FXHorizontalFrame *horizontalFrameParent, GNEViewNet *viewNet)
Constructor.
void handleChange (GNEInternalLane *lane)
update phase definition for the current traffic light and phase
void handleMultiChange (GNELane *lane, FXObject *obj, FXSelector sel, void *data)
update phase definition for the current traffic light and phase
virtual void hide ()
hide Frame
void setFrameWidth (int newWidth)
set width of GNEFrame
virtual void show ()
show Frame
~GNETLSEditorFrame ()
Destructor.
FOX-callbacks
Called when the user presses the OK-Button
Note
saves any modifications
long onCmdOK (FXObject *, FXSelector, void *)
long onCmdCancel (FXObject *, FXSelector, void *)
Called when the user presses the Cancel-button.
long onCmdToggle (FXObject *, FXSelector, void *)
Called when the user presses the button Toogle.
long onCmdGuess (FXObject *, FXSelector, void *)
Called when the user presses the button Guess.
long onCmdDefCreate (FXObject *, FXSelector, void *)
Called when the user creates a TLS.
long onCmdDefDelete (FXObject *, FXSelector, void *)
Called when the user deletes a TLS.
long onCmdDefOffset (FXObject *, FXSelector, void *)
Called when the user changes the offset of a TLS.
long onCmdDefSwitch (FXObject *, FXSelector, void *)
Called when the user switchs a TLS.
long onCmdDefRename (FXObject *, FXSelector, void *)
Called when the user renames a TLS.
long onCmdDefSubRename (FXObject *, FXSelector, void *)
Called when the user sub-renames a TLS.
long onCmdDefAddOff (FXObject *, FXSelector, void *)
Called when the user adds a OFF.
long onCmdPhaseSwitch (FXObject *, FXSelector, void *)
Called when the user switchs a Phase.
long onCmdPhaseCreate (FXObject *, FXSelector, void *)
Called when the user creates a Phase.
long onCmdPhaseDelete (FXObject *, FXSelector, void *)
Called when the user deletes a Phase.
long onCmdCleanup (FXObject *, FXSelector, void *)
Called when the user cleans up states.
long onCmdPhaseEdit (FXObject *, FXSelector, void *)
Called when the user edits a Phase.
long onCmdMakeRILSAConforming (FXObject *, FXSelector, void *)
Called when the user makes RILSA.
long onUpdDefSwitch (FXObject *, FXSelector, void *)
Called when occurs an update of switch definition.
long onUpdNeedsDef (FXObject *, FXSelector, void *)
Called when occurs an update of needs definition.
long onUpdNeedsDefAndPhase (FXObject *, FXSelector, void *)
Called when occurs an update of needs definition an dphase.
long onUpdDefCreate (FXObject *, FXSelector, void *)
Called when occurs an update of create definition.
long onUpdModified (FXObject *, FXSelector, void *)
Called when occurs an update of modified.
Protected Member Functions
GNETLSEditorFrame ()
FOX needs this.
Static Protected Member Functions
static SUMOTime getSUMOTime (const FXString &string)
converts to SUMOTime
Protected Attributes
FXVerticalFrame * myContentFrame
Vertical frame that holds all widgets of frame.
GNEFrame::DrawingMode * myDrawingMode
drawing mode
GNEFrame::GEOAttributes * myGEOAttributes
GEO Parameters.
FXHorizontalFrame * myHeaderFrame
fame for header elements
FXHorizontalFrame * myHeaderLeftFrame
fame for left header elements
FXHorizontalFrame * myHeaderRightFrame
fame for right header elements
GNEFrame::NeteditAttributes * myNeteditAttributes
Netedit parameter.
GNEViewNet * myViewNet
View Net for changes.
Private Types
typedef std::map< int, std::vector< GNEInternalLane * > > TLIndexMap
the internal lanes belonging the the current junction indexed by their tl-index
Private Member Functions
void buildIinternalLanes (NBTrafficLightDefinition *tlDef)
builds internal lanes for the given tlDef
void cleanup ()
cleans up previous lanes
const std::vector< NBTrafficLightLogic::PhaseDefinition > & getPhases ()
the phase of the current traffic light
void initPhaseTable (int index=0)
initialies the phase table
void updateCycleDuration ()
recomputes cycle duration and updates label
void updateDescription () const
update descrition
Static Private Member Functions
static std::string varDurString (SUMOTime dur)
convert duration (potentially undefined) to string
Private Attributes
GNEJunction * myCurrentJunction
the junction of the tls is being modified
FXLabel * myCycleDuration
label with the cycle duration
FXButton * myDeleteSelectedPhaseButton
delete phase button
FXButton * myDeleteTLProgram
button for delete traffic light program
FXButton * myDiscardModificationsButtons
button for cancel modifications
NBLoadedSUMOTLDef * myEditedDef
the traffic light definition being edited
FXGroupBox * myGroupBoxJunction
groupbox for current junction
FXGroupBox * myGroupBoxModifications
groupbox for buttons modifications
FXGroupBox * myGroupBoxPhases
groupbox for phases
FXGroupBox * myGroupBoxTLSDef
groupbox for TLS Definition buttons
bool myHaveModifications
whether the current tls was modified
FXButton * myInsertDuplicateButton
insert new phase button
TLIndexMap myInternalLanes
FXLabel * myLabelJunctionID
label for junction ID
FXLabel * myLabelJunctionStatus
label for junction status
FXButton * myNewTLProgram
button for create new Traffic light program
int myPhaseIndex
index of the phase being shown
FXTable * myPhaseTable
table for selecting and rearranging phases and for changing duration
FXButton * mySaveModificationsButtons
button for save modifications
FXFont * myTableFont
font for the phase table
FXScrollWindow * myTableScroll
window for oversized phase tables
FXTextField * myTextFieldJunctionID
text field for junction ID
FXTextField * myTextFieldJunctionStatus
text field for junction status
TLSAttributes * myTLSAttributes
TLS attributes.
Detailed Description
The Widget for modifying selections of network-elements
Definition at line 50 of file GNETLSEditorFrame.h.
Member Typedef Documentation
TLIndexMap
typedef std::map<int, std::vector<GNEInternalLane*> > GNETLSEditorFrame::TLIndexMap private
the internal lanes belonging the the current junction indexed by their tl-index
Definition at line 293 of file GNETLSEditorFrame.h.
Constructor & Destructor Documentation
GNETLSEditorFrame() [1/2]
GNETLSEditorFrame::GNETLSEditorFrame (FXHorizontalFrame * horizontalFrameParent, GNEViewNet * viewNet)
Constructor.
parent FXHorizontalFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 94 of file GNETLSEditorFrame.cpp.
References GUIDesignAuxiliarHorizontalFrame, GUIDesignButton, GUIDesignGroupBoxFrame, GUIDesignLabelAttribute, GUIDesignLabelLeft, GUIDesignTableLimitedHeight, GUIDesignTextField, GUIDesignTextFieldNCol, MID_CANCEL, MID_GNE_TLSFRAME_CLEANUP, MID_GNE_TLSFRAME_CREATE, MID_GNE_TLSFRAME_DELETE, MID_GNE_TLSFRAME_PHASE_CREATE, MID_GNE_TLSFRAME_PHASE_DELETE, MID_GNE_TLSFRAME_PHASE_TABLE, MID_GNE_TLSFRAME_SELECT_JUNCTION, MID_GNE_TLSFRAME_UPDATE_STATUS, and MID_OK.
~GNETLSEditorFrame()
GNETLSEditorFrame::~GNETLSEditorFrame ()
Destructor.
Definition at line 169 of file GNETLSEditorFrame.cpp.
References cleanup(), and myTableFont.
GNETLSEditorFrame() [2/2]
GNETLSEditorFrame::GNETLSEditorFrame () inline protected
FOX needs this.
Definition at line 223 of file GNETLSEditorFrame.h.
References getSUMOTime().
Member Function Documentation
buildIinternalLanes()
void GNETLSEditorFrame::buildIinternalLanes (NBTrafficLightDefinition * tlDef) private
builds internal lanes for the given tlDef
Definition at line 522 of file GNETLSEditorFrame.cpp.
References SUMORTree::addAdditionalGLObject(), NBNode::computeInternalLaneShape(), NBTrafficLightDefinition::getControlledLinks(), NBNode::getCrossings(), Named::getID(), GNEJunction::getNBNode(), GNEViewNet::getNet(), GNENet::getVisualisationSpeedUp(), myCurrentJunction, myInternalLanes, GNEFrame::myViewNet, NUM_POINTS, SUMORTree::removeAdditionalGLObject(), and toString().
Referenced by cleanup(), and onCmdDefSwitch().
cleanup()
void GNETLSEditorFrame::cleanup () private
cleans up previous lanes
Definition at line 503 of file GNETLSEditorFrame.cpp.
References buildIinternalLanes(), GNETLSEditorFrame::TLSAttributes::clearTLSAttributes(), initPhaseTable(), myCurrentJunction, myCycleDuration, myEditedDef, myHaveModifications, myTLSAttributes, GNEJunction::selectTLS(), and updateDescription().
Referenced by onCmdCancel(), onCmdOK(), and ~GNETLSEditorFrame().
controlsEdge()
bool GNETLSEditorFrame::controlsEdge (GNEEdge & edge) const
whether the given edge is controlled by the currently edited tlDef
Definition at line 662 of file GNETLSEditorFrame.cpp.
References NBTrafficLightDefinition::getControlledLinks(), GUIGlObject::getMicrosimID(), and myEditedDef.
Referenced by GNELane::getPopUpMenu().
editJunction()
void GNETLSEditorFrame::editJunction (GNEJunction * junction)
edits the traffic light for the given junction
Parameters
[in] junction The junction of which the traffic light shall be edited
Definition at line 176 of file GNETLSEditorFrame.cpp.
References GNEViewNet::getUndoList(), GNETLSEditorFrame::TLSAttributes::initTLSAttributes(), myCurrentJunction, myHaveModifications, myTLSAttributes, GNEFrame::myViewNet, onCmdCancel(), GNEUndoList::p_begin(), GNEJunction::selectTLS(), GNEViewNet::setStatusBarText(), and updateDescription().
Referenced by onCmdDefCreate(), and GNEViewNet::onLeftBtnPress().
focusUpperElement()
void GNEFrame::focusUpperElement () inherited
focus upper element of frame
Definition at line 540 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEViewNet::hotkeyFocusFrame(), GNEViewNet::onLeftBtnPress(), GNEViewNet::setEditMode(), and GNEViewNet::updateModeSpecificControls().
getDrawingMode()
GNEFrame::DrawingMode * GNEFrame::getDrawingMode () const inherited
get drawing mode editor
Definition at line 609 of file GNEFrame.cpp.
References GNEFrame::myDrawingMode.
Referenced by GNEViewNet::abortOperation(), GNEViewNet::doPaintGL(), GNEViewNet::hotkeyEnter(), GNEViewNet::onRightBtnPress(), and GNEViewNet::onRightBtnRelease().
getFrameHeaderFont()
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 583 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
getFrameHeaderLabel()
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 577 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspectMultisection().
getGEOAttributes()
GNEFrame::GEOAttributes * GNEFrame::getGEOAttributes () const inherited
get GEO Parameters editor
Definition at line 599 of file GNEFrame.cpp.
References GNEFrame::myGEOAttributes.
getNeteditAttributes()
GNEFrame::NeteditAttributes * GNEFrame::getNeteditAttributes () const inherited
get netedit attributes editor
Definition at line 589 of file GNEFrame.cpp.
References GNEFrame::myNeteditAttributes.
Referenced by GNEFrame::DrawingMode::stopDrawing().
getPhases()
const std::vector< NBTrafficLightLogic::PhaseDefinition > & GNETLSEditorFrame::getPhases () private
the phase of the current traffic light
Definition at line 595 of file GNETLSEditorFrame.cpp.
References NBLoadedSUMOTLDef::getLogic(), NBTrafficLightLogic::getPhases(), and myEditedDef.
Referenced by handleChange(), initPhaseTable(), onCmdPhaseEdit(), onCmdPhaseSwitch(), and updateCycleDuration().
getSUMOTime()
SUMOTime GNETLSEditorFrame::getSUMOTime (const FXString & string) static protected
converts to SUMOTime
Definition at line 676 of file GNETLSEditorFrame.cpp.
References TIME2STEPS.
Referenced by GNETLSEditorFrame::TLSAttributes::getOffset(), GNETLSEditorFrame(), onCmdPhaseCreate(), and onCmdPhaseEdit().
getViewNet()
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 571 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEFrame::DrawingMode::abortDrawing(), GNECrossingFrame::edgesSelector::enableEdgeSelector(), GNEInspectorFrame::NeteditParameters::onCmdChangeAdditionalParent(), GNEInspectorFrame::AttributeInput::onCmdSetAttribute(), GNECrossingFrame::crossingParameters::onCmdSetAttribute(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingMovement(), GNEInspectorFrame::NeteditParameters::onCmdSetBlockingShape(), GNEInspectorFrame::NeteditParameters::onCmdSetClosingShape(), GNEFrame::GEOAttributes::onCmdSetGEOAttribute(), GNEFrame::GEOAttributes::onCmdUseGEOParameters(), GNEDeleteFrame::removeAttributeCarrier(), GNECrossingFrame::edgesSelector::restoreEdgeColors(), and GNEFrame::DrawingMode::stopDrawing().
handleChange()
void GNETLSEditorFrame::handleChange (GNEInternalLane * lane)
update phase definition for the current traffic light and phase
Definition at line 601 of file GNETLSEditorFrame.cpp.
References GNEViewNet::changeAllPhases(), GNEInternalLane::getLinkState(), NBLoadedSUMOTLDef::getLogic(), getPhases(), GNEInternalLane::getTLIndex(), initPhaseTable(), myEditedDef, myHaveModifications, myPhaseTable, GNEFrame::myViewNet, and NBTrafficLightLogic::setPhaseState().
Referenced by GNEInternalLane::onDefault().
handleMultiChange()
void GNETLSEditorFrame::handleMultiChange (GNELane * lane, FXObject * obj, FXSelector sel, void * data)
update phase definition for the current traffic light and phase
Definition at line 617 of file GNETLSEditorFrame.cpp.
References NBTrafficLightDefinition::getControlledLinks(), GUIGlObject::getGlID(), GNEEdge::getLanes(), GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNELane::getParentEdge(), GLO_EDGE, GLO_LANE, gSelected, GUISelectedStorage::isSelected(), myEditedDef, myHaveModifications, myInternalLanes, GNEFrame::myViewNet, GNENet::retrieveEdges(), and GNENet::retrieveLanes().
Referenced by GNELane::onDefault().
hide()
void GNEFrame::hide () virtual inherited
hide Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNECrossingFrame, and GNESelectorFrame.
Definition at line 555 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNESelectorFrame::hide(), GNECrossingFrame::hide(), GNEAdditionalFrame::AdditionalAttributes::hideAdditionalParameters(), GNEAdditionalFrame::SelectorParentLanes::hideList(), GNEAdditionalFrame::SelectorParentAdditional::hideListOfAdditionals(), GNEAdditionalFrame::AdditionalAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributeSingle::hideParameter(), GNEPolygonFrame::ShapeAttributes::hideShapeParameters(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), and GNEDeleteFrame::removeAttributeCarrier().
initPhaseTable()
void GNETLSEditorFrame::initPhaseTable (int index = 0) private
initialies the phase table
Parameters
[in] index The index to select
Definition at line 562 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions(), getPhases(), NBTrafficLightDefinition::getType(), myEditedDef, myPhaseTable, myTableScroll, myTLSAttributes, STEPS2TIME, TLTYPE_STATIC, toString(), and varDurString().
Referenced by cleanup(), handleChange(), onCmdCleanup(), onCmdDefSwitch(), onCmdPhaseCreate(), and onCmdPhaseDelete().
onCmdCancel()
long GNETLSEditorFrame::onCmdCancel (FXObject * , FXSelector , void *)
Called when the user presses the Cancel-button.
Note
discards any modifications
Definition at line 191 of file GNETLSEditorFrame.cpp.
References cleanup(), GNEViewNet::getUndoList(), myCurrentJunction, GNEFrame::myViewNet, and GNEUndoList::p_abort().
Referenced by GNEViewNet::abortOperation(), editJunction(), onCmdDefCreate(), onCmdDefDelete(), onCmdDefSwitch(), and onCmdOK().
onCmdCleanup()
long GNETLSEditorFrame::onCmdCleanup (FXObject * , FXSelector , void *)
Called when the user cleans up states.
Definition at line 407 of file GNETLSEditorFrame.cpp.
References NBLoadedSUMOTLDef::cleanupStates(), initPhaseTable(), myEditedDef, myHaveModifications, and myPhaseTable.
onCmdDefAddOff()
long GNETLSEditorFrame::onCmdDefAddOff (FXObject * , FXSelector , void *)
Called when the user adds a OFF.
Definition at line 345 of file GNETLSEditorFrame.cpp.
onCmdDefCreate()
long GNETLSEditorFrame::onCmdDefCreate (FXObject * , FXSelector , void *)
Called when the user creates a TLS.
Definition at line 225 of file GNETLSEditorFrame.cpp.
References editJunction(), GNEJunction::getAttribute(), GNEViewNet::getUndoList(), myCurrentJunction, GNEFrame::myViewNet, NODETYPE_TRAFFIC_LIGHT, onCmdCancel(), GNEJunction::setAttribute(), SUMO_ATTR_TYPE, and toString().
onCmdDefDelete()
long GNETLSEditorFrame::onCmdDefDelete (FXObject * , FXSelector , void *)
Called when the user deletes a TLS.
Definition at line 239 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::TLSAttributes::getCurrentTLSDefinition(), GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions(), GNEViewNet::getUndoList(), myCurrentJunction, myTLSAttributes, GNEFrame::myViewNet, NODETYPE_PRIORITY, onCmdCancel(), GNEJunction::setAttribute(), SUMO_ATTR_TYPE, and toString().
onCmdDefOffset()
long GNETLSEditorFrame::onCmdDefOffset (FXObject * , FXSelector , void *)
Called when the user changes the offset of a TLS.
Definition at line 325 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::TLSAttributes::getOffset(), myEditedDef, myHaveModifications, myTLSAttributes, and NBLoadedSUMOTLDef::setOffset().
onCmdDefRename()
long GNETLSEditorFrame::onCmdDefRename (FXObject * , FXSelector , void *)
Called when the user renames a TLS.
Definition at line 333 of file GNETLSEditorFrame.cpp.
onCmdDefSubRename()
long GNETLSEditorFrame::onCmdDefSubRename (FXObject * , FXSelector , void *)
Called when the user sub-renames a TLS.
Definition at line 339 of file GNETLSEditorFrame.cpp.
onCmdDefSwitch()
long GNETLSEditorFrame::onCmdDefSwitch (FXObject * , FXSelector , void *)
Called when the user switchs a TLS.
Definition at line 254 of file GNETLSEditorFrame.cpp.
References buildIinternalLanes(), GNENet::computeJunction(), GNETLSEditorFrame::TLSAttributes::getCurrentTLSDefinition(), NBLoadedSUMOTLDef::getLogic(), NBTrafficLightLogicCont::getLogic(), GNEViewNet::getNet(), GNETLSEditorFrame::TLSAttributes::getNumberOfPrograms(), GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions(), NBTrafficLightLogic::getOffset(), GNENet::getTLLogicCont(), initPhaseTable(), myCurrentJunction, myCycleDuration, myEditedDef, myTLSAttributes, GNEFrame::myViewNet, onCmdCancel(), GNETLSEditorFrame::TLSAttributes::setOffset(), GNEViewNet::setStatusBarText(), and updateCycleDuration().
Referenced by GNETLSEditorFrame::TLSAttributes::initTLSAttributes().
onCmdGuess()
long GNETLSEditorFrame::onCmdGuess (FXObject * , FXSelector , void *)
Called when the user presses the button Guess.
Definition at line 351 of file GNETLSEditorFrame.cpp.
onCmdMakeRILSAConforming()
long GNETLSEditorFrame::onCmdMakeRILSAConforming (FXObject * , FXSelector , void *)
Called when the user makes RILSA.
onCmdOK()
long GNETLSEditorFrame::onCmdOK (FXObject * , FXSelector , void *)
Definition at line 202 of file GNETLSEditorFrame.cpp.
References cleanup(), GNETLSEditorFrame::TLSAttributes::getCurrentTLSDefinition(), GNEViewNet::getNet(), NBTrafficLightDefinition::getNodes(), GNEViewNet::getUndoList(), myCurrentJunction, myEditedDef, myHaveModifications, myTLSAttributes, GNEFrame::myViewNet, onCmdCancel(), GNEUndoList::p_end(), and GNENet::retrieveJunction().
Referenced by GNEViewNet::hotkeyEnter().
onCmdPhaseCreate()
long GNETLSEditorFrame::onCmdPhaseCreate (FXObject * , FXSelector , void *)
Called when the user creates a Phase.
Definition at line 378 of file GNETLSEditorFrame.cpp.
References NBTrafficLightLogic::addStep(), NBLoadedSUMOTLDef::getLogic(), getSUMOTime(), NBTrafficLightDefinition::getType(), initPhaseTable(), MAX2(), myEditedDef, myHaveModifications, myPhaseTable, and TLTYPE_STATIC.
onCmdPhaseDelete()
long GNETLSEditorFrame::onCmdPhaseDelete (FXObject * , FXSelector , void *)
Called when the user deletes a Phase.
Definition at line 396 of file GNETLSEditorFrame.cpp.
References NBTrafficLightLogic::deletePhase(), NBLoadedSUMOTLDef::getLogic(), initPhaseTable(), MAX2(), myEditedDef, myHaveModifications, and myPhaseTable.
onCmdPhaseEdit()
long GNETLSEditorFrame::onCmdPhaseEdit (FXObject * , FXSelector , void * ptr)
Called when the user edits a Phase.
Definition at line 416 of file GNETLSEditorFrame.cpp.
References NBTrafficLightLogic::addStep(), NBTrafficLightLogic::deletePhase(), NBLoadedSUMOTLDef::getLogic(), getPhases(), getSUMOTime(), NBTrafficLightDefinition::getType(), myEditedDef, myHaveModifications, myPhaseTable, onCmdPhaseSwitch(), StringUtils::prune(), NBTrafficLightLogic::setPhaseDuration(), NBTrafficLightLogic::setPhaseMaxDuration(), NBTrafficLightLogic::setPhaseMinDuration(), STEPS2TIME, TLTYPE_STATIC, toString(), NBTrafficLightDefinition::UNSPECIFIED_DURATION, updateCycleDuration(), and varDurString().
onCmdPhaseSwitch()
long GNETLSEditorFrame::onCmdPhaseSwitch (FXObject * , FXSelector , void *)
Called when the user switchs a Phase.
Definition at line 357 of file GNETLSEditorFrame.cpp.
References getPhases(), myInternalLanes, myPhaseTable, GNEFrame::myViewNet, and NBTrafficLightLogic::PhaseDefinition::state.
Referenced by onCmdPhaseEdit().
onCmdToggle()
long GNETLSEditorFrame::onCmdToggle (FXObject * , FXSelector , void *)
Called when the user presses the button Toogle.
onUpdDefCreate()
long GNETLSEditorFrame::onUpdDefCreate (FXObject * o, FXSelector , void *)
Called when occurs an update of create definition.
Definition at line 308 of file GNETLSEditorFrame.cpp.
References myCurrentJunction, and myHaveModifications.
onUpdDefSwitch()
long GNETLSEditorFrame::onUpdDefSwitch (FXObject * o, FXSelector , void *)
Called when occurs an update of switch definition.
Definition at line 283 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions(), myHaveModifications, and myTLSAttributes.
onUpdModified()
long GNETLSEditorFrame::onUpdModified (FXObject * o, FXSelector , void *)
Called when occurs an update of modified.
Definition at line 316 of file GNETLSEditorFrame.cpp.
References myHaveModifications.
onUpdNeedsDef()
long GNETLSEditorFrame::onUpdNeedsDef (FXObject * o, FXSelector , void *)
Called when occurs an update of needs definition.
Definition at line 291 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions(), and myTLSAttributes.
onUpdNeedsDefAndPhase()
long GNETLSEditorFrame::onUpdNeedsDefAndPhase (FXObject * o, FXSelector , void *)
Called when occurs an update of needs definition an dphase.
Definition at line 299 of file GNETLSEditorFrame.cpp.
References GNETLSEditorFrame::TLSAttributes::getNumberOfTLSDefinitions(), myPhaseTable, and myTLSAttributes.
setFrameWidth()
void GNEFrame::setFrameWidth (int newWidth) inherited
set width of GNEFrame
Definition at line 564 of file GNEFrame.cpp.
References GNEFrame::myScrollWindowsContents.
show()
void GNEFrame::show () virtual inherited
show Frame
Note
some GNEFrames needs a re-implementation
Reimplemented in GNEAdditionalFrame, GNEPolygonFrame, GNEInspectorFrame, and GNESelectorFrame.
Definition at line 546 of file GNEFrame.cpp.
References GNEViewNet::getViewParent(), GNEFrame::myViewNet, and GNEViewParent::showFramesArea().
Referenced by GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::removeAttributeCarrier(), GNESelectorFrame::show(), GNEInspectorFrame::show(), GNEPolygonFrame::show(), GNEAdditionalFrame::show(), and GNEViewNet::updateModeSpecificControls().
updateCycleDuration()
void GNETLSEditorFrame::updateCycleDuration () private
recomputes cycle duration and updates label
Definition at line 683 of file GNETLSEditorFrame.cpp.
References getPhases(), myCycleDuration, STEPS2TIME, and toString().
Referenced by onCmdDefSwitch(), and onCmdPhaseEdit().
updateDescription()
void GNETLSEditorFrame::updateDescription () const private
update descrition
Definition at line 486 of file GNETLSEditorFrame.cpp.
References Named::getID(), GNEJunction::getNBNode(), NBNode::isTLControlled(), myCurrentJunction, myHaveModifications, myTextFieldJunctionID, and myTextFieldJunctionStatus.
Referenced by cleanup(), and editJunction().
varDurString()
std::string GNETLSEditorFrame::varDurString (SUMOTime dur) static private
convert duration (potentially undefined) to string
Definition at line 557 of file GNETLSEditorFrame.cpp.
References STEPS2TIME, toString(), and NBTrafficLightDefinition::UNSPECIFIED_DURATION.
Referenced by initPhaseTable(), and onCmdPhaseEdit().
Field Documentation
myContentFrame
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
Vertical frame that holds all widgets of frame.
Definition at line 340 of file GNEFrame.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNECrossingFrame::GNECrossingFrame(), GNEFrame::GNEFrame(), GNESelectorFrame::GNESelectorFrame(), and GNEInspectorFrame::inspectMultisection().
myCurrentJunction
GNEJunction* GNETLSEditorFrame::myCurrentJunction private
the junction of the tls is being modified
Definition at line 287 of file GNETLSEditorFrame.h.
Referenced by buildIinternalLanes(), cleanup(), editJunction(), onCmdCancel(), onCmdDefCreate(), onCmdDefDelete(), onCmdDefSwitch(), onCmdOK(), onUpdDefCreate(), and updateDescription().
myCycleDuration
FXLabel* GNETLSEditorFrame::myCycleDuration private
label with the cycle duration
Definition at line 269 of file GNETLSEditorFrame.h.
Referenced by cleanup(), onCmdDefSwitch(), and updateCycleDuration().
myDeleteSelectedPhaseButton
FXButton* GNETLSEditorFrame::myDeleteSelectedPhaseButton private
delete phase button
Definition at line 275 of file GNETLSEditorFrame.h.
myDeleteTLProgram
FXButton* GNETLSEditorFrame::myDeleteTLProgram private
button for delete traffic light program
Definition at line 257 of file GNETLSEditorFrame.h.
myDiscardModificationsButtons
FXButton* GNETLSEditorFrame::myDiscardModificationsButtons private
button for cancel modifications
Definition at line 281 of file GNETLSEditorFrame.h.
myDrawingMode
GNEFrame::DrawingMode* GNEFrame::myDrawingMode protected inherited
drawing mode
Definition at line 358 of file GNEFrame.h.
Referenced by GNEFrame::getDrawingMode(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myEditedDef
NBLoadedSUMOTLDef* GNETLSEditorFrame::myEditedDef private
the traffic light definition being edited
Definition at line 297 of file GNETLSEditorFrame.h.
Referenced by cleanup(), controlsEdge(), getPhases(), handleChange(), handleMultiChange(), initPhaseTable(), onCmdCleanup(), onCmdDefOffset(), onCmdDefSwitch(), onCmdOK(), onCmdPhaseCreate(), onCmdPhaseDelete(), and onCmdPhaseEdit().
myGEOAttributes
GNEFrame::GEOAttributes* GNEFrame::myGEOAttributes protected inherited
GEO Parameters.
Definition at line 355 of file GNEFrame.h.
Referenced by GNEFrame::getGEOAttributes(), GNEInspectorFrame::inspectMultisection(), and GNEInspectorFrame::AttributeInput::onCmdSetAttribute().
myGroupBoxJunction
FXGroupBox* GNETLSEditorFrame::myGroupBoxJunction private
groupbox for current junction
Definition at line 233 of file GNETLSEditorFrame.h.
myGroupBoxModifications
FXGroupBox* GNETLSEditorFrame::myGroupBoxModifications private
groupbox for buttons modifications
Definition at line 278 of file GNETLSEditorFrame.h.
myGroupBoxPhases
FXGroupBox* GNETLSEditorFrame::myGroupBoxPhases private
groupbox for phases
Definition at line 260 of file GNETLSEditorFrame.h.
myGroupBoxTLSDef
FXGroupBox* GNETLSEditorFrame::myGroupBoxTLSDef private
groupbox for TLS Definition buttons
Definition at line 251 of file GNETLSEditorFrame.h.
myHaveModifications
bool GNETLSEditorFrame::myHaveModifications private
whether the current tls was modified
Definition at line 290 of file GNETLSEditorFrame.h.
Referenced by cleanup(), editJunction(), handleChange(), handleMultiChange(), onCmdCleanup(), onCmdDefOffset(), onCmdOK(), onCmdPhaseCreate(), onCmdPhaseDelete(), onCmdPhaseEdit(), onUpdDefCreate(), onUpdDefSwitch(), onUpdModified(), and updateDescription().
myHeaderFrame
FXHorizontalFrame* GNEFrame::myHeaderFrame protected inherited
fame for header elements
Definition at line 343 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myHeaderLeftFrame
FXHorizontalFrame* GNEFrame::myHeaderLeftFrame protected inherited
fame for left header elements
Definition at line 346 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame(), GNEInspectorFrame::inspectChild(), GNEInspectorFrame::inspectFromDeleteFrame(), and GNEInspectorFrame::inspectMultisection().
myHeaderRightFrame
FXHorizontalFrame* GNEFrame::myHeaderRightFrame protected inherited
fame for right header elements
Definition at line 349 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
myInsertDuplicateButton
FXButton* GNETLSEditorFrame::myInsertDuplicateButton private
insert new phase button
Definition at line 272 of file GNETLSEditorFrame.h.
myInternalLanes
TLIndexMap GNETLSEditorFrame::myInternalLanes private
Definition at line 294 of file GNETLSEditorFrame.h.
Referenced by buildIinternalLanes(), handleMultiChange(), and onCmdPhaseSwitch().
myLabelJunctionID
FXLabel* GNETLSEditorFrame::myLabelJunctionID private
label for junction ID
Definition at line 236 of file GNETLSEditorFrame.h.
myLabelJunctionStatus
FXLabel* GNETLSEditorFrame::myLabelJunctionStatus private
label for junction status
Definition at line 242 of file GNETLSEditorFrame.h.
myNeteditAttributes
GNEFrame::NeteditAttributes* GNEFrame::myNeteditAttributes protected inherited
Netedit parameter.
Definition at line 352 of file GNEFrame.h.
Referenced by GNEPolygonFrame::buildPoly(), GNEFrame::getNeteditAttributes(), GNEPolygonFrame::onCmdSelectShape(), and GNEPolygonFrame::processClick().
myNewTLProgram
FXButton* GNETLSEditorFrame::myNewTLProgram private
button for create new Traffic light program
Definition at line 254 of file GNETLSEditorFrame.h.
myPhaseIndex
int GNETLSEditorFrame::myPhaseIndex private
index of the phase being shown
Definition at line 300 of file GNETLSEditorFrame.h.
myPhaseTable
FXTable* GNETLSEditorFrame::myPhaseTable private
table for selecting and rearranging phases and for changing duration
Definition at line 266 of file GNETLSEditorFrame.h.
Referenced by handleChange(), initPhaseTable(), onCmdCleanup(), onCmdPhaseCreate(), onCmdPhaseDelete(), onCmdPhaseEdit(), onCmdPhaseSwitch(), and onUpdNeedsDefAndPhase().
mySaveModificationsButtons
FXButton* GNETLSEditorFrame::mySaveModificationsButtons private
button for save modifications
Definition at line 284 of file GNETLSEditorFrame.h.
myTableFont
FXFont* GNETLSEditorFrame::myTableFont private
font for the phase table
Definition at line 230 of file GNETLSEditorFrame.h.
Referenced by ~GNETLSEditorFrame().
myTableScroll
FXScrollWindow* GNETLSEditorFrame::myTableScroll private
window for oversized phase tables
Definition at line 263 of file GNETLSEditorFrame.h.
Referenced by initPhaseTable().
myTextFieldJunctionID
FXTextField* GNETLSEditorFrame::myTextFieldJunctionID private
text field for junction ID
Definition at line 239 of file GNETLSEditorFrame.h.
Referenced by updateDescription().
myTextFieldJunctionStatus
FXTextField* GNETLSEditorFrame::myTextFieldJunctionStatus private
text field for junction status
Definition at line 245 of file GNETLSEditorFrame.h.
Referenced by updateDescription().
myTLSAttributes
TLSAttributes* GNETLSEditorFrame::myTLSAttributes private
TLS attributes.
Definition at line 248 of file GNETLSEditorFrame.h.
Referenced by cleanup(), editJunction(), initPhaseTable(), onCmdDefDelete(), onCmdDefOffset(), onCmdDefSwitch(), onCmdOK(), onUpdDefSwitch(), onUpdNeedsDef(), and onUpdNeedsDefAndPhase().
myViewNet
GNEViewNet* GNEFrame::myViewNet protected inherited
View Net for changes.
Definition at line 337 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEPolygonFrame::addPOI(), GNEPolygonFrame::addPOILane(), GNEPolygonFrame::addPolygon(), buildIinternalLanes(), GNEPolygonFrame::buildPoly(), GNEDeleteFrame::createPopUpMenu(), GNEInspectorFrame::createPopUpMenu(), editJunction(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), handleMultiChange(), GNEFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), onCmdCancel(), GNEDeleteFrame::onCmdCenterChildItem(), GNEInspectorFrame::onCmdCenterItem(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNECrossingFrame::onCmdCreateCrossing(), onCmdDefCreate(), onCmdDefDelete(), onCmdDefSwitch(), GNEInspectorFrame::onCmdDeleteItem(), GNEInspectorFrame::onCmdGoBack(), GNEDeleteFrame::onCmdInspectChildItem(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), onCmdOK(), onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEPolygonFrame::processClick(), GNEAdditionalFrame::removeAdditional(), GNEDeleteFrame::removeAttributeCarrier(), and GNEFrame::show().
The documentation for this class was generated from the following files:
GNETLSEditorFrame.h
GNETLSEditorFrame.cpp