SUMO - Simulation of Urban MObility: FX::FXRealSpinDialText Class Reference
FX::FXRealSpinDialText Class Reference
Public Types
enum { ID_LAST = FXTextField::ID_LAST }
enum { FLAG_FMTSTRING = 0x1 }
Public Member Functions
FXRealSpinDialText (FXComposite *p, FXint ncols, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=TEXTFIELD_NORMAL, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
Construct a text widget.
FXbool getNumberFormatExponent () const
FXint getNumberFormatPrecision () const
FXString getNumberFormatString () const
long onCmdSetRealValue (FXObject *, FXSelector, void *)
long onMotion (FXObject *, FXSelector, void *)
void setFormatString (const FXchar *fmt)
void setNumberFormat (FXint prec, FXbool bExp=FALSE)
Protected Member Functions
FXRealSpinDialText ()
Protected Attributes
FXbool exponent
FXuint flags
FXString fmtString
FXint precision
Private Member Functions
FXRealSpinDialText (const FXRealSpinDialText &)
FXRealSpinDialText & operator= (const FXRealSpinDialText &)
Detailed Description
Definition at line 330 of file FXRealSpinDial.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_LAST
Definition at line 340 of file FXRealSpinDial.cpp.
anonymous enum
anonymous enum
Enumerator
FLAG_FMTSTRING
Definition at line 343 of file FXRealSpinDial.cpp.
Constructor & Destructor Documentation
FXRealSpinDialText() [1/3]
FX::FXRealSpinDialText::FXRealSpinDialText () inline protected
Definition at line 333 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialDial::onMotion(), and FX::FXRealSpinDialDial::operator=().
FXRealSpinDialText() [2/3]
FX::FXRealSpinDialText::FXRealSpinDialText (const FXRealSpinDialText &) private
FXRealSpinDialText() [3/3]
FX::FXRealSpinDialText::FXRealSpinDialText (FXComposite * p, FXint ncols, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = TEXTFIELD_NORMAL, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD) inline
Construct a text widget.
Definition at line 349 of file FXRealSpinDial.cpp.
Member Function Documentation
getNumberFormatExponent()
FXbool FX::FXRealSpinDialText::getNumberFormatExponent () const inline
Definition at line 367 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDial::getNumberFormatExponent().
getNumberFormatPrecision()
FXint FX::FXRealSpinDialText::getNumberFormatPrecision () const inline
Definition at line 364 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDial::getNumberFormatPrecision().
getNumberFormatString()
FXString FX::FXRealSpinDialText::getNumberFormatString () const inline
Definition at line 374 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDial::getNumberFormatString().
onCmdSetRealValue()
long FX::FXRealSpinDialText::onCmdSetRealValue (FXObject * , FXSelector , void * ptr)
Definition at line 402 of file FXRealSpinDial.cpp.
References FX::FXDEFMAP(), FX::FXRealSpinDial::ID_DECREMENT, FX::FXRealSpinDial::ID_DIAL, FX::FXRealSpinDial::ID_ENTRY, FX::FXRealSpinDial::ID_INCREMENT, FX::FXRealSpinDial::onChgDial(), FX::FXRealSpinDial::onChgEntry(), FX::FXRealSpinDial::onCmdDecrement(), FX::FXRealSpinDial::onCmdEntry(), FX::FXRealSpinDial::onCmdGetIntRange(), FX::FXRealSpinDial::onCmdGetIntValue(), FX::FXRealSpinDial::onCmdGetRealRange(), FX::FXRealSpinDial::onCmdGetRealValue(), FX::FXRealSpinDial::onCmdIncrement(), FX::FXRealSpinDial::onCmdSetIntRange(), FX::FXRealSpinDial::onCmdSetIntValue(), FX::FXRealSpinDial::onCmdSetRealRange(), FX::FXRealSpinDial::onCmdSetRealValue(), FX::FXRealSpinDial::onCmdSetValue(), FX::FXRealSpinDial::onKeyPress(), FX::FXRealSpinDial::onKeyRelease(), FX::FXRealSpinDial::onMotion(), FX::FXRealSpinDial::onMouseWheel(), FX::FXRealSpinDial::onUpdDecrement(), FX::FXRealSpinDial::onUpdDial(), FX::FXRealSpinDial::onUpdEntry(), and FX::FXRealSpinDial::onUpdIncrement().
onMotion()
long FX::FXRealSpinDialText::onMotion (FXObject * o, FXSelector s, void * ptr)
Definition at line 391 of file FXRealSpinDial.cpp.
operator=()
FXRealSpinDialText& FX::FXRealSpinDialText::operator= (const FXRealSpinDialText &) private
setFormatString()
void FX::FXRealSpinDialText::setFormatString (const FXchar * fmt) inline
Definition at line 370 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDial::setFormatString().
setNumberFormat()
void FX::FXRealSpinDialText::setNumberFormat (FXint prec, FXbool bExp = FALSE) inline
Definition at line 359 of file FXRealSpinDial.cpp.
Referenced by FX::FXRealSpinDial::setNumberFormat().
Field Documentation
exponent
FXbool FX::FXRealSpinDialText::exponent protected
Definition at line 380 of file FXRealSpinDial.cpp.
flags
FXuint FX::FXRealSpinDialText::flags protected
Definition at line 382 of file FXRealSpinDial.cpp.
fmtString
FXString FX::FXRealSpinDialText::fmtString protected
Definition at line 381 of file FXRealSpinDial.cpp.
precision
FXint FX::FXRealSpinDialText::precision protected
Definition at line 379 of file FXRealSpinDial.cpp.
The documentation for this class was generated from the following file:
FXRealSpinDial.cpp